### Cell 1 — Initialize PRAGA repository and benchmark paths

In [51]:
from pathlib import Path
import shutil
import subprocess
import sys


WORK_ROOT = Path("/kaggle/working")

PRAGA_ROOT = (
    WORK_ROOT
    / "PRAGA"
)

PRAGA_OUTPUT_ROOT = (
    WORK_ROOT
    / "PRAGA_baseline"
)

DATA_ROOT = Path(
    "/kaggle/input/datasets/wuvdji/smgc-data"
)


print("=" * 100)
print("INITIALIZE PRAGA")
print("=" * 100)


# Fresh official repository
if PRAGA_ROOT.exists():

    shutil.rmtree(
        PRAGA_ROOT
    )


for name in list(sys.modules):

    if (
        name == "PRAGA"
        or name.startswith("PRAGA.")
        or name == "clustering_utils"
    ):

        del sys.modules[name]


subprocess.run(
    [
        "git",
        "clone",
        "https://github.com/Xubin-s-Lab/PRAGA.git",
        str(PRAGA_ROOT),
    ],
    check=True,
)


assert PRAGA_ROOT.exists()
assert DATA_ROOT.exists()


PRAGA_OUTPUT_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


PRAGA_COMMIT = (
    subprocess.check_output(
        [
            "git",
            "-C",
            str(PRAGA_ROOT),
            "rev-parse",
            "HEAD",
        ],
        text=True,
    )
    .strip()
)


print(
    "\nPRAGA root :",
    PRAGA_ROOT
)

print(
    "Data root  :",
    DATA_ROOT
)

print(
    "Git commit :",
    PRAGA_COMMIT
)

print(
    "\nPASS: clean PRAGA repository ready."
)

====================================================================================================
INITIALIZE PRAGA
====================================================================================================

Cloning into '/kaggle/working/PRAGA'...

PRAGA root : /kaggle/working/PRAGA
Data root  : /kaggle/input/datasets/wuvdji/smgc-data
Git commit : 4adb11c96fc7ddad800fa1787eadcc8b91b42784

PASS: clean PRAGA repository ready.

### Cell 2 — Install PRAGA runtime dependencies

In [52]:
import sys
import subprocess


print("=" * 100)
print("INSTALL PRAGA DEPENDENCIES")
print("=" * 100)


subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--prefer-binary",
        "-q",
        "anndata==0.11.4",
        "scanpy==1.11.4",
        "scikit-learn==1.6.1",
        "scikit-misc",
    ],
    check=True,
)


# ============================================================
# R mclust
# ============================================================

mclust_ok = (
    subprocess.run(
        [
            "Rscript",
            "-e",
            (
                'quit(status='
                'ifelse(requireNamespace('
                '"mclust", quietly=TRUE),0,1))'
            ),
        ]
    ).returncode
    == 0
)


if not mclust_ok:

    subprocess.run(
        [
            "Rscript",
            "-e",
            (
                'install.packages('
                '"mclust", '
                'repos="https://cloud.r-project.org")'
            ),
        ],
        check=True,
    )


print(
    "\nPASS: dependencies ready."
)

====================================================================================================
INSTALL PRAGA DEPENDENCIES
====================================================================================================

PASS: dependencies ready.

### Cell 3 — Apply minimal PRAGA source compatibility patch

In [53]:
import sys
import re
import importlib

import numpy as np
import pandas as pd
import scipy
import scanpy as sc
import anndata
import sklearn
import torch


# ============================================================
# ONLY compatibility patch:
#
# official source:
#     cuda:1
#
# Kaggle single T4:
#     cuda:0
#
# Do NOT patch AMP, optimizer, loss or preprocessing here.
# ============================================================

patched_files = []


for path in PRAGA_ROOT.rglob("*.py"):

    text = path.read_text(
        encoding="utf-8"
    )

    if "cuda:1" in text:

        path.write_text(
            text.replace(
                "cuda:1",
                "cuda:0",
            ),
            encoding="utf-8",
        )

        patched_files.append(
            str(
                path.relative_to(
                    PRAGA_ROOT
                )
            )
        )


# ============================================================
# Clear stale modules
# ============================================================

for name in list(sys.modules):

    if (
        name == "PRAGA"
        or name.startswith("PRAGA.")
        or name == "clustering_utils"
    ):

        del sys.modules[name]


repo_root = str(
    PRAGA_ROOT
)

package_root = str(
    PRAGA_ROOT
    / "PRAGA"
)


sys.path = [
    p
    for p in sys.path
    if p not in {
        repo_root,
        package_root,
    }
]


sys.path.insert(
    0,
    package_root,
)

sys.path.insert(
    0,
    repo_root,
)


importlib.invalidate_caches()


# ============================================================
# Source audit
# ============================================================

main_text = (
    PRAGA_ROOT
    / "main.py"
).read_text(
    encoding="utf-8"
)


train_text = (
    PRAGA_ROOT
    / "PRAGA"
    / "Train_model.py"
).read_text(
    encoding="utf-8"
)


cluster_text = (
    PRAGA_ROOT
    / "PRAGA"
    / "optimal_clustering_HLN.py"
).read_text(
    encoding="utf-8"
)


assert (
    "adata_peaks_normalized.h5ad"
    in main_text
)

assert (
    "n_components=51"
    in main_text
)

assert (
    "self.epochs = 30"
    in train_text
)

assert (
    "self.epochs = 300"
    in train_text
)

assert (
    "Arg(init_K=14)"
    in re.sub(
        r"\s+",
        "",
        cluster_text,
    )
)


DEVICE = torch.device(
    "cuda:0"
    if torch.cuda.is_available()
    else "cpu"
)


print("=" * 100)
print("PRAGA SOURCE / ENVIRONMENT AUDIT")
print("=" * 100)

print(
    "Python         :",
    sys.version.split()[0]
)

print(
    "PyTorch        :",
    torch.__version__
)

print(
    "CUDA available :",
    torch.cuda.is_available()
)


if torch.cuda.is_available():

    print(
        "GPU            :",
        torch.cuda.get_device_name(0)
    )


print(
    "NumPy          :",
    np.__version__
)

print(
    "SciPy          :",
    scipy.__version__
)

print(
    "Scanpy         :",
    sc.__version__
)

print(
    "AnnData        :",
    anndata.__version__
)

print(
    "sklearn        :",
    sklearn.__version__
)

print(
    "Device         :",
    DEVICE
)

print(
    "Patched files  :",
    patched_files
)


print(
    "\nPASS: only cuda:1 -> cuda:0 patched."
)

print(
    "PASS: no training or preprocessing patch applied."
)

====================================================================================================
PRAGA SOURCE / ENVIRONMENT AUDIT
====================================================================================================
Python         : 3.12.13
PyTorch        : 2.10.0+cu128
CUDA available : True
GPU            : Tesla T4
NumPy          : 2.0.2
SciPy          : 1.16.3
Scanpy         : 1.11.4
AnnData        : 0.11.4
sklearn        : 1.6.1
Device         : cuda:0
Patched files  : ['main.py', 'PRAGA/optimal_clustering_HLN.py', 'PRAGA/optimal_clustering.py']

PASS: only cuda:1 -> cuda:0 patched.
PASS: no training or preprocessing patch applied.

### Cell 4 — Define the five benchmark datasets and PRAGA settings

In [54]:
DATASET_ORDER = [
    "HLN-A1",
    "HLN-D1",
    "E18.5",
    "S2-E15",
    "S2-E18",
]


DATASET_SPECS = {

    "HLN-A1": {

        "rna":
            DATA_ROOT
            / "Human_Lymph_Nodes/A1/adata_RNA.h5ad",

        "second":
            DATA_ROOT
            / "Human_Lymph_Nodes/A1/adata_ADT.h5ad",

        "second_type":
            "ADT",

        "K":
            10,

        "n_spots":
            3484,

        "init_k":
            10,

        "KNN_k":
            20,

        "RNA_weight":
            5,

        "ADT_weight":
            5,

        "epochs":
            30,
    },


    "HLN-D1": {

        "rna":
            DATA_ROOT
            / "Human_Lymph_Nodes/D1/adata_RNA.h5ad",

        "second":
            DATA_ROOT
            / "Human_Lymph_Nodes/D1/adata_ADT.h5ad",

        "second_type":
            "ADT",

        "K":
            11,

        "n_spots":
            3359,

        "init_k":
            11,

        "KNN_k":
            20,

        "RNA_weight":
            5,

        "ADT_weight":
            5,

        "epochs":
            30,
    },


    "E18.5": {

        "rna":
            DATA_ROOT
            / "E18.5_mouse_brain/adata_RNA.h5ad",

        "second":
            DATA_ROOT
            / "E18.5_mouse_brain/adata_ATAC.h5ad",

        "second_type":
            "ATAC",

        "K":
            14,

        "n_spots":
            2129,

        "init_k":
            14,

        "KNN_k":
            20,

        "RNA_weight":
            1,

        "ADT_weight":
            10,

        "epochs":
            300,
    },


    "S2-E15": {

        "rna":
            DATA_ROOT
            / "Mouse_Embryos_S2/E15/adata_RNA.h5ad",

        "second":
            DATA_ROOT
            / "Mouse_Embryos_S2/E15/adata_ATAC.h5ad",

        "second_type":
            "ATAC",

        "K":
            15,

        "n_spots":
            1939,

        "init_k":
            14,

        "KNN_k":
            20,

        "RNA_weight":
            1,

        "ADT_weight":
            10,

        "epochs":
            300,
    },


    "S2-E18": {

        "rna":
            DATA_ROOT
            / "Mouse_Embryos_S2/E18/adata_RNA.h5ad",

        "second":
            DATA_ROOT
            / "Mouse_Embryos_S2/E18/adata_ATAC.h5ad",

        "second_type":
            "ATAC",

        "K":
            16,

        "n_spots":
            2248,

        "init_k":
            14,

        "KNN_k":
            20,

        "RNA_weight":
            1,

        "ADT_weight":
            10,

        "epochs":
            300,
    },
}


print(
    "PASS: five benchmark datasets configured."
)

PASS: five benchmark datasets configured.

### Cell 5 — Audit benchmark files, spot counts and annotations

In [55]:
def load_clean_dataset(
    dataset_name,
):

    spec = (
        DATASET_SPECS[
            dataset_name
        ]
    )


    assert spec["rna"].exists(), (
        spec["rna"]
    )

    assert spec["second"].exists(), (
        spec["second"]
    )


    rna = sc.read_h5ad(
        spec["rna"]
    )

    second = sc.read_h5ad(
        spec["second"]
    )


    rna.var_names_make_unique()
    second.var_names_make_unique()


    assert (
        rna.n_obs
        ==
        spec["n_spots"]
    )

    assert (
        second.n_obs
        ==
        spec["n_spots"]
    )


    assert np.array_equal(
        np.asarray(
            rna.obs_names
        ),
        np.asarray(
            second.obs_names
        ),
    )


    # ========================================================
    # E18.5 metadata adapter
    # Same benchmark convention used in previous notebooks
    # ========================================================

    if (
        dataset_name
        == "E18.5"
    ):

        coords = np.column_stack(
            [
                np.asarray(
                    rna.obs[
                        "array_col"
                    ],
                    dtype=np.float64,
                ),

                np.asarray(
                    rna.obs[
                        "array_row"
                    ],
                    dtype=np.float64,
                ),
            ]
        )


        labels = (
            rna.obs[
                "Combined_Clusters_annotation"
            ]
            .astype(str)
            .to_numpy()
        )


        rna.obsm[
            "spatial"
        ] = coords.copy()

        second.obsm[
            "spatial"
        ] = coords.copy()


        rna.obs[
            "Spatial_Label"
        ] = labels.copy()

        second.obs[
            "Spatial_Label"
        ] = labels.copy()


    # ========================================================
    # Audit
    # ========================================================

    assert (
        "Spatial_Label"
        in rna.obs.columns
    )

    assert (
        "spatial"
        in rna.obsm
    )

    assert (
        rna.obs[
            "Spatial_Label"
        ].nunique()
        ==
        spec["K"]
    )


    return (
        rna,
        second,
        spec,
    )


print("=" * 110)
print("FIVE-DATASET BENCHMARK AUDIT")
print("=" * 110)


for dataset_name in DATASET_ORDER:

    (
        rna,
        second,
        spec,
    ) = load_clean_dataset(
        dataset_name
    )


    print(
        f"\n{dataset_name}"
    )

    print(
        "  RNA shape        :",
        rna.shape
    )

    print(
        f"  {spec['second_type']} shape"
        f"{' ' * max(0, 7-len(spec['second_type']))}:",
        second.shape
    )

    print(
        "  spots            :",
        rna.n_obs
    )

    print(
        "  target K         :",
        spec["K"]
    )

    print(
        "  annotation K     :",
        rna.obs[
            "Spatial_Label"
        ].nunique()
    )

    print(
        "  spatial shape    :",
        np.asarray(
            rna.obsm[
                "spatial"
            ]
        ).shape
    )


print(
    "\nPASS: five benchmark datasets verified."
)

==============================================================================================================
FIVE-DATASET BENCHMARK AUDIT
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

HLN-A1
  RNA shape        : (3484, 18085)
  ADT shape    : (3484, 31)
  spots            : 3484
  target K         : 10
  annotation K     : 10
  spatial shape    : (3484, 2)

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

HLN-D1
  RNA shape        : (3359, 18085)
  ADT shape    : (3359, 31)
  spots            : 3359
  target K         : 11
  annotation K     : 11
  spatial shape    : (3359, 2)

E18.5
  RNA shape        : (2129, 32285)
  ATAC shape   : (2129, 161461)
  spots            : 2129
  target K         : 14
  annotation K     : 14
  spatial shape    : (2129, 2)

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

S2-E15
  RNA shape        : (1939, 32285)
  ATAC shape   : (1939, 100329)
  spots            : 1939
  target K         : 15
  annotation K     : 15
  spatial shape    : (1939, 2)

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

S2-E18
  RNA shape        : (2248, 32285)
  ATAC shape   : (2248, 94941)
  spots            : 2248
  target K         : 16
  annotation K     : 16
  spatial shape    : (2248, 2)

PASS: five benchmark datasets verified.

### Cell 6 — Audit RNA+ATAC peak-frequency filtering before LSI

In [56]:
import scipy.sparse as sp


print("=" * 110)
print("RNA+ATAC PEAK-FREQUENCY AUDIT")
print("=" * 110)


def peak_detection_counts(
    X,
):

    if sp.issparse(
        X
    ):

        # Number of spots in which each peak is non-zero
        detected = np.asarray(
            (
                X > 0
            ).sum(
                axis=0
            )
        ).ravel()

        total = np.asarray(
            X.sum(
                axis=0
            )
        ).ravel()

    else:

        X = np.asarray(
            X
        )

        detected = (
            X > 0
        ).sum(
            axis=0
        )

        total = X.sum(
            axis=0
        )


    return (
        detected,
        total,
    )


audit_rows = []


for dataset_name in [
    "E18.5",
    "S2-E15",
    "S2-E18",
]:

    spec = (
        DATASET_SPECS[
            dataset_name
        ]
    )


    atac = sc.read_h5ad(
        spec[
            "second"
        ]
    )


    detected, total = (
        peak_detection_counts(
            atac.X
        )
    )


    n_peaks = (
        atac.n_vars
    )


    zero_total = int(
        (
            total == 0
        ).sum()
    )


    at_least_1 = int(
        (
            detected >= 1
        ).sum()
    )

    at_least_2 = int(
        (
            detected >= 2
        ).sum()
    )

    at_least_5 = int(
        (
            detected >= 5
        ).sum()
    )

    at_least_10 = int(
        (
            detected >= 10
        ).sum()
    )

    at_least_20 = int(
        (
            detected >= 20
        ).sum()
    )


    print(
        "\n"
        + "-" * 110
    )

    print(
        dataset_name
    )

    print(
        "-" * 110
    )


    print(
        "spots                  :",
        atac.n_obs
    )

    print(
        "raw peaks              :",
        n_peaks
    )

    print(
        "zero-total peaks       :",
        zero_total
    )

    print(
        "detected >= 1 spot     :",
        at_least_1
    )

    print(
        "detected >= 2 spots    :",
        at_least_2
    )

    print(
        "detected >= 5 spots    :",
        at_least_5
    )

    print(
        "detected >= 10 spots   :",
        at_least_10
    )

    print(
        "detected >= 20 spots   :",
        at_least_20
    )


    audit_rows.append(
        {
            "dataset":
                dataset_name,

            "spots":
                atac.n_obs,

            "raw_peaks":
                n_peaks,

            "zero_total_peaks":
                zero_total,

            "peaks_ge_1":
                at_least_1,

            "peaks_ge_2":
                at_least_2,

            "peaks_ge_5":
                at_least_5,

            "peaks_ge_10":
                at_least_10,

            "peaks_ge_20":
                at_least_20,
        }
    )


peak_audit = pd.DataFrame(
    audit_rows
)


print(
    "\n"
    + "=" * 110
)

print(
    "PEAK-FREQUENCY SUMMARY"
)

print(
    "=" * 110
)


display(
    peak_audit
)


print(
    "\nAUDIT ONLY — no ATAC matrix was modified."
)

print(
    "Do NOT start PRAGA training yet."
)

==============================================================================================================
RNA+ATAC PEAK-FREQUENCY AUDIT
==============================================================================================================

--------------------------------------------------------------------------------------------------------------
E18.5
--------------------------------------------------------------------------------------------------------------
spots                  : 2129
raw peaks              : 161461
zero-total peaks       : 4
detected >= 1 spot     : 161457
detected >= 2 spots    : 161450
detected >= 5 spots    : 161249
detected >= 10 spots   : 158701
detected >= 20 spots   : 139203

--------------------------------------------------------------------------------------------------------------
S2-E15
--------------------------------------------------------------------------------------------------------------
spots                  : 1939
raw peaks              : 100329
zero-total peaks       : 0
detected >= 1 spot     : 100329
detected >= 2 spots    : 100329
detected >= 5 spots    : 100328
detected >= 10 spots   : 100060
detected >= 20 spots   : 95309

--------------------------------------------------------------------------------------------------------------
S2-E18
--------------------------------------------------------------------------------------------------------------
spots                  : 2248
raw peaks              : 94941
zero-total peaks       : 0
detected >= 1 spot     : 94941
detected >= 2 spots    : 94941
detected >= 5 spots    : 94941
detected >= 10 spots   : 94833
detected >= 20 spots   : 91828

==============================================================================================================
PEAK-FREQUENCY SUMMARY
==============================================================================================================

,dataset,spots,raw_peaks,zero_total_peaks,peaks_ge_1,peaks_ge_2,peaks_ge_5,peaks_ge_10,peaks_ge_20
0,E18.5,2129,161461,4,161457,161450,161249,158701,139203
1,S2-E15,1939,100329,0,100329,100329,100328,100060,95309
2,S2-E18,2248,94941,0,94941,94941,94941,94833,91828

AUDIT ONLY — no ATAC matrix was modified.
Do NOT start PRAGA training yet.

### Cell 7 — Define frozen PRAGA preprocessing for all five datasets

In [57]:
from types import SimpleNamespace
import scipy.sparse as sp

from PRAGA.preprocess import (
    fix_seed,
    clr_normalize_each_cell,
    pca,
    lsi,
    construct_neighbor_graph,
)

from PRAGA.Train_model import Train
from PRAGA.utils import clustering


def make_praga_args(spec):

    return SimpleNamespace(
        init_k=int(spec["init_k"]),
        KNN_k=int(spec["KNN_k"]),
        alpha=0.9,
        cl_weight=1.0,
        RNA_weight=float(spec["RNA_weight"]),
        ADT_weight=float(spec["ADT_weight"]),
        tau=2.0,
    )


def remove_zero_total_peaks_only(
    atac,
    dataset_name,
):

    n_spots_before = atac.n_obs
    n_peaks_before = atac.n_vars

    peak_sum = np.asarray(
        atac.X.sum(axis=0)
    ).ravel()

    assert np.isfinite(
        peak_sum
    ).all()

    keep = (
        peak_sum > 0
    )

    n_removed = int(
        (~keep).sum()
    )

    atac = (
        atac[:, keep]
        .copy()
    )

    assert (
        atac.n_obs
        ==
        n_spots_before
    )

    spot_sum = np.asarray(
        atac.X.sum(axis=1)
    ).ravel()

    zero_spots = int(
        (spot_sum <= 0).sum()
    )

    if zero_spots > 0:

        raise RuntimeError(
            f"{dataset_name}: "
            f"{zero_spots} zero-total ATAC spots."
        )

    print(
        f"{dataset_name}: "
        f"ATAC {n_peaks_before} -> {atac.n_vars} peaks "
        f"(removed {n_removed} zero-total peaks)"
    )

    return (
        atac,
        {
            "n_peaks_before":
                int(n_peaks_before),

            "zero_total_peaks_removed":
                int(n_removed),

            "n_peaks_after":
                int(atac.n_vars),

            "zero_total_spots":
                int(zero_spots),
        },
    )


def standardize_lsi_columns(
    X,
    dataset_name,
):

    X = np.asarray(
        X,
        dtype=np.float64,
    )

    assert np.isfinite(
        X
    ).all()

    mean = X.mean(
        axis=0,
        keepdims=True,
    )

    std = X.std(
        axis=0,
        ddof=1,
        keepdims=True,
    )

    if np.any(
        std <= 0
    ):

        raise RuntimeError(
            f"{dataset_name}: "
            "non-positive LSI column std."
        )

    X = (
        X - mean
    ) / std

    assert np.isfinite(
        X
    ).all()

    print(
        f"{dataset_name}: "
        f"scaled LSI shape = {X.shape}"
    )

    print(
        f"{dataset_name}: "
        f"max |column mean| = "
        f"{np.abs(X.mean(axis=0)).max():.3e}"
    )

    print(
        f"{dataset_name}: "
        f"sample std range = "
        f"[{X.std(axis=0, ddof=1).min():.6f}, "
        f"{X.std(axis=0, ddof=1).max():.6f}]"
    )

    return X


def preprocess_praga_frozen(
    dataset_name,
):

    (
        rna,
        second,
        spec,
    ) = load_clean_dataset(
        dataset_name
    )

    args = make_praga_args(
        spec
    )

    # ========================================================
    # RNA + ADT
    # ========================================================

    if (
        spec["second_type"]
        == "ADT"
    ):

        data_type = "10x"

        sc.pp.filter_genes(
            rna,
            min_cells=10,
        )

        sc.pp.highly_variable_genes(
            rna,
            flavor="seurat_v3",
            n_top_genes=3000,
        )

        sc.pp.normalize_total(
            rna,
            target_sum=1e4,
        )

        sc.pp.log1p(
            rna
        )

        sc.pp.scale(
            rna
        )

        rna_high = (
            rna[
                :,
                rna.var[
                    "highly_variable"
                ],
            ]
            .copy()
        )

        n_comps = (
            second.n_vars - 1
        )

        rna.obsm[
            "feat"
        ] = pca(
            rna_high,
            n_comps=n_comps,
        )

        if sp.issparse(
            second.X
        ):

            second.X = (
                second.X.toarray()
            )

        second = (
            clr_normalize_each_cell(
                second
            )
        )

        sc.pp.scale(
            second
        )

        second.obsm[
            "feat"
        ] = pca(
            second,
            n_comps=n_comps,
        )

        audit = {
            "modality":
                "RNA+ADT",

            "compatibility_preprocessing":
                "none",

            "spot_filtering":
                False,

            "extra_LSI_column_scaling":
                False,
        }


    # ========================================================
    # RNA + ATAC
    # ========================================================

    else:

        data_type = (
            "Spatial-epigenome-transcriptome"
        )

        benchmark_spots = (
            rna.obs_names.copy()
        )

        # ----------------------------------------------------
        # RNA
        # ----------------------------------------------------

        sc.pp.filter_genes(
            rna,
            min_cells=10,
        )

        # Keep fixed benchmark spot population.
        # Do NOT call filter_cells(min_genes=200).

        sc.pp.highly_variable_genes(
            rna,
            flavor="seurat_v3",
            n_top_genes=3000,
        )

        sc.pp.normalize_total(
            rna,
            target_sum=1e4,
        )

        sc.pp.log1p(
            rna
        )

        sc.pp.scale(
            rna
        )

        rna_high = (
            rna[
                :,
                rna.var[
                    "highly_variable"
                ],
            ]
            .copy()
        )

        rna.obsm[
            "feat"
        ] = pca(
            rna_high,
            n_comps=50,
        )


        # ----------------------------------------------------
        # ATAC
        # ----------------------------------------------------

        second = (
            second[
                benchmark_spots
            ]
            .copy()
        )

        assert np.array_equal(
            np.asarray(
                benchmark_spots
            ),
            np.asarray(
                second.obs_names
            ),
        )

        (
            second,
            atac_audit,
        ) = remove_zero_total_peaks_only(
            second,
            dataset_name,
        )

        # Keep PRAGA fallback LSI itself unchanged.
        sc.pp.highly_variable_genes(
            second,
            flavor="seurat_v3",
            n_top_genes=3000,
        )

        lsi(
            second,
            use_highly_variable=False,
            n_components=51,
        )

        raw_lsi = np.asarray(
            second.obsm[
                "X_lsi"
            ],
            dtype=np.float64,
        )

        assert raw_lsi.shape == (
            spec["n_spots"],
            50,
        )

        assert np.isfinite(
            raw_lsi
        ).all()

        # Fixed compatibility transformation.
        scaled_lsi = (
            standardize_lsi_columns(
                raw_lsi,
                dataset_name,
            )
        )

        second.obsm[
            "X_lsi"
        ] = scaled_lsi.copy()

        second.obsm[
            "feat"
        ] = scaled_lsi.copy()

        audit = {
            **atac_audit,

            "modality":
                "RNA+ATAC",

            "compatibility_preprocessing":
                "remove_zero_total_peaks"
                "+column_standardize_LSI",

            "spot_filtering":
                False,

            "LSI_use_highly_variable":
                False,

            "LSI_components":
                50,

            "extra_LSI_column_scaling":
                True,

            "LSI_scaling":
                "column_zero_mean_"
                "unit_sample_std_ddof1",
        }


    # ========================================================
    # Final feature audit
    # ========================================================

    assert (
        rna.n_obs
        ==
        spec["n_spots"]
    )

    assert (
        second.n_obs
        ==
        spec["n_spots"]
    )

    assert np.array_equal(
        np.asarray(
            rna.obs_names
        ),
        np.asarray(
            second.obs_names
        ),
    )

    feat1 = np.asarray(
        rna.obsm[
            "feat"
        ]
    )

    feat2 = np.asarray(
        second.obsm[
            "feat"
        ]
    )

    assert np.isfinite(
        feat1
    ).all()

    assert np.isfinite(
        feat2
    ).all()

    print(
        f"{dataset_name}: "
        f"RNA feat = {feat1.shape}"
    )

    print(
        f"{dataset_name}: "
        f"{spec['second_type']} feat = {feat2.shape}"
    )

    print(
        f"{dataset_name}: "
        f"KNN_k={spec['KNN_k']}, "
        f"weights="
        f"[{spec['RNA_weight']}, "
        f"{spec['ADT_weight']}], "
        f"init_k={spec['init_k']}"
    )

    data = construct_neighbor_graph(
        rna,
        second,
        datatype=data_type,
        Arg=args,
    )

    return (
        rna,
        second,
        data,
        args,
        spec,
        data_type,
        audit,
    )


print(
    "PASS: frozen five-dataset PRAGA preprocessing defined."
)

PASS: frozen five-dataset PRAGA preprocessing defined.

### Cell 8 — Stable PCA20 + mclust EEE bridge with explicit column names

In [58]:
import numpy as np
import subprocess
import tempfile
from pathlib import Path

from PRAGA.preprocess import pca

from sklearn.metrics import (
    adjusted_rand_score,
    normalized_mutual_info_score,
)


def mclust_eee_labels(
    X,
    n_clusters,
    random_seed=2020,
):
    """
    Robust bridge:

        NumPy PCA matrix
        -> TSV
        -> Rscript
        -> mclust::Mclust
        -> labels

    Clustering protocol remains:
        G = target K
        modelNames = "EEE"
        seed = 2020
    """

    X = np.asarray(
        X,
        dtype=np.float64,
    )

    assert X.ndim == 2
    assert np.isfinite(X).all()

    n, d = X.shape

    with tempfile.TemporaryDirectory() as tmpdir:

        tmpdir = Path(tmpdir)

        input_path = (
            tmpdir
            / "pca_matrix.tsv"
        )

        output_path = (
            tmpdir
            / "mclust_labels.txt"
        )

        script_path = (
            tmpdir
            / "run_mclust.R"
        )


        # ====================================================
        # Save PCA matrix
        # ====================================================

        np.savetxt(
            input_path,
            X,
            delimiter="\t",
            fmt="%.17g",
        )


        # ====================================================
        # R script
        # ====================================================

        r_script = r'''
suppressPackageStartupMessages(
    library(mclust)
)

args <- commandArgs(
    trailingOnly = TRUE
)

input_file  <- args[1]
output_file <- args[2]
seed        <- as.integer(args[3])
G           <- as.integer(args[4])


X <- as.matrix(
    read.table(
        input_file,
        header = FALSE,
        sep = "\t",
        check.names = FALSE,
        stringsAsFactors = FALSE
    )
)

storage.mode(X) <- "double"


# Explicit names entirely inside R.
colnames(X) <- paste0(
    "PC",
    seq_len(
        ncol(X)
    )
)


if (
    any(
        !is.finite(X)
    )
) {
    stop(
        "Non-finite values in PCA matrix."
    )
}


set.seed(
    seed
)


fit <- Mclust(
    X,
    G = G,
    modelNames = "EEE"
)


labels <- fit$classification


if (
    length(labels)
    !=
    nrow(X)
) {
    stop(
        "Classification length mismatch."
    )
}


write.table(
    labels,
    file = output_file,
    row.names = FALSE,
    col.names = FALSE,
    quote = FALSE
)
'''

        script_path.write_text(
            r_script,
            encoding="utf-8",
        )


        # ====================================================
        # Run mclust in an independent R process
        # ====================================================

        proc = subprocess.run(
            [
                "Rscript",
                str(script_path),
                str(input_path),
                str(output_path),
                str(int(random_seed)),
                str(int(n_clusters)),
            ],
            text=True,
            capture_output=True,
        )


        if proc.returncode != 0:

            print(
                "\nR stdout:"
            )

            print(
                proc.stdout
            )

            print(
                "\nR stderr:"
            )

            print(
                proc.stderr
            )

            raise RuntimeError(
                "External R mclust failed."
            )


        assert output_path.exists()


        labels = np.loadtxt(
            output_path,
            dtype=np.int64,
        )


    labels = np.asarray(
        labels,
        dtype=np.int64,
    ).reshape(-1)


    assert labels.shape == (
        n,
    )

    assert np.isfinite(
        labels
    ).all()


    actual_k = int(
        len(
            np.unique(
                labels
            )
        )
    )


    if (
        actual_k
        !=
        int(n_clusters)
    ):

        raise RuntimeError(
            f"mclust returned "
            f"{actual_k} clusters; "
            f"expected {n_clusters}."
        )


    return labels


def cluster_praga_embedding(
    embedding,
    template_adata,
    target_k,
):

    embedding = np.asarray(
        embedding,
        dtype=np.float64,
    )

    assert embedding.ndim == 2

    assert np.isfinite(
        embedding
    ).all()


    # ========================================================
    # PRAGA embedding -> PCA20
    # ========================================================

    adata = (
        template_adata.copy()
    )

    adata.obsm[
        "PRAGA"
    ] = embedding.copy()


    embedding_pca = pca(
        adata,
        use_reps="PRAGA",
        n_comps=20,
    )

    embedding_pca = np.asarray(
        embedding_pca,
        dtype=np.float64,
    )


    assert embedding_pca.shape == (
        embedding.shape[0],
        20,
    )

    assert np.isfinite(
        embedding_pca
    ).all()


    print(
        "PCA20 shape :",
        embedding_pca.shape
    )

    print(
        "PCA20 finite:",
        np.isfinite(
            embedding_pca
        ).all()
    )


    # ========================================================
    # PCA20 -> mclust EEE
    # ========================================================

    pred = mclust_eee_labels(
        embedding_pca,
        n_clusters=int(
            target_k
        ),
        random_seed=2020,
    )


    print(
        "mclust K    :",
        len(
            np.unique(
                pred
            )
        )
    )


    return pred


def evaluate_praga(
    gt,
    pred,
):

    gt = np.asarray(
        gt
    ).astype(str)

    pred = np.asarray(
        pred
    ).astype(str)


    ari = adjusted_rand_score(
        gt,
        pred,
    )

    nmi = normalized_mutual_info_score(
        gt,
        pred,
        average_method="max",
    )


    return (
        float(ari),
        float(nmi),
    )


print(
    "PASS: external-Rscript PCA20 + mclust EEE bridge defined."
)

PASS: external-Rscript PCA20 + mclust EEE bridge defined.

### Cell 8.1 — Verify the external Rscript mclust bridge

In [59]:
rng = np.random.default_rng(
    2020
)


X_test = np.vstack(
    [
        rng.normal(
            loc=-3.0,
            scale=0.4,
            size=(40, 20),
        ),

        rng.normal(
            loc=0.0,
            scale=0.4,
            size=(40, 20),
        ),

        rng.normal(
            loc=3.0,
            scale=0.4,
            size=(40, 20),
        ),
    ]
)


test_labels = mclust_eee_labels(
    X_test,
    n_clusters=3,
    random_seed=2020,
)


print(
    "Input shape   :",
    X_test.shape
)

print(
    "Labels shape  :",
    test_labels.shape
)

print(
    "Predicted K   :",
    len(
        np.unique(
            test_labels
        )
    )
)

print(
    "Unique labels :",
    np.unique(
        test_labels
    )
)


assert (
    test_labels.shape
    ==
    (120,)
)

assert (
    len(
        np.unique(
            test_labels
        )
    )
    ==
    3
)


print(
    "\nPASS: external Rscript mclust bridge works."
)

Input shape   : (120, 20)
Labels shape  : (120,)
Predicted K   : 3
Unique labels : [1 2 3]

PASS: external Rscript mclust bridge works.

### Cell 9 — Define single-run PRAGA execution and evidence saving

In [60]:
import gc
import json
import time
from pathlib import Path


FORMAL_ROOT = (
    PRAGA_OUTPUT_ROOT
    / "formal"
)

FORMAL_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


def dataset_tag(
    dataset_name,
):

    return (
        dataset_name
        .replace("-", "")
        .replace(".", "")
    )


def run_praga_once(
    dataset_name,
    seed,
    output_root=FORMAL_ROOT,
    overwrite=False,
):

    spec = (
        DATASET_SPECS[
            dataset_name
        ]
    )

    tag = dataset_tag(
        dataset_name
    )

    run_dir = (
        Path(output_root)
        / f"{tag}_seed{seed}"
    )

    metrics_path = (
        run_dir
        / "metrics.json"
    )


    required_files = [
        run_dir / "embedding.npy",
        run_dir / "pred_labels.npy",
        run_dir / "gt_labels.npy",
        run_dir / "coords.npy",
        run_dir / "spot_ids.npy",
        run_dir / "metrics.json",
        run_dir / "preprocessing_audit.json",
    ]


    # ========================================================
    # Resume
    # ========================================================

    if (
        not overwrite
        and all(
            p.exists()
            for p in required_files
        )
    ):

        with open(
            metrics_path,
            "r",
            encoding="utf-8",
        ) as f:

            result = json.load(
                f
            )

        print(
            f"SKIP: {dataset_name} seed={seed} "
            f"already complete."
        )

        return result


    run_dir.mkdir(
        parents=True,
        exist_ok=True,
    )


    print(
        "\n"
        + "=" * 110
    )

    print(
        f"PRAGA RUN | "
        f"{dataset_name} | "
        f"seed={seed}"
    )

    print(
        "=" * 110
    )


    start = time.time()


    # ========================================================
    # Seed
    # ========================================================

    fix_seed(
        int(seed)
    )


    # ========================================================
    # Preprocessing
    # ========================================================

    (
        rna,
        second,
        data,
        args,
        spec,
        data_type,
        preprocessing_audit,
    ) = preprocess_praga_frozen(
        dataset_name
    )


    # ========================================================
    # PRAGA training
    # ========================================================

    model = Train(
        data,
        datatype=data_type,
        device=DEVICE,
        random_seed=int(seed),
        Arg=args,
    )


    assert (
        int(model.epochs)
        ==
        int(spec["epochs"])
    )


    output = (
        model.train()
    )


    embedding = np.asarray(
        output[
            "PRAGA"
        ],
        dtype=np.float64,
    )


    assert embedding.shape == (
        spec["n_spots"],
        64,
    )

    assert np.isfinite(
        embedding
    ).all()


    # ========================================================
    # Final clustering
    # ========================================================

    pred = (
        cluster_praga_embedding(
            embedding,
            rna,
            spec["K"],
        )
    )


    gt = (
        rna.obs[
            "Spatial_Label"
        ]
        .astype(str)
        .to_numpy()
    )


    coords = np.asarray(
        rna.obsm[
            "spatial"
        ],
        dtype=np.float64,
    )


    spot_ids = np.asarray(
        rna.obs_names.astype(str)
    )


    assert len(
        np.unique(
            pred
        )
    ) == spec["K"]


    ari, nmi = evaluate_praga(
        gt,
        pred,
    )


    runtime_sec = float(
        time.time()
        -
        start
    )


    # ========================================================
    # Save evidence
    # ========================================================

    np.save(
        run_dir
        / "embedding.npy",
        embedding,
    )

    np.save(
        run_dir
        / "pred_labels.npy",
        pred,
    )

    np.save(
        run_dir
        / "gt_labels.npy",
        gt,
    )

    np.save(
        run_dir
        / "coords.npy",
        coords,
    )

    np.save(
        run_dir
        / "spot_ids.npy",
        spot_ids,
    )


    with open(
        run_dir
        / "preprocessing_audit.json",
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            preprocessing_audit,
            f,
            indent=2,
        )


    result = {
        "method":
            "PRAGA",

        "dataset":
            dataset_name,

        "seed":
            int(seed),

        "n_spots":
            int(spec["n_spots"]),

        "target_K":
            int(spec["K"]),

        "predicted_K":
            int(
                len(
                    np.unique(
                        pred
                    )
                )
            ),

        "training_init_K":
            int(
                spec[
                    "init_k"
                ]
            ),

        "epochs":
            int(
                spec[
                    "epochs"
                ]
            ),

        "KNN_k":
            int(
                spec[
                    "KNN_k"
                ]
            ),

        "RNA_weight":
            float(
                spec[
                    "RNA_weight"
                ]
            ),

        "second_weight":
            float(
                spec[
                    "ADT_weight"
                ]
            ),

        "embedding_dim":
            int(
                embedding.shape[1]
            ),

        "ARI":
            float(ari),

        "NMI":
            float(nmi),

        "NMI_average_method":
            "max",

        "runtime_sec":
            runtime_sec,

        "preprocessing":
            preprocessing_audit[
                "compatibility_preprocessing"
            ],

        "final_clustering":
            "PCA20+mclust_EEE_seed2020",
    }


    with open(
        metrics_path,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            result,
            f,
            indent=2,
        )


    print(
        "\n"
        + "-" * 110
    )

    print(
        "PRAGA RUN RESULT"
    )

    print(
        "-" * 110
    )

    print(
        f"Dataset     : {dataset_name}"
    )

    print(
        f"Seed        : {seed}"
    )

    print(
        f"Spots       : {spec['n_spots']}"
    )

    print(
        f"Target K    : {spec['K']}"
    )

    print(
        f"Predicted K : "
        f"{len(np.unique(pred))}"
    )

    print(
        f"Embedding   : "
        f"{embedding.shape}"
    )

    print(
        f"ARI         : "
        f"{ari:.12f}"
    )

    print(
        f"NMI         : "
        f"{nmi:.12f}"
    )

    print(
        f"Runtime     : "
        f"{runtime_sec:.2f} sec"
    )

    print(
        f"Evidence    : "
        f"{run_dir}"
    )


    # ========================================================
    # Cleanup
    # ========================================================

    del model
    del output
    del data
    del rna
    del second

    gc.collect()

    if torch.cuda.is_available():

        torch.cuda.empty_cache()


    return result


print(
    "PASS: single-run PRAGA runner defined."
)

PASS: single-run PRAGA runner defined.

### Cell 10 — Run the remaining three seed0 PRAGA smoke tests

In [61]:
SMOKE_ROOT = (
    PRAGA_OUTPUT_ROOT
    / "smoke_final"
)

SMOKE_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


smoke_results = []


for dataset_name in [
    "HLN-D1",
    "S2-E15",
    "S2-E18",
]:

    result = run_praga_once(
        dataset_name=
            dataset_name,

        seed=
            0,

        output_root=
            SMOKE_ROOT,

        overwrite=
            False,
    )

    smoke_results.append(
        result
    )


smoke_df = pd.DataFrame(
    smoke_results
)


display(
    smoke_df[
        [
            "dataset",
            "seed",
            "n_spots",
            "target_K",
            "predicted_K",
            "ARI",
            "NMI",
            "runtime_sec",
        ]
    ]
)


assert (
    smoke_df[
        "predicted_K"
    ]
    ==
    smoke_df[
        "target_K"
    ]
).all()


print(
    "\nPASS: remaining three smoke runs completed."
)

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.08it/s]

tensor(30.5108, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3595, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.2576, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6144, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.11it/s]

tensor(29.7690, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1346, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:00<00:08,  3.06it/s]

tensor(29.0379, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8959, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:08,  2.92it/s]

tensor(28.0627, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8735, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:08,  2.85it/s]

tensor(26.9493, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0476, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.81it/s]

tensor(26.1483, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.3990, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.78it/s]

tensor(25.6756, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9103, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:07,  2.77it/s]

tensor(24.4851, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5662, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.75it/s]

tensor(23.5360, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3529, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.75it/s]

tensor(23.2360, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2578, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:03<00:06,  2.75it/s]

tensor(22.8913, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2700, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.74it/s]

tensor(22.3685, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3781, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.74it/s]

tensor(21.9742, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5733, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:04<00:05,  2.74it/s]

tensor(21.7442, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8480, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.73it/s]

tensor(21.4229, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1933, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.74it/s]

tensor(21.1886, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6030, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.73it/s]

tensor(21.0739, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0709, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.73it/s]

tensor(20.8809, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5915, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:06<00:04,  2.74it/s]

tensor(20.6437, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1599, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.73it/s]

tensor(20.4846, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7711, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.74it/s]

tensor(20.2981, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4210, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:07<00:02,  2.74it/s]

tensor(20.0774, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1064, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.74it/s]

tensor(19.9323, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8229, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:08<00:02,  2.74it/s]

tensor(19.7950, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5684, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.73it/s]

tensor(19.6419, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3402, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.73it/s]

tensor(19.5331, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1351, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:09<00:01,  2.72it/s]

tensor(19.4139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9516, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.71it/s]

tensor(19.2679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7872, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.70it/s]

tensor(19.1640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6412, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:10<00:00,  2.76it/s]

Model training finished!

Infer time:  0.0029745101928710938
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 0
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.193806122448
NMI         : 0.298272318220
Runtime     : 23.60 sec
Evidence    : /kaggle/working/PRAGA_baseline/smoke_final/HLND1_seed0

==============================================================================================================
PRAGA RUN | S2-E15 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 6.417e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29, 10.06it/s]

tensor(17.8598, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3791, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.8635, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2366, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:27, 10.79it/s]

tensor(17.7748, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3044, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6844, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5624, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6079, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9911, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:25, 11.44it/s]

tensor(17.5474, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5734, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5012, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2949, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4581, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1421, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:24, 11.98it/s]

tensor(17.4129, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1037, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3589, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1664, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2935, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3220, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:23, 12.12it/s]

tensor(17.2257, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5605, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1611, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8739, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1129, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2551, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:23, 12.33it/s]

tensor(17.0765, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6980, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0424, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1955, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9944, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7431, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:22, 12.33it/s]

tensor(16.9287, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3355, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8529, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9687, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7769, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6377, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:22, 12.47it/s]

tensor(16.7083, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3405, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6422, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0725, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5746, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8320, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:01<00:22, 12.50it/s]

tensor(16.5016, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6153, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4218, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3352, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2458, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:22, 12.35it/s]

tensor(16.2415, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0893, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9482, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0380, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8225, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:21, 12.39it/s]

tensor(15.9292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7097, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6090, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5190, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:21, 12.36it/s]

tensor(15.5714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4389, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3678, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3044, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:02<00:21, 12.33it/s]

tensor(15.1859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2492, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2012, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1591, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:21, 12.35it/s]

tensor(14.8978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0953, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0727, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:20, 12.32it/s]

tensor(14.6736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0558, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0437, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:21, 12.06it/s]

tensor(14.4245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:20, 12.17it/s]

tensor(14.2512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:04<00:20, 12.30it/s]

tensor(14.1125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0224, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:04<00:19, 12.33it/s]

tensor(13.9785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:19, 12.25it/s]

tensor(13.8545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:04<00:19, 12.27it/s]

tensor(13.7449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7121, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:05<00:19, 12.24it/s]

tensor(13.6517, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:05<00:18, 12.33it/s]

tensor(13.5663, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:18, 12.30it/s]

tensor(13.4857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:18, 12.34it/s]

tensor(13.4133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:06<00:18, 12.33it/s]

tensor(13.3475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:06<00:18, 12.32it/s]

tensor(13.2836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:17, 12.29it/s]

tensor(13.2245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:17, 12.25it/s]

tensor(13.1701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:07<00:17, 12.21it/s]

tensor(13.1190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:07<00:17, 12.13it/s]

tensor(13.0700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:16, 12.22it/s]

tensor(13.0234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:16, 12.18it/s]

tensor(12.9793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9507, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:08<00:16, 12.30it/s]

tensor(12.9369, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([159, 115,  85, 218,  75, 336,  48, 119,  34,  97,  30, 199, 310, 114])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 7/1939 [00:00<00:29, 65.97it/s]
  1%|          | 14/1939 [00:00<00:29, 65.38it/s]
  1%|          | 21/1939 [00:00<00:33, 56.64it/s]
  1%|▏         | 27/1939 [00:00<00:41, 46.30it/s]
  2%|▏         | 32/1939 [00:00<00:41, 45.52it/s]
  2%|▏         | 40/1939 [00:00<00:37, 50.01it/s]
  2%|▏         | 46/1939 [00:01<01:50, 17.18it/s]
  3%|▎         | 50/1939 [00:02<02:24, 13.06it/s]
  3%|▎         | 53/1939 [00:02<02:28, 12.67it/s]
  3%|▎         | 56/1939 [00:03<03:18,  9.50it/s]
  3%|▎         | 58/1939 [00:03<03:00, 10.43it/s]
  3%|▎         | 60/1939 [00:03<04:11,  7.48it/s]
  3%|▎         | 64/1939 [00:03<02:59, 10.47it/s]
  3%|▎         | 67/1939 [00:04<02:54, 10.72it/s]
  4%|▎         | 69/1939 [00:04<02:39, 11.71it/s]
  4%|▎         | 71/1939 [00:04<03:30,  8.87it/s]
  4%|▍         | 73/1939 [00:04<03:43,  8.34it/s]
  4%|▍         | 75/1939 [00:05<03:17,  9.45it/s]
  4%|▍         | 78/1939 [00:05<03:02, 10.19it/s]
  4%|▍         | 80/1939 [00:06<05:10,  5.98it/s]
  4%|▍         | 81/1939 [00:06<06:16,  4.94it/s]
  4%|▍         | 82/1939 [00:06<06:25,  4.81it/s]
  4%|▍         | 83/1939 [00:07<07:08,  4.33it/s]
  4%|▍         | 84/1939 [00:07<06:22,  4.85it/s]
  4%|▍         | 86/1939 [00:07<05:12,  5.93it/s]
  4%|▍         | 87/1939 [00:07<05:33,  5.55it/s]
  5%|▍         | 89/1939 [00:07<04:13,  7.30it/s]
  5%|▍         | 94/1939 [00:07<02:31, 12.15it/s]
  5%|▍         | 96/1939 [00:08<02:27, 12.53it/s]
  5%|▌         | 99/1939 [00:08<02:01, 15.16it/s]
  5%|▌         | 101/1939 [00:08<04:13,  7.25it/s]
  5%|▌         | 104/1939 [00:09<03:12,  9.54it/s]
  6%|▌         | 107/1939 [00:09<02:55, 10.46it/s]
  6%|▌         | 110/1939 [00:09<02:27, 12.39it/s]
  6%|▌         | 114/1939 [00:09<02:22, 12.82it/s]
  6%|▌         | 116/1939 [00:09<02:35, 11.69it/s]
  6%|▌         | 118/1939 [00:10<04:06,  7.40it/s]
  6%|▌         | 120/1939 [00:10<03:51,  7.86it/s]
  6%|▋         | 122/1939 [00:10<03:49,  7.92it/s]
 33%|███▎      | 100/300 [00:22<00:16, 12.30it/s]]
  7%|▋         | 128/1939 [00:11<02:28, 12.17it/s]
  7%|▋         | 130/1939 [00:11<02:20, 12.89it/s]
  7%|▋         | 132/1939 [00:11<02:44, 10.99it/s]
  7%|▋         | 134/1939 [00:11<02:41, 11.18it/s]
  7%|▋         | 136/1939 [00:12<03:52,  7.77it/s]
  7%|▋         | 138/1939 [00:12<05:01,  5.97it/s]
  7%|▋         | 139/1939 [00:13<05:32,  5.41it/s]
  7%|▋         | 141/1939 [00:13<06:23,  4.69it/s]
  7%|▋         | 142/1939 [00:13<05:57,  5.02it/s]
  7%|▋         | 144/1939 [00:13<04:24,  6.79it/s]
  8%|▊         | 146/1939 [00:14<03:58,  7.51it/s]
  8%|▊         | 148/1939 [00:14<03:14,  9.21it/s]
  8%|▊         | 150/1939 [00:14<03:18,  9.00it/s]
  8%|▊         | 153/1939 [00:14<02:46, 10.71it/s]
  8%|▊         | 155/1939 [00:14<02:35, 11.50it/s]
  8%|▊         | 157/1939 [00:15<04:15,  6.98it/s]
  8%|▊         | 159/1939 [00:15<05:07,  5.79it/s]
  8%|▊         | 160/1939 [00:15<05:04,  5.85it/s]
  8%|▊         | 162/1939 [00:16<05:31,  5.36it/s]
  8%|▊         | 163/1939 [00:16<06:33,  4.51it/s]
  8%|▊         | 164/1939 [00:16<06:06,  4.85it/s]
  9%|▊         | 166/1939 [00:17<04:24,  6.71it/s]
  9%|▊         | 169/1939 [00:17<03:06,  9.50it/s]
  9%|▉         | 171/1939 [00:17<04:27,  6.61it/s]
  9%|▉         | 176/1939 [00:17<02:28, 11.88it/s]
  9%|▉         | 183/1939 [00:17<01:25, 20.47it/s]
 10%|▉         | 187/1939 [00:18<02:06, 13.87it/s]
 10%|▉         | 193/1939 [00:18<01:29, 19.45it/s]
 10%|█         | 199/1939 [00:19<02:01, 14.27it/s]
 10%|█         | 202/1939 [00:19<02:12, 13.13it/s]
 11%|█         | 205/1939 [00:19<02:42, 10.68it/s]
 11%|█         | 207/1939 [00:20<02:58,  9.70it/s]
 11%|█         | 209/1939 [00:20<02:42, 10.67it/s]
 11%|█         | 211/1939 [00:20<02:54,  9.89it/s]
 11%|█         | 213/1939 [00:21<03:36,  7.96it/s]
 11%|█         | 215/1939 [00:21<03:38,  7.89it/s]
 11%|█         | 218/1939 [00:21<04:20,  6.62it/s]
 11%|█▏        | 220/1939 [00:21<03:37,  7.89it/s]
 11%|█▏        | 222/1939 [00:22<03:29,  8.20it/s]
 12%|█▏        | 224/1939 [00:22<04:38,  6.16it/s]
 12%|█▏        | 227/1939 [00:22<03:21,  8.51it/s]
 12%|█▏        | 229/1939 [00:23<03:21,  8.49it/s]
 12%|█▏        | 231/1939 [00:23<03:21,  8.48it/s]
 12%|█▏        | 233/1939 [00:23<03:22,  8.44it/s]
 12%|█▏        | 236/1939 [00:23<03:04,  9.22it/s]
 12%|█▏        | 238/1939 [00:23<02:38, 10.71it/s]
 12%|█▏        | 240/1939 [00:24<03:20,  8.47it/s]
 12%|█▏        | 242/1939 [00:25<05:25,  5.22it/s]
 13%|█▎        | 243/1939 [00:25<06:57,  4.06it/s]
 13%|█▎        | 244/1939 [00:26<08:29,  3.33it/s]
 13%|█▎        | 245/1939 [00:26<07:46,  3.63it/s]
 13%|█▎        | 246/1939 [00:26<07:20,  3.84it/s]
 13%|█▎        | 248/1939 [00:26<05:48,  4.86it/s]
 13%|█▎        | 250/1939 [00:27<06:25,  4.38it/s]
 13%|█▎        | 251/1939 [00:27<08:29,  3.32it/s]
 13%|█▎        | 252/1939 [00:28<09:53,  2.84it/s]
 13%|█▎        | 255/1939 [00:28<05:35,  5.01it/s]
 13%|█▎        | 257/1939 [00:28<04:45,  5.90it/s]
 13%|█▎        | 258/1939 [00:29<06:31,  4.29it/s]
 13%|█▎        | 260/1939 [00:29<05:26,  5.14it/s]
 14%|█▎        | 263/1939 [00:29<04:13,  6.62it/s]
 14%|█▎        | 264/1939 [00:30<06:00,  4.65it/s]
 14%|█▎        | 266/1939 [00:30<04:36,  6.06it/s]
 14%|█▍        | 268/1939 [00:30<05:20,  5.21it/s]
 14%|█▍        | 270/1939 [00:31<06:04,  4.57it/s]
 14%|█▍        | 273/1939 [00:32<06:04,  4.57it/s]
 14%|█▍        | 274/1939 [00:32<07:24,  3.75it/s]
 14%|█▍        | 276/1939 [00:32<05:40,  4.88it/s]
 14%|█▍        | 279/1939 [00:33<05:20,  5.19it/s]
 14%|█▍        | 281/1939 [00:33<04:45,  5.80it/s]
 15%|█▍        | 284/1939 [00:33<03:54,  7.07it/s]
 15%|█▍        | 285/1939 [00:34<04:01,  6.86it/s]
 15%|█▍        | 287/1939 [00:34<04:14,  6.50it/s]
 15%|█▍        | 288/1939 [00:34<04:27,  6.18it/s]
 15%|█▌        | 291/1939 [00:34<03:05,  8.87it/s]
 15%|█▌        | 293/1939 [00:35<04:50,  5.67it/s]
 15%|█▌        | 295/1939 [00:35<03:53,  7.04it/s]
 15%|█▌        | 297/1939 [00:36<05:13,  5.25it/s]
 15%|█▌        | 298/1939 [00:36<06:40,  4.10it/s]
 15%|█▌        | 300/1939 [00:37<06:55,  3.95it/s]
 16%|█▌        | 302/1939 [00:37<05:13,  5.22it/s]
 16%|█▌        | 303/1939 [00:37<06:55,  3.94it/s]
 16%|█▌        | 304/1939 [00:38<08:19,  3.27it/s]
 16%|█▌        | 307/1939 [00:38<07:01,  3.87it/s]
 16%|█▌        | 308/1939 [00:39<08:23,  3.24it/s]
 16%|█▌        | 311/1939 [00:39<05:10,  5.25it/s]
 16%|█▌        | 313/1939 [00:40<07:53,  3.43it/s]
 16%|█▌        | 315/1939 [00:41<07:59,  3.39it/s]
 16%|█▋        | 316/1939 [00:41<09:15,  2.92it/s]
 16%|█▋        | 317/1939 [00:42<10:25,  2.59it/s]
 16%|█▋        | 318/1939 [00:42<11:07,  2.43it/s]
 16%|█▋        | 319/1939 [00:43<11:58,  2.26it/s]
 17%|█▋        | 320/1939 [00:43<12:34,  2.15it/s]
 17%|█▋        | 321/1939 [00:44<10:53,  2.48it/s]
 17%|█▋        | 322/1939 [00:44<09:19,  2.89it/s]
 17%|█▋        | 325/1939 [00:44<04:48,  5.59it/s]
 17%|█▋        | 327/1939 [00:44<05:30,  4.88it/s]
 17%|█▋        | 330/1939 [00:45<03:39,  7.33it/s]
 17%|█▋        | 332/1939 [00:45<04:39,  5.75it/s]
 17%|█▋        | 335/1939 [00:45<03:19,  8.04it/s]
 17%|█▋        | 339/1939 [00:46<03:27,  7.72it/s]
 18%|█▊        | 342/1939 [00:46<02:41,  9.87it/s]
 18%|█▊        | 348/1939 [00:47<02:39,  9.95it/s]
 18%|█▊        | 351/1939 [00:47<02:37, 10.09it/s]
 18%|█▊        | 353/1939 [00:47<02:44,  9.65it/s]
 18%|█▊        | 355/1939 [00:48<03:37,  7.29it/s]
 19%|█▊        | 359/1939 [00:48<02:31, 10.46it/s]
 19%|█▊        | 361/1939 [00:48<03:26,  7.64it/s]
 19%|█▊        | 363/1939 [00:48<03:12,  8.20it/s]
 19%|█▉        | 365/1939 [00:49<02:46,  9.44it/s]
 19%|█▉        | 367/1939 [00:49<03:31,  7.45it/s]
 19%|█▉        | 369/1939 [00:49<02:58,  8.81it/s]
 19%|█▉        | 371/1939 [00:49<03:21,  7.78it/s]
 19%|█▉        | 373/1939 [00:50<03:29,  7.47it/s]
 19%|█▉        | 376/1939 [00:50<02:41,  9.70it/s]
 19%|█▉        | 378/1939 [00:50<03:07,  8.35it/s]
 20%|█▉        | 380/1939 [00:51<03:48,  6.82it/s]
 20%|█▉        | 382/1939 [00:51<04:17,  6.04it/s]
 20%|█▉        | 384/1939 [00:51<03:33,  7.28it/s]
 20%|█▉        | 386/1939 [00:51<02:57,  8.76it/s]
 20%|██        | 388/1939 [00:52<03:02,  8.49it/s]
 20%|██        | 390/1939 [00:52<03:53,  6.64it/s]
 20%|██        | 391/1939 [00:52<03:45,  6.85it/s]
 20%|██        | 392/1939 [00:53<05:26,  4.73it/s]
 20%|██        | 393/1939 [00:53<05:18,  4.86it/s]
 20%|██        | 394/1939 [00:53<05:16,  4.88it/s]
 20%|██        | 396/1939 [00:53<04:38,  5.54it/s]
 20%|██        | 397/1939 [00:53<04:35,  5.60it/s]
 21%|██        | 398/1939 [00:54<04:49,  5.33it/s]
 21%|██        | 400/1939 [00:54<03:28,  7.39it/s]
 21%|██        | 404/1939 [00:54<02:22, 10.78it/s]
 21%|██        | 406/1939 [00:54<02:33,  9.99it/s]
 21%|██        | 408/1939 [00:54<02:44,  9.28it/s]
 21%|██        | 411/1939 [00:55<02:31, 10.06it/s]
 21%|██▏       | 413/1939 [00:55<03:14,  7.87it/s]
 21%|██▏       | 415/1939 [00:55<03:05,  8.20it/s]
 21%|██▏       | 416/1939 [00:56<04:19,  5.88it/s]
 22%|██▏       | 418/1939 [00:56<03:27,  7.34it/s]
 22%|██▏       | 420/1939 [00:56<02:51,  8.86it/s]
 22%|██▏       | 422/1939 [00:56<03:03,  8.29it/s]
 22%|██▏       | 424/1939 [00:56<02:30, 10.04it/s]
 22%|██▏       | 426/1939 [00:57<02:19, 10.85it/s]
 22%|██▏       | 428/1939 [00:57<02:20, 10.79it/s]
 22%|██▏       | 430/1939 [00:57<02:08, 11.77it/s]
 22%|██▏       | 433/1939 [00:57<01:38, 15.21it/s]
 23%|██▎       | 439/1939 [00:57<01:00, 24.83it/s]
 23%|██▎       | 442/1939 [00:57<01:19, 18.87it/s]
 23%|██▎       | 445/1939 [00:58<01:17, 19.40it/s]
 23%|██▎       | 449/1939 [00:58<01:03, 23.48it/s]
 23%|██▎       | 452/1939 [00:58<01:01, 24.01it/s]
 23%|██▎       | 455/1939 [00:58<00:59, 24.98it/s]
 24%|██▎       | 459/1939 [00:58<00:53, 27.44it/s]
 24%|██▍       | 464/1939 [00:58<00:45, 32.33it/s]
 24%|██▍       | 468/1939 [00:58<00:43, 33.92it/s]
 24%|██▍       | 472/1939 [00:59<01:40, 14.64it/s]
 24%|██▍       | 475/1939 [00:59<01:30, 16.17it/s]
 25%|██▍       | 478/1939 [00:59<01:50, 13.16it/s]
 25%|██▍       | 481/1939 [00:59<01:47, 13.63it/s]
 25%|██▍       | 483/1939 [01:00<01:41, 14.36it/s]
 25%|██▌       | 489/1939 [01:00<01:22, 17.60it/s]
 25%|██▌       | 492/1939 [01:01<02:25,  9.96it/s]
 26%|██▌       | 495/1939 [01:01<02:18, 10.42it/s]
 26%|██▌       | 497/1939 [01:01<02:23, 10.04it/s]
 26%|██▌       | 500/1939 [01:01<02:26,  9.85it/s]
 26%|██▌       | 502/1939 [01:01<02:10, 11.05it/s]
 26%|██▌       | 505/1939 [01:02<02:05, 11.39it/s]
 26%|██▌       | 508/1939 [01:02<01:46, 13.50it/s]
 26%|██▋       | 511/1939 [01:02<01:49, 13.04it/s]
 27%|██▋       | 515/1939 [01:02<01:23, 16.99it/s]
 27%|██▋       | 519/1939 [01:02<01:08, 20.79it/s]
 27%|██▋       | 525/1939 [01:02<00:49, 28.78it/s]
 27%|██▋       | 531/1939 [01:02<00:39, 35.75it/s]
 28%|██▊       | 537/1939 [01:03<00:52, 26.86it/s]
 28%|██▊       | 541/1939 [01:04<02:13, 10.46it/s]
 28%|██▊       | 546/1939 [01:04<02:00, 11.60it/s]
 28%|██▊       | 549/1939 [01:05<02:47,  8.31it/s]
 28%|██▊       | 551/1939 [01:05<02:48,  8.22it/s]
 29%|██▊       | 553/1939 [01:06<03:31,  6.56it/s]
 29%|██▊       | 556/1939 [01:06<03:46,  6.11it/s]
 29%|██▉       | 558/1939 [01:07<04:18,  5.35it/s]
 29%|██▉       | 560/1939 [01:07<03:37,  6.34it/s]
 29%|██▉       | 562/1939 [01:08<05:53,  3.90it/s]
 29%|██▉       | 566/1939 [01:08<03:40,  6.22it/s]
 29%|██▉       | 568/1939 [01:09<05:22,  4.26it/s]
 29%|██▉       | 570/1939 [01:09<04:21,  5.24it/s]
 29%|██▉       | 572/1939 [01:10<04:30,  5.05it/s]
 30%|██▉       | 574/1939 [01:10<03:47,  6.00it/s]
 30%|██▉       | 576/1939 [01:10<03:09,  7.20it/s]
 30%|██▉       | 579/1939 [01:10<02:25,  9.35it/s]
 30%|███       | 582/1939 [01:11<02:19,  9.70it/s]
 30%|███       | 584/1939 [01:11<02:32,  8.90it/s]
 30%|███       | 586/1939 [01:11<02:38,  8.53it/s]
 30%|███       | 589/1939 [01:12<03:24,  6.61it/s]
 30%|███       | 591/1939 [01:12<02:50,  7.93it/s]
 31%|███       | 593/1939 [01:12<04:10,  5.37it/s]
 31%|███       | 595/1939 [01:13<03:49,  5.85it/s]
 31%|███       | 597/1939 [01:13<03:05,  7.24it/s]
 31%|███       | 599/1939 [01:13<02:53,  7.74it/s]
 31%|███       | 601/1939 [01:13<02:52,  7.77it/s]
 31%|███       | 603/1939 [01:13<02:25,  9.21it/s]
 31%|███       | 605/1939 [01:14<03:34,  6.22it/s]
 31%|███▏      | 607/1939 [01:14<03:21,  6.61it/s]
 31%|███▏      | 608/1939 [01:15<04:52,  4.55it/s]
 31%|███▏      | 610/1939 [01:15<03:39,  6.06it/s]
 32%|███▏      | 612/1939 [01:16<04:47,  4.61it/s]
 32%|███▏      | 613/1939 [01:16<05:08,  4.29it/s]
 32%|███▏      | 614/1939 [01:16<04:31,  4.87it/s]
 32%|███▏      | 615/1939 [01:16<04:28,  4.93it/s]
 32%|███▏      | 616/1939 [01:16<04:29,  4.90it/s]
 32%|███▏      | 617/1939 [01:17<04:03,  5.44it/s]
 32%|███▏      | 618/1939 [01:17<03:59,  5.51it/s]
 32%|███▏      | 620/1939 [01:17<03:05,  7.11it/s]
 32%|███▏      | 622/1939 [01:17<02:31,  8.71it/s]
 32%|███▏      | 624/1939 [01:17<02:03, 10.68it/s]
 32%|███▏      | 629/1939 [01:17<01:31, 14.37it/s]
 33%|███▎      | 631/1939 [01:18<01:54, 11.46it/s]
 33%|███▎      | 633/1939 [01:18<03:07,  6.98it/s]
 33%|███▎      | 635/1939 [01:18<02:39,  8.19it/s]
 33%|███▎      | 637/1939 [01:19<02:42,  7.99it/s]
 33%|███▎      | 640/1939 [01:19<02:32,  8.53it/s]
 33%|███▎      | 643/1939 [01:19<02:26,  8.83it/s]
 33%|███▎      | 645/1939 [01:19<02:07, 10.18it/s]
 33%|███▎      | 647/1939 [01:20<02:56,  7.31it/s]
 33%|███▎      | 649/1939 [01:20<02:45,  7.80it/s]
 34%|███▎      | 650/1939 [01:21<04:09,  5.17it/s]
 34%|███▎      | 651/1939 [01:21<03:52,  5.54it/s]
 34%|███▎      | 652/1939 [01:21<05:44,  3.74it/s]
 34%|███▎      | 654/1939 [01:22<04:27,  4.80it/s]
 34%|███▍      | 656/1939 [01:22<03:48,  5.61it/s]
 34%|███▍      | 658/1939 [01:22<03:39,  5.83it/s]
 34%|███▍      | 659/1939 [01:22<03:42,  5.76it/s]
 34%|███▍      | 661/1939 [01:22<02:49,  7.56it/s]
 34%|███▍      | 664/1939 [01:23<02:05, 10.15it/s]
 34%|███▍      | 666/1939 [01:23<03:01,  7.02it/s]
 34%|███▍      | 668/1939 [01:23<03:12,  6.59it/s]
 35%|███▍      | 670/1939 [01:24<02:42,  7.81it/s]
 35%|███▍      | 672/1939 [01:24<02:33,  8.26it/s]
 35%|███▍      | 674/1939 [01:24<02:47,  7.56it/s]
 35%|███▍      | 676/1939 [01:24<02:56,  7.18it/s]
 35%|███▍      | 677/1939 [01:25<03:26,  6.10it/s]
 35%|███▍      | 678/1939 [01:25<03:49,  5.51it/s]
 35%|███▌      | 680/1939 [01:25<03:09,  6.66it/s]
 35%|███▌      | 682/1939 [01:25<02:27,  8.52it/s]
 35%|███▌      | 684/1939 [01:25<02:07,  9.87it/s]
 35%|███▌      | 686/1939 [01:26<01:49, 11.44it/s]
 35%|███▌      | 688/1939 [01:26<02:28,  8.43it/s]
 36%|███▌      | 690/1939 [01:26<02:27,  8.45it/s]
 36%|███▌      | 692/1939 [01:26<02:37,  7.92it/s]
 36%|███▌      | 693/1939 [01:27<02:44,  7.58it/s]
 36%|███▌      | 696/1939 [01:27<01:56, 10.63it/s]
 36%|███▌      | 700/1939 [01:27<01:18, 15.79it/s]
 37%|███▋      | 708/1939 [01:27<00:43, 28.20it/s]
 37%|███▋      | 712/1939 [01:27<00:41, 29.65it/s]
 37%|███▋      | 717/1939 [01:27<00:36, 33.80it/s]
 37%|███▋      | 721/1939 [01:27<00:45, 26.80it/s]
 37%|███▋      | 725/1939 [01:28<00:53, 22.82it/s]
 38%|███▊      | 728/1939 [01:28<00:50, 23.95it/s]
 38%|███▊      | 731/1939 [01:28<01:26, 13.89it/s]
 38%|███▊      | 734/1939 [01:29<02:23,  8.41it/s]
 38%|███▊      | 737/1939 [01:29<01:57, 10.27it/s]
 38%|███▊      | 739/1939 [01:30<02:37,  7.64it/s]
 38%|███▊      | 741/1939 [01:30<02:17,  8.69it/s]
 38%|███▊      | 743/1939 [01:30<02:19,  8.58it/s]
 38%|███▊      | 745/1939 [01:30<02:34,  7.73it/s]
 39%|███▊      | 747/1939 [01:30<02:08,  9.25it/s]
 39%|███▊      | 749/1939 [01:31<03:16,  6.07it/s]
 39%|███▊      | 751/1939 [01:32<04:01,  4.92it/s]
 39%|███▉      | 753/1939 [01:32<03:08,  6.28it/s]
 39%|███▉      | 755/1939 [01:32<02:51,  6.89it/s]
 39%|███▉      | 757/1939 [01:32<02:52,  6.87it/s]
 39%|███▉      | 758/1939 [01:32<02:43,  7.20it/s]
 39%|███▉      | 759/1939 [01:33<04:23,  4.48it/s]
 39%|███▉      | 760/1939 [01:33<04:23,  4.48it/s]
 39%|███▉      | 763/1939 [01:33<03:09,  6.20it/s]
 39%|███▉      | 765/1939 [01:34<02:34,  7.60it/s]
 40%|███▉      | 766/1939 [01:34<02:45,  7.08it/s]
 40%|███▉      | 767/1939 [01:34<03:10,  6.14it/s]
 40%|███▉      | 768/1939 [01:34<03:44,  5.22it/s]
 40%|███▉      | 769/1939 [01:34<03:24,  5.71it/s]
 40%|███▉      | 770/1939 [01:35<04:09,  4.68it/s]
 40%|███▉      | 771/1939 [01:35<04:38,  4.19it/s]
 40%|███▉      | 772/1939 [01:35<04:22,  4.44it/s]
 40%|███▉      | 773/1939 [01:36<04:58,  3.91it/s]
 40%|███▉      | 774/1939 [01:36<04:16,  4.55it/s]
 40%|███▉      | 775/1939 [01:36<05:08,  3.78it/s]
 40%|████      | 776/1939 [01:36<04:16,  4.53it/s]
 40%|████      | 777/1939 [01:36<04:06,  4.72it/s]
 40%|████      | 779/1939 [01:37<03:08,  6.16it/s]
 40%|████      | 780/1939 [01:37<02:54,  6.64it/s]
 40%|████      | 782/1939 [01:37<02:19,  8.31it/s]
 40%|████      | 784/1939 [01:37<01:55,  9.98it/s]
 41%|████      | 787/1939 [01:37<01:36, 11.89it/s]
 41%|████      | 789/1939 [01:37<01:30, 12.73it/s]
 41%|████      | 792/1939 [01:37<01:20, 14.33it/s]
 41%|████      | 794/1939 [01:38<01:32, 12.40it/s]
 41%|████      | 796/1939 [01:38<01:29, 12.83it/s]
 41%|████      | 798/1939 [01:38<01:41, 11.20it/s]
 41%|████▏     | 800/1939 [01:39<02:37,  7.24it/s]
 41%|████▏     | 802/1939 [01:39<02:08,  8.84it/s]
 41%|████▏     | 804/1939 [01:39<02:00,  9.40it/s]
 42%|████▏     | 806/1939 [01:39<02:19,  8.13it/s]
 42%|████▏     | 809/1939 [01:40<02:47,  6.74it/s]
 42%|████▏     | 811/1939 [01:40<02:19,  8.11it/s]
 42%|████▏     | 813/1939 [01:40<02:18,  8.11it/s]
 42%|████▏     | 816/1939 [01:40<02:13,  8.42it/s]
 42%|████▏     | 818/1939 [01:41<02:25,  7.71it/s]
 42%|████▏     | 819/1939 [01:41<02:38,  7.08it/s]
 42%|████▏     | 820/1939 [01:41<02:33,  7.31it/s]
 42%|████▏     | 822/1939 [01:41<02:04,  8.97it/s]
 42%|████▏     | 824/1939 [01:41<01:51,  9.99it/s]
 43%|████▎     | 826/1939 [01:42<02:32,  7.29it/s]
 43%|████▎     | 828/1939 [01:42<02:57,  6.26it/s]
 43%|████▎     | 829/1939 [01:43<03:39,  5.06it/s]
 43%|████▎     | 832/1939 [01:43<02:27,  7.51it/s]
 43%|████▎     | 834/1939 [01:43<03:11,  5.78it/s]
 43%|████▎     | 837/1939 [01:43<02:19,  7.89it/s]
 43%|████▎     | 839/1939 [01:44<02:19,  7.91it/s]
 43%|████▎     | 841/1939 [01:44<01:59,  9.17it/s]
 44%|████▎     | 844/1939 [01:44<02:12,  8.24it/s]
 44%|████▎     | 847/1939 [01:44<01:40, 10.90it/s]
 44%|████▍     | 849/1939 [01:44<01:30, 12.03it/s]
 44%|████▍     | 851/1939 [01:45<01:55,  9.40it/s]
 44%|████▍     | 853/1939 [01:45<01:39, 10.89it/s]
 44%|████▍     | 855/1939 [01:45<02:03,  8.77it/s]
 44%|████▍     | 857/1939 [01:46<02:12,  8.15it/s]
 44%|████▍     | 859/1939 [01:46<02:45,  6.53it/s]
 44%|████▍     | 861/1939 [01:46<02:48,  6.38it/s]
 44%|████▍     | 862/1939 [01:47<03:08,  5.73it/s]
 45%|████▍     | 863/1939 [01:47<03:22,  5.32it/s]
 45%|████▍     | 864/1939 [01:47<04:14,  4.22it/s]
 45%|████▍     | 866/1939 [01:47<02:57,  6.04it/s]
 45%|████▍     | 869/1939 [01:47<02:02,  8.75it/s]
 45%|████▌     | 875/1939 [01:48<01:03, 16.77it/s]
 45%|████▌     | 880/1939 [01:48<00:47, 22.42it/s]
 46%|████▌     | 888/1939 [01:48<00:33, 31.66it/s]
 46%|████▌     | 895/1939 [01:48<00:27, 38.52it/s]
 46%|████▋     | 900/1939 [01:48<00:41, 24.90it/s]
 47%|████▋     | 904/1939 [01:49<00:51, 19.91it/s]
 47%|████▋     | 910/1939 [01:49<00:51, 19.95it/s]
 47%|████▋     | 913/1939 [01:50<01:20, 12.75it/s]
 47%|████▋     | 915/1939 [01:50<01:56,  8.83it/s]
 47%|████▋     | 918/1939 [01:50<01:48,  9.40it/s]
 47%|████▋     | 920/1939 [01:51<02:23,  7.12it/s]
 48%|████▊     | 923/1939 [01:51<01:50,  9.16it/s]
 48%|████▊     | 925/1939 [01:52<02:26,  6.91it/s]
 48%|████▊     | 927/1939 [01:52<02:23,  7.03it/s]
 48%|████▊     | 930/1939 [01:52<02:03,  8.14it/s]
 48%|████▊     | 932/1939 [01:52<02:11,  7.67it/s]
 48%|████▊     | 933/1939 [01:53<03:10,  5.27it/s]
 48%|████▊     | 935/1939 [01:53<02:32,  6.57it/s]
 49%|████▊     | 943/1939 [01:53<01:04, 15.34it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 296.03it/s]

[[np.int64(0), False, 9], [np.int64(1), False, 11], [np.int64(2), False, 3], [np.int64(3), False, 0], [np.int64(4), False, 7], [np.int64(5), False, 11], [np.int64(6), False, 0], [np.int64(8), False, 13], [np.int64(10), False, 3], [np.int64(12), False, 5], [np.int64(13), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9961, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:08<2:20:50, 42.47s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:08<1:52:01, 33.95s/it]

tensor(12.8989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0993, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2318, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [04:08<1:10:30, 21.59s/it]

tensor(12.9159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4502, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9519, device='cuda:0', grad_fn=<AddBackward0>)

 35%|███▌      | 106/300 [04:08<45:58, 14.22s/it]

tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5196, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6562, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [04:09<20:44,  6.55s/it]

tensor(12.9460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7733, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8257, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [04:09<14:11,  4.53s/it]

tensor(12.9060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8696, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8879, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9044, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9454, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [04:09<06:48,  2.22s/it]

tensor(12.8467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9824, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0145, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [04:10<04:46,  1.58s/it]

tensor(12.8113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0734, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:10<03:23,  1.13s/it]

tensor(12.7863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1019, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1246, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1485, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:10<02:25,  1.22it/s]

tensor(12.7537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1752, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2051, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2316, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [04:10<01:18,  2.22it/s]

tensor(12.7238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2522, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2720, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2786, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:11<00:51,  3.31it/s]

tensor(12.6876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2974, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6744, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3141, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:11<00:38,  4.43it/s]

tensor(12.6611, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3246, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3454, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:11<00:32,  5.10it/s]

tensor(12.6346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3779, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:11<00:21,  7.49it/s]

tensor(12.5986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3879, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3961, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [04:12<00:19,  8.44it/s]

tensor(12.5768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4244, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [04:12<00:17,  9.04it/s]

tensor(12.5564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4308, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4375, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:12<00:17,  9.11it/s]

tensor(12.5365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4458, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4542, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:12<00:16,  9.44it/s]

tensor(12.5177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4731, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4813, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [04:13<00:15,  9.75it/s]

tensor(12.4925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4898, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4968, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4772, device='cuda:0', grad_fn=<AddBackward0>)

 49%|████▉     | 148/300 [04:13<00:15,  9.67it/s]

tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5048, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5101, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:13<00:15,  9.78it/s]

tensor(12.4631, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5161, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([156, 203, 170, 318,  31, 139, 215, 109, 167,  59,  21,  79, 146, 126])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:18, 24.56it/s]
  1%|          | 11/1939 [00:00<00:36, 52.47it/s]
  1%|          | 17/1939 [00:00<00:35, 54.51it/s]
  1%|          | 23/1939 [00:00<00:40, 47.66it/s]
  1%|▏         | 29/1939 [00:00<00:37, 50.28it/s]
  2%|▏         | 36/1939 [00:00<00:34, 55.38it/s]
  2%|▏         | 42/1939 [00:00<00:50, 37.89it/s]
  2%|▏         | 47/1939 [00:01<00:50, 37.27it/s]
  3%|▎         | 52/1939 [00:01<01:13, 25.62it/s]
  3%|▎         | 56/1939 [00:01<01:34, 19.86it/s]
  3%|▎         | 63/1939 [00:01<01:09, 27.11it/s]
  3%|▎         | 67/1939 [00:02<01:21, 22.86it/s]
  4%|▎         | 71/1939 [00:02<01:14, 24.95it/s]
  4%|▍         | 75/1939 [00:02<01:34, 19.71it/s]
  4%|▍         | 78/1939 [00:02<01:41, 18.34it/s]
  4%|▍         | 81/1939 [00:03<01:57, 15.78it/s]
  4%|▍         | 84/1939 [00:03<02:14, 13.83it/s]
  4%|▍         | 86/1939 [00:03<02:35, 11.88it/s]
  5%|▍         | 88/1939 [00:03<02:50, 10.84it/s]
  5%|▍         | 92/1939 [00:03<02:03, 15.01it/s]
  5%|▍         | 95/1939 [00:04<02:15, 13.65it/s]
  5%|▌         | 99/1939 [00:04<01:44, 17.67it/s]
  5%|▌         | 102/1939 [00:04<02:03, 14.82it/s]
  6%|▌         | 107/1939 [00:04<01:29, 20.45it/s]
  6%|▌         | 113/1939 [00:04<01:07, 26.86it/s]
  6%|▌         | 117/1939 [00:04<01:02, 28.98it/s]
  6%|▌         | 121/1939 [00:05<01:25, 21.24it/s]
  6%|▋         | 124/1939 [00:05<01:26, 21.00it/s]
  7%|▋         | 130/1939 [00:05<01:05, 27.55it/s]
  7%|▋         | 134/1939 [00:05<01:11, 25.41it/s]
  7%|▋         | 137/1939 [00:06<01:31, 19.66it/s]
  7%|▋         | 140/1939 [00:06<01:27, 20.47it/s]
  7%|▋         | 145/1939 [00:06<01:24, 21.14it/s]
  8%|▊         | 148/1939 [00:06<01:23, 21.50it/s]
  8%|▊         | 153/1939 [00:06<01:24, 21.16it/s]
  8%|▊         | 156/1939 [00:06<01:21, 21.83it/s]
  8%|▊         | 159/1939 [00:07<01:38, 18.06it/s]
  8%|▊         | 161/1939 [00:07<02:01, 14.67it/s]
  8%|▊         | 164/1939 [00:07<02:03, 14.38it/s]
  9%|▊         | 166/1939 [00:07<01:58, 14.91it/s]
  9%|▉         | 170/1939 [00:07<01:54, 15.41it/s]
  9%|▉         | 173/1939 [00:08<01:39, 17.69it/s]
  9%|▉         | 180/1939 [00:08<01:05, 26.79it/s]
 10%|▉         | 187/1939 [00:08<00:49, 35.35it/s]
 10%|█         | 195/1939 [00:08<00:39, 44.46it/s]
 10%|█         | 202/1939 [00:08<00:47, 36.25it/s]
 11%|█         | 207/1939 [00:09<01:36, 17.97it/s]
 11%|█         | 211/1939 [00:09<01:41, 17.08it/s]
 11%|█         | 214/1939 [00:09<01:36, 17.84it/s]
 11%|█▏        | 220/1939 [00:09<01:14, 23.20it/s]
 12%|█▏        | 227/1939 [00:09<00:56, 30.51it/s]
 12%|█▏        | 232/1939 [00:10<01:29, 18.98it/s]
 12%|█▏        | 236/1939 [00:11<01:58, 14.38it/s]
 12%|█▏        | 239/1939 [00:11<02:03, 13.80it/s]
 12%|█▏        | 242/1939 [00:11<02:27, 11.49it/s]
 13%|█▎        | 244/1939 [00:12<02:52,  9.85it/s]
 13%|█▎        | 246/1939 [00:12<03:26,  8.20it/s]
 13%|█▎        | 248/1939 [00:12<03:36,  7.80it/s]
 13%|█▎        | 251/1939 [00:12<02:51,  9.87it/s]
 13%|█▎        | 257/1939 [00:13<02:02, 13.69it/s]
 13%|█▎        | 260/1939 [00:13<02:11, 12.82it/s]
 14%|█▎        | 263/1939 [00:13<02:21, 11.84it/s]
 14%|█▎        | 265/1939 [00:13<02:14, 12.46it/s]
 14%|█▍        | 272/1939 [00:13<01:18, 21.27it/s]
 14%|█▍        | 279/1939 [00:14<00:55, 29.96it/s]
 15%|█▍        | 284/1939 [00:14<01:33, 17.78it/s]
 15%|█▍        | 288/1939 [00:14<01:23, 19.67it/s]
 15%|█▌        | 296/1939 [00:14<00:58, 28.29it/s]
 16%|█▌        | 303/1939 [00:14<00:46, 34.89it/s]
 16%|█▌        | 309/1939 [00:15<00:42, 37.92it/s]
 16%|█▌        | 314/1939 [00:15<00:43, 37.23it/s]
 17%|█▋        | 321/1939 [00:15<00:50, 31.74it/s]
 17%|█▋        | 325/1939 [00:15<00:52, 30.78it/s]
 17%|█▋        | 332/1939 [00:15<00:43, 36.62it/s]
 17%|█▋        | 337/1939 [00:15<00:41, 38.66it/s]
 18%|█▊        | 343/1939 [00:15<00:37, 43.03it/s]
 18%|█▊        | 348/1939 [00:16<00:38, 41.70it/s]
 18%|█▊        | 353/1939 [00:16<01:17, 20.57it/s]
 18%|█▊        | 357/1939 [00:16<01:21, 19.47it/s]
 19%|█▉        | 364/1939 [00:17<01:01, 25.68it/s]
 19%|█▉        | 371/1939 [00:17<00:48, 32.16it/s]
 19%|█▉        | 376/1939 [00:17<00:56, 27.51it/s]
 20%|█▉        | 380/1939 [00:17<00:56, 27.82it/s]
 20%|█▉        | 384/1939 [00:17<01:19, 19.45it/s]
 20%|█▉        | 387/1939 [00:18<01:27, 17.82it/s]
 20%|██        | 390/1939 [00:18<01:34, 16.31it/s]
 20%|██        | 392/1939 [00:18<01:32, 16.67it/s]
 20%|██        | 394/1939 [00:18<01:56, 13.26it/s]
 20%|██        | 396/1939 [00:19<02:20, 11.01it/s]
 21%|██        | 398/1939 [00:19<03:11,  8.05it/s]
 21%|██        | 400/1939 [00:19<02:44,  9.38it/s]
 21%|██        | 403/1939 [00:19<02:03, 12.41it/s]
 21%|██        | 405/1939 [00:20<02:57,  8.66it/s]
 21%|██        | 407/1939 [00:20<03:25,  7.44it/s]
 21%|██        | 409/1939 [00:20<02:59,  8.51it/s]
 21%|██        | 411/1939 [00:20<02:39,  9.57it/s]
 21%|██▏       | 413/1939 [00:20<02:26, 10.38it/s]
 21%|██▏       | 415/1939 [00:21<02:15, 11.28it/s]
 22%|██▏       | 417/1939 [00:21<02:31, 10.02it/s]
 22%|██▏       | 419/1939 [00:21<02:32, 10.00it/s]
 22%|██▏       | 421/1939 [00:21<02:10, 11.61it/s]
 22%|██▏       | 423/1939 [00:21<02:18, 10.98it/s]
 22%|██▏       | 426/1939 [00:22<02:12, 11.40it/s]
 22%|██▏       | 428/1939 [00:22<02:09, 11.65it/s]
 22%|██▏       | 430/1939 [00:22<01:59, 12.63it/s]
 22%|██▏       | 434/1939 [00:22<01:26, 17.43it/s]
 23%|██▎       | 438/1939 [00:22<01:10, 21.30it/s]
 23%|██▎       | 443/1939 [00:22<00:54, 27.40it/s]
 23%|██▎       | 448/1939 [00:22<00:48, 30.99it/s]
 23%|██▎       | 453/1939 [00:22<00:44, 33.53it/s]
 24%|██▎       | 457/1939 [00:23<00:45, 32.48it/s]
 24%|██▍       | 461/1939 [00:23<00:43, 34.18it/s]
 24%|██▍       | 469/1939 [00:23<00:32, 44.69it/s]
 25%|██▍       | 476/1939 [00:23<00:29, 50.29it/s]
 25%|██▍       | 482/1939 [00:23<00:41, 35.29it/s]
 25%|██▌       | 489/1939 [00:24<00:47, 30.85it/s]
 25%|██▌       | 493/1939 [00:24<00:47, 30.66it/s]
 26%|██▌       | 501/1939 [00:24<00:36, 39.00it/s]
 26%|██▋       | 509/1939 [00:24<00:30, 47.53it/s]
 27%|██▋       | 515/1939 [00:24<00:45, 31.08it/s]
 27%|██▋       | 520/1939 [00:24<00:44, 32.05it/s]
 27%|██▋       | 526/1939 [00:25<00:40, 35.11it/s]
 27%|██▋       | 533/1939 [00:25<00:34, 41.11it/s]
 28%|██▊       | 538/1939 [00:25<00:54, 25.93it/s]
 28%|██▊       | 544/1939 [00:25<00:45, 30.91it/s]
 28%|██▊       | 549/1939 [00:25<00:59, 23.33it/s]
 29%|██▊       | 553/1939 [00:26<01:11, 19.52it/s]
 29%|██▉       | 559/1939 [00:26<00:54, 25.11it/s]
 29%|██▉       | 566/1939 [00:26<00:44, 30.73it/s]
 29%|██▉       | 572/1939 [00:26<00:53, 25.52it/s]
 30%|██▉       | 576/1939 [00:27<01:12, 18.91it/s]
 30%|██▉       | 579/1939 [00:27<01:23, 16.31it/s]
 30%|███       | 582/1939 [00:27<01:32, 14.70it/s]
 30%|███       | 584/1939 [00:28<01:47, 12.59it/s]
 30%|███       | 586/1939 [00:28<01:41, 13.36it/s]
 31%|███       | 593/1939 [00:28<01:01, 21.96it/s]
 31%|███       | 599/1939 [00:28<01:01, 21.75it/s]
 31%|███       | 602/1939 [00:28<01:18, 17.02it/s]
 31%|███▏      | 606/1939 [00:29<01:06, 20.09it/s]
 31%|███▏      | 609/1939 [00:29<01:17, 17.13it/s]
 32%|███▏      | 612/1939 [00:29<01:49, 12.14it/s]
 32%|███▏      | 614/1939 [00:30<02:07, 10.42it/s]
 32%|███▏      | 616/1939 [00:30<02:37,  8.39it/s]
 32%|███▏      | 618/1939 [00:30<03:00,  7.30it/s]
 32%|███▏      | 620/1939 [00:31<02:57,  7.43it/s]
 32%|███▏      | 621/1939 [00:31<03:15,  6.74it/s]
 32%|███▏      | 622/1939 [00:31<03:31,  6.23it/s]
 32%|███▏      | 624/1939 [00:31<02:44,  8.00it/s]
 32%|███▏      | 630/1939 [00:31<01:38, 13.27it/s]
 33%|███▎      | 634/1939 [00:32<01:18, 16.70it/s]
 33%|███▎      | 636/1939 [00:32<01:29, 14.49it/s]
 33%|███▎      | 639/1939 [00:32<01:15, 17.17it/s]
 33%|███▎      | 642/1939 [00:32<01:36, 13.42it/s]
 33%|███▎      | 644/1939 [00:32<01:51, 11.58it/s]
 33%|███▎      | 648/1939 [00:33<01:20, 16.01it/s]
 34%|███▎      | 651/1939 [00:33<01:53, 11.38it/s]
 34%|███▎      | 654/1939 [00:33<01:56, 11.02it/s]
 34%|███▍      | 656/1939 [00:34<02:06, 10.14it/s]
 34%|███▍      | 658/1939 [00:34<02:19,  9.20it/s]
 34%|███▍      | 660/1939 [00:34<02:31,  8.46it/s]
 34%|███▍      | 665/1939 [00:34<01:52, 11.35it/s]
 34%|███▍      | 667/1939 [00:35<02:01, 10.49it/s]
 35%|███▍      | 670/1939 [00:35<01:36, 13.16it/s]
 35%|███▍      | 672/1939 [00:35<01:44, 12.12it/s]
 35%|███▍      | 674/1939 [00:35<01:34, 13.40it/s]
 35%|███▍      | 676/1939 [00:35<01:47, 11.77it/s]
 35%|███▍      | 678/1939 [00:35<01:35, 13.22it/s]
 35%|███▌      | 680/1939 [00:36<01:47, 11.74it/s]
 35%|███▌      | 683/1939 [00:36<01:51, 11.29it/s]
 35%|███▌      | 685/1939 [00:36<01:40, 12.50it/s]
 35%|███▌      | 687/1939 [00:36<01:51, 11.21it/s]
 36%|███▌      | 689/1939 [00:36<02:04, 10.05it/s]
 36%|███▌      | 692/1939 [00:37<02:05,  9.90it/s]
 36%|███▌      | 694/1939 [00:37<02:20,  8.89it/s]
 36%|███▌      | 697/1939 [00:37<01:44, 11.91it/s]
 36%|███▌      | 699/1939 [00:37<01:47, 11.52it/s]
 36%|███▌      | 701/1939 [00:37<01:35, 12.96it/s]
 37%|███▋      | 708/1939 [00:38<00:50, 24.19it/s]
 37%|███▋      | 714/1939 [00:38<00:38, 31.43it/s]
 37%|███▋      | 720/1939 [00:38<00:32, 37.86it/s]
 37%|███▋      | 725/1939 [00:38<00:44, 27.06it/s]
 38%|███▊      | 730/1939 [00:38<00:49, 24.34it/s]
 38%|███▊      | 734/1939 [00:39<01:18, 15.27it/s]
 38%|███▊      | 738/1939 [00:39<01:06, 18.19it/s]
 38%|███▊      | 741/1939 [00:39<01:13, 16.19it/s]
 38%|███▊      | 746/1939 [00:39<00:57, 20.85it/s]
 39%|███▉      | 754/1939 [00:39<00:39, 30.27it/s]
 39%|███▉      | 759/1939 [00:40<01:04, 18.37it/s]
 39%|███▉      | 763/1939 [00:41<01:26, 13.60it/s]
 40%|███▉      | 766/1939 [00:41<01:33, 12.48it/s]
 40%|███▉      | 769/1939 [00:41<01:57,  9.97it/s]
 40%|███▉      | 771/1939 [00:42<02:03,  9.47it/s]
 40%|███▉      | 773/1939 [00:42<02:11,  8.86it/s]
 40%|████      | 776/1939 [00:42<02:04,  9.37it/s]
 40%|████      | 778/1939 [00:42<02:08,  9.02it/s]
 40%|████      | 780/1939 [00:43<02:21,  8.18it/s]
 40%|████      | 784/1939 [00:43<01:53, 10.20it/s]
 41%|████      | 786/1939 [00:43<01:47, 10.68it/s]
 41%|████      | 788/1939 [00:43<01:54, 10.04it/s]
 41%|████      | 790/1939 [00:44<01:45, 10.92it/s]
 41%|████      | 793/1939 [00:44<01:23, 13.72it/s]
 41%|████      | 799/1939 [00:44<00:55, 20.65it/s]
 41%|████▏     | 802/1939 [00:44<00:50, 22.36it/s]
 42%|████▏     | 805/1939 [00:44<00:55, 20.45it/s]
 42%|████▏     | 808/1939 [00:44<01:00, 18.75it/s]
 42%|████▏     | 811/1939 [00:45<01:15, 14.90it/s]
 42%|████▏     | 813/1939 [00:45<01:25, 13.18it/s]
 42%|████▏     | 816/1939 [00:45<01:17, 14.46it/s]
 42%|████▏     | 818/1939 [00:45<01:31, 12.21it/s]
 42%|████▏     | 820/1939 [00:46<01:55,  9.65it/s]
 42%|████▏     | 822/1939 [00:46<02:02,  9.13it/s]
 42%|████▏     | 824/1939 [00:46<01:49, 10.15it/s]
 43%|████▎     | 826/1939 [00:46<01:41, 10.98it/s]
 43%|████▎     | 828/1939 [00:46<01:29, 12.42it/s]
 43%|████▎     | 830/1939 [00:46<01:20, 13.71it/s]
 43%|████▎     | 832/1939 [00:46<01:14, 14.83it/s]
 43%|████▎     | 835/1939 [00:47<01:02, 17.77it/s]
 43%|████▎     | 842/1939 [00:47<00:37, 29.31it/s]
 44%|████▎     | 848/1939 [00:47<00:31, 35.13it/s]
 44%|████▍     | 855/1939 [00:47<00:25, 42.17it/s]
 44%|████▍     | 860/1939 [00:47<00:44, 24.02it/s]
 45%|████▍     | 864/1939 [00:47<00:41, 26.21it/s]
 45%|████▍     | 869/1939 [00:48<00:35, 30.05it/s]
 45%|████▌     | 875/1939 [00:48<00:31, 33.89it/s]
 45%|████▌     | 882/1939 [00:48<00:25, 41.40it/s]
 46%|████▌     | 887/1939 [00:48<00:24, 43.17it/s]
 46%|████▌     | 893/1939 [00:48<00:22, 46.56it/s]
 46%|████▋     | 899/1939 [00:48<00:32, 32.17it/s]
 47%|████▋     | 904/1939 [00:49<00:55, 18.79it/s]
 47%|████▋     | 909/1939 [00:49<00:45, 22.57it/s]
 47%|████▋     | 913/1939 [00:49<00:55, 18.63it/s]
 47%|████▋     | 918/1939 [00:50<00:55, 18.39it/s]
 47%|████▋     | 921/1939 [00:50<00:52, 19.35it/s]
 48%|████▊     | 927/1939 [00:50<00:49, 20.53it/s]
 48%|████▊     | 930/1939 [00:50<01:00, 16.80it/s]
 48%|████▊     | 933/1939 [00:51<01:10, 14.27it/s]
 48%|████▊     | 938/1939 [00:51<01:02, 15.99it/s]
 49%|████▊     | 941/1939 [00:51<00:57, 17.47it/s]
 49%|████▉     | 948/1939 [00:51<00:38, 25.84it/s]
 49%|████▉     | 955/1939 [00:51<00:29, 33.33it/s]
 50%|████▉     | 960/1939 [00:51<00:30, 32.25it/s]
 50%|████▉     | 966/1939 [00:51<00:26, 37.39it/s]
 50%|█████     | 971/1939 [00:52<00:51, 18.94it/s]
 50%|█████     | 975/1939 [00:52<00:56, 17.08it/s]
 50%|█████     | 978/1939 [00:53<01:02, 15.48it/s]
 51%|█████     | 981/1939 [00:53<01:00, 15.95it/s]
 51%|█████     | 984/1939 [00:53<00:58, 16.29it/s]
 51%|█████     | 986/1939 [00:53<00:57, 16.66it/s]
 51%|█████     | 991/1939 [00:53<00:53, 17.79it/s]
 51%|█████▏    | 994/1939 [00:53<00:52, 18.08it/s]
 51%|█████▏    | 997/1939 [00:54<00:58, 16.19it/s]
 52%|█████▏    | 999/1939 [00:54<01:07, 13.89it/s]
 52%|█████▏    | 1001/1939 [00:54<01:05, 14.22it/s]
 52%|█████▏    | 1003/1939 [00:54<01:17, 12.07it/s]
 52%|█████▏    | 1005/1939 [00:55<01:28, 10.51it/s]
 52%|█████▏    | 1007/1939 [00:55<01:38,  9.46it/s]
 52%|█████▏    | 1009/1939 [00:55<01:45,  8.80it/s]
 52%|█████▏    | 1010/1939 [00:55<02:06,  7.33it/s]
 52%|█████▏    | 1011/1939 [00:56<02:23,  6.45it/s]
 52%|█████▏    | 1012/1939 [00:56<02:38,  5.86it/s]
 52%|█████▏    | 1014/1939 [00:56<02:29,  6.18it/s]
 52%|█████▏    | 1015/1939 [00:56<02:38,  5.82it/s]
 52%|█████▏    | 1016/1939 [00:57<02:45,  5.59it/s]
 53%|█████▎    | 1018/1939 [00:57<02:27,  6.24it/s]
 53%|█████▎    | 1019/1939 [00:57<02:42,  5.67it/s]
 53%|█████▎    | 1021/1939 [00:57<02:01,  7.55it/s]
 53%|█████▎    | 1022/1939 [00:57<02:27,  6.22it/s]
 53%|█████▎    | 1024/1939 [00:57<01:50,  8.31it/s]
 53%|█████▎    | 1027/1939 [00:58<01:33,  9.79it/s]
 53%|█████▎    | 1030/1939 [00:58<01:08, 13.29it/s]
 54%|█████▎    | 1038/1939 [00:58<00:34, 26.47it/s]
 54%|█████▍    | 1043/1939 [00:58<00:29, 30.03it/s]
 54%|█████▍    | 1047/1939 [00:58<00:37, 23.93it/s]
 54%|█████▍    | 1051/1939 [00:59<00:45, 19.62it/s]
 54%|█████▍    | 1054/1939 [00:59<00:50, 17.62it/s]
 55%|█████▍    | 1057/1939 [00:59<00:56, 15.72it/s]
 55%|█████▍    | 1059/1939 [00:59<01:02, 14.08it/s]
 55%|█████▍    | 1062/1939 [00:59<00:57, 15.30it/s]
 55%|█████▌    | 1068/1939 [01:00<00:50, 17.10it/s]
 55%|█████▌    | 1072/1939 [01:00<00:43, 19.92it/s]
 55%|█████▌    | 1075/1939 [01:00<00:40, 21.60it/s]
 56%|█████▌    | 1080/1939 [01:00<00:40, 21.44it/s]
 56%|█████▌    | 1083/1939 [01:00<00:43, 19.65it/s]
 56%|█████▌    | 1086/1939 [01:01<00:42, 20.10it/s]
 56%|█████▌    | 1089/1939 [01:01<00:40, 20.99it/s]
 56%|█████▋    | 1092/1939 [01:01<00:48, 17.29it/s]
 56%|█████▋    | 1094/1939 [01:01<01:06, 12.78it/s]
 57%|█████▋    | 1096/1939 [01:01<01:00, 13.89it/s]
 57%|█████▋    | 1102/1939 [01:02<00:52, 15.83it/s]
 57%|█████▋    | 1104/1939 [01:02<01:05, 12.77it/s]
 57%|█████▋    | 1106/1939 [01:02<01:01, 13.50it/s]
 57%|█████▋    | 1113/1939 [01:02<00:35, 22.96it/s]
 58%|█████▊    | 1117/1939 [01:02<00:40, 20.46it/s]
 58%|█████▊    | 1120/1939 [01:03<00:37, 22.07it/s]
 58%|█████▊    | 1128/1939 [01:03<00:24, 32.67it/s]
 58%|█████▊    | 1132/1939 [01:03<00:34, 23.10it/s]
 59%|█████▊    | 1137/1939 [01:03<00:35, 22.31it/s]
 59%|█████▉    | 1141/1939 [01:03<00:32, 24.34it/s]
 59%|█████▉    | 1144/1939 [01:04<00:45, 17.50it/s]
 59%|█████▉    | 1147/1939 [01:04<00:45, 17.58it/s]
 59%|█████▉    | 1150/1939 [01:04<01:03, 12.52it/s]
 59%|█████▉    | 1152/1939 [01:05<01:10, 11.19it/s]
 60%|█████▉    | 1154/1939 [01:05<01:14, 10.50it/s]
 60%|█████▉    | 1157/1939 [01:05<01:00, 12.98it/s]
 60%|█████▉    | 1159/1939 [01:05<01:03, 12.34it/s]
 60%|█████▉    | 1162/1939 [01:05<00:52, 14.70it/s]
 60%|██████    | 1164/1939 [01:05<01:05, 11.85it/s]
 60%|██████    | 1168/1939 [01:06<00:47, 16.28it/s]
 60%|██████    | 1171/1939 [01:06<00:41, 18.37it/s]
 61%|██████    | 1174/1939 [01:06<00:50, 15.15it/s]
 61%|██████    | 1176/1939 [01:06<00:51, 14.90it/s]
 61%|██████    | 1178/1939 [01:06<01:08, 11.07it/s]
 61%|██████    | 1180/1939 [01:07<01:21,  9.31it/s]
 61%|██████    | 1182/1939 [01:07<01:10, 10.80it/s]
 61%|██████    | 1184/1939 [01:07<01:19,  9.44it/s]
 61%|██████    | 1186/1939 [01:07<01:24,  8.95it/s]
 61%|██████▏   | 1188/1939 [01:08<01:12, 10.42it/s]
 61%|██████▏   | 1190/1939 [01:08<01:15,  9.97it/s]
 61%|██████▏   | 1192/1939 [01:08<01:20,  9.34it/s]
 62%|██████▏   | 1194/1939 [01:08<01:23,  8.96it/s]
 62%|██████▏   | 1196/1939 [01:08<01:28,  8.39it/s]
 62%|██████▏   | 1197/1939 [01:09<01:30,  8.16it/s]
 62%|██████▏   | 1199/1939 [01:09<01:13, 10.13it/s]
 62%|██████▏   | 1202/1939 [01:09<00:56, 13.15it/s]
 62%|██████▏   | 1209/1939 [01:09<00:32, 22.73it/s]
 63%|██████▎   | 1212/1939 [01:09<00:31, 23.15it/s]
 63%|██████▎   | 1217/1939 [01:09<00:32, 22.01it/s]
 63%|██████▎   | 1220/1939 [01:10<00:36, 19.44it/s]
 63%|██████▎   | 1223/1939 [01:10<00:35, 20.41it/s]
 63%|██████▎   | 1226/1939 [01:10<00:37, 19.01it/s]
 63%|██████▎   | 1228/1939 [01:10<00:38, 18.69it/s]
 64%|██████▎   | 1232/1939 [01:10<00:42, 16.77it/s]
 64%|██████▎   | 1235/1939 [01:10<00:37, 18.97it/s]
 64%|██████▍   | 1239/1939 [01:11<00:39, 17.84it/s]
 64%|██████▍   | 1241/1939 [01:11<00:38, 18.02it/s]
 64%|██████▍   | 1243/1939 [01:11<00:45, 15.43it/s]
 64%|██████▍   | 1245/1939 [01:11<00:44, 15.45it/s]
 64%|██████▍   | 1247/1939 [01:11<01:02, 11.12it/s]
 64%|██████▍   | 1250/1939 [01:12<00:49, 13.99it/s]
 65%|██████▍   | 1252/1939 [01:12<00:56, 12.11it/s]
 65%|██████▍   | 1254/1939 [01:12<01:04, 10.55it/s]
 65%|██████▍   | 1257/1939 [01:12<00:51, 13.27it/s]
 65%|██████▍   | 1259/1939 [01:12<00:58, 11.60it/s]
 65%|██████▌   | 1262/1939 [01:12<00:46, 14.64it/s]
 65%|██████▌   | 1269/1939 [01:13<00:26, 24.97it/s]
 66%|██████▌   | 1273/1939 [01:13<00:35, 18.58it/s]
 66%|██████▌   | 1277/1939 [01:13<00:30, 21.48it/s]
 66%|██████▌   | 1283/1939 [01:13<00:23, 28.48it/s]
 66%|██████▋   | 1287/1939 [01:13<00:26, 24.45it/s]
 67%|██████▋   | 1291/1939 [01:14<00:31, 20.60it/s]
 67%|██████▋   | 1294/1939 [01:14<00:35, 18.04it/s]
 67%|██████▋   | 1297/1939 [01:14<00:33, 19.13it/s]
 67%|██████▋   | 1304/1939 [01:14<00:22, 28.05it/s]
 68%|██████▊   | 1309/1939 [01:14<00:25, 24.84it/s]
 68%|██████▊   | 1313/1939 [01:15<00:40, 15.48it/s]
 68%|██████▊   | 1316/1939 [01:15<00:39, 15.84it/s]
 68%|██████▊   | 1319/1939 [01:15<00:35, 17.51it/s]
 68%|██████▊   | 1325/1939 [01:15<00:26, 23.40it/s]
 69%|██████▊   | 1329/1939 [01:15<00:23, 25.74it/s]
 69%|██████▊   | 1333/1939 [01:16<00:22, 26.61it/s]
 69%|██████▉   | 1340/1939 [01:16<00:24, 24.74it/s]
 69%|██████▉   | 1343/1939 [01:16<00:26, 22.58it/s]
 69%|██████▉   | 1346/1939 [01:17<00:43, 13.75it/s]
 70%|██████▉   | 1349/1939 [01:17<00:44, 13.31it/s]
 70%|██████▉   | 1351/1939 [01:17<00:42, 13.91it/s]
 70%|██████▉   | 1353/1939 [01:17<00:58, 10.05it/s]
 70%|██████▉   | 1355/1939 [01:18<01:02,  9.33it/s]
 70%|███████   | 1358/1939 [01:18<00:48, 12.00it/s]
 70%|███████   | 1361/1939 [01:18<00:42, 13.51it/s]
 70%|███████   | 1363/1939 [01:18<00:41, 14.00it/s]
 70%|███████   | 1365/1939 [01:18<00:53, 10.72it/s]
 71%|███████   | 1367/1939 [01:18<00:47, 12.10it/s]
 71%|███████   | 1374/1939 [01:19<00:25, 22.12it/s]
 71%|███████   | 1378/1939 [01:19<00:27, 20.33it/s]
 71%|███████   | 1381/1939 [01:19<00:34, 16.12it/s]
 71%|███████▏  | 1384/1939 [01:19<00:40, 13.72it/s]
 71%|███████▏  | 1386/1939 [01:20<00:53, 10.34it/s]
 72%|███████▏  | 1389/1939 [01:20<00:52, 10.40it/s]
 72%|███████▏  | 1391/1939 [01:20<00:56,  9.63it/s]
 72%|███████▏  | 1394/1939 [01:20<00:45, 11.87it/s]
 72%|███████▏  | 1400/1939 [01:21<00:28, 18.91it/s]
 72%|███████▏  | 1403/1939 [01:21<00:29, 17.91it/s]
 73%|███████▎  | 1406/1939 [01:21<00:26, 19.89it/s]
 73%|███████▎  | 1409/1939 [01:21<00:30, 17.57it/s]
 73%|███████▎  | 1412/1939 [01:21<00:31, 16.51it/s]
 73%|███████▎  | 1416/1939 [01:22<00:32, 16.12it/s]
 73%|███████▎  | 1419/1939 [01:22<00:28, 18.16it/s]
 74%|███████▎  | 1426/1939 [01:22<00:18, 27.31it/s]
 74%|███████▎  | 1430/1939 [01:22<00:28, 17.68it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 306.78it/s]
 50%|█████     | 151/300 [06:03<1:03:25, 25.54s/it]

[[np.int64(0), False, 8], [np.int64(1), False, 3], [np.int64(2), False, 3], [np.int64(3), False, 6], [np.int64(4), False, 8], [np.int64(5), False, 13], [np.int64(7), False, 12], [np.int64(8), False, 9], [np.int64(10), False, 0], [np.int64(11), False, 9], [np.int64(12), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6188, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.4514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8560, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [06:03<34:52, 14.23s/it]

tensor(12.4526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1021, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1982, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [06:04<19:46,  8.19s/it]

tensor(12.4645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1594, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1440, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [06:04<12:11,  5.12s/it]

tensor(12.4472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1839, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [06:04<07:52,  3.35s/it]

tensor(12.4412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2262, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2423, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2419, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [06:04<05:14,  2.27s/it]

tensor(12.4214, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2694, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [06:04<03:34,  1.57s/it]

tensor(12.4070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3232, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [06:04<02:55,  1.29s/it]

tensor(12.4038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3647, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3790, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [06:05<01:57,  1.14it/s]

tensor(12.3988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3933, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [06:05<01:21,  1.62it/s]

tensor(12.3927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4116, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4264, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4355, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [06:05<00:58,  2.22it/s]

tensor(12.3695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4523, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [06:05<00:43,  2.95it/s]

tensor(12.3586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4615, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [06:05<00:33,  3.79it/s]

tensor(12.3540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3496, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4717, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3450, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4880, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [06:06<00:26,  4.69it/s]

tensor(12.3403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5069, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [06:06<00:21,  5.61it/s]

tensor(12.3315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5154, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [06:06<00:18,  6.50it/s]

tensor(12.3278, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5252, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5374, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [06:06<00:16,  7.28it/s]

tensor(12.3155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5326, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5333, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [06:06<00:14,  7.96it/s]

tensor(12.3084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5349, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [06:07<00:13,  8.46it/s]

tensor(12.3055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5404, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5469, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [06:07<00:12,  8.90it/s]

tensor(12.2956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5517, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [06:07<00:11,  9.23it/s]

tensor(12.2926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5551, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5597, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5665, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [06:07<00:11,  9.47it/s]

tensor(12.2843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5616, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [06:07<00:11,  9.58it/s]

tensor(12.2815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5617, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5636, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5652, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [06:08<00:10,  9.70it/s]

tensor(12.2734, device='cuda:0', grad_fn=<AddBackward0>)

 66%|██████▌   | 198/300 [06:08<00:10,  9.74it/s]

tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5626, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5610, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [06:08<00:10,  9.78it/s]

tensor(12.2678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5681, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5702, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([146, 264, 164, 143, 124,  82, 208,  21,  87, 132, 316,  93, 131,  28])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:11, 27.10it/s]
  1%|          | 11/1939 [00:00<00:36, 53.22it/s]
  1%|          | 17/1939 [00:00<00:36, 51.95it/s]
  1%|          | 23/1939 [00:00<00:38, 49.20it/s]
  2%|▏         | 30/1939 [00:00<00:35, 54.52it/s]
  2%|▏         | 36/1939 [00:00<00:33, 56.15it/s]
  2%|▏         | 42/1939 [00:01<01:14, 25.47it/s]
  2%|▏         | 47/1939 [00:01<01:09, 27.21it/s]
  3%|▎         | 51/1939 [00:01<01:31, 20.68it/s]
  3%|▎         | 55/1939 [00:02<01:56, 16.20it/s]
  3%|▎         | 58/1939 [00:02<02:11, 14.29it/s]
  3%|▎         | 60/1939 [00:02<02:17, 13.62it/s]
  3%|▎         | 62/1939 [00:02<02:14, 13.91it/s]
  3%|▎         | 64/1939 [00:02<02:09, 14.47it/s]
  3%|▎         | 66/1939 [00:03<02:53, 10.80it/s]
  4%|▎         | 68/1939 [00:03<02:37, 11.87it/s]
  4%|▎         | 70/1939 [00:03<03:22,  9.24it/s]
  4%|▍         | 73/1939 [00:03<03:14,  9.59it/s]
  4%|▍         | 75/1939 [00:04<02:53, 10.74it/s]
  4%|▍         | 77/1939 [00:04<02:32, 12.19it/s]
  4%|▍         | 79/1939 [00:04<03:53,  7.97it/s]
  4%|▍         | 81/1939 [00:05<04:39,  6.64it/s]
  4%|▍         | 82/1939 [00:05<04:51,  6.37it/s]
  4%|▍         | 83/1939 [00:05<04:39,  6.63it/s]
  4%|▍         | 84/1939 [00:05<04:38,  6.67it/s]
  4%|▍         | 86/1939 [00:05<04:12,  7.35it/s]
  4%|▍         | 87/1939 [00:06<05:04,  6.07it/s]
  5%|▍         | 90/1939 [00:06<03:12,  9.59it/s]
  5%|▍         | 94/1939 [00:06<02:25, 12.68it/s]
  5%|▍         | 96/1939 [00:06<02:48, 10.95it/s]
  5%|▌         | 99/1939 [00:06<02:16, 13.45it/s]
  5%|▌         | 101/1939 [00:07<02:58, 10.30it/s]
  5%|▌         | 104/1939 [00:07<02:23, 12.77it/s]
  5%|▌         | 106/1939 [00:07<02:47, 10.97it/s]
  6%|▌         | 108/1939 [00:07<03:09,  9.67it/s]
  6%|▌         | 111/1939 [00:07<02:24, 12.68it/s]
  6%|▌         | 115/1939 [00:08<02:05, 14.56it/s]
  6%|▌         | 117/1939 [00:08<02:22, 12.78it/s]
  6%|▌         | 119/1939 [00:08<02:52, 10.55it/s]
  6%|▌         | 121/1939 [00:09<04:07,  7.34it/s]
  6%|▋         | 124/1939 [00:09<03:05,  9.80it/s]
  7%|▋         | 128/1939 [00:09<02:42, 11.18it/s]
  7%|▋         | 131/1939 [00:09<02:15, 13.39it/s]
  7%|▋         | 133/1939 [00:09<02:39, 11.31it/s]
  7%|▋         | 135/1939 [00:10<02:54, 10.37it/s]
  7%|▋         | 137/1939 [00:10<03:13,  9.33it/s]
  7%|▋         | 139/1939 [00:10<03:57,  7.56it/s]
  7%|▋         | 141/1939 [00:10<03:47,  7.92it/s]
  7%|▋         | 142/1939 [00:11<04:24,  6.81it/s]
  7%|▋         | 145/1939 [00:11<03:54,  7.67it/s]
  8%|▊         | 148/1939 [00:11<02:51, 10.46it/s]
  8%|▊         | 150/1939 [00:11<03:06,  9.61it/s]
  8%|▊         | 152/1939 [00:12<03:14,  9.18it/s]
  8%|▊         | 154/1939 [00:12<03:36,  8.25it/s]
  8%|▊         | 157/1939 [00:12<03:29,  8.51it/s]
  8%|▊         | 158/1939 [00:13<04:15,  6.97it/s]
  8%|▊         | 159/1939 [00:13<04:35,  6.47it/s]
  8%|▊         | 160/1939 [00:13<05:06,  5.80it/s]
  8%|▊         | 161/1939 [00:13<05:52,  5.05it/s]
  8%|▊         | 162/1939 [00:14<05:54,  5.02it/s]
  8%|▊         | 163/1939 [00:14<06:33,  4.51it/s]
  8%|▊         | 164/1939 [00:14<06:35,  4.49it/s]
  9%|▊         | 166/1939 [00:14<04:27,  6.64it/s]
  9%|▉         | 173/1939 [00:14<01:41, 17.43it/s]
  9%|▉         | 181/1939 [00:14<00:59, 29.52it/s]
 10%|▉         | 186/1939 [00:15<01:11, 24.39it/s]
 10%|▉         | 190/1939 [00:15<01:09, 25.12it/s]
 10%|█         | 195/1939 [00:15<00:58, 29.91it/s]
 10%|█         | 199/1939 [00:15<01:17, 22.38it/s]
 10%|█         | 203/1939 [00:16<02:14, 12.87it/s]
 11%|█         | 206/1939 [00:16<02:58,  9.73it/s]
 11%|█         | 208/1939 [00:17<02:52, 10.04it/s]
 11%|█         | 211/1939 [00:17<02:50, 10.11it/s]
 11%|█         | 213/1939 [00:17<02:59,  9.61it/s]
 11%|█         | 216/1939 [00:17<02:25, 11.87it/s]
 11%|█         | 218/1939 [00:17<02:33, 11.24it/s]
 11%|█▏        | 221/1939 [00:18<02:03, 13.96it/s]
 12%|█▏        | 223/1939 [00:18<02:19, 12.29it/s]
 12%|█▏        | 225/1939 [00:18<02:42, 10.52it/s]
 12%|█▏        | 228/1939 [00:18<02:44, 10.43it/s]
 12%|█▏        | 230/1939 [00:19<03:05,  9.19it/s]
 12%|█▏        | 233/1939 [00:19<03:03,  9.32it/s]
 12%|█▏        | 235/1939 [00:19<02:44, 10.34it/s]
 12%|█▏        | 237/1939 [00:19<03:04,  9.20it/s]
 12%|█▏        | 239/1939 [00:20<03:19,  8.51it/s]
 12%|█▏        | 240/1939 [00:20<03:59,  7.10it/s]
 12%|█▏        | 241/1939 [00:20<04:14,  6.67it/s]
 12%|█▏        | 242/1939 [00:20<04:55,  5.74it/s]
 13%|█▎        | 243/1939 [00:21<05:04,  5.57it/s]
 13%|█▎        | 244/1939 [00:21<05:15,  5.37it/s]
 13%|█▎        | 245/1939 [00:21<05:52,  4.80it/s]
 13%|█▎        | 247/1939 [00:21<03:59,  7.06it/s]
 13%|█▎        | 248/1939 [00:21<04:33,  6.19it/s]
 13%|█▎        | 250/1939 [00:22<04:32,  6.19it/s]
 13%|█▎        | 252/1939 [00:22<03:30,  8.03it/s]
 13%|█▎        | 255/1939 [00:22<02:37, 10.70it/s]
 13%|█▎        | 257/1939 [00:22<02:58,  9.41it/s]
 13%|█▎        | 259/1939 [00:23<03:11,  8.79it/s]
 13%|█▎        | 261/1939 [00:23<02:56,  9.49it/s]
 14%|█▎        | 263/1939 [00:23<02:56,  9.52it/s]
 14%|█▎        | 265/1939 [00:23<03:07,  8.91it/s]
 14%|█▍        | 268/1939 [00:23<03:04,  9.08it/s]
 14%|█▍        | 270/1939 [00:24<03:18,  8.39it/s]
 14%|█▍        | 273/1939 [00:24<03:03,  9.09it/s]
 14%|█▍        | 274/1939 [00:24<03:36,  7.69it/s]
 14%|█▍        | 276/1939 [00:24<03:05,  8.98it/s]
 14%|█▍        | 278/1939 [00:25<02:35, 10.65it/s]
 14%|█▍        | 280/1939 [00:25<03:30,  7.89it/s]
 15%|█▍        | 282/1939 [00:25<03:55,  7.05it/s]
 15%|█▍        | 284/1939 [00:26<04:02,  6.83it/s]
 15%|█▍        | 285/1939 [00:26<04:20,  6.34it/s]
 15%|█▍        | 287/1939 [00:26<04:03,  6.79it/s]
 15%|█▍        | 288/1939 [00:26<04:25,  6.22it/s]
 15%|█▍        | 290/1939 [00:26<03:23,  8.10it/s]
 15%|█▌        | 293/1939 [00:27<02:48,  9.77it/s]
 15%|█▌        | 295/1939 [00:27<02:24, 11.35it/s]
 15%|█▌        | 297/1939 [00:27<02:11, 12.45it/s]
 15%|█▌        | 299/1939 [00:27<02:20, 11.69it/s]
 16%|█▌        | 302/1939 [00:27<01:57, 13.98it/s]
 16%|█▌        | 304/1939 [00:27<02:30, 10.87it/s]
 16%|█▌        | 307/1939 [00:28<02:41, 10.11it/s]
 16%|█▌        | 309/1939 [00:28<02:21, 11.53it/s]
 16%|█▌        | 311/1939 [00:28<02:05, 13.01it/s]
 16%|█▌        | 313/1939 [00:28<02:38, 10.23it/s]
 16%|█▌        | 315/1939 [00:29<03:22,  8.03it/s]
 16%|█▋        | 317/1939 [00:29<03:52,  6.97it/s]
 16%|█▋        | 318/1939 [00:29<04:11,  6.44it/s]
 16%|█▋        | 319/1939 [00:30<04:31,  5.97it/s]
 17%|█▋        | 320/1939 [00:30<04:40,  5.76it/s]
 17%|█▋        | 321/1939 [00:30<05:28,  4.93it/s]
 17%|█▋        | 322/1939 [00:30<05:50,  4.61it/s]
 17%|█▋        | 325/1939 [00:30<03:22,  7.98it/s]
 17%|█▋        | 332/1939 [00:31<01:52, 14.23it/s]
 17%|█▋        | 335/1939 [00:31<01:37, 16.41it/s]
 17%|█▋        | 339/1939 [00:31<01:32, 17.26it/s]
 18%|█▊        | 341/1939 [00:31<01:34, 16.88it/s]
 18%|█▊        | 348/1939 [00:31<01:00, 26.15it/s]
 18%|█▊        | 352/1939 [00:32<01:40, 15.71it/s]
 18%|█▊        | 355/1939 [00:32<02:22, 11.13it/s]
 18%|█▊        | 357/1939 [00:32<02:11, 12.07it/s]
 19%|█▊        | 360/1939 [00:33<02:12, 11.92it/s]
 19%|█▊        | 363/1939 [00:33<02:24, 10.89it/s]
 19%|█▉        | 365/1939 [00:33<02:11, 11.98it/s]
 19%|█▉        | 367/1939 [00:33<02:26, 10.70it/s]
 19%|█▉        | 369/1939 [00:33<02:14, 11.65it/s]
 19%|█▉        | 371/1939 [00:34<02:28, 10.55it/s]
 19%|█▉        | 373/1939 [00:34<02:21, 11.05it/s]
 19%|█▉        | 375/1939 [00:34<02:12, 11.84it/s]
 19%|█▉        | 377/1939 [00:34<02:07, 12.28it/s]
 20%|█▉        | 379/1939 [00:34<02:06, 12.34it/s]
 20%|█▉        | 381/1939 [00:35<02:28, 10.48it/s]
 20%|█▉        | 383/1939 [00:35<02:20, 11.08it/s]
 20%|█▉        | 385/1939 [00:35<02:23, 10.85it/s]
 20%|█▉        | 387/1939 [00:35<02:53,  8.95it/s]
 20%|██        | 388/1939 [00:35<03:32,  7.31it/s]
 20%|██        | 389/1939 [00:36<03:56,  6.55it/s]
 20%|██        | 390/1939 [00:36<04:10,  6.19it/s]
 20%|██        | 391/1939 [00:36<04:33,  5.66it/s]
 20%|██        | 393/1939 [00:36<04:16,  6.02it/s]
 20%|██        | 394/1939 [00:37<04:45,  5.41it/s]
 20%|██        | 395/1939 [00:37<04:15,  6.03it/s]
 20%|██        | 396/1939 [00:37<04:46,  5.38it/s]
 20%|██        | 397/1939 [00:37<04:59,  5.14it/s]
 21%|██        | 398/1939 [00:37<04:45,  5.40it/s]
 21%|██        | 400/1939 [00:37<03:14,  7.93it/s]
 21%|██        | 402/1939 [00:38<02:30, 10.23it/s]
 21%|██        | 404/1939 [00:38<02:22, 10.74it/s]
 21%|██        | 406/1939 [00:38<02:24, 10.60it/s]
 21%|██        | 408/1939 [00:38<02:25, 10.51it/s]
 21%|██        | 411/1939 [00:38<02:12, 11.57it/s]
 21%|██▏       | 413/1939 [00:39<02:57,  8.61it/s]
 21%|██▏       | 415/1939 [00:39<03:26,  7.39it/s]
 21%|██▏       | 416/1939 [00:39<03:49,  6.63it/s]
 22%|██▏       | 417/1939 [00:40<03:53,  6.53it/s]
 22%|██▏       | 419/1939 [00:40<03:36,  7.03it/s]
 22%|██▏       | 421/1939 [00:40<02:58,  8.48it/s]
 22%|██▏       | 422/1939 [00:40<03:41,  6.86it/s]
 22%|██▏       | 426/1939 [00:41<02:57,  8.50it/s]
 22%|██▏       | 428/1939 [00:41<03:11,  7.91it/s]
 22%|██▏       | 430/1939 [00:41<02:44,  9.18it/s]
 22%|██▏       | 433/1939 [00:41<02:02, 12.29it/s]
 23%|██▎       | 440/1939 [00:41<01:06, 22.43it/s]
 23%|██▎       | 444/1939 [00:41<01:00, 24.79it/s]
 23%|██▎       | 450/1939 [00:41<00:46, 31.72it/s]
 23%|██▎       | 455/1939 [00:42<00:43, 34.32it/s]
 24%|██▎       | 459/1939 [00:42<00:46, 32.17it/s]
 24%|██▍       | 466/1939 [00:42<00:36, 40.61it/s]
 24%|██▍       | 472/1939 [00:42<00:32, 44.76it/s]
 25%|██▍       | 478/1939 [00:42<00:31, 46.57it/s]
 25%|██▍       | 483/1939 [00:42<00:52, 27.70it/s]
 25%|██▌       | 487/1939 [00:42<00:49, 29.57it/s]
 25%|██▌       | 491/1939 [00:43<01:12, 20.10it/s]
 25%|██▌       | 494/1939 [00:43<01:22, 17.51it/s]
 26%|██▌       | 497/1939 [00:44<01:53, 12.66it/s]
 26%|██▌       | 499/1939 [00:44<01:47, 13.42it/s]
 26%|██▌       | 501/1939 [00:44<02:08, 11.19it/s]
 26%|██▌       | 503/1939 [00:44<01:58, 12.09it/s]
 26%|██▌       | 505/1939 [00:44<02:11, 10.95it/s]
 26%|██▌       | 508/1939 [00:44<01:42, 13.95it/s]
 26%|██▋       | 511/1939 [00:45<01:50, 12.96it/s]
 27%|██▋       | 514/1939 [00:45<01:31, 15.55it/s]
 27%|██▋       | 521/1939 [00:45<00:55, 25.39it/s]
 27%|██▋       | 528/1939 [00:45<00:44, 31.86it/s]
 27%|██▋       | 532/1939 [00:45<00:46, 30.21it/s]
 28%|██▊       | 537/1939 [00:46<01:04, 21.71it/s]
 28%|██▊       | 540/1939 [00:46<01:32, 15.14it/s]
 28%|██▊       | 544/1939 [00:46<01:16, 18.15it/s]
 28%|██▊       | 547/1939 [00:46<01:34, 14.80it/s]
 28%|██▊       | 550/1939 [00:47<01:43, 13.36it/s]
 28%|██▊       | 552/1939 [00:47<02:22,  9.70it/s]
 29%|██▊       | 554/1939 [00:47<02:14, 10.30it/s]
 29%|██▊       | 556/1939 [00:48<02:27,  9.38it/s]
 29%|██▉       | 558/1939 [00:48<02:11, 10.48it/s]
 29%|██▉       | 560/1939 [00:48<01:59, 11.54it/s]
 29%|██▉       | 562/1939 [00:48<02:54,  7.88it/s]
 29%|██▉       | 564/1939 [00:48<02:30,  9.13it/s]
 29%|██▉       | 567/1939 [00:49<01:57, 11.67it/s]
 29%|██▉       | 569/1939 [00:49<02:00, 11.38it/s]
 29%|██▉       | 571/1939 [00:49<02:42,  8.43it/s]
 30%|██▉       | 573/1939 [00:49<02:59,  7.61it/s]
 30%|██▉       | 574/1939 [00:50<03:31,  6.45it/s]
 30%|██▉       | 575/1939 [00:50<03:59,  5.70it/s]
 30%|██▉       | 578/1939 [00:50<02:33,  8.86it/s]
 30%|██▉       | 580/1939 [00:50<02:46,  8.17it/s]
 30%|███       | 582/1939 [00:51<03:01,  7.49it/s]
 30%|███       | 584/1939 [00:51<03:15,  6.94it/s]
 30%|███       | 585/1939 [00:51<03:07,  7.22it/s]
 30%|███       | 586/1939 [00:51<03:30,  6.41it/s]
 30%|███       | 589/1939 [00:52<02:50,  7.94it/s]
 31%|███       | 592/1939 [00:52<02:05, 10.73it/s]
 31%|███       | 594/1939 [00:52<02:15,  9.95it/s]
 31%|███       | 596/1939 [00:52<02:23,  9.34it/s]
 31%|███       | 599/1939 [00:53<02:21,  9.48it/s]
 31%|███       | 601/1939 [00:53<02:30,  8.88it/s]
 31%|███       | 603/1939 [00:53<02:09, 10.35it/s]
 31%|███▏      | 607/1939 [00:53<01:56, 11.44it/s]
 31%|███▏      | 609/1939 [00:54<02:44,  8.11it/s]
 32%|███▏      | 611/1939 [00:54<02:39,  8.30it/s]
 32%|███▏      | 612/1939 [00:54<03:06,  7.11it/s]
 32%|███▏      | 613/1939 [00:54<03:31,  6.26it/s]
 32%|███▏      | 614/1939 [00:55<03:34,  6.17it/s]
 32%|███▏      | 615/1939 [00:55<03:19,  6.65it/s]
 32%|███▏      | 616/1939 [00:55<03:53,  5.67it/s]
 32%|███▏      | 617/1939 [00:55<04:02,  5.46it/s]
 32%|███▏      | 618/1939 [00:55<03:42,  5.93it/s]
 32%|███▏      | 620/1939 [00:56<02:58,  7.38it/s]
 32%|███▏      | 621/1939 [00:56<02:55,  7.53it/s]
 32%|███▏      | 623/1939 [00:56<02:18,  9.50it/s]
 32%|███▏      | 629/1939 [00:56<01:05, 20.00it/s]
 33%|███▎      | 632/1939 [00:56<01:53, 11.53it/s]
 33%|███▎      | 634/1939 [00:57<01:45, 12.42it/s]
 33%|███▎      | 636/1939 [00:57<02:27,  8.83it/s]
 33%|███▎      | 638/1939 [00:57<02:23,  9.07it/s]
 33%|███▎      | 640/1939 [00:57<02:21,  9.21it/s]
 33%|███▎      | 643/1939 [00:58<02:08, 10.11it/s]
 33%|███▎      | 645/1939 [00:58<01:55, 11.19it/s]
 33%|███▎      | 649/1939 [00:58<01:41, 12.66it/s]
 34%|███▎      | 651/1939 [00:58<02:05, 10.23it/s]
 34%|███▎      | 654/1939 [00:59<02:07, 10.08it/s]
 34%|███▍      | 656/1939 [00:59<02:23,  8.96it/s]
 34%|███▍      | 658/1939 [00:59<02:31,  8.44it/s]
 34%|███▍      | 661/1939 [00:59<01:54, 11.20it/s]
 34%|███▍      | 665/1939 [01:00<01:45, 12.03it/s]
 34%|███▍      | 667/1939 [01:00<02:03, 10.26it/s]
 35%|███▍      | 671/1939 [01:00<01:27, 14.44it/s]
 35%|███▍      | 674/1939 [01:01<02:06,  9.98it/s]
 35%|███▍      | 676/1939 [01:01<02:15,  9.32it/s]
 35%|███▍      | 678/1939 [01:01<03:07,  6.73it/s]
 35%|███▌      | 680/1939 [01:02<02:58,  7.06it/s]
 35%|███▌      | 682/1939 [01:02<02:28,  8.44it/s]
 35%|███▌      | 684/1939 [01:02<02:27,  8.53it/s]
 35%|███▌      | 686/1939 [01:02<02:04, 10.05it/s]
 35%|███▌      | 688/1939 [01:02<02:29,  8.39it/s]
 36%|███▌      | 690/1939 [01:03<02:54,  7.18it/s]
 36%|███▌      | 693/1939 [01:03<02:35,  8.01it/s]
 36%|███▌      | 695/1939 [01:03<02:10,  9.52it/s]
 36%|███▌      | 700/1939 [01:03<01:19, 15.67it/s]
 36%|███▋      | 707/1939 [01:03<00:48, 25.23it/s]
 37%|███▋      | 714/1939 [01:03<00:37, 32.57it/s]
 37%|███▋      | 719/1939 [01:04<00:39, 31.26it/s]
 37%|███▋      | 725/1939 [01:04<00:43, 27.84it/s]
 38%|███▊      | 729/1939 [01:04<00:42, 28.66it/s]
 38%|███▊      | 733/1939 [01:05<01:27, 13.78it/s]
 38%|███▊      | 736/1939 [01:05<01:40, 11.98it/s]
 38%|███▊      | 739/1939 [01:05<01:35, 12.63it/s]
 38%|███▊      | 742/1939 [01:06<01:35, 12.56it/s]
 38%|███▊      | 744/1939 [01:06<01:28, 13.51it/s]
 38%|███▊      | 746/1939 [01:06<01:38, 12.16it/s]
 39%|███▊      | 749/1939 [01:06<01:43, 11.53it/s]
 39%|███▊      | 751/1939 [01:06<01:36, 12.32it/s]
 39%|███▉      | 754/1939 [01:06<01:26, 13.76it/s]
 39%|███▉      | 756/1939 [01:07<01:50, 10.71it/s]
 39%|███▉      | 758/1939 [01:07<02:09,  9.11it/s]
 39%|███▉      | 760/1939 [01:07<02:22,  8.25it/s]
 39%|███▉      | 763/1939 [01:08<02:13,  8.82it/s]
 40%|███▉      | 766/1939 [01:08<02:10,  8.97it/s]
 40%|███▉      | 767/1939 [01:08<02:41,  7.27it/s]
 40%|███▉      | 768/1939 [01:09<02:54,  6.69it/s]
 40%|███▉      | 769/1939 [01:09<03:17,  5.91it/s]
 40%|███▉      | 770/1939 [01:09<03:39,  5.32it/s]
 40%|███▉      | 771/1939 [01:09<03:55,  4.96it/s]
 40%|███▉      | 772/1939 [01:10<04:14,  4.59it/s]
 40%|███▉      | 773/1939 [01:10<04:06,  4.73it/s]
 40%|████      | 776/1939 [01:10<02:53,  6.70it/s]
 40%|████      | 777/1939 [01:10<03:20,  5.79it/s]
 40%|████      | 779/1939 [01:11<03:08,  6.14it/s]
 40%|████      | 780/1939 [01:11<03:33,  5.43it/s]
 40%|████      | 783/1939 [01:11<02:17,  8.38it/s]
 40%|████      | 785/1939 [01:11<02:36,  7.38it/s]
 41%|████      | 787/1939 [01:12<02:35,  7.40it/s]
 41%|████      | 789/1939 [01:12<02:24,  7.96it/s]
 41%|████      | 792/1939 [01:12<01:47, 10.64it/s]
 41%|████      | 794/1939 [01:12<01:53, 10.08it/s]
 41%|████      | 797/1939 [01:12<01:28, 12.92it/s]
 41%|████      | 799/1939 [01:13<01:36, 11.80it/s]
 41%|████▏     | 801/1939 [01:13<01:48, 10.51it/s]
 41%|████▏     | 804/1939 [01:13<01:51, 10.21it/s]
 42%|████▏     | 806/1939 [01:13<01:58,  9.57it/s]
 42%|████▏     | 808/1939 [01:13<01:48, 10.42it/s]
 42%|████▏     | 810/1939 [01:14<01:53,  9.91it/s]
 42%|████▏     | 812/1939 [01:14<01:51, 10.08it/s]
 42%|████▏     | 814/1939 [01:14<02:15,  8.29it/s]
 42%|████▏     | 816/1939 [01:14<02:11,  8.55it/s]
 42%|████▏     | 817/1939 [01:15<02:21,  7.92it/s]
 42%|████▏     | 818/1939 [01:15<02:39,  7.01it/s]
 42%|████▏     | 819/1939 [01:15<03:04,  6.08it/s]
 42%|████▏     | 820/1939 [01:15<03:24,  5.46it/s]
 42%|████▏     | 821/1939 [01:16<03:21,  5.54it/s]
 42%|████▏     | 822/1939 [01:16<03:42,  5.02it/s]
 42%|████▏     | 823/1939 [01:16<03:20,  5.56it/s]
 43%|████▎     | 825/1939 [01:16<02:46,  6.69it/s]
 43%|████▎     | 826/1939 [01:16<02:43,  6.83it/s]
 43%|████▎     | 828/1939 [01:16<02:03,  9.02it/s]
 43%|████▎     | 829/1939 [01:17<02:20,  7.92it/s]
 43%|████▎     | 832/1939 [01:17<01:32, 12.01it/s]
 43%|████▎     | 834/1939 [01:17<01:35, 11.58it/s]
 43%|████▎     | 836/1939 [01:17<01:22, 13.33it/s]
 43%|████▎     | 838/1939 [01:17<01:18, 14.11it/s]
 43%|████▎     | 840/1939 [01:17<01:37, 11.27it/s]
 44%|████▎     | 844/1939 [01:18<01:17, 14.17it/s]
 44%|████▎     | 846/1939 [01:18<01:17, 14.12it/s]
 44%|████▎     | 848/1939 [01:18<01:12, 15.15it/s]
 44%|████▍     | 851/1939 [01:18<01:20, 13.60it/s]
 44%|████▍     | 854/1939 [01:18<01:32, 11.74it/s]
 44%|████▍     | 856/1939 [01:18<01:26, 12.58it/s]
 44%|████▍     | 858/1939 [01:19<01:58,  9.16it/s]
 44%|████▍     | 860/1939 [01:19<02:06,  8.52it/s]
 44%|████▍     | 862/1939 [01:19<02:22,  7.54it/s]
 45%|████▍     | 863/1939 [01:20<02:33,  7.03it/s]
 45%|████▍     | 864/1939 [01:20<02:44,  6.54it/s]
 45%|████▍     | 866/1939 [01:20<02:07,  8.40it/s]
 45%|████▍     | 869/1939 [01:20<01:31, 11.72it/s]
 45%|████▌     | 876/1939 [01:20<00:46, 22.84it/s]
 45%|████▌     | 880/1939 [01:20<00:43, 24.53it/s]
 46%|████▌     | 887/1939 [01:21<00:33, 31.36it/s]
 46%|████▌     | 893/1939 [01:21<00:27, 37.40it/s]
 46%|████▋     | 900/1939 [01:21<00:36, 28.25it/s]
 47%|████▋     | 904/1939 [01:22<01:02, 16.47it/s]
 47%|████▋     | 907/1939 [01:22<00:58, 17.70it/s]
 47%|████▋     | 910/1939 [01:22<01:04, 15.91it/s]
 47%|████▋     | 913/1939 [01:22<01:08, 14.93it/s]
 47%|████▋     | 915/1939 [01:22<01:11, 14.26it/s]
 47%|████▋     | 917/1939 [01:22<01:08, 15.01it/s]
 47%|████▋     | 919/1939 [01:23<01:33, 10.96it/s]
 48%|████▊     | 922/1939 [01:23<01:18, 12.99it/s]
 48%|████▊     | 925/1939 [01:23<01:04, 15.73it/s]
 48%|████▊     | 927/1939 [01:23<01:13, 13.86it/s]
 48%|████▊     | 930/1939 [01:23<01:15, 13.39it/s]
 48%|████▊     | 932/1939 [01:24<01:30, 11.15it/s]
 48%|████▊     | 934/1939 [01:24<01:46,  9.43it/s]
 48%|████▊     | 936/1939 [01:24<01:33, 10.74it/s]
 49%|████▊     | 943/1939 [01:24<00:48, 20.48it/s]
 49%|████▉     | 946/1939 [01:24<00:45, 21.69it/s]
 49%|████▉     | 951/1939 [01:25<00:37, 26.33it/s]
 49%|████▉     | 957/1939 [01:25<00:31, 31.67it/s]
 50%|████▉     | 961/1939 [01:25<00:39, 24.68it/s]
 50%|████▉     | 964/1939 [01:25<00:43, 22.21it/s]
 50%|████▉     | 968/1939 [01:25<00:47, 20.37it/s]
 50%|█████     | 971/1939 [01:26<01:13, 13.17it/s]
 50%|█████     | 973/1939 [01:26<01:39,  9.74it/s]
 50%|█████     | 975/1939 [01:26<01:34, 10.17it/s]
 50%|█████     | 977/1939 [01:27<01:33, 10.29it/s]
 50%|█████     | 979/1939 [01:27<01:27, 11.03it/s]
 51%|█████     | 981/1939 [01:27<01:24, 11.34it/s]
 51%|█████     | 983/1939 [01:27<01:33, 10.20it/s]
 51%|█████     | 985/1939 [01:27<01:21, 11.71it/s]
 51%|█████     | 987/1939 [01:27<01:23, 11.34it/s]
 51%|█████     | 989/1939 [01:28<01:19, 11.92it/s]
 51%|█████     | 991/1939 [01:28<01:33, 10.11it/s]
 51%|█████     | 993/1939 [01:28<01:45,  8.97it/s]
 51%|█████▏    | 995/1939 [01:28<01:34,  9.95it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 314.77it/s]
 67%|██████▋   | 201/300 [09:01<48:00, 29.10s/it]

[[np.int64(0), False, 1], [np.int64(1), False, 10], [np.int64(2), False, 12], [np.int64(3), False, 9], [np.int64(4), False, 10], [np.int64(5), False, 0], [np.int64(6), False, 10], [np.int64(7), False, 11], [np.int64(8), False, 3], [np.int64(11), False, 9], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2160, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.2605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3192, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 202/300 [09:01<38:23, 23.51s/it]

tensor(12.2592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4297, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [09:01<22:34, 14.11s/it]

tensor(12.2585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3418, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>)

 69%|██████▊   | 206/300 [09:02<13:16,  8.47s/it]

tensor(-5.4207, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4478, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4740, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:02<06:32,  4.31s/it]

tensor(12.2524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4825, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>)

 70%|███████   | 210/300 [09:02<05:01,  3.35s/it]

tensor(-5.5050, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0387, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5210, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5225, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [09:02<03:02,  2.07s/it]

tensor(12.2634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5406, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:02<02:22,  1.64s/it]

tensor(12.2614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5507, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5602, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [09:03<01:28,  1.04s/it]

tensor(12.2479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5606, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [09:03<00:55,  1.50it/s]

tensor(12.2422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5597, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [09:03<00:42,  1.91it/s]

tensor(12.2391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5601, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:03<00:33,  2.43it/s]

tensor(12.2372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5556, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [09:03<00:26,  3.06it/s]

tensor(12.2337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5574, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2297, device='cuda:0', grad_fn=<AddBackward0>)

 74%|███████▎  | 221/300 [09:03<00:20,  3.79it/s]

tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5655, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [09:03<00:17,  4.52it/s]

tensor(12.2257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5813, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [09:03<00:14,  5.36it/s]

tensor(12.2227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5866, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [09:04<00:12,  6.19it/s]

tensor(12.2207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5888, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:04<00:10,  6.96it/s]

tensor(12.2187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2166, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5980, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>)

 76%|███████▌  | 227/300 [09:04<00:09,  8.08it/s]

tensor(-5.5992, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5957, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5955, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:04<00:08,  8.74it/s]

tensor(12.2083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5977, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>)

 77%|███████▋  | 231/300 [09:04<00:07,  9.18it/s]

tensor(-5.5966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5961, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5931, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [09:05<00:06,  9.55it/s]

tensor(12.1991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5940, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:05<00:06,  9.64it/s]

tensor(12.1967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5902, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5923, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5905, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:05<00:06,  9.80it/s]

tensor(12.1907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5869, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5877, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [09:05<00:06,  9.80it/s]

tensor(12.1868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5880, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:05<00:05,  9.85it/s]

tensor(12.1834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5905, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5916, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:06<00:05,  9.88it/s]

tensor(12.1801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5919, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5948, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [09:06<00:05,  9.86it/s]

tensor(12.1763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5937, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5908, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [09:06<00:05,  9.85it/s]

tensor(12.1729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5925, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [09:06<00:05,  9.83it/s]

tensor(12.1692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5908, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([209,  88, 139, 143, 257, 296,  85,  24, 143, 140, 195,  33,  83, 104])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:40, 19.27it/s]
  0%|          | 8/1939 [00:00<00:46, 41.24it/s]
  1%|          | 15/1939 [00:00<00:36, 52.29it/s]
  1%|          | 21/1939 [00:00<00:41, 46.21it/s]
  1%|▏         | 28/1939 [00:00<00:38, 49.00it/s]
  2%|▏         | 33/1939 [00:00<00:41, 45.72it/s]
  2%|▏         | 38/1939 [00:00<00:50, 37.82it/s]
  2%|▏         | 42/1939 [00:01<01:25, 22.13it/s]
  2%|▏         | 46/1939 [00:01<01:22, 22.82it/s]
  3%|▎         | 49/1939 [00:01<01:31, 20.74it/s]
  3%|▎         | 52/1939 [00:01<01:32, 20.39it/s]
  3%|▎         | 55/1939 [00:02<02:31, 12.46it/s]
  3%|▎         | 57/1939 [00:02<02:47, 11.24it/s]
  3%|▎         | 59/1939 [00:02<02:46, 11.30it/s]
  3%|▎         | 61/1939 [00:02<02:33, 12.26it/s]
  3%|▎         | 64/1939 [00:03<02:09, 14.45it/s]
  3%|▎         | 66/1939 [00:03<03:09,  9.90it/s]
  4%|▎         | 69/1939 [00:03<02:26, 12.77it/s]
  4%|▎         | 71/1939 [00:03<02:52, 10.84it/s]
  4%|▍         | 73/1939 [00:04<03:47,  8.19it/s]
  4%|▍         | 76/1939 [00:04<02:54, 10.65it/s]
  4%|▍         | 78/1939 [00:04<03:35,  8.64it/s]
  4%|▍         | 80/1939 [00:05<05:00,  6.19it/s]
  4%|▍         | 81/1939 [00:05<05:10,  5.99it/s]
  4%|▍         | 82/1939 [00:05<05:20,  5.80it/s]
  4%|▍         | 83/1939 [00:05<05:26,  5.69it/s]
  4%|▍         | 86/1939 [00:06<04:59,  6.18it/s]
  5%|▍         | 89/1939 [00:06<03:23,  9.07it/s]
  5%|▍         | 94/1939 [00:06<02:28, 12.46it/s]
  5%|▍         | 96/1939 [00:06<02:46, 11.04it/s]
  5%|▌         | 99/1939 [00:07<02:15, 13.53it/s]
  5%|▌         | 101/1939 [00:07<03:48,  8.04it/s]
  5%|▌         | 103/1939 [00:07<03:15,  9.40it/s]
  5%|▌         | 105/1939 [00:07<03:21,  9.12it/s]
  6%|▌         | 107/1939 [00:08<03:07,  9.80it/s]
  6%|▌         | 110/1939 [00:08<02:39, 11.45it/s]
  6%|▌         | 112/1939 [00:08<02:23, 12.69it/s]
  6%|▌         | 115/1939 [00:08<02:22, 12.77it/s]
  6%|▌         | 117/1939 [00:08<02:24, 12.58it/s]
  6%|▌         | 119/1939 [00:09<03:24,  8.92it/s]
  6%|▌         | 121/1939 [00:09<04:51,  6.24it/s]
  6%|▋         | 124/1939 [00:09<03:30,  8.62it/s]
  7%|▋         | 128/1939 [00:10<02:52, 10.50it/s]
  7%|▋         | 130/1939 [00:10<02:35, 11.61it/s]
  7%|▋         | 132/1939 [00:10<03:21,  8.97it/s]
  7%|▋         | 135/1939 [00:10<03:18,  9.09it/s]
  7%|▋         | 137/1939 [00:11<04:04,  7.36it/s]
  7%|▋         | 138/1939 [00:11<04:25,  6.78it/s]
  7%|▋         | 139/1939 [00:11<04:45,  6.31it/s]
  7%|▋         | 141/1939 [00:12<04:21,  6.89it/s]
  7%|▋         | 142/1939 [00:12<05:43,  5.24it/s]
  7%|▋         | 145/1939 [00:12<05:13,  5.72it/s]
  8%|▊         | 147/1939 [00:13<04:09,  7.18it/s]
  8%|▊         | 149/1939 [00:13<03:38,  8.20it/s]
  8%|▊         | 151/1939 [00:13<03:36,  8.24it/s]
  8%|▊         | 153/1939 [00:13<04:01,  7.40it/s]
  8%|▊         | 155/1939 [00:13<03:17,  9.05it/s]
  8%|▊         | 157/1939 [00:14<03:49,  7.78it/s]
  8%|▊         | 158/1939 [00:14<04:51,  6.11it/s]
  8%|▊         | 159/1939 [00:14<04:49,  6.15it/s]
  8%|▊         | 160/1939 [00:15<06:07,  4.84it/s]
  8%|▊         | 161/1939 [00:15<06:19,  4.68it/s]
  8%|▊         | 162/1939 [00:15<05:39,  5.24it/s]
  8%|▊         | 163/1939 [00:15<05:32,  5.34it/s]
  8%|▊         | 164/1939 [00:15<05:49,  5.08it/s]
  9%|▊         | 166/1939 [00:15<04:10,  7.08it/s]
  9%|▉         | 171/1939 [00:16<02:02, 14.46it/s]
  9%|▉         | 177/1939 [00:16<01:15, 23.22it/s]
  9%|▉         | 180/1939 [00:16<01:13, 23.95it/s]
 10%|▉         | 185/1939 [00:16<00:59, 29.42it/s]
 10%|▉         | 189/1939 [00:16<00:55, 31.28it/s]
 10%|█         | 195/1939 [00:16<00:45, 38.41it/s]
 10%|█         | 200/1939 [00:16<00:47, 36.72it/s]
 11%|█         | 204/1939 [00:17<01:59, 14.55it/s]
 11%|█         | 207/1939 [00:18<02:49, 10.20it/s]
 11%|█         | 210/1939 [00:18<02:29, 11.59it/s]
 11%|█         | 213/1939 [00:18<03:20,  8.59it/s]
 11%|█         | 215/1939 [00:18<03:03,  9.38it/s]
 11%|█         | 218/1939 [00:19<02:51, 10.06it/s]
 11%|█▏        | 221/1939 [00:19<02:22, 12.09it/s]
 12%|█▏        | 223/1939 [00:19<02:35, 11.01it/s]
 12%|█▏        | 225/1939 [00:19<02:56,  9.72it/s]
 12%|█▏        | 228/1939 [00:20<03:19,  8.58it/s]
 12%|█▏        | 230/1939 [00:20<02:54,  9.78it/s]
 12%|█▏        | 233/1939 [00:20<03:09,  9.00it/s]
 12%|█▏        | 235/1939 [00:20<02:44, 10.34it/s]
 12%|█▏        | 237/1939 [00:21<03:21,  8.45it/s]
 12%|█▏        | 239/1939 [00:21<03:57,  7.15it/s]
 12%|█▏        | 240/1939 [00:22<04:52,  5.80it/s]
 12%|█▏        | 241/1939 [00:22<05:00,  5.66it/s]
 12%|█▏        | 242/1939 [00:22<06:00,  4.70it/s]
 13%|█▎        | 243/1939 [00:22<06:03,  4.66it/s]
 13%|█▎        | 244/1939 [00:23<06:24,  4.41it/s]
 13%|█▎        | 245/1939 [00:23<07:24,  3.81it/s]
 13%|█▎        | 246/1939 [00:23<07:17,  3.87it/s]
 13%|█▎        | 248/1939 [00:24<07:12,  3.91it/s]
 13%|█▎        | 250/1939 [00:24<05:47,  4.87it/s]
 13%|█▎        | 251/1939 [00:24<05:49,  4.82it/s]
 13%|█▎        | 254/1939 [00:24<03:32,  7.94it/s]
 13%|█▎        | 258/1939 [00:24<02:38, 10.63it/s]
 13%|█▎        | 260/1939 [00:25<03:19,  8.43it/s]
 14%|█▎        | 262/1939 [00:25<02:48,  9.94it/s]
 14%|█▎        | 264/1939 [00:26<04:18,  6.49it/s]
 14%|█▍        | 268/1939 [00:26<03:29,  7.96it/s]
 14%|█▍        | 270/1939 [00:26<03:28,  7.99it/s]
 14%|█▍        | 273/1939 [00:26<03:12,  8.67it/s]
 14%|█▍        | 275/1939 [00:27<03:17,  8.43it/s]
 14%|█▍        | 279/1939 [00:27<02:13, 12.44it/s]
 14%|█▍        | 281/1939 [00:27<02:50,  9.72it/s]
 15%|█▍        | 284/1939 [00:28<03:10,  8.68it/s]
 15%|█▍        | 286/1939 [00:28<03:19,  8.27it/s]
 15%|█▍        | 288/1939 [00:28<03:57,  6.95it/s]
 15%|█▌        | 291/1939 [00:28<02:59,  9.19it/s]
 15%|█▌        | 293/1939 [00:29<02:55,  9.40it/s]
 15%|█▌        | 296/1939 [00:29<02:48,  9.75it/s]
 15%|█▌        | 298/1939 [00:29<02:52,  9.52it/s]
 15%|█▌        | 300/1939 [00:29<02:28, 11.01it/s]
 16%|█▌        | 303/1939 [00:29<02:16, 11.95it/s]
 16%|█▌        | 305/1939 [00:30<02:02, 13.30it/s]
 16%|█▌        | 307/1939 [00:30<02:15, 12.08it/s]
 16%|█▌        | 309/1939 [00:30<02:01, 13.37it/s]
 16%|█▌        | 312/1939 [00:30<01:59, 13.62it/s]
 16%|█▌        | 315/1939 [00:30<02:15, 11.94it/s]
 16%|█▋        | 317/1939 [00:31<03:03,  8.84it/s]
 16%|█▋        | 319/1939 [00:31<03:45,  7.19it/s]
 17%|█▋        | 320/1939 [00:31<04:07,  6.53it/s]
 17%|█▋        | 321/1939 [00:32<05:19,  5.06it/s]
 17%|█▋        | 322/1939 [00:32<06:17,  4.29it/s]
 17%|█▋        | 325/1939 [00:32<03:56,  6.81it/s]
 17%|█▋        | 327/1939 [00:33<03:29,  7.68it/s]
 17%|█▋        | 329/1939 [00:33<02:56,  9.15it/s]
 17%|█▋        | 332/1939 [00:33<02:10, 12.28it/s]
 17%|█▋        | 338/1939 [00:33<01:21, 19.70it/s]
 18%|█▊        | 341/1939 [00:33<01:13, 21.63it/s]
 18%|█▊        | 348/1939 [00:33<00:49, 32.29it/s]
 18%|█▊        | 352/1939 [00:34<01:54, 13.82it/s]
 18%|█▊        | 355/1939 [00:34<02:19, 11.39it/s]
 18%|█▊        | 358/1939 [00:34<02:05, 12.56it/s]
 19%|█▊        | 361/1939 [00:35<02:06, 12.43it/s]
 19%|█▊        | 363/1939 [00:35<02:20, 11.21it/s]
 19%|█▉        | 365/1939 [00:35<02:11, 11.95it/s]
 19%|█▉        | 367/1939 [00:35<02:19, 11.23it/s]
 19%|█▉        | 369/1939 [00:35<02:04, 12.60it/s]
 19%|█▉        | 371/1939 [00:36<02:12, 11.81it/s]
 19%|█▉        | 373/1939 [00:36<02:43,  9.60it/s]
 19%|█▉        | 376/1939 [00:36<02:45,  9.45it/s]
 19%|█▉        | 378/1939 [00:36<02:46,  9.35it/s]
 20%|█▉        | 381/1939 [00:37<02:59,  8.68it/s]
 20%|█▉        | 383/1939 [00:37<02:36,  9.95it/s]
 20%|█▉        | 385/1939 [00:37<02:41,  9.62it/s]
 20%|█▉        | 387/1939 [00:37<03:02,  8.51it/s]
 20%|██        | 388/1939 [00:38<04:04,  6.35it/s]
 20%|██        | 389/1939 [00:38<04:31,  5.71it/s]
 20%|██        | 390/1939 [00:38<04:38,  5.56it/s]
 20%|██        | 391/1939 [00:38<04:18,  6.00it/s]
 20%|██        | 393/1939 [00:39<04:36,  5.58it/s]
 20%|██        | 394/1939 [00:39<05:06,  5.05it/s]
 20%|██        | 396/1939 [00:39<04:44,  5.43it/s]
 21%|██        | 398/1939 [00:40<04:02,  6.36it/s]
 21%|██        | 400/1939 [00:40<03:12,  8.01it/s]
 21%|██        | 402/1939 [00:40<02:35,  9.87it/s]
 21%|██        | 405/1939 [00:40<02:09, 11.84it/s]
 21%|██        | 407/1939 [00:40<02:38,  9.64it/s]
 21%|██        | 409/1939 [00:40<02:23, 10.68it/s]
 21%|██        | 411/1939 [00:41<02:53,  8.82it/s]
 21%|██▏       | 413/1939 [00:41<02:43,  9.34it/s]
 21%|██▏       | 415/1939 [00:41<03:14,  7.82it/s]
 21%|██▏       | 416/1939 [00:41<03:27,  7.33it/s]
 22%|██▏       | 417/1939 [00:42<03:57,  6.40it/s]
 22%|██▏       | 419/1939 [00:42<03:53,  6.52it/s]
 22%|██▏       | 421/1939 [00:42<03:05,  8.19it/s]
 22%|██▏       | 422/1939 [00:42<04:16,  5.91it/s]
 22%|██▏       | 425/1939 [00:43<02:46,  9.11it/s]
 22%|██▏       | 428/1939 [00:43<03:02,  8.28it/s]
 22%|██▏       | 431/1939 [00:43<02:21, 10.69it/s]
 22%|██▏       | 436/1939 [00:43<01:31, 16.45it/s]
 23%|██▎       | 444/1939 [00:43<00:54, 27.35it/s]
 23%|██▎       | 452/1939 [00:43<00:41, 36.25it/s]
 24%|██▎       | 458/1939 [00:44<00:36, 41.03it/s]
 24%|██▍       | 463/1939 [00:44<00:35, 41.09it/s]
 24%|██▍       | 470/1939 [00:44<00:33, 43.24it/s]
 25%|██▍       | 477/1939 [00:44<00:29, 48.76it/s]
 25%|██▍       | 483/1939 [00:44<00:54, 26.57it/s]
 25%|██▌       | 490/1939 [00:45<00:54, 26.54it/s]
 25%|██▌       | 494/1939 [00:45<01:08, 21.14it/s]
 26%|██▌       | 497/1939 [00:46<01:39, 14.53it/s]
 26%|██▌       | 500/1939 [00:46<01:44, 13.76it/s]
 26%|██▌       | 503/1939 [00:46<01:33, 15.30it/s]
 26%|██▌       | 506/1939 [00:46<01:41, 14.15it/s]
 26%|██▋       | 511/1939 [00:46<01:15, 18.98it/s]
 27%|██▋       | 516/1939 [00:46<00:59, 24.02it/s]
 27%|██▋       | 522/1939 [00:46<00:46, 30.40it/s]
 27%|██▋       | 527/1939 [00:47<00:40, 34.47it/s]
 28%|██▊       | 534/1939 [00:47<00:33, 41.60it/s]
 28%|██▊       | 539/1939 [00:48<01:28, 15.87it/s]
 28%|██▊       | 543/1939 [00:48<01:19, 17.57it/s]
 28%|██▊       | 547/1939 [00:48<01:33, 14.85it/s]
 28%|██▊       | 550/1939 [00:48<01:48, 12.84it/s]
 29%|██▊       | 553/1939 [00:49<02:39,  8.71it/s]
 29%|██▊       | 556/1939 [00:49<02:40,  8.61it/s]
 29%|██▉       | 558/1939 [00:50<02:46,  8.29it/s]
 29%|██▉       | 560/1939 [00:50<02:27,  9.33it/s]
 29%|██▉       | 562/1939 [00:50<03:02,  7.54it/s]
 29%|██▉       | 565/1939 [00:50<02:20,  9.78it/s]
 29%|██▉       | 568/1939 [00:51<02:06, 10.83it/s]
 29%|██▉       | 570/1939 [00:51<01:54, 11.99it/s]
 29%|██▉       | 572/1939 [00:51<03:04,  7.42it/s]
 30%|██▉       | 574/1939 [00:52<03:22,  6.73it/s]
 30%|██▉       | 575/1939 [00:52<04:13,  5.39it/s]
 30%|██▉       | 577/1939 [00:52<03:19,  6.84it/s]
 30%|██▉       | 579/1939 [00:53<03:33,  6.37it/s]
 30%|███       | 582/1939 [00:53<03:27,  6.53it/s]
 30%|███       | 584/1939 [00:53<03:54,  5.79it/s]
 30%|███       | 586/1939 [00:54<04:00,  5.63it/s]
 30%|███       | 589/1939 [00:54<03:16,  6.87it/s]
 31%|███       | 592/1939 [00:54<02:51,  7.85it/s]
 31%|███       | 593/1939 [00:55<03:04,  7.29it/s]
 31%|███       | 595/1939 [00:55<03:00,  7.46it/s]
 31%|███       | 599/1939 [00:55<02:34,  8.65it/s]
 31%|███       | 601/1939 [00:55<02:28,  9.03it/s]
 31%|███       | 603/1939 [00:56<02:10, 10.21it/s]
 31%|███▏      | 607/1939 [00:56<02:18,  9.60it/s]
 31%|███▏      | 609/1939 [00:57<03:18,  6.69it/s]
 32%|███▏      | 611/1939 [00:57<03:38,  6.07it/s]
 32%|███▏      | 612/1939 [00:57<04:15,  5.18it/s]
 32%|███▏      | 613/1939 [00:58<04:26,  4.97it/s]
 32%|███▏      | 614/1939 [00:58<04:42,  4.68it/s]
 32%|███▏      | 615/1939 [00:58<04:25,  4.98it/s]
 32%|███▏      | 616/1939 [00:58<04:55,  4.48it/s]
 32%|███▏      | 617/1939 [00:59<05:52,  3.75it/s]
 32%|███▏      | 618/1939 [00:59<06:14,  3.53it/s]
 32%|███▏      | 620/1939 [00:59<05:16,  4.16it/s]
 32%|███▏      | 622/1939 [01:00<03:42,  5.91it/s]
 32%|███▏      | 627/1939 [01:00<01:49, 11.96it/s]
 32%|███▏      | 630/1939 [01:00<02:07, 10.29it/s]
 33%|███▎      | 632/1939 [01:00<02:13,  9.77it/s]
 33%|███▎      | 635/1939 [01:00<01:48, 12.07it/s]
 33%|███▎      | 637/1939 [01:01<02:28,  8.78it/s]
 33%|███▎      | 639/1939 [01:01<02:10,  9.93it/s]
 33%|███▎      | 641/1939 [01:01<02:23,  9.05it/s]
 33%|███▎      | 643/1939 [01:01<02:34,  8.41it/s]
 33%|███▎      | 646/1939 [01:02<01:56, 11.11it/s]
 33%|███▎      | 649/1939 [01:02<02:14,  9.61it/s]
 34%|███▎      | 651/1939 [01:02<01:58, 10.84it/s]
 34%|███▍      | 656/1939 [01:02<01:50, 11.61it/s]
 34%|███▍      | 658/1939 [01:03<02:19,  9.15it/s]
 34%|███▍      | 661/1939 [01:03<01:53, 11.29it/s]
 34%|███▍      | 665/1939 [01:03<01:37, 13.08it/s]
 34%|███▍      | 667/1939 [01:04<02:08,  9.91it/s]
 35%|███▍      | 669/1939 [01:04<02:13,  9.50it/s]
 35%|███▍      | 672/1939 [01:04<02:34,  8.19it/s]
 35%|███▍      | 673/1939 [01:04<02:36,  8.11it/s]
 35%|███▍      | 675/1939 [01:05<02:13,  9.44it/s]
 35%|███▍      | 677/1939 [01:05<02:04, 10.18it/s]
 35%|███▌      | 679/1939 [01:05<02:11,  9.55it/s]
 35%|███▌      | 681/1939 [01:05<02:06,  9.98it/s]
 35%|███▌      | 683/1939 [01:05<02:30,  8.32it/s]
 35%|███▌      | 685/1939 [01:06<02:05, 10.00it/s]
 35%|███▌      | 687/1939 [01:06<02:52,  7.25it/s]
 36%|███▌      | 689/1939 [01:06<03:15,  6.38it/s]
 36%|███▌      | 692/1939 [01:07<02:20,  8.85it/s]
 36%|███▌      | 699/1939 [01:07<01:12, 17.17it/s]
 36%|███▋      | 704/1939 [01:07<00:56, 21.79it/s]
 37%|███▋      | 710/1939 [01:07<00:43, 28.50it/s]
 37%|███▋      | 718/1939 [01:07<00:31, 38.89it/s]
 37%|███▋      | 724/1939 [01:07<00:33, 36.57it/s]
 38%|███▊      | 730/1939 [01:08<00:44, 26.94it/s]
 38%|███▊      | 734/1939 [01:08<01:29, 13.52it/s]
 38%|███▊      | 737/1939 [01:09<01:22, 14.58it/s]
 38%|███▊      | 740/1939 [01:09<01:23, 14.33it/s]
 38%|███▊      | 743/1939 [01:09<01:50, 10.82it/s]
 38%|███▊      | 745/1939 [01:09<01:45, 11.33it/s]
 39%|███▊      | 748/1939 [01:09<01:30, 13.19it/s]
 39%|███▊      | 750/1939 [01:10<01:36, 12.29it/s]
 39%|███▉      | 752/1939 [01:10<01:42, 11.54it/s]
 39%|███▉      | 754/1939 [01:10<01:35, 12.42it/s]
 39%|███▉      | 756/1939 [01:10<02:22,  8.30it/s]
 39%|███▉      | 758/1939 [01:11<02:56,  6.71it/s]
 39%|███▉      | 760/1939 [01:11<03:15,  6.02it/s]
 39%|███▉      | 762/1939 [01:11<02:36,  7.51it/s]
 39%|███▉      | 764/1939 [01:12<02:50,  6.88it/s]
 40%|███▉      | 766/1939 [01:12<02:40,  7.30it/s]
 40%|███▉      | 767/1939 [01:12<02:55,  6.68it/s]
 40%|███▉      | 768/1939 [01:12<02:59,  6.54it/s]
 40%|███▉      | 769/1939 [01:13<03:03,  6.36it/s]
 40%|███▉      | 770/1939 [01:13<02:55,  6.65it/s]
 40%|███▉      | 771/1939 [01:13<02:53,  6.72it/s]
 40%|███▉      | 772/1939 [01:13<04:35,  4.23it/s]
 40%|███▉      | 773/1939 [01:14<04:28,  4.34it/s]
 40%|███▉      | 775/1939 [01:14<03:02,  6.40it/s]
 40%|████      | 776/1939 [01:14<03:57,  4.89it/s]
 40%|████      | 777/1939 [01:14<04:48,  4.02it/s]
 40%|████      | 779/1939 [01:15<04:35,  4.21it/s]
 40%|████      | 780/1939 [01:15<04:34,  4.23it/s]
 40%|████      | 782/1939 [01:15<03:09,  6.10it/s]
 40%|████      | 784/1939 [01:16<03:18,  5.83it/s]
 41%|████      | 786/1939 [01:16<02:31,  7.61it/s]
 41%|████      | 788/1939 [01:16<02:19,  8.25it/s]
 41%|████      | 790/1939 [01:16<02:21,  8.14it/s]
 41%|████      | 794/1939 [01:16<01:46, 10.77it/s]
 41%|████      | 797/1939 [01:17<01:26, 13.15it/s]
 41%|████      | 799/1939 [01:17<01:48, 10.49it/s]
 41%|████▏     | 801/1939 [01:17<01:48, 10.52it/s]
 41%|████▏     | 804/1939 [01:17<02:05,  9.06it/s]
 42%|████▏     | 806/1939 [01:18<02:31,  7.48it/s]
 42%|████▏     | 809/1939 [01:18<02:44,  6.85it/s]
 42%|████▏     | 812/1939 [01:19<02:45,  6.80it/s]
 42%|████▏     | 813/1939 [01:19<03:22,  5.57it/s]
 42%|████▏     | 815/1939 [01:19<02:40,  6.99it/s]
 42%|████▏     | 817/1939 [01:20<03:56,  4.75it/s]
 42%|████▏     | 818/1939 [01:20<04:27,  4.19it/s]
 42%|████▏     | 819/1939 [01:21<04:59,  3.74it/s]
 42%|████▏     | 820/1939 [01:21<05:33,  3.35it/s]
 42%|████▏     | 821/1939 [01:22<05:54,  3.16it/s]
 42%|████▏     | 822/1939 [01:22<06:11,  3.01it/s]
 42%|████▏     | 823/1939 [01:22<06:36,  2.82it/s]
 43%|████▎     | 825/1939 [01:23<05:26,  3.42it/s]
 43%|████▎     | 826/1939 [01:23<04:48,  3.86it/s]
 43%|████▎     | 828/1939 [01:23<03:21,  5.52it/s]
 43%|████▎     | 829/1939 [01:23<03:06,  5.95it/s]
 43%|████▎     | 831/1939 [01:23<02:19,  7.95it/s]
 43%|████▎     | 834/1939 [01:23<01:43, 10.67it/s]
 43%|████▎     | 836/1939 [01:24<01:28, 12.42it/s]
 43%|████▎     | 838/1939 [01:24<01:20, 13.76it/s]
 43%|████▎     | 840/1939 [01:24<01:22, 13.25it/s]
 43%|████▎     | 842/1939 [01:24<01:14, 14.67it/s]
 44%|████▎     | 844/1939 [01:24<01:10, 15.49it/s]
 44%|████▎     | 848/1939 [01:24<00:54, 19.97it/s]
 44%|████▍     | 851/1939 [01:24<01:05, 16.60it/s]
 44%|████▍     | 853/1939 [01:25<01:04, 16.96it/s]
 44%|████▍     | 855/1939 [01:25<01:02, 17.25it/s]
 44%|████▍     | 857/1939 [01:25<01:10, 15.29it/s]
 44%|████▍     | 859/1939 [01:25<01:29, 12.02it/s]
 44%|████▍     | 861/1939 [01:25<01:44, 10.28it/s]
 45%|████▍     | 863/1939 [01:26<02:25,  7.37it/s]
 45%|████▍     | 864/1939 [01:26<02:34,  6.97it/s]
 45%|████▍     | 867/1939 [01:26<01:47,  9.94it/s]
 45%|████▌     | 873/1939 [01:26<00:59, 17.98it/s]
 45%|████▌     | 879/1939 [01:26<00:43, 24.60it/s]
 46%|████▌     | 883/1939 [01:26<00:39, 26.75it/s]
 46%|████▌     | 888/1939 [01:27<00:35, 29.62it/s]
 46%|████▌     | 893/1939 [01:27<00:31, 33.63it/s]
 46%|████▋     | 899/1939 [01:27<00:26, 39.92it/s]
 47%|████▋     | 906/1939 [01:27<00:21, 47.24it/s]
 47%|████▋     | 912/1939 [01:28<00:48, 20.97it/s]
 47%|████▋     | 916/1939 [01:28<00:57, 17.82it/s]
 47%|████▋     | 920/1939 [01:28<01:01, 16.67it/s]
 48%|████▊     | 923/1939 [01:28<00:55, 18.26it/s]
 48%|████▊     | 927/1939 [01:29<01:09, 14.49it/s]
 48%|████▊     | 931/1939 [01:29<01:21, 12.32it/s]
 48%|████▊     | 933/1939 [01:29<01:27, 11.53it/s]
 48%|████▊     | 935/1939 [01:29<01:21, 12.30it/s]
 49%|████▊     | 942/1939 [01:30<00:48, 20.48it/s]
 49%|████▊     | 945/1939 [01:30<00:45, 21.73it/s]
 49%|████▉     | 952/1939 [01:30<00:32, 30.44it/s]
 49%|████▉     | 958/1939 [01:30<00:26, 36.50it/s]
 50%|████▉     | 963/1939 [01:30<00:36, 26.68it/s]
 50%|████▉     | 968/1939 [01:31<00:49, 19.65it/s]
 50%|█████     | 971/1939 [01:31<01:09, 13.94it/s]
 50%|█████     | 974/1939 [01:32<01:49,  8.82it/s]
 50%|█████     | 977/1939 [01:32<01:36,  9.94it/s]
 51%|█████     | 980/1939 [01:32<01:31, 10.44it/s]
 51%|█████     | 982/1939 [01:33<01:42,  9.36it/s]
 51%|█████     | 985/1939 [01:33<01:25, 11.19it/s]
 51%|█████     | 987/1939 [01:33<01:31, 10.40it/s]
 51%|█████     | 989/1939 [01:33<01:27, 10.83it/s]
 51%|█████     | 991/1939 [01:34<02:03,  7.69it/s]
 51%|█████     | 993/1939 [01:34<02:01,  7.77it/s]
 51%|█████▏    | 996/1939 [01:34<01:29, 10.50it/s]
 51%|█████▏    | 998/1939 [01:34<01:57,  8.00it/s]
 52%|█████▏    | 1000/1939 [01:35<02:03,  7.61it/s]
 52%|█████▏    | 1002/1939 [01:35<01:50,  8.51it/s]
 52%|█████▏    | 1004/1939 [01:35<01:33,  9.97it/s]
 52%|█████▏    | 1006/1939 [01:36<02:37,  5.93it/s]
 52%|█████▏    | 1009/1939 [01:36<02:01,  7.67it/s]
 52%|█████▏    | 1011/1939 [01:36<02:28,  6.25it/s]
 52%|█████▏    | 1012/1939 [01:37<02:29,  6.20it/s]
 52%|█████▏    | 1013/1939 [01:37<02:42,  5.70it/s]
 52%|█████▏    | 1014/1939 [01:37<03:12,  4.80it/s]
 52%|█████▏    | 1015/1939 [01:37<03:36,  4.27it/s]
 52%|█████▏    | 1016/1939 [01:38<03:59,  3.85it/s]
 53%|█████▎    | 1018/1939 [01:38<03:53,  3.95it/s]
 53%|█████▎    | 1019/1939 [01:39<04:13,  3.63it/s]
 53%|█████▎    | 1021/1939 [01:39<03:18,  4.62it/s]
 53%|█████▎    | 1022/1939 [01:39<03:49,  3.99it/s]
 53%|█████▎    | 1025/1939 [01:39<02:15,  6.73it/s]
 53%|█████▎    | 1027/1939 [01:40<02:29,  6.09it/s]
 53%|█████▎    | 1029/1939 [01:40<01:58,  7.66it/s]
 53%|█████▎    | 1031/1939 [01:40<01:56,  7.81it/s]
 53%|█████▎    | 1033/1939 [01:40<01:54,  7.88it/s]
 53%|█████▎    | 1036/1939 [01:40<01:23, 10.86it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 325.86it/s]
 84%|████████▎ | 251/300 [12:19<47:08, 57.73s/it]

[[np.int64(0), False, 2], [np.int64(1), False, 9], [np.int64(3), False, 13], [np.int64(4), False, 5], [np.int64(6), False, 13], [np.int64(7), False, 13], [np.int64(8), False, 12], [np.int64(10), False, 5], [np.int64(11), False, 13]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6195, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.1846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5051, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [12:19<32:24, 40.50s/it]

tensor(12.2262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0487, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8379, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [12:19<15:16, 19.93s/it]

tensor(12.2480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0553, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6292, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0611, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6546, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0712, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5592, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [12:20<07:54, 10.78s/it]

tensor(12.4039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0820, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2560, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [12:20<04:34,  6.54s/it]

tensor(12.4660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0915, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0870, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0981, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1420, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1016, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5498, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [12:20<02:48,  4.21s/it]

tensor(12.6863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1033, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8823, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1035, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5590, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [12:20<01:46,  2.81s/it]

tensor(12.8112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1024, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6948, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [12:20<01:04,  1.80s/it]

tensor(12.8275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1010, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0985, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0955, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6612, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [12:21<00:38,  1.15s/it]

tensor(12.8669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0916, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6281, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [12:21<00:24,  1.29it/s]

tensor(12.8320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0872, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6591, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0824, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0773, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8030, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [12:21<00:16,  1.83it/s]

tensor(12.7036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0723, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8382, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0672, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8904, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [12:21<00:11,  2.49it/s]

tensor(12.6565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0618, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9276, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [12:21<00:07,  3.26it/s]

tensor(12.6672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0562, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9773, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0503, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0019, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6468, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0145, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [12:22<00:05,  4.14it/s]

tensor(12.6131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0391, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0226, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0180, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [12:22<00:04,  5.06it/s]

tensor(12.5586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9906, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [12:22<00:03,  5.96it/s]

tensor(12.5314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9706, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9878, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [12:22<00:02,  6.76it/s]

tensor(12.4986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0024, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [12:22<00:02,  7.17it/s]

tensor(12.4774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0306, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [12:22<00:02,  7.59it/s]

tensor(12.4558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4412, device='cuda:0', grad_fn=<AddBackward0>)

 95%|█████████▌| 285/300 [12:23<00:01,  8.02it/s]

tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0906, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [12:23<00:01,  8.41it/s]

tensor(12.4281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1389, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [12:23<00:01,  8.73it/s]

tensor(12.4151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1743, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [12:23<00:01,  9.00it/s]

tensor(12.4060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2057, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [12:23<00:01,  9.16it/s]

tensor(12.3962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2265, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [12:23<00:01,  9.35it/s]

tensor(12.3834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2425, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [12:23<00:00,  9.48it/s]

tensor(12.3739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2659, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [12:23<00:00,  9.55it/s]

tensor(12.3660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2826, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [12:23<00:00,  9.35it/s]

tensor(12.3551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3119, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [12:24<00:00,  9.70it/s]

tensor(12.3306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3310, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3147, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3516, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3764, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [12:24<00:00,  9.86it/s]

tensor(12.2893, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4071, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [12:24<00:00,  2.48s/it]

tensor(12.2714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4205, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.004293680191040039
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 0
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.440489005428
NMI         : 0.601843093665
Runtime     : 764.02 sec
Evidence    : /kaggle/working/PRAGA_baseline/smoke_final/S2E15_seed0

==============================================================================================================
PRAGA RUN | S2-E18 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 9.956e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(16.0495, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0707, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8073, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:35,  8.44it/s]

tensor(16.0279, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9799, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8367, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:33,  8.83it/s]

tensor(15.9254, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1400, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8785, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6101, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:32,  9.08it/s]

tensor(15.8342, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2302, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7968, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9877, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:31,  9.15it/s]

tensor(15.7652, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8678, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7350, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8566, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:31,  9.16it/s]

tensor(15.7065, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9464, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6767, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1270, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:31,  9.10it/s]

tensor(15.6463, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3869, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6128, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7210, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:31,  9.09it/s]

tensor(15.5761, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5377, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5800, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:02<00:31,  8.99it/s]

tensor(15.4975, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0932, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4567, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6543, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:31,  8.90it/s]

tensor(15.4167, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2600, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3763, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9042, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:02<00:30,  8.99it/s]

tensor(15.3386, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5840, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3011, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2954, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:30,  9.04it/s]

tensor(15.2617, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0369, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2222, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8031, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:30,  8.91it/s]

tensor(15.1794, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5939, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1340, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4053, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:03<00:30,  9.04it/s]

tensor(15.0850, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2367, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0343, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0840, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:29,  9.14it/s]

tensor(14.9829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9481, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8253, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:30,  8.93it/s]

tensor(14.8799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7164, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6184, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:30,  8.80it/s]

tensor(14.7772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4529, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:04<00:29,  8.84it/s]

tensor(14.6727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3829, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6184, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3215, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:04<00:29,  8.84it/s]

tensor(14.5625, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2670, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2190, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:04<00:29,  8.89it/s]

tensor(14.4476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1774, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1416, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:28,  8.97it/s]

tensor(14.3300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1105, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0858, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:28,  8.83it/s]

tensor(14.2086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0662, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:05<00:28,  8.83it/s]

tensor(14.0825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:05<00:28,  8.90it/s]

tensor(13.9587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9009, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:28,  8.88it/s]

tensor(13.8475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:27,  8.88it/s]

tensor(13.7546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:06<00:27,  8.86it/s]

tensor(13.6804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:06<00:27,  8.80it/s]

tensor(13.6123, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:06<00:27,  8.92it/s]

tensor(13.5406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:06<00:26,  8.92it/s]

tensor(13.4691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:26,  8.93it/s]

tensor(13.4048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:07<00:26,  8.90it/s]

tensor(13.3478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:07<00:25,  9.00it/s]

tensor(13.2937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:07<00:25,  8.94it/s]

tensor(13.2401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:26,  8.71it/s]

tensor(13.1858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:08<00:26,  8.76it/s]

tensor(13.1314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:08<00:25,  8.73it/s]

tensor(13.0782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:08<00:25,  8.82it/s]

tensor(13.0268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:08<00:25,  8.75it/s]

tensor(12.9788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9560, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:09<00:25,  8.73it/s]

tensor(12.9339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9123, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:09<00:25,  8.68it/s]

tensor(12.8913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:09<00:25,  8.64it/s]

tensor(12.8514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:09<00:24,  8.70it/s]

tensor(12.8146, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:09<00:24,  8.77it/s]

tensor(12.7801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:10<00:24,  8.72it/s]

tensor(12.7484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:10<00:23,  8.73it/s]

tensor(12.7182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:10<00:23,  8.81it/s]

tensor(12.6897, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:10<00:23,  8.74it/s]

tensor(12.6628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:11<00:23,  8.65it/s]

tensor(12.6376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6258, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:11<00:23,  8.58it/s]

tensor(12.6142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([183, 163,  98, 130, 155, 117, 238, 390,  63,  90, 228,  87,  90, 216])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 4/2248 [00:00<01:27, 25.70it/s]
  0%|          | 7/2248 [00:00<01:38, 22.74it/s]
  1%|          | 13/2248 [00:00<01:05, 34.29it/s]
  1%|          | 17/2248 [00:00<01:04, 34.66it/s]
  1%|          | 24/2248 [00:00<00:50, 43.73it/s]
  1%|▏         | 30/2248 [00:00<00:46, 48.03it/s]
  2%|▏         | 36/2248 [00:00<00:46, 47.31it/s]
  2%|▏         | 42/2248 [00:01<00:47, 46.71it/s]
  2%|▏         | 47/2248 [00:01<00:52, 41.55it/s]
  2%|▏         | 52/2248 [00:01<00:54, 40.57it/s]
  3%|▎         | 57/2248 [00:01<00:57, 38.43it/s]
  3%|▎         | 63/2248 [00:01<00:50, 42.95it/s]
  3%|▎         | 71/2248 [00:01<00:42, 51.47it/s]
  3%|▎         | 77/2248 [00:02<01:11, 30.55it/s]
  4%|▎         | 82/2248 [00:02<01:15, 28.87it/s]
  4%|▍         | 86/2248 [00:02<02:09, 16.71it/s]
  4%|▍         | 89/2248 [00:02<02:04, 17.36it/s]
  4%|▍         | 96/2248 [00:03<01:28, 24.28it/s]
  4%|▍         | 100/2248 [00:03<02:33, 14.00it/s]
  5%|▍         | 106/2248 [00:03<01:54, 18.68it/s]
  5%|▍         | 110/2248 [00:03<01:41, 21.11it/s]
  5%|▌         | 116/2248 [00:04<01:19, 26.84it/s]
  5%|▌         | 121/2248 [00:05<03:25, 10.33it/s]
  6%|▌         | 124/2248 [00:05<04:11,  8.45it/s]
  6%|▌         | 127/2248 [00:06<05:37,  6.28it/s]
  6%|▌         | 129/2248 [00:07<05:38,  6.25it/s]
  6%|▌         | 131/2248 [00:07<04:55,  7.16it/s]
  6%|▌         | 133/2248 [00:07<05:32,  6.35it/s]
  6%|▌         | 135/2248 [00:07<04:54,  7.18it/s]
  6%|▌         | 137/2248 [00:08<04:46,  7.38it/s]
  6%|▌         | 139/2248 [00:08<04:47,  7.34it/s]
  6%|▋         | 141/2248 [00:08<03:58,  8.83it/s]
  6%|▋         | 145/2248 [00:08<03:44,  9.35it/s]
  7%|▋         | 147/2248 [00:08<03:16, 10.69it/s]
  7%|▋         | 151/2248 [00:09<03:58,  8.79it/s]
  7%|▋         | 154/2248 [00:09<03:14, 10.78it/s]
  7%|▋         | 156/2248 [00:10<04:25,  7.87it/s]
  7%|▋         | 158/2248 [00:11<07:32,  4.62it/s]
  7%|▋         | 159/2248 [00:11<09:03,  3.84it/s]
  7%|▋         | 160/2248 [00:12<10:27,  3.33it/s]
  7%|▋         | 162/2248 [00:12<10:17,  3.38it/s]
  7%|▋         | 165/2248 [00:13<08:41,  4.00it/s]
  7%|▋         | 168/2248 [00:13<05:54,  5.86it/s]
  8%|▊         | 173/2248 [00:13<04:53,  7.06it/s]
  8%|▊         | 176/2248 [00:14<05:24,  6.38it/s]
  8%|▊         | 178/2248 [00:15<06:14,  5.53it/s]
  8%|▊         | 181/2248 [00:15<04:38,  7.41it/s]
  8%|▊         | 187/2248 [00:15<03:59,  8.61it/s]
  8%|▊         | 189/2248 [00:15<03:40,  9.36it/s]
  9%|▊         | 195/2248 [00:16<03:40,  9.29it/s]
  9%|▉         | 197/2248 [00:16<03:24, 10.04it/s]
  9%|▉         | 202/2248 [00:17<03:33,  9.57it/s]
  9%|▉         | 204/2248 [00:17<03:19, 10.24it/s]
  9%|▉         | 206/2248 [00:17<04:23,  7.76it/s]
  9%|▉         | 208/2248 [00:18<05:26,  6.25it/s]
  9%|▉         | 209/2248 [00:18<07:05,  4.79it/s]
  9%|▉         | 210/2248 [00:19<08:46,  3.87it/s]
  9%|▉         | 211/2248 [00:19<10:28,  3.24it/s]
  9%|▉         | 212/2248 [00:20<11:37,  2.92it/s]
 10%|▉         | 214/2248 [00:20<07:55,  4.27it/s]
 10%|▉         | 221/2248 [00:20<03:02, 11.10it/s]
 10%|█         | 228/2248 [00:20<01:49, 18.41it/s]
 10%|█         | 233/2248 [00:20<01:27, 23.09it/s]
 11%|█         | 240/2248 [00:20<01:04, 31.14it/s]
 11%|█         | 248/2248 [00:21<00:49, 40.15it/s]
 11%|█▏        | 255/2248 [00:21<00:43, 46.04it/s]
 12%|█▏        | 262/2248 [00:21<00:38, 51.03it/s]
 12%|█▏        | 269/2248 [00:21<00:36, 53.73it/s]
 12%|█▏        | 276/2248 [00:22<01:37, 20.23it/s]
 12%|█▎        | 281/2248 [00:22<01:31, 21.40it/s]
 13%|█▎        | 287/2248 [00:22<01:15, 25.92it/s]
 13%|█▎        | 292/2248 [00:23<02:40, 12.21it/s]
 13%|█▎        | 296/2248 [00:24<03:12, 10.16it/s]
 13%|█▎        | 299/2248 [00:24<03:32,  9.19it/s]
 13%|█▎        | 301/2248 [00:24<03:14, 10.00it/s]
 13%|█▎        | 303/2248 [00:25<04:05,  7.92it/s]
 14%|█▎        | 305/2248 [00:25<04:57,  6.54it/s]
 14%|█▎        | 307/2248 [00:26<05:42,  5.66it/s]
 14%|█▎        | 308/2248 [00:26<07:00,  4.62it/s]
 14%|█▎        | 309/2248 [00:26<07:16,  4.44it/s]
 14%|█▍        | 311/2248 [00:27<05:35,  5.78it/s]
 14%|█▍        | 313/2248 [00:27<06:22,  5.06it/s]
 14%|█▍        | 314/2248 [00:27<06:39,  4.84it/s]
 14%|█▍        | 315/2248 [00:28<06:34,  4.90it/s]
 14%|█▍        | 317/2248 [00:28<04:43,  6.81it/s]
 14%|█▍        | 319/2248 [00:28<06:06,  5.27it/s]
 14%|█▍        | 320/2248 [00:29<08:17,  3.87it/s]
 14%|█▍        | 322/2248 [00:29<08:52,  3.62it/s]
 14%|█▍        | 323/2248 [00:30<10:15,  3.13it/s]
 14%|█▍        | 325/2248 [00:30<07:08,  4.48it/s]
 15%|█▍        | 327/2248 [00:30<07:46,  4.12it/s]
 15%|█▍        | 330/2248 [00:31<04:58,  6.42it/s]
 15%|█▍        | 337/2248 [00:31<02:19, 13.70it/s]
 15%|█▌        | 340/2248 [00:31<03:10, 10.03it/s]
 15%|█▌        | 343/2248 [00:32<03:52,  8.19it/s]
 15%|█▌        | 345/2248 [00:32<03:25,  9.25it/s]
 15%|█▌        | 347/2248 [00:32<04:29,  7.06it/s]
 16%|█▌        | 349/2248 [00:33<07:15,  4.36it/s]
 16%|█▌        | 351/2248 [00:34<07:37,  4.14it/s]
 16%|█▌        | 353/2248 [00:34<07:53,  4.00it/s]
 16%|█▌        | 356/2248 [00:35<07:16,  4.33it/s]
 16%|█▌        | 359/2248 [00:35<05:14,  6.00it/s]
 16%|█▌        | 362/2248 [00:36<05:16,  5.96it/s]
 16%|█▌        | 364/2248 [00:36<06:01,  5.21it/s]
 16%|█▋        | 366/2248 [00:36<04:53,  6.42it/s]
 17%|█▋        | 371/2248 [00:37<03:29,  8.96it/s]
 17%|█▋        | 375/2248 [00:37<02:36, 12.01it/s]
 17%|█▋        | 379/2248 [00:37<02:46, 11.24it/s]
 17%|█▋        | 382/2248 [00:37<02:22, 13.06it/s]
 17%|█▋        | 385/2248 [00:38<03:12,  9.66it/s]
 17%|█▋        | 388/2248 [00:38<04:00,  7.74it/s]
 17%|█▋        | 391/2248 [00:39<03:13,  9.61it/s]
 17%|█▋        | 393/2248 [00:40<05:50,  5.29it/s]
 18%|█▊        | 395/2248 [00:41<08:00,  3.85it/s]
 18%|█▊        | 398/2248 [00:41<05:44,  5.38it/s]
 18%|█▊        | 405/2248 [00:41<02:58, 10.35it/s]
 18%|█▊        | 409/2248 [00:41<02:20, 13.11it/s]
 18%|█▊        | 412/2248 [00:41<02:06, 14.52it/s]
 19%|█▊        | 419/2248 [00:41<01:21, 22.34it/s]
 19%|█▉        | 426/2248 [00:41<01:00, 30.22it/s]
 19%|█▉        | 433/2248 [00:41<00:48, 37.14it/s]
 20%|█▉        | 439/2248 [00:42<02:16, 13.30it/s]
 20%|█▉        | 444/2248 [00:43<02:32, 11.86it/s]
 20%|█▉        | 447/2248 [00:44<03:11,  9.43it/s]
 20%|██        | 450/2248 [00:44<03:47,  7.89it/s]
 20%|██        | 452/2248 [00:44<03:27,  8.67it/s]
 20%|██        | 455/2248 [00:45<03:52,  7.71it/s]
 20%|██        | 457/2248 [00:45<04:39,  6.40it/s]
 20%|██        | 460/2248 [00:46<04:44,  6.30it/s]
 21%|██        | 462/2248 [00:46<04:07,  7.22it/s]
 21%|██        | 464/2248 [00:46<03:31,  8.45it/s]
 21%|██        | 468/2248 [00:46<02:24, 12.28it/s]
 21%|██        | 472/2248 [00:46<02:02, 14.50it/s]
 21%|██        | 475/2248 [00:47<02:18, 12.76it/s]
 21%|██        | 477/2248 [00:47<02:09, 13.70it/s]
 21%|██▏       | 480/2248 [00:47<02:22, 12.41it/s]
 21%|██▏       | 482/2248 [00:48<03:39,  8.04it/s]
 22%|██▏       | 484/2248 [00:48<03:11,  9.21it/s]
 22%|██▏       | 486/2248 [00:48<03:09,  9.28it/s]
 22%|██▏       | 488/2248 [00:49<05:05,  5.76it/s]
 22%|██▏       | 491/2248 [00:49<03:48,  7.69it/s]
 22%|██▏       | 493/2248 [00:49<04:12,  6.94it/s]
 22%|██▏       | 495/2248 [00:49<03:56,  7.40it/s]
 22%|██▏       | 498/2248 [00:50<03:03,  9.54it/s]
 22%|██▏       | 500/2248 [00:50<03:21,  8.68it/s]
 22%|██▏       | 502/2248 [00:50<02:59,  9.72it/s]
 22%|██▏       | 505/2248 [00:50<02:16, 12.75it/s]
 23%|██▎       | 509/2248 [00:51<02:28, 11.70it/s]
 23%|██▎       | 513/2248 [00:51<01:50, 15.73it/s]
 23%|██▎       | 516/2248 [00:51<03:33,  8.12it/s]
 23%|██▎       | 518/2248 [00:52<04:38,  6.22it/s]
 23%|██▎       | 520/2248 [00:52<04:56,  5.82it/s]
 23%|██▎       | 525/2248 [00:53<02:57,  9.70it/s]
 24%|██▎       | 531/2248 [00:53<01:53, 15.09it/s]
 24%|██▍       | 535/2248 [00:53<01:41, 16.89it/s]
 24%|██▍       | 540/2248 [00:53<01:18, 21.76it/s]
 24%|██▍       | 547/2248 [00:53<00:57, 29.73it/s]
 25%|██▍       | 552/2248 [00:53<00:53, 31.80it/s]
 25%|██▍       | 557/2248 [00:53<00:48, 35.02it/s]
 25%|██▌       | 562/2248 [00:53<00:48, 34.49it/s]
 25%|██▌       | 570/2248 [00:54<00:37, 44.64it/s]
 26%|██▌       | 576/2248 [00:55<02:30, 11.13it/s]
 26%|██▌       | 580/2248 [00:56<02:51,  9.71it/s]
 26%|██▌       | 583/2248 [00:56<03:26,  8.06it/s]
 26%|██▌       | 586/2248 [00:57<03:12,  8.63it/s]
 26%|██▌       | 588/2248 [00:57<03:29,  7.93it/s]
 26%|██▋       | 591/2248 [00:57<02:52,  9.63it/s]
 26%|██▋       | 593/2248 [00:57<03:12,  8.62it/s]
 27%|██▋       | 598/2248 [00:57<02:05, 13.16it/s]
 27%|██▋       | 601/2248 [00:58<02:21, 11.62it/s]
 27%|██▋       | 603/2248 [00:58<02:24, 11.36it/s]
 27%|██▋       | 605/2248 [00:58<03:26,  7.95it/s]
 27%|██▋       | 607/2248 [00:59<04:22,  6.24it/s]
 27%|██▋       | 609/2248 [01:00<06:42,  4.08it/s]
 27%|██▋       | 610/2248 [01:00<07:38,  3.57it/s]
 27%|██▋       | 612/2248 [01:01<05:42,  4.77it/s]
 28%|██▊       | 619/2248 [01:01<02:30, 10.80it/s]
 28%|██▊       | 626/2248 [01:01<01:32, 17.54it/s]
 28%|██▊       | 632/2248 [01:01<01:09, 23.34it/s]
 28%|██▊       | 638/2248 [01:01<00:55, 29.24it/s]
 29%|██▊       | 645/2248 [01:01<00:44, 36.17it/s]
 29%|██▉       | 651/2248 [01:02<01:15, 21.27it/s]
 29%|██▉       | 655/2248 [01:02<01:58, 13.40it/s]
 29%|██▉       | 658/2248 [01:03<02:35, 10.24it/s]
 29%|██▉       | 661/2248 [01:04<04:00,  6.59it/s]
 29%|██▉       | 663/2248 [01:05<04:34,  5.77it/s]
 30%|██▉       | 665/2248 [01:05<05:01,  5.25it/s]
 30%|██▉       | 668/2248 [01:05<03:51,  6.82it/s]
 30%|██▉       | 670/2248 [01:06<04:35,  5.73it/s]
 30%|██▉       | 673/2248 [01:06<03:27,  7.58it/s]
 30%|███       | 677/2248 [01:06<03:02,  8.59it/s]
 30%|███       | 679/2248 [01:06<02:42,  9.66it/s]
 30%|███       | 681/2248 [01:06<02:22, 10.96it/s]
 30%|███       | 683/2248 [01:07<02:50,  9.17it/s]
 30%|███       | 685/2248 [01:07<02:27, 10.60it/s]
 31%|███       | 688/2248 [01:07<02:47,  9.29it/s]
 31%|███       | 690/2248 [01:07<02:32, 10.21it/s]
 31%|███       | 692/2248 [01:08<02:34, 10.09it/s]
 31%|███       | 694/2248 [01:08<02:19, 11.17it/s]
 31%|███       | 696/2248 [01:08<02:03, 12.61it/s]
 31%|███       | 698/2248 [01:08<03:25,  7.55it/s]
 31%|███       | 700/2248 [01:09<04:29,  5.74it/s]
 31%|███       | 702/2248 [01:09<05:17,  4.87it/s]
 31%|███▏      | 704/2248 [01:10<05:45,  4.47it/s]
 31%|███▏      | 706/2248 [01:10<04:28,  5.75it/s]
 32%|███▏      | 712/2248 [01:11<03:20,  7.68it/s]
 32%|███▏      | 715/2248 [01:11<02:40,  9.55it/s]
 32%|███▏      | 723/2248 [01:11<01:27, 17.51it/s]
 32%|███▏      | 730/2248 [01:11<01:02, 24.22it/s]
 33%|███▎      | 735/2248 [01:12<01:32, 16.28it/s]
 33%|███▎      | 739/2248 [01:13<02:49,  8.89it/s]
 33%|███▎      | 742/2248 [01:13<02:37,  9.55it/s]
 33%|███▎      | 744/2248 [01:14<04:00,  6.24it/s]
 33%|███▎      | 746/2248 [01:14<03:34,  7.00it/s]
 33%|███▎      | 749/2248 [01:14<03:04,  8.11it/s]
 33%|███▎      | 751/2248 [01:14<02:44,  9.10it/s]
 33%|███▎      | 753/2248 [01:14<02:48,  8.90it/s]
 34%|███▎      | 755/2248 [01:15<02:27, 10.15it/s]
 34%|███▍      | 762/2248 [01:15<01:19, 18.72it/s]
 34%|███▍      | 765/2248 [01:15<02:12, 11.18it/s]
 34%|███▍      | 768/2248 [01:16<02:52,  8.59it/s]
 34%|███▍      | 770/2248 [01:16<02:33,  9.65it/s]
 34%|███▍      | 772/2248 [01:16<02:58,  8.25it/s]
 34%|███▍      | 774/2248 [01:17<04:12,  5.84it/s]
 35%|███▍      | 776/2248 [01:18<05:07,  4.79it/s]
 35%|███▍      | 778/2248 [01:18<04:31,  5.41it/s]
 35%|███▍      | 780/2248 [01:18<03:37,  6.75it/s]
 35%|███▍      | 782/2248 [01:19<04:27,  5.48it/s]
 35%|███▍      | 783/2248 [01:19<05:36,  4.36it/s]
 35%|███▍      | 784/2248 [01:19<06:46,  3.60it/s]
 35%|███▍      | 786/2248 [01:20<05:03,  4.81it/s]
 35%|███▌      | 789/2248 [01:20<04:38,  5.25it/s]
 35%|███▌      | 792/2248 [01:20<03:43,  6.53it/s]
 35%|███▌      | 794/2248 [01:21<03:15,  7.43it/s]
 35%|███▌      | 797/2248 [01:21<03:40,  6.58it/s]
 36%|███▌      | 799/2248 [01:21<03:08,  7.70it/s]
 36%|███▌      | 803/2248 [01:21<02:05, 11.53it/s]
 36%|███▌      | 806/2248 [01:22<02:17, 10.51it/s]
 36%|███▌      | 809/2248 [01:22<01:52, 12.79it/s]
 36%|███▌      | 811/2248 [01:22<02:47,  8.59it/s]
 36%|███▌      | 813/2248 [01:23<05:00,  4.78it/s]
 36%|███▋      | 815/2248 [01:24<04:56,  4.83it/s]
 36%|███▋      | 816/2248 [01:24<06:02,  3.95it/s]
 36%|███▋      | 819/2248 [01:24<03:58,  6.00it/s]
 37%|███▋      | 824/2248 [01:24<02:16, 10.45it/s]
 37%|███▋      | 827/2248 [01:25<01:53, 12.48it/s]
 37%|███▋      | 833/2248 [01:25<01:13, 19.25it/s]
 37%|███▋      | 837/2248 [01:25<01:03, 22.12it/s]
 38%|███▊      | 844/2248 [01:25<00:45, 31.03it/s]
 38%|███▊      | 852/2248 [01:25<00:34, 41.01it/s]
 38%|███▊      | 860/2248 [01:25<00:27, 49.76it/s]
 39%|███▊      | 867/2248 [01:26<00:50, 27.17it/s]
 39%|███▉      | 872/2248 [01:26<00:49, 27.55it/s]
 39%|███▉      | 877/2248 [01:27<01:57, 11.67it/s]
 39%|███▉      | 881/2248 [01:28<02:16, 10.05it/s]
 39%|███▉      | 884/2248 [01:28<02:01, 11.22it/s]
 40%|███▉      | 890/2248 [01:28<01:26, 15.67it/s]
 40%|███▉      | 894/2248 [01:29<02:33,  8.84it/s]
 40%|███▉      | 897/2248 [01:29<02:53,  7.76it/s]
 40%|████      | 902/2248 [01:30<02:48,  8.00it/s]
 40%|████      | 904/2248 [01:30<03:16,  6.84it/s]
 40%|████      | 906/2248 [01:31<03:47,  5.89it/s]
 40%|████      | 907/2248 [01:32<04:44,  4.72it/s]
 40%|████      | 908/2248 [01:32<04:53,  4.56it/s]
 40%|████      | 909/2248 [01:32<04:28,  4.99it/s]
 40%|████      | 910/2248 [01:32<04:51,  4.59it/s]
 41%|████      | 911/2248 [01:32<04:33,  4.90it/s]
 41%|████      | 912/2248 [01:33<04:34,  4.87it/s]
 41%|████      | 913/2248 [01:33<05:41,  3.91it/s]
 41%|████      | 915/2248 [01:33<03:50,  5.79it/s]
 41%|████      | 917/2248 [01:33<03:51,  5.75it/s]
 41%|████      | 919/2248 [01:34<02:57,  7.51it/s]
 41%|████      | 921/2248 [01:34<03:11,  6.92it/s]
 41%|████      | 923/2248 [01:34<02:37,  8.44it/s]
 41%|████      | 925/2248 [01:34<02:34,  8.57it/s]
 41%|████      | 927/2248 [01:35<03:03,  7.18it/s]
 41%|████▏     | 929/2248 [01:35<03:00,  7.32it/s]
 41%|████▏     | 931/2248 [01:35<02:29,  8.80it/s]
 42%|████▏     | 934/2248 [01:35<02:29,  8.81it/s]
 42%|████▏     | 936/2248 [01:35<02:06, 10.35it/s]
 42%|████▏     | 939/2248 [01:36<01:36, 13.59it/s]
 42%|████▏     | 945/2248 [01:36<00:58, 22.18it/s]
 42%|████▏     | 948/2248 [01:36<00:57, 22.42it/s]
 42%|████▏     | 952/2248 [01:36<01:11, 18.16it/s]
 42%|████▏     | 955/2248 [01:36<01:07, 19.07it/s]
 43%|████▎     | 958/2248 [01:37<02:42,  7.95it/s]
 43%|████▎     | 960/2248 [01:37<02:37,  8.17it/s]
 43%|████▎     | 962/2248 [01:38<03:37,  5.92it/s]
 43%|████▎     | 964/2248 [01:38<03:36,  5.94it/s]
 43%|████▎     | 966/2248 [01:39<03:47,  5.63it/s]
 43%|████▎     | 968/2248 [01:39<03:08,  6.80it/s]
 43%|████▎     | 970/2248 [01:40<04:07,  5.17it/s]
 43%|████▎     | 973/2248 [01:40<02:51,  7.46it/s]
 43%|████▎     | 975/2248 [01:40<03:34,  5.95it/s]
 43%|████▎     | 977/2248 [01:41<04:07,  5.13it/s]
 44%|████▎     | 978/2248 [01:41<05:10,  4.09it/s]
 44%|████▎     | 980/2248 [01:41<03:57,  5.34it/s]
 44%|████▎     | 981/2248 [01:42<05:08,  4.11it/s]
 44%|████▎     | 983/2248 [01:42<03:44,  5.63it/s]
 44%|████▍     | 985/2248 [01:42<04:25,  4.75it/s]
 44%|████▍     | 987/2248 [01:43<04:50,  4.34it/s]
 44%|████▍     | 989/2248 [01:43<03:39,  5.73it/s]
 44%|████▍     | 995/2248 [01:43<01:45, 11.91it/s]
 44%|████▍     | 999/2248 [01:44<02:09,  9.68it/s]
 45%|████▍     | 1002/2248 [01:44<02:34,  8.05it/s]
 45%|████▍     | 1004/2248 [01:45<03:46,  5.50it/s]
 45%|████▍     | 1006/2248 [01:45<03:23,  6.10it/s]
 45%|████▍     | 1008/2248 [01:46<04:19,  4.78it/s]
 45%|████▍     | 1009/2248 [01:46<04:57,  4.17it/s]
 45%|████▌     | 1012/2248 [01:47<03:26,  5.99it/s]
 45%|████▌     | 1014/2248 [01:47<02:47,  7.38it/s]
 45%|████▌     | 1021/2248 [01:47<01:22, 14.95it/s]
 46%|████▌     | 1024/2248 [01:47<01:15, 16.30it/s]
 46%|████▌     | 1027/2248 [01:47<01:08, 17.76it/s]
 46%|████▌     | 1032/2248 [01:47<00:52, 23.17it/s]
 46%|████▌     | 1039/2248 [01:47<00:37, 32.07it/s]
 46%|████▋     | 1044/2248 [01:47<00:33, 35.58it/s]
 47%|████▋     | 1050/2248 [01:48<00:29, 40.01it/s]
 47%|████▋     | 1055/2248 [01:48<00:57, 20.67it/s]
 47%|████▋     | 1059/2248 [01:49<01:19, 14.97it/s]
 47%|████▋     | 1062/2248 [01:49<01:56, 10.19it/s]
 47%|████▋     | 1065/2248 [01:49<01:43, 11.42it/s]
 47%|████▋     | 1067/2248 [01:50<01:54, 10.30it/s]
 48%|████▊     | 1069/2248 [01:50<01:43, 11.39it/s]
 48%|████▊     | 1071/2248 [01:50<01:42, 11.47it/s]
 48%|████▊     | 1073/2248 [01:50<01:34, 12.40it/s]
 48%|████▊     | 1076/2248 [01:50<01:37, 11.99it/s]
 48%|████▊     | 1078/2248 [01:50<01:31, 12.73it/s]
 48%|████▊     | 1082/2248 [01:51<01:06, 17.48it/s]
 48%|████▊     | 1085/2248 [01:51<01:20, 14.46it/s]
 48%|████▊     | 1087/2248 [01:51<01:33, 12.38it/s]
 48%|████▊     | 1089/2248 [01:51<02:05,  9.23it/s]
 49%|████▊     | 1091/2248 [01:52<02:24,  7.99it/s]
 49%|████▊     | 1093/2248 [01:52<02:42,  7.09it/s]
 49%|████▊     | 1094/2248 [01:52<02:56,  6.55it/s]
 49%|████▉     | 1097/2248 [01:53<02:07,  9.00it/s]
 49%|████▉     | 1102/2248 [01:53<01:17, 14.83it/s]
 49%|████▉     | 1107/2248 [01:53<00:57, 19.73it/s]
 49%|████▉     | 1112/2248 [01:53<00:45, 24.98it/s]
 50%|████▉     | 1118/2248 [01:53<00:34, 32.32it/s]
 50%|█████     | 1125/2248 [01:53<00:27, 40.16it/s]
 50%|█████     | 1132/2248 [01:53<00:24, 45.88it/s]
 51%|█████     | 1139/2248 [01:53<00:21, 51.48it/s]
 51%|█████     | 1145/2248 [01:54<00:39, 28.11it/s]
 51%|█████     | 1150/2248 [01:54<01:03, 17.20it/s]
 51%|█████▏    | 1154/2248 [01:55<01:19, 13.79it/s]
 51%|█████▏    | 1157/2248 [01:56<01:54,  9.55it/s]
 52%|█████▏    | 1159/2248 [01:56<01:47, 10.12it/s]
 52%|█████▏    | 1161/2248 [01:56<02:19,  7.78it/s]
 52%|█████▏    | 1163/2248 [01:56<02:03,  8.77it/s]
 52%|█████▏    | 1165/2248 [01:57<02:25,  7.44it/s]
 52%|█████▏    | 1168/2248 [01:57<01:56,  9.25it/s]
 52%|█████▏    | 1170/2248 [01:57<02:38,  6.80it/s]
 52%|█████▏    | 1172/2248 [01:58<03:04,  5.83it/s]
 52%|█████▏    | 1175/2248 [01:58<02:36,  6.86it/s]
 52%|█████▏    | 1177/2248 [01:58<02:10,  8.21it/s]
 52%|█████▏    | 1179/2248 [01:59<02:50,  6.28it/s]
 53%|█████▎    | 1181/2248 [01:59<02:25,  7.31it/s]
 53%|█████▎    | 1183/2248 [01:59<02:18,  7.71it/s]
 53%|█████▎    | 1185/2248 [01:59<01:59,  8.87it/s]
 53%|█████▎    | 1187/2248 [02:00<02:00,  8.80it/s]
 53%|█████▎    | 1189/2248 [02:00<02:49,  6.24it/s]
 53%|█████▎    | 1190/2248 [02:00<02:40,  6.58it/s]
 53%|█████▎    | 1193/2248 [02:00<01:48,  9.72it/s]
 53%|█████▎    | 1195/2248 [02:01<01:59,  8.80it/s]
 53%|█████▎    | 1198/2248 [02:01<01:30, 11.56it/s]
 53%|█████▎    | 1201/2248 [02:01<01:59,  8.77it/s]
 54%|█████▎    | 1204/2248 [02:01<01:31, 11.37it/s]
 54%|█████▎    | 1206/2248 [02:02<01:54,  9.12it/s]
 54%|█████▍    | 1212/2248 [02:02<01:05, 15.70it/s]
 54%|█████▍    | 1216/2248 [02:02<00:53, 19.44it/s]
 54%|█████▍    | 1220/2248 [02:02<00:45, 22.77it/s]
 54%|█████▍    | 1225/2248 [02:02<00:36, 27.93it/s]
 55%|█████▍    | 1229/2248 [02:03<01:10, 14.40it/s]
 55%|█████▍    | 1232/2248 [02:04<02:57,  5.71it/s]
 55%|█████▍    | 1234/2248 [02:05<03:13,  5.25it/s]
 55%|█████▌    | 1238/2248 [02:05<02:15,  7.46it/s]
 55%|█████▌    | 1241/2248 [02:05<01:51,  9.03it/s]
 55%|█████▌    | 1244/2248 [02:06<02:17,  7.32it/s]
 55%|█████▌    | 1246/2248 [02:06<02:50,  5.88it/s]
 56%|█████▌    | 1248/2248 [02:07<03:17,  5.05it/s]
 56%|█████▌    | 1250/2248 [02:07<02:43,  6.09it/s]
 56%|█████▌    | 1256/2248 [02:07<01:28, 11.23it/s]
 56%|█████▌    | 1262/2248 [02:07<00:58, 16.91it/s]
 56%|█████▋    | 1266/2248 [02:08<01:24, 11.56it/s]
 57%|█████▋    | 1271/2248 [02:08<01:34, 10.30it/s]
 57%|█████▋    | 1274/2248 [02:09<01:58,  8.22it/s]
 57%|█████▋    | 1276/2248 [02:09<01:46,  9.12it/s]
 57%|█████▋    | 1278/2248 [02:09<01:36, 10.07it/s]
 57%|█████▋    | 1280/2248 [02:10<02:19,  6.94it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 305.08it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 7], [np.int64(2), False, 1], [np.int64(3), False, 10], [np.int64(4), False, 11], [np.int64(5), False, 13], [np.int64(6), False, 7], [np.int64(8), False, 0], [np.int64(9), False, 0], [np.int64(10), False, 13], [np.int64(12), False, 7]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7474, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [03:44<3:32:35, 64.10s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [03:44<2:28:11, 44.91s/it]

tensor(12.5813, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7644, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8266, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:45<1:12:05, 22.07s/it]

tensor(12.5679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8908, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9676, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [03:45<35:10, 10.88s/it]

tensor(12.5742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0265, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0861, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [03:45<17:16,  5.40s/it]

tensor(12.5883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2155, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [03:45<08:34,  2.71s/it]

tensor(12.6016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2837, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6082, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3614, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [03:46<04:22,  1.40s/it]

tensor(12.6141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4713, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [03:46<02:19,  1.34it/s]

tensor(12.6179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5561, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:46<01:19,  2.31it/s]

tensor(12.6074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5922, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6179, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [03:46<00:50,  3.62it/s]

tensor(12.5845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6389, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6503, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [03:47<00:31,  5.64it/s]

tensor(12.5512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6924, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [03:47<00:28,  6.16it/s]

tensor(12.5173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7216, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7436, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [03:47<00:25,  6.90it/s]

tensor(12.4869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7732, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [03:47<00:23,  7.30it/s]

tensor(12.4601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7896, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8090, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [03:48<00:23,  7.43it/s]

tensor(12.4389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8382, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8613, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [03:48<00:22,  7.43it/s]

tensor(12.4217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8868, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9041, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [03:48<00:22,  7.56it/s]

tensor(12.4074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9260, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9476, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [03:48<00:21,  7.60it/s]

tensor(12.3935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9718, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9906, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [03:49<00:20,  7.84it/s]

tensor(12.3791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0125, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3719, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0208, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [03:49<00:20,  7.78it/s]

tensor(12.3648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0404, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0530, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [03:49<00:20,  7.71it/s]

tensor(12.3514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0716, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0883, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:49<00:20,  7.84it/s]

tensor(12.3401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1063, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1218, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:50<00:20,  7.50it/s]

tensor(12.3296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1356, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3237, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1428, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [03:50<00:20,  7.58it/s]

tensor(12.3173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1588, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1785, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:50<00:19,  7.69it/s]

tensor(12.3048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1996, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2169, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:51<00:19,  7.67it/s]

tensor(12.2934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2345, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([239, 360, 136, 239, 191, 136,  65,  85,  76, 121,  76, 253, 111, 160])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 5/2248 [00:00<00:45, 49.63it/s]
  0%|          | 10/2248 [00:00<00:50, 44.48it/s]
  1%|          | 16/2248 [00:00<00:48, 45.66it/s]
  1%|          | 21/2248 [00:00<00:52, 42.22it/s]
  1%|          | 26/2248 [00:00<01:04, 34.68it/s]
  1%|▏         | 30/2248 [00:00<01:07, 32.67it/s]
  2%|▏         | 36/2248 [00:00<00:57, 38.45it/s]
  2%|▏         | 41/2248 [00:01<00:54, 40.49it/s]
  2%|▏         | 46/2248 [00:01<00:51, 42.49it/s]
  2%|▏         | 52/2248 [00:01<00:47, 46.49it/s]
  3%|▎         | 58/2248 [00:01<00:45, 48.05it/s]
  3%|▎         | 63/2248 [00:01<00:51, 42.05it/s]
  3%|▎         | 69/2248 [00:01<00:48, 45.33it/s]
  3%|▎         | 74/2248 [00:01<01:13, 29.60it/s]
  3%|▎         | 78/2248 [00:02<01:38, 22.07it/s]
  4%|▎         | 83/2248 [00:02<01:24, 25.72it/s]
  4%|▍         | 88/2248 [00:02<01:14, 28.95it/s]
  4%|▍         | 94/2248 [00:02<01:03, 33.94it/s]
  4%|▍         | 99/2248 [00:03<01:36, 22.29it/s]
  5%|▍         | 103/2248 [00:03<01:55, 18.60it/s]
  5%|▍         | 107/2248 [00:03<01:39, 21.44it/s]
  5%|▍         | 110/2248 [00:03<01:35, 22.39it/s]
  5%|▌         | 113/2248 [00:03<02:04, 17.12it/s]
  5%|▌         | 116/2248 [00:04<02:04, 17.12it/s]
  5%|▌         | 119/2248 [00:04<02:30, 14.19it/s]
  5%|▌         | 121/2248 [00:04<03:19, 10.69it/s]
  6%|▌         | 125/2248 [00:04<02:47, 12.68it/s]
  6%|▌         | 127/2248 [00:05<03:25, 10.32it/s]
  6%|▌         | 129/2248 [00:05<03:50,  9.21it/s]
  6%|▌         | 131/2248 [00:05<03:24, 10.37it/s]
  6%|▌         | 133/2248 [00:05<03:32,  9.97it/s]
  6%|▌         | 136/2248 [00:06<03:28, 10.15it/s]
  6%|▌         | 138/2248 [00:06<03:43,  9.43it/s]
  6%|▌         | 140/2248 [00:06<03:21, 10.48it/s]
  6%|▋         | 145/2248 [00:06<02:33, 13.74it/s]
  7%|▋         | 148/2248 [00:06<02:14, 15.58it/s]
  7%|▋         | 150/2248 [00:07<02:48, 12.42it/s]
  7%|▋         | 152/2248 [00:07<03:51,  9.06it/s]
  7%|▋         | 155/2248 [00:07<03:03, 11.41it/s]
  7%|▋         | 157/2248 [00:08<03:37,  9.63it/s]
  7%|▋         | 159/2248 [00:08<04:23,  7.93it/s]
  7%|▋         | 161/2248 [00:08<04:19,  8.05it/s]
  7%|▋         | 162/2248 [00:08<04:38,  7.49it/s]
  7%|▋         | 165/2248 [00:09<03:35,  9.64it/s]
  8%|▊         | 169/2248 [00:09<02:34, 13.45it/s]
  8%|▊         | 171/2248 [00:09<02:23, 14.51it/s]
  8%|▊         | 173/2248 [00:09<02:58, 11.65it/s]
  8%|▊         | 175/2248 [00:09<02:45, 12.51it/s]
  8%|▊         | 177/2248 [00:09<03:04, 11.24it/s]
  8%|▊         | 179/2248 [00:10<03:32,  9.74it/s]
  8%|▊         | 183/2248 [00:10<02:22, 14.52it/s]
  8%|▊         | 186/2248 [00:10<02:03, 16.63it/s]
  8%|▊         | 189/2248 [00:10<02:41, 12.76it/s]
  9%|▊         | 192/2248 [00:10<02:20, 14.68it/s]
  9%|▊         | 195/2248 [00:11<02:32, 13.50it/s]
  9%|▉         | 197/2248 [00:11<02:27, 13.89it/s]
  9%|▉         | 202/2248 [00:11<02:14, 15.22it/s]
  9%|▉         | 204/2248 [00:11<02:14, 15.17it/s]
  9%|▉         | 206/2248 [00:12<02:43, 12.48it/s]
  9%|▉         | 208/2248 [00:12<02:57, 11.48it/s]
  9%|▉         | 210/2248 [00:12<03:53,  8.73it/s]
  9%|▉         | 212/2248 [00:13<04:38,  7.32it/s]
 10%|▉         | 214/2248 [00:13<04:01,  8.43it/s]
 10%|▉         | 219/2248 [00:13<02:24, 14.02it/s]
 10%|▉         | 224/2248 [00:13<01:43, 19.61it/s]
 10%|█         | 231/2248 [00:13<01:12, 27.77it/s]
 10%|█         | 236/2248 [00:13<01:03, 31.74it/s]
 11%|█         | 240/2248 [00:13<01:03, 31.86it/s]
 11%|█         | 247/2248 [00:13<00:49, 40.57it/s]
 11%|█         | 252/2248 [00:14<00:59, 33.48it/s]
 11%|█▏        | 258/2248 [00:14<00:52, 38.15it/s]
 12%|█▏        | 263/2248 [00:14<00:57, 34.80it/s]
 12%|█▏        | 267/2248 [00:14<01:21, 24.17it/s]
 12%|█▏        | 271/2248 [00:15<02:00, 16.36it/s]
 12%|█▏        | 274/2248 [00:15<02:20, 14.01it/s]
 12%|█▏        | 276/2248 [00:15<02:45, 11.93it/s]
 12%|█▏        | 278/2248 [00:16<03:06, 10.58it/s]
 12%|█▏        | 280/2248 [00:16<02:53, 11.35it/s]
 13%|█▎        | 282/2248 [00:16<03:18,  9.90it/s]
 13%|█▎        | 284/2248 [00:16<03:14, 10.11it/s]
 13%|█▎        | 286/2248 [00:16<03:04, 10.63it/s]
 13%|█▎        | 288/2248 [00:16<02:55, 11.19it/s]
 13%|█▎        | 290/2248 [00:17<02:53, 11.29it/s]
 13%|█▎        | 292/2248 [00:17<04:07,  7.90it/s]
 13%|█▎        | 295/2248 [00:17<03:50,  8.49it/s]
 13%|█▎        | 296/2248 [00:18<03:52,  8.40it/s]
 13%|█▎        | 298/2248 [00:18<03:48,  8.54it/s]
 13%|█▎        | 300/2248 [00:18<03:19,  9.77it/s]
 13%|█▎        | 302/2248 [00:18<03:28,  9.36it/s]
 14%|█▎        | 304/2248 [00:19<04:29,  7.20it/s]
 14%|█▎        | 306/2248 [00:19<03:46,  8.59it/s]
 14%|█▎        | 308/2248 [00:19<03:34,  9.04it/s]
 14%|█▍        | 310/2248 [00:19<03:27,  9.32it/s]
 14%|█▍        | 312/2248 [00:19<03:12, 10.06it/s]
 14%|█▍        | 314/2248 [00:19<03:29,  9.22it/s]
 14%|█▍        | 315/2248 [00:20<04:07,  7.80it/s]
 14%|█▍        | 317/2248 [00:20<03:23,  9.48it/s]
 14%|█▍        | 319/2248 [00:20<03:34,  9.00it/s]
 14%|█▍        | 321/2248 [00:20<03:45,  8.55it/s]
 14%|█▍        | 322/2248 [00:21<04:15,  7.54it/s]
 14%|█▍        | 323/2248 [00:21<04:58,  6.44it/s]
 14%|█▍        | 325/2248 [00:21<04:41,  6.84it/s]
 15%|█▍        | 327/2248 [00:21<04:28,  7.15it/s]
 15%|█▍        | 328/2248 [00:21<04:49,  6.64it/s]
 15%|█▍        | 329/2248 [00:22<05:32,  5.78it/s]
 15%|█▍        | 332/2248 [00:22<04:04,  7.82it/s]
 15%|█▍        | 334/2248 [00:22<03:28,  9.20it/s]
 15%|█▌        | 339/2248 [00:22<02:38, 12.02it/s]
 15%|█▌        | 341/2248 [00:23<02:39, 11.98it/s]
 15%|█▌        | 343/2248 [00:23<02:49, 11.27it/s]
 15%|█▌        | 345/2248 [00:23<02:37, 12.07it/s]
 15%|█▌        | 347/2248 [00:23<02:51, 11.08it/s]
 16%|█▌        | 349/2248 [00:24<03:57,  7.99it/s]
 16%|█▌        | 350/2248 [00:24<04:27,  7.10it/s]
 16%|█▌        | 351/2248 [00:24<04:15,  7.43it/s]
 16%|█▌        | 353/2248 [00:24<03:28,  9.09it/s]
 16%|█▌        | 355/2248 [00:24<03:09, 10.01it/s]
 16%|█▌        | 357/2248 [00:24<03:14,  9.70it/s]
 16%|█▌        | 359/2248 [00:25<02:44, 11.46it/s]
 16%|█▌        | 361/2248 [00:25<02:25, 12.99it/s]
 16%|█▌        | 363/2248 [00:25<02:48, 11.19it/s]
 16%|█▌        | 365/2248 [00:25<03:01, 10.38it/s]
 16%|█▋        | 367/2248 [00:25<02:54, 10.77it/s]
 16%|█▋        | 369/2248 [00:25<02:46, 11.28it/s]
 17%|█▋        | 371/2248 [00:26<02:32, 12.31it/s]
 17%|█▋        | 373/2248 [00:26<02:28, 12.63it/s]
 17%|█▋        | 375/2248 [00:26<02:21, 13.23it/s]
 17%|█▋        | 377/2248 [00:26<03:00, 10.37it/s]
 17%|█▋        | 379/2248 [00:26<02:45, 11.28it/s]
 17%|█▋        | 384/2248 [00:27<02:10, 14.25it/s]
 17%|█▋        | 386/2248 [00:27<02:12, 14.01it/s]
 17%|█▋        | 388/2248 [00:27<02:33, 12.12it/s]
 17%|█▋        | 390/2248 [00:27<02:35, 11.94it/s]
 17%|█▋        | 392/2248 [00:27<03:13,  9.60it/s]
 18%|█▊        | 394/2248 [00:28<04:29,  6.88it/s]
 18%|█▊        | 397/2248 [00:28<03:16,  9.41it/s]
 18%|█▊        | 402/2248 [00:28<02:02, 15.12it/s]
 18%|█▊        | 409/2248 [00:28<01:17, 23.73it/s]
 18%|█▊        | 414/2248 [00:28<01:04, 28.34it/s]
 19%|█▊        | 418/2248 [00:28<01:00, 30.12it/s]
 19%|█▉        | 424/2248 [00:29<00:50, 36.36it/s]
 19%|█▉        | 429/2248 [00:29<00:49, 36.94it/s]
 19%|█▉        | 434/2248 [00:29<00:45, 39.68it/s]
 20%|█▉        | 439/2248 [00:29<01:33, 19.42it/s]
 20%|█▉        | 443/2248 [00:30<01:39, 18.11it/s]
 20%|█▉        | 446/2248 [00:30<02:23, 12.58it/s]
 20%|██        | 450/2248 [00:30<01:57, 15.28it/s]
 20%|██        | 453/2248 [00:30<01:47, 16.77it/s]
 20%|██        | 456/2248 [00:31<02:08, 13.93it/s]
 20%|██        | 458/2248 [00:31<02:07, 13.99it/s]
 20%|██        | 460/2248 [00:31<02:43, 10.92it/s]
 21%|██        | 462/2248 [00:31<02:28, 11.99it/s]
 21%|██        | 464/2248 [00:32<02:39, 11.20it/s]
 21%|██        | 467/2248 [00:32<02:08, 13.81it/s]
 21%|██        | 471/2248 [00:32<01:50, 16.15it/s]
 21%|██        | 474/2248 [00:32<01:39, 17.88it/s]
 21%|██        | 476/2248 [00:32<01:57, 15.06it/s]
 21%|██▏       | 478/2248 [00:32<01:54, 15.50it/s]
 21%|██▏       | 481/2248 [00:33<02:11, 13.40it/s]
 21%|██▏       | 483/2248 [00:33<02:47, 10.52it/s]
 22%|██▏       | 486/2248 [00:33<02:32, 11.52it/s]
 22%|██▏       | 488/2248 [00:33<02:45, 10.66it/s]
 22%|██▏       | 490/2248 [00:33<02:26, 12.01it/s]
 22%|██▏       | 495/2248 [00:34<01:58, 14.75it/s]
 22%|██▏       | 497/2248 [00:34<02:02, 14.31it/s]
 22%|██▏       | 499/2248 [00:34<02:18, 12.60it/s]
 22%|██▏       | 501/2248 [00:34<02:31, 11.51it/s]
 22%|██▏       | 503/2248 [00:34<02:17, 12.72it/s]
 23%|██▎       | 507/2248 [00:35<01:45, 16.46it/s]
 23%|██▎       | 509/2248 [00:35<02:02, 14.15it/s]
 23%|██▎       | 511/2248 [00:35<02:00, 14.39it/s]
 23%|██▎       | 513/2248 [00:35<02:28, 11.72it/s]
 23%|██▎       | 515/2248 [00:35<02:37, 10.98it/s]
 23%|██▎       | 517/2248 [00:35<02:23, 12.09it/s]
 23%|██▎       | 519/2248 [00:36<02:39, 10.83it/s]
 23%|██▎       | 521/2248 [00:36<02:39, 10.86it/s]
 23%|██▎       | 523/2248 [00:36<02:19, 12.32it/s]
 23%|██▎       | 526/2248 [00:36<01:53, 15.19it/s]
 24%|██▎       | 532/2248 [00:36<01:09, 24.60it/s]
 24%|██▍       | 537/2248 [00:36<00:56, 30.04it/s]
 24%|██▍       | 544/2248 [00:36<00:45, 37.82it/s]
 25%|██▍       | 551/2248 [00:37<00:38, 44.45it/s]
 25%|██▍       | 557/2248 [00:37<00:35, 47.99it/s]
 25%|██▌       | 563/2248 [00:37<00:40, 41.25it/s]
 25%|██▌       | 569/2248 [00:37<00:37, 45.00it/s]
 26%|██▌       | 574/2248 [00:37<01:08, 24.50it/s]
 26%|██▌       | 578/2248 [00:38<01:29, 18.57it/s]
 26%|██▌       | 581/2248 [00:38<02:19, 11.98it/s]
 26%|██▌       | 584/2248 [00:39<02:17, 12.06it/s]
 26%|██▌       | 586/2248 [00:39<02:20, 11.84it/s]
 26%|██▌       | 588/2248 [00:39<02:29, 11.13it/s]
 26%|██▌       | 590/2248 [00:39<02:14, 12.35it/s]
 26%|██▋       | 592/2248 [00:39<02:22, 11.62it/s]
 26%|██▋       | 594/2248 [00:39<02:13, 12.41it/s]
 27%|██▋       | 599/2248 [00:40<01:57, 14.08it/s]
 27%|██▋       | 601/2248 [00:40<02:10, 12.60it/s]
 27%|██▋       | 603/2248 [00:40<02:22, 11.53it/s]
 27%|██▋       | 605/2248 [00:41<03:10,  8.64it/s]
 27%|██▋       | 606/2248 [00:41<03:28,  7.87it/s]
 27%|██▋       | 607/2248 [00:41<03:55,  6.96it/s]
 27%|██▋       | 608/2248 [00:41<04:17,  6.36it/s]
 27%|██▋       | 609/2248 [00:42<04:51,  5.62it/s]
 27%|██▋       | 610/2248 [00:42<05:09,  5.30it/s]
 27%|██▋       | 612/2248 [00:42<03:42,  7.37it/s]
 27%|██▋       | 618/2248 [00:42<01:38, 16.58it/s]
 28%|██▊       | 623/2248 [00:42<01:10, 23.13it/s]
 28%|██▊       | 629/2248 [00:42<00:52, 30.71it/s]
 28%|██▊       | 635/2248 [00:42<00:42, 37.55it/s]
 28%|██▊       | 640/2248 [00:42<00:40, 39.91it/s]
 29%|██▊       | 645/2248 [00:42<00:38, 41.34it/s]
 29%|██▉       | 650/2248 [00:43<00:55, 28.55it/s]
 29%|██▉       | 654/2248 [00:43<01:53, 14.03it/s]
 29%|██▉       | 657/2248 [00:44<01:48, 14.72it/s]
 29%|██▉       | 660/2248 [00:44<02:23, 11.09it/s]
 29%|██▉       | 662/2248 [00:44<02:29, 10.59it/s]
 30%|██▉       | 664/2248 [00:45<02:37, 10.03it/s]
 30%|██▉       | 666/2248 [00:45<02:35, 10.19it/s]
 30%|██▉       | 668/2248 [00:45<02:20, 11.25it/s]
 30%|██▉       | 670/2248 [00:45<02:33, 10.31it/s]
 30%|██▉       | 673/2248 [00:45<02:10, 12.06it/s]
 30%|███       | 675/2248 [00:45<01:58, 13.33it/s]
 30%|███       | 677/2248 [00:46<01:58, 13.30it/s]
 30%|███       | 679/2248 [00:46<02:15, 11.56it/s]
 30%|███       | 682/2248 [00:46<02:18, 11.27it/s]
 30%|███       | 684/2248 [00:46<02:16, 11.45it/s]
 31%|███       | 686/2248 [00:46<02:08, 12.12it/s]
 31%|███       | 688/2248 [00:47<02:22, 10.96it/s]
 31%|███       | 690/2248 [00:47<02:13, 11.71it/s]
 31%|███       | 692/2248 [00:47<03:10,  8.17it/s]
 31%|███       | 694/2248 [00:47<02:42,  9.58it/s]
 31%|███       | 697/2248 [00:47<02:03, 12.57it/s]
 31%|███       | 699/2248 [00:48<02:45,  9.34it/s]
 31%|███       | 702/2248 [00:48<02:44,  9.40it/s]
 31%|███▏      | 704/2248 [00:48<02:29, 10.34it/s]
 31%|███▏      | 706/2248 [00:48<02:12, 11.68it/s]
 32%|███▏      | 709/2248 [00:49<01:57, 13.09it/s]
 32%|███▏      | 712/2248 [00:49<01:37, 15.76it/s]
 32%|███▏      | 715/2248 [00:49<01:38, 15.53it/s]
 32%|███▏      | 717/2248 [00:49<01:40, 15.19it/s]
 32%|███▏      | 719/2248 [00:49<01:39, 15.42it/s]
 32%|███▏      | 721/2248 [00:49<01:33, 16.36it/s]
 32%|███▏      | 723/2248 [00:49<01:29, 17.00it/s]
 32%|███▏      | 727/2248 [00:50<01:41, 14.99it/s]
 32%|███▏      | 729/2248 [00:50<02:03, 12.34it/s]
 33%|███▎      | 731/2248 [00:50<01:52, 13.53it/s]
 33%|███▎      | 733/2248 [00:50<02:16, 11.14it/s]
 33%|███▎      | 735/2248 [00:51<02:36,  9.65it/s]
 33%|███▎      | 737/2248 [00:51<02:48,  8.94it/s]
 33%|███▎      | 739/2248 [00:51<02:48,  8.95it/s]
 33%|███▎      | 742/2248 [00:51<02:26, 10.31it/s]
 33%|███▎      | 744/2248 [00:52<03:17,  7.63it/s]
 33%|███▎      | 747/2248 [00:52<02:26, 10.25it/s]
 33%|███▎      | 749/2248 [00:52<02:29, 10.05it/s]
 33%|███▎      | 752/2248 [00:52<02:26, 10.18it/s]
 34%|███▎      | 754/2248 [00:53<02:45,  9.02it/s]
 34%|███▎      | 757/2248 [00:53<02:06, 11.77it/s]
 34%|███▍      | 761/2248 [00:53<01:51, 13.28it/s]
 34%|███▍      | 763/2248 [00:53<01:52, 13.19it/s]
 34%|███▍      | 765/2248 [00:53<01:56, 12.72it/s]
 34%|███▍      | 767/2248 [00:53<02:05, 11.76it/s]
 34%|███▍      | 770/2248 [00:54<01:41, 14.52it/s]
 34%|███▍      | 772/2248 [00:54<02:01, 12.17it/s]
 34%|███▍      | 774/2248 [00:54<02:41,  9.13it/s]
 35%|███▍      | 776/2248 [00:55<03:15,  7.54it/s]
 35%|███▍      | 778/2248 [00:55<03:09,  7.76it/s]
 35%|███▍      | 781/2248 [00:55<02:21, 10.34it/s]
 35%|███▍      | 783/2248 [00:55<02:57,  8.25it/s]
 35%|███▍      | 785/2248 [00:56<02:58,  8.18it/s]
 35%|███▌      | 788/2248 [00:56<02:11, 11.06it/s]
 35%|███▌      | 790/2248 [00:56<02:25, 10.05it/s]
 35%|███▌      | 792/2248 [00:56<02:31,  9.63it/s]
 35%|███▌      | 795/2248 [00:56<01:55, 12.57it/s]
 36%|███▌      | 800/2248 [00:56<01:19, 18.13it/s]
 36%|███▌      | 804/2248 [00:57<01:05, 22.21it/s]
 36%|███▌      | 807/2248 [00:57<01:18, 18.45it/s]
 36%|███▌      | 810/2248 [00:57<01:10, 20.39it/s]
 36%|███▌      | 813/2248 [00:57<01:55, 12.46it/s]
 36%|███▋      | 815/2248 [00:58<02:34,  9.29it/s]
 36%|███▋      | 817/2248 [00:58<02:45,  8.62it/s]
 36%|███▋      | 819/2248 [00:58<02:42,  8.81it/s]
 37%|███▋      | 823/2248 [00:58<01:50, 12.85it/s]
 37%|███▋      | 826/2248 [00:59<01:36, 14.71it/s]
 37%|███▋      | 830/2248 [00:59<01:18, 18.06it/s]
 37%|███▋      | 833/2248 [00:59<01:19, 17.90it/s]
 37%|███▋      | 839/2248 [00:59<00:54, 26.08it/s]
 38%|███▊      | 845/2248 [00:59<00:42, 33.27it/s]
 38%|███▊      | 850/2248 [00:59<00:38, 35.90it/s]
 38%|███▊      | 855/2248 [00:59<00:35, 39.24it/s]
 38%|███▊      | 862/2248 [00:59<00:29, 46.41it/s]
 39%|███▊      | 868/2248 [01:00<00:46, 29.88it/s]
 39%|███▉      | 873/2248 [01:00<01:11, 19.36it/s]
 39%|███▉      | 877/2248 [01:00<01:15, 18.07it/s]
 39%|███▉      | 880/2248 [01:01<01:11, 19.12it/s]
 39%|███▉      | 883/2248 [01:01<01:27, 15.64it/s]
 39%|███▉      | 886/2248 [01:01<01:54, 11.88it/s]
 40%|███▉      | 888/2248 [01:02<02:08, 10.59it/s]
 40%|███▉      | 890/2248 [01:02<02:03, 10.96it/s]
 40%|███▉      | 892/2248 [01:02<02:15,  9.98it/s]
 40%|███▉      | 894/2248 [01:02<02:26,  9.22it/s]
 40%|███▉      | 896/2248 [01:03<02:33,  8.81it/s]
 40%|███▉      | 898/2248 [01:03<02:17,  9.82it/s]
 40%|████      | 902/2248 [01:03<01:50, 12.13it/s]
 40%|████      | 904/2248 [01:03<02:01, 11.11it/s]
 40%|████      | 906/2248 [01:04<02:28,  9.01it/s]
 40%|████      | 907/2248 [01:04<02:36,  8.59it/s]
 40%|████      | 908/2248 [01:04<02:44,  8.15it/s]
 40%|████      | 909/2248 [01:04<02:50,  7.84it/s]
 41%|████      | 911/2248 [01:04<02:29,  8.94it/s]
 41%|████      | 912/2248 [01:04<02:30,  8.88it/s]
 41%|████      | 913/2248 [01:04<02:36,  8.53it/s]
 41%|████      | 915/2248 [01:05<02:05, 10.60it/s]
 41%|████      | 917/2248 [01:05<02:24,  9.23it/s]
 41%|████      | 919/2248 [01:05<02:20,  9.48it/s]
 41%|████      | 920/2248 [01:05<02:48,  7.89it/s]
 41%|████      | 921/2248 [01:05<02:45,  8.00it/s]
 41%|████      | 923/2248 [01:05<02:11, 10.11it/s]
 41%|████      | 925/2248 [01:06<02:04, 10.62it/s]
 41%|████      | 927/2248 [01:06<02:16,  9.68it/s]
 41%|████▏     | 929/2248 [01:06<02:32,  8.63it/s]
 41%|████▏     | 932/2248 [01:06<01:56, 11.25it/s]
 42%|████▏     | 934/2248 [01:07<02:06, 10.38it/s]
 42%|████▏     | 936/2248 [01:07<01:53, 11.53it/s]
 42%|████▏     | 938/2248 [01:07<01:43, 12.65it/s]
 42%|████▏     | 940/2248 [01:07<01:36, 13.61it/s]
 42%|████▏     | 943/2248 [01:07<01:25, 15.20it/s]
 42%|████▏     | 945/2248 [01:07<01:47, 12.07it/s]
 42%|████▏     | 949/2248 [01:07<01:15, 17.19it/s]
 42%|████▏     | 952/2248 [01:08<01:16, 17.00it/s]
 42%|████▏     | 954/2248 [01:08<01:19, 16.38it/s]
 43%|████▎     | 956/2248 [01:08<01:36, 13.34it/s]
 43%|████▎     | 958/2248 [01:08<02:09,  9.98it/s]
 43%|████▎     | 960/2248 [01:09<02:38,  8.14it/s]
 43%|████▎     | 962/2248 [01:09<02:37,  8.16it/s]
 43%|████▎     | 963/2248 [01:09<02:40,  7.99it/s]
 43%|████▎     | 964/2248 [01:09<02:34,  8.29it/s]
 43%|████▎     | 966/2248 [01:09<02:44,  7.81it/s]
 43%|████▎     | 967/2248 [01:10<03:02,  7.02it/s]
 43%|████▎     | 969/2248 [01:10<02:49,  7.54it/s]
 43%|████▎     | 970/2248 [01:10<03:17,  6.48it/s]
 43%|████▎     | 972/2248 [01:10<02:34,  8.28it/s]
 43%|████▎     | 974/2248 [01:10<02:27,  8.63it/s]
 43%|████▎     | 976/2248 [01:11<02:15,  9.41it/s]
 44%|████▎     | 978/2248 [01:11<02:28,  8.56it/s]
 44%|████▎     | 981/2248 [01:11<01:54, 11.08it/s]
 44%|████▎     | 983/2248 [01:11<01:53, 11.18it/s]
 44%|████▍     | 985/2248 [01:11<01:45, 11.96it/s]
 44%|████▍     | 988/2248 [01:11<01:27, 14.40it/s]
 44%|████▍     | 991/2248 [01:12<01:30, 13.88it/s]
 44%|████▍     | 993/2248 [01:12<01:30, 13.93it/s]
 44%|████▍     | 996/2248 [01:12<01:14, 16.71it/s]
 44%|████▍     | 998/2248 [01:12<01:13, 16.95it/s]
 44%|████▍     | 1000/2248 [01:12<01:29, 13.89it/s]
 45%|████▍     | 1002/2248 [01:13<01:38, 12.61it/s]
 45%|████▍     | 1004/2248 [01:13<02:19,  8.89it/s]
 45%|████▍     | 1006/2248 [01:13<02:15,  9.14it/s]
 45%|████▍     | 1008/2248 [01:13<02:15,  9.17it/s]
 45%|████▍     | 1010/2248 [01:13<02:03, 10.00it/s]
 45%|████▌     | 1012/2248 [01:14<01:47, 11.45it/s]
 45%|████▌     | 1018/2248 [01:14<01:01, 20.13it/s]
 46%|████▌     | 1024/2248 [01:14<00:44, 27.76it/s]
 46%|████▌     | 1029/2248 [01:14<00:37, 32.36it/s]
 46%|████▌     | 1033/2248 [01:14<00:35, 33.87it/s]
 46%|████▋     | 1040/2248 [01:14<00:28, 41.69it/s]
 46%|████▋     | 1045/2248 [01:14<00:27, 43.78it/s]
 47%|████▋     | 1051/2248 [01:14<00:25, 46.15it/s]
 47%|████▋     | 1056/2248 [01:15<00:49, 24.07it/s]
 47%|████▋     | 1060/2248 [01:15<01:05, 18.12it/s]
 47%|████▋     | 1063/2248 [01:15<01:14, 15.95it/s]
 47%|████▋     | 1066/2248 [01:16<01:21, 14.55it/s]
 48%|████▊     | 1068/2248 [01:16<01:20, 14.64it/s]
 48%|████▊     | 1072/2248 [01:16<01:07, 17.42it/s]
 48%|████▊     | 1075/2248 [01:16<01:03, 18.56it/s]
 48%|████▊     | 1078/2248 [01:16<01:15, 15.40it/s]
 48%|████▊     | 1082/2248 [01:17<01:00, 19.40it/s]
 48%|████▊     | 1085/2248 [01:17<01:29, 13.01it/s]
 48%|████▊     | 1087/2248 [01:17<01:44, 11.16it/s]
 48%|████▊     | 1089/2248 [01:18<02:11,  8.78it/s]
 49%|████▊     | 1091/2248 [01:18<02:43,  7.07it/s]
 49%|████▊     | 1092/2248 [01:18<03:05,  6.22it/s]
 49%|████▊     | 1093/2248 [01:19<03:12,  6.01it/s]
 49%|████▊     | 1094/2248 [01:19<03:21,  5.74it/s]
 49%|████▉     | 1097/2248 [01:19<02:09,  8.91it/s]
 49%|████▉     | 1104/2248 [01:19<01:00, 18.81it/s]
 49%|████▉     | 1111/2248 [01:19<00:41, 27.59it/s]
 50%|████▉     | 1116/2248 [01:19<00:35, 31.97it/s]
 50%|████▉     | 1122/2248 [01:19<00:29, 37.57it/s]
 50%|█████     | 1129/2248 [01:19<00:25, 43.70it/s]
 50%|█████     | 1134/2248 [01:20<00:25, 43.30it/s]
 51%|█████     | 1139/2248 [01:20<00:28, 38.92it/s]
 51%|█████     | 1144/2248 [01:20<00:42, 25.75it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 311.50it/s]

[[np.int64(0), False, 4], [np.int64(1), False, 11], [np.int64(2), False, 10], [np.int64(3), False, 0], [np.int64(5), False, 0], [np.int64(6), False, 2], [np.int64(7), False, 2], [np.int64(8), False, 0], [np.int64(9), False, 1], [np.int64(12), False, 4], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2130, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [06:26<1:56:24, 46.88s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [06:27<1:21:02, 32.86s/it]

tensor(12.2867, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5362, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7922, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [06:27<39:19, 16.16s/it]

tensor(12.3183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8886, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8906, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [06:27<19:10,  7.99s/it]

tensor(12.3386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9653, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0117, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [06:27<09:24,  3.98s/it]

tensor(12.3443, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0371, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0850, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1711, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [06:28<04:41,  2.01s/it]

tensor(12.3388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0385, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2751, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [06:28<02:25,  1.05s/it]

tensor(12.3095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0382, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3165, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [06:28<01:19,  1.72it/s]

tensor(12.2773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3414, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3544, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [06:28<00:46,  2.88it/s]

tensor(12.2666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3648, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3822, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [06:29<00:30,  4.30it/s]

tensor(12.2718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4030, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4161, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [06:29<00:23,  5.63it/s]

tensor(12.2737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4152, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4220, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [06:29<00:19,  6.60it/s]

tensor(12.2635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4295, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4340, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [06:29<00:17,  7.13it/s]

tensor(12.2462, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4439, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4518, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [06:30<00:17,  7.24it/s]

tensor(12.2327, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4656, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [06:30<00:15,  7.67it/s]

tensor(12.2243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4781, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [06:30<00:15,  7.90it/s]

tensor(12.2171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4903, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4998, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [06:30<00:15,  7.82it/s]

tensor(12.2096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5059, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5140, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [06:31<00:14,  7.82it/s]

tensor(12.2030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2002, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5274, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [06:31<00:14,  7.77it/s]

tensor(12.1973, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5257, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5277, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [06:31<00:14,  7.68it/s]

tensor(12.1922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5276, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1899, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5273, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [06:31<00:14,  7.72it/s]

tensor(12.1876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5298, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1854, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5302, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [06:32<00:13,  7.89it/s]

tensor(12.1833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5288, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5290, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [06:32<00:13,  7.82it/s]

tensor(12.1788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5322, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1764, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5322, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [06:32<00:13,  7.84it/s]

tensor(12.1743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5336, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5349, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [06:33<00:12,  7.98it/s]

tensor(12.1702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5351, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5359, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [06:33<00:12,  8.03it/s]

tensor(12.1665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5353, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([199, 349, 169, 126, 138, 205,  33, 125, 222, 127, 197,  77, 189,  92])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:17, 16.38it/s]
  0%|          | 9/2248 [00:00<00:53, 42.11it/s]
  1%|          | 15/2248 [00:00<00:45, 48.88it/s]
  1%|          | 21/2248 [00:00<00:44, 49.54it/s]
  1%|          | 27/2248 [00:00<00:54, 40.48it/s]
  2%|▏         | 34/2248 [00:00<00:48, 45.75it/s]
  2%|▏         | 40/2248 [00:00<00:49, 44.22it/s]
  2%|▏         | 45/2248 [00:01<01:00, 36.43it/s]
  2%|▏         | 49/2248 [00:01<01:00, 36.16it/s]
  2%|▏         | 54/2248 [00:01<00:55, 39.27it/s]
  3%|▎         | 59/2248 [00:01<00:55, 39.39it/s]
  3%|▎         | 64/2248 [00:01<00:53, 40.55it/s]
  3%|▎         | 69/2248 [00:01<00:54, 40.22it/s]
  3%|▎         | 75/2248 [00:02<01:51, 19.44it/s]
  4%|▎         | 79/2248 [00:02<01:46, 20.37it/s]
  4%|▍         | 85/2248 [00:02<01:23, 26.02it/s]
  4%|▍         | 89/2248 [00:03<02:32, 14.18it/s]
  4%|▍         | 96/2248 [00:03<01:45, 20.31it/s]
  4%|▍         | 100/2248 [00:03<02:33, 13.98it/s]
  5%|▍         | 103/2248 [00:04<02:17, 15.58it/s]
  5%|▍         | 106/2248 [00:04<02:04, 17.21it/s]
  5%|▍         | 111/2248 [00:04<01:36, 22.10it/s]
  5%|▌         | 117/2248 [00:04<01:57, 18.08it/s]
  5%|▌         | 120/2248 [00:05<02:51, 12.38it/s]
  5%|▌         | 123/2248 [00:05<02:33, 13.86it/s]
  6%|▌         | 126/2248 [00:05<03:06, 11.35it/s]
  6%|▌         | 128/2248 [00:06<04:33,  7.74it/s]
  6%|▌         | 130/2248 [00:06<04:12,  8.38it/s]
  6%|▌         | 132/2248 [00:06<03:38,  9.69it/s]
  6%|▌         | 134/2248 [00:07<04:28,  7.86it/s]
  6%|▌         | 136/2248 [00:07<04:31,  7.79it/s]
  6%|▌         | 138/2248 [00:07<03:58,  8.84it/s]
  6%|▋         | 142/2248 [00:07<02:42, 12.96it/s]
  6%|▋         | 144/2248 [00:07<02:29, 14.04it/s]
  6%|▋         | 146/2248 [00:08<04:01,  8.71it/s]
  7%|▋         | 148/2248 [00:08<03:27, 10.13it/s]
  7%|▋         | 150/2248 [00:08<03:06, 11.23it/s]
  7%|▋         | 152/2248 [00:08<04:24,  7.94it/s]
  7%|▋         | 154/2248 [00:08<03:44,  9.32it/s]
  7%|▋         | 156/2248 [00:09<05:25,  6.43it/s]
  7%|▋         | 158/2248 [00:10<09:31,  3.66it/s]
  7%|▋         | 159/2248 [00:10<09:45,  3.57it/s]
  7%|▋         | 160/2248 [00:11<09:18,  3.74it/s]
  7%|▋         | 162/2248 [00:11<07:40,  4.53it/s]
  7%|▋         | 164/2248 [00:11<05:42,  6.09it/s]
  7%|▋         | 165/2248 [00:11<06:35,  5.26it/s]
  7%|▋         | 167/2248 [00:11<04:55,  7.05it/s]
  8%|▊         | 169/2248 [00:12<06:30,  5.33it/s]
  8%|▊         | 172/2248 [00:12<04:24,  7.86it/s]
  8%|▊         | 174/2248 [00:13<06:19,  5.47it/s]
  8%|▊         | 176/2248 [00:13<07:28,  4.62it/s]
  8%|▊         | 177/2248 [00:13<06:49,  5.06it/s]
  8%|▊         | 178/2248 [00:14<10:03,  3.43it/s]
  8%|▊         | 181/2248 [00:14<06:01,  5.71it/s]
  8%|▊         | 187/2248 [00:15<04:32,  7.57it/s]
  8%|▊         | 189/2248 [00:15<04:03,  8.46it/s]
  9%|▊         | 195/2248 [00:16<03:47,  9.02it/s]
  9%|▉         | 198/2248 [00:16<03:08, 10.89it/s]
  9%|▉         | 202/2248 [00:16<03:56,  8.66it/s]
  9%|▉         | 204/2248 [00:16<03:34,  9.52it/s]
  9%|▉         | 206/2248 [00:17<04:59,  6.81it/s]
  9%|▉         | 208/2248 [00:18<06:07,  5.55it/s]
  9%|▉         | 209/2248 [00:18<08:20,  4.07it/s]
  9%|▉         | 210/2248 [00:19<10:07,  3.35it/s]
  9%|▉         | 211/2248 [00:19<11:58,  2.84it/s]
  9%|▉         | 212/2248 [00:20<13:26,  2.52it/s]
 10%|▉         | 214/2248 [00:20<09:07,  3.72it/s]
 10%|▉         | 220/2248 [00:20<03:50,  8.81it/s]
 10%|█         | 226/2248 [00:20<02:17, 14.71it/s]
 10%|█         | 231/2248 [00:20<01:42, 19.65it/s]
 11%|█         | 237/2248 [00:21<01:17, 26.05it/s]
 11%|█         | 242/2248 [00:21<01:16, 26.19it/s]
 11%|█         | 249/2248 [00:21<01:00, 33.23it/s]
 11%|█▏        | 256/2248 [00:21<00:49, 40.12it/s]
 12%|█▏        | 263/2248 [00:21<00:47, 42.07it/s]
 12%|█▏        | 269/2248 [00:21<00:45, 43.72it/s]
 12%|█▏        | 274/2248 [00:22<01:55, 17.11it/s]
 12%|█▏        | 278/2248 [00:23<02:49, 11.64it/s]
 13%|█▎        | 282/2248 [00:23<03:16, 10.03it/s]
 13%|█▎        | 285/2248 [00:24<02:57, 11.04it/s]
 13%|█▎        | 288/2248 [00:24<02:43, 11.99it/s]
 13%|█▎        | 292/2248 [00:24<03:32,  9.22it/s]
 13%|█▎        | 295/2248 [00:24<02:59, 10.87it/s]
 13%|█▎        | 301/2248 [00:25<02:06, 15.41it/s]
 14%|█▎        | 304/2248 [00:25<03:31,  9.20it/s]
 14%|█▎        | 306/2248 [00:26<03:11, 10.13it/s]
 14%|█▎        | 308/2248 [00:26<05:00,  6.45it/s]
 14%|█▍        | 310/2248 [00:27<05:17,  6.11it/s]
 14%|█▍        | 312/2248 [00:27<04:23,  7.35it/s]
 14%|█▍        | 314/2248 [00:27<06:01,  5.35it/s]
 14%|█▍        | 316/2248 [00:28<06:11,  5.21it/s]
 14%|█▍        | 318/2248 [00:28<06:16,  5.12it/s]
 14%|█▍        | 320/2248 [00:29<06:53,  4.66it/s]
 14%|█▍        | 322/2248 [00:29<06:32,  4.91it/s]
 14%|█▍        | 323/2248 [00:29<07:19,  4.38it/s]
 14%|█▍        | 325/2248 [00:30<06:34,  4.87it/s]
 15%|█▍        | 326/2248 [00:30<05:57,  5.38it/s]
 15%|█▍        | 328/2248 [00:30<04:40,  6.86it/s]
 15%|█▍        | 332/2248 [00:31<04:20,  7.34it/s]
 15%|█▍        | 335/2248 [00:31<03:13,  9.87it/s]
 15%|█▌        | 339/2248 [00:31<03:56,  8.07it/s]
 15%|█▌        | 341/2248 [00:31<03:25,  9.26it/s]
 15%|█▌        | 343/2248 [00:32<04:56,  6.43it/s]
 15%|█▌        | 345/2248 [00:33<07:24,  4.28it/s]
 15%|█▌        | 346/2248 [00:33<06:46,  4.68it/s]
 15%|█▌        | 347/2248 [00:33<08:09,  3.88it/s]
 15%|█▌        | 348/2248 [00:34<09:45,  3.25it/s]
 16%|█▌        | 349/2248 [00:34<08:35,  3.68it/s]
 16%|█▌        | 350/2248 [00:34<08:05,  3.91it/s]
 16%|█▌        | 353/2248 [00:35<06:20,  4.98it/s]
 16%|█▌        | 355/2248 [00:35<04:50,  6.52it/s]
 16%|█▌        | 356/2248 [00:35<06:42,  4.70it/s]
 16%|█▌        | 358/2248 [00:35<05:02,  6.24it/s]
 16%|█▌        | 362/2248 [00:36<05:14,  6.00it/s]
 16%|█▌        | 364/2248 [00:37<06:27,  4.86it/s]
 16%|█▋        | 366/2248 [00:37<05:08,  6.09it/s]
 17%|█▋        | 371/2248 [00:38<04:39,  6.71it/s]
 17%|█▋        | 374/2248 [00:38<03:41,  8.48it/s]
 17%|█▋        | 380/2248 [00:38<02:13, 13.96it/s]
 17%|█▋        | 385/2248 [00:38<02:18, 13.46it/s]
 17%|█▋        | 388/2248 [00:39<03:08,  9.87it/s]
 17%|█▋        | 390/2248 [00:39<03:59,  7.77it/s]
 17%|█▋        | 392/2248 [00:40<03:58,  7.77it/s]
 18%|█▊        | 394/2248 [00:40<05:41,  5.42it/s]
 18%|█▊        | 395/2248 [00:41<05:57,  5.18it/s]
 18%|█▊        | 397/2248 [00:41<04:48,  6.42it/s]
 18%|█▊        | 402/2248 [00:41<02:46, 11.09it/s]
 18%|█▊        | 408/2248 [00:41<01:51, 16.51it/s]
 18%|█▊        | 411/2248 [00:41<01:40, 18.37it/s]
 18%|█▊        | 415/2248 [00:41<01:30, 20.30it/s]
 19%|█▊        | 421/2248 [00:41<01:07, 27.20it/s]
 19%|█▉        | 427/2248 [00:41<00:54, 33.69it/s]
 19%|█▉        | 432/2248 [00:42<00:50, 36.18it/s]
 19%|█▉        | 437/2248 [00:42<02:12, 13.62it/s]
 20%|█▉        | 441/2248 [00:43<03:13,  9.35it/s]
 20%|█▉        | 444/2248 [00:44<03:42,  8.10it/s]
 20%|█▉        | 446/2248 [00:44<03:51,  7.77it/s]
 20%|█▉        | 449/2248 [00:44<03:15,  9.18it/s]
 20%|██        | 452/2248 [00:44<02:39, 11.24it/s]
 20%|██        | 457/2248 [00:45<02:28, 12.09it/s]
 20%|██        | 459/2248 [00:45<02:18, 12.87it/s]
 21%|██        | 464/2248 [00:45<01:38, 18.16it/s]
 21%|██        | 472/2248 [00:46<02:01, 14.66it/s]
 21%|██        | 475/2248 [00:46<02:58,  9.95it/s]
 21%|██        | 477/2248 [00:47<03:55,  7.51it/s]
 21%|██▏       | 479/2248 [00:48<04:56,  5.96it/s]
 21%|██▏       | 480/2248 [00:48<06:20,  4.65it/s]
 21%|██▏       | 481/2248 [00:49<07:56,  3.71it/s]
 22%|██▏       | 484/2248 [00:49<05:19,  5.52it/s]
 22%|██▏       | 486/2248 [00:49<06:14,  4.70it/s]
 22%|██▏       | 487/2248 [00:50<08:08,  3.61it/s]
 22%|██▏       | 489/2248 [00:50<06:02,  4.85it/s]
 22%|██▏       | 495/2248 [00:51<04:26,  6.58it/s]
 22%|██▏       | 498/2248 [00:51<03:30,  8.31it/s]
 22%|██▏       | 500/2248 [00:51<04:11,  6.94it/s]
 22%|██▏       | 503/2248 [00:52<03:15,  8.91it/s]
 23%|██▎       | 509/2248 [00:52<03:13,  8.97it/s]
 23%|██▎       | 511/2248 [00:52<02:54,  9.93it/s]
 23%|██▎       | 514/2248 [00:53<03:41,  7.83it/s]
 23%|██▎       | 516/2248 [00:54<04:50,  5.95it/s]
 23%|██▎       | 521/2248 [00:54<03:02,  9.47it/s]
 23%|██▎       | 524/2248 [00:54<02:35, 11.12it/s]
 24%|██▎       | 530/2248 [00:54<01:43, 16.53it/s]
 24%|██▍       | 535/2248 [00:54<01:25, 19.97it/s]
 24%|██▍       | 539/2248 [00:54<01:15, 22.72it/s]
 24%|██▍       | 544/2248 [00:54<01:02, 27.12it/s]
 24%|██▍       | 550/2248 [00:54<00:51, 33.14it/s]
 25%|██▍       | 555/2248 [00:55<00:46, 36.34it/s]
 25%|██▍       | 561/2248 [00:55<00:40, 41.99it/s]
 25%|██▌       | 566/2248 [00:55<00:46, 36.20it/s]
 25%|██▌       | 571/2248 [00:55<00:53, 31.25it/s]
 26%|██▌       | 575/2248 [00:56<02:03, 13.59it/s]
 26%|██▌       | 578/2248 [00:56<01:49, 15.31it/s]
 26%|██▌       | 581/2248 [00:57<02:56,  9.43it/s]
 26%|██▌       | 584/2248 [00:58<04:34,  6.05it/s]
 26%|██▌       | 586/2248 [00:58<05:22,  5.15it/s]
 26%|██▌       | 588/2248 [00:59<06:14,  4.43it/s]
 26%|██▌       | 590/2248 [00:59<05:12,  5.31it/s]
 26%|██▋       | 592/2248 [01:00<05:26,  5.07it/s]
 26%|██▋       | 594/2248 [01:00<04:25,  6.24it/s]
 27%|██▋       | 600/2248 [01:00<02:20, 11.76it/s]
 27%|██▋       | 603/2248 [01:00<03:04,  8.92it/s]
 27%|██▋       | 605/2248 [01:01<05:23,  5.07it/s]
 27%|██▋       | 607/2248 [01:02<07:21,  3.72it/s]
 27%|██▋       | 609/2248 [01:03<07:10,  3.80it/s]
 27%|██▋       | 610/2248 [01:03<07:11,  3.79it/s]
 27%|██▋       | 612/2248 [01:03<05:42,  4.77it/s]
 27%|██▋       | 614/2248 [01:03<04:26,  6.14it/s]
 27%|██▋       | 617/2248 [01:04<03:03,  8.89it/s]
 28%|██▊       | 622/2248 [01:04<01:51, 14.52it/s]
 28%|██▊       | 628/2248 [01:04<01:19, 20.27it/s]
 28%|██▊       | 631/2248 [01:04<01:15, 21.37it/s]
 28%|██▊       | 636/2248 [01:04<01:00, 26.77it/s]
 29%|██▊       | 642/2248 [01:04<00:48, 33.15it/s]
 29%|██▉       | 648/2248 [01:04<00:40, 39.39it/s]
 29%|██▉       | 653/2248 [01:05<01:32, 17.33it/s]
 29%|██▉       | 657/2248 [01:05<01:30, 17.67it/s]
 29%|██▉       | 660/2248 [01:06<02:20, 11.27it/s]
 29%|██▉       | 663/2248 [01:06<03:14,  8.16it/s]
 30%|██▉       | 669/2248 [01:07<02:07, 12.38it/s]
 30%|██▉       | 672/2248 [01:07<03:07,  8.40it/s]
 30%|███       | 675/2248 [01:07<02:42,  9.67it/s]
 30%|███       | 678/2248 [01:08<03:06,  8.41it/s]
 30%|███       | 680/2248 [01:08<02:45,  9.46it/s]
 30%|███       | 682/2248 [01:09<03:47,  6.89it/s]
 30%|███       | 684/2248 [01:09<04:45,  5.47it/s]
 31%|███       | 686/2248 [01:10<05:39,  4.60it/s]
 31%|███       | 688/2248 [01:10<06:15,  4.16it/s]
 31%|███       | 690/2248 [01:11<04:55,  5.27it/s]
 31%|███       | 692/2248 [01:11<05:49,  4.45it/s]
 31%|███       | 695/2248 [01:11<04:02,  6.42it/s]
 31%|███       | 698/2248 [01:12<04:24,  5.85it/s]
 31%|███       | 700/2248 [01:13<05:20,  4.83it/s]
 31%|███       | 702/2248 [01:13<05:57,  4.33it/s]
 31%|███▏      | 704/2248 [01:14<06:34,  3.92it/s]
 31%|███▏      | 706/2248 [01:14<05:20,  4.81it/s]
 32%|███▏      | 711/2248 [01:14<02:59,  8.54it/s]
 32%|███▏      | 713/2248 [01:15<04:09,  6.16it/s]
 32%|███▏      | 717/2248 [01:15<02:49,  9.03it/s]
 32%|███▏      | 725/2248 [01:15<01:29, 16.94it/s]
 32%|███▏      | 729/2248 [01:16<02:15, 11.17it/s]
 33%|███▎      | 733/2248 [01:16<01:50, 13.70it/s]
 33%|███▎      | 736/2248 [01:17<03:42,  6.79it/s]
 33%|███▎      | 739/2248 [01:18<04:10,  6.02it/s]
 33%|███▎      | 742/2248 [01:18<04:29,  5.58it/s]
 33%|███▎      | 744/2248 [01:19<06:24,  3.91it/s]
 33%|███▎      | 747/2248 [01:20<04:47,  5.22it/s]
 33%|███▎      | 749/2248 [01:20<05:29,  4.55it/s]
 33%|███▎      | 752/2248 [01:21<05:32,  4.50it/s]
 34%|███▎      | 754/2248 [01:21<04:32,  5.47it/s]
 34%|███▍      | 760/2248 [01:21<02:29,  9.95it/s]
 34%|███▍      | 767/2248 [01:21<01:31, 16.27it/s]
 34%|███▍      | 772/2248 [01:22<02:01, 12.12it/s]
 34%|███▍      | 775/2248 [01:24<04:52,  5.04it/s]
 35%|███▍      | 778/2248 [01:25<06:07,  4.00it/s]
 35%|███▍      | 781/2248 [01:25<04:53,  5.00it/s]
 35%|███▍      | 783/2248 [01:26<06:52,  3.56it/s]
 35%|███▍      | 785/2248 [01:27<06:05,  4.01it/s]
 35%|███▌      | 787/2248 [01:27<04:59,  4.87it/s]
 35%|███▌      | 792/2248 [01:27<04:01,  6.02it/s]
 35%|███▌      | 795/2248 [01:28<03:17,  7.36it/s]
 35%|███▌      | 797/2248 [01:28<03:21,  7.18it/s]
 36%|███▌      | 799/2248 [01:28<02:57,  8.17it/s]
 36%|███▌      | 805/2248 [01:28<01:45, 13.63it/s]
 36%|███▌      | 808/2248 [01:28<01:50, 13.08it/s]
 36%|███▌      | 810/2248 [01:28<01:48, 13.29it/s]
 36%|███▌      | 812/2248 [01:29<02:24,  9.90it/s]
 36%|███▋      | 815/2248 [01:29<02:01, 11.83it/s]
 36%|███▋      | 817/2248 [01:30<03:18,  7.20it/s]
 36%|███▋      | 820/2248 [01:30<02:29,  9.56it/s]
 37%|███▋      | 827/2248 [01:30<01:21, 17.37it/s]
 37%|███▋      | 831/2248 [01:30<01:12, 19.56it/s]
 37%|███▋      | 838/2248 [01:30<00:51, 27.54it/s]
 38%|███▊      | 844/2248 [01:30<00:41, 33.81it/s]
 38%|███▊      | 850/2248 [01:30<00:36, 38.26it/s]
 38%|███▊      | 855/2248 [01:31<00:41, 33.91it/s]
 38%|███▊      | 862/2248 [01:31<00:34, 40.69it/s]
 39%|███▊      | 867/2248 [01:31<00:56, 24.57it/s]
 39%|███▊      | 871/2248 [01:31<01:12, 18.93it/s]
 39%|███▉      | 874/2248 [01:32<01:12, 18.96it/s]
 39%|███▉      | 877/2248 [01:32<01:26, 15.76it/s]
 39%|███▉      | 880/2248 [01:32<01:24, 16.12it/s]
 39%|███▉      | 883/2248 [01:33<02:31,  9.01it/s]
 39%|███▉      | 885/2248 [01:33<02:17,  9.90it/s]
 40%|███▉      | 888/2248 [01:33<01:50, 12.26it/s]
 40%|███▉      | 892/2248 [01:33<01:24, 16.02it/s]
 40%|███▉      | 895/2248 [01:34<02:07, 10.60it/s]
 40%|███▉      | 899/2248 [01:34<01:36, 13.97it/s]
 40%|████      | 902/2248 [01:35<02:42,  8.29it/s]
 40%|████      | 904/2248 [01:35<03:39,  6.12it/s]
 40%|████      | 906/2248 [01:36<04:25,  5.06it/s]
 40%|████      | 908/2248 [01:37<06:34,  3.40it/s]
 40%|████      | 910/2248 [01:38<06:47,  3.29it/s]
 41%|████      | 911/2248 [01:38<07:42,  2.89it/s]
 41%|████      | 912/2248 [01:39<08:49,  2.52it/s]
 41%|████      | 913/2248 [01:40<09:50,  2.26it/s]
 41%|████      | 915/2248 [01:40<06:38,  3.35it/s]
 41%|████      | 917/2248 [01:40<06:22,  3.48it/s]
 41%|████      | 920/2248 [01:41<05:31,  4.01it/s]
 41%|████      | 923/2248 [01:41<03:42,  5.97it/s]
 41%|████      | 925/2248 [01:41<03:46,  5.85it/s]
 41%|████      | 927/2248 [01:42<03:54,  5.64it/s]
 41%|████▏     | 930/2248 [01:42<02:52,  7.65it/s]
 41%|████▏     | 932/2248 [01:42<02:27,  8.94it/s]
 42%|████▏     | 934/2248 [01:42<02:07, 10.34it/s]
 42%|████▏     | 940/2248 [01:42<01:11, 18.38it/s]
 42%|████▏     | 947/2248 [01:42<00:46, 27.83it/s]
 42%|████▏     | 952/2248 [01:43<01:24, 15.27it/s]
 42%|████▏     | 955/2248 [01:43<01:17, 16.65it/s]
 43%|████▎     | 958/2248 [01:44<02:56,  7.33it/s]
 43%|████▎     | 961/2248 [01:45<04:17,  5.00it/s]
 43%|████▎     | 963/2248 [01:46<05:56,  3.60it/s]
 43%|████▎     | 965/2248 [01:47<04:53,  4.37it/s]
 43%|████▎     | 967/2248 [01:47<04:49,  4.43it/s]
 43%|████▎     | 969/2248 [01:47<04:41,  4.54it/s]
 43%|████▎     | 970/2248 [01:48<05:03,  4.21it/s]
 43%|████▎     | 972/2248 [01:48<03:54,  5.44it/s]
 43%|████▎     | 974/2248 [01:48<04:31,  4.69it/s]
 43%|████▎     | 976/2248 [01:49<05:04,  4.17it/s]
 44%|████▎     | 978/2248 [01:49<03:54,  5.41it/s]
 44%|████▎     | 981/2248 [01:50<04:03,  5.20it/s]
 44%|████▎     | 983/2248 [01:50<03:16,  6.44it/s]
 44%|████▍     | 985/2248 [01:50<03:39,  5.77it/s]
 44%|████▍     | 987/2248 [01:51<03:51,  5.44it/s]
 44%|████▍     | 989/2248 [01:51<03:15,  6.44it/s]
 44%|████▍     | 992/2248 [01:51<02:17,  9.16it/s]
 44%|████▍     | 998/2248 [01:51<01:16, 16.44it/s]
 45%|████▍     | 1001/2248 [01:52<02:18,  8.99it/s]
 45%|████▍     | 1004/2248 [01:53<03:32,  5.86it/s]
 45%|████▍     | 1006/2248 [01:54<04:47,  4.32it/s]
 45%|████▍     | 1008/2248 [01:54<05:02,  4.10it/s]
 45%|████▍     | 1009/2248 [01:55<05:12,  3.96it/s]
 45%|████▍     | 1011/2248 [01:55<04:00,  5.14it/s]
 45%|████▌     | 1013/2248 [01:55<03:14,  6.36it/s]
 45%|████▌     | 1015/2248 [01:55<02:36,  7.89it/s]
 45%|████▌     | 1021/2248 [01:55<01:22, 14.81it/s]
 46%|████▌     | 1026/2248 [01:55<01:01, 19.77it/s]
 46%|████▌     | 1031/2248 [01:55<00:50, 24.20it/s]
 46%|████▌     | 1035/2248 [01:55<00:48, 24.87it/s]
 46%|████▋     | 1042/2248 [01:56<00:36, 32.78it/s]
 47%|████▋     | 1048/2248 [01:56<00:31, 38.37it/s]
 47%|████▋     | 1053/2248 [01:56<00:32, 36.52it/s]
 47%|████▋     | 1058/2248 [01:57<01:43, 11.55it/s]
 47%|████▋     | 1061/2248 [01:57<01:35, 12.41it/s]
 47%|████▋     | 1064/2248 [01:57<01:40, 11.78it/s]
 47%|████▋     | 1067/2248 [01:58<02:18,  8.53it/s]
 48%|████▊     | 1069/2248 [01:58<02:06,  9.33it/s]
 48%|████▊     | 1071/2248 [01:59<02:59,  6.56it/s]
 48%|████▊     | 1075/2248 [01:59<02:03,  9.49it/s]
 48%|████▊     | 1077/2248 [01:59<02:31,  7.70it/s]
 48%|████▊     | 1079/2248 [02:00<02:14,  8.69it/s]
 48%|████▊     | 1085/2248 [02:00<01:16, 15.12it/s]
 48%|████▊     | 1088/2248 [02:00<01:33, 12.35it/s]
 49%|████▊     | 1091/2248 [02:01<02:08,  9.02it/s]
 49%|████▊     | 1093/2248 [02:01<02:53,  6.64it/s]
 49%|████▊     | 1095/2248 [02:02<02:57,  6.50it/s]
 49%|████▉     | 1097/2248 [02:02<02:34,  7.46it/s]
 49%|████▉     | 1099/2248 [02:02<02:11,  8.76it/s]
 49%|████▉     | 1103/2248 [02:02<01:27, 13.03it/s]
 49%|████▉     | 1108/2248 [02:02<01:00, 18.96it/s]
 50%|████▉     | 1114/2248 [02:02<00:44, 25.44it/s]
 50%|████▉     | 1118/2248 [02:02<00:41, 27.19it/s]
 50%|█████     | 1125/2248 [02:02<00:31, 35.72it/s]
 50%|█████     | 1131/2248 [02:02<00:27, 41.27it/s]
 51%|█████     | 1136/2248 [02:03<00:26, 42.10it/s]
 51%|█████     | 1141/2248 [02:03<00:25, 43.14it/s]
 51%|█████     | 1146/2248 [02:04<01:26, 12.80it/s]
 51%|█████     | 1150/2248 [02:04<01:35, 11.53it/s]
 51%|█████▏    | 1153/2248 [02:05<02:08,  8.52it/s]
 51%|█████▏    | 1155/2248 [02:05<02:15,  8.07it/s]
 51%|█████▏    | 1157/2248 [02:05<02:01,  8.97it/s]
 52%|█████▏    | 1159/2248 [02:05<01:47, 10.15it/s]
 52%|█████▏    | 1161/2248 [02:06<01:47, 10.14it/s]
 52%|█████▏    | 1164/2248 [02:06<02:23,  7.55it/s]
 52%|█████▏    | 1166/2248 [02:06<02:09,  8.35it/s]
 52%|█████▏    | 1168/2248 [02:07<01:53,  9.49it/s]
 52%|█████▏    | 1170/2248 [02:07<02:07,  8.47it/s]
 52%|█████▏    | 1172/2248 [02:07<01:58,  9.12it/s]
 52%|█████▏    | 1174/2248 [02:07<01:42, 10.46it/s]
 52%|█████▏    | 1178/2248 [02:07<01:39, 10.73it/s]
 52%|█████▏    | 1180/2248 [02:08<01:56,  9.17it/s]
 53%|█████▎    | 1182/2248 [02:08<02:12,  8.03it/s]
 53%|█████▎    | 1185/2248 [02:08<01:41, 10.46it/s]
 53%|█████▎    | 1187/2248 [02:09<01:54,  9.25it/s]
 53%|█████▎    | 1189/2248 [02:09<03:09,  5.60it/s]
 53%|█████▎    | 1191/2248 [02:09<02:32,  6.93it/s]
 53%|█████▎    | 1193/2248 [02:10<02:05,  8.39it/s]
 53%|█████▎    | 1195/2248 [02:10<02:26,  7.17it/s]
 53%|█████▎    | 1198/2248 [02:10<01:45,  9.92it/s]
 53%|█████▎    | 1201/2248 [02:11<02:08,  8.16it/s]
 54%|█████▎    | 1204/2248 [02:11<01:39, 10.52it/s]
 54%|█████▎    | 1206/2248 [02:11<02:07,  8.16it/s]
 54%|█████▍    | 1209/2248 [02:11<01:36, 10.75it/s]
 54%|█████▍    | 1215/2248 [02:12<01:43, 10.02it/s]
 54%|█████▍    | 1218/2248 [02:12<01:27, 11.82it/s]
 54%|█████▍    | 1224/2248 [02:12<00:57, 17.76it/s]
 55%|█████▍    | 1227/2248 [02:13<01:35, 10.66it/s]
 55%|█████▍    | 1230/2248 [02:13<02:03,  8.23it/s]
 55%|█████▍    | 1232/2248 [02:14<03:22,  5.02it/s]
 55%|█████▍    | 1234/2248 [02:14<02:49,  5.97it/s]
 55%|█████▌    | 1239/2248 [02:15<01:44,  9.63it/s]
 55%|█████▌    | 1242/2248 [02:15<02:07,  7.91it/s]
 55%|█████▌    | 1244/2248 [02:15<02:16,  7.37it/s]
 55%|█████▌    | 1246/2248 [02:16<02:40,  6.24it/s]
 56%|█████▌    | 1249/2248 [02:16<01:59,  8.34it/s]
 56%|█████▌    | 1255/2248 [02:16<01:11, 13.85it/s]
 56%|█████▌    | 1260/2248 [02:16<00:52, 18.73it/s]
 56%|█████▋    | 1265/2248 [02:16<00:42, 23.10it/s]
 56%|█████▋    | 1269/2248 [02:17<00:38, 25.37it/s]
 57%|█████▋    | 1273/2248 [02:17<01:18, 12.39it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 307.32it/s]

[[np.int64(0), False, 8], [np.int64(1), False, 12], [np.int64(2), False, 12], [np.int64(3), False, 8], [np.int64(4), False, 9], [np.int64(5), False, 0], [np.int64(6), False, 9], [np.int64(7), False, 0], [np.int64(9), False, 12], [np.int64(10), False, 1], [np.int64(11), False, 9], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6540, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [10:16<1:50:37, 67.04s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [10:16<1:16:43, 46.97s/it]

tensor(12.1669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7922, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1752, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0084, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [10:16<36:55, 23.08s/it]

tensor(12.1861, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1029, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1150, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [10:17<17:49, 11.38s/it]

tensor(12.1956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1824, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1297, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [10:17<08:38,  5.64s/it]

tensor(12.1889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1442, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1600, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [10:17<04:14,  2.83s/it]

tensor(12.1825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1835, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2075, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [10:17<02:07,  1.45s/it]

tensor(12.1789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0369, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2208, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2587, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [10:18<01:06,  1.30it/s]

tensor(12.1766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0375, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9517, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [10:18<00:36,  2.27it/s]

tensor(12.1761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0367, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2374, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [10:18<00:23,  3.55it/s]

tensor(12.1930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2254, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0385, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2486, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [10:18<00:16,  4.97it/s]

tensor(12.1805, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0395, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2872, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3042, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [10:19<00:12,  6.18it/s]

tensor(12.1982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3713, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [10:19<00:11,  6.83it/s]

tensor(12.2003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0407, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3953, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0405, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4076, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [10:19<00:10,  7.29it/s]

tensor(12.1672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4193, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4040, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [10:19<00:09,  7.41it/s]

tensor(12.1716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0387, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4014, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3978, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [10:20<00:09,  7.52it/s]

tensor(12.1816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0373, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3927, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [10:20<00:09,  7.55it/s]

tensor(12.1603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1488, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [10:20<00:08,  7.84it/s]

tensor(12.1422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3960, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3958, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [10:20<00:07,  8.03it/s]

tensor(12.1424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4021, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4033, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [10:21<00:07,  8.03it/s]

tensor(12.1428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4095, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4131, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [10:21<00:07,  7.94it/s]

tensor(12.1363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4136, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4185, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [10:21<00:07,  7.99it/s]

tensor(12.1294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4166, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4201, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [10:21<00:06,  8.13it/s]

tensor(12.1245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4201, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1221, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4189, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [10:22<00:06,  8.01it/s]

tensor(12.1195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4238, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4284, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [10:22<00:06,  7.94it/s]

tensor(12.1142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4303, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4332, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [10:22<00:06,  8.04it/s]

tensor(12.1108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4369, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([219, 214, 247,  54, 116, 133, 112, 189, 173, 170, 115, 322,  95,  89])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<01:58, 18.90it/s]
  0%|          | 8/2248 [00:00<00:57, 39.10it/s]
  1%|          | 13/2248 [00:00<00:52, 42.36it/s]
  1%|          | 20/2248 [00:00<00:44, 50.16it/s]
  1%|          | 26/2248 [00:00<00:45, 49.31it/s]
  1%|▏         | 32/2248 [00:00<00:43, 51.28it/s]
  2%|▏         | 38/2248 [00:00<01:01, 35.85it/s]
  2%|▏         | 43/2248 [00:01<01:12, 30.38it/s]
  2%|▏         | 47/2248 [00:01<01:20, 27.20it/s]
  2%|▏         | 51/2248 [00:01<01:19, 27.79it/s]
  2%|▏         | 55/2248 [00:01<01:30, 24.24it/s]
  3%|▎         | 58/2248 [00:01<01:33, 23.31it/s]
  3%|▎         | 62/2248 [00:02<01:30, 24.12it/s]
  3%|▎         | 65/2248 [00:02<01:33, 23.31it/s]
  3%|▎         | 70/2248 [00:02<01:16, 28.39it/s]
  3%|▎         | 74/2248 [00:02<01:18, 27.67it/s]
  3%|▎         | 77/2248 [00:02<02:12, 16.44it/s]
  4%|▎         | 80/2248 [00:03<02:28, 14.64it/s]
  4%|▎         | 82/2248 [00:03<02:55, 12.32it/s]
  4%|▎         | 84/2248 [00:03<02:54, 12.43it/s]
  4%|▍         | 86/2248 [00:03<02:40, 13.48it/s]
  4%|▍         | 88/2248 [00:03<02:50, 12.67it/s]
  4%|▍         | 90/2248 [00:03<02:42, 13.24it/s]
  4%|▍         | 93/2248 [00:04<02:11, 16.44it/s]
  4%|▍         | 96/2248 [00:04<02:05, 17.12it/s]
  4%|▍         | 98/2248 [00:04<02:26, 14.65it/s]
  4%|▍         | 101/2248 [00:04<02:13, 16.13it/s]
  5%|▍         | 103/2248 [00:04<02:14, 16.00it/s]
  5%|▍         | 106/2248 [00:04<01:54, 18.65it/s]
  5%|▍         | 108/2248 [00:05<02:18, 15.45it/s]
  5%|▍         | 110/2248 [00:05<02:32, 14.02it/s]
  5%|▌         | 113/2248 [00:05<02:29, 14.29it/s]
  5%|▌         | 115/2248 [00:05<02:37, 13.58it/s]
  5%|▌         | 117/2248 [00:05<03:36,  9.86it/s]
  5%|▌         | 119/2248 [00:06<03:13, 11.01it/s]
  5%|▌         | 121/2248 [00:06<03:59,  8.89it/s]
  5%|▌         | 123/2248 [00:06<04:03,  8.71it/s]
  6%|▌         | 126/2248 [00:06<04:05,  8.65it/s]
  6%|▌         | 127/2248 [00:07<05:18,  6.65it/s]
  6%|▌         | 128/2248 [00:07<06:14,  5.66it/s]
  6%|▌         | 130/2248 [00:07<04:46,  7.40it/s]
  6%|▌         | 133/2248 [00:08<04:33,  7.73it/s]
  6%|▌         | 136/2248 [00:08<04:34,  7.70it/s]
  6%|▌         | 138/2248 [00:08<03:51,  9.13it/s]
  6%|▋         | 143/2248 [00:08<02:21, 14.86it/s]
  6%|▋         | 146/2248 [00:09<02:51, 12.29it/s]
  7%|▋         | 149/2248 [00:09<02:22, 14.77it/s]
  7%|▋         | 152/2248 [00:09<02:48, 12.43it/s]
  7%|▋         | 156/2248 [00:09<03:02, 11.47it/s]
  7%|▋         | 158/2248 [00:10<03:52,  9.00it/s]
  7%|▋         | 160/2248 [00:10<04:15,  8.16it/s]
  7%|▋         | 162/2248 [00:11<04:53,  7.10it/s]
  7%|▋         | 164/2248 [00:11<04:16,  8.11it/s]
  7%|▋         | 166/2248 [00:11<04:54,  7.07it/s]
  8%|▊         | 169/2248 [00:11<04:44,  7.30it/s]
  8%|▊         | 170/2248 [00:12<04:38,  7.46it/s]
  8%|▊         | 173/2248 [00:12<03:18, 10.47it/s]
  8%|▊         | 175/2248 [00:12<03:28,  9.95it/s]
  8%|▊         | 177/2248 [00:12<04:40,  7.38it/s]
  8%|▊         | 179/2248 [00:13<05:39,  6.09it/s]
  8%|▊         | 181/2248 [00:13<04:37,  7.46it/s]
  8%|▊         | 183/2248 [00:13<05:05,  6.77it/s]
  8%|▊         | 184/2248 [00:13<05:08,  6.70it/s]
  8%|▊         | 186/2248 [00:14<04:11,  8.18it/s]
  8%|▊         | 188/2248 [00:14<04:00,  8.57it/s]
  8%|▊         | 190/2248 [00:14<03:33,  9.65it/s]
  9%|▊         | 192/2248 [00:14<03:24, 10.07it/s]
  9%|▊         | 194/2248 [00:14<03:00, 11.38it/s]
  9%|▉         | 197/2248 [00:14<02:48, 12.15it/s]
  9%|▉         | 199/2248 [00:15<03:12, 10.62it/s]
  9%|▉         | 201/2248 [00:15<03:07, 10.94it/s]
  9%|▉         | 203/2248 [00:15<04:21,  7.81it/s]
  9%|▉         | 204/2248 [00:16<04:54,  6.94it/s]
  9%|▉         | 206/2248 [00:16<04:05,  8.31it/s]
  9%|▉         | 207/2248 [00:16<04:48,  7.08it/s]
  9%|▉         | 209/2248 [00:16<04:24,  7.72it/s]
  9%|▉         | 210/2248 [00:16<05:12,  6.52it/s]
  9%|▉         | 211/2248 [00:17<05:39,  6.00it/s]
  9%|▉         | 213/2248 [00:17<05:14,  6.47it/s]
 10%|▉         | 215/2248 [00:17<04:15,  7.96it/s]
 10%|▉         | 220/2248 [00:17<03:16, 10.32it/s]
 10%|▉         | 224/2248 [00:17<02:21, 14.26it/s]
 10%|█         | 227/2248 [00:18<02:00, 16.74it/s]
 10%|█         | 231/2248 [00:18<01:42, 19.61it/s]
 10%|█         | 236/2248 [00:18<01:19, 25.17it/s]
 11%|█         | 243/2248 [00:18<00:58, 34.45it/s]
 11%|█         | 250/2248 [00:18<00:48, 41.44it/s]
 11%|█▏        | 257/2248 [00:18<00:41, 47.80it/s]
 12%|█▏        | 264/2248 [00:18<00:37, 52.58it/s]
 12%|█▏        | 270/2248 [00:18<00:47, 41.37it/s]
 12%|█▏        | 275/2248 [00:19<01:02, 31.60it/s]
 12%|█▏        | 279/2248 [00:19<01:34, 20.88it/s]
 13%|█▎        | 283/2248 [00:20<02:14, 14.60it/s]
 13%|█▎        | 286/2248 [00:20<02:09, 15.20it/s]
 13%|█▎        | 289/2248 [00:20<02:00, 16.24it/s]
 13%|█▎        | 292/2248 [00:20<02:18, 14.17it/s]
 13%|█▎        | 294/2248 [00:21<02:33, 12.69it/s]
 13%|█▎        | 296/2248 [00:21<02:35, 12.52it/s]
 13%|█▎        | 298/2248 [00:21<02:32, 12.80it/s]
 13%|█▎        | 300/2248 [00:21<03:58,  8.17it/s]
 13%|█▎        | 302/2248 [00:22<03:56,  8.23it/s]
 14%|█▎        | 304/2248 [00:22<04:29,  7.21it/s]
 14%|█▎        | 306/2248 [00:22<03:41,  8.78it/s]
 14%|█▎        | 308/2248 [00:23<05:18,  6.10it/s]
 14%|█▎        | 309/2248 [00:23<05:35,  5.78it/s]
 14%|█▍        | 310/2248 [00:23<05:09,  6.25it/s]
 14%|█▍        | 313/2248 [00:23<04:09,  7.76it/s]
 14%|█▍        | 314/2248 [00:23<04:37,  6.97it/s]
 14%|█▍        | 315/2248 [00:24<05:03,  6.36it/s]
 14%|█▍        | 317/2248 [00:24<03:49,  8.41it/s]
 14%|█▍        | 320/2248 [00:24<03:44,  8.61it/s]
 14%|█▍        | 322/2248 [00:25<04:46,  6.71it/s]
 14%|█▍        | 323/2248 [00:25<05:34,  5.75it/s]
 14%|█▍        | 325/2248 [00:25<05:44,  5.58it/s]
 15%|█▍        | 327/2248 [00:26<05:34,  5.74it/s]
 15%|█▍        | 329/2248 [00:26<04:55,  6.49it/s]
 15%|█▍        | 332/2248 [00:26<04:37,  6.91it/s]
 15%|█▍        | 334/2248 [00:26<03:56,  8.09it/s]
 15%|█▍        | 337/2248 [00:26<03:01, 10.53it/s]
 15%|█▌        | 339/2248 [00:27<02:42, 11.74it/s]
 15%|█▌        | 341/2248 [00:27<02:25, 13.09it/s]
 15%|█▌        | 343/2248 [00:27<02:50, 11.17it/s]
 15%|█▌        | 345/2248 [00:27<03:54,  8.11it/s]
 15%|█▌        | 347/2248 [00:28<04:11,  7.57it/s]
 15%|█▌        | 348/2248 [00:28<04:29,  7.05it/s]
 16%|█▌        | 349/2248 [00:28<04:40,  6.77it/s]
 16%|█▌        | 350/2248 [00:28<04:50,  6.54it/s]
 16%|█▌        | 352/2248 [00:28<03:47,  8.33it/s]
 16%|█▌        | 353/2248 [00:29<04:31,  6.98it/s]
 16%|█▌        | 355/2248 [00:29<03:42,  8.52it/s]
 16%|█▌        | 356/2248 [00:29<04:47,  6.58it/s]
 16%|█▌        | 358/2248 [00:29<03:34,  8.79it/s]
 16%|█▌        | 362/2248 [00:29<03:22,  9.32it/s]
 16%|█▌        | 364/2248 [00:30<03:47,  8.27it/s]
 16%|█▋        | 366/2248 [00:30<03:10,  9.86it/s]
 16%|█▋        | 368/2248 [00:30<03:46,  8.30it/s]
 17%|█▋        | 371/2248 [00:31<03:47,  8.24it/s]
 17%|█▋        | 373/2248 [00:31<03:14,  9.63it/s]
 17%|█▋        | 379/2248 [00:31<01:49, 17.10it/s]
 17%|█▋        | 385/2248 [00:31<01:35, 19.44it/s]
 17%|█▋        | 388/2248 [00:31<02:13, 13.94it/s]
 17%|█▋        | 390/2248 [00:32<02:31, 12.24it/s]
 17%|█▋        | 392/2248 [00:32<03:11,  9.69it/s]
 18%|█▊        | 394/2248 [00:33<04:29,  6.88it/s]
 18%|█▊        | 395/2248 [00:33<04:27,  6.94it/s]
 18%|█▊        | 397/2248 [00:33<03:47,  8.12it/s]
 18%|█▊        | 400/2248 [00:33<02:54, 10.59it/s]
 18%|█▊        | 403/2248 [00:33<02:22, 12.95it/s]
 18%|█▊        | 407/2248 [00:33<01:48, 16.94it/s]
 18%|█▊        | 411/2248 [00:33<01:27, 21.11it/s]
 19%|█▊        | 417/2248 [00:34<01:05, 28.11it/s]
 19%|█▉        | 423/2248 [00:34<00:53, 34.34it/s]
 19%|█▉        | 427/2248 [00:34<01:06, 27.34it/s]
 19%|█▉        | 433/2248 [00:34<00:55, 32.82it/s]
 19%|█▉        | 437/2248 [00:35<01:59, 15.18it/s]
 20%|█▉        | 440/2248 [00:35<02:28, 12.14it/s]
 20%|█▉        | 443/2248 [00:36<02:45, 10.92it/s]
 20%|█▉        | 446/2248 [00:36<02:55, 10.24it/s]
 20%|█▉        | 449/2248 [00:36<02:30, 11.98it/s]
 20%|██        | 455/2248 [00:36<01:38, 18.23it/s]
 20%|██        | 458/2248 [00:36<02:03, 14.48it/s]
 21%|██        | 461/2248 [00:37<01:48, 16.52it/s]
 21%|██        | 464/2248 [00:37<02:01, 14.70it/s]
 21%|██        | 468/2248 [00:37<01:40, 17.69it/s]
 21%|██        | 471/2248 [00:37<01:40, 17.66it/s]
 21%|██        | 474/2248 [00:38<02:21, 12.50it/s]
 21%|██        | 476/2248 [00:38<02:57, 10.00it/s]
 21%|██▏       | 479/2248 [00:38<03:17,  8.96it/s]
 21%|██▏       | 481/2248 [00:39<04:20,  6.78it/s]
 21%|██▏       | 483/2248 [00:39<04:07,  7.12it/s]
 22%|██▏       | 485/2248 [00:39<03:28,  8.44it/s]
 22%|██▏       | 488/2248 [00:39<02:38, 11.10it/s]
 22%|██▏       | 494/2248 [00:39<01:36, 18.19it/s]
 22%|██▏       | 498/2248 [00:40<01:53, 15.40it/s]
 22%|██▏       | 501/2248 [00:40<02:27, 11.85it/s]
 23%|██▎       | 506/2248 [00:40<02:02, 14.17it/s]
 23%|██▎       | 508/2248 [00:41<02:06, 13.74it/s]
 23%|██▎       | 510/2248 [00:41<02:06, 13.73it/s]
 23%|██▎       | 513/2248 [00:41<01:51, 15.60it/s]
 23%|██▎       | 515/2248 [00:41<02:44, 10.56it/s]
 23%|██▎       | 519/2248 [00:41<01:57, 14.67it/s]
 23%|██▎       | 525/2248 [00:41<01:17, 22.27it/s]
 24%|██▎       | 529/2248 [00:42<01:17, 22.32it/s]
 24%|██▎       | 533/2248 [00:42<01:16, 22.29it/s]
 24%|██▍       | 536/2248 [00:42<01:59, 14.28it/s]
 24%|██▍       | 539/2248 [00:42<01:46, 16.03it/s]
 24%|██▍       | 544/2248 [00:43<01:48, 15.65it/s]
 24%|██▍       | 547/2248 [00:43<01:49, 15.50it/s]
 25%|██▍       | 551/2248 [00:43<01:37, 17.32it/s]
 25%|██▍       | 554/2248 [00:43<01:32, 18.27it/s]
 25%|██▍       | 558/2248 [00:43<01:17, 21.70it/s]
 25%|██▌       | 564/2248 [00:44<01:06, 25.22it/s]
 25%|██▌       | 567/2248 [00:44<01:07, 24.81it/s]
 25%|██▌       | 571/2248 [00:44<01:15, 22.12it/s]
 26%|██▌       | 574/2248 [00:44<02:02, 13.70it/s]
 26%|██▌       | 576/2248 [00:45<02:00, 13.82it/s]
 26%|██▌       | 581/2248 [00:45<01:44, 16.01it/s]
 26%|██▌       | 583/2248 [00:45<02:12, 12.60it/s]
 26%|██▌       | 585/2248 [00:45<02:28, 11.19it/s]
 26%|██▌       | 587/2248 [00:46<02:58,  9.30it/s]
 26%|██▌       | 589/2248 [00:46<03:31,  7.84it/s]
 26%|██▋       | 592/2248 [00:46<03:23,  8.13it/s]
 26%|██▋       | 594/2248 [00:46<02:55,  9.41it/s]
 27%|██▋       | 599/2248 [00:47<01:49, 15.02it/s]
 27%|██▋       | 603/2248 [00:47<01:56, 14.06it/s]
 27%|██▋       | 605/2248 [00:48<03:13,  8.47it/s]
 27%|██▋       | 607/2248 [00:48<04:14,  6.44it/s]
 27%|██▋       | 609/2248 [00:48<04:21,  6.27it/s]
 27%|██▋       | 610/2248 [00:49<04:54,  5.56it/s]
 27%|██▋       | 612/2248 [00:49<04:01,  6.78it/s]
 27%|██▋       | 618/2248 [00:49<02:01, 13.39it/s]
 28%|██▊       | 624/2248 [00:49<01:19, 20.36it/s]
 28%|██▊       | 629/2248 [00:49<01:14, 21.65it/s]
 28%|██▊       | 633/2248 [00:49<01:05, 24.68it/s]
 28%|██▊       | 638/2248 [00:50<00:56, 28.71it/s]
 29%|██▊       | 644/2248 [00:50<00:45, 34.87it/s]
 29%|██▉       | 651/2248 [00:50<00:58, 27.24it/s]
 29%|██▉       | 655/2248 [00:50<01:29, 17.80it/s]
 29%|██▉       | 658/2248 [00:51<01:41, 15.67it/s]
 29%|██▉       | 661/2248 [00:51<02:09, 12.27it/s]
 29%|██▉       | 663/2248 [00:51<02:12, 11.94it/s]
 30%|██▉       | 668/2248 [00:51<01:35, 16.57it/s]
 30%|██▉       | 671/2248 [00:52<01:55, 13.66it/s]
 30%|██▉       | 673/2248 [00:52<02:09, 12.19it/s]
 30%|███       | 675/2248 [00:52<02:04, 12.60it/s]
 30%|███       | 677/2248 [00:52<01:58, 13.22it/s]
 30%|███       | 682/2248 [00:53<01:56, 13.47it/s]
 30%|███       | 684/2248 [00:53<02:31, 10.33it/s]
 31%|███       | 686/2248 [00:53<03:04,  8.47it/s]
 31%|███       | 688/2248 [00:54<03:23,  7.65it/s]
 31%|███       | 690/2248 [00:54<02:51,  9.07it/s]
 31%|███       | 692/2248 [00:55<04:20,  5.97it/s]
 31%|███       | 694/2248 [00:55<03:35,  7.20it/s]
 31%|███       | 696/2248 [00:55<03:49,  6.76it/s]
 31%|███       | 698/2248 [00:55<03:58,  6.49it/s]
 31%|███       | 700/2248 [00:56<03:30,  7.34it/s]
 31%|███       | 702/2248 [00:56<03:01,  8.53it/s]
 31%|███▏      | 704/2248 [00:56<02:57,  8.70it/s]
 31%|███▏      | 706/2248 [00:56<02:30, 10.26it/s]
 32%|███▏      | 710/2248 [00:56<01:45, 14.55it/s]
 32%|███▏      | 712/2248 [00:56<02:28, 10.36it/s]
 32%|███▏      | 714/2248 [00:57<02:21, 10.87it/s]
 32%|███▏      | 717/2248 [00:57<02:16, 11.23it/s]
 32%|███▏      | 719/2248 [00:57<02:06, 12.10it/s]
 32%|███▏      | 725/2248 [00:57<01:13, 20.66it/s]
 32%|███▏      | 728/2248 [00:57<01:39, 15.22it/s]
 33%|███▎      | 731/2248 [00:58<01:33, 16.28it/s]
 33%|███▎      | 735/2248 [00:58<01:48, 13.91it/s]
 33%|███▎      | 737/2248 [00:58<02:23, 10.56it/s]
 33%|███▎      | 739/2248 [00:59<03:07,  8.05it/s]
 33%|███▎      | 742/2248 [00:59<03:18,  7.59it/s]
 33%|███▎      | 743/2248 [01:00<03:48,  6.59it/s]
 33%|███▎      | 745/2248 [01:00<03:06,  8.07it/s]
 33%|███▎      | 748/2248 [01:00<02:19, 10.77it/s]
 33%|███▎      | 752/2248 [01:00<02:10, 11.48it/s]
 34%|███▎      | 754/2248 [01:00<02:09, 11.51it/s]
 34%|███▍      | 760/2248 [01:00<01:20, 18.60it/s]
 34%|███▍      | 766/2248 [01:00<00:58, 25.15it/s]
 34%|███▍      | 772/2248 [01:01<01:04, 22.77it/s]
 34%|███▍      | 775/2248 [01:01<01:30, 16.32it/s]
 35%|███▍      | 778/2248 [01:02<02:01, 12.05it/s]
 35%|███▍      | 780/2248 [01:02<02:19, 10.52it/s]
 35%|███▍      | 783/2248 [01:02<01:55, 12.69it/s]
 35%|███▌      | 788/2248 [01:02<01:21, 18.01it/s]
 35%|███▌      | 792/2248 [01:02<01:19, 18.34it/s]
 35%|███▌      | 795/2248 [01:03<01:24, 17.11it/s]
 35%|███▌      | 798/2248 [01:03<01:44, 13.85it/s]
 36%|███▌      | 803/2248 [01:03<01:32, 15.55it/s]
 36%|███▌      | 805/2248 [01:03<01:50, 13.08it/s]
 36%|███▌      | 808/2248 [01:04<01:40, 14.27it/s]
 36%|███▌      | 811/2248 [01:04<01:28, 16.33it/s]
 36%|███▋      | 817/2248 [01:04<01:12, 19.61it/s]
 37%|███▋      | 822/2248 [01:04<00:58, 24.44it/s]
 37%|███▋      | 826/2248 [01:04<00:52, 26.86it/s]
 37%|███▋      | 831/2248 [01:04<00:45, 31.02it/s]
 37%|███▋      | 838/2248 [01:04<00:36, 38.25it/s]
 38%|███▊      | 843/2248 [01:04<00:36, 38.90it/s]
 38%|███▊      | 848/2248 [01:05<00:36, 38.33it/s]
 38%|███▊      | 854/2248 [01:05<00:32, 43.02it/s]
 38%|███▊      | 861/2248 [01:05<00:29, 46.28it/s]
 39%|███▊      | 866/2248 [01:05<00:44, 31.27it/s]
 39%|███▊      | 870/2248 [01:06<01:21, 16.95it/s]
 39%|███▉      | 873/2248 [01:06<01:22, 16.70it/s]
 39%|███▉      | 876/2248 [01:06<01:18, 17.42it/s]
 39%|███▉      | 879/2248 [01:06<01:43, 13.28it/s]
 39%|███▉      | 884/2248 [01:07<01:16, 17.86it/s]
 39%|███▉      | 887/2248 [01:07<01:35, 14.30it/s]
 40%|███▉      | 890/2248 [01:07<01:29, 15.16it/s]
 40%|███▉      | 893/2248 [01:07<01:33, 14.52it/s]
 40%|███▉      | 895/2248 [01:08<01:58, 11.42it/s]
 40%|███▉      | 897/2248 [01:08<01:47, 12.58it/s]
 40%|████      | 900/2248 [01:08<01:32, 14.54it/s]
 40%|████      | 902/2248 [01:08<01:37, 13.77it/s]
 40%|████      | 904/2248 [01:08<02:09, 10.39it/s]
 40%|████      | 906/2248 [01:09<02:38,  8.49it/s]
 40%|████      | 908/2248 [01:09<03:11,  7.00it/s]
 40%|████      | 909/2248 [01:09<03:24,  6.55it/s]
 40%|████      | 910/2248 [01:10<03:35,  6.20it/s]
 41%|████      | 911/2248 [01:10<04:25,  5.03it/s]
 41%|████      | 912/2248 [01:10<04:47,  4.64it/s]
 41%|████      | 913/2248 [01:10<05:02,  4.41it/s]
 41%|████      | 914/2248 [01:11<04:43,  4.70it/s]
 41%|████      | 916/2248 [01:11<04:14,  5.24it/s]
 41%|████      | 918/2248 [01:11<03:02,  7.28it/s]
 41%|████      | 919/2248 [01:11<03:30,  6.32it/s]
 41%|████      | 920/2248 [01:12<03:48,  5.81it/s]
 41%|████      | 921/2248 [01:12<03:25,  6.45it/s]
 41%|████      | 923/2248 [01:12<02:28,  8.90it/s]
 41%|████      | 925/2248 [01:12<02:04, 10.59it/s]
 41%|████      | 927/2248 [01:12<02:46,  7.94it/s]
 41%|████▏     | 929/2248 [01:12<02:14,  9.82it/s]
 42%|████▏     | 934/2248 [01:13<01:53, 11.57it/s]
 42%|████▏     | 936/2248 [01:13<02:11, 10.00it/s]
 42%|████▏     | 938/2248 [01:13<02:01, 10.77it/s]
 42%|████▏     | 940/2248 [01:13<01:54, 11.40it/s]
 42%|████▏     | 943/2248 [01:14<01:52, 11.64it/s]
 42%|████▏     | 945/2248 [01:14<01:47, 12.13it/s]
 42%|████▏     | 948/2248 [01:14<01:37, 13.34it/s]
 42%|████▏     | 950/2248 [01:14<01:33, 13.86it/s]
 42%|████▏     | 952/2248 [01:14<02:21,  9.18it/s]
 42%|████▏     | 954/2248 [01:15<02:06, 10.26it/s]
 43%|████▎     | 956/2248 [01:15<03:01,  7.14it/s]
 43%|████▎     | 958/2248 [01:15<03:07,  6.88it/s]
 43%|████▎     | 960/2248 [01:16<03:18,  6.50it/s]
 43%|████▎     | 961/2248 [01:16<03:49,  5.61it/s]
 43%|████▎     | 962/2248 [01:16<04:18,  4.97it/s]
 43%|████▎     | 964/2248 [01:16<03:32,  6.05it/s]
 43%|████▎     | 966/2248 [01:17<03:28,  6.15it/s]
 43%|████▎     | 969/2248 [01:17<03:07,  6.83it/s]
 43%|████▎     | 970/2248 [01:17<03:46,  5.64it/s]
 43%|████▎     | 971/2248 [01:18<03:28,  6.12it/s]
 43%|████▎     | 976/2248 [01:18<02:21,  8.99it/s]
 44%|████▎     | 979/2248 [01:18<01:49, 11.57it/s]
 44%|████▎     | 981/2248 [01:18<02:11,  9.65it/s]
 44%|████▎     | 983/2248 [01:19<02:03, 10.27it/s]
 44%|████▍     | 985/2248 [01:19<02:25,  8.66it/s]
 44%|████▍     | 987/2248 [01:19<02:53,  7.27it/s]
 44%|████▍     | 989/2248 [01:19<02:35,  8.08it/s]
 44%|████▍     | 991/2248 [01:20<02:12,  9.50it/s]
 44%|████▍     | 996/2248 [01:20<01:18, 16.04it/s]
 44%|████▍     | 999/2248 [01:20<01:34, 13.23it/s]
 45%|████▍     | 1001/2248 [01:20<01:35, 13.04it/s]
 45%|████▍     | 1003/2248 [01:20<01:45, 11.78it/s]
 45%|████▍     | 1005/2248 [01:21<02:21,  8.78it/s]
 45%|████▍     | 1007/2248 [01:21<02:51,  7.23it/s]
 45%|████▍     | 1008/2248 [01:21<02:46,  7.44it/s]
 45%|████▍     | 1009/2248 [01:21<02:47,  7.41it/s]
 45%|████▍     | 1011/2248 [01:22<02:20,  8.82it/s]
 45%|████▌     | 1013/2248 [01:22<01:59, 10.37it/s]
 45%|████▌     | 1016/2248 [01:22<01:30, 13.57it/s]
 45%|████▌     | 1021/2248 [01:22<01:07, 18.09it/s]
 46%|████▌     | 1023/2248 [01:22<01:07, 18.27it/s]
 46%|████▌     | 1025/2248 [01:22<01:06, 18.33it/s]
 46%|████▌     | 1030/2248 [01:22<01:05, 18.56it/s]
 46%|████▌     | 1032/2248 [01:23<01:06, 18.38it/s]
 46%|████▌     | 1034/2248 [01:23<01:07, 18.00it/s]
 46%|████▌     | 1037/2248 [01:23<01:01, 19.59it/s]
 46%|████▋     | 1040/2248 [01:23<01:01, 19.54it/s]
 46%|████▋     | 1043/2248 [01:23<00:58, 20.45it/s]
 47%|████▋     | 1049/2248 [01:23<00:40, 29.64it/s]
 47%|████▋     | 1054/2248 [01:24<00:52, 22.59it/s]
 47%|████▋     | 1057/2248 [01:24<01:17, 15.39it/s]
 47%|████▋     | 1060/2248 [01:24<01:17, 15.29it/s]
 47%|████▋     | 1065/2248 [01:24<00:57, 20.42it/s]
 48%|████▊     | 1068/2248 [01:25<01:24, 13.95it/s]
 48%|████▊     | 1071/2248 [01:25<01:40, 11.73it/s]
 48%|████▊     | 1074/2248 [01:25<01:24, 13.92it/s]
 48%|████▊     | 1079/2248 [01:25<01:06, 17.53it/s]
 48%|████▊     | 1082/2248 [01:25<01:01, 19.09it/s]
 48%|████▊     | 1087/2248 [01:26<01:05, 17.63it/s]
 48%|████▊     | 1090/2248 [01:26<01:28, 13.07it/s]
 49%|████▊     | 1092/2248 [01:26<01:24, 13.63it/s]
 49%|████▊     | 1094/2248 [01:27<01:49, 10.56it/s]
 49%|████▉     | 1097/2248 [01:27<01:27, 13.20it/s]
 49%|████▉     | 1103/2248 [01:27<00:55, 20.56it/s]
 49%|████▉     | 1109/2248 [01:27<00:41, 27.60it/s]
 50%|████▉     | 1113/2248 [01:27<00:42, 26.97it/s]
 50%|████▉     | 1120/2248 [01:27<00:31, 35.83it/s]
 50%|█████     | 1126/2248 [01:27<00:27, 40.36it/s]
 50%|█████     | 1132/2248 [01:27<00:25, 43.48it/s]
 51%|█████     | 1139/2248 [01:28<00:22, 48.84it/s]
 51%|█████     | 1145/2248 [01:28<00:50, 21.91it/s]
 51%|█████     | 1149/2248 [01:29<01:11, 15.29it/s]
 51%|█████▏    | 1153/2248 [01:29<01:15, 14.46it/s]
 51%|█████▏    | 1156/2248 [01:29<01:12, 14.96it/s]
 52%|█████▏    | 1160/2248 [01:30<01:15, 14.33it/s]
 52%|█████▏    | 1162/2248 [01:30<01:14, 14.62it/s]
 52%|█████▏    | 1164/2248 [01:30<01:40, 10.83it/s]
 52%|█████▏    | 1166/2248 [01:30<01:32, 11.68it/s]
 52%|█████▏    | 1170/2248 [01:31<01:36, 11.15it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 299.37it/s]

[[np.int64(0), False, 7], [np.int64(1), False, 11], [np.int64(2), False, 9], [np.int64(3), False, 4], [np.int64(4), False, 8], [np.int64(5), False, 0], [np.int64(6), False, 0], [np.int64(8), False, 1], [np.int64(9), False, 11], [np.int64(10), False, 13], [np.int64(12), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2215, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [13:21<43:55, 53.78s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [13:21<30:09, 37.69s/it]

tensor(12.1083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2550, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2861, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [13:22<14:12, 18.53s/it]

tensor(12.1073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2954, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3098, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [13:22<06:42,  9.15s/it]

tensor(12.1057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3251, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3305, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [13:22<03:10,  4.55s/it]

tensor(12.1028, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3344, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3379, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [13:22<01:31,  2.29s/it]

tensor(12.0984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3470, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3562, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [13:23<00:45,  1.19s/it]

tensor(12.0952, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0939, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3658, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [13:23<00:23,  1.55it/s]

tensor(12.0928, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3541, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3586, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [13:23<00:12,  2.63it/s]

tensor(12.0906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3734, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [13:23<00:08,  3.95it/s]

tensor(12.0889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3792, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3826, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [13:24<00:05,  5.22it/s]

tensor(12.0869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3853, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3929, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [13:24<00:04,  6.26it/s]

tensor(12.0846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4023, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4110, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [13:24<00:03,  7.11it/s]

tensor(12.0822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4156, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4234, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [13:24<00:03,  7.43it/s]

tensor(12.0797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4349, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4379, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [13:25<00:02,  7.51it/s]

tensor(12.0775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4408, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4436, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [13:25<00:02,  7.49it/s]

tensor(12.0753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4459, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4323, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [13:25<00:02,  7.65it/s]

tensor(12.0730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4348, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4394, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [13:25<00:02,  7.75it/s]

tensor(12.0709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4446, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [13:26<00:01,  7.69it/s]

tensor(12.0688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4495, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [13:26<00:01,  7.65it/s]

tensor(12.0669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4513, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4524, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [13:26<00:01,  7.61it/s]

tensor(12.0650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4535, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [13:26<00:01,  7.70it/s]

tensor(12.0636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4539, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4570, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [13:27<00:00,  7.76it/s]

tensor(12.0621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4579, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4593, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [13:27<00:00,  7.66it/s]

tensor(12.0606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4595, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4619, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [13:27<00:00,  7.56it/s]

tensor(12.0589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4656, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [13:27<00:00,  2.69s/it]

tensor(12.0574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4648, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.003326416015625
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 0
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.352017873965
NMI         : 0.475134628466
Runtime     : 828.90 sec
Evidence    : /kaggle/working/PRAGA_baseline/smoke_final/S2E18_seed0

,dataset,seed,n_spots,target_K,predicted_K,ARI,NMI,runtime_sec
0,HLN-D1,0,3359,11,11,0.193806,0.298272,23.602796
1,S2-E15,0,1939,15,15,0.440489,0.601843,764.021488
2,S2-E18,0,2248,16,16,0.352018,0.475135,828.896516

PASS: remaining three smoke runs completed.

### Cell 11 — Run 5 datasets × 10 seeds with resume

In [62]:
FORMAL_SEEDS = list(
    range(10)
)


print("=" * 110)
print("PRAGA FORMAL BENCHMARK")
print("=" * 110)

print(
    "Datasets:",
    DATASET_ORDER
)

print(
    "Seeds:",
    FORMAL_SEEDS
)

print(
    "Total expected runs:",
    len(DATASET_ORDER)
    *
    len(FORMAL_SEEDS)
)


all_results = []


for dataset_name in DATASET_ORDER:

    for seed in FORMAL_SEEDS:

        try:

            result = run_praga_once(
                dataset_name=
                    dataset_name,

                seed=
                    seed,

                output_root=
                    FORMAL_ROOT,

                overwrite=
                    False,
            )

            all_results.append(
                result
            )

        except Exception as e:

            print(
                "\n"
                + "!" * 110
            )

            print(
                f"FAILED: "
                f"{dataset_name} "
                f"seed={seed}"
            )

            print(
                repr(e)
            )

            print(
                "!" * 110
            )

            raise


formal_raw = pd.DataFrame(
    all_results
)


formal_raw = (
    formal_raw
    .sort_values(
        [
            "dataset",
            "seed",
        ]
    )
    .reset_index(
        drop=True
    )
)


RAW_CSV = (
    PRAGA_OUTPUT_ROOT
    / "PRAGA_5datasets_10seeds_RAW.csv"
)


formal_raw.to_csv(
    RAW_CSV,
    index=False,
)


print(
    "\nSaved:",
    RAW_CSV
)

print(
    "Completed runs:",
    len(formal_raw)
)


display(
    formal_raw[
        [
            "dataset",
            "seed",
            "ARI",
            "NMI",
            "runtime_sec",
        ]
    ]
)

==============================================================================================================
PRAGA FORMAL BENCHMARK
==============================================================================================================
Datasets: ['HLN-A1', 'HLN-D1', 'E18.5', 'S2-E15', 'S2-E18']
Seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Total expected runs: 50

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:06,  4.38it/s]

tensor(39.0317, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6541, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(38.1447, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8785, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.98it/s]

tensor(36.2384, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3714, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.75it/s]

tensor(33.2007, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1073, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.63it/s]

tensor(31.9106, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0620, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.57it/s]

tensor(28.3648, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2150, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.53it/s]

tensor(26.5782, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5473, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:09,  2.51it/s]

tensor(26.0451, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0411, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:03<00:08,  2.50it/s]

tensor(25.0519, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6813, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.49it/s]

tensor(24.3456, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4537, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:08,  2.48it/s]

tensor(23.8263, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3455, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.47it/s]

tensor(23.6276, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3454, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.47it/s]

tensor(23.2563, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4427, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:05<00:06,  2.46it/s]

tensor(22.8204, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6290, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.45it/s]

tensor(22.5279, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8945, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:06,  2.46it/s]

tensor(22.0555, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2324, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.44it/s]

tensor(21.8487, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6347, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.44it/s]

tensor(21.3554, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0964, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:07<00:04,  2.44it/s]

tensor(21.0851, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6121, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.43it/s]

tensor(21.0577, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1751, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:04,  2.43it/s]

tensor(20.8259, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7813, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.44it/s]

tensor(20.4192, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4279, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.43it/s]

tensor(20.3106, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1093, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:09<00:02,  2.41it/s]

tensor(20.2659, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8234, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.41it/s]

tensor(19.9426, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5668, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:10<00:02,  2.41it/s]

tensor(19.8098, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3356, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.42it/s]

tensor(19.7941, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1292, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.42it/s]

tensor(19.5553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9446, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:11<00:00,  2.41it/s]

tensor(19.4288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7799, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.43it/s]

tensor(19.3941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6335, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:12<00:00,  2.48it/s]

Model training finished!

Infer time:  0.0040853023529052734
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 0
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.268852424660
NMI         : 0.355541243196
Runtime     : 24.84 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed0

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=1
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:06,  4.28it/s]

tensor(39.7170, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6578, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.5860, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8818, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.03it/s]

tensor(39.4852, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3746, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.81it/s]

tensor(39.3285, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1097, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.73it/s]

tensor(38.9902, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0648, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.67it/s]

tensor(38.2404, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2174, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.64it/s]

tensor(36.5626, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5496, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.61it/s]

tensor(33.1927, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0435, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.59it/s]

tensor(31.3528, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6832, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.59it/s]

tensor(29.3158, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4555, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.58it/s]

tensor(27.2738, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3473, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.58it/s]

tensor(27.6858, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3468, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.56it/s]

tensor(26.2602, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4441, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.56it/s]

tensor(25.7262, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6300, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.56it/s]

tensor(24.4573, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8954, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.56it/s]

tensor(23.9244, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2321, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.56it/s]

tensor(23.6800, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6350, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.56it/s]

tensor(22.8921, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0960, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.55it/s]

tensor(22.6712, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6108, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.55it/s]

tensor(21.9038, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1738, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.55it/s]

tensor(21.6611, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7795, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.55it/s]

tensor(21.3379, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4254, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.54it/s]

tensor(20.9964, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1070, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.54it/s]

tensor(20.7939, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8209, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.54it/s]

tensor(20.4411, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5637, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.54it/s]

tensor(20.3605, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3324, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.53it/s]

tensor(20.0821, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1261, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.53it/s]

tensor(20.0905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9409, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.53it/s]

tensor(19.8106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7762, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.54it/s]

tensor(19.7577, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6296, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.58it/s]

Model training finished!

Infer time:  0.00267791748046875
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 1
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.266686393007
NMI         : 0.347508768241
Runtime     : 24.77 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed1

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=2
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.04it/s]

tensor(39.7342, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6533, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.7188, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8779, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.90it/s]

tensor(39.6276, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3712, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.74it/s]

tensor(39.4687, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1068, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.68it/s]

tensor(39.1394, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0620, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.64it/s]

tensor(38.3730, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2148, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.62it/s]

tensor(36.6737, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5472, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.60it/s]

tensor(33.9493, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0410, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.58it/s]

tensor(32.7769, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6810, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.58it/s]

tensor(28.4945, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4537, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.57it/s]

tensor(27.2777, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3458, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.58it/s]

tensor(26.2685, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3458, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.57it/s]

tensor(26.2286, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4432, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.56it/s]

tensor(24.8020, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6289, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.56it/s]

tensor(24.3024, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8944, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.56it/s]

tensor(23.6209, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2318, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.54it/s]

tensor(23.2200, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6347, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.54it/s]

tensor(22.9777, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0964, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.53it/s]

tensor(22.5495, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6115, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.54it/s]

tensor(22.2863, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1743, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.53it/s]

tensor(21.6561, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7810, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.51it/s]

tensor(21.6465, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4276, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.49it/s]

tensor(21.2219, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1087, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.50it/s]

tensor(21.1264, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8223, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.49it/s]

tensor(20.9484, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5657, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:02,  2.49it/s]

tensor(20.6555, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3346, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.49it/s]

tensor(20.6463, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1282, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.51it/s]

tensor(20.3236, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9434, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.51it/s]

tensor(20.2522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7783, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.51it/s]

tensor(20.1112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6317, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.56it/s]

Model training finished!

Infer time:  0.002271413803100586
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 2
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.260934130352
NMI         : 0.337296494729
Runtime     : 27.91 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed2

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=3
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:06,  4.18it/s]

tensor(42.7227, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6548, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(34.6465, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8790, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.02it/s]

tensor(31.4029, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3721, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.77it/s]

tensor(28.9275, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1078, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.67it/s]

tensor(27.1889, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0626, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.61it/s]

tensor(26.0961, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2158, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.57it/s]

tensor(25.9382, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5479, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:09,  2.55it/s]

tensor(26.0400, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0418, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:03<00:08,  2.53it/s]

tensor(24.7678, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6817, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.52it/s]

tensor(23.9831, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4544, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.51it/s]

tensor(23.8723, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3463, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.50it/s]

tensor(23.7762, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3459, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.49it/s]

tensor(23.6696, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4435, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:05<00:06,  2.48it/s]

tensor(22.6099, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6294, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.47it/s]

tensor(21.9582, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8951, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:06,  2.47it/s]

tensor(22.1300, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2323, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.46it/s]

tensor(23.6664, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6355, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.44it/s]

tensor(32.6571, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0969, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:07<00:04,  2.44it/s]

tensor(24.5237, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6121, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.44it/s]

tensor(33.4350, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1750, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:04,  2.43it/s]

tensor(31.1323, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7805, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.42it/s]

tensor(33.4958, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4268, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.42it/s]

tensor(36.0241, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1076, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:09<00:02,  2.41it/s]

tensor(34.9722, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8209, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.41it/s]

tensor(27.9401, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5637, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:10<00:02,  2.40it/s]

tensor(26.6010, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3321, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.41it/s]

tensor(26.1936, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1252, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.40it/s]

tensor(27.4129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9399, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:11<00:00,  2.38it/s]

tensor(50.7598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7751, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.38it/s]

tensor(45.7750, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6277, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:12<00:00,  2.48it/s]

Model training finished!

Infer time:  0.0028946399688720703
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 3
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.222458815542
NMI         : 0.303297613912
Runtime     : 26.17 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed3

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=4
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:06,  4.29it/s]

tensor(39.6205, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6508, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.1821, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8758, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.97it/s]

tensor(38.3191, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3688, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.76it/s]

tensor(36.9355, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1050, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.65it/s]

tensor(34.5684, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0600, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.60it/s]

tensor(31.2640, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2138, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.57it/s]

tensor(31.1031, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5460, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:09,  2.55it/s]

tensor(27.0767, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0398, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:03<00:08,  2.55it/s]

tensor(26.4656, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6800, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.53it/s]

tensor(26.1225, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4524, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.53it/s]

tensor(25.0409, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3448, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.52it/s]

tensor(24.9851, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3444, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.51it/s]

tensor(23.8906, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4419, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:05<00:06,  2.52it/s]

tensor(23.5721, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6273, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.52it/s]

tensor(22.9749, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8933, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.51it/s]

tensor(22.6200, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2307, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.51it/s]

tensor(22.2593, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6335, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.51it/s]

tensor(21.7903, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0949, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:07<00:04,  2.50it/s]

tensor(21.4607, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6102, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.50it/s]

tensor(21.0945, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1730, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:04,  2.49it/s]

tensor(20.9305, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7797, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.50it/s]

tensor(20.8031, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4259, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.49it/s]

tensor(20.5071, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1073, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:09<00:02,  2.48it/s]

tensor(20.5941, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8213, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.48it/s]

tensor(20.2594, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5645, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:02,  2.48it/s]

tensor(20.2698, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3336, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.47it/s]

tensor(20.0462, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1275, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.48it/s]

tensor(19.8739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9425, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:11<00:00,  2.48it/s]

tensor(19.8393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7777, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.49it/s]

tensor(19.6341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6312, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.53it/s]

Model training finished!

Infer time:  0.0025277137756347656
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 4
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.270035404608
NMI         : 0.349796783162
Runtime     : 24.26 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed4

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=5
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  3.96it/s]

tensor(39.9658, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6550, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.6317, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8793, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.04it/s]

tensor(38.9524, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3725, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.82it/s]

tensor(38.0585, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1081, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.73it/s]

tensor(36.8323, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0631, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.67it/s]

tensor(34.9710, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2160, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.64it/s]

tensor(32.2488, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5485, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.63it/s]

tensor(30.1455, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0427, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.61it/s]

tensor(31.1804, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6824, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.59it/s]

tensor(27.4530, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4541, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.58it/s]

tensor(27.4021, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3456, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.58it/s]

tensor(27.9680, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3449, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.57it/s]

tensor(26.9784, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4424, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.57it/s]

tensor(26.2516, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6280, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.56it/s]

tensor(25.6255, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8932, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.57it/s]

tensor(24.1399, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2301, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.57it/s]

tensor(24.1434, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6327, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.58it/s]

tensor(23.5286, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0938, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.58it/s]

tensor(23.5675, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6087, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.57it/s]

tensor(22.4871, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1722, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.56it/s]

tensor(22.3892, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7783, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.56it/s]

tensor(21.9699, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4243, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.55it/s]

tensor(22.0523, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1057, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.55it/s]

tensor(21.5543, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8193, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.55it/s]

tensor(21.4018, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5626, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.55it/s]

tensor(21.0095, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3319, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.57it/s]

tensor(20.7565, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1253, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.56it/s]

tensor(20.5621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9409, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.55it/s]

tensor(20.2430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7760, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.54it/s]

tensor(20.1751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6292, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.60it/s]

Model training finished!

Infer time:  0.0027823448181152344
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 5
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.253819612476
NMI         : 0.345298698657
Runtime     : 24.76 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed5

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=6
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.13it/s]

tensor(40.0175, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6532, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.8051, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8778, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.91it/s]

tensor(39.5601, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3712, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.72it/s]

tensor(39.3235, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1068, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.64it/s]

tensor(38.7001, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0620, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.59it/s]

tensor(36.9233, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2149, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.57it/s]

tensor(33.6239, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5475, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:09,  2.55it/s]

tensor(33.4766, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0412, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:03<00:08,  2.53it/s]

tensor(28.4331, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6814, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.53it/s]

tensor(27.8616, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4540, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.51it/s]

tensor(27.0574, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3459, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.50it/s]

tensor(26.5060, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3457, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.50it/s]

tensor(24.9843, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4435, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:05<00:06,  2.49it/s]

tensor(24.3364, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6295, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.48it/s]

tensor(23.6961, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8948, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:06,  2.48it/s]

tensor(23.2899, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2322, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.47it/s]

tensor(22.6457, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6349, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.47it/s]

tensor(22.1972, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0969, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:07<00:04,  2.47it/s]

tensor(21.7872, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6116, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.47it/s]

tensor(21.6504, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1748, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:04,  2.47it/s]

tensor(21.0962, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7812, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.46it/s]

tensor(20.9481, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4277, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.46it/s]

tensor(20.6538, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1094, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:09<00:02,  2.46it/s]

tensor(20.4486, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8230, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.45it/s]

tensor(20.3845, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5664, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:02,  2.45it/s]

tensor(20.1501, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3352, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.45it/s]

tensor(20.0420, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1290, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.45it/s]

tensor(19.8984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9436, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:11<00:00,  2.44it/s]

tensor(19.7154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7791, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.44it/s]

tensor(19.6595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6326, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.50it/s]

Model training finished!

Infer time:  0.0026378631591796875
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 6
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.266413612853
NMI         : 0.349928186240
Runtime     : 27.07 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed6

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=7
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:06,  4.28it/s]

tensor(40.0449, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6559, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.5994, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8801, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.98it/s]

tensor(38.8149, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3730, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.77it/s]

tensor(37.6633, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1087, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.67it/s]

tensor(35.4239, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0635, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.62it/s]

tensor(32.2867, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2166, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.59it/s]

tensor(32.6291, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5487, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.57it/s]

tensor(27.0890, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0424, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:03<00:08,  2.55it/s]

tensor(27.3837, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6824, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.55it/s]

tensor(26.3153, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4549, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.54it/s]

tensor(26.0566, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3466, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.53it/s]

tensor(24.5901, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3464, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.52it/s]

tensor(24.2841, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4440, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.51it/s]

tensor(23.9615, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6302, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.51it/s]

tensor(22.7926, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8955, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.51it/s]

tensor(22.7960, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2332, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.50it/s]

tensor(22.4232, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6360, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.50it/s]

tensor(22.0928, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0976, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:07<00:04,  2.50it/s]

tensor(21.9526, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6131, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.49it/s]

tensor(21.3724, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1760, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:04,  2.49it/s]

tensor(21.1735, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7822, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.49it/s]

tensor(21.3219, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4286, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.49it/s]

tensor(21.1777, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1102, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:09<00:02,  2.49it/s]

tensor(21.0834, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8240, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.48it/s]

tensor(20.5180, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5675, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:02,  2.48it/s]

tensor(20.3472, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3366, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.48it/s]

tensor(20.4192, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1300, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.47it/s]

tensor(20.2814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9452, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:11<00:00,  2.47it/s]

tensor(20.1876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7803, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.47it/s]

tensor(19.9188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6341, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.53it/s]

Model training finished!

Infer time:  0.0025835037231445312
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 7
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.265952589622
NMI         : 0.348738499337
Runtime     : 27.08 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed7

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=8
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:06,  4.23it/s]

tensor(39.9824, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6560, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(38.1198, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8803, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.00it/s]

tensor(35.0724, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3732, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.79it/s]

tensor(31.3826, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1089, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.70it/s]

tensor(32.5111, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0636, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.65it/s]

tensor(27.6675, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2162, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.62it/s]

tensor(27.9915, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5484, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.60it/s]

tensor(26.1257, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0423, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.59it/s]

tensor(27.5961, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6822, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.57it/s]

tensor(27.6839, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4549, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.57it/s]

tensor(27.1397, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3468, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.56it/s]

tensor(26.7085, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3469, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.54it/s]

tensor(23.9164, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4443, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.54it/s]

tensor(24.1539, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6300, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.54it/s]

tensor(22.7581, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8954, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.54it/s]

tensor(23.6654, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2334, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.53it/s]

tensor(23.0184, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6358, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.53it/s]

tensor(22.5517, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0975, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.53it/s]

tensor(22.4516, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6127, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.54it/s]

tensor(21.2285, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1758, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.53it/s]

tensor(21.4896, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7821, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.53it/s]

tensor(20.8354, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4282, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.53it/s]

tensor(21.2627, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1097, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.53it/s]

tensor(20.9525, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8234, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.52it/s]

tensor(20.6331, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5666, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.51it/s]

tensor(20.9718, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3361, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.52it/s]

tensor(20.2495, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1292, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.49it/s]

tensor(20.1257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9443, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.50it/s]

tensor(20.1116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7798, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.49it/s]

tensor(19.5112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6333, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.56it/s]

Model training finished!

Infer time:  0.002606630325317383
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 8
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.235729591518
NMI         : 0.324173106984
Runtime     : 25.19 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed8

==============================================================================================================
PRAGA RUN | HLN-A1 | seed=9
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-A1: RNA feat = (3484, 30)
HLN-A1: ADT feat = (3484, 30)
HLN-A1: KNN_k=20, weights=[5, 5], init_k=10

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.11it/s]

tensor(39.7730, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.6576, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(39.5588, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.8819, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.89it/s]

tensor(39.1003, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.3747, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.72it/s]

tensor(38.4820, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.1104, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.64it/s]

tensor(37.6499, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.0650, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.61it/s]

tensor(36.4425, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.2176, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.60it/s]

tensor(34.6731, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.5496, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.58it/s]

tensor(32.5695, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.0433, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:03<00:08,  2.56it/s]

tensor(31.5734, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.6833, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:08,  2.55it/s]

tensor(30.6630, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.4553, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.55it/s]

tensor(27.8726, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.3467, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.54it/s]

tensor(27.6203, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.3459, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:07,  2.53it/s]

tensor(27.7908, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.4427, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:05<00:06,  2.53it/s]

tensor(27.1673, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.6281, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.53it/s]

tensor(26.6859, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8935, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.52it/s]

tensor(25.9649, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2304, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.52it/s]

tensor(24.8090, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6333, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.52it/s]

tensor(24.5073, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0938, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.51it/s]

tensor(23.9092, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6088, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.51it/s]

tensor(23.7164, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1722, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.51it/s]

tensor(22.7778, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7781, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:08<00:03,  2.50it/s]

tensor(22.5245, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4243, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.49it/s]

tensor(22.2259, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1060, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.49it/s]

tensor(22.1362, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8196, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.49it/s]

tensor(21.8954, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5628, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:02,  2.49it/s]

tensor(21.4650, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3324, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:10<00:01,  2.48it/s]

tensor(21.5201, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1258, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.48it/s]

tensor(21.2777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9412, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:11<00:00,  2.47it/s]

tensor(21.0914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7764, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.47it/s]

tensor(21.1172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6308, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.54it/s]

Model training finished!

Infer time:  0.002460002899169922
PCA20 shape : (3484, 20)
PCA20 finite: True
mclust K    : 10

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-A1
Seed        : 9
Spots       : 3484
Target K    : 10
Predicted K : 10
Embedding   : (3484, 64)
ARI         : 0.262256594140
NMI         : 0.339514918798
Runtime     : 28.53 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLNA1_seed9

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.01it/s]

tensor(30.5108, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3595, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.2576, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6144, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.09it/s]

tensor(29.7690, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1346, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.88it/s]

tensor(29.0379, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8959, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.77it/s]

tensor(28.0627, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8735, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.71it/s]

tensor(26.9493, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0476, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.68it/s]

tensor(26.1483, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.3990, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.66it/s]

tensor(25.6756, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9103, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.66it/s]

tensor(24.4851, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5662, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.64it/s]

tensor(23.5360, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3529, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.63it/s]

tensor(23.2360, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2578, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.63it/s]

tensor(22.8913, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2700, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.63it/s]

tensor(22.3685, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3781, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.63it/s]

tensor(21.9742, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5733, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.62it/s]

tensor(21.7442, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8480, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.61it/s]

tensor(21.4229, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1933, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.61it/s]

tensor(21.1886, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6030, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.60it/s]

tensor(21.0739, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0709, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.60it/s]

tensor(20.8809, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5915, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.60it/s]

tensor(20.6437, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1599, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.60it/s]

tensor(20.4846, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7711, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.60it/s]

tensor(20.2981, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4210, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.60it/s]

tensor(20.0774, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1064, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.59it/s]

tensor(19.9323, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8229, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.59it/s]

tensor(19.7950, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5684, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.59it/s]

tensor(19.6419, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3402, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.59it/s]

tensor(19.5331, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1351, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.58it/s]

tensor(19.4139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9516, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.58it/s]

tensor(19.2679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7872, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.58it/s]

tensor(19.1640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6412, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.63it/s]

Model training finished!

Infer time:  0.0023310184478759766
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 0
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.193806122448
NMI         : 0.298272318220
Runtime     : 24.55 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed0

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=1
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.12it/s]

tensor(30.7383, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3618, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.6804, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6162, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.04it/s]

tensor(30.6287, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1361, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.85it/s]

tensor(30.5576, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8972, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.75it/s]

tensor(30.4603, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8747, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.69it/s]

tensor(30.3225, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0483, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.67it/s]

tensor(30.1125, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.3996, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.65it/s]

tensor(29.7906, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9106, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.66it/s]

tensor(29.2948, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5669, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.64it/s]

tensor(28.5442, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3537, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.63it/s]

tensor(27.5031, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2587, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.63it/s]

tensor(26.4159, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2709, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.63it/s]

tensor(26.0546, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3788, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.62it/s]

tensor(25.9828, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5737, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.63it/s]

tensor(24.5649, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8480, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.63it/s]

tensor(23.7743, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1934, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.62it/s]

tensor(23.7594, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6033, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.61it/s]

tensor(23.6243, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0709, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.60it/s]

tensor(23.1612, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5916, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.60it/s]

tensor(22.6131, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1594, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.60it/s]

tensor(22.2419, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7709, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.60it/s]

tensor(21.8877, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4205, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.59it/s]

tensor(21.3873, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1056, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.60it/s]

tensor(21.0252, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8219, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.59it/s]

tensor(20.8266, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5674, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.59it/s]

tensor(20.6073, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3394, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.60it/s]

tensor(20.3453, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1342, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.59it/s]

tensor(20.1560, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9503, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.59it/s]

tensor(19.9907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7864, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.59it/s]

tensor(19.7378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6397, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.64it/s]

Model training finished!

Infer time:  0.0024123191833496094
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 1
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.211567286598
NMI         : 0.304277252281
Runtime     : 23.82 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed1

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=2
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  3.67it/s]

tensor(30.7441, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3644, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.7338, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6185, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.93it/s]

tensor(30.7037, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1384, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.81it/s]

tensor(30.6612, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8989, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.73it/s]

tensor(30.6027, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8766, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.70it/s]

tensor(30.5233, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0504, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.69it/s]

tensor(30.4083, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.4015, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.68it/s]

tensor(30.2329, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9124, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.68it/s]

tensor(29.9569, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5681, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.67it/s]

tensor(29.5208, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3544, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.67it/s]

tensor(28.8556, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2592, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.67it/s]

tensor(27.9227, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2714, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.67it/s]

tensor(26.8826, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3794, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.66it/s]

tensor(26.0956, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5745, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.66it/s]

tensor(25.2210, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8488, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.66it/s]

tensor(23.8817, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1941, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.67it/s]

tensor(23.1186, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6036, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.65it/s]

tensor(22.8092, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0719, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.64it/s]

tensor(22.4742, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5927, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.64it/s]

tensor(22.1149, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1602, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.64it/s]

tensor(21.7575, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7711, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.63it/s]

tensor(21.3877, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4209, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.62it/s]

tensor(21.1561, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1061, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.62it/s]

tensor(21.0472, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8228, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:08<00:02,  2.62it/s]

tensor(20.9126, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5681, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.63it/s]

tensor(20.7255, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3397, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.63it/s]

tensor(20.5467, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1351, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.63it/s]

tensor(20.3599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9512, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.63it/s]

tensor(20.1549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7869, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.63it/s]

tensor(19.9830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6407, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.66it/s]

Model training finished!

Infer time:  0.0024919509887695312
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 2
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.198649890007
NMI         : 0.307996197005
Runtime     : 26.02 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed2

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=3
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.11it/s]

tensor(32.2711, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3625, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(29.5162, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6166, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.06it/s]

tensor(27.6511, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1369, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.87it/s]

tensor(26.7177, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8976, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.79it/s]

tensor(25.4561, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8751, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.75it/s]

tensor(24.4682, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0488, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.73it/s]

tensor(23.8470, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.4000, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.69it/s]

tensor(23.2529, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9110, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.68it/s]

tensor(22.8545, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5666, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.68it/s]

tensor(22.7209, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3535, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.66it/s]

tensor(22.3021, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2586, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.66it/s]

tensor(21.8836, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2707, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.65it/s]

tensor(21.6263, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3787, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.64it/s]

tensor(21.3377, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5738, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.63it/s]

tensor(21.1366, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8482, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.63it/s]

tensor(20.9202, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1938, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.64it/s]

tensor(20.6686, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6033, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.64it/s]

tensor(20.5497, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0715, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.63it/s]

tensor(20.3907, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5924, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.63it/s]

tensor(20.2305, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1602, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.64it/s]

tensor(20.0897, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7714, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.62it/s]

tensor(19.8962, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4213, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.61it/s]

tensor(19.7672, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1068, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.61it/s]

tensor(19.6323, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8230, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:08<00:02,  2.60it/s]

tensor(19.5014, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5687, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.60it/s]

tensor(19.4122, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3403, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.60it/s]

tensor(19.2965, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1352, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.59it/s]

tensor(19.2097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9515, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.60it/s]

tensor(19.1189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7872, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.59it/s]

tensor(19.0113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6410, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.66it/s]

Model training finished!

Infer time:  0.0024483203887939453
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 3
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.165635819035
NMI         : 0.297201513648
Runtime     : 27.19 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed3

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=4
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.01it/s]

tensor(30.9195, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3623, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.7208, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6169, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.07it/s]

tensor(30.2874, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1367, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.86it/s]

tensor(29.7351, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8974, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.79it/s]

tensor(29.0719, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8750, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.73it/s]

tensor(28.2664, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0488, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.70it/s]

tensor(27.3082, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.4003, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.67it/s]

tensor(26.3363, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9114, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.64it/s]

tensor(25.7600, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5674, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.64it/s]

tensor(25.4986, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3542, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.63it/s]

tensor(24.6118, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2588, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.64it/s]

tensor(23.6745, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2708, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.63it/s]

tensor(23.2836, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3790, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.63it/s]

tensor(22.9953, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5739, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.62it/s]

tensor(22.5360, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8483, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.61it/s]

tensor(22.1053, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1939, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.61it/s]

tensor(21.9804, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6034, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.60it/s]

tensor(21.7305, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0709, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.59it/s]

tensor(21.2734, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5918, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.59it/s]

tensor(21.0783, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1600, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.60it/s]

tensor(20.9634, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7711, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.59it/s]

tensor(20.7357, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4209, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.60it/s]

tensor(20.5239, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1064, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.59it/s]

tensor(20.4087, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8231, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.59it/s]

tensor(20.1731, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5679, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.59it/s]

tensor(19.9128, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3395, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.59it/s]

tensor(19.7995, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1345, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.59it/s]

tensor(19.7014, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9513, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.58it/s]

tensor(19.5755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7870, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.57it/s]

tensor(19.4820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6403, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.63it/s]

Model training finished!

Infer time:  0.0025005340576171875
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 4
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.173935494738
NMI         : 0.298787376689
Runtime     : 24.71 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed4

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=5
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  3.98it/s]

tensor(30.9783, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3623, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.8217, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6163, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.07it/s]

tensor(30.4728, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1369, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.86it/s]

tensor(30.0412, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8973, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.77it/s]

tensor(29.5566, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8749, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.70it/s]

tensor(29.0013, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0487, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.67it/s]

tensor(28.3539, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.4000, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.64it/s]

tensor(27.6203, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9109, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.62it/s]

tensor(26.9159, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5668, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.63it/s]

tensor(26.4458, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3535, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.64it/s]

tensor(26.0952, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2583, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.63it/s]

tensor(25.4368, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2700, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.62it/s]

tensor(24.7289, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3782, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.63it/s]

tensor(24.3649, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5730, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.63it/s]

tensor(24.1886, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8473, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.63it/s]

tensor(23.9711, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1929, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.62it/s]

tensor(23.6627, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6022, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.61it/s]

tensor(23.3322, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0701, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.61it/s]

tensor(23.0438, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5905, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.60it/s]

tensor(22.7217, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1588, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.59it/s]

tensor(22.3147, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7697, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.58it/s]

tensor(21.9964, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4193, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.58it/s]

tensor(21.8095, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1041, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.59it/s]

tensor(21.6120, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8209, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.59it/s]

tensor(21.3370, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5660, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.59it/s]

tensor(21.0721, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3373, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.59it/s]

tensor(20.8716, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1326, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.58it/s]

tensor(20.6835, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9488, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.59it/s]

tensor(20.5180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7849, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.59it/s]

tensor(20.3882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6382, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.63it/s]

Model training finished!

Infer time:  0.0025434494018554688
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 5
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.186998325571
NMI         : 0.296371181981
Runtime     : 26.81 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed5

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=6
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.06it/s]

tensor(30.8647, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3592, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.8134, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6140, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.10it/s]

tensor(30.7329, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1343, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:00<00:09,  2.89it/s]

tensor(30.6431, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8953, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.81it/s]

tensor(30.5603, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8732, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.75it/s]

tensor(30.4574, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0469, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.74it/s]

tensor(30.2746, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.3987, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.72it/s]

tensor(29.9314, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9096, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.71it/s]

tensor(29.3380, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5658, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.70it/s]

tensor(28.4097, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3528, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.68it/s]

tensor(27.3071, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2577, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:03<00:07,  2.67it/s]

tensor(26.7438, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2697, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.67it/s]

tensor(26.4283, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3780, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.67it/s]

tensor(24.7953, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5734, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:05,  2.67it/s]

tensor(24.0014, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8471, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.67it/s]

tensor(23.8772, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1929, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.67it/s]

tensor(23.5108, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6026, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.66it/s]

tensor(22.9836, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0706, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.66it/s]

tensor(22.6582, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5916, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:06<00:04,  2.65it/s]

tensor(22.2116, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1595, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.65it/s]

tensor(21.5701, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7707, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.65it/s]

tensor(21.2258, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4206, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.63it/s]

tensor(21.0348, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1058, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.62it/s]

tensor(20.7625, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8223, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:08<00:02,  2.61it/s]

tensor(20.4689, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5680, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.61it/s]

tensor(20.2986, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3395, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.61it/s]

tensor(20.1437, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1347, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.61it/s]

tensor(19.9187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9509, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.61it/s]

tensor(19.7562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7868, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.61it/s]

tensor(19.6240, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6405, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.67it/s]

Model training finished!

Infer time:  0.002592325210571289
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 6
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.191968056833
NMI         : 0.295183893695
Runtime     : 24.52 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed6

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=7
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  4.04it/s]

tensor(30.9009, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3593, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.8310, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6141, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.04it/s]

tensor(30.6330, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1343, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.87it/s]

tensor(30.3936, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8954, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.77it/s]

tensor(30.1073, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8728, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.74it/s]

tensor(29.7004, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0471, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.68it/s]

tensor(29.0515, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.3985, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.66it/s]

tensor(28.0461, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9098, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.65it/s]

tensor(26.8578, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5659, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.65it/s]

tensor(26.2837, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3524, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.65it/s]

tensor(25.7225, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2575, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.64it/s]

tensor(23.9530, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2696, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.64it/s]

tensor(23.3193, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3778, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.65it/s]

tensor(23.2367, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5731, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.63it/s]

tensor(22.8626, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8473, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.62it/s]

tensor(22.3616, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1926, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.61it/s]

tensor(22.0050, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6024, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.60it/s]

tensor(21.5670, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0705, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.60it/s]

tensor(21.2534, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5911, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.60it/s]

tensor(21.1448, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1593, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.59it/s]

tensor(20.9639, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7706, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.60it/s]

tensor(20.7378, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4204, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.59it/s]

tensor(20.6250, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1057, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.60it/s]

tensor(20.4547, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8223, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.59it/s]

tensor(20.2389, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5677, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.59it/s]

tensor(20.1201, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3394, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.58it/s]

tensor(19.9885, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1343, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.58it/s]

tensor(19.8275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9509, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.58it/s]

tensor(19.7273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7864, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.58it/s]

tensor(19.6134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6405, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.64it/s]

Model training finished!

Infer time:  0.0022253990173339844
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 7
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.195814950271
NMI         : 0.308085526142
Runtime     : 24.74 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed7

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=8
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  3.64it/s]

tensor(30.9453, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3644, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.6172, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6184, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  2.97it/s]

tensor(29.9355, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1383, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:01<00:09,  2.80it/s]

tensor(29.0658, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8989, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.73it/s]

tensor(27.9643, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8763, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:09,  2.69it/s]

tensor(26.7573, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0497, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:09,  2.66it/s]

tensor(26.2641, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.4013, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.65it/s]

tensor(26.0958, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9121, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.65it/s]

tensor(24.4895, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5678, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.64it/s]

tensor(23.9347, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3543, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.63it/s]

tensor(23.7519, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2592, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:04<00:07,  2.61it/s]

tensor(23.2058, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2711, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.61it/s]

tensor(22.8317, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3792, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.60it/s]

tensor(22.8580, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5746, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:06,  2.60it/s]

tensor(22.1650, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8489, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.59it/s]

tensor(21.7660, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1941, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:06<00:05,  2.60it/s]

tensor(21.6632, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6038, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:05,  2.60it/s]

tensor(21.2963, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0720, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.60it/s]

tensor(21.0292, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5924, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:07<00:04,  2.59it/s]

tensor(21.0297, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1607, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.59it/s]

tensor(20.6887, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7720, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.59it/s]

tensor(20.5490, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4217, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:03,  2.59it/s]

tensor(20.4985, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1070, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.59it/s]

tensor(20.2687, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8239, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:09<00:02,  2.59it/s]

tensor(20.1772, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5692, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.59it/s]

tensor(20.0941, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3408, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.58it/s]

tensor(19.8649, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1357, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:10<00:01,  2.58it/s]

tensor(19.7855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9520, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.58it/s]

tensor(19.6747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7878, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:11<00:00,  2.59it/s]

tensor(19.5116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6416, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.62it/s]

Model training finished!

Infer time:  0.002457857131958008
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 8
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.175745566167
NMI         : 0.295863735715
Runtime     : 27.02 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed8

==============================================================================================================
PRAGA RUN | HLN-D1 | seed=9
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

HLN-D1: RNA feat = (3359, 30)
HLN-D1: ADT feat = (3359, 30)
HLN-D1: KNN_k=20, weights=[5, 5], init_k=11

  0%|          | 0/30 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  3%|▎         | 1/30 [00:00<00:07,  3.71it/s]

tensor(30.9305, device='cuda:0', grad_fn=<AddBackward0>) tensor(27.3618, device='cuda:0', grad_fn=<DivBackward0>) 0.0
tensor(30.8306, device='cuda:0', grad_fn=<AddBackward0>) tensor(24.6163, device='cuda:0', grad_fn=<DivBackward0>) 0.0

  7%|▋         | 2/30 [00:00<00:09,  3.07it/s]

tensor(30.5864, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.1363, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 10%|█         | 3/30 [00:00<00:09,  2.91it/s]

tensor(30.2692, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.8971, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 13%|█▎        | 4/30 [00:01<00:09,  2.83it/s]

tensor(29.8945, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.8745, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 17%|█▋        | 5/30 [00:01<00:08,  2.78it/s]

tensor(29.4545, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.0489, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 20%|██        | 6/30 [00:02<00:08,  2.73it/s]

tensor(28.9197, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.3998, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 23%|██▎       | 7/30 [00:02<00:08,  2.73it/s]

tensor(28.2648, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.9110, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 27%|██▋       | 8/30 [00:02<00:08,  2.72it/s]

tensor(27.5145, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.5668, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 30%|███       | 9/30 [00:03<00:07,  2.70it/s]

tensor(26.8377, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.3536, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 33%|███▎      | 10/30 [00:03<00:07,  2.71it/s]

tensor(26.4637, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.2585, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 37%|███▋      | 11/30 [00:03<00:07,  2.69it/s]

tensor(26.1224, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.2705, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 40%|████      | 12/30 [00:04<00:06,  2.69it/s]

tensor(25.3273, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3785, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 43%|████▎     | 13/30 [00:04<00:06,  2.69it/s]

tensor(24.6033, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5734, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 47%|████▋     | 14/30 [00:05<00:05,  2.67it/s]

tensor(24.2538, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8478, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 50%|█████     | 15/30 [00:05<00:05,  2.66it/s]

tensor(23.9777, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1931, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 53%|█████▎    | 16/30 [00:05<00:05,  2.66it/s]

tensor(23.6005, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6030, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 57%|█████▋    | 17/30 [00:06<00:04,  2.66it/s]

tensor(23.2366, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0708, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 60%|██████    | 18/30 [00:06<00:04,  2.66it/s]

tensor(22.9958, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5915, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 63%|██████▎   | 19/30 [00:06<00:04,  2.66it/s]

tensor(22.7036, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1598, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 67%|██████▋   | 20/30 [00:07<00:03,  2.73it/s]

tensor(22.3287, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7707, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 70%|███████   | 21/30 [00:07<00:03,  2.71it/s]

tensor(22.0854, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4203, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 73%|███████▎  | 22/30 [00:08<00:02,  2.68it/s]

tensor(21.9293, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.1055, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 77%|███████▋  | 23/30 [00:08<00:02,  2.65it/s]

tensor(21.7311, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8222, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 80%|████████  | 24/30 [00:08<00:02,  2.65it/s]

tensor(21.5064, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5673, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 83%|████████▎ | 25/30 [00:09<00:01,  2.65it/s]

tensor(21.3159, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3392, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 87%|████████▋ | 26/30 [00:09<00:01,  2.64it/s]

tensor(21.1090, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1341, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 90%|█████████ | 27/30 [00:09<00:01,  2.63it/s]

tensor(20.8751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9501, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 93%|█████████▎| 28/30 [00:10<00:00,  2.61it/s]

tensor(20.6886, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7865, device='cuda:0', grad_fn=<DivBackward0>) 0.0

 97%|█████████▋| 29/30 [00:10<00:00,  2.61it/s]

tensor(20.5223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6401, device='cuda:0', grad_fn=<DivBackward0>) 0.0

100%|██████████| 30/30 [00:11<00:00,  2.69it/s]

Model training finished!

Infer time:  0.002621889114379883
PCA20 shape : (3359, 20)
PCA20 finite: True
mclust K    : 11

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : HLN-D1
Seed        : 9
Spots       : 3359
Target K    : 11
Predicted K : 11
Embedding   : (3359, 64)
ARI         : 0.201763413717
NMI         : 0.310365857982
Runtime     : 24.57 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/HLND1_seed9

==============================================================================================================
PRAGA RUN | E18.5 | seed=0
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 1.976e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:34,  8.74it/s]

tensor(15.7772, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4763, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7879, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2245, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:33,  8.93it/s]

tensor(15.7387, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1938, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6769, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3630, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:31,  9.39it/s]

tensor(15.6187, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7125, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5643, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2240, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:30,  9.63it/s]

tensor(15.5135, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8822, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4745, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6723, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.74it/s]

tensor(15.4378, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5814, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4055, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5981, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:29,  9.79it/s]

tensor(15.3805, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7117, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3517, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9131, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:29,  9.83it/s]

tensor(15.3138, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1930, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2803, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5446, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:29,  9.64it/s]

tensor(15.2439, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9596, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2005, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4336, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:28,  9.84it/s]

tensor(15.1598, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9591, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1093, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5320, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0645, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1475, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:28,  9.89it/s]

tensor(15.0181, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8014, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9662, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4895, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9183, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2094, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:27,  9.88it/s]

tensor(14.8702, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9571, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8173, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7307, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:28,  9.70it/s]

tensor(14.7642, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5271, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7076, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3437, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:27,  9.87it/s]

tensor(14.6480, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1799, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5888, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5282, device='cuda:0', grad_fn=<AddBackward0>)

 10%|█         | 30/300 [00:03<00:27,  9.89it/s]

tensor(0.9006, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7824, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4091, device='cuda:0', grad_fn=<AddBackward0>)

 11%|█         | 32/300 [00:03<00:27,  9.87it/s]

tensor(0.6764, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5819, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:27,  9.84it/s]

tensor(14.2871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4975, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4227, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:26,  9.85it/s]

tensor(14.1559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3557, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2965, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.72it/s]

tensor(14.0217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2445, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1989, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:04<00:26,  9.86it/s]

tensor(13.8831, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1590, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7447, device='cuda:0', grad_fn=<AddBackward0>)

 14%|█▎        | 41/300 [00:04<00:26,  9.74it/s]

tensor(0.0950, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0714, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:26,  9.75it/s]

tensor(13.6111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0534, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5483, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0418, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:26,  9.49it/s]

tensor(13.4874, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:26,  9.68it/s]

tensor(13.3834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:25,  9.78it/s]

tensor(13.3058, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.62it/s]

tensor(13.1959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1615, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:24,  9.81it/s]

tensor(13.1257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0537, device='cuda:0', grad_fn=<AddBackward0>)

 19%|█▉        | 57/300 [00:05<00:24,  9.88it/s]

tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:06<00:24,  9.79it/s]

tensor(12.9963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:06<00:24,  9.87it/s]

tensor(12.9500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:24,  9.87it/s]

tensor(12.9062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:23,  9.86it/s]

tensor(12.8619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:24,  9.57it/s]

tensor(12.8171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:24,  9.43it/s]

tensor(12.7715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:23,  9.71it/s]

tensor(12.7279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6880, device='cuda:0', grad_fn=<AddBackward0>)

 24%|██▍       | 73/300 [00:07<00:23,  9.78it/s]

tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6690, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:22,  9.82it/s]

tensor(12.6506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6152, device='cuda:0', grad_fn=<AddBackward0>)

 26%|██▌       | 77/300 [00:07<00:22,  9.82it/s]

tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:22,  9.86it/s]

tensor(12.5809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5643, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:08<00:22,  9.64it/s]

tensor(12.5479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:22,  9.59it/s]

tensor(12.5172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5028, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:22,  9.69it/s]

tensor(12.4883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4740, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:21,  9.73it/s]

tensor(12.4600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:09<00:21,  9.61it/s]

tensor(12.4325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:09<00:21,  9.51it/s]

tensor(12.4055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:21,  9.56it/s]

tensor(12.3791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:21,  9.72it/s]

tensor(12.3540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:20,  9.72it/s]

tensor(12.3301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:10<00:21,  9.56it/s]

tensor(12.3071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.2960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.52it/s]

tensor(12.2852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([320,  78, 186, 148,  81, 102,  97,  67, 133, 340, 121, 180,  54, 222])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 4/2129 [00:00<00:56, 37.54it/s]
  1%|          | 11/2129 [00:00<00:38, 54.67it/s]
  1%|          | 17/2129 [00:00<00:37, 56.74it/s]
  1%|          | 23/2129 [00:00<01:18, 26.94it/s]
  1%|▏         | 28/2129 [00:00<01:09, 30.28it/s]
  2%|▏         | 35/2129 [00:00<00:58, 35.53it/s]
  2%|▏         | 40/2129 [00:01<00:57, 36.10it/s]
  2%|▏         | 45/2129 [00:01<01:29, 23.40it/s]
  2%|▏         | 49/2129 [00:01<01:20, 25.93it/s]
  3%|▎         | 54/2129 [00:01<01:42, 20.15it/s]
  3%|▎         | 58/2129 [00:02<01:33, 22.09it/s]
  3%|▎         | 65/2129 [00:02<02:09, 15.94it/s]
  3%|▎         | 68/2129 [00:02<02:00, 17.04it/s]
  3%|▎         | 73/2129 [00:03<03:05, 11.09it/s]
  4%|▎         | 76/2129 [00:03<02:41, 12.73it/s]
  4%|▍         | 80/2129 [00:04<02:36, 13.13it/s]
  4%|▍         | 82/2129 [00:04<02:28, 13.75it/s]
  4%|▍         | 85/2129 [00:04<02:08, 15.93it/s]
  4%|▍         | 91/2129 [00:04<01:28, 23.05it/s]
  5%|▍         | 96/2129 [00:04<01:12, 28.19it/s]
  5%|▍         | 101/2129 [00:04<01:16, 26.46it/s]
  5%|▍         | 105/2129 [00:05<02:21, 14.35it/s]
  5%|▌         | 108/2129 [00:05<02:11, 15.36it/s]
  5%|▌         | 115/2129 [00:05<01:28, 22.80it/s]
  6%|▌         | 120/2129 [00:05<01:18, 25.60it/s]
  6%|▌         | 125/2129 [00:06<01:45, 18.91it/s]
  6%|▌         | 128/2129 [00:06<01:39, 20.15it/s]
  6%|▌         | 132/2129 [00:06<02:00, 16.60it/s]
  6%|▋         | 135/2129 [00:06<01:50, 18.00it/s]
  7%|▋         | 143/2129 [00:06<01:12, 27.55it/s]
  7%|▋         | 150/2129 [00:06<00:56, 35.09it/s]
  7%|▋         | 157/2129 [00:07<01:05, 30.24it/s]
  8%|▊         | 161/2129 [00:07<01:42, 19.22it/s]
  8%|▊         | 164/2129 [00:08<02:15, 14.48it/s]
  8%|▊         | 167/2129 [00:08<02:14, 14.57it/s]
  8%|▊         | 170/2129 [00:08<02:17, 14.23it/s]
  8%|▊         | 172/2129 [00:08<02:11, 14.90it/s]
  8%|▊         | 178/2129 [00:08<01:42, 19.12it/s]
  9%|▊         | 181/2129 [00:09<01:41, 19.23it/s]
  9%|▊         | 184/2129 [00:09<02:44, 11.79it/s]
  9%|▉         | 187/2129 [00:09<03:16,  9.88it/s]
  9%|▉         | 189/2129 [00:10<03:03, 10.58it/s]
  9%|▉         | 191/2129 [00:10<03:06, 10.39it/s]
  9%|▉         | 193/2129 [00:10<02:46, 11.60it/s]
  9%|▉         | 199/2129 [00:10<01:38, 19.58it/s]
  9%|▉         | 202/2129 [00:10<02:21, 13.64it/s]
 10%|▉         | 205/2129 [00:11<02:03, 15.64it/s]
 10%|▉         | 212/2129 [00:11<01:52, 16.98it/s]
 10%|█         | 215/2129 [00:11<02:26, 13.09it/s]
 10%|█         | 219/2129 [00:11<01:58, 16.18it/s]
 10%|█         | 223/2129 [00:12<02:49, 11.23it/s]
 11%|█         | 225/2129 [00:12<02:39, 11.94it/s]
 11%|█         | 233/2129 [00:13<02:05, 15.12it/s]
 11%|█         | 235/2129 [00:13<03:18,  9.56it/s]
 11%|█         | 239/2129 [00:14<03:16,  9.64it/s]
 11%|█▏        | 242/2129 [00:14<02:47, 11.30it/s]
 12%|█▏        | 246/2129 [00:14<02:44, 11.46it/s]
 12%|█▏        | 248/2129 [00:14<03:18,  9.49it/s]
 12%|█▏        | 250/2129 [00:15<04:31,  6.91it/s]
 12%|█▏        | 252/2129 [00:15<05:04,  6.17it/s]
 12%|█▏        | 254/2129 [00:16<04:13,  7.40it/s]
 12%|█▏        | 258/2129 [00:16<03:36,  8.66it/s]
 12%|█▏        | 260/2129 [00:17<05:00,  6.22it/s]
 12%|█▏        | 261/2129 [00:17<07:13,  4.30it/s]
 12%|█▏        | 264/2129 [00:17<04:57,  6.28it/s]
 13%|█▎        | 267/2129 [00:18<04:04,  7.62it/s]
 13%|█▎        | 270/2129 [00:18<03:11,  9.70it/s]
 13%|█▎        | 273/2129 [00:18<03:31,  8.77it/s]
 13%|█▎        | 275/2129 [00:18<03:54,  7.91it/s]
 13%|█▎        | 278/2129 [00:19<03:03, 10.10it/s]
 13%|█▎        | 286/2129 [00:19<01:34, 19.59it/s]
 14%|█▎        | 290/2129 [00:19<01:56, 15.74it/s]
 14%|█▍        | 293/2129 [00:19<02:26, 12.50it/s]
 14%|█▍        | 298/2129 [00:20<01:47, 17.03it/s]
 14%|█▍        | 304/2129 [00:20<01:47, 16.90it/s]
 14%|█▍        | 307/2129 [00:20<02:19, 13.08it/s]
 15%|█▍        | 312/2129 [00:21<02:46, 10.94it/s]
 15%|█▍        | 314/2129 [00:22<03:53,  7.77it/s]
 15%|█▍        | 316/2129 [00:22<03:29,  8.66it/s]
 15%|█▌        | 323/2129 [00:22<02:01, 14.86it/s]
 15%|█▌        | 326/2129 [00:23<03:01,  9.92it/s]
 15%|█▌        | 329/2129 [00:23<03:14,  9.27it/s]
 16%|█▌        | 331/2129 [00:23<04:20,  6.90it/s]
 16%|█▌        | 334/2129 [00:24<04:09,  7.18it/s]
 16%|█▌        | 337/2129 [00:24<04:05,  7.29it/s]
 16%|█▌        | 340/2129 [00:24<03:21,  8.89it/s]
 16%|█▌        | 342/2129 [00:25<03:39,  8.16it/s]
 16%|█▌        | 344/2129 [00:25<03:59,  7.44it/s]
 16%|█▌        | 345/2129 [00:25<04:36,  6.46it/s]
 16%|█▋        | 348/2129 [00:25<03:19,  8.91it/s]
 16%|█▋        | 350/2129 [00:26<03:40,  8.06it/s]
 17%|█▋        | 353/2129 [00:26<02:48, 10.54it/s]
 17%|█▋        | 355/2129 [00:26<03:00,  9.81it/s]
 17%|█▋        | 357/2129 [00:27<03:48,  7.74it/s]
 17%|█▋        | 359/2129 [00:27<03:53,  7.58it/s]
 17%|█▋        | 361/2129 [00:28<05:28,  5.38it/s]
 17%|█▋        | 362/2129 [00:28<06:01,  4.89it/s]
 17%|█▋        | 365/2129 [00:28<04:00,  7.34it/s]
 17%|█▋        | 372/2129 [00:28<01:54, 15.35it/s]
 18%|█▊        | 375/2129 [00:29<04:24,  6.63it/s]
 18%|█▊        | 378/2129 [00:30<04:10,  6.99it/s]
 18%|█▊        | 380/2129 [00:30<04:25,  6.60it/s]
 18%|█▊        | 383/2129 [00:30<03:23,  8.58it/s]
 18%|█▊        | 385/2129 [00:30<03:49,  7.60it/s]
 18%|█▊        | 387/2129 [00:31<04:10,  6.96it/s]
 18%|█▊        | 391/2129 [00:31<03:38,  7.97it/s]
 19%|█▊        | 394/2129 [00:32<03:49,  7.56it/s]
 19%|█▊        | 397/2129 [00:32<03:01,  9.56it/s]
 19%|█▉        | 400/2129 [00:32<03:00,  9.59it/s]
 19%|█▉        | 403/2129 [00:32<02:24, 11.93it/s]
 19%|█▉        | 405/2129 [00:33<03:35,  8.02it/s]
 19%|█▉        | 407/2129 [00:33<04:17,  6.67it/s]
 19%|█▉        | 409/2129 [00:34<04:30,  6.35it/s]
 19%|█▉        | 411/2129 [00:34<03:45,  7.63it/s]
 20%|█▉        | 416/2129 [00:34<02:12, 12.93it/s]
 20%|█▉        | 423/2129 [00:34<01:18, 21.60it/s]
 20%|██        | 430/2129 [00:34<01:25, 19.78it/s]
 20%|██        | 434/2129 [00:35<02:09, 13.07it/s]
 21%|██        | 437/2129 [00:35<02:33, 11.01it/s]
 21%|██        | 439/2129 [00:36<03:07,  9.02it/s]
 21%|██        | 442/2129 [00:36<02:33, 10.95it/s]
 21%|██        | 448/2129 [00:36<01:43, 16.23it/s]
 21%|██▏       | 454/2129 [00:36<01:15, 22.19it/s]
 22%|██▏       | 458/2129 [00:37<01:51, 14.92it/s]
 22%|██▏       | 461/2129 [00:37<02:04, 13.36it/s]
 22%|██▏       | 464/2129 [00:37<01:57, 14.22it/s]
 22%|██▏       | 467/2129 [00:37<02:22, 11.66it/s]
 22%|██▏       | 469/2129 [00:38<03:22,  8.19it/s]
 22%|██▏       | 471/2129 [00:38<03:47,  7.28it/s]
 22%|██▏       | 474/2129 [00:38<02:55,  9.42it/s]
 22%|██▏       | 477/2129 [00:39<02:59,  9.22it/s]
 22%|██▏       | 479/2129 [00:39<03:39,  7.52it/s]
 23%|██▎       | 481/2129 [00:40<04:57,  5.54it/s]
 23%|██▎       | 483/2129 [00:40<04:53,  5.61it/s]
 23%|██▎       | 484/2129 [00:41<05:19,  5.15it/s]
 23%|██▎       | 486/2129 [00:41<04:18,  6.37it/s]
 23%|██▎       | 487/2129 [00:41<05:22,  5.09it/s]
 23%|██▎       | 489/2129 [00:41<04:03,  6.74it/s]
 23%|██▎       | 491/2129 [00:41<03:35,  7.60it/s]
 23%|██▎       | 493/2129 [00:41<03:01,  9.00it/s]
 23%|██▎       | 496/2129 [00:42<02:12, 12.35it/s]
 24%|██▎       | 501/2129 [00:42<01:37, 16.72it/s]
 24%|██▎       | 504/2129 [00:42<01:30, 17.95it/s]
 24%|██▍       | 508/2129 [00:42<01:50, 14.63it/s]
 24%|██▍       | 510/2129 [00:43<02:27, 11.01it/s]
 24%|██▍       | 512/2129 [00:43<02:16, 11.82it/s]
 24%|██▍       | 515/2129 [00:43<03:23,  7.95it/s]
 24%|██▍       | 517/2129 [00:44<04:48,  5.58it/s]
 24%|██▍       | 520/2129 [00:44<04:20,  6.17it/s]
 24%|██▍       | 521/2129 [00:45<04:56,  5.43it/s]
 25%|██▍       | 522/2129 [00:45<06:52,  3.90it/s]
 25%|██▍       | 525/2129 [00:46<04:30,  5.93it/s]
 25%|██▍       | 527/2129 [00:46<04:32,  5.87it/s]
 25%|██▍       | 528/2129 [00:46<05:22,  4.96it/s]
 25%|██▍       | 529/2129 [00:47<06:03,  4.40it/s]
 25%|██▍       | 530/2129 [00:47<08:26,  3.15it/s]
 25%|██▍       | 532/2129 [00:47<05:45,  4.63it/s]
 25%|██▌       | 535/2129 [00:48<04:36,  5.77it/s]
 25%|██▌       | 536/2129 [00:48<05:12,  5.10it/s]
 25%|██▌       | 539/2129 [00:48<03:29,  7.61it/s]
 26%|██▌       | 543/2129 [00:48<02:50,  9.28it/s]
 26%|██▌       | 545/2129 [00:49<02:29, 10.61it/s]
 26%|██▌       | 547/2129 [00:49<02:36, 10.09it/s]
 26%|██▌       | 550/2129 [00:49<02:07, 12.39it/s]
 26%|██▌       | 555/2129 [00:49<01:24, 18.67it/s]
 26%|██▌       | 558/2129 [00:49<01:52, 13.92it/s]
 26%|██▋       | 560/2129 [00:50<01:58, 13.19it/s]
 26%|██▋       | 563/2129 [00:50<02:22, 10.99it/s]
 27%|██▋       | 565/2129 [00:50<02:31, 10.31it/s]
 27%|██▋       | 567/2129 [00:51<03:02,  8.58it/s]
 27%|██▋       | 569/2129 [00:51<02:39,  9.79it/s]
 27%|██▋       | 571/2129 [00:51<02:48,  9.24it/s]
 27%|██▋       | 575/2129 [00:51<01:55, 13.46it/s]
 27%|██▋       | 577/2129 [00:51<02:08, 12.06it/s]
 27%|██▋       | 580/2129 [00:51<01:50, 14.02it/s]
 27%|██▋       | 582/2129 [00:52<01:59, 12.94it/s]
 27%|██▋       | 584/2129 [00:52<02:20, 10.96it/s]
 28%|██▊       | 586/2129 [00:52<02:24, 10.66it/s]
 28%|██▊       | 588/2129 [00:52<02:40,  9.58it/s]
 28%|██▊       | 590/2129 [00:53<04:07,  6.23it/s]
 28%|██▊       | 593/2129 [00:53<03:41,  6.93it/s]
 28%|██▊       | 596/2129 [00:53<02:47,  9.14it/s]
 28%|██▊       | 599/2129 [00:54<02:48,  9.08it/s]
 28%|██▊       | 602/2129 [00:54<02:54,  8.76it/s]
 28%|██▊       | 605/2129 [00:55<03:00,  8.46it/s]
 29%|██▊       | 607/2129 [00:55<02:37,  9.65it/s]
 29%|██▊       | 610/2129 [00:55<03:26,  7.35it/s]
 29%|██▉       | 613/2129 [00:56<03:24,  7.41it/s]
 29%|██▉       | 616/2129 [00:56<02:40,  9.46it/s]
 29%|██▉       | 622/2129 [00:56<02:05, 11.97it/s]
 29%|██▉       | 625/2129 [00:56<01:47, 14.00it/s]
 29%|██▉       | 627/2129 [00:57<02:20, 10.67it/s]
 30%|██▉       | 629/2129 [00:57<02:50,  8.78it/s]
 30%|██▉       | 631/2129 [00:58<03:52,  6.45it/s]
 30%|██▉       | 632/2129 [00:58<04:24,  5.67it/s]
 30%|██▉       | 633/2129 [00:58<05:59,  4.16it/s]
 30%|██▉       | 635/2129 [00:59<04:38,  5.36it/s]
 30%|██▉       | 636/2129 [00:59<05:16,  4.72it/s]
 30%|██▉       | 638/2129 [00:59<03:54,  6.35it/s]
 30%|███       | 640/2129 [00:59<03:01,  8.23it/s]
 30%|███       | 642/2129 [00:59<03:19,  7.45it/s]
 30%|███       | 644/2129 [01:00<05:39,  4.37it/s]
 30%|███       | 648/2129 [01:00<03:20,  7.40it/s]
 31%|███       | 650/2129 [01:01<03:33,  6.94it/s]
 31%|███       | 653/2129 [01:01<03:19,  7.40it/s]
 31%|███       | 656/2129 [01:01<02:33,  9.61it/s]
 31%|███       | 658/2129 [01:02<02:56,  8.33it/s]
 31%|███       | 661/2129 [01:02<03:06,  7.89it/s]
 31%|███       | 663/2129 [01:03<04:29,  5.43it/s]
 31%|███▏      | 666/2129 [01:03<03:18,  7.36it/s]
 31%|███▏      | 668/2129 [01:03<03:32,  6.87it/s]
 31%|███▏      | 670/2129 [01:03<02:57,  8.21it/s]
 32%|███▏      | 672/2129 [01:04<03:27,  7.01it/s]
 32%|███▏      | 674/2129 [01:04<04:24,  5.50it/s]
 32%|███▏      | 675/2129 [01:05<05:55,  4.09it/s]
 32%|███▏      | 677/2129 [01:05<05:19,  4.55it/s]
 32%|███▏      | 679/2129 [01:05<04:02,  5.98it/s]
 32%|███▏      | 683/2129 [01:06<04:00,  6.02it/s]
 32%|███▏      | 684/2129 [01:06<04:30,  5.34it/s]
 32%|███▏      | 685/2129 [01:07<05:02,  4.77it/s]
 32%|███▏      | 687/2129 [01:07<05:46,  4.16it/s]
 32%|███▏      | 688/2129 [01:07<06:03,  3.97it/s]
 32%|███▏      | 689/2129 [01:08<06:26,  3.72it/s]
 33%|███▎      | 692/2129 [01:08<03:49,  6.27it/s]
 33%|███▎      | 694/2129 [01:08<04:00,  5.98it/s]
 33%|███▎      | 696/2129 [01:09<04:08,  5.76it/s]
 33%|███▎      | 698/2129 [01:09<03:21,  7.10it/s]
 33%|███▎      | 703/2129 [01:09<03:12,  7.40it/s]
 33%|███▎      | 705/2129 [01:10<04:07,  5.76it/s]
 33%|███▎      | 707/2129 [01:10<04:08,  5.71it/s]
 33%|███▎      | 708/2129 [01:11<04:36,  5.14it/s]
 33%|███▎      | 709/2129 [01:11<05:08,  4.60it/s]
 33%|███▎      | 712/2129 [01:11<04:17,  5.50it/s]
 33%|███▎      | 713/2129 [01:12<04:50,  4.88it/s]
 34%|███▎      | 715/2129 [01:12<03:38,  6.48it/s]
 34%|███▍      | 719/2129 [01:12<03:34,  6.59it/s]
 34%|███▍      | 721/2129 [01:13<04:28,  5.25it/s]
 34%|███▍      | 723/2129 [01:13<04:15,  5.50it/s]
 34%|███▍      | 724/2129 [01:14<05:37,  4.17it/s]
 34%|███▍      | 725/2129 [01:14<05:43,  4.09it/s]
 34%|███▍      | 726/2129 [01:14<05:58,  3.91it/s]
 34%|███▍      | 727/2129 [01:15<07:10,  3.25it/s]
 34%|███▍      | 728/2129 [01:15<07:12,  3.24it/s]
 34%|███▍      | 731/2129 [01:15<03:59,  5.85it/s]
 34%|███▍      | 733/2129 [01:16<03:29,  6.67it/s]
 35%|███▍      | 736/2129 [01:16<02:27,  9.42it/s]
 35%|███▍      | 739/2129 [01:16<02:09, 10.74it/s]
 35%|███▍      | 741/2129 [01:16<02:01, 11.43it/s]
 35%|███▍      | 743/2129 [01:16<02:33,  9.02it/s]
 35%|███▍      | 745/2129 [01:17<02:12, 10.41it/s]
 35%|███▌      | 748/2129 [01:17<01:42, 13.44it/s]
 35%|███▌      | 750/2129 [01:17<03:16,  7.01it/s]
 35%|███▌      | 752/2129 [01:18<04:22,  5.24it/s]
 35%|███▌      | 753/2129 [01:18<05:33,  4.13it/s]
 35%|███▌      | 754/2129 [01:19<06:53,  3.33it/s]
 35%|███▌      | 755/2129 [01:20<08:17,  2.76it/s]
 36%|███▌      | 757/2129 [01:20<05:46,  3.96it/s]
 36%|███▌      | 758/2129 [01:20<06:05,  3.75it/s]
 36%|███▌      | 760/2129 [01:20<04:21,  5.23it/s]
 36%|███▌      | 762/2129 [01:20<03:47,  6.02it/s]
 36%|███▌      | 763/2129 [01:21<03:43,  6.11it/s]
 36%|███▌      | 766/2129 [01:21<03:15,  6.97it/s]
 36%|███▌      | 767/2129 [01:21<04:07,  5.50it/s]
 36%|███▌      | 769/2129 [01:22<03:40,  6.17it/s]
 36%|███▌      | 771/2129 [01:22<02:53,  7.83it/s]
 36%|███▋      | 774/2129 [01:22<03:10,  7.10it/s]
 36%|███▋      | 776/2129 [01:23<03:34,  6.31it/s]
 37%|███▋      | 779/2129 [01:23<02:37,  8.56it/s]
 37%|███▋      | 781/2129 [01:23<02:29,  9.01it/s]
 37%|███▋      | 783/2129 [01:23<02:42,  8.31it/s]
 37%|███▋      | 785/2129 [01:24<03:06,  7.19it/s]
 37%|███▋      | 787/2129 [01:24<03:00,  7.42it/s]
 37%|███▋      | 790/2129 [01:24<02:18,  9.65it/s]
 37%|███▋      | 795/2129 [01:25<02:32,  8.77it/s]
 37%|███▋      | 797/2129 [01:25<03:32,  6.27it/s]
 37%|███▋      | 798/2129 [01:26<04:02,  5.48it/s]
 38%|███▊      | 800/2129 [01:26<03:59,  5.55it/s]
 38%|███▊      | 802/2129 [01:26<03:57,  5.59it/s]
 38%|███▊      | 805/2129 [01:26<02:49,  7.82it/s]
 38%|███▊      | 809/2129 [01:27<02:26,  8.98it/s]
 38%|███▊      | 811/2129 [01:27<02:36,  8.40it/s]
 38%|███▊      | 813/2129 [01:27<02:49,  7.78it/s]
 38%|███▊      | 816/2129 [01:28<02:15,  9.69it/s]
 38%|███▊      | 818/2129 [01:28<02:30,  8.69it/s]
 39%|███▊      | 820/2129 [01:28<03:27,  6.31it/s]
 39%|███▊      | 822/2129 [01:29<02:50,  7.68it/s]
 39%|███▉      | 827/2129 [01:29<02:02, 10.67it/s]
 39%|███▉      | 829/2129 [01:29<01:53, 11.43it/s]
 39%|███▉      | 831/2129 [01:29<01:44, 12.46it/s]
 39%|███▉      | 840/2129 [01:29<00:50, 25.73it/s]
 40%|███▉      | 844/2129 [01:30<01:41, 12.66it/s]
 40%|███▉      | 847/2129 [01:30<01:42, 12.50it/s]
 40%|███▉      | 850/2129 [01:31<02:15,  9.43it/s]
 40%|████      | 852/2129 [01:31<02:14,  9.53it/s]
 40%|████      | 854/2129 [01:31<02:10,  9.76it/s]
 40%|████      | 856/2129 [01:31<02:21,  8.98it/s]
 40%|████      | 858/2129 [01:32<02:24,  8.78it/s]
 40%|████      | 860/2129 [01:32<02:41,  7.87it/s]
 40%|████      | 862/2129 [01:32<02:34,  8.17it/s]
 41%|████      | 864/2129 [01:33<03:03,  6.88it/s]
 41%|████      | 865/2129 [01:33<03:39,  5.76it/s]
 41%|████      | 866/2129 [01:33<05:23,  3.91it/s]
 41%|████      | 869/2129 [01:34<03:15,  6.43it/s]
 41%|████      | 873/2129 [01:34<02:12,  9.46it/s]
 41%|████      | 875/2129 [01:34<01:56, 10.81it/s]
 41%|████      | 877/2129 [01:34<02:21,  8.85it/s]
 41%|████▏     | 881/2129 [01:35<02:47,  7.43it/s]
 42%|████▏     | 884/2129 [01:35<02:11,  9.50it/s]
 42%|████▏     | 886/2129 [01:36<03:07,  6.62it/s]
 42%|████▏     | 888/2129 [01:36<03:59,  5.18it/s]
 42%|████▏     | 890/2129 [01:37<04:43,  4.38it/s]
 42%|████▏     | 891/2129 [01:37<05:49,  3.54it/s]
 42%|████▏     | 893/2129 [01:38<05:51,  3.52it/s]
 42%|████▏     | 895/2129 [01:39<06:10,  3.33it/s]
 42%|████▏     | 898/2129 [01:39<04:43,  4.34it/s]
 42%|████▏     | 900/2129 [01:40<05:12,  3.94it/s]
 42%|████▏     | 902/2129 [01:40<04:47,  4.27it/s]
 42%|████▏     | 903/2129 [01:40<05:10,  3.95it/s]
 43%|████▎     | 905/2129 [01:41<05:41,  3.59it/s]
 43%|████▎     | 906/2129 [01:42<06:47,  3.00it/s]
 43%|████▎     | 908/2129 [01:42<06:25,  3.17it/s]
 43%|████▎     | 911/2129 [01:43<04:58,  4.08it/s]
 43%|████▎     | 912/2129 [01:43<05:16,  3.85it/s]
 43%|████▎     | 914/2129 [01:43<04:39,  4.35it/s]
 43%|████▎     | 916/2129 [01:44<04:19,  4.68it/s]
 43%|████▎     | 918/2129 [01:44<03:16,  6.15it/s]
 43%|████▎     | 925/2129 [01:44<01:27, 13.72it/s]
 44%|████▎     | 928/2129 [01:45<02:25,  8.26it/s]
 44%|████▎     | 931/2129 [01:45<02:10,  9.18it/s]
 44%|████▍     | 933/2129 [01:45<01:55, 10.34it/s]
 44%|████▍     | 935/2129 [01:46<02:55,  6.79it/s]
 44%|████▍     | 937/2129 [01:46<03:25,  5.81it/s]
 44%|████▍     | 939/2129 [01:47<04:19,  4.58it/s]
 44%|████▍     | 943/2129 [01:47<03:15,  6.06it/s]
 44%|████▍     | 944/2129 [01:47<03:09,  6.26it/s]
 44%|████▍     | 945/2129 [01:48<03:14,  6.08it/s]
 44%|████▍     | 946/2129 [01:48<03:54,  5.05it/s]
 44%|████▍     | 947/2129 [01:48<04:01,  4.89it/s]
 45%|████▍     | 950/2129 [01:48<02:42,  7.23it/s]
 45%|████▍     | 953/2129 [01:48<01:58,  9.94it/s]
 45%|████▍     | 955/2129 [01:49<02:16,  8.62it/s]
 45%|████▍     | 958/2129 [01:49<02:07,  9.19it/s]
 45%|████▌     | 960/2129 [01:49<02:32,  7.66it/s]
 45%|████▌     | 961/2129 [01:50<02:36,  7.46it/s]
 45%|████▌     | 963/2129 [01:50<02:19,  8.35it/s]
 45%|████▌     | 966/2129 [01:50<01:47, 10.83it/s]
 45%|████▌     | 968/2129 [01:50<02:47,  6.93it/s]
 46%|████▌     | 969/2129 [01:51<03:03,  6.31it/s]
 46%|████▌     | 970/2129 [01:51<04:18,  4.49it/s]
 46%|████▌     | 971/2129 [01:51<04:11,  4.61it/s]
 46%|████▌     | 973/2129 [01:52<03:56,  4.88it/s]
 46%|████▌     | 974/2129 [01:52<03:31,  5.45it/s]
 46%|████▌     | 977/2129 [01:52<02:15,  8.49it/s]
 46%|████▌     | 981/2129 [01:52<01:45, 10.87it/s]
 46%|████▌     | 984/2129 [01:53<02:02,  9.35it/s]
 46%|████▋     | 986/2129 [01:53<01:46, 10.74it/s]
 46%|████▋     | 988/2129 [01:53<02:02,  9.31it/s]
 47%|████▋     | 991/2129 [01:53<01:33, 12.17it/s]
 47%|████▋     | 993/2129 [01:53<01:48, 10.50it/s]
 47%|████▋     | 997/2129 [01:54<01:16, 14.86it/s]
 47%|████▋     | 1001/2129 [01:54<01:50, 10.21it/s]
 47%|████▋     | 1003/2129 [01:54<02:05,  9.01it/s]
 47%|████▋     | 1005/2129 [01:55<01:48, 10.32it/s]
 47%|████▋     | 1007/2129 [01:55<02:24,  7.74it/s]
 47%|████▋     | 1010/2129 [01:55<01:56,  9.57it/s]
 48%|████▊     | 1012/2129 [01:56<02:18,  8.09it/s]
 48%|████▊     | 1014/2129 [01:56<02:20,  7.93it/s]
 48%|████▊     | 1016/2129 [01:56<02:36,  7.11it/s]
 48%|████▊     | 1018/2129 [01:57<03:30,  5.28it/s]
 48%|████▊     | 1019/2129 [01:57<04:01,  4.59it/s]
 48%|████▊     | 1021/2129 [01:57<03:38,  5.08it/s]
 48%|████▊     | 1023/2129 [01:58<03:13,  5.70it/s]
 48%|████▊     | 1024/2129 [01:58<03:18,  5.56it/s]
 48%|████▊     | 1026/2129 [01:58<02:33,  7.19it/s]
 48%|████▊     | 1028/2129 [01:59<03:17,  5.57it/s]
 48%|████▊     | 1030/2129 [01:59<02:55,  6.25it/s]
 48%|████▊     | 1032/2129 [01:59<02:46,  6.58it/s]
 49%|████▊     | 1034/2129 [01:59<02:38,  6.91it/s]
 49%|████▊     | 1036/2129 [01:59<02:13,  8.17it/s]
 49%|████▉     | 1040/2129 [02:00<01:58,  9.19it/s]
 49%|████▉     | 1042/2129 [02:00<02:08,  8.44it/s]
 49%|████▉     | 1044/2129 [02:00<01:49,  9.89it/s]
 49%|████▉     | 1046/2129 [02:00<01:41, 10.64it/s]
 49%|████▉     | 1048/2129 [02:01<02:40,  6.72it/s]
 49%|████▉     | 1049/2129 [02:01<03:40,  4.90it/s]
 49%|████▉     | 1051/2129 [02:02<03:01,  5.94it/s]
 50%|████▉     | 1054/2129 [02:02<02:05,  8.56it/s]
 50%|████▉     | 1056/2129 [02:02<02:46,  6.43it/s]
 50%|████▉     | 1058/2129 [02:03<03:45,  4.74it/s]
 50%|████▉     | 1060/2129 [02:03<03:21,  5.32it/s]
 50%|████▉     | 1064/2129 [02:04<02:35,  6.85it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 310.21it/s]

[[np.int64(0), False, 11], [np.int64(1), False, 9], [np.int64(2), False, 13], [np.int64(3), False, 1], [np.int64(4), False, 10], [np.int64(5), False, 0], [np.int64(6), False, 1], [np.int64(7), False, 13], [np.int64(8), False, 9], [np.int64(9), False, 0], [np.int64(10), False, 2], [np.int64(12), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.4445, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:52<4:38:18, 83.91s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.2680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>)

 34%|███▍      | 102/300 [04:52<3:14:28, 58.93s/it]

tensor(-2.5937, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2821, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8046, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:52<1:06:12, 20.37s/it]

tensor(12.3206, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0280, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2146, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [04:52<46:15, 14.31s/it]

tensor(12.4150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3428, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4631, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [04:53<22:38,  7.08s/it]

tensor(12.4520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5686, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6848, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [04:53<11:11,  3.54s/it]

tensor(12.4376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8039, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9194, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:53<04:01,  1.29s/it]

tensor(12.4280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0117, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0900, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:53<02:08,  1.44it/s]

tensor(12.4116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1955, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [04:53<01:36,  1.91it/s]

tensor(12.3608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2428, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3491, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2981, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [04:54<00:57,  3.14it/s]

tensor(12.3454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3474, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3407, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3812, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:54<00:39,  4.59it/s]

tensor(12.3286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4070, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4350, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [04:54<00:27,  6.47it/s]

tensor(12.2864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4538, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4783, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [04:54<00:25,  6.92it/s]

tensor(12.2378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4928, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2161, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5118, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [04:55<00:22,  7.72it/s]

tensor(12.1969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5451, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [04:55<00:21,  7.85it/s]

tensor(12.1673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5650, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1555, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5894, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [04:55<00:21,  8.04it/s]

tensor(12.1435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1305, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6308, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [04:56<00:20,  8.16it/s]

tensor(12.1163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6516, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6759, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [04:56<00:20,  8.17it/s]

tensor(12.0863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6929, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0725, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7119, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:56<00:19,  8.20it/s]

tensor(12.0603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7309, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0492, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7440, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [04:56<00:19,  8.17it/s]

tensor(12.0390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7725, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:57<00:19,  8.17it/s]

tensor(12.0183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7814, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7928, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:57<00:19,  8.24it/s]

tensor(11.9981, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8066, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8212, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [04:57<00:18,  8.25it/s]

tensor(11.9771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8361, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8535, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [04:57<00:18,  8.25it/s]

tensor(11.9564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8827, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9470, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8974, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:57<00:18,  8.22it/s]

tensor(11.9386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9169, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9384, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:58<00:18,  8.21it/s]

tensor(11.9215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9531, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([308,  44, 116,  87, 187, 108, 127, 290,  70, 199, 198, 249,  89,  57])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:28, 24.12it/s]
  0%|          | 10/2129 [00:00<00:45, 46.16it/s]
  1%|          | 17/2129 [00:00<00:39, 53.34it/s]
  1%|          | 23/2129 [00:00<00:48, 43.48it/s]
  1%|▏         | 30/2129 [00:00<00:43, 48.27it/s]
  2%|▏         | 36/2129 [00:00<00:43, 48.50it/s]
  2%|▏         | 43/2129 [00:00<00:40, 51.84it/s]
  2%|▏         | 50/2129 [00:01<00:38, 54.57it/s]
  3%|▎         | 56/2129 [00:01<00:57, 35.89it/s]
  3%|▎         | 61/2129 [00:01<01:07, 30.69it/s]
  3%|▎         | 65/2129 [00:01<01:15, 27.23it/s]
  3%|▎         | 69/2129 [00:01<01:23, 24.82it/s]
  3%|▎         | 73/2129 [00:02<01:40, 20.54it/s]
  4%|▎         | 76/2129 [00:02<01:37, 20.96it/s]
  4%|▍         | 80/2129 [00:02<01:24, 24.34it/s]
  4%|▍         | 83/2129 [00:02<01:22, 24.89it/s]
  4%|▍         | 89/2129 [00:02<01:03, 32.06it/s]
  4%|▍         | 95/2129 [00:02<00:53, 37.77it/s]
  5%|▍         | 100/2129 [00:03<01:30, 22.33it/s]
  5%|▍         | 104/2129 [00:03<01:41, 19.95it/s]
  5%|▌         | 107/2129 [00:03<01:36, 20.85it/s]
  5%|▌         | 114/2129 [00:03<01:09, 28.82it/s]
  6%|▌         | 122/2129 [00:03<00:52, 38.26it/s]
  6%|▌         | 129/2129 [00:03<00:45, 43.63it/s]
  6%|▋         | 135/2129 [00:04<01:12, 27.47it/s]
  7%|▋         | 143/2129 [00:04<00:55, 35.73it/s]
  7%|▋         | 150/2129 [00:04<00:47, 42.06it/s]
  7%|▋         | 156/2129 [00:04<00:44, 44.43it/s]
  8%|▊         | 162/2129 [00:05<01:11, 27.41it/s]
  8%|▊         | 167/2129 [00:05<01:26, 22.68it/s]
  8%|▊         | 171/2129 [00:05<01:31, 21.38it/s]
  8%|▊         | 175/2129 [00:05<01:25, 22.95it/s]
  8%|▊         | 180/2129 [00:05<01:12, 27.06it/s]
  9%|▊         | 184/2129 [00:06<01:15, 25.72it/s]
  9%|▉         | 188/2129 [00:06<02:01, 16.01it/s]
  9%|▉         | 191/2129 [00:06<02:19, 13.89it/s]
  9%|▉         | 194/2129 [00:07<02:02, 15.83it/s]
  9%|▉         | 200/2129 [00:07<01:38, 19.65it/s]
 10%|▉         | 204/2129 [00:07<01:25, 22.54it/s]
 10%|▉         | 211/2129 [00:07<01:02, 30.78it/s]
 10%|█         | 215/2129 [00:07<01:12, 26.50it/s]
 10%|█         | 219/2129 [00:07<01:08, 27.90it/s]
 10%|█         | 223/2129 [00:08<01:23, 22.83it/s]
 11%|█         | 226/2129 [00:08<01:19, 23.86it/s]
 11%|█         | 232/2129 [00:08<01:05, 28.84it/s]
 11%|█         | 236/2129 [00:08<01:37, 19.44it/s]
 11%|█         | 239/2129 [00:08<01:45, 17.97it/s]
 11%|█▏        | 242/2129 [00:09<01:47, 17.60it/s]
 12%|█▏        | 246/2129 [00:09<01:40, 18.79it/s]
 12%|█▏        | 249/2129 [00:09<01:41, 18.49it/s]
 12%|█▏        | 251/2129 [00:09<02:08, 14.62it/s]
 12%|█▏        | 253/2129 [00:09<02:08, 14.64it/s]
 12%|█▏        | 256/2129 [00:09<01:49, 17.06it/s]
 12%|█▏        | 259/2129 [00:10<01:40, 18.70it/s]
 12%|█▏        | 262/2129 [00:10<01:48, 17.15it/s]
 12%|█▏        | 264/2129 [00:10<01:45, 17.60it/s]
 13%|█▎        | 267/2129 [00:10<02:05, 14.85it/s]
 13%|█▎        | 269/2129 [00:10<01:57, 15.79it/s]
 13%|█▎        | 272/2129 [00:10<01:42, 18.10it/s]
 13%|█▎        | 274/2129 [00:11<02:14, 13.83it/s]
 13%|█▎        | 276/2129 [00:11<02:27, 12.58it/s]
 13%|█▎        | 278/2129 [00:11<02:20, 13.19it/s]
 13%|█▎        | 280/2129 [00:11<02:12, 14.00it/s]
 13%|█▎        | 286/2129 [00:11<01:17, 23.73it/s]
 14%|█▎        | 289/2129 [00:11<01:41, 18.06it/s]
 14%|█▎        | 292/2129 [00:12<02:06, 14.53it/s]
 14%|█▍        | 294/2129 [00:12<02:11, 13.99it/s]
 14%|█▍        | 296/2129 [00:12<02:02, 14.94it/s]
 14%|█▍        | 302/2129 [00:12<01:21, 22.53it/s]
 14%|█▍        | 305/2129 [00:12<01:50, 16.45it/s]
 14%|█▍        | 308/2129 [00:13<01:44, 17.36it/s]
 15%|█▍        | 312/2129 [00:13<01:30, 19.97it/s]
 15%|█▍        | 315/2129 [00:13<01:32, 19.55it/s]
 15%|█▍        | 318/2129 [00:13<01:23, 21.62it/s]
 15%|█▌        | 324/2129 [00:13<01:27, 20.56it/s]
 15%|█▌        | 327/2129 [00:13<01:26, 20.90it/s]
 16%|█▌        | 330/2129 [00:14<02:37, 11.42it/s]
 16%|█▌        | 332/2129 [00:14<03:12,  9.32it/s]
 16%|█▌        | 334/2129 [00:15<03:21,  8.90it/s]
 16%|█▌        | 337/2129 [00:15<02:53, 10.30it/s]
 16%|█▌        | 339/2129 [00:15<02:41, 11.06it/s]
 16%|█▌        | 342/2129 [00:15<02:40, 11.12it/s]
 16%|█▌        | 344/2129 [00:15<02:43, 10.89it/s]
 16%|█▋        | 347/2129 [00:16<02:13, 13.30it/s]
 16%|█▋        | 349/2129 [00:16<02:37, 11.33it/s]
 16%|█▋        | 351/2129 [00:16<02:38, 11.21it/s]
 17%|█▋        | 354/2129 [00:16<03:00,  9.85it/s]
 17%|█▋        | 356/2129 [00:17<03:37,  8.14it/s]
 17%|█▋        | 357/2129 [00:17<04:28,  6.61it/s]
 17%|█▋        | 358/2129 [00:17<04:19,  6.84it/s]
 17%|█▋        | 359/2129 [00:17<04:04,  7.23it/s]
 17%|█▋        | 361/2129 [00:18<03:51,  7.65it/s]
 17%|█▋        | 362/2129 [00:18<04:49,  6.10it/s]
 17%|█▋        | 365/2129 [00:18<03:04,  9.55it/s]
 17%|█▋        | 371/2129 [00:18<01:36, 18.25it/s]
 18%|█▊        | 374/2129 [00:18<01:53, 15.46it/s]
 18%|█▊        | 377/2129 [00:19<02:27, 11.88it/s]
 18%|█▊        | 380/2129 [00:19<02:14, 13.02it/s]
 18%|█▊        | 382/2129 [00:19<02:11, 13.28it/s]
 18%|█▊        | 384/2129 [00:19<02:22, 12.27it/s]
 18%|█▊        | 386/2129 [00:19<02:13, 13.07it/s]
 18%|█▊        | 390/2129 [00:20<01:38, 17.71it/s]
 18%|█▊        | 393/2129 [00:20<01:50, 15.67it/s]
 19%|█▊        | 395/2129 [00:20<01:54, 15.15it/s]
 19%|█▉        | 400/2129 [00:20<01:25, 20.24it/s]
 19%|█▉        | 404/2129 [00:20<01:19, 21.56it/s]
 19%|█▉        | 407/2129 [00:20<01:37, 17.67it/s]
 19%|█▉        | 409/2129 [00:21<01:50, 15.59it/s]
 19%|█▉        | 412/2129 [00:21<01:36, 17.72it/s]
 20%|█▉        | 416/2129 [00:21<01:17, 22.16it/s]
 20%|█▉        | 422/2129 [00:21<00:56, 30.45it/s]
 20%|██        | 430/2129 [00:21<00:53, 32.03it/s]
 20%|██        | 434/2129 [00:22<01:16, 22.15it/s]
 21%|██        | 437/2129 [00:22<01:26, 19.49it/s]
 21%|██        | 440/2129 [00:22<01:38, 17.07it/s]
 21%|██        | 443/2129 [00:22<01:29, 18.87it/s]
 21%|██        | 448/2129 [00:22<01:13, 22.98it/s]
 21%|██▏       | 453/2129 [00:22<01:00, 27.82it/s]
 21%|██▏       | 457/2129 [00:23<01:32, 18.16it/s]
 22%|██▏       | 460/2129 [00:23<01:47, 15.53it/s]
 22%|██▏       | 463/2129 [00:23<01:44, 15.89it/s]
 22%|██▏       | 466/2129 [00:23<01:50, 15.07it/s]
 22%|██▏       | 468/2129 [00:24<02:05, 13.22it/s]
 22%|██▏       | 470/2129 [00:24<01:57, 14.17it/s]
 22%|██▏       | 472/2129 [00:24<01:54, 14.47it/s]
 22%|██▏       | 475/2129 [00:24<01:39, 16.70it/s]
 22%|██▏       | 477/2129 [00:24<01:51, 14.82it/s]
 22%|██▏       | 479/2129 [00:24<01:51, 14.76it/s]
 23%|██▎       | 481/2129 [00:25<02:44, 10.03it/s]
 23%|██▎       | 483/2129 [00:25<02:47,  9.83it/s]
 23%|██▎       | 485/2129 [00:25<02:43, 10.03it/s]
 23%|██▎       | 487/2129 [00:25<03:01,  9.04it/s]
 23%|██▎       | 489/2129 [00:26<02:44,  9.99it/s]
 23%|██▎       | 491/2129 [00:26<02:41, 10.14it/s]
 23%|██▎       | 494/2129 [00:26<02:58,  9.17it/s]
 23%|██▎       | 497/2129 [00:26<02:16, 11.93it/s]
 23%|██▎       | 500/2129 [00:26<01:49, 14.93it/s]
 24%|██▎       | 502/2129 [00:27<03:12,  8.47it/s]
 24%|██▎       | 504/2129 [00:27<02:50,  9.55it/s]
 24%|██▍       | 508/2129 [00:27<02:19, 11.60it/s]
 24%|██▍       | 510/2129 [00:27<02:14, 12.07it/s]
 24%|██▍       | 512/2129 [00:28<02:56,  9.18it/s]
 24%|██▍       | 515/2129 [00:28<02:48,  9.56it/s]
 24%|██▍       | 517/2129 [00:28<02:58,  9.03it/s]
 24%|██▍       | 519/2129 [00:28<02:39, 10.10it/s]
 25%|██▍       | 522/2129 [00:29<02:33, 10.46it/s]
 25%|██▍       | 525/2129 [00:29<02:59,  8.95it/s]
 25%|██▍       | 527/2129 [00:30<03:24,  7.82it/s]
 25%|██▍       | 528/2129 [00:30<04:02,  6.60it/s]
 25%|██▍       | 530/2129 [00:30<04:01,  6.61it/s]
 25%|██▍       | 532/2129 [00:30<03:13,  8.24it/s]
 25%|██▌       | 535/2129 [00:30<02:46,  9.57it/s]
 25%|██▌       | 537/2129 [00:31<02:53,  9.15it/s]
 25%|██▌       | 540/2129 [00:31<02:09, 12.27it/s]
 26%|██▌       | 543/2129 [00:31<02:03, 12.79it/s]
 26%|██▌       | 547/2129 [00:31<01:41, 15.62it/s]
 26%|██▌       | 549/2129 [00:31<02:03, 12.84it/s]
 26%|██▌       | 553/2129 [00:32<01:32, 16.95it/s]
 26%|██▌       | 557/2129 [00:32<01:33, 16.86it/s]
 26%|██▋       | 559/2129 [00:32<01:35, 16.53it/s]
 26%|██▋       | 563/2129 [00:32<01:37, 16.03it/s]
 27%|██▋       | 565/2129 [00:32<01:55, 13.53it/s]
 27%|██▋       | 567/2129 [00:33<01:48, 14.35it/s]
 27%|██▋       | 571/2129 [00:33<01:27, 17.77it/s]
 27%|██▋       | 574/2129 [00:33<01:23, 18.71it/s]
 27%|██▋       | 581/2129 [00:33<00:56, 27.31it/s]
 27%|██▋       | 584/2129 [00:33<01:04, 24.03it/s]
 28%|██▊       | 587/2129 [00:33<01:21, 18.88it/s]
 28%|██▊       | 590/2129 [00:34<01:33, 16.53it/s]
 28%|██▊       | 593/2129 [00:34<01:36, 15.88it/s]
 28%|██▊       | 596/2129 [00:34<01:28, 17.30it/s]
 28%|██▊       | 599/2129 [00:34<01:37, 15.70it/s]
 28%|██▊       | 602/2129 [00:34<01:30, 16.93it/s]
 28%|██▊       | 604/2129 [00:35<02:20, 10.82it/s]
 28%|██▊       | 606/2129 [00:35<02:32, 10.00it/s]
 29%|██▊       | 609/2129 [00:35<02:26, 10.39it/s]
 29%|██▊       | 611/2129 [00:36<02:27, 10.28it/s]
 29%|██▉       | 613/2129 [00:36<02:25, 10.43it/s]
 29%|██▉       | 617/2129 [00:36<01:41, 14.94it/s]
 29%|██▉       | 623/2129 [00:36<01:05, 23.04it/s]
 29%|██▉       | 627/2129 [00:36<00:59, 25.13it/s]
 30%|██▉       | 631/2129 [00:36<01:33, 16.00it/s]
 30%|██▉       | 634/2129 [00:37<01:40, 14.85it/s]
 30%|██▉       | 637/2129 [00:37<01:36, 15.44it/s]
 30%|███       | 640/2129 [00:37<01:25, 17.39it/s]
 30%|███       | 643/2129 [00:37<01:22, 18.04it/s]
 30%|███       | 646/2129 [00:37<01:32, 16.05it/s]
 31%|███       | 650/2129 [00:38<01:14, 19.84it/s]
 31%|███       | 653/2129 [00:38<01:34, 15.68it/s]
 31%|███       | 655/2129 [00:38<02:03, 11.93it/s]
 31%|███       | 657/2129 [00:38<01:52, 13.03it/s]
 31%|███       | 660/2129 [00:39<02:05, 11.69it/s]
 31%|███       | 662/2129 [00:39<02:34,  9.52it/s]
 31%|███       | 664/2129 [00:39<02:32,  9.59it/s]
 31%|███▏      | 666/2129 [00:39<02:13, 10.93it/s]
 31%|███▏      | 669/2129 [00:39<01:46, 13.73it/s]
 32%|███▏      | 672/2129 [00:39<01:27, 16.64it/s]
 32%|███▏      | 675/2129 [00:40<02:03, 11.80it/s]
 32%|███▏      | 677/2129 [00:40<01:59, 12.17it/s]
 32%|███▏      | 679/2129 [00:40<02:28,  9.74it/s]
 32%|███▏      | 681/2129 [00:40<02:10, 11.09it/s]
 32%|███▏      | 683/2129 [00:41<02:18, 10.42it/s]
 32%|███▏      | 685/2129 [00:41<02:22, 10.12it/s]
 32%|███▏      | 687/2129 [00:41<02:53,  8.33it/s]
 32%|███▏      | 688/2129 [00:41<03:14,  7.43it/s]
 32%|███▏      | 689/2129 [00:42<03:05,  7.77it/s]
 32%|███▏      | 691/2129 [00:42<02:32,  9.41it/s]
 33%|███▎      | 694/2129 [00:42<02:04, 11.56it/s]
 33%|███▎      | 696/2129 [00:42<02:11, 10.86it/s]
 33%|███▎      | 699/2129 [00:42<01:48, 13.16it/s]
 33%|███▎      | 703/2129 [00:42<01:42, 13.91it/s]
 33%|███▎      | 705/2129 [00:43<02:12, 10.76it/s]
 33%|███▎      | 707/2129 [00:43<02:21, 10.06it/s]
 33%|███▎      | 709/2129 [00:43<02:35,  9.13it/s]
 33%|███▎      | 711/2129 [00:43<02:14, 10.53it/s]
 33%|███▎      | 713/2129 [00:44<02:15, 10.49it/s]
 34%|███▎      | 715/2129 [00:44<01:57, 12.05it/s]
 34%|███▍      | 719/2129 [00:44<01:50, 12.74it/s]
 34%|███▍      | 721/2129 [00:44<01:59, 11.79it/s]
 34%|███▍      | 723/2129 [00:44<01:49, 12.86it/s]
 34%|███▍      | 725/2129 [00:45<02:07, 11.02it/s]
 34%|███▍      | 727/2129 [00:45<02:32,  9.18it/s]
 34%|███▍      | 729/2129 [00:45<02:46,  8.42it/s]
 34%|███▍      | 733/2129 [00:45<02:09, 10.74it/s]
 35%|███▍      | 736/2129 [00:46<01:46, 13.04it/s]
 35%|███▍      | 739/2129 [00:46<01:39, 13.94it/s]
 35%|███▍      | 741/2129 [00:46<02:13, 10.38it/s]
 35%|███▍      | 743/2129 [00:46<02:03, 11.24it/s]
 35%|███▌      | 750/2129 [00:47<01:36, 14.26it/s]
 35%|███▌      | 752/2129 [00:47<01:53, 12.18it/s]
 35%|███▌      | 754/2129 [00:47<02:34,  8.91it/s]
 36%|███▌      | 756/2129 [00:48<02:37,  8.72it/s]
 36%|███▌      | 758/2129 [00:48<02:47,  8.19it/s]
 36%|███▌      | 761/2129 [00:48<02:09, 10.58it/s]
 36%|███▌      | 763/2129 [00:48<02:12, 10.33it/s]
 36%|███▌      | 766/2129 [00:49<02:15, 10.05it/s]
 36%|███▌      | 768/2129 [00:49<02:29,  9.08it/s]
 36%|███▌      | 770/2129 [00:49<02:35,  8.75it/s]
 36%|███▋      | 773/2129 [00:49<01:56, 11.67it/s]
 36%|███▋      | 775/2129 [00:49<02:04, 10.88it/s]
 36%|███▋      | 777/2129 [00:50<02:27,  9.16it/s]
 37%|███▋      | 780/2129 [00:50<02:04, 10.81it/s]
 37%|███▋      | 782/2129 [00:50<02:12, 10.15it/s]
 37%|███▋      | 784/2129 [00:50<02:06, 10.63it/s]
 37%|███▋      | 786/2129 [00:51<02:39,  8.41it/s]
 37%|███▋      | 788/2129 [00:51<02:14,  9.94it/s]
 37%|███▋      | 795/2129 [00:51<01:27, 15.30it/s]
 37%|███▋      | 797/2129 [00:52<02:16,  9.78it/s]
 38%|███▊      | 799/2129 [00:52<02:09, 10.25it/s]
 38%|███▊      | 801/2129 [00:52<02:15,  9.78it/s]
 38%|███▊      | 803/2129 [00:52<02:05, 10.57it/s]
 38%|███▊      | 805/2129 [00:52<01:55, 11.49it/s]
 38%|███▊      | 808/2129 [00:52<01:31, 14.49it/s]
 38%|███▊      | 810/2129 [00:53<01:58, 11.12it/s]
 38%|███▊      | 812/2129 [00:53<02:11, 10.04it/s]
 38%|███▊      | 814/2129 [00:53<02:05, 10.48it/s]
 38%|███▊      | 816/2129 [00:53<01:48, 12.11it/s]
 38%|███▊      | 818/2129 [00:53<02:00, 10.90it/s]
 39%|███▊      | 820/2129 [00:54<02:15,  9.65it/s]
 39%|███▊      | 822/2129 [00:54<01:59, 10.91it/s]
 39%|███▉      | 827/2129 [00:54<01:33, 13.89it/s]
 39%|███▉      | 831/2129 [00:54<01:30, 14.36it/s]
 39%|███▉      | 833/2129 [00:54<01:31, 14.12it/s]
 39%|███▉      | 836/2129 [00:55<01:19, 16.30it/s]
 39%|███▉      | 839/2129 [00:55<01:08, 18.84it/s]
 40%|███▉      | 842/2129 [00:55<01:38, 13.02it/s]
 40%|███▉      | 844/2129 [00:55<01:53, 11.35it/s]
 40%|███▉      | 846/2129 [00:55<01:45, 12.16it/s]
 40%|███▉      | 848/2129 [00:56<02:12,  9.65it/s]
 40%|███▉      | 851/2129 [00:56<01:44, 12.18it/s]
 40%|████      | 853/2129 [00:56<01:57, 10.82it/s]
 40%|████      | 855/2129 [00:56<02:16,  9.32it/s]
 40%|████      | 857/2129 [00:57<02:37,  8.05it/s]
 40%|████      | 859/2129 [00:57<02:14,  9.46it/s]
 40%|████      | 862/2129 [00:57<01:44, 12.11it/s]
 41%|████      | 865/2129 [00:57<01:32, 13.72it/s]
 41%|████      | 867/2129 [00:57<01:46, 11.89it/s]
 41%|████      | 871/2129 [00:58<01:16, 16.42it/s]
 41%|████      | 874/2129 [00:58<01:25, 14.76it/s]
 41%|████      | 876/2129 [00:58<01:54, 10.95it/s]
 41%|████      | 878/2129 [00:58<01:44, 11.93it/s]
 41%|████▏     | 881/2129 [00:58<01:38, 12.66it/s]
 41%|████▏     | 883/2129 [00:59<01:34, 13.23it/s]
 42%|████▏     | 886/2129 [00:59<01:30, 13.75it/s]
 42%|████▏     | 888/2129 [00:59<01:44, 11.92it/s]
 42%|████▏     | 891/2129 [00:59<01:48, 11.40it/s]
 42%|████▏     | 894/2129 [00:59<01:27, 14.04it/s]
 42%|████▏     | 896/2129 [01:00<01:45, 11.65it/s]
 42%|████▏     | 898/2129 [01:00<01:56, 10.57it/s]
 42%|████▏     | 900/2129 [01:00<02:30,  8.14it/s]
 42%|████▏     | 902/2129 [01:01<02:29,  8.20it/s]
 43%|████▎     | 905/2129 [01:01<02:43,  7.47it/s]
 43%|████▎     | 906/2129 [01:01<02:51,  7.15it/s]
 43%|████▎     | 908/2129 [01:02<02:57,  6.88it/s]
 43%|████▎     | 909/2129 [01:02<03:20,  6.10it/s]
 43%|████▎     | 911/2129 [01:02<02:38,  7.67it/s]
 43%|████▎     | 912/2129 [01:02<02:44,  7.38it/s]
 43%|████▎     | 914/2129 [01:02<02:43,  7.42it/s]
 43%|████▎     | 917/2129 [01:02<01:55, 10.45it/s]
 43%|████▎     | 924/2129 [01:03<00:59, 20.15it/s]
 44%|████▎     | 927/2129 [01:03<01:34, 12.74it/s]
 44%|████▎     | 929/2129 [01:04<02:08,  9.30it/s]
 44%|████▎     | 931/2129 [01:04<02:01,  9.88it/s]
 44%|████▍     | 934/2129 [01:04<01:41, 11.74it/s]
 44%|████▍     | 936/2129 [01:04<01:44, 11.41it/s]
 44%|████▍     | 938/2129 [01:04<01:50, 10.74it/s]
 44%|████▍     | 940/2129 [01:05<02:10,  9.12it/s]
 44%|████▍     | 943/2129 [01:05<02:03,  9.61it/s]
 44%|████▍     | 945/2129 [01:05<02:44,  7.20it/s]
 44%|████▍     | 946/2129 [01:06<02:58,  6.63it/s]
 45%|████▍     | 948/2129 [01:06<02:29,  7.90it/s]
 45%|████▍     | 950/2129 [01:06<02:14,  8.80it/s]
 45%|████▍     | 953/2129 [01:06<01:43, 11.31it/s]
 45%|████▍     | 955/2129 [01:06<01:50, 10.60it/s]
 45%|████▍     | 957/2129 [01:07<02:29,  7.85it/s]
 45%|████▍     | 958/2129 [01:07<02:37,  7.44it/s]
 45%|████▌     | 960/2129 [01:07<02:21,  8.29it/s]
 45%|████▌     | 963/2129 [01:07<01:45, 11.05it/s]
 45%|████▌     | 967/2129 [01:07<01:12, 15.99it/s]
 46%|████▌     | 970/2129 [01:07<01:12, 16.02it/s]
 46%|████▌     | 972/2129 [01:08<01:13, 15.78it/s]
 46%|████▌     | 974/2129 [01:08<01:34, 12.23it/s]
 46%|████▌     | 976/2129 [01:08<01:26, 13.38it/s]
 46%|████▌     | 978/2129 [01:08<01:30, 12.66it/s]
 46%|████▌     | 981/2129 [01:08<01:17, 14.85it/s]
 46%|████▌     | 983/2129 [01:08<01:15, 15.10it/s]
 46%|████▋     | 985/2129 [01:09<01:11, 15.95it/s]
 46%|████▋     | 987/2129 [01:09<01:14, 15.27it/s]
 47%|████▋     | 990/2129 [01:09<01:01, 18.63it/s]
 47%|████▋     | 993/2129 [01:09<01:06, 17.02it/s]
 47%|████▋     | 996/2129 [01:09<01:00, 18.60it/s]
 47%|████▋     | 998/2129 [01:09<01:10, 16.06it/s]
 47%|████▋     | 1000/2129 [01:09<01:09, 16.31it/s]
 47%|████▋     | 1002/2129 [01:10<02:03,  9.12it/s]
 47%|████▋     | 1004/2129 [01:10<01:50, 10.21it/s]
 47%|████▋     | 1006/2129 [01:10<01:41, 11.03it/s]
 47%|████▋     | 1010/2129 [01:10<01:15, 14.90it/s]
 48%|████▊     | 1012/2129 [01:11<01:26, 12.90it/s]
 48%|████▊     | 1014/2129 [01:11<01:35, 11.66it/s]
 48%|████▊     | 1016/2129 [01:11<01:54,  9.72it/s]
 48%|████▊     | 1018/2129 [01:11<01:52,  9.91it/s]
 48%|████▊     | 1020/2129 [01:11<01:52,  9.86it/s]
 48%|████▊     | 1023/2129 [01:12<01:51,  9.90it/s]
 48%|████▊     | 1025/2129 [01:12<01:55,  9.54it/s]
 48%|████▊     | 1027/2129 [01:12<01:43, 10.64it/s]
 48%|████▊     | 1029/2129 [01:12<01:52,  9.82it/s]
 48%|████▊     | 1031/2129 [01:12<01:40, 10.92it/s]
 49%|████▊     | 1033/2129 [01:13<01:58,  9.26it/s]
 49%|████▊     | 1035/2129 [01:13<02:23,  7.62it/s]
 49%|████▊     | 1036/2129 [01:13<03:01,  6.02it/s]
 49%|████▉     | 1038/2129 [01:14<02:19,  7.82it/s]
 49%|████▉     | 1041/2129 [01:14<02:02,  8.87it/s]
 49%|████▉     | 1043/2129 [01:14<01:54,  9.46it/s]
 49%|████▉     | 1045/2129 [01:14<01:55,  9.41it/s]
 49%|████▉     | 1047/2129 [01:14<01:55,  9.35it/s]
 49%|████▉     | 1049/2129 [01:15<02:14,  8.02it/s]
 49%|████▉     | 1051/2129 [01:15<02:03,  8.74it/s]
 49%|████▉     | 1053/2129 [01:15<01:43, 10.41it/s]
 50%|████▉     | 1055/2129 [01:15<01:36, 11.09it/s]
 50%|████▉     | 1057/2129 [01:15<01:40, 10.62it/s]
 50%|████▉     | 1059/2129 [01:16<01:29, 11.95it/s]
 50%|████▉     | 1061/2129 [01:16<01:18, 13.53it/s]
 50%|████▉     | 1064/2129 [01:16<01:36, 11.06it/s]
 50%|█████     | 1066/2129 [01:16<01:34, 11.21it/s]
 50%|█████     | 1068/2129 [01:16<01:24, 12.58it/s]
 50%|█████     | 1071/2129 [01:16<01:13, 14.34it/s]
 50%|█████     | 1073/2129 [01:17<01:11, 14.83it/s]
 50%|█████     | 1075/2129 [01:17<01:31, 11.56it/s]
 51%|█████     | 1077/2129 [01:17<01:23, 12.66it/s]
 51%|█████     | 1079/2129 [01:17<01:50,  9.54it/s]
 51%|█████     | 1081/2129 [01:18<02:04,  8.40it/s]
 51%|█████     | 1083/2129 [01:18<02:48,  6.22it/s]
 51%|█████     | 1085/2129 [01:18<02:41,  6.46it/s]
 51%|█████     | 1088/2129 [01:19<01:56,  8.91it/s]
 51%|█████     | 1091/2129 [01:19<01:45,  9.82it/s]
 51%|█████▏    | 1093/2129 [01:19<01:32, 11.17it/s]
 51%|█████▏    | 1095/2129 [01:19<01:41, 10.23it/s]
 52%|█████▏    | 1097/2129 [01:19<01:27, 11.81it/s]
 52%|█████▏    | 1103/2129 [01:20<01:04, 15.95it/s]
 52%|█████▏    | 1105/2129 [01:20<01:28, 11.58it/s]
 52%|█████▏    | 1107/2129 [01:20<02:08,  7.98it/s]
 52%|█████▏    | 1109/2129 [01:21<02:08,  7.96it/s]
 52%|█████▏    | 1110/2129 [01:21<02:19,  7.28it/s]
 52%|█████▏    | 1111/2129 [01:21<02:42,  6.27it/s]
 52%|█████▏    | 1112/2129 [01:21<02:41,  6.30it/s]
 52%|█████▏    | 1113/2129 [01:21<02:43,  6.21it/s]
 52%|█████▏    | 1114/2129 [01:22<02:56,  5.75it/s]
 52%|█████▏    | 1115/2129 [01:22<03:27,  4.89it/s]
 52%|█████▏    | 1117/2129 [01:22<02:24,  6.99it/s]
 53%|█████▎    | 1118/2129 [01:22<02:35,  6.51it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 343.48it/s]
 50%|█████     | 151/300 [08:35<2:42:04, 65.27s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 3], [np.int64(2), False, 7], [np.int64(3), False, 7], [np.int64(4), False, 5], [np.int64(6), False, 10], [np.int64(8), False, 9], [np.int64(9), False, 10], [np.int64(10), False, 11], [np.int64(12), False, 10], [np.int64(13), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6270, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [08:35<1:52:49, 45.74s/it]

tensor(11.9054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6647, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9012, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7081, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [08:35<38:06, 15.77s/it]

tensor(11.9022, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7534, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7982, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [08:36<26:34, 11.07s/it]

tensor(11.9167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8496, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8929, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [08:36<09:06,  3.88s/it]

tensor(11.9239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9551, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9985, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [08:36<04:32,  1.96s/it]

tensor(11.9160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0493, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0719, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [08:36<03:14,  1.41s/it]

tensor(11.9063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1001, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1278, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [08:37<01:16,  1.78it/s]

tensor(11.8974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1625, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1882, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [08:37<00:57,  2.32it/s]

tensor(11.8810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2036, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2267, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [08:37<00:29,  4.38it/s]

tensor(11.8595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2449, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2574, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [08:37<00:25,  5.05it/s]

tensor(11.8414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2716, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2722, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [08:38<00:18,  6.82it/s]

tensor(11.8324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2860, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3059, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [08:38<00:16,  7.47it/s]

tensor(11.8295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3239, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3490, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [08:38<00:16,  7.69it/s]

tensor(11.8237, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3754, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3960, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [08:38<00:15,  8.00it/s]

tensor(11.8146, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4137, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4183, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [08:38<00:14,  8.06it/s]

tensor(11.8034, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4271, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4313, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [08:39<00:14,  8.15it/s]

tensor(11.7919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4440, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7861, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4519, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [08:39<00:14,  8.18it/s]

tensor(11.7809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4605, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4771, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [08:39<00:14,  8.11it/s]

tensor(11.7723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4845, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4919, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [08:39<00:13,  8.24it/s]

tensor(11.7652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4977, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5045, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [08:40<00:13,  8.24it/s]

tensor(11.7587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5090, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5104, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [08:40<00:13,  8.26it/s]

tensor(11.7521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5177, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5279, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [08:40<00:13,  8.08it/s]

tensor(11.7461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5361, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5387, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [08:40<00:12,  8.02it/s]

tensor(11.7406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5418, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5484, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [08:41<00:12,  7.96it/s]

tensor(11.7353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7327, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5589, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:41<00:12,  8.01it/s]

tensor(11.7306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5647, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([199, 102, 130, 145, 165, 112, 185, 141,  86, 243, 133, 166, 122, 200])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 5/2129 [00:00<00:44, 47.92it/s]
  1%|          | 11/2129 [00:00<00:39, 53.72it/s]
  1%|          | 18/2129 [00:00<00:35, 60.18it/s]
  1%|          | 25/2129 [00:00<00:38, 55.26it/s]
  1%|▏         | 31/2129 [00:00<00:43, 48.40it/s]
  2%|▏         | 37/2129 [00:00<00:42, 49.81it/s]
  2%|▏         | 43/2129 [00:00<00:46, 44.55it/s]
  2%|▏         | 49/2129 [00:00<00:43, 47.62it/s]
  3%|▎         | 54/2129 [00:01<00:49, 41.99it/s]
  3%|▎         | 60/2129 [00:01<00:45, 45.53it/s]
  3%|▎         | 66/2129 [00:01<00:42, 48.85it/s]
  3%|▎         | 72/2129 [00:01<00:45, 45.18it/s]
  4%|▎         | 77/2129 [00:01<00:52, 38.94it/s]
  4%|▍         | 85/2129 [00:01<00:42, 48.14it/s]
  4%|▍         | 91/2129 [00:01<00:40, 50.49it/s]
  5%|▍         | 97/2129 [00:02<00:39, 51.45it/s]
  5%|▍         | 104/2129 [00:02<00:36, 54.88it/s]
  5%|▌         | 110/2129 [00:02<00:45, 44.47it/s]
  5%|▌         | 115/2129 [00:02<00:45, 44.60it/s]
  6%|▌         | 121/2129 [00:02<00:41, 47.83it/s]
  6%|▌         | 129/2129 [00:02<00:39, 50.55it/s]
  6%|▋         | 135/2129 [00:02<00:38, 51.24it/s]
  7%|▋         | 142/2129 [00:02<00:36, 53.85it/s]
  7%|▋         | 148/2129 [00:03<00:36, 54.15it/s]
  7%|▋         | 154/2129 [00:03<00:36, 53.50it/s]
  8%|▊         | 162/2129 [00:03<00:34, 57.79it/s]
  8%|▊         | 168/2129 [00:03<00:42, 46.56it/s]
  8%|▊         | 174/2129 [00:03<00:42, 45.55it/s]
  8%|▊         | 179/2129 [00:03<00:45, 43.01it/s]
  9%|▊         | 185/2129 [00:03<00:43, 44.98it/s]
  9%|▉         | 190/2129 [00:03<00:41, 46.18it/s]
  9%|▉         | 195/2129 [00:04<00:42, 45.52it/s]
  9%|▉         | 202/2129 [00:04<00:37, 51.28it/s]
 10%|▉         | 209/2129 [00:04<00:34, 55.62it/s]
 10%|█         | 216/2129 [00:04<00:32, 58.43it/s]
 10%|█         | 223/2129 [00:04<00:32, 59.52it/s]
 11%|█         | 230/2129 [00:04<00:31, 59.74it/s]
 11%|█         | 237/2129 [00:04<00:32, 58.03it/s]
 12%|█▏        | 245/2129 [00:04<00:30, 62.19it/s]
 12%|█▏        | 252/2129 [00:04<00:30, 61.58it/s]
 12%|█▏        | 259/2129 [00:05<00:30, 60.75it/s]
 12%|█▏        | 266/2129 [00:05<00:30, 61.58it/s]
 13%|█▎        | 273/2129 [00:05<00:30, 61.36it/s]
 13%|█▎        | 280/2129 [00:05<00:30, 61.12it/s]
 13%|█▎        | 287/2129 [00:05<00:29, 61.65it/s]
 14%|█▍        | 294/2129 [00:05<00:29, 62.23it/s]
 14%|█▍        | 301/2129 [00:05<00:30, 60.73it/s]
 14%|█▍        | 308/2129 [00:05<00:34, 53.33it/s]
 15%|█▍        | 314/2129 [00:06<00:44, 40.35it/s]
 15%|█▌        | 322/2129 [00:06<00:38, 47.38it/s]
 15%|█▌        | 329/2129 [00:06<00:34, 51.53it/s]
 16%|█▌        | 336/2129 [00:06<00:32, 55.34it/s]
 16%|█▌        | 343/2129 [00:06<00:32, 55.79it/s]
 16%|█▋        | 349/2129 [00:06<00:36, 48.46it/s]
 17%|█▋        | 356/2129 [00:06<00:33, 52.69it/s]
 17%|█▋        | 362/2129 [00:07<00:33, 53.48it/s]
 17%|█▋        | 370/2129 [00:07<00:29, 59.14it/s]
 18%|█▊        | 377/2129 [00:07<00:33, 52.76it/s]
 18%|█▊        | 383/2129 [00:07<00:32, 53.08it/s]
 18%|█▊        | 389/2129 [00:07<00:35, 48.76it/s]
 19%|█▊        | 396/2129 [00:07<00:32, 52.62it/s]
 19%|█▉        | 402/2129 [00:07<00:36, 46.84it/s]
 19%|█▉        | 409/2129 [00:07<00:33, 51.72it/s]
 19%|█▉        | 415/2129 [00:08<00:34, 50.00it/s]
 20%|█▉        | 422/2129 [00:08<00:31, 53.86it/s]
 20%|██        | 429/2129 [00:08<00:29, 57.41it/s]
 20%|██        | 435/2129 [00:08<00:33, 50.42it/s]
 21%|██        | 441/2129 [00:08<00:36, 46.21it/s]
 21%|██        | 448/2129 [00:08<00:33, 50.13it/s]
 21%|██▏       | 454/2129 [00:08<00:34, 48.79it/s]
 22%|██▏       | 460/2129 [00:08<00:35, 47.54it/s]
 22%|██▏       | 466/2129 [00:09<00:33, 49.88it/s]
 22%|██▏       | 472/2129 [00:09<00:41, 39.66it/s]
 22%|██▏       | 479/2129 [00:09<00:35, 46.12it/s]
 23%|██▎       | 486/2129 [00:09<00:32, 49.90it/s]
 23%|██▎       | 492/2129 [00:09<00:31, 51.42it/s]
 23%|██▎       | 498/2129 [00:09<00:40, 40.60it/s]
 24%|██▎       | 503/2129 [00:10<00:46, 35.08it/s]
 24%|██▍       | 510/2129 [00:10<00:39, 41.44it/s]
 24%|██▍       | 516/2129 [00:10<00:35, 45.20it/s]
 25%|██▍       | 522/2129 [00:10<00:38, 41.79it/s]
 25%|██▍       | 528/2129 [00:10<00:35, 44.69it/s]
 25%|██▌       | 535/2129 [00:10<00:31, 50.04it/s]
 25%|██▌       | 541/2129 [00:10<00:36, 44.09it/s]
 26%|██▌       | 547/2129 [00:10<00:33, 47.46it/s]
 26%|██▌       | 555/2129 [00:11<00:29, 52.58it/s]
 26%|██▋       | 561/2129 [00:11<00:34, 46.10it/s]
 27%|██▋       | 568/2129 [00:11<00:31, 50.04it/s]
 27%|██▋       | 574/2129 [00:11<00:29, 52.44it/s]
 27%|██▋       | 580/2129 [00:11<00:35, 43.86it/s]
 27%|██▋       | 585/2129 [00:11<00:42, 36.08it/s]
 28%|██▊       | 591/2129 [00:11<00:38, 40.44it/s]
 28%|██▊       | 598/2129 [00:12<00:33, 46.06it/s]
 28%|██▊       | 605/2129 [00:12<00:29, 51.53it/s]
 29%|██▊       | 612/2129 [00:12<00:27, 54.80it/s]
 29%|██▉       | 619/2129 [00:12<00:25, 58.31it/s]
 29%|██▉       | 626/2129 [00:12<00:25, 59.92it/s]
 30%|██▉       | 633/2129 [00:12<00:24, 60.71it/s]
 30%|███       | 640/2129 [00:12<00:26, 56.18it/s]
 30%|███       | 646/2129 [00:12<00:26, 56.01it/s]
 31%|███       | 653/2129 [00:12<00:25, 57.70it/s]
 31%|███       | 659/2129 [00:13<00:27, 52.83it/s]
 31%|███       | 665/2129 [00:13<00:30, 48.11it/s]
 32%|███▏      | 671/2129 [00:13<00:28, 50.28it/s]
 32%|███▏      | 677/2129 [00:13<00:40, 36.17it/s]
 32%|███▏      | 682/2129 [00:13<00:40, 35.47it/s]
 32%|███▏      | 687/2129 [00:13<00:37, 38.46it/s]
 33%|███▎      | 694/2129 [00:13<00:32, 44.30it/s]
 33%|███▎      | 701/2129 [00:14<00:28, 49.87it/s]
 33%|███▎      | 708/2129 [00:14<00:27, 52.51it/s]
 34%|███▎      | 714/2129 [00:14<00:27, 51.75it/s]
 34%|███▍      | 721/2129 [00:14<00:25, 54.37it/s]
 34%|███▍      | 727/2129 [00:14<00:25, 55.42it/s]
 34%|███▍      | 734/2129 [00:14<00:24, 57.86it/s]
 35%|███▍      | 740/2129 [00:14<00:27, 50.79it/s]
 35%|███▌      | 746/2129 [00:14<00:27, 49.68it/s]
 35%|███▌      | 752/2129 [00:15<00:33, 41.09it/s]
 36%|███▌      | 759/2129 [00:15<00:29, 46.44it/s]
 36%|███▌      | 766/2129 [00:15<00:27, 50.45it/s]
 36%|███▋      | 772/2129 [00:15<00:25, 52.58it/s]
 37%|███▋      | 778/2129 [00:15<00:30, 44.53it/s]
 37%|███▋      | 784/2129 [00:15<00:28, 47.90it/s]
 37%|███▋      | 791/2129 [00:15<00:25, 51.48it/s]
 37%|███▋      | 798/2129 [00:15<00:23, 56.08it/s]
 38%|███▊      | 805/2129 [00:16<00:22, 58.05it/s]
 38%|███▊      | 812/2129 [00:16<00:23, 56.41it/s]
 38%|███▊      | 818/2129 [00:16<00:22, 57.31it/s]
 39%|███▉      | 826/2129 [00:16<00:21, 61.27it/s]
 39%|███▉      | 833/2129 [00:16<00:26, 49.31it/s]
 39%|███▉      | 839/2129 [00:16<00:24, 51.60it/s]
 40%|███▉      | 845/2129 [00:16<00:26, 48.43it/s]
 40%|███▉      | 851/2129 [00:17<00:26, 47.68it/s]
 40%|████      | 856/2129 [00:17<00:29, 43.72it/s]
 40%|████      | 862/2129 [00:17<00:27, 46.50it/s]
 41%|████      | 867/2129 [00:17<00:28, 44.34it/s]
 41%|████      | 874/2129 [00:17<00:25, 48.73it/s]
 41%|████▏     | 881/2129 [00:17<00:24, 51.85it/s]
 42%|████▏     | 887/2129 [00:17<00:23, 51.97it/s]
 42%|████▏     | 893/2129 [00:17<00:28, 43.84it/s]
 42%|████▏     | 898/2129 [00:18<00:27, 44.45it/s]
 43%|████▎     | 905/2129 [00:18<00:24, 50.18it/s]
 43%|████▎     | 912/2129 [00:18<00:22, 54.26it/s]
 43%|████▎     | 918/2129 [00:18<00:22, 53.56it/s]
 43%|████▎     | 924/2129 [00:18<00:22, 53.38it/s]
 44%|████▎     | 930/2129 [00:18<00:26, 45.49it/s]
 44%|████▍     | 938/2129 [00:18<00:22, 52.71it/s]
 44%|████▍     | 944/2129 [00:18<00:23, 49.68it/s]
 45%|████▍     | 950/2129 [00:19<00:23, 50.47it/s]
 45%|████▍     | 956/2129 [00:19<00:22, 52.05it/s]
 45%|████▌     | 962/2129 [00:19<00:24, 48.27it/s]
 45%|████▌     | 968/2129 [00:19<00:23, 48.56it/s]
 46%|████▌     | 973/2129 [00:19<00:25, 45.46it/s]
 46%|████▌     | 978/2129 [00:19<00:25, 45.68it/s]
 46%|████▌     | 983/2129 [00:19<00:26, 42.95it/s]
 46%|████▋     | 988/2129 [00:19<00:25, 44.45it/s]
 47%|████▋     | 993/2129 [00:19<00:26, 43.18it/s]
 47%|████▋     | 998/2129 [00:20<00:25, 44.15it/s]
 47%|████▋     | 1003/2129 [00:20<00:28, 39.54it/s]
 47%|████▋     | 1008/2129 [00:20<00:34, 32.39it/s]
 48%|████▊     | 1014/2129 [00:20<00:29, 37.66it/s]
 48%|████▊     | 1020/2129 [00:20<00:26, 42.04it/s]
 48%|████▊     | 1027/2129 [00:20<00:23, 47.76it/s]
 49%|████▊     | 1034/2129 [00:20<00:21, 51.74it/s]
 49%|████▉     | 1042/2129 [00:21<00:18, 57.76it/s]
 49%|████▉     | 1049/2129 [00:21<00:17, 60.03it/s]
 50%|████▉     | 1056/2129 [00:21<00:21, 50.06it/s]
 50%|████▉     | 1063/2129 [00:21<00:19, 53.51it/s]
 50%|█████     | 1070/2129 [00:21<00:18, 56.65it/s]
 51%|█████     | 1076/2129 [00:21<00:18, 55.51it/s]
 51%|█████     | 1082/2129 [00:21<00:19, 54.83it/s]
 51%|█████     | 1088/2129 [00:21<00:22, 45.76it/s]
 51%|█████▏    | 1093/2129 [00:22<00:22, 46.05it/s]
 52%|█████▏    | 1100/2129 [00:22<00:19, 51.52it/s]
 52%|█████▏    | 1106/2129 [00:22<00:19, 53.71it/s]
 52%|█████▏    | 1113/2129 [00:22<00:17, 57.07it/s]
 53%|█████▎    | 1119/2129 [00:22<00:17, 57.49it/s]
 53%|█████▎    | 1125/2129 [00:22<00:18, 55.44it/s]
 53%|█████▎    | 1131/2129 [00:22<00:24, 41.12it/s]
 53%|█████▎    | 1136/2129 [00:22<00:23, 41.41it/s]
 54%|█████▎    | 1141/2129 [00:23<00:25, 38.67it/s]
 54%|█████▍    | 1147/2129 [00:23<00:23, 42.42it/s]
 54%|█████▍    | 1152/2129 [00:23<00:33, 29.50it/s]
 54%|█████▍    | 1157/2129 [00:23<00:29, 32.84it/s]
 55%|█████▍    | 1161/2129 [00:23<00:30, 31.79it/s]
 55%|█████▍    | 1166/2129 [00:23<00:27, 35.46it/s]
 55%|█████▍    | 1170/2129 [00:23<00:26, 36.17it/s]
 55%|█████▌    | 1175/2129 [00:24<00:24, 39.53it/s]
 56%|█████▌    | 1182/2129 [00:24<00:20, 45.20it/s]
 56%|█████▌    | 1189/2129 [00:24<00:18, 50.64it/s]
 56%|█████▌    | 1196/2129 [00:24<00:17, 52.99it/s]
 57%|█████▋    | 1203/2129 [00:24<00:16, 56.01it/s]
 57%|█████▋    | 1209/2129 [00:24<00:17, 54.09it/s]
 57%|█████▋    | 1216/2129 [00:24<00:16, 56.61it/s]
 57%|█████▋    | 1222/2129 [00:24<00:15, 56.79it/s]
 58%|█████▊    | 1228/2129 [00:24<00:16, 55.79it/s]
 58%|█████▊    | 1234/2129 [00:25<00:16, 53.60it/s]
 58%|█████▊    | 1240/2129 [00:25<00:16, 53.94it/s]
 59%|█████▊    | 1247/2129 [00:25<00:15, 57.15it/s]
 59%|█████▉    | 1253/2129 [00:25<00:19, 43.92it/s]
 59%|█████▉    | 1258/2129 [00:25<00:25, 34.68it/s]
 59%|█████▉    | 1263/2129 [00:25<00:24, 35.65it/s]
 60%|█████▉    | 1268/2129 [00:26<00:22, 38.15it/s]
 60%|█████▉    | 1274/2129 [00:26<00:19, 42.92it/s]
 60%|██████    | 1279/2129 [00:26<00:20, 41.12it/s]
 60%|██████    | 1285/2129 [00:26<00:18, 45.56it/s]
 61%|██████    | 1292/2129 [00:26<00:18, 45.20it/s]
 61%|██████    | 1297/2129 [00:26<00:18, 46.04it/s]
 61%|██████    | 1302/2129 [00:26<00:19, 42.70it/s]
 61%|██████▏   | 1308/2129 [00:26<00:17, 45.84it/s]
 62%|██████▏   | 1315/2129 [00:26<00:16, 50.39it/s]
 62%|██████▏   | 1321/2129 [00:27<00:15, 50.70it/s]
 62%|██████▏   | 1328/2129 [00:27<00:15, 52.85it/s]
 63%|██████▎   | 1335/2129 [00:27<00:14, 56.04it/s]
 63%|██████▎   | 1341/2129 [00:27<00:15, 51.28it/s]
 63%|██████▎   | 1347/2129 [00:27<00:15, 51.89it/s]
 64%|██████▎   | 1353/2129 [00:27<00:14, 51.74it/s]
 64%|██████▍   | 1360/2129 [00:27<00:13, 55.71it/s]
 64%|██████▍   | 1366/2129 [00:27<00:15, 50.44it/s]
 64%|██████▍   | 1372/2129 [00:28<00:15, 47.56it/s]
 65%|██████▍   | 1377/2129 [00:28<00:16, 46.17it/s]
 65%|██████▍   | 1383/2129 [00:28<00:16, 44.41it/s]
 65%|██████▌   | 1388/2129 [00:28<00:17, 43.46it/s]
 66%|██████▌   | 1396/2129 [00:28<00:14, 51.27it/s]
 66%|██████▌   | 1402/2129 [00:28<00:13, 52.68it/s]
 66%|██████▌   | 1408/2129 [00:28<00:13, 51.82it/s]
 66%|██████▋   | 1414/2129 [00:28<00:13, 52.22it/s]
 67%|██████▋   | 1420/2129 [00:29<00:13, 53.60it/s]
 67%|██████▋   | 1426/2129 [00:29<00:13, 53.75it/s]
 67%|██████▋   | 1432/2129 [00:29<00:13, 51.10it/s]
 68%|██████▊   | 1438/2129 [00:29<00:15, 44.87it/s]
 68%|██████▊   | 1443/2129 [00:29<00:15, 43.34it/s]
 68%|██████▊   | 1448/2129 [00:29<00:16, 41.65it/s]
 68%|██████▊   | 1455/2129 [00:29<00:13, 48.48it/s]
 69%|██████▊   | 1462/2129 [00:29<00:12, 53.88it/s]
 69%|██████▉   | 1470/2129 [00:30<00:10, 60.52it/s]
 69%|██████▉   | 1477/2129 [00:30<00:10, 59.89it/s]
 70%|██████▉   | 1484/2129 [00:30<00:10, 60.00it/s]
 70%|███████   | 1491/2129 [00:30<00:10, 60.55it/s]
 70%|███████   | 1498/2129 [00:30<00:10, 57.42it/s]
 71%|███████   | 1506/2129 [00:30<00:10, 61.11it/s]
 71%|███████   | 1513/2129 [00:30<00:10, 57.75it/s]
 71%|███████▏  | 1520/2129 [00:30<00:10, 59.10it/s]
 72%|███████▏  | 1526/2129 [00:30<00:10, 56.65it/s]
 72%|███████▏  | 1532/2129 [00:31<00:10, 54.52it/s]
 72%|███████▏  | 1538/2129 [00:31<00:11, 53.14it/s]
 73%|███████▎  | 1544/2129 [00:31<00:10, 53.62it/s]
 73%|███████▎  | 1550/2129 [00:31<00:10, 54.13it/s]
 73%|███████▎  | 1557/2129 [00:31<00:10, 56.91it/s]
 73%|███████▎  | 1563/2129 [00:31<00:09, 57.09it/s]
 74%|███████▎  | 1569/2129 [00:31<00:09, 57.37it/s]
 74%|███████▍  | 1575/2129 [00:32<00:13, 39.75it/s]
 74%|███████▍  | 1582/2129 [00:32<00:12, 45.37it/s]
 75%|███████▍  | 1588/2129 [00:32<00:12, 41.90it/s]
 75%|███████▍  | 1594/2129 [00:32<00:11, 45.64it/s]
 75%|███████▌  | 1600/2129 [00:32<00:11, 47.40it/s]
 75%|███████▌  | 1606/2129 [00:32<00:11, 46.07it/s]
 76%|███████▌  | 1611/2129 [00:32<00:12, 39.89it/s]
 76%|███████▌  | 1617/2129 [00:32<00:11, 43.88it/s]
 76%|███████▌  | 1622/2129 [00:33<00:12, 41.88it/s]
 77%|███████▋  | 1630/2129 [00:33<00:10, 48.50it/s]
 77%|███████▋  | 1636/2129 [00:33<00:09, 51.22it/s]
 77%|███████▋  | 1642/2129 [00:33<00:10, 48.69it/s]
 77%|███████▋  | 1648/2129 [00:33<00:11, 42.51it/s]
 78%|███████▊  | 1653/2129 [00:33<00:12, 38.24it/s]
 78%|███████▊  | 1658/2129 [00:33<00:11, 40.60it/s]
 78%|███████▊  | 1663/2129 [00:33<00:11, 40.80it/s]
 78%|███████▊  | 1668/2129 [00:34<00:10, 42.99it/s]
 79%|███████▊  | 1673/2129 [00:34<00:12, 35.40it/s]
 79%|███████▉  | 1679/2129 [00:34<00:11, 40.77it/s]
 79%|███████▉  | 1685/2129 [00:34<00:10, 43.55it/s]
 79%|███████▉  | 1691/2129 [00:34<00:09, 47.18it/s]
 80%|███████▉  | 1697/2129 [00:34<00:08, 49.00it/s]
 80%|████████  | 1704/2129 [00:34<00:07, 53.77it/s]
 80%|████████  | 1711/2129 [00:34<00:07, 57.51it/s]
 81%|████████  | 1717/2129 [00:35<00:07, 56.77it/s]
 81%|████████  | 1724/2129 [00:35<00:06, 58.36it/s]
 81%|████████▏ | 1730/2129 [00:35<00:07, 56.92it/s]
 82%|████████▏ | 1737/2129 [00:35<00:06, 56.74it/s]
 82%|████████▏ | 1743/2129 [00:35<00:07, 54.71it/s]
 82%|████████▏ | 1750/2129 [00:35<00:06, 58.30it/s]
 83%|████████▎ | 1757/2129 [00:35<00:06, 61.07it/s]
 83%|████████▎ | 1764/2129 [00:35<00:06, 57.95it/s]
 83%|████████▎ | 1770/2129 [00:36<00:07, 50.45it/s]
 83%|████████▎ | 1776/2129 [00:36<00:09, 37.74it/s]
 84%|████████▎ | 1781/2129 [00:36<00:10, 33.57it/s]
 84%|████████▍ | 1785/2129 [00:36<00:10, 34.15it/s]
 84%|████████▍ | 1791/2129 [00:36<00:08, 39.26it/s]
 84%|████████▍ | 1797/2129 [00:36<00:08, 40.88it/s]
 85%|████████▍ | 1802/2129 [00:36<00:08, 39.24it/s]
 85%|████████▍ | 1807/2129 [00:37<00:08, 36.30it/s]
 85%|████████▌ | 1812/2129 [00:37<00:08, 38.95it/s]
 85%|████████▌ | 1818/2129 [00:37<00:07, 42.42it/s]
 86%|████████▌ | 1824/2129 [00:37<00:06, 44.87it/s]
 86%|████████▌ | 1829/2129 [00:37<00:07, 42.50it/s]
 86%|████████▌ | 1834/2129 [00:37<00:06, 42.16it/s]
 86%|████████▋ | 1839/2129 [00:37<00:07, 39.99it/s]
 87%|████████▋ | 1844/2129 [00:38<00:07, 39.26it/s]
 87%|████████▋ | 1849/2129 [00:38<00:07, 38.93it/s]
 87%|████████▋ | 1854/2129 [00:38<00:06, 41.53it/s]
 87%|████████▋ | 1860/2129 [00:38<00:06, 41.99it/s]
 88%|████████▊ | 1866/2129 [00:38<00:05, 46.41it/s]
 88%|████████▊ | 1872/2129 [00:38<00:05, 48.96it/s]
 88%|████████▊ | 1877/2129 [00:38<00:05, 43.83it/s]
 88%|████████▊ | 1883/2129 [00:38<00:05, 46.28it/s]
 89%|████████▊ | 1888/2129 [00:38<00:05, 46.53it/s]
 89%|████████▉ | 1895/2129 [00:39<00:04, 52.25it/s]
 89%|████████▉ | 1901/2129 [00:39<00:04, 53.25it/s]
 90%|████████▉ | 1907/2129 [00:39<00:04, 45.58it/s]
 90%|████████▉ | 1913/2129 [00:39<00:04, 48.72it/s]
 90%|█████████ | 1919/2129 [00:39<00:04, 50.54it/s]
 90%|█████████ | 1925/2129 [00:39<00:03, 52.78it/s]
 91%|█████████ | 1931/2129 [00:39<00:03, 51.51it/s]
 91%|█████████ | 1937/2129 [00:39<00:04, 43.21it/s]
 91%|█████████ | 1942/2129 [00:40<00:05, 32.93it/s]
 91%|█████████▏| 1947/2129 [00:40<00:05, 35.54it/s]
 92%|█████████▏| 1955/2129 [00:40<00:03, 43.77it/s]
 92%|█████████▏| 1960/2129 [00:40<00:04, 39.23it/s]
 92%|█████████▏| 1965/2129 [00:40<00:04, 40.19it/s]
 93%|█████████▎| 1971/2129 [00:40<00:03, 43.91it/s]
 93%|█████████▎| 1977/2129 [00:40<00:03, 45.98it/s]
 93%|█████████▎| 1982/2129 [00:41<00:03, 46.98it/s]
 93%|█████████▎| 1988/2129 [00:41<00:02, 49.33it/s]
 94%|█████████▎| 1994/2129 [00:41<00:02, 49.86it/s]
 94%|█████████▍| 2000/2129 [00:41<00:02, 52.50it/s]
 94%|█████████▍| 2006/2129 [00:41<00:03, 40.80it/s]
 95%|█████████▍| 2012/2129 [00:41<00:02, 44.17it/s]
 95%|█████████▍| 2017/2129 [00:41<00:02, 45.05it/s]
 95%|█████████▍| 2022/2129 [00:41<00:02, 44.07it/s]
 95%|█████████▌| 2027/2129 [00:42<00:02, 36.67it/s]
 96%|█████████▌| 2034/2129 [00:42<00:02, 44.26it/s]
 96%|█████████▌| 2040/2129 [00:42<00:01, 46.05it/s]
 96%|█████████▌| 2045/2129 [00:42<00:02, 39.94it/s]
 96%|█████████▋| 2051/2129 [00:42<00:01, 44.23it/s]
 97%|█████████▋| 2056/2129 [00:42<00:01, 41.71it/s]
 97%|█████████▋| 2061/2129 [00:42<00:01, 40.38it/s]
 97%|█████████▋| 2067/2129 [00:43<00:01, 44.05it/s]
 97%|█████████▋| 2072/2129 [00:43<00:01, 43.72it/s]
 98%|█████████▊| 2078/2129 [00:43<00:01, 46.25it/s]
 98%|█████████▊| 2084/2129 [00:43<00:00, 48.38it/s]
 98%|█████████▊| 2090/2129 [00:43<00:00, 50.60it/s]
 98%|█████████▊| 2096/2129 [00:43<00:00, 46.70it/s]
 99%|█████████▊| 2101/2129 [00:43<00:00, 46.85it/s]
 99%|█████████▉| 2106/2129 [00:43<00:00, 44.81it/s]
 99%|█████████▉| 2112/2129 [00:43<00:00, 46.92it/s]
 99%|█████████▉| 2117/2129 [00:44<00:00, 47.71it/s]
100%|█████████▉| 2122/2129 [00:44<00:00, 47.48it/s]
100%|██████████| 2129/2129 [00:44<00:00, 48.08it/s]
/kaggle/working/PRAGA/clustering_utils.py:173: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return log_Hastings_ratio_split(1.0, torch.tensor(N_k_1), torch.tensor(N_k_2), log_ll_k1, log_ll_k2, log_ll_k, split_prob=0.1)

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 343.81it/s]
 67%|██████▋   | 201/300 [09:28<23:24, 14.18s/it]

[[np.int64(0), False, 4], [np.int64(1), False, 11], [np.int64(2), False, 0], [np.int64(3), False, 11], [np.int64(5), False, 10], [np.int64(6), False, 11], [np.int64(7), False, 3], [np.int64(8), False, 10], [np.int64(9), False, 13], [np.int64(12), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4442, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [09:28<16:17,  9.98s/it]

tensor(11.7264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5491, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7228, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:28<05:32,  3.50s/it]

tensor(11.7296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5021, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6930, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [09:29<02:45,  1.78s/it]

tensor(11.7503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9735, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0376, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0493, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:29<01:24,  1.07it/s]

tensor(11.7918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9320, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0420, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8598, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:29<00:46,  1.93it/s]

tensor(11.7873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8113, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0404, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9332, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:29<00:27,  3.17it/s]

tensor(11.7525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0422, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0197, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7444, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0451, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1184, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [09:30<00:22,  3.89it/s]

tensor(11.7454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0476, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1712, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0485, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1898, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [09:30<00:15,  5.28it/s]

tensor(11.7623, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0478, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2115, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0461, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2232, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:30<00:11,  6.84it/s]

tensor(11.7588, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2312, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0420, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2451, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [09:30<00:10,  7.29it/s]

tensor(11.7341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2510, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2607, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [09:31<00:10,  7.71it/s]

tensor(11.7288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2681, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:31<00:09,  8.04it/s]

tensor(11.7320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2757, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2830, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:31<00:08,  8.17it/s]

tensor(11.7211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2923, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7121, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2975, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:31<00:08,  8.23it/s]

tensor(11.7036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3020, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3065, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [09:32<00:08,  8.24it/s]

tensor(11.6938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3121, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6928, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3146, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [09:32<00:08,  8.22it/s]

tensor(11.6931, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3197, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3204, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [09:32<00:08,  8.20it/s]

tensor(11.6905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3235, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [09:32<00:07,  8.21it/s]

tensor(11.6825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3241, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3259, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:33<00:07,  8.20it/s]

tensor(11.6790, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3239, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3248, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [09:33<00:07,  8.21it/s]

tensor(11.6762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3263, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3287, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:33<00:06,  8.20it/s]

tensor(11.6717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3304, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3279, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:33<00:06,  8.23it/s]

tensor(11.6656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3335, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3377, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [09:33<00:06,  8.25it/s]

tensor(11.6612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3412, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3447, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [09:34<00:06,  8.22it/s]

tensor(11.6583, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3444, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3437, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [09:34<00:06,  8.14it/s]

tensor(11.6552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3436, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([211, 138,  76, 157, 121, 114, 121, 209, 174, 243, 141, 166, 148, 110])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:28, 23.94it/s]
  0%|          | 10/2129 [00:00<00:45, 46.42it/s]
  1%|          | 15/2129 [00:00<00:48, 43.42it/s]
  1%|          | 23/2129 [00:00<00:38, 54.72it/s]
  1%|▏         | 29/2129 [00:00<00:42, 49.22it/s]
  2%|▏         | 35/2129 [00:00<00:40, 52.07it/s]
  2%|▏         | 41/2129 [00:00<00:50, 41.65it/s]
  2%|▏         | 48/2129 [00:01<00:43, 48.29it/s]
  3%|▎         | 55/2129 [00:01<00:39, 53.13it/s]
  3%|▎         | 62/2129 [00:01<00:36, 56.24it/s]
  3%|▎         | 69/2129 [00:01<00:34, 59.76it/s]
  4%|▎         | 76/2129 [00:01<00:32, 62.34it/s]
  4%|▍         | 83/2129 [00:01<00:32, 63.21it/s]
  4%|▍         | 91/2129 [00:01<00:31, 64.84it/s]
  5%|▍         | 98/2129 [00:01<00:32, 62.51it/s]
  5%|▍         | 105/2129 [00:01<00:33, 60.07it/s]
  5%|▌         | 112/2129 [00:02<00:32, 61.53it/s]
  6%|▌         | 119/2129 [00:02<00:32, 61.80it/s]
  6%|▌         | 127/2129 [00:02<00:30, 65.49it/s]
  6%|▋         | 134/2129 [00:02<00:31, 64.32it/s]
  7%|▋         | 142/2129 [00:02<00:29, 68.30it/s]
  7%|▋         | 149/2129 [00:02<00:29, 67.64it/s]
  7%|▋         | 156/2129 [00:02<00:29, 67.15it/s]
  8%|▊         | 164/2129 [00:02<00:28, 69.02it/s]
  8%|▊         | 171/2129 [00:02<00:35, 54.95it/s]
  8%|▊         | 178/2129 [00:03<00:33, 57.64it/s]
  9%|▊         | 185/2129 [00:03<00:39, 49.55it/s]
  9%|▉         | 193/2129 [00:03<00:35, 55.25it/s]
  9%|▉         | 200/2129 [00:03<00:32, 58.52it/s]
 10%|▉         | 207/2129 [00:03<00:40, 47.28it/s]
 10%|█         | 213/2129 [00:03<00:39, 48.36it/s]
 10%|█         | 220/2129 [00:03<00:36, 52.23it/s]
 11%|█         | 226/2129 [00:04<00:45, 42.14it/s]
 11%|█         | 231/2129 [00:04<00:48, 39.14it/s]
 11%|█         | 236/2129 [00:04<00:48, 39.25it/s]
 11%|█▏        | 243/2129 [00:04<00:41, 45.49it/s]
 12%|█▏        | 250/2129 [00:04<00:37, 49.96it/s]
 12%|█▏        | 258/2129 [00:04<00:33, 55.17it/s]
 12%|█▏        | 265/2129 [00:04<00:33, 56.27it/s]
 13%|█▎        | 272/2129 [00:04<00:31, 58.68it/s]
 13%|█▎        | 279/2129 [00:05<00:30, 60.52it/s]
 13%|█▎        | 286/2129 [00:05<00:29, 62.83it/s]
 14%|█▍        | 293/2129 [00:05<00:29, 62.92it/s]
 14%|█▍        | 301/2129 [00:05<00:27, 66.77it/s]
 14%|█▍        | 308/2129 [00:05<00:33, 54.31it/s]
 15%|█▍        | 314/2129 [00:05<00:33, 53.67it/s]
 15%|█▌        | 321/2129 [00:05<00:32, 56.06it/s]
 15%|█▌        | 327/2129 [00:05<00:32, 55.28it/s]
 16%|█▌        | 333/2129 [00:06<00:32, 55.34it/s]
 16%|█▌        | 339/2129 [00:06<00:32, 55.10it/s]
 16%|█▌        | 345/2129 [00:06<00:32, 55.38it/s]
 16%|█▋        | 351/2129 [00:06<00:32, 55.33it/s]
 17%|█▋        | 358/2129 [00:06<00:30, 58.48it/s]
 17%|█▋        | 366/2129 [00:06<00:28, 62.00it/s]
 18%|█▊        | 373/2129 [00:06<00:27, 62.74it/s]
 18%|█▊        | 380/2129 [00:06<00:29, 59.88it/s]
 18%|█▊        | 387/2129 [00:06<00:29, 59.52it/s]
 19%|█▊        | 394/2129 [00:07<00:28, 60.77it/s]
 19%|█▉        | 401/2129 [00:07<00:28, 59.79it/s]
 19%|█▉        | 407/2129 [00:07<00:35, 48.10it/s]
 19%|█▉        | 414/2129 [00:07<00:32, 52.44it/s]
 20%|█▉        | 421/2129 [00:07<00:30, 55.79it/s]
 20%|██        | 427/2129 [00:07<00:30, 56.65it/s]
 20%|██        | 433/2129 [00:07<00:30, 54.95it/s]
 21%|██        | 440/2129 [00:07<00:28, 58.24it/s]
 21%|██        | 448/2129 [00:08<00:27, 61.35it/s]
 21%|██▏       | 455/2129 [00:08<00:27, 61.83it/s]
 22%|██▏       | 462/2129 [00:08<00:27, 60.98it/s]
 22%|██▏       | 469/2129 [00:08<00:27, 59.92it/s]
 22%|██▏       | 476/2129 [00:08<00:30, 54.58it/s]
 23%|██▎       | 482/2129 [00:08<00:30, 53.84it/s]
 23%|██▎       | 488/2129 [00:08<00:30, 53.78it/s]
 23%|██▎       | 494/2129 [00:08<00:31, 51.79it/s]
 24%|██▎       | 502/2129 [00:08<00:27, 58.28it/s]
 24%|██▍       | 508/2129 [00:09<00:29, 55.12it/s]
 24%|██▍       | 515/2129 [00:09<00:27, 58.44it/s]
 24%|██▍       | 521/2129 [00:09<00:34, 47.05it/s]
 25%|██▍       | 528/2129 [00:09<00:31, 51.30it/s]
 25%|██▌       | 536/2129 [00:09<00:28, 55.70it/s]
 25%|██▌       | 542/2129 [00:09<00:34, 46.59it/s]
 26%|██▌       | 548/2129 [00:09<00:32, 48.60it/s]
 26%|██▌       | 554/2129 [00:10<00:35, 44.49it/s]
 26%|██▋       | 559/2129 [00:10<00:38, 40.34it/s]
 26%|██▋       | 564/2129 [00:10<00:38, 40.77it/s]
 27%|██▋       | 569/2129 [00:10<00:36, 42.18it/s]
 27%|██▋       | 574/2129 [00:10<00:36, 42.71it/s]
 27%|██▋       | 582/2129 [00:10<00:30, 51.30it/s]
 28%|██▊       | 588/2129 [00:10<00:29, 52.67it/s]
 28%|██▊       | 594/2129 [00:11<00:43, 35.15it/s]
 28%|██▊       | 601/2129 [00:11<00:36, 41.33it/s]
 28%|██▊       | 606/2129 [00:11<00:37, 40.44it/s]
 29%|██▉       | 613/2129 [00:11<00:35, 42.40it/s]
 29%|██▉       | 618/2129 [00:11<00:36, 41.41it/s]
 29%|██▉       | 626/2129 [00:11<00:30, 49.35it/s]
 30%|██▉       | 633/2129 [00:11<00:31, 47.93it/s]
 30%|███       | 639/2129 [00:12<00:29, 50.01it/s]
 30%|███       | 645/2129 [00:12<00:28, 51.66it/s]
 31%|███       | 651/2129 [00:12<00:28, 51.50it/s]
 31%|███       | 657/2129 [00:12<00:31, 46.74it/s]
 31%|███       | 663/2129 [00:12<00:29, 49.39it/s]
 31%|███▏      | 669/2129 [00:12<00:28, 50.37it/s]
 32%|███▏      | 675/2129 [00:12<00:27, 52.46it/s]
 32%|███▏      | 681/2129 [00:12<00:27, 53.19it/s]
 32%|███▏      | 687/2129 [00:12<00:27, 52.77it/s]
 33%|███▎      | 694/2129 [00:13<00:25, 55.66it/s]
 33%|███▎      | 701/2129 [00:13<00:24, 59.21it/s]
 33%|███▎      | 707/2129 [00:13<00:27, 52.48it/s]
 34%|███▎      | 714/2129 [00:13<00:25, 55.20it/s]
 34%|███▍      | 721/2129 [00:13<00:24, 57.38it/s]
 34%|███▍      | 727/2129 [00:13<00:28, 49.78it/s]
 34%|███▍      | 733/2129 [00:13<00:35, 39.87it/s]
 35%|███▍      | 740/2129 [00:14<00:30, 45.73it/s]
 35%|███▌      | 746/2129 [00:14<00:28, 48.86it/s]
 35%|███▌      | 753/2129 [00:14<00:26, 52.09it/s]
 36%|███▌      | 759/2129 [00:14<00:26, 51.82it/s]
 36%|███▌      | 766/2129 [00:14<00:27, 49.92it/s]
 36%|███▋      | 772/2129 [00:14<00:29, 46.05it/s]
 36%|███▋      | 777/2129 [00:14<00:28, 46.87it/s]
 37%|███▋      | 783/2129 [00:14<00:27, 48.99it/s]
 37%|███▋      | 789/2129 [00:14<00:26, 49.87it/s]
 37%|███▋      | 796/2129 [00:15<00:25, 52.14it/s]
 38%|███▊      | 802/2129 [00:15<00:24, 53.92it/s]
 38%|███▊      | 808/2129 [00:15<00:27, 48.12it/s]
 38%|███▊      | 813/2129 [00:15<00:29, 44.01it/s]
 38%|███▊      | 818/2129 [00:15<00:32, 40.63it/s]
 39%|███▊      | 823/2129 [00:15<00:37, 34.82it/s]
 39%|███▉      | 827/2129 [00:15<00:39, 33.28it/s]
 39%|███▉      | 833/2129 [00:16<00:33, 38.46it/s]
 39%|███▉      | 839/2129 [00:16<00:30, 41.80it/s]
 40%|███▉      | 845/2129 [00:16<00:28, 44.31it/s]
 40%|████      | 852/2129 [00:16<00:28, 44.30it/s]
 40%|████      | 857/2129 [00:16<00:30, 41.66it/s]
 41%|████      | 863/2129 [00:16<00:28, 44.87it/s]
 41%|████      | 869/2129 [00:16<00:26, 46.87it/s]
 41%|████      | 874/2129 [00:16<00:29, 42.16it/s]
 41%|████▏     | 881/2129 [00:17<00:25, 48.65it/s]
 42%|████▏     | 887/2129 [00:17<00:25, 48.08it/s]
 42%|████▏     | 892/2129 [00:17<00:28, 43.87it/s]
 42%|████▏     | 897/2129 [00:17<00:27, 44.40it/s]
 42%|████▏     | 902/2129 [00:17<00:28, 42.92it/s]
 43%|████▎     | 908/2129 [00:17<00:26, 45.58it/s]
 43%|████▎     | 914/2129 [00:17<00:25, 48.22it/s]
 43%|████▎     | 919/2129 [00:17<00:27, 43.56it/s]
 43%|████▎     | 924/2129 [00:18<00:26, 45.12it/s]
 44%|████▎     | 930/2129 [00:18<00:24, 48.00it/s]
 44%|████▍     | 935/2129 [00:18<00:27, 43.84it/s]
 44%|████▍     | 940/2129 [00:18<00:26, 44.74it/s]
 44%|████▍     | 946/2129 [00:18<00:24, 48.80it/s]
 45%|████▍     | 953/2129 [00:18<00:22, 53.20it/s]
 45%|████▌     | 959/2129 [00:18<00:22, 52.39it/s]
 45%|████▌     | 965/2129 [00:18<00:29, 39.87it/s]
 46%|████▌     | 970/2129 [00:19<00:28, 40.53it/s]
 46%|████▌     | 975/2129 [00:19<00:31, 37.01it/s]
 46%|████▌     | 981/2129 [00:19<00:27, 42.09it/s]
 46%|████▋     | 986/2129 [00:19<00:26, 42.47it/s]
 47%|████▋     | 991/2129 [00:19<00:26, 43.28it/s]
 47%|████▋     | 996/2129 [00:19<00:27, 41.67it/s]
 47%|████▋     | 1002/2129 [00:19<00:24, 45.75it/s]
 47%|████▋     | 1009/2129 [00:19<00:22, 50.33it/s]
 48%|████▊     | 1015/2129 [00:20<00:23, 46.42it/s]
 48%|████▊     | 1020/2129 [00:20<00:25, 42.75it/s]
 48%|████▊     | 1025/2129 [00:20<00:26, 42.42it/s]
 49%|████▊     | 1033/2129 [00:20<00:21, 50.75it/s]
 49%|████▉     | 1039/2129 [00:20<00:21, 49.56it/s]
 49%|████▉     | 1045/2129 [00:20<00:21, 51.35it/s]
 49%|████▉     | 1051/2129 [00:20<00:21, 50.45it/s]
 50%|████▉     | 1057/2129 [00:20<00:20, 52.25it/s]
 50%|████▉     | 1063/2129 [00:21<00:19, 53.64it/s]
 50%|█████     | 1069/2129 [00:21<00:20, 51.17it/s]
 51%|█████     | 1076/2129 [00:21<00:19, 54.92it/s]
 51%|█████     | 1082/2129 [00:21<00:18, 55.35it/s]
 51%|█████     | 1088/2129 [00:21<00:18, 56.51it/s]
 51%|█████▏    | 1095/2129 [00:21<00:17, 57.51it/s]
 52%|█████▏    | 1102/2129 [00:21<00:17, 58.70it/s]
 52%|█████▏    | 1108/2129 [00:21<00:18, 54.70it/s]
 52%|█████▏    | 1114/2129 [00:21<00:18, 53.45it/s]
 53%|█████▎    | 1120/2129 [00:22<00:25, 39.74it/s]
 53%|█████▎    | 1126/2129 [00:22<00:23, 43.28it/s]
 53%|█████▎    | 1131/2129 [00:22<00:26, 38.05it/s]
 53%|█████▎    | 1136/2129 [00:22<00:26, 38.08it/s]
 54%|█████▎    | 1142/2129 [00:22<00:22, 43.03it/s]
 54%|█████▍    | 1147/2129 [00:22<00:28, 35.00it/s]
 54%|█████▍    | 1152/2129 [00:23<00:26, 36.86it/s]
 54%|█████▍    | 1157/2129 [00:23<00:26, 36.15it/s]
 55%|█████▍    | 1164/2129 [00:23<00:22, 42.35it/s]
 55%|█████▍    | 1170/2129 [00:23<00:21, 45.13it/s]
 55%|█████▌    | 1176/2129 [00:23<00:19, 48.77it/s]
 56%|█████▌    | 1182/2129 [00:23<00:18, 49.97it/s]
 56%|█████▌    | 1189/2129 [00:23<00:17, 54.17it/s]
 56%|█████▌    | 1195/2129 [00:23<00:20, 45.22it/s]
 56%|█████▋    | 1201/2129 [00:24<00:19, 48.37it/s]
 57%|█████▋    | 1207/2129 [00:24<00:21, 43.65it/s]
 57%|█████▋    | 1213/2129 [00:24<00:19, 46.35it/s]
 57%|█████▋    | 1218/2129 [00:24<00:19, 47.03it/s]
 57%|█████▋    | 1224/2129 [00:24<00:18, 49.23it/s]
 58%|█████▊    | 1232/2129 [00:24<00:16, 54.77it/s]
 58%|█████▊    | 1238/2129 [00:24<00:16, 53.98it/s]
 58%|█████▊    | 1245/2129 [00:24<00:16, 54.88it/s]
 59%|█████▉    | 1251/2129 [00:24<00:15, 55.59it/s]
 59%|█████▉    | 1257/2129 [00:25<00:18, 46.92it/s]
 59%|█████▉    | 1262/2129 [00:25<00:22, 38.64it/s]
 60%|█████▉    | 1267/2129 [00:25<00:22, 37.83it/s]
 60%|█████▉    | 1273/2129 [00:25<00:20, 40.96it/s]
 60%|██████    | 1279/2129 [00:25<00:20, 41.09it/s]
 60%|██████    | 1284/2129 [00:25<00:20, 41.73it/s]
 61%|██████    | 1289/2129 [00:25<00:19, 43.12it/s]
 61%|██████    | 1295/2129 [00:26<00:17, 46.42it/s]
 61%|██████    | 1300/2129 [00:26<00:19, 43.51it/s]
 61%|██████▏   | 1305/2129 [00:26<00:18, 43.89it/s]
 62%|██████▏   | 1310/2129 [00:26<00:18, 43.37it/s]
 62%|██████▏   | 1315/2129 [00:26<00:19, 42.79it/s]
 62%|██████▏   | 1321/2129 [00:26<00:17, 46.55it/s]
 62%|██████▏   | 1326/2129 [00:26<00:18, 43.02it/s]
 63%|██████▎   | 1331/2129 [00:26<00:20, 38.90it/s]
 63%|██████▎   | 1336/2129 [00:27<00:20, 38.97it/s]
 63%|██████▎   | 1340/2129 [00:27<00:24, 31.77it/s]
 63%|██████▎   | 1346/2129 [00:27<00:21, 36.69it/s]
 64%|██████▎   | 1353/2129 [00:27<00:18, 42.86it/s]
 64%|██████▍   | 1359/2129 [00:27<00:16, 46.35it/s]
 64%|██████▍   | 1364/2129 [00:27<00:17, 43.00it/s]
 64%|██████▍   | 1369/2129 [00:27<00:17, 43.79it/s]
 65%|██████▍   | 1374/2129 [00:28<00:19, 38.76it/s]
 65%|██████▍   | 1379/2129 [00:28<00:19, 38.17it/s]
 65%|██████▍   | 1383/2129 [00:28<00:23, 31.69it/s]
 65%|██████▌   | 1387/2129 [00:28<00:22, 32.86it/s]
 65%|██████▌   | 1393/2129 [00:28<00:19, 38.35it/s]
 66%|██████▌   | 1398/2129 [00:28<00:17, 40.97it/s]
 66%|██████▌   | 1403/2129 [00:28<00:21, 33.25it/s]
 66%|██████▌   | 1407/2129 [00:29<00:20, 34.43it/s]
 66%|██████▋   | 1413/2129 [00:29<00:18, 38.97it/s]
 67%|██████▋   | 1418/2129 [00:29<00:17, 39.56it/s]
 67%|██████▋   | 1423/2129 [00:29<00:17, 40.35it/s]
 67%|██████▋   | 1429/2129 [00:29<00:15, 44.36it/s]
 67%|██████▋   | 1435/2129 [00:29<00:14, 46.98it/s]
 68%|██████▊   | 1441/2129 [00:29<00:13, 49.71it/s]
 68%|██████▊   | 1447/2129 [00:29<00:13, 48.97it/s]
 68%|██████▊   | 1453/2129 [00:29<00:13, 51.87it/s]
 69%|██████▊   | 1459/2129 [00:30<00:13, 51.07it/s]
 69%|██████▉   | 1465/2129 [00:30<00:12, 52.60it/s]
 69%|██████▉   | 1471/2129 [00:30<00:16, 38.99it/s]
 69%|██████▉   | 1477/2129 [00:30<00:15, 42.73it/s]
 70%|██████▉   | 1483/2129 [00:30<00:14, 45.34it/s]
 70%|██████▉   | 1490/2129 [00:30<00:12, 50.97it/s]
 70%|███████   | 1496/2129 [00:30<00:15, 42.09it/s]
 71%|███████   | 1501/2129 [00:31<00:16, 37.47it/s]
 71%|███████   | 1507/2129 [00:31<00:15, 41.08it/s]
 71%|███████   | 1514/2129 [00:31<00:13, 46.42it/s]
 71%|███████▏  | 1521/2129 [00:31<00:12, 50.47it/s]
 72%|███████▏  | 1527/2129 [00:31<00:11, 52.21it/s]
 72%|███████▏  | 1533/2129 [00:31<00:14, 40.50it/s]
 72%|███████▏  | 1539/2129 [00:31<00:13, 43.12it/s]
 73%|███████▎  | 1545/2129 [00:32<00:12, 45.92it/s]
 73%|███████▎  | 1553/2129 [00:32<00:10, 52.76it/s]
 73%|███████▎  | 1559/2129 [00:32<00:10, 53.62it/s]
 74%|███████▎  | 1565/2129 [00:32<00:10, 54.59it/s]
 74%|███████▍  | 1571/2129 [00:32<00:10, 55.15it/s]
 74%|███████▍  | 1577/2129 [00:32<00:10, 54.04it/s]
 74%|███████▍  | 1583/2129 [00:32<00:10, 54.13it/s]
 75%|███████▍  | 1589/2129 [00:32<00:09, 55.61it/s]
 75%|███████▍  | 1595/2129 [00:32<00:11, 48.14it/s]
 75%|███████▌  | 1601/2129 [00:33<00:12, 43.04it/s]
 75%|███████▌  | 1607/2129 [00:33<00:12, 43.19it/s]
 76%|███████▌  | 1613/2129 [00:33<00:11, 45.53it/s]
 76%|███████▌  | 1618/2129 [00:33<00:12, 40.84it/s]
 76%|███████▌  | 1623/2129 [00:33<00:12, 39.81it/s]
 77%|███████▋  | 1629/2129 [00:33<00:11, 42.08it/s]
 77%|███████▋  | 1635/2129 [00:33<00:11, 44.32it/s]
 77%|███████▋  | 1641/2129 [00:34<00:10, 46.43it/s]
 77%|███████▋  | 1646/2129 [00:34<00:11, 40.45it/s]
 78%|███████▊  | 1652/2129 [00:34<00:10, 44.56it/s]
 78%|███████▊  | 1657/2129 [00:34<00:10, 45.34it/s]
 78%|███████▊  | 1663/2129 [00:34<00:09, 49.05it/s]
 78%|███████▊  | 1669/2129 [00:34<00:10, 45.70it/s]
 79%|███████▊  | 1675/2129 [00:34<00:09, 49.04it/s]
 79%|███████▉  | 1681/2129 [00:34<00:08, 51.05it/s]
 79%|███████▉  | 1687/2129 [00:34<00:08, 52.30it/s]
 80%|███████▉  | 1693/2129 [00:35<00:08, 50.94it/s]
 80%|███████▉  | 1699/2129 [00:35<00:08, 51.82it/s]
 80%|████████  | 1705/2129 [00:35<00:08, 52.22it/s]
 80%|████████  | 1711/2129 [00:35<00:08, 51.96it/s]
 81%|████████  | 1717/2129 [00:35<00:07, 53.11it/s]
 81%|████████  | 1723/2129 [00:35<00:07, 51.21it/s]
 81%|████████  | 1729/2129 [00:35<00:08, 49.18it/s]
 81%|████████▏ | 1734/2129 [00:35<00:08, 48.67it/s]
 82%|████████▏ | 1740/2129 [00:36<00:07, 51.22it/s]
 82%|████████▏ | 1746/2129 [00:36<00:07, 52.83it/s]
 82%|████████▏ | 1752/2129 [00:36<00:07, 53.22it/s]
 83%|████████▎ | 1758/2129 [00:36<00:06, 54.50it/s]
 83%|████████▎ | 1764/2129 [00:36<00:06, 55.40it/s]
 83%|████████▎ | 1770/2129 [00:36<00:06, 55.21it/s]
 83%|████████▎ | 1776/2129 [00:36<00:06, 55.10it/s]
 84%|████████▎ | 1782/2129 [00:36<00:08, 43.07it/s]
 84%|████████▍ | 1787/2129 [00:36<00:08, 42.67it/s]
 84%|████████▍ | 1793/2129 [00:37<00:07, 45.25it/s]
 84%|████████▍ | 1798/2129 [00:37<00:07, 46.22it/s]
 85%|████████▍ | 1803/2129 [00:37<00:06, 46.93it/s]
 85%|████████▍ | 1808/2129 [00:37<00:06, 46.58it/s]
 85%|████████▌ | 1813/2129 [00:37<00:08, 35.56it/s]
 85%|████████▌ | 1819/2129 [00:37<00:07, 39.76it/s]
 86%|████████▌ | 1825/2129 [00:37<00:07, 41.79it/s]
 86%|████████▌ | 1830/2129 [00:37<00:06, 43.57it/s]
 86%|████████▌ | 1835/2129 [00:38<00:06, 44.46it/s]
 86%|████████▋ | 1840/2129 [00:38<00:06, 43.74it/s]
 87%|████████▋ | 1846/2129 [00:38<00:06, 46.02it/s]
 87%|████████▋ | 1851/2129 [00:38<00:06, 45.74it/s]
 87%|████████▋ | 1858/2129 [00:38<00:05, 50.15it/s]
 88%|████████▊ | 1864/2129 [00:38<00:05, 51.57it/s]
 88%|████████▊ | 1870/2129 [00:38<00:05, 48.56it/s]
 88%|████████▊ | 1875/2129 [00:38<00:05, 46.04it/s]
 88%|████████▊ | 1880/2129 [00:39<00:05, 46.34it/s]
 89%|████████▊ | 1886/2129 [00:39<00:05, 48.54it/s]
 89%|████████▉ | 1891/2129 [00:39<00:05, 42.73it/s]
 89%|████████▉ | 1897/2129 [00:39<00:05, 46.27it/s]
 89%|████████▉ | 1902/2129 [00:39<00:05, 42.67it/s]
 90%|████████▉ | 1907/2129 [00:39<00:05, 39.71it/s]
 90%|████████▉ | 1912/2129 [00:39<00:06, 35.05it/s]
 90%|█████████ | 1918/2129 [00:39<00:05, 40.19it/s]
 90%|█████████ | 1923/2129 [00:40<00:05, 37.49it/s]
 91%|█████████ | 1927/2129 [00:40<00:05, 35.27it/s]
 91%|█████████ | 1932/2129 [00:40<00:05, 38.66it/s]
 91%|█████████ | 1937/2129 [00:40<00:05, 32.66it/s]
 91%|█████████▏| 1943/2129 [00:40<00:05, 35.48it/s]
 91%|█████████▏| 1947/2129 [00:40<00:05, 34.56it/s]
 92%|█████████▏| 1952/2129 [00:40<00:04, 35.73it/s]
 92%|█████████▏| 1957/2129 [00:41<00:04, 38.41it/s]
 92%|█████████▏| 1963/2129 [00:41<00:03, 42.49it/s]
 92%|█████████▏| 1968/2129 [00:41<00:04, 34.47it/s]
 93%|█████████▎| 1973/2129 [00:41<00:04, 37.79it/s]
 93%|█████████▎| 1978/2129 [00:41<00:04, 36.36it/s]
 93%|█████████▎| 1983/2129 [00:41<00:03, 39.55it/s]
 93%|█████████▎| 1988/2129 [00:41<00:03, 39.20it/s]
 94%|█████████▎| 1993/2129 [00:42<00:03, 39.37it/s]
 94%|█████████▍| 1998/2129 [00:42<00:04, 28.75it/s]
 94%|█████████▍| 2002/2129 [00:42<00:04, 28.49it/s]
 94%|█████████▍| 2007/2129 [00:42<00:03, 32.12it/s]
 94%|█████████▍| 2011/2129 [00:42<00:03, 31.89it/s]
 95%|█████████▍| 2015/2129 [00:42<00:03, 29.79it/s]
 95%|█████████▍| 2021/2129 [00:43<00:03, 32.23it/s]
 95%|█████████▌| 2025/2129 [00:43<00:03, 30.69it/s]
 95%|█████████▌| 2030/2129 [00:43<00:02, 34.74it/s]
 96%|█████████▌| 2035/2129 [00:43<00:02, 38.11it/s]
 96%|█████████▌| 2040/2129 [00:43<00:02, 36.03it/s]
 96%|█████████▌| 2046/2129 [00:43<00:02, 40.16it/s]
 96%|█████████▋| 2051/2129 [00:43<00:02, 37.50it/s]
 97%|█████████▋| 2057/2129 [00:43<00:01, 41.66it/s]
 97%|█████████▋| 2063/2129 [00:44<00:01, 46.22it/s]
 97%|█████████▋| 2069/2129 [00:44<00:01, 48.78it/s]
 97%|█████████▋| 2075/2129 [00:44<00:01, 50.99it/s]
 98%|█████████▊| 2081/2129 [00:44<00:00, 50.99it/s]
 98%|█████████▊| 2087/2129 [00:44<00:00, 50.37it/s]
 98%|█████████▊| 2093/2129 [00:44<00:00, 50.78it/s]
 99%|█████████▊| 2099/2129 [00:44<00:00, 48.98it/s]
 99%|█████████▉| 2104/2129 [00:44<00:00, 45.07it/s]
 99%|█████████▉| 2110/2129 [00:44<00:00, 43.45it/s]
 99%|█████████▉| 2115/2129 [00:45<00:00, 37.93it/s]
100%|█████████▉| 2119/2129 [00:45<00:00, 36.29it/s]
100%|██████████| 2129/2129 [00:45<00:00, 46.84it/s]
/kaggle/working/PRAGA/clustering_utils.py:173: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return log_Hastings_ratio_split(1.0, torch.tensor(N_k_1), torch.tensor(N_k_2), log_ll_k1, log_ll_k2, log_ll_k, split_prob=0.1)

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 335.07it/s]
 84%|████████▎ | 251/300 [10:23<12:10, 14.91s/it]

[[np.int64(0), False, 8], [np.int64(1), False, 8], [np.int64(2), False, 13], [np.int64(3), False, 12], [np.int64(4), False, 6], [np.int64(5), False, 8], [np.int64(6), False, 13], [np.int64(7), False, 9], [np.int64(10), False, 0], [np.int64(11), False, 7]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.6537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1630, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [10:24<08:23, 10.48s/it]

tensor(11.6580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4555, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6828, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [10:24<02:45,  3.67s/it]

tensor(11.6681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7681, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9713, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [10:24<01:20,  1.86s/it]

tensor(11.6791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0422, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0322, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0458, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8181, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [10:24<00:56,  1.34s/it]

tensor(11.6728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0489, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8723, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0517, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9414, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [10:24<00:28,  1.39it/s]

tensor(11.6713, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0539, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0236, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0555, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1279, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [10:25<00:12,  3.07it/s]

tensor(11.6866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0568, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1749, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0565, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2108, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [10:25<00:09,  3.77it/s]

tensor(11.6817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0557, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2423, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0537, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2690, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [10:25<00:05,  5.87it/s]

tensor(11.6712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0512, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2912, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0482, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3112, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [10:26<00:04,  6.90it/s]

tensor(11.6736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3261, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0408, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3442, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [10:26<00:03,  7.54it/s]

tensor(11.6737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0371, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3564, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3631, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [10:26<00:03,  7.70it/s]

tensor(11.6660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3711, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3771, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [10:26<00:03,  7.93it/s]

tensor(11.6571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3805, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3825, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [10:27<00:02,  8.01it/s]

tensor(11.6549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3841, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6535, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3888, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [10:27<00:02,  7.88it/s]

tensor(11.6514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3945, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6482, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3927, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [10:27<00:02,  8.14it/s]

tensor(11.6454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3924, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3916, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [10:27<00:02,  8.15it/s]

tensor(11.6418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6407, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3905, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [10:28<00:01,  8.17it/s]

tensor(11.6388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3909, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3929, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [10:28<00:01,  8.05it/s]

tensor(11.6351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3944, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3982, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [10:28<00:01,  8.01it/s]

tensor(11.6312, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3989, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6299, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3952, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [10:28<00:01,  8.07it/s]

tensor(11.6287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3915, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3903, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [10:28<00:00,  8.05it/s]

tensor(11.6259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3883, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3884, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [10:29<00:00,  8.00it/s]

tensor(11.6234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3875, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6224, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3873, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [10:29<00:00,  8.11it/s]

tensor(11.6216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3856, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6206, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3857, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [10:29<00:00,  8.03it/s]

tensor(11.6198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3866, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3880, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [10:29<00:00,  2.10s/it]

tensor(11.6182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3864, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.003597259521484375
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 0
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.619754865456
NMI         : 0.620757891483
Runtime     : 674.40 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed0

==============================================================================================================
PRAGA RUN | E18.5 | seed=1
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 2.608e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(15.6346, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4808, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6184, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2284, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:34,  8.71it/s]

tensor(15.6092, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1975, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5982, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3665, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5855, device='cuda:0', grad_fn=<AddBackward0>)

  2%|▏         | 6/300 [00:00<00:30,  9.51it/s]

tensor(14.7153, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5728, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2267, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5596, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8842, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:30,  9.63it/s]

tensor(15.5474, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6746, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5355, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5837, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:29,  9.76it/s]

tensor(15.5230, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5999, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5133, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7134, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5044, device='cuda:0', grad_fn=<AddBackward0>)

  4%|▍         | 13/300 [00:01<00:29,  9.81it/s]

tensor(6.9149, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4937, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1945, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:28,  9.87it/s]

tensor(15.4829, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5460, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4722, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9612, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4608, device='cuda:0', grad_fn=<AddBackward0>)

  6%|▌         | 17/300 [00:01<00:28,  9.88it/s]

tensor(4.4348, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4489, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9602, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.69it/s]

tensor(15.4351, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5330, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4204, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1487, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:28,  9.85it/s]

tensor(15.4048, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8018, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3865, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4909, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:28,  9.86it/s]

tensor(15.3678, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2099, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3457, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9578, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3216, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7310, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:28,  9.58it/s]

tensor(15.2959, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5276, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2677, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3442, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:28,  9.64it/s]

tensor(15.2383, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1799, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2061, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0330, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|▉         | 29/300 [00:03<00:28,  9.52it/s]

tensor(15.1716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9009, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7823, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.77it/s]

tensor(15.0948, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6766, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5821, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:27,  9.81it/s]

tensor(15.0083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4977, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4230, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:26,  9.88it/s]

tensor(14.9162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3556, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8694, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2969, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8224, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2447, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.77it/s]

tensor(14.7734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1985, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1587, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6702, device='cuda:0', grad_fn=<AddBackward0>)

 14%|█▎        | 41/300 [00:04<00:26,  9.84it/s]

tensor(0.1242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0948, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0711, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:25,  9.91it/s]

tensor(14.4925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0533, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0419, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:25,  9.89it/s]

tensor(14.3564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.83it/s]

tensor(14.2109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:05<00:25,  9.69it/s]

tensor(14.0681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.65it/s]

tensor(13.9400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8854, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:25,  9.61it/s]

tensor(13.8388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:25,  9.57it/s]

tensor(13.7613, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:25,  9.47it/s]

tensor(13.6813, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:06<00:24,  9.61it/s]

tensor(13.5917, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.72it/s]

tensor(13.5165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:24,  9.80it/s]

tensor(13.4586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:24,  9.60it/s]

tensor(13.4080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:07<00:24,  9.52it/s]

tensor(13.3576, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:23,  9.62it/s]

tensor(13.3033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:07<00:23,  9.59it/s]

tensor(13.2463, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:23,  9.48it/s]

tensor(13.1906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:07<00:23,  9.56it/s]

tensor(13.1390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1145, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:08<00:22,  9.66it/s]

tensor(13.0913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:08<00:23,  9.56it/s]

tensor(13.0458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0236, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:22,  9.52it/s]

tensor(13.0016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:22,  9.66it/s]

tensor(12.9594, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:21,  9.74it/s]

tensor(12.9203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:09<00:22,  9.43it/s]

tensor(12.8834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:21,  9.57it/s]

tensor(12.8480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:21,  9.69it/s]

tensor(12.8131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:21,  9.72it/s]

tensor(12.7788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:21,  9.51it/s]

tensor(12.7459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:10<00:21,  9.57it/s]

tensor(12.7146, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:20,  9.63it/s]

tensor(12.6847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([340, 159, 106, 286,  74, 228, 214, 146, 111,  93, 127, 119,  48,  78])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 5/2129 [00:00<00:53, 39.54it/s]
  0%|          | 9/2129 [00:00<01:09, 30.44it/s]
  1%|          | 14/2129 [00:00<01:00, 35.07it/s]
  1%|          | 18/2129 [00:00<00:59, 35.38it/s]
  1%|          | 22/2129 [00:00<01:09, 30.34it/s]
  1%|▏         | 28/2129 [00:00<00:56, 37.09it/s]
  2%|▏         | 33/2129 [00:00<00:56, 37.06it/s]
  2%|▏         | 39/2129 [00:01<00:50, 41.63it/s]
  2%|▏         | 44/2129 [00:01<01:20, 25.97it/s]
  2%|▏         | 48/2129 [00:01<01:18, 26.65it/s]
  3%|▎         | 54/2129 [00:01<01:23, 24.92it/s]
  3%|▎         | 57/2129 [00:01<01:28, 23.29it/s]
  3%|▎         | 60/2129 [00:02<02:09, 15.97it/s]
  3%|▎         | 65/2129 [00:02<02:02, 16.92it/s]
  3%|▎         | 68/2129 [00:02<01:53, 18.15it/s]
  3%|▎         | 73/2129 [00:02<01:48, 19.02it/s]
  4%|▎         | 76/2129 [00:03<01:42, 20.00it/s]
  4%|▍         | 80/2129 [00:03<01:50, 18.55it/s]
  4%|▍         | 83/2129 [00:03<01:43, 19.69it/s]
  4%|▍         | 90/2129 [00:03<01:12, 28.02it/s]
  5%|▍         | 97/2129 [00:03<00:56, 35.85it/s]
  5%|▍         | 102/2129 [00:03<00:54, 36.96it/s]
  5%|▌         | 107/2129 [00:04<02:12, 15.29it/s]
  5%|▌         | 111/2129 [00:04<01:55, 17.48it/s]
  5%|▌         | 115/2129 [00:05<02:03, 16.31it/s]
  6%|▌         | 121/2129 [00:05<01:50, 18.17it/s]
  6%|▌         | 124/2129 [00:05<01:43, 19.37it/s]
  6%|▌         | 132/2129 [00:05<01:29, 22.26it/s]
  6%|▋         | 135/2129 [00:06<02:06, 15.74it/s]
  7%|▋         | 139/2129 [00:06<01:47, 18.57it/s]
  7%|▋         | 147/2129 [00:06<01:12, 27.29it/s]
  7%|▋         | 151/2129 [00:06<01:10, 28.23it/s]
  7%|▋         | 155/2129 [00:06<01:32, 21.35it/s]
  7%|▋         | 158/2129 [00:07<01:52, 17.54it/s]
  8%|▊         | 161/2129 [00:07<02:08, 15.34it/s]
  8%|▊         | 163/2129 [00:07<02:22, 13.79it/s]
  8%|▊         | 166/2129 [00:07<02:12, 14.82it/s]
  8%|▊         | 168/2129 [00:07<02:29, 13.10it/s]
  8%|▊         | 170/2129 [00:08<02:25, 13.46it/s]
  8%|▊         | 172/2129 [00:08<02:39, 12.25it/s]
  8%|▊         | 175/2129 [00:08<02:06, 15.40it/s]
  8%|▊         | 178/2129 [00:08<02:16, 14.26it/s]
  8%|▊         | 180/2129 [00:09<03:36,  8.99it/s]
  9%|▊         | 182/2129 [00:09<03:07, 10.37it/s]
  9%|▊         | 184/2129 [00:09<03:11, 10.15it/s]
  9%|▉         | 187/2129 [00:09<03:13, 10.06it/s]
  9%|▉         | 190/2129 [00:10<03:13, 10.04it/s]
  9%|▉         | 193/2129 [00:10<02:36, 12.40it/s]
  9%|▉         | 197/2129 [00:10<02:25, 13.30it/s]
  9%|▉         | 200/2129 [00:10<02:33, 12.53it/s]
  9%|▉         | 202/2129 [00:10<02:51, 11.24it/s]
 10%|▉         | 205/2129 [00:11<02:23, 13.40it/s]
 10%|▉         | 211/2129 [00:11<01:30, 21.21it/s]
 10%|█         | 214/2129 [00:11<02:14, 14.19it/s]
 10%|█         | 217/2129 [00:11<02:29, 12.76it/s]
 10%|█         | 220/2129 [00:12<02:26, 13.02it/s]
 10%|█         | 222/2129 [00:12<02:20, 13.56it/s]
 11%|█         | 224/2129 [00:12<02:46, 11.44it/s]
 11%|█         | 226/2129 [00:13<03:52,  8.19it/s]
 11%|█         | 229/2129 [00:13<03:01, 10.47it/s]
 11%|█         | 233/2129 [00:13<02:35, 12.19it/s]
 11%|█         | 235/2129 [00:13<02:55, 10.79it/s]
 11%|█         | 239/2129 [00:13<02:38, 11.94it/s]
 11%|█▏        | 242/2129 [00:14<02:11, 14.38it/s]
 12%|█▏        | 246/2129 [00:14<02:03, 15.20it/s]
 12%|█▏        | 248/2129 [00:14<02:28, 12.63it/s]
 12%|█▏        | 250/2129 [00:14<02:48, 11.14it/s]
 12%|█▏        | 252/2129 [00:15<03:18,  9.45it/s]
 12%|█▏        | 255/2129 [00:15<02:39, 11.77it/s]
 12%|█▏        | 258/2129 [00:15<02:33, 12.23it/s]
 12%|█▏        | 260/2129 [00:15<02:48, 11.09it/s]
 12%|█▏        | 262/2129 [00:15<03:08,  9.89it/s]
 12%|█▏        | 265/2129 [00:16<02:32, 12.25it/s]
 13%|█▎        | 267/2129 [00:16<02:50, 10.94it/s]
 13%|█▎        | 269/2129 [00:16<03:11,  9.70it/s]
 13%|█▎        | 273/2129 [00:16<02:15, 13.74it/s]
 13%|█▎        | 275/2129 [00:16<02:25, 12.78it/s]
 13%|█▎        | 278/2129 [00:17<02:03, 14.93it/s]
 13%|█▎        | 284/2129 [00:17<01:19, 23.33it/s]
 13%|█▎        | 287/2129 [00:17<01:29, 20.48it/s]
 14%|█▎        | 290/2129 [00:17<01:23, 22.03it/s]
 14%|█▍        | 293/2129 [00:17<01:46, 17.26it/s]
 14%|█▍        | 296/2129 [00:18<02:38, 11.58it/s]
 14%|█▍        | 298/2129 [00:18<02:24, 12.67it/s]
 14%|█▍        | 301/2129 [00:18<01:59, 15.27it/s]
 14%|█▍        | 304/2129 [00:18<02:13, 13.70it/s]
 14%|█▍        | 306/2129 [00:18<02:33, 11.91it/s]
 15%|█▍        | 309/2129 [00:19<02:03, 14.70it/s]
 15%|█▍        | 312/2129 [00:19<02:12, 13.67it/s]
 15%|█▍        | 314/2129 [00:19<03:07,  9.69it/s]
 15%|█▍        | 316/2129 [00:19<03:13,  9.39it/s]
 15%|█▍        | 319/2129 [00:20<03:05,  9.77it/s]
 15%|█▌        | 321/2129 [00:20<03:14,  9.28it/s]
 15%|█▌        | 324/2129 [00:20<03:11,  9.41it/s]
 15%|█▌        | 327/2129 [00:20<02:30, 11.96it/s]
 15%|█▌        | 329/2129 [00:21<02:45, 10.86it/s]
 16%|█▌        | 331/2129 [00:21<03:43,  8.04it/s]
 16%|█▌        | 334/2129 [00:21<03:30,  8.52it/s]
 16%|█▌        | 337/2129 [00:22<03:11,  9.35it/s]
 16%|█▌        | 339/2129 [00:22<02:51, 10.42it/s]
 16%|█▌        | 342/2129 [00:22<02:37, 11.32it/s]
 16%|█▌        | 344/2129 [00:22<02:44, 10.87it/s]
 16%|█▋        | 346/2129 [00:22<03:11,  9.31it/s]
 16%|█▋        | 349/2129 [00:23<02:51, 10.39it/s]
 16%|█▋        | 351/2129 [00:23<03:00,  9.84it/s]
 17%|█▋        | 354/2129 [00:23<02:39, 11.15it/s]
 17%|█▋        | 356/2129 [00:23<03:01,  9.79it/s]
 17%|█▋        | 358/2129 [00:24<03:34,  8.24it/s]
 17%|█▋        | 360/2129 [00:24<03:09,  9.32it/s]
 17%|█▋        | 362/2129 [00:24<03:48,  7.72it/s]
 17%|█▋        | 364/2129 [00:24<03:21,  8.74it/s]
 17%|█▋        | 366/2129 [00:25<03:00,  9.78it/s]
 17%|█▋        | 371/2129 [00:25<01:49, 16.00it/s]
 18%|█▊        | 374/2129 [00:25<02:05, 13.96it/s]
 18%|█▊        | 376/2129 [00:25<02:28, 11.77it/s]
 18%|█▊        | 378/2129 [00:25<02:42, 10.76it/s]
 18%|█▊        | 380/2129 [00:26<02:51, 10.18it/s]
 18%|█▊        | 382/2129 [00:26<02:32, 11.43it/s]
 18%|█▊        | 384/2129 [00:26<02:40, 10.88it/s]
 18%|█▊        | 386/2129 [00:26<03:36,  8.05it/s]
 18%|█▊        | 388/2129 [00:27<03:06,  9.33it/s]
 18%|█▊        | 391/2129 [00:27<02:44, 10.58it/s]
 19%|█▊        | 394/2129 [00:27<02:51, 10.14it/s]
 19%|█▊        | 397/2129 [00:27<02:17, 12.63it/s]
 19%|█▉        | 400/2129 [00:27<02:13, 12.97it/s]
 19%|█▉        | 403/2129 [00:28<01:53, 15.15it/s]
 19%|█▉        | 405/2129 [00:28<02:47, 10.30it/s]
 19%|█▉        | 407/2129 [00:28<02:58,  9.63it/s]
 19%|█▉        | 409/2129 [00:29<03:22,  8.49it/s]
 19%|█▉        | 413/2129 [00:29<02:16, 12.62it/s]
 20%|█▉        | 419/2129 [00:29<01:48, 15.78it/s]
 20%|█▉        | 421/2129 [00:29<01:48, 15.73it/s]
 20%|██        | 427/2129 [00:29<01:14, 22.94it/s]
 20%|██        | 430/2129 [00:29<01:27, 19.51it/s]
 20%|██        | 433/2129 [00:30<02:07, 13.35it/s]
 20%|██        | 436/2129 [00:30<02:16, 12.40it/s]
 21%|██        | 439/2129 [00:30<02:26, 11.56it/s]
 21%|██        | 442/2129 [00:31<02:05, 13.42it/s]
 21%|██        | 446/2129 [00:31<01:56, 14.41it/s]
 21%|██        | 448/2129 [00:31<01:50, 15.22it/s]
 21%|██        | 450/2129 [00:31<02:13, 12.55it/s]
 21%|██        | 452/2129 [00:31<02:01, 13.76it/s]
 21%|██▏       | 455/2129 [00:32<02:10, 12.85it/s]
 21%|██▏       | 457/2129 [00:32<02:38, 10.53it/s]
 22%|██▏       | 459/2129 [00:32<02:36, 10.65it/s]
 22%|██▏       | 461/2129 [00:32<02:19, 11.99it/s]
 22%|██▏       | 464/2129 [00:32<02:00, 13.86it/s]
 22%|██▏       | 466/2129 [00:32<02:07, 13.08it/s]
 22%|██▏       | 468/2129 [00:33<01:58, 13.98it/s]
 22%|██▏       | 470/2129 [00:33<01:49, 15.12it/s]
 22%|██▏       | 472/2129 [00:33<01:56, 14.21it/s]
 22%|██▏       | 474/2129 [00:33<01:55, 14.35it/s]
 22%|██▏       | 476/2129 [00:33<01:49, 15.14it/s]
 22%|██▏       | 478/2129 [00:33<02:26, 11.26it/s]
 23%|██▎       | 480/2129 [00:33<02:09, 12.72it/s]
 23%|██▎       | 482/2129 [00:34<02:01, 13.56it/s]
 23%|██▎       | 484/2129 [00:34<02:56,  9.33it/s]
 23%|██▎       | 486/2129 [00:34<02:38, 10.34it/s]
 23%|██▎       | 490/2129 [00:34<02:11, 12.49it/s]
 23%|██▎       | 492/2129 [00:34<02:02, 13.41it/s]
 23%|██▎       | 496/2129 [00:35<01:57, 13.88it/s]
 23%|██▎       | 498/2129 [00:35<01:58, 13.79it/s]
 24%|██▎       | 501/2129 [00:35<01:52, 14.53it/s]
 24%|██▎       | 503/2129 [00:35<01:54, 14.23it/s]
 24%|██▍       | 506/2129 [00:35<01:34, 17.15it/s]
 24%|██▍       | 508/2129 [00:36<02:02, 13.23it/s]
 24%|██▍       | 510/2129 [00:36<02:04, 12.98it/s]
 24%|██▍       | 512/2129 [00:36<01:58, 13.66it/s]
 24%|██▍       | 515/2129 [00:36<02:07, 12.68it/s]
 24%|██▍       | 517/2129 [00:36<02:26, 11.03it/s]
 24%|██▍       | 520/2129 [00:37<02:26, 10.95it/s]
 25%|██▍       | 522/2129 [00:37<03:10,  8.44it/s]
 25%|██▍       | 525/2129 [00:37<02:25, 10.99it/s]
 25%|██▍       | 527/2129 [00:37<02:37, 10.15it/s]
 25%|██▍       | 529/2129 [00:38<03:22,  7.89it/s]
 25%|██▍       | 531/2129 [00:38<03:43,  7.14it/s]
 25%|██▌       | 533/2129 [00:38<03:03,  8.70it/s]
 25%|██▌       | 535/2129 [00:39<03:19,  7.98it/s]
 25%|██▌       | 537/2129 [00:39<03:16,  8.11it/s]
 25%|██▌       | 540/2129 [00:39<02:31, 10.46it/s]
 26%|██▌       | 543/2129 [00:39<02:26, 10.79it/s]
 26%|██▌       | 545/2129 [00:39<02:10, 12.13it/s]
 26%|██▌       | 547/2129 [00:40<02:16, 11.55it/s]
 26%|██▌       | 549/2129 [00:40<02:35, 10.17it/s]
 26%|██▌       | 552/2129 [00:40<01:58, 13.27it/s]
 26%|██▌       | 557/2129 [00:40<01:41, 15.50it/s]
 26%|██▋       | 559/2129 [00:40<02:01, 12.94it/s]
 26%|██▋       | 561/2129 [00:41<01:52, 13.94it/s]
 26%|██▋       | 564/2129 [00:41<01:56, 13.47it/s]
 27%|██▋       | 566/2129 [00:41<02:11, 11.84it/s]
 27%|██▋       | 568/2129 [00:41<02:23, 10.85it/s]
 27%|██▋       | 570/2129 [00:41<02:36,  9.99it/s]
 27%|██▋       | 572/2129 [00:42<02:51,  9.10it/s]
 27%|██▋       | 573/2129 [00:42<03:14,  7.98it/s]
 27%|██▋       | 576/2129 [00:42<02:21, 10.99it/s]
 27%|██▋       | 578/2129 [00:42<02:31, 10.21it/s]
 27%|██▋       | 581/2129 [00:43<02:33, 10.11it/s]
 27%|██▋       | 583/2129 [00:43<02:42,  9.49it/s]
 27%|██▋       | 585/2129 [00:43<03:00,  8.55it/s]
 28%|██▊       | 586/2129 [00:43<03:18,  7.79it/s]
 28%|██▊       | 587/2129 [00:44<03:30,  7.33it/s]
 28%|██▊       | 589/2129 [00:44<03:21,  7.62it/s]
 28%|██▊       | 591/2129 [00:44<02:53,  8.87it/s]
 28%|██▊       | 593/2129 [00:44<02:25, 10.57it/s]
 28%|██▊       | 596/2129 [00:44<01:59, 12.87it/s]
 28%|██▊       | 599/2129 [00:44<02:08, 11.93it/s]
 28%|██▊       | 602/2129 [00:45<02:03, 12.40it/s]
 28%|██▊       | 605/2129 [00:45<01:51, 13.70it/s]
 29%|██▊       | 608/2129 [00:45<01:37, 15.66it/s]
 29%|██▊       | 610/2129 [00:45<01:54, 13.30it/s]
 29%|██▊       | 612/2129 [00:45<02:14, 11.28it/s]
 29%|██▉       | 614/2129 [00:46<02:26, 10.33it/s]
 29%|██▉       | 616/2129 [00:46<02:41,  9.35it/s]
 29%|██▉       | 621/2129 [00:46<01:38, 15.34it/s]
 29%|██▉       | 624/2129 [00:46<01:48, 13.89it/s]
 29%|██▉       | 626/2129 [00:47<02:07, 11.78it/s]
 29%|██▉       | 628/2129 [00:47<02:20, 10.71it/s]
 30%|██▉       | 630/2129 [00:47<02:04, 12.07it/s]
 30%|██▉       | 632/2129 [00:47<02:17, 10.90it/s]
 30%|██▉       | 634/2129 [00:47<02:00, 12.44it/s]
 30%|██▉       | 636/2129 [00:48<02:10, 11.48it/s]
 30%|███       | 639/2129 [00:48<01:45, 14.14it/s]
 30%|███       | 641/2129 [00:48<02:36,  9.52it/s]
 30%|███       | 644/2129 [00:48<02:41,  9.18it/s]
 30%|███       | 646/2129 [00:49<02:48,  8.80it/s]
 30%|███       | 649/2129 [00:49<02:36,  9.43it/s]
 31%|███       | 651/2129 [00:49<02:16, 10.85it/s]
 31%|███       | 653/2129 [00:49<02:26, 10.04it/s]
 31%|███       | 655/2129 [00:49<02:13, 11.02it/s]
 31%|███       | 657/2129 [00:50<02:27,  9.96it/s]
 31%|███       | 659/2129 [00:50<02:34,  9.53it/s]
 31%|███       | 661/2129 [00:50<02:39,  9.23it/s]
 31%|███       | 663/2129 [00:51<03:18,  7.39it/s]
 31%|███▏      | 666/2129 [00:51<02:22, 10.29it/s]
 31%|███▏      | 668/2129 [00:51<02:05, 11.67it/s]
 31%|███▏      | 670/2129 [00:51<01:50, 13.18it/s]
 32%|███▏      | 672/2129 [00:51<02:18, 10.50it/s]
 32%|███▏      | 674/2129 [00:51<02:05, 11.60it/s]
 32%|███▏      | 677/2129 [00:51<01:56, 12.48it/s]
 32%|███▏      | 680/2129 [00:52<02:03, 11.70it/s]
 32%|███▏      | 682/2129 [00:52<02:10, 11.09it/s]
 32%|███▏      | 684/2129 [00:52<02:29,  9.68it/s]
 32%|███▏      | 686/2129 [00:52<02:36,  9.21it/s]
 32%|███▏      | 688/2129 [00:53<02:44,  8.77it/s]
 32%|███▏      | 689/2129 [00:53<03:05,  7.77it/s]
 33%|███▎      | 692/2129 [00:53<02:12, 10.86it/s]
 33%|███▎      | 694/2129 [00:53<02:17, 10.45it/s]
 33%|███▎      | 696/2129 [00:54<02:25,  9.88it/s]
 33%|███▎      | 698/2129 [00:54<02:05, 11.39it/s]
 33%|███▎      | 700/2129 [00:54<01:53, 12.56it/s]
 33%|███▎      | 702/2129 [00:54<01:42, 13.90it/s]
 33%|███▎      | 704/2129 [00:54<02:01, 11.77it/s]
 33%|███▎      | 706/2129 [00:54<02:29,  9.50it/s]
 33%|███▎      | 708/2129 [00:55<03:01,  7.83it/s]
 33%|███▎      | 710/2129 [00:55<02:31,  9.38it/s]
 33%|███▎      | 712/2129 [00:55<02:53,  8.18it/s]
 34%|███▎      | 714/2129 [00:55<02:55,  8.06it/s]
 34%|███▎      | 717/2129 [00:56<02:10, 10.83it/s]
 34%|███▍      | 720/2129 [00:56<01:40, 13.98it/s]
 34%|███▍      | 722/2129 [00:56<01:58, 11.86it/s]
 34%|███▍      | 724/2129 [00:56<02:54,  8.06it/s]
 34%|███▍      | 726/2129 [00:57<03:27,  6.76it/s]
 34%|███▍      | 727/2129 [00:57<03:51,  6.05it/s]
 34%|███▍      | 728/2129 [00:57<03:56,  5.93it/s]
 34%|███▍      | 730/2129 [00:57<03:07,  7.44it/s]
 34%|███▍      | 733/2129 [00:58<02:31,  9.23it/s]
 35%|███▍      | 735/2129 [00:58<02:33,  9.08it/s]
 35%|███▍      | 738/2129 [00:58<01:52, 12.34it/s]
 35%|███▍      | 740/2129 [00:58<01:51, 12.51it/s]
 35%|███▍      | 743/2129 [00:58<01:28, 15.67it/s]
 35%|███▍      | 745/2129 [00:58<01:23, 16.56it/s]
 35%|███▌      | 749/2129 [00:58<01:04, 21.28it/s]
 35%|███▌      | 752/2129 [00:59<01:31, 15.12it/s]
 35%|███▌      | 754/2129 [00:59<02:02, 11.22it/s]
 36%|███▌      | 756/2129 [00:59<01:56, 11.80it/s]
 36%|███▌      | 758/2129 [00:59<01:46, 12.83it/s]
 36%|███▌      | 762/2129 [00:59<01:21, 16.74it/s]
 36%|███▌      | 764/2129 [01:00<01:42, 13.38it/s]
 36%|███▌      | 766/2129 [01:00<01:58, 11.46it/s]
 36%|███▌      | 768/2129 [01:00<02:12, 10.29it/s]
 36%|███▌      | 770/2129 [01:00<02:20,  9.69it/s]
 36%|███▋      | 774/2129 [01:01<02:01, 11.17it/s]
 36%|███▋      | 776/2129 [01:01<02:33,  8.82it/s]
 37%|███▋      | 778/2129 [01:01<02:11, 10.25it/s]
 37%|███▋      | 780/2129 [01:01<02:19,  9.65it/s]
 37%|███▋      | 782/2129 [01:02<02:52,  7.79it/s]
 37%|███▋      | 785/2129 [01:02<02:36,  8.60it/s]
 37%|███▋      | 787/2129 [01:02<02:14,  9.97it/s]
 37%|███▋      | 792/2129 [01:02<01:42, 13.05it/s]
 37%|███▋      | 794/2129 [01:03<01:57, 11.33it/s]
 37%|███▋      | 796/2129 [01:03<02:31,  8.82it/s]
 37%|███▋      | 798/2129 [01:03<02:38,  8.39it/s]
 38%|███▊      | 800/2129 [01:04<02:48,  7.89it/s]
 38%|███▊      | 802/2129 [01:04<02:48,  7.87it/s]
 38%|███▊      | 803/2129 [01:04<03:15,  6.78it/s]
 38%|███▊      | 806/2129 [01:04<02:20,  9.40it/s]
 38%|███▊      | 809/2129 [01:05<02:17,  9.60it/s]
 38%|███▊      | 811/2129 [01:05<02:29,  8.82it/s]
 38%|███▊      | 813/2129 [01:05<02:39,  8.26it/s]
 38%|███▊      | 817/2129 [01:05<01:45, 12.47it/s]
 38%|███▊      | 819/2129 [01:06<01:48, 12.05it/s]
 39%|███▊      | 821/2129 [01:06<01:49, 11.91it/s]
 39%|███▊      | 823/2129 [01:06<01:44, 12.49it/s]
 39%|███▉      | 827/2129 [01:06<01:36, 13.48it/s]
 39%|███▉      | 829/2129 [01:06<01:30, 14.32it/s]
 39%|███▉      | 835/2129 [01:06<01:14, 17.40it/s]
 39%|███▉      | 838/2129 [01:07<01:29, 14.44it/s]
 39%|███▉      | 840/2129 [01:07<01:43, 12.50it/s]
 40%|███▉      | 842/2129 [01:07<01:51, 11.56it/s]
 40%|███▉      | 844/2129 [01:08<02:34,  8.33it/s]
 40%|███▉      | 845/2129 [01:08<02:51,  7.47it/s]
 40%|███▉      | 846/2129 [01:08<03:09,  6.77it/s]
 40%|███▉      | 848/2129 [01:08<03:07,  6.82it/s]
 40%|███▉      | 850/2129 [01:09<02:32,  8.39it/s]
 40%|████      | 852/2129 [01:09<02:23,  8.93it/s]
 40%|████      | 854/2129 [01:09<02:01, 10.53it/s]
 40%|████      | 856/2129 [01:09<01:50, 11.49it/s]
 40%|████      | 859/2129 [01:09<01:26, 14.75it/s]
 40%|████      | 861/2129 [01:09<01:31, 13.79it/s]
 41%|████      | 863/2129 [01:10<01:48, 11.67it/s]
 41%|████      | 865/2129 [01:10<02:03, 10.24it/s]
 41%|████      | 867/2129 [01:10<02:28,  8.49it/s]
 41%|████      | 870/2129 [01:10<02:21,  8.87it/s]
 41%|████      | 873/2129 [01:11<02:09,  9.67it/s]
 41%|████      | 875/2129 [01:11<02:15,  9.24it/s]
 41%|████      | 877/2129 [01:11<02:26,  8.55it/s]
 41%|████▏     | 879/2129 [01:11<02:32,  8.19it/s]
 41%|████▏     | 882/2129 [01:12<01:55, 10.79it/s]
 42%|████▏     | 886/2129 [01:12<01:37, 12.76it/s]
 42%|████▏     | 888/2129 [01:12<01:51, 11.17it/s]
 42%|████▏     | 891/2129 [01:12<01:51, 11.10it/s]
 42%|████▏     | 893/2129 [01:13<02:08,  9.60it/s]
 42%|████▏     | 895/2129 [01:13<02:15,  9.12it/s]
 42%|████▏     | 898/2129 [01:13<02:11,  9.35it/s]
 42%|████▏     | 901/2129 [01:13<01:42, 12.04it/s]
 42%|████▏     | 903/2129 [01:14<01:54, 10.71it/s]
 43%|████▎     | 906/2129 [01:14<01:53, 10.81it/s]
 43%|████▎     | 908/2129 [01:14<02:06,  9.63it/s]
 43%|████▎     | 910/2129 [01:14<01:52, 10.85it/s]
 43%|████▎     | 912/2129 [01:15<02:17,  8.84it/s]
 43%|████▎     | 914/2129 [01:15<02:05,  9.67it/s]
 43%|████▎     | 916/2129 [01:15<02:06,  9.63it/s]
 43%|████▎     | 919/2129 [01:15<01:39, 12.13it/s]
 43%|████▎     | 925/2129 [01:15<01:12, 16.68it/s]
 44%|████▎     | 927/2129 [01:16<01:36, 12.45it/s]
 44%|████▎     | 929/2129 [01:16<01:48, 11.05it/s]
 44%|████▎     | 931/2129 [01:16<02:03,  9.68it/s]
 44%|████▍     | 936/2129 [01:16<01:36, 12.31it/s]
 44%|████▍     | 938/2129 [01:17<01:52, 10.54it/s]
 44%|████▍     | 940/2129 [01:17<01:58, 10.03it/s]
 44%|████▍     | 943/2129 [01:17<01:39, 11.93it/s]
 44%|████▍     | 945/2129 [01:17<02:01,  9.77it/s]
 44%|████▍     | 947/2129 [01:18<01:58,  9.98it/s]
 45%|████▍     | 949/2129 [01:18<01:49, 10.74it/s]
 45%|████▍     | 951/2129 [01:18<01:52, 10.51it/s]
 45%|████▍     | 956/2129 [01:18<01:08, 17.00it/s]
 45%|████▌     | 959/2129 [01:18<01:19, 14.66it/s]
 45%|████▌     | 961/2129 [01:19<01:55, 10.13it/s]
 45%|████▌     | 963/2129 [01:19<01:57,  9.89it/s]
 45%|████▌     | 965/2129 [01:19<02:06,  9.20it/s]
 45%|████▌     | 967/2129 [01:20<02:11,  8.84it/s]
 46%|████▌     | 969/2129 [01:20<02:15,  8.56it/s]
 46%|████▌     | 970/2129 [01:20<02:30,  7.72it/s]
 46%|████▌     | 973/2129 [01:20<02:11,  8.77it/s]
 46%|████▌     | 974/2129 [01:20<02:33,  7.52it/s]
 46%|████▌     | 977/2129 [01:21<02:19,  8.28it/s]
 46%|████▌     | 979/2129 [01:21<01:58,  9.67it/s]
 46%|████▌     | 981/2129 [01:21<01:56,  9.82it/s]
 46%|████▌     | 984/2129 [01:21<01:28, 12.96it/s]
 46%|████▋     | 988/2129 [01:21<01:18, 14.51it/s]
 47%|████▋     | 991/2129 [01:22<01:08, 16.52it/s]
 47%|████▋     | 993/2129 [01:22<01:18, 14.51it/s]
 47%|████▋     | 996/2129 [01:22<01:08, 16.47it/s]
 47%|████▋     | 1001/2129 [01:22<01:04, 17.46it/s]
 47%|████▋     | 1003/2129 [01:22<01:23, 13.42it/s]
 47%|████▋     | 1006/2129 [01:23<01:27, 12.79it/s]
 47%|████▋     | 1009/2129 [01:23<01:14, 14.95it/s]
 47%|████▋     | 1011/2129 [01:23<01:29, 12.55it/s]
 48%|████▊     | 1013/2129 [01:24<02:02,  9.08it/s]
 48%|████▊     | 1015/2129 [01:24<02:12,  8.40it/s]
 48%|████▊     | 1017/2129 [01:24<02:18,  8.05it/s]
 48%|████▊     | 1019/2129 [01:24<02:15,  8.17it/s]
 48%|████▊     | 1021/2129 [01:24<01:56,  9.50it/s]
 48%|████▊     | 1023/2129 [01:25<02:02,  8.99it/s]
 48%|████▊     | 1025/2129 [01:25<02:05,  8.78it/s]
 48%|████▊     | 1028/2129 [01:25<01:55,  9.55it/s]
 48%|████▊     | 1030/2129 [01:25<02:02,  8.95it/s]
 48%|████▊     | 1031/2129 [01:26<02:17,  8.01it/s]
 49%|████▊     | 1034/2129 [01:26<01:39, 11.05it/s]
 49%|████▉     | 1040/2129 [01:26<01:13, 14.88it/s]
 49%|████▉     | 1042/2129 [01:26<01:25, 12.75it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 313.90it/s]

[[np.int64(0), False, 10], [np.int64(1), False, 5], [np.int64(2), False, 10], [np.int64(3), False, 0], [np.int64(4), False, 13], [np.int64(5), False, 6], [np.int64(7), False, 3], [np.int64(8), False, 10], [np.int64(9), False, 2], [np.int64(11), False, 10], [np.int64(12), False, 11], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.6563, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-1.4946, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [03:02<2:51:11, 51.62s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [03:02<1:59:22, 36.17s/it]

tensor(12.6576, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-1.8551, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.3337, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:02<58:06, 17.79s/it]

tensor(12.8256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6405, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.7751, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [03:02<19:52,  6.18s/it]

tensor(12.9793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8196, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8859, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [03:03<09:49,  3.09s/it]

tensor(12.9390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0150, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1768, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [03:03<04:57,  1.57s/it]

tensor(12.8376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3203, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8347, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4216, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [03:03<03:33,  1.14s/it]

tensor(12.8435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4768, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5190, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [03:03<01:56,  1.59it/s]

tensor(12.7393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5975, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6684, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:04<01:07,  2.71it/s]

tensor(12.6826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7619, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6897, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8339, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [03:04<00:36,  4.89it/s]

tensor(12.6911, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8819, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9091, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [03:04<00:28,  6.23it/s]

tensor(12.6496, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9145, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9553, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [03:04<00:26,  6.73it/s]

tensor(12.5761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9785, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0084, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [03:04<00:23,  7.41it/s]

tensor(12.5165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0462, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0816, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [03:05<00:21,  7.94it/s]

tensor(12.4816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1091, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1378, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [03:05<00:21,  8.00it/s]

tensor(12.4504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1678, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4380, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2088, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [03:05<00:20,  8.15it/s]

tensor(12.4279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2349, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2626, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [03:05<00:20,  8.15it/s]

tensor(12.4038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3603, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [03:06<00:20,  8.21it/s]

tensor(12.3713, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3978, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4156, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [03:06<00:19,  8.20it/s]

tensor(12.3448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4409, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3347, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4642, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [03:06<00:19,  8.23it/s]

tensor(12.3251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4735, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5079, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [03:06<00:19,  8.22it/s]

tensor(12.3050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5386, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2931, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5542, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:07<00:19,  8.20it/s]

tensor(12.2799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5898, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:07<00:18,  8.23it/s]

tensor(12.2543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6061, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6207, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [03:07<00:18,  8.21it/s]

tensor(12.2339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6404, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6569, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:07<00:18,  8.22it/s]

tensor(12.2143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6722, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6805, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:08<00:18,  8.23it/s]

tensor(12.1958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6970, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([383, 157, 118,  60,  79, 293, 131, 296,  73, 277,  82,  50,  54,  76])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 6/2129 [00:00<00:38, 55.27it/s]
  1%|          | 12/2129 [00:00<00:38, 55.60it/s]
  1%|          | 18/2129 [00:00<00:40, 51.80it/s]
  1%|          | 24/2129 [00:00<01:16, 27.40it/s]
  1%|▏         | 28/2129 [00:00<01:13, 28.75it/s]
  2%|▏         | 32/2129 [00:01<01:21, 25.86it/s]
  2%|▏         | 37/2129 [00:01<01:08, 30.68it/s]
  2%|▏         | 43/2129 [00:01<01:45, 19.81it/s]
  2%|▏         | 46/2129 [00:01<01:39, 20.83it/s]
  2%|▏         | 49/2129 [00:02<02:28, 14.03it/s]
  2%|▏         | 52/2129 [00:02<02:56, 11.80it/s]
  3%|▎         | 54/2129 [00:02<03:05, 11.18it/s]
  3%|▎         | 57/2129 [00:02<02:35, 13.36it/s]
  3%|▎         | 59/2129 [00:03<03:16, 10.55it/s]
  3%|▎         | 61/2129 [00:03<03:04, 11.19it/s]
  3%|▎         | 65/2129 [00:03<03:34,  9.61it/s]
  3%|▎         | 67/2129 [00:04<03:21, 10.23it/s]
  3%|▎         | 70/2129 [00:04<02:40, 12.82it/s]
  3%|▎         | 72/2129 [00:04<02:48, 12.23it/s]
  3%|▎         | 74/2129 [00:04<03:06, 11.05it/s]
  4%|▎         | 76/2129 [00:04<02:47, 12.25it/s]
  4%|▍         | 80/2129 [00:04<02:38, 12.91it/s]
  4%|▍         | 82/2129 [00:05<03:45,  9.09it/s]
  4%|▍         | 86/2129 [00:05<03:16, 10.39it/s]
  4%|▍         | 89/2129 [00:05<02:41, 12.64it/s]
  5%|▍         | 96/2129 [00:06<02:02, 16.63it/s]
  5%|▍         | 99/2129 [00:06<01:52, 18.05it/s]
  5%|▍         | 102/2129 [00:06<02:12, 15.32it/s]
  5%|▍         | 104/2129 [00:06<03:14, 10.44it/s]
  5%|▍         | 106/2129 [00:07<02:53, 11.63it/s]
  5%|▌         | 110/2129 [00:07<03:22,  9.98it/s]
  5%|▌         | 113/2129 [00:07<03:24,  9.88it/s]
  5%|▌         | 115/2129 [00:08<04:15,  7.87it/s]
  6%|▌         | 120/2129 [00:08<02:42, 12.37it/s]
  6%|▌         | 125/2129 [00:08<02:18, 14.46it/s]
  6%|▌         | 128/2129 [00:08<02:04, 16.03it/s]
  6%|▌         | 132/2129 [00:09<02:05, 15.97it/s]
  6%|▋         | 134/2129 [00:09<03:00, 11.08it/s]
  6%|▋         | 137/2129 [00:09<02:33, 12.95it/s]
  7%|▋         | 144/2129 [00:09<01:32, 21.41it/s]
  7%|▋         | 148/2129 [00:09<01:24, 23.47it/s]
  7%|▋         | 152/2129 [00:10<01:50, 17.88it/s]
  7%|▋         | 155/2129 [00:10<01:41, 19.48it/s]
  7%|▋         | 158/2129 [00:10<02:44, 11.98it/s]
  8%|▊         | 161/2129 [00:11<03:07, 10.48it/s]
  8%|▊         | 163/2129 [00:11<03:24,  9.61it/s]
  8%|▊         | 165/2129 [00:11<03:39,  8.95it/s]
  8%|▊         | 167/2129 [00:11<03:24,  9.57it/s]
  8%|▊         | 169/2129 [00:12<03:36,  9.05it/s]
  8%|▊         | 171/2129 [00:12<03:09, 10.33it/s]
  8%|▊         | 173/2129 [00:12<03:18,  9.85it/s]
  8%|▊         | 175/2129 [00:12<02:51, 11.42it/s]
  8%|▊         | 177/2129 [00:13<04:43,  6.88it/s]
  8%|▊         | 179/2129 [00:13<05:34,  5.84it/s]
  8%|▊         | 180/2129 [00:13<05:26,  5.97it/s]
  9%|▊         | 182/2129 [00:13<04:11,  7.73it/s]
  9%|▊         | 184/2129 [00:14<05:04,  6.38it/s]
  9%|▊         | 186/2129 [00:14<04:52,  6.64it/s]
  9%|▉         | 187/2129 [00:14<05:28,  5.91it/s]
  9%|▉         | 188/2129 [00:15<05:25,  5.97it/s]
  9%|▉         | 190/2129 [00:15<05:59,  5.39it/s]
  9%|▉         | 193/2129 [00:15<03:55,  8.22it/s]
  9%|▉         | 195/2129 [00:16<04:51,  6.63it/s]
  9%|▉         | 197/2129 [00:16<03:53,  8.28it/s]
  9%|▉         | 200/2129 [00:16<03:48,  8.44it/s]
  9%|▉         | 202/2129 [00:17<05:29,  5.84it/s]
 10%|▉         | 205/2129 [00:17<03:58,  8.05it/s]
 10%|▉         | 212/2129 [00:17<02:30, 12.73it/s]
 10%|█         | 214/2129 [00:18<03:51,  8.26it/s]
 10%|█         | 216/2129 [00:18<04:24,  7.22it/s]
 10%|█         | 219/2129 [00:18<03:27,  9.19it/s]
 10%|█         | 221/2129 [00:18<03:28,  9.13it/s]
 10%|█         | 223/2129 [00:19<04:57,  6.41it/s]
 11%|█         | 225/2129 [00:19<04:41,  6.77it/s]
 11%|█         | 226/2129 [00:19<04:33,  6.96it/s]
 11%|█         | 228/2129 [00:20<04:38,  6.83it/s]
 11%|█         | 230/2129 [00:20<03:42,  8.54it/s]
 11%|█         | 232/2129 [00:20<03:40,  8.58it/s]
 11%|█         | 234/2129 [00:20<04:27,  7.07it/s]
 11%|█         | 236/2129 [00:21<03:44,  8.44it/s]
 11%|█         | 239/2129 [00:21<04:17,  7.34it/s]
 11%|█▏        | 242/2129 [00:21<03:14,  9.69it/s]
 12%|█▏        | 246/2129 [00:22<03:42,  8.47it/s]
 12%|█▏        | 248/2129 [00:22<03:52,  8.07it/s]
 12%|█▏        | 250/2129 [00:23<05:15,  5.95it/s]
 12%|█▏        | 252/2129 [00:23<05:04,  6.16it/s]
 12%|█▏        | 255/2129 [00:23<05:11,  6.01it/s]
 12%|█▏        | 258/2129 [00:24<05:26,  5.73it/s]
 12%|█▏        | 259/2129 [00:24<06:26,  4.84it/s]
 12%|█▏        | 260/2129 [00:25<07:33,  4.12it/s]
 12%|█▏        | 261/2129 [00:25<09:18,  3.35it/s]
 12%|█▏        | 265/2129 [00:26<06:34,  4.73it/s]
 13%|█▎        | 267/2129 [00:26<06:11,  5.01it/s]
 13%|█▎        | 269/2129 [00:26<05:28,  5.67it/s]
 13%|█▎        | 271/2129 [00:27<05:50,  5.31it/s]
 13%|█▎        | 274/2129 [00:27<04:06,  7.53it/s]
 13%|█▎        | 276/2129 [00:28<05:26,  5.68it/s]
 13%|█▎        | 280/2129 [00:28<03:25,  8.98it/s]
 13%|█▎        | 285/2129 [00:28<03:15,  9.42it/s]
 13%|█▎        | 287/2129 [00:29<04:12,  7.30it/s]
 14%|█▎        | 290/2129 [00:29<03:20,  9.16it/s]
 14%|█▎        | 292/2129 [00:29<04:26,  6.88it/s]
 14%|█▍        | 294/2129 [00:30<04:15,  7.18it/s]
 14%|█▍        | 296/2129 [00:30<04:30,  6.79it/s]
 14%|█▍        | 298/2129 [00:30<04:12,  7.24it/s]
 14%|█▍        | 301/2129 [00:30<03:10,  9.61it/s]
 14%|█▍        | 304/2129 [00:31<03:14,  9.38it/s]
 14%|█▍        | 306/2129 [00:31<04:41,  6.49it/s]
 15%|█▍        | 312/2129 [00:32<03:52,  7.81it/s]
 15%|█▍        | 313/2129 [00:32<04:05,  7.40it/s]
 15%|█▍        | 314/2129 [00:33<05:34,  5.43it/s]
 15%|█▍        | 315/2129 [00:33<05:39,  5.34it/s]
 15%|█▍        | 318/2129 [00:33<03:46,  8.00it/s]
 15%|█▌        | 320/2129 [00:33<03:43,  8.08it/s]
 15%|█▌        | 322/2129 [00:33<03:52,  7.78it/s]
 15%|█▌        | 324/2129 [00:34<04:49,  6.23it/s]
 15%|█▌        | 326/2129 [00:34<03:51,  7.77it/s]
 15%|█▌        | 328/2129 [00:35<05:02,  5.96it/s]
 16%|█▌        | 330/2129 [00:35<04:31,  6.64it/s]
 16%|█▌        | 331/2129 [00:35<04:51,  6.17it/s]
 16%|█▌        | 334/2129 [00:36<05:11,  5.76it/s]
 16%|█▌        | 337/2129 [00:36<05:26,  5.49it/s]
 16%|█▌        | 340/2129 [00:37<05:12,  5.72it/s]
 16%|█▌        | 342/2129 [00:37<04:45,  6.25it/s]
 16%|█▌        | 343/2129 [00:37<06:52,  4.33it/s]
 16%|█▌        | 345/2129 [00:38<06:36,  4.50it/s]
 16%|█▋        | 346/2129 [00:38<06:48,  4.36it/s]
 16%|█▋        | 349/2129 [00:39<05:49,  5.10it/s]
 16%|█▋        | 350/2129 [00:39<06:36,  4.49it/s]
 17%|█▋        | 353/2129 [00:39<04:22,  6.75it/s]
 17%|█▋        | 354/2129 [00:39<04:43,  6.26it/s]
 17%|█▋        | 355/2129 [00:40<06:42,  4.41it/s]
 17%|█▋        | 356/2129 [00:40<06:29,  4.55it/s]
 17%|█▋        | 357/2129 [00:40<06:07,  4.82it/s]
 17%|█▋        | 358/2129 [00:40<05:45,  5.13it/s]
 17%|█▋        | 359/2129 [00:41<07:51,  3.75it/s]
 17%|█▋        | 361/2129 [00:41<08:01,  3.67it/s]
 17%|█▋        | 362/2129 [00:42<09:42,  3.03it/s]
 17%|█▋        | 363/2129 [00:42<08:00,  3.67it/s]
 17%|█▋        | 364/2129 [00:42<07:20,  4.00it/s]
 17%|█▋        | 367/2129 [00:42<04:06,  7.16it/s]
 18%|█▊        | 373/2129 [00:43<03:24,  8.59it/s]
 18%|█▊        | 375/2129 [00:43<04:10,  7.00it/s]
 18%|█▊        | 376/2129 [00:44<05:51,  4.99it/s]
 18%|█▊        | 377/2129 [00:44<05:45,  5.06it/s]
 18%|█▊        | 380/2129 [00:44<04:24,  6.60it/s]
 18%|█▊        | 383/2129 [00:45<03:15,  8.95it/s]
 18%|█▊        | 385/2129 [00:45<03:57,  7.34it/s]
 18%|█▊        | 387/2129 [00:46<06:37,  4.38it/s]
 18%|█▊        | 389/2129 [00:46<05:15,  5.52it/s]
 18%|█▊        | 391/2129 [00:46<04:41,  6.17it/s]
 18%|█▊        | 392/2129 [00:47<06:03,  4.78it/s]
 19%|█▊        | 394/2129 [00:47<05:09,  5.61it/s]
 19%|█▊        | 397/2129 [00:47<03:32,  8.14it/s]
 19%|█▉        | 400/2129 [00:47<03:03,  9.45it/s]
 19%|█▉        | 402/2129 [00:48<03:59,  7.21it/s]
 19%|█▉        | 404/2129 [00:48<04:00,  7.17it/s]
 19%|█▉        | 405/2129 [00:48<04:19,  6.64it/s]
 19%|█▉        | 406/2129 [00:49<05:53,  4.87it/s]
 19%|█▉        | 408/2129 [00:49<05:00,  5.73it/s]
 19%|█▉        | 410/2129 [00:49<03:50,  7.45it/s]
 19%|█▉        | 414/2129 [00:49<03:33,  8.02it/s]
 19%|█▉        | 415/2129 [00:50<04:46,  5.98it/s]
 20%|█▉        | 417/2129 [00:50<03:47,  7.53it/s]
 20%|█▉        | 421/2129 [00:50<03:36,  7.88it/s]
 20%|█▉        | 423/2129 [00:51<04:18,  6.61it/s]
 20%|██        | 426/2129 [00:51<03:10,  8.92it/s]
 20%|██        | 428/2129 [00:51<03:05,  9.18it/s]
 20%|██        | 430/2129 [00:52<04:33,  6.22it/s]
 20%|██        | 432/2129 [00:52<05:24,  5.24it/s]
 20%|██        | 433/2129 [00:53<05:16,  5.35it/s]
 20%|██        | 436/2129 [00:53<05:25,  5.21it/s]
 21%|██        | 438/2129 [00:53<04:17,  6.57it/s]
 21%|██        | 440/2129 [00:54<05:27,  5.15it/s]
 21%|██        | 442/2129 [00:54<04:59,  5.63it/s]
 21%|██        | 443/2129 [00:55<06:20,  4.43it/s]
 21%|██        | 444/2129 [00:55<07:25,  3.78it/s]
 21%|██        | 446/2129 [00:55<05:50,  4.81it/s]
 21%|██        | 448/2129 [00:55<04:22,  6.39it/s]
 21%|██        | 451/2129 [00:56<03:27,  8.09it/s]
 21%|██▏       | 453/2129 [00:56<02:53,  9.64it/s]
 21%|██▏       | 455/2129 [00:56<04:13,  6.61it/s]
 21%|██▏       | 457/2129 [00:57<06:49,  4.09it/s]
 22%|██▏       | 459/2129 [00:58<07:19,  3.80it/s]
 22%|██▏       | 460/2129 [00:58<08:00,  3.47it/s]
 22%|██▏       | 463/2129 [00:58<05:03,  5.50it/s]
 22%|██▏       | 466/2129 [00:59<03:55,  7.08it/s]
 22%|██▏       | 468/2129 [00:59<05:03,  5.47it/s]
 22%|██▏       | 470/2129 [00:59<04:03,  6.82it/s]
 22%|██▏       | 472/2129 [01:00<05:06,  5.40it/s]
 22%|██▏       | 473/2129 [01:00<05:21,  5.14it/s]
 22%|██▏       | 475/2129 [01:00<04:46,  5.77it/s]
 22%|██▏       | 477/2129 [01:01<05:41,  4.83it/s]
 22%|██▏       | 478/2129 [01:01<06:07,  4.50it/s]
 23%|██▎       | 480/2129 [01:01<04:32,  6.06it/s]
 23%|██▎       | 482/2129 [01:01<04:05,  6.71it/s]
 23%|██▎       | 483/2129 [01:02<06:02,  4.54it/s]
 23%|██▎       | 484/2129 [01:02<05:55,  4.62it/s]
 23%|██▎       | 486/2129 [01:03<06:03,  4.52it/s]
 23%|██▎       | 487/2129 [01:03<07:43,  3.54it/s]
 23%|██▎       | 488/2129 [01:03<07:07,  3.84it/s]
 23%|██▎       | 490/2129 [01:04<06:23,  4.28it/s]
 23%|██▎       | 492/2129 [01:04<04:49,  5.65it/s]
 23%|██▎       | 494/2129 [01:04<05:25,  5.02it/s]
 23%|██▎       | 496/2129 [01:05<05:05,  5.34it/s]
 23%|██▎       | 499/2129 [01:05<03:24,  7.95it/s]
 24%|██▎       | 501/2129 [01:05<04:28,  6.05it/s]
 24%|██▎       | 504/2129 [01:05<03:12,  8.45it/s]
 24%|██▍       | 508/2129 [01:06<03:28,  7.76it/s]
 24%|██▍       | 510/2129 [01:06<03:29,  7.73it/s]
 24%|██▍       | 512/2129 [01:07<03:27,  7.78it/s]
 24%|██▍       | 515/2129 [01:07<04:07,  6.52it/s]
 24%|██▍       | 517/2129 [01:08<04:55,  5.45it/s]
 24%|██▍       | 520/2129 [01:08<05:14,  5.12it/s]
 24%|██▍       | 521/2129 [01:09<05:12,  5.15it/s]
 25%|██▍       | 522/2129 [01:09<05:16,  5.08it/s]
 25%|██▍       | 524/2129 [01:09<04:07,  6.49it/s]
 25%|██▍       | 525/2129 [01:09<04:46,  5.60it/s]
 25%|██▍       | 526/2129 [01:09<05:26,  4.91it/s]
 25%|██▍       | 527/2129 [01:10<05:30,  4.84it/s]
 25%|██▍       | 528/2129 [01:10<06:50,  3.90it/s]
 25%|██▍       | 529/2129 [01:10<07:11,  3.71it/s]
 25%|██▍       | 530/2129 [01:11<07:47,  3.42it/s]
 25%|██▍       | 532/2129 [01:11<05:06,  5.21it/s]
 25%|██▌       | 535/2129 [01:11<04:08,  6.43it/s]
 25%|██▌       | 536/2129 [01:11<04:02,  6.58it/s]
 25%|██▌       | 538/2129 [01:11<03:15,  8.13it/s]
 26%|██▌       | 543/2129 [01:12<02:31, 10.46it/s]
 26%|██▌       | 545/2129 [01:12<02:16, 11.62it/s]
 26%|██▌       | 547/2129 [01:12<02:26, 10.81it/s]
 26%|██▌       | 549/2129 [01:13<03:04,  8.54it/s]
 26%|██▌       | 552/2129 [01:13<02:16, 11.53it/s]
 26%|██▌       | 554/2129 [01:13<02:52,  9.12it/s]
 26%|██▌       | 556/2129 [01:13<02:35, 10.09it/s]
 26%|██▌       | 558/2129 [01:14<03:38,  7.20it/s]
 26%|██▋       | 560/2129 [01:14<03:34,  7.33it/s]
 26%|██▋       | 562/2129 [01:14<02:58,  8.78it/s]
 26%|██▋       | 564/2129 [01:14<03:31,  7.41it/s]
 27%|██▋       | 566/2129 [01:15<02:56,  8.85it/s]
 27%|██▋       | 568/2129 [01:15<03:43,  6.99it/s]
 27%|██▋       | 570/2129 [01:15<03:04,  8.47it/s]
 27%|██▋       | 572/2129 [01:16<04:03,  6.41it/s]
 27%|██▋       | 573/2129 [01:16<04:22,  5.92it/s]
 27%|██▋       | 574/2129 [01:16<05:37,  4.60it/s]
 27%|██▋       | 576/2129 [01:16<04:03,  6.39it/s]
 27%|██▋       | 578/2129 [01:17<05:07,  5.04it/s]
 27%|██▋       | 581/2129 [01:17<05:06,  5.05it/s]
 27%|██▋       | 582/2129 [01:18<05:10,  4.98it/s]
 27%|██▋       | 584/2129 [01:18<05:52,  4.38it/s]
 27%|██▋       | 585/2129 [01:18<05:59,  4.29it/s]
 28%|██▊       | 586/2129 [01:19<06:10,  4.16it/s]
 28%|██▊       | 587/2129 [01:19<07:56,  3.24it/s]
 28%|██▊       | 589/2129 [01:20<06:18,  4.07it/s]
 28%|██▊       | 590/2129 [01:20<06:13,  4.12it/s]
 28%|██▊       | 592/2129 [01:20<06:08,  4.17it/s]
 28%|██▊       | 593/2129 [01:21<06:06,  4.19it/s]
 28%|██▊       | 595/2129 [01:21<05:28,  4.67it/s]
 28%|██▊       | 596/2129 [01:21<05:44,  4.45it/s]
 28%|██▊       | 599/2129 [01:21<04:22,  5.83it/s]
 28%|██▊       | 600/2129 [01:22<04:28,  5.70it/s]
 28%|██▊       | 602/2129 [01:22<04:11,  6.06it/s]
 28%|██▊       | 604/2129 [01:22<04:13,  6.01it/s]
 28%|██▊       | 605/2129 [01:22<04:05,  6.20it/s]
 29%|██▊       | 608/2129 [01:23<02:54,  8.73it/s]
 29%|██▊       | 610/2129 [01:23<03:17,  7.67it/s]
 29%|██▊       | 611/2129 [01:23<03:13,  7.84it/s]
 29%|██▉       | 613/2129 [01:24<04:35,  5.51it/s]
 29%|██▉       | 615/2129 [01:24<03:31,  7.16it/s]
 29%|██▉       | 617/2129 [01:24<02:51,  8.82it/s]
 29%|██▉       | 619/2129 [01:24<02:46,  9.09it/s]
 29%|██▉       | 622/2129 [01:24<02:11, 11.50it/s]
 29%|██▉       | 624/2129 [01:24<02:31,  9.90it/s]
 29%|██▉       | 626/2129 [01:25<03:26,  7.28it/s]
 29%|██▉       | 627/2129 [01:25<04:36,  5.44it/s]
 29%|██▉       | 628/2129 [01:26<06:14,  4.01it/s]
 30%|██▉       | 630/2129 [01:26<04:32,  5.51it/s]
 30%|██▉       | 632/2129 [01:26<03:49,  6.53it/s]
 30%|██▉       | 634/2129 [01:27<04:29,  5.55it/s]
 30%|██▉       | 636/2129 [01:27<04:04,  6.10it/s]
 30%|██▉       | 638/2129 [01:27<04:50,  5.13it/s]
 30%|███       | 640/2129 [01:28<04:16,  5.80it/s]
 30%|███       | 641/2129 [01:28<04:16,  5.79it/s]
 30%|███       | 643/2129 [01:28<03:51,  6.42it/s]
 30%|███       | 644/2129 [01:29<05:02,  4.92it/s]
 30%|███       | 645/2129 [01:29<05:16,  4.69it/s]
 30%|███       | 647/2129 [01:29<04:44,  5.22it/s]
 30%|███       | 649/2129 [01:29<04:20,  5.69it/s]
 31%|███       | 651/2129 [01:30<04:19,  5.70it/s]
 31%|███       | 653/2129 [01:30<04:18,  5.71it/s]
 31%|███       | 656/2129 [01:30<03:00,  8.14it/s]
 31%|███       | 658/2129 [01:31<04:05,  5.99it/s]
 31%|███       | 659/2129 [01:31<05:07,  4.77it/s]
 31%|███       | 660/2129 [01:31<05:05,  4.81it/s]
 31%|███       | 661/2129 [01:32<05:01,  4.87it/s]
 31%|███       | 662/2129 [01:32<05:22,  4.55it/s]
 31%|███       | 663/2129 [01:32<05:18,  4.60it/s]
 31%|███       | 665/2129 [01:32<03:40,  6.62it/s]
 31%|███▏      | 667/2129 [01:33<04:48,  5.07it/s]
 31%|███▏      | 669/2129 [01:33<03:39,  6.66it/s]
 32%|███▏      | 672/2129 [01:33<03:05,  7.84it/s]
 32%|███▏      | 675/2129 [01:33<02:14, 10.78it/s]
 32%|███▏      | 677/2129 [01:33<02:20, 10.31it/s]
 32%|███▏      | 679/2129 [01:34<02:30,  9.62it/s]
 32%|███▏      | 681/2129 [01:34<02:34,  9.37it/s]
 32%|███▏      | 683/2129 [01:34<02:39,  9.08it/s]
 32%|███▏      | 685/2129 [01:35<03:30,  6.86it/s]
 32%|███▏      | 686/2129 [01:35<04:38,  5.18it/s]
 32%|███▏      | 687/2129 [01:35<04:37,  5.19it/s]
 32%|███▏      | 688/2129 [01:35<04:43,  5.08it/s]
 32%|███▏      | 689/2129 [01:36<06:40,  3.59it/s]
 32%|███▏      | 691/2129 [01:36<06:13,  3.85it/s]
 33%|███▎      | 694/2129 [01:37<05:29,  4.36it/s]
 33%|███▎      | 696/2129 [01:38<05:47,  4.12it/s]
 33%|███▎      | 699/2129 [01:38<03:53,  6.12it/s]
 33%|███▎      | 701/2129 [01:38<04:14,  5.61it/s]
 33%|███▎      | 703/2129 [01:39<05:00,  4.75it/s]
 33%|███▎      | 705/2129 [01:39<05:43,  4.14it/s]
 33%|███▎      | 707/2129 [01:40<04:59,  4.75it/s]
 33%|███▎      | 708/2129 [01:40<06:19,  3.74it/s]
 33%|███▎      | 711/2129 [01:40<04:02,  5.84it/s]
 33%|███▎      | 713/2129 [01:41<06:12,  3.80it/s]
 34%|███▎      | 714/2129 [01:42<06:42,  3.52it/s]
 34%|███▎      | 717/2129 [01:42<04:18,  5.46it/s]
 34%|███▍      | 721/2129 [01:42<03:54,  6.01it/s]
 34%|███▍      | 723/2129 [01:43<04:28,  5.24it/s]
 34%|███▍      | 724/2129 [01:43<05:35,  4.19it/s]
 34%|███▍      | 725/2129 [01:44<05:29,  4.27it/s]
 34%|███▍      | 726/2129 [01:44<05:15,  4.45it/s]
 34%|███▍      | 727/2129 [01:44<06:42,  3.49it/s]
 34%|███▍      | 728/2129 [01:45<07:57,  2.94it/s]
 34%|███▍      | 729/2129 [01:45<08:39,  2.69it/s]
 34%|███▍      | 730/2129 [01:46<08:53,  2.62it/s]
 34%|███▍      | 733/2129 [01:46<06:32,  3.56it/s]
 34%|███▍      | 734/2129 [01:47<06:12,  3.74it/s]
 35%|███▍      | 735/2129 [01:47<06:51,  3.39it/s]
 35%|███▍      | 738/2129 [01:47<03:53,  5.95it/s]
 35%|███▍      | 740/2129 [01:48<04:43,  4.90it/s]
 35%|███▍      | 743/2129 [01:48<03:08,  7.35it/s]
 35%|███▌      | 751/2129 [01:48<02:16, 10.10it/s]
 35%|███▌      | 753/2129 [01:49<02:58,  7.69it/s]
 35%|███▌      | 755/2129 [01:50<04:39,  4.91it/s]
 36%|███▌      | 758/2129 [01:50<03:28,  6.58it/s]
 36%|███▌      | 760/2129 [01:50<03:46,  6.05it/s]
 36%|███▌      | 762/2129 [01:51<05:07,  4.44it/s]
 36%|███▌      | 763/2129 [01:52<05:45,  3.96it/s]
 36%|███▌      | 765/2129 [01:52<05:41,  4.00it/s]
 36%|███▌      | 766/2129 [01:53<06:39,  3.41it/s]
 36%|███▌      | 767/2129 [01:53<07:39,  2.96it/s]
 36%|███▌      | 769/2129 [01:54<07:16,  3.12it/s]
 36%|███▌      | 771/2129 [01:54<05:12,  4.35it/s]
 36%|███▋      | 772/2129 [01:54<05:29,  4.12it/s]
 36%|███▋      | 773/2129 [01:54<05:18,  4.26it/s]
 36%|███▋      | 774/2129 [01:55<06:26,  3.51it/s]
 36%|███▋      | 775/2129 [01:55<07:10,  3.15it/s]
 36%|███▋      | 776/2129 [01:55<07:09,  3.15it/s]
 36%|███▋      | 777/2129 [01:56<07:07,  3.16it/s]
 37%|███▋      | 778/2129 [01:56<07:24,  3.04it/s]
 37%|███▋      | 780/2129 [01:56<05:45,  3.90it/s]
 37%|███▋      | 781/2129 [01:57<05:26,  4.13it/s]
 37%|███▋      | 782/2129 [01:57<05:04,  4.43it/s]
 37%|███▋      | 784/2129 [01:57<03:33,  6.29it/s]
 37%|███▋      | 785/2129 [01:57<04:09,  5.39it/s]
 37%|███▋      | 787/2129 [01:57<03:16,  6.82it/s]
 37%|███▋      | 790/2129 [01:58<02:08, 10.44it/s]
 37%|███▋      | 792/2129 [01:58<01:58, 11.30it/s]
 37%|███▋      | 794/2129 [01:58<02:03, 10.84it/s]
 37%|███▋      | 796/2129 [01:58<03:24,  6.53it/s]
 37%|███▋      | 798/2129 [01:59<03:25,  6.48it/s]
 38%|███▊      | 800/2129 [01:59<03:32,  6.27it/s]
 38%|███▊      | 802/2129 [01:59<03:21,  6.59it/s]
 38%|███▊      | 803/2129 [02:00<03:21,  6.58it/s]
 38%|███▊      | 805/2129 [02:00<03:31,  6.27it/s]
 38%|███▊      | 806/2129 [02:00<03:42,  5.94it/s]
 38%|███▊      | 809/2129 [02:00<02:55,  7.53it/s]
 38%|███▊      | 810/2129 [02:01<02:51,  7.69it/s]
 38%|███▊      | 812/2129 [02:01<02:31,  8.68it/s]
 38%|███▊      | 814/2129 [02:01<03:10,  6.90it/s]
 38%|███▊      | 815/2129 [02:01<03:56,  5.56it/s]
 38%|███▊      | 817/2129 [02:02<03:00,  7.28it/s]
 38%|███▊      | 818/2129 [02:02<04:12,  5.20it/s]
 39%|███▊      | 820/2129 [02:02<04:14,  5.14it/s]
 39%|███▊      | 822/2129 [02:02<03:11,  6.84it/s]
 39%|███▊      | 824/2129 [02:03<02:33,  8.48it/s]
 39%|███▉      | 827/2129 [02:03<02:29,  8.70it/s]
 39%|███▉      | 830/2129 [02:03<01:51, 11.66it/s]
 39%|███▉      | 832/2129 [02:04<03:12,  6.73it/s]
 39%|███▉      | 834/2129 [02:04<02:40,  8.07it/s]
 39%|███▉      | 836/2129 [02:04<03:14,  6.66it/s]
 39%|███▉      | 838/2129 [02:04<03:08,  6.84it/s]
 39%|███▉      | 839/2129 [02:05<03:16,  6.58it/s]
 40%|███▉      | 841/2129 [02:05<03:07,  6.86it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 343.12it/s]
 50%|█████     | 151/300 [09:26<4:41:53, 113.52s/it]

[[np.int64(0), False, 7], [np.int64(1), False, 9], [np.int64(2), False, 6], [np.int64(3), False, 8], [np.int64(4), False, 5], [np.int64(5), False, 9], [np.int64(6), False, 5], [np.int64(10), False, 8], [np.int64(11), False, 1], [np.int64(12), False, 13]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4468, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.1815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5197, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [09:26<3:16:07, 79.51s/it]

tensor(12.1802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6161, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [09:26<2:16:26, 55.69s/it]

tensor(12.1867, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7534, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [09:26<1:06:05, 27.35s/it]

tensor(12.1976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8808, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [09:26<46:02, 19.18s/it]

tensor(12.2080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9869, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [09:27<32:05, 13.46s/it]

tensor(12.2131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0667, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [09:27<22:23,  9.46s/it]

tensor(12.2122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1561, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [09:27<15:38,  6.66s/it]

tensor(12.2011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1906, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [09:27<10:57,  4.70s/it]

tensor(12.1963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2077, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [09:27<05:26,  2.36s/it]

tensor(12.1919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2275, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [09:27<03:51,  1.69s/it]

tensor(12.1855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2411, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2599, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [09:27<02:46,  1.22s/it]

tensor(12.1605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2725, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [09:27<02:00,  1.12it/s]

tensor(12.1445, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2772, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [09:28<01:28,  1.51it/s]

tensor(12.1296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2809, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [09:28<01:06,  2.00it/s]

tensor(12.1170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2727, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [09:28<00:40,  3.27it/s]

tensor(12.1071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2676, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2617, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [09:28<00:32,  3.98it/s]

tensor(12.0941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2635, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [09:28<00:27,  4.70it/s]

tensor(12.0890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2709, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [09:28<00:23,  5.38it/s]

tensor(12.0837, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2893, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [09:29<00:19,  6.55it/s]

tensor(12.0773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3058, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [09:29<00:17,  6.97it/s]

tensor(12.0701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3334, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3355, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [09:29<00:17,  7.27it/s]

tensor(12.0563, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3352, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [09:29<00:15,  7.73it/s]

tensor(12.0507, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3206, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [09:29<00:15,  7.87it/s]

tensor(12.0459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1808, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0411, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2050, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [09:29<00:15,  7.95it/s]

tensor(12.0360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2357, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [09:30<00:14,  8.09it/s]

tensor(12.0309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1654, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [09:30<00:14,  8.10it/s]

tensor(12.0221, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1913, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [09:30<00:14,  8.17it/s]

tensor(12.0180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2246, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3499, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [09:30<00:13,  8.16it/s]

tensor(12.0099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0332, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3690, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [09:30<00:13,  8.18it/s]

tensor(12.0059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3921, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [09:30<00:13,  8.19it/s]

tensor(12.0015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4149, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [09:31<00:13,  8.20it/s]

tensor(11.9971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0391, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4399, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4610, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [09:31<00:13,  8.17it/s]

tensor(11.9908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4709, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [09:31<00:13,  8.18it/s]

tensor(11.9887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0417, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4654, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [09:31<00:12,  8.20it/s]

tensor(11.9868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0418, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4734, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [09:31<00:12,  8.21it/s]

tensor(11.9847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4837, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [09:31<00:12,  8.21it/s]

tensor(11.9823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4881, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [09:31<00:12,  8.21it/s]

tensor(11.9793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0369, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4980, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [09:32<00:12,  8.19it/s]

tensor(11.9728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5019, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [09:32<00:12,  8.20it/s]

tensor(11.9701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5075, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 93, 119, 262,  48, 111, 203,  90,  58, 115, 208, 225, 212, 127, 258])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 6/2129 [00:00<00:38, 54.97it/s]
  1%|          | 14/2129 [00:00<00:32, 65.05it/s]
  1%|          | 21/2129 [00:00<00:46, 44.87it/s]
  1%|▏         | 28/2129 [00:00<00:43, 48.66it/s]
  2%|▏         | 34/2129 [00:00<00:43, 48.28it/s]
  2%|▏         | 40/2129 [00:00<00:45, 46.12it/s]
  2%|▏         | 45/2129 [00:01<01:04, 32.11it/s]
  2%|▏         | 50/2129 [00:01<00:59, 34.71it/s]
  3%|▎         | 54/2129 [00:01<00:58, 35.57it/s]
  3%|▎         | 58/2129 [00:01<00:56, 36.46it/s]
  3%|▎         | 64/2129 [00:01<00:50, 41.02it/s]
  3%|▎         | 69/2129 [00:01<01:24, 24.24it/s]
  3%|▎         | 73/2129 [00:02<01:39, 20.63it/s]
  4%|▎         | 76/2129 [00:02<01:37, 21.13it/s]
  4%|▍         | 82/2129 [00:02<01:13, 27.72it/s]
  4%|▍         | 87/2129 [00:02<01:03, 32.07it/s]
  4%|▍         | 94/2129 [00:02<00:52, 39.07it/s]
  5%|▍         | 99/2129 [00:02<00:57, 35.19it/s]
  5%|▍         | 104/2129 [00:02<00:53, 37.94it/s]
  5%|▌         | 109/2129 [00:03<00:52, 38.35it/s]
  5%|▌         | 115/2129 [00:03<00:46, 43.25it/s]
  6%|▌         | 123/2129 [00:03<00:40, 48.93it/s]
  6%|▌         | 131/2129 [00:03<00:36, 54.64it/s]
  6%|▋         | 137/2129 [00:03<00:36, 55.21it/s]
  7%|▋         | 145/2129 [00:03<00:33, 60.00it/s]
  7%|▋         | 152/2129 [00:03<00:38, 51.24it/s]
  7%|▋         | 158/2129 [00:04<00:54, 36.17it/s]
  8%|▊         | 163/2129 [00:04<01:08, 28.84it/s]
  8%|▊         | 170/2129 [00:04<00:55, 35.44it/s]
  8%|▊         | 175/2129 [00:04<01:14, 26.07it/s]
  8%|▊         | 179/2129 [00:05<01:26, 22.62it/s]
  9%|▊         | 183/2129 [00:05<01:39, 19.62it/s]
  9%|▊         | 186/2129 [00:05<02:05, 15.50it/s]
  9%|▉         | 189/2129 [00:05<01:59, 16.28it/s]
  9%|▉         | 191/2129 [00:06<02:14, 14.41it/s]
  9%|▉         | 193/2129 [00:06<02:12, 14.60it/s]
  9%|▉         | 195/2129 [00:06<02:06, 15.26it/s]
  9%|▉         | 197/2129 [00:06<02:03, 15.68it/s]
  9%|▉         | 200/2129 [00:06<01:57, 16.46it/s]
  9%|▉         | 202/2129 [00:06<02:48, 11.45it/s]
 10%|▉         | 205/2129 [00:07<02:15, 14.22it/s]
 10%|▉         | 212/2129 [00:07<01:19, 24.09it/s]
 10%|█         | 217/2129 [00:07<01:04, 29.46it/s]
 10%|█         | 223/2129 [00:07<01:10, 27.14it/s]
 11%|█         | 227/2129 [00:07<01:35, 19.82it/s]
 11%|█         | 230/2129 [00:08<01:28, 21.35it/s]
 11%|█         | 233/2129 [00:08<01:40, 18.79it/s]
 11%|█         | 236/2129 [00:08<01:54, 16.54it/s]
 11%|█         | 239/2129 [00:08<02:08, 14.70it/s]
 11%|█▏        | 242/2129 [00:08<01:56, 16.26it/s]
 12%|█▏        | 246/2129 [00:09<01:53, 16.59it/s]
 12%|█▏        | 249/2129 [00:09<01:44, 17.93it/s]
 12%|█▏        | 251/2129 [00:09<02:12, 14.22it/s]
 12%|█▏        | 253/2129 [00:09<02:40, 11.68it/s]
 12%|█▏        | 257/2129 [00:09<01:57, 15.95it/s]
 12%|█▏        | 260/2129 [00:10<02:33, 12.21it/s]
 12%|█▏        | 262/2129 [00:10<02:48, 11.08it/s]
 12%|█▏        | 265/2129 [00:10<02:16, 13.63it/s]
 13%|█▎        | 271/2129 [00:10<01:32, 20.02it/s]
 13%|█▎        | 275/2129 [00:11<01:40, 18.50it/s]
 13%|█▎        | 278/2129 [00:11<01:31, 20.20it/s]
 13%|█▎        | 284/2129 [00:11<01:06, 27.84it/s]
 14%|█▎        | 288/2129 [00:11<01:38, 18.60it/s]
 14%|█▎        | 292/2129 [00:11<01:40, 18.26it/s]
 14%|█▍        | 295/2129 [00:11<01:35, 19.30it/s]
 14%|█▍        | 298/2129 [00:12<01:47, 17.01it/s]
 14%|█▍        | 301/2129 [00:12<01:42, 17.82it/s]
 14%|█▍        | 305/2129 [00:12<01:42, 17.78it/s]
 14%|█▍        | 307/2129 [00:12<01:44, 17.45it/s]
 15%|█▍        | 312/2129 [00:12<01:40, 18.04it/s]
 15%|█▍        | 314/2129 [00:13<02:32, 11.94it/s]
 15%|█▍        | 317/2129 [00:13<02:05, 14.42it/s]
 15%|█▌        | 323/2129 [00:13<01:24, 21.47it/s]
 15%|█▌        | 326/2129 [00:13<01:49, 16.49it/s]
 15%|█▌        | 329/2129 [00:14<02:00, 14.97it/s]
 16%|█▌        | 332/2129 [00:14<01:45, 17.08it/s]
 16%|█▌        | 335/2129 [00:14<01:57, 15.26it/s]
 16%|█▌        | 337/2129 [00:14<02:19, 12.88it/s]
 16%|█▌        | 341/2129 [00:14<01:47, 16.63it/s]
 16%|█▌        | 344/2129 [00:15<02:28, 12.01it/s]
 16%|█▋        | 346/2129 [00:15<02:46, 10.68it/s]
 16%|█▋        | 349/2129 [00:15<02:53, 10.26it/s]
 16%|█▋        | 351/2129 [00:16<02:51, 10.36it/s]
 17%|█▋        | 355/2129 [00:16<02:33, 11.58it/s]
 17%|█▋        | 357/2129 [00:16<02:23, 12.32it/s]
 17%|█▋        | 359/2129 [00:16<02:10, 13.54it/s]
 17%|█▋        | 361/2129 [00:16<02:21, 12.48it/s]
 17%|█▋        | 363/2129 [00:16<02:23, 12.34it/s]
 17%|█▋        | 365/2129 [00:17<02:13, 13.22it/s]
 17%|█▋        | 369/2129 [00:17<01:35, 18.41it/s]
 18%|█▊        | 373/2129 [00:17<01:25, 20.48it/s]
 18%|█▊        | 376/2129 [00:17<01:23, 20.91it/s]
 18%|█▊        | 380/2129 [00:17<01:29, 19.52it/s]
 18%|█▊        | 383/2129 [00:17<01:32, 18.80it/s]
 18%|█▊        | 386/2129 [00:18<01:49, 15.98it/s]
 18%|█▊        | 388/2129 [00:18<01:47, 16.21it/s]
 19%|█▊        | 394/2129 [00:18<01:12, 24.01it/s]
 19%|█▊        | 399/2129 [00:18<00:59, 29.12it/s]
 19%|█▉        | 403/2129 [00:18<01:24, 20.40it/s]
 19%|█▉        | 406/2129 [00:19<02:20, 12.31it/s]
 19%|█▉        | 409/2129 [00:19<02:03, 13.94it/s]
 20%|█▉        | 416/2129 [00:19<01:17, 21.98it/s]
 20%|█▉        | 421/2129 [00:19<01:04, 26.42it/s]
 20%|██        | 427/2129 [00:19<00:51, 32.78it/s]
 20%|██        | 432/2129 [00:20<01:19, 21.42it/s]
 20%|██        | 436/2129 [00:20<01:51, 15.22it/s]
 21%|██        | 439/2129 [00:21<02:09, 13.08it/s]
 21%|██        | 442/2129 [00:21<01:53, 14.90it/s]
 21%|██        | 448/2129 [00:21<01:19, 21.09it/s]
 21%|██        | 452/2129 [00:21<01:26, 19.37it/s]
 21%|██▏       | 455/2129 [00:21<01:21, 20.48it/s]
 22%|██▏       | 458/2129 [00:21<01:40, 16.56it/s]
 22%|██▏       | 461/2129 [00:22<02:20, 11.86it/s]
 22%|██▏       | 464/2129 [00:22<02:01, 13.67it/s]
 22%|██▏       | 466/2129 [00:22<02:13, 12.48it/s]
 22%|██▏       | 468/2129 [00:23<02:30, 11.00it/s]
 22%|██▏       | 471/2129 [00:23<02:34, 10.75it/s]
 22%|██▏       | 474/2129 [00:23<02:02, 13.48it/s]
 22%|██▏       | 477/2129 [00:23<02:04, 13.24it/s]
 22%|██▏       | 479/2129 [00:23<02:25, 11.38it/s]
 23%|██▎       | 481/2129 [00:24<02:16, 12.08it/s]
 23%|██▎       | 484/2129 [00:24<02:02, 13.41it/s]
 23%|██▎       | 487/2129 [00:24<01:44, 15.75it/s]
 23%|██▎       | 489/2129 [00:24<02:05, 13.04it/s]
 23%|██▎       | 491/2129 [00:24<02:26, 11.20it/s]
 23%|██▎       | 493/2129 [00:24<02:09, 12.67it/s]
 23%|██▎       | 498/2129 [00:25<01:29, 18.17it/s]
 24%|██▎       | 501/2129 [00:25<01:42, 15.87it/s]
 24%|██▎       | 503/2129 [00:25<02:15, 12.04it/s]
 24%|██▎       | 505/2129 [00:25<02:03, 13.15it/s]
 24%|██▍       | 508/2129 [00:25<01:51, 14.58it/s]
 24%|██▍       | 510/2129 [00:26<01:48, 14.98it/s]
 24%|██▍       | 513/2129 [00:26<01:31, 17.59it/s]
 24%|██▍       | 515/2129 [00:26<01:41, 15.90it/s]
 24%|██▍       | 517/2129 [00:26<01:55, 13.96it/s]
 24%|██▍       | 520/2129 [00:26<02:03, 13.07it/s]
 25%|██▍       | 522/2129 [00:27<02:47,  9.61it/s]
 25%|██▍       | 525/2129 [00:27<02:07, 12.60it/s]
 25%|██▍       | 527/2129 [00:27<02:19, 11.45it/s]
 25%|██▍       | 529/2129 [00:27<02:36, 10.25it/s]
 25%|██▍       | 531/2129 [00:27<02:48,  9.48it/s]
 25%|██▌       | 534/2129 [00:28<02:06, 12.65it/s]
 25%|██▌       | 536/2129 [00:28<03:02,  8.74it/s]
 25%|██▌       | 538/2129 [00:28<02:34, 10.29it/s]
 26%|██▌       | 543/2129 [00:28<01:57, 13.52it/s]
 26%|██▌       | 545/2129 [00:29<02:07, 12.42it/s]
 26%|██▌       | 547/2129 [00:29<01:56, 13.58it/s]
 26%|██▌       | 551/2129 [00:29<01:25, 18.47it/s]
 26%|██▌       | 556/2129 [00:29<01:08, 23.08it/s]
 26%|██▋       | 559/2129 [00:30<02:13, 11.75it/s]
 26%|██▋       | 562/2129 [00:30<01:52, 13.88it/s]
 27%|██▋       | 565/2129 [00:30<01:52, 13.94it/s]
 27%|██▋       | 567/2129 [00:30<02:06, 12.32it/s]
 27%|██▋       | 570/2129 [00:30<01:44, 14.99it/s]
 27%|██▋       | 573/2129 [00:30<01:58, 13.12it/s]
 27%|██▋       | 575/2129 [00:31<02:03, 12.57it/s]
 27%|██▋       | 577/2129 [00:31<02:21, 10.93it/s]
 27%|██▋       | 579/2129 [00:31<02:13, 11.57it/s]
 27%|██▋       | 581/2129 [00:31<02:00, 12.80it/s]
 27%|██▋       | 584/2129 [00:31<02:09, 11.95it/s]
 28%|██▊       | 587/2129 [00:32<01:48, 14.19it/s]
 28%|██▊       | 589/2129 [00:32<02:03, 12.44it/s]
 28%|██▊       | 592/2129 [00:32<01:40, 15.24it/s]
 28%|██▊       | 595/2129 [00:32<01:26, 17.75it/s]
 28%|██▊       | 599/2129 [00:32<01:18, 19.49it/s]
 28%|██▊       | 602/2129 [00:32<01:30, 16.95it/s]
 29%|██▊       | 607/2129 [00:33<01:06, 22.86it/s]
 29%|██▊       | 610/2129 [00:33<01:19, 19.09it/s]
 29%|██▉       | 613/2129 [00:33<01:15, 19.96it/s]
 29%|██▉       | 616/2129 [00:33<01:28, 17.11it/s]
 29%|██▉       | 619/2129 [00:33<01:17, 19.39it/s]
 29%|██▉       | 625/2129 [00:33<00:55, 27.28it/s]
 30%|██▉       | 629/2129 [00:34<01:30, 16.66it/s]
 30%|██▉       | 632/2129 [00:34<01:20, 18.59it/s]
 30%|██▉       | 636/2129 [00:34<01:22, 18.06it/s]
 30%|███       | 639/2129 [00:34<01:16, 19.50it/s]
 30%|███       | 644/2129 [00:35<01:15, 19.68it/s]
 30%|███       | 647/2129 [00:35<01:12, 20.53it/s]
 31%|███       | 650/2129 [00:35<01:27, 16.89it/s]
 31%|███       | 653/2129 [00:35<01:38, 15.04it/s]
 31%|███       | 656/2129 [00:35<01:25, 17.30it/s]
 31%|███       | 659/2129 [00:36<01:39, 14.83it/s]
 31%|███       | 662/2129 [00:36<01:49, 13.40it/s]
 31%|███       | 664/2129 [00:36<01:42, 14.27it/s]
 32%|███▏      | 671/2129 [00:36<01:01, 23.83it/s]
 32%|███▏      | 678/2129 [00:36<00:45, 31.68it/s]
 32%|███▏      | 682/2129 [00:36<01:03, 22.82it/s]
 32%|███▏      | 687/2129 [00:37<01:06, 21.83it/s]
 32%|███▏      | 690/2129 [00:37<01:28, 16.23it/s]
 33%|███▎      | 693/2129 [00:37<01:25, 16.86it/s]
 33%|███▎      | 696/2129 [00:38<01:58, 12.07it/s]
 33%|███▎      | 698/2129 [00:38<01:53, 12.59it/s]
 33%|███▎      | 703/2129 [00:38<01:36, 14.78it/s]
 33%|███▎      | 705/2129 [00:38<01:50, 12.91it/s]
 33%|███▎      | 707/2129 [00:38<01:46, 13.35it/s]
 33%|███▎      | 709/2129 [00:39<02:07, 11.18it/s]
 33%|███▎      | 712/2129 [00:39<01:55, 12.29it/s]
 34%|███▎      | 714/2129 [00:39<02:07, 11.08it/s]
 34%|███▎      | 716/2129 [00:39<01:56, 12.08it/s]
 34%|███▍      | 721/2129 [00:40<01:29, 15.79it/s]
 34%|███▍      | 723/2129 [00:40<01:28, 15.97it/s]
 34%|███▍      | 725/2129 [00:40<02:10, 10.75it/s]
 34%|███▍      | 727/2129 [00:40<02:20, 10.01it/s]
 34%|███▍      | 730/2129 [00:40<01:50, 12.62it/s]
 34%|███▍      | 733/2129 [00:41<01:46, 13.11it/s]
 35%|███▍      | 736/2129 [00:41<01:31, 15.26it/s]
 35%|███▍      | 739/2129 [00:41<01:32, 14.95it/s]
 35%|███▍      | 742/2129 [00:41<01:20, 17.15it/s]
 35%|███▌      | 749/2129 [00:41<00:49, 27.75it/s]
 35%|███▌      | 753/2129 [00:42<01:19, 17.22it/s]
 36%|███▌      | 756/2129 [00:42<02:03, 11.09it/s]
 36%|███▌      | 759/2129 [00:42<01:53, 12.12it/s]
 36%|███▌      | 761/2129 [00:42<01:47, 12.76it/s]
 36%|███▌      | 763/2129 [00:43<02:23,  9.53it/s]
 36%|███▌      | 766/2129 [00:43<02:04, 10.93it/s]
 36%|███▌      | 768/2129 [00:43<02:28,  9.17it/s]
 36%|███▌      | 770/2129 [00:44<02:36,  8.67it/s]
 36%|███▋      | 772/2129 [00:44<02:13, 10.13it/s]
 36%|███▋      | 774/2129 [00:44<02:21,  9.57it/s]
 36%|███▋      | 776/2129 [00:44<03:03,  7.38it/s]
 37%|███▋      | 778/2129 [00:45<02:32,  8.87it/s]
 37%|███▋      | 780/2129 [00:45<02:32,  8.87it/s]
 37%|███▋      | 782/2129 [00:45<02:34,  8.71it/s]
 37%|███▋      | 784/2129 [00:45<02:10, 10.34it/s]
 37%|███▋      | 786/2129 [00:45<02:05, 10.74it/s]
 37%|███▋      | 791/2129 [00:45<01:15, 17.64it/s]
 37%|███▋      | 795/2129 [00:46<01:23, 16.04it/s]
 37%|███▋      | 797/2129 [00:46<01:55, 11.57it/s]
 38%|███▊      | 799/2129 [00:46<02:12, 10.07it/s]
 38%|███▊      | 803/2129 [00:47<01:56, 11.35it/s]
 38%|███▊      | 806/2129 [00:47<01:39, 13.36it/s]
 38%|███▊      | 809/2129 [00:47<01:35, 13.80it/s]
 38%|███▊      | 812/2129 [00:47<01:22, 15.90it/s]
 38%|███▊      | 814/2129 [00:47<01:33, 14.13it/s]
 38%|███▊      | 817/2129 [00:47<01:21, 16.14it/s]
 38%|███▊      | 819/2129 [00:48<01:43, 12.68it/s]
 39%|███▊      | 821/2129 [00:48<01:49, 11.91it/s]
 39%|███▊      | 823/2129 [00:48<01:42, 12.74it/s]
 39%|███▉      | 825/2129 [00:48<01:34, 13.87it/s]
 39%|███▉      | 832/2129 [00:48<00:50, 25.49it/s]
 39%|███▉      | 838/2129 [00:48<00:39, 33.09it/s]
 40%|███▉      | 842/2129 [00:49<00:48, 26.57it/s]
 40%|███▉      | 846/2129 [00:49<01:21, 15.67it/s]
 40%|███▉      | 849/2129 [00:49<01:41, 12.59it/s]
 40%|███▉      | 851/2129 [00:50<01:39, 12.82it/s]
 40%|████      | 853/2129 [00:50<01:51, 11.44it/s]
 40%|████      | 855/2129 [00:50<01:44, 12.18it/s]
 40%|████      | 859/2129 [00:50<01:16, 16.58it/s]
 40%|████      | 862/2129 [00:50<01:40, 12.65it/s]
 41%|████      | 865/2129 [00:51<01:22, 15.24it/s]
 41%|████      | 868/2129 [00:51<01:33, 13.50it/s]
 41%|████      | 873/2129 [00:51<01:24, 14.80it/s]
 41%|████      | 877/2129 [00:51<01:09, 17.98it/s]
 41%|████▏     | 880/2129 [00:51<01:17, 16.15it/s]
 42%|████▏     | 884/2129 [00:52<01:03, 19.73it/s]
 42%|████▏     | 887/2129 [00:52<01:30, 13.80it/s]
 42%|████▏     | 890/2129 [00:52<01:20, 15.40it/s]
 42%|████▏     | 893/2129 [00:52<01:29, 13.86it/s]
 42%|████▏     | 895/2129 [00:53<01:41, 12.20it/s]
 42%|████▏     | 897/2129 [00:53<01:34, 13.11it/s]
 42%|████▏     | 899/2129 [00:53<01:44, 11.76it/s]
 42%|████▏     | 902/2129 [00:53<01:48, 11.30it/s]
 42%|████▏     | 904/2129 [00:53<01:57, 10.46it/s]
 43%|████▎     | 906/2129 [00:54<02:08,  9.49it/s]
 43%|████▎     | 908/2129 [00:54<02:09,  9.42it/s]
 43%|████▎     | 909/2129 [00:54<02:08,  9.49it/s]
 43%|████▎     | 911/2129 [00:54<02:17,  8.86it/s]
 43%|████▎     | 912/2129 [00:54<02:22,  8.55it/s]
 43%|████▎     | 914/2129 [00:55<01:53, 10.66it/s]
 43%|████▎     | 916/2129 [00:55<01:52, 10.79it/s]
 43%|████▎     | 918/2129 [00:55<01:42, 11.84it/s]
 43%|████▎     | 920/2129 [00:55<01:43, 11.68it/s]
 43%|████▎     | 923/2129 [00:55<01:19, 15.11it/s]
 43%|████▎     | 926/2129 [00:55<01:24, 14.23it/s]
 44%|████▎     | 928/2129 [00:56<01:54, 10.51it/s]
 44%|████▎     | 931/2129 [00:56<01:48, 11.07it/s]
 44%|████▍     | 934/2129 [00:56<01:27, 13.69it/s]
 44%|████▍     | 936/2129 [00:56<01:36, 12.33it/s]
 44%|████▍     | 938/2129 [00:57<01:52, 10.56it/s]
 44%|████▍     | 940/2129 [00:57<02:05,  9.50it/s]
 44%|████▍     | 943/2129 [00:57<01:36, 12.29it/s]
 44%|████▍     | 945/2129 [00:57<01:52, 10.57it/s]
 44%|████▍     | 947/2129 [00:57<01:59,  9.91it/s]
 45%|████▍     | 950/2129 [00:58<01:41, 11.56it/s]
 45%|████▍     | 952/2129 [00:58<01:30, 12.96it/s]
 45%|████▍     | 954/2129 [00:58<01:26, 13.52it/s]
 45%|████▍     | 956/2129 [00:58<01:48, 10.82it/s]
 45%|████▍     | 958/2129 [00:58<01:59,  9.76it/s]
 45%|████▌     | 960/2129 [00:59<01:53, 10.28it/s]
 45%|████▌     | 963/2129 [00:59<01:50, 10.52it/s]
 45%|████▌     | 966/2129 [00:59<01:27, 13.31it/s]
 46%|████▌     | 969/2129 [00:59<01:39, 11.63it/s]
 46%|████▌     | 971/2129 [01:00<01:59,  9.68it/s]
 46%|████▌     | 973/2129 [01:00<01:59,  9.69it/s]
 46%|████▌     | 975/2129 [01:00<01:44, 11.06it/s]
 46%|████▌     | 977/2129 [01:00<01:32, 12.43it/s]
 46%|████▌     | 981/2129 [01:00<01:16, 15.05it/s]
 46%|████▌     | 984/2129 [01:00<01:10, 16.27it/s]
 46%|████▋     | 986/2129 [01:00<01:08, 16.78it/s]
 46%|████▋     | 988/2129 [01:01<01:05, 17.37it/s]
 47%|████▋     | 991/2129 [01:01<00:55, 20.33it/s]
 47%|████▋     | 994/2129 [01:01<00:51, 22.09it/s]
 47%|████▋     | 997/2129 [01:01<00:50, 22.38it/s]
 47%|████▋     | 1001/2129 [01:01<01:05, 17.13it/s]
 47%|████▋     | 1003/2129 [01:01<01:19, 14.21it/s]
 47%|████▋     | 1005/2129 [01:02<01:17, 14.45it/s]
 47%|████▋     | 1010/2129 [01:02<00:54, 20.51it/s]
 48%|████▊     | 1013/2129 [01:02<01:23, 13.33it/s]
 48%|████▊     | 1015/2129 [01:02<01:34, 11.79it/s]
 48%|████▊     | 1017/2129 [01:03<01:30, 12.27it/s]
 48%|████▊     | 1019/2129 [01:03<01:35, 11.68it/s]
 48%|████▊     | 1021/2129 [01:03<01:24, 13.05it/s]
 48%|████▊     | 1023/2129 [01:03<01:32, 11.91it/s]
 48%|████▊     | 1025/2129 [01:03<01:50, 10.00it/s]
 48%|████▊     | 1027/2129 [01:03<01:37, 11.30it/s]
 48%|████▊     | 1029/2129 [01:04<01:44, 10.52it/s]
 48%|████▊     | 1031/2129 [01:04<01:47, 10.25it/s]
 49%|████▊     | 1033/2129 [01:04<01:51,  9.80it/s]
 49%|████▊     | 1037/2129 [01:04<01:13, 14.81it/s]
 49%|████▉     | 1043/2129 [01:04<00:46, 23.60it/s]
 49%|████▉     | 1047/2129 [01:05<01:00, 17.99it/s]
 49%|████▉     | 1050/2129 [01:05<01:13, 14.73it/s]
 50%|████▉     | 1055/2129 [01:05<01:04, 16.69it/s]
 50%|████▉     | 1058/2129 [01:06<01:40, 10.68it/s]
 50%|████▉     | 1060/2129 [01:06<01:52,  9.52it/s]
 50%|████▉     | 1062/2129 [01:06<01:42, 10.46it/s]
 50%|████▉     | 1064/2129 [01:06<01:39, 10.74it/s]
 50%|█████     | 1067/2129 [01:07<01:21, 13.10it/s]
 50%|█████     | 1069/2129 [01:07<01:36, 10.93it/s]
 50%|█████     | 1071/2129 [01:07<02:05,  8.41it/s]
 50%|█████     | 1074/2129 [01:07<01:34, 11.15it/s]
 51%|█████     | 1077/2129 [01:08<01:31, 11.55it/s]
 51%|█████     | 1079/2129 [01:08<01:35, 10.99it/s]
 51%|█████     | 1081/2129 [01:08<01:29, 11.76it/s]
 51%|█████     | 1083/2129 [01:08<01:36, 10.83it/s]
 51%|█████     | 1085/2129 [01:08<01:55,  9.01it/s]
 51%|█████     | 1087/2129 [01:09<01:39, 10.51it/s]
 51%|█████     | 1089/2129 [01:09<01:48,  9.59it/s]
 51%|█████     | 1091/2129 [01:09<01:56,  8.93it/s]
 51%|█████▏    | 1094/2129 [01:09<01:24, 12.19it/s]
 52%|█████▏    | 1099/2129 [01:09<01:10, 14.67it/s]
 52%|█████▏    | 1101/2129 [01:10<01:06, 15.54it/s]
 52%|█████▏    | 1103/2129 [01:10<01:16, 13.39it/s]
 52%|█████▏    | 1105/2129 [01:10<01:10, 14.50it/s]
 52%|█████▏    | 1107/2129 [01:10<01:29, 11.42it/s]
 52%|█████▏    | 1109/2129 [01:10<01:44,  9.76it/s]
 52%|█████▏    | 1111/2129 [01:11<01:48,  9.40it/s]
 52%|█████▏    | 1113/2129 [01:11<01:48,  9.35it/s]
 52%|█████▏    | 1115/2129 [01:11<01:32, 10.91it/s]
 52%|█████▏    | 1117/2129 [01:11<01:45,  9.57it/s]
 53%|█████▎    | 1119/2129 [01:11<01:48,  9.29it/s]
 53%|█████▎    | 1121/2129 [01:12<01:45,  9.53it/s]
 53%|█████▎    | 1124/2129 [01:12<01:18, 12.76it/s]
 53%|█████▎    | 1130/2129 [01:12<00:55, 17.89it/s]
 53%|█████▎    | 1132/2129 [01:12<01:32, 10.78it/s]
 53%|█████▎    | 1134/2129 [01:13<01:38, 10.13it/s]
 53%|█████▎    | 1136/2129 [01:13<01:43,  9.62it/s]
 53%|█████▎    | 1138/2129 [01:13<01:45,  9.35it/s]
 54%|█████▎    | 1140/2129 [01:13<01:52,  8.75it/s]
 54%|█████▎    | 1142/2129 [01:14<01:58,  8.30it/s]
 54%|█████▍    | 1145/2129 [01:14<01:52,  8.77it/s]
 54%|█████▍    | 1146/2129 [01:14<02:05,  7.81it/s]
 54%|█████▍    | 1149/2129 [01:14<01:29, 10.97it/s]
 54%|█████▍    | 1152/2129 [01:15<01:25, 11.38it/s]
 54%|█████▍    | 1154/2129 [01:15<01:17, 12.57it/s]
 54%|█████▍    | 1156/2129 [01:15<01:48,  8.99it/s]
 54%|█████▍    | 1158/2129 [01:15<01:54,  8.49it/s]
 54%|█████▍    | 1160/2129 [01:15<01:37,  9.94it/s]
 55%|█████▍    | 1163/2129 [01:16<01:13, 13.15it/s]
 55%|█████▍    | 1165/2129 [01:16<01:21, 11.80it/s]
 55%|█████▍    | 1169/2129 [01:16<01:14, 12.85it/s]
 55%|█████▌    | 1171/2129 [01:16<01:24, 11.35it/s]
 55%|█████▌    | 1174/2129 [01:17<01:23, 11.38it/s]
 55%|█████▌    | 1176/2129 [01:17<01:30, 10.50it/s]
 55%|█████▌    | 1178/2129 [01:17<01:23, 11.42it/s]
 55%|█████▌    | 1180/2129 [01:17<01:37,  9.72it/s]
 56%|█████▌    | 1182/2129 [01:17<01:28, 10.71it/s]
 56%|█████▌    | 1185/2129 [01:17<01:09, 13.59it/s]
 56%|█████▌    | 1187/2129 [01:18<01:20, 11.71it/s]
 56%|█████▌    | 1189/2129 [01:18<01:14, 12.55it/s]
 56%|█████▌    | 1191/2129 [01:18<01:26, 10.81it/s]
 56%|█████▌    | 1194/2129 [01:18<01:06, 14.15it/s]
 56%|█████▌    | 1196/2129 [01:18<01:20, 11.57it/s]
 56%|█████▋    | 1199/2129 [01:19<01:24, 10.98it/s]
 56%|█████▋    | 1202/2129 [01:19<01:08, 13.51it/s]
 57%|█████▋    | 1204/2129 [01:19<01:37,  9.47it/s]
 57%|█████▋    | 1206/2129 [01:20<01:43,  8.96it/s]
 57%|█████▋    | 1208/2129 [01:20<01:30, 10.14it/s]
 57%|█████▋    | 1211/2129 [01:20<01:22, 11.11it/s]
 57%|█████▋    | 1213/2129 [01:20<01:43,  8.82it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 328.35it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 0], [np.int64(2), False, 5], [np.int64(3), False, 11], [np.int64(4), False, 10], [np.int64(6), False, 5], [np.int64(7), False, 11], [np.int64(8), False, 5], [np.int64(9), False, 10], [np.int64(10), False, 2], [np.int64(12), False, 11], [np.int64(13), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8381, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [12:07<1:17:11, 46.78s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(11.9688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>)

 67%|██████▋   | 202/300 [12:08<53:33, 32.79s/it]

tensor(-3.9208, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0636, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [12:08<17:55, 11.33s/it]

tensor(12.0120, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2332, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4145, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [12:08<08:41,  5.61s/it]

tensor(12.0965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5145, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6074, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [12:08<04:15,  2.81s/it]

tensor(12.1661, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6393, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6512, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [12:09<02:07,  1.44s/it]

tensor(12.1621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7120, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [12:09<01:06,  1.31it/s]

tensor(12.1097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7504, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7983, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [12:09<00:49,  1.75it/s]

tensor(12.0673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8637, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [12:09<00:28,  2.92it/s]

tensor(12.0676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9149, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [12:10<00:16,  5.06it/s]

tensor(12.0671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9690, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [12:10<00:13,  5.73it/s]

tensor(12.0282, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9733, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9865, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [12:10<00:11,  6.68it/s]

tensor(12.0107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9872, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [12:10<00:09,  7.67it/s]

tensor(12.0063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9970, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9911, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [12:10<00:09,  7.69it/s]

tensor(12.0042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0131, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0329, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [12:11<00:08,  8.12it/s]

tensor(11.9973, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0275, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0396, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [12:11<00:08,  8.19it/s]

tensor(11.9883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0520, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0692, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [12:11<00:08,  8.18it/s]

tensor(11.9786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0908, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1080, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [12:11<00:08,  8.22it/s]

tensor(11.9660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1440, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [12:12<00:07,  8.20it/s]

tensor(11.9544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1550, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1669, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [12:12<00:07,  8.21it/s]

tensor(11.9452, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1782, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1903, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [12:12<00:07,  7.96it/s]

tensor(11.9387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2106, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2234, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [12:13<00:07,  8.11it/s]

tensor(11.9321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2544, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [12:13<00:06,  8.13it/s]

tensor(11.9266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9237, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2649, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [12:13<00:06,  8.19it/s]

tensor(11.9211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2722, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2853, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [12:13<00:06,  8.19it/s]

tensor(11.9167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2899, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2948, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [12:13<00:06,  8.21it/s]

tensor(11.9132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3115, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([147, 179, 114, 259, 103, 198, 224, 118, 135,  36, 333,  96,  63, 124])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<02:45, 12.87it/s]
  0%|          | 5/2129 [00:00<01:56, 18.23it/s]
  1%|          | 12/2129 [00:00<00:57, 36.72it/s]
  1%|          | 19/2129 [00:00<01:27, 23.98it/s]
  1%|          | 23/2129 [00:00<01:22, 25.48it/s]
  1%|▏         | 29/2129 [00:01<01:05, 31.94it/s]
  2%|▏         | 35/2129 [00:01<00:55, 38.00it/s]
  2%|▏         | 42/2129 [00:01<00:47, 44.27it/s]
  2%|▏         | 50/2129 [00:01<00:40, 51.66it/s]
  3%|▎         | 56/2129 [00:01<01:08, 30.23it/s]
  3%|▎         | 61/2129 [00:02<01:34, 21.83it/s]
  3%|▎         | 65/2129 [00:02<01:25, 24.20it/s]
  3%|▎         | 71/2129 [00:02<01:08, 29.97it/s]
  4%|▎         | 78/2129 [00:02<00:55, 36.79it/s]
  4%|▍         | 83/2129 [00:02<01:32, 22.23it/s]
  4%|▍         | 89/2129 [00:03<01:14, 27.40it/s]
  5%|▍         | 96/2129 [00:03<01:00, 33.75it/s]
  5%|▍         | 101/2129 [00:03<01:15, 26.90it/s]
  5%|▍         | 105/2129 [00:04<02:29, 13.55it/s]
  5%|▌         | 108/2129 [00:04<02:14, 15.00it/s]
  5%|▌         | 111/2129 [00:04<02:03, 16.30it/s]
  5%|▌         | 117/2129 [00:04<01:30, 22.28it/s]
  6%|▌         | 124/2129 [00:04<01:06, 30.06it/s]
  6%|▌         | 129/2129 [00:05<01:36, 20.81it/s]
  6%|▌         | 133/2129 [00:05<02:24, 13.81it/s]
  6%|▋         | 136/2129 [00:05<02:17, 14.46it/s]
  7%|▋         | 141/2129 [00:06<01:45, 18.89it/s]
  7%|▋         | 148/2129 [00:06<01:14, 26.56it/s]
  7%|▋         | 153/2129 [00:06<01:38, 20.15it/s]
  7%|▋         | 157/2129 [00:06<02:01, 16.29it/s]
  8%|▊         | 160/2129 [00:07<02:29, 13.21it/s]
  8%|▊         | 163/2129 [00:07<02:51, 11.45it/s]
  8%|▊         | 166/2129 [00:08<03:07, 10.45it/s]
  8%|▊         | 168/2129 [00:08<03:40,  8.89it/s]
  8%|▊         | 172/2129 [00:08<02:42, 12.02it/s]
  8%|▊         | 178/2129 [00:08<02:18, 14.08it/s]
  8%|▊         | 180/2129 [00:09<02:52, 11.27it/s]
  9%|▊         | 183/2129 [00:09<03:09, 10.25it/s]
  9%|▊         | 185/2129 [00:09<03:41,  8.79it/s]
  9%|▉         | 187/2129 [00:10<04:05,  7.90it/s]
  9%|▉         | 189/2129 [00:10<03:35,  8.99it/s]
  9%|▉         | 191/2129 [00:10<04:03,  7.95it/s]
  9%|▉         | 194/2129 [00:10<03:01, 10.66it/s]
  9%|▉         | 200/2129 [00:11<02:05, 15.38it/s]
  9%|▉         | 202/2129 [00:11<02:25, 13.23it/s]
 10%|▉         | 205/2129 [00:11<02:13, 14.41it/s]
 10%|▉         | 207/2129 [00:11<02:09, 14.85it/s]
 10%|▉         | 210/2129 [00:11<01:49, 17.59it/s]
 10%|█         | 213/2129 [00:12<02:37, 12.18it/s]
 10%|█         | 215/2129 [00:12<03:08, 10.17it/s]
 10%|█         | 217/2129 [00:12<03:42,  8.60it/s]
 10%|█         | 220/2129 [00:12<02:48, 11.33it/s]
 11%|█         | 225/2129 [00:13<02:38, 12.00it/s]
 11%|█         | 227/2129 [00:13<03:25,  9.27it/s]
 11%|█         | 230/2129 [00:13<02:42, 11.67it/s]
 11%|█         | 232/2129 [00:14<03:26,  9.18it/s]
 11%|█         | 234/2129 [00:14<05:01,  6.30it/s]
 11%|█         | 237/2129 [00:14<03:45,  8.38it/s]
 11%|█         | 239/2129 [00:15<04:01,  7.84it/s]
 11%|█▏        | 242/2129 [00:15<03:05, 10.17it/s]
 12%|█▏        | 246/2129 [00:15<03:03, 10.28it/s]
 12%|█▏        | 248/2129 [00:16<03:32,  8.84it/s]
 12%|█▏        | 250/2129 [00:16<04:08,  7.57it/s]
 12%|█▏        | 252/2129 [00:16<03:54,  8.00it/s]
 12%|█▏        | 253/2129 [00:16<03:53,  8.04it/s]
 12%|█▏        | 258/2129 [00:17<02:43, 11.45it/s]
 12%|█▏        | 260/2129 [00:17<02:31, 12.35it/s]
 12%|█▏        | 262/2129 [00:17<02:52, 10.84it/s]
 12%|█▏        | 265/2129 [00:17<02:22, 13.04it/s]
 13%|█▎        | 267/2129 [00:17<02:43, 11.37it/s]
 13%|█▎        | 271/2129 [00:17<01:59, 15.57it/s]
 13%|█▎        | 275/2129 [00:18<01:48, 17.02it/s]
 13%|█▎        | 277/2129 [00:18<01:46, 17.44it/s]
 13%|█▎        | 283/2129 [00:18<01:12, 25.60it/s]
 13%|█▎        | 287/2129 [00:18<01:39, 18.55it/s]
 14%|█▎        | 290/2129 [00:18<01:32, 19.79it/s]
 14%|█▍        | 293/2129 [00:19<02:08, 14.31it/s]
 14%|█▍        | 296/2129 [00:19<02:24, 12.71it/s]
 14%|█▍        | 298/2129 [00:19<02:20, 12.99it/s]
 14%|█▍        | 300/2129 [00:19<02:11, 13.87it/s]
 14%|█▍        | 303/2129 [00:19<01:51, 16.43it/s]
 14%|█▍        | 305/2129 [00:20<03:22,  9.01it/s]
 14%|█▍        | 308/2129 [00:20<02:42, 11.21it/s]
 15%|█▍        | 312/2129 [00:20<02:39, 11.39it/s]
 15%|█▍        | 314/2129 [00:21<03:12,  9.44it/s]
 15%|█▍        | 316/2129 [00:21<02:48, 10.77it/s]
 15%|█▌        | 322/2129 [00:21<01:39, 18.12it/s]
 15%|█▌        | 325/2129 [00:21<02:13, 13.47it/s]
 15%|█▌        | 328/2129 [00:22<02:39, 11.29it/s]
 16%|█▌        | 330/2129 [00:22<03:23,  8.82it/s]
 16%|█▌        | 332/2129 [00:22<03:42,  8.06it/s]
 16%|█▌        | 334/2129 [00:23<04:16,  7.01it/s]
 16%|█▌        | 337/2129 [00:23<03:49,  7.80it/s]
 16%|█▌        | 339/2129 [00:23<03:21,  8.86it/s]
 16%|█▌        | 342/2129 [00:23<03:03,  9.72it/s]
 16%|█▌        | 344/2129 [00:24<03:04,  9.65it/s]
 16%|█▋        | 346/2129 [00:24<03:22,  8.78it/s]
 16%|█▋        | 349/2129 [00:24<03:11,  9.32it/s]
 16%|█▋        | 351/2129 [00:24<02:48, 10.52it/s]
 17%|█▋        | 354/2129 [00:25<03:01,  9.79it/s]
 17%|█▋        | 356/2129 [00:25<03:25,  8.63it/s]
 17%|█▋        | 357/2129 [00:25<03:51,  7.66it/s]
 17%|█▋        | 358/2129 [00:26<04:42,  6.27it/s]
 17%|█▋        | 361/2129 [00:26<03:32,  8.31it/s]
 17%|█▋        | 362/2129 [00:26<03:28,  8.46it/s]
 17%|█▋        | 365/2129 [00:26<02:31, 11.63it/s]
 17%|█▋        | 369/2129 [00:26<01:43, 16.99it/s]
 18%|█▊        | 373/2129 [00:26<01:42, 17.15it/s]
 18%|█▊        | 376/2129 [00:27<01:53, 15.46it/s]
 18%|█▊        | 378/2129 [00:27<01:55, 15.16it/s]
 18%|█▊        | 380/2129 [00:27<02:39, 10.96it/s]
 18%|█▊        | 382/2129 [00:27<02:21, 12.37it/s]
 18%|█▊        | 384/2129 [00:27<02:14, 13.00it/s]
 18%|█▊        | 386/2129 [00:28<02:43, 10.69it/s]
 18%|█▊        | 389/2129 [00:28<02:06, 13.77it/s]
 18%|█▊        | 391/2129 [00:28<02:09, 13.37it/s]
 18%|█▊        | 393/2129 [00:28<02:09, 13.43it/s]
 19%|█▊        | 395/2129 [00:28<02:53,  9.97it/s]
 19%|█▉        | 400/2129 [00:29<02:15, 12.81it/s]
 19%|█▉        | 402/2129 [00:29<02:05, 13.81it/s]
 19%|█▉        | 404/2129 [00:29<02:38, 10.91it/s]
 19%|█▉        | 406/2129 [00:29<03:25,  8.37it/s]
 19%|█▉        | 408/2129 [00:30<04:03,  7.06it/s]
 19%|█▉        | 411/2129 [00:30<02:55,  9.78it/s]
 20%|█▉        | 418/2129 [00:30<01:33, 18.25it/s]
 20%|█▉        | 421/2129 [00:30<01:36, 17.64it/s]
 20%|██        | 427/2129 [00:30<01:08, 25.02it/s]
 20%|██        | 431/2129 [00:31<01:14, 22.81it/s]
 20%|██        | 435/2129 [00:31<01:53, 14.94it/s]
 21%|██        | 438/2129 [00:31<02:03, 13.74it/s]
 21%|██        | 441/2129 [00:32<02:24, 11.65it/s]
 21%|██        | 446/2129 [00:32<01:43, 16.32it/s]
 21%|██        | 451/2129 [00:32<01:24, 19.94it/s]
 21%|██▏       | 454/2129 [00:32<01:26, 19.32it/s]
 21%|██▏       | 457/2129 [00:33<02:05, 13.33it/s]
 22%|██▏       | 459/2129 [00:33<02:27, 11.33it/s]
 22%|██▏       | 461/2129 [00:33<02:16, 12.25it/s]
 22%|██▏       | 463/2129 [00:33<02:07, 13.09it/s]
 22%|██▏       | 466/2129 [00:33<02:28, 11.17it/s]
 22%|██▏       | 468/2129 [00:34<03:02,  9.09it/s]
 22%|██▏       | 471/2129 [00:34<03:17,  8.41it/s]
 22%|██▏       | 474/2129 [00:34<02:30, 10.98it/s]
 22%|██▏       | 476/2129 [00:35<03:05,  8.92it/s]
 22%|██▏       | 478/2129 [00:35<04:32,  6.06it/s]
 23%|██▎       | 480/2129 [00:35<03:46,  7.28it/s]
 23%|██▎       | 483/2129 [00:36<03:29,  7.85it/s]
 23%|██▎       | 485/2129 [00:36<03:52,  7.08it/s]
 23%|██▎       | 488/2129 [00:36<03:43,  7.34it/s]
 23%|██▎       | 490/2129 [00:37<04:03,  6.72it/s]
 23%|██▎       | 494/2129 [00:37<02:39, 10.23it/s]
 23%|██▎       | 500/2129 [00:37<01:37, 16.72it/s]
 24%|██▎       | 503/2129 [00:37<02:06, 12.82it/s]
 24%|██▍       | 508/2129 [00:38<02:06, 12.79it/s]
 24%|██▍       | 510/2129 [00:38<02:39, 10.15it/s]
 24%|██▍       | 512/2129 [00:38<02:25, 11.09it/s]
 24%|██▍       | 515/2129 [00:39<02:33, 10.55it/s]
 24%|██▍       | 517/2129 [00:39<02:25, 11.11it/s]
 24%|██▍       | 519/2129 [00:39<02:11, 12.22it/s]
 24%|██▍       | 521/2129 [00:39<02:23, 11.19it/s]
 25%|██▍       | 523/2129 [00:39<02:41,  9.97it/s]
 25%|██▍       | 526/2129 [00:40<02:23, 11.20it/s]
 25%|██▍       | 528/2129 [00:40<02:40,  9.99it/s]
 25%|██▍       | 530/2129 [00:40<03:11,  8.37it/s]
 25%|██▍       | 532/2129 [00:40<02:45,  9.64it/s]
 25%|██▌       | 534/2129 [00:40<02:25, 10.93it/s]
 25%|██▌       | 536/2129 [00:41<04:11,  6.34it/s]
 25%|██▌       | 539/2129 [00:41<02:56,  9.01it/s]
 26%|██▌       | 543/2129 [00:42<02:41,  9.83it/s]
 26%|██▌       | 546/2129 [00:42<02:11, 12.05it/s]
 26%|██▌       | 548/2129 [00:42<02:45,  9.53it/s]
 26%|██▌       | 552/2129 [00:42<01:59, 13.20it/s]
 26%|██▌       | 554/2129 [00:42<02:32, 10.34it/s]
 26%|██▌       | 556/2129 [00:43<02:17, 11.44it/s]
 26%|██▌       | 558/2129 [00:43<03:00,  8.69it/s]
 26%|██▋       | 560/2129 [00:43<03:31,  7.43it/s]
 26%|██▋       | 563/2129 [00:43<02:33, 10.19it/s]
 27%|██▋       | 565/2129 [00:44<03:03,  8.52it/s]
 27%|██▋       | 567/2129 [00:44<03:27,  7.52it/s]
 27%|██▋       | 570/2129 [00:44<02:33, 10.15it/s]
 27%|██▋       | 572/2129 [00:45<03:06,  8.34it/s]
 27%|██▋       | 576/2129 [00:45<02:06, 12.32it/s]
 27%|██▋       | 578/2129 [00:45<02:41,  9.63it/s]
 27%|██▋       | 581/2129 [00:45<02:48,  9.18it/s]
 27%|██▋       | 584/2129 [00:46<02:54,  8.85it/s]
 28%|██▊       | 586/2129 [00:46<03:21,  7.67it/s]
 28%|██▊       | 587/2129 [00:47<04:03,  6.34it/s]
 28%|██▊       | 589/2129 [00:47<04:10,  6.15it/s]
 28%|██▊       | 590/2129 [00:47<04:45,  5.38it/s]
 28%|██▊       | 593/2129 [00:48<04:08,  6.18it/s]
 28%|██▊       | 595/2129 [00:48<03:21,  7.60it/s]
 28%|██▊       | 599/2129 [00:48<02:45,  9.23it/s]
 28%|██▊       | 601/2129 [00:48<02:24, 10.58it/s]
 28%|██▊       | 603/2129 [00:48<02:37,  9.71it/s]
 28%|██▊       | 605/2129 [00:49<02:35,  9.81it/s]
 29%|██▊       | 607/2129 [00:49<02:14, 11.35it/s]
 29%|██▊       | 610/2129 [00:49<01:54, 13.22it/s]
 29%|██▊       | 612/2129 [00:49<02:14, 11.29it/s]
 29%|██▉       | 614/2129 [00:49<02:33,  9.85it/s]
 29%|██▉       | 616/2129 [00:50<03:04,  8.22it/s]
 29%|██▉       | 619/2129 [00:50<02:14, 11.20it/s]
 29%|██▉       | 622/2129 [00:50<02:06, 11.96it/s]
 29%|██▉       | 624/2129 [00:50<02:02, 12.24it/s]
 29%|██▉       | 626/2129 [00:50<02:26, 10.25it/s]
 29%|██▉       | 628/2129 [00:51<02:46,  9.04it/s]
 30%|██▉       | 631/2129 [00:51<02:12, 11.30it/s]
 30%|██▉       | 633/2129 [00:51<02:45,  9.03it/s]
 30%|██▉       | 635/2129 [00:51<02:25, 10.24it/s]
 30%|██▉       | 637/2129 [00:52<02:51,  8.69it/s]
 30%|███       | 639/2129 [00:52<02:25, 10.27it/s]
 30%|███       | 641/2129 [00:52<02:31,  9.85it/s]
 30%|███       | 643/2129 [00:52<02:35,  9.58it/s]
 30%|███       | 645/2129 [00:52<02:35,  9.56it/s]
 30%|███       | 647/2129 [00:53<02:15, 10.98it/s]
 30%|███       | 649/2129 [00:53<03:01,  8.14it/s]
 31%|███       | 652/2129 [00:53<02:14, 11.01it/s]
 31%|███       | 654/2129 [00:53<02:37,  9.37it/s]
 31%|███       | 658/2129 [00:54<02:32,  9.67it/s]
 31%|███       | 660/2129 [00:54<02:13, 10.97it/s]
 31%|███       | 662/2129 [00:55<03:32,  6.89it/s]
 31%|███       | 664/2129 [00:55<03:26,  7.09it/s]
 31%|███▏      | 667/2129 [00:55<03:20,  7.29it/s]
 31%|███▏      | 670/2129 [00:55<02:33,  9.48it/s]
 32%|███▏      | 672/2129 [00:55<02:28,  9.78it/s]
 32%|███▏      | 674/2129 [00:56<02:09, 11.22it/s]
 32%|███▏      | 677/2129 [00:56<02:30,  9.66it/s]
 32%|███▏      | 679/2129 [00:56<02:10, 11.08it/s]
 32%|███▏      | 681/2129 [00:56<02:19, 10.36it/s]
 32%|███▏      | 683/2129 [00:57<02:28,  9.71it/s]
 32%|███▏      | 685/2129 [00:57<02:36,  9.20it/s]
 32%|███▏      | 687/2129 [00:57<02:40,  8.98it/s]
 32%|███▏      | 688/2129 [00:57<02:49,  8.49it/s]
 32%|███▏      | 689/2129 [00:57<03:17,  7.28it/s]
 32%|███▏      | 691/2129 [00:57<02:33,  9.36it/s]
 33%|███▎      | 693/2129 [00:58<02:07, 11.22it/s]
 33%|███▎      | 695/2129 [00:58<02:35,  9.22it/s]
 33%|███▎      | 697/2129 [00:58<02:53,  8.27it/s]
 33%|███▎      | 699/2129 [00:58<02:26,  9.75it/s]
 33%|███▎      | 705/2129 [00:59<01:41, 14.10it/s]
 33%|███▎      | 707/2129 [00:59<02:09, 10.95it/s]
 33%|███▎      | 709/2129 [00:59<02:20, 10.14it/s]
 33%|███▎      | 711/2129 [00:59<02:04, 11.43it/s]
 33%|███▎      | 713/2129 [01:00<02:58,  7.92it/s]
 34%|███▎      | 716/2129 [01:00<02:13, 10.61it/s]
 34%|███▍      | 721/2129 [01:00<02:00, 11.72it/s]
 34%|███▍      | 723/2129 [01:01<02:24,  9.70it/s]
 34%|███▍      | 725/2129 [01:01<03:01,  7.75it/s]
 34%|███▍      | 726/2129 [01:01<03:38,  6.41it/s]
 34%|███▍      | 727/2129 [01:02<03:52,  6.02it/s]
 34%|███▍      | 728/2129 [01:02<04:17,  5.44it/s]
 34%|███▍      | 731/2129 [01:02<02:55,  7.98it/s]
 34%|███▍      | 733/2129 [01:02<02:48,  8.30it/s]
 34%|███▍      | 734/2129 [01:02<02:55,  7.95it/s]
 35%|███▍      | 737/2129 [01:02<02:00, 11.58it/s]
 35%|███▍      | 739/2129 [01:03<02:14, 10.37it/s]
 35%|███▍      | 741/2129 [01:03<01:57, 11.86it/s]
 35%|███▌      | 747/2129 [01:03<01:05, 21.26it/s]
 35%|███▌      | 750/2129 [01:03<01:39, 13.84it/s]
 35%|███▌      | 753/2129 [01:04<02:29,  9.18it/s]
 35%|███▌      | 755/2129 [01:04<02:39,  8.61it/s]
 36%|███▌      | 757/2129 [01:04<02:19,  9.83it/s]
 36%|███▌      | 762/2129 [01:04<01:40, 13.65it/s]
 36%|███▌      | 764/2129 [01:05<01:34, 14.37it/s]
 36%|███▌      | 766/2129 [01:05<02:01, 11.23it/s]
 36%|███▌      | 768/2129 [01:05<01:54, 11.87it/s]
 36%|███▌      | 770/2129 [01:05<02:01, 11.18it/s]
 36%|███▋      | 774/2129 [01:06<01:48, 12.51it/s]
 36%|███▋      | 776/2129 [01:06<02:32,  8.86it/s]
 37%|███▋      | 779/2129 [01:06<01:57, 11.48it/s]
 37%|███▋      | 781/2129 [01:07<03:26,  6.54it/s]
 37%|███▋      | 783/2129 [01:07<03:08,  7.12it/s]
 37%|███▋      | 785/2129 [01:07<02:55,  7.66it/s]
 37%|███▋      | 787/2129 [01:07<02:26,  9.17it/s]
 37%|███▋      | 789/2129 [01:07<02:08, 10.40it/s]
 37%|███▋      | 793/2129 [01:08<01:26, 15.49it/s]
 37%|███▋      | 796/2129 [01:08<02:17,  9.69it/s]
 37%|███▋      | 798/2129 [01:08<02:21,  9.39it/s]
 38%|███▊      | 800/2129 [01:09<02:31,  8.75it/s]
 38%|███▊      | 802/2129 [01:09<02:57,  7.49it/s]
 38%|███▊      | 804/2129 [01:09<02:53,  7.65it/s]
 38%|███▊      | 806/2129 [01:09<02:27,  8.96it/s]
 38%|███▊      | 809/2129 [01:10<02:20,  9.40it/s]
 38%|███▊      | 812/2129 [01:10<01:52, 11.73it/s]
 38%|███▊      | 814/2129 [01:10<02:25,  9.04it/s]
 38%|███▊      | 816/2129 [01:10<02:05, 10.46it/s]
 38%|███▊      | 818/2129 [01:11<02:35,  8.42it/s]
 39%|███▊      | 820/2129 [01:11<03:08,  6.93it/s]
 39%|███▊      | 822/2129 [01:11<02:38,  8.25it/s]
 39%|███▉      | 827/2129 [01:12<02:01, 10.76it/s]
 39%|███▉      | 830/2129 [01:12<01:39, 13.05it/s]
 39%|███▉      | 837/2129 [01:12<00:59, 21.57it/s]
 39%|███▉      | 840/2129 [01:12<01:27, 14.78it/s]
 40%|███▉      | 843/2129 [01:13<02:02, 10.47it/s]
 40%|███▉      | 845/2129 [01:13<02:13,  9.63it/s]
 40%|███▉      | 847/2129 [01:13<02:45,  7.73it/s]
 40%|███▉      | 849/2129 [01:14<02:45,  7.75it/s]
 40%|███▉      | 851/2129 [01:14<02:25,  8.79it/s]
 40%|████      | 853/2129 [01:14<02:45,  7.72it/s]
 40%|████      | 854/2129 [01:14<03:25,  6.21it/s]
 40%|████      | 855/2129 [01:15<04:02,  5.25it/s]
 40%|████      | 858/2129 [01:15<02:40,  7.93it/s]
 40%|████      | 860/2129 [01:15<02:53,  7.32it/s]
 40%|████      | 862/2129 [01:16<03:00,  7.02it/s]
 41%|████      | 865/2129 [01:16<02:54,  7.25it/s]
 41%|████      | 866/2129 [01:16<03:35,  5.85it/s]
 41%|████      | 868/2129 [01:16<02:52,  7.32it/s]
 41%|████      | 871/2129 [01:17<02:01, 10.35it/s]
 41%|████      | 873/2129 [01:17<01:52, 11.14it/s]
 41%|████      | 876/2129 [01:17<01:30, 13.89it/s]
 41%|████▏     | 879/2129 [01:17<01:40, 12.43it/s]
 41%|████▏     | 881/2129 [01:17<01:32, 13.55it/s]
 41%|████▏     | 883/2129 [01:17<01:27, 14.29it/s]
 42%|████▏     | 886/2129 [01:18<01:24, 14.63it/s]
 42%|████▏     | 888/2129 [01:18<01:50, 11.27it/s]
 42%|████▏     | 891/2129 [01:18<01:48, 11.36it/s]
 42%|████▏     | 893/2129 [01:18<01:57, 10.52it/s]
 42%|████▏     | 895/2129 [01:18<01:49, 11.22it/s]
 42%|████▏     | 897/2129 [01:19<01:37, 12.58it/s]
 42%|████▏     | 899/2129 [01:19<01:41, 12.14it/s]
 42%|████▏     | 901/2129 [01:19<01:36, 12.78it/s]
 42%|████▏     | 903/2129 [01:19<02:07,  9.58it/s]
 43%|████▎     | 906/2129 [01:19<01:50, 11.09it/s]
 43%|████▎     | 908/2129 [01:20<01:40, 12.16it/s]
 43%|████▎     | 911/2129 [01:20<02:01, 10.03it/s]
 43%|████▎     | 913/2129 [01:20<02:35,  7.81it/s]
 43%|████▎     | 914/2129 [01:21<03:15,  6.22it/s]
 43%|████▎     | 916/2129 [01:21<03:22,  5.98it/s]
 43%|████▎     | 919/2129 [01:21<02:21,  8.57it/s]
 43%|████▎     | 921/2129 [01:22<02:43,  7.39it/s]
 43%|████▎     | 925/2129 [01:22<01:45, 11.44it/s]
 44%|████▎     | 927/2129 [01:22<01:56, 10.28it/s]
 44%|████▎     | 929/2129 [01:22<02:01,  9.87it/s]
 44%|████▎     | 931/2129 [01:22<02:10,  9.18it/s]
 44%|████▍     | 933/2129 [01:23<01:56, 10.28it/s]
 44%|████▍     | 936/2129 [01:23<02:21,  8.45it/s]
 44%|████▍     | 938/2129 [01:24<03:19,  5.98it/s]
 44%|████▍     | 939/2129 [01:24<03:41,  5.38it/s]
 44%|████▍     | 941/2129 [01:24<02:52,  6.88it/s]
 44%|████▍     | 944/2129 [01:24<02:43,  7.25it/s]
 44%|████▍     | 945/2129 [01:25<03:16,  6.01it/s]
 44%|████▍     | 947/2129 [01:25<03:15,  6.05it/s]
 45%|████▍     | 949/2129 [01:25<02:35,  7.60it/s]
 45%|████▍     | 951/2129 [01:25<02:50,  6.91it/s]
 45%|████▍     | 955/2129 [01:26<02:22,  8.26it/s]
 45%|████▍     | 958/2129 [01:26<02:22,  8.20it/s]
 45%|████▌     | 959/2129 [01:27<02:54,  6.69it/s]
 45%|████▌     | 960/2129 [01:27<03:16,  5.94it/s]
 45%|████▌     | 961/2129 [01:27<03:49,  5.10it/s]
 45%|████▌     | 963/2129 [01:27<03:44,  5.20it/s]
 45%|████▌     | 964/2129 [01:28<04:13,  4.59it/s]
 45%|████▌     | 966/2129 [01:28<03:04,  6.31it/s]
 45%|████▌     | 968/2129 [01:28<03:05,  6.28it/s]
 46%|████▌     | 969/2129 [01:29<03:44,  5.16it/s]
 46%|████▌     | 970/2129 [01:29<04:20,  4.45it/s]
 46%|████▌     | 972/2129 [01:29<03:05,  6.23it/s]
 46%|████▌     | 973/2129 [01:29<03:28,  5.54it/s]
 46%|████▌     | 974/2129 [01:30<03:48,  5.05it/s]
 46%|████▌     | 975/2129 [01:30<03:20,  5.74it/s]
 46%|████▌     | 977/2129 [01:30<03:18,  5.79it/s]
 46%|████▌     | 980/2129 [01:30<02:06,  9.10it/s]
 46%|████▌     | 982/2129 [01:30<02:29,  7.69it/s]
 46%|████▌     | 984/2129 [01:31<02:03,  9.26it/s]
 46%|████▋     | 988/2129 [01:31<01:53, 10.03it/s]
 47%|████▋     | 990/2129 [01:31<01:44, 10.88it/s]
 47%|████▋     | 992/2129 [01:31<01:34, 12.03it/s]
 47%|████▋     | 994/2129 [01:32<02:09,  8.76it/s]
 47%|████▋     | 999/2129 [01:32<01:17, 14.64it/s]
 47%|████▋     | 1002/2129 [01:32<02:02,  9.17it/s]
 47%|████▋     | 1005/2129 [01:32<01:37, 11.51it/s]
 47%|████▋     | 1008/2129 [01:33<01:54,  9.76it/s]
 47%|████▋     | 1010/2129 [01:33<02:11,  8.50it/s]
 48%|████▊     | 1012/2129 [01:33<02:12,  8.45it/s]
 48%|████▊     | 1014/2129 [01:34<02:03,  8.99it/s]
 48%|████▊     | 1016/2129 [01:34<02:26,  7.58it/s]
 48%|████▊     | 1018/2129 [01:34<02:04,  8.91it/s]
 48%|████▊     | 1020/2129 [01:34<02:19,  7.95it/s]
 48%|████▊     | 1023/2129 [01:35<02:07,  8.70it/s]
 48%|████▊     | 1025/2129 [01:35<01:59,  9.28it/s]
 48%|████▊     | 1028/2129 [01:35<01:36, 11.41it/s]
 48%|████▊     | 1030/2129 [01:35<01:31, 12.02it/s]
 48%|████▊     | 1032/2129 [01:35<01:34, 11.55it/s]
 49%|████▊     | 1035/2129 [01:35<01:15, 14.52it/s]
 49%|████▉     | 1040/2129 [01:36<01:12, 15.05it/s]
 49%|████▉     | 1042/2129 [01:36<01:14, 14.59it/s]
 49%|████▉     | 1044/2129 [01:36<01:16, 14.25it/s]
 49%|████▉     | 1048/2129 [01:36<01:07, 16.10it/s]
 49%|████▉     | 1051/2129 [01:37<01:09, 15.45it/s]
 50%|████▉     | 1054/2129 [01:37<01:03, 17.03it/s]
 50%|████▉     | 1056/2129 [01:37<01:48,  9.85it/s]
 50%|████▉     | 1058/2129 [01:37<01:50,  9.66it/s]
 50%|████▉     | 1061/2129 [01:38<01:32, 11.49it/s]
 50%|████▉     | 1064/2129 [01:38<01:33, 11.38it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 342.40it/s]
 84%|████████▎ | 251/300 [15:51<53:24, 65.40s/it]

[[np.int64(0), False, 3], [np.int64(1), False, 5], [np.int64(2), False, 7], [np.int64(3), False, 10], [np.int64(4), False, 5], [np.int64(6), False, 3], [np.int64(7), False, 3], [np.int64(8), False, 3], [np.int64(9), False, 3], [np.int64(10), False, 1], [np.int64(11), False, 7], [np.int64(12), False, 6], [np.int64(13), False, 5]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7908, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [15:51<36:39, 45.83s/it]

tensor(11.9188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1390, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6817, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [15:52<11:50, 15.80s/it]

tensor(12.0045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8807, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8789, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [15:52<05:35,  7.80s/it]

tensor(12.0582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8072, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8666, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [15:52<03:50,  5.50s/it]

tensor(12.0017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0676, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2606, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [15:52<01:50,  2.76s/it]

tensor(11.9816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3119, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [15:52<00:53,  1.41s/it]

tensor(12.0385, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2803, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2522, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [15:53<00:27,  1.33it/s]

tensor(12.0461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2711, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3070, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [15:53<00:14,  2.32it/s]

tensor(11.9665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3282, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3449, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [15:53<00:08,  3.66it/s]

tensor(11.9587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3600, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3720, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [15:53<00:05,  5.10it/s]

tensor(11.9696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3816, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [15:54<00:04,  6.32it/s]

tensor(11.9539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4010, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4230, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [15:54<00:03,  7.08it/s]

tensor(11.9290, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4329, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4341, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [15:54<00:02,  7.86it/s]

tensor(11.9198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4437, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9233, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4462, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [15:54<00:02,  7.96it/s]

tensor(11.9271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4446, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9250, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4469, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [15:55<00:02,  8.13it/s]

tensor(11.9160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4502, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4529, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [15:55<00:02,  8.17it/s]

tensor(11.8995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4559, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4571, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [15:55<00:01,  8.18it/s]

tensor(11.9013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4546, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9034, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4552, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [15:55<00:01,  8.19it/s]

tensor(11.9032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4572, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4577, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [15:56<00:01,  8.22it/s]

tensor(11.8956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4560, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4559, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [15:56<00:01,  8.22it/s]

tensor(11.8833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4592, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4680, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [15:56<00:00,  8.19it/s]

tensor(11.8783, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4683, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4756, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [15:57<00:00,  8.22it/s]

tensor(11.8764, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4765, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4807, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [15:57<00:00,  8.21it/s]

tensor(11.8717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4834, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4850, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [15:57<00:00,  8.22it/s]

tensor(11.8671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4839, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4875, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [15:57<00:00,  3.19s/it]

tensor(11.8645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4854, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.002087831497192383
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 1
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.527283807336
NMI         : 0.589601427503
Runtime     : 1002.81 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed1

==============================================================================================================
PRAGA RUN | E18.5 | seed=2
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 3.784e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(15.6293, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4770, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6267, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2252, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:32,  9.01it/s]

tensor(15.6200, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1947, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6123, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3644, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:31,  9.46it/s]

tensor(15.5993, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7132, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5892, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2245, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:30,  9.68it/s]

tensor(15.5785, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8819, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5661, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6719, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.77it/s]

tensor(15.5563, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5819, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5481, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5977, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:30,  9.61it/s]

tensor(15.5383, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7114, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5319, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9129, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:28,  9.87it/s]

tensor(15.5259, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1926, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5200, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5441, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:28,  9.86it/s]

tensor(15.5146, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9591, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5103, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4331, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5060, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9585, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.87it/s]

tensor(15.5004, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5310, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4955, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1464, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:28,  9.85it/s]

tensor(15.4895, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8000, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4837, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4885, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:28,  9.88it/s]

tensor(15.4761, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2080, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4669, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9557, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:28,  9.72it/s]

tensor(15.4555, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7292, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4456, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5259, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:27,  9.86it/s]

tensor(15.4321, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3423, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4176, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1781, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4010, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0308, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|▉         | 29/300 [00:02<00:27,  9.77it/s]

tensor(15.3821, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8988, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7804, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.88it/s]

tensor(15.3393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6745, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5802, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:26,  9.87it/s]

tensor(15.2892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4954, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4207, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:27,  9.79it/s]

tensor(15.2332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3538, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2947, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.91it/s]

tensor(15.1701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2424, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1969, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0989, device='cuda:0', grad_fn=<AddBackward0>)

 13%|█▎        | 40/300 [00:04<00:26,  9.92it/s]

tensor(0.1569, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1225, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:26,  9.73it/s]

tensor(15.0180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0928, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9738, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0701, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:26,  9.63it/s]

tensor(14.9269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0526, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8783, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:26,  9.62it/s]

tensor(14.8279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0353, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.71it/s]

tensor(14.7233, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:25,  9.74it/s]

tensor(14.6108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5517, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.66it/s]

tensor(14.4903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:24,  9.85it/s]

tensor(14.3600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2932, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:25,  9.71it/s]

tensor(14.1601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:06<00:25,  9.63it/s]

tensor(14.0346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:06<00:24,  9.57it/s]

tensor(13.9278, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:24,  9.57it/s]

tensor(13.8506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:24,  9.46it/s]

tensor(13.7844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:24,  9.63it/s]

tensor(13.7092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6703, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:07<00:23,  9.74it/s]

tensor(13.6337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:23,  9.79it/s]

tensor(13.5710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5444, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:23,  9.83it/s]

tensor(13.5199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:22,  9.83it/s]

tensor(13.4726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 77/300 [00:07<00:22,  9.84it/s]

tensor(13.4244, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3994, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:22,  9.82it/s]

tensor(13.3735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:08<00:22,  9.85it/s]

tensor(13.3210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:22,  9.85it/s]

tensor(13.2695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:21,  9.83it/s]

tensor(13.2214, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:22,  9.61it/s]

tensor(13.1758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:09<00:22,  9.54it/s]

tensor(13.1323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1105, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:09<00:21,  9.55it/s]

tensor(13.0889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:21,  9.44it/s]

tensor(13.0470, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:21,  9.57it/s]

tensor(13.0075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:21,  9.61it/s]

tensor(12.9706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:10<00:21,  9.49it/s]

tensor(12.9345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.47it/s]

tensor(12.8989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([252, 193,  87, 122,  78, 392, 253,  93, 257,  46,  70,  96,  74, 116])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<02:39, 13.33it/s]
  0%|          | 5/2129 [00:00<01:41, 20.83it/s]
  0%|          | 8/2129 [00:00<01:57, 18.04it/s]
  0%|          | 10/2129 [00:00<02:10, 16.21it/s]
  1%|          | 12/2129 [00:00<02:03, 17.11it/s]
  1%|          | 14/2129 [00:00<02:20, 15.01it/s]
  1%|          | 16/2129 [00:00<02:15, 15.62it/s]
  1%|          | 18/2129 [00:01<02:31, 13.97it/s]
  1%|          | 20/2129 [00:01<02:34, 13.65it/s]
  1%|          | 22/2129 [00:01<02:36, 13.45it/s]
  1%|          | 24/2129 [00:01<02:29, 14.13it/s]
  1%|          | 26/2129 [00:01<02:30, 13.95it/s]
  1%|▏         | 28/2129 [00:02<03:07, 11.23it/s]
  1%|▏         | 30/2129 [00:02<03:07, 11.18it/s]
  2%|▏         | 34/2129 [00:02<02:11, 15.91it/s]
  2%|▏         | 36/2129 [00:02<02:25, 14.38it/s]
  2%|▏         | 41/2129 [00:02<02:09, 16.09it/s]
  2%|▏         | 44/2129 [00:02<02:00, 17.35it/s]
  2%|▏         | 47/2129 [00:03<01:46, 19.59it/s]
  2%|▏         | 50/2129 [00:03<01:52, 18.48it/s]
  3%|▎         | 54/2129 [00:03<02:03, 16.82it/s]
  3%|▎         | 57/2129 [00:03<01:55, 18.02it/s]
  3%|▎         | 60/2129 [00:03<01:43, 19.99it/s]
  3%|▎         | 63/2129 [00:03<01:52, 18.41it/s]
  3%|▎         | 65/2129 [00:04<02:28, 13.87it/s]
  3%|▎         | 67/2129 [00:04<02:34, 13.30it/s]
  3%|▎         | 70/2129 [00:04<02:31, 13.55it/s]
  3%|▎         | 72/2129 [00:04<02:35, 13.26it/s]
  3%|▎         | 74/2129 [00:04<02:56, 11.62it/s]
  4%|▎         | 76/2129 [00:05<02:42, 12.65it/s]
  4%|▎         | 79/2129 [00:05<02:11, 15.64it/s]
  4%|▍         | 81/2129 [00:05<02:45, 12.37it/s]
  4%|▍         | 84/2129 [00:05<02:26, 13.95it/s]
  4%|▍         | 87/2129 [00:05<02:00, 16.96it/s]
  4%|▍         | 93/2129 [00:05<01:20, 25.22it/s]
  5%|▍         | 96/2129 [00:05<01:23, 24.23it/s]
  5%|▍         | 101/2129 [00:06<01:07, 30.12it/s]
  5%|▍         | 105/2129 [00:06<01:56, 17.36it/s]
  5%|▌         | 108/2129 [00:06<01:45, 19.24it/s]
  5%|▌         | 112/2129 [00:06<01:41, 19.84it/s]
  5%|▌         | 115/2129 [00:07<02:07, 15.75it/s]
  6%|▌         | 118/2129 [00:07<01:52, 17.86it/s]
  6%|▌         | 124/2129 [00:07<01:21, 24.72it/s]
  6%|▌         | 128/2129 [00:07<01:27, 22.92it/s]
  6%|▌         | 132/2129 [00:07<01:41, 19.61it/s]
  6%|▋         | 135/2129 [00:08<02:02, 16.27it/s]
  7%|▋         | 139/2129 [00:08<01:40, 19.80it/s]
  7%|▋         | 146/2129 [00:08<01:09, 28.44it/s]
  7%|▋         | 152/2129 [00:08<00:57, 34.34it/s]
  7%|▋         | 157/2129 [00:08<01:44, 18.93it/s]
  8%|▊         | 161/2129 [00:09<01:58, 16.68it/s]
  8%|▊         | 164/2129 [00:09<02:27, 13.33it/s]
  8%|▊         | 167/2129 [00:09<02:32, 12.87it/s]
  8%|▊         | 169/2129 [00:10<02:54, 11.26it/s]
  8%|▊         | 171/2129 [00:10<03:06, 10.50it/s]
  8%|▊         | 173/2129 [00:10<02:47, 11.68it/s]
  8%|▊         | 177/2129 [00:10<02:03, 15.82it/s]
  8%|▊         | 180/2129 [00:10<02:18, 14.02it/s]
  9%|▊         | 183/2129 [00:11<01:57, 16.52it/s]
  9%|▊         | 186/2129 [00:11<02:22, 13.64it/s]
  9%|▉         | 188/2129 [00:11<03:07, 10.37it/s]
  9%|▉         | 190/2129 [00:11<03:14,  9.97it/s]
  9%|▉         | 193/2129 [00:12<02:35, 12.43it/s]
  9%|▉         | 195/2129 [00:12<02:46, 11.62it/s]
  9%|▉         | 197/2129 [00:12<02:36, 12.37it/s]
  9%|▉         | 200/2129 [00:12<02:53, 11.09it/s]
  9%|▉         | 202/2129 [00:13<03:18,  9.73it/s]
 10%|▉         | 205/2129 [00:13<02:37, 12.24it/s]
 10%|▉         | 207/2129 [00:13<02:27, 13.00it/s]
 10%|▉         | 209/2129 [00:13<02:18, 13.86it/s]
 10%|▉         | 212/2129 [00:13<02:52, 11.13it/s]
 10%|█         | 214/2129 [00:14<03:26,  9.26it/s]
 10%|█         | 216/2129 [00:14<03:23,  9.42it/s]
 10%|█         | 219/2129 [00:14<02:52, 11.10it/s]
 10%|█         | 221/2129 [00:14<02:33, 12.45it/s]
 10%|█         | 223/2129 [00:14<02:51, 11.15it/s]
 11%|█         | 226/2129 [00:15<02:55, 10.86it/s]
 11%|█         | 228/2129 [00:15<02:34, 12.31it/s]
 11%|█         | 231/2129 [00:15<02:05, 15.18it/s]
 11%|█         | 233/2129 [00:15<02:20, 13.46it/s]
 11%|█         | 235/2129 [00:15<02:25, 13.04it/s]
 11%|█         | 237/2129 [00:15<02:12, 14.25it/s]
 11%|█         | 239/2129 [00:16<03:11,  9.88it/s]
 11%|█▏        | 241/2129 [00:16<02:54, 10.79it/s]
 12%|█▏        | 246/2129 [00:16<02:04, 15.16it/s]
 12%|█▏        | 248/2129 [00:16<02:29, 12.60it/s]
 12%|█▏        | 250/2129 [00:17<02:52, 10.89it/s]
 12%|█▏        | 252/2129 [00:17<02:58, 10.54it/s]
 12%|█▏        | 255/2129 [00:17<02:21, 13.20it/s]
 12%|█▏        | 258/2129 [00:17<02:29, 12.49it/s]
 12%|█▏        | 260/2129 [00:17<02:24, 12.92it/s]
 12%|█▏        | 262/2129 [00:17<02:50, 10.97it/s]
 12%|█▏        | 265/2129 [00:18<02:11, 14.14it/s]
 13%|█▎        | 268/2129 [00:18<01:56, 15.93it/s]
 13%|█▎        | 270/2129 [00:18<02:08, 14.44it/s]
 13%|█▎        | 272/2129 [00:18<02:13, 13.91it/s]
 13%|█▎        | 274/2129 [00:18<02:21, 13.07it/s]
 13%|█▎        | 276/2129 [00:19<02:52, 10.77it/s]
 13%|█▎        | 279/2129 [00:19<02:19, 13.25it/s]
 13%|█▎        | 281/2129 [00:19<02:15, 13.67it/s]
 13%|█▎        | 283/2129 [00:19<02:15, 13.58it/s]
 13%|█▎        | 286/2129 [00:19<01:51, 16.54it/s]
 14%|█▎        | 288/2129 [00:19<02:18, 13.30it/s]
 14%|█▎        | 291/2129 [00:19<01:54, 16.11it/s]
 14%|█▍        | 293/2129 [00:20<02:13, 13.79it/s]
 14%|█▍        | 295/2129 [00:20<03:19,  9.18it/s]
 14%|█▍        | 300/2129 [00:20<02:01, 15.07it/s]
 14%|█▍        | 304/2129 [00:20<02:01, 15.07it/s]
 14%|█▍        | 307/2129 [00:21<02:35, 11.68it/s]
 15%|█▍        | 310/2129 [00:21<02:10, 13.97it/s]
 15%|█▍        | 312/2129 [00:21<02:13, 13.60it/s]
 15%|█▍        | 314/2129 [00:22<03:11,  9.46it/s]
 15%|█▍        | 317/2129 [00:22<02:45, 10.97it/s]
 15%|█▍        | 319/2129 [00:22<02:56, 10.27it/s]
 15%|█▌        | 321/2129 [00:22<02:52, 10.49it/s]
 15%|█▌        | 324/2129 [00:22<02:58, 10.12it/s]
 15%|█▌        | 327/2129 [00:23<02:21, 12.72it/s]
 15%|█▌        | 329/2129 [00:23<03:03,  9.84it/s]
 16%|█▌        | 331/2129 [00:23<03:48,  7.85it/s]
 16%|█▌        | 333/2129 [00:23<03:21,  8.93it/s]
 16%|█▌        | 335/2129 [00:24<03:53,  7.69it/s]
 16%|█▌        | 337/2129 [00:24<03:48,  7.86it/s]
 16%|█▌        | 340/2129 [00:24<02:54, 10.24it/s]
 16%|█▌        | 342/2129 [00:25<03:25,  8.69it/s]
 16%|█▌        | 344/2129 [00:25<03:42,  8.01it/s]
 16%|█▌        | 345/2129 [00:25<04:32,  6.54it/s]
 16%|█▋        | 348/2129 [00:25<03:04,  9.63it/s]
 16%|█▋        | 350/2129 [00:26<04:12,  7.04it/s]
 17%|█▋        | 353/2129 [00:26<03:04,  9.61it/s]
 17%|█▋        | 355/2129 [00:26<03:52,  7.63it/s]
 17%|█▋        | 357/2129 [00:27<04:27,  6.64it/s]
 17%|█▋        | 358/2129 [00:27<04:36,  6.40it/s]
 17%|█▋        | 359/2129 [00:27<04:22,  6.75it/s]
 17%|█▋        | 361/2129 [00:27<03:58,  7.41it/s]
 17%|█▋        | 362/2129 [00:27<04:23,  6.71it/s]
 17%|█▋        | 364/2129 [00:28<04:10,  7.04it/s]
 17%|█▋        | 366/2129 [00:28<03:20,  8.79it/s]
 17%|█▋        | 369/2129 [00:28<02:41, 10.90it/s]
 17%|█▋        | 372/2129 [00:28<02:03, 14.18it/s]
 18%|█▊        | 374/2129 [00:28<02:42, 10.82it/s]
 18%|█▊        | 376/2129 [00:29<03:17,  8.89it/s]
 18%|█▊        | 379/2129 [00:29<02:32, 11.48it/s]
 18%|█▊        | 381/2129 [00:29<02:43, 10.67it/s]
 18%|█▊        | 384/2129 [00:29<02:50, 10.26it/s]
 18%|█▊        | 386/2129 [00:30<02:58,  9.79it/s]
 18%|█▊        | 390/2129 [00:30<02:07, 13.65it/s]
 18%|█▊        | 392/2129 [00:30<02:55,  9.90it/s]
 19%|█▊        | 394/2129 [00:30<03:42,  7.79it/s]
 19%|█▊        | 396/2129 [00:31<03:39,  7.90it/s]
 19%|█▉        | 400/2129 [00:31<02:58,  9.67it/s]
 19%|█▉        | 402/2129 [00:31<03:04,  9.38it/s]
 19%|█▉        | 404/2129 [00:32<03:09,  9.13it/s]
 19%|█▉        | 405/2129 [00:32<03:58,  7.23it/s]
 19%|█▉        | 406/2129 [00:32<04:18,  6.68it/s]
 19%|█▉        | 407/2129 [00:32<04:25,  6.49it/s]
 19%|█▉        | 408/2129 [00:32<04:47,  5.99it/s]
 19%|█▉        | 410/2129 [00:33<04:09,  6.88it/s]
 19%|█▉        | 413/2129 [00:33<02:43, 10.52it/s]
 19%|█▉        | 415/2129 [00:33<03:22,  8.46it/s]
 20%|█▉        | 418/2129 [00:33<02:28, 11.50it/s]
 20%|█▉        | 421/2129 [00:33<02:17, 12.47it/s]
 20%|█▉        | 425/2129 [00:33<01:40, 16.94it/s]
 20%|██        | 428/2129 [00:34<01:29, 18.98it/s]
 20%|██        | 431/2129 [00:34<01:46, 15.90it/s]
 20%|██        | 433/2129 [00:34<02:49, 10.00it/s]
 20%|██        | 436/2129 [00:35<02:42, 10.45it/s]
 21%|██        | 438/2129 [00:35<02:44, 10.26it/s]
 21%|██        | 440/2129 [00:35<03:09,  8.92it/s]
 21%|██        | 442/2129 [00:35<03:10,  8.85it/s]
 21%|██        | 444/2129 [00:35<02:41, 10.42it/s]
 21%|██        | 446/2129 [00:36<02:49,  9.93it/s]
 21%|██        | 448/2129 [00:36<02:38, 10.62it/s]
 21%|██        | 452/2129 [00:36<02:05, 13.39it/s]
 21%|██▏       | 454/2129 [00:36<02:07, 13.16it/s]
 21%|██▏       | 456/2129 [00:36<02:35, 10.78it/s]
 22%|██▏       | 458/2129 [00:37<02:52,  9.69it/s]
 22%|██▏       | 460/2129 [00:37<03:10,  8.75it/s]
 22%|██▏       | 463/2129 [00:37<02:26, 11.34it/s]
 22%|██▏       | 466/2129 [00:37<02:15, 12.24it/s]
 22%|██▏       | 468/2129 [00:38<02:22, 11.65it/s]
 22%|██▏       | 471/2129 [00:38<02:23, 11.57it/s]
 22%|██▏       | 473/2129 [00:38<02:37, 10.54it/s]
 22%|██▏       | 475/2129 [00:38<02:25, 11.33it/s]
 22%|██▏       | 477/2129 [00:39<02:58,  9.23it/s]
 22%|██▏       | 479/2129 [00:39<02:57,  9.28it/s]
 23%|██▎       | 481/2129 [00:39<02:53,  9.53it/s]
 23%|██▎       | 483/2129 [00:39<02:38, 10.37it/s]
 23%|██▎       | 485/2129 [00:39<02:33, 10.68it/s]
 23%|██▎       | 487/2129 [00:39<02:40, 10.24it/s]
 23%|██▎       | 490/2129 [00:40<02:30, 10.86it/s]
 23%|██▎       | 492/2129 [00:40<02:17, 11.93it/s]
 23%|██▎       | 496/2129 [00:40<02:08, 12.73it/s]
 23%|██▎       | 498/2129 [00:40<02:09, 12.62it/s]
 23%|██▎       | 500/2129 [00:40<02:03, 13.20it/s]
 24%|██▎       | 502/2129 [00:41<02:31, 10.74it/s]
 24%|██▎       | 505/2129 [00:41<02:13, 12.15it/s]
 24%|██▍       | 508/2129 [00:41<02:26, 11.03it/s]
 24%|██▍       | 510/2129 [00:41<02:33, 10.57it/s]
 24%|██▍       | 512/2129 [00:42<03:03,  8.80it/s]
 24%|██▍       | 515/2129 [00:42<02:55,  9.19it/s]
 24%|██▍       | 517/2129 [00:42<02:54,  9.23it/s]
 24%|██▍       | 519/2129 [00:42<02:39, 10.09it/s]
 24%|██▍       | 521/2129 [00:43<02:57,  9.08it/s]
 25%|██▍       | 522/2129 [00:43<03:16,  8.19it/s]
 25%|██▍       | 525/2129 [00:43<02:44,  9.74it/s]
 25%|██▍       | 526/2129 [00:43<03:44,  7.15it/s]
 25%|██▍       | 527/2129 [00:44<04:04,  6.54it/s]
 25%|██▍       | 528/2129 [00:44<04:30,  5.93it/s]
 25%|██▍       | 529/2129 [00:44<04:50,  5.51it/s]
 25%|██▍       | 530/2129 [00:44<05:21,  4.98it/s]
 25%|██▌       | 533/2129 [00:44<03:02,  8.73it/s]
 25%|██▌       | 535/2129 [00:45<02:51,  9.28it/s]
 25%|██▌       | 537/2129 [00:45<02:35, 10.24it/s]
 25%|██▌       | 539/2129 [00:45<02:21, 11.25it/s]
 25%|██▌       | 541/2129 [00:45<02:08, 12.40it/s]
 26%|██▌       | 543/2129 [00:45<02:45,  9.59it/s]
 26%|██▌       | 547/2129 [00:46<02:02, 12.87it/s]
 26%|██▌       | 549/2129 [00:46<02:11, 11.97it/s]
 26%|██▌       | 553/2129 [00:46<01:35, 16.46it/s]
 26%|██▌       | 555/2129 [00:46<01:49, 14.34it/s]
 26%|██▌       | 557/2129 [00:46<02:16, 11.53it/s]
 26%|██▋       | 559/2129 [00:47<02:43,  9.62it/s]
 26%|██▋       | 563/2129 [00:47<02:26, 10.68it/s]
 27%|██▋       | 565/2129 [00:47<02:39,  9.80it/s]
 27%|██▋       | 567/2129 [00:48<03:17,  7.89it/s]
 27%|██▋       | 569/2129 [00:48<02:46,  9.34it/s]
 27%|██▋       | 571/2129 [00:48<02:55,  8.86it/s]
 27%|██▋       | 573/2129 [00:48<03:02,  8.51it/s]
 27%|██▋       | 575/2129 [00:48<02:36,  9.95it/s]
 27%|██▋       | 577/2129 [00:49<02:47,  9.26it/s]
 27%|██▋       | 580/2129 [00:49<02:03, 12.54it/s]
 27%|██▋       | 582/2129 [00:49<03:05,  8.35it/s]
 27%|██▋       | 584/2129 [00:49<03:06,  8.30it/s]
 28%|██▊       | 586/2129 [00:50<03:50,  6.69it/s]
 28%|██▊       | 587/2129 [00:50<04:08,  6.20it/s]
 28%|██▊       | 589/2129 [00:50<03:56,  6.52it/s]
 28%|██▊       | 590/2129 [00:51<04:16,  6.01it/s]
 28%|██▊       | 592/2129 [00:51<03:18,  7.72it/s]
 28%|██▊       | 593/2129 [00:51<03:31,  7.25it/s]
 28%|██▊       | 594/2129 [00:51<03:50,  6.65it/s]
 28%|██▊       | 595/2129 [00:51<04:07,  6.20it/s]
 28%|██▊       | 597/2129 [00:51<03:07,  8.18it/s]
 28%|██▊       | 599/2129 [00:52<02:35,  9.85it/s]
 28%|██▊       | 602/2129 [00:52<02:18, 11.01it/s]
 28%|██▊       | 605/2129 [00:52<01:53, 13.45it/s]
 29%|██▊       | 608/2129 [00:52<01:35, 15.86it/s]
 29%|██▊       | 610/2129 [00:52<01:59, 12.76it/s]
 29%|██▊       | 612/2129 [00:53<02:18, 10.99it/s]
 29%|██▉       | 614/2129 [00:53<02:32,  9.95it/s]
 29%|██▉       | 618/2129 [00:53<01:47, 14.06it/s]
 29%|██▉       | 621/2129 [00:53<01:30, 16.59it/s]
 29%|██▉       | 623/2129 [00:53<02:09, 11.63it/s]
 29%|██▉       | 626/2129 [00:54<02:12, 11.34it/s]
 29%|██▉       | 628/2129 [00:54<02:56,  8.50it/s]
 30%|██▉       | 630/2129 [00:54<02:34,  9.68it/s]
 30%|██▉       | 632/2129 [00:54<02:47,  8.94it/s]
 30%|██▉       | 635/2129 [00:55<02:08, 11.64it/s]
 30%|██▉       | 637/2129 [00:55<02:21, 10.54it/s]
 30%|███       | 640/2129 [00:55<01:51, 13.32it/s]
 30%|███       | 642/2129 [00:55<02:03, 12.00it/s]
 30%|███       | 644/2129 [00:56<03:01,  8.20it/s]
 30%|███       | 646/2129 [00:56<03:06,  7.95it/s]
 30%|███       | 649/2129 [00:56<02:48,  8.79it/s]
 31%|███       | 651/2129 [00:56<02:39,  9.25it/s]
 31%|███       | 653/2129 [00:57<02:50,  8.67it/s]
 31%|███       | 655/2129 [00:57<02:29,  9.87it/s]
 31%|███       | 658/2129 [00:57<02:23, 10.23it/s]
 31%|███       | 660/2129 [00:57<02:06, 11.58it/s]
 31%|███       | 662/2129 [00:58<02:52,  8.51it/s]
 31%|███       | 664/2129 [00:58<02:56,  8.29it/s]
 31%|███▏      | 667/2129 [00:58<02:41,  9.06it/s]
 31%|███▏      | 669/2129 [00:58<02:20, 10.43it/s]
 32%|███▏      | 671/2129 [00:58<02:04, 11.75it/s]
 32%|███▏      | 673/2129 [00:59<02:22, 10.25it/s]
 32%|███▏      | 676/2129 [00:59<01:50, 13.17it/s]
 32%|███▏      | 678/2129 [00:59<02:03, 11.79it/s]
 32%|███▏      | 680/2129 [00:59<02:03, 11.75it/s]
 32%|███▏      | 683/2129 [00:59<01:47, 13.44it/s]
 32%|███▏      | 685/2129 [01:00<02:05, 11.48it/s]
 32%|███▏      | 687/2129 [01:00<01:56, 12.35it/s]
 32%|███▏      | 689/2129 [01:00<01:49, 13.14it/s]
 33%|███▎      | 692/2129 [01:00<01:33, 15.43it/s]
 33%|███▎      | 694/2129 [01:00<02:20, 10.25it/s]
 33%|███▎      | 696/2129 [01:01<02:45,  8.67it/s]
 33%|███▎      | 698/2129 [01:01<02:25,  9.83it/s]
 33%|███▎      | 700/2129 [01:01<02:13, 10.67it/s]
 33%|███▎      | 702/2129 [01:01<02:02, 11.62it/s]
 33%|███▎      | 704/2129 [01:01<02:22,  9.98it/s]
 33%|███▎      | 706/2129 [01:02<02:55,  8.13it/s]
 33%|███▎      | 707/2129 [01:02<03:16,  7.22it/s]
 33%|███▎      | 708/2129 [01:02<03:42,  6.38it/s]
 33%|███▎      | 711/2129 [01:02<02:28,  9.56it/s]
 33%|███▎      | 713/2129 [01:03<03:17,  7.18it/s]
 34%|███▎      | 715/2129 [01:03<02:38,  8.91it/s]
 34%|███▍      | 719/2129 [01:03<02:08, 10.98it/s]
 34%|███▍      | 721/2129 [01:03<02:49,  8.30it/s]
 34%|███▍      | 723/2129 [01:04<02:51,  8.22it/s]
 34%|███▍      | 724/2129 [01:04<03:17,  7.12it/s]
 34%|███▍      | 725/2129 [01:04<03:30,  6.65it/s]
 34%|███▍      | 726/2129 [01:04<03:39,  6.41it/s]
 34%|███▍      | 727/2129 [01:05<04:00,  5.83it/s]
 34%|███▍      | 728/2129 [01:05<04:19,  5.39it/s]
 34%|███▍      | 730/2129 [01:05<03:10,  7.34it/s]
 34%|███▍      | 733/2129 [01:05<02:47,  8.33it/s]
 35%|███▍      | 736/2129 [01:05<02:00, 11.56it/s]
 35%|███▍      | 738/2129 [01:06<02:12, 10.51it/s]
 35%|███▍      | 740/2129 [01:06<02:56,  7.88it/s]
 35%|███▍      | 742/2129 [01:06<02:50,  8.15it/s]
 35%|███▍      | 744/2129 [01:06<02:23,  9.63it/s]
 35%|███▌      | 748/2129 [01:06<01:38, 13.95it/s]
 35%|███▌      | 751/2129 [01:07<01:49, 12.57it/s]
 35%|███▌      | 753/2129 [01:07<02:05, 10.99it/s]
 35%|███▌      | 755/2129 [01:07<02:53,  7.90it/s]
 36%|███▌      | 758/2129 [01:08<02:37,  8.72it/s]
 36%|███▌      | 761/2129 [01:08<02:04, 10.98it/s]
 36%|███▌      | 763/2129 [01:08<03:00,  7.56it/s]
 36%|███▌      | 765/2129 [01:08<02:32,  8.95it/s]
 36%|███▌      | 767/2129 [01:09<03:05,  7.36it/s]
 36%|███▌      | 769/2129 [01:09<02:50,  7.97it/s]
 36%|███▋      | 772/2129 [01:09<02:11, 10.35it/s]
 36%|███▋      | 774/2129 [01:09<01:56, 11.66it/s]
 36%|███▋      | 776/2129 [01:09<01:54, 11.87it/s]
 37%|███▋      | 778/2129 [01:10<02:01, 11.15it/s]
 37%|███▋      | 780/2129 [01:10<02:28,  9.09it/s]
 37%|███▋      | 782/2129 [01:10<03:11,  7.05it/s]
 37%|███▋      | 784/2129 [01:11<03:06,  7.20it/s]
 37%|███▋      | 785/2129 [01:11<03:43,  6.01it/s]
 37%|███▋      | 787/2129 [01:11<03:42,  6.04it/s]
 37%|███▋      | 789/2129 [01:11<02:57,  7.57it/s]
 37%|███▋      | 792/2129 [01:12<02:21,  9.42it/s]
 37%|███▋      | 794/2129 [01:12<02:36,  8.52it/s]
 37%|███▋      | 795/2129 [01:12<02:52,  7.71it/s]
 37%|███▋      | 796/2129 [01:12<03:35,  6.19it/s]
 37%|███▋      | 798/2129 [01:13<03:18,  6.70it/s]
 38%|███▊      | 800/2129 [01:13<03:22,  6.55it/s]
 38%|███▊      | 802/2129 [01:13<02:46,  7.95it/s]
 38%|███▊      | 803/2129 [01:13<02:51,  7.75it/s]
 38%|███▊      | 805/2129 [01:13<02:24,  9.14it/s]
 38%|███▊      | 808/2129 [01:14<01:46, 12.39it/s]
 38%|███▊      | 810/2129 [01:14<02:30,  8.74it/s]
 38%|███▊      | 812/2129 [01:14<02:18,  9.53it/s]
 38%|███▊      | 814/2129 [01:14<02:31,  8.67it/s]
 38%|███▊      | 817/2129 [01:15<01:51, 11.72it/s]
 38%|███▊      | 819/2129 [01:15<02:09, 10.13it/s]
 39%|███▊      | 821/2129 [01:15<02:25,  9.02it/s]
 39%|███▉      | 825/2129 [01:15<01:38, 13.29it/s]
 39%|███▉      | 827/2129 [01:15<01:54, 11.39it/s]
 39%|███▉      | 830/2129 [01:16<01:36, 13.48it/s]
 39%|███▉      | 832/2129 [01:16<01:37, 13.31it/s]
 39%|███▉      | 834/2129 [01:16<01:30, 14.37it/s]
 39%|███▉      | 838/2129 [01:16<01:31, 14.11it/s]
 39%|███▉      | 840/2129 [01:16<01:39, 13.00it/s]
 40%|███▉      | 842/2129 [01:17<01:48, 11.85it/s]
 40%|███▉      | 844/2129 [01:17<02:08,  9.97it/s]
 40%|███▉      | 846/2129 [01:17<02:29,  8.59it/s]
 40%|███▉      | 848/2129 [01:17<02:24,  8.89it/s]
 40%|███▉      | 850/2129 [01:17<02:04, 10.24it/s]
 40%|████      | 852/2129 [01:18<01:55, 11.03it/s]
 40%|████      | 854/2129 [01:18<02:10,  9.75it/s]
 40%|████      | 856/2129 [01:18<02:33,  8.30it/s]
 40%|████      | 859/2129 [01:18<01:53, 11.19it/s]
 40%|████      | 861/2129 [01:19<02:29,  8.50it/s]
 41%|████      | 863/2129 [01:19<02:19,  9.04it/s]
 41%|████      | 865/2129 [01:19<02:39,  7.95it/s]
 41%|████      | 867/2129 [01:19<02:18,  9.13it/s]
 41%|████      | 869/2129 [01:20<02:04, 10.13it/s]
 41%|████      | 871/2129 [01:20<02:15,  9.31it/s]
 41%|████      | 873/2129 [01:20<02:42,  7.72it/s]
 41%|████      | 876/2129 [01:20<02:07,  9.81it/s]
 41%|████      | 878/2129 [01:21<02:07,  9.82it/s]
 41%|████▏     | 880/2129 [01:21<02:13,  9.38it/s]
 41%|████▏     | 882/2129 [01:21<02:58,  7.00it/s]
 42%|████▏     | 884/2129 [01:21<02:26,  8.49it/s]
 42%|████▏     | 886/2129 [01:22<02:26,  8.47it/s]
 42%|████▏     | 888/2129 [01:22<02:26,  8.47it/s]
 42%|████▏     | 889/2129 [01:22<02:38,  7.84it/s]
 42%|████▏     | 890/2129 [01:22<02:50,  7.25it/s]
 42%|████▏     | 891/2129 [01:22<03:15,  6.32it/s]
 42%|████▏     | 893/2129 [01:23<02:23,  8.60it/s]
 42%|████▏     | 895/2129 [01:23<02:30,  8.19it/s]
 42%|████▏     | 896/2129 [01:23<02:45,  7.44it/s]
 42%|████▏     | 898/2129 [01:23<02:51,  7.16it/s]
 42%|████▏     | 900/2129 [01:24<02:47,  7.35it/s]
 42%|████▏     | 902/2129 [01:24<02:36,  7.86it/s]
 42%|████▏     | 903/2129 [01:24<03:02,  6.72it/s]
 43%|████▎     | 905/2129 [01:24<02:41,  7.60it/s]
 43%|████▎     | 906/2129 [01:24<03:06,  6.55it/s]
 43%|████▎     | 908/2129 [01:25<02:59,  6.82it/s]
 43%|████▎     | 910/2129 [01:25<02:21,  8.61it/s]
 43%|████▎     | 912/2129 [01:25<03:04,  6.58it/s]
 43%|████▎     | 914/2129 [01:26<02:56,  6.90it/s]
 43%|████▎     | 917/2129 [01:26<02:09,  9.38it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 327.92it/s]

[[np.int64(0), False, 5], [np.int64(1), False, 6], [np.int64(2), False, 10], [np.int64(3), False, 10], [np.int64(4), False, 13], [np.int64(6), False, 0], [np.int64(7), False, 11], [np.int64(8), False, 5], [np.int64(9), False, 0], [np.int64(10), False, 8], [np.int64(12), False, 6], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-1.7752, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [03:52<3:40:56, 66.62s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [03:52<2:34:00, 46.67s/it]

tensor(12.8762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.0139, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.3641, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [03:52<52:16, 16.09s/it]

tensor(12.9685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6249, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.7501, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [03:52<36:31, 11.30s/it]

tensor(13.0544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8884, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [03:53<12:35,  3.95s/it]

tensor(13.0130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.9774, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0955, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [03:53<06:17,  2.00s/it]

tensor(12.9664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2943, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [03:53<03:14,  1.04s/it]

tensor(12.9398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3680, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4267, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [03:53<01:45,  1.75it/s]

tensor(12.8344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4986, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5735, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [03:54<01:02,  2.92it/s]

tensor(12.8103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6347, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6809, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [03:54<00:41,  4.35it/s]

tensor(12.7903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7360, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7945, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [03:54<00:35,  5.08it/s]

tensor(12.7416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9319, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [03:54<00:28,  6.30it/s]

tensor(12.7197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9940, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0458, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [03:54<00:24,  7.12it/s]

tensor(12.7052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0893, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1418, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [03:55<00:22,  7.81it/s]

tensor(12.6720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1946, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2472, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [03:55<00:21,  8.03it/s]

tensor(12.6515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2758, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3176, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [03:55<00:20,  8.15it/s]

tensor(12.6272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3635, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [03:55<00:20,  8.11it/s]

tensor(12.5923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3957, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4137, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [03:56<00:20,  8.22it/s]

tensor(12.5668, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4453, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5563, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4665, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [03:56<00:19,  8.21it/s]

tensor(12.5440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5066, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5299, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [03:56<00:19,  8.22it/s]

tensor(12.5168, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5915, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [03:56<00:19,  8.23it/s]

tensor(12.4918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6040, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6266, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:57<00:19,  8.23it/s]

tensor(12.4647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4518, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6712, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [03:57<00:18,  8.21it/s]

tensor(12.4397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6798, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4276, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6982, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [03:57<00:18,  8.22it/s]

tensor(12.4151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7341, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:57<00:18,  8.21it/s]

tensor(12.3889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7640, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:58<00:18,  8.20it/s]

tensor(12.3648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7724, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([212,  81, 163,  71, 136,  91,  84, 179, 134,  97, 175, 103, 340, 263])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:38, 21.65it/s]
  0%|          | 8/2129 [00:00<01:11, 29.83it/s]
  1%|          | 11/2129 [00:00<01:24, 25.17it/s]
  1%|          | 14/2129 [00:00<01:22, 25.69it/s]
  1%|          | 20/2129 [00:00<01:04, 32.85it/s]
  1%|          | 24/2129 [00:00<01:02, 33.91it/s]
  1%|▏         | 29/2129 [00:00<00:55, 37.52it/s]
  2%|▏         | 35/2129 [00:01<00:49, 42.02it/s]
  2%|▏         | 40/2129 [00:01<00:47, 43.59it/s]
  2%|▏         | 45/2129 [00:01<01:21, 25.72it/s]
  2%|▏         | 50/2129 [00:01<01:47, 19.33it/s]
  2%|▏         | 53/2129 [00:02<01:45, 19.60it/s]
  3%|▎         | 56/2129 [00:02<01:41, 20.48it/s]
  3%|▎         | 63/2129 [00:02<01:10, 29.27it/s]
  3%|▎         | 70/2129 [00:02<00:56, 36.31it/s]
  4%|▎         | 75/2129 [00:02<01:20, 25.46it/s]
  4%|▎         | 79/2129 [00:02<01:23, 24.60it/s]
  4%|▍         | 85/2129 [00:03<01:07, 30.35it/s]
  4%|▍         | 89/2129 [00:03<01:10, 28.97it/s]
  4%|▍         | 93/2129 [00:03<01:11, 28.59it/s]
  5%|▍         | 97/2129 [00:03<01:23, 24.43it/s]
  5%|▍         | 101/2129 [00:03<01:16, 26.54it/s]
  5%|▌         | 108/2129 [00:03<00:57, 35.04it/s]
  5%|▌         | 113/2129 [00:03<01:00, 33.29it/s]
  6%|▌         | 120/2129 [00:04<00:49, 40.82it/s]
  6%|▌         | 127/2129 [00:04<00:42, 46.88it/s]
  6%|▋         | 134/2129 [00:04<00:38, 52.15it/s]
  7%|▋         | 141/2129 [00:04<00:35, 56.46it/s]
  7%|▋         | 147/2129 [00:04<00:35, 55.45it/s]
  7%|▋         | 154/2129 [00:04<00:34, 57.22it/s]
  8%|▊         | 160/2129 [00:04<00:56, 34.74it/s]
  8%|▊         | 169/2129 [00:05<00:44, 43.84it/s]
  8%|▊         | 177/2129 [00:05<00:39, 49.50it/s]
  9%|▊         | 183/2129 [00:05<00:58, 33.50it/s]
  9%|▉         | 188/2129 [00:05<01:08, 28.47it/s]
  9%|▉         | 192/2129 [00:06<01:32, 21.01it/s]
  9%|▉         | 199/2129 [00:06<01:10, 27.33it/s]
 10%|▉         | 204/2129 [00:06<01:45, 18.23it/s]
 10%|▉         | 212/2129 [00:06<01:15, 25.37it/s]
 10%|█         | 217/2129 [00:07<01:27, 21.78it/s]
 10%|█         | 223/2129 [00:07<01:26, 21.94it/s]
 11%|█         | 227/2129 [00:07<01:21, 23.21it/s]
 11%|█         | 233/2129 [00:07<01:22, 23.02it/s]
 11%|█         | 236/2129 [00:08<01:40, 18.76it/s]
 11%|█         | 239/2129 [00:08<01:41, 18.58it/s]
 11%|█▏        | 242/2129 [00:08<01:38, 19.11it/s]
 12%|█▏        | 249/2129 [00:08<01:10, 26.58it/s]
 12%|█▏        | 253/2129 [00:08<01:20, 23.39it/s]
 12%|█▏        | 258/2129 [00:09<01:28, 21.22it/s]
 12%|█▏        | 261/2129 [00:09<02:30, 12.42it/s]
 12%|█▏        | 264/2129 [00:09<02:12, 14.06it/s]
 13%|█▎        | 272/2129 [00:09<01:21, 22.71it/s]
 13%|█▎        | 276/2129 [00:10<01:33, 19.91it/s]
 13%|█▎        | 281/2129 [00:10<01:16, 24.20it/s]
 13%|█▎        | 287/2129 [00:10<01:18, 23.46it/s]
 14%|█▎        | 291/2129 [00:10<01:13, 25.06it/s]
 14%|█▍        | 295/2129 [00:11<01:27, 20.98it/s]
 14%|█▍        | 298/2129 [00:11<01:26, 21.22it/s]
 14%|█▍        | 302/2129 [00:11<01:18, 23.41it/s]
 14%|█▍        | 305/2129 [00:11<01:46, 17.10it/s]
 14%|█▍        | 308/2129 [00:11<01:41, 17.94it/s]
 15%|█▍        | 312/2129 [00:11<01:26, 20.97it/s]
 15%|█▍        | 315/2129 [00:12<01:44, 17.28it/s]
 15%|█▌        | 320/2129 [00:12<01:18, 22.94it/s]
 15%|█▌        | 324/2129 [00:12<01:25, 20.99it/s]
 15%|█▌        | 327/2129 [00:12<01:22, 21.81it/s]
 16%|█▌        | 330/2129 [00:12<01:42, 17.48it/s]
 16%|█▌        | 334/2129 [00:13<01:48, 16.47it/s]
 16%|█▌        | 337/2129 [00:13<01:39, 18.05it/s]
 16%|█▌        | 342/2129 [00:13<01:33, 19.14it/s]
 16%|█▌        | 345/2129 [00:13<01:50, 16.10it/s]
 16%|█▋        | 349/2129 [00:14<01:52, 15.81it/s]
 16%|█▋        | 351/2129 [00:14<02:13, 13.30it/s]
 17%|█▋        | 354/2129 [00:14<01:53, 15.70it/s]
 17%|█▋        | 356/2129 [00:14<02:07, 13.87it/s]
 17%|█▋        | 358/2129 [00:14<01:58, 14.89it/s]
 17%|█▋        | 361/2129 [00:14<02:02, 14.45it/s]
 17%|█▋        | 363/2129 [00:15<02:20, 12.60it/s]
 17%|█▋        | 366/2129 [00:15<01:52, 15.67it/s]
 17%|█▋        | 372/2129 [00:15<01:11, 24.66it/s]
 18%|█▊        | 376/2129 [00:15<01:28, 19.91it/s]
 18%|█▊        | 381/2129 [00:15<01:12, 24.08it/s]
 18%|█▊        | 384/2129 [00:15<01:15, 23.15it/s]
 18%|█▊        | 387/2129 [00:16<01:41, 17.08it/s]
 18%|█▊        | 390/2129 [00:16<01:36, 17.99it/s]
 18%|█▊        | 393/2129 [00:16<01:28, 19.57it/s]
 19%|█▉        | 400/2129 [00:16<01:10, 24.54it/s]
 19%|█▉        | 403/2129 [00:16<01:22, 21.01it/s]
 19%|█▉        | 406/2129 [00:17<01:42, 16.82it/s]
 19%|█▉        | 408/2129 [00:17<02:07, 13.50it/s]
 19%|█▉        | 411/2129 [00:17<01:56, 14.81it/s]
 19%|█▉        | 414/2129 [00:17<01:40, 17.07it/s]
 20%|█▉        | 422/2129 [00:18<01:21, 21.01it/s]
 20%|█▉        | 425/2129 [00:18<01:20, 21.14it/s]
 20%|██        | 430/2129 [00:18<01:05, 26.11it/s]
 20%|██        | 433/2129 [00:18<01:12, 23.49it/s]
 20%|██        | 436/2129 [00:18<01:37, 17.29it/s]
 21%|██        | 439/2129 [00:19<01:52, 15.05it/s]
 21%|██        | 441/2129 [00:19<01:51, 15.19it/s]
 21%|██        | 448/2129 [00:19<01:07, 24.77it/s]
 21%|██        | 452/2129 [00:19<01:30, 18.62it/s]
 21%|██▏       | 455/2129 [00:19<01:25, 19.62it/s]
 22%|██▏       | 459/2129 [00:19<01:26, 19.37it/s]
 22%|██▏       | 462/2129 [00:20<01:22, 20.28it/s]
 22%|██▏       | 466/2129 [00:20<01:26, 19.29it/s]
 22%|██▏       | 469/2129 [00:20<01:41, 16.41it/s]
 22%|██▏       | 471/2129 [00:20<01:37, 17.00it/s]
 22%|██▏       | 477/2129 [00:20<01:24, 19.65it/s]
 23%|██▎       | 480/2129 [00:21<01:21, 20.35it/s]
 23%|██▎       | 484/2129 [00:21<01:28, 18.68it/s]
 23%|██▎       | 487/2129 [00:21<01:22, 19.84it/s]
 23%|██▎       | 496/2129 [00:21<00:50, 32.14it/s]
 24%|██▎       | 503/2129 [00:21<00:41, 39.17it/s]
 24%|██▍       | 508/2129 [00:21<00:49, 32.72it/s]
 24%|██▍       | 512/2129 [00:22<01:39, 16.31it/s]
 24%|██▍       | 515/2129 [00:22<01:46, 15.16it/s]
 24%|██▍       | 518/2129 [00:22<01:37, 16.59it/s]
 24%|██▍       | 521/2129 [00:23<01:44, 15.44it/s]
 25%|██▍       | 524/2129 [00:23<01:36, 16.60it/s]
 25%|██▍       | 527/2129 [00:23<01:55, 13.90it/s]
 25%|██▍       | 529/2129 [00:23<02:07, 12.50it/s]
 25%|██▍       | 531/2129 [00:23<02:03, 12.97it/s]
 25%|██▌       | 534/2129 [00:24<01:46, 14.91it/s]
 25%|██▌       | 536/2129 [00:24<02:02, 12.98it/s]
 25%|██▌       | 539/2129 [00:24<01:51, 14.26it/s]
 26%|██▌       | 543/2129 [00:24<01:39, 15.95it/s]
 26%|██▌       | 546/2129 [00:24<01:28, 17.93it/s]
 26%|██▌       | 553/2129 [00:24<00:56, 27.94it/s]
 26%|██▌       | 557/2129 [00:25<01:10, 22.33it/s]
 26%|██▋       | 560/2129 [00:25<01:12, 21.67it/s]
 26%|██▋       | 564/2129 [00:25<01:13, 21.32it/s]
 27%|██▋       | 567/2129 [00:25<01:36, 16.18it/s]
 27%|██▋       | 570/2129 [00:25<01:28, 17.60it/s]
 27%|██▋       | 573/2129 [00:26<01:45, 14.75it/s]
 27%|██▋       | 577/2129 [00:26<01:42, 15.13it/s]
 27%|██▋       | 580/2129 [00:26<01:32, 16.79it/s]
 27%|██▋       | 582/2129 [00:26<01:52, 13.70it/s]
 28%|██▊       | 586/2129 [00:26<01:25, 18.03it/s]
 28%|██▊       | 589/2129 [00:27<01:31, 16.85it/s]
 28%|██▊       | 592/2129 [00:27<01:47, 14.34it/s]
 28%|██▊       | 596/2129 [00:27<01:59, 12.81it/s]
 28%|██▊       | 598/2129 [00:27<01:53, 13.54it/s]
 28%|██▊       | 600/2129 [00:28<02:08, 11.92it/s]
 28%|██▊       | 602/2129 [00:28<02:21, 10.78it/s]
 28%|██▊       | 604/2129 [00:28<02:54,  8.74it/s]
 28%|██▊       | 606/2129 [00:28<02:33,  9.95it/s]
 29%|██▉       | 614/2129 [00:29<01:12, 21.02it/s]
 29%|██▉       | 620/2129 [00:29<00:55, 27.41it/s]
 29%|██▉       | 626/2129 [00:29<00:59, 25.18it/s]
 30%|██▉       | 630/2129 [00:29<01:18, 18.99it/s]
 30%|██▉       | 636/2129 [00:29<01:00, 24.79it/s]
 30%|███       | 641/2129 [00:30<01:04, 23.16it/s]
 30%|███       | 645/2129 [00:30<01:20, 18.51it/s]
 30%|███       | 648/2129 [00:30<01:40, 14.78it/s]
 31%|███       | 652/2129 [00:30<01:22, 17.85it/s]
 31%|███       | 655/2129 [00:31<01:41, 14.56it/s]
 31%|███       | 660/2129 [00:31<01:40, 14.64it/s]
 31%|███       | 663/2129 [00:31<01:31, 15.95it/s]
 31%|███▏      | 670/2129 [00:31<01:01, 23.87it/s]
 32%|███▏      | 674/2129 [00:32<01:12, 20.14it/s]
 32%|███▏      | 679/2129 [00:32<01:23, 17.28it/s]
 32%|███▏      | 682/2129 [00:32<01:19, 18.10it/s]
 32%|███▏      | 685/2129 [00:32<01:26, 16.70it/s]
 32%|███▏      | 687/2129 [00:32<01:25, 16.85it/s]
 32%|███▏      | 689/2129 [00:33<01:57, 12.23it/s]
 32%|███▏      | 691/2129 [00:33<01:51, 12.85it/s]
 33%|███▎      | 694/2129 [00:33<01:42, 14.07it/s]
 33%|███▎      | 696/2129 [00:33<02:09, 11.11it/s]
 33%|███▎      | 700/2129 [00:34<01:32, 15.52it/s]
 33%|███▎      | 703/2129 [00:34<01:30, 15.71it/s]
 33%|███▎      | 705/2129 [00:34<01:43, 13.82it/s]
 33%|███▎      | 707/2129 [00:34<02:00, 11.84it/s]
 33%|███▎      | 709/2129 [00:34<02:16, 10.41it/s]
 33%|███▎      | 712/2129 [00:35<02:16, 10.36it/s]
 34%|███▎      | 716/2129 [00:35<01:39, 14.25it/s]
 34%|███▍      | 721/2129 [00:35<01:28, 15.91it/s]
 34%|███▍      | 724/2129 [00:35<01:37, 14.40it/s]
 34%|███▍      | 726/2129 [00:35<01:34, 14.82it/s]
 34%|███▍      | 728/2129 [00:36<01:50, 12.66it/s]
 34%|███▍      | 730/2129 [00:36<01:41, 13.72it/s]
 34%|███▍      | 733/2129 [00:36<01:42, 13.61it/s]
 35%|███▍      | 736/2129 [00:36<01:27, 15.90it/s]
 35%|███▍      | 739/2129 [00:36<01:32, 14.97it/s]
 35%|███▍      | 741/2129 [00:37<01:28, 15.77it/s]
 35%|███▌      | 748/2129 [00:37<00:51, 26.78it/s]
 35%|███▌      | 752/2129 [00:37<01:05, 21.17it/s]
 35%|███▌      | 755/2129 [00:37<01:46, 12.95it/s]
 36%|███▌      | 758/2129 [00:38<01:33, 14.67it/s]
 36%|███▌      | 766/2129 [00:38<01:11, 19.13it/s]
 36%|███▌      | 769/2129 [00:38<01:21, 16.78it/s]
 36%|███▋      | 772/2129 [00:39<01:47, 12.62it/s]
 36%|███▋      | 774/2129 [00:39<01:53, 11.95it/s]
 36%|███▋      | 776/2129 [00:39<01:59, 11.28it/s]
 37%|███▋      | 778/2129 [00:39<02:16,  9.87it/s]
 37%|███▋      | 780/2129 [00:39<02:25,  9.28it/s]
 37%|███▋      | 783/2129 [00:40<01:55, 11.68it/s]
 37%|███▋      | 785/2129 [00:40<01:58, 11.34it/s]
 37%|███▋      | 787/2129 [00:40<02:57,  7.55it/s]
 37%|███▋      | 791/2129 [00:40<01:59, 11.19it/s]
 37%|███▋      | 795/2129 [00:41<01:41, 13.17it/s]
 37%|███▋      | 797/2129 [00:41<01:57, 11.30it/s]
 38%|███▊      | 799/2129 [00:41<02:16,  9.73it/s]
 38%|███▊      | 802/2129 [00:42<02:12, 10.00it/s]
 38%|███▊      | 804/2129 [00:42<01:57, 11.26it/s]
 38%|███▊      | 810/2129 [00:42<01:25, 15.46it/s]
 38%|███▊      | 813/2129 [00:42<01:20, 16.42it/s]
 38%|███▊      | 817/2129 [00:42<01:26, 15.08it/s]
 39%|███▊      | 820/2129 [00:43<01:30, 14.45it/s]
 39%|███▊      | 823/2129 [00:43<01:23, 15.72it/s]
 39%|███▉      | 825/2129 [00:43<01:21, 15.96it/s]
 39%|███▉      | 831/2129 [00:43<01:15, 17.23it/s]
 39%|███▉      | 834/2129 [00:43<01:11, 18.23it/s]
 39%|███▉      | 838/2129 [00:43<01:00, 21.23it/s]
 40%|███▉      | 842/2129 [00:43<00:51, 24.84it/s]
 40%|███▉      | 845/2129 [00:44<01:12, 17.60it/s]
 40%|███▉      | 848/2129 [00:44<01:51, 11.48it/s]
 40%|███▉      | 850/2129 [00:44<01:44, 12.22it/s]
 40%|████      | 857/2129 [00:45<01:02, 20.43it/s]
 40%|████      | 861/2129 [00:45<01:37, 12.94it/s]
 41%|████      | 864/2129 [00:45<01:25, 14.85it/s]
 41%|████      | 867/2129 [00:46<01:56, 10.83it/s]
 41%|████      | 873/2129 [00:46<01:30, 13.88it/s]
 41%|████      | 876/2129 [00:46<01:21, 15.32it/s]
 41%|████▏     | 882/2129 [00:46<00:57, 21.60it/s]
 42%|████▏     | 886/2129 [00:46<01:02, 19.90it/s]
 42%|████▏     | 889/2129 [00:47<00:58, 21.16it/s]
 42%|████▏     | 893/2129 [00:47<01:02, 19.63it/s]
 42%|████▏     | 896/2129 [00:47<01:24, 14.54it/s]
 42%|████▏     | 898/2129 [00:48<01:45, 11.70it/s]
 42%|████▏     | 901/2129 [00:48<01:29, 13.69it/s]
 42%|████▏     | 903/2129 [00:48<01:43, 11.85it/s]
 43%|████▎     | 906/2129 [00:48<01:55, 10.62it/s]
 43%|████▎     | 908/2129 [00:49<02:15,  9.02it/s]
 43%|████▎     | 910/2129 [00:49<02:37,  7.72it/s]
 43%|████▎     | 911/2129 [00:49<02:51,  7.12it/s]
 43%|████▎     | 913/2129 [00:49<02:20,  8.64it/s]
 43%|████▎     | 915/2129 [00:50<02:19,  8.69it/s]
 43%|████▎     | 918/2129 [00:50<01:45, 11.44it/s]
 43%|████▎     | 920/2129 [00:50<01:53, 10.66it/s]
 43%|████▎     | 922/2129 [00:50<01:39, 12.18it/s]
 43%|████▎     | 924/2129 [00:50<01:30, 13.29it/s]
 43%|████▎     | 926/2129 [00:50<01:25, 14.15it/s]
 44%|████▎     | 928/2129 [00:50<01:36, 12.39it/s]
 44%|████▎     | 931/2129 [00:51<01:28, 13.59it/s]
 44%|████▍     | 935/2129 [00:51<01:09, 17.29it/s]
 44%|████▍     | 937/2129 [00:51<01:41, 11.79it/s]
 44%|████▍     | 939/2129 [00:52<02:16,  8.70it/s]
 44%|████▍     | 942/2129 [00:52<01:43, 11.44it/s]
 44%|████▍     | 944/2129 [00:52<01:45, 11.22it/s]
 44%|████▍     | 946/2129 [00:52<01:55, 10.21it/s]
 45%|████▍     | 950/2129 [00:52<01:42, 11.52it/s]
 45%|████▍     | 953/2129 [00:52<01:23, 14.10it/s]
 45%|████▍     | 955/2129 [00:53<01:30, 12.97it/s]
 45%|████▍     | 957/2129 [00:53<01:28, 13.17it/s]
 45%|████▌     | 959/2129 [00:53<01:52, 10.42it/s]
 45%|████▌     | 961/2129 [00:53<02:13,  8.74it/s]
 45%|████▌     | 963/2129 [00:54<01:57,  9.93it/s]
 45%|████▌     | 967/2129 [00:54<01:24, 13.80it/s]
 46%|████▌     | 969/2129 [00:54<01:24, 13.72it/s]
 46%|████▌     | 971/2129 [00:54<01:35, 12.08it/s]
 46%|████▌     | 973/2129 [00:54<01:36, 11.97it/s]
 46%|████▌     | 975/2129 [00:54<01:42, 11.30it/s]
 46%|████▌     | 977/2129 [00:55<01:29, 12.89it/s]
 46%|████▌     | 979/2129 [00:55<01:56,  9.86it/s]
 46%|████▌     | 981/2129 [00:55<01:55,  9.95it/s]
 46%|████▌     | 983/2129 [00:55<02:15,  8.48it/s]
 46%|████▋     | 985/2129 [00:55<01:55,  9.89it/s]
 46%|████▋     | 988/2129 [00:56<01:34, 12.06it/s]
 47%|████▋     | 990/2129 [00:56<01:25, 13.33it/s]
 47%|████▋     | 993/2129 [00:56<01:20, 14.06it/s]
 47%|████▋     | 995/2129 [00:56<01:15, 15.02it/s]
 47%|████▋     | 998/2129 [00:56<01:37, 11.63it/s]
 47%|████▋     | 1000/2129 [00:57<01:29, 12.61it/s]
 47%|████▋     | 1002/2129 [00:57<01:24, 13.37it/s]
 47%|████▋     | 1004/2129 [00:57<01:17, 14.56it/s]
 47%|████▋     | 1007/2129 [00:57<01:05, 17.15it/s]
 47%|████▋     | 1010/2129 [00:57<01:12, 15.35it/s]
 48%|████▊     | 1012/2129 [00:57<01:11, 15.55it/s]
 48%|████▊     | 1014/2129 [00:57<01:27, 12.67it/s]
 48%|████▊     | 1016/2129 [00:58<01:41, 10.94it/s]
 48%|████▊     | 1018/2129 [00:58<01:52,  9.89it/s]
 48%|████▊     | 1020/2129 [00:58<02:04,  8.94it/s]
 48%|████▊     | 1023/2129 [00:59<01:51,  9.92it/s]
 48%|████▊     | 1025/2129 [00:59<02:00,  9.16it/s]
 48%|████▊     | 1028/2129 [00:59<01:51,  9.87it/s]
 48%|████▊     | 1030/2129 [00:59<01:54,  9.57it/s]
 49%|████▊     | 1033/2129 [00:59<01:31, 12.02it/s]
 49%|████▊     | 1036/2129 [01:00<01:37, 11.17it/s]
 49%|████▉     | 1038/2129 [01:00<01:32, 11.78it/s]
 49%|████▉     | 1044/2129 [01:00<00:54, 19.94it/s]
 49%|████▉     | 1048/2129 [01:00<00:56, 18.98it/s]
 49%|████▉     | 1051/2129 [01:01<01:11, 15.17it/s]
 49%|████▉     | 1053/2129 [01:01<01:08, 15.74it/s]
 50%|████▉     | 1055/2129 [01:01<01:25, 12.56it/s]
 50%|████▉     | 1057/2129 [01:01<01:35, 11.24it/s]
 50%|████▉     | 1059/2129 [01:01<01:26, 12.42it/s]
 50%|████▉     | 1061/2129 [01:01<01:22, 12.95it/s]
 50%|████▉     | 1063/2129 [01:01<01:15, 14.18it/s]
 50%|█████     | 1065/2129 [01:02<01:23, 12.68it/s]
 50%|█████     | 1068/2129 [01:02<01:05, 16.19it/s]
 50%|█████     | 1071/2129 [01:02<01:16, 13.82it/s]
 50%|█████     | 1075/2129 [01:02<00:57, 18.18it/s]
 51%|█████     | 1078/2129 [01:02<01:14, 14.15it/s]
 51%|█████     | 1080/2129 [01:03<01:26, 12.07it/s]
 51%|█████     | 1083/2129 [01:03<01:10, 14.85it/s]
 51%|█████     | 1085/2129 [01:03<01:20, 13.02it/s]
 51%|█████     | 1087/2129 [01:03<01:14, 13.96it/s]
 51%|█████▏    | 1093/2129 [01:03<00:45, 22.67it/s]
 51%|█████▏    | 1096/2129 [01:04<00:58, 17.58it/s]
 52%|█████▏    | 1100/2129 [01:04<01:10, 14.51it/s]
 52%|█████▏    | 1102/2129 [01:04<01:31, 11.24it/s]
 52%|█████▏    | 1104/2129 [01:05<01:39, 10.29it/s]
 52%|█████▏    | 1106/2129 [01:05<02:21,  7.23it/s]
 52%|█████▏    | 1108/2129 [01:05<02:20,  7.28it/s]
 52%|█████▏    | 1112/2129 [01:06<01:50,  9.23it/s]
 52%|█████▏    | 1114/2129 [01:06<01:55,  8.77it/s]
 52%|█████▏    | 1115/2129 [01:06<02:24,  7.00it/s]
 53%|█████▎    | 1118/2129 [01:06<02:01,  8.33it/s]
 53%|█████▎    | 1120/2129 [01:07<02:02,  8.21it/s]
 53%|█████▎    | 1122/2129 [01:07<01:45,  9.57it/s]
 53%|█████▎    | 1127/2129 [01:07<01:19, 12.57it/s]
 53%|█████▎    | 1129/2129 [01:07<01:47,  9.31it/s]
 53%|█████▎    | 1132/2129 [01:08<01:43,  9.63it/s]
 53%|█████▎    | 1135/2129 [01:08<01:40,  9.92it/s]
 53%|█████▎    | 1138/2129 [01:08<01:22, 12.00it/s]
 54%|█████▎    | 1140/2129 [01:08<01:28, 11.18it/s]
 54%|█████▎    | 1142/2129 [01:09<01:35, 10.36it/s]
 54%|█████▎    | 1144/2129 [01:09<01:28, 11.15it/s]
 54%|█████▍    | 1146/2129 [01:09<01:28, 11.09it/s]
 54%|█████▍    | 1149/2129 [01:09<01:12, 13.60it/s]
 54%|█████▍    | 1152/2129 [01:09<01:19, 12.34it/s]
 54%|█████▍    | 1154/2129 [01:10<01:32, 10.58it/s]
 54%|█████▍    | 1156/2129 [01:10<01:59,  8.13it/s]
 54%|█████▍    | 1159/2129 [01:10<01:30, 10.73it/s]
 55%|█████▍    | 1163/2129 [01:11<01:25, 11.31it/s]
 55%|█████▍    | 1165/2129 [01:11<01:34, 10.25it/s]
 55%|█████▍    | 1167/2129 [01:11<01:38,  9.75it/s]
 55%|█████▍    | 1169/2129 [01:11<01:25, 11.22it/s]
 55%|█████▌    | 1171/2129 [01:11<01:33, 10.29it/s]
 55%|█████▌    | 1174/2129 [01:12<01:31, 10.49it/s]
 55%|█████▌    | 1177/2129 [01:12<01:12, 13.11it/s]
 55%|█████▌    | 1179/2129 [01:12<01:35,  9.98it/s]
 55%|█████▌    | 1181/2129 [01:12<01:42,  9.28it/s]
 56%|█████▌    | 1183/2129 [01:13<01:45,  8.92it/s]
 56%|█████▌    | 1185/2129 [01:13<01:53,  8.29it/s]
 56%|█████▌    | 1186/2129 [01:13<02:06,  7.47it/s]
 56%|█████▌    | 1189/2129 [01:13<01:30, 10.40it/s]
 56%|█████▌    | 1191/2129 [01:13<01:34,  9.91it/s]
 56%|█████▌    | 1194/2129 [01:14<01:28, 10.62it/s]
 56%|█████▌    | 1196/2129 [01:14<01:54,  8.16it/s]
 56%|█████▋    | 1199/2129 [01:14<01:27, 10.69it/s]
 57%|█████▋    | 1203/2129 [01:14<01:13, 12.55it/s]
 57%|█████▋    | 1205/2129 [01:15<01:32,  9.94it/s]
 57%|█████▋    | 1207/2129 [01:15<01:37,  9.48it/s]
 57%|█████▋    | 1210/2129 [01:15<01:14, 12.31it/s]
 57%|█████▋    | 1212/2129 [01:16<01:39,  9.21it/s]
 57%|█████▋    | 1214/2129 [01:16<01:43,  8.88it/s]
 57%|█████▋    | 1217/2129 [01:16<01:17, 11.83it/s]
 57%|█████▋    | 1219/2129 [01:16<01:21, 11.11it/s]
 57%|█████▋    | 1221/2129 [01:16<01:30, 10.04it/s]
 57%|█████▋    | 1224/2129 [01:17<01:25, 10.53it/s]
 58%|█████▊    | 1227/2129 [01:17<01:28, 10.20it/s]
 58%|█████▊    | 1229/2129 [01:17<01:22, 10.89it/s]
 58%|█████▊    | 1231/2129 [01:17<01:26, 10.39it/s]
 58%|█████▊    | 1233/2129 [01:18<01:42,  8.75it/s]
 58%|█████▊    | 1236/2129 [01:18<01:19, 11.29it/s]
 58%|█████▊    | 1238/2129 [01:18<01:31,  9.78it/s]
 58%|█████▊    | 1243/2129 [01:18<00:56, 15.76it/s]
 59%|█████▊    | 1246/2129 [01:18<01:05, 13.56it/s]
 59%|█████▊    | 1248/2129 [01:19<01:01, 14.27it/s]
 59%|█████▊    | 1250/2129 [01:19<00:57, 15.21it/s]
 59%|█████▉    | 1253/2129 [01:19<00:55, 15.74it/s]
 59%|█████▉    | 1256/2129 [01:19<00:59, 14.68it/s]
 59%|█████▉    | 1258/2129 [01:19<01:16, 11.43it/s]
 59%|█████▉    | 1260/2129 [01:20<01:17, 11.20it/s]
 59%|█████▉    | 1262/2129 [01:20<01:21, 10.60it/s]
 59%|█████▉    | 1266/2129 [01:20<00:56, 15.29it/s]
 60%|█████▉    | 1269/2129 [01:20<01:06, 12.89it/s]
 60%|█████▉    | 1271/2129 [01:21<01:36,  8.86it/s]
 60%|█████▉    | 1274/2129 [01:21<01:34,  9.04it/s]
 60%|█████▉    | 1276/2129 [01:21<01:33,  9.17it/s]
 60%|██████    | 1279/2129 [01:21<01:27,  9.70it/s]
 60%|██████    | 1281/2129 [01:22<01:31,  9.22it/s]
 60%|██████    | 1283/2129 [01:22<01:31,  9.22it/s]
 60%|██████    | 1286/2129 [01:22<01:26,  9.73it/s]
 60%|██████    | 1288/2129 [01:22<01:16, 10.94it/s]
 61%|██████    | 1290/2129 [01:23<01:49,  7.69it/s]
 61%|██████    | 1291/2129 [01:23<02:09,  6.45it/s]
 61%|██████    | 1292/2129 [01:23<02:18,  6.03it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 335.66it/s]

[[np.int64(0), False, 12], [np.int64(1), False, 10], [np.int64(2), False, 7], [np.int64(3), False, 4], [np.int64(5), False, 13], [np.int64(6), False, 2], [np.int64(8), False, 1], [np.int64(9), False, 1], [np.int64(10), False, 12], [np.int64(11), False, 7], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0398, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [07:07<2:21:27, 56.96s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [07:07<1:38:27, 39.91s/it]

tensor(12.3546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1850, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3750, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3726, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [07:08<47:44, 19.62s/it]

tensor(12.4058, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4228, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4236, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4742, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [07:08<23:13,  9.68s/it]

tensor(12.4198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5319, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6455, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [07:08<07:59,  3.40s/it]

tensor(12.3787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7386, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8091, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [07:08<04:00,  1.73s/it]

tensor(12.3534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3432, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8926, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [07:09<02:04,  1.10it/s]

tensor(12.3386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9349, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9784, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [07:09<01:08,  1.97it/s]

tensor(12.3382, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0091, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3329, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0744, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [07:09<00:41,  3.22it/s]

tensor(12.3256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1214, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1507, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [07:09<00:33,  3.92it/s]

tensor(12.3068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1787, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2045, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [07:10<00:21,  5.97it/s]

tensor(12.2797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2250, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2446, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [07:10<00:18,  6.97it/s]

tensor(12.2514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2558, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2710, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [07:10<00:16,  7.58it/s]

tensor(12.2392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2791, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2829, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [07:10<00:16,  7.75it/s]

tensor(12.2296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2890, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2941, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [07:11<00:15,  8.06it/s]

tensor(12.1980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2894, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2923, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [07:11<00:14,  8.14it/s]

tensor(12.1789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2962, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2957, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [07:11<00:14,  8.17it/s]

tensor(12.1661, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2932, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2998, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [07:11<00:14,  8.19it/s]

tensor(12.1526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3030, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3019, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [07:11<00:13,  8.19it/s]

tensor(12.1406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3053, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3087, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [07:12<00:13,  8.21it/s]

tensor(12.1287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3251, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [07:12<00:13,  8.22it/s]

tensor(12.1189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3302, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3389, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [07:12<00:13,  8.21it/s]

tensor(12.1090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3448, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3474, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [07:12<00:12,  8.20it/s]

tensor(12.0998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3527, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0949, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3551, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [07:13<00:12,  8.18it/s]

tensor(12.0902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3587, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [07:13<00:12,  8.20it/s]

tensor(12.0812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3614, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3602, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [07:13<00:12,  8.20it/s]

tensor(12.0723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3608, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([226, 128,  89, 209,  97, 101,  67, 134, 198, 204, 316, 104, 161,  95])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<02:16, 15.53it/s]
  0%|          | 5/2129 [00:00<01:51, 19.00it/s]
  1%|          | 12/2129 [00:00<00:57, 36.68it/s]
  1%|          | 16/2129 [00:00<01:12, 29.26it/s]
  1%|          | 21/2129 [00:00<01:04, 32.89it/s]
  1%|▏         | 27/2129 [00:00<00:53, 38.98it/s]
  2%|▏         | 32/2129 [00:00<00:57, 36.30it/s]
  2%|▏         | 39/2129 [00:01<00:46, 44.73it/s]
  2%|▏         | 46/2129 [00:01<00:44, 47.28it/s]
  2%|▏         | 51/2129 [00:01<00:46, 44.29it/s]
  3%|▎         | 58/2129 [00:01<00:41, 49.98it/s]
  3%|▎         | 65/2129 [00:01<00:38, 54.22it/s]
  3%|▎         | 71/2129 [00:01<00:39, 51.81it/s]
  4%|▎         | 78/2129 [00:01<00:39, 51.52it/s]
  4%|▍         | 84/2129 [00:02<01:06, 30.80it/s]
  4%|▍         | 89/2129 [00:02<01:03, 32.12it/s]
  4%|▍         | 93/2129 [00:02<01:02, 32.80it/s]
  5%|▍         | 97/2129 [00:02<01:10, 28.71it/s]
  5%|▍         | 102/2129 [00:02<01:02, 32.49it/s]
  5%|▍         | 106/2129 [00:03<01:48, 18.65it/s]
  5%|▌         | 111/2129 [00:03<01:27, 23.07it/s]
  5%|▌         | 116/2129 [00:03<01:14, 26.93it/s]
  6%|▌         | 121/2129 [00:03<01:05, 30.75it/s]
  6%|▌         | 125/2129 [00:03<01:16, 26.17it/s]
  6%|▌         | 130/2129 [00:03<01:07, 29.73it/s]
  6%|▋         | 134/2129 [00:04<01:26, 23.07it/s]
  6%|▋         | 138/2129 [00:04<01:17, 25.71it/s]
  7%|▋         | 144/2129 [00:04<01:01, 32.53it/s]
  7%|▋         | 149/2129 [00:04<00:54, 36.25it/s]
  7%|▋         | 154/2129 [00:04<00:50, 39.20it/s]
  7%|▋         | 159/2129 [00:05<01:31, 21.56it/s]
  8%|▊         | 163/2129 [00:05<01:33, 20.95it/s]
  8%|▊         | 166/2129 [00:05<01:45, 18.69it/s]
  8%|▊         | 169/2129 [00:05<01:39, 19.61it/s]
  8%|▊         | 175/2129 [00:05<01:12, 26.85it/s]
  8%|▊         | 179/2129 [00:06<01:32, 21.10it/s]
  9%|▊         | 182/2129 [00:06<01:27, 22.28it/s]
  9%|▊         | 185/2129 [00:06<01:50, 17.52it/s]
  9%|▉         | 188/2129 [00:06<02:13, 14.53it/s]
  9%|▉         | 190/2129 [00:06<02:37, 12.32it/s]
  9%|▉         | 193/2129 [00:07<02:14, 14.41it/s]
  9%|▉         | 200/2129 [00:07<01:47, 18.03it/s]
  9%|▉         | 202/2129 [00:07<01:56, 16.54it/s]
 10%|▉         | 208/2129 [00:07<01:21, 23.59it/s]
 10%|▉         | 212/2129 [00:07<01:32, 20.68it/s]
 10%|█         | 215/2129 [00:08<01:57, 16.34it/s]
 10%|█         | 218/2129 [00:08<01:43, 18.43it/s]
 10%|█         | 223/2129 [00:08<01:42, 18.56it/s]
 11%|█         | 226/2129 [00:08<01:37, 19.45it/s]
 11%|█         | 234/2129 [00:08<01:20, 23.46it/s]
 11%|█         | 237/2129 [00:09<01:21, 23.23it/s]
 11%|█▏        | 240/2129 [00:09<01:42, 18.36it/s]
 12%|█▏        | 245/2129 [00:09<01:20, 23.48it/s]
 12%|█▏        | 248/2129 [00:09<01:41, 18.50it/s]
 12%|█▏        | 252/2129 [00:10<01:52, 16.68it/s]
 12%|█▏        | 255/2129 [00:10<01:43, 18.11it/s]
 12%|█▏        | 258/2129 [00:10<01:55, 16.17it/s]
 12%|█▏        | 260/2129 [00:10<01:52, 16.60it/s]
 12%|█▏        | 266/2129 [00:10<01:16, 24.29it/s]
 13%|█▎        | 269/2129 [00:10<01:42, 18.21it/s]
 13%|█▎        | 272/2129 [00:11<01:35, 19.49it/s]
 13%|█▎        | 275/2129 [00:11<01:40, 18.42it/s]
 13%|█▎        | 280/2129 [00:11<01:16, 24.29it/s]
 13%|█▎        | 285/2129 [00:11<01:02, 29.30it/s]
 14%|█▎        | 289/2129 [00:11<01:23, 22.08it/s]
 14%|█▎        | 292/2129 [00:11<01:35, 19.16it/s]
 14%|█▍        | 295/2129 [00:12<02:00, 15.25it/s]
 14%|█▍        | 297/2129 [00:12<01:54, 15.93it/s]
 14%|█▍        | 299/2129 [00:12<01:57, 15.60it/s]
 14%|█▍        | 304/2129 [00:12<01:33, 19.46it/s]
 14%|█▍        | 307/2129 [00:12<01:49, 16.59it/s]
 15%|█▍        | 312/2129 [00:13<01:49, 16.64it/s]
 15%|█▍        | 314/2129 [00:13<02:21, 12.79it/s]
 15%|█▍        | 316/2129 [00:13<02:15, 13.43it/s]
 15%|█▍        | 319/2129 [00:13<01:58, 15.32it/s]
 15%|█▌        | 324/2129 [00:14<01:54, 15.83it/s]
 15%|█▌        | 327/2129 [00:14<01:45, 17.13it/s]
 15%|█▌        | 329/2129 [00:14<02:05, 14.31it/s]
 16%|█▌        | 331/2129 [00:14<02:56, 10.21it/s]
 16%|█▌        | 334/2129 [00:15<02:57, 10.09it/s]
 16%|█▌        | 337/2129 [00:15<02:59,  9.97it/s]
 16%|█▌        | 339/2129 [00:15<02:39, 11.25it/s]
 16%|█▌        | 343/2129 [00:15<02:18, 12.87it/s]
 16%|█▌        | 345/2129 [00:15<02:08, 13.93it/s]
 16%|█▋        | 350/2129 [00:16<01:51, 15.89it/s]
 17%|█▋        | 353/2129 [00:16<01:47, 16.50it/s]
 17%|█▋        | 355/2129 [00:16<02:35, 11.38it/s]
 17%|█▋        | 357/2129 [00:17<03:10,  9.31it/s]
 17%|█▋        | 359/2129 [00:17<03:02,  9.70it/s]
 17%|█▋        | 361/2129 [00:17<02:39, 11.06it/s]
 17%|█▋        | 363/2129 [00:17<02:40, 11.01it/s]
 17%|█▋        | 365/2129 [00:17<02:26, 12.03it/s]
 17%|█▋        | 367/2129 [00:17<02:11, 13.39it/s]
 17%|█▋        | 369/2129 [00:17<01:58, 14.79it/s]
 18%|█▊        | 373/2129 [00:18<01:55, 15.25it/s]
 18%|█▊        | 375/2129 [00:18<01:48, 16.12it/s]
 18%|█▊        | 377/2129 [00:18<02:23, 12.17it/s]
 18%|█▊        | 379/2129 [00:18<02:14, 13.02it/s]
 18%|█▊        | 381/2129 [00:18<02:38, 11.06it/s]
 18%|█▊        | 384/2129 [00:19<02:36, 11.13it/s]
 18%|█▊        | 386/2129 [00:19<02:53, 10.03it/s]
 18%|█▊        | 388/2129 [00:19<02:30, 11.56it/s]
 18%|█▊        | 391/2129 [00:19<02:05, 13.82it/s]
 19%|█▊        | 394/2129 [00:19<01:53, 15.26it/s]
 19%|█▊        | 398/2129 [00:20<01:34, 18.28it/s]
 19%|█▉        | 400/2129 [00:20<01:56, 14.89it/s]
 19%|█▉        | 402/2129 [00:20<01:50, 15.58it/s]
 19%|█▉        | 407/2129 [00:20<01:19, 21.68it/s]
 19%|█▉        | 410/2129 [00:20<01:44, 16.41it/s]
 19%|█▉        | 412/2129 [00:20<01:40, 17.04it/s]
 20%|█▉        | 417/2129 [00:20<01:12, 23.68it/s]
 20%|█▉        | 424/2129 [00:21<00:51, 33.22it/s]
 20%|██        | 430/2129 [00:21<00:58, 28.95it/s]
 20%|██        | 434/2129 [00:21<01:32, 18.33it/s]
 21%|██        | 437/2129 [00:22<01:44, 16.24it/s]
 21%|██        | 441/2129 [00:22<01:27, 19.18it/s]
 21%|██        | 446/2129 [00:22<01:12, 23.23it/s]
 21%|██        | 451/2129 [00:22<01:00, 27.76it/s]
 21%|██▏       | 455/2129 [00:22<00:56, 29.58it/s]
 22%|██▏       | 459/2129 [00:22<01:32, 18.09it/s]
 22%|██▏       | 462/2129 [00:23<01:34, 17.68it/s]
 22%|██▏       | 465/2129 [00:23<01:28, 18.77it/s]
 22%|██▏       | 468/2129 [00:23<02:12, 12.54it/s]
 22%|██▏       | 471/2129 [00:24<02:18, 11.99it/s]
 22%|██▏       | 473/2129 [00:24<02:10, 12.74it/s]
 22%|██▏       | 477/2129 [00:24<02:00, 13.68it/s]
 22%|██▏       | 479/2129 [00:24<02:14, 12.28it/s]
 23%|██▎       | 481/2129 [00:24<02:07, 12.94it/s]
 23%|██▎       | 483/2129 [00:25<02:42, 10.11it/s]
 23%|██▎       | 485/2129 [00:25<02:56,  9.29it/s]
 23%|██▎       | 487/2129 [00:25<02:35, 10.56it/s]
 23%|██▎       | 489/2129 [00:25<02:15, 12.06it/s]
 23%|██▎       | 493/2129 [00:25<01:35, 17.21it/s]
 23%|██▎       | 496/2129 [00:25<01:23, 19.55it/s]
 24%|██▎       | 504/2129 [00:25<00:49, 32.68it/s]
 24%|██▍       | 509/2129 [00:26<00:59, 27.43it/s]
 24%|██▍       | 513/2129 [00:26<01:00, 26.51it/s]
 24%|██▍       | 517/2129 [00:26<01:40, 15.97it/s]
 24%|██▍       | 520/2129 [00:27<01:55, 13.98it/s]
 25%|██▍       | 522/2129 [00:27<02:14, 11.93it/s]
 25%|██▍       | 526/2129 [00:27<02:08, 12.43it/s]
 25%|██▍       | 528/2129 [00:27<02:20, 11.43it/s]
 25%|██▍       | 530/2129 [00:28<02:33, 10.43it/s]
 25%|██▍       | 532/2129 [00:28<02:16, 11.70it/s]
 25%|██▌       | 536/2129 [00:28<01:57, 13.55it/s]
 25%|██▌       | 539/2129 [00:28<01:39, 16.00it/s]
 26%|██▌       | 543/2129 [00:28<01:42, 15.43it/s]
 26%|██▌       | 546/2129 [00:28<01:31, 17.28it/s]
 26%|██▌       | 554/2129 [00:29<00:54, 28.67it/s]
 26%|██▋       | 559/2129 [00:29<01:03, 24.66it/s]
 26%|██▋       | 563/2129 [00:29<01:00, 25.77it/s]
 27%|██▋       | 567/2129 [00:30<01:39, 15.74it/s]
 27%|██▋       | 570/2129 [00:30<01:29, 17.40it/s]
 27%|██▋       | 573/2129 [00:30<01:45, 14.78it/s]
 27%|██▋       | 577/2129 [00:30<01:43, 14.99it/s]
 27%|██▋       | 579/2129 [00:30<01:47, 14.46it/s]
 27%|██▋       | 584/2129 [00:31<01:37, 15.77it/s]
 28%|██▊       | 586/2129 [00:31<01:52, 13.73it/s]
 28%|██▊       | 588/2129 [00:31<02:13, 11.54it/s]
 28%|██▊       | 590/2129 [00:32<02:54,  8.82it/s]
 28%|██▊       | 592/2129 [00:32<02:30, 10.24it/s]
 28%|██▊       | 594/2129 [00:32<02:41,  9.48it/s]
 28%|██▊       | 596/2129 [00:32<02:20, 10.90it/s]
 28%|██▊       | 599/2129 [00:32<02:15, 11.25it/s]
 28%|██▊       | 601/2129 [00:32<02:09, 11.82it/s]
 28%|██▊       | 603/2129 [00:33<02:39,  9.56it/s]
 28%|██▊       | 605/2129 [00:33<02:43,  9.30it/s]
 29%|██▊       | 607/2129 [00:33<02:19, 10.93it/s]
 29%|██▊       | 610/2129 [00:33<02:12, 11.44it/s]
 29%|██▉       | 613/2129 [00:33<01:47, 14.04it/s]
 29%|██▉       | 619/2129 [00:34<01:06, 22.60it/s]
 29%|██▉       | 626/2129 [00:34<01:04, 23.34it/s]
 30%|██▉       | 629/2129 [00:34<01:24, 17.65it/s]
 30%|██▉       | 633/2129 [00:34<01:13, 20.47it/s]
 30%|██▉       | 636/2129 [00:34<01:18, 19.03it/s]
 30%|███       | 640/2129 [00:35<01:07, 21.97it/s]
 30%|███       | 643/2129 [00:35<01:23, 17.89it/s]
 30%|███       | 646/2129 [00:35<01:41, 14.65it/s]
 30%|███       | 649/2129 [00:35<01:49, 13.51it/s]
 31%|███       | 651/2129 [00:35<01:42, 14.46it/s]
 31%|███       | 657/2129 [00:36<01:05, 22.48it/s]
 31%|███       | 660/2129 [00:36<01:23, 17.68it/s]
 31%|███       | 663/2129 [00:36<02:02, 11.99it/s]
 31%|███▏      | 666/2129 [00:36<01:43, 14.13it/s]
 31%|███▏      | 669/2129 [00:37<01:52, 12.95it/s]
 32%|███▏      | 672/2129 [00:37<01:54, 12.73it/s]
 32%|███▏      | 674/2129 [00:37<01:49, 13.28it/s]
 32%|███▏      | 677/2129 [00:37<01:48, 13.40it/s]
 32%|███▏      | 680/2129 [00:37<01:32, 15.62it/s]
 32%|███▏      | 684/2129 [00:38<01:29, 16.20it/s]
 32%|███▏      | 686/2129 [00:38<01:49, 13.20it/s]
 32%|███▏      | 688/2129 [00:38<02:06, 11.41it/s]
 32%|███▏      | 690/2129 [00:38<02:27,  9.75it/s]
 33%|███▎      | 694/2129 [00:39<02:08, 11.17it/s]
 33%|███▎      | 696/2129 [00:39<02:21, 10.14it/s]
 33%|███▎      | 699/2129 [00:39<01:53, 12.62it/s]
 33%|███▎      | 704/2129 [00:39<01:17, 18.45it/s]
 33%|███▎      | 707/2129 [00:40<01:54, 12.39it/s]
 33%|███▎      | 709/2129 [00:40<02:10, 10.84it/s]
 33%|███▎      | 712/2129 [00:40<02:08, 11.03it/s]
 34%|███▎      | 714/2129 [00:40<02:17, 10.30it/s]
 34%|███▎      | 717/2129 [00:41<01:49, 12.84it/s]
 34%|███▍      | 721/2129 [00:41<01:42, 13.68it/s]
 34%|███▍      | 723/2129 [00:41<01:57, 11.96it/s]
 34%|███▍      | 725/2129 [00:41<02:15, 10.34it/s]
 34%|███▍      | 727/2129 [00:41<01:59, 11.73it/s]
 34%|███▍      | 729/2129 [00:42<01:51, 12.58it/s]
 34%|███▍      | 733/2129 [00:42<01:42, 13.64it/s]
 35%|███▍      | 736/2129 [00:42<01:25, 16.28it/s]
 35%|███▍      | 739/2129 [00:42<01:40, 13.79it/s]
 35%|███▍      | 743/2129 [00:42<01:18, 17.63it/s]
 35%|███▌      | 750/2129 [00:43<00:53, 25.61it/s]
 35%|███▌      | 753/2129 [00:43<01:30, 15.16it/s]
 36%|███▌      | 756/2129 [00:44<02:04, 11.03it/s]
 36%|███▌      | 758/2129 [00:44<01:56, 11.77it/s]
 36%|███▌      | 761/2129 [00:44<01:37, 14.00it/s]
 36%|███▌      | 764/2129 [00:44<02:20,  9.73it/s]
 36%|███▌      | 766/2129 [00:45<02:31,  8.99it/s]
 36%|███▌      | 769/2129 [00:45<02:28,  9.13it/s]
 36%|███▌      | 771/2129 [00:45<02:11, 10.30it/s]
 36%|███▋      | 775/2129 [00:45<02:01, 11.15it/s]
 36%|███▋      | 777/2129 [00:45<01:57, 11.48it/s]
 37%|███▋      | 779/2129 [00:46<01:47, 12.61it/s]
 37%|███▋      | 781/2129 [00:46<01:52, 12.00it/s]
 37%|███▋      | 784/2129 [00:46<01:38, 13.71it/s]
 37%|███▋      | 786/2129 [00:46<02:10, 10.27it/s]
 37%|███▋      | 788/2129 [00:47<02:26,  9.16it/s]
 37%|███▋      | 791/2129 [00:47<01:50, 12.11it/s]
 37%|███▋      | 796/2129 [00:47<01:30, 14.77it/s]
 37%|███▋      | 798/2129 [00:47<01:46, 12.55it/s]
 38%|███▊      | 800/2129 [00:47<02:05, 10.60it/s]
 38%|███▊      | 802/2129 [00:48<02:24,  9.20it/s]
 38%|███▊      | 804/2129 [00:48<02:05, 10.57it/s]
 38%|███▊      | 810/2129 [00:48<01:32, 14.24it/s]
 38%|███▊      | 812/2129 [00:48<01:28, 14.86it/s]
 38%|███▊      | 815/2129 [00:48<01:16, 17.25it/s]
 39%|███▊      | 821/2129 [00:48<00:51, 25.23it/s]
 39%|███▉      | 828/2129 [00:49<00:37, 34.78it/s]
 39%|███▉      | 833/2129 [00:49<00:34, 37.70it/s]
 39%|███▉      | 838/2129 [00:49<00:46, 27.48it/s]
 40%|███▉      | 842/2129 [00:49<00:45, 28.06it/s]
 40%|███▉      | 846/2129 [00:50<01:15, 16.95it/s]
 40%|███▉      | 849/2129 [00:50<01:15, 16.91it/s]
 40%|████      | 852/2129 [00:50<01:36, 13.22it/s]
 40%|████      | 854/2129 [00:50<01:45, 12.14it/s]
 40%|████      | 856/2129 [00:50<01:37, 13.00it/s]
 40%|████      | 858/2129 [00:51<01:30, 14.06it/s]
 40%|████      | 860/2129 [00:51<01:54, 11.06it/s]
 40%|████      | 862/2129 [00:51<01:43, 12.30it/s]
 41%|████      | 865/2129 [00:51<02:00, 10.51it/s]
 41%|████      | 867/2129 [00:51<01:46, 11.85it/s]
 41%|████      | 873/2129 [00:52<01:02, 20.08it/s]
 41%|████▏     | 879/2129 [00:52<00:45, 27.43it/s]
 42%|████▏     | 884/2129 [00:52<00:39, 31.86it/s]
 42%|████▏     | 888/2129 [00:52<00:51, 24.09it/s]
 42%|████▏     | 892/2129 [00:52<01:02, 19.77it/s]
 42%|████▏     | 895/2129 [00:52<01:00, 20.54it/s]
 42%|████▏     | 898/2129 [00:53<01:07, 18.21it/s]
 42%|████▏     | 901/2129 [00:53<01:05, 18.82it/s]
 42%|████▏     | 904/2129 [00:53<01:32, 13.28it/s]
 43%|████▎     | 906/2129 [00:53<01:30, 13.45it/s]
 43%|████▎     | 908/2129 [00:54<01:30, 13.47it/s]
 43%|████▎     | 910/2129 [00:54<01:23, 14.51it/s]
 43%|████▎     | 912/2129 [00:54<01:36, 12.67it/s]
 43%|████▎     | 914/2129 [00:54<01:51, 10.91it/s]
 43%|████▎     | 917/2129 [00:54<01:28, 13.68it/s]
 43%|████▎     | 920/2129 [00:54<01:14, 16.21it/s]
 43%|████▎     | 924/2129 [00:54<00:56, 21.16it/s]
 44%|████▎     | 927/2129 [00:55<00:56, 21.36it/s]
 44%|████▎     | 930/2129 [00:55<01:08, 17.55it/s]
 44%|████▍     | 933/2129 [00:55<01:09, 17.33it/s]
 44%|████▍     | 936/2129 [00:55<01:05, 18.20it/s]
 44%|████▍     | 938/2129 [00:55<01:08, 17.30it/s]
 44%|████▍     | 940/2129 [00:56<01:33, 12.72it/s]
 44%|████▍     | 942/2129 [00:56<01:26, 13.75it/s]
 44%|████▍     | 944/2129 [00:56<01:35, 12.40it/s]
 44%|████▍     | 946/2129 [00:56<01:30, 13.07it/s]
 45%|████▍     | 950/2129 [00:56<01:23, 14.15it/s]
 45%|████▍     | 952/2129 [00:56<01:18, 15.06it/s]
 45%|████▍     | 954/2129 [00:57<01:14, 15.87it/s]
 45%|████▍     | 958/2129 [00:57<01:17, 15.09it/s]
 45%|████▌     | 960/2129 [00:57<01:34, 12.32it/s]
 45%|████▌     | 962/2129 [00:57<01:49, 10.69it/s]
 45%|████▌     | 964/2129 [00:58<02:04,  9.35it/s]
 45%|████▌     | 968/2129 [00:58<01:45, 11.04it/s]
 46%|████▌     | 970/2129 [00:58<01:38, 11.75it/s]
 46%|████▌     | 973/2129 [00:58<01:33, 12.34it/s]
 46%|████▌     | 975/2129 [00:58<01:43, 11.20it/s]
 46%|████▌     | 978/2129 [00:59<01:22, 13.89it/s]
 46%|████▌     | 981/2129 [00:59<01:32, 12.45it/s]
 46%|████▌     | 984/2129 [00:59<01:16, 14.94it/s]
 46%|████▋     | 988/2129 [00:59<01:08, 16.78it/s]
 47%|████▋     | 991/2129 [00:59<01:02, 18.09it/s]
 47%|████▋     | 993/2129 [01:00<01:17, 14.61it/s]
 47%|████▋     | 996/2129 [01:00<01:05, 17.40it/s]
 47%|████▋     | 1000/2129 [01:00<00:52, 21.60it/s]
 47%|████▋     | 1003/2129 [01:00<01:04, 17.44it/s]
 47%|████▋     | 1006/2129 [01:00<00:56, 19.83it/s]
 48%|████▊     | 1012/2129 [01:00<00:42, 26.01it/s]
 48%|████▊     | 1015/2129 [01:01<01:19, 14.03it/s]
 48%|████▊     | 1018/2129 [01:01<01:32, 12.07it/s]
 48%|████▊     | 1020/2129 [01:01<01:33, 11.89it/s]
 48%|████▊     | 1022/2129 [01:01<01:25, 12.89it/s]
 48%|████▊     | 1024/2129 [01:02<01:44, 10.62it/s]
 48%|████▊     | 1027/2129 [01:02<01:22, 13.33it/s]
 48%|████▊     | 1029/2129 [01:02<01:31, 12.08it/s]
 48%|████▊     | 1031/2129 [01:02<01:26, 12.70it/s]
 49%|████▊     | 1033/2129 [01:02<01:24, 13.00it/s]
 49%|████▉     | 1040/2129 [01:02<00:46, 23.66it/s]
 49%|████▉     | 1043/2129 [01:03<00:52, 20.75it/s]
 49%|████▉     | 1046/2129 [01:03<00:49, 21.76it/s]
 49%|████▉     | 1049/2129 [01:03<01:10, 15.33it/s]
 50%|████▉     | 1054/2129 [01:03<00:51, 21.05it/s]
 50%|████▉     | 1057/2129 [01:04<01:19, 13.51it/s]
 50%|████▉     | 1060/2129 [01:04<01:31, 11.66it/s]
 50%|████▉     | 1062/2129 [01:04<01:30, 11.84it/s]
 50%|█████     | 1066/2129 [01:04<01:06, 15.87it/s]
 50%|█████     | 1070/2129 [01:05<01:06, 15.82it/s]
 50%|█████     | 1073/2129 [01:05<01:15, 14.04it/s]
 51%|█████     | 1077/2129 [01:05<01:14, 14.06it/s]
 51%|█████     | 1079/2129 [01:05<01:10, 14.83it/s]
 51%|█████     | 1085/2129 [01:05<01:02, 16.64it/s]
 51%|█████     | 1088/2129 [01:06<00:58, 17.92it/s]
 51%|█████▏    | 1094/2129 [01:06<00:42, 24.60it/s]
 52%|█████▏    | 1098/2129 [01:06<00:39, 26.35it/s]
 52%|█████▏    | 1103/2129 [01:06<00:45, 22.79it/s]
 52%|█████▏    | 1106/2129 [01:06<00:56, 18.19it/s]
 52%|█████▏    | 1109/2129 [01:07<01:05, 15.57it/s]
 52%|█████▏    | 1111/2129 [01:07<01:19, 12.87it/s]
 52%|█████▏    | 1113/2129 [01:07<01:47,  9.42it/s]
 52%|█████▏    | 1115/2129 [01:08<01:36, 10.55it/s]
 52%|█████▏    | 1117/2129 [01:08<01:48,  9.36it/s]
 53%|█████▎    | 1119/2129 [01:08<01:52,  9.01it/s]
 53%|█████▎    | 1121/2129 [01:08<01:57,  8.54it/s]
 53%|█████▎    | 1125/2129 [01:08<01:17, 12.90it/s]
 53%|█████▎    | 1131/2129 [01:09<01:06, 14.95it/s]
 53%|█████▎    | 1134/2129 [01:09<00:58, 17.12it/s]
 53%|█████▎    | 1137/2129 [01:09<01:08, 14.38it/s]
 53%|█████▎    | 1139/2129 [01:09<01:18, 12.60it/s]
 54%|█████▎    | 1141/2129 [01:09<01:12, 13.60it/s]
 54%|█████▍    | 1147/2129 [01:10<00:45, 21.46it/s]
 54%|█████▍    | 1152/2129 [01:10<00:45, 21.71it/s]
 54%|█████▍    | 1155/2129 [01:10<00:55, 17.51it/s]
 54%|█████▍    | 1158/2129 [01:10<00:59, 16.20it/s]
 54%|█████▍    | 1160/2129 [01:10<00:57, 16.81it/s]
 55%|█████▍    | 1163/2129 [01:11<00:50, 19.06it/s]
 55%|█████▍    | 1166/2129 [01:11<01:25, 11.25it/s]
 55%|█████▍    | 1168/2129 [01:11<01:17, 12.34it/s]
 55%|█████▌    | 1171/2129 [01:11<01:06, 14.36it/s]
 55%|█████▌    | 1173/2129 [01:11<01:03, 15.06it/s]
 55%|█████▌    | 1175/2129 [01:12<01:09, 13.69it/s]
 55%|█████▌    | 1177/2129 [01:12<01:06, 14.22it/s]
 55%|█████▌    | 1180/2129 [01:12<01:08, 13.85it/s]
 56%|█████▌    | 1182/2129 [01:12<01:14, 12.78it/s]
 56%|█████▌    | 1184/2129 [01:12<01:33, 10.08it/s]
 56%|█████▌    | 1186/2129 [01:13<01:20, 11.67it/s]
 56%|█████▌    | 1190/2129 [01:13<01:13, 12.75it/s]
 56%|█████▌    | 1192/2129 [01:13<01:09, 13.53it/s]
 56%|█████▌    | 1194/2129 [01:13<01:16, 12.23it/s]
 56%|█████▌    | 1196/2129 [01:14<01:49,  8.51it/s]
 56%|█████▋    | 1198/2129 [01:14<01:33,  9.93it/s]
 57%|█████▋    | 1205/2129 [01:14<00:51, 18.08it/s]
 57%|█████▋    | 1208/2129 [01:14<01:02, 14.71it/s]
 57%|█████▋    | 1211/2129 [01:14<01:09, 13.29it/s]
 57%|█████▋    | 1213/2129 [01:15<01:20, 11.43it/s]
 57%|█████▋    | 1215/2129 [01:15<01:13, 12.45it/s]
 57%|█████▋    | 1217/2129 [01:15<01:08, 13.39it/s]
 57%|█████▋    | 1219/2129 [01:15<01:20, 11.26it/s]
 57%|█████▋    | 1221/2129 [01:15<01:33,  9.67it/s]
 57%|█████▋    | 1223/2129 [01:16<01:37,  9.29it/s]
 58%|█████▊    | 1225/2129 [01:16<01:29, 10.15it/s]
 58%|█████▊    | 1227/2129 [01:16<01:25, 10.56it/s]
 58%|█████▊    | 1230/2129 [01:16<01:08, 13.17it/s]
 58%|█████▊    | 1232/2129 [01:17<01:26, 10.31it/s]
 58%|█████▊    | 1236/2129 [01:17<01:00, 14.88it/s]
 58%|█████▊    | 1243/2129 [01:17<00:35, 25.09it/s]
 59%|█████▊    | 1247/2129 [01:17<00:54, 16.08it/s]
 59%|█████▊    | 1250/2129 [01:17<00:51, 17.20it/s]
 59%|█████▉    | 1253/2129 [01:18<00:53, 16.33it/s]
 59%|█████▉    | 1256/2129 [01:18<01:04, 13.56it/s]
 59%|█████▉    | 1258/2129 [01:18<01:00, 14.30it/s]
 59%|█████▉    | 1260/2129 [01:18<01:07, 12.91it/s]
 59%|█████▉    | 1262/2129 [01:18<01:03, 13.59it/s]
 59%|█████▉    | 1265/2129 [01:18<00:52, 16.49it/s]
 60%|█████▉    | 1271/2129 [01:19<00:51, 16.77it/s]
 60%|█████▉    | 1274/2129 [01:19<00:46, 18.41it/s]
 60%|█████▉    | 1277/2129 [01:19<00:53, 15.89it/s]
 60%|██████    | 1282/2129 [01:19<00:40, 21.03it/s]
 60%|██████    | 1285/2129 [01:19<00:47, 17.81it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 307.60it/s]

[[np.int64(0), False, 10], [np.int64(1), False, 10], [np.int64(2), False, 11], [np.int64(3), False, 8], [np.int64(4), False, 12], [np.int64(5), False, 3], [np.int64(6), False, 2], [np.int64(7), False, 1], [np.int64(9), False, 0], [np.int64(12), False, 9], [np.int64(13), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2118, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [09:14<1:00:06, 36.43s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [09:14<41:43, 25.54s/it]

tensor(12.0739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3668, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4914, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:15<13:59,  8.84s/it]

tensor(12.1544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6902, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7465, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [09:15<09:45,  6.23s/it]

tensor(12.2346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7937, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2441, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7697, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:15<03:21,  2.22s/it]

tensor(12.2278, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7059, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7310, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:16<01:42,  1.15s/it]

tensor(12.1672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8038, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1492, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0094, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [09:16<01:14,  1.19it/s]

tensor(12.1404, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1566, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2210, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [09:16<00:40,  2.11it/s]

tensor(12.1344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0369, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2946, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3335, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [09:16<00:24,  3.39it/s]

tensor(12.1309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0393, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3653, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3942, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [09:16<00:17,  4.78it/s]

tensor(12.1257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0397, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4150, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0390, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4063, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [09:17<00:12,  6.55it/s]

tensor(12.1143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0382, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4053, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1014, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4060, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [09:17<00:11,  7.02it/s]

tensor(12.0900, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4234, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:17<00:09,  7.71it/s]

tensor(12.0782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4269, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4203, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:18<00:09,  8.00it/s]

tensor(12.0594, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4245, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0518, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4328, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [09:18<00:08,  8.05it/s]

tensor(12.0474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4329, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0446, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4337, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [09:18<00:08,  7.91it/s]

tensor(12.0405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4348, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4363, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [09:18<00:08,  8.01it/s]

tensor(12.0323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4414, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4399, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:19<00:08,  8.08it/s]

tensor(12.0249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4451, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0200, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4459, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [09:19<00:07,  8.16it/s]

tensor(12.0158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4390, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4414, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [09:19<00:07,  8.08it/s]

tensor(12.0080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4471, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [09:19<00:07,  7.94it/s]

tensor(11.9992, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4491, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4505, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:20<00:06,  8.18it/s]

tensor(11.9913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4502, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4491, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:20<00:06,  8.18it/s]

tensor(11.9855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4522, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4568, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [09:20<00:06,  8.10it/s]

tensor(11.9803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4534, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4495, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [09:20<00:06,  8.07it/s]

tensor(11.9757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4493, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4512, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [09:20<00:06,  8.00it/s]

tensor(11.9704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4494, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([249, 114, 206, 267,  80,  90,  94, 168, 123, 175, 126, 137, 151, 149])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<02:03, 17.20it/s]
  0%|          | 5/2129 [00:00<01:44, 20.25it/s]
  0%|          | 9/2129 [00:00<01:15, 28.05it/s]
  1%|          | 14/2129 [00:00<01:01, 34.49it/s]
  1%|          | 19/2129 [00:00<00:59, 35.73it/s]
  1%|          | 24/2129 [00:00<00:52, 39.85it/s]
  1%|▏         | 30/2129 [00:00<00:46, 44.71it/s]
  2%|▏         | 36/2129 [00:00<00:43, 47.65it/s]
  2%|▏         | 42/2129 [00:01<00:42, 49.54it/s]
  2%|▏         | 47/2129 [00:01<00:42, 49.29it/s]
  2%|▏         | 53/2129 [00:01<00:40, 51.54it/s]
  3%|▎         | 60/2129 [00:01<00:37, 55.08it/s]
  3%|▎         | 66/2129 [00:01<00:38, 53.01it/s]
  3%|▎         | 72/2129 [00:01<00:40, 50.74it/s]
  4%|▎         | 78/2129 [00:01<00:39, 51.30it/s]
  4%|▍         | 84/2129 [00:02<01:14, 27.51it/s]
  4%|▍         | 89/2129 [00:02<01:07, 30.44it/s]
  4%|▍         | 94/2129 [00:02<01:01, 32.92it/s]
  5%|▍         | 99/2129 [00:02<00:55, 36.38it/s]
  5%|▍         | 104/2129 [00:03<01:38, 20.48it/s]
  5%|▌         | 108/2129 [00:03<01:31, 22.05it/s]
  5%|▌         | 115/2129 [00:03<01:08, 29.61it/s]
  6%|▌         | 122/2129 [00:03<00:55, 36.35it/s]
  6%|▌         | 127/2129 [00:03<00:59, 33.79it/s]
  6%|▌         | 132/2129 [00:03<01:17, 25.75it/s]
  6%|▋         | 136/2129 [00:04<01:27, 22.73it/s]
  7%|▋         | 143/2129 [00:04<01:06, 29.88it/s]
  7%|▋         | 149/2129 [00:04<00:56, 34.75it/s]
  7%|▋         | 155/2129 [00:04<00:49, 39.51it/s]
  8%|▊         | 160/2129 [00:04<01:06, 29.77it/s]
  8%|▊         | 166/2129 [00:04<01:14, 26.50it/s]
  8%|▊         | 170/2129 [00:05<01:21, 23.97it/s]
  8%|▊         | 173/2129 [00:05<01:50, 17.69it/s]
  8%|▊         | 178/2129 [00:05<01:41, 19.20it/s]
  9%|▊         | 181/2129 [00:05<01:45, 18.54it/s]
  9%|▊         | 184/2129 [00:06<01:52, 17.30it/s]
  9%|▊         | 186/2129 [00:06<02:00, 16.17it/s]
  9%|▉         | 188/2129 [00:06<02:11, 14.70it/s]
  9%|▉         | 190/2129 [00:06<02:21, 13.70it/s]
  9%|▉         | 193/2129 [00:06<01:58, 16.29it/s]
  9%|▉         | 199/2129 [00:06<01:18, 24.52it/s]
  9%|▉         | 202/2129 [00:07<02:19, 13.79it/s]
 10%|▉         | 205/2129 [00:07<02:05, 15.30it/s]
 10%|▉         | 212/2129 [00:07<01:49, 17.54it/s]
 10%|█         | 215/2129 [00:08<02:03, 15.51it/s]
 10%|█         | 218/2129 [00:08<01:49, 17.38it/s]
 10%|█         | 222/2129 [00:08<01:33, 20.30it/s]
 11%|█         | 225/2129 [00:08<01:45, 18.12it/s]
 11%|█         | 229/2129 [00:08<01:27, 21.77it/s]
 11%|█         | 234/2129 [00:08<01:20, 23.60it/s]
 11%|█         | 237/2129 [00:09<01:26, 21.76it/s]
 11%|█▏        | 240/2129 [00:09<01:51, 16.89it/s]
 11%|█▏        | 242/2129 [00:09<01:54, 16.52it/s]
 12%|█▏        | 245/2129 [00:09<01:40, 18.79it/s]
 12%|█▏        | 248/2129 [00:09<02:14, 13.98it/s]
 12%|█▏        | 250/2129 [00:10<02:36, 12.04it/s]
 12%|█▏        | 252/2129 [00:10<02:50, 11.04it/s]
 12%|█▏        | 254/2129 [00:10<02:33, 12.19it/s]
 12%|█▏        | 258/2129 [00:10<01:52, 16.60it/s]
 12%|█▏        | 261/2129 [00:10<02:05, 14.88it/s]
 12%|█▏        | 263/2129 [00:11<02:01, 15.35it/s]
 13%|█▎        | 267/2129 [00:11<02:00, 15.43it/s]
 13%|█▎        | 270/2129 [00:11<01:45, 17.62it/s]
 13%|█▎        | 275/2129 [00:11<01:27, 21.20it/s]
 13%|█▎        | 278/2129 [00:11<01:32, 19.95it/s]
 13%|█▎        | 283/2129 [00:11<01:12, 25.44it/s]
 13%|█▎        | 287/2129 [00:12<01:15, 24.46it/s]
 14%|█▎        | 290/2129 [00:12<01:15, 24.27it/s]
 14%|█▍        | 293/2129 [00:12<01:54, 16.06it/s]
 14%|█▍        | 296/2129 [00:12<02:10, 14.05it/s]
 14%|█▍        | 298/2129 [00:12<02:08, 14.21it/s]
 14%|█▍        | 304/2129 [00:13<01:51, 16.33it/s]
 14%|█▍        | 306/2129 [00:13<02:08, 14.13it/s]
 15%|█▍        | 309/2129 [00:13<01:59, 15.25it/s]
 15%|█▍        | 312/2129 [00:13<01:59, 15.19it/s]
 15%|█▍        | 314/2129 [00:14<02:16, 13.27it/s]
 15%|█▍        | 316/2129 [00:14<02:07, 14.17it/s]
 15%|█▍        | 318/2129 [00:14<02:04, 14.59it/s]
 15%|█▌        | 322/2129 [00:14<01:33, 19.29it/s]
 15%|█▌        | 325/2129 [00:14<01:41, 17.69it/s]
 15%|█▌        | 327/2129 [00:14<01:40, 18.02it/s]
 15%|█▌        | 329/2129 [00:14<02:10, 13.83it/s]
 16%|█▌        | 331/2129 [00:15<03:24,  8.80it/s]
 16%|█▌        | 333/2129 [00:15<02:58, 10.07it/s]
 16%|█▌        | 335/2129 [00:15<02:35, 11.57it/s]
 16%|█▌        | 337/2129 [00:15<02:42, 11.05it/s]
 16%|█▌        | 339/2129 [00:15<02:34, 11.55it/s]
 16%|█▌        | 342/2129 [00:16<02:12, 13.51it/s]
 16%|█▋        | 346/2129 [00:16<01:43, 17.28it/s]
 16%|█▋        | 350/2129 [00:16<01:43, 17.24it/s]
 17%|█▋        | 352/2129 [00:16<01:48, 16.43it/s]
 17%|█▋        | 354/2129 [00:16<01:52, 15.73it/s]
 17%|█▋        | 356/2129 [00:17<02:57, 10.00it/s]
 17%|█▋        | 358/2129 [00:17<03:09,  9.35it/s]
 17%|█▋        | 360/2129 [00:17<02:47, 10.54it/s]
 17%|█▋        | 362/2129 [00:17<02:57,  9.96it/s]
 17%|█▋        | 364/2129 [00:17<02:40, 10.97it/s]
 17%|█▋        | 366/2129 [00:18<02:24, 12.20it/s]
 17%|█▋        | 371/2129 [00:18<01:30, 19.45it/s]
 18%|█▊        | 374/2129 [00:18<01:38, 17.88it/s]
 18%|█▊        | 377/2129 [00:18<01:36, 18.23it/s]
 18%|█▊        | 380/2129 [00:18<02:01, 14.36it/s]
 18%|█▊        | 382/2129 [00:19<02:03, 14.19it/s]
 18%|█▊        | 384/2129 [00:19<02:25, 11.97it/s]
 18%|█▊        | 386/2129 [00:19<02:45, 10.50it/s]
 18%|█▊        | 388/2129 [00:19<02:29, 11.61it/s]
 19%|█▊        | 395/2129 [00:19<01:23, 20.75it/s]
 19%|█▉        | 400/2129 [00:20<01:22, 20.90it/s]
 19%|█▉        | 403/2129 [00:20<01:29, 19.32it/s]
 19%|█▉        | 407/2129 [00:20<01:17, 22.09it/s]
 19%|█▉        | 410/2129 [00:20<01:37, 17.61it/s]
 19%|█▉        | 414/2129 [00:20<01:21, 21.13it/s]
 20%|█▉        | 417/2129 [00:20<01:15, 22.66it/s]
 20%|█▉        | 425/2129 [00:20<00:51, 33.03it/s]
 20%|██        | 432/2129 [00:21<00:53, 31.60it/s]
 20%|██        | 436/2129 [00:21<01:14, 22.64it/s]
 21%|██        | 439/2129 [00:21<01:18, 21.63it/s]
 21%|██        | 444/2129 [00:21<01:07, 24.81it/s]
 21%|██        | 451/2129 [00:21<00:54, 30.54it/s]
 21%|██▏       | 456/2129 [00:22<00:48, 34.38it/s]
 22%|██▏       | 460/2129 [00:22<01:16, 21.84it/s]
 22%|██▏       | 464/2129 [00:22<01:08, 24.37it/s]
 22%|██▏       | 468/2129 [00:23<01:41, 16.34it/s]
 22%|██▏       | 471/2129 [00:23<01:56, 14.17it/s]
 22%|██▏       | 474/2129 [00:23<01:45, 15.72it/s]
 22%|██▏       | 477/2129 [00:23<01:45, 15.66it/s]
 22%|██▏       | 479/2129 [00:23<02:00, 13.70it/s]
 23%|██▎       | 482/2129 [00:24<01:43, 15.94it/s]
 23%|██▎       | 484/2129 [00:24<02:20, 11.74it/s]
 23%|██▎       | 487/2129 [00:24<02:27, 11.11it/s]
 23%|██▎       | 490/2129 [00:24<02:28, 11.02it/s]
 23%|██▎       | 493/2129 [00:25<02:01, 13.46it/s]
 23%|██▎       | 498/2129 [00:25<01:24, 19.35it/s]
 24%|██▎       | 504/2129 [00:25<01:01, 26.28it/s]
 24%|██▍       | 508/2129 [00:25<00:58, 27.63it/s]
 24%|██▍       | 512/2129 [00:25<01:12, 22.16it/s]
 24%|██▍       | 515/2129 [00:25<01:21, 19.72it/s]
 24%|██▍       | 518/2129 [00:26<01:35, 16.88it/s]
 24%|██▍       | 521/2129 [00:26<02:07, 12.63it/s]
 25%|██▍       | 523/2129 [00:26<02:07, 12.56it/s]
 25%|██▍       | 526/2129 [00:26<02:08, 12.52it/s]
 25%|██▍       | 528/2129 [00:27<02:07, 12.56it/s]
 25%|██▍       | 530/2129 [00:27<02:47,  9.53it/s]
 25%|██▍       | 532/2129 [00:27<02:27, 10.81it/s]
 25%|██▌       | 535/2129 [00:27<01:56, 13.65it/s]
 25%|██▌       | 537/2129 [00:27<02:04, 12.81it/s]
 25%|██▌       | 539/2129 [00:27<01:52, 14.15it/s]
 26%|██▌       | 543/2129 [00:28<01:49, 14.55it/s]
 26%|██▌       | 545/2129 [00:28<01:42, 15.53it/s]
 26%|██▌       | 551/2129 [00:28<01:03, 24.66it/s]
 26%|██▌       | 557/2129 [00:28<00:51, 30.28it/s]
 26%|██▋       | 561/2129 [00:28<01:04, 24.40it/s]
 26%|██▋       | 564/2129 [00:29<01:15, 20.74it/s]
 27%|██▋       | 567/2129 [00:29<01:24, 18.57it/s]
 27%|██▋       | 570/2129 [00:29<01:21, 19.22it/s]
 27%|██▋       | 573/2129 [00:29<01:36, 16.05it/s]
 27%|██▋       | 577/2129 [00:29<01:39, 15.56it/s]
 27%|██▋       | 580/2129 [00:30<01:27, 17.78it/s]
 27%|██▋       | 583/2129 [00:30<01:28, 17.41it/s]
 27%|██▋       | 585/2129 [00:30<02:14, 11.47it/s]
 28%|██▊       | 587/2129 [00:30<02:30, 10.24it/s]
 28%|██▊       | 589/2129 [00:30<02:13, 11.53it/s]
 28%|██▊       | 591/2129 [00:31<02:28, 10.34it/s]
 28%|██▊       | 593/2129 [00:31<02:40,  9.60it/s]
 28%|██▊       | 596/2129 [00:31<02:03, 12.40it/s]
 28%|██▊       | 599/2129 [00:31<02:02, 12.53it/s]
 28%|██▊       | 601/2129 [00:31<01:53, 13.45it/s]
 28%|██▊       | 603/2129 [00:32<02:10, 11.70it/s]
 29%|██▊       | 608/2129 [00:32<01:22, 18.41it/s]
 29%|██▊       | 611/2129 [00:32<01:35, 15.84it/s]
 29%|██▉       | 614/2129 [00:32<01:23, 18.04it/s]
 29%|██▉       | 621/2129 [00:32<00:52, 28.52it/s]
 29%|██▉       | 626/2129 [00:32<01:00, 24.80it/s]
 30%|██▉       | 630/2129 [00:33<01:03, 23.62it/s]
 30%|██▉       | 633/2129 [00:33<01:21, 18.27it/s]
 30%|██▉       | 636/2129 [00:33<01:37, 15.25it/s]
 30%|███       | 639/2129 [00:33<01:25, 17.42it/s]
 30%|███       | 642/2129 [00:34<01:40, 14.81it/s]
 30%|███       | 644/2129 [00:34<01:47, 13.86it/s]
 30%|███       | 646/2129 [00:34<01:39, 14.84it/s]
 30%|███       | 649/2129 [00:34<01:45, 14.01it/s]
 31%|███       | 652/2129 [00:34<01:33, 15.85it/s]
 31%|███       | 654/2129 [00:34<01:32, 15.97it/s]
 31%|███       | 657/2129 [00:35<01:19, 18.51it/s]
 31%|███       | 660/2129 [00:35<01:46, 13.83it/s]
 31%|███       | 662/2129 [00:35<02:08, 11.44it/s]
 31%|███       | 665/2129 [00:35<01:43, 14.18it/s]
 31%|███▏      | 667/2129 [00:35<01:45, 13.92it/s]
 31%|███▏      | 670/2129 [00:36<01:30, 16.15it/s]
 32%|███▏      | 674/2129 [00:36<01:10, 20.64it/s]
 32%|███▏      | 677/2129 [00:36<01:17, 18.70it/s]
 32%|███▏      | 680/2129 [00:36<01:14, 19.46it/s]
 32%|███▏      | 684/2129 [00:36<01:20, 17.97it/s]
 32%|███▏      | 686/2129 [00:36<01:41, 14.26it/s]
 32%|███▏      | 688/2129 [00:37<02:23, 10.06it/s]
 32%|███▏      | 690/2129 [00:37<02:31,  9.52it/s]
 33%|███▎      | 693/2129 [00:37<01:56, 12.34it/s]
 33%|███▎      | 695/2129 [00:37<02:14, 10.70it/s]
 33%|███▎      | 697/2129 [00:38<02:24,  9.88it/s]
 33%|███▎      | 700/2129 [00:38<01:50, 12.95it/s]
 33%|███▎      | 706/2129 [00:38<01:07, 21.10it/s]
 33%|███▎      | 709/2129 [00:38<01:21, 17.45it/s]
 33%|███▎      | 712/2129 [00:38<01:13, 19.36it/s]
 34%|███▎      | 715/2129 [00:39<01:24, 16.68it/s]
 34%|███▍      | 719/2129 [00:39<01:07, 20.85it/s]
 34%|███▍      | 722/2129 [00:39<01:19, 17.69it/s]
 34%|███▍      | 725/2129 [00:39<01:39, 14.11it/s]
 34%|███▍      | 728/2129 [00:39<01:25, 16.46it/s]
 34%|███▍      | 732/2129 [00:39<01:09, 20.10it/s]
 35%|███▍      | 735/2129 [00:40<01:06, 21.03it/s]
 35%|███▍      | 739/2129 [00:40<01:13, 18.85it/s]
 35%|███▍      | 742/2129 [00:40<01:09, 19.86it/s]
 35%|███▌      | 748/2129 [00:40<00:50, 27.55it/s]
 35%|███▌      | 752/2129 [00:40<00:53, 25.70it/s]
 35%|███▌      | 755/2129 [00:41<01:40, 13.64it/s]
 36%|███▌      | 758/2129 [00:41<01:27, 15.65it/s]
 36%|███▌      | 762/2129 [00:41<01:25, 16.07it/s]
 36%|███▌      | 765/2129 [00:41<01:31, 14.93it/s]
 36%|███▌      | 767/2129 [00:42<01:47, 12.64it/s]
 36%|███▌      | 769/2129 [00:42<01:55, 11.76it/s]
 36%|███▋      | 772/2129 [00:42<01:39, 13.68it/s]
 36%|███▋      | 775/2129 [00:42<01:47, 12.62it/s]
 36%|███▋      | 777/2129 [00:43<02:06, 10.67it/s]
 37%|███▋      | 780/2129 [00:43<02:02, 11.04it/s]
 37%|███▋      | 782/2129 [00:43<02:11, 10.25it/s]
 37%|███▋      | 784/2129 [00:43<01:56, 11.59it/s]
 37%|███▋      | 786/2129 [00:43<02:08, 10.44it/s]
 37%|███▋      | 788/2129 [00:44<02:18,  9.65it/s]
 37%|███▋      | 792/2129 [00:44<01:33, 14.24it/s]
 37%|███▋      | 795/2129 [00:44<01:32, 14.35it/s]
 37%|███▋      | 797/2129 [00:44<01:38, 13.58it/s]
 38%|███▊      | 799/2129 [00:44<01:42, 12.92it/s]
 38%|███▊      | 801/2129 [00:44<01:46, 12.48it/s]
 38%|███▊      | 803/2129 [00:45<01:49, 12.09it/s]
 38%|███▊      | 806/2129 [00:45<01:25, 15.41it/s]
 38%|███▊      | 809/2129 [00:45<01:23, 15.83it/s]
 38%|███▊      | 811/2129 [00:45<01:32, 14.22it/s]
 38%|███▊      | 814/2129 [00:45<01:16, 17.08it/s]
 38%|███▊      | 818/2129 [00:45<01:08, 19.08it/s]
 39%|███▊      | 821/2129 [00:46<01:07, 19.29it/s]
 39%|███▊      | 824/2129 [00:46<01:01, 21.30it/s]
 39%|███▉      | 832/2129 [00:46<00:37, 34.70it/s]
 39%|███▉      | 836/2129 [00:46<00:36, 35.69it/s]
 39%|███▉      | 840/2129 [00:46<01:02, 20.56it/s]
 40%|███▉      | 844/2129 [00:47<01:25, 15.00it/s]
 40%|███▉      | 847/2129 [00:47<01:40, 12.79it/s]
 40%|███▉      | 849/2129 [00:47<01:51, 11.50it/s]
 40%|████      | 852/2129 [00:48<01:52, 11.31it/s]
 40%|████      | 854/2129 [00:48<01:59, 10.64it/s]
 40%|████      | 857/2129 [00:48<01:39, 12.85it/s]
 40%|████      | 860/2129 [00:48<01:45, 12.07it/s]
 40%|████      | 862/2129 [00:48<01:40, 12.58it/s]
 41%|████      | 865/2129 [00:49<01:43, 12.23it/s]
 41%|████      | 867/2129 [00:49<01:34, 13.40it/s]
 41%|████      | 873/2129 [00:49<00:58, 21.55it/s]
 41%|████      | 878/2129 [00:49<00:45, 27.39it/s]
 41%|████▏     | 882/2129 [00:49<01:10, 17.75it/s]
 42%|████▏     | 886/2129 [00:49<00:59, 20.79it/s]
 42%|████▏     | 889/2129 [00:50<00:58, 21.16it/s]
 42%|████▏     | 893/2129 [00:50<00:59, 20.76it/s]
 42%|████▏     | 896/2129 [00:50<01:00, 20.55it/s]
 42%|████▏     | 899/2129 [00:50<00:58, 20.85it/s]
 42%|████▏     | 902/2129 [00:50<01:12, 16.95it/s]
 42%|████▏     | 904/2129 [00:51<01:26, 14.12it/s]
 43%|████▎     | 906/2129 [00:51<01:22, 14.74it/s]
 43%|████▎     | 908/2129 [00:51<01:31, 13.32it/s]
 43%|████▎     | 911/2129 [00:51<01:28, 13.83it/s]
 43%|████▎     | 913/2129 [00:51<01:53, 10.73it/s]
 43%|████▎     | 915/2129 [00:52<01:49, 11.09it/s]
 43%|████▎     | 917/2129 [00:52<01:38, 12.34it/s]
 43%|████▎     | 920/2129 [00:52<01:22, 14.64it/s]
 44%|████▎     | 927/2129 [00:52<00:49, 24.23it/s]
 44%|████▎     | 930/2129 [00:52<00:59, 20.10it/s]
 44%|████▍     | 933/2129 [00:52<01:12, 16.47it/s]
 44%|████▍     | 935/2129 [00:53<01:12, 16.46it/s]
 44%|████▍     | 937/2129 [00:53<01:39, 12.03it/s]
 44%|████▍     | 939/2129 [00:53<01:51, 10.66it/s]
 44%|████▍     | 941/2129 [00:53<01:38, 12.09it/s]
 44%|████▍     | 944/2129 [00:54<01:43, 11.49it/s]
 44%|████▍     | 946/2129 [00:54<01:43, 11.39it/s]
 45%|████▍     | 950/2129 [00:54<01:36, 12.18it/s]
 45%|████▍     | 953/2129 [00:54<01:22, 14.23it/s]
 45%|████▍     | 958/2129 [00:55<01:23, 14.07it/s]
 45%|████▌     | 960/2129 [00:55<01:31, 12.83it/s]
 45%|████▌     | 962/2129 [00:55<01:49, 10.67it/s]
 45%|████▌     | 964/2129 [00:55<01:45, 11.09it/s]
 45%|████▌     | 967/2129 [00:55<01:23, 13.91it/s]
 46%|████▌     | 969/2129 [00:56<01:40, 11.51it/s]
 46%|████▌     | 971/2129 [00:56<01:33, 12.34it/s]
 46%|████▌     | 973/2129 [00:56<01:31, 12.67it/s]
 46%|████▌     | 975/2129 [00:56<01:29, 12.89it/s]
 46%|████▌     | 977/2129 [00:56<01:46, 10.80it/s]
 46%|████▌     | 980/2129 [00:56<01:24, 13.66it/s]
 46%|████▌     | 982/2129 [00:57<01:31, 12.47it/s]
 46%|████▌     | 984/2129 [00:57<01:47, 10.64it/s]
 46%|████▋     | 987/2129 [00:57<01:27, 13.00it/s]
 46%|████▋     | 989/2129 [00:57<01:56,  9.78it/s]
 47%|████▋     | 991/2129 [00:57<01:46, 10.66it/s]
 47%|████▋     | 993/2129 [00:58<01:39, 11.44it/s]
 47%|████▋     | 997/2129 [00:58<01:08, 16.52it/s]
 47%|████▋     | 1000/2129 [00:58<00:59, 18.86it/s]
 47%|████▋     | 1003/2129 [00:58<01:17, 14.52it/s]
 47%|████▋     | 1005/2129 [00:58<01:18, 14.32it/s]
 47%|████▋     | 1007/2129 [00:59<01:34, 11.93it/s]
 47%|████▋     | 1010/2129 [00:59<01:16, 14.61it/s]
 48%|████▊     | 1013/2129 [00:59<01:14, 14.93it/s]
 48%|████▊     | 1015/2129 [00:59<01:28, 12.61it/s]
 48%|████▊     | 1017/2129 [00:59<01:28, 12.54it/s]
 48%|████▊     | 1019/2129 [00:59<01:27, 12.68it/s]
 48%|████▊     | 1023/2129 [01:00<01:06, 16.72it/s]
 48%|████▊     | 1026/2129 [01:00<00:56, 19.38it/s]
 48%|████▊     | 1029/2129 [01:00<01:10, 15.63it/s]
 48%|████▊     | 1031/2129 [01:00<01:22, 13.24it/s]
 49%|████▊     | 1033/2129 [01:00<01:32, 11.81it/s]
 49%|████▊     | 1036/2129 [01:00<01:13, 14.84it/s]
 49%|████▉     | 1042/2129 [01:01<01:02, 17.49it/s]
 49%|████▉     | 1045/2129 [01:01<00:55, 19.60it/s]
 49%|████▉     | 1048/2129 [01:01<01:01, 17.47it/s]
 49%|████▉     | 1051/2129 [01:01<01:12, 14.95it/s]
 49%|████▉     | 1053/2129 [01:01<01:08, 15.76it/s]
 50%|████▉     | 1055/2129 [01:02<01:18, 13.74it/s]
 50%|████▉     | 1057/2129 [01:02<01:22, 12.97it/s]
 50%|████▉     | 1059/2129 [01:02<01:15, 14.11it/s]
 50%|████▉     | 1061/2129 [01:02<01:38, 10.82it/s]
 50%|████▉     | 1064/2129 [01:02<01:29, 11.86it/s]
 50%|█████     | 1066/2129 [01:03<01:27, 12.21it/s]
 50%|█████     | 1070/2129 [01:03<01:09, 15.28it/s]
 50%|█████     | 1072/2129 [01:03<01:12, 14.56it/s]
 50%|█████     | 1074/2129 [01:03<01:10, 15.02it/s]
 51%|█████     | 1077/2129 [01:03<01:08, 15.34it/s]
 51%|█████     | 1079/2129 [01:03<01:09, 15.21it/s]
 51%|█████     | 1081/2129 [01:04<01:16, 13.67it/s]
 51%|█████     | 1083/2129 [01:04<01:13, 14.28it/s]
 51%|█████     | 1085/2129 [01:04<01:23, 12.43it/s]
 51%|█████     | 1087/2129 [01:04<01:20, 12.99it/s]
 51%|█████     | 1091/2129 [01:04<01:04, 16.14it/s]
 51%|█████▏    | 1094/2129 [01:04<01:08, 15.11it/s]
 51%|█████▏    | 1096/2129 [01:05<01:04, 15.97it/s]
 52%|█████▏    | 1098/2129 [01:05<01:03, 16.28it/s]
 52%|█████▏    | 1103/2129 [01:05<00:57, 17.87it/s]
 52%|█████▏    | 1105/2129 [01:05<01:00, 16.90it/s]
 52%|█████▏    | 1107/2129 [01:05<01:16, 13.30it/s]
 52%|█████▏    | 1109/2129 [01:05<01:13, 13.81it/s]
 52%|█████▏    | 1111/2129 [01:06<01:17, 13.07it/s]
 52%|█████▏    | 1113/2129 [01:06<01:24, 12.00it/s]
 52%|█████▏    | 1115/2129 [01:06<01:17, 13.06it/s]
 52%|█████▏    | 1117/2129 [01:06<01:28, 11.46it/s]
 53%|█████▎    | 1119/2129 [01:06<01:19, 12.64it/s]
 53%|█████▎    | 1121/2129 [01:06<01:19, 12.66it/s]
 53%|█████▎    | 1123/2129 [01:07<01:13, 13.62it/s]
 53%|█████▎    | 1127/2129 [01:07<01:07, 14.88it/s]
 53%|█████▎    | 1129/2129 [01:07<01:03, 15.77it/s]
 53%|█████▎    | 1131/2129 [01:07<01:20, 12.35it/s]
 53%|█████▎    | 1133/2129 [01:07<01:18, 12.72it/s]
 53%|█████▎    | 1136/2129 [01:07<01:08, 14.56it/s]
 53%|█████▎    | 1139/2129 [01:08<01:12, 13.62it/s]
 54%|█████▎    | 1142/2129 [01:08<01:13, 13.35it/s]
 54%|█████▍    | 1146/2129 [01:08<00:58, 16.71it/s]
 54%|█████▍    | 1149/2129 [01:08<00:53, 18.39it/s]
 54%|█████▍    | 1152/2129 [01:08<00:58, 16.80it/s]
 54%|█████▍    | 1154/2129 [01:09<01:31, 10.70it/s]
 54%|█████▍    | 1156/2129 [01:09<01:43,  9.40it/s]
 54%|█████▍    | 1158/2129 [01:09<01:31, 10.61it/s]
 54%|█████▍    | 1160/2129 [01:10<01:36, 10.03it/s]
 55%|█████▍    | 1164/2129 [01:10<01:05, 14.72it/s]
 55%|█████▍    | 1166/2129 [01:10<01:14, 12.95it/s]
 55%|█████▍    | 1168/2129 [01:10<01:14, 12.90it/s]
 55%|█████▌    | 1172/2129 [01:10<01:14, 12.88it/s]
 55%|█████▌    | 1174/2129 [01:10<01:12, 13.20it/s]
 55%|█████▌    | 1176/2129 [01:11<01:14, 12.74it/s]
 55%|█████▌    | 1179/2129 [01:11<01:02, 15.23it/s]
 55%|█████▌    | 1181/2129 [01:11<01:31, 10.39it/s]
 56%|█████▌    | 1183/2129 [01:11<01:44,  9.05it/s]
 56%|█████▌    | 1185/2129 [01:12<01:45,  8.97it/s]
 56%|█████▌    | 1187/2129 [01:12<01:40,  9.35it/s]
 56%|█████▌    | 1190/2129 [01:12<01:17, 12.08it/s]
 56%|█████▌    | 1192/2129 [01:12<01:09, 13.40it/s]
 56%|█████▌    | 1194/2129 [01:12<01:19, 11.75it/s]
 56%|█████▌    | 1196/2129 [01:13<01:37,  9.56it/s]
 56%|█████▋    | 1199/2129 [01:13<01:13, 12.61it/s]
 57%|█████▋    | 1203/2129 [01:13<01:05, 14.04it/s]
 57%|█████▋    | 1205/2129 [01:13<01:01, 15.03it/s]
 57%|█████▋    | 1207/2129 [01:13<01:15, 12.22it/s]
 57%|█████▋    | 1211/2129 [01:14<01:07, 13.60it/s]
 57%|█████▋    | 1213/2129 [01:14<01:21, 11.28it/s]
 57%|█████▋    | 1217/2129 [01:14<00:59, 15.31it/s]
 57%|█████▋    | 1219/2129 [01:14<01:13, 12.30it/s]
 57%|█████▋    | 1221/2129 [01:15<01:36,  9.43it/s]
 57%|█████▋    | 1223/2129 [01:15<01:36,  9.44it/s]
 58%|█████▊    | 1225/2129 [01:15<01:45,  8.59it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 324.86it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 8], [np.int64(2), False, 7], [np.int64(4), False, 12], [np.int64(5), False, 13], [np.int64(6), False, 11], [np.int64(7), False, 0], [np.int64(8), False, 10], [np.int64(9), False, 2], [np.int64(10), False, 3], [np.int64(12), False, 9], [np.int64(13), False, 7]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9697, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [11:30<31:52, 39.03s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [11:30<21:53, 27.36s/it]

tensor(11.9681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1342, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3860, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [11:31<07:05,  9.46s/it]

tensor(11.9968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6562, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8969, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [11:31<03:22,  4.70s/it]

tensor(12.0513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0573, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1529, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [11:31<02:19,  3.33s/it]

tensor(12.0810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2172, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2481, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [11:31<00:47,  1.22s/it]

tensor(12.0749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2678, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2833, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [11:32<00:33,  1.12it/s]

tensor(12.0549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2941, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3078, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [11:32<00:13,  2.59it/s]

tensor(12.0403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3306, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3561, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [11:32<00:10,  3.26it/s]

tensor(12.0193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3808, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [11:32<00:06,  4.70it/s]

tensor(12.0030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3838, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3789, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [11:33<00:04,  6.55it/s]

tensor(11.9961, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3814, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3764, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [11:33<00:04,  6.98it/s]

tensor(11.9865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3761, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3751, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [11:33<00:03,  7.55it/s]

tensor(11.9744, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3740, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3792, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [11:33<00:02,  8.00it/s]

tensor(11.9644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3847, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3914, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [11:33<00:02,  8.06it/s]

tensor(11.9594, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3913, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3951, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [11:34<00:02,  8.08it/s]

tensor(11.9505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4028, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4065, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [11:34<00:02,  8.26it/s]

tensor(11.9414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4086, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4095, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [11:34<00:01,  8.26it/s]

tensor(11.9330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4150, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [11:34<00:01,  8.24it/s]

tensor(11.9275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4151, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4169, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [11:35<00:01,  8.23it/s]

tensor(11.9220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4176, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4228, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [11:35<00:01,  8.22it/s]

tensor(11.9170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4259, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9145, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4261, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [11:35<00:00,  8.23it/s]

tensor(11.9121, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4262, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4256, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [11:35<00:00,  8.21it/s]

tensor(11.9079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4269, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4252, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [11:36<00:00,  8.21it/s]

tensor(11.9044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4246, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4192, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [11:36<00:00,  8.22it/s]

tensor(11.9011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4178, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8994, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4174, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [11:36<00:00,  2.32s/it]

tensor(11.8981, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4148, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.001989603042602539
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 2
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.527941705220
NMI         : 0.577047106254
Runtime     : 740.73 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed2

==============================================================================================================
PRAGA RUN | E18.5 | seed=3
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 2.799e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:31,  9.58it/s]

tensor(16.9301, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4770, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4496, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2253, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:32,  9.25it/s]

tensor(15.9426, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1947, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7206, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3636, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:30,  9.70it/s]

tensor(15.5753, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7126, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4411, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2239, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:29,  9.78it/s]

tensor(15.3285, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8812, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2314, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6713, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.81it/s]

tensor(15.1595, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5808, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1021, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5969, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:29,  9.82it/s]

tensor(15.0514, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7103, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0075, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9116, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:29,  9.68it/s]

tensor(14.9644, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1915, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9224, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5432, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:28,  9.83it/s]

tensor(14.8747, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9579, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8241, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4318, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7650, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9572, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.88it/s]

tensor(14.7025, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5301, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6369, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1457, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:28,  9.75it/s]

tensor(14.5681, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.7991, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4988, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4875, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:28,  9.87it/s]

tensor(14.4291, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2073, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3579, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9549, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2882, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7285, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:27,  9.91it/s]

tensor(14.2165, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1454, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3419, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:28,  9.71it/s]

tensor(14.0754, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1776, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0094, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0304, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:27,  9.84it/s]

tensor(13.9465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8981, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8867, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7801, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6742, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:27,  9.86it/s]

tensor(13.7709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5798, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4956, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:26,  9.86it/s]

tensor(13.6710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3539, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 37/300 [00:03<00:26,  9.85it/s]

tensor(13.5858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2945, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5432, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2423, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:26,  9.86it/s]

tensor(13.5022, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1965, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4646, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1566, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▎        | 41/300 [00:04<00:26,  9.76it/s]

tensor(13.4304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0932, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:26,  9.62it/s]

tensor(13.3669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0698, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3364, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0526, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:26,  9.61it/s]

tensor(13.3073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0414, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 47/300 [00:04<00:26,  9.67it/s]

tensor(13.2530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:05<00:25,  9.77it/s]

tensor(13.2000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:25,  9.63it/s]

tensor(13.1468, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1200, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 53/300 [00:05<00:26,  9.49it/s]

tensor(13.0933, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:25,  9.62it/s]

tensor(13.0423, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:24,  9.74it/s]

tensor(12.9932, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9469, device='cuda:0', grad_fn=<AddBackward0>)

 19%|█▉        | 58/300 [00:05<00:24,  9.76it/s]

tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.76it/s]

tensor(12.8792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8576, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:24,  9.67it/s]

tensor(12.8363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:24,  9.58it/s]

tensor(12.7958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:24,  9.55it/s]

tensor(12.7571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:23,  9.68it/s]

tensor(12.7191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:07<00:23,  9.57it/s]

tensor(12.6828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:23,  9.50it/s]

tensor(12.6472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:07<00:23,  9.63it/s]

tensor(12.6126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:08<00:22,  9.70it/s]

tensor(12.5794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:08<00:22,  9.62it/s]

tensor(12.5475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:22,  9.50it/s]

tensor(12.5170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:22,  9.46it/s]

tensor(12.4876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:22,  9.53it/s]

tensor(12.4596, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:09<00:22,  9.52it/s]

tensor(12.4326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4194, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:21,  9.67it/s]

tensor(12.4067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3945, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:21,  9.52it/s]

tensor(12.3821, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:21,  9.50it/s]

tensor(12.3582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:21,  9.66it/s]

tensor(12.3354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:10<00:21,  9.56it/s]

tensor(12.3131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.47it/s]

tensor(12.2918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.2814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([324, 222, 197,  76,  90, 259, 132, 340,  46, 103,  85, 137,  64,  54])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:23, 25.36it/s]
  0%|          | 9/2129 [00:00<00:53, 39.26it/s]
  1%|          | 15/2129 [00:00<00:45, 46.73it/s]
  1%|          | 22/2129 [00:00<00:38, 54.06it/s]
  1%|▏         | 29/2129 [00:00<00:35, 58.47it/s]
  2%|▏         | 37/2129 [00:00<00:33, 62.22it/s]
  2%|▏         | 44/2129 [00:00<00:34, 60.91it/s]
  2%|▏         | 51/2129 [00:00<00:33, 62.30it/s]
  3%|▎         | 59/2129 [00:01<00:32, 63.89it/s]
  3%|▎         | 66/2129 [00:01<01:11, 28.89it/s]
  3%|▎         | 71/2129 [00:01<01:07, 30.69it/s]
  4%|▎         | 79/2129 [00:01<00:53, 38.35it/s]
  4%|▍         | 85/2129 [00:02<01:10, 29.08it/s]
  4%|▍         | 92/2129 [00:02<00:58, 34.83it/s]
  5%|▍         | 98/2129 [00:02<00:52, 38.36it/s]
  5%|▍         | 103/2129 [00:02<01:25, 23.63it/s]
  5%|▌         | 107/2129 [00:03<01:43, 19.52it/s]
  5%|▌         | 111/2129 [00:03<01:56, 17.27it/s]
  5%|▌         | 114/2129 [00:03<02:10, 15.46it/s]
  5%|▌         | 117/2129 [00:03<01:58, 16.93it/s]
  6%|▌         | 124/2129 [00:03<01:20, 24.80it/s]
  6%|▌         | 131/2129 [00:04<01:01, 32.55it/s]
  6%|▋         | 136/2129 [00:04<01:23, 23.83it/s]
  7%|▋         | 144/2129 [00:04<01:01, 32.14it/s]
  7%|▋         | 151/2129 [00:04<00:50, 38.88it/s]
  7%|▋         | 157/2129 [00:04<00:57, 34.34it/s]
  8%|▊         | 162/2129 [00:05<01:31, 21.40it/s]
  8%|▊         | 166/2129 [00:05<01:45, 18.68it/s]
  8%|▊         | 169/2129 [00:05<01:40, 19.41it/s]
  8%|▊         | 177/2129 [00:05<01:09, 28.14it/s]
  9%|▊         | 182/2129 [00:06<01:24, 23.10it/s]
  9%|▊         | 186/2129 [00:06<01:39, 19.50it/s]
  9%|▉         | 190/2129 [00:06<01:46, 18.24it/s]
  9%|▉         | 194/2129 [00:06<01:31, 21.15it/s]
  9%|▉         | 200/2129 [00:07<01:30, 21.40it/s]
 10%|▉         | 203/2129 [00:07<01:48, 17.76it/s]
 10%|▉         | 206/2129 [00:07<01:47, 17.82it/s]
 10%|▉         | 210/2129 [00:07<01:31, 20.95it/s]
 10%|█         | 213/2129 [00:08<02:01, 15.81it/s]
 10%|█         | 216/2129 [00:08<02:21, 13.48it/s]
 10%|█         | 219/2129 [00:08<02:09, 14.70it/s]
 10%|█         | 223/2129 [00:08<01:44, 18.27it/s]
 11%|█         | 226/2129 [00:08<01:38, 19.39it/s]
 11%|█         | 229/2129 [00:08<01:33, 20.33it/s]
 11%|█         | 232/2129 [00:09<01:31, 20.79it/s]
 11%|█         | 235/2129 [00:09<01:46, 17.71it/s]
 11%|█         | 238/2129 [00:09<01:40, 18.90it/s]
 11%|█▏        | 241/2129 [00:09<01:54, 16.46it/s]
 12%|█▏        | 246/2129 [00:09<01:44, 18.04it/s]
 12%|█▏        | 248/2129 [00:10<02:07, 14.75it/s]
 12%|█▏        | 250/2129 [00:10<02:11, 14.27it/s]
 12%|█▏        | 253/2129 [00:10<01:58, 15.78it/s]
 12%|█▏        | 255/2129 [00:10<02:28, 12.64it/s]
 12%|█▏        | 258/2129 [00:10<02:35, 12.04it/s]
 12%|█▏        | 260/2129 [00:11<03:18,  9.43it/s]
 12%|█▏        | 262/2129 [00:11<03:27,  8.98it/s]
 12%|█▏        | 265/2129 [00:11<02:47, 11.16it/s]
 13%|█▎        | 267/2129 [00:11<02:52, 10.82it/s]
 13%|█▎        | 269/2129 [00:12<02:38, 11.74it/s]
 13%|█▎        | 271/2129 [00:12<02:35, 11.97it/s]
 13%|█▎        | 273/2129 [00:12<02:59, 10.35it/s]
 13%|█▎        | 275/2129 [00:12<03:11,  9.70it/s]
 13%|█▎        | 277/2129 [00:12<02:44, 11.27it/s]
 13%|█▎        | 279/2129 [00:12<02:32, 12.11it/s]
 13%|█▎        | 284/2129 [00:13<01:35, 19.31it/s]
 13%|█▎        | 287/2129 [00:13<01:49, 16.82it/s]
 14%|█▎        | 290/2129 [00:13<01:44, 17.57it/s]
 14%|█▎        | 292/2129 [00:13<02:14, 13.61it/s]
 14%|█▍        | 294/2129 [00:13<02:06, 14.49it/s]
 14%|█▍        | 297/2129 [00:13<01:52, 16.32it/s]
 14%|█▍        | 304/2129 [00:14<01:38, 18.45it/s]
 14%|█▍        | 306/2129 [00:14<01:55, 15.77it/s]
 15%|█▍        | 309/2129 [00:14<01:43, 17.59it/s]
 15%|█▍        | 312/2129 [00:14<01:47, 16.87it/s]
 15%|█▍        | 314/2129 [00:15<02:48, 10.80it/s]
 15%|█▍        | 317/2129 [00:15<02:19, 13.01it/s]
 15%|█▌        | 320/2129 [00:15<02:20, 12.86it/s]
 15%|█▌        | 323/2129 [00:15<01:59, 15.06it/s]
 15%|█▌        | 325/2129 [00:16<02:19, 12.91it/s]
 15%|█▌        | 328/2129 [00:16<02:26, 12.28it/s]
 16%|█▌        | 330/2129 [00:16<02:50, 10.55it/s]
 16%|█▌        | 332/2129 [00:16<03:05,  9.70it/s]
 16%|█▌        | 334/2129 [00:17<03:16,  9.14it/s]
 16%|█▌        | 335/2129 [00:17<03:58,  7.54it/s]
 16%|█▌        | 337/2129 [00:17<03:58,  7.52it/s]
 16%|█▌        | 340/2129 [00:17<02:48, 10.62it/s]
 16%|█▌        | 342/2129 [00:17<02:47, 10.64it/s]
 16%|█▌        | 344/2129 [00:18<03:13,  9.22it/s]
 16%|█▋        | 349/2129 [00:18<02:10, 13.68it/s]
 16%|█▋        | 351/2129 [00:18<02:24, 12.33it/s]
 17%|█▋        | 354/2129 [00:18<02:23, 12.34it/s]
 17%|█▋        | 356/2129 [00:19<02:53, 10.24it/s]
 17%|█▋        | 358/2129 [00:19<03:34,  8.24it/s]
 17%|█▋        | 359/2129 [00:19<04:32,  6.49it/s]
 17%|█▋        | 361/2129 [00:20<04:32,  6.48it/s]
 17%|█▋        | 362/2129 [00:20<04:39,  6.31it/s]
 17%|█▋        | 365/2129 [00:20<03:13,  9.13it/s]
 18%|█▊        | 373/2129 [00:20<01:56, 15.07it/s]
 18%|█▊        | 376/2129 [00:21<02:08, 13.66it/s]
 18%|█▊        | 378/2129 [00:21<02:02, 14.26it/s]
 18%|█▊        | 380/2129 [00:21<02:16, 12.86it/s]
 18%|█▊        | 382/2129 [00:21<02:07, 13.75it/s]
 18%|█▊        | 384/2129 [00:21<02:19, 12.51it/s]
 18%|█▊        | 386/2129 [00:22<03:10,  9.14it/s]
 18%|█▊        | 388/2129 [00:22<02:45, 10.53it/s]
 18%|█▊        | 391/2129 [00:22<02:31, 11.45it/s]
 19%|█▊        | 394/2129 [00:22<02:40, 10.82it/s]
 19%|█▊        | 397/2129 [00:22<02:11, 13.16it/s]
 19%|█▉        | 400/2129 [00:23<02:08, 13.46it/s]
 19%|█▉        | 402/2129 [00:23<02:00, 14.35it/s]
 19%|█▉        | 405/2129 [00:23<02:03, 14.00it/s]
 19%|█▉        | 407/2129 [00:23<02:04, 13.81it/s]
 19%|█▉        | 409/2129 [00:23<02:30, 11.42it/s]
 19%|█▉        | 411/2129 [00:23<02:21, 12.17it/s]
 19%|█▉        | 413/2129 [00:24<02:10, 13.13it/s]
 20%|█▉        | 420/2129 [00:24<01:10, 24.11it/s]
 20%|█▉        | 423/2129 [00:24<01:30, 18.89it/s]
 20%|██        | 426/2129 [00:24<01:22, 20.75it/s]
 20%|██        | 429/2129 [00:24<01:42, 16.51it/s]
 20%|██        | 432/2129 [00:25<01:44, 16.20it/s]
 20%|██        | 434/2129 [00:25<02:10, 12.95it/s]
 20%|██        | 436/2129 [00:25<02:21, 11.93it/s]
 21%|██        | 439/2129 [00:25<02:21, 11.91it/s]
 21%|██        | 442/2129 [00:26<02:37, 10.73it/s]
 21%|██        | 445/2129 [00:26<02:07, 13.23it/s]
 21%|██        | 452/2129 [00:26<01:15, 22.28it/s]
 21%|██▏       | 456/2129 [00:26<01:14, 22.51it/s]
 22%|██▏       | 459/2129 [00:26<01:47, 15.56it/s]
 22%|██▏       | 462/2129 [00:27<01:44, 15.90it/s]
 22%|██▏       | 466/2129 [00:27<01:42, 16.15it/s]
 22%|██▏       | 468/2129 [00:27<01:51, 14.88it/s]
 22%|██▏       | 470/2129 [00:27<01:46, 15.59it/s]
 22%|██▏       | 472/2129 [00:27<01:43, 15.96it/s]
 22%|██▏       | 475/2129 [00:27<01:35, 17.29it/s]
 22%|██▏       | 477/2129 [00:28<01:46, 15.48it/s]
 22%|██▏       | 479/2129 [00:28<02:34, 10.66it/s]
 23%|██▎       | 481/2129 [00:28<02:57,  9.26it/s]
 23%|██▎       | 483/2129 [00:28<02:55,  9.38it/s]
 23%|██▎       | 485/2129 [00:29<02:42, 10.10it/s]
 23%|██▎       | 487/2129 [00:29<03:10,  8.61it/s]
 23%|██▎       | 489/2129 [00:29<02:50,  9.63it/s]
 23%|██▎       | 491/2129 [00:29<02:44,  9.94it/s]
 23%|██▎       | 493/2129 [00:29<02:58,  9.15it/s]
 23%|██▎       | 494/2129 [00:30<03:25,  7.95it/s]
 23%|██▎       | 496/2129 [00:30<02:52,  9.49it/s]
 23%|██▎       | 498/2129 [00:30<03:16,  8.30it/s]
 24%|██▎       | 501/2129 [00:30<02:46,  9.78it/s]
 24%|██▎       | 503/2129 [00:30<02:24, 11.28it/s]
 24%|██▎       | 505/2129 [00:31<02:09, 12.58it/s]
 24%|██▍       | 508/2129 [00:31<02:05, 12.93it/s]
 24%|██▍       | 510/2129 [00:31<02:29, 10.86it/s]
 24%|██▍       | 512/2129 [00:31<02:38, 10.21it/s]
 24%|██▍       | 515/2129 [00:31<02:08, 12.59it/s]
 24%|██▍       | 517/2129 [00:32<02:14, 12.01it/s]
 24%|██▍       | 519/2129 [00:32<02:02, 13.12it/s]
 24%|██▍       | 521/2129 [00:32<02:53,  9.28it/s]
 25%|██▍       | 523/2129 [00:32<03:04,  8.72it/s]
 25%|██▍       | 525/2129 [00:33<03:10,  8.41it/s]
 25%|██▍       | 526/2129 [00:33<03:24,  7.83it/s]
 25%|██▍       | 528/2129 [00:33<03:15,  8.18it/s]
 25%|██▍       | 529/2129 [00:33<03:27,  7.73it/s]
 25%|██▍       | 530/2129 [00:33<03:51,  6.91it/s]
 25%|██▍       | 532/2129 [00:33<02:55,  9.08it/s]
 25%|██▌       | 535/2129 [00:34<02:09, 12.31it/s]
 25%|██▌       | 537/2129 [00:34<02:17, 11.57it/s]
 25%|██▌       | 539/2129 [00:34<02:08, 12.34it/s]
 26%|██▌       | 543/2129 [00:34<01:51, 14.17it/s]
 26%|██▌       | 545/2129 [00:34<02:01, 13.01it/s]
 26%|██▌       | 547/2129 [00:35<02:17, 11.54it/s]
 26%|██▌       | 549/2129 [00:35<03:00,  8.73it/s]
 26%|██▌       | 551/2129 [00:35<03:01,  8.71it/s]
 26%|██▌       | 553/2129 [00:35<03:15,  8.08it/s]
 26%|██▌       | 555/2129 [00:36<02:48,  9.33it/s]
 26%|██▌       | 557/2129 [00:36<03:01,  8.66it/s]
 26%|██▋       | 559/2129 [00:36<02:35, 10.08it/s]
 26%|██▋       | 561/2129 [00:36<02:13, 11.73it/s]
 26%|██▋       | 563/2129 [00:36<02:09, 12.05it/s]
 27%|██▋       | 565/2129 [00:36<02:16, 11.44it/s]
 27%|██▋       | 567/2129 [00:37<02:39,  9.79it/s]
 27%|██▋       | 569/2129 [00:37<02:22, 10.97it/s]
 27%|██▋       | 571/2129 [00:37<02:38,  9.80it/s]
 27%|██▋       | 573/2129 [00:37<02:18, 11.26it/s]
 27%|██▋       | 577/2129 [00:37<01:59, 13.04it/s]
 27%|██▋       | 580/2129 [00:38<01:38, 15.71it/s]
 27%|██▋       | 582/2129 [00:38<01:55, 13.36it/s]
 27%|██▋       | 584/2129 [00:38<02:16, 11.29it/s]
 28%|██▊       | 586/2129 [00:38<02:26, 10.55it/s]
 28%|██▊       | 588/2129 [00:39<02:39,  9.69it/s]
 28%|██▊       | 590/2129 [00:39<03:34,  7.17it/s]
 28%|██▊       | 593/2129 [00:39<03:13,  7.95it/s]
 28%|██▊       | 594/2129 [00:40<03:47,  6.74it/s]
 28%|██▊       | 597/2129 [00:40<02:41,  9.46it/s]
 28%|██▊       | 599/2129 [00:40<02:38,  9.65it/s]
 28%|██▊       | 602/2129 [00:40<02:34,  9.87it/s]
 28%|██▊       | 604/2129 [00:40<02:55,  8.71it/s]
 28%|██▊       | 605/2129 [00:41<03:12,  7.92it/s]
 29%|██▊       | 608/2129 [00:41<02:17, 11.04it/s]
 29%|██▊       | 610/2129 [00:41<02:23, 10.59it/s]
 29%|██▊       | 612/2129 [00:41<02:09, 11.71it/s]
 29%|██▉       | 614/2129 [00:41<02:21, 10.67it/s]
 29%|██▉       | 616/2129 [00:42<02:30, 10.03it/s]
 29%|██▉       | 618/2129 [00:42<02:08, 11.75it/s]
 29%|██▉       | 622/2129 [00:42<01:48, 13.88it/s]
 29%|██▉       | 625/2129 [00:42<01:40, 14.98it/s]
 29%|██▉       | 627/2129 [00:42<01:38, 15.21it/s]
 30%|██▉       | 629/2129 [00:42<01:56, 12.93it/s]
 30%|██▉       | 631/2129 [00:43<02:13, 11.19it/s]
 30%|██▉       | 633/2129 [00:43<03:03,  8.16it/s]
 30%|██▉       | 635/2129 [00:43<02:37,  9.50it/s]
 30%|██▉       | 637/2129 [00:43<02:46,  8.95it/s]
 30%|███       | 639/2129 [00:44<02:19, 10.66it/s]
 30%|███       | 641/2129 [00:44<02:29,  9.96it/s]
 30%|███       | 643/2129 [00:44<02:45,  8.99it/s]
 30%|███       | 645/2129 [00:44<02:43,  9.10it/s]
 30%|███       | 648/2129 [00:44<01:59, 12.44it/s]
 31%|███       | 650/2129 [00:45<02:23, 10.34it/s]
 31%|███       | 652/2129 [00:45<02:08, 11.52it/s]
 31%|███       | 654/2129 [00:45<02:16, 10.79it/s]
 31%|███       | 656/2129 [00:45<02:25, 10.15it/s]
 31%|███       | 658/2129 [00:45<02:33,  9.57it/s]
 31%|███       | 661/2129 [00:46<02:30,  9.77it/s]
 31%|███       | 663/2129 [00:46<02:58,  8.21it/s]
 31%|███▏      | 666/2129 [00:46<02:23, 10.21it/s]
 31%|███▏      | 668/2129 [00:47<02:39,  9.16it/s]
 31%|███▏      | 670/2129 [00:47<02:17, 10.62it/s]
 32%|███▏      | 672/2129 [00:47<02:29,  9.73it/s]
 32%|███▏      | 675/2129 [00:47<02:27,  9.84it/s]
 32%|███▏      | 677/2129 [00:47<02:35,  9.36it/s]
 32%|███▏      | 679/2129 [00:48<02:18, 10.45it/s]
 32%|███▏      | 683/2129 [00:48<01:55, 12.54it/s]
 32%|███▏      | 685/2129 [00:48<02:05, 11.50it/s]
 32%|███▏      | 687/2129 [00:48<02:15, 10.63it/s]
 32%|███▏      | 689/2129 [00:49<02:51,  8.39it/s]
 32%|███▏      | 691/2129 [00:49<02:34,  9.31it/s]
 33%|███▎      | 694/2129 [00:49<02:34,  9.31it/s]
 33%|███▎      | 696/2129 [00:49<02:38,  9.06it/s]
 33%|███▎      | 698/2129 [00:50<02:39,  9.00it/s]
 33%|███▎      | 701/2129 [00:50<02:04, 11.46it/s]
 33%|███▎      | 703/2129 [00:50<02:00, 11.82it/s]
 33%|███▎      | 705/2129 [00:50<02:01, 11.69it/s]
 33%|███▎      | 707/2129 [00:50<02:16, 10.45it/s]
 33%|███▎      | 709/2129 [00:51<02:27,  9.64it/s]
 33%|███▎      | 712/2129 [00:51<02:19, 10.13it/s]
 34%|███▎      | 714/2129 [00:51<02:33,  9.19it/s]
 34%|███▎      | 718/2129 [00:51<01:43, 13.58it/s]
 34%|███▍      | 720/2129 [00:51<02:00, 11.65it/s]
 34%|███▍      | 722/2129 [00:52<02:11, 10.74it/s]
 34%|███▍      | 724/2129 [00:52<02:53,  8.12it/s]
 34%|███▍      | 726/2129 [00:53<03:21,  6.96it/s]
 34%|███▍      | 727/2129 [00:53<03:33,  6.56it/s]
 34%|███▍      | 728/2129 [00:53<03:49,  6.10it/s]
 34%|███▍      | 729/2129 [00:53<04:26,  5.25it/s]
 34%|███▍      | 731/2129 [00:53<03:12,  7.26it/s]
 34%|███▍      | 733/2129 [00:54<02:56,  7.89it/s]
 35%|███▍      | 737/2129 [00:54<02:15, 10.24it/s]
 35%|███▍      | 739/2129 [00:54<02:33,  9.05it/s]
 35%|███▍      | 741/2129 [00:54<02:17, 10.11it/s]
 35%|███▍      | 743/2129 [00:54<01:58, 11.67it/s]
 35%|███▍      | 745/2129 [00:54<01:44, 13.20it/s]
 35%|███▌      | 750/2129 [00:55<01:32, 14.96it/s]
 35%|███▌      | 752/2129 [00:55<01:48, 12.69it/s]
 35%|███▌      | 754/2129 [00:55<02:28,  9.28it/s]
 36%|███▌      | 756/2129 [00:56<02:28,  9.22it/s]
 36%|███▌      | 758/2129 [00:56<02:37,  8.72it/s]
 36%|███▌      | 761/2129 [00:56<02:00, 11.39it/s]
 36%|███▌      | 763/2129 [00:56<02:39,  8.57it/s]
 36%|███▌      | 766/2129 [00:57<02:30,  9.06it/s]
 36%|███▌      | 768/2129 [00:57<02:36,  8.69it/s]
 36%|███▌      | 769/2129 [00:57<02:53,  7.84it/s]
 36%|███▋      | 772/2129 [00:57<02:42,  8.35it/s]
 36%|███▋      | 774/2129 [00:58<02:45,  8.18it/s]
 36%|███▋      | 775/2129 [00:58<03:01,  7.46it/s]
 36%|███▋      | 776/2129 [00:58<03:18,  6.81it/s]
 36%|███▋      | 777/2129 [00:58<03:52,  5.82it/s]
 37%|███▋      | 780/2129 [00:59<03:00,  7.49it/s]
 37%|███▋      | 782/2129 [00:59<02:50,  7.91it/s]
 37%|███▋      | 784/2129 [00:59<03:05,  7.26it/s]
 37%|███▋      | 785/2129 [00:59<03:24,  6.56it/s]
 37%|███▋      | 787/2129 [01:00<03:14,  6.88it/s]
 37%|███▋      | 790/2129 [01:00<02:13, 10.02it/s]
 37%|███▋      | 795/2129 [01:00<01:39, 13.46it/s]
 37%|███▋      | 797/2129 [01:00<02:24,  9.20it/s]
 38%|███▊      | 799/2129 [01:01<02:36,  8.49it/s]
 38%|███▊      | 801/2129 [01:01<02:39,  8.35it/s]
 38%|███▊      | 802/2129 [01:01<02:51,  7.74it/s]
 38%|███▊      | 805/2129 [01:01<02:05, 10.51it/s]
 38%|███▊      | 809/2129 [01:02<01:43, 12.73it/s]
 38%|███▊      | 811/2129 [01:02<01:57, 11.22it/s]
 38%|███▊      | 813/2129 [01:02<02:46,  7.90it/s]
 38%|███▊      | 817/2129 [01:02<01:54, 11.46it/s]
 38%|███▊      | 819/2129 [01:03<02:02, 10.65it/s]
 39%|███▊      | 821/2129 [01:03<02:11,  9.94it/s]
 39%|███▊      | 824/2129 [01:03<01:42, 12.70it/s]
 39%|███▉      | 826/2129 [01:03<01:51, 11.66it/s]
 39%|███▉      | 828/2129 [01:03<02:02, 10.61it/s]
 39%|███▉      | 832/2129 [01:04<01:24, 15.40it/s]
 39%|███▉      | 838/2129 [01:04<01:10, 18.33it/s]
 40%|███▉      | 841/2129 [01:04<01:31, 14.13it/s]
 40%|███▉      | 843/2129 [01:05<02:04, 10.31it/s]
 40%|███▉      | 845/2129 [01:05<02:12,  9.68it/s]
 40%|███▉      | 847/2129 [01:05<02:17,  9.30it/s]
 40%|███▉      | 849/2129 [01:05<02:25,  8.82it/s]
 40%|████      | 852/2129 [01:06<02:13,  9.54it/s]
 40%|████      | 854/2129 [01:06<02:25,  8.76it/s]
 40%|████      | 856/2129 [01:06<02:33,  8.31it/s]
 40%|████      | 857/2129 [01:06<02:52,  7.39it/s]
 40%|████      | 860/2129 [01:07<02:35,  8.19it/s]
 40%|████      | 862/2129 [01:07<02:35,  8.12it/s]
 41%|████      | 864/2129 [01:07<02:09,  9.75it/s]
 41%|████      | 866/2129 [01:07<02:46,  7.60it/s]
 41%|████      | 869/2129 [01:08<01:58, 10.62it/s]
 41%|████      | 873/2129 [01:08<01:42, 12.24it/s]
 41%|████      | 876/2129 [01:08<01:51, 11.27it/s]
 41%|████      | 878/2129 [01:08<02:09,  9.64it/s]
 41%|████▏     | 881/2129 [01:09<02:01, 10.26it/s]
 42%|████▏     | 884/2129 [01:09<01:38, 12.64it/s]
 42%|████▏     | 886/2129 [01:09<01:42, 12.15it/s]
 42%|████▏     | 888/2129 [01:09<01:56, 10.66it/s]
 42%|████▏     | 890/2129 [01:10<02:07,  9.68it/s]
 42%|████▏     | 893/2129 [01:10<02:04,  9.95it/s]
 42%|████▏     | 895/2129 [01:10<02:13,  9.21it/s]
 42%|████▏     | 897/2129 [01:10<01:55, 10.71it/s]
 42%|████▏     | 899/2129 [01:10<02:07,  9.62it/s]
 42%|████▏     | 901/2129 [01:11<02:26,  8.37it/s]
 42%|████▏     | 902/2129 [01:11<02:42,  7.56it/s]
 42%|████▏     | 903/2129 [01:11<03:00,  6.79it/s]
 43%|████▎     | 905/2129 [01:11<03:02,  6.71it/s]
 43%|████▎     | 906/2129 [01:12<03:12,  6.35it/s]
 43%|████▎     | 908/2129 [01:12<02:57,  6.88it/s]
 43%|████▎     | 909/2129 [01:12<03:32,  5.74it/s]
 43%|████▎     | 911/2129 [01:12<03:08,  6.45it/s]
 43%|████▎     | 912/2129 [01:13<03:22,  6.01it/s]
 43%|████▎     | 914/2129 [01:13<03:05,  6.57it/s]
 43%|████▎     | 916/2129 [01:13<03:03,  6.60it/s]
 43%|████▎     | 917/2129 [01:13<03:27,  5.84it/s]
 43%|████▎     | 919/2129 [01:14<02:36,  7.75it/s]
 43%|████▎     | 924/2129 [01:14<01:48, 11.12it/s]
 43%|████▎     | 926/2129 [01:14<01:58, 10.18it/s]
 44%|████▎     | 928/2129 [01:15<02:31,  7.92it/s]
 44%|████▎     | 929/2129 [01:15<03:07,  6.41it/s]
 44%|████▎     | 931/2129 [01:15<02:59,  6.66it/s]
 44%|████▍     | 933/2129 [01:15<02:23,  8.34it/s]
 44%|████▍     | 936/2129 [01:15<02:06,  9.40it/s]
 44%|████▍     | 938/2129 [01:16<02:42,  7.34it/s]
 44%|████▍     | 939/2129 [01:16<02:45,  7.21it/s]
 44%|████▍     | 940/2129 [01:16<02:59,  6.64it/s]
 44%|████▍     | 943/2129 [01:17<02:27,  8.05it/s]
 44%|████▍     | 944/2129 [01:17<02:44,  7.21it/s]
 44%|████▍     | 945/2129 [01:17<03:02,  6.48it/s]
 44%|████▍     | 946/2129 [01:17<03:17,  6.00it/s]
 45%|████▍     | 948/2129 [01:17<02:23,  8.24it/s]
 45%|████▍     | 950/2129 [01:17<02:22,  8.28it/s]
 45%|████▍     | 952/2129 [01:18<01:56, 10.14it/s]
 45%|████▍     | 955/2129 [01:18<01:50, 10.63it/s]
 45%|████▍     | 957/2129 [01:18<02:00,  9.70it/s]
 45%|████▌     | 959/2129 [01:18<02:10,  8.99it/s]
 45%|████▌     | 960/2129 [01:19<02:37,  7.43it/s]
 45%|████▌     | 961/2129 [01:19<02:50,  6.87it/s]
 45%|████▌     | 963/2129 [01:19<02:55,  6.66it/s]
 45%|████▌     | 966/2129 [01:19<01:57,  9.92it/s]
 45%|████▌     | 968/2129 [01:20<02:16,  8.54it/s]
 46%|████▌     | 970/2129 [01:20<02:24,  8.02it/s]
 46%|████▌     | 971/2129 [01:20<02:37,  7.35it/s]
 46%|████▌     | 973/2129 [01:20<02:23,  8.08it/s]
 46%|████▌     | 974/2129 [01:20<02:30,  7.68it/s]
 46%|████▌     | 976/2129 [01:21<02:02,  9.45it/s]
 46%|████▌     | 978/2129 [01:21<02:14,  8.54it/s]
 46%|████▌     | 980/2129 [01:21<01:58,  9.67it/s]
 46%|████▌     | 982/2129 [01:21<02:29,  7.68it/s]
 46%|████▌     | 984/2129 [01:22<02:48,  6.78it/s]
 46%|████▋     | 988/2129 [01:22<02:02,  9.31it/s]
 47%|████▋     | 991/2129 [01:22<01:37, 11.64it/s]
 47%|████▋     | 993/2129 [01:22<01:30, 12.56it/s]
 47%|████▋     | 995/2129 [01:22<01:23, 13.58it/s]
 47%|████▋     | 1000/2129 [01:22<00:54, 20.83it/s]
 47%|████▋     | 1003/2129 [01:23<01:29, 12.53it/s]
 47%|████▋     | 1006/2129 [01:23<01:14, 15.11it/s]
 47%|████▋     | 1009/2129 [01:23<01:25, 13.08it/s]
 47%|████▋     | 1011/2129 [01:23<01:33, 11.90it/s]
 48%|████▊     | 1013/2129 [01:24<02:10,  8.54it/s]
 48%|████▊     | 1015/2129 [01:24<02:09,  8.58it/s]
 48%|████▊     | 1017/2129 [01:25<02:49,  6.56it/s]
 48%|████▊     | 1018/2129 [01:25<02:55,  6.34it/s]
 48%|████▊     | 1019/2129 [01:25<02:50,  6.51it/s]
 48%|████▊     | 1021/2129 [01:25<02:42,  6.81it/s]
 48%|████▊     | 1023/2129 [01:26<02:34,  7.14it/s]
 48%|████▊     | 1024/2129 [01:26<02:37,  7.03it/s]
 48%|████▊     | 1025/2129 [01:26<02:45,  6.68it/s]
 48%|████▊     | 1027/2129 [01:26<02:42,  6.80it/s]
 48%|████▊     | 1029/2129 [01:26<02:12,  8.32it/s]
 48%|████▊     | 1030/2129 [01:26<02:26,  7.48it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 293.50it/s]

[[np.int64(0), False, 2], [np.int64(1), False, 5], [np.int64(3), False, 2], [np.int64(4), False, 1], [np.int64(6), False, 7], [np.int64(7), False, 0], [np.int64(8), False, 12], [np.int64(9), False, 2], [np.int64(10), False, 7], [np.int64(11), False, 3], [np.int64(13), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8544, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:00<3:48:44, 68.97s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:00<2:39:30, 48.33s/it]

tensor(12.2637, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.9595, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2707, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1211, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:00<54:09, 16.67s/it]

tensor(12.2977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3102, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3364, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4810, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [04:00<37:50, 11.70s/it]

tensor(12.3741, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6300, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7382, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [04:01<13:02,  4.10s/it]

tensor(12.4131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8374, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9416, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [04:01<06:30,  2.07s/it]

tensor(12.4083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0446, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4037, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1439, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:01<03:21,  1.08s/it]

tensor(12.3990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2216, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2825, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:01<01:48,  1.70it/s]

tensor(12.3629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3202, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3620, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [04:02<01:04,  2.85it/s]

tensor(12.3145, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3913, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4321, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [04:02<00:42,  4.28it/s]

tensor(12.3080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4669, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4968, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:02<00:36,  4.99it/s]

tensor(12.3026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5285, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5543, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:02<00:28,  6.16it/s]

tensor(12.2711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5814, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5962, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [04:03<00:24,  7.13it/s]

tensor(12.2247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6122, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2037, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6269, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [04:03<00:22,  7.76it/s]

tensor(12.1858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6407, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1690, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6503, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:03<00:21,  8.01it/s]

tensor(12.1527, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6679, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1367, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6838, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:03<00:20,  8.14it/s]

tensor(12.1219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6982, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7169, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:04<00:21,  7.81it/s]

tensor(12.0955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7333, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7494, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [04:04<00:20,  8.00it/s]

tensor(12.0698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7686, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0569, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7850, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [04:04<00:20,  8.15it/s]

tensor(12.0450, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8007, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8169, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [04:04<00:19,  8.20it/s]

tensor(12.0274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8318, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8448, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [04:05<00:19,  8.09it/s]

tensor(12.0139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8732, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:05<00:19,  8.20it/s]

tensor(11.9999, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9932, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9024, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [04:05<00:18,  8.22it/s]

tensor(11.9866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9361, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [04:05<00:18,  8.25it/s]

tensor(11.9734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9526, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9737, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:06<00:18,  8.23it/s]

tensor(11.9608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9907, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0059, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:06<00:18,  8.22it/s]

tensor(11.9476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0190, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([261,  66, 265,  81, 130, 120, 196, 134,  61,  70,  48, 329, 247, 121])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<01:52, 18.98it/s]
  0%|          | 5/2129 [00:00<01:27, 24.30it/s]
  0%|          | 9/2129 [00:00<01:12, 29.36it/s]
  1%|          | 14/2129 [00:00<00:59, 35.83it/s]
  1%|          | 19/2129 [00:00<00:52, 39.95it/s]
  1%|          | 25/2129 [00:00<00:45, 45.94it/s]
  1%|▏         | 31/2129 [00:00<00:42, 49.08it/s]
  2%|▏         | 36/2129 [00:00<00:48, 43.57it/s]
  2%|▏         | 41/2129 [00:01<00:58, 35.75it/s]
  2%|▏         | 45/2129 [00:01<01:30, 23.09it/s]
  2%|▏         | 49/2129 [00:01<01:23, 24.93it/s]
  2%|▏         | 53/2129 [00:01<01:32, 22.45it/s]
  3%|▎         | 56/2129 [00:02<01:57, 17.67it/s]
  3%|▎         | 60/2129 [00:02<01:38, 21.02it/s]
  3%|▎         | 65/2129 [00:02<01:58, 17.36it/s]
  3%|▎         | 68/2129 [00:02<01:57, 17.54it/s]
  3%|▎         | 71/2129 [00:02<02:00, 17.11it/s]
  3%|▎         | 73/2129 [00:03<02:59, 11.47it/s]
  4%|▎         | 75/2129 [00:03<02:43, 12.57it/s]
  4%|▍         | 80/2129 [00:03<02:15, 15.12it/s]
  4%|▍         | 83/2129 [00:03<01:57, 17.37it/s]
  4%|▍         | 88/2129 [00:03<01:28, 23.00it/s]
  4%|▍         | 92/2129 [00:04<01:18, 25.86it/s]
  5%|▍         | 96/2129 [00:04<01:15, 27.08it/s]
  5%|▍         | 100/2129 [00:04<01:18, 25.92it/s]
  5%|▍         | 103/2129 [00:04<02:16, 14.80it/s]
  5%|▍         | 106/2129 [00:05<02:43, 12.40it/s]
  5%|▌         | 111/2129 [00:05<01:56, 17.34it/s]
  5%|▌         | 114/2129 [00:05<01:47, 18.80it/s]
  5%|▌         | 117/2129 [00:05<01:36, 20.81it/s]
  6%|▌         | 123/2129 [00:05<01:17, 25.97it/s]
  6%|▌         | 127/2129 [00:06<01:50, 18.11it/s]
  6%|▌         | 130/2129 [00:06<01:44, 19.16it/s]
  6%|▌         | 133/2129 [00:06<02:06, 15.80it/s]
  7%|▋         | 139/2129 [00:06<01:27, 22.63it/s]
  7%|▋         | 145/2129 [00:06<01:07, 29.50it/s]
  7%|▋         | 151/2129 [00:06<00:55, 35.78it/s]
  7%|▋         | 156/2129 [00:06<00:57, 34.42it/s]
  8%|▊         | 161/2129 [00:07<01:19, 24.80it/s]
  8%|▊         | 165/2129 [00:07<01:50, 17.81it/s]
  8%|▊         | 168/2129 [00:08<02:39, 12.28it/s]
  8%|▊         | 171/2129 [00:08<02:22, 13.78it/s]
  8%|▊         | 176/2129 [00:08<01:56, 16.77it/s]
  8%|▊         | 179/2129 [00:08<02:11, 14.83it/s]
  9%|▊         | 183/2129 [00:08<01:48, 18.01it/s]
  9%|▊         | 186/2129 [00:09<02:09, 14.98it/s]
  9%|▉         | 188/2129 [00:09<02:31, 12.84it/s]
  9%|▉         | 190/2129 [00:09<02:45, 11.71it/s]
  9%|▉         | 193/2129 [00:09<02:15, 14.26it/s]
  9%|▉         | 200/2129 [00:10<01:48, 17.74it/s]
  9%|▉         | 202/2129 [00:10<02:18, 13.91it/s]
 10%|▉         | 205/2129 [00:10<02:02, 15.64it/s]
 10%|▉         | 211/2129 [00:10<01:24, 22.78it/s]
 10%|█         | 214/2129 [00:11<02:50, 11.25it/s]
 10%|█         | 217/2129 [00:11<02:32, 12.58it/s]
 10%|█         | 223/2129 [00:11<02:06, 15.02it/s]
 11%|█         | 226/2129 [00:11<01:56, 16.39it/s]
 11%|█         | 229/2129 [00:12<02:04, 15.31it/s]
 11%|█         | 232/2129 [00:12<01:48, 17.41it/s]
 11%|█         | 235/2129 [00:12<02:25, 13.06it/s]
 11%|█         | 238/2129 [00:12<02:12, 14.23it/s]
 11%|█▏        | 240/2129 [00:13<02:54, 10.81it/s]
 11%|█▏        | 244/2129 [00:13<02:07, 14.75it/s]
 12%|█▏        | 247/2129 [00:13<02:07, 14.75it/s]
 12%|█▏        | 249/2129 [00:13<02:53, 10.81it/s]
 12%|█▏        | 251/2129 [00:14<03:35,  8.70it/s]
 12%|█▏        | 253/2129 [00:14<03:44,  8.34it/s]
 12%|█▏        | 255/2129 [00:14<03:21,  9.30it/s]
 12%|█▏        | 258/2129 [00:14<03:19,  9.36it/s]
 12%|█▏        | 260/2129 [00:15<03:57,  7.86it/s]
 12%|█▏        | 261/2129 [00:15<04:32,  6.85it/s]
 12%|█▏        | 263/2129 [00:15<03:43,  8.35it/s]
 13%|█▎        | 267/2129 [00:15<03:00, 10.31it/s]
 13%|█▎        | 270/2129 [00:16<02:25, 12.80it/s]
 13%|█▎        | 273/2129 [00:16<02:56, 10.54it/s]
 13%|█▎        | 275/2129 [00:16<02:57, 10.43it/s]
 13%|█▎        | 277/2129 [00:16<02:41, 11.50it/s]
 13%|█▎        | 282/2129 [00:16<01:46, 17.40it/s]
 13%|█▎        | 286/2129 [00:16<01:26, 21.24it/s]
 14%|█▎        | 289/2129 [00:17<01:58, 15.50it/s]
 14%|█▎        | 292/2129 [00:17<01:49, 16.75it/s]
 14%|█▍        | 295/2129 [00:17<02:03, 14.80it/s]
 14%|█▍        | 298/2129 [00:17<01:47, 16.97it/s]
 14%|█▍        | 304/2129 [00:18<01:38, 18.57it/s]
 14%|█▍        | 307/2129 [00:18<02:03, 14.78it/s]
 15%|█▍        | 312/2129 [00:18<01:57, 15.40it/s]
 15%|█▍        | 314/2129 [00:19<02:54, 10.42it/s]
 15%|█▍        | 316/2129 [00:19<02:41, 11.22it/s]
 15%|█▌        | 321/2129 [00:19<01:49, 16.55it/s]
 15%|█▌        | 324/2129 [00:19<01:56, 15.44it/s]
 15%|█▌        | 327/2129 [00:19<01:46, 16.86it/s]
 16%|█▌        | 330/2129 [00:20<02:37, 11.41it/s]
 16%|█▌        | 332/2129 [00:20<02:53, 10.34it/s]
 16%|█▌        | 334/2129 [00:20<02:56, 10.18it/s]
 16%|█▌        | 337/2129 [00:20<02:38, 11.33it/s]
 16%|█▌        | 339/2129 [00:21<02:23, 12.45it/s]
 16%|█▌        | 341/2129 [00:21<02:12, 13.46it/s]
 16%|█▌        | 343/2129 [00:21<03:16,  9.07it/s]
 16%|█▌        | 345/2129 [00:21<03:36,  8.24it/s]
 16%|█▋        | 347/2129 [00:22<03:05,  9.59it/s]
 16%|█▋        | 349/2129 [00:22<03:04,  9.66it/s]
 16%|█▋        | 351/2129 [00:22<03:10,  9.31it/s]
 17%|█▋        | 354/2129 [00:22<03:01,  9.77it/s]
 17%|█▋        | 356/2129 [00:23<03:18,  8.94it/s]
 17%|█▋        | 357/2129 [00:23<03:46,  7.82it/s]
 17%|█▋        | 358/2129 [00:23<04:11,  7.05it/s]
 17%|█▋        | 360/2129 [00:23<04:45,  6.19it/s]
 17%|█▋        | 361/2129 [00:24<05:04,  5.81it/s]
 17%|█▋        | 362/2129 [00:24<05:20,  5.52it/s]
 17%|█▋        | 364/2129 [00:24<04:02,  7.29it/s]
 17%|█▋        | 370/2129 [00:24<01:49, 16.05it/s]
 18%|█▊        | 373/2129 [00:24<02:04, 14.08it/s]
 18%|█▊        | 375/2129 [00:25<02:35, 11.25it/s]
 18%|█▊        | 377/2129 [00:25<03:02,  9.59it/s]
 18%|█▊        | 380/2129 [00:25<03:06,  9.37it/s]
 18%|█▊        | 382/2129 [00:25<02:47, 10.41it/s]
 18%|█▊        | 384/2129 [00:26<02:59,  9.70it/s]
 18%|█▊        | 386/2129 [00:26<03:28,  8.37it/s]
 18%|█▊        | 387/2129 [00:26<03:29,  8.31it/s]
 18%|█▊        | 390/2129 [00:26<02:30, 11.59it/s]
 18%|█▊        | 392/2129 [00:26<02:43, 10.65it/s]
 19%|█▊        | 394/2129 [00:27<03:01,  9.58it/s]
 19%|█▊        | 396/2129 [00:27<02:34, 11.21it/s]
 19%|█▊        | 399/2129 [00:27<02:02, 14.12it/s]
 19%|█▉        | 401/2129 [00:27<02:47, 10.34it/s]
 19%|█▉        | 403/2129 [00:27<02:34, 11.18it/s]
 19%|█▉        | 405/2129 [00:28<03:13,  8.92it/s]
 19%|█▉        | 407/2129 [00:28<03:16,  8.75it/s]
 19%|█▉        | 409/2129 [00:28<02:57,  9.68it/s]
 19%|█▉        | 412/2129 [00:28<02:13, 12.89it/s]
 20%|█▉        | 416/2129 [00:28<01:40, 16.96it/s]
 20%|█▉        | 422/2129 [00:29<01:19, 21.42it/s]
 20%|█▉        | 425/2129 [00:29<02:00, 14.19it/s]
 20%|██        | 427/2129 [00:29<01:53, 14.93it/s]
 20%|██        | 429/2129 [00:29<01:51, 15.22it/s]
 20%|██        | 431/2129 [00:29<02:16, 12.42it/s]
 20%|██        | 433/2129 [00:30<03:09,  8.97it/s]
 20%|██        | 436/2129 [00:30<02:51,  9.85it/s]
 21%|██        | 438/2129 [00:30<02:29, 11.28it/s]
 21%|██        | 440/2129 [00:30<02:48, 10.03it/s]
 21%|██        | 442/2129 [00:31<03:28,  8.10it/s]
 21%|██        | 445/2129 [00:31<02:34, 10.89it/s]
 21%|██        | 449/2129 [00:31<01:48, 15.53it/s]
 21%|██▏       | 455/2129 [00:31<01:34, 17.79it/s]
 22%|██▏       | 458/2129 [00:32<01:56, 14.37it/s]
 22%|██▏       | 460/2129 [00:32<02:16, 12.18it/s]
 22%|██▏       | 462/2129 [00:32<03:00,  9.24it/s]
 22%|██▏       | 465/2129 [00:32<02:21, 11.77it/s]
 22%|██▏       | 467/2129 [00:33<02:42, 10.25it/s]
 22%|██▏       | 469/2129 [00:33<02:51,  9.66it/s]
 22%|██▏       | 471/2129 [00:33<03:00,  9.16it/s]
 22%|██▏       | 473/2129 [00:33<02:39, 10.38it/s]
 22%|██▏       | 477/2129 [00:34<02:20, 11.79it/s]
 22%|██▏       | 479/2129 [00:34<03:11,  8.61it/s]
 23%|██▎       | 481/2129 [00:34<03:07,  8.78it/s]
 23%|██▎       | 483/2129 [00:34<02:46,  9.91it/s]
 23%|██▎       | 485/2129 [00:35<02:41, 10.17it/s]
 23%|██▎       | 487/2129 [00:35<02:52,  9.55it/s]
 23%|██▎       | 490/2129 [00:35<02:51,  9.57it/s]
 23%|██▎       | 492/2129 [00:35<03:26,  7.91it/s]
 23%|██▎       | 494/2129 [00:36<03:17,  8.29it/s]
 23%|██▎       | 497/2129 [00:36<02:25, 11.19it/s]
 23%|██▎       | 499/2129 [00:36<03:09,  8.59it/s]
 24%|██▎       | 501/2129 [00:36<03:18,  8.19it/s]
 24%|██▎       | 505/2129 [00:37<02:13, 12.16it/s]
 24%|██▍       | 508/2129 [00:37<02:13, 12.14it/s]
 24%|██▍       | 510/2129 [00:37<02:26, 11.03it/s]
 24%|██▍       | 512/2129 [00:37<02:54,  9.28it/s]
 24%|██▍       | 515/2129 [00:38<02:43,  9.87it/s]
 24%|██▍       | 517/2129 [00:38<02:43,  9.86it/s]
 24%|██▍       | 519/2129 [00:38<02:27, 10.91it/s]
 24%|██▍       | 521/2129 [00:38<03:04,  8.69it/s]
 25%|██▍       | 523/2129 [00:39<02:50,  9.42it/s]
 25%|██▍       | 525/2129 [00:39<02:32, 10.52it/s]
 25%|██▍       | 527/2129 [00:39<02:37, 10.20it/s]
 25%|██▍       | 529/2129 [00:39<03:31,  7.58it/s]
 25%|██▍       | 530/2129 [00:40<03:59,  6.68it/s]
 25%|██▍       | 532/2129 [00:40<03:08,  8.47it/s]
 25%|██▌       | 535/2129 [00:40<02:43,  9.72it/s]
 25%|██▌       | 537/2129 [00:40<02:36, 10.16it/s]
 25%|██▌       | 539/2129 [00:40<02:15, 11.70it/s]
 26%|██▌       | 543/2129 [00:40<01:52, 14.12it/s]
 26%|██▌       | 545/2129 [00:41<02:47,  9.45it/s]
 26%|██▌       | 547/2129 [00:41<03:02,  8.68it/s]
 26%|██▌       | 549/2129 [00:41<03:09,  8.34it/s]
 26%|██▌       | 551/2129 [00:42<03:43,  7.06it/s]
 26%|██▌       | 553/2129 [00:42<03:11,  8.24it/s]
 26%|██▌       | 557/2129 [00:42<02:32, 10.30it/s]
 26%|██▋       | 559/2129 [00:42<02:56,  8.87it/s]
 26%|██▋       | 560/2129 [00:43<03:09,  8.27it/s]
 26%|██▋       | 562/2129 [00:43<02:46,  9.40it/s]
 26%|██▋       | 564/2129 [00:43<03:32,  7.38it/s]
 27%|██▋       | 566/2129 [00:43<02:53,  9.01it/s]
 27%|██▋       | 568/2129 [00:44<02:53,  8.98it/s]
 27%|██▋       | 570/2129 [00:44<02:26, 10.65it/s]
 27%|██▋       | 572/2129 [00:44<02:09, 11.98it/s]
 27%|██▋       | 576/2129 [00:44<01:30, 17.10it/s]
 27%|██▋       | 579/2129 [00:44<01:51, 13.95it/s]
 27%|██▋       | 581/2129 [00:44<02:06, 12.26it/s]
 27%|██▋       | 584/2129 [00:45<02:14, 11.51it/s]
 28%|██▊       | 586/2129 [00:45<02:27, 10.48it/s]
 28%|██▊       | 588/2129 [00:45<02:39,  9.65it/s]
 28%|██▊       | 590/2129 [00:46<03:25,  7.50it/s]
 28%|██▊       | 593/2129 [00:46<03:03,  8.37it/s]
 28%|██▊       | 594/2129 [00:46<03:48,  6.73it/s]
 28%|██▊       | 596/2129 [00:46<03:39,  6.98it/s]
 28%|██▊       | 598/2129 [00:47<02:57,  8.62it/s]
 28%|██▊       | 600/2129 [00:47<02:59,  8.54it/s]
 28%|██▊       | 602/2129 [00:47<02:45,  9.25it/s]
 28%|██▊       | 604/2129 [00:47<02:31, 10.09it/s]
 28%|██▊       | 606/2129 [00:47<02:13, 11.39it/s]
 29%|██▊       | 609/2129 [00:48<02:20, 10.82it/s]
 29%|██▊       | 611/2129 [00:48<02:25, 10.42it/s]
 29%|██▉       | 613/2129 [00:48<02:23, 10.57it/s]
 29%|██▉       | 615/2129 [00:48<02:49,  8.93it/s]
 29%|██▉       | 617/2129 [00:48<02:26, 10.30it/s]
 29%|██▉       | 619/2129 [00:49<02:14, 11.19it/s]
 29%|██▉       | 622/2129 [00:49<01:56, 12.95it/s]
 29%|██▉       | 624/2129 [00:49<01:48, 13.84it/s]
 29%|██▉       | 626/2129 [00:49<01:49, 13.76it/s]
 29%|██▉       | 628/2129 [00:49<02:27, 10.21it/s]
 30%|██▉       | 631/2129 [00:50<02:46,  8.99it/s]
 30%|██▉       | 633/2129 [00:50<02:57,  8.43it/s]
 30%|██▉       | 635/2129 [00:50<02:42,  9.18it/s]
 30%|██▉       | 637/2129 [00:50<02:40,  9.28it/s]
 30%|███       | 640/2129 [00:50<02:06, 11.76it/s]
 30%|███       | 642/2129 [00:51<02:28, 10.03it/s]
 30%|███       | 644/2129 [00:51<03:16,  7.56it/s]
 30%|███       | 646/2129 [00:51<02:45,  8.99it/s]
 30%|███       | 648/2129 [00:51<02:36,  9.47it/s]
 31%|███       | 650/2129 [00:52<02:34,  9.57it/s]
 31%|███       | 652/2129 [00:52<02:13, 11.05it/s]
 31%|███       | 654/2129 [00:52<02:25, 10.16it/s]
 31%|███       | 656/2129 [00:52<02:20, 10.45it/s]
 31%|███       | 658/2129 [00:52<02:27,  9.96it/s]
 31%|███       | 660/2129 [00:53<02:35,  9.47it/s]
 31%|███       | 662/2129 [00:53<02:46,  8.82it/s]
 31%|███       | 663/2129 [00:53<02:57,  8.28it/s]
 31%|███       | 665/2129 [00:53<02:30,  9.74it/s]
 31%|███▏      | 667/2129 [00:53<02:07, 11.47it/s]
 31%|███▏      | 669/2129 [00:53<01:55, 12.63it/s]
 32%|███▏      | 672/2129 [00:54<02:01, 12.02it/s]
 32%|███▏      | 675/2129 [00:54<01:46, 13.61it/s]
 32%|███▏      | 677/2129 [00:54<01:59, 12.13it/s]
 32%|███▏      | 679/2129 [00:55<02:43,  8.86it/s]
 32%|███▏      | 682/2129 [00:55<02:08, 11.23it/s]
 32%|███▏      | 684/2129 [00:55<03:30,  6.86it/s]
 32%|███▏      | 686/2129 [00:56<03:58,  6.04it/s]
 32%|███▏      | 687/2129 [00:56<03:50,  6.25it/s]
 32%|███▏      | 688/2129 [00:56<03:40,  6.55it/s]
 32%|███▏      | 689/2129 [00:56<03:34,  6.71it/s]
 32%|███▏      | 691/2129 [00:56<02:54,  8.23it/s]
 33%|███▎      | 694/2129 [00:56<02:19, 10.29it/s]
 33%|███▎      | 696/2129 [00:57<02:36,  9.13it/s]
 33%|███▎      | 698/2129 [00:57<02:50,  8.39it/s]
 33%|███▎      | 700/2129 [00:57<02:22, 10.02it/s]
 33%|███▎      | 703/2129 [00:57<02:12, 10.79it/s]
 33%|███▎      | 705/2129 [00:58<02:20, 10.10it/s]
 33%|███▎      | 707/2129 [00:58<02:05, 11.30it/s]
 33%|███▎      | 709/2129 [00:58<01:55, 12.29it/s]
 33%|███▎      | 711/2129 [00:58<01:48, 13.13it/s]
 33%|███▎      | 713/2129 [00:58<02:59,  7.88it/s]
 34%|███▎      | 715/2129 [00:59<02:56,  8.00it/s]
 34%|███▍      | 719/2129 [00:59<02:12, 10.63it/s]
 34%|███▍      | 721/2129 [00:59<02:25,  9.70it/s]
 34%|███▍      | 723/2129 [01:00<02:41,  8.71it/s]
 34%|███▍      | 724/2129 [01:00<02:46,  8.42it/s]
 34%|███▍      | 725/2129 [01:00<03:04,  7.60it/s]
 34%|███▍      | 726/2129 [01:00<03:01,  7.71it/s]
 34%|███▍      | 727/2129 [01:00<03:12,  7.29it/s]
 34%|███▍      | 728/2129 [01:00<03:34,  6.52it/s]
 34%|███▍      | 731/2129 [01:00<02:11, 10.64it/s]
 34%|███▍      | 733/2129 [01:01<02:42,  8.61it/s]
 35%|███▍      | 735/2129 [01:01<02:21,  9.87it/s]
 35%|███▍      | 737/2129 [01:01<02:01, 11.45it/s]
 35%|███▍      | 739/2129 [01:01<02:18, 10.04it/s]
 35%|███▍      | 741/2129 [01:02<02:48,  8.26it/s]
 35%|███▍      | 743/2129 [01:02<02:24,  9.57it/s]
 35%|███▌      | 747/2129 [01:02<01:36, 14.35it/s]
 35%|███▌      | 750/2129 [01:02<01:54, 12.03it/s]
 35%|███▌      | 752/2129 [01:02<02:09, 10.62it/s]
 35%|███▌      | 754/2129 [01:03<02:57,  7.75it/s]
 36%|███▌      | 756/2129 [01:03<02:58,  7.68it/s]
 36%|███▌      | 758/2129 [01:04<03:13,  7.07it/s]
 36%|███▌      | 760/2129 [01:04<02:44,  8.31it/s]
 36%|███▌      | 762/2129 [01:04<02:38,  8.65it/s]
 36%|███▌      | 764/2129 [01:04<02:42,  8.38it/s]
 36%|███▌      | 766/2129 [01:04<02:53,  7.87it/s]
 36%|███▌      | 767/2129 [01:05<03:15,  6.96it/s]
 36%|███▌      | 769/2129 [01:05<03:17,  6.90it/s]
 36%|███▌      | 771/2129 [01:05<02:37,  8.64it/s]
 36%|███▋      | 773/2129 [01:05<02:10, 10.42it/s]
 36%|███▋      | 775/2129 [01:06<02:56,  7.68it/s]
 36%|███▋      | 777/2129 [01:06<03:00,  7.48it/s]
 37%|███▋      | 780/2129 [01:06<02:34,  8.71it/s]
 37%|███▋      | 782/2129 [01:06<02:39,  8.46it/s]
 37%|███▋      | 784/2129 [01:07<03:05,  7.27it/s]
 37%|███▋      | 785/2129 [01:07<03:10,  7.07it/s]
 37%|███▋      | 786/2129 [01:07<04:00,  5.58it/s]
 37%|███▋      | 787/2129 [01:08<04:36,  4.85it/s]
 37%|███▋      | 789/2129 [01:08<03:26,  6.48it/s]
 37%|███▋      | 791/2129 [01:08<02:43,  8.18it/s]
 37%|███▋      | 795/2129 [01:08<01:55, 11.51it/s]
 37%|███▋      | 797/2129 [01:09<02:57,  7.52it/s]
 38%|███▊      | 799/2129 [01:09<03:03,  7.25it/s]
 38%|███▊      | 800/2129 [01:09<03:22,  6.57it/s]
 38%|███▊      | 802/2129 [01:09<03:06,  7.12it/s]
 38%|███▊      | 804/2129 [01:09<02:31,  8.77it/s]
 38%|███▊      | 809/2129 [01:10<01:50, 11.97it/s]
 38%|███▊      | 811/2129 [01:10<02:02, 10.74it/s]
 38%|███▊      | 813/2129 [01:10<02:54,  7.54it/s]
 38%|███▊      | 815/2129 [01:11<02:52,  7.63it/s]
 38%|███▊      | 817/2129 [01:11<02:35,  8.44it/s]
 38%|███▊      | 818/2129 [01:11<02:56,  7.41it/s]
 39%|███▊      | 820/2129 [01:11<02:36,  8.38it/s]
 39%|███▊      | 822/2129 [01:11<02:18,  9.41it/s]
 39%|███▊      | 824/2129 [01:11<01:56, 11.19it/s]
 39%|███▉      | 826/2129 [01:12<02:16,  9.55it/s]
 39%|███▉      | 828/2129 [01:12<02:02, 10.59it/s]
 39%|███▉      | 831/2129 [01:12<02:05, 10.35it/s]
 39%|███▉      | 833/2129 [01:12<01:50, 11.73it/s]
 39%|███▉      | 837/2129 [01:12<01:16, 16.90it/s]
 39%|███▉      | 840/2129 [01:13<02:05, 10.27it/s]
 40%|███▉      | 842/2129 [01:13<02:41,  7.97it/s]
 40%|███▉      | 844/2129 [01:14<02:49,  7.60it/s]
 40%|███▉      | 846/2129 [01:14<03:08,  6.82it/s]
 40%|███▉      | 847/2129 [01:14<03:03,  7.00it/s]
 40%|███▉      | 848/2129 [01:14<03:09,  6.76it/s]
 40%|███▉      | 850/2129 [01:14<02:26,  8.73it/s]
 40%|████      | 852/2129 [01:15<02:32,  8.39it/s]
 40%|████      | 854/2129 [01:15<02:15,  9.40it/s]
 40%|████      | 856/2129 [01:15<02:25,  8.73it/s]
 40%|████      | 858/2129 [01:15<02:24,  8.79it/s]
 40%|████      | 860/2129 [01:16<02:13,  9.50it/s]
 40%|████      | 862/2129 [01:16<02:31,  8.38it/s]
 41%|████      | 863/2129 [01:16<02:29,  8.45it/s]
 41%|████      | 865/2129 [01:16<02:32,  8.28it/s]
 41%|████      | 866/2129 [01:16<02:57,  7.13it/s]
 41%|████      | 868/2129 [01:17<02:22,  8.83it/s]
 41%|████      | 871/2129 [01:17<01:50, 11.37it/s]
 41%|████      | 873/2129 [01:17<02:10,  9.62it/s]
 41%|████      | 876/2129 [01:17<01:58, 10.61it/s]
 41%|████▏     | 879/2129 [01:17<01:36, 12.89it/s]
 41%|████▏     | 881/2129 [01:18<02:22,  8.77it/s]
 41%|████▏     | 883/2129 [01:18<02:04, 10.03it/s]
 42%|████▏     | 886/2129 [01:18<01:55, 10.73it/s]
 42%|████▏     | 888/2129 [01:19<02:28,  8.33it/s]
 42%|████▏     | 890/2129 [01:19<02:58,  6.95it/s]
 42%|████▏     | 891/2129 [01:19<03:08,  6.56it/s]
 42%|████▏     | 893/2129 [01:19<02:56,  6.98it/s]
 42%|████▏     | 895/2129 [01:20<03:03,  6.74it/s]
 42%|████▏     | 897/2129 [01:20<02:28,  8.32it/s]
 42%|████▏     | 899/2129 [01:20<02:29,  8.24it/s]
 42%|████▏     | 900/2129 [01:20<03:05,  6.62it/s]
 42%|████▏     | 901/2129 [01:21<02:56,  6.97it/s]
 42%|████▏     | 902/2129 [01:21<03:25,  5.97it/s]
 42%|████▏     | 903/2129 [01:21<03:40,  5.56it/s]
 43%|████▎     | 905/2129 [01:21<03:33,  5.73it/s]
 43%|████▎     | 906/2129 [01:22<03:35,  5.68it/s]
 43%|████▎     | 908/2129 [01:22<03:13,  6.30it/s]
 43%|████▎     | 910/2129 [01:22<02:33,  7.95it/s]
 43%|████▎     | 911/2129 [01:22<02:54,  6.98it/s]
 43%|████▎     | 912/2129 [01:22<02:45,  7.34it/s]
 43%|████▎     | 914/2129 [01:22<02:24,  8.41it/s]
 43%|████▎     | 916/2129 [01:23<02:14,  9.04it/s]
 43%|████▎     | 917/2129 [01:23<02:33,  7.89it/s]
 43%|████▎     | 919/2129 [01:23<01:59, 10.12it/s]
 43%|████▎     | 924/2129 [01:23<01:11, 16.96it/s]
 43%|████▎     | 926/2129 [01:23<01:15, 15.83it/s]
 44%|████▎     | 928/2129 [01:24<02:04,  9.67it/s]
 44%|████▎     | 931/2129 [01:24<01:58, 10.10it/s]
 44%|████▍     | 933/2129 [01:24<02:05,  9.50it/s]
 44%|████▍     | 936/2129 [01:24<01:43, 11.54it/s]
 44%|████▍     | 938/2129 [01:25<01:43, 11.56it/s]
 44%|████▍     | 940/2129 [01:25<02:10,  9.08it/s]
 44%|████▍     | 943/2129 [01:25<02:04,  9.54it/s]
 44%|████▍     | 945/2129 [01:26<02:39,  7.42it/s]
 44%|████▍     | 946/2129 [01:26<03:17,  5.99it/s]
 44%|████▍     | 947/2129 [01:26<03:39,  5.38it/s]
 45%|████▍     | 949/2129 [01:26<02:45,  7.12it/s]
 45%|████▍     | 950/2129 [01:26<02:53,  6.78it/s]
 45%|████▍     | 952/2129 [01:27<02:13,  8.81it/s]
 45%|████▍     | 955/2129 [01:27<01:51, 10.56it/s]
 45%|████▍     | 957/2129 [01:27<02:21,  8.26it/s]
 45%|████▌     | 959/2129 [01:27<02:11,  8.89it/s]
 45%|████▌     | 961/2129 [01:28<02:41,  7.21it/s]
 45%|████▌     | 963/2129 [01:28<02:43,  7.11it/s]
 45%|████▌     | 967/2129 [01:28<02:10,  8.93it/s]
 45%|████▌     | 968/2129 [01:29<02:26,  7.93it/s]
 46%|████▌     | 970/2129 [01:29<02:33,  7.55it/s]
 46%|████▌     | 971/2129 [01:29<02:50,  6.79it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 368.27it/s]
 50%|█████     | 151/300 [08:13<3:04:21, 74.24s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 11], [np.int64(2), False, 0], [np.int64(3), False, 13], [np.int64(4), False, 6], [np.int64(5), False, 2], [np.int64(6), False, 12], [np.int64(7), False, 11], [np.int64(8), False, 4], [np.int64(9), False, 3], [np.int64(10), False, 1], [np.int64(12), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5963, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [08:13<2:08:18, 52.02s/it]

tensor(11.9349, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7030, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8730, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [08:13<43:18, 17.92s/it]

tensor(11.9855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9456, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [08:14<21:04,  8.84s/it]

tensor(12.0253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9055, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9444, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [08:14<14:44,  6.23s/it]

tensor(11.9716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0237, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0680, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [08:14<07:15,  3.11s/it]

tensor(11.9558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0887, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [08:14<03:39,  1.59s/it]

tensor(11.9479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1038, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9399, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1450, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [08:15<01:54,  1.19it/s]

tensor(11.9301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1693, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2020, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [08:15<01:03,  2.11it/s]

tensor(11.9178, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2249, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9202, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2473, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [08:15<00:38,  3.40it/s]

tensor(11.9223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2635, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2951, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [08:15<00:26,  4.85it/s]

tensor(11.9073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3215, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8996, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3361, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [08:16<00:19,  6.67it/s]

tensor(11.8966, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3344, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [08:16<00:17,  7.01it/s]

tensor(11.8863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3532, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3642, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [08:16<00:16,  7.52it/s]

tensor(11.8654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3762, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3844, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [08:16<00:15,  7.66it/s]

tensor(11.8526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3963, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4083, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [08:16<00:15,  7.87it/s]

tensor(11.8477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4127, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [08:17<00:14,  7.95it/s]

tensor(11.8405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4159, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [08:17<00:14,  8.08it/s]

tensor(11.8337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4223, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4309, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [08:17<00:13,  8.14it/s]

tensor(11.8256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4432, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4491, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [08:18<00:13,  8.18it/s]

tensor(11.8169, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4586, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4661, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [08:18<00:13,  8.17it/s]

tensor(11.8106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4685, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4732, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [08:18<00:13,  8.19it/s]

tensor(11.8035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4743, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4793, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [08:18<00:12,  8.20it/s]

tensor(11.7987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4860, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4895, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [08:18<00:12,  8.19it/s]

tensor(11.7934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4907, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7911, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4988, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [08:19<00:12,  8.12it/s]

tensor(11.7888, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5067, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5120, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:19<00:12,  8.08it/s]

tensor(11.7836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5190, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([188,  56, 115, 148, 142, 244,  44, 181, 130, 111, 156, 226, 244, 144])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 5/2129 [00:00<00:46, 45.86it/s]
  1%|          | 12/2129 [00:00<00:35, 59.21it/s]
  1%|          | 18/2129 [00:00<00:43, 48.42it/s]
  1%|          | 25/2129 [00:00<00:39, 53.82it/s]
  1%|▏         | 31/2129 [00:00<00:39, 53.49it/s]
  2%|▏         | 37/2129 [00:00<00:48, 43.33it/s]
  2%|▏         | 44/2129 [00:00<00:42, 49.30it/s]
  2%|▏         | 50/2129 [00:01<00:47, 43.99it/s]
  3%|▎         | 57/2129 [00:01<00:41, 49.59it/s]
  3%|▎         | 64/2129 [00:01<00:38, 54.20it/s]
  3%|▎         | 70/2129 [00:01<00:44, 46.73it/s]
  4%|▎         | 76/2129 [00:01<00:48, 42.54it/s]
  4%|▍         | 81/2129 [00:01<00:54, 37.70it/s]
  4%|▍         | 86/2129 [00:02<01:04, 31.83it/s]
  4%|▍         | 92/2129 [00:02<00:54, 37.06it/s]
  5%|▍         | 97/2129 [00:02<01:00, 33.84it/s]
  5%|▍         | 105/2129 [00:02<00:47, 42.27it/s]
  5%|▌         | 112/2129 [00:02<00:42, 47.45it/s]
  6%|▌         | 118/2129 [00:02<00:40, 50.25it/s]
  6%|▌         | 124/2129 [00:02<00:38, 51.69it/s]
  6%|▌         | 131/2129 [00:02<00:35, 55.54it/s]
  6%|▋         | 138/2129 [00:02<00:33, 58.90it/s]
  7%|▋         | 145/2129 [00:03<00:32, 60.67it/s]
  7%|▋         | 152/2129 [00:03<00:38, 51.67it/s]
  7%|▋         | 158/2129 [00:03<00:38, 50.97it/s]
  8%|▊         | 164/2129 [00:03<00:47, 41.30it/s]
  8%|▊         | 171/2129 [00:03<00:42, 46.51it/s]
  8%|▊         | 178/2129 [00:03<00:41, 47.32it/s]
  9%|▊         | 184/2129 [00:04<00:55, 35.03it/s]
  9%|▉         | 191/2129 [00:04<00:47, 41.00it/s]
  9%|▉         | 199/2129 [00:04<00:40, 47.48it/s]
 10%|▉         | 205/2129 [00:04<00:42, 45.32it/s]
 10%|▉         | 212/2129 [00:04<00:38, 49.71it/s]
 10%|█         | 218/2129 [00:04<00:38, 50.28it/s]
 11%|█         | 225/2129 [00:04<00:34, 54.98it/s]
 11%|█         | 233/2129 [00:04<00:34, 55.30it/s]
 11%|█         | 239/2129 [00:05<00:41, 45.77it/s]
 12%|█▏        | 245/2129 [00:05<00:39, 47.88it/s]
 12%|█▏        | 251/2129 [00:05<00:40, 45.84it/s]
 12%|█▏        | 257/2129 [00:05<00:38, 48.41it/s]
 12%|█▏        | 264/2129 [00:05<00:35, 52.99it/s]
 13%|█▎        | 270/2129 [00:05<00:37, 49.85it/s]
 13%|█▎        | 276/2129 [00:05<00:39, 47.37it/s]
 13%|█▎        | 281/2129 [00:06<00:41, 44.15it/s]
 13%|█▎        | 287/2129 [00:06<00:42, 42.99it/s]
 14%|█▍        | 294/2129 [00:06<00:38, 47.28it/s]
 14%|█▍        | 299/2129 [00:06<00:45, 39.93it/s]
 14%|█▍        | 305/2129 [00:06<00:41, 43.59it/s]
 15%|█▍        | 312/2129 [00:06<00:37, 49.01it/s]
 15%|█▍        | 318/2129 [00:06<00:40, 44.40it/s]
 15%|█▌        | 325/2129 [00:06<00:36, 49.61it/s]
 16%|█▌        | 331/2129 [00:07<00:34, 51.67it/s]
 16%|█▌        | 338/2129 [00:07<00:32, 54.75it/s]
 16%|█▌        | 344/2129 [00:07<00:32, 55.02it/s]
 17%|█▋        | 352/2129 [00:07<00:29, 60.40it/s]
 17%|█▋        | 359/2129 [00:07<00:29, 60.18it/s]
 17%|█▋        | 366/2129 [00:07<00:29, 60.09it/s]
 18%|█▊        | 373/2129 [00:07<00:39, 44.23it/s]
 18%|█▊        | 379/2129 [00:08<00:39, 44.35it/s]
 18%|█▊        | 384/2129 [00:08<00:45, 38.38it/s]
 18%|█▊        | 391/2129 [00:08<00:39, 44.49it/s]
 19%|█▊        | 396/2129 [00:08<00:39, 43.65it/s]
 19%|█▉        | 401/2129 [00:08<00:40, 43.07it/s]
 19%|█▉        | 406/2129 [00:08<00:39, 43.41it/s]
 19%|█▉        | 413/2129 [00:08<00:34, 49.54it/s]
 20%|█▉        | 419/2129 [00:08<00:33, 51.11it/s]
 20%|██        | 426/2129 [00:08<00:31, 54.06it/s]
 20%|██        | 432/2129 [00:09<00:30, 55.42it/s]
 21%|██        | 439/2129 [00:09<00:29, 56.49it/s]
 21%|██        | 447/2129 [00:09<00:27, 62.28it/s]
 21%|██▏       | 454/2129 [00:09<00:27, 60.93it/s]
 22%|██▏       | 461/2129 [00:09<00:26, 63.22it/s]
 22%|██▏       | 468/2129 [00:09<00:27, 60.73it/s]
 22%|██▏       | 475/2129 [00:09<00:27, 61.19it/s]
 23%|██▎       | 482/2129 [00:09<00:27, 58.98it/s]
 23%|██▎       | 488/2129 [00:10<00:30, 54.52it/s]
 23%|██▎       | 494/2129 [00:10<00:31, 51.48it/s]
 23%|██▎       | 500/2129 [00:10<00:33, 48.28it/s]
 24%|██▎       | 505/2129 [00:10<00:35, 46.22it/s]
 24%|██▍       | 510/2129 [00:10<00:35, 45.52it/s]
 24%|██▍       | 515/2129 [00:10<00:36, 43.66it/s]
 24%|██▍       | 520/2129 [00:10<00:35, 45.26it/s]
 25%|██▍       | 525/2129 [00:10<00:41, 38.66it/s]
 25%|██▍       | 530/2129 [00:11<00:39, 40.94it/s]
 25%|██▌       | 535/2129 [00:11<00:37, 42.58it/s]
 25%|██▌       | 541/2129 [00:11<00:34, 45.75it/s]
 26%|██▌       | 549/2129 [00:11<00:29, 54.43it/s]
 26%|██▌       | 556/2129 [00:11<00:27, 57.61it/s]
 26%|██▋       | 563/2129 [00:11<00:26, 59.07it/s]
 27%|██▋       | 569/2129 [00:11<00:27, 57.66it/s]
 27%|██▋       | 575/2129 [00:11<00:27, 57.47it/s]
 27%|██▋       | 581/2129 [00:11<00:26, 57.54it/s]
 28%|██▊       | 587/2129 [00:12<00:27, 56.12it/s]
 28%|██▊       | 593/2129 [00:12<00:27, 56.76it/s]
 28%|██▊       | 599/2129 [00:12<00:26, 57.53it/s]
 28%|██▊       | 605/2129 [00:12<00:29, 52.48it/s]
 29%|██▊       | 611/2129 [00:12<00:30, 50.47it/s]
 29%|██▉       | 618/2129 [00:12<00:27, 54.58it/s]
 29%|██▉       | 625/2129 [00:12<00:26, 57.63it/s]
 30%|██▉       | 631/2129 [00:12<00:34, 43.66it/s]
 30%|██▉       | 636/2129 [00:13<00:34, 43.13it/s]
 30%|███       | 644/2129 [00:13<00:30, 49.42it/s]
 31%|███       | 651/2129 [00:13<00:27, 53.75it/s]
 31%|███       | 657/2129 [00:13<00:27, 52.70it/s]
 31%|███       | 663/2129 [00:13<00:27, 53.46it/s]
 31%|███▏      | 669/2129 [00:13<00:26, 54.61it/s]
 32%|███▏      | 675/2129 [00:13<00:34, 41.92it/s]
 32%|███▏      | 680/2129 [00:13<00:33, 43.43it/s]
 32%|███▏      | 685/2129 [00:14<00:36, 40.07it/s]
 32%|███▏      | 691/2129 [00:14<00:33, 43.14it/s]
 33%|███▎      | 697/2129 [00:14<00:30, 46.37it/s]
 33%|███▎      | 703/2129 [00:14<00:29, 48.61it/s]
 33%|███▎      | 710/2129 [00:14<00:27, 51.91it/s]
 34%|███▎      | 717/2129 [00:14<00:25, 54.74it/s]
 34%|███▍      | 723/2129 [00:14<00:28, 48.83it/s]
 34%|███▍      | 729/2129 [00:14<00:30, 45.74it/s]
 35%|███▍      | 735/2129 [00:15<00:28, 48.37it/s]
 35%|███▍      | 740/2129 [00:15<00:29, 46.31it/s]
 35%|███▌      | 746/2129 [00:15<00:28, 48.21it/s]
 35%|███▌      | 752/2129 [00:15<00:28, 48.74it/s]
 36%|███▌      | 757/2129 [00:15<00:29, 46.16it/s]
 36%|███▌      | 764/2129 [00:15<00:26, 50.87it/s]
 36%|███▌      | 770/2129 [00:15<00:33, 40.30it/s]
 37%|███▋      | 778/2129 [00:15<00:28, 48.15it/s]
 37%|███▋      | 784/2129 [00:16<00:26, 50.84it/s]
 37%|███▋      | 790/2129 [00:16<00:25, 51.62it/s]
 37%|███▋      | 797/2129 [00:16<00:23, 55.87it/s]
 38%|███▊      | 803/2129 [00:16<00:24, 53.61it/s]
 38%|███▊      | 809/2129 [00:16<00:24, 52.83it/s]
 38%|███▊      | 816/2129 [00:16<00:23, 56.17it/s]
 39%|███▊      | 823/2129 [00:16<00:21, 59.61it/s]
 39%|███▉      | 830/2129 [00:16<00:27, 47.19it/s]
 39%|███▉      | 836/2129 [00:17<00:29, 43.89it/s]
 40%|███▉      | 841/2129 [00:17<00:30, 42.82it/s]
 40%|███▉      | 847/2129 [00:17<00:28, 44.70it/s]
 40%|████      | 852/2129 [00:17<00:30, 42.03it/s]
 40%|████      | 858/2129 [00:17<00:29, 43.81it/s]
 41%|████      | 864/2129 [00:17<00:26, 47.73it/s]
 41%|████      | 870/2129 [00:17<00:25, 50.30it/s]
 41%|████      | 877/2129 [00:17<00:23, 53.40it/s]
 42%|████▏     | 884/2129 [00:18<00:22, 54.33it/s]
 42%|████▏     | 890/2129 [00:18<00:22, 55.42it/s]
 42%|████▏     | 897/2129 [00:18<00:21, 58.41it/s]
 43%|████▎     | 905/2129 [00:18<00:19, 63.38it/s]
 43%|████▎     | 912/2129 [00:18<00:20, 58.82it/s]
 43%|████▎     | 918/2129 [00:18<00:20, 58.01it/s]
 43%|████▎     | 924/2129 [00:18<00:22, 54.17it/s]
 44%|████▎     | 930/2129 [00:18<00:23, 51.39it/s]
 44%|████▍     | 937/2129 [00:19<00:21, 55.73it/s]
 44%|████▍     | 943/2129 [00:19<00:25, 46.42it/s]
 45%|████▍     | 950/2129 [00:19<00:23, 49.68it/s]
 45%|████▍     | 957/2129 [00:19<00:21, 53.51it/s]
 45%|████▌     | 963/2129 [00:19<00:25, 45.83it/s]
 46%|████▌     | 970/2129 [00:19<00:22, 50.80it/s]
 46%|████▌     | 976/2129 [00:19<00:21, 52.76it/s]
 46%|████▌     | 982/2129 [00:19<00:21, 53.62it/s]
 46%|████▋     | 988/2129 [00:20<00:21, 52.11it/s]
 47%|████▋     | 995/2129 [00:20<00:20, 55.23it/s]
 47%|████▋     | 1001/2129 [00:20<00:20, 53.82it/s]
 47%|████▋     | 1007/2129 [00:20<00:22, 50.94it/s]
 48%|████▊     | 1013/2129 [00:20<00:25, 43.82it/s]
 48%|████▊     | 1018/2129 [00:20<00:24, 45.21it/s]
 48%|████▊     | 1024/2129 [00:20<00:24, 44.63it/s]
 48%|████▊     | 1029/2129 [00:20<00:24, 44.71it/s]
 49%|████▊     | 1036/2129 [00:21<00:21, 50.41it/s]
 49%|████▉     | 1043/2129 [00:21<00:19, 54.97it/s]
 49%|████▉     | 1049/2129 [00:21<00:19, 55.89it/s]
 50%|████▉     | 1056/2129 [00:21<00:18, 56.73it/s]
 50%|████▉     | 1063/2129 [00:21<00:18, 59.13it/s]
 50%|█████     | 1070/2129 [00:21<00:18, 58.72it/s]
 51%|█████     | 1077/2129 [00:21<00:17, 60.36it/s]
 51%|█████     | 1084/2129 [00:21<00:18, 56.09it/s]
 51%|█████     | 1091/2129 [00:21<00:18, 57.42it/s]
 52%|█████▏    | 1097/2129 [00:22<00:17, 57.68it/s]
 52%|█████▏    | 1103/2129 [00:22<00:17, 57.02it/s]
 52%|█████▏    | 1110/2129 [00:22<00:16, 59.97it/s]
 52%|█████▏    | 1117/2129 [00:22<00:17, 59.37it/s]
 53%|█████▎    | 1123/2129 [00:22<00:17, 58.98it/s]
 53%|█████▎    | 1129/2129 [00:22<00:19, 52.26it/s]
 53%|█████▎    | 1135/2129 [00:22<00:18, 53.99it/s]
 54%|█████▎    | 1141/2129 [00:22<00:18, 54.43it/s]
 54%|█████▍    | 1148/2129 [00:22<00:17, 57.26it/s]
 54%|█████▍    | 1154/2129 [00:23<00:24, 39.34it/s]
 54%|█████▍    | 1159/2129 [00:23<00:23, 41.56it/s]
 55%|█████▍    | 1164/2129 [00:23<00:23, 40.34it/s]
 55%|█████▍    | 1170/2129 [00:23<00:22, 43.13it/s]
 55%|█████▌    | 1176/2129 [00:23<00:21, 45.19it/s]
 55%|█████▌    | 1181/2129 [00:23<00:22, 41.81it/s]
 56%|█████▌    | 1186/2129 [00:23<00:21, 43.57it/s]
 56%|█████▌    | 1191/2129 [00:24<00:22, 41.49it/s]
 56%|█████▌    | 1196/2129 [00:24<00:22, 41.18it/s]
 56%|█████▋    | 1202/2129 [00:24<00:20, 44.43it/s]
 57%|█████▋    | 1209/2129 [00:24<00:18, 49.57it/s]
 57%|█████▋    | 1217/2129 [00:24<00:16, 56.56it/s]
 57%|█████▋    | 1223/2129 [00:24<00:16, 56.42it/s]
 58%|█████▊    | 1229/2129 [00:24<00:15, 56.32it/s]
 58%|█████▊    | 1236/2129 [00:24<00:14, 59.79it/s]
 58%|█████▊    | 1243/2129 [00:25<00:18, 46.98it/s]
 59%|█████▊    | 1249/2129 [00:25<00:19, 45.99it/s]
 59%|█████▉    | 1255/2129 [00:25<00:18, 47.70it/s]
 59%|█████▉    | 1262/2129 [00:25<00:16, 51.12it/s]
 60%|█████▉    | 1268/2129 [00:25<00:16, 53.23it/s]
 60%|█████▉    | 1275/2129 [00:25<00:15, 53.54it/s]
 60%|██████    | 1281/2129 [00:25<00:21, 39.83it/s]
 60%|██████    | 1286/2129 [00:26<00:21, 39.59it/s]
 61%|██████    | 1292/2129 [00:26<00:19, 43.66it/s]
 61%|██████    | 1298/2129 [00:26<00:18, 46.06it/s]
 61%|██████    | 1303/2129 [00:26<00:18, 44.38it/s]
 62%|██████▏   | 1310/2129 [00:26<00:16, 49.73it/s]
 62%|██████▏   | 1317/2129 [00:26<00:14, 54.40it/s]
 62%|██████▏   | 1323/2129 [00:26<00:14, 54.63it/s]
 62%|██████▏   | 1329/2129 [00:26<00:15, 52.94it/s]
 63%|██████▎   | 1335/2129 [00:27<00:16, 48.45it/s]
 63%|██████▎   | 1340/2129 [00:27<00:17, 46.40it/s]
 63%|██████▎   | 1345/2129 [00:27<00:18, 41.50it/s]
 64%|██████▎   | 1353/2129 [00:27<00:15, 49.26it/s]
 64%|██████▍   | 1359/2129 [00:27<00:15, 50.20it/s]
 64%|██████▍   | 1365/2129 [00:27<00:14, 51.91it/s]
 64%|██████▍   | 1371/2129 [00:27<00:14, 51.04it/s]
 65%|██████▍   | 1378/2129 [00:27<00:13, 54.43it/s]
 65%|██████▌   | 1384/2129 [00:27<00:14, 52.90it/s]
 65%|██████▌   | 1390/2129 [00:28<00:13, 53.21it/s]
 66%|██████▌   | 1396/2129 [00:28<00:13, 53.35it/s]
 66%|██████▌   | 1402/2129 [00:28<00:13, 54.94it/s]
 66%|██████▌   | 1410/2129 [00:28<00:12, 59.66it/s]
 67%|██████▋   | 1416/2129 [00:28<00:13, 52.48it/s]
 67%|██████▋   | 1422/2129 [00:28<00:13, 54.16it/s]
 67%|██████▋   | 1429/2129 [00:28<00:12, 57.23it/s]
 67%|██████▋   | 1435/2129 [00:28<00:12, 57.27it/s]
 68%|██████▊   | 1441/2129 [00:29<00:12, 53.83it/s]
 68%|██████▊   | 1447/2129 [00:29<00:12, 54.45it/s]
 68%|██████▊   | 1453/2129 [00:29<00:14, 47.75it/s]
 68%|██████▊   | 1458/2129 [00:29<00:14, 45.80it/s]
 69%|██████▊   | 1463/2129 [00:29<00:17, 38.81it/s]
 69%|██████▉   | 1469/2129 [00:29<00:15, 43.15it/s]
 69%|██████▉   | 1475/2129 [00:29<00:15, 42.81it/s]
 70%|██████▉   | 1480/2129 [00:29<00:15, 42.68it/s]
 70%|██████▉   | 1485/2129 [00:30<00:17, 37.44it/s]
 70%|███████   | 1492/2129 [00:30<00:14, 43.76it/s]
 70%|███████   | 1497/2129 [00:30<00:15, 41.42it/s]
 71%|███████   | 1504/2129 [00:30<00:13, 47.28it/s]
 71%|███████   | 1510/2129 [00:30<00:13, 46.93it/s]
 71%|███████   | 1515/2129 [00:30<00:15, 39.17it/s]
 71%|███████▏  | 1520/2129 [00:30<00:14, 40.78it/s]
 72%|███████▏  | 1526/2129 [00:31<00:13, 45.10it/s]
 72%|███████▏  | 1532/2129 [00:31<00:13, 43.77it/s]
 72%|███████▏  | 1537/2129 [00:31<00:13, 44.98it/s]
 73%|███████▎  | 1544/2129 [00:31<00:11, 50.52it/s]
 73%|███████▎  | 1551/2129 [00:31<00:10, 55.47it/s]
 73%|███████▎  | 1557/2129 [00:31<00:10, 56.11it/s]
 73%|███████▎  | 1563/2129 [00:31<00:10, 56.47it/s]
 74%|███████▎  | 1569/2129 [00:31<00:10, 54.19it/s]
 74%|███████▍  | 1576/2129 [00:31<00:09, 56.57it/s]
 74%|███████▍  | 1582/2129 [00:32<00:09, 57.20it/s]
 75%|███████▍  | 1588/2129 [00:32<00:10, 51.88it/s]
 75%|███████▍  | 1594/2129 [00:32<00:10, 51.07it/s]
 75%|███████▌  | 1600/2129 [00:32<00:10, 52.48it/s]
 75%|███████▌  | 1607/2129 [00:32<00:09, 56.55it/s]
 76%|███████▌  | 1613/2129 [00:32<00:10, 48.88it/s]
 76%|███████▌  | 1619/2129 [00:32<00:12, 40.81it/s]
 76%|███████▋  | 1624/2129 [00:32<00:11, 42.74it/s]
 77%|███████▋  | 1629/2129 [00:33<00:11, 43.64it/s]
 77%|███████▋  | 1636/2129 [00:33<00:09, 50.04it/s]
 77%|███████▋  | 1644/2129 [00:33<00:08, 56.37it/s]
 78%|███████▊  | 1650/2129 [00:33<00:09, 51.36it/s]
 78%|███████▊  | 1656/2129 [00:33<00:12, 39.12it/s]
 78%|███████▊  | 1661/2129 [00:33<00:11, 40.12it/s]
 78%|███████▊  | 1669/2129 [00:33<00:09, 47.36it/s]
 79%|███████▊  | 1675/2129 [00:34<00:09, 49.05it/s]
 79%|███████▉  | 1682/2129 [00:34<00:08, 52.86it/s]
 79%|███████▉  | 1689/2129 [00:34<00:08, 54.84it/s]
 80%|███████▉  | 1695/2129 [00:34<00:07, 56.06it/s]
 80%|███████▉  | 1701/2129 [00:34<00:07, 56.24it/s]
 80%|████████  | 1707/2129 [00:34<00:07, 56.16it/s]
 80%|████████  | 1713/2129 [00:34<00:09, 45.21it/s]
 81%|████████  | 1719/2129 [00:34<00:08, 47.09it/s]
 81%|████████  | 1725/2129 [00:34<00:08, 49.70it/s]
 81%|████████▏ | 1731/2129 [00:35<00:07, 51.58it/s]
 82%|████████▏ | 1738/2129 [00:35<00:07, 55.49it/s]
 82%|████████▏ | 1745/2129 [00:35<00:06, 59.29it/s]
 82%|████████▏ | 1752/2129 [00:35<00:06, 60.52it/s]
 83%|████████▎ | 1759/2129 [00:35<00:05, 62.71it/s]
 83%|████████▎ | 1766/2129 [00:35<00:05, 62.46it/s]
 83%|████████▎ | 1773/2129 [00:35<00:05, 60.34it/s]
 84%|████████▎ | 1780/2129 [00:35<00:05, 59.89it/s]
 84%|████████▍ | 1787/2129 [00:36<00:06, 51.64it/s]
 84%|████████▍ | 1793/2129 [00:36<00:06, 48.24it/s]
 84%|████████▍ | 1799/2129 [00:36<00:06, 47.73it/s]
 85%|████████▍ | 1804/2129 [00:36<00:08, 39.57it/s]
 85%|████████▌ | 1810/2129 [00:36<00:07, 43.36it/s]
 85%|████████▌ | 1816/2129 [00:36<00:06, 46.19it/s]
 86%|████████▌ | 1821/2129 [00:36<00:07, 43.18it/s]
 86%|████████▌ | 1826/2129 [00:37<00:08, 37.12it/s]
 86%|████████▌ | 1830/2129 [00:37<00:08, 35.69it/s]
 86%|████████▌ | 1835/2129 [00:37<00:08, 35.17it/s]
 87%|████████▋ | 1843/2129 [00:37<00:06, 44.26it/s]
 87%|████████▋ | 1851/2129 [00:37<00:05, 49.20it/s]
 87%|████████▋ | 1857/2129 [00:37<00:06, 43.32it/s]
 87%|████████▋ | 1862/2129 [00:37<00:06, 43.97it/s]
 88%|████████▊ | 1867/2129 [00:38<00:06, 39.11it/s]
 88%|████████▊ | 1873/2129 [00:38<00:05, 42.82it/s]
 88%|████████▊ | 1878/2129 [00:38<00:06, 37.77it/s]
 88%|████████▊ | 1884/2129 [00:38<00:05, 42.47it/s]
 89%|████████▊ | 1889/2129 [00:38<00:05, 42.21it/s]
 89%|████████▉ | 1896/2129 [00:38<00:04, 47.35it/s]
 89%|████████▉ | 1902/2129 [00:38<00:04, 49.17it/s]
 90%|████████▉ | 1909/2129 [00:38<00:04, 53.53it/s]
 90%|████████▉ | 1915/2129 [00:39<00:04, 47.37it/s]
 90%|█████████ | 1920/2129 [00:39<00:04, 47.25it/s]
 90%|█████████ | 1925/2129 [00:39<00:06, 33.75it/s]
 91%|█████████ | 1931/2129 [00:39<00:05, 38.20it/s]
 91%|█████████ | 1936/2129 [00:39<00:05, 37.73it/s]
 91%|█████████ | 1942/2129 [00:39<00:04, 41.47it/s]
 92%|█████████▏| 1949/2129 [00:39<00:03, 46.52it/s]
 92%|█████████▏| 1954/2129 [00:39<00:03, 46.45it/s]
 92%|█████████▏| 1959/2129 [00:40<00:03, 43.36it/s]
 92%|█████████▏| 1964/2129 [00:40<00:03, 44.02it/s]
 93%|█████████▎| 1970/2129 [00:40<00:03, 46.58it/s]
 93%|█████████▎| 1975/2129 [00:40<00:03, 40.81it/s]
 93%|█████████▎| 1980/2129 [00:40<00:03, 38.88it/s]
 93%|█████████▎| 1986/2129 [00:40<00:03, 42.99it/s]
 94%|█████████▎| 1991/2129 [00:40<00:03, 44.16it/s]
 94%|█████████▍| 1997/2129 [00:40<00:02, 48.26it/s]
 94%|█████████▍| 2002/2129 [00:41<00:02, 46.83it/s]
 94%|█████████▍| 2008/2129 [00:41<00:02, 50.26it/s]
 95%|█████████▍| 2014/2129 [00:41<00:02, 51.26it/s]
 95%|█████████▍| 2020/2129 [00:41<00:02, 52.52it/s]
 95%|█████████▌| 2026/2129 [00:41<00:02, 49.12it/s]
 95%|█████████▌| 2032/2129 [00:41<00:02, 38.70it/s]
 96%|█████████▌| 2037/2129 [00:41<00:02, 40.27it/s]
 96%|█████████▌| 2042/2129 [00:42<00:02, 38.42it/s]
 96%|█████████▌| 2047/2129 [00:42<00:02, 37.06it/s]
 96%|█████████▋| 2051/2129 [00:42<00:02, 34.56it/s]
 97%|█████████▋| 2058/2129 [00:42<00:01, 42.38it/s]
 97%|█████████▋| 2067/2129 [00:42<00:01, 53.18it/s]
 97%|█████████▋| 2073/2129 [00:42<00:01, 54.09it/s]
 98%|█████████▊| 2079/2129 [00:42<00:00, 55.10it/s]
 98%|█████████▊| 2086/2129 [00:42<00:00, 58.97it/s]
 98%|█████████▊| 2093/2129 [00:42<00:00, 61.77it/s]
 99%|█████████▊| 2100/2129 [00:43<00:00, 60.82it/s]
 99%|█████████▉| 2108/2129 [00:43<00:00, 63.21it/s]
 99%|█████████▉| 2115/2129 [00:43<00:00, 58.74it/s]
100%|██████████| 2129/2129 [00:43<00:00, 48.96it/s]
/kaggle/working/PRAGA/clustering_utils.py:173: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return log_Hastings_ratio_split(1.0, torch.tensor(N_k_1), torch.tensor(N_k_2), log_ll_k1, log_ll_k2, log_ll_k, split_prob=0.1)

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 331.55it/s]
 67%|██████▋   | 201/300 [09:05<23:03, 13.97s/it]

[[np.int64(0), False, 5], [np.int64(1), False, 4], [np.int64(2), False, 12], [np.int64(3), False, 13], [np.int64(4), False, 7], [np.int64(5), False, 11], [np.int64(6), False, 10], [np.int64(7), False, 12], [np.int64(8), False, 5], [np.int64(9), False, 3], [np.int64(10), False, 11], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8555, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [09:05<16:02,  9.82s/it]

tensor(11.7817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0069, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1885, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:06<05:27,  3.45s/it]

tensor(11.7988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3720, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8218, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5735, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [09:06<02:42,  1.75s/it]

tensor(11.8531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7406, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8514, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:06<01:23,  1.09it/s]

tensor(11.9069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8613, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8314, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:06<00:45,  1.96it/s]

tensor(11.8964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8386, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8738, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8895, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:07<00:27,  3.21it/s]

tensor(11.8530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9819, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [09:07<00:18,  4.67it/s]

tensor(11.8461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0213, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0504, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [09:07<00:15,  5.37it/s]

tensor(11.8614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0756, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0963, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:07<00:11,  6.95it/s]

tensor(11.8323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1024, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0958, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [09:08<00:10,  7.29it/s]

tensor(11.8059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0881, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8009, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0918, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [09:08<00:10,  7.52it/s]

tensor(11.7964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1028, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1219, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:08<00:09,  7.89it/s]

tensor(11.7838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1544, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:08<00:09,  8.08it/s]

tensor(11.7779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1665, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1806, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:09<00:08,  8.16it/s]

tensor(11.7758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1930, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7722, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2038, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [09:09<00:08,  8.18it/s]

tensor(11.7685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2176, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2272, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [09:09<00:08,  8.19it/s]

tensor(11.7610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2366, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2458, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:09<00:07,  8.21it/s]

tensor(11.7539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2448, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2489, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [09:10<00:07,  8.08it/s]

tensor(11.7500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2546, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2621, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:10<00:07,  8.26it/s]

tensor(11.7455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2705, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2778, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [09:10<00:07,  8.25it/s]

tensor(11.7406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2873, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7380, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2925, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:10<00:06,  8.22it/s]

tensor(11.7360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2977, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3036, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [09:10<00:06,  8.23it/s]

tensor(11.7334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3105, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7317, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3142, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [09:11<00:06,  8.22it/s]

tensor(11.7300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3187, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3218, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [09:11<00:06,  8.16it/s]

tensor(11.7268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3294, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3351, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [09:11<00:06,  8.23it/s]

tensor(11.7242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3396, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([311, 166, 115,  82, 186, 188, 146, 134, 134, 235, 117, 127,  88, 100])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:23, 25.58it/s]
  1%|          | 11/2129 [00:00<00:39, 53.71it/s]
  1%|          | 17/2129 [00:00<00:46, 45.54it/s]
  1%|          | 24/2129 [00:00<00:39, 52.96it/s]
  1%|▏         | 30/2129 [00:00<00:38, 54.61it/s]
  2%|▏         | 36/2129 [00:00<00:49, 42.61it/s]
  2%|▏         | 42/2129 [00:00<00:45, 45.76it/s]
  2%|▏         | 48/2129 [00:01<00:42, 49.24it/s]
  3%|▎         | 54/2129 [00:01<00:52, 39.72it/s]
  3%|▎         | 61/2129 [00:01<00:45, 45.60it/s]
  3%|▎         | 67/2129 [00:01<01:35, 21.58it/s]
  3%|▎         | 71/2129 [00:02<01:30, 22.73it/s]
  4%|▎         | 76/2129 [00:02<01:16, 26.70it/s]
  4%|▍         | 82/2129 [00:02<01:03, 32.01it/s]
  4%|▍         | 88/2129 [00:02<00:54, 37.55it/s]
  4%|▍         | 95/2129 [00:02<00:46, 43.98it/s]
  5%|▍         | 102/2129 [00:02<00:40, 49.53it/s]
  5%|▌         | 109/2129 [00:02<00:37, 53.20it/s]
  5%|▌         | 116/2129 [00:02<00:35, 56.41it/s]
  6%|▌         | 123/2129 [00:02<00:36, 55.28it/s]
  6%|▌         | 129/2129 [00:03<00:36, 55.55it/s]
  6%|▋         | 135/2129 [00:03<00:35, 55.79it/s]
  7%|▋         | 141/2129 [00:03<00:43, 46.18it/s]
  7%|▋         | 146/2129 [00:03<00:43, 45.50it/s]
  7%|▋         | 151/2129 [00:03<00:45, 43.16it/s]
  7%|▋         | 157/2129 [00:04<01:18, 25.15it/s]
  8%|▊         | 161/2129 [00:04<01:17, 25.34it/s]
  8%|▊         | 168/2129 [00:04<01:00, 32.33it/s]
  8%|▊         | 173/2129 [00:04<00:54, 35.56it/s]
  8%|▊         | 178/2129 [00:04<01:35, 20.34it/s]
  9%|▊         | 182/2129 [00:05<01:40, 19.29it/s]
  9%|▊         | 185/2129 [00:05<02:24, 13.47it/s]
  9%|▉         | 188/2129 [00:05<02:06, 15.35it/s]
  9%|▉         | 196/2129 [00:05<01:20, 23.97it/s]
 10%|▉         | 203/2129 [00:06<01:02, 30.94it/s]
 10%|▉         | 209/2129 [00:06<00:52, 36.36it/s]
 10%|█         | 217/2129 [00:06<00:42, 45.38it/s]
 11%|█         | 224/2129 [00:06<00:37, 50.22it/s]
 11%|█         | 231/2129 [00:06<00:35, 53.02it/s]
 11%|█         | 238/2129 [00:06<00:53, 35.57it/s]
 11%|█▏        | 243/2129 [00:07<01:38, 19.14it/s]
 12%|█▏        | 250/2129 [00:07<01:50, 16.99it/s]
 12%|█▏        | 253/2129 [00:08<02:28, 12.63it/s]
 12%|█▏        | 256/2129 [00:08<02:12, 14.11it/s]
 12%|█▏        | 259/2129 [00:09<02:53, 10.75it/s]
 12%|█▏        | 261/2129 [00:09<03:37,  8.59it/s]
 12%|█▏        | 264/2129 [00:09<02:58, 10.43it/s]
 13%|█▎        | 271/2129 [00:09<01:48, 17.16it/s]
 13%|█▎        | 278/2129 [00:09<01:15, 24.57it/s]
 13%|█▎        | 283/2129 [00:10<01:08, 26.89it/s]
 14%|█▎        | 288/2129 [00:10<01:55, 15.95it/s]
 14%|█▎        | 292/2129 [00:11<02:30, 12.24it/s]
 14%|█▍        | 295/2129 [00:11<02:15, 13.51it/s]
 14%|█▍        | 303/2129 [00:11<01:25, 21.46it/s]
 14%|█▍        | 307/2129 [00:12<02:05, 14.46it/s]
 15%|█▍        | 312/2129 [00:12<02:23, 12.64it/s]
 15%|█▍        | 315/2129 [00:12<02:09, 14.03it/s]
 15%|█▌        | 322/2129 [00:12<01:27, 20.73it/s]
 15%|█▌        | 326/2129 [00:13<02:13, 13.49it/s]
 16%|█▌        | 332/2129 [00:13<01:39, 18.11it/s]
 16%|█▌        | 336/2129 [00:13<01:33, 19.16it/s]
 16%|█▌        | 341/2129 [00:13<01:16, 23.42it/s]
 16%|█▌        | 345/2129 [00:14<02:25, 12.25it/s]
 16%|█▋        | 349/2129 [00:15<02:53, 10.26it/s]
 17%|█▋        | 352/2129 [00:15<02:30, 11.82it/s]
 17%|█▋        | 358/2129 [00:15<01:44, 16.95it/s]
 17%|█▋        | 362/2129 [00:16<03:15,  9.04it/s]
 17%|█▋        | 365/2129 [00:16<02:50, 10.34it/s]
 18%|█▊        | 373/2129 [00:16<02:08, 13.67it/s]
 18%|█▊        | 376/2129 [00:16<02:00, 14.59it/s]
 18%|█▊        | 382/2129 [00:17<01:27, 19.98it/s]
 18%|█▊        | 386/2129 [00:17<01:19, 22.04it/s]
 18%|█▊        | 391/2129 [00:17<01:06, 25.98it/s]
 19%|█▊        | 397/2129 [00:17<00:53, 32.23it/s]
 19%|█▉        | 402/2129 [00:18<01:40, 17.12it/s]
 19%|█▉        | 406/2129 [00:18<01:28, 19.55it/s]
 19%|█▉        | 411/2129 [00:18<01:11, 24.07it/s]
 19%|█▉        | 415/2129 [00:18<01:05, 26.17it/s]
 20%|█▉        | 420/2129 [00:18<00:59, 28.51it/s]
 20%|█▉        | 424/2129 [00:18<00:55, 30.60it/s]
 20%|██        | 428/2129 [00:18<00:54, 31.21it/s]
 20%|██        | 432/2129 [00:19<01:51, 15.25it/s]
 20%|██        | 435/2129 [00:19<02:38, 10.69it/s]
 21%|██        | 438/2129 [00:20<03:23,  8.32it/s]
 21%|██        | 440/2129 [00:20<03:40,  7.66it/s]
 21%|██        | 443/2129 [00:21<02:56,  9.54it/s]
 21%|██        | 448/2129 [00:21<02:04, 13.54it/s]
 21%|██▏       | 453/2129 [00:21<01:33, 18.02it/s]
 21%|██▏       | 457/2129 [00:21<01:42, 16.32it/s]
 22%|██▏       | 460/2129 [00:22<02:15, 12.30it/s]
 22%|██▏       | 465/2129 [00:22<01:38, 16.91it/s]
 22%|██▏       | 468/2129 [00:22<02:37, 10.55it/s]
 22%|██▏       | 471/2129 [00:22<02:13, 12.41it/s]
 22%|██▏       | 477/2129 [00:22<01:33, 17.74it/s]
 23%|██▎       | 482/2129 [00:23<01:13, 22.41it/s]
 23%|██▎       | 486/2129 [00:23<01:07, 24.19it/s]
 23%|██▎       | 490/2129 [00:23<02:06, 12.92it/s]
 23%|██▎       | 493/2129 [00:24<01:53, 14.48it/s]
 23%|██▎       | 499/2129 [00:24<01:19, 20.40it/s]
 24%|██▎       | 503/2129 [00:24<02:02, 13.26it/s]
 24%|██▍       | 508/2129 [00:25<02:21, 11.48it/s]
 24%|██▍       | 511/2129 [00:25<02:07, 12.70it/s]
 24%|██▍       | 515/2129 [00:25<02:32, 10.59it/s]
 24%|██▍       | 517/2129 [00:26<03:27,  7.79it/s]
 24%|██▍       | 519/2129 [00:26<03:05,  8.67it/s]
 24%|██▍       | 521/2129 [00:27<04:05,  6.54it/s]
 25%|██▍       | 523/2129 [00:27<04:20,  6.16it/s]
 25%|██▍       | 525/2129 [00:27<03:41,  7.25it/s]
 25%|██▍       | 528/2129 [00:28<03:40,  7.26it/s]
 25%|██▍       | 530/2129 [00:28<04:08,  6.44it/s]
 25%|██▍       | 532/2129 [00:28<03:25,  7.76it/s]
 25%|██▌       | 535/2129 [00:29<03:37,  7.34it/s]
 25%|██▌       | 536/2129 [00:29<04:32,  5.85it/s]
 25%|██▌       | 538/2129 [00:29<03:36,  7.34it/s]
 25%|██▌       | 540/2129 [00:29<03:01,  8.77it/s]
 26%|██▌       | 543/2129 [00:30<03:23,  7.81it/s]
 26%|██▌       | 545/2129 [00:30<02:56,  9.00it/s]
 26%|██▌       | 548/2129 [00:30<02:12, 11.89it/s]
 26%|██▌       | 552/2129 [00:30<01:36, 16.42it/s]
 26%|██▌       | 557/2129 [00:30<01:49, 14.37it/s]
 26%|██▋       | 559/2129 [00:31<01:47, 14.67it/s]
 26%|██▋       | 561/2129 [00:31<01:44, 14.98it/s]
 26%|██▋       | 563/2129 [00:31<02:49,  9.25it/s]
 27%|██▋       | 565/2129 [00:32<03:46,  6.91it/s]
 27%|██▋       | 567/2129 [00:32<04:41,  5.55it/s]
 27%|██▋       | 569/2129 [00:32<03:48,  6.83it/s]
 27%|██▋       | 571/2129 [00:33<04:40,  5.56it/s]
 27%|██▋       | 573/2129 [00:33<03:48,  6.81it/s]
 27%|██▋       | 579/2129 [00:33<01:56, 13.25it/s]
 27%|██▋       | 585/2129 [00:33<01:18, 19.77it/s]
 28%|██▊       | 591/2129 [00:33<00:59, 26.06it/s]
 28%|██▊       | 596/2129 [00:33<00:50, 30.28it/s]
 28%|██▊       | 602/2129 [00:34<00:42, 36.32it/s]
 29%|██▊       | 607/2129 [00:34<00:57, 26.60it/s]
 29%|██▊       | 611/2129 [00:34<01:29, 17.01it/s]
 29%|██▉       | 614/2129 [00:34<01:22, 18.37it/s]
 29%|██▉       | 619/2129 [00:35<01:04, 23.29it/s]
 29%|██▉       | 625/2129 [00:35<00:51, 29.27it/s]
 30%|██▉       | 629/2129 [00:35<00:49, 30.31it/s]
 30%|██▉       | 635/2129 [00:35<00:40, 36.58it/s]
 30%|███       | 640/2129 [00:36<01:31, 16.22it/s]
 30%|███       | 644/2129 [00:36<01:19, 18.63it/s]
 31%|███       | 650/2129 [00:36<01:01, 23.99it/s]
 31%|███       | 654/2129 [00:36<01:34, 15.61it/s]
 31%|███       | 658/2129 [00:36<01:20, 18.20it/s]
 31%|███       | 663/2129 [00:37<01:42, 14.30it/s]
 31%|███▏      | 666/2129 [00:37<01:34, 15.49it/s]
 32%|███▏      | 672/2129 [00:37<01:09, 21.04it/s]
 32%|███▏      | 677/2129 [00:37<00:56, 25.55it/s]
 32%|███▏      | 681/2129 [00:38<00:56, 25.46it/s]
 32%|███▏      | 685/2129 [00:38<02:00, 12.02it/s]
 32%|███▏      | 688/2129 [00:39<02:07, 11.34it/s]
 32%|███▏      | 691/2129 [00:39<01:55, 12.46it/s]
 33%|███▎      | 693/2129 [00:39<01:47, 13.34it/s]
 33%|███▎      | 696/2129 [00:39<02:26,  9.77it/s]
 33%|███▎      | 699/2129 [00:40<02:01, 11.73it/s]
 33%|███▎      | 703/2129 [00:40<02:23,  9.91it/s]
 33%|███▎      | 705/2129 [00:41<03:06,  7.62it/s]
 33%|███▎      | 708/2129 [00:41<03:28,  6.82it/s]
 33%|███▎      | 711/2129 [00:41<02:43,  8.66it/s]
 33%|███▎      | 713/2129 [00:42<03:33,  6.64it/s]
 34%|███▎      | 716/2129 [00:42<02:39,  8.84it/s]
 34%|███▍      | 719/2129 [00:42<02:54,  8.06it/s]
 34%|███▍      | 721/2129 [00:42<02:42,  8.67it/s]
 34%|███▍      | 723/2129 [00:43<03:22,  6.94it/s]
 34%|███▍      | 725/2129 [00:44<04:25,  5.29it/s]
 34%|███▍      | 727/2129 [00:44<04:13,  5.52it/s]
 34%|███▍      | 728/2129 [00:44<04:24,  5.30it/s]
 34%|███▍      | 730/2129 [00:44<03:24,  6.84it/s]
 34%|███▍      | 733/2129 [00:45<03:19,  7.01it/s]
 35%|███▍      | 736/2129 [00:45<02:27,  9.43it/s]
 35%|███▍      | 739/2129 [00:45<02:11, 10.58it/s]
 35%|███▍      | 742/2129 [00:45<01:47, 12.90it/s]
 35%|███▌      | 748/2129 [00:45<01:06, 20.73it/s]
 35%|███▌      | 751/2129 [00:46<01:49, 12.62it/s]
 35%|███▌      | 754/2129 [00:47<03:20,  6.85it/s]
 36%|███▌      | 756/2129 [00:47<03:54,  5.86it/s]
 36%|███▌      | 758/2129 [00:48<04:27,  5.12it/s]
 36%|███▌      | 760/2129 [00:48<03:39,  6.24it/s]
 36%|███▌      | 766/2129 [00:48<02:50,  7.98it/s]
 36%|███▌      | 768/2129 [00:49<02:30,  9.04it/s]
 36%|███▋      | 773/2129 [00:49<01:40, 13.47it/s]
 36%|███▋      | 776/2129 [00:49<02:38,  8.53it/s]
 37%|███▋      | 779/2129 [00:50<02:08, 10.53it/s]
 37%|███▋      | 785/2129 [00:50<01:40, 13.33it/s]
 37%|███▋      | 788/2129 [00:50<01:54, 11.66it/s]
 37%|███▋      | 790/2129 [00:50<01:48, 12.37it/s]
 37%|███▋      | 794/2129 [00:50<01:24, 15.72it/s]
 37%|███▋      | 797/2129 [00:52<03:14,  6.84it/s]
 38%|███▊      | 799/2129 [00:52<03:50,  5.77it/s]
 38%|███▊      | 801/2129 [00:52<03:16,  6.77it/s]
 38%|███▊      | 806/2129 [00:52<02:01, 10.87it/s]
 38%|███▊      | 811/2129 [00:52<01:24, 15.54it/s]
 38%|███▊      | 816/2129 [00:53<01:04, 20.48it/s]
 39%|███▊      | 820/2129 [00:54<02:29,  8.73it/s]
 39%|███▊      | 823/2129 [00:54<02:05, 10.40it/s]
 39%|███▉      | 828/2129 [00:54<01:30, 14.44it/s]
 39%|███▉      | 833/2129 [00:54<01:08, 18.84it/s]
 39%|███▉      | 839/2129 [00:54<00:51, 24.98it/s]
 40%|███▉      | 844/2129 [00:55<01:50, 11.59it/s]
 40%|███▉      | 848/2129 [00:56<02:16,  9.38it/s]
 40%|███▉      | 851/2129 [00:56<01:57, 10.92it/s]
 40%|████      | 856/2129 [00:56<01:25, 14.86it/s]
 40%|████      | 862/2129 [00:56<01:02, 20.17it/s]
 41%|████      | 866/2129 [00:56<01:06, 19.07it/s]
 41%|████      | 870/2129 [00:57<01:12, 17.44it/s]
 41%|████      | 873/2129 [00:57<01:06, 18.84it/s]
 41%|████▏     | 879/2129 [00:57<00:49, 25.12it/s]
 41%|████▏     | 883/2129 [00:57<01:01, 20.12it/s]
 42%|████▏     | 886/2129 [00:58<01:36, 12.92it/s]
 42%|████▏     | 889/2129 [00:58<02:11,  9.45it/s]
 42%|████▏     | 891/2129 [00:59<02:27,  8.38it/s]
 42%|████▏     | 893/2129 [00:59<02:17,  8.97it/s]
 42%|████▏     | 895/2129 [00:59<02:15,  9.11it/s]
 42%|████▏     | 897/2129 [00:59<02:05,  9.82it/s]
 42%|████▏     | 899/2129 [01:00<02:59,  6.84it/s]
 42%|████▏     | 903/2129 [01:00<02:09,  9.47it/s]
 43%|████▎     | 905/2129 [01:00<02:00, 10.19it/s]
 43%|████▎     | 907/2129 [01:00<02:08,  9.54it/s]
 43%|████▎     | 909/2129 [01:01<02:29,  8.17it/s]
 43%|████▎     | 911/2129 [01:01<02:38,  7.71it/s]
 43%|████▎     | 912/2129 [01:01<03:01,  6.69it/s]
 43%|████▎     | 914/2129 [01:02<03:30,  5.76it/s]
 43%|████▎     | 917/2129 [01:02<02:21,  8.55it/s]
 43%|████▎     | 924/2129 [01:02<01:10, 17.11it/s]
 44%|████▎     | 927/2129 [01:02<01:05, 18.31it/s]
 44%|████▎     | 930/2129 [01:02<01:01, 19.40it/s]
 44%|████▍     | 933/2129 [01:02<01:30, 13.16it/s]
 44%|████▍     | 936/2129 [01:03<01:23, 14.35it/s]
 44%|████▍     | 938/2129 [01:03<02:16,  8.75it/s]
 44%|████▍     | 940/2129 [01:03<02:04,  9.57it/s]
 44%|████▍     | 943/2129 [01:03<01:37, 12.21it/s]
 44%|████▍     | 945/2129 [01:04<02:23,  8.26it/s]
 45%|████▍     | 948/2129 [01:04<01:52, 10.51it/s]
 45%|████▍     | 950/2129 [01:04<02:02,  9.64it/s]
 45%|████▍     | 952/2129 [01:04<01:46, 11.06it/s]
 45%|████▍     | 955/2129 [01:05<02:21,  8.29it/s]
 45%|████▍     | 957/2129 [01:05<02:01,  9.68it/s]
 45%|████▌     | 959/2129 [01:06<02:53,  6.73it/s]
 45%|████▌     | 961/2129 [01:06<03:34,  5.44it/s]
 45%|████▌     | 963/2129 [01:07<03:56,  4.92it/s]
 45%|████▌     | 966/2129 [01:07<02:46,  7.01it/s]
 46%|████▌     | 970/2129 [01:07<02:29,  7.77it/s]
 46%|████▌     | 973/2129 [01:08<02:51,  6.72it/s]
 46%|████▌     | 974/2129 [01:08<03:42,  5.19it/s]
 46%|████▌     | 976/2129 [01:08<03:01,  6.36it/s]
 46%|████▌     | 981/2129 [01:09<02:27,  7.80it/s]
 46%|████▌     | 984/2129 [01:09<01:56,  9.84it/s]
 47%|████▋     | 990/2129 [01:09<01:12, 15.77it/s]
 47%|████▋     | 993/2129 [01:09<01:24, 13.45it/s]
 47%|████▋     | 996/2129 [01:10<01:20, 14.06it/s]
 47%|████▋     | 1001/2129 [01:10<00:59, 18.98it/s]
 47%|████▋     | 1004/2129 [01:10<01:14, 15.16it/s]
 47%|████▋     | 1007/2129 [01:10<01:14, 15.02it/s]
 48%|████▊     | 1012/2129 [01:11<01:30, 12.29it/s]
 48%|████▊     | 1014/2129 [01:11<02:06,  8.82it/s]
 48%|████▊     | 1016/2129 [01:12<02:38,  7.03it/s]
 48%|████▊     | 1019/2129 [01:12<02:51,  6.49it/s]
 48%|████▊     | 1021/2129 [01:12<02:25,  7.61it/s]
 48%|████▊     | 1023/2129 [01:13<02:42,  6.79it/s]
 48%|████▊     | 1025/2129 [01:13<02:16,  8.11it/s]
 48%|████▊     | 1030/2129 [01:14<02:09,  8.51it/s]
 48%|████▊     | 1032/2129 [01:14<02:38,  6.90it/s]
 49%|████▊     | 1034/2129 [01:14<02:17,  7.99it/s]
 49%|████▉     | 1040/2129 [01:14<01:18, 13.85it/s]
 49%|████▉     | 1045/2129 [01:14<00:57, 18.92it/s]
 49%|████▉     | 1049/2129 [01:15<01:25, 12.64it/s]
 49%|████▉     | 1052/2129 [01:15<01:13, 14.66it/s]
 50%|████▉     | 1056/2129 [01:16<01:34, 11.31it/s]
 50%|████▉     | 1059/2129 [01:16<01:58,  9.03it/s]
 50%|████▉     | 1061/2129 [01:17<02:32,  7.01it/s]
 50%|████▉     | 1064/2129 [01:17<02:41,  6.59it/s]
 50%|█████     | 1066/2129 [01:17<02:20,  7.54it/s]
 50%|█████     | 1068/2129 [01:18<02:47,  6.34it/s]
 50%|█████     | 1070/2129 [01:18<02:18,  7.65it/s]
 50%|█████     | 1075/2129 [01:18<01:23, 12.66it/s]
 51%|█████     | 1079/2129 [01:18<01:03, 16.54it/s]
 51%|█████     | 1082/2129 [01:19<01:45,  9.97it/s]
 51%|█████     | 1085/2129 [01:19<02:05,  8.33it/s]
 51%|█████     | 1087/2129 [01:19<01:51,  9.38it/s]
 51%|█████▏    | 1093/2129 [01:19<01:06, 15.64it/s]
 51%|█████▏    | 1096/2129 [01:20<01:35, 10.78it/s]
 52%|█████▏    | 1100/2129 [01:20<01:13, 14.09it/s]
 52%|█████▏    | 1103/2129 [01:21<01:39, 10.36it/s]
 52%|█████▏    | 1106/2129 [01:21<01:22, 12.40it/s]
 52%|█████▏    | 1109/2129 [01:21<01:44,  9.78it/s]
 52%|█████▏    | 1112/2129 [01:21<01:25, 11.86it/s]
 52%|█████▏    | 1115/2129 [01:22<01:58,  8.52it/s]
 53%|█████▎    | 1118/2129 [01:22<02:10,  7.74it/s]
 53%|█████▎    | 1120/2129 [01:23<02:38,  6.36it/s]
 53%|█████▎    | 1122/2129 [01:23<02:13,  7.52it/s]
 53%|█████▎    | 1127/2129 [01:23<02:02,  8.18it/s]
 53%|█████▎    | 1130/2129 [01:24<02:15,  7.39it/s]
 53%|█████▎    | 1132/2129 [01:25<02:42,  6.12it/s]
 53%|█████▎    | 1133/2129 [01:25<03:20,  4.97it/s]
 53%|█████▎    | 1136/2129 [01:26<03:13,  5.12it/s]
 53%|█████▎    | 1138/2129 [01:26<02:36,  6.32it/s]
 54%|█████▎    | 1140/2129 [01:26<03:01,  5.44it/s]
 54%|█████▎    | 1142/2129 [01:27<03:18,  4.98it/s]
 54%|█████▍    | 1145/2129 [01:27<03:07,  5.25it/s]
 54%|█████▍    | 1146/2129 [01:28<03:50,  4.26it/s]
 54%|█████▍    | 1148/2129 [01:28<02:58,  5.48it/s]
 54%|█████▍    | 1153/2129 [01:28<01:36, 10.15it/s]
 54%|█████▍    | 1157/2129 [01:28<01:41,  9.61it/s]
 54%|█████▍    | 1159/2129 [01:29<02:14,  7.21it/s]
 55%|█████▍    | 1163/2129 [01:29<01:34, 10.27it/s]
 55%|█████▍    | 1168/2129 [01:29<01:03, 15.03it/s]
 55%|█████▌    | 1171/2129 [01:30<02:04,  7.71it/s]
 55%|█████▌    | 1174/2129 [01:30<01:40,  9.55it/s]
 55%|█████▌    | 1177/2129 [01:31<01:55,  8.26it/s]
 55%|█████▌    | 1179/2129 [01:31<02:20,  6.78it/s]
 55%|█████▌    | 1181/2129 [01:31<02:02,  7.76it/s]
 56%|█████▌    | 1183/2129 [01:32<02:29,  6.31it/s]
 56%|█████▌    | 1186/2129 [01:32<02:33,  6.14it/s]
 56%|█████▌    | 1189/2129 [01:32<01:53,  8.29it/s]
 56%|█████▌    | 1191/2129 [01:33<02:24,  6.48it/s]
 56%|█████▌    | 1195/2129 [01:33<02:09,  7.20it/s]
 56%|█████▌    | 1197/2129 [01:33<01:52,  8.31it/s]
 56%|█████▋    | 1202/2129 [01:34<01:10, 13.11it/s]
 57%|█████▋    | 1206/2129 [01:34<01:28, 10.48it/s]
 57%|█████▋    | 1210/2129 [01:34<01:08, 13.48it/s]
 57%|█████▋    | 1213/2129 [01:35<01:27, 10.47it/s]
 57%|█████▋    | 1215/2129 [01:35<01:21, 11.18it/s]
 57%|█████▋    | 1219/2129 [01:35<01:30, 10.01it/s]
 57%|█████▋    | 1221/2129 [01:36<02:39,  5.68it/s]
 57%|█████▋    | 1224/2129 [01:37<02:43,  5.55it/s]
 58%|█████▊    | 1227/2129 [01:37<02:02,  7.37it/s]
 58%|█████▊    | 1232/2129 [01:37<01:53,  7.89it/s]
 58%|█████▊    | 1234/2129 [01:38<02:14,  6.67it/s]
 58%|█████▊    | 1236/2129 [01:38<01:55,  7.76it/s]
 58%|█████▊    | 1242/2129 [01:38<01:07, 13.20it/s]
 58%|█████▊    | 1245/2129 [01:39<02:01,  7.28it/s]
 59%|█████▊    | 1247/2129 [01:40<02:20,  6.26it/s]
 59%|█████▊    | 1250/2129 [01:40<01:49,  8.02it/s]
 59%|█████▉    | 1253/2129 [01:40<01:57,  7.43it/s]
 59%|█████▉    | 1256/2129 [01:41<02:11,  6.64it/s]
 59%|█████▉    | 1259/2129 [01:41<01:41,  8.56it/s]
 59%|█████▉    | 1261/2129 [01:41<02:08,  6.76it/s]
 59%|█████▉    | 1263/2129 [01:42<02:14,  6.45it/s]
 59%|█████▉    | 1265/2129 [01:42<01:51,  7.75it/s]
 60%|█████▉    | 1267/2129 [01:42<01:34,  9.16it/s]
 60%|█████▉    | 1270/2129 [01:42<01:45,  8.11it/s]
 60%|█████▉    | 1272/2129 [01:43<01:32,  9.30it/s]
 60%|█████▉    | 1274/2129 [01:43<02:06,  6.77it/s]
 60%|█████▉    | 1276/2129 [01:44<02:31,  5.63it/s]
 60%|██████    | 1278/2129 [01:44<02:20,  6.06it/s]
 60%|██████    | 1279/2129 [01:44<02:44,  5.18it/s]
 60%|██████    | 1281/2129 [01:45<02:36,  5.43it/s]
 60%|██████    | 1283/2129 [01:45<02:36,  5.41it/s]
 60%|██████    | 1286/2129 [01:45<02:08,  6.56it/s]
 60%|██████    | 1288/2129 [01:45<01:49,  7.71it/s]
 61%|██████    | 1292/2129 [01:46<01:40,  8.30it/s]
 61%|██████    | 1294/2129 [01:46<01:39,  8.43it/s]
 61%|██████    | 1296/2129 [01:46<01:39,  8.39it/s]
 61%|██████    | 1297/2129 [01:46<01:53,  7.31it/s]
 61%|██████    | 1299/2129 [01:47<02:07,  6.51it/s]
 61%|██████    | 1301/2129 [01:47<02:17,  6.02it/s]
 61%|██████    | 1302/2129 [01:47<02:26,  5.63it/s]
 61%|██████    | 1304/2129 [01:48<02:25,  5.66it/s]
 61%|██████▏   | 1306/2129 [01:48<01:58,  6.95it/s]
 62%|██████▏   | 1310/2129 [01:48<01:12, 11.36it/s]
 62%|██████▏   | 1312/2129 [01:49<01:40,  8.09it/s]
 62%|██████▏   | 1316/2129 [01:49<01:07, 11.99it/s]
 62%|██████▏   | 1320/2129 [01:49<01:21,  9.97it/s]
 62%|██████▏   | 1324/2129 [01:49<01:03, 12.61it/s]
 62%|██████▏   | 1326/2129 [01:49<00:59, 13.49it/s]
 62%|██████▏   | 1328/2129 [01:50<01:09, 11.55it/s]
 63%|██████▎   | 1331/2129 [01:50<00:57, 13.81it/s]
 63%|██████▎   | 1333/2129 [01:50<00:54, 14.73it/s]
 63%|██████▎   | 1335/2129 [01:50<01:10, 11.23it/s]
 63%|██████▎   | 1338/2129 [01:50<00:56, 14.11it/s]
 63%|██████▎   | 1346/2129 [01:50<00:30, 25.91it/s]
 63%|██████▎   | 1350/2129 [01:51<01:00, 12.88it/s]
 64%|██████▎   | 1353/2129 [01:51<01:06, 11.67it/s]
 64%|██████▎   | 1356/2129 [01:52<01:17, 10.02it/s]
 64%|██████▍   | 1358/2129 [01:52<01:21,  9.50it/s]
 64%|██████▍   | 1360/2129 [01:52<01:28,  8.68it/s]
 64%|██████▍   | 1362/2129 [01:53<01:18,  9.75it/s]
 64%|██████▍   | 1364/2129 [01:53<01:47,  7.11it/s]
 64%|██████▍   | 1368/2129 [01:53<01:10, 10.73it/s]
 64%|██████▍   | 1370/2129 [01:54<01:40,  7.54it/s]
 64%|██████▍   | 1373/2129 [01:54<01:38,  7.70it/s]
 65%|██████▍   | 1376/2129 [01:54<01:19,  9.43it/s]
 65%|██████▍   | 1380/2129 [01:54<00:57, 13.13it/s]
 65%|██████▌   | 1384/2129 [01:55<00:54, 13.65it/s]
 65%|██████▌   | 1387/2129 [01:55<00:47, 15.76it/s]
 65%|██████▌   | 1390/2129 [01:55<00:54, 13.63it/s]
 65%|██████▌   | 1392/2129 [01:55<00:51, 14.39it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 333.25it/s]
 84%|████████▎ | 251/300 [12:13<44:43, 54.76s/it]

[[np.int64(0), False, 4], [np.int64(1), False, 11], [np.int64(2), False, 1], [np.int64(3), False, 11], [np.int64(5), False, 1], [np.int64(6), False, 10], [np.int64(7), False, 4], [np.int64(8), False, 4], [np.int64(9), False, 0], [np.int64(12), False, 7], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5344, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [12:14<30:42, 38.38s/it]

tensor(11.7252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6620, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7329, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7703, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [12:14<14:27, 18.87s/it]

tensor(11.7420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8545, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7501, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9299, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [12:14<06:49,  9.31s/it]

tensor(11.7542, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0460, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [12:14<03:14,  4.62s/it]

tensor(11.7464, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0445, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1056, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1482, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [12:15<01:04,  1.67s/it]

tensor(11.7307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0517, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1882, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0544, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2251, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [12:15<00:32,  1.14it/s]

tensor(11.7319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0565, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2465, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0578, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2522, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [12:15<00:23,  1.54it/s]

tensor(11.7431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0581, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2428, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0570, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2316, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [12:15<00:12,  2.62it/s]

tensor(11.7358, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2249, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0520, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2264, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [12:16<00:06,  4.75it/s]

tensor(11.7226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0489, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2318, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0457, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2392, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [12:16<00:05,  5.44it/s]

tensor(11.7252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0427, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2475, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0394, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2530, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [12:16<00:03,  7.05it/s]

tensor(11.7284, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2578, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2598, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [12:16<00:03,  7.36it/s]

tensor(11.7209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2617, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2512, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [12:17<00:03,  7.68it/s]

tensor(11.7110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2470, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7094, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2466, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [12:17<00:02,  8.01it/s]

tensor(11.7097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2521, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7104, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2514, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [12:17<00:02,  8.09it/s]

tensor(11.7099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2552, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2579, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [12:17<00:02,  8.18it/s]

tensor(11.7051, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2625, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2627, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [12:18<00:01,  8.23it/s]

tensor(11.7000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2615, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2636, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [12:18<00:01,  7.88it/s]

tensor(11.6980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2661, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2679, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [12:18<00:01,  8.02it/s]

tensor(11.6971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2697, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2704, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [12:18<00:01,  8.15it/s]

tensor(11.6941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2704, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2707, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [12:19<00:00,  8.19it/s]

tensor(11.6902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2741, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2779, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [12:19<00:00,  8.21it/s]

tensor(11.6878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2790, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2799, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [12:19<00:00,  8.21it/s]

tensor(11.6862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2821, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2834, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [12:19<00:00,  8.21it/s]

tensor(11.6848, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2855, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2863, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [12:19<00:00,  2.47s/it]

tensor(11.6829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2874, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0018427371978759766
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 3
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.519993347589
NMI         : 0.590708355059
Runtime     : 784.30 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed3

==============================================================================================================
PRAGA RUN | E18.5 | seed=4
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 1.818e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(15.6595, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4757, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6761, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2239, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:33,  8.76it/s]

tensor(15.6470, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1936, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6094, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3628, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5705, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7122, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 7/300 [00:00<00:30,  9.68it/s]

tensor(15.5122, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4530, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8819, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4092, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6718, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.69it/s]

tensor(15.3512, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5817, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3039, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5981, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:29,  9.84it/s]

tensor(15.2495, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7121, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2000, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9136, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1495, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1935, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:29,  9.60it/s]

tensor(15.0979, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5451, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0472, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9604, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:28,  9.84it/s]

tensor(14.9991, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9516, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9595, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9058, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5324, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:28,  9.88it/s]

tensor(14.8595, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1485, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8144, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8016, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7675, device='cuda:0', grad_fn=<AddBackward0>)

  7%|▋         | 21/300 [00:02<00:28,  9.77it/s]

tensor(2.4906, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7181, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2100, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:27,  9.89it/s]

tensor(14.6646, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9584, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6090, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7313, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:28,  9.75it/s]

tensor(14.5525, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5281, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4959, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3447, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:27,  9.87it/s]

tensor(14.4358, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1804, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3777, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0332, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:27,  9.89it/s]

tensor(14.3156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9012, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7830, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.72it/s]

tensor(14.1864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6770, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5828, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:27,  9.74it/s]

tensor(14.0537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4984, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4232, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:27,  9.78it/s]

tensor(13.9129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3565, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2973, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2454, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.88it/s]

tensor(13.7013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1992, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1595, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5623, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1246, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:26,  9.91it/s]

tensor(13.4965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0958, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4329, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0716, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:25,  9.89it/s]

tensor(13.3742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0540, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0424, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:25,  9.84it/s]

tensor(13.2705, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.69it/s]

tensor(13.1877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:05<00:25,  9.75it/s]

tensor(13.1098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.84it/s]

tensor(13.0307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:24,  9.85it/s]

tensor(12.9611, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:24,  9.83it/s]

tensor(12.9038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8796, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:24,  9.83it/s]

tensor(12.8571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:06<00:24,  9.75it/s]

tensor(12.8136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.89it/s]

tensor(12.7692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:23,  9.86it/s]

tensor(12.7035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:23,  9.84it/s]

tensor(12.6618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6413, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:07<00:24,  9.55it/s]

tensor(12.6218, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:23,  9.56it/s]

tensor(12.5840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:23,  9.69it/s]

tensor(12.5476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:23,  9.78it/s]

tensor(12.5129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 77/300 [00:07<00:23,  9.68it/s]

tensor(12.4800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:23,  9.56it/s]

tensor(12.4489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4338, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:08<00:22,  9.62it/s]

tensor(12.4193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:22,  9.59it/s]

tensor(12.3909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:21,  9.97it/s]

tensor(12.3629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3492, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3358, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:09<00:21,  9.74it/s]

tensor(12.3226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:21,  9.80it/s]

tensor(12.2967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.2844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:21,  9.56it/s]

tensor(12.2720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.2603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:21,  9.61it/s]

tensor(12.2487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.2371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:21,  9.70it/s]

tensor(12.2261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.2155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:10<00:20,  9.74it/s]

tensor(12.2052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.1951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:20,  9.80it/s]

tensor(12.1851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.1754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([263,  88,  79, 403,  67, 146, 135,  96,  95,  73, 225, 154,  58, 247])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:44, 20.43it/s]
  0%|          | 6/2129 [00:00<01:27, 24.20it/s]
  0%|          | 9/2129 [00:00<02:12, 16.03it/s]
  1%|          | 13/2129 [00:00<02:13, 15.86it/s]
  1%|          | 16/2129 [00:00<01:55, 18.24it/s]
  1%|          | 23/2129 [00:00<01:10, 29.77it/s]
  1%|▏         | 30/2129 [00:01<00:53, 39.48it/s]
  2%|▏         | 35/2129 [00:01<01:10, 29.80it/s]
  2%|▏         | 39/2129 [00:01<01:33, 22.46it/s]
  2%|▏         | 43/2129 [00:01<01:28, 23.67it/s]
  2%|▏         | 46/2129 [00:02<01:42, 20.41it/s]
  2%|▏         | 49/2129 [00:02<02:05, 16.58it/s]
  2%|▏         | 52/2129 [00:02<01:54, 18.07it/s]
  3%|▎         | 55/2129 [00:02<01:46, 19.43it/s]
  3%|▎         | 60/2129 [00:02<01:22, 25.21it/s]
  3%|▎         | 65/2129 [00:03<01:46, 19.32it/s]
  3%|▎         | 68/2129 [00:03<01:46, 19.33it/s]
  3%|▎         | 71/2129 [00:03<01:41, 20.33it/s]
  3%|▎         | 74/2129 [00:03<01:37, 21.13it/s]
  4%|▍         | 80/2129 [00:03<01:29, 22.99it/s]
  4%|▍         | 83/2129 [00:03<01:27, 23.32it/s]
  4%|▍         | 90/2129 [00:03<01:03, 31.97it/s]
  4%|▍         | 95/2129 [00:04<00:57, 35.26it/s]
  5%|▍         | 102/2129 [00:04<00:47, 42.51it/s]
  5%|▌         | 107/2129 [00:04<01:27, 23.11it/s]
  5%|▌         | 111/2129 [00:04<01:24, 23.87it/s]
  5%|▌         | 115/2129 [00:05<01:55, 17.47it/s]
  6%|▌         | 118/2129 [00:05<01:45, 19.00it/s]
  6%|▌         | 123/2129 [00:05<01:26, 23.30it/s]
  6%|▌         | 131/2129 [00:05<01:00, 32.99it/s]
  6%|▋         | 136/2129 [00:05<01:25, 23.21it/s]
  7%|▋         | 143/2129 [00:05<01:05, 30.38it/s]
  7%|▋         | 151/2129 [00:06<00:52, 37.80it/s]
  7%|▋         | 157/2129 [00:06<01:31, 21.62it/s]
  8%|▊         | 161/2129 [00:06<01:41, 19.29it/s]
  8%|▊         | 165/2129 [00:07<02:27, 13.28it/s]
  8%|▊         | 168/2129 [00:07<02:12, 14.76it/s]
  8%|▊         | 171/2129 [00:07<02:11, 14.88it/s]
  8%|▊         | 174/2129 [00:08<02:30, 13.03it/s]
  8%|▊         | 178/2129 [00:08<02:00, 16.20it/s]
  9%|▊         | 181/2129 [00:08<01:59, 16.31it/s]
  9%|▊         | 184/2129 [00:09<03:11, 10.17it/s]
  9%|▉         | 187/2129 [00:09<02:39, 12.19it/s]
  9%|▉         | 190/2129 [00:09<02:54, 11.09it/s]
  9%|▉         | 192/2129 [00:09<02:38, 12.20it/s]
  9%|▉         | 197/2129 [00:09<01:53, 17.07it/s]
  9%|▉         | 200/2129 [00:09<01:44, 18.48it/s]
 10%|▉         | 203/2129 [00:10<01:33, 20.50it/s]
 10%|▉         | 206/2129 [00:10<01:25, 22.43it/s]
 10%|▉         | 212/2129 [00:10<01:10, 27.18it/s]
 10%|█         | 215/2129 [00:10<01:21, 23.49it/s]
 10%|█         | 218/2129 [00:10<01:24, 22.57it/s]
 10%|█         | 223/2129 [00:10<01:27, 21.70it/s]
 11%|█         | 226/2129 [00:11<01:39, 19.15it/s]
 11%|█         | 229/2129 [00:11<01:41, 18.64it/s]
 11%|█         | 233/2129 [00:11<02:11, 14.45it/s]
 11%|█         | 235/2129 [00:11<02:20, 13.44it/s]
 11%|█         | 238/2129 [00:11<01:58, 15.99it/s]
 11%|█▏        | 243/2129 [00:12<01:26, 21.89it/s]
 12%|█▏        | 246/2129 [00:12<01:27, 21.56it/s]
 12%|█▏        | 249/2129 [00:12<02:00, 15.65it/s]
 12%|█▏        | 252/2129 [00:13<03:04, 10.18it/s]
 12%|█▏        | 255/2129 [00:13<02:34, 12.16it/s]
 12%|█▏        | 258/2129 [00:13<03:06, 10.04it/s]
 12%|█▏        | 260/2129 [00:13<02:52, 10.85it/s]
 12%|█▏        | 262/2129 [00:14<03:59,  7.78it/s]
 12%|█▏        | 265/2129 [00:14<03:11,  9.76it/s]
 13%|█▎        | 267/2129 [00:14<02:48, 11.03it/s]
 13%|█▎        | 270/2129 [00:14<02:12, 14.01it/s]
 13%|█▎        | 273/2129 [00:14<02:29, 12.41it/s]
 13%|█▎        | 275/2129 [00:15<04:16,  7.24it/s]
 13%|█▎        | 279/2129 [00:15<02:54, 10.63it/s]
 13%|█▎        | 283/2129 [00:15<02:08, 14.42it/s]
 13%|█▎        | 287/2129 [00:16<03:06,  9.87it/s]
 14%|█▎        | 290/2129 [00:16<02:36, 11.76it/s]
 14%|█▍        | 293/2129 [00:16<02:57, 10.33it/s]
 14%|█▍        | 295/2129 [00:17<02:46, 11.04it/s]
 14%|█▍        | 297/2129 [00:17<02:38, 11.59it/s]
 14%|█▍        | 299/2129 [00:17<02:22, 12.82it/s]
 14%|█▍        | 302/2129 [00:17<01:54, 15.94it/s]
 14%|█▍        | 305/2129 [00:17<02:49, 10.77it/s]
 14%|█▍        | 308/2129 [00:18<02:22, 12.80it/s]
 15%|█▍        | 310/2129 [00:18<03:04,  9.88it/s]
 15%|█▍        | 312/2129 [00:18<03:56,  7.67it/s]
 15%|█▍        | 314/2129 [00:19<04:50,  6.24it/s]
 15%|█▍        | 315/2129 [00:19<04:52,  6.21it/s]
 15%|█▍        | 317/2129 [00:19<04:00,  7.55it/s]
 15%|█▍        | 319/2129 [00:19<03:22,  8.93it/s]
 15%|█▌        | 321/2129 [00:19<02:55, 10.31it/s]
 15%|█▌        | 323/2129 [00:20<02:38, 11.38it/s]
 15%|█▌        | 325/2129 [00:20<03:10,  9.45it/s]
 15%|█▌        | 328/2129 [00:20<03:02,  9.84it/s]
 16%|█▌        | 331/2129 [00:20<02:28, 12.08it/s]
 16%|█▌        | 334/2129 [00:20<02:07, 14.07it/s]
 16%|█▌        | 337/2129 [00:21<01:50, 16.15it/s]
 16%|█▌        | 340/2129 [00:21<01:41, 17.63it/s]
 16%|█▌        | 342/2129 [00:21<03:34,  8.32it/s]
 16%|█▌        | 344/2129 [00:22<05:02,  5.90it/s]
 16%|█▋        | 347/2129 [00:22<03:41,  8.06it/s]
 16%|█▋        | 349/2129 [00:23<04:28,  6.63it/s]
 16%|█▋        | 351/2129 [00:23<04:04,  7.27it/s]
 17%|█▋        | 355/2129 [00:23<02:40, 11.03it/s]
 17%|█▋        | 358/2129 [00:23<02:13, 13.29it/s]
 17%|█▋        | 361/2129 [00:23<02:04, 14.16it/s]
 17%|█▋        | 363/2129 [00:23<02:34, 11.46it/s]
 17%|█▋        | 365/2129 [00:24<02:29, 11.82it/s]
 17%|█▋        | 367/2129 [00:24<02:23, 12.24it/s]
 17%|█▋        | 372/2129 [00:24<01:32, 19.02it/s]
 18%|█▊        | 375/2129 [00:24<02:04, 14.05it/s]
 18%|█▊        | 377/2129 [00:24<02:06, 13.89it/s]
 18%|█▊        | 380/2129 [00:24<01:56, 14.95it/s]
 18%|█▊        | 383/2129 [00:25<01:45, 16.58it/s]
 18%|█▊        | 385/2129 [00:25<02:06, 13.81it/s]
 18%|█▊        | 388/2129 [00:25<01:47, 16.22it/s]
 18%|█▊        | 392/2129 [00:25<01:35, 18.15it/s]
 19%|█▊        | 394/2129 [00:25<01:47, 16.13it/s]
 19%|█▊        | 396/2129 [00:25<01:48, 15.97it/s]
 19%|█▊        | 399/2129 [00:26<01:34, 18.27it/s]
 19%|█▉        | 401/2129 [00:26<02:45, 10.46it/s]
 19%|█▉        | 404/2129 [00:26<02:24, 11.93it/s]
 19%|█▉        | 406/2129 [00:27<03:30,  8.17it/s]
 19%|█▉        | 408/2129 [00:27<03:19,  8.61it/s]
 19%|█▉        | 412/2129 [00:27<02:20, 12.25it/s]
 19%|█▉        | 414/2129 [00:27<02:18, 12.36it/s]
 20%|█▉        | 416/2129 [00:28<02:52,  9.96it/s]
 20%|█▉        | 418/2129 [00:28<02:31, 11.30it/s]
 20%|█▉        | 422/2129 [00:28<01:55, 14.83it/s]
 20%|█▉        | 425/2129 [00:28<01:37, 17.47it/s]
 20%|██        | 430/2129 [00:29<02:39, 10.65it/s]
 20%|██        | 432/2129 [00:29<02:45, 10.23it/s]
 20%|██        | 434/2129 [00:29<04:13,  6.67it/s]
 20%|██        | 436/2129 [00:30<04:00,  7.05it/s]
 21%|██        | 439/2129 [00:30<04:48,  5.85it/s]
 21%|██        | 442/2129 [00:31<03:34,  7.85it/s]
 21%|██        | 444/2129 [00:31<03:33,  7.89it/s]
 21%|██        | 446/2129 [00:31<03:22,  8.31it/s]
 21%|██        | 449/2129 [00:31<02:39, 10.53it/s]
 21%|██        | 452/2129 [00:31<02:06, 13.27it/s]
 21%|██▏       | 454/2129 [00:31<02:22, 11.71it/s]
 21%|██▏       | 456/2129 [00:32<02:19, 12.01it/s]
 22%|██▏       | 458/2129 [00:32<04:19,  6.44it/s]
 22%|██▏       | 460/2129 [00:33<03:59,  6.96it/s]
 22%|██▏       | 465/2129 [00:33<02:17, 12.13it/s]
 22%|██▏       | 468/2129 [00:33<03:24,  8.11it/s]
 22%|██▏       | 471/2129 [00:33<02:45, 10.02it/s]
 22%|██▏       | 474/2129 [00:34<02:14, 12.32it/s]
 22%|██▏       | 477/2129 [00:34<03:30,  7.83it/s]
 22%|██▏       | 479/2129 [00:34<03:03,  8.99it/s]
 23%|██▎       | 481/2129 [00:35<03:01,  9.07it/s]
 23%|██▎       | 483/2129 [00:35<02:45,  9.94it/s]
 23%|██▎       | 486/2129 [00:35<02:33, 10.73it/s]
 23%|██▎       | 488/2129 [00:35<03:17,  8.32it/s]
 23%|██▎       | 490/2129 [00:36<02:55,  9.36it/s]
 23%|██▎       | 495/2129 [00:36<01:50, 14.84it/s]
 23%|██▎       | 498/2129 [00:36<01:34, 17.32it/s]
 24%|██▎       | 501/2129 [00:36<02:56,  9.22it/s]
 24%|██▎       | 504/2129 [00:37<02:19, 11.61it/s]
 24%|██▍       | 508/2129 [00:37<03:09,  8.57it/s]
 24%|██▍       | 510/2129 [00:38<04:25,  6.09it/s]
 24%|██▍       | 512/2129 [00:38<04:07,  6.52it/s]
 24%|██▍       | 517/2129 [00:39<04:08,  6.49it/s]
 24%|██▍       | 519/2129 [00:39<03:54,  6.86it/s]
 24%|██▍       | 521/2129 [00:40<05:13,  5.13it/s]
 25%|██▍       | 522/2129 [00:40<05:46,  4.64it/s]
 25%|██▍       | 525/2129 [00:40<04:12,  6.36it/s]
 25%|██▍       | 527/2129 [00:41<03:48,  7.01it/s]
 25%|██▍       | 529/2129 [00:41<03:20,  8.00it/s]
 25%|██▍       | 531/2129 [00:41<03:27,  7.72it/s]
 25%|██▌       | 533/2129 [00:41<02:52,  9.25it/s]
 25%|██▌       | 535/2129 [00:42<03:34,  7.42it/s]
 25%|██▌       | 536/2129 [00:42<03:30,  7.57it/s]
 25%|██▌       | 538/2129 [00:42<02:52,  9.22it/s]
 25%|██▌       | 541/2129 [00:42<02:10, 12.19it/s]
 26%|██▌       | 543/2129 [00:42<02:56,  8.98it/s]
 26%|██▌       | 545/2129 [00:43<03:12,  8.21it/s]
 26%|██▌       | 547/2129 [00:43<03:00,  8.75it/s]
 26%|██▌       | 549/2129 [00:43<03:03,  8.61it/s]
 26%|██▌       | 551/2129 [00:43<03:05,  8.50it/s]
 26%|██▌       | 554/2129 [00:43<02:25, 10.84it/s]
 26%|██▌       | 557/2129 [00:44<03:42,  7.05it/s]
 26%|██▋       | 559/2129 [00:44<03:24,  7.69it/s]
 26%|██▋       | 561/2129 [00:44<02:55,  8.94it/s]
 26%|██▋       | 563/2129 [00:45<02:44,  9.52it/s]
 27%|██▋       | 565/2129 [00:45<02:55,  8.91it/s]
 27%|██▋       | 567/2129 [00:45<02:48,  9.28it/s]
 27%|██▋       | 569/2129 [00:45<02:40,  9.75it/s]
 27%|██▋       | 571/2129 [00:46<03:24,  7.61it/s]
 27%|██▋       | 573/2129 [00:46<03:24,  7.60it/s]
 27%|██▋       | 574/2129 [00:46<03:16,  7.90it/s]
 27%|██▋       | 576/2129 [00:46<02:41,  9.64it/s]
 27%|██▋       | 578/2129 [00:46<02:58,  8.71it/s]
 27%|██▋       | 580/2129 [00:46<02:28, 10.44it/s]
 27%|██▋       | 582/2129 [00:47<02:35,  9.92it/s]
 27%|██▋       | 584/2129 [00:47<02:26, 10.56it/s]
 28%|██▊       | 587/2129 [00:47<02:00, 12.79it/s]
 28%|██▊       | 589/2129 [00:47<02:53,  8.88it/s]
 28%|██▊       | 591/2129 [00:48<02:38,  9.67it/s]
 28%|██▊       | 595/2129 [00:48<01:46, 14.37it/s]
 28%|██▊       | 598/2129 [00:48<01:31, 16.72it/s]
 28%|██▊       | 601/2129 [00:48<01:40, 15.17it/s]
 28%|██▊       | 603/2129 [00:48<02:16, 11.15it/s]
 28%|██▊       | 605/2129 [00:49<02:04, 12.26it/s]
 29%|██▊       | 610/2129 [00:49<01:54, 13.25it/s]
 29%|██▉       | 613/2129 [00:49<01:38, 15.43it/s]
 29%|██▉       | 615/2129 [00:49<01:46, 14.20it/s]
 29%|██▉       | 618/2129 [00:49<01:44, 14.51it/s]
 29%|██▉       | 621/2129 [00:50<01:35, 15.83it/s]
 29%|██▉       | 623/2129 [00:50<01:43, 14.58it/s]
 29%|██▉       | 626/2129 [00:50<01:55, 13.01it/s]
 29%|██▉       | 628/2129 [00:50<02:12, 11.33it/s]
 30%|██▉       | 631/2129 [00:50<02:09, 11.57it/s]
 30%|██▉       | 633/2129 [00:51<02:40,  9.32it/s]
 30%|██▉       | 635/2129 [00:51<02:21, 10.54it/s]
 30%|██▉       | 637/2129 [00:51<03:00,  8.27it/s]
 30%|███       | 639/2129 [00:51<02:32,  9.78it/s]
 30%|███       | 641/2129 [00:52<02:20, 10.56it/s]
 30%|███       | 644/2129 [00:52<03:34,  6.94it/s]
 30%|███       | 646/2129 [00:52<03:11,  7.74it/s]
 30%|███       | 648/2129 [00:53<02:41,  9.15it/s]
 31%|███       | 650/2129 [00:53<02:17, 10.78it/s]
 31%|███       | 653/2129 [00:53<02:18, 10.62it/s]
 31%|███       | 655/2129 [00:53<02:15, 10.88it/s]
 31%|███       | 657/2129 [00:53<02:07, 11.54it/s]
 31%|███       | 659/2129 [00:53<02:00, 12.17it/s]
 31%|███       | 661/2129 [00:54<02:10, 11.22it/s]
 31%|███       | 663/2129 [00:54<04:16,  5.71it/s]
 31%|███▏      | 666/2129 [00:55<03:06,  7.84it/s]
 31%|███▏      | 668/2129 [00:55<02:45,  8.81it/s]
 31%|███▏      | 670/2129 [00:55<03:03,  7.96it/s]
 32%|███▏      | 672/2129 [00:56<04:38,  5.23it/s]
 32%|███▏      | 674/2129 [00:56<04:15,  5.69it/s]
 32%|███▏      | 675/2129 [00:56<04:28,  5.41it/s]
 32%|███▏      | 677/2129 [00:56<03:40,  6.58it/s]
 32%|███▏      | 679/2129 [00:56<02:56,  8.22it/s]
 32%|███▏      | 683/2129 [00:57<02:29,  9.66it/s]
 32%|███▏      | 685/2129 [00:57<03:03,  7.85it/s]
 32%|███▏      | 687/2129 [00:58<04:13,  5.69it/s]
 32%|███▏      | 688/2129 [00:58<04:18,  5.57it/s]
 32%|███▏      | 689/2129 [00:58<04:14,  5.66it/s]
 33%|███▎      | 692/2129 [00:58<02:45,  8.66it/s]
 33%|███▎      | 695/2129 [00:58<02:04, 11.53it/s]
 33%|███▎      | 697/2129 [00:59<02:57,  8.06it/s]
 33%|███▎      | 699/2129 [00:59<02:38,  9.04it/s]
 33%|███▎      | 702/2129 [00:59<01:58, 12.03it/s]
 33%|███▎      | 704/2129 [01:00<02:48,  8.47it/s]
 33%|███▎      | 706/2129 [01:00<04:04,  5.83it/s]
 33%|███▎      | 708/2129 [01:01<05:45,  4.11it/s]
 33%|███▎      | 711/2129 [01:01<03:56,  6.00it/s]
 33%|███▎      | 713/2129 [01:02<05:07,  4.60it/s]
 34%|███▎      | 716/2129 [01:02<03:33,  6.61it/s]
 34%|███▍      | 719/2129 [01:03<04:06,  5.71it/s]
 34%|███▍      | 721/2129 [01:03<05:04,  4.62it/s]
 34%|███▍      | 723/2129 [01:04<05:46,  4.06it/s]
 34%|███▍      | 724/2129 [01:04<06:04,  3.85it/s]
 34%|███▍      | 725/2129 [01:05<07:03,  3.32it/s]
 34%|███▍      | 726/2129 [01:05<06:15,  3.73it/s]
 34%|███▍      | 727/2129 [01:06<07:44,  3.02it/s]
 34%|███▍      | 728/2129 [01:06<07:08,  3.27it/s]
 34%|███▍      | 730/2129 [01:06<05:00,  4.65it/s]
 34%|███▍      | 732/2129 [01:06<03:38,  6.40it/s]
 34%|███▍      | 733/2129 [01:06<03:55,  5.93it/s]
 34%|███▍      | 734/2129 [01:06<04:01,  5.78it/s]
 35%|███▍      | 737/2129 [01:07<02:28,  9.39it/s]
 35%|███▍      | 739/2129 [01:07<02:45,  8.39it/s]
 35%|███▍      | 741/2129 [01:07<02:47,  8.27it/s]
 35%|███▍      | 743/2129 [01:07<02:19,  9.95it/s]
 35%|███▌      | 747/2129 [01:07<01:31, 15.06it/s]
 35%|███▌      | 750/2129 [01:08<01:36, 14.23it/s]
 35%|███▌      | 752/2129 [01:08<02:43,  8.42it/s]
 35%|███▌      | 754/2129 [01:09<04:50,  4.73it/s]
 35%|███▌      | 755/2129 [01:09<05:28,  4.18it/s]
 36%|███▌      | 757/2129 [01:10<04:10,  5.48it/s]
 36%|███▌      | 759/2129 [01:10<03:23,  6.73it/s]
 36%|███▌      | 762/2129 [01:10<02:32,  8.99it/s]
 36%|███▌      | 764/2129 [01:10<02:26,  9.29it/s]
 36%|███▌      | 766/2129 [01:10<02:25,  9.39it/s]
 36%|███▌      | 768/2129 [01:11<02:30,  9.07it/s]
 36%|███▌      | 770/2129 [01:11<02:18,  9.78it/s]
 36%|███▋      | 772/2129 [01:11<02:00, 11.22it/s]
 36%|███▋      | 774/2129 [01:11<03:22,  6.68it/s]
 36%|███▋      | 776/2129 [01:12<04:12,  5.36it/s]
 37%|███▋      | 778/2129 [01:12<03:22,  6.68it/s]
 37%|███▋      | 780/2129 [01:12<02:44,  8.18it/s]
 37%|███▋      | 783/2129 [01:12<01:58, 11.40it/s]
 37%|███▋      | 785/2129 [01:13<03:33,  6.29it/s]
 37%|███▋      | 787/2129 [01:14<04:33,  4.91it/s]
 37%|███▋      | 790/2129 [01:14<03:08,  7.12it/s]
 37%|███▋      | 794/2129 [01:14<02:08, 10.39it/s]
 37%|███▋      | 796/2129 [01:15<04:03,  5.47it/s]
 37%|███▋      | 798/2129 [01:16<05:09,  4.30it/s]
 38%|███▊      | 800/2129 [01:16<04:18,  5.13it/s]
 38%|███▊      | 803/2129 [01:16<03:09,  7.01it/s]
 38%|███▊      | 806/2129 [01:16<02:20,  9.43it/s]
 38%|███▊      | 809/2129 [01:17<03:19,  6.63it/s]
 38%|███▊      | 811/2129 [01:17<03:07,  7.02it/s]
 38%|███▊      | 813/2129 [01:17<03:24,  6.44it/s]
 38%|███▊      | 818/2129 [01:18<03:12,  6.80it/s]
 39%|███▊      | 820/2129 [01:19<04:16,  5.10it/s]
 39%|███▊      | 821/2129 [01:19<04:17,  5.07it/s]
 39%|███▊      | 824/2129 [01:19<03:04,  7.08it/s]
 39%|███▉      | 827/2129 [01:19<02:33,  8.48it/s]
 39%|███▉      | 830/2129 [01:19<01:58, 10.92it/s]
 39%|███▉      | 835/2129 [01:20<01:24, 15.27it/s]
 39%|███▉      | 838/2129 [01:20<01:23, 15.39it/s]
 40%|███▉      | 841/2129 [01:20<01:27, 14.68it/s]
 40%|███▉      | 843/2129 [01:21<03:00,  7.13it/s]
 40%|███▉      | 845/2129 [01:21<03:19,  6.45it/s]
 40%|███▉      | 848/2129 [01:22<03:07,  6.83it/s]
 40%|███▉      | 851/2129 [01:22<02:28,  8.61it/s]
 40%|████      | 853/2129 [01:22<02:08,  9.91it/s]
 40%|████      | 855/2129 [01:22<02:04, 10.20it/s]
 40%|████      | 857/2129 [01:22<02:32,  8.32it/s]
 40%|████      | 859/2129 [01:23<02:10,  9.73it/s]
 40%|████      | 861/2129 [01:23<02:34,  8.22it/s]
 41%|████      | 863/2129 [01:23<02:13,  9.46it/s]
 41%|████      | 865/2129 [01:23<01:57, 10.77it/s]
 41%|████      | 867/2129 [01:24<02:28,  8.51it/s]
 41%|████      | 870/2129 [01:24<02:00, 10.43it/s]
 41%|████      | 872/2129 [01:24<01:49, 11.45it/s]
 41%|████      | 874/2129 [01:24<02:39,  7.88it/s]
 41%|████      | 876/2129 [01:25<02:48,  7.42it/s]
 41%|████      | 877/2129 [01:25<02:55,  7.15it/s]
 41%|████      | 878/2129 [01:25<02:55,  7.14it/s]
 41%|████▏     | 880/2129 [01:25<02:26,  8.51it/s]
 41%|████▏     | 881/2129 [01:25<03:17,  6.32it/s]
 41%|████▏     | 882/2129 [01:25<03:11,  6.50it/s]
 42%|████▏     | 885/2129 [01:26<02:06,  9.87it/s]
 42%|████▏     | 887/2129 [01:27<04:34,  4.52it/s]
 42%|████▏     | 889/2129 [01:27<03:43,  5.54it/s]
 42%|████▏     | 890/2129 [01:27<03:40,  5.61it/s]
 42%|████▏     | 892/2129 [01:27<02:49,  7.31it/s]
 42%|████▏     | 894/2129 [01:27<02:29,  8.28it/s]
 42%|████▏     | 896/2129 [01:28<02:59,  6.85it/s]
 42%|████▏     | 898/2129 [01:28<02:55,  7.00it/s]
 42%|████▏     | 900/2129 [01:28<02:32,  8.06it/s]
 42%|████▏     | 902/2129 [01:28<02:13,  9.21it/s]
 42%|████▏     | 904/2129 [01:29<03:39,  5.57it/s]
 43%|████▎     | 905/2129 [01:29<03:41,  5.51it/s]
 43%|████▎     | 906/2129 [01:30<05:24,  3.77it/s]
 43%|████▎     | 909/2129 [01:30<03:42,  5.48it/s]
 43%|████▎     | 911/2129 [01:31<04:52,  4.16it/s]
 43%|████▎     | 913/2129 [01:31<03:44,  5.42it/s]
 43%|████▎     | 914/2129 [01:31<05:15,  3.85it/s]
 43%|████▎     | 916/2129 [01:32<04:01,  5.03it/s]
 43%|████▎     | 920/2129 [01:32<02:17,  8.78it/s]
 43%|████▎     | 923/2129 [01:32<02:03,  9.74it/s]
 43%|████▎     | 925/2129 [01:32<01:51, 10.80it/s]
 44%|████▎     | 927/2129 [01:33<03:50,  5.22it/s]
 44%|████▎     | 929/2129 [01:33<03:51,  5.19it/s]
 44%|████▎     | 931/2129 [01:34<03:32,  5.64it/s]
 44%|████▍     | 933/2129 [01:34<02:58,  6.71it/s]
 44%|████▍     | 936/2129 [01:35<03:37,  5.48it/s]
 44%|████▍     | 937/2129 [01:35<05:14,  3.79it/s]
 44%|████▍     | 938/2129 [01:36<06:41,  2.97it/s]
 44%|████▍     | 939/2129 [01:37<07:57,  2.49it/s]
 44%|████▍     | 940/2129 [01:37<07:05,  2.79it/s]
 44%|████▍     | 943/2129 [01:38<06:00,  3.29it/s]
 44%|████▍     | 944/2129 [01:38<05:39,  3.49it/s]
 44%|████▍     | 945/2129 [01:38<07:22,  2.68it/s]
 44%|████▍     | 946/2129 [01:39<06:22,  3.09it/s]
 45%|████▍     | 948/2129 [01:39<04:19,  4.55it/s]
 45%|████▍     | 950/2129 [01:39<05:04,  3.88it/s]
 45%|████▍     | 952/2129 [01:39<03:47,  5.17it/s]
 45%|████▍     | 955/2129 [01:40<03:14,  6.05it/s]
 45%|████▍     | 956/2129 [01:40<03:22,  5.80it/s]
 45%|████▍     | 958/2129 [01:40<03:32,  5.50it/s]
 45%|████▌     | 960/2129 [01:41<02:47,  7.00it/s]
 45%|████▌     | 962/2129 [01:41<02:19,  8.34it/s]
 45%|████▌     | 964/2129 [01:41<02:19,  8.37it/s]
 45%|████▌     | 966/2129 [01:41<01:55, 10.09it/s]
 46%|████▌     | 969/2129 [01:41<01:27, 13.25it/s]
 46%|████▌     | 971/2129 [01:42<02:21,  8.19it/s]
 46%|████▌     | 973/2129 [01:42<02:22,  8.13it/s]
 46%|████▌     | 975/2129 [01:42<03:08,  6.13it/s]
 46%|████▌     | 977/2129 [01:43<02:33,  7.50it/s]
 46%|████▌     | 979/2129 [01:43<02:33,  7.48it/s]
 46%|████▌     | 981/2129 [01:43<03:18,  5.77it/s]
 46%|████▌     | 982/2129 [01:44<03:06,  6.16it/s]
 46%|████▌     | 984/2129 [01:44<03:29,  5.46it/s]
 46%|████▋     | 986/2129 [01:44<03:21,  5.67it/s]
 46%|████▋     | 988/2129 [01:44<02:54,  6.54it/s]
 47%|████▋     | 992/2129 [01:45<01:46, 10.68it/s]
 47%|████▋     | 994/2129 [01:45<02:51,  6.60it/s]
 47%|████▋     | 996/2129 [01:45<02:41,  7.01it/s]
 47%|████▋     | 1001/2129 [01:46<02:39,  7.08it/s]
 47%|████▋     | 1002/2129 [01:47<03:44,  5.03it/s]
 47%|████▋     | 1005/2129 [01:47<02:42,  6.92it/s]
 47%|████▋     | 1007/2129 [01:48<03:57,  4.72it/s]
 47%|████▋     | 1009/2129 [01:48<03:11,  5.85it/s]
 47%|████▋     | 1011/2129 [01:49<04:05,  4.55it/s]
 48%|████▊     | 1012/2129 [01:49<05:19,  3.50it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 353.46it/s]
 34%|███▎      | 101/300 [05:19<5:07:24, 92.69s/it]

[[np.int64(0), False, 10], [np.int64(1), False, 0], [np.int64(2), False, 11], [np.int64(3), False, 5], [np.int64(4), False, 8], [np.int64(6), False, 13], [np.int64(7), False, 5], [np.int64(9), False, 0], [np.int64(11), False, 10], [np.int64(12), False, 5], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.4817, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [05:19<3:34:18, 64.94s/it]

tensor(12.1632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.7129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1854, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.9918, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [05:19<1:12:40, 22.36s/it]

tensor(12.2337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2260, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4118, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [05:20<35:26, 11.02s/it]

tensor(12.3360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5343, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3593, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6516, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [05:20<17:22,  5.46s/it]

tensor(12.3655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8865, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [05:20<08:37,  2.74s/it]

tensor(12.3398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0178, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1359, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [05:20<06:07,  1.95s/it]

tensor(12.3354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2142, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2875, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [05:20<02:18,  1.33it/s]

tensor(12.3220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3417, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2973, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4037, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [05:21<01:43,  1.78it/s]

tensor(12.2808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4720, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5204, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [05:21<01:01,  2.97it/s]

tensor(12.2685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2573, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5705, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [05:21<00:40,  4.40it/s]

tensor(12.2391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5913, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6145, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [05:21<00:30,  5.76it/s]

tensor(12.1883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6667, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [05:22<00:25,  6.80it/s]

tensor(12.1337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6863, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7097, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [05:22<00:23,  7.45it/s]

tensor(12.0922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7297, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7468, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [05:22<00:22,  7.70it/s]

tensor(12.0664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7708, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7948, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [05:22<00:21,  8.02it/s]

tensor(12.0431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8317, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8620, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [05:23<00:20,  8.16it/s]

tensor(12.0262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9002, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9306, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [05:23<00:20,  8.19it/s]

tensor(12.0075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9626, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9855, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [05:23<00:20,  8.19it/s]

tensor(11.9850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0089, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0436, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [05:23<00:20,  7.95it/s]

tensor(11.9674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0705, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0882, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [05:24<00:20,  7.95it/s]

tensor(11.9500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1125, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1373, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [05:24<00:19,  8.17it/s]

tensor(11.9286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1685, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [05:24<00:18,  8.20it/s]

tensor(11.9046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1800, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1986, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [05:24<00:18,  8.21it/s]

tensor(11.8800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2203, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2289, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [05:25<00:18,  8.21it/s]

tensor(11.8582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2456, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2589, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [05:25<00:18,  8.20it/s]

tensor(11.8414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2712, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([264,  40, 102,  85, 134, 217,  94, 133, 126,  52,  62, 484,  62, 274])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:19, 26.85it/s]
  1%|          | 11/2129 [00:00<00:38, 55.12it/s]
  1%|          | 17/2129 [00:00<00:39, 53.50it/s]
  1%|          | 24/2129 [00:00<00:36, 57.91it/s]
  1%|▏         | 30/2129 [00:00<00:44, 46.68it/s]
  2%|▏         | 39/2129 [00:00<00:36, 57.59it/s]
  2%|▏         | 46/2129 [00:00<00:42, 48.96it/s]
  2%|▏         | 53/2129 [00:01<00:39, 52.77it/s]
  3%|▎         | 60/2129 [00:01<00:36, 56.62it/s]
  3%|▎         | 67/2129 [00:01<00:40, 50.84it/s]
  3%|▎         | 74/2129 [00:01<00:37, 54.27it/s]
  4%|▍         | 80/2129 [00:02<01:25, 23.83it/s]
  4%|▍         | 85/2129 [00:02<01:30, 22.64it/s]
  4%|▍         | 91/2129 [00:02<01:15, 26.97it/s]
  4%|▍         | 95/2129 [00:02<01:17, 26.09it/s]
  5%|▍         | 99/2129 [00:02<01:26, 23.43it/s]
  5%|▍         | 102/2129 [00:02<01:27, 23.06it/s]
  5%|▍         | 105/2129 [00:03<02:29, 13.56it/s]
  5%|▌         | 108/2129 [00:03<02:16, 14.78it/s]
  5%|▌         | 111/2129 [00:03<02:27, 13.65it/s]
  5%|▌         | 114/2129 [00:04<02:49, 11.86it/s]
  5%|▌         | 117/2129 [00:04<02:21, 14.24it/s]
  6%|▌         | 119/2129 [00:04<02:12, 15.15it/s]
  6%|▌         | 123/2129 [00:04<01:43, 19.45it/s]
  6%|▌         | 128/2129 [00:04<01:18, 25.52it/s]
  6%|▌         | 132/2129 [00:04<01:28, 22.56it/s]
  7%|▋         | 140/2129 [00:04<00:59, 33.42it/s]
  7%|▋         | 147/2129 [00:05<00:48, 40.72it/s]
  7%|▋         | 152/2129 [00:05<01:06, 29.52it/s]
  7%|▋         | 156/2129 [00:05<01:06, 29.58it/s]
  8%|▊         | 160/2129 [00:07<04:37,  7.10it/s]
  8%|▊         | 163/2129 [00:08<05:42,  5.74it/s]
  8%|▊         | 166/2129 [00:08<04:46,  6.86it/s]
  8%|▊         | 168/2129 [00:08<04:16,  7.65it/s]
  8%|▊         | 173/2129 [00:08<02:50, 11.48it/s]
  8%|▊         | 176/2129 [00:08<03:01, 10.77it/s]
  8%|▊         | 179/2129 [00:09<05:03,  6.43it/s]
  9%|▊         | 183/2129 [00:10<03:39,  8.87it/s]
  9%|▊         | 186/2129 [00:11<05:28,  5.92it/s]
  9%|▉         | 190/2129 [00:11<05:05,  6.34it/s]
  9%|▉         | 192/2129 [00:11<04:31,  7.13it/s]
  9%|▉         | 194/2129 [00:11<03:54,  8.26it/s]
  9%|▉         | 200/2129 [00:12<03:03, 10.53it/s]
  9%|▉         | 202/2129 [00:12<02:55, 10.96it/s]
 10%|▉         | 205/2129 [00:12<02:29, 12.85it/s]
 10%|▉         | 207/2129 [00:12<02:23, 13.39it/s]
 10%|▉         | 210/2129 [00:12<02:01, 15.78it/s]
 10%|▉         | 212/2129 [00:13<02:49, 11.29it/s]
 10%|█         | 214/2129 [00:13<04:04,  7.83it/s]
 10%|█         | 217/2129 [00:13<03:03, 10.44it/s]
 10%|█         | 223/2129 [00:14<02:44, 11.56it/s]
 11%|█         | 225/2129 [00:14<02:40, 11.90it/s]
 11%|█         | 227/2129 [00:14<02:26, 12.98it/s]
 11%|█         | 229/2129 [00:14<03:15,  9.70it/s]
 11%|█         | 231/2129 [00:14<02:54, 10.89it/s]
 11%|█         | 233/2129 [00:15<05:01,  6.29it/s]
 11%|█         | 235/2129 [00:16<07:23,  4.27it/s]
 11%|█         | 239/2129 [00:17<07:22,  4.28it/s]
 11%|█▏        | 242/2129 [00:17<05:23,  5.83it/s]
 12%|█▏        | 246/2129 [00:18<06:01,  5.21it/s]
 12%|█▏        | 248/2129 [00:19<07:44,  4.05it/s]
 12%|█▏        | 250/2129 [00:20<09:02,  3.46it/s]
 12%|█▏        | 252/2129 [00:20<10:01,  3.12it/s]
 12%|█▏        | 255/2129 [00:21<07:40,  4.07it/s]
 12%|█▏        | 258/2129 [00:22<08:07,  3.84it/s]
 12%|█▏        | 261/2129 [00:23<08:36,  3.62it/s]
 12%|█▏        | 263/2129 [00:23<07:04,  4.40it/s]
 13%|█▎        | 267/2129 [00:23<06:19,  4.90it/s]
 13%|█▎        | 269/2129 [00:24<05:16,  5.88it/s]
 13%|█▎        | 273/2129 [00:24<03:36,  8.59it/s]
 13%|█▎        | 275/2129 [00:24<03:13,  9.59it/s]
 13%|█▎        | 282/2129 [00:24<01:47, 17.16it/s]
 13%|█▎        | 286/2129 [00:24<01:30, 20.37it/s]
 14%|█▎        | 290/2129 [00:25<03:06,  9.84it/s]
 14%|█▍        | 293/2129 [00:26<04:34,  6.69it/s]
 14%|█▍        | 295/2129 [00:27<06:14,  4.90it/s]
 14%|█▍        | 298/2129 [00:27<04:44,  6.45it/s]
 14%|█▍        | 304/2129 [00:28<04:37,  6.57it/s]
 14%|█▍        | 306/2129 [00:28<04:35,  6.63it/s]
 15%|█▍        | 309/2129 [00:28<03:37,  8.37it/s]
 15%|█▍        | 312/2129 [00:29<05:05,  5.95it/s]
 15%|█▍        | 314/2129 [00:31<09:19,  3.25it/s]
 15%|█▍        | 317/2129 [00:31<06:47,  4.44it/s]
 15%|█▌        | 324/2129 [00:32<05:11,  5.80it/s]
 15%|█▌        | 326/2129 [00:32<04:35,  6.54it/s]
 15%|█▌        | 328/2129 [00:33<06:14,  4.81it/s]
 16%|█▌        | 331/2129 [00:33<04:44,  6.32it/s]
 16%|█▌        | 334/2129 [00:34<05:51,  5.11it/s]
 16%|█▌        | 337/2129 [00:34<06:32,  4.57it/s]
 16%|█▌        | 339/2129 [00:35<07:58,  3.74it/s]
 16%|█▌        | 341/2129 [00:35<06:25,  4.63it/s]
 16%|█▌        | 343/2129 [00:37<10:48,  2.75it/s]
 16%|█▌        | 345/2129 [00:37<08:25,  3.53it/s]
 16%|█▋        | 348/2129 [00:37<05:46,  5.14it/s]
 16%|█▋        | 350/2129 [00:39<10:15,  2.89it/s]
 17%|█▋        | 352/2129 [00:39<07:54,  3.75it/s]
 17%|█▋        | 355/2129 [00:40<08:19,  3.55it/s]
 17%|█▋        | 357/2129 [00:41<12:11,  2.42it/s]
 17%|█▋        | 358/2129 [00:42<12:30,  2.36it/s]
 17%|█▋        | 360/2129 [00:42<09:16,  3.18it/s]
 17%|█▋        | 361/2129 [00:42<10:22,  2.84it/s]
 17%|█▋        | 362/2129 [00:43<11:21,  2.59it/s]
 17%|█▋        | 365/2129 [00:43<06:45,  4.35it/s]
 17%|█▋        | 371/2129 [00:43<03:14,  9.03it/s]
 18%|█▊        | 374/2129 [00:44<04:16,  6.84it/s]
 18%|█▊        | 376/2129 [00:45<05:41,  5.13it/s]
 18%|█▊        | 378/2129 [00:45<04:44,  6.15it/s]
 18%|█▊        | 380/2129 [00:46<06:42,  4.34it/s]
 18%|█▊        | 382/2129 [00:46<05:22,  5.42it/s]
 18%|█▊        | 384/2129 [00:47<07:18,  3.98it/s]
 18%|█▊        | 386/2129 [00:47<08:16,  3.51it/s]
 18%|█▊        | 388/2129 [00:47<06:19,  4.59it/s]
 18%|█▊        | 391/2129 [00:48<06:58,  4.15it/s]
 19%|█▊        | 394/2129 [00:49<07:24,  3.91it/s]
 19%|█▊        | 397/2129 [00:49<05:14,  5.50it/s]
 19%|█▉        | 400/2129 [00:50<06:11,  4.66it/s]
 19%|█▉        | 402/2129 [00:50<05:05,  5.66it/s]
 19%|█▉        | 404/2129 [00:51<06:49,  4.21it/s]
 19%|█▉        | 405/2129 [00:52<09:29,  3.03it/s]
 19%|█▉        | 407/2129 [00:52<07:19,  3.92it/s]
 19%|█▉        | 408/2129 [00:53<08:10,  3.51it/s]
 19%|█▉        | 410/2129 [00:53<06:04,  4.72it/s]
 20%|█▉        | 416/2129 [00:53<02:47, 10.25it/s]
 20%|█▉        | 420/2129 [00:54<04:03,  7.01it/s]
 20%|█▉        | 422/2129 [00:54<03:57,  7.17it/s]
 20%|█▉        | 425/2129 [00:54<03:06,  9.16it/s]
 20%|██        | 427/2129 [00:55<04:58,  5.70it/s]
 20%|██        | 429/2129 [00:55<04:40,  6.06it/s]
 20%|██        | 431/2129 [00:56<06:28,  4.37it/s]
 20%|██        | 432/2129 [00:57<09:02,  3.13it/s]
 20%|██        | 433/2129 [00:58<11:36,  2.43it/s]
 20%|██        | 435/2129 [00:58<08:07,  3.48it/s]
 20%|██        | 436/2129 [00:58<08:45,  3.22it/s]
 21%|██        | 439/2129 [00:59<06:38,  4.24it/s]
 21%|██        | 441/2129 [00:59<05:11,  5.41it/s]
 21%|██        | 444/2129 [00:59<03:34,  7.87it/s]
 21%|██        | 448/2129 [00:59<02:20, 11.95it/s]
 21%|██▏       | 455/2129 [01:00<03:03,  9.15it/s]
 21%|██▏       | 457/2129 [01:01<04:20,  6.42it/s]
 22%|██▏       | 459/2129 [01:01<04:33,  6.10it/s]
 22%|██▏       | 462/2129 [01:01<03:36,  7.69it/s]
 22%|██▏       | 464/2129 [01:01<03:07,  8.89it/s]
 22%|██▏       | 466/2129 [01:01<03:23,  8.16it/s]
 22%|██▏       | 468/2129 [01:02<03:51,  7.18it/s]
 22%|██▏       | 470/2129 [01:02<03:14,  8.52it/s]
 22%|██▏       | 472/2129 [01:03<04:29,  6.14it/s]
 22%|██▏       | 475/2129 [01:03<03:21,  8.23it/s]
 22%|██▏       | 477/2129 [01:03<03:45,  7.31it/s]
 22%|██▏       | 479/2129 [01:03<03:50,  7.17it/s]
 23%|██▎       | 481/2129 [01:03<03:16,  8.40it/s]
 23%|██▎       | 483/2129 [01:04<04:00,  6.83it/s]
 23%|██▎       | 484/2129 [01:04<05:13,  5.25it/s]
 23%|██▎       | 486/2129 [01:05<04:18,  6.35it/s]
 23%|██▎       | 487/2129 [01:05<04:32,  6.03it/s]
 23%|██▎       | 489/2129 [01:05<03:29,  7.82it/s]
 23%|██▎       | 491/2129 [01:05<05:07,  5.33it/s]
 23%|██▎       | 493/2129 [01:06<03:57,  6.88it/s]
 23%|██▎       | 495/2129 [01:06<03:32,  7.67it/s]
 23%|██▎       | 499/2129 [01:06<02:12, 12.35it/s]
 24%|██▎       | 501/2129 [01:07<04:24,  6.15it/s]
 24%|██▎       | 503/2129 [01:07<04:07,  6.56it/s]
 24%|██▍       | 507/2129 [01:07<02:39, 10.17it/s]
 24%|██▍       | 509/2129 [01:08<06:44,  4.01it/s]
 24%|██▍       | 512/2129 [01:09<04:50,  5.57it/s]
 24%|██▍       | 517/2129 [01:09<03:22,  7.95it/s]
 24%|██▍       | 520/2129 [01:10<04:06,  6.53it/s]
 25%|██▍       | 522/2129 [01:11<06:54,  3.87it/s]
 25%|██▍       | 526/2129 [01:11<05:35,  4.77it/s]
 25%|██▍       | 528/2129 [01:12<05:09,  5.17it/s]
 25%|██▍       | 529/2129 [01:12<05:45,  4.64it/s]
 25%|██▍       | 530/2129 [01:12<05:48,  4.59it/s]
 25%|██▍       | 532/2129 [01:12<04:24,  6.03it/s]
 25%|██▌       | 534/2129 [01:12<03:29,  7.61it/s]
 25%|██▌       | 536/2129 [01:14<08:36,  3.09it/s]
 25%|██▌       | 538/2129 [01:14<06:29,  4.09it/s]
 25%|██▌       | 541/2129 [01:14<04:23,  6.03it/s]
 26%|██▌       | 543/2129 [01:15<06:22,  4.14it/s]
 26%|██▌       | 545/2129 [01:15<05:41,  4.64it/s]
 26%|██▌       | 547/2129 [01:16<05:14,  5.03it/s]
 26%|██▌       | 548/2129 [01:16<05:04,  5.19it/s]
 26%|██▌       | 551/2129 [01:16<04:03,  6.49it/s]
 26%|██▌       | 554/2129 [01:16<02:51,  9.17it/s]
 26%|██▌       | 557/2129 [01:17<02:31, 10.38it/s]
 26%|██▋       | 559/2129 [01:17<04:33,  5.73it/s]
 26%|██▋       | 562/2129 [01:18<03:23,  7.70it/s]
 26%|██▋       | 564/2129 [01:18<03:55,  6.64it/s]
 27%|██▋       | 567/2129 [01:18<03:35,  7.26it/s]
 27%|██▋       | 570/2129 [01:18<02:44,  9.47it/s]
 27%|██▋       | 572/2129 [01:19<03:35,  7.22it/s]
 27%|██▋       | 574/2129 [01:19<03:01,  8.55it/s]
 27%|██▋       | 577/2129 [01:19<02:52,  9.00it/s]
 27%|██▋       | 579/2129 [01:19<02:37,  9.84it/s]
 27%|██▋       | 581/2129 [01:20<04:45,  5.43it/s]
 27%|██▋       | 583/2129 [01:20<03:48,  6.76it/s]
 27%|██▋       | 585/2129 [01:21<05:48,  4.43it/s]
 28%|██▊       | 587/2129 [01:22<05:37,  4.56it/s]
 28%|██▊       | 589/2129 [01:22<06:11,  4.15it/s]
 28%|██▊       | 590/2129 [01:23<07:00,  3.66it/s]
 28%|██▊       | 592/2129 [01:23<05:07,  5.00it/s]
 28%|██▊       | 594/2129 [01:23<04:36,  5.55it/s]
 28%|██▊       | 596/2129 [01:23<04:00,  6.38it/s]
 28%|██▊       | 599/2129 [01:24<04:47,  5.33it/s]
 28%|██▊       | 601/2129 [01:24<03:55,  6.50it/s]
 28%|██▊       | 602/2129 [01:25<05:32,  4.60it/s]
 28%|██▊       | 604/2129 [01:25<04:20,  5.85it/s]
 28%|██▊       | 605/2129 [01:25<05:11,  4.89it/s]
 29%|██▊       | 608/2129 [01:25<03:15,  7.77it/s]
 29%|██▊       | 610/2129 [01:26<05:02,  5.02it/s]
 29%|██▊       | 612/2129 [01:27<06:45,  3.74it/s]
 29%|██▉       | 613/2129 [01:28<09:11,  2.75it/s]
 29%|██▉       | 616/2129 [01:28<05:41,  4.43it/s]
 29%|██▉       | 622/2129 [01:28<02:49,  8.92it/s]
 29%|██▉       | 625/2129 [01:28<02:40,  9.37it/s]
 29%|██▉       | 627/2129 [01:29<04:25,  5.66it/s]
 30%|██▉       | 629/2129 [01:30<06:01,  4.15it/s]
 30%|██▉       | 631/2129 [01:30<05:18,  4.71it/s]
 30%|██▉       | 632/2129 [01:31<07:38,  3.27it/s]
 30%|██▉       | 633/2129 [01:31<07:09,  3.49it/s]
 30%|██▉       | 635/2129 [01:31<05:12,  4.78it/s]
 30%|██▉       | 637/2129 [01:32<07:03,  3.52it/s]
 30%|███       | 639/2129 [01:32<05:14,  4.74it/s]
 30%|███       | 641/2129 [01:33<05:12,  4.76it/s]
 30%|███       | 644/2129 [01:33<03:47,  6.52it/s]
 30%|███       | 646/2129 [01:33<03:13,  7.68it/s]
 30%|███       | 648/2129 [01:33<03:08,  7.86it/s]
 31%|███       | 650/2129 [01:34<03:50,  6.43it/s]
 31%|███       | 652/2129 [01:34<03:14,  7.61it/s]
 31%|███       | 654/2129 [01:34<04:19,  5.68it/s]
 31%|███       | 657/2129 [01:35<03:06,  7.91it/s]
 31%|███       | 659/2129 [01:35<03:20,  7.34it/s]
 31%|███       | 661/2129 [01:36<04:37,  5.29it/s]
 31%|███       | 662/2129 [01:36<05:30,  4.43it/s]
 31%|███       | 663/2129 [01:36<06:00,  4.07it/s]
 31%|███       | 665/2129 [01:36<04:26,  5.49it/s]
 31%|███▏      | 667/2129 [01:37<03:42,  6.58it/s]
 31%|███▏      | 669/2129 [01:37<03:00,  8.11it/s]
 32%|███▏      | 672/2129 [01:37<03:01,  8.04it/s]
 32%|███▏      | 674/2129 [01:37<02:31,  9.61it/s]
 32%|███▏      | 676/2129 [01:37<02:37,  9.24it/s]
 32%|███▏      | 678/2129 [01:39<05:44,  4.21it/s]
 32%|███▏      | 679/2129 [01:39<05:36,  4.31it/s]
 32%|███▏      | 682/2129 [01:40<06:21,  3.79it/s]
 32%|███▏      | 683/2129 [01:40<05:52,  4.10it/s]
 32%|███▏      | 684/2129 [01:40<05:44,  4.19it/s]
 32%|███▏      | 685/2129 [01:41<08:22,  2.87it/s]
 32%|███▏      | 686/2129 [01:41<07:33,  3.18it/s]
 32%|███▏      | 687/2129 [01:41<06:55,  3.47it/s]
 32%|███▏      | 688/2129 [01:42<10:26,  2.30it/s]
 32%|███▏      | 689/2129 [01:43<13:15,  1.81it/s]
 33%|███▎      | 692/2129 [01:43<06:36,  3.63it/s]
 33%|███▎      | 694/2129 [01:44<06:37,  3.61it/s]
 33%|███▎      | 696/2129 [01:44<07:52,  3.03it/s]
 33%|███▎      | 698/2129 [01:45<06:17,  3.79it/s]
 33%|███▎      | 700/2129 [01:45<04:42,  5.06it/s]
 33%|███▎      | 703/2129 [01:46<04:53,  4.86it/s]
 33%|███▎      | 705/2129 [01:46<04:58,  4.78it/s]
 33%|███▎      | 707/2129 [01:46<05:11,  4.57it/s]
 33%|███▎      | 708/2129 [01:47<06:07,  3.87it/s]
 33%|███▎      | 709/2129 [01:47<05:39,  4.19it/s]
 33%|███▎      | 711/2129 [01:47<04:08,  5.71it/s]
 33%|███▎      | 712/2129 [01:48<05:53,  4.00it/s]
 33%|███▎      | 713/2129 [01:48<07:10,  3.29it/s]
 34%|███▎      | 717/2129 [01:48<03:39,  6.44it/s]
 34%|███▍      | 719/2129 [01:49<03:13,  7.27it/s]
 34%|███▍      | 721/2129 [01:49<05:18,  4.43it/s]
 34%|███▍      | 723/2129 [01:50<07:04,  3.31it/s]
 34%|███▍      | 724/2129 [01:51<09:09,  2.56it/s]
 34%|███▍      | 725/2129 [01:51<08:14,  2.84it/s]
 34%|███▍      | 726/2129 [01:52<10:28,  2.23it/s]
 34%|███▍      | 727/2129 [01:53<12:33,  1.86it/s]
 34%|███▍      | 728/2129 [01:53<10:21,  2.26it/s]
 34%|███▍      | 731/2129 [01:53<05:30,  4.23it/s]
 34%|███▍      | 733/2129 [01:54<06:41,  3.48it/s]
 34%|███▍      | 734/2129 [01:55<07:31,  3.09it/s]
 35%|███▍      | 736/2129 [01:55<05:29,  4.23it/s]
 35%|███▍      | 739/2129 [01:56<05:49,  3.98it/s]
 35%|███▍      | 741/2129 [01:56<04:58,  4.66it/s]
 35%|███▍      | 743/2129 [01:56<03:54,  5.91it/s]
 35%|███▌      | 748/2129 [01:56<02:08, 10.77it/s]
 35%|███▌      | 751/2129 [01:57<03:06,  7.38it/s]
 35%|███▌      | 753/2129 [01:57<03:38,  6.30it/s]
 35%|███▌      | 755/2129 [01:58<05:10,  4.42it/s]
 36%|███▌      | 757/2129 [01:58<04:08,  5.52it/s]
 36%|███▌      | 759/2129 [01:58<03:24,  6.70it/s]
 36%|███▌      | 761/2129 [01:58<02:51,  7.99it/s]
 36%|███▌      | 763/2129 [02:00<07:18,  3.12it/s]
 36%|███▌      | 765/2129 [02:00<05:41,  4.00it/s]
 36%|███▌      | 767/2129 [02:01<07:27,  3.04it/s]
 36%|███▌      | 769/2129 [02:02<07:31,  3.01it/s]
 36%|███▌      | 771/2129 [02:02<05:40,  3.99it/s]
 36%|███▋      | 773/2129 [02:02<04:48,  4.70it/s]
 36%|███▋      | 775/2129 [02:03<05:14,  4.30it/s]
 37%|███▋      | 778/2129 [02:03<03:32,  6.34it/s]
 37%|███▋      | 780/2129 [02:03<04:06,  5.47it/s]
 37%|███▋      | 782/2129 [02:04<03:56,  5.69it/s]
 37%|███▋      | 784/2129 [02:04<03:30,  6.40it/s]
 37%|███▋      | 785/2129 [02:04<04:20,  5.17it/s]
 37%|███▋      | 786/2129 [02:04<04:01,  5.56it/s]
 37%|███▋      | 787/2129 [02:05<03:43,  6.00it/s]
 37%|███▋      | 790/2129 [02:05<02:24,  9.27it/s]
 37%|███▋      | 795/2129 [02:05<01:43, 12.83it/s]
 37%|███▋      | 797/2129 [02:06<04:04,  5.45it/s]
 38%|███▊      | 799/2129 [02:07<05:32,  4.00it/s]
 38%|███▊      | 800/2129 [02:08<07:36,  2.91it/s]
 38%|███▊      | 802/2129 [02:09<08:27,  2.61it/s]
 38%|███▊      | 803/2129 [02:10<10:12,  2.16it/s]
 38%|███▊      | 806/2129 [02:10<06:11,  3.56it/s]
 38%|███▊      | 809/2129 [02:11<06:10,  3.57it/s]
 38%|███▊      | 810/2129 [02:11<08:04,  2.72it/s]
 38%|███▊      | 812/2129 [02:12<06:32,  3.35it/s]
 38%|███▊      | 813/2129 [02:13<08:45,  2.51it/s]
 38%|███▊      | 816/2129 [02:13<05:18,  4.13it/s]
 38%|███▊      | 818/2129 [02:14<06:57,  3.14it/s]
 39%|███▊      | 820/2129 [02:14<07:30,  2.90it/s]
 39%|███▊      | 822/2129 [02:15<05:38,  3.86it/s]
 39%|███▉      | 827/2129 [02:15<03:48,  5.70it/s]
 39%|███▉      | 829/2129 [02:15<03:16,  6.61it/s]
 39%|███▉      | 831/2129 [02:16<03:19,  6.52it/s]
 39%|███▉      | 834/2129 [02:16<02:29,  8.64it/s]
 39%|███▉      | 838/2129 [02:16<03:16,  6.58it/s]
 40%|███▉      | 841/2129 [02:17<02:32,  8.46it/s]
 40%|███▉      | 843/2129 [02:18<05:02,  4.25it/s]
 40%|███▉      | 845/2129 [02:19<05:26,  3.93it/s]
 40%|███▉      | 846/2129 [02:19<05:57,  3.58it/s]
 40%|███▉      | 847/2129 [02:19<05:18,  4.03it/s]
 40%|███▉      | 848/2129 [02:19<05:41,  3.76it/s]
 40%|███▉      | 850/2129 [02:20<04:02,  5.28it/s]
 40%|████      | 852/2129 [02:20<05:54,  3.60it/s]
 40%|████      | 854/2129 [02:21<05:43,  3.71it/s]
 40%|████      | 855/2129 [02:21<06:08,  3.46it/s]
 40%|████      | 857/2129 [02:22<04:52,  4.35it/s]
 40%|████      | 860/2129 [02:22<03:41,  5.73it/s]
 40%|████      | 862/2129 [02:22<03:50,  5.50it/s]
 41%|████      | 865/2129 [02:23<04:15,  4.95it/s]
 41%|████      | 866/2129 [02:23<04:04,  5.16it/s]
 41%|████      | 869/2129 [02:23<02:48,  7.46it/s]
 41%|████      | 872/2129 [02:23<02:05, 10.04it/s]
 41%|████      | 874/2129 [02:24<02:56,  7.10it/s]
 41%|████      | 876/2129 [02:24<02:42,  7.69it/s]
 41%|████      | 878/2129 [02:24<02:15,  9.25it/s]
 41%|████▏     | 881/2129 [02:25<03:52,  5.36it/s]
 41%|████▏     | 883/2129 [02:25<03:09,  6.56it/s]
 42%|████▏     | 886/2129 [02:26<03:13,  6.42it/s]
 42%|████▏     | 888/2129 [02:26<03:36,  5.74it/s]
 42%|████▏     | 890/2129 [02:26<03:17,  6.26it/s]
 42%|████▏     | 893/2129 [02:27<02:46,  7.43it/s]
 42%|████▏     | 895/2129 [02:28<04:18,  4.78it/s]
 42%|████▏     | 897/2129 [02:28<03:24,  6.01it/s]
 42%|████▏     | 899/2129 [02:28<04:50,  4.23it/s]
 42%|████▏     | 900/2129 [02:29<04:39,  4.40it/s]
 42%|████▏     | 902/2129 [02:29<05:58,  3.42it/s]
 42%|████▏     | 903/2129 [02:30<08:11,  2.49it/s]
 43%|████▎     | 905/2129 [02:31<06:22,  3.20it/s]
 43%|████▎     | 906/2129 [02:31<06:48,  2.99it/s]
 43%|████▎     | 908/2129 [02:32<06:16,  3.24it/s]
 43%|████▎     | 910/2129 [02:32<04:29,  4.52it/s]
 43%|████▎     | 911/2129 [02:32<05:02,  4.02it/s]
 43%|████▎     | 912/2129 [02:33<05:51,  3.46it/s]
 43%|████▎     | 914/2129 [02:33<05:09,  3.92it/s]
 43%|████▎     | 916/2129 [02:33<05:14,  3.85it/s]
 43%|████▎     | 919/2129 [02:34<03:21,  6.02it/s]
 43%|████▎     | 921/2129 [02:34<02:48,  7.18it/s]
 43%|████▎     | 923/2129 [02:34<02:21,  8.51it/s]
 43%|████▎     | 925/2129 [02:34<02:31,  7.93it/s]
 44%|████▎     | 927/2129 [02:36<06:14,  3.21it/s]
 44%|████▎     | 928/2129 [02:36<07:44,  2.59it/s]
 44%|████▎     | 929/2129 [02:37<06:53,  2.90it/s]
 44%|████▎     | 931/2129 [02:37<05:12,  3.83it/s]
 44%|████▍     | 933/2129 [02:37<03:46,  5.29it/s]
 44%|████▍     | 936/2129 [02:38<04:33,  4.36it/s]
 44%|████▍     | 937/2129 [02:39<06:33,  3.03it/s]
 44%|████▍     | 938/2129 [02:39<07:00,  2.83it/s]
 44%|████▍     | 939/2129 [02:39<07:03,  2.81it/s]
 44%|████▍     | 941/2129 [02:40<04:47,  4.14it/s]
 44%|████▍     | 943/2129 [02:40<03:56,  5.00it/s]
 44%|████▍     | 944/2129 [02:40<04:58,  3.97it/s]
 44%|████▍     | 945/2129 [02:40<05:06,  3.87it/s]
 44%|████▍     | 946/2129 [02:41<04:26,  4.44it/s]
 45%|████▍     | 948/2129 [02:41<06:03,  3.25it/s]
 45%|████▍     | 950/2129 [02:42<05:48,  3.38it/s]
 45%|████▍     | 953/2129 [02:42<03:35,  5.46it/s]
 45%|████▍     | 955/2129 [02:42<03:04,  6.35it/s]
 45%|████▍     | 957/2129 [02:43<02:56,  6.66it/s]
 45%|████▍     | 958/2129 [02:43<03:47,  5.15it/s]
 45%|████▌     | 960/2129 [02:44<04:38,  4.20it/s]
 45%|████▌     | 961/2129 [02:44<05:27,  3.57it/s]
 45%|████▌     | 963/2129 [02:45<06:32,  2.97it/s]
 45%|████▌     | 966/2129 [02:45<04:05,  4.74it/s]
 45%|████▌     | 968/2129 [02:46<05:21,  3.61it/s]
 46%|████▌     | 970/2129 [02:46<04:40,  4.13it/s]
 46%|████▌     | 971/2129 [02:47<06:37,  2.91it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 336.71it/s]
 50%|█████     | 151/300 [12:33<5:19:00, 128.46s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 11], [np.int64(2), False, 13], [np.int64(3), False, 8], [np.int64(4), False, 5], [np.int64(5), False, 0], [np.int64(6), False, 5], [np.int64(7), False, 0], [np.int64(8), False, 0], [np.int64(9), False, 5], [np.int64(10), False, 8], [np.int64(12), False, 5], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.8340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5761, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [12:33<3:41:56, 89.97s/it]

tensor(11.8268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6532, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8255, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [12:33<1:47:25, 44.15s/it]

tensor(11.8368, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9518, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0447, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [12:33<52:04, 21.70s/it]

tensor(11.8701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1031, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1348, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [12:34<17:40,  7.52s/it]

tensor(11.8842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1406, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1570, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [12:34<12:22,  5.30s/it]

tensor(11.8701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1837, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2096, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [12:34<06:07,  2.66s/it]

tensor(11.8433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2515, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3034, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [12:34<03:06,  1.37s/it]

tensor(11.8208, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3506, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3752, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [12:35<01:13,  1.82it/s]

tensor(11.8085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3941, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4056, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [12:35<00:55,  2.37it/s]

tensor(11.7972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4261, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7875, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4228, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [12:35<00:34,  3.73it/s]

tensor(11.7778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4194, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4190, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [12:35<00:24,  5.16it/s]

tensor(11.7650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4286, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4260, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [12:36<00:18,  6.83it/s]

tensor(11.7600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4302, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4359, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [12:36<00:17,  7.19it/s]

tensor(11.7538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4570, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [12:36<00:15,  7.84it/s]

tensor(11.7437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4628, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4693, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [12:36<00:14,  8.03it/s]

tensor(11.7309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4784, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4883, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [12:37<00:14,  8.11it/s]

tensor(11.7220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4944, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7194, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4984, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [12:37<00:14,  8.18it/s]

tensor(11.7172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5018, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5100, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [12:37<00:14,  8.03it/s]

tensor(11.7109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5168, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5168, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [12:37<00:13,  8.05it/s]

tensor(11.7037, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5222, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5253, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [12:38<00:13,  8.00it/s]

tensor(11.6979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5247, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5257, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [12:38<00:13,  8.11it/s]

tensor(11.6935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5308, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [12:38<00:12,  8.12it/s]

tensor(11.6892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5334, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5329, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [12:38<00:12,  8.11it/s]

tensor(11.6843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5343, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5365, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [12:39<00:12,  8.00it/s]

tensor(11.6793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5433, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5468, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [12:39<00:12,  8.01it/s]

tensor(11.6753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5521, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([346,  80, 120, 249, 114,  81, 133, 327,  62,  92, 105, 105,  91, 224])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:32, 23.04it/s]
  0%|          | 7/2129 [00:00<01:07, 31.24it/s]
  1%|          | 12/2129 [00:00<00:55, 38.24it/s]
  1%|          | 18/2129 [00:00<00:47, 44.46it/s]
  1%|          | 23/2129 [00:00<00:47, 44.32it/s]
  1%|▏         | 29/2129 [00:00<00:43, 48.09it/s]
  2%|▏         | 35/2129 [00:00<00:48, 42.93it/s]
  2%|▏         | 41/2129 [00:00<00:44, 47.01it/s]
  2%|▏         | 46/2129 [00:01<00:44, 46.40it/s]
  2%|▏         | 51/2129 [00:01<00:54, 38.46it/s]
  3%|▎         | 56/2129 [00:01<00:51, 40.13it/s]
  3%|▎         | 63/2129 [00:01<00:44, 46.78it/s]
  3%|▎         | 68/2129 [00:01<01:12, 28.43it/s]
  4%|▎         | 76/2129 [00:01<00:56, 36.56it/s]
  4%|▍         | 81/2129 [00:02<01:10, 29.15it/s]
  4%|▍         | 85/2129 [00:02<01:14, 27.34it/s]
  4%|▍         | 92/2129 [00:02<00:59, 34.40it/s]
  5%|▍         | 97/2129 [00:02<01:07, 29.93it/s]
  5%|▍         | 101/2129 [00:03<01:28, 22.88it/s]
  5%|▍         | 104/2129 [00:03<02:03, 16.42it/s]
  5%|▌         | 107/2129 [00:03<02:00, 16.83it/s]
  5%|▌         | 115/2129 [00:03<01:17, 25.95it/s]
  6%|▌         | 123/2129 [00:03<00:57, 34.81it/s]
  6%|▌         | 129/2129 [00:03<00:50, 39.48it/s]
  6%|▋         | 135/2129 [00:04<01:33, 21.23it/s]
  7%|▋         | 142/2129 [00:04<01:13, 27.21it/s]
  7%|▋         | 147/2129 [00:04<01:06, 29.91it/s]
  7%|▋         | 152/2129 [00:05<01:43, 19.16it/s]
  7%|▋         | 156/2129 [00:05<01:32, 21.22it/s]
  8%|▊         | 160/2129 [00:06<02:30, 13.05it/s]
  8%|▊         | 163/2129 [00:06<02:44, 11.98it/s]
  8%|▊         | 166/2129 [00:06<02:46, 11.79it/s]
  8%|▊         | 169/2129 [00:06<02:25, 13.52it/s]
  8%|▊         | 171/2129 [00:06<02:34, 12.70it/s]
  8%|▊         | 173/2129 [00:07<02:22, 13.72it/s]
  8%|▊         | 176/2129 [00:07<02:01, 16.08it/s]
  8%|▊         | 179/2129 [00:07<02:28, 13.15it/s]
  9%|▊         | 183/2129 [00:07<01:52, 17.23it/s]
  9%|▊         | 186/2129 [00:08<02:50, 11.36it/s]
  9%|▉         | 190/2129 [00:08<02:37, 12.33it/s]
  9%|▉         | 194/2129 [00:08<02:03, 15.67it/s]
  9%|▉         | 200/2129 [00:08<01:46, 18.12it/s]
 10%|▉         | 203/2129 [00:09<02:15, 14.25it/s]
 10%|▉         | 208/2129 [00:09<01:41, 19.01it/s]
 10%|▉         | 212/2129 [00:09<01:43, 18.54it/s]
 10%|█         | 215/2129 [00:09<02:02, 15.68it/s]
 10%|█         | 218/2129 [00:09<01:48, 17.66it/s]
 10%|█         | 223/2129 [00:10<02:11, 14.48it/s]
 11%|█         | 226/2129 [00:10<01:59, 15.94it/s]
 11%|█         | 233/2129 [00:10<01:36, 19.62it/s]
 11%|█         | 236/2129 [00:10<01:50, 17.13it/s]
 11%|█         | 239/2129 [00:11<02:32, 12.39it/s]
 11%|█▏        | 242/2129 [00:11<02:11, 14.34it/s]
 12%|█▏        | 246/2129 [00:11<02:05, 15.03it/s]
 12%|█▏        | 248/2129 [00:11<02:24, 12.98it/s]
 12%|█▏        | 250/2129 [00:12<03:19,  9.40it/s]
 12%|█▏        | 252/2129 [00:12<03:27,  9.07it/s]
 12%|█▏        | 255/2129 [00:12<03:09,  9.91it/s]
 12%|█▏        | 258/2129 [00:13<04:02,  7.72it/s]
 12%|█▏        | 261/2129 [00:13<04:24,  7.07it/s]
 12%|█▏        | 264/2129 [00:14<03:25,  9.10it/s]
 13%|█▎        | 267/2129 [00:14<03:07,  9.95it/s]
 13%|█▎        | 270/2129 [00:14<02:33, 12.12it/s]
 13%|█▎        | 275/2129 [00:14<02:40, 11.57it/s]
 13%|█▎        | 278/2129 [00:15<02:18, 13.38it/s]
 13%|█▎        | 285/2129 [00:15<01:26, 21.38it/s]
 14%|█▎        | 289/2129 [00:15<01:39, 18.54it/s]
 14%|█▎        | 292/2129 [00:15<02:17, 13.40it/s]
 14%|█▍        | 295/2129 [00:16<02:21, 13.00it/s]
 14%|█▍        | 299/2129 [00:16<01:53, 16.11it/s]
 14%|█▍        | 304/2129 [00:16<01:44, 17.46it/s]
 14%|█▍        | 307/2129 [00:16<02:03, 14.80it/s]
 15%|█▍        | 312/2129 [00:17<02:27, 12.34it/s]
 15%|█▍        | 314/2129 [00:17<03:07,  9.66it/s]
 15%|█▍        | 317/2129 [00:17<02:35, 11.62it/s]
 15%|█▌        | 324/2129 [00:18<02:21, 12.73it/s]
 15%|█▌        | 327/2129 [00:18<02:06, 14.26it/s]
 15%|█▌        | 329/2129 [00:18<02:57, 10.16it/s]
 16%|█▌        | 331/2129 [00:19<03:34,  8.37it/s]
 16%|█▌        | 334/2129 [00:19<03:16,  9.15it/s]
 16%|█▌        | 337/2129 [00:20<03:45,  7.94it/s]
 16%|█▌        | 339/2129 [00:20<03:40,  8.14it/s]
 16%|█▌        | 342/2129 [00:20<03:22,  8.81it/s]
 16%|█▌        | 343/2129 [00:20<04:01,  7.39it/s]
 16%|█▌        | 345/2129 [00:20<03:27,  8.58it/s]
 16%|█▋        | 349/2129 [00:21<02:46, 10.66it/s]
 16%|█▋        | 351/2129 [00:21<03:09,  9.36it/s]
 17%|█▋        | 353/2129 [00:21<02:51, 10.35it/s]
 17%|█▋        | 355/2129 [00:22<03:39,  8.08it/s]
 17%|█▋        | 356/2129 [00:22<04:06,  7.19it/s]
 17%|█▋        | 357/2129 [00:22<04:25,  6.67it/s]
 17%|█▋        | 358/2129 [00:22<04:40,  6.31it/s]
 17%|█▋        | 360/2129 [00:22<03:29,  8.43it/s]
 17%|█▋        | 362/2129 [00:23<04:43,  6.22it/s]
 17%|█▋        | 364/2129 [00:23<03:47,  7.77it/s]
 17%|█▋        | 367/2129 [00:23<02:39, 11.03it/s]
 18%|█▊        | 373/2129 [00:24<02:33, 11.46it/s]
 18%|█▊        | 375/2129 [00:24<02:19, 12.56it/s]
 18%|█▊        | 377/2129 [00:24<02:33, 11.42it/s]
 18%|█▊        | 380/2129 [00:24<02:31, 11.52it/s]
 18%|█▊        | 382/2129 [00:24<02:21, 12.36it/s]
 18%|█▊        | 384/2129 [00:24<02:23, 12.19it/s]
 18%|█▊        | 386/2129 [00:25<02:29, 11.65it/s]
 18%|█▊        | 389/2129 [00:25<02:01, 14.33it/s]
 18%|█▊        | 391/2129 [00:25<02:10, 13.30it/s]
 18%|█▊        | 393/2129 [00:25<02:00, 14.41it/s]
 19%|█▊        | 395/2129 [00:25<02:23, 12.08it/s]
 19%|█▊        | 399/2129 [00:25<01:41, 17.05it/s]
 19%|█▉        | 402/2129 [00:26<02:03, 13.99it/s]
 19%|█▉        | 404/2129 [00:26<02:19, 12.38it/s]
 19%|█▉        | 406/2129 [00:26<02:41, 10.66it/s]
 19%|█▉        | 408/2129 [00:26<02:48, 10.22it/s]
 19%|█▉        | 411/2129 [00:26<02:08, 13.38it/s]
 20%|█▉        | 417/2129 [00:27<01:19, 21.65it/s]
 20%|█▉        | 420/2129 [00:27<01:34, 18.09it/s]
 20%|█▉        | 423/2129 [00:27<01:31, 18.55it/s]
 20%|██        | 427/2129 [00:27<01:16, 22.38it/s]
 20%|██        | 430/2129 [00:28<02:00, 14.05it/s]
 20%|██        | 433/2129 [00:28<02:34, 10.99it/s]
 20%|██        | 436/2129 [00:28<03:09,  8.91it/s]
 21%|██        | 439/2129 [00:29<03:30,  8.03it/s]
 21%|██        | 441/2129 [00:29<03:04,  9.16it/s]
 21%|██        | 447/2129 [00:29<01:49, 15.34it/s]
 21%|██▏       | 453/2129 [00:29<01:16, 21.83it/s]
 21%|██▏       | 457/2129 [00:30<01:54, 14.62it/s]
 22%|██▏       | 460/2129 [00:30<02:53,  9.61it/s]
 22%|██▏       | 464/2129 [00:31<02:18, 12.04it/s]
 22%|██▏       | 467/2129 [00:31<02:30, 11.05it/s]
 22%|██▏       | 469/2129 [00:31<03:11,  8.66it/s]
 22%|██▏       | 471/2129 [00:32<03:18,  8.34it/s]
 22%|██▏       | 473/2129 [00:32<02:53,  9.52it/s]
 22%|██▏       | 477/2129 [00:32<03:06,  8.84it/s]
 22%|██▏       | 479/2129 [00:32<03:14,  8.48it/s]
 23%|██▎       | 482/2129 [00:33<02:29, 10.99it/s]
 23%|██▎       | 484/2129 [00:33<03:22,  8.11it/s]
 23%|██▎       | 486/2129 [00:33<03:21,  8.14it/s]
 23%|██▎       | 488/2129 [00:34<04:09,  6.57it/s]
 23%|██▎       | 490/2129 [00:34<03:58,  6.89it/s]
 23%|██▎       | 493/2129 [00:34<02:56,  9.27it/s]
 23%|██▎       | 495/2129 [00:34<02:57,  9.21it/s]
 23%|██▎       | 498/2129 [00:34<02:14, 12.09it/s]
 24%|██▎       | 501/2129 [00:35<02:17, 11.88it/s]
 24%|██▎       | 503/2129 [00:35<02:08, 12.69it/s]
 24%|██▍       | 507/2129 [00:35<01:33, 17.30it/s]
 24%|██▍       | 510/2129 [00:35<02:08, 12.55it/s]
 24%|██▍       | 512/2129 [00:36<02:13, 12.09it/s]
 24%|██▍       | 515/2129 [00:36<02:19, 11.58it/s]
 24%|██▍       | 518/2129 [00:36<01:52, 14.31it/s]
 24%|██▍       | 520/2129 [00:36<02:04, 12.92it/s]
 25%|██▍       | 522/2129 [00:36<02:51,  9.37it/s]
 25%|██▍       | 524/2129 [00:37<02:29, 10.72it/s]
 25%|██▍       | 526/2129 [00:37<02:32, 10.50it/s]
 25%|██▍       | 528/2129 [00:37<02:55,  9.12it/s]
 25%|██▍       | 530/2129 [00:38<04:22,  6.08it/s]
 25%|██▌       | 533/2129 [00:38<03:05,  8.62it/s]
 25%|██▌       | 535/2129 [00:38<03:42,  7.15it/s]
 25%|██▌       | 537/2129 [00:39<03:48,  6.97it/s]
 25%|██▌       | 541/2129 [00:39<02:25, 10.91it/s]
 26%|██▌       | 543/2129 [00:39<03:06,  8.50it/s]
 26%|██▌       | 546/2129 [00:39<02:26, 10.82it/s]
 26%|██▌       | 548/2129 [00:39<02:38,  9.97it/s]
 26%|██▌       | 551/2129 [00:40<02:02, 12.91it/s]
 26%|██▌       | 557/2129 [00:40<01:55, 13.59it/s]
 26%|██▋       | 559/2129 [00:40<02:11, 11.92it/s]
 26%|██▋       | 562/2129 [00:40<01:52, 13.95it/s]
 26%|██▋       | 564/2129 [00:41<03:41,  7.08it/s]
 27%|██▋       | 567/2129 [00:41<03:11,  8.15it/s]
 27%|██▋       | 570/2129 [00:41<02:32, 10.22it/s]
 27%|██▋       | 572/2129 [00:42<02:36,  9.95it/s]
 27%|██▋       | 574/2129 [00:42<02:19, 11.13it/s]
 27%|██▋       | 577/2129 [00:42<02:01, 12.75it/s]
 27%|██▋       | 579/2129 [00:42<01:51, 13.90it/s]
 27%|██▋       | 581/2129 [00:42<02:12, 11.69it/s]
 27%|██▋       | 584/2129 [00:43<02:15, 11.42it/s]
 28%|██▊       | 586/2129 [00:43<02:26, 10.51it/s]
 28%|██▊       | 588/2129 [00:43<02:42,  9.46it/s]
 28%|██▊       | 590/2129 [00:44<03:28,  7.39it/s]
 28%|██▊       | 593/2129 [00:44<03:00,  8.51it/s]
 28%|██▊       | 595/2129 [00:44<02:33, 10.00it/s]
 28%|██▊       | 599/2129 [00:44<02:05, 12.15it/s]
 28%|██▊       | 602/2129 [00:44<02:14, 11.34it/s]
 28%|██▊       | 604/2129 [00:45<02:12, 11.53it/s]
 28%|██▊       | 606/2129 [00:45<02:38,  9.62it/s]
 29%|██▊       | 609/2129 [00:45<02:01, 12.53it/s]
 29%|██▊       | 611/2129 [00:46<03:28,  7.29it/s]
 29%|██▉       | 613/2129 [00:46<03:18,  7.64it/s]
 29%|██▉       | 615/2129 [00:46<04:23,  5.76it/s]
 29%|██▉       | 618/2129 [00:47<03:07,  8.06it/s]
 29%|██▉       | 622/2129 [00:47<02:23, 10.49it/s]
 29%|██▉       | 625/2129 [00:47<01:59, 12.64it/s]
 29%|██▉       | 627/2129 [00:47<02:54,  8.62it/s]
 30%|██▉       | 629/2129 [00:48<02:53,  8.62it/s]
 30%|██▉       | 632/2129 [00:48<02:41,  9.28it/s]
 30%|██▉       | 635/2129 [00:48<02:07, 11.69it/s]
 30%|██▉       | 637/2129 [00:48<02:22, 10.43it/s]
 30%|███       | 641/2129 [00:49<02:04, 11.93it/s]
 30%|███       | 644/2129 [00:49<02:06, 11.78it/s]
 30%|███       | 646/2129 [00:49<02:14, 11.00it/s]
 30%|███       | 649/2129 [00:49<02:10, 11.32it/s]
 31%|███       | 651/2129 [00:49<01:57, 12.60it/s]
 31%|███       | 653/2129 [00:50<02:52,  8.55it/s]
 31%|███       | 656/2129 [00:50<02:15, 10.87it/s]
 31%|███       | 658/2129 [00:50<02:07, 11.49it/s]
 31%|███       | 660/2129 [00:50<01:55, 12.67it/s]
 31%|███       | 662/2129 [00:51<03:00,  8.15it/s]
 31%|███       | 664/2129 [00:51<02:59,  8.15it/s]
 31%|███▏      | 667/2129 [00:51<02:48,  8.69it/s]
 31%|███▏      | 670/2129 [00:51<02:16, 10.66it/s]
 32%|███▏      | 672/2129 [00:52<02:41,  9.00it/s]
 32%|███▏      | 675/2129 [00:52<02:09, 11.25it/s]
 32%|███▏      | 677/2129 [00:52<02:28,  9.79it/s]
 32%|███▏      | 679/2129 [00:52<02:23, 10.10it/s]
 32%|███▏      | 681/2129 [00:52<02:08, 11.29it/s]
 32%|███▏      | 683/2129 [00:53<03:22,  7.14it/s]
 32%|███▏      | 685/2129 [00:53<03:24,  7.05it/s]
 32%|███▏      | 686/2129 [00:53<03:18,  7.26it/s]
 32%|███▏      | 687/2129 [00:54<03:51,  6.22it/s]
 32%|███▏      | 689/2129 [00:54<03:13,  7.43it/s]
 32%|███▏      | 691/2129 [00:54<02:35,  9.23it/s]
 33%|███▎      | 693/2129 [00:54<02:13, 10.72it/s]
 33%|███▎      | 695/2129 [00:55<03:08,  7.60it/s]
 33%|███▎      | 697/2129 [00:55<03:10,  7.51it/s]
 33%|███▎      | 700/2129 [00:55<02:19, 10.25it/s]
 33%|███▎      | 704/2129 [00:55<01:35, 14.96it/s]
 33%|███▎      | 707/2129 [00:56<02:42,  8.74it/s]
 33%|███▎      | 709/2129 [00:57<04:29,  5.27it/s]
 33%|███▎      | 712/2129 [00:57<04:18,  5.49it/s]
 34%|███▎      | 714/2129 [00:57<03:59,  5.90it/s]
 34%|███▎      | 717/2129 [00:57<02:55,  8.05it/s]
 34%|███▍      | 719/2129 [00:58<02:45,  8.54it/s]
 34%|███▍      | 721/2129 [00:58<03:24,  6.90it/s]
 34%|███▍      | 723/2129 [00:58<03:11,  7.34it/s]
 34%|███▍      | 725/2129 [00:59<04:12,  5.55it/s]
 34%|███▍      | 726/2129 [00:59<04:15,  5.50it/s]
 34%|███▍      | 727/2129 [00:59<04:19,  5.41it/s]
 34%|███▍      | 728/2129 [00:59<04:25,  5.29it/s]
 34%|███▍      | 730/2129 [01:00<03:15,  7.15it/s]
 34%|███▍      | 733/2129 [01:00<03:12,  7.27it/s]
 34%|███▍      | 734/2129 [01:00<03:23,  6.84it/s]
 35%|███▍      | 736/2129 [01:00<02:40,  8.66it/s]
 35%|███▍      | 739/2129 [01:01<02:21,  9.85it/s]
 35%|███▍      | 741/2129 [01:01<02:02, 11.37it/s]
 35%|███▌      | 748/2129 [01:01<01:02, 22.00it/s]
 35%|███▌      | 751/2129 [01:01<01:13, 18.80it/s]
 35%|███▌      | 754/2129 [01:01<01:54, 11.98it/s]
 36%|███▌      | 756/2129 [01:02<02:21,  9.69it/s]
 36%|███▌      | 758/2129 [01:02<03:01,  7.56it/s]
 36%|███▌      | 760/2129 [01:02<02:36,  8.75it/s]
 36%|███▌      | 762/2129 [01:03<02:37,  8.68it/s]
 36%|███▌      | 764/2129 [01:03<02:38,  8.59it/s]
 36%|███▌      | 766/2129 [01:03<02:26,  9.33it/s]
 36%|███▌      | 768/2129 [01:03<02:45,  8.23it/s]
 36%|███▌      | 769/2129 [01:04<02:59,  7.59it/s]
 36%|███▌      | 771/2129 [01:04<02:28,  9.17it/s]
 36%|███▋      | 773/2129 [01:04<02:02, 11.02it/s]
 36%|███▋      | 775/2129 [01:04<03:13,  7.00it/s]
 36%|███▋      | 777/2129 [01:04<02:55,  7.71it/s]
 37%|███▋      | 779/2129 [01:05<02:23,  9.42it/s]
 37%|███▋      | 781/2129 [01:05<03:08,  7.16it/s]
 37%|███▋      | 783/2129 [01:05<03:14,  6.91it/s]
 37%|███▋      | 785/2129 [01:06<03:29,  6.41it/s]
 37%|███▋      | 787/2129 [01:06<04:02,  5.53it/s]
 37%|███▋      | 790/2129 [01:06<02:47,  7.98it/s]
 37%|███▋      | 793/2129 [01:06<02:07, 10.49it/s]
 37%|███▋      | 795/2129 [01:07<02:32,  8.75it/s]
 37%|███▋      | 797/2129 [01:07<03:16,  6.79it/s]
 38%|███▊      | 799/2129 [01:08<03:11,  6.95it/s]
 38%|███▊      | 800/2129 [01:08<03:27,  6.39it/s]
 38%|███▊      | 802/2129 [01:08<02:52,  7.68it/s]
 38%|███▊      | 803/2129 [01:08<03:16,  6.76it/s]
 38%|███▊      | 806/2129 [01:08<02:09, 10.21it/s]
 38%|███▊      | 809/2129 [01:08<02:00, 10.91it/s]
 38%|███▊      | 811/2129 [01:09<02:11, 10.03it/s]
 38%|███▊      | 813/2129 [01:09<02:27,  8.95it/s]
 38%|███▊      | 816/2129 [01:09<01:52, 11.71it/s]
 38%|███▊      | 818/2129 [01:10<02:30,  8.70it/s]
 39%|███▊      | 820/2129 [01:10<03:08,  6.95it/s]
 39%|███▊      | 822/2129 [01:10<02:36,  8.33it/s]
 39%|███▉      | 825/2129 [01:10<01:59, 10.92it/s]
 39%|███▉      | 827/2129 [01:10<02:12,  9.82it/s]
 39%|███▉      | 829/2129 [01:11<01:59, 10.85it/s]
 39%|███▉      | 831/2129 [01:11<02:12,  9.79it/s]
 39%|███▉      | 833/2129 [01:11<01:57, 11.03it/s]
 39%|███▉      | 837/2129 [01:11<01:24, 15.28it/s]
 39%|███▉      | 839/2129 [01:11<01:29, 14.47it/s]
 40%|███▉      | 842/2129 [01:12<01:38, 13.06it/s]
 40%|███▉      | 844/2129 [01:12<03:14,  6.59it/s]
 40%|███▉      | 846/2129 [01:13<03:07,  6.84it/s]
 40%|███▉      | 848/2129 [01:13<03:56,  5.41it/s]
 40%|███▉      | 850/2129 [01:13<03:10,  6.72it/s]
 40%|████      | 852/2129 [01:13<02:56,  7.25it/s]
 40%|████      | 854/2129 [01:14<02:52,  7.40it/s]
 40%|████      | 855/2129 [01:14<03:12,  6.63it/s]
 40%|████      | 858/2129 [01:14<02:14,  9.46it/s]
 40%|████      | 860/2129 [01:14<02:16,  9.29it/s]
 40%|████      | 862/2129 [01:15<02:21,  8.97it/s]
 41%|████      | 865/2129 [01:15<02:21,  8.94it/s]
 41%|████      | 866/2129 [01:15<03:17,  6.39it/s]
 41%|████      | 869/2129 [01:15<02:21,  8.88it/s]
 41%|████      | 873/2129 [01:16<02:06,  9.93it/s]
 41%|████      | 875/2129 [01:16<01:51, 11.25it/s]
 41%|████▏     | 879/2129 [01:16<01:42, 12.24it/s]
 41%|████▏     | 881/2129 [01:16<01:57, 10.59it/s]
 41%|████▏     | 883/2129 [01:17<01:44, 11.93it/s]
 42%|████▏     | 885/2129 [01:17<01:36, 12.95it/s]
 42%|████▏     | 887/2129 [01:18<03:47,  5.45it/s]
 42%|████▏     | 890/2129 [01:18<03:41,  5.60it/s]
 42%|████▏     | 891/2129 [01:18<03:41,  5.58it/s]
 42%|████▏     | 893/2129 [01:19<04:03,  5.07it/s]
 42%|████▏     | 895/2129 [01:19<04:23,  4.68it/s]
 42%|████▏     | 898/2129 [01:20<04:02,  5.07it/s]
 42%|████▏     | 900/2129 [01:20<03:13,  6.35it/s]
 42%|████▏     | 902/2129 [01:20<03:15,  6.26it/s]
 42%|████▏     | 903/2129 [01:20<03:22,  6.06it/s]
 43%|████▎     | 905/2129 [01:21<02:41,  7.56it/s]
 43%|████▎     | 907/2129 [01:21<03:33,  5.71it/s]
 43%|████▎     | 908/2129 [01:21<04:08,  4.91it/s]
 43%|████▎     | 910/2129 [01:22<03:06,  6.52it/s]
 43%|████▎     | 911/2129 [01:22<04:06,  4.95it/s]
 43%|████▎     | 912/2129 [01:22<04:01,  5.04it/s]
 43%|████▎     | 914/2129 [01:23<04:08,  4.88it/s]
 43%|████▎     | 916/2129 [01:23<03:37,  5.57it/s]
 43%|████▎     | 918/2129 [01:23<02:46,  7.29it/s]
 43%|████▎     | 924/2129 [01:23<01:38, 12.21it/s]
 43%|████▎     | 926/2129 [01:24<01:59, 10.09it/s]
 44%|████▎     | 928/2129 [01:24<03:07,  6.40it/s]
 44%|████▎     | 929/2129 [01:24<03:15,  6.14it/s]
 44%|████▎     | 931/2129 [01:25<03:27,  5.76it/s]
 44%|████▍     | 933/2129 [01:25<02:46,  7.20it/s]
 44%|████▍     | 936/2129 [01:25<02:45,  7.21it/s]
 44%|████▍     | 937/2129 [01:26<03:03,  6.49it/s]
 44%|████▍     | 938/2129 [01:26<03:09,  6.30it/s]
 44%|████▍     | 939/2129 [01:26<04:11,  4.73it/s]
 44%|████▍     | 941/2129 [01:26<03:04,  6.46it/s]
 44%|████▍     | 943/2129 [01:27<03:16,  6.02it/s]
 44%|████▍     | 944/2129 [01:27<03:22,  5.86it/s]
 44%|████▍     | 945/2129 [01:27<03:35,  5.48it/s]
 44%|████▍     | 946/2129 [01:28<04:57,  3.98it/s]
 44%|████▍     | 947/2129 [01:28<04:37,  4.25it/s]
 45%|████▍     | 949/2129 [01:28<03:14,  6.07it/s]
 45%|████▍     | 950/2129 [01:28<03:48,  5.17it/s]
 45%|████▍     | 952/2129 [01:28<02:42,  7.26it/s]
 45%|████▍     | 955/2129 [01:29<02:29,  7.84it/s]
 45%|████▍     | 957/2129 [01:29<02:05,  9.36it/s]
 45%|████▌     | 959/2129 [01:29<02:14,  8.69it/s]
 45%|████▌     | 961/2129 [01:29<03:03,  6.38it/s]
 45%|████▌     | 963/2129 [01:30<02:41,  7.21it/s]
 45%|████▌     | 965/2129 [01:30<02:21,  8.20it/s]
 45%|████▌     | 967/2129 [01:30<01:56,  9.96it/s]
 46%|████▌     | 969/2129 [01:30<02:04,  9.35it/s]
 46%|████▌     | 971/2129 [01:31<03:24,  5.67it/s]
 46%|████▌     | 973/2129 [01:31<03:41,  5.22it/s]
 46%|████▌     | 974/2129 [01:32<04:20,  4.43it/s]
 46%|████▌     | 976/2129 [01:32<03:14,  5.93it/s]
 46%|████▌     | 977/2129 [01:32<03:15,  5.88it/s]
 46%|████▌     | 979/2129 [01:32<02:33,  7.48it/s]
 46%|████▌     | 981/2129 [01:33<03:13,  5.92it/s]
 46%|████▌     | 983/2129 [01:33<02:34,  7.41it/s]
 46%|████▋     | 985/2129 [01:33<03:02,  6.27it/s]
 46%|████▋     | 988/2129 [01:33<02:23,  7.96it/s]
 47%|████▋     | 990/2129 [01:33<02:00,  9.49it/s]
 47%|████▋     | 992/2129 [01:34<01:42, 11.13it/s]
 47%|████▋     | 994/2129 [01:34<02:29,  7.59it/s]
 47%|████▋     | 997/2129 [01:34<01:46, 10.62it/s]
 47%|████▋     | 999/2129 [01:34<01:44, 10.86it/s]
 47%|████▋     | 1001/2129 [01:35<02:09,  8.70it/s]
 47%|████▋     | 1003/2129 [01:35<02:04,  9.04it/s]
 47%|████▋     | 1006/2129 [01:35<01:57,  9.52it/s]
 47%|████▋     | 1008/2129 [01:36<02:32,  7.36it/s]
 47%|████▋     | 1010/2129 [01:36<03:04,  6.07it/s]
 48%|████▊     | 1012/2129 [01:37<03:26,  5.42it/s]
 48%|████▊     | 1013/2129 [01:37<04:08,  4.49it/s]
 48%|████▊     | 1015/2129 [01:37<03:31,  5.27it/s]
 48%|████▊     | 1016/2129 [01:37<03:37,  5.12it/s]
 48%|████▊     | 1018/2129 [01:38<03:56,  4.69it/s]
 48%|████▊     | 1019/2129 [01:38<04:46,  3.88it/s]
 48%|████▊     | 1021/2129 [01:39<04:28,  4.13it/s]
 48%|████▊     | 1023/2129 [01:39<04:23,  4.19it/s]
 48%|████▊     | 1024/2129 [01:40<04:51,  3.80it/s]
 48%|████▊     | 1027/2129 [01:40<03:00,  6.12it/s]
 48%|████▊     | 1028/2129 [01:40<03:55,  4.68it/s]
 48%|████▊     | 1030/2129 [01:41<04:03,  4.52it/s]
 48%|████▊     | 1032/2129 [01:41<04:16,  4.28it/s]
 49%|████▊     | 1035/2129 [01:41<02:46,  6.56it/s]
 49%|████▊     | 1037/2129 [01:41<02:29,  7.32it/s]
 49%|████▉     | 1040/2129 [01:42<02:16,  7.97it/s]
 49%|████▉     | 1042/2129 [01:42<02:12,  8.21it/s]
 49%|████▉     | 1045/2129 [01:42<01:37, 11.10it/s]
 49%|████▉     | 1048/2129 [01:42<01:37, 11.09it/s]
 49%|████▉     | 1051/2129 [01:43<01:38, 10.90it/s]
 50%|████▉     | 1054/2129 [01:43<01:20, 13.38it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 308.76it/s]

[[np.int64(0), False, 7], [np.int64(1), False, 13], [np.int64(2), False, 7], [np.int64(3), False, 13], [np.int64(4), False, 3], [np.int64(5), False, 11], [np.int64(6), False, 7], [np.int64(8), False, 10], [np.int64(9), False, 11], [np.int64(12), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.6737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6229, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [16:56<2:07:35, 77.33s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [16:56<1:28:29, 54.18s/it]

tensor(11.6719, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7981, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9975, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [16:57<29:32, 18.66s/it]

tensor(11.6740, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0684, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1042, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [16:57<14:15,  9.20s/it]

tensor(11.6788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1543, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [16:57<06:55,  4.57s/it]

tensor(11.6846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1550, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1500, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [16:57<03:24,  2.30s/it]

tensor(11.6813, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1695, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2124, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [16:58<01:43,  1.19s/it]

tensor(11.6693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2486, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2769, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [16:58<00:54,  1.56it/s]

tensor(11.6667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2916, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3080, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [16:58<00:31,  2.67it/s]

tensor(11.6721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3188, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3289, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [16:58<00:19,  4.09it/s]

tensor(11.6684, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3364, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3450, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [16:59<00:16,  4.82it/s]

tensor(11.6622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6590, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3554, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [16:59<00:11,  6.67it/s]

tensor(11.6566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3586, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3636, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [16:59<00:09,  7.56it/s]

tensor(11.6551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3706, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [16:59<00:09,  7.98it/s]

tensor(11.6521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3810, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [17:00<00:08,  8.25it/s]

tensor(11.6478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3841, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3890, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [17:00<00:08,  8.38it/s]

tensor(11.6441, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3919, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3964, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [17:00<00:08,  8.35it/s]

tensor(11.6409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4056, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [17:00<00:07,  8.37it/s]

tensor(11.6391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4074, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4119, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [17:01<00:07,  8.32it/s]

tensor(11.6366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4150, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [17:01<00:07,  8.40it/s]

tensor(11.6341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4156, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4168, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [17:01<00:07,  8.42it/s]

tensor(11.6319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4188, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4217, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [17:01<00:06,  8.51it/s]

tensor(11.6295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4246, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6282, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4250, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [17:01<00:06,  8.47it/s]

tensor(11.6270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4280, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4311, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [17:02<00:06,  8.49it/s]

tensor(11.6243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4316, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4352, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [17:02<00:06,  8.38it/s]

tensor(11.6220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4403, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4422, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [17:02<00:05,  8.39it/s]

tensor(11.6200, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4448, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([242, 115, 152, 113, 140,  99,  87,  58,  89, 113, 189,  74, 215, 443])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:12, 29.30it/s]
  0%|          | 10/2129 [00:00<00:41, 51.24it/s]
  1%|          | 18/2129 [00:00<00:34, 62.03it/s]
  1%|          | 25/2129 [00:00<00:41, 50.68it/s]
  1%|▏         | 31/2129 [00:00<00:39, 52.84it/s]
  2%|▏         | 39/2129 [00:00<00:36, 57.10it/s]
  2%|▏         | 46/2129 [00:00<00:34, 60.76it/s]
  2%|▏         | 53/2129 [00:00<00:33, 62.68it/s]
  3%|▎         | 60/2129 [00:01<00:37, 54.50it/s]
  3%|▎         | 67/2129 [00:01<00:35, 58.22it/s]
  3%|▎         | 74/2129 [00:01<00:37, 54.68it/s]
  4%|▍         | 80/2129 [00:01<00:57, 35.53it/s]
  4%|▍         | 85/2129 [00:01<01:06, 30.54it/s]
  4%|▍         | 92/2129 [00:02<00:55, 36.55it/s]
  5%|▍         | 97/2129 [00:02<00:57, 35.36it/s]
  5%|▍         | 103/2129 [00:02<01:28, 22.78it/s]
  5%|▌         | 107/2129 [00:02<01:26, 23.51it/s]
  5%|▌         | 112/2129 [00:02<01:15, 26.74it/s]
  5%|▌         | 116/2129 [00:03<01:11, 28.15it/s]
  6%|▌         | 120/2129 [00:03<01:06, 30.14it/s]
  6%|▌         | 127/2129 [00:03<00:51, 38.69it/s]
  6%|▌         | 133/2129 [00:03<00:45, 43.73it/s]
  7%|▋         | 142/2129 [00:03<00:36, 53.88it/s]
  7%|▋         | 148/2129 [00:03<00:39, 49.79it/s]
  7%|▋         | 154/2129 [00:03<00:38, 51.78it/s]
  8%|▊         | 160/2129 [00:04<01:14, 26.48it/s]
  8%|▊         | 165/2129 [00:04<01:58, 16.61it/s]
  8%|▊         | 171/2129 [00:05<02:12, 14.76it/s]
  8%|▊         | 174/2129 [00:05<02:02, 15.91it/s]
  8%|▊         | 178/2129 [00:05<02:26, 13.34it/s]
  9%|▊         | 182/2129 [00:06<02:03, 15.77it/s]
  9%|▊         | 185/2129 [00:06<02:42, 11.98it/s]
  9%|▉         | 189/2129 [00:06<02:08, 15.08it/s]
  9%|▉         | 192/2129 [00:07<02:55, 11.07it/s]
  9%|▉         | 196/2129 [00:07<02:14, 14.33it/s]
  9%|▉         | 200/2129 [00:07<02:44, 11.75it/s]
 10%|▉         | 203/2129 [00:07<02:23, 13.40it/s]
 10%|▉         | 209/2129 [00:07<01:37, 19.77it/s]
 10%|█         | 213/2129 [00:08<02:20, 13.61it/s]
 10%|█         | 216/2129 [00:08<02:45, 11.59it/s]
 10%|█         | 221/2129 [00:08<02:00, 15.81it/s]
 11%|█         | 228/2129 [00:09<01:22, 22.98it/s]
 11%|█         | 233/2129 [00:09<01:42, 18.58it/s]
 11%|█         | 237/2129 [00:09<01:36, 19.70it/s]
 11%|█▏        | 240/2129 [00:09<01:37, 19.32it/s]
 11%|█▏        | 244/2129 [00:09<01:23, 22.53it/s]
 12%|█▏        | 247/2129 [00:10<01:49, 17.24it/s]
 12%|█▏        | 250/2129 [00:10<02:40, 11.68it/s]
 12%|█▏        | 252/2129 [00:10<02:56, 10.61it/s]
 12%|█▏        | 254/2129 [00:11<02:39, 11.73it/s]
 12%|█▏        | 258/2129 [00:11<02:33, 12.16it/s]
 12%|█▏        | 262/2129 [00:11<02:02, 15.21it/s]
 13%|█▎        | 267/2129 [00:11<02:08, 14.45it/s]
 13%|█▎        | 269/2129 [00:11<02:03, 15.00it/s]
 13%|█▎        | 272/2129 [00:12<01:46, 17.36it/s]
 13%|█▎        | 276/2129 [00:12<01:29, 20.77it/s]
 13%|█▎        | 280/2129 [00:12<01:15, 24.55it/s]
 13%|█▎        | 284/2129 [00:12<01:11, 25.83it/s]
 13%|█▎        | 287/2129 [00:12<01:13, 25.13it/s]
 14%|█▍        | 294/2129 [00:12<01:21, 22.63it/s]
 14%|█▍        | 297/2129 [00:13<01:19, 22.92it/s]
 14%|█▍        | 303/2129 [00:13<01:03, 28.61it/s]
 14%|█▍        | 307/2129 [00:13<02:01, 15.04it/s]
 15%|█▍        | 310/2129 [00:13<01:52, 16.18it/s]
 15%|█▍        | 313/2129 [00:14<03:26,  8.78it/s]
 15%|█▍        | 315/2129 [00:15<03:43,  8.12it/s]
 15%|█▌        | 322/2129 [00:15<02:08, 14.05it/s]
 15%|█▌        | 325/2129 [00:15<02:44, 10.95it/s]
 15%|█▌        | 328/2129 [00:16<03:12,  9.36it/s]
 16%|█▌        | 330/2129 [00:16<02:54, 10.31it/s]
 16%|█▌        | 334/2129 [00:16<03:04,  9.72it/s]
 16%|█▌        | 336/2129 [00:16<02:48, 10.62it/s]
 16%|█▌        | 338/2129 [00:17<03:43,  8.00it/s]
 16%|█▌        | 342/2129 [00:17<02:35, 11.50it/s]
 16%|█▌        | 344/2129 [00:17<03:33,  8.36it/s]
 16%|█▋        | 347/2129 [00:17<02:45, 10.79it/s]
 16%|█▋        | 349/2129 [00:18<03:27,  8.60it/s]
 16%|█▋        | 351/2129 [00:18<04:20,  6.83it/s]
 17%|█▋        | 355/2129 [00:19<03:24,  8.66it/s]
 17%|█▋        | 357/2129 [00:19<03:43,  7.92it/s]
 17%|█▋        | 359/2129 [00:19<03:26,  8.57it/s]
 17%|█▋        | 361/2129 [00:20<04:28,  6.58it/s]
 17%|█▋        | 362/2129 [00:20<05:45,  5.12it/s]
 17%|█▋        | 365/2129 [00:20<03:52,  7.57it/s]
 18%|█▊        | 373/2129 [00:21<02:38, 11.05it/s]
 18%|█▊        | 375/2129 [00:21<02:28, 11.80it/s]
 18%|█▊        | 377/2129 [00:21<03:19,  8.80it/s]
 18%|█▊        | 380/2129 [00:22<03:41,  7.90it/s]
 18%|█▊        | 382/2129 [00:22<03:11,  9.12it/s]
 18%|█▊        | 384/2129 [00:22<04:17,  6.79it/s]
 18%|█▊        | 386/2129 [00:23<04:54,  5.91it/s]
 18%|█▊        | 388/2129 [00:23<03:59,  7.27it/s]
 18%|█▊        | 391/2129 [00:23<04:30,  6.43it/s]
 19%|█▊        | 394/2129 [00:24<04:49,  6.00it/s]
 19%|█▊        | 397/2129 [00:24<03:37,  7.97it/s]
 19%|█▉        | 400/2129 [00:25<03:53,  7.41it/s]
 19%|█▉        | 403/2129 [00:25<03:00,  9.58it/s]
 19%|█▉        | 408/2129 [00:25<02:56,  9.72it/s]
 19%|█▉        | 411/2129 [00:25<02:26, 11.76it/s]
 20%|█▉        | 418/2129 [00:25<01:29, 19.17it/s]
 20%|█▉        | 424/2129 [00:26<01:08, 24.82it/s]
 20%|██        | 430/2129 [00:26<01:36, 17.59it/s]
 20%|██        | 433/2129 [00:27<02:51,  9.87it/s]
 20%|██        | 436/2129 [00:27<02:50,  9.91it/s]
 21%|██        | 439/2129 [00:27<02:25, 11.64it/s]
 21%|██        | 444/2129 [00:27<01:45, 16.02it/s]
 21%|██        | 449/2129 [00:28<01:20, 20.81it/s]
 21%|██▏       | 455/2129 [00:28<01:33, 17.83it/s]
 22%|██▏       | 458/2129 [00:28<01:30, 18.53it/s]
 22%|██▏       | 461/2129 [00:29<02:19, 11.92it/s]
 22%|██▏       | 464/2129 [00:29<02:03, 13.53it/s]
 22%|██▏       | 467/2129 [00:29<02:12, 12.54it/s]
 22%|██▏       | 469/2129 [00:29<02:06, 13.11it/s]
 22%|██▏       | 471/2129 [00:30<02:52,  9.63it/s]
 22%|██▏       | 474/2129 [00:30<02:15, 12.18it/s]
 22%|██▏       | 477/2129 [00:30<02:49,  9.75it/s]
 22%|██▏       | 479/2129 [00:30<02:58,  9.26it/s]
 23%|██▎       | 481/2129 [00:31<02:39, 10.33it/s]
 23%|██▎       | 483/2129 [00:31<03:56,  6.95it/s]
 23%|██▎       | 485/2129 [00:32<04:53,  5.61it/s]
 23%|██▎       | 488/2129 [00:32<04:46,  5.72it/s]
 23%|██▎       | 490/2129 [00:33<04:57,  5.52it/s]
 23%|██▎       | 493/2129 [00:33<03:31,  7.74it/s]
 23%|██▎       | 500/2129 [00:33<01:48, 14.97it/s]
 24%|██▎       | 504/2129 [00:33<02:05, 12.99it/s]
 24%|██▍       | 508/2129 [00:33<01:59, 13.60it/s]
 24%|██▍       | 511/2129 [00:34<02:15, 11.92it/s]
 24%|██▍       | 516/2129 [00:34<01:39, 16.25it/s]
 24%|██▍       | 519/2129 [00:34<02:13, 12.08it/s]
 24%|██▍       | 521/2129 [00:35<02:52,  9.31it/s]
 25%|██▍       | 523/2129 [00:35<02:45,  9.69it/s]
 25%|██▍       | 526/2129 [00:35<02:32, 10.50it/s]
 25%|██▍       | 528/2129 [00:35<02:44,  9.71it/s]
 25%|██▍       | 530/2129 [00:36<03:43,  7.15it/s]
 25%|██▍       | 532/2129 [00:36<03:13,  8.26it/s]
 25%|██▌       | 535/2129 [00:37<03:28,  7.65it/s]
 25%|██▌       | 536/2129 [00:37<03:37,  7.34it/s]
 25%|██▌       | 539/2129 [00:37<02:48,  9.44it/s]
 26%|██▌       | 543/2129 [00:37<02:33, 10.35it/s]
 26%|██▌       | 546/2129 [00:37<02:05, 12.58it/s]
 26%|██▌       | 548/2129 [00:38<02:57,  8.91it/s]
 26%|██▌       | 551/2129 [00:38<02:18, 11.40it/s]
 26%|██▌       | 557/2129 [00:38<02:22, 11.01it/s]
 26%|██▋       | 559/2129 [00:39<03:01,  8.65it/s]
 26%|██▋       | 561/2129 [00:39<02:41,  9.73it/s]
 26%|██▋       | 564/2129 [00:39<03:05,  8.43it/s]
 27%|██▋       | 566/2129 [00:40<02:41,  9.71it/s]
 27%|██▋       | 568/2129 [00:40<03:29,  7.46it/s]
 27%|██▋       | 571/2129 [00:41<03:48,  6.81it/s]
 27%|██▋       | 575/2129 [00:41<02:36,  9.92it/s]
 27%|██▋       | 577/2129 [00:41<03:21,  7.68it/s]
 27%|██▋       | 579/2129 [00:41<02:54,  8.86it/s]
 27%|██▋       | 581/2129 [00:42<03:45,  6.87it/s]
 27%|██▋       | 583/2129 [00:42<03:07,  8.25it/s]
 27%|██▋       | 585/2129 [00:42<03:56,  6.54it/s]
 28%|██▊       | 587/2129 [00:43<04:32,  5.66it/s]
 28%|██▊       | 589/2129 [00:43<05:05,  5.04it/s]
 28%|██▊       | 590/2129 [00:44<06:10,  4.15it/s]
 28%|██▊       | 592/2129 [00:44<04:40,  5.47it/s]
 28%|██▊       | 594/2129 [00:44<03:41,  6.92it/s]
 28%|██▊       | 599/2129 [00:44<03:05,  8.24it/s]
 28%|██▊       | 601/2129 [00:45<02:40,  9.49it/s]
 28%|██▊       | 603/2129 [00:45<03:27,  7.36it/s]
 28%|██▊       | 605/2129 [00:46<04:15,  5.96it/s]
 29%|██▊       | 607/2129 [00:46<03:29,  7.26it/s]
 29%|██▊       | 610/2129 [00:46<03:39,  6.91it/s]
 29%|██▊       | 611/2129 [00:47<04:50,  5.22it/s]
 29%|██▉       | 613/2129 [00:47<05:20,  4.74it/s]
 29%|██▉       | 616/2129 [00:47<03:40,  6.87it/s]
 29%|██▉       | 623/2129 [00:47<01:48, 13.86it/s]
 29%|██▉       | 626/2129 [00:48<02:25, 10.30it/s]
 30%|██▉       | 629/2129 [00:48<02:52,  8.69it/s]
 30%|██▉       | 632/2129 [00:49<03:02,  8.19it/s]
 30%|██▉       | 634/2129 [00:49<02:45,  9.05it/s]
 30%|██▉       | 636/2129 [00:49<02:50,  8.78it/s]
 30%|██▉       | 638/2129 [00:49<02:32,  9.79it/s]
 30%|███       | 641/2129 [00:50<02:27, 10.07it/s]
 30%|███       | 643/2129 [00:50<02:14, 11.07it/s]
 30%|███       | 645/2129 [00:50<03:02,  8.12it/s]
 30%|███       | 648/2129 [00:50<02:24, 10.28it/s]
 31%|███       | 650/2129 [00:51<02:39,  9.28it/s]
 31%|███       | 653/2129 [00:51<02:33,  9.59it/s]
 31%|███       | 655/2129 [00:51<02:22, 10.36it/s]
 31%|███       | 658/2129 [00:51<02:28,  9.90it/s]
 31%|███       | 660/2129 [00:51<02:19, 10.52it/s]
 31%|███       | 662/2129 [00:52<03:07,  7.82it/s]
 31%|███       | 663/2129 [00:52<03:32,  6.90it/s]
 31%|███▏      | 666/2129 [00:52<02:30,  9.73it/s]
 31%|███▏      | 668/2129 [00:52<02:29,  9.77it/s]
 31%|███▏      | 670/2129 [00:53<02:09, 11.26it/s]
 32%|███▏      | 672/2129 [00:53<01:54, 12.69it/s]
 32%|███▏      | 677/2129 [00:53<01:42, 14.19it/s]
 32%|███▏      | 679/2129 [00:53<01:44, 13.92it/s]
 32%|███▏      | 682/2129 [00:54<02:30,  9.62it/s]
 32%|███▏      | 684/2129 [00:54<02:18, 10.45it/s]
 32%|███▏      | 686/2129 [00:54<02:27,  9.79it/s]
 32%|███▏      | 688/2129 [00:54<02:28,  9.68it/s]
 32%|███▏      | 690/2129 [00:55<02:57,  8.12it/s]
 33%|███▎      | 692/2129 [00:55<02:28,  9.69it/s]
 33%|███▎      | 694/2129 [00:55<03:22,  7.10it/s]
 33%|███▎      | 696/2129 [00:56<04:00,  5.96it/s]
 33%|███▎      | 699/2129 [00:56<02:51,  8.36it/s]
 33%|███▎      | 705/2129 [00:56<02:22, 10.01it/s]
 33%|███▎      | 707/2129 [00:57<02:58,  7.95it/s]
 33%|███▎      | 709/2129 [00:58<04:31,  5.24it/s]
 33%|███▎      | 712/2129 [00:58<04:24,  5.36it/s]
 33%|███▎      | 713/2129 [00:59<05:06,  4.62it/s]
 34%|███▎      | 715/2129 [00:59<04:05,  5.76it/s]
 34%|███▎      | 717/2129 [00:59<03:17,  7.14it/s]
 34%|███▍      | 721/2129 [00:59<03:04,  7.63it/s]
 34%|███▍      | 723/2129 [01:00<03:40,  6.36it/s]
 34%|███▍      | 724/2129 [01:00<04:43,  4.95it/s]
 34%|███▍      | 726/2129 [01:01<04:57,  4.72it/s]
 34%|███▍      | 728/2129 [01:01<05:16,  4.42it/s]
 34%|███▍      | 731/2129 [01:01<03:37,  6.44it/s]
 34%|███▍      | 733/2129 [01:02<03:59,  5.83it/s]
 34%|███▍      | 734/2129 [01:02<04:58,  4.67it/s]
 35%|███▍      | 736/2129 [01:02<03:52,  5.99it/s]
 35%|███▍      | 739/2129 [01:03<03:45,  6.16it/s]
 35%|███▍      | 742/2129 [01:03<02:43,  8.50it/s]
 35%|███▌      | 748/2129 [01:03<01:31, 15.11it/s]
 35%|███▌      | 751/2129 [01:03<02:06, 10.87it/s]
 35%|███▌      | 754/2129 [01:04<03:23,  6.76it/s]
 36%|███▌      | 756/2129 [01:05<03:50,  5.96it/s]
 36%|███▌      | 759/2129 [01:05<02:53,  7.89it/s]
 36%|███▌      | 762/2129 [01:05<03:03,  7.47it/s]
 36%|███▌      | 764/2129 [01:06<03:36,  6.32it/s]
 36%|███▌      | 769/2129 [01:06<02:59,  7.56it/s]
 36%|███▋      | 772/2129 [01:06<02:26,  9.27it/s]
 36%|███▋      | 775/2129 [01:07<02:42,  8.32it/s]
 36%|███▋      | 777/2129 [01:07<02:25,  9.31it/s]
 37%|███▋      | 780/2129 [01:08<02:42,  8.29it/s]
 37%|███▋      | 782/2129 [01:08<03:28,  6.45it/s]
 37%|███▋      | 785/2129 [01:09<03:25,  6.55it/s]
 37%|███▋      | 787/2129 [01:09<03:41,  6.05it/s]
 37%|███▋      | 790/2129 [01:09<02:43,  8.17it/s]
 37%|███▋      | 792/2129 [01:09<02:20,  9.52it/s]
 37%|███▋      | 796/2129 [01:09<02:07, 10.43it/s]
 37%|███▋      | 798/2129 [01:10<02:22,  9.32it/s]
 38%|███▊      | 800/2129 [01:10<02:13,  9.95it/s]
 38%|███▊      | 802/2129 [01:10<02:12, 10.00it/s]
 38%|███▊      | 806/2129 [01:10<01:33, 14.10it/s]
 38%|███▊      | 810/2129 [01:11<01:31, 14.34it/s]
 38%|███▊      | 813/2129 [01:11<01:50, 11.93it/s]
 38%|███▊      | 817/2129 [01:11<01:25, 15.36it/s]
 39%|███▊      | 824/2129 [01:11<00:54, 23.73it/s]
 39%|███▉      | 828/2129 [01:12<01:20, 16.16it/s]
 39%|███▉      | 832/2129 [01:12<01:08, 18.98it/s]
 39%|███▉      | 838/2129 [01:12<01:21, 15.84it/s]
 40%|███▉      | 841/2129 [01:12<01:18, 16.51it/s]
 40%|███▉      | 844/2129 [01:13<02:00, 10.70it/s]
 40%|███▉      | 846/2129 [01:13<02:01, 10.57it/s]
 40%|███▉      | 848/2129 [01:14<02:41,  7.92it/s]
 40%|███▉      | 850/2129 [01:14<02:24,  8.85it/s]
 40%|████      | 852/2129 [01:14<02:37,  8.12it/s]
 40%|████      | 854/2129 [01:14<02:23,  8.86it/s]
 40%|████      | 856/2129 [01:14<02:25,  8.75it/s]
 40%|████      | 858/2129 [01:15<02:05, 10.12it/s]
 40%|████      | 860/2129 [01:15<02:26,  8.68it/s]
 40%|████      | 862/2129 [01:15<02:43,  7.73it/s]
 41%|████      | 864/2129 [01:15<02:18,  9.14it/s]
 41%|████      | 866/2129 [01:16<03:04,  6.86it/s]
 41%|████      | 869/2129 [01:16<02:14,  9.35it/s]
 41%|████      | 871/2129 [01:16<01:55, 10.91it/s]
 41%|████      | 873/2129 [01:17<03:01,  6.92it/s]
 41%|████      | 877/2129 [01:17<01:57, 10.69it/s]
 41%|████▏     | 879/2129 [01:17<02:05, 10.00it/s]
 41%|████▏     | 881/2129 [01:17<01:50, 11.32it/s]
 42%|████▏     | 886/2129 [01:18<02:02, 10.19it/s]
 42%|████▏     | 888/2129 [01:18<02:40,  7.73it/s]
 42%|████▏     | 890/2129 [01:18<02:20,  8.82it/s]
 42%|████▏     | 892/2129 [01:18<02:00, 10.23it/s]
 42%|████▏     | 894/2129 [01:18<01:46, 11.64it/s]
 42%|████▏     | 896/2129 [01:19<02:46,  7.39it/s]
 42%|████▏     | 898/2129 [01:19<02:54,  7.07it/s]
 42%|████▏     | 901/2129 [01:19<02:03,  9.91it/s]
 42%|████▏     | 903/2129 [01:20<03:02,  6.71it/s]
 43%|████▎     | 905/2129 [01:20<02:30,  8.12it/s]
 43%|████▎     | 907/2129 [01:20<02:29,  8.18it/s]
 43%|████▎     | 910/2129 [01:20<01:48, 11.23it/s]
 43%|████▎     | 912/2129 [01:21<02:19,  8.72it/s]
 43%|████▎     | 914/2129 [01:21<03:01,  6.71it/s]
 43%|████▎     | 916/2129 [01:21<02:48,  7.22it/s]
 43%|████▎     | 919/2129 [01:22<02:08,  9.39it/s]
 43%|████▎     | 924/2129 [01:22<01:20, 14.98it/s]
 44%|████▎     | 927/2129 [01:22<02:14,  8.97it/s]
 44%|████▎     | 929/2129 [01:23<02:29,  8.01it/s]
 44%|████▍     | 935/2129 [01:23<01:27, 13.64it/s]
 44%|████▍     | 938/2129 [01:24<02:54,  6.82it/s]
 44%|████▍     | 940/2129 [01:24<03:14,  6.11it/s]
 44%|████▍     | 943/2129 [01:25<02:28,  7.98it/s]
 44%|████▍     | 945/2129 [01:25<03:01,  6.51it/s]
 44%|████▍     | 947/2129 [01:25<02:38,  7.44it/s]
 45%|████▍     | 950/2129 [01:25<02:12,  8.91it/s]
 45%|████▍     | 952/2129 [01:26<01:58,  9.96it/s]
 45%|████▍     | 955/2129 [01:26<01:34, 12.46it/s]
 45%|████▍     | 958/2129 [01:26<01:48, 10.76it/s]
 45%|████▌     | 960/2129 [01:26<01:49, 10.65it/s]
 45%|████▌     | 962/2129 [01:26<01:53, 10.27it/s]
 45%|████▌     | 964/2129 [01:27<02:14,  8.68it/s]
 45%|████▌     | 967/2129 [01:27<01:41, 11.44it/s]
 46%|████▌     | 969/2129 [01:27<02:05,  9.22it/s]
 46%|████▌     | 971/2129 [01:28<02:52,  6.73it/s]
 46%|████▌     | 973/2129 [01:28<02:25,  7.95it/s]
 46%|████▌     | 975/2129 [01:28<02:35,  7.43it/s]
 46%|████▌     | 977/2129 [01:29<02:54,  6.62it/s]
 46%|████▌     | 979/2129 [01:29<02:31,  7.57it/s]
 46%|████▌     | 981/2129 [01:29<02:29,  7.67it/s]
 46%|████▌     | 983/2129 [01:29<02:10,  8.79it/s]
 46%|████▋     | 985/2129 [01:29<02:13,  8.56it/s]
 46%|████▋     | 988/2129 [01:30<02:02,  9.34it/s]
 47%|████▋     | 991/2129 [01:30<01:39, 11.43it/s]
 47%|████▋     | 993/2129 [01:30<01:51, 10.16it/s]
 47%|████▋     | 996/2129 [01:30<01:32, 12.24it/s]
 47%|████▋     | 1002/2129 [01:31<01:20, 13.94it/s]
 47%|████▋     | 1004/2129 [01:31<01:17, 14.60it/s]
 47%|████▋     | 1010/2129 [01:31<01:30, 12.43it/s]
 48%|████▊     | 1012/2129 [01:31<01:25, 13.12it/s]
 48%|████▊     | 1014/2129 [01:32<02:00,  9.28it/s]
 48%|████▊     | 1016/2129 [01:33<03:24,  5.43it/s]
 48%|████▊     | 1018/2129 [01:33<02:50,  6.51it/s]
 48%|████▊     | 1020/2129 [01:33<03:16,  5.64it/s]
 48%|████▊     | 1024/2129 [01:34<02:55,  6.30it/s]
 48%|████▊     | 1026/2129 [01:34<02:28,  7.43it/s]
 48%|████▊     | 1028/2129 [01:34<02:54,  6.31it/s]
 48%|████▊     | 1030/2129 [01:35<03:22,  5.42it/s]
 49%|████▊     | 1033/2129 [01:35<02:25,  7.54it/s]
 49%|████▉     | 1039/2129 [01:35<01:20, 13.53it/s]
 49%|████▉     | 1042/2129 [01:36<02:26,  7.43it/s]
 49%|████▉     | 1046/2129 [01:36<01:48, 10.01it/s]
 49%|████▉     | 1049/2129 [01:37<02:05,  8.63it/s]
 49%|████▉     | 1051/2129 [01:37<02:34,  6.98it/s]
 50%|████▉     | 1054/2129 [01:37<02:00,  8.91it/s]
 50%|████▉     | 1056/2129 [01:38<03:17,  5.44it/s]
 50%|████▉     | 1058/2129 [01:39<03:34,  5.00it/s]
 50%|████▉     | 1060/2129 [01:39<03:20,  5.33it/s]
 50%|████▉     | 1063/2129 [01:39<02:22,  7.46it/s]
 50%|█████     | 1065/2129 [01:39<02:40,  6.63it/s]
 50%|█████     | 1068/2129 [01:40<02:23,  7.39it/s]
 50%|█████     | 1070/2129 [01:40<02:38,  6.69it/s]
 50%|█████     | 1071/2129 [01:41<03:22,  5.22it/s]
 50%|█████     | 1073/2129 [01:41<02:38,  6.68it/s]
 51%|█████     | 1077/2129 [01:41<02:23,  7.31it/s]
 51%|█████     | 1080/2129 [01:42<02:41,  6.51it/s]
 51%|█████     | 1083/2129 [01:42<02:03,  8.50it/s]
 51%|█████     | 1085/2129 [01:42<02:31,  6.90it/s]
 51%|█████     | 1087/2129 [01:42<02:08,  8.11it/s]
 51%|█████     | 1091/2129 [01:43<01:45,  9.80it/s]
 51%|█████▏    | 1093/2129 [01:43<01:36, 10.78it/s]
 51%|█████▏    | 1095/2129 [01:43<02:16,  7.58it/s]
 52%|█████▏    | 1099/2129 [01:44<01:30, 11.35it/s]
 52%|█████▏    | 1103/2129 [01:44<01:42, 10.01it/s]
 52%|█████▏    | 1106/2129 [01:44<02:00,  8.49it/s]
 52%|█████▏    | 1108/2129 [01:45<02:25,  7.01it/s]
 52%|█████▏    | 1110/2129 [01:46<03:35,  4.74it/s]
 52%|█████▏    | 1111/2129 [01:46<04:03,  4.18it/s]
 52%|█████▏    | 1112/2129 [01:47<04:38,  3.66it/s]
 52%|█████▏    | 1114/2129 [01:47<04:30,  3.75it/s]
 52%|█████▏    | 1116/2129 [01:48<04:30,  3.74it/s]
 53%|█████▎    | 1118/2129 [01:48<04:43,  3.57it/s]
 53%|█████▎    | 1120/2129 [01:49<04:35,  3.67it/s]
 53%|█████▎    | 1123/2129 [01:49<03:59,  4.20it/s]
 53%|█████▎    | 1126/2129 [01:50<03:38,  4.59it/s]
 53%|█████▎    | 1127/2129 [01:50<03:39,  4.56it/s]
 53%|█████▎    | 1129/2129 [01:50<02:54,  5.74it/s]
 53%|█████▎    | 1131/2129 [01:51<02:50,  5.86it/s]
 53%|█████▎    | 1132/2129 [01:51<03:10,  5.23it/s]
 53%|█████▎    | 1135/2129 [01:51<03:01,  5.46it/s]
 53%|█████▎    | 1137/2129 [01:52<02:23,  6.92it/s]
 53%|█████▎    | 1139/2129 [01:52<02:33,  6.44it/s]
 54%|█████▎    | 1141/2129 [01:52<02:36,  6.32it/s]
 54%|█████▎    | 1144/2129 [01:52<01:51,  8.81it/s]
 54%|█████▍    | 1146/2129 [01:53<02:27,  6.65it/s]
 54%|█████▍    | 1149/2129 [01:53<01:49,  8.98it/s]
 54%|█████▍    | 1151/2129 [01:53<01:35, 10.24it/s]
 54%|█████▍    | 1153/2129 [01:53<01:59,  8.19it/s]
 54%|█████▍    | 1155/2129 [01:54<01:56,  8.36it/s]
 54%|█████▍    | 1157/2129 [01:55<03:25,  4.72it/s]
 54%|█████▍    | 1159/2129 [01:55<03:21,  4.81it/s]
 55%|█████▍    | 1162/2129 [01:55<02:21,  6.81it/s]
 55%|█████▍    | 1164/2129 [01:56<02:50,  5.67it/s]
 55%|█████▍    | 1166/2129 [01:56<03:12,  5.01it/s]
 55%|█████▍    | 1167/2129 [01:57<03:51,  4.16it/s]
 55%|█████▍    | 1169/2129 [01:57<02:59,  5.36it/s]
 55%|█████▌    | 1174/2129 [01:57<02:25,  6.57it/s]
 55%|█████▌    | 1176/2129 [01:58<02:43,  5.83it/s]
 55%|█████▌    | 1178/2129 [01:58<02:14,  7.06it/s]
 55%|█████▌    | 1180/2129 [01:59<03:26,  4.61it/s]
 56%|█████▌    | 1183/2129 [01:59<02:26,  6.48it/s]
 56%|█████▌    | 1185/2129 [01:59<02:45,  5.69it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 313.27it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 10], [np.int64(2), False, 10], [np.int64(3), False, 12], [np.int64(4), False, 13], [np.int64(5), False, 10], [np.int64(6), False, 2], [np.int64(7), False, 12], [np.int64(8), False, 13], [np.int64(9), False, 11], [np.int64(12), False, 13]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.6190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9711, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [20:29<50:49, 62.23s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [20:29<34:53, 43.61s/it]

tensor(11.6255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2734, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7368, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [20:30<11:16, 15.03s/it]

tensor(11.7264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1693, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1532, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [20:30<05:19,  7.43s/it]

tensor(11.8288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9974, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9784, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [20:30<02:31,  3.70s/it]

tensor(11.7738, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0891, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2355, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [20:30<01:12,  1.87s/it]

tensor(11.7100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3153, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3434, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [20:31<00:36,  1.02it/s]

tensor(11.7308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3325, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3222, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [20:31<00:18,  1.86it/s]

tensor(11.7632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3625, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3912, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [20:31<00:10,  3.09it/s]

tensor(11.6638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6590, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3768, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [20:31<00:06,  4.54it/s]

tensor(11.6728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3482, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3270, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [20:32<00:04,  5.96it/s]

tensor(11.6763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3297, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3534, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [20:32<00:03,  7.04it/s]

tensor(11.6499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3745, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6429, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3979, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [20:32<00:03,  7.68it/s]

tensor(11.6371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4037, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4011, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [20:32<00:02,  8.15it/s]

tensor(11.6285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3975, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3959, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [20:33<00:02,  8.30it/s]

tensor(11.6260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4003, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4099, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [20:33<00:02,  8.43it/s]

tensor(11.6190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4147, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4129, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [20:33<00:02,  8.45it/s]

tensor(11.6166, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4118, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6168, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4085, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [20:33<00:01,  8.32it/s]

tensor(11.6163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4079, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4101, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [20:34<00:01,  8.38it/s]

tensor(11.6112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4122, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4182, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [20:34<00:01,  8.51it/s]

tensor(11.6059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4215, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [20:34<00:01,  8.46it/s]

tensor(11.6034, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4244, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4241, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [20:34<00:00,  8.44it/s]

tensor(11.6025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4238, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4241, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [20:34<00:00,  8.52it/s]

tensor(11.5995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4243, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.5971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4224, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [20:35<00:00,  8.49it/s]

tensor(11.5957, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4225, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.5949, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4206, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [20:35<00:00,  8.40it/s]

tensor(11.5945, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4194, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.5940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4186, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [20:35<00:00,  4.12s/it]

tensor(11.5938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4158, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0018970966339111328
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 4
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.597059211309
NMI         : 0.609564407445
Runtime     : 1279.13 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed4

==============================================================================================================
PRAGA RUN | E18.5 | seed=5
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 5.759e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(15.7649, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4801, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7877, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2277, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:31,  9.44it/s]

tensor(15.7477, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1968, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7052, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3660, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6562, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7148, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 7/300 [00:00<00:30,  9.73it/s]

tensor(15.6037, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2262, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5576, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8838, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:29,  9.74it/s]

tensor(15.5064, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6732, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4552, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5833, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:30,  9.64it/s]

tensor(15.4108, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5997, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3622, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7130, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:29,  9.83it/s]

tensor(15.3229, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9139, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2753, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1943, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2321, device='cuda:0', grad_fn=<AddBackward0>)

  5%|▌         | 15/300 [00:01<00:28,  9.85it/s]

tensor(5.5457, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1923, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9613, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:28,  9.87it/s]

tensor(15.1432, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0972, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9604, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.88it/s]

tensor(15.0487, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0020, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1484, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:28,  9.85it/s]

tensor(14.9435, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8021, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8931, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4905, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:28,  9.82it/s]

tensor(14.8357, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2100, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7820, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9578, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:27,  9.85it/s]

tensor(14.7222, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6593, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5273, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:28,  9.57it/s]

tensor(14.5982, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3442, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5332, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1809, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:27,  9.75it/s]

tensor(14.4683, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0332, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9012, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3329, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7829, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.91it/s]

tensor(14.2633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6773, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1911, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5826, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:26,  9.92it/s]

tensor(14.1171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4982, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0450, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4232, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:27,  9.75it/s]

tensor(13.9747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3563, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2972, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 37/300 [00:03<00:26,  9.84it/s]

tensor(13.8334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2451, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1993, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:26,  9.88it/s]

tensor(13.6965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1592, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0952, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:25,  9.90it/s]

tensor(13.5241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0719, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0540, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:26,  9.74it/s]

tensor(13.3930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.85it/s]

tensor(13.3118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:05<00:25,  9.64it/s]

tensor(13.1964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 53/300 [00:05<00:25,  9.71it/s]

tensor(13.1344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:25,  9.73it/s]

tensor(13.0815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:24,  9.82it/s]

tensor(13.0325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:25,  9.66it/s]

tensor(12.9840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:06<00:24,  9.84it/s]

tensor(12.9353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:24,  9.78it/s]

tensor(12.8655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:24,  9.64it/s]

tensor(12.8225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:24,  9.63it/s]

tensor(12.7830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:23,  9.73it/s]

tensor(12.7447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:07<00:23,  9.66it/s]

tensor(12.7077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:23,  9.78it/s]

tensor(12.6733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 77/300 [00:07<00:23,  9.58it/s]

tensor(12.6255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:23,  9.48it/s]

tensor(12.5955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:08<00:22,  9.64it/s]

tensor(12.5657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5517, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:22,  9.61it/s]

tensor(12.5368, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:22,  9.44it/s]

tensor(12.5084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:22,  9.62it/s]

tensor(12.4812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:09<00:21,  9.73it/s]

tensor(12.4550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:21,  9.79it/s]

tensor(12.4299, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:21,  9.57it/s]

tensor(12.4056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3933, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:21,  9.45it/s]

tensor(12.3823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:21,  9.44it/s]

tensor(12.3597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:10<00:21,  9.45it/s]

tensor(12.3375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.38it/s]

tensor(12.3170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([312, 187,  73, 267,  84, 139,  95, 122, 367,  63, 102, 196,  55,  67])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<03:20, 10.61it/s]
  0%|          | 5/2129 [00:00<03:28, 10.17it/s]
  0%|          | 7/2129 [00:00<04:57,  7.14it/s]
  0%|          | 10/2129 [00:01<04:04,  8.65it/s]
  1%|          | 11/2129 [00:01<04:38,  7.61it/s]
  1%|          | 13/2129 [00:01<04:10,  8.43it/s]
  1%|          | 15/2129 [00:01<04:09,  8.48it/s]
  1%|          | 17/2129 [00:02<04:05,  8.60it/s]
  1%|          | 18/2129 [00:02<04:34,  7.69it/s]
  1%|          | 20/2129 [00:02<03:38,  9.67it/s]
  1%|          | 22/2129 [00:02<03:43,  9.42it/s]
  1%|          | 24/2129 [00:02<04:47,  7.33it/s]
  1%|          | 26/2129 [00:03<05:01,  6.96it/s]
  1%|▏         | 28/2129 [00:03<04:50,  7.23it/s]
  1%|▏         | 29/2129 [00:03<05:15,  6.66it/s]
  1%|▏         | 30/2129 [00:03<05:52,  5.95it/s]
  2%|▏         | 33/2129 [00:04<05:04,  6.88it/s]
  2%|▏         | 35/2129 [00:04<04:49,  7.24it/s]
  2%|▏         | 37/2129 [00:04<04:00,  8.70it/s]
  2%|▏         | 39/2129 [00:04<03:28, 10.04it/s]
  2%|▏         | 41/2129 [00:05<03:42,  9.40it/s]
  2%|▏         | 43/2129 [00:05<03:47,  9.18it/s]
  2%|▏         | 45/2129 [00:05<03:19, 10.44it/s]
  2%|▏         | 49/2129 [00:05<02:54, 11.91it/s]
  2%|▏         | 51/2129 [00:05<02:49, 12.26it/s]
  2%|▏         | 53/2129 [00:05<02:48, 12.30it/s]
  3%|▎         | 55/2129 [00:06<02:31, 13.67it/s]
  3%|▎         | 57/2129 [00:06<03:26, 10.05it/s]
  3%|▎         | 59/2129 [00:06<02:56, 11.71it/s]
  3%|▎         | 61/2129 [00:06<03:34,  9.63it/s]
  3%|▎         | 63/2129 [00:06<03:14, 10.63it/s]
  3%|▎         | 65/2129 [00:07<03:03, 11.23it/s]
  3%|▎         | 67/2129 [00:07<03:18, 10.39it/s]
  3%|▎         | 70/2129 [00:07<03:00, 11.43it/s]
  3%|▎         | 72/2129 [00:07<03:02, 11.30it/s]
  3%|▎         | 74/2129 [00:07<03:13, 10.61it/s]
  4%|▎         | 76/2129 [00:08<02:53, 11.80it/s]
  4%|▎         | 79/2129 [00:08<03:09, 10.81it/s]
  4%|▍         | 81/2129 [00:08<03:53,  8.76it/s]
  4%|▍         | 83/2129 [00:08<03:24, 10.01it/s]
  4%|▍         | 85/2129 [00:09<03:58,  8.55it/s]
  4%|▍         | 87/2129 [00:09<04:45,  7.16it/s]
  4%|▍         | 88/2129 [00:09<05:03,  6.72it/s]
  4%|▍         | 90/2129 [00:09<03:57,  8.57it/s]
  4%|▍         | 94/2129 [00:10<03:02, 11.14it/s]
  5%|▍         | 97/2129 [00:10<02:23, 14.15it/s]
  5%|▍         | 104/2129 [00:10<01:24, 23.93it/s]
  5%|▌         | 108/2129 [00:10<01:50, 18.27it/s]
  5%|▌         | 111/2129 [00:10<01:41, 19.80it/s]
  5%|▌         | 114/2129 [00:11<02:07, 15.78it/s]
  5%|▌         | 117/2129 [00:11<02:27, 13.62it/s]
  6%|▌         | 122/2129 [00:11<01:47, 18.67it/s]
  6%|▌         | 125/2129 [00:11<02:04, 16.04it/s]
  6%|▌         | 129/2129 [00:11<01:42, 19.54it/s]
  6%|▌         | 132/2129 [00:12<02:13, 14.94it/s]
  7%|▋         | 139/2129 [00:12<01:38, 20.29it/s]
  7%|▋         | 142/2129 [00:12<01:38, 20.16it/s]
  7%|▋         | 148/2129 [00:12<01:14, 26.70it/s]
  7%|▋         | 153/2129 [00:12<01:14, 26.62it/s]
  7%|▋         | 157/2129 [00:13<02:07, 15.45it/s]
  8%|▊         | 160/2129 [00:13<02:00, 16.39it/s]
  8%|▊         | 163/2129 [00:13<02:19, 14.05it/s]
  8%|▊         | 165/2129 [00:14<02:29, 13.12it/s]
  8%|▊         | 168/2129 [00:14<02:06, 15.47it/s]
  8%|▊         | 170/2129 [00:14<02:22, 13.73it/s]
  8%|▊         | 172/2129 [00:14<02:55, 11.15it/s]
  8%|▊         | 174/2129 [00:14<02:41, 12.13it/s]
  8%|▊         | 177/2129 [00:14<02:17, 14.23it/s]
  9%|▊         | 183/2129 [00:15<01:24, 22.90it/s]
  9%|▊         | 186/2129 [00:15<02:19, 13.88it/s]
  9%|▉         | 189/2129 [00:15<02:35, 12.48it/s]
  9%|▉         | 191/2129 [00:16<02:45, 11.71it/s]
  9%|▉         | 193/2129 [00:16<02:36, 12.41it/s]
  9%|▉         | 195/2129 [00:16<02:51, 11.29it/s]
  9%|▉         | 198/2129 [00:16<02:22, 13.53it/s]
  9%|▉         | 200/2129 [00:16<03:06, 10.37it/s]
  9%|▉         | 202/2129 [00:17<03:19,  9.66it/s]
 10%|▉         | 205/2129 [00:17<02:31, 12.73it/s]
 10%|▉         | 207/2129 [00:17<03:40,  8.71it/s]
 10%|▉         | 209/2129 [00:17<03:07, 10.22it/s]
 10%|▉         | 211/2129 [00:17<03:11, 10.02it/s]
 10%|█         | 213/2129 [00:18<03:22,  9.47it/s]
 10%|█         | 215/2129 [00:18<02:56, 10.85it/s]
 10%|█         | 219/2129 [00:18<02:45, 11.56it/s]
 10%|█         | 221/2129 [00:18<02:34, 12.33it/s]
 11%|█         | 229/2129 [00:18<01:20, 23.73it/s]
 11%|█         | 233/2129 [00:19<02:23, 13.23it/s]
 11%|█         | 236/2129 [00:19<02:46, 11.38it/s]
 11%|█         | 238/2129 [00:20<02:56, 10.73it/s]
 11%|█▏        | 240/2129 [00:20<02:42, 11.62it/s]
 12%|█▏        | 245/2129 [00:20<02:20, 13.39it/s]
 12%|█▏        | 248/2129 [00:20<02:48, 11.14it/s]
 12%|█▏        | 250/2129 [00:21<03:24,  9.20it/s]
 12%|█▏        | 252/2129 [00:21<04:11,  7.45it/s]
 12%|█▏        | 253/2129 [00:21<04:06,  7.62it/s]
 12%|█▏        | 255/2129 [00:22<04:06,  7.62it/s]
 12%|█▏        | 258/2129 [00:22<03:59,  7.80it/s]
 12%|█▏        | 259/2129 [00:22<04:22,  7.12it/s]
 12%|█▏        | 260/2129 [00:22<04:35,  6.78it/s]
 12%|█▏        | 261/2129 [00:23<05:29,  5.67it/s]
 12%|█▏        | 262/2129 [00:23<05:40,  5.49it/s]
 12%|█▏        | 265/2129 [00:23<04:13,  7.34it/s]
 13%|█▎        | 267/2129 [00:23<03:22,  9.19it/s]
 13%|█▎        | 271/2129 [00:23<02:39, 11.62it/s]
 13%|█▎        | 273/2129 [00:24<02:52, 10.75it/s]
 13%|█▎        | 275/2129 [00:24<03:18,  9.34it/s]
 13%|█▎        | 277/2129 [00:24<02:58, 10.36it/s]
 13%|█▎        | 280/2129 [00:24<02:17, 13.49it/s]
 13%|█▎        | 282/2129 [00:24<02:11, 14.01it/s]
 13%|█▎        | 285/2129 [00:24<01:54, 16.07it/s]
 13%|█▎        | 287/2129 [00:25<02:15, 13.62it/s]
 14%|█▎        | 290/2129 [00:25<01:50, 16.70it/s]
 14%|█▍        | 296/2129 [00:25<01:11, 25.52it/s]
 14%|█▍        | 299/2129 [00:25<01:13, 25.01it/s]
 14%|█▍        | 305/2129 [00:25<01:17, 23.56it/s]
 15%|█▍        | 309/2129 [00:26<01:32, 19.75it/s]
 15%|█▍        | 312/2129 [00:26<01:53, 16.03it/s]
 15%|█▍        | 314/2129 [00:26<02:47, 10.81it/s]
 15%|█▍        | 316/2129 [00:26<02:36, 11.55it/s]
 15%|█▍        | 319/2129 [00:27<02:10, 13.89it/s]
 15%|█▌        | 321/2129 [00:27<02:28, 12.19it/s]
 15%|█▌        | 324/2129 [00:27<02:28, 12.16it/s]
 15%|█▌        | 326/2129 [00:27<02:14, 13.40it/s]
 15%|█▌        | 328/2129 [00:27<02:29, 12.08it/s]
 16%|█▌        | 330/2129 [00:28<02:27, 12.22it/s]
 16%|█▌        | 333/2129 [00:28<02:43, 10.98it/s]
 16%|█▌        | 335/2129 [00:28<02:57, 10.10it/s]
 16%|█▌        | 338/2129 [00:28<02:21, 12.66it/s]
 16%|█▌        | 342/2129 [00:29<02:11, 13.54it/s]
 16%|█▌        | 344/2129 [00:29<02:39, 11.19it/s]
 16%|█▋        | 346/2129 [00:29<02:43, 10.88it/s]
 16%|█▋        | 349/2129 [00:29<02:37, 11.28it/s]
 16%|█▋        | 351/2129 [00:29<02:25, 12.24it/s]
 17%|█▋        | 355/2129 [00:29<01:44, 16.96it/s]
 17%|█▋        | 359/2129 [00:30<01:45, 16.75it/s]
 17%|█▋        | 361/2129 [00:30<02:38, 11.13it/s]
 17%|█▋        | 363/2129 [00:30<03:12,  9.19it/s]
 17%|█▋        | 365/2129 [00:31<02:46, 10.57it/s]
 17%|█▋        | 369/2129 [00:31<02:35, 11.29it/s]
 17%|█▋        | 371/2129 [00:31<02:26, 12.02it/s]
 18%|█▊        | 373/2129 [00:31<03:04,  9.52it/s]
 18%|█▊        | 375/2129 [00:32<02:45, 10.58it/s]
 18%|█▊        | 380/2129 [00:32<02:15, 12.90it/s]
 18%|█▊        | 383/2129 [00:32<01:54, 15.22it/s]
 18%|█▊        | 385/2129 [00:32<01:54, 15.29it/s]
 18%|█▊        | 387/2129 [00:32<02:20, 12.39it/s]
 18%|█▊        | 390/2129 [00:32<01:54, 15.15it/s]
 18%|█▊        | 392/2129 [00:33<01:57, 14.77it/s]
 19%|█▊        | 394/2129 [00:33<02:23, 12.05it/s]
 19%|█▊        | 396/2129 [00:33<02:10, 13.33it/s]
 19%|█▉        | 400/2129 [00:33<02:08, 13.45it/s]
 19%|█▉        | 402/2129 [00:33<02:17, 12.52it/s]
 19%|█▉        | 404/2129 [00:34<02:15, 12.70it/s]
 19%|█▉        | 406/2129 [00:34<03:18,  8.67it/s]
 19%|█▉        | 409/2129 [00:34<02:30, 11.40it/s]
 19%|█▉        | 411/2129 [00:34<02:48, 10.19it/s]
 19%|█▉        | 413/2129 [00:34<02:28, 11.54it/s]
 19%|█▉        | 415/2129 [00:35<03:18,  8.64it/s]
 20%|█▉        | 417/2129 [00:35<02:53,  9.88it/s]
 20%|█▉        | 421/2129 [00:35<02:40, 10.64it/s]
 20%|█▉        | 423/2129 [00:36<03:21,  8.47it/s]
 20%|██        | 426/2129 [00:36<02:49, 10.05it/s]
 20%|██        | 428/2129 [00:36<02:39, 10.66it/s]
 20%|██        | 430/2129 [00:36<03:05,  9.17it/s]
 20%|██        | 433/2129 [00:37<02:45, 10.26it/s]
 20%|██        | 436/2129 [00:37<02:18, 12.26it/s]
 21%|██        | 439/2129 [00:37<02:13, 12.68it/s]
 21%|██        | 441/2129 [00:37<02:03, 13.69it/s]
 21%|██        | 443/2129 [00:37<02:14, 12.55it/s]
 21%|██        | 445/2129 [00:37<02:24, 11.63it/s]
 21%|██        | 448/2129 [00:38<01:53, 14.77it/s]
 21%|██        | 452/2129 [00:38<01:31, 18.28it/s]
 21%|██▏       | 455/2129 [00:38<02:22, 11.77it/s]
 21%|██▏       | 457/2129 [00:38<02:39, 10.47it/s]
 22%|██▏       | 459/2129 [00:39<02:22, 11.73it/s]
 22%|██▏       | 461/2129 [00:39<02:28, 11.22it/s]
 22%|██▏       | 466/2129 [00:39<01:33, 17.79it/s]
 22%|██▏       | 469/2129 [00:39<02:31, 10.94it/s]
 22%|██▏       | 473/2129 [00:39<01:52, 14.71it/s]
 22%|██▏       | 477/2129 [00:40<02:04, 13.27it/s]
 23%|██▎       | 481/2129 [00:40<02:04, 13.29it/s]
 23%|██▎       | 484/2129 [00:41<02:26, 11.26it/s]
 23%|██▎       | 486/2129 [00:41<02:40, 10.26it/s]
 23%|██▎       | 488/2129 [00:41<03:25,  7.98it/s]
 23%|██▎       | 491/2129 [00:41<02:40, 10.24it/s]
 23%|██▎       | 494/2129 [00:42<02:30, 10.88it/s]
 23%|██▎       | 496/2129 [00:42<02:14, 12.11it/s]
 23%|██▎       | 499/2129 [00:42<02:12, 12.32it/s]
 24%|██▎       | 501/2129 [00:42<02:55,  9.25it/s]
 24%|██▎       | 504/2129 [00:42<02:15, 11.98it/s]
 24%|██▍       | 506/2129 [00:43<03:00,  9.00it/s]
 24%|██▍       | 508/2129 [00:43<03:24,  7.92it/s]
 24%|██▍       | 510/2129 [00:44<04:13,  6.38it/s]
 24%|██▍       | 511/2129 [00:44<04:40,  5.78it/s]
 24%|██▍       | 513/2129 [00:44<03:43,  7.22it/s]
 24%|██▍       | 515/2129 [00:44<03:10,  8.48it/s]
 24%|██▍       | 517/2129 [00:44<03:08,  8.56it/s]
 24%|██▍       | 519/2129 [00:45<03:05,  8.69it/s]
 24%|██▍       | 521/2129 [00:45<02:59,  8.97it/s]
 25%|██▍       | 522/2129 [00:45<03:17,  8.12it/s]
 25%|██▍       | 524/2129 [00:45<02:41,  9.94it/s]
 25%|██▍       | 526/2129 [00:46<03:28,  7.69it/s]
 25%|██▍       | 527/2129 [00:46<03:22,  7.92it/s]
 25%|██▍       | 529/2129 [00:46<02:42,  9.84it/s]
 25%|██▍       | 531/2129 [00:46<02:19, 11.42it/s]
 25%|██▌       | 533/2129 [00:46<02:11, 12.14it/s]
 25%|██▌       | 535/2129 [00:46<02:12, 12.02it/s]
 25%|██▌       | 537/2129 [00:46<01:59, 13.37it/s]
 25%|██▌       | 539/2129 [00:47<02:16, 11.63it/s]
 25%|██▌       | 542/2129 [00:47<01:46, 14.96it/s]
 26%|██▌       | 544/2129 [00:47<02:01, 13.06it/s]
 26%|██▌       | 546/2129 [00:47<02:26, 10.82it/s]
 26%|██▌       | 548/2129 [00:47<02:52,  9.14it/s]
 26%|██▌       | 550/2129 [00:48<03:02,  8.64it/s]
 26%|██▌       | 551/2129 [00:48<03:20,  7.87it/s]
 26%|██▌       | 552/2129 [00:48<03:51,  6.81it/s]
 26%|██▌       | 553/2129 [00:48<04:13,  6.22it/s]
 26%|██▌       | 555/2129 [00:48<03:15,  8.04it/s]
 26%|██▌       | 557/2129 [00:49<03:21,  7.78it/s]
 26%|██▋       | 559/2129 [00:49<02:43,  9.58it/s]
 26%|██▋       | 562/2129 [00:49<02:02, 12.81it/s]
 26%|██▋       | 564/2129 [00:49<02:44,  9.51it/s]
 27%|██▋       | 566/2129 [00:49<02:21, 11.07it/s]
 27%|██▋       | 568/2129 [00:50<02:25, 10.73it/s]
 27%|██▋       | 570/2129 [00:50<02:08, 12.15it/s]
 27%|██▋       | 573/2129 [00:50<01:39, 15.65it/s]
 27%|██▋       | 576/2129 [00:50<01:28, 17.50it/s]
 27%|██▋       | 578/2129 [00:50<02:22, 10.90it/s]
 27%|██▋       | 581/2129 [00:51<02:39,  9.72it/s]
 27%|██▋       | 584/2129 [00:51<02:05, 12.32it/s]
 28%|██▊       | 589/2129 [00:51<01:53, 13.53it/s]
 28%|██▊       | 591/2129 [00:51<01:48, 14.23it/s]
 28%|██▊       | 593/2129 [00:52<02:13, 11.48it/s]
 28%|██▊       | 595/2129 [00:52<02:54,  8.81it/s]
 28%|██▊       | 599/2129 [00:52<02:06, 12.14it/s]
 28%|██▊       | 604/2129 [00:52<01:40, 15.22it/s]
 28%|██▊       | 606/2129 [00:52<01:36, 15.75it/s]
 29%|██▊       | 609/2129 [00:53<01:26, 17.51it/s]
 29%|██▊       | 611/2129 [00:53<02:00, 12.62it/s]
 29%|██▉       | 614/2129 [00:53<01:45, 14.33it/s]
 29%|██▉       | 618/2129 [00:53<01:38, 15.27it/s]
 29%|██▉       | 620/2129 [00:53<01:34, 16.00it/s]
 29%|██▉       | 622/2129 [00:53<01:30, 16.71it/s]
 29%|██▉       | 625/2129 [00:54<01:18, 19.06it/s]
 29%|██▉       | 628/2129 [00:54<01:37, 15.37it/s]
 30%|██▉       | 631/2129 [00:54<01:46, 14.11it/s]
 30%|██▉       | 633/2129 [00:54<02:08, 11.68it/s]
 30%|██▉       | 635/2129 [00:55<02:23, 10.40it/s]
 30%|██▉       | 638/2129 [00:55<01:51, 13.40it/s]
 30%|███       | 644/2129 [00:55<01:42, 14.44it/s]
 30%|███       | 647/2129 [00:55<01:31, 16.11it/s]
 31%|███       | 653/2129 [00:56<01:32, 15.95it/s]
 31%|███       | 655/2129 [00:56<01:52, 13.11it/s]
 31%|███       | 657/2129 [00:56<01:45, 13.98it/s]
 31%|███       | 659/2129 [00:56<01:58, 12.43it/s]
 31%|███       | 661/2129 [00:57<02:34,  9.50it/s]
 31%|███       | 663/2129 [00:57<03:47,  6.44it/s]
 31%|███       | 664/2129 [00:57<03:57,  6.17it/s]
 31%|███▏      | 667/2129 [00:57<02:45,  8.83it/s]
 31%|███▏      | 670/2129 [00:58<02:22, 10.26it/s]
 32%|███▏      | 672/2129 [00:58<02:55,  8.31it/s]
 32%|███▏      | 674/2129 [00:58<02:54,  8.32it/s]
 32%|███▏      | 676/2129 [00:59<02:56,  8.24it/s]
 32%|███▏      | 678/2129 [00:59<02:29,  9.72it/s]
 32%|███▏      | 683/2129 [00:59<02:14, 10.74it/s]
 32%|███▏      | 686/2129 [00:59<01:51, 12.90it/s]
 32%|███▏      | 688/2129 [01:00<03:02,  7.91it/s]
 32%|███▏      | 690/2129 [01:00<02:35,  9.23it/s]
 33%|███▎      | 694/2129 [01:00<02:34,  9.28it/s]
 33%|███▎      | 696/2129 [01:01<02:38,  9.07it/s]
 33%|███▎      | 698/2129 [01:01<03:05,  7.70it/s]
 33%|███▎      | 700/2129 [01:01<02:37,  9.08it/s]
 33%|███▎      | 703/2129 [01:01<02:24,  9.85it/s]
 33%|███▎      | 705/2129 [01:02<02:36,  9.10it/s]
 33%|███▎      | 708/2129 [01:02<02:39,  8.91it/s]
 33%|███▎      | 710/2129 [01:02<02:48,  8.40it/s]
 33%|███▎      | 712/2129 [01:02<02:44,  8.61it/s]
 34%|███▎      | 714/2129 [01:03<02:24,  9.78it/s]
 34%|███▎      | 718/2129 [01:03<01:37, 14.42it/s]
 34%|███▍      | 720/2129 [01:03<02:13, 10.56it/s]
 34%|███▍      | 722/2129 [01:03<02:15, 10.39it/s]
 34%|███▍      | 724/2129 [01:04<02:52,  8.16it/s]
 34%|███▍      | 726/2129 [01:04<02:51,  8.18it/s]
 34%|███▍      | 728/2129 [01:04<03:26,  6.78it/s]
 34%|███▍      | 729/2129 [01:04<03:33,  6.57it/s]
 34%|███▍      | 730/2129 [01:05<03:43,  6.26it/s]
 34%|███▍      | 732/2129 [01:05<02:48,  8.27it/s]
 34%|███▍      | 734/2129 [01:05<02:31,  9.21it/s]
 35%|███▍      | 736/2129 [01:05<02:10, 10.68it/s]
 35%|███▍      | 738/2129 [01:05<02:50,  8.17it/s]
 35%|███▍      | 740/2129 [01:06<03:28,  6.65it/s]
 35%|███▍      | 741/2129 [01:06<03:43,  6.22it/s]
 35%|███▍      | 743/2129 [01:06<02:56,  7.85it/s]
 35%|███▌      | 747/2129 [01:06<01:46, 12.98it/s]
 35%|███▌      | 750/2129 [01:06<01:40, 13.74it/s]
 35%|███▌      | 752/2129 [01:07<02:17, 10.00it/s]
 35%|███▌      | 754/2129 [01:07<03:35,  6.38it/s]
 36%|███▌      | 756/2129 [01:08<03:41,  6.19it/s]
 36%|███▌      | 758/2129 [01:08<03:43,  6.12it/s]
 36%|███▌      | 760/2129 [01:08<03:01,  7.53it/s]
 36%|███▌      | 764/2129 [01:08<02:18,  9.89it/s]
 36%|███▌      | 766/2129 [01:09<03:05,  7.34it/s]
 36%|███▌      | 768/2129 [01:09<02:57,  7.66it/s]
 36%|███▌      | 770/2129 [01:09<02:58,  7.62it/s]
 36%|███▋      | 772/2129 [01:10<03:04,  7.37it/s]
 36%|███▋      | 774/2129 [01:10<03:29,  6.47it/s]
 36%|███▋      | 776/2129 [01:11<03:34,  6.32it/s]
 36%|███▋      | 777/2129 [01:11<03:42,  6.07it/s]
 37%|███▋      | 778/2129 [01:11<03:50,  5.87it/s]
 37%|███▋      | 781/2129 [01:11<02:27,  9.16it/s]
 37%|███▋      | 785/2129 [01:11<02:10, 10.32it/s]
 37%|███▋      | 787/2129 [01:12<02:13, 10.08it/s]
 37%|███▋      | 789/2129 [01:12<01:55, 11.59it/s]
 37%|███▋      | 792/2129 [01:12<01:30, 14.70it/s]
 37%|███▋      | 795/2129 [01:12<01:33, 14.32it/s]
 37%|███▋      | 797/2129 [01:12<02:23,  9.27it/s]
 38%|███▊      | 799/2129 [01:13<02:21,  9.40it/s]
 38%|███▊      | 801/2129 [01:13<02:02, 10.87it/s]
 38%|███▊      | 804/2129 [01:13<01:36, 13.73it/s]
 38%|███▊      | 806/2129 [01:13<02:23,  9.22it/s]
 38%|███▊      | 809/2129 [01:14<02:12,  9.93it/s]
 38%|███▊      | 811/2129 [01:14<01:59, 11.05it/s]
 38%|███▊      | 813/2129 [01:14<03:00,  7.28it/s]
 38%|███▊      | 815/2129 [01:14<02:57,  7.41it/s]
 38%|███▊      | 818/2129 [01:15<02:31,  8.64it/s]
 39%|███▊      | 820/2129 [01:15<02:57,  7.37it/s]
 39%|███▊      | 822/2129 [01:15<02:31,  8.64it/s]
 39%|███▉      | 825/2129 [01:15<01:52, 11.62it/s]
 39%|███▉      | 833/2129 [01:15<00:56, 23.05it/s]
 39%|███▉      | 837/2129 [01:16<01:03, 20.28it/s]
 39%|███▉      | 840/2129 [01:16<01:05, 19.69it/s]
 40%|███▉      | 843/2129 [01:16<01:44, 12.36it/s]
 40%|███▉      | 845/2129 [01:17<01:58, 10.85it/s]
 40%|███▉      | 847/2129 [01:17<02:03, 10.42it/s]
 40%|███▉      | 849/2129 [01:17<02:14,  9.49it/s]
 40%|████      | 852/2129 [01:17<01:48, 11.80it/s]
 40%|████      | 854/2129 [01:17<01:46, 11.94it/s]
 40%|████      | 856/2129 [01:18<01:38, 12.99it/s]
 40%|████      | 858/2129 [01:18<02:08,  9.89it/s]
 40%|████      | 860/2129 [01:18<02:29,  8.50it/s]
 40%|████      | 862/2129 [01:18<02:06,  9.98it/s]
 41%|████      | 864/2129 [01:18<02:06,  9.99it/s]
 41%|████      | 866/2129 [01:19<02:39,  7.90it/s]
 41%|████      | 869/2129 [01:19<01:58, 10.60it/s]
 41%|████      | 871/2129 [01:19<01:44, 12.04it/s]
 41%|████      | 873/2129 [01:20<02:27,  8.50it/s]
 41%|████      | 876/2129 [01:20<02:09,  9.69it/s]
 41%|████      | 878/2129 [01:20<01:56, 10.78it/s]
 41%|████▏     | 881/2129 [01:20<02:03, 10.08it/s]
 41%|████▏     | 883/2129 [01:20<02:07,  9.77it/s]
 42%|████▏     | 886/2129 [01:21<01:49, 11.34it/s]
 42%|████▏     | 888/2129 [01:21<01:57, 10.53it/s]
 42%|████▏     | 890/2129 [01:21<02:07,  9.69it/s]
 42%|████▏     | 892/2129 [01:21<01:50, 11.19it/s]
 42%|████▏     | 895/2129 [01:21<01:49, 11.25it/s]
 42%|████▏     | 897/2129 [01:22<02:05,  9.85it/s]
 42%|████▏     | 899/2129 [01:22<02:47,  7.33it/s]
 42%|████▏     | 900/2129 [01:22<02:41,  7.62it/s]
 42%|████▏     | 901/2129 [01:22<02:37,  7.79it/s]
 42%|████▏     | 903/2129 [01:23<02:17,  8.91it/s]
 43%|████▎     | 905/2129 [01:23<02:13,  9.16it/s]
 43%|████▎     | 906/2129 [01:23<03:00,  6.77it/s]
 43%|████▎     | 907/2129 [01:23<03:13,  6.33it/s]
 43%|████▎     | 909/2129 [01:24<02:51,  7.10it/s]
 43%|████▎     | 911/2129 [01:24<02:55,  6.92it/s]
 43%|████▎     | 914/2129 [01:24<02:26,  8.32it/s]
 43%|████▎     | 915/2129 [01:24<02:38,  7.67it/s]
 43%|████▎     | 918/2129 [01:24<01:53, 10.64it/s]
 43%|████▎     | 920/2129 [01:25<02:02,  9.84it/s]
 43%|████▎     | 922/2129 [01:25<02:07,  9.48it/s]
 43%|████▎     | 924/2129 [01:25<02:07,  9.46it/s]
 43%|████▎     | 926/2129 [01:25<02:10,  9.24it/s]
 44%|████▎     | 927/2129 [01:26<02:43,  7.35it/s]
 44%|████▎     | 929/2129 [01:26<02:29,  8.03it/s]
 44%|████▎     | 931/2129 [01:26<03:16,  6.10it/s]
 44%|████▍     | 933/2129 [01:26<02:34,  7.76it/s]
 44%|████▍     | 935/2129 [01:27<02:04,  9.57it/s]
 44%|████▍     | 937/2129 [01:27<02:30,  7.95it/s]
 44%|████▍     | 939/2129 [01:27<02:33,  7.77it/s]
 44%|████▍     | 941/2129 [01:27<02:08,  9.22it/s]
 44%|████▍     | 943/2129 [01:27<02:03,  9.59it/s]
 44%|████▍     | 946/2129 [01:28<01:50, 10.75it/s]
 45%|████▍     | 949/2129 [01:28<01:24, 13.94it/s]
 45%|████▍     | 951/2129 [01:28<01:30, 13.03it/s]
 45%|████▍     | 953/2129 [01:28<01:41, 11.62it/s]
 45%|████▍     | 955/2129 [01:28<01:42, 11.51it/s]
 45%|████▍     | 957/2129 [01:29<01:42, 11.39it/s]
 45%|████▌     | 959/2129 [01:29<02:15,  8.64it/s]
 45%|████▌     | 961/2129 [01:29<02:13,  8.74it/s]
 45%|████▌     | 963/2129 [01:29<02:28,  7.83it/s]
 45%|████▌     | 966/2129 [01:30<01:57,  9.93it/s]
 45%|████▌     | 968/2129 [01:30<01:41, 11.45it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 292.38it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 3], [np.int64(2), False, 0], [np.int64(4), False, 1], [np.int64(5), False, 8], [np.int64(6), False, 5], [np.int64(7), False, 5], [np.int64(9), False, 10], [np.int64(11), False, 8], [np.int64(12), False, 0], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.1305, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:14<4:00:22, 72.47s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:14<2:48:09, 50.96s/it]

tensor(12.3058, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.3633, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6841, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:15<57:22, 17.65s/it]

tensor(12.4018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.9333, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0778, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [04:15<28:03,  8.72s/it]

tensor(12.5234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1733, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2758, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [04:15<13:48,  4.34s/it]

tensor(12.5386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3781, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4985, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [04:15<06:53,  2.19s/it]

tensor(12.4772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7196, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:16<03:31,  1.13s/it]

tensor(12.4471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8021, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8418, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:16<01:53,  1.62it/s]

tensor(12.3990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8759, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3573, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9275, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [04:16<01:06,  2.75it/s]

tensor(12.3415, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0572, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [04:16<00:42,  4.22it/s]

tensor(12.3687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1263, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1758, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [04:16<00:31,  5.70it/s]

tensor(12.3536, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2272, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2732, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [04:17<00:25,  6.93it/s]

tensor(12.2988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3309, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3846, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [04:17<00:22,  7.75it/s]

tensor(12.2697, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4335, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4710, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [04:17<00:21,  8.19it/s]

tensor(12.2539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4989, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5265, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:17<00:20,  8.46it/s]

tensor(12.2214, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5612, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5923, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:18<00:19,  8.60it/s]

tensor(12.2063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6227, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2014, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6475, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [04:18<00:19,  8.70it/s]

tensor(12.1918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6693, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6958, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [04:18<00:18,  8.70it/s]

tensor(12.1608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7175, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7366, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [04:18<00:18,  8.63it/s]

tensor(12.1353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7578, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7782, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [04:19<00:18,  8.67it/s]

tensor(12.1141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8023, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8328, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:19<00:18,  8.73it/s]

tensor(12.0882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8853, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:19<00:18,  8.68it/s]

tensor(12.0629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9063, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9270, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [04:19<00:18,  8.60it/s]

tensor(12.0375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9508, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0258, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9147, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [04:19<00:18,  8.45it/s]

tensor(12.0153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9335, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0058, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9592, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:20<00:17,  8.41it/s]

tensor(11.9970, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9697, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9880, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:20<00:17,  8.38it/s]

tensor(11.9793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0083, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 63, 193, 104, 245, 193, 367,  82, 123,  34, 211,  94,  86,  61, 273])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:43, 20.54it/s]
  0%|          | 9/2129 [00:00<00:56, 37.71it/s]
  1%|          | 14/2129 [00:00<00:56, 37.72it/s]
  1%|          | 18/2129 [00:00<01:00, 35.04it/s]
  1%|          | 22/2129 [00:00<01:04, 32.60it/s]
  1%|▏         | 27/2129 [00:00<01:00, 34.85it/s]
  2%|▏         | 33/2129 [00:00<00:51, 40.45it/s]
  2%|▏         | 38/2129 [00:01<00:49, 42.58it/s]
  2%|▏         | 43/2129 [00:01<00:56, 36.78it/s]
  2%|▏         | 47/2129 [00:01<01:05, 31.85it/s]
  2%|▏         | 52/2129 [00:01<00:59, 34.77it/s]
  3%|▎         | 56/2129 [00:01<01:09, 29.80it/s]
  3%|▎         | 62/2129 [00:01<00:57, 35.68it/s]
  3%|▎         | 66/2129 [00:02<01:24, 24.29it/s]
  3%|▎         | 71/2129 [00:02<01:12, 28.46it/s]
  4%|▎         | 75/2129 [00:02<01:24, 24.24it/s]
  4%|▎         | 78/2129 [00:02<01:24, 24.39it/s]
  4%|▍         | 81/2129 [00:02<01:51, 18.30it/s]
  4%|▍         | 84/2129 [00:02<01:40, 20.26it/s]
  4%|▍         | 90/2129 [00:03<01:12, 27.95it/s]
  5%|▍         | 96/2129 [00:03<00:59, 34.03it/s]
  5%|▍         | 101/2129 [00:03<00:58, 34.62it/s]
  5%|▍         | 105/2129 [00:03<01:15, 26.93it/s]
  5%|▌         | 109/2129 [00:03<01:32, 21.77it/s]
  5%|▌         | 113/2129 [00:03<01:22, 24.50it/s]
  6%|▌         | 118/2129 [00:04<01:09, 28.95it/s]
  6%|▌         | 124/2129 [00:04<01:14, 26.82it/s]
  6%|▌         | 128/2129 [00:04<01:19, 25.05it/s]
  6%|▌         | 132/2129 [00:04<01:30, 22.16it/s]
  6%|▋         | 135/2129 [00:04<01:30, 22.13it/s]
  7%|▋         | 143/2129 [00:04<01:00, 32.73it/s]
  7%|▋         | 150/2129 [00:05<00:49, 40.08it/s]
  7%|▋         | 155/2129 [00:05<00:51, 38.18it/s]
  8%|▊         | 160/2129 [00:05<01:15, 26.17it/s]
  8%|▊         | 164/2129 [00:05<01:41, 19.44it/s]
  8%|▊         | 167/2129 [00:06<01:55, 16.93it/s]
  8%|▊         | 170/2129 [00:06<02:19, 14.01it/s]
  8%|▊         | 172/2129 [00:06<02:21, 13.84it/s]
  8%|▊         | 174/2129 [00:06<02:13, 14.68it/s]
  8%|▊         | 176/2129 [00:06<02:10, 14.97it/s]
  8%|▊         | 178/2129 [00:07<02:08, 15.17it/s]
  8%|▊         | 180/2129 [00:07<02:01, 16.03it/s]
  9%|▊         | 183/2129 [00:07<01:57, 16.49it/s]
  9%|▊         | 185/2129 [00:07<02:28, 13.07it/s]
  9%|▉         | 187/2129 [00:07<02:18, 14.02it/s]
  9%|▉         | 189/2129 [00:07<02:22, 13.59it/s]
  9%|▉         | 191/2129 [00:08<02:55, 11.07it/s]
  9%|▉         | 193/2129 [00:08<02:38, 12.20it/s]
  9%|▉         | 196/2129 [00:08<02:08, 15.10it/s]
  9%|▉         | 201/2129 [00:08<01:27, 22.09it/s]
 10%|▉         | 204/2129 [00:08<01:23, 23.02it/s]
 10%|▉         | 209/2129 [00:08<01:06, 28.89it/s]
 10%|█         | 213/2129 [00:08<01:30, 21.17it/s]
 10%|█         | 216/2129 [00:09<01:47, 17.84it/s]
 10%|█         | 221/2129 [00:09<01:35, 20.02it/s]
 11%|█         | 224/2129 [00:09<01:40, 18.96it/s]
 11%|█         | 228/2129 [00:09<01:25, 22.17it/s]
 11%|█         | 231/2129 [00:09<01:28, 21.35it/s]
 11%|█         | 234/2129 [00:10<02:03, 15.38it/s]
 11%|█         | 237/2129 [00:10<01:50, 17.10it/s]
 11%|█▏        | 240/2129 [00:10<02:03, 15.24it/s]
 11%|█▏        | 243/2129 [00:10<02:11, 14.31it/s]
 12%|█▏        | 246/2129 [00:11<02:32, 12.34it/s]
 12%|█▏        | 248/2129 [00:11<03:07, 10.04it/s]
 12%|█▏        | 250/2129 [00:11<03:19,  9.40it/s]
 12%|█▏        | 252/2129 [00:12<03:46,  8.28it/s]
 12%|█▏        | 255/2129 [00:12<02:53, 10.80it/s]
 12%|█▏        | 258/2129 [00:12<02:51, 10.92it/s]
 12%|█▏        | 260/2129 [00:12<03:21,  9.26it/s]
 12%|█▏        | 262/2129 [00:13<04:11,  7.43it/s]
 12%|█▏        | 263/2129 [00:13<04:03,  7.67it/s]
 12%|█▏        | 265/2129 [00:13<03:20,  9.29it/s]
 13%|█▎        | 267/2129 [00:13<03:31,  8.80it/s]
 13%|█▎        | 270/2129 [00:13<02:40, 11.60it/s]
 13%|█▎        | 272/2129 [00:13<02:28, 12.52it/s]
 13%|█▎        | 274/2129 [00:14<03:10,  9.71it/s]
 13%|█▎        | 276/2129 [00:14<03:15,  9.50it/s]
 13%|█▎        | 278/2129 [00:14<02:50, 10.85it/s]
 13%|█▎        | 280/2129 [00:14<02:58, 10.36it/s]
 13%|█▎        | 282/2129 [00:15<03:05,  9.97it/s]
 13%|█▎        | 286/2129 [00:15<02:04, 14.78it/s]
 14%|█▎        | 288/2129 [00:15<02:26, 12.56it/s]
 14%|█▎        | 291/2129 [00:15<01:57, 15.70it/s]
 14%|█▍        | 293/2129 [00:15<02:19, 13.14it/s]
 14%|█▍        | 295/2129 [00:15<02:45, 11.05it/s]
 14%|█▍        | 298/2129 [00:16<02:14, 13.65it/s]
 14%|█▍        | 302/2129 [00:16<01:41, 17.97it/s]
 14%|█▍        | 305/2129 [00:16<02:34, 11.84it/s]
 14%|█▍        | 307/2129 [00:16<02:20, 13.01it/s]
 15%|█▍        | 310/2129 [00:16<01:58, 15.36it/s]
 15%|█▍        | 312/2129 [00:17<02:07, 14.25it/s]
 15%|█▍        | 314/2129 [00:17<02:59, 10.11it/s]
 15%|█▍        | 316/2129 [00:17<02:38, 11.46it/s]
 15%|█▍        | 318/2129 [00:17<02:44, 11.00it/s]
 15%|█▌        | 320/2129 [00:17<02:30, 12.00it/s]
 15%|█▌        | 322/2129 [00:18<02:33, 11.79it/s]
 15%|█▌        | 324/2129 [00:18<02:18, 12.99it/s]
 15%|█▌        | 327/2129 [00:18<01:57, 15.37it/s]
 15%|█▌        | 329/2129 [00:18<02:37, 11.42it/s]
 16%|█▌        | 331/2129 [00:18<02:28, 12.14it/s]
 16%|█▌        | 333/2129 [00:18<02:16, 13.13it/s]
 16%|█▌        | 335/2129 [00:18<02:07, 14.07it/s]
 16%|█▌        | 337/2129 [00:19<02:08, 13.91it/s]
 16%|█▌        | 339/2129 [00:19<02:00, 14.91it/s]
 16%|█▌        | 342/2129 [00:19<02:23, 12.43it/s]
 16%|█▌        | 344/2129 [00:19<03:02,  9.78it/s]
 16%|█▋        | 346/2129 [00:20<02:41, 11.03it/s]
 16%|█▋        | 349/2129 [00:20<02:38, 11.22it/s]
 16%|█▋        | 351/2129 [00:20<02:52, 10.29it/s]
 17%|█▋        | 354/2129 [00:20<02:55, 10.11it/s]
 17%|█▋        | 356/2129 [00:21<03:41,  8.01it/s]
 17%|█▋        | 357/2129 [00:21<03:56,  7.49it/s]
 17%|█▋        | 358/2129 [00:21<04:14,  6.97it/s]
 17%|█▋        | 359/2129 [00:21<03:58,  7.41it/s]
 17%|█▋        | 361/2129 [00:21<03:15,  9.05it/s]
 17%|█▋        | 362/2129 [00:21<03:18,  8.91it/s]
 17%|█▋        | 365/2129 [00:22<02:28, 11.87it/s]
 17%|█▋        | 370/2129 [00:22<01:29, 19.64it/s]
 18%|█▊        | 373/2129 [00:22<01:45, 16.67it/s]
 18%|█▊        | 375/2129 [00:22<02:18, 12.68it/s]
 18%|█▊        | 377/2129 [00:22<02:38, 11.06it/s]
 18%|█▊        | 379/2129 [00:23<02:27, 11.88it/s]
 18%|█▊        | 381/2129 [00:23<02:32, 11.45it/s]
 18%|█▊        | 383/2129 [00:23<02:15, 12.89it/s]
 18%|█▊        | 385/2129 [00:23<02:47, 10.41it/s]
 18%|█▊        | 387/2129 [00:23<03:04,  9.46it/s]
 18%|█▊        | 390/2129 [00:24<02:15, 12.80it/s]
 18%|█▊        | 392/2129 [00:24<02:43, 10.62it/s]
 19%|█▊        | 394/2129 [00:24<02:59,  9.67it/s]
 19%|█▊        | 396/2129 [00:24<02:36, 11.06it/s]
 19%|█▉        | 400/2129 [00:24<02:14, 12.81it/s]
 19%|█▉        | 402/2129 [00:25<02:03, 13.99it/s]
 19%|█▉        | 404/2129 [00:25<02:20, 12.32it/s]
 19%|█▉        | 406/2129 [00:25<02:52, 10.00it/s]
 19%|█▉        | 408/2129 [00:25<03:32,  8.10it/s]
 19%|█▉        | 410/2129 [00:26<03:02,  9.41it/s]
 19%|█▉        | 412/2129 [00:26<02:36, 10.97it/s]
 19%|█▉        | 414/2129 [00:26<02:20, 12.19it/s]
 20%|█▉        | 417/2129 [00:26<01:57, 14.63it/s]
 20%|█▉        | 420/2129 [00:26<02:15, 12.60it/s]
 20%|█▉        | 422/2129 [00:26<02:09, 13.21it/s]
 20%|█▉        | 425/2129 [00:26<01:45, 16.21it/s]
 20%|██        | 428/2129 [00:27<01:35, 17.79it/s]
 20%|██        | 430/2129 [00:27<02:09, 13.16it/s]
 20%|██        | 432/2129 [00:27<02:30, 11.28it/s]
 20%|██        | 434/2129 [00:27<02:54,  9.72it/s]
 20%|██        | 436/2129 [00:28<03:06,  9.05it/s]
 21%|██        | 439/2129 [00:28<02:56,  9.60it/s]
 21%|██        | 441/2129 [00:28<02:36, 10.75it/s]
 21%|██        | 444/2129 [00:28<02:06, 13.31it/s]
 21%|██        | 449/2129 [00:28<01:26, 19.50it/s]
 21%|██        | 452/2129 [00:28<01:21, 20.60it/s]
 21%|██▏       | 455/2129 [00:29<01:39, 16.80it/s]
 22%|██▏       | 458/2129 [00:29<01:52, 14.84it/s]
 22%|██▏       | 460/2129 [00:29<02:18, 12.03it/s]
 22%|██▏       | 464/2129 [00:29<01:43, 16.04it/s]
 22%|██▏       | 467/2129 [00:30<01:51, 14.90it/s]
 22%|██▏       | 469/2129 [00:30<02:17, 12.10it/s]
 22%|██▏       | 471/2129 [00:30<02:33, 10.83it/s]
 22%|██▏       | 473/2129 [00:30<02:16, 12.16it/s]
 22%|██▏       | 477/2129 [00:30<02:03, 13.33it/s]
 22%|██▏       | 479/2129 [00:31<02:26, 11.29it/s]
 23%|██▎       | 481/2129 [00:31<02:41, 10.18it/s]
 23%|██▎       | 483/2129 [00:31<02:50,  9.63it/s]
 23%|██▎       | 485/2129 [00:32<03:04,  8.89it/s]
 23%|██▎       | 487/2129 [00:32<03:11,  8.59it/s]
 23%|██▎       | 488/2129 [00:32<03:45,  7.28it/s]
 23%|██▎       | 490/2129 [00:32<03:47,  7.21it/s]
 23%|██▎       | 492/2129 [00:32<03:01,  9.02it/s]
 23%|██▎       | 494/2129 [00:33<02:30, 10.84it/s]
 23%|██▎       | 498/2129 [00:33<01:40, 16.15it/s]
 24%|██▎       | 501/2129 [00:33<01:48, 15.03it/s]
 24%|██▎       | 503/2129 [00:33<01:50, 14.66it/s]
 24%|██▍       | 506/2129 [00:33<01:35, 16.97it/s]
 24%|██▍       | 508/2129 [00:33<01:42, 15.88it/s]
 24%|██▍       | 510/2129 [00:33<02:02, 13.21it/s]
 24%|██▍       | 512/2129 [00:34<01:56, 13.86it/s]
 24%|██▍       | 515/2129 [00:34<01:49, 14.74it/s]
 24%|██▍       | 517/2129 [00:34<02:10, 12.39it/s]
 24%|██▍       | 519/2129 [00:34<01:56, 13.76it/s]
 24%|██▍       | 521/2129 [00:34<02:03, 13.05it/s]
 25%|██▍       | 523/2129 [00:34<01:59, 13.44it/s]
 25%|██▍       | 525/2129 [00:35<01:52, 14.21it/s]
 25%|██▍       | 527/2129 [00:35<02:11, 12.18it/s]
 25%|██▍       | 529/2129 [00:35<02:32, 10.51it/s]
 25%|██▍       | 531/2129 [00:35<02:46,  9.59it/s]
 25%|██▌       | 535/2129 [00:36<02:25, 10.95it/s]
 25%|██▌       | 537/2129 [00:36<02:23, 11.09it/s]
 25%|██▌       | 541/2129 [00:36<01:42, 15.48it/s]
 26%|██▌       | 543/2129 [00:36<01:44, 15.21it/s]
 26%|██▌       | 545/2129 [00:36<01:41, 15.55it/s]
 26%|██▌       | 547/2129 [00:36<01:52, 14.12it/s]
 26%|██▌       | 549/2129 [00:37<02:21, 11.14it/s]
 26%|██▌       | 553/2129 [00:37<01:49, 14.38it/s]
 26%|██▌       | 557/2129 [00:37<01:52, 13.92it/s]
 26%|██▋       | 559/2129 [00:37<02:07, 12.27it/s]
 26%|██▋       | 561/2129 [00:37<01:57, 13.34it/s]
 26%|██▋       | 563/2129 [00:38<02:13, 11.73it/s]
 27%|██▋       | 565/2129 [00:38<02:32, 10.28it/s]
 27%|██▋       | 567/2129 [00:38<02:44,  9.49it/s]
 27%|██▋       | 570/2129 [00:38<02:06, 12.28it/s]
 27%|██▋       | 572/2129 [00:39<02:27, 10.59it/s]
 27%|██▋       | 575/2129 [00:39<01:54, 13.53it/s]
 27%|██▋       | 577/2129 [00:39<02:13, 11.67it/s]
 27%|██▋       | 579/2129 [00:39<01:59, 12.99it/s]
 27%|██▋       | 581/2129 [00:39<02:11, 11.81it/s]
 27%|██▋       | 584/2129 [00:40<02:20, 10.99it/s]
 28%|██▊       | 586/2129 [00:40<02:31, 10.17it/s]
 28%|██▊       | 588/2129 [00:40<02:59,  8.56it/s]
 28%|██▊       | 589/2129 [00:40<03:21,  7.63it/s]
 28%|██▊       | 590/2129 [00:40<03:39,  7.01it/s]
 28%|██▊       | 593/2129 [00:41<03:04,  8.33it/s]
 28%|██▊       | 595/2129 [00:41<02:36,  9.78it/s]
 28%|██▊       | 599/2129 [00:41<02:07, 11.98it/s]
 28%|██▊       | 601/2129 [00:41<01:55, 13.24it/s]
 28%|██▊       | 605/2129 [00:42<01:53, 13.44it/s]
 29%|██▊       | 607/2129 [00:42<01:46, 14.34it/s]
 29%|██▊       | 610/2129 [00:42<01:46, 14.28it/s]
 29%|██▊       | 612/2129 [00:42<02:06, 11.95it/s]
 29%|██▉       | 614/2129 [00:42<02:24, 10.48it/s]
 29%|██▉       | 617/2129 [00:42<01:52, 13.44it/s]
 29%|██▉       | 623/2129 [00:43<01:10, 21.49it/s]
 29%|██▉       | 626/2129 [00:43<01:17, 19.28it/s]
 30%|██▉       | 629/2129 [00:43<01:22, 18.09it/s]
 30%|██▉       | 632/2129 [00:43<01:29, 16.76it/s]
 30%|██▉       | 634/2129 [00:43<01:28, 16.99it/s]
 30%|██▉       | 636/2129 [00:44<01:43, 14.47it/s]
 30%|██▉       | 638/2129 [00:44<01:43, 14.35it/s]
 30%|███       | 641/2129 [00:44<01:49, 13.56it/s]
 30%|███       | 644/2129 [00:44<01:55, 12.88it/s]
 30%|███       | 646/2129 [00:44<02:13, 11.08it/s]
 30%|███       | 649/2129 [00:45<02:14, 11.01it/s]
 31%|███       | 651/2129 [00:45<02:00, 12.32it/s]
 31%|███       | 653/2129 [00:45<02:14, 11.01it/s]
 31%|███       | 655/2129 [00:45<02:00, 12.19it/s]
 31%|███       | 658/2129 [00:45<01:59, 12.35it/s]
 31%|███       | 660/2129 [00:46<02:12, 11.05it/s]
 31%|███       | 662/2129 [00:46<02:57,  8.28it/s]
 31%|███       | 663/2129 [00:46<03:11,  7.65it/s]
 31%|███       | 665/2129 [00:46<02:39,  9.19it/s]
 31%|███▏      | 667/2129 [00:46<02:23, 10.20it/s]
 31%|███▏      | 669/2129 [00:47<02:04, 11.76it/s]
 32%|███▏      | 672/2129 [00:47<02:00, 12.09it/s]
 32%|███▏      | 674/2129 [00:47<02:20, 10.36it/s]
 32%|███▏      | 676/2129 [00:47<02:02, 11.87it/s]
 32%|███▏      | 678/2129 [00:47<02:18, 10.47it/s]
 32%|███▏      | 681/2129 [00:48<01:46, 13.57it/s]
 32%|███▏      | 683/2129 [00:48<01:57, 12.35it/s]
 32%|███▏      | 685/2129 [00:48<02:49,  8.52it/s]
 32%|███▏      | 687/2129 [00:48<02:55,  8.22it/s]
 32%|███▏      | 689/2129 [00:49<03:30,  6.83it/s]
 33%|███▎      | 692/2129 [00:49<02:33,  9.39it/s]
 33%|███▎      | 694/2129 [00:49<02:27,  9.70it/s]
 33%|███▎      | 696/2129 [00:49<02:45,  8.67it/s]
 33%|███▎      | 699/2129 [00:50<02:01, 11.74it/s]
 33%|███▎      | 703/2129 [00:50<01:48, 13.17it/s]
 33%|███▎      | 705/2129 [00:50<02:11, 10.79it/s]
 33%|███▎      | 707/2129 [00:50<02:17, 10.34it/s]
 33%|███▎      | 709/2129 [00:51<02:56,  8.02it/s]
 33%|███▎      | 711/2129 [00:51<02:33,  9.23it/s]
 33%|███▎      | 713/2129 [00:51<03:10,  7.43it/s]
 34%|███▎      | 717/2129 [00:51<02:06, 11.19it/s]
 34%|███▍      | 719/2129 [00:52<02:09, 10.88it/s]
 34%|███▍      | 721/2129 [00:52<02:24,  9.72it/s]
 34%|███▍      | 723/2129 [00:52<02:26,  9.57it/s]
 34%|███▍      | 725/2129 [00:52<02:35,  9.06it/s]
 34%|███▍      | 727/2129 [00:53<02:51,  8.16it/s]
 34%|███▍      | 728/2129 [00:53<03:06,  7.51it/s]
 34%|███▍      | 729/2129 [00:53<03:01,  7.71it/s]
 34%|███▍      | 732/2129 [00:53<02:09, 10.81it/s]
 34%|███▍      | 734/2129 [00:53<02:08, 10.86it/s]
 35%|███▍      | 737/2129 [00:54<02:12, 10.54it/s]
 35%|███▍      | 739/2129 [00:54<02:40,  8.68it/s]
 35%|███▍      | 741/2129 [00:54<02:22,  9.74it/s]
 35%|███▍      | 743/2129 [00:54<02:13, 10.40it/s]
 35%|███▌      | 746/2129 [00:54<01:43, 13.42it/s]
 35%|███▌      | 751/2129 [00:55<01:16, 17.91it/s]
 35%|███▌      | 753/2129 [00:55<01:33, 14.70it/s]
 35%|███▌      | 755/2129 [00:55<02:02, 11.20it/s]
 36%|███▌      | 757/2129 [00:55<01:49, 12.50it/s]
 36%|███▌      | 759/2129 [00:55<01:45, 12.97it/s]
 36%|███▌      | 762/2129 [00:56<01:49, 12.43it/s]
 36%|███▌      | 764/2129 [00:56<01:41, 13.47it/s]
 36%|███▌      | 766/2129 [00:56<01:59, 11.42it/s]
 36%|███▌      | 768/2129 [00:56<02:15, 10.06it/s]
 36%|███▌      | 770/2129 [00:56<02:29,  9.11it/s]
 36%|███▋      | 772/2129 [00:57<02:08, 10.53it/s]
 36%|███▋      | 774/2129 [00:57<02:14, 10.04it/s]
 36%|███▋      | 776/2129 [00:57<02:23,  9.44it/s]
 37%|███▋      | 778/2129 [00:57<02:05, 10.79it/s]
 37%|███▋      | 780/2129 [00:57<02:09, 10.45it/s]
 37%|███▋      | 782/2129 [00:58<02:22,  9.43it/s]
 37%|███▋      | 784/2129 [00:58<02:00, 11.16it/s]
 37%|███▋      | 786/2129 [00:58<02:22,  9.45it/s]
 37%|███▋      | 788/2129 [00:58<02:36,  8.59it/s]
 37%|███▋      | 791/2129 [00:58<01:52, 11.91it/s]
 37%|███▋      | 795/2129 [00:59<01:34, 14.12it/s]
 37%|███▋      | 797/2129 [00:59<01:47, 12.37it/s]
 38%|███▊      | 799/2129 [00:59<02:03, 10.75it/s]
 38%|███▊      | 801/2129 [00:59<02:14,  9.85it/s]
 38%|███▊      | 803/2129 [01:00<02:24,  9.18it/s]
 38%|███▊      | 805/2129 [01:00<02:22,  9.26it/s]
 38%|███▊      | 807/2129 [01:00<02:14,  9.86it/s]
 38%|███▊      | 809/2129 [01:00<02:23,  9.20it/s]
 38%|███▊      | 810/2129 [01:00<02:52,  7.65it/s]
 38%|███▊      | 812/2129 [01:01<02:20,  9.41it/s]
 38%|███▊      | 814/2129 [01:01<03:09,  6.92it/s]
 38%|███▊      | 816/2129 [01:01<02:42,  8.08it/s]
 38%|███▊      | 818/2129 [01:01<02:32,  8.60it/s]
 39%|███▊      | 820/2129 [01:02<02:33,  8.52it/s]
 39%|███▊      | 822/2129 [01:02<02:12,  9.86it/s]
 39%|███▊      | 824/2129 [01:02<01:58, 11.04it/s]
 39%|███▉      | 827/2129 [01:02<01:50, 11.81it/s]
 39%|███▉      | 830/2129 [01:02<01:28, 14.61it/s]
 39%|███▉      | 836/2129 [01:02<00:58, 21.93it/s]
 39%|███▉      | 839/2129 [01:03<01:19, 16.20it/s]
 40%|███▉      | 841/2129 [01:03<01:22, 15.69it/s]
 40%|███▉      | 843/2129 [01:03<01:51, 11.55it/s]
 40%|███▉      | 845/2129 [01:03<01:56, 10.99it/s]
 40%|███▉      | 847/2129 [01:04<01:50, 11.65it/s]
 40%|███▉      | 849/2129 [01:04<01:58, 10.76it/s]
 40%|███▉      | 851/2129 [01:04<01:46, 12.04it/s]
 40%|████      | 853/2129 [01:04<01:44, 12.17it/s]
 40%|████      | 855/2129 [01:04<02:14,  9.48it/s]
 40%|████      | 857/2129 [01:05<02:39,  7.98it/s]
 40%|████      | 858/2129 [01:05<02:43,  7.76it/s]
 40%|████      | 860/2129 [01:05<02:47,  7.59it/s]
 40%|████      | 862/2129 [01:05<02:39,  7.92it/s]
 41%|████      | 864/2129 [01:06<02:57,  7.11it/s]
 41%|████      | 865/2129 [01:06<03:14,  6.51it/s]
 41%|████      | 866/2129 [01:06<03:21,  6.25it/s]
 41%|████      | 869/2129 [01:06<02:12,  9.52it/s]
 41%|████      | 873/2129 [01:06<01:44, 12.02it/s]
 41%|████      | 876/2129 [01:07<01:50, 11.39it/s]
 41%|████▏     | 879/2129 [01:07<01:46, 11.73it/s]
 41%|████▏     | 881/2129 [01:07<02:02, 10.18it/s]
 42%|████▏     | 884/2129 [01:07<01:39, 12.55it/s]
 42%|████▏     | 886/2129 [01:08<01:44, 11.92it/s]
 42%|████▏     | 888/2129 [01:08<01:57, 10.60it/s]
 42%|████▏     | 890/2129 [01:08<02:11,  9.45it/s]
 42%|████▏     | 892/2129 [01:08<02:14,  9.19it/s]
 42%|████▏     | 894/2129 [01:08<01:59, 10.35it/s]
 42%|████▏     | 896/2129 [01:09<02:14,  9.16it/s]
 42%|████▏     | 898/2129 [01:09<02:22,  8.63it/s]
 42%|████▏     | 901/2129 [01:09<01:45, 11.64it/s]
 42%|████▏     | 903/2129 [01:10<02:27,  8.30it/s]
 43%|████▎     | 905/2129 [01:10<02:35,  7.88it/s]
 43%|████▎     | 907/2129 [01:10<02:40,  7.60it/s]
 43%|████▎     | 908/2129 [01:10<02:57,  6.88it/s]
 43%|████▎     | 911/2129 [01:11<02:33,  7.91it/s]
 43%|████▎     | 912/2129 [01:11<02:40,  7.60it/s]
 43%|████▎     | 914/2129 [01:11<02:39,  7.63it/s]
 43%|████▎     | 915/2129 [01:11<02:32,  7.96it/s]
 43%|████▎     | 918/2129 [01:11<01:43, 11.76it/s]
 43%|████▎     | 922/2129 [01:11<01:15, 16.09it/s]
 43%|████▎     | 924/2129 [01:12<01:15, 15.99it/s]
 43%|████▎     | 926/2129 [01:12<01:33, 12.91it/s]
 44%|████▎     | 928/2129 [01:12<02:05,  9.58it/s]
 44%|████▎     | 930/2129 [01:12<01:52, 10.70it/s]
 44%|████▍     | 932/2129 [01:13<02:13,  8.99it/s]
 44%|████▍     | 935/2129 [01:13<01:40, 11.92it/s]
 44%|████▍     | 937/2129 [01:13<01:55, 10.35it/s]
 44%|████▍     | 939/2129 [01:13<01:45, 11.29it/s]
 44%|████▍     | 941/2129 [01:13<01:33, 12.64it/s]
 44%|████▍     | 943/2129 [01:13<01:41, 11.66it/s]
 44%|████▍     | 945/2129 [01:14<02:09,  9.14it/s]
 44%|████▍     | 947/2129 [01:14<02:10,  9.08it/s]
 45%|████▍     | 950/2129 [01:14<01:57, 10.03it/s]
 45%|████▍     | 952/2129 [01:14<02:05,  9.36it/s]
 45%|████▍     | 954/2129 [01:15<01:48, 10.84it/s]
 45%|████▍     | 956/2129 [01:15<01:50, 10.61it/s]
 45%|████▍     | 958/2129 [01:15<01:44, 11.23it/s]
 45%|████▌     | 960/2129 [01:15<01:55, 10.09it/s]
 45%|████▌     | 962/2129 [01:15<01:51, 10.46it/s]
 45%|████▌     | 964/2129 [01:15<01:37, 11.90it/s]
 45%|████▌     | 966/2129 [01:16<01:29, 13.06it/s]
 45%|████▌     | 968/2129 [01:16<01:23, 13.98it/s]
 46%|████▌     | 970/2129 [01:16<01:42, 11.27it/s]
 46%|████▌     | 972/2129 [01:16<01:45, 10.97it/s]
 46%|████▌     | 974/2129 [01:17<02:28,  7.79it/s]
 46%|████▌     | 976/2129 [01:17<02:01,  9.49it/s]
 46%|████▌     | 978/2129 [01:17<01:59,  9.62it/s]
 46%|████▌     | 980/2129 [01:17<01:44, 10.95it/s]
 46%|████▌     | 982/2129 [01:17<01:42, 11.15it/s]
 46%|████▌     | 984/2129 [01:17<01:54, 10.00it/s]
 46%|████▋     | 986/2129 [01:18<01:42, 11.19it/s]
 46%|████▋     | 988/2129 [01:18<01:36, 11.84it/s]
 47%|████▋     | 991/2129 [01:18<01:21, 13.91it/s]
 47%|████▋     | 993/2129 [01:18<01:33, 12.16it/s]
 47%|████▋     | 996/2129 [01:18<01:17, 14.67it/s]
 47%|████▋     | 999/2129 [01:18<01:03, 17.67it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 314.99it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 4], [np.int64(2), False, 4], [np.int64(3), False, 5], [np.int64(4), False, 5], [np.int64(5), False, 13], [np.int64(6), False, 10], [np.int64(7), False, 3], [np.int64(8), False, 13], [np.int64(9), False, 4], [np.int64(10), False, 3], [np.int64(11), False, 3], [np.int64(12), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5160, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [07:35<2:25:32, 58.61s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [07:35<1:41:19, 41.08s/it]

tensor(11.9631, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5515, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9569, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6374, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [07:35<49:07, 20.19s/it]

tensor(11.9524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7285, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8488, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [07:36<16:41,  7.00s/it]

tensor(11.9473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9099, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9955, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [07:36<08:12,  3.49s/it]

tensor(11.9431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0127, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0249, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [07:36<05:47,  2.48s/it]

tensor(11.9381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0019, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9863, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [07:36<02:07,  1.07it/s]

tensor(11.9303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9754, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0109, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [07:37<01:09,  1.93it/s]

tensor(11.9219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0622, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0845, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [07:37<00:53,  2.50it/s]

tensor(11.9144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0263, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0357, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [07:37<00:28,  4.60it/s]

tensor(11.9175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0997, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1945, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [07:37<00:24,  5.32it/s]

tensor(11.9500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2764, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2985, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [07:38<00:18,  6.94it/s]

tensor(11.9645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2893, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2975, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [07:38<00:17,  7.20it/s]

tensor(11.9173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3522, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3962, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [07:38<00:15,  7.88it/s]

tensor(11.9045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4082, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4004, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [07:38<00:15,  7.84it/s]

tensor(11.9107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4161, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4223, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [07:39<00:14,  8.20it/s]

tensor(11.8754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4207, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4071, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [07:39<00:14,  8.22it/s]

tensor(11.8584, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4011, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4152, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [07:39<00:14,  8.19it/s]

tensor(11.8486, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4275, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4268, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [07:39<00:13,  8.23it/s]

tensor(11.8328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4222, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4146, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [07:39<00:13,  8.06it/s]

tensor(11.8258, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8174, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4242, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [07:40<00:13,  8.24it/s]

tensor(11.8122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4321, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8105, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4327, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [07:40<00:13,  8.21it/s]

tensor(11.8086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4350, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4365, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [07:40<00:12,  8.24it/s]

tensor(11.7985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4535, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [07:40<00:12,  8.27it/s]

tensor(11.7926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4618, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7888, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4600, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [07:41<00:12,  8.25it/s]

tensor(11.7849, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4622, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4658, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [07:41<00:12,  8.28it/s]

tensor(11.7764, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4668, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([247, 431,  69,  66, 112, 199,  79, 165, 201, 222,  37, 100,  90, 111])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 6/2129 [00:00<00:40, 52.37it/s]
  1%|          | 13/2129 [00:00<00:37, 55.98it/s]
  1%|          | 20/2129 [00:00<00:34, 60.53it/s]
  1%|▏         | 28/2129 [00:00<00:31, 66.15it/s]
  2%|▏         | 35/2129 [00:00<00:32, 64.65it/s]
  2%|▏         | 42/2129 [00:00<00:31, 65.42it/s]
  2%|▏         | 49/2129 [00:01<01:03, 32.75it/s]
  3%|▎         | 54/2129 [00:01<01:00, 34.27it/s]
  3%|▎         | 62/2129 [00:01<00:48, 42.94it/s]
  3%|▎         | 68/2129 [00:01<01:00, 33.89it/s]
  3%|▎         | 73/2129 [00:01<01:06, 30.84it/s]
  4%|▎         | 77/2129 [00:02<01:16, 26.75it/s]
  4%|▍         | 81/2129 [00:02<01:18, 26.19it/s]
  4%|▍         | 89/2129 [00:02<00:57, 35.48it/s]
  4%|▍         | 94/2129 [00:02<00:53, 37.78it/s]
  5%|▍         | 99/2129 [00:02<00:53, 37.80it/s]
  5%|▍         | 104/2129 [00:03<01:34, 21.44it/s]
  5%|▌         | 108/2129 [00:03<01:28, 22.95it/s]
  5%|▌         | 114/2129 [00:03<01:11, 28.24it/s]
  6%|▌         | 119/2129 [00:03<01:04, 31.30it/s]
  6%|▌         | 123/2129 [00:03<01:06, 30.37it/s]
  6%|▌         | 130/2129 [00:03<00:52, 37.95it/s]
  6%|▋         | 135/2129 [00:04<01:41, 19.56it/s]
  7%|▋         | 143/2129 [00:04<01:12, 27.44it/s]
  7%|▋         | 150/2129 [00:04<00:58, 33.55it/s]
  7%|▋         | 156/2129 [00:04<00:59, 33.39it/s]
  8%|▊         | 162/2129 [00:05<01:25, 22.87it/s]
  8%|▊         | 166/2129 [00:05<01:47, 18.30it/s]
  8%|▊         | 169/2129 [00:05<01:42, 19.18it/s]
  8%|▊         | 174/2129 [00:05<01:24, 23.23it/s]
  8%|▊         | 178/2129 [00:06<02:01, 15.99it/s]
  9%|▊         | 181/2129 [00:06<01:49, 17.72it/s]
  9%|▊         | 186/2129 [00:06<01:27, 22.17it/s]
  9%|▉         | 190/2129 [00:06<01:42, 18.96it/s]
  9%|▉         | 197/2129 [00:06<01:11, 27.03it/s]
  9%|▉         | 201/2129 [00:07<01:29, 21.45it/s]
 10%|▉         | 205/2129 [00:07<02:17, 14.02it/s]
 10%|▉         | 211/2129 [00:07<01:40, 19.15it/s]
 10%|█         | 215/2129 [00:08<02:31, 12.60it/s]
 10%|█         | 218/2129 [00:08<02:21, 13.46it/s]
 10%|█         | 221/2129 [00:08<02:09, 14.76it/s]
 11%|█         | 227/2129 [00:08<01:30, 21.01it/s]
 11%|█         | 232/2129 [00:08<01:13, 25.64it/s]
 11%|█         | 236/2129 [00:09<02:33, 12.32it/s]
 11%|█▏        | 240/2129 [00:09<02:05, 15.04it/s]
 12%|█▏        | 247/2129 [00:09<01:25, 21.95it/s]
 12%|█▏        | 252/2129 [00:10<02:51, 10.93it/s]
 12%|█▏        | 255/2129 [00:11<02:33, 12.19it/s]
 12%|█▏        | 260/2129 [00:11<02:09, 14.39it/s]
 12%|█▏        | 263/2129 [00:11<02:05, 14.89it/s]
 13%|█▎        | 267/2129 [00:11<01:42, 18.10it/s]
 13%|█▎        | 273/2129 [00:11<01:34, 19.70it/s]
 13%|█▎        | 276/2129 [00:12<01:46, 17.47it/s]
 13%|█▎        | 279/2129 [00:12<01:38, 18.87it/s]
 13%|█▎        | 285/2129 [00:12<01:11, 25.97it/s]
 14%|█▎        | 292/2129 [00:12<00:53, 34.04it/s]
 14%|█▍        | 297/2129 [00:12<01:17, 23.55it/s]
 14%|█▍        | 303/2129 [00:12<01:02, 29.32it/s]
 14%|█▍        | 308/2129 [00:13<01:27, 20.71it/s]
 15%|█▍        | 312/2129 [00:13<01:20, 22.61it/s]
 15%|█▍        | 316/2129 [00:13<01:48, 16.75it/s]
 15%|█▌        | 320/2129 [00:14<02:02, 14.77it/s]
 15%|█▌        | 323/2129 [00:14<01:55, 15.66it/s]
 15%|█▌        | 328/2129 [00:14<01:27, 20.56it/s]
 16%|█▌        | 331/2129 [00:14<01:47, 16.73it/s]
 16%|█▌        | 334/2129 [00:15<02:20, 12.81it/s]
 16%|█▌        | 337/2129 [00:15<02:03, 14.50it/s]
 16%|█▌        | 340/2129 [00:15<01:49, 16.29it/s]
 16%|█▌        | 343/2129 [00:16<03:17,  9.05it/s]
 16%|█▌        | 345/2129 [00:16<04:12,  7.07it/s]
 16%|█▋        | 347/2129 [00:16<03:36,  8.23it/s]
 16%|█▋        | 349/2129 [00:17<04:02,  7.33it/s]
 17%|█▋        | 353/2129 [00:17<02:42, 10.90it/s]
 17%|█▋        | 355/2129 [00:17<03:45,  7.88it/s]
 17%|█▋        | 357/2129 [00:18<04:26,  6.64it/s]
 17%|█▋        | 359/2129 [00:18<05:10,  5.70it/s]
 17%|█▋        | 363/2129 [00:18<03:20,  8.83it/s]
 17%|█▋        | 370/2129 [00:18<01:49, 16.07it/s]
 18%|█▊        | 374/2129 [00:19<02:25, 12.03it/s]
 18%|█▊        | 377/2129 [00:19<03:01,  9.63it/s]
 18%|█▊        | 380/2129 [00:20<03:28,  8.39it/s]
 18%|█▊        | 382/2129 [00:20<03:07,  9.33it/s]
 18%|█▊        | 384/2129 [00:20<03:56,  7.39it/s]
 18%|█▊        | 387/2129 [00:21<03:02,  9.57it/s]
 18%|█▊        | 391/2129 [00:21<03:09,  9.19it/s]
 18%|█▊        | 393/2129 [00:21<03:15,  8.86it/s]
 19%|█▊        | 395/2129 [00:22<04:07,  7.01it/s]
 19%|█▊        | 398/2129 [00:22<03:05,  9.33it/s]
 19%|█▉        | 400/2129 [00:22<03:52,  7.44it/s]
 19%|█▉        | 403/2129 [00:22<02:56,  9.79it/s]
 19%|█▉        | 405/2129 [00:23<04:05,  7.01it/s]
 19%|█▉        | 408/2129 [00:23<03:06,  9.21it/s]
 19%|█▉        | 412/2129 [00:23<02:11, 13.04it/s]
 19%|█▉        | 415/2129 [00:23<02:03, 13.90it/s]
 20%|█▉        | 418/2129 [00:24<01:45, 16.28it/s]
 20%|█▉        | 425/2129 [00:24<01:05, 25.93it/s]
 20%|██        | 429/2129 [00:24<00:59, 28.37it/s]
 20%|██        | 433/2129 [00:24<01:51, 15.24it/s]
 20%|██        | 436/2129 [00:24<01:43, 16.29it/s]
 21%|██        | 439/2129 [00:25<01:37, 17.26it/s]
 21%|██        | 443/2129 [00:25<01:22, 20.54it/s]
 21%|██        | 447/2129 [00:25<01:10, 23.79it/s]
 21%|██        | 452/2129 [00:25<00:59, 28.41it/s]
 21%|██▏       | 456/2129 [00:25<01:43, 16.16it/s]
 22%|██▏       | 460/2129 [00:26<01:27, 19.17it/s]
 22%|██▏       | 466/2129 [00:26<01:42, 16.21it/s]
 22%|██▏       | 469/2129 [00:26<01:39, 16.68it/s]
 22%|██▏       | 473/2129 [00:26<01:23, 19.79it/s]
 22%|██▏       | 478/2129 [00:27<01:23, 19.67it/s]
 23%|██▎       | 481/2129 [00:27<01:31, 18.02it/s]
 23%|██▎       | 484/2129 [00:27<02:01, 13.52it/s]
 23%|██▎       | 486/2129 [00:27<02:06, 13.03it/s]
 23%|██▎       | 488/2129 [00:28<02:12, 12.41it/s]
 23%|██▎       | 490/2129 [00:28<03:19,  8.20it/s]
 23%|██▎       | 492/2129 [00:28<02:52,  9.48it/s]
 23%|██▎       | 499/2129 [00:28<01:30, 18.01it/s]
 24%|██▎       | 502/2129 [00:28<01:28, 18.35it/s]
 24%|██▍       | 506/2129 [00:29<01:14, 21.69it/s]
 24%|██▍       | 509/2129 [00:29<01:29, 18.07it/s]
 24%|██▍       | 512/2129 [00:29<01:45, 15.33it/s]
 24%|██▍       | 515/2129 [00:30<02:27, 10.98it/s]
 24%|██▍       | 518/2129 [00:30<02:02, 13.17it/s]
 24%|██▍       | 521/2129 [00:30<02:36, 10.28it/s]
 25%|██▍       | 523/2129 [00:31<03:26,  7.80it/s]
 25%|██▍       | 525/2129 [00:31<03:11,  8.38it/s]
 25%|██▍       | 527/2129 [00:31<04:00,  6.65it/s]
 25%|██▍       | 528/2129 [00:32<05:08,  5.19it/s]
 25%|██▍       | 531/2129 [00:32<03:33,  7.49it/s]
 25%|██▌       | 535/2129 [00:32<03:16,  8.12it/s]
 25%|██▌       | 537/2129 [00:33<03:58,  6.68it/s]
 25%|██▌       | 541/2129 [00:33<02:39,  9.94it/s]
 26%|██▌       | 547/2129 [00:33<02:21, 11.22it/s]
 26%|██▌       | 549/2129 [00:33<02:29, 10.56it/s]
 26%|██▌       | 553/2129 [00:34<01:51, 14.09it/s]
 26%|██▌       | 557/2129 [00:34<02:15, 11.59it/s]
 26%|██▋       | 559/2129 [00:35<03:01,  8.64it/s]
 26%|██▋       | 561/2129 [00:35<02:41,  9.68it/s]
 26%|██▋       | 563/2129 [00:36<04:37,  5.65it/s]
 27%|██▋       | 565/2129 [00:36<03:52,  6.71it/s]
 27%|██▋       | 573/2129 [00:36<01:47, 14.42it/s]
 27%|██▋       | 577/2129 [00:36<02:05, 12.40it/s]
 27%|██▋       | 580/2129 [00:36<01:49, 14.21it/s]
 27%|██▋       | 585/2129 [00:37<02:00, 12.79it/s]
 28%|██▊       | 588/2129 [00:37<01:47, 14.37it/s]
 28%|██▊       | 591/2129 [00:38<03:01,  8.49it/s]
 28%|██▊       | 593/2129 [00:38<03:06,  8.22it/s]
 28%|██▊       | 596/2129 [00:38<02:37,  9.73it/s]
 28%|██▊       | 599/2129 [00:39<03:07,  8.14it/s]
 28%|██▊       | 602/2129 [00:39<03:04,  8.29it/s]
 28%|██▊       | 604/2129 [00:39<02:50,  8.92it/s]
 28%|██▊       | 606/2129 [00:39<02:57,  8.57it/s]
 29%|██▊       | 610/2129 [00:39<02:03, 12.33it/s]
 29%|██▊       | 612/2129 [00:40<02:58,  8.51it/s]
 29%|██▉       | 614/2129 [00:40<03:46,  6.69it/s]
 29%|██▉       | 620/2129 [00:41<02:04, 12.13it/s]
 29%|██▉       | 626/2129 [00:41<02:07, 11.75it/s]
 30%|██▉       | 629/2129 [00:42<02:53,  8.64it/s]
 30%|██▉       | 631/2129 [00:42<03:21,  7.44it/s]
 30%|██▉       | 633/2129 [00:43<03:56,  6.34it/s]
 30%|██▉       | 636/2129 [00:43<04:01,  6.19it/s]
 30%|██▉       | 638/2129 [00:43<03:26,  7.22it/s]
 30%|███       | 641/2129 [00:44<03:37,  6.84it/s]
 30%|███       | 643/2129 [00:44<04:02,  6.13it/s]
 30%|███       | 644/2129 [00:45<04:58,  4.97it/s]
 30%|███       | 647/2129 [00:45<03:30,  7.05it/s]
 30%|███       | 649/2129 [00:45<03:34,  6.91it/s]
 31%|███       | 651/2129 [00:45<02:56,  8.37it/s]
 31%|███       | 653/2129 [00:45<02:36,  9.46it/s]
 31%|███       | 655/2129 [00:46<02:30,  9.78it/s]
 31%|███       | 657/2129 [00:46<02:15, 10.84it/s]
 31%|███       | 659/2129 [00:46<02:38,  9.29it/s]
 31%|███       | 661/2129 [00:46<02:19, 10.51it/s]
 31%|███       | 663/2129 [00:47<03:29,  6.99it/s]
 31%|███▏      | 667/2129 [00:47<02:15, 10.82it/s]
 32%|███▏      | 672/2129 [00:47<01:58, 12.27it/s]
 32%|███▏      | 674/2129 [00:48<02:39,  9.14it/s]
 32%|███▏      | 676/2129 [00:48<02:48,  8.62it/s]
 32%|███▏      | 678/2129 [00:48<02:33,  9.45it/s]
 32%|███▏      | 681/2129 [00:48<01:57, 12.28it/s]
 32%|███▏      | 683/2129 [00:49<02:45,  8.76it/s]
 32%|███▏      | 685/2129 [00:49<03:42,  6.50it/s]
 32%|███▏      | 687/2129 [00:50<04:20,  5.54it/s]
 32%|███▏      | 688/2129 [00:50<04:30,  5.33it/s]
 32%|███▏      | 689/2129 [00:50<04:39,  5.16it/s]
 32%|███▏      | 690/2129 [00:50<04:15,  5.63it/s]
 33%|███▎      | 694/2129 [00:50<02:42,  8.85it/s]
 33%|███▎      | 696/2129 [00:51<03:18,  7.21it/s]
 33%|███▎      | 698/2129 [00:51<02:45,  8.66it/s]
 33%|███▎      | 700/2129 [00:51<02:21, 10.11it/s]
 33%|███▎      | 703/2129 [00:51<01:46, 13.37it/s]
 33%|███▎      | 707/2129 [00:52<02:13, 10.61it/s]
 33%|███▎      | 709/2129 [00:52<03:06,  7.61it/s]
 33%|███▎      | 712/2129 [00:52<02:28,  9.51it/s]
 34%|███▎      | 714/2129 [00:52<02:11, 10.75it/s]
 34%|███▍      | 719/2129 [00:53<02:09, 10.87it/s]
 34%|███▍      | 722/2129 [00:53<01:46, 13.24it/s]
 34%|███▍      | 724/2129 [00:53<02:37,  8.91it/s]
 34%|███▍      | 726/2129 [00:54<04:19,  5.40it/s]
 34%|███▍      | 728/2129 [00:55<04:34,  5.11it/s]
 34%|███▍      | 730/2129 [00:55<03:42,  6.30it/s]
 34%|███▍      | 734/2129 [00:55<02:30,  9.29it/s]
 35%|███▍      | 737/2129 [00:55<02:25,  9.54it/s]
 35%|███▍      | 739/2129 [00:56<02:36,  8.88it/s]
 35%|███▍      | 741/2129 [00:56<02:48,  8.24it/s]
 35%|███▍      | 743/2129 [00:56<02:26,  9.46it/s]
 35%|███▍      | 745/2129 [00:56<02:09, 10.72it/s]
 35%|███▌      | 747/2129 [00:56<01:54, 12.11it/s]
 35%|███▌      | 752/2129 [00:56<01:12, 18.91it/s]
 35%|███▌      | 755/2129 [00:57<01:55, 11.86it/s]
 36%|███▌      | 757/2129 [00:57<01:47, 12.75it/s]
 36%|███▌      | 759/2129 [00:57<02:31,  9.04it/s]
 36%|███▌      | 761/2129 [00:57<02:11, 10.41it/s]
 36%|███▌      | 765/2129 [00:58<01:30, 15.04it/s]
 36%|███▌      | 768/2129 [00:58<01:37, 13.93it/s]
 36%|███▌      | 770/2129 [00:58<02:22,  9.55it/s]
 36%|███▋      | 773/2129 [00:58<01:51, 12.15it/s]
 36%|███▋      | 776/2129 [00:59<02:19,  9.69it/s]
 37%|███▋      | 778/2129 [00:59<02:27,  9.13it/s]
 37%|███▋      | 780/2129 [00:59<03:06,  7.22it/s]
 37%|███▋      | 782/2129 [01:00<03:37,  6.20it/s]
 37%|███▋      | 784/2129 [01:00<03:08,  7.15it/s]
 37%|███▋      | 786/2129 [01:00<02:37,  8.55it/s]
 37%|███▋      | 788/2129 [01:01<03:09,  7.09it/s]
 37%|███▋      | 791/2129 [01:01<02:19,  9.61it/s]
 37%|███▋      | 795/2129 [01:01<01:36, 13.83it/s]
 37%|███▋      | 798/2129 [01:01<01:25, 15.59it/s]
 38%|███▊      | 801/2129 [01:01<01:59, 11.10it/s]
 38%|███▊      | 803/2129 [01:02<02:38,  8.35it/s]
 38%|███▊      | 806/2129 [01:02<02:01, 10.90it/s]
 38%|███▊      | 809/2129 [01:02<02:08, 10.29it/s]
 38%|███▊      | 811/2129 [01:03<02:44,  8.02it/s]
 38%|███▊      | 813/2129 [01:03<03:06,  7.05it/s]
 38%|███▊      | 815/2129 [01:03<02:41,  8.12it/s]
 38%|███▊      | 817/2129 [01:03<02:16,  9.61it/s]
 38%|███▊      | 819/2129 [01:04<03:14,  6.75it/s]
 39%|███▉      | 825/2129 [01:04<01:40, 13.01it/s]
 39%|███▉      | 828/2129 [01:04<02:01, 10.72it/s]
 39%|███▉      | 831/2129 [01:05<01:47, 12.08it/s]
 39%|███▉      | 833/2129 [01:05<01:40, 12.95it/s]
 39%|███▉      | 837/2129 [01:05<01:15, 17.22it/s]
 39%|███▉      | 840/2129 [01:05<01:49, 11.77it/s]
 40%|███▉      | 842/2129 [01:06<02:27,  8.71it/s]
 40%|███▉      | 844/2129 [01:06<03:04,  6.96it/s]
 40%|███▉      | 846/2129 [01:07<03:34,  5.98it/s]
 40%|███▉      | 847/2129 [01:07<03:26,  6.22it/s]
 40%|███▉      | 848/2129 [01:07<04:03,  5.25it/s]
 40%|███▉      | 850/2129 [01:07<03:03,  6.98it/s]
 40%|████      | 852/2129 [01:07<02:26,  8.71it/s]
 40%|████      | 854/2129 [01:08<03:11,  6.65it/s]
 40%|████      | 856/2129 [01:08<03:10,  6.69it/s]
 40%|████      | 858/2129 [01:08<02:40,  7.94it/s]
 40%|████      | 860/2129 [01:09<03:25,  6.19it/s]
 40%|████      | 862/2129 [01:09<03:52,  5.44it/s]
 41%|████      | 864/2129 [01:10<04:16,  4.94it/s]
 41%|████      | 865/2129 [01:10<04:59,  4.22it/s]
 41%|████      | 867/2129 [01:10<03:47,  5.54it/s]
 41%|████      | 872/2129 [01:10<02:21,  8.89it/s]
 41%|████      | 874/2129 [01:11<02:55,  7.14it/s]
 41%|████      | 876/2129 [01:11<02:38,  7.89it/s]
 41%|████      | 878/2129 [01:11<02:15,  9.22it/s]
 41%|████▏     | 881/2129 [01:12<02:43,  7.61it/s]
 41%|████▏     | 883/2129 [01:12<03:23,  6.13it/s]
 42%|████▏     | 885/2129 [01:12<02:45,  7.53it/s]
 42%|████▏     | 887/2129 [01:12<02:20,  8.81it/s]
 42%|████▏     | 890/2129 [01:13<02:08,  9.67it/s]
 42%|████▏     | 892/2129 [01:13<02:47,  7.36it/s]
 42%|████▏     | 894/2129 [01:14<03:32,  5.81it/s]
 42%|████▏     | 900/2129 [01:14<01:54, 10.78it/s]
 42%|████▏     | 903/2129 [01:14<02:17,  8.93it/s]
 43%|████▎     | 905/2129 [01:15<02:06,  9.65it/s]
 43%|████▎     | 908/2129 [01:15<01:42, 11.92it/s]
 43%|████▎     | 910/2129 [01:15<01:43, 11.83it/s]
 43%|████▎     | 912/2129 [01:15<02:22,  8.55it/s]
 43%|████▎     | 914/2129 [01:15<02:22,  8.54it/s]
 43%|████▎     | 916/2129 [01:16<03:06,  6.50it/s]
 43%|████▎     | 919/2129 [01:16<02:13,  9.03it/s]
 43%|████▎     | 921/2129 [01:16<02:07,  9.47it/s]
 43%|████▎     | 925/2129 [01:16<01:25, 14.00it/s]
 44%|████▎     | 928/2129 [01:18<03:35,  5.57it/s]
 44%|████▎     | 930/2129 [01:18<03:02,  6.58it/s]
 44%|████▍     | 933/2129 [01:18<02:15,  8.82it/s]
 44%|████▍     | 935/2129 [01:18<02:51,  6.97it/s]
 44%|████▍     | 937/2129 [01:19<03:25,  5.79it/s]
 44%|████▍     | 940/2129 [01:19<02:44,  7.23it/s]
 44%|████▍     | 943/2129 [01:19<02:07,  9.27it/s]
 44%|████▍     | 945/2129 [01:20<03:44,  5.28it/s]
 44%|████▍     | 947/2129 [01:21<04:18,  4.58it/s]
 45%|████▍     | 949/2129 [01:21<03:27,  5.68it/s]
 45%|████▍     | 952/2129 [01:21<03:19,  5.90it/s]
 45%|████▍     | 954/2129 [01:21<02:43,  7.20it/s]
 45%|████▍     | 956/2129 [01:22<02:25,  8.05it/s]
 45%|████▍     | 958/2129 [01:22<02:01,  9.62it/s]
 45%|████▌     | 961/2129 [01:22<02:18,  8.43it/s]
 45%|████▌     | 963/2129 [01:22<01:58,  9.81it/s]
 45%|████▌     | 968/2129 [01:23<01:55, 10.02it/s]
 46%|████▌     | 970/2129 [01:23<02:38,  7.31it/s]
 46%|████▌     | 972/2129 [01:24<03:10,  6.09it/s]
 46%|████▌     | 976/2129 [01:24<02:05,  9.22it/s]
 46%|████▌     | 978/2129 [01:24<02:39,  7.23it/s]
 46%|████▌     | 980/2129 [01:24<02:14,  8.54it/s]
 46%|████▌     | 982/2129 [01:25<02:47,  6.85it/s]
 46%|████▌     | 984/2129 [01:25<03:21,  5.69it/s]
 46%|████▋     | 987/2129 [01:26<02:21,  8.06it/s]
 46%|████▋     | 989/2129 [01:26<02:55,  6.51it/s]
 47%|████▋     | 992/2129 [01:26<02:06,  8.97it/s]
 47%|████▋     | 994/2129 [01:27<02:37,  7.23it/s]
 47%|████▋     | 997/2129 [01:27<01:57,  9.61it/s]
 47%|████▋     | 1001/2129 [01:27<01:38, 11.41it/s]
 47%|████▋     | 1004/2129 [01:27<01:25, 13.12it/s]
 47%|████▋     | 1006/2129 [01:28<02:15,  8.30it/s]
 47%|████▋     | 1008/2129 [01:28<02:25,  7.70it/s]
 47%|████▋     | 1010/2129 [01:28<02:28,  7.54it/s]
 48%|████▊     | 1012/2129 [01:28<02:31,  7.37it/s]
 48%|████▊     | 1013/2129 [01:29<02:37,  7.07it/s]
 48%|████▊     | 1015/2129 [01:29<02:56,  6.33it/s]
 48%|████▊     | 1018/2129 [01:29<02:49,  6.56it/s]
 48%|████▊     | 1021/2129 [01:30<02:57,  6.23it/s]
 48%|████▊     | 1023/2129 [01:30<02:26,  7.56it/s]
 48%|████▊     | 1025/2129 [01:31<02:55,  6.30it/s]
 48%|████▊     | 1029/2129 [01:31<01:51,  9.83it/s]
 48%|████▊     | 1032/2129 [01:31<01:38, 11.10it/s]
 49%|████▊     | 1034/2129 [01:31<01:42, 10.68it/s]
 49%|████▊     | 1036/2129 [01:31<01:30, 12.08it/s]
 49%|████▉     | 1041/2129 [01:31<01:17, 14.09it/s]
 49%|████▉     | 1044/2129 [01:32<01:06, 16.36it/s]
 49%|████▉     | 1046/2129 [01:32<01:16, 14.17it/s]
 49%|████▉     | 1048/2129 [01:32<02:04,  8.71it/s]
 49%|████▉     | 1050/2129 [01:33<02:07,  8.49it/s]
 49%|████▉     | 1052/2129 [01:33<02:37,  6.82it/s]
 50%|████▉     | 1055/2129 [01:33<02:20,  7.62it/s]
 50%|████▉     | 1057/2129 [01:34<02:10,  8.23it/s]
 50%|████▉     | 1058/2129 [01:34<02:27,  7.24it/s]
 50%|████▉     | 1060/2129 [01:34<02:48,  6.35it/s]
 50%|████▉     | 1062/2129 [01:34<02:18,  7.70it/s]
 50%|█████     | 1066/2129 [01:34<01:27, 12.12it/s]
 50%|█████     | 1068/2129 [01:35<02:06,  8.40it/s]
 50%|█████     | 1070/2129 [01:35<01:52,  9.42it/s]
 50%|█████     | 1072/2129 [01:35<02:18,  7.64it/s]
 50%|█████     | 1074/2129 [01:36<02:40,  6.57it/s]
 50%|█████     | 1075/2129 [01:36<02:37,  6.71it/s]
 51%|█████     | 1077/2129 [01:36<02:48,  6.24it/s]
 51%|█████     | 1078/2129 [01:36<02:49,  6.21it/s]
 51%|█████     | 1080/2129 [01:37<02:44,  6.40it/s]
 51%|█████     | 1082/2129 [01:37<02:26,  7.15it/s]
 51%|█████     | 1083/2129 [01:37<02:57,  5.88it/s]
 51%|█████     | 1086/2129 [01:37<01:58,  8.77it/s]
 51%|█████     | 1091/2129 [01:38<01:45,  9.82it/s]
 51%|█████▏    | 1093/2129 [01:38<01:35, 10.89it/s]
 51%|█████▏    | 1096/2129 [01:38<01:17, 13.36it/s]
 52%|█████▏    | 1099/2129 [01:38<01:11, 14.33it/s]
 52%|█████▏    | 1102/2129 [01:38<01:05, 15.77it/s]
 52%|█████▏    | 1106/2129 [01:39<01:15, 13.59it/s]
 52%|█████▏    | 1108/2129 [01:39<01:39, 10.25it/s]
 52%|█████▏    | 1110/2129 [01:39<01:41, 10.09it/s]
 52%|█████▏    | 1112/2129 [01:40<01:59,  8.54it/s]
 52%|█████▏    | 1114/2129 [01:40<02:42,  6.25it/s]
 52%|█████▏    | 1116/2129 [01:41<03:01,  5.59it/s]
 53%|█████▎    | 1119/2129 [01:41<02:09,  7.80it/s]
 53%|█████▎    | 1121/2129 [01:41<02:38,  6.37it/s]
 53%|█████▎    | 1123/2129 [01:42<03:03,  5.47it/s]
 53%|█████▎    | 1125/2129 [01:42<02:26,  6.85it/s]
 53%|█████▎    | 1127/2129 [01:43<03:25,  4.87it/s]
 53%|█████▎    | 1129/2129 [01:43<02:48,  5.94it/s]
 53%|█████▎    | 1131/2129 [01:43<02:16,  7.34it/s]
 53%|█████▎    | 1133/2129 [01:43<02:17,  7.25it/s]
 53%|█████▎    | 1135/2129 [01:44<02:30,  6.58it/s]
 53%|█████▎    | 1136/2129 [01:44<02:37,  6.30it/s]
 53%|█████▎    | 1139/2129 [01:44<02:29,  6.63it/s]
 54%|█████▎    | 1141/2129 [01:44<02:11,  7.49it/s]
 54%|█████▎    | 1143/2129 [01:44<01:47,  9.14it/s]
 54%|█████▍    | 1145/2129 [01:45<02:07,  7.70it/s]
 54%|█████▍    | 1148/2129 [01:45<01:34, 10.33it/s]
 54%|█████▍    | 1151/2129 [01:45<01:16, 12.78it/s]
 54%|█████▍    | 1153/2129 [01:46<02:09,  7.55it/s]
 54%|█████▍    | 1155/2129 [01:46<02:33,  6.36it/s]
 54%|█████▍    | 1157/2129 [01:47<02:50,  5.71it/s]
 54%|█████▍    | 1158/2129 [01:47<03:05,  5.24it/s]
 54%|█████▍    | 1159/2129 [01:47<03:21,  4.82it/s]
 55%|█████▍    | 1163/2129 [01:47<01:58,  8.18it/s]
 55%|█████▍    | 1165/2129 [01:48<02:01,  7.94it/s]
 55%|█████▍    | 1166/2129 [01:48<02:25,  6.61it/s]
 55%|█████▍    | 1167/2129 [01:48<02:31,  6.37it/s]
 55%|█████▍    | 1169/2129 [01:48<01:54,  8.35it/s]
 55%|█████▌    | 1171/2129 [01:48<02:01,  7.86it/s]
 55%|█████▌    | 1173/2129 [01:49<02:19,  6.85it/s]
 55%|█████▌    | 1174/2129 [01:49<03:11,  4.99it/s]
 55%|█████▌    | 1176/2129 [01:50<03:37,  4.38it/s]
 55%|█████▌    | 1177/2129 [01:50<03:35,  4.43it/s]
 55%|█████▌    | 1179/2129 [01:50<02:55,  5.40it/s]
 55%|█████▌    | 1180/2129 [01:51<03:48,  4.16it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 317.86it/s]

[[np.int64(0), False, 1], [np.int64(1), False, 8], [np.int64(2), False, 7], [np.int64(3), False, 1], [np.int64(4), False, 9], [np.int64(5), False, 9], [np.int64(6), False, 2], [np.int64(9), False, 0], [np.int64(10), False, 7], [np.int64(11), False, 13], [np.int64(12), False, 5], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2934, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [11:34<1:55:17, 69.88s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [11:34<1:19:58, 48.96s/it]

tensor(11.7747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5131, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8367, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [11:34<38:29, 24.05s/it]

tensor(11.8255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0865, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [11:34<18:33, 11.85s/it]

tensor(11.8598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0779, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8463, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1183, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [11:35<06:17,  4.14s/it]

tensor(11.8249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2514, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [11:35<03:06,  2.09s/it]

tensor(11.8126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2839, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2345, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [11:35<01:34,  1.09s/it]

tensor(11.8460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2325, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8404, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2351, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [11:35<01:08,  1.25it/s]

tensor(11.8157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2970, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3556, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [11:36<00:29,  2.83it/s]

tensor(11.7981, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3973, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4039, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [11:36<00:19,  4.26it/s]

tensor(11.8225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4082, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3944, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [11:36<00:13,  5.65it/s]

tensor(11.8284, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3860, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3837, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [11:36<00:12,  6.23it/s]

tensor(11.8009, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4011, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7806, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4156, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [11:36<00:10,  7.02it/s]

tensor(11.7637, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4253, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4313, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [11:37<00:09,  7.79it/s]

tensor(11.7573, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4492, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4606, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [11:37<00:09,  7.90it/s]

tensor(11.7679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4756, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4826, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [11:37<00:08,  8.20it/s]

tensor(11.7576, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4924, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4988, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [11:38<00:08,  8.15it/s]

tensor(11.7445, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5045, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [11:38<00:08,  8.08it/s]

tensor(11.7438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5065, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5076, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [11:38<00:07,  8.17it/s]

tensor(11.7417, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7384, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5154, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [11:38<00:07,  8.22it/s]

tensor(11.7331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5189, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5218, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [11:38<00:07,  8.25it/s]

tensor(11.7239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5249, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5290, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [11:39<00:06,  8.25it/s]

tensor(11.7209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5357, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5362, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [11:39<00:06,  8.14it/s]

tensor(11.7185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5364, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [11:39<00:06,  8.23it/s]

tensor(11.7134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5354, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5347, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [11:39<00:06,  8.24it/s]

tensor(11.7097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5301, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5297, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [11:40<00:06,  8.12it/s]

tensor(11.7079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5292, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 44, 148, 210,  94,  95, 158, 167,  97, 310, 147,  32, 323, 106, 198])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:13, 28.98it/s]
  1%|          | 11/2129 [00:00<00:38, 55.15it/s]
  1%|          | 19/2129 [00:00<00:32, 65.08it/s]
  1%|          | 26/2129 [00:00<00:33, 63.72it/s]
  2%|▏         | 33/2129 [00:00<00:32, 63.88it/s]
  2%|▏         | 40/2129 [00:00<00:38, 53.87it/s]
  2%|▏         | 46/2129 [00:01<01:13, 28.36it/s]
  2%|▏         | 53/2129 [00:01<00:59, 34.61it/s]
  3%|▎         | 59/2129 [00:01<00:53, 38.79it/s]
  3%|▎         | 65/2129 [00:01<01:26, 23.88it/s]
  3%|▎         | 69/2129 [00:02<01:24, 24.44it/s]
  3%|▎         | 73/2129 [00:02<01:41, 20.16it/s]
  4%|▎         | 76/2129 [00:02<01:39, 20.68it/s]
  4%|▍         | 80/2129 [00:02<01:41, 20.14it/s]
  4%|▍         | 83/2129 [00:02<01:39, 20.66it/s]
  4%|▍         | 91/2129 [00:02<01:05, 31.23it/s]
  5%|▍         | 97/2129 [00:03<01:00, 33.51it/s]
  5%|▍         | 101/2129 [00:03<01:07, 29.96it/s]
  5%|▍         | 105/2129 [00:03<01:47, 18.76it/s]
  5%|▌         | 108/2129 [00:03<01:46, 18.93it/s]
  5%|▌         | 113/2129 [00:03<01:25, 23.70it/s]
  6%|▌         | 118/2129 [00:04<01:11, 28.10it/s]
  6%|▌         | 124/2129 [00:04<00:57, 34.72it/s]
  6%|▌         | 131/2129 [00:04<00:47, 41.79it/s]
  6%|▋         | 137/2129 [00:04<00:43, 46.13it/s]
  7%|▋         | 145/2129 [00:04<00:37, 52.81it/s]
  7%|▋         | 151/2129 [00:04<00:36, 54.69it/s]
  7%|▋         | 157/2129 [00:04<01:01, 32.06it/s]
  8%|▊         | 162/2129 [00:05<01:18, 25.06it/s]
  8%|▊         | 166/2129 [00:05<01:33, 21.03it/s]
  8%|▊         | 169/2129 [00:05<01:28, 22.15it/s]
  8%|▊         | 175/2129 [00:05<01:08, 28.42it/s]
  8%|▊         | 179/2129 [00:06<01:26, 22.47it/s]
  9%|▊         | 183/2129 [00:06<01:19, 24.61it/s]
  9%|▉         | 187/2129 [00:06<02:14, 14.40it/s]
  9%|▉         | 190/2129 [00:07<02:44, 11.81it/s]
  9%|▉         | 193/2129 [00:07<02:24, 13.42it/s]
  9%|▉         | 200/2129 [00:07<02:07, 15.12it/s]
  9%|▉         | 202/2129 [00:07<02:05, 15.34it/s]
 10%|▉         | 209/2129 [00:07<01:23, 23.04it/s]
 10%|█         | 213/2129 [00:08<01:34, 20.31it/s]
 10%|█         | 216/2129 [00:08<01:53, 16.93it/s]
 10%|█         | 221/2129 [00:08<01:27, 21.84it/s]
 11%|█         | 225/2129 [00:08<01:53, 16.73it/s]
 11%|█         | 229/2129 [00:09<01:35, 19.87it/s]
 11%|█         | 233/2129 [00:09<01:54, 16.56it/s]
 11%|█         | 236/2129 [00:09<02:23, 13.23it/s]
 11%|█         | 239/2129 [00:10<02:59, 10.56it/s]
 11%|█▏        | 242/2129 [00:10<02:29, 12.65it/s]
 12%|█▏        | 246/2129 [00:10<02:09, 14.58it/s]
 12%|█▏        | 248/2129 [00:10<02:13, 14.10it/s]
 12%|█▏        | 250/2129 [00:10<02:39, 11.75it/s]
 12%|█▏        | 252/2129 [00:11<02:48, 11.12it/s]
 12%|█▏        | 255/2129 [00:11<02:13, 14.07it/s]
 12%|█▏        | 258/2129 [00:11<02:23, 13.06it/s]
 12%|█▏        | 261/2129 [00:11<02:21, 13.19it/s]
 12%|█▏        | 264/2129 [00:11<02:02, 15.26it/s]
 13%|█▎        | 267/2129 [00:12<02:07, 14.55it/s]
 13%|█▎        | 269/2129 [00:12<02:02, 15.15it/s]
 13%|█▎        | 275/2129 [00:12<01:55, 16.03it/s]
 13%|█▎        | 277/2129 [00:12<01:53, 16.26it/s]
 13%|█▎        | 281/2129 [00:12<01:31, 20.10it/s]
 13%|█▎        | 284/2129 [00:12<01:29, 20.70it/s]
 13%|█▎        | 287/2129 [00:13<02:00, 15.28it/s]
 14%|█▎        | 290/2129 [00:13<01:48, 16.90it/s]
 14%|█▎        | 292/2129 [00:13<02:38, 11.60it/s]
 14%|█▍        | 294/2129 [00:14<02:53, 10.55it/s]
 14%|█▍        | 297/2129 [00:14<02:20, 13.08it/s]
 14%|█▍        | 303/2129 [00:14<01:26, 21.13it/s]
 14%|█▍        | 306/2129 [00:14<02:21, 12.91it/s]
 15%|█▍        | 309/2129 [00:14<02:03, 14.70it/s]
 15%|█▍        | 312/2129 [00:15<02:13, 13.57it/s]
 15%|█▍        | 314/2129 [00:15<03:07,  9.68it/s]
 15%|█▍        | 316/2129 [00:15<02:50, 10.65it/s]
 15%|█▍        | 318/2129 [00:15<02:38, 11.40it/s]
 15%|█▌        | 324/2129 [00:16<02:10, 13.79it/s]
 15%|█▌        | 327/2129 [00:16<01:53, 15.89it/s]
 15%|█▌        | 329/2129 [00:16<02:07, 14.16it/s]
 16%|█▌        | 331/2129 [00:16<02:00, 14.93it/s]
 16%|█▌        | 334/2129 [00:16<01:49, 16.33it/s]
 16%|█▌        | 336/2129 [00:16<01:46, 16.88it/s]
 16%|█▌        | 338/2129 [00:16<01:49, 16.40it/s]
 16%|█▌        | 341/2129 [00:17<01:32, 19.32it/s]
 16%|█▌        | 344/2129 [00:17<02:18, 12.86it/s]
 16%|█▋        | 346/2129 [00:17<02:28, 12.04it/s]
 16%|█▋        | 349/2129 [00:18<02:52, 10.31it/s]
 16%|█▋        | 351/2129 [00:18<03:25,  8.63it/s]
 17%|█▋        | 353/2129 [00:18<02:59,  9.88it/s]
 17%|█▋        | 355/2129 [00:18<03:38,  8.13it/s]
 17%|█▋        | 357/2129 [00:19<03:48,  7.76it/s]
 17%|█▋        | 358/2129 [00:19<03:41,  7.99it/s]
 17%|█▋        | 361/2129 [00:19<03:07,  9.41it/s]
 17%|█▋        | 363/2129 [00:19<03:07,  9.44it/s]
 17%|█▋        | 367/2129 [00:19<02:04, 14.15it/s]
 18%|█▊        | 373/2129 [00:20<02:01, 14.45it/s]
 18%|█▊        | 375/2129 [00:20<02:02, 14.30it/s]
 18%|█▊        | 377/2129 [00:20<02:38, 11.05it/s]
 18%|█▊        | 380/2129 [00:20<02:31, 11.52it/s]
 18%|█▊        | 383/2129 [00:21<02:05, 13.90it/s]
 18%|█▊        | 385/2129 [00:21<02:14, 12.97it/s]
 18%|█▊        | 387/2129 [00:21<02:10, 13.34it/s]
 18%|█▊        | 390/2129 [00:21<01:52, 15.51it/s]
 18%|█▊        | 392/2129 [00:21<01:55, 15.04it/s]
 19%|█▊        | 394/2129 [00:21<02:21, 12.26it/s]
 19%|█▊        | 396/2129 [00:22<03:30,  8.22it/s]
 19%|█▊        | 398/2129 [00:22<02:58,  9.70it/s]
 19%|█▉        | 401/2129 [00:22<02:18, 12.47it/s]
 19%|█▉        | 403/2129 [00:22<02:10, 13.25it/s]
 19%|█▉        | 405/2129 [00:22<02:12, 13.00it/s]
 19%|█▉        | 408/2129 [00:23<02:05, 13.66it/s]
 19%|█▉        | 411/2129 [00:23<01:44, 16.46it/s]
 20%|█▉        | 418/2129 [00:23<01:02, 27.49it/s]
 20%|█▉        | 422/2129 [00:23<01:26, 19.73it/s]
 20%|██        | 429/2129 [00:23<00:59, 28.54it/s]
 20%|██        | 433/2129 [00:24<02:21, 11.99it/s]
 20%|██        | 436/2129 [00:24<02:35, 10.91it/s]
 21%|██        | 439/2129 [00:25<02:48, 10.03it/s]
 21%|██        | 442/2129 [00:25<02:24, 11.71it/s]
 21%|██        | 451/2129 [00:25<01:20, 20.85it/s]
 21%|██▏       | 455/2129 [00:25<01:27, 19.14it/s]
 22%|██▏       | 458/2129 [00:26<01:43, 16.20it/s]
 22%|██▏       | 461/2129 [00:26<02:21, 11.79it/s]
 22%|██▏       | 464/2129 [00:26<02:00, 13.87it/s]
 22%|██▏       | 467/2129 [00:26<01:58, 13.99it/s]
 22%|██▏       | 469/2129 [00:27<02:15, 12.26it/s]
 22%|██▏       | 471/2129 [00:27<02:30, 11.05it/s]
 22%|██▏       | 474/2129 [00:27<02:05, 13.23it/s]
 22%|██▏       | 477/2129 [00:27<02:03, 13.39it/s]
 22%|██▏       | 479/2129 [00:28<02:23, 11.51it/s]
 23%|██▎       | 482/2129 [00:28<01:54, 14.40it/s]
 23%|██▎       | 484/2129 [00:28<02:42, 10.13it/s]
 23%|██▎       | 487/2129 [00:28<02:55,  9.34it/s]
 23%|██▎       | 490/2129 [00:29<02:42, 10.07it/s]
 23%|██▎       | 493/2129 [00:29<02:09, 12.65it/s]
 23%|██▎       | 499/2129 [00:29<01:20, 20.13it/s]
 24%|██▎       | 502/2129 [00:29<02:02, 13.32it/s]
 24%|██▎       | 505/2129 [00:30<01:57, 13.86it/s]
 24%|██▍       | 508/2129 [00:30<02:30, 10.80it/s]
 24%|██▍       | 510/2129 [00:30<02:40, 10.12it/s]
 24%|██▍       | 512/2129 [00:30<02:53,  9.32it/s]
 24%|██▍       | 514/2129 [00:31<02:38, 10.19it/s]
 24%|██▍       | 516/2129 [00:31<02:49,  9.53it/s]
 24%|██▍       | 518/2129 [00:31<03:15,  8.23it/s]
 24%|██▍       | 520/2129 [00:31<03:11,  8.40it/s]
 24%|██▍       | 521/2129 [00:32<03:18,  8.10it/s]
 25%|██▍       | 523/2129 [00:32<02:43,  9.80it/s]
 25%|██▍       | 526/2129 [00:32<02:38, 10.12it/s]
 25%|██▍       | 528/2129 [00:32<02:45,  9.66it/s]
 25%|██▍       | 530/2129 [00:33<03:20,  7.98it/s]
 25%|██▌       | 533/2129 [00:33<02:29, 10.67it/s]
 25%|██▌       | 535/2129 [00:33<02:31, 10.52it/s]
 25%|██▌       | 537/2129 [00:33<02:46,  9.56it/s]
 25%|██▌       | 541/2129 [00:33<01:51, 14.18it/s]
 26%|██▌       | 543/2129 [00:34<02:20, 11.30it/s]
 26%|██▌       | 546/2129 [00:34<01:55, 13.73it/s]
 26%|██▌       | 548/2129 [00:34<02:10, 12.14it/s]
 26%|██▌       | 551/2129 [00:34<01:43, 15.18it/s]
 26%|██▌       | 557/2129 [00:34<01:40, 15.71it/s]
 26%|██▋       | 559/2129 [00:35<02:05, 12.55it/s]
 26%|██▋       | 562/2129 [00:35<02:31, 10.35it/s]
 26%|██▋       | 564/2129 [00:36<03:34,  7.29it/s]
 27%|██▋       | 566/2129 [00:36<03:03,  8.54it/s]
 27%|██▋       | 568/2129 [00:36<03:07,  8.31it/s]
 27%|██▋       | 571/2129 [00:36<03:03,  8.51it/s]
 27%|██▋       | 574/2129 [00:37<02:30, 10.36it/s]
 27%|██▋       | 577/2129 [00:37<02:29, 10.40it/s]
 27%|██▋       | 579/2129 [00:37<02:18, 11.21it/s]
 27%|██▋       | 581/2129 [00:37<02:39,  9.70it/s]
 27%|██▋       | 583/2129 [00:37<02:23, 10.79it/s]
 27%|██▋       | 585/2129 [00:38<02:51,  9.02it/s]
 28%|██▊       | 587/2129 [00:38<02:34,  9.98it/s]
 28%|██▊       | 589/2129 [00:38<02:44,  9.37it/s]
 28%|██▊       | 591/2129 [00:38<02:45,  9.28it/s]
 28%|██▊       | 593/2129 [00:38<02:38,  9.69it/s]
 28%|██▊       | 595/2129 [00:39<02:20, 10.92it/s]
 28%|██▊       | 599/2129 [00:39<01:36, 15.83it/s]
 28%|██▊       | 601/2129 [00:39<01:32, 16.52it/s]
 28%|██▊       | 603/2129 [00:39<01:42, 14.95it/s]
 28%|██▊       | 605/2129 [00:39<02:00, 12.61it/s]
 29%|██▊       | 607/2129 [00:39<01:51, 13.64it/s]
 29%|██▊       | 610/2129 [00:40<02:09, 11.70it/s]
 29%|██▊       | 612/2129 [00:40<02:24, 10.49it/s]
 29%|██▉       | 614/2129 [00:40<03:29,  7.21it/s]
 29%|██▉       | 616/2129 [00:40<02:53,  8.72it/s]
 29%|██▉       | 618/2129 [00:41<02:30, 10.05it/s]
 29%|██▉       | 624/2129 [00:41<01:21, 18.54it/s]
 29%|██▉       | 627/2129 [00:41<01:27, 17.14it/s]
 30%|██▉       | 630/2129 [00:41<01:31, 16.38it/s]
 30%|██▉       | 633/2129 [00:41<01:49, 13.61it/s]
 30%|██▉       | 635/2129 [00:42<01:48, 13.77it/s]
 30%|██▉       | 637/2129 [00:42<02:13, 11.20it/s]
 30%|███       | 641/2129 [00:42<02:01, 12.25it/s]
 30%|███       | 644/2129 [00:42<02:12, 11.22it/s]
 30%|███       | 646/2129 [00:43<02:26, 10.11it/s]
 30%|███       | 648/2129 [00:43<02:14, 11.02it/s]
 31%|███       | 650/2129 [00:43<02:24, 10.22it/s]
 31%|███       | 652/2129 [00:43<02:11, 11.21it/s]
 31%|███       | 654/2129 [00:44<02:33,  9.61it/s]
 31%|███       | 657/2129 [00:44<01:57, 12.56it/s]
 31%|███       | 659/2129 [00:44<01:57, 12.48it/s]
 31%|███       | 661/2129 [00:44<02:21, 10.38it/s]
 31%|███       | 663/2129 [00:44<02:56,  8.29it/s]
 31%|███▏      | 666/2129 [00:45<02:11, 11.10it/s]
 31%|███▏      | 668/2129 [00:45<02:12, 11.05it/s]
 32%|███▏      | 672/2129 [00:45<01:59, 12.23it/s]
 32%|███▏      | 674/2129 [00:46<03:15,  7.44it/s]
 32%|███▏      | 677/2129 [00:46<02:57,  8.20it/s]
 32%|███▏      | 680/2129 [00:46<02:18, 10.48it/s]
 32%|███▏      | 683/2129 [00:46<02:08, 11.24it/s]
 32%|███▏      | 685/2129 [00:47<02:35,  9.29it/s]
 32%|███▏      | 687/2129 [00:47<02:53,  8.31it/s]
 32%|███▏      | 689/2129 [00:47<02:41,  8.93it/s]
 33%|███▎      | 692/2129 [00:47<02:06, 11.35it/s]
 33%|███▎      | 694/2129 [00:47<02:16, 10.55it/s]
 33%|███▎      | 696/2129 [00:48<02:32,  9.40it/s]
 33%|███▎      | 699/2129 [00:48<01:58, 12.11it/s]
 33%|███▎      | 702/2129 [00:48<01:35, 15.01it/s]
 33%|███▎      | 704/2129 [00:48<02:25,  9.80it/s]
 33%|███▎      | 706/2129 [00:49<02:16, 10.41it/s]
 33%|███▎      | 708/2129 [00:49<02:36,  9.09it/s]
 33%|███▎      | 710/2129 [00:49<03:11,  7.42it/s]
 33%|███▎      | 712/2129 [00:49<03:02,  7.75it/s]
 33%|███▎      | 713/2129 [00:50<03:23,  6.95it/s]
 34%|███▎      | 716/2129 [00:50<02:23,  9.83it/s]
 34%|███▍      | 719/2129 [00:50<02:28,  9.51it/s]
 34%|███▍      | 721/2129 [00:51<02:53,  8.09it/s]
 34%|███▍      | 723/2129 [00:51<03:08,  7.47it/s]
 34%|███▍      | 724/2129 [00:51<03:48,  6.16it/s]
 34%|███▍      | 725/2129 [00:51<03:55,  5.97it/s]
 34%|███▍      | 726/2129 [00:52<04:03,  5.77it/s]
 34%|███▍      | 727/2129 [00:52<04:15,  5.50it/s]
 34%|███▍      | 728/2129 [00:52<04:53,  4.78it/s]
 34%|███▍      | 731/2129 [00:52<02:48,  8.31it/s]
 34%|███▍      | 733/2129 [00:52<03:08,  7.40it/s]
 35%|███▍      | 736/2129 [00:53<02:13, 10.45it/s]
 35%|███▍      | 738/2129 [00:53<02:42,  8.55it/s]
 35%|███▍      | 740/2129 [00:53<02:48,  8.23it/s]
 35%|███▍      | 744/2129 [00:53<01:48, 12.72it/s]
 35%|███▌      | 750/2129 [00:53<01:06, 20.68it/s]
 35%|███▌      | 754/2129 [00:54<02:29,  9.19it/s]
 36%|███▌      | 757/2129 [00:55<02:37,  8.68it/s]
 36%|███▌      | 759/2129 [00:55<02:58,  7.70it/s]
 36%|███▌      | 761/2129 [00:55<02:36,  8.77it/s]
 36%|███▌      | 763/2129 [00:56<03:04,  7.40it/s]
 36%|███▌      | 765/2129 [00:56<02:40,  8.50it/s]
 36%|███▌      | 767/2129 [00:56<03:52,  5.85it/s]
 36%|███▌      | 769/2129 [00:57<03:20,  6.77it/s]
 36%|███▌      | 771/2129 [00:57<02:44,  8.25it/s]
 36%|███▋      | 773/2129 [00:57<02:16,  9.90it/s]
 36%|███▋      | 775/2129 [00:57<02:35,  8.72it/s]
 36%|███▋      | 777/2129 [00:57<02:27,  9.18it/s]
 37%|███▋      | 779/2129 [00:57<02:14, 10.07it/s]
 37%|███▋      | 781/2129 [00:58<02:22,  9.47it/s]
 37%|███▋      | 783/2129 [00:58<02:28,  9.06it/s]
 37%|███▋      | 785/2129 [00:58<02:48,  7.96it/s]
 37%|███▋      | 787/2129 [00:59<02:46,  8.05it/s]
 37%|███▋      | 790/2129 [00:59<02:10, 10.25it/s]
 37%|███▋      | 794/2129 [00:59<01:32, 14.45it/s]
 37%|███▋      | 796/2129 [00:59<02:28,  8.95it/s]
 37%|███▋      | 798/2129 [01:00<02:54,  7.62it/s]
 38%|███▊      | 800/2129 [01:00<02:50,  7.78it/s]
 38%|███▊      | 802/2129 [01:00<02:51,  7.74it/s]
 38%|███▊      | 804/2129 [01:00<02:24,  9.18it/s]
 38%|███▊      | 809/2129 [01:01<02:03, 10.73it/s]
 38%|███▊      | 811/2129 [01:01<02:14,  9.77it/s]
 38%|███▊      | 813/2129 [01:01<02:19,  9.41it/s]
 38%|███▊      | 816/2129 [01:01<01:48, 12.15it/s]
 38%|███▊      | 818/2129 [01:02<02:11,  9.93it/s]
 39%|███▊      | 820/2129 [01:02<02:41,  8.10it/s]
 39%|███▊      | 822/2129 [01:02<02:17,  9.50it/s]
 39%|███▉      | 827/2129 [01:02<01:46, 12.18it/s]
 39%|███▉      | 829/2129 [01:02<01:39, 13.12it/s]
 39%|███▉      | 836/2129 [01:03<00:56, 22.76it/s]
 39%|███▉      | 840/2129 [01:03<01:17, 16.66it/s]
 40%|███▉      | 843/2129 [01:03<01:35, 13.48it/s]
 40%|███▉      | 846/2129 [01:04<02:15,  9.46it/s]
 40%|███▉      | 848/2129 [01:04<02:33,  8.37it/s]
 40%|███▉      | 850/2129 [01:04<02:14,  9.53it/s]
 40%|████      | 852/2129 [01:05<02:18,  9.19it/s]
 40%|████      | 854/2129 [01:05<02:29,  8.54it/s]
 40%|████      | 856/2129 [01:05<02:37,  8.10it/s]
 40%|████      | 860/2129 [01:05<02:05, 10.14it/s]
 40%|████      | 862/2129 [01:06<02:13,  9.50it/s]
 41%|████      | 864/2129 [01:06<02:39,  7.94it/s]
 41%|████      | 865/2129 [01:06<03:15,  6.47it/s]
 41%|████      | 866/2129 [01:07<03:51,  5.46it/s]
 41%|████      | 869/2129 [01:07<02:33,  8.21it/s]
 41%|████      | 873/2129 [01:07<02:13,  9.38it/s]
 41%|████      | 876/2129 [01:07<01:48, 11.53it/s]
 41%|████▏     | 879/2129 [01:07<01:28, 14.10it/s]
 41%|████▏     | 881/2129 [01:08<01:48, 11.54it/s]
 41%|████▏     | 883/2129 [01:08<01:46, 11.66it/s]
 42%|████▏     | 885/2129 [01:08<01:35, 12.97it/s]
 42%|████▏     | 887/2129 [01:08<02:16,  9.09it/s]
 42%|████▏     | 890/2129 [01:09<01:46, 11.59it/s]
 42%|████▏     | 892/2129 [01:09<01:51, 11.13it/s]
 42%|████▏     | 894/2129 [01:09<01:59, 10.37it/s]
 42%|████▏     | 896/2129 [01:09<02:21,  8.69it/s]
 42%|████▏     | 898/2129 [01:09<02:05,  9.78it/s]
 42%|████▏     | 900/2129 [01:10<01:57, 10.50it/s]
 42%|████▏     | 902/2129 [01:10<02:22,  8.60it/s]
 42%|████▏     | 904/2129 [01:10<02:22,  8.60it/s]
 43%|████▎     | 906/2129 [01:10<02:11,  9.34it/s]
 43%|████▎     | 908/2129 [01:11<02:40,  7.62it/s]
 43%|████▎     | 911/2129 [01:11<02:16,  8.95it/s]
 43%|████▎     | 913/2129 [01:11<01:56, 10.41it/s]
 43%|████▎     | 915/2129 [01:11<02:10,  9.33it/s]
 43%|████▎     | 917/2129 [01:11<01:52, 10.80it/s]
 43%|████▎     | 920/2129 [01:12<01:29, 13.45it/s]
 43%|████▎     | 926/2129 [01:12<01:19, 15.04it/s]
 44%|████▎     | 928/2129 [01:12<01:27, 13.79it/s]
 44%|████▎     | 930/2129 [01:12<01:40, 11.88it/s]
 44%|████▍     | 932/2129 [01:13<01:58, 10.13it/s]
 44%|████▍     | 934/2129 [01:13<01:49, 10.93it/s]
 44%|████▍     | 936/2129 [01:13<02:40,  7.41it/s]
 44%|████▍     | 937/2129 [01:13<02:41,  7.40it/s]
 44%|████▍     | 938/2129 [01:14<02:46,  7.14it/s]
 44%|████▍     | 939/2129 [01:14<02:40,  7.42it/s]
 44%|████▍     | 941/2129 [01:14<02:04,  9.52it/s]
 44%|████▍     | 944/2129 [01:14<01:40, 11.83it/s]
 44%|████▍     | 946/2129 [01:14<02:06,  9.37it/s]
 45%|████▍     | 948/2129 [01:14<01:56, 10.14it/s]
 45%|████▍     | 950/2129 [01:15<01:58,  9.98it/s]
 45%|████▍     | 952/2129 [01:15<02:36,  7.52it/s]
 45%|████▍     | 954/2129 [01:15<02:16,  8.61it/s]
 45%|████▍     | 956/2129 [01:16<02:24,  8.09it/s]
 45%|████▍     | 958/2129 [01:16<02:21,  8.27it/s]
 45%|████▌     | 960/2129 [01:16<02:40,  7.27it/s]
 45%|████▌     | 961/2129 [01:16<02:39,  7.31it/s]
 45%|████▌     | 963/2129 [01:16<02:33,  7.61it/s]
 45%|████▌     | 966/2129 [01:17<01:51, 10.46it/s]
 45%|████▌     | 968/2129 [01:17<02:10,  8.89it/s]
 46%|████▌     | 970/2129 [01:17<02:20,  8.25it/s]
 46%|████▌     | 971/2129 [01:17<02:30,  7.70it/s]
 46%|████▌     | 973/2129 [01:18<02:10,  8.85it/s]
 46%|████▌     | 974/2129 [01:18<02:28,  7.78it/s]
 46%|████▌     | 977/2129 [01:18<01:59,  9.68it/s]
 46%|████▌     | 980/2129 [01:18<01:31, 12.59it/s]
 46%|████▌     | 982/2129 [01:18<01:29, 12.85it/s]
 46%|████▌     | 984/2129 [01:19<01:56,  9.79it/s]
 46%|████▋     | 986/2129 [01:19<01:44, 10.97it/s]
 46%|████▋     | 988/2129 [01:19<01:49, 10.40it/s]
 47%|████▋     | 990/2129 [01:19<01:34, 12.05it/s]
 47%|████▋     | 993/2129 [01:19<01:54,  9.89it/s]
 47%|████▋     | 995/2129 [01:20<01:39, 11.42it/s]
 47%|████▋     | 1001/2129 [01:20<01:28, 12.71it/s]
 47%|████▋     | 1003/2129 [01:20<01:45, 10.63it/s]
 47%|████▋     | 1006/2129 [01:21<01:47, 10.42it/s]
 47%|████▋     | 1008/2129 [01:21<02:06,  8.89it/s]
 47%|████▋     | 1010/2129 [01:21<02:09,  8.64it/s]
 48%|████▊     | 1012/2129 [01:21<02:22,  7.84it/s]
 48%|████▊     | 1013/2129 [01:22<02:34,  7.21it/s]
 48%|████▊     | 1015/2129 [01:22<02:22,  7.85it/s]
 48%|████▊     | 1016/2129 [01:22<02:22,  7.78it/s]
 48%|████▊     | 1018/2129 [01:22<01:53,  9.76it/s]
 48%|████▊     | 1020/2129 [01:22<02:02,  9.07it/s]
 48%|████▊     | 1022/2129 [01:23<02:13,  8.29it/s]
 48%|████▊     | 1023/2129 [01:23<02:30,  7.35it/s]
 48%|████▊     | 1024/2129 [01:23<02:56,  6.25it/s]
 48%|████▊     | 1025/2129 [01:23<02:45,  6.69it/s]
 48%|████▊     | 1027/2129 [01:23<02:03,  8.91it/s]
 48%|████▊     | 1029/2129 [01:24<02:21,  7.79it/s]
 48%|████▊     | 1030/2129 [01:24<02:52,  6.36it/s]
 48%|████▊     | 1032/2129 [01:24<02:49,  6.49it/s]
 49%|████▊     | 1034/2129 [01:24<02:14,  8.13it/s]
 49%|████▉     | 1038/2129 [01:24<01:25, 12.73it/s]
 49%|████▉     | 1040/2129 [01:25<01:48, 10.07it/s]
 49%|████▉     | 1042/2129 [01:25<01:51,  9.75it/s]
 49%|████▉     | 1044/2129 [01:25<01:45, 10.31it/s]
 49%|████▉     | 1047/2129 [01:25<01:20, 13.46it/s]
 49%|████▉     | 1049/2129 [01:25<01:30, 11.97it/s]
 49%|████▉     | 1051/2129 [01:26<01:54,  9.42it/s]
 49%|████▉     | 1053/2129 [01:26<01:37, 11.00it/s]
 50%|████▉     | 1055/2129 [01:26<01:38, 10.95it/s]
 50%|████▉     | 1057/2129 [01:27<02:31,  7.07it/s]
 50%|████▉     | 1059/2129 [01:27<02:20,  7.60it/s]
 50%|████▉     | 1060/2129 [01:27<02:34,  6.90it/s]
 50%|████▉     | 1062/2129 [01:27<02:08,  8.28it/s]
 50%|████▉     | 1064/2129 [01:27<02:00,  8.85it/s]
 50%|█████     | 1067/2129 [01:28<01:33, 11.36it/s]
 50%|█████     | 1069/2129 [01:28<01:44, 10.17it/s]
 50%|█████     | 1071/2129 [01:28<02:04,  8.50it/s]
 50%|█████     | 1073/2129 [01:28<02:22,  7.43it/s]
 51%|█████     | 1076/2129 [01:29<01:48,  9.69it/s]
 51%|█████     | 1078/2129 [01:29<01:55,  9.13it/s]
 51%|█████     | 1080/2129 [01:29<01:48,  9.71it/s]
 51%|█████     | 1083/2129 [01:29<01:26, 12.14it/s]
 51%|█████     | 1085/2129 [01:30<01:45,  9.88it/s]
 51%|█████     | 1087/2129 [01:30<01:33, 11.12it/s]
 51%|█████     | 1091/2129 [01:30<01:19, 13.10it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 346.44it/s]
 84%|████████▎ | 251/300 [14:56<48:16, 59.12s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 5], [np.int64(2), False, 1], [np.int64(3), False, 9], [np.int64(4), False, 5], [np.int64(6), False, 8], [np.int64(7), False, 2], [np.int64(8), False, 11], [np.int64(9), False, 1], [np.int64(10), False, 8], [np.int64(12), False, 8], [np.int64(13), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3045, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [14:57<33:08, 41.43s/it]

tensor(11.7141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4567, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7382, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7253, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [14:57<10:43, 14.29s/it]

tensor(11.7675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8252, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0003, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [14:57<07:21, 10.04s/it]

tensor(11.7873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1209, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2466, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [14:57<03:29,  4.98s/it]

tensor(11.7626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2757, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [14:57<01:40,  2.50s/it]

tensor(11.7372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2733, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2589, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [14:58<00:48,  1.29s/it]

tensor(11.7431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2795, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7481, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3000, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [14:58<00:24,  1.44it/s]

tensor(11.7474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3317, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3595, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [14:58<00:13,  2.49it/s]

tensor(11.7438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3707, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [14:58<00:08,  3.86it/s]

tensor(11.7391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3540, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3415, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [14:59<00:05,  5.30it/s]

tensor(11.7307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3361, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3388, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [14:59<00:04,  6.47it/s]

tensor(11.7234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3476, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3342, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [14:59<00:03,  7.23it/s]

tensor(11.7138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3409, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3515, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [15:00<00:02,  7.85it/s]

tensor(11.7078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3779, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3997, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [15:00<00:02,  8.06it/s]

tensor(11.7059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4105, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [15:00<00:02,  8.15it/s]

tensor(11.7027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1831, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7002, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2106, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [15:00<00:02,  8.16it/s]

tensor(11.6975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2572, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6949, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3054, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [15:00<00:01,  8.19it/s]

tensor(11.6924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3896, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [15:01<00:01,  8.22it/s]

tensor(11.6873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4103, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4163, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [15:01<00:01,  8.22it/s]

tensor(11.6840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4090, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4054, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [15:01<00:01,  8.19it/s]

tensor(11.6818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4161, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4307, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [15:02<00:00,  8.21it/s]

tensor(11.6792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4767, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [15:02<00:00,  8.09it/s]

tensor(11.6770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4898, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4997, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [15:02<00:00,  8.24it/s]

tensor(11.6757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4996, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5144, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [15:02<00:00,  8.24it/s]

tensor(11.6748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5169, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5335, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [15:02<00:00,  3.01s/it]

tensor(11.6722, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5389, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0020232200622558594
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 5
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.580906294753
NMI         : 0.601505089225
Runtime     : 946.88 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed5

==============================================================================================================
PRAGA RUN | E18.5 | seed=6
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 2.920e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:31,  9.51it/s]

tensor(15.6342, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4816, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6280, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2290, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:30,  9.58it/s]

tensor(15.6176, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1977, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6009, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3669, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 5/300 [00:00<00:30,  9.69it/s]

tensor(15.5814, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7156, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5636, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2273, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5526, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8843, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:29,  9.89it/s]

tensor(15.5450, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6745, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5385, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5838, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:29,  9.90it/s]

tensor(15.5288, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5999, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5164, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7134, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:29,  9.88it/s]

tensor(15.5135, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9149, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5048, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1945, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:28,  9.87it/s]

tensor(15.4974, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5461, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4873, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9613, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4746, device='cuda:0', grad_fn=<AddBackward0>)

  6%|▌         | 17/300 [00:01<00:29,  9.68it/s]

tensor(4.4344, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4633, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9606, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.86it/s]

tensor(15.4434, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5323, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4247, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1486, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:28,  9.70it/s]

tensor(15.4091, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8017, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3925, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4905, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:28,  9.87it/s]

tensor(15.3733, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2098, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3499, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9578, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3259, device='cuda:0', grad_fn=<AddBackward0>)

  8%|▊         | 25/300 [00:02<00:28,  9.77it/s]

tensor(1.7311, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3025, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5274, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:27,  9.89it/s]

tensor(15.2790, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3441, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2493, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1801, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:27,  9.86it/s]

tensor(15.2214, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9006, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1563, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7822, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 31/300 [00:03<00:27,  9.81it/s]

tensor(15.1210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6766, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5819, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:27,  9.85it/s]

tensor(15.0465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4973, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4223, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:26,  9.88it/s]

tensor(14.9656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3557, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2967, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.90it/s]

tensor(14.8813, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2438, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1988, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:04<00:26,  9.84it/s]

tensor(14.7944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1585, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1238, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:26,  9.85it/s]

tensor(14.6976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0947, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0711, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:25,  9.86it/s]

tensor(14.5910, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0533, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0420, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:25,  9.86it/s]

tensor(14.4724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4094, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 47/300 [00:04<00:26,  9.70it/s]

tensor(14.3451, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:25,  9.83it/s]

tensor(14.2117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.73it/s]

tensor(14.0840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:25,  9.76it/s]

tensor(13.9791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:25,  9.64it/s]

tensor(13.9025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:25,  9.67it/s]

tensor(13.8381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8058, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:06<00:24,  9.71it/s]

tensor(13.7699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.53it/s]

tensor(13.6977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:24,  9.52it/s]

tensor(13.6346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:24,  9.46it/s]

tensor(13.5855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:24,  9.65it/s]

tensor(13.5428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:24,  9.50it/s]

tensor(13.4986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:07<00:23,  9.58it/s]

tensor(13.4502, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:23,  9.74it/s]

tensor(13.4004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3509, device='cuda:0', grad_fn=<AddBackward0>)

 25%|██▌       | 76/300 [00:07<00:22,  9.92it/s]

tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3051, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:23,  9.56it/s]

tensor(13.2828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:08<00:23,  9.49it/s]

tensor(13.2389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:22,  9.56it/s]

tensor(13.1950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:22,  9.66it/s]

tensor(13.1524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:22,  9.52it/s]

tensor(13.1115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0917, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:09<00:22,  9.51it/s]

tensor(13.0718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:09<00:21,  9.65it/s]

tensor(13.0337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0148, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:21,  9.48it/s]

tensor(12.9955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:21,  9.47it/s]

tensor(12.9582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:21,  9.49it/s]

tensor(12.9211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:10<00:21,  9.45it/s]

tensor(12.8858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.30it/s]

tensor(12.8516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([207, 223, 318, 254,  76, 113, 128,  72,  84, 189,  42, 237, 116,  70])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 4/2129 [00:00<01:01, 34.54it/s]
  1%|          | 11/2129 [00:00<00:40, 52.75it/s]
  1%|          | 18/2129 [00:00<00:38, 55.41it/s]
  1%|          | 25/2129 [00:00<00:35, 59.17it/s]
  1%|▏         | 31/2129 [00:00<00:45, 45.70it/s]
  2%|▏         | 37/2129 [00:00<00:44, 47.35it/s]
  2%|▏         | 43/2129 [00:00<00:50, 41.01it/s]
  2%|▏         | 51/2129 [00:01<00:41, 50.17it/s]
  3%|▎         | 59/2129 [00:01<00:40, 50.88it/s]
  3%|▎         | 65/2129 [00:01<00:49, 41.40it/s]
  3%|▎         | 70/2129 [00:01<00:47, 43.20it/s]
  4%|▎         | 75/2129 [00:01<00:49, 41.61it/s]
  4%|▍         | 81/2129 [00:01<00:47, 43.00it/s]
  4%|▍         | 86/2129 [00:01<00:51, 39.85it/s]
  4%|▍         | 91/2129 [00:02<00:52, 38.95it/s]
  5%|▍         | 97/2129 [00:02<00:47, 42.95it/s]
  5%|▍         | 102/2129 [00:02<01:15, 26.91it/s]
  5%|▍         | 106/2129 [00:02<01:34, 21.33it/s]
  5%|▌         | 109/2129 [00:02<01:33, 21.56it/s]
  5%|▌         | 112/2129 [00:03<01:29, 22.61it/s]
  5%|▌         | 115/2129 [00:03<01:46, 19.00it/s]
  6%|▌         | 120/2129 [00:03<01:22, 24.43it/s]
  6%|▌         | 125/2129 [00:03<01:09, 28.89it/s]
  6%|▌         | 129/2129 [00:03<01:13, 27.04it/s]
  6%|▌         | 133/2129 [00:03<01:32, 21.51it/s]
  6%|▋         | 136/2129 [00:04<01:38, 20.24it/s]
  7%|▋         | 143/2129 [00:04<01:07, 29.22it/s]
  7%|▋         | 150/2129 [00:04<00:54, 36.05it/s]
  7%|▋         | 155/2129 [00:04<01:05, 30.23it/s]
  7%|▋         | 159/2129 [00:04<01:29, 21.98it/s]
  8%|▊         | 163/2129 [00:05<01:22, 23.81it/s]
  8%|▊         | 166/2129 [00:05<01:32, 21.31it/s]
  8%|▊         | 169/2129 [00:05<01:39, 19.66it/s]
  8%|▊         | 173/2129 [00:05<01:27, 22.47it/s]
  8%|▊         | 177/2129 [00:05<01:15, 25.92it/s]
  9%|▊         | 181/2129 [00:05<01:07, 28.80it/s]
  9%|▊         | 185/2129 [00:06<01:57, 16.50it/s]
  9%|▉         | 188/2129 [00:06<02:00, 16.08it/s]
  9%|▉         | 191/2129 [00:06<02:21, 13.71it/s]
  9%|▉         | 194/2129 [00:06<02:01, 15.93it/s]
  9%|▉         | 200/2129 [00:07<01:46, 18.16it/s]
 10%|▉         | 203/2129 [00:07<02:05, 15.37it/s]
 10%|▉         | 207/2129 [00:07<01:41, 18.85it/s]
 10%|▉         | 212/2129 [00:07<01:35, 20.07it/s]
 10%|█         | 215/2129 [00:07<01:37, 19.66it/s]
 10%|█         | 218/2129 [00:08<01:35, 20.05it/s]
 10%|█         | 223/2129 [00:08<01:15, 25.23it/s]
 11%|█         | 226/2129 [00:08<01:17, 24.61it/s]
 11%|█         | 229/2129 [00:08<01:16, 24.88it/s]
 11%|█         | 233/2129 [00:08<01:28, 21.52it/s]
 11%|█         | 236/2129 [00:09<01:57, 16.04it/s]
 11%|█         | 239/2129 [00:09<01:55, 16.41it/s]
 11%|█▏        | 243/2129 [00:09<02:01, 15.50it/s]
 12%|█▏        | 246/2129 [00:09<01:47, 17.53it/s]
 12%|█▏        | 249/2129 [00:09<02:04, 15.16it/s]
 12%|█▏        | 252/2129 [00:10<02:16, 13.80it/s]
 12%|█▏        | 254/2129 [00:10<02:11, 14.23it/s]
 12%|█▏        | 258/2129 [00:10<02:00, 15.50it/s]
 12%|█▏        | 261/2129 [00:10<02:22, 13.08it/s]
 12%|█▏        | 264/2129 [00:10<02:02, 15.16it/s]
 13%|█▎        | 268/2129 [00:11<01:36, 19.28it/s]
 13%|█▎        | 271/2129 [00:11<01:59, 15.55it/s]
 13%|█▎        | 277/2129 [00:11<01:21, 22.86it/s]
 13%|█▎        | 283/2129 [00:11<01:02, 29.75it/s]
 13%|█▎        | 287/2129 [00:11<01:14, 24.79it/s]
 14%|█▎        | 291/2129 [00:11<01:11, 25.57it/s]
 14%|█▍        | 295/2129 [00:12<01:56, 15.72it/s]
 14%|█▍        | 298/2129 [00:12<01:54, 16.02it/s]
 14%|█▍        | 302/2129 [00:12<01:34, 19.38it/s]
 14%|█▍        | 305/2129 [00:12<01:49, 16.59it/s]
 14%|█▍        | 308/2129 [00:13<01:44, 17.50it/s]
 15%|█▍        | 311/2129 [00:13<01:32, 19.72it/s]
 15%|█▍        | 314/2129 [00:13<01:53, 15.98it/s]
 15%|█▍        | 317/2129 [00:13<01:55, 15.67it/s]
 15%|█▍        | 319/2129 [00:13<01:50, 16.43it/s]
 15%|█▌        | 321/2129 [00:14<02:27, 12.23it/s]
 15%|█▌        | 324/2129 [00:14<02:34, 11.71it/s]
 15%|█▌        | 327/2129 [00:14<02:18, 12.98it/s]
 15%|█▌        | 329/2129 [00:14<02:12, 13.63it/s]
 16%|█▌        | 331/2129 [00:14<02:52, 10.41it/s]
 16%|█▌        | 333/2129 [00:15<02:30, 11.90it/s]
 16%|█▌        | 335/2129 [00:15<02:18, 12.96it/s]
 16%|█▌        | 337/2129 [00:15<02:11, 13.63it/s]
 16%|█▌        | 340/2129 [00:15<01:59, 15.02it/s]
 16%|█▌        | 342/2129 [00:15<02:41, 11.09it/s]
 16%|█▌        | 344/2129 [00:15<02:47, 10.69it/s]
 16%|█▋        | 346/2129 [00:16<02:54, 10.23it/s]
 16%|█▋        | 349/2129 [00:16<03:01,  9.82it/s]
 16%|█▋        | 351/2129 [00:16<03:08,  9.44it/s]
 17%|█▋        | 354/2129 [00:16<02:42, 10.94it/s]
 17%|█▋        | 356/2129 [00:17<02:42, 10.89it/s]
 17%|█▋        | 358/2129 [00:17<02:45, 10.73it/s]
 17%|█▋        | 360/2129 [00:17<02:28, 11.93it/s]
 17%|█▋        | 362/2129 [00:17<02:57,  9.95it/s]
 17%|█▋        | 364/2129 [00:17<02:42, 10.83it/s]
 17%|█▋        | 368/2129 [00:18<01:49, 16.09it/s]
 17%|█▋        | 371/2129 [00:18<01:36, 18.14it/s]
 18%|█▊        | 374/2129 [00:18<02:10, 13.47it/s]
 18%|█▊        | 376/2129 [00:18<02:00, 14.49it/s]
 18%|█▊        | 379/2129 [00:18<01:41, 17.32it/s]
 18%|█▊        | 382/2129 [00:19<02:11, 13.27it/s]
 18%|█▊        | 384/2129 [00:19<02:20, 12.46it/s]
 18%|█▊        | 386/2129 [00:19<02:38, 11.00it/s]
 18%|█▊        | 388/2129 [00:19<02:20, 12.42it/s]
 18%|█▊        | 392/2129 [00:19<01:45, 16.46it/s]
 19%|█▊        | 394/2129 [00:20<02:40, 10.84it/s]
 19%|█▊        | 396/2129 [00:20<02:33, 11.32it/s]
 19%|█▉        | 400/2129 [00:20<02:20, 12.33it/s]
 19%|█▉        | 402/2129 [00:20<02:09, 13.36it/s]
 19%|█▉        | 404/2129 [00:20<02:13, 12.90it/s]
 19%|█▉        | 406/2129 [00:20<02:04, 13.89it/s]
 19%|█▉        | 408/2129 [00:21<02:22, 12.05it/s]
 19%|█▉        | 410/2129 [00:21<02:07, 13.51it/s]
 19%|█▉        | 415/2129 [00:21<01:20, 21.19it/s]
 20%|█▉        | 418/2129 [00:21<01:13, 23.16it/s]
 20%|█▉        | 421/2129 [00:21<01:21, 20.90it/s]
 20%|██        | 427/2129 [00:21<00:59, 28.82it/s]
 20%|██        | 432/2129 [00:21<00:56, 29.91it/s]
 20%|██        | 436/2129 [00:22<01:20, 21.13it/s]
 21%|██        | 439/2129 [00:22<01:32, 18.20it/s]
 21%|██        | 442/2129 [00:22<01:25, 19.77it/s]
 21%|██        | 446/2129 [00:22<01:16, 21.93it/s]
 21%|██        | 449/2129 [00:22<01:11, 23.36it/s]
 21%|██        | 452/2129 [00:22<01:14, 22.39it/s]
 21%|██▏       | 455/2129 [00:23<01:39, 16.74it/s]
 22%|██▏       | 458/2129 [00:23<02:04, 13.41it/s]
 22%|██▏       | 461/2129 [00:23<01:46, 15.60it/s]
 22%|██▏       | 466/2129 [00:24<01:46, 15.55it/s]
 22%|██▏       | 468/2129 [00:24<01:56, 14.21it/s]
 22%|██▏       | 471/2129 [00:24<02:03, 13.44it/s]
 22%|██▏       | 473/2129 [00:24<02:14, 12.33it/s]
 22%|██▏       | 476/2129 [00:24<01:49, 15.08it/s]
 22%|██▏       | 478/2129 [00:25<02:37, 10.48it/s]
 23%|██▎       | 480/2129 [00:25<02:23, 11.46it/s]
 23%|██▎       | 482/2129 [00:25<02:08, 12.81it/s]
 23%|██▎       | 484/2129 [00:25<02:06, 13.02it/s]
 23%|██▎       | 488/2129 [00:25<01:33, 17.56it/s]
 23%|██▎       | 491/2129 [00:25<01:23, 19.61it/s]
 23%|██▎       | 494/2129 [00:25<01:28, 18.40it/s]
 23%|██▎       | 497/2129 [00:26<01:47, 15.22it/s]
 23%|██▎       | 500/2129 [00:26<01:31, 17.74it/s]
 24%|██▎       | 503/2129 [00:26<01:44, 15.63it/s]
 24%|██▍       | 506/2129 [00:26<01:31, 17.73it/s]
 24%|██▍       | 509/2129 [00:26<01:44, 15.47it/s]
 24%|██▍       | 511/2129 [00:27<01:42, 15.77it/s]
 24%|██▍       | 515/2129 [00:27<01:26, 18.68it/s]
 24%|██▍       | 518/2129 [00:27<01:38, 16.34it/s]
 24%|██▍       | 520/2129 [00:27<01:40, 16.07it/s]
 25%|██▍       | 522/2129 [00:27<02:17, 11.67it/s]
 25%|██▍       | 524/2129 [00:28<02:12, 12.07it/s]
 25%|██▍       | 526/2129 [00:28<02:21, 11.32it/s]
 25%|██▍       | 528/2129 [00:28<02:12, 12.05it/s]
 25%|██▍       | 530/2129 [00:28<02:57,  8.99it/s]
 25%|██▍       | 532/2129 [00:28<02:30, 10.58it/s]
 25%|██▌       | 535/2129 [00:29<02:42,  9.79it/s]
 25%|██▌       | 537/2129 [00:29<02:21, 11.26it/s]
 25%|██▌       | 541/2129 [00:29<01:45, 15.08it/s]
 26%|██▌       | 543/2129 [00:29<01:54, 13.90it/s]
 26%|██▌       | 545/2129 [00:29<01:46, 14.84it/s]
 26%|██▌       | 547/2129 [00:29<01:42, 15.43it/s]
 26%|██▌       | 549/2129 [00:30<01:37, 16.21it/s]
 26%|██▌       | 554/2129 [00:30<01:07, 23.29it/s]
 26%|██▌       | 557/2129 [00:30<01:15, 20.72it/s]
 26%|██▋       | 560/2129 [00:30<01:14, 21.13it/s]
 26%|██▋       | 563/2129 [00:30<01:35, 16.37it/s]
 27%|██▋       | 565/2129 [00:30<01:38, 15.80it/s]
 27%|██▋       | 567/2129 [00:31<02:00, 12.91it/s]
 27%|██▋       | 569/2129 [00:31<01:54, 13.63it/s]
 27%|██▋       | 571/2129 [00:31<01:57, 13.22it/s]
 27%|██▋       | 574/2129 [00:31<01:42, 15.20it/s]
 27%|██▋       | 577/2129 [00:31<01:31, 16.88it/s]
 27%|██▋       | 579/2129 [00:31<01:31, 16.88it/s]
 27%|██▋       | 581/2129 [00:31<01:46, 14.60it/s]
 27%|██▋       | 583/2129 [00:32<01:56, 13.24it/s]
 28%|██▊       | 586/2129 [00:32<01:54, 13.52it/s]
 28%|██▊       | 588/2129 [00:32<01:52, 13.75it/s]
 28%|██▊       | 590/2129 [00:32<02:21, 10.91it/s]
 28%|██▊       | 593/2129 [00:33<02:16, 11.27it/s]
 28%|██▊       | 596/2129 [00:33<01:51, 13.70it/s]
 28%|██▊       | 600/2129 [00:33<01:26, 17.67it/s]
 28%|██▊       | 603/2129 [00:33<01:28, 17.30it/s]
 28%|██▊       | 605/2129 [00:33<01:35, 15.94it/s]
 29%|██▊       | 610/2129 [00:33<01:08, 22.22it/s]
 29%|██▉       | 613/2129 [00:33<01:06, 22.91it/s]
 29%|██▉       | 618/2129 [00:34<00:58, 25.66it/s]
 29%|██▉       | 621/2129 [00:34<01:04, 23.34it/s]
 29%|██▉       | 624/2129 [00:34<01:22, 18.30it/s]
 29%|██▉       | 628/2129 [00:34<01:10, 21.44it/s]
 30%|██▉       | 634/2129 [00:34<00:53, 28.08it/s]
 30%|███       | 640/2129 [00:34<00:44, 33.58it/s]
 30%|███       | 644/2129 [00:34<00:47, 31.35it/s]
 30%|███       | 648/2129 [00:35<00:50, 29.60it/s]
 31%|███       | 652/2129 [00:35<00:49, 29.61it/s]
 31%|███       | 656/2129 [00:35<01:08, 21.56it/s]
 31%|███       | 659/2129 [00:35<01:25, 17.18it/s]
 31%|███       | 662/2129 [00:36<01:46, 13.80it/s]
 31%|███       | 664/2129 [00:36<01:58, 12.34it/s]
 31%|███▏      | 666/2129 [00:36<01:53, 12.94it/s]
 31%|███▏      | 669/2129 [00:36<01:32, 15.74it/s]
 32%|███▏      | 672/2129 [00:36<01:46, 13.73it/s]
 32%|███▏      | 674/2129 [00:37<01:49, 13.30it/s]
 32%|███▏      | 676/2129 [00:37<01:42, 14.19it/s]
 32%|███▏      | 680/2129 [00:37<01:17, 18.68it/s]
 32%|███▏      | 683/2129 [00:37<01:42, 14.05it/s]
 32%|███▏      | 685/2129 [00:37<01:49, 13.24it/s]
 32%|███▏      | 688/2129 [00:38<01:54, 12.61it/s]
 33%|███▎      | 692/2129 [00:38<01:27, 16.44it/s]
 33%|███▎      | 694/2129 [00:38<01:28, 16.13it/s]
 33%|███▎      | 698/2129 [00:38<01:09, 20.63it/s]
 33%|███▎      | 701/2129 [00:38<01:04, 22.13it/s]
 33%|███▎      | 705/2129 [00:38<01:14, 19.19it/s]
 33%|███▎      | 708/2129 [00:39<01:32, 15.33it/s]
 33%|███▎      | 710/2129 [00:39<01:28, 16.07it/s]
 33%|███▎      | 712/2129 [00:39<01:46, 13.33it/s]
 34%|███▎      | 714/2129 [00:39<02:02, 11.54it/s]
 34%|███▍      | 719/2129 [00:40<01:39, 14.16it/s]
 34%|███▍      | 721/2129 [00:40<01:57, 11.98it/s]
 34%|███▍      | 723/2129 [00:40<02:09, 10.86it/s]
 34%|███▍      | 725/2129 [00:40<02:43,  8.57it/s]
 34%|███▍      | 726/2129 [00:41<03:05,  7.57it/s]
 34%|███▍      | 727/2129 [00:41<03:19,  7.04it/s]
 34%|███▍      | 728/2129 [00:41<03:36,  6.47it/s]
 34%|███▍      | 731/2129 [00:41<02:20,  9.92it/s]
 34%|███▍      | 733/2129 [00:41<02:22,  9.78it/s]
 35%|███▍      | 735/2129 [00:42<02:26,  9.51it/s]
 35%|███▍      | 737/2129 [00:42<02:32,  9.14it/s]
 35%|███▍      | 739/2129 [00:42<02:37,  8.82it/s]
 35%|███▍      | 742/2129 [00:42<02:34,  8.99it/s]
 35%|███▍      | 745/2129 [00:43<02:00, 11.51it/s]
 35%|███▌      | 751/2129 [00:43<01:29, 15.43it/s]
 35%|███▌      | 753/2129 [00:43<01:52, 12.19it/s]
 35%|███▌      | 755/2129 [00:43<02:26,  9.40it/s]
 36%|███▌      | 757/2129 [00:44<02:08, 10.68it/s]
 36%|███▌      | 759/2129 [00:44<02:05, 10.92it/s]
 36%|███▌      | 761/2129 [00:44<01:52, 12.16it/s]
 36%|███▌      | 763/2129 [00:44<02:21,  9.63it/s]
 36%|███▌      | 766/2129 [00:44<02:08, 10.57it/s]
 36%|███▌      | 768/2129 [00:45<02:03, 11.04it/s]
 36%|███▌      | 770/2129 [00:45<02:14, 10.10it/s]
 36%|███▋      | 773/2129 [00:45<01:42, 13.17it/s]
 36%|███▋      | 775/2129 [00:45<02:26,  9.26it/s]
 36%|███▋      | 777/2129 [00:46<02:30,  8.98it/s]
 37%|███▋      | 780/2129 [00:46<02:17,  9.82it/s]
 37%|███▋      | 782/2129 [00:46<02:48,  8.02it/s]
 37%|███▋      | 784/2129 [00:46<02:23,  9.36it/s]
 37%|███▋      | 786/2129 [00:47<02:23,  9.33it/s]
 37%|███▋      | 788/2129 [00:47<02:23,  9.35it/s]
 37%|███▋      | 790/2129 [00:47<02:01, 10.98it/s]
 37%|███▋      | 792/2129 [00:47<02:04, 10.77it/s]
 37%|███▋      | 794/2129 [00:47<02:10, 10.26it/s]
 37%|███▋      | 796/2129 [00:48<02:34,  8.63it/s]
 37%|███▋      | 798/2129 [00:48<02:54,  7.65it/s]
 38%|███▊      | 800/2129 [00:48<02:55,  7.58it/s]
 38%|███▊      | 802/2129 [00:48<02:36,  8.47it/s]
 38%|███▊      | 805/2129 [00:49<02:03, 10.70it/s]
 38%|███▊      | 808/2129 [00:49<01:35, 13.78it/s]
 38%|███▊      | 811/2129 [00:49<01:19, 16.51it/s]
 38%|███▊      | 813/2129 [00:49<01:33, 14.13it/s]
 38%|███▊      | 816/2129 [00:49<01:17, 16.91it/s]
 38%|███▊      | 818/2129 [00:49<01:28, 14.80it/s]
 39%|███▊      | 820/2129 [00:49<01:26, 15.05it/s]
 39%|███▊      | 822/2129 [00:49<01:21, 16.03it/s]
 39%|███▊      | 824/2129 [00:50<01:20, 16.20it/s]
 39%|███▉      | 827/2129 [00:50<01:18, 16.58it/s]
 39%|███▉      | 829/2129 [00:50<01:22, 15.71it/s]
 39%|███▉      | 832/2129 [00:50<01:08, 18.85it/s]
 39%|███▉      | 838/2129 [00:50<00:48, 26.54it/s]
 40%|███▉      | 841/2129 [00:50<00:54, 23.66it/s]
 40%|███▉      | 844/2129 [00:51<01:31, 14.06it/s]
 40%|███▉      | 846/2129 [00:51<01:49, 11.67it/s]
 40%|███▉      | 850/2129 [00:51<01:22, 15.46it/s]
 40%|████      | 854/2129 [00:51<01:22, 15.51it/s]
 40%|████      | 856/2129 [00:52<01:28, 14.32it/s]
 40%|████      | 858/2129 [00:52<01:27, 14.53it/s]
 40%|████      | 862/2129 [00:52<01:13, 17.29it/s]
 41%|████      | 865/2129 [00:52<01:16, 16.58it/s]
 41%|████      | 867/2129 [00:52<01:13, 17.13it/s]
 41%|████      | 872/2129 [00:52<00:54, 23.14it/s]
 41%|████      | 875/2129 [00:53<01:11, 17.42it/s]
 41%|████      | 878/2129 [00:53<01:13, 17.13it/s]
 41%|████▏     | 880/2129 [00:53<01:19, 15.61it/s]
 42%|████▏     | 885/2129 [00:53<01:01, 20.12it/s]
 42%|████▏     | 888/2129 [00:54<01:39, 12.45it/s]
 42%|████▏     | 891/2129 [00:54<01:30, 13.66it/s]
 42%|████▏     | 893/2129 [00:54<01:27, 14.14it/s]
 42%|████▏     | 896/2129 [00:54<01:17, 15.91it/s]
 42%|████▏     | 898/2129 [00:54<01:44, 11.76it/s]
 42%|████▏     | 901/2129 [00:54<01:28, 13.90it/s]
 42%|████▏     | 903/2129 [00:55<02:00, 10.14it/s]
 43%|████▎     | 905/2129 [00:55<01:48, 11.26it/s]
 43%|████▎     | 907/2129 [00:55<01:53, 10.77it/s]
 43%|████▎     | 909/2129 [00:55<01:52, 10.83it/s]
 43%|████▎     | 911/2129 [00:56<02:09,  9.42it/s]
 43%|████▎     | 913/2129 [00:56<02:00, 10.06it/s]
 43%|████▎     | 915/2129 [00:56<02:04,  9.72it/s]
 43%|████▎     | 917/2129 [00:56<01:47, 11.29it/s]
 43%|████▎     | 922/2129 [00:56<01:06, 18.19it/s]
 43%|████▎     | 925/2129 [00:56<01:09, 17.27it/s]
 44%|████▎     | 928/2129 [00:57<01:19, 15.15it/s]
 44%|████▎     | 930/2129 [00:57<01:19, 15.04it/s]
 44%|████▍     | 932/2129 [00:57<01:32, 12.98it/s]
 44%|████▍     | 935/2129 [00:57<01:14, 16.00it/s]
 44%|████▍     | 937/2129 [00:58<01:55, 10.36it/s]
 44%|████▍     | 939/2129 [00:58<02:06,  9.44it/s]
 44%|████▍     | 941/2129 [00:58<01:48, 10.91it/s]
 44%|████▍     | 944/2129 [00:58<01:33, 12.66it/s]
 45%|████▍     | 948/2129 [00:58<01:10, 16.78it/s]
 45%|████▍     | 951/2129 [00:58<01:21, 14.53it/s]
 45%|████▍     | 953/2129 [00:59<01:20, 14.59it/s]
 45%|████▍     | 956/2129 [00:59<01:06, 17.52it/s]
 45%|████▌     | 959/2129 [00:59<01:15, 15.59it/s]
 45%|████▌     | 961/2129 [00:59<01:14, 15.69it/s]
 45%|████▌     | 963/2129 [00:59<01:28, 13.14it/s]
 45%|████▌     | 965/2129 [00:59<01:22, 14.17it/s]
 45%|████▌     | 968/2129 [01:00<01:16, 15.08it/s]
 46%|████▌     | 970/2129 [01:00<01:20, 14.47it/s]
 46%|████▌     | 972/2129 [01:00<01:30, 12.73it/s]
 46%|████▌     | 974/2129 [01:00<01:47, 10.70it/s]
 46%|████▌     | 977/2129 [01:00<01:30, 12.75it/s]
 46%|████▌     | 981/2129 [01:01<01:24, 13.55it/s]
 46%|████▌     | 984/2129 [01:01<01:11, 16.06it/s]
 46%|████▋     | 988/2129 [01:01<01:02, 18.23it/s]
 47%|████▋     | 990/2129 [01:01<01:05, 17.39it/s]
 47%|████▋     | 993/2129 [01:01<01:25, 13.21it/s]
 47%|████▋     | 996/2129 [01:02<01:16, 14.81it/s]
 47%|████▋     | 1000/2129 [01:02<00:59, 19.12it/s]
 47%|████▋     | 1003/2129 [01:02<01:22, 13.69it/s]
 47%|████▋     | 1005/2129 [01:02<01:18, 14.39it/s]
 47%|████▋     | 1007/2129 [01:02<01:26, 12.93it/s]
 47%|████▋     | 1009/2129 [01:02<01:19, 14.17it/s]
 47%|████▋     | 1011/2129 [01:03<01:25, 13.11it/s]
 48%|████▊     | 1013/2129 [01:03<01:45, 10.56it/s]
 48%|████▊     | 1015/2129 [01:03<01:40, 11.10it/s]
 48%|████▊     | 1017/2129 [01:03<01:43, 10.77it/s]
 48%|████▊     | 1019/2129 [01:03<01:43, 10.73it/s]
 48%|████▊     | 1022/2129 [01:04<01:17, 14.22it/s]
 48%|████▊     | 1024/2129 [01:04<01:52,  9.81it/s]
 48%|████▊     | 1027/2129 [01:04<01:28, 12.39it/s]
 48%|████▊     | 1029/2129 [01:04<01:44, 10.54it/s]
 48%|████▊     | 1031/2129 [01:05<01:57,  9.38it/s]
 49%|████▊     | 1033/2129 [01:05<01:42, 10.74it/s]
 49%|████▊     | 1036/2129 [01:05<01:18, 13.94it/s]
 49%|████▉     | 1040/2129 [01:05<01:05, 16.66it/s]
 49%|████▉     | 1042/2129 [01:05<01:17, 14.08it/s]
 49%|████▉     | 1045/2129 [01:05<01:04, 16.85it/s]
 49%|████▉     | 1048/2129 [01:06<01:08, 15.72it/s]
 49%|████▉     | 1051/2129 [01:06<01:16, 14.10it/s]
 50%|████▉     | 1054/2129 [01:06<01:19, 13.46it/s]
 50%|████▉     | 1056/2129 [01:06<01:50,  9.75it/s]
 50%|████▉     | 1058/2129 [01:07<02:18,  7.75it/s]
 50%|████▉     | 1059/2129 [01:07<02:29,  7.14it/s]
 50%|████▉     | 1060/2129 [01:07<02:33,  6.98it/s]
 50%|████▉     | 1063/2129 [01:07<01:47,  9.89it/s]
 50%|█████     | 1065/2129 [01:08<01:56,  9.15it/s]
 50%|█████     | 1067/2129 [01:08<01:39, 10.73it/s]
 50%|█████     | 1069/2129 [01:08<01:47,  9.84it/s]
 50%|█████     | 1071/2129 [01:08<01:55,  9.16it/s]
 50%|█████     | 1073/2129 [01:08<01:38, 10.77it/s]
 51%|█████     | 1077/2129 [01:09<01:27, 12.03it/s]
 51%|█████     | 1080/2129 [01:09<01:35, 10.96it/s]
 51%|█████     | 1082/2129 [01:09<01:28, 11.84it/s]
 51%|█████     | 1085/2129 [01:09<01:23, 12.53it/s]
 51%|█████     | 1088/2129 [01:10<01:28, 11.77it/s]
 51%|█████     | 1090/2129 [01:10<01:19, 13.00it/s]
 51%|█████▏    | 1092/2129 [01:10<01:34, 10.97it/s]
 51%|█████▏    | 1094/2129 [01:10<01:40, 10.30it/s]
 52%|█████▏    | 1097/2129 [01:10<01:18, 13.07it/s]
 52%|█████▏    | 1099/2129 [01:11<01:26, 11.87it/s]
 52%|█████▏    | 1101/2129 [01:11<01:33, 10.96it/s]
 52%|█████▏    | 1103/2129 [01:11<01:40, 10.23it/s]
 52%|█████▏    | 1106/2129 [01:11<01:38, 10.38it/s]
 52%|█████▏    | 1108/2129 [01:12<01:47,  9.49it/s]
 52%|█████▏    | 1110/2129 [01:12<01:41, 10.03it/s]
 52%|█████▏    | 1113/2129 [01:12<01:35, 10.62it/s]
 52%|█████▏    | 1115/2129 [01:12<01:44,  9.74it/s]
 52%|█████▏    | 1117/2129 [01:12<01:30, 11.17it/s]
 53%|█████▎    | 1119/2129 [01:13<01:39, 10.11it/s]
 53%|█████▎    | 1121/2129 [01:13<01:43,  9.70it/s]
 53%|█████▎    | 1123/2129 [01:13<01:42,  9.81it/s]
 53%|█████▎    | 1125/2129 [01:13<01:28, 11.34it/s]
 53%|█████▎    | 1127/2129 [01:13<01:35, 10.49it/s]
 53%|█████▎    | 1130/2129 [01:13<01:15, 13.15it/s]
 53%|█████▎    | 1132/2129 [01:14<01:43,  9.60it/s]
 53%|█████▎    | 1134/2129 [01:14<01:28, 11.21it/s]
 53%|█████▎    | 1136/2129 [01:14<01:50,  9.01it/s]
 53%|█████▎    | 1139/2129 [01:15<01:41,  9.71it/s]
 54%|█████▎    | 1141/2129 [01:15<01:33, 10.55it/s]
 54%|█████▎    | 1143/2129 [01:15<01:27, 11.27it/s]
 54%|█████▍    | 1145/2129 [01:15<01:33, 10.55it/s]
 54%|█████▍    | 1147/2129 [01:15<01:27, 11.28it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 310.47it/s]

[[np.int64(0), False, 2], [np.int64(1), False, 11], [np.int64(2), False, 3], [np.int64(4), False, 5], [np.int64(5), False, 1], [np.int64(6), False, 3], [np.int64(7), False, 13], [np.int64(8), False, 12], [np.int64(9), False, 0], [np.int64(10), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8349, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-1.8307, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [02:31<2:21:11, 42.57s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [02:32<1:38:28, 29.84s/it]

tensor(12.8237, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.0226, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.2913, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [02:32<33:31, 10.32s/it]

tensor(12.8855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.5569, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.7465, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [02:32<23:27,  7.26s/it]

tensor(12.9849, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.9623, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [02:32<08:10,  2.57s/it]

tensor(13.0027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0597, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9861, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1754, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [02:33<05:48,  1.84s/it]

tensor(12.9647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2934, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3945, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [02:33<02:12,  1.41it/s]

tensor(12.9244, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4832, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5255, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [02:33<01:39,  1.87it/s]

tensor(12.8321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5700, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6089, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [02:33<00:48,  3.81it/s]

tensor(12.7696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6660, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7135, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [02:34<00:34,  5.25it/s]

tensor(12.7554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7621, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7426, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7987, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [02:34<00:30,  5.90it/s]

tensor(12.7292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9268, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [02:34<00:24,  7.23it/s]

tensor(12.7143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9750, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0077, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [02:34<00:23,  7.38it/s]

tensor(12.6872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0549, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0758, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [02:35<00:21,  7.97it/s]

tensor(12.6420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0656, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0825, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [02:35<00:21,  8.05it/s]

tensor(12.6085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0940, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1140, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [02:35<00:20,  8.18it/s]

tensor(12.5746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1504, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1823, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [02:35<00:20,  8.23it/s]

tensor(12.5362, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2026, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2351, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [02:36<00:20,  8.21it/s]

tensor(12.4991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2688, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2854, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [02:36<00:19,  8.20it/s]

tensor(12.4681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3138, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3336, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [02:36<00:19,  8.22it/s]

tensor(12.4404, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3560, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3734, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [02:36<00:19,  8.11it/s]

tensor(12.4172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4286, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [02:37<00:19,  8.20it/s]

tensor(12.3988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4511, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4769, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [02:37<00:18,  8.22it/s]

tensor(12.3771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4901, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4942, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [02:37<00:19,  8.09it/s]

tensor(12.3538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5144, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3426, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5353, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [02:37<00:18,  8.27it/s]

tensor(12.3324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5680, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5904, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [02:37<00:18,  8.27it/s]

tensor(12.3160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6096, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([151,  90, 243, 168,  71, 155, 166, 261, 119,  95,  36, 224, 182, 168])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:41, 20.86it/s]
  0%|          | 6/2129 [00:00<01:29, 23.65it/s]
  1%|          | 13/2129 [00:00<00:51, 40.80it/s]
  1%|          | 19/2129 [00:00<00:45, 46.65it/s]
  1%|▏         | 27/2129 [00:00<00:37, 55.52it/s]
  2%|▏         | 34/2129 [00:00<00:34, 59.87it/s]
  2%|▏         | 41/2129 [00:00<00:34, 61.10it/s]
  2%|▏         | 49/2129 [00:00<00:31, 66.25it/s]
  3%|▎         | 57/2129 [00:01<00:30, 68.35it/s]
  3%|▎         | 65/2129 [00:01<00:30, 68.62it/s]
  3%|▎         | 72/2129 [00:01<00:33, 62.08it/s]
  4%|▎         | 79/2129 [00:01<00:32, 63.85it/s]
  4%|▍         | 86/2129 [00:01<00:31, 63.88it/s]
  4%|▍         | 94/2129 [00:01<00:30, 66.29it/s]
  5%|▍         | 101/2129 [00:01<00:31, 63.93it/s]
  5%|▌         | 108/2129 [00:01<00:31, 65.06it/s]
  5%|▌         | 115/2129 [00:01<00:32, 61.91it/s]
  6%|▌         | 122/2129 [00:02<00:32, 60.82it/s]
  6%|▌         | 129/2129 [00:02<00:34, 58.00it/s]
  6%|▋         | 137/2129 [00:02<00:31, 62.44it/s]
  7%|▋         | 144/2129 [00:02<00:30, 64.22it/s]
  7%|▋         | 152/2129 [00:02<00:29, 66.56it/s]
  7%|▋         | 159/2129 [00:02<00:39, 49.58it/s]
  8%|▊         | 165/2129 [00:02<00:39, 49.63it/s]
  8%|▊         | 173/2129 [00:02<00:34, 56.53it/s]
  8%|▊         | 180/2129 [00:03<00:34, 55.77it/s]
  9%|▊         | 186/2129 [00:03<00:53, 36.49it/s]
  9%|▉         | 191/2129 [00:03<01:07, 28.87it/s]
  9%|▉         | 195/2129 [00:03<01:04, 29.97it/s]
  9%|▉         | 202/2129 [00:03<00:52, 36.56it/s]
 10%|▉         | 207/2129 [00:04<00:49, 38.93it/s]
 10%|▉         | 212/2129 [00:04<00:58, 32.77it/s]
 10%|█         | 216/2129 [00:04<01:47, 17.84it/s]
 10%|█         | 220/2129 [00:04<01:33, 20.49it/s]
 11%|█         | 224/2129 [00:05<01:32, 20.57it/s]
 11%|█         | 227/2129 [00:05<01:26, 21.97it/s]
 11%|█         | 233/2129 [00:05<01:26, 22.02it/s]
 11%|█         | 237/2129 [00:05<01:19, 23.78it/s]
 11%|█▏        | 240/2129 [00:05<01:39, 18.98it/s]
 11%|█▏        | 244/2129 [00:05<01:24, 22.23it/s]
 12%|█▏        | 247/2129 [00:06<01:47, 17.45it/s]
 12%|█▏        | 250/2129 [00:06<01:53, 16.57it/s]
 12%|█▏        | 252/2129 [00:06<02:30, 12.51it/s]
 12%|█▏        | 254/2129 [00:06<02:19, 13.41it/s]
 12%|█▏        | 258/2129 [00:07<01:58, 15.72it/s]
 12%|█▏        | 260/2129 [00:07<02:04, 15.02it/s]
 12%|█▏        | 266/2129 [00:07<01:21, 22.87it/s]
 13%|█▎        | 269/2129 [00:07<01:33, 19.85it/s]
 13%|█▎        | 272/2129 [00:07<01:33, 19.76it/s]
 13%|█▎        | 278/2129 [00:07<01:07, 27.41it/s]
 13%|█▎        | 285/2129 [00:07<00:51, 35.69it/s]
 14%|█▎        | 290/2129 [00:08<01:16, 24.01it/s]
 14%|█▍        | 294/2129 [00:08<01:28, 20.69it/s]
 14%|█▍        | 299/2129 [00:08<01:13, 25.06it/s]
 14%|█▍        | 304/2129 [00:08<01:20, 22.79it/s]
 14%|█▍        | 307/2129 [00:09<01:46, 17.14it/s]
 15%|█▍        | 312/2129 [00:09<01:39, 18.32it/s]
 15%|█▍        | 315/2129 [00:09<01:55, 15.77it/s]
 15%|█▌        | 320/2129 [00:09<01:27, 20.62it/s]
 15%|█▌        | 324/2129 [00:10<01:31, 19.71it/s]
 15%|█▌        | 327/2129 [00:10<01:27, 20.56it/s]
 16%|█▌        | 330/2129 [00:10<01:49, 16.43it/s]
 16%|█▌        | 334/2129 [00:10<01:56, 15.47it/s]
 16%|█▌        | 336/2129 [00:10<01:55, 15.48it/s]
 16%|█▌        | 338/2129 [00:11<02:18, 12.89it/s]
 16%|█▌        | 342/2129 [00:11<01:45, 16.91it/s]
 16%|█▌        | 345/2129 [00:11<02:04, 14.36it/s]
 16%|█▋        | 349/2129 [00:11<01:59, 14.86it/s]
 16%|█▋        | 351/2129 [00:12<02:21, 12.55it/s]
 17%|█▋        | 355/2129 [00:12<02:16, 13.02it/s]
 17%|█▋        | 357/2129 [00:12<02:38, 11.15it/s]
 17%|█▋        | 359/2129 [00:12<02:52, 10.24it/s]
 17%|█▋        | 361/2129 [00:13<03:08,  9.39it/s]
 17%|█▋        | 362/2129 [00:13<03:45,  7.84it/s]
 17%|█▋        | 365/2129 [00:13<02:44, 10.69it/s]
 18%|█▊        | 373/2129 [00:13<01:46, 16.53it/s]
 18%|█▊        | 376/2129 [00:14<01:59, 14.64it/s]
 18%|█▊        | 378/2129 [00:14<01:58, 14.76it/s]
 18%|█▊        | 380/2129 [00:14<02:00, 14.47it/s]
 18%|█▊        | 383/2129 [00:14<01:44, 16.66it/s]
 18%|█▊        | 386/2129 [00:14<01:52, 15.47it/s]
 18%|█▊        | 388/2129 [00:14<01:48, 16.08it/s]
 18%|█▊        | 391/2129 [00:15<01:37, 17.77it/s]
 19%|█▊        | 396/2129 [00:15<01:11, 24.19it/s]
 19%|█▉        | 400/2129 [00:15<01:17, 22.27it/s]
 19%|█▉        | 403/2129 [00:15<01:27, 19.75it/s]
 19%|█▉        | 409/2129 [00:15<01:03, 27.03it/s]
 19%|█▉        | 414/2129 [00:15<00:54, 31.22it/s]
 20%|█▉        | 420/2129 [00:15<00:46, 36.41it/s]
 20%|█▉        | 425/2129 [00:16<00:43, 39.25it/s]
 20%|██        | 430/2129 [00:16<00:45, 37.28it/s]
 20%|██        | 434/2129 [00:16<01:12, 23.25it/s]
 21%|██        | 438/2129 [00:16<01:33, 18.02it/s]
 21%|██        | 441/2129 [00:17<01:32, 18.19it/s]
 21%|██        | 447/2129 [00:17<01:07, 24.82it/s]
 21%|██▏       | 454/2129 [00:17<00:50, 33.01it/s]
 22%|██▏       | 459/2129 [00:17<01:32, 18.04it/s]
 22%|██▏       | 463/2129 [00:17<01:24, 19.73it/s]
 22%|██▏       | 467/2129 [00:18<01:30, 18.27it/s]
 22%|██▏       | 470/2129 [00:18<01:43, 16.02it/s]
 22%|██▏       | 473/2129 [00:18<02:01, 13.63it/s]
 22%|██▏       | 477/2129 [00:19<01:54, 14.48it/s]
 22%|██▏       | 479/2129 [00:19<02:19, 11.81it/s]
 23%|██▎       | 482/2129 [00:19<01:55, 14.23it/s]
 23%|██▎       | 484/2129 [00:19<02:12, 12.41it/s]
 23%|██▎       | 487/2129 [00:20<02:25, 11.32it/s]
 23%|██▎       | 489/2129 [00:20<02:15, 12.12it/s]
 23%|██▎       | 495/2129 [00:20<01:23, 19.53it/s]
 24%|██▎       | 501/2129 [00:20<01:22, 19.73it/s]
 24%|██▎       | 504/2129 [00:20<01:27, 18.53it/s]
 24%|██▍       | 507/2129 [00:20<01:27, 18.62it/s]
 24%|██▍       | 510/2129 [00:21<01:19, 20.47it/s]
 24%|██▍       | 515/2129 [00:21<01:05, 24.79it/s]
 24%|██▍       | 518/2129 [00:21<01:08, 23.45it/s]
 24%|██▍       | 521/2129 [00:21<01:50, 14.55it/s]
 25%|██▍       | 524/2129 [00:21<01:35, 16.82it/s]
 25%|██▍       | 527/2129 [00:22<01:56, 13.77it/s]
 25%|██▍       | 529/2129 [00:22<02:15, 11.83it/s]
 25%|██▍       | 532/2129 [00:22<02:00, 13.27it/s]
 25%|██▌       | 535/2129 [00:22<02:01, 13.13it/s]
 25%|██▌       | 538/2129 [00:22<01:42, 15.54it/s]
 26%|██▌       | 543/2129 [00:23<01:26, 18.44it/s]
 26%|██▌       | 546/2129 [00:23<01:27, 18.13it/s]
 26%|██▌       | 552/2129 [00:23<01:02, 25.23it/s]
 26%|██▌       | 556/2129 [00:23<00:55, 28.26it/s]
 26%|██▋       | 560/2129 [00:23<01:09, 22.71it/s]
 26%|██▋       | 563/2129 [00:23<01:16, 20.53it/s]
 27%|██▋       | 567/2129 [00:24<01:25, 18.36it/s]
 27%|██▋       | 570/2129 [00:24<01:21, 19.02it/s]
 27%|██▋       | 573/2129 [00:24<01:36, 16.06it/s]
 27%|██▋       | 579/2129 [00:24<01:07, 23.10it/s]
 27%|██▋       | 582/2129 [00:25<01:21, 19.06it/s]
 27%|██▋       | 585/2129 [00:25<01:45, 14.63it/s]
 28%|██▊       | 587/2129 [00:25<01:55, 13.37it/s]
 28%|██▊       | 590/2129 [00:25<01:59, 12.87it/s]
 28%|██▊       | 593/2129 [00:25<01:42, 14.94it/s]
 28%|██▊       | 599/2129 [00:26<01:19, 19.24it/s]
 28%|██▊       | 603/2129 [00:26<01:10, 21.61it/s]
 29%|██▊       | 610/2129 [00:26<01:09, 21.95it/s]
 29%|██▉       | 613/2129 [00:26<01:09, 21.79it/s]
 29%|██▉       | 620/2129 [00:26<00:50, 30.09it/s]
 29%|██▉       | 624/2129 [00:26<00:48, 30.85it/s]
 29%|██▉       | 628/2129 [00:27<01:05, 22.81it/s]
 30%|██▉       | 634/2129 [00:27<00:51, 29.04it/s]
 30%|██▉       | 638/2129 [00:27<01:04, 23.14it/s]
 30%|███       | 642/2129 [00:27<01:20, 18.51it/s]
 30%|███       | 645/2129 [00:28<01:32, 16.06it/s]
 30%|███       | 648/2129 [00:28<01:23, 17.72it/s]
 31%|███       | 651/2129 [00:28<01:40, 14.73it/s]
 31%|███       | 657/2129 [00:28<01:08, 21.50it/s]
 31%|███       | 661/2129 [00:29<01:24, 17.34it/s]
 31%|███       | 664/2129 [00:29<01:55, 12.65it/s]
 31%|███▏      | 667/2129 [00:29<02:02, 11.97it/s]
 31%|███▏      | 669/2129 [00:29<01:56, 12.51it/s]
 32%|███▏      | 677/2129 [00:30<01:06, 21.76it/s]
 32%|███▏      | 684/2129 [00:30<00:49, 29.16it/s]
 32%|███▏      | 688/2129 [00:30<01:06, 21.72it/s]
 33%|███▎      | 692/2129 [00:30<01:18, 18.41it/s]
 33%|███▎      | 695/2129 [00:31<01:27, 16.41it/s]
 33%|███▎      | 698/2129 [00:31<01:42, 13.96it/s]
 33%|███▎      | 705/2129 [00:31<01:06, 21.27it/s]
 33%|███▎      | 709/2129 [00:31<01:15, 18.87it/s]
 33%|███▎      | 712/2129 [00:32<01:26, 16.44it/s]
 34%|███▎      | 715/2129 [00:32<01:38, 14.38it/s]
 34%|███▍      | 721/2129 [00:32<01:22, 16.97it/s]
 34%|███▍      | 723/2129 [00:32<01:38, 14.28it/s]
 34%|███▍      | 725/2129 [00:33<01:57, 11.94it/s]
 34%|███▍      | 728/2129 [00:33<02:00, 11.59it/s]
 34%|███▍      | 730/2129 [00:33<01:53, 12.33it/s]
 34%|███▍      | 733/2129 [00:33<02:06, 11.07it/s]
 35%|███▍      | 736/2129 [00:34<01:42, 13.62it/s]
 35%|███▍      | 739/2129 [00:34<01:53, 12.30it/s]
 35%|███▍      | 742/2129 [00:34<01:33, 14.85it/s]
 35%|███▌      | 749/2129 [00:34<00:56, 24.54it/s]
 35%|███▌      | 753/2129 [00:34<01:09, 19.91it/s]
 36%|███▌      | 756/2129 [00:35<01:47, 12.72it/s]
 36%|███▌      | 759/2129 [00:35<01:33, 14.69it/s]
 36%|███▌      | 762/2129 [00:35<01:40, 13.66it/s]
 36%|███▌      | 764/2129 [00:35<01:56, 11.67it/s]
 36%|███▌      | 766/2129 [00:36<02:02, 11.11it/s]
 36%|███▌      | 768/2129 [00:36<01:52, 12.12it/s]
 36%|███▌      | 770/2129 [00:36<02:19,  9.73it/s]
 36%|███▋      | 774/2129 [00:36<01:58, 11.41it/s]
 36%|███▋      | 776/2129 [00:37<02:00, 11.21it/s]
 37%|███▋      | 780/2129 [00:37<01:43, 13.06it/s]
 37%|███▋      | 783/2129 [00:37<01:27, 15.38it/s]
 37%|███▋      | 786/2129 [00:37<01:24, 15.86it/s]
 37%|███▋      | 788/2129 [00:37<01:38, 13.64it/s]
 37%|███▋      | 790/2129 [00:37<01:30, 14.77it/s]
 37%|███▋      | 796/2129 [00:38<01:21, 16.28it/s]
 37%|███▋      | 798/2129 [00:38<01:41, 13.16it/s]
 38%|███▊      | 800/2129 [00:38<01:38, 13.49it/s]
 38%|███▊      | 802/2129 [00:38<02:01, 10.92it/s]
 38%|███▊      | 804/2129 [00:39<01:57, 11.28it/s]
 38%|███▊      | 809/2129 [00:39<01:15, 17.54it/s]
 38%|███▊      | 815/2129 [00:39<00:53, 24.61it/s]
 39%|███▊      | 820/2129 [00:39<01:00, 21.75it/s]
 39%|███▊      | 823/2129 [00:39<00:59, 22.02it/s]
 39%|███▉      | 831/2129 [00:39<00:41, 31.64it/s]
 39%|███▉      | 838/2129 [00:39<00:33, 38.98it/s]
 40%|███▉      | 843/2129 [00:40<00:44, 28.91it/s]
 40%|███▉      | 847/2129 [00:40<01:02, 20.48it/s]
 40%|███▉      | 851/2129 [00:40<00:55, 22.96it/s]
 40%|████      | 855/2129 [00:41<01:18, 16.30it/s]
 40%|████      | 859/2129 [00:41<01:05, 19.46it/s]
 40%|████      | 862/2129 [00:41<01:26, 14.60it/s]
 41%|████      | 865/2129 [00:42<01:37, 12.94it/s]
 41%|████      | 867/2129 [00:42<01:47, 11.76it/s]
 41%|████      | 870/2129 [00:42<01:28, 14.25it/s]
 41%|████      | 876/2129 [00:42<00:58, 21.53it/s]
 41%|████▏     | 880/2129 [00:42<00:50, 24.55it/s]
 42%|████▏     | 885/2129 [00:42<00:42, 29.27it/s]
 42%|████▏     | 889/2129 [00:43<01:20, 15.37it/s]
 42%|████▏     | 892/2129 [00:43<01:13, 16.92it/s]
 42%|████▏     | 898/2129 [00:43<01:09, 17.78it/s]
 42%|████▏     | 901/2129 [00:43<01:06, 18.41it/s]
 42%|████▏     | 904/2129 [00:44<01:38, 12.40it/s]
 43%|████▎     | 906/2129 [00:44<01:49, 11.15it/s]
 43%|████▎     | 908/2129 [00:44<01:59, 10.21it/s]
 43%|████▎     | 910/2129 [00:44<01:50, 11.08it/s]
 43%|████▎     | 918/2129 [00:45<00:57, 21.06it/s]
 43%|████▎     | 925/2129 [00:45<00:40, 29.47it/s]
 44%|████▎     | 930/2129 [00:45<00:53, 22.54it/s]
 44%|████▍     | 935/2129 [00:45<00:44, 26.69it/s]
 44%|████▍     | 939/2129 [00:46<01:09, 17.12it/s]
 44%|████▍     | 942/2129 [00:46<01:05, 18.17it/s]
 44%|████▍     | 945/2129 [00:46<01:16, 15.38it/s]
 45%|████▍     | 948/2129 [00:46<01:15, 15.60it/s]
 45%|████▍     | 951/2129 [00:47<01:31, 12.93it/s]
 45%|████▍     | 954/2129 [00:47<01:18, 15.02it/s]
 45%|████▍     | 956/2129 [00:47<01:32, 12.68it/s]
 45%|████▍     | 958/2129 [00:47<01:42, 11.44it/s]
 45%|████▌     | 960/2129 [00:47<01:53, 10.33it/s]
 45%|████▌     | 962/2129 [00:48<01:57,  9.92it/s]
 45%|████▌     | 964/2129 [00:48<02:13,  8.72it/s]
 45%|████▌     | 966/2129 [00:48<01:54, 10.19it/s]
 45%|████▌     | 968/2129 [00:48<01:51, 10.38it/s]
 46%|████▌     | 971/2129 [00:48<01:30, 12.75it/s]
 46%|████▌     | 973/2129 [00:49<01:48, 10.61it/s]
 46%|████▌     | 975/2129 [00:49<01:50, 10.47it/s]
 46%|████▌     | 977/2129 [00:49<01:36, 11.91it/s]
 46%|████▌     | 979/2129 [00:49<01:30, 12.77it/s]
 46%|████▌     | 981/2129 [00:49<01:33, 12.30it/s]
 46%|████▌     | 983/2129 [00:49<01:29, 12.75it/s]
 46%|████▋     | 985/2129 [00:50<01:23, 13.70it/s]
 46%|████▋     | 988/2129 [00:50<01:23, 13.72it/s]
 47%|████▋     | 991/2129 [00:50<01:10, 16.21it/s]
 47%|████▋     | 993/2129 [00:50<01:18, 14.48it/s]
 47%|████▋     | 996/2129 [00:50<01:05, 17.42it/s]
 47%|████▋     | 998/2129 [00:50<01:03, 17.81it/s]
 47%|████▋     | 1003/2129 [00:50<00:47, 23.88it/s]
 47%|████▋     | 1006/2129 [00:51<00:45, 24.84it/s]
 47%|████▋     | 1010/2129 [00:51<00:40, 27.95it/s]
 48%|████▊     | 1013/2129 [00:51<00:59, 18.77it/s]
 48%|████▊     | 1016/2129 [00:51<01:11, 15.52it/s]
 48%|████▊     | 1019/2129 [00:51<01:16, 14.52it/s]
 48%|████▊     | 1022/2129 [00:52<01:07, 16.35it/s]
 48%|████▊     | 1024/2129 [00:52<01:19, 13.93it/s]
 48%|████▊     | 1027/2129 [00:52<01:06, 16.64it/s]
 48%|████▊     | 1029/2129 [00:52<01:21, 13.47it/s]
 48%|████▊     | 1031/2129 [00:52<01:37, 11.21it/s]
 49%|████▊     | 1033/2129 [00:53<01:27, 12.46it/s]
 49%|████▉     | 1040/2129 [00:53<00:50, 21.59it/s]
 49%|████▉     | 1043/2129 [00:53<01:09, 15.58it/s]
 49%|████▉     | 1046/2129 [00:53<01:05, 16.42it/s]
 49%|████▉     | 1048/2129 [00:53<01:07, 16.01it/s]
 49%|████▉     | 1051/2129 [00:53<01:00, 17.68it/s]
 50%|████▉     | 1055/2129 [00:54<01:05, 16.44it/s]
 50%|████▉     | 1057/2129 [00:54<01:06, 16.16it/s]
 50%|████▉     | 1059/2129 [00:54<01:03, 16.80it/s]
 50%|████▉     | 1061/2129 [00:54<01:25, 12.45it/s]
 50%|████▉     | 1064/2129 [00:54<01:12, 14.62it/s]
 50%|█████     | 1066/2129 [00:54<01:09, 15.25it/s]
 50%|█████     | 1068/2129 [00:55<01:07, 15.77it/s]
 50%|█████     | 1070/2129 [00:55<01:30, 11.72it/s]
 50%|█████     | 1072/2129 [00:55<01:23, 12.67it/s]
 51%|█████     | 1078/2129 [00:55<00:48, 21.70it/s]
 51%|█████     | 1081/2129 [00:55<01:03, 16.44it/s]
 51%|█████     | 1084/2129 [00:56<01:04, 16.15it/s]
 51%|█████     | 1086/2129 [00:56<01:08, 15.33it/s]
 51%|█████     | 1088/2129 [00:56<01:04, 16.11it/s]
 51%|█████     | 1091/2129 [00:56<01:15, 13.77it/s]
 51%|█████▏    | 1094/2129 [00:56<01:11, 14.42it/s]
 52%|█████▏    | 1097/2129 [00:56<01:03, 16.27it/s]
 52%|█████▏    | 1103/2129 [00:57<00:57, 17.85it/s]
 52%|█████▏    | 1106/2129 [00:57<01:09, 14.80it/s]
 52%|█████▏    | 1108/2129 [00:57<01:07, 15.22it/s]
 52%|█████▏    | 1110/2129 [00:57<01:03, 15.99it/s]
 52%|█████▏    | 1112/2129 [00:58<01:25, 11.91it/s]
 52%|█████▏    | 1114/2129 [00:58<02:01,  8.38it/s]
 52%|█████▏    | 1116/2129 [00:58<02:05,  8.07it/s]
 53%|█████▎    | 1118/2129 [00:59<02:09,  7.83it/s]
 53%|█████▎    | 1120/2129 [00:59<02:12,  7.63it/s]
 53%|█████▎    | 1122/2129 [00:59<01:50,  9.11it/s]
 53%|█████▎    | 1129/2129 [00:59<00:55, 18.12it/s]
 53%|█████▎    | 1132/2129 [00:59<00:57, 17.43it/s]
 53%|█████▎    | 1135/2129 [00:59<00:56, 17.74it/s]
 53%|█████▎    | 1139/2129 [01:00<00:53, 18.39it/s]
 54%|█████▎    | 1142/2129 [01:00<00:51, 19.32it/s]
 54%|█████▍    | 1145/2129 [01:00<00:46, 21.39it/s]
 54%|█████▍    | 1148/2129 [01:00<00:57, 16.94it/s]
 54%|█████▍    | 1152/2129 [01:00<01:01, 15.93it/s]
 54%|█████▍    | 1154/2129 [01:01<00:58, 16.55it/s]
 54%|█████▍    | 1156/2129 [01:01<01:09, 14.09it/s]
 54%|█████▍    | 1159/2129 [01:01<01:18, 12.32it/s]
 55%|█████▍    | 1161/2129 [01:01<01:12, 13.33it/s]
 55%|█████▍    | 1166/2129 [01:01<00:48, 19.86it/s]
 55%|█████▌    | 1172/2129 [01:01<00:34, 27.59it/s]
 55%|█████▌    | 1179/2129 [01:01<00:26, 36.49it/s]
 56%|█████▌    | 1184/2129 [01:02<00:28, 33.03it/s]
 56%|█████▌    | 1188/2129 [01:02<00:29, 31.88it/s]
 56%|█████▌    | 1192/2129 [01:02<00:39, 23.56it/s]
 56%|█████▌    | 1195/2129 [01:02<00:48, 19.11it/s]
 56%|█████▋    | 1198/2129 [01:03<01:01, 15.23it/s]
 57%|█████▋    | 1204/2129 [01:03<00:42, 21.88it/s]
 57%|█████▋    | 1208/2129 [01:03<00:50, 18.10it/s]
 57%|█████▋    | 1211/2129 [01:03<00:57, 15.98it/s]
 57%|█████▋    | 1214/2129 [01:04<01:16, 11.91it/s]
 57%|█████▋    | 1216/2129 [01:04<01:10, 12.87it/s]
 57%|█████▋    | 1220/2129 [01:04<01:05, 13.87it/s]
 57%|█████▋    | 1223/2129 [01:04<00:55, 16.23it/s]
 58%|█████▊    | 1226/2129 [01:05<01:07, 13.33it/s]
 58%|█████▊    | 1228/2129 [01:05<01:23, 10.84it/s]
 58%|█████▊    | 1234/2129 [01:05<00:51, 17.53it/s]
 58%|█████▊    | 1240/2129 [01:05<00:36, 24.33it/s]
 58%|█████▊    | 1245/2129 [01:05<00:40, 21.73it/s]
 59%|█████▊    | 1249/2129 [01:06<00:48, 18.08it/s]
 59%|█████▉    | 1254/2129 [01:06<00:39, 22.21it/s]
 59%|█████▉    | 1258/2129 [01:06<00:48, 18.01it/s]
 59%|█████▉    | 1261/2129 [01:06<00:52, 16.53it/s]
 59%|█████▉    | 1264/2129 [01:07<00:52, 16.59it/s]
 60%|█████▉    | 1270/2129 [01:07<00:36, 23.24it/s]
 60%|█████▉    | 1275/2129 [01:07<00:42, 20.24it/s]
 60%|██████    | 1278/2129 [01:07<00:44, 19.18it/s]
 60%|██████    | 1281/2129 [01:07<00:43, 19.63it/s]
 60%|██████    | 1284/2129 [01:08<00:54, 15.58it/s]
 60%|██████    | 1287/2129 [01:08<00:59, 14.09it/s]
 61%|██████    | 1289/2129 [01:08<01:18, 10.70it/s]
 61%|██████    | 1292/2129 [01:09<01:19, 10.48it/s]
 61%|██████    | 1295/2129 [01:09<01:06, 12.50it/s]
 61%|██████    | 1297/2129 [01:09<01:10, 11.76it/s]
 61%|██████    | 1300/2129 [01:09<00:56, 14.55it/s]
 61%|██████    | 1304/2129 [01:09<00:53, 15.31it/s]
 61%|██████▏   | 1306/2129 [01:10<01:05, 12.49it/s]
 61%|██████▏   | 1308/2129 [01:10<01:17, 10.54it/s]
 62%|██████▏   | 1311/2129 [01:10<01:20, 10.20it/s]
 62%|██████▏   | 1313/2129 [01:11<01:37,  8.33it/s]
 62%|██████▏   | 1316/2129 [01:11<01:17, 10.56it/s]
 62%|██████▏   | 1318/2129 [01:11<01:18, 10.27it/s]
 62%|██████▏   | 1320/2129 [01:11<01:09, 11.66it/s]
 62%|██████▏   | 1322/2129 [01:11<01:35,  8.49it/s]
 62%|██████▏   | 1324/2129 [01:12<01:34,  8.56it/s]
 62%|██████▏   | 1326/2129 [01:12<01:36,  8.28it/s]
 62%|██████▏   | 1328/2129 [01:12<01:48,  7.39it/s]
 62%|██████▏   | 1330/2129 [01:12<01:29,  8.95it/s]
 63%|██████▎   | 1332/2129 [01:13<01:29,  8.90it/s]
 63%|██████▎   | 1336/2129 [01:13<00:58, 13.62it/s]
 63%|██████▎   | 1339/2129 [01:13<00:57, 13.64it/s]
 63%|██████▎   | 1342/2129 [01:13<01:02, 12.67it/s]
 63%|██████▎   | 1346/2129 [01:13<00:47, 16.56it/s]
 64%|██████▎   | 1352/2129 [01:14<00:42, 18.44it/s]
 64%|██████▎   | 1355/2129 [01:14<00:39, 19.50it/s]
 64%|██████▍   | 1358/2129 [01:14<00:46, 16.45it/s]
 64%|██████▍   | 1362/2129 [01:14<00:38, 20.03it/s]
 64%|██████▍   | 1369/2129 [01:14<00:26, 29.04it/s]
 64%|██████▍   | 1373/2129 [01:15<00:41, 18.01it/s]
 65%|██████▍   | 1376/2129 [01:15<00:38, 19.69it/s]
 65%|██████▍   | 1379/2129 [01:15<00:48, 15.54it/s]
 65%|██████▍   | 1383/2129 [01:15<00:47, 15.78it/s]
 65%|██████▌   | 1386/2129 [01:15<00:43, 16.99it/s]
 65%|██████▌   | 1389/2129 [01:16<00:57, 12.98it/s]
 65%|██████▌   | 1391/2129 [01:16<00:53, 13.86it/s]
 65%|██████▌   | 1393/2129 [01:16<01:07, 10.98it/s]
 66%|██████▌   | 1395/2129 [01:16<01:12, 10.11it/s]
 66%|██████▌   | 1398/2129 [01:17<00:55, 13.07it/s]
 66%|██████▌   | 1400/2129 [01:17<01:02, 11.59it/s]
 66%|██████▌   | 1404/2129 [01:17<00:44, 16.12it/s]
 66%|██████▌   | 1407/2129 [01:17<00:53, 13.42it/s]
 66%|██████▌   | 1409/2129 [01:17<00:59, 12.05it/s]
 66%|██████▋   | 1412/2129 [01:18<00:48, 14.66it/s]
 67%|██████▋   | 1418/2129 [01:18<00:31, 22.90it/s]
 67%|██████▋   | 1426/2129 [01:18<00:20, 34.31it/s]
 67%|██████▋   | 1431/2129 [01:18<00:33, 20.84it/s]
 67%|██████▋   | 1435/2129 [01:18<00:35, 19.30it/s]
 68%|██████▊   | 1438/2129 [01:19<00:36, 18.72it/s]
 68%|██████▊   | 1441/2129 [01:19<00:43, 15.91it/s]
 68%|██████▊   | 1444/2129 [01:19<00:38, 18.00it/s]
 68%|██████▊   | 1448/2129 [01:19<00:39, 17.33it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 341.32it/s]

[[np.int64(0), False, 11], [np.int64(1), False, 12], [np.int64(2), False, 5], [np.int64(3), False, 9], [np.int64(4), False, 9], [np.int64(6), False, 7], [np.int64(7), False, 0], [np.int64(8), False, 11], [np.int64(9), False, 12], [np.int64(10), False, 1], [np.int64(12), False, 5], [np.int64(13), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6014, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [04:24<1:19:42, 32.10s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [04:24<55:32, 22.52s/it]

tensor(12.3001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7855, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0628, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [04:25<27:00, 11.10s/it]

tensor(12.2950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4010, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [04:25<09:15,  3.89s/it]

tensor(12.2964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4853, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5225, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [04:25<06:31,  2.76s/it]

tensor(12.2991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5434, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5410, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [04:25<02:22,  1.02s/it]

tensor(12.2975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5548, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5834, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [04:26<01:17,  1.77it/s]

tensor(12.2844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0366, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6507, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0385, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7321, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [04:26<00:58,  2.32it/s]

tensor(12.2624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0404, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8053, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0415, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8662, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [04:26<00:30,  4.39it/s]

tensor(12.2398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0417, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2317, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0404, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9186, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [04:26<00:25,  5.10it/s]

tensor(12.2254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0375, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9477, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2192, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9978, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [04:27<00:19,  6.78it/s]

tensor(12.2116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0322, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [04:27<00:17,  7.44it/s]

tensor(12.1979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0107, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0652, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [04:27<00:16,  7.77it/s]

tensor(12.1947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1016, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1299, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [04:27<00:15,  8.07it/s]

tensor(12.1920, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1535, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1762, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [04:28<00:14,  8.17it/s]

tensor(12.1755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2055, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2076, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [04:28<00:14,  8.18it/s]

tensor(12.1571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2318, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2453, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [04:28<00:14,  8.20it/s]

tensor(12.1420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2594, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2686, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [04:28<00:13,  8.25it/s]

tensor(12.1334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2939, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3089, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [04:28<00:13,  8.23it/s]

tensor(12.1281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3254, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3417, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [04:29<00:13,  8.20it/s]

tensor(12.1207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3750, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [04:29<00:13,  8.21it/s]

tensor(12.1087, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3882, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4074, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [04:29<00:13,  8.22it/s]

tensor(12.1003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4217, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4294, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [04:29<00:12,  8.22it/s]

tensor(12.0920, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4427, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4557, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [04:30<00:12,  8.09it/s]

tensor(12.0826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4638, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4722, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [04:30<00:12,  8.06it/s]

tensor(12.0760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4491, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0740, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4607, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [04:30<00:12,  8.02it/s]

tensor(12.0714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4721, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([192,  64, 145, 178, 236, 113, 197, 233,  96, 103, 321, 125,  49,  77])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 5/2129 [00:00<00:47, 44.53it/s]
  0%|          | 10/2129 [00:00<00:54, 39.10it/s]
  1%|          | 15/2129 [00:00<00:57, 36.81it/s]
  1%|          | 19/2129 [00:00<01:04, 32.57it/s]
  1%|          | 24/2129 [00:00<01:03, 33.18it/s]
  1%|▏         | 28/2129 [00:00<01:01, 33.92it/s]
  2%|▏         | 32/2129 [00:00<01:00, 34.89it/s]
  2%|▏         | 39/2129 [00:01<00:48, 42.85it/s]
  2%|▏         | 46/2129 [00:01<00:41, 50.00it/s]
  2%|▏         | 53/2129 [00:01<00:37, 54.71it/s]
  3%|▎         | 59/2129 [00:01<00:39, 52.73it/s]
  3%|▎         | 65/2129 [00:01<00:44, 46.33it/s]
  3%|▎         | 70/2129 [00:01<00:44, 46.44it/s]
  4%|▎         | 76/2129 [00:01<00:41, 49.18it/s]
  4%|▍         | 82/2129 [00:01<00:41, 49.88it/s]
  4%|▍         | 88/2129 [00:01<00:39, 52.25it/s]
  4%|▍         | 95/2129 [00:02<00:36, 55.72it/s]
  5%|▍         | 101/2129 [00:02<00:41, 48.93it/s]
  5%|▌         | 107/2129 [00:02<00:43, 46.87it/s]
  5%|▌         | 114/2129 [00:02<00:38, 51.70it/s]
  6%|▌         | 120/2129 [00:02<00:38, 52.60it/s]
  6%|▌         | 127/2129 [00:02<00:35, 56.32it/s]
  6%|▋         | 134/2129 [00:02<00:34, 58.25it/s]
  7%|▋         | 142/2129 [00:02<00:31, 63.77it/s]
  7%|▋         | 150/2129 [00:03<00:29, 66.03it/s]
  7%|▋         | 157/2129 [00:03<00:39, 49.88it/s]
  8%|▊         | 163/2129 [00:03<00:51, 38.30it/s]
  8%|▊         | 168/2129 [00:03<00:50, 38.64it/s]
  8%|▊         | 173/2129 [00:03<00:48, 40.74it/s]
  8%|▊         | 178/2129 [00:03<00:48, 40.25it/s]
  9%|▊         | 183/2129 [00:04<00:55, 34.92it/s]
  9%|▉         | 187/2129 [00:04<01:20, 23.99it/s]
  9%|▉         | 191/2129 [00:04<01:31, 21.15it/s]
  9%|▉         | 195/2129 [00:04<01:21, 23.76it/s]
  9%|▉         | 202/2129 [00:04<01:00, 31.93it/s]
 10%|▉         | 208/2129 [00:04<00:51, 37.29it/s]
 10%|█         | 213/2129 [00:05<01:05, 29.12it/s]
 10%|█         | 217/2129 [00:05<01:25, 22.37it/s]
 10%|█         | 223/2129 [00:05<01:24, 22.43it/s]
 11%|█         | 227/2129 [00:05<01:17, 24.46it/s]
 11%|█         | 233/2129 [00:06<01:24, 22.35it/s]
 11%|█         | 236/2129 [00:06<01:43, 18.26it/s]
 11%|█         | 239/2129 [00:06<01:55, 16.37it/s]
 11%|█▏        | 242/2129 [00:06<01:44, 18.12it/s]
 12%|█▏        | 246/2129 [00:07<01:48, 17.32it/s]
 12%|█▏        | 248/2129 [00:07<01:46, 17.74it/s]
 12%|█▏        | 252/2129 [00:07<01:51, 16.89it/s]
 12%|█▏        | 255/2129 [00:07<01:40, 18.64it/s]
 12%|█▏        | 258/2129 [00:07<01:48, 17.19it/s]
 12%|█▏        | 261/2129 [00:08<02:04, 15.04it/s]
 12%|█▏        | 264/2129 [00:08<01:52, 16.53it/s]
 13%|█▎        | 267/2129 [00:08<01:42, 18.20it/s]
 13%|█▎        | 274/2129 [00:08<01:06, 28.05it/s]
 13%|█▎        | 278/2129 [00:08<01:05, 28.29it/s]
 13%|█▎        | 282/2129 [00:08<01:02, 29.43it/s]
 13%|█▎        | 287/2129 [00:08<01:07, 27.45it/s]
 14%|█▎        | 290/2129 [00:09<01:09, 26.63it/s]
 14%|█▍        | 296/2129 [00:09<00:54, 33.83it/s]
 14%|█▍        | 300/2129 [00:09<00:57, 31.70it/s]
 14%|█▍        | 304/2129 [00:09<01:10, 25.95it/s]
 14%|█▍        | 307/2129 [00:09<01:25, 21.31it/s]
 15%|█▍        | 311/2129 [00:09<01:14, 24.57it/s]
 15%|█▍        | 314/2129 [00:10<01:56, 15.52it/s]
 15%|█▍        | 317/2129 [00:10<01:52, 16.16it/s]
 15%|█▌        | 320/2129 [00:10<01:42, 17.62it/s]
 15%|█▌        | 324/2129 [00:10<01:39, 18.07it/s]
 15%|█▌        | 327/2129 [00:10<01:33, 19.36it/s]
 16%|█▌        | 330/2129 [00:11<01:58, 15.25it/s]
 16%|█▌        | 334/2129 [00:11<01:54, 15.69it/s]
 16%|█▌        | 337/2129 [00:11<02:05, 14.24it/s]
 16%|█▌        | 340/2129 [00:11<01:51, 15.98it/s]
 16%|█▌        | 342/2129 [00:12<02:10, 13.71it/s]
 16%|█▌        | 344/2129 [00:12<02:35, 11.49it/s]
 16%|█▋        | 348/2129 [00:12<01:51, 15.91it/s]
 16%|█▋        | 351/2129 [00:12<02:34, 11.51it/s]
 17%|█▋        | 354/2129 [00:12<02:06, 14.04it/s]
 17%|█▋        | 357/2129 [00:13<02:16, 13.01it/s]
 17%|█▋        | 359/2129 [00:13<02:45, 10.72it/s]
 17%|█▋        | 361/2129 [00:13<03:04,  9.57it/s]
 17%|█▋        | 363/2129 [00:14<03:15,  9.03it/s]
 17%|█▋        | 368/2129 [00:14<02:00, 14.62it/s]
 18%|█▊        | 373/2129 [00:14<01:52, 15.63it/s]
 18%|█▊        | 376/2129 [00:14<02:01, 14.40it/s]
 18%|█▊        | 378/2129 [00:14<01:56, 15.04it/s]
 18%|█▊        | 380/2129 [00:15<02:09, 13.46it/s]
 18%|█▊        | 383/2129 [00:15<01:51, 15.69it/s]
 18%|█▊        | 386/2129 [00:15<02:04, 13.96it/s]
 18%|█▊        | 388/2129 [00:15<01:58, 14.68it/s]
 18%|█▊        | 390/2129 [00:15<01:51, 15.66it/s]
 19%|█▊        | 395/2129 [00:15<01:16, 22.67it/s]
 19%|█▉        | 400/2129 [00:15<01:03, 27.16it/s]
 19%|█▉        | 405/2129 [00:15<00:53, 32.50it/s]
 19%|█▉        | 410/2129 [00:16<00:50, 34.09it/s]
 19%|█▉        | 415/2129 [00:16<00:46, 36.68it/s]
 20%|█▉        | 420/2129 [00:16<00:43, 39.39it/s]
 20%|█▉        | 425/2129 [00:16<00:41, 41.18it/s]
 20%|██        | 431/2129 [00:16<00:37, 45.02it/s]
 20%|██        | 436/2129 [00:17<01:22, 20.59it/s]
 21%|██        | 440/2129 [00:17<01:35, 17.73it/s]
 21%|██        | 443/2129 [00:17<01:28, 19.15it/s]
 21%|██        | 449/2129 [00:17<01:05, 25.72it/s]
 21%|██▏       | 455/2129 [00:17<00:52, 31.70it/s]
 22%|██▏       | 460/2129 [00:18<01:02, 26.83it/s]
 22%|██▏       | 464/2129 [00:18<01:04, 25.82it/s]
 22%|██▏       | 468/2129 [00:18<01:37, 17.07it/s]
 22%|██▏       | 471/2129 [00:18<01:55, 14.36it/s]
 22%|██▏       | 474/2129 [00:19<01:45, 15.67it/s]
 22%|██▏       | 477/2129 [00:19<01:47, 15.36it/s]
 22%|██▏       | 479/2129 [00:19<02:09, 12.75it/s]
 23%|██▎       | 483/2129 [00:19<02:04, 13.27it/s]
 23%|██▎       | 485/2129 [00:20<02:17, 12.00it/s]
 23%|██▎       | 487/2129 [00:20<02:28, 11.06it/s]
 23%|██▎       | 490/2129 [00:20<02:01, 13.54it/s]
 23%|██▎       | 497/2129 [00:20<01:10, 23.03it/s]
 24%|██▎       | 501/2129 [00:20<01:25, 18.97it/s]
 24%|██▎       | 504/2129 [00:20<01:26, 18.70it/s]
 24%|██▍       | 507/2129 [00:21<01:21, 19.88it/s]
 24%|██▍       | 510/2129 [00:21<01:48, 14.90it/s]
 24%|██▍       | 515/2129 [00:21<01:42, 15.69it/s]
 24%|██▍       | 517/2129 [00:22<02:04, 12.92it/s]
 24%|██▍       | 520/2129 [00:22<01:54, 14.04it/s]
 25%|██▍       | 522/2129 [00:22<02:49,  9.45it/s]
 25%|██▍       | 524/2129 [00:22<02:40, 10.01it/s]
 25%|██▍       | 526/2129 [00:23<02:39, 10.06it/s]
 25%|██▍       | 528/2129 [00:23<02:44,  9.73it/s]
 25%|██▍       | 530/2129 [00:23<02:35, 10.30it/s]
 25%|██▌       | 533/2129 [00:23<01:58, 13.48it/s]
 25%|██▌       | 536/2129 [00:23<01:49, 14.57it/s]
 25%|██▌       | 538/2129 [00:23<01:47, 14.82it/s]
 25%|██▌       | 540/2129 [00:23<01:50, 14.35it/s]
 26%|██▌       | 543/2129 [00:24<01:56, 13.62it/s]
 26%|██▌       | 546/2129 [00:24<01:44, 15.14it/s]
 26%|██▌       | 552/2129 [00:24<01:06, 23.82it/s]
 26%|██▌       | 555/2129 [00:24<01:03, 24.90it/s]
 26%|██▌       | 558/2129 [00:24<01:30, 17.28it/s]
 26%|██▋       | 561/2129 [00:25<01:29, 17.60it/s]
 27%|██▋       | 567/2129 [00:25<01:23, 18.61it/s]
 27%|██▋       | 570/2129 [00:25<01:16, 20.46it/s]
 27%|██▋       | 573/2129 [00:25<01:44, 14.87it/s]
 27%|██▋       | 579/2129 [00:25<01:11, 21.76it/s]
 27%|██▋       | 583/2129 [00:26<01:12, 21.45it/s]
 28%|██▊       | 586/2129 [00:26<01:32, 16.66it/s]
 28%|██▊       | 589/2129 [00:26<01:47, 14.39it/s]
 28%|██▊       | 591/2129 [00:26<01:56, 13.23it/s]
 28%|██▊       | 593/2129 [00:27<01:54, 13.45it/s]
 28%|██▊       | 597/2129 [00:27<01:30, 16.93it/s]
 28%|██▊       | 599/2129 [00:27<01:36, 15.84it/s]
 28%|██▊       | 602/2129 [00:27<01:23, 18.24it/s]
 29%|██▊       | 608/2129 [00:27<00:57, 26.39it/s]
 29%|██▊       | 612/2129 [00:27<01:02, 24.14it/s]
 29%|██▉       | 616/2129 [00:27<00:56, 26.81it/s]
 29%|██▉       | 622/2129 [00:27<00:44, 33.51it/s]
 29%|██▉       | 626/2129 [00:28<00:52, 28.81it/s]
 30%|██▉       | 630/2129 [00:28<01:14, 20.21it/s]
 30%|██▉       | 633/2129 [00:28<01:08, 21.83it/s]
 30%|██▉       | 636/2129 [00:28<01:05, 22.73it/s]
 30%|███       | 639/2129 [00:28<01:06, 22.39it/s]
 30%|███       | 642/2129 [00:29<01:19, 18.61it/s]
 30%|███       | 645/2129 [00:29<01:14, 20.05it/s]
 30%|███       | 648/2129 [00:29<01:09, 21.33it/s]
 31%|███       | 652/2129 [00:29<00:59, 25.02it/s]
 31%|███       | 655/2129 [00:29<01:14, 19.73it/s]
 31%|███       | 658/2129 [00:29<01:22, 17.91it/s]
 31%|███       | 661/2129 [00:30<01:18, 18.65it/s]
 31%|███       | 664/2129 [00:30<01:49, 13.40it/s]
 31%|███▏      | 667/2129 [00:30<01:31, 15.93it/s]
 32%|███▏      | 672/2129 [00:30<01:24, 17.25it/s]
 32%|███▏      | 675/2129 [00:30<01:22, 17.58it/s]
 32%|███▏      | 678/2129 [00:31<01:16, 19.02it/s]
 32%|███▏      | 681/2129 [00:31<01:10, 20.65it/s]
 32%|███▏      | 685/2129 [00:31<01:26, 16.74it/s]
 32%|███▏      | 688/2129 [00:31<01:43, 13.92it/s]
 32%|███▏      | 690/2129 [00:32<01:51, 12.95it/s]
 33%|███▎      | 692/2129 [00:32<01:43, 13.86it/s]
 33%|███▎      | 694/2129 [00:32<01:59, 11.97it/s]
 33%|███▎      | 696/2129 [00:32<02:17, 10.44it/s]
 33%|███▎      | 699/2129 [00:32<01:45, 13.51it/s]
 33%|███▎      | 705/2129 [00:32<01:15, 18.89it/s]
 33%|███▎      | 708/2129 [00:33<01:26, 16.35it/s]
 33%|███▎      | 710/2129 [00:33<01:29, 15.89it/s]
 33%|███▎      | 712/2129 [00:33<01:49, 12.94it/s]
 34%|███▎      | 714/2129 [00:33<02:14, 10.49it/s]
 34%|███▎      | 718/2129 [00:33<01:34, 14.92it/s]
 34%|███▍      | 720/2129 [00:34<01:32, 15.15it/s]
 34%|███▍      | 722/2129 [00:34<01:57, 11.96it/s]
 34%|███▍      | 724/2129 [00:34<02:46,  8.42it/s]
 34%|███▍      | 726/2129 [00:35<02:38,  8.86it/s]
 34%|███▍      | 728/2129 [00:35<03:17,  7.11it/s]
 34%|███▍      | 730/2129 [00:35<02:41,  8.67it/s]
 34%|███▍      | 733/2129 [00:35<02:29,  9.32it/s]
 35%|███▍      | 735/2129 [00:35<02:14, 10.33it/s]
 35%|███▍      | 738/2129 [00:36<01:45, 13.21it/s]
 35%|███▍      | 740/2129 [00:36<02:00, 11.55it/s]
 35%|███▍      | 743/2129 [00:36<01:36, 14.39it/s]
 35%|███▌      | 746/2129 [00:36<01:19, 17.34it/s]
 35%|███▌      | 751/2129 [00:36<01:19, 17.29it/s]
 35%|███▌      | 754/2129 [00:37<01:31, 14.97it/s]
 36%|███▌      | 757/2129 [00:37<01:18, 17.42it/s]
 36%|███▌      | 762/2129 [00:37<01:16, 17.95it/s]
 36%|███▌      | 765/2129 [00:37<01:30, 15.12it/s]
 36%|███▌      | 767/2129 [00:38<01:46, 12.81it/s]
 36%|███▌      | 769/2129 [00:38<02:00, 11.28it/s]
 36%|███▋      | 772/2129 [00:38<01:37, 13.92it/s]
 36%|███▋      | 774/2129 [00:38<01:48, 12.51it/s]
 36%|███▋      | 776/2129 [00:38<02:19,  9.72it/s]
 37%|███▋      | 778/2129 [00:39<02:01, 11.11it/s]
 37%|███▋      | 780/2129 [00:39<02:11, 10.26it/s]
 37%|███▋      | 782/2129 [00:39<01:57, 11.43it/s]
 37%|███▋      | 785/2129 [00:39<01:58, 11.30it/s]
 37%|███▋      | 787/2129 [00:39<02:15,  9.89it/s]
 37%|███▋      | 789/2129 [00:40<02:00, 11.13it/s]
 37%|███▋      | 796/2129 [00:40<01:23, 16.01it/s]
 37%|███▋      | 798/2129 [00:40<01:43, 12.86it/s]
 38%|███▊      | 801/2129 [00:40<01:28, 15.02it/s]
 38%|███▊      | 808/2129 [00:40<00:54, 24.12it/s]
 38%|███▊      | 812/2129 [00:41<01:05, 20.16it/s]
 38%|███▊      | 818/2129 [00:41<00:49, 26.66it/s]
 39%|███▊      | 822/2129 [00:41<01:05, 20.06it/s]
 39%|███▉      | 829/2129 [00:41<00:47, 27.57it/s]
 39%|███▉      | 833/2129 [00:41<00:45, 28.20it/s]
 39%|███▉      | 837/2129 [00:41<00:43, 30.00it/s]
 40%|███▉      | 842/2129 [00:42<00:43, 29.39it/s]
 40%|███▉      | 846/2129 [00:42<01:04, 19.89it/s]
 40%|███▉      | 849/2129 [00:42<01:07, 19.06it/s]
 40%|████      | 852/2129 [00:42<01:08, 18.54it/s]
 40%|████      | 855/2129 [00:43<01:34, 13.48it/s]
 40%|████      | 858/2129 [00:43<01:26, 14.63it/s]
 40%|████      | 860/2129 [00:43<01:33, 13.53it/s]
 40%|████      | 862/2129 [00:43<01:31, 13.83it/s]
 41%|████      | 867/2129 [00:43<01:03, 19.83it/s]
 41%|████      | 872/2129 [00:43<00:48, 25.90it/s]
 41%|████      | 876/2129 [00:44<01:05, 19.09it/s]
 41%|████▏     | 881/2129 [00:44<01:06, 18.73it/s]
 42%|████▏     | 884/2129 [00:44<01:06, 18.73it/s]
 42%|████▏     | 887/2129 [00:45<01:39, 12.51it/s]
 42%|████▏     | 889/2129 [00:45<01:36, 12.85it/s]
 42%|████▏     | 894/2129 [00:45<01:08, 17.99it/s]
 42%|████▏     | 898/2129 [00:45<01:13, 16.69it/s]
 42%|████▏     | 901/2129 [00:45<01:07, 18.09it/s]
 42%|████▏     | 904/2129 [00:46<01:39, 12.30it/s]
 43%|████▎     | 906/2129 [00:46<01:45, 11.59it/s]
 43%|████▎     | 908/2129 [00:46<01:47, 11.40it/s]
 43%|████▎     | 910/2129 [00:46<01:43, 11.77it/s]
 43%|████▎     | 912/2129 [00:47<02:03,  9.88it/s]
 43%|████▎     | 914/2129 [00:47<02:27,  8.23it/s]
 43%|████▎     | 916/2129 [00:47<02:08,  9.40it/s]
 43%|████▎     | 921/2129 [00:47<01:18, 15.34it/s]
 43%|████▎     | 924/2129 [00:47<01:08, 17.58it/s]
 44%|████▎     | 928/2129 [00:48<01:09, 17.30it/s]
 44%|████▎     | 931/2129 [00:48<01:05, 18.27it/s]
 44%|████▍     | 936/2129 [00:48<01:01, 19.45it/s]
 44%|████▍     | 939/2129 [00:48<01:19, 14.88it/s]
 44%|████▍     | 942/2129 [00:48<01:10, 16.73it/s]
 44%|████▍     | 944/2129 [00:49<01:08, 17.18it/s]
 44%|████▍     | 946/2129 [00:49<01:13, 16.11it/s]
 45%|████▍     | 949/2129 [00:49<01:07, 17.56it/s]
 45%|████▍     | 951/2129 [00:49<01:05, 17.87it/s]
 45%|████▍     | 953/2129 [00:49<01:04, 18.31it/s]
 45%|████▍     | 955/2129 [00:49<01:05, 17.79it/s]
 45%|████▍     | 957/2129 [00:49<01:08, 17.08it/s]
 45%|████▌     | 959/2129 [00:50<01:31, 12.77it/s]
 45%|████▌     | 961/2129 [00:50<02:06,  9.24it/s]
 45%|████▌     | 963/2129 [00:50<02:12,  8.78it/s]
 45%|████▌     | 965/2129 [00:50<01:53, 10.29it/s]
 45%|████▌     | 967/2129 [00:50<01:36, 11.98it/s]
 46%|████▌     | 969/2129 [00:51<01:30, 12.81it/s]
 46%|████▌     | 973/2129 [00:51<01:23, 13.82it/s]
 46%|████▌     | 975/2129 [00:51<01:36, 11.94it/s]
 46%|████▌     | 978/2129 [00:51<01:18, 14.59it/s]
 46%|████▌     | 981/2129 [00:51<01:24, 13.61it/s]
 46%|████▌     | 983/2129 [00:51<01:17, 14.73it/s]
 46%|████▋     | 988/2129 [00:52<01:07, 16.92it/s]
 47%|████▋     | 991/2129 [00:52<01:05, 17.26it/s]
 47%|████▋     | 993/2129 [00:52<01:21, 13.94it/s]
 47%|████▋     | 995/2129 [00:52<01:24, 13.45it/s]
 47%|████▋     | 997/2129 [00:52<01:20, 14.09it/s]
 47%|████▋     | 1001/2129 [00:53<01:04, 17.35it/s]
 47%|████▋     | 1003/2129 [00:53<01:28, 12.79it/s]
 47%|████▋     | 1006/2129 [00:53<01:11, 15.61it/s]
 47%|████▋     | 1010/2129 [00:53<01:08, 16.39it/s]
 48%|████▊     | 1012/2129 [00:53<01:23, 13.34it/s]
 48%|████▊     | 1014/2129 [00:54<01:39, 11.22it/s]
 48%|████▊     | 1016/2129 [00:54<01:48, 10.27it/s]
 48%|████▊     | 1019/2129 [00:54<01:50, 10.09it/s]
 48%|████▊     | 1021/2129 [00:54<01:36, 11.48it/s]
 48%|████▊     | 1023/2129 [00:55<01:47, 10.30it/s]
 48%|████▊     | 1025/2129 [00:55<01:55,  9.60it/s]
 48%|████▊     | 1028/2129 [00:55<01:49, 10.09it/s]
 48%|████▊     | 1030/2129 [00:55<01:55,  9.50it/s]
 49%|████▊     | 1033/2129 [00:56<01:30, 12.09it/s]
 49%|████▉     | 1040/2129 [00:56<00:50, 21.63it/s]
 49%|████▉     | 1045/2129 [00:56<00:39, 27.11it/s]
 49%|████▉     | 1049/2129 [00:56<00:50, 21.31it/s]
 50%|████▉     | 1054/2129 [00:56<00:41, 26.18it/s]
 50%|████▉     | 1058/2129 [00:57<01:18, 13.60it/s]
 50%|████▉     | 1061/2129 [00:57<01:25, 12.49it/s]
 50%|████▉     | 1064/2129 [00:57<01:25, 12.45it/s]
 50%|█████     | 1066/2129 [00:57<01:21, 12.98it/s]
 50%|█████     | 1068/2129 [00:58<01:29, 11.83it/s]
 50%|█████     | 1070/2129 [00:58<01:41, 10.41it/s]
 50%|█████     | 1072/2129 [00:58<01:58,  8.89it/s]
 50%|█████     | 1074/2129 [00:58<01:42, 10.32it/s]
 51%|█████     | 1080/2129 [00:59<01:13, 14.29it/s]
 51%|█████     | 1082/2129 [00:59<01:10, 14.94it/s]
 51%|█████     | 1085/2129 [00:59<01:14, 13.98it/s]
 51%|█████     | 1088/2129 [00:59<01:05, 15.87it/s]
 51%|█████     | 1091/2129 [00:59<01:08, 15.08it/s]
 51%|█████▏    | 1094/2129 [01:00<01:17, 13.31it/s]
 51%|█████▏    | 1096/2129 [01:00<01:14, 13.95it/s]
 52%|█████▏    | 1099/2129 [01:00<01:12, 14.16it/s]
 52%|█████▏    | 1101/2129 [01:00<01:08, 15.08it/s]
 52%|█████▏    | 1103/2129 [01:00<01:19, 12.94it/s]
 52%|█████▏    | 1106/2129 [01:01<01:24, 12.04it/s]
 52%|█████▏    | 1108/2129 [01:01<01:34, 10.77it/s]
 52%|█████▏    | 1110/2129 [01:01<01:26, 11.76it/s]
 52%|█████▏    | 1112/2129 [01:01<01:35, 10.69it/s]
 52%|█████▏    | 1114/2129 [01:02<02:03,  8.25it/s]
 52%|█████▏    | 1115/2129 [01:02<02:01,  8.33it/s]
 53%|█████▎    | 1118/2129 [01:02<01:46,  9.48it/s]
 53%|█████▎    | 1120/2129 [01:02<01:49,  9.19it/s]
 53%|█████▎    | 1123/2129 [01:02<01:47,  9.34it/s]
 53%|█████▎    | 1125/2129 [01:03<01:34, 10.64it/s]
 53%|█████▎    | 1127/2129 [01:03<02:12,  7.59it/s]
 53%|█████▎    | 1128/2129 [01:03<02:08,  7.76it/s]
 53%|█████▎    | 1130/2129 [01:03<01:45,  9.44it/s]
 53%|█████▎    | 1132/2129 [01:04<01:53,  8.78it/s]
 53%|█████▎    | 1134/2129 [01:04<01:33, 10.62it/s]
 53%|█████▎    | 1137/2129 [01:04<01:10, 14.17it/s]
 53%|█████▎    | 1139/2129 [01:04<01:24, 11.73it/s]
 54%|█████▎    | 1141/2129 [01:04<01:14, 13.25it/s]
 54%|█████▎    | 1143/2129 [01:04<01:07, 14.61it/s]
 54%|█████▍    | 1146/2129 [01:04<00:57, 17.22it/s]
 54%|█████▍    | 1150/2129 [01:04<00:45, 21.75it/s]
 54%|█████▍    | 1153/2129 [01:05<01:09, 14.03it/s]
 54%|█████▍    | 1156/2129 [01:05<01:16, 12.73it/s]
 54%|█████▍    | 1158/2129 [01:05<01:40,  9.66it/s]
 54%|█████▍    | 1160/2129 [01:06<01:50,  8.74it/s]
 55%|█████▍    | 1163/2129 [01:06<01:28, 10.92it/s]
 55%|█████▍    | 1169/2129 [01:06<00:53, 18.01it/s]
 55%|█████▌    | 1174/2129 [01:06<00:50, 18.79it/s]
 55%|█████▌    | 1177/2129 [01:07<00:56, 16.97it/s]
 55%|█████▌    | 1181/2129 [01:07<00:52, 17.91it/s]
 56%|█████▌    | 1184/2129 [01:07<00:51, 18.20it/s]
 56%|█████▌    | 1187/2129 [01:07<01:04, 14.61it/s]
 56%|█████▌    | 1190/2129 [01:07<01:07, 14.00it/s]
 56%|█████▌    | 1193/2129 [01:08<00:59, 15.65it/s]
 56%|█████▌    | 1195/2129 [01:08<01:12, 12.93it/s]
 56%|█████▌    | 1197/2129 [01:08<01:17, 12.00it/s]
 56%|█████▋    | 1200/2129 [01:08<01:02, 14.89it/s]
 57%|█████▋    | 1206/2129 [01:08<00:51, 17.94it/s]
 57%|█████▋    | 1208/2129 [01:09<00:50, 18.26it/s]
 57%|█████▋    | 1211/2129 [01:09<00:57, 16.02it/s]
 57%|█████▋    | 1213/2129 [01:09<01:08, 13.35it/s]
 57%|█████▋    | 1217/2129 [01:09<00:52, 17.46it/s]
 57%|█████▋    | 1220/2129 [01:09<00:56, 15.95it/s]
 57%|█████▋    | 1223/2129 [01:09<00:51, 17.56it/s]
 58%|█████▊    | 1225/2129 [01:10<01:03, 14.18it/s]
 58%|█████▊    | 1228/2129 [01:10<00:53, 16.96it/s]
 58%|█████▊    | 1231/2129 [01:10<00:56, 16.02it/s]
 58%|█████▊    | 1234/2129 [01:10<00:50, 17.87it/s]
 58%|█████▊    | 1240/2129 [01:10<00:34, 25.76it/s]
 58%|█████▊    | 1243/2129 [01:11<00:53, 16.52it/s]
 59%|█████▊    | 1246/2129 [01:11<00:49, 17.82it/s]
 59%|█████▊    | 1249/2129 [01:11<00:59, 14.80it/s]
 59%|█████▉    | 1252/2129 [01:11<00:50, 17.23it/s]
 59%|█████▉    | 1256/2129 [01:11<00:55, 15.68it/s]
 59%|█████▉    | 1258/2129 [01:12<00:55, 15.68it/s]
 59%|█████▉    | 1260/2129 [01:12<01:07, 12.83it/s]
 59%|█████▉    | 1262/2129 [01:12<01:02, 13.78it/s]
 59%|█████▉    | 1264/2129 [01:12<01:13, 11.70it/s]
 60%|█████▉    | 1267/2129 [01:12<00:59, 14.57it/s]
 60%|█████▉    | 1270/2129 [01:13<01:01, 14.02it/s]
 60%|█████▉    | 1273/2129 [01:13<00:52, 16.23it/s]
 60%|█████▉    | 1275/2129 [01:13<01:21, 10.45it/s]
 60%|█████▉    | 1277/2129 [01:13<01:14, 11.41it/s]
 60%|██████    | 1279/2129 [01:13<01:13, 11.57it/s]
 60%|██████    | 1281/2129 [01:13<01:05, 13.00it/s]
 60%|██████    | 1283/2129 [01:14<01:11, 11.75it/s]
 60%|██████    | 1285/2129 [01:14<01:03, 13.26it/s]
 60%|██████    | 1287/2129 [01:14<01:15, 11.17it/s]
 61%|██████    | 1289/2129 [01:14<01:05, 12.79it/s]
 61%|██████    | 1292/2129 [01:14<01:08, 12.25it/s]
 61%|██████    | 1295/2129 [01:15<00:55, 14.90it/s]
 61%|██████    | 1297/2129 [01:15<01:25,  9.68it/s]
 61%|██████    | 1299/2129 [01:15<01:30,  9.18it/s]
 61%|██████    | 1301/2129 [01:15<01:16, 10.75it/s]
 61%|██████    | 1304/2129 [01:16<01:11, 11.50it/s]
 61%|██████▏   | 1306/2129 [01:16<01:18, 10.46it/s]
 61%|██████▏   | 1308/2129 [01:16<01:25,  9.63it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 338.22it/s]
 67%|██████▋   | 201/300 [06:31<1:00:01, 36.38s/it]

[[np.int64(0), False, 8], [np.int64(1), False, 11], [np.int64(2), False, 7], [np.int64(3), False, 10], [np.int64(4), False, 6], [np.int64(5), False, 11], [np.int64(6), False, 7], [np.int64(7), False, 0], [np.int64(9), False, 8], [np.int64(12), False, 13]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6193, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.0721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>)

 67%|██████▋   | 202/300 [06:31<41:39, 25.51s/it]

tensor(-4.9195, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0964, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [06:32<13:58,  8.83s/it]

tensor(12.0958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7179, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [06:32<06:47,  4.39s/it]

tensor(12.0787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0473, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8306, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0574, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9603, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [06:32<03:21,  2.21s/it]

tensor(12.0750, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0643, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6096, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0693, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6486, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [06:32<02:22,  1.58s/it]

tensor(12.0986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0721, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5144, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0740, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6285, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [06:33<01:13,  1.19it/s]

tensor(12.1212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0750, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0760, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7509, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [06:33<00:31,  2.71it/s]

tensor(12.1120, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0770, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8558, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0774, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9761, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [06:33<00:20,  4.13it/s]

tensor(12.1288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0769, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0101, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0759, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1131, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [06:33<00:16,  4.86it/s]

tensor(12.1835, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0743, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1530, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0720, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1272, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [06:34<00:13,  6.12it/s]

tensor(12.1448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0693, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1231, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0663, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1571, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [06:34<00:11,  6.98it/s]

tensor(12.0866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0632, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1988, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0602, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2231, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [06:34<00:10,  7.39it/s]

tensor(12.1000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0574, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2278, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0544, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2294, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [06:34<00:09,  7.96it/s]

tensor(12.1060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0510, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0473, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2831, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [06:34<00:09,  7.94it/s]

tensor(12.0764, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0435, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3117, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3266, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [06:35<00:08,  8.14it/s]

tensor(12.0627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0373, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3173, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3009, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [06:35<00:08,  8.16it/s]

tensor(12.0616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3152, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3332, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [06:35<00:08,  8.16it/s]

tensor(12.0437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3331, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0369, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3268, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [06:35<00:07,  8.20it/s]

tensor(12.0321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3304, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3473, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [06:36<00:07,  8.11it/s]

tensor(12.0255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3617, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3632, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [06:36<00:07,  8.12it/s]

tensor(12.0172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3719, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3848, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [06:36<00:07,  8.16it/s]

tensor(12.0086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4011, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4194, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [06:37<00:06,  8.15it/s]

tensor(12.0033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4267, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0020, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4402, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [06:37<00:06,  8.07it/s]

tensor(12.0008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9994, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4523, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [06:37<00:06,  7.89it/s]

tensor(11.9971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4543, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4570, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [06:37<00:06,  8.09it/s]

tensor(11.9902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4522, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([228,  97, 129, 160, 133, 225, 117,  95, 211, 162, 157, 145, 171,  99])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:41, 21.01it/s]
  0%|          | 7/2129 [00:00<01:16, 27.73it/s]
  1%|          | 12/2129 [00:00<01:00, 35.22it/s]
  1%|          | 18/2129 [00:00<00:48, 43.52it/s]
  1%|          | 23/2129 [00:00<00:47, 44.67it/s]
  1%|▏         | 28/2129 [00:00<00:52, 39.70it/s]
  2%|▏         | 35/2129 [00:00<00:46, 44.77it/s]
  2%|▏         | 40/2129 [00:00<00:47, 43.60it/s]
  2%|▏         | 48/2129 [00:01<00:39, 53.09it/s]
  3%|▎         | 54/2129 [00:01<00:37, 54.75it/s]
  3%|▎         | 61/2129 [00:01<00:36, 56.39it/s]
  3%|▎         | 67/2129 [00:01<00:41, 50.15it/s]
  3%|▎         | 73/2129 [00:01<00:46, 44.20it/s]
  4%|▍         | 81/2129 [00:01<00:41, 49.55it/s]
  4%|▍         | 87/2129 [00:01<00:39, 51.98it/s]
  4%|▍         | 94/2129 [00:01<00:36, 56.22it/s]
  5%|▍         | 100/2129 [00:02<00:43, 46.65it/s]
  5%|▍         | 106/2129 [00:02<00:43, 46.88it/s]
  5%|▌         | 114/2129 [00:02<00:37, 54.28it/s]
  6%|▌         | 120/2129 [00:02<00:44, 44.92it/s]
  6%|▌         | 128/2129 [00:02<00:38, 51.94it/s]
  6%|▋         | 134/2129 [00:02<00:43, 45.53it/s]
  7%|▋         | 141/2129 [00:02<00:39, 50.15it/s]
  7%|▋         | 147/2129 [00:03<00:41, 47.36it/s]
  7%|▋         | 153/2129 [00:03<00:40, 48.66it/s]
  8%|▊         | 160/2129 [00:03<00:36, 53.26it/s]
  8%|▊         | 167/2129 [00:03<00:34, 56.47it/s]
  8%|▊         | 173/2129 [00:03<00:41, 47.08it/s]
  8%|▊         | 179/2129 [00:03<00:39, 49.35it/s]
  9%|▊         | 185/2129 [00:03<00:42, 45.69it/s]
  9%|▉         | 192/2129 [00:03<00:37, 51.22it/s]
  9%|▉         | 199/2129 [00:04<00:37, 51.49it/s]
 10%|▉         | 205/2129 [00:04<00:39, 49.12it/s]
 10%|▉         | 212/2129 [00:04<00:35, 53.68it/s]
 10%|█         | 218/2129 [00:04<00:47, 40.56it/s]
 11%|█         | 225/2129 [00:04<00:42, 45.27it/s]
 11%|█         | 231/2129 [00:04<00:39, 48.05it/s]
 11%|█         | 237/2129 [00:04<00:41, 45.59it/s]
 11%|█▏        | 242/2129 [00:05<00:44, 42.77it/s]
 12%|█▏        | 248/2129 [00:05<00:41, 45.20it/s]
 12%|█▏        | 255/2129 [00:05<00:38, 48.48it/s]
 12%|█▏        | 262/2129 [00:05<00:37, 49.74it/s]
 13%|█▎        | 268/2129 [00:05<00:45, 40.90it/s]
 13%|█▎        | 276/2129 [00:05<00:38, 48.34it/s]
 13%|█▎        | 283/2129 [00:05<00:35, 52.38it/s]
 14%|█▎        | 289/2129 [00:06<00:34, 53.54it/s]
 14%|█▍        | 295/2129 [00:06<00:34, 53.48it/s]
 14%|█▍        | 302/2129 [00:06<00:31, 57.44it/s]
 14%|█▍        | 308/2129 [00:06<00:33, 53.66it/s]
 15%|█▍        | 315/2129 [00:06<00:31, 57.04it/s]
 15%|█▌        | 321/2129 [00:06<00:40, 44.31it/s]
 15%|█▌        | 328/2129 [00:06<00:36, 49.25it/s]
 16%|█▌        | 334/2129 [00:06<00:35, 50.63it/s]
 16%|█▌        | 340/2129 [00:07<00:37, 48.31it/s]
 16%|█▋        | 346/2129 [00:07<00:38, 46.52it/s]
 17%|█▋        | 352/2129 [00:07<00:36, 48.90it/s]
 17%|█▋        | 358/2129 [00:07<00:39, 44.34it/s]
 17%|█▋        | 363/2129 [00:07<00:41, 42.09it/s]
 17%|█▋        | 368/2129 [00:07<00:41, 42.04it/s]
 18%|█▊        | 373/2129 [00:07<00:48, 36.53it/s]
 18%|█▊        | 377/2129 [00:07<00:47, 37.16it/s]
 18%|█▊        | 383/2129 [00:08<00:41, 41.84it/s]
 18%|█▊        | 389/2129 [00:08<00:38, 45.74it/s]
 19%|█▊        | 396/2129 [00:08<00:34, 50.91it/s]
 19%|█▉        | 402/2129 [00:08<00:35, 48.31it/s]
 19%|█▉        | 407/2129 [00:08<00:42, 40.75it/s]
 19%|█▉        | 414/2129 [00:08<00:37, 46.01it/s]
 20%|█▉        | 419/2129 [00:08<00:39, 43.69it/s]
 20%|█▉        | 425/2129 [00:08<00:35, 47.61it/s]
 20%|██        | 430/2129 [00:09<00:41, 40.70it/s]
 20%|██        | 436/2129 [00:09<00:38, 43.63it/s]
 21%|██        | 443/2129 [00:09<00:34, 48.46it/s]
 21%|██        | 449/2129 [00:09<00:39, 42.91it/s]
 21%|██▏       | 456/2129 [00:09<00:34, 48.29it/s]
 22%|██▏       | 462/2129 [00:09<00:32, 51.16it/s]
 22%|██▏       | 468/2129 [00:09<00:32, 51.45it/s]
 22%|██▏       | 476/2129 [00:09<00:28, 57.44it/s]
 23%|██▎       | 482/2129 [00:10<00:30, 53.54it/s]
 23%|██▎       | 488/2129 [00:10<00:30, 54.25it/s]
 23%|██▎       | 494/2129 [00:10<00:34, 46.85it/s]
 23%|██▎       | 500/2129 [00:10<00:32, 49.71it/s]
 24%|██▍       | 506/2129 [00:10<00:34, 46.76it/s]
 24%|██▍       | 513/2129 [00:10<00:31, 50.66it/s]
 24%|██▍       | 519/2129 [00:10<00:35, 45.23it/s]
 25%|██▍       | 524/2129 [00:11<00:34, 46.13it/s]
 25%|██▍       | 529/2129 [00:11<00:35, 45.42it/s]
 25%|██▌       | 536/2129 [00:11<00:31, 50.07it/s]
 26%|██▌       | 543/2129 [00:11<00:29, 54.01it/s]
 26%|██▌       | 549/2129 [00:11<00:29, 53.55it/s]
 26%|██▌       | 556/2129 [00:11<00:27, 57.32it/s]
 26%|██▋       | 563/2129 [00:11<00:26, 58.88it/s]
 27%|██▋       | 569/2129 [00:11<00:27, 57.10it/s]
 27%|██▋       | 575/2129 [00:11<00:27, 57.35it/s]
 27%|██▋       | 582/2129 [00:12<00:25, 60.66it/s]
 28%|██▊       | 589/2129 [00:12<00:24, 62.23it/s]
 28%|██▊       | 596/2129 [00:12<00:28, 53.28it/s]
 28%|██▊       | 602/2129 [00:12<00:28, 54.20it/s]
 29%|██▊       | 608/2129 [00:12<00:28, 54.30it/s]
 29%|██▉       | 616/2129 [00:12<00:25, 58.36it/s]
 29%|██▉       | 622/2129 [00:12<00:31, 47.94it/s]
 29%|██▉       | 628/2129 [00:13<00:37, 40.06it/s]
 30%|██▉       | 634/2129 [00:13<00:34, 43.16it/s]
 30%|███       | 642/2129 [00:13<00:29, 50.55it/s]
 30%|███       | 648/2129 [00:13<00:30, 48.54it/s]
 31%|███       | 654/2129 [00:13<00:30, 48.54it/s]
 31%|███       | 660/2129 [00:13<00:28, 51.32it/s]
 31%|███▏      | 666/2129 [00:13<00:27, 52.56it/s]
 32%|███▏      | 673/2129 [00:13<00:25, 56.92it/s]
 32%|███▏      | 679/2129 [00:14<00:31, 45.64it/s]
 32%|███▏      | 686/2129 [00:14<00:28, 50.41it/s]
 33%|███▎      | 692/2129 [00:14<00:31, 46.26it/s]
 33%|███▎      | 698/2129 [00:14<00:29, 48.72it/s]
 33%|███▎      | 704/2129 [00:14<00:27, 51.19it/s]
 33%|███▎      | 710/2129 [00:14<00:27, 51.69it/s]
 34%|███▎      | 716/2129 [00:14<00:30, 47.08it/s]
 34%|███▍      | 721/2129 [00:14<00:31, 44.96it/s]
 34%|███▍      | 726/2129 [00:15<00:31, 44.34it/s]
 34%|███▍      | 731/2129 [00:15<00:30, 45.46it/s]
 35%|███▍      | 737/2129 [00:15<00:29, 46.59it/s]
 35%|███▍      | 742/2129 [00:15<00:33, 41.40it/s]
 35%|███▌      | 749/2129 [00:15<00:28, 47.95it/s]
 35%|███▌      | 755/2129 [00:15<00:27, 50.43it/s]
 36%|███▌      | 762/2129 [00:15<00:26, 52.44it/s]
 36%|███▌      | 768/2129 [00:15<00:28, 47.29it/s]
 36%|███▋      | 773/2129 [00:16<00:33, 40.44it/s]
 37%|███▋      | 780/2129 [00:16<00:29, 45.39it/s]
 37%|███▋      | 785/2129 [00:16<00:29, 45.94it/s]
 37%|███▋      | 790/2129 [00:16<00:30, 43.50it/s]
 37%|███▋      | 797/2129 [00:16<00:29, 45.11it/s]
 38%|███▊      | 804/2129 [00:16<00:27, 47.69it/s]
 38%|███▊      | 811/2129 [00:16<00:25, 52.20it/s]
 38%|███▊      | 817/2129 [00:16<00:27, 46.98it/s]
 39%|███▊      | 823/2129 [00:17<00:26, 48.99it/s]
 39%|███▉      | 829/2129 [00:17<00:25, 50.93it/s]
 39%|███▉      | 836/2129 [00:17<00:23, 54.33it/s]
 40%|███▉      | 843/2129 [00:17<00:25, 50.98it/s]
 40%|███▉      | 849/2129 [00:17<00:29, 43.18it/s]
 40%|████      | 855/2129 [00:17<00:28, 45.18it/s]
 40%|████      | 860/2129 [00:17<00:33, 37.79it/s]
 41%|████      | 866/2129 [00:18<00:29, 42.46it/s]
 41%|████      | 873/2129 [00:18<00:25, 48.47it/s]
 41%|████▏     | 879/2129 [00:18<00:25, 49.84it/s]
 42%|████▏     | 887/2129 [00:18<00:22, 55.73it/s]
 42%|████▏     | 893/2129 [00:18<00:23, 53.38it/s]
 42%|████▏     | 900/2129 [00:18<00:21, 56.68it/s]
 43%|████▎     | 906/2129 [00:18<00:21, 56.32it/s]
 43%|████▎     | 912/2129 [00:18<00:21, 57.13it/s]
 43%|████▎     | 918/2129 [00:18<00:22, 54.04it/s]
 43%|████▎     | 924/2129 [00:19<00:22, 53.77it/s]
 44%|████▎     | 931/2129 [00:19<00:21, 55.04it/s]
 44%|████▍     | 937/2129 [00:19<00:22, 52.78it/s]
 44%|████▍     | 943/2129 [00:19<00:22, 53.32it/s]
 45%|████▍     | 949/2129 [00:19<00:25, 46.41it/s]
 45%|████▍     | 956/2129 [00:19<00:23, 50.97it/s]
 45%|████▌     | 962/2129 [00:19<00:22, 52.75it/s]
 45%|████▌     | 968/2129 [00:19<00:21, 54.16it/s]
 46%|████▌     | 974/2129 [00:19<00:20, 55.74it/s]
 46%|████▌     | 981/2129 [00:20<00:20, 57.33it/s]
 46%|████▋     | 987/2129 [00:20<00:20, 55.65it/s]
 47%|████▋     | 993/2129 [00:20<00:20, 56.64it/s]
 47%|████▋     | 999/2129 [00:20<00:23, 48.02it/s]
 47%|████▋     | 1007/2129 [00:20<00:20, 54.75it/s]
 48%|████▊     | 1013/2129 [00:20<00:20, 54.98it/s]
 48%|████▊     | 1019/2129 [00:20<00:23, 47.27it/s]
 48%|████▊     | 1026/2129 [00:20<00:21, 51.27it/s]
 48%|████▊     | 1032/2129 [00:21<00:25, 43.68it/s]
 49%|████▉     | 1039/2129 [00:21<00:22, 48.66it/s]
 49%|████▉     | 1045/2129 [00:21<00:22, 47.75it/s]
 49%|████▉     | 1051/2129 [00:21<00:33, 32.35it/s]
 50%|████▉     | 1057/2129 [00:21<00:29, 36.95it/s]
 50%|████▉     | 1063/2129 [00:21<00:25, 41.31it/s]
 50%|█████     | 1069/2129 [00:22<00:23, 44.26it/s]
 50%|█████     | 1075/2129 [00:22<00:24, 43.61it/s]
 51%|█████     | 1080/2129 [00:22<00:26, 39.36it/s]
 51%|█████     | 1085/2129 [00:22<00:25, 40.60it/s]
 51%|█████▏    | 1092/2129 [00:22<00:22, 46.36it/s]
 52%|█████▏    | 1097/2129 [00:22<00:25, 41.05it/s]
 52%|█████▏    | 1103/2129 [00:22<00:23, 43.76it/s]
 52%|█████▏    | 1109/2129 [00:23<00:22, 44.78it/s]
 52%|█████▏    | 1114/2129 [00:23<00:23, 43.02it/s]
 53%|█████▎    | 1120/2129 [00:23<00:22, 45.73it/s]
 53%|█████▎    | 1126/2129 [00:23<00:20, 48.63it/s]
 53%|█████▎    | 1131/2129 [00:23<00:23, 42.27it/s]
 53%|█████▎    | 1137/2129 [00:23<00:21, 46.43it/s]
 54%|█████▎    | 1142/2129 [00:23<00:21, 46.85it/s]
 54%|█████▍    | 1148/2129 [00:23<00:20, 48.16it/s]
 54%|█████▍    | 1154/2129 [00:23<00:19, 50.42it/s]
 54%|█████▍    | 1160/2129 [00:24<00:20, 47.10it/s]
 55%|█████▍    | 1165/2129 [00:24<00:20, 46.13it/s]
 55%|█████▍    | 1170/2129 [00:24<00:22, 42.06it/s]
 55%|█████▌    | 1175/2129 [00:24<00:23, 40.47it/s]
 56%|█████▌    | 1182/2129 [00:24<00:20, 47.00it/s]
 56%|█████▌    | 1189/2129 [00:24<00:19, 47.49it/s]
 56%|█████▌    | 1194/2129 [00:24<00:19, 47.54it/s]
 56%|█████▋    | 1200/2129 [00:24<00:18, 50.77it/s]
 57%|█████▋    | 1206/2129 [00:25<00:17, 53.26it/s]
 57%|█████▋    | 1213/2129 [00:25<00:16, 56.93it/s]
 57%|█████▋    | 1219/2129 [00:25<00:18, 48.42it/s]
 58%|█████▊    | 1225/2129 [00:25<00:18, 48.29it/s]
 58%|█████▊    | 1231/2129 [00:25<00:17, 50.67it/s]
 58%|█████▊    | 1238/2129 [00:25<00:16, 55.36it/s]
 58%|█████▊    | 1244/2129 [00:25<00:16, 55.30it/s]
 59%|█████▉    | 1251/2129 [00:25<00:16, 53.09it/s]
 59%|█████▉    | 1257/2129 [00:26<00:16, 53.77it/s]
 59%|█████▉    | 1263/2129 [00:26<00:17, 48.50it/s]
 60%|█████▉    | 1268/2129 [00:26<00:18, 47.57it/s]
 60%|█████▉    | 1273/2129 [00:26<00:18, 46.00it/s]
 60%|██████    | 1279/2129 [00:26<00:17, 48.65it/s]
 60%|██████    | 1285/2129 [00:26<00:16, 51.51it/s]
 61%|██████    | 1291/2129 [00:26<00:15, 53.80it/s]
 61%|██████    | 1297/2129 [00:26<00:15, 54.11it/s]
 61%|██████    | 1303/2129 [00:26<00:15, 53.05it/s]
 62%|██████▏   | 1310/2129 [00:27<00:14, 55.92it/s]
 62%|██████▏   | 1316/2129 [00:27<00:15, 52.25it/s]
 62%|██████▏   | 1322/2129 [00:27<00:15, 51.71it/s]
 62%|██████▏   | 1328/2129 [00:27<00:19, 41.62it/s]
 63%|██████▎   | 1334/2129 [00:27<00:17, 45.51it/s]
 63%|██████▎   | 1341/2129 [00:27<00:15, 50.53it/s]
 63%|██████▎   | 1349/2129 [00:27<00:13, 56.86it/s]
 64%|██████▎   | 1355/2129 [00:27<00:13, 56.59it/s]
 64%|██████▍   | 1362/2129 [00:28<00:12, 59.82it/s]
 64%|██████▍   | 1369/2129 [00:28<00:13, 58.38it/s]
 65%|██████▍   | 1375/2129 [00:28<00:18, 41.79it/s]
 65%|██████▍   | 1382/2129 [00:28<00:15, 47.26it/s]
 65%|██████▌   | 1388/2129 [00:28<00:16, 43.96it/s]
 65%|██████▌   | 1394/2129 [00:28<00:15, 47.09it/s]
 66%|██████▌   | 1401/2129 [00:28<00:14, 50.37it/s]
 66%|██████▌   | 1407/2129 [00:29<00:16, 43.83it/s]
 66%|██████▋   | 1413/2129 [00:29<00:15, 45.55it/s]
 67%|██████▋   | 1418/2129 [00:29<00:15, 46.16it/s]
 67%|██████▋   | 1423/2129 [00:29<00:16, 42.01it/s]
 67%|██████▋   | 1428/2129 [00:29<00:17, 41.01it/s]
 67%|██████▋   | 1433/2129 [00:29<00:20, 34.25it/s]
 68%|██████▊   | 1439/2129 [00:29<00:18, 37.49it/s]
 68%|██████▊   | 1444/2129 [00:30<00:17, 39.63it/s]
 68%|██████▊   | 1450/2129 [00:30<00:15, 43.74it/s]
 68%|██████▊   | 1455/2129 [00:30<00:16, 41.18it/s]
 69%|██████▊   | 1460/2129 [00:30<00:17, 37.67it/s]
 69%|██████▉   | 1464/2129 [00:30<00:19, 33.49it/s]
 69%|██████▉   | 1469/2129 [00:30<00:18, 36.51it/s]
 69%|██████▉   | 1475/2129 [00:30<00:15, 42.10it/s]
 70%|██████▉   | 1481/2129 [00:30<00:14, 45.27it/s]
 70%|██████▉   | 1487/2129 [00:31<00:13, 47.88it/s]
 70%|███████   | 1493/2129 [00:31<00:12, 50.68it/s]
 70%|███████   | 1499/2129 [00:31<00:12, 51.68it/s]
 71%|███████   | 1505/2129 [00:31<00:12, 50.82it/s]
 71%|███████   | 1511/2129 [00:31<00:11, 52.56it/s]
 71%|███████▏  | 1517/2129 [00:31<00:13, 44.94it/s]
 71%|███████▏  | 1522/2129 [00:31<00:13, 43.51it/s]
 72%|███████▏  | 1527/2129 [00:31<00:15, 38.90it/s]
 72%|███████▏  | 1533/2129 [00:32<00:13, 42.59it/s]
 72%|███████▏  | 1539/2129 [00:32<00:14, 42.11it/s]
 73%|███████▎  | 1544/2129 [00:32<00:13, 43.00it/s]
 73%|███████▎  | 1549/2129 [00:32<00:13, 43.09it/s]
 73%|███████▎  | 1554/2129 [00:32<00:13, 41.66it/s]
 73%|███████▎  | 1559/2129 [00:32<00:14, 40.16it/s]
 73%|███████▎  | 1564/2129 [00:32<00:15, 37.14it/s]
 74%|███████▎  | 1568/2129 [00:32<00:16, 35.03it/s]
 74%|███████▍  | 1574/2129 [00:33<00:13, 40.04it/s]
 74%|███████▍  | 1580/2129 [00:33<00:12, 44.57it/s]
 74%|███████▍  | 1586/2129 [00:33<00:11, 48.25it/s]
 75%|███████▍  | 1593/2129 [00:33<00:10, 51.48it/s]
 75%|███████▌  | 1599/2129 [00:33<00:10, 52.37it/s]
 75%|███████▌  | 1605/2129 [00:33<00:10, 51.08it/s]
 76%|███████▌  | 1611/2129 [00:33<00:10, 49.41it/s]
 76%|███████▌  | 1616/2129 [00:33<00:11, 45.75it/s]
 76%|███████▌  | 1623/2129 [00:34<00:10, 49.52it/s]
 77%|███████▋  | 1629/2129 [00:34<00:10, 45.64it/s]
 77%|███████▋  | 1634/2129 [00:34<00:10, 45.62it/s]
 77%|███████▋  | 1640/2129 [00:34<00:10, 46.53it/s]
 77%|███████▋  | 1646/2129 [00:34<00:09, 49.65it/s]
 78%|███████▊  | 1652/2129 [00:34<00:11, 42.60it/s]
 78%|███████▊  | 1657/2129 [00:34<00:11, 42.80it/s]
 78%|███████▊  | 1663/2129 [00:34<00:10, 45.78it/s]
 78%|███████▊  | 1669/2129 [00:35<00:09, 49.19it/s]
 79%|███████▊  | 1675/2129 [00:35<00:09, 45.53it/s]
 79%|███████▉  | 1680/2129 [00:35<00:11, 40.38it/s]
 79%|███████▉  | 1685/2129 [00:35<00:10, 42.34it/s]
 79%|███████▉  | 1690/2129 [00:35<00:10, 42.79it/s]
 80%|███████▉  | 1696/2129 [00:35<00:10, 41.94it/s]
 80%|███████▉  | 1701/2129 [00:35<00:10, 39.98it/s]
 80%|████████  | 1707/2129 [00:35<00:10, 42.06it/s]
 81%|████████  | 1714/2129 [00:36<00:08, 46.94it/s]
 81%|████████  | 1719/2129 [00:36<00:09, 43.85it/s]
 81%|████████  | 1724/2129 [00:36<00:09, 42.77it/s]
 81%|████████▏ | 1731/2129 [00:36<00:08, 47.73it/s]
 82%|████████▏ | 1737/2129 [00:36<00:07, 49.68it/s]
 82%|████████▏ | 1743/2129 [00:36<00:07, 51.03it/s]
 82%|████████▏ | 1749/2129 [00:36<00:07, 51.98it/s]
 82%|████████▏ | 1755/2129 [00:36<00:06, 54.09it/s]
 83%|████████▎ | 1761/2129 [00:37<00:06, 55.45it/s]
 83%|████████▎ | 1767/2129 [00:37<00:06, 51.99it/s]
 83%|████████▎ | 1773/2129 [00:37<00:07, 49.97it/s]
 84%|████████▎ | 1779/2129 [00:37<00:07, 47.26it/s]
 84%|████████▍ | 1786/2129 [00:37<00:06, 52.28it/s]
 84%|████████▍ | 1792/2129 [00:37<00:06, 52.30it/s]
 84%|████████▍ | 1798/2129 [00:37<00:06, 53.05it/s]
 85%|████████▍ | 1805/2129 [00:37<00:06, 50.45it/s]
 85%|████████▌ | 1811/2129 [00:38<00:06, 51.30it/s]
 85%|████████▌ | 1817/2129 [00:38<00:05, 53.38it/s]
 86%|████████▌ | 1823/2129 [00:38<00:05, 54.02it/s]
 86%|████████▌ | 1829/2129 [00:38<00:05, 53.85it/s]
 86%|████████▌ | 1835/2129 [00:38<00:05, 51.61it/s]
 86%|████████▋ | 1841/2129 [00:38<00:05, 50.12it/s]
 87%|████████▋ | 1847/2129 [00:38<00:05, 52.20it/s]
 87%|████████▋ | 1853/2129 [00:38<00:05, 50.58it/s]
 87%|████████▋ | 1859/2129 [00:38<00:05, 50.46it/s]
 88%|████████▊ | 1867/2129 [00:39<00:04, 56.27it/s]
 88%|████████▊ | 1873/2129 [00:39<00:04, 54.81it/s]
 88%|████████▊ | 1879/2129 [00:39<00:04, 56.13it/s]
 89%|████████▊ | 1885/2129 [00:39<00:04, 51.92it/s]
 89%|████████▉ | 1891/2129 [00:39<00:04, 52.55it/s]
 89%|████████▉ | 1897/2129 [00:39<00:04, 51.76it/s]
 89%|████████▉ | 1903/2129 [00:39<00:04, 53.82it/s]
 90%|████████▉ | 1909/2129 [00:39<00:04, 52.65it/s]
 90%|████████▉ | 1916/2129 [00:39<00:03, 55.23it/s]
 90%|█████████ | 1922/2129 [00:40<00:03, 52.94it/s]
 91%|█████████ | 1928/2129 [00:40<00:03, 53.59it/s]
 91%|█████████ | 1934/2129 [00:40<00:03, 49.36it/s]
 91%|█████████ | 1940/2129 [00:40<00:04, 42.74it/s]
 91%|█████████▏| 1946/2129 [00:40<00:04, 44.59it/s]
 92%|█████████▏| 1951/2129 [00:40<00:04, 42.05it/s]
 92%|█████████▏| 1957/2129 [00:40<00:03, 44.84it/s]
 92%|█████████▏| 1964/2129 [00:41<00:03, 49.10it/s]
 93%|█████████▎| 1970/2129 [00:41<00:04, 37.78it/s]
 93%|█████████▎| 1975/2129 [00:41<00:04, 36.04it/s]
 93%|█████████▎| 1979/2129 [00:41<00:04, 33.95it/s]
 93%|█████████▎| 1984/2129 [00:41<00:03, 37.35it/s]
 93%|█████████▎| 1989/2129 [00:41<00:03, 37.42it/s]
 94%|█████████▎| 1995/2129 [00:41<00:03, 41.82it/s]
 94%|█████████▍| 2001/2129 [00:42<00:02, 44.90it/s]
 94%|█████████▍| 2007/2129 [00:42<00:02, 43.61it/s]
 95%|█████████▍| 2012/2129 [00:42<00:02, 43.79it/s]
 95%|█████████▍| 2018/2129 [00:42<00:02, 47.04it/s]
 95%|█████████▌| 2025/2129 [00:42<00:02, 51.48it/s]
 95%|█████████▌| 2031/2129 [00:42<00:01, 49.63it/s]
 96%|█████████▌| 2037/2129 [00:42<00:01, 50.88it/s]
 96%|█████████▌| 2043/2129 [00:42<00:01, 51.69it/s]
 96%|█████████▋| 2051/2129 [00:42<00:01, 55.55it/s]
 97%|█████████▋| 2058/2129 [00:43<00:01, 57.26it/s]
 97%|█████████▋| 2064/2129 [00:43<00:01, 52.02it/s]
 97%|█████████▋| 2070/2129 [00:43<00:01, 42.72it/s]
 98%|█████████▊| 2077/2129 [00:43<00:01, 47.97it/s]
 98%|█████████▊| 2083/2129 [00:43<00:00, 50.70it/s]
 98%|█████████▊| 2090/2129 [00:43<00:00, 54.84it/s]
 98%|█████████▊| 2097/2129 [00:43<00:00, 56.40it/s]
 99%|█████████▉| 2105/2129 [00:43<00:00, 61.04it/s]
 99%|█████████▉| 2112/2129 [00:44<00:00, 52.55it/s]
 99%|█████████▉| 2118/2129 [00:44<00:00, 49.63it/s]
100%|██████████| 2129/2129 [00:44<00:00, 47.84it/s]
/kaggle/working/PRAGA/clustering_utils.py:173: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return log_Hastings_ratio_split(1.0, torch.tensor(N_k_1), torch.tensor(N_k_2), log_ll_k1, log_ll_k2, log_ll_k, split_prob=0.1)

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 319.89it/s]

[[np.int64(0), False, 5], [np.int64(1), False, 7], [np.int64(2), False, 5], [np.int64(3), False, 11], [np.int64(4), False, 10], [np.int64(6), False, 11], [np.int64(8), False, 10], [np.int64(9), False, 10], [np.int64(11), False, 0], [np.int64(12), False, 10], [np.int64(13), False, 8]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3117, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [07:26<11:54, 14.57s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [07:26<08:11, 10.24s/it]

tensor(12.0041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4079, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7747, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [07:26<02:41,  3.59s/it]

tensor(12.0439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4675, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0360, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5112, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [07:26<01:18,  1.82s/it]

tensor(12.0523, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0389, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6896, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8428, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [07:26<00:39,  1.05it/s]

tensor(12.0180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0439, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8806, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0458, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9114, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [07:27<00:20,  1.89it/s]

tensor(12.0261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9541, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0505, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9704, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [07:27<00:15,  2.45it/s]

tensor(12.0234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0526, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0200, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0542, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0646, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [07:27<00:09,  3.73it/s]

tensor(12.0149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0554, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1149, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0569, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1519, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [07:27<00:06,  5.15it/s]

tensor(12.0053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0578, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0092, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0577, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0462, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [07:28<00:04,  6.83it/s]

tensor(12.0052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0578, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0757, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0576, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1007, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [07:28<00:03,  7.48it/s]

tensor(12.0022, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0575, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1371, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1965, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [07:28<00:03,  7.94it/s]

tensor(11.9930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0576, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2501, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0580, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2901, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [07:28<00:03,  8.02it/s]

tensor(11.9838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2934, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0549, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3032, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [07:29<00:02,  8.18it/s]

tensor(11.9884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0502, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3070, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0455, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3174, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [07:29<00:02,  8.21it/s]

tensor(11.9858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0425, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3330, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9835, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3500, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [07:29<00:02,  8.22it/s]

tensor(11.9804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0399, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3648, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9765, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3674, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [07:29<00:02,  8.21it/s]

tensor(11.9731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3644, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3805, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [07:30<00:01,  8.23it/s]

tensor(11.9669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3934, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3944, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [07:30<00:01,  8.28it/s]

tensor(11.9601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4039, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4158, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [07:30<00:01,  8.24it/s]

tensor(11.9531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4304, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4458, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [07:30<00:01,  8.21it/s]

tensor(11.9518, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4579, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4685, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [07:31<00:00,  8.21it/s]

tensor(11.9489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4762, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4789, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [07:31<00:00,  8.22it/s]

tensor(11.9441, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4812, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4805, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [07:31<00:00,  8.26it/s]

tensor(11.9398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4900, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4902, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [07:31<00:00,  8.27it/s]

tensor(11.9360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4945, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9342, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4993, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [07:32<00:00,  1.51s/it]

tensor(11.9329, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5026, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0019278526306152344
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 6
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.460449452864
NMI         : 0.569379700996
Runtime     : 497.07 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed6

==============================================================================================================
PRAGA RUN | E18.5 | seed=7
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 5.877e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:32,  9.07it/s]

tensor(15.6725, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4753, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6872, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2236, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:31,  9.40it/s]

tensor(15.6598, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1929, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6241, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3622, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:30,  9.63it/s]

tensor(15.5920, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7117, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5595, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2228, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:30,  9.70it/s]

tensor(15.5336, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8807, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5121, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6716, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.68it/s]

tensor(15.4912, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5811, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4750, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5973, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:29,  9.74it/s]

tensor(15.4583, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7114, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4406, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9132, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4207, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1925, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:28,  9.84it/s]

tensor(15.4004, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5442, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3765, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9599, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:29,  9.66it/s]

tensor(15.3523, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4330, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3287, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9591, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.83it/s]

tensor(15.3054, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5318, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2811, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1472, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:28,  9.82it/s]

tensor(15.2577, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8012, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2310, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4890, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2003, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2090, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:27,  9.88it/s]

tensor(15.1650, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9566, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1266, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7299, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:28,  9.74it/s]

tensor(15.0873, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5266, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0485, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3433, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:28,  9.63it/s]

tensor(15.0102, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1795, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9725, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0316, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:27,  9.65it/s]

tensor(14.9343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9001, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8939, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7813, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.72it/s]

tensor(14.8490, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6763, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5811, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:27,  9.77it/s]

tensor(14.7442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4973, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4214, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:26,  9.79it/s]

tensor(14.6306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3553, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2959, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.83it/s]

tensor(14.5151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2438, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1981, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:04<00:26,  9.66it/s]

tensor(14.3885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1576, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1233, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:26,  9.85it/s]

tensor(14.2630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0943, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0707, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:26,  9.71it/s]

tensor(14.1554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0531, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:26,  9.58it/s]

tensor(14.0700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0353, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0380, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:26,  9.67it/s]

tensor(14.0102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:05<00:26,  9.60it/s]

tensor(13.9555, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:05<00:25,  9.64it/s]

tensor(13.8919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:25,  9.62it/s]

tensor(13.8348, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:25,  9.65it/s]

tensor(13.7975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:24,  9.70it/s]

tensor(13.7690, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:06<00:24,  9.74it/s]

tensor(13.7375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.81it/s]

tensor(13.7001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:24,  9.81it/s]

tensor(13.6624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:23,  9.82it/s]

tensor(13.6273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:23,  9.84it/s]

tensor(13.5965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5821, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:23,  9.84it/s]

tensor(13.5679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:07<00:23,  9.83it/s]

tensor(13.5392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:23,  9.79it/s]

tensor(13.5108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:23,  9.68it/s]

tensor(13.4851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:08<00:22,  9.84it/s]

tensor(13.4612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:08<00:22,  9.86it/s]

tensor(13.4379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4145, device='cuda:0', grad_fn=<AddBackward0>)

 27%|██▋       | 82/300 [00:08<00:22,  9.78it/s]

tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:22,  9.73it/s]

tensor(13.3910, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:22,  9.47it/s]

tensor(13.3671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:09<00:22,  9.47it/s]

tensor(13.3439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:22,  9.38it/s]

tensor(13.3215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:22,  9.23it/s]

tensor(13.2997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:21,  9.49it/s]

tensor(13.2785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:21,  9.54it/s]

tensor(13.2578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:10<00:21,  9.43it/s]

tensor(13.2378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.37it/s]

tensor(13.2183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([197, 187, 130, 272,  87,  84,  58,  52, 253, 151, 115, 164,  78, 301])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<01:49, 19.41it/s]
  0%|          | 5/2129 [00:00<01:25, 24.90it/s]
  1%|          | 11/2129 [00:00<00:52, 40.08it/s]
  1%|          | 18/2129 [00:00<00:43, 48.15it/s]
  1%|          | 25/2129 [00:00<00:38, 54.38it/s]
  2%|▏         | 32/2129 [00:00<00:36, 57.52it/s]
  2%|▏         | 38/2129 [00:00<00:39, 52.64it/s]
  2%|▏         | 45/2129 [00:00<00:36, 57.40it/s]
  2%|▏         | 51/2129 [00:01<00:37, 55.07it/s]
  3%|▎         | 57/2129 [00:01<00:37, 55.36it/s]
  3%|▎         | 63/2129 [00:01<00:36, 55.87it/s]
  3%|▎         | 70/2129 [00:01<00:47, 43.28it/s]
  4%|▎         | 75/2129 [00:01<01:12, 28.44it/s]
  4%|▍         | 80/2129 [00:02<01:29, 22.95it/s]
  4%|▍         | 84/2129 [00:02<01:35, 21.43it/s]
  4%|▍         | 87/2129 [00:02<01:35, 21.43it/s]
  4%|▍         | 92/2129 [00:02<01:19, 25.66it/s]
  5%|▍         | 99/2129 [00:02<00:59, 34.02it/s]
  5%|▍         | 104/2129 [00:03<01:48, 18.60it/s]
  5%|▌         | 108/2129 [00:03<01:50, 18.37it/s]
  5%|▌         | 113/2129 [00:03<01:56, 17.36it/s]
  5%|▌         | 116/2129 [00:04<01:54, 17.65it/s]
  6%|▌         | 120/2129 [00:04<01:47, 18.71it/s]
  6%|▌         | 124/2129 [00:04<01:32, 21.62it/s]
  6%|▌         | 129/2129 [00:04<01:16, 26.13it/s]
  6%|▌         | 133/2129 [00:04<01:50, 18.05it/s]
  6%|▋         | 136/2129 [00:05<02:29, 13.33it/s]
  7%|▋         | 144/2129 [00:05<01:31, 21.67it/s]
  7%|▋         | 149/2129 [00:05<01:16, 25.80it/s]
  7%|▋         | 153/2129 [00:05<01:38, 19.98it/s]
  7%|▋         | 157/2129 [00:06<02:01, 16.23it/s]
  8%|▊         | 160/2129 [00:06<02:12, 14.90it/s]
  8%|▊         | 163/2129 [00:06<02:26, 13.39it/s]
  8%|▊         | 165/2129 [00:06<02:25, 13.46it/s]
  8%|▊         | 167/2129 [00:07<02:33, 12.75it/s]
  8%|▊         | 170/2129 [00:07<02:08, 15.27it/s]
  8%|▊         | 172/2129 [00:07<02:48, 11.59it/s]
  8%|▊         | 176/2129 [00:07<02:32, 12.82it/s]
  8%|▊         | 178/2129 [00:08<03:07, 10.40it/s]
  8%|▊         | 180/2129 [00:08<03:10, 10.23it/s]
  9%|▊         | 182/2129 [00:08<02:48, 11.58it/s]
  9%|▊         | 184/2129 [00:08<03:30,  9.25it/s]
  9%|▊         | 186/2129 [00:08<03:10, 10.20it/s]
  9%|▉         | 188/2129 [00:09<03:27,  9.35it/s]
  9%|▉         | 190/2129 [00:09<03:20,  9.66it/s]
  9%|▉         | 192/2129 [00:09<02:51, 11.26it/s]
  9%|▉         | 195/2129 [00:09<02:27, 13.10it/s]
  9%|▉         | 200/2129 [00:09<02:07, 15.10it/s]
  9%|▉         | 202/2129 [00:10<02:17, 14.06it/s]
 10%|▉         | 205/2129 [00:10<02:04, 15.51it/s]
 10%|▉         | 212/2129 [00:10<01:47, 17.89it/s]
 10%|█         | 214/2129 [00:10<02:39, 12.03it/s]
 10%|█         | 216/2129 [00:11<02:59, 10.66it/s]
 10%|█         | 219/2129 [00:11<02:35, 12.25it/s]
 10%|█         | 223/2129 [00:11<02:26, 12.98it/s]
 11%|█         | 225/2129 [00:11<03:02, 10.43it/s]
 11%|█         | 227/2129 [00:12<02:44, 11.57it/s]
 11%|█         | 231/2129 [00:12<01:58, 16.03it/s]
 11%|█         | 234/2129 [00:12<02:42, 11.67it/s]
 11%|█         | 236/2129 [00:12<02:29, 12.70it/s]
 11%|█         | 238/2129 [00:12<02:16, 13.88it/s]
 11%|█▏        | 240/2129 [00:13<02:43, 11.53it/s]
 11%|█▏        | 243/2129 [00:13<02:13, 14.08it/s]
 12%|█▏        | 246/2129 [00:13<02:54, 10.79it/s]
 12%|█▏        | 248/2129 [00:13<03:28,  9.03it/s]
 12%|█▏        | 250/2129 [00:14<03:38,  8.61it/s]
 12%|█▏        | 252/2129 [00:14<04:01,  7.78it/s]
 12%|█▏        | 254/2129 [00:14<03:21,  9.30it/s]
 12%|█▏        | 256/2129 [00:14<03:01, 10.30it/s]
 12%|█▏        | 258/2129 [00:15<03:11,  9.76it/s]
 12%|█▏        | 260/2129 [00:15<02:51, 10.90it/s]
 12%|█▏        | 262/2129 [00:15<02:58, 10.44it/s]
 12%|█▏        | 266/2129 [00:15<02:02, 15.23it/s]
 13%|█▎        | 268/2129 [00:15<02:38, 11.75it/s]
 13%|█▎        | 270/2129 [00:16<02:57, 10.48it/s]
 13%|█▎        | 272/2129 [00:16<02:48, 11.00it/s]
 13%|█▎        | 275/2129 [00:16<02:49, 10.95it/s]
 13%|█▎        | 278/2129 [00:16<02:16, 13.58it/s]
 13%|█▎        | 285/2129 [00:16<01:35, 19.22it/s]
 14%|█▎        | 288/2129 [00:17<02:23, 12.83it/s]
 14%|█▎        | 291/2129 [00:17<02:05, 14.68it/s]
 14%|█▍        | 293/2129 [00:17<02:13, 13.74it/s]
 14%|█▍        | 295/2129 [00:17<02:51, 10.69it/s]
 14%|█▍        | 297/2129 [00:18<03:26,  8.89it/s]
 14%|█▍        | 299/2129 [00:18<03:27,  8.82it/s]
 14%|█▍        | 301/2129 [00:18<03:08,  9.70it/s]
 14%|█▍        | 304/2129 [00:18<03:11,  9.55it/s]
 14%|█▍        | 306/2129 [00:19<03:21,  9.04it/s]
 14%|█▍        | 308/2129 [00:19<02:51, 10.59it/s]
 15%|█▍        | 312/2129 [00:19<02:18, 13.15it/s]
 15%|█▍        | 314/2129 [00:20<03:39,  8.27it/s]
 15%|█▍        | 316/2129 [00:20<04:20,  6.96it/s]
 15%|█▍        | 319/2129 [00:20<04:09,  7.27it/s]
 15%|█▌        | 321/2129 [00:20<03:34,  8.41it/s]
 15%|█▌        | 324/2129 [00:21<03:09,  9.51it/s]
 15%|█▌        | 326/2129 [00:21<02:46, 10.83it/s]
 15%|█▌        | 328/2129 [00:21<02:57, 10.17it/s]
 16%|█▌        | 330/2129 [00:21<03:55,  7.63it/s]
 16%|█▌        | 331/2129 [00:22<04:10,  7.19it/s]
 16%|█▌        | 334/2129 [00:22<03:56,  7.58it/s]
 16%|█▌        | 337/2129 [00:22<03:51,  7.76it/s]
 16%|█▌        | 340/2129 [00:23<02:59,  9.99it/s]
 16%|█▌        | 342/2129 [00:23<03:02,  9.80it/s]
 16%|█▌        | 344/2129 [00:23<03:15,  9.13it/s]
 16%|█▋        | 346/2129 [00:23<02:48, 10.61it/s]
 16%|█▋        | 349/2129 [00:23<02:38, 11.26it/s]
 16%|█▋        | 351/2129 [00:24<03:33,  8.31it/s]
 17%|█▋        | 354/2129 [00:24<03:42,  7.97it/s]
 17%|█▋        | 355/2129 [00:25<04:38,  6.37it/s]
 17%|█▋        | 356/2129 [00:25<05:25,  5.45it/s]
 17%|█▋        | 357/2129 [00:25<06:15,  4.72it/s]
 17%|█▋        | 358/2129 [00:25<06:52,  4.29it/s]
 17%|█▋        | 359/2129 [00:26<06:31,  4.52it/s]
 17%|█▋        | 361/2129 [00:26<05:18,  5.55it/s]
 17%|█▋        | 362/2129 [00:26<06:22,  4.62it/s]
 17%|█▋        | 364/2129 [00:27<06:03,  4.85it/s]
 17%|█▋        | 367/2129 [00:27<03:54,  7.50it/s]
 17%|█▋        | 371/2129 [00:27<02:26, 12.04it/s]
 18%|█▊        | 373/2129 [00:27<02:35, 11.30it/s]
 18%|█▊        | 375/2129 [00:27<02:21, 12.35it/s]
 18%|█▊        | 377/2129 [00:28<03:06,  9.37it/s]
 18%|█▊        | 380/2129 [00:28<03:17,  8.88it/s]
 18%|█▊        | 382/2129 [00:28<02:51, 10.21it/s]
 18%|█▊        | 384/2129 [00:28<02:55,  9.93it/s]
 18%|█▊        | 386/2129 [00:29<04:17,  6.76it/s]
 18%|█▊        | 387/2129 [00:29<04:09,  6.99it/s]
 18%|█▊        | 390/2129 [00:29<02:56,  9.84it/s]
 18%|█▊        | 392/2129 [00:29<03:43,  7.79it/s]
 19%|█▊        | 394/2129 [00:30<04:03,  7.12it/s]
 19%|█▊        | 396/2129 [00:30<03:19,  8.69it/s]
 19%|█▉        | 402/2129 [00:30<01:59, 14.48it/s]
 19%|█▉        | 404/2129 [00:30<02:08, 13.41it/s]
 19%|█▉        | 406/2129 [00:31<02:48, 10.22it/s]
 19%|█▉        | 408/2129 [00:31<03:24,  8.43it/s]
 19%|█▉        | 411/2129 [00:31<02:39, 10.75it/s]
 20%|█▉        | 417/2129 [00:31<01:35, 17.87it/s]
 20%|█▉        | 420/2129 [00:32<02:09, 13.24it/s]
 20%|█▉        | 423/2129 [00:32<02:12, 12.92it/s]
 20%|██        | 426/2129 [00:32<01:51, 15.21it/s]
 20%|██        | 429/2129 [00:32<01:46, 15.92it/s]
 20%|██        | 432/2129 [00:33<02:31, 11.18it/s]
 20%|██        | 434/2129 [00:33<02:29, 11.36it/s]
 20%|██        | 436/2129 [00:33<03:02,  9.25it/s]
 21%|██        | 439/2129 [00:33<03:15,  8.64it/s]
 21%|██        | 441/2129 [00:34<02:51,  9.87it/s]
 21%|██        | 443/2129 [00:34<02:33, 11.00it/s]
 21%|██        | 446/2129 [00:34<02:45, 10.15it/s]
 21%|██        | 449/2129 [00:34<02:11, 12.74it/s]
 21%|██        | 452/2129 [00:34<01:52, 14.92it/s]
 21%|██▏       | 455/2129 [00:35<02:08, 13.04it/s]
 21%|██▏       | 457/2129 [00:35<02:48,  9.91it/s]
 22%|██▏       | 459/2129 [00:35<03:18,  8.40it/s]
 22%|██▏       | 461/2129 [00:35<03:03,  9.10it/s]
 22%|██▏       | 463/2129 [00:36<02:46, 10.02it/s]
 22%|██▏       | 466/2129 [00:36<02:33, 10.83it/s]
 22%|██▏       | 468/2129 [00:36<03:27,  7.99it/s]
 22%|██▏       | 471/2129 [00:37<03:32,  7.80it/s]
 22%|██▏       | 473/2129 [00:37<03:58,  6.95it/s]
 22%|██▏       | 477/2129 [00:37<03:09,  8.72it/s]
 22%|██▏       | 478/2129 [00:38<03:58,  6.91it/s]
 23%|██▎       | 480/2129 [00:38<03:18,  8.31it/s]
 23%|██▎       | 483/2129 [00:38<03:27,  7.95it/s]
 23%|██▎       | 484/2129 [00:38<03:53,  7.03it/s]
 23%|██▎       | 486/2129 [00:39<03:16,  8.35it/s]
 23%|██▎       | 488/2129 [00:39<03:43,  7.34it/s]
 23%|██▎       | 490/2129 [00:39<04:00,  6.83it/s]
 23%|██▎       | 492/2129 [00:39<03:16,  8.33it/s]
 23%|██▎       | 496/2129 [00:40<02:52,  9.47it/s]
 23%|██▎       | 499/2129 [00:40<02:18, 11.81it/s]
 24%|██▎       | 501/2129 [00:40<02:21, 11.49it/s]
 24%|██▎       | 504/2129 [00:40<01:56, 13.97it/s]
 24%|██▍       | 508/2129 [00:40<01:45, 15.32it/s]
 24%|██▍       | 510/2129 [00:41<02:15, 11.98it/s]
 24%|██▍       | 512/2129 [00:41<02:10, 12.40it/s]
 24%|██▍       | 515/2129 [00:41<01:47, 15.00it/s]
 24%|██▍       | 517/2129 [00:41<02:02, 13.14it/s]
 24%|██▍       | 520/2129 [00:42<02:33, 10.49it/s]
 25%|██▍       | 522/2129 [00:42<03:33,  7.52it/s]
 25%|██▍       | 525/2129 [00:42<02:45,  9.68it/s]
 25%|██▍       | 527/2129 [00:43<03:08,  8.51it/s]
 25%|██▍       | 529/2129 [00:43<04:31,  5.90it/s]
 25%|██▍       | 530/2129 [00:43<04:51,  5.49it/s]
 25%|██▍       | 532/2129 [00:44<03:52,  6.86it/s]
 25%|██▌       | 534/2129 [00:44<03:09,  8.41it/s]
 25%|██▌       | 536/2129 [00:44<04:27,  5.96it/s]
 25%|██▌       | 539/2129 [00:44<03:09,  8.40it/s]
 26%|██▌       | 543/2129 [00:45<02:42,  9.79it/s]
 26%|██▌       | 546/2129 [00:45<02:12, 11.97it/s]
 26%|██▌       | 548/2129 [00:45<02:47,  9.45it/s]
 26%|██▌       | 552/2129 [00:45<01:58, 13.35it/s]
 26%|██▌       | 555/2129 [00:45<01:39, 15.85it/s]
 26%|██▌       | 558/2129 [00:46<01:54, 13.67it/s]
 26%|██▋       | 560/2129 [00:46<02:32, 10.30it/s]
 26%|██▋       | 563/2129 [00:46<02:27, 10.64it/s]
 27%|██▋       | 565/2129 [00:47<02:40,  9.75it/s]
 27%|██▋       | 567/2129 [00:47<03:31,  7.39it/s]
 27%|██▋       | 570/2129 [00:47<02:40,  9.70it/s]
 27%|██▋       | 572/2129 [00:47<02:30, 10.32it/s]
 27%|██▋       | 574/2129 [00:48<02:48,  9.20it/s]
 27%|██▋       | 576/2129 [00:48<02:27, 10.50it/s]
 27%|██▋       | 578/2129 [00:48<03:03,  8.44it/s]
 27%|██▋       | 580/2129 [00:48<02:40,  9.65it/s]
 27%|██▋       | 582/2129 [00:48<02:33, 10.05it/s]
 27%|██▋       | 584/2129 [00:49<03:12,  8.05it/s]
 27%|██▋       | 585/2129 [00:49<03:38,  7.07it/s]
 28%|██▊       | 586/2129 [00:49<03:30,  7.34it/s]
 28%|██▊       | 587/2129 [00:49<03:23,  7.58it/s]
 28%|██▊       | 589/2129 [00:49<03:04,  8.34it/s]
 28%|██▊       | 590/2129 [00:50<03:57,  6.47it/s]
 28%|██▊       | 592/2129 [00:50<03:09,  8.12it/s]
 28%|██▊       | 593/2129 [00:50<03:33,  7.18it/s]
 28%|██▊       | 595/2129 [00:50<03:04,  8.34it/s]
 28%|██▊       | 598/2129 [00:50<02:10, 11.76it/s]
 28%|██▊       | 600/2129 [00:51<03:04,  8.28it/s]
 28%|██▊       | 602/2129 [00:51<03:23,  7.51it/s]
 28%|██▊       | 604/2129 [00:51<03:05,  8.21it/s]
 28%|██▊       | 605/2129 [00:52<03:44,  6.79it/s]
 29%|██▊       | 607/2129 [00:52<02:55,  8.66it/s]
 29%|██▊       | 610/2129 [00:52<02:27, 10.33it/s]
 29%|██▊       | 612/2129 [00:52<02:55,  8.64it/s]
 29%|██▉       | 614/2129 [00:53<03:17,  7.67it/s]
 29%|██▉       | 617/2129 [00:53<02:21, 10.66it/s]
 29%|██▉       | 622/2129 [00:53<02:04, 12.06it/s]
 29%|██▉       | 626/2129 [00:53<02:12, 11.35it/s]
 29%|██▉       | 628/2129 [00:54<02:31,  9.88it/s]
 30%|██▉       | 631/2129 [00:54<02:03, 12.12it/s]
 30%|██▉       | 633/2129 [00:54<02:35,  9.60it/s]
 30%|██▉       | 635/2129 [00:54<02:31,  9.86it/s]
 30%|██▉       | 637/2129 [00:55<02:58,  8.38it/s]
 30%|███       | 639/2129 [00:55<02:35,  9.57it/s]
 30%|███       | 641/2129 [00:55<03:01,  8.19it/s]
 30%|███       | 644/2129 [00:55<02:47,  8.87it/s]
 30%|███       | 646/2129 [00:56<03:09,  7.83it/s]
 30%|███       | 649/2129 [00:56<03:10,  7.78it/s]
 31%|███       | 651/2129 [00:56<02:41,  9.13it/s]
 31%|███       | 653/2129 [00:57<02:52,  8.56it/s]
 31%|███       | 655/2129 [00:57<02:31,  9.70it/s]
 31%|███       | 658/2129 [00:57<03:02,  8.08it/s]
 31%|███       | 661/2129 [00:58<03:03,  7.99it/s]
 31%|███       | 662/2129 [00:58<03:19,  7.35it/s]
 31%|███       | 663/2129 [00:58<03:32,  6.89it/s]
 31%|███▏      | 666/2129 [00:58<02:25, 10.04it/s]
 31%|███▏      | 668/2129 [00:58<02:56,  8.29it/s]
 32%|███▏      | 672/2129 [00:59<02:25, 10.04it/s]
 32%|███▏      | 675/2129 [00:59<01:54, 12.70it/s]
 32%|███▏      | 677/2129 [00:59<02:20, 10.34it/s]
 32%|███▏      | 679/2129 [00:59<02:16, 10.59it/s]
 32%|███▏      | 682/2129 [01:00<02:32,  9.52it/s]
 32%|███▏      | 684/2129 [01:00<03:13,  7.46it/s]
 32%|███▏      | 685/2129 [01:00<03:20,  7.22it/s]
 32%|███▏      | 687/2129 [01:00<02:48,  8.58it/s]
 32%|███▏      | 689/2129 [01:01<02:59,  8.04it/s]
 32%|███▏      | 691/2129 [01:01<02:35,  9.25it/s]
 33%|███▎      | 694/2129 [01:01<02:30,  9.50it/s]
 33%|███▎      | 696/2129 [01:01<02:50,  8.43it/s]
 33%|███▎      | 699/2129 [01:02<02:07, 11.23it/s]
 33%|███▎      | 701/2129 [01:02<02:10, 10.91it/s]
 33%|███▎      | 704/2129 [01:02<01:45, 13.51it/s]
 33%|███▎      | 706/2129 [01:02<02:26,  9.70it/s]
 33%|███▎      | 708/2129 [01:03<03:08,  7.52it/s]
 33%|███▎      | 710/2129 [01:03<02:44,  8.61it/s]
 33%|███▎      | 712/2129 [01:03<02:24,  9.77it/s]
 34%|███▎      | 714/2129 [01:03<02:37,  8.99it/s]
 34%|███▎      | 716/2129 [01:03<02:18, 10.18it/s]
 34%|███▍      | 719/2129 [01:04<01:59, 11.78it/s]
 34%|███▍      | 721/2129 [01:04<02:28,  9.50it/s]
 34%|███▍      | 723/2129 [01:04<02:28,  9.50it/s]
 34%|███▍      | 725/2129 [01:04<02:18, 10.14it/s]
 34%|███▍      | 727/2129 [01:04<02:08, 10.87it/s]
 34%|███▍      | 729/2129 [01:05<02:32,  9.16it/s]
 34%|███▍      | 731/2129 [01:05<02:13, 10.46it/s]
 34%|███▍      | 733/2129 [01:05<02:23,  9.71it/s]
 35%|███▍      | 735/2129 [01:05<02:57,  7.86it/s]
 35%|███▍      | 739/2129 [01:06<02:19,  9.94it/s]
 35%|███▍      | 742/2129 [01:06<01:52, 12.34it/s]
 35%|███▌      | 749/2129 [01:06<01:03, 21.69it/s]
 35%|███▌      | 753/2129 [01:06<01:35, 14.35it/s]
 36%|███▌      | 756/2129 [01:07<02:02, 11.25it/s]
 36%|███▌      | 759/2129 [01:07<01:42, 13.34it/s]
 36%|███▌      | 762/2129 [01:07<01:56, 11.70it/s]
 36%|███▌      | 764/2129 [01:08<02:23,  9.52it/s]
 36%|███▌      | 766/2129 [01:08<02:34,  8.80it/s]
 36%|███▌      | 768/2129 [01:08<02:16,  9.96it/s]
 36%|███▌      | 770/2129 [01:08<02:43,  8.33it/s]
 36%|███▋      | 772/2129 [01:09<02:17,  9.88it/s]
 36%|███▋      | 774/2129 [01:09<02:22,  9.54it/s]
 36%|███▋      | 776/2129 [01:09<03:03,  7.37it/s]
 37%|███▋      | 778/2129 [01:09<02:34,  8.72it/s]
 37%|███▋      | 781/2129 [01:09<02:00, 11.19it/s]
 37%|███▋      | 783/2129 [01:10<02:18,  9.73it/s]
 37%|███▋      | 785/2129 [01:10<02:23,  9.35it/s]
 37%|███▋      | 787/2129 [01:10<02:20,  9.58it/s]
 37%|███▋      | 789/2129 [01:10<02:01, 11.01it/s]
 37%|███▋      | 792/2129 [01:11<01:49, 12.18it/s]
 37%|███▋      | 794/2129 [01:11<01:57, 11.37it/s]
 37%|███▋      | 796/2129 [01:11<02:03, 10.75it/s]
 37%|███▋      | 798/2129 [01:11<02:38,  8.40it/s]
 38%|███▊      | 800/2129 [01:12<03:03,  7.24it/s]
 38%|███▊      | 802/2129 [01:12<03:23,  6.54it/s]
 38%|███▊      | 805/2129 [01:12<02:26,  9.05it/s]
 38%|███▊      | 810/2129 [01:12<01:56, 11.33it/s]
 38%|███▊      | 812/2129 [01:13<01:45, 12.44it/s]
 38%|███▊      | 814/2129 [01:13<01:58, 11.06it/s]
 38%|███▊      | 816/2129 [01:13<01:48, 12.06it/s]
 38%|███▊      | 818/2129 [01:13<02:10, 10.02it/s]
 39%|███▊      | 820/2129 [01:14<02:32,  8.56it/s]
 39%|███▊      | 822/2129 [01:14<02:11,  9.96it/s]
 39%|███▉      | 827/2129 [01:14<01:58, 11.03it/s]
 39%|███▉      | 830/2129 [01:14<01:37, 13.26it/s]
 39%|███▉      | 832/2129 [01:14<01:44, 12.35it/s]
 39%|███▉      | 835/2129 [01:15<01:46, 12.13it/s]
 39%|███▉      | 838/2129 [01:15<02:03, 10.41it/s]
 39%|███▉      | 840/2129 [01:15<02:32,  8.44it/s]
 40%|███▉      | 842/2129 [01:16<02:32,  8.45it/s]
 40%|███▉      | 843/2129 [01:16<02:41,  7.95it/s]
 40%|███▉      | 845/2129 [01:16<03:18,  6.46it/s]
 40%|███▉      | 846/2129 [01:17<03:55,  5.45it/s]
 40%|███▉      | 848/2129 [01:17<03:30,  6.10it/s]
 40%|███▉      | 849/2129 [01:17<03:15,  6.56it/s]
 40%|███▉      | 851/2129 [01:17<02:32,  8.40it/s]
 40%|████      | 853/2129 [01:17<02:50,  7.49it/s]
 40%|████      | 854/2129 [01:18<03:41,  5.76it/s]
 40%|████      | 855/2129 [01:18<04:24,  4.82it/s]
 40%|████      | 857/2129 [01:18<03:09,  6.70it/s]
 40%|████      | 860/2129 [01:19<03:03,  6.92it/s]
 40%|████      | 862/2129 [01:19<02:40,  7.89it/s]
 41%|████      | 864/2129 [01:19<02:11,  9.62it/s]
 41%|████      | 866/2129 [01:19<02:27,  8.59it/s]
 41%|████      | 868/2129 [01:19<02:01, 10.35it/s]
 41%|████      | 870/2129 [01:20<02:32,  8.25it/s]
 41%|████      | 872/2129 [01:20<02:06,  9.91it/s]
 41%|████      | 875/2129 [01:20<01:35, 13.15it/s]
 41%|████      | 877/2129 [01:20<01:43, 12.15it/s]
 41%|████▏     | 879/2129 [01:20<01:41, 12.32it/s]
 41%|████▏     | 881/2129 [01:20<01:58, 10.50it/s]
 42%|████▏     | 884/2129 [01:21<01:38, 12.64it/s]
 42%|████▏     | 886/2129 [01:21<01:44, 11.90it/s]
 42%|████▏     | 888/2129 [01:21<02:07,  9.70it/s]
 42%|████▏     | 890/2129 [01:21<02:00, 10.31it/s]
 42%|████▏     | 893/2129 [01:22<01:59, 10.30it/s]
 42%|████▏     | 895/2129 [01:22<02:04,  9.88it/s]
 42%|████▏     | 898/2129 [01:22<02:00, 10.25it/s]
 42%|████▏     | 900/2129 [01:22<01:46, 11.58it/s]
 42%|████▏     | 902/2129 [01:23<02:33,  8.02it/s]
 42%|████▏     | 904/2129 [01:23<02:35,  7.89it/s]
 43%|████▎     | 906/2129 [01:23<02:36,  7.80it/s]
 43%|████▎     | 908/2129 [01:23<02:12,  9.20it/s]
 43%|████▎     | 910/2129 [01:23<02:00, 10.14it/s]
 43%|████▎     | 912/2129 [01:24<01:59, 10.15it/s]
 43%|████▎     | 914/2129 [01:24<01:51, 10.90it/s]
 43%|████▎     | 916/2129 [01:24<01:40, 12.03it/s]
 43%|████▎     | 919/2129 [01:24<01:21, 14.91it/s]
 43%|████▎     | 924/2129 [01:24<01:00, 19.95it/s]
 44%|████▎     | 927/2129 [01:25<01:47, 11.16it/s]
 44%|████▎     | 929/2129 [01:25<02:29,  8.04it/s]
 44%|████▎     | 931/2129 [01:26<02:42,  7.36it/s]
 44%|████▍     | 934/2129 [01:26<02:03,  9.66it/s]
 44%|████▍     | 936/2129 [01:26<02:12,  8.97it/s]
 44%|████▍     | 938/2129 [01:26<02:36,  7.61it/s]
 44%|████▍     | 940/2129 [01:27<02:45,  7.18it/s]
 44%|████▍     | 943/2129 [01:27<02:00,  9.84it/s]
 44%|████▍     | 945/2129 [01:27<02:11,  9.02it/s]
 44%|████▍     | 947/2129 [01:27<02:04,  9.50it/s]
 45%|████▍     | 950/2129 [01:28<01:57, 10.01it/s]
 45%|████▍     | 953/2129 [01:28<01:32, 12.76it/s]
 45%|████▍     | 958/2129 [01:28<01:17, 15.08it/s]
 45%|████▌     | 960/2129 [01:28<01:49, 10.66it/s]
 45%|████▌     | 962/2129 [01:28<01:47, 10.81it/s]
 45%|████▌     | 964/2129 [01:29<01:57,  9.91it/s]
 45%|████▌     | 967/2129 [01:29<01:55, 10.02it/s]
 46%|████▌     | 969/2129 [01:29<02:08,  9.00it/s]
 46%|████▌     | 971/2129 [01:29<01:52, 10.30it/s]
 46%|████▌     | 973/2129 [01:30<01:41, 11.41it/s]
 46%|████▌     | 975/2129 [01:30<02:12,  8.70it/s]
 46%|████▌     | 977/2129 [01:30<02:56,  6.52it/s]
 46%|████▌     | 978/2129 [01:31<02:50,  6.76it/s]
 46%|████▌     | 980/2129 [01:31<02:13,  8.61it/s]
 46%|████▌     | 982/2129 [01:31<02:12,  8.64it/s]
 46%|████▌     | 984/2129 [01:31<01:54, 10.01it/s]
 46%|████▋     | 988/2129 [01:31<01:45, 10.77it/s]
 47%|████▋     | 990/2129 [01:32<01:43, 10.96it/s]
 47%|████▋     | 992/2129 [01:32<01:38, 11.57it/s]
 47%|████▋     | 994/2129 [01:32<01:49, 10.37it/s]
 47%|████▋     | 996/2129 [01:32<01:38, 11.47it/s]
 47%|████▋     | 1001/2129 [01:32<01:05, 17.33it/s]
 47%|████▋     | 1003/2129 [01:32<01:12, 15.61it/s]
 47%|████▋     | 1005/2129 [01:32<01:12, 15.50it/s]
 47%|████▋     | 1007/2129 [01:33<01:50, 10.15it/s]
 47%|████▋     | 1009/2129 [01:33<01:41, 11.02it/s]
 47%|████▋     | 1011/2129 [01:33<01:39, 11.19it/s]
 48%|████▊     | 1013/2129 [01:33<01:40, 11.15it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 316.91it/s]

[[np.int64(0), False, 11], [np.int64(1), False, 8], [np.int64(2), False, 3], [np.int64(3), False, 13], [np.int64(4), False, 10], [np.int64(5), False, 1], [np.int64(6), False, 4], [np.int64(7), False, 9], [np.int64(8), False, 0], [np.int64(9), False, 13], [np.int64(12), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.1990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.0175, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [03:34<3:23:18, 61.30s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [03:34<2:21:46, 42.96s/it]

tensor(13.2033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.3643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.7937, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [03:35<48:09, 14.82s/it]

tensor(13.3325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0524, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1647, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [03:35<23:33,  7.32s/it]

tensor(13.4504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2309, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4527, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2440, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [03:35<16:31,  5.16s/it]

tensor(13.4226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3662, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6106, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [03:35<05:49,  1.85s/it]

tensor(13.3522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6790, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8129, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [03:35<03:01,  1.03it/s]

tensor(13.3217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8546, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9321, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [03:36<02:12,  1.40it/s]

tensor(13.2655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9885, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0857, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:36<01:16,  2.42it/s]

tensor(13.3030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1496, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1996, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [03:36<00:39,  4.54it/s]

tensor(13.2671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3198, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [03:36<00:30,  5.90it/s]

tensor(13.2236, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3009, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3309, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [03:37<00:25,  6.89it/s]

tensor(13.2014, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3876, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4555, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [03:37<00:23,  7.52it/s]

tensor(13.1669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1542, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5691, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [03:37<00:22,  7.61it/s]

tensor(13.1459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6241, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6794, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [03:37<00:21,  7.90it/s]

tensor(13.1418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7238, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7526, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [03:38<00:21,  8.05it/s]

tensor(13.1362, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7616, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7526, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [03:38<00:20,  8.18it/s]

tensor(13.1133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7954, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1089, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8345, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [03:38<00:20,  8.17it/s]

tensor(13.1049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8714, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9081, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [03:38<00:19,  8.22it/s]

tensor(13.0840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9459, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9715, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [03:39<00:19,  8.10it/s]

tensor(13.0614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9664, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9789, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [03:39<00:19,  8.17it/s]

tensor(13.0389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9888, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0154, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [03:39<00:18,  8.27it/s]

tensor(13.0251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0227, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0500, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:39<00:18,  8.26it/s]

tensor(13.0160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0940, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1378, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [03:40<00:18,  8.25it/s]

tensor(13.0027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1734, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9939, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2073, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:40<00:18,  8.09it/s]

tensor(12.9870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2072, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1205, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:40<00:18,  8.22it/s]

tensor(12.9804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1551, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([128, 209, 314, 213, 179, 219, 112,  56,  47,  55, 180, 114, 218,  85])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:30, 23.57it/s]
  0%|          | 10/2129 [00:00<00:44, 47.18it/s]
  1%|          | 15/2129 [00:00<00:49, 42.48it/s]
  1%|          | 20/2129 [00:00<00:49, 42.45it/s]
  1%|          | 26/2129 [00:00<00:44, 47.65it/s]
  1%|▏         | 31/2129 [00:00<00:46, 44.82it/s]
  2%|▏         | 36/2129 [00:00<00:49, 42.22it/s]
  2%|▏         | 43/2129 [00:00<00:43, 47.95it/s]
  2%|▏         | 49/2129 [00:01<00:42, 49.35it/s]
  3%|▎         | 54/2129 [00:01<00:45, 45.38it/s]
  3%|▎         | 59/2129 [00:01<00:49, 41.47it/s]
  3%|▎         | 64/2129 [00:01<00:49, 41.55it/s]
  3%|▎         | 69/2129 [00:01<00:47, 43.55it/s]
  3%|▎         | 74/2129 [00:01<00:46, 44.57it/s]
  4%|▎         | 79/2129 [00:01<00:50, 40.26it/s]
  4%|▍         | 84/2129 [00:01<00:49, 41.57it/s]
  4%|▍         | 91/2129 [00:02<00:42, 47.59it/s]
  5%|▍         | 98/2129 [00:02<00:38, 52.27it/s]
  5%|▍         | 105/2129 [00:02<00:36, 55.71it/s]
  5%|▌         | 111/2129 [00:02<00:41, 49.18it/s]
  5%|▌         | 117/2129 [00:02<00:47, 42.00it/s]
  6%|▌         | 124/2129 [00:02<00:42, 47.46it/s]
  6%|▌         | 130/2129 [00:02<00:40, 49.50it/s]
  6%|▋         | 136/2129 [00:02<00:39, 50.04it/s]
  7%|▋         | 142/2129 [00:03<00:37, 52.52it/s]
  7%|▋         | 149/2129 [00:03<00:34, 56.82it/s]
  7%|▋         | 155/2129 [00:03<00:45, 43.29it/s]
  8%|▊         | 160/2129 [00:03<01:02, 31.60it/s]
  8%|▊         | 166/2129 [00:03<00:54, 36.15it/s]
  8%|▊         | 171/2129 [00:03<00:51, 37.72it/s]
  8%|▊         | 176/2129 [00:03<00:49, 39.86it/s]
  9%|▊         | 183/2129 [00:04<00:42, 45.63it/s]
  9%|▉         | 190/2129 [00:04<00:59, 32.84it/s]
  9%|▉         | 195/2129 [00:04<01:07, 28.53it/s]
  9%|▉         | 201/2129 [00:04<00:58, 33.23it/s]
 10%|▉         | 208/2129 [00:04<00:49, 38.98it/s]
 10%|█         | 214/2129 [00:05<00:44, 42.80it/s]
 10%|█         | 221/2129 [00:05<00:39, 48.28it/s]
 11%|█         | 227/2129 [00:05<00:56, 33.81it/s]
 11%|█         | 232/2129 [00:05<00:57, 33.01it/s]
 11%|█         | 236/2129 [00:05<01:09, 27.22it/s]
 11%|█▏        | 240/2129 [00:06<01:34, 20.02it/s]
 12%|█▏        | 245/2129 [00:06<01:17, 24.19it/s]
 12%|█▏        | 250/2129 [00:06<01:24, 22.25it/s]
 12%|█▏        | 253/2129 [00:06<01:23, 22.38it/s]
 12%|█▏        | 259/2129 [00:06<01:04, 28.89it/s]
 12%|█▏        | 263/2129 [00:07<01:27, 21.33it/s]
 13%|█▎        | 269/2129 [00:07<01:08, 27.09it/s]
 13%|█▎        | 275/2129 [00:07<00:56, 32.83it/s]
 13%|█▎        | 281/2129 [00:07<00:49, 37.35it/s]
 13%|█▎        | 287/2129 [00:07<00:58, 31.28it/s]
 14%|█▎        | 291/2129 [00:07<01:02, 29.56it/s]
 14%|█▍        | 295/2129 [00:08<01:25, 21.50it/s]
 14%|█▍        | 302/2129 [00:08<01:02, 29.20it/s]
 14%|█▍        | 306/2129 [00:08<01:18, 23.13it/s]
 15%|█▍        | 310/2129 [00:08<01:12, 25.21it/s]
 15%|█▍        | 314/2129 [00:09<01:30, 19.99it/s]
 44%|████▍     | 937/2129 [00:43<01:39, 11.93it/s]
 44%|████▍     | 939/2129 [00:43<01:48, 10.97it/s]
 44%|████▍     | 943/2129 [00:43<01:37, 12.13it/s]
 44%|████▍     | 945/2129 [00:43<02:04,  9.49it/s]
 44%|████▍     | 947/2129 [00:44<02:11,  9.00it/s]
 45%|████▍     | 950/2129 [00:44<02:02,  9.65it/s]
 45%|████▍     | 953/2129 [00:44<01:37, 12.01it/s]
 45%|████▍     | 955/2129 [00:44<01:42, 11.47it/s]
 45%|████▍     | 957/2129 [00:44<01:34, 12.47it/s]
 45%|████▌     | 959/2129 [00:45<01:46, 10.97it/s]
 45%|████▌     | 961/2129 [00:45<02:18,  8.44it/s]
 45%|████▌     | 963/2129 [00:45<02:17,  8.48it/s]
 45%|████▌     | 966/2129 [00:45<01:44, 11.17it/s]
 45%|████▌     | 968/2129 [00:46<02:23,  8.07it/s]
 46%|████▌     | 971/2129 [00:46<01:48, 10.70it/s]
 46%|████▌     | 973/2129 [00:46<01:52, 10.29it/s]
 46%|████▌     | 975/2129 [00:46<02:06,  9.13it/s]
 46%|████▌     | 979/2129 [00:47<01:25, 13.41it/s]
 46%|████▋     | 985/2129 [00:47<00:55, 20.78it/s]
 46%|████▋     | 988/2129 [00:47<01:03, 17.93it/s]
 47%|████▋     | 991/2129 [00:47<00:57, 19.82it/s]
 47%|████▋     | 994/2129 [00:47<01:09, 16.38it/s]
 47%|████▋     | 997/2129 [00:47<01:01, 18.46it/s]
 47%|████▋     | 1001/2129 [00:48<01:00, 18.52it/s]
 47%|████▋     | 1004/2129 [00:48<01:15, 14.91it/s]
 47%|████▋     | 1007/2129 [00:48<01:23, 13.41it/s]
 47%|████▋     | 1010/2129 [00:48<01:28, 12.59it/s]
 48%|████▊     | 1012/2129 [00:49<01:24, 13.28it/s]
 48%|████▊     | 1015/2129 [00:49<01:14, 14.97it/s]
 48%|████▊     | 1019/2129 [00:49<01:12, 15.38it/s]
 48%|████▊     | 1023/2129 [00:49<01:14, 14.86it/s]
 48%|████▊     | 1025/2129 [00:50<01:25, 12.88it/s]
 48%|████▊     | 1027/2129 [00:50<01:20, 13.76it/s]
 48%|████▊     | 1029/2129 [00:50<01:42, 10.74it/s]
 48%|████▊     | 1032/2129 [00:50<01:20, 13.62it/s]
 49%|████▊     | 1036/2129 [00:50<01:00, 18.07it/s]
 49%|████▉     | 1042/2129 [00:50<00:41, 26.51it/s]
 49%|████▉     | 1047/2129 [00:50<00:35, 30.65it/s]
 49%|████▉     | 1051/2129 [00:51<00:49, 21.91it/s]
 50%|████▉     | 1055/2129 [00:51<00:56, 19.02it/s]
 50%|████▉     | 1058/2129 [00:52<01:36, 11.15it/s]
 50%|████▉     | 1060/2129 [00:52<01:42, 10.47it/s]
 50%|████▉     | 1062/2129 [00:52<01:31, 11.62it/s]
 50%|████▉     | 1064/2129 [00:52<01:38, 10.76it/s]
 50%|█████     | 1067/2129 [00:52<01:21, 13.00it/s]
 50%|█████     | 1069/2129 [00:53<01:28, 12.00it/s]
 50%|█████     | 1071/2129 [00:53<01:47,  9.81it/s]
 50%|█████     | 1073/2129 [00:53<01:35, 11.09it/s]
 50%|█████     | 1075/2129 [00:53<01:23, 12.58it/s]
 51%|█████     | 1080/2129 [00:53<01:07, 15.64it/s]
 51%|█████     | 1083/2129 [00:53<01:01, 17.14it/s]
 51%|█████     | 1086/2129 [00:54<00:53, 19.38it/s]
 51%|█████     | 1090/2129 [00:54<00:44, 23.18it/s]
 51%|█████▏    | 1093/2129 [00:54<00:53, 19.38it/s]
 51%|█████▏    | 1096/2129 [00:54<00:57, 18.07it/s]
 52%|█████▏    | 1100/2129 [00:54<00:46, 22.28it/s]
 52%|█████▏    | 1103/2129 [00:54<01:01, 16.71it/s]
 52%|█████▏    | 1106/2129 [00:55<01:17, 13.18it/s]
 52%|█████▏    | 1108/2129 [00:55<01:28, 11.58it/s]
 52%|█████▏    | 1110/2129 [00:55<01:22, 12.39it/s]
 52%|█████▏    | 1112/2129 [00:55<01:28, 11.43it/s]
 52%|█████▏    | 1114/2129 [00:56<01:37, 10.41it/s]
 52%|█████▏    | 1116/2129 [00:56<01:49,  9.22it/s]
 53%|█████▎    | 1118/2129 [00:56<02:00,  8.41it/s]
 53%|█████▎    | 1120/2129 [00:56<02:05,  8.02it/s]
 53%|█████▎    | 1122/2129 [00:57<01:44,  9.61it/s]
 53%|█████▎    | 1126/2129 [00:57<01:27, 11.50it/s]
 53%|█████▎    | 1128/2129 [00:57<01:20, 12.37it/s]
 53%|█████▎    | 1130/2129 [00:57<01:33, 10.67it/s]
 53%|█████▎    | 1133/2129 [00:57<01:13, 13.52it/s]
 53%|█████▎    | 1136/2129 [00:58<01:06, 14.90it/s]
 53%|█████▎    | 1138/2129 [00:58<01:20, 12.35it/s]
 54%|█████▎    | 1140/2129 [00:58<01:29, 11.08it/s]
 54%|█████▎    | 1142/2129 [00:58<01:22, 11.91it/s]
 54%|█████▍    | 1145/2129 [00:58<01:15, 12.98it/s]
 54%|█████▍    | 1147/2129 [00:59<01:20, 12.23it/s]
 54%|█████▍    | 1151/2129 [00:59<00:57, 16.98it/s]
 54%|█████▍    | 1153/2129 [00:59<01:15, 12.92it/s]
 54%|█████▍    | 1156/2129 [00:59<01:18, 12.45it/s]
 54%|█████▍    | 1158/2129 [00:59<01:12, 13.35it/s]
 54%|█████▍    | 1160/2129 [01:00<01:22, 11.80it/s]
 55%|█████▍    | 1163/2129 [01:00<01:05, 14.69it/s]
 55%|█████▍    | 1169/2129 [01:00<00:57, 16.56it/s]
 55%|█████▌    | 1172/2129 [01:00<00:53, 17.89it/s]
 55%|█████▌    | 1176/2129 [01:00<00:56, 16.85it/s]
 55%|█████▌    | 1178/2129 [01:00<00:57, 16.57it/s]
 55%|█████▌    | 1180/2129 [01:01<01:06, 14.22it/s]
 56%|█████▌    | 1182/2129 [01:01<01:45,  9.01it/s]
 56%|█████▌    | 1184/2129 [01:01<01:32, 10.23it/s]
 56%|█████▌    | 1186/2129 [01:01<01:32, 10.22it/s]
 56%|█████▌    | 1189/2129 [01:02<01:13, 12.79it/s]
 56%|█████▌    | 1191/2129 [01:02<01:23, 11.17it/s]
 56%|█████▌    | 1193/2129 [01:02<01:36,  9.75it/s]
 56%|█████▌    | 1195/2129 [01:02<01:38,  9.47it/s]
 56%|█████▌    | 1197/2129 [01:03<02:04,  7.50it/s]
 56%|█████▋    | 1200/2129 [01:03<01:32, 10.08it/s]
 57%|█████▋    | 1206/2129 [01:03<01:06, 13.87it/s]
 57%|█████▋    | 1208/2129 [01:03<01:06, 13.84it/s]
 57%|█████▋    | 1212/2129 [01:03<00:51, 17.75it/s]
 57%|█████▋    | 1215/2129 [01:04<00:57, 15.84it/s]
 57%|█████▋    | 1218/2129 [01:04<01:03, 14.33it/s]
 57%|█████▋    | 1220/2129 [01:04<01:12, 12.53it/s]
 57%|█████▋    | 1222/2129 [01:05<01:37,  9.28it/s]
 57%|█████▋    | 1224/2129 [01:05<01:39,  9.09it/s]
 58%|█████▊    | 1226/2129 [01:05<01:25, 10.60it/s]
 58%|█████▊    | 1231/2129 [01:05<01:03, 14.04it/s]
 58%|█████▊    | 1233/2129 [01:05<01:17, 11.61it/s]
 58%|█████▊    | 1236/2129 [01:06<01:03, 14.09it/s]
 58%|█████▊    | 1238/2129 [01:06<01:14, 12.00it/s]
 58%|█████▊    | 1241/2129 [01:06<01:00, 14.61it/s]
 59%|█████▊    | 1247/2129 [01:06<00:51, 16.98it/s]
 59%|█████▊    | 1249/2129 [01:06<00:51, 17.16it/s]
 59%|█████▉    | 1251/2129 [01:07<00:59, 14.77it/s]
 59%|█████▉    | 1253/2129 [01:07<01:16, 11.44it/s]
 59%|█████▉    | 1255/2129 [01:07<01:08, 12.77it/s]
 59%|█████▉    | 1257/2129 [01:07<01:20, 10.80it/s]
 59%|█████▉    | 1260/2129 [01:07<01:19, 10.94it/s]
 59%|█████▉    | 1263/2129 [01:08<01:17, 11.12it/s]
 59%|█████▉    | 1266/2129 [01:08<01:04, 13.46it/s]
 60%|█████▉    | 1270/2129 [01:08<00:59, 14.40it/s]
 60%|█████▉    | 1272/2129 [01:08<01:21, 10.50it/s]
 60%|█████▉    | 1274/2129 [01:09<01:27,  9.75it/s]
 60%|█████▉    | 1276/2129 [01:09<01:40,  8.45it/s]
 60%|██████    | 1279/2129 [01:09<01:34,  9.04it/s]
 60%|██████    | 1281/2129 [01:09<01:25,  9.89it/s]
 60%|██████    | 1283/2129 [01:10<01:27,  9.69it/s]
 60%|██████    | 1286/2129 [01:10<01:13, 11.40it/s]
 60%|██████    | 1288/2129 [01:10<01:24, 10.01it/s]
 61%|██████    | 1290/2129 [01:10<01:18, 10.74it/s]
 61%|██████    | 1292/2129 [01:10<01:12, 11.55it/s]
 61%|██████    | 1294/2129 [01:11<01:23, 10.01it/s]
 61%|██████    | 1297/2129 [01:11<01:09, 12.03it/s]
 61%|██████    | 1299/2129 [01:11<01:12, 11.51it/s]
 61%|██████    | 1301/2129 [01:11<01:06, 12.54it/s]
 61%|██████    | 1303/2129 [01:11<01:05, 12.57it/s]
 61%|██████▏   | 1305/2129 [01:12<01:07, 12.27it/s]
 61%|██████▏   | 1308/2129 [01:12<00:51, 15.81it/s]
 62%|██████▏   | 1315/2129 [01:12<00:40, 20.04it/s]
 62%|██████▏   | 1318/2129 [01:12<00:48, 16.61it/s]
 62%|██████▏   | 1320/2129 [01:12<00:59, 13.62it/s]
 62%|██████▏   | 1322/2129 [01:13<01:25,  9.47it/s]
 62%|██████▏   | 1324/2129 [01:13<01:31,  8.78it/s]
 62%|██████▏   | 1327/2129 [01:13<01:11, 11.26it/s]
 62%|██████▏   | 1329/2129 [01:14<01:24,  9.48it/s]
 63%|██████▎   | 1331/2129 [01:14<01:27,  9.13it/s]
 63%|██████▎   | 1333/2129 [01:14<01:16, 10.47it/s]
 63%|██████▎   | 1337/2129 [01:14<00:52, 15.09it/s]
 63%|██████▎   | 1339/2129 [01:14<00:59, 13.22it/s]
 63%|██████▎   | 1341/2129 [01:14<00:55, 14.23it/s]
 63%|██████▎   | 1343/2129 [01:15<01:07, 11.64it/s]
 63%|██████▎   | 1349/2129 [01:15<00:49, 15.67it/s]
 64%|██████▎   | 1352/2129 [01:15<00:56, 13.77it/s]
 64%|██████▎   | 1355/2129 [01:15<00:50, 15.42it/s]
 64%|██████▍   | 1359/2129 [01:16<00:50, 15.11it/s]
 64%|██████▍   | 1362/2129 [01:16<00:44, 17.39it/s]
 64%|██████▍   | 1365/2129 [01:16<00:44, 17.26it/s]
 64%|██████▍   | 1367/2129 [01:16<00:48, 15.83it/s]
 64%|██████▍   | 1371/2129 [01:16<00:41, 18.37it/s]
 64%|██████▍   | 1373/2129 [01:16<00:50, 15.11it/s]
 65%|██████▍   | 1375/2129 [01:17<01:00, 12.41it/s]
 65%|██████▍   | 1377/2129 [01:17<01:13, 10.18it/s]
 65%|██████▍   | 1379/2129 [01:17<01:09, 10.81it/s]
 65%|██████▍   | 1382/2129 [01:17<00:54, 13.65it/s]
 65%|██████▌   | 1384/2129 [01:17<01:04, 11.55it/s]
 65%|██████▌   | 1386/2129 [01:18<00:57, 12.91it/s]
 65%|██████▌   | 1388/2129 [01:18<00:52, 14.20it/s]
 65%|██████▌   | 1390/2129 [01:18<00:54, 13.67it/s]
 65%|██████▌   | 1393/2129 [01:18<00:50, 14.52it/s]
 66%|██████▌   | 1395/2129 [01:18<00:53, 13.79it/s]
 66%|██████▌   | 1399/2129 [01:18<00:38, 18.90it/s]
 66%|██████▌   | 1402/2129 [01:18<00:35, 20.38it/s]
 66%|██████▌   | 1405/2129 [01:19<00:58, 12.37it/s]
 66%|██████▌   | 1408/2129 [01:19<00:50, 14.38it/s]
 66%|██████▌   | 1410/2129 [01:19<00:55, 12.87it/s]
 66%|██████▋   | 1412/2129 [01:19<01:00, 11.78it/s]
 66%|██████▋   | 1414/2129 [01:20<01:13,  9.77it/s]
 67%|██████▋   | 1418/2129 [01:20<00:49, 14.27it/s]
 67%|██████▋   | 1420/2129 [01:20<00:56, 12.64it/s]
 67%|██████▋   | 1423/2129 [01:20<00:45, 15.58it/s]
 67%|██████▋   | 1428/2129 [01:20<00:40, 17.13it/s]
 67%|██████▋   | 1431/2129 [01:21<00:37, 18.65it/s]
 67%|██████▋   | 1437/2129 [01:21<00:25, 26.66it/s]
 68%|██████▊   | 1441/2129 [01:21<00:32, 20.90it/s]
 68%|██████▊   | 1444/2129 [01:21<00:42, 16.15it/s]
 68%|██████▊   | 1448/2129 [01:21<00:34, 19.75it/s]
 68%|██████▊   | 1452/2129 [01:22<00:35, 19.04it/s]
 68%|██████▊   | 1455/2129 [01:22<00:32, 20.69it/s]
 68%|██████▊   | 1458/2129 [01:22<00:49, 13.64it/s]
 69%|██████▊   | 1460/2129 [01:22<00:47, 14.04it/s]
 69%|██████▊   | 1462/2129 [01:22<00:53, 12.45it/s]
 69%|██████▉   | 1464/2129 [01:23<00:50, 13.05it/s]
 69%|██████▉   | 1467/2129 [01:23<00:50, 13.01it/s]
 69%|██████▉   | 1469/2129 [01:23<00:56, 11.63it/s]
 69%|██████▉   | 1471/2129 [01:23<01:12,  9.10it/s]
 69%|██████▉   | 1475/2129 [01:24<00:50, 13.01it/s]
 69%|██████▉   | 1477/2129 [01:24<00:57, 11.42it/s]
 69%|██████▉   | 1479/2129 [01:24<01:00, 10.78it/s]
 70%|██████▉   | 1481/2129 [01:24<00:53, 12.12it/s]
 70%|██████▉   | 1483/2129 [01:24<00:59, 10.78it/s]
 70%|██████▉   | 1485/2129 [01:25<01:07,  9.53it/s]
 70%|██████▉   | 1488/2129 [01:25<00:51, 12.46it/s]
 70%|███████   | 1496/2129 [01:25<00:26, 23.86it/s]
 70%|███████   | 1500/2129 [01:25<00:40, 15.57it/s]
 71%|███████   | 1503/2129 [01:26<00:39, 15.75it/s]
 71%|███████   | 1506/2129 [01:26<00:55, 11.14it/s]
 71%|███████   | 1510/2129 [01:26<00:43, 14.17it/s]
 71%|███████   | 1513/2129 [01:27<00:57, 10.71it/s]
 71%|███████   | 1515/2129 [01:27<00:58, 10.43it/s]
 71%|███████▏  | 1518/2129 [01:27<00:48, 12.64it/s]
 72%|███████▏  | 1524/2129 [01:27<00:32, 18.49it/s]
 72%|███████▏  | 1527/2129 [01:28<00:49, 12.27it/s]
 72%|███████▏  | 1530/2129 [01:28<00:44, 13.35it/s]
 72%|███████▏  | 1532/2129 [01:28<01:01,  9.68it/s]
 72%|███████▏  | 1535/2129 [01:28<00:50, 11.68it/s]
 72%|███████▏  | 1538/2129 [01:29<00:48, 12.26it/s]
 72%|███████▏  | 1540/2129 [01:29<01:05,  8.97it/s]
 72%|███████▏  | 1542/2129 [01:29<01:07,  8.66it/s]
 73%|███████▎  | 1544/2129 [01:30<01:11,  8.16it/s]
 73%|███████▎  | 1545/2129 [01:30<01:20,  7.24it/s]
 73%|███████▎  | 1548/2129 [01:30<00:58,  9.93it/s]
 73%|███████▎  | 1555/2129 [01:30<00:29, 19.33it/s]
 73%|███████▎  | 1559/2129 [01:30<00:29, 19.37it/s]
 73%|███████▎  | 1562/2129 [01:31<00:36, 15.62it/s]
 74%|███████▎  | 1565/2129 [01:31<00:32, 17.46it/s]
 74%|███████▎  | 1570/2129 [01:31<00:30, 18.44it/s]
 74%|███████▍  | 1573/2129 [01:31<00:38, 14.28it/s]
 74%|███████▍  | 1575/2129 [01:31<00:39, 14.16it/s]
 74%|███████▍  | 1578/2129 [01:32<00:36, 15.21it/s]
 74%|███████▍  | 1580/2129 [01:32<00:36, 15.14it/s]
 74%|███████▍  | 1583/2129 [01:32<00:37, 14.65it/s]
 74%|███████▍  | 1586/2129 [01:32<00:38, 14.14it/s]
 75%|███████▍  | 1588/2129 [01:32<00:46, 11.53it/s]
 75%|███████▍  | 1590/2129 [01:33<00:51, 10.38it/s]
 75%|███████▍  | 1592/2129 [01:33<00:45, 11.73it/s]
 75%|███████▍  | 1595/2129 [01:33<00:43, 12.27it/s]
 75%|███████▌  | 1597/2129 [01:33<00:40, 13.18it/s]
 75%|███████▌  | 1599/2129 [01:33<00:40, 13.07it/s]
 75%|███████▌  | 1601/2129 [01:33<00:40, 13.19it/s]
 75%|███████▌  | 1603/2129 [01:34<00:38, 13.65it/s]
 75%|███████▌  | 1605/2129 [01:34<00:38, 13.50it/s]
 75%|███████▌  | 1607/2129 [01:34<00:41, 12.51it/s]
 76%|███████▌  | 1609/2129 [01:34<00:38, 13.54it/s]
 76%|███████▌  | 1611/2129 [01:34<00:36, 14.03it/s]
 76%|███████▌  | 1613/2129 [01:34<00:39, 13.09it/s]
 76%|███████▌  | 1616/2129 [01:34<00:31, 16.53it/s]
 76%|███████▌  | 1622/2129 [01:35<00:19, 26.03it/s]
 76%|███████▋  | 1627/2129 [01:35<00:22, 21.94it/s]
 77%|███████▋  | 1630/2129 [01:35<00:28, 17.81it/s]
 77%|███████▋  | 1633/2129 [01:35<00:33, 14.61it/s]
 77%|███████▋  | 1635/2129 [01:35<00:33, 14.93it/s]
 77%|███████▋  | 1640/2129 [01:36<00:24, 20.26it/s]
 77%|███████▋  | 1643/2129 [01:36<00:28, 16.79it/s]
 77%|███████▋  | 1646/2129 [01:36<00:27, 17.66it/s]
 78%|███████▊  | 1650/2129 [01:36<00:28, 16.54it/s]
 78%|███████▊  | 1652/2129 [01:37<00:35, 13.61it/s]
 78%|███████▊  | 1655/2129 [01:37<00:29, 15.98it/s]
 78%|███████▊  | 1657/2129 [01:37<00:34, 13.61it/s]
 78%|███████▊  | 1659/2129 [01:37<00:33, 14.23it/s]
 78%|███████▊  | 1662/2129 [01:37<00:33, 14.03it/s]
 78%|███████▊  | 1665/2129 [01:37<00:28, 16.53it/s]
 78%|███████▊  | 1667/2129 [01:38<00:34, 13.47it/s]
 78%|███████▊  | 1670/2129 [01:38<00:28, 16.38it/s]
 79%|███████▊  | 1672/2129 [01:38<00:32, 13.88it/s]
 79%|███████▊  | 1675/2129 [01:38<00:27, 16.41it/s]
 79%|███████▉  | 1680/2129 [01:38<00:25, 17.50it/s]
 79%|███████▉  | 1682/2129 [01:39<00:38, 11.48it/s]
 79%|███████▉  | 1684/2129 [01:39<00:41, 10.68it/s]
 79%|███████▉  | 1686/2129 [01:39<00:37, 11.77it/s]
 79%|███████▉  | 1692/2129 [01:39<00:22, 19.67it/s]
 80%|███████▉  | 1695/2129 [01:39<00:20, 21.14it/s]
 80%|███████▉  | 1701/2129 [01:39<00:14, 28.82it/s]
 80%|████████  | 1705/2129 [01:40<00:20, 20.93it/s]
 80%|████████  | 1711/2129 [01:40<00:15, 27.37it/s]
 81%|████████  | 1717/2129 [01:40<00:15, 26.41it/s]
 81%|████████  | 1721/2129 [01:40<00:15, 26.96it/s]
 81%|████████  | 1727/2129 [01:40<00:12, 33.33it/s]
 81%|████████▏ | 1733/2129 [01:40<00:10, 36.73it/s]
 82%|████████▏ | 1738/2129 [01:41<00:16, 23.29it/s]
 82%|████████▏ | 1742/2129 [01:41<00:23, 16.51it/s]
 82%|████████▏ | 1746/2129 [01:41<00:20, 19.09it/s]
 82%|████████▏ | 1752/2129 [01:42<00:15, 25.08it/s]
 83%|████████▎ | 1758/2129 [01:42<00:11, 31.17it/s]
 83%|████████▎ | 1763/2129 [01:42<00:19, 18.66it/s]
 83%|████████▎ | 1767/2129 [01:42<00:22, 16.43it/s]
 83%|████████▎ | 1774/2129 [01:43<00:15, 22.88it/s]
 84%|████████▎ | 1778/2129 [01:43<00:15, 22.20it/s]
 84%|████████▎ | 1782/2129 [01:43<00:15, 22.17it/s]
 84%|████████▍ | 1785/2129 [01:43<00:17, 19.75it/s]
 84%|████████▍ | 1788/2129 [01:43<00:19, 17.81it/s]
 84%|████████▍ | 1791/2129 [01:44<00:19, 17.61it/s]
 84%|████████▍ | 1796/2129 [01:44<00:14, 22.83it/s]
 85%|████████▍ | 1801/2129 [01:44<00:11, 27.71it/s]
 85%|████████▍ | 1807/2129 [01:44<00:09, 33.81it/s]
 85%|████████▌ | 1811/2129 [01:44<00:09, 33.98it/s]
 85%|████████▌ | 1815/2129 [01:44<00:09, 33.04it/s]
 85%|████████▌ | 1820/2129 [01:44<00:08, 36.20it/s]
 86%|████████▌ | 1824/2129 [01:44<00:10, 28.66it/s]
 86%|████████▌ | 1828/2129 [01:45<00:11, 26.87it/s]
 86%|████████▌ | 1834/2129 [01:45<00:08, 33.33it/s]
 86%|████████▋ | 1838/2129 [01:45<00:11, 25.47it/s]
 87%|████████▋ | 1842/2129 [01:45<00:10, 26.60it/s]
 87%|████████▋ | 1846/2129 [01:45<00:11, 24.76it/s]
 87%|████████▋ | 1849/2129 [01:45<00:12, 23.32it/s]
 87%|████████▋ | 1852/2129 [01:46<00:16, 16.98it/s]
 87%|████████▋ | 1857/2129 [01:46<00:12, 22.42it/s]
 87%|████████▋ | 1862/2129 [01:46<00:09, 27.32it/s]
 88%|████████▊ | 1866/2129 [01:46<00:09, 26.65it/s]
 88%|████████▊ | 1870/2129 [01:46<00:11, 22.42it/s]
 88%|████████▊ | 1873/2129 [01:47<00:11, 21.94it/s]
 88%|████████▊ | 1877/2129 [01:47<00:10, 24.25it/s]
 88%|████████▊ | 1881/2129 [01:47<00:09, 27.38it/s]
 89%|████████▊ | 1887/2129 [01:47<00:07, 34.57it/s]
 89%|████████▉ | 1893/2129 [01:47<00:05, 40.14it/s]
 89%|████████▉ | 1898/2129 [01:47<00:06, 36.84it/s]
 89%|████████▉ | 1904/2129 [01:47<00:05, 40.04it/s]
 90%|████████▉ | 1910/2129 [01:47<00:05, 42.95it/s]
 90%|████████▉ | 1915/2129 [01:48<00:05, 36.94it/s]
 90%|█████████ | 1919/2129 [01:48<00:05, 35.22it/s]
 90%|█████████ | 1923/2129 [01:48<00:06, 32.21it/s]
 91%|█████████ | 1929/2129 [01:48<00:05, 37.80it/s]
 91%|█████████ | 1936/2129 [01:48<00:04, 44.18it/s]
 91%|█████████▏| 1945/2129 [01:48<00:03, 54.33it/s]
 92%|█████████▏| 1951/2129 [01:49<00:04, 38.35it/s]
 92%|█████████▏| 1956/2129 [01:49<00:04, 38.48it/s]
 92%|█████████▏| 1961/2129 [01:49<00:04, 34.82it/s]
 92%|█████████▏| 1965/2129 [01:49<00:04, 33.02it/s]
 92%|█████████▏| 1969/2129 [01:49<00:04, 33.44it/s]
 93%|█████████▎| 1974/2129 [01:49<00:04, 35.68it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 333.05it/s]

[[np.int64(0), False, 10], [np.int64(1), False, 12], [np.int64(2), False, 3], [np.int64(4), False, 0], [np.int64(5), False, 10], [np.int64(6), False, 2], [np.int64(7), False, 9], [np.int64(8), False, 11], [np.int64(11), False, 12], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5019, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [05:37<1:27:23, 35.19s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [05:37<1:00:51, 24.67s/it]

tensor(12.9880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6878, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [05:38<20:38,  8.54s/it]

tensor(12.9722, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7876, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9137, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [05:38<14:26,  6.02s/it]

tensor(12.9581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0832, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [05:38<07:07,  3.01s/it]

tensor(12.9431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1614, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [05:38<02:34,  1.11s/it]

tensor(12.9175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2260, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0449, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1766, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [05:38<01:23,  1.65it/s]

tensor(12.8933, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0458, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0467, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2263, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [05:39<01:02,  2.17it/s]

tensor(12.8702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2511, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3098, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [05:39<00:39,  3.40it/s]

tensor(12.8521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0542, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3086, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8446, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0539, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3427, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [05:39<00:27,  4.85it/s]

tensor(12.8370, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0501, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3729, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [05:39<00:19,  6.62it/s]

tensor(12.8152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0482, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3849, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0455, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3820, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [05:40<00:18,  7.04it/s]

tensor(12.7994, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0430, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7931, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4087, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [05:40<00:16,  7.57it/s]

tensor(12.7866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4159, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0392, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4269, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [05:40<00:15,  8.00it/s]

tensor(12.7774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0379, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4293, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4377, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [05:40<00:15,  8.04it/s]

tensor(12.7638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4417, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7555, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4470, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [05:41<00:14,  8.11it/s]

tensor(12.7484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4522, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7415, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4553, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [05:41<00:14,  8.16it/s]

tensor(12.7358, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4651, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [05:41<00:14,  8.19it/s]

tensor(12.7261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4728, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4715, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [05:41<00:13,  8.20it/s]

tensor(12.7157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4708, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4710, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [05:42<00:13,  8.19it/s]

tensor(12.7052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4706, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4721, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [05:42<00:13,  8.18it/s]

tensor(12.6950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3203, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [05:42<00:13,  8.20it/s]

tensor(12.6859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3789, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4231, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [05:42<00:12,  8.21it/s]

tensor(12.6776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0429, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4555, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [05:43<00:12,  8.21it/s]

tensor(12.6698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0454, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4543, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [05:43<00:12,  8.17it/s]

tensor(12.6610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4577, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4582, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [05:43<00:12,  8.20it/s]

tensor(12.6516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0435, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4587, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([283, 200, 202, 147, 177, 154, 172, 118,  53, 122, 213,  72,  76, 140])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<01:56, 18.27it/s]
  0%|          | 8/2129 [00:00<00:51, 41.01it/s]
  1%|          | 14/2129 [00:00<00:43, 49.06it/s]
  1%|          | 20/2129 [00:00<00:43, 48.15it/s]
  1%|          | 26/2129 [00:00<00:40, 51.55it/s]
  2%|▏         | 32/2129 [00:00<00:39, 52.78it/s]
  2%|▏         | 38/2129 [00:00<00:39, 53.50it/s]
  2%|▏         | 45/2129 [00:00<00:36, 57.75it/s]
  2%|▏         | 52/2129 [00:00<00:36, 57.47it/s]
  3%|▎         | 60/2129 [00:01<00:33, 62.59it/s]
  3%|▎         | 67/2129 [00:01<00:37, 55.71it/s]
  3%|▎         | 73/2129 [00:01<00:38, 52.80it/s]
  4%|▎         | 79/2129 [00:01<00:39, 51.76it/s]
  4%|▍         | 85/2129 [00:01<00:47, 42.73it/s]
  4%|▍         | 90/2129 [00:01<00:47, 42.64it/s]
  5%|▍         | 97/2129 [00:01<00:41, 48.92it/s]
  5%|▍         | 103/2129 [00:02<00:46, 43.86it/s]
  5%|▌         | 109/2129 [00:02<00:43, 46.25it/s]
  5%|▌         | 115/2129 [00:02<00:40, 49.50it/s]
  6%|▌         | 121/2129 [00:02<00:40, 49.83it/s]
  6%|▌         | 127/2129 [00:02<00:39, 50.73it/s]
  6%|▌         | 133/2129 [00:02<00:38, 51.34it/s]
  7%|▋         | 139/2129 [00:02<00:43, 45.49it/s]
  7%|▋         | 144/2129 [00:02<00:46, 42.84it/s]
  7%|▋         | 151/2129 [00:03<00:41, 48.21it/s]
  7%|▋         | 159/2129 [00:03<00:35, 54.96it/s]
  8%|▊         | 166/2129 [00:03<00:34, 57.14it/s]
  8%|▊         | 172/2129 [00:03<00:34, 56.64it/s]
  8%|▊         | 178/2129 [00:03<00:34, 56.18it/s]
  9%|▊         | 184/2129 [00:03<00:35, 55.12it/s]
  9%|▉         | 190/2129 [00:03<00:36, 53.62it/s]
  9%|▉         | 196/2129 [00:03<00:35, 53.90it/s]
  9%|▉         | 202/2129 [00:03<00:35, 54.29it/s]
 10%|▉         | 209/2129 [00:04<00:33, 57.20it/s]
 10%|█         | 217/2129 [00:04<00:34, 55.37it/s]
 11%|█         | 224/2129 [00:04<00:34, 54.50it/s]
 11%|█         | 231/2129 [00:04<00:32, 57.75it/s]
 11%|█         | 237/2129 [00:05<01:10, 26.82it/s]
 11%|█▏        | 244/2129 [00:05<00:57, 32.82it/s]
 12%|█▏        | 250/2129 [00:05<01:23, 22.61it/s]
 12%|█▏        | 254/2129 [00:05<01:21, 23.04it/s]
 12%|█▏        | 260/2129 [00:05<01:06, 28.31it/s]
 12%|█▏        | 265/2129 [00:06<01:43, 17.94it/s]
 13%|█▎        | 270/2129 [00:06<01:26, 21.57it/s]
 13%|█▎        | 276/2129 [00:06<01:10, 26.35it/s]
 13%|█▎        | 282/2129 [00:06<00:57, 31.96it/s]
 14%|█▎        | 288/2129 [00:06<00:49, 37.07it/s]
 14%|█▍        | 294/2129 [00:06<00:46, 39.80it/s]
 14%|█▍        | 299/2129 [00:07<00:43, 41.97it/s]
 14%|█▍        | 305/2129 [00:07<01:17, 23.52it/s]
 15%|█▍        | 309/2129 [00:07<01:13, 24.61it/s]
 15%|█▍        | 316/2129 [00:07<00:56, 32.06it/s]
 15%|█▌        | 321/2129 [00:07<00:56, 32.04it/s]
 15%|█▌        | 326/2129 [00:08<01:27, 20.53it/s]
 16%|█▌        | 331/2129 [00:08<01:14, 24.10it/s]
 16%|█▌        | 338/2129 [00:08<00:56, 31.43it/s]
 16%|█▌        | 343/2129 [00:09<01:27, 20.33it/s]
 16%|█▋        | 347/2129 [00:09<01:23, 21.35it/s]
 16%|█▋        | 351/2129 [00:09<02:13, 13.30it/s]
 17%|█▋        | 356/2129 [00:10<01:44, 17.01it/s]
 17%|█▋        | 361/2129 [00:10<01:51, 15.87it/s]
 17%|█▋        | 364/2129 [00:10<01:42, 17.26it/s]
 17%|█▋        | 370/2129 [00:10<01:15, 23.19it/s]
 18%|█▊        | 374/2129 [00:11<01:49, 16.02it/s]
 18%|█▊        | 377/2129 [00:11<01:38, 17.77it/s]
 18%|█▊        | 385/2129 [00:11<01:03, 27.38it/s]
 18%|█▊        | 392/2129 [00:11<00:50, 34.48it/s]
 19%|█▉        | 400/2129 [00:11<00:40, 43.11it/s]
 19%|█▉        | 406/2129 [00:12<01:12, 23.87it/s]
 19%|█▉        | 411/2129 [00:12<01:04, 26.75it/s]
 20%|█▉        | 418/2129 [00:12<00:51, 33.04it/s]
 20%|█▉        | 425/2129 [00:12<00:44, 38.45it/s]
 20%|██        | 432/2129 [00:12<00:38, 43.78it/s]
 21%|██        | 438/2129 [00:13<01:11, 23.53it/s]
 21%|██        | 444/2129 [00:13<00:59, 28.32it/s]
 21%|██        | 452/2129 [00:13<00:46, 36.02it/s]
 22%|██▏       | 458/2129 [00:13<00:43, 38.67it/s]
 22%|██▏       | 464/2129 [00:14<01:22, 20.26it/s]
 22%|██▏       | 468/2129 [00:14<02:22, 11.67it/s]
 22%|██▏       | 471/2129 [00:15<02:09, 12.83it/s]
 22%|██▏       | 478/2129 [00:15<01:28, 18.60it/s]
 23%|██▎       | 482/2129 [00:15<01:55, 14.21it/s]
 23%|██▎       | 486/2129 [00:15<01:38, 16.61it/s]
 23%|██▎       | 490/2129 [00:16<02:04, 13.13it/s]
 23%|██▎       | 494/2129 [00:16<01:42, 15.88it/s]
 24%|██▎       | 501/2129 [00:16<01:10, 23.02it/s]
 24%|██▍       | 508/2129 [00:16<01:22, 19.64it/s]
 24%|██▍       | 512/2129 [00:17<01:57, 13.76it/s]
 24%|██▍       | 515/2129 [00:17<01:50, 14.65it/s]
 24%|██▍       | 518/2129 [00:18<02:09, 12.47it/s]
 24%|██▍       | 520/2129 [00:18<02:03, 13.01it/s]
 25%|██▍       | 522/2129 [00:18<01:58, 13.58it/s]
 25%|██▍       | 529/2129 [00:18<01:11, 22.24it/s]
 25%|██▌       | 533/2129 [00:18<01:49, 14.62it/s]
 25%|██▌       | 536/2129 [00:19<02:39, 10.00it/s]
 25%|██▌       | 538/2129 [00:19<02:29, 10.61it/s]
 25%|██▌       | 541/2129 [00:19<02:05, 12.62it/s]
 26%|██▌       | 545/2129 [00:20<02:26, 10.84it/s]
 26%|██▌       | 547/2129 [00:20<02:14, 11.75it/s]
 26%|██▌       | 552/2129 [00:20<01:34, 16.62it/s]
 26%|██▌       | 556/2129 [00:20<01:20, 19.55it/s]
 26%|██▋       | 559/2129 [00:21<02:08, 12.18it/s]
 26%|██▋       | 563/2129 [00:21<01:39, 15.72it/s]
 27%|██▋       | 566/2129 [00:21<02:16, 11.45it/s]
 27%|██▋       | 569/2129 [00:21<01:58, 13.20it/s]
 27%|██▋       | 575/2129 [00:21<01:18, 19.85it/s]
 27%|██▋       | 581/2129 [00:22<01:33, 16.58it/s]
 27%|██▋       | 584/2129 [00:22<01:31, 16.89it/s]
 28%|██▊       | 588/2129 [00:22<01:17, 19.97it/s]
 28%|██▊       | 591/2129 [00:22<01:20, 19.07it/s]
 28%|██▊       | 595/2129 [00:23<01:12, 21.16it/s]
 28%|██▊       | 599/2129 [00:23<01:46, 14.37it/s]
 28%|██▊       | 602/2129 [00:23<01:36, 15.80it/s]
 29%|██▊       | 608/2129 [00:23<01:08, 22.34it/s]
 29%|██▉       | 614/2129 [00:23<00:53, 28.27it/s]
 29%|██▉       | 618/2129 [00:23<00:50, 30.07it/s]
 29%|██▉       | 625/2129 [00:24<00:39, 38.51it/s]
 30%|██▉       | 630/2129 [00:24<01:48, 13.82it/s]
 30%|██▉       | 634/2129 [00:25<01:32, 16.15it/s]
 30%|██▉       | 638/2129 [00:25<01:18, 19.11it/s]
 30%|███       | 644/2129 [00:25<00:58, 25.21it/s]
 30%|███       | 649/2129 [00:25<01:24, 17.62it/s]
 31%|███       | 653/2129 [00:26<01:51, 13.22it/s]
 31%|███       | 656/2129 [00:26<01:42, 14.41it/s]
 31%|███       | 661/2129 [00:26<01:17, 18.89it/s]
 31%|███       | 665/2129 [00:27<01:53, 12.87it/s]
 32%|███▏      | 673/2129 [00:27<01:43, 14.13it/s]
 32%|███▏      | 677/2129 [00:27<01:29, 16.30it/s]
 32%|███▏      | 683/2129 [00:27<01:07, 21.39it/s]
 32%|███▏      | 688/2129 [00:27<00:56, 25.59it/s]
 33%|███▎      | 695/2129 [00:28<00:43, 32.93it/s]
 33%|███▎      | 700/2129 [00:28<01:14, 19.27it/s]
 33%|███▎      | 705/2129 [00:29<01:30, 15.69it/s]
 33%|███▎      | 708/2129 [00:29<01:24, 16.91it/s]
 33%|███▎      | 712/2129 [00:29<01:45, 13.46it/s]
 34%|███▎      | 715/2129 [00:29<01:35, 14.81it/s]
 34%|███▍      | 719/2129 [00:30<01:50, 12.71it/s]
 34%|███▍      | 721/2129 [00:30<02:35,  9.04it/s]
 34%|███▍      | 723/2129 [00:30<02:19, 10.05it/s]
 34%|███▍      | 725/2129 [00:31<02:57,  7.93it/s]
 34%|███▍      | 728/2129 [00:31<02:59,  7.79it/s]
 34%|███▍      | 731/2129 [00:31<02:22,  9.80it/s]
 34%|███▍      | 733/2129 [00:32<02:52,  8.10it/s]
 35%|███▍      | 735/2129 [00:32<02:28,  9.39it/s]
 35%|███▍      | 738/2129 [00:32<01:53, 12.28it/s]
 35%|███▍      | 740/2129 [00:32<02:13, 10.44it/s]
 35%|███▍      | 742/2129 [00:32<01:57, 11.84it/s]
 35%|███▌      | 748/2129 [00:32<01:07, 20.46it/s]
 35%|███▌      | 751/2129 [00:33<01:46, 12.95it/s]
 35%|███▌      | 754/2129 [00:34<03:08,  7.31it/s]
 36%|███▌      | 756/2129 [00:34<02:43,  8.40it/s]
 36%|███▌      | 760/2129 [00:34<01:56, 11.74it/s]
 36%|███▌      | 763/2129 [00:34<01:38, 13.85it/s]
 36%|███▌      | 766/2129 [00:35<02:13, 10.23it/s]
 36%|███▌      | 769/2129 [00:35<01:50, 12.27it/s]
 36%|███▋      | 774/2129 [00:35<01:56, 11.66it/s]
 36%|███▋      | 776/2129 [00:35<01:49, 12.35it/s]
 37%|███▋      | 782/2129 [00:35<01:11, 18.78it/s]
 37%|███▋      | 785/2129 [00:36<01:44, 12.87it/s]
 37%|███▋      | 788/2129 [00:36<01:30, 14.74it/s]
 37%|███▋      | 795/2129 [00:36<01:31, 14.53it/s]
 37%|███▋      | 798/2129 [00:37<01:23, 15.89it/s]
 38%|███▊      | 805/2129 [00:37<00:56, 23.28it/s]
 38%|███▊      | 809/2129 [00:37<01:19, 16.64it/s]
 38%|███▊      | 812/2129 [00:38<01:55, 11.40it/s]
 38%|███▊      | 818/2129 [00:38<01:52, 11.69it/s]
 39%|███▊      | 820/2129 [00:39<02:24,  9.06it/s]
 39%|███▊      | 823/2129 [00:39<02:00, 10.81it/s]
 39%|███▉      | 831/2129 [00:39<01:10, 18.43it/s]
 39%|███▉      | 838/2129 [00:39<01:20, 16.04it/s]
 40%|███▉      | 841/2129 [00:40<01:18, 16.45it/s]
 40%|███▉      | 844/2129 [00:41<02:46,  7.71it/s]
 40%|███▉      | 846/2129 [00:41<02:33,  8.38it/s]
 40%|███▉      | 848/2129 [00:41<03:12,  6.67it/s]
 40%|███▉      | 851/2129 [00:42<02:30,  8.49it/s]
 40%|████      | 857/2129 [00:42<01:35, 13.39it/s]
 40%|████      | 860/2129 [00:42<01:22, 15.38it/s]
 41%|████      | 865/2129 [00:42<01:02, 20.29it/s]
 41%|████      | 869/2129 [00:42<01:05, 19.11it/s]
 41%|████      | 874/2129 [00:42<00:52, 23.99it/s]
 41%|████      | 878/2129 [00:42<00:46, 26.80it/s]
 41%|████▏     | 882/2129 [00:43<01:18, 15.89it/s]
 42%|████▏     | 886/2129 [00:43<01:04, 19.17it/s]
 42%|████▏     | 890/2129 [00:44<01:37, 12.71it/s]
 42%|████▏     | 893/2129 [00:44<02:02, 10.10it/s]
 42%|████▏     | 895/2129 [00:45<02:31,  8.17it/s]
 42%|████▏     | 899/2129 [00:45<01:52, 10.96it/s]
 43%|████▎     | 906/2129 [00:45<01:38, 12.43it/s]
 43%|████▎     | 909/2129 [00:45<01:26, 14.08it/s]
 43%|████▎     | 912/2129 [00:46<01:51, 10.92it/s]
 43%|████▎     | 914/2129 [00:46<02:22,  8.53it/s]
 43%|████▎     | 917/2129 [00:46<01:56, 10.40it/s]
 43%|████▎     | 924/2129 [00:46<01:09, 17.34it/s]
 44%|████▎     | 927/2129 [00:47<01:36, 12.46it/s]
 44%|████▎     | 930/2129 [00:47<01:43, 11.62it/s]
 44%|████▍     | 932/2129 [00:47<01:39, 12.01it/s]
 44%|████▍     | 934/2129 [00:47<01:31, 13.05it/s]
 44%|████▍     | 937/2129 [00:48<01:38, 12.09it/s]
 44%|████▍     | 939/2129 [00:48<01:48, 11.00it/s]
 44%|████▍     | 941/2129 [00:48<01:39, 11.88it/s]
 44%|████▍     | 944/2129 [00:48<01:23, 14.14it/s]
 44%|████▍     | 946/2129 [00:49<02:08,  9.19it/s]
 45%|████▍     | 950/2129 [00:49<02:18,  8.53it/s]
 45%|████▍     | 953/2129 [00:49<01:51, 10.51it/s]
 45%|████▍     | 955/2129 [00:50<02:21,  8.32it/s]
 45%|████▍     | 957/2129 [00:50<02:49,  6.90it/s]
 45%|████▍     | 958/2129 [00:51<03:39,  5.34it/s]
 45%|████▌     | 960/2129 [00:51<02:51,  6.83it/s]
 45%|████▌     | 963/2129 [00:51<02:52,  6.76it/s]
 45%|████▌     | 966/2129 [00:51<02:06,  9.18it/s]
 45%|████▌     | 968/2129 [00:52<02:37,  7.35it/s]
 46%|████▌     | 970/2129 [00:52<03:05,  6.24it/s]
 46%|████▌     | 972/2129 [00:52<02:35,  7.43it/s]
 46%|████▌     | 977/2129 [00:52<01:30, 12.75it/s]
 46%|████▌     | 981/2129 [00:53<01:09, 16.54it/s]
 46%|████▌     | 984/2129 [00:53<01:02, 18.30it/s]
 46%|████▋     | 988/2129 [00:53<01:09, 16.34it/s]
 47%|████▋     | 991/2129 [00:53<01:03, 18.01it/s]
 47%|████▋     | 994/2129 [00:53<01:01, 18.53it/s]
 47%|████▋     | 1001/2129 [00:54<00:58, 19.44it/s]
 47%|████▋     | 1004/2129 [00:54<00:57, 19.42it/s]
 47%|████▋     | 1007/2129 [00:54<01:01, 18.19it/s]
 47%|████▋     | 1010/2129 [00:54<01:15, 14.90it/s]
 48%|████▊     | 1012/2129 [00:54<01:21, 13.73it/s]
 48%|████▊     | 1015/2129 [00:55<01:13, 15.10it/s]
 48%|████▊     | 1018/2129 [00:55<01:29, 12.43it/s]
 48%|████▊     | 1020/2129 [00:55<01:42, 10.80it/s]
 48%|████▊     | 1022/2129 [00:55<02:00,  9.19it/s]
 48%|████▊     | 1024/2129 [00:56<02:33,  7.21it/s]
 48%|████▊     | 1026/2129 [00:56<02:14,  8.22it/s]
 48%|████▊     | 1028/2129 [00:56<02:30,  7.31it/s]
 48%|████▊     | 1030/2129 [00:57<02:11,  8.33it/s]
 49%|████▊     | 1033/2129 [00:57<01:36, 11.31it/s]
 49%|████▉     | 1039/2129 [00:57<00:56, 19.44it/s]
 49%|████▉     | 1045/2129 [00:57<00:40, 26.87it/s]
 49%|████▉     | 1049/2129 [00:58<01:17, 13.95it/s]
 49%|████▉     | 1052/2129 [00:58<01:09, 15.44it/s]
 50%|████▉     | 1055/2129 [00:58<01:33, 11.55it/s]
 50%|████▉     | 1058/2129 [00:59<02:27,  7.24it/s]
 50%|████▉     | 1060/2129 [00:59<02:49,  6.32it/s]
 50%|████▉     | 1062/2129 [01:00<02:24,  7.38it/s]
 50%|████▉     | 1064/2129 [01:00<02:43,  6.50it/s]
 50%|█████     | 1066/2129 [01:00<02:18,  7.69it/s]
 50%|█████     | 1068/2129 [01:01<02:43,  6.49it/s]
 50%|█████     | 1071/2129 [01:01<02:46,  6.34it/s]
 50%|█████     | 1073/2129 [01:01<02:20,  7.49it/s]
 51%|█████     | 1079/2129 [01:01<01:17, 13.58it/s]
 51%|█████     | 1086/2129 [01:01<00:48, 21.58it/s]
 51%|█████     | 1091/2129 [01:02<01:04, 16.18it/s]
 51%|█████▏    | 1094/2129 [01:02<01:25, 12.13it/s]
 52%|█████▏    | 1097/2129 [01:02<01:15, 13.59it/s]
 52%|█████▏    | 1101/2129 [01:03<01:03, 16.23it/s]
 52%|█████▏    | 1104/2129 [01:03<01:36, 10.64it/s]
 52%|█████▏    | 1110/2129 [01:03<01:03, 16.02it/s]
 52%|█████▏    | 1113/2129 [01:04<01:24, 12.04it/s]
 52%|█████▏    | 1116/2129 [01:04<01:11, 14.10it/s]
 53%|█████▎    | 1119/2129 [01:04<01:36, 10.49it/s]
 53%|█████▎    | 1121/2129 [01:05<01:58,  8.48it/s]
 53%|█████▎    | 1124/2129 [01:05<01:35, 10.52it/s]
 53%|█████▎    | 1126/2129 [01:05<02:03,  8.15it/s]
 53%|█████▎    | 1128/2129 [01:06<02:34,  6.49it/s]
 53%|█████▎    | 1130/2129 [01:06<02:08,  7.79it/s]
 53%|█████▎    | 1133/2129 [01:06<02:04,  7.99it/s]
 53%|█████▎    | 1136/2129 [01:07<01:49,  9.07it/s]
 53%|█████▎    | 1138/2129 [01:07<02:10,  7.60it/s]
 53%|█████▎    | 1139/2129 [01:07<02:20,  7.03it/s]
 54%|█████▎    | 1141/2129 [01:07<01:59,  8.24it/s]
 54%|█████▍    | 1145/2129 [01:08<01:39,  9.89it/s]
 54%|█████▍    | 1147/2129 [01:08<01:55,  8.51it/s]
 54%|█████▍    | 1150/2129 [01:08<01:31, 10.74it/s]
 54%|█████▍    | 1152/2129 [01:09<02:08,  7.58it/s]
 54%|█████▍    | 1154/2129 [01:09<01:49,  8.90it/s]
 54%|█████▍    | 1156/2129 [01:09<02:10,  7.43it/s]
 54%|█████▍    | 1159/2129 [01:09<02:09,  7.50it/s]
 55%|█████▍    | 1161/2129 [01:10<01:53,  8.52it/s]
 55%|█████▍    | 1164/2129 [01:10<01:25, 11.33it/s]
 55%|█████▍    | 1168/2129 [01:10<01:03, 15.24it/s]
 55%|█████▌    | 1171/2129 [01:11<02:07,  7.50it/s]
 55%|█████▌    | 1174/2129 [01:11<01:41,  9.44it/s]
 55%|█████▌    | 1176/2129 [01:11<02:04,  7.67it/s]
 55%|█████▌    | 1178/2129 [01:11<01:45,  9.01it/s]
 55%|█████▌    | 1180/2129 [01:12<02:13,  7.09it/s]
 56%|█████▌    | 1182/2129 [01:13<03:20,  4.73it/s]
 56%|█████▌    | 1184/2129 [01:13<02:38,  5.97it/s]
 56%|█████▌    | 1186/2129 [01:13<03:00,  5.23it/s]
 56%|█████▌    | 1188/2129 [01:13<02:25,  6.49it/s]
 56%|█████▌    | 1190/2129 [01:14<02:43,  5.75it/s]
 56%|█████▌    | 1192/2129 [01:14<02:09,  7.21it/s]
 56%|█████▌    | 1194/2129 [01:14<02:42,  5.77it/s]
 56%|█████▌    | 1195/2129 [01:15<03:16,  4.75it/s]
 56%|█████▌    | 1197/2129 [01:15<03:23,  4.58it/s]
 56%|█████▋    | 1200/2129 [01:15<02:13,  6.95it/s]
 57%|█████▋    | 1203/2129 [01:16<02:16,  6.80it/s]
 57%|█████▋    | 1206/2129 [01:16<02:21,  6.53it/s]
 57%|█████▋    | 1208/2129 [01:16<01:57,  7.81it/s]
 57%|█████▋    | 1211/2129 [01:17<01:29, 10.22it/s]
 57%|█████▋    | 1213/2129 [01:17<02:03,  7.41it/s]
 57%|█████▋    | 1216/2129 [01:17<01:34,  9.66it/s]
 57%|█████▋    | 1218/2129 [01:18<02:11,  6.95it/s]
 57%|█████▋    | 1220/2129 [01:18<01:50,  8.24it/s]
 57%|█████▋    | 1222/2129 [01:19<03:00,  5.03it/s]
 57%|█████▋    | 1224/2129 [01:19<03:09,  4.76it/s]
 58%|█████▊    | 1227/2129 [01:19<02:16,  6.60it/s]
 58%|█████▊    | 1230/2129 [01:19<01:39,  9.04it/s]
 58%|█████▊    | 1233/2129 [01:20<01:43,  8.65it/s]
 58%|█████▊    | 1236/2129 [01:20<01:24, 10.61it/s]
 58%|█████▊    | 1238/2129 [01:20<01:44,  8.55it/s]
 58%|█████▊    | 1240/2129 [01:20<01:32,  9.64it/s]
 58%|█████▊    | 1243/2129 [01:21<01:34,  9.33it/s]
 58%|█████▊    | 1245/2129 [01:21<01:27, 10.08it/s]
 59%|█████▊    | 1249/2129 [01:21<01:01, 14.42it/s]
 59%|█████▉    | 1251/2129 [01:21<01:13, 11.96it/s]
 59%|█████▉    | 1255/2129 [01:21<00:54, 16.10it/s]
 59%|█████▉    | 1258/2129 [01:22<01:22, 10.62it/s]
 59%|█████▉    | 1260/2129 [01:22<01:15, 11.50it/s]
 59%|█████▉    | 1263/2129 [01:22<01:24, 10.26it/s]
 59%|█████▉    | 1265/2129 [01:23<01:17, 11.10it/s]
 60%|█████▉    | 1270/2129 [01:23<01:19, 10.85it/s]
 60%|█████▉    | 1273/2129 [01:23<01:06, 12.87it/s]
 60%|█████▉    | 1275/2129 [01:24<02:08,  6.64it/s]
 60%|██████    | 1278/2129 [01:24<01:38,  8.61it/s]
 60%|██████    | 1280/2129 [01:25<02:04,  6.81it/s]
 60%|██████    | 1282/2129 [01:25<01:45,  8.05it/s]
 60%|██████    | 1284/2129 [01:25<02:04,  6.79it/s]
 60%|██████    | 1286/2129 [01:26<02:22,  5.90it/s]
 61%|██████    | 1289/2129 [01:26<01:41,  8.30it/s]
 61%|██████    | 1292/2129 [01:26<01:44,  8.02it/s]
 61%|██████    | 1294/2129 [01:26<01:44,  8.01it/s]
 61%|██████    | 1296/2129 [01:26<01:32,  8.97it/s]
 61%|██████    | 1298/2129 [01:27<01:51,  7.45it/s]
 61%|██████    | 1300/2129 [01:27<01:35,  8.71it/s]
 61%|██████    | 1302/2129 [01:27<01:55,  7.15it/s]
 61%|██████    | 1304/2129 [01:28<02:16,  6.06it/s]
 61%|██████▏   | 1306/2129 [01:28<01:51,  7.40it/s]
 62%|██████▏   | 1313/2129 [01:28<00:52, 15.65it/s]
 62%|██████▏   | 1316/2129 [01:29<01:15, 10.71it/s]
 62%|██████▏   | 1319/2129 [01:29<01:36,  8.37it/s]
 62%|██████▏   | 1321/2129 [01:30<02:26,  5.50it/s]
 62%|██████▏   | 1323/2129 [01:30<02:02,  6.59it/s]
 62%|██████▏   | 1325/2129 [01:31<02:17,  5.84it/s]
 62%|██████▏   | 1328/2129 [01:31<02:14,  5.96it/s]
 62%|██████▏   | 1330/2129 [01:31<01:50,  7.21it/s]
 63%|██████▎   | 1336/2129 [01:31<01:00, 13.14it/s]
 63%|██████▎   | 1342/2129 [01:32<00:59, 13.27it/s]
 63%|██████▎   | 1345/2129 [01:32<00:53, 14.66it/s]
 63%|██████▎   | 1351/2129 [01:32<00:37, 20.81it/s]
 64%|██████▎   | 1356/2129 [01:32<00:30, 25.58it/s]
 64%|██████▍   | 1360/2129 [01:33<00:48, 15.71it/s]
 64%|██████▍   | 1363/2129 [01:33<01:05, 11.72it/s]
 64%|██████▍   | 1366/2129 [01:33<00:57, 13.21it/s]
 64%|██████▍   | 1369/2129 [01:34<01:11, 10.61it/s]
 64%|██████▍   | 1373/2129 [01:34<01:18,  9.64it/s]
 65%|██████▍   | 1375/2129 [01:35<01:35,  7.89it/s]
 65%|██████▍   | 1378/2129 [01:35<01:15,  9.90it/s]
 65%|██████▍   | 1383/2129 [01:35<01:13, 10.21it/s]
 65%|██████▌   | 1385/2129 [01:36<01:30,  8.23it/s]
 65%|██████▌   | 1387/2129 [01:36<01:50,  6.71it/s]
 65%|██████▌   | 1389/2129 [01:37<02:08,  5.75it/s]
 65%|██████▌   | 1390/2129 [01:37<02:36,  4.72it/s]
 65%|██████▌   | 1393/2129 [01:37<02:11,  5.60it/s]
 65%|██████▌   | 1394/2129 [01:38<02:04,  5.89it/s]
 66%|██████▌   | 1396/2129 [01:38<01:42,  7.15it/s]
 66%|██████▌   | 1399/2129 [01:38<01:13, 10.00it/s]
 66%|██████▌   | 1405/2129 [01:38<01:08, 10.63it/s]
 66%|██████▌   | 1408/2129 [01:38<00:57, 12.58it/s]
 66%|██████▋   | 1411/2129 [01:39<01:11, 10.06it/s]
 66%|██████▋   | 1413/2129 [01:39<01:37,  7.38it/s]
 67%|██████▋   | 1416/2129 [01:40<01:16,  9.35it/s]
 67%|██████▋   | 1420/2129 [01:40<01:17,  9.20it/s]
 67%|██████▋   | 1422/2129 [01:40<01:10, 10.08it/s]
 67%|██████▋   | 1428/2129 [01:41<01:04, 10.92it/s]
 67%|██████▋   | 1430/2129 [01:41<01:00, 11.50it/s]
 67%|██████▋   | 1432/2129 [01:41<01:18,  8.87it/s]
 67%|██████▋   | 1434/2129 [01:42<02:05,  5.53it/s]
 67%|██████▋   | 1436/2129 [01:42<01:44,  6.63it/s]
 68%|██████▊   | 1440/2129 [01:43<01:32,  7.44it/s]
 68%|██████▊   | 1442/2129 [01:43<01:47,  6.40it/s]
 68%|██████▊   | 1445/2129 [01:43<01:21,  8.35it/s]
 68%|██████▊   | 1451/2129 [01:43<00:47, 14.25it/s]
 68%|██████▊   | 1454/2129 [01:44<01:04, 10.43it/s]
 68%|██████▊   | 1457/2129 [01:44<01:14,  8.99it/s]
 69%|██████▊   | 1459/2129 [01:44<01:07,  9.94it/s]
 69%|██████▉   | 1465/2129 [01:45<00:41, 16.10it/s]
 69%|██████▉   | 1468/2129 [01:45<00:36, 18.15it/s]
 69%|██████▉   | 1471/2129 [01:45<01:11,  9.15it/s]
 69%|██████▉   | 1474/2129 [01:46<00:59, 11.01it/s]
 69%|██████▉   | 1477/2129 [01:46<01:20,  8.07it/s]
 69%|██████▉   | 1479/2129 [01:47<01:32,  7.03it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 339.65it/s]

[[np.int64(0), False, 7], [np.int64(1), False, 10], [np.int64(2), False, 3], [np.int64(3), False, 0], [np.int64(4), False, 10], [np.int64(5), False, 0], [np.int64(6), False, 7], [np.int64(8), False, 9], [np.int64(9), False, 4], [np.int64(11), False, 1], [np.int64(12), False, 2], [np.int64(13), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.6471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0422, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1278, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [08:23<1:19:24, 48.13s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [08:23<55:05, 33.73s/it]

tensor(12.6449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0415, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3799, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0456, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7282, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [08:24<26:32, 16.59s/it]

tensor(12.6490, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0525, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9356, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0599, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9199, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [08:24<08:56,  5.77s/it]

tensor(12.6538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0644, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9918, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0673, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1539, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [08:24<06:14,  4.08s/it]

tensor(12.6802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0682, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1174, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0683, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5700, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [08:24<03:05,  2.06s/it]

tensor(12.6522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0729, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5365, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6569, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0747, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1596, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [08:25<01:08,  1.27it/s]

tensor(12.6672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0699, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4460, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0655, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9078, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [08:25<00:50,  1.70it/s]

tensor(12.6998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0656, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0678, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6462, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [08:25<00:29,  2.86it/s]

tensor(12.7519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0714, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6676, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0769, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9697, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [08:25<00:19,  4.29it/s]

tensor(12.7378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0848, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0937, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3394, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [08:26<00:12,  6.25it/s]

tensor(12.7308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0970, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3187, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0923, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4344, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [08:26<00:10,  7.15it/s]

tensor(12.7221, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0842, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0795, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7847, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [08:26<00:09,  7.69it/s]

tensor(12.7106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0767, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9147, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0754, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2113, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [08:26<00:09,  7.96it/s]

tensor(12.7267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0764, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3990, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7443, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0774, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4588, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [08:26<00:08,  8.04it/s]

tensor(12.7529, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0781, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3590, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0767, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3512, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [08:27<00:08,  8.13it/s]

tensor(12.7227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0744, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3427, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0715, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3841, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [08:27<00:08,  8.18it/s]

tensor(12.7187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0675, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4426, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0643, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4657, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [08:27<00:08,  8.21it/s]

tensor(12.7097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0609, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4987, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0576, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5749, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [08:27<00:07,  8.19it/s]

tensor(12.6891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0549, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6368, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0531, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6593, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [08:28<00:07,  8.20it/s]

tensor(12.6686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0510, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6947, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0483, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6005, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [08:28<00:07,  8.22it/s]

tensor(12.6489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0457, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6569, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6660, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [08:28<00:07,  8.12it/s]

tensor(12.6394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0427, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7255, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7683, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [08:28<00:06,  8.10it/s]

tensor(12.6333, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0392, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8170, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8758, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [08:29<00:06,  8.25it/s]

tensor(12.6038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0383, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9420, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0388, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9574, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [08:29<00:06,  8.05it/s]

tensor(12.5749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0456, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0418, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0933, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [08:29<00:06,  8.03it/s]

tensor(12.5453, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0429, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1352, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([158, 126, 127, 172, 159, 209,  42, 153, 113, 274, 176,  93, 202, 125])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 5/2129 [00:00<01:06, 31.99it/s]
  0%|          | 10/2129 [00:00<00:55, 38.23it/s]
  1%|          | 14/2129 [00:00<00:59, 35.45it/s]
  1%|          | 20/2129 [00:00<00:56, 37.53it/s]
  1%|          | 25/2129 [00:00<00:53, 39.23it/s]
  1%|▏         | 30/2129 [00:00<00:49, 42.17it/s]
  2%|▏         | 37/2129 [00:00<00:42, 49.78it/s]
  2%|▏         | 44/2129 [00:00<00:39, 52.45it/s]
  2%|▏         | 50/2129 [00:01<00:45, 45.66it/s]
  3%|▎         | 55/2129 [00:01<00:47, 44.10it/s]
  3%|▎         | 62/2129 [00:01<00:41, 49.72it/s]
  3%|▎         | 68/2129 [00:01<00:44, 45.89it/s]
  3%|▎         | 73/2129 [00:01<00:52, 38.91it/s]
  4%|▍         | 80/2129 [00:02<01:09, 29.68it/s]
  4%|▍         | 84/2129 [00:02<01:19, 25.83it/s]
  4%|▍         | 92/2129 [00:02<01:02, 32.53it/s]
  5%|▍         | 96/2129 [00:02<01:04, 31.63it/s]
  5%|▍         | 100/2129 [00:02<01:04, 31.23it/s]
  5%|▍         | 104/2129 [00:02<01:08, 29.37it/s]
  5%|▌         | 110/2129 [00:02<00:57, 35.07it/s]
  5%|▌         | 114/2129 [00:03<01:14, 26.98it/s]
  6%|▌         | 118/2129 [00:03<01:18, 25.72it/s]
  6%|▌         | 121/2129 [00:03<01:19, 25.27it/s]
  6%|▌         | 124/2129 [00:03<01:17, 26.03it/s]
  6%|▌         | 131/2129 [00:03<00:56, 35.57it/s]
  6%|▋         | 135/2129 [00:03<01:14, 26.82it/s]
  7%|▋         | 139/2129 [00:04<01:08, 29.07it/s]
  7%|▋         | 147/2129 [00:04<00:49, 40.07it/s]
  7%|▋         | 154/2129 [00:04<00:42, 45.94it/s]
  8%|▊         | 160/2129 [00:04<01:18, 24.94it/s]
  8%|▊         | 164/2129 [00:04<01:13, 26.84it/s]
  8%|▊         | 170/2129 [00:05<01:00, 32.38it/s]
  8%|▊         | 175/2129 [00:05<01:17, 25.34it/s]
  9%|▊         | 183/2129 [00:05<00:58, 33.33it/s]
  9%|▉         | 190/2129 [00:05<01:07, 28.69it/s]
  9%|▉         | 194/2129 [00:05<01:07, 28.79it/s]
  9%|▉         | 200/2129 [00:06<01:14, 25.73it/s]
 10%|▉         | 204/2129 [00:06<01:25, 22.50it/s]
 10%|▉         | 209/2129 [00:06<01:11, 26.69it/s]
 10%|█         | 213/2129 [00:06<01:26, 22.10it/s]
 10%|█         | 216/2129 [00:07<02:10, 14.66it/s]
 10%|█         | 219/2129 [00:07<01:56, 16.46it/s]
 11%|█         | 226/2129 [00:07<01:18, 24.19it/s]
 11%|█         | 233/2129 [00:07<00:59, 31.76it/s]
 11%|█         | 238/2129 [00:07<01:02, 30.39it/s]
 11%|█▏        | 242/2129 [00:07<00:59, 31.61it/s]
 12%|█▏        | 246/2129 [00:08<01:15, 24.88it/s]
 12%|█▏        | 250/2129 [00:08<01:38, 19.10it/s]
 12%|█▏        | 253/2129 [00:08<02:04, 15.05it/s]
 12%|█▏        | 256/2129 [00:08<01:54, 16.35it/s]
 12%|█▏        | 259/2129 [00:09<02:12, 14.10it/s]
 12%|█▏        | 261/2129 [00:09<02:07, 14.68it/s]
 13%|█▎        | 267/2129 [00:09<01:52, 16.58it/s]
 13%|█▎        | 269/2129 [00:09<02:16, 13.63it/s]
 13%|█▎        | 272/2129 [00:10<02:00, 15.42it/s]
 13%|█▎        | 280/2129 [00:10<01:11, 25.89it/s]
 13%|█▎        | 287/2129 [00:10<01:16, 24.20it/s]
 14%|█▎        | 291/2129 [00:10<01:17, 23.58it/s]
 14%|█▍        | 294/2129 [00:11<01:39, 18.53it/s]
 14%|█▍        | 297/2129 [00:11<01:49, 16.72it/s]
 14%|█▍        | 302/2129 [00:11<01:24, 21.72it/s]
 14%|█▍        | 305/2129 [00:11<01:36, 18.99it/s]
 14%|█▍        | 308/2129 [00:11<01:27, 20.83it/s]
 15%|█▍        | 315/2129 [00:11<00:59, 30.52it/s]
 15%|█▍        | 319/2129 [00:12<01:13, 24.56it/s]
 15%|█▌        | 323/2129 [00:12<01:10, 25.77it/s]
 15%|█▌        | 328/2129 [00:12<01:15, 23.81it/s]
 16%|█▌        | 331/2129 [00:12<01:14, 24.07it/s]
 16%|█▌        | 334/2129 [00:12<01:28, 20.30it/s]
 16%|█▌        | 337/2129 [00:13<01:53, 15.84it/s]
 16%|█▌        | 340/2129 [00:13<01:41, 17.65it/s]
 16%|█▌        | 343/2129 [00:13<01:51, 16.01it/s]
 16%|█▋        | 346/2129 [00:13<01:41, 17.51it/s]
 16%|█▋        | 349/2129 [00:13<01:51, 15.90it/s]
 16%|█▋        | 351/2129 [00:14<02:12, 13.41it/s]
 17%|█▋        | 355/2129 [00:14<02:04, 14.22it/s]
 17%|█▋        | 357/2129 [00:14<02:34, 11.45it/s]
 17%|█▋        | 359/2129 [00:14<02:20, 12.62it/s]
 17%|█▋        | 361/2129 [00:14<02:17, 12.89it/s]
 17%|█▋        | 363/2129 [00:14<02:16, 12.94it/s]
 17%|█▋        | 365/2129 [00:15<02:55, 10.08it/s]
 17%|█▋        | 367/2129 [00:15<02:40, 10.99it/s]
 18%|█▊        | 374/2129 [00:15<01:22, 21.28it/s]
 18%|█▊        | 377/2129 [00:15<01:25, 20.40it/s]
 18%|█▊        | 380/2129 [00:15<01:32, 18.85it/s]
 18%|█▊        | 383/2129 [00:16<01:31, 19.12it/s]
 18%|█▊        | 386/2129 [00:16<02:01, 14.37it/s]
 18%|█▊        | 388/2129 [00:16<02:07, 13.68it/s]
 18%|█▊        | 392/2129 [00:16<01:36, 18.02it/s]
 19%|█▊        | 395/2129 [00:16<01:45, 16.46it/s]
 19%|█▊        | 397/2129 [00:16<01:44, 16.56it/s]
 19%|█▉        | 400/2129 [00:17<01:54, 15.16it/s]
 19%|█▉        | 402/2129 [00:17<01:49, 15.80it/s]
 19%|█▉        | 408/2129 [00:17<01:35, 17.98it/s]
 19%|█▉        | 410/2129 [00:17<01:35, 18.06it/s]
 20%|█▉        | 416/2129 [00:17<01:05, 26.12it/s]
 20%|█▉        | 423/2129 [00:17<00:51, 32.92it/s]
 20%|██        | 428/2129 [00:18<00:47, 35.63it/s]
 20%|██        | 432/2129 [00:18<00:59, 28.65it/s]
 20%|██        | 436/2129 [00:18<01:17, 21.91it/s]
 21%|██        | 439/2129 [00:18<01:32, 18.29it/s]
 21%|██        | 442/2129 [00:19<01:29, 18.77it/s]
 21%|██        | 446/2129 [00:19<01:40, 16.71it/s]
 21%|██        | 450/2129 [00:19<01:24, 19.81it/s]
 21%|██▏       | 456/2129 [00:19<01:01, 27.05it/s]
 22%|██▏       | 460/2129 [00:19<01:20, 20.77it/s]
 22%|██▏       | 466/2129 [00:20<01:15, 22.03it/s]
 22%|██▏       | 469/2129 [00:20<01:14, 22.15it/s]
 22%|██▏       | 472/2129 [00:20<01:38, 16.86it/s]
 22%|██▏       | 477/2129 [00:20<01:16, 21.60it/s]
 23%|██▎       | 480/2129 [00:20<01:41, 16.21it/s]
 23%|██▎       | 483/2129 [00:21<01:46, 15.39it/s]
 23%|██▎       | 485/2129 [00:21<02:06, 13.03it/s]
 23%|██▎       | 489/2129 [00:21<01:37, 16.84it/s]
 23%|██▎       | 492/2129 [00:21<01:55, 14.22it/s]
 23%|██▎       | 496/2129 [00:22<01:50, 14.75it/s]
 23%|██▎       | 498/2129 [00:22<01:46, 15.26it/s]
 24%|██▍       | 506/2129 [00:22<01:02, 26.07it/s]
 24%|██▍       | 510/2129 [00:22<01:13, 21.91it/s]
 24%|██▍       | 514/2129 [00:22<01:05, 24.72it/s]
 24%|██▍       | 521/2129 [00:23<01:07, 23.74it/s]
 25%|██▍       | 524/2129 [00:23<01:08, 23.38it/s]
 25%|██▍       | 528/2129 [00:23<01:17, 20.71it/s]
 25%|██▍       | 531/2129 [00:23<01:51, 14.36it/s]
 25%|██▌       | 534/2129 [00:23<01:39, 16.06it/s]
 25%|██▌       | 537/2129 [00:24<01:52, 14.19it/s]
 26%|██▌       | 543/2129 [00:24<01:36, 16.41it/s]
 26%|██▌       | 546/2129 [00:24<01:28, 17.81it/s]
 26%|██▌       | 549/2129 [00:24<01:42, 15.49it/s]
 26%|██▌       | 553/2129 [00:25<01:22, 19.21it/s]
 26%|██▋       | 559/2129 [00:25<01:17, 20.15it/s]
 26%|██▋       | 562/2129 [00:25<01:19, 19.69it/s]
 27%|██▋       | 565/2129 [00:25<01:17, 20.21it/s]
 27%|██▋       | 568/2129 [00:26<01:54, 13.61it/s]
 27%|██▋       | 571/2129 [00:26<01:56, 13.39it/s]
 27%|██▋       | 573/2129 [00:26<02:15, 11.52it/s]
 27%|██▋       | 575/2129 [00:26<02:06, 12.28it/s]
 27%|██▋       | 581/2129 [00:26<01:16, 20.11it/s]
 27%|██▋       | 584/2129 [00:27<02:07, 12.09it/s]
 28%|██▊       | 587/2129 [00:27<02:40,  9.62it/s]
 28%|██▊       | 590/2129 [00:27<02:11, 11.72it/s]
 28%|██▊       | 597/2129 [00:27<01:18, 19.49it/s]
 28%|██▊       | 602/2129 [00:28<01:23, 18.23it/s]
 28%|██▊       | 605/2129 [00:28<01:36, 15.78it/s]
 29%|██▊       | 608/2129 [00:28<01:29, 17.04it/s]
 29%|██▊       | 611/2129 [00:28<01:36, 15.72it/s]
 29%|██▉       | 614/2129 [00:29<01:53, 13.31it/s]
 29%|██▉       | 618/2129 [00:29<01:28, 17.02it/s]
 29%|██▉       | 623/2129 [00:29<01:08, 21.87it/s]
 29%|██▉       | 626/2129 [00:29<01:22, 18.14it/s]
 30%|██▉       | 629/2129 [00:30<01:37, 15.33it/s]
 30%|██▉       | 631/2129 [00:30<01:37, 15.38it/s]
 30%|██▉       | 633/2129 [00:30<01:58, 12.63it/s]
 30%|██▉       | 635/2129 [00:30<01:49, 13.70it/s]
 30%|██▉       | 637/2129 [00:30<02:07, 11.73it/s]
 30%|███       | 639/2129 [00:30<01:54, 12.97it/s]
 30%|███       | 644/2129 [00:31<01:35, 15.47it/s]
 30%|███       | 646/2129 [00:31<01:53, 13.02it/s]
 30%|███       | 648/2129 [00:31<01:49, 13.57it/s]
 31%|███       | 653/2129 [00:31<01:24, 17.57it/s]
 31%|███       | 657/2129 [00:31<01:11, 20.57it/s]
 31%|███       | 660/2129 [00:32<01:27, 16.71it/s]
 31%|███       | 662/2129 [00:32<02:06, 11.58it/s]
 31%|███       | 664/2129 [00:32<02:09, 11.27it/s]
 31%|███▏      | 666/2129 [00:32<02:00, 12.11it/s]
 31%|███▏      | 668/2129 [00:32<02:04, 11.77it/s]
 32%|███▏      | 672/2129 [00:33<01:45, 13.78it/s]
 32%|███▏      | 674/2129 [00:33<01:43, 14.04it/s]
 32%|███▏      | 677/2129 [00:33<01:44, 13.96it/s]
 32%|███▏      | 679/2129 [00:33<01:36, 15.05it/s]
 32%|███▏      | 685/2129 [00:33<01:20, 17.89it/s]
 32%|███▏      | 688/2129 [00:34<01:36, 14.96it/s]
 32%|███▏      | 690/2129 [00:34<01:55, 12.41it/s]
 33%|███▎      | 694/2129 [00:34<01:51, 12.91it/s]
 33%|███▎      | 696/2129 [00:35<02:06, 11.37it/s]
 33%|███▎      | 699/2129 [00:35<01:42, 14.02it/s]
 33%|███▎      | 706/2129 [00:35<01:00, 23.33it/s]
 33%|███▎      | 710/2129 [00:35<01:36, 14.74it/s]
 33%|███▎      | 713/2129 [00:36<01:45, 13.46it/s]
 34%|███▎      | 716/2129 [00:36<01:32, 15.28it/s]
 34%|███▍      | 721/2129 [00:36<01:09, 20.24it/s]
 34%|███▍      | 724/2129 [00:36<01:19, 17.56it/s]
 34%|███▍      | 727/2129 [00:36<01:22, 17.07it/s]
 34%|███▍      | 730/2129 [00:36<01:16, 18.27it/s]
 34%|███▍      | 733/2129 [00:37<01:23, 16.76it/s]
 35%|███▍      | 736/2129 [00:37<01:16, 18.12it/s]
 35%|███▍      | 744/2129 [00:37<00:46, 29.83it/s]
 35%|███▌      | 748/2129 [00:37<00:45, 30.40it/s]
 35%|███▌      | 752/2129 [00:37<01:08, 20.10it/s]
 35%|███▌      | 755/2129 [00:38<01:41, 13.49it/s]
 36%|███▌      | 758/2129 [00:38<01:33, 14.62it/s]
 36%|███▌      | 761/2129 [00:38<01:22, 16.62it/s]
 36%|███▌      | 764/2129 [00:39<02:08, 10.62it/s]
 36%|███▌      | 768/2129 [00:39<01:36, 14.05it/s]
 36%|███▌      | 771/2129 [00:39<01:45, 12.84it/s]
 36%|███▋      | 774/2129 [00:39<01:48, 12.50it/s]
 36%|███▋      | 776/2129 [00:40<02:21,  9.60it/s]
 37%|███▋      | 779/2129 [00:40<01:53, 11.95it/s]
 37%|███▋      | 782/2129 [00:40<01:49, 12.33it/s]
 37%|███▋      | 785/2129 [00:40<01:50, 12.15it/s]
 37%|███▋      | 788/2129 [00:40<01:37, 13.75it/s]
 37%|███▋      | 791/2129 [00:41<01:28, 15.06it/s]
 37%|███▋      | 793/2129 [00:41<01:48, 12.37it/s]
 37%|███▋      | 795/2129 [00:41<01:42, 13.01it/s]
 37%|███▋      | 797/2129 [00:41<01:41, 13.11it/s]
 38%|███▊      | 799/2129 [00:41<01:36, 13.73it/s]
 38%|███▊      | 801/2129 [00:41<02:08, 10.34it/s]
 38%|███▊      | 803/2129 [00:42<02:16,  9.73it/s]
 38%|███▊      | 805/2129 [00:42<02:00, 10.99it/s]
 38%|███▊      | 810/2129 [00:42<01:24, 15.53it/s]
 38%|███▊      | 812/2129 [00:42<01:21, 16.21it/s]
 38%|███▊      | 814/2129 [00:42<01:36, 13.64it/s]
 38%|███▊      | 816/2129 [00:42<01:34, 13.97it/s]
 39%|███▊      | 822/2129 [00:43<01:00, 21.61it/s]
 39%|███▉      | 825/2129 [00:43<00:59, 22.04it/s]
 39%|███▉      | 830/2129 [00:43<00:48, 26.90it/s]
 39%|███▉      | 835/2129 [00:43<00:41, 31.30it/s]
 39%|███▉      | 839/2129 [00:43<00:49, 26.14it/s]
 40%|███▉      | 842/2129 [00:43<01:04, 20.06it/s]
 40%|███▉      | 845/2129 [00:44<01:53, 11.29it/s]
 40%|███▉      | 848/2129 [00:44<01:35, 13.40it/s]
 40%|████      | 852/2129 [00:44<01:31, 13.92it/s]
 40%|████      | 854/2129 [00:45<01:45, 12.06it/s]
 40%|████      | 856/2129 [00:45<01:53, 11.21it/s]
 40%|████      | 859/2129 [00:45<01:32, 13.74it/s]
 40%|████      | 861/2129 [00:45<01:48, 11.66it/s]
 41%|████      | 863/2129 [00:46<02:03, 10.26it/s]
 41%|████      | 865/2129 [00:46<02:12,  9.53it/s]
 41%|████      | 867/2129 [00:46<02:16,  9.23it/s]
 41%|████      | 870/2129 [00:46<02:03, 10.18it/s]
 41%|████      | 873/2129 [00:46<01:35, 13.17it/s]
 41%|████      | 877/2129 [00:47<01:27, 14.23it/s]
 41%|████▏     | 879/2129 [00:47<01:24, 14.83it/s]
 42%|████▏     | 886/2129 [00:47<01:05, 19.08it/s]
 42%|████▏     | 888/2129 [00:47<01:25, 14.48it/s]
 42%|████▏     | 892/2129 [00:47<01:08, 18.18it/s]
 42%|████▏     | 895/2129 [00:48<01:13, 16.77it/s]
 42%|████▏     | 897/2129 [00:48<01:12, 17.03it/s]
 42%|████▏     | 902/2129 [00:48<01:09, 17.63it/s]
 42%|████▏     | 904/2129 [00:48<01:11, 17.10it/s]
 43%|████▎     | 910/2129 [00:48<00:48, 24.92it/s]
 43%|████▎     | 913/2129 [00:49<01:04, 18.82it/s]
 43%|████▎     | 920/2129 [00:49<00:43, 27.89it/s]
 43%|████▎     | 925/2129 [00:49<00:47, 25.18it/s]
 44%|████▎     | 929/2129 [00:49<00:54, 21.84it/s]
 44%|████▍     | 932/2129 [00:49<00:57, 20.89it/s]
 44%|████▍     | 936/2129 [00:50<01:11, 16.73it/s]
 44%|████▍     | 939/2129 [00:50<01:46, 11.20it/s]
 44%|████▍     | 943/2129 [00:50<01:22, 14.36it/s]
 44%|████▍     | 946/2129 [00:51<01:36, 12.23it/s]
 45%|████▍     | 948/2129 [00:51<01:31, 12.90it/s]
 45%|████▍     | 950/2129 [00:51<01:45, 11.13it/s]
 45%|████▍     | 952/2129 [00:51<01:39, 11.80it/s]
 45%|████▍     | 955/2129 [00:51<01:26, 13.60it/s]
 45%|████▌     | 960/2129 [00:51<00:58, 19.95it/s]
 45%|████▌     | 963/2129 [00:52<01:34, 12.36it/s]
 45%|████▌     | 967/2129 [00:52<01:30, 12.82it/s]
 46%|████▌     | 969/2129 [00:52<01:40, 11.59it/s]
 46%|████▌     | 972/2129 [00:53<01:22, 14.06it/s]
 46%|████▌     | 978/2129 [00:53<00:53, 21.41it/s]
 46%|████▌     | 982/2129 [00:53<01:00, 19.10it/s]
 46%|████▋     | 987/2129 [00:53<00:47, 23.99it/s]
 47%|████▋     | 991/2129 [00:53<01:00, 18.83it/s]
 47%|████▋     | 994/2129 [00:54<01:09, 16.40it/s]
 47%|████▋     | 999/2129 [00:54<00:52, 21.41it/s]
 47%|████▋     | 1002/2129 [00:54<01:00, 18.50it/s]
 47%|████▋     | 1005/2129 [00:54<00:57, 19.48it/s]
 47%|████▋     | 1008/2129 [00:54<01:09, 16.09it/s]
 47%|████▋     | 1010/2129 [00:55<01:22, 13.55it/s]
 48%|████▊     | 1013/2129 [00:55<01:11, 15.61it/s]
 48%|████▊     | 1015/2129 [00:55<01:18, 14.23it/s]
 48%|████▊     | 1017/2129 [00:55<01:34, 11.81it/s]
 48%|████▊     | 1021/2129 [00:55<01:07, 16.41it/s]
 48%|████▊     | 1028/2129 [00:55<00:43, 25.21it/s]
 48%|████▊     | 1032/2129 [00:56<01:06, 16.49it/s]
 49%|████▊     | 1036/2129 [00:56<00:55, 19.81it/s]
 49%|████▉     | 1040/2129 [00:56<01:01, 17.70it/s]
 49%|████▉     | 1043/2129 [00:57<01:14, 14.67it/s]
 49%|████▉     | 1045/2129 [00:57<01:11, 15.25it/s]
 49%|████▉     | 1051/2129 [00:57<01:02, 17.39it/s]
 50%|████▉     | 1054/2129 [00:57<00:57, 18.73it/s]
 50%|████▉     | 1057/2129 [00:57<01:03, 16.81it/s]
 50%|████▉     | 1059/2129 [00:58<01:27, 12.24it/s]
 50%|████▉     | 1062/2129 [00:58<01:12, 14.69it/s]
 50%|█████     | 1068/2129 [00:58<00:47, 22.42it/s]
 50%|█████     | 1072/2129 [00:58<00:51, 20.53it/s]
 51%|█████     | 1077/2129 [00:58<00:41, 25.50it/s]
 51%|█████     | 1081/2129 [00:58<00:49, 21.27it/s]
 51%|█████     | 1084/2129 [00:59<00:47, 21.99it/s]
 51%|█████     | 1087/2129 [00:59<01:01, 17.03it/s]
 51%|█████     | 1091/2129 [00:59<01:03, 16.36it/s]
 51%|█████▏    | 1094/2129 [00:59<01:10, 14.70it/s]
 52%|█████▏    | 1097/2129 [01:00<01:01, 16.84it/s]
 52%|█████▏    | 1101/2129 [01:00<01:02, 16.54it/s]
 52%|█████▏    | 1103/2129 [01:00<01:14, 13.82it/s]
 52%|█████▏    | 1106/2129 [01:00<01:04, 15.76it/s]
 52%|█████▏    | 1109/2129 [01:00<01:07, 15.00it/s]
 52%|█████▏    | 1111/2129 [01:01<01:20, 12.57it/s]
 52%|█████▏    | 1113/2129 [01:01<01:39, 10.22it/s]
 52%|█████▏    | 1115/2129 [01:01<01:41, 10.04it/s]
 53%|█████▎    | 1118/2129 [01:01<01:17, 13.05it/s]
 53%|█████▎    | 1120/2129 [01:01<01:17, 13.01it/s]
 53%|█████▎    | 1123/2129 [01:02<01:07, 14.99it/s]
 53%|█████▎    | 1126/2129 [01:02<00:59, 16.80it/s]
 53%|█████▎    | 1128/2129 [01:02<01:06, 14.94it/s]
 53%|█████▎    | 1131/2129 [01:02<01:14, 13.44it/s]
 53%|█████▎    | 1133/2129 [01:02<01:08, 14.53it/s]
 53%|█████▎    | 1136/2129 [01:02<00:56, 17.44it/s]
 53%|█████▎    | 1138/2129 [01:03<01:08, 14.46it/s]
 54%|█████▎    | 1140/2129 [01:03<01:24, 11.71it/s]
 54%|█████▎    | 1143/2129 [01:03<01:29, 11.06it/s]
 54%|█████▍    | 1146/2129 [01:03<01:29, 10.94it/s]
 54%|█████▍    | 1149/2129 [01:04<01:12, 13.51it/s]
 54%|█████▍    | 1153/2129 [01:04<01:06, 14.77it/s]
 54%|█████▍    | 1155/2129 [01:04<01:02, 15.58it/s]
 54%|█████▍    | 1157/2129 [01:04<01:31, 10.62it/s]
 54%|█████▍    | 1159/2129 [01:04<01:20, 11.99it/s]
 55%|█████▍    | 1166/2129 [01:04<00:44, 21.62it/s]
 55%|█████▍    | 1169/2129 [01:05<00:55, 17.43it/s]
 55%|█████▌    | 1173/2129 [01:05<00:44, 21.25it/s]
 55%|█████▌    | 1180/2129 [01:05<00:39, 23.82it/s]
 56%|█████▌    | 1183/2129 [01:05<00:40, 23.11it/s]
 56%|█████▌    | 1190/2129 [01:06<00:40, 22.97it/s]
 56%|█████▌    | 1193/2129 [01:06<00:42, 22.03it/s]
 56%|█████▌    | 1196/2129 [01:06<00:53, 17.45it/s]
 56%|█████▋    | 1198/2129 [01:06<00:58, 16.01it/s]
 56%|█████▋    | 1200/2129 [01:06<00:58, 15.83it/s]
 57%|█████▋    | 1205/2129 [01:06<00:41, 22.13it/s]
 57%|█████▋    | 1208/2129 [01:07<00:42, 21.56it/s]
 57%|█████▋    | 1211/2129 [01:07<00:48, 18.88it/s]
 57%|█████▋    | 1214/2129 [01:07<01:19, 11.55it/s]
 57%|█████▋    | 1217/2129 [01:08<01:19, 11.51it/s]
 57%|█████▋    | 1219/2129 [01:08<01:25, 10.69it/s]
 57%|█████▋    | 1222/2129 [01:08<01:22, 10.95it/s]
 58%|█████▊    | 1225/2129 [01:08<01:07, 13.32it/s]
 58%|█████▊    | 1227/2129 [01:08<01:12, 12.44it/s]
 58%|█████▊    | 1229/2129 [01:08<01:05, 13.68it/s]
 58%|█████▊    | 1231/2129 [01:09<01:15, 11.88it/s]
 58%|█████▊    | 1233/2129 [01:09<01:07, 13.20it/s]
 58%|█████▊    | 1235/2129 [01:09<01:14, 12.01it/s]
 58%|█████▊    | 1238/2129 [01:09<01:01, 14.58it/s]
 58%|█████▊    | 1245/2129 [01:09<00:37, 23.27it/s]
 59%|█████▊    | 1248/2129 [01:10<00:53, 16.61it/s]
 59%|█████▉    | 1253/2129 [01:10<00:39, 21.91it/s]
 59%|█████▉    | 1256/2129 [01:10<00:50, 17.23it/s]
 59%|█████▉    | 1260/2129 [01:10<00:41, 20.96it/s]
 59%|█████▉    | 1264/2129 [01:10<00:35, 24.18it/s]
 60%|█████▉    | 1270/2129 [01:10<00:27, 31.32it/s]
 60%|█████▉    | 1274/2129 [01:10<00:29, 28.66it/s]
 60%|██████    | 1278/2129 [01:11<00:30, 27.55it/s]
 60%|██████    | 1282/2129 [01:11<00:41, 20.37it/s]
 60%|██████    | 1287/2129 [01:11<00:41, 20.22it/s]
 61%|██████    | 1290/2129 [01:11<00:49, 16.97it/s]
 61%|██████    | 1292/2129 [01:12<00:48, 17.36it/s]
 61%|██████    | 1298/2129 [01:12<00:45, 18.28it/s]
 61%|██████    | 1301/2129 [01:12<00:43, 19.18it/s]
 61%|██████    | 1304/2129 [01:12<00:52, 15.83it/s]
 61%|██████▏   | 1306/2129 [01:13<01:01, 13.34it/s]
 61%|██████▏   | 1308/2129 [01:13<01:14, 11.06it/s]
 62%|██████▏   | 1311/2129 [01:13<01:13, 11.11it/s]
 62%|██████▏   | 1313/2129 [01:14<01:36,  8.47it/s]
 62%|██████▏   | 1316/2129 [01:14<01:15, 10.73it/s]
 62%|██████▏   | 1318/2129 [01:14<01:16, 10.62it/s]
 62%|██████▏   | 1322/2129 [01:14<01:02, 12.92it/s]
 62%|██████▏   | 1324/2129 [01:14<01:00, 13.23it/s]
 62%|██████▏   | 1326/2129 [01:15<01:12, 11.02it/s]
 62%|██████▏   | 1328/2129 [01:15<01:08, 11.76it/s]
 62%|██████▏   | 1330/2129 [01:15<01:01, 12.93it/s]
 63%|██████▎   | 1332/2129 [01:15<01:00, 13.28it/s]
 63%|██████▎   | 1334/2129 [01:15<00:55, 14.32it/s]
 63%|██████▎   | 1339/2129 [01:15<00:35, 22.13it/s]
 63%|██████▎   | 1345/2129 [01:15<00:25, 30.66it/s]
 63%|██████▎   | 1349/2129 [01:15<00:26, 29.91it/s]
 64%|██████▎   | 1354/2129 [01:16<00:30, 25.20it/s]
 64%|██████▎   | 1357/2129 [01:16<00:40, 19.11it/s]
 64%|██████▍   | 1360/2129 [01:16<00:41, 18.40it/s]
 64%|██████▍   | 1364/2129 [01:16<00:36, 20.82it/s]
 64%|██████▍   | 1370/2129 [01:16<00:35, 21.56it/s]
 65%|██████▍   | 1374/2129 [01:17<00:31, 23.62it/s]
 65%|██████▍   | 1377/2129 [01:17<00:40, 18.37it/s]
 65%|██████▍   | 1381/2129 [01:17<00:34, 21.57it/s]
 65%|██████▌   | 1384/2129 [01:17<00:38, 19.32it/s]
 65%|██████▌   | 1387/2129 [01:17<00:40, 18.29it/s]
 65%|██████▌   | 1390/2129 [01:18<00:47, 15.50it/s]
 65%|██████▌   | 1392/2129 [01:18<00:46, 15.77it/s]
 65%|██████▌   | 1394/2129 [01:18<00:56, 12.95it/s]
 66%|██████▌   | 1396/2129 [01:18<00:55, 13.09it/s]
 66%|██████▌   | 1399/2129 [01:18<00:54, 13.31it/s]
 66%|██████▌   | 1402/2129 [01:19<00:46, 15.64it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 316.29it/s]

[[np.int64(0), False, 12], [np.int64(1), False, 3], [np.int64(2), False, 9], [np.int64(3), False, 8], [np.int64(4), False, 5], [np.int64(5), False, 7], [np.int64(6), False, 5], [np.int64(8), False, 2], [np.int64(9), False, 12], [np.int64(10), False, 0], [np.int64(11), False, 2], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0433, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3500, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [10:16<26:16, 32.17s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [10:16<18:02, 22.56s/it]

tensor(12.5358, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0434, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6023, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0436, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8523, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [10:17<05:51,  7.82s/it]

tensor(12.5513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0433, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8887, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0429, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8974, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [10:17<02:47,  3.89s/it]

tensor(12.5603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0428, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9524, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5482, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0434, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8148, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [10:17<01:20,  1.97s/it]

tensor(12.5344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9332, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0342, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [10:17<00:39,  1.02s/it]

tensor(12.5409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0817, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0893, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [10:18<00:20,  1.78it/s]

tensor(12.5238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1796, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2230, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [10:18<00:15,  2.32it/s]

tensor(12.5054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0445, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2414, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0444, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2810, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [10:18<00:07,  4.39it/s]

tensor(12.4923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0444, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3153, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0447, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3412, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [10:18<00:06,  5.10it/s]

tensor(12.4744, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0446, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0438, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3699, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [10:18<00:04,  6.32it/s]

tensor(12.4647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0422, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3836, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3919, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [10:19<00:03,  7.44it/s]

tensor(12.4577, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0378, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3963, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4043, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [10:19<00:03,  7.82it/s]

tensor(12.4401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4103, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4185, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [10:19<00:02,  8.05it/s]

tensor(12.4303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4206, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4178, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [10:19<00:02,  8.09it/s]

tensor(12.4268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4236, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4301, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [10:20<00:02,  8.16it/s]

tensor(12.4210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4407, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4547, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [10:20<00:02,  8.17it/s]

tensor(12.4107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4599, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4715, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [10:20<00:01,  8.21it/s]

tensor(12.4047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4830, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4888, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [10:20<00:01,  8.21it/s]

tensor(12.3995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4963, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [10:21<00:01,  8.23it/s]

tensor(12.3922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4991, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5011, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [10:21<00:01,  8.22it/s]

tensor(12.3865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5017, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5015, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [10:21<00:00,  8.21it/s]

tensor(12.3822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5037, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5056, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [10:21<00:00,  8.20it/s]

tensor(12.3770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5115, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3738, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5124, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [10:22<00:00,  8.21it/s]

tensor(12.3710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5156, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5161, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [10:22<00:00,  8.22it/s]

tensor(12.3665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5171, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5170, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [10:22<00:00,  2.08s/it]

tensor(12.3626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5177, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.001934051513671875
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 7
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.507631836929
NMI         : 0.579140510549
Runtime     : 667.82 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed7

==============================================================================================================
PRAGA RUN | E18.5 | seed=8
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 3.699e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(15.8316, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4773, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8422, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2254, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:32,  9.18it/s]

tensor(15.7567, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1945, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6571, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3641, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:32,  9.15it/s]

tensor(15.5736, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7129, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5157, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2245, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:30,  9.54it/s]

tensor(15.4651, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8824, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4324, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6723, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4081, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5820, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:29,  9.69it/s]

tensor(15.3890, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5986, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3688, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7118, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:29,  9.79it/s]

tensor(15.3501, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9137, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3227, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1934, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:29,  9.59it/s]

tensor(15.2989, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5449, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2718, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9603, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:28,  9.87it/s]

tensor(15.2407, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2101, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9595, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1793, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5326, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:28,  9.86it/s]

tensor(15.1466, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.1478, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1178, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8013, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:02<00:28,  9.83it/s]

tensor(15.0807, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4901, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0412, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2098, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:28,  9.85it/s]

tensor(14.9967, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9579, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9473, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7308, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:28,  9.68it/s]

tensor(14.8969, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5273, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8480, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3447, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:27,  9.87it/s]

tensor(14.7985, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1802, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7515, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0330, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:27,  9.88it/s]

tensor(14.7045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9009, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7825, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.88it/s]

tensor(14.6018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6769, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5464, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5824, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:27,  9.84it/s]

tensor(14.4916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4978, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4229, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:26,  9.84it/s]

tensor(14.3817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3562, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2970, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.83it/s]

tensor(14.2748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2446, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1989, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:04<00:26,  9.66it/s]

tensor(14.1696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1585, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1243, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:26,  9.82it/s]

tensor(14.0716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0950, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0714, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0536, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:25,  9.86it/s]

tensor(13.9435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0419, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 47/300 [00:04<00:25,  9.85it/s]

tensor(13.8742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:05<00:25,  9.85it/s]

tensor(13.8146, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:05<00:25,  9.86it/s]

tensor(13.7612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.72it/s]

tensor(13.7095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:24,  9.86it/s]

tensor(13.6613, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:24,  9.86it/s]

tensor(13.6192, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6012, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:06<00:24,  9.83it/s]

tensor(13.5844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:06<00:24,  9.63it/s]

tensor(13.5510, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5352, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:24,  9.83it/s]

tensor(13.5178, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:24,  9.56it/s]

tensor(13.4836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:24,  9.44it/s]

tensor(13.4498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4329, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:07<00:24,  9.46it/s]

tensor(13.4173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:24,  9.50it/s]

tensor(13.3856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:23,  9.58it/s]

tensor(13.3543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3384, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:23,  9.43it/s]

tensor(13.3230, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 77/300 [00:07<00:23,  9.47it/s]

tensor(13.2917, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:22,  9.66it/s]

tensor(13.2606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:08<00:23,  9.39it/s]

tensor(13.2295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:23,  9.27it/s]

tensor(13.1986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:23,  9.25it/s]

tensor(13.1676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1517, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:09<00:22,  9.51it/s]

tensor(13.1360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:09<00:21,  9.69it/s]

tensor(13.1046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:09<00:21,  9.71it/s]

tensor(13.0734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0577, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:22,  9.30it/s]

tensor(13.0420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:21,  9.35it/s]

tensor(13.0115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:10<00:21,  9.41it/s]

tensor(12.9807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:10<00:21,  9.34it/s]

tensor(12.9509, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:21,  9.21it/s]

tensor(12.9212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([275, 219, 118, 298, 102, 124, 143,  41, 106, 207, 138, 167, 112,  79])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 4/2129 [00:00<00:59, 35.66it/s]
  1%|          | 12/2129 [00:00<00:35, 59.56it/s]
  1%|          | 21/2129 [00:00<00:30, 70.09it/s]
  1%|▏         | 29/2129 [00:00<00:35, 59.09it/s]
  2%|▏         | 37/2129 [00:00<00:32, 63.44it/s]
  2%|▏         | 44/2129 [00:00<00:32, 64.35it/s]
  2%|▏         | 51/2129 [00:00<00:35, 57.97it/s]
  3%|▎         | 58/2129 [00:00<00:34, 60.78it/s]
  3%|▎         | 65/2129 [00:01<00:57, 36.12it/s]
  3%|▎         | 70/2129 [00:01<00:58, 35.30it/s]
  4%|▎         | 78/2129 [00:01<00:47, 43.61it/s]
  4%|▍         | 84/2129 [00:02<01:20, 25.43it/s]
  4%|▍         | 91/2129 [00:02<01:04, 31.74it/s]
  5%|▍         | 96/2129 [00:02<01:07, 30.08it/s]
  5%|▍         | 101/2129 [00:02<01:04, 31.61it/s]
  5%|▍         | 106/2129 [00:03<01:58, 17.12it/s]
  5%|▌         | 110/2129 [00:03<02:14, 15.06it/s]
  5%|▌         | 113/2129 [00:03<02:19, 14.46it/s]
  5%|▌         | 116/2129 [00:03<02:04, 16.20it/s]
  6%|▌         | 123/2129 [00:03<01:23, 24.07it/s]
  6%|▌         | 127/2129 [00:04<01:19, 25.31it/s]
  6%|▌         | 131/2129 [00:04<01:15, 26.58it/s]
  6%|▋         | 135/2129 [00:04<02:03, 16.15it/s]
  6%|▋         | 138/2129 [00:04<01:56, 17.14it/s]
  7%|▋         | 144/2129 [00:05<01:24, 23.45it/s]
  7%|▋         | 148/2129 [00:05<01:19, 24.86it/s]
  7%|▋         | 152/2129 [00:05<01:37, 20.32it/s]
  7%|▋         | 155/2129 [00:05<01:31, 21.66it/s]
  7%|▋         | 158/2129 [00:05<01:55, 17.10it/s]
  8%|▊         | 161/2129 [00:05<01:48, 18.21it/s]
  8%|▊         | 164/2129 [00:06<02:09, 15.13it/s]
  8%|▊         | 166/2129 [00:06<02:17, 14.32it/s]
  8%|▊         | 169/2129 [00:06<02:01, 16.07it/s]
  8%|▊         | 171/2129 [00:06<02:10, 15.03it/s]
  8%|▊         | 174/2129 [00:06<01:59, 16.32it/s]
  8%|▊         | 176/2129 [00:06<01:57, 16.67it/s]
  8%|▊         | 178/2129 [00:07<02:11, 14.78it/s]
  9%|▊         | 184/2129 [00:07<01:46, 18.19it/s]
  9%|▊         | 186/2129 [00:07<01:48, 17.84it/s]
  9%|▉         | 188/2129 [00:07<02:08, 15.10it/s]
  9%|▉         | 190/2129 [00:07<02:30, 12.92it/s]
  9%|▉         | 192/2129 [00:08<02:24, 13.44it/s]
  9%|▉         | 195/2129 [00:08<01:56, 16.64it/s]
  9%|▉         | 200/2129 [00:08<01:27, 22.05it/s]
 10%|▉         | 203/2129 [00:08<01:40, 19.22it/s]
 10%|▉         | 209/2129 [00:08<01:09, 27.47it/s]
 10%|█         | 213/2129 [00:08<01:28, 21.59it/s]
 10%|█         | 216/2129 [00:09<02:14, 14.26it/s]
 10%|█         | 219/2129 [00:09<01:56, 16.43it/s]
 10%|█         | 223/2129 [00:09<01:56, 16.37it/s]
 11%|█         | 226/2129 [00:10<02:22, 13.39it/s]
 11%|█         | 230/2129 [00:10<01:51, 16.98it/s]
 11%|█         | 233/2129 [00:10<02:00, 15.71it/s]
 11%|█         | 236/2129 [00:10<02:22, 13.31it/s]
 11%|█         | 239/2129 [00:10<02:25, 12.97it/s]
 11%|█▏        | 241/2129 [00:11<02:15, 13.96it/s]
 12%|█▏        | 246/2129 [00:11<01:57, 16.01it/s]
 12%|█▏        | 248/2129 [00:11<02:16, 13.75it/s]
 12%|█▏        | 250/2129 [00:11<02:51, 10.99it/s]
 12%|█▏        | 252/2129 [00:12<03:21,  9.30it/s]
 12%|█▏        | 254/2129 [00:12<02:54, 10.75it/s]
 12%|█▏        | 258/2129 [00:12<02:31, 12.36it/s]
 12%|█▏        | 261/2129 [00:12<02:41, 11.57it/s]
 12%|█▏        | 263/2129 [00:12<02:27, 12.63it/s]
 13%|█▎        | 267/2129 [00:13<02:12, 14.03it/s]
 13%|█▎        | 269/2129 [00:13<02:34, 12.02it/s]
 13%|█▎        | 272/2129 [00:13<02:08, 14.43it/s]
 13%|█▎        | 275/2129 [00:13<02:08, 14.47it/s]
 13%|█▎        | 278/2129 [00:13<01:49, 16.87it/s]
 13%|█▎        | 285/2129 [00:13<01:08, 26.83it/s]
 14%|█▎        | 289/2129 [00:14<01:28, 20.75it/s]
 14%|█▎        | 292/2129 [00:14<01:43, 17.81it/s]
 14%|█▍        | 295/2129 [00:14<02:24, 12.72it/s]
 14%|█▍        | 298/2129 [00:15<02:06, 14.47it/s]
 14%|█▍        | 304/2129 [00:15<01:46, 17.13it/s]
 14%|█▍        | 307/2129 [00:15<02:19, 13.11it/s]
 15%|█▍        | 312/2129 [00:15<01:56, 15.62it/s]
 15%|█▍        | 314/2129 [00:16<02:08, 14.10it/s]
 15%|█▍        | 316/2129 [00:16<02:18, 13.05it/s]
 15%|█▍        | 318/2129 [00:16<02:10, 13.93it/s]
 15%|█▌        | 320/2129 [00:16<02:29, 12.06it/s]
 15%|█▌        | 322/2129 [00:16<02:45, 10.92it/s]
 15%|█▌        | 324/2129 [00:17<02:56, 10.22it/s]
 15%|█▌        | 327/2129 [00:17<02:20, 12.84it/s]
 15%|█▌        | 329/2129 [00:17<02:44, 10.97it/s]
 16%|█▌        | 331/2129 [00:17<02:56, 10.21it/s]
 16%|█▌        | 334/2129 [00:18<02:52, 10.39it/s]
 16%|█▌        | 336/2129 [00:18<02:37, 11.38it/s]
 16%|█▌        | 338/2129 [00:18<02:56, 10.14it/s]
 16%|█▌        | 342/2129 [00:18<01:59, 14.94it/s]
 16%|█▌        | 344/2129 [00:18<02:24, 12.34it/s]
 16%|█▋        | 346/2129 [00:19<02:41, 11.05it/s]
 16%|█▋        | 349/2129 [00:19<02:40, 11.12it/s]
 16%|█▋        | 351/2129 [00:19<02:53, 10.25it/s]
 17%|█▋        | 354/2129 [00:19<02:31, 11.70it/s]
 17%|█▋        | 356/2129 [00:19<02:46, 10.66it/s]
 17%|█▋        | 358/2129 [00:20<03:21,  8.79it/s]
 17%|█▋        | 360/2129 [00:20<02:54, 10.13it/s]
 17%|█▋        | 362/2129 [00:20<03:39,  8.06it/s]
 17%|█▋        | 364/2129 [00:21<04:01,  7.30it/s]
 17%|█▋        | 366/2129 [00:21<03:18,  8.87it/s]
 17%|█▋        | 372/2129 [00:21<01:45, 16.70it/s]
 18%|█▊        | 375/2129 [00:21<02:21, 12.36it/s]
 18%|█▊        | 378/2129 [00:22<02:36, 11.19it/s]
 18%|█▊        | 380/2129 [00:22<02:41, 10.82it/s]
 18%|█▊        | 382/2129 [00:22<02:27, 11.82it/s]
 18%|█▊        | 384/2129 [00:22<02:34, 11.31it/s]
 18%|█▊        | 386/2129 [00:23<03:28,  8.37it/s]
 18%|█▊        | 388/2129 [00:23<02:55,  9.90it/s]
 18%|█▊        | 391/2129 [00:23<02:39, 10.93it/s]
 19%|█▊        | 394/2129 [00:23<02:43, 10.58it/s]
 19%|█▊        | 397/2129 [00:23<02:13, 12.94it/s]
 19%|█▉        | 400/2129 [00:24<02:15, 12.74it/s]
 19%|█▉        | 403/2129 [00:24<01:54, 15.01it/s]
 19%|█▉        | 405/2129 [00:24<02:10, 13.21it/s]
 19%|█▉        | 407/2129 [00:24<02:01, 14.21it/s]
 19%|█▉        | 409/2129 [00:24<02:18, 12.38it/s]
 19%|█▉        | 413/2129 [00:24<01:39, 17.32it/s]
 20%|█▉        | 419/2129 [00:25<01:23, 20.50it/s]
 20%|█▉        | 422/2129 [00:25<01:37, 17.51it/s]
 20%|██        | 428/2129 [00:25<01:09, 24.57it/s]
 20%|██        | 432/2129 [00:25<01:33, 18.17it/s]
 20%|██        | 435/2129 [00:26<01:52, 15.11it/s]
 21%|██        | 437/2129 [00:26<02:00, 14.02it/s]
 21%|██        | 439/2129 [00:26<01:59, 14.16it/s]
 21%|██        | 442/2129 [00:26<01:42, 16.38it/s]
 21%|██        | 446/2129 [00:26<01:38, 17.03it/s]
 21%|██        | 449/2129 [00:26<01:31, 18.36it/s]
 21%|██▏       | 455/2129 [00:27<01:18, 21.23it/s]
 22%|██▏       | 458/2129 [00:27<01:47, 15.61it/s]
 22%|██▏       | 460/2129 [00:27<02:10, 12.76it/s]
 22%|██▏       | 464/2129 [00:27<01:40, 16.63it/s]
 22%|██▏       | 467/2129 [00:28<01:50, 15.02it/s]
 22%|██▏       | 469/2129 [00:28<02:10, 12.74it/s]
 22%|██▏       | 471/2129 [00:28<02:32, 10.88it/s]
 22%|██▏       | 473/2129 [00:28<02:48,  9.81it/s]
 22%|██▏       | 476/2129 [00:29<02:18, 11.97it/s]
 22%|██▏       | 478/2129 [00:29<03:21,  8.19it/s]
 23%|██▎       | 480/2129 [00:29<02:51,  9.59it/s]
 23%|██▎       | 482/2129 [00:29<02:49,  9.73it/s]
 23%|██▎       | 484/2129 [00:30<03:35,  7.62it/s]
 23%|██▎       | 486/2129 [00:30<03:00,  9.09it/s]
 23%|██▎       | 488/2129 [00:30<03:07,  8.76it/s]
 23%|██▎       | 490/2129 [00:30<03:12,  8.52it/s]
 23%|██▎       | 494/2129 [00:30<02:08, 12.76it/s]
 23%|██▎       | 496/2129 [00:31<02:18, 11.77it/s]
 23%|██▎       | 498/2129 [00:31<02:06, 12.92it/s]
 24%|██▎       | 501/2129 [00:31<02:07, 12.81it/s]
 24%|██▎       | 504/2129 [00:31<01:47, 15.17it/s]
 24%|██▍       | 508/2129 [00:31<01:43, 15.63it/s]
 24%|██▍       | 510/2129 [00:32<02:08, 12.58it/s]
 24%|██▍       | 514/2129 [00:32<01:36, 16.82it/s]
 24%|██▍       | 517/2129 [00:32<01:54, 14.11it/s]
 24%|██▍       | 520/2129 [00:32<02:13, 12.04it/s]
 25%|██▍       | 522/2129 [00:33<02:57,  9.03it/s]
 25%|██▍       | 525/2129 [00:33<02:21, 11.31it/s]
 25%|██▍       | 527/2129 [00:33<02:28, 10.80it/s]
 25%|██▍       | 529/2129 [00:34<03:09,  8.45it/s]
 25%|██▍       | 531/2129 [00:34<03:17,  8.07it/s]
 25%|██▌       | 535/2129 [00:34<02:28, 10.77it/s]
 25%|██▌       | 537/2129 [00:34<02:41,  9.86it/s]
 25%|██▌       | 540/2129 [00:34<02:07, 12.50it/s]
 26%|██▌       | 543/2129 [00:35<01:51, 14.17it/s]
 26%|██▌       | 545/2129 [00:35<01:45, 14.97it/s]
 26%|██▌       | 547/2129 [00:35<02:15, 11.69it/s]
 26%|██▌       | 549/2129 [00:35<02:17, 11.52it/s]
 26%|██▌       | 552/2129 [00:35<01:52, 13.99it/s]
 26%|██▌       | 554/2129 [00:35<01:46, 14.83it/s]
 26%|██▌       | 557/2129 [00:35<01:33, 16.87it/s]
 26%|██▋       | 559/2129 [00:36<02:01, 12.96it/s]
 26%|██▋       | 562/2129 [00:36<01:40, 15.53it/s]
 26%|██▋       | 564/2129 [00:36<01:55, 13.56it/s]
 27%|██▋       | 566/2129 [00:36<02:33, 10.18it/s]
 27%|██▋       | 568/2129 [00:37<02:36,  9.95it/s]
 27%|██▋       | 571/2129 [00:37<02:32, 10.22it/s]
 27%|██▋       | 573/2129 [00:37<02:39,  9.73it/s]
 27%|██▋       | 576/2129 [00:37<02:07, 12.17it/s]
 27%|██▋       | 578/2129 [00:38<02:28, 10.44it/s]
 27%|██▋       | 581/2129 [00:38<02:23, 10.75it/s]
 27%|██▋       | 583/2129 [00:38<02:50,  9.07it/s]
 27%|██▋       | 585/2129 [00:39<03:27,  7.44it/s]
 28%|██▊       | 586/2129 [00:39<03:35,  7.15it/s]
 28%|██▊       | 587/2129 [00:39<03:47,  6.79it/s]
 28%|██▊       | 589/2129 [00:39<03:36,  7.13it/s]
 28%|██▊       | 590/2129 [00:39<04:11,  6.12it/s]
 28%|██▊       | 593/2129 [00:40<03:21,  7.64it/s]
 28%|██▊       | 596/2129 [00:40<02:21, 10.82it/s]
 28%|██▊       | 599/2129 [00:40<02:09, 11.82it/s]
 28%|██▊       | 601/2129 [00:40<01:58, 12.95it/s]
 28%|██▊       | 603/2129 [00:40<02:16, 11.14it/s]
 28%|██▊       | 605/2129 [00:41<02:34,  9.89it/s]
 29%|██▊       | 607/2129 [00:41<02:13, 11.43it/s]
 29%|██▊       | 610/2129 [00:41<02:03, 12.26it/s]
 29%|██▊       | 612/2129 [00:41<02:20, 10.78it/s]
 29%|██▉       | 614/2129 [00:41<02:32,  9.97it/s]
 29%|██▉       | 618/2129 [00:42<01:41, 14.83it/s]
 29%|██▉       | 622/2129 [00:42<01:39, 15.15it/s]
 29%|██▉       | 625/2129 [00:42<01:26, 17.35it/s]
 29%|██▉       | 628/2129 [00:42<02:05, 11.99it/s]
 30%|██▉       | 631/2129 [00:42<01:47, 13.91it/s]
 30%|██▉       | 633/2129 [00:43<02:04, 12.01it/s]
 30%|██▉       | 636/2129 [00:43<02:09, 11.56it/s]
 30%|███       | 639/2129 [00:43<01:47, 13.87it/s]
 30%|███       | 641/2129 [00:43<02:01, 12.29it/s]
 30%|███       | 644/2129 [00:44<02:03, 12.00it/s]
 30%|███       | 646/2129 [00:44<02:15, 10.93it/s]
 30%|███       | 649/2129 [00:44<02:13, 11.12it/s]
 31%|███       | 651/2129 [00:44<01:58, 12.42it/s]
 31%|███       | 653/2129 [00:44<02:07, 11.56it/s]
 31%|███       | 655/2129 [00:45<01:58, 12.45it/s]
 31%|███       | 658/2129 [00:45<01:58, 12.43it/s]
 31%|███       | 660/2129 [00:45<01:53, 13.00it/s]
 31%|███       | 662/2129 [00:45<03:04,  7.97it/s]
 31%|███       | 664/2129 [00:46<03:01,  8.07it/s]
 31%|███▏      | 667/2129 [00:46<02:45,  8.85it/s]
 31%|███▏      | 670/2129 [00:46<02:07, 11.45it/s]
 32%|███▏      | 672/2129 [00:46<02:13, 10.88it/s]
 32%|███▏      | 674/2129 [00:46<01:59, 12.13it/s]
 32%|███▏      | 677/2129 [00:47<02:02, 11.81it/s]
 32%|███▏      | 679/2129 [00:47<01:52, 12.89it/s]
 32%|███▏      | 684/2129 [00:47<01:38, 14.65it/s]
 32%|███▏      | 686/2129 [00:47<02:00, 11.94it/s]
 32%|███▏      | 688/2129 [00:48<02:11, 10.93it/s]
 32%|███▏      | 690/2129 [00:48<02:16, 10.55it/s]
 33%|███▎      | 692/2129 [00:48<02:00, 11.95it/s]
 33%|███▎      | 694/2129 [00:48<02:06, 11.37it/s]
 33%|███▎      | 696/2129 [00:48<02:17, 10.42it/s]
 33%|███▎      | 698/2129 [00:48<01:58, 12.04it/s]
 33%|███▎      | 703/2129 [00:49<01:33, 15.28it/s]
 33%|███▎      | 705/2129 [00:49<02:00, 11.83it/s]
 33%|███▎      | 707/2129 [00:49<02:22,  9.97it/s]
 33%|███▎      | 709/2129 [00:50<02:33,  9.27it/s]
 33%|███▎      | 712/2129 [00:50<02:23,  9.90it/s]
 34%|███▎      | 714/2129 [00:50<02:29,  9.47it/s]
 34%|███▎      | 718/2129 [00:50<01:42, 13.81it/s]
 34%|███▍      | 721/2129 [00:50<01:37, 14.45it/s]
 34%|███▍      | 723/2129 [00:51<01:53, 12.43it/s]
 34%|███▍      | 725/2129 [00:51<02:05, 11.16it/s]
 34%|███▍      | 727/2129 [00:51<02:58,  7.87it/s]
 34%|███▍      | 729/2129 [00:51<02:43,  8.54it/s]
 34%|███▍      | 731/2129 [00:52<02:19, 10.02it/s]
 34%|███▍      | 733/2129 [00:52<02:22,  9.78it/s]
 35%|███▍      | 735/2129 [00:52<02:52,  8.07it/s]
 35%|███▍      | 739/2129 [00:52<02:08, 10.84it/s]
 35%|███▍      | 742/2129 [00:52<01:43, 13.46it/s]
 35%|███▌      | 749/2129 [00:53<00:59, 23.02it/s]
 35%|███▌      | 753/2129 [00:53<01:22, 16.65it/s]
 36%|███▌      | 756/2129 [00:53<01:27, 15.72it/s]
 36%|███▌      | 759/2129 [00:53<01:17, 17.72it/s]
 36%|███▌      | 762/2129 [00:53<01:23, 16.32it/s]
 36%|███▌      | 765/2129 [00:54<01:41, 13.47it/s]
 36%|███▌      | 767/2129 [00:54<02:22,  9.54it/s]
 36%|███▌      | 769/2129 [00:55<02:29,  9.10it/s]
 36%|███▋      | 772/2129 [00:55<01:59, 11.38it/s]
 36%|███▋      | 774/2129 [00:55<02:01, 11.12it/s]
 36%|███▋      | 776/2129 [00:55<02:42,  8.35it/s]
 37%|███▋      | 779/2129 [00:55<02:03, 10.89it/s]
 37%|███▋      | 781/2129 [00:56<02:13, 10.09it/s]
 37%|███▋      | 783/2129 [00:56<02:17,  9.79it/s]
 37%|███▋      | 785/2129 [00:56<02:18,  9.69it/s]
 37%|███▋      | 788/2129 [00:56<01:45, 12.70it/s]
 37%|███▋      | 792/2129 [00:56<01:34, 14.22it/s]
 37%|███▋      | 794/2129 [00:57<01:49, 12.15it/s]
 37%|███▋      | 796/2129 [00:57<02:35,  8.55it/s]
 37%|███▋      | 798/2129 [00:57<02:48,  7.88it/s]
 38%|███▊      | 800/2129 [00:58<02:48,  7.89it/s]
 38%|███▊      | 802/2129 [00:58<03:23,  6.52it/s]
 38%|███▊      | 804/2129 [00:58<02:45,  7.99it/s]
 38%|███▊      | 809/2129 [00:58<01:40, 13.18it/s]
 38%|███▊      | 811/2129 [00:58<01:38, 13.38it/s]
 38%|███▊      | 813/2129 [00:59<01:45, 12.51it/s]
 38%|███▊      | 816/2129 [00:59<01:27, 15.07it/s]
 38%|███▊      | 818/2129 [00:59<01:31, 14.30it/s]
 39%|███▊      | 820/2129 [00:59<01:51, 11.79it/s]
 39%|███▊      | 823/2129 [00:59<01:28, 14.68it/s]
 39%|███▉      | 827/2129 [01:00<01:22, 15.84it/s]
 39%|███▉      | 830/2129 [01:00<01:13, 17.71it/s]
 39%|███▉      | 835/2129 [01:00<01:10, 18.48it/s]
 39%|███▉      | 837/2129 [01:00<01:10, 18.28it/s]
 39%|███▉      | 839/2129 [01:00<01:47, 11.98it/s]
 40%|███▉      | 842/2129 [01:01<01:47, 12.00it/s]
 40%|███▉      | 844/2129 [01:01<02:23,  8.93it/s]
 40%|███▉      | 846/2129 [01:01<02:42,  7.89it/s]
 40%|███▉      | 848/2129 [01:02<02:39,  8.04it/s]
 40%|███▉      | 851/2129 [01:02<02:02, 10.45it/s]
 40%|████      | 853/2129 [01:02<01:57, 10.82it/s]
 40%|████      | 855/2129 [01:02<02:34,  8.26it/s]
 40%|████      | 857/2129 [01:02<02:12,  9.62it/s]
 40%|████      | 859/2129 [01:03<01:52, 11.27it/s]
 40%|████      | 861/2129 [01:03<02:02, 10.36it/s]
 41%|████      | 863/2129 [01:03<02:11,  9.61it/s]
 41%|████      | 865/2129 [01:03<02:13,  9.45it/s]
 41%|████      | 867/2129 [01:03<02:10,  9.64it/s]
 41%|████      | 870/2129 [01:04<02:00, 10.42it/s]
 41%|████      | 872/2129 [01:04<01:46, 11.85it/s]
 41%|████      | 874/2129 [01:04<01:34, 13.22it/s]
 41%|████      | 877/2129 [01:04<01:32, 13.60it/s]
 41%|████▏     | 879/2129 [01:04<01:30, 13.84it/s]
 41%|████▏     | 882/2129 [01:04<01:22, 15.14it/s]
 42%|████▏     | 884/2129 [01:05<01:17, 16.14it/s]
 42%|████▏     | 887/2129 [01:05<01:31, 13.53it/s]
 42%|████▏     | 890/2129 [01:05<01:45, 11.77it/s]
 42%|████▏     | 892/2129 [01:05<01:58, 10.42it/s]
 42%|████▏     | 894/2129 [01:06<02:06,  9.78it/s]
 42%|████▏     | 896/2129 [01:06<02:30,  8.21it/s]
 42%|████▏     | 898/2129 [01:06<02:32,  8.06it/s]
 42%|████▏     | 900/2129 [01:06<02:08,  9.58it/s]
 42%|████▏     | 902/2129 [01:07<02:22,  8.61it/s]
 42%|████▏     | 904/2129 [01:07<02:39,  7.69it/s]
 43%|████▎     | 906/2129 [01:07<02:38,  7.70it/s]
 43%|████▎     | 908/2129 [01:08<02:40,  7.63it/s]
 43%|████▎     | 910/2129 [01:08<02:14,  9.04it/s]
 43%|████▎     | 912/2129 [01:08<02:28,  8.18it/s]
 43%|████▎     | 914/2129 [01:08<02:04,  9.78it/s]
 43%|████▎     | 916/2129 [01:08<02:00, 10.08it/s]
 43%|████▎     | 918/2129 [01:08<01:43, 11.68it/s]
 43%|████▎     | 925/2129 [01:09<01:10, 17.19it/s]
 44%|████▎     | 927/2129 [01:09<01:40, 11.99it/s]
 44%|████▎     | 929/2129 [01:09<01:50, 10.83it/s]
 44%|████▎     | 931/2129 [01:09<01:58, 10.12it/s]
 44%|████▍     | 934/2129 [01:10<01:34, 12.65it/s]
 44%|████▍     | 936/2129 [01:10<01:41, 11.72it/s]
 44%|████▍     | 938/2129 [01:10<02:17,  8.67it/s]
 44%|████▍     | 940/2129 [01:10<02:24,  8.23it/s]
 44%|████▍     | 944/2129 [01:11<01:56, 10.14it/s]
 44%|████▍     | 946/2129 [01:11<02:00,  9.83it/s]
 45%|████▍     | 948/2129 [01:11<01:45, 11.25it/s]
 45%|████▍     | 950/2129 [01:11<01:48, 10.85it/s]
 45%|████▍     | 953/2129 [01:11<01:25, 13.70it/s]
 45%|████▍     | 955/2129 [01:12<01:38, 11.94it/s]
 45%|████▍     | 958/2129 [01:12<01:23, 13.98it/s]
 45%|████▌     | 960/2129 [01:12<01:33, 12.51it/s]
 45%|████▌     | 962/2129 [01:12<01:38, 11.84it/s]
 45%|████▌     | 964/2129 [01:12<01:41, 11.51it/s]
 45%|████▌     | 967/2129 [01:13<01:44, 11.15it/s]
 46%|████▌     | 969/2129 [01:13<01:53, 10.25it/s]
 46%|████▌     | 971/2129 [01:13<02:14,  8.60it/s]
 46%|████▌     | 973/2129 [01:13<02:15,  8.56it/s]
 46%|████▌     | 974/2129 [01:14<02:32,  7.56it/s]
 46%|████▌     | 977/2129 [01:14<02:13,  8.61it/s]
 46%|████▌     | 980/2129 [01:14<01:39, 11.52it/s]
 46%|████▌     | 982/2129 [01:14<01:52, 10.20it/s]
 46%|████▋     | 986/2129 [01:14<01:18, 14.61it/s]
 46%|████▋     | 988/2129 [01:15<01:24, 13.43it/s]
 47%|████▋     | 991/2129 [01:15<01:13, 15.51it/s]
 47%|████▋     | 993/2129 [01:15<01:22, 13.72it/s]
 47%|████▋     | 996/2129 [01:15<01:08, 16.46it/s]
 47%|████▋     | 1001/2129 [01:15<01:02, 17.92it/s]
 47%|████▋     | 1003/2129 [01:16<01:17, 14.54it/s]
 47%|████▋     | 1006/2129 [01:16<01:25, 13.11it/s]
 47%|████▋     | 1008/2129 [01:16<01:20, 13.89it/s]
 47%|████▋     | 1010/2129 [01:16<01:28, 12.62it/s]
 48%|████▊     | 1012/2129 [01:16<01:39, 11.25it/s]
 48%|████▊     | 1014/2129 [01:17<01:45, 10.57it/s]
 48%|████▊     | 1016/2129 [01:17<02:17,  8.08it/s]
 48%|████▊     | 1019/2129 [01:17<02:06,  8.79it/s]
 48%|████▊     | 1022/2129 [01:17<01:37, 11.34it/s]
 48%|████▊     | 1024/2129 [01:18<02:15,  8.16it/s]
 48%|████▊     | 1026/2129 [01:18<01:58,  9.35it/s]
 48%|████▊     | 1028/2129 [01:18<01:53,  9.67it/s]
 48%|████▊     | 1030/2129 [01:18<01:56,  9.46it/s]
 48%|████▊     | 1032/2129 [01:19<02:06,  8.67it/s]
 49%|████▉     | 1038/2129 [01:19<01:06, 16.29it/s]
 49%|████▉     | 1041/2129 [01:19<01:05, 16.52it/s]
 49%|████▉     | 1044/2129 [01:19<01:18, 13.87it/s]
 49%|████▉     | 1048/2129 [01:20<01:14, 14.44it/s]
 49%|████▉     | 1051/2129 [01:20<01:12, 14.91it/s]
 50%|████▉     | 1054/2129 [01:20<01:08, 15.71it/s]
 50%|████▉     | 1056/2129 [01:20<01:27, 12.20it/s]
 50%|████▉     | 1058/2129 [01:20<01:28, 12.05it/s]
 50%|████▉     | 1060/2129 [01:21<01:47,  9.95it/s]
 50%|████▉     | 1063/2129 [01:21<01:28, 11.99it/s]
 50%|█████     | 1065/2129 [01:21<01:39, 10.73it/s]
 50%|█████     | 1067/2129 [01:21<01:32, 11.51it/s]
 50%|█████     | 1069/2129 [01:21<01:43, 10.29it/s]
 50%|█████     | 1071/2129 [01:22<02:22,  7.44it/s]
 50%|█████     | 1073/2129 [01:22<01:56,  9.04it/s]
 50%|█████     | 1075/2129 [01:22<02:15,  7.79it/s]
 51%|█████     | 1077/2129 [01:23<02:12,  7.96it/s]
 51%|█████     | 1080/2129 [01:23<01:59,  8.74it/s]
 51%|█████     | 1082/2129 [01:23<01:44, 10.04it/s]
 51%|█████     | 1085/2129 [01:23<01:33, 11.18it/s]
 51%|█████     | 1088/2129 [01:23<01:14, 14.07it/s]
 51%|█████     | 1091/2129 [01:24<01:17, 13.35it/s]
 51%|█████▏    | 1094/2129 [01:24<01:21, 12.71it/s]
 51%|█████▏    | 1096/2129 [01:24<01:17, 13.26it/s]
 52%|█████▏    | 1101/2129 [01:24<01:03, 16.09it/s]
 52%|█████▏    | 1103/2129 [01:25<01:27, 11.75it/s]
 52%|█████▏    | 1105/2129 [01:25<01:20, 12.67it/s]
 52%|█████▏    | 1107/2129 [01:25<01:33, 10.92it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 323.38it/s]
 34%|███▎      | 101/300 [02:52<2:41:11, 48.60s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 9], [np.int64(2), False, 9], [np.int64(3), False, 0], [np.int64(4), False, 12], [np.int64(5), False, 11], [np.int64(6), False, 12], [np.int64(7), False, 11], [np.int64(8), False, 1], [np.int64(10), False, 11], [np.int64(12), False, 10], [np.int64(13), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-1.9148, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.9030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>)

 34%|███▍      | 102/300 [02:52<1:52:27, 34.08s/it]

tensor(-2.1911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9404, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.5606, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [02:52<38:15, 11.77s/it]

tensor(13.0118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8336, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0127, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [02:53<18:45,  5.83s/it]

tensor(13.1162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0987, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1164, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1931, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [02:53<09:17,  2.92s/it]

tensor(13.0879, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2894, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0511, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3897, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [02:53<04:41,  1.49s/it]

tensor(13.0264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4611, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5247, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [02:53<03:22,  1.08s/it]

tensor(12.9841, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5510, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5979, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [02:53<01:50,  1.69it/s]

tensor(12.8850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6578, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7298, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [02:54<00:51,  3.54it/s]

tensor(12.8692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8178, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [02:54<00:36,  5.00it/s]

tensor(12.8549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8532, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8971, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [02:54<00:31,  5.64it/s]

tensor(12.7982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9243, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9497, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [02:54<00:24,  7.14it/s]

tensor(12.7437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9742, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9947, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [02:55<00:23,  7.45it/s]

tensor(12.7126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0238, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6992, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0556, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [02:55<00:21,  7.97it/s]

tensor(12.6856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0843, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6725, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1190, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [02:55<00:21,  7.95it/s]

tensor(12.6586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1427, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1657, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [02:55<00:20,  8.19it/s]

tensor(12.6275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1730, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1878, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [02:56<00:20,  8.20it/s]

tensor(12.6023, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2004, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2220, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [02:56<00:20,  8.22it/s]

tensor(12.5776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2609, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [02:56<00:19,  8.21it/s]

tensor(12.5528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2801, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5417, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2999, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [02:56<00:19,  8.23it/s]

tensor(12.5291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3214, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3357, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [02:57<00:19,  8.20it/s]

tensor(12.5027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3575, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3780, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [02:57<00:19,  8.20it/s]

tensor(12.4789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3985, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4147, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [02:57<00:18,  8.21it/s]

tensor(12.4568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4337, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4546, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [02:57<00:18,  8.19it/s]

tensor(12.4389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4749, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4963, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [02:58<00:18,  8.20it/s]

tensor(12.4214, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5092, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5278, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [02:58<00:18,  8.22it/s]

tensor(12.4050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5456, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([256,  70, 115, 118, 204, 106, 236, 224, 167, 134, 194,  76,  71, 158])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<01:48, 19.66it/s]
  0%|          | 5/2129 [00:00<01:32, 22.89it/s]
  1%|          | 11/2129 [00:00<00:55, 38.40it/s]
  1%|          | 17/2129 [00:00<00:48, 43.55it/s]
  1%|          | 22/2129 [00:00<01:14, 28.16it/s]
  1%|▏         | 28/2129 [00:00<01:00, 34.52it/s]
  2%|▏         | 34/2129 [00:00<00:51, 40.60it/s]
  2%|▏         | 42/2129 [00:01<00:42, 49.68it/s]
  2%|▏         | 49/2129 [00:01<00:37, 54.76it/s]
  3%|▎         | 56/2129 [00:01<00:35, 58.25it/s]
  3%|▎         | 63/2129 [00:01<00:37, 54.81it/s]
  3%|▎         | 69/2129 [00:01<00:38, 53.31it/s]
  4%|▎         | 75/2129 [00:01<00:38, 53.18it/s]
  4%|▍         | 81/2129 [00:01<00:40, 50.67it/s]
  4%|▍         | 89/2129 [00:01<00:35, 57.76it/s]
  5%|▍         | 96/2129 [00:01<00:33, 60.15it/s]
  5%|▍         | 104/2129 [00:02<00:32, 62.54it/s]
  5%|▌         | 111/2129 [00:02<00:32, 61.29it/s]
  6%|▌         | 118/2129 [00:02<00:32, 61.81it/s]
  6%|▌         | 125/2129 [00:02<00:33, 60.42it/s]
  6%|▌         | 133/2129 [00:02<00:32, 62.25it/s]
  7%|▋         | 141/2129 [00:02<00:30, 65.52it/s]
  7%|▋         | 148/2129 [00:02<00:33, 59.26it/s]
  7%|▋         | 157/2129 [00:02<00:29, 65.75it/s]
  8%|▊         | 164/2129 [00:03<00:30, 63.62it/s]
  8%|▊         | 171/2129 [00:03<00:30, 64.35it/s]
  8%|▊         | 179/2129 [00:03<00:29, 67.15it/s]
  9%|▊         | 186/2129 [00:03<00:29, 65.18it/s]
  9%|▉         | 193/2129 [00:03<00:29, 65.93it/s]
  9%|▉         | 200/2129 [00:03<00:35, 54.41it/s]
 10%|▉         | 206/2129 [00:03<00:38, 50.05it/s]
 10%|▉         | 212/2129 [00:03<00:43, 43.92it/s]
 10%|█         | 219/2129 [00:04<00:39, 48.91it/s]
 11%|█         | 225/2129 [00:04<00:58, 32.73it/s]
 11%|█         | 232/2129 [00:04<00:49, 38.44it/s]
 11%|█         | 237/2129 [00:04<01:10, 26.97it/s]
 12%|█▏        | 245/2129 [00:05<00:53, 35.33it/s]
 12%|█▏        | 251/2129 [00:05<01:04, 29.03it/s]
 12%|█▏        | 256/2129 [00:05<01:00, 30.81it/s]
 12%|█▏        | 261/2129 [00:06<01:41, 18.47it/s]
 12%|█▏        | 265/2129 [00:06<01:28, 21.08it/s]
 13%|█▎        | 272/2129 [00:06<01:06, 27.86it/s]
 13%|█▎        | 277/2129 [00:06<01:05, 28.45it/s]
 13%|█▎        | 285/2129 [00:06<00:49, 37.08it/s]
 14%|█▎        | 291/2129 [00:06<00:45, 40.57it/s]
 14%|█▍        | 297/2129 [00:06<00:41, 44.68it/s]
 14%|█▍        | 304/2129 [00:06<00:36, 49.64it/s]
 15%|█▍        | 310/2129 [00:07<00:47, 38.57it/s]
 15%|█▍        | 315/2129 [00:07<01:09, 26.23it/s]
 15%|█▍        | 319/2129 [00:07<01:14, 24.22it/s]
 15%|█▌        | 325/2129 [00:07<01:03, 28.57it/s]
 15%|█▌        | 329/2129 [00:07<01:01, 29.21it/s]
 16%|█▌        | 334/2129 [00:08<01:13, 24.43it/s]
 16%|█▌        | 337/2129 [00:08<01:25, 21.02it/s]
 16%|█▌        | 343/2129 [00:08<01:27, 20.41it/s]
 16%|█▋        | 346/2129 [00:08<01:26, 20.64it/s]
 16%|█▋        | 349/2129 [00:09<01:36, 18.54it/s]
 16%|█▋        | 351/2129 [00:09<01:37, 18.25it/s]
 17%|█▋        | 358/2129 [00:09<01:04, 27.39it/s]
 17%|█▋        | 362/2129 [00:09<01:51, 15.83it/s]
 17%|█▋        | 365/2129 [00:09<01:44, 16.82it/s]
 17%|█▋        | 371/2129 [00:10<01:20, 21.75it/s]
 18%|█▊        | 374/2129 [00:10<01:36, 18.11it/s]
 18%|█▊        | 377/2129 [00:10<01:42, 17.07it/s]
 18%|█▊        | 380/2129 [00:10<02:02, 14.24it/s]
 18%|█▊        | 382/2129 [00:11<01:58, 14.69it/s]
 18%|█▊        | 384/2129 [00:11<01:59, 14.66it/s]
 18%|█▊        | 386/2129 [00:11<01:53, 15.31it/s]
 18%|█▊        | 388/2129 [00:11<01:47, 16.15it/s]
 18%|█▊        | 393/2129 [00:11<01:14, 23.27it/s]
 19%|█▊        | 398/2129 [00:11<01:00, 28.76it/s]
 19%|█▉        | 404/2129 [00:11<00:47, 36.24it/s]
 19%|█▉        | 411/2129 [00:11<00:39, 43.22it/s]
 20%|█▉        | 419/2129 [00:11<00:32, 52.35it/s]
 20%|█▉        | 425/2129 [00:12<00:34, 49.62it/s]
 20%|██        | 431/2129 [00:12<00:40, 41.96it/s]
 20%|██        | 436/2129 [00:12<01:03, 26.78it/s]
 21%|██        | 440/2129 [00:13<01:24, 19.96it/s]
 21%|██        | 443/2129 [00:13<01:27, 19.38it/s]
 21%|██        | 448/2129 [00:13<01:10, 23.83it/s]
 21%|██        | 452/2129 [00:13<01:03, 26.39it/s]
 21%|██▏       | 456/2129 [00:13<00:59, 28.23it/s]
 22%|██▏       | 460/2129 [00:13<01:01, 27.08it/s]
 22%|██▏       | 467/2129 [00:13<00:46, 35.49it/s]
 22%|██▏       | 472/2129 [00:14<01:14, 22.21it/s]
 22%|██▏       | 476/2129 [00:14<01:08, 24.28it/s]
 23%|██▎       | 483/2129 [00:14<00:52, 31.42it/s]
 23%|██▎       | 488/2129 [00:14<01:08, 23.92it/s]
 23%|██▎       | 492/2129 [00:15<01:13, 22.33it/s]
 23%|██▎       | 498/2129 [00:15<00:57, 28.43it/s]
 24%|██▎       | 502/2129 [00:15<00:59, 27.35it/s]
 24%|██▍       | 506/2129 [00:15<00:56, 28.75it/s]
 24%|██▍       | 510/2129 [00:15<01:09, 23.34it/s]
 24%|██▍       | 514/2129 [00:15<01:01, 26.39it/s]
 24%|██▍       | 518/2129 [00:16<01:36, 16.66it/s]
 24%|██▍       | 521/2129 [00:16<01:28, 18.21it/s]
 25%|██▍       | 524/2129 [00:16<01:42, 15.69it/s]
 25%|██▍       | 529/2129 [00:16<01:17, 20.75it/s]
 25%|██▍       | 532/2129 [00:16<01:31, 17.40it/s]
 25%|██▌       | 535/2129 [00:17<01:46, 14.96it/s]
 25%|██▌       | 538/2129 [00:17<01:32, 17.19it/s]
 26%|██▌       | 546/2129 [00:17<00:56, 28.00it/s]
 26%|██▌       | 550/2129 [00:17<01:20, 19.53it/s]
 26%|██▌       | 557/2129 [00:18<01:12, 21.67it/s]
 26%|██▋       | 560/2129 [00:18<01:15, 20.77it/s]
 26%|██▋       | 563/2129 [00:18<01:15, 20.75it/s]
 27%|██▋       | 566/2129 [00:18<01:20, 19.32it/s]
 27%|██▋       | 569/2129 [00:18<01:36, 16.16it/s]
 27%|██▋       | 574/2129 [00:18<01:11, 21.68it/s]
 27%|██▋       | 577/2129 [00:19<01:11, 21.59it/s]
 27%|██▋       | 580/2129 [00:19<01:16, 20.15it/s]
 27%|██▋       | 583/2129 [00:19<01:42, 15.03it/s]
 28%|██▊       | 589/2129 [00:19<01:10, 21.89it/s]
 28%|██▊       | 594/2129 [00:19<00:56, 26.99it/s]
 28%|██▊       | 599/2129 [00:19<00:49, 30.99it/s]
 28%|██▊       | 606/2129 [00:20<00:38, 39.72it/s]
 29%|██▊       | 612/2129 [00:20<00:38, 39.50it/s]
 29%|██▉       | 617/2129 [00:20<00:40, 37.01it/s]
 29%|██▉       | 622/2129 [00:20<00:43, 34.86it/s]
 30%|██▉       | 630/2129 [00:20<00:33, 44.30it/s]
 30%|██▉       | 636/2129 [00:20<00:31, 47.36it/s]
 30%|███       | 642/2129 [00:20<00:31, 47.28it/s]
 30%|███       | 648/2129 [00:21<00:31, 47.05it/s]
 31%|███       | 653/2129 [00:21<00:45, 32.50it/s]
 31%|███       | 657/2129 [00:21<00:47, 30.69it/s]
 31%|███       | 663/2129 [00:21<00:52, 27.99it/s]
 31%|███▏      | 667/2129 [00:21<00:54, 26.81it/s]
 32%|███▏      | 673/2129 [00:21<00:45, 32.12it/s]
 32%|███▏      | 677/2129 [00:22<00:43, 33.12it/s]
 32%|███▏      | 681/2129 [00:22<00:41, 34.59it/s]
 32%|███▏      | 686/2129 [00:22<00:38, 37.51it/s]
 32%|███▏      | 690/2129 [00:22<01:04, 22.46it/s]
 33%|███▎      | 694/2129 [00:22<00:59, 24.25it/s]
 33%|███▎      | 698/2129 [00:23<01:05, 21.98it/s]
 33%|███▎      | 703/2129 [00:23<01:09, 20.42it/s]
 33%|███▎      | 706/2129 [00:23<01:19, 17.92it/s]
 33%|███▎      | 709/2129 [00:23<01:28, 16.09it/s]
 33%|███▎      | 711/2129 [00:23<01:28, 15.98it/s]
 33%|███▎      | 713/2129 [00:24<01:44, 13.56it/s]
 34%|███▎      | 715/2129 [00:24<01:40, 14.06it/s]
 34%|███▍      | 721/2129 [00:24<01:18, 17.96it/s]
 34%|███▍      | 723/2129 [00:24<01:22, 17.13it/s]
 34%|███▍      | 725/2129 [00:24<01:27, 16.11it/s]
 34%|███▍      | 727/2129 [00:24<01:25, 16.41it/s]
 34%|███▍      | 730/2129 [00:25<01:16, 18.41it/s]
 34%|███▍      | 733/2129 [00:25<01:23, 16.73it/s]
 35%|███▍      | 735/2129 [00:25<01:21, 17.08it/s]
 35%|███▍      | 739/2129 [00:25<01:15, 18.38it/s]
 35%|███▍      | 741/2129 [00:25<01:14, 18.63it/s]
 35%|███▌      | 748/2129 [00:25<00:47, 29.38it/s]
 35%|███▌      | 752/2129 [00:25<00:51, 26.81it/s]
 35%|███▌      | 755/2129 [00:26<01:15, 18.27it/s]
 36%|███▌      | 758/2129 [00:26<01:14, 18.31it/s]
 36%|███▌      | 762/2129 [00:26<01:04, 21.20it/s]
 36%|███▌      | 766/2129 [00:26<00:58, 23.20it/s]
 36%|███▌      | 769/2129 [00:26<01:09, 19.70it/s]
 36%|███▋      | 774/2129 [00:27<00:55, 24.21it/s]
 36%|███▋      | 777/2129 [00:27<00:58, 23.10it/s]
 37%|███▋      | 783/2129 [00:27<00:43, 30.91it/s]
 37%|███▋      | 787/2129 [00:27<00:54, 24.55it/s]
 37%|███▋      | 792/2129 [00:27<00:45, 29.12it/s]
 37%|███▋      | 796/2129 [00:28<01:11, 18.74it/s]
 38%|███▊      | 799/2129 [00:28<01:21, 16.27it/s]
 38%|███▊      | 803/2129 [00:28<01:07, 19.52it/s]
 38%|███▊      | 809/2129 [00:28<00:49, 26.47it/s]
 38%|███▊      | 816/2129 [00:28<00:38, 34.36it/s]
 39%|███▊      | 821/2129 [00:29<01:06, 19.53it/s]
 39%|███▉      | 825/2129 [00:29<00:59, 21.94it/s]
 39%|███▉      | 831/2129 [00:29<00:46, 27.75it/s]
 39%|███▉      | 836/2129 [00:29<00:41, 30.85it/s]
 40%|███▉      | 841/2129 [00:29<00:42, 30.00it/s]
 40%|███▉      | 845/2129 [00:30<01:04, 19.88it/s]
 40%|███▉      | 848/2129 [00:30<01:01, 20.81it/s]
 40%|████      | 855/2129 [00:30<00:44, 28.72it/s]
 40%|████      | 860/2129 [00:30<00:39, 32.12it/s]
 41%|████      | 865/2129 [00:30<00:36, 34.41it/s]
 41%|████      | 870/2129 [00:30<00:53, 23.74it/s]
 41%|████      | 876/2129 [00:31<00:42, 29.55it/s]
 41%|████▏     | 880/2129 [00:31<00:40, 30.56it/s]
 42%|████▏     | 886/2129 [00:31<00:40, 30.95it/s]
 42%|████▏     | 890/2129 [00:31<00:51, 23.97it/s]
 42%|████▏     | 893/2129 [00:31<00:57, 21.53it/s]
 42%|████▏     | 896/2129 [00:32<01:05, 18.96it/s]
 42%|████▏     | 899/2129 [00:32<01:05, 18.90it/s]
 43%|████▎     | 905/2129 [00:32<00:46, 26.20it/s]
 43%|████▎     | 909/2129 [00:32<01:05, 18.50it/s]
 43%|████▎     | 912/2129 [00:33<01:18, 15.58it/s]
 43%|████▎     | 915/2129 [00:33<01:29, 13.62it/s]
 43%|████▎     | 918/2129 [00:33<01:16, 15.81it/s]
 43%|████▎     | 925/2129 [00:33<00:49, 24.42it/s]
 44%|████▎     | 929/2129 [00:34<01:15, 15.90it/s]
 44%|████▍     | 932/2129 [00:34<01:24, 14.18it/s]
 44%|████▍     | 936/2129 [00:34<01:25, 13.92it/s]
 44%|████▍     | 938/2129 [00:34<01:36, 12.28it/s]
 44%|████▍     | 942/2129 [00:34<01:15, 15.81it/s]
 44%|████▍     | 945/2129 [00:35<01:20, 14.75it/s]
 45%|████▍     | 948/2129 [00:35<01:11, 16.43it/s]
 45%|████▍     | 951/2129 [00:35<01:14, 15.85it/s]
 45%|████▍     | 953/2129 [00:35<01:14, 15.80it/s]
 45%|████▍     | 956/2129 [00:35<01:06, 17.62it/s]
 45%|████▌     | 963/2129 [00:35<00:41, 28.42it/s]
 45%|████▌     | 968/2129 [00:36<00:50, 23.21it/s]
 46%|████▌     | 971/2129 [00:36<01:04, 18.09it/s]
 46%|████▌     | 974/2129 [00:36<00:59, 19.31it/s]
 46%|████▌     | 981/2129 [00:36<00:41, 27.76it/s]
 46%|████▋     | 988/2129 [00:36<00:42, 26.89it/s]
 47%|████▋     | 992/2129 [00:37<00:42, 26.75it/s]
 47%|████▋     | 996/2129 [00:37<00:53, 21.12it/s]
 47%|████▋     | 1003/2129 [00:37<00:39, 28.58it/s]
 47%|████▋     | 1010/2129 [00:37<00:40, 27.33it/s]
 48%|████▊     | 1014/2129 [00:38<01:04, 17.23it/s]
 48%|████▊     | 1017/2129 [00:38<01:04, 17.34it/s]
 48%|████▊     | 1020/2129 [00:38<01:13, 15.12it/s]
 48%|████▊     | 1023/2129 [00:39<01:19, 13.86it/s]
 48%|████▊     | 1026/2129 [00:39<01:14, 14.74it/s]
 48%|████▊     | 1028/2129 [00:39<01:13, 15.05it/s]
 48%|████▊     | 1031/2129 [00:39<01:08, 16.09it/s]
 49%|████▊     | 1036/2129 [00:39<00:49, 22.16it/s]
 49%|████▉     | 1042/2129 [00:39<00:36, 29.68it/s]
 49%|████▉     | 1048/2129 [00:39<00:35, 30.82it/s]
 49%|████▉     | 1052/2129 [00:40<00:43, 24.85it/s]
 50%|████▉     | 1056/2129 [00:40<00:41, 26.07it/s]
 50%|████▉     | 1059/2129 [00:40<00:42, 25.40it/s]
 50%|████▉     | 1062/2129 [00:40<00:55, 19.06it/s]
 50%|█████     | 1069/2129 [00:40<00:38, 27.74it/s]
 50%|█████     | 1073/2129 [00:41<00:48, 21.87it/s]
 51%|█████     | 1078/2129 [00:41<00:39, 26.63it/s]
 51%|█████     | 1082/2129 [00:41<00:50, 20.56it/s]
 51%|█████     | 1085/2129 [00:41<00:59, 17.67it/s]
 51%|█████     | 1088/2129 [00:41<00:55, 18.65it/s]
 51%|█████▏    | 1094/2129 [00:42<00:53, 19.22it/s]
 52%|█████▏    | 1097/2129 [00:42<00:49, 20.79it/s]
 52%|█████▏    | 1104/2129 [00:42<00:35, 29.23it/s]
 52%|█████▏    | 1108/2129 [00:42<00:45, 22.44it/s]
 52%|█████▏    | 1112/2129 [00:42<00:51, 19.92it/s]
 52%|█████▏    | 1115/2129 [00:43<00:51, 19.86it/s]
 53%|█████▎    | 1120/2129 [00:43<00:51, 19.60it/s]
 53%|█████▎    | 1123/2129 [00:43<00:49, 20.14it/s]
 53%|█████▎    | 1127/2129 [00:43<00:46, 21.36it/s]
 53%|█████▎    | 1133/2129 [00:43<00:47, 20.91it/s]
 53%|█████▎    | 1136/2129 [00:44<00:45, 21.63it/s]
 53%|█████▎    | 1139/2129 [00:44<01:07, 14.71it/s]
 54%|█████▎    | 1141/2129 [00:44<01:05, 15.16it/s]
 54%|█████▎    | 1143/2129 [00:44<01:16, 12.86it/s]
 54%|█████▍    | 1146/2129 [00:45<01:22, 11.86it/s]
 54%|█████▍    | 1149/2129 [00:45<01:08, 14.29it/s]
 54%|█████▍    | 1155/2129 [00:45<00:56, 17.19it/s]
 54%|█████▍    | 1157/2129 [00:45<00:55, 17.39it/s]
 55%|█████▍    | 1164/2129 [00:45<00:36, 26.67it/s]
 55%|█████▍    | 1169/2129 [00:46<00:40, 23.82it/s]
 55%|█████▌    | 1172/2129 [00:46<00:40, 23.52it/s]
 55%|█████▌    | 1177/2129 [00:46<00:43, 22.01it/s]
 55%|█████▌    | 1180/2129 [00:46<00:44, 21.14it/s]
 56%|█████▌    | 1184/2129 [00:46<00:38, 24.43it/s]
 56%|█████▌    | 1187/2129 [00:46<00:45, 20.50it/s]
 56%|█████▌    | 1190/2129 [00:47<00:53, 17.56it/s]
 56%|█████▌    | 1193/2129 [00:47<00:54, 17.10it/s]
 56%|█████▌    | 1195/2129 [00:47<01:11, 13.06it/s]
 56%|█████▋    | 1198/2129 [00:47<01:00, 15.36it/s]
 57%|█████▋    | 1205/2129 [00:47<00:36, 25.07it/s]
 57%|█████▋    | 1209/2129 [00:48<00:47, 19.28it/s]
 57%|█████▋    | 1212/2129 [00:48<00:53, 17.29it/s]
 57%|█████▋    | 1215/2129 [00:48<00:56, 16.20it/s]
 57%|█████▋    | 1218/2129 [00:48<00:50, 17.95it/s]
 57%|█████▋    | 1221/2129 [00:49<01:14, 12.19it/s]
 57%|█████▋    | 1223/2129 [00:49<01:13, 12.33it/s]
 58%|█████▊    | 1225/2129 [00:49<01:16, 11.88it/s]
 58%|█████▊    | 1227/2129 [00:49<01:17, 11.58it/s]
 58%|█████▊    | 1230/2129 [00:49<01:03, 14.23it/s]
 58%|█████▊    | 1232/2129 [00:50<01:05, 13.63it/s]
 58%|█████▊    | 1234/2129 [00:50<01:00, 14.85it/s]
 58%|█████▊    | 1236/2129 [00:50<01:08, 12.95it/s]
 58%|█████▊    | 1238/2129 [00:50<01:10, 12.66it/s]
 58%|█████▊    | 1243/2129 [00:50<00:44, 19.89it/s]
 59%|█████▊    | 1246/2129 [00:50<00:41, 21.23it/s]
 59%|█████▊    | 1249/2129 [00:50<00:40, 21.97it/s]
 59%|█████▉    | 1254/2129 [00:50<00:31, 27.79it/s]
 59%|█████▉    | 1258/2129 [00:51<00:46, 18.80it/s]
 59%|█████▉    | 1261/2129 [00:51<00:55, 15.64it/s]
 59%|█████▉    | 1264/2129 [00:51<01:00, 14.27it/s]
 60%|█████▉    | 1268/2129 [00:51<00:48, 17.76it/s]
 60%|█████▉    | 1274/2129 [00:52<00:42, 19.89it/s]
 60%|█████▉    | 1277/2129 [00:52<00:54, 15.64it/s]
 60%|██████    | 1279/2129 [00:52<01:09, 12.15it/s]
 60%|██████    | 1282/2129 [00:52<00:59, 14.26it/s]
 60%|██████    | 1284/2129 [00:53<01:03, 13.25it/s]
 60%|██████    | 1286/2129 [00:53<01:00, 14.00it/s]
 60%|██████    | 1288/2129 [00:53<00:55, 15.07it/s]
 61%|██████    | 1290/2129 [00:53<00:52, 16.04it/s]
 61%|██████    | 1292/2129 [00:53<01:01, 13.66it/s]
 61%|██████    | 1295/2129 [00:53<00:48, 17.06it/s]
 61%|██████    | 1298/2129 [00:54<00:56, 14.60it/s]
 61%|██████    | 1300/2129 [00:54<01:04, 12.77it/s]
 61%|██████    | 1302/2129 [00:54<01:15, 11.01it/s]
 61%|██████    | 1304/2129 [00:54<01:36,  8.52it/s]
 61%|██████▏   | 1307/2129 [00:55<01:17, 10.63it/s]
 61%|██████▏   | 1309/2129 [00:55<01:08, 12.06it/s]
 62%|██████▏   | 1311/2129 [00:55<01:13, 11.20it/s]
 62%|██████▏   | 1314/2129 [00:55<01:03, 12.92it/s]
 62%|██████▏   | 1316/2129 [00:55<01:03, 12.90it/s]
 62%|██████▏   | 1318/2129 [00:55<01:05, 12.40it/s]
 62%|██████▏   | 1320/2129 [00:56<00:59, 13.63it/s]
 62%|██████▏   | 1322/2129 [00:56<01:05, 12.31it/s]
 62%|██████▏   | 1324/2129 [00:56<00:59, 13.57it/s]
 62%|██████▏   | 1326/2129 [00:56<00:54, 14.74it/s]
 62%|██████▏   | 1328/2129 [00:56<00:59, 13.54it/s]
 62%|██████▏   | 1330/2129 [00:56<00:54, 14.71it/s]
 63%|██████▎   | 1336/2129 [00:56<00:31, 25.19it/s]
 63%|██████▎   | 1342/2129 [00:57<00:32, 24.31it/s]
 63%|██████▎   | 1346/2129 [00:57<00:30, 25.78it/s]
 63%|██████▎   | 1350/2129 [00:57<00:34, 22.51it/s]
 64%|██████▎   | 1353/2129 [00:57<00:32, 23.65it/s]
 64%|██████▍   | 1359/2129 [00:57<00:33, 22.94it/s]
 64%|██████▍   | 1363/2129 [00:57<00:30, 25.03it/s]
 64%|██████▍   | 1370/2129 [00:58<00:31, 24.45it/s]
 64%|██████▍   | 1373/2129 [00:58<00:31, 24.18it/s]
 65%|██████▍   | 1380/2129 [00:58<00:22, 32.76it/s]
 65%|██████▌   | 1384/2129 [00:58<00:28, 26.02it/s]
 65%|██████▌   | 1388/2129 [00:58<00:27, 26.50it/s]
 65%|██████▌   | 1392/2129 [00:59<00:44, 16.62it/s]
 66%|██████▌   | 1395/2129 [00:59<00:58, 12.47it/s]
 66%|██████▌   | 1398/2129 [00:59<00:52, 13.82it/s]
 66%|██████▌   | 1401/2129 [01:00<00:54, 13.43it/s]
 66%|██████▌   | 1404/2129 [01:00<00:46, 15.53it/s]
 66%|██████▌   | 1407/2129 [01:00<00:53, 13.39it/s]
 66%|██████▋   | 1411/2129 [01:00<00:45, 15.67it/s]
 66%|██████▋   | 1413/2129 [01:01<00:54, 13.12it/s]
 66%|██████▋   | 1415/2129 [01:01<00:52, 13.60it/s]
 67%|██████▋   | 1419/2129 [01:01<00:40, 17.46it/s]
 67%|██████▋   | 1422/2129 [01:01<00:50, 13.98it/s]
 67%|██████▋   | 1427/2129 [01:01<00:35, 19.52it/s]
 67%|██████▋   | 1431/2129 [01:01<00:30, 22.64it/s]
 67%|██████▋   | 1434/2129 [01:01<00:30, 22.73it/s]
 67%|██████▋   | 1437/2129 [01:02<00:37, 18.21it/s]
 68%|██████▊   | 1440/2129 [01:02<00:43, 15.86it/s]
 68%|██████▊   | 1442/2129 [01:02<00:56, 12.20it/s]
 68%|██████▊   | 1444/2129 [01:02<00:51, 13.20it/s]
 68%|██████▊   | 1451/2129 [01:03<00:38, 17.79it/s]
 68%|██████▊   | 1453/2129 [01:03<00:45, 14.85it/s]
 68%|██████▊   | 1456/2129 [01:03<00:39, 17.15it/s]
 68%|██████▊   | 1458/2129 [01:03<00:48, 13.84it/s]
 69%|██████▊   | 1462/2129 [01:03<00:37, 17.93it/s]
 69%|██████▉   | 1465/2129 [01:04<00:41, 15.89it/s]
 69%|██████▉   | 1468/2129 [01:04<00:37, 17.53it/s]
 69%|██████▉   | 1471/2129 [01:04<00:42, 15.46it/s]
 69%|██████▉   | 1475/2129 [01:04<00:33, 19.50it/s]
 70%|██████▉   | 1482/2129 [01:04<00:32, 20.09it/s]
 70%|██████▉   | 1485/2129 [01:05<00:31, 20.75it/s]
 70%|██████▉   | 1488/2129 [01:05<00:31, 20.17it/s]
 70%|███████   | 1492/2129 [01:05<00:28, 22.20it/s]
 70%|███████   | 1495/2129 [01:05<00:38, 16.48it/s]
 70%|███████   | 1497/2129 [01:05<00:38, 16.46it/s]
 70%|███████   | 1499/2129 [01:05<00:37, 16.73it/s]
 71%|███████   | 1501/2129 [01:06<00:36, 17.14it/s]
 71%|███████   | 1504/2129 [01:06<00:35, 17.63it/s]
 71%|███████   | 1506/2129 [01:06<00:34, 17.95it/s]
 71%|███████   | 1508/2129 [01:06<00:58, 10.61it/s]
 71%|███████   | 1511/2129 [01:06<00:45, 13.62it/s]
 71%|███████   | 1515/2129 [01:07<00:42, 14.30it/s]
 71%|███████▏  | 1517/2129 [01:07<00:42, 14.57it/s]
 72%|███████▏  | 1523/2129 [01:07<00:26, 22.64it/s]
 72%|███████▏  | 1526/2129 [01:07<00:31, 19.44it/s]
 72%|███████▏  | 1529/2129 [01:07<00:39, 15.32it/s]
 72%|███████▏  | 1531/2129 [01:08<00:45, 13.18it/s]
 72%|███████▏  | 1533/2129 [01:08<00:52, 11.33it/s]
 72%|███████▏  | 1537/2129 [01:08<00:39, 15.02it/s]
 72%|███████▏  | 1539/2129 [01:08<00:44, 13.14it/s]
 72%|███████▏  | 1541/2129 [01:08<00:51, 11.39it/s]
 72%|███████▏  | 1543/2129 [01:09<01:08,  8.55it/s]
 73%|███████▎  | 1545/2129 [01:09<01:10,  8.33it/s]
 73%|███████▎  | 1548/2129 [01:09<00:52, 10.98it/s]
 73%|███████▎  | 1550/2129 [01:09<00:54, 10.63it/s]
 73%|███████▎  | 1552/2129 [01:10<00:49, 11.68it/s]
 73%|███████▎  | 1557/2129 [01:10<00:39, 14.33it/s]
 73%|███████▎  | 1559/2129 [01:10<00:48, 11.67it/s]
 73%|███████▎  | 1561/2129 [01:10<00:44, 12.66it/s]
 73%|███████▎  | 1563/2129 [01:10<00:45, 12.38it/s]
 74%|███████▎  | 1565/2129 [01:10<00:41, 13.48it/s]
 74%|███████▍  | 1571/2129 [01:11<00:24, 22.65it/s]
 74%|███████▍  | 1578/2129 [01:11<00:24, 22.10it/s]
 74%|███████▍  | 1581/2129 [01:11<00:24, 22.31it/s]
 74%|███████▍  | 1584/2129 [01:11<00:31, 17.44it/s]
 75%|███████▍  | 1587/2129 [01:12<00:35, 15.26it/s]
 75%|███████▍  | 1590/2129 [01:12<00:39, 13.61it/s]
 75%|███████▍  | 1593/2129 [01:12<00:33, 15.89it/s]
 75%|███████▍  | 1596/2129 [01:12<00:35, 15.05it/s]
 75%|███████▌  | 1599/2129 [01:12<00:38, 13.92it/s]
 75%|███████▌  | 1601/2129 [01:13<00:44, 11.88it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 311.82it/s]

[[np.int64(0), False, 6], [np.int64(1), False, 13], [np.int64(2), False, 4], [np.int64(3), False, 8], [np.int64(5), False, 8], [np.int64(7), False, 10], [np.int64(9), False, 7], [np.int64(11), False, 5], [np.int64(12), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0500, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [04:41<1:17:02, 31.02s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.3903, device='cuda:0', grad_fn=<AddBackward0>)

 51%|█████     | 152/300 [04:41<53:41, 21.76s/it]

tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2227, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3900, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5142, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [04:41<18:13,  7.54s/it]

tensor(12.3959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7355, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8784, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [04:42<08:57,  3.76s/it]

tensor(12.4068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9807, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [04:42<04:28,  1.90s/it]

tensor(12.3998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0218, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3932, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0511, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [04:42<03:11,  1.37s/it]

tensor(12.3851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0737, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1041, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [04:42<01:15,  1.82it/s]

tensor(12.3641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0373, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3527, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1561, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [04:43<00:44,  3.02it/s]

tensor(12.3425, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1862, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2096, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [04:43<00:35,  3.73it/s]

tensor(12.3256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2572, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [04:43<00:22,  5.82it/s]

tensor(12.3133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2833, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2987, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [04:43<00:20,  6.37it/s]

tensor(12.3047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3184, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3288, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [04:44<00:17,  7.46it/s]

tensor(12.2936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3462, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [04:44<00:15,  7.84it/s]

tensor(12.2795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3653, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [04:44<00:15,  8.04it/s]

tensor(12.2650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3760, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2575, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3798, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [04:44<00:15,  7.97it/s]

tensor(12.2503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3947, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4066, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [04:45<00:14,  8.15it/s]

tensor(12.2378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4149, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4355, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [04:45<00:14,  8.22it/s]

tensor(12.2275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4429, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4512, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [04:45<00:14,  8.21it/s]

tensor(12.2179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4544, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4602, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [04:45<00:14,  8.08it/s]

tensor(12.2078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2031, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4690, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [04:46<00:13,  8.24it/s]

tensor(12.1985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4673, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4731, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [04:46<00:13,  8.24it/s]

tensor(12.1902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4777, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4793, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [04:46<00:12,  8.24it/s]

tensor(12.1820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4813, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4840, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [04:46<00:12,  8.25it/s]

tensor(12.1739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4872, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4915, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [04:46<00:12,  8.23it/s]

tensor(12.1664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4973, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4956, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [04:47<00:12,  8.27it/s]

tensor(12.1598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4997, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5015, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [04:47<00:12,  8.27it/s]

tensor(12.1535, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5007, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([142, 142, 115, 120,  76, 149, 176, 223, 201, 137, 285,  90, 152, 121])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 2/2129 [00:00<02:13, 15.99it/s]
  0%|          | 10/2129 [00:00<00:45, 46.70it/s]
  1%|          | 15/2129 [00:00<00:46, 45.18it/s]
  1%|          | 20/2129 [00:00<00:48, 43.07it/s]
  1%|          | 25/2129 [00:00<00:49, 42.26it/s]
  1%|▏         | 31/2129 [00:00<00:46, 45.06it/s]
  2%|▏         | 38/2129 [00:00<00:44, 46.50it/s]
  2%|▏         | 43/2129 [00:00<00:45, 45.38it/s]
  2%|▏         | 50/2129 [00:01<00:41, 50.23it/s]
  3%|▎         | 57/2129 [00:01<00:38, 54.24it/s]
  3%|▎         | 64/2129 [00:01<00:35, 57.45it/s]
  3%|▎         | 70/2129 [00:01<00:36, 56.26it/s]
  4%|▎         | 76/2129 [00:01<00:36, 57.00it/s]
  4%|▍         | 82/2129 [00:01<00:38, 53.37it/s]
  4%|▍         | 88/2129 [00:01<00:39, 51.24it/s]
  4%|▍         | 95/2129 [00:01<00:36, 55.41it/s]
  5%|▍         | 101/2129 [00:02<00:46, 43.90it/s]
  5%|▌         | 107/2129 [00:02<00:45, 44.58it/s]
  5%|▌         | 114/2129 [00:02<00:40, 49.56it/s]
  6%|▌         | 120/2129 [00:02<00:40, 49.74it/s]
  6%|▌         | 126/2129 [00:02<00:42, 46.62it/s]
  6%|▌         | 133/2129 [00:02<00:39, 51.01it/s]
  7%|▋         | 139/2129 [00:02<00:43, 45.30it/s]
  7%|▋         | 146/2129 [00:02<00:39, 49.73it/s]
  7%|▋         | 152/2129 [00:03<00:38, 51.82it/s]
  7%|▋         | 158/2129 [00:03<00:55, 35.61it/s]
  8%|▊         | 163/2129 [00:03<00:56, 34.87it/s]
  8%|▊         | 170/2129 [00:03<00:47, 41.08it/s]
  8%|▊         | 175/2129 [00:03<00:46, 42.39it/s]
  9%|▊         | 182/2129 [00:03<00:41, 47.26it/s]
  9%|▉         | 188/2129 [00:04<01:04, 29.97it/s]
  9%|▉         | 195/2129 [00:04<00:53, 36.06it/s]
  9%|▉         | 201/2129 [00:04<00:47, 40.29it/s]
 10%|▉         | 208/2129 [00:04<00:42, 45.09it/s]
 10%|█         | 214/2129 [00:04<00:40, 47.45it/s]
 10%|█         | 220/2129 [00:04<00:38, 49.44it/s]
 11%|█         | 226/2129 [00:05<01:00, 31.22it/s]
 11%|█         | 231/2129 [00:05<01:01, 31.07it/s]
 11%|█         | 235/2129 [00:05<01:21, 23.22it/s]
 11%|█         | 239/2129 [00:05<01:40, 18.84it/s]
 11%|█▏        | 242/2129 [00:06<01:39, 19.04it/s]
 12%|█▏        | 248/2129 [00:06<01:33, 20.04it/s]
 12%|█▏        | 251/2129 [00:06<01:52, 16.70it/s]
 12%|█▏        | 253/2129 [00:06<02:18, 13.56it/s]
 12%|█▏        | 256/2129 [00:07<01:59, 15.68it/s]
 12%|█▏        | 258/2129 [00:07<02:15, 13.79it/s]
 12%|█▏        | 260/2129 [00:07<02:11, 14.25it/s]
 12%|█▏        | 262/2129 [00:07<02:31, 12.33it/s]
 12%|█▏        | 264/2129 [00:07<02:19, 13.41it/s]
 13%|█▎        | 268/2129 [00:07<01:42, 18.17it/s]
 13%|█▎        | 274/2129 [00:08<01:08, 26.95it/s]
 13%|█▎        | 281/2129 [00:08<00:50, 36.24it/s]
 13%|█▎        | 287/2129 [00:08<01:09, 26.53it/s]
 14%|█▎        | 291/2129 [00:08<01:09, 26.63it/s]
 14%|█▍        | 295/2129 [00:08<01:32, 19.79it/s]
 14%|█▍        | 303/2129 [00:09<01:03, 28.86it/s]
 14%|█▍        | 308/2129 [00:09<01:19, 22.77it/s]
 15%|█▍        | 312/2129 [00:09<01:28, 20.46it/s]
 15%|█▍        | 315/2129 [00:09<01:47, 16.80it/s]
 15%|█▍        | 318/2129 [00:10<01:38, 18.43it/s]
 15%|█▌        | 324/2129 [00:10<01:29, 20.24it/s]
 15%|█▌        | 327/2129 [00:10<01:27, 20.68it/s]
 16%|█▌        | 330/2129 [00:10<01:27, 20.61it/s]
 16%|█▌        | 333/2129 [00:10<01:24, 21.22it/s]
 16%|█▌        | 336/2129 [00:10<01:37, 18.45it/s]
 16%|█▌        | 341/2129 [00:11<01:13, 24.26it/s]
 16%|█▌        | 344/2129 [00:11<01:23, 21.36it/s]
 16%|█▋        | 347/2129 [00:11<01:27, 20.29it/s]
 16%|█▋        | 350/2129 [00:11<01:55, 15.45it/s]
 17%|█▋        | 352/2129 [00:11<01:50, 16.13it/s]
 17%|█▋        | 355/2129 [00:12<02:00, 14.78it/s]
 17%|█▋        | 357/2129 [00:12<01:55, 15.39it/s]
 17%|█▋        | 361/2129 [00:12<01:53, 15.61it/s]
 17%|█▋        | 363/2129 [00:12<02:15, 13.06it/s]
 17%|█▋        | 366/2129 [00:12<01:50, 15.90it/s]
 18%|█▊        | 373/2129 [00:13<01:29, 19.71it/s]
 18%|█▊        | 376/2129 [00:13<01:28, 19.88it/s]
 18%|█▊        | 383/2129 [00:13<01:01, 28.27it/s]
 18%|█▊        | 389/2129 [00:13<00:50, 34.70it/s]
 19%|█▊        | 397/2129 [00:13<00:39, 43.65it/s]
 19%|█▉        | 404/2129 [00:13<00:35, 48.26it/s]
 19%|█▉        | 410/2129 [00:13<00:35, 48.52it/s]
 20%|█▉        | 416/2129 [00:13<00:37, 45.98it/s]
 20%|█▉        | 421/2129 [00:14<00:40, 41.87it/s]
 20%|██        | 427/2129 [00:14<00:37, 45.56it/s]
 20%|██        | 432/2129 [00:14<00:59, 28.67it/s]
 20%|██        | 436/2129 [00:15<01:36, 17.57it/s]
 21%|██        | 439/2129 [00:15<01:46, 15.84it/s]
 21%|██        | 442/2129 [00:15<01:45, 16.02it/s]
 21%|██        | 445/2129 [00:15<01:39, 16.84it/s]
 21%|██▏       | 453/2129 [00:15<01:02, 26.74it/s]
 21%|██▏       | 457/2129 [00:16<01:34, 17.67it/s]
 22%|██▏       | 460/2129 [00:16<01:47, 15.50it/s]
 22%|██▏       | 464/2129 [00:16<01:29, 18.53it/s]
 22%|██▏       | 468/2129 [00:16<01:31, 18.15it/s]
 22%|██▏       | 471/2129 [00:16<01:27, 19.02it/s]
 22%|██▏       | 477/2129 [00:17<01:24, 19.46it/s]
 23%|██▎       | 480/2129 [00:17<01:19, 20.79it/s]
 23%|██▎       | 484/2129 [00:17<01:33, 17.59it/s]
 23%|██▎       | 487/2129 [00:17<01:38, 16.62it/s]
 23%|██▎       | 493/2129 [00:17<01:10, 23.19it/s]
 23%|██▎       | 496/2129 [00:18<01:06, 24.41it/s]
 23%|██▎       | 499/2129 [00:18<01:04, 25.14it/s]
 24%|██▎       | 502/2129 [00:18<01:27, 18.66it/s]
 24%|██▍       | 506/2129 [00:18<01:11, 22.57it/s]
 24%|██▍       | 509/2129 [00:18<01:27, 18.57it/s]
 24%|██▍       | 512/2129 [00:18<01:19, 20.35it/s]
 24%|██▍       | 517/2129 [00:19<01:27, 18.36it/s]
 24%|██▍       | 520/2129 [00:19<01:43, 15.52it/s]
 25%|██▍       | 522/2129 [00:19<01:41, 15.88it/s]
 25%|██▍       | 526/2129 [00:19<01:44, 15.35it/s]
 25%|██▍       | 529/2129 [00:20<01:34, 16.92it/s]
 25%|██▍       | 531/2129 [00:20<01:55, 13.86it/s]
 25%|██▌       | 535/2129 [00:20<01:51, 14.25it/s]
 25%|██▌       | 537/2129 [00:20<01:46, 14.96it/s]
 26%|██▌       | 543/2129 [00:20<01:29, 17.66it/s]
 26%|██▌       | 546/2129 [00:21<01:21, 19.44it/s]
 26%|██▌       | 553/2129 [00:21<00:54, 28.80it/s]
 26%|██▌       | 557/2129 [00:21<01:06, 23.61it/s]
 26%|██▋       | 560/2129 [00:21<01:29, 17.55it/s]
 26%|██▋       | 564/2129 [00:21<01:32, 16.93it/s]
 27%|██▋       | 567/2129 [00:22<01:47, 14.51it/s]
 27%|██▋       | 570/2129 [00:22<01:36, 16.17it/s]
 27%|██▋       | 577/2129 [00:22<01:02, 24.98it/s]
 27%|██▋       | 581/2129 [00:22<01:17, 20.08it/s]
 27%|██▋       | 584/2129 [00:22<01:14, 20.78it/s]
 28%|██▊       | 589/2129 [00:23<01:17, 19.81it/s]
 28%|██▊       | 592/2129 [00:23<01:15, 20.43it/s]
 28%|██▊       | 598/2129 [00:23<00:56, 27.32it/s]
 28%|██▊       | 602/2129 [00:23<01:13, 20.68it/s]
 29%|██▊       | 608/2129 [00:23<00:56, 27.00it/s]
 29%|██▊       | 612/2129 [00:24<01:09, 21.68it/s]
 29%|██▉       | 616/2129 [00:24<01:01, 24.73it/s]
 29%|██▉       | 624/2129 [00:24<00:43, 34.48it/s]
 30%|██▉       | 629/2129 [00:24<01:05, 22.94it/s]
 30%|██▉       | 633/2129 [00:24<01:02, 23.80it/s]
 30%|███       | 640/2129 [00:25<00:48, 30.74it/s]
 30%|███       | 645/2129 [00:25<01:07, 21.89it/s]
 30%|███       | 649/2129 [00:25<01:14, 19.97it/s]
 31%|███       | 652/2129 [00:25<01:11, 20.52it/s]
 31%|███       | 655/2129 [00:26<01:36, 15.25it/s]
 31%|███       | 661/2129 [00:26<01:08, 21.30it/s]
 31%|███       | 665/2129 [00:26<01:42, 14.34it/s]
 31%|███▏      | 669/2129 [00:26<01:28, 16.52it/s]
 32%|███▏      | 672/2129 [00:27<01:19, 18.26it/s]
 32%|███▏      | 677/2129 [00:27<01:05, 22.19it/s]
 32%|███▏      | 681/2129 [00:27<00:57, 25.13it/s]
 32%|███▏      | 685/2129 [00:27<00:51, 27.80it/s]
 32%|███▏      | 689/2129 [00:27<01:25, 16.89it/s]
 33%|███▎      | 692/2129 [00:28<01:19, 18.13it/s]
 33%|███▎      | 695/2129 [00:28<01:37, 14.64it/s]
 33%|███▎      | 698/2129 [00:28<01:35, 14.96it/s]
 33%|███▎      | 704/2129 [00:28<01:06, 21.51it/s]
 33%|███▎      | 707/2129 [00:28<01:06, 21.38it/s]
 33%|███▎      | 710/2129 [00:29<01:37, 14.58it/s]
 33%|███▎      | 713/2129 [00:29<01:43, 13.68it/s]
 34%|███▎      | 715/2129 [00:29<01:40, 14.11it/s]
 34%|███▍      | 720/2129 [00:29<01:13, 19.13it/s]
 34%|███▍      | 723/2129 [00:30<01:42, 13.74it/s]
 34%|███▍      | 725/2129 [00:30<01:56, 12.05it/s]
 34%|███▍      | 727/2129 [00:30<01:48, 12.93it/s]
 34%|███▍      | 729/2129 [00:30<02:00, 11.57it/s]
 34%|███▍      | 731/2129 [00:30<01:53, 12.30it/s]
 34%|███▍      | 733/2129 [00:30<01:44, 13.39it/s]
 35%|███▍      | 735/2129 [00:31<01:35, 14.58it/s]
 35%|███▍      | 737/2129 [00:31<01:35, 14.57it/s]
 35%|███▍      | 739/2129 [00:31<01:50, 12.62it/s]
 35%|███▍      | 742/2129 [00:31<01:26, 16.03it/s]
 35%|███▌      | 748/2129 [00:31<00:58, 23.47it/s]
 35%|███▌      | 751/2129 [00:31<01:09, 19.73it/s]
 35%|███▌      | 754/2129 [00:32<01:47, 12.81it/s]
 36%|███▌      | 756/2129 [00:32<01:48, 12.66it/s]
 36%|███▌      | 759/2129 [00:32<01:29, 15.29it/s]
 36%|███▌      | 764/2129 [00:32<01:03, 21.53it/s]
 36%|███▌      | 767/2129 [00:32<01:24, 16.11it/s]
 36%|███▌      | 770/2129 [00:33<01:13, 18.41it/s]
 36%|███▋      | 774/2129 [00:33<01:18, 17.26it/s]
 36%|███▋      | 777/2129 [00:33<01:12, 18.66it/s]
 37%|███▋      | 780/2129 [00:33<01:16, 17.53it/s]
 37%|███▋      | 783/2129 [00:33<01:11, 18.82it/s]
 37%|███▋      | 786/2129 [00:34<01:23, 16.04it/s]
 37%|███▋      | 789/2129 [00:34<01:12, 18.38it/s]
 37%|███▋      | 795/2129 [00:34<01:04, 20.65it/s]
 37%|███▋      | 798/2129 [00:34<01:37, 13.62it/s]
 38%|███▊      | 800/2129 [00:34<01:32, 14.39it/s]
 38%|███▊      | 802/2129 [00:35<01:27, 15.20it/s]
 38%|███▊      | 805/2129 [00:35<01:16, 17.29it/s]
 38%|███▊      | 811/2129 [00:35<00:51, 25.44it/s]
 38%|███▊      | 818/2129 [00:35<00:38, 34.38it/s]
 39%|███▊      | 822/2129 [00:35<00:48, 27.07it/s]
 39%|███▉      | 826/2129 [00:35<00:53, 24.33it/s]
 39%|███▉      | 830/2129 [00:35<00:48, 26.59it/s]
 39%|███▉      | 836/2129 [00:36<00:41, 31.45it/s]
 39%|███▉      | 840/2129 [00:36<01:00, 21.17it/s]
 40%|███▉      | 843/2129 [00:36<01:12, 17.82it/s]
 40%|███▉      | 846/2129 [00:36<01:07, 19.05it/s]
 40%|███▉      | 849/2129 [00:37<01:19, 16.08it/s]
 40%|████      | 854/2129 [00:37<01:14, 17.17it/s]
 40%|████      | 856/2129 [00:37<01:15, 16.82it/s]
 40%|████      | 860/2129 [00:37<01:13, 17.33it/s]
 41%|████      | 863/2129 [00:37<01:06, 18.95it/s]
 41%|████      | 866/2129 [00:38<01:35, 13.16it/s]
 41%|████      | 868/2129 [00:38<01:30, 14.00it/s]
 41%|████      | 873/2129 [00:38<01:18, 15.96it/s]
 41%|████      | 875/2129 [00:38<01:17, 16.15it/s]
 41%|████▏     | 880/2129 [00:38<00:56, 22.08it/s]
 42%|████▏     | 886/2129 [00:39<00:58, 21.15it/s]
 42%|████▏     | 889/2129 [00:39<01:09, 17.74it/s]
 42%|████▏     | 894/2129 [00:39<00:54, 22.53it/s]
 42%|████▏     | 898/2129 [00:39<00:59, 20.56it/s]
 42%|████▏     | 902/2129 [00:39<00:52, 23.31it/s]
 43%|████▎     | 906/2129 [00:40<00:59, 20.40it/s]
 43%|████▎     | 909/2129 [00:40<01:13, 16.64it/s]
 43%|████▎     | 911/2129 [00:40<01:27, 14.00it/s]
 43%|████▎     | 913/2129 [00:40<01:40, 12.07it/s]
 43%|████▎     | 915/2129 [00:41<01:47, 11.33it/s]
 43%|████▎     | 918/2129 [00:41<01:26, 14.00it/s]
 44%|████▎     | 927/2129 [00:41<00:57, 20.75it/s]
 44%|████▎     | 930/2129 [00:41<01:07, 17.69it/s]
 44%|████▍     | 935/2129 [00:41<00:53, 22.43it/s]
 44%|████▍     | 938/2129 [00:42<01:23, 14.18it/s]
 44%|████▍     | 941/2129 [00:42<01:31, 12.96it/s]
 44%|████▍     | 944/2129 [00:42<01:32, 12.80it/s]
 44%|████▍     | 946/2129 [00:43<01:41, 11.64it/s]
 45%|████▍     | 949/2129 [00:43<01:24, 14.02it/s]
 45%|████▍     | 951/2129 [00:43<01:37, 12.10it/s]
 45%|████▍     | 954/2129 [00:43<01:19, 14.70it/s]
 45%|████▍     | 958/2129 [00:43<01:17, 15.07it/s]
 45%|████▌     | 960/2129 [00:44<01:33, 12.49it/s]
 45%|████▌     | 962/2129 [00:44<01:51, 10.48it/s]
 45%|████▌     | 964/2129 [00:44<01:59,  9.76it/s]
 45%|████▌     | 968/2129 [00:45<01:50, 10.49it/s]
 46%|████▌     | 971/2129 [00:45<01:32, 12.49it/s]
 46%|████▌     | 973/2129 [00:45<01:50, 10.51it/s]
 46%|████▌     | 975/2129 [00:45<01:42, 11.31it/s]
 46%|████▌     | 977/2129 [00:45<01:59,  9.64it/s]
 46%|████▌     | 980/2129 [00:45<01:31, 12.59it/s]
 46%|████▌     | 982/2129 [00:46<01:44, 11.02it/s]
 46%|████▋     | 985/2129 [00:46<01:21, 14.09it/s]
 46%|████▋     | 988/2129 [00:46<01:20, 14.17it/s]
 47%|████▋     | 990/2129 [00:46<01:15, 15.16it/s]
 47%|████▋     | 993/2129 [00:46<01:24, 13.49it/s]
 47%|████▋     | 996/2129 [00:47<01:10, 15.97it/s]
 47%|████▋     | 1002/2129 [00:47<00:59, 18.88it/s]
 47%|████▋     | 1005/2129 [00:47<00:56, 19.88it/s]
 47%|████▋     | 1010/2129 [00:47<00:58, 19.22it/s]
 48%|████▊     | 1013/2129 [00:48<01:28, 12.65it/s]
 48%|████▊     | 1015/2129 [00:48<01:24, 13.22it/s]
 48%|████▊     | 1019/2129 [00:48<01:16, 14.55it/s]
 48%|████▊     | 1021/2129 [00:48<01:15, 14.73it/s]
 48%|████▊     | 1023/2129 [00:48<01:18, 14.18it/s]
 48%|████▊     | 1025/2129 [00:48<01:24, 13.13it/s]
 48%|████▊     | 1027/2129 [00:49<01:20, 13.69it/s]
 48%|████▊     | 1029/2129 [00:49<01:43, 10.68it/s]
 48%|████▊     | 1032/2129 [00:49<01:19, 13.76it/s]
 49%|████▉     | 1039/2129 [00:49<00:45, 24.16it/s]
 49%|████▉     | 1045/2129 [00:49<00:34, 31.35it/s]
 49%|████▉     | 1049/2129 [00:50<00:46, 23.05it/s]
 49%|████▉     | 1053/2129 [00:50<01:00, 17.76it/s]
 50%|████▉     | 1056/2129 [00:50<01:21, 13.09it/s]
 50%|████▉     | 1058/2129 [00:51<01:29, 11.91it/s]
 50%|████▉     | 1060/2129 [00:51<01:41, 10.55it/s]
 50%|████▉     | 1063/2129 [00:51<01:23, 12.76it/s]
 50%|█████     | 1065/2129 [00:51<01:35, 11.16it/s]
 50%|█████     | 1069/2129 [00:51<01:08, 15.43it/s]
 50%|█████     | 1072/2129 [00:52<01:14, 14.10it/s]
 50%|█████     | 1075/2129 [00:52<01:03, 16.70it/s]
 51%|█████     | 1083/2129 [00:52<00:37, 28.01it/s]
 51%|█████     | 1087/2129 [00:52<00:54, 19.05it/s]
 51%|█████     | 1091/2129 [00:52<00:59, 17.36it/s]
 51%|█████▏    | 1094/2129 [00:53<01:09, 14.87it/s]
 51%|█████▏    | 1096/2129 [00:53<01:06, 15.51it/s]
 52%|█████▏    | 1102/2129 [00:53<00:45, 22.59it/s]
 52%|█████▏    | 1106/2129 [00:53<01:09, 14.68it/s]
 52%|█████▏    | 1109/2129 [00:54<01:02, 16.20it/s]
 52%|█████▏    | 1112/2129 [00:54<01:03, 15.94it/s]
 52%|█████▏    | 1115/2129 [00:54<01:17, 13.14it/s]
 53%|█████▎    | 1118/2129 [00:54<01:15, 13.43it/s]
 53%|█████▎    | 1120/2129 [00:55<01:33, 10.83it/s]
 53%|█████▎    | 1123/2129 [00:55<01:16, 13.14it/s]
 53%|█████▎    | 1126/2129 [00:55<01:14, 13.38it/s]
 53%|█████▎    | 1128/2129 [00:55<01:28, 11.35it/s]
 53%|█████▎    | 1132/2129 [00:56<01:25, 11.60it/s]
 53%|█████▎    | 1134/2129 [00:56<01:21, 12.21it/s]
 53%|█████▎    | 1137/2129 [00:56<01:06, 14.96it/s]
 53%|█████▎    | 1139/2129 [00:56<01:29, 11.02it/s]
 54%|█████▎    | 1141/2129 [00:56<01:26, 11.45it/s]
 54%|█████▎    | 1143/2129 [00:56<01:21, 12.02it/s]
 54%|█████▍    | 1145/2129 [00:57<01:13, 13.40it/s]
 54%|█████▍    | 1147/2129 [00:57<01:25, 11.50it/s]
 54%|█████▍    | 1149/2129 [00:57<01:18, 12.53it/s]
 54%|█████▍    | 1152/2129 [00:57<01:09, 13.98it/s]
 54%|█████▍    | 1155/2129 [00:57<01:15, 12.89it/s]
 54%|█████▍    | 1157/2129 [00:58<01:51,  8.75it/s]
 54%|█████▍    | 1159/2129 [00:58<01:55,  8.43it/s]
 55%|█████▍    | 1161/2129 [00:58<01:39,  9.76it/s]
 55%|█████▍    | 1164/2129 [00:58<01:17, 12.48it/s]
 55%|█████▍    | 1170/2129 [00:59<00:58, 16.44it/s]
 55%|█████▌    | 1173/2129 [00:59<00:52, 18.04it/s]
 55%|█████▌    | 1176/2129 [00:59<00:56, 16.74it/s]
 55%|█████▌    | 1179/2129 [00:59<00:52, 18.21it/s]
 55%|█████▌    | 1181/2129 [00:59<01:06, 14.20it/s]
 56%|█████▌    | 1183/2129 [01:00<01:21, 11.60it/s]
 56%|█████▌    | 1187/2129 [01:00<00:58, 16.07it/s]
 56%|█████▌    | 1190/2129 [01:00<01:02, 15.05it/s]
 56%|█████▌    | 1193/2129 [01:00<00:54, 17.03it/s]
 56%|█████▌    | 1196/2129 [01:01<01:35,  9.76it/s]
 56%|█████▋    | 1198/2129 [01:01<01:31, 10.17it/s]
 57%|█████▋    | 1205/2129 [01:01<00:51, 17.97it/s]
 57%|█████▋    | 1208/2129 [01:01<00:57, 16.10it/s]
 57%|█████▋    | 1211/2129 [01:01<01:03, 14.40it/s]
 57%|█████▋    | 1213/2129 [01:02<01:26, 10.63it/s]
 57%|█████▋    | 1216/2129 [01:02<01:12, 12.61it/s]
 57%|█████▋    | 1220/2129 [01:02<01:04, 14.10it/s]
 57%|█████▋    | 1223/2129 [01:02<00:58, 15.62it/s]
 58%|█████▊    | 1225/2129 [01:03<01:10, 12.77it/s]
 58%|█████▊    | 1227/2129 [01:03<01:17, 11.58it/s]
 58%|█████▊    | 1230/2129 [01:03<01:03, 14.26it/s]
 58%|█████▊    | 1232/2129 [01:03<01:14, 12.09it/s]
 58%|█████▊    | 1235/2129 [01:03<00:59, 15.13it/s]
 58%|█████▊    | 1243/2129 [01:03<00:31, 27.78it/s]
 59%|█████▊    | 1247/2129 [01:04<00:49, 17.94it/s]
 59%|█████▊    | 1250/2129 [01:04<00:45, 19.50it/s]
 59%|█████▉    | 1255/2129 [01:04<00:43, 19.97it/s]
 59%|█████▉    | 1258/2129 [01:04<00:51, 16.81it/s]
 59%|█████▉    | 1261/2129 [01:05<00:59, 14.50it/s]
 59%|█████▉    | 1266/2129 [01:05<00:43, 19.63it/s]
 60%|█████▉    | 1271/2129 [01:05<00:43, 19.60it/s]
 60%|█████▉    | 1274/2129 [01:05<00:53, 16.02it/s]
 60%|█████▉    | 1277/2129 [01:06<01:05, 13.04it/s]
 60%|██████    | 1279/2129 [01:06<01:15, 11.33it/s]
 60%|██████    | 1281/2129 [01:06<01:10, 11.99it/s]
 60%|██████    | 1283/2129 [01:06<01:15, 11.20it/s]
 60%|██████    | 1285/2129 [01:06<01:07, 12.51it/s]
 61%|██████    | 1291/2129 [01:07<00:40, 20.86it/s]
 61%|██████    | 1294/2129 [01:07<00:54, 15.21it/s]
 61%|██████    | 1297/2129 [01:07<01:13, 11.26it/s]
 61%|██████    | 1299/2129 [01:08<01:19, 10.50it/s]
 61%|██████    | 1301/2129 [01:08<01:21, 10.16it/s]
 61%|██████    | 1303/2129 [01:08<01:23,  9.83it/s]
 61%|██████▏   | 1305/2129 [01:08<01:44,  7.90it/s]
 61%|██████▏   | 1307/2129 [01:09<01:29,  9.17it/s]
 61%|██████▏   | 1309/2129 [01:09<01:31,  9.00it/s]
 62%|██████▏   | 1311/2129 [01:09<01:33,  8.78it/s]
 62%|██████▏   | 1314/2129 [01:09<01:10, 11.50it/s]
 62%|██████▏   | 1316/2129 [01:09<01:15, 10.84it/s]
 62%|██████▏   | 1318/2129 [01:10<01:20, 10.05it/s]
 62%|██████▏   | 1320/2129 [01:10<01:30,  8.96it/s]
 62%|██████▏   | 1322/2129 [01:10<01:41,  7.98it/s]
 62%|██████▏   | 1324/2129 [01:10<01:39,  8.11it/s]
 62%|██████▏   | 1326/2129 [01:11<01:24,  9.54it/s]
 62%|██████▏   | 1328/2129 [01:11<01:19, 10.05it/s]
 63%|██████▎   | 1331/2129 [01:11<01:17, 10.30it/s]
 63%|██████▎   | 1334/2129 [01:11<01:00, 13.13it/s]
 63%|██████▎   | 1340/2129 [01:11<00:37, 20.99it/s]
 63%|██████▎   | 1343/2129 [01:12<00:48, 16.12it/s]
 63%|██████▎   | 1348/2129 [01:12<00:36, 21.16it/s]
 63%|██████▎   | 1351/2129 [01:12<00:44, 17.45it/s]
 64%|██████▎   | 1354/2129 [01:12<00:54, 14.31it/s]
 64%|██████▎   | 1357/2129 [01:12<00:53, 14.32it/s]
 64%|██████▍   | 1359/2129 [01:13<01:01, 12.49it/s]
 64%|██████▍   | 1361/2129 [01:13<00:57, 13.25it/s]
 64%|██████▍   | 1368/2129 [01:13<00:33, 22.88it/s]
 64%|██████▍   | 1371/2129 [01:13<00:40, 18.84it/s]
 65%|██████▍   | 1375/2129 [01:13<00:43, 17.29it/s]
 65%|██████▍   | 1378/2129 [01:14<00:49, 15.16it/s]
 65%|██████▍   | 1380/2129 [01:14<00:47, 15.87it/s]
 65%|██████▍   | 1383/2129 [01:14<00:49, 15.18it/s]
 65%|██████▌   | 1385/2129 [01:14<00:59, 12.56it/s]
 65%|██████▌   | 1388/2129 [01:15<01:03, 11.76it/s]
 65%|██████▌   | 1390/2129 [01:15<01:08, 10.78it/s]
 65%|██████▌   | 1392/2129 [01:15<01:03, 11.57it/s]
 65%|██████▌   | 1394/2129 [01:15<01:33,  7.83it/s]
 66%|██████▌   | 1396/2129 [01:16<01:19,  9.20it/s]
 66%|██████▌   | 1402/2129 [01:16<00:53, 13.49it/s]
 66%|██████▌   | 1405/2129 [01:16<00:57, 12.54it/s]
 66%|██████▌   | 1408/2129 [01:16<00:48, 14.85it/s]
 66%|██████▋   | 1411/2129 [01:16<00:50, 14.09it/s]
 66%|██████▋   | 1413/2129 [01:17<00:49, 14.59it/s]
 67%|██████▋   | 1419/2129 [01:17<00:31, 22.59it/s]
 67%|██████▋   | 1422/2129 [01:17<00:39, 17.84it/s]
 67%|██████▋   | 1427/2129 [01:17<00:29, 23.55it/s]
 67%|██████▋   | 1431/2129 [01:17<00:35, 19.54it/s]
 67%|██████▋   | 1436/2129 [01:18<00:35, 19.77it/s]
 68%|██████▊   | 1439/2129 [01:18<00:34, 20.02it/s]
 68%|██████▊   | 1443/2129 [01:18<00:30, 22.68it/s]
 68%|██████▊   | 1451/2129 [01:18<00:21, 31.72it/s]
 68%|██████▊   | 1455/2129 [01:18<00:32, 20.58it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 340.22it/s]

[[np.int64(0), False, 8], [np.int64(1), False, 9], [np.int64(2), False, 7], [np.int64(3), False, 7], [np.int64(4), False, 12], [np.int64(5), False, 10], [np.int64(6), False, 12], [np.int64(7), False, 8], [np.int64(11), False, 12], [np.int64(12), False, 0], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4263, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [06:41<56:30, 34.25s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [06:41<39:13, 24.02s/it]

tensor(12.1513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5804, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7255, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [06:41<13:10,  8.32s/it]

tensor(12.1699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7693, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8490, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [06:41<09:10,  5.86s/it]

tensor(12.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8903, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9286, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [06:42<03:10,  2.09s/it]

tensor(12.1798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9692, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9968, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [06:42<01:36,  1.09s/it]

tensor(12.1638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0327, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1615, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0519, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [06:42<00:51,  1.69it/s]

tensor(12.1604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0531, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0888, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [06:42<00:39,  2.21it/s]

tensor(12.1555, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1734, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [06:43<00:19,  4.27it/s]

tensor(12.1519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1906, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2078, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [06:43<00:16,  4.98it/s]

tensor(12.1565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1575, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2081, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [06:43<00:11,  6.71it/s]

tensor(12.1541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2040, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1482, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2100, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [06:43<00:10,  7.10it/s]

tensor(12.1420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2100, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2163, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [06:44<00:10,  7.54it/s]

tensor(12.1302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2227, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1236, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2286, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [06:44<00:09,  8.02it/s]

tensor(12.1189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2548, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [06:44<00:08,  8.07it/s]

tensor(12.1129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2610, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1094, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2713, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [06:44<00:08,  8.16it/s]

tensor(12.1075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2759, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2827, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [06:45<00:08,  8.17it/s]

tensor(12.1041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2862, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2899, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [06:45<00:07,  8.22it/s]

tensor(12.0984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2937, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2990, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [06:45<00:07,  8.23it/s]

tensor(12.0918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3013, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3060, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [06:45<00:07,  8.24it/s]

tensor(12.0851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3058, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3102, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [06:46<00:07,  8.22it/s]

tensor(12.0797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3132, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3158, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [06:46<00:06,  8.22it/s]

tensor(12.0756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3185, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3209, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [06:46<00:06,  8.20it/s]

tensor(12.0711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3241, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3256, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [06:46<00:06,  8.09it/s]

tensor(12.0667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3268, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3289, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [06:47<00:06,  8.20it/s]

tensor(12.0626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3319, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [06:47<00:06,  8.18it/s]

tensor(12.0585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3348, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([224, 154, 137, 168, 210, 135, 258,  78, 151, 106, 110, 149, 140, 109])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:39, 21.33it/s]
  0%|          | 6/2129 [00:00<01:27, 24.23it/s]
  1%|          | 12/2129 [00:00<00:55, 38.48it/s]
  1%|          | 19/2129 [00:00<00:44, 47.82it/s]
  1%|          | 24/2129 [00:00<00:47, 44.45it/s]
  1%|▏         | 29/2129 [00:00<00:48, 43.17it/s]
  2%|▏         | 37/2129 [00:00<00:39, 52.39it/s]
  2%|▏         | 45/2129 [00:00<00:34, 60.11it/s]
  2%|▏         | 52/2129 [00:01<00:36, 57.12it/s]
  3%|▎         | 59/2129 [00:01<00:35, 59.13it/s]
  3%|▎         | 66/2129 [00:01<00:38, 53.66it/s]
  3%|▎         | 73/2129 [00:01<00:36, 55.69it/s]
  4%|▎         | 79/2129 [00:01<00:39, 51.36it/s]
  4%|▍         | 85/2129 [00:01<00:39, 51.82it/s]
  4%|▍         | 92/2129 [00:01<00:37, 54.79it/s]
  5%|▍         | 99/2129 [00:01<00:35, 57.90it/s]
  5%|▍         | 105/2129 [00:02<00:38, 51.91it/s]
  5%|▌         | 113/2129 [00:02<00:58, 34.64it/s]
  6%|▌         | 118/2129 [00:02<00:59, 33.94it/s]
  6%|▌         | 125/2129 [00:02<00:49, 40.45it/s]
  6%|▌         | 131/2129 [00:02<00:46, 43.22it/s]
  6%|▋         | 136/2129 [00:03<01:23, 23.97it/s]
  7%|▋         | 143/2129 [00:03<01:05, 30.12it/s]
  7%|▋         | 148/2129 [00:03<00:59, 33.44it/s]
  7%|▋         | 157/2129 [00:03<00:45, 43.04it/s]
  8%|▊         | 163/2129 [00:03<00:42, 45.91it/s]
  8%|▊         | 170/2129 [00:03<00:38, 51.29it/s]
  8%|▊         | 176/2129 [00:04<01:13, 26.51it/s]
  9%|▊         | 181/2129 [00:04<01:43, 18.80it/s]
  9%|▊         | 185/2129 [00:05<01:41, 19.16it/s]
  9%|▉         | 191/2129 [00:05<01:21, 23.88it/s]
  9%|▉         | 197/2129 [00:05<01:05, 29.34it/s]
  9%|▉         | 202/2129 [00:05<01:32, 20.81it/s]
 10%|▉         | 206/2129 [00:05<01:25, 22.39it/s]
 10%|▉         | 212/2129 [00:06<01:34, 20.28it/s]
 10%|█         | 215/2129 [00:06<01:58, 16.18it/s]
 10%|█         | 218/2129 [00:06<01:53, 16.81it/s]
 10%|█         | 221/2129 [00:06<01:45, 18.11it/s]
 11%|█         | 224/2129 [00:06<01:41, 18.80it/s]
 11%|█         | 230/2129 [00:07<01:13, 25.73it/s]
 11%|█         | 235/2129 [00:07<01:03, 29.76it/s]
 11%|█         | 239/2129 [00:07<01:31, 20.72it/s]
 11%|█▏        | 242/2129 [00:07<01:33, 20.16it/s]
 12%|█▏        | 245/2129 [00:07<01:30, 20.74it/s]
 12%|█▏        | 248/2129 [00:08<02:09, 14.58it/s]
 12%|█▏        | 252/2129 [00:08<02:24, 13.02it/s]
 12%|█▏        | 255/2129 [00:08<02:07, 14.67it/s]
 12%|█▏        | 263/2129 [00:08<01:17, 23.96it/s]
 13%|█▎        | 267/2129 [00:09<01:46, 17.45it/s]
 13%|█▎        | 270/2129 [00:09<02:14, 13.80it/s]
 13%|█▎        | 273/2129 [00:09<02:00, 15.39it/s]
 13%|█▎        | 281/2129 [00:09<01:14, 24.91it/s]
 13%|█▎        | 287/2129 [00:10<01:26, 21.38it/s]
 14%|█▎        | 291/2129 [00:10<01:21, 22.64it/s]
 14%|█▍        | 295/2129 [00:11<03:01, 10.13it/s]
 14%|█▍        | 298/2129 [00:11<02:39, 11.49it/s]
 14%|█▍        | 303/2129 [00:11<01:57, 15.54it/s]
 15%|█▍        | 311/2129 [00:11<01:16, 23.73it/s]
 15%|█▍        | 316/2129 [00:12<01:41, 17.79it/s]
 15%|█▌        | 320/2129 [00:12<01:58, 15.26it/s]
 15%|█▌        | 323/2129 [00:12<01:46, 16.95it/s]
 15%|█▌        | 326/2129 [00:13<02:14, 13.39it/s]
 16%|█▌        | 332/2129 [00:13<01:34, 19.03it/s]
 16%|█▌        | 337/2129 [00:13<01:47, 16.73it/s]
 16%|█▌        | 340/2129 [00:13<01:40, 17.77it/s]
 16%|█▌        | 343/2129 [00:13<01:33, 19.07it/s]
 16%|█▋        | 349/2129 [00:13<01:08, 25.98it/s]
 17%|█▋        | 353/2129 [00:14<01:49, 16.21it/s]
 17%|█▋        | 356/2129 [00:14<02:07, 13.85it/s]
 17%|█▋        | 359/2129 [00:15<02:25, 12.13it/s]
 17%|█▋        | 361/2129 [00:15<02:17, 12.85it/s]
 17%|█▋        | 364/2129 [00:15<02:02, 14.43it/s]
 17%|█▋        | 367/2129 [00:15<01:46, 16.50it/s]
 18%|█▊        | 373/2129 [00:15<01:36, 18.23it/s]
 18%|█▊        | 376/2129 [00:15<01:47, 16.33it/s]
 18%|█▊        | 378/2129 [00:16<01:50, 15.90it/s]
 18%|█▊        | 380/2129 [00:16<02:28, 11.80it/s]
 18%|█▊        | 382/2129 [00:16<02:14, 12.99it/s]
 18%|█▊        | 384/2129 [00:16<02:19, 12.52it/s]
 18%|█▊        | 386/2129 [00:17<02:57,  9.82it/s]
 18%|█▊        | 388/2129 [00:17<02:36, 11.14it/s]
 19%|█▊        | 394/2129 [00:17<02:12, 13.07it/s]
 19%|█▊        | 397/2129 [00:17<01:55, 14.98it/s]
 19%|█▉        | 400/2129 [00:18<02:25, 11.89it/s]
 19%|█▉        | 402/2129 [00:18<02:23, 11.99it/s]
 19%|█▉        | 404/2129 [00:18<02:12, 13.00it/s]
 19%|█▉        | 408/2129 [00:18<02:18, 12.44it/s]
 19%|█▉        | 411/2129 [00:18<01:56, 14.80it/s]
 20%|█▉        | 419/2129 [00:18<01:06, 25.84it/s]
 20%|█▉        | 424/2129 [00:19<01:02, 27.44it/s]
 20%|██        | 430/2129 [00:19<01:04, 26.27it/s]
 20%|██        | 434/2129 [00:19<01:19, 21.23it/s]
 21%|██        | 437/2129 [00:20<01:57, 14.45it/s]
 21%|██        | 440/2129 [00:20<02:26, 11.49it/s]
 21%|██        | 446/2129 [00:20<02:11, 12.79it/s]
 21%|██        | 450/2129 [00:20<01:47, 15.62it/s]
 21%|██▏       | 453/2129 [00:21<01:36, 17.44it/s]
 21%|██▏       | 456/2129 [00:21<02:05, 13.29it/s]
 22%|██▏       | 458/2129 [00:21<02:40, 10.40it/s]
 22%|██▏       | 461/2129 [00:21<02:13, 12.51it/s]
 22%|██▏       | 466/2129 [00:22<02:17, 12.13it/s]
 22%|██▏       | 469/2129 [00:22<01:57, 14.16it/s]
 22%|██▏       | 471/2129 [00:22<02:28, 11.15it/s]
 22%|██▏       | 473/2129 [00:23<03:14,  8.53it/s]
 22%|██▏       | 476/2129 [00:23<02:33, 10.77it/s]
 22%|██▏       | 478/2129 [00:23<03:02,  9.03it/s]
 23%|██▎       | 480/2129 [00:23<02:37, 10.47it/s]
 23%|██▎       | 483/2129 [00:24<02:46,  9.87it/s]
 23%|██▎       | 485/2129 [00:24<03:14,  8.45it/s]
 23%|██▎       | 489/2129 [00:24<02:12, 12.35it/s]
 23%|██▎       | 491/2129 [00:24<02:45,  9.88it/s]
 23%|██▎       | 495/2129 [00:25<01:57, 13.89it/s]
 23%|██▎       | 498/2129 [00:25<02:19, 11.68it/s]
 24%|██▎       | 504/2129 [00:25<01:28, 18.36it/s]
 24%|██▍       | 511/2129 [00:25<01:00, 26.82it/s]
 24%|██▍       | 517/2129 [00:25<00:48, 33.03it/s]
 25%|██▍       | 522/2129 [00:26<01:38, 16.25it/s]
 25%|██▍       | 526/2129 [00:26<01:53, 14.06it/s]
 25%|██▍       | 529/2129 [00:27<02:42,  9.83it/s]
 25%|██▍       | 532/2129 [00:27<02:31, 10.53it/s]
 25%|██▌       | 536/2129 [00:28<02:27, 10.77it/s]
 25%|██▌       | 539/2129 [00:28<02:07, 12.50it/s]
 26%|██▌       | 543/2129 [00:28<02:07, 12.45it/s]
 26%|██▌       | 545/2129 [00:28<02:02, 12.92it/s]
 26%|██▌       | 547/2129 [00:28<02:43,  9.65it/s]
 26%|██▌       | 550/2129 [00:29<02:13, 11.85it/s]
 26%|██▌       | 556/2129 [00:29<01:23, 18.74it/s]
 26%|██▋       | 559/2129 [00:29<01:54, 13.66it/s]
 26%|██▋       | 562/2129 [00:29<01:47, 14.61it/s]
 27%|██▋       | 565/2129 [00:29<01:36, 16.20it/s]
 27%|██▋       | 568/2129 [00:30<01:59, 13.08it/s]
 27%|██▋       | 571/2129 [00:30<02:16, 11.37it/s]
 27%|██▋       | 573/2129 [00:31<02:54,  8.93it/s]
 27%|██▋       | 575/2129 [00:31<02:34, 10.04it/s]
 27%|██▋       | 582/2129 [00:31<01:57, 13.19it/s]
 27%|██▋       | 584/2129 [00:31<02:37,  9.78it/s]
 28%|██▊       | 586/2129 [00:32<02:58,  8.66it/s]
 28%|██▊       | 587/2129 [00:32<03:34,  7.17it/s]
 28%|██▊       | 589/2129 [00:32<03:45,  6.84it/s]
 28%|██▊       | 590/2129 [00:33<04:24,  5.82it/s]
 28%|██▊       | 593/2129 [00:33<02:59,  8.58it/s]
 28%|██▊       | 599/2129 [00:33<02:14, 11.38it/s]
 28%|██▊       | 602/2129 [00:34<02:31, 10.05it/s]
 28%|██▊       | 604/2129 [00:34<02:16, 11.14it/s]
 28%|██▊       | 606/2129 [00:34<02:45,  9.18it/s]
 29%|██▊       | 609/2129 [00:34<02:10, 11.64it/s]
 29%|██▊       | 611/2129 [00:35<02:39,  9.50it/s]
 29%|██▉       | 613/2129 [00:35<03:00,  8.40it/s]
 29%|██▉       | 616/2129 [00:35<02:20, 10.74it/s]
 29%|██▉       | 624/2129 [00:35<01:10, 21.26it/s]
 29%|██▉       | 628/2129 [00:36<01:59, 12.54it/s]
 30%|██▉       | 631/2129 [00:36<01:45, 14.25it/s]
 30%|██▉       | 634/2129 [00:36<02:05, 11.87it/s]
 30%|██▉       | 637/2129 [00:37<02:28, 10.08it/s]
 30%|███       | 640/2129 [00:37<02:02, 12.17it/s]
 30%|███       | 642/2129 [00:37<02:28, 10.03it/s]
 30%|███       | 644/2129 [00:37<02:56,  8.44it/s]
 30%|███       | 646/2129 [00:38<03:21,  7.35it/s]
 30%|███       | 649/2129 [00:38<03:18,  7.47it/s]
 31%|███       | 652/2129 [00:38<02:31,  9.78it/s]
 31%|███       | 658/2129 [00:39<02:04, 11.86it/s]
 31%|███       | 661/2129 [00:39<02:23, 10.26it/s]
 31%|███       | 663/2129 [00:40<03:23,  7.22it/s]
 31%|███▏      | 666/2129 [00:40<02:40,  9.10it/s]
 32%|███▏      | 672/2129 [00:40<02:09, 11.25it/s]
 32%|███▏      | 675/2129 [00:40<01:56, 12.43it/s]
 32%|███▏      | 677/2129 [00:41<02:31,  9.61it/s]
 32%|███▏      | 679/2129 [00:41<02:16, 10.65it/s]
 32%|███▏      | 685/2129 [00:41<02:09, 11.18it/s]
 32%|███▏      | 688/2129 [00:42<01:52, 12.83it/s]
 33%|███▎      | 694/2129 [00:42<01:15, 18.90it/s]
 33%|███▎      | 701/2129 [00:42<00:53, 26.73it/s]
 33%|███▎      | 707/2129 [00:42<01:06, 21.53it/s]
 33%|███▎      | 711/2129 [00:42<01:06, 21.32it/s]
 34%|███▎      | 714/2129 [00:43<01:20, 17.58it/s]
 34%|███▎      | 717/2129 [00:43<01:19, 17.76it/s]
 34%|███▍      | 724/2129 [00:43<00:54, 25.68it/s]
 34%|███▍      | 728/2129 [00:44<01:45, 13.23it/s]
 34%|███▍      | 731/2129 [00:44<01:34, 14.81it/s]
 35%|███▍      | 738/2129 [00:44<01:05, 21.21it/s]
 35%|███▍      | 742/2129 [00:44<01:13, 18.92it/s]
 35%|███▍      | 745/2129 [00:44<01:08, 20.30it/s]
 35%|███▌      | 752/2129 [00:44<00:48, 28.45it/s]
 36%|███▌      | 756/2129 [00:45<00:57, 24.03it/s]
 36%|███▌      | 761/2129 [00:45<00:47, 28.53it/s]
 36%|███▌      | 765/2129 [00:45<01:38, 13.84it/s]
 36%|███▌      | 769/2129 [00:46<01:41, 13.45it/s]
 36%|███▋      | 772/2129 [00:46<01:36, 14.02it/s]
 36%|███▋      | 775/2129 [00:46<01:39, 13.60it/s]
 36%|███▋      | 777/2129 [00:46<01:38, 13.78it/s]
 37%|███▋      | 780/2129 [00:47<01:52, 12.01it/s]
 37%|███▋      | 782/2129 [00:47<02:21,  9.52it/s]
 37%|███▋      | 785/2129 [00:47<01:51, 12.01it/s]
 37%|███▋      | 792/2129 [00:47<01:28, 15.08it/s]
 37%|███▋      | 794/2129 [00:48<01:50, 12.12it/s]
 37%|███▋      | 796/2129 [00:48<01:42, 13.03it/s]
 38%|███▊      | 800/2129 [00:48<01:42, 12.91it/s]
 38%|███▊      | 802/2129 [00:49<02:09, 10.23it/s]
 38%|███▊      | 805/2129 [00:49<01:44, 12.73it/s]
 38%|███▊      | 810/2129 [00:49<01:41, 12.94it/s]
 38%|███▊      | 813/2129 [00:49<01:57, 11.16it/s]
 38%|███▊      | 815/2129 [00:50<01:47, 12.21it/s]
 39%|███▊      | 822/2129 [00:50<01:03, 20.61it/s]
 39%|███▉      | 826/2129 [00:50<00:57, 22.78it/s]
 39%|███▉      | 832/2129 [00:50<00:45, 28.25it/s]
 39%|███▉      | 836/2129 [00:50<00:45, 28.13it/s]
 39%|███▉      | 840/2129 [00:50<01:06, 19.32it/s]
 40%|███▉      | 843/2129 [00:51<01:23, 15.33it/s]
 40%|███▉      | 846/2129 [00:51<02:14,  9.53it/s]
 40%|███▉      | 849/2129 [00:52<01:51, 11.49it/s]
 40%|████      | 852/2129 [00:52<01:43, 12.39it/s]
 40%|████      | 854/2129 [00:52<01:56, 10.97it/s]
 40%|████      | 856/2129 [00:52<02:05, 10.14it/s]
 40%|████      | 858/2129 [00:52<01:52, 11.28it/s]
 40%|████      | 860/2129 [00:52<01:43, 12.25it/s]
 40%|████      | 862/2129 [00:53<01:54, 11.08it/s]
 41%|████      | 864/2129 [00:53<01:45, 12.01it/s]
 41%|████      | 866/2129 [00:53<02:00, 10.47it/s]
 41%|████      | 868/2129 [00:53<01:46, 11.81it/s]
 41%|████      | 870/2129 [00:53<01:56, 10.77it/s]
 41%|████      | 873/2129 [00:54<01:55, 10.85it/s]
 41%|████      | 875/2129 [00:54<01:48, 11.53it/s]
 41%|████      | 877/2129 [00:54<02:15,  9.22it/s]
 41%|████▏     | 879/2129 [00:54<02:09,  9.67it/s]
 41%|████▏     | 882/2129 [00:54<01:39, 12.48it/s]
 42%|████▏     | 889/2129 [00:55<00:53, 22.99it/s]
 42%|████▏     | 893/2129 [00:55<01:12, 17.06it/s]
 42%|████▏     | 896/2129 [00:55<01:07, 18.25it/s]
 42%|████▏     | 902/2129 [00:55<01:10, 17.49it/s]
 43%|████▎     | 905/2129 [00:56<01:06, 18.34it/s]
 43%|████▎     | 908/2129 [00:56<01:21, 15.06it/s]
 43%|████▎     | 911/2129 [00:56<01:13, 16.53it/s]
 43%|████▎     | 913/2129 [00:56<01:19, 15.25it/s]
 43%|████▎     | 916/2129 [00:56<01:08, 17.69it/s]
 43%|████▎     | 923/2129 [00:56<00:42, 28.22it/s]
 44%|████▎     | 927/2129 [00:57<01:10, 17.06it/s]
 44%|████▎     | 930/2129 [00:57<01:32, 12.98it/s]
 44%|████▍     | 936/2129 [00:57<01:03, 18.69it/s]
 44%|████▍     | 940/2129 [00:58<01:48, 10.97it/s]
 44%|████▍     | 944/2129 [00:58<01:26, 13.69it/s]
 45%|████▍     | 950/2129 [00:59<01:20, 14.71it/s]
 45%|████▍     | 953/2129 [00:59<01:13, 16.11it/s]
 45%|████▌     | 960/2129 [00:59<01:09, 16.94it/s]
 45%|████▌     | 963/2129 [01:00<01:28, 13.17it/s]
 45%|████▌     | 967/2129 [01:00<01:33, 12.44it/s]
 46%|████▌     | 969/2129 [01:00<01:52, 10.27it/s]
 46%|████▌     | 972/2129 [01:00<01:34, 12.26it/s]
 46%|████▌     | 974/2129 [01:01<02:18,  8.36it/s]
 46%|████▌     | 976/2129 [01:01<02:05,  9.22it/s]
 46%|████▌     | 978/2129 [01:01<02:26,  7.87it/s]
 46%|████▌     | 981/2129 [01:02<02:25,  7.90it/s]
 46%|████▌     | 983/2129 [01:02<02:03,  9.26it/s]
 46%|████▋     | 988/2129 [01:02<01:43, 11.02it/s]
 47%|████▋     | 990/2129 [01:02<01:33, 12.12it/s]
 47%|████▋     | 993/2129 [01:03<01:50, 10.27it/s]
 47%|████▋     | 995/2129 [01:03<01:39, 11.41it/s]
 47%|████▋     | 1003/2129 [01:03<00:51, 21.91it/s]
 47%|████▋     | 1007/2129 [01:03<01:08, 16.40it/s]
 47%|████▋     | 1011/2129 [01:03<00:57, 19.48it/s]
 48%|████▊     | 1015/2129 [01:04<01:08, 16.35it/s]
 48%|████▊     | 1018/2129 [01:04<01:27, 12.72it/s]
 48%|████▊     | 1023/2129 [01:04<01:03, 17.40it/s]
 48%|████▊     | 1026/2129 [01:05<01:20, 13.63it/s]
 48%|████▊     | 1030/2129 [01:05<01:23, 13.14it/s]
 48%|████▊     | 1032/2129 [01:05<01:43, 10.65it/s]
 49%|████▊     | 1035/2129 [01:05<01:24, 12.89it/s]
 49%|████▉     | 1040/2129 [01:06<01:26, 12.63it/s]
 49%|████▉     | 1042/2129 [01:06<01:56,  9.32it/s]
 49%|████▉     | 1045/2129 [01:06<01:34, 11.42it/s]
 49%|████▉     | 1051/2129 [01:07<01:22, 13.01it/s]
 50%|████▉     | 1054/2129 [01:07<01:13, 14.61it/s]
 50%|████▉     | 1056/2129 [01:07<01:28, 12.12it/s]
 50%|████▉     | 1058/2129 [01:07<01:24, 12.67it/s]
 50%|████▉     | 1060/2129 [01:08<01:58,  9.03it/s]
 50%|████▉     | 1062/2129 [01:08<01:51,  9.60it/s]
 50%|████▉     | 1064/2129 [01:08<02:16,  7.81it/s]
 50%|█████     | 1066/2129 [01:09<01:56,  9.11it/s]
 50%|█████     | 1070/2129 [01:09<01:46,  9.93it/s]
 50%|█████     | 1073/2129 [01:09<01:27, 12.10it/s]
 51%|█████     | 1080/2129 [01:09<00:49, 21.03it/s]
 51%|█████     | 1088/2129 [01:09<00:34, 29.95it/s]
 51%|█████▏    | 1092/2129 [01:09<00:34, 30.41it/s]
 51%|█████▏    | 1096/2129 [01:10<00:50, 20.51it/s]
 52%|█████▏    | 1100/2129 [01:10<00:44, 22.94it/s]
 52%|█████▏    | 1104/2129 [01:10<00:54, 18.80it/s]
 52%|█████▏    | 1107/2129 [01:10<01:03, 16.10it/s]
 52%|█████▏    | 1110/2129 [01:11<01:27, 11.60it/s]
 52%|█████▏    | 1112/2129 [01:11<01:39, 10.19it/s]
 52%|█████▏    | 1114/2129 [01:11<01:37, 10.37it/s]
 52%|█████▏    | 1116/2129 [01:12<01:34, 10.72it/s]
 53%|█████▎    | 1118/2129 [01:12<01:26, 11.68it/s]
 53%|█████▎    | 1121/2129 [01:12<01:13, 13.64it/s]
 53%|█████▎    | 1126/2129 [01:12<01:11, 13.93it/s]
 53%|█████▎    | 1128/2129 [01:13<01:31, 10.98it/s]
 53%|█████▎    | 1131/2129 [01:13<01:41,  9.80it/s]
 53%|█████▎    | 1134/2129 [01:13<01:21, 12.15it/s]
 53%|█████▎    | 1136/2129 [01:13<01:45,  9.45it/s]
 53%|█████▎    | 1139/2129 [01:14<01:26, 11.42it/s]
 54%|█████▎    | 1141/2129 [01:14<01:43,  9.57it/s]
 54%|█████▎    | 1143/2129 [01:14<01:57,  8.36it/s]
 54%|█████▍    | 1145/2129 [01:14<01:39,  9.86it/s]
 54%|█████▍    | 1152/2129 [01:15<01:03, 15.41it/s]
 54%|█████▍    | 1154/2129 [01:15<01:14, 13.13it/s]
 54%|█████▍    | 1156/2129 [01:15<01:32, 10.57it/s]
 54%|█████▍    | 1158/2129 [01:15<01:47,  9.06it/s]
 54%|█████▍    | 1160/2129 [01:16<01:58,  8.17it/s]
 55%|█████▍    | 1162/2129 [01:16<01:42,  9.42it/s]
 55%|█████▍    | 1167/2129 [01:16<01:22, 11.64it/s]
 55%|█████▍    | 1170/2129 [01:17<01:31, 10.50it/s]
 55%|█████▌    | 1172/2129 [01:17<01:24, 11.29it/s]
 55%|█████▌    | 1174/2129 [01:17<01:17, 12.34it/s]
 55%|█████▌    | 1176/2129 [01:17<01:36,  9.85it/s]
 55%|█████▌    | 1178/2129 [01:17<01:28, 10.70it/s]
 55%|█████▌    | 1180/2129 [01:18<01:53,  8.39it/s]
 56%|█████▌    | 1182/2129 [01:18<01:34,  9.98it/s]
 56%|█████▌    | 1184/2129 [01:18<01:59,  7.92it/s]
 56%|█████▌    | 1186/2129 [01:18<01:38,  9.54it/s]
 56%|█████▌    | 1191/2129 [01:18<01:01, 15.23it/s]
 56%|█████▌    | 1196/2129 [01:19<01:03, 14.81it/s]
 56%|█████▋    | 1199/2129 [01:19<00:55, 16.68it/s]
 57%|█████▋    | 1206/2129 [01:19<00:53, 17.30it/s]
 57%|█████▋    | 1209/2129 [01:19<00:49, 18.71it/s]
 57%|█████▋    | 1212/2129 [01:20<01:05, 13.97it/s]
 57%|█████▋    | 1216/2129 [01:20<00:52, 17.52it/s]
 57%|█████▋    | 1222/2129 [01:20<00:55, 16.44it/s]
 58%|█████▊    | 1225/2129 [01:20<00:52, 17.21it/s]
 58%|█████▊    | 1228/2129 [01:21<01:10, 12.69it/s]
 58%|█████▊    | 1231/2129 [01:21<01:20, 11.21it/s]
 58%|█████▊    | 1233/2129 [01:21<01:16, 11.67it/s]
 58%|█████▊    | 1235/2129 [01:22<01:31,  9.74it/s]
 58%|█████▊    | 1238/2129 [01:22<01:14, 11.90it/s]
 58%|█████▊    | 1245/2129 [01:22<00:43, 20.47it/s]
 59%|█████▊    | 1248/2129 [01:22<00:49, 17.84it/s]
 59%|█████▉    | 1251/2129 [01:22<01:01, 14.28it/s]
 59%|█████▉    | 1253/2129 [01:23<00:59, 14.81it/s]
 59%|█████▉    | 1255/2129 [01:23<01:06, 13.07it/s]
 59%|█████▉    | 1257/2129 [01:23<01:17, 11.22it/s]
 59%|█████▉    | 1259/2129 [01:23<01:11, 12.20it/s]
 59%|█████▉    | 1263/2129 [01:23<00:50, 17.19it/s]
 60%|█████▉    | 1267/2129 [01:23<00:40, 21.14it/s]
 60%|█████▉    | 1271/2129 [01:24<00:43, 19.61it/s]
 60%|█████▉    | 1274/2129 [01:24<00:40, 21.30it/s]
 60%|█████▉    | 1277/2129 [01:24<00:48, 17.39it/s]
 60%|██████    | 1280/2129 [01:24<00:42, 19.76it/s]
 60%|██████    | 1286/2129 [01:24<00:30, 27.83it/s]
 61%|██████    | 1290/2129 [01:25<00:54, 15.30it/s]
 61%|██████    | 1293/2129 [01:25<00:55, 14.97it/s]
 61%|██████    | 1296/2129 [01:25<01:09, 11.98it/s]
 61%|██████    | 1298/2129 [01:26<01:19, 10.41it/s]
 61%|██████    | 1301/2129 [01:26<01:04, 12.75it/s]
 61%|██████    | 1303/2129 [01:26<01:03, 13.00it/s]
 61%|██████▏   | 1305/2129 [01:26<01:13, 11.17it/s]
 61%|██████▏   | 1307/2129 [01:26<01:07, 12.14it/s]
 62%|██████▏   | 1310/2129 [01:26<00:54, 14.96it/s]
 62%|██████▏   | 1312/2129 [01:27<01:00, 13.61it/s]
 62%|██████▏   | 1314/2129 [01:27<01:18, 10.38it/s]
 62%|██████▏   | 1316/2129 [01:27<01:38,  8.24it/s]
 62%|██████▏   | 1318/2129 [01:28<02:01,  6.68it/s]
 62%|██████▏   | 1320/2129 [01:28<01:39,  8.10it/s]
 62%|██████▏   | 1322/2129 [01:28<01:27,  9.23it/s]
 62%|██████▏   | 1325/2129 [01:28<01:27,  9.22it/s]
 62%|██████▏   | 1328/2129 [01:28<01:07, 11.86it/s]
 63%|██████▎   | 1331/2129 [01:29<01:13, 10.83it/s]
 63%|██████▎   | 1333/2129 [01:29<01:09, 11.46it/s]
 63%|██████▎   | 1335/2129 [01:29<01:02, 12.62it/s]
 63%|██████▎   | 1339/2129 [01:29<01:05, 12.04it/s]
 63%|██████▎   | 1341/2129 [01:29<01:02, 12.62it/s]
 63%|██████▎   | 1345/2129 [01:30<00:45, 17.22it/s]
 63%|██████▎   | 1349/2129 [01:30<00:51, 15.03it/s]
 63%|██████▎   | 1351/2129 [01:30<00:49, 15.62it/s]
 64%|██████▎   | 1353/2129 [01:30<01:08, 11.40it/s]
 64%|██████▎   | 1355/2129 [01:31<01:22,  9.41it/s]
 64%|██████▎   | 1357/2129 [01:31<01:34,  8.14it/s]
 64%|██████▍   | 1360/2129 [01:31<01:11, 10.69it/s]
 64%|██████▍   | 1368/2129 [01:31<00:36, 20.67it/s]
 64%|██████▍   | 1371/2129 [01:32<00:47, 15.79it/s]
 65%|██████▍   | 1374/2129 [01:32<00:42, 17.72it/s]
 65%|██████▍   | 1377/2129 [01:32<00:54, 13.82it/s]
 65%|██████▍   | 1380/2129 [01:32<00:48, 15.42it/s]
 65%|██████▍   | 1383/2129 [01:33<01:03, 11.78it/s]
 65%|██████▌   | 1385/2129 [01:33<01:02, 11.99it/s]
 65%|██████▌   | 1388/2129 [01:33<01:08, 10.82it/s]
 65%|██████▌   | 1390/2129 [01:33<01:05, 11.29it/s]
 65%|██████▌   | 1393/2129 [01:34<01:14,  9.92it/s]
 66%|██████▌   | 1395/2129 [01:34<01:05, 11.13it/s]
 66%|██████▌   | 1399/2129 [01:34<01:06, 10.97it/s]
 66%|██████▌   | 1401/2129 [01:34<00:59, 12.20it/s]
 66%|██████▌   | 1403/2129 [01:35<01:16,  9.50it/s]
 66%|██████▌   | 1407/2129 [01:35<00:53, 13.56it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 276.39it/s]

[[np.int64(0), False, 6], [np.int64(1), False, 13], [np.int64(2), False, 1], [np.int64(3), False, 2], [np.int64(4), False, 1], [np.int64(5), False, 1], [np.int64(7), False, 8], [np.int64(9), False, 8], [np.int64(10), False, 4], [np.int64(11), False, 4], [np.int64(12), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8448, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [08:52<30:38, 37.51s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [08:52<21:02, 26.31s/it]

tensor(12.0580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0190, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0661, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1463, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [08:52<09:55, 12.95s/it]

tensor(12.0728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1713, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [08:52<04:42,  6.41s/it]

tensor(12.0779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1925, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2213, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [08:53<01:33,  2.28s/it]

tensor(12.0733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2502, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2822, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [08:53<01:05,  1.63s/it]

tensor(12.0595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3065, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3242, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [08:53<00:32,  1.16it/s]

tensor(12.0629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3386, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3448, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [08:53<00:13,  2.66it/s]

tensor(12.0664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3478, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3447, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [08:54<00:08,  4.08it/s]

tensor(12.0613, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3450, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3471, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [08:54<00:05,  5.50it/s]

tensor(12.0525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3481, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [08:54<00:04,  6.11it/s]

tensor(12.0449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3497, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3533, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [08:54<00:03,  7.01it/s]

tensor(12.0414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3526, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0407, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3522, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [08:54<00:03,  7.58it/s]

tensor(12.0397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3513, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0384, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3540, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [08:55<00:02,  7.97it/s]

tensor(12.0364, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3534, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3555, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [08:55<00:02,  8.11it/s]

tensor(12.0311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3565, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3600, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [08:55<00:02,  8.00it/s]

tensor(12.0263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0244, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3616, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [08:55<00:02,  8.20it/s]

tensor(12.0233, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3626, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0224, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3646, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [08:56<00:01,  8.22it/s]

tensor(12.0218, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3623, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0206, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3621, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [08:56<00:01,  8.20it/s]

tensor(12.0193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3618, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3620, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [08:56<00:01,  8.09it/s]

tensor(12.0160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3615, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3607, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [08:56<00:01,  8.23it/s]

tensor(12.0128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3620, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3638, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [08:57<00:00,  8.20it/s]

tensor(12.0102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3670, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3696, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [08:57<00:00,  8.23it/s]

tensor(12.0082, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3703, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3694, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [08:57<00:00,  8.23it/s]

tensor(12.0060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3699, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3716, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [08:57<00:00,  8.22it/s]

tensor(12.0035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3741, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0023, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3747, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [08:58<00:00,  1.79s/it]

tensor(12.0010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3759, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0022125244140625
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 8
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.603200275331
NMI         : 0.608395446108
Runtime     : 585.16 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed8

==============================================================================================================
PRAGA RUN | E18.5 | seed=9
==============================================================================================================
E18.5: ATAC 161461 -> 161457 peaks (removed 4 zero-total peaks)
E18.5: scaled LSI shape = (2129, 50)
E18.5: max |column mean| = 4.668e-16
E18.5: sample std range = [1.000000, 1.000000]
E18.5: RNA feat = (2129, 50)
E18.5: ATAC feat = (2129, 50)
E18.5: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:32,  9.18it/s]

tensor(15.6271, device='cuda:0', grad_fn=<AddBackward0>) tensor(22.4793, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6368, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.2269, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:31,  9.47it/s]

tensor(15.6185, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.1965, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5930, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.3652, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:30,  9.62it/s]

tensor(15.5621, device='cuda:0', grad_fn=<AddBackward0>) tensor(14.7138, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5283, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.2251, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 7/300 [00:00<00:30,  9.55it/s]

tensor(15.4930, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.8830, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4564, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.6729, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.77it/s]

tensor(15.4210, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.5822, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3866, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.5987, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:29,  9.83it/s]

tensor(15.3535, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.7118, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3211, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.9128, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:29,  9.85it/s]

tensor(15.2890, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.1930, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2580, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.5442, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:29,  9.71it/s]

tensor(15.2274, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.9595, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1953, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.4333, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:28,  9.87it/s]

tensor(15.1632, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.9588, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1309, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.5315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0968, device='cuda:0', grad_fn=<AddBackward0>)

  7%|▋         | 20/300 [00:02<00:28,  9.70it/s]

tensor(3.1469, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0610, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.8004, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:02<00:28,  9.82it/s]

tensor(15.0241, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.4889, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9848, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2083, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9440, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.9561, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:27,  9.90it/s]

tensor(14.9017, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.7296, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8583, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5257, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:27,  9.88it/s]

tensor(14.8132, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.3431, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7680, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.1790, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7210, device='cuda:0', grad_fn=<AddBackward0>)

 10%|▉         | 29/300 [00:02<00:27,  9.74it/s]

tensor(1.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8995, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 31/300 [00:03<00:27,  9.87it/s]

tensor(14.6273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7810, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6759, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5351, device='cuda:0', grad_fn=<AddBackward0>)

 11%|█         | 33/300 [00:03<00:27,  9.88it/s]

tensor(0.5806, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4966, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:26,  9.86it/s]

tensor(14.4450, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3549, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 37/300 [00:03<00:26,  9.86it/s]

tensor(14.3564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2956, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2433, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2697, device='cuda:0', grad_fn=<AddBackward0>)

 13%|█▎        | 39/300 [00:03<00:26,  9.90it/s]

tensor(0.1974, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1579, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▎        | 41/300 [00:04<00:26,  9.69it/s]

tensor(14.1833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0939, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:26,  9.88it/s]

tensor(14.0972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0704, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0529, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:25,  9.86it/s]

tensor(14.0119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.90it/s]

tensor(13.8861, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:25,  9.88it/s]

tensor(13.8030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.84it/s]

tensor(13.7188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:24,  9.87it/s]

tensor(13.6331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:25,  9.70it/s]

tensor(13.5447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4999, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:24,  9.84it/s]

tensor(13.4547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:06<00:24,  9.86it/s]

tensor(13.3182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:24,  9.87it/s]

tensor(13.2259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:23,  9.86it/s]

tensor(13.1339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:23,  9.87it/s]

tensor(13.0435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:07<00:23,  9.85it/s]

tensor(12.9584, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:23,  9.73it/s]

tensor(12.8822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:23,  9.59it/s]

tensor(12.8179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7910, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:23,  9.46it/s]

tensor(12.7668, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 77/300 [00:07<00:23,  9.69it/s]

tensor(12.7255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:08<00:22,  9.79it/s]

tensor(12.6693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6502, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:22,  9.82it/s]

tensor(12.6303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:21,  9.83it/s]

tensor(12.5913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:22,  9.70it/s]

tensor(12.5554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:08<00:22,  9.56it/s]

tensor(12.5245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:21,  9.65it/s]

tensor(12.4966, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:21,  9.71it/s]

tensor(12.4703, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:21,  9.80it/s]

tensor(12.4433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:20,  9.80it/s]

tensor(12.4154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.4013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:10<00:21,  9.59it/s]

tensor(12.3872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:20,  9.57it/s]

tensor(12.3593, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.3457, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([330, 221,  83, 110, 288,  72, 104, 109,  59,  50,  63, 129,  94, 417])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 5/2129 [00:00<00:45, 46.98it/s]
  0%|          | 10/2129 [00:00<02:18, 15.27it/s]
  1%|          | 13/2129 [00:00<02:48, 12.52it/s]
  1%|          | 15/2129 [00:01<03:04, 11.43it/s]
  1%|          | 19/2129 [00:01<03:06, 11.30it/s]
  1%|          | 21/2129 [00:01<02:55, 11.99it/s]
  1%|          | 24/2129 [00:01<02:26, 14.39it/s]
  2%|▏         | 32/2129 [00:01<01:20, 26.16it/s]
  2%|▏         | 36/2129 [00:02<01:35, 21.94it/s]
  2%|▏         | 39/2129 [00:02<02:30, 13.89it/s]
  2%|▏         | 42/2129 [00:02<02:13, 15.68it/s]
  2%|▏         | 45/2129 [00:02<02:28, 14.00it/s]
  2%|▏         | 48/2129 [00:03<02:07, 16.26it/s]
  2%|▏         | 51/2129 [00:03<04:02,  8.56it/s]
  2%|▏         | 53/2129 [00:04<03:59,  8.67it/s]
  3%|▎         | 55/2129 [00:04<04:17,  8.05it/s]
  3%|▎         | 58/2129 [00:05<05:40,  6.08it/s]
  3%|▎         | 59/2129 [00:05<07:01,  4.91it/s]
  3%|▎         | 62/2129 [00:05<04:52,  7.06it/s]
  3%|▎         | 65/2129 [00:06<06:08,  5.60it/s]
  3%|▎         | 67/2129 [00:06<06:25,  5.34it/s]
  3%|▎         | 69/2129 [00:06<05:11,  6.61it/s]
  3%|▎         | 73/2129 [00:07<05:39,  6.05it/s]
  4%|▎         | 76/2129 [00:07<04:18,  7.95it/s]
  4%|▍         | 80/2129 [00:08<05:00,  6.82it/s]
  4%|▍         | 82/2129 [00:08<04:20,  7.84it/s]
  4%|▍         | 89/2129 [00:08<02:22, 14.34it/s]
  4%|▍         | 93/2129 [00:08<02:06, 16.06it/s]
  5%|▍         | 96/2129 [00:09<02:25, 14.00it/s]
  5%|▍         | 99/2129 [00:09<02:22, 14.21it/s]
  5%|▍         | 102/2129 [00:10<03:30,  9.64it/s]
  5%|▍         | 104/2129 [00:10<04:18,  7.84it/s]
  5%|▍         | 106/2129 [00:10<03:46,  8.95it/s]
  5%|▌         | 108/2129 [00:11<04:36,  7.31it/s]
  5%|▌         | 110/2129 [00:11<03:53,  8.63it/s]
  5%|▌         | 113/2129 [00:11<02:59, 11.23it/s]
  5%|▌         | 115/2129 [00:11<03:28,  9.67it/s]
  6%|▌         | 120/2129 [00:11<02:09, 15.49it/s]
  6%|▌         | 125/2129 [00:11<01:59, 16.74it/s]
  6%|▌         | 129/2129 [00:12<01:40, 19.81it/s]
  6%|▌         | 132/2129 [00:12<03:10, 10.46it/s]
  6%|▋         | 135/2129 [00:12<02:41, 12.36it/s]
  7%|▋         | 143/2129 [00:12<01:33, 21.20it/s]
  7%|▋         | 151/2129 [00:13<01:44, 18.93it/s]
  7%|▋         | 155/2129 [00:14<03:43,  8.81it/s]
  7%|▋         | 158/2129 [00:15<04:36,  7.13it/s]
  8%|▊         | 160/2129 [00:16<05:57,  5.51it/s]
  8%|▊         | 162/2129 [00:17<07:14,  4.53it/s]
  8%|▊         | 166/2129 [00:17<06:54,  4.73it/s]
  8%|▊         | 167/2129 [00:17<06:47,  4.81it/s]
  8%|▊         | 168/2129 [00:18<06:46,  4.83it/s]
  8%|▊         | 171/2129 [00:18<04:47,  6.81it/s]
  8%|▊         | 173/2129 [00:18<05:17,  6.17it/s]
  8%|▊         | 176/2129 [00:18<03:48,  8.55it/s]
  8%|▊         | 178/2129 [00:19<03:45,  8.64it/s]
  9%|▊         | 181/2129 [00:19<02:49, 11.46it/s]
  9%|▊         | 183/2129 [00:19<02:59, 10.85it/s]
  9%|▊         | 185/2129 [00:20<05:18,  6.10it/s]
  9%|▉         | 187/2129 [00:20<07:10,  4.51it/s]
  9%|▉         | 189/2129 [00:21<07:10,  4.51it/s]
  9%|▉         | 190/2129 [00:21<09:41,  3.33it/s]
  9%|▉         | 193/2129 [00:22<06:17,  5.12it/s]
  9%|▉         | 200/2129 [00:22<04:37,  6.96it/s]
  9%|▉         | 202/2129 [00:23<05:50,  5.50it/s]
 10%|▉         | 204/2129 [00:23<04:57,  6.47it/s]
 10%|▉         | 212/2129 [00:24<03:57,  8.08it/s]
 10%|█         | 214/2129 [00:25<05:21,  5.95it/s]
 10%|█         | 216/2129 [00:25<06:32,  4.88it/s]
 10%|█         | 218/2129 [00:26<05:34,  5.71it/s]
 10%|█         | 219/2129 [00:26<05:38,  5.65it/s]
 10%|█         | 220/2129 [00:26<08:13,  3.87it/s]
 10%|█         | 221/2129 [00:27<09:07,  3.48it/s]
 10%|█         | 223/2129 [00:28<09:58,  3.19it/s]
 11%|█         | 225/2129 [00:28<09:20,  3.40it/s]
 11%|█         | 228/2129 [00:28<05:58,  5.31it/s]
 11%|█         | 231/2129 [00:29<04:42,  6.72it/s]
 11%|█         | 233/2129 [00:29<05:17,  5.97it/s]
 11%|█         | 234/2129 [00:29<06:03,  5.22it/s]
 11%|█         | 237/2129 [00:29<04:07,  7.65it/s]
 11%|█         | 239/2129 [00:30<06:31,  4.82it/s]
 11%|█▏        | 241/2129 [00:30<05:08,  6.12it/s]
 11%|█▏        | 243/2129 [00:31<04:33,  6.90it/s]
 12%|█▏        | 246/2129 [00:31<05:40,  5.54it/s]
 12%|█▏        | 248/2129 [00:32<07:26,  4.21it/s]
 12%|█▏        | 250/2129 [00:33<08:46,  3.57it/s]
 12%|█▏        | 252/2129 [00:34<09:27,  3.31it/s]
 12%|█▏        | 255/2129 [00:34<07:42,  4.06it/s]
 12%|█▏        | 257/2129 [00:34<06:04,  5.14it/s]
 12%|█▏        | 258/2129 [00:35<08:33,  3.64it/s]
 12%|█▏        | 259/2129 [00:35<09:14,  3.37it/s]
 12%|█▏        | 260/2129 [00:35<08:35,  3.62it/s]
 12%|█▏        | 261/2129 [00:36<11:39,  2.67it/s]
 12%|█▏        | 264/2129 [00:36<06:34,  4.73it/s]
 13%|█▎        | 267/2129 [00:37<07:15,  4.27it/s]
 13%|█▎        | 271/2129 [00:38<05:52,  5.27it/s]
 13%|█▎        | 273/2129 [00:38<05:39,  5.46it/s]
 13%|█▎        | 275/2129 [00:39<06:59,  4.42it/s]
 13%|█▎        | 279/2129 [00:39<04:24,  7.00it/s]
 13%|█▎        | 281/2129 [00:39<04:52,  6.32it/s]
 13%|█▎        | 283/2129 [00:40<05:13,  5.89it/s]
 13%|█▎        | 286/2129 [00:40<03:51,  7.97it/s]
 14%|█▎        | 288/2129 [00:40<05:32,  5.54it/s]
 14%|█▎        | 292/2129 [00:41<05:32,  5.53it/s]
 14%|█▍        | 294/2129 [00:42<06:38,  4.60it/s]
 14%|█▍        | 296/2129 [00:42<07:45,  3.94it/s]
 14%|█▍        | 298/2129 [00:43<07:28,  4.08it/s]
 14%|█▍        | 299/2129 [00:43<06:47,  4.49it/s]
 14%|█▍        | 304/2129 [00:44<05:22,  5.66it/s]
 14%|█▍        | 305/2129 [00:44<07:13,  4.21it/s]
 14%|█▍        | 307/2129 [00:44<05:43,  5.30it/s]
 15%|█▍        | 312/2129 [00:45<03:44,  8.08it/s]
 15%|█▍        | 314/2129 [00:45<05:25,  5.58it/s]
 15%|█▍        | 316/2129 [00:46<04:39,  6.48it/s]
 15%|█▍        | 318/2129 [00:46<04:34,  6.60it/s]
 15%|█▌        | 320/2129 [00:46<03:57,  7.61it/s]
 15%|█▌        | 322/2129 [00:46<03:22,  8.91it/s]
 15%|█▌        | 324/2129 [00:46<03:42,  8.12it/s]
 15%|█▌        | 327/2129 [00:47<02:44, 10.94it/s]
 15%|█▌        | 329/2129 [00:47<03:56,  7.60it/s]
 16%|█▌        | 331/2129 [00:48<07:00,  4.28it/s]
 16%|█▌        | 333/2129 [00:48<05:30,  5.44it/s]
 16%|█▌        | 335/2129 [00:49<07:03,  4.23it/s]
 16%|█▌        | 337/2129 [00:50<08:25,  3.55it/s]
 16%|█▌        | 340/2129 [00:50<05:40,  5.26it/s]
 16%|█▌        | 342/2129 [00:50<06:30,  4.57it/s]
 16%|█▌        | 343/2129 [00:51<08:37,  3.45it/s]
 16%|█▌        | 345/2129 [00:51<07:13,  4.11it/s]
 16%|█▋        | 348/2129 [00:52<04:49,  6.16it/s]
 16%|█▋        | 350/2129 [00:53<09:05,  3.26it/s]
 17%|█▋        | 353/2129 [00:53<06:12,  4.77it/s]
 17%|█▋        | 355/2129 [00:54<09:50,  3.00it/s]
 17%|█▋        | 356/2129 [00:55<11:36,  2.54it/s]
 17%|█▋        | 357/2129 [00:55<10:42,  2.76it/s]
 17%|█▋        | 358/2129 [00:56<09:44,  3.03it/s]
 17%|█▋        | 361/2129 [00:56<06:28,  4.55it/s]
 17%|█▋        | 362/2129 [00:56<07:27,  3.95it/s]
 17%|█▋        | 364/2129 [00:56<05:26,  5.41it/s]
 17%|█▋        | 369/2129 [00:56<02:52, 10.18it/s]
 18%|█▊        | 373/2129 [00:57<03:46,  7.74it/s]
 18%|█▊        | 375/2129 [00:57<03:40,  7.95it/s]
 18%|█▊        | 377/2129 [00:58<05:24,  5.40it/s]
 18%|█▊        | 380/2129 [00:59<06:02,  4.82it/s]
 18%|█▊        | 383/2129 [00:59<04:29,  6.48it/s]
 18%|█▊        | 385/2129 [01:00<05:52,  4.94it/s]
 18%|█▊        | 386/2129 [01:00<07:50,  3.71it/s]
 18%|█▊        | 389/2129 [01:01<05:18,  5.46it/s]
 18%|█▊        | 391/2129 [01:01<06:36,  4.39it/s]
 18%|█▊        | 392/2129 [01:02<07:20,  3.94it/s]
 18%|█▊        | 393/2129 [01:02<08:06,  3.57it/s]
 19%|█▊        | 394/2129 [01:03<10:52,  2.66it/s]
 19%|█▊        | 397/2129 [01:03<06:12,  4.65it/s]
 19%|█▉        | 400/2129 [01:03<05:22,  5.36it/s]
 19%|█▉        | 402/2129 [01:03<04:18,  6.69it/s]
 19%|█▉        | 404/2129 [01:04<05:55,  4.86it/s]
 19%|█▉        | 405/2129 [01:05<08:09,  3.52it/s]
 19%|█▉        | 406/2129 [01:05<07:43,  3.71it/s]
 19%|█▉        | 407/2129 [01:05<07:15,  3.95it/s]
 19%|█▉        | 408/2129 [01:06<10:09,  2.82it/s]
 19%|█▉        | 410/2129 [01:06<06:45,  4.24it/s]
 19%|█▉        | 413/2129 [01:06<05:35,  5.11it/s]
 19%|█▉        | 415/2129 [01:07<05:57,  4.79it/s]
 20%|█▉        | 418/2129 [01:07<04:04,  7.00it/s]
 20%|█▉        | 420/2129 [01:08<05:54,  4.82it/s]
 20%|█▉        | 422/2129 [01:08<05:56,  4.79it/s]
 20%|█▉        | 424/2129 [01:08<04:38,  6.11it/s]
 20%|██        | 430/2129 [01:09<02:45, 10.29it/s]
 20%|██        | 432/2129 [01:09<04:20,  6.50it/s]
 20%|██        | 434/2129 [01:10<05:49,  4.84it/s]
 20%|██        | 436/2129 [01:11<06:55,  4.07it/s]
 21%|██        | 438/2129 [01:11<05:30,  5.11it/s]
 21%|██        | 440/2129 [01:12<06:50,  4.12it/s]
 21%|██        | 443/2129 [01:12<04:40,  6.00it/s]
 21%|██        | 450/2129 [01:12<02:19, 12.02it/s]
 21%|██▏       | 453/2129 [01:13<04:36,  6.07it/s]
 21%|██▏       | 456/2129 [01:14<05:40,  4.91it/s]
 22%|██▏       | 458/2129 [01:15<06:38,  4.20it/s]
 22%|██▏       | 460/2129 [01:16<07:38,  3.64it/s]
 22%|██▏       | 463/2129 [01:16<05:27,  5.08it/s]
 22%|██▏       | 466/2129 [01:16<05:46,  4.80it/s]
 22%|██▏       | 468/2129 [01:17<07:09,  3.87it/s]
 22%|██▏       | 471/2129 [01:18<07:09,  3.86it/s]
 22%|██▏       | 474/2129 [01:18<05:09,  5.34it/s]
 22%|██▏       | 476/2129 [01:18<04:44,  5.81it/s]
 22%|██▏       | 478/2129 [01:20<08:14,  3.34it/s]
 23%|██▎       | 480/2129 [01:20<06:25,  4.27it/s]
 23%|██▎       | 482/2129 [01:20<05:37,  4.88it/s]
 23%|██▎       | 484/2129 [01:22<09:24,  2.91it/s]
 23%|██▎       | 486/2129 [01:22<07:38,  3.58it/s]
 23%|██▎       | 487/2129 [01:22<07:21,  3.72it/s]
 23%|██▎       | 488/2129 [01:22<08:11,  3.34it/s]
 23%|██▎       | 490/2129 [01:23<08:30,  3.21it/s]
 23%|██▎       | 492/2129 [01:23<06:10,  4.42it/s]
 23%|██▎       | 494/2129 [01:24<06:10,  4.42it/s]
 23%|██▎       | 498/2129 [01:24<03:32,  7.66it/s]
 24%|██▎       | 501/2129 [01:24<03:39,  7.42it/s]
 24%|██▎       | 503/2129 [01:24<03:47,  7.16it/s]
 24%|██▎       | 505/2129 [01:25<03:13,  8.38it/s]
 24%|██▍       | 508/2129 [01:25<04:16,  6.31it/s]
 24%|██▍       | 510/2129 [01:25<03:50,  7.01it/s]
 24%|██▍       | 512/2129 [01:26<03:40,  7.34it/s]
 24%|██▍       | 515/2129 [01:26<03:24,  7.89it/s]
 24%|██▍       | 517/2129 [01:27<04:18,  6.25it/s]
 24%|██▍       | 519/2129 [01:27<04:16,  6.27it/s]
 24%|██▍       | 520/2129 [01:27<05:51,  4.58it/s]
 24%|██▍       | 521/2129 [01:28<06:23,  4.20it/s]
 25%|██▍       | 522/2129 [01:28<05:47,  4.62it/s]
 25%|██▍       | 524/2129 [01:28<04:12,  6.36it/s]
 25%|██▍       | 526/2129 [01:28<04:40,  5.71it/s]
 25%|██▍       | 527/2129 [01:29<04:54,  5.43it/s]
 25%|██▍       | 528/2129 [01:29<06:39,  4.01it/s]
 25%|██▍       | 529/2129 [01:30<07:40,  3.47it/s]
 25%|██▍       | 530/2129 [01:30<07:01,  3.80it/s]
 25%|██▌       | 533/2129 [01:30<03:54,  6.80it/s]
 25%|██▌       | 535/2129 [01:30<03:19,  7.98it/s]
 25%|██▌       | 537/2129 [01:31<04:55,  5.39it/s]
 25%|██▌       | 539/2129 [01:31<04:35,  5.76it/s]
 25%|██▌       | 542/2129 [01:31<03:10,  8.31it/s]
 26%|██▌       | 544/2129 [01:31<03:24,  7.75it/s]
 26%|██▌       | 546/2129 [01:32<04:16,  6.16it/s]
 26%|██▌       | 547/2129 [01:32<06:30,  4.05it/s]
 26%|██▌       | 548/2129 [01:33<07:16,  3.62it/s]
 26%|██▌       | 550/2129 [01:33<05:12,  5.05it/s]
 26%|██▌       | 552/2129 [01:33<03:53,  6.75it/s]
 26%|██▌       | 554/2129 [01:34<05:10,  5.07it/s]
 26%|██▌       | 557/2129 [01:34<04:16,  6.13it/s]
 26%|██▋       | 559/2129 [01:34<04:29,  5.83it/s]
 26%|██▋       | 562/2129 [01:35<03:23,  7.70it/s]
 26%|██▋       | 564/2129 [01:35<03:49,  6.81it/s]
 27%|██▋       | 567/2129 [01:35<03:47,  6.86it/s]
 27%|██▋       | 570/2129 [01:36<02:50,  9.14it/s]
 27%|██▋       | 572/2129 [01:36<03:45,  6.89it/s]
 27%|██▋       | 575/2129 [01:36<02:46,  9.31it/s]
 27%|██▋       | 577/2129 [01:36<02:42,  9.57it/s]
 27%|██▋       | 580/2129 [01:36<02:06, 12.24it/s]
 27%|██▋       | 582/2129 [01:37<03:32,  7.29it/s]
 27%|██▋       | 584/2129 [01:38<05:03,  5.09it/s]
 28%|██▊       | 586/2129 [01:38<05:13,  4.92it/s]
 28%|██▊       | 587/2129 [01:39<05:50,  4.40it/s]
 28%|██▊       | 589/2129 [01:39<05:03,  5.08it/s]
 28%|██▊       | 590/2129 [01:39<06:17,  4.07it/s]
 28%|██▊       | 592/2129 [01:39<04:36,  5.55it/s]
 28%|██▊       | 593/2129 [01:40<06:17,  4.07it/s]
 28%|██▊       | 596/2129 [01:40<04:00,  6.39it/s]
 28%|██▊       | 599/2129 [01:41<03:44,  6.82it/s]
 28%|██▊       | 601/2129 [01:41<03:09,  8.08it/s]
 28%|██▊       | 603/2129 [01:42<05:28,  4.64it/s]
 28%|██▊       | 604/2129 [01:42<06:14,  4.08it/s]
 28%|██▊       | 605/2129 [01:42<05:56,  4.27it/s]
 29%|██▊       | 607/2129 [01:42<04:28,  5.67it/s]
 29%|██▊       | 609/2129 [01:42<03:28,  7.30it/s]
 29%|██▊       | 611/2129 [01:43<06:49,  3.71it/s]
 29%|██▉       | 613/2129 [01:44<06:21,  3.97it/s]
 29%|██▉       | 614/2129 [01:44<05:55,  4.26it/s]
 29%|██▉       | 617/2129 [01:44<03:41,  6.82it/s]
 29%|██▉       | 619/2129 [01:44<03:28,  7.25it/s]
 29%|██▉       | 621/2129 [01:44<02:48,  8.94it/s]
 29%|██▉       | 623/2129 [01:45<02:53,  8.66it/s]
 29%|██▉       | 626/2129 [01:45<04:12,  5.96it/s]
 29%|██▉       | 628/2129 [01:46<05:38,  4.43it/s]
 30%|██▉       | 631/2129 [01:46<04:17,  5.81it/s]
 30%|██▉       | 632/2129 [01:47<06:17,  3.96it/s]
 30%|██▉       | 633/2129 [01:47<06:08,  4.06it/s]
 30%|██▉       | 635/2129 [01:48<04:31,  5.51it/s]
 30%|██▉       | 637/2129 [01:48<05:58,  4.16it/s]
 30%|███       | 641/2129 [01:49<05:21,  4.63it/s]
 30%|███       | 643/2129 [01:49<05:30,  4.50it/s]
 30%|███       | 644/2129 [01:50<07:29,  3.30it/s]
 30%|███       | 648/2129 [01:50<04:19,  5.70it/s]
 31%|███       | 650/2129 [01:51<05:26,  4.53it/s]
 31%|███       | 652/2129 [01:51<05:03,  4.86it/s]
 31%|███       | 653/2129 [01:52<06:54,  3.56it/s]
 31%|███       | 655/2129 [01:53<06:27,  3.80it/s]
 31%|███       | 656/2129 [01:53<06:46,  3.63it/s]
 31%|███       | 657/2129 [01:53<07:12,  3.41it/s]
 31%|███       | 658/2129 [01:54<08:50,  2.78it/s]
 31%|███       | 659/2129 [01:54<07:44,  3.16it/s]
 31%|███       | 661/2129 [01:55<08:13,  2.97it/s]
 31%|███       | 662/2129 [01:55<07:31,  3.25it/s]
 31%|███       | 663/2129 [01:55<09:03,  2.70it/s]
 31%|███       | 664/2129 [01:56<09:07,  2.68it/s]
 31%|███▏      | 667/2129 [01:57<07:16,  3.35it/s]
 31%|███▏      | 669/2129 [01:57<05:15,  4.63it/s]
 31%|███▏      | 670/2129 [01:57<05:52,  4.14it/s]
 32%|███▏      | 672/2129 [01:58<06:39,  3.65it/s]
 32%|███▏      | 673/2129 [01:58<06:22,  3.80it/s]
 32%|███▏      | 674/2129 [01:58<06:19,  3.84it/s]
 32%|███▏      | 676/2129 [01:58<04:21,  5.55it/s]
 32%|███▏      | 677/2129 [01:59<05:12,  4.64it/s]
 32%|███▏      | 679/2129 [01:59<03:48,  6.33it/s]
 32%|███▏      | 680/2129 [01:59<04:06,  5.87it/s]
 32%|███▏      | 682/2129 [01:59<03:01,  7.98it/s]
 32%|███▏      | 684/2129 [02:00<04:55,  4.89it/s]
 32%|███▏      | 685/2129 [02:00<05:13,  4.60it/s]
 32%|███▏      | 687/2129 [02:00<03:53,  6.18it/s]
 32%|███▏      | 688/2129 [02:01<05:05,  4.72it/s]
 32%|███▏      | 689/2129 [02:01<05:34,  4.31it/s]
 32%|███▏      | 691/2129 [02:01<03:50,  6.23it/s]
 33%|███▎      | 693/2129 [02:01<04:37,  5.18it/s]
 33%|███▎      | 694/2129 [02:02<06:24,  3.73it/s]
 33%|███▎      | 696/2129 [02:03<07:02,  3.39it/s]
 33%|███▎      | 698/2129 [02:03<05:01,  4.75it/s]
 33%|███▎      | 701/2129 [02:03<03:18,  7.19it/s]
 33%|███▎      | 703/2129 [02:04<04:56,  4.82it/s]
 33%|███▎      | 705/2129 [02:04<05:53,  4.03it/s]
 33%|███▎      | 707/2129 [02:05<06:42,  3.53it/s]
 33%|███▎      | 708/2129 [02:06<08:19,  2.85it/s]
 33%|███▎      | 709/2129 [02:06<07:35,  3.12it/s]
 33%|███▎      | 711/2129 [02:06<05:16,  4.48it/s]
 33%|███▎      | 712/2129 [02:07<07:19,  3.22it/s]
 33%|███▎      | 713/2129 [02:07<09:20,  2.52it/s]
 34%|███▎      | 716/2129 [02:08<05:13,  4.51it/s]
 34%|███▍      | 719/2129 [02:08<04:10,  5.62it/s]
 34%|███▍      | 721/2129 [02:09<05:19,  4.40it/s]
 34%|███▍      | 723/2129 [02:09<06:07,  3.83it/s]
 34%|███▍      | 724/2129 [02:10<07:33,  3.10it/s]
 34%|███▍      | 725/2129 [02:11<08:58,  2.61it/s]
 34%|███▍      | 726/2129 [02:11<10:23,  2.25it/s]
 34%|███▍      | 727/2129 [02:12<11:27,  2.04it/s]
 34%|███▍      | 728/2129 [02:13<12:23,  1.89it/s]
 34%|███▍      | 730/2129 [02:13<09:30,  2.45it/s]
 34%|███▍      | 732/2129 [02:13<06:29,  3.59it/s]
 34%|███▍      | 733/2129 [02:14<07:31,  3.09it/s]
 34%|███▍      | 734/2129 [02:14<07:34,  3.07it/s]
 35%|███▍      | 736/2129 [02:14<05:01,  4.61it/s]
 35%|███▍      | 737/2129 [02:14<04:56,  4.69it/s]
 35%|███▍      | 738/2129 [02:14<04:44,  4.89it/s]
 35%|███▍      | 739/2129 [02:15<07:43,  3.00it/s]
 35%|███▍      | 740/2129 [02:15<06:43,  3.44it/s]
 35%|███▍      | 741/2129 [02:16<07:40,  3.02it/s]
 35%|███▍      | 742/2129 [02:16<06:41,  3.45it/s]
 35%|███▍      | 745/2129 [02:16<03:34,  6.46it/s]
 35%|███▌      | 749/2129 [02:16<02:22,  9.66it/s]
 35%|███▌      | 751/2129 [02:17<03:56,  5.82it/s]
 35%|███▌      | 752/2129 [02:18<05:42,  4.02it/s]
 35%|███▌      | 753/2129 [02:18<07:34,  3.03it/s]
 35%|███▌      | 754/2129 [02:19<09:19,  2.46it/s]
 35%|███▌      | 755/2129 [02:20<10:49,  2.11it/s]
 36%|███▌      | 757/2129 [02:20<06:58,  3.28it/s]
 36%|███▌      | 758/2129 [02:20<06:32,  3.50it/s]
 36%|███▌      | 761/2129 [02:20<03:46,  6.03it/s]
 36%|███▌      | 763/2129 [02:21<07:22,  3.09it/s]
 36%|███▌      | 765/2129 [02:22<06:01,  3.78it/s]
 36%|███▌      | 766/2129 [02:22<07:45,  2.93it/s]
 36%|███▌      | 767/2129 [02:23<08:02,  2.82it/s]
 36%|███▌      | 769/2129 [02:23<07:28,  3.03it/s]
 36%|███▌      | 771/2129 [02:24<05:21,  4.23it/s]
 36%|███▋      | 772/2129 [02:24<05:17,  4.28it/s]
 36%|███▋      | 774/2129 [02:24<05:36,  4.02it/s]
 36%|███▋      | 775/2129 [02:25<06:13,  3.63it/s]
 36%|███▋      | 776/2129 [02:25<05:30,  4.09it/s]
 37%|███▋      | 778/2129 [02:25<03:49,  5.89it/s]
 37%|███▋      | 780/2129 [02:26<05:34,  4.04it/s]
 37%|███▋      | 781/2129 [02:26<05:24,  4.15it/s]
 37%|███▋      | 782/2129 [02:27<07:43,  2.91it/s]
 37%|███▋      | 784/2129 [02:27<06:30,  3.45it/s]
 37%|███▋      | 785/2129 [02:28<08:26,  2.66it/s]
 37%|███▋      | 787/2129 [02:28<06:19,  3.54it/s]
 37%|███▋      | 790/2129 [02:28<03:51,  5.78it/s]
 37%|███▋      | 795/2129 [02:28<02:25,  9.19it/s]
 37%|███▋      | 797/2129 [02:29<03:41,  6.02it/s]
 38%|███▊      | 799/2129 [02:30<04:56,  4.49it/s]
 38%|███▊      | 800/2129 [02:31<06:27,  3.43it/s]
 38%|███▊      | 802/2129 [02:31<06:59,  3.16it/s]
 38%|███▊      | 803/2129 [02:32<08:28,  2.61it/s]
 38%|███▊      | 805/2129 [02:33<07:31,  2.93it/s]
 38%|███▊      | 806/2129 [02:33<07:45,  2.84it/s]
 38%|███▊      | 808/2129 [02:33<05:24,  4.07it/s]
 38%|███▊      | 809/2129 [02:34<07:21,  2.99it/s]
 38%|███▊      | 810/2129 [02:34<08:56,  2.46it/s]
 38%|███▊      | 812/2129 [02:35<07:16,  3.02it/s]
 38%|███▊      | 813/2129 [02:35<08:51,  2.48it/s]
 38%|███▊      | 814/2129 [02:36<07:47,  2.82it/s]
 38%|███▊      | 816/2129 [02:36<05:04,  4.31it/s]
 38%|███▊      | 818/2129 [02:37<06:20,  3.44it/s]
 39%|███▊      | 820/2129 [02:37<06:56,  3.14it/s]
 39%|███▊      | 821/2129 [02:38<07:23,  2.95it/s]
 39%|███▊      | 824/2129 [02:38<04:24,  4.93it/s]
 39%|███▉      | 827/2129 [02:38<03:15,  6.66it/s]
 39%|███▉      | 830/2129 [02:38<02:24,  9.01it/s]
 39%|███▉      | 832/2129 [02:39<03:32,  6.10it/s]
 39%|███▉      | 834/2129 [02:39<02:55,  7.38it/s]
 39%|███▉      | 836/2129 [02:39<02:48,  7.67it/s]
 39%|███▉      | 838/2129 [02:40<04:21,  4.94it/s]
 40%|███▉      | 841/2129 [02:40<04:01,  5.33it/s]
 40%|███▉      | 842/2129 [02:41<04:01,  5.33it/s]
 40%|███▉      | 843/2129 [02:41<05:47,  3.70it/s]
 40%|███▉      | 844/2129 [02:42<07:36,  2.82it/s]
 40%|███▉      | 846/2129 [02:43<07:30,  2.85it/s]
 40%|███▉      | 848/2129 [02:43<06:02,  3.54it/s]
 40%|███▉      | 849/2129 [02:43<05:35,  3.81it/s]
 40%|███▉      | 851/2129 [02:43<04:03,  5.26it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 327.01it/s]
 34%|███▎      | 101/300 [07:24<7:11:56, 130.23s/it]

[[np.int64(0), False, 13], [np.int64(1), False, 4], [np.int64(2), False, 7], [np.int64(3), False, 13], [np.int64(4), False, 0], [np.int64(5), False, 4], [np.int64(6), False, 8], [np.int64(7), False, 1], [np.int64(8), False, 13], [np.int64(9), False, 1], [np.int64(10), False, 4], [np.int64(11), False, 8], [np.int64(12), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.4806, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [07:24<5:00:58, 91.21s/it]

tensor(12.3233, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6165, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.8616, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [07:24<1:41:55, 31.36s/it]

tensor(12.3510, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1240, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3578, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [07:24<49:38, 15.43s/it]

tensor(12.4350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5312, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6634, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [07:24<34:40, 10.84s/it]

tensor(12.5167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7732, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8777, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [07:25<11:57,  3.80s/it]

tensor(12.5676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9913, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0846, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [07:25<08:26,  2.69s/it]

tensor(12.5761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1466, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2010, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [07:25<04:17,  1.38s/it]

tensor(12.5300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2365, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2656, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [07:25<02:16,  1.35it/s]

tensor(12.4259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2855, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3071, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [07:26<01:17,  2.35it/s]

tensor(12.3189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3468, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [07:26<00:40,  4.41it/s]

tensor(12.2620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3358, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3542, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [07:26<00:35,  5.07it/s]

tensor(12.2368, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3741, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3913, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [07:26<00:28,  6.26it/s]

tensor(12.2127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4266, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4547, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [07:27<00:23,  7.44it/s]

tensor(12.1856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4910, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5274, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [07:27<00:21,  7.83it/s]

tensor(12.1626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5658, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5904, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [07:27<00:21,  7.93it/s]

tensor(12.1465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6216, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6468, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [07:27<00:21,  7.66it/s]

tensor(12.1311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6654, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6901, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [07:28<00:20,  8.00it/s]

tensor(12.1112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7073, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0994, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7224, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [07:28<00:19,  8.29it/s]

tensor(12.0871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7448, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0750, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7614, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [07:28<00:19,  8.33it/s]

tensor(12.0635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7800, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7982, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [07:29<00:19,  8.28it/s]

tensor(12.0416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8115, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8351, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [07:29<00:19,  8.17it/s]

tensor(12.0197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8736, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [07:29<00:19,  8.18it/s]

tensor(11.9996, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8935, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [07:29<00:18,  8.26it/s]

tensor(11.9840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9175, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9395, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [07:30<00:18,  8.26it/s]

tensor(11.9714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9541, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9671, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [07:30<00:18,  8.25it/s]

tensor(11.9595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9856, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([292,  43, 202, 171,  84, 123, 128, 215,  82, 116, 457,  66,  69,  81])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:18, 27.15it/s]
  0%|          | 7/2129 [00:00<01:37, 21.80it/s]
  0%|          | 10/2129 [00:00<01:28, 23.90it/s]
  1%|          | 13/2129 [00:00<02:16, 15.48it/s]
  1%|          | 15/2129 [00:00<02:10, 16.20it/s]
  1%|          | 22/2129 [00:00<01:15, 27.98it/s]
  1%|▏         | 30/2129 [00:01<00:52, 39.81it/s]
  2%|▏         | 35/2129 [00:01<01:12, 28.74it/s]
  2%|▏         | 39/2129 [00:01<01:12, 28.67it/s]
  2%|▏         | 43/2129 [00:01<01:40, 20.70it/s]
  2%|▏         | 46/2129 [00:01<01:38, 21.18it/s]
  2%|▏         | 52/2129 [00:02<01:48, 19.21it/s]
  3%|▎         | 55/2129 [00:02<01:42, 20.29it/s]
  3%|▎         | 63/2129 [00:02<01:08, 30.10it/s]
  3%|▎         | 67/2129 [00:03<01:55, 17.89it/s]
  3%|▎         | 71/2129 [00:03<01:39, 20.60it/s]
  4%|▎         | 75/2129 [00:03<01:30, 22.71it/s]
  4%|▎         | 79/2129 [00:03<01:19, 25.68it/s]
  4%|▍         | 83/2129 [00:03<02:12, 15.38it/s]
  4%|▍         | 88/2129 [00:04<01:42, 19.89it/s]
  4%|▍         | 93/2129 [00:04<01:26, 23.64it/s]
  5%|▍         | 99/2129 [00:04<01:07, 30.13it/s]
  5%|▍         | 104/2129 [00:05<02:25, 13.92it/s]
  5%|▌         | 108/2129 [00:05<02:01, 16.62it/s]
  5%|▌         | 114/2129 [00:05<01:31, 22.05it/s]
  6%|▌         | 121/2129 [00:05<01:09, 29.01it/s]
  6%|▌         | 128/2129 [00:05<00:55, 36.24it/s]
  6%|▋         | 136/2129 [00:05<00:45, 43.77it/s]
  7%|▋         | 144/2129 [00:05<00:39, 50.20it/s]
  7%|▋         | 151/2129 [00:05<00:37, 52.66it/s]
  7%|▋         | 158/2129 [00:06<01:09, 28.45it/s]
  8%|▊         | 163/2129 [00:06<01:43, 19.01it/s]
  8%|▊         | 171/2129 [00:06<01:16, 25.72it/s]
  8%|▊         | 176/2129 [00:07<01:35, 20.42it/s]
  8%|▊         | 180/2129 [00:07<02:03, 15.76it/s]
  9%|▊         | 184/2129 [00:08<02:30, 12.96it/s]
  9%|▉         | 187/2129 [00:08<02:13, 14.59it/s]
  9%|▉         | 190/2129 [00:08<02:51, 11.33it/s]
  9%|▉         | 192/2129 [00:09<02:41, 12.02it/s]
  9%|▉         | 200/2129 [00:09<02:21, 13.61it/s]
  9%|▉         | 202/2129 [00:10<03:14,  9.91it/s]
 10%|▉         | 204/2129 [00:10<02:57, 10.85it/s]
 10%|▉         | 208/2129 [00:10<02:15, 14.21it/s]
 10%|▉         | 212/2129 [00:10<02:16, 14.02it/s]
 10%|█         | 214/2129 [00:10<02:52, 11.09it/s]
 10%|█         | 217/2129 [00:11<02:22, 13.46it/s]
 10%|█         | 220/2129 [00:11<01:59, 16.01it/s]
 10%|█         | 223/2129 [00:11<02:49, 11.22it/s]
 11%|█         | 225/2129 [00:11<02:34, 12.29it/s]
 11%|█         | 231/2129 [00:11<01:35, 19.78it/s]
 11%|█         | 234/2129 [00:12<03:33,  8.88it/s]
 11%|█         | 237/2129 [00:12<02:56, 10.71it/s]
 11%|█▏        | 240/2129 [00:13<03:29,  9.02it/s]
 11%|█▏        | 243/2129 [00:13<03:37,  8.67it/s]
 12%|█▏        | 245/2129 [00:13<03:12,  9.77it/s]
 12%|█▏        | 247/2129 [00:14<04:22,  7.16it/s]
 12%|█▏        | 249/2129 [00:14<05:09,  6.08it/s]
 12%|█▏        | 252/2129 [00:15<05:18,  5.89it/s]
 12%|█▏        | 255/2129 [00:15<03:58,  7.85it/s]
 12%|█▏        | 258/2129 [00:15<04:16,  7.30it/s]
 12%|█▏        | 260/2129 [00:16<04:44,  6.58it/s]
 12%|█▏        | 261/2129 [00:16<05:59,  5.19it/s]
 12%|█▏        | 265/2129 [00:16<03:42,  8.38it/s]
 13%|█▎        | 267/2129 [00:17<04:28,  6.93it/s]
 13%|█▎        | 270/2129 [00:17<03:21,  9.23it/s]
 13%|█▎        | 273/2129 [00:17<03:04, 10.08it/s]
 13%|█▎        | 275/2129 [00:18<04:11,  7.38it/s]
 13%|█▎        | 278/2129 [00:18<03:11,  9.65it/s]
 13%|█▎        | 280/2129 [00:18<03:33,  8.67it/s]
 13%|█▎        | 283/2129 [00:18<02:45, 11.17it/s]
 13%|█▎        | 287/2129 [00:19<03:06,  9.90it/s]
 14%|█▎        | 290/2129 [00:19<02:30, 12.22it/s]
 14%|█▎        | 292/2129 [00:19<03:28,  8.81it/s]
 14%|█▍        | 296/2129 [00:19<02:29, 12.26it/s]
 14%|█▍        | 298/2129 [00:20<03:01, 10.09it/s]
 14%|█▍        | 300/2129 [00:20<02:40, 11.36it/s]
 14%|█▍        | 304/2129 [00:20<02:59, 10.16it/s]
 14%|█▍        | 306/2129 [00:21<03:23,  8.96it/s]
 15%|█▍        | 309/2129 [00:21<03:38,  8.34it/s]
 15%|█▍        | 311/2129 [00:21<03:13,  9.41it/s]
 15%|█▍        | 313/2129 [00:22<05:44,  5.26it/s]
 15%|█▍        | 314/2129 [00:22<06:14,  4.84it/s]
 15%|█▍        | 317/2129 [00:22<04:17,  7.04it/s]
 15%|█▌        | 320/2129 [00:23<03:56,  7.65it/s]
 15%|█▌        | 323/2129 [00:23<02:58, 10.14it/s]
 15%|█▌        | 325/2129 [00:23<04:11,  7.18it/s]
 15%|█▌        | 328/2129 [00:24<04:30,  6.66it/s]
 16%|█▌        | 330/2129 [00:24<03:50,  7.81it/s]
 16%|█▌        | 332/2129 [00:24<03:14,  9.25it/s]
 16%|█▌        | 334/2129 [00:25<04:49,  6.19it/s]
 16%|█▌        | 337/2129 [00:25<05:08,  5.81it/s]
 16%|█▌        | 339/2129 [00:25<04:21,  6.83it/s]
 16%|█▌        | 342/2129 [00:26<03:47,  7.85it/s]
 16%|█▌        | 344/2129 [00:26<03:47,  7.85it/s]
 16%|█▌        | 345/2129 [00:26<04:26,  6.70it/s]
 16%|█▋        | 347/2129 [00:26<03:34,  8.31it/s]
 16%|█▋        | 350/2129 [00:27<03:59,  7.43it/s]
 17%|█▋        | 352/2129 [00:27<03:26,  8.60it/s]
 17%|█▋        | 354/2129 [00:27<02:53, 10.21it/s]
 17%|█▋        | 356/2129 [00:28<05:49,  5.07it/s]
 17%|█▋        | 358/2129 [00:29<07:59,  3.69it/s]
 17%|█▋        | 361/2129 [00:29<06:55,  4.26it/s]
 17%|█▋        | 362/2129 [00:30<07:48,  3.77it/s]
 17%|█▋        | 365/2129 [00:30<05:14,  5.60it/s]
 17%|█▋        | 368/2129 [00:30<03:46,  7.79it/s]
 18%|█▊        | 373/2129 [00:31<03:15,  8.96it/s]
 18%|█▊        | 375/2129 [00:31<03:47,  7.72it/s]
 18%|█▊        | 377/2129 [00:31<04:32,  6.42it/s]
 18%|█▊        | 380/2129 [00:32<04:35,  6.34it/s]
 18%|█▊        | 382/2129 [00:32<03:51,  7.56it/s]
 18%|█▊        | 384/2129 [00:32<04:29,  6.48it/s]
 18%|█▊        | 386/2129 [00:33<05:01,  5.77it/s]
 18%|█▊        | 388/2129 [00:33<04:07,  7.03it/s]
 18%|█▊        | 391/2129 [00:33<04:00,  7.23it/s]
 18%|█▊        | 392/2129 [00:34<04:36,  6.28it/s]
 19%|█▊        | 395/2129 [00:34<03:17,  8.76it/s]
 19%|█▉        | 400/2129 [00:34<03:12,  8.98it/s]
 19%|█▉        | 402/2129 [00:34<02:50, 10.13it/s]
 19%|█▉        | 405/2129 [00:35<03:32,  8.13it/s]
 19%|█▉        | 407/2129 [00:35<03:44,  7.67it/s]
 19%|█▉        | 408/2129 [00:36<04:04,  7.04it/s]
 19%|█▉        | 411/2129 [00:36<03:05,  9.27it/s]
 19%|█▉        | 414/2129 [00:36<02:30, 11.37it/s]
 20%|█▉        | 419/2129 [00:36<01:39, 17.23it/s]
 20%|█▉        | 425/2129 [00:36<01:09, 24.54it/s]
 20%|██        | 430/2129 [00:36<01:19, 21.43it/s]
 20%|██        | 433/2129 [00:37<02:23, 11.85it/s]
 20%|██        | 436/2129 [00:37<02:45, 10.25it/s]
 21%|██        | 438/2129 [00:38<02:32, 11.07it/s]
 21%|██        | 441/2129 [00:38<02:06, 13.31it/s]
 21%|██        | 444/2129 [00:38<01:54, 14.78it/s]
 21%|██        | 448/2129 [00:38<01:30, 18.63it/s]
 21%|██        | 451/2129 [00:38<02:02, 13.65it/s]
 21%|██▏       | 453/2129 [00:38<01:57, 14.30it/s]
 21%|██▏       | 455/2129 [00:39<02:56,  9.50it/s]
 21%|██▏       | 457/2129 [00:39<02:36, 10.68it/s]
 22%|██▏       | 459/2129 [00:39<03:29,  7.98it/s]
 22%|██▏       | 462/2129 [00:39<02:38, 10.49it/s]
 22%|██▏       | 466/2129 [00:40<02:51,  9.70it/s]
 22%|██▏       | 469/2129 [00:40<02:18, 12.01it/s]
 22%|██▏       | 471/2129 [00:41<03:12,  8.63it/s]
 22%|██▏       | 474/2129 [00:41<02:31, 10.95it/s]
 22%|██▏       | 477/2129 [00:41<02:03, 13.34it/s]
 22%|██▏       | 479/2129 [00:41<03:28,  7.92it/s]
 23%|██▎       | 481/2129 [00:42<03:28,  7.90it/s]
 23%|██▎       | 483/2129 [00:42<04:24,  6.23it/s]
 23%|██▎       | 484/2129 [00:43<05:42,  4.81it/s]
 23%|██▎       | 486/2129 [00:43<04:23,  6.23it/s]
 23%|██▎       | 488/2129 [00:44<06:28,  4.23it/s]
 23%|██▎       | 490/2129 [00:44<06:49,  4.01it/s]
 23%|██▎       | 492/2129 [00:44<05:12,  5.24it/s]
 23%|██▎       | 498/2129 [00:44<02:30, 10.81it/s]
 24%|██▎       | 501/2129 [00:45<02:30, 10.78it/s]
 24%|██▎       | 504/2129 [00:45<02:45,  9.80it/s]
 24%|██▍       | 507/2129 [00:45<02:14, 12.02it/s]
 24%|██▍       | 509/2129 [00:46<03:31,  7.67it/s]
 24%|██▍       | 511/2129 [00:46<03:01,  8.92it/s]
 24%|██▍       | 515/2129 [00:46<02:33, 10.51it/s]
 24%|██▍       | 517/2129 [00:46<02:34, 10.41it/s]
 24%|██▍       | 519/2129 [00:46<02:17, 11.71it/s]
 24%|██▍       | 521/2129 [00:46<02:12, 12.13it/s]
 25%|██▍       | 523/2129 [00:47<02:27, 10.89it/s]
 25%|██▍       | 525/2129 [00:47<02:18, 11.61it/s]
 25%|██▍       | 527/2129 [00:47<02:33, 10.45it/s]
 25%|██▍       | 529/2129 [00:48<03:29,  7.65it/s]
 25%|██▍       | 530/2129 [00:48<03:45,  7.10it/s]
 25%|██▍       | 532/2129 [00:48<03:00,  8.84it/s]
 25%|██▌       | 535/2129 [00:48<02:10, 12.18it/s]
 25%|██▌       | 537/2129 [00:48<03:18,  8.02it/s]
 26%|██▌       | 543/2129 [00:49<02:09, 12.27it/s]
 26%|██▌       | 545/2129 [00:49<02:34, 10.22it/s]
 26%|██▌       | 547/2129 [00:49<03:17,  8.02it/s]
 26%|██▌       | 549/2129 [00:50<03:35,  7.32it/s]
 26%|██▌       | 553/2129 [00:50<02:25, 10.84it/s]
 26%|██▌       | 557/2129 [00:50<02:13, 11.73it/s]
 26%|██▋       | 559/2129 [00:50<02:08, 12.19it/s]
 26%|██▋       | 561/2129 [00:50<01:59, 13.18it/s]
 26%|██▋       | 563/2129 [00:51<04:01,  6.49it/s]
 27%|██▋       | 565/2129 [00:52<04:26,  5.86it/s]
 27%|██▋       | 569/2129 [00:52<02:52,  9.06it/s]
 27%|██▋       | 571/2129 [00:52<03:04,  8.42it/s]
 27%|██▋       | 574/2129 [00:52<02:27, 10.55it/s]
 27%|██▋       | 577/2129 [00:53<02:33, 10.08it/s]
 27%|██▋       | 581/2129 [00:53<02:56,  8.76it/s]
 27%|██▋       | 583/2129 [00:53<02:36,  9.85it/s]
 27%|██▋       | 585/2129 [00:54<02:57,  8.68it/s]
 28%|██▊       | 587/2129 [00:54<03:36,  7.12it/s]
 28%|██▊       | 589/2129 [00:54<03:02,  8.45it/s]
 28%|██▊       | 591/2129 [00:55<03:48,  6.74it/s]
 28%|██▊       | 594/2129 [00:55<02:43,  9.41it/s]
 28%|██▊       | 599/2129 [00:55<01:59, 12.77it/s]
 28%|██▊       | 602/2129 [00:55<02:14, 11.36it/s]
 28%|██▊       | 604/2129 [00:55<02:16, 11.14it/s]
 28%|██▊       | 606/2129 [00:56<03:07,  8.11it/s]
 29%|██▊       | 610/2129 [00:56<02:36,  9.68it/s]
 29%|██▊       | 612/2129 [00:57<03:07,  8.10it/s]
 29%|██▉       | 613/2129 [00:57<03:28,  7.26it/s]
 29%|██▉       | 615/2129 [00:57<02:53,  8.74it/s]
 29%|██▉       | 620/2129 [00:57<01:41, 14.81it/s]
 29%|██▉       | 623/2129 [00:57<02:09, 11.67it/s]
 29%|██▉       | 626/2129 [00:58<02:42,  9.24it/s]
 29%|██▉       | 628/2129 [00:58<03:26,  7.27it/s]
 30%|██▉       | 631/2129 [00:59<03:14,  7.69it/s]
 30%|██▉       | 633/2129 [00:59<03:31,  7.08it/s]
 30%|██▉       | 636/2129 [01:00<03:48,  6.55it/s]
 30%|██▉       | 638/2129 [01:00<03:13,  7.71it/s]
 30%|███       | 640/2129 [01:00<02:42,  9.14it/s]
 30%|███       | 643/2129 [01:00<02:09, 11.48it/s]
 30%|███       | 645/2129 [01:00<02:49,  8.76it/s]
 30%|███       | 647/2129 [01:00<02:26, 10.12it/s]
 30%|███       | 649/2129 [01:01<03:25,  7.19it/s]
 31%|███       | 651/2129 [01:01<03:55,  6.28it/s]
 31%|███       | 653/2129 [01:02<04:34,  5.38it/s]
 31%|███       | 655/2129 [01:02<04:26,  5.53it/s]
 31%|███       | 657/2129 [01:02<03:32,  6.93it/s]
 31%|███       | 659/2129 [01:03<04:50,  5.06it/s]
 31%|███       | 661/2129 [01:03<05:07,  4.77it/s]
 31%|███       | 663/2129 [01:04<04:10,  5.86it/s]
 31%|███       | 664/2129 [01:04<04:23,  5.55it/s]
 31%|███▏      | 666/2129 [01:04<03:22,  7.24it/s]
 31%|███▏      | 668/2129 [01:04<03:21,  7.24it/s]
 32%|███▏      | 671/2129 [01:04<02:19, 10.47it/s]
 32%|███▏      | 673/2129 [01:05<02:43,  8.88it/s]
 32%|███▏      | 675/2129 [01:05<04:00,  6.05it/s]
 32%|███▏      | 677/2129 [01:06<04:28,  5.40it/s]
 32%|███▏      | 679/2129 [01:06<03:36,  6.71it/s]
 32%|███▏      | 682/2129 [01:06<02:35,  9.31it/s]
 32%|███▏      | 684/2129 [01:06<03:28,  6.92it/s]
 32%|███▏      | 686/2129 [01:07<03:26,  6.99it/s]
 32%|███▏      | 688/2129 [01:07<04:15,  5.63it/s]
 32%|███▏      | 689/2129 [01:07<04:22,  5.48it/s]
 32%|███▏      | 691/2129 [01:08<03:31,  6.79it/s]
 33%|███▎      | 694/2129 [01:08<02:40,  8.92it/s]
 33%|███▎      | 696/2129 [01:08<02:36,  9.17it/s]
 33%|███▎      | 700/2129 [01:08<01:46, 13.39it/s]
 33%|███▎      | 703/2129 [01:08<02:09, 11.00it/s]
 33%|███▎      | 705/2129 [01:09<02:46,  8.57it/s]
 33%|███▎      | 707/2129 [01:09<03:12,  7.40it/s]
 33%|███▎      | 708/2129 [01:09<03:32,  6.69it/s]
 33%|███▎      | 709/2129 [01:10<03:28,  6.80it/s]
 33%|███▎      | 711/2129 [01:10<02:58,  7.95it/s]
 33%|███▎      | 712/2129 [01:10<03:05,  7.65it/s]
 33%|███▎      | 713/2129 [01:10<02:57,  7.96it/s]
 34%|███▎      | 715/2129 [01:10<02:24,  9.81it/s]
 34%|███▎      | 717/2129 [01:10<01:58, 11.94it/s]
 34%|███▍      | 719/2129 [01:10<01:45, 13.40it/s]
 34%|███▍      | 721/2129 [01:11<02:47,  8.41it/s]
 34%|███▍      | 723/2129 [01:11<02:47,  8.41it/s]
 34%|███▍      | 725/2129 [01:11<02:47,  8.39it/s]
 34%|███▍      | 727/2129 [01:12<03:08,  7.43it/s]
 34%|███▍      | 729/2129 [01:12<02:37,  8.86it/s]
 34%|███▍      | 733/2129 [01:12<02:44,  8.50it/s]
 35%|███▍      | 735/2129 [01:13<02:55,  7.94it/s]
 35%|███▍      | 737/2129 [01:13<02:40,  8.66it/s]
 35%|███▍      | 738/2129 [01:13<03:28,  6.67it/s]
 35%|███▍      | 740/2129 [01:13<02:55,  7.89it/s]
 35%|███▍      | 742/2129 [01:13<02:59,  7.71it/s]
 35%|███▍      | 745/2129 [01:14<02:10, 10.64it/s]
 35%|███▌      | 750/2129 [01:14<01:48, 12.72it/s]
 35%|███▌      | 752/2129 [01:14<01:59, 11.50it/s]
 35%|███▌      | 754/2129 [01:15<02:58,  7.69it/s]
 35%|███▌      | 755/2129 [01:15<03:38,  6.29it/s]
 36%|███▌      | 758/2129 [01:15<03:07,  7.32it/s]
 36%|███▌      | 760/2129 [01:15<02:35,  8.80it/s]
 36%|███▌      | 762/2129 [01:16<03:37,  6.28it/s]
 36%|███▌      | 763/2129 [01:16<03:48,  5.97it/s]
 36%|███▌      | 764/2129 [01:16<04:11,  5.43it/s]
 36%|███▌      | 766/2129 [01:17<03:53,  5.85it/s]
 36%|███▌      | 767/2129 [01:17<04:04,  5.56it/s]
 36%|███▌      | 769/2129 [01:17<04:37,  4.90it/s]
 36%|███▌      | 771/2129 [01:18<03:26,  6.58it/s]
 36%|███▋      | 774/2129 [01:18<03:27,  6.52it/s]
 36%|███▋      | 775/2129 [01:18<04:34,  4.94it/s]
 36%|███▋      | 776/2129 [01:19<05:32,  4.07it/s]
 37%|███▋      | 778/2129 [01:19<04:00,  5.62it/s]
 37%|███▋      | 780/2129 [01:19<04:23,  5.12it/s]
 37%|███▋      | 781/2129 [01:20<04:37,  4.86it/s]
 37%|███▋      | 782/2129 [01:20<04:58,  4.51it/s]
 37%|███▋      | 784/2129 [01:20<04:03,  5.52it/s]
 37%|███▋      | 785/2129 [01:20<03:52,  5.77it/s]
 37%|███▋      | 787/2129 [01:20<03:07,  7.14it/s]
 37%|███▋      | 790/2129 [01:21<02:09, 10.34it/s]
 37%|███▋      | 793/2129 [01:21<01:43, 12.90it/s]
 37%|███▋      | 795/2129 [01:21<01:38, 13.51it/s]
 37%|███▋      | 797/2129 [01:21<02:50,  7.79it/s]
 38%|███▊      | 799/2129 [01:22<02:49,  7.84it/s]
 38%|███▊      | 801/2129 [01:22<03:32,  6.24it/s]
 38%|███▊      | 802/2129 [01:23<04:36,  4.80it/s]
 38%|███▊      | 805/2129 [01:23<03:04,  7.19it/s]
 38%|███▊      | 809/2129 [01:23<02:49,  7.78it/s]
 38%|███▊      | 811/2129 [01:23<02:29,  8.83it/s]
 38%|███▊      | 813/2129 [01:24<03:07,  7.02it/s]
 38%|███▊      | 816/2129 [01:24<02:16,  9.58it/s]
 38%|███▊      | 818/2129 [01:24<02:56,  7.44it/s]
 39%|███▊      | 820/2129 [01:25<03:32,  6.16it/s]
 39%|███▊      | 823/2129 [01:25<02:35,  8.38it/s]
 39%|███▉      | 827/2129 [01:25<02:33,  8.50it/s]
 39%|███▉      | 830/2129 [01:26<02:03, 10.52it/s]
 39%|███▉      | 832/2129 [01:26<02:20,  9.25it/s]
 39%|███▉      | 836/2129 [01:26<02:08, 10.05it/s]
 39%|███▉      | 840/2129 [01:26<01:36, 13.31it/s]
 40%|███▉      | 842/2129 [01:27<02:12,  9.70it/s]
 40%|███▉      | 844/2129 [01:28<03:46,  5.67it/s]
 40%|███▉      | 846/2129 [01:28<04:03,  5.26it/s]
 40%|███▉      | 848/2129 [01:29<04:19,  4.93it/s]
 40%|███▉      | 850/2129 [01:29<03:28,  6.13it/s]
 40%|████      | 852/2129 [01:29<03:56,  5.39it/s]
 40%|████      | 855/2129 [01:30<03:52,  5.48it/s]
 40%|████      | 857/2129 [01:30<03:48,  5.56it/s]
 40%|████      | 858/2129 [01:30<04:16,  4.95it/s]
 40%|████      | 860/2129 [01:31<04:35,  4.61it/s]
 40%|████      | 861/2129 [01:31<05:01,  4.20it/s]
 40%|████      | 862/2129 [01:32<05:48,  3.64it/s]
 41%|████      | 864/2129 [01:32<05:00,  4.21it/s]
 41%|████      | 865/2129 [01:32<05:46,  3.64it/s]
 41%|████      | 866/2129 [01:33<05:53,  3.57it/s]
 41%|████      | 869/2129 [01:33<03:24,  6.16it/s]
 41%|████      | 873/2129 [01:33<02:50,  7.38it/s]
 41%|████      | 876/2129 [01:34<02:51,  7.30it/s]
 41%|████      | 878/2129 [01:34<02:25,  8.59it/s]
 41%|████▏     | 881/2129 [01:34<01:57, 10.58it/s]
 42%|████▏     | 884/2129 [01:34<01:39, 12.57it/s]
 42%|████▏     | 886/2129 [01:34<01:31, 13.51it/s]
 42%|████▏     | 888/2129 [01:35<02:07,  9.76it/s]
 42%|████▏     | 890/2129 [01:35<02:43,  7.59it/s]
 42%|████▏     | 892/2129 [01:35<02:16,  9.09it/s]
 42%|████▏     | 894/2129 [01:36<03:03,  6.72it/s]
 42%|████▏     | 896/2129 [01:36<04:19,  4.75it/s]
 42%|████▏     | 898/2129 [01:37<04:23,  4.68it/s]
 42%|████▏     | 900/2129 [01:37<04:10,  4.90it/s]
 42%|████▏     | 902/2129 [01:38<04:20,  4.71it/s]
 42%|████▏     | 903/2129 [01:38<05:04,  4.03it/s]
 43%|████▎     | 905/2129 [01:38<04:33,  4.48it/s]
 43%|████▎     | 906/2129 [01:39<04:36,  4.42it/s]
 43%|████▎     | 908/2129 [01:39<04:04,  5.00it/s]
 43%|████▎     | 910/2129 [01:39<03:07,  6.50it/s]
 43%|████▎     | 911/2129 [01:39<03:21,  6.05it/s]
 43%|████▎     | 912/2129 [01:39<03:30,  5.79it/s]
 43%|████▎     | 914/2129 [01:40<03:10,  6.37it/s]
 43%|████▎     | 915/2129 [01:40<03:26,  5.87it/s]
 43%|████▎     | 918/2129 [01:40<02:10,  9.28it/s]
 43%|████▎     | 920/2129 [01:40<02:15,  8.91it/s]
 43%|████▎     | 922/2129 [01:41<02:43,  7.40it/s]
 43%|████▎     | 923/2129 [01:41<03:20,  6.02it/s]
 43%|████▎     | 926/2129 [01:41<03:29,  5.74it/s]
 44%|████▎     | 927/2129 [01:42<04:28,  4.48it/s]
 44%|████▎     | 928/2129 [01:42<05:19,  3.76it/s]
 44%|████▎     | 931/2129 [01:43<04:27,  4.48it/s]
 44%|████▍     | 934/2129 [01:43<02:59,  6.65it/s]
 44%|████▍     | 936/2129 [01:44<03:35,  5.54it/s]
 44%|████▍     | 937/2129 [01:44<04:15,  4.66it/s]
 44%|████▍     | 938/2129 [01:44<05:03,  3.92it/s]
 44%|████▍     | 939/2129 [01:45<05:39,  3.51it/s]
 44%|████▍     | 941/2129 [01:45<03:54,  5.07it/s]
 44%|████▍     | 943/2129 [01:45<03:39,  5.41it/s]
 44%|████▍     | 944/2129 [01:46<04:44,  4.17it/s]
 44%|████▍     | 945/2129 [01:46<05:36,  3.52it/s]
 44%|████▍     | 947/2129 [01:47<05:22,  3.66it/s]
 45%|████▍     | 950/2129 [01:47<04:28,  4.38it/s]
 45%|████▍     | 952/2129 [01:48<04:22,  4.49it/s]
 45%|████▍     | 954/2129 [01:48<03:25,  5.73it/s]
 45%|████▍     | 955/2129 [01:48<03:55,  4.99it/s]
 45%|████▍     | 956/2129 [01:48<04:20,  4.51it/s]
 45%|████▍     | 958/2129 [01:49<04:27,  4.38it/s]
 45%|████▌     | 959/2129 [01:49<05:19,  3.66it/s]
 45%|████▌     | 960/2129 [01:49<05:28,  3.56it/s]
 45%|████▌     | 961/2129 [01:50<05:09,  3.77it/s]
 45%|████▌     | 963/2129 [01:50<04:28,  4.34it/s]
 45%|████▌     | 964/2129 [01:50<04:07,  4.71it/s]
 45%|████▌     | 967/2129 [01:50<02:30,  7.74it/s]
 46%|████▌     | 969/2129 [01:51<04:11,  4.61it/s]
 46%|████▌     | 970/2129 [01:52<04:51,  3.98it/s]
 46%|████▌     | 971/2129 [01:52<05:10,  3.73it/s]
 46%|████▌     | 972/2129 [01:52<05:09,  3.74it/s]
 46%|████▌     | 973/2129 [01:53<06:05,  3.16it/s]
 46%|████▌     | 974/2129 [01:53<06:13,  3.09it/s]
 46%|████▌     | 976/2129 [01:53<03:59,  4.82it/s]
 46%|████▌     | 978/2129 [01:53<02:55,  6.54it/s]
 46%|████▌     | 980/2129 [01:54<02:53,  6.62it/s]
 46%|████▌     | 981/2129 [01:54<02:52,  6.66it/s]
 46%|████▌     | 982/2129 [01:54<02:42,  7.06it/s]
 46%|████▌     | 983/2129 [01:54<03:15,  5.87it/s]
 46%|████▌     | 984/2129 [01:54<03:43,  5.13it/s]
 46%|████▋     | 986/2129 [01:55<03:02,  6.26it/s]
 46%|████▋     | 988/2129 [01:55<02:15,  8.41it/s]
 47%|████▋     | 991/2129 [01:55<01:35, 11.89it/s]
 47%|████▋     | 993/2129 [01:55<02:26,  7.77it/s]
 47%|████▋     | 996/2129 [01:55<01:47, 10.58it/s]
 47%|████▋     | 1001/2129 [01:56<01:48, 10.38it/s]
 47%|████▋     | 1003/2129 [01:56<02:23,  7.83it/s]
 47%|████▋     | 1005/2129 [01:57<02:43,  6.86it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 352.78it/s]

[[np.int64(0), False, 10], [np.int64(1), False, 13], [np.int64(2), False, 0], [np.int64(3), False, 10], [np.int64(4), False, 1], [np.int64(5), False, 2], [np.int64(6), False, 1], [np.int64(7), False, 0], [np.int64(8), False, 4], [np.int64(9), False, 1], [np.int64(11), False, 3], [np.int64(12), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6306, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [12:15<3:32:44, 85.67s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [12:15<2:28:01, 60.01s/it]

tensor(11.9472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9407, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7546, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [12:15<49:56, 20.66s/it]

tensor(11.9353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8993, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [12:16<24:16, 10.19s/it]

tensor(11.9277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9605, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9250, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9866, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [12:16<11:52,  5.05s/it]

tensor(11.9225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0286, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0678, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [12:16<05:52,  2.54s/it]

tensor(11.9175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0968, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1118, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [12:16<02:58,  1.30s/it]

tensor(11.9129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1235, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1425, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [12:17<01:34,  1.43it/s]

tensor(11.9069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1541, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1727, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [12:17<00:53,  2.49it/s]

tensor(11.8972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2525, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [12:17<00:33,  3.89it/s]

tensor(11.8868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2926, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3335, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [12:17<00:23,  5.41it/s]

tensor(11.8793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3535, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3728, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [12:17<00:21,  5.95it/s]

tensor(11.8742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3790, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3807, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [12:18<00:18,  6.71it/s]

tensor(11.8683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3849, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3927, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [12:18<00:17,  6.98it/s]

tensor(11.8607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4025, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4166, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [12:18<00:15,  7.80it/s]

tensor(11.8524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4329, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4415, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [12:19<00:14,  8.12it/s]

tensor(11.8432, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4519, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4593, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [12:19<00:14,  8.35it/s]

tensor(11.8351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4690, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4727, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [12:19<00:13,  8.35it/s]

tensor(11.8287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4775, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4828, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [12:19<00:13,  8.39it/s]

tensor(11.8226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4841, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8194, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4887, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [12:20<00:13,  8.48it/s]

tensor(11.8161, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4931, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8124, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4977, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [12:20<00:12,  8.46it/s]

tensor(11.8088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5018, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.8055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5031, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [12:20<00:12,  8.42it/s]

tensor(11.8024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5065, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5060, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [12:20<00:12,  8.48it/s]

tensor(11.7973, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5042, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7948, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5093, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [12:20<00:12,  8.43it/s]

tensor(11.7921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5136, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7894, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5148, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [12:21<00:12,  8.41it/s]

tensor(11.7866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5147, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [12:21<00:11,  8.38it/s]

tensor(11.7817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5167, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([172, 593, 177,  62,  60, 103, 112, 114,  86,  99, 105,  76, 286,  84])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:16, 27.87it/s]
  1%|          | 11/2129 [00:00<00:37, 56.15it/s]
  1%|          | 17/2129 [00:00<00:43, 48.21it/s]
  1%|          | 22/2129 [00:00<00:43, 48.42it/s]
  1%|▏         | 28/2129 [00:00<00:42, 49.55it/s]
  2%|▏         | 34/2129 [00:00<00:41, 50.83it/s]
  2%|▏         | 40/2129 [00:00<00:56, 36.82it/s]
  2%|▏         | 45/2129 [00:01<00:56, 37.04it/s]
  2%|▏         | 50/2129 [00:01<01:53, 18.26it/s]
  3%|▎         | 54/2129 [00:01<01:46, 19.44it/s]
  3%|▎         | 61/2129 [00:01<01:18, 26.29it/s]
  3%|▎         | 65/2129 [00:02<02:09, 15.95it/s]
  3%|▎         | 68/2129 [00:02<02:07, 16.13it/s]
  3%|▎         | 71/2129 [00:02<01:54, 17.96it/s]
  4%|▍         | 80/2129 [00:04<03:30,  9.74it/s]
  4%|▍         | 84/2129 [00:04<02:52, 11.83it/s]
  4%|▍         | 92/2129 [00:04<01:53, 17.92it/s]
  5%|▍         | 97/2129 [00:05<02:59, 11.33it/s]
  5%|▍         | 102/2129 [00:05<02:21, 14.34it/s]
  5%|▍         | 106/2129 [00:06<04:43,  7.15it/s]
  5%|▌         | 113/2129 [00:06<03:07, 10.75it/s]
  5%|▌         | 117/2129 [00:07<03:14, 10.33it/s]
  6%|▌         | 122/2129 [00:07<02:29, 13.46it/s]
  6%|▌         | 129/2129 [00:07<01:45, 18.90it/s]
  6%|▋         | 134/2129 [00:08<02:57, 11.25it/s]
  7%|▋         | 141/2129 [00:08<02:04, 15.92it/s]
  7%|▋         | 149/2129 [00:08<01:28, 22.35it/s]
  7%|▋         | 155/2129 [00:10<04:01,  8.17it/s]
  7%|▋         | 159/2129 [00:13<07:32,  4.36it/s]
  8%|▊         | 162/2129 [00:14<08:00,  4.10it/s]
  8%|▊         | 164/2129 [00:14<07:03,  4.64it/s]
  8%|▊         | 167/2129 [00:14<06:19,  5.16it/s]
  8%|▊         | 170/2129 [00:14<04:59,  6.54it/s]
  8%|▊         | 172/2129 [00:14<04:51,  6.72it/s]
  8%|▊         | 174/2129 [00:15<04:12,  7.73it/s]
  8%|▊         | 177/2129 [00:15<03:15,  9.98it/s]
  8%|▊         | 179/2129 [00:15<05:00,  6.48it/s]
  9%|▊         | 181/2129 [00:16<07:13,  4.50it/s]
  9%|▊         | 183/2129 [00:17<07:13,  4.49it/s]
  9%|▊         | 184/2129 [00:17<08:31,  3.80it/s]
  9%|▉         | 187/2129 [00:17<05:34,  5.81it/s]
  9%|▉         | 190/2129 [00:18<05:38,  5.73it/s]
  9%|▉         | 192/2129 [00:18<04:38,  6.95it/s]
  9%|▉         | 196/2129 [00:18<03:02, 10.57it/s]
  9%|▉         | 200/2129 [00:19<03:48,  8.44it/s]
  9%|▉         | 202/2129 [00:19<05:37,  5.71it/s]
 10%|▉         | 205/2129 [00:20<04:24,  7.27it/s]
 10%|▉         | 208/2129 [00:20<03:23,  9.44it/s]
 10%|▉         | 212/2129 [00:21<05:21,  5.97it/s]
 10%|█         | 214/2129 [00:22<08:28,  3.76it/s]
 10%|█         | 217/2129 [00:22<06:15,  5.10it/s]
 10%|█         | 219/2129 [00:23<09:04,  3.51it/s]
 10%|█         | 222/2129 [00:23<06:39,  4.78it/s]
 11%|█         | 224/2129 [00:24<07:43,  4.11it/s]
 11%|█         | 225/2129 [00:25<09:47,  3.24it/s]
 11%|█         | 226/2129 [00:26<12:34,  2.52it/s]
 11%|█         | 228/2129 [00:26<08:59,  3.52it/s]
 11%|█         | 233/2129 [00:27<07:05,  4.45it/s]
 11%|█         | 234/2129 [00:27<09:11,  3.44it/s]
 11%|█         | 236/2129 [00:28<07:04,  4.46it/s]
 11%|█         | 239/2129 [00:28<07:25,  4.24it/s]
 11%|█▏        | 242/2129 [00:28<05:18,  5.93it/s]
 11%|█▏        | 244/2129 [00:29<05:38,  5.57it/s]
 12%|█▏        | 246/2129 [00:29<06:31,  4.81it/s]
 12%|█▏        | 248/2129 [00:30<07:21,  4.26it/s]
 12%|█▏        | 250/2129 [00:31<07:54,  3.96it/s]
 12%|█▏        | 252/2129 [00:31<08:49,  3.55it/s]
 12%|█▏        | 254/2129 [00:31<06:46,  4.61it/s]
 12%|█▏        | 255/2129 [00:32<07:00,  4.46it/s]
 12%|█▏        | 257/2129 [00:32<05:12,  5.98it/s]
 12%|█▏        | 259/2129 [00:33<07:47,  4.00it/s]
 12%|█▏        | 261/2129 [00:34<10:16,  3.03it/s]
 12%|█▏        | 264/2129 [00:34<06:40,  4.66it/s]
 13%|█▎        | 267/2129 [00:35<09:33,  3.25it/s]
 13%|█▎        | 270/2129 [00:35<06:40,  4.64it/s]
 13%|█▎        | 275/2129 [00:37<07:24,  4.17it/s]
 13%|█▎        | 279/2129 [00:37<05:10,  5.95it/s]
 13%|█▎        | 281/2129 [00:37<05:23,  5.71it/s]
 13%|█▎        | 283/2129 [00:38<05:42,  5.39it/s]
 13%|█▎        | 287/2129 [00:39<07:29,  4.10it/s]
 14%|█▎        | 290/2129 [00:39<05:39,  5.41it/s]
 14%|█▎        | 292/2129 [00:40<06:33,  4.67it/s]
 14%|█▍        | 295/2129 [00:40<04:52,  6.26it/s]
 14%|█▍        | 297/2129 [00:40<05:37,  5.43it/s]
 14%|█▍        | 301/2129 [00:41<03:42,  8.21it/s]
 14%|█▍        | 303/2129 [00:41<03:16,  9.31it/s]
 14%|█▍        | 305/2129 [00:42<06:09,  4.94it/s]
 14%|█▍        | 307/2129 [00:42<05:10,  5.87it/s]
 15%|█▍        | 311/2129 [00:42<03:18,  9.14it/s]
 15%|█▍        | 314/2129 [00:46<14:37,  2.07it/s]
 15%|█▍        | 316/2129 [00:47<15:53,  1.90it/s]
 15%|█▍        | 319/2129 [00:47<11:01,  2.74it/s]
 15%|█▌        | 321/2129 [00:49<12:48,  2.35it/s]
 15%|█▌        | 324/2129 [00:50<13:05,  2.30it/s]
 15%|█▌        | 326/2129 [00:50<10:20,  2.91it/s]
 15%|█▌        | 328/2129 [00:51<12:42,  2.36it/s]
 16%|█▌        | 331/2129 [00:51<08:35,  3.49it/s]
 16%|█▌        | 334/2129 [00:53<10:11,  2.94it/s]
 16%|█▌        | 337/2129 [00:54<11:23,  2.62it/s]
 16%|█▌        | 340/2129 [00:54<08:09,  3.66it/s]
 16%|█▌        | 342/2129 [00:56<10:39,  2.80it/s]
 16%|█▌        | 343/2129 [00:57<14:15,  2.09it/s]
 16%|█▌        | 345/2129 [00:58<15:24,  1.93it/s]
 16%|█▋        | 348/2129 [00:58<10:00,  2.97it/s]
 16%|█▋        | 350/2129 [00:59<12:02,  2.46it/s]
 17%|█▋        | 353/2129 [00:59<08:05,  3.66it/s]
 17%|█▋        | 355/2129 [01:01<10:23,  2.85it/s]
 17%|█▋        | 356/2129 [01:02<14:48,  1.99it/s]
 17%|█▋        | 357/2129 [01:03<19:21,  1.53it/s]
 17%|█▋        | 358/2129 [01:04<22:46,  1.30it/s]
 17%|█▋        | 359/2129 [01:05<20:12,  1.46it/s]
 17%|█▋        | 361/2129 [01:06<16:48,  1.75it/s]
 17%|█▋        | 362/2129 [01:06<16:54,  1.74it/s]
 17%|█▋        | 364/2129 [01:06<10:58,  2.68it/s]
 17%|█▋        | 367/2129 [01:06<06:32,  4.48it/s]
 18%|█▊        | 373/2129 [01:07<05:29,  5.33it/s]
 18%|█▊        | 375/2129 [01:08<05:24,  5.40it/s]
 18%|█▊        | 376/2129 [01:08<06:12,  4.71it/s]
 18%|█▊        | 379/2129 [01:08<04:21,  6.70it/s]
 18%|█▊        | 381/2129 [01:09<06:00,  4.85it/s]
 18%|█▊        | 383/2129 [01:09<04:47,  6.07it/s]
 18%|█▊        | 385/2129 [01:10<07:35,  3.83it/s]
 18%|█▊        | 386/2129 [01:11<08:59,  3.23it/s]
 18%|█▊        | 388/2129 [01:11<06:40,  4.34it/s]
 18%|█▊        | 391/2129 [01:12<08:24,  3.44it/s]
 18%|█▊        | 392/2129 [01:12<07:54,  3.66it/s]
 18%|█▊        | 393/2129 [01:12<07:23,  3.91it/s]
 19%|█▊        | 394/2129 [01:13<09:01,  3.20it/s]
 19%|█▊        | 396/2129 [01:13<06:13,  4.64it/s]
 19%|█▊        | 399/2129 [01:13<04:01,  7.18it/s]
 19%|█▉        | 401/2129 [01:14<04:53,  5.88it/s]
 19%|█▉        | 404/2129 [01:14<06:07,  4.70it/s]
 19%|█▉        | 405/2129 [01:16<11:18,  2.54it/s]
 19%|█▉        | 408/2129 [01:16<09:11,  3.12it/s]
 19%|█▉        | 411/2129 [01:17<06:12,  4.61it/s]
 19%|█▉        | 414/2129 [01:17<04:29,  6.37it/s]
 20%|█▉        | 416/2129 [01:17<04:41,  6.10it/s]
 20%|█▉        | 418/2129 [01:17<03:50,  7.43it/s]
 20%|█▉        | 420/2129 [01:18<07:16,  3.92it/s]
 20%|█▉        | 422/2129 [01:19<06:49,  4.16it/s]
 20%|█▉        | 424/2129 [01:19<05:21,  5.31it/s]
 20%|██        | 427/2129 [01:19<03:43,  7.63it/s]
 20%|██        | 430/2129 [01:20<05:32,  5.12it/s]
 20%|██        | 432/2129 [01:21<08:55,  3.17it/s]
 20%|██        | 433/2129 [01:22<10:05,  2.80it/s]
 20%|██        | 436/2129 [01:23<09:52,  2.86it/s]
 21%|██        | 438/2129 [01:23<07:34,  3.72it/s]
 21%|██        | 439/2129 [01:24<11:33,  2.44it/s]
 21%|██        | 440/2129 [01:24<09:54,  2.84it/s]
 21%|██        | 446/2129 [01:24<04:04,  6.87it/s]
 21%|██        | 449/2129 [01:26<06:30,  4.30it/s]
 21%|██        | 451/2129 [01:26<05:25,  5.15it/s]
 21%|██▏       | 453/2129 [01:26<06:20,  4.40it/s]
 21%|██▏       | 455/2129 [01:28<09:21,  2.98it/s]
 21%|██▏       | 456/2129 [01:28<09:13,  3.02it/s]
 21%|██▏       | 457/2129 [01:29<13:25,  2.08it/s]
 22%|██▏       | 459/2129 [01:30<12:19,  2.26it/s]
 22%|██▏       | 461/2129 [01:30<08:44,  3.18it/s]
 22%|██▏       | 463/2129 [01:30<06:30,  4.27it/s]
 22%|██▏       | 466/2129 [01:31<06:06,  4.54it/s]
 22%|██▏       | 468/2129 [01:31<06:35,  4.20it/s]
 22%|██▏       | 470/2129 [01:31<05:07,  5.39it/s]
 22%|██▏       | 472/2129 [01:32<05:23,  5.12it/s]
 22%|██▏       | 474/2129 [01:32<04:13,  6.52it/s]
 22%|██▏       | 477/2129 [01:33<07:42,  3.57it/s]
 22%|██▏       | 478/2129 [01:34<10:40,  2.58it/s]
 23%|██▎       | 480/2129 [01:34<07:55,  3.47it/s]
 23%|██▎       | 483/2129 [01:36<10:11,  2.69it/s]
 23%|██▎       | 484/2129 [01:37<13:58,  1.96it/s]
 23%|██▎       | 486/2129 [01:38<11:22,  2.41it/s]
 23%|██▎       | 487/2129 [01:38<10:35,  2.58it/s]
 23%|██▎       | 488/2129 [01:38<09:18,  2.94it/s]
 23%|██▎       | 490/2129 [01:39<08:35,  3.18it/s]
 23%|██▎       | 492/2129 [01:39<06:07,  4.45it/s]
 23%|██▎       | 495/2129 [01:39<04:01,  6.76it/s]
 24%|██▎       | 501/2129 [01:39<03:30,  7.74it/s]
 24%|██▎       | 504/2129 [01:40<02:50,  9.52it/s]
 24%|██▍       | 508/2129 [01:40<03:44,  7.23it/s]
 24%|██▍       | 510/2129 [01:41<04:34,  5.91it/s]
 24%|██▍       | 511/2129 [01:41<04:22,  6.17it/s]
 24%|██▍       | 514/2129 [01:41<03:16,  8.23it/s]
 24%|██▍       | 516/2129 [01:43<06:54,  3.90it/s]
 24%|██▍       | 517/2129 [01:44<11:19,  2.37it/s]
 24%|██▍       | 519/2129 [01:44<09:30,  2.82it/s]
 24%|██▍       | 520/2129 [01:46<13:56,  1.92it/s]
 24%|██▍       | 521/2129 [01:47<17:53,  1.50it/s]
 25%|██▍       | 522/2129 [01:48<19:15,  1.39it/s]
 25%|██▍       | 525/2129 [01:48<11:24,  2.34it/s]
 25%|██▍       | 526/2129 [01:49<12:16,  2.18it/s]
 25%|██▍       | 527/2129 [01:49<10:26,  2.56it/s]
 25%|██▍       | 528/2129 [01:50<12:42,  2.10it/s]
 25%|██▍       | 529/2129 [01:50<13:39,  1.95it/s]
 25%|██▍       | 530/2129 [01:51<14:48,  1.80it/s]
 25%|██▍       | 532/2129 [01:51<09:04,  2.93it/s]
 25%|██▌       | 535/2129 [01:51<06:38,  4.00it/s]
 25%|██▌       | 536/2129 [01:52<08:49,  3.01it/s]
 25%|██▌       | 538/2129 [01:52<06:15,  4.24it/s]
 25%|██▌       | 539/2129 [01:53<07:07,  3.72it/s]
 25%|██▌       | 542/2129 [01:53<04:26,  5.95it/s]
 26%|██▌       | 544/2129 [01:53<04:39,  5.68it/s]
 26%|██▌       | 546/2129 [01:53<03:40,  7.18it/s]
 26%|██▌       | 548/2129 [01:54<06:42,  3.93it/s]
 26%|██▌       | 551/2129 [01:55<04:37,  5.69it/s]
 26%|██▌       | 553/2129 [01:55<04:15,  6.18it/s]
 26%|██▌       | 555/2129 [01:55<03:28,  7.53it/s]
 26%|██▌       | 557/2129 [01:55<04:33,  5.76it/s]
 26%|██▋       | 559/2129 [01:56<05:34,  4.69it/s]
 26%|██▋       | 562/2129 [01:56<03:47,  6.88it/s]
 26%|██▋       | 564/2129 [01:57<04:50,  5.39it/s]
 27%|██▋       | 566/2129 [01:57<03:55,  6.64it/s]
 27%|██▋       | 568/2129 [01:57<04:50,  5.37it/s]
 27%|██▋       | 571/2129 [01:59<07:05,  3.66it/s]
 27%|██▋       | 574/2129 [01:59<05:48,  4.46it/s]
 27%|██▋       | 577/2129 [02:00<07:24,  3.49it/s]
 27%|██▋       | 580/2129 [02:00<05:22,  4.80it/s]
 27%|██▋       | 582/2129 [02:02<08:06,  3.18it/s]
 27%|██▋       | 584/2129 [02:03<10:22,  2.48it/s]
 28%|██▊       | 586/2129 [02:03<08:03,  3.19it/s]
 28%|██▊       | 587/2129 [02:04<10:44,  2.39it/s]
 28%|██▊       | 589/2129 [02:05<10:41,  2.40it/s]
 28%|██▊       | 590/2129 [02:05<10:49,  2.37it/s]
 28%|██▊       | 592/2129 [02:06<07:35,  3.37it/s]
 28%|██▊       | 598/2129 [02:06<03:19,  7.67it/s]
 28%|██▊       | 601/2129 [02:06<03:52,  6.57it/s]
 28%|██▊       | 603/2129 [02:08<06:36,  3.85it/s]
 28%|██▊       | 605/2129 [02:08<06:50,  3.71it/s]
 29%|██▊       | 608/2129 [02:08<04:49,  5.26it/s]
 29%|██▊       | 610/2129 [02:09<05:13,  4.84it/s]
 29%|██▊       | 612/2129 [02:10<06:28,  3.90it/s]
 29%|██▉       | 613/2129 [02:10<08:40,  2.91it/s]
 29%|██▉       | 618/2129 [02:11<04:44,  5.31it/s]
 29%|██▉       | 620/2129 [02:11<03:58,  6.32it/s]
 29%|██▉       | 622/2129 [02:12<05:13,  4.81it/s]
 29%|██▉       | 624/2129 [02:12<04:12,  5.96it/s]
 29%|██▉       | 626/2129 [02:12<05:39,  4.43it/s]
 29%|██▉       | 627/2129 [02:13<05:42,  4.39it/s]
 29%|██▉       | 628/2129 [02:13<08:19,  3.01it/s]
 30%|██▉       | 631/2129 [02:14<05:08,  4.86it/s]
 30%|██▉       | 636/2129 [02:14<04:06,  6.05it/s]
 30%|███       | 640/2129 [02:14<02:50,  8.72it/s]
 30%|███       | 644/2129 [02:15<03:34,  6.91it/s]
 30%|███       | 646/2129 [02:15<03:14,  7.63it/s]
 30%|███       | 649/2129 [02:16<03:33,  6.94it/s]
 31%|███       | 651/2129 [02:16<03:31,  6.98it/s]
 31%|███       | 653/2129 [02:17<04:30,  5.46it/s]
 31%|███       | 656/2129 [02:17<04:55,  4.99it/s]
 31%|███       | 658/2129 [02:18<05:12,  4.70it/s]
 31%|███       | 660/2129 [02:18<04:11,  5.85it/s]
 31%|███       | 661/2129 [02:19<08:27,  2.89it/s]
 31%|███       | 662/2129 [02:21<12:25,  1.97it/s]
 31%|███       | 663/2129 [02:22<15:47,  1.55it/s]
 31%|███       | 664/2129 [02:22<14:10,  1.72it/s]
 31%|███▏      | 667/2129 [02:23<12:17,  1.98it/s]
 31%|███▏      | 670/2129 [02:24<08:47,  2.77it/s]
 32%|███▏      | 673/2129 [02:24<05:49,  4.17it/s]
 32%|███▏      | 677/2129 [02:25<06:41,  3.62it/s]
 32%|███▏      | 680/2129 [02:27<08:04,  2.99it/s]
 32%|███▏      | 682/2129 [02:28<09:42,  2.49it/s]
 32%|███▏      | 683/2129 [02:29<12:41,  1.90it/s]
 32%|███▏      | 684/2129 [02:30<14:45,  1.63it/s]
 32%|███▏      | 685/2129 [02:32<17:51,  1.35it/s]
 32%|███▏      | 687/2129 [02:33<17:12,  1.40it/s]
 32%|███▏      | 688/2129 [02:34<20:02,  1.20it/s]
 32%|███▏      | 689/2129 [02:35<18:10,  1.32it/s]
 32%|███▏      | 691/2129 [02:35<11:33,  2.07it/s]
 33%|███▎      | 693/2129 [02:35<07:58,  3.00it/s]
 33%|███▎      | 694/2129 [02:36<12:03,  1.98it/s]
 33%|███▎      | 696/2129 [02:37<13:01,  1.83it/s]
 33%|███▎      | 698/2129 [02:37<08:58,  2.66it/s]
 33%|███▎      | 703/2129 [02:39<07:13,  3.29it/s]
 33%|███▎      | 705/2129 [02:40<09:02,  2.62it/s]
 33%|███▎      | 707/2129 [02:41<09:23,  2.52it/s]
 33%|███▎      | 708/2129 [02:41<10:36,  2.23it/s]
 33%|███▎      | 710/2129 [02:42<07:48,  3.03it/s]
 33%|███▎      | 712/2129 [02:42<07:48,  3.02it/s]
 33%|███▎      | 713/2129 [02:43<08:06,  2.91it/s]
 34%|███▎      | 715/2129 [02:43<05:51,  4.02it/s]
 34%|███▎      | 717/2129 [02:43<04:20,  5.42it/s]
 34%|███▍      | 719/2129 [02:43<05:06,  4.61it/s]
 34%|███▍      | 721/2129 [02:44<05:38,  4.16it/s]
 34%|███▍      | 723/2129 [02:45<07:43,  3.04it/s]
 34%|███▍      | 724/2129 [02:46<11:15,  2.08it/s]
 34%|███▍      | 725/2129 [02:47<11:52,  1.97it/s]
 34%|███▍      | 726/2129 [02:48<15:31,  1.51it/s]
 34%|███▍      | 727/2129 [02:49<18:51,  1.24it/s]
 34%|███▍      | 728/2129 [02:51<21:24,  1.09it/s]
 34%|███▍      | 730/2129 [02:51<14:12,  1.64it/s]
 34%|███▍      | 732/2129 [02:51<09:17,  2.51it/s]
 34%|███▍      | 733/2129 [02:52<11:21,  2.05it/s]
 34%|███▍      | 734/2129 [02:53<12:20,  1.88it/s]
 35%|███▍      | 737/2129 [02:53<06:34,  3.53it/s]
 35%|███▍      | 739/2129 [02:54<09:21,  2.47it/s]
 35%|███▍      | 741/2129 [02:54<06:50,  3.38it/s]
 35%|███▌      | 748/2129 [02:54<02:51,  8.05it/s]
 35%|███▌      | 751/2129 [02:56<04:52,  4.70it/s]
 35%|███▌      | 753/2129 [02:57<06:55,  3.31it/s]
 35%|███▌      | 755/2129 [02:59<12:00,  1.91it/s]
 36%|███▌      | 758/2129 [03:00<08:22,  2.73it/s]
 36%|███▌      | 762/2129 [03:01<08:11,  2.78it/s]
 36%|███▌      | 764/2129 [03:02<09:39,  2.36it/s]
 36%|███▌      | 765/2129 [03:03<09:31,  2.39it/s]
 36%|███▌      | 766/2129 [03:04<12:09,  1.87it/s]
 36%|███▌      | 767/2129 [03:05<13:05,  1.73it/s]
 36%|███▌      | 769/2129 [03:05<11:30,  1.97it/s]
 36%|███▌      | 771/2129 [03:05<08:05,  2.80it/s]
 36%|███▋      | 772/2129 [03:06<07:13,  3.13it/s]
 36%|███▋      | 774/2129 [03:07<08:44,  2.59it/s]
 36%|███▋      | 775/2129 [03:07<10:36,  2.13it/s]
 36%|███▋      | 776/2129 [03:08<13:51,  1.63it/s]
 36%|███▋      | 777/2129 [03:09<12:09,  1.85it/s]
 37%|███▋      | 779/2129 [03:09<07:38,  2.94it/s]
 37%|███▋      | 780/2129 [03:10<11:37,  1.93it/s]
 37%|███▋      | 781/2129 [03:11<13:33,  1.66it/s]
 37%|███▋      | 782/2129 [03:12<15:17,  1.47it/s]
 37%|███▋      | 784/2129 [03:12<09:27,  2.37it/s]
 37%|███▋      | 785/2129 [03:12<09:59,  2.24it/s]
 37%|███▋      | 787/2129 [03:13<08:54,  2.51it/s]
 37%|███▋      | 790/2129 [03:13<05:12,  4.29it/s]
 37%|███▋      | 795/2129 [03:14<03:48,  5.84it/s]
 37%|███▋      | 796/2129 [03:14<05:13,  4.25it/s]
 37%|███▋      | 798/2129 [03:15<06:16,  3.54it/s]
 38%|███▊      | 800/2129 [03:16<06:20,  3.50it/s]
 38%|███▊      | 802/2129 [03:17<06:59,  3.17it/s]
 38%|███▊      | 803/2129 [03:17<08:03,  2.74it/s]
 38%|███▊      | 805/2129 [03:17<05:48,  3.80it/s]
 38%|███▊      | 806/2129 [03:18<05:23,  4.09it/s]
 38%|███▊      | 808/2129 [03:18<03:53,  5.67it/s]
 38%|███▊      | 810/2129 [03:18<04:54,  4.47it/s]
 38%|███▊      | 812/2129 [03:19<04:50,  4.53it/s]
 38%|███▊      | 813/2129 [03:20<09:04,  2.42it/s]
 38%|███▊      | 816/2129 [03:20<05:26,  4.02it/s]
 38%|███▊      | 818/2129 [03:21<06:01,  3.63it/s]
 39%|███▊      | 820/2129 [03:21<06:03,  3.61it/s]
 39%|███▊      | 821/2129 [03:21<05:35,  3.90it/s]
 39%|███▊      | 823/2129 [03:22<04:05,  5.32it/s]
 39%|███▉      | 827/2129 [03:23<04:46,  4.55it/s]
 39%|███▉      | 830/2129 [03:23<03:25,  6.31it/s]
 39%|███▉      | 832/2129 [03:23<04:27,  4.85it/s]
 39%|███▉      | 834/2129 [03:24<03:45,  5.74it/s]
 39%|███▉      | 838/2129 [03:25<05:03,  4.25it/s]
 40%|███▉      | 841/2129 [03:25<04:17,  5.01it/s]
 40%|███▉      | 842/2129 [03:26<07:16,  2.95it/s]
 40%|███▉      | 843/2129 [03:28<10:03,  2.13it/s]
 40%|███▉      | 844/2129 [03:29<13:05,  1.64it/s]
 40%|███▉      | 846/2129 [03:30<13:06,  1.63it/s]
 40%|███▉      | 848/2129 [03:32<13:31,  1.58it/s]
 40%|███▉      | 851/2129 [03:32<08:16,  2.58it/s]
 40%|████      | 852/2129 [03:33<11:15,  1.89it/s]
 40%|████      | 854/2129 [03:34<12:10,  1.75it/s]
 40%|████      | 855/2129 [03:36<15:03,  1.41it/s]
 40%|████      | 858/2129 [03:36<08:46,  2.41it/s]
 40%|████      | 860/2129 [03:37<09:54,  2.14it/s]
 40%|████      | 862/2129 [03:38<11:06,  1.90it/s]
 41%|████      | 864/2129 [03:38<08:06,  2.60it/s]
 41%|████      | 865/2129 [03:39<11:02,  1.91it/s]
 41%|████      | 866/2129 [03:41<13:47,  1.53it/s]
 41%|████      | 868/2129 [03:41<09:08,  2.30it/s]
 41%|████      | 872/2129 [03:41<05:01,  4.17it/s]
 41%|████      | 874/2129 [03:42<06:01,  3.47it/s]
 41%|████      | 878/2129 [03:42<03:58,  5.25it/s]
 41%|████▏     | 880/2129 [03:42<03:21,  6.20it/s]
 41%|████▏     | 882/2129 [03:43<04:24,  4.71it/s]
 42%|████▏     | 884/2129 [03:43<03:31,  5.90it/s]
 42%|████▏     | 886/2129 [03:44<06:12,  3.34it/s]
 42%|████▏     | 887/2129 [03:46<09:28,  2.18it/s]
 42%|████▏     | 889/2129 [03:46<07:45,  2.66it/s]
 42%|████▏     | 892/2129 [03:46<04:57,  4.16it/s]
 42%|████▏     | 894/2129 [03:47<07:16,  2.83it/s]
 42%|████▏     | 895/2129 [03:49<10:27,  1.97it/s]
 42%|████▏     | 898/2129 [03:50<09:53,  2.08it/s]
 42%|████▏     | 901/2129 [03:50<06:28,  3.16it/s]
 42%|████▏     | 903/2129 [03:51<07:50,  2.61it/s]
 43%|████▎     | 906/2129 [03:52<06:27,  3.16it/s]
 43%|████▎     | 908/2129 [03:53<06:39,  3.05it/s]
 43%|████▎     | 909/2129 [03:53<06:14,  3.26it/s]
 43%|████▎     | 911/2129 [03:53<06:41,  3.03it/s]
 43%|████▎     | 912/2129 [03:54<06:41,  3.03it/s]
 43%|████▎     | 914/2129 [03:54<06:22,  3.17it/s]
 43%|████▎     | 916/2129 [03:55<05:57,  3.39it/s]
 43%|████▎     | 919/2129 [03:55<03:48,  5.29it/s]
 43%|████▎     | 921/2129 [03:55<03:02,  6.63it/s]
 43%|████▎     | 924/2129 [03:55<02:47,  7.18it/s]
 43%|████▎     | 926/2129 [03:56<02:24,  8.30it/s]
 44%|████▎     | 928/2129 [03:57<05:29,  3.65it/s]
 44%|████▎     | 929/2129 [03:57<04:56,  4.04it/s]
 44%|████▎     | 931/2129 [03:58<05:01,  3.97it/s]
 44%|████▍     | 934/2129 [03:58<03:16,  6.08it/s]
 44%|████▍     | 936/2129 [03:58<04:06,  4.84it/s]
 44%|████▍     | 938/2129 [04:00<07:12,  2.76it/s]
 44%|████▍     | 939/2129 [04:01<10:04,  1.97it/s]
 44%|████▍     | 942/2129 [04:01<06:09,  3.21it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 290.85it/s]

[[np.int64(0), False, 1], [np.int64(2), False, 12], [np.int64(3), False, 6], [np.int64(4), False, 8], [np.int64(5), False, 12], [np.int64(6), False, 9], [np.int64(7), False, 2], [np.int64(9), False, 13], [np.int64(10), False, 5], [np.int64(11), False, 8], [np.int64(12), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8426, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [23:23<5:27:52, 198.72s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [23:23<3:47:17, 139.16s/it]

tensor(11.7783, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1874, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [23:23<1:15:41, 47.81s/it]

tensor(11.7828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2409, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2786, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [23:24<36:24, 23.49s/it]

tensor(11.7866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3224, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3811, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [23:24<25:16, 16.48s/it]

tensor(11.7873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4707, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [23:24<08:30,  5.73s/it]

tensor(11.7860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5024, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [23:24<04:09,  2.87s/it]

tensor(11.7829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4969, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4809, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [23:25<02:55,  2.05s/it]

tensor(11.7786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4731, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4914, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [23:25<01:29,  1.06s/it]

tensor(11.7723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5181, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5383, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [23:25<00:36,  2.25it/s]

tensor(11.7672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5457, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5566, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [23:25<00:22,  3.57it/s]

tensor(11.7651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5616, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5622, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [23:26<00:15,  5.02it/s]

tensor(11.7628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5665, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5671, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [23:26<00:13,  5.68it/s]

tensor(11.7592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5635, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5632, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [23:26<00:10,  6.73it/s]

tensor(11.7537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5646, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [23:26<00:09,  7.61it/s]

tensor(11.7472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5697, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7445, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5685, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [23:27<00:08,  7.81it/s]

tensor(11.7421, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5652, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7396, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5648, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [23:27<00:08,  7.90it/s]

tensor(11.7374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5649, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5644, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [23:27<00:08,  8.04it/s]

tensor(11.7331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5649, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5664, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [23:27<00:07,  8.15it/s]

tensor(11.7286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5726, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5745, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [23:28<00:07,  8.14it/s]

tensor(11.7245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5785, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5792, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [23:28<00:07,  8.21it/s]

tensor(11.7205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5834, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5873, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [23:28<00:07,  7.89it/s]

tensor(11.7167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5879, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5876, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [23:28<00:06,  8.06it/s]

tensor(11.7132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5876, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5903, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [23:29<00:06,  8.09it/s]

tensor(11.7098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5934, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [23:29<00:06,  7.85it/s]

tensor(11.7066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5946, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5965, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [23:29<00:06,  7.99it/s]

tensor(11.7034, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5991, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([206, 106, 118, 475, 108, 188,  59, 197,  95, 101,  88, 227,  81,  80])

  0%|          | 0/2129 [00:00<?, ?it/s]
  0%|          | 3/2129 [00:00<01:20, 26.37it/s]
  0%|          | 6/2129 [00:00<01:29, 23.83it/s]
  0%|          | 9/2129 [00:00<01:43, 20.54it/s]
  1%|          | 12/2129 [00:00<01:34, 22.43it/s]
  1%|          | 18/2129 [00:00<01:04, 32.89it/s]
  1%|          | 25/2129 [00:00<00:48, 43.70it/s]
  1%|▏         | 31/2129 [00:00<00:44, 47.21it/s]
  2%|▏         | 36/2129 [00:01<00:50, 41.82it/s]
  2%|▏         | 43/2129 [00:01<00:44, 47.38it/s]
  2%|▏         | 50/2129 [00:01<00:41, 49.80it/s]
  3%|▎         | 57/2129 [00:01<00:37, 54.95it/s]
  3%|▎         | 64/2129 [00:01<00:35, 57.72it/s]
  3%|▎         | 70/2129 [00:02<02:04, 16.51it/s]
  4%|▎         | 76/2129 [00:02<01:39, 20.68it/s]
  4%|▍         | 82/2129 [00:02<01:20, 25.32it/s]
  4%|▍         | 87/2129 [00:02<01:10, 28.93it/s]
  4%|▍         | 94/2129 [00:02<00:57, 35.46it/s]
  5%|▍         | 100/2129 [00:03<00:50, 39.91it/s]
  5%|▍         | 106/2129 [00:03<00:45, 44.02it/s]
  5%|▌         | 112/2129 [00:03<00:43, 46.86it/s]
  6%|▌         | 119/2129 [00:03<00:38, 52.21it/s]
  6%|▌         | 126/2129 [00:03<00:35, 55.85it/s]
  6%|▌         | 133/2129 [00:04<01:48, 18.46it/s]
  6%|▋         | 138/2129 [00:04<01:36, 20.57it/s]
  7%|▋         | 146/2129 [00:04<01:11, 27.72it/s]
  7%|▋         | 152/2129 [00:04<01:01, 32.18it/s]
  7%|▋         | 158/2129 [00:05<02:09, 15.21it/s]
  8%|▊         | 162/2129 [00:06<03:15, 10.08it/s]
  8%|▊         | 165/2129 [00:06<03:00, 10.91it/s]
  8%|▊         | 168/2129 [00:06<02:39, 12.27it/s]
  8%|▊         | 171/2129 [00:07<03:12, 10.16it/s]
  8%|▊         | 173/2129 [00:07<02:57, 11.03it/s]
  8%|▊         | 175/2129 [00:07<02:45, 11.81it/s]
  8%|▊         | 179/2129 [00:07<02:03, 15.79it/s]
  9%|▊         | 184/2129 [00:08<03:05, 10.48it/s]
  9%|▊         | 186/2129 [00:08<02:52, 11.27it/s]
  9%|▉         | 188/2129 [00:08<02:36, 12.37it/s]
  9%|▉         | 190/2129 [00:09<03:57,  8.17it/s]
  9%|▉         | 192/2129 [00:09<03:25,  9.43it/s]
  9%|▉         | 198/2129 [00:09<01:58, 16.26it/s]
  9%|▉         | 202/2129 [00:09<01:39, 19.43it/s]
 10%|▉         | 207/2129 [00:09<01:17, 24.70it/s]
 10%|▉         | 211/2129 [00:09<01:09, 27.75it/s]
 10%|█         | 215/2129 [00:10<02:58, 10.72it/s]
 10%|█         | 222/2129 [00:10<01:55, 16.47it/s]
 11%|█         | 226/2129 [00:11<03:22,  9.42it/s]
 11%|█         | 232/2129 [00:12<03:52,  8.16it/s]
 11%|█         | 235/2129 [00:14<06:28,  4.88it/s]
 11%|█         | 237/2129 [00:14<05:42,  5.53it/s]
 11%|█         | 239/2129 [00:15<07:06,  4.43it/s]
 11%|█▏        | 243/2129 [00:15<04:57,  6.34it/s]
 12%|█▏        | 246/2129 [00:16<05:56,  5.28it/s]
 12%|█▏        | 248/2129 [00:16<05:08,  6.11it/s]
 12%|█▏        | 250/2129 [00:17<07:02,  4.44it/s]
 12%|█▏        | 252/2129 [00:17<05:44,  5.44it/s]
 12%|█▏        | 258/2129 [00:18<05:08,  6.07it/s]
 12%|█▏        | 261/2129 [00:18<05:45,  5.40it/s]
 12%|█▏        | 263/2129 [00:18<04:55,  6.31it/s]
 12%|█▏        | 266/2129 [00:19<03:49,  8.10it/s]
 13%|█▎        | 270/2129 [00:19<02:45, 11.24it/s]
 13%|█▎        | 274/2129 [00:19<02:07, 14.52it/s]
 13%|█▎        | 277/2129 [00:20<04:12,  7.35it/s]
 13%|█▎        | 280/2129 [00:20<03:20,  9.23it/s]
 13%|█▎        | 287/2129 [00:21<03:42,  8.27it/s]
 14%|█▎        | 289/2129 [00:21<03:23,  9.04it/s]
 14%|█▎        | 292/2129 [00:22<04:54,  6.25it/s]
 14%|█▍        | 296/2129 [00:22<03:35,  8.49it/s]
 14%|█▍        | 298/2129 [00:23<05:30,  5.54it/s]
 14%|█▍        | 302/2129 [00:23<03:51,  7.91it/s]
 14%|█▍        | 305/2129 [00:24<07:08,  4.26it/s]
 14%|█▍        | 308/2129 [00:25<05:30,  5.52it/s]
 15%|█▍        | 312/2129 [00:25<05:46,  5.25it/s]
 15%|█▍        | 314/2129 [00:27<09:54,  3.05it/s]
 15%|█▍        | 316/2129 [00:27<08:12,  3.68it/s]
 15%|█▍        | 318/2129 [00:27<06:40,  4.52it/s]
 15%|█▌        | 321/2129 [00:28<04:44,  6.35it/s]
 15%|█▌        | 323/2129 [00:28<03:57,  7.62it/s]
 15%|█▌        | 325/2129 [00:29<06:24,  4.69it/s]
 15%|█▌        | 327/2129 [00:29<05:07,  5.85it/s]
 15%|█▌        | 329/2129 [00:30<07:20,  4.09it/s]
 16%|█▌        | 331/2129 [00:30<05:44,  5.22it/s]
 16%|█▌        | 335/2129 [00:30<03:30,  8.52it/s]
 16%|█▌        | 338/2129 [00:31<05:12,  5.74it/s]
 16%|█▌        | 341/2129 [00:31<03:51,  7.72it/s]
 16%|█▌        | 343/2129 [00:32<06:52,  4.33it/s]
 16%|█▌        | 345/2129 [00:32<05:32,  5.37it/s]
 16%|█▋        | 349/2129 [00:33<05:16,  5.63it/s]
 16%|█▋        | 351/2129 [00:34<07:07,  4.15it/s]
 17%|█▋        | 355/2129 [00:34<07:00,  4.22it/s]
 17%|█▋        | 357/2129 [00:35<08:26,  3.50it/s]
 17%|█▋        | 358/2129 [00:36<10:36,  2.78it/s]
 17%|█▋        | 361/2129 [00:37<09:53,  2.98it/s]
 17%|█▋        | 362/2129 [00:38<12:05,  2.44it/s]
 17%|█▋        | 364/2129 [00:38<09:01,  3.26it/s]
 17%|█▋        | 371/2129 [00:38<03:51,  7.60it/s]
 18%|█▊        | 374/2129 [00:39<05:14,  5.58it/s]
 18%|█▊        | 376/2129 [00:40<05:34,  5.24it/s]
 18%|█▊        | 378/2129 [00:40<04:42,  6.19it/s]
 18%|█▊        | 382/2129 [00:40<03:08,  9.25it/s]
 18%|█▊        | 385/2129 [00:41<04:44,  6.13it/s]
 18%|█▊        | 387/2129 [00:42<06:37,  4.38it/s]
 18%|█▊        | 391/2129 [00:42<06:29,  4.47it/s]
 18%|█▊        | 393/2129 [00:43<05:29,  5.27it/s]
 19%|█▊        | 395/2129 [00:43<07:15,  3.98it/s]
 19%|█▉        | 400/2129 [00:44<06:23,  4.51it/s]
 19%|█▉        | 403/2129 [00:45<04:52,  5.91it/s]
 19%|█▉        | 405/2129 [00:45<06:40,  4.30it/s]
 19%|█▉        | 410/2129 [00:46<04:03,  7.06it/s]
 20%|█▉        | 417/2129 [00:46<02:21, 12.06it/s]
 20%|█▉        | 421/2129 [00:47<03:27,  8.22it/s]
 20%|█▉        | 425/2129 [00:47<02:41, 10.56it/s]
 20%|██        | 428/2129 [00:48<03:56,  7.21it/s]
 20%|██        | 431/2129 [00:48<03:11,  8.85it/s]
 20%|██        | 434/2129 [00:49<06:22,  4.43it/s]
 20%|██        | 436/2129 [00:50<07:31,  3.75it/s]
 21%|██        | 438/2129 [00:50<06:15,  4.50it/s]
 21%|██        | 440/2129 [00:51<06:20,  4.44it/s]
 21%|██        | 443/2129 [00:51<04:30,  6.24it/s]
 21%|██        | 449/2129 [00:52<04:06,  6.81it/s]
 21%|██        | 451/2129 [00:52<03:40,  7.62it/s]
 21%|██▏       | 455/2129 [00:52<03:36,  7.75it/s]
 21%|██▏       | 457/2129 [00:53<04:12,  6.62it/s]
 22%|██▏       | 459/2129 [00:53<04:51,  5.73it/s]
 22%|██▏       | 462/2129 [00:53<03:37,  7.66it/s]
 22%|██▏       | 464/2129 [00:54<05:33,  4.99it/s]
 22%|██▏       | 466/2129 [00:55<07:34,  3.66it/s]
 22%|██▏       | 468/2129 [00:56<08:45,  3.16it/s]
 22%|██▏       | 471/2129 [00:57<08:42,  3.17it/s]
 22%|██▏       | 473/2129 [00:57<06:49,  4.04it/s]
 22%|██▏       | 476/2129 [00:57<04:45,  5.79it/s]
 22%|██▏       | 478/2129 [00:59<09:13,  2.98it/s]
 23%|██▎       | 481/2129 [00:59<06:19,  4.34it/s]
 23%|██▎       | 483/2129 [01:00<07:30,  3.65it/s]
 23%|██▎       | 485/2129 [01:00<06:39,  4.11it/s]
 23%|██▎       | 487/2129 [01:00<05:18,  5.16it/s]
 23%|██▎       | 489/2129 [01:00<04:14,  6.45it/s]
 23%|██▎       | 491/2129 [01:01<05:18,  5.15it/s]
 23%|██▎       | 493/2129 [01:01<04:10,  6.54it/s]
 23%|██▎       | 495/2129 [01:01<03:21,  8.12it/s]
 23%|██▎       | 497/2129 [01:01<02:45,  9.84it/s]
 24%|██▎       | 501/2129 [01:02<04:01,  6.74it/s]
 24%|██▎       | 503/2129 [01:02<03:33,  7.62it/s]
 24%|██▍       | 506/2129 [01:02<02:39, 10.19it/s]
 24%|██▍       | 508/2129 [01:03<05:04,  5.32it/s]
 24%|██▍       | 510/2129 [01:04<04:58,  5.42it/s]
 24%|██▍       | 512/2129 [01:04<04:03,  6.64it/s]
 24%|██▍       | 515/2129 [01:04<03:01,  8.89it/s]
 24%|██▍       | 517/2129 [01:04<03:37,  7.42it/s]
 24%|██▍       | 520/2129 [01:05<03:56,  6.79it/s]
 25%|██▍       | 522/2129 [01:05<05:08,  5.21it/s]
 25%|██▍       | 525/2129 [01:05<03:40,  7.28it/s]
 25%|██▍       | 527/2129 [01:06<05:11,  5.15it/s]
 25%|██▍       | 529/2129 [01:08<09:13,  2.89it/s]
 25%|██▍       | 530/2129 [01:08<09:49,  2.71it/s]
 25%|██▌       | 533/2129 [01:08<06:13,  4.27it/s]
 25%|██▌       | 535/2129 [01:09<05:23,  4.93it/s]
 25%|██▌       | 537/2129 [01:09<06:58,  3.81it/s]
 25%|██▌       | 541/2129 [01:10<04:09,  6.36it/s]
 26%|██▌       | 543/2129 [01:10<05:32,  4.76it/s]
 26%|██▌       | 545/2129 [01:10<04:28,  5.90it/s]
 26%|██▌       | 547/2129 [01:11<06:03,  4.35it/s]
 26%|██▌       | 549/2129 [01:12<07:30,  3.51it/s]
 26%|██▌       | 554/2129 [01:12<04:02,  6.48it/s]
 26%|██▌       | 557/2129 [01:13<04:58,  5.27it/s]
 26%|██▋       | 559/2129 [01:14<06:13,  4.21it/s]
 26%|██▋       | 561/2129 [01:14<05:03,  5.17it/s]
 26%|██▋       | 564/2129 [01:14<03:58,  6.55it/s]
 27%|██▋       | 567/2129 [01:15<03:49,  6.82it/s]
 27%|██▋       | 569/2129 [01:15<03:17,  7.89it/s]
 27%|██▋       | 571/2129 [01:15<04:26,  5.85it/s]
 27%|██▋       | 574/2129 [01:15<03:22,  7.69it/s]
 27%|██▋       | 577/2129 [01:16<04:26,  5.83it/s]
 27%|██▋       | 579/2129 [01:16<03:44,  6.89it/s]
 27%|██▋       | 581/2129 [01:17<05:22,  4.79it/s]
 27%|██▋       | 583/2129 [01:17<04:18,  5.98it/s]
 27%|██▋       | 585/2129 [01:18<04:35,  5.59it/s]
 28%|██▊       | 587/2129 [01:18<06:26,  3.99it/s]
 28%|██▊       | 589/2129 [01:19<07:53,  3.25it/s]
 28%|██▊       | 590/2129 [01:20<09:21,  2.74it/s]
 28%|██▊       | 592/2129 [01:20<06:43,  3.81it/s]
 28%|██▊       | 598/2129 [01:20<03:02,  8.41it/s]
 28%|██▊       | 601/2129 [01:21<03:32,  7.18it/s]
 28%|██▊       | 603/2129 [01:21<03:41,  6.89it/s]
 28%|██▊       | 605/2129 [01:22<04:04,  6.22it/s]
 29%|██▊       | 608/2129 [01:22<03:05,  8.21it/s]
 29%|██▊       | 610/2129 [01:22<04:20,  5.84it/s]
 29%|██▊       | 612/2129 [01:23<06:16,  4.03it/s]
 29%|██▉       | 613/2129 [01:24<08:50,  2.86it/s]
 29%|██▉       | 616/2129 [01:24<05:42,  4.41it/s]
 29%|██▉       | 622/2129 [01:25<04:34,  5.50it/s]
 29%|██▉       | 625/2129 [01:25<03:35,  6.99it/s]
 29%|██▉       | 627/2129 [01:26<05:06,  4.91it/s]
 30%|██▉       | 630/2129 [01:26<03:47,  6.59it/s]
 30%|██▉       | 632/2129 [01:27<05:15,  4.74it/s]
 30%|██▉       | 635/2129 [01:27<03:49,  6.52it/s]
 30%|██▉       | 637/2129 [01:28<05:26,  4.57it/s]
 30%|███       | 640/2129 [01:28<03:52,  6.40it/s]
 30%|███       | 642/2129 [01:29<05:32,  4.47it/s]
 30%|███       | 644/2129 [01:30<05:59,  4.13it/s]
 30%|███       | 646/2129 [01:30<04:52,  5.07it/s]
 30%|███       | 649/2129 [01:31<05:31,  4.47it/s]
 31%|███       | 652/2129 [01:31<04:01,  6.12it/s]
 31%|███       | 654/2129 [01:31<04:28,  5.49it/s]
 31%|███       | 656/2129 [01:32<06:01,  4.08it/s]
 31%|███       | 657/2129 [01:33<08:24,  2.92it/s]
 31%|███       | 658/2129 [01:34<10:25,  2.35it/s]
 31%|███       | 660/2129 [01:34<07:21,  3.33it/s]
 31%|███       | 661/2129 [01:35<09:50,  2.49it/s]
 31%|███       | 663/2129 [01:35<09:57,  2.45it/s]
 31%|███       | 665/2129 [01:36<07:03,  3.45it/s]
 31%|███▏      | 667/2129 [01:36<08:00,  3.04it/s]
 32%|███▏      | 671/2129 [01:37<04:29,  5.41it/s]
 32%|███▏      | 673/2129 [01:37<06:05,  3.99it/s]
 32%|███▏      | 676/2129 [01:37<04:12,  5.75it/s]
 32%|███▏      | 682/2129 [01:38<03:46,  6.38it/s]
 32%|███▏      | 684/2129 [01:39<05:00,  4.80it/s]
 32%|███▏      | 686/2129 [01:40<06:02,  3.98it/s]
 32%|███▏      | 688/2129 [01:41<07:02,  3.41it/s]
 32%|███▏      | 689/2129 [01:41<07:36,  3.16it/s]
 32%|███▏      | 691/2129 [01:41<05:47,  4.14it/s]
 33%|███▎      | 694/2129 [01:42<06:29,  3.68it/s]
 33%|███▎      | 696/2129 [01:43<07:31,  3.17it/s]
 33%|███▎      | 699/2129 [01:43<05:09,  4.62it/s]
 33%|███▎      | 703/2129 [01:44<05:05,  4.66it/s]
 33%|███▎      | 705/2129 [01:45<06:17,  3.78it/s]
 33%|███▎      | 707/2129 [01:46<07:18,  3.24it/s]
 33%|███▎      | 708/2129 [01:47<08:32,  2.77it/s]
 33%|███▎      | 710/2129 [01:47<06:22,  3.71it/s]
 33%|███▎      | 712/2129 [01:48<07:33,  3.13it/s]
 33%|███▎      | 713/2129 [01:48<08:14,  2.87it/s]
 34%|███▎      | 716/2129 [01:48<05:04,  4.64it/s]
 34%|███▍      | 721/2129 [01:49<04:36,  5.09it/s]
 34%|███▍      | 723/2129 [01:50<05:46,  4.06it/s]
 34%|███▍      | 724/2129 [01:51<07:42,  3.04it/s]
 34%|███▍      | 725/2129 [01:52<09:38,  2.43it/s]
 34%|███▍      | 726/2129 [01:53<11:38,  2.01it/s]
 34%|███▍      | 727/2129 [01:53<13:17,  1.76it/s]
 34%|███▍      | 728/2129 [01:54<14:41,  1.59it/s]
 34%|███▍      | 731/2129 [01:54<07:48,  2.98it/s]
 34%|███▍      | 733/2129 [01:55<08:24,  2.77it/s]
 35%|███▍      | 735/2129 [01:55<06:08,  3.78it/s]
 35%|███▍      | 739/2129 [01:56<05:35,  4.15it/s]
 35%|███▍      | 741/2129 [01:56<04:31,  5.12it/s]
 35%|███▌      | 748/2129 [01:56<02:10, 10.56it/s]
 35%|███▌      | 751/2129 [01:57<03:14,  7.07it/s]
 35%|███▌      | 754/2129 [01:59<05:52,  3.90it/s]
 36%|███▌      | 756/2129 [02:00<06:38,  3.44it/s]
 36%|███▌      | 758/2129 [02:00<05:32,  4.12it/s]
 36%|███▌      | 762/2129 [02:01<05:18,  4.29it/s]
 36%|███▌      | 763/2129 [02:02<07:00,  3.25it/s]
 36%|███▌      | 765/2129 [02:02<05:29,  4.15it/s]
 36%|███▌      | 767/2129 [02:03<09:05,  2.50it/s]
 36%|███▌      | 769/2129 [02:04<09:33,  2.37it/s]
 36%|███▋      | 772/2129 [02:04<06:19,  3.58it/s]
 36%|███▋      | 774/2129 [02:05<07:13,  3.12it/s]
 36%|███▋      | 775/2129 [02:06<07:18,  3.09it/s]
 36%|███▋      | 777/2129 [02:06<05:31,  4.08it/s]
 37%|███▋      | 780/2129 [02:06<04:45,  4.73it/s]
 37%|███▋      | 782/2129 [02:07<04:26,  5.05it/s]
 37%|███▋      | 784/2129 [02:07<03:40,  6.10it/s]
 37%|███▋      | 785/2129 [02:07<04:56,  4.53it/s]
 37%|███▋      | 786/2129 [02:07<04:26,  5.04it/s]
 37%|███▋      | 789/2129 [02:07<02:49,  7.88it/s]
 37%|███▋      | 795/2129 [02:08<02:46,  8.03it/s]
 37%|███▋      | 797/2129 [02:09<04:12,  5.27it/s]
 37%|███▋      | 798/2129 [02:10<06:03,  3.66it/s]
 38%|███▊      | 800/2129 [02:11<07:04,  3.13it/s]
 38%|███▊      | 802/2129 [02:12<07:50,  2.82it/s]
 38%|███▊      | 803/2129 [02:12<09:25,  2.35it/s]
 38%|███▊      | 805/2129 [02:13<06:46,  3.26it/s]
 38%|███▊      | 809/2129 [02:13<05:40,  3.87it/s]
 38%|███▊      | 810/2129 [02:14<07:47,  2.82it/s]
 38%|███▊      | 813/2129 [02:15<07:12,  3.04it/s]
 38%|███▊      | 816/2129 [02:15<04:58,  4.40it/s]
 38%|███▊      | 818/2129 [02:16<05:52,  3.72it/s]
 39%|███▊      | 820/2129 [02:17<05:48,  3.76it/s]
 39%|███▊      | 824/2129 [02:17<03:35,  6.05it/s]
 39%|███▉      | 827/2129 [02:17<04:03,  5.34it/s]
 39%|███▉      | 830/2129 [02:18<03:05,  7.00it/s]
 39%|███▉      | 834/2129 [02:18<02:10,  9.91it/s]
 39%|███▉      | 838/2129 [02:19<02:56,  7.32it/s]
 39%|███▉      | 840/2129 [02:19<02:34,  8.36it/s]
 40%|███▉      | 842/2129 [02:19<03:15,  6.59it/s]
 40%|███▉      | 844/2129 [02:20<04:57,  4.32it/s]
 40%|███▉      | 846/2129 [02:21<06:07,  3.49it/s]
 40%|███▉      | 848/2129 [02:22<06:59,  3.05it/s]
 40%|███▉      | 851/2129 [02:22<04:44,  4.49it/s]
 40%|████      | 853/2129 [02:23<05:50,  3.64it/s]
 40%|████      | 854/2129 [02:24<07:52,  2.70it/s]
 40%|████      | 855/2129 [02:25<09:50,  2.16it/s]
 40%|████      | 857/2129 [02:25<06:50,  3.10it/s]
 40%|████      | 860/2129 [02:26<06:30,  3.25it/s]
 40%|████      | 862/2129 [02:26<04:57,  4.26it/s]
 41%|████      | 865/2129 [02:26<04:09,  5.06it/s]
 41%|████      | 867/2129 [02:26<03:29,  6.02it/s]
 41%|████      | 871/2129 [02:26<02:13,  9.43it/s]
 41%|████      | 873/2129 [02:27<03:10,  6.58it/s]
 41%|████      | 876/2129 [02:27<02:24,  8.68it/s]
 41%|████▏     | 879/2129 [02:28<03:29,  5.98it/s]
 41%|████▏     | 882/2129 [02:28<02:37,  7.90it/s]
 42%|████▏     | 886/2129 [02:29<03:18,  6.26it/s]
 42%|████▏     | 888/2129 [02:30<04:24,  4.69it/s]
 42%|████▏     | 891/2129 [02:30<03:14,  6.35it/s]
 42%|████▏     | 895/2129 [02:31<03:40,  5.60it/s]
 42%|████▏     | 897/2129 [02:31<03:07,  6.56it/s]
 42%|████▏     | 899/2129 [02:32<04:29,  4.56it/s]
 42%|████▏     | 902/2129 [02:33<05:02,  4.05it/s]
 43%|████▎     | 905/2129 [02:33<03:41,  5.52it/s]
 43%|████▎     | 907/2129 [02:33<03:38,  5.60it/s]
 43%|████▎     | 909/2129 [02:34<04:01,  5.05it/s]
 43%|████▎     | 911/2129 [02:34<04:45,  4.27it/s]
 43%|████▎     | 913/2129 [02:35<04:40,  4.34it/s]
 43%|████▎     | 914/2129 [02:35<05:24,  3.75it/s]
 43%|████▎     | 916/2129 [02:35<04:43,  4.28it/s]
 43%|████▎     | 918/2129 [02:36<03:34,  5.65it/s]
 43%|████▎     | 920/2129 [02:36<02:46,  7.25it/s]
 43%|████▎     | 925/2129 [02:36<01:33, 12.91it/s]
 44%|████▎     | 928/2129 [02:37<02:34,  7.79it/s]
 44%|████▎     | 930/2129 [02:37<02:15,  8.85it/s]
 44%|████▍     | 936/2129 [02:37<02:02,  9.76it/s]
 44%|████▍     | 938/2129 [02:38<03:53,  5.10it/s]
 44%|████▍     | 940/2129 [02:39<04:17,  4.62it/s]
 44%|████▍     | 943/2129 [02:39<03:10,  6.22it/s]
 44%|████▍     | 945/2129 [02:41<06:14,  3.16it/s]
 44%|████▍     | 947/2129 [02:42<07:00,  2.81it/s]
 45%|████▍     | 948/2129 [02:43<08:37,  2.28it/s]
 45%|████▍     | 950/2129 [02:43<08:37,  2.28it/s]
 45%|████▍     | 952/2129 [02:44<06:23,  3.07it/s]
 45%|████▍     | 957/2129 [02:44<03:18,  5.92it/s]
 45%|████▌     | 959/2129 [02:45<04:27,  4.37it/s]
 45%|████▌     | 961/2129 [02:46<05:37,  3.46it/s]
 45%|████▌     | 963/2129 [02:46<05:57,  3.26it/s]
 45%|████▌     | 965/2129 [02:46<04:45,  4.07it/s]
 45%|████▌     | 968/2129 [02:47<04:57,  3.90it/s]
 46%|████▌     | 969/2129 [02:47<04:33,  4.24it/s]
 46%|████▌     | 970/2129 [02:48<05:01,  3.84it/s]
 46%|████▌     | 972/2129 [02:48<03:50,  5.02it/s]
 46%|████▌     | 973/2129 [02:48<04:29,  4.28it/s]
 46%|████▌     | 974/2129 [02:49<05:26,  3.54it/s]
 46%|████▌     | 976/2129 [02:49<03:46,  5.09it/s]
 46%|████▌     | 977/2129 [02:49<04:57,  3.87it/s]
 46%|████▌     | 979/2129 [02:49<03:29,  5.50it/s]
 46%|████▌     | 981/2129 [02:50<03:11,  6.00it/s]
 46%|████▌     | 983/2129 [02:50<02:28,  7.71it/s]
 46%|████▋     | 985/2129 [02:50<02:03,  9.24it/s]
 46%|████▋     | 988/2129 [02:50<02:15,  8.39it/s]
 47%|████▋     | 990/2129 [02:50<01:54,  9.91it/s]
 47%|████▋     | 993/2129 [02:51<01:56,  9.78it/s]
 47%|████▋     | 995/2129 [02:51<01:48, 10.47it/s]
 47%|████▋     | 1001/2129 [02:52<01:51, 10.16it/s]
 47%|████▋     | 1003/2129 [02:52<02:35,  7.23it/s]
 47%|████▋     | 1005/2129 [02:52<02:16,  8.23it/s]
 47%|████▋     | 1007/2129 [02:53<02:23,  7.83it/s]
 47%|████▋     | 1010/2129 [02:53<02:28,  7.53it/s]
 48%|████▊     | 1012/2129 [02:54<03:19,  5.60it/s]
 48%|████▊     | 1015/2129 [02:54<02:44,  6.77it/s]
 48%|████▊     | 1016/2129 [02:54<03:38,  5.10it/s]
 48%|████▊     | 1018/2129 [02:54<02:55,  6.33it/s]
 48%|████▊     | 1019/2129 [02:55<03:23,  5.46it/s]
 48%|████▊     | 1021/2129 [02:55<02:34,  7.15it/s]
 48%|████▊     | 1023/2129 [02:56<04:17,  4.30it/s]
 48%|████▊     | 1024/2129 [02:57<06:12,  2.97it/s]
 48%|████▊     | 1027/2129 [02:57<03:45,  4.88it/s]
 48%|████▊     | 1029/2129 [02:58<05:02,  3.63it/s]
 48%|████▊     | 1030/2129 [02:58<05:07,  3.57it/s]
 49%|████▊     | 1033/2129 [02:58<03:11,  5.74it/s]
 49%|████▉     | 1038/2129 [02:58<01:46, 10.28it/s]
 49%|████▉     | 1041/2129 [02:59<02:49,  6.41it/s]
 49%|████▉     | 1044/2129 [02:59<02:11,  8.22it/s]
 49%|████▉     | 1048/2129 [03:00<02:17,  7.84it/s]
 49%|████▉     | 1050/2129 [03:00<02:03,  8.71it/s]
 49%|████▉     | 1052/2129 [03:00<02:57,  6.05it/s]
 50%|████▉     | 1054/2129 [03:01<02:33,  7.00it/s]
 50%|████▉     | 1056/2129 [03:01<03:40,  4.87it/s]
 50%|████▉     | 1058/2129 [03:01<03:01,  5.89it/s]
 50%|████▉     | 1060/2129 [03:02<03:36,  4.94it/s]
 50%|████▉     | 1062/2129 [03:02<02:54,  6.10it/s]
 50%|████▉     | 1064/2129 [03:03<03:20,  5.32it/s]
 50%|█████     | 1066/2129 [03:03<02:38,  6.69it/s]
 50%|█████     | 1068/2129 [03:04<04:22,  4.04it/s]
 50%|█████     | 1070/2129 [03:05<05:26,  3.24it/s]
 50%|█████     | 1071/2129 [03:06<07:09,  2.47it/s]
 50%|█████     | 1073/2129 [03:06<05:14,  3.36it/s]
 50%|█████     | 1075/2129 [03:06<03:52,  4.53it/s]
 51%|█████     | 1077/2129 [03:07<04:58,  3.53it/s]
 51%|█████     | 1080/2129 [03:08<05:08,  3.40it/s]
 51%|█████     | 1082/2129 [03:08<03:58,  4.39it/s]
 51%|█████     | 1085/2129 [03:09<04:17,  4.06it/s]
 51%|█████     | 1089/2129 [03:09<02:44,  6.31it/s]
 51%|█████     | 1091/2129 [03:09<03:10,  5.44it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 293.63it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 0], [np.int64(2), False, 7], [np.int64(3), False, 11], [np.int64(4), False, 8], [np.int64(5), False, 7], [np.int64(6), False, 8], [np.int64(7), False, 0], [np.int64(9), False, 10], [np.int64(12), False, 13], [np.int64(13), False, 8]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.7017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8247, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [29:47<1:32:46, 113.60s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [29:48<1:03:38, 79.56s/it]

tensor(11.7013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9458, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0626, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [29:48<20:31, 27.36s/it]

tensor(11.7046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1216, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1599, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [29:48<09:39, 13.47s/it]

tensor(11.7059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1875, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2174, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [29:48<04:32,  6.66s/it]

tensor(11.7107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2472, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2784, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [29:49<02:09,  3.32s/it]

tensor(11.7117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3042, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3175, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [29:49<01:02,  1.68s/it]

tensor(11.7075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3278, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3346, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [29:49<00:30,  1.13it/s]

tensor(11.7029, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3395, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.7008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3428, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [29:49<00:16,  2.04it/s]

tensor(11.6985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3577, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3712, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [29:49<00:09,  3.37it/s]

tensor(11.6939, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3779, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3834, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [29:50<00:05,  4.93it/s]

tensor(11.6896, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3829, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6875, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3828, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [29:50<00:04,  6.40it/s]

tensor(11.6853, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3856, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3857, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [29:50<00:03,  7.48it/s]

tensor(11.6818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3845, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6805, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3833, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [29:50<00:02,  8.07it/s]

tensor(11.6794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3826, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3817, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [29:51<00:02,  8.46it/s]

tensor(11.6767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3807, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3831, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [29:51<00:02,  8.62it/s]

tensor(11.6735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3843, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3861, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [29:51<00:01,  8.60it/s]

tensor(11.6706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3870, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3886, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [29:51<00:01,  8.71it/s]

tensor(11.6680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3946, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [29:52<00:01,  8.71it/s]

tensor(11.6662, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3964, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3994, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [29:52<00:01,  8.81it/s]

tensor(11.6641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4041, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4053, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [29:52<00:01,  8.79it/s]

tensor(11.6620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4091, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4110, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [29:52<00:00,  8.71it/s]

tensor(11.6601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4131, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [29:52<00:00,  8.69it/s]

tensor(11.6582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4124, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4136, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [29:53<00:00,  8.60it/s]

tensor(11.6566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4167, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [29:53<00:00,  8.72it/s]

tensor(11.6547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.6540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4188, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [29:53<00:00,  5.98s/it]

tensor(11.6528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4198, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0021615028381347656
PCA20 shape : (2129, 20)
PCA20 finite: True
mclust K    : 14

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : E18.5
Seed        : 9
Spots       : 2129
Target K    : 14
Predicted K : 14
Embedding   : (2129, 64)
ARI         : 0.547170650939
NMI         : 0.582059062654
Runtime     : 1837.79 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/E185_seed9

==============================================================================================================
PRAGA RUN | S2-E15 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 6.417e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:26, 11.04it/s]

tensor(17.8598, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3791, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.8635, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2366, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.7748, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3044, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:26, 11.32it/s]

tensor(17.6844, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5624, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6079, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9911, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5474, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5734, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:22, 12.77it/s]

tensor(17.5012, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2949, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4581, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1421, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4129, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1037, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:00<00:21, 13.22it/s]

tensor(17.3589, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1664, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2935, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2257, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5605, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:21, 13.35it/s]

tensor(17.1611, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8739, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1129, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2551, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0765, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6980, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.40it/s]

tensor(17.0424, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1955, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9944, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7431, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9287, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3355, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:01<00:20, 13.36it/s]

tensor(16.8529, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9687, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7769, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6377, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7083, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3405, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:20, 13.38it/s]

tensor(16.6422, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0725, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5746, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8320, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5016, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6153, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:01<00:20, 13.40it/s]

tensor(16.4218, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3352, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2458, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2415, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0893, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:20, 13.42it/s]

tensor(16.1422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9482, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0380, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7097, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:02<00:19, 13.44it/s]

tensor(15.8151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6090, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4389, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:19, 13.43it/s]

tensor(15.4419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3678, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3044, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2492, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:02<00:19, 13.46it/s]

tensor(15.0732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2012, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1591, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1241, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.49it/s]

tensor(14.8259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0953, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0727, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0558, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:03<00:18, 13.49it/s]

tensor(14.5877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0437, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:18, 13.51it/s]

tensor(14.3578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:03<00:18, 13.47it/s]

tensor(14.2041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:04<00:18, 13.50it/s]

tensor(14.0672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0224, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:04<00:18, 13.47it/s]

tensor(13.9354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:04<00:17, 13.48it/s]

tensor(13.8162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:04<00:17, 13.45it/s]

tensor(13.7121, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6517, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.41it/s]

tensor(13.6227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5663, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:05<00:17, 13.47it/s]

tensor(13.5387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.44it/s]

tensor(13.4605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:05<00:16, 13.42it/s]

tensor(13.3909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:05<00:16, 13.43it/s]

tensor(13.3261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:05<00:16, 13.40it/s]

tensor(13.2633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:16, 13.44it/s]

tensor(13.2060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:06<00:15, 13.41it/s]

tensor(13.1528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:15, 13.43it/s]

tensor(13.1024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:06<00:15, 13.36it/s]

tensor(13.0543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:15, 13.44it/s]

tensor(13.0086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:07<00:15, 13.40it/s]

tensor(12.9649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9507, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9369, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:14, 13.43it/s]

tensor(12.9234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([159, 115,  85, 218,  75, 336,  48, 119,  34,  97,  30, 199, 310, 114])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<02:12, 14.64it/s]
  0%|          | 7/1939 [00:00<01:00, 32.06it/s]
  1%|          | 11/1939 [00:00<01:14, 26.02it/s]
  1%|          | 16/1939 [00:00<01:00, 32.00it/s]
  1%|          | 21/1939 [00:00<00:54, 35.10it/s]
  1%|▏         | 26/1939 [00:00<00:49, 38.56it/s]
  2%|▏         | 33/1939 [00:00<00:41, 46.43it/s]
  2%|▏         | 41/1939 [00:01<00:53, 35.35it/s]
  2%|▏         | 46/1939 [00:01<01:52, 16.83it/s]
  3%|▎         | 50/1939 [00:02<02:28, 12.71it/s]
  3%|▎         | 53/1939 [00:02<02:36, 12.08it/s]
  3%|▎         | 56/1939 [00:03<03:30,  8.94it/s]
  3%|▎         | 58/1939 [00:03<03:16,  9.60it/s]
  3%|▎         | 60/1939 [00:04<04:19,  7.23it/s]
  3%|▎         | 64/1939 [00:04<03:03, 10.22it/s]
  3%|▎         | 66/1939 [00:04<03:05, 10.11it/s]
  4%|▎         | 69/1939 [00:04<02:32, 12.23it/s]
  4%|▎         | 71/1939 [00:05<04:12,  7.41it/s]
  4%|▍         | 73/1939 [00:05<04:04,  7.63it/s]
  4%|▍         | 75/1939 [00:05<03:32,  8.77it/s]
  4%|▍         | 78/1939 [00:05<03:07,  9.94it/s]
  4%|▍         | 80/1939 [00:06<05:07,  6.04it/s]
  4%|▍         | 82/1939 [00:07<07:01,  4.40it/s]
  4%|▍         | 83/1939 [00:07<08:39,  3.58it/s]
  4%|▍         | 84/1939 [00:08<08:11,  3.77it/s]
  4%|▍         | 86/1939 [00:08<06:19,  4.88it/s]
  4%|▍         | 87/1939 [00:08<06:04,  5.08it/s]
  5%|▍         | 89/1939 [00:08<04:28,  6.89it/s]
  5%|▍         | 94/1939 [00:08<02:57, 10.41it/s]
  5%|▍         | 96/1939 [00:09<03:14,  9.46it/s]
  5%|▌         | 98/1939 [00:09<02:49, 10.89it/s]
  5%|▌         | 100/1939 [00:09<03:06,  9.87it/s]
 33%|███▎      | 100/300 [00:21<00:14, 13.43it/s]]
  5%|▌         | 106/1939 [00:10<03:00, 10.13it/s]
  6%|▌         | 108/1939 [00:10<03:01, 10.09it/s]
  6%|▌         | 111/1939 [00:10<02:21, 12.88it/s]
  6%|▌         | 114/1939 [00:10<03:17,  9.25it/s]
  6%|▌         | 116/1939 [00:11<03:34,  8.49it/s]
  6%|▌         | 118/1939 [00:11<04:44,  6.40it/s]
  6%|▌         | 120/1939 [00:12<04:34,  6.64it/s]
  6%|▌         | 121/1939 [00:12<04:19,  7.00it/s]
  6%|▋         | 123/1939 [00:12<03:44,  8.09it/s]
  6%|▋         | 126/1939 [00:12<02:39, 11.33it/s]
  7%|▋         | 128/1939 [00:12<02:48, 10.74it/s]
  7%|▋         | 130/1939 [00:12<02:30, 12.00it/s]
  7%|▋         | 132/1939 [00:12<02:46, 10.87it/s]
  7%|▋         | 135/1939 [00:13<04:01,  7.48it/s]
  7%|▋         | 137/1939 [00:13<04:00,  7.48it/s]
  7%|▋         | 138/1939 [00:14<05:58,  5.02it/s]
  7%|▋         | 139/1939 [00:14<07:33,  3.97it/s]
  7%|▋         | 141/1939 [00:15<06:13,  4.81it/s]
  7%|▋         | 142/1939 [00:15<05:53,  5.08it/s]
  7%|▋         | 144/1939 [00:15<04:20,  6.88it/s]
  7%|▋         | 145/1939 [00:15<04:45,  6.29it/s]
  8%|▊         | 147/1939 [00:15<03:34,  8.36it/s]
  8%|▊         | 149/1939 [00:16<04:23,  6.79it/s]
  8%|▊         | 151/1939 [00:16<03:28,  8.59it/s]
  8%|▊         | 153/1939 [00:16<03:28,  8.58it/s]
  8%|▊         | 156/1939 [00:16<02:31, 11.77it/s]
  8%|▊         | 158/1939 [00:17<04:52,  6.08it/s]
  8%|▊         | 160/1939 [00:18<06:36,  4.49it/s]
  8%|▊         | 161/1939 [00:18<06:32,  4.52it/s]
  8%|▊         | 162/1939 [00:18<08:04,  3.67it/s]
  8%|▊         | 163/1939 [00:19<09:30,  3.12it/s]
  8%|▊         | 164/1939 [00:19<08:49,  3.35it/s]
  9%|▊         | 166/1939 [00:19<05:52,  5.03it/s]
  9%|▉         | 170/1939 [00:20<05:05,  5.79it/s]
  9%|▉         | 172/1939 [00:20<04:12,  6.99it/s]
  9%|▉         | 177/1939 [00:20<02:25, 12.11it/s]
  9%|▉         | 183/1939 [00:20<01:32, 18.89it/s]
 10%|▉         | 187/1939 [00:21<02:34, 11.33it/s]
 10%|▉         | 191/1939 [00:21<02:04, 14.04it/s]
 10%|█         | 194/1939 [00:21<01:53, 15.31it/s]
 10%|█         | 199/1939 [00:21<01:53, 15.29it/s]
 10%|█         | 202/1939 [00:21<01:53, 15.34it/s]
 11%|█         | 204/1939 [00:22<02:02, 14.11it/s]
 11%|█         | 206/1939 [00:22<02:21, 12.21it/s]
 11%|█         | 208/1939 [00:22<02:20, 12.31it/s]
 11%|█         | 210/1939 [00:22<02:09, 13.34it/s]
 11%|█         | 212/1939 [00:23<03:10,  9.05it/s]
 11%|█         | 214/1939 [00:23<04:26,  6.48it/s]
 11%|█         | 215/1939 [00:23<04:14,  6.78it/s]
 11%|█         | 217/1939 [00:23<03:29,  8.23it/s]
 11%|█▏        | 219/1939 [00:24<04:29,  6.37it/s]
 11%|█▏        | 222/1939 [00:24<03:33,  8.03it/s]
 12%|█▏        | 224/1939 [00:25<04:18,  6.64it/s]
 12%|█▏        | 227/1939 [00:25<03:10,  8.97it/s]
 12%|█▏        | 229/1939 [00:25<03:14,  8.81it/s]
 12%|█▏        | 231/1939 [00:25<03:22,  8.43it/s]
 12%|█▏        | 233/1939 [00:25<03:32,  8.02it/s]
 12%|█▏        | 236/1939 [00:26<03:13,  8.79it/s]
 12%|█▏        | 238/1939 [00:26<02:48, 10.09it/s]
 12%|█▏        | 240/1939 [00:26<03:35,  7.88it/s]
 12%|█▏        | 241/1939 [00:27<05:18,  5.32it/s]
 13%|█▎        | 243/1939 [00:27<06:02,  4.68it/s]
 13%|█▎        | 244/1939 [00:28<07:31,  3.75it/s]
 13%|█▎        | 245/1939 [00:28<07:18,  3.87it/s]
 13%|█▎        | 246/1939 [00:28<07:00,  4.03it/s]
 13%|█▎        | 248/1939 [00:28<05:38,  4.99it/s]
 13%|█▎        | 250/1939 [00:29<06:34,  4.28it/s]
 13%|█▎        | 251/1939 [00:29<07:08,  3.94it/s]
 13%|█▎        | 252/1939 [00:30<06:52,  4.09it/s]
 13%|█▎        | 254/1939 [00:30<04:58,  5.65it/s]
 13%|█▎        | 257/1939 [00:30<04:03,  6.90it/s]
 13%|█▎        | 258/1939 [00:31<05:38,  4.97it/s]
 13%|█▎        | 260/1939 [00:31<04:52,  5.74it/s]
 14%|█▎        | 262/1939 [00:31<03:54,  7.16it/s]
 14%|█▎        | 263/1939 [00:31<04:01,  6.93it/s]
 14%|█▎        | 264/1939 [00:31<04:05,  6.83it/s]
 14%|█▍        | 267/1939 [00:31<02:39, 10.49it/s]
 14%|█▍        | 269/1939 [00:32<03:32,  7.85it/s]
 14%|█▍        | 271/1939 [00:32<03:51,  7.19it/s]
 14%|█▍        | 273/1939 [00:32<04:17,  6.47it/s]
 14%|█▍        | 274/1939 [00:33<05:17,  5.25it/s]
 14%|█▍        | 276/1939 [00:33<04:00,  6.90it/s]
 14%|█▍        | 279/1939 [00:33<03:31,  7.87it/s]
 14%|█▍        | 281/1939 [00:33<03:08,  8.81it/s]
 15%|█▍        | 283/1939 [00:34<02:42, 10.21it/s]
 15%|█▍        | 285/1939 [00:34<03:37,  7.60it/s]
 15%|█▍        | 287/1939 [00:35<04:58,  5.53it/s]
 15%|█▍        | 288/1939 [00:35<05:15,  5.24it/s]
 15%|█▍        | 290/1939 [00:35<04:04,  6.75it/s]
 15%|█▌        | 292/1939 [00:35<03:12,  8.54it/s]
 15%|█▌        | 294/1939 [00:36<04:46,  5.73it/s]
 15%|█▌        | 296/1939 [00:36<05:28,  5.01it/s]
 15%|█▌        | 298/1939 [00:37<06:29,  4.22it/s]
 15%|█▌        | 300/1939 [00:37<06:55,  3.94it/s]
 16%|█▌        | 303/1939 [00:38<06:23,  4.26it/s]
 16%|█▌        | 304/1939 [00:38<06:58,  3.90it/s]
 16%|█▌        | 306/1939 [00:38<05:17,  5.15it/s]
 16%|█▌        | 307/1939 [00:39<05:30,  4.93it/s]
 16%|█▌        | 308/1939 [00:39<06:00,  4.52it/s]
 16%|█▌        | 310/1939 [00:39<04:16,  6.34it/s]
 16%|█▌        | 312/1939 [00:39<03:52,  7.00it/s]
 16%|█▌        | 313/1939 [00:40<04:43,  5.74it/s]
 16%|█▌        | 315/1939 [00:40<04:18,  6.29it/s]
 16%|█▋        | 316/1939 [00:40<05:20,  5.06it/s]
 16%|█▋        | 317/1939 [00:41<06:02,  4.47it/s]
 16%|█▋        | 318/1939 [00:41<06:11,  4.37it/s]
 16%|█▋        | 319/1939 [00:41<06:11,  4.36it/s]
 17%|█▋        | 320/1939 [00:41<06:43,  4.01it/s]
 17%|█▋        | 321/1939 [00:41<06:13,  4.34it/s]
 17%|█▋        | 322/1939 [00:42<05:38,  4.78it/s]
 17%|█▋        | 324/1939 [00:42<03:46,  7.14it/s]
 17%|█▋        | 327/1939 [00:42<04:12,  6.38it/s]
 17%|█▋        | 330/1939 [00:42<02:55,  9.17it/s]
 17%|█▋        | 332/1939 [00:43<04:07,  6.50it/s]
 17%|█▋        | 334/1939 [00:43<03:23,  7.90it/s]
 17%|█▋        | 339/1939 [00:44<03:14,  8.25it/s]
 18%|█▊        | 342/1939 [00:44<02:34, 10.30it/s]
 18%|█▊        | 348/1939 [00:44<02:33, 10.37it/s]
 18%|█▊        | 350/1939 [00:44<02:20, 11.27it/s]
 18%|█▊        | 352/1939 [00:45<02:49,  9.36it/s]
 18%|█▊        | 354/1939 [00:45<02:51,  9.26it/s]
 18%|█▊        | 356/1939 [00:46<04:10,  6.32it/s]
 19%|█▊        | 360/1939 [00:46<04:04,  6.46it/s]
 19%|█▊        | 363/1939 [00:47<03:32,  7.42it/s]
 19%|█▉        | 366/1939 [00:47<04:04,  6.43it/s]
 19%|█▉        | 369/1939 [00:47<03:06,  8.41it/s]
 19%|█▉        | 371/1939 [00:48<04:08,  6.31it/s]
 19%|█▉        | 373/1939 [00:48<05:08,  5.08it/s]
 19%|█▉        | 376/1939 [00:49<04:15,  6.11it/s]
 19%|█▉        | 378/1939 [00:49<05:06,  5.08it/s]
 20%|█▉        | 380/1939 [00:50<05:45,  4.51it/s]
 20%|█▉        | 381/1939 [00:50<05:43,  4.53it/s]
 20%|█▉        | 382/1939 [00:51<07:32,  3.44it/s]
 20%|█▉        | 384/1939 [00:51<05:58,  4.34it/s]
 20%|█▉        | 387/1939 [00:51<04:33,  5.68it/s]
 20%|██        | 388/1939 [00:51<04:37,  5.60it/s]
 20%|██        | 389/1939 [00:52<05:25,  4.77it/s]
 20%|██        | 390/1939 [00:52<04:56,  5.22it/s]
 20%|██        | 391/1939 [00:52<04:35,  5.63it/s]
 20%|██        | 392/1939 [00:52<04:39,  5.53it/s]
 20%|██        | 393/1939 [00:52<04:39,  5.53it/s]
 20%|██        | 394/1939 [00:53<04:20,  5.93it/s]
 20%|██        | 396/1939 [00:53<03:17,  7.81it/s]
 20%|██        | 397/1939 [00:53<03:30,  7.32it/s]
 21%|██        | 398/1939 [00:53<03:59,  6.45it/s]
 21%|██        | 400/1939 [00:53<02:51,  8.97it/s]
 21%|██        | 404/1939 [00:53<02:12, 11.63it/s]
 21%|██        | 406/1939 [00:54<02:31, 10.09it/s]
 21%|██        | 408/1939 [00:54<02:39,  9.63it/s]
 21%|██        | 411/1939 [00:54<02:30, 10.16it/s]
 21%|██▏       | 413/1939 [00:55<03:50,  6.62it/s]
 21%|██▏       | 415/1939 [00:55<03:34,  7.12it/s]
 21%|██▏       | 416/1939 [00:56<05:29,  4.62it/s]
 22%|██▏       | 417/1939 [00:56<05:22,  4.72it/s]
 22%|██▏       | 419/1939 [00:56<04:38,  5.45it/s]
 22%|██▏       | 422/1939 [00:56<03:42,  6.83it/s]
 22%|██▏       | 424/1939 [00:57<03:02,  8.29it/s]
 22%|██▏       | 426/1939 [00:57<02:55,  8.61it/s]
 22%|██▏       | 428/1939 [00:57<02:58,  8.47it/s]
 22%|██▏       | 431/1939 [00:57<02:14, 11.22it/s]
 23%|██▎       | 439/1939 [00:57<01:05, 22.84it/s]
 23%|██▎       | 443/1939 [00:58<02:00, 12.41it/s]
 23%|██▎       | 446/1939 [00:58<01:44, 14.28it/s]
 23%|██▎       | 449/1939 [00:58<01:33, 16.00it/s]
 23%|██▎       | 455/1939 [00:58<01:06, 22.35it/s]
 24%|██▎       | 459/1939 [00:58<00:59, 24.72it/s]
 24%|██▍       | 463/1939 [00:58<00:54, 27.06it/s]
 24%|██▍       | 470/1939 [00:59<01:26, 16.89it/s]
 24%|██▍       | 473/1939 [00:59<01:24, 17.30it/s]
 25%|██▍       | 476/1939 [01:00<02:00, 12.19it/s]
 25%|██▍       | 479/1939 [01:00<02:02, 11.88it/s]
 25%|██▍       | 483/1939 [01:00<01:40, 14.49it/s]
 25%|██▌       | 488/1939 [01:00<01:17, 18.77it/s]
 25%|██▌       | 491/1939 [01:01<02:33,  9.43it/s]
 25%|██▌       | 493/1939 [01:01<02:43,  8.84it/s]
 26%|██▌       | 495/1939 [01:02<03:34,  6.74it/s]
 26%|██▌       | 497/1939 [01:03<04:18,  5.58it/s]
 26%|██▌       | 500/1939 [01:03<04:30,  5.31it/s]
 26%|██▌       | 503/1939 [01:03<03:21,  7.12it/s]
 26%|██▌       | 505/1939 [01:04<04:05,  5.84it/s]
 26%|██▋       | 509/1939 [01:04<02:43,  8.73it/s]
 26%|██▋       | 511/1939 [01:04<02:41,  8.84it/s]
 27%|██▋       | 514/1939 [01:04<02:07, 11.21it/s]
 27%|██▋       | 521/1939 [01:04<01:13, 19.36it/s]
 27%|██▋       | 528/1939 [01:04<00:51, 27.41it/s]
 28%|██▊       | 535/1939 [01:05<00:39, 35.20it/s]
 28%|██▊       | 540/1939 [01:06<01:54, 12.23it/s]
 28%|██▊       | 544/1939 [01:06<01:42, 13.55it/s]
 28%|██▊       | 548/1939 [01:07<02:18, 10.07it/s]
 28%|██▊       | 551/1939 [01:07<02:18, 10.04it/s]
 29%|██▊       | 553/1939 [01:07<03:03,  7.56it/s]
 29%|██▊       | 556/1939 [01:08<03:21,  6.86it/s]
 29%|██▉       | 558/1939 [01:09<03:52,  5.93it/s]
 29%|██▉       | 560/1939 [01:09<03:22,  6.81it/s]
 29%|██▉       | 562/1939 [01:09<04:07,  5.56it/s]
 29%|██▉       | 565/1939 [01:09<02:59,  7.65it/s]
 29%|██▉       | 567/1939 [01:10<03:15,  7.01it/s]
 29%|██▉       | 569/1939 [01:10<03:14,  7.05it/s]
 29%|██▉       | 571/1939 [01:11<03:58,  5.73it/s]
 29%|██▉       | 572/1939 [01:11<04:11,  5.44it/s]
 30%|██▉       | 574/1939 [01:11<03:49,  5.95it/s]
 30%|██▉       | 575/1939 [01:11<03:59,  5.70it/s]
 30%|██▉       | 577/1939 [01:11<03:02,  7.48it/s]
 30%|██▉       | 579/1939 [01:12<02:51,  7.93it/s]
 30%|██▉       | 581/1939 [01:12<02:18,  9.80it/s]
 30%|███       | 583/1939 [01:12<02:27,  9.18it/s]
 30%|███       | 585/1939 [01:12<02:37,  8.62it/s]
 30%|███       | 587/1939 [01:12<02:37,  8.57it/s]
 30%|███       | 589/1939 [01:13<03:51,  5.84it/s]
 30%|███       | 591/1939 [01:13<03:05,  7.26it/s]
 31%|███       | 593/1939 [01:14<05:43,  3.91it/s]
 31%|███       | 595/1939 [01:15<06:05,  3.68it/s]
 31%|███       | 597/1939 [01:15<04:35,  4.87it/s]
 31%|███       | 599/1939 [01:15<03:52,  5.77it/s]
 31%|███       | 601/1939 [01:15<03:32,  6.29it/s]
 31%|███       | 603/1939 [01:15<02:54,  7.67it/s]
 31%|███       | 605/1939 [01:16<03:52,  5.74it/s]
 31%|███▏      | 607/1939 [01:16<03:24,  6.52it/s]
 31%|███▏      | 608/1939 [01:17<03:57,  5.61it/s]
 32%|███▏      | 611/1939 [01:17<03:43,  5.94it/s]
 32%|███▏      | 612/1939 [01:17<04:03,  5.44it/s]
 32%|███▏      | 613/1939 [01:18<05:11,  4.26it/s]
 32%|███▏      | 614/1939 [01:18<04:50,  4.56it/s]
 32%|███▏      | 615/1939 [01:18<04:47,  4.60it/s]
 32%|███▏      | 616/1939 [01:18<04:51,  4.54it/s]
 32%|███▏      | 617/1939 [01:19<04:57,  4.45it/s]
 32%|███▏      | 618/1939 [01:19<04:56,  4.46it/s]
 32%|███▏      | 620/1939 [01:19<04:16,  5.14it/s]
 32%|███▏      | 621/1939 [01:19<04:23,  5.00it/s]
 32%|███▏      | 622/1939 [01:20<04:24,  4.98it/s]
 32%|███▏      | 625/1939 [01:20<02:34,  8.52it/s]
 32%|███▏      | 629/1939 [01:20<01:55, 11.32it/s]
 33%|███▎      | 631/1939 [01:20<02:04, 10.52it/s]
 33%|███▎      | 633/1939 [01:21<03:18,  6.59it/s]
 33%|███▎      | 636/1939 [01:21<02:54,  7.46it/s]
 33%|███▎      | 638/1939 [01:21<02:27,  8.80it/s]
 33%|███▎      | 640/1939 [01:21<02:49,  7.67it/s]
 33%|███▎      | 643/1939 [01:22<02:32,  8.49it/s]
 33%|███▎      | 645/1939 [01:22<02:10,  9.89it/s]
 33%|███▎      | 647/1939 [01:22<03:17,  6.55it/s]
 33%|███▎      | 649/1939 [01:23<03:06,  6.93it/s]
 34%|███▎      | 650/1939 [01:23<04:32,  4.73it/s]
 34%|███▎      | 651/1939 [01:23<04:33,  4.71it/s]
 34%|███▎      | 652/1939 [01:24<06:05,  3.52it/s]
 34%|███▎      | 654/1939 [01:24<04:48,  4.45it/s]
 34%|███▍      | 656/1939 [01:25<04:10,  5.12it/s]
 34%|███▍      | 658/1939 [01:25<03:35,  5.94it/s]
 34%|███▍      | 659/1939 [01:25<03:54,  5.46it/s]
 34%|███▍      | 662/1939 [01:25<02:32,  8.37it/s]
 34%|███▍      | 665/1939 [01:25<02:16,  9.33it/s]
 34%|███▍      | 667/1939 [01:26<02:16,  9.34it/s]
 35%|███▍      | 669/1939 [01:26<02:19,  9.08it/s]
 35%|███▍      | 672/1939 [01:26<02:18,  9.13it/s]
 35%|███▍      | 673/1939 [01:27<03:06,  6.78it/s]
 35%|███▍      | 675/1939 [01:27<02:38,  7.99it/s]
 35%|███▍      | 676/1939 [01:27<02:41,  7.82it/s]
 35%|███▍      | 677/1939 [01:27<02:53,  7.27it/s]
 35%|███▍      | 678/1939 [01:28<04:44,  4.43it/s]
 35%|███▌      | 680/1939 [01:28<03:50,  5.47it/s]
 35%|███▌      | 682/1939 [01:28<02:59,  7.01it/s]
 35%|███▌      | 683/1939 [01:28<02:51,  7.31it/s]
 35%|███▌      | 685/1939 [01:28<02:26,  8.56it/s]
 35%|███▌      | 687/1939 [01:28<02:14,  9.29it/s]
 36%|███▌      | 689/1939 [01:29<03:31,  5.92it/s]
 36%|███▌      | 691/1939 [01:29<03:42,  5.60it/s]
 36%|███▌      | 693/1939 [01:30<03:05,  6.72it/s]
 36%|███▌      | 696/1939 [01:30<02:09,  9.61it/s]
 36%|███▌      | 702/1939 [01:30<01:11, 17.39it/s]
 37%|███▋      | 710/1939 [01:30<00:43, 28.04it/s]
 37%|███▋      | 717/1939 [01:30<00:34, 35.63it/s]
 37%|███▋      | 722/1939 [01:30<00:32, 38.00it/s]
 37%|███▋      | 727/1939 [01:30<00:45, 26.47it/s]
 38%|███▊      | 731/1939 [01:31<01:04, 18.74it/s]
 38%|███▊      | 734/1939 [01:31<01:47, 11.17it/s]
 38%|███▊      | 737/1939 [01:32<01:44, 11.45it/s]
 38%|███▊      | 739/1939 [01:32<02:22,  8.42it/s]
 38%|███▊      | 741/1939 [01:32<02:06,  9.50it/s]
 38%|███▊      | 743/1939 [01:33<02:07,  9.38it/s]
 38%|███▊      | 745/1939 [01:33<03:00,  6.61it/s]
 39%|███▊      | 747/1939 [01:33<02:29,  7.99it/s]
 39%|███▊      | 749/1939 [01:34<03:19,  5.95it/s]
 39%|███▊      | 751/1939 [01:34<03:25,  5.77it/s]
 39%|███▉      | 753/1939 [01:34<02:45,  7.15it/s]
 39%|███▉      | 755/1939 [01:35<02:43,  7.24it/s]
 39%|███▉      | 757/1939 [01:35<02:36,  7.55it/s]
 39%|███▉      | 759/1939 [01:35<02:53,  6.79it/s]
 39%|███▉      | 760/1939 [01:35<03:03,  6.43it/s]
 39%|███▉      | 763/1939 [01:36<02:14,  8.74it/s]
 39%|███▉      | 765/1939 [01:36<01:57,  9.96it/s]
 40%|███▉      | 767/1939 [01:36<02:19,  8.38it/s]
 40%|███▉      | 769/1939 [01:36<02:58,  6.55it/s]
 40%|███▉      | 770/1939 [01:37<03:30,  5.55it/s]
 40%|███▉      | 771/1939 [01:37<04:23,  4.44it/s]
 40%|███▉      | 772/1939 [01:37<04:18,  4.51it/s]
 40%|███▉      | 773/1939 [01:38<05:10,  3.76it/s]
 40%|███▉      | 775/1939 [01:38<04:10,  4.65it/s]
 40%|████      | 776/1939 [01:38<03:41,  5.24it/s]
 40%|████      | 777/1939 [01:38<03:28,  5.57it/s]
 40%|████      | 779/1939 [01:39<02:55,  6.60it/s]
 40%|████      | 780/1939 [01:39<02:53,  6.66it/s]
 40%|████      | 782/1939 [01:39<02:23,  8.08it/s]
 40%|████      | 784/1939 [01:39<02:14,  8.58it/s]
 41%|████      | 787/1939 [01:39<01:54, 10.09it/s]
 41%|████      | 789/1939 [01:40<02:00,  9.52it/s]
 41%|████      | 792/1939 [01:40<01:30, 12.66it/s]
 41%|████      | 794/1939 [01:40<02:23,  7.99it/s]
 41%|████      | 797/1939 [01:40<01:54,  9.96it/s]
 41%|████      | 799/1939 [01:41<01:50, 10.34it/s]
 41%|████▏     | 801/1939 [01:41<02:00,  9.45it/s]
 41%|████▏     | 803/1939 [01:41<01:46, 10.65it/s]
 42%|████▏     | 805/1939 [01:41<01:58,  9.54it/s]
 42%|████▏     | 807/1939 [01:41<01:50, 10.27it/s]
 42%|████▏     | 809/1939 [01:42<02:00,  9.40it/s]
 42%|████▏     | 811/1939 [01:42<01:46, 10.60it/s]
 42%|████▏     | 813/1939 [01:42<02:04,  9.02it/s]
 42%|████▏     | 815/1939 [01:42<01:45, 10.66it/s]
 42%|████▏     | 817/1939 [01:42<01:57,  9.51it/s]
 42%|████▏     | 819/1939 [01:43<02:09,  8.65it/s]
 42%|████▏     | 821/1939 [01:43<02:10,  8.55it/s]
 42%|████▏     | 822/1939 [01:43<02:28,  7.53it/s]
 42%|████▏     | 823/1939 [01:43<02:30,  7.43it/s]
 43%|████▎     | 825/1939 [01:43<02:05,  8.88it/s]
 43%|████▎     | 826/1939 [01:44<03:09,  5.87it/s]
 43%|████▎     | 828/1939 [01:44<03:03,  6.06it/s]
 43%|████▎     | 829/1939 [01:44<03:02,  6.07it/s]
 43%|████▎     | 831/1939 [01:44<02:19,  7.96it/s]
 43%|████▎     | 834/1939 [01:45<02:16,  8.09it/s]
 43%|████▎     | 836/1939 [01:45<01:55,  9.53it/s]
 43%|████▎     | 839/1939 [01:45<01:49, 10.06it/s]
 43%|████▎     | 841/1939 [01:45<01:43, 10.58it/s]
 44%|████▎     | 844/1939 [01:46<02:24,  7.60it/s]
 44%|████▎     | 847/1939 [01:46<01:48, 10.04it/s]
 44%|████▍     | 851/1939 [01:47<02:07,  8.55it/s]
 44%|████▍     | 854/1939 [01:47<02:33,  7.08it/s]
 44%|████▍     | 856/1939 [01:47<02:13,  8.11it/s]
 44%|████▍     | 858/1939 [01:48<02:13,  8.10it/s]
 44%|████▍     | 860/1939 [01:48<02:58,  6.04it/s]
 44%|████▍     | 861/1939 [01:49<03:57,  4.53it/s]
 44%|████▍     | 862/1939 [01:49<04:53,  3.66it/s]
 45%|████▍     | 863/1939 [01:50<05:48,  3.09it/s]
 45%|████▍     | 864/1939 [01:50<05:30,  3.26it/s]
 45%|████▍     | 867/1939 [01:50<03:08,  5.69it/s]
 45%|████▍     | 872/1939 [01:50<01:37, 10.89it/s]
 45%|████▌     | 876/1939 [01:50<01:11, 14.92it/s]
 45%|████▌     | 881/1939 [01:50<00:51, 20.62it/s]
 46%|████▌     | 888/1939 [01:51<00:37, 27.86it/s]
 46%|████▌     | 892/1939 [01:51<00:39, 26.29it/s]
 46%|████▋     | 899/1939 [01:51<00:41, 24.97it/s]
 47%|████▋     | 903/1939 [01:51<00:58, 17.82it/s]
 47%|████▋     | 906/1939 [01:52<00:57, 18.00it/s]
 47%|████▋     | 910/1939 [01:52<00:59, 17.25it/s]
 47%|████▋     | 913/1939 [01:52<01:32, 11.08it/s]
 47%|████▋     | 915/1939 [01:53<02:06,  8.07it/s]
 47%|████▋     | 918/1939 [01:53<02:00,  8.47it/s]
 47%|████▋     | 920/1939 [01:54<02:21,  7.19it/s]
 48%|████▊     | 922/1939 [01:54<02:04,  8.20it/s]
 48%|████▊     | 924/1939 [01:54<02:51,  5.93it/s]
 48%|████▊     | 927/1939 [01:55<02:21,  7.13it/s]
 48%|████▊     | 929/1939 [01:55<01:59,  8.49it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 321.07it/s]
 34%|███▎      | 101/300 [04:12<2:23:35, 43.29s/it]

[[np.int64(0), False, 9], [np.int64(1), False, 11], [np.int64(2), False, 3], [np.int64(3), False, 0], [np.int64(4), False, 7], [np.int64(5), False, 11], [np.int64(6), False, 0], [np.int64(8), False, 13], [np.int64(10), False, 3], [np.int64(12), False, 5], [np.int64(13), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9961, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.8989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0993, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [04:12<1:54:11, 34.60s/it]

tensor(12.9006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2318, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [04:12<1:11:52, 22.00s/it]

tensor(12.9159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4502, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5196, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [04:12<46:51, 14.49s/it]

tensor(12.9579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5865, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [04:13<31:13,  9.76s/it]

tensor(12.9551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6562, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7733, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [04:13<21:07,  6.67s/it]

tensor(12.9213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8257, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8696, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [04:13<14:26,  4.61s/it]

tensor(12.8879, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9044, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [04:13<09:57,  3.21s/it]

tensor(12.8675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9454, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9824, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0145, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [04:13<06:55,  2.26s/it]

tensor(12.8113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0734, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [04:14<04:50,  1.60s/it]

tensor(12.7863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1019, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:14<03:25,  1.14s/it]

tensor(12.7751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1246, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1485, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1752, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:14<02:26,  1.21it/s]

tensor(12.7437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2051, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2316, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [04:14<01:46,  1.65it/s]

tensor(12.7238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2522, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [04:14<01:18,  2.22it/s]

tensor(12.7128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2720, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2786, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2974, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [04:15<00:59,  2.90it/s]

tensor(12.6744, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6611, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3246, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [04:15<00:45,  3.72it/s]

tensor(12.6477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3454, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:15<00:36,  4.62it/s]

tensor(12.6346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3779, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [04:15<00:29,  5.57it/s]

tensor(12.5986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3879, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3961, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:15<00:25,  6.47it/s]

tensor(12.5768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4112, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [04:16<00:22,  7.33it/s]

tensor(12.5664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4244, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4308, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4375, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [04:16<00:19,  8.08it/s]

tensor(12.5365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4458, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4542, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [04:16<00:18,  8.72it/s]

tensor(12.5177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4659, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [04:16<00:16,  9.22it/s]

tensor(12.5090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4731, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4813, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4898, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [04:16<00:16,  9.59it/s]

tensor(12.4847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4968, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5048, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [04:16<00:15,  9.89it/s]

tensor(12.4700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5101, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:17<00:14, 10.10it/s]

tensor(12.4631, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5161, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([156, 203, 170, 318,  31, 139, 215, 109, 167,  59,  21,  79, 146, 126])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:45, 18.40it/s]
  0%|          | 7/1939 [00:00<01:22, 23.35it/s]
  1%|          | 11/1939 [00:00<01:10, 27.47it/s]
  1%|          | 16/1939 [00:00<00:59, 32.16it/s]
  1%|          | 20/1939 [00:00<01:04, 29.79it/s]
  1%|▏         | 26/1939 [00:00<00:53, 35.70it/s]
  2%|▏         | 32/1939 [00:00<00:45, 42.05it/s]
  2%|▏         | 38/1939 [00:01<00:41, 46.33it/s]
  2%|▏         | 43/1939 [00:01<01:01, 30.65it/s]
  2%|▏         | 47/1939 [00:01<00:58, 32.53it/s]
  3%|▎         | 51/1939 [00:01<01:14, 25.37it/s]
  3%|▎         | 55/1939 [00:02<01:48, 17.38it/s]
  3%|▎         | 58/1939 [00:02<01:48, 17.36it/s]
  3%|▎         | 63/1939 [00:02<01:24, 22.16it/s]
  3%|▎         | 66/1939 [00:02<01:22, 22.66it/s]
  4%|▎         | 69/1939 [00:02<01:21, 22.90it/s]
  4%|▍         | 73/1939 [00:02<01:32, 20.12it/s]
  4%|▍         | 77/1939 [00:03<01:21, 22.95it/s]
  4%|▍         | 80/1939 [00:03<02:22, 13.06it/s]
  4%|▍         | 83/1939 [00:03<02:04, 14.90it/s]
  4%|▍         | 86/1939 [00:04<02:52, 10.75it/s]
  5%|▍         | 88/1939 [00:04<03:02, 10.13it/s]
  5%|▍         | 90/1939 [00:04<02:42, 11.41it/s]
  5%|▍         | 94/1939 [00:04<02:23, 12.90it/s]
  5%|▌         | 97/1939 [00:04<02:00, 15.29it/s]
  5%|▌         | 100/1939 [00:05<02:04, 14.72it/s]
  5%|▌         | 102/1939 [00:05<02:03, 14.87it/s]
  6%|▌         | 109/1939 [00:05<01:13, 24.92it/s]
  6%|▌         | 114/1939 [00:05<01:00, 30.20it/s]
  6%|▌         | 118/1939 [00:05<01:16, 23.80it/s]
  6%|▋         | 122/1939 [00:06<01:43, 17.58it/s]
  7%|▋         | 128/1939 [00:06<01:15, 24.06it/s]
  7%|▋         | 132/1939 [00:06<01:12, 24.86it/s]
  7%|▋         | 136/1939 [00:06<01:23, 21.48it/s]
  7%|▋         | 139/1939 [00:06<01:50, 16.30it/s]
  7%|▋         | 145/1939 [00:07<01:41, 17.75it/s]
  8%|▊         | 148/1939 [00:07<01:31, 19.48it/s]
  8%|▊         | 153/1939 [00:07<01:33, 19.18it/s]
  8%|▊         | 156/1939 [00:07<01:30, 19.68it/s]
  8%|▊         | 159/1939 [00:07<01:48, 16.46it/s]
  8%|▊         | 161/1939 [00:08<02:18, 12.88it/s]
  8%|▊         | 164/1939 [00:08<02:24, 12.28it/s]
  9%|▊         | 168/1939 [00:08<01:52, 15.68it/s]
  9%|▉         | 170/1939 [00:08<02:09, 13.68it/s]
  9%|▉         | 172/1939 [00:08<02:00, 14.62it/s]
  9%|▉         | 177/1939 [00:09<01:23, 21.09it/s]
  9%|▉         | 182/1939 [00:09<01:08, 25.47it/s]
 10%|▉         | 186/1939 [00:09<01:01, 28.55it/s]
 10%|▉         | 191/1939 [00:09<00:52, 33.20it/s]
 10%|█         | 196/1939 [00:09<00:47, 36.50it/s]
 10%|█         | 202/1939 [00:09<01:00, 28.67it/s]
 11%|█         | 206/1939 [00:10<02:01, 14.22it/s]
 11%|█         | 209/1939 [00:10<01:53, 15.18it/s]
 11%|█         | 212/1939 [00:10<02:03, 13.97it/s]
 11%|█         | 215/1939 [00:11<01:53, 15.17it/s]
 11%|█▏        | 221/1939 [00:11<01:19, 21.50it/s]
 50%|█████     | 150/300 [04:31<00:14, 10.10it/s]]
 12%|█▏        | 228/1939 [00:11<01:35, 18.01it/s]
 12%|█▏        | 231/1939 [00:11<01:49, 15.58it/s]
 12%|█▏        | 233/1939 [00:12<02:02, 13.92it/s]
 12%|█▏        | 235/1939 [00:12<02:06, 13.47it/s]
 12%|█▏        | 237/1939 [00:12<02:43, 10.41it/s]
 12%|█▏        | 239/1939 [00:12<03:02,  9.31it/s]
 12%|█▏        | 241/1939 [00:13<02:51,  9.92it/s]
 13%|█▎        | 243/1939 [00:13<03:40,  7.71it/s]
 13%|█▎        | 245/1939 [00:13<03:37,  7.79it/s]
 13%|█▎        | 246/1939 [00:13<04:06,  6.85it/s]
 13%|█▎        | 248/1939 [00:14<04:11,  6.73it/s]
 13%|█▎        | 250/1939 [00:14<03:24,  8.24it/s]
 13%|█▎        | 255/1939 [00:14<01:54, 14.68it/s]
 13%|█▎        | 258/1939 [00:14<02:04, 13.48it/s]
 13%|█▎        | 260/1939 [00:14<02:23, 11.73it/s]
 14%|█▎        | 262/1939 [00:15<02:11, 12.79it/s]
 14%|█▎        | 264/1939 [00:15<02:33, 10.89it/s]
 14%|█▍        | 268/1939 [00:15<01:48, 15.43it/s]
 14%|█▍        | 275/1939 [00:15<01:05, 25.42it/s]
 14%|█▍        | 279/1939 [00:15<00:58, 28.15it/s]
 15%|█▍        | 283/1939 [00:15<01:12, 22.85it/s]
 15%|█▍        | 286/1939 [00:16<01:32, 17.94it/s]
 15%|█▍        | 289/1939 [00:16<01:25, 19.27it/s]
 15%|█▌        | 295/1939 [00:16<01:01, 26.85it/s]
 15%|█▌        | 299/1939 [00:16<00:59, 27.44it/s]
 16%|█▌        | 306/1939 [00:16<00:45, 35.51it/s]
 16%|█▌        | 312/1939 [00:16<00:40, 40.62it/s]
 16%|█▋        | 318/1939 [00:16<00:37, 43.77it/s]
 17%|█▋        | 323/1939 [00:17<01:03, 25.39it/s]
 17%|█▋        | 329/1939 [00:17<00:52, 30.42it/s]
 17%|█▋        | 335/1939 [00:17<00:45, 35.27it/s]
 18%|█▊        | 340/1939 [00:17<00:42, 37.37it/s]
 18%|█▊        | 346/1939 [00:17<00:38, 40.91it/s]
 18%|█▊        | 351/1939 [00:18<01:00, 26.18it/s]
 18%|█▊        | 355/1939 [00:18<01:14, 21.34it/s]
 19%|█▊        | 361/1939 [00:18<00:57, 27.28it/s]
 19%|█▉        | 367/1939 [00:18<00:47, 33.04it/s]
 19%|█▉        | 372/1939 [00:18<00:46, 33.91it/s]
 19%|█▉        | 377/1939 [00:19<01:02, 25.10it/s]
 20%|█▉        | 381/1939 [00:19<01:17, 20.22it/s]
 20%|█▉        | 384/1939 [00:19<01:35, 16.28it/s]
 20%|█▉        | 387/1939 [00:20<01:52, 13.76it/s]
 20%|██        | 389/1939 [00:20<02:14, 11.54it/s]
 20%|██        | 391/1939 [00:20<02:24, 10.70it/s]
 20%|██        | 394/1939 [00:20<02:25, 10.64it/s]
 20%|██        | 396/1939 [00:21<02:33, 10.02it/s]
 21%|██        | 398/1939 [00:21<03:24,  7.53it/s]
 21%|██        | 400/1939 [00:21<02:56,  8.73it/s]
 21%|██        | 402/1939 [00:21<02:29, 10.25it/s]
 21%|██        | 404/1939 [00:22<02:27, 10.42it/s]
 21%|██        | 406/1939 [00:22<02:46,  9.23it/s]
 21%|██        | 408/1939 [00:22<02:27, 10.37it/s]
 21%|██        | 410/1939 [00:22<02:12, 11.56it/s]
 21%|██        | 412/1939 [00:22<02:34,  9.91it/s]
 21%|██▏       | 414/1939 [00:22<02:12, 11.55it/s]
 21%|██▏       | 416/1939 [00:23<02:15, 11.26it/s]
 22%|██▏       | 418/1939 [00:23<02:22, 10.68it/s]
 22%|██▏       | 420/1939 [00:23<02:36,  9.72it/s]
 22%|██▏       | 422/1939 [00:23<02:32,  9.95it/s]
 22%|██▏       | 424/1939 [00:23<02:20, 10.78it/s]
 22%|██▏       | 426/1939 [00:24<02:19, 10.87it/s]
 22%|██▏       | 428/1939 [00:24<02:06, 11.93it/s]
 22%|██▏       | 430/1939 [00:24<02:01, 12.39it/s]
 22%|██▏       | 432/1939 [00:24<01:52, 13.41it/s]
 23%|██▎       | 438/1939 [00:24<01:06, 22.51it/s]
 23%|██▎       | 444/1939 [00:24<00:49, 30.22it/s]
 23%|██▎       | 450/1939 [00:24<00:40, 37.19it/s]
 23%|██▎       | 455/1939 [00:25<00:42, 34.65it/s]
 24%|██▎       | 460/1939 [00:25<00:38, 38.24it/s]
 24%|██▍       | 465/1939 [00:25<00:39, 37.53it/s]
 24%|██▍       | 469/1939 [00:25<00:49, 29.70it/s]
 24%|██▍       | 475/1939 [00:25<00:44, 33.21it/s]
 25%|██▍       | 479/1939 [00:25<00:44, 32.69it/s]
 25%|██▍       | 483/1939 [00:25<00:52, 27.50it/s]
 25%|██▌       | 486/1939 [00:26<00:52, 27.80it/s]
 25%|██▌       | 489/1939 [00:26<01:07, 21.45it/s]
 25%|██▌       | 492/1939 [00:26<01:06, 21.69it/s]
 26%|██▌       | 498/1939 [00:26<00:50, 28.75it/s]
 26%|██▌       | 504/1939 [00:26<00:41, 34.67it/s]
 26%|██▌       | 508/1939 [00:26<00:43, 32.60it/s]
 26%|██▋       | 512/1939 [00:27<00:58, 24.30it/s]
 27%|██▋       | 516/1939 [00:27<00:53, 26.64it/s]
 27%|██▋       | 522/1939 [00:27<00:42, 33.27it/s]
 27%|██▋       | 528/1939 [00:27<00:36, 38.96it/s]
 28%|██▊       | 534/1939 [00:27<00:32, 43.45it/s]
 28%|██▊       | 539/1939 [00:27<00:50, 27.69it/s]
 28%|██▊       | 543/1939 [00:27<00:47, 29.41it/s]
 28%|██▊       | 547/1939 [00:28<00:57, 24.21it/s]
 28%|██▊       | 551/1939 [00:28<01:11, 19.46it/s]
 29%|██▊       | 554/1939 [00:28<01:06, 20.70it/s]
 29%|██▉       | 561/1939 [00:28<00:50, 27.18it/s]
 29%|██▉       | 566/1939 [00:28<00:45, 29.99it/s]
 29%|██▉       | 572/1939 [00:29<00:50, 27.06it/s]
 30%|██▉       | 576/1939 [00:29<01:02, 21.66it/s]
 30%|██▉       | 579/1939 [00:29<01:01, 22.08it/s]
 30%|███       | 582/1939 [00:29<01:17, 17.51it/s]
 30%|███       | 585/1939 [00:30<01:28, 15.32it/s]
 30%|███       | 589/1939 [00:30<01:12, 18.65it/s]
 31%|███       | 594/1939 [00:30<00:55, 24.12it/s]
 31%|███       | 599/1939 [00:30<00:52, 25.29it/s]
 31%|███       | 602/1939 [00:30<01:15, 17.78it/s]
 31%|███       | 605/1939 [00:31<01:09, 19.18it/s]
 31%|███▏      | 608/1939 [00:31<01:24, 15.79it/s]
 32%|███▏      | 611/1939 [00:31<01:33, 14.27it/s]
 32%|███▏      | 613/1939 [00:31<01:49, 12.12it/s]
 32%|███▏      | 615/1939 [00:32<02:32,  8.68it/s]
 32%|███▏      | 617/1939 [00:32<02:41,  8.21it/s]
 32%|███▏      | 619/1939 [00:32<02:41,  8.16it/s]
 32%|███▏      | 620/1939 [00:33<02:58,  7.39it/s]
 32%|███▏      | 621/1939 [00:33<03:16,  6.70it/s]
 32%|███▏      | 622/1939 [00:33<03:26,  6.39it/s]
 32%|███▏      | 624/1939 [00:33<02:37,  8.37it/s]
 32%|███▏      | 626/1939 [00:33<02:10, 10.04it/s]
 32%|███▏      | 630/1939 [00:33<01:54, 11.45it/s]
 33%|███▎      | 633/1939 [00:34<01:34, 13.85it/s]
 33%|███▎      | 636/1939 [00:34<01:36, 13.52it/s]
 33%|███▎      | 639/1939 [00:34<01:21, 16.01it/s]
 33%|███▎      | 641/1939 [00:34<01:38, 13.14it/s]
 33%|███▎      | 643/1939 [00:34<01:50, 11.77it/s]
 33%|███▎      | 645/1939 [00:35<01:43, 12.56it/s]
 33%|███▎      | 649/1939 [00:35<01:31, 14.10it/s]
 34%|███▎      | 651/1939 [00:35<01:47, 12.03it/s]
 34%|███▎      | 653/1939 [00:35<01:38, 13.12it/s]
 34%|███▍      | 655/1939 [00:35<01:54, 11.19it/s]
 34%|███▍      | 657/1939 [00:36<02:04, 10.33it/s]
 34%|███▍      | 659/1939 [00:36<02:41,  7.91it/s]
 34%|███▍      | 663/1939 [00:36<01:47, 11.87it/s]
 34%|███▍      | 665/1939 [00:36<01:54, 11.15it/s]
 34%|███▍      | 667/1939 [00:37<02:05, 10.15it/s]
 35%|███▍      | 670/1939 [00:37<01:36, 13.10it/s]
 35%|███▍      | 672/1939 [00:37<01:48, 11.65it/s]
 35%|███▍      | 674/1939 [00:37<01:38, 12.90it/s]
 35%|███▍      | 676/1939 [00:37<01:53, 11.16it/s]
 35%|███▍      | 678/1939 [00:37<01:39, 12.72it/s]
 35%|███▌      | 680/1939 [00:38<01:55, 10.92it/s]
 35%|███▌      | 682/1939 [00:38<01:44, 12.05it/s]
 35%|███▌      | 684/1939 [00:38<02:02, 10.25it/s]
 35%|███▌      | 687/1939 [00:38<02:01, 10.27it/s]
 36%|███▌      | 689/1939 [00:39<02:06,  9.87it/s]
 36%|███▌      | 691/1939 [00:39<01:52, 11.05it/s]
 36%|███▌      | 693/1939 [00:39<02:30,  8.29it/s]
 36%|███▌      | 696/1939 [00:39<01:52, 11.08it/s]
 36%|███▌      | 699/1939 [00:39<01:45, 11.81it/s]
 36%|███▌      | 702/1939 [00:40<01:27, 14.06it/s]
 37%|███▋      | 709/1939 [00:40<00:51, 23.78it/s]
 37%|███▋      | 713/1939 [00:40<00:49, 24.96it/s]
 37%|███▋      | 717/1939 [00:40<00:43, 28.01it/s]
 37%|███▋      | 723/1939 [00:40<00:46, 25.88it/s]
 37%|███▋      | 726/1939 [00:40<00:48, 25.16it/s]
 38%|███▊      | 730/1939 [00:41<00:53, 22.49it/s]
 38%|███▊      | 733/1939 [00:41<01:20, 14.99it/s]
 38%|███▊      | 736/1939 [00:41<01:13, 16.44it/s]
 38%|███▊      | 739/1939 [00:41<01:24, 14.23it/s]
 38%|███▊      | 741/1939 [00:41<01:19, 14.98it/s]
 38%|███▊      | 746/1939 [00:42<00:58, 20.55it/s]
 39%|███▊      | 751/1939 [00:42<00:46, 25.68it/s]
 39%|███▉      | 755/1939 [00:42<00:53, 22.19it/s]
 39%|███▉      | 758/1939 [00:42<01:10, 16.66it/s]
 39%|███▉      | 761/1939 [00:43<01:23, 14.19it/s]
 39%|███▉      | 763/1939 [00:43<01:36, 12.13it/s]
 40%|███▉      | 766/1939 [00:43<01:44, 11.24it/s]
 40%|███▉      | 768/1939 [00:43<01:46, 10.95it/s]
 40%|███▉      | 770/1939 [00:44<02:25,  8.01it/s]
 40%|███▉      | 772/1939 [00:44<02:22,  8.18it/s]
 40%|███▉      | 775/1939 [00:44<01:48, 10.68it/s]
 40%|████      | 777/1939 [00:45<02:18,  8.38it/s]
 40%|████      | 779/1939 [00:45<02:22,  8.14it/s]
 40%|████      | 781/1939 [00:45<02:04,  9.34it/s]
 40%|████      | 784/1939 [00:45<01:52, 10.29it/s]
 41%|████      | 786/1939 [00:45<01:38, 11.66it/s]
 41%|████      | 788/1939 [00:46<01:51, 10.36it/s]
 41%|████      | 790/1939 [00:46<02:06,  9.12it/s]
 41%|████      | 794/1939 [00:46<01:23, 13.75it/s]
 41%|████      | 799/1939 [00:46<00:56, 20.12it/s]
 41%|████▏     | 804/1939 [00:46<00:57, 19.68it/s]
 42%|████▏     | 807/1939 [00:47<01:14, 15.28it/s]
 42%|████▏     | 810/1939 [00:47<01:27, 12.92it/s]
 42%|████▏     | 812/1939 [00:47<01:38, 11.47it/s]
 42%|████▏     | 814/1939 [00:47<01:42, 11.01it/s]
 42%|████▏     | 816/1939 [00:48<01:34, 11.94it/s]
 42%|████▏     | 818/1939 [00:48<01:34, 11.87it/s]
 42%|████▏     | 820/1939 [00:48<01:40, 11.13it/s]
 42%|████▏     | 822/1939 [00:48<02:00,  9.27it/s]
 42%|████▏     | 824/1939 [00:48<02:07,  8.73it/s]
 43%|████▎     | 826/1939 [00:49<01:52,  9.90it/s]
 43%|████▎     | 828/1939 [00:49<01:38, 11.26it/s]
 43%|████▎     | 832/1939 [00:49<01:06, 16.58it/s]
 43%|████▎     | 836/1939 [00:49<00:51, 21.31it/s]
 43%|████▎     | 840/1939 [00:49<00:44, 24.54it/s]
 43%|████▎     | 843/1939 [00:49<00:47, 23.17it/s]
 44%|████▎     | 846/1939 [00:49<00:44, 24.38it/s]
 44%|████▍     | 852/1939 [00:49<00:33, 32.54it/s]
 44%|████▍     | 857/1939 [00:50<00:45, 24.01it/s]
 44%|████▍     | 860/1939 [00:50<00:47, 22.60it/s]
 45%|████▍     | 863/1939 [00:50<00:45, 23.52it/s]
 45%|████▍     | 868/1939 [00:50<00:37, 28.38it/s]
 45%|████▌     | 873/1939 [00:50<00:33, 32.25it/s]
 45%|████▌     | 878/1939 [00:50<00:29, 35.67it/s]
 45%|████▌     | 882/1939 [00:50<00:31, 33.17it/s]
 46%|████▌     | 886/1939 [00:51<00:31, 33.37it/s]
 46%|████▌     | 891/1939 [00:51<00:28, 36.90it/s]
 46%|████▋     | 897/1939 [00:51<00:25, 41.31it/s]
 47%|████▋     | 902/1939 [00:51<00:50, 20.70it/s]
 47%|████▋     | 906/1939 [00:52<00:47, 21.55it/s]
 47%|████▋     | 910/1939 [00:52<00:54, 18.74it/s]
 47%|████▋     | 913/1939 [00:52<00:53, 19.29it/s]
 47%|████▋     | 918/1939 [00:52<00:53, 19.03it/s]
 47%|████▋     | 921/1939 [00:52<00:50, 20.05it/s]
 48%|████▊     | 927/1939 [00:53<00:50, 19.89it/s]
 48%|████▊     | 930/1939 [00:53<00:59, 16.84it/s]
 48%|████▊     | 932/1939 [00:53<01:13, 13.61it/s]
 48%|████▊     | 937/1939 [00:53<00:53, 18.70it/s]
 48%|████▊     | 940/1939 [00:54<01:04, 15.52it/s]
 49%|████▉     | 947/1939 [00:54<00:41, 23.74it/s]
 49%|████▉     | 953/1939 [00:54<00:32, 30.04it/s]
 49%|████▉     | 959/1939 [00:54<00:30, 32.25it/s]
 50%|████▉     | 964/1939 [00:54<00:30, 32.05it/s]
 50%|████▉     | 968/1939 [00:54<00:38, 24.93it/s]
 50%|█████     | 972/1939 [00:55<01:10, 13.77it/s]
 50%|█████     | 975/1939 [00:55<01:06, 14.50it/s]
 50%|█████     | 978/1939 [00:56<01:12, 13.21it/s]
 51%|█████     | 980/1939 [00:56<01:10, 13.53it/s]
 51%|█████     | 982/1939 [00:56<01:11, 13.44it/s]
 51%|█████     | 984/1939 [00:56<01:09, 13.77it/s]
 51%|█████     | 987/1939 [00:56<00:58, 16.30it/s]
 51%|█████     | 991/1939 [00:56<00:57, 16.54it/s]
 51%|█████▏    | 994/1939 [00:56<00:51, 18.51it/s]
 51%|█████▏    | 997/1939 [00:57<00:57, 16.45it/s]
 52%|█████▏    | 999/1939 [00:57<01:13, 12.85it/s]
 52%|█████▏    | 1001/1939 [00:57<01:09, 13.57it/s]
 52%|█████▏    | 1003/1939 [00:57<01:19, 11.81it/s]
 52%|█████▏    | 1005/1939 [00:58<01:37,  9.61it/s]
 52%|█████▏    | 1007/1939 [00:58<01:36,  9.70it/s]
 52%|█████▏    | 1009/1939 [00:58<01:35,  9.70it/s]
 52%|█████▏    | 1011/1939 [00:58<02:01,  7.61it/s]
 52%|█████▏    | 1012/1939 [00:59<01:58,  7.81it/s]
 52%|█████▏    | 1014/1939 [00:59<01:44,  8.84it/s]
 52%|█████▏    | 1015/1939 [00:59<01:44,  8.86it/s]
 52%|█████▏    | 1016/1939 [00:59<01:44,  8.80it/s]
 53%|█████▎    | 1018/1939 [00:59<01:27, 10.56it/s]
 53%|█████▎    | 1020/1939 [00:59<01:28, 10.37it/s]
 53%|█████▎    | 1022/1939 [00:59<01:20, 11.41it/s]
 53%|█████▎    | 1024/1939 [00:59<01:09, 13.22it/s]
 53%|█████▎    | 1026/1939 [01:00<01:04, 14.14it/s]
 53%|█████▎    | 1028/1939 [01:00<01:02, 14.49it/s]
 53%|█████▎    | 1030/1939 [01:00<01:00, 14.95it/s]
 53%|█████▎    | 1033/1939 [01:00<00:50, 18.08it/s]
 53%|█████▎    | 1037/1939 [01:00<00:38, 23.61it/s]
 54%|█████▍    | 1043/1939 [01:00<00:27, 32.36it/s]
 54%|█████▍    | 1047/1939 [01:00<00:39, 22.46it/s]
 54%|█████▍    | 1050/1939 [01:01<00:52, 16.99it/s]
 54%|█████▍    | 1053/1939 [01:01<01:09, 12.83it/s]
 54%|█████▍    | 1055/1939 [01:01<01:17, 11.37it/s]
 55%|█████▍    | 1057/1939 [01:02<01:21, 10.77it/s]
 55%|█████▍    | 1059/1939 [01:02<01:26, 10.23it/s]
 55%|█████▍    | 1062/1939 [01:02<01:08, 12.73it/s]
 55%|█████▌    | 1068/1939 [01:02<00:55, 15.74it/s]
 55%|█████▌    | 1071/1939 [01:02<00:48, 17.75it/s]
 56%|█████▌    | 1077/1939 [01:02<00:34, 25.17it/s]
 56%|█████▌    | 1081/1939 [01:03<00:41, 20.57it/s]
 56%|█████▌    | 1085/1939 [01:03<00:36, 23.63it/s]
 56%|█████▌    | 1088/1939 [01:03<00:43, 19.68it/s]
 56%|█████▋    | 1091/1939 [01:03<00:41, 20.62it/s]
 56%|█████▋    | 1094/1939 [01:04<01:08, 12.26it/s]
 57%|█████▋    | 1096/1939 [01:04<01:05, 12.79it/s]
 57%|█████▋    | 1102/1939 [01:04<00:53, 15.68it/s]
 57%|█████▋    | 1104/1939 [01:04<01:03, 13.08it/s]
 57%|█████▋    | 1106/1939 [01:05<01:01, 13.56it/s]
 57%|█████▋    | 1112/1939 [01:05<00:39, 21.02it/s]
 58%|█████▊    | 1116/1939 [01:05<00:42, 19.20it/s]
 58%|█████▊    | 1119/1939 [01:05<00:42, 19.42it/s]
 58%|█████▊    | 1125/1939 [01:05<00:30, 26.31it/s]
 58%|█████▊    | 1129/1939 [01:05<00:35, 22.61it/s]
 58%|█████▊    | 1132/1939 [01:06<00:39, 20.20it/s]
 59%|█████▊    | 1135/1939 [01:06<00:38, 20.88it/s]
 59%|█████▊    | 1138/1939 [01:06<00:54, 14.82it/s]
 59%|█████▉    | 1142/1939 [01:06<00:56, 14.20it/s]
 59%|█████▉    | 1144/1939 [01:07<01:08, 11.53it/s]
 59%|█████▉    | 1146/1939 [01:07<01:04, 12.38it/s]
 59%|█████▉    | 1148/1939 [01:07<01:10, 11.16it/s]
 59%|█████▉    | 1150/1939 [01:07<01:18, 10.04it/s]
 59%|█████▉    | 1152/1939 [01:08<01:23,  9.46it/s]
 60%|█████▉    | 1154/1939 [01:08<01:34,  8.29it/s]
 60%|█████▉    | 1157/1939 [01:08<01:11, 10.96it/s]
 60%|█████▉    | 1159/1939 [01:08<01:20,  9.68it/s]
 60%|█████▉    | 1161/1939 [01:08<01:10, 10.99it/s]
 60%|█████▉    | 1163/1939 [01:09<01:25,  9.11it/s]
 60%|██████    | 1166/1939 [01:09<01:04, 12.03it/s]
 60%|██████    | 1172/1939 [01:09<00:47, 16.01it/s]
 61%|██████    | 1175/1939 [01:09<00:43, 17.42it/s]
 61%|██████    | 1178/1939 [01:09<00:48, 15.63it/s]
 61%|██████    | 1180/1939 [01:10<01:01, 12.31it/s]
 61%|██████    | 1182/1939 [01:10<00:56, 13.40it/s]
 61%|██████    | 1184/1939 [01:10<01:10, 10.64it/s]
 61%|██████    | 1186/1939 [01:10<01:15,  9.99it/s]
 61%|██████▏   | 1188/1939 [01:11<01:07, 11.08it/s]
 61%|██████▏   | 1190/1939 [01:11<01:13, 10.21it/s]
 61%|██████▏   | 1192/1939 [01:11<01:24,  8.84it/s]
 62%|██████▏   | 1194/1939 [01:11<01:30,  8.22it/s]
 62%|██████▏   | 1196/1939 [01:12<01:29,  8.30it/s]
 62%|██████▏   | 1197/1939 [01:12<01:40,  7.35it/s]
 62%|██████▏   | 1199/1939 [01:12<01:21,  9.08it/s]
 62%|██████▏   | 1204/1939 [01:12<00:45, 16.23it/s]
 62%|██████▏   | 1210/1939 [01:12<00:30, 23.86it/s]
 63%|██████▎   | 1214/1939 [01:12<00:27, 26.70it/s]
 63%|██████▎   | 1218/1939 [01:13<00:35, 20.40it/s]
 63%|██████▎   | 1221/1939 [01:13<00:42, 16.89it/s]
 63%|██████▎   | 1224/1939 [01:13<00:41, 17.25it/s]
 63%|██████▎   | 1227/1939 [01:13<00:52, 13.63it/s]
 63%|██████▎   | 1230/1939 [01:13<00:47, 15.02it/s]
 64%|██████▎   | 1232/1939 [01:14<00:56, 12.61it/s]
 64%|██████▎   | 1234/1939 [01:14<00:52, 13.51it/s]
 64%|██████▍   | 1237/1939 [01:14<00:43, 16.29it/s]
 64%|██████▍   | 1239/1939 [01:14<00:46, 15.09it/s]
 64%|██████▍   | 1242/1939 [01:14<00:52, 13.30it/s]
 64%|██████▍   | 1244/1939 [01:15<00:48, 14.20it/s]
 64%|██████▍   | 1246/1939 [01:15<00:57, 12.09it/s]
 64%|██████▍   | 1249/1939 [01:15<00:47, 14.63it/s]
 65%|██████▍   | 1251/1939 [01:15<00:55, 12.49it/s]
 65%|██████▍   | 1254/1939 [01:15<00:57, 11.88it/s]
 65%|██████▍   | 1256/1939 [01:15<00:51, 13.19it/s]
 65%|██████▍   | 1258/1939 [01:16<00:59, 11.46it/s]
 65%|██████▌   | 1261/1939 [01:16<00:47, 14.21it/s]
 65%|██████▌   | 1266/1939 [01:16<00:31, 21.16it/s]
 66%|██████▌   | 1272/1939 [01:16<00:31, 21.33it/s]
 66%|██████▌   | 1275/1939 [01:16<00:30, 21.62it/s]
 66%|██████▌   | 1281/1939 [01:16<00:22, 28.76it/s]
 66%|██████▋   | 1285/1939 [01:17<00:23, 28.15it/s]
 66%|██████▋   | 1289/1939 [01:17<00:32, 20.14it/s]
 67%|██████▋   | 1293/1939 [01:17<00:35, 17.98it/s]
 67%|██████▋   | 1296/1939 [01:17<00:34, 18.86it/s]
 67%|██████▋   | 1301/1939 [01:18<00:27, 23.51it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 292.63it/s]
 50%|█████     | 151/300 [06:13<51:04, 20.56s/it]

[[np.int64(0), False, 8], [np.int64(1), False, 3], [np.int64(2), False, 3], [np.int64(3), False, 6], [np.int64(4), False, 8], [np.int64(5), False, 13], [np.int64(7), False, 12], [np.int64(8), False, 9], [np.int64(10), False, 0], [np.int64(11), False, 9], [np.int64(12), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6188, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.4514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8560, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [06:13<40:34, 16.45s/it]

tensor(12.4526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1021, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [06:13<31:21, 12.80s/it]

tensor(12.4600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1982, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [06:13<18:58,  7.85s/it]

tensor(12.4645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1594, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1440, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [06:13<12:06,  5.08s/it]

tensor(12.4472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1839, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2262, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [06:14<07:58,  3.39s/it]

tensor(12.4359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2423, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [06:14<05:22,  2.32s/it]

tensor(12.4295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4214, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2694, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [06:14<03:40,  1.61s/it]

tensor(12.4070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3232, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3647, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [06:14<02:33,  1.14s/it]

tensor(12.4021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3790, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [06:14<01:48,  1.22it/s]

tensor(12.3988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4116, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4264, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [06:14<01:18,  1.68it/s]

tensor(12.3763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4355, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4425, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [06:15<00:57,  2.25it/s]

tensor(12.3638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4523, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [06:15<00:42,  2.95it/s]

tensor(12.3586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4615, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3496, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4717, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [06:15<00:33,  3.78it/s]

tensor(12.3450, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4880, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5000, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [06:15<00:26,  4.68it/s]

tensor(12.3354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5069, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [06:15<00:21,  5.63it/s]

tensor(12.3315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5154, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3278, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5252, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [06:16<00:18,  6.53it/s]

tensor(12.3195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5374, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5326, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [06:16<00:15,  7.38it/s]

tensor(12.3117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5333, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [06:16<00:14,  8.10it/s]

tensor(12.3084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5349, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5404, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5431, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [06:16<00:13,  8.68it/s]

tensor(12.2988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5517, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [06:16<00:12,  9.14it/s]

tensor(12.2926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5551, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [06:17<00:11,  9.50it/s]

tensor(12.2902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5597, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5665, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5616, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [06:17<00:11,  9.72it/s]

tensor(12.2815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5617, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5636, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [06:17<00:10,  9.93it/s]

tensor(12.2759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5652, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [06:17<00:10, 10.09it/s]

tensor(12.2734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5626, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5610, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5681, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [06:17<00:09, 10.22it/s]

tensor(12.2653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5702, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([146, 264, 164, 143, 124,  82, 208,  21,  87, 132, 316,  93, 131,  28])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<02:20, 13.75it/s]
  0%|          | 7/1939 [00:00<01:05, 29.69it/s]
  1%|          | 13/1939 [00:00<00:47, 40.47it/s]
  1%|          | 18/1939 [00:00<00:48, 39.45it/s]
  1%|          | 23/1939 [00:00<00:56, 33.76it/s]
  1%|▏         | 28/1939 [00:00<00:50, 37.52it/s]
  2%|▏         | 32/1939 [00:00<00:56, 33.50it/s]
  2%|▏         | 36/1939 [00:01<01:10, 27.03it/s]
  2%|▏         | 41/1939 [00:01<01:26, 22.02it/s]
  2%|▏         | 44/1939 [00:01<01:52, 16.82it/s]
  3%|▎         | 49/1939 [00:02<01:43, 18.29it/s]
  3%|▎         | 52/1939 [00:02<01:46, 17.80it/s]
  3%|▎         | 54/1939 [00:02<02:07, 14.82it/s]
  3%|▎         | 56/1939 [00:02<02:19, 13.46it/s]
  3%|▎         | 59/1939 [00:02<02:28, 12.66it/s]
  3%|▎         | 63/1939 [00:03<01:56, 16.15it/s]
  3%|▎         | 65/1939 [00:03<01:54, 16.34it/s]
  3%|▎         | 67/1939 [00:03<02:08, 14.54it/s]
  4%|▎         | 69/1939 [00:03<02:08, 14.60it/s]
  4%|▎         | 71/1939 [00:03<02:16, 13.65it/s]
  4%|▍         | 73/1939 [00:03<02:28, 12.59it/s]
  4%|▍         | 75/1939 [00:03<02:24, 12.88it/s]
  4%|▍         | 78/1939 [00:04<02:53, 10.71it/s]
  4%|▍         | 80/1939 [00:04<03:57,  7.82it/s]
  4%|▍         | 81/1939 [00:05<04:22,  7.07it/s]
  4%|▍         | 82/1939 [00:05<04:50,  6.39it/s]
  4%|▍         | 83/1939 [00:05<05:02,  6.14it/s]
  4%|▍         | 84/1939 [00:05<05:40,  5.44it/s]
  4%|▍         | 86/1939 [00:06<05:27,  5.65it/s]
  4%|▍         | 87/1939 [00:06<06:15,  4.94it/s]
  5%|▍         | 89/1939 [00:06<04:31,  6.81it/s]
  5%|▍         | 92/1939 [00:06<02:58, 10.35it/s]
  5%|▍         | 94/1939 [00:06<03:03, 10.04it/s]
  5%|▍         | 96/1939 [00:07<03:28,  8.84it/s]
  5%|▌         | 99/1939 [00:07<02:35, 11.86it/s]
  5%|▌         | 101/1939 [00:07<04:08,  7.40it/s]
  5%|▌         | 103/1939 [00:07<03:29,  8.78it/s]
  5%|▌         | 105/1939 [00:08<03:53,  7.85it/s]
  6%|▌         | 107/1939 [00:08<04:02,  7.56it/s]
  6%|▌         | 109/1939 [00:08<03:18,  9.20it/s]
  6%|▌         | 111/1939 [00:08<02:52, 10.57it/s]
  6%|▌         | 113/1939 [00:08<02:30, 12.13it/s]
  6%|▌         | 115/1939 [00:08<02:44, 11.08it/s]
  6%|▌         | 117/1939 [00:09<02:58, 10.23it/s]
  6%|▌         | 119/1939 [00:09<03:12,  9.46it/s]
  6%|▌         | 121/1939 [00:09<03:52,  7.82it/s]
  6%|▋         | 124/1939 [00:09<02:49, 10.73it/s]
  7%|▋         | 128/1939 [00:10<02:29, 12.11it/s]
 66%|██████▋   | 199/300 [06:31<00:09, 10.22it/s]]
  7%|▋         | 132/1939 [00:10<02:41, 11.17it/s]
  7%|▋         | 134/1939 [00:10<02:24, 12.48it/s]
  7%|▋         | 136/1939 [00:10<02:51, 10.51it/s]
  7%|▋         | 138/1939 [00:11<04:05,  7.35it/s]
  7%|▋         | 139/1939 [00:11<04:29,  6.68it/s]
  7%|▋         | 141/1939 [00:11<04:15,  7.02it/s]
  7%|▋         | 142/1939 [00:12<04:48,  6.24it/s]
  7%|▋         | 144/1939 [00:12<03:39,  8.18it/s]
  8%|▊         | 146/1939 [00:12<04:08,  7.22it/s]
  8%|▊         | 149/1939 [00:12<03:25,  8.71it/s]
  8%|▊         | 151/1939 [00:13<03:35,  8.29it/s]
  8%|▊         | 153/1939 [00:13<03:50,  7.75it/s]
  8%|▊         | 155/1939 [00:13<03:16,  9.06it/s]
  8%|▊         | 157/1939 [00:13<03:39,  8.13it/s]
  8%|▊         | 158/1939 [00:14<04:20,  6.83it/s]
  8%|▊         | 159/1939 [00:14<04:37,  6.41it/s]
  8%|▊         | 160/1939 [00:14<05:17,  5.60it/s]
  8%|▊         | 161/1939 [00:14<05:47,  5.12it/s]
  8%|▊         | 162/1939 [00:15<05:46,  5.13it/s]
  8%|▊         | 163/1939 [00:15<06:04,  4.87it/s]
  8%|▊         | 164/1939 [00:15<06:48,  4.35it/s]
  9%|▊         | 167/1939 [00:15<03:51,  7.66it/s]
  9%|▉         | 173/1939 [00:15<01:49, 16.14it/s]
  9%|▉         | 178/1939 [00:15<01:18, 22.30it/s]
  9%|▉         | 182/1939 [00:16<01:21, 21.58it/s]
 10%|▉         | 185/1939 [00:16<01:44, 16.73it/s]
 10%|▉         | 188/1939 [00:16<01:33, 18.72it/s]
 10%|█         | 194/1939 [00:16<01:07, 25.78it/s]
 10%|█         | 199/1939 [00:16<01:15, 23.08it/s]
 10%|█         | 202/1939 [00:17<01:47, 16.18it/s]
 11%|█         | 205/1939 [00:17<02:49, 10.23it/s]
 11%|█         | 207/1939 [00:18<03:05,  9.35it/s]
 11%|█         | 210/1939 [00:18<02:29, 11.56it/s]
 11%|█         | 212/1939 [00:18<02:40, 10.78it/s]
 11%|█         | 214/1939 [00:18<02:47, 10.32it/s]
 11%|█         | 218/1939 [00:18<02:24, 11.93it/s]
 11%|█▏        | 220/1939 [00:19<02:16, 12.57it/s]
 11%|█▏        | 222/1939 [00:19<02:31, 11.31it/s]
 12%|█▏        | 224/1939 [00:19<02:50, 10.05it/s]
 12%|█▏        | 226/1939 [00:19<02:34, 11.10it/s]
 12%|█▏        | 228/1939 [00:20<02:55,  9.74it/s]
 12%|█▏        | 230/1939 [00:20<03:33,  8.01it/s]
 12%|█▏        | 233/1939 [00:20<03:24,  8.33it/s]
 12%|█▏        | 235/1939 [00:20<02:55,  9.69it/s]
 12%|█▏        | 237/1939 [00:21<03:25,  8.29it/s]
 12%|█▏        | 239/1939 [00:21<04:02,  7.01it/s]
 12%|█▏        | 240/1939 [00:21<04:28,  6.33it/s]
 12%|█▏        | 241/1939 [00:22<04:53,  5.79it/s]
 12%|█▏        | 242/1939 [00:22<05:23,  5.25it/s]
 13%|█▎        | 243/1939 [00:22<06:08,  4.60it/s]
 13%|█▎        | 244/1939 [00:22<05:31,  5.11it/s]
 13%|█▎        | 245/1939 [00:22<05:32,  5.09it/s]
 13%|█▎        | 247/1939 [00:23<04:01,  6.99it/s]
 13%|█▎        | 248/1939 [00:23<04:07,  6.83it/s]
 13%|█▎        | 250/1939 [00:23<03:23,  8.29it/s]
 13%|█▎        | 251/1939 [00:23<04:02,  6.97it/s]
 13%|█▎        | 254/1939 [00:23<02:40, 10.51it/s]
 13%|█▎        | 257/1939 [00:23<02:03, 13.61it/s]
 13%|█▎        | 259/1939 [00:24<02:44, 10.21it/s]
 13%|█▎        | 261/1939 [00:24<03:08,  8.91it/s]
 14%|█▎        | 263/1939 [00:24<03:32,  7.89it/s]
 14%|█▎        | 264/1939 [00:25<04:01,  6.93it/s]
 14%|█▍        | 267/1939 [00:25<02:48,  9.92it/s]
 14%|█▍        | 269/1939 [00:25<02:59,  9.31it/s]
 14%|█▍        | 271/1939 [00:25<03:05,  8.98it/s]
 14%|█▍        | 273/1939 [00:25<03:13,  8.60it/s]
 14%|█▍        | 274/1939 [00:26<03:42,  7.49it/s]
 14%|█▍        | 276/1939 [00:26<02:56,  9.41it/s]
 14%|█▍        | 279/1939 [00:26<02:50,  9.71it/s]
 14%|█▍        | 281/1939 [00:26<03:10,  8.68it/s]
 15%|█▍        | 283/1939 [00:26<02:44, 10.08it/s]
 15%|█▍        | 285/1939 [00:27<03:58,  6.95it/s]
 15%|█▍        | 287/1939 [00:27<03:54,  7.05it/s]
 15%|█▍        | 288/1939 [00:27<04:23,  6.26it/s]
 15%|█▍        | 290/1939 [00:28<03:25,  8.02it/s]
 15%|█▌        | 293/1939 [00:28<02:57,  9.27it/s]
 15%|█▌        | 295/1939 [00:28<02:32, 10.75it/s]
 15%|█▌        | 297/1939 [00:28<02:46,  9.86it/s]
 15%|█▌        | 299/1939 [00:28<03:00,  9.10it/s]
 16%|█▌        | 303/1939 [00:29<02:30, 10.87it/s]
 16%|█▌        | 305/1939 [00:29<02:18, 11.80it/s]
 16%|█▌        | 307/1939 [00:29<02:28, 10.97it/s]
 16%|█▌        | 309/1939 [00:29<02:14, 12.10it/s]
 16%|█▌        | 312/1939 [00:29<02:07, 12.72it/s]
 16%|█▌        | 315/1939 [00:30<02:26, 11.05it/s]
 16%|█▋        | 317/1939 [00:30<03:15,  8.31it/s]
 16%|█▋        | 318/1939 [00:30<03:35,  7.54it/s]
 16%|█▋        | 319/1939 [00:31<04:07,  6.55it/s]
 17%|█▋        | 320/1939 [00:31<04:35,  5.87it/s]
 17%|█▋        | 321/1939 [00:31<05:08,  5.25it/s]
 17%|█▋        | 322/1939 [00:31<05:34,  4.84it/s]
 17%|█▋        | 325/1939 [00:31<03:19,  8.10it/s]
 17%|█▋        | 331/1939 [00:32<01:37, 16.56it/s]
 17%|█▋        | 334/1939 [00:32<01:55, 13.90it/s]
 17%|█▋        | 339/1939 [00:32<01:43, 15.42it/s]
 18%|█▊        | 341/1939 [00:32<01:40, 15.92it/s]
 18%|█▊        | 348/1939 [00:32<01:03, 25.18it/s]
 18%|█▊        | 352/1939 [00:33<01:44, 15.21it/s]
 18%|█▊        | 355/1939 [00:33<02:25, 10.86it/s]
 18%|█▊        | 358/1939 [00:34<02:06, 12.51it/s]
 19%|█▊        | 361/1939 [00:34<02:07, 12.33it/s]
 19%|█▊        | 363/1939 [00:34<02:32, 10.33it/s]
 19%|█▉        | 366/1939 [00:34<02:31, 10.37it/s]
 19%|█▉        | 368/1939 [00:35<02:20, 11.16it/s]
 19%|█▉        | 370/1939 [00:35<02:26, 10.73it/s]
 19%|█▉        | 372/1939 [00:35<02:51,  9.12it/s]
 19%|█▉        | 375/1939 [00:35<02:13, 11.74it/s]
 19%|█▉        | 377/1939 [00:35<02:34, 10.12it/s]
 20%|█▉        | 379/1939 [00:36<02:45,  9.43it/s]
 20%|█▉        | 381/1939 [00:36<03:07,  8.31it/s]
 20%|█▉        | 382/1939 [00:36<03:28,  7.47it/s]
 20%|█▉        | 384/1939 [00:37<03:39,  7.08it/s]
 20%|█▉        | 387/1939 [00:37<03:23,  7.62it/s]
 20%|██        | 388/1939 [00:37<03:57,  6.54it/s]
 20%|██        | 389/1939 [00:37<04:16,  6.05it/s]
 20%|██        | 390/1939 [00:38<04:45,  5.43it/s]
 20%|██        | 391/1939 [00:38<05:09,  5.01it/s]
 20%|██        | 393/1939 [00:38<04:25,  5.83it/s]
 20%|██        | 394/1939 [00:38<04:05,  6.30it/s]
 20%|██        | 396/1939 [00:38<03:19,  7.72it/s]
 20%|██        | 397/1939 [00:39<03:19,  7.74it/s]
 21%|██        | 398/1939 [00:39<04:09,  6.18it/s]
 21%|██        | 400/1939 [00:39<03:07,  8.19it/s]
 21%|██        | 402/1939 [00:39<02:31, 10.13it/s]
 21%|██        | 404/1939 [00:39<02:58,  8.61it/s]
 21%|██        | 406/1939 [00:40<03:44,  6.82it/s]
 21%|██        | 407/1939 [00:40<04:41,  5.45it/s]
 21%|██        | 409/1939 [00:40<03:32,  7.21it/s]
 21%|██        | 411/1939 [00:40<03:25,  7.45it/s]
 21%|██        | 412/1939 [00:41<03:50,  6.62it/s]
 21%|██▏       | 414/1939 [00:41<03:02,  8.35it/s]
 21%|██▏       | 416/1939 [00:41<04:00,  6.33it/s]
 22%|██▏       | 417/1939 [00:42<04:29,  5.64it/s]
 22%|██▏       | 419/1939 [00:42<04:18,  5.88it/s]
 22%|██▏       | 422/1939 [00:42<03:44,  6.77it/s]
 22%|██▏       | 424/1939 [00:42<03:07,  8.09it/s]
 22%|██▏       | 426/1939 [00:43<03:12,  7.84it/s]
 22%|██▏       | 428/1939 [00:43<03:00,  8.35it/s]
 22%|██▏       | 431/1939 [00:43<02:10, 11.55it/s]
 23%|██▎       | 438/1939 [00:43<01:10, 21.34it/s]
 23%|██▎       | 441/1939 [00:43<01:05, 23.00it/s]
 23%|██▎       | 447/1939 [00:43<00:49, 30.27it/s]
 23%|██▎       | 453/1939 [00:43<00:41, 35.80it/s]
 24%|██▎       | 459/1939 [00:44<00:37, 39.75it/s]
 24%|██▍       | 464/1939 [00:44<00:39, 37.23it/s]
 24%|██▍       | 470/1939 [00:44<00:35, 41.56it/s]
 25%|██▍       | 476/1939 [00:44<00:33, 44.26it/s]
 25%|██▍       | 481/1939 [00:44<00:54, 26.94it/s]
 25%|██▌       | 486/1939 [00:44<00:47, 30.75it/s]
 25%|██▌       | 490/1939 [00:45<01:19, 18.20it/s]
 25%|██▌       | 494/1939 [00:45<01:34, 15.34it/s]
 26%|██▌       | 497/1939 [00:46<02:03, 11.64it/s]
 26%|██▌       | 500/1939 [00:46<02:05, 11.49it/s]
 26%|██▌       | 503/1939 [00:46<01:49, 13.17it/s]
 26%|██▌       | 505/1939 [00:46<01:56, 12.30it/s]
 26%|██▌       | 507/1939 [00:46<01:46, 13.39it/s]
 26%|██▋       | 511/1939 [00:47<01:49, 12.99it/s]
 27%|██▋       | 514/1939 [00:47<01:34, 15.08it/s]
 27%|██▋       | 520/1939 [00:47<01:03, 22.33it/s]
 27%|██▋       | 526/1939 [00:47<00:49, 28.83it/s]
 27%|██▋       | 532/1939 [00:47<00:41, 34.23it/s]
 28%|██▊       | 537/1939 [00:48<00:56, 24.68it/s]
 28%|██▊       | 541/1939 [00:48<01:27, 15.98it/s]
 28%|██▊       | 546/1939 [00:48<01:29, 15.53it/s]
 28%|██▊       | 549/1939 [00:49<01:43, 13.48it/s]
 28%|██▊       | 551/1939 [00:49<02:04, 11.13it/s]
 29%|██▊       | 553/1939 [00:49<02:14, 10.31it/s]
 29%|██▊       | 556/1939 [00:50<02:09, 10.68it/s]
 29%|██▉       | 558/1939 [00:50<02:16, 10.13it/s]
 29%|██▉       | 561/1939 [00:50<02:14, 10.28it/s]
 29%|██▉       | 563/1939 [00:50<02:11, 10.48it/s]
 29%|██▉       | 566/1939 [00:50<01:48, 12.67it/s]
 29%|██▉       | 568/1939 [00:51<02:16, 10.05it/s]
 29%|██▉       | 571/1939 [00:51<02:00, 11.40it/s]
 30%|██▉       | 573/1939 [00:51<02:06, 10.77it/s]
 30%|██▉       | 575/1939 [00:51<02:16,  9.96it/s]
 30%|██▉       | 577/1939 [00:52<02:07, 10.69it/s]
 30%|██▉       | 579/1939 [00:52<02:18,  9.85it/s]
 30%|██▉       | 581/1939 [00:52<02:02, 11.05it/s]
 30%|███       | 583/1939 [00:52<02:34,  8.78it/s]
 30%|███       | 585/1939 [00:53<03:11,  7.07it/s]
 30%|███       | 586/1939 [00:53<03:21,  6.71it/s]
 30%|███       | 588/1939 [00:53<02:45,  8.15it/s]
 30%|███       | 589/1939 [00:53<03:18,  6.80it/s]
 30%|███       | 591/1939 [00:53<02:32,  8.85it/s]
 31%|███       | 593/1939 [00:54<02:17,  9.77it/s]
 31%|███       | 595/1939 [00:54<01:57, 11.45it/s]
 31%|███       | 597/1939 [00:54<01:48, 12.36it/s]
 31%|███       | 599/1939 [00:54<02:05, 10.67it/s]
 31%|███       | 601/1939 [00:54<02:38,  8.44it/s]
 31%|███       | 603/1939 [00:54<02:19,  9.61it/s]
 31%|███▏      | 607/1939 [00:55<01:59, 11.18it/s]
 31%|███▏      | 609/1939 [00:55<02:18,  9.63it/s]
 32%|███▏      | 611/1939 [00:55<02:19,  9.53it/s]
 32%|███▏      | 613/1939 [00:56<02:23,  9.26it/s]
 32%|███▏      | 614/1939 [00:56<02:22,  9.29it/s]
 32%|███▏      | 616/1939 [00:56<02:24,  9.14it/s]
 32%|███▏      | 617/1939 [00:56<02:45,  8.00it/s]
 32%|███▏      | 618/1939 [00:56<03:13,  6.82it/s]
 32%|███▏      | 620/1939 [00:56<02:48,  7.82it/s]
 32%|███▏      | 621/1939 [00:57<03:09,  6.96it/s]
 32%|███▏      | 623/1939 [00:57<02:25,  9.02it/s]
 32%|███▏      | 625/1939 [00:57<02:00, 10.94it/s]
 32%|███▏      | 627/1939 [00:57<01:45, 12.43it/s]
 32%|███▏      | 630/1939 [00:57<02:12,  9.91it/s]
 33%|███▎      | 632/1939 [00:58<02:19,  9.36it/s]
 33%|███▎      | 635/1939 [00:58<01:45, 12.35it/s]
 33%|███▎      | 637/1939 [00:58<02:22,  9.11it/s]
 33%|███▎      | 639/1939 [00:58<02:05, 10.35it/s]
 33%|███▎      | 641/1939 [00:59<02:15,  9.61it/s]
 33%|███▎      | 643/1939 [00:59<02:10,  9.96it/s]
 33%|███▎      | 645/1939 [00:59<01:52, 11.48it/s]
 33%|███▎      | 649/1939 [00:59<01:36, 13.33it/s]
 34%|███▎      | 651/1939 [00:59<01:59, 10.75it/s]
 34%|███▎      | 653/1939 [00:59<01:47, 12.01it/s]
 34%|███▍      | 655/1939 [01:00<02:11,  9.76it/s]
 34%|███▍      | 657/1939 [01:00<02:25,  8.81it/s]
 34%|███▍      | 659/1939 [01:00<02:36,  8.19it/s]
 34%|███▍      | 662/1939 [01:00<01:57, 10.87it/s]
 34%|███▍      | 665/1939 [01:01<02:02, 10.42it/s]
 34%|███▍      | 667/1939 [01:01<02:19,  9.10it/s]
 35%|███▍      | 670/1939 [01:01<01:53, 11.18it/s]
 35%|███▍      | 672/1939 [01:02<02:13,  9.50it/s]
 35%|███▍      | 674/1939 [01:02<02:18,  9.16it/s]
 35%|███▍      | 676/1939 [01:02<02:28,  8.49it/s]
 35%|███▍      | 678/1939 [01:02<02:35,  8.09it/s]
 35%|███▌      | 680/1939 [01:03<02:43,  7.68it/s]
 35%|███▌      | 682/1939 [01:03<02:16,  9.21it/s]
 35%|███▌      | 684/1939 [01:03<02:06,  9.92it/s]
 35%|███▌      | 686/1939 [01:03<01:51, 11.21it/s]
 35%|███▌      | 688/1939 [01:03<02:10,  9.62it/s]
 36%|███▌      | 690/1939 [01:04<02:09,  9.63it/s]
 36%|███▌      | 693/1939 [01:04<02:13,  9.35it/s]
 36%|███▌      | 696/1939 [01:04<01:45, 11.83it/s]
 36%|███▌      | 699/1939 [01:04<01:24, 14.65it/s]
 36%|███▋      | 703/1939 [01:04<01:05, 18.96it/s]
 36%|███▋      | 706/1939 [01:04<00:59, 20.60it/s]
 37%|███▋      | 710/1939 [01:04<00:52, 23.51it/s]
 37%|███▋      | 716/1939 [01:05<00:39, 30.61it/s]
 37%|███▋      | 722/1939 [01:05<00:33, 36.78it/s]
 37%|███▋      | 726/1939 [01:05<00:50, 23.87it/s]
 38%|███▊      | 730/1939 [01:05<01:06, 18.09it/s]
 38%|███▊      | 733/1939 [01:06<01:44, 11.58it/s]
 38%|███▊      | 735/1939 [01:06<01:50, 10.86it/s]
 38%|███▊      | 737/1939 [01:06<01:41, 11.87it/s]
 38%|███▊      | 739/1939 [01:07<02:00,  9.96it/s]
 38%|███▊      | 741/1939 [01:07<01:50, 10.84it/s]
 38%|███▊      | 743/1939 [01:07<02:11,  9.10it/s]
 38%|███▊      | 745/1939 [01:07<02:16,  8.73it/s]
 39%|███▊      | 747/1939 [01:07<01:57, 10.17it/s]
 39%|███▊      | 749/1939 [01:08<02:09,  9.19it/s]
 39%|███▊      | 751/1939 [01:08<02:25,  8.14it/s]
 39%|███▉      | 753/1939 [01:08<02:03,  9.63it/s]
 39%|███▉      | 755/1939 [01:08<02:21,  8.39it/s]
 39%|███▉      | 757/1939 [01:09<02:11,  8.97it/s]
 39%|███▉      | 759/1939 [01:09<01:53, 10.36it/s]
 39%|███▉      | 761/1939 [01:09<02:09,  9.11it/s]
 39%|███▉      | 763/1939 [01:09<02:17,  8.52it/s]
 39%|███▉      | 765/1939 [01:09<01:56, 10.08it/s]
 40%|███▉      | 767/1939 [01:10<02:21,  8.29it/s]
 40%|███▉      | 769/1939 [01:10<02:50,  6.86it/s]
 40%|███▉      | 770/1939 [01:10<03:03,  6.35it/s]
 40%|███▉      | 771/1939 [01:11<03:07,  6.24it/s]
 40%|███▉      | 772/1939 [01:11<03:35,  5.41it/s]
 40%|███▉      | 774/1939 [01:11<02:39,  7.32it/s]
 40%|████      | 776/1939 [01:11<02:20,  8.28it/s]
 40%|████      | 777/1939 [01:11<02:30,  7.73it/s]
 40%|████      | 779/1939 [01:12<02:46,  6.98it/s]
 40%|████      | 780/1939 [01:12<02:52,  6.71it/s]
 40%|████      | 782/1939 [01:12<02:24,  8.02it/s]
 40%|████      | 785/1939 [01:12<01:46, 10.80it/s]
 41%|████      | 787/1939 [01:12<02:17,  8.35it/s]
 41%|████      | 789/1939 [01:13<02:42,  7.07it/s]
 41%|████      | 792/1939 [01:13<01:55,  9.91it/s]
 41%|████      | 794/1939 [01:13<01:55,  9.94it/s]
 41%|████      | 796/1939 [01:13<01:40, 11.38it/s]
 41%|████      | 798/1939 [01:14<01:46, 10.69it/s]
 41%|████▏     | 800/1939 [01:14<01:57,  9.73it/s]
 41%|████▏     | 802/1939 [01:14<01:41, 11.24it/s]
 41%|████▏     | 804/1939 [01:14<02:00,  9.43it/s]
 42%|████▏     | 806/1939 [01:14<02:15,  8.35it/s]
 42%|████▏     | 808/1939 [01:15<01:54,  9.89it/s]
 42%|████▏     | 810/1939 [01:15<02:05,  8.97it/s]
 42%|████▏     | 812/1939 [01:15<02:17,  8.17it/s]
 42%|████▏     | 813/1939 [01:15<02:43,  6.88it/s]
 42%|████▏     | 815/1939 [01:16<02:13,  8.41it/s]
 42%|████▏     | 817/1939 [01:16<03:00,  6.21it/s]
 42%|████▏     | 818/1939 [01:16<03:07,  5.98it/s]
 42%|████▏     | 819/1939 [01:16<03:10,  5.87it/s]
 42%|████▏     | 820/1939 [01:17<03:37,  5.14it/s]
 42%|████▏     | 821/1939 [01:17<03:24,  5.48it/s]
 42%|████▏     | 822/1939 [01:17<03:21,  5.55it/s]
 42%|████▏     | 823/1939 [01:17<03:59,  4.66it/s]
 43%|████▎     | 825/1939 [01:18<03:30,  5.30it/s]
 43%|████▎     | 826/1939 [01:18<03:39,  5.07it/s]
 43%|████▎     | 828/1939 [01:18<03:13,  5.73it/s]
 43%|████▎     | 829/1939 [01:18<03:20,  5.54it/s]
 43%|████▎     | 832/1939 [01:18<02:08,  8.62it/s]
 43%|████▎     | 834/1939 [01:19<01:50,  9.96it/s]
 43%|████▎     | 837/1939 [01:19<01:22, 13.37it/s]
 43%|████▎     | 839/1939 [01:19<01:30, 12.11it/s]
 43%|████▎     | 842/1939 [01:19<01:14, 14.78it/s]
 44%|████▎     | 844/1939 [01:19<01:25, 12.87it/s]
 44%|████▎     | 847/1939 [01:19<01:08, 15.95it/s]
 44%|████▍     | 851/1939 [01:20<01:07, 16.19it/s]
 44%|████▍     | 853/1939 [01:20<01:05, 16.70it/s]
 44%|████▍     | 855/1939 [01:20<01:21, 13.35it/s]
 44%|████▍     | 857/1939 [01:20<01:41, 10.71it/s]
 44%|████▍     | 859/1939 [01:21<01:59,  9.02it/s]
 44%|████▍     | 861/1939 [01:21<02:12,  8.13it/s]
 44%|████▍     | 862/1939 [01:21<02:28,  7.24it/s]
 45%|████▍     | 863/1939 [01:21<02:41,  6.68it/s]
 45%|████▍     | 864/1939 [01:21<02:39,  6.72it/s]
 45%|████▍     | 866/1939 [01:22<02:11,  8.17it/s]
 45%|████▍     | 872/1939 [01:22<01:01, 17.32it/s]
 45%|████▌     | 879/1939 [01:22<00:39, 27.03it/s]
 46%|████▌     | 884/1939 [01:22<00:32, 32.00it/s]
 46%|████▌     | 890/1939 [01:22<00:29, 35.30it/s]
 46%|████▌     | 894/1939 [01:22<00:30, 33.86it/s]
 46%|████▋     | 899/1939 [01:22<00:28, 36.68it/s]
 47%|████▋     | 903/1939 [01:23<00:59, 17.48it/s]
 47%|████▋     | 906/1939 [01:23<00:56, 18.34it/s]
 47%|████▋     | 910/1939 [01:23<00:59, 17.36it/s]
 47%|████▋     | 913/1939 [01:24<01:15, 13.51it/s]
 47%|████▋     | 915/1939 [01:24<01:25, 11.91it/s]
 47%|████▋     | 917/1939 [01:24<01:20, 12.64it/s]
 47%|████▋     | 919/1939 [01:24<01:40, 10.16it/s]
 48%|████▊     | 922/1939 [01:24<01:22, 12.32it/s]
 48%|████▊     | 927/1939 [01:25<01:17, 13.06it/s]
 48%|████▊     | 930/1939 [01:25<01:23, 12.10it/s]
 48%|████▊     | 932/1939 [01:26<01:52,  8.93it/s]
 48%|████▊     | 934/1939 [01:26<01:46,  9.40it/s]
 48%|████▊     | 938/1939 [01:26<01:15, 13.33it/s]
 49%|████▊     | 944/1939 [01:26<00:48, 20.56it/s]
 49%|████▉     | 950/1939 [01:26<00:36, 26.99it/s]
 49%|████▉     | 954/1939 [01:26<00:35, 28.08it/s]
 49%|████▉     | 958/1939 [01:26<00:36, 27.24it/s]
 50%|████▉     | 962/1939 [01:27<00:46, 21.03it/s]
 50%|████▉     | 965/1939 [01:27<00:43, 22.57it/s]
 50%|████▉     | 968/1939 [01:27<00:54, 17.69it/s]
 50%|█████     | 971/1939 [01:28<01:31, 10.60it/s]
 50%|█████     | 973/1939 [01:28<02:02,  7.89it/s]
 50%|█████     | 976/1939 [01:28<01:37,  9.83it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 327.59it/s]
 67%|██████▋   | 201/300 [09:16<44:16, 26.83s/it]

[[np.int64(0), False, 1], [np.int64(1), False, 10], [np.int64(2), False, 12], [np.int64(3), False, 9], [np.int64(4), False, 10], [np.int64(5), False, 0], [np.int64(6), False, 10], [np.int64(7), False, 11], [np.int64(8), False, 3], [np.int64(11), False, 9], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2160, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.2605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3192, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [09:16<28:35, 17.68s/it]

tensor(12.2592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4297, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3418, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:16<17:49, 11.26s/it]

tensor(12.2600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4207, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [09:16<11:31,  7.43s/it]

tensor(12.2600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4478, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4740, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4825, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:17<07:36,  5.02s/it]

tensor(12.2515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5050, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0387, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5210, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:17<05:06,  3.45s/it]

tensor(12.2605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5225, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:17<03:28,  2.40s/it]

tensor(12.2634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5406, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5507, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5602, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [09:17<02:23,  1.68s/it]

tensor(12.2479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5606, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5597, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [09:17<01:39,  1.20s/it]

tensor(12.2391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5601, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:17<01:09,  1.16it/s]

tensor(12.2372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5556, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5574, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5655, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [09:18<00:49,  1.59it/s]

tensor(12.2257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5813, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5866, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [09:18<00:35,  2.14it/s]

tensor(12.2207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5888, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:18<00:26,  2.82it/s]

tensor(12.2187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2166, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5980, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5992, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:18<00:20,  3.61it/s]

tensor(12.2125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5957, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5955, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:18<00:15,  4.51it/s]

tensor(12.2083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5977, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [09:19<00:12,  5.45it/s]

tensor(12.2062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5961, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5931, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [09:19<00:10,  6.37it/s]

tensor(12.1991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5940, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5902, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:19<00:08,  7.23it/s]

tensor(12.1947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5923, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [09:19<00:07,  8.04it/s]

tensor(12.1925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5905, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5869, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5877, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:19<00:07,  8.66it/s]

tensor(12.1868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5880, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [09:20<00:06,  9.21it/s]

tensor(12.1834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5905, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:20<00:05,  9.62it/s]

tensor(12.1817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5916, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5919, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5948, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:20<00:05,  9.93it/s]

tensor(12.1763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5937, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5908, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [09:20<00:05, 10.16it/s]

tensor(12.1729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5938, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [09:20<00:04, 10.29it/s]

tensor(12.1711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5925, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5908, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([209,  88, 139, 143, 257, 296,  85,  24, 143, 140, 195,  33,  83, 104])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 4/1939 [00:00<01:00, 31.98it/s]
  1%|          | 10/1939 [00:00<00:44, 43.67it/s]
  1%|          | 15/1939 [00:00<00:43, 43.75it/s]
  1%|          | 20/1939 [00:00<00:50, 37.73it/s]
  1%|          | 24/1939 [00:00<00:56, 34.06it/s]
  2%|▏         | 30/1939 [00:00<00:48, 39.66it/s]
  2%|▏         | 36/1939 [00:00<00:43, 44.18it/s]
  2%|▏         | 41/1939 [00:01<01:17, 24.43it/s]
  2%|▏         | 45/1939 [00:01<01:43, 18.29it/s]
  3%|▎         | 49/1939 [00:01<01:46, 17.82it/s]
  3%|▎         | 52/1939 [00:02<01:41, 18.64it/s]
  3%|▎         | 55/1939 [00:02<02:21, 13.36it/s]
  3%|▎         | 57/1939 [00:02<02:43, 11.50it/s]
  3%|▎         | 59/1939 [00:02<02:56, 10.62it/s]
  3%|▎         | 61/1939 [00:03<02:42, 11.52it/s]
  3%|▎         | 66/1939 [00:03<02:48, 11.14it/s]
  4%|▎         | 69/1939 [00:03<02:22, 13.13it/s]
  4%|▎         | 71/1939 [00:03<02:38, 11.79it/s]
  4%|▍         | 73/1939 [00:04<03:37,  8.57it/s]
  4%|▍         | 75/1939 [00:04<03:08,  9.88it/s]
  4%|▍         | 78/1939 [00:04<03:34,  8.68it/s]
  4%|▍         | 80/1939 [00:05<04:17,  7.22it/s]
  4%|▍         | 81/1939 [00:05<04:42,  6.57it/s]
  4%|▍         | 82/1939 [00:05<04:58,  6.21it/s]
  4%|▍         | 83/1939 [00:05<05:06,  6.05it/s]
  4%|▍         | 85/1939 [00:06<03:56,  7.84it/s]
  4%|▍         | 86/1939 [00:06<03:49,  8.07it/s]
  5%|▍         | 88/1939 [00:06<02:59, 10.31it/s]
 83%|████████▎ | 249/300 [09:31<00:04, 10.29it/s]
  5%|▍         | 94/1939 [00:06<02:43, 11.26it/s]
  5%|▍         | 96/1939 [00:07<03:09,  9.72it/s]
  5%|▌         | 98/1939 [00:07<02:46, 11.07it/s]
  5%|▌         | 100/1939 [00:07<03:30,  8.75it/s]
  5%|▌         | 102/1939 [00:07<03:47,  8.08it/s]
  5%|▌         | 105/1939 [00:07<03:03, 10.01it/s]
  6%|▌         | 107/1939 [00:08<04:06,  7.44it/s]
  6%|▌         | 110/1939 [00:08<03:43,  8.19it/s]
  6%|▌         | 112/1939 [00:08<03:23,  8.99it/s]
  6%|▌         | 115/1939 [00:09<03:14,  9.38it/s]
  6%|▌         | 117/1939 [00:09<03:14,  9.35it/s]
  6%|▌         | 119/1939 [00:09<04:03,  7.47it/s]
  6%|▌         | 120/1939 [00:10<04:46,  6.34it/s]
  6%|▌         | 121/1939 [00:10<04:47,  6.33it/s]
  6%|▋         | 123/1939 [00:10<03:42,  8.15it/s]
  6%|▋         | 126/1939 [00:10<02:35, 11.64it/s]
  7%|▋         | 128/1939 [00:10<03:21,  8.99it/s]
  7%|▋         | 131/1939 [00:10<02:31, 11.91it/s]
  7%|▋         | 133/1939 [00:11<03:16,  9.20it/s]
  7%|▋         | 135/1939 [00:11<02:55, 10.28it/s]
  7%|▋         | 137/1939 [00:11<03:16,  9.16it/s]
  7%|▋         | 139/1939 [00:11<03:28,  8.61it/s]
  7%|▋         | 141/1939 [00:12<02:59, 10.02it/s]
  7%|▋         | 143/1939 [00:12<02:54, 10.26it/s]
  7%|▋         | 145/1939 [00:12<03:02,  9.85it/s]
  8%|▊         | 147/1939 [00:12<02:39, 11.23it/s]
  8%|▊         | 149/1939 [00:12<03:10,  9.37it/s]
  8%|▊         | 151/1939 [00:13<03:45,  7.92it/s]
  8%|▊         | 153/1939 [00:13<04:20,  6.86it/s]
  8%|▊         | 155/1939 [00:13<03:31,  8.45it/s]
  8%|▊         | 157/1939 [00:14<04:06,  7.22it/s]
  8%|▊         | 158/1939 [00:14<05:33,  5.34it/s]
  8%|▊         | 159/1939 [00:14<05:36,  5.29it/s]
  8%|▊         | 160/1939 [00:14<05:30,  5.38it/s]
  8%|▊         | 161/1939 [00:15<05:45,  5.15it/s]
  8%|▊         | 162/1939 [00:15<05:10,  5.72it/s]
  8%|▊         | 163/1939 [00:15<04:51,  6.08it/s]
  8%|▊         | 164/1939 [00:15<04:43,  6.27it/s]
  9%|▊         | 167/1939 [00:15<02:49, 10.48it/s]
  9%|▉         | 174/1939 [00:15<01:16, 23.06it/s]
  9%|▉         | 181/1939 [00:15<00:51, 33.84it/s]
 10%|▉         | 187/1939 [00:15<00:43, 40.20it/s]
 10%|▉         | 193/1939 [00:16<00:39, 44.43it/s]
 10%|█         | 198/1939 [00:16<00:38, 45.72it/s]
 10%|█         | 203/1939 [00:17<01:51, 15.56it/s]
 11%|█         | 207/1939 [00:17<02:50, 10.16it/s]
 11%|█         | 210/1939 [00:17<02:27, 11.71it/s]
 11%|█         | 213/1939 [00:18<02:58,  9.67it/s]
 11%|█         | 216/1939 [00:18<02:28, 11.60it/s]
 11%|█▏        | 219/1939 [00:18<02:25, 11.83it/s]
 11%|█▏        | 222/1939 [00:19<02:32, 11.26it/s]
 12%|█▏        | 224/1939 [00:19<02:50, 10.03it/s]
 12%|█▏        | 227/1939 [00:19<02:17, 12.43it/s]
 12%|█▏        | 229/1939 [00:19<03:02,  9.38it/s]
 12%|█▏        | 232/1939 [00:19<02:22, 11.96it/s]
 12%|█▏        | 234/1939 [00:20<03:09,  8.99it/s]
 12%|█▏        | 236/1939 [00:20<03:41,  7.67it/s]
 12%|█▏        | 239/1939 [00:21<03:48,  7.43it/s]
 12%|█▏        | 241/1939 [00:21<04:48,  5.89it/s]
 12%|█▏        | 242/1939 [00:22<05:32,  5.10it/s]
 13%|█▎        | 244/1939 [00:22<04:36,  6.14it/s]
 13%|█▎        | 245/1939 [00:22<05:24,  5.22it/s]
 13%|█▎        | 246/1939 [00:22<05:21,  5.26it/s]
 13%|█▎        | 248/1939 [00:23<04:57,  5.68it/s]
 13%|█▎        | 250/1939 [00:23<04:13,  6.65it/s]
 13%|█▎        | 251/1939 [00:23<04:13,  6.67it/s]
 13%|█▎        | 253/1939 [00:23<03:19,  8.46it/s]
 13%|█▎        | 255/1939 [00:23<02:50,  9.87it/s]
 13%|█▎        | 258/1939 [00:23<02:36, 10.74it/s]
 13%|█▎        | 260/1939 [00:24<03:35,  7.79it/s]
 14%|█▎        | 262/1939 [00:24<03:03,  9.15it/s]
 14%|█▎        | 264/1939 [00:24<04:21,  6.40it/s]
 14%|█▎        | 266/1939 [00:25<03:30,  7.96it/s]
 14%|█▍        | 268/1939 [00:25<03:21,  8.31it/s]
 14%|█▍        | 270/1939 [00:25<03:32,  7.87it/s]
 14%|█▍        | 272/1939 [00:25<02:56,  9.47it/s]
 14%|█▍        | 274/1939 [00:26<03:38,  7.61it/s]
 14%|█▍        | 277/1939 [00:26<02:41, 10.28it/s]
 14%|█▍        | 281/1939 [00:26<02:49,  9.79it/s]
 15%|█▍        | 283/1939 [00:26<02:32, 10.89it/s]
 15%|█▍        | 285/1939 [00:27<03:18,  8.35it/s]
 15%|█▍        | 287/1939 [00:27<03:07,  8.83it/s]
 15%|█▍        | 289/1939 [00:27<02:51,  9.61it/s]
 15%|█▌        | 291/1939 [00:27<02:27, 11.16it/s]
 15%|█▌        | 293/1939 [00:27<02:38, 10.37it/s]
 15%|█▌        | 295/1939 [00:27<02:22, 11.57it/s]
 15%|█▌        | 297/1939 [00:28<02:43, 10.03it/s]
 15%|█▌        | 299/1939 [00:28<02:53,  9.45it/s]
 16%|█▌        | 302/1939 [00:28<02:07, 12.80it/s]
 16%|█▌        | 304/1939 [00:28<02:34, 10.60it/s]
 16%|█▌        | 306/1939 [00:29<02:21, 11.54it/s]
 16%|█▌        | 308/1939 [00:29<02:42, 10.01it/s]
 16%|█▌        | 310/1939 [00:29<02:24, 11.31it/s]
 16%|█▌        | 312/1939 [00:29<02:43,  9.97it/s]
 16%|█▌        | 314/1939 [00:29<02:22, 11.44it/s]
 16%|█▋        | 316/1939 [00:30<03:17,  8.22it/s]
 16%|█▋        | 318/1939 [00:30<04:03,  6.66it/s]
 16%|█▋        | 319/1939 [00:30<04:25,  6.11it/s]
 17%|█▋        | 320/1939 [00:30<04:13,  6.38it/s]
 17%|█▋        | 321/1939 [00:31<04:32,  5.94it/s]
 17%|█▋        | 322/1939 [00:31<06:04,  4.44it/s]
 17%|█▋        | 326/1939 [00:31<02:58,  9.06it/s]
 17%|█▋        | 328/1939 [00:31<02:56,  9.14it/s]
 17%|█▋        | 331/1939 [00:32<02:10, 12.36it/s]
 17%|█▋        | 335/1939 [00:32<01:31, 17.44it/s]
 18%|█▊        | 341/1939 [00:32<01:01, 25.78it/s]
 18%|█▊        | 347/1939 [00:32<00:48, 32.66it/s]
 18%|█▊        | 351/1939 [00:32<01:26, 18.38it/s]
 18%|█▊        | 355/1939 [00:33<02:53,  9.13it/s]
 18%|█▊        | 358/1939 [00:33<02:31, 10.46it/s]
 19%|█▊        | 361/1939 [00:34<02:27, 10.67it/s]
 19%|█▊        | 363/1939 [00:34<02:58,  8.85it/s]
 19%|█▉        | 365/1939 [00:34<02:38,  9.96it/s]
 19%|█▉        | 367/1939 [00:34<02:42,  9.67it/s]
 19%|█▉        | 370/1939 [00:35<02:36, 10.04it/s]
 19%|█▉        | 372/1939 [00:35<02:42,  9.64it/s]
 19%|█▉        | 374/1939 [00:35<02:24, 10.85it/s]
 19%|█▉        | 376/1939 [00:35<03:07,  8.32it/s]
 19%|█▉        | 378/1939 [00:36<03:26,  7.55it/s]
 20%|█▉        | 380/1939 [00:36<02:50,  9.14it/s]
 20%|█▉        | 382/1939 [00:36<03:54,  6.65it/s]
 20%|█▉        | 384/1939 [00:37<03:43,  6.97it/s]
 20%|█▉        | 386/1939 [00:37<03:07,  8.27it/s]
 20%|██        | 388/1939 [00:37<03:48,  6.80it/s]
 20%|██        | 389/1939 [00:37<03:41,  6.98it/s]
 20%|██        | 390/1939 [00:38<04:48,  5.36it/s]
 20%|██        | 391/1939 [00:38<04:31,  5.69it/s]
 20%|██        | 393/1939 [00:38<03:54,  6.59it/s]
 20%|██        | 394/1939 [00:38<04:29,  5.73it/s]
 20%|██        | 396/1939 [00:39<04:44,  5.42it/s]
 21%|██        | 398/1939 [00:39<04:29,  5.72it/s]
 21%|██        | 400/1939 [00:39<03:31,  7.28it/s]
 21%|██        | 403/1939 [00:39<02:29, 10.31it/s]
 21%|██        | 405/1939 [00:40<03:17,  7.76it/s]
 21%|██        | 407/1939 [00:40<03:20,  7.63it/s]
 21%|██        | 409/1939 [00:40<02:52,  8.85it/s]
 21%|██        | 411/1939 [00:40<02:47,  9.12it/s]
 21%|██▏       | 413/1939 [00:41<03:09,  8.05it/s]
 21%|██▏       | 415/1939 [00:41<03:45,  6.75it/s]
 21%|██▏       | 416/1939 [00:41<04:06,  6.19it/s]
 22%|██▏       | 417/1939 [00:42<05:08,  4.93it/s]
 22%|██▏       | 419/1939 [00:42<05:16,  4.81it/s]
 22%|██▏       | 421/1939 [00:42<03:58,  6.35it/s]
 22%|██▏       | 422/1939 [00:43<04:52,  5.18it/s]
 22%|██▏       | 425/1939 [00:43<03:09,  7.99it/s]
 22%|██▏       | 428/1939 [00:43<03:14,  7.78it/s]
 22%|██▏       | 430/1939 [00:43<02:43,  9.23it/s]
 23%|██▎       | 437/1939 [00:43<01:22, 18.17it/s]
 23%|██▎       | 442/1939 [00:43<01:03, 23.48it/s]
 23%|██▎       | 446/1939 [00:44<01:07, 22.13it/s]
 23%|██▎       | 452/1939 [00:44<00:51, 28.67it/s]
 24%|██▎       | 458/1939 [00:44<00:43, 34.36it/s]
 24%|██▍       | 465/1939 [00:44<00:34, 42.42it/s]
 24%|██▍       | 471/1939 [00:44<00:32, 45.65it/s]
 25%|██▍       | 477/1939 [00:44<00:29, 48.75it/s]
 25%|██▍       | 483/1939 [00:45<01:04, 22.48it/s]
 25%|██▌       | 488/1939 [00:45<01:00, 24.17it/s]
 25%|██▌       | 492/1939 [00:45<01:29, 16.16it/s]
 26%|██▌       | 495/1939 [00:46<01:42, 14.04it/s]
 26%|██▌       | 498/1939 [00:46<02:02, 11.77it/s]
 26%|██▌       | 500/1939 [00:46<02:19, 10.31it/s]
 26%|██▌       | 502/1939 [00:47<02:08, 11.18it/s]
 26%|██▌       | 505/1939 [00:47<01:59, 12.03it/s]
 26%|██▌       | 507/1939 [00:47<01:53, 12.63it/s]
 27%|██▋       | 515/1939 [00:47<01:01, 23.29it/s]
 27%|██▋       | 521/1939 [00:47<00:48, 29.51it/s]
 27%|██▋       | 526/1939 [00:47<00:43, 32.17it/s]
 27%|██▋       | 530/1939 [00:47<00:41, 33.66it/s]
 28%|██▊       | 536/1939 [00:47<00:37, 37.80it/s]
 28%|██▊       | 541/1939 [00:48<01:16, 18.28it/s]
 28%|██▊       | 546/1939 [00:48<01:15, 18.54it/s]
 28%|██▊       | 549/1939 [00:49<01:37, 14.30it/s]
 28%|██▊       | 552/1939 [00:49<01:44, 13.32it/s]
 29%|██▊       | 554/1939 [00:49<01:38, 14.04it/s]
 29%|██▊       | 556/1939 [00:49<01:47, 12.82it/s]
 29%|██▉       | 558/1939 [00:50<01:59, 11.60it/s]
 29%|██▉       | 561/1939 [00:50<01:56, 11.79it/s]
 29%|██▉       | 563/1939 [00:50<02:02, 11.25it/s]
 29%|██▉       | 566/1939 [00:50<01:39, 13.78it/s]
 29%|██▉       | 568/1939 [00:50<01:54, 12.01it/s]
 29%|██▉       | 571/1939 [00:51<02:04, 10.98it/s]
 30%|██▉       | 573/1939 [00:51<02:43,  8.35it/s]
 30%|██▉       | 575/1939 [00:52<04:26,  5.12it/s]
 30%|██▉       | 578/1939 [00:52<03:12,  7.09it/s]
 30%|██▉       | 580/1939 [00:52<03:36,  6.28it/s]
 30%|███       | 582/1939 [00:53<03:58,  5.70it/s]
 30%|███       | 584/1939 [00:53<04:08,  5.45it/s]
 30%|███       | 586/1939 [00:54<04:19,  5.22it/s]
 30%|███       | 589/1939 [00:54<03:30,  6.41it/s]
 30%|███       | 591/1939 [00:54<02:59,  7.50it/s]
 31%|███       | 592/1939 [00:54<03:32,  6.34it/s]
 31%|███       | 593/1939 [00:55<03:33,  6.30it/s]
 31%|███       | 595/1939 [00:55<03:16,  6.84it/s]
 31%|███       | 597/1939 [00:55<02:39,  8.42it/s]
 31%|███       | 599/1939 [00:55<03:21,  6.65it/s]
 31%|███       | 601/1939 [00:56<03:15,  6.83it/s]
 31%|███       | 603/1939 [00:56<02:49,  7.90it/s]
 31%|███▏      | 607/1939 [00:56<02:45,  8.04it/s]
 31%|███▏      | 608/1939 [00:57<03:07,  7.10it/s]
 31%|███▏      | 609/1939 [00:57<03:56,  5.63it/s]
 32%|███▏      | 611/1939 [00:57<04:08,  5.35it/s]
 32%|███▏      | 612/1939 [00:57<03:50,  5.75it/s]
 32%|███▏      | 613/1939 [00:58<04:00,  5.51it/s]
 32%|███▏      | 614/1939 [00:58<04:27,  4.95it/s]
 32%|███▏      | 615/1939 [00:58<04:24,  5.00it/s]
 32%|███▏      | 616/1939 [00:58<04:28,  4.93it/s]
 32%|███▏      | 617/1939 [00:59<04:35,  4.79it/s]
 32%|███▏      | 618/1939 [00:59<05:27,  4.03it/s]
 32%|███▏      | 620/1939 [00:59<04:25,  4.96it/s]
 32%|███▏      | 622/1939 [00:59<03:08,  7.00it/s]
 32%|███▏      | 624/1939 [00:59<02:29,  8.79it/s]
 32%|███▏      | 630/1939 [01:00<01:36, 13.53it/s]
 33%|███▎      | 632/1939 [01:00<01:37, 13.47it/s]
 33%|███▎      | 636/1939 [01:00<01:41, 12.85it/s]
 33%|███▎      | 638/1939 [01:00<01:43, 12.63it/s]
 33%|███▎      | 640/1939 [01:00<01:34, 13.82it/s]
 33%|███▎      | 642/1939 [01:01<01:58, 10.99it/s]
 33%|███▎      | 644/1939 [01:01<02:38,  8.17it/s]
 33%|███▎      | 647/1939 [01:01<01:57, 11.02it/s]
 33%|███▎      | 649/1939 [01:02<02:30,  8.56it/s]
 34%|███▎      | 651/1939 [01:02<02:11,  9.78it/s]
 34%|███▍      | 656/1939 [01:02<01:59, 10.78it/s]
 34%|███▍      | 658/1939 [01:03<02:34,  8.30it/s]
 34%|███▍      | 660/1939 [01:03<02:13,  9.56it/s]
 34%|███▍      | 665/1939 [01:03<01:44, 12.23it/s]
 34%|███▍      | 667/1939 [01:03<02:18,  9.20it/s]
 35%|███▍      | 669/1939 [01:04<02:22,  8.90it/s]
 35%|███▍      | 672/1939 [01:04<02:39,  7.96it/s]
 35%|███▍      | 673/1939 [01:04<02:52,  7.34it/s]
 35%|███▍      | 676/1939 [01:05<02:34,  8.17it/s]
 35%|███▍      | 677/1939 [01:05<02:51,  7.35it/s]
 35%|███▍      | 678/1939 [01:05<03:18,  6.35it/s]
 35%|███▌      | 680/1939 [01:06<03:41,  5.68it/s]
 35%|███▌      | 682/1939 [01:06<02:53,  7.23it/s]
 35%|███▌      | 683/1939 [01:06<03:46,  5.54it/s]
 35%|███▌      | 685/1939 [01:06<02:50,  7.35it/s]
 35%|███▌      | 687/1939 [01:07<03:17,  6.33it/s]
 36%|███▌      | 689/1939 [01:07<03:47,  5.50it/s]
 36%|███▌      | 691/1939 [01:07<02:56,  7.07it/s]
 36%|███▌      | 697/1939 [01:07<01:28, 14.01it/s]
 36%|███▋      | 703/1939 [01:07<00:58, 21.07it/s]
 37%|███▋      | 709/1939 [01:07<00:44, 27.94it/s]
 37%|███▋      | 713/1939 [01:08<00:41, 29.74it/s]
 37%|███▋      | 718/1939 [01:08<00:39, 30.55it/s]
 37%|███▋      | 722/1939 [01:08<00:42, 28.41it/s]
 38%|███▊      | 728/1939 [01:08<00:37, 32.36it/s]
 38%|███▊      | 732/1939 [01:09<01:32, 13.00it/s]
 38%|███▊      | 735/1939 [01:09<02:05,  9.56it/s]
 38%|███▊      | 739/1939 [01:10<01:50, 10.85it/s]
 38%|███▊      | 741/1939 [01:10<01:43, 11.55it/s]
 38%|███▊      | 743/1939 [01:10<02:02,  9.75it/s]
 38%|███▊      | 745/1939 [01:10<02:03,  9.66it/s]
 39%|███▊      | 748/1939 [01:11<01:40, 11.91it/s]
 39%|███▊      | 750/1939 [01:11<01:50, 10.74it/s]
 39%|███▉      | 752/1939 [01:11<02:10,  9.08it/s]
 39%|███▉      | 755/1939 [01:12<02:27,  8.04it/s]
 39%|███▉      | 757/1939 [01:12<02:57,  6.67it/s]
 39%|███▉      | 760/1939 [01:12<02:51,  6.89it/s]
 39%|███▉      | 763/1939 [01:13<02:50,  6.90it/s]
 39%|███▉      | 765/1939 [01:13<02:28,  7.92it/s]
 40%|███▉      | 766/1939 [01:13<03:20,  5.85it/s]
 40%|███▉      | 767/1939 [01:14<03:55,  4.98it/s]
 40%|███▉      | 768/1939 [01:14<03:57,  4.92it/s]
 40%|███▉      | 769/1939 [01:14<04:42,  4.14it/s]
 40%|███▉      | 770/1939 [01:15<04:38,  4.19it/s]
 40%|███▉      | 771/1939 [01:15<04:32,  4.29it/s]
 40%|███▉      | 772/1939 [01:15<05:14,  3.71it/s]
 40%|███▉      | 773/1939 [01:15<04:51,  3.99it/s]
 40%|███▉      | 775/1939 [01:15<03:14,  5.99it/s]
 40%|████      | 776/1939 [01:16<04:14,  4.57it/s]
 40%|████      | 777/1939 [01:16<05:10,  3.74it/s]
 40%|████      | 779/1939 [01:17<04:48,  4.02it/s]
 40%|████      | 780/1939 [01:17<05:03,  3.82it/s]
 40%|████      | 782/1939 [01:17<03:27,  5.59it/s]
 40%|████      | 784/1939 [01:18<03:40,  5.24it/s]
 41%|████      | 786/1939 [01:18<02:46,  6.92it/s]
 41%|████      | 788/1939 [01:18<03:01,  6.34it/s]
 41%|████      | 789/1939 [01:18<03:46,  5.08it/s]
 41%|████      | 792/1939 [01:19<02:26,  7.81it/s]
 41%|████      | 794/1939 [01:19<02:24,  7.94it/s]
 41%|████      | 796/1939 [01:19<02:02,  9.36it/s]
 41%|████      | 798/1939 [01:19<02:27,  7.75it/s]
 41%|████▏     | 800/1939 [01:20<02:31,  7.53it/s]
 41%|████▏     | 802/1939 [01:20<02:04,  9.13it/s]
 41%|████▏     | 804/1939 [01:20<02:31,  7.51it/s]
 42%|████▏     | 806/1939 [01:20<02:58,  6.36it/s]
 42%|████▏     | 809/1939 [01:21<02:55,  6.45it/s]
 42%|████▏     | 812/1939 [01:21<02:51,  6.56it/s]
 42%|████▏     | 813/1939 [01:22<03:37,  5.18it/s]
 42%|████▏     | 816/1939 [01:22<03:20,  5.61it/s]
 42%|████▏     | 817/1939 [01:23<03:55,  4.76it/s]
 42%|████▏     | 818/1939 [01:23<03:55,  4.77it/s]
 42%|████▏     | 819/1939 [01:23<04:27,  4.18it/s]
 42%|████▏     | 820/1939 [01:23<04:24,  4.23it/s]
 42%|████▏     | 821/1939 [01:24<04:11,  4.45it/s]
 42%|████▏     | 822/1939 [01:24<03:55,  4.73it/s]
 42%|████▏     | 823/1939 [01:24<04:40,  3.99it/s]
 43%|████▎     | 825/1939 [01:25<04:21,  4.26it/s]
 43%|████▎     | 826/1939 [01:25<04:32,  4.09it/s]
 43%|████▎     | 828/1939 [01:25<03:39,  5.07it/s]
 43%|████▎     | 829/1939 [01:25<03:28,  5.32it/s]
 43%|████▎     | 832/1939 [01:25<02:07,  8.67it/s]
 43%|████▎     | 834/1939 [01:25<01:46, 10.35it/s]
 43%|████▎     | 837/1939 [01:26<01:19, 13.86it/s]
 43%|████▎     | 839/1939 [01:26<01:28, 12.40it/s]
 43%|████▎     | 842/1939 [01:26<01:12, 15.18it/s]
 44%|████▎     | 844/1939 [01:26<01:26, 12.62it/s]
 44%|████▎     | 846/1939 [01:26<01:20, 13.55it/s]
 44%|████▎     | 848/1939 [01:26<01:17, 14.01it/s]
 44%|████▍     | 851/1939 [01:27<01:22, 13.22it/s]
 44%|████▍     | 853/1939 [01:27<01:20, 13.46it/s]
 44%|████▍     | 855/1939 [01:27<01:46, 10.16it/s]
 44%|████▍     | 857/1939 [01:28<02:15,  7.99it/s]
 44%|████▍     | 859/1939 [01:28<02:22,  7.58it/s]
 44%|████▍     | 861/1939 [01:28<02:30,  7.14it/s]
 44%|████▍     | 862/1939 [01:28<02:44,  6.55it/s]
 45%|████▍     | 863/1939 [01:29<02:58,  6.02it/s]
 45%|████▍     | 864/1939 [01:29<03:48,  4.71it/s]
 45%|████▍     | 866/1939 [01:29<02:42,  6.62it/s]
 45%|████▍     | 872/1939 [01:29<01:12, 14.65it/s]
 45%|████▌     | 879/1939 [01:29<00:43, 24.48it/s]
 46%|████▌     | 886/1939 [01:29<00:31, 33.00it/s]
 46%|████▌     | 894/1939 [01:29<00:24, 43.09it/s]
 46%|████▋     | 901/1939 [01:30<00:21, 48.36it/s]
 47%|████▋     | 908/1939 [01:30<00:19, 52.53it/s]
 47%|████▋     | 914/1939 [01:30<00:46, 21.86it/s]
 47%|████▋     | 919/1939 [01:31<01:01, 16.63it/s]
 48%|████▊     | 923/1939 [01:31<00:57, 17.74it/s]
 48%|████▊     | 927/1939 [01:31<01:07, 15.09it/s]
 48%|████▊     | 930/1939 [01:32<01:02, 16.21it/s]
 48%|████▊     | 933/1939 [01:32<01:31, 11.03it/s]
 48%|████▊     | 936/1939 [01:32<01:19, 12.63it/s]
 49%|████▊     | 942/1939 [01:32<00:53, 18.57it/s]
 49%|████▉     | 948/1939 [01:32<00:39, 24.78it/s]
 49%|████▉     | 954/1939 [01:33<00:32, 29.98it/s]
 50%|████▉     | 960/1939 [01:33<00:27, 35.28it/s]
 50%|████▉     | 965/1939 [01:33<00:42, 22.85it/s]
 50%|████▉     | 969/1939 [01:34<00:58, 16.59it/s]
 50%|█████     | 972/1939 [01:34<01:19, 12.16it/s]
 50%|█████     | 975/1939 [01:34<01:25, 11.27it/s]
 50%|█████     | 977/1939 [01:35<01:39,  9.70it/s]
 51%|█████     | 980/1939 [01:35<01:35, 10.08it/s]
 51%|█████     | 982/1939 [01:35<01:42,  9.30it/s]
 51%|█████     | 984/1939 [01:35<01:35, 10.03it/s]
 51%|█████     | 987/1939 [01:36<01:35,  9.97it/s]
 51%|█████     | 991/1939 [01:36<01:30, 10.48it/s]
 51%|█████     | 993/1939 [01:37<01:54,  8.28it/s]
 51%|█████▏    | 995/1939 [01:37<01:38,  9.60it/s]
 51%|█████▏    | 997/1939 [01:37<02:03,  7.63it/s]
 52%|█████▏    | 999/1939 [01:37<02:23,  6.56it/s]
 52%|█████▏    | 1001/1939 [01:38<02:00,  7.81it/s]
 52%|█████▏    | 1003/1939 [01:38<02:22,  6.57it/s]
 52%|█████▏    | 1005/1939 [01:38<02:39,  5.84it/s]
 52%|█████▏    | 1006/1939 [01:39<03:10,  4.90it/s]
 52%|█████▏    | 1009/1939 [01:39<02:50,  5.45it/s]
 52%|█████▏    | 1010/1939 [01:40<03:18,  4.69it/s]
 52%|█████▏    | 1011/1939 [01:40<03:46,  4.09it/s]
 52%|█████▏    | 1012/1939 [01:40<04:16,  3.61it/s]
 52%|█████▏    | 1013/1939 [01:41<04:07,  3.75it/s]
 52%|█████▏    | 1014/1939 [01:41<04:36,  3.35it/s]
 52%|█████▏    | 1015/1939 [01:41<04:58,  3.10it/s]
 52%|█████▏    | 1016/1939 [01:42<05:13,  2.95it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 307.43it/s]
 84%|████████▎ | 251/300 [12:37<24:12, 29.65s/it]

[[np.int64(0), False, 2], [np.int64(1), False, 9], [np.int64(3), False, 13], [np.int64(4), False, 5], [np.int64(6), False, 13], [np.int64(7), False, 13], [np.int64(8), False, 12], [np.int64(10), False, 5], [np.int64(11), False, 13]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6195, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.1846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5051, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [12:38<19:33, 24.44s/it]

tensor(12.2262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0487, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8379, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [12:38<12:28, 16.28s/it]

tensor(12.2480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0553, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6292, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0611, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.6546, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0712, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5592, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [12:38<08:05, 11.04s/it]

tensor(12.4039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0820, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2560, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0915, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0870, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [12:38<05:18,  7.58s/it]

tensor(12.5190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0981, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1420, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [12:38<03:29,  5.25s/it]

tensor(12.5868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1016, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5498, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1033, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8823, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1035, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5590, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [12:39<02:19,  3.66s/it]

tensor(12.8112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1024, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6948, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1010, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3005, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [12:39<01:32,  2.57s/it]

tensor(12.8359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0985, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5966, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [12:39<01:01,  1.82s/it]

tensor(12.8532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0955, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6612, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0916, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6281, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0872, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6591, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [12:39<00:41,  1.30s/it]

tensor(12.7812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0824, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0773, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8030, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [12:39<00:28,  1.07it/s]

tensor(12.7036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0723, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8382, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [12:40<00:19,  1.47it/s]

tensor(12.6688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0672, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8904, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0618, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9276, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0562, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9773, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [12:40<00:13,  1.98it/s]

tensor(12.6704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0503, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0019, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6468, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0145, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [12:40<00:09,  2.62it/s]

tensor(12.6131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0391, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0226, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [12:40<00:06,  3.38it/s]

tensor(12.5855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9906, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9706, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [12:40<00:04,  4.25it/s]

tensor(12.5130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9878, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0024, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [12:40<00:03,  5.19it/s]

tensor(12.4774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0306, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [12:41<00:02,  6.11it/s]

tensor(12.4558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0906, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1389, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [12:41<00:02,  6.97it/s]

tensor(12.4151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1743, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2057, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [12:41<00:01,  7.70it/s]

tensor(12.3962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2265, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [12:41<00:01,  8.38it/s]

tensor(12.3834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2826, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [12:41<00:00,  8.88it/s]

tensor(12.3551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3119, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [12:42<00:00,  9.25it/s]

tensor(12.3306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3310, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [12:42<00:00,  9.61it/s]

tensor(12.3147, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3516, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3764, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2893, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4000, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [12:42<00:00,  9.82it/s]

tensor(12.2794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4071, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4205, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [12:42<00:00,  2.54s/it]

Model training finished!

Infer time:  0.0029006004333496094
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 0
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.440489005428
NMI         : 0.601843093665
Runtime     : 782.09 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed0

==============================================================================================================
PRAGA RUN | S2-E15 | seed=1
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 5.010e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:26, 11.27it/s]

tensor(17.7226, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3792, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6953, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2367, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6856, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3045, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:26, 11.08it/s]

tensor(17.6733, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5625, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6617, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9909, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6493, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5730, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:23, 12.65it/s]

tensor(17.6376, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2948, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6258, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1425, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6151, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1032, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:00<00:21, 13.14it/s]

tensor(17.6046, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1661, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5946, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5846, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5598, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:21, 13.28it/s]

tensor(17.5749, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8737, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5655, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2549, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5564, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6973, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.35it/s]

tensor(17.5471, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1953, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5376, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7424, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5277, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3346, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:01<00:20, 13.40it/s]

tensor(17.5169, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9676, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5045, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6370, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4904, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3395, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:01<00:20, 13.48it/s]

tensor(17.4744, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0721, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4551, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4334, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6148, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:01<00:20, 13.45it/s]

tensor(17.4082, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4202, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3791, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2456, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3461, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0886, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:19, 13.52it/s]

tensor(17.3084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9483, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2659, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7094, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:02<00:19, 13.54it/s]

tensor(17.1670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6084, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4381, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:02<00:19, 13.58it/s]

tensor(16.9926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3677, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3043, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2494, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:02<00:19, 13.53it/s]

tensor(16.7971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2004, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1593, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1239, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.48it/s]

tensor(16.5695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0950, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0724, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0553, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:03<00:19, 13.47it/s]

tensor(16.3064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0436, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:18, 13.46it/s]

tensor(16.0015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:03<00:18, 13.46it/s]

tensor(15.6572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:03<00:18, 13.40it/s]

tensor(15.2814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1593, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:04<00:18, 13.48it/s]

tensor(14.9275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8305, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:18, 13.43it/s]

tensor(14.6692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5953, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0185, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:04<00:17, 13.46it/s]

tensor(14.4559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0185, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.43it/s]

tensor(14.2842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:05<00:17, 13.44it/s]

tensor(14.1689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0910, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:16, 13.48it/s]

tensor(14.0514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:05<00:16, 13.45it/s]

tensor(13.9356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8707, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:05<00:16, 13.47it/s]

tensor(13.8413, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:05<00:16, 13.49it/s]

tensor(13.7585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:16, 13.47it/s]

tensor(13.6728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6453, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:06<00:15, 13.43it/s]

tensor(13.5941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5482, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:15, 13.42it/s]

tensor(13.5262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4824, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:06<00:15, 13.47it/s]

tensor(13.4605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4176, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:15, 13.47it/s]

tensor(13.3971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3583, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:07<00:15, 13.43it/s]

tensor(13.3398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:14, 13.40it/s]

tensor(13.2872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([180,  83,  57, 143, 125, 109, 406,  49,  35, 326, 104, 148,  71, 103])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:06, 29.21it/s]
  1%|          | 10/1939 [00:00<00:39, 48.58it/s]
  1%|          | 17/1939 [00:00<00:34, 55.09it/s]
  1%|          | 24/1939 [00:00<00:33, 57.34it/s]
  2%|▏         | 30/1939 [00:00<00:33, 56.47it/s]
  2%|▏         | 37/1939 [00:00<00:32, 58.83it/s]
  2%|▏         | 43/1939 [00:01<01:43, 18.26it/s]
  3%|▎         | 49/1939 [00:01<01:46, 17.82it/s]
  3%|▎         | 53/1939 [00:02<02:07, 14.85it/s]
  3%|▎         | 56/1939 [00:02<02:33, 12.28it/s]
  3%|▎         | 59/1939 [00:03<02:57, 10.58it/s]
  3%|▎         | 61/1939 [00:03<02:44, 11.45it/s]
  3%|▎         | 66/1939 [00:03<02:34, 12.12it/s]
  4%|▎         | 69/1939 [00:03<02:15, 13.79it/s]
  4%|▎         | 71/1939 [00:04<03:39,  8.50it/s]
  4%|▍         | 73/1939 [00:04<03:57,  7.85it/s]
  4%|▍         | 75/1939 [00:04<03:30,  8.87it/s]
  4%|▍         | 78/1939 [00:05<03:28,  8.93it/s]
 33%|███▎      | 100/300 [00:18<00:14, 13.40it/s]
  4%|▍         | 81/1939 [00:06<05:40,  5.45it/s]
  4%|▍         | 82/1939 [00:06<06:24,  4.83it/s]
  4%|▍         | 84/1939 [00:06<06:25,  4.81it/s]
  4%|▍         | 86/1939 [00:07<05:53,  5.24it/s]
  4%|▍         | 87/1939 [00:07<06:35,  4.68it/s]
  5%|▍         | 90/1939 [00:07<04:14,  7.27it/s]
  5%|▍         | 94/1939 [00:07<03:35,  8.57it/s]
  5%|▍         | 96/1939 [00:08<03:48,  8.05it/s]
  5%|▌         | 98/1939 [00:08<03:23,  9.05it/s]
  5%|▌         | 100/1939 [00:08<03:09,  9.69it/s]
  5%|▌         | 102/1939 [00:08<03:06,  9.86it/s]
  5%|▌         | 105/1939 [00:09<03:02, 10.04it/s]
  6%|▌         | 107/1939 [00:09<03:40,  8.32it/s]
  6%|▌         | 109/1939 [00:09<03:08,  9.69it/s]
  6%|▌         | 111/1939 [00:09<03:24,  8.92it/s]
  6%|▌         | 114/1939 [00:10<03:46,  8.05it/s]
  6%|▌         | 115/1939 [00:10<03:46,  8.06it/s]
  6%|▌         | 117/1939 [00:10<03:52,  7.84it/s]
  6%|▌         | 118/1939 [00:10<03:50,  7.90it/s]
  6%|▌         | 120/1939 [00:10<03:33,  8.52it/s]
  6%|▌         | 121/1939 [00:11<04:08,  7.31it/s]
  6%|▋         | 123/1939 [00:11<03:17,  9.18it/s]
  6%|▋         | 125/1939 [00:11<02:44, 11.01it/s]
  7%|▋         | 127/1939 [00:11<02:49, 10.72it/s]
  7%|▋         | 129/1939 [00:11<03:04,  9.78it/s]
  7%|▋         | 131/1939 [00:11<02:41, 11.19it/s]
  7%|▋         | 133/1939 [00:12<03:33,  8.45it/s]
  7%|▋         | 135/1939 [00:12<03:27,  8.69it/s]
  7%|▋         | 137/1939 [00:12<02:59, 10.04it/s]
  7%|▋         | 139/1939 [00:12<03:27,  8.68it/s]
  7%|▋         | 141/1939 [00:13<03:13,  9.30it/s]
  7%|▋         | 143/1939 [00:13<03:20,  8.95it/s]
  7%|▋         | 145/1939 [00:13<03:37,  8.24it/s]
  8%|▊         | 146/1939 [00:13<03:51,  7.73it/s]
  8%|▊         | 149/1939 [00:14<03:41,  8.10it/s]
  8%|▊         | 151/1939 [00:14<03:21,  8.88it/s]
  8%|▊         | 153/1939 [00:14<03:00,  9.87it/s]
  8%|▊         | 155/1939 [00:14<02:35, 11.49it/s]
  8%|▊         | 157/1939 [00:14<03:07,  9.48it/s]
  8%|▊         | 159/1939 [00:15<04:34,  6.48it/s]
  8%|▊         | 160/1939 [00:15<04:57,  5.98it/s]
  8%|▊         | 161/1939 [00:15<04:53,  6.06it/s]
  8%|▊         | 162/1939 [00:16<05:05,  5.82it/s]
  8%|▊         | 163/1939 [00:16<05:21,  5.53it/s]
  8%|▊         | 164/1939 [00:16<05:23,  5.49it/s]
  9%|▊         | 165/1939 [00:16<05:26,  5.44it/s]
  9%|▊         | 167/1939 [00:16<03:50,  7.69it/s]
  9%|▉         | 170/1939 [00:16<02:30, 11.78it/s]
  9%|▉         | 177/1939 [00:16<01:13, 23.87it/s]
  9%|▉         | 183/1939 [00:17<00:56, 31.34it/s]
 10%|▉         | 187/1939 [00:17<01:29, 19.57it/s]
 10%|▉         | 190/1939 [00:17<01:23, 20.88it/s]
 10%|█         | 195/1939 [00:17<01:06, 26.03it/s]
 10%|█         | 199/1939 [00:17<01:18, 22.21it/s]
 10%|█         | 202/1939 [00:18<02:06, 13.75it/s]
 11%|█         | 205/1939 [00:18<02:29, 11.58it/s]
 11%|█         | 207/1939 [00:18<02:42, 10.66it/s]
 11%|█         | 210/1939 [00:19<02:31, 11.43it/s]
 11%|█         | 212/1939 [00:19<03:26,  8.37it/s]
 11%|█         | 214/1939 [00:19<03:28,  8.26it/s]
 11%|█         | 216/1939 [00:20<03:23,  8.47it/s]
 11%|█         | 218/1939 [00:20<04:03,  7.06it/s]
 11%|█▏        | 219/1939 [00:20<04:48,  5.96it/s]
 11%|█▏        | 220/1939 [00:21<05:44,  4.99it/s]
 11%|█▏        | 222/1939 [00:21<05:42,  5.01it/s]
 12%|█▏        | 224/1939 [00:22<05:45,  4.96it/s]
 12%|█▏        | 225/1939 [00:22<06:21,  4.49it/s]
 12%|█▏        | 227/1939 [00:22<04:45,  6.00it/s]
 12%|█▏        | 228/1939 [00:22<05:32,  5.14it/s]
 12%|█▏        | 229/1939 [00:23<06:17,  4.53it/s]
 12%|█▏        | 230/1939 [00:23<06:59,  4.07it/s]
 12%|█▏        | 232/1939 [00:23<04:46,  5.95it/s]
 12%|█▏        | 233/1939 [00:23<05:43,  4.97it/s]
 12%|█▏        | 234/1939 [00:24<06:24,  4.44it/s]
 12%|█▏        | 236/1939 [00:24<05:52,  4.83it/s]
 12%|█▏        | 237/1939 [00:24<06:40,  4.25it/s]
 12%|█▏        | 239/1939 [00:25<06:14,  4.54it/s]
 12%|█▏        | 240/1939 [00:25<06:59,  4.05it/s]
 12%|█▏        | 241/1939 [00:25<07:40,  3.69it/s]
 12%|█▏        | 242/1939 [00:26<08:04,  3.50it/s]
 13%|█▎        | 243/1939 [00:26<08:01,  3.52it/s]
 13%|█▎        | 244/1939 [00:26<07:38,  3.69it/s]
 13%|█▎        | 245/1939 [00:26<06:33,  4.30it/s]
 13%|█▎        | 246/1939 [00:27<06:19,  4.46it/s]
 13%|█▎        | 249/1939 [00:27<03:31,  7.98it/s]
 13%|█▎        | 251/1939 [00:27<03:50,  7.31it/s]
 13%|█▎        | 254/1939 [00:27<02:48, 10.00it/s]
 13%|█▎        | 257/1939 [00:27<02:47, 10.03it/s]
 13%|█▎        | 259/1939 [00:28<03:01,  9.26it/s]
 13%|█▎        | 261/1939 [00:28<02:58,  9.40it/s]
 14%|█▎        | 263/1939 [00:28<03:10,  8.80it/s]
 14%|█▎        | 264/1939 [00:29<04:10,  6.70it/s]
 14%|█▍        | 267/1939 [00:29<02:54,  9.56it/s]
 14%|█▍        | 269/1939 [00:29<03:03,  9.08it/s]
 14%|█▍        | 271/1939 [00:29<03:13,  8.60it/s]
 14%|█▍        | 273/1939 [00:29<03:28,  7.99it/s]
 14%|█▍        | 274/1939 [00:30<04:19,  6.41it/s]
 14%|█▍        | 277/1939 [00:30<02:59,  9.26it/s]
 14%|█▍        | 281/1939 [00:30<02:41, 10.24it/s]
 15%|█▍        | 283/1939 [00:30<02:22, 11.60it/s]
 15%|█▍        | 285/1939 [00:31<03:57,  6.97it/s]
 15%|█▍        | 287/1939 [00:31<04:07,  6.66it/s]
 15%|█▍        | 288/1939 [00:32<04:46,  5.76it/s]
 15%|█▌        | 291/1939 [00:32<03:19,  8.27it/s]
 15%|█▌        | 293/1939 [00:32<03:37,  7.57it/s]
 15%|█▌        | 296/1939 [00:32<03:33,  7.68it/s]
 15%|█▌        | 298/1939 [00:33<03:52,  7.07it/s]
 15%|█▌        | 300/1939 [00:33<04:07,  6.63it/s]
 16%|█▌        | 302/1939 [00:33<03:21,  8.11it/s]
 16%|█▌        | 304/1939 [00:34<04:49,  5.65it/s]
 16%|█▌        | 307/1939 [00:34<04:18,  6.32it/s]
 16%|█▌        | 309/1939 [00:34<03:33,  7.64it/s]
 16%|█▌        | 312/1939 [00:35<03:16,  8.30it/s]
 16%|█▌        | 315/1939 [00:35<03:21,  8.05it/s]
 16%|█▋        | 316/1939 [00:35<04:04,  6.63it/s]
 16%|█▋        | 317/1939 [00:36<04:54,  5.52it/s]
 16%|█▋        | 318/1939 [00:36<05:26,  4.96it/s]
 16%|█▋        | 319/1939 [00:36<06:15,  4.31it/s]
 17%|█▋        | 320/1939 [00:37<06:48,  3.96it/s]
 17%|█▋        | 321/1939 [00:37<07:16,  3.71it/s]
 17%|█▋        | 322/1939 [00:37<07:35,  3.55it/s]
 17%|█▋        | 324/1939 [00:37<05:01,  5.35it/s]
 17%|█▋        | 330/1939 [00:38<02:03, 13.04it/s]
 17%|█▋        | 336/1939 [00:38<01:18, 20.37it/s]
 18%|█▊        | 340/1939 [00:38<01:39, 16.07it/s]
 18%|█▊        | 343/1939 [00:38<01:29, 17.86it/s]
 18%|█▊        | 349/1939 [00:38<01:04, 24.80it/s]
 18%|█▊        | 353/1939 [00:39<01:57, 13.53it/s]
 18%|█▊        | 356/1939 [00:40<03:20,  7.89it/s]
 19%|█▊        | 359/1939 [00:40<02:47,  9.43it/s]
 19%|█▊        | 362/1939 [00:40<02:55,  8.98it/s]
 19%|█▉        | 364/1939 [00:41<03:21,  7.81it/s]
 19%|█▉        | 366/1939 [00:41<03:37,  7.22it/s]
 19%|█▉        | 368/1939 [00:42<04:38,  5.63it/s]
 19%|█▉        | 370/1939 [00:42<04:42,  5.54it/s]
 19%|█▉        | 372/1939 [00:42<04:42,  5.54it/s]
 19%|█▉        | 373/1939 [00:43<05:12,  5.02it/s]
 19%|█▉        | 376/1939 [00:43<04:25,  5.89it/s]
 19%|█▉        | 377/1939 [00:43<04:28,  5.81it/s]
 19%|█▉        | 378/1939 [00:44<05:07,  5.08it/s]
 20%|█▉        | 381/1939 [00:44<04:18,  6.04it/s]
 20%|█▉        | 384/1939 [00:44<03:48,  6.82it/s]
 20%|█▉        | 385/1939 [00:45<04:27,  5.80it/s]
 20%|█▉        | 387/1939 [00:45<04:31,  5.71it/s]
 20%|██        | 388/1939 [00:45<05:08,  5.03it/s]
 20%|██        | 389/1939 [00:46<05:53,  4.39it/s]
 20%|██        | 390/1939 [00:46<06:51,  3.76it/s]
 20%|██        | 391/1939 [00:46<06:07,  4.21it/s]
 20%|██        | 392/1939 [00:46<05:16,  4.89it/s]
 20%|██        | 393/1939 [00:46<05:44,  4.49it/s]
 20%|██        | 394/1939 [00:47<05:04,  5.07it/s]
 20%|██        | 395/1939 [00:47<05:09,  4.99it/s]
 20%|██        | 396/1939 [00:47<04:57,  5.19it/s]
 21%|██        | 398/1939 [00:47<04:50,  5.30it/s]
 21%|██        | 400/1939 [00:48<03:42,  6.92it/s]
 21%|██        | 404/1939 [00:48<02:18, 11.08it/s]
 21%|██        | 406/1939 [00:48<02:36,  9.80it/s]
 21%|██        | 408/1939 [00:48<03:10,  8.05it/s]
 21%|██        | 410/1939 [00:48<02:43,  9.36it/s]
 21%|██        | 412/1939 [00:49<03:12,  7.94it/s]
 21%|██▏       | 414/1939 [00:49<02:39,  9.56it/s]
 21%|██▏       | 416/1939 [00:49<03:48,  6.68it/s]
 22%|██▏       | 417/1939 [00:50<04:04,  6.23it/s]
 22%|██▏       | 419/1939 [00:50<03:24,  7.42it/s]
 22%|██▏       | 421/1939 [00:50<02:45,  9.16it/s]
 22%|██▏       | 423/1939 [00:50<03:12,  7.87it/s]
 22%|██▏       | 426/1939 [00:51<02:53,  8.74it/s]
 22%|██▏       | 428/1939 [00:51<02:58,  8.44it/s]
 22%|██▏       | 430/1939 [00:51<02:43,  9.26it/s]
 22%|██▏       | 432/1939 [00:51<02:53,  8.71it/s]
 22%|██▏       | 435/1939 [00:51<02:08, 11.72it/s]
 23%|██▎       | 437/1939 [00:51<01:57, 12.81it/s]
 23%|██▎       | 443/1939 [00:52<01:08, 21.77it/s]
 23%|██▎       | 449/1939 [00:52<00:50, 29.77it/s]
 23%|██▎       | 453/1939 [00:52<01:13, 20.21it/s]
 24%|██▎       | 456/1939 [00:52<01:09, 21.40it/s]
 24%|██▍       | 463/1939 [00:52<00:48, 30.20it/s]
 24%|██▍       | 469/1939 [00:52<00:42, 34.27it/s]
 25%|██▍       | 476/1939 [00:53<00:53, 27.39it/s]
 25%|██▍       | 480/1939 [00:53<00:56, 25.93it/s]
 25%|██▌       | 486/1939 [00:53<00:45, 31.80it/s]
 25%|██▌       | 490/1939 [00:54<01:33, 15.53it/s]
 25%|██▌       | 493/1939 [00:54<01:57, 12.34it/s]
 26%|██▌       | 496/1939 [00:55<02:30,  9.62it/s]
 26%|██▌       | 498/1939 [00:55<02:16, 10.55it/s]
 26%|██▌       | 500/1939 [00:55<02:30,  9.59it/s]
 26%|██▌       | 503/1939 [00:55<02:00, 11.93it/s]
 26%|██▋       | 510/1939 [00:55<01:10, 20.40it/s]
 27%|██▋       | 514/1939 [00:56<01:25, 16.66it/s]
 27%|██▋       | 517/1939 [00:56<01:19, 17.79it/s]
 27%|██▋       | 522/1939 [00:56<01:01, 23.10it/s]
 27%|██▋       | 526/1939 [00:56<01:04, 21.99it/s]
 27%|██▋       | 532/1939 [00:56<00:50, 28.10it/s]
 28%|██▊       | 537/1939 [00:57<01:07, 20.73it/s]
 28%|██▊       | 540/1939 [00:57<01:35, 14.71it/s]
 28%|██▊       | 543/1939 [00:57<01:25, 16.25it/s]
 28%|██▊       | 546/1939 [00:57<01:41, 13.68it/s]
 28%|██▊       | 548/1939 [00:58<02:09, 10.77it/s]
 28%|██▊       | 550/1939 [00:58<01:59, 11.63it/s]
 28%|██▊       | 552/1939 [00:58<03:09,  7.31it/s]
 29%|██▊       | 555/1939 [00:59<02:25,  9.49it/s]
 29%|██▊       | 557/1939 [00:59<02:46,  8.31it/s]
 29%|██▉       | 559/1939 [00:59<03:06,  7.42it/s]
 29%|██▉       | 561/1939 [01:00<03:22,  6.81it/s]
 29%|██▉       | 562/1939 [01:00<04:04,  5.63it/s]
 29%|██▉       | 564/1939 [01:00<03:09,  7.26it/s]
 29%|██▉       | 567/1939 [01:00<02:57,  7.74it/s]
 29%|██▉       | 569/1939 [01:01<03:16,  6.96it/s]
 29%|██▉       | 571/1939 [01:01<03:32,  6.45it/s]
 29%|██▉       | 572/1939 [01:01<04:10,  5.46it/s]
 30%|██▉       | 574/1939 [01:02<04:10,  5.46it/s]
 30%|██▉       | 575/1939 [01:02<04:35,  4.95it/s]
 30%|██▉       | 576/1939 [01:02<05:05,  4.46it/s]
 30%|██▉       | 578/1939 [01:03<03:43,  6.10it/s]
 30%|██▉       | 579/1939 [01:03<04:26,  5.10it/s]
 30%|██▉       | 580/1939 [01:03<04:56,  4.59it/s]
 30%|███       | 582/1939 [01:04<04:40,  4.83it/s]
 30%|███       | 584/1939 [01:04<04:21,  5.17it/s]
 30%|███       | 586/1939 [01:04<04:24,  5.11it/s]
 30%|███       | 588/1939 [01:04<03:25,  6.59it/s]
 30%|███       | 589/1939 [01:05<04:04,  5.53it/s]
 30%|███       | 590/1939 [01:05<03:51,  5.82it/s]
 30%|███       | 591/1939 [01:05<04:01,  5.58it/s]
 31%|███       | 592/1939 [01:05<04:03,  5.52it/s]
 31%|███       | 593/1939 [01:05<04:06,  5.45it/s]
 31%|███       | 595/1939 [01:06<04:13,  5.30it/s]
 31%|███       | 596/1939 [01:06<04:18,  5.20it/s]
 31%|███       | 598/1939 [01:06<03:39,  6.10it/s]
 31%|███       | 599/1939 [01:06<03:55,  5.70it/s]
 31%|███       | 600/1939 [01:07<04:59,  4.48it/s]
 31%|███       | 601/1939 [01:07<04:43,  4.72it/s]
 31%|███       | 603/1939 [01:07<04:05,  5.44it/s]
 31%|███       | 605/1939 [01:08<03:43,  5.96it/s]
 31%|███▏      | 607/1939 [01:08<03:04,  7.20it/s]
 31%|███▏      | 608/1939 [01:08<03:48,  5.83it/s]
 31%|███▏      | 609/1939 [01:08<04:11,  5.29it/s]
 32%|███▏      | 611/1939 [01:09<04:10,  5.30it/s]
 32%|███▏      | 612/1939 [01:09<04:02,  5.46it/s]
 32%|███▏      | 613/1939 [01:09<04:02,  5.46it/s]
 32%|███▏      | 614/1939 [01:09<04:13,  5.23it/s]
 32%|███▏      | 615/1939 [01:09<04:16,  5.16it/s]
 32%|███▏      | 616/1939 [01:10<04:48,  4.58it/s]
 32%|███▏      | 617/1939 [01:10<05:26,  4.05it/s]
 32%|███▏      | 618/1939 [01:10<05:34,  3.95it/s]
 32%|███▏      | 619/1939 [01:11<05:34,  3.95it/s]
 32%|███▏      | 620/1939 [01:11<05:40,  3.87it/s]
 32%|███▏      | 621/1939 [01:11<05:45,  3.81it/s]
 32%|███▏      | 623/1939 [01:11<03:44,  5.86it/s]
 32%|███▏      | 629/1939 [01:12<02:11,  9.96it/s]
 32%|███▏      | 630/1939 [01:12<02:23,  9.12it/s]
 33%|███▎      | 632/1939 [01:12<02:31,  8.64it/s]
 33%|███▎      | 634/1939 [01:12<02:06, 10.28it/s]
 33%|███▎      | 636/1939 [01:13<02:40,  8.09it/s]
 33%|███▎      | 637/1939 [01:13<03:00,  7.19it/s]
 33%|███▎      | 640/1939 [01:13<02:27,  8.80it/s]
 33%|███▎      | 641/1939 [01:13<02:37,  8.26it/s]
 33%|███▎      | 643/1939 [01:13<02:30,  8.58it/s]
 33%|███▎      | 645/1939 [01:14<02:12,  9.73it/s]
 33%|███▎      | 647/1939 [01:14<02:20,  9.20it/s]
 33%|███▎      | 649/1939 [01:14<02:40,  8.02it/s]
 34%|███▎      | 651/1939 [01:14<02:30,  8.56it/s]
 34%|███▎      | 653/1939 [01:14<02:06, 10.20it/s]
 34%|███▍      | 655/1939 [01:15<02:38,  8.12it/s]
 34%|███▍      | 656/1939 [01:15<03:20,  6.40it/s]
 34%|███▍      | 658/1939 [01:15<03:37,  5.88it/s]
 34%|███▍      | 660/1939 [01:16<02:52,  7.43it/s]
 34%|███▍      | 665/1939 [01:16<02:05, 10.18it/s]
 34%|███▍      | 667/1939 [01:16<02:05, 10.16it/s]
 35%|███▍      | 669/1939 [01:16<02:14,  9.43it/s]
 35%|███▍      | 672/1939 [01:17<02:18,  9.17it/s]
 35%|███▍      | 673/1939 [01:17<02:38,  8.01it/s]
 35%|███▍      | 675/1939 [01:17<02:13,  9.45it/s]
 35%|███▍      | 677/1939 [01:18<03:34,  5.89it/s]
 35%|███▍      | 678/1939 [01:18<03:40,  5.71it/s]
 35%|███▌      | 680/1939 [01:18<03:35,  5.84it/s]
 35%|███▌      | 683/1939 [01:19<02:53,  7.26it/s]
 35%|███▌      | 686/1939 [01:19<02:06,  9.92it/s]
 35%|███▌      | 688/1939 [01:19<02:37,  7.96it/s]
 36%|███▌      | 690/1939 [01:19<02:36,  7.96it/s]
 36%|███▌      | 692/1939 [01:20<03:00,  6.91it/s]
 36%|███▌      | 696/1939 [01:20<01:55, 10.78it/s]
 36%|███▌      | 702/1939 [01:20<01:11, 17.33it/s]
 37%|███▋      | 708/1939 [01:20<00:50, 24.37it/s]
 37%|███▋      | 713/1939 [01:20<00:44, 27.58it/s]
 37%|███▋      | 717/1939 [01:20<00:41, 29.74it/s]
 37%|███▋      | 721/1939 [01:20<00:39, 30.78it/s]
 37%|███▋      | 725/1939 [01:21<00:46, 25.91it/s]
 38%|███▊      | 729/1939 [01:21<00:52, 22.89it/s]
 38%|███▊      | 732/1939 [01:21<01:31, 13.21it/s]
 38%|███▊      | 735/1939 [01:22<02:04,  9.65it/s]
 38%|███▊      | 737/1939 [01:22<01:53, 10.55it/s]
 38%|███▊      | 739/1939 [01:22<02:19,  8.62it/s]
 38%|███▊      | 741/1939 [01:23<02:00,  9.95it/s]
 38%|███▊      | 743/1939 [01:23<02:11,  9.11it/s]
 38%|███▊      | 745/1939 [01:23<02:08,  9.26it/s]
 39%|███▊      | 747/1939 [01:23<01:56, 10.23it/s]
 39%|███▊      | 749/1939 [01:23<01:53, 10.49it/s]
 39%|███▊      | 751/1939 [01:24<02:37,  7.53it/s]
 39%|███▉      | 752/1939 [01:24<03:14,  6.09it/s]
 39%|███▉      | 755/1939 [01:24<02:52,  6.88it/s]
 39%|███▉      | 756/1939 [01:25<03:19,  5.94it/s]
 39%|███▉      | 757/1939 [01:25<03:52,  5.09it/s]
 39%|███▉      | 759/1939 [01:25<02:50,  6.90it/s]
 39%|███▉      | 760/1939 [01:25<03:24,  5.75it/s]
 39%|███▉      | 761/1939 [01:26<04:04,  4.82it/s]
 39%|███▉      | 763/1939 [01:26<04:10,  4.70it/s]
 39%|███▉      | 764/1939 [01:26<04:30,  4.34it/s]
 40%|███▉      | 766/1939 [01:27<04:15,  4.60it/s]
 40%|███▉      | 767/1939 [01:27<04:40,  4.18it/s]
 40%|███▉      | 768/1939 [01:28<05:05,  3.83it/s]
 40%|███▉      | 769/1939 [01:28<05:34,  3.50it/s]
 40%|███▉      | 770/1939 [01:28<05:54,  3.30it/s]
 40%|███▉      | 771/1939 [01:28<04:55,  3.95it/s]
 40%|███▉      | 772/1939 [01:29<04:23,  4.44it/s]
 40%|███▉      | 774/1939 [01:29<03:11,  6.07it/s]
 40%|████      | 776/1939 [01:29<02:51,  6.78it/s]
 40%|████      | 777/1939 [01:29<02:48,  6.91it/s]
 40%|████      | 778/1939 [01:29<02:39,  7.30it/s]
 40%|████      | 779/1939 [01:30<03:35,  5.38it/s]
 40%|████      | 780/1939 [01:30<04:01,  4.80it/s]
 40%|████      | 781/1939 [01:30<04:34,  4.21it/s]
 40%|████      | 783/1939 [01:30<03:06,  6.19it/s]
 40%|████      | 784/1939 [01:31<03:46,  5.11it/s]
 40%|████      | 785/1939 [01:31<04:12,  4.57it/s]
 41%|████      | 787/1939 [01:31<03:48,  5.05it/s]
 41%|████      | 789/1939 [01:32<03:38,  5.26it/s]
 41%|████      | 791/1939 [01:32<03:30,  5.45it/s]
 41%|████      | 794/1939 [01:32<03:05,  6.17it/s]
 41%|████      | 795/1939 [01:33<03:34,  5.34it/s]
 41%|████      | 796/1939 [01:33<04:01,  4.73it/s]
 41%|████      | 798/1939 [01:33<03:46,  5.04it/s]
 41%|████▏     | 800/1939 [01:34<03:32,  5.36it/s]
 41%|████▏     | 801/1939 [01:34<04:02,  4.70it/s]
 41%|████▏     | 803/1939 [01:34<03:49,  4.95it/s]
 41%|████▏     | 804/1939 [01:35<04:13,  4.47it/s]
 42%|████▏     | 805/1939 [01:35<04:13,  4.47it/s]
 42%|████▏     | 806/1939 [01:35<04:48,  3.92it/s]
 42%|████▏     | 808/1939 [01:35<03:54,  4.83it/s]
 42%|████▏     | 809/1939 [01:36<04:15,  4.42it/s]
 42%|████▏     | 810/1939 [01:36<04:31,  4.16it/s]
 42%|████▏     | 812/1939 [01:36<04:02,  4.65it/s]
 42%|████▏     | 813/1939 [01:37<04:28,  4.19it/s]
 42%|████▏     | 814/1939 [01:37<04:53,  3.83it/s]
 42%|████▏     | 816/1939 [01:37<04:23,  4.26it/s]
 42%|████▏     | 817/1939 [01:38<04:46,  3.92it/s]
 42%|████▏     | 818/1939 [01:38<04:57,  3.77it/s]
 42%|████▏     | 819/1939 [01:38<04:39,  4.01it/s]
 42%|████▏     | 821/1939 [01:39<04:11,  4.44it/s]
 42%|████▏     | 822/1939 [01:39<03:58,  4.68it/s]
 42%|████▏     | 823/1939 [01:39<03:35,  5.18it/s]
 43%|████▎     | 825/1939 [01:39<02:55,  6.36it/s]
 43%|████▎     | 826/1939 [01:39<03:15,  5.70it/s]
 43%|████▎     | 828/1939 [01:40<02:46,  6.67it/s]
 43%|████▎     | 829/1939 [01:40<02:51,  6.48it/s]
 43%|████▎     | 830/1939 [01:40<02:37,  7.06it/s]
 43%|████▎     | 834/1939 [01:40<02:13,  8.27it/s]
 43%|████▎     | 836/1939 [01:40<01:51,  9.92it/s]
 43%|████▎     | 839/1939 [01:41<02:03,  8.88it/s]
 43%|████▎     | 842/1939 [01:41<01:34, 11.64it/s]
 44%|████▎     | 844/1939 [01:41<01:45, 10.40it/s]
 44%|████▎     | 846/1939 [01:41<01:53,  9.62it/s]
 44%|████▎     | 848/1939 [01:41<01:40, 10.82it/s]
 44%|████▍     | 850/1939 [01:42<02:01,  8.95it/s]
 44%|████▍     | 852/1939 [01:42<02:10,  8.34it/s]
 44%|████▍     | 854/1939 [01:42<02:03,  8.78it/s]
 44%|████▍     | 855/1939 [01:42<02:15,  8.00it/s]
 44%|████▍     | 857/1939 [01:43<02:31,  7.15it/s]
 44%|████▍     | 859/1939 [01:43<02:28,  7.26it/s]
 44%|████▍     | 860/1939 [01:43<02:36,  6.87it/s]
 44%|████▍     | 861/1939 [01:43<02:44,  6.54it/s]
 44%|████▍     | 862/1939 [01:44<02:51,  6.27it/s]
 45%|████▍     | 863/1939 [01:44<02:55,  6.14it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 311.43it/s]
 34%|███▎      | 101/300 [03:59<2:15:47, 40.94s/it]

[[np.int64(0), False, 9], [np.int64(1), False, 5], [np.int64(2), False, 3], [np.int64(3), False, 13], [np.int64(4), False, 6], [np.int64(6), False, 9], [np.int64(7), False, 13], [np.int64(8), False, 11], [np.int64(10), False, 0], [np.int64(11), False, 6], [np.int64(12), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.2704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1882, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.2614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3742, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [03:59<1:47:59, 32.72s/it]

tensor(13.2780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5949, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:59<1:07:58, 20.81s/it]

tensor(13.3250, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8314, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0245, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1294, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [03:59<44:19, 13.71s/it]

tensor(13.4785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1911, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [03:59<29:32,  9.23s/it]

tensor(13.4860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2453, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2842, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3331, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [04:00<19:59,  6.31s/it]

tensor(13.3844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3711, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4029, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [04:00<13:40,  4.36s/it]

tensor(13.2920, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4289, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [04:00<09:26,  3.04s/it]

tensor(13.2604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4579, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5209, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5603, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [04:00<06:33,  2.14s/it]

tensor(13.1710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6149, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1576, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6722, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [04:00<04:35,  1.52s/it]

tensor(13.1548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7242, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:00<03:15,  1.09s/it]

tensor(13.1539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7675, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1488, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7972, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8387, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:01<02:19,  1.27it/s]

tensor(13.1225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8757, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9033, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [04:01<01:41,  1.73it/s]

tensor(13.0820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9342, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [04:01<01:15,  2.31it/s]

tensor(13.0618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9620, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9873, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0282, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0211, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [04:01<00:56,  3.03it/s]

tensor(13.0124, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0372, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0592, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [04:01<00:44,  3.86it/s]

tensor(12.9734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0787, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:02<00:35,  4.77it/s]

tensor(12.9540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0957, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1163, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1345, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [04:02<00:29,  5.71it/s]

tensor(12.9074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1523, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1681, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:02<00:24,  6.62it/s]

tensor(12.8753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1837, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [04:02<00:21,  7.45it/s]

tensor(12.8595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2086, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2260, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2411, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [04:02<00:19,  8.12it/s]

tensor(12.8203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2609, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2814, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [04:03<00:18,  8.75it/s]

tensor(12.7953, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3039, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [04:03<00:17,  9.11it/s]

tensor(12.7837, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7725, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3428, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3571, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [04:03<00:16,  9.50it/s]

tensor(12.7485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3681, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7362, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3736, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [04:03<00:15,  9.80it/s]

tensor(12.7253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3832, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:03<00:14, 10.02it/s]

tensor(12.7153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3919, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([124, 277,  84, 205,  67, 125,  56, 116, 121,  32, 335,  80, 139, 178])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:30, 21.31it/s]
  0%|          | 6/1939 [00:00<01:41, 19.12it/s]
  1%|          | 10/1939 [00:00<01:24, 22.85it/s]
  1%|          | 15/1939 [00:00<01:04, 29.99it/s]
  1%|          | 20/1939 [00:00<00:54, 35.51it/s]
  1%|▏         | 25/1939 [00:00<00:49, 38.71it/s]
  2%|▏         | 30/1939 [00:00<00:52, 36.30it/s]
  2%|▏         | 34/1939 [00:01<00:51, 36.66it/s]
  2%|▏         | 40/1939 [00:01<00:44, 42.40it/s]
  2%|▏         | 45/1939 [00:01<02:08, 14.78it/s]
  3%|▎         | 49/1939 [00:02<02:42, 11.65it/s]
  3%|▎         | 52/1939 [00:02<02:23, 13.19it/s]
  3%|▎         | 55/1939 [00:02<02:34, 12.18it/s]
  3%|▎         | 58/1939 [00:03<02:36, 12.04it/s]
  3%|▎         | 60/1939 [00:03<02:28, 12.67it/s]
  3%|▎         | 64/1939 [00:03<01:54, 16.42it/s]
  3%|▎         | 67/1939 [00:03<02:03, 15.15it/s]
  4%|▎         | 70/1939 [00:03<01:50, 16.96it/s]
  4%|▍         | 73/1939 [00:04<02:24, 12.93it/s]
  4%|▍         | 76/1939 [00:04<02:04, 14.95it/s]
  4%|▍         | 78/1939 [00:04<02:16, 13.63it/s]
  4%|▍         | 80/1939 [00:04<03:03, 10.15it/s]
  4%|▍         | 82/1939 [00:05<04:04,  7.60it/s]
  4%|▍         | 84/1939 [00:05<04:05,  7.57it/s]
  4%|▍         | 86/1939 [00:05<04:11,  7.37it/s]
  4%|▍         | 87/1939 [00:06<04:15,  7.26it/s]
  5%|▍         | 89/1939 [00:06<03:24,  9.04it/s]
  5%|▍         | 91/1939 [00:06<02:53, 10.67it/s]
  5%|▍         | 94/1939 [00:06<02:28, 12.42it/s]
  5%|▍         | 96/1939 [00:06<03:53,  7.88it/s]
  5%|▌         | 98/1939 [00:07<03:24,  9.02it/s]
  5%|▌         | 100/1939 [00:07<03:53,  7.86it/s]
  5%|▌         | 102/1939 [00:07<03:14,  9.45it/s]
  5%|▌         | 105/1939 [00:07<03:27,  8.83it/s]
  6%|▌         | 107/1939 [00:08<03:06,  9.83it/s]
  6%|▌         | 109/1939 [00:08<02:40, 11.43it/s]
  6%|▌         | 111/1939 [00:08<04:07,  7.37it/s]
  6%|▌         | 113/1939 [00:08<03:23,  8.99it/s]
  6%|▌         | 115/1939 [00:09<04:23,  6.93it/s]
  6%|▌         | 118/1939 [00:09<03:49,  7.95it/s]
 50%|█████     | 150/300 [04:18<00:14, 10.02it/s]]
  6%|▌         | 121/1939 [00:10<05:34,  5.43it/s]
  6%|▋         | 123/1939 [00:10<04:30,  6.70it/s]
  6%|▋         | 126/1939 [00:10<04:44,  6.36it/s]
  7%|▋         | 128/1939 [00:11<04:43,  6.40it/s]
  7%|▋         | 130/1939 [00:11<03:49,  7.90it/s]
  7%|▋         | 132/1939 [00:11<03:38,  8.25it/s]
  7%|▋         | 135/1939 [00:12<04:21,  6.90it/s]
  7%|▋         | 137/1939 [00:12<04:08,  7.26it/s]
  7%|▋         | 139/1939 [00:12<03:24,  8.79it/s]
  7%|▋         | 142/1939 [00:12<03:59,  7.52it/s]
  7%|▋         | 144/1939 [00:13<04:54,  6.10it/s]
  7%|▋         | 145/1939 [00:13<05:12,  5.74it/s]
  8%|▊         | 146/1939 [00:14<06:35,  4.53it/s]
  8%|▊         | 148/1939 [00:14<04:58,  6.01it/s]
  8%|▊         | 153/1939 [00:14<03:04,  9.70it/s]
  8%|▊         | 155/1939 [00:14<02:43, 10.93it/s]
  8%|▊         | 157/1939 [00:14<03:44,  7.94it/s]
  8%|▊         | 159/1939 [00:15<05:45,  5.16it/s]
  8%|▊         | 160/1939 [00:15<05:48,  5.11it/s]
  8%|▊         | 161/1939 [00:16<07:05,  4.18it/s]
  8%|▊         | 162/1939 [00:16<06:50,  4.33it/s]
  8%|▊         | 163/1939 [00:16<06:46,  4.37it/s]
  8%|▊         | 164/1939 [00:16<06:18,  4.69it/s]
  9%|▊         | 165/1939 [00:17<06:33,  4.50it/s]
  9%|▊         | 167/1939 [00:17<04:31,  6.52it/s]
  9%|▊         | 169/1939 [00:17<03:24,  8.67it/s]
  9%|▉         | 175/1939 [00:17<01:36, 18.22it/s]
  9%|▉         | 182/1939 [00:17<01:01, 28.57it/s]
 10%|▉         | 188/1939 [00:17<00:53, 32.71it/s]
 10%|█         | 194/1939 [00:17<00:46, 37.28it/s]
 10%|█         | 199/1939 [00:18<00:44, 39.28it/s]
 11%|█         | 204/1939 [00:18<01:07, 25.52it/s]
 11%|█         | 208/1939 [00:18<01:41, 17.01it/s]
 11%|█         | 211/1939 [00:19<02:23, 12.07it/s]
 11%|█         | 214/1939 [00:19<02:09, 13.37it/s]
 11%|█         | 217/1939 [00:19<02:30, 11.44it/s]
 11%|█▏        | 219/1939 [00:20<04:04,  7.04it/s]
 11%|█▏        | 221/1939 [00:21<04:35,  6.23it/s]
 12%|█▏        | 223/1939 [00:21<04:53,  5.85it/s]
 12%|█▏        | 225/1939 [00:21<04:38,  6.16it/s]
 12%|█▏        | 227/1939 [00:21<03:47,  7.52it/s]
 12%|█▏        | 229/1939 [00:22<04:54,  5.81it/s]
 12%|█▏        | 230/1939 [00:22<05:20,  5.33it/s]
 12%|█▏        | 232/1939 [00:22<04:08,  6.86it/s]
 12%|█▏        | 234/1939 [00:23<04:10,  6.82it/s]
 12%|█▏        | 236/1939 [00:23<03:54,  7.27it/s]
 12%|█▏        | 237/1939 [00:23<04:06,  6.92it/s]
 12%|█▏        | 239/1939 [00:23<04:52,  5.81it/s]
 12%|█▏        | 240/1939 [00:24<04:41,  6.04it/s]
 12%|█▏        | 241/1939 [00:24<06:21,  4.45it/s]
 12%|█▏        | 242/1939 [00:24<06:16,  4.51it/s]
 13%|█▎        | 243/1939 [00:25<07:48,  3.62it/s]
 13%|█▎        | 244/1939 [00:25<07:12,  3.92it/s]
 13%|█▎        | 245/1939 [00:25<06:30,  4.33it/s]
 13%|█▎        | 246/1939 [00:25<06:29,  4.35it/s]
 13%|█▎        | 247/1939 [00:25<06:06,  4.61it/s]
 13%|█▎        | 248/1939 [00:26<05:56,  4.74it/s]
 13%|█▎        | 250/1939 [00:26<03:55,  7.17it/s]
 13%|█▎        | 256/1939 [00:26<01:39, 17.00it/s]
 13%|█▎        | 259/1939 [00:26<01:42, 16.40it/s]
 14%|█▎        | 262/1939 [00:26<01:49, 15.36it/s]
 14%|█▎        | 264/1939 [00:27<04:10,  6.67it/s]
 14%|█▎        | 266/1939 [00:27<03:31,  7.92it/s]
 14%|█▍        | 271/1939 [00:27<02:07, 13.05it/s]
 14%|█▍        | 276/1939 [00:27<01:31, 18.12it/s]
 14%|█▍        | 280/1939 [00:28<01:39, 16.70it/s]
 15%|█▍        | 283/1939 [00:28<02:28, 11.15it/s]
 15%|█▍        | 285/1939 [00:29<03:48,  7.25it/s]
 15%|█▍        | 287/1939 [00:29<03:20,  8.23it/s]
 15%|█▍        | 289/1939 [00:30<04:13,  6.50it/s]
 15%|█▌        | 292/1939 [00:30<03:08,  8.73it/s]
 15%|█▌        | 294/1939 [00:30<04:02,  6.77it/s]
 15%|█▌        | 296/1939 [00:31<04:36,  5.94it/s]
 15%|█▌        | 298/1939 [00:31<03:51,  7.08it/s]
 15%|█▌        | 300/1939 [00:31<03:15,  8.39it/s]
 16%|█▌        | 306/1939 [00:31<01:45, 15.42it/s]
 16%|█▌        | 309/1939 [00:32<02:33, 10.59it/s]
 16%|█▌        | 313/1939 [00:32<01:56, 14.02it/s]
 16%|█▋        | 316/1939 [00:32<02:36, 10.35it/s]
 16%|█▋        | 318/1939 [00:32<02:23, 11.29it/s]
 17%|█▋        | 321/1939 [00:33<02:42,  9.94it/s]
 17%|█▋        | 323/1939 [00:33<03:22,  7.99it/s]
 17%|█▋        | 327/1939 [00:33<02:19, 11.57it/s]
 17%|█▋        | 333/1939 [00:33<01:30, 17.80it/s]
 17%|█▋        | 337/1939 [00:33<01:16, 20.89it/s]
 18%|█▊        | 343/1939 [00:34<00:58, 27.48it/s]
 18%|█▊        | 348/1939 [00:34<00:50, 31.23it/s]
 18%|█▊        | 352/1939 [00:34<01:19, 19.99it/s]
 18%|█▊        | 356/1939 [00:35<03:03,  8.63it/s]
 19%|█▊        | 360/1939 [00:36<03:08,  8.36it/s]
 19%|█▊        | 363/1939 [00:36<03:02,  8.62it/s]
 19%|█▉        | 365/1939 [00:36<02:46,  9.47it/s]
 19%|█▉        | 367/1939 [00:37<03:39,  7.18it/s]
 19%|█▉        | 369/1939 [00:37<03:41,  7.07it/s]
 19%|█▉        | 371/1939 [00:38<04:53,  5.34it/s]
 19%|█▉        | 373/1939 [00:38<05:14,  4.98it/s]
 19%|█▉        | 375/1939 [00:39<05:39,  4.61it/s]
 19%|█▉        | 376/1939 [00:39<05:35,  4.66it/s]
 19%|█▉        | 377/1939 [00:39<06:49,  3.82it/s]
 20%|█▉        | 379/1939 [00:39<05:04,  5.13it/s]
 20%|█▉        | 381/1939 [00:40<04:12,  6.17it/s]
 20%|█▉        | 383/1939 [00:40<03:23,  7.65it/s]
 20%|█▉        | 385/1939 [00:40<04:57,  5.23it/s]
 20%|█▉        | 387/1939 [00:41<05:13,  4.95it/s]
 20%|██        | 388/1939 [00:41<05:19,  4.85it/s]
 20%|██        | 390/1939 [00:41<04:37,  5.57it/s]
 20%|██        | 391/1939 [00:42<06:11,  4.16it/s]
 20%|██        | 393/1939 [00:42<06:19,  4.08it/s]
 20%|██        | 394/1939 [00:43<06:37,  3.88it/s]
 20%|██        | 395/1939 [00:43<07:33,  3.41it/s]
 20%|██        | 396/1939 [00:43<07:06,  3.62it/s]
 21%|██        | 398/1939 [00:44<05:32,  4.64it/s]
 21%|██        | 400/1939 [00:44<04:00,  6.40it/s]
 21%|██        | 404/1939 [00:44<02:41,  9.53it/s]
 21%|██        | 406/1939 [00:44<02:51,  8.92it/s]
 21%|██        | 408/1939 [00:45<03:20,  7.62it/s]
 21%|██        | 410/1939 [00:45<02:48,  9.10it/s]
 21%|██        | 412/1939 [00:45<03:16,  7.79it/s]
 21%|██▏       | 415/1939 [00:45<03:01,  8.39it/s]
 22%|██▏       | 417/1939 [00:46<03:24,  7.45it/s]
 22%|██▏       | 419/1939 [00:46<03:15,  7.79it/s]
 22%|██▏       | 421/1939 [00:46<02:46,  9.13it/s]
 22%|██▏       | 423/1939 [00:46<03:06,  8.14it/s]
 22%|██▏       | 426/1939 [00:47<02:41,  9.35it/s]
 22%|██▏       | 428/1939 [00:47<02:43,  9.25it/s]
 22%|██▏       | 431/1939 [00:47<02:07, 11.82it/s]
 23%|██▎       | 438/1939 [00:47<01:09, 21.66it/s]
 23%|██▎       | 442/1939 [00:47<01:01, 24.44it/s]
 23%|██▎       | 447/1939 [00:47<00:50, 29.36it/s]
 23%|██▎       | 452/1939 [00:47<00:44, 33.59it/s]
 24%|██▎       | 456/1939 [00:48<01:37, 15.20it/s]
 24%|██▍       | 461/1939 [00:48<01:14, 19.77it/s]
 24%|██▍       | 467/1939 [00:48<00:57, 25.56it/s]
 24%|██▍       | 473/1939 [00:48<00:46, 31.48it/s]
 25%|██▍       | 479/1939 [00:48<00:42, 34.37it/s]
 25%|██▍       | 484/1939 [00:49<00:40, 36.14it/s]
 25%|██▌       | 489/1939 [00:49<00:48, 30.18it/s]
 25%|██▌       | 493/1939 [00:49<01:16, 18.82it/s]
 26%|██▌       | 497/1939 [00:49<01:07, 21.43it/s]
 26%|██▌       | 503/1939 [00:49<00:52, 27.56it/s]
 26%|██▌       | 508/1939 [00:50<00:44, 31.80it/s]
 26%|██▋       | 513/1939 [00:50<00:41, 34.13it/s]
 27%|██▋       | 518/1939 [00:50<00:50, 28.21it/s]
 27%|██▋       | 524/1939 [00:50<00:43, 32.86it/s]
 27%|██▋       | 528/1939 [00:50<00:41, 34.21it/s]
 27%|██▋       | 533/1939 [00:50<00:38, 37.00it/s]
 28%|██▊       | 538/1939 [00:51<00:56, 24.99it/s]
 28%|██▊       | 542/1939 [00:51<00:50, 27.47it/s]
 28%|██▊       | 546/1939 [00:51<00:57, 24.23it/s]
 28%|██▊       | 549/1939 [00:51<01:11, 19.42it/s]
 28%|██▊       | 552/1939 [00:52<01:39, 13.90it/s]
 29%|██▊       | 556/1939 [00:52<01:19, 17.29it/s]
 29%|██▉       | 562/1939 [00:52<00:57, 24.08it/s]
 29%|██▉       | 568/1939 [00:52<00:45, 30.44it/s]
 30%|██▉       | 573/1939 [00:52<00:58, 23.38it/s]
 30%|██▉       | 577/1939 [00:53<01:45, 12.89it/s]
 30%|██▉       | 580/1939 [00:53<02:04, 10.92it/s]
 30%|███       | 582/1939 [00:54<01:59, 11.38it/s]
 30%|███       | 584/1939 [00:54<02:13, 10.19it/s]
 30%|███       | 586/1939 [00:54<02:17,  9.83it/s]
 30%|███       | 588/1939 [00:54<02:04, 10.82it/s]
 30%|███       | 590/1939 [00:55<02:35,  8.66it/s]
 31%|███       | 592/1939 [00:55<03:50,  5.83it/s]
 31%|███       | 593/1939 [00:55<04:18,  5.20it/s]
 31%|███       | 595/1939 [00:56<03:32,  6.32it/s]
 31%|███       | 596/1939 [00:56<03:47,  5.91it/s]
 31%|███       | 597/1939 [00:56<03:28,  6.45it/s]
 31%|███       | 598/1939 [00:56<03:42,  6.02it/s]
 31%|███       | 600/1939 [00:56<03:14,  6.90it/s]
 31%|███       | 601/1939 [00:57<03:06,  7.17it/s]
 31%|███       | 603/1939 [00:57<03:22,  6.61it/s]
 31%|███       | 605/1939 [00:57<03:51,  5.77it/s]
 31%|███▏      | 606/1939 [00:57<03:35,  6.18it/s]
 31%|███▏      | 607/1939 [00:58<04:12,  5.28it/s]
 31%|███▏      | 608/1939 [00:58<04:21,  5.09it/s]
 31%|███▏      | 609/1939 [00:58<06:08,  3.61it/s]
 32%|███▏      | 611/1939 [00:59<06:15,  3.53it/s]
 32%|███▏      | 612/1939 [00:59<05:52,  3.77it/s]
 32%|███▏      | 613/1939 [01:00<07:10,  3.08it/s]
 32%|███▏      | 614/1939 [01:00<06:26,  3.43it/s]
 32%|███▏      | 615/1939 [01:00<07:32,  2.93it/s]
 32%|███▏      | 616/1939 [01:01<06:42,  3.29it/s]
 32%|███▏      | 617/1939 [01:01<07:43,  2.85it/s]
 32%|███▏      | 618/1939 [01:01<06:45,  3.26it/s]
 32%|███▏      | 619/1939 [01:02<08:08,  2.70it/s]
 32%|███▏      | 620/1939 [01:02<07:08,  3.08it/s]
 32%|███▏      | 621/1939 [01:02<06:22,  3.45it/s]
 32%|███▏      | 622/1939 [01:02<05:38,  3.89it/s]
 32%|███▏      | 625/1939 [01:02<02:53,  7.57it/s]
 32%|███▏      | 629/1939 [01:03<02:15,  9.69it/s]
 33%|███▎      | 631/1939 [01:03<02:35,  8.42it/s]
 33%|███▎      | 633/1939 [01:03<02:22,  9.17it/s]
 33%|███▎      | 635/1939 [01:03<02:04, 10.49it/s]
 33%|███▎      | 637/1939 [01:04<04:00,  5.41it/s]
 33%|███▎      | 639/1939 [01:04<03:12,  6.74it/s]
 33%|███▎      | 641/1939 [01:05<03:40,  5.89it/s]
 33%|███▎      | 643/1939 [01:05<03:07,  6.91it/s]
 33%|███▎      | 646/1939 [01:05<02:15,  9.58it/s]
 33%|███▎      | 649/1939 [01:05<02:21,  9.14it/s]
 34%|███▎      | 651/1939 [01:06<02:33,  8.36it/s]
 34%|███▎      | 653/1939 [01:06<02:25,  8.85it/s]
 34%|███▍      | 655/1939 [01:06<02:22,  8.98it/s]
 34%|███▍      | 657/1939 [01:06<02:27,  8.69it/s]
 34%|███▍      | 658/1939 [01:07<02:49,  7.56it/s]
 34%|███▍      | 659/1939 [01:07<03:08,  6.80it/s]
 34%|███▍      | 661/1939 [01:07<02:32,  8.41it/s]
 34%|███▍      | 665/1939 [01:07<02:39,  7.97it/s]
 34%|███▍      | 666/1939 [01:08<02:54,  7.28it/s]
 34%|███▍      | 668/1939 [01:08<02:51,  7.41it/s]
 35%|███▍      | 671/1939 [01:08<02:03, 10.26it/s]
 35%|███▍      | 673/1939 [01:09<04:24,  4.79it/s]
 35%|███▍      | 675/1939 [01:09<03:28,  6.07it/s]
 35%|███▍      | 677/1939 [01:10<03:51,  5.45it/s]
 35%|███▌      | 679/1939 [01:10<03:02,  6.90it/s]
 35%|███▌      | 681/1939 [01:10<02:53,  7.25it/s]
 35%|███▌      | 683/1939 [01:10<02:50,  7.35it/s]
 35%|███▌      | 686/1939 [01:10<02:03, 10.13it/s]
 35%|███▌      | 688/1939 [01:11<03:25,  6.08it/s]
 36%|███▌      | 690/1939 [01:11<03:11,  6.52it/s]
 36%|███▌      | 692/1939 [01:12<03:01,  6.88it/s]
 36%|███▌      | 695/1939 [01:12<02:09,  9.64it/s]
 36%|███▌      | 699/1939 [01:12<01:28, 13.98it/s]
 36%|███▋      | 707/1939 [01:12<00:49, 25.02it/s]
 37%|███▋      | 714/1939 [01:12<00:37, 32.78it/s]
 37%|███▋      | 719/1939 [01:12<00:36, 33.79it/s]
 37%|███▋      | 724/1939 [01:12<00:39, 30.77it/s]
 38%|███▊      | 728/1939 [01:12<00:42, 28.46it/s]
 38%|███▊      | 732/1939 [01:13<01:27, 13.72it/s]
 38%|███▊      | 735/1939 [01:14<02:11,  9.17it/s]
 38%|███▊      | 737/1939 [01:14<01:58, 10.11it/s]
 38%|███▊      | 739/1939 [01:15<03:18,  6.03it/s]
 38%|███▊      | 742/1939 [01:15<02:55,  6.81it/s]
 38%|███▊      | 744/1939 [01:15<02:30,  7.95it/s]
 39%|███▊      | 747/1939 [01:16<02:14,  8.85it/s]
 39%|███▊      | 749/1939 [01:16<03:00,  6.58it/s]
 39%|███▊      | 751/1939 [01:16<02:34,  7.71it/s]
 39%|███▉      | 753/1939 [01:17<03:05,  6.41it/s]
 39%|███▉      | 755/1939 [01:17<02:54,  6.79it/s]
 39%|███▉      | 756/1939 [01:17<04:02,  4.87it/s]
 39%|███▉      | 757/1939 [01:18<03:54,  5.05it/s]
 39%|███▉      | 759/1939 [01:18<02:57,  6.65it/s]
 39%|███▉      | 760/1939 [01:18<02:55,  6.73it/s]
 39%|███▉      | 761/1939 [01:18<03:04,  6.39it/s]
 39%|███▉      | 763/1939 [01:18<02:32,  7.69it/s]
 39%|███▉      | 764/1939 [01:19<03:11,  6.15it/s]
 40%|███▉      | 766/1939 [01:19<03:02,  6.44it/s]
 40%|███▉      | 768/1939 [01:19<02:41,  7.27it/s]
 40%|███▉      | 769/1939 [01:19<02:34,  7.57it/s]
 40%|███▉      | 770/1939 [01:20<03:42,  5.25it/s]
 40%|███▉      | 771/1939 [01:20<04:44,  4.11it/s]
 40%|███▉      | 772/1939 [01:20<04:10,  4.67it/s]
 40%|███▉      | 773/1939 [01:20<04:13,  4.60it/s]
 40%|███▉      | 774/1939 [01:21<05:18,  3.65it/s]
 40%|████      | 776/1939 [01:21<03:47,  5.12it/s]
 40%|████      | 777/1939 [01:21<03:56,  4.92it/s]
 40%|████      | 779/1939 [01:21<03:24,  5.67it/s]
 40%|████      | 780/1939 [01:22<04:13,  4.57it/s]
 40%|████      | 781/1939 [01:22<04:09,  4.65it/s]
 40%|████      | 783/1939 [01:22<02:58,  6.49it/s]
 40%|████      | 784/1939 [01:22<03:12,  6.00it/s]
 40%|████      | 785/1939 [01:23<04:00,  4.80it/s]
 41%|████      | 787/1939 [01:23<03:14,  5.91it/s]
 41%|████      | 789/1939 [01:23<02:49,  6.80it/s]
 41%|████      | 791/1939 [01:24<03:34,  5.36it/s]
 41%|████      | 794/1939 [01:24<03:32,  5.40it/s]
 41%|████      | 795/1939 [01:25<04:21,  4.38it/s]
 41%|████      | 796/1939 [01:25<04:30,  4.23it/s]
 41%|████      | 798/1939 [01:25<03:36,  5.28it/s]
 41%|████▏     | 800/1939 [01:25<02:56,  6.47it/s]
 41%|████▏     | 801/1939 [01:26<03:19,  5.71it/s]
 41%|████▏     | 803/1939 [01:26<03:10,  5.95it/s]
 42%|████▏     | 805/1939 [01:26<03:24,  5.55it/s]
 42%|████▏     | 806/1939 [01:26<03:32,  5.33it/s]
 42%|████▏     | 808/1939 [01:27<04:28,  4.22it/s]
 42%|████▏     | 809/1939 [01:27<04:18,  4.38it/s]
 42%|████▏     | 810/1939 [01:28<04:12,  4.47it/s]
 42%|████▏     | 811/1939 [01:28<03:38,  5.15it/s]
 42%|████▏     | 812/1939 [01:28<03:50,  4.90it/s]
 42%|████▏     | 813/1939 [01:28<03:39,  5.14it/s]
 42%|████▏     | 814/1939 [01:28<03:43,  5.02it/s]
 42%|████▏     | 816/1939 [01:28<02:56,  6.37it/s]
 42%|████▏     | 818/1939 [01:29<03:19,  5.61it/s]
 42%|████▏     | 819/1939 [01:29<03:14,  5.77it/s]
 42%|████▏     | 820/1939 [01:29<03:18,  5.65it/s]
 42%|████▏     | 821/1939 [01:29<03:10,  5.86it/s]
 42%|████▏     | 822/1939 [01:30<04:20,  4.29it/s]
 42%|████▏     | 823/1939 [01:30<04:12,  4.41it/s]
 43%|████▎     | 825/1939 [01:30<03:21,  5.54it/s]
 43%|████▎     | 827/1939 [01:30<02:36,  7.09it/s]
 43%|████▎     | 829/1939 [01:31<03:19,  5.57it/s]
 43%|████▎     | 832/1939 [01:31<02:13,  8.27it/s]
 43%|████▎     | 834/1939 [01:31<02:48,  6.57it/s]
 43%|████▎     | 837/1939 [01:32<02:01,  9.05it/s]
 43%|████▎     | 841/1939 [01:32<01:23, 13.15it/s]
 44%|████▎     | 844/1939 [01:32<01:09, 15.65it/s]
 44%|████▎     | 847/1939 [01:32<01:50,  9.86it/s]
 44%|████▍     | 849/1939 [01:33<02:27,  7.40it/s]
 44%|████▍     | 851/1939 [01:33<02:11,  8.26it/s]
 44%|████▍     | 855/1939 [01:33<02:03,  8.78it/s]
 44%|████▍     | 857/1939 [01:34<02:12,  8.16it/s]
 44%|████▍     | 859/1939 [01:34<01:57,  9.20it/s]
 44%|████▍     | 861/1939 [01:34<02:29,  7.22it/s]
 45%|████▍     | 864/1939 [01:35<02:39,  6.75it/s]
 45%|████▍     | 866/1939 [01:35<02:12,  8.10it/s]
 45%|████▍     | 871/1939 [01:35<01:19, 13.36it/s]
 45%|████▌     | 876/1939 [01:35<00:57, 18.36it/s]
 45%|████▌     | 882/1939 [01:35<00:42, 25.04it/s]
 46%|████▌     | 889/1939 [01:35<00:31, 33.09it/s]
 46%|████▌     | 896/1939 [01:35<00:25, 40.20it/s]
 46%|████▋     | 901/1939 [01:36<00:33, 31.10it/s]
 47%|████▋     | 906/1939 [01:36<00:50, 20.63it/s]
 47%|████▋     | 910/1939 [01:37<01:08, 14.97it/s]
 47%|████▋     | 913/1939 [01:37<01:04, 15.89it/s]
 47%|████▋     | 918/1939 [01:37<00:59, 17.28it/s]
 47%|████▋     | 921/1939 [01:37<00:57, 17.79it/s]
 48%|████▊     | 927/1939 [01:37<00:52, 19.23it/s]
 48%|████▊     | 930/1939 [01:38<01:04, 15.61it/s]
 48%|████▊     | 932/1939 [01:38<01:17, 12.91it/s]
 48%|████▊     | 935/1939 [01:38<01:06, 15.19it/s]
 49%|████▊     | 942/1939 [01:38<00:41, 23.80it/s]
 49%|████▉     | 947/1939 [01:38<00:36, 27.49it/s]
 49%|████▉     | 952/1939 [01:39<00:31, 31.81it/s]
 49%|████▉     | 957/1939 [01:39<00:27, 35.86it/s]
 50%|████▉     | 964/1939 [01:39<00:22, 43.33it/s]
 50%|████▉     | 969/1939 [01:39<00:41, 23.55it/s]
 50%|█████     | 973/1939 [01:40<01:33, 10.31it/s]
 50%|█████     | 976/1939 [01:41<01:56,  8.23it/s]
 50%|█████     | 979/1939 [01:41<02:09,  7.40it/s]
 51%|█████     | 981/1939 [01:42<02:13,  7.20it/s]
 51%|█████     | 983/1939 [01:42<02:10,  7.31it/s]
 51%|█████     | 985/1939 [01:42<02:26,  6.49it/s]
 51%|█████     | 988/1939 [01:43<02:39,  5.97it/s]
 51%|█████     | 989/1939 [01:43<02:48,  5.64it/s]
 51%|█████     | 991/1939 [01:44<02:39,  5.93it/s]
 51%|█████     | 993/1939 [01:44<02:09,  7.31it/s]
 51%|█████▏    | 995/1939 [01:44<02:21,  6.68it/s]
 51%|█████▏    | 996/1939 [01:45<03:11,  4.92it/s]
 51%|█████▏    | 997/1939 [01:45<02:59,  5.24it/s]
 51%|█████▏    | 998/1939 [01:45<03:08,  5.00it/s]
 52%|█████▏    | 1000/1939 [01:45<02:23,  6.52it/s]
 52%|█████▏    | 1001/1939 [01:45<02:13,  7.01it/s]
 52%|█████▏    | 1002/1939 [01:46<03:07,  5.00it/s]
 52%|█████▏    | 1003/1939 [01:46<03:29,  4.47it/s]
 52%|█████▏    | 1005/1939 [01:46<02:27,  6.34it/s]
 52%|█████▏    | 1006/1939 [01:46<02:28,  6.27it/s]
 52%|█████▏    | 1007/1939 [01:46<02:52,  5.40it/s]
 52%|█████▏    | 1009/1939 [01:47<02:18,  6.69it/s]
 52%|█████▏    | 1010/1939 [01:47<02:13,  6.96it/s]
 52%|█████▏    | 1011/1939 [01:47<02:21,  6.54it/s]
 52%|█████▏    | 1012/1939 [01:47<02:23,  6.47it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 295.80it/s]
 50%|█████     | 151/300 [07:55<1:41:45, 40.98s/it]

[[np.int64(0), False, 5], [np.int64(1), False, 10], [np.int64(2), False, 0], [np.int64(3), False, 12], [np.int64(4), False, 0], [np.int64(6), False, 0], [np.int64(7), False, 12], [np.int64(8), False, 10], [np.int64(9), False, 11], [np.int64(11), False, 3], [np.int64(13), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.7052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6480, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.6986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8349, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [07:55<1:20:47, 32.75s/it]

tensor(12.7038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0357, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [07:55<50:41, 20.83s/it]

tensor(12.7132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1249, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1809, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2173, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [07:56<32:55, 13.72s/it]

tensor(12.7106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2554, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2738, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [07:56<21:52,  9.24s/it]

tensor(12.7064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2953, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [07:56<14:44,  6.32s/it]

tensor(12.6989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3065, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3237, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6705, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3479, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [07:56<10:02,  4.37s/it]

tensor(12.6569, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3620, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6463, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3838, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [07:56<06:54,  3.05s/it]

tensor(12.6362, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4028, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [07:57<04:47,  2.14s/it]

tensor(12.6257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4224, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4318, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [07:57<03:20,  1.52s/it]

tensor(12.5968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4366, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4402, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [07:57<02:21,  1.09s/it]

tensor(12.5839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4463, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [07:57<01:40,  1.27it/s]

tensor(12.5773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5703, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4536, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4563, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [07:57<01:13,  1.72it/s]

tensor(12.5580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4577, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5527, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4579, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [07:57<00:53,  2.31it/s]

tensor(12.5473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4582, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [07:58<00:40,  3.02it/s]

tensor(12.5417, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4619, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4621, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4644, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [07:58<00:31,  3.85it/s]

tensor(12.5268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4653, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4708, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [07:58<00:24,  4.76it/s]

tensor(12.5187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4731, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [07:58<00:20,  5.71it/s]

tensor(12.5146, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4718, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4723, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4739, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [07:58<00:17,  6.58it/s]

tensor(12.5016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4750, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4761, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [07:59<00:15,  7.44it/s]

tensor(12.4942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4793, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [07:59<00:13,  8.11it/s]

tensor(12.4908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4751, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4875, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4739, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [07:59<00:12,  8.57it/s]

tensor(12.4840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4806, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4774, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4804, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [07:59<00:11,  9.10it/s]

tensor(12.4739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4828, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4820, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [07:59<00:10,  9.54it/s]

tensor(12.4677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4821, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [08:00<00:10,  9.85it/s]

tensor(12.4648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4845, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4857, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4869, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:00<00:09, 10.11it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([157, 216,  30,  92, 174, 126, 194,  83,  70, 115, 109, 396,  22, 155])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:15, 25.68it/s]
  1%|          | 10/1939 [00:00<00:39, 49.16it/s]
  1%|          | 18/1939 [00:00<00:31, 60.99it/s]
  1%|▏         | 25/1939 [00:00<00:32, 58.87it/s]
  2%|▏         | 31/1939 [00:00<00:40, 47.06it/s]
  2%|▏         | 37/1939 [00:00<00:46, 41.08it/s]
  2%|▏         | 42/1939 [00:01<01:17, 24.50it/s]
  2%|▏         | 46/1939 [00:01<01:14, 25.42it/s]
  3%|▎         | 50/1939 [00:01<01:29, 21.18it/s]
  3%|▎         | 56/1939 [00:01<01:10, 26.77it/s]
  3%|▎         | 62/1939 [00:01<00:59, 31.40it/s]
  3%|▎         | 66/1939 [00:01<00:57, 32.80it/s]
  4%|▎         | 71/1939 [00:02<01:45, 17.77it/s]
  4%|▍         | 74/1939 [00:02<01:40, 18.63it/s]
  4%|▍         | 79/1939 [00:03<02:24, 12.90it/s]
  4%|▍         | 82/1939 [00:04<04:17,  7.21it/s]
  4%|▍         | 84/1939 [00:04<03:51,  8.02it/s]
  4%|▍         | 86/1939 [00:05<04:45,  6.49it/s]
  5%|▍         | 88/1939 [00:05<04:08,  7.44it/s]
  5%|▍         | 94/1939 [00:05<02:24, 12.74it/s]
  5%|▌         | 100/1939 [00:05<02:42, 11.30it/s]
  5%|▌         | 103/1939 [00:06<02:25, 12.66it/s]
  5%|▌         | 106/1939 [00:06<03:03,  9.98it/s]
  6%|▌         | 108/1939 [00:06<02:46, 10.97it/s]
  6%|▌         | 110/1939 [00:07<03:47,  8.06it/s]
  6%|▌         | 113/1939 [00:07<03:01, 10.09it/s]
  6%|▌         | 115/1939 [00:07<04:01,  7.57it/s]
  6%|▌         | 117/1939 [00:07<03:25,  8.88it/s]
  6%|▌         | 121/1939 [00:08<03:45,  8.06it/s]
  6%|▋         | 123/1939 [00:08<03:16,  9.26it/s]
  6%|▋         | 126/1939 [00:09<03:56,  7.66it/s]
  7%|▋         | 128/1939 [00:09<04:52,  6.19it/s]
  7%|▋         | 130/1939 [00:09<04:05,  7.36it/s]
  7%|▋         | 135/1939 [00:10<03:40,  8.18it/s]
  7%|▋         | 137/1939 [00:10<03:16,  9.17it/s]
  7%|▋         | 142/1939 [00:10<03:18,  9.03it/s]
  7%|▋         | 144/1939 [00:11<04:16,  6.99it/s]
  8%|▊         | 146/1939 [00:12<05:14,  5.70it/s]
  8%|▊         | 149/1939 [00:12<03:57,  7.55it/s]
  8%|▊         | 151/1939 [00:12<04:45,  6.26it/s]
  8%|▊         | 153/1939 [00:12<04:01,  7.39it/s]
  8%|▊         | 157/1939 [00:13<03:13,  9.19it/s]
  8%|▊         | 159/1939 [00:13<04:09,  7.12it/s]
  8%|▊         | 161/1939 [00:14<04:48,  6.15it/s]
  8%|▊         | 162/1939 [00:14<05:22,  5.51it/s]
  8%|▊         | 163/1939 [00:14<05:32,  5.34it/s]
  9%|▊         | 165/1939 [00:15<06:11,  4.77it/s]
  9%|▊         | 167/1939 [00:15<04:41,  6.30it/s]
  9%|▉         | 174/1939 [00:15<02:05, 14.04it/s]
  9%|▉         | 181/1939 [00:15<01:19, 22.08it/s]
 10%|▉         | 185/1939 [00:15<01:10, 24.99it/s]
 10%|▉         | 191/1939 [00:15<00:57, 30.26it/s]
 10%|█         | 195/1939 [00:15<00:56, 30.96it/s]
 67%|██████▋   | 200/300 [08:18<00:09, 10.11it/s]]
 11%|█         | 205/1939 [00:16<02:27, 11.77it/s]
 11%|█         | 209/1939 [00:17<02:53,  9.98it/s]
 11%|█         | 212/1939 [00:18<03:29,  8.25it/s]
 11%|█         | 215/1939 [00:18<03:58,  7.24it/s]
 11%|█         | 217/1939 [00:18<03:33,  8.08it/s]
 11%|█▏        | 219/1939 [00:19<05:47,  4.95it/s]
 11%|█▏        | 221/1939 [00:20<06:06,  4.68it/s]
 11%|█▏        | 222/1939 [00:20<07:31,  3.80it/s]
 12%|█▏        | 225/1939 [00:21<06:49,  4.19it/s]
 12%|█▏        | 228/1939 [00:21<04:51,  5.87it/s]
 12%|█▏        | 230/1939 [00:22<05:30,  5.17it/s]
 12%|█▏        | 233/1939 [00:22<05:22,  5.28it/s]
 12%|█▏        | 234/1939 [00:23<06:38,  4.28it/s]
 12%|█▏        | 236/1939 [00:23<05:12,  5.45it/s]
 12%|█▏        | 237/1939 [00:23<06:39,  4.26it/s]
 12%|█▏        | 239/1939 [00:24<06:57,  4.07it/s]
 12%|█▏        | 241/1939 [00:24<07:10,  3.94it/s]
 12%|█▏        | 242/1939 [00:25<08:34,  3.30it/s]
 13%|█▎        | 243/1939 [00:25<09:42,  2.91it/s]
 13%|█▎        | 245/1939 [00:26<08:58,  3.14it/s]
 13%|█▎        | 248/1939 [00:26<05:31,  5.10it/s]
 13%|█▎        | 253/1939 [00:26<02:57,  9.48it/s]
 13%|█▎        | 258/1939 [00:26<01:56, 14.38it/s]
 13%|█▎        | 261/1939 [00:27<02:42, 10.35it/s]
 14%|█▎        | 264/1939 [00:27<03:21,  8.30it/s]
 14%|█▍        | 267/1939 [00:27<02:42, 10.29it/s]
 14%|█▍        | 272/1939 [00:27<01:50, 15.07it/s]
 14%|█▍        | 275/1939 [00:28<01:43, 16.06it/s]
 14%|█▍        | 278/1939 [00:28<01:32, 18.04it/s]
 14%|█▍        | 281/1939 [00:28<01:47, 15.49it/s]
 15%|█▍        | 284/1939 [00:28<01:38, 16.85it/s]
 15%|█▍        | 287/1939 [00:29<02:48,  9.78it/s]
 15%|█▌        | 293/1939 [00:29<01:46, 15.51it/s]
 15%|█▌        | 296/1939 [00:29<02:32, 10.79it/s]
 15%|█▌        | 299/1939 [00:30<02:09, 12.67it/s]
 16%|█▌        | 306/1939 [00:30<01:20, 20.17it/s]
 16%|█▌        | 310/1939 [00:30<02:16, 11.91it/s]
 16%|█▌        | 315/1939 [00:31<02:16, 11.93it/s]
 16%|█▋        | 318/1939 [00:31<02:36, 10.36it/s]
 17%|█▋        | 321/1939 [00:32<02:50,  9.51it/s]
 17%|█▋        | 323/1939 [00:32<02:54,  9.24it/s]
 17%|█▋        | 325/1939 [00:32<02:36, 10.29it/s]
 17%|█▋        | 328/1939 [00:32<02:07, 12.67it/s]
 17%|█▋        | 334/1939 [00:32<01:20, 19.90it/s]
 18%|█▊        | 341/1939 [00:32<00:55, 28.97it/s]
 18%|█▊        | 347/1939 [00:32<00:45, 35.01it/s]
 18%|█▊        | 352/1939 [00:33<01:16, 20.74it/s]
 18%|█▊        | 356/1939 [00:34<02:50,  9.31it/s]
 19%|█▊        | 359/1939 [00:34<02:29, 10.55it/s]
 19%|█▉        | 366/1939 [00:34<01:37, 16.10it/s]
 19%|█▉        | 370/1939 [00:35<02:53,  9.02it/s]
 19%|█▉        | 373/1939 [00:36<03:19,  7.84it/s]
 19%|█▉        | 376/1939 [00:36<02:49,  9.23it/s]
 20%|█▉        | 379/1939 [00:37<03:23,  7.65it/s]
 20%|█▉        | 381/1939 [00:37<04:08,  6.27it/s]
 20%|█▉        | 383/1939 [00:37<03:35,  7.22it/s]
 20%|█▉        | 385/1939 [00:38<04:16,  6.05it/s]
 20%|█▉        | 387/1939 [00:38<04:52,  5.31it/s]
 20%|██        | 389/1939 [00:38<04:01,  6.43it/s]
 20%|██        | 391/1939 [00:39<05:09,  5.00it/s]
 20%|██        | 393/1939 [00:40<05:40,  4.54it/s]
 20%|██        | 394/1939 [00:40<05:32,  4.64it/s]
 20%|██        | 396/1939 [00:40<04:14,  6.07it/s]
 21%|██        | 398/1939 [00:40<05:07,  5.01it/s]
 21%|██        | 400/1939 [00:41<03:57,  6.47it/s]
 21%|██        | 405/1939 [00:41<03:15,  7.85it/s]
 21%|██        | 407/1939 [00:41<03:04,  8.30it/s]
 21%|██        | 410/1939 [00:41<02:23, 10.64it/s]
 21%|██        | 412/1939 [00:42<03:21,  7.60it/s]
 21%|██▏       | 415/1939 [00:42<03:46,  6.73it/s]
 22%|██▏       | 417/1939 [00:43<03:14,  7.84it/s]
 22%|██▏       | 422/1939 [00:43<01:57, 12.91it/s]
 22%|██▏       | 428/1939 [00:43<02:13, 11.35it/s]
 22%|██▏       | 430/1939 [00:43<02:03, 12.23it/s]
 23%|██▎       | 437/1939 [00:43<01:15, 19.82it/s]
 23%|██▎       | 443/1939 [00:44<00:58, 25.69it/s]
 23%|██▎       | 447/1939 [00:44<00:53, 28.12it/s]
 23%|██▎       | 453/1939 [00:44<01:25, 17.48it/s]
 24%|██▎       | 457/1939 [00:44<01:17, 19.07it/s]
 24%|██▍       | 463/1939 [00:45<00:58, 25.04it/s]
 24%|██▍       | 469/1939 [00:45<00:48, 30.23it/s]
 24%|██▍       | 475/1939 [00:45<00:40, 36.00it/s]
 25%|██▍       | 481/1939 [00:45<00:35, 40.61it/s]
 25%|██▌       | 487/1939 [00:45<00:32, 45.03it/s]
 25%|██▌       | 493/1939 [00:46<01:05, 22.04it/s]
 26%|██▌       | 498/1939 [00:46<00:59, 24.05it/s]
 26%|██▌       | 502/1939 [00:46<00:54, 26.21it/s]
 26%|██▌       | 506/1939 [00:46<00:54, 26.29it/s]
 26%|██▋       | 511/1939 [00:46<00:47, 30.06it/s]
 27%|██▋       | 517/1939 [00:46<00:39, 35.81it/s]
 27%|██▋       | 523/1939 [00:46<00:34, 41.01it/s]
 27%|██▋       | 528/1939 [00:46<00:34, 40.56it/s]
 27%|██▋       | 533/1939 [00:47<00:38, 36.65it/s]
 28%|██▊       | 538/1939 [00:47<01:13, 19.14it/s]
 28%|██▊       | 542/1939 [00:47<01:07, 20.62it/s]
 28%|██▊       | 548/1939 [00:47<00:52, 26.69it/s]
 28%|██▊       | 552/1939 [00:48<01:32, 14.98it/s]
 29%|██▊       | 555/1939 [00:48<01:30, 15.35it/s]
 29%|██▉       | 558/1939 [00:48<01:21, 17.02it/s]
 29%|██▉       | 563/1939 [00:48<01:04, 21.48it/s]
 29%|██▉       | 570/1939 [00:49<00:46, 29.29it/s]
 30%|██▉       | 574/1939 [00:49<01:30, 15.07it/s]
 30%|██▉       | 577/1939 [00:50<02:51,  7.96it/s]
 30%|██▉       | 580/1939 [00:51<04:03,  5.58it/s]
 30%|███       | 582/1939 [00:52<04:24,  5.13it/s]
 30%|███       | 584/1939 [00:52<05:02,  4.48it/s]
 30%|███       | 586/1939 [00:53<04:10,  5.40it/s]
 30%|███       | 589/1939 [00:53<03:46,  5.96it/s]
 30%|███       | 591/1939 [00:54<04:22,  5.14it/s]
 31%|███       | 592/1939 [00:54<04:57,  4.53it/s]
 31%|███       | 593/1939 [00:54<05:42,  3.93it/s]
 31%|███       | 595/1939 [00:54<04:17,  5.22it/s]
 31%|███       | 596/1939 [00:55<04:08,  5.40it/s]
 31%|███       | 598/1939 [00:55<04:54,  4.56it/s]
 31%|███       | 600/1939 [00:56<05:22,  4.16it/s]
 31%|███       | 601/1939 [00:56<05:41,  3.91it/s]
 31%|███       | 603/1939 [00:56<04:58,  4.48it/s]
 31%|███       | 605/1939 [00:57<05:08,  4.33it/s]
 31%|███▏      | 607/1939 [00:57<03:52,  5.73it/s]
 31%|███▏      | 608/1939 [00:57<04:31,  4.90it/s]
 31%|███▏      | 609/1939 [00:58<04:30,  4.92it/s]
 32%|███▏      | 611/1939 [00:58<04:21,  5.08it/s]
 32%|███▏      | 613/1939 [00:58<03:38,  6.06it/s]
 32%|███▏      | 615/1939 [00:58<03:05,  7.15it/s]
 32%|███▏      | 616/1939 [00:59<03:38,  6.07it/s]
 32%|███▏      | 617/1939 [00:59<04:03,  5.42it/s]
 32%|███▏      | 619/1939 [00:59<03:32,  6.20it/s]
 32%|███▏      | 620/1939 [00:59<04:43,  4.66it/s]
 32%|███▏      | 622/1939 [01:00<03:26,  6.38it/s]
 32%|███▏      | 625/1939 [01:00<02:22,  9.24it/s]
 32%|███▏      | 629/1939 [01:00<01:33, 13.97it/s]
 33%|███▎      | 631/1939 [01:00<02:34,  8.45it/s]
 33%|███▎      | 633/1939 [01:01<03:25,  6.35it/s]
 33%|███▎      | 636/1939 [01:01<03:42,  5.86it/s]
 33%|███▎      | 637/1939 [01:02<04:42,  4.61it/s]
 33%|███▎      | 639/1939 [01:02<03:38,  5.94it/s]
 33%|███▎      | 641/1939 [01:03<04:30,  4.80it/s]
 33%|███▎      | 643/1939 [01:03<04:16,  5.06it/s]
 33%|███▎      | 645/1939 [01:03<03:19,  6.48it/s]
 33%|███▎      | 647/1939 [01:03<02:41,  7.98it/s]
 33%|███▎      | 649/1939 [01:04<03:06,  6.91it/s]
 34%|███▎      | 651/1939 [01:04<02:34,  8.33it/s]
 34%|███▎      | 654/1939 [01:04<02:34,  8.30it/s]
 34%|███▍      | 656/1939 [01:04<02:27,  8.70it/s]
 34%|███▍      | 658/1939 [01:05<03:23,  6.28it/s]
 34%|███▍      | 660/1939 [01:05<02:48,  7.60it/s]
 34%|███▍      | 665/1939 [01:05<01:52, 11.29it/s]
 34%|███▍      | 667/1939 [01:06<02:12,  9.58it/s]
 35%|███▍      | 671/1939 [01:06<01:34, 13.41it/s]
 35%|███▍      | 673/1939 [01:06<02:51,  7.37it/s]
 35%|███▍      | 675/1939 [01:06<02:28,  8.50it/s]
 35%|███▍      | 677/1939 [01:07<02:35,  8.12it/s]
 35%|███▌      | 679/1939 [01:07<02:15,  9.30it/s]
 35%|███▌      | 681/1939 [01:07<02:45,  7.59it/s]
 35%|███▌      | 683/1939 [01:07<02:21,  8.86it/s]
 35%|███▌      | 687/1939 [01:08<01:49, 11.46it/s]
 36%|███▌      | 689/1939 [01:08<01:41, 12.26it/s]
 36%|███▌      | 693/1939 [01:08<01:15, 16.51it/s]
 36%|███▌      | 696/1939 [01:08<01:08, 18.17it/s]
 36%|███▌      | 699/1939 [01:08<01:03, 19.58it/s]
 36%|███▌      | 702/1939 [01:08<00:57, 21.40it/s]
 37%|███▋      | 709/1939 [01:08<00:38, 32.23it/s]
 37%|███▋      | 716/1939 [01:08<00:29, 41.11it/s]
 37%|███▋      | 723/1939 [01:09<00:25, 48.39it/s]
 38%|███▊      | 729/1939 [01:09<00:26, 45.72it/s]
 38%|███▊      | 734/1939 [01:09<00:53, 22.63it/s]
 38%|███▊      | 738/1939 [01:10<01:17, 15.42it/s]
 38%|███▊      | 741/1939 [01:10<01:26, 13.81it/s]
 38%|███▊      | 744/1939 [01:10<01:35, 12.54it/s]
 38%|███▊      | 746/1939 [01:10<01:30, 13.24it/s]
 39%|███▊      | 748/1939 [01:11<01:44, 11.40it/s]
 39%|███▊      | 750/1939 [01:11<01:42, 11.62it/s]
 39%|███▉      | 752/1939 [01:11<02:33,  7.71it/s]
 39%|███▉      | 754/1939 [01:12<02:11,  9.00it/s]
 39%|███▉      | 756/1939 [01:12<02:55,  6.74it/s]
 39%|███▉      | 758/1939 [01:13<03:39,  5.38it/s]
 39%|███▉      | 760/1939 [01:13<04:03,  4.85it/s]
 39%|███▉      | 763/1939 [01:13<02:51,  6.87it/s]
 39%|███▉      | 765/1939 [01:14<03:29,  5.60it/s]
 40%|███▉      | 766/1939 [01:14<04:29,  4.36it/s]
 40%|███▉      | 767/1939 [01:15<05:28,  3.57it/s]
 40%|███▉      | 768/1939 [01:15<05:20,  3.66it/s]
 40%|███▉      | 769/1939 [01:15<05:48,  3.36it/s]
 40%|███▉      | 770/1939 [01:16<06:25,  3.03it/s]
 40%|███▉      | 771/1939 [01:16<05:19,  3.66it/s]
 40%|███▉      | 772/1939 [01:16<05:16,  3.69it/s]
 40%|███▉      | 773/1939 [01:16<04:39,  4.18it/s]
 40%|███▉      | 775/1939 [01:17<03:04,  6.32it/s]
 40%|████      | 776/1939 [01:17<04:14,  4.56it/s]
 40%|████      | 778/1939 [01:17<02:59,  6.48it/s]
 40%|████      | 780/1939 [01:18<03:57,  4.89it/s]
 40%|████      | 781/1939 [01:18<03:49,  5.04it/s]
 40%|████      | 783/1939 [01:18<02:53,  6.67it/s]
 40%|████      | 784/1939 [01:18<04:18,  4.47it/s]
 40%|████      | 785/1939 [01:19<04:26,  4.32it/s]
 41%|████      | 787/1939 [01:19<03:44,  5.13it/s]
 41%|████      | 789/1939 [01:19<04:05,  4.69it/s]
 41%|████      | 791/1939 [01:20<03:44,  5.12it/s]
 41%|████      | 793/1939 [01:20<02:54,  6.59it/s]
 41%|████      | 795/1939 [01:21<03:59,  4.79it/s]
 41%|████      | 796/1939 [01:21<05:02,  3.77it/s]
 41%|████      | 798/1939 [01:22<05:05,  3.73it/s]
 41%|████▏     | 800/1939 [01:22<03:44,  5.08it/s]
 41%|████▏     | 801/1939 [01:22<04:51,  3.90it/s]
 41%|████▏     | 803/1939 [01:22<03:30,  5.40it/s]
 42%|████▏     | 805/1939 [01:23<04:00,  4.71it/s]
 42%|████▏     | 806/1939 [01:23<04:39,  4.06it/s]
 42%|████▏     | 807/1939 [01:23<04:05,  4.61it/s]
 42%|████▏     | 808/1939 [01:24<04:13,  4.45it/s]
 42%|████▏     | 809/1939 [01:24<04:01,  4.68it/s]
 42%|████▏     | 810/1939 [01:24<03:38,  5.17it/s]
 42%|████▏     | 812/1939 [01:24<02:43,  6.91it/s]
 42%|████▏     | 813/1939 [01:24<02:50,  6.59it/s]
 42%|████▏     | 814/1939 [01:25<03:02,  6.16it/s]
 42%|████▏     | 816/1939 [01:25<02:24,  7.75it/s]
 42%|████▏     | 818/1939 [01:25<03:13,  5.80it/s]
 42%|████▏     | 820/1939 [01:26<04:07,  4.52it/s]
 42%|████▏     | 821/1939 [01:26<04:19,  4.31it/s]
 42%|████▏     | 822/1939 [01:26<04:17,  4.34it/s]
 42%|████▏     | 824/1939 [01:26<03:12,  5.79it/s]
 43%|████▎     | 829/1939 [01:27<02:18,  8.00it/s]
 43%|████▎     | 831/1939 [01:27<02:00,  9.22it/s]
 43%|████▎     | 838/1939 [01:27<01:03, 17.44it/s]
 44%|████▎     | 844/1939 [01:27<00:46, 23.68it/s]
 44%|████▎     | 848/1939 [01:28<01:18, 13.85it/s]
 44%|████▍     | 851/1939 [01:28<01:53,  9.60it/s]
 44%|████▍     | 854/1939 [01:29<01:34, 11.44it/s]
 44%|████▍     | 857/1939 [01:30<02:46,  6.48it/s]
 44%|████▍     | 860/1939 [01:30<02:13,  8.09it/s]
 45%|████▍     | 864/1939 [01:30<02:18,  7.78it/s]
 45%|████▍     | 867/1939 [01:30<01:53,  9.46it/s]
 45%|████▌     | 874/1939 [01:31<01:06, 15.95it/s]
 45%|████▌     | 881/1939 [01:31<00:46, 22.92it/s]
 46%|████▌     | 887/1939 [01:31<00:36, 28.79it/s]
 46%|████▌     | 894/1939 [01:31<00:29, 35.84it/s]
 46%|████▋     | 900/1939 [01:31<00:25, 40.18it/s]
 47%|████▋     | 906/1939 [01:31<00:23, 44.14it/s]
 47%|████▋     | 912/1939 [01:32<01:13, 13.88it/s]
 47%|████▋     | 916/1939 [01:32<01:04, 15.76it/s]
 48%|████▊     | 923/1939 [01:32<00:47, 21.31it/s]
 48%|████▊     | 928/1939 [01:33<01:07, 15.05it/s]
 48%|████▊     | 932/1939 [01:33<00:57, 17.38it/s]
 48%|████▊     | 939/1939 [01:33<00:42, 23.79it/s]
 49%|████▊     | 945/1939 [01:33<00:34, 29.08it/s]
 49%|████▉     | 951/1939 [01:33<00:28, 34.19it/s]
 49%|████▉     | 958/1939 [01:34<00:23, 40.94it/s]
 50%|████▉     | 964/1939 [01:34<00:21, 44.51it/s]
 50%|█████     | 970/1939 [01:34<00:38, 25.49it/s]
 50%|█████     | 975/1939 [01:35<00:57, 16.63it/s]
 50%|█████     | 979/1939 [01:35<01:15, 12.74it/s]
 51%|█████     | 982/1939 [01:36<01:48,  8.82it/s]
 51%|█████     | 984/1939 [01:37<02:12,  7.21it/s]
 51%|█████     | 987/1939 [01:37<01:48,  8.77it/s]
 51%|█████     | 989/1939 [01:38<02:58,  5.32it/s]
 51%|█████     | 991/1939 [01:38<02:31,  6.24it/s]
 51%|█████▏    | 994/1939 [01:38<02:39,  5.93it/s]
 51%|█████▏    | 997/1939 [01:39<02:00,  7.82it/s]
 52%|█████▏    | 999/1939 [01:40<03:26,  4.55it/s]
 52%|█████▏    | 1002/1939 [01:40<03:17,  4.74it/s]
 52%|█████▏    | 1003/1939 [01:41<03:58,  3.93it/s]
 52%|█████▏    | 1006/1939 [01:41<02:44,  5.66it/s]
 52%|█████▏    | 1008/1939 [01:41<03:04,  5.03it/s]
 52%|█████▏    | 1009/1939 [01:42<03:48,  4.08it/s]
 52%|█████▏    | 1011/1939 [01:42<03:55,  3.94it/s]
 52%|█████▏    | 1013/1939 [01:43<04:00,  3.85it/s]
 52%|█████▏    | 1014/1939 [01:43<04:41,  3.29it/s]
 52%|█████▏    | 1015/1939 [01:44<05:22,  2.86it/s]
 53%|█████▎    | 1018/1939 [01:44<03:10,  4.83it/s]
 53%|█████▎    | 1019/1939 [01:45<03:55,  3.91it/s]
 53%|█████▎    | 1021/1939 [01:45<02:51,  5.35it/s]
 53%|█████▎    | 1027/1939 [01:45<02:01,  7.50it/s]
 53%|█████▎    | 1029/1939 [01:45<01:45,  8.63it/s]
 53%|█████▎    | 1031/1939 [01:46<02:16,  6.67it/s]
 53%|█████▎    | 1033/1939 [01:46<02:37,  5.75it/s]
 53%|█████▎    | 1035/1939 [01:46<02:07,  7.09it/s]
 54%|█████▎    | 1040/1939 [01:47<01:13, 12.19it/s]
 54%|█████▍    | 1045/1939 [01:47<01:24, 10.61it/s]
 54%|█████▍    | 1047/1939 [01:47<01:16, 11.59it/s]
 54%|█████▍    | 1049/1939 [01:48<01:50,  8.03it/s]
 54%|█████▍    | 1051/1939 [01:48<02:30,  5.90it/s]
 54%|█████▍    | 1053/1939 [01:49<02:54,  5.07it/s]
 54%|█████▍    | 1054/1939 [01:49<03:32,  4.16it/s]
 54%|█████▍    | 1056/1939 [01:50<03:41,  3.99it/s]
 55%|█████▍    | 1059/1939 [01:51<03:21,  4.37it/s]
 55%|█████▍    | 1060/1939 [01:51<04:05,  3.59it/s]
 55%|█████▍    | 1061/1939 [01:52<04:36,  3.17it/s]
 55%|█████▍    | 1064/1939 [01:52<03:47,  3.85it/s]
 55%|█████▌    | 1067/1939 [01:52<02:33,  5.68it/s]
 55%|█████▌    | 1068/1939 [01:53<03:22,  4.30it/s]
 55%|█████▌    | 1070/1939 [01:53<02:33,  5.65it/s]
 55%|█████▌    | 1072/1939 [01:54<04:04,  3.55it/s]
 55%|█████▌    | 1074/1939 [01:55<04:02,  3.56it/s]
 55%|█████▌    | 1076/1939 [01:55<03:06,  4.64it/s]
 56%|█████▌    | 1077/1939 [01:55<03:55,  3.65it/s]
 56%|█████▌    | 1079/1939 [01:55<02:53,  4.96it/s]
 56%|█████▌    | 1081/1939 [01:56<04:19,  3.31it/s]
 56%|█████▌    | 1083/1939 [01:56<03:13,  4.43it/s]
 56%|█████▌    | 1085/1939 [01:57<02:26,  5.81it/s]
 56%|█████▌    | 1088/1939 [01:57<02:19,  6.11it/s]
 56%|█████▌    | 1090/1939 [01:58<02:46,  5.09it/s]
 56%|█████▋    | 1091/1939 [01:58<03:26,  4.10it/s]
 56%|█████▋    | 1092/1939 [01:59<04:09,  3.39it/s]
 56%|█████▋    | 1094/1939 [01:59<03:58,  3.54it/s]
 57%|█████▋    | 1096/1939 [01:59<02:53,  4.87it/s]
 57%|█████▋    | 1097/1939 [02:00<03:41,  3.81it/s]
 57%|█████▋    | 1100/1939 [02:00<02:16,  6.14it/s]
 57%|█████▋    | 1102/1939 [02:00<02:47,  5.00it/s]
 57%|█████▋    | 1105/1939 [02:01<02:45,  5.05it/s]
 57%|█████▋    | 1106/1939 [02:02<03:27,  4.02it/s]
 57%|█████▋    | 1109/1939 [02:02<03:09,  4.37it/s]
 57%|█████▋    | 1110/1939 [02:03<03:44,  3.69it/s]
 57%|█████▋    | 1112/1939 [02:03<03:49,  3.61it/s]
 57%|█████▋    | 1114/1939 [02:04<03:48,  3.61it/s]
 58%|█████▊    | 1116/1939 [02:04<02:51,  4.80it/s]
 58%|█████▊    | 1120/1939 [02:04<02:21,  5.79it/s]
 58%|█████▊    | 1121/1939 [02:05<03:05,  4.41it/s]
 58%|█████▊    | 1123/1939 [02:06<03:31,  3.85it/s]
 58%|█████▊    | 1126/1939 [02:06<03:23,  4.00it/s]
 58%|█████▊    | 1128/1939 [02:07<03:28,  3.89it/s]
 58%|█████▊    | 1130/1939 [02:07<03:33,  3.79it/s]
 58%|█████▊    | 1132/1939 [02:08<02:47,  4.82it/s]
 59%|█████▊    | 1135/1939 [02:08<02:36,  5.13it/s]
 59%|█████▊    | 1137/1939 [02:08<02:05,  6.37it/s]
 59%|█████▊    | 1139/1939 [02:09<02:30,  5.31it/s]
 59%|█████▉    | 1141/1939 [02:09<02:12,  6.01it/s]
 59%|█████▉    | 1143/1939 [02:09<01:48,  7.32it/s]
 59%|█████▉    | 1145/1939 [02:10<02:23,  5.53it/s]
 59%|█████▉    | 1146/1939 [02:10<02:54,  4.55it/s]
 59%|█████▉    | 1147/1939 [02:11<03:32,  3.73it/s]
 59%|█████▉    | 1149/1939 [02:11<03:09,  4.17it/s]
 59%|█████▉    | 1150/1939 [02:11<03:42,  3.55it/s]
 59%|█████▉    | 1152/1939 [02:11<02:36,  5.03it/s]
 59%|█████▉    | 1153/1939 [02:12<03:05,  4.24it/s]
 60%|█████▉    | 1154/1939 [02:12<02:50,  4.60it/s]
 60%|█████▉    | 1155/1939 [02:12<02:44,  4.77it/s]
 60%|█████▉    | 1157/1939 [02:12<01:56,  6.69it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 302.64it/s]
 67%|██████▋   | 201/300 [11:39<1:03:51, 38.70s/it]

[[np.int64(0), False, 10], [np.int64(1), False, 11], [np.int64(2), False, 4], [np.int64(3), False, 13], [np.int64(4), False, 10], [np.int64(5), False, 10], [np.int64(6), False, 11], [np.int64(7), False, 4], [np.int64(8), False, 13], [np.int64(9), False, 11], [np.int64(12), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1771, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.4541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3581, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 202/300 [11:39<50:32, 30.94s/it]

tensor(12.4549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4846, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [11:39<29:12, 18.26s/it]

tensor(12.4566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5370, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5845, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [11:39<16:58, 10.83s/it]

tensor(12.4497, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6073, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [11:39<10:32,  6.87s/it]

tensor(12.4439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6231, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6319, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6328, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [11:40<06:48,  4.53s/it]

tensor(12.4337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6375, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6430, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [11:40<04:30,  3.07s/it]

tensor(12.4305, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6518, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [11:40<03:01,  2.12s/it]

tensor(12.4281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6559, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6662, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6692, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [11:40<02:04,  1.48s/it]

tensor(12.4170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6757, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6783, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [11:40<01:26,  1.05s/it]

tensor(12.4104, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6819, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [11:40<01:00,  1.32it/s]

tensor(12.4073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6870, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6889, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6901, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [11:41<00:43,  1.80it/s]

tensor(12.3989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3966, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6898, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [11:41<00:31,  2.41it/s]

tensor(12.3940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6909, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [11:41<00:23,  3.15it/s]

tensor(12.3912, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6913, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6904, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6918, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [11:41<00:17,  4.01it/s]

tensor(12.3834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6923, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6938, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [11:41<00:14,  4.95it/s]

tensor(12.3789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6950, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [11:42<00:11,  5.89it/s]

tensor(12.3767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6951, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6940, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6932, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [11:42<00:09,  6.80it/s]

tensor(12.3709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6904, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [11:42<00:08,  7.65it/s]

tensor(12.3674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6906, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [11:42<00:07,  8.37it/s]

tensor(12.3654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6901, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6896, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6899, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [11:42<00:06,  8.97it/s]

tensor(12.3600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6912, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6902, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [11:43<00:06,  9.44it/s]

tensor(12.3562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6893, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [11:43<00:05,  9.71it/s]

tensor(12.3545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6909, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6876, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3508, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6890, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [11:43<00:05,  9.88it/s]

tensor(12.3489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6898, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6880, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [11:43<00:05, 10.11it/s]

tensor(12.3456, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6871, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [11:43<00:04, 10.26it/s]

tensor(12.3438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6907, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([167, 339, 187, 121, 204, 116, 170,  87,  80, 160, 141,  21, 114,  32])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:24, 22.95it/s]
  1%|          | 10/1939 [00:00<00:43, 44.35it/s]
  1%|          | 15/1939 [00:00<00:45, 41.86it/s]
  1%|          | 21/1939 [00:00<00:43, 44.59it/s]
  1%|▏         | 27/1939 [00:00<00:39, 48.04it/s]
  2%|▏         | 32/1939 [00:00<00:44, 42.41it/s]
  2%|▏         | 38/1939 [00:00<00:41, 45.93it/s]
  2%|▏         | 43/1939 [00:00<00:44, 43.03it/s]
  3%|▎         | 49/1939 [00:01<01:21, 23.19it/s]
  3%|▎         | 53/1939 [00:01<01:34, 20.02it/s]
  3%|▎         | 56/1939 [00:01<01:37, 19.37it/s]
  3%|▎         | 59/1939 [00:02<01:32, 20.24it/s]
  3%|▎         | 67/1939 [00:02<01:01, 30.29it/s]
  4%|▎         | 71/1939 [00:02<01:37, 19.14it/s]
  4%|▍         | 74/1939 [00:02<01:39, 18.83it/s]
  4%|▍         | 79/1939 [00:02<01:28, 21.13it/s]
  4%|▍         | 82/1939 [00:03<02:42, 11.40it/s]
  4%|▍         | 84/1939 [00:04<03:29,  8.84it/s]
  4%|▍         | 86/1939 [00:04<04:07,  7.49it/s]
  5%|▍         | 88/1939 [00:04<04:39,  6.62it/s]
  5%|▍         | 92/1939 [00:05<03:10,  9.72it/s]
  5%|▍         | 94/1939 [00:05<03:57,  7.77it/s]
  5%|▍         | 96/1939 [00:05<03:26,  8.91it/s]
  5%|▌         | 100/1939 [00:06<03:26,  8.90it/s]
  5%|▌         | 103/1939 [00:06<02:46, 11.00it/s]
  6%|▌         | 110/1939 [00:06<02:26, 12.52it/s]
  6%|▌         | 113/1939 [00:06<02:08, 14.16it/s]
  6%|▌         | 115/1939 [00:07<02:53, 10.52it/s]
  6%|▌         | 117/1939 [00:07<02:38, 11.48it/s]
  6%|▌         | 120/1939 [00:07<02:11, 13.82it/s]
  6%|▋         | 123/1939 [00:07<01:52, 16.19it/s]
  6%|▋         | 126/1939 [00:08<02:32, 11.85it/s]
  7%|▋         | 128/1939 [00:08<02:24, 12.49it/s]
  7%|▋         | 131/1939 [00:08<02:01, 14.91it/s]
  7%|▋         | 137/1939 [00:08<01:19, 22.73it/s]
  7%|▋         | 140/1939 [00:08<01:22, 21.82it/s]
  7%|▋         | 143/1939 [00:08<02:15, 13.23it/s]
  8%|▊         | 146/1939 [00:09<02:55, 10.19it/s]
  8%|▊         | 148/1939 [00:09<02:39, 11.25it/s]
  8%|▊         | 152/1939 [00:09<01:57, 15.21it/s]
  8%|▊         | 157/1939 [00:09<01:25, 20.88it/s]
  8%|▊         | 162/1939 [00:10<01:57, 15.06it/s]
  9%|▊         | 165/1939 [00:10<02:53, 10.23it/s]
 83%|████████▎ | 250/300 [11:58<00:04, 10.26it/s]]
  9%|▉         | 170/1939 [00:11<03:02,  9.70it/s]
  9%|▉         | 173/1939 [00:11<02:31, 11.67it/s]
  9%|▉         | 178/1939 [00:11<01:45, 16.71it/s]
  9%|▉         | 183/1939 [00:11<01:20, 21.94it/s]
 10%|▉         | 187/1939 [00:11<01:16, 22.77it/s]
 10%|▉         | 192/1939 [00:12<01:03, 27.31it/s]
 10%|█         | 198/1939 [00:12<00:51, 33.91it/s]
 10%|█         | 203/1939 [00:12<01:26, 20.08it/s]
 11%|█         | 207/1939 [00:13<02:36, 11.05it/s]
 11%|█         | 210/1939 [00:13<02:43, 10.55it/s]
 11%|█         | 212/1939 [00:13<02:36, 11.06it/s]
 11%|█         | 215/1939 [00:14<02:58,  9.68it/s]
 11%|█         | 218/1939 [00:14<02:29, 11.52it/s]
 11%|█▏        | 220/1939 [00:15<04:25,  6.46it/s]
 11%|█▏        | 222/1939 [00:15<03:48,  7.53it/s]
 12%|█▏        | 225/1939 [00:15<03:53,  7.33it/s]
 12%|█▏        | 227/1939 [00:16<04:34,  6.23it/s]
 12%|█▏        | 229/1939 [00:16<05:15,  5.42it/s]
 12%|█▏        | 232/1939 [00:16<03:48,  7.46it/s]
 12%|█▏        | 234/1939 [00:17<05:43,  4.97it/s]
 12%|█▏        | 236/1939 [00:17<04:41,  6.04it/s]
 12%|█▏        | 238/1939 [00:18<04:38,  6.10it/s]
 12%|█▏        | 239/1939 [00:18<05:12,  5.44it/s]
 12%|█▏        | 241/1939 [00:18<05:31,  5.12it/s]
 12%|█▏        | 242/1939 [00:19<05:55,  4.77it/s]
 13%|█▎        | 243/1939 [00:19<05:57,  4.75it/s]
 13%|█▎        | 245/1939 [00:19<04:53,  5.76it/s]
 13%|█▎        | 247/1939 [00:19<04:47,  5.89it/s]
 13%|█▎        | 248/1939 [00:20<04:28,  6.29it/s]
 13%|█▎        | 251/1939 [00:20<02:53,  9.73it/s]
 13%|█▎        | 258/1939 [00:20<01:23, 20.19it/s]
 13%|█▎        | 261/1939 [00:20<02:18, 12.15it/s]
 14%|█▎        | 264/1939 [00:21<02:41, 10.35it/s]
 14%|█▎        | 266/1939 [00:21<02:30, 11.09it/s]
 14%|█▍        | 274/1939 [00:21<01:22, 20.26it/s]
 14%|█▍        | 280/1939 [00:21<01:03, 26.09it/s]
 15%|█▍        | 284/1939 [00:21<01:22, 19.94it/s]
 15%|█▍        | 287/1939 [00:22<01:50, 14.92it/s]
 15%|█▌        | 291/1939 [00:22<01:31, 18.06it/s]
 15%|█▌        | 298/1939 [00:22<01:02, 26.25it/s]
 16%|█▌        | 304/1939 [00:22<00:51, 32.04it/s]
 16%|█▌        | 309/1939 [00:23<01:27, 18.65it/s]
 16%|█▌        | 314/1939 [00:23<01:12, 22.44it/s]
 16%|█▋        | 318/1939 [00:23<01:51, 14.50it/s]
 17%|█▋        | 322/1939 [00:24<02:12, 12.18it/s]
 17%|█▋        | 325/1939 [00:24<01:59, 13.48it/s]
 17%|█▋        | 333/1939 [00:24<01:14, 21.56it/s]
 18%|█▊        | 341/1939 [00:24<00:53, 29.66it/s]
 18%|█▊        | 346/1939 [00:24<00:50, 31.66it/s]
 18%|█▊        | 351/1939 [00:25<01:21, 19.50it/s]
 18%|█▊        | 355/1939 [00:26<02:09, 12.22it/s]
 18%|█▊        | 358/1939 [00:26<02:32, 10.34it/s]
 19%|█▊        | 360/1939 [00:26<02:20, 11.20it/s]
 19%|█▉        | 366/1939 [00:26<01:35, 16.52it/s]
 19%|█▉        | 369/1939 [00:27<02:09, 12.08it/s]
 19%|█▉        | 372/1939 [00:27<02:01, 12.92it/s]
 19%|█▉        | 375/1939 [00:28<03:38,  7.15it/s]
 19%|█▉        | 377/1939 [00:29<05:03,  5.15it/s]
 20%|█▉        | 379/1939 [00:29<04:16,  6.08it/s]
 20%|█▉        | 381/1939 [00:29<04:55,  5.26it/s]
 20%|█▉        | 384/1939 [00:29<03:34,  7.23it/s]
 20%|█▉        | 387/1939 [00:30<03:16,  7.90it/s]
 20%|██        | 389/1939 [00:30<03:00,  8.57it/s]
 20%|██        | 391/1939 [00:30<03:19,  7.78it/s]
 20%|██        | 393/1939 [00:31<03:40,  7.00it/s]
 20%|██        | 394/1939 [00:31<03:50,  6.70it/s]
 20%|██        | 395/1939 [00:31<04:37,  5.56it/s]
 20%|██        | 396/1939 [00:31<05:22,  4.79it/s]
 21%|██        | 398/1939 [00:32<05:51,  4.38it/s]
 21%|██        | 400/1939 [00:32<04:26,  5.78it/s]
 21%|██        | 404/1939 [00:32<02:34,  9.92it/s]
 21%|██        | 406/1939 [00:33<03:35,  7.11it/s]
 21%|██        | 408/1939 [00:33<04:28,  5.71it/s]
 21%|██        | 411/1939 [00:34<04:24,  5.77it/s]
 21%|██▏       | 413/1939 [00:34<03:39,  6.97it/s]
 21%|██▏       | 415/1939 [00:34<04:03,  6.25it/s]
 22%|██▏       | 417/1939 [00:34<03:21,  7.54it/s]
 22%|██▏       | 419/1939 [00:35<03:49,  6.62it/s]
 22%|██▏       | 421/1939 [00:35<03:16,  7.71it/s]
 22%|██▏       | 423/1939 [00:35<02:50,  8.91it/s]
 22%|██▏       | 428/1939 [00:36<02:39,  9.47it/s]
 22%|██▏       | 430/1939 [00:36<02:21, 10.69it/s]
 22%|██▏       | 432/1939 [00:36<03:13,  7.77it/s]
 23%|██▎       | 437/1939 [00:36<01:57, 12.74it/s]
 23%|██▎       | 443/1939 [00:36<01:18, 19.13it/s]
 23%|██▎       | 448/1939 [00:36<01:02, 23.85it/s]
 23%|██▎       | 453/1939 [00:37<01:18, 18.96it/s]
 24%|██▎       | 456/1939 [00:37<01:16, 19.29it/s]
 24%|██▍       | 463/1939 [00:37<00:53, 27.42it/s]
 24%|██▍       | 470/1939 [00:37<00:41, 35.52it/s]
 24%|██▍       | 475/1939 [00:37<00:37, 38.53it/s]
 25%|██▍       | 480/1939 [00:37<00:35, 40.85it/s]
 25%|██▌       | 487/1939 [00:38<00:32, 44.73it/s]
 25%|██▌       | 492/1939 [00:38<00:35, 40.28it/s]
 26%|██▌       | 497/1939 [00:38<00:42, 34.00it/s]
 26%|██▌       | 504/1939 [00:38<00:34, 41.03it/s]
 26%|██▋       | 511/1939 [00:38<00:30, 46.48it/s]
 27%|██▋       | 517/1939 [00:38<00:29, 48.44it/s]
 27%|██▋       | 523/1939 [00:38<00:28, 49.96it/s]
 27%|██▋       | 530/1939 [00:38<00:25, 54.54it/s]
 28%|██▊       | 536/1939 [00:39<00:25, 54.66it/s]
 28%|██▊       | 542/1939 [00:39<00:44, 31.45it/s]
 28%|██▊       | 547/1939 [00:39<01:01, 22.78it/s]
 28%|██▊       | 551/1939 [00:40<01:27, 15.91it/s]
 29%|██▊       | 554/1939 [00:40<01:28, 15.66it/s]
 29%|██▉       | 560/1939 [00:40<01:05, 21.19it/s]
 29%|██▉       | 566/1939 [00:40<00:51, 26.72it/s]
 29%|██▉       | 571/1939 [00:41<01:11, 19.26it/s]
 30%|██▉       | 575/1939 [00:41<01:24, 16.16it/s]
 30%|██▉       | 578/1939 [00:41<01:46, 12.75it/s]
 30%|██▉       | 580/1939 [00:42<02:02, 11.09it/s]
 30%|███       | 582/1939 [00:42<02:06, 10.69it/s]
 30%|███       | 584/1939 [00:42<02:16,  9.95it/s]
 30%|███       | 586/1939 [00:42<02:08, 10.53it/s]
 30%|███       | 588/1939 [00:43<01:57, 11.54it/s]
 30%|███       | 590/1939 [00:43<02:28,  9.08it/s]
 31%|███       | 592/1939 [00:43<02:24,  9.32it/s]
 31%|███       | 594/1939 [00:43<02:13, 10.05it/s]
 31%|███       | 596/1939 [00:44<02:39,  8.44it/s]
 31%|███       | 598/1939 [00:44<03:06,  7.19it/s]
 31%|███       | 600/1939 [00:44<03:35,  6.21it/s]
 31%|███       | 601/1939 [00:45<04:33,  4.89it/s]
 31%|███       | 603/1939 [00:45<03:30,  6.36it/s]
 31%|███       | 605/1939 [00:45<04:00,  5.55it/s]
 31%|███▏      | 607/1939 [00:45<03:07,  7.12it/s]
 31%|███▏      | 609/1939 [00:46<03:38,  6.09it/s]
 32%|███▏      | 611/1939 [00:46<04:26,  4.98it/s]
 32%|███▏      | 614/1939 [00:47<03:02,  7.26it/s]
 32%|███▏      | 616/1939 [00:47<04:38,  4.75it/s]
 32%|███▏      | 617/1939 [00:48<05:14,  4.20it/s]
 32%|███▏      | 619/1939 [00:48<05:04,  4.33it/s]
 32%|███▏      | 620/1939 [00:48<05:02,  4.36it/s]
 32%|███▏      | 622/1939 [00:49<03:54,  5.62it/s]
 32%|███▏      | 624/1939 [00:49<03:00,  7.27it/s]
 32%|███▏      | 630/1939 [00:49<01:48, 12.02it/s]
 33%|███▎      | 633/1939 [00:49<01:33, 13.99it/s]
 33%|███▎      | 636/1939 [00:49<01:39, 13.16it/s]
 33%|███▎      | 638/1939 [00:50<02:07, 10.17it/s]
 33%|███▎      | 641/1939 [00:50<02:30,  8.61it/s]
 33%|███▎      | 643/1939 [00:50<02:20,  9.21it/s]
 33%|███▎      | 645/1939 [00:51<02:11,  9.82it/s]
 33%|███▎      | 647/1939 [00:51<01:54, 11.31it/s]
 33%|███▎      | 649/1939 [00:51<02:38,  8.15it/s]
 34%|███▎      | 651/1939 [00:51<02:15,  9.53it/s]
 34%|███▎      | 654/1939 [00:51<02:05, 10.25it/s]
 34%|███▍      | 656/1939 [00:52<02:04, 10.27it/s]
 34%|███▍      | 658/1939 [00:52<02:06, 10.16it/s]
 34%|███▍      | 660/1939 [00:52<01:57, 10.93it/s]
 34%|███▍      | 663/1939 [00:52<01:31, 13.96it/s]
 34%|███▍      | 665/1939 [00:52<01:59, 10.65it/s]
 34%|███▍      | 667/1939 [00:53<02:22,  8.95it/s]
 35%|███▍      | 672/1939 [00:53<01:49, 11.54it/s]
 35%|███▍      | 674/1939 [00:53<01:49, 11.53it/s]
 35%|███▍      | 676/1939 [00:53<01:51, 11.30it/s]
 35%|███▍      | 678/1939 [00:54<01:48, 11.57it/s]
 35%|███▌      | 680/1939 [00:54<02:34,  8.14it/s]
 35%|███▌      | 681/1939 [00:54<02:30,  8.36it/s]
 35%|███▌      | 687/1939 [00:54<01:39, 12.53it/s]
 36%|███▌      | 689/1939 [00:55<01:39, 12.62it/s]
 36%|███▌      | 692/1939 [00:55<01:51, 11.17it/s]
 36%|███▌      | 694/1939 [00:55<01:41, 12.26it/s]
 36%|███▌      | 696/1939 [00:55<01:33, 13.34it/s]
 36%|███▌      | 702/1939 [00:55<00:58, 21.07it/s]
 37%|███▋      | 708/1939 [00:55<00:43, 28.47it/s]
 37%|███▋      | 715/1939 [00:55<00:33, 36.69it/s]
 37%|███▋      | 721/1939 [00:56<00:30, 40.51it/s]
 38%|███▊      | 728/1939 [00:56<00:25, 47.34it/s]
 38%|███▊      | 734/1939 [00:57<01:15, 16.02it/s]
 38%|███▊      | 738/1939 [00:58<02:01,  9.88it/s]
 38%|███▊      | 741/1939 [00:58<02:20,  8.55it/s]
 38%|███▊      | 744/1939 [00:59<02:34,  7.73it/s]
 39%|███▊      | 747/1939 [00:59<02:42,  7.34it/s]
 39%|███▊      | 749/1939 [00:59<02:25,  8.20it/s]
 39%|███▉      | 752/1939 [01:00<02:40,  7.38it/s]
 39%|███▉      | 754/1939 [01:00<03:06,  6.35it/s]
 39%|███▉      | 756/1939 [01:01<03:29,  5.66it/s]
 39%|███▉      | 757/1939 [01:01<04:08,  4.75it/s]
 39%|███▉      | 759/1939 [01:01<03:14,  6.06it/s]
 39%|███▉      | 761/1939 [01:02<04:29,  4.37it/s]
 39%|███▉      | 763/1939 [01:02<03:28,  5.63it/s]
 39%|███▉      | 765/1939 [01:03<03:54,  5.01it/s]
 40%|███▉      | 766/1939 [01:03<04:25,  4.42it/s]
 40%|███▉      | 768/1939 [01:03<04:16,  4.56it/s]
 40%|███▉      | 769/1939 [01:04<05:10,  3.77it/s]
 40%|███▉      | 770/1939 [01:04<05:10,  3.77it/s]
 40%|███▉      | 772/1939 [01:05<05:03,  3.85it/s]
 40%|███▉      | 773/1939 [01:05<05:20,  3.64it/s]
 40%|███▉      | 774/1939 [01:05<05:39,  3.44it/s]
 40%|████      | 776/1939 [01:06<04:42,  4.11it/s]
 40%|████      | 778/1939 [01:06<03:21,  5.76it/s]
 40%|████      | 780/1939 [01:06<02:56,  6.57it/s]
 40%|████      | 781/1939 [01:06<03:25,  5.65it/s]
 40%|████      | 783/1939 [01:06<02:36,  7.40it/s]
 40%|████      | 785/1939 [01:07<03:58,  4.84it/s]
 41%|████      | 787/1939 [01:07<04:02,  4.75it/s]
 41%|████      | 789/1939 [01:08<04:12,  4.56it/s]
 41%|████      | 791/1939 [01:08<04:13,  4.53it/s]
 41%|████      | 793/1939 [01:08<03:13,  5.93it/s]
 41%|████      | 795/1939 [01:09<03:34,  5.34it/s]
 41%|████      | 796/1939 [01:09<04:17,  4.43it/s]
 41%|████      | 798/1939 [01:10<04:16,  4.45it/s]
 41%|████▏     | 800/1939 [01:10<03:13,  5.88it/s]
 41%|████▏     | 801/1939 [01:10<04:06,  4.62it/s]
 41%|████▏     | 804/1939 [01:10<02:35,  7.31it/s]
 42%|████▏     | 806/1939 [01:11<04:08,  4.56it/s]
 42%|████▏     | 808/1939 [01:11<03:17,  5.73it/s]
 42%|████▏     | 810/1939 [01:12<03:36,  5.22it/s]
 42%|████▏     | 812/1939 [01:12<02:56,  6.39it/s]
 42%|████▏     | 814/1939 [01:13<03:55,  4.78it/s]
 42%|████▏     | 816/1939 [01:13<03:44,  5.00it/s]
 42%|████▏     | 818/1939 [01:13<03:17,  5.66it/s]
 42%|████▏     | 820/1939 [01:14<03:09,  5.92it/s]
 42%|████▏     | 821/1939 [01:14<03:07,  5.97it/s]
 42%|████▏     | 822/1939 [01:14<03:08,  5.94it/s]
 42%|████▏     | 824/1939 [01:14<03:05,  6.00it/s]
 43%|████▎     | 826/1939 [01:14<02:31,  7.32it/s]
 43%|████▎     | 829/1939 [01:14<01:43, 10.72it/s]
 43%|████▎     | 831/1939 [01:15<01:53,  9.78it/s]
 43%|████▎     | 833/1939 [01:15<01:40, 10.96it/s]
 43%|████▎     | 839/1939 [01:15<00:56, 19.42it/s]
 43%|████▎     | 843/1939 [01:15<00:48, 22.81it/s]
 44%|████▎     | 846/1939 [01:15<00:54, 19.92it/s]
 44%|████▍     | 849/1939 [01:16<01:28, 12.35it/s]
 44%|████▍     | 851/1939 [01:16<01:21, 13.32it/s]
 44%|████▍     | 855/1939 [01:16<01:36, 11.18it/s]
 44%|████▍     | 857/1939 [01:17<02:14,  8.07it/s]
 44%|████▍     | 859/1939 [01:17<01:58,  9.15it/s]
 45%|████▍     | 864/1939 [01:17<01:14, 14.46it/s]
 45%|████▍     | 870/1939 [01:17<00:49, 21.50it/s]
 45%|████▌     | 877/1939 [01:17<00:35, 29.90it/s]
 46%|████▌     | 883/1939 [01:17<00:29, 35.74it/s]
 46%|████▌     | 890/1939 [01:18<00:24, 42.95it/s]
 46%|████▌     | 896/1939 [01:18<00:23, 44.85it/s]
 47%|████▋     | 902/1939 [01:18<00:23, 44.02it/s]
 47%|████▋     | 908/1939 [01:18<00:21, 47.80it/s]
 47%|████▋     | 914/1939 [01:18<00:26, 39.31it/s]
 47%|████▋     | 919/1939 [01:18<00:24, 41.53it/s]
 48%|████▊     | 924/1939 [01:18<00:24, 41.07it/s]
 48%|████▊     | 929/1939 [01:19<00:37, 26.97it/s]
 48%|████▊     | 933/1939 [01:19<00:36, 27.59it/s]
 48%|████▊     | 937/1939 [01:19<00:35, 28.18it/s]
 49%|████▊     | 943/1939 [01:19<00:31, 31.65it/s]
 49%|████▉     | 947/1939 [01:19<00:29, 33.22it/s]
 49%|████▉     | 955/1939 [01:19<00:23, 42.34it/s]
 50%|████▉     | 960/1939 [01:19<00:23, 42.38it/s]
 50%|████▉     | 965/1939 [01:20<00:22, 43.09it/s]
 50%|█████     | 970/1939 [01:20<00:28, 33.55it/s]
 50%|█████     | 974/1939 [01:20<00:33, 28.42it/s]
 50%|█████     | 978/1939 [01:21<01:20, 11.91it/s]
 51%|█████     | 981/1939 [01:21<01:12, 13.24it/s]
 51%|█████     | 984/1939 [01:22<01:56,  8.18it/s]
 51%|█████     | 986/1939 [01:22<01:46,  8.97it/s]
 51%|█████     | 988/1939 [01:22<01:46,  8.92it/s]
 51%|█████     | 990/1939 [01:23<02:08,  7.36it/s]
 51%|█████     | 992/1939 [01:23<01:48,  8.70it/s]
 51%|█████▏    | 994/1939 [01:23<02:14,  7.04it/s]
 51%|█████▏    | 996/1939 [01:23<02:14,  7.03it/s]
 51%|█████▏    | 998/1939 [01:24<02:25,  6.48it/s]
 52%|█████▏    | 999/1939 [01:24<02:45,  5.69it/s]
 52%|█████▏    | 1001/1939 [01:24<02:17,  6.84it/s]
 52%|█████▏    | 1002/1939 [01:24<02:29,  6.25it/s]
 52%|█████▏    | 1003/1939 [01:25<02:40,  5.84it/s]
 52%|█████▏    | 1005/1939 [01:25<02:00,  7.75it/s]
 52%|█████▏    | 1007/1939 [01:25<02:16,  6.81it/s]
 52%|█████▏    | 1009/1939 [01:25<02:17,  6.76it/s]
 52%|█████▏    | 1011/1939 [01:26<02:14,  6.92it/s]
 52%|█████▏    | 1013/1939 [01:26<01:51,  8.27it/s]
 52%|█████▏    | 1014/1939 [01:26<02:42,  5.70it/s]
 52%|█████▏    | 1015/1939 [01:27<03:42,  4.16it/s]
 52%|█████▏    | 1017/1939 [01:27<03:08,  4.89it/s]
 53%|█████▎    | 1019/1939 [01:27<02:46,  5.51it/s]
 53%|█████▎    | 1021/1939 [01:27<02:12,  6.95it/s]
 53%|█████▎    | 1024/1939 [01:28<01:30, 10.11it/s]
 53%|█████▎    | 1028/1939 [01:28<01:00, 14.97it/s]
 53%|█████▎    | 1031/1939 [01:28<01:33,  9.76it/s]
 54%|█████▎    | 1038/1939 [01:28<00:51, 17.41it/s]
 54%|█████▍    | 1044/1939 [01:28<00:37, 23.75it/s]
 54%|█████▍    | 1048/1939 [01:29<01:17, 11.50it/s]
 54%|█████▍    | 1051/1939 [01:29<01:15, 11.78it/s]
 54%|█████▍    | 1054/1939 [01:30<01:27, 10.15it/s]
 54%|█████▍    | 1056/1939 [01:30<01:34,  9.34it/s]
 55%|█████▍    | 1059/1939 [01:31<01:32,  9.53it/s]
 55%|█████▍    | 1061/1939 [01:31<01:56,  7.56it/s]
 55%|█████▍    | 1064/1939 [01:31<01:56,  7.50it/s]
 55%|█████▍    | 1066/1939 [01:31<01:40,  8.65it/s]
 55%|█████▌    | 1068/1939 [01:32<02:05,  6.96it/s]
 55%|█████▌    | 1070/1939 [01:32<01:49,  7.91it/s]
 55%|█████▌    | 1072/1939 [01:33<02:48,  5.14it/s]
 55%|█████▌    | 1074/1939 [01:33<02:16,  6.34it/s]
 56%|█████▌    | 1077/1939 [01:33<02:12,  6.53it/s]
 56%|█████▌    | 1080/1939 [01:34<02:16,  6.28it/s]
 56%|█████▌    | 1081/1939 [01:34<02:46,  5.16it/s]
 56%|█████▌    | 1083/1939 [01:34<02:14,  6.38it/s]
 56%|█████▌    | 1087/1939 [01:35<01:23, 10.17it/s]
 56%|█████▌    | 1089/1939 [01:35<01:38,  8.66it/s]
 56%|█████▋    | 1091/1939 [01:35<01:26,  9.85it/s]
 56%|█████▋    | 1093/1939 [01:35<01:23, 10.09it/s]
 56%|█████▋    | 1095/1939 [01:35<01:23, 10.07it/s]
 57%|█████▋    | 1097/1939 [01:36<01:19, 10.61it/s]
 57%|█████▋    | 1099/1939 [01:36<01:35,  8.84it/s]
 57%|█████▋    | 1101/1939 [01:36<01:27,  9.62it/s]
 57%|█████▋    | 1103/1939 [01:36<01:17, 10.76it/s]
 57%|█████▋    | 1106/1939 [01:37<01:21, 10.26it/s]
 57%|█████▋    | 1108/1939 [01:37<01:12, 11.54it/s]
 57%|█████▋    | 1110/1939 [01:37<01:22, 10.09it/s]
 57%|█████▋    | 1112/1939 [01:37<01:23,  9.95it/s]
 57%|█████▋    | 1114/1939 [01:37<01:12, 11.45it/s]
 58%|█████▊    | 1119/1939 [01:37<00:44, 18.40it/s]
 58%|█████▊    | 1122/1939 [01:38<01:05, 12.51it/s]
 58%|█████▊    | 1126/1939 [01:38<01:07, 12.02it/s]
 58%|█████▊    | 1128/1939 [01:38<01:17, 10.43it/s]
 58%|█████▊    | 1130/1939 [01:39<01:24,  9.60it/s]
 58%|█████▊    | 1132/1939 [01:39<01:18, 10.29it/s]
 59%|█████▊    | 1135/1939 [01:39<01:25,  9.38it/s]
 59%|█████▊    | 1137/1939 [01:39<01:19, 10.06it/s]
 59%|█████▉    | 1141/1939 [01:39<00:55, 14.41it/s]
 59%|█████▉    | 1146/1939 [01:40<00:39, 19.95it/s]
 59%|█████▉    | 1149/1939 [01:40<01:25,  9.29it/s]
 59%|█████▉    | 1151/1939 [01:41<01:29,  8.83it/s]
 59%|█████▉    | 1153/1939 [01:41<01:27,  8.98it/s]
 60%|█████▉    | 1155/1939 [01:41<01:39,  7.91it/s]
 60%|█████▉    | 1158/1939 [01:41<01:20,  9.74it/s]
 60%|█████▉    | 1160/1939 [01:42<01:37,  8.02it/s]
 60%|█████▉    | 1163/1939 [01:42<01:30,  8.57it/s]
 60%|██████    | 1165/1939 [01:42<01:33,  8.24it/s]
 60%|██████    | 1168/1939 [01:42<01:12, 10.56it/s]
 60%|██████    | 1170/1939 [01:43<01:43,  7.46it/s]
 60%|██████    | 1173/1939 [01:43<01:16,  9.96it/s]
 61%|██████    | 1175/1939 [01:43<01:30,  8.46it/s]
 61%|██████    | 1177/1939 [01:44<01:19,  9.57it/s]
 61%|██████    | 1179/1939 [01:44<01:29,  8.53it/s]
 61%|██████    | 1181/1939 [01:44<01:28,  8.54it/s]
 61%|██████    | 1183/1939 [01:45<01:53,  6.66it/s]
 61%|██████    | 1184/1939 [01:45<01:54,  6.60it/s]
 61%|██████    | 1186/1939 [01:45<01:35,  7.90it/s]
 61%|██████▏   | 1188/1939 [01:45<01:48,  6.94it/s]
 61%|██████▏   | 1190/1939 [01:46<01:51,  6.74it/s]
 61%|██████▏   | 1192/1939 [01:46<01:31,  8.16it/s]
 62%|██████▏   | 1194/1939 [01:46<01:44,  7.11it/s]
 62%|██████▏   | 1196/1939 [01:46<01:39,  7.47it/s]
 62%|██████▏   | 1198/1939 [01:47<01:52,  6.57it/s]
 62%|██████▏   | 1200/1939 [01:47<01:30,  8.16it/s]
 62%|██████▏   | 1203/1939 [01:47<01:04, 11.33it/s]
 62%|██████▏   | 1206/1939 [01:47<00:52, 13.95it/s]
 63%|██████▎   | 1212/1939 [01:47<00:32, 22.41it/s]
 63%|██████▎   | 1217/1939 [01:48<00:44, 16.12it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 313.80it/s]
 84%|████████▎ | 251/300 [14:35<24:48, 30.38s/it]

[[np.int64(0), False, 9], [np.int64(1), False, 6], [np.int64(2), False, 3], [np.int64(4), False, 1], [np.int64(5), False, 10], [np.int64(7), False, 12], [np.int64(8), False, 3], [np.int64(10), False, 4], [np.int64(11), False, 2], [np.int64(12), False, 1], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3368, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.3529, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8767, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [14:35<19:25, 24.29s/it]

tensor(12.3819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2051, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [14:35<11:50, 15.45s/it]

tensor(12.4249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4494, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6882, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4886, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9711, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [14:35<07:28, 10.19s/it]

tensor(12.4858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0674, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9864, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [14:36<04:48,  6.87s/it]

tensor(12.4419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0382, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9360, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [14:36<03:08,  4.70s/it]

tensor(12.4293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0391, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9527, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0398, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7366, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4685, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [14:36<02:03,  3.26s/it]

tensor(12.4326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4318, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0376, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6428, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [14:36<01:22,  2.28s/it]

tensor(12.4386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7803, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [14:36<00:54,  1.61s/it]

tensor(12.4578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8470, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9068, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0379, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7850, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [14:37<00:36,  1.15s/it]

tensor(12.4786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8108, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8653, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [14:37<00:24,  1.21it/s]

tensor(12.4462, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9213, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [14:37<00:17,  1.65it/s]

tensor(12.4438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9920, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4511, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0534, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4594, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0882, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [14:37<00:11,  2.21it/s]

tensor(12.4614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1189, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1369, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [14:37<00:08,  2.90it/s]

tensor(12.4430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1524, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [14:38<00:05,  3.71it/s]

tensor(12.4291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1626, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1717, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1953, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [14:38<00:04,  4.61it/s]

tensor(12.4032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2092, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2341, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [14:38<00:03,  5.56it/s]

tensor(12.3928, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2902, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [14:38<00:02,  6.49it/s]

tensor(12.3854, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3088, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3301, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3676, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [14:38<00:01,  7.33it/s]

tensor(12.3685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3887, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4122, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [14:38<00:01,  8.08it/s]

tensor(12.3609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4306, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [14:39<00:01,  8.72it/s]

tensor(12.3557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4511, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4706, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3445, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4844, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [14:39<00:00,  9.18it/s]

tensor(12.3390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5022, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5243, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [14:39<00:00,  9.52it/s]

tensor(12.3303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5398, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [14:39<00:00,  9.86it/s]

tensor(12.3269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5462, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5566, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5727, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [14:39<00:00, 10.07it/s]

tensor(12.3163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5799, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5889, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [14:40<00:00,  2.93s/it]

Model training finished!

Infer time:  0.0020325183868408203
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 1
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.452735122904
NMI         : 0.583210128661
Runtime     : 899.70 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed1

==============================================================================================================
PRAGA RUN | S2-E15 | seed=2
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 6.247e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29,  9.97it/s]

tensor(17.6848, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3793, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6763, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2372, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:26, 11.00it/s]

tensor(17.6698, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3047, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6620, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5623, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6515, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9908, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:23, 12.56it/s]

tensor(17.6406, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5735, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6296, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2958, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6196, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1429, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.85it/s]

tensor(17.6091, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1040, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6001, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1672, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5917, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3227, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:00<00:22, 13.05it/s]

tensor(17.5840, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5614, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5774, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8751, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5713, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2562, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.27it/s]

tensor(17.5655, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6992, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5599, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1965, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5547, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7442, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:21, 13.33it/s]

tensor(17.5490, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3368, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5431, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9696, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5368, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6394, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:20, 13.44it/s]

tensor(17.5295, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3417, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5218, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0740, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5129, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8334, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:20, 13.51it/s]

tensor(17.5031, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6169, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4922, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4798, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2474, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.42it/s]

tensor(17.4660, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0908, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9505, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8241, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:02<00:19, 13.40it/s]

tensor(17.4138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7114, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6109, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5209, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:19, 13.38it/s]

tensor(17.3406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4411, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3105, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3691, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3065, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:02<00:19, 13.43it/s]

tensor(17.2397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2511, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2024, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1609, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.49it/s]

tensor(17.1050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0523, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0963, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0734, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.47it/s]

tensor(16.9360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0564, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:18, 13.44it/s]

tensor(16.7377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:18, 13.41it/s]

tensor(16.5094, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:03<00:18, 13.47it/s]

tensor(16.2411, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:04<00:18, 13.44it/s]

tensor(15.9163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:17, 13.45it/s]

tensor(15.5571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:04<00:17, 13.40it/s]

tensor(15.2049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.40it/s]

tensor(14.9572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:04<00:17, 13.40it/s]

tensor(14.7276, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.37it/s]

tensor(14.4605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:17, 13.32it/s]

tensor(14.2765, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:16, 13.37it/s]

tensor(14.1291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:06<00:16, 13.43it/s]

tensor(13.9955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9511, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.42it/s]

tensor(13.8627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:16, 13.43it/s]

tensor(13.7479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:15, 13.43it/s]

tensor(13.6570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:06<00:15, 13.46it/s]

tensor(13.5762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5240, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.44it/s]

tensor(13.4983, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:07<00:15, 13.44it/s]

tensor(13.4225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3981, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:14, 13.39it/s]

tensor(13.3525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([178,  59,  67, 410, 106, 187, 110, 113, 163,  71,  80,  33,  34, 328])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 5/1939 [00:00<00:40, 48.03it/s]
  1%|          | 10/1939 [00:00<00:55, 34.47it/s]
  1%|          | 16/1939 [00:00<00:44, 43.19it/s]
  1%|          | 21/1939 [00:00<00:45, 42.02it/s]
  1%|▏         | 27/1939 [00:00<00:40, 47.44it/s]
  2%|▏         | 34/1939 [00:00<00:38, 49.09it/s]
  2%|▏         | 40/1939 [00:00<00:45, 41.74it/s]
  2%|▏         | 45/1939 [00:01<01:55, 16.34it/s]
  3%|▎         | 49/1939 [00:02<02:16, 13.89it/s]
  3%|▎         | 52/1939 [00:02<02:05, 15.09it/s]
  3%|▎         | 55/1939 [00:02<02:46, 11.30it/s]
  3%|▎         | 57/1939 [00:03<03:25,  9.16it/s]
  3%|▎         | 59/1939 [00:03<04:47,  6.54it/s]
  3%|▎         | 62/1939 [00:03<03:42,  8.42it/s]
  3%|▎         | 65/1939 [00:04<03:00, 10.38it/s]
  3%|▎         | 67/1939 [00:04<03:43,  8.38it/s]
  4%|▎         | 69/1939 [00:04<03:14,  9.64it/s]
  4%|▎         | 71/1939 [00:04<04:02,  7.72it/s]
  4%|▍         | 73/1939 [00:05<04:34,  6.81it/s]
  4%|▍         | 75/1939 [00:05<03:46,  8.22it/s]
  4%|▍         | 77/1939 [00:05<03:14,  9.57it/s]
  4%|▍         | 79/1939 [00:05<03:37,  8.57it/s]
  4%|▍         | 81/1939 [00:06<05:19,  5.82it/s]
  4%|▍         | 82/1939 [00:06<05:23,  5.74it/s]
  4%|▍         | 83/1939 [00:06<05:51,  5.28it/s]
  4%|▍         | 84/1939 [00:07<05:54,  5.24it/s]
  4%|▍         | 86/1939 [00:07<04:44,  6.51it/s]
  4%|▍         | 87/1939 [00:07<05:06,  6.03it/s]
 33%|███▎      | 100/300 [00:19<00:14, 13.39it/s]
  5%|▍         | 93/1939 [00:07<02:14, 13.69it/s]
  5%|▍         | 95/1939 [00:08<03:32,  8.67it/s]
  5%|▌         | 97/1939 [00:08<03:57,  7.76it/s]
  5%|▌         | 100/1939 [00:08<04:00,  7.66it/s]
  5%|▌         | 102/1939 [00:09<04:19,  7.07it/s]
  5%|▌         | 105/1939 [00:09<04:05,  7.46it/s]
  6%|▌         | 107/1939 [00:09<04:09,  7.36it/s]
  6%|▌         | 109/1939 [00:10<03:28,  8.78it/s]
  6%|▌         | 111/1939 [00:10<03:24,  8.94it/s]
  6%|▌         | 113/1939 [00:10<02:52, 10.59it/s]
  6%|▌         | 115/1939 [00:10<03:39,  8.29it/s]
  6%|▌         | 117/1939 [00:11<04:23,  6.91it/s]
  6%|▌         | 118/1939 [00:11<05:06,  5.94it/s]
  6%|▌         | 120/1939 [00:11<04:26,  6.82it/s]
  6%|▌         | 121/1939 [00:11<05:18,  5.71it/s]
  6%|▋         | 123/1939 [00:12<04:13,  7.16it/s]
  6%|▋         | 126/1939 [00:12<04:14,  7.11it/s]
  7%|▋         | 128/1939 [00:12<04:26,  6.79it/s]
  7%|▋         | 130/1939 [00:12<03:36,  8.35it/s]
  7%|▋         | 132/1939 [00:13<04:13,  7.13it/s]
  7%|▋         | 135/1939 [00:13<04:06,  7.31it/s]
  7%|▋         | 137/1939 [00:14<04:47,  6.26it/s]
  7%|▋         | 138/1939 [00:14<05:28,  5.48it/s]
  7%|▋         | 139/1939 [00:14<06:10,  4.86it/s]
  7%|▋         | 141/1939 [00:15<05:54,  5.07it/s]
  7%|▋         | 142/1939 [00:15<07:06,  4.22it/s]
  7%|▋         | 144/1939 [00:15<05:04,  5.89it/s]
  7%|▋         | 145/1939 [00:15<06:08,  4.87it/s]
  8%|▊         | 146/1939 [00:16<07:20,  4.07it/s]
  8%|▊         | 149/1939 [00:16<05:31,  5.40it/s]
  8%|▊         | 151/1939 [00:17<05:28,  5.44it/s]
  8%|▊         | 153/1939 [00:17<05:37,  5.29it/s]
  8%|▊         | 155/1939 [00:17<04:23,  6.76it/s]
  8%|▊         | 157/1939 [00:17<04:38,  6.40it/s]
  8%|▊         | 158/1939 [00:18<05:43,  5.19it/s]
  8%|▊         | 159/1939 [00:18<06:29,  4.57it/s]
  8%|▊         | 160/1939 [00:19<07:34,  3.91it/s]
  8%|▊         | 161/1939 [00:19<08:12,  3.61it/s]
  8%|▊         | 162/1939 [00:19<08:34,  3.45it/s]
  8%|▊         | 163/1939 [00:19<08:40,  3.41it/s]
  8%|▊         | 164/1939 [00:20<09:16,  3.19it/s]
  9%|▊         | 165/1939 [00:20<09:37,  3.07it/s]
  9%|▊         | 167/1939 [00:20<06:02,  4.88it/s]
  9%|▉         | 170/1939 [00:21<05:00,  5.89it/s]
  9%|▉         | 172/1939 [00:21<03:53,  7.57it/s]
  9%|▉         | 178/1939 [00:21<01:56, 15.06it/s]
  9%|▉         | 184/1939 [00:21<01:17, 22.73it/s]
 10%|▉         | 189/1939 [00:21<01:03, 27.61it/s]
 10%|▉         | 193/1939 [00:21<01:06, 26.44it/s]
 10%|█         | 199/1939 [00:22<01:30, 19.15it/s]
 10%|█         | 202/1939 [00:22<01:53, 15.29it/s]
 11%|█         | 205/1939 [00:22<02:13, 13.03it/s]
 11%|█         | 207/1939 [00:23<02:14, 12.85it/s]
 11%|█         | 209/1939 [00:23<02:09, 13.39it/s]
 11%|█         | 211/1939 [00:23<02:40, 10.79it/s]
 11%|█         | 213/1939 [00:23<03:18,  8.70it/s]
 11%|█         | 215/1939 [00:24<03:29,  8.21it/s]
 11%|█         | 217/1939 [00:24<02:58,  9.64it/s]
 11%|█▏        | 219/1939 [00:24<03:36,  7.93it/s]
 11%|█▏        | 221/1939 [00:24<03:35,  7.96it/s]
 11%|█▏        | 222/1939 [00:25<03:34,  8.00it/s]
 12%|█▏        | 224/1939 [00:25<03:23,  8.44it/s]
 12%|█▏        | 225/1939 [00:25<03:24,  8.39it/s]
 12%|█▏        | 227/1939 [00:25<03:29,  8.17it/s]
 12%|█▏        | 228/1939 [00:25<03:33,  8.02it/s]
 12%|█▏        | 229/1939 [00:26<05:05,  5.59it/s]
 12%|█▏        | 230/1939 [00:26<05:41,  5.01it/s]
 12%|█▏        | 232/1939 [00:26<03:59,  7.12it/s]
 12%|█▏        | 233/1939 [00:26<03:54,  7.27it/s]
 12%|█▏        | 234/1939 [00:26<03:49,  7.43it/s]
 12%|█▏        | 236/1939 [00:27<04:25,  6.42it/s]
 12%|█▏        | 237/1939 [00:27<05:34,  5.08it/s]
 12%|█▏        | 239/1939 [00:27<05:26,  5.21it/s]
 12%|█▏        | 240/1939 [00:28<06:39,  4.26it/s]
 12%|█▏        | 241/1939 [00:28<07:26,  3.81it/s]
 12%|█▏        | 242/1939 [00:28<08:15,  3.43it/s]
 13%|█▎        | 243/1939 [00:29<08:32,  3.31it/s]
 13%|█▎        | 244/1939 [00:29<08:39,  3.26it/s]
 13%|█▎        | 245/1939 [00:29<07:31,  3.75it/s]
 13%|█▎        | 246/1939 [00:30<08:16,  3.41it/s]
 13%|█▎        | 247/1939 [00:30<09:06,  3.10it/s]
 13%|█▎        | 248/1939 [00:30<08:13,  3.43it/s]
 13%|█▎        | 250/1939 [00:31<06:22,  4.41it/s]
 13%|█▎        | 251/1939 [00:31<06:21,  4.42it/s]
 13%|█▎        | 253/1939 [00:31<04:28,  6.28it/s]
 13%|█▎        | 255/1939 [00:31<03:22,  8.32it/s]
 13%|█▎        | 257/1939 [00:31<04:15,  6.59it/s]
 13%|█▎        | 258/1939 [00:32<05:04,  5.51it/s]
 13%|█▎        | 260/1939 [00:32<05:04,  5.51it/s]
 14%|█▎        | 262/1939 [00:32<03:57,  7.05it/s]
 14%|█▎        | 263/1939 [00:33<05:13,  5.35it/s]
 14%|█▎        | 264/1939 [00:33<05:54,  4.73it/s]
 14%|█▍        | 267/1939 [00:33<03:31,  7.92it/s]
 14%|█▍        | 269/1939 [00:33<03:54,  7.13it/s]
 14%|█▍        | 271/1939 [00:34<04:08,  6.71it/s]
 14%|█▍        | 273/1939 [00:34<04:34,  6.06it/s]
 14%|█▍        | 274/1939 [00:34<04:45,  5.84it/s]
 14%|█▍        | 277/1939 [00:34<03:13,  8.58it/s]
 14%|█▍        | 279/1939 [00:35<03:02,  9.08it/s]
 14%|█▍        | 281/1939 [00:35<03:44,  7.39it/s]
 15%|█▍        | 283/1939 [00:35<03:08,  8.78it/s]
 15%|█▍        | 285/1939 [00:36<04:32,  6.07it/s]
 15%|█▍        | 287/1939 [00:36<04:20,  6.35it/s]
 15%|█▍        | 288/1939 [00:36<04:48,  5.73it/s]
 15%|█▌        | 291/1939 [00:36<03:15,  8.43it/s]
 15%|█▌        | 293/1939 [00:37<03:18,  8.30it/s]
 15%|█▌        | 296/1939 [00:37<03:00,  9.09it/s]
 15%|█▌        | 298/1939 [00:37<02:57,  9.23it/s]
 15%|█▌        | 300/1939 [00:37<03:04,  8.87it/s]
 16%|█▌        | 302/1939 [00:37<02:38, 10.36it/s]
 16%|█▌        | 304/1939 [00:38<03:14,  8.40it/s]
 16%|█▌        | 306/1939 [00:38<02:45,  9.89it/s]
 16%|█▌        | 308/1939 [00:38<03:12,  8.46it/s]
 16%|█▌        | 312/1939 [00:39<02:57,  9.19it/s]
 16%|█▌        | 314/1939 [00:39<02:36, 10.37it/s]
 16%|█▋        | 316/1939 [00:39<04:18,  6.29it/s]
 16%|█▋        | 317/1939 [00:40<04:51,  5.56it/s]
 16%|█▋        | 318/1939 [00:40<05:27,  4.94it/s]
 16%|█▋        | 319/1939 [00:40<06:09,  4.38it/s]
 17%|█▋        | 320/1939 [00:41<06:52,  3.92it/s]
 17%|█▋        | 321/1939 [00:41<07:12,  3.74it/s]
 17%|█▋        | 322/1939 [00:41<07:25,  3.63it/s]
 17%|█▋        | 325/1939 [00:41<04:06,  6.56it/s]
 17%|█▋        | 327/1939 [00:42<04:12,  6.39it/s]
 17%|█▋        | 330/1939 [00:42<02:51,  9.36it/s]
 17%|█▋        | 336/1939 [00:42<01:33, 17.22it/s]
 18%|█▊        | 343/1939 [00:42<00:59, 26.72it/s]
 18%|█▊        | 349/1939 [00:42<00:48, 32.66it/s]
 18%|█▊        | 354/1939 [00:43<02:16, 11.63it/s]
 18%|█▊        | 358/1939 [00:44<03:04,  8.57it/s]
 19%|█▊        | 361/1939 [00:44<03:05,  8.51it/s]
 19%|█▊        | 363/1939 [00:45<03:21,  7.83it/s]
 19%|█▉        | 365/1939 [00:45<02:58,  8.81it/s]
 19%|█▉        | 367/1939 [00:45<03:25,  7.64it/s]
 19%|█▉        | 369/1939 [00:46<03:24,  7.69it/s]
 19%|█▉        | 371/1939 [00:46<03:41,  7.09it/s]
 19%|█▉        | 372/1939 [00:46<04:18,  6.06it/s]
 19%|█▉        | 373/1939 [00:46<04:37,  5.64it/s]
 19%|█▉        | 375/1939 [00:47<03:32,  7.36it/s]
 19%|█▉        | 377/1939 [00:47<04:37,  5.64it/s]
 19%|█▉        | 378/1939 [00:47<05:15,  4.94it/s]
 20%|█▉        | 381/1939 [00:48<04:53,  5.31it/s]
 20%|█▉        | 384/1939 [00:48<04:20,  5.96it/s]
 20%|█▉        | 385/1939 [00:49<05:10,  5.00it/s]
 20%|█▉        | 387/1939 [00:49<05:01,  5.15it/s]
 20%|██        | 388/1939 [00:49<05:41,  4.54it/s]
 20%|██        | 389/1939 [00:49<05:15,  4.92it/s]
 20%|██        | 390/1939 [00:50<04:45,  5.42it/s]
 20%|██        | 391/1939 [00:50<05:14,  4.93it/s]
 20%|██        | 392/1939 [00:50<05:15,  4.90it/s]
 20%|██        | 393/1939 [00:50<04:37,  5.57it/s]
 20%|██        | 394/1939 [00:50<04:21,  5.90it/s]
 20%|██        | 395/1939 [00:51<06:00,  4.28it/s]
 20%|██        | 396/1939 [00:51<05:16,  4.87it/s]
 20%|██        | 397/1939 [00:51<04:56,  5.20it/s]
 21%|██        | 398/1939 [00:51<04:44,  5.41it/s]
 21%|██        | 400/1939 [00:51<03:13,  7.97it/s]
 21%|██        | 403/1939 [00:51<02:03, 12.43it/s]
 21%|██        | 405/1939 [00:52<02:58,  8.57it/s]
 21%|██        | 407/1939 [00:52<03:17,  7.74it/s]
 21%|██        | 409/1939 [00:52<02:40,  9.52it/s]
 21%|██        | 411/1939 [00:52<02:52,  8.87it/s]
 21%|██▏       | 413/1939 [00:53<02:53,  8.82it/s]
 21%|██▏       | 415/1939 [00:53<03:03,  8.32it/s]
 21%|██▏       | 416/1939 [00:53<03:41,  6.86it/s]
 22%|██▏       | 417/1939 [00:54<04:45,  5.33it/s]
 22%|██▏       | 419/1939 [00:54<04:07,  6.15it/s]
 22%|██▏       | 422/1939 [00:54<03:11,  7.94it/s]
 22%|██▏       | 424/1939 [00:54<02:37,  9.60it/s]
 22%|██▏       | 426/1939 [00:54<02:29, 10.11it/s]
 22%|██▏       | 428/1939 [00:55<02:25, 10.36it/s]
 22%|██▏       | 430/1939 [00:55<02:08, 11.73it/s]
 22%|██▏       | 436/1939 [00:55<01:11, 20.90it/s]
 23%|██▎       | 443/1939 [00:55<00:50, 29.88it/s]
 23%|██▎       | 448/1939 [00:55<00:43, 34.24it/s]
 23%|██▎       | 453/1939 [00:55<00:57, 25.98it/s]
 24%|██▎       | 457/1939 [00:55<01:03, 23.50it/s]
 24%|██▍       | 464/1939 [00:56<00:46, 31.95it/s]
 24%|██▍       | 470/1939 [00:56<00:39, 37.23it/s]
 25%|██▍       | 476/1939 [00:56<00:34, 42.00it/s]
 25%|██▍       | 483/1939 [00:56<00:31, 46.58it/s]
 25%|██▌       | 489/1939 [00:56<00:48, 30.20it/s]
 25%|██▌       | 494/1939 [00:57<01:23, 17.28it/s]
 26%|██▌       | 498/1939 [00:58<01:54, 12.54it/s]
 26%|██▌       | 501/1939 [00:58<02:11, 10.95it/s]
 26%|██▌       | 503/1939 [00:58<02:02, 11.71it/s]
 26%|██▌       | 505/1939 [00:58<02:12, 10.84it/s]
 26%|██▌       | 507/1939 [00:58<02:01, 11.80it/s]
 26%|██▋       | 511/1939 [00:59<02:18, 10.27it/s]
 26%|██▋       | 513/1939 [00:59<02:07, 11.19it/s]
 27%|██▋       | 521/1939 [00:59<01:08, 20.76it/s]
 27%|██▋       | 529/1939 [00:59<00:46, 30.61it/s]
 28%|██▊       | 534/1939 [01:00<01:00, 23.26it/s]
 28%|██▊       | 538/1939 [01:00<01:52, 12.50it/s]
 28%|██▊       | 541/1939 [01:01<01:55, 12.16it/s]
 28%|██▊       | 544/1939 [01:01<01:45, 13.27it/s]
 28%|██▊       | 547/1939 [01:01<02:00, 11.54it/s]
 28%|██▊       | 549/1939 [01:01<02:07, 10.94it/s]
 28%|██▊       | 551/1939 [01:02<02:35,  8.92it/s]
 29%|██▊       | 553/1939 [01:02<03:00,  7.67it/s]
 29%|██▊       | 556/1939 [01:02<02:56,  7.83it/s]
 29%|██▉       | 558/1939 [01:03<03:10,  7.25it/s]
 29%|██▉       | 560/1939 [01:03<02:41,  8.54it/s]
 29%|██▉       | 562/1939 [01:04<03:49,  5.99it/s]
 29%|██▉       | 564/1939 [01:04<03:06,  7.36it/s]
 29%|██▉       | 567/1939 [01:04<02:58,  7.70it/s]
 29%|██▉       | 569/1939 [01:04<03:15,  7.01it/s]
 29%|██▉       | 571/1939 [01:05<03:28,  6.56it/s]
 29%|██▉       | 572/1939 [01:05<04:15,  5.35it/s]
 30%|██▉       | 574/1939 [01:06<04:34,  4.97it/s]
 30%|██▉       | 575/1939 [01:06<04:57,  4.59it/s]
 30%|██▉       | 576/1939 [01:06<05:44,  3.96it/s]
 30%|██▉       | 578/1939 [01:06<04:05,  5.53it/s]
 30%|██▉       | 579/1939 [01:07<04:40,  4.85it/s]
 30%|██▉       | 580/1939 [01:07<05:41,  3.98it/s]
 30%|███       | 582/1939 [01:07<05:13,  4.32it/s]
 30%|███       | 584/1939 [01:08<04:27,  5.06it/s]
 30%|███       | 586/1939 [01:08<04:36,  4.89it/s]
 30%|███       | 589/1939 [01:09<03:52,  5.81it/s]
 30%|███       | 590/1939 [01:09<04:39,  4.82it/s]
 30%|███       | 591/1939 [01:09<05:22,  4.18it/s]
 31%|███       | 592/1939 [01:10<05:58,  3.76it/s]
 31%|███       | 593/1939 [01:10<06:09,  3.65it/s]
 31%|███       | 595/1939 [01:10<05:23,  4.15it/s]
 31%|███       | 596/1939 [01:11<06:06,  3.66it/s]
 31%|███       | 598/1939 [01:11<05:35,  4.00it/s]
 31%|███       | 599/1939 [01:12<06:14,  3.57it/s]
 31%|███       | 600/1939 [01:12<06:37,  3.37it/s]
 31%|███       | 601/1939 [01:12<06:46,  3.29it/s]
 31%|███       | 603/1939 [01:13<05:56,  3.75it/s]
 31%|███       | 605/1939 [01:13<05:27,  4.07it/s]
 31%|███▏      | 607/1939 [01:14<05:19,  4.17it/s]
 31%|███▏      | 608/1939 [01:14<05:31,  4.02it/s]
 31%|███▏      | 609/1939 [01:14<06:04,  3.65it/s]
 32%|███▏      | 611/1939 [01:15<05:27,  4.06it/s]
 32%|███▏      | 612/1939 [01:15<05:59,  3.69it/s]
 32%|███▏      | 613/1939 [01:15<06:00,  3.68it/s]
 32%|███▏      | 614/1939 [01:16<06:27,  3.42it/s]
 32%|███▏      | 615/1939 [01:16<06:29,  3.40it/s]
 32%|███▏      | 616/1939 [01:16<06:34,  3.36it/s]
 32%|███▏      | 617/1939 [01:16<06:42,  3.29it/s]
 32%|███▏      | 618/1939 [01:17<06:58,  3.15it/s]
 32%|███▏      | 619/1939 [01:17<06:18,  3.49it/s]
 32%|███▏      | 620/1939 [01:17<05:52,  3.75it/s]
 32%|███▏      | 621/1939 [01:18<06:05,  3.61it/s]
 32%|███▏      | 623/1939 [01:18<03:58,  5.51it/s]
 32%|███▏      | 629/1939 [01:18<02:40,  8.17it/s]
 32%|███▏      | 630/1939 [01:18<02:54,  7.51it/s]
 33%|███▎      | 632/1939 [01:19<02:35,  8.42it/s]
 33%|███▎      | 634/1939 [01:19<02:11,  9.89it/s]
 33%|███▎      | 636/1939 [01:19<02:30,  8.66it/s]
 33%|███▎      | 637/1939 [01:19<03:07,  6.93it/s]
 33%|███▎      | 640/1939 [01:20<02:36,  8.28it/s]
 33%|███▎      | 641/1939 [01:20<02:53,  7.49it/s]
 33%|███▎      | 643/1939 [01:20<03:13,  6.70it/s]
 33%|███▎      | 645/1939 [01:20<02:45,  7.81it/s]
 33%|███▎      | 646/1939 [01:21<03:20,  6.46it/s]
 33%|███▎      | 648/1939 [01:21<02:38,  8.15it/s]
 33%|███▎      | 649/1939 [01:21<03:04,  7.01it/s]
 34%|███▎      | 651/1939 [01:21<02:39,  8.08it/s]
 34%|███▎      | 652/1939 [01:21<03:34,  6.01it/s]
 34%|███▎      | 654/1939 [01:22<02:54,  7.36it/s]
 34%|███▍      | 656/1939 [01:22<02:33,  8.38it/s]
 34%|███▍      | 658/1939 [01:22<02:35,  8.23it/s]
 34%|███▍      | 661/1939 [01:22<01:54, 11.11it/s]
 34%|███▍      | 665/1939 [01:23<02:00, 10.59it/s]
 34%|███▍      | 667/1939 [01:23<02:35,  8.19it/s]
 34%|███▍      | 668/1939 [01:23<03:25,  6.19it/s]
 35%|███▍      | 670/1939 [01:24<02:46,  7.62it/s]
 35%|███▍      | 672/1939 [01:24<02:44,  7.70it/s]
 35%|███▍      | 673/1939 [01:24<02:38,  7.99it/s]
 35%|███▍      | 675/1939 [01:24<02:13,  9.49it/s]
 35%|███▍      | 677/1939 [01:24<02:44,  7.69it/s]
 35%|███▌      | 680/1939 [01:25<02:48,  7.48it/s]
 35%|███▌      | 682/1939 [01:25<02:26,  8.59it/s]
 35%|███▌      | 684/1939 [01:25<02:48,  7.45it/s]
 35%|███▌      | 686/1939 [01:25<02:23,  8.74it/s]
 35%|███▌      | 688/1939 [01:26<02:45,  7.58it/s]
 36%|███▌      | 689/1939 [01:26<03:41,  5.64it/s]
 36%|███▌      | 691/1939 [01:26<02:50,  7.34it/s]
 36%|███▌      | 693/1939 [01:27<03:17,  6.30it/s]
 36%|███▌      | 695/1939 [01:27<02:36,  7.96it/s]
 36%|███▌      | 701/1939 [01:27<01:18, 15.78it/s]
 36%|███▋      | 707/1939 [01:27<00:53, 23.16it/s]
 37%|███▋      | 712/1939 [01:27<00:44, 27.53it/s]
 37%|███▋      | 717/1939 [01:27<00:38, 31.49it/s]
 37%|███▋      | 723/1939 [01:27<00:32, 37.38it/s]
 38%|███▊      | 728/1939 [01:28<01:03, 19.01it/s]
 38%|███▊      | 732/1939 [01:29<01:56, 10.33it/s]
 38%|███▊      | 735/1939 [01:30<03:04,  6.54it/s]
 38%|███▊      | 738/1939 [01:30<02:30,  7.98it/s]
 38%|███▊      | 741/1939 [01:30<02:35,  7.70it/s]
 38%|███▊      | 743/1939 [01:31<02:53,  6.89it/s]
 38%|███▊      | 745/1939 [01:31<03:05,  6.44it/s]
 39%|███▊      | 747/1939 [01:32<03:27,  5.75it/s]
 39%|███▊      | 749/1939 [01:32<03:26,  5.76it/s]
 39%|███▊      | 751/1939 [01:32<03:39,  5.42it/s]
 39%|███▉      | 752/1939 [01:33<04:10,  4.73it/s]
 39%|███▉      | 755/1939 [01:33<03:35,  5.50it/s]
 39%|███▉      | 756/1939 [01:34<04:15,  4.63it/s]
 39%|███▉      | 757/1939 [01:34<04:50,  4.07it/s]
 39%|███▉      | 760/1939 [01:34<03:57,  4.97it/s]
 39%|███▉      | 761/1939 [01:35<04:03,  4.84it/s]
 39%|███▉      | 763/1939 [01:35<03:45,  5.22it/s]
 39%|███▉      | 764/1939 [01:35<04:23,  4.46it/s]
 40%|███▉      | 766/1939 [01:36<04:00,  4.88it/s]
 40%|███▉      | 767/1939 [01:36<04:50,  4.03it/s]
 40%|███▉      | 768/1939 [01:36<04:29,  4.34it/s]
 40%|███▉      | 769/1939 [01:36<04:06,  4.74it/s]
 40%|███▉      | 770/1939 [01:37<03:58,  4.89it/s]
 40%|███▉      | 771/1939 [01:37<04:30,  4.32it/s]
 40%|███▉      | 772/1939 [01:37<04:28,  4.35it/s]
 40%|███▉      | 773/1939 [01:37<04:13,  4.61it/s]
 40%|███▉      | 775/1939 [01:37<02:46,  7.00it/s]
 40%|████      | 776/1939 [01:38<03:27,  5.62it/s]
 40%|████      | 777/1939 [01:38<04:00,  4.82it/s]
 40%|████      | 779/1939 [01:38<03:35,  5.38it/s]
 40%|████      | 780/1939 [01:38<03:19,  5.82it/s]
 40%|████      | 781/1939 [01:39<03:00,  6.41it/s]
 40%|████      | 783/1939 [01:39<02:16,  8.49it/s]
 40%|████      | 784/1939 [01:39<02:15,  8.51it/s]
 40%|████      | 785/1939 [01:39<03:00,  6.40it/s]
 41%|████      | 787/1939 [01:39<03:16,  5.88it/s]
 41%|████      | 789/1939 [01:40<03:38,  5.27it/s]
 41%|████      | 791/1939 [01:40<03:50,  4.97it/s]
 41%|████      | 793/1939 [01:40<02:55,  6.53it/s]
 41%|████      | 794/1939 [01:41<03:23,  5.62it/s]
 41%|████      | 795/1939 [01:41<04:14,  4.49it/s]
 41%|████      | 796/1939 [01:41<04:38,  4.10it/s]
 41%|████      | 797/1939 [01:42<04:37,  4.12it/s]
 41%|████      | 798/1939 [01:42<04:25,  4.30it/s]
 41%|████▏     | 800/1939 [01:42<03:34,  5.30it/s]
 41%|████▏     | 801/1939 [01:42<03:51,  4.91it/s]
 41%|████▏     | 803/1939 [01:43<04:02,  4.68it/s]
 41%|████▏     | 804/1939 [01:43<03:58,  4.75it/s]
 42%|████▏     | 805/1939 [01:43<03:31,  5.35it/s]
 42%|████▏     | 806/1939 [01:43<03:46,  5.01it/s]
 42%|████▏     | 808/1939 [01:44<03:48,  4.95it/s]
 42%|████▏     | 809/1939 [01:44<04:26,  4.23it/s]
 42%|████▏     | 810/1939 [01:45<04:58,  3.78it/s]
 42%|████▏     | 812/1939 [01:45<04:32,  4.13it/s]
 42%|████▏     | 813/1939 [01:45<04:56,  3.80it/s]
 42%|████▏     | 814/1939 [01:46<05:23,  3.47it/s]
 42%|████▏     | 816/1939 [01:46<04:32,  4.12it/s]
 42%|████▏     | 817/1939 [01:46<05:06,  3.66it/s]
 42%|████▏     | 818/1939 [01:47<05:37,  3.32it/s]
 42%|████▏     | 819/1939 [01:47<06:10,  3.02it/s]
 42%|████▏     | 820/1939 [01:47<05:59,  3.11it/s]
 42%|████▏     | 821/1939 [01:48<06:06,  3.05it/s]
 42%|████▏     | 822/1939 [01:48<06:03,  3.07it/s]
 42%|████▏     | 823/1939 [01:48<06:08,  3.03it/s]
 43%|████▎     | 825/1939 [01:49<05:05,  3.64it/s]
 43%|████▎     | 826/1939 [01:49<05:17,  3.51it/s]
 43%|████▎     | 828/1939 [01:50<04:24,  4.20it/s]
 43%|████▎     | 829/1939 [01:50<04:45,  3.89it/s]
 43%|████▎     | 831/1939 [01:50<03:16,  5.65it/s]
 43%|████▎     | 834/1939 [01:50<02:44,  6.71it/s]
 43%|████▎     | 837/1939 [01:50<01:58,  9.32it/s]
 43%|████▎     | 839/1939 [01:51<02:13,  8.27it/s]
 43%|████▎     | 843/1939 [01:51<01:28, 12.41it/s]
 44%|████▎     | 845/1939 [01:51<01:50,  9.91it/s]
 44%|████▎     | 847/1939 [01:51<01:39, 10.98it/s]
 44%|████▍     | 851/1939 [01:52<01:41, 10.69it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 309.03it/s]
 34%|███▎      | 101/300 [04:19<2:27:28, 44.46s/it]

[[np.int64(0), False, 13], [np.int64(1), False, 5], [np.int64(2), False, 7], [np.int64(3), False, 13], [np.int64(4), False, 0], [np.int64(5), False, 0], [np.int64(6), False, 8], [np.int64(8), False, 3], [np.int64(9), False, 1], [np.int64(10), False, 5], [np.int64(11), False, 1], [np.int64(12), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.3112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.2820, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.2941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4251, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [04:19<1:57:16, 35.54s/it]

tensor(13.2959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6398, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [04:19<1:13:48, 22.60s/it]

tensor(13.3263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8187, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9819, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0781, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [04:19<48:07, 14.88s/it]

tensor(13.4763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1424, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [04:19<32:03, 10.02s/it]

tensor(13.4928, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1803, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1927, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2416, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [04:20<21:41,  6.85s/it]

tensor(13.3879, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2878, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3277, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [04:20<14:49,  4.73s/it]

tensor(13.2773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3689, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [04:20<10:13,  3.30s/it]

tensor(13.2316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4154, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4368, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4632, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [04:20<07:06,  2.32s/it]

tensor(13.1533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5022, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5493, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [04:20<04:58,  1.64s/it]

tensor(13.1247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5884, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:20<03:30,  1.17s/it]

tensor(13.1134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6262, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6778, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7196, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:21<02:30,  1.18it/s]

tensor(13.0824, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7869, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [04:21<01:48,  1.61it/s]

tensor(13.0541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8322, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [04:21<01:20,  2.17it/s]

tensor(13.0405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8661, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9050, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9372, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [04:21<01:00,  2.85it/s]

tensor(13.0134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9831, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0213, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [04:21<00:46,  3.65it/s]

tensor(12.9871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0641, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:22<00:36,  4.55it/s]

tensor(12.9718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1072, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1806, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [04:22<00:30,  5.50it/s]

tensor(12.9349, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2103, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2282, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:22<00:25,  6.41it/s]

tensor(12.9095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2495, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [04:22<00:22,  7.27it/s]

tensor(12.8951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2647, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2837, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3108, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [04:22<00:19,  8.03it/s]

tensor(12.8528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3322, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8373, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3491, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [04:23<00:18,  8.64it/s]

tensor(12.8205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3694, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [04:23<00:17,  9.14it/s]

tensor(12.8033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3963, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4161, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7703, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4398, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [04:23<00:16,  9.55it/s]

tensor(12.7544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4830, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [04:23<00:15,  9.82it/s]

tensor(12.7246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4971, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:23<00:14, 10.05it/s]

tensor(12.7115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5140, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([228, 218,  77,  88,  70, 111,  61, 120, 250,  34, 114,  30, 189, 349])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:15, 25.68it/s]
  1%|          | 10/1939 [00:00<00:39, 49.26it/s]
  1%|          | 17/1939 [00:00<00:34, 56.34it/s]
  1%|          | 23/1939 [00:00<00:54, 35.27it/s]
  1%|▏         | 28/1939 [00:00<00:57, 33.42it/s]
  2%|▏         | 33/1939 [00:00<00:52, 36.22it/s]
  2%|▏         | 39/1939 [00:00<00:46, 41.27it/s]
  2%|▏         | 44/1939 [00:01<01:59, 15.88it/s]
  3%|▎         | 49/1939 [00:02<02:21, 13.37it/s]
  3%|▎         | 52/1939 [00:02<02:05, 15.06it/s]
  3%|▎         | 55/1939 [00:02<02:59, 10.50it/s]
  3%|▎         | 58/1939 [00:03<02:32, 12.37it/s]
  3%|▎         | 61/1939 [00:03<02:13, 14.09it/s]
  3%|▎         | 64/1939 [00:03<02:05, 14.94it/s]
  3%|▎         | 67/1939 [00:03<03:12,  9.71it/s]
  4%|▎         | 70/1939 [00:04<02:53, 10.75it/s]
  4%|▍         | 73/1939 [00:04<03:48,  8.18it/s]
  4%|▍         | 76/1939 [00:04<03:02, 10.19it/s]
  4%|▍         | 78/1939 [00:05<03:54,  7.94it/s]
  4%|▍         | 80/1939 [00:05<05:19,  5.81it/s]
  4%|▍         | 82/1939 [00:06<04:30,  6.86it/s]
  4%|▍         | 86/1939 [00:06<04:25,  6.97it/s]
  5%|▍         | 89/1939 [00:06<03:25,  9.02it/s]
  5%|▍         | 94/1939 [00:07<03:15,  9.42it/s]
  5%|▍         | 96/1939 [00:07<03:23,  9.07it/s]
  5%|▌         | 99/1939 [00:07<02:44, 11.20it/s]
  5%|▌         | 101/1939 [00:07<02:46, 11.02it/s]
  5%|▌         | 104/1939 [00:07<02:17, 13.31it/s]
  6%|▌         | 109/1939 [00:08<01:35, 19.26it/s]
  6%|▌         | 112/1939 [00:08<01:26, 21.08it/s]
  6%|▌         | 115/1939 [00:08<01:37, 18.75it/s]
  6%|▌         | 118/1939 [00:08<02:55, 10.40it/s]
  6%|▌         | 120/1939 [00:09<03:59,  7.59it/s]
  6%|▋         | 122/1939 [00:09<03:30,  8.63it/s]
  6%|▋         | 126/1939 [00:09<02:24, 12.57it/s]
  7%|▋         | 129/1939 [00:10<02:33, 11.83it/s]
  7%|▋         | 131/1939 [00:10<02:19, 12.96it/s]
  7%|▋         | 133/1939 [00:10<03:01,  9.96it/s]
  7%|▋         | 135/1939 [00:10<03:53,  7.73it/s]
  7%|▋         | 137/1939 [00:11<03:59,  7.52it/s]
  7%|▋         | 139/1939 [00:11<04:20,  6.92it/s]
  7%|▋         | 141/1939 [00:11<03:44,  8.00it/s]
  7%|▋         | 143/1939 [00:11<03:27,  8.67it/s]
  7%|▋         | 145/1939 [00:12<04:41,  6.37it/s]
  8%|▊         | 147/1939 [00:12<03:45,  7.94it/s]
  8%|▊         | 149/1939 [00:12<03:14,  9.18it/s]
  8%|▊         | 151/1939 [00:12<02:47, 10.68it/s]
  8%|▊         | 153/1939 [00:13<04:24,  6.74it/s]
 50%|█████     | 150/300 [04:39<00:14, 10.05it/s]]
  8%|▊         | 158/1939 [00:14<06:23,  4.65it/s]
  8%|▊         | 160/1939 [00:15<08:16,  3.58it/s]
  8%|▊         | 161/1939 [00:15<09:16,  3.20it/s]
  8%|▊         | 162/1939 [00:16<10:25,  2.84it/s]
  8%|▊         | 163/1939 [00:16<11:09,  2.65it/s]
  8%|▊         | 164/1939 [00:17<11:17,  2.62it/s]
  9%|▊         | 167/1939 [00:17<06:11,  4.77it/s]
  9%|▊         | 169/1939 [00:17<04:49,  6.11it/s]
  9%|▉         | 171/1939 [00:17<03:49,  7.70it/s]
  9%|▉         | 176/1939 [00:17<02:09, 13.67it/s]
  9%|▉         | 180/1939 [00:17<01:36, 18.16it/s]
 10%|▉         | 185/1939 [00:18<01:34, 18.51it/s]
 10%|▉         | 188/1939 [00:18<01:32, 19.03it/s]
 10%|█         | 194/1939 [00:18<01:06, 26.40it/s]
 10%|█         | 199/1939 [00:18<01:04, 27.18it/s]
 10%|█         | 203/1939 [00:19<02:38, 10.93it/s]
 11%|█         | 206/1939 [00:20<03:25,  8.45it/s]
 11%|█         | 209/1939 [00:20<02:54,  9.91it/s]
 11%|█         | 211/1939 [00:20<02:48, 10.24it/s]
 11%|█         | 213/1939 [00:20<02:51, 10.08it/s]
 11%|█         | 215/1939 [00:21<04:13,  6.79it/s]
 11%|█         | 217/1939 [00:21<03:34,  8.03it/s]
 11%|█▏        | 219/1939 [00:21<03:30,  8.16it/s]
 11%|█▏        | 222/1939 [00:21<02:58,  9.62it/s]
 12%|█▏        | 224/1939 [00:21<02:51,  9.99it/s]
 12%|█▏        | 226/1939 [00:22<02:29, 11.46it/s]
 12%|█▏        | 228/1939 [00:22<02:42, 10.52it/s]
 12%|█▏        | 230/1939 [00:22<02:33, 11.16it/s]
 12%|█▏        | 232/1939 [00:22<02:17, 12.41it/s]
 12%|█▏        | 234/1939 [00:22<03:02,  9.32it/s]
 12%|█▏        | 236/1939 [00:23<03:41,  7.68it/s]
 12%|█▏        | 238/1939 [00:23<03:14,  8.73it/s]
 12%|█▏        | 240/1939 [00:23<04:47,  5.91it/s]
 12%|█▏        | 241/1939 [00:24<06:21,  4.45it/s]
 12%|█▏        | 242/1939 [00:24<05:45,  4.91it/s]
 13%|█▎        | 244/1939 [00:24<04:35,  6.16it/s]
 13%|█▎        | 245/1939 [00:25<06:18,  4.47it/s]
 13%|█▎        | 246/1939 [00:25<05:57,  4.73it/s]
 13%|█▎        | 248/1939 [00:25<06:15,  4.50it/s]
 13%|█▎        | 250/1939 [00:26<04:44,  5.93it/s]
 13%|█▎        | 252/1939 [00:26<03:54,  7.20it/s]
 13%|█▎        | 254/1939 [00:26<03:11,  8.79it/s]
 13%|█▎        | 257/1939 [00:26<03:39,  7.67it/s]
 13%|█▎        | 258/1939 [00:26<03:38,  7.70it/s]
 13%|█▎        | 260/1939 [00:26<02:58,  9.41it/s]
 14%|█▎        | 263/1939 [00:27<03:26,  8.10it/s]
 14%|█▎        | 265/1939 [00:27<02:57,  9.43it/s]
 14%|█▍        | 268/1939 [00:27<02:34, 10.82it/s]
 14%|█▍        | 270/1939 [00:27<02:26, 11.41it/s]
 14%|█▍        | 273/1939 [00:28<02:06, 13.19it/s]
 14%|█▍        | 275/1939 [00:28<02:01, 13.65it/s]
 14%|█▍        | 278/1939 [00:28<01:42, 16.26it/s]
 14%|█▍        | 280/1939 [00:28<02:09, 12.80it/s]
 15%|█▍        | 282/1939 [00:29<03:12,  8.59it/s]
 15%|█▍        | 284/1939 [00:29<02:53,  9.54it/s]
 15%|█▍        | 286/1939 [00:29<04:07,  6.69it/s]
 15%|█▍        | 288/1939 [00:30<04:40,  5.88it/s]
 15%|█▌        | 291/1939 [00:30<03:16,  8.40it/s]
 15%|█▌        | 293/1939 [00:30<03:11,  8.59it/s]
 15%|█▌        | 296/1939 [00:30<02:34, 10.61it/s]
 15%|█▌        | 298/1939 [00:30<02:42, 10.09it/s]
 15%|█▌        | 300/1939 [00:31<02:38, 10.37it/s]
 16%|█▌        | 302/1939 [00:31<02:17, 11.88it/s]
 16%|█▌        | 304/1939 [00:31<02:11, 12.40it/s]
 16%|█▌        | 307/1939 [00:31<01:50, 14.75it/s]
 16%|█▌        | 310/1939 [00:31<01:32, 17.68it/s]
 16%|█▌        | 314/1939 [00:31<01:17, 20.99it/s]
 16%|█▋        | 317/1939 [00:32<02:22, 11.40it/s]
 16%|█▋        | 319/1939 [00:32<02:35, 10.45it/s]
 17%|█▋        | 321/1939 [00:32<03:28,  7.76it/s]
 17%|█▋        | 323/1939 [00:33<04:08,  6.49it/s]
 17%|█▋        | 327/1939 [00:33<03:02,  8.81it/s]
 17%|█▋        | 329/1939 [00:33<02:45,  9.73it/s]
 17%|█▋        | 331/1939 [00:33<02:26, 10.95it/s]
 17%|█▋        | 335/1939 [00:33<01:44, 15.37it/s]
 18%|█▊        | 342/1939 [00:34<01:03, 25.04it/s]
 18%|█▊        | 347/1939 [00:34<00:54, 29.15it/s]
 18%|█▊        | 351/1939 [00:34<01:25, 18.61it/s]
 18%|█▊        | 354/1939 [00:35<01:58, 13.37it/s]
 18%|█▊        | 357/1939 [00:35<02:01, 13.06it/s]
 19%|█▊        | 359/1939 [00:35<01:54, 13.84it/s]
 19%|█▊        | 361/1939 [00:35<01:58, 13.34it/s]
 19%|█▊        | 363/1939 [00:35<02:25, 10.85it/s]
 19%|█▉        | 366/1939 [00:36<02:02, 12.85it/s]
 19%|█▉        | 370/1939 [00:36<01:33, 16.78it/s]
 19%|█▉        | 374/1939 [00:36<01:16, 20.37it/s]
 19%|█▉        | 377/1939 [00:36<02:05, 12.42it/s]
 20%|█▉        | 380/1939 [00:36<01:48, 14.35it/s]
 20%|█▉        | 383/1939 [00:37<02:18, 11.27it/s]
 20%|█▉        | 385/1939 [00:37<03:04,  8.44it/s]
 20%|█▉        | 387/1939 [00:37<02:52,  9.00it/s]
 20%|██        | 389/1939 [00:38<03:21,  7.70it/s]
 20%|██        | 391/1939 [00:38<04:24,  5.85it/s]
 20%|██        | 393/1939 [00:39<03:39,  7.05it/s]
 20%|██        | 395/1939 [00:39<04:09,  6.19it/s]
 20%|██        | 396/1939 [00:39<05:08,  5.01it/s]
 20%|██        | 397/1939 [00:39<04:42,  5.46it/s]
 21%|██        | 398/1939 [00:40<05:33,  4.62it/s]
 21%|██        | 401/1939 [00:40<03:23,  7.57it/s]
 21%|██        | 404/1939 [00:40<03:19,  7.68it/s]
 21%|██        | 406/1939 [00:41<04:13,  6.06it/s]
 21%|██        | 411/1939 [00:41<03:26,  7.39it/s]
 21%|██        | 412/1939 [00:41<03:36,  7.05it/s]
 21%|██▏       | 415/1939 [00:42<03:52,  6.55it/s]
 22%|██▏       | 417/1939 [00:43<04:45,  5.34it/s]
 22%|██▏       | 419/1939 [00:43<05:20,  4.74it/s]
 22%|██▏       | 421/1939 [00:43<04:16,  5.93it/s]
 22%|██▏       | 422/1939 [00:44<05:30,  4.59it/s]
 22%|██▏       | 424/1939 [00:44<04:16,  5.90it/s]
 22%|██▏       | 426/1939 [00:44<04:09,  6.06it/s]
 22%|██▏       | 428/1939 [00:45<04:19,  5.82it/s]
 22%|██▏       | 431/1939 [00:45<03:02,  8.27it/s]
 23%|██▎       | 438/1939 [00:45<01:31, 16.47it/s]
 23%|██▎       | 441/1939 [00:45<01:34, 15.85it/s]
 23%|██▎       | 444/1939 [00:45<01:27, 17.01it/s]
 23%|██▎       | 451/1939 [00:45<00:56, 26.47it/s]
 24%|██▎       | 458/1939 [00:45<00:42, 34.47it/s]
 24%|██▍       | 465/1939 [00:45<00:34, 42.18it/s]
 24%|██▍       | 471/1939 [00:46<00:33, 44.47it/s]
 25%|██▍       | 477/1939 [00:46<00:30, 47.57it/s]
 25%|██▍       | 483/1939 [00:46<00:28, 50.43it/s]
 25%|██▌       | 489/1939 [00:46<00:28, 51.67it/s]
 26%|██▌       | 495/1939 [00:46<00:56, 25.36it/s]
 26%|██▌       | 500/1939 [00:47<01:05, 22.02it/s]
 26%|██▌       | 504/1939 [00:47<01:01, 23.30it/s]
 26%|██▌       | 508/1939 [00:47<01:04, 22.05it/s]
 26%|██▋       | 511/1939 [00:47<01:02, 22.78it/s]
 27%|██▋       | 515/1939 [00:47<00:56, 25.13it/s]
 27%|██▋       | 521/1939 [00:47<00:44, 31.97it/s]
 27%|██▋       | 526/1939 [00:48<00:40, 35.07it/s]
 27%|██▋       | 530/1939 [00:48<00:43, 32.23it/s]
 28%|██▊       | 537/1939 [00:48<01:11, 19.64it/s]
 28%|██▊       | 540/1939 [00:48<01:09, 20.13it/s]
 28%|██▊       | 545/1939 [00:48<00:56, 24.59it/s]
 28%|██▊       | 549/1939 [00:49<01:40, 13.78it/s]
 28%|██▊       | 552/1939 [00:50<02:13, 10.39it/s]
 29%|██▊       | 555/1939 [00:50<01:52, 12.25it/s]
 29%|██▉       | 558/1939 [00:50<01:41, 13.61it/s]
 29%|██▉       | 561/1939 [00:50<01:43, 13.27it/s]
 29%|██▉       | 564/1939 [00:50<01:29, 15.32it/s]
 29%|██▉       | 568/1939 [00:50<01:12, 19.02it/s]
 29%|██▉       | 571/1939 [00:51<01:54, 11.90it/s]
 30%|██▉       | 573/1939 [00:51<02:23,  9.51it/s]
 30%|██▉       | 575/1939 [00:52<03:18,  6.87it/s]
 30%|██▉       | 578/1939 [00:52<02:33,  8.86it/s]
 30%|██▉       | 580/1939 [00:52<03:12,  7.06it/s]
 30%|███       | 582/1939 [00:53<03:48,  5.95it/s]
 30%|███       | 584/1939 [00:53<04:15,  5.31it/s]
 30%|███       | 586/1939 [00:54<04:39,  4.85it/s]
 30%|███       | 588/1939 [00:54<03:40,  6.13it/s]
 30%|███       | 590/1939 [00:54<03:54,  5.76it/s]
 30%|███       | 591/1939 [00:55<03:59,  5.62it/s]
 31%|███       | 592/1939 [00:55<03:50,  5.85it/s]
 31%|███       | 593/1939 [00:55<03:54,  5.75it/s]
 31%|███       | 595/1939 [00:55<03:09,  7.10it/s]
 31%|███       | 596/1939 [00:56<04:29,  4.99it/s]
 31%|███       | 598/1939 [00:56<03:14,  6.90it/s]
 31%|███       | 600/1939 [00:56<04:46,  4.68it/s]
 31%|███       | 601/1939 [00:57<04:54,  4.55it/s]
 31%|███       | 603/1939 [00:57<03:38,  6.13it/s]
 31%|███       | 605/1939 [00:57<02:55,  7.58it/s]
 31%|███▏      | 607/1939 [00:57<02:53,  7.67it/s]
 31%|███▏      | 608/1939 [00:57<03:14,  6.83it/s]
 31%|███▏      | 609/1939 [00:58<04:19,  5.12it/s]
 32%|███▏      | 611/1939 [00:58<03:56,  5.61it/s]
 32%|███▏      | 612/1939 [00:58<04:17,  5.15it/s]
 32%|███▏      | 613/1939 [00:59<04:43,  4.67it/s]
 32%|███▏      | 614/1939 [00:59<06:04,  3.63it/s]
 32%|███▏      | 615/1939 [00:59<06:51,  3.22it/s]
 32%|███▏      | 616/1939 [01:00<07:56,  2.78it/s]
 32%|███▏      | 617/1939 [01:00<08:23,  2.62it/s]
 32%|███▏      | 618/1939 [01:01<09:02,  2.44it/s]
 32%|███▏      | 620/1939 [01:01<07:49,  2.81it/s]
 32%|███▏      | 621/1939 [01:02<07:16,  3.02it/s]
 32%|███▏      | 623/1939 [01:02<04:45,  4.62it/s]
 32%|███▏      | 627/1939 [01:02<02:35,  8.46it/s]
 32%|███▏      | 630/1939 [01:02<02:21,  9.27it/s]
 33%|███▎      | 632/1939 [01:02<02:26,  8.92it/s]
 33%|███▎      | 635/1939 [01:03<01:54, 11.38it/s]
 33%|███▎      | 637/1939 [01:03<02:26,  8.88it/s]
 33%|███▎      | 641/1939 [01:03<01:42, 12.70it/s]
 33%|███▎      | 643/1939 [01:03<01:52, 11.51it/s]
 33%|███▎      | 646/1939 [01:03<01:41, 12.71it/s]
 33%|███▎      | 649/1939 [01:04<02:14,  9.59it/s]
 34%|███▎      | 651/1939 [01:04<02:33,  8.41it/s]
 34%|███▎      | 653/1939 [01:04<02:16,  9.42it/s]
 34%|███▍      | 655/1939 [01:05<01:58, 10.81it/s]
 34%|███▍      | 657/1939 [01:05<01:59, 10.71it/s]
 34%|███▍      | 659/1939 [01:05<02:27,  8.68it/s]
 34%|███▍      | 662/1939 [01:05<01:51, 11.42it/s]
 34%|███▍      | 666/1939 [01:06<02:10,  9.74it/s]
 34%|███▍      | 668/1939 [01:06<01:57, 10.83it/s]
 35%|███▍      | 672/1939 [01:06<02:15,  9.38it/s]
 35%|███▍      | 674/1939 [01:06<02:01, 10.44it/s]
 35%|███▍      | 676/1939 [01:07<02:42,  7.75it/s]
 35%|███▍      | 678/1939 [01:07<02:30,  8.40it/s]
 35%|███▌      | 680/1939 [01:08<03:15,  6.43it/s]
 35%|███▌      | 682/1939 [01:08<02:43,  7.67it/s]
 35%|███▌      | 684/1939 [01:08<03:26,  6.07it/s]
 35%|███▌      | 687/1939 [01:09<03:37,  5.75it/s]
 36%|███▌      | 689/1939 [01:09<04:09,  5.02it/s]
 36%|███▌      | 692/1939 [01:09<02:56,  7.05it/s]
 36%|███▌      | 696/1939 [01:10<01:57, 10.58it/s]
 36%|███▋      | 704/1939 [01:10<01:02, 19.65it/s]
 37%|███▋      | 711/1939 [01:10<00:45, 26.98it/s]
 37%|███▋      | 717/1939 [01:10<00:38, 31.99it/s]
 37%|███▋      | 724/1939 [01:10<00:31, 39.03it/s]
 38%|███▊      | 730/1939 [01:10<00:53, 22.70it/s]
 38%|███▊      | 734/1939 [01:11<01:25, 14.05it/s]
 38%|███▊      | 737/1939 [01:11<01:18, 15.28it/s]
 38%|███▊      | 740/1939 [01:11<01:12, 16.58it/s]
 38%|███▊      | 743/1939 [01:12<01:33, 12.77it/s]
 38%|███▊      | 746/1939 [01:12<01:22, 14.50it/s]
 39%|███▊      | 751/1939 [01:12<01:08, 17.24it/s]
 39%|███▉      | 754/1939 [01:12<01:08, 17.31it/s]
 39%|███▉      | 757/1939 [01:13<01:40, 11.79it/s]
 39%|███▉      | 760/1939 [01:13<02:13,  8.82it/s]
 39%|███▉      | 763/1939 [01:14<02:30,  7.79it/s]
 39%|███▉      | 765/1939 [01:14<02:12,  8.86it/s]
 40%|███▉      | 767/1939 [01:15<03:49,  5.10it/s]
 40%|███▉      | 768/1939 [01:15<04:40,  4.17it/s]
 40%|███▉      | 769/1939 [01:16<05:32,  3.52it/s]
 40%|███▉      | 770/1939 [01:16<06:16,  3.11it/s]
 40%|███▉      | 772/1939 [01:17<05:59,  3.25it/s]
 40%|███▉      | 773/1939 [01:17<06:37,  2.94it/s]
 40%|████      | 776/1939 [01:18<05:18,  3.65it/s]
 40%|████      | 777/1939 [01:19<06:01,  3.22it/s]
 40%|████      | 779/1939 [01:19<05:00,  3.86it/s]
 40%|████      | 780/1939 [01:19<05:15,  3.67it/s]
 40%|████      | 782/1939 [01:19<03:44,  5.14it/s]
 40%|████      | 784/1939 [01:20<03:57,  4.87it/s]
 41%|████      | 787/1939 [01:20<03:55,  4.89it/s]
 41%|████      | 789/1939 [01:21<04:18,  4.44it/s]
 41%|████      | 791/1939 [01:21<04:43,  4.05it/s]
 41%|████      | 793/1939 [01:22<03:42,  5.15it/s]
 41%|████      | 794/1939 [01:22<03:28,  5.50it/s]
 41%|████      | 796/1939 [01:22<03:08,  6.05it/s]
 41%|████      | 798/1939 [01:22<02:35,  7.34it/s]
 41%|████▏     | 800/1939 [01:22<02:08,  8.85it/s]
 41%|████▏     | 802/1939 [01:22<01:54,  9.94it/s]
 41%|████▏     | 804/1939 [01:23<02:37,  7.20it/s]
 42%|████▏     | 806/1939 [01:23<02:19,  8.15it/s]
 42%|████▏     | 808/1939 [01:23<01:54,  9.87it/s]
 42%|████▏     | 810/1939 [01:24<02:25,  7.78it/s]
 42%|████▏     | 812/1939 [01:24<03:09,  5.96it/s]
 42%|████▏     | 813/1939 [01:24<03:06,  6.04it/s]
 42%|████▏     | 814/1939 [01:24<03:04,  6.09it/s]
 42%|████▏     | 816/1939 [01:25<02:59,  6.26it/s]
 42%|████▏     | 817/1939 [01:25<03:35,  5.21it/s]
 42%|████▏     | 818/1939 [01:25<03:20,  5.60it/s]
 42%|████▏     | 819/1939 [01:25<03:21,  5.57it/s]
 42%|████▏     | 820/1939 [01:26<03:47,  4.92it/s]
 42%|████▏     | 821/1939 [01:26<04:12,  4.42it/s]
 42%|████▏     | 823/1939 [01:26<03:29,  5.33it/s]
 43%|████▎     | 825/1939 [01:26<02:41,  6.89it/s]
 43%|████▎     | 826/1939 [01:26<02:49,  6.55it/s]
 43%|████▎     | 828/1939 [01:27<02:21,  7.86it/s]
 43%|████▎     | 830/1939 [01:27<02:04,  8.89it/s]
 43%|████▎     | 834/1939 [01:27<01:31, 12.10it/s]
 43%|████▎     | 838/1939 [01:27<01:07, 16.42it/s]
 43%|████▎     | 840/1939 [01:27<01:18, 14.04it/s]
 44%|████▎     | 844/1939 [01:28<01:02, 17.53it/s]
 44%|████▎     | 848/1939 [01:28<00:51, 21.14it/s]
 44%|████▍     | 851/1939 [01:28<00:49, 22.19it/s]
 44%|████▍     | 854/1939 [01:28<00:50, 21.50it/s]
 44%|████▍     | 857/1939 [01:28<01:23, 12.89it/s]
 44%|████▍     | 859/1939 [01:28<01:20, 13.35it/s]
 44%|████▍     | 861/1939 [01:29<01:32, 11.69it/s]
 45%|████▍     | 863/1939 [01:29<01:33, 11.49it/s]
 45%|████▍     | 865/1939 [01:29<01:31, 11.78it/s]
 45%|████▍     | 867/1939 [01:29<01:22, 12.99it/s]
 45%|████▍     | 871/1939 [01:29<00:58, 18.39it/s]
 45%|████▌     | 876/1939 [01:29<00:42, 24.97it/s]
 45%|████▌     | 879/1939 [01:29<00:40, 26.11it/s]
 46%|████▌     | 886/1939 [01:30<00:29, 35.70it/s]
 46%|████▌     | 892/1939 [01:30<00:25, 41.85it/s]
 46%|████▋     | 898/1939 [01:30<00:22, 45.50it/s]
 47%|████▋     | 903/1939 [01:31<01:04, 16.09it/s]
 47%|████▋     | 907/1939 [01:31<00:57, 18.00it/s]
 47%|████▋     | 911/1939 [01:31<01:09, 14.85it/s]
 47%|████▋     | 914/1939 [01:31<01:08, 14.96it/s]
 47%|████▋     | 917/1939 [01:32<01:10, 14.54it/s]
 47%|████▋     | 920/1939 [01:32<01:44,  9.73it/s]
 48%|████▊     | 922/1939 [01:32<01:34, 10.78it/s]
 48%|████▊     | 927/1939 [01:33<01:42,  9.86it/s]
 48%|████▊     | 929/1939 [01:33<01:33, 10.78it/s]
 48%|████▊     | 931/1939 [01:34<02:57,  5.68it/s]
 48%|████▊     | 933/1939 [01:34<02:32,  6.58it/s]
 48%|████▊     | 936/1939 [01:34<01:52,  8.89it/s]
 49%|████▊     | 944/1939 [01:34<00:57, 17.24it/s]
 49%|████▉     | 951/1939 [01:34<00:39, 24.96it/s]
 49%|████▉     | 956/1939 [01:35<00:38, 25.59it/s]
 50%|████▉     | 960/1939 [01:35<00:36, 26.93it/s]
 50%|████▉     | 964/1939 [01:35<00:36, 26.58it/s]
 50%|████▉     | 968/1939 [01:35<00:53, 18.24it/s]
 50%|█████     | 971/1939 [01:36<01:30, 10.67it/s]
 50%|█████     | 973/1939 [01:37<02:18,  6.96it/s]
 50%|█████     | 975/1939 [01:37<02:05,  7.68it/s]
 50%|█████     | 977/1939 [01:37<02:16,  7.03it/s]
 50%|█████     | 979/1939 [01:37<01:56,  8.25it/s]
 51%|█████     | 981/1939 [01:38<02:19,  6.86it/s]
 51%|█████     | 983/1939 [01:38<02:15,  7.04it/s]
 51%|█████     | 984/1939 [01:38<02:21,  6.74it/s]
 51%|█████     | 986/1939 [01:38<01:55,  8.27it/s]
 51%|█████     | 988/1939 [01:38<01:40,  9.50it/s]
 51%|█████     | 991/1939 [01:39<01:58,  8.03it/s]
 51%|█████     | 993/1939 [01:39<01:53,  8.36it/s]
 51%|█████▏    | 997/1939 [01:40<01:53,  8.30it/s]
 52%|█████▏    | 999/1939 [01:40<02:24,  6.50it/s]
 52%|█████▏    | 1002/1939 [01:41<02:30,  6.22it/s]
 52%|█████▏    | 1005/1939 [01:41<02:33,  6.08it/s]
 52%|█████▏    | 1007/1939 [01:42<02:50,  5.46it/s]
 52%|█████▏    | 1009/1939 [01:42<02:38,  5.87it/s]
 52%|█████▏    | 1010/1939 [01:42<03:15,  4.75it/s]
 52%|█████▏    | 1011/1939 [01:43<03:49,  4.05it/s]
 52%|█████▏    | 1012/1939 [01:43<04:23,  3.52it/s]
 52%|█████▏    | 1013/1939 [01:43<04:05,  3.78it/s]
 52%|█████▏    | 1014/1939 [01:44<04:36,  3.35it/s]
 52%|█████▏    | 1015/1939 [01:44<04:06,  3.74it/s]
 52%|█████▏    | 1016/1939 [01:44<04:57,  3.10it/s]
 53%|█████▎    | 1018/1939 [01:45<03:12,  4.78it/s]
 53%|█████▎    | 1019/1939 [01:45<04:08,  3.71it/s]
 53%|█████▎    | 1021/1939 [01:45<03:10,  4.83it/s]
 53%|█████▎    | 1022/1939 [01:46<03:57,  3.87it/s]
 53%|█████▎    | 1024/1939 [01:46<02:43,  5.60it/s]
 53%|█████▎    | 1027/1939 [01:46<02:36,  5.84it/s]
 53%|█████▎    | 1029/1939 [01:46<02:02,  7.41it/s]
 53%|█████▎    | 1031/1939 [01:47<01:53,  8.01it/s]
 53%|█████▎    | 1033/1939 [01:47<01:38,  9.24it/s]
 54%|█████▎    | 1038/1939 [01:47<00:57, 15.54it/s]
 54%|█████▍    | 1044/1939 [01:47<00:38, 23.46it/s]
 54%|█████▍    | 1048/1939 [01:48<01:01, 14.57it/s]
 54%|█████▍    | 1051/1939 [01:48<01:34,  9.43it/s]
 54%|█████▍    | 1053/1939 [01:49<02:38,  5.59it/s]
 54%|█████▍    | 1055/1939 [01:50<02:57,  4.97it/s]
 55%|█████▍    | 1057/1939 [01:50<03:27,  4.24it/s]
 55%|█████▍    | 1059/1939 [01:51<03:30,  4.17it/s]
 55%|█████▍    | 1060/1939 [01:51<03:27,  4.23it/s]
 55%|█████▍    | 1063/1939 [01:51<02:17,  6.39it/s]
 55%|█████▌    | 1068/1939 [01:52<01:56,  7.49it/s]
 55%|█████▌    | 1070/1939 [01:52<01:52,  7.72it/s]
 55%|█████▌    | 1073/1939 [01:52<01:27,  9.90it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 308.63it/s]
 50%|█████     | 151/300 [07:52<1:31:37, 36.90s/it]

[[np.int64(0), False, 8], [np.int64(1), False, 13], [np.int64(2), False, 3], [np.int64(3), False, 12], [np.int64(4), False, 5], [np.int64(5), False, 1], [np.int64(6), False, 12], [np.int64(7), False, 5], [np.int64(8), False, 13], [np.int64(9), False, 1], [np.int64(10), False, 13], [np.int64(11), False, 5]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.6990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0687, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.6896, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1522, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [07:52<1:12:45, 29.50s/it]

tensor(12.6847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2161, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [07:52<45:39, 18.76s/it]

tensor(12.6817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2550, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2754, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2835, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [07:52<29:40, 12.36s/it]

tensor(12.6635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2972, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6529, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3084, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [07:53<19:42,  8.33s/it]

tensor(12.6421, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3220, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [07:53<13:17,  5.70s/it]

tensor(12.6320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3384, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3597, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3831, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [07:53<09:03,  3.94s/it]

tensor(12.6056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4017, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4270, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [07:53<06:14,  2.75s/it]

tensor(12.5911, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4497, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [07:53<04:19,  1.94s/it]

tensor(12.5843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4747, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4941, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5098, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [07:54<03:01,  1.38s/it]

tensor(12.5600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5213, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5517, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5344, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [07:54<02:08,  1.01it/s]

tensor(12.5442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5487, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [07:54<01:31,  1.40it/s]

tensor(12.5375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5565, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5819, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [07:54<01:06,  1.89it/s]

tensor(12.5188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5898, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5969, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [07:54<00:49,  2.51it/s]

tensor(12.5073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6116, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [07:55<00:37,  3.26it/s]

tensor(12.5020, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6197, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4970, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6280, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6354, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [07:55<00:29,  4.13it/s]

tensor(12.4873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6498, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6545, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [07:55<00:23,  5.06it/s]

tensor(12.4781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6597, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [07:55<00:19,  6.00it/s]

tensor(12.4735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6630, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6649, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6627, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [07:55<00:16,  6.90it/s]

tensor(12.4605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6688, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6701, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [07:55<00:14,  7.73it/s]

tensor(12.4524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6712, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [07:56<00:13,  8.42it/s]

tensor(12.4487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6695, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6740, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4410, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6773, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [07:56<00:12,  8.97it/s]

tensor(12.4376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6784, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6786, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [07:56<00:11,  9.40it/s]

tensor(12.4304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6804, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [07:56<00:10,  9.77it/s]

tensor(12.4272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6824, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6832, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6855, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [07:56<00:10, 10.03it/s]

tensor(12.4175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6874, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6874, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [07:57<00:09, 10.24it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([178, 186, 162,  77,  83, 157, 218, 120,  33, 132,  75,  21, 396, 101])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:12, 26.88it/s]
  0%|          | 8/1939 [00:00<00:51, 37.53it/s]
  1%|          | 14/1939 [00:00<00:43, 44.17it/s]
  1%|          | 19/1939 [00:00<00:41, 46.04it/s]
  1%|▏         | 25/1939 [00:00<00:38, 49.30it/s]
  2%|▏         | 30/1939 [00:00<00:50, 38.04it/s]
  2%|▏         | 35/1939 [00:00<00:57, 33.38it/s]
  2%|▏         | 39/1939 [00:01<01:04, 29.31it/s]
  2%|▏         | 43/1939 [00:03<05:22,  5.87it/s]
  2%|▏         | 46/1939 [00:03<04:30,  7.01it/s]
  3%|▎         | 49/1939 [00:04<06:19,  4.99it/s]
  3%|▎         | 51/1939 [00:04<05:26,  5.78it/s]
  3%|▎         | 53/1939 [00:05<07:58,  3.94it/s]
  3%|▎         | 55/1939 [00:05<06:39,  4.72it/s]
  3%|▎         | 58/1939 [00:06<08:08,  3.85it/s]
  3%|▎         | 60/1939 [00:07<06:32,  4.78it/s]
  3%|▎         | 66/1939 [00:08<06:14,  5.00it/s]
  4%|▎         | 68/1939 [00:08<05:20,  5.83it/s]
  4%|▍         | 73/1939 [00:09<05:54,  5.26it/s]
 67%|██████▋   | 200/300 [08:09<00:09, 10.24it/s]
  4%|▍         | 78/1939 [00:10<06:33,  4.73it/s]
  4%|▍         | 80/1939 [00:11<07:12,  4.30it/s]
  4%|▍         | 82/1939 [00:12<09:50,  3.15it/s]
  4%|▍         | 84/1939 [00:13<11:21,  2.72it/s]
  4%|▍         | 86/1939 [00:14<12:39,  2.44it/s]
  4%|▍         | 87/1939 [00:14<13:44,  2.25it/s]
  5%|▍         | 88/1939 [00:15<11:47,  2.62it/s]
  5%|▍         | 94/1939 [00:16<08:00,  3.84it/s]
  5%|▍         | 96/1939 [00:16<06:36,  4.64it/s]
  5%|▌         | 100/1939 [00:16<05:31,  5.55it/s]
  5%|▌         | 102/1939 [00:16<04:41,  6.51it/s]
  5%|▌         | 105/1939 [00:17<04:42,  6.49it/s]
  6%|▌         | 108/1939 [00:17<03:39,  8.35it/s]
  6%|▌         | 111/1939 [00:17<02:58, 10.25it/s]
  6%|▌         | 114/1939 [00:17<02:23, 12.75it/s]
  6%|▌         | 116/1939 [00:18<03:19,  9.12it/s]
  6%|▌         | 118/1939 [00:18<04:51,  6.25it/s]
  6%|▌         | 120/1939 [00:19<06:41,  4.53it/s]
  6%|▌         | 121/1939 [00:20<08:32,  3.55it/s]
  6%|▋         | 123/1939 [00:20<06:26,  4.70it/s]
  7%|▋         | 128/1939 [00:20<04:48,  6.27it/s]
  7%|▋         | 130/1939 [00:21<04:13,  7.14it/s]
  7%|▋         | 132/1939 [00:21<06:41,  4.50it/s]
  7%|▋         | 134/1939 [00:22<05:27,  5.51it/s]
  7%|▋         | 136/1939 [00:23<08:41,  3.46it/s]
  7%|▋         | 137/1939 [00:24<12:01,  2.50it/s]
  7%|▋         | 139/1939 [00:24<08:49,  3.40it/s]
  7%|▋         | 143/1939 [00:24<04:58,  6.02it/s]
  7%|▋         | 145/1939 [00:25<07:36,  3.93it/s]
  8%|▊         | 148/1939 [00:25<05:23,  5.54it/s]
  8%|▊         | 151/1939 [00:26<07:08,  4.17it/s]
  8%|▊         | 153/1939 [00:27<09:14,  3.22it/s]
  8%|▊         | 156/1939 [00:27<06:30,  4.57it/s]
  8%|▊         | 158/1939 [00:29<12:23,  2.39it/s]
  8%|▊         | 159/1939 [00:30<13:18,  2.23it/s]
  8%|▊         | 160/1939 [00:31<14:21,  2.07it/s]
  8%|▊         | 161/1939 [00:31<15:14,  1.94it/s]
  8%|▊         | 162/1939 [00:32<16:50,  1.76it/s]
  8%|▊         | 163/1939 [00:33<19:36,  1.51it/s]
  8%|▊         | 164/1939 [00:34<21:34,  1.37it/s]
  9%|▊         | 167/1939 [00:34<10:53,  2.71it/s]
  9%|▉         | 170/1939 [00:35<09:32,  3.09it/s]
  9%|▉         | 172/1939 [00:35<07:14,  4.07it/s]
  9%|▉         | 174/1939 [00:35<05:37,  5.23it/s]
  9%|▉         | 180/1939 [00:35<02:46, 10.55it/s]
 10%|▉         | 186/1939 [00:35<01:46, 16.49it/s]
 10%|▉         | 193/1939 [00:35<01:12, 23.93it/s]
 10%|█         | 199/1939 [00:36<00:59, 29.41it/s]
 11%|█         | 204/1939 [00:37<02:24, 12.00it/s]
 11%|█         | 208/1939 [00:37<03:12,  8.98it/s]
 11%|█         | 211/1939 [00:38<02:56,  9.77it/s]
 11%|█         | 215/1939 [00:39<04:12,  6.82it/s]
 11%|█         | 217/1939 [00:39<03:44,  7.66it/s]
 11%|█▏        | 221/1939 [00:39<02:46, 10.29it/s]
 12%|█▏        | 226/1939 [00:39<01:58, 14.41it/s]
 12%|█▏        | 229/1939 [00:40<03:12,  8.89it/s]
 12%|█▏        | 232/1939 [00:40<02:46, 10.26it/s]
 12%|█▏        | 235/1939 [00:41<03:57,  7.17it/s]
 12%|█▏        | 237/1939 [00:41<05:00,  5.66it/s]
 12%|█▏        | 239/1939 [00:42<06:04,  4.67it/s]
 12%|█▏        | 241/1939 [00:43<06:40,  4.24it/s]
 12%|█▏        | 242/1939 [00:43<09:37,  2.94it/s]
 13%|█▎        | 244/1939 [00:44<07:21,  3.84it/s]
 13%|█▎        | 245/1939 [00:44<08:29,  3.32it/s]
 13%|█▎        | 246/1939 [00:45<09:03,  3.12it/s]
 13%|█▎        | 248/1939 [00:45<09:33,  2.95it/s]
 13%|█▎        | 250/1939 [00:45<06:47,  4.14it/s]
 13%|█▎        | 255/1939 [00:45<03:21,  8.34it/s]
 13%|█▎        | 258/1939 [00:46<05:02,  5.55it/s]
 13%|█▎        | 260/1939 [00:47<07:08,  3.92it/s]
 14%|█▎        | 263/1939 [00:49<08:15,  3.38it/s]
 14%|█▎        | 265/1939 [00:49<06:38,  4.20it/s]
 14%|█▍        | 268/1939 [00:49<04:49,  5.77it/s]
 14%|█▍        | 272/1939 [00:49<03:11,  8.70it/s]
 14%|█▍        | 277/1939 [00:49<02:06, 13.10it/s]
 14%|█▍        | 281/1939 [00:50<03:51,  7.17it/s]
 15%|█▍        | 284/1939 [00:50<03:17,  8.39it/s]
 15%|█▍        | 287/1939 [00:51<05:14,  5.25it/s]
 15%|█▌        | 291/1939 [00:52<03:42,  7.42it/s]
 15%|█▌        | 294/1939 [00:53<05:10,  5.29it/s]
 15%|█▌        | 297/1939 [00:53<04:01,  6.81it/s]
 16%|█▌        | 303/1939 [00:53<02:29, 10.94it/s]
 16%|█▌        | 307/1939 [00:53<02:01, 13.44it/s]
 16%|█▌        | 312/1939 [00:53<01:31, 17.79it/s]
 16%|█▋        | 316/1939 [00:54<02:47,  9.69it/s]
 16%|█▋        | 319/1939 [00:54<02:31, 10.72it/s]
 17%|█▋        | 322/1939 [00:55<04:59,  5.39it/s]
 17%|█▋        | 324/1939 [00:56<04:19,  6.22it/s]
 17%|█▋        | 326/1939 [00:56<03:42,  7.24it/s]
 17%|█▋        | 328/1939 [00:56<03:09,  8.50it/s]
 17%|█▋        | 332/1939 [00:56<02:11, 12.27it/s]
 17%|█▋        | 339/1939 [00:56<01:17, 20.58it/s]
 18%|█▊        | 346/1939 [00:56<00:55, 28.69it/s]
 18%|█▊        | 351/1939 [00:57<02:05, 12.68it/s]
 18%|█▊        | 355/1939 [00:58<03:34,  7.40it/s]
 18%|█▊        | 358/1939 [00:58<03:06,  8.49it/s]
 19%|█▊        | 361/1939 [00:59<02:41,  9.77it/s]
 19%|█▉        | 364/1939 [00:59<02:14, 11.67it/s]
 19%|█▉        | 367/1939 [00:59<02:00, 13.08it/s]
 19%|█▉        | 372/1939 [00:59<01:26, 18.18it/s]
 19%|█▉        | 376/1939 [01:00<03:14,  8.04it/s]
 20%|█▉        | 379/1939 [01:00<02:43,  9.54it/s]
 20%|█▉        | 382/1939 [01:01<04:26,  5.84it/s]
 20%|█▉        | 384/1939 [01:02<06:16,  4.13it/s]
 20%|█▉        | 386/1939 [01:02<05:18,  4.87it/s]
 20%|██        | 388/1939 [01:03<06:54,  3.74it/s]
 20%|██        | 390/1939 [01:04<06:31,  3.96it/s]
 20%|██        | 391/1939 [01:04<07:24,  3.48it/s]
 20%|██        | 392/1939 [01:04<06:35,  3.91it/s]
 20%|██        | 393/1939 [01:05<08:29,  3.04it/s]
 20%|██        | 394/1939 [01:06<09:43,  2.65it/s]
 20%|██        | 396/1939 [01:06<07:50,  3.28it/s]
 21%|██        | 398/1939 [01:06<07:25,  3.46it/s]
 21%|██        | 400/1939 [01:07<05:22,  4.78it/s]
 21%|██        | 404/1939 [01:08<06:09,  4.15it/s]
 21%|██        | 405/1939 [01:09<09:22,  2.73it/s]
 21%|██        | 407/1939 [01:09<08:30,  3.00it/s]
 21%|██        | 409/1939 [01:09<06:21,  4.01it/s]
 21%|██        | 411/1939 [01:10<08:07,  3.13it/s]
 21%|██▏       | 413/1939 [01:10<06:09,  4.13it/s]
 21%|██▏       | 415/1939 [01:11<08:07,  3.12it/s]
 21%|██▏       | 416/1939 [01:12<07:11,  3.53it/s]
 22%|██▏       | 417/1939 [01:12<07:01,  3.61it/s]
 22%|██▏       | 419/1939 [01:12<06:07,  4.13it/s]
 22%|██▏       | 422/1939 [01:13<04:57,  5.09it/s]
 22%|██▏       | 424/1939 [01:13<03:52,  6.52it/s]
 22%|██▏       | 426/1939 [01:13<04:48,  5.24it/s]
 22%|██▏       | 428/1939 [01:14<05:27,  4.62it/s]
 22%|██▏       | 431/1939 [01:14<03:46,  6.67it/s]
 23%|██▎       | 439/1939 [01:14<01:43, 14.53it/s]
 23%|██▎       | 445/1939 [01:14<01:14, 20.14it/s]
 23%|██▎       | 451/1939 [01:14<00:56, 26.11it/s]
 24%|██▎       | 458/1939 [01:14<00:44, 33.50it/s]
 24%|██▍       | 463/1939 [01:15<00:47, 31.03it/s]
 24%|██▍       | 469/1939 [01:15<00:40, 36.67it/s]
 24%|██▍       | 474/1939 [01:15<00:37, 39.18it/s]
 25%|██▍       | 479/1939 [01:15<00:37, 38.81it/s]
 25%|██▌       | 486/1939 [01:15<00:31, 45.58it/s]
 25%|██▌       | 492/1939 [01:15<00:50, 28.93it/s]
 26%|██▌       | 497/1939 [01:16<00:57, 25.10it/s]
 26%|██▌       | 503/1939 [01:16<00:47, 30.08it/s]
 26%|██▋       | 509/1939 [01:16<00:40, 35.44it/s]
 27%|██▋       | 514/1939 [01:17<01:16, 18.71it/s]
 27%|██▋       | 518/1939 [01:17<01:07, 21.08it/s]
 27%|██▋       | 526/1939 [01:17<00:47, 29.94it/s]
 27%|██▋       | 531/1939 [01:17<00:43, 32.15it/s]
 28%|██▊       | 536/1939 [01:17<00:39, 35.37it/s]
 28%|██▊       | 541/1939 [01:18<02:10, 10.74it/s]
 28%|██▊       | 546/1939 [01:19<02:06, 11.05it/s]
 28%|██▊       | 549/1939 [01:20<03:31,  6.59it/s]
 28%|██▊       | 551/1939 [01:21<04:10,  5.55it/s]
 29%|██▊       | 553/1939 [01:21<03:40,  6.28it/s]
 29%|██▊       | 555/1939 [01:21<03:10,  7.26it/s]
 29%|██▊       | 557/1939 [01:21<03:40,  6.28it/s]
 29%|██▉       | 559/1939 [01:21<03:04,  7.47it/s]
 29%|██▉       | 563/1939 [01:21<02:05, 10.96it/s]
 29%|██▉       | 569/1939 [01:22<01:19, 17.29it/s]
 29%|██▉       | 572/1939 [01:23<02:46,  8.19it/s]
 30%|██▉       | 575/1939 [01:24<04:46,  4.76it/s]
 30%|██▉       | 577/1939 [01:24<04:11,  5.41it/s]
 30%|██▉       | 579/1939 [01:25<05:58,  3.80it/s]
 30%|██▉       | 581/1939 [01:25<04:51,  4.65it/s]
 30%|███       | 583/1939 [01:26<05:17,  4.27it/s]
 30%|███       | 584/1939 [01:26<05:54,  3.82it/s]
 30%|███       | 586/1939 [01:27<06:33,  3.44it/s]
 30%|███       | 589/1939 [01:28<07:09,  3.14it/s]
 30%|███       | 591/1939 [01:29<06:57,  3.23it/s]
 31%|███       | 592/1939 [01:29<08:06,  2.77it/s]
 31%|███       | 594/1939 [01:29<05:55,  3.79it/s]
 31%|███       | 596/1939 [01:30<06:09,  3.63it/s]
 31%|███       | 599/1939 [01:31<07:09,  3.12it/s]
 31%|███       | 600/1939 [01:32<07:54,  2.82it/s]
 31%|███       | 601/1939 [01:32<09:51,  2.26it/s]
 31%|███       | 603/1939 [01:33<07:06,  3.14it/s]
 31%|███▏      | 607/1939 [01:33<04:44,  4.69it/s]
 31%|███▏      | 608/1939 [01:33<04:54,  4.53it/s]
 31%|███▏      | 609/1939 [01:34<05:51,  3.78it/s]
 32%|███▏      | 611/1939 [01:35<06:59,  3.17it/s]
 32%|███▏      | 612/1939 [01:35<08:13,  2.69it/s]
 32%|███▏      | 613/1939 [01:36<09:23,  2.35it/s]
 32%|███▏      | 614/1939 [01:36<09:48,  2.25it/s]
 32%|███▏      | 615/1939 [01:37<10:59,  2.01it/s]
 32%|███▏      | 616/1939 [01:37<10:11,  2.16it/s]
 32%|███▏      | 617/1939 [01:38<10:12,  2.16it/s]
 32%|███▏      | 618/1939 [01:38<11:02,  1.99it/s]
 32%|███▏      | 620/1939 [01:39<08:45,  2.51it/s]
 32%|███▏      | 621/1939 [01:39<08:38,  2.54it/s]
 32%|███▏      | 623/1939 [01:39<05:36,  3.91it/s]
 32%|███▏      | 626/1939 [01:40<03:21,  6.50it/s]
 32%|███▏      | 629/1939 [01:41<04:46,  4.57it/s]
 33%|███▎      | 631/1939 [01:41<05:24,  4.03it/s]
 33%|███▎      | 632/1939 [01:42<05:55,  3.68it/s]
 33%|███▎      | 635/1939 [01:42<03:53,  5.57it/s]
 33%|███▎      | 637/1939 [01:42<05:04,  4.27it/s]
 33%|███▎      | 639/1939 [01:43<03:58,  5.45it/s]
 33%|███▎      | 641/1939 [01:43<03:32,  6.10it/s]
 33%|███▎      | 643/1939 [01:44<04:53,  4.41it/s]
 33%|███▎      | 646/1939 [01:44<03:21,  6.42it/s]
 33%|███▎      | 649/1939 [01:44<03:28,  6.19it/s]
 34%|███▎      | 651/1939 [01:45<04:14,  5.07it/s]
 34%|███▎      | 654/1939 [01:46<05:08,  4.17it/s]
 34%|███▍      | 656/1939 [01:47<06:43,  3.18it/s]
 34%|███▍      | 658/1939 [01:48<08:02,  2.65it/s]
 34%|███▍      | 660/1939 [01:48<06:17,  3.39it/s]
 34%|███▍      | 662/1939 [01:48<04:50,  4.39it/s]
 34%|███▍      | 665/1939 [01:49<05:55,  3.58it/s]
 34%|███▍      | 666/1939 [01:50<08:06,  2.62it/s]
 35%|███▍      | 669/1939 [01:50<05:14,  4.04it/s]
 35%|███▍      | 672/1939 [01:51<05:09,  4.09it/s]
 35%|███▍      | 673/1939 [01:52<05:48,  3.63it/s]
 35%|███▍      | 674/1939 [01:52<05:13,  4.04it/s]
 35%|███▍      | 676/1939 [01:52<05:45,  3.65it/s]
 35%|███▍      | 677/1939 [01:52<05:05,  4.13it/s]
 35%|███▌      | 679/1939 [01:53<03:48,  5.51it/s]
 35%|███▌      | 680/1939 [01:54<06:58,  3.01it/s]
 35%|███▌      | 683/1939 [01:55<07:36,  2.75it/s]
 35%|███▌      | 685/1939 [01:55<05:40,  3.69it/s]
 35%|███▌      | 687/1939 [01:56<06:32,  3.19it/s]
 36%|███▌      | 689/1939 [01:56<06:45,  3.08it/s]
 36%|███▌      | 691/1939 [01:57<05:09,  4.03it/s]
 36%|███▌      | 693/1939 [01:58<06:52,  3.02it/s]
 36%|███▌      | 695/1939 [01:58<05:07,  4.05it/s]
 36%|███▌      | 697/1939 [01:58<03:55,  5.26it/s]
 36%|███▌      | 700/1939 [01:58<02:47,  7.38it/s]
 37%|███▋      | 708/1939 [01:58<01:16, 16.02it/s]
 37%|███▋      | 714/1939 [01:58<00:55, 22.08it/s]
 37%|███▋      | 719/1939 [01:58<00:45, 26.81it/s]
 37%|███▋      | 724/1939 [01:58<00:40, 29.75it/s]
 38%|███▊      | 730/1939 [01:59<00:59, 20.19it/s]
 38%|███▊      | 734/1939 [02:00<02:15,  8.88it/s]
 38%|███▊      | 738/1939 [02:00<01:48, 11.11it/s]
 38%|███▊      | 741/1939 [02:01<02:34,  7.76it/s]
 38%|███▊      | 745/1939 [02:01<01:58, 10.07it/s]
 39%|███▊      | 750/1939 [02:01<01:26, 13.72it/s]
 39%|███▉      | 755/1939 [02:02<02:06,  9.36it/s]
 39%|███▉      | 758/1939 [02:02<01:49, 10.77it/s]
 39%|███▉      | 761/1939 [02:03<03:08,  6.25it/s]
 39%|███▉      | 763/1939 [02:04<04:28,  4.38it/s]
 39%|███▉      | 765/1939 [02:04<03:44,  5.23it/s]
 40%|███▉      | 767/1939 [02:07<07:30,  2.60it/s]
 40%|███▉      | 769/1939 [02:08<09:29,  2.06it/s]
 40%|███▉      | 770/1939 [02:09<09:35,  2.03it/s]
 40%|███▉      | 771/1939 [02:09<08:18,  2.34it/s]
 40%|███▉      | 772/1939 [02:10<10:45,  1.81it/s]
 40%|███▉      | 773/1939 [02:10<11:01,  1.76it/s]
 40%|███▉      | 775/1939 [02:11<07:21,  2.64it/s]
 40%|████      | 776/1939 [02:11<07:33,  2.56it/s]
 40%|████      | 777/1939 [02:12<09:11,  2.11it/s]
 40%|████      | 779/1939 [02:13<09:56,  1.94it/s]
 40%|████      | 780/1939 [02:14<12:11,  1.58it/s]
 40%|████      | 783/1939 [02:14<06:37,  2.91it/s]
 40%|████      | 784/1939 [02:15<08:58,  2.15it/s]
 41%|████      | 787/1939 [02:16<08:12,  2.34it/s]
 41%|████      | 789/1939 [02:17<08:50,  2.17it/s]
 41%|████      | 791/1939 [02:18<09:15,  2.07it/s]
 41%|████      | 793/1939 [02:19<06:50,  2.79it/s]
 41%|████      | 797/1939 [02:20<05:59,  3.18it/s]
 41%|████      | 798/1939 [02:20<06:43,  2.83it/s]
 41%|████▏     | 800/1939 [02:20<05:07,  3.70it/s]
 41%|████▏     | 802/1939 [02:20<03:55,  4.82it/s]
 41%|████▏     | 804/1939 [02:22<06:02,  3.13it/s]
 42%|████▏     | 806/1939 [02:23<07:27,  2.53it/s]
 42%|████▏     | 809/1939 [02:24<07:21,  2.56it/s]
 42%|████▏     | 812/1939 [02:25<07:16,  2.58it/s]
 42%|████▏     | 813/1939 [02:26<09:01,  2.08it/s]
 42%|████▏     | 814/1939 [02:27<09:25,  1.99it/s]
 42%|████▏     | 816/1939 [02:27<08:19,  2.25it/s]
 42%|████▏     | 817/1939 [02:28<09:07,  2.05it/s]
 42%|████▏     | 818/1939 [02:28<08:26,  2.21it/s]
 42%|████▏     | 819/1939 [02:29<08:39,  2.15it/s]
 42%|████▏     | 820/1939 [02:29<09:12,  2.02it/s]
 42%|████▏     | 821/1939 [02:30<09:29,  1.96it/s]
 42%|████▏     | 822/1939 [02:31<09:42,  1.92it/s]
 42%|████▏     | 823/1939 [02:31<09:31,  1.95it/s]
 43%|████▎     | 825/1939 [02:31<06:24,  2.90it/s]
 43%|████▎     | 827/1939 [02:31<04:26,  4.18it/s]
 43%|████▎     | 829/1939 [02:32<03:15,  5.68it/s]
 43%|████▎     | 834/1939 [02:32<01:43, 10.72it/s]
 43%|████▎     | 839/1939 [02:32<01:08, 16.10it/s]
 43%|████▎     | 843/1939 [02:32<00:54, 20.06it/s]
 44%|████▎     | 847/1939 [02:32<00:48, 22.57it/s]
 44%|████▍     | 852/1939 [02:32<00:39, 27.29it/s]
 44%|████▍     | 857/1939 [02:33<01:48,  9.98it/s]
 44%|████▍     | 860/1939 [02:33<01:35, 11.30it/s]
 45%|████▍     | 865/1939 [02:34<01:10, 15.24it/s]
 45%|████▍     | 871/1939 [02:34<00:51, 20.81it/s]
 45%|████▌     | 878/1939 [02:34<00:38, 27.78it/s]
 46%|████▌     | 884/1939 [02:34<00:31, 33.35it/s]
 46%|████▌     | 890/1939 [02:34<00:27, 37.69it/s]
 46%|████▋     | 898/1939 [02:34<00:22, 45.85it/s]
 47%|████▋     | 904/1939 [02:36<02:13,  7.77it/s]
 47%|████▋     | 908/1939 [02:37<01:53,  9.12it/s]
 47%|████▋     | 912/1939 [02:39<03:28,  4.92it/s]
 47%|████▋     | 915/1939 [02:39<02:56,  5.81it/s]
 47%|████▋     | 918/1939 [02:39<02:59,  5.70it/s]
 47%|████▋     | 920/1939 [02:40<02:40,  6.36it/s]
 48%|████▊     | 922/1939 [02:40<02:18,  7.34it/s]
 48%|████▊     | 927/1939 [02:40<02:23,  7.05it/s]
 48%|████▊     | 930/1939 [02:41<02:45,  6.08it/s]
 48%|████▊     | 932/1939 [02:42<03:26,  4.87it/s]
 48%|████▊     | 938/1939 [02:42<01:59,  8.39it/s]
 49%|████▊     | 944/1939 [02:42<01:18, 12.65it/s]
 49%|████▉     | 948/1939 [02:42<01:06, 14.99it/s]
 49%|████▉     | 954/1939 [02:42<00:48, 20.12it/s]
 49%|████▉     | 958/1939 [02:42<00:47, 20.65it/s]
 50%|████▉     | 964/1939 [02:43<00:36, 26.78it/s]
 50%|████▉     | 968/1939 [02:44<01:34, 10.27it/s]
 50%|█████     | 971/1939 [02:45<03:11,  5.04it/s]
 50%|█████     | 974/1939 [02:47<03:54,  4.12it/s]
 50%|█████     | 976/1939 [02:47<03:21,  4.77it/s]
 50%|█████     | 978/1939 [02:48<04:32,  3.53it/s]
 51%|█████     | 980/1939 [02:49<05:26,  2.94it/s]
 51%|█████     | 982/1939 [02:50<06:19,  2.52it/s]
 51%|█████     | 984/1939 [02:50<04:57,  3.21it/s]
 51%|█████     | 989/1939 [02:50<02:43,  5.82it/s]
 51%|█████     | 992/1939 [02:52<05:09,  3.06it/s]
 51%|█████▏    | 995/1939 [02:52<03:47,  4.15it/s]
 51%|█████▏    | 997/1939 [02:53<04:42,  3.33it/s]
 52%|█████▏    | 999/1939 [02:54<05:22,  2.91it/s]
 52%|█████▏    | 1002/1939 [02:55<05:21,  2.91it/s]
 52%|█████▏    | 1004/1939 [02:56<04:17,  3.63it/s]
 52%|█████▏    | 1006/1939 [02:57<06:55,  2.24it/s]
 52%|█████▏    | 1007/1939 [02:58<07:24,  2.09it/s]
 52%|█████▏    | 1009/1939 [02:59<06:22,  2.43it/s]
 52%|█████▏    | 1010/1939 [02:59<07:23,  2.09it/s]
 52%|█████▏    | 1011/1939 [03:00<07:38,  2.02it/s]
 52%|█████▏    | 1012/1939 [03:01<09:33,  1.62it/s]
 52%|█████▏    | 1013/1939 [03:01<07:42,  2.00it/s]
 52%|█████▏    | 1014/1939 [03:01<06:36,  2.33it/s]
 52%|█████▏    | 1015/1939 [03:01<05:15,  2.93it/s]
 52%|█████▏    | 1016/1939 [03:02<06:22,  2.41it/s]
 53%|█████▎    | 1018/1939 [03:02<03:56,  3.89it/s]
 53%|█████▎    | 1019/1939 [03:03<05:36,  2.73it/s]
 53%|█████▎    | 1021/1939 [03:03<03:40,  4.16it/s]
 53%|█████▎    | 1022/1939 [03:04<04:36,  3.32it/s]
 53%|█████▎    | 1025/1939 [03:04<02:39,  5.75it/s]
 53%|█████▎    | 1027/1939 [03:04<03:28,  4.36it/s]
 53%|█████▎    | 1029/1939 [03:04<02:40,  5.68it/s]
 53%|█████▎    | 1032/1939 [03:05<01:51,  8.14it/s]
 54%|█████▎    | 1038/1939 [03:05<01:00, 14.99it/s]
 54%|█████▎    | 1041/1939 [03:05<00:52, 17.06it/s]
 54%|█████▍    | 1044/1939 [03:05<00:46, 19.13it/s]
 54%|█████▍    | 1047/1939 [03:06<02:09,  6.89it/s]
 54%|█████▍    | 1049/1939 [03:07<03:28,  4.26it/s]
 54%|█████▍    | 1051/1939 [03:08<04:32,  3.25it/s]
 54%|█████▍    | 1053/1939 [03:09<05:24,  2.73it/s]
 54%|█████▍    | 1054/1939 [03:10<05:50,  2.52it/s]
 54%|█████▍    | 1056/1939 [03:11<06:14,  2.36it/s]
 55%|█████▍    | 1058/1939 [03:11<04:34,  3.21it/s]
 55%|█████▍    | 1059/1939 [03:12<06:17,  2.33it/s]
 55%|█████▍    | 1060/1939 [03:13<07:55,  1.85it/s]
 55%|█████▍    | 1062/1939 [03:13<05:19,  2.74it/s]
 55%|█████▍    | 1064/1939 [03:13<03:46,  3.87it/s]
 55%|█████▌    | 1068/1939 [03:14<03:50,  3.78it/s]
 55%|█████▌    | 1070/1939 [03:14<03:05,  4.69it/s]
 55%|█████▌    | 1075/1939 [03:14<01:43,  8.31it/s]
 56%|█████▌    | 1080/1939 [03:16<02:20,  6.12it/s]
 56%|█████▌    | 1082/1939 [03:16<02:02,  7.00it/s]
 56%|█████▌    | 1087/1939 [03:16<01:19, 10.69it/s]
 56%|█████▌    | 1090/1939 [03:17<02:17,  6.18it/s]
 56%|█████▋    | 1092/1939 [03:18<03:20,  4.23it/s]
 56%|█████▋    | 1094/1939 [03:19<04:24,  3.20it/s]
 57%|█████▋    | 1096/1939 [03:19<03:31,  3.98it/s]
 57%|█████▋    | 1098/1939 [03:20<04:13,  3.32it/s]
 57%|█████▋    | 1102/1939 [03:21<03:20,  4.18it/s]
 57%|█████▋    | 1104/1939 [03:21<03:03,  4.54it/s]
 57%|█████▋    | 1105/1939 [03:22<03:51,  3.60it/s]
 57%|█████▋    | 1108/1939 [03:22<02:34,  5.36it/s]
 57%|█████▋    | 1110/1939 [03:23<03:16,  4.22it/s]
 57%|█████▋    | 1112/1939 [03:23<02:35,  5.32it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 321.47it/s]
 67%|██████▋   | 201/300 [13:42<1:40:35, 60.96s/it]

[[np.int64(0), False, 13], [np.int64(1), False, 12], [np.int64(2), False, 13], [np.int64(3), False, 10], [np.int64(4), False, 0], [np.int64(5), False, 9], [np.int64(6), False, 12], [np.int64(7), False, 12], [np.int64(8), False, 1], [np.int64(10), False, 2], [np.int64(11), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7045, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.4106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9173, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [13:42<1:01:12, 37.86s/it]

tensor(12.4159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1673, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3575, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [13:42<36:38, 23.14s/it]

tensor(12.4303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4213, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4274, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [13:42<23:05, 14.90s/it]

tensor(12.4269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4700, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4981, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [13:42<15:00,  9.90s/it]

tensor(12.4211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5147, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [13:43<09:56,  6.70s/it]

tensor(12.4223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0367, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5265, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5558, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5545, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [13:43<06:40,  4.60s/it]

tensor(12.4242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0333, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5496, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5560, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [13:43<04:31,  3.20s/it]

tensor(12.4095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5633, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [13:43<03:05,  2.24s/it]

tensor(12.4020, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5749, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5927, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [13:43<02:08,  1.58s/it]

tensor(12.3975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5987, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6027, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [13:43<01:29,  1.13s/it]

tensor(12.3946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5974, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [13:44<01:02,  1.23it/s]

tensor(12.3892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5885, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3752, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6004, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [13:44<00:44,  1.67it/s]

tensor(12.3700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6065, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6078, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [13:44<00:32,  2.24it/s]

tensor(12.3670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6174, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [13:44<00:24,  2.94it/s]

tensor(12.3673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6168, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6233, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6283, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [13:44<00:18,  3.77it/s]

tensor(12.3626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6320, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3584, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6297, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [13:45<00:14,  4.68it/s]

tensor(12.3543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6279, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [13:45<00:11,  5.63it/s]

tensor(12.3507, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6250, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6279, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3456, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6326, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [13:45<00:09,  6.56it/s]

tensor(12.3439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6274, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6280, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [13:45<00:08,  7.40it/s]

tensor(12.3403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6288, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [13:45<00:07,  8.15it/s]

tensor(12.3382, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6197, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6135, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [13:46<00:06,  8.78it/s]

tensor(12.3313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6184, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [13:46<00:05,  9.29it/s]

tensor(12.3273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6204, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [13:46<00:05,  9.65it/s]

tensor(12.3254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6202, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6220, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6190, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [13:46<00:05,  9.96it/s]

tensor(12.3199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6193, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([135, 254, 122,  62, 110,  70, 224, 369, 118,  75, 175, 173,  20,  32])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:18, 24.51it/s]
  0%|          | 7/1939 [00:00<00:59, 32.68it/s]
  1%|          | 12/1939 [00:00<00:51, 37.73it/s]
  1%|          | 19/1939 [00:00<00:39, 48.53it/s]
  1%|▏         | 27/1939 [00:00<00:38, 49.74it/s]
  2%|▏         | 32/1939 [00:00<00:42, 44.42it/s]
  2%|▏         | 38/1939 [00:00<00:41, 46.26it/s]
  2%|▏         | 43/1939 [00:02<02:40, 11.79it/s]
  2%|▏         | 47/1939 [00:02<02:16, 13.88it/s]
  3%|▎         | 51/1939 [00:02<03:15,  9.67it/s]
  3%|▎         | 54/1939 [00:03<04:02,  7.78it/s]
  3%|▎         | 58/1939 [00:04<03:43,  8.42it/s]
  3%|▎         | 60/1939 [00:04<03:21,  9.33it/s]
  3%|▎         | 66/1939 [00:04<03:27,  9.02it/s]
  4%|▎         | 68/1939 [00:04<03:14,  9.64it/s]
  4%|▎         | 71/1939 [00:05<03:03, 10.16it/s]
  4%|▍         | 73/1939 [00:05<03:41,  8.42it/s]
  4%|▍         | 75/1939 [00:05<03:14,  9.57it/s]
  4%|▍         | 78/1939 [00:06<04:24,  7.03it/s]
  4%|▍         | 80/1939 [00:07<05:51,  5.29it/s]
  4%|▍         | 82/1939 [00:07<07:09,  4.32it/s]
  4%|▍         | 84/1939 [00:08<07:52,  3.93it/s]
  4%|▍         | 86/1939 [00:09<08:10,  3.77it/s]
  4%|▍         | 87/1939 [00:09<07:48,  3.95it/s]
  5%|▍         | 89/1939 [00:09<05:49,  5.29it/s]
 83%|████████▎ | 249/300 [13:59<00:05,  9.96it/s]
  5%|▍         | 95/1939 [00:10<05:15,  5.85it/s]
  5%|▌         | 98/1939 [00:10<04:26,  6.91it/s]
  5%|▌         | 100/1939 [00:11<05:56,  5.16it/s]
  5%|▌         | 103/1939 [00:11<04:15,  7.17it/s]
  5%|▌         | 105/1939 [00:11<06:08,  4.98it/s]
  6%|▌         | 107/1939 [00:12<04:56,  6.19it/s]
  6%|▌         | 110/1939 [00:12<03:59,  7.63it/s]
  6%|▌         | 112/1939 [00:12<03:24,  8.94it/s]
  6%|▌         | 114/1939 [00:12<03:20,  9.12it/s]
  6%|▌         | 116/1939 [00:13<05:20,  5.69it/s]
  6%|▌         | 118/1939 [00:14<06:52,  4.42it/s]
  6%|▌         | 120/1939 [00:14<07:40,  3.95it/s]
  6%|▌         | 121/1939 [00:15<09:17,  3.26it/s]
  6%|▋         | 123/1939 [00:15<06:45,  4.48it/s]
  6%|▋         | 126/1939 [00:15<04:51,  6.22it/s]
  7%|▋         | 128/1939 [00:15<04:55,  6.12it/s]
  7%|▋         | 132/1939 [00:16<05:11,  5.81it/s]
  7%|▋         | 135/1939 [00:17<05:43,  5.25it/s]
  7%|▋         | 137/1939 [00:17<06:34,  4.57it/s]
  7%|▋         | 140/1939 [00:18<04:44,  6.33it/s]
  7%|▋         | 144/1939 [00:18<03:33,  8.40it/s]
  8%|▊         | 146/1939 [00:19<05:18,  5.63it/s]
  8%|▊         | 149/1939 [00:19<03:57,  7.55it/s]
  8%|▊         | 153/1939 [00:19<03:29,  8.54it/s]
  8%|▊         | 155/1939 [00:19<03:16,  9.08it/s]
  8%|▊         | 157/1939 [00:20<04:17,  6.91it/s]
  8%|▊         | 159/1939 [00:20<05:25,  5.46it/s]
  8%|▊         | 160/1939 [00:21<06:25,  4.62it/s]
  8%|▊         | 161/1939 [00:21<06:19,  4.69it/s]
  8%|▊         | 162/1939 [00:21<08:01,  3.69it/s]
  8%|▊         | 163/1939 [00:22<09:44,  3.04it/s]
  8%|▊         | 164/1939 [00:22<11:00,  2.69it/s]
  9%|▊         | 165/1939 [00:23<09:34,  3.09it/s]
  9%|▊         | 167/1939 [00:23<06:12,  4.76it/s]
  9%|▉         | 172/1939 [00:23<02:51, 10.31it/s]
  9%|▉         | 178/1939 [00:23<01:45, 16.65it/s]
  9%|▉         | 182/1939 [00:23<01:41, 17.39it/s]
 10%|▉         | 186/1939 [00:23<01:23, 20.93it/s]
 10%|█         | 194/1939 [00:23<00:55, 31.29it/s]
 10%|█         | 200/1939 [00:24<00:50, 34.42it/s]
 11%|█         | 205/1939 [00:25<03:39,  7.89it/s]
 11%|█         | 208/1939 [00:26<04:13,  6.82it/s]
 11%|█         | 211/1939 [00:27<04:48,  6.00it/s]
 11%|█         | 214/1939 [00:27<03:56,  7.31it/s]
 11%|█         | 216/1939 [00:28<04:48,  5.97it/s]
 11%|█▏        | 219/1939 [00:28<03:44,  7.67it/s]
 11%|█▏        | 222/1939 [00:28<03:00,  9.53it/s]
 12%|█▏        | 225/1939 [00:28<02:35, 11.03it/s]
 12%|█▏        | 227/1939 [00:28<02:28, 11.52it/s]
 12%|█▏        | 229/1939 [00:29<04:06,  6.93it/s]
 12%|█▏        | 232/1939 [00:29<03:03,  9.29it/s]
 12%|█▏        | 234/1939 [00:29<04:17,  6.61it/s]
 12%|█▏        | 236/1939 [00:30<05:21,  5.29it/s]
 12%|█▏        | 238/1939 [00:30<04:48,  5.90it/s]
 12%|█▏        | 239/1939 [00:31<06:36,  4.29it/s]
 12%|█▏        | 240/1939 [00:31<06:32,  4.33it/s]
 12%|█▏        | 241/1939 [00:31<07:23,  3.83it/s]
 12%|█▏        | 242/1939 [00:32<08:09,  3.47it/s]
 13%|█▎        | 243/1939 [00:32<10:13,  2.77it/s]
 13%|█▎        | 245/1939 [00:33<08:13,  3.43it/s]
 13%|█▎        | 246/1939 [00:33<09:24,  3.00it/s]
 13%|█▎        | 247/1939 [00:33<07:55,  3.56it/s]
 13%|█▎        | 248/1939 [00:33<06:37,  4.26it/s]
 13%|█▎        | 250/1939 [00:34<04:50,  5.81it/s]
 13%|█▎        | 252/1939 [00:34<03:40,  7.67it/s]
 13%|█▎        | 254/1939 [00:34<02:52,  9.76it/s]
 13%|█▎        | 257/1939 [00:34<02:24, 11.64it/s]
 13%|█▎        | 259/1939 [00:34<02:11, 12.80it/s]
 14%|█▎        | 263/1939 [00:35<03:05,  9.03it/s]
 14%|█▎        | 265/1939 [00:35<02:43, 10.23it/s]
 14%|█▍        | 267/1939 [00:35<02:45, 10.09it/s]
 14%|█▍        | 270/1939 [00:35<02:14, 12.45it/s]
 14%|█▍        | 274/1939 [00:35<01:42, 16.32it/s]
 14%|█▍        | 276/1939 [00:36<01:46, 15.64it/s]
 14%|█▍        | 280/1939 [00:36<01:36, 17.19it/s]
 15%|█▍        | 282/1939 [00:36<03:03,  9.05it/s]
 15%|█▍        | 284/1939 [00:36<02:42, 10.18it/s]
 15%|█▍        | 286/1939 [00:37<02:59,  9.19it/s]
 15%|█▍        | 288/1939 [00:37<03:06,  8.86it/s]
 15%|█▍        | 290/1939 [00:37<02:44, 10.05it/s]
 15%|█▌        | 293/1939 [00:38<03:31,  7.79it/s]
 15%|█▌        | 296/1939 [00:38<02:43, 10.07it/s]
 15%|█▌        | 300/1939 [00:38<01:57, 13.99it/s]
 16%|█▌        | 305/1939 [00:38<01:28, 18.49it/s]
 16%|█▌        | 312/1939 [00:38<01:00, 26.89it/s]
 16%|█▋        | 316/1939 [00:39<02:01, 13.41it/s]
 16%|█▋        | 319/1939 [00:39<01:49, 14.77it/s]
 17%|█▋        | 322/1939 [00:40<03:40,  7.34it/s]
 17%|█▋        | 324/1939 [00:40<03:17,  8.18it/s]
 17%|█▋        | 327/1939 [00:40<02:36, 10.30it/s]
 17%|█▋        | 330/1939 [00:40<02:07, 12.63it/s]
 17%|█▋        | 333/1939 [00:41<01:53, 14.10it/s]
 18%|█▊        | 340/1939 [00:41<01:08, 23.23it/s]
 18%|█▊        | 344/1939 [00:41<01:01, 25.75it/s]
 18%|█▊        | 350/1939 [00:41<00:48, 32.48it/s]
 18%|█▊        | 355/1939 [00:43<03:41,  7.14it/s]
 19%|█▊        | 359/1939 [00:43<02:59,  8.81it/s]
 19%|█▊        | 362/1939 [00:43<02:31, 10.40it/s]
 19%|█▉        | 365/1939 [00:43<02:29, 10.54it/s]
 19%|█▉        | 368/1939 [00:44<02:25, 10.77it/s]
 19%|█▉        | 370/1939 [00:44<03:35,  7.27it/s]
 19%|█▉        | 373/1939 [00:44<02:50,  9.18it/s]
 19%|█▉        | 376/1939 [00:45<03:43,  6.99it/s]
 19%|█▉        | 378/1939 [00:45<03:19,  7.84it/s]
 20%|█▉        | 381/1939 [00:46<03:57,  6.57it/s]
 20%|█▉        | 384/1939 [00:46<04:30,  5.74it/s]
 20%|█▉        | 386/1939 [00:47<03:50,  6.74it/s]
 20%|██        | 388/1939 [00:48<06:23,  4.04it/s]
 20%|██        | 390/1939 [00:48<06:47,  3.80it/s]
 20%|██        | 391/1939 [00:49<08:13,  3.13it/s]
 20%|██        | 393/1939 [00:50<08:26,  3.05it/s]
 20%|██        | 394/1939 [00:50<09:30,  2.71it/s]
 20%|██        | 395/1939 [00:50<08:32,  3.02it/s]
 20%|██        | 396/1939 [00:51<09:51,  2.61it/s]
 21%|██        | 398/1939 [00:51<09:07,  2.81it/s]
 21%|██        | 399/1939 [00:52<08:02,  3.19it/s]
 21%|██        | 402/1939 [00:52<04:37,  5.53it/s]
 21%|██        | 404/1939 [00:52<05:32,  4.61it/s]
 21%|██        | 405/1939 [00:53<07:20,  3.48it/s]
 21%|██        | 407/1939 [00:54<07:33,  3.38it/s]
 21%|██        | 409/1939 [00:54<05:30,  4.62it/s]
 21%|██        | 411/1939 [00:54<06:09,  4.14it/s]
 21%|██▏       | 413/1939 [00:54<04:37,  5.51it/s]
 21%|██▏       | 415/1939 [00:55<05:27,  4.66it/s]
 22%|██▏       | 417/1939 [00:55<04:37,  5.49it/s]
 22%|██▏       | 419/1939 [00:56<05:27,  4.64it/s]
 22%|██▏       | 422/1939 [00:56<05:28,  4.61it/s]
 22%|██▏       | 425/1939 [00:57<03:51,  6.54it/s]
 22%|██▏       | 427/1939 [00:57<04:59,  5.06it/s]
 22%|██▏       | 428/1939 [00:58<06:28,  3.89it/s]
 22%|██▏       | 430/1939 [00:58<04:56,  5.09it/s]
 22%|██▏       | 434/1939 [00:58<02:57,  8.50it/s]
 23%|██▎       | 439/1939 [00:58<01:50, 13.62it/s]
 23%|██▎       | 446/1939 [00:58<01:08, 21.92it/s]
 23%|██▎       | 452/1939 [00:58<00:52, 28.52it/s]
 24%|██▎       | 457/1939 [00:59<00:56, 26.36it/s]
 24%|██▍       | 463/1939 [00:59<00:46, 32.02it/s]
 24%|██▍       | 469/1939 [00:59<00:39, 37.26it/s]
 24%|██▍       | 475/1939 [00:59<00:34, 41.97it/s]
 25%|██▍       | 481/1939 [00:59<00:43, 33.74it/s]
 25%|██▌       | 486/1939 [00:59<00:54, 26.86it/s]
 25%|██▌       | 490/1939 [01:00<00:56, 25.47it/s]
 25%|██▌       | 494/1939 [01:00<01:28, 16.24it/s]
 26%|██▌       | 499/1939 [01:00<01:24, 17.07it/s]
 26%|██▌       | 502/1939 [01:00<01:19, 18.06it/s]
 26%|██▌       | 505/1939 [01:01<01:26, 16.66it/s]
 26%|██▌       | 507/1939 [01:01<01:34, 15.18it/s]
 26%|██▋       | 509/1939 [01:01<01:47, 13.35it/s]
 26%|██▋       | 511/1939 [01:01<02:01, 11.78it/s]
 26%|██▋       | 513/1939 [01:02<02:02, 11.61it/s]
 27%|██▋       | 515/1939 [01:02<01:54, 12.39it/s]
 27%|██▋       | 522/1939 [01:02<01:01, 23.01it/s]
 27%|██▋       | 529/1939 [01:02<00:43, 32.05it/s]
 28%|██▊       | 537/1939 [01:02<01:09, 20.22it/s]
 28%|██▊       | 541/1939 [01:03<01:06, 20.88it/s]
 28%|██▊       | 545/1939 [01:03<01:07, 20.58it/s]
 28%|██▊       | 548/1939 [01:03<01:43, 13.41it/s]
 28%|██▊       | 551/1939 [01:04<02:11, 10.55it/s]
 29%|██▊       | 553/1939 [01:04<02:06, 10.92it/s]
 29%|██▊       | 555/1939 [01:04<01:59, 11.63it/s]
 29%|██▊       | 557/1939 [01:05<03:00,  7.66it/s]
 29%|██▉       | 559/1939 [01:05<02:39,  8.67it/s]
 29%|██▉       | 562/1939 [01:05<02:01, 11.30it/s]
 29%|██▉       | 564/1939 [01:05<01:49, 12.60it/s]
 29%|██▉       | 566/1939 [01:05<01:57, 11.69it/s]
 29%|██▉       | 568/1939 [01:05<01:56, 11.81it/s]
 29%|██▉       | 571/1939 [01:06<02:59,  7.61it/s]
 30%|██▉       | 573/1939 [01:07<03:33,  6.41it/s]
 30%|██▉       | 574/1939 [01:07<03:31,  6.44it/s]
 30%|██▉       | 575/1939 [01:07<04:54,  4.63it/s]
 30%|██▉       | 576/1939 [01:07<04:24,  5.16it/s]
 30%|██▉       | 578/1939 [01:07<03:12,  7.08it/s]
 30%|██▉       | 580/1939 [01:08<04:19,  5.23it/s]
 30%|███       | 582/1939 [01:08<04:56,  4.57it/s]
 30%|███       | 584/1939 [01:09<04:28,  5.05it/s]
 30%|███       | 586/1939 [01:09<05:26,  4.14it/s]
 30%|███       | 588/1939 [01:10<04:09,  5.42it/s]
 30%|███       | 589/1939 [01:10<05:39,  3.98it/s]
 30%|███       | 590/1939 [01:10<05:22,  4.18it/s]
 30%|███       | 591/1939 [01:11<06:27,  3.47it/s]
 31%|███       | 593/1939 [01:11<06:08,  3.65it/s]
 31%|███       | 595/1939 [01:11<04:21,  5.13it/s]
 31%|███       | 596/1939 [01:12<06:15,  3.58it/s]
 31%|███       | 598/1939 [01:12<04:54,  4.55it/s]
 31%|███       | 599/1939 [01:13<06:47,  3.29it/s]
 31%|███       | 600/1939 [01:13<08:20,  2.68it/s]
 31%|███       | 601/1939 [01:14<09:40,  2.30it/s]
 31%|███       | 603/1939 [01:14<06:45,  3.29it/s]
 31%|███       | 605/1939 [01:15<05:16,  4.21it/s]
 31%|███▏      | 607/1939 [01:15<06:02,  3.68it/s]
 31%|███▏      | 608/1939 [01:16<06:23,  3.47it/s]
 31%|███▏      | 609/1939 [01:16<06:35,  3.37it/s]
 32%|███▏      | 611/1939 [01:16<05:47,  3.82it/s]
 32%|███▏      | 612/1939 [01:16<05:15,  4.20it/s]
 32%|███▏      | 613/1939 [01:17<05:13,  4.23it/s]
 32%|███▏      | 614/1939 [01:17<05:43,  3.85it/s]
 32%|███▏      | 615/1939 [01:17<06:19,  3.49it/s]
 32%|███▏      | 616/1939 [01:18<07:51,  2.81it/s]
 32%|███▏      | 617/1939 [01:18<08:26,  2.61it/s]
 32%|███▏      | 618/1939 [01:19<08:02,  2.74it/s]
 32%|███▏      | 620/1939 [01:19<06:33,  3.36it/s]
 32%|███▏      | 621/1939 [01:19<05:33,  3.95it/s]
 32%|███▏      | 622/1939 [01:19<05:03,  4.34it/s]
 32%|███▏      | 627/1939 [01:20<02:08, 10.20it/s]
 32%|███▏      | 629/1939 [01:20<02:12,  9.86it/s]
 33%|███▎      | 631/1939 [01:20<02:49,  7.72it/s]
 33%|███▎      | 633/1939 [01:20<02:25,  8.99it/s]
 33%|███▎      | 636/1939 [01:21<02:28,  8.76it/s]
 33%|███▎      | 638/1939 [01:21<02:28,  8.79it/s]
 33%|███▎      | 640/1939 [01:21<02:23,  9.08it/s]
 33%|███▎      | 642/1939 [01:21<02:09,  9.98it/s]
 33%|███▎      | 646/1939 [01:21<01:26, 14.88it/s]
 33%|███▎      | 649/1939 [01:22<01:27, 14.83it/s]
 34%|███▎      | 651/1939 [01:22<01:31, 14.10it/s]
 34%|███▎      | 654/1939 [01:22<01:53, 11.37it/s]
 34%|███▍      | 656/1939 [01:23<02:29,  8.58it/s]
 34%|███▍      | 658/1939 [01:23<02:41,  7.95it/s]
 34%|███▍      | 660/1939 [01:23<02:15,  9.41it/s]
 34%|███▍      | 663/1939 [01:23<01:43, 12.39it/s]
 34%|███▍      | 665/1939 [01:24<02:55,  7.26it/s]
 34%|███▍      | 667/1939 [01:24<03:56,  5.39it/s]
 35%|███▍      | 669/1939 [01:24<03:08,  6.75it/s]
 35%|███▍      | 672/1939 [01:25<03:29,  6.05it/s]
 35%|███▍      | 674/1939 [01:26<04:19,  4.87it/s]
 35%|███▍      | 676/1939 [01:26<04:57,  4.25it/s]
 35%|███▌      | 679/1939 [01:26<03:23,  6.20it/s]
 35%|███▌      | 681/1939 [01:27<04:13,  4.97it/s]
 35%|███▌      | 683/1939 [01:28<04:47,  4.37it/s]
 35%|███▌      | 687/1939 [01:28<04:13,  4.94it/s]
 36%|███▌      | 689/1939 [01:29<04:45,  4.38it/s]
 36%|███▌      | 692/1939 [01:29<03:28,  5.98it/s]
 36%|███▌      | 695/1939 [01:29<02:36,  7.96it/s]
 36%|███▌      | 698/1939 [01:29<02:01, 10.23it/s]
 36%|███▋      | 704/1939 [01:29<01:15, 16.37it/s]
 36%|███▋      | 707/1939 [01:30<01:23, 14.76it/s]
 37%|███▋      | 711/1939 [01:30<01:07, 18.09it/s]
 37%|███▋      | 716/1939 [01:30<00:52, 23.21it/s]
 37%|███▋      | 722/1939 [01:30<00:41, 29.52it/s]
 37%|███▋      | 727/1939 [01:30<00:38, 31.89it/s]
 38%|███▊      | 731/1939 [01:31<01:45, 11.48it/s]
 38%|███▊      | 734/1939 [01:32<02:18,  8.72it/s]
 38%|███▊      | 737/1939 [01:32<02:08,  9.34it/s]
 38%|███▊      | 739/1939 [01:32<02:25,  8.25it/s]
 38%|███▊      | 741/1939 [01:32<02:10,  9.20it/s]
 38%|███▊      | 743/1939 [01:33<03:05,  6.44it/s]
 38%|███▊      | 746/1939 [01:33<02:36,  7.63it/s]
 39%|███▊      | 749/1939 [01:33<02:00,  9.86it/s]
 39%|███▉      | 752/1939 [01:34<01:47, 11.00it/s]
 39%|███▉      | 755/1939 [01:34<02:24,  8.21it/s]
 39%|███▉      | 757/1939 [01:34<02:15,  8.69it/s]
 39%|███▉      | 760/1939 [01:35<02:53,  6.80it/s]
 39%|███▉      | 761/1939 [01:35<03:02,  6.45it/s]
 39%|███▉      | 763/1939 [01:36<04:01,  4.87it/s]
 39%|███▉      | 764/1939 [01:36<04:02,  4.84it/s]
 40%|███▉      | 766/1939 [01:37<04:40,  4.18it/s]
 40%|███▉      | 767/1939 [01:37<05:48,  3.36it/s]
 40%|███▉      | 768/1939 [01:38<07:00,  2.79it/s]
 40%|███▉      | 769/1939 [01:38<07:43,  2.52it/s]
 40%|███▉      | 770/1939 [01:39<08:27,  2.30it/s]
 40%|███▉      | 772/1939 [01:40<07:30,  2.59it/s]
 40%|███▉      | 773/1939 [01:40<08:19,  2.33it/s]
 40%|███▉      | 774/1939 [01:40<07:03,  2.75it/s]
 40%|████      | 776/1939 [01:41<06:43,  2.88it/s]
 40%|████      | 777/1939 [01:42<07:41,  2.52it/s]
 40%|████      | 779/1939 [01:42<07:13,  2.67it/s]
 40%|████      | 780/1939 [01:43<07:42,  2.51it/s]
 40%|████      | 782/1939 [01:43<05:09,  3.73it/s]
 40%|████      | 784/1939 [01:43<05:12,  3.70it/s]
 40%|████      | 785/1939 [01:43<04:32,  4.23it/s]
 41%|████      | 787/1939 [01:44<04:56,  3.89it/s]
 41%|████      | 789/1939 [01:45<05:05,  3.77it/s]
 41%|████      | 791/1939 [01:45<05:11,  3.68it/s]
 41%|████      | 794/1939 [01:45<03:19,  5.75it/s]
 41%|████      | 796/1939 [01:46<03:40,  5.17it/s]
 41%|████      | 797/1939 [01:46<03:24,  5.57it/s]
 41%|████      | 798/1939 [01:46<04:43,  4.03it/s]
 41%|████▏     | 800/1939 [01:46<03:22,  5.63it/s]
 41%|████▏     | 802/1939 [01:47<04:15,  4.45it/s]
 41%|████▏     | 804/1939 [01:48<04:22,  4.33it/s]
 42%|████▏     | 805/1939 [01:48<04:12,  4.49it/s]
 42%|████▏     | 806/1939 [01:48<04:04,  4.63it/s]
 42%|████▏     | 808/1939 [01:48<03:05,  6.10it/s]
 42%|████▏     | 809/1939 [01:49<04:07,  4.56it/s]
 42%|████▏     | 810/1939 [01:49<04:08,  4.55it/s]
 42%|████▏     | 812/1939 [01:49<03:27,  5.43it/s]
 42%|████▏     | 813/1939 [01:49<04:28,  4.19it/s]
 42%|████▏     | 814/1939 [01:50<05:03,  3.70it/s]
 42%|████▏     | 816/1939 [01:51<05:27,  3.43it/s]
 42%|████▏     | 817/1939 [01:51<06:45,  2.76it/s]
 42%|████▏     | 818/1939 [01:52<07:51,  2.38it/s]
 42%|████▏     | 819/1939 [01:52<08:42,  2.14it/s]
 42%|████▏     | 820/1939 [01:53<09:23,  1.99it/s]
 42%|████▏     | 821/1939 [01:53<09:37,  1.94it/s]
 42%|████▏     | 822/1939 [01:54<09:43,  1.91it/s]
 42%|████▏     | 823/1939 [01:55<10:01,  1.86it/s]
 42%|████▏     | 824/1939 [01:55<07:44,  2.40it/s]
 43%|████▎     | 825/1939 [01:55<06:05,  3.04it/s]
 43%|████▎     | 827/1939 [01:55<03:51,  4.80it/s]
 43%|████▎     | 830/1939 [01:55<02:19,  7.97it/s]
 43%|████▎     | 833/1939 [01:55<01:50, 10.04it/s]
 43%|████▎     | 835/1939 [01:55<01:37, 11.35it/s]
 43%|████▎     | 837/1939 [01:56<01:40, 10.92it/s]
 43%|████▎     | 839/1939 [01:56<01:30, 12.10it/s]
 43%|████▎     | 841/1939 [01:56<01:37, 11.25it/s]
 44%|████▎     | 844/1939 [01:56<01:13, 14.82it/s]
 44%|████▎     | 846/1939 [01:56<01:09, 15.78it/s]
 44%|████▎     | 848/1939 [01:56<01:05, 16.74it/s]
 44%|████▍     | 850/1939 [01:56<01:06, 16.31it/s]
 44%|████▍     | 853/1939 [01:56<00:56, 19.33it/s]
 44%|████▍     | 856/1939 [01:57<01:05, 16.66it/s]
 44%|████▍     | 858/1939 [01:57<01:54,  9.45it/s]
 44%|████▍     | 860/1939 [01:57<01:41, 10.65it/s]
 45%|████▍     | 863/1939 [01:57<01:17, 13.83it/s]
 45%|████▍     | 868/1939 [01:57<00:52, 20.43it/s]
 45%|████▍     | 872/1939 [01:58<00:46, 22.96it/s]
 45%|████▌     | 875/1939 [01:58<00:44, 23.95it/s]
 45%|████▌     | 878/1939 [01:58<00:49, 21.40it/s]
 46%|████▌     | 886/1939 [01:58<00:31, 33.57it/s]
 46%|████▌     | 894/1939 [01:58<00:23, 44.33it/s]
 46%|████▋     | 900/1939 [01:58<00:29, 35.78it/s]
 47%|████▋     | 905/1939 [01:59<00:37, 27.88it/s]
 47%|████▋     | 909/1939 [01:59<00:34, 29.70it/s]
 47%|████▋     | 913/1939 [02:00<01:36, 10.69it/s]
 47%|████▋     | 917/1939 [02:00<01:17, 13.12it/s]
 47%|████▋     | 920/1939 [02:01<01:47,  9.49it/s]
 48%|████▊     | 923/1939 [02:01<01:33, 10.82it/s]
 48%|████▊     | 927/1939 [02:01<01:53,  8.93it/s]
 48%|████▊     | 929/1939 [02:02<01:48,  9.28it/s]
 48%|████▊     | 931/1939 [02:03<03:15,  5.16it/s]
 48%|████▊     | 933/1939 [02:03<02:42,  6.19it/s]
 48%|████▊     | 935/1939 [02:03<02:17,  7.31it/s]
 49%|████▊     | 941/1939 [02:03<01:15, 13.18it/s]
 49%|████▉     | 948/1939 [02:03<00:48, 20.63it/s]
 49%|████▉     | 955/1939 [02:03<00:35, 28.07it/s]
 50%|████▉     | 961/1939 [02:03<00:29, 33.00it/s]
 50%|████▉     | 967/1939 [02:03<00:25, 38.33it/s]
 50%|█████     | 973/1939 [02:06<02:32,  6.32it/s]
 50%|█████     | 977/1939 [02:07<02:44,  5.85it/s]
 51%|█████     | 980/1939 [02:07<02:23,  6.68it/s]
 51%|█████     | 983/1939 [02:08<02:36,  6.11it/s]
 51%|█████     | 985/1939 [02:08<03:03,  5.20it/s]
 51%|█████     | 988/1939 [02:09<02:23,  6.65it/s]
 51%|█████     | 990/1939 [02:09<02:54,  5.44it/s]
 51%|█████     | 992/1939 [02:09<02:27,  6.42it/s]
 51%|█████▏    | 994/1939 [02:10<02:59,  5.28it/s]
 51%|█████▏    | 996/1939 [02:10<02:28,  6.34it/s]
 51%|█████▏    | 998/1939 [02:11<03:09,  4.96it/s]
 52%|█████▏    | 999/1939 [02:11<03:44,  4.18it/s]
 52%|█████▏    | 1001/1939 [02:11<02:51,  5.48it/s]
 52%|█████▏    | 1003/1939 [02:12<03:34,  4.36it/s]
 52%|█████▏    | 1004/1939 [02:12<03:14,  4.82it/s]
 52%|█████▏    | 1005/1939 [02:13<04:39,  3.34it/s]
 52%|█████▏    | 1006/1939 [02:13<04:26,  3.51it/s]
 52%|█████▏    | 1007/1939 [02:13<05:33,  2.79it/s]
 52%|█████▏    | 1009/1939 [02:14<05:24,  2.86it/s]
 52%|█████▏    | 1010/1939 [02:15<06:20,  2.44it/s]
 52%|█████▏    | 1011/1939 [02:15<06:57,  2.22it/s]
 52%|█████▏    | 1012/1939 [02:16<06:39,  2.32it/s]
 52%|█████▏    | 1013/1939 [02:16<06:26,  2.39it/s]
 52%|█████▏    | 1014/1939 [02:16<06:04,  2.53it/s]
 52%|█████▏    | 1016/1939 [02:17<04:50,  3.18it/s]
 53%|█████▎    | 1018/1939 [02:17<03:26,  4.47it/s]
 53%|█████▎    | 1019/1939 [02:17<04:05,  3.75it/s]
 53%|█████▎    | 1021/1939 [02:17<02:50,  5.39it/s]
 53%|█████▎    | 1023/1939 [02:18<02:08,  7.15it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 306.65it/s]
 84%|████████▎ | 251/300 [18:01<31:17, 38.31s/it]

[[np.int64(0), False, 2], [np.int64(1), False, 7], [np.int64(3), False, 10], [np.int64(4), False, 0], [np.int64(5), False, 3], [np.int64(6), False, 7], [np.int64(8), False, 1], [np.int64(9), False, 11], [np.int64(10), False, 2], [np.int64(12), False, 2], [np.int64(13), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3181, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4246, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.3194, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8201, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 253/300 [18:01<19:46, 25.24s/it]

tensor(12.3277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3343, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4764, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [18:01<12:02, 16.06s/it]

tensor(12.3513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4360, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2122, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3502, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3658, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [18:02<07:35, 10.58s/it]

tensor(12.3507, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4723, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4551, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [18:02<04:52,  7.13s/it]

tensor(12.3604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5288, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [18:02<03:10,  4.89s/it]

tensor(12.3720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6083, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6285, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6021, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [18:02<02:05,  3.38s/it]

tensor(12.3636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6093, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6413, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [18:02<01:22,  2.37s/it]

tensor(12.3515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6728, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [18:03<00:55,  1.67s/it]

tensor(12.3551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6906, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3575, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7070, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7098, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [18:03<00:36,  1.19s/it]

tensor(12.3420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4095, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5433, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [18:03<00:24,  1.17it/s]

tensor(12.3374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6741, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [18:03<00:16,  1.59it/s]

tensor(12.3567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0398, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6126, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0445, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0477, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8576, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [18:03<00:11,  2.14it/s]

tensor(12.4639, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0503, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1726, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2376, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [18:04<00:08,  2.82it/s]

tensor(12.4873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0529, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9355, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [18:04<00:05,  3.63it/s]

tensor(12.4658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0531, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9439, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0534, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0946, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0543, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2059, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [18:04<00:04,  4.53it/s]

tensor(12.4260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0561, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3354, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0587, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3901, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [18:04<00:03,  5.47it/s]

tensor(12.4835, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0609, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4128, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [18:04<00:02,  6.41it/s]

tensor(12.4837, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0623, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4146, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4561, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0624, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4009, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4318, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0605, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8331, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [18:04<00:01,  7.28it/s]

tensor(12.4212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0540, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0918, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [18:05<00:01,  8.06it/s]

tensor(12.4848, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0523, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2237, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [18:05<00:01,  8.69it/s]

tensor(12.5298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0523, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3261, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0536, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5305, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8616, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [18:05<00:00,  9.21it/s]

tensor(12.4884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0548, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0541, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9057, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [18:05<00:00,  9.60it/s]

tensor(12.4280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0535, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0992, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [18:05<00:00,  9.91it/s]

tensor(12.4249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0525, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1375, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0505, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0490, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2427, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [18:06<00:00,  3.62s/it]

tensor(12.4537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0469, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2923, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0027387142181396484

PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 2
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.439195548242
NMI         : 0.569899984833
Runtime     : 1106.12 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed2

==============================================================================================================
PRAGA RUN | S2-E15 | seed=3
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 8.171e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29, 10.19it/s]

tensor(19.9980, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3789, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(18.8357, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2365, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:27, 10.89it/s]

tensor(18.0935, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3042, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.8273, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5615, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6081, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9901, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:23, 12.53it/s]

tensor(17.4044, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5725, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2645, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2947, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1895, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1417, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.92it/s]

tensor(17.1577, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1023, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1482, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1654, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1390, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3211, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:21, 13.30it/s]

tensor(17.1117, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5598, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0559, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8726, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9684, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2547, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.36it/s]

tensor(16.8638, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6965, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7591, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1947, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6727, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7424, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:01<00:20, 13.49it/s]

tensor(16.5954, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3347, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4997, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9672, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3707, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6369, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:20, 13.53it/s]

tensor(16.2244, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3398, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0889, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0720, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9757, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8316, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:01<00:20, 13.59it/s]

tensor(15.8748, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6149, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7695, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4205, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6502, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2456, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.57it/s]

tensor(15.5227, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0892, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9485, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8225, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:02<00:19, 13.54it/s]

tensor(15.2126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7093, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6091, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5190, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:19, 13.56it/s]

tensor(14.9545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4386, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3677, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3047, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:02<00:19, 13.58it/s]

tensor(14.7406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2500, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2008, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1594, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.55it/s]

tensor(14.5197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0952, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0731, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.39it/s]

tensor(14.3505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0558, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0438, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2508, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0361, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:18, 13.43it/s]

tensor(14.2085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:18, 13.44it/s]

tensor(14.0705, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0332, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:03<00:18, 13.45it/s]

tensor(13.9350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:04<00:17, 13.56it/s]

tensor(13.8175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:17, 13.47it/s]

tensor(13.7187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:04<00:17, 13.50it/s]

tensor(13.6229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0186, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0186, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.47it/s]

tensor(13.5353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:05<00:17, 13.49it/s]

tensor(13.4570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4081, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.43it/s]

tensor(13.3844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3615, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:16, 13.45it/s]

tensor(13.3167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:16, 13.45it/s]

tensor(13.2526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:05<00:16, 13.47it/s]

tensor(13.1920, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.44it/s]

tensor(13.1357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1176, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:06<00:15, 13.46it/s]

tensor(13.0819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0646, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:15, 13.42it/s]

tensor(13.0302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:06<00:15, 13.46it/s]

tensor(12.9815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.44it/s]

tensor(12.9352, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:15, 13.42it/s]

tensor(12.8921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:14, 13.38it/s]

tensor(12.8516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([172, 216,  92,  75, 206, 188, 120,  33,  81, 113, 448,  65,  35,  95])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:18, 24.81it/s]
  0%|          | 8/1939 [00:00<01:08, 28.34it/s]
  1%|          | 12/1939 [00:00<00:59, 32.45it/s]
  1%|          | 16/1939 [00:00<01:02, 30.82it/s]
  1%|          | 22/1939 [00:00<00:49, 38.89it/s]
  1%|▏         | 28/1939 [00:00<00:43, 44.30it/s]
  2%|▏         | 33/1939 [00:00<00:43, 43.94it/s]
  2%|▏         | 39/1939 [00:00<00:39, 47.58it/s]
  2%|▏         | 44/1939 [00:02<04:07,  7.65it/s]
  3%|▎         | 49/1939 [00:03<04:51,  6.49it/s]
  3%|▎         | 52/1939 [00:04<04:07,  7.62it/s]
  3%|▎         | 55/1939 [00:05<05:30,  5.71it/s]
  3%|▎         | 60/1939 [00:05<03:48,  8.21it/s]
  3%|▎         | 66/1939 [00:06<04:10,  7.46it/s]
  4%|▎         | 69/1939 [00:06<03:41,  8.45it/s]
  4%|▎         | 71/1939 [00:06<03:27,  9.01it/s]
  4%|▍         | 73/1939 [00:06<04:22,  7.10it/s]
  4%|▍         | 76/1939 [00:07<03:29,  8.89it/s]
  4%|▍         | 78/1939 [00:07<05:42,  5.44it/s]
  4%|▍         | 80/1939 [00:09<11:35,  2.67it/s]
  4%|▍         | 81/1939 [00:10<14:15,  2.17it/s]
  4%|▍         | 82/1939 [00:11<16:50,  1.84it/s]
  4%|▍         | 84/1939 [00:12<16:19,  1.89it/s]
 33%|███▎      | 100/300 [00:23<00:14, 13.38it/s]
  4%|▍         | 87/1939 [00:14<18:26,  1.67it/s]
  5%|▍         | 89/1939 [00:14<12:39,  2.44it/s]
  5%|▍         | 94/1939 [00:15<09:01,  3.41it/s]
  5%|▍         | 96/1939 [00:16<10:32,  2.92it/s]
  5%|▌         | 99/1939 [00:17<07:17,  4.20it/s]
  5%|▌         | 101/1939 [00:18<09:19,  3.29it/s]
  5%|▌         | 106/1939 [00:18<05:14,  5.82it/s]
  6%|▌         | 110/1939 [00:18<03:41,  8.25it/s]
  6%|▌         | 115/1939 [00:18<03:40,  8.27it/s]
  6%|▌         | 118/1939 [00:19<04:50,  6.26it/s]
  6%|▌         | 120/1939 [00:20<05:52,  5.16it/s]
  6%|▋         | 122/1939 [00:21<06:59,  4.33it/s]
  6%|▋         | 124/1939 [00:21<05:46,  5.24it/s]
  7%|▋         | 128/1939 [00:22<06:47,  4.44it/s]
  7%|▋         | 130/1939 [00:22<05:36,  5.37it/s]
  7%|▋         | 132/1939 [00:23<07:42,  3.91it/s]
  7%|▋         | 134/1939 [00:23<06:07,  4.91it/s]
  7%|▋         | 136/1939 [00:24<08:29,  3.54it/s]
  7%|▋         | 137/1939 [00:24<09:24,  3.19it/s]
  7%|▋         | 139/1939 [00:25<07:08,  4.20it/s]
  7%|▋         | 141/1939 [00:26<09:05,  3.30it/s]
  7%|▋         | 142/1939 [00:26<09:01,  3.32it/s]
  7%|▋         | 144/1939 [00:26<06:29,  4.61it/s]
  7%|▋         | 145/1939 [00:26<07:17,  4.10it/s]
  8%|▊         | 147/1939 [00:26<05:31,  5.41it/s]
  8%|▊         | 151/1939 [00:27<03:06,  9.59it/s]
  8%|▊         | 153/1939 [00:27<05:21,  5.55it/s]
  8%|▊         | 155/1939 [00:27<04:30,  6.59it/s]
  8%|▊         | 157/1939 [00:28<05:09,  5.75it/s]
  8%|▊         | 159/1939 [00:29<07:02,  4.21it/s]
  8%|▊         | 160/1939 [00:29<07:44,  3.83it/s]
  8%|▊         | 161/1939 [00:30<08:53,  3.33it/s]
  8%|▊         | 162/1939 [00:30<09:53,  2.99it/s]
  8%|▊         | 163/1939 [00:31<11:26,  2.59it/s]
  8%|▊         | 164/1939 [00:31<14:35,  2.03it/s]
  9%|▊         | 166/1939 [00:31<09:06,  3.24it/s]
  9%|▊         | 168/1939 [00:32<06:19,  4.67it/s]
  9%|▉         | 170/1939 [00:32<04:40,  6.31it/s]
  9%|▉         | 176/1939 [00:32<02:12, 13.28it/s]
  9%|▉         | 183/1939 [00:32<01:20, 21.70it/s]
 10%|▉         | 187/1939 [00:32<01:17, 22.55it/s]
 10%|▉         | 193/1939 [00:32<01:00, 28.96it/s]
 10%|█         | 199/1939 [00:32<00:50, 34.37it/s]
 11%|█         | 204/1939 [00:33<02:35, 11.16it/s]
 11%|█         | 208/1939 [00:34<03:30,  8.24it/s]
 11%|█         | 211/1939 [00:35<03:55,  7.32it/s]
 11%|█         | 213/1939 [00:35<03:32,  8.14it/s]
 11%|█         | 215/1939 [00:35<03:08,  9.13it/s]
 11%|█         | 218/1939 [00:35<02:38, 10.89it/s]
 11%|█▏        | 222/1939 [00:36<03:39,  7.83it/s]
 12%|█▏        | 224/1939 [00:36<03:17,  8.70it/s]
 12%|█▏        | 226/1939 [00:36<02:52,  9.95it/s]
 12%|█▏        | 228/1939 [00:37<03:24,  8.36it/s]
 12%|█▏        | 230/1939 [00:37<04:35,  6.21it/s]
 12%|█▏        | 232/1939 [00:37<03:46,  7.53it/s]
 12%|█▏        | 234/1939 [00:38<03:48,  7.46it/s]
 12%|█▏        | 236/1939 [00:38<03:45,  7.55it/s]
 12%|█▏        | 239/1939 [00:39<04:56,  5.73it/s]
 12%|█▏        | 240/1939 [00:39<05:19,  5.32it/s]
 12%|█▏        | 241/1939 [00:39<06:06,  4.63it/s]
 12%|█▏        | 242/1939 [00:39<05:56,  4.75it/s]
 13%|█▎        | 243/1939 [00:40<08:17,  3.41it/s]
 13%|█▎        | 244/1939 [00:41<09:59,  2.83it/s]
 13%|█▎        | 245/1939 [00:41<11:42,  2.41it/s]
 13%|█▎        | 246/1939 [00:42<12:20,  2.29it/s]
 13%|█▎        | 248/1939 [00:42<10:49,  2.60it/s]
 13%|█▎        | 250/1939 [00:42<07:13,  3.90it/s]
 13%|█▎        | 252/1939 [00:42<05:17,  5.31it/s]
 13%|█▎        | 257/1939 [00:43<03:28,  8.05it/s]
 13%|█▎        | 259/1939 [00:43<03:08,  8.92it/s]
 13%|█▎        | 261/1939 [00:44<04:32,  6.16it/s]
 14%|█▎        | 263/1939 [00:44<06:10,  4.52it/s]
 14%|█▎        | 264/1939 [00:45<07:23,  3.77it/s]
 14%|█▎        | 266/1939 [00:45<05:32,  5.03it/s]
 14%|█▍        | 272/1939 [00:45<02:38, 10.49it/s]
 14%|█▍        | 278/1939 [00:45<01:42, 16.23it/s]
 15%|█▍        | 282/1939 [00:46<02:08, 12.89it/s]
 15%|█▍        | 285/1939 [00:47<03:33,  7.76it/s]
 15%|█▍        | 288/1939 [00:47<04:05,  6.73it/s]
 15%|█▍        | 290/1939 [00:47<03:34,  7.69it/s]
 15%|█▌        | 293/1939 [00:48<03:37,  7.58it/s]
 15%|█▌        | 295/1939 [00:48<03:12,  8.55it/s]
 15%|█▌        | 297/1939 [00:48<04:41,  5.84it/s]
 15%|█▌        | 300/1939 [00:49<03:29,  7.83it/s]
 16%|█▌        | 303/1939 [00:49<02:45,  9.87it/s]
 16%|█▌        | 306/1939 [00:49<02:10, 12.48it/s]
 16%|█▌        | 312/1939 [00:49<02:06, 12.88it/s]
 16%|█▌        | 315/1939 [00:50<03:41,  7.34it/s]
 16%|█▋        | 317/1939 [00:51<05:16,  5.12it/s]
 17%|█▋        | 320/1939 [00:52<06:23,  4.22it/s]
 17%|█▋        | 321/1939 [00:53<08:50,  3.05it/s]
 17%|█▋        | 322/1939 [00:54<11:04,  2.43it/s]
 17%|█▋        | 324/1939 [00:54<08:20,  3.23it/s]
 17%|█▋        | 330/1939 [00:54<03:57,  6.77it/s]
 17%|█▋        | 335/1939 [00:54<02:35, 10.29it/s]
 18%|█▊        | 341/1939 [00:54<01:45, 15.13it/s]
 18%|█▊        | 346/1939 [00:55<01:24, 18.87it/s]
 18%|█▊        | 350/1939 [00:55<01:13, 21.73it/s]
 18%|█▊        | 354/1939 [00:58<06:20,  4.17it/s]
 18%|█▊        | 357/1939 [00:59<06:58,  3.78it/s]
 19%|█▊        | 360/1939 [01:00<07:26,  3.54it/s]
 19%|█▊        | 363/1939 [01:01<07:52,  3.34it/s]
 19%|█▉        | 366/1939 [01:01<06:05,  4.30it/s]
 19%|█▉        | 368/1939 [01:01<05:07,  5.11it/s]
 19%|█▉        | 370/1939 [01:02<06:55,  3.78it/s]
 19%|█▉        | 373/1939 [01:02<05:00,  5.20it/s]
 19%|█▉        | 376/1939 [01:03<05:57,  4.38it/s]
 19%|█▉        | 378/1939 [01:03<04:53,  5.33it/s]
 20%|█▉        | 380/1939 [01:03<03:59,  6.51it/s]
 20%|█▉        | 382/1939 [01:04<06:09,  4.21it/s]
 20%|█▉        | 384/1939 [01:05<07:09,  3.62it/s]
 20%|█▉        | 386/1939 [01:05<05:32,  4.67it/s]
 20%|██        | 388/1939 [01:06<07:51,  3.29it/s]
 20%|██        | 390/1939 [01:06<06:40,  3.86it/s]
 20%|██        | 391/1939 [01:07<06:47,  3.80it/s]
 20%|██        | 393/1939 [01:07<06:16,  4.10it/s]
 20%|██        | 394/1939 [01:08<07:20,  3.50it/s]
 20%|██        | 396/1939 [01:08<07:48,  3.30it/s]
 20%|██        | 397/1939 [01:09<09:36,  2.68it/s]
 21%|██        | 398/1939 [01:10<10:50,  2.37it/s]
 21%|██        | 401/1939 [01:10<06:00,  4.27it/s]
 21%|██        | 404/1939 [01:10<06:32,  3.91it/s]
 21%|██        | 405/1939 [01:11<07:42,  3.32it/s]
 21%|██        | 407/1939 [01:12<08:12,  3.11it/s]
 21%|██        | 409/1939 [01:12<06:03,  4.21it/s]
 21%|██        | 411/1939 [01:12<05:26,  4.68it/s]
 21%|██▏       | 413/1939 [01:12<04:13,  6.03it/s]
 21%|██▏       | 415/1939 [01:13<05:21,  4.73it/s]
 22%|██▏       | 417/1939 [01:14<07:30,  3.38it/s]
 22%|██▏       | 419/1939 [01:15<08:00,  3.16it/s]
 22%|██▏       | 422/1939 [01:15<06:26,  3.92it/s]
 22%|██▏       | 425/1939 [01:15<04:31,  5.57it/s]
 22%|██▏       | 427/1939 [01:16<06:50,  3.69it/s]
 22%|██▏       | 428/1939 [01:17<09:34,  2.63it/s]
 22%|██▏       | 431/1939 [01:17<06:11,  4.06it/s]
 23%|██▎       | 438/1939 [01:18<02:52,  8.71it/s]
 23%|██▎       | 441/1939 [01:18<02:28, 10.09it/s]
 23%|██▎       | 448/1939 [01:18<01:30, 16.42it/s]
 23%|██▎       | 453/1939 [01:18<01:13, 20.09it/s]
 24%|██▎       | 457/1939 [01:18<01:04, 22.98it/s]
 24%|██▍       | 462/1939 [01:18<00:53, 27.67it/s]
 24%|██▍       | 469/1939 [01:18<00:41, 35.41it/s]
 24%|██▍       | 474/1939 [01:18<00:42, 34.66it/s]
 25%|██▍       | 479/1939 [01:19<01:32, 15.83it/s]
 25%|██▍       | 483/1939 [01:19<01:22, 17.72it/s]
 25%|██▌       | 489/1939 [01:20<02:20, 10.34it/s]
 25%|██▌       | 492/1939 [01:21<03:31,  6.84it/s]
 25%|██▌       | 494/1939 [01:21<03:10,  7.59it/s]
 26%|██▌       | 501/1939 [01:22<01:54, 12.56it/s]
 26%|██▋       | 509/1939 [01:22<01:14, 19.29it/s]
 27%|██▋       | 514/1939 [01:23<02:13, 10.63it/s]
 27%|██▋       | 520/1939 [01:23<01:39, 14.29it/s]
 27%|██▋       | 528/1939 [01:23<01:08, 20.55it/s]
 28%|██▊       | 535/1939 [01:23<00:52, 26.52it/s]
 28%|██▊       | 541/1939 [01:24<01:50, 12.65it/s]
 28%|██▊       | 546/1939 [01:25<02:38,  8.78it/s]
 28%|██▊       | 549/1939 [01:26<03:37,  6.38it/s]
 28%|██▊       | 552/1939 [01:27<04:30,  5.13it/s]
 29%|██▊       | 556/1939 [01:27<03:24,  6.76it/s]
 29%|██▉       | 563/1939 [01:28<02:10, 10.58it/s]
 29%|██▉       | 568/1939 [01:29<02:50,  8.05it/s]
 29%|██▉       | 571/1939 [01:30<03:51,  5.90it/s]
 30%|██▉       | 573/1939 [01:31<04:59,  4.56it/s]
 30%|██▉       | 575/1939 [01:32<08:04,  2.82it/s]
 30%|██▉       | 578/1939 [01:33<06:06,  3.72it/s]
 30%|██▉       | 580/1939 [01:33<06:25,  3.53it/s]
 30%|███       | 582/1939 [01:34<07:24,  3.05it/s]
 30%|███       | 584/1939 [01:35<07:31,  3.00it/s]
 30%|███       | 586/1939 [01:35<07:01,  3.21it/s]
 30%|███       | 588/1939 [01:36<05:28,  4.11it/s]
 31%|███       | 593/1939 [01:36<04:48,  4.67it/s]
 31%|███       | 595/1939 [01:37<04:03,  5.52it/s]
 31%|███       | 597/1939 [01:37<03:24,  6.55it/s]
 31%|███       | 599/1939 [01:38<05:08,  4.35it/s]
 31%|███       | 601/1939 [01:39<06:50,  3.26it/s]
 31%|███       | 603/1939 [01:39<05:19,  4.19it/s]
 31%|███▏      | 607/1939 [01:40<05:28,  4.05it/s]
 31%|███▏      | 608/1939 [01:41<07:36,  2.91it/s]
 31%|███▏      | 610/1939 [01:41<05:48,  3.81it/s]
 32%|███▏      | 611/1939 [01:42<08:25,  2.63it/s]
 32%|███▏      | 612/1939 [01:43<10:51,  2.04it/s]
 32%|███▏      | 613/1939 [01:44<13:05,  1.69it/s]
 32%|███▏      | 614/1939 [01:45<15:05,  1.46it/s]
 32%|███▏      | 615/1939 [01:46<16:51,  1.31it/s]
 32%|███▏      | 616/1939 [01:47<17:41,  1.25it/s]
 32%|███▏      | 617/1939 [01:48<18:46,  1.17it/s]
 32%|███▏      | 618/1939 [01:49<19:34,  1.12it/s]
 32%|███▏      | 620/1939 [01:50<16:06,  1.37it/s]
 32%|███▏      | 621/1939 [01:51<17:19,  1.27it/s]
 32%|███▏      | 622/1939 [01:52<18:27,  1.19it/s]
 32%|███▏      | 625/1939 [01:52<09:17,  2.36it/s]
 32%|███▏      | 629/1939 [01:53<07:12,  3.03it/s]
 32%|███▏      | 630/1939 [01:53<07:49,  2.79it/s]
 33%|███▎      | 632/1939 [01:54<06:51,  3.18it/s]
 33%|███▎      | 634/1939 [01:54<05:06,  4.25it/s]
 33%|███▎      | 636/1939 [01:55<06:23,  3.40it/s]
 33%|███▎      | 638/1939 [01:55<04:47,  4.52it/s]
 33%|███▎      | 640/1939 [01:55<04:51,  4.46it/s]
 33%|███▎      | 642/1939 [01:55<03:49,  5.64it/s]
 33%|███▎      | 644/1939 [01:56<03:55,  5.50it/s]
 33%|███▎      | 647/1939 [01:56<02:40,  8.07it/s]
 33%|███▎      | 649/1939 [01:56<03:04,  7.00it/s]
 34%|███▎      | 651/1939 [01:57<04:04,  5.27it/s]
 34%|███▎      | 653/1939 [01:57<03:12,  6.67it/s]
 34%|███▍      | 655/1939 [01:57<03:39,  5.84it/s]
 34%|███▍      | 657/1939 [01:58<04:16,  4.99it/s]
 34%|███▍      | 658/1939 [01:58<04:20,  4.93it/s]
 34%|███▍      | 659/1939 [01:58<04:45,  4.49it/s]
 34%|███▍      | 661/1939 [01:59<03:28,  6.14it/s]
 34%|███▍      | 665/1939 [01:59<02:58,  7.12it/s]
 34%|███▍      | 666/1939 [02:00<04:13,  5.02it/s]
 34%|███▍      | 668/1939 [02:00<03:23,  6.26it/s]
 35%|███▍      | 670/1939 [02:00<02:41,  7.84it/s]
 35%|███▍      | 672/1939 [02:01<04:49,  4.38it/s]
 35%|███▍      | 675/1939 [02:01<03:11,  6.59it/s]
 35%|███▍      | 677/1939 [02:02<05:05,  4.13it/s]
 35%|███▌      | 680/1939 [02:03<05:47,  3.62it/s]
 35%|███▌      | 682/1939 [02:03<04:34,  4.58it/s]
 35%|███▌      | 684/1939 [02:04<06:11,  3.38it/s]
 35%|███▌      | 687/1939 [02:05<06:17,  3.31it/s]
 35%|███▌      | 688/1939 [02:05<05:40,  3.67it/s]
 36%|███▌      | 689/1939 [02:06<08:46,  2.38it/s]
 36%|███▌      | 691/1939 [02:06<06:11,  3.36it/s]
 36%|███▌      | 692/1939 [02:07<08:53,  2.34it/s]
 36%|███▌      | 693/1939 [02:08<11:26,  1.81it/s]
 36%|███▌      | 696/1939 [02:08<06:16,  3.30it/s]
 36%|███▋      | 703/1939 [02:08<02:36,  7.92it/s]
 37%|███▋      | 709/1939 [02:09<01:41, 12.18it/s]
 37%|███▋      | 713/1939 [02:09<01:29, 13.65it/s]
 37%|███▋      | 717/1939 [02:09<01:14, 16.47it/s]
 37%|███▋      | 722/1939 [02:09<00:56, 21.38it/s]
 37%|███▋      | 726/1939 [02:10<01:34, 12.84it/s]
 38%|███▊      | 729/1939 [02:10<01:26, 14.05it/s]
 38%|███▊      | 732/1939 [02:11<02:57,  6.80it/s]
 38%|███▊      | 734/1939 [02:12<03:51,  5.20it/s]
 38%|███▊      | 736/1939 [02:12<03:16,  6.13it/s]
 38%|███▊      | 738/1939 [02:12<02:49,  7.10it/s]
 38%|███▊      | 740/1939 [02:13<04:43,  4.23it/s]
 38%|███▊      | 742/1939 [02:14<05:26,  3.67it/s]
 38%|███▊      | 744/1939 [02:14<04:15,  4.67it/s]
 39%|███▊      | 749/1939 [02:15<04:30,  4.40it/s]
 39%|███▉      | 752/1939 [02:15<03:24,  5.81it/s]
 39%|███▉      | 755/1939 [02:16<04:25,  4.47it/s]
 39%|███▉      | 757/1939 [02:17<05:36,  3.51it/s]
 39%|███▉      | 759/1939 [02:17<04:31,  4.35it/s]
 39%|███▉      | 761/1939 [02:18<05:58,  3.29it/s]
 39%|███▉      | 763/1939 [02:19<06:56,  2.82it/s]
 39%|███▉      | 765/1939 [02:19<05:18,  3.68it/s]
 40%|███▉      | 767/1939 [02:21<07:29,  2.61it/s]
 40%|███▉      | 768/1939 [02:21<08:31,  2.29it/s]
 40%|███▉      | 769/1939 [02:22<08:04,  2.41it/s]
 40%|███▉      | 770/1939 [02:22<07:32,  2.59it/s]
 40%|███▉      | 772/1939 [02:22<06:15,  3.11it/s]
 40%|███▉      | 773/1939 [02:23<06:33,  2.96it/s]
 40%|███▉      | 775/1939 [02:23<04:26,  4.36it/s]
 40%|████      | 776/1939 [02:24<06:37,  2.93it/s]
 40%|████      | 777/1939 [02:24<07:47,  2.49it/s]
 40%|████      | 779/1939 [02:25<06:48,  2.84it/s]
 40%|████      | 780/1939 [02:25<06:57,  2.78it/s]
 40%|████      | 782/1939 [02:25<04:43,  4.09it/s]
 40%|████      | 784/1939 [02:26<04:27,  4.32it/s]
 41%|████      | 786/1939 [02:26<03:22,  5.68it/s]
 41%|████      | 787/1939 [02:26<03:51,  4.98it/s]
 41%|████      | 789/1939 [02:27<05:25,  3.53it/s]
 41%|████      | 791/1939 [02:27<03:54,  4.89it/s]
 41%|████      | 796/1939 [02:27<01:58,  9.63it/s]
 41%|████      | 799/1939 [02:28<03:30,  5.41it/s]
 41%|████▏     | 801/1939 [02:29<02:59,  6.35it/s]
 41%|████▏     | 804/1939 [02:29<02:59,  6.33it/s]
 42%|████▏     | 806/1939 [02:29<03:24,  5.55it/s]
 42%|████▏     | 809/1939 [02:30<03:46,  5.00it/s]
 42%|████▏     | 811/1939 [02:30<03:07,  6.01it/s]
 42%|████▏     | 813/1939 [02:32<05:50,  3.21it/s]
 42%|████▏     | 815/1939 [02:32<04:34,  4.09it/s]
 42%|████▏     | 817/1939 [02:34<07:55,  2.36it/s]
 42%|████▏     | 818/1939 [02:35<09:07,  2.05it/s]
 42%|████▏     | 819/1939 [02:35<09:27,  1.97it/s]
 42%|████▏     | 820/1939 [02:35<08:17,  2.25it/s]
 42%|████▏     | 821/1939 [02:36<08:14,  2.26it/s]
 42%|████▏     | 822/1939 [02:36<08:04,  2.31it/s]
 42%|████▏     | 823/1939 [02:37<07:42,  2.41it/s]
 43%|████▎     | 825/1939 [02:37<05:45,  3.23it/s]
 43%|████▎     | 827/1939 [02:37<03:59,  4.64it/s]
 43%|████▎     | 829/1939 [02:38<05:57,  3.10it/s]
 43%|████▎     | 831/1939 [02:38<04:20,  4.26it/s]
 43%|████▎     | 834/1939 [02:39<04:22,  4.21it/s]
 43%|████▎     | 838/1939 [02:39<02:38,  6.95it/s]
 44%|████▎     | 845/1939 [02:39<01:23, 13.07it/s]
 44%|████▍     | 850/1939 [02:39<01:03, 17.15it/s]
 44%|████▍     | 855/1939 [02:39<00:50, 21.40it/s]
 44%|████▍     | 859/1939 [02:40<01:23, 12.95it/s]
 44%|████▍     | 862/1939 [02:40<01:16, 14.09it/s]
 45%|████▍     | 865/1939 [02:41<01:44, 10.25it/s]
 45%|████▍     | 869/1939 [02:41<01:19, 13.41it/s]
 45%|████▌     | 875/1939 [02:41<00:54, 19.51it/s]
 45%|████▌     | 879/1939 [02:41<00:47, 22.14it/s]
 46%|████▌     | 885/1939 [02:41<00:36, 28.89it/s]
 46%|████▌     | 892/1939 [02:41<00:29, 35.83it/s]
 46%|████▋     | 899/1939 [02:42<01:12, 14.27it/s]
 47%|████▋     | 903/1939 [02:44<02:46,  6.22it/s]
 47%|████▋     | 906/1939 [02:44<02:26,  7.06it/s]
 47%|████▋     | 910/1939 [02:45<02:57,  5.79it/s]
 47%|████▋     | 912/1939 [02:45<02:37,  6.51it/s]
 47%|████▋     | 918/1939 [02:46<02:19,  7.31it/s]
 47%|████▋     | 921/1939 [02:46<01:57,  8.68it/s]
 48%|████▊     | 927/1939 [02:47<02:12,  7.62it/s]
 48%|████▊     | 930/1939 [02:48<03:00,  5.59it/s]
 48%|████▊     | 932/1939 [02:49<03:56,  4.26it/s]
 48%|████▊     | 933/1939 [02:50<05:17,  3.17it/s]
 48%|████▊     | 935/1939 [02:50<04:14,  3.94it/s]
 49%|████▊     | 942/1939 [02:50<02:03,  8.06it/s]
 49%|████▉     | 949/1939 [02:51<01:16, 13.00it/s]
 49%|████▉     | 955/1939 [02:51<00:56, 17.27it/s]
 49%|████▉     | 959/1939 [02:51<00:52, 18.84it/s]
 50%|████▉     | 966/1939 [02:51<00:37, 25.78it/s]
 50%|█████     | 971/1939 [02:54<03:01,  5.35it/s]
 50%|█████     | 975/1939 [02:56<04:07,  3.89it/s]
 50%|█████     | 978/1939 [02:56<04:05,  3.92it/s]
 51%|█████     | 980/1939 [02:57<04:31,  3.54it/s]
 51%|█████     | 982/1939 [02:58<04:37,  3.45it/s]
 51%|█████     | 984/1939 [02:58<03:50,  4.14it/s]
 51%|█████     | 986/1939 [02:58<03:08,  5.06it/s]
 51%|█████     | 990/1939 [02:58<02:04,  7.63it/s]
 51%|█████     | 992/1939 [02:59<03:09,  4.99it/s]
 51%|█████▏    | 994/1939 [02:59<02:37,  6.02it/s]
 51%|█████▏    | 997/1939 [03:00<03:28,  4.51it/s]
 52%|█████▏    | 999/1939 [03:01<03:32,  4.42it/s]
 52%|█████▏    | 1001/1939 [03:01<02:55,  5.36it/s]
 52%|█████▏    | 1003/1939 [03:02<03:48,  4.09it/s]
 52%|█████▏    | 1005/1939 [03:02<04:08,  3.77it/s]
 52%|█████▏    | 1006/1939 [03:03<05:12,  2.98it/s]
 52%|█████▏    | 1008/1939 [03:03<03:47,  4.09it/s]
 52%|█████▏    | 1009/1939 [03:03<03:50,  4.04it/s]
 52%|█████▏    | 1010/1939 [03:04<04:47,  3.23it/s]
 52%|█████▏    | 1011/1939 [03:04<05:27,  2.83it/s]
 52%|█████▏    | 1012/1939 [03:05<06:11,  2.50it/s]
 52%|█████▏    | 1013/1939 [03:05<06:52,  2.24it/s]
 52%|█████▏    | 1014/1939 [03:06<06:56,  2.22it/s]
 52%|█████▏    | 1015/1939 [03:06<07:03,  2.18it/s]
 52%|█████▏    | 1016/1939 [03:07<06:47,  2.27it/s]
 53%|█████▎    | 1018/1939 [03:08<07:08,  2.15it/s]
 53%|█████▎    | 1019/1939 [03:09<08:43,  1.76it/s]
 53%|█████▎    | 1022/1939 [03:10<06:54,  2.21it/s]
 53%|█████▎    | 1024/1939 [03:10<04:53,  3.11it/s]
 53%|█████▎    | 1027/1939 [03:11<04:54,  3.10it/s]
 53%|█████▎    | 1030/1939 [03:11<03:59,  3.79it/s]
 53%|█████▎    | 1034/1939 [03:11<02:30,  6.03it/s]
 54%|█████▎    | 1040/1939 [03:12<01:49,  8.19it/s]
 54%|█████▎    | 1042/1939 [03:12<01:41,  8.86it/s]
 54%|█████▍    | 1045/1939 [03:12<01:41,  8.83it/s]
 54%|█████▍    | 1047/1939 [03:12<01:31,  9.74it/s]
 54%|█████▍    | 1049/1939 [03:13<02:09,  6.87it/s]
 54%|█████▍    | 1051/1939 [03:14<02:59,  4.95it/s]
 54%|█████▍    | 1052/1939 [03:14<03:36,  4.10it/s]
 54%|█████▍    | 1053/1939 [03:15<04:01,  3.66it/s]
 54%|█████▍    | 1054/1939 [03:15<04:14,  3.48it/s]
 54%|█████▍    | 1056/1939 [03:16<05:38,  2.61it/s]
 55%|█████▍    | 1057/1939 [03:17<07:21,  2.00it/s]
 55%|█████▍    | 1059/1939 [03:18<07:30,  1.95it/s]
 55%|█████▍    | 1060/1939 [03:19<08:53,  1.65it/s]
 55%|█████▍    | 1063/1939 [03:19<04:57,  2.94it/s]
 55%|█████▌    | 1068/1939 [03:20<03:55,  3.71it/s]
 55%|█████▌    | 1071/1939 [03:20<02:53,  5.00it/s]
 55%|█████▌    | 1074/1939 [03:21<02:31,  5.70it/s]
 55%|█████▌    | 1076/1939 [03:21<02:08,  6.71it/s]
 56%|█████▌    | 1080/1939 [03:21<02:04,  6.89it/s]
 56%|█████▌    | 1082/1939 [03:22<01:51,  7.67it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 309.85it/s]
 34%|███▎      | 101/300 [06:11<3:32:59, 64.22s/it]

[[np.int64(0), False, 5], [np.int64(1), False, 10], [np.int64(2), False, 6], [np.int64(3), False, 8], [np.int64(4), False, 0], [np.int64(7), False, 13], [np.int64(8), False, 4], [np.int64(9), False, 10], [np.int64(11), False, 4], [np.int64(12), False, 13], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8830, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.8180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0096, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [06:11<2:49:21, 51.32s/it]

tensor(12.8285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2110, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [06:11<1:46:32, 32.62s/it]

tensor(12.8641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4022, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5358, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6225, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [06:11<1:09:24, 21.47s/it]

tensor(12.9907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6709, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [06:11<46:12, 14.44s/it]

tensor(12.9900, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7351, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9684, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8142, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8958, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [06:11<31:12,  9.86s/it]

tensor(12.9127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9565, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8904, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9931, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [06:12<21:17,  6.80s/it]

tensor(12.8699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0071, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [06:12<14:38,  4.72s/it]

tensor(12.8475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8244, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0339, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0570, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [06:12<10:08,  3.30s/it]

tensor(12.7922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0869, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1049, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [06:12<07:03,  2.33s/it]

tensor(12.7748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1186, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [06:12<04:56,  1.65s/it]

tensor(12.7628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1395, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1565, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1756, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [06:13<03:29,  1.18s/it]

tensor(12.7204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2075, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2242, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [06:13<02:30,  1.17it/s]

tensor(12.6937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2503, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [06:13<01:48,  1.60it/s]

tensor(12.6822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2621, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2782, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2923, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [06:13<01:20,  2.15it/s]

tensor(12.6484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2892, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2912, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [06:13<01:00,  2.82it/s]

tensor(12.6226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3053, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [06:14<00:46,  3.60it/s]

tensor(12.6108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3052, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2836, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5900, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2961, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [06:14<00:36,  4.49it/s]

tensor(12.5804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2963, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2668, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [06:14<00:30,  5.43it/s]

tensor(12.5639, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2832, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [06:14<00:25,  6.36it/s]

tensor(12.5572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2824, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2511, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2633, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [06:14<00:22,  7.22it/s]

tensor(12.5367, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2788, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2973, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [06:14<00:19,  8.01it/s]

tensor(12.5200, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3124, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [06:15<00:18,  8.66it/s]

tensor(12.5108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3050, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3275, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4948, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3469, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [06:15<00:16,  9.13it/s]

tensor(12.4884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3573, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3713, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [06:15<00:15,  9.55it/s]

tensor(12.4778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3806, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [06:15<00:15,  9.86it/s]

tensor(12.4733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3871, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([117,  84, 129, 213, 196,  49, 112, 133, 204,  66, 332,  32,  80, 192])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 4/1939 [00:00<00:52, 36.71it/s]
  0%|          | 9/1939 [00:00<00:49, 39.13it/s]
  1%|          | 13/1939 [00:00<00:51, 37.61it/s]
  1%|          | 18/1939 [00:00<00:48, 39.78it/s]
  1%|▏         | 25/1939 [00:00<00:39, 48.33it/s]
  2%|▏         | 30/1939 [00:00<00:47, 39.93it/s]
  2%|▏         | 35/1939 [00:00<00:54, 35.20it/s]
  2%|▏         | 39/1939 [00:01<00:52, 35.92it/s]
  2%|▏         | 43/1939 [00:01<01:42, 18.55it/s]
  2%|▏         | 48/1939 [00:01<01:22, 23.06it/s]
  3%|▎         | 52/1939 [00:01<01:41, 18.57it/s]
  3%|▎         | 55/1939 [00:02<02:16, 13.81it/s]
  3%|▎         | 58/1939 [00:02<02:15, 13.85it/s]
  3%|▎         | 60/1939 [00:02<02:12, 14.15it/s]
  3%|▎         | 62/1939 [00:02<02:04, 15.07it/s]
  3%|▎         | 66/1939 [00:03<02:05, 14.89it/s]
  4%|▎         | 68/1939 [00:03<02:02, 15.26it/s]
  4%|▍         | 73/1939 [00:03<01:53, 16.39it/s]
  4%|▍         | 76/1939 [00:03<01:51, 16.75it/s]
  4%|▍         | 78/1939 [00:03<02:19, 13.38it/s]
  4%|▍         | 80/1939 [00:04<02:50, 10.90it/s]
  4%|▍         | 82/1939 [00:04<03:42,  8.34it/s]
  4%|▍         | 84/1939 [00:04<03:47,  8.16it/s]
  4%|▍         | 86/1939 [00:05<03:48,  8.10it/s]
  5%|▍         | 88/1939 [00:05<03:12,  9.63it/s]
  5%|▍         | 94/1939 [00:05<02:07, 14.47it/s]
  5%|▌         | 97/1939 [00:05<01:53, 16.26it/s]
  5%|▌         | 99/1939 [00:05<01:55, 15.93it/s]
  5%|▌         | 101/1939 [00:06<02:41, 11.39it/s]
  5%|▌         | 106/1939 [00:06<01:47, 16.99it/s]
  6%|▌         | 112/1939 [00:06<01:14, 24.38it/s]
  6%|▌         | 116/1939 [00:06<01:11, 25.51it/s]
  6%|▌         | 120/1939 [00:07<02:24, 12.58it/s]
  6%|▋         | 123/1939 [00:07<02:40, 11.31it/s]
  7%|▋         | 128/1939 [00:07<02:17, 13.19it/s]
  7%|▋         | 131/1939 [00:07<02:00, 14.96it/s]
  7%|▋         | 134/1939 [00:08<02:19, 12.92it/s]
  7%|▋         | 137/1939 [00:08<02:25, 12.35it/s]
  7%|▋         | 139/1939 [00:08<02:17, 13.10it/s]
  7%|▋         | 145/1939 [00:08<01:52, 15.95it/s]
  8%|▊         | 148/1939 [00:09<01:44, 17.20it/s]
  8%|▊         | 153/1939 [00:09<01:38, 18.08it/s]
  8%|▊         | 155/1939 [00:09<01:38, 18.15it/s]
  8%|▊         | 158/1939 [00:09<01:50, 16.19it/s]
  8%|▊         | 160/1939 [00:09<02:12, 13.45it/s]
  8%|▊         | 162/1939 [00:10<03:00,  9.87it/s]
  8%|▊         | 164/1939 [00:10<03:13,  9.19it/s]
  9%|▊         | 167/1939 [00:10<02:30, 11.77it/s]
  9%|▉         | 173/1939 [00:10<01:31, 19.29it/s]
  9%|▉         | 179/1939 [00:10<01:07, 25.95it/s]
 10%|▉         | 185/1939 [00:10<00:55, 31.66it/s]
 10%|▉         | 189/1939 [00:11<00:55, 31.38it/s]
 10%|█         | 196/1939 [00:11<00:44, 38.79it/s]
 10%|█         | 202/1939 [00:11<01:00, 28.89it/s]
 11%|█         | 206/1939 [00:12<01:39, 17.41it/s]
 11%|█         | 209/1939 [00:12<01:34, 18.24it/s]
 11%|█         | 215/1939 [00:12<01:12, 23.80it/s]
 11%|█▏        | 222/1939 [00:12<00:56, 30.56it/s]
 12%|█▏        | 228/1939 [00:12<01:07, 25.44it/s]
 12%|█▏        | 232/1939 [00:12<01:05, 26.22it/s]
 12%|█▏        | 236/1939 [00:13<01:42, 16.61it/s]
 12%|█▏        | 239/1939 [00:13<01:58, 14.36it/s]
 12%|█▏        | 242/1939 [00:14<02:52,  9.84it/s]
 13%|█▎        | 244/1939 [00:14<03:12,  8.79it/s]
 13%|█▎        | 246/1939 [00:15<03:43,  7.58it/s]
 13%|█▎        | 248/1939 [00:15<03:39,  7.72it/s]
 13%|█▎        | 250/1939 [00:15<03:14,  8.68it/s]
 50%|█████     | 150/300 [06:33<00:15,  9.86it/s]]
 13%|█▎        | 259/1939 [00:15<02:01, 13.82it/s]
 14%|█▎        | 262/1939 [00:16<02:14, 12.51it/s]
 14%|█▍        | 268/1939 [00:16<01:28, 18.95it/s]
 14%|█▍        | 275/1939 [00:16<01:02, 26.51it/s]
 14%|█▍        | 281/1939 [00:16<01:12, 22.83it/s]
 15%|█▍        | 285/1939 [00:17<01:29, 18.38it/s]
 15%|█▍        | 288/1939 [00:17<01:42, 16.12it/s]
 15%|█▌        | 291/1939 [00:17<01:35, 17.33it/s]
 15%|█▌        | 294/1939 [00:17<01:44, 15.79it/s]
 15%|█▌        | 297/1939 [00:17<01:31, 17.95it/s]
 16%|█▌        | 302/1939 [00:17<01:12, 22.60it/s]
 16%|█▌        | 305/1939 [00:18<01:08, 23.93it/s]
 16%|█▌        | 311/1939 [00:18<00:51, 31.78it/s]
 16%|█▌        | 315/1939 [00:18<00:57, 28.07it/s]
 16%|█▋        | 319/1939 [00:18<00:58, 27.63it/s]
 17%|█▋        | 323/1939 [00:18<01:30, 17.83it/s]
 17%|█▋        | 327/1939 [00:19<01:16, 20.99it/s]
 17%|█▋        | 334/1939 [00:19<00:54, 29.48it/s]
 18%|█▊        | 340/1939 [00:19<00:45, 35.45it/s]
 18%|█▊        | 347/1939 [00:19<00:36, 43.08it/s]
 18%|█▊        | 353/1939 [00:19<01:12, 21.89it/s]
 18%|█▊        | 357/1939 [00:20<01:33, 16.98it/s]
 19%|█▊        | 361/1939 [00:20<01:20, 19.57it/s]
 19%|█▉        | 365/1939 [00:20<01:10, 22.39it/s]
 19%|█▉        | 369/1939 [00:20<01:07, 23.36it/s]
 19%|█▉        | 373/1939 [00:20<01:11, 21.81it/s]
 19%|█▉        | 376/1939 [00:21<01:20, 19.34it/s]
 20%|█▉        | 379/1939 [00:21<01:17, 20.08it/s]
 20%|█▉        | 382/1939 [00:21<01:41, 15.39it/s]
 20%|█▉        | 384/1939 [00:21<02:09, 12.05it/s]
 20%|█▉        | 386/1939 [00:21<01:59, 12.96it/s]
 20%|██        | 388/1939 [00:22<02:11, 11.81it/s]
 20%|██        | 390/1939 [00:22<02:27, 10.47it/s]
 20%|██        | 392/1939 [00:22<02:44,  9.41it/s]
 20%|██        | 394/1939 [00:22<02:28, 10.41it/s]
 20%|██        | 396/1939 [00:22<02:14, 11.48it/s]
 21%|██        | 398/1939 [00:23<02:19, 11.08it/s]
 21%|██        | 400/1939 [00:23<02:01, 12.70it/s]
 21%|██        | 402/1939 [00:23<01:49, 14.10it/s]
 21%|██        | 404/1939 [00:23<01:59, 12.86it/s]
 21%|██        | 406/1939 [00:23<02:05, 12.22it/s]
 21%|██        | 408/1939 [00:23<02:00, 12.68it/s]
 21%|██        | 411/1939 [00:24<01:33, 16.26it/s]
 21%|██▏       | 414/1939 [00:24<01:20, 19.04it/s]
 22%|██▏       | 417/1939 [00:24<01:44, 14.56it/s]
 22%|██▏       | 419/1939 [00:24<01:40, 15.09it/s]
 22%|██▏       | 421/1939 [00:24<01:39, 15.31it/s]
 22%|██▏       | 423/1939 [00:24<02:08, 11.76it/s]
 22%|██▏       | 426/1939 [00:25<02:00, 12.53it/s]
 22%|██▏       | 428/1939 [00:25<02:02, 12.33it/s]
 22%|██▏       | 430/1939 [00:25<01:59, 12.60it/s]
 22%|██▏       | 432/1939 [00:25<01:52, 13.37it/s]
 23%|██▎       | 439/1939 [00:25<01:01, 24.21it/s]
 23%|██▎       | 443/1939 [00:25<00:56, 26.46it/s]
 23%|██▎       | 447/1939 [00:25<00:51, 28.94it/s]
 23%|██▎       | 453/1939 [00:26<00:46, 32.08it/s]
 24%|██▎       | 457/1939 [00:26<00:47, 30.98it/s]
 24%|██▍       | 463/1939 [00:26<00:40, 36.75it/s]
 24%|██▍       | 470/1939 [00:26<00:33, 43.47it/s]
 25%|██▍       | 476/1939 [00:26<00:31, 46.54it/s]
 25%|██▍       | 482/1939 [00:26<00:30, 48.53it/s]
 25%|██▌       | 487/1939 [00:26<00:33, 43.40it/s]
 25%|██▌       | 492/1939 [00:27<01:00, 23.94it/s]
 26%|██▌       | 498/1939 [00:27<00:48, 29.49it/s]
 26%|██▌       | 506/1939 [00:27<00:37, 38.16it/s]
 27%|██▋       | 514/1939 [00:27<00:30, 46.11it/s]
 27%|██▋       | 522/1939 [00:27<00:27, 51.94it/s]
 27%|██▋       | 530/1939 [00:27<00:24, 57.01it/s]
 28%|██▊       | 537/1939 [00:28<00:39, 35.05it/s]
 28%|██▊       | 543/1939 [00:28<00:43, 32.08it/s]
 28%|██▊       | 548/1939 [00:28<00:54, 25.52it/s]
 28%|██▊       | 552/1939 [00:29<01:04, 21.62it/s]
 29%|██▊       | 555/1939 [00:29<01:00, 22.80it/s]
 29%|██▉       | 562/1939 [00:29<00:45, 29.94it/s]
 29%|██▉       | 568/1939 [00:29<00:38, 35.17it/s]
 30%|██▉       | 573/1939 [00:29<01:04, 21.34it/s]
 30%|██▉       | 577/1939 [00:30<01:30, 15.09it/s]
 30%|██▉       | 580/1939 [00:30<01:38, 13.76it/s]
 30%|███       | 583/1939 [00:30<01:47, 12.61it/s]
 30%|███       | 585/1939 [00:31<02:01, 11.15it/s]
 30%|███       | 588/1939 [00:31<01:42, 13.23it/s]
 31%|███       | 594/1939 [00:31<01:08, 19.51it/s]
 31%|███       | 599/1939 [00:31<01:08, 19.54it/s]
 31%|███       | 602/1939 [00:32<01:24, 15.85it/s]
 31%|███▏      | 607/1939 [00:32<01:09, 19.12it/s]
 31%|███▏      | 610/1939 [00:32<01:13, 18.07it/s]
 32%|███▏      | 613/1939 [00:32<01:47, 12.34it/s]
 32%|███▏      | 615/1939 [00:33<01:52, 11.75it/s]
 32%|███▏      | 617/1939 [00:33<01:54, 11.53it/s]
 32%|███▏      | 619/1939 [00:33<02:07, 10.35it/s]
 32%|███▏      | 621/1939 [00:33<02:24,  9.12it/s]
 32%|███▏      | 623/1939 [00:33<02:03, 10.65it/s]
 32%|███▏      | 629/1939 [00:34<01:10, 18.54it/s]
 33%|███▎      | 632/1939 [00:34<01:14, 17.62it/s]
 33%|███▎      | 635/1939 [00:34<01:13, 17.75it/s]
 33%|███▎      | 638/1939 [00:34<01:40, 12.92it/s]
 33%|███▎      | 640/1939 [00:34<01:34, 13.70it/s]
 33%|███▎      | 642/1939 [00:35<01:29, 14.55it/s]
 33%|███▎      | 646/1939 [00:35<01:07, 19.07it/s]
 33%|███▎      | 649/1939 [00:35<01:20, 16.12it/s]
 34%|███▎      | 651/1939 [00:35<01:38, 13.02it/s]
 34%|███▎      | 653/1939 [00:35<01:32, 13.97it/s]
 34%|███▍      | 656/1939 [00:36<01:36, 13.33it/s]
 34%|███▍      | 658/1939 [00:36<01:50, 11.55it/s]
 34%|███▍      | 661/1939 [00:36<01:31, 13.91it/s]
 34%|███▍      | 665/1939 [00:36<01:27, 14.61it/s]
 34%|███▍      | 667/1939 [00:36<01:41, 12.53it/s]
 35%|███▍      | 670/1939 [00:37<01:28, 14.31it/s]
 35%|███▍      | 672/1939 [00:37<01:43, 12.24it/s]
 35%|███▍      | 674/1939 [00:37<01:36, 13.15it/s]
 35%|███▍      | 676/1939 [00:37<01:31, 13.79it/s]
 35%|███▌      | 680/1939 [00:37<01:26, 14.49it/s]
 35%|███▌      | 682/1939 [00:37<01:22, 15.18it/s]
 35%|███▌      | 684/1939 [00:37<01:20, 15.52it/s]
 35%|███▌      | 686/1939 [00:38<01:23, 15.08it/s]
 35%|███▌      | 688/1939 [00:38<01:21, 15.42it/s]
 36%|███▌      | 690/1939 [00:38<01:34, 13.28it/s]
 36%|███▌      | 692/1939 [00:38<01:27, 14.20it/s]
 36%|███▌      | 698/1939 [00:38<00:53, 23.26it/s]
 36%|███▋      | 705/1939 [00:38<00:36, 33.54it/s]
 37%|███▋      | 711/1939 [00:38<00:31, 38.84it/s]
 37%|███▋      | 716/1939 [00:39<00:29, 41.53it/s]
 37%|███▋      | 722/1939 [00:39<00:27, 44.77it/s]
 38%|███▊      | 728/1939 [00:39<00:25, 47.34it/s]
 38%|███▊      | 733/1939 [00:39<00:51, 23.37it/s]
 38%|███▊      | 737/1939 [00:39<00:55, 21.69it/s]
 38%|███▊      | 741/1939 [00:40<01:04, 18.71it/s]
 38%|███▊      | 744/1939 [00:40<01:14, 16.07it/s]
 39%|███▊      | 748/1939 [00:40<01:01, 19.34it/s]
 39%|███▉      | 752/1939 [00:40<00:55, 21.44it/s]
 39%|███▉      | 755/1939 [00:40<00:58, 20.27it/s]
 39%|███▉      | 758/1939 [00:41<01:03, 18.62it/s]
 39%|███▉      | 761/1939 [00:41<01:13, 15.96it/s]
 39%|███▉      | 763/1939 [00:41<01:28, 13.35it/s]
 40%|███▉      | 766/1939 [00:41<01:38, 11.95it/s]
 40%|███▉      | 768/1939 [00:42<02:11,  8.90it/s]
 40%|███▉      | 770/1939 [00:42<02:06,  9.28it/s]
 40%|███▉      | 772/1939 [00:42<02:10,  8.98it/s]
 40%|███▉      | 774/1939 [00:43<02:00,  9.63it/s]
 40%|████      | 776/1939 [00:43<01:58,  9.79it/s]
 40%|████      | 778/1939 [00:43<01:45, 10.97it/s]
 40%|████      | 780/1939 [00:43<02:20,  8.25it/s]
 40%|████      | 782/1939 [00:43<02:00,  9.59it/s]
 40%|████      | 784/1939 [00:44<02:24,  7.99it/s]
 41%|████      | 786/1939 [00:44<02:01,  9.51it/s]
 41%|████      | 788/1939 [00:44<02:07,  9.06it/s]
 41%|████      | 790/1939 [00:44<02:15,  8.47it/s]
 41%|████      | 794/1939 [00:44<01:26, 13.26it/s]
 41%|████      | 798/1939 [00:45<01:20, 14.10it/s]
 41%|████▏     | 800/1939 [00:45<01:16, 14.81it/s]
 41%|████▏     | 803/1939 [00:45<01:06, 17.11it/s]
 42%|████▏     | 806/1939 [00:46<02:02,  9.24it/s]
 42%|████▏     | 809/1939 [00:46<02:03,  9.13it/s]
 42%|████▏     | 811/1939 [00:46<01:53,  9.97it/s]
 42%|████▏     | 813/1939 [00:46<02:18,  8.11it/s]
 42%|████▏     | 816/1939 [00:47<02:07,  8.79it/s]
 42%|████▏     | 818/1939 [00:47<02:36,  7.17it/s]
 42%|████▏     | 819/1939 [00:47<02:59,  6.25it/s]
 42%|████▏     | 820/1939 [00:48<03:03,  6.11it/s]
 42%|████▏     | 821/1939 [00:48<03:28,  5.37it/s]
 42%|████▏     | 822/1939 [00:48<03:34,  5.20it/s]
 42%|████▏     | 823/1939 [00:48<03:28,  5.35it/s]
 43%|████▎     | 825/1939 [00:48<02:35,  7.18it/s]
 43%|████▎     | 828/1939 [00:49<01:45, 10.58it/s]
 43%|████▎     | 832/1939 [00:49<01:09, 15.92it/s]
 43%|████▎     | 839/1939 [00:49<00:41, 26.32it/s]
 44%|████▎     | 845/1939 [00:49<00:33, 33.09it/s]
 44%|████▍     | 851/1939 [00:49<00:28, 37.96it/s]
 44%|████▍     | 856/1939 [00:49<00:26, 40.93it/s]
 44%|████▍     | 861/1939 [00:50<00:48, 22.23it/s]
 45%|████▍     | 867/1939 [00:50<00:38, 27.98it/s]
 45%|████▍     | 872/1939 [00:50<00:35, 30.09it/s]
 45%|████▌     | 878/1939 [00:50<00:29, 35.59it/s]
 46%|████▌     | 883/1939 [00:50<00:30, 34.94it/s]
 46%|████▌     | 889/1939 [00:50<00:26, 39.85it/s]
 46%|████▌     | 896/1939 [00:50<00:23, 45.17it/s]
 47%|████▋     | 902/1939 [00:51<00:44, 23.39it/s]
 47%|████▋     | 906/1939 [00:51<00:46, 22.06it/s]
 47%|████▋     | 910/1939 [00:51<00:51, 19.94it/s]
 47%|████▋     | 913/1939 [00:51<00:51, 20.11it/s]
 47%|████▋     | 918/1939 [00:52<00:54, 18.80it/s]
 47%|████▋     | 921/1939 [00:52<00:55, 18.42it/s]
 48%|████▊     | 924/1939 [00:52<00:51, 19.58it/s]
 48%|████▊     | 927/1939 [00:52<00:57, 17.58it/s]
 48%|████▊     | 930/1939 [00:53<01:10, 14.28it/s]
 48%|████▊     | 932/1939 [00:53<01:21, 12.37it/s]
 48%|████▊     | 935/1939 [00:53<01:06, 15.02it/s]
 49%|████▊     | 942/1939 [00:53<00:40, 24.49it/s]
 49%|████▉     | 947/1939 [00:53<00:34, 29.16it/s]
 49%|████▉     | 953/1939 [00:53<00:27, 35.63it/s]
 49%|████▉     | 959/1939 [00:53<00:24, 40.16it/s]
 50%|████▉     | 966/1939 [00:53<00:21, 45.02it/s]
 50%|█████     | 971/1939 [00:54<00:48, 20.03it/s]
 50%|█████     | 975/1939 [00:55<01:05, 14.79it/s]
 50%|█████     | 978/1939 [00:55<01:09, 13.78it/s]
 51%|█████     | 982/1939 [00:55<01:04, 14.86it/s]
 51%|█████     | 986/1939 [00:55<00:55, 17.18it/s]
 51%|█████     | 990/1939 [00:55<00:47, 20.00it/s]
 51%|█████     | 993/1939 [00:56<01:02, 15.25it/s]
 51%|█████▏    | 997/1939 [00:56<01:05, 14.29it/s]
 52%|█████▏    | 999/1939 [00:56<01:14, 12.60it/s]
 52%|█████▏    | 1001/1939 [00:56<01:11, 13.17it/s]
 52%|█████▏    | 1003/1939 [00:57<01:19, 11.78it/s]
 52%|█████▏    | 1005/1939 [00:57<01:33, 10.00it/s]
 52%|█████▏    | 1007/1939 [00:57<01:36,  9.68it/s]
 52%|█████▏    | 1009/1939 [00:57<01:43,  9.01it/s]
 52%|█████▏    | 1010/1939 [00:58<01:53,  8.19it/s]
 52%|█████▏    | 1011/1939 [00:58<02:04,  7.46it/s]
 52%|█████▏    | 1012/1939 [00:58<02:09,  7.17it/s]
 52%|█████▏    | 1014/1939 [00:58<02:07,  7.26it/s]
 52%|█████▏    | 1016/1939 [00:58<01:58,  7.80it/s]
 53%|█████▎    | 1018/1939 [00:59<01:39,  9.25it/s]
 53%|█████▎    | 1019/1939 [00:59<01:41,  9.07it/s]
 53%|█████▎    | 1021/1939 [00:59<01:28, 10.34it/s]
 53%|█████▎    | 1023/1939 [00:59<01:46,  8.60it/s]
 53%|█████▎    | 1027/1939 [00:59<01:15, 12.01it/s]
 53%|█████▎    | 1030/1939 [00:59<01:03, 14.23it/s]
 53%|█████▎    | 1033/1939 [01:00<00:53, 16.93it/s]
 54%|█████▎    | 1040/1939 [01:00<00:32, 27.43it/s]
 54%|█████▍    | 1045/1939 [01:00<00:38, 23.49it/s]
 54%|█████▍    | 1048/1939 [01:00<00:50, 17.52it/s]
 54%|█████▍    | 1051/1939 [01:01<01:01, 14.37it/s]
 54%|█████▍    | 1053/1939 [01:01<01:24, 10.55it/s]
 54%|█████▍    | 1055/1939 [01:01<01:26, 10.21it/s]
 55%|█████▍    | 1057/1939 [01:01<01:23, 10.50it/s]
 55%|█████▍    | 1059/1939 [01:02<01:24, 10.43it/s]
 55%|█████▍    | 1061/1939 [01:02<01:20, 10.93it/s]
 55%|█████▍    | 1063/1939 [01:02<01:10, 12.46it/s]
 55%|█████▌    | 1070/1939 [01:02<00:37, 23.08it/s]
 55%|█████▌    | 1076/1939 [01:02<00:29, 29.75it/s]
 56%|█████▌    | 1080/1939 [01:02<00:37, 22.81it/s]
 56%|█████▌    | 1083/1939 [01:03<00:41, 20.59it/s]
 56%|█████▌    | 1088/1939 [01:03<00:41, 20.64it/s]
 56%|█████▋    | 1091/1939 [01:03<00:40, 20.94it/s]
 56%|█████▋    | 1094/1939 [01:03<01:05, 12.97it/s]
 57%|█████▋    | 1096/1939 [01:04<01:14, 11.35it/s]
 57%|█████▋    | 1098/1939 [01:04<01:21, 10.36it/s]
 57%|█████▋    | 1100/1939 [01:04<01:12, 11.65it/s]
 57%|█████▋    | 1102/1939 [01:04<01:22, 10.17it/s]
 57%|█████▋    | 1104/1939 [01:05<01:36,  8.65it/s]
 57%|█████▋    | 1106/1939 [01:05<01:41,  8.19it/s]
 57%|█████▋    | 1109/1939 [01:05<01:29,  9.29it/s]
 57%|█████▋    | 1111/1939 [01:05<01:20, 10.27it/s]
 58%|█████▊    | 1116/1939 [01:06<01:06, 12.44it/s]
 58%|█████▊    | 1118/1939 [01:06<01:02, 13.24it/s]
 58%|█████▊    | 1121/1939 [01:06<00:51, 15.84it/s]
 58%|█████▊    | 1123/1939 [01:06<00:50, 16.01it/s]
 58%|█████▊    | 1125/1939 [01:06<00:49, 16.44it/s]
 58%|█████▊    | 1128/1939 [01:06<00:42, 19.24it/s]
 58%|█████▊    | 1131/1939 [01:06<00:53, 15.03it/s]
 58%|█████▊    | 1133/1939 [01:07<00:53, 14.95it/s]
 59%|█████▊    | 1137/1939 [01:07<01:00, 13.19it/s]
 59%|█████▊    | 1139/1939 [01:07<00:56, 14.26it/s]
 59%|█████▉    | 1142/1939 [01:07<00:53, 14.77it/s]
 59%|█████▉    | 1144/1939 [01:08<01:11, 11.05it/s]
 59%|█████▉    | 1146/1939 [01:08<01:20,  9.90it/s]
 59%|█████▉    | 1148/1939 [01:08<01:41,  7.77it/s]
 59%|█████▉    | 1150/1939 [01:09<01:46,  7.38it/s]
 59%|█████▉    | 1151/1939 [01:09<01:59,  6.61it/s]
 59%|█████▉    | 1153/1939 [01:09<02:03,  6.37it/s]
 60%|█████▉    | 1156/1939 [01:09<01:26,  9.10it/s]
 60%|█████▉    | 1162/1939 [01:09<00:47, 16.44it/s]
 60%|██████    | 1165/1939 [01:10<01:03, 12.19it/s]
 60%|██████    | 1168/1939 [01:10<00:53, 14.42it/s]
 61%|██████    | 1174/1939 [01:10<00:35, 21.42it/s]
 61%|██████    | 1178/1939 [01:10<00:40, 18.89it/s]
 61%|██████    | 1181/1939 [01:11<00:51, 14.64it/s]
 61%|██████    | 1184/1939 [01:11<01:00, 12.48it/s]
 61%|██████    | 1186/1939 [01:11<01:05, 11.58it/s]
 61%|██████▏   | 1189/1939 [01:11<00:54, 13.73it/s]
 61%|██████▏   | 1191/1939 [01:11<00:57, 12.91it/s]
 62%|██████▏   | 1193/1939 [01:12<01:06, 11.23it/s]
 62%|██████▏   | 1195/1939 [01:12<01:05, 11.41it/s]
 62%|██████▏   | 1197/1939 [01:12<01:03, 11.63it/s]
 62%|██████▏   | 1199/1939 [01:12<00:58, 12.72it/s]
 62%|██████▏   | 1202/1939 [01:12<00:46, 15.76it/s]
 62%|██████▏   | 1208/1939 [01:12<00:31, 23.15it/s]
 63%|██████▎   | 1212/1939 [01:13<00:27, 26.86it/s]
 63%|██████▎   | 1216/1939 [01:13<00:24, 29.60it/s]
 63%|██████▎   | 1220/1939 [01:13<00:55, 13.05it/s]
 63%|██████▎   | 1226/1939 [01:14<00:47, 15.01it/s]
 63%|██████▎   | 1229/1939 [01:14<00:43, 16.42it/s]
 64%|██████▎   | 1232/1939 [01:14<00:43, 16.37it/s]
 64%|██████▎   | 1235/1939 [01:14<00:38, 18.10it/s]
 64%|██████▍   | 1239/1939 [01:14<00:40, 17.13it/s]
 64%|██████▍   | 1242/1939 [01:15<00:47, 14.69it/s]
 64%|██████▍   | 1244/1939 [01:15<00:45, 15.23it/s]
 64%|██████▍   | 1246/1939 [01:15<00:52, 13.17it/s]
 64%|██████▍   | 1248/1939 [01:15<00:50, 13.65it/s]
 65%|██████▍   | 1251/1939 [01:15<00:52, 13.13it/s]
 65%|██████▍   | 1253/1939 [01:15<00:53, 12.89it/s]
 65%|██████▍   | 1255/1939 [01:16<00:52, 12.92it/s]
 65%|██████▍   | 1257/1939 [01:16<00:49, 13.85it/s]
 65%|██████▍   | 1259/1939 [01:16<00:47, 14.42it/s]
 65%|██████▌   | 1265/1939 [01:16<00:27, 24.45it/s]
 65%|██████▌   | 1268/1939 [01:16<00:33, 20.02it/s]
 66%|██████▌   | 1271/1939 [01:16<00:37, 17.99it/s]
 66%|██████▌   | 1274/1939 [01:17<00:46, 14.36it/s]
 66%|██████▌   | 1279/1939 [01:17<00:33, 19.67it/s]
 66%|██████▋   | 1285/1939 [01:17<00:24, 26.90it/s]
 66%|██████▋   | 1289/1939 [01:17<00:32, 19.80it/s]
 67%|██████▋   | 1293/1939 [01:18<00:36, 17.69it/s]
 67%|██████▋   | 1296/1939 [01:18<00:34, 18.57it/s]
 67%|██████▋   | 1302/1939 [01:18<00:25, 25.12it/s]
 67%|██████▋   | 1308/1939 [01:18<00:20, 31.16it/s]
 68%|██████▊   | 1312/1939 [01:18<00:28, 21.78it/s]
 68%|██████▊   | 1316/1939 [01:19<00:32, 19.27it/s]
 68%|██████▊   | 1321/1939 [01:19<00:26, 23.71it/s]
 68%|██████▊   | 1325/1939 [01:19<00:31, 19.53it/s]
 68%|██████▊   | 1328/1939 [01:19<00:31, 19.70it/s]
 69%|██████▊   | 1333/1939 [01:19<00:24, 24.52it/s]
 69%|██████▉   | 1339/1939 [01:19<00:19, 30.62it/s]
 69%|██████▉   | 1343/1939 [01:20<00:32, 18.53it/s]
 69%|██████▉   | 1346/1939 [01:20<00:31, 18.96it/s]
 70%|██████▉   | 1349/1939 [01:20<00:34, 17.11it/s]
 70%|██████▉   | 1352/1939 [01:20<00:30, 19.06it/s]
 70%|██████▉   | 1355/1939 [01:21<00:46, 12.56it/s]
 70%|███████   | 1358/1939 [01:21<00:40, 14.39it/s]
 70%|███████   | 1361/1939 [01:21<00:39, 14.46it/s]
 70%|███████   | 1364/1939 [01:21<00:43, 13.13it/s]
 70%|███████   | 1366/1939 [01:22<00:50, 11.33it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 307.78it/s]
 50%|█████     | 151/300 [08:13<51:36, 20.78s/it]

[[np.int64(0), False, 4], [np.int64(1), False, 12], [np.int64(2), False, 3], [np.int64(3), False, 10], [np.int64(4), False, 13], [np.int64(5), False, 13], [np.int64(6), False, 2], [np.int64(7), False, 12], [np.int64(8), False, 10], [np.int64(9), False, 7], [np.int64(11), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1740, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.4667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2359, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [08:13<41:01, 16.63s/it]

tensor(12.4678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3369, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [08:13<23:55,  9.83s/it]

tensor(12.4733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4071, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4266, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4237, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [08:13<14:02,  5.85s/it]

tensor(12.4809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4181, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [08:13<08:49,  3.73s/it]

tensor(12.4737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4122, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4207, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [08:13<05:47,  2.48s/it]

tensor(12.4522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4338, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4441, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4530, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [08:14<02:40,  1.18s/it]

tensor(12.4367, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4665, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4283, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4774, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [08:14<01:52,  1.19it/s]

tensor(12.4203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4850, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4887, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4888, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [08:14<00:58,  2.22it/s]

tensor(12.3959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4905, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4954, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4960, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [08:15<00:43,  2.93it/s]

tensor(12.3779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5036, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5106, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5162, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [08:15<00:26,  4.68it/s]

tensor(12.3592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5218, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5255, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3490, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5320, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [08:15<00:21,  5.63it/s]

tensor(12.3442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5370, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5472, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [08:16<00:15,  7.40it/s]

tensor(12.3299, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5507, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5543, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5559, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [08:16<00:14,  8.17it/s]

tensor(12.3186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5579, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3148, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5582, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5552, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [08:16<00:12,  9.31it/s]

tensor(12.3081, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5637, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5660, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3012, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5672, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [08:16<00:11,  9.69it/s]

tensor(12.2980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5719, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5716, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5727, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [08:17<00:10, 10.20it/s]

tensor(12.2893, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5711, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5743, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5756, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [08:17<00:10, 10.36it/s]

tensor(12.2813, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5776, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5777, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5802, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:17<00:09, 10.55it/s]

tensor(12.2736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5850, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5776, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([186, 210, 127,  93, 171, 178,  83, 129,  99, 114, 232, 198,  20,  99])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:14, 25.87it/s]
  1%|          | 10/1939 [00:00<00:38, 50.18it/s]
  1%|          | 16/1939 [00:00<00:37, 51.71it/s]
  1%|          | 22/1939 [00:00<00:46, 41.19it/s]
  1%|▏         | 28/1939 [00:00<00:44, 42.84it/s]
  2%|▏         | 34/1939 [00:00<00:40, 47.02it/s]
  2%|▏         | 39/1939 [00:00<00:41, 46.01it/s]
  2%|▏         | 46/1939 [00:00<00:37, 50.85it/s]
  3%|▎         | 53/1939 [00:01<00:36, 51.47it/s]
  3%|▎         | 59/1939 [00:01<00:46, 40.25it/s]
  3%|▎         | 65/1939 [00:01<00:43, 42.89it/s]
  4%|▎         | 70/1939 [00:01<00:44, 41.95it/s]
  4%|▍         | 75/1939 [00:01<00:43, 43.25it/s]
  4%|▍         | 81/1939 [00:01<00:39, 46.62it/s]
  4%|▍         | 86/1939 [00:01<00:39, 47.30it/s]
  5%|▍         | 92/1939 [00:02<00:37, 49.33it/s]
  5%|▌         | 98/1939 [00:02<00:37, 49.33it/s]
  5%|▌         | 104/1939 [00:02<00:35, 51.96it/s]
  6%|▌         | 110/1939 [00:02<00:35, 52.10it/s]
  6%|▌         | 116/1939 [00:02<00:41, 44.40it/s]
  6%|▌         | 121/1939 [00:02<00:44, 40.96it/s]
  6%|▋         | 126/1939 [00:02<00:42, 42.70it/s]
  7%|▋         | 132/1939 [00:02<00:38, 46.35it/s]
  7%|▋         | 138/1939 [00:03<00:37, 47.67it/s]
  7%|▋         | 143/1939 [00:03<00:38, 46.36it/s]
  8%|▊         | 149/1939 [00:03<00:36, 49.25it/s]
  8%|▊         | 155/1939 [00:03<00:38, 46.24it/s]
  8%|▊         | 160/1939 [00:03<00:50, 35.39it/s]
  8%|▊         | 164/1939 [00:03<00:48, 36.29it/s]
  9%|▉         | 170/1939 [00:03<00:42, 41.29it/s]
  9%|▉         | 175/1939 [00:03<00:42, 41.80it/s]
  9%|▉         | 180/1939 [00:04<00:44, 39.92it/s]
 10%|▉         | 186/1939 [00:04<00:40, 43.09it/s]
 10%|▉         | 192/1939 [00:04<00:37, 46.58it/s]
 10%|█         | 197/1939 [00:04<00:38, 45.19it/s]
 11%|█         | 204/1939 [00:04<00:35, 48.91it/s]
 11%|█         | 209/1939 [00:04<00:35, 49.06it/s]
 11%|█         | 215/1939 [00:04<00:34, 50.39it/s]
 11%|█▏        | 221/1939 [00:04<00:35, 48.28it/s]
 12%|█▏        | 226/1939 [00:05<00:45, 37.43it/s]
 12%|█▏        | 231/1939 [00:05<00:53, 32.22it/s]
 12%|█▏        | 237/1939 [00:05<00:45, 37.15it/s]
 12%|█▏        | 242/1939 [00:05<00:50, 33.41it/s]
 13%|█▎        | 246/1939 [00:05<00:49, 33.93it/s]
 13%|█▎        | 252/1939 [00:05<00:42, 39.47it/s]
 13%|█▎        | 258/1939 [00:05<00:38, 43.58it/s]
 14%|█▎        | 263/1939 [00:06<00:37, 45.11it/s]
 14%|█▍        | 269/1939 [00:06<00:34, 48.76it/s]
 14%|█▍        | 276/1939 [00:06<00:31, 52.68it/s]
 15%|█▍        | 282/1939 [00:06<00:30, 53.56it/s]
 15%|█▍        | 288/1939 [00:06<00:30, 54.60it/s]
 15%|█▌        | 294/1939 [00:06<00:32, 51.17it/s]
 15%|█▌        | 300/1939 [00:06<00:34, 47.38it/s]
 16%|█▌        | 305/1939 [00:06<00:36, 44.77it/s]
 16%|█▌        | 310/1939 [00:07<00:45, 36.05it/s]
 16%|█▌        | 314/1939 [00:07<00:46, 35.08it/s]
 16%|█▋        | 319/1939 [00:07<00:42, 38.33it/s]
 17%|█▋        | 324/1939 [00:07<00:44, 36.56it/s]
 17%|█▋        | 330/1939 [00:07<00:38, 42.06it/s]
 17%|█▋        | 336/1939 [00:07<00:36, 44.53it/s]
 18%|█▊        | 343/1939 [00:07<00:35, 45.55it/s]
 18%|█▊        | 348/1939 [00:08<00:41, 38.50it/s]
 18%|█▊        | 354/1939 [00:08<00:37, 41.73it/s]
 19%|█▊        | 359/1939 [00:08<00:43, 36.02it/s]
 19%|█▉        | 365/1939 [00:08<00:40, 38.73it/s]
 19%|█▉        | 370/1939 [00:08<00:44, 34.89it/s]
 19%|█▉        | 374/1939 [00:08<00:47, 32.61it/s]
 20%|█▉        | 379/1939 [00:08<00:42, 36.28it/s]
 20%|█▉        | 384/1939 [00:08<00:39, 39.00it/s]
 20%|██        | 389/1939 [00:09<00:41, 37.78it/s]
 20%|██        | 394/1939 [00:09<00:38, 39.62it/s]
 21%|██        | 400/1939 [00:09<00:34, 44.71it/s]
 21%|██        | 405/1939 [00:09<00:33, 45.20it/s]
 21%|██        | 410/1939 [00:09<00:33, 46.10it/s]
 21%|██▏       | 416/1939 [00:09<00:32, 46.99it/s]
 22%|██▏       | 422/1939 [00:09<00:31, 47.58it/s]
 22%|██▏       | 428/1939 [00:09<00:31, 48.35it/s]
 22%|██▏       | 435/1939 [00:10<00:28, 53.35it/s]
 23%|██▎       | 442/1939 [00:10<00:26, 56.35it/s]
 23%|██▎       | 448/1939 [00:10<00:28, 51.56it/s]
 23%|██▎       | 454/1939 [00:10<00:27, 53.38it/s]
 24%|██▎       | 460/1939 [00:10<00:27, 53.71it/s]
 24%|██▍       | 466/1939 [00:10<00:27, 52.95it/s]
 24%|██▍       | 472/1939 [00:10<00:27, 53.11it/s]
 25%|██▍       | 479/1939 [00:10<00:26, 54.47it/s]
 25%|██▌       | 485/1939 [00:10<00:26, 54.65it/s]
 25%|██▌       | 491/1939 [00:11<00:26, 54.90it/s]
 26%|██▌       | 497/1939 [00:11<00:32, 44.52it/s]
 26%|██▌       | 502/1939 [00:11<00:31, 45.39it/s]
 26%|██▌       | 508/1939 [00:11<00:29, 49.04it/s]
 27%|██▋       | 514/1939 [00:11<00:27, 51.65it/s]
 27%|██▋       | 520/1939 [00:11<00:31, 45.24it/s]
 27%|██▋       | 528/1939 [00:11<00:27, 52.07it/s]
 28%|██▊       | 535/1939 [00:11<00:25, 55.00it/s]
 28%|██▊       | 541/1939 [00:12<00:25, 54.75it/s]
 28%|██▊       | 547/1939 [00:12<00:25, 54.23it/s]
 29%|██▊       | 553/1939 [00:12<00:25, 53.46it/s]
 29%|██▉       | 559/1939 [00:12<00:28, 47.81it/s]
 29%|██▉       | 566/1939 [00:12<00:26, 51.67it/s]
 29%|██▉       | 572/1939 [00:12<00:28, 48.44it/s]
 30%|██▉       | 577/1939 [00:12<00:32, 42.08it/s]
 30%|███       | 582/1939 [00:12<00:31, 43.33it/s]
 67%|██████▋   | 200/300 [08:33<00:09, 10.55it/s]]
 31%|███       | 592/1939 [00:13<00:32, 41.26it/s]
 31%|███       | 597/1939 [00:13<00:43, 30.81it/s]
 31%|███       | 602/1939 [00:13<00:39, 34.08it/s]
 31%|███▏      | 606/1939 [00:13<00:39, 33.54it/s]
 31%|███▏      | 610/1939 [00:13<00:41, 32.08it/s]
 32%|███▏      | 614/1939 [00:13<00:39, 33.22it/s]
 32%|███▏      | 620/1939 [00:14<00:37, 35.29it/s]
 32%|███▏      | 626/1939 [00:14<00:32, 40.27it/s]
 33%|███▎      | 632/1939 [00:14<00:29, 44.61it/s]
 33%|███▎      | 638/1939 [00:14<00:27, 47.77it/s]
 33%|███▎      | 643/1939 [00:14<00:27, 47.32it/s]
 33%|███▎      | 649/1939 [00:14<00:26, 49.40it/s]
 34%|███▍      | 655/1939 [00:14<00:28, 45.15it/s]
 34%|███▍      | 661/1939 [00:14<00:27, 46.57it/s]
 34%|███▍      | 667/1939 [00:15<00:25, 49.37it/s]
 35%|███▍      | 673/1939 [00:15<00:30, 41.25it/s]
 35%|███▍      | 678/1939 [00:15<00:29, 43.06it/s]
 35%|███▌      | 684/1939 [00:15<00:27, 46.01it/s]
 36%|███▌      | 689/1939 [00:15<00:27, 46.08it/s]
 36%|███▌      | 695/1939 [00:15<00:25, 49.59it/s]
 36%|███▌      | 701/1939 [00:15<00:25, 48.12it/s]
 36%|███▋      | 706/1939 [00:15<00:26, 46.06it/s]
 37%|███▋      | 711/1939 [00:16<00:28, 42.43it/s]
 37%|███▋      | 716/1939 [00:16<00:27, 44.05it/s]
 37%|███▋      | 721/1939 [00:16<00:27, 44.28it/s]
 37%|███▋      | 726/1939 [00:16<00:26, 45.68it/s]
 38%|███▊      | 732/1939 [00:16<00:24, 48.86it/s]
 38%|███▊      | 738/1939 [00:16<00:23, 51.53it/s]
 38%|███▊      | 744/1939 [00:16<00:29, 39.91it/s]
 39%|███▊      | 749/1939 [00:16<00:29, 40.06it/s]
 39%|███▉      | 754/1939 [00:17<00:33, 35.52it/s]
 39%|███▉      | 758/1939 [00:17<00:32, 36.05it/s]
 39%|███▉      | 762/1939 [00:17<00:31, 36.80it/s]
 40%|███▉      | 767/1939 [00:17<00:29, 39.83it/s]
 40%|███▉      | 772/1939 [00:17<00:28, 41.21it/s]
 40%|████      | 777/1939 [00:17<00:27, 42.98it/s]
 40%|████      | 782/1939 [00:17<00:33, 34.94it/s]
 41%|████      | 788/1939 [00:17<00:28, 39.77it/s]
 41%|████      | 794/1939 [00:18<00:27, 41.70it/s]
 41%|████      | 799/1939 [00:18<00:29, 38.67it/s]
 42%|████▏     | 805/1939 [00:18<00:26, 42.21it/s]
 42%|████▏     | 811/1939 [00:18<00:24, 45.70it/s]
 42%|████▏     | 816/1939 [00:18<00:27, 40.31it/s]
 42%|████▏     | 822/1939 [00:18<00:26, 42.77it/s]
 43%|████▎     | 828/1939 [00:18<00:24, 46.25it/s]
 43%|████▎     | 834/1939 [00:18<00:22, 48.63it/s]
 43%|████▎     | 840/1939 [00:19<00:22, 49.90it/s]
 44%|████▎     | 846/1939 [00:19<00:21, 50.23it/s]
 44%|████▍     | 853/1939 [00:19<00:20, 52.36it/s]
 44%|████▍     | 859/1939 [00:19<00:20, 52.30it/s]
 45%|████▍     | 865/1939 [00:19<00:24, 44.21it/s]
 45%|████▍     | 870/1939 [00:19<00:25, 41.66it/s]
 45%|████▌     | 875/1939 [00:19<00:25, 41.19it/s]
 45%|████▌     | 882/1939 [00:19<00:22, 47.27it/s]
 46%|████▌     | 888/1939 [00:20<00:21, 49.66it/s]
 46%|████▌     | 894/1939 [00:20<00:26, 39.32it/s]
 46%|████▋     | 899/1939 [00:20<00:33, 31.18it/s]
 47%|████▋     | 903/1939 [00:20<00:33, 31.03it/s]
 47%|████▋     | 910/1939 [00:20<00:27, 37.30it/s]
 47%|████▋     | 915/1939 [00:20<00:26, 38.76it/s]
 47%|████▋     | 920/1939 [00:21<00:29, 34.46it/s]
 48%|████▊     | 925/1939 [00:21<00:26, 37.60it/s]
 48%|████▊     | 931/1939 [00:21<00:25, 39.03it/s]
 48%|████▊     | 936/1939 [00:21<00:24, 40.36it/s]
 49%|████▊     | 942/1939 [00:21<00:22, 43.79it/s]
 49%|████▉     | 948/1939 [00:21<00:21, 45.91it/s]
 49%|████▉     | 953/1939 [00:21<00:22, 44.55it/s]
 49%|████▉     | 958/1939 [00:21<00:22, 44.36it/s]
 50%|████▉     | 963/1939 [00:22<00:24, 39.30it/s]
 50%|████▉     | 968/1939 [00:22<00:23, 41.58it/s]
 50%|█████     | 974/1939 [00:22<00:21, 44.17it/s]
 51%|█████     | 980/1939 [00:22<00:20, 46.37it/s]
 51%|█████     | 985/1939 [00:22<00:22, 41.89it/s]
 51%|█████     | 991/1939 [00:22<00:21, 43.93it/s]
 51%|█████▏    | 997/1939 [00:22<00:21, 44.81it/s]
 52%|█████▏    | 1002/1939 [00:23<00:25, 37.07it/s]
 52%|█████▏    | 1006/1939 [00:23<00:27, 33.79it/s]
 52%|█████▏    | 1010/1939 [00:23<00:26, 35.12it/s]
 52%|█████▏    | 1015/1939 [00:23<00:25, 35.98it/s]
 53%|█████▎    | 1019/1939 [00:23<00:26, 35.16it/s]
 53%|█████▎    | 1025/1939 [00:23<00:22, 40.83it/s]
 53%|█████▎    | 1030/1939 [00:23<00:23, 39.35it/s]
 53%|█████▎    | 1035/1939 [00:23<00:21, 41.43it/s]
 54%|█████▎    | 1041/1939 [00:24<00:19, 45.33it/s]
 54%|█████▍    | 1048/1939 [00:24<00:17, 49.91it/s]
 54%|█████▍    | 1054/1939 [00:24<00:17, 49.31it/s]
 55%|█████▍    | 1059/1939 [00:24<00:18, 47.51it/s]
 55%|█████▍    | 1064/1939 [00:24<00:19, 44.38it/s]
 55%|█████▌    | 1070/1939 [00:24<00:18, 47.27it/s]
 55%|█████▌    | 1076/1939 [00:24<00:17, 48.77it/s]
 56%|█████▌    | 1081/1939 [00:24<00:19, 43.32it/s]
 56%|█████▌    | 1086/1939 [00:25<00:20, 41.74it/s]
 56%|█████▋    | 1092/1939 [00:25<00:18, 44.83it/s]
 57%|█████▋    | 1098/1939 [00:25<00:17, 47.66it/s]
 57%|█████▋    | 1105/1939 [00:25<00:16, 50.23it/s]
 57%|█████▋    | 1111/1939 [00:25<00:20, 40.81it/s]
 58%|█████▊    | 1116/1939 [00:25<00:20, 40.95it/s]
 58%|█████▊    | 1121/1939 [00:25<00:19, 42.48it/s]
 58%|█████▊    | 1126/1939 [00:25<00:20, 38.85it/s]
 58%|█████▊    | 1132/1939 [00:26<00:18, 43.02it/s]
 59%|█████▊    | 1138/1939 [00:26<00:17, 46.70it/s]
 59%|█████▉    | 1144/1939 [00:26<00:15, 49.70it/s]
 59%|█████▉    | 1150/1939 [00:26<00:16, 48.61it/s]
 60%|█████▉    | 1155/1939 [00:26<00:19, 40.22it/s]
 60%|█████▉    | 1160/1939 [00:26<00:19, 39.79it/s]
 60%|██████    | 1165/1939 [00:26<00:20, 37.54it/s]
 60%|██████    | 1169/1939 [00:26<00:22, 34.89it/s]
 61%|██████    | 1174/1939 [00:27<00:19, 38.35it/s]
 61%|██████    | 1179/1939 [00:27<00:24, 30.90it/s]
 61%|██████    | 1184/1939 [00:27<00:22, 34.28it/s]
 61%|██████▏   | 1188/1939 [00:27<00:22, 33.50it/s]
 62%|██████▏   | 1193/1939 [00:27<00:20, 35.94it/s]
 62%|██████▏   | 1198/1939 [00:27<00:18, 39.10it/s]
 62%|██████▏   | 1205/1939 [00:27<00:16, 43.87it/s]
 62%|██████▏   | 1210/1939 [00:28<00:19, 37.00it/s]
 63%|██████▎   | 1217/1939 [00:28<00:16, 43.98it/s]
 63%|██████▎   | 1223/1939 [00:28<00:15, 45.46it/s]
 63%|██████▎   | 1229/1939 [00:28<00:14, 47.85it/s]
 64%|██████▎   | 1234/1939 [00:28<00:18, 38.05it/s]
 64%|██████▍   | 1240/1939 [00:28<00:16, 42.01it/s]
 64%|██████▍   | 1245/1939 [00:28<00:15, 43.67it/s]
 65%|██████▍   | 1251/1939 [00:28<00:14, 46.12it/s]
 65%|██████▍   | 1256/1939 [00:29<00:14, 46.57it/s]
 65%|██████▌   | 1261/1939 [00:29<00:14, 45.99it/s]
 65%|██████▌   | 1266/1939 [00:29<00:14, 46.70it/s]
 66%|██████▌   | 1272/1939 [00:29<00:13, 48.35it/s]
 66%|██████▌   | 1278/1939 [00:29<00:13, 50.68it/s]
 66%|██████▋   | 1285/1939 [00:29<00:12, 52.60it/s]
 67%|██████▋   | 1291/1939 [00:29<00:13, 49.83it/s]
 67%|██████▋   | 1297/1939 [00:29<00:12, 50.17it/s]
 67%|██████▋   | 1303/1939 [00:30<00:12, 51.28it/s]
 68%|██████▊   | 1309/1939 [00:30<00:12, 50.87it/s]
 68%|██████▊   | 1315/1939 [00:30<00:12, 49.90it/s]
 68%|██████▊   | 1322/1939 [00:30<00:11, 52.82it/s]
 68%|██████▊   | 1328/1939 [00:30<00:12, 49.71it/s]
 69%|██████▉   | 1334/1939 [00:30<00:11, 50.62it/s]
 69%|██████▉   | 1340/1939 [00:30<00:13, 43.54it/s]
 69%|██████▉   | 1345/1939 [00:30<00:15, 37.28it/s]
 70%|██████▉   | 1349/1939 [00:31<00:17, 34.35it/s]
 70%|██████▉   | 1354/1939 [00:31<00:15, 36.72it/s]
 70%|███████   | 1359/1939 [00:31<00:15, 37.18it/s]
 70%|███████   | 1363/1939 [00:31<00:16, 35.58it/s]
 71%|███████   | 1369/1939 [00:31<00:13, 41.43it/s]
 71%|███████   | 1375/1939 [00:31<00:12, 44.55it/s]
 71%|███████   | 1381/1939 [00:31<00:12, 43.36it/s]
 71%|███████▏  | 1386/1939 [00:32<00:13, 39.56it/s]
 72%|███████▏  | 1392/1939 [00:32<00:12, 43.80it/s]
 72%|███████▏  | 1398/1939 [00:32<00:11, 46.54it/s]
 72%|███████▏  | 1404/1939 [00:32<00:11, 45.19it/s]
 73%|███████▎  | 1409/1939 [00:32<00:13, 38.96it/s]
 73%|███████▎  | 1415/1939 [00:32<00:12, 42.18it/s]
 73%|███████▎  | 1420/1939 [00:32<00:12, 40.67it/s]
 74%|███████▎  | 1427/1939 [00:32<00:11, 46.43it/s]
 74%|███████▍  | 1432/1939 [00:33<00:11, 45.74it/s]
 74%|███████▍  | 1439/1939 [00:33<00:10, 49.69it/s]
 75%|███████▍  | 1445/1939 [00:33<00:10, 48.81it/s]
 75%|███████▍  | 1450/1939 [00:33<00:10, 47.69it/s]
 75%|███████▌  | 1456/1939 [00:33<00:09, 50.11it/s]
 75%|███████▌  | 1462/1939 [00:33<00:10, 47.63it/s]
 76%|███████▌  | 1468/1939 [00:33<00:09, 49.40it/s]
 76%|███████▌  | 1474/1939 [00:33<00:09, 49.83it/s]
 76%|███████▋  | 1480/1939 [00:33<00:08, 51.49it/s]
 77%|███████▋  | 1486/1939 [00:34<00:09, 49.98it/s]
 77%|███████▋  | 1492/1939 [00:34<00:08, 50.97it/s]
 77%|███████▋  | 1498/1939 [00:34<00:08, 50.54it/s]
 78%|███████▊  | 1504/1939 [00:34<00:08, 51.19it/s]
 78%|███████▊  | 1510/1939 [00:34<00:08, 50.95it/s]
 78%|███████▊  | 1516/1939 [00:34<00:08, 48.68it/s]
 79%|███████▊  | 1523/1939 [00:34<00:07, 52.75it/s]
 79%|███████▉  | 1529/1939 [00:34<00:07, 52.28it/s]
 79%|███████▉  | 1535/1939 [00:35<00:07, 53.25it/s]
 80%|███████▉  | 1542/1939 [00:35<00:07, 56.60it/s]
 80%|███████▉  | 1548/1939 [00:35<00:08, 46.98it/s]
 80%|████████  | 1555/1939 [00:35<00:07, 49.98it/s]
 81%|████████  | 1561/1939 [00:35<00:07, 49.79it/s]
 81%|████████  | 1567/1939 [00:35<00:07, 49.26it/s]
 81%|████████  | 1574/1939 [00:35<00:06, 52.99it/s]
 81%|████████▏ | 1580/1939 [00:35<00:06, 54.75it/s]
 82%|████████▏ | 1586/1939 [00:36<00:06, 52.59it/s]
 82%|████████▏ | 1592/1939 [00:36<00:06, 52.76it/s]
 82%|████████▏ | 1598/1939 [00:36<00:08, 42.48it/s]
 83%|████████▎ | 1603/1939 [00:36<00:08, 40.60it/s]
 83%|████████▎ | 1608/1939 [00:36<00:08, 39.87it/s]
 83%|████████▎ | 1614/1939 [00:36<00:07, 42.42it/s]
 84%|████████▎ | 1620/1939 [00:36<00:07, 45.01it/s]
 84%|████████▍ | 1626/1939 [00:36<00:06, 47.15it/s]
 84%|████████▍ | 1631/1939 [00:37<00:07, 41.88it/s]
 84%|████████▍ | 1636/1939 [00:37<00:07, 43.22it/s]
 85%|████████▍ | 1642/1939 [00:37<00:06, 46.96it/s]
 85%|████████▍ | 1647/1939 [00:37<00:06, 44.64it/s]
 85%|████████▌ | 1652/1939 [00:37<00:07, 36.85it/s]
 86%|████████▌ | 1659/1939 [00:37<00:06, 42.84it/s]
 86%|████████▌ | 1664/1939 [00:37<00:06, 44.33it/s]
 86%|████████▌ | 1669/1939 [00:37<00:05, 45.07it/s]
 86%|████████▋ | 1676/1939 [00:38<00:05, 49.47it/s]
 87%|████████▋ | 1682/1939 [00:38<00:05, 51.39it/s]
 87%|████████▋ | 1688/1939 [00:38<00:05, 45.19it/s]
 87%|████████▋ | 1693/1939 [00:38<00:05, 43.29it/s]
 88%|████████▊ | 1698/1939 [00:38<00:05, 40.99it/s]
 88%|████████▊ | 1704/1939 [00:38<00:05, 43.60it/s]
 88%|████████▊ | 1709/1939 [00:38<00:05, 44.74it/s]
 88%|████████▊ | 1714/1939 [00:38<00:04, 45.65it/s]
 89%|████████▊ | 1719/1939 [00:39<00:04, 46.56it/s]
 89%|████████▉ | 1724/1939 [00:39<00:04, 45.37it/s]
 89%|████████▉ | 1730/1939 [00:39<00:04, 45.86it/s]
 89%|████████▉ | 1735/1939 [00:39<00:04, 43.16it/s]
 90%|████████▉ | 1741/1939 [00:39<00:04, 46.85it/s]
 90%|█████████ | 1747/1939 [00:39<00:03, 50.09it/s]
 90%|█████████ | 1754/1939 [00:39<00:03, 54.41it/s]
 91%|█████████ | 1760/1939 [00:39<00:03, 55.28it/s]
 91%|█████████ | 1767/1939 [00:39<00:02, 58.14it/s]
 91%|█████████▏| 1774/1939 [00:40<00:02, 59.79it/s]
 92%|█████████▏| 1781/1939 [00:40<00:02, 57.31it/s]
 92%|█████████▏| 1787/1939 [00:40<00:02, 54.40it/s]
 92%|█████████▏| 1793/1939 [00:40<00:02, 54.99it/s]
 93%|█████████▎| 1799/1939 [00:40<00:02, 53.85it/s]
 93%|█████████▎| 1806/1939 [00:40<00:02, 56.83it/s]
 94%|█████████▎| 1813/1939 [00:40<00:02, 59.20it/s]
 94%|█████████▍| 1819/1939 [00:40<00:02, 57.34it/s]
 94%|█████████▍| 1825/1939 [00:41<00:02, 52.55it/s]
 94%|█████████▍| 1831/1939 [00:41<00:02, 51.10it/s]
 95%|█████████▍| 1837/1939 [00:41<00:02, 49.94it/s]
 95%|█████████▌| 1843/1939 [00:41<00:01, 49.11it/s]
 95%|█████████▌| 1848/1939 [00:41<00:01, 47.73it/s]
 96%|█████████▌| 1854/1939 [00:41<00:01, 49.97it/s]
 96%|█████████▌| 1860/1939 [00:41<00:01, 51.63it/s]
 96%|█████████▋| 1868/1939 [00:41<00:01, 57.82it/s]
 97%|█████████▋| 1874/1939 [00:41<00:01, 56.24it/s]
 97%|█████████▋| 1880/1939 [00:42<00:01, 55.12it/s]
 97%|█████████▋| 1886/1939 [00:42<00:00, 53.78it/s]
 98%|█████████▊| 1892/1939 [00:42<00:00, 52.43it/s]
 98%|█████████▊| 1898/1939 [00:42<00:00, 53.60it/s]
 98%|█████████▊| 1904/1939 [00:42<00:00, 50.98it/s]
 99%|█████████▊| 1910/1939 [00:42<00:00, 51.71it/s]
 99%|█████████▉| 1916/1939 [00:42<00:00, 50.94it/s]
 99%|█████████▉| 1922/1939 [00:42<00:00, 45.18it/s]
 99%|█████████▉| 1928/1939 [00:43<00:00, 45.83it/s]
100%|█████████▉| 1933/1939 [00:43<00:00, 45.54it/s]
100%|██████████| 1939/1939 [00:43<00:00, 44.73it/s]
/kaggle/working/PRAGA/clustering_utils.py:173: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return log_Hastings_ratio_split(1.0, torch.tensor(N_k_1), torch.tensor(N_k_2), log_ll_k1, log_ll_k2, log_ll_k, split_prob=0.1)

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 299.72it/s]
 67%|██████▋   | 201/300 [09:04<13:40,  8.29s/it]

[[np.int64(0), False, 4], [np.int64(1), False, 10], [np.int64(2), False, 3], [np.int64(3), False, 13], [np.int64(4), False, 13], [np.int64(5), False, 10], [np.int64(6), False, 13], [np.int64(7), False, 9], [np.int64(8), False, 0], [np.int64(11), False, 10], [np.int64(12), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1035, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.2675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1371, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 202/300 [09:04<10:51,  6.65s/it]

tensor(12.2699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1798, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [09:04<08:23,  5.19s/it]

tensor(12.2739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2145, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2228, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:04<05:04,  3.20s/it]

tensor(12.2731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2424, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [09:04<03:14,  2.09s/it]

tensor(12.2657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2651, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2829, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3008, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:05<02:08,  1.42s/it]

tensor(12.2512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3243, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3392, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:05<01:27,  1.01it/s]

tensor(12.2549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3499, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:05<01:01,  1.42it/s]

tensor(12.2541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3632, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2510, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3718, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3861, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [09:05<00:43,  1.95it/s]

tensor(12.2433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4036, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4096, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [09:05<00:31,  2.61it/s]

tensor(12.2371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4160, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:06<00:23,  3.39it/s]

tensor(12.2343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4190, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4203, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4151, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [09:06<00:18,  4.27it/s]

tensor(12.2287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4207, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4292, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [09:06<00:14,  5.22it/s]

tensor(12.2251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4292, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:06<00:12,  6.16it/s]

tensor(12.2228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4292, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4323, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2192, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4247, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:06<00:10,  7.05it/s]

tensor(12.2176, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4232, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4264, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:06<00:09,  7.85it/s]

tensor(12.2141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4243, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [09:07<00:08,  8.47it/s]

tensor(12.2126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4279, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4284, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4285, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [09:07<00:07,  8.98it/s]

tensor(12.2084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4278, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4285, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:07<00:06,  9.44it/s]

tensor(12.2056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4295, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [09:07<00:06,  9.77it/s]

tensor(12.2042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4273, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2012, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4295, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:07<00:06,  9.99it/s]

tensor(12.1999, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4298, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1983, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4301, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [09:08<00:05, 10.20it/s]

tensor(12.1968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4107, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:08<00:05, 10.31it/s]

tensor(12.1955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4138, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4140, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4163, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:08<00:05, 10.37it/s]

tensor(12.1914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4177, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4196, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [09:08<00:05, 10.47it/s]

tensor(12.1888, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4217, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [09:08<00:04, 10.56it/s]

tensor(12.1877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4237, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4255, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([172, 179,  82, 280, 207, 195,  69,  66, 117, 109, 128,  86, 138, 111])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:45, 18.36it/s]
  0%|          | 4/1939 [00:00<01:50, 17.55it/s]
  0%|          | 7/1939 [00:00<01:27, 22.08it/s]
  1%|          | 11/1939 [00:00<01:08, 28.33it/s]
  1%|          | 17/1939 [00:00<00:50, 38.19it/s]
  1%|          | 24/1939 [00:00<00:40, 47.60it/s]
  1%|▏         | 29/1939 [00:00<00:45, 42.31it/s]
  2%|▏         | 35/1939 [00:00<00:40, 46.62it/s]
  2%|▏         | 40/1939 [00:01<00:40, 46.59it/s]
  2%|▏         | 45/1939 [00:01<01:40, 18.84it/s]
  3%|▎         | 49/1939 [00:01<01:43, 18.20it/s]
  3%|▎         | 52/1939 [00:02<01:43, 18.29it/s]
  3%|▎         | 55/1939 [00:02<02:04, 15.10it/s]
  3%|▎         | 58/1939 [00:02<02:30, 12.48it/s]
  3%|▎         | 60/1939 [00:02<02:25, 12.93it/s]
  3%|▎         | 63/1939 [00:02<02:07, 14.73it/s]
  3%|▎         | 66/1939 [00:03<02:02, 15.30it/s]
  4%|▎         | 69/1939 [00:03<01:47, 17.44it/s]
  4%|▍         | 73/1939 [00:03<01:47, 17.40it/s]
  4%|▍         | 75/1939 [00:03<01:49, 17.04it/s]
  4%|▍         | 78/1939 [00:03<01:54, 16.21it/s]
  4%|▍         | 80/1939 [00:04<02:23, 12.96it/s]
  4%|▍         | 82/1939 [00:04<02:52, 10.76it/s]
  4%|▍         | 85/1939 [00:04<02:14, 13.77it/s]
  4%|▍         | 87/1939 [00:04<02:41, 11.47it/s]
  5%|▍         | 91/1939 [00:04<01:55, 16.06it/s]
  5%|▌         | 99/1939 [00:04<01:06, 27.70it/s]
  5%|▌         | 103/1939 [00:05<01:34, 19.39it/s]
  6%|▌         | 107/1939 [00:05<01:24, 21.74it/s]
  6%|▌         | 110/1939 [00:05<01:20, 22.73it/s]
  6%|▌         | 117/1939 [00:05<00:56, 32.25it/s]
  6%|▋         | 122/1939 [00:06<01:48, 16.69it/s]
  7%|▋         | 128/1939 [00:06<01:38, 18.45it/s]
  7%|▋         | 131/1939 [00:06<01:37, 18.51it/s]
  7%|▋         | 134/1939 [00:07<01:59, 15.13it/s]
  7%|▋         | 137/1939 [00:07<01:53, 15.92it/s]
  7%|▋         | 140/1939 [00:07<01:48, 16.51it/s]
  7%|▋         | 142/1939 [00:07<01:47, 16.65it/s]
  7%|▋         | 145/1939 [00:07<01:48, 16.51it/s]
  8%|▊         | 148/1939 [00:07<01:38, 18.19it/s]
  8%|▊         | 150/1939 [00:07<01:37, 18.41it/s]
  8%|▊         | 153/1939 [00:08<01:28, 20.23it/s]
  8%|▊         | 156/1939 [00:08<01:25, 20.84it/s]
  8%|▊         | 159/1939 [00:08<01:36, 18.50it/s]
  8%|▊         | 161/1939 [00:08<02:26, 12.18it/s]
  8%|▊         | 163/1939 [00:08<02:21, 12.54it/s]
  9%|▊         | 165/1939 [00:09<02:28, 11.94it/s]
  9%|▊         | 169/1939 [00:09<01:47, 16.50it/s]
  9%|▉         | 171/1939 [00:09<02:11, 13.49it/s]
  9%|▉         | 173/1939 [00:09<02:04, 14.14it/s]
  9%|▉         | 175/1939 [00:09<01:56, 15.14it/s]
  9%|▉         | 180/1939 [00:09<01:17, 22.76it/s]
 10%|▉         | 186/1939 [00:09<00:56, 31.02it/s]
 10%|▉         | 191/1939 [00:09<00:49, 35.07it/s]
 10%|█         | 195/1939 [00:10<01:04, 26.84it/s]
 10%|█         | 199/1939 [00:10<01:12, 23.87it/s]
 10%|█         | 202/1939 [00:10<01:28, 19.66it/s]
 11%|█         | 205/1939 [00:11<02:16, 12.72it/s]
 11%|█         | 207/1939 [00:11<02:33, 11.30it/s]
 11%|█         | 210/1939 [00:11<02:05, 13.82it/s]
 11%|█         | 215/1939 [00:11<01:58, 14.59it/s]
 11%|█         | 217/1939 [00:11<01:54, 15.00it/s]
 83%|████████▎ | 249/300 [09:23<00:04, 10.56it/s]]
 12%|█▏        | 227/1939 [00:12<01:08, 24.91it/s]
 12%|█▏        | 231/1939 [00:12<01:13, 23.21it/s]
 12%|█▏        | 234/1939 [00:12<01:34, 18.10it/s]
 12%|█▏        | 237/1939 [00:12<01:55, 14.73it/s]
 12%|█▏        | 239/1939 [00:13<02:13, 12.74it/s]
 12%|█▏        | 241/1939 [00:13<02:28, 11.42it/s]
 13%|█▎        | 243/1939 [00:13<02:48, 10.08it/s]
 13%|█▎        | 245/1939 [00:13<02:43, 10.33it/s]
 13%|█▎        | 247/1939 [00:14<02:35, 10.88it/s]
 13%|█▎        | 249/1939 [00:14<02:18, 12.21it/s]
 13%|█▎        | 251/1939 [00:14<02:07, 13.29it/s]
 13%|█▎        | 256/1939 [00:14<01:21, 20.75it/s]
 13%|█▎        | 260/1939 [00:14<01:07, 24.76it/s]
 14%|█▎        | 266/1939 [00:14<00:50, 32.93it/s]
 14%|█▍        | 271/1939 [00:14<00:45, 36.48it/s]
 14%|█▍        | 277/1939 [00:14<00:39, 42.39it/s]
 15%|█▍        | 282/1939 [00:15<00:59, 28.08it/s]
 15%|█▍        | 286/1939 [00:15<01:02, 26.25it/s]
 15%|█▌        | 293/1939 [00:15<00:48, 34.05it/s]
 15%|█▌        | 299/1939 [00:15<00:42, 38.96it/s]
 16%|█▌        | 305/1939 [00:15<00:38, 42.88it/s]
 16%|█▌        | 311/1939 [00:15<00:35, 46.14it/s]
 16%|█▋        | 317/1939 [00:15<00:38, 42.22it/s]
 17%|█▋        | 323/1939 [00:15<00:35, 46.08it/s]
 17%|█▋        | 328/1939 [00:16<00:35, 45.71it/s]
 17%|█▋        | 333/1939 [00:16<00:40, 39.99it/s]
 17%|█▋        | 338/1939 [00:16<00:42, 37.47it/s]
 18%|█▊        | 342/1939 [00:16<01:05, 24.25it/s]
 18%|█▊        | 348/1939 [00:16<00:53, 29.90it/s]
 18%|█▊        | 352/1939 [00:17<01:24, 18.87it/s]
 18%|█▊        | 355/1939 [00:17<01:51, 14.19it/s]
 18%|█▊        | 358/1939 [00:17<01:39, 15.81it/s]
 19%|█▊        | 363/1939 [00:18<01:36, 16.29it/s]
 19%|█▉        | 366/1939 [00:18<01:29, 17.61it/s]
 19%|█▉        | 372/1939 [00:18<01:04, 24.20it/s]
 19%|█▉        | 376/1939 [00:18<01:17, 20.27it/s]
 20%|█▉        | 379/1939 [00:18<01:17, 20.25it/s]
 20%|█▉        | 382/1939 [00:18<01:14, 20.98it/s]
 20%|█▉        | 385/1939 [00:19<01:29, 17.30it/s]
 20%|██        | 388/1939 [00:19<01:44, 14.91it/s]
 20%|██        | 390/1939 [00:19<02:13, 11.61it/s]
 20%|██        | 392/1939 [00:20<02:29, 10.33it/s]
 20%|██        | 394/1939 [00:20<02:43,  9.45it/s]
 20%|██        | 396/1939 [00:20<03:01,  8.51it/s]
 21%|██        | 398/1939 [00:20<03:14,  7.91it/s]
 21%|██        | 400/1939 [00:21<02:46,  9.26it/s]
 21%|██        | 404/1939 [00:21<02:13, 11.52it/s]
 21%|██        | 406/1939 [00:21<02:32, 10.04it/s]
 21%|██        | 410/1939 [00:21<01:50, 13.88it/s]
 21%|██        | 412/1939 [00:22<02:21, 10.77it/s]
 21%|██▏       | 414/1939 [00:22<02:06, 12.02it/s]
 21%|██▏       | 416/1939 [00:22<02:40,  9.52it/s]
 22%|██▏       | 418/1939 [00:22<02:20, 10.79it/s]
 22%|██▏       | 420/1939 [00:22<02:23, 10.56it/s]
 22%|██▏       | 422/1939 [00:23<02:31, 10.01it/s]
 22%|██▏       | 424/1939 [00:23<02:22, 10.61it/s]
 22%|██▏       | 426/1939 [00:23<02:05, 12.09it/s]
 22%|██▏       | 428/1939 [00:23<01:51, 13.58it/s]
 22%|██▏       | 435/1939 [00:23<01:01, 24.33it/s]
 23%|██▎       | 439/1939 [00:23<00:53, 27.86it/s]
 23%|██▎       | 445/1939 [00:23<00:43, 34.21it/s]
 23%|██▎       | 451/1939 [00:23<00:37, 40.19it/s]
 24%|██▎       | 457/1939 [00:23<00:33, 43.65it/s]
 24%|██▍       | 462/1939 [00:24<00:36, 40.02it/s]
 24%|██▍       | 469/1939 [00:24<00:31, 46.21it/s]
 25%|██▍       | 476/1939 [00:24<00:28, 51.63it/s]
 25%|██▍       | 482/1939 [00:24<00:30, 47.99it/s]
 25%|██▌       | 488/1939 [00:24<00:28, 50.33it/s]
 25%|██▌       | 494/1939 [00:24<00:43, 32.99it/s]
 26%|██▌       | 500/1939 [00:25<00:37, 38.09it/s]
 26%|██▌       | 507/1939 [00:25<00:32, 43.63it/s]
 26%|██▋       | 513/1939 [00:25<00:35, 40.13it/s]
 27%|██▋       | 518/1939 [00:25<00:40, 34.97it/s]
 27%|██▋       | 525/1939 [00:25<00:34, 41.50it/s]
 27%|██▋       | 532/1939 [00:25<00:30, 45.98it/s]
 28%|██▊       | 538/1939 [00:26<00:46, 29.94it/s]
 28%|██▊       | 543/1939 [00:26<00:48, 28.76it/s]
 28%|██▊       | 548/1939 [00:26<00:44, 31.42it/s]
 28%|██▊       | 552/1939 [00:26<00:58, 23.65it/s]
 29%|██▊       | 556/1939 [00:26<00:54, 25.29it/s]
 29%|██▉       | 561/1939 [00:26<00:46, 29.67it/s]
 29%|██▉       | 566/1939 [00:27<00:43, 31.92it/s]
 29%|██▉       | 570/1939 [00:27<00:41, 32.66it/s]
 30%|██▉       | 574/1939 [00:27<01:14, 18.38it/s]
 30%|██▉       | 577/1939 [00:27<01:26, 15.74it/s]
 30%|██▉       | 580/1939 [00:28<01:36, 14.07it/s]
 30%|███       | 582/1939 [00:28<01:54, 11.82it/s]
 30%|███       | 584/1939 [00:28<02:04, 10.92it/s]
 30%|███       | 586/1939 [00:28<02:06, 10.71it/s]
 30%|███       | 588/1939 [00:29<01:53, 11.88it/s]
 31%|███       | 592/1939 [00:29<01:21, 16.60it/s]
 31%|███       | 598/1939 [00:29<00:54, 24.50it/s]
 31%|███       | 602/1939 [00:29<01:23, 16.08it/s]
 31%|███       | 605/1939 [00:29<01:23, 16.02it/s]
 31%|███▏      | 608/1939 [00:30<01:37, 13.59it/s]
 32%|███▏      | 611/1939 [00:30<01:32, 14.42it/s]
 32%|███▏      | 613/1939 [00:30<01:38, 13.43it/s]
 32%|███▏      | 615/1939 [00:30<02:12, 10.03it/s]
 32%|███▏      | 617/1939 [00:31<02:16,  9.69it/s]
 32%|███▏      | 619/1939 [00:31<02:06, 10.41it/s]
 32%|███▏      | 621/1939 [00:31<02:15,  9.76it/s]
 32%|███▏      | 623/1939 [00:31<01:59, 11.05it/s]
 32%|███▏      | 627/1939 [00:31<01:20, 16.22it/s]
 32%|███▏      | 630/1939 [00:32<01:23, 15.64it/s]
 33%|███▎      | 632/1939 [00:32<01:21, 16.05it/s]
 33%|███▎      | 636/1939 [00:32<01:17, 16.76it/s]
 33%|███▎      | 639/1939 [00:32<01:11, 18.29it/s]
 33%|███▎      | 643/1939 [00:32<01:12, 17.99it/s]
 33%|███▎      | 645/1939 [00:32<01:10, 18.37it/s]
 34%|███▎      | 651/1939 [00:32<00:48, 26.46it/s]
 34%|███▍      | 656/1939 [00:33<00:58, 21.84it/s]
 34%|███▍      | 659/1939 [00:33<01:13, 17.51it/s]
 34%|███▍      | 662/1939 [00:33<01:09, 18.49it/s]
 34%|███▍      | 665/1939 [00:33<01:24, 15.15it/s]
 34%|███▍      | 667/1939 [00:34<01:46, 11.97it/s]
 35%|███▍      | 669/1939 [00:34<01:39, 12.70it/s]
 35%|███▍      | 672/1939 [00:34<01:37, 13.06it/s]
 35%|███▍      | 675/1939 [00:34<01:21, 15.55it/s]
 35%|███▌      | 679/1939 [00:34<01:03, 19.98it/s]
 35%|███▌      | 682/1939 [00:35<01:24, 14.91it/s]
 35%|███▌      | 684/1939 [00:35<01:43, 12.09it/s]
 35%|███▌      | 687/1939 [00:35<01:43, 12.13it/s]
 36%|███▌      | 689/1939 [00:35<01:58, 10.58it/s]
 36%|███▌      | 691/1939 [00:36<01:46, 11.72it/s]
 36%|███▌      | 697/1939 [00:36<01:06, 18.76it/s]
 36%|███▌      | 702/1939 [00:36<00:52, 23.58it/s]
 36%|███▋      | 706/1939 [00:36<00:46, 26.80it/s]
 37%|███▋      | 711/1939 [00:36<00:39, 31.47it/s]
 37%|███▋      | 717/1939 [00:36<00:32, 37.80it/s]
 37%|███▋      | 722/1939 [00:36<00:29, 40.87it/s]
 38%|███▊      | 728/1939 [00:36<00:27, 43.64it/s]
 38%|███▊      | 733/1939 [00:37<00:54, 22.15it/s]
 38%|███▊      | 737/1939 [00:37<00:52, 22.94it/s]
 38%|███▊      | 741/1939 [00:37<01:02, 19.06it/s]
 38%|███▊      | 744/1939 [00:38<01:09, 17.10it/s]
 39%|███▊      | 747/1939 [00:38<01:10, 16.86it/s]
 39%|███▉      | 752/1939 [00:38<00:53, 22.00it/s]
 39%|███▉      | 755/1939 [00:38<01:06, 17.90it/s]
 39%|███▉      | 758/1939 [00:38<01:01, 19.34it/s]
 39%|███▉      | 761/1939 [00:38<01:12, 16.34it/s]
 39%|███▉      | 764/1939 [00:39<01:24, 13.99it/s]
 40%|███▉      | 767/1939 [00:39<01:29, 13.13it/s]
 40%|███▉      | 769/1939 [00:39<01:58,  9.85it/s]
 40%|███▉      | 772/1939 [00:40<01:35, 12.17it/s]
 40%|███▉      | 774/1939 [00:40<01:49, 10.68it/s]
 40%|████      | 776/1939 [00:40<01:57,  9.89it/s]
 40%|████      | 778/1939 [00:40<02:02,  9.51it/s]
 40%|████      | 780/1939 [00:41<02:21,  8.17it/s]
 40%|████      | 783/1939 [00:41<01:48, 10.63it/s]
 40%|████      | 785/1939 [00:41<01:55,  9.99it/s]
 41%|████      | 787/1939 [00:41<02:00,  9.57it/s]
 41%|████      | 789/1939 [00:41<02:06,  9.09it/s]
 41%|████      | 791/1939 [00:42<02:11,  8.70it/s]
 41%|████      | 793/1939 [00:42<01:52, 10.17it/s]
 41%|████      | 798/1939 [00:42<01:32, 12.28it/s]
 41%|████▏     | 800/1939 [00:42<01:27, 13.02it/s]
 41%|████▏     | 804/1939 [00:43<01:23, 13.52it/s]
 42%|████▏     | 806/1939 [00:43<01:48, 10.45it/s]
 42%|████▏     | 809/1939 [00:43<01:43, 10.93it/s]
 42%|████▏     | 812/1939 [00:43<01:35, 11.86it/s]
 42%|████▏     | 814/1939 [00:44<01:34, 11.85it/s]
 42%|████▏     | 816/1939 [00:44<01:39, 11.32it/s]
 42%|████▏     | 818/1939 [00:44<01:53,  9.86it/s]
 42%|████▏     | 820/1939 [00:44<02:00,  9.32it/s]
 42%|████▏     | 821/1939 [00:44<02:08,  8.73it/s]
 42%|████▏     | 822/1939 [00:45<02:32,  7.33it/s]
 42%|████▏     | 823/1939 [00:45<02:35,  7.19it/s]
 43%|████▎     | 825/1939 [00:45<02:09,  8.63it/s]
 43%|████▎     | 827/1939 [00:45<01:43, 10.77it/s]
 43%|████▎     | 829/1939 [00:45<01:32, 11.99it/s]
 43%|████▎     | 831/1939 [00:45<01:20, 13.74it/s]
 43%|████▎     | 835/1939 [00:45<00:55, 20.01it/s]
 43%|████▎     | 840/1939 [00:45<00:40, 26.85it/s]
 44%|████▎     | 846/1939 [00:46<00:31, 35.15it/s]
 44%|████▍     | 852/1939 [00:46<00:26, 40.38it/s]
 44%|████▍     | 857/1939 [00:46<00:39, 27.67it/s]
 44%|████▍     | 861/1939 [00:46<00:39, 27.54it/s]
 45%|████▍     | 868/1939 [00:46<00:30, 35.54it/s]
 45%|████▌     | 875/1939 [00:46<00:24, 43.22it/s]
 45%|████▌     | 882/1939 [00:46<00:22, 47.54it/s]
 46%|████▌     | 890/1939 [00:47<00:19, 52.65it/s]
 46%|████▌     | 896/1939 [00:47<00:21, 48.79it/s]
 47%|████▋     | 902/1939 [00:47<00:44, 23.47it/s]
 47%|████▋     | 906/1939 [00:48<00:45, 22.72it/s]
 47%|████▋     | 912/1939 [00:48<00:37, 27.04it/s]
 47%|████▋     | 916/1939 [00:48<00:35, 29.16it/s]
 48%|████▊     | 924/1939 [00:48<00:26, 38.10it/s]
 48%|████▊     | 929/1939 [00:48<00:37, 26.77it/s]
 48%|████▊     | 933/1939 [00:49<00:59, 16.88it/s]
 48%|████▊     | 939/1939 [00:49<00:45, 21.86it/s]
 49%|████▊     | 944/1939 [00:49<00:40, 24.38it/s]
 49%|████▉     | 949/1939 [00:49<00:36, 26.87it/s]
 49%|████▉     | 954/1939 [00:49<00:32, 30.33it/s]
 50%|████▉     | 960/1939 [00:49<00:28, 34.31it/s]
 50%|████▉     | 967/1939 [00:50<00:25, 38.33it/s]
 50%|█████     | 972/1939 [00:50<01:00, 16.09it/s]
 50%|█████     | 976/1939 [00:51<01:04, 14.92it/s]
 50%|█████     | 979/1939 [00:51<01:09, 13.86it/s]
 51%|█████     | 982/1939 [00:51<01:12, 13.16it/s]
 51%|█████     | 984/1939 [00:51<01:21, 11.70it/s]
 51%|█████     | 986/1939 [00:52<01:16, 12.44it/s]
 51%|█████     | 990/1939 [00:52<01:15, 12.54it/s]
 51%|█████     | 992/1939 [00:52<01:10, 13.45it/s]
 51%|█████▏    | 997/1939 [00:52<01:02, 15.02it/s]
 52%|█████▏    | 999/1939 [00:52<01:07, 14.02it/s]
 52%|█████▏    | 1001/1939 [00:53<01:05, 14.39it/s]
 52%|█████▏    | 1003/1939 [00:53<01:09, 13.40it/s]
 52%|█████▏    | 1005/1939 [00:53<01:11, 13.10it/s]
 52%|█████▏    | 1007/1939 [00:53<01:11, 12.98it/s]
 52%|█████▏    | 1009/1939 [00:53<01:12, 12.89it/s]
 52%|█████▏    | 1011/1939 [00:53<01:13, 12.55it/s]
 52%|█████▏    | 1013/1939 [00:54<01:32,  9.98it/s]
 52%|█████▏    | 1015/1939 [00:54<01:29, 10.32it/s]
 52%|█████▏    | 1017/1939 [00:54<01:20, 11.41it/s]
 53%|█████▎    | 1019/1939 [00:54<01:26, 10.59it/s]
 53%|█████▎    | 1021/1939 [00:54<01:16, 11.95it/s]
 53%|█████▎    | 1023/1939 [00:55<01:30, 10.10it/s]
 53%|█████▎    | 1027/1939 [00:55<00:59, 15.32it/s]
 53%|█████▎    | 1033/1939 [00:55<00:37, 23.91it/s]
 54%|█████▎    | 1040/1939 [00:55<00:26, 33.58it/s]
 54%|█████▍    | 1045/1939 [00:55<00:32, 27.45it/s]
 54%|█████▍    | 1049/1939 [00:55<00:32, 27.24it/s]
 54%|█████▍    | 1053/1939 [00:56<00:37, 23.50it/s]
 54%|█████▍    | 1056/1939 [00:56<00:45, 19.23it/s]
 55%|█████▍    | 1059/1939 [00:56<00:54, 16.03it/s]
 55%|█████▍    | 1061/1939 [00:56<01:05, 13.35it/s]
 55%|█████▍    | 1065/1939 [00:57<00:50, 17.36it/s]
 55%|█████▌    | 1068/1939 [00:57<00:53, 16.21it/s]
 55%|█████▌    | 1071/1939 [00:57<00:47, 18.33it/s]
 55%|█████▌    | 1074/1939 [00:57<01:00, 14.22it/s]
 56%|█████▌    | 1080/1939 [00:57<00:50, 16.86it/s]
 56%|█████▌    | 1082/1939 [00:58<00:50, 16.96it/s]
 56%|█████▌    | 1088/1939 [00:58<00:45, 18.60it/s]
 56%|█████▌    | 1090/1939 [00:58<00:45, 18.71it/s]
 56%|█████▋    | 1092/1939 [00:58<00:55, 15.32it/s]
 56%|█████▋    | 1094/1939 [00:59<01:14, 11.31it/s]
 57%|█████▋    | 1096/1939 [00:59<01:07, 12.55it/s]
 57%|█████▋    | 1098/1939 [00:59<01:13, 11.44it/s]
 57%|█████▋    | 1101/1939 [00:59<00:58, 14.23it/s]
 57%|█████▋    | 1103/1939 [00:59<01:04, 12.88it/s]
 57%|█████▋    | 1105/1939 [00:59<01:23,  9.94it/s]
 57%|█████▋    | 1108/1939 [01:00<01:10, 11.83it/s]
 57%|█████▋    | 1110/1939 [01:00<01:07, 12.22it/s]
 58%|█████▊    | 1116/1939 [01:00<00:54, 15.05it/s]
 58%|█████▊    | 1119/1939 [01:00<00:49, 16.58it/s]
 58%|█████▊    | 1121/1939 [01:00<00:57, 14.16it/s]
 58%|█████▊    | 1123/1939 [01:01<00:53, 15.14it/s]
 58%|█████▊    | 1129/1939 [01:01<00:47, 17.17it/s]
 58%|█████▊    | 1133/1939 [01:01<00:39, 20.29it/s]
 59%|█████▊    | 1137/1939 [01:01<00:40, 19.89it/s]
 59%|█████▉    | 1140/1939 [01:01<00:38, 20.55it/s]
 59%|█████▉    | 1143/1939 [01:02<00:47, 16.59it/s]
 59%|█████▉    | 1145/1939 [01:02<01:14, 10.71it/s]
 59%|█████▉    | 1147/1939 [01:02<01:08, 11.49it/s]
 59%|█████▉    | 1149/1939 [01:02<01:17, 10.19it/s]
 59%|█████▉    | 1151/1939 [01:03<01:39,  7.89it/s]
 59%|█████▉    | 1153/1939 [01:03<01:38,  7.97it/s]
 60%|█████▉    | 1156/1939 [01:03<01:15, 10.39it/s]
 60%|█████▉    | 1162/1939 [01:03<00:43, 17.91it/s]
 60%|██████    | 1165/1939 [01:04<00:42, 18.02it/s]
 60%|██████    | 1168/1939 [01:04<00:42, 18.33it/s]
 60%|██████    | 1173/1939 [01:04<00:32, 23.50it/s]
 61%|██████    | 1178/1939 [01:04<00:31, 24.06it/s]
 61%|██████    | 1181/1939 [01:04<00:44, 16.97it/s]
 61%|██████    | 1184/1939 [01:05<00:57, 13.06it/s]
 61%|██████    | 1186/1939 [01:05<01:11, 10.59it/s]
 61%|██████▏   | 1188/1939 [01:05<01:04, 11.56it/s]
 61%|██████▏   | 1190/1939 [01:05<01:07, 11.06it/s]
 61%|██████▏   | 1192/1939 [01:06<01:14,  9.98it/s]
 62%|██████▏   | 1194/1939 [01:06<01:14,  9.94it/s]
 62%|██████▏   | 1196/1939 [01:06<01:19,  9.37it/s]
 62%|██████▏   | 1198/1939 [01:06<01:26,  8.61it/s]
 62%|██████▏   | 1200/1939 [01:07<01:15,  9.77it/s]
 62%|██████▏   | 1203/1939 [01:07<00:56, 13.04it/s]
 62%|██████▏   | 1210/1939 [01:07<00:30, 23.52it/s]
 63%|██████▎   | 1217/1939 [01:07<00:28, 25.16it/s]
 63%|██████▎   | 1220/1939 [01:07<00:28, 25.40it/s]
 63%|██████▎   | 1226/1939 [01:07<00:28, 25.29it/s]
 63%|██████▎   | 1229/1939 [01:07<00:29, 23.78it/s]
 64%|██████▎   | 1232/1939 [01:08<00:39, 17.69it/s]
 64%|██████▎   | 1235/1939 [01:08<00:37, 18.66it/s]
 64%|██████▍   | 1239/1939 [01:08<00:39, 17.56it/s]
 64%|██████▍   | 1242/1939 [01:08<00:37, 18.78it/s]
 64%|██████▍   | 1247/1939 [01:08<00:28, 24.54it/s]
 65%|██████▍   | 1251/1939 [01:09<00:34, 19.97it/s]
 65%|██████▍   | 1254/1939 [01:09<00:40, 17.02it/s]
 65%|██████▍   | 1257/1939 [01:09<00:35, 19.17it/s]
 65%|██████▌   | 1263/1939 [01:09<00:25, 26.79it/s]
 66%|██████▌   | 1271/1939 [01:09<00:18, 36.24it/s]
 66%|██████▌   | 1276/1939 [01:09<00:16, 39.09it/s]
 66%|██████▌   | 1284/1939 [01:10<00:13, 48.01it/s]
 67%|██████▋   | 1290/1939 [01:10<00:13, 48.50it/s]
 67%|██████▋   | 1296/1939 [01:10<00:12, 49.91it/s]
 67%|██████▋   | 1302/1939 [01:10<00:13, 47.44it/s]
 67%|██████▋   | 1307/1939 [01:10<00:15, 39.86it/s]
 68%|██████▊   | 1312/1939 [01:11<00:31, 20.01it/s]
 68%|██████▊   | 1316/1939 [01:11<00:34, 18.07it/s]
 68%|██████▊   | 1322/1939 [01:11<00:26, 23.17it/s]
 68%|██████▊   | 1326/1939 [01:11<00:23, 25.63it/s]
 69%|██████▊   | 1330/1939 [01:11<00:23, 25.46it/s]
 69%|██████▉   | 1334/1939 [01:11<00:22, 27.09it/s]
 69%|██████▉   | 1340/1939 [01:12<00:24, 24.63it/s]
 69%|██████▉   | 1343/1939 [01:12<00:30, 19.25it/s]
 69%|██████▉   | 1346/1939 [01:12<00:36, 16.35it/s]
 70%|██████▉   | 1348/1939 [01:12<00:35, 16.66it/s]
 70%|██████▉   | 1350/1939 [01:13<00:41, 14.24it/s]
 70%|██████▉   | 1352/1939 [01:13<00:39, 14.91it/s]
 70%|██████▉   | 1354/1939 [01:13<00:45, 12.81it/s]
 70%|███████   | 1358/1939 [01:13<00:33, 17.36it/s]
 70%|███████   | 1361/1939 [01:13<00:35, 16.16it/s]
 70%|███████   | 1363/1939 [01:13<00:34, 16.89it/s]
 71%|███████   | 1368/1939 [01:13<00:24, 23.38it/s]
 71%|███████   | 1374/1939 [01:14<00:18, 29.87it/s]
 71%|███████   | 1378/1939 [01:14<00:23, 24.16it/s]
 71%|███████   | 1381/1939 [01:14<00:34, 16.23it/s]
 71%|███████▏  | 1384/1939 [01:15<00:43, 12.62it/s]
 71%|███████▏  | 1386/1939 [01:15<00:52, 10.62it/s]
 72%|███████▏  | 1389/1939 [01:15<00:49, 11.16it/s]
 72%|███████▏  | 1391/1939 [01:15<00:52, 10.52it/s]
 72%|███████▏  | 1393/1939 [01:16<00:49, 11.05it/s]
 72%|███████▏  | 1396/1939 [01:16<00:38, 13.97it/s]
 72%|███████▏  | 1399/1939 [01:16<00:40, 13.50it/s]
 72%|███████▏  | 1401/1939 [01:16<00:38, 13.82it/s]
 72%|███████▏  | 1403/1939 [01:16<00:43, 12.27it/s]
 73%|███████▎  | 1406/1939 [01:16<00:36, 14.65it/s]
 73%|███████▎  | 1408/1939 [01:17<00:40, 13.03it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 287.64it/s]
 34%|███▎      | 101/300 [02:44<1:32:17, 27.83s/it]

[[np.int64(0), False, 7], [np.int64(1), False, 8], [np.int64(2), False, 10], [np.int64(3), False, 2], [np.int64(4), False, 1], [np.int64(5), False, 1], [np.int64(6), False, 2], [np.int64(7), False, 8], [np.int64(9), False, 2], [np.int64(11), False, 8], [np.int64(12), False, 8], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.7279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9984, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.7175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0811, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [02:44<1:13:25, 22.25s/it]

tensor(12.7169, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1901, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [02:45<46:15, 14.16s/it]

tensor(12.7302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3071, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4675, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [02:45<30:11,  9.34s/it]

tensor(12.7916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5238, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [02:45<20:09,  6.30s/it]

tensor(12.7959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5953, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6349, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [02:45<13:40,  4.32s/it]

tensor(12.7642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6688, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6965, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [02:45<09:22,  2.99s/it]

tensor(12.7264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7210, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [02:46<06:29,  2.10s/it]

tensor(12.7049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7485, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7778, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8063, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [02:46<04:32,  1.48s/it]

tensor(12.6500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8424, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8745, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [02:46<03:12,  1.06s/it]

tensor(12.6199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8944, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [02:46<02:18,  1.30it/s]

tensor(12.6064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9377, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5824, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9592, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [02:46<01:40,  1.77it/s]

tensor(12.5723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9814, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9977, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [02:47<01:14,  2.36it/s]

tensor(12.5550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0216, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [02:47<00:56,  3.09it/s]

tensor(12.5465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0348, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5373, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0620, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0866, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [02:47<00:43,  3.93it/s]

tensor(12.5176, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1091, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1343, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [02:47<00:35,  4.84it/s]

tensor(12.4967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1629, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [02:47<00:29,  5.79it/s]

tensor(12.4866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1776, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4663, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2182, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [02:47<00:24,  6.72it/s]

tensor(12.4557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2385, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4453, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2538, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [02:48<00:21,  7.57it/s]

tensor(12.4350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2718, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [02:48<00:19,  8.27it/s]

tensor(12.4253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2881, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3040, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3258, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [02:48<00:18,  8.82it/s]

tensor(12.3986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3389, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3563, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [02:48<00:17,  9.29it/s]

tensor(12.3821, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3751, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [02:48<00:16,  9.65it/s]

tensor(12.3742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3814, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4060, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [02:49<00:15,  9.94it/s]

tensor(12.3521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4158, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3453, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4318, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [02:49<00:14, 10.17it/s]

tensor(12.3388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4457, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [02:49<00:14, 10.30it/s]

tensor(12.3324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4495, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([140, 322, 158, 154, 158,  87, 163,  19,  83, 117, 105,  34, 176, 223])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:28, 21.75it/s]
  0%|          | 6/1939 [00:00<01:32, 20.87it/s]
  1%|          | 13/1939 [00:00<00:50, 37.87it/s]
  1%|          | 19/1939 [00:00<00:43, 44.33it/s]
  1%|▏         | 25/1939 [00:00<00:39, 48.41it/s]
  2%|▏         | 31/1939 [00:00<00:37, 50.90it/s]
  2%|▏         | 37/1939 [00:00<00:36, 52.57it/s]
  2%|▏         | 43/1939 [00:01<00:55, 34.34it/s]
  2%|▏         | 48/1939 [00:01<00:51, 36.85it/s]
  3%|▎         | 53/1939 [00:01<01:02, 30.10it/s]
  3%|▎         | 57/1939 [00:01<01:02, 30.12it/s]
  3%|▎         | 61/1939 [00:01<01:26, 21.79it/s]
  3%|▎         | 66/1939 [00:02<01:34, 19.79it/s]
  4%|▎         | 69/1939 [00:02<01:29, 20.84it/s]
  4%|▍         | 73/1939 [00:02<01:43, 18.05it/s]
  4%|▍         | 76/1939 [00:02<01:33, 19.89it/s]
  4%|▍         | 79/1939 [00:03<01:52, 16.56it/s]
  4%|▍         | 82/1939 [00:03<02:21, 13.10it/s]
  4%|▍         | 86/1939 [00:03<01:53, 16.39it/s]
  5%|▍         | 89/1939 [00:03<02:01, 15.27it/s]
  5%|▍         | 94/1939 [00:04<01:55, 15.99it/s]
  5%|▍         | 96/1939 [00:04<02:02, 15.10it/s]
  5%|▌         | 99/1939 [00:04<01:47, 17.11it/s]
  5%|▌         | 104/1939 [00:04<01:19, 23.17it/s]
  6%|▌         | 110/1939 [00:04<01:00, 30.17it/s]
  6%|▌         | 115/1939 [00:04<00:53, 34.13it/s]
  6%|▌         | 119/1939 [00:04<01:23, 21.88it/s]
  6%|▋         | 123/1939 [00:05<01:29, 20.22it/s]
  6%|▋         | 126/1939 [00:05<01:32, 19.55it/s]
  7%|▋         | 132/1939 [00:05<01:15, 23.90it/s]
  7%|▋         | 135/1939 [00:05<01:21, 22.07it/s]
  7%|▋         | 138/1939 [00:06<01:50, 16.24it/s]
  7%|▋         | 140/1939 [00:06<01:47, 16.69it/s]
  7%|▋         | 142/1939 [00:06<01:51, 16.10it/s]
  7%|▋         | 145/1939 [00:06<02:08, 13.93it/s]
  8%|▊         | 149/1939 [00:06<01:41, 17.62it/s]
  8%|▊         | 153/1939 [00:06<01:38, 18.11it/s]
  8%|▊         | 156/1939 [00:07<01:32, 19.31it/s]
  8%|▊         | 159/1939 [00:07<01:48, 16.45it/s]
  8%|▊         | 161/1939 [00:07<02:39, 11.12it/s]
  8%|▊         | 163/1939 [00:08<03:23,  8.74it/s]
  9%|▊         | 165/1939 [00:08<03:24,  8.66it/s]
  9%|▊         | 167/1939 [00:08<02:56, 10.05it/s]
  9%|▉         | 173/1939 [00:08<01:39, 17.73it/s]
  9%|▉         | 180/1939 [00:08<01:05, 26.95it/s]
 10%|▉         | 186/1939 [00:08<00:52, 33.24it/s]
 10%|▉         | 193/1939 [00:08<00:44, 39.59it/s]
 10%|█         | 198/1939 [00:08<00:41, 41.64it/s]
 10%|█         | 203/1939 [00:09<01:17, 22.38it/s]
 11%|█         | 207/1939 [00:10<01:55, 15.05it/s]
 11%|█         | 210/1939 [00:10<01:49, 15.77it/s]
 11%|█         | 213/1939 [00:10<01:57, 14.70it/s]
 11%|█         | 216/1939 [00:10<02:11, 13.07it/s]
 11%|█         | 218/1939 [00:10<02:05, 13.72it/s]
 11%|█▏        | 220/1939 [00:10<02:01, 14.17it/s]
 12%|█▏        | 224/1939 [00:11<01:33, 18.32it/s]
 12%|█▏        | 228/1939 [00:11<01:39, 17.17it/s]
 50%|█████     | 150/300 [03:04<00:14, 10.30it/s]]
 12%|█▏        | 233/1939 [00:11<02:22, 12.00it/s]
 12%|█▏        | 235/1939 [00:12<02:14, 12.65it/s]
 12%|█▏        | 237/1939 [00:12<02:18, 12.26it/s]
 12%|█▏        | 239/1939 [00:12<02:34, 11.00it/s]
 12%|█▏        | 241/1939 [00:12<03:30,  8.05it/s]
 12%|█▏        | 242/1939 [00:13<03:49,  7.41it/s]
 13%|█▎        | 243/1939 [00:13<04:21,  6.48it/s]
 13%|█▎        | 245/1939 [00:13<04:00,  7.05it/s]
 13%|█▎        | 246/1939 [00:13<04:19,  6.53it/s]
 13%|█▎        | 248/1939 [00:14<04:17,  6.57it/s]
 13%|█▎        | 250/1939 [00:14<03:34,  7.87it/s]
 13%|█▎        | 256/1939 [00:14<01:46, 15.75it/s]
 13%|█▎        | 259/1939 [00:14<01:51, 15.08it/s]
 13%|█▎        | 261/1939 [00:14<01:48, 15.43it/s]
 14%|█▎        | 263/1939 [00:14<02:08, 13.01it/s]
 14%|█▎        | 265/1939 [00:15<02:01, 13.78it/s]
 14%|█▍        | 268/1939 [00:15<01:38, 16.93it/s]
 14%|█▍        | 275/1939 [00:15<01:00, 27.53it/s]
 14%|█▍        | 281/1939 [00:15<00:58, 28.11it/s]
 15%|█▍        | 285/1939 [00:15<00:58, 28.50it/s]
 15%|█▌        | 291/1939 [00:15<00:47, 34.73it/s]
 15%|█▌        | 296/1939 [00:15<00:42, 38.30it/s]
 16%|█▌        | 301/1939 [00:15<00:41, 39.66it/s]
 16%|█▌        | 306/1939 [00:16<00:44, 36.41it/s]
 16%|█▌        | 310/1939 [00:16<00:44, 36.86it/s]
 16%|█▌        | 314/1939 [00:16<00:50, 31.97it/s]
 16%|█▋        | 319/1939 [00:16<00:45, 35.30it/s]
 17%|█▋        | 323/1939 [00:16<00:48, 33.08it/s]
 17%|█▋        | 328/1939 [00:16<00:43, 36.86it/s]
 17%|█▋        | 333/1939 [00:16<00:41, 38.84it/s]
 18%|█▊        | 340/1939 [00:16<00:35, 45.32it/s]
 18%|█▊        | 346/1939 [00:17<00:33, 48.23it/s]
 18%|█▊        | 351/1939 [00:17<00:47, 33.56it/s]
 18%|█▊        | 356/1939 [00:17<01:23, 18.86it/s]
 19%|█▊        | 363/1939 [00:18<01:14, 21.08it/s]
 19%|█▉        | 366/1939 [00:18<01:12, 21.70it/s]
 19%|█▉        | 369/1939 [00:18<01:14, 21.11it/s]
 19%|█▉        | 375/1939 [00:18<00:56, 27.78it/s]
 20%|█▉        | 379/1939 [00:18<01:16, 20.46it/s]
 20%|█▉        | 382/1939 [00:19<01:30, 17.15it/s]
 20%|█▉        | 385/1939 [00:19<01:47, 14.42it/s]
 20%|█▉        | 387/1939 [00:19<02:04, 12.45it/s]
 20%|██        | 389/1939 [00:19<02:20, 11.02it/s]
 20%|██        | 391/1939 [00:20<02:39,  9.73it/s]
 20%|██        | 394/1939 [00:20<02:19, 11.11it/s]
 20%|██        | 396/1939 [00:20<02:23, 10.76it/s]
 21%|██        | 398/1939 [00:21<03:12,  8.01it/s]
 21%|██        | 400/1939 [00:21<02:42,  9.47it/s]
 21%|██        | 404/1939 [00:21<02:15, 11.32it/s]
 21%|██        | 406/1939 [00:21<02:33,  9.99it/s]
 21%|██        | 409/1939 [00:21<02:02, 12.53it/s]
 21%|██▏       | 415/1939 [00:22<01:37, 15.65it/s]
 22%|██▏       | 417/1939 [00:22<01:53, 13.37it/s]
 22%|██▏       | 419/1939 [00:22<02:18, 10.97it/s]
 22%|██▏       | 422/1939 [00:22<02:23, 10.59it/s]
 22%|██▏       | 424/1939 [00:23<02:11, 11.54it/s]
 22%|██▏       | 426/1939 [00:23<02:21, 10.71it/s]
 22%|██▏       | 429/1939 [00:23<01:55, 13.13it/s]
 22%|██▏       | 435/1939 [00:23<01:11, 21.01it/s]
 23%|██▎       | 442/1939 [00:23<00:50, 29.85it/s]
 23%|██▎       | 450/1939 [00:23<00:37, 39.56it/s]
 23%|██▎       | 455/1939 [00:23<00:41, 35.85it/s]
 24%|██▍       | 461/1939 [00:24<00:36, 40.80it/s]
 24%|██▍       | 466/1939 [00:24<00:35, 41.60it/s]
 24%|██▍       | 472/1939 [00:24<00:33, 44.29it/s]
 25%|██▍       | 478/1939 [00:24<00:34, 42.96it/s]
 25%|██▍       | 484/1939 [00:24<00:31, 45.89it/s]
 25%|██▌       | 489/1939 [00:24<00:43, 33.02it/s]
 25%|██▌       | 493/1939 [00:25<00:49, 29.35it/s]
 26%|██▌       | 497/1939 [00:25<00:48, 29.68it/s]
 26%|██▌       | 503/1939 [00:25<00:40, 35.80it/s]
 26%|██▌       | 508/1939 [00:25<00:40, 35.73it/s]
 27%|██▋       | 515/1939 [00:25<00:33, 43.06it/s]
 27%|██▋       | 520/1939 [00:25<00:32, 44.11it/s]
 27%|██▋       | 525/1939 [00:25<00:31, 45.47it/s]
 27%|██▋       | 531/1939 [00:25<00:29, 48.49it/s]
 28%|██▊       | 537/1939 [00:26<00:42, 33.29it/s]
 28%|██▊       | 542/1939 [00:26<00:43, 32.01it/s]
 28%|██▊       | 546/1939 [00:26<00:53, 26.04it/s]
 28%|██▊       | 550/1939 [00:26<00:57, 24.34it/s]
 29%|██▊       | 553/1939 [00:26<01:10, 19.66it/s]
 29%|██▉       | 559/1939 [00:27<00:53, 25.75it/s]
 29%|██▉       | 565/1939 [00:27<00:43, 31.82it/s]
 29%|██▉       | 571/1939 [00:27<00:51, 26.75it/s]
 30%|██▉       | 575/1939 [00:27<01:05, 20.94it/s]
 30%|██▉       | 578/1939 [00:27<01:07, 20.04it/s]
 30%|██▉       | 581/1939 [00:28<01:24, 16.02it/s]
 30%|███       | 583/1939 [00:28<01:33, 14.52it/s]
 30%|███       | 585/1939 [00:28<01:48, 12.50it/s]
 30%|███       | 587/1939 [00:29<02:11, 10.32it/s]
 31%|███       | 592/1939 [00:29<01:31, 14.80it/s]
 31%|███       | 595/1939 [00:29<01:19, 16.85it/s]
 31%|███       | 598/1939 [00:29<01:32, 14.42it/s]
 31%|███       | 600/1939 [00:29<02:01, 11.05it/s]
 31%|███       | 602/1939 [00:30<02:17,  9.69it/s]
 31%|███▏      | 607/1939 [00:30<01:47, 12.41it/s]
 31%|███▏      | 609/1939 [00:30<01:44, 12.68it/s]
 32%|███▏      | 611/1939 [00:30<01:39, 13.38it/s]
 32%|███▏      | 613/1939 [00:30<01:48, 12.26it/s]
 32%|███▏      | 615/1939 [00:31<01:41, 13.08it/s]
 32%|███▏      | 617/1939 [00:31<02:02, 10.78it/s]
 32%|███▏      | 619/1939 [00:31<02:13,  9.86it/s]
 32%|███▏      | 621/1939 [00:31<02:34,  8.54it/s]
 32%|███▏      | 622/1939 [00:32<02:39,  8.28it/s]
 32%|███▏      | 624/1939 [00:32<02:15,  9.74it/s]
 32%|███▏      | 626/1939 [00:32<01:53, 11.53it/s]
 32%|███▏      | 629/1939 [00:32<01:45, 12.44it/s]
 33%|███▎      | 631/1939 [00:32<02:06, 10.33it/s]
 33%|███▎      | 635/1939 [00:32<01:25, 15.31it/s]
 33%|███▎      | 641/1939 [00:33<00:55, 23.57it/s]
 33%|███▎      | 645/1939 [00:33<01:04, 19.97it/s]
 33%|███▎      | 649/1939 [00:33<01:14, 17.38it/s]
 34%|███▎      | 652/1939 [00:33<01:26, 14.90it/s]
 34%|███▍      | 655/1939 [00:33<01:16, 16.84it/s]
 34%|███▍      | 658/1939 [00:34<02:04, 10.27it/s]
 34%|███▍      | 660/1939 [00:34<02:15,  9.46it/s]
 34%|███▍      | 663/1939 [00:34<01:49, 11.62it/s]
 34%|███▍      | 665/1939 [00:35<01:48, 11.73it/s]
 34%|███▍      | 667/1939 [00:35<01:58, 10.72it/s]
 35%|███▍      | 670/1939 [00:35<01:32, 13.66it/s]
 35%|███▍      | 672/1939 [00:35<01:36, 13.10it/s]
 35%|███▍      | 675/1939 [00:35<01:19, 15.92it/s]
 35%|███▌      | 680/1939 [00:36<01:13, 17.09it/s]
 35%|███▌      | 682/1939 [00:36<01:12, 17.29it/s]
 35%|███▌      | 684/1939 [00:36<01:35, 13.08it/s]
 35%|███▌      | 687/1939 [00:36<01:19, 15.73it/s]
 36%|███▌      | 689/1939 [00:36<01:34, 13.24it/s]
 36%|███▌      | 691/1939 [00:36<01:29, 13.97it/s]
 36%|███▌      | 693/1939 [00:37<01:42, 12.10it/s]
 36%|███▌      | 696/1939 [00:37<01:22, 15.02it/s]
 36%|███▌      | 702/1939 [00:37<00:50, 24.28it/s]
 37%|███▋      | 708/1939 [00:37<00:39, 31.35it/s]
 37%|███▋      | 714/1939 [00:37<00:33, 36.38it/s]
 37%|███▋      | 720/1939 [00:37<00:30, 40.41it/s]
 37%|███▋      | 725/1939 [00:37<00:29, 41.70it/s]
 38%|███▊      | 730/1939 [00:38<00:40, 29.63it/s]
 38%|███▊      | 734/1939 [00:38<01:09, 17.35it/s]
 38%|███▊      | 737/1939 [00:38<01:03, 18.84it/s]
 38%|███▊      | 740/1939 [00:38<01:13, 16.40it/s]
 38%|███▊      | 743/1939 [00:39<01:27, 13.61it/s]
 39%|███▊      | 747/1939 [00:39<01:08, 17.28it/s]
 39%|███▉      | 753/1939 [00:39<00:48, 24.32it/s]
 39%|███▉      | 757/1939 [00:39<01:06, 17.84it/s]
 39%|███▉      | 760/1939 [00:40<01:10, 16.83it/s]
 39%|███▉      | 763/1939 [00:40<01:21, 14.34it/s]
 39%|███▉      | 765/1939 [00:40<01:17, 15.16it/s]
 40%|███▉      | 767/1939 [00:40<01:47, 10.91it/s]
 40%|███▉      | 769/1939 [00:41<02:36,  7.46it/s]
 40%|███▉      | 771/1939 [00:41<02:31,  7.73it/s]
 40%|███▉      | 773/1939 [00:41<02:26,  7.97it/s]
 40%|███▉      | 775/1939 [00:41<02:03,  9.42it/s]
 40%|████      | 777/1939 [00:42<02:38,  7.35it/s]
 40%|████      | 779/1939 [00:42<02:30,  7.71it/s]
 40%|████      | 780/1939 [00:42<02:44,  7.04it/s]
 40%|████      | 783/1939 [00:42<01:56,  9.93it/s]
 40%|████      | 785/1939 [00:43<02:04,  9.28it/s]
 41%|████      | 787/1939 [00:43<02:06,  9.11it/s]
 41%|████      | 789/1939 [00:43<02:16,  8.44it/s]
 41%|████      | 791/1939 [00:43<02:15,  8.46it/s]
 41%|████      | 793/1939 [00:44<01:53, 10.06it/s]
 41%|████      | 798/1939 [00:44<01:31, 12.44it/s]
 41%|████▏     | 800/1939 [00:44<01:27, 13.05it/s]
 41%|████▏     | 802/1939 [00:44<01:22, 13.75it/s]
 41%|████▏     | 804/1939 [00:44<01:32, 12.23it/s]
 42%|████▏     | 806/1939 [00:45<01:38, 11.47it/s]
 42%|████▏     | 808/1939 [00:45<01:28, 12.76it/s]
 42%|████▏     | 810/1939 [00:45<01:27, 12.88it/s]
 42%|████▏     | 812/1939 [00:45<01:39, 11.36it/s]
 42%|████▏     | 814/1939 [00:45<02:19,  8.07it/s]
 42%|████▏     | 816/1939 [00:46<02:20,  8.00it/s]
 42%|████▏     | 817/1939 [00:46<02:41,  6.95it/s]
 42%|████▏     | 818/1939 [00:46<02:36,  7.18it/s]
 42%|████▏     | 819/1939 [00:46<02:48,  6.65it/s]
 42%|████▏     | 820/1939 [00:46<03:13,  5.78it/s]
 42%|████▏     | 821/1939 [00:47<03:15,  5.71it/s]
 42%|████▏     | 823/1939 [00:47<02:41,  6.91it/s]
 43%|████▎     | 825/1939 [00:47<02:18,  8.02it/s]
 43%|████▎     | 828/1939 [00:47<01:44, 10.66it/s]
 43%|████▎     | 832/1939 [00:47<01:11, 15.56it/s]
 43%|████▎     | 838/1939 [00:47<00:45, 24.18it/s]
 44%|████▎     | 844/1939 [00:48<00:34, 31.89it/s]
 44%|████▎     | 848/1939 [00:48<00:32, 33.26it/s]
 44%|████▍     | 852/1939 [00:48<00:32, 32.94it/s]
 44%|████▍     | 857/1939 [00:48<00:44, 24.18it/s]
 44%|████▍     | 860/1939 [00:48<00:54, 19.83it/s]
 45%|████▍     | 866/1939 [00:48<00:40, 26.53it/s]
 45%|████▍     | 871/1939 [00:49<00:36, 29.33it/s]
 45%|████▌     | 878/1939 [00:49<00:29, 36.03it/s]
 46%|████▌     | 883/1939 [00:49<00:31, 33.60it/s]
 46%|████▌     | 888/1939 [00:49<00:28, 36.94it/s]
 46%|████▌     | 893/1939 [00:49<00:28, 36.56it/s]
 46%|████▋     | 899/1939 [00:49<00:25, 40.54it/s]
 47%|████▋     | 904/1939 [00:50<00:50, 20.60it/s]
 47%|████▋     | 908/1939 [00:50<00:44, 23.10it/s]
 47%|████▋     | 914/1939 [00:50<00:35, 28.94it/s]
 47%|████▋     | 919/1939 [00:50<00:41, 24.65it/s]
 48%|████▊     | 923/1939 [00:50<00:42, 24.16it/s]
 48%|████▊     | 927/1939 [00:51<00:40, 24.78it/s]
 48%|████▊     | 930/1939 [00:51<00:50, 19.93it/s]
 48%|████▊     | 933/1939 [00:51<01:08, 14.72it/s]
 48%|████▊     | 935/1939 [00:51<01:06, 15.18it/s]
 48%|████▊     | 937/1939 [00:51<01:02, 15.95it/s]
 49%|████▊     | 942/1939 [00:52<00:45, 21.99it/s]
 49%|████▉     | 948/1939 [00:52<00:33, 29.76it/s]
 49%|████▉     | 955/1939 [00:52<00:26, 36.95it/s]
 50%|████▉     | 960/1939 [00:52<00:30, 31.67it/s]
 50%|████▉     | 966/1939 [00:52<00:26, 37.11it/s]
 50%|█████     | 971/1939 [00:53<00:54, 17.83it/s]
 50%|█████     | 975/1939 [00:53<01:03, 15.08it/s]
 50%|█████     | 978/1939 [00:53<01:06, 14.53it/s]
 51%|█████     | 981/1939 [00:53<00:59, 16.23it/s]
 51%|█████     | 984/1939 [00:54<01:06, 14.29it/s]
 51%|█████     | 986/1939 [00:54<01:06, 14.44it/s]
 51%|█████     | 988/1939 [00:54<01:02, 15.16it/s]
 51%|█████     | 991/1939 [00:54<01:03, 14.90it/s]
 51%|█████     | 993/1939 [00:54<01:03, 14.99it/s]
 51%|█████▏    | 997/1939 [00:55<00:58, 15.97it/s]
 52%|█████▏    | 999/1939 [00:55<01:01, 15.28it/s]
 52%|█████▏    | 1001/1939 [00:55<00:58, 16.07it/s]
 52%|█████▏    | 1003/1939 [00:55<01:01, 15.15it/s]
 52%|█████▏    | 1005/1939 [00:55<01:00, 15.46it/s]
 52%|█████▏    | 1007/1939 [00:55<01:03, 14.72it/s]
 52%|█████▏    | 1009/1939 [00:55<01:06, 14.07it/s]
 52%|█████▏    | 1011/1939 [00:56<01:26, 10.68it/s]
 52%|█████▏    | 1013/1939 [00:56<01:38,  9.42it/s]
 52%|█████▏    | 1015/1939 [00:56<01:38,  9.37it/s]
 52%|█████▏    | 1017/1939 [00:56<01:43,  8.92it/s]
 53%|█████▎    | 1018/1939 [00:57<01:51,  8.25it/s]
 53%|█████▎    | 1019/1939 [00:57<01:53,  8.12it/s]
 53%|█████▎    | 1021/1939 [00:57<01:36,  9.51it/s]
 53%|█████▎    | 1022/1939 [00:57<01:47,  8.50it/s]
 53%|█████▎    | 1024/1939 [00:57<01:29, 10.23it/s]
 53%|█████▎    | 1030/1939 [00:57<00:43, 20.82it/s]
 53%|█████▎    | 1035/1939 [00:57<00:33, 26.73it/s]
 54%|█████▎    | 1040/1939 [00:58<00:29, 30.38it/s]
 54%|█████▍    | 1044/1939 [00:58<00:28, 31.81it/s]
 54%|█████▍    | 1048/1939 [00:58<00:54, 16.31it/s]
 54%|█████▍    | 1051/1939 [00:59<01:05, 13.66it/s]
 54%|█████▍    | 1054/1939 [00:59<01:25, 10.33it/s]
 54%|█████▍    | 1056/1939 [00:59<01:34,  9.35it/s]
 55%|█████▍    | 1058/1939 [00:59<01:24, 10.42it/s]
 55%|█████▍    | 1060/1939 [01:00<01:48,  8.12it/s]
 55%|█████▍    | 1063/1939 [01:00<01:23, 10.51it/s]
 55%|█████▌    | 1068/1939 [01:00<01:05, 13.20it/s]
 55%|█████▌    | 1070/1939 [01:00<01:02, 13.84it/s]
 55%|█████▌    | 1075/1939 [01:00<00:44, 19.59it/s]
 56%|█████▌    | 1080/1939 [01:01<00:47, 18.23it/s]
 56%|█████▌    | 1083/1939 [01:01<00:43, 19.81it/s]
 56%|█████▌    | 1087/1939 [01:01<00:37, 23.01it/s]
 56%|█████▌    | 1090/1939 [01:01<00:45, 18.76it/s]
 56%|█████▋    | 1093/1939 [01:01<00:47, 17.87it/s]
 57%|█████▋    | 1096/1939 [01:02<01:12, 11.62it/s]
 57%|█████▋    | 1098/1939 [01:02<01:13, 11.47it/s]
 57%|█████▋    | 1100/1939 [01:02<01:06, 12.53it/s]
 57%|█████▋    | 1102/1939 [01:02<01:21, 10.28it/s]
 57%|█████▋    | 1104/1939 [01:03<01:17, 10.76it/s]
 57%|█████▋    | 1106/1939 [01:03<01:09, 11.92it/s]
 57%|█████▋    | 1108/1939 [01:03<01:04, 12.92it/s]
 57%|█████▋    | 1110/1939 [01:03<00:59, 14.03it/s]
 57%|█████▋    | 1112/1939 [01:03<01:09, 11.97it/s]
 57%|█████▋    | 1114/1939 [01:03<01:07, 12.26it/s]
 58%|█████▊    | 1116/1939 [01:04<01:11, 11.57it/s]
 58%|█████▊    | 1118/1939 [01:04<01:05, 12.51it/s]
 58%|█████▊    | 1121/1939 [01:04<00:57, 14.21it/s]
 58%|█████▊    | 1123/1939 [01:04<00:54, 14.95it/s]
 58%|█████▊    | 1126/1939 [01:04<00:59, 13.55it/s]
 58%|█████▊    | 1128/1939 [01:04<01:01, 13.20it/s]
 58%|█████▊    | 1130/1939 [01:05<01:04, 12.63it/s]
 58%|█████▊    | 1133/1939 [01:05<00:53, 14.99it/s]
 59%|█████▊    | 1137/1939 [01:05<00:45, 17.65it/s]
 59%|█████▉    | 1140/1939 [01:05<00:41, 19.40it/s]
 59%|█████▉    | 1143/1939 [01:05<00:50, 15.81it/s]
 59%|█████▉    | 1145/1939 [01:06<01:14, 10.59it/s]
 59%|█████▉    | 1148/1939 [01:06<01:13, 10.81it/s]
 59%|█████▉    | 1150/1939 [01:06<01:20,  9.80it/s]
 59%|█████▉    | 1152/1939 [01:06<01:25,  9.21it/s]
 60%|█████▉    | 1154/1939 [01:07<01:29,  8.78it/s]
 60%|█████▉    | 1157/1939 [01:07<01:06, 11.75it/s]
 60%|█████▉    | 1159/1939 [01:07<01:14, 10.45it/s]
 60%|█████▉    | 1162/1939 [01:07<00:57, 13.59it/s]
 60%|██████    | 1164/1939 [01:07<01:03, 12.21it/s]
 60%|██████    | 1167/1939 [01:08<00:50, 15.17it/s]
 60%|██████    | 1172/1939 [01:08<00:40, 18.76it/s]
 61%|██████    | 1175/1939 [01:08<00:38, 19.90it/s]
 61%|██████    | 1178/1939 [01:08<00:37, 20.17it/s]
 61%|██████    | 1181/1939 [01:08<00:45, 16.50it/s]
 61%|██████    | 1183/1939 [01:08<00:54, 13.98it/s]
 61%|██████    | 1185/1939 [01:09<00:52, 14.49it/s]
 61%|██████    | 1187/1939 [01:09<01:07, 11.11it/s]
 61%|██████▏   | 1190/1939 [01:09<01:09, 10.74it/s]
 61%|██████▏   | 1192/1939 [01:09<01:10, 10.57it/s]
 62%|██████▏   | 1194/1939 [01:10<01:07, 10.96it/s]
 62%|██████▏   | 1196/1939 [01:10<01:01, 12.01it/s]
 62%|██████▏   | 1198/1939 [01:10<01:02, 11.90it/s]
 62%|██████▏   | 1200/1939 [01:10<00:55, 13.36it/s]
 62%|██████▏   | 1203/1939 [01:10<00:44, 16.68it/s]
 62%|██████▏   | 1207/1939 [01:10<00:33, 22.09it/s]
 63%|██████▎   | 1214/1939 [01:10<00:22, 32.25it/s]
 63%|██████▎   | 1218/1939 [01:10<00:25, 28.21it/s]
 63%|██████▎   | 1222/1939 [01:11<00:32, 21.92it/s]
 63%|██████▎   | 1226/1939 [01:11<00:29, 24.51it/s]
 63%|██████▎   | 1229/1939 [01:11<00:30, 23.37it/s]
 64%|██████▎   | 1234/1939 [01:11<00:25, 28.02it/s]
 64%|██████▍   | 1238/1939 [01:11<00:24, 28.35it/s]
 64%|██████▍   | 1242/1939 [01:12<00:41, 16.77it/s]
 64%|██████▍   | 1245/1939 [01:12<00:39, 17.78it/s]
 64%|██████▍   | 1250/1939 [01:12<00:29, 23.22it/s]
 65%|██████▍   | 1254/1939 [01:12<00:33, 20.32it/s]
 65%|██████▍   | 1257/1939 [01:12<00:34, 19.83it/s]
 65%|██████▌   | 1262/1939 [01:12<00:27, 24.85it/s]
 65%|██████▌   | 1268/1939 [01:13<00:21, 31.35it/s]
 66%|██████▌   | 1272/1939 [01:13<00:21, 31.01it/s]
 66%|██████▌   | 1278/1939 [01:13<00:18, 36.20it/s]
 66%|██████▌   | 1284/1939 [01:13<00:15, 41.63it/s]
 66%|██████▋   | 1289/1939 [01:13<00:25, 25.14it/s]
 67%|██████▋   | 1293/1939 [01:13<00:23, 27.56it/s]
 67%|██████▋   | 1297/1939 [01:14<00:22, 28.12it/s]
 67%|██████▋   | 1303/1939 [01:14<00:18, 33.50it/s]
 67%|██████▋   | 1307/1939 [01:14<00:18, 33.82it/s]
 68%|██████▊   | 1311/1939 [01:14<00:26, 23.58it/s]
 68%|██████▊   | 1315/1939 [01:15<00:36, 16.88it/s]
 68%|██████▊   | 1321/1939 [01:15<00:27, 22.83it/s]
 68%|██████▊   | 1325/1939 [01:15<00:32, 18.77it/s]
 69%|██████▊   | 1330/1939 [01:15<00:26, 23.09it/s]
 69%|██████▉   | 1335/1939 [01:15<00:21, 27.67it/s]
 69%|██████▉   | 1340/1939 [01:15<00:25, 23.51it/s]
 69%|██████▉   | 1344/1939 [01:16<00:30, 19.48it/s]
 69%|██████▉   | 1347/1939 [01:16<00:28, 20.88it/s]
 70%|██████▉   | 1350/1939 [01:16<00:36, 16.16it/s]
 70%|██████▉   | 1353/1939 [01:17<00:48, 12.07it/s]
 70%|██████▉   | 1355/1939 [01:17<00:47, 12.36it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 321.89it/s]
 50%|█████     | 151/300 [04:41<49:19, 19.86s/it]

[[np.int64(0), False, 13], [np.int64(1), False, 12], [np.int64(2), False, 10], [np.int64(3), False, 1], [np.int64(4), False, 10], [np.int64(5), False, 0], [np.int64(6), False, 9], [np.int64(7), False, 2], [np.int64(8), False, 4], [np.int64(11), False, 1], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9107, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.3247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0198, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [04:41<30:17, 12.36s/it]

tensor(12.3297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0010, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8645, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [04:41<18:19,  7.58s/it]

tensor(12.3499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9122, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3631, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0214, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1234, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [04:42<11:41,  4.91s/it]

tensor(12.3806, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2151, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2673, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [04:42<07:42,  3.28s/it]

tensor(12.3670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3171, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [04:42<05:11,  2.24s/it]

tensor(12.3526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3337, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3385, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3528, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [04:42<03:33,  1.56s/it]

tensor(12.3154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3667, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4004, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [04:42<02:28,  1.10s/it]

tensor(12.2987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4000, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [04:43<01:45,  1.26it/s]

tensor(12.2953, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3528, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2710, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2309, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [04:43<01:15,  1.73it/s]

tensor(12.3013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2585, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2938, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [04:43<00:55,  2.32it/s]

tensor(12.3076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3348, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [04:43<00:41,  3.04it/s]

tensor(12.3053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3729, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4113, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4454, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [04:43<00:32,  3.88it/s]

tensor(12.2772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4794, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5173, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [04:44<00:25,  4.80it/s]

tensor(12.2591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5565, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [04:44<00:21,  5.60it/s]

tensor(12.2536, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5783, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2497, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5913, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6095, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [04:44<00:18,  6.51it/s]

tensor(12.2443, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6257, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [04:44<00:15,  7.36it/s]

tensor(12.2420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6420, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6535, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6608, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [04:44<00:14,  8.07it/s]

tensor(12.2307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6744, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6869, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [04:45<00:12,  8.71it/s]

tensor(12.2205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6857, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [04:45<00:12,  9.24it/s]

tensor(12.2164, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6774, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6859, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6781, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [04:45<00:11,  9.62it/s]

tensor(12.2094, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6903, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7056, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [04:45<00:10,  9.93it/s]

tensor(12.2042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7152, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [04:45<00:10, 10.09it/s]

tensor(12.2007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7229, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7275, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [04:45<00:10, 10.24it/s]

tensor(12.1899, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7340, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7440, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [04:46<00:09, 10.34it/s]

tensor(12.1839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7491, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([165,  31, 114, 148, 179, 239,  79, 172,  34,  79, 145, 394, 141,  19])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:06, 29.20it/s]
  1%|          | 10/1939 [00:00<00:40, 48.09it/s]
  1%|          | 15/1939 [00:00<00:41, 46.32it/s]
  1%|          | 20/1939 [00:00<00:40, 47.33it/s]
  1%|▏         | 26/1939 [00:00<00:38, 49.69it/s]
  2%|▏         | 31/1939 [00:00<00:38, 49.74it/s]
  2%|▏         | 37/1939 [00:00<00:37, 51.19it/s]
  2%|▏         | 43/1939 [00:01<01:18, 24.12it/s]
  2%|▏         | 48/1939 [00:01<01:07, 28.06it/s]
  3%|▎         | 53/1939 [00:01<01:55, 16.37it/s]
  3%|▎         | 57/1939 [00:02<01:42, 18.33it/s]
  3%|▎         | 61/1939 [00:02<02:28, 12.62it/s]
  3%|▎         | 66/1939 [00:03<02:15, 13.79it/s]
  4%|▎         | 69/1939 [00:03<02:05, 14.95it/s]
  4%|▎         | 72/1939 [00:03<02:24, 12.96it/s]
  4%|▍         | 74/1939 [00:03<02:43, 11.38it/s]
  4%|▍         | 76/1939 [00:03<02:31, 12.30it/s]
  4%|▍         | 78/1939 [00:04<02:49, 10.99it/s]
  4%|▍         | 80/1939 [00:04<03:19,  9.34it/s]
  4%|▍         | 82/1939 [00:04<04:36,  6.72it/s]
  4%|▍         | 84/1939 [00:05<04:35,  6.73it/s]
  4%|▍         | 86/1939 [00:05<04:42,  6.56it/s]
  4%|▍         | 87/1939 [00:05<04:57,  6.22it/s]
  5%|▍         | 89/1939 [00:05<04:01,  7.65it/s]
  5%|▍         | 92/1939 [00:06<02:50, 10.86it/s]
  5%|▍         | 94/1939 [00:06<03:07,  9.85it/s]
  5%|▍         | 96/1939 [00:06<02:45, 11.11it/s]
  5%|▌         | 100/1939 [00:06<02:22, 12.87it/s]
  5%|▌         | 102/1939 [00:06<02:54, 10.51it/s]
  5%|▌         | 105/1939 [00:07<02:53, 10.56it/s]
  6%|▌         | 107/1939 [00:07<02:36, 11.71it/s]
  6%|▌         | 110/1939 [00:07<02:35, 11.77it/s]
  6%|▌         | 113/1939 [00:07<02:05, 14.56it/s]
  6%|▌         | 115/1939 [00:07<02:33, 11.87it/s]
  6%|▌         | 118/1939 [00:08<02:50, 10.71it/s]
  6%|▌         | 120/1939 [00:08<03:07,  9.70it/s]
  6%|▋         | 122/1939 [00:08<03:22,  8.96it/s]
  6%|▋         | 124/1939 [00:08<03:02,  9.96it/s]
  7%|▋         | 127/1939 [00:09<02:17, 13.14it/s]
  7%|▋         | 129/1939 [00:09<02:30, 12.02it/s]
  7%|▋         | 131/1939 [00:09<02:17, 13.19it/s]
  7%|▋         | 133/1939 [00:09<02:46, 10.88it/s]
  7%|▋         | 135/1939 [00:09<02:35, 11.62it/s]
  7%|▋         | 137/1939 [00:09<02:16, 13.17it/s]
  7%|▋         | 139/1939 [00:10<02:12, 13.59it/s]
  7%|▋         | 142/1939 [00:10<01:46, 16.82it/s]
  7%|▋         | 145/1939 [00:10<02:12, 13.58it/s]
  8%|▊         | 147/1939 [00:10<02:22, 12.60it/s]
  8%|▊         | 150/1939 [00:10<01:54, 15.65it/s]
  8%|▊         | 152/1939 [00:10<02:01, 14.71it/s]
  8%|▊         | 154/1939 [00:11<02:26, 12.15it/s]
  8%|▊         | 157/1939 [00:11<02:13, 13.39it/s]
  8%|▊         | 159/1939 [00:11<02:48, 10.56it/s]
  8%|▊         | 161/1939 [00:12<03:37,  8.18it/s]
  8%|▊         | 163/1939 [00:12<03:46,  7.86it/s]
  8%|▊         | 164/1939 [00:12<03:55,  7.53it/s]
  9%|▊         | 166/1939 [00:12<03:17,  8.97it/s]
  9%|▉         | 171/1939 [00:12<01:52, 15.78it/s]
  9%|▉         | 177/1939 [00:12<01:13, 23.97it/s]
  9%|▉         | 181/1939 [00:12<01:06, 26.49it/s]
 10%|▉         | 185/1939 [00:13<00:59, 29.32it/s]
 10%|▉         | 191/1939 [00:13<00:48, 36.09it/s]
 10%|█         | 196/1939 [00:13<00:44, 39.26it/s]
 10%|█         | 202/1939 [00:13<01:01, 28.37it/s]
 11%|█         | 206/1939 [00:14<02:14, 12.93it/s]
 11%|█         | 209/1939 [00:14<02:05, 13.82it/s]
 11%|█         | 212/1939 [00:14<01:59, 14.42it/s]
 11%|█         | 215/1939 [00:14<01:45, 16.31it/s]
 11%|█▏        | 221/1939 [00:14<01:14, 23.03it/s]
 12%|█▏        | 225/1939 [00:15<01:05, 26.14it/s]
 66%|██████▋   | 199/300 [05:04<00:09, 10.34it/s]]
 12%|█▏        | 233/1939 [00:15<02:08, 13.28it/s]
 12%|█▏        | 236/1939 [00:16<02:25, 11.71it/s]
 12%|█▏        | 238/1939 [00:16<02:17, 12.39it/s]
 12%|█▏        | 240/1939 [00:16<03:11,  8.85it/s]
 12%|█▏        | 242/1939 [00:17<03:16,  8.64it/s]
 13%|█▎        | 244/1939 [00:17<03:28,  8.14it/s]
 13%|█▎        | 246/1939 [00:17<04:20,  6.49it/s]
 13%|█▎        | 248/1939 [00:18<04:24,  6.40it/s]
 13%|█▎        | 250/1939 [00:18<03:44,  7.52it/s]
 13%|█▎        | 257/1939 [00:18<02:22, 11.78it/s]
 13%|█▎        | 259/1939 [00:18<02:14, 12.48it/s]
 13%|█▎        | 261/1939 [00:19<02:40, 10.45it/s]
 14%|█▎        | 263/1939 [00:19<02:56,  9.50it/s]
 14%|█▎        | 266/1939 [00:19<02:21, 11.85it/s]
 14%|█▍        | 273/1939 [00:19<01:20, 20.74it/s]
 14%|█▍        | 280/1939 [00:19<00:56, 29.15it/s]
 15%|█▍        | 284/1939 [00:20<01:47, 15.47it/s]
 15%|█▍        | 287/1939 [00:20<01:41, 16.24it/s]
 15%|█▌        | 291/1939 [00:20<01:24, 19.60it/s]
 15%|█▌        | 296/1939 [00:20<01:06, 24.66it/s]
 15%|█▌        | 300/1939 [00:20<01:03, 25.75it/s]
 16%|█▌        | 306/1939 [00:20<00:50, 32.30it/s]
 16%|█▌        | 312/1939 [00:21<00:42, 38.31it/s]
 16%|█▋        | 318/1939 [00:21<00:37, 42.79it/s]
 17%|█▋        | 323/1939 [00:21<00:59, 27.38it/s]
 17%|█▋        | 328/1939 [00:21<00:52, 30.87it/s]
 17%|█▋        | 334/1939 [00:21<00:47, 33.65it/s]
 17%|█▋        | 339/1939 [00:21<00:43, 36.53it/s]
 18%|█▊        | 344/1939 [00:22<00:45, 35.17it/s]
 18%|█▊        | 350/1939 [00:22<00:40, 38.84it/s]
 18%|█▊        | 355/1939 [00:22<01:32, 17.15it/s]
 19%|█▊        | 360/1939 [00:22<01:15, 20.87it/s]
 19%|█▉        | 364/1939 [00:23<01:26, 18.24it/s]
 19%|█▉        | 367/1939 [00:23<01:21, 19.24it/s]
 19%|█▉        | 370/1939 [00:23<01:35, 16.38it/s]
 19%|█▉        | 373/1939 [00:23<01:29, 17.49it/s]
 19%|█▉        | 376/1939 [00:24<01:42, 15.28it/s]
 19%|█▉        | 378/1939 [00:24<01:40, 15.47it/s]
 20%|█▉        | 381/1939 [00:24<01:56, 13.37it/s]
 20%|█▉        | 383/1939 [00:24<01:51, 13.98it/s]
 20%|█▉        | 385/1939 [00:24<02:15, 11.49it/s]
 20%|█▉        | 387/1939 [00:25<02:39,  9.74it/s]
 20%|██        | 389/1939 [00:25<03:08,  8.22it/s]
 20%|██        | 390/1939 [00:25<03:03,  8.42it/s]
 20%|██        | 392/1939 [00:25<02:33, 10.08it/s]
 20%|██        | 394/1939 [00:25<02:45,  9.33it/s]
 20%|██        | 396/1939 [00:26<03:16,  7.84it/s]
 20%|██        | 397/1939 [00:26<03:09,  8.16it/s]
 21%|██        | 398/1939 [00:26<03:39,  7.02it/s]
 21%|██        | 400/1939 [00:26<02:56,  8.72it/s]
 21%|██        | 404/1939 [00:27<02:26, 10.44it/s]
 21%|██        | 406/1939 [00:27<02:47,  9.13it/s]
 21%|██        | 407/1939 [00:27<03:17,  7.75it/s]
 21%|██        | 409/1939 [00:27<02:45,  9.27it/s]
 21%|██        | 411/1939 [00:27<02:50,  8.96it/s]
 21%|██▏       | 414/1939 [00:28<02:08, 11.83it/s]
 21%|██▏       | 416/1939 [00:28<02:36,  9.74it/s]
 22%|██▏       | 418/1939 [00:28<03:02,  8.33it/s]
 22%|██▏       | 419/1939 [00:28<03:37,  7.00it/s]
 22%|██▏       | 421/1939 [00:29<02:57,  8.55it/s]
 22%|██▏       | 423/1939 [00:29<03:05,  8.19it/s]
 22%|██▏       | 426/1939 [00:29<02:56,  8.56it/s]
 22%|██▏       | 428/1939 [00:30<03:18,  7.63it/s]
 22%|██▏       | 432/1939 [00:30<02:11, 11.46it/s]
 23%|██▎       | 439/1939 [00:30<01:14, 20.15it/s]
 23%|██▎       | 445/1939 [00:30<00:56, 26.66it/s]
 23%|██▎       | 449/1939 [00:30<00:58, 25.39it/s]
 23%|██▎       | 453/1939 [00:30<00:55, 26.98it/s]
 24%|██▎       | 459/1939 [00:30<00:44, 33.42it/s]
 24%|██▍       | 464/1939 [00:30<00:40, 36.48it/s]
 24%|██▍       | 469/1939 [00:31<00:38, 38.60it/s]
 25%|██▍       | 476/1939 [00:31<00:31, 46.43it/s]
 25%|██▍       | 482/1939 [00:31<00:53, 27.03it/s]
 25%|██▌       | 486/1939 [00:31<00:57, 25.46it/s]
 25%|██▌       | 490/1939 [00:31<01:02, 23.12it/s]
 25%|██▌       | 493/1939 [00:32<01:18, 18.46it/s]
 26%|██▌       | 496/1939 [00:32<01:11, 20.11it/s]
 26%|██▌       | 502/1939 [00:32<00:58, 24.39it/s]
 26%|██▌       | 506/1939 [00:32<00:53, 26.57it/s]
 26%|██▋       | 511/1939 [00:32<01:02, 22.91it/s]
 27%|██▋       | 514/1939 [00:33<01:03, 22.47it/s]
 27%|██▋       | 519/1939 [00:33<00:51, 27.56it/s]
 27%|██▋       | 525/1939 [00:33<00:41, 34.04it/s]
 27%|██▋       | 529/1939 [00:33<00:42, 33.20it/s]
 28%|██▊       | 535/1939 [00:33<00:35, 39.05it/s]
 28%|██▊       | 540/1939 [00:33<00:56, 24.72it/s]
 28%|██▊       | 546/1939 [00:34<01:05, 21.15it/s]
 28%|██▊       | 549/1939 [00:34<01:34, 14.71it/s]
 28%|██▊       | 552/1939 [00:35<01:50, 12.51it/s]
 29%|██▊       | 557/1939 [00:35<01:22, 16.78it/s]
 29%|██▉       | 561/1939 [00:35<01:09, 19.90it/s]
 29%|██▉       | 567/1939 [00:35<00:52, 26.34it/s]
 29%|██▉       | 571/1939 [00:35<01:04, 21.12it/s]
 30%|██▉       | 575/1939 [00:36<02:06, 10.81it/s]
 30%|██▉       | 578/1939 [00:36<01:49, 12.39it/s]
 30%|██▉       | 581/1939 [00:36<01:56, 11.68it/s]
 30%|███       | 583/1939 [00:37<02:10, 10.40it/s]
 30%|███       | 585/1939 [00:37<02:24,  9.40it/s]
 30%|███       | 587/1939 [00:37<02:06, 10.69it/s]
 31%|███       | 592/1939 [00:37<01:42, 13.14it/s]
 31%|███       | 594/1939 [00:38<01:39, 13.48it/s]
 31%|███       | 599/1939 [00:38<01:34, 14.15it/s]
 31%|███       | 601/1939 [00:38<01:59, 11.21it/s]
 31%|███       | 603/1939 [00:38<02:14,  9.93it/s]
 31%|███       | 605/1939 [00:39<02:01, 11.02it/s]
 31%|███▏      | 607/1939 [00:39<02:13,  9.99it/s]
 31%|███▏      | 609/1939 [00:39<02:36,  8.52it/s]
 32%|███▏      | 611/1939 [00:40<02:59,  7.41it/s]
 32%|███▏      | 612/1939 [00:40<03:06,  7.11it/s]
 32%|███▏      | 613/1939 [00:40<03:05,  7.14it/s]
 32%|███▏      | 614/1939 [00:40<03:13,  6.85it/s]
 32%|███▏      | 615/1939 [00:40<03:29,  6.33it/s]
 32%|███▏      | 616/1939 [00:40<03:25,  6.44it/s]
 32%|███▏      | 617/1939 [00:41<03:21,  6.56it/s]
 32%|███▏      | 618/1939 [00:41<03:18,  6.65it/s]
 32%|███▏      | 620/1939 [00:41<03:30,  6.27it/s]
 32%|███▏      | 621/1939 [00:41<03:57,  5.56it/s]
 32%|███▏      | 622/1939 [00:41<04:19,  5.08it/s]
 32%|███▏      | 624/1939 [00:42<03:00,  7.28it/s]
 32%|███▏      | 629/1939 [00:42<02:02, 10.67it/s]
 33%|███▎      | 631/1939 [00:42<02:26,  8.90it/s]
 33%|███▎      | 632/1939 [00:42<02:42,  8.05it/s]
 33%|███▎      | 634/1939 [00:43<02:14,  9.68it/s]
 33%|███▎      | 636/1939 [00:43<02:38,  8.23it/s]
 33%|███▎      | 637/1939 [00:43<03:06,  6.99it/s]
 33%|███▎      | 638/1939 [00:43<02:56,  7.36it/s]
 33%|███▎      | 640/1939 [00:44<03:17,  6.57it/s]
 33%|███▎      | 641/1939 [00:44<03:21,  6.44it/s]
 33%|███▎      | 643/1939 [00:44<03:18,  6.54it/s]
 33%|███▎      | 645/1939 [00:44<02:46,  7.77it/s]
 33%|███▎      | 649/1939 [00:45<02:09,  9.93it/s]
 34%|███▎      | 651/1939 [00:45<02:27,  8.73it/s]
 34%|███▎      | 653/1939 [00:45<02:10,  9.88it/s]
 34%|███▍      | 655/1939 [00:45<02:37,  8.13it/s]
 34%|███▍      | 656/1939 [00:46<03:05,  6.92it/s]
 34%|███▍      | 658/1939 [00:46<03:17,  6.48it/s]
 34%|███▍      | 659/1939 [00:46<03:14,  6.57it/s]
 34%|███▍      | 661/1939 [00:46<02:31,  8.44it/s]
 34%|███▍      | 663/1939 [00:46<02:03, 10.35it/s]
 34%|███▍      | 665/1939 [00:47<02:12,  9.59it/s]
 34%|███▍      | 667/1939 [00:47<02:14,  9.49it/s]
 35%|███▍      | 669/1939 [00:47<02:18,  9.18it/s]
 35%|███▍      | 672/1939 [00:47<02:20,  9.01it/s]
 35%|███▍      | 674/1939 [00:47<02:04, 10.14it/s]
 35%|███▌      | 680/1939 [00:48<01:33, 13.43it/s]
 35%|███▌      | 683/1939 [00:48<01:46, 11.76it/s]
 35%|███▌      | 686/1939 [00:48<01:28, 14.15it/s]
 35%|███▌      | 688/1939 [00:49<01:52, 11.09it/s]
 36%|███▌      | 690/1939 [00:49<02:09,  9.63it/s]
 36%|███▌      | 692/1939 [00:49<01:53, 11.02it/s]
 36%|███▌      | 699/1939 [00:49<01:00, 20.45it/s]
 36%|███▋      | 704/1939 [00:49<00:47, 25.88it/s]
 37%|███▋      | 709/1939 [00:49<00:40, 30.20it/s]
 37%|███▋      | 715/1939 [00:49<00:34, 35.90it/s]
 37%|███▋      | 720/1939 [00:49<00:34, 35.85it/s]
 37%|███▋      | 726/1939 [00:50<00:32, 37.09it/s]
 38%|███▊      | 731/1939 [00:50<00:57, 20.92it/s]
 38%|███▊      | 735/1939 [00:51<01:12, 16.63it/s]
 38%|███▊      | 738/1939 [00:51<01:07, 17.87it/s]
 38%|███▊      | 741/1939 [00:51<01:11, 16.75it/s]
 38%|███▊      | 744/1939 [00:51<01:13, 16.25it/s]
 38%|███▊      | 746/1939 [00:51<01:17, 15.41it/s]
 39%|███▊      | 748/1939 [00:51<01:19, 15.03it/s]
 39%|███▊      | 750/1939 [00:52<01:44, 11.40it/s]
 39%|███▉      | 752/1939 [00:52<01:36, 12.36it/s]
 39%|███▉      | 755/1939 [00:52<01:22, 14.31it/s]
 39%|███▉      | 757/1939 [00:52<01:23, 14.12it/s]
 39%|███▉      | 759/1939 [00:52<01:19, 14.83it/s]
 39%|███▉      | 761/1939 [00:52<01:40, 11.76it/s]
 39%|███▉      | 763/1939 [00:53<01:58,  9.94it/s]
 40%|███▉      | 766/1939 [00:53<01:50, 10.58it/s]
 40%|███▉      | 768/1939 [00:53<02:19,  8.41it/s]
 40%|███▉      | 770/1939 [00:54<02:08,  9.09it/s]
 40%|███▉      | 772/1939 [00:54<02:05,  9.29it/s]
 40%|███▉      | 774/1939 [00:54<01:58,  9.83it/s]
 40%|████      | 776/1939 [00:54<02:16,  8.55it/s]
 40%|████      | 777/1939 [00:54<02:26,  7.94it/s]
 40%|████      | 779/1939 [00:55<02:28,  7.81it/s]
 40%|████      | 780/1939 [00:55<02:37,  7.35it/s]
 40%|████      | 782/1939 [00:55<02:05,  9.23it/s]
 40%|████      | 784/1939 [00:55<02:14,  8.57it/s]
 41%|████      | 786/1939 [00:55<01:50, 10.44it/s]
 41%|████      | 788/1939 [00:56<02:06,  9.11it/s]
 41%|████      | 790/1939 [00:56<02:19,  8.26it/s]
 41%|████      | 792/1939 [00:56<01:59,  9.63it/s]
 41%|████      | 794/1939 [00:56<01:43, 11.06it/s]
 41%|████      | 796/1939 [00:56<01:31, 12.51it/s]
 41%|████      | 798/1939 [00:57<01:47, 10.63it/s]
 41%|████▏     | 801/1939 [00:57<01:21, 13.94it/s]
 41%|████▏     | 804/1939 [00:57<01:31, 12.45it/s]
 42%|████▏     | 806/1939 [00:58<02:34,  7.35it/s]
 42%|████▏     | 809/1939 [00:58<02:23,  7.86it/s]
 42%|████▏     | 811/1939 [00:58<02:02,  9.22it/s]
 42%|████▏     | 813/1939 [00:58<02:43,  6.91it/s]
 42%|████▏     | 816/1939 [00:59<02:28,  7.54it/s]
 42%|████▏     | 818/1939 [00:59<02:58,  6.29it/s]
 42%|████▏     | 819/1939 [01:00<03:14,  5.75it/s]
 42%|████▏     | 820/1939 [01:00<03:24,  5.48it/s]
 42%|████▏     | 821/1939 [01:00<03:32,  5.25it/s]
 42%|████▏     | 822/1939 [01:00<03:49,  4.87it/s]
 42%|████▏     | 823/1939 [01:00<03:34,  5.20it/s]
 43%|████▎     | 825/1939 [01:01<02:47,  6.65it/s]
 43%|████▎     | 827/1939 [01:01<02:10,  8.54it/s]
 43%|████▎     | 829/1939 [01:01<01:44, 10.64it/s]
 43%|████▎     | 834/1939 [01:01<00:59, 18.71it/s]
 43%|████▎     | 840/1939 [01:01<00:39, 27.65it/s]
 44%|████▎     | 844/1939 [01:01<00:37, 29.39it/s]
 44%|████▍     | 850/1939 [01:01<00:30, 35.37it/s]
 44%|████▍     | 856/1939 [01:01<00:26, 40.88it/s]
 44%|████▍     | 861/1939 [01:02<00:44, 24.35it/s]
 45%|████▍     | 865/1939 [01:02<00:40, 26.71it/s]
 45%|████▍     | 871/1939 [01:02<00:32, 32.57it/s]
 45%|████▌     | 876/1939 [01:02<00:30, 35.42it/s]
 45%|████▌     | 881/1939 [01:02<00:27, 38.70it/s]
 46%|████▌     | 886/1939 [01:02<00:25, 40.60it/s]
 46%|████▌     | 891/1939 [01:02<00:26, 40.11it/s]
 46%|████▌     | 896/1939 [01:02<00:24, 41.99it/s]
 46%|████▋     | 901/1939 [01:03<00:52, 19.78it/s]
 47%|████▋     | 905/1939 [01:03<01:05, 15.68it/s]
 47%|████▋     | 908/1939 [01:04<01:01, 16.83it/s]
 47%|████▋     | 911/1939 [01:04<01:10, 14.67it/s]
 47%|████▋     | 914/1939 [01:04<01:16, 13.47it/s]
 47%|████▋     | 916/1939 [01:04<01:27, 11.69it/s]
 47%|████▋     | 918/1939 [01:05<01:41, 10.06it/s]
 47%|████▋     | 920/1939 [01:05<01:32, 11.07it/s]
 48%|████▊     | 926/1939 [01:05<00:54, 18.63it/s]
 48%|████▊     | 929/1939 [01:05<01:10, 14.25it/s]
 48%|████▊     | 932/1939 [01:06<01:47,  9.39it/s]
 48%|████▊     | 936/1939 [01:06<01:18, 12.71it/s]
 49%|████▊     | 943/1939 [01:06<00:49, 19.92it/s]
 49%|████▉     | 949/1939 [01:06<00:40, 24.55it/s]
 49%|████▉     | 954/1939 [01:06<00:35, 27.98it/s]
 49%|████▉     | 959/1939 [01:06<00:30, 31.84it/s]
 50%|████▉     | 965/1939 [01:07<00:25, 37.62it/s]
 50%|█████     | 970/1939 [01:07<01:00, 15.92it/s]
 50%|█████     | 974/1939 [01:08<01:20, 11.93it/s]
 50%|█████     | 977/1939 [01:08<01:23, 11.55it/s]
 51%|█████     | 980/1939 [01:08<01:17, 12.31it/s]
 51%|█████     | 982/1939 [01:09<01:27, 10.97it/s]
 51%|█████     | 984/1939 [01:09<01:22, 11.61it/s]
 51%|█████     | 988/1939 [01:09<01:02, 15.23it/s]
 51%|█████     | 991/1939 [01:09<01:05, 14.52it/s]
 51%|█████     | 993/1939 [01:09<01:02, 15.02it/s]
 51%|█████▏    | 997/1939 [01:10<01:01, 15.35it/s]
 52%|█████▏    | 999/1939 [01:10<01:24, 11.15it/s]
 52%|█████▏    | 1001/1939 [01:10<01:17, 12.10it/s]
 52%|█████▏    | 1003/1939 [01:10<01:30, 10.29it/s]
 52%|█████▏    | 1005/1939 [01:11<01:41,  9.16it/s]
 52%|█████▏    | 1007/1939 [01:11<01:59,  7.80it/s]
 52%|█████▏    | 1009/1939 [01:11<02:12,  7.04it/s]
 52%|█████▏    | 1010/1939 [01:12<02:27,  6.28it/s]
 52%|█████▏    | 1011/1939 [01:12<02:36,  5.91it/s]
 52%|█████▏    | 1012/1939 [01:12<02:41,  5.75it/s]
 52%|█████▏    | 1014/1939 [01:12<02:03,  7.48it/s]
 52%|█████▏    | 1015/1939 [01:12<01:58,  7.79it/s]
 52%|█████▏    | 1016/1939 [01:12<02:20,  6.55it/s]
 53%|█████▎    | 1018/1939 [01:13<02:15,  6.81it/s]
 53%|█████▎    | 1019/1939 [01:13<02:21,  6.52it/s]
 53%|█████▎    | 1021/1939 [01:13<01:45,  8.70it/s]
 53%|█████▎    | 1023/1939 [01:13<01:34,  9.72it/s]
 53%|█████▎    | 1026/1939 [01:13<01:13, 12.48it/s]
 53%|█████▎    | 1028/1939 [01:14<01:21, 11.19it/s]
 53%|█████▎    | 1031/1939 [01:14<01:02, 14.48it/s]
 53%|█████▎    | 1035/1939 [01:14<00:47, 18.83it/s]
 54%|█████▎    | 1039/1939 [01:14<00:38, 23.41it/s]
 54%|█████▎    | 1042/1939 [01:14<00:46, 19.35it/s]
 54%|█████▍    | 1045/1939 [01:14<01:02, 14.23it/s]
 54%|█████▍    | 1047/1939 [01:15<01:00, 14.72it/s]
 54%|█████▍    | 1049/1939 [01:15<01:21, 10.94it/s]
 54%|█████▍    | 1051/1939 [01:15<01:31,  9.67it/s]
 54%|█████▍    | 1053/1939 [01:16<02:04,  7.12it/s]
 54%|█████▍    | 1054/1939 [01:16<02:19,  6.34it/s]
 54%|█████▍    | 1056/1939 [01:16<02:24,  6.13it/s]
 55%|█████▍    | 1059/1939 [01:17<02:04,  7.06it/s]
 55%|█████▍    | 1060/1939 [01:17<02:18,  6.34it/s]
 55%|█████▍    | 1062/1939 [01:17<01:49,  8.03it/s]
 55%|█████▌    | 1067/1939 [01:17<01:00, 14.38it/s]
 55%|█████▌    | 1070/1939 [01:17<01:11, 12.21it/s]
 55%|█████▌    | 1074/1939 [01:17<00:52, 16.45it/s]
 56%|█████▌    | 1080/1939 [01:18<00:50, 17.13it/s]
 56%|█████▌    | 1083/1939 [01:18<00:45, 18.65it/s]
 56%|█████▌    | 1088/1939 [01:18<00:47, 17.98it/s]
 56%|█████▋    | 1091/1939 [01:18<00:45, 18.81it/s]
 56%|█████▋    | 1094/1939 [01:19<01:12, 11.72it/s]
 57%|█████▋    | 1096/1939 [01:19<01:26,  9.73it/s]
 57%|█████▋    | 1098/1939 [01:20<01:35,  8.84it/s]
 57%|█████▋    | 1102/1939 [01:20<01:25,  9.82it/s]
 57%|█████▋    | 1104/1939 [01:20<01:34,  8.82it/s]
 57%|█████▋    | 1106/1939 [01:21<02:03,  6.73it/s]
 57%|█████▋    | 1108/1939 [01:21<01:44,  7.92it/s]
 57%|█████▋    | 1112/1939 [01:21<01:30,  9.16it/s]
 57%|█████▋    | 1114/1939 [01:21<01:38,  8.39it/s]
 58%|█████▊    | 1116/1939 [01:22<01:48,  7.60it/s]
 58%|█████▊    | 1119/1939 [01:22<01:26,  9.52it/s]
 58%|█████▊    | 1121/1939 [01:22<01:41,  8.09it/s]
 58%|█████▊    | 1123/1939 [01:22<01:26,  9.43it/s]
 58%|█████▊    | 1129/1939 [01:23<01:03, 12.70it/s]
 58%|█████▊    | 1131/1939 [01:23<01:00, 13.26it/s]
 59%|█████▊    | 1136/1939 [01:23<00:42, 19.04it/s]
 59%|█████▊    | 1139/1939 [01:23<01:01, 13.02it/s]
 59%|█████▉    | 1141/1939 [01:24<01:09, 11.40it/s]
 59%|█████▉    | 1143/1939 [01:24<01:24,  9.37it/s]
 59%|█████▉    | 1145/1939 [01:24<01:33,  8.48it/s]
 59%|█████▉    | 1147/1939 [01:25<01:25,  9.30it/s]
 59%|█████▉    | 1149/1939 [01:25<01:33,  8.48it/s]
 59%|█████▉    | 1151/1939 [01:25<02:07,  6.18it/s]
 59%|█████▉    | 1153/1939 [01:26<02:05,  6.27it/s]
 60%|█████▉    | 1155/1939 [01:26<01:42,  7.68it/s]
 60%|█████▉    | 1158/1939 [01:26<01:24,  9.24it/s]
 60%|█████▉    | 1160/1939 [01:26<01:13, 10.62it/s]
 60%|█████▉    | 1163/1939 [01:26<01:11, 10.82it/s]
 60%|██████    | 1165/1939 [01:27<01:08, 11.25it/s]
 60%|██████    | 1168/1939 [01:27<00:53, 14.36it/s]
 60%|██████    | 1172/1939 [01:27<00:44, 17.34it/s]
 61%|██████    | 1174/1939 [01:27<00:43, 17.72it/s]
 61%|██████    | 1178/1939 [01:27<00:49, 15.37it/s]
 61%|██████    | 1180/1939 [01:28<01:04, 11.68it/s]
 61%|██████    | 1183/1939 [01:28<01:10, 10.79it/s]
 61%|██████    | 1186/1939 [01:28<01:15,  9.96it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 310.91it/s]
 67%|██████▋   | 201/300 [07:05<34:40, 21.02s/it]

[[np.int64(0), False, 3], [np.int64(1), False, 12], [np.int64(2), False, 7], [np.int64(3), False, 12], [np.int64(4), False, 11], [np.int64(5), False, 11], [np.int64(6), False, 12], [np.int64(8), False, 2], [np.int64(9), False, 0], [np.int64(10), False, 11], [np.int64(13), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9967, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.2060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1454, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 202/300 [07:06<28:19, 17.34s/it]

tensor(12.2406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0508, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [07:06<17:16, 10.79s/it]

tensor(12.2605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9973, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1142, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2468, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1801, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [07:06<10:22,  6.63s/it]

tensor(12.2447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1722, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [07:06<06:34,  4.29s/it]

tensor(12.2526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1273, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0429, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2640, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0460, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2222, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [07:06<04:18,  2.87s/it]

tensor(12.2475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0501, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2682, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0542, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3982, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [07:06<02:53,  1.97s/it]

tensor(12.2177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0577, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5778, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [07:07<01:58,  1.37s/it]

tensor(12.2092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0606, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5679, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0625, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6179, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0631, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6478, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [07:07<01:21,  1.03it/s]

tensor(12.2055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0621, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6305, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0606, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6540, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [07:07<00:57,  1.42it/s]

tensor(12.2117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0585, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6663, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [07:07<00:41,  1.93it/s]

tensor(12.2147, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0558, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7008, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0532, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5604, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0504, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5648, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [07:07<00:30,  2.57it/s]

tensor(12.2155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0479, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5070, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0452, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8988, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [07:08<00:22,  3.33it/s]

tensor(12.2095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0425, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9466, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [07:08<00:17,  4.21it/s]

tensor(12.2101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0404, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0399, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1390, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0405, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1346, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [07:08<00:14,  5.13it/s]

tensor(12.2327, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0420, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3253, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0424, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3867, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [07:08<00:11,  6.04it/s]

tensor(12.2339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0417, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4466, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [07:08<00:09,  6.93it/s]

tensor(12.2263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0410, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5593, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0400, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5777, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0388, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5429, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [07:09<00:08,  7.70it/s]

tensor(12.2021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0378, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5055, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0371, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5086, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [07:09<00:07,  8.39it/s]

tensor(12.2077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0367, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5052, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [07:09<00:06,  8.95it/s]

tensor(12.2075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5045, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1888, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4456, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [07:09<00:06,  9.40it/s]

tensor(12.1730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4476, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4738, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [07:09<00:05,  9.71it/s]

tensor(12.1562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5215, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [07:10<00:05,  9.93it/s]

tensor(12.1565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5447, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5590, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5618, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [07:10<00:05, 10.06it/s]

tensor(12.1550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5588, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5577, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [07:10<00:05, 10.20it/s]

tensor(12.1389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5582, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [07:10<00:04, 10.24it/s]

tensor(12.1306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5625, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([142, 271, 118,  77, 142,  93, 274, 161,  89, 305,  29,  83,  35, 120])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 1/1939 [00:00<04:00,  8.04it/s]
  0%|          | 3/1939 [00:00<03:17,  9.82it/s]
  0%|          | 5/1939 [00:00<02:38, 12.21it/s]
  0%|          | 7/1939 [00:00<03:55,  8.20it/s]
  1%|          | 11/1939 [00:00<02:17, 14.05it/s]
  1%|          | 13/1939 [00:01<02:10, 14.74it/s]
  1%|          | 17/1939 [00:01<01:57, 16.38it/s]
  1%|          | 19/1939 [00:01<01:57, 16.40it/s]
  1%|          | 21/1939 [00:01<02:19, 13.76it/s]
  1%|          | 24/1939 [00:01<02:08, 14.88it/s]
  1%|▏         | 26/1939 [00:02<02:38, 12.10it/s]
  1%|▏         | 28/1939 [00:02<02:58, 10.68it/s]
  2%|▏         | 30/1939 [00:02<02:49, 11.25it/s]
  2%|▏         | 32/1939 [00:02<02:34, 12.34it/s]
  2%|▏         | 34/1939 [00:02<02:31, 12.56it/s]
  2%|▏         | 36/1939 [00:02<02:33, 12.40it/s]
  2%|▏         | 38/1939 [00:03<03:03, 10.34it/s]
  2%|▏         | 40/1939 [00:03<02:38, 11.97it/s]
  2%|▏         | 42/1939 [00:03<02:58, 10.61it/s]
  2%|▏         | 44/1939 [00:03<02:35, 12.21it/s]
  2%|▏         | 47/1939 [00:03<01:59, 15.77it/s]
  3%|▎         | 49/1939 [00:03<02:37, 11.99it/s]
  3%|▎         | 51/1939 [00:04<02:21, 13.30it/s]
  3%|▎         | 53/1939 [00:04<02:43, 11.55it/s]
  3%|▎         | 55/1939 [00:04<02:24, 13.07it/s]
  3%|▎         | 57/1939 [00:04<02:52, 10.91it/s]
  3%|▎         | 59/1939 [00:05<03:53,  8.04it/s]
  3%|▎         | 61/1939 [00:05<03:16,  9.55it/s]
  3%|▎         | 66/1939 [00:05<02:28, 12.60it/s]
  4%|▎         | 68/1939 [00:05<02:16, 13.74it/s]
  4%|▎         | 70/1939 [00:05<02:34, 12.08it/s]
  4%|▎         | 72/1939 [00:06<03:18,  9.42it/s]
  4%|▍         | 74/1939 [00:06<03:48,  8.15it/s]
  4%|▍         | 76/1939 [00:06<03:11,  9.74it/s]
  4%|▍         | 78/1939 [00:06<03:32,  8.76it/s]
  4%|▍         | 80/1939 [00:07<04:28,  6.92it/s]
  4%|▍         | 81/1939 [00:07<05:07,  6.04it/s]
  4%|▍         | 82/1939 [00:07<05:15,  5.88it/s]
  4%|▍         | 84/1939 [00:07<04:43,  6.54it/s]
  4%|▍         | 86/1939 [00:08<04:23,  7.03it/s]
  4%|▍         | 87/1939 [00:08<04:45,  6.49it/s]
  5%|▍         | 89/1939 [00:08<03:36,  8.55it/s]
  5%|▍         | 94/1939 [00:08<02:28, 12.46it/s]
  5%|▍         | 96/1939 [00:09<02:51, 10.76it/s]
  5%|▌         | 98/1939 [00:09<02:32, 12.08it/s]
  5%|▌         | 100/1939 [00:09<02:45, 11.13it/s]
  5%|▌         | 102/1939 [00:09<03:03, 10.00it/s]
  5%|▌         | 105/1939 [00:09<02:55, 10.47it/s]
  6%|▌         | 107/1939 [00:09<02:35, 11.74it/s]
  6%|▌         | 110/1939 [00:10<02:35, 11.78it/s]
 83%|████████▎ | 250/300 [07:24<00:04, 10.24it/s]]
  6%|▌         | 114/1939 [00:10<02:40, 11.37it/s]
  6%|▌         | 116/1939 [00:10<02:47, 10.91it/s]
  6%|▌         | 118/1939 [00:11<03:54,  7.76it/s]
  6%|▌         | 120/1939 [00:11<04:09,  7.29it/s]
  6%|▌         | 121/1939 [00:11<04:32,  6.67it/s]
  6%|▋         | 123/1939 [00:11<03:36,  8.40it/s]
  6%|▋         | 126/1939 [00:12<03:10,  9.53it/s]
  7%|▋         | 128/1939 [00:12<03:13,  9.35it/s]
  7%|▋         | 130/1939 [00:12<02:48, 10.73it/s]
  7%|▋         | 132/1939 [00:12<02:52, 10.46it/s]
  7%|▋         | 135/1939 [00:12<02:53, 10.42it/s]
  7%|▋         | 137/1939 [00:13<03:18,  9.06it/s]
  7%|▋         | 138/1939 [00:13<03:48,  7.87it/s]
  7%|▋         | 139/1939 [00:13<04:19,  6.93it/s]
  7%|▋         | 141/1939 [00:13<04:19,  6.92it/s]
  7%|▋         | 142/1939 [00:14<04:44,  6.32it/s]
  7%|▋         | 144/1939 [00:14<04:28,  6.68it/s]
  7%|▋         | 145/1939 [00:14<04:51,  6.16it/s]
  8%|▊         | 146/1939 [00:14<05:16,  5.67it/s]
  8%|▊         | 148/1939 [00:15<03:50,  7.76it/s]
  8%|▊         | 149/1939 [00:15<04:14,  7.03it/s]
  8%|▊         | 151/1939 [00:15<03:58,  7.50it/s]
  8%|▊         | 153/1939 [00:15<03:55,  7.58it/s]
  8%|▊         | 155/1939 [00:15<03:10,  9.38it/s]
  8%|▊         | 157/1939 [00:16<03:11,  9.29it/s]
  8%|▊         | 159/1939 [00:16<04:05,  7.24it/s]
  8%|▊         | 160/1939 [00:16<04:25,  6.70it/s]
  8%|▊         | 161/1939 [00:16<04:46,  6.21it/s]
  8%|▊         | 162/1939 [00:17<05:12,  5.68it/s]
  8%|▊         | 163/1939 [00:17<05:26,  5.44it/s]
  8%|▊         | 164/1939 [00:17<05:50,  5.06it/s]
  9%|▊         | 165/1939 [00:17<06:12,  4.76it/s]
  9%|▊         | 168/1939 [00:17<03:27,  8.54it/s]
  9%|▉         | 170/1939 [00:18<03:25,  8.61it/s]
  9%|▉         | 172/1939 [00:18<02:50, 10.38it/s]
  9%|▉         | 179/1939 [00:18<01:48, 16.27it/s]
  9%|▉         | 182/1939 [00:18<02:01, 14.42it/s]
  9%|▉         | 184/1939 [00:18<02:03, 14.18it/s]
 10%|▉         | 186/1939 [00:19<02:17, 12.77it/s]
 10%|▉         | 188/1939 [00:19<02:05, 13.93it/s]
 10%|▉         | 190/1939 [00:19<01:58, 14.73it/s]
 10%|█         | 197/1939 [00:19<01:05, 26.52it/s]
 10%|█         | 201/1939 [00:19<01:27, 19.80it/s]
 11%|█         | 204/1939 [00:20<02:13, 13.04it/s]
 11%|█         | 207/1939 [00:20<02:44, 10.53it/s]
 11%|█         | 210/1939 [00:20<02:28, 11.62it/s]
 11%|█         | 212/1939 [00:21<02:39, 10.82it/s]
 11%|█         | 214/1939 [00:21<02:56,  9.75it/s]
 11%|█         | 216/1939 [00:21<03:04,  9.32it/s]
 11%|█         | 218/1939 [00:21<02:51, 10.02it/s]
 11%|█▏        | 220/1939 [00:21<02:52,  9.94it/s]
 11%|█▏        | 222/1939 [00:22<02:56,  9.73it/s]
 12%|█▏        | 224/1939 [00:22<03:35,  7.96it/s]
 12%|█▏        | 225/1939 [00:22<04:07,  6.94it/s]
 12%|█▏        | 227/1939 [00:22<03:23,  8.43it/s]
 12%|█▏        | 228/1939 [00:23<04:00,  7.12it/s]
 12%|█▏        | 230/1939 [00:23<03:37,  7.87it/s]
 12%|█▏        | 232/1939 [00:23<02:57,  9.60it/s]
 12%|█▏        | 234/1939 [00:23<03:41,  7.71it/s]
 12%|█▏        | 236/1939 [00:23<03:09,  8.97it/s]
 12%|█▏        | 238/1939 [00:24<03:20,  8.50it/s]
 12%|█▏        | 239/1939 [00:24<03:39,  7.74it/s]
 12%|█▏        | 240/1939 [00:24<03:56,  7.18it/s]
 12%|█▏        | 242/1939 [00:24<03:37,  7.82it/s]
 13%|█▎        | 244/1939 [00:24<03:09,  8.95it/s]
 13%|█▎        | 245/1939 [00:25<03:27,  8.16it/s]
 13%|█▎        | 246/1939 [00:25<03:56,  7.15it/s]
 13%|█▎        | 247/1939 [00:25<04:23,  6.42it/s]
 13%|█▎        | 248/1939 [00:25<05:13,  5.40it/s]
 13%|█▎        | 250/1939 [00:25<04:00,  7.03it/s]
 13%|█▎        | 251/1939 [00:26<03:54,  7.21it/s]
 13%|█▎        | 253/1939 [00:26<03:07,  9.01it/s]
 13%|█▎        | 255/1939 [00:26<02:36, 10.75it/s]
 13%|█▎        | 257/1939 [00:26<03:09,  8.89it/s]
 13%|█▎        | 259/1939 [00:26<03:17,  8.49it/s]
 13%|█▎        | 260/1939 [00:27<03:41,  7.60it/s]
 14%|█▎        | 262/1939 [00:27<03:02,  9.20it/s]
 14%|█▎        | 264/1939 [00:27<03:59,  7.01it/s]
 14%|█▍        | 267/1939 [00:27<02:47,  9.97it/s]
 14%|█▍        | 269/1939 [00:28<02:55,  9.50it/s]
 14%|█▍        | 271/1939 [00:28<03:06,  8.96it/s]
 14%|█▍        | 273/1939 [00:28<03:11,  8.71it/s]
 14%|█▍        | 274/1939 [00:28<03:34,  7.78it/s]
 14%|█▍        | 276/1939 [00:28<02:51,  9.68it/s]
 14%|█▍        | 279/1939 [00:29<02:32, 10.86it/s]
 14%|█▍        | 281/1939 [00:29<02:41, 10.28it/s]
 15%|█▍        | 283/1939 [00:29<02:20, 11.79it/s]
 15%|█▍        | 285/1939 [00:29<02:36, 10.56it/s]
 15%|█▍        | 287/1939 [00:29<03:08,  8.77it/s]
 15%|█▍        | 289/1939 [00:30<03:30,  7.84it/s]
 15%|█▌        | 293/1939 [00:30<02:51,  9.60it/s]
 15%|█▌        | 295/1939 [00:30<02:35, 10.58it/s]
 15%|█▌        | 297/1939 [00:30<02:42, 10.11it/s]
 15%|█▌        | 299/1939 [00:31<02:49,  9.65it/s]
 16%|█▌        | 301/1939 [00:31<03:16,  8.34it/s]
 16%|█▌        | 303/1939 [00:31<03:19,  8.21it/s]
 16%|█▌        | 304/1939 [00:31<03:44,  7.29it/s]
 16%|█▌        | 306/1939 [00:32<02:57,  9.18it/s]
 16%|█▌        | 308/1939 [00:32<02:57,  9.21it/s]
 16%|█▌        | 310/1939 [00:32<02:27, 11.03it/s]
 16%|█▌        | 312/1939 [00:32<02:33, 10.61it/s]
 16%|█▌        | 315/1939 [00:32<02:35, 10.43it/s]
 16%|█▋        | 317/1939 [00:33<03:29,  7.75it/s]
 16%|█▋        | 318/1939 [00:33<03:53,  6.94it/s]
 16%|█▋        | 319/1939 [00:33<04:10,  6.46it/s]
 17%|█▋        | 320/1939 [00:33<04:25,  6.10it/s]
 17%|█▋        | 321/1939 [00:34<04:45,  5.66it/s]
 17%|█▋        | 322/1939 [00:34<05:09,  5.22it/s]
 17%|█▋        | 324/1939 [00:34<04:37,  5.82it/s]
 17%|█▋        | 325/1939 [00:34<04:20,  6.20it/s]
 17%|█▋        | 326/1939 [00:34<04:17,  6.27it/s]
 17%|█▋        | 328/1939 [00:35<03:44,  7.18it/s]
 17%|█▋        | 329/1939 [00:35<03:46,  7.11it/s]
 17%|█▋        | 330/1939 [00:35<04:03,  6.60it/s]
 17%|█▋        | 331/1939 [00:35<04:04,  6.57it/s]
 17%|█▋        | 332/1939 [00:35<04:44,  5.64it/s]
 17%|█▋        | 334/1939 [00:36<04:35,  5.83it/s]
 17%|█▋        | 336/1939 [00:36<04:06,  6.51it/s]
 17%|█▋        | 337/1939 [00:36<04:03,  6.59it/s]
 17%|█▋        | 339/1939 [00:36<03:39,  7.28it/s]
 18%|█▊        | 340/1939 [00:37<04:14,  6.29it/s]
 18%|█▊        | 342/1939 [00:37<03:42,  7.17it/s]
 18%|█▊        | 343/1939 [00:37<04:10,  6.38it/s]
 18%|█▊        | 345/1939 [00:37<03:31,  7.53it/s]
 18%|█▊        | 347/1939 [00:37<03:12,  8.29it/s]
 18%|█▊        | 350/1939 [00:38<02:48,  9.44it/s]
 18%|█▊        | 351/1939 [00:38<03:27,  7.66it/s]
 18%|█▊        | 352/1939 [00:38<03:50,  6.88it/s]
 18%|█▊        | 354/1939 [00:38<03:50,  6.89it/s]
 18%|█▊        | 355/1939 [00:39<04:02,  6.53it/s]
 18%|█▊        | 356/1939 [00:39<04:05,  6.44it/s]
 18%|█▊        | 358/1939 [00:39<03:10,  8.31it/s]
 19%|█▊        | 360/1939 [00:39<03:02,  8.65it/s]
 19%|█▊        | 362/1939 [00:39<02:38,  9.95it/s]
 19%|█▉        | 364/1939 [00:40<02:53,  9.06it/s]
 19%|█▉        | 366/1939 [00:40<03:01,  8.67it/s]
 19%|█▉        | 367/1939 [00:40<03:31,  7.42it/s]
 19%|█▉        | 368/1939 [00:40<03:25,  7.66it/s]
 19%|█▉        | 370/1939 [00:40<03:49,  6.83it/s]
 19%|█▉        | 371/1939 [00:41<03:37,  7.22it/s]
 19%|█▉        | 372/1939 [00:41<03:57,  6.59it/s]
 19%|█▉        | 373/1939 [00:41<04:12,  6.20it/s]
 19%|█▉        | 375/1939 [00:41<03:43,  6.98it/s]
 19%|█▉        | 376/1939 [00:41<03:57,  6.58it/s]
 19%|█▉        | 377/1939 [00:42<04:19,  6.03it/s]
 19%|█▉        | 378/1939 [00:42<04:42,  5.53it/s]
 20%|█▉        | 381/1939 [00:42<03:37,  7.16it/s]
 20%|█▉        | 383/1939 [00:42<02:50,  9.10it/s]
 20%|█▉        | 385/1939 [00:43<03:29,  7.41it/s]
 20%|█▉        | 387/1939 [00:43<03:22,  7.68it/s]
 20%|██        | 388/1939 [00:43<03:53,  6.64it/s]
 20%|██        | 389/1939 [00:43<04:37,  5.59it/s]
 20%|██        | 390/1939 [00:44<04:49,  5.34it/s]
 20%|██        | 391/1939 [00:44<04:45,  5.42it/s]
 20%|██        | 392/1939 [00:44<04:38,  5.55it/s]
 20%|██        | 393/1939 [00:44<04:08,  6.22it/s]
 20%|██        | 395/1939 [00:44<03:28,  7.42it/s]
 20%|██        | 397/1939 [00:44<03:15,  7.91it/s]
 21%|██        | 399/1939 [00:45<03:19,  7.71it/s]
 21%|██        | 402/1939 [00:45<02:21, 10.89it/s]
 21%|██        | 404/1939 [00:45<02:17, 11.14it/s]
 21%|██        | 406/1939 [00:45<02:14, 11.38it/s]
 21%|██        | 408/1939 [00:45<02:21, 10.79it/s]
 21%|██        | 410/1939 [00:45<02:02, 12.50it/s]
 21%|██        | 412/1939 [00:46<02:35,  9.85it/s]
 21%|██▏       | 415/1939 [00:46<02:34,  9.88it/s]
 22%|██▏       | 417/1939 [00:46<03:12,  7.91it/s]
 22%|██▏       | 419/1939 [00:47<03:08,  8.08it/s]
 22%|██▏       | 421/1939 [00:47<02:38,  9.60it/s]
 22%|██▏       | 423/1939 [00:47<02:44,  9.24it/s]
 22%|██▏       | 425/1939 [00:47<02:22, 10.62it/s]
 22%|██▏       | 427/1939 [00:47<02:30, 10.04it/s]
 22%|██▏       | 429/1939 [00:48<02:28, 10.17it/s]
 22%|██▏       | 431/1939 [00:48<02:17, 10.97it/s]
 22%|██▏       | 433/1939 [00:48<02:06, 11.91it/s]
 22%|██▏       | 435/1939 [00:48<02:35,  9.65it/s]
 23%|██▎       | 437/1939 [00:48<02:47,  8.97it/s]
 23%|██▎       | 439/1939 [00:49<02:26, 10.21it/s]
 23%|██▎       | 444/1939 [00:49<01:27, 17.10it/s]
 23%|██▎       | 447/1939 [00:49<01:16, 19.58it/s]
 23%|██▎       | 450/1939 [00:49<01:25, 17.43it/s]
 23%|██▎       | 453/1939 [00:49<01:35, 15.48it/s]
 23%|██▎       | 455/1939 [00:49<01:31, 16.30it/s]
 24%|██▎       | 457/1939 [00:50<01:50, 13.44it/s]
 24%|██▍       | 463/1939 [00:50<01:07, 21.81it/s]
 24%|██▍       | 466/1939 [00:50<01:23, 17.62it/s]
 24%|██▍       | 469/1939 [00:50<01:17, 19.08it/s]
 24%|██▍       | 473/1939 [00:50<01:18, 18.69it/s]
 25%|██▍       | 476/1939 [00:50<01:17, 18.84it/s]
 25%|██▍       | 479/1939 [00:51<01:15, 19.46it/s]
 25%|██▌       | 485/1939 [00:51<00:53, 27.20it/s]
 25%|██▌       | 489/1939 [00:51<01:06, 21.97it/s]
 25%|██▌       | 492/1939 [00:51<01:41, 14.32it/s]
 26%|██▌       | 495/1939 [00:52<01:55, 12.50it/s]
 26%|██▌       | 497/1939 [00:52<02:13, 10.80it/s]
 26%|██▌       | 500/1939 [00:52<02:07, 11.27it/s]
 26%|██▌       | 502/1939 [00:52<02:01, 11.86it/s]
 26%|██▌       | 505/1939 [00:53<02:02, 11.74it/s]
 26%|██▋       | 509/1939 [00:53<01:29, 15.91it/s]
 26%|██▋       | 512/1939 [00:53<01:38, 14.48it/s]
 27%|██▋       | 516/1939 [00:53<01:28, 16.15it/s]
 27%|██▋       | 518/1939 [00:53<01:37, 14.62it/s]
 27%|██▋       | 520/1939 [00:54<02:10, 10.89it/s]
 27%|██▋       | 522/1939 [00:54<02:18, 10.23it/s]
 27%|██▋       | 524/1939 [00:54<02:43,  8.64it/s]
 27%|██▋       | 526/1939 [00:55<03:14,  7.27it/s]
 27%|██▋       | 527/1939 [00:55<03:31,  6.68it/s]
 27%|██▋       | 529/1939 [00:55<03:14,  7.26it/s]
 27%|██▋       | 531/1939 [00:55<03:07,  7.50it/s]
 27%|██▋       | 533/1939 [00:56<02:54,  8.04it/s]
 28%|██▊       | 534/1939 [00:56<03:21,  6.96it/s]
 28%|██▊       | 536/1939 [00:56<03:08,  7.44it/s]
 28%|██▊       | 537/1939 [00:56<03:11,  7.33it/s]
 28%|██▊       | 538/1939 [00:56<03:29,  6.68it/s]
 28%|██▊       | 539/1939 [00:57<03:38,  6.42it/s]
 28%|██▊       | 541/1939 [00:57<02:46,  8.40it/s]
 28%|██▊       | 543/1939 [00:57<02:14, 10.37it/s]
 28%|██▊       | 546/1939 [00:57<01:45, 13.14it/s]
 28%|██▊       | 548/1939 [00:57<02:13, 10.42it/s]
 28%|██▊       | 550/1939 [00:57<01:57, 11.83it/s]
 28%|██▊       | 552/1939 [00:58<02:39,  8.70it/s]
 29%|██▊       | 555/1939 [00:58<02:01, 11.36it/s]
 29%|██▊       | 557/1939 [00:58<02:27,  9.35it/s]
 29%|██▉       | 560/1939 [00:58<01:51, 12.42it/s]
 29%|██▉       | 562/1939 [00:59<02:43,  8.41it/s]
 29%|██▉       | 564/1939 [00:59<02:25,  9.48it/s]
 29%|██▉       | 567/1939 [00:59<01:55, 11.87it/s]
 29%|██▉       | 569/1939 [00:59<01:53, 12.05it/s]
 29%|██▉       | 571/1939 [00:59<01:43, 13.16it/s]
 30%|██▉       | 573/1939 [01:00<02:03, 11.04it/s]
 30%|██▉       | 575/1939 [01:00<02:45,  8.26it/s]
 30%|██▉       | 577/1939 [01:00<02:39,  8.56it/s]
 30%|██▉       | 579/1939 [01:00<02:44,  8.26it/s]
 30%|██▉       | 580/1939 [01:01<03:23,  6.69it/s]
 30%|███       | 582/1939 [01:01<03:16,  6.90it/s]
 30%|███       | 584/1939 [01:01<02:46,  8.12it/s]
 30%|███       | 586/1939 [01:01<02:46,  8.15it/s]
 30%|███       | 589/1939 [01:02<02:36,  8.63it/s]
 30%|███       | 590/1939 [01:02<02:44,  8.22it/s]
 30%|███       | 591/1939 [01:02<03:00,  7.46it/s]
 31%|███       | 593/1939 [01:02<02:57,  7.60it/s]
 31%|███       | 595/1939 [01:03<02:47,  8.05it/s]
 31%|███       | 597/1939 [01:03<02:23,  9.33it/s]
 31%|███       | 598/1939 [01:03<02:56,  7.61it/s]
 31%|███       | 599/1939 [01:03<03:18,  6.76it/s]
 31%|███       | 600/1939 [01:03<03:48,  5.87it/s]
 31%|███       | 601/1939 [01:04<03:51,  5.77it/s]
 31%|███       | 603/1939 [01:04<03:33,  6.26it/s]
 31%|███       | 605/1939 [01:04<03:12,  6.94it/s]
 31%|███▏      | 607/1939 [01:04<03:11,  6.95it/s]
 31%|███▏      | 608/1939 [01:04<03:01,  7.34it/s]
 31%|███▏      | 610/1939 [01:05<02:32,  8.69it/s]
 32%|███▏      | 611/1939 [01:05<02:33,  8.63it/s]
 32%|███▏      | 612/1939 [01:05<02:34,  8.61it/s]
 32%|███▏      | 613/1939 [01:05<02:34,  8.56it/s]
 32%|███▏      | 614/1939 [01:05<02:51,  7.73it/s]
 32%|███▏      | 615/1939 [01:05<03:03,  7.23it/s]
 32%|███▏      | 616/1939 [01:05<02:55,  7.52it/s]
 32%|███▏      | 617/1939 [01:06<03:09,  6.98it/s]
 32%|███▏      | 619/1939 [01:06<02:37,  8.41it/s]
 32%|███▏      | 620/1939 [01:06<02:30,  8.74it/s]
 32%|███▏      | 621/1939 [01:06<02:33,  8.57it/s]
 32%|███▏      | 622/1939 [01:06<02:46,  7.90it/s]
 32%|███▏      | 624/1939 [01:06<02:10, 10.09it/s]
 32%|███▏      | 626/1939 [01:06<01:49, 12.01it/s]
 32%|███▏      | 629/1939 [01:07<01:43, 12.61it/s]
 33%|███▎      | 631/1939 [01:07<02:01, 10.74it/s]
 33%|███▎      | 633/1939 [01:07<02:15,  9.62it/s]
 33%|███▎      | 636/1939 [01:07<02:10, 10.02it/s]
 33%|███▎      | 638/1939 [01:08<02:20,  9.29it/s]
 33%|███▎      | 641/1939 [01:08<02:14,  9.66it/s]
 33%|███▎      | 643/1939 [01:08<01:59, 10.87it/s]
 33%|███▎      | 646/1939 [01:08<01:51, 11.56it/s]
 33%|███▎      | 648/1939 [01:08<01:41, 12.72it/s]
 34%|███▎      | 650/1939 [01:09<02:03, 10.46it/s]
 34%|███▎      | 652/1939 [01:09<02:33,  8.39it/s]
 34%|███▎      | 654/1939 [01:09<02:27,  8.68it/s]
 34%|███▍      | 656/1939 [01:09<02:29,  8.58it/s]
 34%|███▍      | 658/1939 [01:10<02:35,  8.23it/s]
 34%|███▍      | 660/1939 [01:10<02:10,  9.80it/s]
 34%|███▍      | 662/1939 [01:10<01:51, 11.43it/s]
 34%|███▍      | 665/1939 [01:10<01:51, 11.38it/s]
 34%|███▍      | 667/1939 [01:11<02:15,  9.36it/s]
 35%|███▍      | 669/1939 [01:11<02:18,  9.16it/s]
 35%|███▍      | 671/1939 [01:11<01:58, 10.72it/s]
 35%|███▍      | 673/1939 [01:11<02:33,  8.22it/s]
 35%|███▍      | 675/1939 [01:11<02:15,  9.31it/s]
 35%|███▍      | 677/1939 [01:12<02:28,  8.50it/s]
 35%|███▌      | 680/1939 [01:12<02:16,  9.23it/s]
 35%|███▌      | 683/1939 [01:12<02:10,  9.62it/s]
 35%|███▌      | 686/1939 [01:12<01:41, 12.41it/s]
 35%|███▌      | 688/1939 [01:13<02:16,  9.14it/s]
 36%|███▌      | 690/1939 [01:13<02:30,  8.30it/s]
 36%|███▌      | 692/1939 [01:13<02:35,  8.01it/s]
 36%|███▌      | 693/1939 [01:14<03:00,  6.91it/s]
 36%|███▌      | 695/1939 [01:14<02:23,  8.70it/s]
 36%|███▌      | 697/1939 [01:14<02:25,  8.53it/s]
 36%|███▌      | 699/1939 [01:14<02:29,  8.28it/s]
 36%|███▌      | 702/1939 [01:14<01:51, 11.11it/s]
 37%|███▋      | 708/1939 [01:15<01:19, 15.40it/s]
 37%|███▋      | 710/1939 [01:15<01:19, 15.47it/s]
 37%|███▋      | 712/1939 [01:15<01:17, 15.92it/s]
 37%|███▋      | 720/1939 [01:15<00:42, 28.40it/s]
 37%|███▋      | 724/1939 [01:15<00:39, 30.76it/s]
 38%|███▊      | 728/1939 [01:15<00:58, 20.61it/s]
 38%|███▊      | 731/1939 [01:16<01:21, 14.85it/s]
 38%|███▊      | 734/1939 [01:16<01:42, 11.74it/s]
 38%|███▊      | 736/1939 [01:16<01:53, 10.63it/s]
 38%|███▊      | 738/1939 [01:17<01:59, 10.02it/s]
 38%|███▊      | 740/1939 [01:17<02:08,  9.30it/s]
 38%|███▊      | 742/1939 [01:17<02:14,  8.87it/s]
 38%|███▊      | 744/1939 [01:17<01:59, 10.04it/s]
 38%|███▊      | 746/1939 [01:18<02:04,  9.60it/s]
 39%|███▊      | 748/1939 [01:18<02:14,  8.87it/s]
 39%|███▊      | 749/1939 [01:18<02:30,  7.91it/s]
 39%|███▊      | 751/1939 [01:18<02:24,  8.21it/s]
 39%|███▉      | 752/1939 [01:18<02:43,  7.27it/s]
 39%|███▉      | 754/1939 [01:19<02:38,  7.50it/s]
 39%|███▉      | 755/1939 [01:19<02:44,  7.19it/s]
 39%|███▉      | 756/1939 [01:19<02:38,  7.46it/s]
 39%|███▉      | 757/1939 [01:19<02:42,  7.27it/s]
 39%|███▉      | 759/1939 [01:19<02:04,  9.50it/s]
 39%|███▉      | 761/1939 [01:20<02:42,  7.27it/s]
 39%|███▉      | 763/1939 [01:20<02:42,  7.23it/s]
 39%|███▉      | 764/1939 [01:20<03:00,  6.53it/s]
 40%|███▉      | 766/1939 [01:20<02:47,  7.02it/s]
 40%|███▉      | 767/1939 [01:21<02:56,  6.64it/s]
 40%|███▉      | 768/1939 [01:21<03:05,  6.33it/s]
 40%|███▉      | 769/1939 [01:21<03:11,  6.10it/s]
 40%|███▉      | 770/1939 [01:21<03:23,  5.75it/s]
 40%|███▉      | 771/1939 [01:21<03:35,  5.41it/s]
 40%|███▉      | 772/1939 [01:22<03:44,  5.20it/s]
 40%|███▉      | 773/1939 [01:22<03:43,  5.22it/s]
 40%|███▉      | 774/1939 [01:22<03:47,  5.12it/s]
 40%|████      | 776/1939 [01:22<03:13,  6.00it/s]
 40%|████      | 777/1939 [01:22<03:25,  5.66it/s]
 40%|████      | 779/1939 [01:23<02:58,  6.49it/s]
 40%|████      | 780/1939 [01:23<03:13,  5.97it/s]
 40%|████      | 781/1939 [01:23<03:24,  5.67it/s]
 40%|████      | 783/1939 [01:23<02:24,  8.03it/s]
 40%|████      | 784/1939 [01:23<02:45,  6.97it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 308.86it/s]
 84%|████████▎ | 251/300 [10:35<29:35, 36.23s/it]

[[np.int64(0), False, 6], [np.int64(1), False, 9], [np.int64(2), False, 13], [np.int64(3), False, 8], [np.int64(4), False, 8], [np.int64(5), False, 11], [np.int64(6), False, 9], [np.int64(7), False, 11], [np.int64(10), False, 7], [np.int64(12), False, 9], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0120, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.1277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5094, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [10:35<23:10, 28.96s/it]

tensor(12.1419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1601, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 253/300 [10:35<17:38, 22.52s/it]

tensor(12.1700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8001, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [10:35<10:20, 13.78s/it]

tensor(12.2137, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0410, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1640, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1140, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0461, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0216, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [10:36<06:22,  8.89s/it]

tensor(12.2742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0452, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0927, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0437, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1056, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [10:36<04:02,  5.91s/it]

tensor(12.2587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0426, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1324, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [10:36<02:36,  4.02s/it]

tensor(12.2504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0419, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1703, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2154, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2369, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0405, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2432, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [10:36<01:42,  2.77s/it]

tensor(12.2269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0393, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2622, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2829, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [10:36<01:07,  1.94s/it]

tensor(12.2142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3109, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [10:36<00:45,  1.37s/it]

tensor(12.2097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3358, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3545, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1912, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3653, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [10:37<00:30,  1.02it/s]

tensor(12.1809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3874, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [10:37<00:20,  1.40it/s]

tensor(12.1638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3903, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [10:37<00:14,  1.90it/s]

tensor(12.1597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3979, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4069, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [10:37<00:09,  2.53it/s]

tensor(12.1487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1429, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4164, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [10:37<00:07,  3.28it/s]

tensor(12.1371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4177, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [10:38<00:05,  4.13it/s]

tensor(12.1315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4193, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4235, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [10:38<00:03,  5.05it/s]

tensor(12.1182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4307, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4367, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [10:38<00:02,  5.99it/s]

tensor(12.1077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4471, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [10:38<00:02,  6.88it/s]

tensor(12.1026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4588, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4681, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4809, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [10:38<00:01,  7.69it/s]

tensor(12.0928, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4896, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0904, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4932, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [10:39<00:01,  8.34it/s]

tensor(12.0878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4994, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [10:39<00:01,  8.91it/s]

tensor(12.0852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5014, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5043, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5091, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [10:39<00:00,  9.32it/s]

tensor(12.0781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5173, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [10:39<00:00,  9.64it/s]

tensor(12.0736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5232, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [10:39<00:00,  9.90it/s]

tensor(12.0713, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5268, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5298, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5303, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [10:40<00:00,  2.13s/it]

tensor(12.0657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5318, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.002125978469848633

PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 4
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.472254846676
NMI         : 0.590750606208
Runtime     : 660.14 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed4

==============================================================================================================
PRAGA RUN | S2-E15 | seed=5
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 1.054e-16
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:26, 11.15it/s]

tensor(17.8552, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3721, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.8616, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.8273, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.2991, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:26, 11.14it/s]

tensor(17.7781, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5573, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.7298, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9865, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6831, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5685, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:23, 12.57it/s]

tensor(17.6344, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2910, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5891, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1391, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5436, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1002, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.82it/s]

tensor(17.4978, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1638, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4510, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4033, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5582, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:21, 13.16it/s]

tensor(17.3567, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8716, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3089, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2536, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2609, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6958, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.19it/s]

tensor(17.2112, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1941, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1577, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7414, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1028, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3343, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:01<00:21, 13.24it/s]

tensor(17.0430, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9671, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9784, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6367, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9083, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3396, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:20, 13.25it/s]

tensor(16.8339, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0717, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7554, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6742, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6147, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:20, 13.27it/s]

tensor(16.5895, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5028, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2461, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4124, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0893, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.32it/s]

tensor(16.3187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9484, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2208, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8224, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7101, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:02<00:20, 13.35it/s]

tensor(16.0097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6088, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8952, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5194, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4390, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:19, 13.32it/s]

tensor(15.6569, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3684, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5427, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3051, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2499, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:02<00:19, 13.30it/s]

tensor(15.3271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2013, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1595, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1244, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.30it/s]

tensor(15.0227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0954, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0729, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0554, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:03<00:19, 13.25it/s]

tensor(14.7241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0435, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0360, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:19, 13.19it/s]

tensor(14.4666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3094, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:03<00:18, 13.23it/s]

tensor(14.2338, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:03<00:18, 13.25it/s]

tensor(14.0471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9588, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:04<00:18, 13.27it/s]

tensor(13.9163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8741, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:18, 13.23it/s]

tensor(13.7923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7509, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0185, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:04<00:18, 13.18it/s]

tensor(13.6693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0185, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.22it/s]

tensor(13.5650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:05<00:17, 13.22it/s]

tensor(13.4773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.20it/s]

tensor(13.3942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:05<00:17, 13.26it/s]

tensor(13.3138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:16, 13.22it/s]

tensor(13.2424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1999, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:06<00:16, 13.21it/s]

tensor(13.1795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1399, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.22it/s]

tensor(13.1207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:06<00:16, 13.24it/s]

tensor(13.0650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:16, 13.16it/s]

tensor(13.0131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:06<00:15, 13.34it/s]

tensor(12.9649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.26it/s]

tensor(12.9183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9028, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:07<00:15, 13.21it/s]

tensor(12.8726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8577, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8429, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:15, 13.22it/s]

tensor(12.8285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([194, 165,  69,  39,  34, 112,  73, 106, 355,  80, 379, 184,  56,  93])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 4/1939 [00:00<00:54, 35.53it/s]
  1%|          | 11/1939 [00:00<00:44, 43.46it/s]
  1%|          | 16/1939 [00:00<00:41, 45.97it/s]
  1%|          | 22/1939 [00:00<00:38, 50.15it/s]
  1%|▏         | 29/1939 [00:00<00:33, 56.72it/s]
  2%|▏         | 35/1939 [00:00<00:34, 54.98it/s]
  2%|▏         | 41/1939 [00:00<00:52, 36.05it/s]
  2%|▏         | 46/1939 [00:01<01:04, 29.37it/s]
  3%|▎         | 50/1939 [00:01<01:18, 23.96it/s]
  3%|▎         | 53/1939 [00:01<01:41, 18.56it/s]
  3%|▎         | 56/1939 [00:02<02:04, 15.17it/s]
  3%|▎         | 58/1939 [00:02<02:28, 12.65it/s]
  3%|▎         | 60/1939 [00:02<02:48, 11.14it/s]
  3%|▎         | 64/1939 [00:02<02:05, 14.97it/s]
  3%|▎         | 67/1939 [00:03<02:18, 13.53it/s]
  4%|▎         | 69/1939 [00:03<02:16, 13.65it/s]
  4%|▎         | 71/1939 [00:03<02:53, 10.79it/s]
  4%|▍         | 73/1939 [00:03<03:00, 10.35it/s]
  4%|▍         | 75/1939 [00:03<02:48, 11.07it/s]
  4%|▍         | 78/1939 [00:04<02:58, 10.44it/s]
  4%|▍         | 80/1939 [00:04<03:41,  8.40it/s]
  4%|▍         | 81/1939 [00:04<03:56,  7.85it/s]
  4%|▍         | 82/1939 [00:04<04:16,  7.24it/s]
  4%|▍         | 84/1939 [00:05<04:12,  7.36it/s]
  4%|▍         | 86/1939 [00:05<03:39,  8.46it/s]
  5%|▍         | 88/1939 [00:05<03:20,  9.22it/s]
  5%|▍         | 91/1939 [00:05<02:33, 12.02it/s]
  5%|▍         | 93/1939 [00:05<02:48, 10.95it/s]
  5%|▍         | 95/1939 [00:06<02:56, 10.43it/s]
  5%|▌         | 97/1939 [00:06<02:54, 10.55it/s]
  5%|▌         | 99/1939 [00:06<02:33, 11.99it/s]
  5%|▌         | 101/1939 [00:06<03:52,  7.92it/s]
  5%|▌         | 104/1939 [00:06<02:51, 10.71it/s]
  5%|▌         | 106/1939 [00:07<02:38, 11.59it/s]
  6%|▌         | 108/1939 [00:07<03:00, 10.13it/s]
  6%|▌         | 110/1939 [00:07<03:07,  9.74it/s]
  6%|▌         | 112/1939 [00:07<02:43, 11.16it/s]
  6%|▌         | 114/1939 [00:07<03:04,  9.91it/s]
  6%|▌         | 116/1939 [00:08<03:20,  9.09it/s]
  6%|▌         | 118/1939 [00:08<04:09,  7.29it/s]
  6%|▌         | 120/1939 [00:08<03:35,  8.42it/s]
  6%|▋         | 122/1939 [00:08<03:03,  9.92it/s]
  6%|▋         | 124/1939 [00:09<02:42, 11.18it/s]
  7%|▋         | 128/1939 [00:09<02:00, 15.02it/s]
  7%|▋         | 130/1939 [00:09<01:56, 15.51it/s]
  7%|▋         | 132/1939 [00:09<02:35, 11.64it/s]
  7%|▋         | 135/1939 [00:09<02:48, 10.70it/s]
  7%|▋         | 137/1939 [00:10<03:12,  9.34it/s]
  7%|▋         | 139/1939 [00:10<03:21,  8.92it/s]
  7%|▋         | 141/1939 [00:10<03:30,  8.54it/s]
  7%|▋         | 142/1939 [00:10<03:46,  7.95it/s]
  7%|▋         | 144/1939 [00:11<03:16,  9.16it/s]
  7%|▋         | 145/1939 [00:11<04:04,  7.34it/s]
  8%|▊         | 146/1939 [00:11<04:33,  6.57it/s]
  8%|▊         | 148/1939 [00:11<03:39,  8.15it/s]
  8%|▊         | 149/1939 [00:11<04:01,  7.42it/s]
  8%|▊         | 151/1939 [00:12<03:43,  8.01it/s]
  8%|▊         | 153/1939 [00:12<03:24,  8.73it/s]
  8%|▊         | 155/1939 [00:12<02:58,  9.98it/s]
  8%|▊         | 157/1939 [00:12<03:05,  9.59it/s]
  8%|▊         | 159/1939 [00:13<04:01,  7.38it/s]
  8%|▊         | 160/1939 [00:13<04:20,  6.83it/s]
 33%|███▎      | 100/300 [00:23<00:15, 13.22it/s]]
  8%|▊         | 162/1939 [00:13<04:44,  6.25it/s]
  8%|▊         | 163/1939 [00:13<04:29,  6.58it/s]
  9%|▊         | 165/1939 [00:13<03:38,  8.10it/s]
  9%|▊         | 167/1939 [00:13<02:54, 10.15it/s]
  9%|▊         | 169/1939 [00:14<02:25, 12.19it/s]
  9%|▉         | 171/1939 [00:14<02:11, 13.49it/s]
  9%|▉         | 177/1939 [00:14<01:11, 24.59it/s]
  9%|▉         | 184/1939 [00:14<00:49, 35.13it/s]
 10%|▉         | 188/1939 [00:14<00:55, 31.46it/s]
 10%|▉         | 192/1939 [00:14<00:59, 29.12it/s]
 10%|█         | 198/1939 [00:14<00:49, 35.50it/s]
 10%|█         | 202/1939 [00:15<01:42, 16.90it/s]
 11%|█         | 205/1939 [00:15<02:21, 12.23it/s]
 11%|█         | 208/1939 [00:16<02:30, 11.52it/s]
 11%|█         | 211/1939 [00:16<02:28, 11.61it/s]
 11%|█         | 213/1939 [00:16<02:47, 10.32it/s]
 11%|█         | 215/1939 [00:17<03:06,  9.23it/s]
 11%|█         | 217/1939 [00:17<02:47, 10.30it/s]
 11%|█▏        | 219/1939 [00:17<02:59,  9.60it/s]
 11%|█▏        | 221/1939 [00:17<03:01,  9.48it/s]
 12%|█▏        | 223/1939 [00:17<03:18,  8.65it/s]
 12%|█▏        | 224/1939 [00:18<03:44,  7.65it/s]
 12%|█▏        | 225/1939 [00:18<04:06,  6.97it/s]
 12%|█▏        | 227/1939 [00:18<03:15,  8.77it/s]
 12%|█▏        | 229/1939 [00:18<04:13,  6.76it/s]
 12%|█▏        | 230/1939 [00:19<04:30,  6.31it/s]
 12%|█▏        | 233/1939 [00:19<03:42,  7.67it/s]
 12%|█▏        | 234/1939 [00:19<04:11,  6.78it/s]
 12%|█▏        | 236/1939 [00:19<04:00,  7.09it/s]
 12%|█▏        | 237/1939 [00:20<04:23,  6.46it/s]
 12%|█▏        | 239/1939 [00:20<03:54,  7.25it/s]
 12%|█▏        | 240/1939 [00:20<04:25,  6.41it/s]
 12%|█▏        | 241/1939 [00:20<04:53,  5.79it/s]
 12%|█▏        | 242/1939 [00:20<05:13,  5.42it/s]
 13%|█▎        | 243/1939 [00:21<05:24,  5.23it/s]
 13%|█▎        | 244/1939 [00:21<05:48,  4.87it/s]
 13%|█▎        | 245/1939 [00:21<05:54,  4.78it/s]
 13%|█▎        | 246/1939 [00:21<05:54,  4.78it/s]
 13%|█▎        | 248/1939 [00:22<05:03,  5.57it/s]
 13%|█▎        | 250/1939 [00:22<04:44,  5.94it/s]
 13%|█▎        | 251/1939 [00:22<05:04,  5.54it/s]
 13%|█▎        | 254/1939 [00:22<03:11,  8.82it/s]
 13%|█▎        | 257/1939 [00:23<02:48,  9.96it/s]
 13%|█▎        | 259/1939 [00:23<02:44, 10.22it/s]
 13%|█▎        | 261/1939 [00:23<03:11,  8.74it/s]
 14%|█▎        | 263/1939 [00:23<03:13,  8.65it/s]
 14%|█▎        | 264/1939 [00:23<03:38,  7.65it/s]
 14%|█▎        | 266/1939 [00:24<03:06,  8.98it/s]
 14%|█▍        | 268/1939 [00:24<03:30,  7.92it/s]
 14%|█▍        | 270/1939 [00:24<03:37,  7.69it/s]
 14%|█▍        | 272/1939 [00:24<02:58,  9.35it/s]
 14%|█▍        | 274/1939 [00:25<03:39,  7.58it/s]
 14%|█▍        | 277/1939 [00:25<02:35, 10.68it/s]
 14%|█▍        | 281/1939 [00:25<02:02, 13.53it/s]
 15%|█▍        | 283/1939 [00:25<01:53, 14.59it/s]
 15%|█▍        | 285/1939 [00:25<02:28, 11.14it/s]
 15%|█▍        | 287/1939 [00:26<02:52,  9.55it/s]
 15%|█▍        | 289/1939 [00:26<02:46,  9.94it/s]
 15%|█▌        | 292/1939 [00:26<02:11, 12.54it/s]
 15%|█▌        | 294/1939 [00:26<02:20, 11.74it/s]
 15%|█▌        | 296/1939 [00:26<02:34, 10.60it/s]
 15%|█▌        | 298/1939 [00:27<02:46,  9.87it/s]
 15%|█▌        | 300/1939 [00:27<03:12,  8.54it/s]
 16%|█▌        | 303/1939 [00:27<02:57,  9.24it/s]
 16%|█▌        | 304/1939 [00:27<03:22,  8.08it/s]
 16%|█▌        | 307/1939 [00:28<03:04,  8.86it/s]
 16%|█▌        | 308/1939 [00:28<03:24,  7.99it/s]
 16%|█▌        | 310/1939 [00:28<03:02,  8.92it/s]
 16%|█▌        | 312/1939 [00:28<03:17,  8.25it/s]
 16%|█▌        | 314/1939 [00:29<02:49,  9.58it/s]
 16%|█▋        | 316/1939 [00:29<03:21,  8.05it/s]
 16%|█▋        | 317/1939 [00:29<03:36,  7.48it/s]
 16%|█▋        | 318/1939 [00:29<03:50,  7.04it/s]
 16%|█▋        | 319/1939 [00:29<04:03,  6.65it/s]
 17%|█▋        | 320/1939 [00:30<04:41,  5.76it/s]
 17%|█▋        | 321/1939 [00:30<04:43,  5.71it/s]
 17%|█▋        | 322/1939 [00:30<04:35,  5.86it/s]
 17%|█▋        | 324/1939 [00:30<03:26,  7.84it/s]
 17%|█▋        | 327/1939 [00:30<02:57,  9.11it/s]
 17%|█▋        | 331/1939 [00:31<01:54, 14.09it/s]
 17%|█▋        | 338/1939 [00:31<01:04, 24.84it/s]
 18%|█▊        | 344/1939 [00:31<00:49, 32.09it/s]
 18%|█▊        | 351/1939 [00:31<00:54, 29.39it/s]
 18%|█▊        | 355/1939 [00:32<01:36, 16.41it/s]
 18%|█▊        | 358/1939 [00:32<01:35, 16.48it/s]
 19%|█▊        | 361/1939 [00:32<01:38, 15.94it/s]
 19%|█▉        | 364/1939 [00:32<01:50, 14.21it/s]
 19%|█▉        | 366/1939 [00:32<01:54, 13.73it/s]
 19%|█▉        | 368/1939 [00:33<01:59, 13.11it/s]
 19%|█▉        | 370/1939 [00:33<02:21, 11.07it/s]
 19%|█▉        | 372/1939 [00:33<02:19, 11.23it/s]
 19%|█▉        | 374/1939 [00:33<02:13, 11.75it/s]
 19%|█▉        | 376/1939 [00:33<02:11, 11.89it/s]
 19%|█▉        | 378/1939 [00:34<02:32, 10.22it/s]
 20%|█▉        | 381/1939 [00:34<02:30, 10.33it/s]
 20%|█▉        | 383/1939 [00:34<02:19, 11.15it/s]
 20%|█▉        | 385/1939 [00:34<03:00,  8.59it/s]
 20%|█▉        | 387/1939 [00:35<03:16,  7.92it/s]
 20%|██        | 388/1939 [00:35<03:47,  6.83it/s]
 20%|██        | 389/1939 [00:35<04:01,  6.41it/s]
 20%|██        | 390/1939 [00:35<04:16,  6.03it/s]
 20%|██        | 391/1939 [00:36<04:25,  5.83it/s]
 20%|██        | 392/1939 [00:36<04:38,  5.56it/s]
 20%|██        | 393/1939 [00:36<04:40,  5.50it/s]
 20%|██        | 394/1939 [00:36<04:56,  5.22it/s]
 20%|██        | 396/1939 [00:36<04:09,  6.18it/s]
 20%|██        | 397/1939 [00:37<04:21,  5.90it/s]
 21%|██        | 398/1939 [00:37<04:27,  5.76it/s]
 21%|██        | 400/1939 [00:37<03:29,  7.34it/s]
 21%|██        | 403/1939 [00:37<02:18, 11.07it/s]
 21%|██        | 405/1939 [00:37<02:29, 10.25it/s]
 21%|██        | 407/1939 [00:37<02:35,  9.88it/s]
 21%|██        | 409/1939 [00:38<02:20, 10.89it/s]
 21%|██        | 411/1939 [00:38<02:10, 11.74it/s]
 21%|██▏       | 413/1939 [00:38<02:40,  9.49it/s]
 21%|██▏       | 415/1939 [00:38<02:35,  9.81it/s]
 22%|██▏       | 417/1939 [00:39<03:22,  7.51it/s]
 22%|██▏       | 419/1939 [00:39<03:07,  8.10it/s]
 22%|██▏       | 421/1939 [00:39<02:36,  9.72it/s]
 22%|██▏       | 423/1939 [00:39<02:40,  9.45it/s]
 22%|██▏       | 425/1939 [00:39<02:21, 10.68it/s]
 22%|██▏       | 427/1939 [00:40<02:23, 10.56it/s]
 22%|██▏       | 429/1939 [00:40<02:34,  9.78it/s]
 22%|██▏       | 431/1939 [00:40<02:19, 10.82it/s]
 22%|██▏       | 434/1939 [00:40<01:46, 14.14it/s]
 23%|██▎       | 441/1939 [00:40<00:58, 25.49it/s]
 23%|██▎       | 447/1939 [00:40<00:46, 32.39it/s]
 23%|██▎       | 452/1939 [00:40<00:40, 36.43it/s]
 24%|██▎       | 457/1939 [00:40<00:37, 39.80it/s]
 24%|██▍       | 463/1939 [00:41<00:33, 44.51it/s]
 24%|██▍       | 468/1939 [00:41<00:33, 43.93it/s]
 24%|██▍       | 475/1939 [00:41<00:30, 48.12it/s]
 25%|██▍       | 480/1939 [00:41<00:42, 34.46it/s]
 25%|██▌       | 485/1939 [00:41<00:50, 28.94it/s]
 25%|██▌       | 489/1939 [00:42<00:58, 24.92it/s]
 25%|██▌       | 492/1939 [00:42<01:28, 16.35it/s]
 26%|██▌       | 495/1939 [00:42<01:26, 16.68it/s]
 26%|██▌       | 498/1939 [00:42<01:41, 14.17it/s]
 26%|██▌       | 500/1939 [00:43<02:03, 11.64it/s]
 26%|██▌       | 503/1939 [00:43<01:42, 13.99it/s]
 26%|██▌       | 505/1939 [00:43<02:01, 11.80it/s]
 26%|██▌       | 508/1939 [00:43<01:40, 14.19it/s]
 26%|██▋       | 512/1939 [00:43<01:20, 17.69it/s]
 27%|██▋       | 515/1939 [00:43<01:13, 19.50it/s]
 27%|██▋       | 520/1939 [00:44<00:58, 24.07it/s]
 27%|██▋       | 526/1939 [00:44<00:45, 30.90it/s]
 27%|██▋       | 530/1939 [00:44<00:45, 31.13it/s]
 28%|██▊       | 537/1939 [00:44<00:42, 32.67it/s]
 28%|██▊       | 541/1939 [00:44<01:00, 22.98it/s]
 28%|██▊       | 544/1939 [00:44<00:58, 23.80it/s]
 28%|██▊       | 547/1939 [00:45<01:12, 19.33it/s]
 28%|██▊       | 550/1939 [00:45<01:23, 16.60it/s]
 28%|██▊       | 552/1939 [00:45<02:07, 10.87it/s]
 29%|██▊       | 554/1939 [00:46<01:55, 12.02it/s]
 29%|██▊       | 556/1939 [00:46<01:47, 12.88it/s]
 29%|██▉       | 558/1939 [00:46<01:53, 12.14it/s]
 29%|██▉       | 561/1939 [00:46<02:01, 11.33it/s]
 29%|██▉       | 563/1939 [00:46<02:11, 10.49it/s]
 29%|██▉       | 567/1939 [00:47<01:57, 11.72it/s]
 29%|██▉       | 569/1939 [00:47<02:10, 10.49it/s]
 29%|██▉       | 571/1939 [00:47<02:17,  9.95it/s]
 30%|██▉       | 573/1939 [00:47<02:33,  8.88it/s]
 30%|██▉       | 574/1939 [00:48<02:48,  8.10it/s]
 30%|██▉       | 575/1939 [00:48<03:00,  7.54it/s]
 30%|██▉       | 576/1939 [00:48<03:22,  6.73it/s]
 30%|██▉       | 578/1939 [00:48<02:34,  8.83it/s]
 30%|██▉       | 580/1939 [00:49<03:09,  7.18it/s]
 30%|███       | 582/1939 [00:49<03:05,  7.30it/s]
 30%|███       | 584/1939 [00:49<03:05,  7.31it/s]
 30%|███       | 586/1939 [00:49<03:03,  7.36it/s]
 30%|███       | 589/1939 [00:50<02:40,  8.40it/s]
 30%|███       | 590/1939 [00:50<02:57,  7.58it/s]
 30%|███       | 591/1939 [00:50<03:00,  7.46it/s]
 31%|███       | 592/1939 [00:50<03:12,  7.01it/s]
 31%|███       | 593/1939 [00:50<03:02,  7.39it/s]
 31%|███       | 595/1939 [00:51<03:10,  7.06it/s]
 31%|███       | 596/1939 [00:51<03:10,  7.03it/s]
 31%|███       | 598/1939 [00:51<02:59,  7.47it/s]
 31%|███       | 599/1939 [00:51<03:20,  6.68it/s]
 31%|███       | 600/1939 [00:51<03:34,  6.23it/s]
 31%|███       | 601/1939 [00:51<03:38,  6.11it/s]
 31%|███       | 603/1939 [00:52<02:44,  8.10it/s]
 31%|███       | 605/1939 [00:52<02:47,  7.97it/s]
 31%|███▏      | 607/1939 [00:52<02:45,  8.06it/s]
 31%|███▏      | 608/1939 [00:52<02:57,  7.48it/s]
 31%|███▏      | 609/1939 [00:53<03:22,  6.56it/s]
 32%|███▏      | 611/1939 [00:53<03:21,  6.60it/s]
 32%|███▏      | 612/1939 [00:53<03:49,  5.78it/s]
 32%|███▏      | 613/1939 [00:53<04:12,  5.25it/s]
 32%|███▏      | 614/1939 [00:53<03:47,  5.84it/s]
 32%|███▏      | 616/1939 [00:54<03:05,  7.12it/s]
 32%|███▏      | 618/1939 [00:54<03:00,  7.34it/s]
 32%|███▏      | 619/1939 [00:54<03:18,  6.64it/s]
 32%|███▏      | 621/1939 [00:54<03:14,  6.78it/s]
 32%|███▏      | 622/1939 [00:55<03:30,  6.25it/s]
 32%|███▏      | 624/1939 [00:55<02:37,  8.35it/s]
 32%|███▏      | 626/1939 [00:55<02:07, 10.30it/s]
 32%|███▏      | 629/1939 [00:55<02:00, 10.88it/s]
 33%|███▎      | 631/1939 [00:55<02:19,  9.35it/s]
 33%|███▎      | 633/1939 [00:56<02:16,  9.54it/s]
 33%|███▎      | 635/1939 [00:56<01:56, 11.18it/s]
 33%|███▎      | 637/1939 [00:56<02:17,  9.49it/s]
 33%|███▎      | 639/1939 [00:56<02:00, 10.83it/s]
 33%|███▎      | 641/1939 [00:56<02:39,  8.16it/s]
 33%|███▎      | 643/1939 [00:57<02:51,  7.54it/s]
 33%|███▎      | 646/1939 [00:57<02:34,  8.36it/s]
 33%|███▎      | 649/1939 [00:57<02:24,  8.94it/s]
 34%|███▎      | 651/1939 [00:58<02:37,  8.18it/s]
 34%|███▎      | 652/1939 [00:58<02:51,  7.51it/s]
 34%|███▎      | 654/1939 [00:58<02:42,  7.89it/s]
 34%|███▍      | 656/1939 [00:58<02:40,  8.01it/s]
 34%|███▍      | 658/1939 [00:59<02:49,  7.54it/s]
 34%|███▍      | 659/1939 [00:59<03:07,  6.84it/s]
 34%|███▍      | 661/1939 [00:59<02:33,  8.35it/s]
 34%|███▍      | 665/1939 [00:59<01:53, 11.18it/s]
 34%|███▍      | 667/1939 [00:59<01:59, 10.68it/s]
 35%|███▍      | 669/1939 [01:00<02:11,  9.69it/s]
 35%|███▍      | 672/1939 [01:00<02:04, 10.18it/s]
 35%|███▍      | 674/1939 [01:00<02:18,  9.12it/s]
 35%|███▍      | 676/1939 [01:00<02:19,  9.07it/s]
 35%|███▍      | 677/1939 [01:01<02:36,  8.08it/s]
 35%|███▍      | 678/1939 [01:01<02:56,  7.16it/s]
 35%|███▌      | 680/1939 [01:01<02:47,  7.51it/s]
 35%|███▌      | 683/1939 [01:01<02:21,  8.85it/s]
 35%|███▌      | 685/1939 [01:01<02:02, 10.21it/s]
 35%|███▌      | 687/1939 [01:02<02:01, 10.27it/s]
 36%|███▌      | 689/1939 [01:02<02:14,  9.30it/s]
 36%|███▌      | 691/1939 [01:02<01:57, 10.66it/s]
 36%|███▌      | 693/1939 [01:02<02:42,  7.65it/s]
 36%|███▌      | 697/1939 [01:03<01:44, 11.89it/s]
 36%|███▋      | 703/1939 [01:03<01:04, 19.06it/s]
 37%|███▋      | 708/1939 [01:03<00:50, 24.43it/s]
 37%|███▋      | 715/1939 [01:03<00:38, 31.49it/s]
 37%|███▋      | 720/1939 [01:03<00:35, 33.95it/s]
 37%|███▋      | 725/1939 [01:03<00:44, 27.50it/s]
 38%|███▊      | 729/1939 [01:03<00:43, 27.57it/s]
 38%|███▊      | 733/1939 [01:04<01:26, 14.02it/s]
 38%|███▊      | 736/1939 [01:04<01:32, 12.95it/s]
 38%|███▊      | 739/1939 [01:05<01:36, 12.49it/s]
 38%|███▊      | 741/1939 [01:05<01:32, 12.94it/s]
 38%|███▊      | 743/1939 [01:05<01:46, 11.21it/s]
 38%|███▊      | 745/1939 [01:05<01:57, 10.16it/s]
 39%|███▊      | 747/1939 [01:06<02:06,  9.41it/s]
 39%|███▊      | 749/1939 [01:06<02:11,  9.08it/s]
 39%|███▊      | 751/1939 [01:06<02:17,  8.63it/s]
 39%|███▉      | 752/1939 [01:06<02:36,  7.60it/s]
 39%|███▉      | 754/1939 [01:06<02:07,  9.32it/s]
 39%|███▉      | 756/1939 [01:07<02:13,  8.89it/s]
 39%|███▉      | 758/1939 [01:07<02:24,  8.15it/s]
 39%|███▉      | 760/1939 [01:07<02:30,  7.82it/s]
 39%|███▉      | 763/1939 [01:08<02:17,  8.54it/s]
 39%|███▉      | 765/1939 [01:08<01:59,  9.82it/s]
 40%|███▉      | 767/1939 [01:08<02:34,  7.60it/s]
 40%|███▉      | 768/1939 [01:08<02:52,  6.81it/s]
 40%|███▉      | 769/1939 [01:09<03:02,  6.40it/s]
 40%|███▉      | 770/1939 [01:09<03:13,  6.05it/s]
 40%|███▉      | 771/1939 [01:09<03:17,  5.91it/s]
 40%|███▉      | 772/1939 [01:09<03:34,  5.45it/s]
 40%|███▉      | 773/1939 [01:09<03:34,  5.44it/s]
 40%|███▉      | 775/1939 [01:09<02:28,  7.84it/s]
 40%|████      | 776/1939 [01:10<02:56,  6.58it/s]
 40%|████      | 777/1939 [01:10<02:52,  6.74it/s]
 40%|████      | 779/1939 [01:10<02:27,  7.87it/s]
 40%|████      | 780/1939 [01:10<02:46,  6.98it/s]
 40%|████      | 781/1939 [01:10<03:14,  5.95it/s]
 40%|████      | 784/1939 [01:11<02:33,  7.55it/s]
 40%|████      | 785/1939 [01:11<02:52,  6.67it/s]
 41%|████      | 787/1939 [01:11<02:41,  7.14it/s]
 41%|████      | 789/1939 [01:12<02:47,  6.86it/s]
 41%|████      | 791/1939 [01:12<02:40,  7.17it/s]
 41%|████      | 793/1939 [01:12<02:09,  8.84it/s]
 41%|████      | 795/1939 [01:12<02:36,  7.32it/s]
 41%|████      | 796/1939 [01:12<02:45,  6.91it/s]
 41%|████      | 797/1939 [01:13<02:55,  6.49it/s]
 41%|████      | 798/1939 [01:13<03:06,  6.11it/s]
 41%|████▏     | 800/1939 [01:13<02:53,  6.55it/s]
 41%|████▏     | 801/1939 [01:13<03:16,  5.79it/s]
 41%|████▏     | 804/1939 [01:14<02:29,  7.58it/s]
 42%|████▏     | 805/1939 [01:14<02:26,  7.72it/s]
 42%|████▏     | 806/1939 [01:14<02:26,  7.73it/s]
 42%|████▏     | 808/1939 [01:14<02:07,  8.84it/s]
 42%|████▏     | 809/1939 [01:14<02:15,  8.32it/s]
 42%|████▏     | 811/1939 [01:14<01:57,  9.64it/s]
 42%|████▏     | 812/1939 [01:14<02:08,  8.79it/s]
 42%|████▏     | 813/1939 [01:15<02:17,  8.21it/s]
 42%|████▏     | 814/1939 [01:15<02:37,  7.16it/s]
 42%|████▏     | 816/1939 [01:15<02:27,  7.61it/s]
 42%|████▏     | 817/1939 [01:15<02:50,  6.57it/s]
 42%|████▏     | 818/1939 [01:15<03:05,  6.04it/s]
 42%|████▏     | 819/1939 [01:16<03:09,  5.90it/s]
 42%|████▏     | 820/1939 [01:16<03:11,  5.85it/s]
 42%|████▏     | 821/1939 [01:16<03:06,  6.00it/s]
 42%|████▏     | 822/1939 [01:16<03:01,  6.14it/s]
 42%|████▏     | 823/1939 [01:16<02:54,  6.39it/s]
 43%|████▎     | 825/1939 [01:17<02:37,  7.06it/s]
 43%|████▎     | 826/1939 [01:17<02:47,  6.65it/s]
 43%|████▎     | 828/1939 [01:17<02:41,  6.90it/s]
 43%|████▎     | 829/1939 [01:17<03:16,  5.66it/s]
 43%|████▎     | 831/1939 [01:17<02:24,  7.68it/s]
 43%|████▎     | 834/1939 [01:18<01:55,  9.57it/s]
 43%|████▎     | 837/1939 [01:18<01:33, 11.73it/s]
 43%|████▎     | 839/1939 [01:18<01:42, 10.70it/s]
 43%|████▎     | 841/1939 [01:18<01:38, 11.11it/s]
 44%|████▎     | 844/1939 [01:18<01:24, 12.97it/s]
 44%|████▎     | 847/1939 [01:18<01:08, 15.94it/s]
 44%|████▍     | 851/1939 [01:19<01:06, 16.40it/s]
 44%|████▍     | 853/1939 [01:19<01:04, 16.74it/s]
 44%|████▍     | 855/1939 [01:19<01:28, 12.27it/s]
 44%|████▍     | 857/1939 [01:19<01:44, 10.40it/s]
 44%|████▍     | 859/1939 [01:20<01:55,  9.36it/s]
 44%|████▍     | 861/1939 [01:20<02:14,  8.03it/s]
 44%|████▍     | 862/1939 [01:20<02:24,  7.46it/s]
 45%|████▍     | 863/1939 [01:20<02:46,  6.46it/s]
 45%|████▍     | 864/1939 [01:21<02:50,  6.30it/s]
 45%|████▍     | 866/1939 [01:21<02:13,  8.05it/s]
 45%|████▍     | 869/1939 [01:21<01:32, 11.53it/s]
 45%|████▌     | 875/1939 [01:21<00:50, 21.00it/s]
 45%|████▌     | 881/1939 [01:21<00:36, 28.89it/s]
 46%|████▌     | 885/1939 [01:21<00:33, 31.16it/s]
 46%|████▌     | 889/1939 [01:21<00:35, 29.84it/s]
 46%|████▌     | 894/1939 [01:21<00:33, 31.09it/s]
 46%|████▋     | 899/1939 [01:22<00:41, 25.04it/s]
 47%|████▋     | 902/1939 [01:22<01:12, 14.38it/s]
 47%|████▋     | 905/1939 [01:22<01:10, 14.59it/s]
 47%|████▋     | 907/1939 [01:23<01:07, 15.22it/s]
 47%|████▋     | 910/1939 [01:23<01:15, 13.58it/s]
 47%|████▋     | 912/1939 [01:23<01:26, 11.82it/s]
 47%|████▋     | 914/1939 [01:23<01:20, 12.72it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 308.96it/s]
 34%|███▎      | 101/300 [03:11<1:47:52, 32.53s/it]

[[np.int64(0), False, 8], [np.int64(1), False, 10], [np.int64(2), False, 12], [np.int64(3), False, 6], [np.int64(4), False, 10], [np.int64(5), False, 9], [np.int64(6), False, 0], [np.int64(7), False, 10], [np.int64(8), False, 10], [np.int64(9), False, 1], [np.int64(11), False, 0], [np.int64(12), False, 11], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5638, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.8047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7002, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [03:11<1:25:49, 26.01s/it]

tensor(12.8158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9056, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:11<54:03, 16.55s/it]

tensor(12.8549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1223, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3019, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9735, device='cuda:0', grad_fn=<AddBackward0>)

 35%|███▌      | 106/300 [03:12<35:16, 10.91s/it]

tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4147, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4592, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0318, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4957, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [03:12<15:56,  5.03s/it]

tensor(13.0153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5245, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5912, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6468, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [03:12<10:55,  3.48s/it]

tensor(12.8851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6909, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8470, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7268, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7425, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:13<05:16,  1.72s/it]

tensor(12.7852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7737, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8053, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [03:13<03:43,  1.23s/it]

tensor(12.7455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8561, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9001, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9500, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [03:13<02:39,  1.13it/s]

tensor(12.7274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9810, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0143, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0618, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [03:13<01:24,  2.08it/s]

tensor(12.7006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1098, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1440, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1827, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [03:14<01:03,  2.74it/s]

tensor(12.6697, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2446, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6486, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2748, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [03:14<00:38,  4.40it/s]

tensor(12.6343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3101, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3292, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [03:14<00:31,  5.31it/s]

tensor(12.5850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3442, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3548, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3652, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [03:14<00:23,  7.10it/s]

tensor(12.5388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3796, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3883, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4004, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [03:15<00:20,  7.86it/s]

tensor(12.5012, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4297, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4790, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4459, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:15<00:17,  9.02it/s]

tensor(12.4684, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4806, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4490, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4943, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:15<00:16,  9.40it/s]

tensor(12.4400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5067, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4312, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5372, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:16<00:15,  9.96it/s]

tensor(12.4141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5559, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5682, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:16<00:14, 10.12it/s]

tensor(12.3912, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5585, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([120, 186, 120, 201, 182, 142,  79,  90,  88, 119, 252, 296,  33,  31])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:25, 22.53it/s]
  0%|          | 6/1939 [00:00<01:36, 20.00it/s]
  1%|          | 13/1939 [00:00<00:52, 37.04it/s]
  1%|          | 18/1939 [00:00<00:58, 32.62it/s]
  1%|          | 23/1939 [00:00<00:51, 37.18it/s]
  2%|▏         | 30/1939 [00:00<00:42, 45.31it/s]
  2%|▏         | 37/1939 [00:00<00:37, 50.75it/s]
  2%|▏         | 43/1939 [00:01<01:07, 28.29it/s]
  2%|▏         | 48/1939 [00:01<01:00, 31.21it/s]
  3%|▎         | 53/1939 [00:01<01:32, 20.32it/s]
  3%|▎         | 58/1939 [00:02<01:22, 22.89it/s]
  3%|▎         | 62/1939 [00:02<01:42, 18.31it/s]
  3%|▎         | 65/1939 [00:02<01:40, 18.59it/s]
  4%|▎         | 68/1939 [00:02<01:53, 16.55it/s]
  4%|▎         | 71/1939 [00:03<02:43, 11.43it/s]
  4%|▍         | 73/1939 [00:03<02:36, 11.89it/s]
  4%|▍         | 75/1939 [00:03<02:26, 12.72it/s]
  4%|▍         | 78/1939 [00:03<02:22, 13.07it/s]
  4%|▍         | 80/1939 [00:04<03:41,  8.39it/s]
  4%|▍         | 82/1939 [00:04<04:55,  6.28it/s]
  4%|▍         | 84/1939 [00:04<04:06,  7.52it/s]
  4%|▍         | 86/1939 [00:05<03:53,  7.92it/s]
  5%|▍         | 88/1939 [00:05<03:32,  8.71it/s]
  5%|▍         | 90/1939 [00:05<03:06,  9.91it/s]
  5%|▍         | 94/1939 [00:05<02:51, 10.73it/s]
  5%|▌         | 97/1939 [00:05<02:21, 13.03it/s]
  5%|▌         | 100/1939 [00:06<02:26, 12.58it/s]
  5%|▌         | 102/1939 [00:06<02:21, 13.01it/s]
  5%|▌         | 105/1939 [00:06<02:03, 14.89it/s]
  6%|▌         | 109/1939 [00:06<01:34, 19.29it/s]
  6%|▌         | 113/1939 [00:06<01:20, 22.69it/s]
  6%|▌         | 117/1939 [00:06<01:09, 26.13it/s]
  6%|▌         | 120/1939 [00:07<02:05, 14.44it/s]
  6%|▋         | 123/1939 [00:07<02:02, 14.79it/s]
  6%|▋         | 126/1939 [00:07<02:07, 14.17it/s]
  7%|▋         | 128/1939 [00:08<02:47, 10.79it/s]
  7%|▋         | 130/1939 [00:08<02:31, 11.94it/s]
  7%|▋         | 132/1939 [00:08<02:29, 12.12it/s]
  7%|▋         | 134/1939 [00:08<02:19, 12.92it/s]
  7%|▋         | 139/1939 [00:08<01:31, 19.75it/s]
  7%|▋         | 142/1939 [00:08<02:01, 14.82it/s]
  7%|▋         | 144/1939 [00:09<01:56, 15.46it/s]
  8%|▊         | 146/1939 [00:09<02:53, 10.32it/s]
  8%|▊         | 148/1939 [00:09<02:37, 11.39it/s]
  8%|▊         | 150/1939 [00:09<02:23, 12.51it/s]
  8%|▊         | 153/1939 [00:09<02:14, 13.32it/s]
  8%|▊         | 155/1939 [00:10<02:38, 11.27it/s]
  8%|▊         | 157/1939 [00:10<02:48, 10.56it/s]
  8%|▊         | 159/1939 [00:10<03:03,  9.68it/s]
  8%|▊         | 161/1939 [00:10<03:17,  9.00it/s]
  8%|▊         | 162/1939 [00:11<03:56,  7.51it/s]
  8%|▊         | 164/1939 [00:11<03:13,  9.16it/s]
  9%|▊         | 166/1939 [00:11<02:41, 10.99it/s]
  9%|▊         | 169/1939 [00:11<02:00, 14.71it/s]
  9%|▉         | 175/1939 [00:11<01:12, 24.24it/s]
  9%|▉         | 178/1939 [00:11<01:19, 22.10it/s]
  9%|▉         | 184/1939 [00:11<01:00, 29.02it/s]
 10%|▉         | 188/1939 [00:11<00:58, 30.18it/s]
 10%|█         | 194/1939 [00:12<00:51, 33.95it/s]
 10%|█         | 198/1939 [00:12<00:53, 32.81it/s]
 10%|█         | 202/1939 [00:12<01:34, 18.35it/s]
 11%|█         | 205/1939 [00:12<01:34, 18.35it/s]
 11%|█         | 208/1939 [00:13<02:05, 13.74it/s]
 11%|█         | 212/1939 [00:13<01:39, 17.37it/s]
 11%|█         | 215/1939 [00:13<01:30, 19.09it/s]
 11%|█         | 218/1939 [00:13<01:28, 19.49it/s]
 11%|█▏        | 222/1939 [00:13<01:14, 23.20it/s]
 12%|█▏        | 226/1939 [00:13<01:05, 26.07it/s]
 50%|█████     | 150/300 [03:33<00:14, 10.12it/s]]
 12%|█▏        | 233/1939 [00:14<02:45, 10.33it/s]
 12%|█▏        | 235/1939 [00:15<02:34, 11.02it/s]
 12%|█▏        | 237/1939 [00:15<03:10,  8.94it/s]
 12%|█▏        | 239/1939 [00:15<03:37,  7.81it/s]
 12%|█▏        | 241/1939 [00:16<04:45,  5.94it/s]
 12%|█▏        | 242/1939 [00:16<05:15,  5.38it/s]
 13%|█▎        | 243/1939 [00:16<05:49,  4.85it/s]
 13%|█▎        | 245/1939 [00:17<05:23,  5.23it/s]
 13%|█▎        | 246/1939 [00:17<04:55,  5.74it/s]
 13%|█▎        | 247/1939 [00:17<04:28,  6.30it/s]
 13%|█▎        | 248/1939 [00:17<04:43,  5.97it/s]
 13%|█▎        | 250/1939 [00:17<03:35,  7.82it/s]
 13%|█▎        | 252/1939 [00:17<03:02,  9.25it/s]
 13%|█▎        | 257/1939 [00:18<02:22, 11.82it/s]
 13%|█▎        | 259/1939 [00:18<02:09, 12.97it/s]
 13%|█▎        | 261/1939 [00:18<02:56,  9.52it/s]
 14%|█▎        | 263/1939 [00:19<03:21,  8.30it/s]
 14%|█▎        | 265/1939 [00:19<02:57,  9.41it/s]
 14%|█▍        | 270/1939 [00:19<01:47, 15.49it/s]
 14%|█▍        | 276/1939 [00:19<01:11, 23.28it/s]
 14%|█▍        | 281/1939 [00:19<01:29, 18.60it/s]
 15%|█▍        | 284/1939 [00:20<01:57, 14.09it/s]
 15%|█▍        | 287/1939 [00:20<02:16, 12.10it/s]
 15%|█▌        | 292/1939 [00:20<01:38, 16.69it/s]
 15%|█▌        | 295/1939 [00:20<01:32, 17.76it/s]
 15%|█▌        | 298/1939 [00:21<02:10, 12.56it/s]
 16%|█▌        | 303/1939 [00:21<01:34, 17.39it/s]
 16%|█▌        | 307/1939 [00:21<01:49, 14.95it/s]
 16%|█▌        | 310/1939 [00:21<01:39, 16.42it/s]
 16%|█▌        | 315/1939 [00:21<01:15, 21.64it/s]
 17%|█▋        | 320/1939 [00:22<01:00, 26.77it/s]
 17%|█▋        | 324/1939 [00:22<02:11, 12.29it/s]
 17%|█▋        | 329/1939 [00:22<01:38, 16.33it/s]
 17%|█▋        | 334/1939 [00:23<01:16, 20.85it/s]
 18%|█▊        | 340/1939 [00:23<01:00, 26.34it/s]
 18%|█▊        | 346/1939 [00:23<00:49, 32.00it/s]
 18%|█▊        | 351/1939 [00:23<01:12, 21.79it/s]
 18%|█▊        | 355/1939 [00:24<02:03, 12.78it/s]
 18%|█▊        | 358/1939 [00:24<01:58, 13.37it/s]
 19%|█▊        | 362/1939 [00:24<01:36, 16.30it/s]
 19%|█▉        | 365/1939 [00:25<02:03, 12.71it/s]
 19%|█▉        | 368/1939 [00:25<01:47, 14.56it/s]
 19%|█▉        | 372/1939 [00:25<01:29, 17.49it/s]
 19%|█▉        | 375/1939 [00:25<01:21, 19.20it/s]
 19%|█▉        | 378/1939 [00:25<01:22, 18.86it/s]
 20%|█▉        | 381/1939 [00:25<01:54, 13.65it/s]
 20%|█▉        | 383/1939 [00:26<01:50, 14.10it/s]
 20%|█▉        | 385/1939 [00:26<02:37,  9.89it/s]
 20%|█▉        | 387/1939 [00:26<02:49,  9.18it/s]
 20%|██        | 389/1939 [00:26<02:37,  9.82it/s]
 20%|██        | 391/1939 [00:27<02:37,  9.84it/s]
 20%|██        | 393/1939 [00:27<03:31,  7.30it/s]
 20%|██        | 394/1939 [00:27<04:21,  5.91it/s]
 20%|██        | 395/1939 [00:28<04:11,  6.13it/s]
 20%|██        | 396/1939 [00:28<05:03,  5.09it/s]
 20%|██        | 397/1939 [00:28<04:38,  5.53it/s]
 21%|██        | 398/1939 [00:28<05:49,  4.41it/s]
 21%|██        | 399/1939 [00:29<06:29,  3.95it/s]
 21%|██        | 402/1939 [00:29<03:38,  7.04it/s]
 21%|██        | 404/1939 [00:29<03:03,  8.36it/s]
 21%|██        | 406/1939 [00:29<03:13,  7.93it/s]
 21%|██        | 407/1939 [00:29<03:23,  7.52it/s]
 21%|██        | 411/1939 [00:30<02:30, 10.15it/s]
 21%|██▏       | 413/1939 [00:30<02:14, 11.33it/s]
 21%|██▏       | 415/1939 [00:30<02:12, 11.54it/s]
 22%|██▏       | 417/1939 [00:30<02:46,  9.16it/s]
 22%|██▏       | 419/1939 [00:30<02:36,  9.71it/s]
 22%|██▏       | 421/1939 [00:31<02:14, 11.30it/s]
 22%|██▏       | 423/1939 [00:31<02:18, 10.92it/s]
 22%|██▏       | 425/1939 [00:31<02:04, 12.14it/s]
 22%|██▏       | 427/1939 [00:31<03:09,  7.99it/s]
 22%|██▏       | 429/1939 [00:32<03:50,  6.54it/s]
 22%|██▏       | 432/1939 [00:32<02:41,  9.31it/s]
 23%|██▎       | 437/1939 [00:32<01:38, 15.19it/s]
 23%|██▎       | 443/1939 [00:32<01:05, 22.89it/s]
 23%|██▎       | 448/1939 [00:32<00:52, 28.20it/s]
 23%|██▎       | 454/1939 [00:32<00:42, 35.04it/s]
 24%|██▎       | 460/1939 [00:32<00:37, 39.87it/s]
 24%|██▍       | 466/1939 [00:33<00:34, 43.24it/s]
 24%|██▍       | 473/1939 [00:33<00:33, 44.12it/s]
 25%|██▍       | 478/1939 [00:33<00:33, 43.25it/s]
 25%|██▍       | 483/1939 [00:33<00:48, 29.86it/s]
 25%|██▌       | 489/1939 [00:33<01:01, 23.48it/s]
 25%|██▌       | 493/1939 [00:34<01:24, 17.19it/s]
 26%|██▌       | 496/1939 [00:34<01:16, 18.77it/s]
 26%|██▌       | 501/1939 [00:34<01:01, 23.34it/s]
 26%|██▌       | 508/1939 [00:34<00:46, 30.94it/s]
 27%|██▋       | 514/1939 [00:34<00:41, 34.30it/s]
 27%|██▋       | 519/1939 [00:34<00:37, 37.50it/s]
 27%|██▋       | 524/1939 [00:35<00:36, 38.31it/s]
 27%|██▋       | 531/1939 [00:35<00:31, 44.40it/s]
 28%|██▊       | 537/1939 [00:35<00:50, 27.55it/s]
 28%|██▊       | 541/1939 [00:35<00:50, 27.45it/s]
 28%|██▊       | 546/1939 [00:36<01:04, 21.72it/s]
 28%|██▊       | 549/1939 [00:36<01:29, 15.54it/s]
 28%|██▊       | 552/1939 [00:36<01:50, 12.51it/s]
 29%|██▊       | 554/1939 [00:37<01:46, 13.02it/s]
 29%|██▉       | 559/1939 [00:37<01:17, 17.79it/s]
 29%|██▉       | 566/1939 [00:37<00:52, 25.93it/s]
 29%|██▉       | 570/1939 [00:37<00:47, 28.55it/s]
 30%|██▉       | 574/1939 [00:37<01:03, 21.42it/s]
 30%|██▉       | 578/1939 [00:38<01:23, 16.37it/s]
 30%|██▉       | 581/1939 [00:38<01:50, 12.33it/s]
 30%|███       | 583/1939 [00:38<02:04, 10.85it/s]
 30%|███       | 585/1939 [00:39<02:30,  9.02it/s]
 30%|███       | 587/1939 [00:39<02:16,  9.90it/s]
 30%|███       | 590/1939 [00:39<01:51, 12.12it/s]
 31%|███       | 592/1939 [00:39<01:48, 12.39it/s]
 31%|███       | 594/1939 [00:39<01:40, 13.43it/s]
 31%|███       | 596/1939 [00:39<01:44, 12.83it/s]
 31%|███       | 598/1939 [00:39<01:34, 14.23it/s]
 31%|███       | 600/1939 [00:40<01:55, 11.63it/s]
 31%|███       | 602/1939 [00:40<02:27,  9.07it/s]
 31%|███       | 604/1939 [00:40<02:21,  9.42it/s]
 31%|███▏      | 606/1939 [00:40<02:10, 10.23it/s]
 31%|███▏      | 608/1939 [00:41<02:23,  9.26it/s]
 31%|███▏      | 610/1939 [00:41<02:20,  9.48it/s]
 32%|███▏      | 612/1939 [00:41<02:13,  9.96it/s]
 32%|███▏      | 614/1939 [00:41<02:29,  8.85it/s]
 32%|███▏      | 615/1939 [00:41<02:28,  8.92it/s]
 32%|███▏      | 616/1939 [00:42<02:26,  9.05it/s]
 32%|███▏      | 617/1939 [00:42<02:57,  7.45it/s]
 32%|███▏      | 619/1939 [00:42<02:30,  8.75it/s]
 32%|███▏      | 620/1939 [00:42<02:56,  7.46it/s]
 32%|███▏      | 621/1939 [00:42<03:39,  6.01it/s]
 32%|███▏      | 622/1939 [00:43<04:07,  5.32it/s]
 32%|███▏      | 626/1939 [00:43<02:03, 10.63it/s]
 32%|███▏      | 629/1939 [00:43<02:14,  9.71it/s]
 33%|███▎      | 631/1939 [00:44<02:43,  7.99it/s]
 33%|███▎      | 633/1939 [00:44<02:59,  7.29it/s]
 33%|███▎      | 635/1939 [00:44<02:27,  8.83it/s]
 33%|███▎      | 637/1939 [00:45<03:50,  5.65it/s]
 33%|███▎      | 639/1939 [00:45<03:08,  6.88it/s]
 33%|███▎      | 641/1939 [00:45<04:14,  5.11it/s]
 33%|███▎      | 643/1939 [00:46<04:14,  5.08it/s]
 33%|███▎      | 645/1939 [00:46<03:21,  6.41it/s]
 33%|███▎      | 649/1939 [00:46<02:40,  8.03it/s]
 34%|███▎      | 651/1939 [00:47<02:56,  7.30it/s]
 34%|███▎      | 653/1939 [00:47<02:28,  8.65it/s]
 34%|███▍      | 656/1939 [00:47<02:28,  8.65it/s]
 34%|███▍      | 658/1939 [00:48<02:58,  7.16it/s]
 34%|███▍      | 659/1939 [00:48<03:32,  6.01it/s]
 34%|███▍      | 662/1939 [00:48<02:30,  8.49it/s]
 34%|███▍      | 665/1939 [00:48<02:27,  8.63it/s]
 34%|███▍      | 667/1939 [00:49<02:54,  7.31it/s]
 35%|███▍      | 669/1939 [00:49<02:29,  8.50it/s]
 35%|███▍      | 672/1939 [00:49<02:15,  9.32it/s]
 35%|███▍      | 674/1939 [00:49<02:31,  8.37it/s]
 35%|███▍      | 676/1939 [00:50<02:42,  7.79it/s]
 35%|███▍      | 678/1939 [00:50<02:19,  9.06it/s]
 35%|███▌      | 680/1939 [00:50<02:34,  8.14it/s]
 35%|███▌      | 683/1939 [00:50<02:04, 10.12it/s]
 35%|███▌      | 685/1939 [00:50<01:52, 11.12it/s]
 35%|███▌      | 687/1939 [00:51<02:07,  9.84it/s]
 36%|███▌      | 689/1939 [00:51<02:02, 10.18it/s]
 36%|███▌      | 691/1939 [00:51<01:49, 11.44it/s]
 36%|███▌      | 693/1939 [00:51<01:40, 12.44it/s]
 36%|███▌      | 696/1939 [00:51<01:21, 15.30it/s]
 36%|███▌      | 699/1939 [00:51<01:10, 17.61it/s]
 36%|███▋      | 703/1939 [00:51<00:54, 22.66it/s]
 37%|███▋      | 708/1939 [00:52<00:42, 29.25it/s]
 37%|███▋      | 712/1939 [00:52<00:42, 28.89it/s]
 37%|███▋      | 717/1939 [00:52<00:36, 33.75it/s]
 37%|███▋      | 723/1939 [00:52<00:30, 40.08it/s]
 38%|███▊      | 728/1939 [00:52<00:49, 24.57it/s]
 38%|███▊      | 732/1939 [00:53<01:24, 14.21it/s]
 38%|███▊      | 735/1939 [00:53<01:22, 14.62it/s]
 38%|███▊      | 738/1939 [00:53<01:15, 15.82it/s]
 38%|███▊      | 741/1939 [00:53<01:08, 17.60it/s]
 38%|███▊      | 745/1939 [00:53<00:57, 20.82it/s]
 39%|███▊      | 748/1939 [00:54<01:06, 17.85it/s]
 39%|███▉      | 752/1939 [00:54<00:58, 20.16it/s]
 39%|███▉      | 755/1939 [00:54<01:27, 13.50it/s]
 39%|███▉      | 757/1939 [00:55<01:45, 11.21it/s]
 39%|███▉      | 759/1939 [00:55<01:38, 12.02it/s]
 39%|███▉      | 761/1939 [00:55<02:04,  9.48it/s]
 39%|███▉      | 763/1939 [00:55<02:29,  7.87it/s]
 39%|███▉      | 765/1939 [00:56<02:12,  8.88it/s]
 40%|███▉      | 767/1939 [00:56<03:11,  6.12it/s]
 40%|███▉      | 768/1939 [00:57<03:43,  5.24it/s]
 40%|███▉      | 769/1939 [00:57<04:22,  4.45it/s]
 40%|███▉      | 770/1939 [00:57<04:09,  4.68it/s]
 40%|███▉      | 772/1939 [00:57<03:20,  5.82it/s]
 40%|███▉      | 773/1939 [00:57<03:32,  5.48it/s]
 40%|███▉      | 774/1939 [00:58<03:25,  5.66it/s]
 40%|████      | 776/1939 [00:58<02:55,  6.64it/s]
 40%|████      | 777/1939 [00:58<02:47,  6.94it/s]
 40%|████      | 779/1939 [00:58<02:11,  8.85it/s]
 40%|████      | 780/1939 [00:58<03:07,  6.18it/s]
 40%|████      | 782/1939 [00:59<02:21,  8.16it/s]
 40%|████      | 784/1939 [00:59<02:41,  7.15it/s]
 40%|████      | 785/1939 [00:59<02:40,  7.17it/s]
 41%|████      | 787/1939 [00:59<02:21,  8.16it/s]
 41%|████      | 789/1939 [00:59<02:14,  8.52it/s]
 41%|████      | 791/1939 [01:00<02:08,  8.91it/s]
 41%|████      | 793/1939 [01:00<01:50, 10.41it/s]
 41%|████      | 795/1939 [01:00<01:43, 11.03it/s]
 41%|████      | 797/1939 [01:00<02:24,  7.92it/s]
 41%|████      | 798/1939 [01:01<03:06,  6.13it/s]
 41%|████▏     | 800/1939 [01:01<02:32,  7.45it/s]
 41%|████▏     | 802/1939 [01:01<02:06,  9.01it/s]
 41%|████▏     | 804/1939 [01:01<02:05,  9.04it/s]
 42%|████▏     | 806/1939 [01:02<02:37,  7.20it/s]
 42%|████▏     | 808/1939 [01:02<02:13,  8.47it/s]
 42%|████▏     | 810/1939 [01:02<02:39,  7.08it/s]
 42%|████▏     | 813/1939 [01:02<02:31,  7.45it/s]
 42%|████▏     | 814/1939 [01:03<02:31,  7.43it/s]
 42%|████▏     | 816/1939 [01:03<02:38,  7.10it/s]
 42%|████▏     | 817/1939 [01:03<02:40,  6.99it/s]
 42%|████▏     | 818/1939 [01:03<03:14,  5.76it/s]
 42%|████▏     | 819/1939 [01:03<03:02,  6.15it/s]
 42%|████▏     | 820/1939 [01:04<03:25,  5.46it/s]
 42%|████▏     | 821/1939 [01:04<03:29,  5.34it/s]
 42%|████▏     | 822/1939 [01:04<03:23,  5.49it/s]
 42%|████▏     | 823/1939 [01:04<03:09,  5.90it/s]
 43%|████▎     | 825/1939 [01:05<02:49,  6.57it/s]
 43%|████▎     | 827/1939 [01:05<02:05,  8.84it/s]
 43%|████▎     | 829/1939 [01:05<01:45, 10.49it/s]
 43%|████▎     | 833/1939 [01:05<01:07, 16.41it/s]
 43%|████▎     | 839/1939 [01:05<00:41, 26.24it/s]
 44%|████▎     | 845/1939 [01:05<00:34, 32.02it/s]
 44%|████▍     | 849/1939 [01:05<00:35, 30.78it/s]
 44%|████▍     | 853/1939 [01:05<00:33, 31.99it/s]
 44%|████▍     | 857/1939 [01:06<01:02, 17.45it/s]
 44%|████▍     | 860/1939 [01:06<01:02, 17.17it/s]
 45%|████▍     | 863/1939 [01:06<01:00, 17.79it/s]
 45%|████▍     | 866/1939 [01:06<01:03, 17.02it/s]
 45%|████▍     | 869/1939 [01:06<00:59, 17.89it/s]
 45%|████▍     | 872/1939 [01:07<00:54, 19.64it/s]
 45%|████▌     | 879/1939 [01:07<00:35, 29.74it/s]
 46%|████▌     | 885/1939 [01:07<00:29, 35.73it/s]
 46%|████▌     | 890/1939 [01:07<00:29, 35.90it/s]
 46%|████▌     | 896/1939 [01:07<00:25, 40.66it/s]
 46%|████▋     | 901/1939 [01:08<00:59, 17.55it/s]
 47%|████▋     | 905/1939 [01:08<01:13, 14.05it/s]
 47%|████▋     | 910/1939 [01:09<01:12, 14.13it/s]
 47%|████▋     | 913/1939 [01:09<01:28, 11.61it/s]
 47%|████▋     | 916/1939 [01:09<01:15, 13.46it/s]
 47%|████▋     | 919/1939 [01:09<01:29, 11.42it/s]
 48%|████▊     | 923/1939 [01:10<01:08, 14.80it/s]
 48%|████▊     | 927/1939 [01:10<01:17, 13.12it/s]
 48%|████▊     | 930/1939 [01:10<01:31, 11.03it/s]
 48%|████▊     | 932/1939 [01:11<01:45,  9.59it/s]
 48%|████▊     | 934/1939 [01:11<01:56,  8.64it/s]
 48%|████▊     | 937/1939 [01:11<01:32, 10.89it/s]
 48%|████▊     | 939/1939 [01:11<01:26, 11.53it/s]
 49%|████▊     | 943/1939 [01:11<01:02, 15.83it/s]
 49%|████▉     | 949/1939 [01:11<00:41, 23.60it/s]
 49%|████▉     | 955/1939 [01:12<00:32, 30.52it/s]
 50%|████▉     | 960/1939 [01:12<00:28, 33.98it/s]
 50%|████▉     | 965/1939 [01:12<00:28, 34.52it/s]
 50%|████▉     | 969/1939 [01:12<01:02, 15.50it/s]
 50%|█████     | 972/1939 [01:13<01:16, 12.56it/s]
 50%|█████     | 975/1939 [01:13<01:33, 10.36it/s]
 50%|█████     | 977/1939 [01:14<01:51,  8.61it/s]
 50%|█████     | 979/1939 [01:14<01:41,  9.45it/s]
 51%|█████     | 981/1939 [01:14<01:56,  8.21it/s]
 51%|█████     | 983/1939 [01:15<02:11,  7.29it/s]
 51%|█████     | 984/1939 [01:15<02:18,  6.90it/s]
 51%|█████     | 986/1939 [01:15<01:51,  8.52it/s]
 51%|█████     | 988/1939 [01:15<01:46,  8.95it/s]
 51%|█████     | 990/1939 [01:15<01:45,  9.01it/s]
 51%|█████     | 992/1939 [01:16<02:03,  7.66it/s]
 51%|█████▏    | 994/1939 [01:16<01:57,  8.05it/s]
 51%|█████▏    | 996/1939 [01:16<01:53,  8.34it/s]
 51%|█████▏    | 997/1939 [01:16<01:52,  8.34it/s]
 52%|█████▏    | 999/1939 [01:17<02:12,  7.11it/s]
 52%|█████▏    | 1001/1939 [01:17<02:21,  6.63it/s]
 52%|█████▏    | 1002/1939 [01:17<02:42,  5.76it/s]
 52%|█████▏    | 1004/1939 [01:17<02:15,  6.90it/s]
 52%|█████▏    | 1006/1939 [01:18<02:07,  7.29it/s]
 52%|█████▏    | 1007/1939 [01:18<02:41,  5.77it/s]
 52%|█████▏    | 1009/1939 [01:18<02:34,  6.00it/s]
 52%|█████▏    | 1011/1939 [01:19<02:35,  5.98it/s]
 52%|█████▏    | 1012/1939 [01:19<02:35,  5.97it/s]
 52%|█████▏    | 1014/1939 [01:19<02:25,  6.37it/s]
 52%|█████▏    | 1015/1939 [01:19<02:45,  5.58it/s]
 52%|█████▏    | 1016/1939 [01:19<02:31,  6.08it/s]
 52%|█████▏    | 1017/1939 [01:20<02:18,  6.67it/s]
 53%|█████▎    | 1018/1939 [01:20<03:04,  5.00it/s]
 53%|█████▎    | 1019/1939 [01:20<03:04,  5.00it/s]
 53%|█████▎    | 1021/1939 [01:20<02:09,  7.09it/s]
 53%|█████▎    | 1022/1939 [01:20<02:21,  6.48it/s]
 53%|█████▎    | 1024/1939 [01:21<01:47,  8.52it/s]
 53%|█████▎    | 1026/1939 [01:21<01:26, 10.58it/s]
 53%|█████▎    | 1030/1939 [01:21<01:10, 12.85it/s]
 53%|█████▎    | 1033/1939 [01:21<01:14, 12.10it/s]
 53%|█████▎    | 1035/1939 [01:21<01:08, 13.28it/s]
 54%|█████▎    | 1040/1939 [01:21<00:45, 19.88it/s]
 54%|█████▍    | 1044/1939 [01:21<00:37, 23.85it/s]
 54%|█████▍    | 1047/1939 [01:22<01:06, 13.45it/s]
 54%|█████▍    | 1050/1939 [01:23<01:39,  8.91it/s]
 54%|█████▍    | 1052/1939 [01:23<01:55,  7.66it/s]
 54%|█████▍    | 1054/1939 [01:23<02:19,  6.35it/s]
 54%|█████▍    | 1056/1939 [01:24<02:10,  6.74it/s]
 55%|█████▍    | 1058/1939 [01:24<01:53,  7.79it/s]
 55%|█████▍    | 1060/1939 [01:24<02:04,  7.07it/s]
 55%|█████▍    | 1061/1939 [01:24<02:04,  7.08it/s]
 55%|█████▍    | 1063/1939 [01:25<01:45,  8.28it/s]
 55%|█████▍    | 1065/1939 [01:25<01:29,  9.73it/s]
 55%|█████▌    | 1068/1939 [01:25<01:21, 10.65it/s]
 55%|█████▌    | 1070/1939 [01:25<01:18, 11.14it/s]
 55%|█████▌    | 1072/1939 [01:25<01:20, 10.72it/s]
 55%|█████▌    | 1074/1939 [01:25<01:17, 11.22it/s]
 56%|█████▌    | 1077/1939 [01:26<01:04, 13.30it/s]
 56%|█████▌    | 1080/1939 [01:26<00:55, 15.46it/s]
 56%|█████▌    | 1084/1939 [01:26<00:42, 20.14it/s]
 56%|█████▌    | 1088/1939 [01:26<00:42, 19.83it/s]
 56%|█████▋    | 1091/1939 [01:26<01:04, 13.12it/s]
 56%|█████▋    | 1093/1939 [01:27<01:22, 10.22it/s]
 56%|█████▋    | 1095/1939 [01:27<02:01,  6.94it/s]
 57%|█████▋    | 1097/1939 [01:28<02:08,  6.57it/s]
 57%|█████▋    | 1099/1939 [01:28<02:01,  6.89it/s]
 57%|█████▋    | 1101/1939 [01:28<02:09,  6.46it/s]
 57%|█████▋    | 1102/1939 [01:29<02:16,  6.13it/s]
 57%|█████▋    | 1104/1939 [01:29<02:00,  6.94it/s]
 57%|█████▋    | 1105/1939 [01:29<02:32,  5.47it/s]
 57%|█████▋    | 1106/1939 [01:29<02:34,  5.38it/s]
 57%|█████▋    | 1109/1939 [01:30<02:13,  6.23it/s]
 57%|█████▋    | 1110/1939 [01:30<02:19,  5.94it/s]
 57%|█████▋    | 1112/1939 [01:30<02:16,  6.06it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 295.06it/s]
 50%|█████     | 151/300 [05:53<1:08:53, 27.74s/it]

[[np.int64(0), False, 5], [np.int64(1), False, 11], [np.int64(2), False, 4], [np.int64(3), False, 0], [np.int64(5), False, 11], [np.int64(6), False, 2], [np.int64(7), False, 5], [np.int64(8), False, 3], [np.int64(9), False, 5], [np.int64(10), False, 11], [np.int64(12), False, 11], [np.int64(13), False, 8]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8624, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.3769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9008, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [05:53<42:15, 17.25s/it]

tensor(12.3785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9451, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [05:53<31:53, 13.10s/it]

tensor(12.3852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9688, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [05:53<23:35,  9.76s/it]

tensor(12.3932, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0632, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0714, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [05:53<13:31,  5.67s/it]

tensor(12.3794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0771, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [05:53<08:23,  3.57s/it]

tensor(12.3616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1018, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3451, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1329, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1714, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [05:54<05:27,  2.36s/it]

tensor(12.3275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2038, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2393, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [05:54<03:39,  1.60s/it]

tensor(12.3256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2653, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [05:54<02:30,  1.12s/it]

tensor(12.3251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3111, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3181, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2927, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [05:54<01:45,  1.26it/s]

tensor(12.3118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2872, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3041, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2803, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [05:54<01:15,  1.73it/s]

tensor(12.2959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2728, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [05:55<00:55,  2.32it/s]

tensor(12.2876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2605, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2589, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [05:55<00:41,  3.04it/s]

tensor(12.2686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2751, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2643, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2845, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [05:55<00:32,  3.87it/s]

tensor(12.2601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2978, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [05:55<00:25,  4.77it/s]

tensor(12.2552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3155, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3245, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2443, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3442, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [05:55<00:21,  5.70it/s]

tensor(12.2386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3581, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3627, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [05:56<00:18,  6.60it/s]

tensor(12.2292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3746, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [05:56<00:15,  7.42it/s]

tensor(12.2246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3769, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3801, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3836, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [05:56<00:14,  8.11it/s]

tensor(12.2107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3852, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3848, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [05:56<00:13,  8.68it/s]

tensor(12.2030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3878, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [05:56<00:12,  9.12it/s]

tensor(12.1995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3927, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3957, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3978, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [05:56<00:11,  9.47it/s]

tensor(12.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4033, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4045, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [05:57<00:10,  9.74it/s]

tensor(12.1802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4024, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [05:57<00:10,  9.94it/s]

tensor(12.1769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1740, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3737, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3784, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [05:57<00:10, 10.05it/s]

tensor(12.1682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3843, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3863, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [05:57<00:09, 10.10it/s]

tensor(12.1624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3844, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([159, 151,  88, 295, 101,  66, 176,  20, 221, 136,  77,  85, 172, 192])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:42, 18.94it/s]
  0%|          | 4/1939 [00:00<01:54, 16.94it/s]
  0%|          | 6/1939 [00:00<01:54, 16.87it/s]
  0%|          | 8/1939 [00:00<01:57, 16.41it/s]
  1%|          | 14/1939 [00:00<01:04, 29.91it/s]
  1%|          | 20/1939 [00:00<00:51, 37.49it/s]
  1%|▏         | 25/1939 [00:00<00:48, 39.47it/s]
  2%|▏         | 31/1939 [00:00<00:44, 43.25it/s]
  2%|▏         | 37/1939 [00:01<00:40, 46.39it/s]
  2%|▏         | 42/1939 [00:01<00:45, 41.71it/s]
  2%|▏         | 47/1939 [00:01<00:46, 40.78it/s]
  3%|▎         | 52/1939 [00:01<01:09, 27.30it/s]
  3%|▎         | 58/1939 [00:01<00:57, 32.65it/s]
  3%|▎         | 62/1939 [00:02<01:14, 25.27it/s]
  3%|▎         | 66/1939 [00:02<01:13, 25.38it/s]
  4%|▎         | 70/1939 [00:02<01:28, 21.23it/s]
  4%|▍         | 73/1939 [00:02<01:30, 20.62it/s]
  4%|▍         | 77/1939 [00:02<01:17, 24.00it/s]
  4%|▍         | 80/1939 [00:03<01:43, 18.01it/s]
  4%|▍         | 83/1939 [00:03<02:29, 12.45it/s]
  4%|▍         | 86/1939 [00:03<02:36, 11.84it/s]
  5%|▍         | 88/1939 [00:04<02:55, 10.53it/s]
  5%|▍         | 91/1939 [00:04<02:22, 12.95it/s]
  5%|▍         | 93/1939 [00:04<02:29, 12.31it/s]
  5%|▍         | 95/1939 [00:04<03:07,  9.85it/s]
  5%|▌         | 98/1939 [00:04<02:38, 11.64it/s]
  5%|▌         | 100/1939 [00:05<02:49, 10.82it/s]
  5%|▌         | 102/1939 [00:05<02:35, 11.80it/s]
  5%|▌         | 104/1939 [00:05<02:18, 13.22it/s]
  6%|▌         | 110/1939 [00:05<01:22, 22.27it/s]
  6%|▌         | 115/1939 [00:05<01:13, 24.79it/s]
  6%|▌         | 118/1939 [00:05<01:22, 22.05it/s]
  6%|▌         | 121/1939 [00:05<01:41, 17.90it/s]
  6%|▋         | 124/1939 [00:06<01:42, 17.66it/s]
  6%|▋         | 126/1939 [00:06<01:40, 18.01it/s]
  7%|▋         | 128/1939 [00:06<02:03, 14.68it/s]
  7%|▋         | 130/1939 [00:06<01:58, 15.30it/s]
  7%|▋         | 136/1939 [00:06<01:12, 24.74it/s]
  7%|▋         | 141/1939 [00:06<01:03, 28.16it/s]
  7%|▋         | 145/1939 [00:07<01:30, 19.83it/s]
  8%|▊         | 148/1939 [00:07<01:47, 16.66it/s]
  8%|▊         | 151/1939 [00:07<01:43, 17.25it/s]
  8%|▊         | 154/1939 [00:07<01:32, 19.36it/s]
  8%|▊         | 157/1939 [00:07<01:31, 19.53it/s]
  8%|▊         | 160/1939 [00:08<02:01, 14.70it/s]
  8%|▊         | 162/1939 [00:08<02:46, 10.68it/s]
  8%|▊         | 164/1939 [00:08<02:43, 10.87it/s]
  9%|▊         | 166/1939 [00:08<02:37, 11.25it/s]
  9%|▊         | 168/1939 [00:09<02:21, 12.51it/s]
  9%|▉         | 173/1939 [00:09<02:00, 14.67it/s]
  9%|▉         | 176/1939 [00:09<01:46, 16.59it/s]
  9%|▉         | 182/1939 [00:09<01:11, 24.63it/s]
 10%|▉         | 186/1939 [00:09<01:13, 23.97it/s]
 10%|▉         | 189/1939 [00:09<01:13, 23.95it/s]
 10%|█         | 195/1939 [00:09<00:55, 31.40it/s]
 66%|██████▋   | 199/300 [06:13<00:09, 10.10it/s]]
 10%|█         | 202/1939 [00:10<01:41, 17.11it/s]
 11%|█         | 205/1939 [00:10<01:42, 16.97it/s]
 11%|█         | 208/1939 [00:10<01:53, 15.24it/s]
 11%|█         | 214/1939 [00:11<01:17, 22.29it/s]
 11%|█▏        | 219/1939 [00:11<01:04, 26.87it/s]
 12%|█▏        | 224/1939 [00:11<00:55, 30.99it/s]
 12%|█▏        | 228/1939 [00:11<00:58, 29.15it/s]
 12%|█▏        | 232/1939 [00:11<01:24, 20.13it/s]
 12%|█▏        | 235/1939 [00:12<01:45, 16.16it/s]
 12%|█▏        | 239/1939 [00:12<01:44, 16.21it/s]
 12%|█▏        | 242/1939 [00:13<02:48, 10.05it/s]
 13%|█▎        | 244/1939 [00:13<02:56,  9.59it/s]
 13%|█▎        | 246/1939 [00:13<03:28,  8.14it/s]
 13%|█▎        | 248/1939 [00:13<03:13,  8.73it/s]
 13%|█▎        | 250/1939 [00:13<02:51,  9.84it/s]
 13%|█▎        | 252/1939 [00:14<02:28, 11.35it/s]
 13%|█▎        | 254/1939 [00:14<02:14, 12.57it/s]
 13%|█▎        | 258/1939 [00:14<01:35, 17.60it/s]
 13%|█▎        | 261/1939 [00:14<02:13, 12.59it/s]
 14%|█▎        | 263/1939 [00:14<02:26, 11.47it/s]
 14%|█▎        | 265/1939 [00:15<02:14, 12.42it/s]
 14%|█▍        | 272/1939 [00:15<01:14, 22.49it/s]
 14%|█▍        | 277/1939 [00:15<00:59, 27.91it/s]
 14%|█▍        | 281/1939 [00:15<01:28, 18.80it/s]
 15%|█▍        | 284/1939 [00:15<01:50, 15.00it/s]
 15%|█▍        | 287/1939 [00:16<02:02, 13.48it/s]
 15%|█▌        | 291/1939 [00:16<01:36, 17.15it/s]
 15%|█▌        | 296/1939 [00:16<01:14, 22.06it/s]
 16%|█▌        | 302/1939 [00:16<00:56, 28.78it/s]
 16%|█▌        | 307/1939 [00:16<01:06, 24.72it/s]
 16%|█▌        | 311/1939 [00:16<01:05, 25.04it/s]
 16%|█▌        | 315/1939 [00:17<01:25, 18.94it/s]
 17%|█▋        | 320/1939 [00:17<01:08, 23.73it/s]
 17%|█▋        | 324/1939 [00:17<01:28, 18.21it/s]
 17%|█▋        | 331/1939 [00:17<01:01, 25.97it/s]
 17%|█▋        | 338/1939 [00:17<00:48, 33.23it/s]
 18%|█▊        | 343/1939 [00:18<00:44, 35.95it/s]
 18%|█▊        | 348/1939 [00:18<00:46, 34.29it/s]
 18%|█▊        | 353/1939 [00:18<01:19, 19.98it/s]
 18%|█▊        | 357/1939 [00:19<01:38, 16.09it/s]
 19%|█▊        | 362/1939 [00:19<01:18, 20.21it/s]
 19%|█▉        | 367/1939 [00:19<01:04, 24.35it/s]
 19%|█▉        | 371/1939 [00:19<01:21, 19.23it/s]
 19%|█▉        | 374/1939 [00:19<01:15, 20.64it/s]
 20%|█▉        | 379/1939 [00:19<01:00, 25.73it/s]
 20%|█▉        | 383/1939 [00:20<01:22, 18.83it/s]
 20%|█▉        | 386/1939 [00:20<01:53, 13.64it/s]
 20%|██        | 389/1939 [00:20<02:02, 12.62it/s]
 20%|██        | 393/1939 [00:21<01:57, 13.13it/s]
 20%|██        | 395/1939 [00:21<02:12, 11.69it/s]
 20%|██        | 397/1939 [00:21<02:26, 10.56it/s]
 21%|██        | 399/1939 [00:22<02:43,  9.43it/s]
 21%|██        | 401/1939 [00:22<02:21, 10.83it/s]
 21%|██        | 405/1939 [00:22<02:07, 11.99it/s]
 21%|██        | 407/1939 [00:22<02:23, 10.69it/s]
 21%|██        | 411/1939 [00:22<02:10, 11.72it/s]
 21%|██▏       | 413/1939 [00:23<02:00, 12.61it/s]
 21%|██▏       | 415/1939 [00:23<02:10, 11.65it/s]
 22%|██▏       | 417/1939 [00:23<02:31, 10.04it/s]
 22%|██▏       | 419/1939 [00:23<02:44,  9.26it/s]
 22%|██▏       | 422/1939 [00:23<02:07, 11.92it/s]
 22%|██▏       | 426/1939 [00:24<01:59, 12.64it/s]
 22%|██▏       | 428/1939 [00:24<02:25, 10.40it/s]
 22%|██▏       | 431/1939 [00:24<01:57, 12.83it/s]
 23%|██▎       | 437/1939 [00:24<01:13, 20.35it/s]
 23%|██▎       | 443/1939 [00:24<00:54, 27.55it/s]
 23%|██▎       | 449/1939 [00:25<00:43, 34.34it/s]
 23%|██▎       | 454/1939 [00:25<00:39, 37.82it/s]
 24%|██▎       | 459/1939 [00:25<00:37, 39.95it/s]
 24%|██▍       | 465/1939 [00:25<00:33, 43.67it/s]
 24%|██▍       | 470/1939 [00:25<00:33, 43.84it/s]
 24%|██▍       | 475/1939 [00:25<00:32, 44.87it/s]
 25%|██▍       | 480/1939 [00:25<00:47, 30.91it/s]
 25%|██▍       | 484/1939 [00:25<00:46, 31.57it/s]
 25%|██▌       | 490/1939 [00:26<00:38, 37.40it/s]
 26%|██▌       | 495/1939 [00:26<00:56, 25.76it/s]
 26%|██▌       | 502/1939 [00:26<00:42, 33.44it/s]
 26%|██▌       | 508/1939 [00:26<00:38, 36.70it/s]
 26%|██▋       | 513/1939 [00:26<00:55, 25.69it/s]
 27%|██▋       | 518/1939 [00:27<00:48, 29.29it/s]
 27%|██▋       | 524/1939 [00:27<00:41, 33.98it/s]
 27%|██▋       | 530/1939 [00:27<00:36, 38.12it/s]
 28%|██▊       | 536/1939 [00:27<00:33, 42.10it/s]
 28%|██▊       | 541/1939 [00:27<00:54, 25.54it/s]
 28%|██▊       | 546/1939 [00:28<00:59, 23.31it/s]
 28%|██▊       | 550/1939 [00:28<01:14, 18.67it/s]
 29%|██▊       | 553/1939 [00:28<01:25, 16.16it/s]
 29%|██▉       | 558/1939 [00:28<01:06, 20.69it/s]
 29%|██▉       | 564/1939 [00:28<00:52, 26.02it/s]
 29%|██▉       | 569/1939 [00:29<00:46, 29.73it/s]
 30%|██▉       | 573/1939 [00:29<01:00, 22.65it/s]
 30%|██▉       | 577/1939 [00:29<01:13, 18.49it/s]
 30%|██▉       | 580/1939 [00:30<01:29, 15.18it/s]
 30%|███       | 583/1939 [00:30<01:41, 13.36it/s]
 30%|███       | 585/1939 [00:30<01:55, 11.75it/s]
 30%|███       | 587/1939 [00:30<01:48, 12.49it/s]
 30%|███       | 589/1939 [00:30<01:48, 12.40it/s]
 30%|███       | 591/1939 [00:30<01:41, 13.34it/s]
 31%|███       | 593/1939 [00:31<01:57, 11.47it/s]
 31%|███       | 596/1939 [00:31<01:31, 14.61it/s]
 31%|███       | 601/1939 [00:31<01:28, 15.05it/s]
 31%|███       | 603/1939 [00:31<01:45, 12.63it/s]
 31%|███       | 605/1939 [00:32<01:45, 12.67it/s]
 31%|███▏      | 608/1939 [00:32<01:40, 13.20it/s]
 32%|███▏      | 611/1939 [00:32<01:51, 11.93it/s]
 32%|███▏      | 613/1939 [00:32<02:06, 10.52it/s]
 32%|███▏      | 615/1939 [00:33<02:21,  9.36it/s]
 32%|███▏      | 616/1939 [00:33<02:44,  8.04it/s]
 32%|███▏      | 617/1939 [00:33<03:07,  7.07it/s]
 32%|███▏      | 620/1939 [00:33<02:44,  8.04it/s]
 32%|███▏      | 622/1939 [00:34<02:43,  8.06it/s]
 32%|███▏      | 624/1939 [00:34<02:18,  9.52it/s]
 32%|███▏      | 629/1939 [00:34<01:41, 12.89it/s]
 33%|███▎      | 631/1939 [00:34<01:53, 11.53it/s]
 33%|███▎      | 633/1939 [00:34<01:59, 10.91it/s]
 33%|███▎      | 636/1939 [00:35<01:50, 11.79it/s]
 33%|███▎      | 638/1939 [00:35<02:12,  9.85it/s]
 33%|███▎      | 640/1939 [00:35<02:23,  9.03it/s]
 33%|███▎      | 641/1939 [00:35<02:32,  8.53it/s]
 33%|███▎      | 643/1939 [00:36<02:21,  9.14it/s]
 33%|███▎      | 645/1939 [00:36<01:59, 10.82it/s]
 33%|███▎      | 649/1939 [00:36<01:30, 14.28it/s]
 34%|███▎      | 652/1939 [00:36<01:18, 16.37it/s]
 34%|███▍      | 656/1939 [00:36<01:19, 16.08it/s]
 34%|███▍      | 658/1939 [00:36<01:17, 16.52it/s]
 34%|███▍      | 660/1939 [00:37<01:39, 12.85it/s]
 34%|███▍      | 663/1939 [00:37<01:20, 15.81it/s]
 34%|███▍      | 665/1939 [00:37<01:33, 13.67it/s]
 34%|███▍      | 667/1939 [00:37<01:51, 11.46it/s]
 35%|███▍      | 670/1939 [00:37<01:28, 14.36it/s]
 35%|███▍      | 672/1939 [00:38<01:45, 11.97it/s]
 35%|███▍      | 674/1939 [00:38<01:38, 12.84it/s]
 35%|███▍      | 676/1939 [00:38<02:02, 10.31it/s]
 35%|███▌      | 679/1939 [00:38<01:38, 12.82it/s]
 35%|███▌      | 681/1939 [00:38<01:58, 10.58it/s]
 35%|███▌      | 684/1939 [00:39<01:33, 13.48it/s]
 35%|███▌      | 687/1939 [00:39<01:42, 12.17it/s]
 36%|███▌      | 689/1939 [00:39<02:07,  9.80it/s]
 36%|███▌      | 691/1939 [00:39<01:52, 11.12it/s]
 36%|███▌      | 693/1939 [00:39<01:56, 10.66it/s]
 36%|███▌      | 695/1939 [00:40<01:46, 11.68it/s]
 36%|███▌      | 701/1939 [00:40<01:00, 20.62it/s]
 36%|███▋      | 706/1939 [00:40<00:48, 25.47it/s]
 37%|███▋      | 710/1939 [00:40<00:57, 21.42it/s]
 37%|███▋      | 713/1939 [00:40<00:59, 20.74it/s]
 37%|███▋      | 719/1939 [00:40<00:43, 28.23it/s]
 37%|███▋      | 723/1939 [00:40<00:44, 27.45it/s]
 37%|███▋      | 727/1939 [00:41<00:40, 29.72it/s]
 38%|███▊      | 731/1939 [00:41<00:52, 23.17it/s]
 38%|███▊      | 734/1939 [00:41<01:09, 17.45it/s]
 38%|███▊      | 738/1939 [00:41<00:58, 20.52it/s]
 38%|███▊      | 745/1939 [00:41<00:43, 27.54it/s]
 39%|███▊      | 749/1939 [00:42<00:53, 22.42it/s]
 39%|███▉      | 752/1939 [00:42<00:52, 22.63it/s]
 39%|███▉      | 755/1939 [00:42<01:00, 19.61it/s]
 39%|███▉      | 758/1939 [00:42<01:14, 15.81it/s]
 39%|███▉      | 760/1939 [00:43<01:29, 13.15it/s]
 39%|███▉      | 762/1939 [00:43<01:25, 13.73it/s]
 39%|███▉      | 764/1939 [00:43<01:51, 10.58it/s]
 40%|███▉      | 766/1939 [00:43<01:54, 10.28it/s]
 40%|███▉      | 768/1939 [00:44<02:12,  8.84it/s]
 40%|███▉      | 770/1939 [00:44<02:14,  8.67it/s]
 40%|███▉      | 772/1939 [00:44<02:17,  8.49it/s]
 40%|███▉      | 773/1939 [00:44<02:34,  7.57it/s]
 40%|███▉      | 775/1939 [00:44<02:09,  9.01it/s]
 40%|████      | 776/1939 [00:45<02:26,  7.91it/s]
 40%|████      | 779/1939 [00:45<01:43, 11.25it/s]
 40%|████      | 781/1939 [00:45<02:00,  9.64it/s]
 40%|████      | 784/1939 [00:45<01:52, 10.30it/s]
 41%|████      | 786/1939 [00:45<01:42, 11.24it/s]
 41%|████      | 788/1939 [00:46<01:52, 10.19it/s]
 41%|████      | 790/1939 [00:46<01:59,  9.64it/s]
 41%|████      | 793/1939 [00:46<01:30, 12.67it/s]
 41%|████      | 796/1939 [00:46<01:12, 15.66it/s]
 41%|████      | 798/1939 [00:47<01:55,  9.89it/s]
 41%|████▏     | 800/1939 [00:47<01:48, 10.45it/s]
 41%|████▏     | 803/1939 [00:47<01:28, 12.88it/s]
 42%|████▏     | 805/1939 [00:47<01:24, 13.44it/s]
 42%|████▏     | 807/1939 [00:47<01:50, 10.26it/s]
 42%|████▏     | 809/1939 [00:48<02:01,  9.32it/s]
 42%|████▏     | 811/1939 [00:48<01:46, 10.60it/s]
 42%|████▏     | 813/1939 [00:48<01:49, 10.25it/s]
 42%|████▏     | 815/1939 [00:48<02:00,  9.37it/s]
 42%|████▏     | 817/1939 [00:48<02:04,  9.04it/s]
 42%|████▏     | 818/1939 [00:49<02:25,  7.69it/s]
 42%|████▏     | 820/1939 [00:49<02:25,  7.72it/s]
 42%|████▏     | 821/1939 [00:49<02:44,  6.79it/s]
 42%|████▏     | 822/1939 [00:49<03:04,  6.05it/s]
 42%|████▏     | 824/1939 [00:49<02:21,  7.86it/s]
 43%|████▎     | 825/1939 [00:50<02:51,  6.49it/s]
 43%|████▎     | 827/1939 [00:50<02:09,  8.62it/s]
 43%|████▎     | 832/1939 [00:50<01:10, 15.78it/s]
 43%|████▎     | 837/1939 [00:50<00:49, 22.47it/s]
 43%|████▎     | 842/1939 [00:50<00:38, 28.18it/s]
 44%|████▎     | 848/1939 [00:50<00:31, 34.15it/s]
 44%|████▍     | 854/1939 [00:50<00:27, 39.11it/s]
 44%|████▍     | 859/1939 [00:50<00:26, 40.80it/s]
 45%|████▍     | 864/1939 [00:51<00:37, 28.88it/s]
 45%|████▍     | 868/1939 [00:51<00:39, 27.44it/s]
 45%|████▌     | 873/1939 [00:51<00:33, 31.83it/s]
 45%|████▌     | 880/1939 [00:51<00:27, 38.57it/s]
 46%|████▌     | 885/1939 [00:52<00:42, 24.95it/s]
 46%|████▌     | 889/1939 [00:52<00:41, 25.61it/s]
 46%|████▌     | 894/1939 [00:52<00:35, 29.67it/s]
 46%|████▋     | 899/1939 [00:52<00:46, 22.51it/s]
 47%|████▋     | 903/1939 [00:52<00:42, 24.36it/s]
 47%|████▋     | 910/1939 [00:53<00:42, 24.27it/s]
 47%|████▋     | 913/1939 [00:53<00:43, 23.85it/s]
 47%|████▋     | 918/1939 [00:53<00:49, 20.70it/s]
 47%|████▋     | 921/1939 [00:53<00:46, 21.88it/s]
 48%|████▊     | 927/1939 [00:53<00:47, 21.47it/s]
 48%|████▊     | 930/1939 [00:54<00:46, 21.57it/s]
 48%|████▊     | 937/1939 [00:54<00:33, 30.18it/s]
 49%|████▊     | 942/1939 [00:54<00:29, 33.91it/s]
 49%|████▉     | 947/1939 [00:54<00:29, 33.30it/s]
 49%|████▉     | 951/1939 [00:54<00:28, 34.09it/s]
 49%|████▉     | 957/1939 [00:54<00:24, 39.66it/s]
 50%|████▉     | 962/1939 [00:54<00:23, 41.93it/s]
 50%|████▉     | 967/1939 [00:54<00:22, 43.35it/s]
 50%|█████     | 972/1939 [00:55<00:48, 20.11it/s]
 50%|█████     | 976/1939 [00:55<00:56, 17.01it/s]
 50%|█████     | 979/1939 [00:55<01:02, 15.30it/s]
 51%|█████     | 982/1939 [00:56<01:23, 11.41it/s]
 51%|█████     | 985/1939 [00:56<01:11, 13.29it/s]
 51%|█████     | 990/1939 [00:56<01:05, 14.43it/s]
 51%|█████     | 992/1939 [00:57<01:15, 12.57it/s]
 51%|█████▏    | 995/1939 [00:57<01:04, 14.61it/s]
 52%|█████▏    | 999/1939 [00:57<01:06, 14.17it/s]
 52%|█████▏    | 1001/1939 [00:57<01:17, 12.16it/s]
 52%|█████▏    | 1003/1939 [00:58<01:27, 10.64it/s]
 52%|█████▏    | 1006/1939 [00:58<01:28, 10.48it/s]
 52%|█████▏    | 1008/1939 [00:58<01:41,  9.22it/s]
 52%|█████▏    | 1010/1939 [00:58<01:42,  9.07it/s]
 52%|█████▏    | 1011/1939 [00:59<01:53,  8.21it/s]
 52%|█████▏    | 1013/1939 [00:59<01:44,  8.82it/s]
 52%|█████▏    | 1015/1939 [00:59<01:47,  8.57it/s]
 52%|█████▏    | 1016/1939 [00:59<01:45,  8.76it/s]
 53%|█████▎    | 1018/1939 [00:59<01:41,  9.04it/s]
 53%|█████▎    | 1019/1939 [01:00<01:57,  7.84it/s]
 53%|█████▎    | 1021/1939 [01:00<01:35,  9.66it/s]
 53%|█████▎    | 1023/1939 [01:00<01:38,  9.27it/s]
 53%|█████▎    | 1027/1939 [01:00<01:24, 10.82it/s]
 53%|█████▎    | 1029/1939 [01:00<01:15, 11.97it/s]
 53%|█████▎    | 1034/1939 [01:00<00:48, 18.63it/s]
 54%|█████▎    | 1040/1939 [01:01<00:33, 26.77it/s]
 54%|█████▍    | 1045/1939 [01:01<00:40, 21.90it/s]
 54%|█████▍    | 1048/1939 [01:01<01:00, 14.76it/s]
 54%|█████▍    | 1051/1939 [01:02<01:07, 13.21it/s]
 54%|█████▍    | 1053/1939 [01:02<01:27, 10.15it/s]
 54%|█████▍    | 1055/1939 [01:02<01:38,  9.02it/s]
 55%|█████▍    | 1057/1939 [01:03<02:11,  6.70it/s]
 55%|█████▍    | 1059/1939 [01:03<02:03,  7.14it/s]
 55%|█████▍    | 1060/1939 [01:03<02:10,  6.75it/s]
 55%|█████▍    | 1062/1939 [01:03<01:47,  8.15it/s]
 55%|█████▌    | 1067/1939 [01:03<01:00, 14.36it/s]
 55%|█████▌    | 1070/1939 [01:04<01:11, 12.10it/s]
 55%|█████▌    | 1074/1939 [01:04<01:07, 12.91it/s]
 56%|█████▌    | 1077/1939 [01:04<01:01, 14.07it/s]
 56%|█████▌    | 1079/1939 [01:04<00:58, 14.69it/s]
 56%|█████▌    | 1081/1939 [01:05<01:14, 11.44it/s]
 56%|█████▌    | 1084/1939 [01:05<01:02, 13.70it/s]
 56%|█████▌    | 1086/1939 [01:05<00:59, 14.22it/s]
 56%|█████▌    | 1089/1939 [01:05<01:01, 13.82it/s]
 56%|█████▋    | 1091/1939 [01:05<01:15, 11.27it/s]
 56%|█████▋    | 1093/1939 [01:06<01:24, 10.04it/s]
 56%|█████▋    | 1095/1939 [01:06<01:50,  7.66it/s]
 57%|█████▋    | 1097/1939 [01:06<01:48,  7.74it/s]
 57%|█████▋    | 1099/1939 [01:06<01:32,  9.10it/s]
 57%|█████▋    | 1105/1939 [01:07<01:04, 12.98it/s]
 57%|█████▋    | 1107/1939 [01:07<01:05, 12.71it/s]
 57%|█████▋    | 1109/1939 [01:07<01:15, 10.94it/s]
 57%|█████▋    | 1111/1939 [01:07<01:09, 11.90it/s]
 57%|█████▋    | 1113/1939 [01:08<01:17, 10.63it/s]
 58%|█████▊    | 1115/1939 [01:08<01:26,  9.48it/s]
 58%|█████▊    | 1120/1939 [01:08<00:53, 15.26it/s]
 58%|█████▊    | 1125/1939 [01:08<00:38, 21.12it/s]
 58%|█████▊    | 1130/1939 [01:08<00:31, 26.05it/s]
 58%|█████▊    | 1134/1939 [01:09<00:39, 20.28it/s]
 59%|█████▊    | 1137/1939 [01:09<00:41, 19.34it/s]
 59%|█████▉    | 1141/1939 [01:09<00:48, 16.36it/s]
 59%|█████▉    | 1144/1939 [01:09<00:48, 16.30it/s]
 59%|█████▉    | 1146/1939 [01:09<00:57, 13.72it/s]
 59%|█████▉    | 1148/1939 [01:10<01:08, 11.56it/s]
 59%|█████▉    | 1150/1939 [01:10<01:15, 10.39it/s]
 59%|█████▉    | 1153/1939 [01:10<01:14, 10.52it/s]
 60%|█████▉    | 1155/1939 [01:10<01:06, 11.87it/s]
 60%|█████▉    | 1158/1939 [01:11<01:05, 11.86it/s]
 60%|█████▉    | 1160/1939 [01:11<01:01, 12.59it/s]
 60%|█████▉    | 1162/1939 [01:11<01:11, 10.83it/s]
 60%|██████    | 1164/1939 [01:11<01:19,  9.69it/s]
 60%|██████    | 1168/1939 [01:11<00:54, 14.12it/s]
 60%|██████    | 1172/1939 [01:12<00:54, 14.14it/s]
 61%|██████    | 1175/1939 [01:12<00:48, 15.84it/s]
 61%|██████    | 1180/1939 [01:12<00:49, 15.46it/s]
 61%|██████    | 1182/1939 [01:12<00:59, 12.71it/s]
 61%|██████    | 1184/1939 [01:13<01:08, 10.98it/s]
 61%|██████    | 1187/1939 [01:13<00:55, 13.51it/s]
 61%|██████▏   | 1189/1939 [01:13<00:52, 14.23it/s]
 61%|██████▏   | 1191/1939 [01:13<00:58, 12.69it/s]
 62%|██████▏   | 1193/1939 [01:13<01:07, 11.09it/s]
 62%|██████▏   | 1195/1939 [01:13<01:02, 11.91it/s]
 62%|██████▏   | 1197/1939 [01:14<01:15,  9.88it/s]
 62%|██████▏   | 1201/1939 [01:14<00:50, 14.72it/s]
 62%|██████▏   | 1208/1939 [01:14<00:29, 24.48it/s]
 63%|██████▎   | 1214/1939 [01:14<00:23, 30.94it/s]
 63%|██████▎   | 1218/1939 [01:15<00:40, 17.98it/s]
 63%|██████▎   | 1221/1939 [01:15<00:47, 15.01it/s]
 63%|██████▎   | 1224/1939 [01:15<00:43, 16.59it/s]
 63%|██████▎   | 1227/1939 [01:15<00:55, 12.89it/s]
 63%|██████▎   | 1229/1939 [01:16<01:01, 11.62it/s]
 63%|██████▎   | 1231/1939 [01:16<00:55, 12.65it/s]
 64%|██████▎   | 1233/1939 [01:16<01:13,  9.61it/s]
 64%|██████▎   | 1236/1939 [01:16<00:58, 11.97it/s]
 64%|██████▍   | 1239/1939 [01:16<00:57, 12.18it/s]
 64%|██████▍   | 1241/1939 [01:17<00:55, 12.58it/s]
 64%|██████▍   | 1243/1939 [01:17<00:51, 13.43it/s]
 64%|██████▍   | 1246/1939 [01:17<00:57, 11.99it/s]
 64%|██████▍   | 1248/1939 [01:17<01:11,  9.61it/s]
 64%|██████▍   | 1250/1939 [01:17<01:02, 11.02it/s]
 65%|██████▍   | 1252/1939 [01:18<01:12,  9.45it/s]
 65%|██████▍   | 1254/1939 [01:18<01:09,  9.79it/s]
 65%|██████▍   | 1256/1939 [01:18<01:01, 11.12it/s]
 65%|██████▍   | 1258/1939 [01:18<00:59, 11.48it/s]
 65%|██████▌   | 1261/1939 [01:18<00:47, 14.22it/s]
 65%|██████▌   | 1266/1939 [01:18<00:31, 21.17it/s]
 65%|██████▌   | 1270/1939 [01:19<00:27, 24.00it/s]
 66%|██████▌   | 1273/1939 [01:19<00:33, 19.65it/s]
 66%|██████▌   | 1276/1939 [01:19<00:32, 20.31it/s]
 66%|██████▌   | 1282/1939 [01:19<00:23, 28.38it/s]
 66%|██████▋   | 1287/1939 [01:19<00:20, 32.32it/s]
 67%|██████▋   | 1292/1939 [01:19<00:18, 35.48it/s]
 67%|██████▋   | 1296/1939 [01:20<00:27, 23.58it/s]
 67%|██████▋   | 1301/1939 [01:20<00:22, 27.76it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 320.72it/s]
 67%|██████▋   | 201/300 [07:55<29:19, 17.77s/it]

[[np.int64(0), False, 4], [np.int64(1), False, 8], [np.int64(2), False, 6], [np.int64(3), False, 1], [np.int64(4), False, 12], [np.int64(5), False, 0], [np.int64(7), False, 12], [np.int64(9), False, 8], [np.int64(10), False, 11], [np.int64(11), False, 2], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2498, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.1609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5111, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 202/300 [07:55<23:56, 14.66s/it]

tensor(12.1676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7469, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [07:56<14:36,  9.13s/it]

tensor(12.1804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9582, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9833, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0169, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [07:56<08:47,  5.61s/it]

tensor(12.1838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1719, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [07:56<05:34,  3.64s/it]

tensor(12.1751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0367, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2912, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1849, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3923, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [07:56<03:39,  2.44s/it]

tensor(12.1960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4267, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1994, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4472, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [07:56<02:27,  1.68s/it]

tensor(12.1965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4718, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [07:57<01:41,  1.18s/it]

tensor(12.1924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4953, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5212, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5139, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [07:57<01:10,  1.19it/s]

tensor(12.1802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4281, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [07:57<00:50,  1.64it/s]

tensor(12.1771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4691, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [07:57<00:36,  2.21it/s]

tensor(12.1747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5037, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5281, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5314, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [07:57<00:26,  2.90it/s]

tensor(12.1616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5301, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1563, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5305, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [07:58<00:20,  3.71it/s]

tensor(12.1519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5296, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [07:58<00:16,  4.62it/s]

tensor(12.1476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5328, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5366, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5407, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [07:58<00:12,  5.54it/s]

tensor(12.1346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5450, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1305, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5503, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [07:58<00:10,  6.44it/s]

tensor(12.1268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5512, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [07:58<00:09,  7.28it/s]

tensor(12.1232, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5560, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5569, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5584, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [07:59<00:08,  8.00it/s]

tensor(12.1135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5559, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5599, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [07:59<00:07,  8.59it/s]

tensor(12.1071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5637, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 238/300 [07:59<00:06,  9.07it/s]

tensor(12.1039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5640, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5664, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5660, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [07:59<00:06,  9.44it/s]

tensor(12.0954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5672, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0929, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5700, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [07:59<00:05,  9.73it/s]

tensor(12.0901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5740, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [07:59<00:05,  9.94it/s]

tensor(12.0877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5783, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0853, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5789, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0831, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5792, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [08:00<00:05, 10.06it/s]

tensor(12.0808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5797, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5799, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [08:00<00:05, 10.21it/s]

tensor(12.0766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5811, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [08:00<00:04, 10.27it/s]

tensor(12.0745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5851, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([119, 402, 103,  86, 187,  78, 210, 291, 123,  21,  30, 108,  33, 148])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 1/1939 [00:00<03:27,  9.35it/s]
  0%|          | 3/1939 [00:00<04:29,  7.18it/s]
  0%|          | 5/1939 [00:00<03:21,  9.62it/s]
  0%|          | 7/1939 [00:00<04:37,  6.96it/s]
  1%|          | 12/1939 [00:01<02:18, 13.92it/s]
  1%|          | 17/1939 [00:01<02:28, 12.97it/s]
  1%|          | 20/1939 [00:01<02:14, 14.24it/s]
  1%|          | 22/1939 [00:01<02:43, 11.75it/s]
  1%|▏         | 25/1939 [00:02<02:25, 13.13it/s]
  1%|▏         | 27/1939 [00:02<03:08, 10.14it/s]
  1%|▏         | 29/1939 [00:02<03:03, 10.39it/s]
  2%|▏         | 31/1939 [00:03<03:51,  8.25it/s]
  2%|▏         | 33/1939 [00:03<04:17,  7.40it/s]
  2%|▏         | 35/1939 [00:03<03:45,  8.42it/s]
  2%|▏         | 37/1939 [00:03<03:52,  8.18it/s]
  2%|▏         | 39/1939 [00:04<04:00,  7.91it/s]
  2%|▏         | 41/1939 [00:04<05:09,  6.13it/s]
  2%|▏         | 42/1939 [00:04<04:50,  6.53it/s]
  2%|▏         | 43/1939 [00:04<04:44,  6.66it/s]
  2%|▏         | 46/1939 [00:04<03:03, 10.33it/s]
  3%|▎         | 49/1939 [00:05<03:38,  8.66it/s]
  3%|▎         | 52/1939 [00:05<02:47, 11.29it/s]
  3%|▎         | 54/1939 [00:05<04:02,  7.78it/s]
  3%|▎         | 56/1939 [00:06<03:27,  9.06it/s]
  3%|▎         | 58/1939 [00:06<04:28,  7.00it/s]
  3%|▎         | 60/1939 [00:06<05:07,  6.10it/s]
  3%|▎         | 66/1939 [00:07<03:48,  8.21it/s]
  3%|▎         | 67/1939 [00:07<04:34,  6.82it/s]
  4%|▎         | 70/1939 [00:08<04:21,  7.14it/s]
  4%|▎         | 71/1939 [00:08<04:16,  7.27it/s]
  4%|▍         | 73/1939 [00:08<04:33,  6.81it/s]
  4%|▍         | 75/1939 [00:09<04:52,  6.38it/s]
  4%|▍         | 77/1939 [00:09<03:59,  7.78it/s]
  4%|▍         | 78/1939 [00:09<05:34,  5.57it/s]
  4%|▍         | 80/1939 [00:10<06:25,  4.83it/s]
  4%|▍         | 81/1939 [00:10<07:48,  3.96it/s]
 83%|████████▎ | 250/300 [08:13<00:04, 10.27it/s]
  4%|▍         | 84/1939 [00:11<08:41,  3.56it/s]
  4%|▍         | 85/1939 [00:11<07:31,  4.10it/s]
  4%|▍         | 86/1939 [00:12<09:02,  3.42it/s]
  4%|▍         | 87/1939 [00:12<10:03,  3.07it/s]
  5%|▍         | 90/1939 [00:12<05:29,  5.60it/s]
  5%|▍         | 93/1939 [00:13<05:15,  5.85it/s]
  5%|▍         | 94/1939 [00:13<06:38,  4.63it/s]
  5%|▍         | 96/1939 [00:13<05:15,  5.83it/s]
  5%|▌         | 100/1939 [00:14<03:57,  7.76it/s]
  5%|▌         | 101/1939 [00:14<04:31,  6.77it/s]
  5%|▌         | 104/1939 [00:14<03:17,  9.28it/s]
  5%|▌         | 106/1939 [00:14<03:44,  8.16it/s]
  6%|▌         | 109/1939 [00:14<02:48, 10.85it/s]
  6%|▌         | 111/1939 [00:15<03:15,  9.36it/s]
  6%|▌         | 113/1939 [00:15<02:49, 10.77it/s]
  6%|▌         | 115/1939 [00:15<02:36, 11.67it/s]
  6%|▌         | 118/1939 [00:15<02:35, 11.68it/s]
  6%|▌         | 120/1939 [00:15<02:55, 10.39it/s]
  6%|▋         | 122/1939 [00:16<03:00, 10.09it/s]
  6%|▋         | 124/1939 [00:16<02:38, 11.48it/s]
  6%|▋         | 126/1939 [00:16<02:45, 10.99it/s]
  7%|▋         | 128/1939 [00:16<02:25, 12.45it/s]
  7%|▋         | 132/1939 [00:17<02:59, 10.05it/s]
  7%|▋         | 135/1939 [00:17<02:24, 12.51it/s]
  7%|▋         | 137/1939 [00:17<04:16,  7.03it/s]
  7%|▋         | 141/1939 [00:17<02:51, 10.48it/s]
  7%|▋         | 143/1939 [00:18<03:46,  7.92it/s]
  7%|▋         | 145/1939 [00:19<05:36,  5.33it/s]
  8%|▊         | 147/1939 [00:19<05:42,  5.23it/s]
  8%|▊         | 151/1939 [00:19<03:37,  8.21it/s]
  8%|▊         | 153/1939 [00:19<03:54,  7.62it/s]
  8%|▊         | 155/1939 [00:20<03:44,  7.95it/s]
  8%|▊         | 157/1939 [00:20<04:20,  6.85it/s]
  8%|▊         | 159/1939 [00:20<04:19,  6.87it/s]
  8%|▊         | 160/1939 [00:21<05:51,  5.06it/s]
  8%|▊         | 162/1939 [00:21<04:29,  6.59it/s]
  8%|▊         | 164/1939 [00:21<05:07,  5.78it/s]
  9%|▊         | 165/1939 [00:22<05:55,  4.99it/s]
  9%|▊         | 169/1939 [00:22<03:18,  8.91it/s]
  9%|▉         | 171/1939 [00:22<03:44,  7.89it/s]
  9%|▉         | 173/1939 [00:22<03:07,  9.43it/s]
  9%|▉         | 179/1939 [00:23<02:29, 11.76it/s]
  9%|▉         | 181/1939 [00:23<02:28, 11.87it/s]
  9%|▉         | 183/1939 [00:23<02:50, 10.28it/s]
 10%|▉         | 185/1939 [00:23<02:36, 11.20it/s]
 10%|▉         | 188/1939 [00:23<02:09, 13.56it/s]
 10%|▉         | 191/1939 [00:24<01:48, 16.08it/s]
 10%|█         | 197/1939 [00:24<02:06, 13.80it/s]
 10%|█         | 200/1939 [00:24<01:52, 15.45it/s]
 10%|█         | 202/1939 [00:25<02:42, 10.69it/s]
 11%|█         | 204/1939 [00:25<03:41,  7.84it/s]
 11%|█         | 206/1939 [00:26<04:30,  6.42it/s]
 11%|█         | 207/1939 [00:26<05:14,  5.51it/s]
 11%|█         | 209/1939 [00:26<04:07,  6.98it/s]
 11%|█         | 211/1939 [00:26<04:24,  6.52it/s]
 11%|█         | 215/1939 [00:27<04:03,  7.07it/s]
 11%|█▏        | 219/1939 [00:27<03:36,  7.95it/s]
 11%|█▏        | 220/1939 [00:28<04:17,  6.67it/s]
 12%|█▏        | 223/1939 [00:28<03:11,  8.97it/s]
 12%|█▏        | 225/1939 [00:28<03:56,  7.25it/s]
 12%|█▏        | 227/1939 [00:28<04:07,  6.93it/s]
 12%|█▏        | 228/1939 [00:29<05:32,  5.15it/s]
 12%|█▏        | 229/1939 [00:29<06:13,  4.57it/s]
 12%|█▏        | 230/1939 [00:30<07:25,  3.83it/s]
 12%|█▏        | 232/1939 [00:30<06:34,  4.33it/s]
 12%|█▏        | 233/1939 [00:30<07:38,  3.72it/s]
 12%|█▏        | 234/1939 [00:31<07:38,  3.72it/s]
 12%|█▏        | 236/1939 [00:31<05:50,  4.86it/s]
 12%|█▏        | 237/1939 [00:31<05:54,  4.80it/s]
 12%|█▏        | 239/1939 [00:31<05:28,  5.17it/s]
 12%|█▏        | 240/1939 [00:32<05:33,  5.09it/s]
 12%|█▏        | 241/1939 [00:32<05:04,  5.57it/s]
 12%|█▏        | 242/1939 [00:32<05:29,  5.16it/s]
 13%|█▎        | 244/1939 [00:32<04:05,  6.90it/s]
 13%|█▎        | 246/1939 [00:32<03:43,  7.56it/s]
 13%|█▎        | 247/1939 [00:33<03:53,  7.25it/s]
 13%|█▎        | 248/1939 [00:33<05:30,  5.12it/s]
 13%|█▎        | 250/1939 [00:33<03:56,  7.15it/s]
 13%|█▎        | 256/1939 [00:33<01:47, 15.61it/s]
 13%|█▎        | 259/1939 [00:33<02:03, 13.59it/s]
 13%|█▎        | 261/1939 [00:34<02:38, 10.62it/s]
 14%|█▎        | 263/1939 [00:34<03:39,  7.63it/s]
 14%|█▎        | 265/1939 [00:34<03:08,  8.89it/s]
 14%|█▍        | 268/1939 [00:35<02:28, 11.22it/s]
 14%|█▍        | 274/1939 [00:35<01:29, 18.63it/s]
 14%|█▍        | 277/1939 [00:35<02:20, 11.79it/s]
 14%|█▍        | 280/1939 [00:35<02:05, 13.17it/s]
 15%|█▍        | 285/1939 [00:36<02:03, 13.38it/s]
 15%|█▍        | 287/1939 [00:36<02:01, 13.59it/s]
 15%|█▍        | 289/1939 [00:36<01:55, 14.27it/s]
 15%|█▌        | 293/1939 [00:36<01:28, 18.51it/s]
 15%|█▌        | 300/1939 [00:36<00:57, 28.60it/s]
 16%|█▌        | 308/1939 [00:36<00:41, 39.12it/s]
 16%|█▌        | 314/1939 [00:36<00:37, 43.51it/s]
 17%|█▋        | 320/1939 [00:37<00:40, 40.37it/s]
 17%|█▋        | 325/1939 [00:38<02:47,  9.61it/s]
 17%|█▋        | 329/1939 [00:39<03:35,  7.46it/s]
 17%|█▋        | 332/1939 [00:40<03:59,  6.72it/s]
 17%|█▋        | 334/1939 [00:40<04:04,  6.55it/s]
 17%|█▋        | 336/1939 [00:40<04:09,  6.44it/s]
 17%|█▋        | 338/1939 [00:41<04:54,  5.43it/s]
 17%|█▋        | 339/1939 [00:41<05:28,  4.87it/s]
 18%|█▊        | 340/1939 [00:42<05:58,  4.46it/s]
 18%|█▊        | 342/1939 [00:42<05:35,  4.76it/s]
 18%|█▊        | 343/1939 [00:42<06:03,  4.39it/s]
 18%|█▊        | 345/1939 [00:43<05:46,  4.60it/s]
 18%|█▊        | 347/1939 [00:43<05:28,  4.84it/s]
 18%|█▊        | 350/1939 [00:43<04:41,  5.65it/s]
 18%|█▊        | 351/1939 [00:44<04:59,  5.30it/s]
 18%|█▊        | 352/1939 [00:44<05:28,  4.83it/s]
 18%|█▊        | 354/1939 [00:44<05:18,  4.98it/s]
 18%|█▊        | 355/1939 [00:44<04:46,  5.52it/s]
 18%|█▊        | 356/1939 [00:45<05:13,  5.05it/s]
 18%|█▊        | 358/1939 [00:45<03:49,  6.90it/s]
 19%|█▊        | 359/1939 [00:45<04:04,  6.45it/s]
 19%|█▊        | 361/1939 [00:45<03:12,  8.18it/s]
 19%|█▊        | 363/1939 [00:46<04:30,  5.83it/s]
 19%|█▉        | 365/1939 [00:46<03:29,  7.52it/s]
 19%|█▉        | 367/1939 [00:46<03:33,  7.38it/s]
 19%|█▉        | 368/1939 [00:47<04:52,  5.36it/s]
 19%|█▉        | 371/1939 [00:47<03:12,  8.16it/s]
 19%|█▉        | 373/1939 [00:47<03:38,  7.18it/s]
 19%|█▉        | 375/1939 [00:47<03:54,  6.67it/s]
 19%|█▉        | 376/1939 [00:48<04:40,  5.58it/s]
 19%|█▉        | 377/1939 [00:48<04:56,  5.27it/s]
 19%|█▉        | 378/1939 [00:48<04:27,  5.83it/s]
 20%|█▉        | 381/1939 [00:49<04:35,  5.66it/s]
 20%|█▉        | 383/1939 [00:49<03:35,  7.22it/s]
 20%|█▉        | 384/1939 [00:49<05:01,  5.16it/s]
 20%|█▉        | 385/1939 [00:49<05:50,  4.43it/s]
 20%|█▉        | 387/1939 [00:50<05:31,  4.69it/s]
 20%|██        | 388/1939 [00:50<05:13,  4.95it/s]
 20%|██        | 390/1939 [00:50<04:15,  6.06it/s]
 20%|██        | 392/1939 [00:50<03:19,  7.77it/s]
 20%|██        | 394/1939 [00:51<03:51,  6.68it/s]
 20%|██        | 395/1939 [00:51<04:00,  6.43it/s]
 20%|██        | 396/1939 [00:51<04:16,  6.01it/s]
 20%|██        | 397/1939 [00:52<05:55,  4.34it/s]
 21%|██        | 398/1939 [00:52<06:29,  3.95it/s]
 21%|██        | 399/1939 [00:52<07:11,  3.57it/s]
 21%|██        | 402/1939 [00:52<03:50,  6.66it/s]
 21%|██        | 404/1939 [00:52<03:20,  7.65it/s]
 21%|██        | 406/1939 [00:53<04:14,  6.02it/s]
 21%|██        | 407/1939 [00:53<05:31,  4.62it/s]
 21%|██        | 410/1939 [00:54<03:29,  7.29it/s]
 21%|██        | 412/1939 [00:54<03:23,  7.50it/s]
 21%|██▏       | 415/1939 [00:54<02:56,  8.62it/s]
 22%|██▏       | 417/1939 [00:55<03:45,  6.74it/s]
 22%|██▏       | 419/1939 [00:55<04:18,  5.88it/s]
 22%|██▏       | 421/1939 [00:55<03:27,  7.33it/s]
 22%|██▏       | 423/1939 [00:56<04:09,  6.08it/s]
 22%|██▏       | 425/1939 [00:56<03:19,  7.60it/s]
 22%|██▏       | 427/1939 [00:56<03:54,  6.46it/s]
 22%|██▏       | 428/1939 [00:56<04:02,  6.23it/s]
 22%|██▏       | 430/1939 [00:56<03:16,  7.68it/s]
 22%|██▏       | 432/1939 [00:57<03:48,  6.60it/s]
 22%|██▏       | 434/1939 [00:57<03:02,  8.24it/s]
 22%|██▏       | 436/1939 [00:57<03:20,  7.51it/s]
 23%|██▎       | 437/1939 [00:57<03:43,  6.73it/s]
 23%|██▎       | 440/1939 [00:58<02:27, 10.17it/s]
 23%|██▎       | 444/1939 [00:58<01:37, 15.27it/s]
 23%|██▎       | 450/1939 [00:58<01:26, 17.25it/s]
 23%|██▎       | 453/1939 [00:58<01:40, 14.82it/s]
 23%|██▎       | 455/1939 [00:58<01:35, 15.56it/s]
 24%|██▎       | 457/1939 [00:58<01:37, 15.15it/s]
 24%|██▎       | 459/1939 [00:59<01:35, 15.46it/s]
 24%|██▍       | 462/1939 [00:59<01:21, 18.11it/s]
 24%|██▍       | 466/1939 [00:59<01:19, 18.63it/s]
 24%|██▍       | 469/1939 [00:59<01:12, 20.15it/s]
 24%|██▍       | 472/1939 [00:59<01:06, 21.93it/s]
 24%|██▍       | 475/1939 [01:00<01:53, 12.93it/s]
 25%|██▍       | 479/1939 [01:00<02:05, 11.60it/s]
 25%|██▍       | 482/1939 [01:00<01:52, 12.91it/s]
 25%|██▌       | 485/1939 [01:00<01:34, 15.36it/s]
 25%|██▌       | 489/1939 [01:00<01:29, 16.18it/s]
 25%|██▌       | 491/1939 [01:01<01:28, 16.32it/s]
 25%|██▌       | 493/1939 [01:01<02:18, 10.44it/s]
 26%|██▌       | 495/1939 [01:01<02:08, 11.24it/s]
 26%|██▌       | 497/1939 [01:01<02:01, 11.91it/s]
 26%|██▌       | 500/1939 [01:01<01:42, 14.00it/s]
 26%|██▌       | 505/1939 [01:02<01:10, 20.30it/s]
 26%|██▋       | 510/1939 [01:02<00:54, 26.46it/s]
 27%|██▋       | 514/1939 [01:02<01:20, 17.77it/s]
 27%|██▋       | 517/1939 [01:02<01:41, 13.98it/s]
 27%|██▋       | 520/1939 [01:03<03:08,  7.51it/s]
 27%|██▋       | 522/1939 [01:04<03:13,  7.33it/s]
 27%|██▋       | 524/1939 [01:04<03:27,  6.81it/s]
 27%|██▋       | 526/1939 [01:04<03:41,  6.38it/s]
 27%|██▋       | 527/1939 [01:05<03:52,  6.08it/s]
 27%|██▋       | 529/1939 [01:05<03:24,  6.91it/s]
 27%|██▋       | 531/1939 [01:05<03:11,  7.35it/s]
 27%|██▋       | 533/1939 [01:05<03:18,  7.09it/s]
 28%|██▊       | 534/1939 [01:05<03:18,  7.08it/s]
 28%|██▊       | 536/1939 [01:06<03:38,  6.41it/s]
 28%|██▊       | 537/1939 [01:06<04:46,  4.89it/s]
 28%|██▊       | 540/1939 [01:06<03:03,  7.63it/s]
 28%|██▊       | 546/1939 [01:07<02:33,  9.05it/s]
 28%|██▊       | 548/1939 [01:07<02:19,  9.95it/s]
 28%|██▊       | 551/1939 [01:08<02:42,  8.52it/s]
 29%|██▊       | 553/1939 [01:08<02:24,  9.57it/s]
 29%|██▊       | 556/1939 [01:08<02:48,  8.22it/s]
 29%|██▉       | 559/1939 [01:08<02:13, 10.37it/s]
 29%|██▉       | 562/1939 [01:09<02:40,  8.57it/s]
 29%|██▉       | 564/1939 [01:09<03:25,  6.70it/s]
 29%|██▉       | 567/1939 [01:09<02:41,  8.51it/s]
 29%|██▉       | 571/1939 [01:09<01:52, 12.15it/s]
 30%|██▉       | 574/1939 [01:10<02:58,  7.64it/s]
 30%|██▉       | 576/1939 [01:11<03:08,  7.22it/s]
 30%|██▉       | 579/1939 [01:11<02:50,  7.98it/s]
 30%|██▉       | 581/1939 [01:11<02:52,  7.85it/s]
 30%|███       | 583/1939 [01:12<03:14,  6.97it/s]
 30%|███       | 584/1939 [01:12<03:24,  6.64it/s]
 30%|███       | 586/1939 [01:12<03:00,  7.49it/s]
 30%|███       | 588/1939 [01:12<02:31,  8.94it/s]
 30%|███       | 590/1939 [01:12<02:30,  8.95it/s]
 31%|███       | 592/1939 [01:13<03:42,  6.05it/s]
 31%|███       | 595/1939 [01:13<02:35,  8.64it/s]
 31%|███       | 597/1939 [01:13<02:44,  8.18it/s]
 31%|███       | 599/1939 [01:14<03:20,  6.69it/s]
 31%|███       | 600/1939 [01:14<04:09,  5.38it/s]
 31%|███       | 601/1939 [01:14<05:16,  4.23it/s]
 31%|███       | 603/1939 [01:15<04:09,  5.35it/s]
 31%|███       | 605/1939 [01:15<03:56,  5.64it/s]
 31%|███▏      | 607/1939 [01:15<03:31,  6.31it/s]
 31%|███▏      | 609/1939 [01:16<03:29,  6.35it/s]
 32%|███▏      | 611/1939 [01:16<02:48,  7.88it/s]
 32%|███▏      | 613/1939 [01:16<03:59,  5.54it/s]
 32%|███▏      | 614/1939 [01:17<04:16,  5.16it/s]
 32%|███▏      | 615/1939 [01:17<04:23,  5.03it/s]
 32%|███▏      | 616/1939 [01:17<05:30,  4.01it/s]
 32%|███▏      | 618/1939 [01:18<05:27,  4.03it/s]
 32%|███▏      | 619/1939 [01:18<05:44,  3.83it/s]
 32%|███▏      | 620/1939 [01:18<05:47,  3.80it/s]
 32%|███▏      | 621/1939 [01:19<06:36,  3.32it/s]
 32%|███▏      | 622/1939 [01:19<05:52,  3.73it/s]
 32%|███▏      | 624/1939 [01:19<03:57,  5.54it/s]
 32%|███▏      | 626/1939 [01:19<02:53,  7.58it/s]
 32%|███▏      | 629/1939 [01:19<02:56,  7.43it/s]
 32%|███▏      | 630/1939 [01:20<03:22,  6.46it/s]
 33%|███▎      | 632/1939 [01:20<02:55,  7.43it/s]
 33%|███▎      | 634/1939 [01:20<02:20,  9.28it/s]
 33%|███▎      | 636/1939 [01:20<02:46,  7.81it/s]
 33%|███▎      | 638/1939 [01:21<03:06,  6.98it/s]
 33%|███▎      | 641/1939 [01:21<02:45,  7.83it/s]
 33%|███▎      | 643/1939 [01:21<02:19,  9.29it/s]
 33%|███▎      | 648/1939 [01:21<01:23, 15.46it/s]
 34%|███▎      | 651/1939 [01:22<02:15,  9.50it/s]
 34%|███▎      | 653/1939 [01:22<02:09,  9.96it/s]
 34%|███▍      | 655/1939 [01:22<02:31,  8.48it/s]
 34%|███▍      | 657/1939 [01:23<03:04,  6.96it/s]
 34%|███▍      | 659/1939 [01:23<04:16,  4.99it/s]
 34%|███▍      | 661/1939 [01:24<03:23,  6.29it/s]
 34%|███▍      | 665/1939 [01:24<02:41,  7.88it/s]
 34%|███▍      | 667/1939 [01:24<02:41,  7.87it/s]
 35%|███▍      | 669/1939 [01:24<02:28,  8.54it/s]
 35%|███▍      | 672/1939 [01:25<02:33,  8.23it/s]
 35%|███▍      | 673/1939 [01:25<03:25,  6.15it/s]
 35%|███▍      | 676/1939 [01:25<02:26,  8.62it/s]
 35%|███▌      | 680/1939 [01:26<02:27,  8.54it/s]
 35%|███▌      | 682/1939 [01:26<02:10,  9.63it/s]
 35%|███▌      | 684/1939 [01:26<02:48,  7.45it/s]
 35%|███▌      | 687/1939 [01:27<03:06,  6.73it/s]
 36%|███▌      | 689/1939 [01:27<03:45,  5.54it/s]
 36%|███▌      | 692/1939 [01:28<03:39,  5.69it/s]
 36%|███▌      | 693/1939 [01:28<04:22,  4.75it/s]
 36%|███▌      | 696/1939 [01:29<03:42,  5.60it/s]
 36%|███▌      | 698/1939 [01:29<03:01,  6.84it/s]
 36%|███▌      | 699/1939 [01:29<03:36,  5.74it/s]
 36%|███▌      | 701/1939 [01:29<02:49,  7.29it/s]
 36%|███▋      | 704/1939 [01:29<01:59, 10.30it/s]
 37%|███▋      | 708/1939 [01:30<01:41, 12.13it/s]
 37%|███▋      | 710/1939 [01:30<01:32, 13.30it/s]
 37%|███▋      | 712/1939 [01:30<02:01, 10.12it/s]
 37%|███▋      | 714/1939 [01:30<01:46, 11.53it/s]
 37%|███▋      | 716/1939 [01:30<01:37, 12.58it/s]
 37%|███▋      | 720/1939 [01:30<01:08, 17.76it/s]
 37%|███▋      | 723/1939 [01:31<01:24, 14.36it/s]
 37%|███▋      | 725/1939 [01:31<01:22, 14.80it/s]
 38%|███▊      | 729/1939 [01:31<01:08, 17.64it/s]
 38%|███▊      | 731/1939 [01:31<01:57, 10.32it/s]
 38%|███▊      | 733/1939 [01:32<02:12,  9.10it/s]
 38%|███▊      | 735/1939 [01:32<02:16,  8.82it/s]
 38%|███▊      | 737/1939 [01:32<02:03,  9.72it/s]
 38%|███▊      | 739/1939 [01:32<02:09,  9.25it/s]
 38%|███▊      | 741/1939 [01:32<01:50, 10.87it/s]
 38%|███▊      | 743/1939 [01:33<01:47, 11.08it/s]
 38%|███▊      | 745/1939 [01:33<01:39, 12.00it/s]
 39%|███▊      | 747/1939 [01:33<02:35,  7.66it/s]
 39%|███▊      | 749/1939 [01:33<02:15,  8.79it/s]
 39%|███▉      | 752/1939 [01:34<01:53, 10.42it/s]
 39%|███▉      | 754/1939 [01:34<02:00,  9.81it/s]
 39%|███▉      | 756/1939 [01:35<03:17,  5.97it/s]
 39%|███▉      | 757/1939 [01:35<04:10,  4.71it/s]
 39%|███▉      | 759/1939 [01:35<03:17,  5.98it/s]
 39%|███▉      | 760/1939 [01:36<04:28,  4.39it/s]
 39%|███▉      | 761/1939 [01:36<04:42,  4.16it/s]
 39%|███▉      | 763/1939 [01:36<04:45,  4.13it/s]
 39%|███▉      | 764/1939 [01:37<04:28,  4.37it/s]
 40%|███▉      | 766/1939 [01:37<04:04,  4.81it/s]
 40%|███▉      | 767/1939 [01:37<03:54,  5.00it/s]
 40%|███▉      | 769/1939 [01:38<04:14,  4.60it/s]
 40%|███▉      | 770/1939 [01:38<05:15,  3.71it/s]
 40%|███▉      | 772/1939 [01:39<05:05,  3.82it/s]
 40%|███▉      | 774/1939 [01:39<04:30,  4.30it/s]
 40%|████      | 776/1939 [01:39<04:34,  4.23it/s]
 40%|████      | 777/1939 [01:40<05:13,  3.71it/s]
 40%|████      | 779/1939 [01:40<05:12,  3.71it/s]
 40%|████      | 780/1939 [01:41<05:42,  3.38it/s]
 40%|████      | 781/1939 [01:41<05:50,  3.30it/s]
 40%|████      | 783/1939 [01:41<04:00,  4.81it/s]
 40%|████      | 784/1939 [01:42<04:56,  3.90it/s]
 40%|████      | 785/1939 [01:42<05:11,  3.70it/s]
 41%|████      | 787/1939 [01:42<04:59,  3.85it/s]
 41%|████      | 789/1939 [01:43<05:04,  3.78it/s]
 41%|████      | 791/1939 [01:43<05:03,  3.78it/s]
 41%|████      | 793/1939 [01:44<03:47,  5.04it/s]
 41%|████      | 795/1939 [01:44<03:08,  6.06it/s]
 41%|████      | 796/1939 [01:44<03:00,  6.33it/s]
 41%|████      | 797/1939 [01:44<03:43,  5.10it/s]
 41%|████      | 798/1939 [01:45<04:54,  3.88it/s]
 41%|████▏     | 800/1939 [01:45<03:20,  5.69it/s]
 41%|████▏     | 801/1939 [01:45<04:28,  4.24it/s]
 41%|████▏     | 803/1939 [01:46<04:22,  4.32it/s]
 41%|████▏     | 804/1939 [01:46<04:26,  4.26it/s]
 42%|████▏     | 805/1939 [01:46<04:57,  3.81it/s]
 42%|████▏     | 806/1939 [01:47<04:42,  4.01it/s]
 42%|████▏     | 808/1939 [01:47<03:35,  5.26it/s]
 42%|████▏     | 809/1939 [01:47<04:29,  4.19it/s]
 42%|████▏     | 810/1939 [01:47<04:23,  4.29it/s]
 42%|████▏     | 812/1939 [01:48<03:30,  5.35it/s]
 42%|████▏     | 813/1939 [01:48<04:03,  4.63it/s]
 42%|████▏     | 814/1939 [01:48<04:30,  4.16it/s]
 42%|████▏     | 816/1939 [01:49<03:55,  4.77it/s]
 42%|████▏     | 817/1939 [01:49<04:05,  4.56it/s]
 42%|████▏     | 818/1939 [01:49<04:10,  4.47it/s]
 42%|████▏     | 819/1939 [01:49<04:28,  4.18it/s]
 42%|████▏     | 820/1939 [01:50<05:19,  3.50it/s]
 42%|████▏     | 821/1939 [01:50<05:26,  3.43it/s]
 42%|████▏     | 822/1939 [01:50<05:29,  3.39it/s]
 42%|████▏     | 823/1939 [01:51<05:22,  3.46it/s]
 42%|████▏     | 824/1939 [01:51<04:44,  3.92it/s]
 43%|████▎     | 825/1939 [01:51<04:04,  4.56it/s]
 43%|████▎     | 827/1939 [01:51<02:44,  6.76it/s]
 43%|████▎     | 829/1939 [01:51<02:07,  8.74it/s]
 43%|████▎     | 831/1939 [01:52<02:32,  7.27it/s]
 43%|████▎     | 833/1939 [01:52<02:44,  6.71it/s]
 43%|████▎     | 835/1939 [01:52<02:12,  8.31it/s]
 43%|████▎     | 837/1939 [01:52<02:29,  7.38it/s]
 43%|████▎     | 839/1939 [01:52<02:01,  9.02it/s]
 43%|████▎     | 841/1939 [01:53<01:57,  9.36it/s]
 43%|████▎     | 843/1939 [01:53<01:44, 10.51it/s]
 44%|████▎     | 845/1939 [01:53<01:32, 11.84it/s]
 44%|████▎     | 847/1939 [01:53<01:25, 12.84it/s]
 44%|████▍     | 849/1939 [01:53<01:42, 10.61it/s]
 44%|████▍     | 851/1939 [01:53<01:28, 12.30it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 319.12it/s]
 84%|████████▎ | 251/300 [12:23<37:59, 46.52s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 6], [np.int64(2), False, 4], [np.int64(3), False, 13], [np.int64(5), False, 8], [np.int64(7), False, 1], [np.int64(8), False, 11], [np.int64(9), False, 2], [np.int64(10), False, 8], [np.int64(12), False, 1], [np.int64(13), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6841, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.0717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8776, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [12:23<29:44, 37.18s/it]

tensor(12.0746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1249, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [12:24<16:48, 21.93s/it]

tensor(12.0811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2041, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0438, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3423, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0490, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4180, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [12:24<09:32, 13.01s/it]

tensor(12.0997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0524, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4618, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [12:24<05:46,  8.25s/it]

tensor(12.0957, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0535, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4835, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0538, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5140, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0849, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0542, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5295, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [12:24<03:37,  5.44s/it]

tensor(12.0824, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0543, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5290, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0541, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5420, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [12:24<02:19,  3.67s/it]

tensor(12.0801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0533, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5215, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [12:24<01:30,  2.53s/it]

tensor(12.0792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0520, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4825, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0504, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5088, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0486, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5199, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [12:25<00:59,  1.76s/it]

tensor(12.0789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0464, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5415, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5538, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [12:25<00:39,  1.25s/it]

tensor(12.0761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5787, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [12:25<00:26,  1.12it/s]

tensor(12.0737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0400, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5930, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6049, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [12:25<00:18,  1.54it/s]

tensor(12.0623, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6081, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6120, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [12:25<00:12,  2.07it/s]

tensor(12.0565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6074, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [12:26<00:08,  2.73it/s]

tensor(12.0545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5061, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5252, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5484, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [12:26<00:06,  3.52it/s]

tensor(12.0475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5621, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5571, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [12:26<00:04,  4.40it/s]

tensor(12.0444, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5505, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [12:26<00:03,  5.33it/s]

tensor(12.0428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5515, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0411, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5624, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5696, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [12:26<00:02,  6.23it/s]

tensor(12.0383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5820, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0382, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5864, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [12:27<00:01,  7.09it/s]

tensor(12.0381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5921, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [12:27<00:01,  7.87it/s]

tensor(12.0371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5998, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6024, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6049, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [12:27<00:01,  8.53it/s]

tensor(12.0288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6073, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6101, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [12:27<00:00,  9.06it/s]

tensor(12.0231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6099, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [12:27<00:00,  9.44it/s]

tensor(12.0211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6096, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0192, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6117, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0181, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6132, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [12:28<00:00,  9.73it/s]

tensor(12.0168, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6134, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [12:28<00:00, 10.01it/s]

tensor(12.0144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6130, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [12:28<00:00,  2.49s/it]

tensor(12.0128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6158, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0016155242919921875
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 5
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.460202833714
NMI         : 0.596453555075
Runtime     : 768.53 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed5

==============================================================================================================
PRAGA RUN | S2-E15 | seed=6
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 9.516e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29, 10.14it/s]

tensor(17.7154, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3743, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.7116, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2324, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:27, 10.86it/s]

tensor(17.6918, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3004, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6665, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5580, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6471, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9873, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:24, 11.82it/s]

tensor(17.6321, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5701, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6246, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2925, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6181, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1401, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.72it/s]

tensor(17.6107, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1012, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6013, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1647, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5904, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3197, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:00<00:22, 12.85it/s]

tensor(17.5744, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5587, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5527, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8723, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5301, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2536, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.11it/s]

tensor(17.5073, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6961, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4825, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1943, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4573, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7416, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:21, 13.17it/s]

tensor(17.4300, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4001, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9670, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3678, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6365, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:21, 13.20it/s]

tensor(17.3328, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3392, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2949, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0717, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2519, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8311, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:01<00:20, 13.24it/s]

tensor(17.2061, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6149, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1560, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1006, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2455, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.23it/s]

tensor(17.0433, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0890, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9481, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9174, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8220, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:20, 13.20it/s]

tensor(16.8503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7095, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7790, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6084, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5188, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:20, 13.28it/s]

tensor(16.6236, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4387, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3675, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4464, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3044, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:02<00:19, 13.25it/s]

tensor(16.3485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2494, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2452, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2006, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1590, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.24it/s]

tensor(16.0242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0952, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0725, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.26it/s]

tensor(15.6669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0556, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0436, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:19, 13.25it/s]

tensor(15.3274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:18, 13.26it/s]

tensor(15.0817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0333, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:03<00:18, 13.24it/s]

tensor(14.8521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0344, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:04<00:18, 13.20it/s]

tensor(14.6495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:18, 13.13it/s]

tensor(14.5289, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:04<00:18, 13.17it/s]

tensor(14.4142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.22it/s]

tensor(14.2986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:05<00:17, 13.14it/s]

tensor(14.2025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1483, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.15it/s]

tensor(14.1216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0945, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:17, 13.22it/s]

tensor(14.0386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9837, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:16, 13.25it/s]

tensor(13.9580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:05<00:16, 13.22it/s]

tensor(13.8866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8630, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.17it/s]

tensor(13.8156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:16, 13.16it/s]

tensor(13.7455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7232, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:16, 13.18it/s]

tensor(13.6802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:06<00:15, 13.14it/s]

tensor(13.6171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.20it/s]

tensor(13.5557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5358, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:15, 13.19it/s]

tensor(13.4964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:15, 13.21it/s]

tensor(13.4392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([279, 121,  35, 214, 113, 193,  82,  48,  86, 143, 150,  98,  20, 357])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:11, 27.13it/s]
  1%|          | 10/1939 [00:00<00:46, 41.77it/s]
  1%|          | 15/1939 [00:00<00:49, 38.90it/s]
  1%|          | 20/1939 [00:00<01:11, 26.90it/s]
  1%|          | 24/1939 [00:00<01:23, 22.80it/s]
  1%|▏         | 28/1939 [00:01<01:13, 26.13it/s]
  2%|▏         | 35/1939 [00:01<00:54, 34.83it/s]
  2%|▏         | 41/1939 [00:01<01:09, 27.24it/s]
  2%|▏         | 45/1939 [00:01<01:34, 19.99it/s]
  2%|▏         | 48/1939 [00:01<01:32, 20.36it/s]
  3%|▎         | 51/1939 [00:02<01:37, 19.34it/s]
  3%|▎         | 54/1939 [00:02<02:07, 14.77it/s]
  3%|▎         | 56/1939 [00:02<02:26, 12.88it/s]
  3%|▎         | 58/1939 [00:02<02:28, 12.63it/s]
  3%|▎         | 60/1939 [00:03<03:10,  9.85it/s]
  3%|▎         | 64/1939 [00:03<02:12, 14.11it/s]
  3%|▎         | 67/1939 [00:03<02:08, 14.62it/s]
  4%|▎         | 70/1939 [00:03<01:50, 16.88it/s]
  4%|▍         | 73/1939 [00:03<02:07, 14.69it/s]
  4%|▍         | 75/1939 [00:04<02:02, 15.17it/s]
  4%|▍         | 77/1939 [00:04<01:58, 15.66it/s]
  4%|▍         | 79/1939 [00:04<02:41, 11.54it/s]
  4%|▍         | 81/1939 [00:04<02:55, 10.59it/s]
  4%|▍         | 83/1939 [00:04<02:53, 10.69it/s]
  4%|▍         | 85/1939 [00:04<02:39, 11.63it/s]
  4%|▍         | 87/1939 [00:05<03:06,  9.94it/s]
  5%|▍         | 89/1939 [00:05<02:48, 10.96it/s]
  5%|▍         | 94/1939 [00:05<02:20, 13.13it/s]
  5%|▍         | 96/1939 [00:05<02:33, 12.00it/s]
  5%|▌         | 98/1939 [00:06<02:21, 13.05it/s]
  5%|▌         | 100/1939 [00:06<03:06,  9.87it/s]
  5%|▌         | 102/1939 [00:06<03:53,  7.88it/s]
  5%|▌         | 105/1939 [00:06<03:05,  9.89it/s]
  6%|▌         | 107/1939 [00:07<02:56, 10.40it/s]
  6%|▌         | 110/1939 [00:07<02:22, 12.82it/s]
  6%|▌         | 113/1939 [00:07<02:00, 15.14it/s]
  6%|▌         | 115/1939 [00:07<03:18,  9.21it/s]
  6%|▌         | 117/1939 [00:08<03:25,  8.86it/s]
  6%|▌         | 119/1939 [00:08<03:35,  8.45it/s]
  6%|▌         | 121/1939 [00:08<03:13,  9.39it/s]
  6%|▋         | 123/1939 [00:08<03:02,  9.94it/s]
  7%|▋         | 127/1939 [00:08<02:01, 14.97it/s]
  7%|▋         | 129/1939 [00:08<02:09, 13.93it/s]
  7%|▋         | 132/1939 [00:09<02:18, 13.04it/s]
  7%|▋         | 134/1939 [00:09<02:14, 13.45it/s]
  7%|▋         | 136/1939 [00:09<02:28, 12.13it/s]
  7%|▋         | 138/1939 [00:09<02:48, 10.70it/s]
  7%|▋         | 140/1939 [00:09<02:41, 11.14it/s]
  7%|▋         | 142/1939 [00:10<03:10,  9.44it/s]
  7%|▋         | 145/1939 [00:10<02:58, 10.05it/s]
  8%|▊         | 147/1939 [00:10<02:51, 10.44it/s]
  8%|▊         | 149/1939 [00:10<02:49, 10.58it/s]
  8%|▊         | 151/1939 [00:11<02:56, 10.13it/s]
  8%|▊         | 153/1939 [00:11<02:42, 10.96it/s]
  8%|▊         | 155/1939 [00:11<03:03,  9.74it/s]
  8%|▊         | 157/1939 [00:11<03:02,  9.77it/s]
  8%|▊         | 159/1939 [00:12<03:47,  7.82it/s]
  8%|▊         | 160/1939 [00:12<04:19,  6.86it/s]
  8%|▊         | 162/1939 [00:12<04:18,  6.86it/s]
  8%|▊         | 163/1939 [00:12<04:47,  6.17it/s]
  8%|▊         | 164/1939 [00:13<05:08,  5.76it/s]
  9%|▊         | 166/1939 [00:13<03:52,  7.64it/s]
  9%|▊         | 168/1939 [00:13<03:06,  9.48it/s]
  9%|▉         | 173/1939 [00:13<01:43, 17.00it/s]
  9%|▉         | 178/1939 [00:13<01:13, 23.86it/s]
  9%|▉         | 183/1939 [00:13<00:59, 29.30it/s]
 10%|▉         | 187/1939 [00:14<01:37, 17.98it/s]
 33%|███▎      | 100/300 [00:24<00:15, 13.21it/s]]
 10%|█         | 197/1939 [00:14<01:40, 17.36it/s]
 10%|█         | 200/1939 [00:14<02:01, 14.36it/s]
 10%|█         | 203/1939 [00:15<02:47, 10.37it/s]
 11%|█         | 205/1939 [00:15<03:09,  9.15it/s]
 11%|█         | 207/1939 [00:15<03:15,  8.86it/s]
 11%|█         | 209/1939 [00:16<02:54,  9.89it/s]
 11%|█         | 211/1939 [00:16<03:00,  9.55it/s]
 11%|█         | 213/1939 [00:16<03:23,  8.46it/s]
 11%|█         | 215/1939 [00:16<02:53,  9.92it/s]
 11%|█         | 218/1939 [00:17<02:41, 10.65it/s]
 11%|█▏        | 221/1939 [00:17<02:11, 13.07it/s]
 12%|█▏        | 223/1939 [00:17<02:45, 10.36it/s]
 12%|█▏        | 225/1939 [00:17<03:18,  8.62it/s]
 12%|█▏        | 228/1939 [00:18<02:58,  9.58it/s]
 12%|█▏        | 230/1939 [00:18<03:09,  9.01it/s]
 12%|█▏        | 233/1939 [00:18<02:59,  9.51it/s]
 12%|█▏        | 235/1939 [00:18<02:42, 10.52it/s]
 12%|█▏        | 237/1939 [00:18<02:55,  9.71it/s]
 12%|█▏        | 239/1939 [00:19<03:17,  8.61it/s]
 12%|█▏        | 240/1939 [00:19<03:56,  7.19it/s]
 12%|█▏        | 241/1939 [00:19<04:06,  6.90it/s]
 12%|█▏        | 242/1939 [00:19<04:23,  6.43it/s]
 13%|█▎        | 243/1939 [00:20<04:42,  6.00it/s]
 13%|█▎        | 244/1939 [00:20<05:19,  5.30it/s]
 13%|█▎        | 246/1939 [00:20<04:07,  6.85it/s]
 13%|█▎        | 248/1939 [00:20<03:22,  8.33it/s]
 13%|█▎        | 250/1939 [00:20<03:02,  9.25it/s]
 13%|█▎        | 251/1939 [00:21<03:15,  8.64it/s]
 13%|█▎        | 252/1939 [00:21<03:14,  8.66it/s]
 13%|█▎        | 254/1939 [00:21<02:41, 10.43it/s]
 13%|█▎        | 256/1939 [00:21<02:30, 11.22it/s]
 13%|█▎        | 258/1939 [00:21<03:12,  8.74it/s]
 13%|█▎        | 259/1939 [00:21<03:14,  8.63it/s]
 13%|█▎        | 260/1939 [00:21<03:24,  8.23it/s]
 14%|█▎        | 263/1939 [00:22<03:02,  9.20it/s]
 14%|█▎        | 264/1939 [00:22<03:39,  7.64it/s]
 14%|█▎        | 266/1939 [00:22<03:00,  9.28it/s]
 14%|█▍        | 268/1939 [00:22<03:15,  8.53it/s]
 14%|█▍        | 270/1939 [00:23<03:14,  8.60it/s]
 14%|█▍        | 272/1939 [00:23<02:51,  9.72it/s]
 14%|█▍        | 274/1939 [00:23<03:20,  8.30it/s]
 14%|█▍        | 275/1939 [00:23<03:15,  8.51it/s]
 14%|█▍        | 278/1939 [00:23<02:19, 11.92it/s]
 14%|█▍        | 281/1939 [00:24<02:36, 10.59it/s]
 15%|█▍        | 283/1939 [00:24<02:19, 11.85it/s]
 15%|█▍        | 285/1939 [00:24<02:52,  9.62it/s]
 15%|█▍        | 287/1939 [00:24<03:11,  8.61it/s]
 15%|█▍        | 289/1939 [00:25<03:06,  8.84it/s]
 15%|█▌        | 292/1939 [00:25<02:16, 12.03it/s]
 15%|█▌        | 294/1939 [00:25<02:50,  9.64it/s]
 15%|█▌        | 296/1939 [00:25<03:15,  8.42it/s]
 15%|█▌        | 298/1939 [00:26<03:29,  7.85it/s]
 15%|█▌        | 300/1939 [00:26<03:37,  7.55it/s]
 16%|█▌        | 302/1939 [00:26<03:01,  9.01it/s]
 16%|█▌        | 304/1939 [00:27<04:08,  6.57it/s]
 16%|█▌        | 306/1939 [00:27<03:25,  7.93it/s]
 16%|█▌        | 308/1939 [00:27<04:28,  6.09it/s]
 16%|█▌        | 311/1939 [00:27<03:07,  8.66it/s]
 16%|█▌        | 313/1939 [00:28<04:01,  6.74it/s]
 16%|█▌        | 315/1939 [00:28<04:06,  6.60it/s]
 16%|█▋        | 316/1939 [00:28<04:40,  5.78it/s]
 16%|█▋        | 317/1939 [00:29<05:11,  5.20it/s]
 16%|█▋        | 318/1939 [00:29<05:35,  4.84it/s]
 16%|█▋        | 319/1939 [00:29<06:19,  4.27it/s]
 17%|█▋        | 320/1939 [00:30<06:35,  4.09it/s]
 17%|█▋        | 321/1939 [00:30<06:09,  4.38it/s]
 17%|█▋        | 322/1939 [00:30<05:56,  4.54it/s]
 17%|█▋        | 325/1939 [00:30<03:15,  8.26it/s]
 17%|█▋        | 327/1939 [00:30<03:10,  8.44it/s]
 17%|█▋        | 329/1939 [00:30<02:35, 10.39it/s]
 17%|█▋        | 334/1939 [00:30<01:28, 18.11it/s]
 17%|█▋        | 339/1939 [00:31<01:24, 18.95it/s]
 18%|█▊        | 342/1939 [00:31<01:16, 20.98it/s]
 18%|█▊        | 348/1939 [00:31<00:56, 27.94it/s]
 18%|█▊        | 352/1939 [00:31<01:30, 17.63it/s]
 18%|█▊        | 355/1939 [00:32<02:20, 11.28it/s]
 18%|█▊        | 357/1939 [00:32<02:11, 11.99it/s]
 19%|█▊        | 360/1939 [00:32<02:15, 11.69it/s]
 19%|█▊        | 363/1939 [00:33<02:22, 11.07it/s]
 19%|█▉        | 365/1939 [00:33<02:09, 12.13it/s]
 19%|█▉        | 367/1939 [00:33<02:32, 10.33it/s]
 19%|█▉        | 370/1939 [00:33<02:34, 10.18it/s]
 19%|█▉        | 372/1939 [00:34<02:58,  8.77it/s]
 19%|█▉        | 374/1939 [00:34<02:33, 10.18it/s]
 19%|█▉        | 376/1939 [00:34<02:39,  9.77it/s]
 19%|█▉        | 378/1939 [00:34<02:37,  9.92it/s]
 20%|█▉        | 380/1939 [00:34<03:02,  8.53it/s]
 20%|█▉        | 381/1939 [00:35<03:24,  7.61it/s]
 20%|█▉        | 382/1939 [00:35<03:57,  6.55it/s]
 20%|█▉        | 384/1939 [00:35<03:48,  6.81it/s]
 20%|█▉        | 387/1939 [00:35<03:01,  8.53it/s]
 20%|██        | 388/1939 [00:36<03:01,  8.54it/s]
 20%|██        | 389/1939 [00:36<03:02,  8.50it/s]
 20%|██        | 390/1939 [00:36<03:22,  7.66it/s]
 20%|██        | 392/1939 [00:36<02:57,  8.74it/s]
 20%|██        | 394/1939 [00:36<02:47,  9.21it/s]
 20%|██        | 396/1939 [00:36<02:37,  9.81it/s]
 20%|██        | 397/1939 [00:37<02:45,  9.33it/s]
 21%|██        | 399/1939 [00:37<02:24, 10.63it/s]
 21%|██        | 401/1939 [00:37<02:06, 12.20it/s]
 21%|██        | 404/1939 [00:37<01:51, 13.81it/s]
 21%|██        | 406/1939 [00:37<01:55, 13.31it/s]
 21%|██        | 408/1939 [00:37<02:23, 10.66it/s]
 21%|██        | 411/1939 [00:38<02:16, 11.23it/s]
 21%|██▏       | 413/1939 [00:38<02:09, 11.74it/s]
 21%|██▏       | 415/1939 [00:38<02:18, 11.03it/s]
 22%|██▏       | 417/1939 [00:38<02:58,  8.53it/s]
 22%|██▏       | 419/1939 [00:39<02:58,  8.53it/s]
 22%|██▏       | 422/1939 [00:39<02:31,  9.99it/s]
 22%|██▏       | 424/1939 [00:39<02:13, 11.32it/s]
 22%|██▏       | 426/1939 [00:39<02:38,  9.56it/s]
 22%|██▏       | 428/1939 [00:39<02:49,  8.93it/s]
 22%|██▏       | 431/1939 [00:40<02:17, 10.98it/s]
 22%|██▏       | 435/1939 [00:40<01:36, 15.58it/s]
 23%|██▎       | 440/1939 [00:40<01:08, 21.82it/s]
 23%|██▎       | 443/1939 [00:40<01:41, 14.79it/s]
 23%|██▎       | 450/1939 [00:40<01:03, 23.48it/s]
 23%|██▎       | 455/1939 [00:40<00:54, 27.34it/s]
 24%|██▎       | 460/1939 [00:41<00:47, 30.82it/s]
 24%|██▍       | 466/1939 [00:41<00:40, 36.62it/s]
 24%|██▍       | 471/1939 [00:41<01:02, 23.35it/s]
 24%|██▍       | 475/1939 [00:41<01:04, 22.60it/s]
 25%|██▍       | 479/1939 [00:42<01:23, 17.44it/s]
 25%|██▍       | 482/1939 [00:42<01:20, 18.10it/s]
 25%|██▌       | 486/1939 [00:42<01:08, 21.08it/s]
 25%|██▌       | 489/1939 [00:42<01:05, 22.27it/s]
 25%|██▌       | 492/1939 [00:42<01:26, 16.73it/s]
 26%|██▌       | 495/1939 [00:43<01:39, 14.49it/s]
 26%|██▌       | 497/1939 [00:43<02:14, 10.71it/s]
 26%|██▌       | 500/1939 [00:43<02:03, 11.62it/s]
 26%|██▌       | 504/1939 [00:43<01:33, 15.37it/s]
 26%|██▌       | 507/1939 [00:44<02:07, 11.21it/s]
 26%|██▋       | 511/1939 [00:44<01:48, 13.20it/s]
 27%|██▋       | 514/1939 [00:44<01:39, 14.27it/s]
 27%|██▋       | 516/1939 [00:44<01:34, 15.03it/s]
 27%|██▋       | 524/1939 [00:44<00:53, 26.32it/s]
 27%|██▋       | 530/1939 [00:44<00:44, 31.47it/s]
 28%|██▊       | 534/1939 [00:45<01:11, 19.69it/s]
 28%|██▊       | 537/1939 [00:45<01:27, 15.95it/s]
 28%|██▊       | 540/1939 [00:46<02:11, 10.65it/s]
 28%|██▊       | 543/1939 [00:46<01:55, 12.10it/s]
 28%|██▊       | 546/1939 [00:46<02:00, 11.57it/s]
 28%|██▊       | 548/1939 [00:47<02:36,  8.87it/s]
 28%|██▊       | 550/1939 [00:47<02:19,  9.97it/s]
 28%|██▊       | 552/1939 [00:47<03:29,  6.61it/s]
 29%|██▊       | 556/1939 [00:48<02:53,  7.97it/s]
 29%|██▉       | 558/1939 [00:48<03:02,  7.58it/s]
 29%|██▉       | 560/1939 [00:48<02:34,  8.90it/s]
 29%|██▉       | 562/1939 [00:49<03:30,  6.55it/s]
 29%|██▉       | 564/1939 [00:49<02:56,  7.78it/s]
 29%|██▉       | 567/1939 [00:49<02:42,  8.43it/s]
 29%|██▉       | 569/1939 [00:49<02:53,  7.90it/s]
 29%|██▉       | 571/1939 [00:50<02:55,  7.80it/s]
 29%|██▉       | 572/1939 [00:50<03:20,  6.81it/s]
 30%|██▉       | 574/1939 [00:50<03:06,  7.32it/s]
 30%|██▉       | 575/1939 [00:50<03:32,  6.43it/s]
 30%|██▉       | 577/1939 [00:51<02:42,  8.39it/s]
 30%|██▉       | 579/1939 [00:51<03:03,  7.43it/s]
 30%|███       | 582/1939 [00:51<02:41,  8.42it/s]
 30%|███       | 584/1939 [00:51<02:25,  9.29it/s]
 30%|███       | 586/1939 [00:52<02:26,  9.22it/s]
 30%|███       | 588/1939 [00:52<02:16,  9.89it/s]
 30%|███       | 590/1939 [00:52<02:48,  8.02it/s]
 31%|███       | 592/1939 [00:52<02:18,  9.72it/s]
 31%|███       | 594/1939 [00:52<02:29,  8.99it/s]
 31%|███       | 596/1939 [00:53<02:34,  8.71it/s]
 31%|███       | 599/1939 [00:53<02:21,  9.48it/s]
 31%|███       | 601/1939 [00:53<02:32,  8.77it/s]
 31%|███       | 604/1939 [00:54<02:30,  8.87it/s]
 31%|███▏      | 606/1939 [00:54<02:14,  9.89it/s]
 31%|███▏      | 608/1939 [00:54<02:58,  7.44it/s]
 32%|███▏      | 611/1939 [00:54<02:43,  8.15it/s]
 32%|███▏      | 612/1939 [00:55<03:00,  7.37it/s]
 32%|███▏      | 613/1939 [00:55<03:22,  6.55it/s]
 32%|███▏      | 614/1939 [00:55<03:38,  6.06it/s]
 32%|███▏      | 615/1939 [00:55<03:48,  5.79it/s]
 32%|███▏      | 616/1939 [00:55<04:01,  5.48it/s]
 32%|███▏      | 617/1939 [00:56<04:27,  4.94it/s]
 32%|███▏      | 618/1939 [00:56<04:34,  4.82it/s]
 32%|███▏      | 620/1939 [00:56<03:49,  5.76it/s]
 32%|███▏      | 621/1939 [00:56<04:01,  5.46it/s]
 32%|███▏      | 622/1939 [00:57<04:13,  5.19it/s]
 32%|███▏      | 624/1939 [00:57<03:10,  6.89it/s]
 32%|███▏      | 629/1939 [00:57<02:06, 10.32it/s]
 32%|███▏      | 630/1939 [00:57<02:33,  8.54it/s]
 33%|███▎      | 632/1939 [00:58<02:43,  8.00it/s]
 33%|███▎      | 635/1939 [00:58<02:09, 10.10it/s]
 33%|███▎      | 637/1939 [00:58<02:23,  9.08it/s]
 33%|███▎      | 639/1939 [00:58<02:02, 10.60it/s]
 33%|███▎      | 641/1939 [00:59<02:29,  8.70it/s]
 33%|███▎      | 643/1939 [00:59<02:29,  8.70it/s]
 33%|███▎      | 645/1939 [00:59<02:11,  9.82it/s]
 33%|███▎      | 647/1939 [00:59<02:28,  8.73it/s]
 33%|███▎      | 649/1939 [00:59<02:17,  9.36it/s]
 34%|███▎      | 651/1939 [01:00<02:03, 10.44it/s]
 34%|███▎      | 653/1939 [01:00<02:07, 10.08it/s]
 34%|███▍      | 655/1939 [01:00<02:23,  8.95it/s]
 34%|███▍      | 656/1939 [01:00<02:42,  7.91it/s]
 34%|███▍      | 658/1939 [01:00<02:30,  8.49it/s]
 34%|███▍      | 659/1939 [01:01<02:47,  7.63it/s]
 34%|███▍      | 661/1939 [01:01<02:15,  9.41it/s]
 34%|███▍      | 663/1939 [01:01<01:54, 11.17it/s]
 34%|███▍      | 665/1939 [01:01<02:10,  9.79it/s]
 34%|███▍      | 667/1939 [01:01<02:10,  9.72it/s]
 35%|███▍      | 669/1939 [01:01<01:50, 11.51it/s]
 35%|███▍      | 672/1939 [01:02<01:29, 14.22it/s]
 35%|███▍      | 675/1939 [01:02<01:16, 16.47it/s]
 35%|███▍      | 677/1939 [01:02<01:37, 12.96it/s]
 35%|███▌      | 679/1939 [01:02<02:06,  9.97it/s]
 35%|███▌      | 681/1939 [01:03<02:17,  9.18it/s]
 35%|███▌      | 683/1939 [01:03<02:25,  8.60it/s]
 35%|███▌      | 684/1939 [01:03<02:59,  7.00it/s]
 35%|███▌      | 687/1939 [01:03<02:40,  7.82it/s]
 35%|███▌      | 688/1939 [01:04<02:56,  7.10it/s]
 36%|███▌      | 689/1939 [01:04<02:59,  6.96it/s]
 36%|███▌      | 691/1939 [01:04<03:15,  6.37it/s]
 36%|███▌      | 693/1939 [01:04<03:03,  6.81it/s]
 36%|███▌      | 697/1939 [01:04<01:50, 11.22it/s]
 36%|███▋      | 703/1939 [01:05<01:04, 19.06it/s]
 36%|███▋      | 707/1939 [01:05<00:54, 22.54it/s]
 37%|███▋      | 713/1939 [01:05<01:00, 20.19it/s]
 37%|███▋      | 716/1939 [01:05<01:00, 20.35it/s]
 37%|███▋      | 722/1939 [01:05<00:44, 27.16it/s]
 37%|███▋      | 726/1939 [01:05<00:41, 29.34it/s]
 38%|███▊      | 730/1939 [01:06<00:53, 22.54it/s]
 38%|███▊      | 733/1939 [01:06<01:25, 14.16it/s]
 38%|███▊      | 736/1939 [01:07<01:43, 11.60it/s]
 38%|███▊      | 739/1939 [01:07<01:44, 11.52it/s]
 38%|███▊      | 741/1939 [01:07<01:38, 12.19it/s]
 38%|███▊      | 743/1939 [01:07<01:46, 11.19it/s]
 38%|███▊      | 745/1939 [01:07<01:56, 10.22it/s]
 39%|███▊      | 747/1939 [01:08<01:52, 10.61it/s]
 39%|███▊      | 749/1939 [01:08<02:02,  9.71it/s]
 39%|███▊      | 751/1939 [01:08<02:25,  8.16it/s]
 39%|███▉      | 753/1939 [01:08<02:04,  9.54it/s]
 39%|███▉      | 755/1939 [01:09<02:06,  9.39it/s]
 39%|███▉      | 757/1939 [01:09<02:21,  8.33it/s]
 39%|███▉      | 759/1939 [01:09<02:18,  8.54it/s]
 39%|███▉      | 760/1939 [01:09<02:16,  8.62it/s]
 39%|███▉      | 762/1939 [01:09<01:57, 10.04it/s]
 39%|███▉      | 764/1939 [01:10<02:35,  7.55it/s]
 40%|███▉      | 766/1939 [01:10<02:17,  8.54it/s]
 40%|███▉      | 768/1939 [01:10<02:41,  7.25it/s]
 40%|███▉      | 769/1939 [01:10<02:49,  6.91it/s]
 40%|███▉      | 770/1939 [01:11<03:03,  6.36it/s]
 40%|███▉      | 771/1939 [01:11<03:34,  5.44it/s]
 40%|███▉      | 772/1939 [01:11<03:59,  4.88it/s]
 40%|███▉      | 773/1939 [01:11<04:15,  4.56it/s]
 40%|███▉      | 775/1939 [01:12<03:39,  5.31it/s]
 40%|████      | 776/1939 [01:12<03:49,  5.08it/s]
 40%|████      | 777/1939 [01:12<03:47,  5.10it/s]
 40%|████      | 779/1939 [01:12<03:07,  6.19it/s]
 40%|████      | 780/1939 [01:13<03:41,  5.22it/s]
 40%|████      | 782/1939 [01:13<02:42,  7.13it/s]
 40%|████      | 784/1939 [01:13<02:30,  7.67it/s]
 41%|████      | 786/1939 [01:13<02:00,  9.55it/s]
 41%|████      | 788/1939 [01:13<01:56,  9.85it/s]
 41%|████      | 790/1939 [01:14<02:04,  9.24it/s]
 41%|████      | 793/1939 [01:14<01:30, 12.73it/s]
 41%|████      | 795/1939 [01:14<01:57,  9.75it/s]
 41%|████      | 797/1939 [01:14<01:42, 11.10it/s]
 41%|████      | 799/1939 [01:14<01:52, 10.15it/s]
 41%|████▏     | 801/1939 [01:15<02:02,  9.27it/s]
 41%|████▏     | 803/1939 [01:15<01:45, 10.82it/s]
 42%|████▏     | 805/1939 [01:15<02:05,  9.05it/s]
 42%|████▏     | 807/1939 [01:15<02:26,  7.71it/s]
 42%|████▏     | 809/1939 [01:16<02:26,  7.74it/s]
 42%|████▏     | 811/1939 [01:16<02:03,  9.13it/s]
 42%|████▏     | 813/1939 [01:16<02:31,  7.42it/s]
 42%|████▏     | 815/1939 [01:16<02:04,  9.03it/s]
 42%|████▏     | 817/1939 [01:17<02:47,  6.69it/s]
 42%|████▏     | 818/1939 [01:17<03:00,  6.20it/s]
 42%|████▏     | 819/1939 [01:17<03:14,  5.74it/s]
 42%|████▏     | 820/1939 [01:17<03:27,  5.41it/s]
 42%|████▏     | 821/1939 [01:18<03:32,  5.26it/s]
 42%|████▏     | 822/1939 [01:18<03:35,  5.19it/s]
 42%|████▏     | 823/1939 [01:18<03:48,  4.89it/s]
 43%|████▎     | 825/1939 [01:18<03:14,  5.73it/s]
 43%|████▎     | 826/1939 [01:19<03:39,  5.06it/s]
 43%|████▎     | 828/1939 [01:19<03:19,  5.57it/s]
 43%|████▎     | 829/1939 [01:19<03:44,  4.94it/s]
 43%|████▎     | 832/1939 [01:19<02:18,  7.99it/s]
 43%|████▎     | 834/1939 [01:20<02:18,  7.95it/s]
 43%|████▎     | 837/1939 [01:20<01:42, 10.80it/s]
 43%|████▎     | 839/1939 [01:20<01:48, 10.09it/s]
 43%|████▎     | 841/1939 [01:20<01:36, 11.39it/s]
 44%|████▎     | 844/1939 [01:20<01:36, 11.39it/s]
 44%|████▎     | 846/1939 [01:20<01:29, 12.24it/s]
 44%|████▍     | 851/1939 [01:21<01:20, 13.53it/s]
 44%|████▍     | 853/1939 [01:21<01:16, 14.18it/s]
 44%|████▍     | 855/1939 [01:21<01:36, 11.25it/s]
 44%|████▍     | 857/1939 [01:21<01:48,  9.97it/s]
 44%|████▍     | 859/1939 [01:22<02:04,  8.67it/s]
 44%|████▍     | 860/1939 [01:22<02:28,  7.27it/s]
 44%|████▍     | 861/1939 [01:22<02:54,  6.19it/s]
 44%|████▍     | 862/1939 [01:23<03:19,  5.39it/s]
 45%|████▍     | 863/1939 [01:23<03:44,  4.80it/s]
 45%|████▍     | 864/1939 [01:23<03:30,  5.11it/s]
 45%|████▍     | 866/1939 [01:23<02:34,  6.92it/s]
 45%|████▍     | 872/1939 [01:23<01:10, 15.18it/s]
 45%|████▌     | 877/1939 [01:23<00:51, 20.60it/s]
 45%|████▌     | 880/1939 [01:24<00:49, 21.38it/s]
 46%|████▌     | 883/1939 [01:24<00:57, 18.21it/s]
 46%|████▌     | 886/1939 [01:24<01:04, 16.26it/s]
 46%|████▌     | 893/1939 [01:24<00:41, 25.25it/s]
 46%|████▋     | 897/1939 [01:24<00:37, 28.01it/s]
 46%|████▋     | 901/1939 [01:25<00:47, 21.96it/s]
 47%|████▋     | 904/1939 [01:25<01:04, 16.06it/s]
 47%|████▋     | 910/1939 [01:25<00:56, 18.11it/s]
 47%|████▋     | 913/1939 [01:26<01:16, 13.35it/s]
 47%|████▋     | 915/1939 [01:26<01:25, 11.93it/s]
 47%|████▋     | 918/1939 [01:26<01:29, 11.40it/s]
 47%|████▋     | 920/1939 [01:26<01:41, 10.08it/s]
 48%|████▊     | 923/1939 [01:26<01:20, 12.55it/s]
 48%|████▊     | 925/1939 [01:27<01:38, 10.26it/s]
 48%|████▊     | 927/1939 [01:27<01:44,  9.64it/s]
 48%|████▊     | 930/1939 [01:27<01:41,  9.96it/s]
 48%|████▊     | 932/1939 [01:28<01:48,  9.30it/s]
 48%|████▊     | 936/1939 [01:28<01:15, 13.36it/s]
 49%|████▊     | 944/1939 [01:28<00:41, 24.01it/s]
 49%|████▉     | 951/1939 [01:28<00:30, 32.63it/s]
 49%|████▉     | 958/1939 [01:28<00:24, 40.11it/s]
 50%|████▉     | 964/1939 [01:28<00:37, 26.27it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 302.36it/s]
 34%|███▎      | 101/300 [03:15<1:50:11, 33.22s/it]

[[np.int64(0), False, 13], [np.int64(1), False, 3], [np.int64(2), False, 5], [np.int64(3), False, 13], [np.int64(4), False, 8], [np.int64(5), False, 10], [np.int64(6), False, 5], [np.int64(7), False, 11], [np.int64(9), False, 0], [np.int64(11), False, 3], [np.int64(12), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.4024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8787, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.3896, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0290, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [03:15<1:27:38, 26.56s/it]

tensor(13.3958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2411, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:15<55:11, 16.90s/it]

tensor(13.4214, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4920, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5649, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [03:16<36:00, 11.14s/it]

tensor(13.4749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6400, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [03:16<24:01,  7.51s/it]

tensor(13.4681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7139, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7787, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8302, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [03:16<16:16,  5.14s/it]

tensor(13.4157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8716, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9110, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [03:16<11:08,  3.56s/it]

tensor(13.3707, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9463, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [03:16<07:42,  2.49s/it]

tensor(13.3496, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9802, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0078, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3123, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0382, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:17<05:22,  1.75s/it]

tensor(13.2958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0630, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0791, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [03:17<03:47,  1.25s/it]

tensor(13.2620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1057, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [03:17<02:41,  1.11it/s]

tensor(13.2462, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1268, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1489, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1739, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [03:17<01:57,  1.52it/s]

tensor(13.2000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2017, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2277, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [03:17<01:25,  2.05it/s]

tensor(13.1711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2490, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [03:17<01:04,  2.71it/s]

tensor(13.1553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2714, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2877, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3156, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [03:18<00:49,  3.48it/s]

tensor(13.1061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3258, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3376, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [03:18<00:39,  4.35it/s]

tensor(13.0743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3485, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [03:18<00:31,  5.27it/s]

tensor(13.0601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3616, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3727, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3810, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [03:18<00:26,  6.19it/s]

tensor(13.0178, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3902, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3997, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [03:18<00:23,  7.06it/s]

tensor(12.9914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4192, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [03:19<00:20,  7.78it/s]

tensor(12.9788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4296, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4393, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4501, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [03:19<00:18,  8.43it/s]

tensor(12.9447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4567, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4648, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:19<00:17,  8.95it/s]

tensor(12.9239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4738, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:19<00:16,  9.33it/s]

tensor(12.9140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4799, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9043, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4872, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4950, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [03:19<00:15,  9.65it/s]

tensor(12.8862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5007, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5068, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:20<00:15,  9.90it/s]

tensor(12.8683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5129, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:20<00:14, 10.06it/s]

tensor(12.8599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5177, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([164, 361, 116, 124, 262, 197,  88,  29,  71, 229, 114,  82,  71,  31])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:41, 19.17it/s]
  0%|          | 5/1939 [00:00<02:27, 13.09it/s]
  0%|          | 7/1939 [00:00<02:17, 14.02it/s]
  1%|          | 10/1939 [00:00<02:24, 13.31it/s]
  1%|          | 12/1939 [00:00<02:27, 13.08it/s]
  1%|          | 14/1939 [00:01<02:31, 12.74it/s]
  1%|          | 16/1939 [00:01<02:16, 14.05it/s]
  1%|          | 18/1939 [00:01<02:31, 12.66it/s]
  1%|          | 20/1939 [00:01<02:20, 13.62it/s]
  1%|          | 24/1939 [00:01<02:07, 15.07it/s]
  1%|▏         | 27/1939 [00:01<02:00, 15.86it/s]
  1%|▏         | 29/1939 [00:02<01:58, 16.10it/s]
  2%|▏         | 31/1939 [00:02<01:58, 16.14it/s]
  2%|▏         | 35/1939 [00:02<01:28, 21.45it/s]
  2%|▏         | 40/1939 [00:02<01:38, 19.32it/s]
  2%|▏         | 43/1939 [00:03<03:07, 10.13it/s]
  2%|▏         | 47/1939 [00:03<02:19, 13.56it/s]
  3%|▎         | 50/1939 [00:03<02:23, 13.16it/s]
  3%|▎         | 53/1939 [00:03<02:16, 13.83it/s]
  3%|▎         | 55/1939 [00:03<02:12, 14.26it/s]
  3%|▎         | 58/1939 [00:04<02:32, 12.35it/s]
  3%|▎         | 60/1939 [00:04<02:23, 13.10it/s]
  3%|▎         | 64/1939 [00:04<02:29, 12.57it/s]
  3%|▎         | 66/1939 [00:04<02:40, 11.64it/s]
  4%|▎         | 68/1939 [00:05<02:36, 11.97it/s]
  4%|▎         | 70/1939 [00:05<02:34, 12.12it/s]
  4%|▎         | 72/1939 [00:05<02:20, 13.26it/s]
  4%|▍         | 74/1939 [00:05<02:52, 10.84it/s]
  4%|▍         | 76/1939 [00:05<02:49, 11.01it/s]
  4%|▍         | 78/1939 [00:05<02:50, 10.92it/s]
  4%|▍         | 80/1939 [00:06<03:40,  8.44it/s]
  4%|▍         | 81/1939 [00:06<04:39,  6.65it/s]
  4%|▍         | 82/1939 [00:06<06:02,  5.13it/s]
  4%|▍         | 84/1939 [00:07<05:20,  5.79it/s]
  4%|▍         | 86/1939 [00:07<04:26,  6.96it/s]
  4%|▍         | 87/1939 [00:07<04:11,  7.36it/s]
  5%|▍         | 89/1939 [00:07<03:44,  8.23it/s]
  5%|▍         | 90/1939 [00:07<03:57,  7.78it/s]
  5%|▍         | 92/1939 [00:07<03:04, 10.03it/s]
  5%|▍         | 94/1939 [00:08<03:11,  9.64it/s]
  5%|▌         | 97/1939 [00:08<02:20, 13.10it/s]
  5%|▌         | 99/1939 [00:08<02:32, 12.03it/s]
  5%|▌         | 101/1939 [00:08<02:33, 11.94it/s]
  5%|▌         | 104/1939 [00:08<02:00, 15.25it/s]
  6%|▌         | 111/1939 [00:09<01:38, 18.57it/s]
  6%|▌         | 113/1939 [00:09<01:40, 18.13it/s]
  6%|▌         | 115/1939 [00:09<02:21, 12.92it/s]
  6%|▌         | 117/1939 [00:09<02:13, 13.70it/s]
  6%|▌         | 119/1939 [00:10<03:33,  8.53it/s]
  6%|▌         | 121/1939 [00:10<05:09,  5.88it/s]
  6%|▋         | 123/1939 [00:11<04:55,  6.14it/s]
  6%|▋         | 124/1939 [00:11<05:11,  5.83it/s]
  6%|▋         | 126/1939 [00:11<04:04,  7.43it/s]
  7%|▋         | 128/1939 [00:11<04:36,  6.56it/s]
 50%|█████     | 150/300 [03:34<00:14, 10.06it/s]]
  7%|▋         | 131/1939 [00:12<04:32,  6.63it/s]
  7%|▋         | 132/1939 [00:12<05:30,  5.47it/s]
  7%|▋         | 133/1939 [00:12<05:50,  5.15it/s]
  7%|▋         | 134/1939 [00:13<05:56,  5.06it/s]
  7%|▋         | 136/1939 [00:13<04:11,  7.18it/s]
  7%|▋         | 137/1939 [00:13<05:33,  5.40it/s]
  7%|▋         | 140/1939 [00:13<03:25,  8.77it/s]
  7%|▋         | 145/1939 [00:13<02:47, 10.72it/s]
  8%|▊         | 147/1939 [00:14<02:28, 12.03it/s]
  8%|▊         | 149/1939 [00:14<02:48, 10.60it/s]
  8%|▊         | 151/1939 [00:14<02:34, 11.59it/s]
  8%|▊         | 153/1939 [00:14<03:10,  9.37it/s]
  8%|▊         | 155/1939 [00:14<02:51, 10.38it/s]
  8%|▊         | 157/1939 [00:15<04:40,  6.36it/s]
  8%|▊         | 158/1939 [00:15<05:19,  5.57it/s]
  8%|▊         | 160/1939 [00:16<05:23,  5.50it/s]
  8%|▊         | 161/1939 [00:16<05:34,  5.31it/s]
  8%|▊         | 162/1939 [00:16<06:16,  4.72it/s]
  8%|▊         | 163/1939 [00:16<05:30,  5.38it/s]
  8%|▊         | 164/1939 [00:17<06:23,  4.62it/s]
  9%|▊         | 167/1939 [00:17<03:35,  8.21it/s]
  9%|▊         | 169/1939 [00:17<03:25,  8.61it/s]
  9%|▉         | 171/1939 [00:17<03:03,  9.64it/s]
  9%|▉         | 174/1939 [00:17<02:56, 10.01it/s]
  9%|▉         | 176/1939 [00:18<02:52, 10.21it/s]
  9%|▉         | 179/1939 [00:18<02:11, 13.35it/s]
  9%|▉         | 184/1939 [00:18<01:46, 16.53it/s]
 10%|▉         | 186/1939 [00:18<01:44, 16.73it/s]
 10%|▉         | 188/1939 [00:18<02:14, 13.00it/s]
 10%|▉         | 190/1939 [00:18<02:04, 14.06it/s]
 10%|▉         | 193/1939 [00:19<02:04, 14.06it/s]
 10%|█         | 195/1939 [00:19<02:01, 14.37it/s]
 10%|█         | 202/1939 [00:19<01:33, 18.58it/s]
 11%|█         | 204/1939 [00:19<01:51, 15.62it/s]
 11%|█         | 206/1939 [00:20<03:04,  9.40it/s]
 11%|█         | 208/1939 [00:20<03:18,  8.72it/s]
 11%|█         | 210/1939 [00:20<02:52,  9.99it/s]
 11%|█         | 212/1939 [00:21<04:07,  6.97it/s]
 11%|█         | 214/1939 [00:21<04:01,  7.14it/s]
 11%|█         | 216/1939 [00:21<03:20,  8.58it/s]
 11%|█▏        | 222/1939 [00:21<01:48, 15.76it/s]
 12%|█▏        | 225/1939 [00:22<02:18, 12.39it/s]
 12%|█▏        | 228/1939 [00:22<02:44, 10.40it/s]
 12%|█▏        | 230/1939 [00:22<02:32, 11.21it/s]
 12%|█▏        | 233/1939 [00:22<02:50, 10.02it/s]
 12%|█▏        | 235/1939 [00:23<03:14,  8.77it/s]
 12%|█▏        | 237/1939 [00:23<03:39,  7.75it/s]
 12%|█▏        | 238/1939 [00:23<04:14,  6.69it/s]
 12%|█▏        | 239/1939 [00:24<04:28,  6.32it/s]
 12%|█▏        | 240/1939 [00:24<05:43,  4.94it/s]
 12%|█▏        | 241/1939 [00:24<06:25,  4.40it/s]
 12%|█▏        | 242/1939 [00:25<07:04,  4.00it/s]
 13%|█▎        | 243/1939 [00:25<07:43,  3.66it/s]
 13%|█▎        | 245/1939 [00:25<06:47,  4.16it/s]
 13%|█▎        | 246/1939 [00:26<07:33,  3.74it/s]
 13%|█▎        | 248/1939 [00:26<06:51,  4.11it/s]
 13%|█▎        | 251/1939 [00:26<04:14,  6.64it/s]
 13%|█▎        | 254/1939 [00:26<03:34,  7.86it/s]
 13%|█▎        | 257/1939 [00:27<03:36,  7.75it/s]
 13%|█▎        | 260/1939 [00:27<03:42,  7.54it/s]
 13%|█▎        | 261/1939 [00:28<04:06,  6.81it/s]
 14%|█▎        | 263/1939 [00:28<04:30,  6.19it/s]
 14%|█▎        | 265/1939 [00:28<04:25,  6.30it/s]
 14%|█▍        | 267/1939 [00:28<03:37,  7.69it/s]
 14%|█▍        | 273/1939 [00:28<01:51, 14.90it/s]
 14%|█▍        | 276/1939 [00:29<02:02, 13.58it/s]
 14%|█▍        | 281/1939 [00:29<02:08, 12.95it/s]
 15%|█▍        | 283/1939 [00:29<02:00, 13.78it/s]
 15%|█▍        | 285/1939 [00:30<03:10,  8.66it/s]
 15%|█▍        | 287/1939 [00:30<02:50,  9.67it/s]
 15%|█▌        | 291/1939 [00:30<02:03, 13.40it/s]
 15%|█▌        | 293/1939 [00:30<01:54, 14.39it/s]
 15%|█▌        | 296/1939 [00:30<02:18, 11.87it/s]
 15%|█▌        | 299/1939 [00:31<01:56, 14.04it/s]
 16%|█▌        | 302/1939 [00:31<01:56, 14.00it/s]
 16%|█▌        | 305/1939 [00:31<02:04, 13.17it/s]
 16%|█▌        | 307/1939 [00:31<02:43, 10.01it/s]
 16%|█▌        | 309/1939 [00:32<02:31, 10.74it/s]
 16%|█▌        | 311/1939 [00:32<02:45,  9.84it/s]
 16%|█▌        | 313/1939 [00:32<02:34, 10.54it/s]
 16%|█▌        | 315/1939 [00:33<03:53,  6.97it/s]
 16%|█▋        | 318/1939 [00:33<02:52,  9.38it/s]
 17%|█▋        | 320/1939 [00:33<02:35, 10.40it/s]
 17%|█▋        | 322/1939 [00:33<03:46,  7.15it/s]
 17%|█▋        | 324/1939 [00:33<03:06,  8.68it/s]
 17%|█▋        | 329/1939 [00:34<01:48, 14.78it/s]
 17%|█▋        | 333/1939 [00:34<01:51, 14.41it/s]
 17%|█▋        | 336/1939 [00:34<01:38, 16.21it/s]
 18%|█▊        | 342/1939 [00:34<01:08, 23.26it/s]
 18%|█▊        | 346/1939 [00:34<01:08, 23.42it/s]
 18%|█▊        | 351/1939 [00:34<01:11, 22.07it/s]
 18%|█▊        | 354/1939 [00:35<02:06, 12.57it/s]
 18%|█▊        | 356/1939 [00:35<02:01, 13.05it/s]
 18%|█▊        | 358/1939 [00:35<01:58, 13.37it/s]
 19%|█▊        | 360/1939 [00:35<01:53, 13.87it/s]
 19%|█▊        | 362/1939 [00:36<02:05, 12.52it/s]
 19%|█▉        | 364/1939 [00:36<01:55, 13.62it/s]
 19%|█▉        | 370/1939 [00:36<01:48, 14.50it/s]
 19%|█▉        | 372/1939 [00:36<02:05, 12.45it/s]
 19%|█▉        | 374/1939 [00:37<02:20, 11.14it/s]
 19%|█▉        | 376/1939 [00:37<03:02,  8.58it/s]
 20%|█▉        | 379/1939 [00:37<02:22, 10.92it/s]
 20%|█▉        | 381/1939 [00:37<02:45,  9.43it/s]
 20%|█▉        | 383/1939 [00:38<02:55,  8.88it/s]
 20%|█▉        | 385/1939 [00:38<03:19,  7.78it/s]
 20%|█▉        | 386/1939 [00:38<03:36,  7.16it/s]
 20%|█▉        | 387/1939 [00:39<04:25,  5.85it/s]
 20%|██        | 388/1939 [00:39<05:08,  5.02it/s]
 20%|██        | 390/1939 [00:39<04:48,  5.37it/s]
 20%|██        | 393/1939 [00:40<04:18,  5.98it/s]
 20%|██        | 394/1939 [00:40<05:00,  5.14it/s]
 20%|██        | 396/1939 [00:40<04:56,  5.20it/s]
 20%|██        | 397/1939 [00:41<05:30,  4.67it/s]
 21%|██        | 398/1939 [00:41<05:45,  4.46it/s]
 21%|██        | 401/1939 [00:41<04:15,  6.02it/s]
 21%|██        | 403/1939 [00:41<03:25,  7.49it/s]
 21%|██        | 404/1939 [00:42<04:03,  6.30it/s]
 21%|██        | 405/1939 [00:42<04:59,  5.11it/s]
 21%|██        | 407/1939 [00:42<04:49,  5.29it/s]
 21%|██        | 408/1939 [00:43<05:02,  5.06it/s]
 21%|██        | 410/1939 [00:43<04:09,  6.12it/s]
 21%|██        | 411/1939 [00:43<04:58,  5.12it/s]
 21%|██▏       | 413/1939 [00:43<04:12,  6.04it/s]
 21%|██▏       | 415/1939 [00:44<04:21,  5.82it/s]
 22%|██▏       | 417/1939 [00:44<04:36,  5.50it/s]
 22%|██▏       | 419/1939 [00:44<04:36,  5.49it/s]
 22%|██▏       | 421/1939 [00:45<04:24,  5.74it/s]
 22%|██▏       | 422/1939 [00:45<04:41,  5.39it/s]
 22%|██▏       | 424/1939 [00:45<04:19,  5.83it/s]
 22%|██▏       | 425/1939 [00:45<04:01,  6.26it/s]
 22%|██▏       | 426/1939 [00:46<05:06,  4.93it/s]
 22%|██▏       | 428/1939 [00:46<04:54,  5.13it/s]
 22%|██▏       | 430/1939 [00:46<03:40,  6.84it/s]
 23%|██▎       | 437/1939 [00:46<01:33, 15.98it/s]
 23%|██▎       | 440/1939 [00:47<01:41, 14.76it/s]
 23%|██▎       | 443/1939 [00:47<01:30, 16.52it/s]
 23%|██▎       | 446/1939 [00:47<01:58, 12.56it/s]
 23%|██▎       | 448/1939 [00:47<02:11, 11.32it/s]
 23%|██▎       | 451/1939 [00:47<01:50, 13.52it/s]
 23%|██▎       | 455/1939 [00:48<01:45, 14.13it/s]
 24%|██▎       | 458/1939 [00:48<01:51, 13.25it/s]
 24%|██▎       | 460/1939 [00:48<01:45, 13.99it/s]
 24%|██▍       | 463/1939 [00:48<01:30, 16.28it/s]
 24%|██▍       | 465/1939 [00:49<01:58, 12.44it/s]
 24%|██▍       | 467/1939 [00:49<01:48, 13.59it/s]
 24%|██▍       | 469/1939 [00:49<02:17, 10.68it/s]
 24%|██▍       | 471/1939 [00:49<02:00, 12.18it/s]
 25%|██▍       | 476/1939 [00:49<01:18, 18.67it/s]
 25%|██▍       | 479/1939 [00:49<01:09, 20.93it/s]
 25%|██▍       | 484/1939 [00:49<01:10, 20.61it/s]
 25%|██▌       | 487/1939 [00:50<01:09, 21.02it/s]
 25%|██▌       | 490/1939 [00:50<01:36, 14.98it/s]
 25%|██▌       | 492/1939 [00:50<01:35, 15.22it/s]
 25%|██▌       | 494/1939 [00:50<01:50, 13.02it/s]
 26%|██▌       | 496/1939 [00:50<01:50, 13.01it/s]
 26%|██▌       | 498/1939 [00:51<02:05, 11.44it/s]
 26%|██▌       | 501/1939 [00:51<01:38, 14.66it/s]
 26%|██▌       | 506/1939 [00:51<01:26, 16.51it/s]
 26%|██▌       | 508/1939 [00:51<01:25, 16.76it/s]
 26%|██▋       | 511/1939 [00:51<01:15, 18.84it/s]
 27%|██▋       | 514/1939 [00:51<01:07, 21.18it/s]
 27%|██▋       | 518/1939 [00:52<00:56, 25.19it/s]
 27%|██▋       | 522/1939 [00:52<00:49, 28.40it/s]
 27%|██▋       | 528/1939 [00:52<00:39, 36.11it/s]
 27%|██▋       | 533/1939 [00:52<00:38, 36.24it/s]
 28%|██▊       | 537/1939 [00:52<00:57, 24.22it/s]
 28%|██▊       | 541/1939 [00:52<00:55, 25.31it/s]
 28%|██▊       | 544/1939 [00:53<01:18, 17.75it/s]
 28%|██▊       | 547/1939 [00:53<01:25, 16.35it/s]
 28%|██▊       | 550/1939 [00:53<01:20, 17.31it/s]
 29%|██▊       | 553/1939 [00:53<01:42, 13.50it/s]
 29%|██▊       | 557/1939 [00:53<01:20, 17.14it/s]
 29%|██▉       | 562/1939 [00:54<01:03, 21.54it/s]
 29%|██▉       | 565/1939 [00:54<01:26, 15.83it/s]
 29%|██▉       | 571/1939 [00:54<01:26, 15.78it/s]
 30%|██▉       | 573/1939 [00:55<02:13, 10.24it/s]
 30%|██▉       | 575/1939 [00:56<03:10,  7.16it/s]
 30%|██▉       | 577/1939 [00:56<03:09,  7.17it/s]
 30%|██▉       | 579/1939 [00:56<03:48,  5.95it/s]
 30%|██▉       | 581/1939 [00:56<03:13,  7.02it/s]
 30%|███       | 583/1939 [00:57<03:46,  5.98it/s]
 30%|███       | 584/1939 [00:57<04:15,  5.31it/s]
 30%|███       | 585/1939 [00:57<04:22,  5.15it/s]
 30%|███       | 586/1939 [00:58<04:56,  4.57it/s]
 30%|███       | 588/1939 [00:58<03:47,  5.95it/s]
 31%|███       | 593/1939 [00:58<01:54, 11.79it/s]
 31%|███       | 595/1939 [00:58<02:12, 10.13it/s]
 31%|███       | 597/1939 [00:59<02:23,  9.34it/s]
 31%|███       | 599/1939 [00:59<02:47,  8.01it/s]
 31%|███       | 601/1939 [00:59<03:08,  7.11it/s]
 31%|███       | 603/1939 [00:59<02:34,  8.65it/s]
 31%|███▏      | 606/1939 [01:00<02:13,  9.96it/s]
 31%|███▏      | 608/1939 [01:00<03:29,  6.37it/s]
 31%|███▏      | 610/1939 [01:00<03:13,  6.86it/s]
 32%|███▏      | 611/1939 [01:01<03:51,  5.74it/s]
 32%|███▏      | 612/1939 [01:01<04:24,  5.02it/s]
 32%|███▏      | 613/1939 [01:01<05:00,  4.42it/s]
 32%|███▏      | 614/1939 [01:02<05:04,  4.35it/s]
 32%|███▏      | 615/1939 [01:02<04:22,  5.04it/s]
 32%|███▏      | 616/1939 [01:02<05:04,  4.34it/s]
 32%|███▏      | 617/1939 [01:02<05:27,  4.04it/s]
 32%|███▏      | 618/1939 [01:03<05:19,  4.13it/s]
 32%|███▏      | 620/1939 [01:03<04:47,  4.60it/s]
 32%|███▏      | 622/1939 [01:03<03:24,  6.45it/s]
 32%|███▏      | 624/1939 [01:03<03:08,  6.97it/s]
 32%|███▏      | 625/1939 [01:04<03:26,  6.37it/s]
 32%|███▏      | 627/1939 [01:04<02:38,  8.28it/s]
 32%|███▏      | 629/1939 [01:04<02:36,  8.38it/s]
 32%|███▏      | 630/1939 [01:04<03:30,  6.21it/s]
 33%|███▎      | 633/1939 [01:04<02:16,  9.55it/s]
 33%|███▎      | 635/1939 [01:05<02:25,  8.97it/s]
 33%|███▎      | 637/1939 [01:05<02:40,  8.09it/s]
 33%|███▎      | 639/1939 [01:05<02:19,  9.35it/s]
 33%|███▎      | 641/1939 [01:05<02:49,  7.66it/s]
 33%|███▎      | 643/1939 [01:06<02:36,  8.29it/s]
 33%|███▎      | 645/1939 [01:06<02:23,  9.04it/s]
 33%|███▎      | 647/1939 [01:06<02:20,  9.18it/s]
 33%|███▎      | 649/1939 [01:06<02:17,  9.37it/s]
 34%|███▎      | 651/1939 [01:06<01:57, 10.92it/s]
 34%|███▎      | 653/1939 [01:06<01:44, 12.26it/s]
 34%|███▍      | 655/1939 [01:07<02:24,  8.90it/s]
 34%|███▍      | 657/1939 [01:07<02:45,  7.73it/s]
 34%|███▍      | 658/1939 [01:07<03:29,  6.10it/s]
 34%|███▍      | 659/1939 [01:08<04:02,  5.28it/s]
 34%|███▍      | 661/1939 [01:08<03:03,  6.96it/s]
 34%|███▍      | 663/1939 [01:08<02:23,  8.88it/s]
 34%|███▍      | 665/1939 [01:08<03:09,  6.73it/s]
 34%|███▍      | 666/1939 [01:09<03:09,  6.73it/s]
 34%|███▍      | 668/1939 [01:09<02:35,  8.15it/s]
 35%|███▍      | 671/1939 [01:09<02:07,  9.96it/s]
 35%|███▍      | 673/1939 [01:09<02:36,  8.07it/s]
 35%|███▍      | 674/1939 [01:10<02:56,  7.15it/s]
 35%|███▍      | 676/1939 [01:10<02:22,  8.87it/s]
 35%|███▌      | 680/1939 [01:10<02:06,  9.98it/s]
 35%|███▌      | 682/1939 [01:10<02:19,  9.01it/s]
 35%|███▌      | 683/1939 [01:11<02:57,  7.09it/s]
 35%|███▌      | 685/1939 [01:11<03:02,  6.87it/s]
 35%|███▌      | 687/1939 [01:11<03:10,  6.57it/s]
 36%|███▌      | 689/1939 [01:12<03:17,  6.32it/s]
 36%|███▌      | 691/1939 [01:12<02:38,  7.86it/s]
 36%|███▌      | 692/1939 [01:12<03:13,  6.46it/s]
 36%|███▌      | 694/1939 [01:12<02:33,  8.12it/s]
 36%|███▌      | 700/1939 [01:12<01:16, 16.20it/s]
 36%|███▋      | 703/1939 [01:13<01:30, 13.66it/s]
 36%|███▋      | 706/1939 [01:13<01:16, 16.18it/s]
 37%|███▋      | 712/1939 [01:13<01:05, 18.81it/s]
 37%|███▋      | 715/1939 [01:13<01:10, 17.46it/s]
 37%|███▋      | 717/1939 [01:13<01:09, 17.64it/s]
 37%|███▋      | 721/1939 [01:13<01:03, 19.04it/s]
 37%|███▋      | 724/1939 [01:13<01:00, 20.06it/s]
 38%|███▊      | 729/1939 [01:14<00:47, 25.41it/s]
 38%|███▊      | 732/1939 [01:14<01:42, 11.75it/s]
 38%|███▊      | 735/1939 [01:15<01:48, 11.05it/s]
 38%|███▊      | 737/1939 [01:15<01:51, 10.75it/s]
 38%|███▊      | 739/1939 [01:15<02:03,  9.72it/s]
 38%|███▊      | 741/1939 [01:15<02:29,  8.03it/s]
 38%|███▊      | 743/1939 [01:16<02:32,  7.82it/s]
 38%|███▊      | 745/1939 [01:16<02:11,  9.05it/s]
 39%|███▊      | 749/1939 [01:16<01:54, 10.40it/s]
 39%|███▊      | 751/1939 [01:16<02:09,  9.20it/s]
 39%|███▉      | 753/1939 [01:17<01:52, 10.50it/s]
 39%|███▉      | 755/1939 [01:17<02:02,  9.67it/s]
 39%|███▉      | 757/1939 [01:17<01:50, 10.66it/s]
 39%|███▉      | 760/1939 [01:17<01:45, 11.18it/s]
 39%|███▉      | 762/1939 [01:17<01:51, 10.60it/s]
 39%|███▉      | 764/1939 [01:18<02:29,  7.84it/s]
 39%|███▉      | 765/1939 [01:18<02:42,  7.24it/s]
 40%|███▉      | 766/1939 [01:18<02:58,  6.59it/s]
 40%|███▉      | 767/1939 [01:19<03:29,  5.59it/s]
 40%|███▉      | 768/1939 [01:19<03:55,  4.97it/s]
 40%|███▉      | 769/1939 [01:19<04:30,  4.32it/s]
 40%|███▉      | 771/1939 [01:19<03:03,  6.37it/s]
 40%|███▉      | 772/1939 [01:20<03:39,  5.31it/s]
 40%|███▉      | 773/1939 [01:20<04:05,  4.75it/s]
 40%|███▉      | 775/1939 [01:20<02:51,  6.77it/s]
 40%|████      | 776/1939 [01:20<02:57,  6.55it/s]
 40%|████      | 777/1939 [01:20<03:39,  5.29it/s]
 40%|████      | 778/1939 [01:21<03:42,  5.21it/s]
 40%|████      | 779/1939 [01:21<04:18,  4.49it/s]
 40%|████      | 780/1939 [01:21<04:50,  3.99it/s]
 40%|████      | 782/1939 [01:22<03:50,  5.02it/s]
 40%|████      | 784/1939 [01:22<03:55,  4.91it/s]
 41%|████      | 786/1939 [01:22<03:02,  6.31it/s]
 41%|████      | 787/1939 [01:22<03:25,  5.60it/s]
 41%|████      | 788/1939 [01:22<03:19,  5.78it/s]
 41%|████      | 789/1939 [01:23<03:28,  5.52it/s]
 41%|████      | 791/1939 [01:23<02:27,  7.78it/s]
 41%|████      | 792/1939 [01:23<02:45,  6.94it/s]
 41%|████      | 793/1939 [01:23<03:16,  5.83it/s]
 41%|████      | 795/1939 [01:23<02:20,  8.17it/s]
 41%|████      | 798/1939 [01:24<02:14,  8.50it/s]
 41%|████▏     | 800/1939 [01:24<02:17,  8.28it/s]
 41%|████▏     | 802/1939 [01:24<02:23,  7.92it/s]
 41%|████▏     | 804/1939 [01:25<02:42,  6.98it/s]
 42%|████▏     | 806/1939 [01:25<02:56,  6.42it/s]
 42%|████▏     | 807/1939 [01:25<03:07,  6.04it/s]
 42%|████▏     | 809/1939 [01:26<03:14,  5.81it/s]
 42%|████▏     | 811/1939 [01:26<03:09,  5.96it/s]
 42%|████▏     | 812/1939 [01:26<03:41,  5.09it/s]
 42%|████▏     | 813/1939 [01:26<04:09,  4.52it/s]
 42%|████▏     | 815/1939 [01:27<03:26,  5.44it/s]
 42%|████▏     | 816/1939 [01:27<04:00,  4.66it/s]
 42%|████▏     | 817/1939 [01:27<04:34,  4.09it/s]
 42%|████▏     | 818/1939 [01:28<04:18,  4.33it/s]
 42%|████▏     | 819/1939 [01:28<05:02,  3.71it/s]
 42%|████▏     | 820/1939 [01:28<05:12,  3.58it/s]
 42%|████▏     | 821/1939 [01:29<05:31,  3.37it/s]
 42%|████▏     | 822/1939 [01:29<05:20,  3.49it/s]
 42%|████▏     | 823/1939 [01:29<05:31,  3.37it/s]
 43%|████▎     | 825/1939 [01:30<04:22,  4.25it/s]
 43%|████▎     | 828/1939 [01:30<02:43,  6.81it/s]
 43%|████▎     | 834/1939 [01:30<01:22, 13.44it/s]
 43%|████▎     | 839/1939 [01:30<00:57, 19.15it/s]
 43%|████▎     | 842/1939 [01:30<00:53, 20.67it/s]
 44%|████▎     | 845/1939 [01:30<01:11, 15.26it/s]
 44%|████▍     | 850/1939 [01:30<00:53, 20.50it/s]
 44%|████▍     | 853/1939 [01:31<01:02, 17.36it/s]
 44%|████▍     | 856/1939 [01:31<00:56, 19.21it/s]
 44%|████▍     | 859/1939 [01:31<01:25, 12.60it/s]
 45%|████▍     | 863/1939 [01:31<01:06, 16.15it/s]
 45%|████▍     | 866/1939 [01:32<01:27, 12.23it/s]
 45%|████▍     | 869/1939 [01:32<01:13, 14.52it/s]
 45%|████▍     | 872/1939 [01:32<01:21, 13.13it/s]
 45%|████▌     | 875/1939 [01:32<01:10, 15.12it/s]
 45%|████▌     | 878/1939 [01:33<01:23, 12.69it/s]
 46%|████▌     | 884/1939 [01:33<00:53, 19.71it/s]
 46%|████▌     | 888/1939 [01:33<00:49, 21.26it/s]
 46%|████▌     | 894/1939 [01:33<00:37, 28.22it/s]
 46%|████▋     | 900/1939 [01:33<00:44, 23.41it/s]
 47%|████▋     | 904/1939 [01:34<01:06, 15.64it/s]
 47%|████▋     | 907/1939 [01:34<01:15, 13.75it/s]
 47%|████▋     | 910/1939 [01:35<01:27, 11.83it/s]
 47%|████▋     | 913/1939 [01:35<01:29, 11.44it/s]
 47%|████▋     | 915/1939 [01:35<01:23, 12.28it/s]
 47%|████▋     | 917/1939 [01:35<01:32, 11.01it/s]
 47%|████▋     | 919/1939 [01:36<02:02,  8.34it/s]
 48%|████▊     | 922/1939 [01:36<01:50,  9.20it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 285.04it/s]
 50%|█████     | 151/300 [06:44<1:29:51, 36.19s/it]

[[np.int64(0), False, 2], [np.int64(1), False, 9], [np.int64(3), False, 6], [np.int64(4), False, 0], [np.int64(5), False, 1], [np.int64(7), False, 6], [np.int64(8), False, 10], [np.int64(10), False, 1], [np.int64(11), False, 6], [np.int64(12), False, 0], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0081, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.8437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9690, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [06:45<1:11:21, 28.93s/it]

tensor(12.8382, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0339, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [06:45<44:46, 18.40s/it]

tensor(12.8362, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1153, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8368, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1972, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2744, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [06:45<29:05, 12.12s/it]

tensor(12.8412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3403, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8411, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3715, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [06:45<19:20,  8.17s/it]

tensor(12.8376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3898, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [06:45<13:02,  5.59s/it]

tensor(12.8307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4004, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3960, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [06:45<08:53,  3.87s/it]

tensor(12.8057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3978, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [06:46<06:07,  2.70s/it]

tensor(12.7958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4238, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [06:46<04:14,  1.90s/it]

tensor(12.7905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4600, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7848, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4861, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4856, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [06:46<02:58,  1.35s/it]

tensor(12.7717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4835, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7637, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4815, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [06:46<02:06,  1.03it/s]

tensor(12.7556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4770, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [06:46<01:30,  1.42it/s]

tensor(12.7483, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4796, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7417, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4891, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4982, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [06:47<01:05,  1.92it/s]

tensor(12.7310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5062, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7257, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5071, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [06:47<00:48,  2.55it/s]

tensor(12.7199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5091, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [06:47<00:37,  3.29it/s]

tensor(12.7136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5137, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5290, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [06:47<00:28,  4.15it/s]

tensor(12.6947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5320, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5385, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [06:47<00:23,  5.08it/s]

tensor(12.6836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5408, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [06:48<00:19,  6.03it/s]

tensor(12.6783, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5498, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5548, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [06:48<00:16,  6.92it/s]

tensor(12.6620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5591, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5582, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [06:48<00:14,  7.75it/s]

tensor(12.6526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5578, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [06:48<00:13,  8.43it/s]

tensor(12.6487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5592, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5600, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5627, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [06:48<00:11,  9.00it/s]

tensor(12.6372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5665, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5695, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [06:48<00:11,  9.39it/s]

tensor(12.6287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5711, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [06:49<00:10,  9.67it/s]

tensor(12.6241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5703, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5730, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5755, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [06:49<00:10,  9.88it/s]

tensor(12.6116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5759, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5756, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [06:49<00:09, 10.11it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([156,  48, 134, 296, 149,  81, 215, 119, 208,  98,  79,  88, 151, 117])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:39, 19.53it/s]
  0%|          | 6/1939 [00:00<01:39, 19.49it/s]
  1%|          | 10/1939 [00:00<01:12, 26.65it/s]
  1%|          | 14/1939 [00:00<01:02, 30.66it/s]
  1%|          | 21/1939 [00:00<00:51, 37.54it/s]
  1%|▏         | 27/1939 [00:00<00:50, 37.80it/s]
  2%|▏         | 31/1939 [00:00<00:49, 38.37it/s]
  2%|▏         | 39/1939 [00:01<00:38, 49.36it/s]
  2%|▏         | 45/1939 [00:01<01:44, 18.21it/s]
  3%|▎         | 49/1939 [00:02<02:03, 15.36it/s]
  3%|▎         | 52/1939 [00:02<01:54, 16.46it/s]
  3%|▎         | 55/1939 [00:02<02:34, 12.22it/s]
  3%|▎         | 58/1939 [00:03<02:56, 10.68it/s]
  3%|▎         | 61/1939 [00:03<02:28, 12.65it/s]
  3%|▎         | 66/1939 [00:03<02:31, 12.39it/s]
  4%|▎         | 68/1939 [00:03<02:21, 13.26it/s]
  4%|▍         | 73/1939 [00:04<02:28, 12.60it/s]
  4%|▍         | 76/1939 [00:04<02:09, 14.33it/s]
  4%|▍         | 78/1939 [00:04<02:52, 10.77it/s]
  4%|▍         | 80/1939 [00:05<03:36,  8.58it/s]
  4%|▍         | 82/1939 [00:05<04:13,  7.34it/s]
  4%|▍         | 84/1939 [00:05<04:48,  6.43it/s]
  4%|▍         | 86/1939 [00:06<05:14,  5.89it/s]
  4%|▍         | 87/1939 [00:06<06:06,  5.05it/s]
  5%|▍         | 90/1939 [00:06<04:08,  7.44it/s]
  5%|▍         | 94/1939 [00:07<03:33,  8.65it/s]
  5%|▍         | 96/1939 [00:07<03:10,  9.65it/s]
  5%|▌         | 100/1939 [00:07<03:09,  9.73it/s]
  5%|▌         | 103/1939 [00:07<02:35, 11.79it/s]
  6%|▌         | 109/1939 [00:07<01:37, 18.69it/s]
  6%|▌         | 115/1939 [00:08<01:10, 25.71it/s]
  6%|▌         | 119/1939 [00:08<01:46, 17.07it/s]
  6%|▋         | 122/1939 [00:09<02:27, 12.31it/s]
  7%|▋         | 129/1939 [00:09<01:35, 19.02it/s]
  7%|▋         | 133/1939 [00:09<02:04, 14.50it/s]
  7%|▋         | 136/1939 [00:09<01:51, 16.11it/s]
  7%|▋         | 139/1939 [00:10<02:29, 12.03it/s]
  7%|▋         | 144/1939 [00:10<01:49, 16.40it/s]
  8%|▊         | 147/1939 [00:10<02:31, 11.86it/s]
  8%|▊         | 153/1939 [00:11<02:30, 11.89it/s]
  8%|▊         | 155/1939 [00:11<02:24, 12.33it/s]
 67%|██████▋   | 200/300 [07:04<00:09, 10.11it/s]]
  8%|▊         | 160/1939 [00:12<03:19,  8.93it/s]
  8%|▊         | 162/1939 [00:12<02:56, 10.07it/s]
  8%|▊         | 164/1939 [00:12<03:37,  8.16it/s]
  9%|▊         | 166/1939 [00:12<03:06,  9.50it/s]
  9%|▊         | 168/1939 [00:12<02:40, 11.01it/s]
  9%|▉         | 173/1939 [00:12<01:40, 17.58it/s]
  9%|▉         | 176/1939 [00:13<01:30, 19.49it/s]
  9%|▉         | 179/1939 [00:13<01:22, 21.30it/s]
 10%|▉         | 185/1939 [00:13<00:59, 29.50it/s]
 10%|▉         | 192/1939 [00:13<00:45, 38.10it/s]
 10%|█         | 199/1939 [00:13<00:38, 45.02it/s]
 11%|█         | 204/1939 [00:14<01:24, 20.44it/s]
 11%|█         | 208/1939 [00:14<02:09, 13.39it/s]
 11%|█         | 211/1939 [00:14<02:03, 14.03it/s]
 11%|█         | 217/1939 [00:14<01:28, 19.47it/s]
 12%|█▏        | 223/1939 [00:15<01:07, 25.39it/s]
 12%|█▏        | 228/1939 [00:15<01:30, 18.97it/s]
 12%|█▏        | 232/1939 [00:15<01:29, 19.14it/s]
 12%|█▏        | 235/1939 [00:16<02:18, 12.35it/s]
 12%|█▏        | 238/1939 [00:16<02:24, 11.78it/s]
 12%|█▏        | 240/1939 [00:17<03:13,  8.76it/s]
 12%|█▏        | 242/1939 [00:17<03:31,  8.01it/s]
 13%|█▎        | 244/1939 [00:17<04:09,  6.80it/s]
 13%|█▎        | 245/1939 [00:18<04:59,  5.65it/s]
 13%|█▎        | 246/1939 [00:18<05:43,  4.93it/s]
 13%|█▎        | 248/1939 [00:18<05:42,  4.94it/s]
 13%|█▎        | 250/1939 [00:19<04:25,  6.36it/s]
 13%|█▎        | 256/1939 [00:19<02:08, 13.06it/s]
 13%|█▎        | 259/1939 [00:19<02:40, 10.47it/s]
 13%|█▎        | 261/1939 [00:20<03:27,  8.10it/s]
 14%|█▎        | 263/1939 [00:20<03:58,  7.02it/s]
 14%|█▎        | 265/1939 [00:20<03:22,  8.27it/s]
 14%|█▍        | 272/1939 [00:20<01:44, 15.88it/s]
 14%|█▍        | 278/1939 [00:20<01:14, 22.39it/s]
 15%|█▍        | 282/1939 [00:21<01:42, 16.09it/s]
 15%|█▍        | 285/1939 [00:21<01:32, 17.89it/s]
 15%|█▌        | 292/1939 [00:21<01:02, 26.36it/s]
 15%|█▌        | 298/1939 [00:21<00:50, 32.32it/s]
 16%|█▌        | 304/1939 [00:21<00:44, 36.91it/s]
 16%|█▌        | 309/1939 [00:22<01:14, 21.85it/s]
 16%|█▌        | 315/1939 [00:22<01:00, 26.97it/s]
 17%|█▋        | 320/1939 [00:22<00:52, 30.85it/s]
 17%|█▋        | 325/1939 [00:22<01:23, 19.25it/s]
 17%|█▋        | 332/1939 [00:22<01:01, 26.10it/s]
 17%|█▋        | 338/1939 [00:23<00:51, 30.95it/s]
 18%|█▊        | 343/1939 [00:23<01:23, 19.09it/s]
 18%|█▊        | 350/1939 [00:23<01:02, 25.26it/s]
 18%|█▊        | 355/1939 [00:24<02:09, 12.25it/s]
 19%|█▊        | 359/1939 [00:24<01:49, 14.37it/s]
 19%|█▉        | 364/1939 [00:24<01:27, 18.06it/s]
 19%|█▉        | 368/1939 [00:25<01:15, 20.88it/s]
 19%|█▉        | 374/1939 [00:25<00:59, 26.18it/s]
 20%|█▉        | 379/1939 [00:25<01:25, 18.29it/s]
 20%|█▉        | 383/1939 [00:26<01:53, 13.67it/s]
 20%|█▉        | 386/1939 [00:26<02:25, 10.64it/s]
 20%|██        | 388/1939 [00:27<02:54,  8.90it/s]
 20%|██        | 390/1939 [00:27<03:22,  7.63it/s]
 20%|██        | 392/1939 [00:27<02:59,  8.60it/s]
 20%|██        | 394/1939 [00:27<03:24,  7.57it/s]
 20%|██        | 396/1939 [00:28<03:56,  6.53it/s]
 20%|██        | 397/1939 [00:28<04:44,  5.41it/s]
 21%|██        | 399/1939 [00:28<03:51,  6.66it/s]
 21%|██        | 402/1939 [00:28<02:41,  9.51it/s]
 21%|██        | 404/1939 [00:29<03:15,  7.87it/s]
 21%|██        | 406/1939 [00:29<03:33,  7.18it/s]
 21%|██        | 408/1939 [00:30<03:58,  6.41it/s]
 21%|██        | 410/1939 [00:30<03:14,  7.88it/s]
 21%|██        | 412/1939 [00:30<03:19,  7.64it/s]
 21%|██▏       | 415/1939 [00:30<02:44,  9.24it/s]
 22%|██▏       | 417/1939 [00:30<03:00,  8.45it/s]
 22%|██▏       | 419/1939 [00:31<03:46,  6.71it/s]
 22%|██▏       | 421/1939 [00:31<03:10,  7.99it/s]
 22%|██▏       | 423/1939 [00:31<03:15,  7.76it/s]
 22%|██▏       | 426/1939 [00:32<03:24,  7.39it/s]
 22%|██▏       | 428/1939 [00:32<03:02,  8.27it/s]
 22%|██▏       | 431/1939 [00:32<02:19, 10.79it/s]
 22%|██▏       | 436/1939 [00:32<01:29, 16.73it/s]
 23%|██▎       | 439/1939 [00:32<01:24, 17.82it/s]
 23%|██▎       | 442/1939 [00:32<01:15, 19.76it/s]
 23%|██▎       | 448/1939 [00:33<00:53, 27.81it/s]
 23%|██▎       | 454/1939 [00:33<00:43, 34.03it/s]
 24%|██▎       | 460/1939 [00:33<00:36, 40.05it/s]
 24%|██▍       | 466/1939 [00:33<00:32, 45.14it/s]
 24%|██▍       | 472/1939 [00:33<00:30, 48.38it/s]
 25%|██▍       | 478/1939 [00:33<00:32, 44.96it/s]
 25%|██▍       | 483/1939 [00:33<00:50, 28.88it/s]
 25%|██▌       | 489/1939 [00:34<00:48, 29.80it/s]
 25%|██▌       | 493/1939 [00:34<00:51, 28.01it/s]
 26%|██▌       | 497/1939 [00:34<00:49, 29.12it/s]
 26%|██▌       | 502/1939 [00:34<00:43, 33.24it/s]
 26%|██▌       | 508/1939 [00:34<00:36, 39.28it/s]
 27%|██▋       | 514/1939 [00:34<00:32, 43.57it/s]
 27%|██▋       | 520/1939 [00:34<00:30, 46.00it/s]
 27%|██▋       | 527/1939 [00:34<00:27, 50.75it/s]
 27%|██▋       | 533/1939 [00:35<00:26, 52.65it/s]
 28%|██▊       | 539/1939 [00:35<00:54, 25.80it/s]
 28%|██▊       | 546/1939 [00:35<00:54, 25.55it/s]
 28%|██▊       | 550/1939 [00:36<00:53, 25.99it/s]
 29%|██▊       | 554/1939 [00:36<01:07, 20.49it/s]
 29%|██▉       | 561/1939 [00:36<00:50, 27.32it/s]
 29%|██▉       | 566/1939 [00:36<00:44, 30.87it/s]
 29%|██▉       | 571/1939 [00:36<00:43, 31.47it/s]
 30%|██▉       | 575/1939 [00:37<01:25, 15.91it/s]
 30%|██▉       | 578/1939 [00:37<01:20, 16.82it/s]
 30%|██▉       | 581/1939 [00:37<01:43, 13.09it/s]
 30%|███       | 584/1939 [00:38<01:51, 12.16it/s]
 30%|███       | 586/1939 [00:38<02:24,  9.38it/s]
 30%|███       | 588/1939 [00:38<02:10, 10.35it/s]
 30%|███       | 590/1939 [00:38<01:55, 11.63it/s]
 31%|███       | 596/1939 [00:38<01:10, 18.99it/s]
 31%|███       | 599/1939 [00:39<01:33, 14.35it/s]
 31%|███       | 602/1939 [00:39<02:04, 10.74it/s]
 31%|███       | 604/1939 [00:39<01:52, 11.88it/s]
 31%|███▏      | 606/1939 [00:39<01:43, 12.84it/s]
 31%|███▏      | 608/1939 [00:40<02:25,  9.15it/s]
 32%|███▏      | 611/1939 [00:40<02:52,  7.70it/s]
 32%|███▏      | 613/1939 [00:41<03:33,  6.22it/s]
 32%|███▏      | 614/1939 [00:41<04:02,  5.46it/s]
 32%|███▏      | 615/1939 [00:42<04:33,  4.84it/s]
 32%|███▏      | 616/1939 [00:42<04:28,  4.93it/s]
 32%|███▏      | 618/1939 [00:42<04:23,  5.02it/s]
 32%|███▏      | 620/1939 [00:42<04:06,  5.36it/s]
 32%|███▏      | 622/1939 [00:43<03:57,  5.54it/s]
 32%|███▏      | 624/1939 [00:43<03:08,  6.99it/s]
 32%|███▏      | 630/1939 [00:43<02:07, 10.23it/s]
 33%|███▎      | 632/1939 [00:43<01:56, 11.25it/s]
 33%|███▎      | 636/1939 [00:44<02:14,  9.72it/s]
 33%|███▎      | 638/1939 [00:44<02:02, 10.58it/s]
 33%|███▎      | 643/1939 [00:44<01:54, 11.31it/s]
 33%|███▎      | 646/1939 [00:45<01:36, 13.43it/s]
 34%|███▎      | 651/1939 [00:45<01:39, 12.95it/s]
 34%|███▎      | 653/1939 [00:45<01:36, 13.34it/s]
 34%|███▍      | 655/1939 [00:45<02:08,  9.97it/s]
 34%|███▍      | 657/1939 [00:46<02:37,  8.15it/s]
 34%|███▍      | 659/1939 [00:47<04:01,  5.30it/s]
 34%|███▍      | 661/1939 [00:47<03:23,  6.28it/s]
 34%|███▍      | 663/1939 [00:47<02:49,  7.53it/s]
 34%|███▍      | 665/1939 [00:47<03:23,  6.26it/s]
 34%|███▍      | 666/1939 [00:48<03:56,  5.38it/s]
 34%|███▍      | 668/1939 [00:48<03:09,  6.70it/s]
 35%|███▍      | 672/1939 [00:48<02:48,  7.53it/s]
 35%|███▍      | 675/1939 [00:48<02:06, 10.01it/s]
 35%|███▌      | 680/1939 [00:49<01:57, 10.69it/s]
 35%|███▌      | 683/1939 [00:49<02:15,  9.27it/s]
 35%|███▌      | 685/1939 [00:49<02:03, 10.17it/s]
 36%|███▌      | 689/1939 [00:50<02:07,  9.79it/s]
 36%|███▌      | 691/1939 [00:50<01:57, 10.65it/s]
 36%|███▌      | 693/1939 [00:50<02:33,  8.12it/s]
 36%|███▌      | 697/1939 [00:51<01:46, 11.64it/s]
 36%|███▌      | 701/1939 [00:51<01:19, 15.65it/s]
 37%|███▋      | 708/1939 [00:51<00:50, 24.50it/s]
 37%|███▋      | 714/1939 [00:51<00:40, 30.52it/s]
 37%|███▋      | 720/1939 [00:51<00:34, 35.69it/s]
 37%|███▋      | 725/1939 [00:51<00:34, 35.46it/s]
 38%|███▊      | 730/1939 [00:52<00:55, 21.64it/s]
 38%|███▊      | 734/1939 [00:52<01:48, 11.10it/s]
 38%|███▊      | 737/1939 [00:53<01:34, 12.73it/s]
 38%|███▊      | 740/1939 [00:53<01:51, 10.71it/s]
 38%|███▊      | 742/1939 [00:53<02:17,  8.69it/s]
 38%|███▊      | 744/1939 [00:54<02:04,  9.59it/s]
 39%|███▊      | 749/1939 [00:54<01:21, 14.53it/s]
 39%|███▉      | 754/1939 [00:54<01:00, 19.49it/s]
 39%|███▉      | 758/1939 [00:54<01:30, 13.12it/s]
 39%|███▉      | 761/1939 [00:55<01:47, 10.99it/s]
 39%|███▉      | 763/1939 [00:55<02:12,  8.90it/s]
 39%|███▉      | 765/1939 [00:55<01:58,  9.88it/s]
 40%|███▉      | 767/1939 [00:56<03:09,  6.18it/s]
 40%|███▉      | 769/1939 [00:56<03:18,  5.90it/s]
 40%|███▉      | 770/1939 [00:57<03:51,  5.06it/s]
 40%|███▉      | 772/1939 [00:57<03:51,  5.04it/s]
 40%|███▉      | 773/1939 [00:57<04:32,  4.28it/s]
 40%|███▉      | 775/1939 [00:58<03:22,  5.75it/s]
 40%|████      | 776/1939 [00:58<03:51,  5.02it/s]
 40%|████      | 777/1939 [00:58<04:35,  4.22it/s]
 40%|████      | 778/1939 [00:58<03:57,  4.88it/s]
 40%|████      | 779/1939 [00:59<03:43,  5.20it/s]
 40%|████      | 780/1939 [00:59<04:02,  4.79it/s]
 40%|████      | 782/1939 [00:59<02:45,  7.01it/s]
 40%|████      | 784/1939 [00:59<02:30,  7.65it/s]
 41%|████      | 786/1939 [00:59<02:00,  9.58it/s]
 41%|████      | 788/1939 [01:00<02:13,  8.63it/s]
 41%|████      | 790/1939 [01:00<02:15,  8.46it/s]
 41%|████      | 792/1939 [01:00<01:57,  9.72it/s]
 41%|████      | 798/1939 [01:00<01:14, 15.21it/s]
 41%|████▏     | 800/1939 [01:00<01:16, 14.93it/s]
 41%|████▏     | 804/1939 [01:00<01:09, 16.27it/s]
 42%|████▏     | 806/1939 [01:01<01:36, 11.72it/s]
 42%|████▏     | 808/1939 [01:01<01:31, 12.40it/s]
 42%|████▏     | 810/1939 [01:01<02:18,  8.13it/s]
 42%|████▏     | 812/1939 [01:02<02:46,  6.79it/s]
 42%|████▏     | 813/1939 [01:02<03:04,  6.09it/s]
 42%|████▏     | 815/1939 [01:02<02:28,  7.56it/s]
 42%|████▏     | 817/1939 [01:03<03:25,  5.47it/s]
 42%|████▏     | 818/1939 [01:03<03:34,  5.23it/s]
 42%|████▏     | 819/1939 [01:03<03:52,  4.82it/s]
 42%|████▏     | 820/1939 [01:04<04:38,  4.02it/s]
 42%|████▏     | 821/1939 [01:04<05:06,  3.65it/s]
 42%|████▏     | 822/1939 [01:04<05:28,  3.40it/s]
 42%|████▏     | 823/1939 [01:05<05:47,  3.21it/s]
 43%|████▎     | 825/1939 [01:05<04:57,  3.75it/s]
 43%|████▎     | 827/1939 [01:05<03:31,  5.25it/s]
 43%|████▎     | 833/1939 [01:05<01:33, 11.88it/s]
 43%|████▎     | 839/1939 [01:06<00:58, 18.93it/s]
 44%|████▎     | 844/1939 [01:06<00:46, 23.59it/s]
 44%|████▍     | 850/1939 [01:06<00:36, 30.13it/s]
 44%|████▍     | 855/1939 [01:06<00:32, 33.22it/s]
 44%|████▍     | 860/1939 [01:06<00:55, 19.50it/s]
 45%|████▍     | 865/1939 [01:07<00:45, 23.82it/s]
 45%|████▍     | 869/1939 [01:07<00:41, 25.91it/s]
 45%|████▌     | 873/1939 [01:07<00:37, 28.20it/s]
 45%|████▌     | 878/1939 [01:07<00:32, 32.65it/s]
 46%|████▌     | 884/1939 [01:07<00:29, 35.29it/s]
 46%|████▌     | 889/1939 [01:07<00:28, 37.34it/s]
 46%|████▌     | 895/1939 [01:07<00:25, 41.31it/s]
 46%|████▋     | 900/1939 [01:08<00:51, 20.37it/s]
 47%|████▋     | 904/1939 [01:08<01:00, 17.05it/s]
 47%|████▋     | 907/1939 [01:08<00:55, 18.62it/s]
 47%|████▋     | 910/1939 [01:09<01:07, 15.24it/s]
 47%|████▋     | 913/1939 [01:09<01:05, 15.64it/s]
 47%|████▋     | 916/1939 [01:09<01:00, 16.85it/s]
 47%|████▋     | 919/1939 [01:09<01:23, 12.16it/s]
 48%|████▊     | 923/1939 [01:09<01:04, 15.68it/s]
 48%|████▊     | 927/1939 [01:10<01:19, 12.72it/s]
 48%|████▊     | 929/1939 [01:10<01:14, 13.65it/s]
 48%|████▊     | 931/1939 [01:11<02:02,  8.25it/s]
 48%|████▊     | 933/1939 [01:11<01:51,  9.05it/s]
 48%|████▊     | 935/1939 [01:11<01:36, 10.38it/s]
 49%|████▊     | 943/1939 [01:11<00:47, 20.88it/s]
 49%|████▉     | 947/1939 [01:11<00:41, 23.90it/s]
 49%|████▉     | 951/1939 [01:11<00:45, 21.64it/s]
 49%|████▉     | 954/1939 [01:11<00:43, 22.65it/s]
 50%|████▉     | 960/1939 [01:11<00:33, 29.57it/s]
 50%|████▉     | 966/1939 [01:12<00:27, 35.72it/s]
 50%|█████     | 971/1939 [01:12<01:03, 15.27it/s]
 50%|█████     | 975/1939 [01:13<01:16, 12.55it/s]
 50%|█████     | 978/1939 [01:13<01:23, 11.54it/s]
 51%|█████     | 980/1939 [01:13<01:26, 11.12it/s]
 51%|█████     | 982/1939 [01:14<01:42,  9.33it/s]
 51%|█████     | 984/1939 [01:14<01:32, 10.29it/s]
 51%|█████     | 986/1939 [01:14<01:23, 11.46it/s]
 51%|█████     | 991/1939 [01:14<01:22, 11.43it/s]
 51%|█████     | 993/1939 [01:15<01:17, 12.17it/s]
 51%|█████▏    | 997/1939 [01:15<01:22, 11.35it/s]
 52%|█████▏    | 999/1939 [01:15<01:53,  8.31it/s]
 52%|█████▏    | 1001/1939 [01:16<01:39,  9.44it/s]
 52%|█████▏    | 1003/1939 [01:16<02:03,  7.58it/s]
 52%|█████▏    | 1005/1939 [01:16<02:22,  6.57it/s]
 52%|█████▏    | 1006/1939 [01:17<02:56,  5.30it/s]
 52%|█████▏    | 1008/1939 [01:17<02:18,  6.72it/s]
 52%|█████▏    | 1009/1939 [01:17<02:55,  5.31it/s]
 52%|█████▏    | 1010/1939 [01:18<03:32,  4.38it/s]
 52%|█████▏    | 1011/1939 [01:18<04:01,  3.84it/s]
 52%|█████▏    | 1012/1939 [01:18<04:35,  3.36it/s]
 52%|█████▏    | 1014/1939 [01:19<03:51,  3.99it/s]
 52%|█████▏    | 1015/1939 [01:19<04:08,  3.72it/s]
 52%|█████▏    | 1016/1939 [01:19<04:21,  3.52it/s]
 53%|█████▎    | 1018/1939 [01:20<03:40,  4.18it/s]
 53%|█████▎    | 1019/1939 [01:20<03:57,  3.88it/s]
 53%|█████▎    | 1021/1939 [01:20<02:47,  5.47it/s]
 53%|█████▎    | 1022/1939 [01:21<03:07,  4.89it/s]
 53%|█████▎    | 1025/1939 [01:21<02:00,  7.58it/s]
 53%|█████▎    | 1027/1939 [01:21<01:38,  9.24it/s]
 53%|█████▎    | 1031/1939 [01:21<01:02, 14.50it/s]
 53%|█████▎    | 1036/1939 [01:21<00:43, 20.71it/s]
 54%|█████▎    | 1041/1939 [01:21<00:34, 25.80it/s]
 54%|█████▍    | 1046/1939 [01:21<00:29, 30.73it/s]
 54%|█████▍    | 1051/1939 [01:21<00:25, 35.37it/s]
 54%|█████▍    | 1055/1939 [01:22<01:07, 13.07it/s]
 55%|█████▍    | 1058/1939 [01:23<01:21, 10.85it/s]
 55%|█████▍    | 1061/1939 [01:23<01:44,  8.40it/s]
 55%|█████▍    | 1064/1939 [01:23<01:26, 10.09it/s]
 55%|█████▌    | 1067/1939 [01:23<01:12, 12.05it/s]
 55%|█████▌    | 1070/1939 [01:24<01:17, 11.25it/s]
 55%|█████▌    | 1072/1939 [01:24<01:12, 12.02it/s]
 55%|█████▌    | 1074/1939 [01:24<01:07, 12.77it/s]
 56%|█████▌    | 1080/1939 [01:24<00:53, 16.05it/s]
 56%|█████▌    | 1082/1939 [01:24<00:55, 15.46it/s]
 56%|█████▌    | 1086/1939 [01:25<00:43, 19.51it/s]
 56%|█████▌    | 1089/1939 [01:25<01:05, 13.06it/s]
 56%|█████▋    | 1092/1939 [01:25<01:24, 10.04it/s]
 56%|█████▋    | 1094/1939 [01:26<01:45,  7.99it/s]
 57%|█████▋    | 1096/1939 [01:26<01:33,  9.03it/s]
 57%|█████▋    | 1101/1939 [01:26<00:58, 14.34it/s]
 57%|█████▋    | 1104/1939 [01:27<01:17, 10.81it/s]
 57%|█████▋    | 1106/1939 [01:27<01:33,  8.88it/s]
 57%|█████▋    | 1108/1939 [01:27<01:23,  9.95it/s]
 57%|█████▋    | 1113/1939 [01:27<00:53, 15.41it/s]
 58%|█████▊    | 1116/1939 [01:28<01:08, 11.94it/s]
 58%|█████▊    | 1118/1939 [01:28<01:03, 12.84it/s]
 58%|█████▊    | 1123/1939 [01:28<00:43, 18.77it/s]
 58%|█████▊    | 1126/1939 [01:28<00:40, 20.12it/s]
 58%|█████▊    | 1129/1939 [01:28<00:52, 15.46it/s]
 58%|█████▊    | 1132/1939 [01:28<00:48, 16.55it/s]
 59%|█████▊    | 1135/1939 [01:29<00:51, 15.76it/s]
 59%|█████▊    | 1137/1939 [01:29<01:14, 10.83it/s]
 59%|█████▊    | 1139/1939 [01:29<01:06, 12.10it/s]
 59%|█████▉    | 1142/1939 [01:29<01:17, 10.23it/s]
 59%|█████▉    | 1144/1939 [01:30<01:30,  8.80it/s]
 59%|█████▉    | 1146/1939 [01:30<01:29,  8.89it/s]
 59%|█████▉    | 1148/1939 [01:30<01:36,  8.16it/s]
 59%|█████▉    | 1150/1939 [01:31<01:50,  7.12it/s]
 59%|█████▉    | 1151/1939 [01:31<02:03,  6.41it/s]
 59%|█████▉    | 1153/1939 [01:31<02:12,  5.92it/s]
 60%|█████▉    | 1155/1939 [01:31<01:45,  7.45it/s]
 60%|█████▉    | 1157/1939 [01:32<01:27,  8.91it/s]
 60%|█████▉    | 1159/1939 [01:32<01:13, 10.55it/s]
 60%|█████▉    | 1161/1939 [01:32<01:45,  7.37it/s]
 60%|█████▉    | 1163/1939 [01:32<01:50,  7.02it/s]
 60%|██████    | 1165/1939 [01:33<01:32,  8.38it/s]
 60%|██████    | 1167/1939 [01:33<01:16, 10.03it/s]
 60%|██████    | 1172/1939 [01:33<01:12, 10.53it/s]
 61%|██████    | 1174/1939 [01:33<01:04, 11.78it/s]
 61%|██████    | 1176/1939 [01:33<01:00, 12.59it/s]
 61%|██████    | 1178/1939 [01:34<01:10, 10.83it/s]
 61%|██████    | 1180/1939 [01:34<01:19,  9.52it/s]
 61%|██████    | 1183/1939 [01:34<01:13, 10.34it/s]
 61%|██████    | 1185/1939 [01:34<01:09, 10.91it/s]
 61%|██████    | 1187/1939 [01:35<01:20,  9.30it/s]
 61%|██████▏   | 1189/1939 [01:35<01:11, 10.48it/s]
 61%|██████▏   | 1191/1939 [01:35<02:07,  5.86it/s]
 62%|██████▏   | 1193/1939 [01:36<02:11,  5.67it/s]
 62%|██████▏   | 1196/1939 [01:36<02:02,  6.08it/s]
 62%|██████▏   | 1197/1939 [01:36<02:04,  5.95it/s]
 62%|██████▏   | 1199/1939 [01:37<01:43,  7.14it/s]
 62%|██████▏   | 1206/1939 [01:37<00:47, 15.38it/s]
 62%|██████▏   | 1209/1939 [01:37<00:42, 16.99it/s]
 63%|██████▎   | 1215/1939 [01:37<00:30, 23.97it/s]
 63%|██████▎   | 1219/1939 [01:38<00:55, 12.94it/s]
 63%|██████▎   | 1222/1939 [01:38<00:52, 13.78it/s]
 63%|██████▎   | 1226/1939 [01:38<00:59, 11.97it/s]
 63%|██████▎   | 1230/1939 [01:38<00:49, 14.39it/s]
 64%|██████▎   | 1233/1939 [01:39<01:01, 11.52it/s]
 64%|██████▎   | 1236/1939 [01:39<00:51, 13.64it/s]
 64%|██████▍   | 1239/1939 [01:39<01:01, 11.36it/s]
 64%|██████▍   | 1241/1939 [01:39<00:57, 12.17it/s]
 64%|██████▍   | 1247/1939 [01:39<00:36, 18.97it/s]
 65%|██████▍   | 1251/1939 [01:40<00:48, 14.23it/s]
 65%|██████▍   | 1254/1939 [01:40<01:04, 10.66it/s]
 65%|██████▍   | 1256/1939 [01:41<01:00, 11.30it/s]
 65%|██████▌   | 1262/1939 [01:41<00:38, 17.73it/s]
 65%|██████▌   | 1267/1939 [01:41<00:31, 21.67it/s]
 66%|██████▌   | 1272/1939 [01:41<00:25, 26.28it/s]
 66%|██████▌   | 1278/1939 [01:41<00:21, 30.65it/s]
 66%|██████▌   | 1283/1939 [01:41<00:19, 33.51it/s]
 66%|██████▋   | 1287/1939 [01:42<00:32, 20.00it/s]
 67%|██████▋   | 1291/1939 [01:42<00:39, 16.28it/s]
 67%|██████▋   | 1294/1939 [01:42<00:36, 17.86it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 324.07it/s]
 67%|██████▋   | 201/300 [09:18<43:36, 26.42s/it]

[[np.int64(0), False, 2], [np.int64(1), False, 11], [np.int64(2), False, 9], [np.int64(3), False, 8], [np.int64(4), False, 13], [np.int64(5), False, 12], [np.int64(6), False, 3], [np.int64(7), False, 11], [np.int64(10), False, 11], [np.int64(12), False, 8]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.6044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0015, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.6033, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3537, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 202/300 [09:18<34:30, 21.13s/it]

tensor(12.6110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7897, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [09:19<26:34, 16.44s/it]

tensor(12.6281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9521, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:19<15:56, 10.07s/it]

tensor(12.6493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9882, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0388, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9600, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0428, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9666, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [09:19<10:04,  6.50s/it]

tensor(12.6600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0458, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0105, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0476, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9354, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:19<06:34,  4.34s/it]

tensor(12.6319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0482, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9620, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:19<04:23,  2.96s/it]

tensor(12.6263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0477, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9724, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0467, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6250, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0455, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0323, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:20<02:58,  2.05s/it]

tensor(12.6248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0500, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6240, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0427, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0632, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [09:20<02:02,  1.44s/it]

tensor(12.6217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0415, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0716, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [09:20<01:25,  1.02s/it]

tensor(12.6183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1227, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1401, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1257, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:20<00:59,  1.35it/s]

tensor(12.6113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0332, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9092, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [09:20<00:42,  1.84it/s]

tensor(12.6063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9284, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [09:20<00:31,  2.45it/s]

tensor(12.6022, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8905, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9383, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1572, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:21<00:23,  3.18it/s]

tensor(12.6098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2898, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1967, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:21<00:18,  4.03it/s]

tensor(12.6182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1877, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:21<00:14,  4.94it/s]

tensor(12.6123, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3452, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3743, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3703, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [09:21<00:11,  5.87it/s]

tensor(12.6001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3320, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3272, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [09:21<00:09,  6.76it/s]

tensor(12.5925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3275, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:22<00:08,  7.56it/s]

tensor(12.5891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3572, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5853, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3751, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3804, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [09:22<00:07,  8.16it/s]

tensor(12.5754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3755, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3536, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:22<00:07,  8.68it/s]

tensor(12.5671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3524, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [09:22<00:06,  9.17it/s]

tensor(12.5612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3602, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3789, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5470, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3967, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:22<00:05,  9.50it/s]

tensor(12.5416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4080, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4215, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:23<00:05,  9.75it/s]

tensor(12.5342, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4242, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [09:23<00:05,  9.88it/s]

tensor(12.5301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4264, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4323, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4303, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [09:23<00:05, 10.00it/s]

tensor(12.5172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4334, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([147, 233, 321, 124, 197, 118,  92, 135, 125, 172, 107,  58,  32,  78])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<02:13, 14.49it/s]
  0%|          | 7/1939 [00:00<01:00, 31.92it/s]
  1%|          | 12/1939 [00:00<00:52, 36.48it/s]
  1%|          | 16/1939 [00:00<01:07, 28.50it/s]
  1%|          | 20/1939 [00:00<01:01, 31.07it/s]
  1%|          | 24/1939 [00:00<00:59, 32.11it/s]
  1%|▏         | 28/1939 [00:00<01:01, 31.20it/s]
  2%|▏         | 33/1939 [00:01<00:55, 34.17it/s]
  2%|▏         | 39/1939 [00:01<00:50, 37.98it/s]
  2%|▏         | 43/1939 [00:02<02:23, 13.17it/s]
  2%|▏         | 46/1939 [00:02<02:14, 14.11it/s]
  3%|▎         | 49/1939 [00:02<03:45,  8.38it/s]
  3%|▎         | 51/1939 [00:03<03:31,  8.92it/s]
  3%|▎         | 53/1939 [00:03<05:34,  5.63it/s]
  3%|▎         | 55/1939 [00:04<04:42,  6.67it/s]
  3%|▎         | 58/1939 [00:04<05:53,  5.32it/s]
  3%|▎         | 60/1939 [00:05<04:56,  6.34it/s]
  3%|▎         | 66/1939 [00:05<04:35,  6.80it/s]
  4%|▎         | 68/1939 [00:05<04:02,  7.70it/s]
  4%|▍         | 73/1939 [00:06<04:27,  6.99it/s]
  4%|▍         | 75/1939 [00:06<03:56,  7.87it/s]
 83%|████████▎ | 249/300 [09:34<00:05, 10.00it/s]
  4%|▍         | 80/1939 [00:08<06:33,  4.73it/s]
  4%|▍         | 82/1939 [00:09<07:42,  4.02it/s]
  4%|▍         | 84/1939 [00:09<08:30,  3.63it/s]
  4%|▍         | 85/1939 [00:09<07:45,  3.98it/s]
  4%|▍         | 86/1939 [00:10<09:06,  3.39it/s]
  5%|▍         | 89/1939 [00:10<05:49,  5.30it/s]
  5%|▍         | 92/1939 [00:10<04:04,  7.56it/s]
  5%|▍         | 94/1939 [00:11<05:47,  5.31it/s]
  5%|▍         | 96/1939 [00:11<04:38,  6.62it/s]
  5%|▌         | 100/1939 [00:12<04:31,  6.77it/s]
  5%|▌         | 102/1939 [00:12<03:53,  7.87it/s]
  6%|▌         | 107/1939 [00:12<02:27, 12.39it/s]
  6%|▌         | 111/1939 [00:12<01:53, 16.06it/s]
  6%|▌         | 118/1939 [00:13<02:12, 13.71it/s]
  6%|▌         | 121/1939 [00:13<02:39, 11.39it/s]
  6%|▋         | 123/1939 [00:13<02:32, 11.92it/s]
  7%|▋         | 128/1939 [00:14<03:16,  9.20it/s]
  7%|▋         | 130/1939 [00:14<03:05,  9.74it/s]
  7%|▋         | 132/1939 [00:15<04:44,  6.36it/s]
  7%|▋         | 134/1939 [00:15<04:04,  7.38it/s]
  7%|▋         | 136/1939 [00:15<03:32,  8.48it/s]
  7%|▋         | 138/1939 [00:15<04:07,  7.27it/s]
  7%|▋         | 140/1939 [00:16<03:26,  8.70it/s]
  7%|▋         | 142/1939 [00:16<02:54, 10.30it/s]
  7%|▋         | 145/1939 [00:16<04:26,  6.73it/s]
  8%|▊         | 148/1939 [00:16<03:21,  8.88it/s]
  8%|▊         | 153/1939 [00:17<04:05,  7.28it/s]
  8%|▊         | 155/1939 [00:17<03:34,  8.33it/s]
  8%|▊         | 157/1939 [00:18<03:11,  9.31it/s]
  8%|▊         | 159/1939 [00:18<05:09,  5.76it/s]
  8%|▊         | 161/1939 [00:19<06:50,  4.33it/s]
  8%|▊         | 162/1939 [00:20<09:09,  3.23it/s]
  8%|▊         | 164/1939 [00:21<10:04,  2.94it/s]
  9%|▊         | 166/1939 [00:21<07:35,  3.89it/s]
  9%|▉         | 172/1939 [00:21<03:33,  8.28it/s]
  9%|▉         | 176/1939 [00:21<02:36, 11.29it/s]
  9%|▉         | 180/1939 [00:21<02:00, 14.61it/s]
 10%|▉         | 186/1939 [00:21<01:23, 20.92it/s]
 10%|▉         | 192/1939 [00:21<01:03, 27.54it/s]
 10%|█         | 197/1939 [00:21<00:54, 31.87it/s]
 10%|█         | 202/1939 [00:22<01:54, 15.21it/s]
 11%|█         | 206/1939 [00:24<05:19,  5.42it/s]
 11%|█         | 209/1939 [00:24<04:26,  6.49it/s]
 11%|█         | 215/1939 [00:25<04:13,  6.79it/s]
 11%|█         | 217/1939 [00:25<03:48,  7.54it/s]
 11%|█▏        | 222/1939 [00:25<02:39, 10.78it/s]
 12%|█▏        | 228/1939 [00:26<03:01,  9.40it/s]
 12%|█▏        | 231/1939 [00:26<02:41, 10.56it/s]
 12%|█▏        | 234/1939 [00:27<03:15,  8.71it/s]
 12%|█▏        | 236/1939 [00:27<03:33,  7.96it/s]
 12%|█▏        | 238/1939 [00:27<03:11,  8.87it/s]
 12%|█▏        | 240/1939 [00:29<06:48,  4.16it/s]
 12%|█▏        | 242/1939 [00:29<06:22,  4.43it/s]
 13%|█▎        | 243/1939 [00:29<06:21,  4.45it/s]
 13%|█▎        | 245/1939 [00:30<07:52,  3.58it/s]
 13%|█▎        | 246/1939 [00:31<10:17,  2.74it/s]
 13%|█▎        | 248/1939 [00:31<07:20,  3.84it/s]
 13%|█▎        | 252/1939 [00:31<04:06,  6.85it/s]
 13%|█▎        | 257/1939 [00:32<04:14,  6.60it/s]
 13%|█▎        | 259/1939 [00:32<03:39,  7.65it/s]
 13%|█▎        | 261/1939 [00:33<05:21,  5.22it/s]
 14%|█▎        | 264/1939 [00:33<03:53,  7.18it/s]
 14%|█▍        | 270/1939 [00:33<02:14, 12.45it/s]
 14%|█▍        | 276/1939 [00:33<01:31, 18.14it/s]
 14%|█▍        | 281/1939 [00:33<01:31, 18.05it/s]
 15%|█▍        | 285/1939 [00:34<01:27, 18.82it/s]
 15%|█▌        | 291/1939 [00:34<01:05, 24.99it/s]
 15%|█▌        | 297/1939 [00:34<00:53, 30.88it/s]
 16%|█▌        | 304/1939 [00:34<00:42, 38.60it/s]
 16%|█▌        | 310/1939 [00:35<01:46, 15.30it/s]
 16%|█▌        | 315/1939 [00:35<01:27, 18.64it/s]
 16%|█▋        | 319/1939 [00:36<02:27, 11.00it/s]
 17%|█▋        | 322/1939 [00:37<03:26,  7.85it/s]
 17%|█▋        | 325/1939 [00:37<02:58,  9.02it/s]
 17%|█▋        | 328/1939 [00:37<02:31, 10.63it/s]
 17%|█▋        | 335/1939 [00:37<01:38, 16.24it/s]
 18%|█▊        | 340/1939 [00:37<01:17, 20.56it/s]
 18%|█▊        | 344/1939 [00:37<01:08, 23.14it/s]
 18%|█▊        | 349/1939 [00:37<01:00, 26.13it/s]
 18%|█▊        | 353/1939 [00:39<02:51,  9.26it/s]
 18%|█▊        | 356/1939 [00:39<03:47,  6.96it/s]
 19%|█▊        | 363/1939 [00:39<02:22, 11.09it/s]
 19%|█▉        | 367/1939 [00:40<01:57, 13.41it/s]
 19%|█▉        | 372/1939 [00:40<01:31, 17.12it/s]
 19%|█▉        | 376/1939 [00:40<01:52, 13.92it/s]
 20%|█▉        | 379/1939 [00:40<01:43, 15.03it/s]
 20%|█▉        | 382/1939 [00:41<03:00,  8.63it/s]
 20%|█▉        | 384/1939 [00:42<04:17,  6.04it/s]
 20%|█▉        | 386/1939 [00:42<03:43,  6.96it/s]
 20%|██        | 388/1939 [00:43<06:36,  3.92it/s]
 20%|██        | 390/1939 [00:44<06:07,  4.21it/s]
 20%|██        | 392/1939 [00:44<04:54,  5.25it/s]
 20%|██        | 394/1939 [00:44<06:04,  4.24it/s]
 20%|██        | 396/1939 [00:45<06:18,  4.07it/s]
 21%|██        | 398/1939 [00:45<05:53,  4.36it/s]
 21%|██        | 400/1939 [00:45<04:37,  5.55it/s]
 21%|██        | 402/1939 [00:46<03:41,  6.93it/s]
 21%|██        | 404/1939 [00:46<05:04,  5.04it/s]
 21%|██        | 405/1939 [00:47<06:45,  3.78it/s]
 21%|██        | 407/1939 [00:48<07:43,  3.31it/s]
 21%|██        | 409/1939 [00:48<05:38,  4.51it/s]
 21%|██        | 411/1939 [00:48<07:09,  3.56it/s]
 21%|██▏       | 413/1939 [00:49<05:24,  4.70it/s]
 21%|██▏       | 415/1939 [00:49<06:44,  3.77it/s]
 21%|██▏       | 416/1939 [00:49<06:01,  4.22it/s]
 22%|██▏       | 419/1939 [00:50<06:34,  3.85it/s]
 22%|██▏       | 421/1939 [00:50<05:03,  5.01it/s]
 22%|██▏       | 423/1939 [00:51<06:37,  3.81it/s]
 22%|██▏       | 426/1939 [00:52<06:34,  3.84it/s]
 22%|██▏       | 428/1939 [00:53<07:30,  3.36it/s]
 22%|██▏       | 430/1939 [00:53<05:49,  4.31it/s]
 22%|██▏       | 436/1939 [00:53<02:52,  8.70it/s]
 23%|██▎       | 442/1939 [00:53<01:48, 13.80it/s]
 23%|██▎       | 448/1939 [00:53<01:16, 19.38it/s]
 23%|██▎       | 454/1939 [00:53<00:58, 25.50it/s]
 24%|██▍       | 461/1939 [00:53<00:44, 33.27it/s]
 24%|██▍       | 467/1939 [00:54<00:38, 38.62it/s]
 24%|██▍       | 473/1939 [00:54<00:35, 41.07it/s]
 25%|██▍       | 479/1939 [00:54<00:36, 39.97it/s]
 25%|██▍       | 484/1939 [00:54<00:35, 41.52it/s]
 25%|██▌       | 489/1939 [00:55<01:28, 16.34it/s]
 25%|██▌       | 493/1939 [00:55<01:19, 18.20it/s]
 26%|██▌       | 500/1939 [00:55<00:59, 24.37it/s]
 26%|██▌       | 506/1939 [00:55<00:49, 28.83it/s]
 27%|██▋       | 514/1939 [00:55<00:38, 37.44it/s]
 27%|██▋       | 520/1939 [00:55<00:37, 37.59it/s]
 27%|██▋       | 526/1939 [00:56<00:33, 41.96it/s]
 27%|██▋       | 533/1939 [00:56<00:29, 48.04it/s]
 28%|██▊       | 539/1939 [00:56<01:16, 18.23it/s]
 28%|██▊       | 544/1939 [00:57<01:05, 21.21it/s]
 28%|██▊       | 549/1939 [00:57<01:54, 12.10it/s]
 29%|██▊       | 553/1939 [00:58<02:34,  8.98it/s]
 29%|██▉       | 559/1939 [00:58<01:51, 12.42it/s]
 29%|██▉       | 565/1939 [00:59<01:22, 16.60it/s]
 29%|██▉       | 569/1939 [00:59<01:11, 19.12it/s]
 30%|██▉       | 573/1939 [01:00<02:50,  8.00it/s]
 30%|██▉       | 576/1939 [01:01<04:12,  5.40it/s]
 30%|██▉       | 579/1939 [01:02<04:32,  5.00it/s]
 30%|██▉       | 581/1939 [01:02<03:55,  5.77it/s]
 30%|███       | 583/1939 [01:03<05:00,  4.52it/s]
 30%|███       | 585/1939 [01:04<05:51,  3.85it/s]
 30%|███       | 586/1939 [01:04<07:24,  3.04it/s]
 30%|███       | 588/1939 [01:05<05:42,  3.95it/s]
 31%|███       | 594/1939 [01:05<02:47,  8.01it/s]
 31%|███       | 599/1939 [01:06<03:12,  6.97it/s]
 31%|███       | 601/1939 [01:06<04:10,  5.34it/s]
 31%|███       | 604/1939 [01:06<03:15,  6.84it/s]
 31%|███▏      | 607/1939 [01:07<03:56,  5.63it/s]
 31%|███▏      | 609/1939 [01:08<04:59,  4.44it/s]
 32%|███▏      | 611/1939 [01:09<05:54,  3.74it/s]
 32%|███▏      | 612/1939 [01:10<07:29,  2.95it/s]
 32%|███▏      | 614/1939 [01:10<08:01,  2.75it/s]
 32%|███▏      | 615/1939 [01:11<09:40,  2.28it/s]
 32%|███▏      | 616/1939 [01:12<11:03,  1.99it/s]
 32%|███▏      | 617/1939 [01:13<12:16,  1.80it/s]
 32%|███▏      | 618/1939 [01:13<13:15,  1.66it/s]
 32%|███▏      | 620/1939 [01:14<11:43,  1.88it/s]
 32%|███▏      | 623/1939 [01:14<06:40,  3.29it/s]
 32%|███▏      | 628/1939 [01:15<03:23,  6.45it/s]
 33%|███▎      | 631/1939 [01:16<05:44,  3.80it/s]
 33%|███▎      | 633/1939 [01:16<04:41,  4.64it/s]
 33%|███▎      | 636/1939 [01:17<04:11,  5.19it/s]
 33%|███▎      | 638/1939 [01:17<03:36,  6.00it/s]
 33%|███▎      | 640/1939 [01:18<04:55,  4.40it/s]
 33%|███▎      | 642/1939 [01:18<03:56,  5.49it/s]
 33%|███▎      | 647/1939 [01:18<02:14,  9.62it/s]
 34%|███▎      | 650/1939 [01:19<03:06,  6.92it/s]
 34%|███▎      | 652/1939 [01:19<04:16,  5.02it/s]
 34%|███▎      | 654/1939 [01:20<05:15,  4.08it/s]
 34%|███▍      | 656/1939 [01:21<05:40,  3.77it/s]
 34%|███▍      | 658/1939 [01:21<06:10,  3.46it/s]
 34%|███▍      | 660/1939 [01:22<04:46,  4.47it/s]
 34%|███▍      | 665/1939 [01:22<04:08,  5.13it/s]
 34%|███▍      | 666/1939 [01:23<05:21,  3.96it/s]
 34%|███▍      | 668/1939 [01:23<04:19,  4.90it/s]
 35%|███▍      | 671/1939 [01:23<03:06,  6.79it/s]
 35%|███▍      | 673/1939 [01:24<04:14,  4.97it/s]
 35%|███▍      | 675/1939 [01:24<03:23,  6.21it/s]
 35%|███▍      | 677/1939 [01:25<04:42,  4.47it/s]
 35%|███▌      | 680/1939 [01:26<05:02,  4.17it/s]
 35%|███▌      | 682/1939 [01:26<04:01,  5.20it/s]
 35%|███▌      | 684/1939 [01:27<05:16,  3.96it/s]
 35%|███▌      | 687/1939 [01:27<05:23,  3.87it/s]
 36%|███▌      | 689/1939 [01:28<05:15,  3.96it/s]
 36%|███▌      | 691/1939 [01:28<04:10,  4.99it/s]
 36%|███▌      | 692/1939 [01:29<05:02,  4.12it/s]
 36%|███▌      | 694/1939 [01:29<03:47,  5.48it/s]
 36%|███▌      | 700/1939 [01:29<01:48, 11.46it/s]
 36%|███▋      | 706/1939 [01:29<01:08, 17.91it/s]
 37%|███▋      | 713/1939 [01:29<00:47, 25.79it/s]
 37%|███▋      | 719/1939 [01:29<00:40, 30.16it/s]
 37%|███▋      | 724/1939 [01:29<00:40, 30.18it/s]
 38%|███▊      | 730/1939 [01:30<00:52, 22.87it/s]
 38%|███▊      | 734/1939 [01:31<01:43, 11.62it/s]
 38%|███▊      | 737/1939 [01:31<01:33, 12.86it/s]
 38%|███▊      | 740/1939 [01:31<01:43, 11.63it/s]
 38%|███▊      | 742/1939 [01:32<02:21,  8.48it/s]
 38%|███▊      | 744/1939 [01:32<02:05,  9.53it/s]
 39%|███▊      | 748/1939 [01:32<01:30, 13.19it/s]
 39%|███▉      | 754/1939 [01:32<01:00, 19.67it/s]
 39%|███▉      | 758/1939 [01:33<01:57, 10.06it/s]
 39%|███▉      | 761/1939 [01:34<02:44,  7.14it/s]
 39%|███▉      | 763/1939 [01:34<03:49,  5.12it/s]
 40%|███▉      | 766/1939 [01:35<04:18,  4.53it/s]
 40%|███▉      | 768/1939 [01:36<05:05,  3.84it/s]
 40%|███▉      | 769/1939 [01:37<06:22,  3.06it/s]
 40%|███▉      | 770/1939 [01:38<07:29,  2.60it/s]
 40%|███▉      | 772/1939 [01:38<06:42,  2.90it/s]
 40%|███▉      | 773/1939 [01:39<07:23,  2.63it/s]
 40%|████      | 776/1939 [01:39<06:21,  3.05it/s]
 40%|████      | 777/1939 [01:40<07:40,  2.52it/s]
 40%|████      | 779/1939 [01:41<07:53,  2.45it/s]
 40%|████      | 780/1939 [01:41<07:56,  2.43it/s]
 40%|████      | 782/1939 [01:42<05:39,  3.41it/s]
 40%|████      | 784/1939 [01:42<05:31,  3.49it/s]
 41%|████      | 786/1939 [01:42<04:11,  4.58it/s]
 41%|████      | 787/1939 [01:43<04:51,  3.95it/s]
 41%|████      | 789/1939 [01:43<05:56,  3.22it/s]
 41%|████      | 791/1939 [01:44<06:08,  3.12it/s]
 41%|████      | 793/1939 [01:44<04:33,  4.20it/s]
 41%|████      | 798/1939 [01:45<03:47,  5.01it/s]
 41%|████▏     | 801/1939 [01:45<02:51,  6.63it/s]
 41%|████▏     | 804/1939 [01:46<03:23,  5.56it/s]
 42%|████▏     | 806/1939 [01:47<04:09,  4.54it/s]
 42%|████▏     | 808/1939 [01:47<03:26,  5.48it/s]
 42%|████▏     | 809/1939 [01:48<04:53,  3.85it/s]
 42%|████▏     | 811/1939 [01:48<03:47,  4.96it/s]
 42%|████▏     | 812/1939 [01:48<05:33,  3.38it/s]
 42%|████▏     | 813/1939 [01:49<07:04,  2.65it/s]
 42%|████▏     | 816/1939 [01:50<06:08,  3.05it/s]
 42%|████▏     | 817/1939 [01:51<07:32,  2.48it/s]
 42%|████▏     | 818/1939 [01:51<07:39,  2.44it/s]
 42%|████▏     | 819/1939 [01:52<07:41,  2.43it/s]
 42%|████▏     | 820/1939 [01:52<07:54,  2.36it/s]
 42%|████▏     | 821/1939 [01:52<07:14,  2.57it/s]
 42%|████▏     | 822/1939 [01:53<07:20,  2.54it/s]
 42%|████▏     | 823/1939 [01:53<07:54,  2.35it/s]
 43%|████▎     | 825/1939 [01:53<04:52,  3.81it/s]
 43%|████▎     | 827/1939 [01:53<03:20,  5.54it/s]
 43%|████▎     | 830/1939 [01:54<02:10,  8.50it/s]
 43%|████▎     | 834/1939 [01:54<01:28, 12.50it/s]
 43%|████▎     | 838/1939 [01:54<01:06, 16.62it/s]
 43%|████▎     | 842/1939 [01:54<00:54, 20.23it/s]
 44%|████▎     | 845/1939 [01:54<00:49, 22.16it/s]
 44%|████▎     | 848/1939 [01:54<00:46, 23.53it/s]
 44%|████▍     | 854/1939 [01:54<00:33, 32.13it/s]
 44%|████▍     | 858/1939 [01:55<01:26, 12.47it/s]
 44%|████▍     | 861/1939 [01:55<01:14, 14.48it/s]
 45%|████▍     | 867/1939 [01:55<00:51, 20.76it/s]
 45%|████▌     | 874/1939 [01:55<00:37, 28.54it/s]
 45%|████▌     | 879/1939 [01:55<00:34, 30.96it/s]
 46%|████▌     | 884/1939 [01:56<00:38, 27.41it/s]
 46%|████▌     | 890/1939 [01:56<00:31, 32.90it/s]
 46%|████▌     | 895/1939 [01:56<00:29, 35.53it/s]
 46%|████▋     | 900/1939 [01:56<00:47, 21.87it/s]
 47%|████▋     | 904/1939 [01:57<01:06, 15.66it/s]
 47%|████▋     | 907/1939 [01:57<01:01, 16.87it/s]
 47%|████▋     | 910/1939 [01:57<01:29, 11.51it/s]
 47%|████▋     | 912/1939 [01:58<01:24, 12.17it/s]
 47%|████▋     | 916/1939 [01:58<01:05, 15.71it/s]
 47%|████▋     | 919/1939 [01:58<01:19, 12.79it/s]
 48%|████▊     | 922/1939 [01:58<01:07, 15.11it/s]
 48%|████▊     | 927/1939 [01:59<01:45,  9.56it/s]
 48%|████▊     | 930/1939 [02:00<02:28,  6.81it/s]
 48%|████▊     | 932/1939 [02:01<03:13,  5.21it/s]
 48%|████▊     | 936/1939 [02:01<02:13,  7.49it/s]
 49%|████▊     | 943/1939 [02:01<01:17, 12.89it/s]
 49%|████▉     | 948/1939 [02:01<01:02, 15.98it/s]
 49%|████▉     | 953/1939 [02:01<00:50, 19.69it/s]
 49%|████▉     | 958/1939 [02:01<00:40, 23.93it/s]
 50%|████▉     | 964/1939 [02:01<00:32, 29.71it/s]
 50%|████▉     | 969/1939 [02:02<00:47, 20.54it/s]
 50%|█████     | 973/1939 [02:03<01:23, 11.54it/s]
 50%|█████     | 977/1939 [02:03<01:51,  8.59it/s]
 50%|█████     | 979/1939 [02:03<01:43,  9.25it/s]
 51%|█████     | 982/1939 [02:04<02:17,  6.95it/s]
 51%|█████     | 984/1939 [02:04<02:03,  7.71it/s]
 51%|█████     | 990/1939 [02:04<01:15, 12.60it/s]
 51%|█████▏    | 996/1939 [02:05<00:51, 18.22it/s]
 52%|█████▏    | 1000/1939 [02:06<02:18,  6.77it/s]
 52%|█████▏    | 1003/1939 [02:07<02:44,  5.70it/s]
 52%|█████▏    | 1005/1939 [02:08<03:19,  4.67it/s]
 52%|█████▏    | 1008/1939 [02:08<02:35,  6.00it/s]
 52%|█████▏    | 1010/1939 [02:09<04:19,  3.58it/s]
 52%|█████▏    | 1012/1939 [02:11<05:57,  2.59it/s]
 52%|█████▏    | 1014/1939 [02:12<05:59,  2.58it/s]
 52%|█████▏    | 1015/1939 [02:12<06:49,  2.26it/s]
 52%|█████▏    | 1016/1939 [02:13<07:43,  1.99it/s]
 53%|█████▎    | 1018/1939 [02:13<05:25,  2.83it/s]
 53%|█████▎    | 1019/1939 [02:14<06:33,  2.34it/s]
 53%|█████▎    | 1021/1939 [02:14<04:32,  3.36it/s]
 53%|█████▎    | 1022/1939 [02:15<05:51,  2.61it/s]
 53%|█████▎    | 1025/1939 [02:15<03:25,  4.45it/s]
 53%|█████▎    | 1027/1939 [02:16<04:04,  3.73it/s]
 53%|█████▎    | 1030/1939 [02:16<02:42,  5.58it/s]
 53%|█████▎    | 1037/1939 [02:16<01:17, 11.57it/s]
 54%|█████▍    | 1044/1939 [02:16<00:48, 18.46it/s]
 54%|█████▍    | 1049/1939 [02:17<01:49,  8.12it/s]
 54%|█████▍    | 1052/1939 [02:18<02:18,  6.39it/s]
 54%|█████▍    | 1055/1939 [02:20<03:24,  4.32it/s]
 55%|█████▍    | 1057/1939 [02:20<03:46,  3.90it/s]
 55%|█████▍    | 1059/1939 [02:21<04:09,  3.52it/s]
 55%|█████▍    | 1060/1939 [02:22<04:59,  2.93it/s]
 55%|█████▍    | 1061/1939 [02:22<04:27,  3.28it/s]
 55%|█████▍    | 1063/1939 [02:22<03:20,  4.37it/s]
 55%|█████▍    | 1065/1939 [02:22<02:35,  5.60it/s]
 55%|█████▌    | 1068/1939 [02:23<02:08,  6.80it/s]
 55%|█████▌    | 1070/1939 [02:23<01:45,  8.27it/s]
 55%|█████▌    | 1073/1939 [02:23<01:16, 11.29it/s]
 56%|█████▌    | 1078/1939 [02:23<00:48, 17.58it/s]
 56%|█████▌    | 1081/1939 [02:23<01:29,  9.59it/s]
 56%|█████▌    | 1084/1939 [02:24<01:11, 11.88it/s]
 56%|█████▌    | 1088/1939 [02:24<01:47,  7.95it/s]
 56%|█████▌    | 1090/1939 [02:25<01:37,  8.72it/s]
 56%|█████▋    | 1092/1939 [02:25<02:27,  5.72it/s]
 56%|█████▋    | 1094/1939 [02:26<02:54,  4.86it/s]
 56%|█████▋    | 1095/1939 [02:26<03:22,  4.17it/s]
 57%|█████▋    | 1097/1939 [02:27<03:29,  4.02it/s]
 57%|█████▋    | 1099/1939 [02:27<02:40,  5.22it/s]
 57%|█████▋    | 1101/1939 [02:27<02:08,  6.54it/s]
 57%|█████▋    | 1103/1939 [02:28<02:22,  5.88it/s]
 57%|█████▋    | 1104/1939 [02:28<03:37,  3.85it/s]
 57%|█████▋    | 1105/1939 [02:29<05:12,  2.67it/s]
 57%|█████▋    | 1108/1939 [02:29<03:01,  4.58it/s]
 57%|█████▋    | 1113/1939 [02:29<01:38,  8.37it/s]
 58%|█████▊    | 1115/1939 [02:29<01:26,  9.52it/s]
 58%|█████▊    | 1117/1939 [02:30<02:24,  5.70it/s]
 58%|█████▊    | 1121/1939 [02:31<02:38,  5.16it/s]
 58%|█████▊    | 1123/1939 [02:31<02:12,  6.14it/s]
 58%|█████▊    | 1128/1939 [02:31<01:20, 10.06it/s]
 58%|█████▊    | 1131/1939 [02:32<02:01,  6.63it/s]
 59%|█████▊    | 1136/1939 [02:32<01:19, 10.08it/s]
 59%|█████▊    | 1139/1939 [02:33<01:54,  6.98it/s]
 59%|█████▉    | 1142/1939 [02:34<02:02,  6.48it/s]
 59%|█████▉    | 1144/1939 [02:34<02:36,  5.07it/s]
 59%|█████▉    | 1146/1939 [02:35<02:12,  5.98it/s]
 59%|█████▉    | 1148/1939 [02:36<04:00,  3.29it/s]
 59%|█████▉    | 1150/1939 [02:37<04:21,  3.01it/s]
 59%|█████▉    | 1151/1939 [02:38<05:15,  2.50it/s]
 59%|█████▉    | 1153/1939 [02:38<05:11,  2.53it/s]
 60%|█████▉    | 1155/1939 [02:38<03:51,  3.39it/s]
 60%|█████▉    | 1161/1939 [02:39<02:43,  4.75it/s]
 60%|█████▉    | 1163/1939 [02:40<03:15,  3.97it/s]
 60%|██████    | 1165/1939 [02:41<03:41,  3.49it/s]
 60%|██████    | 1167/1939 [02:41<02:57,  4.34it/s]
 60%|██████    | 1172/1939 [02:41<01:40,  7.61it/s]
 61%|██████    | 1178/1939 [02:42<01:44,  7.29it/s]
 61%|██████    | 1180/1939 [02:43<02:16,  5.58it/s]
 61%|██████    | 1183/1939 [02:44<02:33,  4.92it/s]
 61%|██████    | 1185/1939 [02:44<02:10,  5.79it/s]
 61%|██████    | 1187/1939 [02:44<02:46,  4.51it/s]
 61%|██████▏   | 1190/1939 [02:45<03:01,  4.13it/s]
 61%|██████▏   | 1191/1939 [02:46<04:00,  3.11it/s]
 61%|██████▏   | 1192/1939 [02:47<04:55,  2.53it/s]
 62%|██████▏   | 1193/1939 [02:48<05:47,  2.15it/s]
 62%|██████▏   | 1196/1939 [02:49<04:44,  2.61it/s]
 62%|██████▏   | 1197/1939 [02:49<05:32,  2.23it/s]
 62%|██████▏   | 1199/1939 [02:49<03:53,  3.16it/s]
 62%|██████▏   | 1206/1939 [02:50<01:34,  7.79it/s]
 62%|██████▏   | 1211/1939 [02:50<01:05, 11.04it/s]
 63%|██████▎   | 1216/1939 [02:50<00:47, 15.24it/s]
 63%|██████▎   | 1220/1939 [02:51<01:17,  9.27it/s]
 63%|██████▎   | 1223/1939 [02:51<01:04, 11.07it/s]
 63%|██████▎   | 1226/1939 [02:51<01:21,  8.78it/s]
 63%|██████▎   | 1228/1939 [02:51<01:13,  9.73it/s]
 63%|██████▎   | 1231/1939 [02:52<01:00, 11.73it/s]
 64%|██████▎   | 1234/1939 [02:52<01:40,  7.01it/s]
 64%|██████▍   | 1239/1939 [02:53<01:45,  6.64it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 309.09it/s]
 84%|████████▎ | 251/300 [13:42<31:48, 38.96s/it]

[[np.int64(0), False, 9], [np.int64(1), False, 2], [np.int64(2), False, 4], [np.int64(3), False, 9], [np.int64(5), False, 8], [np.int64(6), False, 8], [np.int64(7), False, 4], [np.int64(10), False, 7], [np.int64(11), False, 3], [np.int64(12), False, 10], [np.int64(13), False, 7]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1414, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.5084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2048, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [13:42<25:41, 32.11s/it]

tensor(12.5102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4288, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [13:43<15:17, 19.95s/it]

tensor(12.5149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4337, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [13:43<11:21, 15.15s/it]

tensor(12.5189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4391, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3821, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4319, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [13:43<06:26,  9.00s/it]

tensor(12.5132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4618, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [13:43<03:54,  5.72s/it]

tensor(12.5083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4778, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4797, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4804, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [13:43<02:27,  3.78s/it]

tensor(12.5093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4832, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4886, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [13:43<01:34,  2.56s/it]

tensor(12.5044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4902, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [13:44<01:02,  1.77s/it]

tensor(12.5002, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4920, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4922, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4917, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4907, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [13:44<00:41,  1.25s/it]

tensor(12.4901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4920, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4913, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [13:44<00:27,  1.12it/s]

tensor(12.4834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4923, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [13:44<00:18,  1.55it/s]

tensor(12.4808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4921, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4935, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [13:44<00:12,  2.08it/s]

tensor(12.4726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4952, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4956, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [13:45<00:09,  2.75it/s]

tensor(12.4685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4924, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [13:45<00:06,  3.54it/s]

tensor(12.4665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4963, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4971, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [13:45<00:04,  4.40it/s]

tensor(12.4600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4583, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4953, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [13:45<00:03,  5.33it/s]

tensor(12.4568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4957, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [13:45<00:02,  6.23it/s]

tensor(12.4553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4968, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4970, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [13:46<00:02,  7.12it/s]

tensor(12.4503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4967, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4964, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [13:46<00:01,  7.85it/s]

tensor(12.4466, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4963, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [13:46<00:01,  8.47it/s]

tensor(12.4448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4952, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [13:46<00:01,  8.95it/s]

tensor(12.4401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4932, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4938, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [13:46<00:00,  9.34it/s]

tensor(12.4374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4940, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [13:47<00:00,  9.60it/s]

tensor(12.4360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4907, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4347, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4912, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4917, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [13:47<00:00,  9.83it/s]

tensor(12.4323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4918, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4312, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4918, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [13:47<00:00,  9.95it/s]

tensor(12.4301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4920, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [13:47<00:00,  2.76s/it]

Model training finished!

Infer time:  0.0025069713592529297
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 6
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.475248151047
NMI         : 0.597647734030
Runtime     : 847.47 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed6

==============================================================================================================
PRAGA RUN | S2-E15 | seed=7
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 1.161e-16
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29, 10.14it/s]

tensor(17.8075, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3748, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.8105, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2329, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:26, 11.22it/s]

tensor(17.7506, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3006, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6885, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5588, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6337, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9877, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:24, 12.00it/s]

tensor(17.5943, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5705, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5665, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2926, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5465, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1402, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.65it/s]

tensor(17.5273, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1010, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5026, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1641, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4688, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3203, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:00<00:22, 12.78it/s]

tensor(17.4240, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5586, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3684, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8718, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3067, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2532, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:22, 12.85it/s]

tensor(17.2446, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6962, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1937, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1377, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7417, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:21, 12.87it/s]

tensor(17.0879, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3342, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0288, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9668, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9554, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6364, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:21, 12.98it/s]

tensor(16.8702, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3389, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.7819, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0714, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6960, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8309, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:01<00:21, 13.04it/s]

tensor(16.6130, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6144, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5282, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4195, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4367, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2449, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.02it/s]

tensor(16.3355, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0882, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9476, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8213, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:20, 13.04it/s]

tensor(15.9797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7088, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6083, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7415, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5185, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:20, 13.05it/s]

tensor(15.6330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4384, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3668, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3045, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:02<00:20, 12.98it/s]

tensor(15.3439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2491, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2661, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2005, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1590, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.03it/s]

tensor(15.1249, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0950, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0729, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.02it/s]

tensor(14.9068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0561, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:19, 12.94it/s]

tensor(14.7350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6561, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:19, 12.99it/s]

tensor(14.6187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:04<00:19, 12.95it/s]

tensor(14.4971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:04<00:19, 12.94it/s]

tensor(14.3812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:18, 12.92it/s]

tensor(14.2827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:04<00:18, 12.96it/s]

tensor(14.1962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0185, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:18, 13.02it/s]

tensor(14.1116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:05<00:18, 12.95it/s]

tensor(14.0381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 12.98it/s]

tensor(13.9729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9317, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:17, 13.03it/s]

tensor(13.9116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:17, 12.97it/s]

tensor(13.8543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:06<00:17, 13.03it/s]

tensor(13.8019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7853, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.01it/s]

tensor(13.7524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7364, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:16, 12.99it/s]

tensor(13.7049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6744, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:16, 13.05it/s]

tensor(13.6595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6446, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:06<00:16, 12.99it/s]

tensor(13.6156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6014, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.03it/s]

tensor(13.5734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5464, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:15, 13.05it/s]

tensor(13.5332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:15, 12.96it/s]

tensor(13.4956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([187, 176, 120, 175,  30,  67, 492,  34,  20, 114, 282,  68, 106,  68])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<02:18, 13.94it/s]
  0%|          | 6/1939 [00:00<01:12, 26.59it/s]
  1%|          | 10/1939 [00:00<01:11, 26.91it/s]
  1%|          | 17/1939 [00:00<00:47, 40.86it/s]
  1%|          | 22/1939 [00:00<00:44, 43.08it/s]
  1%|▏         | 27/1939 [00:00<01:04, 29.86it/s]
  2%|▏         | 33/1939 [00:00<00:53, 35.52it/s]
  2%|▏         | 38/1939 [00:01<00:57, 33.29it/s]
  2%|▏         | 42/1939 [00:02<03:37,  8.71it/s]
  2%|▏         | 45/1939 [00:02<03:18,  9.55it/s]
  2%|▏         | 48/1939 [00:02<02:46, 11.34it/s]
  3%|▎         | 51/1939 [00:03<03:48,  8.27it/s]
  3%|▎         | 53/1939 [00:03<04:09,  7.54it/s]
  3%|▎         | 55/1939 [00:04<03:49,  8.20it/s]
  3%|▎         | 57/1939 [00:04<03:53,  8.05it/s]
  3%|▎         | 59/1939 [00:05<07:57,  3.94it/s]
  3%|▎         | 61/1939 [00:05<06:21,  4.92it/s]
  3%|▎         | 63/1939 [00:06<06:22,  4.90it/s]
  3%|▎         | 66/1939 [00:07<07:48,  4.00it/s]
  4%|▎         | 68/1939 [00:07<06:21,  4.90it/s]
  4%|▎         | 70/1939 [00:07<05:57,  5.23it/s]
  4%|▍         | 73/1939 [00:08<07:01,  4.43it/s]
  4%|▍         | 75/1939 [00:08<05:38,  5.50it/s]
  4%|▍         | 78/1939 [00:09<05:33,  5.58it/s]
  4%|▍         | 79/1939 [00:09<08:38,  3.59it/s]
  4%|▍         | 80/1939 [00:10<12:19,  2.51it/s]
  4%|▍         | 81/1939 [00:11<12:59,  2.38it/s]
  4%|▍         | 82/1939 [00:11<12:11,  2.54it/s]
  4%|▍         | 84/1939 [00:12<10:15,  3.01it/s]
  4%|▍         | 86/1939 [00:12<08:56,  3.46it/s]
  4%|▍         | 87/1939 [00:12<09:01,  3.42it/s]
  5%|▍         | 89/1939 [00:13<06:27,  4.78it/s]
 33%|███▎      | 100/300 [00:24<00:15, 12.96it/s]
  5%|▍         | 95/1939 [00:13<05:18,  5.78it/s]
  5%|▌         | 97/1939 [00:14<04:52,  6.29it/s]
  5%|▌         | 99/1939 [00:14<04:00,  7.64it/s]
  5%|▌         | 101/1939 [00:14<05:30,  5.55it/s]
  5%|▌         | 103/1939 [00:14<04:22,  7.00it/s]
  5%|▌         | 105/1939 [00:15<05:23,  5.66it/s]
  6%|▌         | 107/1939 [00:15<05:55,  5.15it/s]
  6%|▌         | 109/1939 [00:15<04:38,  6.57it/s]
  6%|▌         | 111/1939 [00:16<07:14,  4.21it/s]
  6%|▌         | 114/1939 [00:17<06:37,  4.59it/s]
  6%|▌         | 115/1939 [00:17<08:01,  3.79it/s]
  6%|▌         | 117/1939 [00:18<07:12,  4.21it/s]
  6%|▌         | 118/1939 [00:18<08:54,  3.40it/s]
  6%|▌         | 120/1939 [00:19<11:20,  2.67it/s]
  6%|▌         | 121/1939 [00:20<11:24,  2.66it/s]
  6%|▋         | 123/1939 [00:20<07:57,  3.80it/s]
  6%|▋         | 126/1939 [00:20<06:34,  4.60it/s]
  7%|▋         | 128/1939 [00:21<09:05,  3.32it/s]
  7%|▋         | 130/1939 [00:22<06:58,  4.33it/s]
  7%|▋         | 132/1939 [00:23<09:18,  3.24it/s]
  7%|▋         | 134/1939 [00:23<07:03,  4.26it/s]
  7%|▋         | 135/1939 [00:24<10:55,  2.75it/s]
  7%|▋         | 137/1939 [00:25<12:22,  2.43it/s]
  7%|▋         | 138/1939 [00:25<12:13,  2.45it/s]
  7%|▋         | 139/1939 [00:25<12:23,  2.42it/s]
  7%|▋         | 141/1939 [00:26<10:14,  2.93it/s]
  7%|▋         | 142/1939 [00:26<10:44,  2.79it/s]
  7%|▋         | 144/1939 [00:26<07:15,  4.12it/s]
  7%|▋         | 145/1939 [00:27<11:55,  2.51it/s]
  8%|▊         | 146/1939 [00:28<15:52,  1.88it/s]
  8%|▊         | 148/1939 [00:28<10:17,  2.90it/s]
  8%|▊         | 149/1939 [00:29<10:52,  2.74it/s]
  8%|▊         | 151/1939 [00:29<09:19,  3.20it/s]
  8%|▊         | 153/1939 [00:30<11:35,  2.57it/s]
  8%|▊         | 155/1939 [00:31<08:15,  3.60it/s]
  8%|▊         | 157/1939 [00:31<07:00,  4.23it/s]
  8%|▊         | 158/1939 [00:31<07:41,  3.86it/s]
  8%|▊         | 160/1939 [00:32<07:13,  4.11it/s]
  8%|▊         | 161/1939 [00:32<08:26,  3.51it/s]
  8%|▊         | 162/1939 [00:33<09:44,  3.04it/s]
  8%|▊         | 163/1939 [00:33<10:43,  2.76it/s]
  8%|▊         | 164/1939 [00:34<14:21,  2.06it/s]
  9%|▊         | 165/1939 [00:35<17:50,  1.66it/s]
  9%|▊         | 168/1939 [00:35<08:52,  3.33it/s]
  9%|▉         | 170/1939 [00:35<07:20,  4.01it/s]
  9%|▉         | 172/1939 [00:35<05:26,  5.42it/s]
  9%|▉         | 177/1939 [00:35<02:51, 10.30it/s]
  9%|▉         | 180/1939 [00:36<02:20, 12.55it/s]
 10%|▉         | 185/1939 [00:36<02:28, 11.84it/s]
 10%|▉         | 188/1939 [00:36<02:09, 13.49it/s]
 10%|█         | 194/1939 [00:36<01:27, 20.02it/s]
 10%|█         | 199/1939 [00:37<01:55, 15.07it/s]
 10%|█         | 202/1939 [00:38<03:46,  7.68it/s]
 11%|█         | 204/1939 [00:39<05:40,  5.09it/s]
 11%|█         | 206/1939 [00:40<07:39,  3.77it/s]
 11%|█         | 208/1939 [00:40<06:19,  4.56it/s]
 11%|█         | 211/1939 [00:41<07:16,  3.96it/s]
 11%|█         | 213/1939 [00:41<07:09,  4.02it/s]
 11%|█         | 215/1939 [00:42<08:53,  3.23it/s]
 11%|█         | 218/1939 [00:43<09:07,  3.14it/s]
 11%|█▏        | 219/1939 [00:44<11:42,  2.45it/s]
 11%|█▏        | 220/1939 [00:45<14:25,  1.99it/s]
 11%|█▏        | 221/1939 [00:46<13:53,  2.06it/s]
 11%|█▏        | 222/1939 [00:46<13:59,  2.04it/s]
 12%|█▏        | 224/1939 [00:47<11:06,  2.57it/s]
 12%|█▏        | 225/1939 [00:48<14:50,  1.92it/s]
 12%|█▏        | 228/1939 [00:49<12:11,  2.34it/s]
 12%|█▏        | 229/1939 [00:50<14:59,  1.90it/s]
 12%|█▏        | 230/1939 [00:51<17:45,  1.60it/s]
 12%|█▏        | 232/1939 [00:51<13:59,  2.03it/s]
 12%|█▏        | 233/1939 [00:52<17:02,  1.67it/s]
 12%|█▏        | 236/1939 [00:53<12:51,  2.21it/s]
 12%|█▏        | 237/1939 [00:54<14:44,  1.92it/s]
 12%|█▏        | 239/1939 [00:54<12:07,  2.34it/s]
 12%|█▏        | 240/1939 [00:55<12:49,  2.21it/s]
 12%|█▏        | 241/1939 [00:55<11:54,  2.38it/s]
 12%|█▏        | 242/1939 [00:56<11:24,  2.48it/s]
 13%|█▎        | 243/1939 [00:56<12:04,  2.34it/s]
 13%|█▎        | 244/1939 [00:56<10:50,  2.61it/s]
 13%|█▎        | 245/1939 [00:57<11:20,  2.49it/s]
 13%|█▎        | 246/1939 [00:57<11:51,  2.38it/s]
 13%|█▎        | 248/1939 [00:58<10:11,  2.77it/s]
 13%|█▎        | 250/1939 [00:58<08:24,  3.35it/s]
 13%|█▎        | 251/1939 [00:58<07:26,  3.78it/s]
 13%|█▎        | 252/1939 [00:59<07:27,  3.77it/s]
 13%|█▎        | 254/1939 [00:59<05:07,  5.47it/s]
 13%|█▎        | 256/1939 [00:59<03:46,  7.43it/s]
 13%|█▎        | 258/1939 [01:00<05:47,  4.84it/s]
 13%|█▎        | 260/1939 [01:00<05:34,  5.02it/s]
 14%|█▎        | 262/1939 [01:00<04:15,  6.56it/s]
 14%|█▎        | 264/1939 [01:01<06:04,  4.59it/s]
 14%|█▎        | 266/1939 [01:01<04:44,  5.87it/s]
 14%|█▍        | 268/1939 [01:01<04:38,  6.01it/s]
 14%|█▍        | 270/1939 [01:02<05:03,  5.51it/s]
 14%|█▍        | 271/1939 [01:02<04:41,  5.92it/s]
 14%|█▍        | 273/1939 [01:02<05:42,  4.86it/s]
 14%|█▍        | 274/1939 [01:02<05:36,  4.94it/s]
 14%|█▍        | 276/1939 [01:03<04:08,  6.68it/s]
 14%|█▍        | 279/1939 [01:03<04:30,  6.14it/s]
 14%|█▍        | 281/1939 [01:04<05:09,  5.35it/s]
 15%|█▍        | 284/1939 [01:05<06:45,  4.08it/s]
 15%|█▍        | 285/1939 [01:05<07:04,  3.90it/s]
 15%|█▍        | 287/1939 [01:05<05:56,  4.64it/s]
 15%|█▍        | 288/1939 [01:06<06:58,  3.94it/s]
 15%|█▍        | 290/1939 [01:06<05:12,  5.27it/s]
 15%|█▌        | 293/1939 [01:06<05:05,  5.39it/s]
 15%|█▌        | 295/1939 [01:06<04:01,  6.80it/s]
 15%|█▌        | 297/1939 [01:07<04:30,  6.07it/s]
 15%|█▌        | 298/1939 [01:07<05:40,  4.81it/s]
 15%|█▌        | 300/1939 [01:08<05:10,  5.28it/s]
 16%|█▌        | 303/1939 [01:08<04:55,  5.53it/s]
 16%|█▌        | 304/1939 [01:08<04:46,  5.70it/s]
 16%|█▌        | 307/1939 [01:08<03:45,  7.24it/s]
 16%|█▌        | 308/1939 [01:09<03:51,  7.05it/s]
 16%|█▌        | 310/1939 [01:09<03:20,  8.13it/s]
 16%|█▌        | 312/1939 [01:09<04:07,  6.58it/s]
 16%|█▌        | 313/1939 [01:10<05:05,  5.33it/s]
 16%|█▌        | 315/1939 [01:10<05:45,  4.70it/s]
 16%|█▋        | 316/1939 [01:10<06:11,  4.37it/s]
 16%|█▋        | 317/1939 [01:11<06:38,  4.07it/s]
 16%|█▋        | 318/1939 [01:11<07:14,  3.73it/s]
 16%|█▋        | 319/1939 [01:11<07:00,  3.85it/s]
 17%|█▋        | 320/1939 [01:11<06:33,  4.12it/s]
 17%|█▋        | 321/1939 [01:12<09:19,  2.89it/s]
 17%|█▋        | 322/1939 [01:13<12:46,  2.11it/s]
 17%|█▋        | 324/1939 [01:13<07:54,  3.41it/s]
 17%|█▋        | 327/1939 [01:14<06:21,  4.22it/s]
 17%|█▋        | 331/1939 [01:14<03:37,  7.39it/s]
 17%|█▋        | 333/1939 [01:14<04:18,  6.21it/s]
 17%|█▋        | 335/1939 [01:14<03:34,  7.47it/s]
 17%|█▋        | 339/1939 [01:15<03:26,  7.75it/s]
 18%|█▊        | 343/1939 [01:15<02:25, 10.94it/s]
 18%|█▊        | 349/1939 [01:15<01:34, 16.84it/s]
 18%|█▊        | 352/1939 [01:17<05:17,  4.99it/s]
 18%|█▊        | 354/1939 [01:18<06:53,  3.83it/s]
 18%|█▊        | 356/1939 [01:19<09:28,  2.78it/s]
 18%|█▊        | 358/1939 [01:19<07:35,  3.47it/s]
 19%|█▊        | 360/1939 [01:20<08:56,  2.95it/s]
 19%|█▊        | 362/1939 [01:21<07:03,  3.73it/s]
 19%|█▉        | 364/1939 [01:22<08:47,  2.99it/s]
 19%|█▉        | 366/1939 [01:22<07:52,  3.33it/s]
 19%|█▉        | 367/1939 [01:22<08:19,  3.14it/s]
 19%|█▉        | 368/1939 [01:23<10:15,  2.55it/s]
 19%|█▉        | 370/1939 [01:24<10:18,  2.54it/s]
 19%|█▉        | 372/1939 [01:24<08:44,  2.99it/s]
 19%|█▉        | 373/1939 [01:25<09:33,  2.73it/s]
 19%|█▉        | 375/1939 [01:25<06:41,  3.89it/s]
 19%|█▉        | 376/1939 [01:25<07:39,  3.41it/s]
 19%|█▉        | 377/1939 [01:26<07:41,  3.39it/s]
 19%|█▉        | 378/1939 [01:26<06:37,  3.93it/s]
 20%|█▉        | 380/1939 [01:26<05:59,  4.33it/s]
 20%|█▉        | 381/1939 [01:27<06:48,  3.81it/s]
 20%|█▉        | 382/1939 [01:27<06:22,  4.07it/s]
 20%|█▉        | 384/1939 [01:27<06:46,  3.82it/s]
 20%|█▉        | 385/1939 [01:28<06:41,  3.87it/s]
 20%|█▉        | 387/1939 [01:28<06:57,  3.72it/s]
 20%|██        | 388/1939 [01:29<07:50,  3.29it/s]
 20%|██        | 389/1939 [01:29<07:15,  3.56it/s]
 20%|██        | 390/1939 [01:30<09:47,  2.64it/s]
 20%|██        | 391/1939 [01:30<10:00,  2.58it/s]
 20%|██        | 392/1939 [01:30<09:09,  2.82it/s]
 20%|██        | 393/1939 [01:31<08:43,  2.95it/s]
 20%|██        | 394/1939 [01:31<10:51,  2.37it/s]
 20%|██        | 396/1939 [01:32<09:25,  2.73it/s]
 21%|██        | 398/1939 [01:32<08:25,  3.05it/s]
 21%|██        | 399/1939 [01:32<07:11,  3.56it/s]
 21%|██        | 401/1939 [01:33<05:10,  4.95it/s]
 21%|██        | 404/1939 [01:33<04:58,  5.14it/s]
 21%|██        | 405/1939 [01:34<06:16,  4.07it/s]
 21%|██        | 407/1939 [01:35<08:24,  3.04it/s]
 21%|██        | 408/1939 [01:35<07:16,  3.50it/s]
 21%|██        | 411/1939 [01:36<08:21,  3.05it/s]
 21%|██        | 412/1939 [01:36<08:48,  2.89it/s]
 21%|██▏       | 415/1939 [01:37<09:08,  2.78it/s]
 21%|██▏       | 416/1939 [01:38<08:47,  2.89it/s]
 22%|██▏       | 417/1939 [01:38<10:43,  2.37it/s]
 22%|██▏       | 419/1939 [01:39<11:09,  2.27it/s]
 22%|██▏       | 421/1939 [01:39<08:01,  3.15it/s]
 22%|██▏       | 422/1939 [01:40<08:48,  2.87it/s]
 22%|██▏       | 424/1939 [01:40<06:10,  4.08it/s]
 22%|██▏       | 426/1939 [01:41<06:16,  4.02it/s]
 22%|██▏       | 427/1939 [01:41<06:11,  4.07it/s]
 22%|██▏       | 428/1939 [01:42<08:52,  2.84it/s]
 22%|██▏       | 430/1939 [01:42<07:35,  3.31it/s]
 22%|██▏       | 432/1939 [01:42<05:28,  4.59it/s]
 23%|██▎       | 438/1939 [01:42<02:25, 10.31it/s]
 23%|██▎       | 441/1939 [01:43<02:49,  8.84it/s]
 23%|██▎       | 443/1939 [01:43<02:32,  9.82it/s]
 23%|██▎       | 447/1939 [01:43<01:49, 13.64it/s]
 23%|██▎       | 451/1939 [01:43<01:24, 17.58it/s]
 24%|██▎       | 457/1939 [01:43<00:59, 24.89it/s]
 24%|██▍       | 461/1939 [01:43<00:53, 27.38it/s]
 24%|██▍       | 466/1939 [01:43<00:46, 31.55it/s]
 24%|██▍       | 472/1939 [01:43<00:40, 36.35it/s]
 25%|██▍       | 477/1939 [01:44<01:16, 19.22it/s]
 25%|██▍       | 481/1939 [01:45<02:46,  8.77it/s]
 25%|██▍       | 484/1939 [01:46<03:00,  8.06it/s]
 25%|██▌       | 489/1939 [01:46<02:41,  8.98it/s]
 25%|██▌       | 491/1939 [01:46<02:48,  8.60it/s]
 25%|██▌       | 493/1939 [01:47<03:19,  7.25it/s]
 26%|██▌       | 495/1939 [01:47<03:30,  6.88it/s]
 26%|██▌       | 496/1939 [01:47<03:41,  6.52it/s]
 26%|██▌       | 498/1939 [01:48<03:04,  7.81it/s]
 26%|██▌       | 500/1939 [01:48<02:53,  8.30it/s]
 26%|██▌       | 502/1939 [01:48<02:25,  9.90it/s]
 26%|██▌       | 505/1939 [01:48<02:47,  8.55it/s]
 26%|██▌       | 507/1939 [01:48<02:27,  9.73it/s]
 26%|██▋       | 513/1939 [01:49<01:25, 16.64it/s]
 27%|██▋       | 517/1939 [01:49<01:09, 20.59it/s]
 27%|██▋       | 522/1939 [01:49<00:54, 25.77it/s]
 27%|██▋       | 528/1939 [01:49<01:04, 21.74it/s]
 27%|██▋       | 531/1939 [01:49<01:08, 20.67it/s]
 28%|██▊       | 534/1939 [01:49<01:04, 21.71it/s]
 28%|██▊       | 537/1939 [01:50<02:45,  8.45it/s]
 28%|██▊       | 539/1939 [01:51<04:11,  5.57it/s]
 28%|██▊       | 541/1939 [01:52<04:25,  5.26it/s]
 28%|██▊       | 544/1939 [01:52<03:16,  7.10it/s]
 28%|██▊       | 546/1939 [01:52<03:53,  5.96it/s]
 28%|██▊       | 548/1939 [01:53<04:32,  5.10it/s]
 28%|██▊       | 550/1939 [01:53<03:45,  6.16it/s]
 28%|██▊       | 552/1939 [01:54<04:25,  5.23it/s]
 29%|██▊       | 555/1939 [01:54<03:06,  7.40it/s]
 29%|██▊       | 557/1939 [01:54<02:44,  8.39it/s]
 29%|██▉       | 559/1939 [01:54<02:51,  8.05it/s]
 29%|██▉       | 561/1939 [01:54<02:42,  8.46it/s]
 29%|██▉       | 563/1939 [01:55<02:56,  7.81it/s]
 29%|██▉       | 567/1939 [01:55<02:25,  9.43it/s]
 29%|██▉       | 569/1939 [01:55<02:30,  9.09it/s]
 29%|██▉       | 571/1939 [01:55<02:46,  8.23it/s]
 29%|██▉       | 572/1939 [01:56<03:49,  5.95it/s]
 30%|██▉       | 574/1939 [01:57<05:35,  4.06it/s]
 30%|██▉       | 575/1939 [01:57<06:35,  3.45it/s]
 30%|██▉       | 576/1939 [01:58<07:59,  2.84it/s]
 30%|██▉       | 578/1939 [01:58<05:29,  4.13it/s]
 30%|██▉       | 579/1939 [01:58<06:01,  3.76it/s]
 30%|██▉       | 580/1939 [01:59<07:06,  3.18it/s]
 30%|███       | 582/1939 [02:00<08:01,  2.82it/s]
 30%|███       | 584/1939 [02:00<07:01,  3.21it/s]
 30%|███       | 586/1939 [02:01<06:44,  3.35it/s]
 30%|███       | 588/1939 [02:01<05:04,  4.44it/s]
 30%|███       | 589/1939 [02:01<05:56,  3.79it/s]
 30%|███       | 590/1939 [02:02<09:22,  2.40it/s]
 30%|███       | 591/1939 [02:03<11:57,  1.88it/s]
 31%|███       | 592/1939 [02:04<11:25,  1.97it/s]
 31%|███       | 593/1939 [02:04<10:51,  2.07it/s]
 31%|███       | 595/1939 [02:04<08:16,  2.71it/s]
 31%|███       | 596/1939 [02:05<08:53,  2.52it/s]
 31%|███       | 598/1939 [02:05<05:54,  3.78it/s]
 31%|███       | 599/1939 [02:06<09:20,  2.39it/s]
 31%|███       | 600/1939 [02:06<09:22,  2.38it/s]
 31%|███       | 601/1939 [02:07<09:05,  2.45it/s]
 31%|███       | 603/1939 [02:07<06:50,  3.26it/s]
 31%|███       | 605/1939 [02:08<07:06,  3.13it/s]
 31%|███▏      | 607/1939 [02:08<06:54,  3.21it/s]
 31%|███▏      | 608/1939 [02:09<07:24,  2.99it/s]
 31%|███▏      | 609/1939 [02:10<10:17,  2.16it/s]
 32%|███▏      | 611/1939 [02:11<10:47,  2.05it/s]
 32%|███▏      | 612/1939 [02:12<12:58,  1.70it/s]
 32%|███▏      | 613/1939 [02:12<12:08,  1.82it/s]
 32%|███▏      | 614/1939 [02:13<14:17,  1.55it/s]
 32%|███▏      | 615/1939 [02:14<16:04,  1.37it/s]
 32%|███▏      | 616/1939 [02:15<17:24,  1.27it/s]
 32%|███▏      | 617/1939 [02:16<18:37,  1.18it/s]
 32%|███▏      | 618/1939 [02:17<19:11,  1.15it/s]
 32%|███▏      | 619/1939 [02:18<19:35,  1.12it/s]
 32%|███▏      | 620/1939 [02:19<20:19,  1.08it/s]
 32%|███▏      | 621/1939 [02:20<20:14,  1.08it/s]
 32%|███▏      | 622/1939 [02:21<20:32,  1.07it/s]
 32%|███▏      | 625/1939 [02:21<09:33,  2.29it/s]
 32%|███▏      | 627/1939 [02:21<07:57,  2.75it/s]
 32%|███▏      | 629/1939 [02:22<09:08,  2.39it/s]
 32%|███▏      | 630/1939 [02:23<11:25,  1.91it/s]
 33%|███▎      | 632/1939 [02:24<11:07,  1.96it/s]
 33%|███▎      | 635/1939 [02:24<06:44,  3.23it/s]
 33%|███▎      | 636/1939 [02:25<08:47,  2.47it/s]
 33%|███▎      | 637/1939 [02:26<08:48,  2.46it/s]
 33%|███▎      | 639/1939 [02:26<06:06,  3.54it/s]
 33%|███▎      | 640/1939 [02:27<08:15,  2.62it/s]
 33%|███▎      | 641/1939 [02:27<09:43,  2.22it/s]
 33%|███▎      | 643/1939 [02:28<08:13,  2.63it/s]
 33%|███▎      | 645/1939 [02:28<05:51,  3.68it/s]
 33%|███▎      | 646/1939 [02:28<05:23,  4.00it/s]
 33%|███▎      | 648/1939 [02:28<03:50,  5.59it/s]
 34%|███▎      | 650/1939 [02:29<04:42,  4.56it/s]
 34%|███▎      | 651/1939 [02:29<06:20,  3.38it/s]
 34%|███▎      | 652/1939 [02:30<06:08,  3.49it/s]
 34%|███▎      | 653/1939 [02:30<06:08,  3.49it/s]
 34%|███▎      | 654/1939 [02:31<08:16,  2.59it/s]
 34%|███▍      | 656/1939 [02:31<07:00,  3.05it/s]
 34%|███▍      | 658/1939 [02:32<06:32,  3.26it/s]
 34%|███▍      | 659/1939 [02:32<08:16,  2.58it/s]
 34%|███▍      | 661/1939 [02:33<05:46,  3.69it/s]
 34%|███▍      | 665/1939 [02:33<04:54,  4.32it/s]
 34%|███▍      | 666/1939 [02:34<06:02,  3.51it/s]
 34%|███▍      | 668/1939 [02:34<04:43,  4.48it/s]
 35%|███▍      | 672/1939 [02:34<03:24,  6.20it/s]
 35%|███▍      | 673/1939 [02:35<03:53,  5.42it/s]
 35%|███▍      | 675/1939 [02:35<03:04,  6.85it/s]
 35%|███▍      | 677/1939 [02:35<03:37,  5.81it/s]
 35%|███▍      | 678/1939 [02:36<04:08,  5.08it/s]
 35%|███▌      | 680/1939 [02:36<04:06,  5.11it/s]
 35%|███▌      | 682/1939 [02:36<03:14,  6.46it/s]
 35%|███▌      | 683/1939 [02:37<04:42,  4.44it/s]
 35%|███▌      | 684/1939 [02:37<05:09,  4.06it/s]
 35%|███▌      | 687/1939 [02:37<04:12,  4.96it/s]
 35%|███▌      | 688/1939 [02:38<04:38,  4.49it/s]
 36%|███▌      | 689/1939 [02:38<05:28,  3.80it/s]
 36%|███▌      | 691/1939 [02:38<04:16,  4.87it/s]
 36%|███▌      | 692/1939 [02:39<05:22,  3.87it/s]
 36%|███▌      | 694/1939 [02:39<03:50,  5.40it/s]
 36%|███▌      | 702/1939 [02:39<01:24, 14.67it/s]
 36%|███▋      | 706/1939 [02:39<01:07, 18.27it/s]
 37%|███▋      | 710/1939 [02:39<01:07, 18.17it/s]
 37%|███▋      | 715/1939 [02:40<00:52, 23.38it/s]
 37%|███▋      | 721/1939 [02:40<00:41, 29.53it/s]
 37%|███▋      | 725/1939 [02:40<00:44, 27.51it/s]
 38%|███▊      | 729/1939 [02:40<00:49, 24.46it/s]
 38%|███▊      | 732/1939 [02:41<02:11,  9.15it/s]
 38%|███▊      | 735/1939 [02:42<02:37,  7.64it/s]
 38%|███▊      | 737/1939 [02:42<02:21,  8.50it/s]
 38%|███▊      | 739/1939 [02:43<03:50,  5.21it/s]
 38%|███▊      | 741/1939 [02:43<03:12,  6.23it/s]
 38%|███▊      | 743/1939 [02:44<04:54,  4.07it/s]
 38%|███▊      | 745/1939 [02:44<04:47,  4.15it/s]
 39%|███▊      | 747/1939 [02:45<06:11,  3.21it/s]
 39%|███▊      | 748/1939 [02:46<06:39,  2.98it/s]
 39%|███▊      | 749/1939 [02:47<08:54,  2.23it/s]
 39%|███▊      | 751/1939 [02:48<09:13,  2.15it/s]
 39%|███▉      | 752/1939 [02:49<11:11,  1.77it/s]
 39%|███▉      | 754/1939 [02:49<07:31,  2.62it/s]
 39%|███▉      | 755/1939 [02:50<09:51,  2.00it/s]
 39%|███▉      | 757/1939 [02:51<09:55,  1.98it/s]
 39%|███▉      | 759/1939 [02:51<08:13,  2.39it/s]
 39%|███▉      | 760/1939 [02:52<10:21,  1.90it/s]
 39%|███▉      | 762/1939 [02:52<07:02,  2.79it/s]
 39%|███▉      | 763/1939 [02:53<09:20,  2.10it/s]
 39%|███▉      | 764/1939 [02:54<11:22,  1.72it/s]
 40%|███▉      | 766/1939 [02:55<10:43,  1.82it/s]
 40%|███▉      | 767/1939 [02:56<12:17,  1.59it/s]
 40%|███▉      | 768/1939 [02:57<13:49,  1.41it/s]
 40%|███▉      | 769/1939 [02:58<15:04,  1.29it/s]
 40%|███▉      | 770/1939 [02:59<16:06,  1.21it/s]
 40%|███▉      | 771/1939 [02:59<13:51,  1.40it/s]
 40%|███▉      | 772/1939 [03:00<15:17,  1.27it/s]
 40%|███▉      | 773/1939 [03:01<13:52,  1.40it/s]
 40%|███▉      | 775/1939 [03:01<08:09,  2.38it/s]
 40%|████      | 776/1939 [03:02<09:35,  2.02it/s]
 40%|████      | 777/1939 [03:03<10:56,  1.77it/s]
 40%|████      | 779/1939 [03:04<10:27,  1.85it/s]
 40%|████      | 780/1939 [03:05<12:05,  1.60it/s]
 40%|████      | 781/1939 [03:05<12:40,  1.52it/s]
 40%|████      | 783/1939 [03:05<08:07,  2.37it/s]
 40%|████      | 784/1939 [03:06<08:52,  2.17it/s]
 41%|████      | 787/1939 [03:07<06:18,  3.04it/s]
 41%|████      | 789/1939 [03:07<06:21,  3.01it/s]
 41%|████      | 791/1939 [03:08<06:37,  2.89it/s]
 41%|████      | 793/1939 [03:08<04:59,  3.83it/s]
 41%|████      | 794/1939 [03:08<05:03,  3.78it/s]
 41%|████      | 795/1939 [03:09<04:42,  4.04it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 315.85it/s]
 34%|███▎      | 101/300 [08:10<4:43:02, 85.34s/it]

[[np.int64(0), False, 1], [np.int64(2), False, 11], [np.int64(3), False, 6], [np.int64(4), False, 1], [np.int64(5), False, 13], [np.int64(6), False, 10], [np.int64(7), False, 6], [np.int64(8), False, 4], [np.int64(9), False, 6], [np.int64(12), False, 0], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.4719, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9036, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.4655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0037, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [08:11<3:45:00, 68.19s/it]

tensor(13.4814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2244, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [08:11<2:21:31, 43.32s/it]

tensor(13.5323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4140, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.6130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5715, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.6941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6718, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [08:11<1:32:09, 28.50s/it]

tensor(13.7362, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7160, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [08:11<1:01:19, 19.16s/it]

tensor(13.7260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7464, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.6783, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8099, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.6190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9037, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [08:11<41:23, 13.07s/it]

tensor(13.5680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.5314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9924, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [08:12<28:12,  9.00s/it]

tensor(13.5052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0119, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [08:12<19:22,  6.25s/it]

tensor(13.4827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0297, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4617, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0580, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1073, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [08:12<13:22,  4.36s/it]

tensor(13.4273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1728, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [08:12<09:17,  3.06s/it]

tensor(13.4057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1637, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [08:12<06:29,  2.16s/it]

tensor(13.3963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1915, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2373, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2740, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [08:13<04:33,  1.54s/it]

tensor(13.3494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3062, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3352, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3265, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [08:13<03:14,  1.10s/it]

tensor(13.3262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3725, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [08:13<02:19,  1.25it/s]

tensor(13.3201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3937, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4390, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [08:13<01:41,  1.70it/s]

tensor(13.2946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4818, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [08:13<01:14,  2.27it/s]

tensor(13.2745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5023, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [08:14<00:56,  2.96it/s]

tensor(13.2665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5220, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2583, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5464, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5613, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [08:14<00:44,  3.77it/s]

tensor(13.2410, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5781, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5944, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [08:14<00:35,  4.66it/s]

tensor(13.2283, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6181, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [08:14<00:29,  5.58it/s]

tensor(13.2229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6373, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6532, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6634, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [08:14<00:24,  6.50it/s]

tensor(13.2046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6710, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6872, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [08:14<00:21,  7.34it/s]

tensor(13.1915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6969, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [08:15<00:19,  8.07it/s]

tensor(13.1851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7135, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7273, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7323, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [08:15<00:17,  8.64it/s]

tensor(13.1674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7368, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1617, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7452, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [08:15<00:16,  9.10it/s]

tensor(13.1563, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7548, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [08:15<00:15,  9.43it/s]

tensor(13.1510, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7602, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([158, 210,  28, 175,  91, 219,  81, 139,  44, 106, 306, 129,  33, 220])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 4/1939 [00:00<00:56, 34.54it/s]
  1%|          | 10/1939 [00:00<00:40, 47.29it/s]
  1%|          | 16/1939 [00:00<00:39, 49.03it/s]
  1%|          | 21/1939 [00:00<00:41, 46.52it/s]
  1%|▏         | 26/1939 [00:00<00:51, 36.92it/s]
  2%|▏         | 30/1939 [00:00<00:53, 35.38it/s]
  2%|▏         | 36/1939 [00:00<00:46, 40.66it/s]
  2%|▏         | 41/1939 [00:01<01:16, 24.94it/s]
  2%|▏         | 45/1939 [00:01<01:14, 25.47it/s]
  3%|▎         | 49/1939 [00:01<01:30, 20.96it/s]
  3%|▎         | 52/1939 [00:01<01:29, 21.18it/s]
  3%|▎         | 55/1939 [00:02<02:13, 14.08it/s]
  3%|▎         | 58/1939 [00:02<02:33, 12.24it/s]
  3%|▎         | 60/1939 [00:02<02:22, 13.18it/s]
  3%|▎         | 65/1939 [00:02<01:39, 18.91it/s]
  4%|▎         | 68/1939 [00:03<02:15, 13.78it/s]
  4%|▎         | 72/1939 [00:03<01:46, 17.48it/s]
  4%|▍         | 75/1939 [00:03<02:24, 12.86it/s]
  4%|▍         | 78/1939 [00:04<02:43, 11.41it/s]
  4%|▍         | 80/1939 [00:04<03:20,  9.29it/s]
  4%|▍         | 82/1939 [00:04<02:59, 10.34it/s]
  4%|▍         | 86/1939 [00:04<02:53, 10.69it/s]
  5%|▍         | 88/1939 [00:05<02:49, 10.91it/s]
  5%|▍         | 92/1939 [00:05<02:05, 14.69it/s]
  5%|▍         | 94/1939 [00:05<02:52, 10.72it/s]
  5%|▍         | 96/1939 [00:05<02:41, 11.40it/s]
  5%|▌         | 99/1939 [00:05<02:11, 13.97it/s]
  5%|▌         | 103/1939 [00:05<01:39, 18.38it/s]
  6%|▌         | 110/1939 [00:06<01:04, 28.37it/s]
  6%|▌         | 115/1939 [00:06<00:57, 31.46it/s]
  6%|▌         | 119/1939 [00:06<01:35, 19.06it/s]
  6%|▋         | 122/1939 [00:06<01:58, 15.32it/s]
  6%|▋         | 126/1939 [00:07<01:38, 18.48it/s]
  7%|▋         | 130/1939 [00:07<01:25, 21.20it/s]
  7%|▋         | 133/1939 [00:07<01:59, 15.08it/s]
  7%|▋         | 136/1939 [00:07<01:45, 17.08it/s]
  7%|▋         | 139/1939 [00:08<02:36, 11.48it/s]
  7%|▋         | 142/1939 [00:08<02:13, 13.47it/s]
  7%|▋         | 145/1939 [00:08<02:48, 10.66it/s]
  8%|▊         | 147/1939 [00:08<02:48, 10.63it/s]
  8%|▊         | 149/1939 [00:08<02:30, 11.89it/s]
  8%|▊         | 153/1939 [00:09<02:41, 11.05it/s]
  8%|▊         | 155/1939 [00:09<02:27, 12.12it/s]
  8%|▊         | 158/1939 [00:09<02:42, 10.98it/s]
  8%|▊         | 160/1939 [00:10<03:04,  9.65it/s]
  8%|▊         | 162/1939 [00:10<03:05,  9.59it/s]
  8%|▊         | 164/1939 [00:10<03:19,  8.89it/s]
  9%|▊         | 166/1939 [00:10<03:02,  9.73it/s]
  9%|▊         | 168/1939 [00:10<02:40, 11.06it/s]
  9%|▉         | 171/1939 [00:10<02:12, 13.32it/s]
  9%|▉         | 174/1939 [00:11<01:51, 15.78it/s]
  9%|▉         | 180/1939 [00:11<01:13, 24.06it/s]
  9%|▉         | 183/1939 [00:11<01:13, 24.03it/s]
 10%|▉         | 188/1939 [00:11<00:58, 29.92it/s]
 10%|▉         | 192/1939 [00:11<00:54, 31.99it/s]
 10%|█         | 198/1939 [00:11<00:45, 38.36it/s]
 10%|█         | 203/1939 [00:12<01:51, 15.62it/s]
 11%|█         | 207/1939 [00:13<02:45, 10.44it/s]
 11%|█         | 210/1939 [00:13<02:31, 11.42it/s]
 11%|█         | 213/1939 [00:13<02:51, 10.06it/s]
 11%|█         | 215/1939 [00:14<03:19,  8.65it/s]
 11%|█         | 218/1939 [00:14<02:39, 10.80it/s]
 12%|█▏        | 223/1939 [00:14<01:50, 15.48it/s]
 12%|█▏        | 228/1939 [00:14<01:59, 14.31it/s]
 12%|█▏        | 231/1939 [00:14<01:51, 15.26it/s]
 12%|█▏        | 234/1939 [00:15<02:17, 12.38it/s]
 12%|█▏        | 236/1939 [00:15<02:49, 10.06it/s]
 50%|█████     | 150/300 [08:34<00:15,  9.43it/s]]
 12%|█▏        | 240/1939 [00:16<04:02,  7.00it/s]
 12%|█▏        | 242/1939 [00:16<04:26,  6.36it/s]
 13%|█▎        | 243/1939 [00:17<05:19,  5.31it/s]
 13%|█▎        | 245/1939 [00:17<05:19,  5.30it/s]
 13%|█▎        | 246/1939 [00:17<06:03,  4.65it/s]
 13%|█▎        | 247/1939 [00:17<05:35,  5.05it/s]
 13%|█▎        | 253/1939 [00:18<02:23, 11.77it/s]
 13%|█▎        | 256/1939 [00:18<01:56, 14.46it/s]
 13%|█▎        | 259/1939 [00:18<02:34, 10.87it/s]
 13%|█▎        | 261/1939 [00:18<03:00,  9.29it/s]
 14%|█▎        | 264/1939 [00:19<02:21, 11.80it/s]
 14%|█▍        | 271/1939 [00:19<01:26, 19.20it/s]
 14%|█▍        | 274/1939 [00:19<01:22, 20.30it/s]
 14%|█▍        | 280/1939 [00:19<00:59, 27.76it/s]
 15%|█▍        | 285/1939 [00:19<01:10, 23.50it/s]
 15%|█▍        | 289/1939 [00:19<01:10, 23.40it/s]
 15%|█▌        | 293/1939 [00:19<01:02, 26.29it/s]
 15%|█▌        | 299/1939 [00:20<00:50, 32.63it/s]
 16%|█▌        | 305/1939 [00:20<00:42, 38.79it/s]
 16%|█▌        | 310/1939 [00:20<01:04, 25.19it/s]
 16%|█▌        | 315/1939 [00:20<01:00, 27.03it/s]
 16%|█▋        | 319/1939 [00:20<01:08, 23.52it/s]
 17%|█▋        | 322/1939 [00:21<02:03, 13.04it/s]
 17%|█▋        | 325/1939 [00:21<01:53, 14.20it/s]
 17%|█▋        | 330/1939 [00:21<01:24, 19.05it/s]
 17%|█▋        | 333/1939 [00:21<01:25, 18.75it/s]
 17%|█▋        | 336/1939 [00:22<01:18, 20.48it/s]
 18%|█▊        | 341/1939 [00:22<01:01, 25.79it/s]
 18%|█▊        | 347/1939 [00:22<00:49, 32.10it/s]
 18%|█▊        | 351/1939 [00:22<01:06, 23.70it/s]
 18%|█▊        | 355/1939 [00:23<02:06, 12.57it/s]
 19%|█▊        | 359/1939 [00:23<01:44, 15.18it/s]
 19%|█▊        | 362/1939 [00:23<01:36, 16.36it/s]
 19%|█▉        | 365/1939 [00:23<02:13, 11.80it/s]
 19%|█▉        | 369/1939 [00:24<01:49, 14.32it/s]
 19%|█▉        | 374/1939 [00:24<01:21, 19.18it/s]
 19%|█▉        | 377/1939 [00:24<01:55, 13.57it/s]
 20%|█▉        | 381/1939 [00:24<01:32, 16.88it/s]
 20%|█▉        | 384/1939 [00:25<01:50, 14.02it/s]
 20%|█▉        | 387/1939 [00:25<02:13, 11.64it/s]
 20%|██        | 389/1939 [00:25<02:38,  9.78it/s]
 20%|██        | 391/1939 [00:26<02:47,  9.24it/s]
 20%|██        | 393/1939 [00:26<03:05,  8.33it/s]
 20%|██        | 395/1939 [00:26<03:03,  8.42it/s]
 20%|██        | 396/1939 [00:26<03:12,  8.02it/s]
 20%|██        | 397/1939 [00:26<03:07,  8.20it/s]
 21%|██        | 399/1939 [00:27<02:54,  8.83it/s]
 21%|██        | 401/1939 [00:27<02:26, 10.47it/s]
 21%|██        | 404/1939 [00:27<02:45,  9.27it/s]
 21%|██        | 406/1939 [00:27<03:25,  7.46it/s]
 21%|██        | 409/1939 [00:28<02:27, 10.37it/s]
 21%|██        | 412/1939 [00:28<01:57, 13.01it/s]
 21%|██▏       | 415/1939 [00:28<01:56, 13.13it/s]
 22%|██▏       | 417/1939 [00:28<01:46, 14.27it/s]
 22%|██▏       | 419/1939 [00:28<02:08, 11.80it/s]
 22%|██▏       | 421/1939 [00:28<01:55, 13.17it/s]
 22%|██▏       | 423/1939 [00:29<02:38,  9.59it/s]
 22%|██▏       | 426/1939 [00:29<02:54,  8.69it/s]
 22%|██▏       | 428/1939 [00:30<03:22,  7.45it/s]
 22%|██▏       | 430/1939 [00:30<02:53,  8.68it/s]
 22%|██▏       | 436/1939 [00:30<01:33, 16.00it/s]
 23%|██▎       | 441/1939 [00:30<01:09, 21.54it/s]
 23%|██▎       | 445/1939 [00:30<01:02, 23.78it/s]
 23%|██▎       | 451/1939 [00:30<00:47, 31.07it/s]
 24%|██▎       | 456/1939 [00:30<00:43, 34.47it/s]
 24%|██▍       | 461/1939 [00:30<00:45, 32.78it/s]
 24%|██▍       | 466/1939 [00:30<00:40, 36.14it/s]
 24%|██▍       | 471/1939 [00:31<00:37, 39.17it/s]
 25%|██▍       | 476/1939 [00:31<00:42, 34.64it/s]
 25%|██▍       | 480/1939 [00:31<00:43, 33.40it/s]
 25%|██▌       | 485/1939 [00:31<00:41, 34.69it/s]
 25%|██▌       | 489/1939 [00:31<01:01, 23.77it/s]
 25%|██▌       | 492/1939 [00:32<01:11, 20.26it/s]
 26%|██▌       | 500/1939 [00:32<00:47, 30.46it/s]
 26%|██▌       | 507/1939 [00:32<00:38, 37.62it/s]
 26%|██▋       | 512/1939 [00:32<00:39, 36.03it/s]
 27%|██▋       | 517/1939 [00:32<00:41, 34.48it/s]
 27%|██▋       | 521/1939 [00:32<00:44, 31.67it/s]
 27%|██▋       | 526/1939 [00:32<00:40, 34.61it/s]
 27%|██▋       | 531/1939 [00:32<00:37, 37.45it/s]
 28%|██▊       | 536/1939 [00:33<00:39, 35.09it/s]
 28%|██▊       | 540/1939 [00:33<00:46, 30.36it/s]
 28%|██▊       | 546/1939 [00:33<00:38, 36.30it/s]
 28%|██▊       | 551/1939 [00:33<00:56, 24.74it/s]
 29%|██▊       | 555/1939 [00:33<00:53, 25.74it/s]
 29%|██▉       | 561/1939 [00:34<00:47, 28.88it/s]
 29%|██▉       | 565/1939 [00:34<00:47, 28.71it/s]
 29%|██▉       | 571/1939 [00:34<00:56, 24.31it/s]
 30%|██▉       | 574/1939 [00:35<01:51, 12.20it/s]
 30%|██▉       | 577/1939 [00:35<02:20,  9.72it/s]
 30%|██▉       | 579/1939 [00:36<02:39,  8.52it/s]
 30%|██▉       | 581/1939 [00:36<02:29,  9.10it/s]
 30%|███       | 583/1939 [00:36<02:44,  8.26it/s]
 30%|███       | 585/1939 [00:37<03:01,  7.44it/s]
 30%|███       | 586/1939 [00:37<03:38,  6.18it/s]
 30%|███       | 589/1939 [00:37<02:34,  8.75it/s]
 31%|███       | 594/1939 [00:37<01:33, 14.44it/s]
 31%|███       | 597/1939 [00:37<01:52, 11.89it/s]
 31%|███       | 599/1939 [00:38<02:10, 10.23it/s]
 31%|███       | 601/1939 [00:38<02:38,  8.42it/s]
 31%|███       | 603/1939 [00:38<02:20,  9.48it/s]
 31%|███       | 605/1939 [00:38<02:01, 11.01it/s]
 31%|███▏      | 607/1939 [00:39<02:14,  9.92it/s]
 31%|███▏      | 609/1939 [00:39<02:40,  8.31it/s]
 32%|███▏      | 611/1939 [00:39<02:39,  8.30it/s]
 32%|███▏      | 613/1939 [00:40<03:07,  7.09it/s]
 32%|███▏      | 614/1939 [00:40<03:28,  6.37it/s]
 32%|███▏      | 615/1939 [00:40<03:45,  5.86it/s]
 32%|███▏      | 616/1939 [00:40<04:14,  5.19it/s]
 32%|███▏      | 617/1939 [00:40<04:22,  5.03it/s]
 32%|███▏      | 618/1939 [00:41<03:57,  5.57it/s]
 32%|███▏      | 619/1939 [00:41<03:40,  5.98it/s]
 32%|███▏      | 620/1939 [00:41<04:37,  4.76it/s]
 32%|███▏      | 622/1939 [00:41<03:16,  6.70it/s]
 32%|███▏      | 628/1939 [00:41<01:24, 15.44it/s]
 33%|███▎      | 631/1939 [00:42<01:52, 11.67it/s]
 33%|███▎      | 634/1939 [00:42<01:32, 14.16it/s]
 33%|███▎      | 640/1939 [00:42<01:00, 21.62it/s]
 33%|███▎      | 643/1939 [00:42<01:23, 15.58it/s]
 33%|███▎      | 646/1939 [00:42<01:19, 16.28it/s]
 34%|███▎      | 651/1939 [00:43<00:58, 22.00it/s]
 34%|███▍      | 656/1939 [00:43<01:07, 19.07it/s]
 34%|███▍      | 659/1939 [00:43<01:37, 13.19it/s]
 34%|███▍      | 664/1939 [00:43<01:12, 17.63it/s]
 34%|███▍      | 667/1939 [00:44<01:29, 14.14it/s]
 35%|███▍      | 670/1939 [00:44<01:20, 15.85it/s]
 35%|███▍      | 673/1939 [00:44<01:42, 12.37it/s]
 35%|███▍      | 676/1939 [00:45<01:58, 10.63it/s]
 35%|███▍      | 678/1939 [00:45<01:48, 11.67it/s]
 35%|███▌      | 680/1939 [00:45<02:16,  9.21it/s]
 35%|███▌      | 682/1939 [00:45<02:05,  9.99it/s]
 35%|███▌      | 684/1939 [00:46<02:38,  7.92it/s]
 35%|███▌      | 686/1939 [00:46<02:19,  8.98it/s]
 35%|███▌      | 688/1939 [00:46<02:52,  7.25it/s]
 36%|███▌      | 689/1939 [00:47<03:25,  6.09it/s]
 36%|███▌      | 692/1939 [00:47<02:29,  8.35it/s]
 36%|███▌      | 696/1939 [00:47<01:36, 12.83it/s]
 36%|███▌      | 702/1939 [00:47<01:01, 20.23it/s]
 37%|███▋      | 708/1939 [00:47<00:46, 26.43it/s]
 37%|███▋      | 713/1939 [00:47<00:39, 30.76it/s]
 37%|███▋      | 719/1939 [00:47<00:32, 37.04it/s]
 37%|███▋      | 724/1939 [00:47<00:35, 34.45it/s]
 38%|███▊      | 729/1939 [00:48<00:32, 36.98it/s]
 38%|███▊      | 734/1939 [00:48<01:19, 15.15it/s]
 38%|███▊      | 738/1939 [00:49<01:16, 15.67it/s]
 38%|███▊      | 741/1939 [00:49<01:31, 13.14it/s]
 38%|███▊      | 744/1939 [00:49<01:37, 12.28it/s]
 39%|███▊      | 747/1939 [00:50<01:48, 11.01it/s]
 39%|███▊      | 749/1939 [00:50<01:42, 11.62it/s]
 39%|███▉      | 754/1939 [00:50<01:10, 16.89it/s]
 39%|███▉      | 757/1939 [00:50<01:46, 11.07it/s]
 39%|███▉      | 759/1939 [00:51<01:41, 11.57it/s]
 39%|███▉      | 761/1939 [00:51<02:10,  9.01it/s]
 39%|███▉      | 763/1939 [00:51<02:17,  8.53it/s]
 39%|███▉      | 765/1939 [00:51<02:11,  8.95it/s]
 40%|███▉      | 767/1939 [00:52<03:06,  6.29it/s]
 40%|███▉      | 769/1939 [00:52<03:09,  6.18it/s]
 40%|███▉      | 770/1939 [00:53<03:31,  5.52it/s]
 40%|███▉      | 772/1939 [00:53<03:52,  5.01it/s]
 40%|███▉      | 773/1939 [00:53<03:59,  4.87it/s]
 40%|███▉      | 775/1939 [00:53<03:10,  6.10it/s]
 40%|████      | 776/1939 [00:54<03:56,  4.91it/s]
 40%|████      | 777/1939 [00:54<04:05,  4.73it/s]
 40%|████      | 779/1939 [00:54<03:38,  5.31it/s]
 40%|████      | 780/1939 [00:55<03:45,  5.14it/s]
 40%|████      | 781/1939 [00:55<03:19,  5.80it/s]
 40%|████      | 783/1939 [00:55<02:30,  7.67it/s]
 40%|████      | 784/1939 [00:55<03:15,  5.91it/s]
 41%|████      | 786/1939 [00:55<02:28,  7.75it/s]
 41%|████      | 787/1939 [00:56<03:33,  5.40it/s]
 41%|████      | 789/1939 [00:56<03:17,  5.82it/s]
 41%|████      | 791/1939 [00:56<02:53,  6.60it/s]
 41%|████      | 793/1939 [00:56<02:17,  8.35it/s]
 41%|████      | 795/1939 [00:56<01:54,  9.95it/s]
 41%|████      | 798/1939 [00:57<01:54, 10.00it/s]
 41%|████▏     | 800/1939 [00:57<01:39, 11.50it/s]
 41%|████▏     | 804/1939 [00:57<01:39, 11.44it/s]
 42%|████▏     | 806/1939 [00:58<02:47,  6.75it/s]
 42%|████▏     | 808/1939 [00:58<02:28,  7.61it/s]
 42%|████▏     | 810/1939 [00:58<02:25,  7.77it/s]
 42%|████▏     | 812/1939 [00:59<02:50,  6.60it/s]
 42%|████▏     | 813/1939 [00:59<03:25,  5.47it/s]
 42%|████▏     | 814/1939 [00:59<03:53,  4.81it/s]
 42%|████▏     | 816/1939 [01:00<03:38,  5.13it/s]
 42%|████▏     | 817/1939 [01:00<04:05,  4.57it/s]
 42%|████▏     | 818/1939 [01:00<04:37,  4.03it/s]
 42%|████▏     | 819/1939 [01:01<04:49,  3.87it/s]
 42%|████▏     | 820/1939 [01:01<04:57,  3.76it/s]
 42%|████▏     | 821/1939 [01:01<05:08,  3.63it/s]
 42%|████▏     | 822/1939 [01:02<05:26,  3.43it/s]
 42%|████▏     | 823/1939 [01:02<05:02,  3.69it/s]
 43%|████▎     | 825/1939 [01:02<03:28,  5.34it/s]
 43%|████▎     | 828/1939 [01:02<02:12,  8.41it/s]
 43%|████▎     | 834/1939 [01:02<01:07, 16.43it/s]
 43%|████▎     | 839/1939 [01:02<00:49, 22.20it/s]
 44%|████▎     | 844/1939 [01:02<00:40, 26.99it/s]
 44%|████▍     | 849/1939 [01:03<00:34, 31.77it/s]
 44%|████▍     | 854/1939 [01:03<00:30, 36.11it/s]
 44%|████▍     | 859/1939 [01:03<00:27, 38.72it/s]
 45%|████▍     | 864/1939 [01:03<00:45, 23.66it/s]
 45%|████▍     | 868/1939 [01:03<00:44, 23.97it/s]
 45%|████▌     | 874/1939 [01:03<00:34, 30.54it/s]
 45%|████▌     | 878/1939 [01:04<00:34, 30.54it/s]
 45%|████▌     | 882/1939 [01:04<00:37, 28.44it/s]
 46%|████▌     | 888/1939 [01:04<00:30, 34.53it/s]
 46%|████▌     | 892/1939 [01:04<00:30, 34.15it/s]
 46%|████▋     | 899/1939 [01:04<00:25, 40.68it/s]
 47%|████▋     | 904/1939 [01:05<00:46, 22.36it/s]
 47%|████▋     | 908/1939 [01:05<00:45, 22.83it/s]
 47%|████▋     | 912/1939 [01:05<01:04, 15.88it/s]
 47%|████▋     | 917/1939 [01:05<00:52, 19.50it/s]
 47%|████▋     | 920/1939 [01:06<01:10, 14.49it/s]
 48%|████▊     | 926/1939 [01:06<00:50, 20.08it/s]
 48%|████▊     | 930/1939 [01:07<01:25, 11.82it/s]
 48%|████▊     | 933/1939 [01:07<01:38, 10.21it/s]
 48%|████▊     | 939/1939 [01:07<01:06, 14.96it/s]
 49%|████▊     | 945/1939 [01:07<00:51, 19.36it/s]
 49%|████▉     | 949/1939 [01:07<00:45, 21.78it/s]
 49%|████▉     | 955/1939 [01:07<00:35, 27.35it/s]
 50%|████▉     | 961/1939 [01:08<00:29, 32.97it/s]
 50%|████▉     | 966/1939 [01:08<00:27, 35.23it/s]
 50%|█████     | 971/1939 [01:08<01:04, 14.91it/s]
 50%|█████     | 975/1939 [01:09<01:27, 10.98it/s]
 50%|█████     | 978/1939 [01:10<01:38,  9.77it/s]
 51%|█████     | 982/1939 [01:10<01:24, 11.31it/s]
 51%|█████     | 984/1939 [01:10<01:35, 10.03it/s]
 51%|█████     | 986/1939 [01:10<01:29, 10.69it/s]
 51%|█████     | 991/1939 [01:10<01:01, 15.45it/s]
 51%|█████▏    | 996/1939 [01:10<00:46, 20.41it/s]
 52%|█████▏    | 999/1939 [01:11<01:15, 12.52it/s]
 52%|█████▏    | 1002/1939 [01:12<01:43,  9.01it/s]
 52%|█████▏    | 1005/1939 [01:12<01:49,  8.49it/s]
 52%|█████▏    | 1007/1939 [01:12<02:08,  7.24it/s]
 52%|█████▏    | 1009/1939 [01:13<02:15,  6.88it/s]
 52%|█████▏    | 1010/1939 [01:13<02:35,  5.96it/s]
 52%|█████▏    | 1011/1939 [01:13<02:51,  5.41it/s]
 52%|█████▏    | 1012/1939 [01:14<03:18,  4.67it/s]
 52%|█████▏    | 1013/1939 [01:14<03:33,  4.35it/s]
 52%|█████▏    | 1014/1939 [01:14<03:43,  4.15it/s]
 52%|█████▏    | 1015/1939 [01:15<04:06,  3.74it/s]
 52%|█████▏    | 1016/1939 [01:15<04:20,  3.55it/s]
 53%|█████▎    | 1019/1939 [01:15<03:11,  4.80it/s]
 53%|█████▎    | 1021/1939 [01:15<02:23,  6.39it/s]
 53%|█████▎    | 1022/1939 [01:16<02:44,  5.59it/s]
 53%|█████▎    | 1025/1939 [01:16<01:52,  8.16it/s]
 53%|█████▎    | 1027/1939 [01:16<02:08,  7.09it/s]
 53%|█████▎    | 1029/1939 [01:16<01:46,  8.55it/s]
 53%|█████▎    | 1035/1939 [01:17<00:55, 16.41it/s]
 54%|█████▎    | 1041/1939 [01:17<00:38, 23.28it/s]
 54%|█████▍    | 1045/1939 [01:17<00:48, 18.50it/s]
 54%|█████▍    | 1048/1939 [01:17<01:04, 13.90it/s]
 54%|█████▍    | 1051/1939 [01:18<01:19, 11.21it/s]
 54%|█████▍    | 1053/1939 [01:18<02:00,  7.34it/s]
 54%|█████▍    | 1055/1939 [01:19<02:13,  6.61it/s]
 55%|█████▍    | 1057/1939 [01:19<02:16,  6.48it/s]
 55%|█████▍    | 1059/1939 [01:19<02:20,  6.26it/s]
 55%|█████▍    | 1061/1939 [01:20<01:58,  7.41it/s]
 55%|█████▌    | 1068/1939 [01:20<00:58, 15.00it/s]
 55%|█████▌    | 1074/1939 [01:20<00:40, 21.32it/s]
 56%|█████▌    | 1080/1939 [01:20<00:46, 18.29it/s]
 56%|█████▌    | 1083/1939 [01:20<00:45, 18.75it/s]
 56%|█████▌    | 1088/1939 [01:21<00:45, 18.51it/s]
 56%|█████▋    | 1091/1939 [01:21<00:53, 15.76it/s]
 56%|█████▋    | 1093/1939 [01:21<01:02, 13.46it/s]
 56%|█████▋    | 1095/1939 [01:21<00:58, 14.31it/s]
 57%|█████▋    | 1099/1939 [01:22<01:01, 13.63it/s]
 57%|█████▋    | 1102/1939 [01:22<01:18, 10.60it/s]
 57%|█████▋    | 1104/1939 [01:22<01:38,  8.50it/s]
 57%|█████▋    | 1106/1939 [01:23<01:26,  9.63it/s]
 57%|█████▋    | 1111/1939 [01:23<00:55, 14.94it/s]
 58%|█████▊    | 1116/1939 [01:23<00:57, 14.21it/s]
 58%|█████▊    | 1118/1939 [01:23<00:58, 14.09it/s]
 58%|█████▊    | 1120/1939 [01:23<00:57, 14.33it/s]
 58%|█████▊    | 1122/1939 [01:24<01:26,  9.41it/s]
 58%|█████▊    | 1124/1939 [01:24<01:17, 10.58it/s]
 58%|█████▊    | 1126/1939 [01:24<01:10, 11.49it/s]
 58%|█████▊    | 1129/1939 [01:24<01:14, 10.84it/s]
 58%|█████▊    | 1131/1939 [01:25<01:07, 12.03it/s]
 59%|█████▊    | 1136/1939 [01:25<00:42, 18.79it/s]
 59%|█████▊    | 1139/1939 [01:25<01:01, 12.99it/s]
 59%|█████▉    | 1142/1939 [01:25<01:13, 10.90it/s]
 59%|█████▉    | 1144/1939 [01:26<01:23,  9.54it/s]
 59%|█████▉    | 1147/1939 [01:26<01:10, 11.17it/s]
 59%|█████▉    | 1149/1939 [01:26<01:12, 10.97it/s]
 59%|█████▉    | 1151/1939 [01:27<01:40,  7.86it/s]
 59%|█████▉    | 1153/1939 [01:27<01:42,  7.70it/s]
 60%|█████▉    | 1155/1939 [01:27<01:28,  8.81it/s]
 60%|█████▉    | 1158/1939 [01:27<01:06, 11.75it/s]
 60%|█████▉    | 1160/1939 [01:27<00:59, 13.07it/s]
 60%|█████▉    | 1162/1939 [01:28<01:19,  9.75it/s]
 60%|██████    | 1164/1939 [01:28<01:13, 10.51it/s]
 60%|██████    | 1166/1939 [01:28<01:32,  8.33it/s]
 60%|██████    | 1168/1939 [01:28<01:20,  9.59it/s]
 60%|██████    | 1170/1939 [01:28<01:10, 10.93it/s]
 61%|██████    | 1175/1939 [01:28<00:42, 17.87it/s]
 61%|██████    | 1178/1939 [01:29<00:54, 14.05it/s]
 61%|██████    | 1180/1939 [01:29<01:12, 10.51it/s]
 61%|██████    | 1183/1939 [01:29<01:17,  9.71it/s]
 61%|██████    | 1185/1939 [01:30<01:16,  9.82it/s]
 61%|██████    | 1187/1939 [01:30<01:33,  8.06it/s]
 61%|██████▏   | 1189/1939 [01:30<01:23,  9.01it/s]
 61%|██████▏   | 1191/1939 [01:31<01:38,  7.61it/s]
 62%|██████▏   | 1193/1939 [01:31<01:32,  8.03it/s]
 62%|██████▏   | 1195/1939 [01:31<01:20,  9.30it/s]
 62%|██████▏   | 1197/1939 [01:31<01:19,  9.36it/s]
 62%|██████▏   | 1201/1939 [01:31<00:51, 14.26it/s]
 62%|██████▏   | 1209/1939 [01:31<00:29, 24.53it/s]
 63%|██████▎   | 1212/1939 [01:31<00:31, 23.10it/s]
 63%|██████▎   | 1217/1939 [01:32<00:39, 18.05it/s]
 63%|██████▎   | 1220/1939 [01:32<00:54, 13.21it/s]
 63%|██████▎   | 1225/1939 [01:32<00:39, 17.91it/s]
 63%|██████▎   | 1228/1939 [01:33<00:54, 13.12it/s]
 64%|██████▎   | 1235/1939 [01:33<00:35, 20.11it/s]
 64%|██████▍   | 1239/1939 [01:33<00:43, 16.10it/s]
 64%|██████▍   | 1242/1939 [01:33<00:40, 17.26it/s]
 64%|██████▍   | 1246/1939 [01:34<00:40, 17.03it/s]
 64%|██████▍   | 1249/1939 [01:34<00:38, 17.96it/s]
 65%|██████▍   | 1254/1939 [01:34<00:37, 18.09it/s]
 65%|██████▍   | 1257/1939 [01:34<00:40, 16.96it/s]
 65%|██████▌   | 1263/1939 [01:34<00:29, 23.08it/s]
 65%|██████▌   | 1269/1939 [01:35<00:22, 29.40it/s]
 66%|██████▌   | 1273/1939 [01:35<00:27, 24.23it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 319.01it/s]
 50%|█████     | 151/300 [10:37<1:02:13, 25.05s/it]

[[np.int64(0), False, 1], [np.int64(1), False, 10], [np.int64(2), False, 9], [np.int64(3), False, 5], [np.int64(4), False, 11], [np.int64(5), False, 10], [np.int64(6), False, 13], [np.int64(7), False, 9], [np.int64(8), False, 11], [np.int64(12), False, 5], [np.int64(13), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.1459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4128, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.1463, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5586, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [10:37<49:25, 20.04s/it]

tensor(13.1574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7002, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [10:37<31:02, 12.76s/it]

tensor(13.1777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9317, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9233, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [10:37<20:11,  8.41s/it]

tensor(13.2373, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9695, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0217, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [10:37<13:26,  5.68s/it]

tensor(13.2327, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0725, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [10:38<09:05,  3.89s/it]

tensor(13.2186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1017, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1484, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [10:38<06:13,  2.70s/it]

tensor(13.2022, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1451, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2051, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1435, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [10:38<04:17,  1.90s/it]

tensor(13.2048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1665, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [10:38<03:00,  1.34s/it]

tensor(13.1986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1731, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1818, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1597, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [10:38<02:07,  1.04it/s]

tensor(13.1627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1270, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [10:39<01:31,  1.43it/s]

tensor(13.1540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1267, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [10:39<01:06,  1.93it/s]

tensor(13.1459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1438, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1775, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2170, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [10:39<00:49,  2.56it/s]

tensor(13.1239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2660, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [10:39<00:37,  3.31it/s]

tensor(13.1179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2821, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [10:39<00:29,  4.17it/s]

tensor(13.1095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2934, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0992, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3072, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3140, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [10:40<00:23,  5.07it/s]

tensor(13.0853, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3397, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3453, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [10:40<00:19,  5.99it/s]

tensor(13.0799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3607, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [10:40<00:16,  6.86it/s]

tensor(13.0777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3760, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3939, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0741, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4112, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [10:40<00:14,  7.65it/s]

tensor(13.0709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4006, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4082, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [10:40<00:13,  8.30it/s]

tensor(13.0619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4493, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [10:40<00:12,  8.84it/s]

tensor(13.0579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0502, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5004, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [10:41<00:11,  9.16it/s]

tensor(13.0459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5133, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0423, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5235, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [10:41<00:11,  9.50it/s]

tensor(13.0393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5327, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [10:41<00:10,  9.74it/s]

tensor(13.0365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5420, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5475, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5534, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [10:41<00:10,  9.93it/s]

tensor(13.0255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5559, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5585, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [10:41<00:09, 10.04it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 91, 390, 157, 110, 144,  82,  75,  17, 136, 182, 172, 235,  48, 100])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:51, 17.43it/s]
  0%|          | 5/1939 [00:00<01:21, 23.67it/s]
  0%|          | 8/1939 [00:01<05:50,  5.51it/s]
  1%|          | 14/1939 [00:01<02:45, 11.66it/s]
  1%|          | 18/1939 [00:01<03:22,  9.50it/s]
  1%|          | 21/1939 [00:02<02:52, 11.14it/s]
  1%|▏         | 25/1939 [00:02<03:38,  8.74it/s]
  1%|▏         | 27/1939 [00:02<03:15,  9.76it/s]
  2%|▏         | 30/1939 [00:03<05:12,  6.11it/s]
  2%|▏         | 32/1939 [00:03<04:24,  7.22it/s]
  2%|▏         | 36/1939 [00:04<05:12,  6.09it/s]
  2%|▏         | 38/1939 [00:04<04:27,  7.10it/s]
  2%|▏         | 41/1939 [00:05<05:52,  5.39it/s]
  2%|▏         | 43/1939 [00:05<04:55,  6.42it/s]
  3%|▎         | 49/1939 [00:06<04:50,  6.50it/s]
  3%|▎         | 51/1939 [00:06<04:14,  7.41it/s]
  3%|▎         | 53/1939 [00:07<06:15,  5.02it/s]
 67%|██████▋   | 200/300 [10:54<00:09, 10.04it/s]
  3%|▎         | 58/1939 [00:08<06:23,  4.90it/s]
  3%|▎         | 59/1939 [00:08<06:00,  5.22it/s]
  3%|▎         | 65/1939 [00:08<03:10,  9.84it/s]
  3%|▎         | 67/1939 [00:09<05:33,  5.60it/s]
  4%|▍         | 73/1939 [00:10<04:23,  7.09it/s]
  4%|▍         | 76/1939 [00:10<03:39,  8.50it/s]
  4%|▍         | 78/1939 [00:11<05:22,  5.77it/s]
  4%|▍         | 80/1939 [00:12<08:01,  3.86it/s]
  4%|▍         | 82/1939 [00:12<06:34,  4.71it/s]
  4%|▍         | 84/1939 [00:13<07:04,  4.37it/s]
  4%|▍         | 86/1939 [00:13<06:53,  4.48it/s]
  4%|▍         | 87/1939 [00:13<08:00,  3.85it/s]
  5%|▍         | 89/1939 [00:14<06:02,  5.10it/s]
  5%|▍         | 94/1939 [00:15<05:52,  5.24it/s]
  5%|▍         | 96/1939 [00:15<04:54,  6.25it/s]
  5%|▌         | 100/1939 [00:15<04:07,  7.43it/s]
  5%|▌         | 103/1939 [00:15<03:14,  9.44it/s]
  5%|▌         | 105/1939 [00:15<03:03,  9.98it/s]
  6%|▌         | 107/1939 [00:15<02:43, 11.17it/s]
  6%|▌         | 112/1939 [00:16<01:45, 17.28it/s]
  6%|▌         | 115/1939 [00:16<03:46,  8.06it/s]
  6%|▌         | 118/1939 [00:17<05:19,  5.70it/s]
  6%|▌         | 120/1939 [00:18<06:59,  4.34it/s]
  6%|▋         | 122/1939 [00:18<05:45,  5.27it/s]
  6%|▋         | 125/1939 [00:18<04:17,  7.03it/s]
  7%|▋         | 128/1939 [00:19<05:57,  5.07it/s]
  7%|▋         | 130/1939 [00:19<04:55,  6.13it/s]
  7%|▋         | 132/1939 [00:20<05:14,  5.74it/s]
  7%|▋         | 134/1939 [00:20<04:20,  6.93it/s]
  7%|▋         | 136/1939 [00:20<03:39,  8.22it/s]
  7%|▋         | 138/1939 [00:21<04:41,  6.40it/s]
  7%|▋         | 141/1939 [00:21<03:30,  8.56it/s]
  7%|▋         | 145/1939 [00:21<03:40,  8.15it/s]
  8%|▊         | 147/1939 [00:22<04:12,  7.10it/s]
  8%|▊         | 149/1939 [00:22<03:33,  8.39it/s]
  8%|▊         | 151/1939 [00:22<04:14,  7.03it/s]
  8%|▊         | 153/1939 [00:23<05:41,  5.23it/s]
  8%|▊         | 155/1939 [00:23<04:34,  6.51it/s]
  8%|▊         | 157/1939 [00:23<04:50,  6.13it/s]
  8%|▊         | 158/1939 [00:24<07:45,  3.83it/s]
  8%|▊         | 160/1939 [00:25<09:27,  3.13it/s]
  8%|▊         | 162/1939 [00:25<07:05,  4.18it/s]
  8%|▊         | 163/1939 [00:26<10:05,  2.93it/s]
  8%|▊         | 164/1939 [00:27<12:01,  2.46it/s]
  9%|▊         | 166/1939 [00:27<08:13,  3.60it/s]
  9%|▉         | 171/1939 [00:27<03:53,  7.58it/s]
  9%|▉         | 177/1939 [00:27<02:13, 13.25it/s]
  9%|▉         | 183/1939 [00:27<01:30, 19.38it/s]
 10%|▉         | 187/1939 [00:27<01:57, 14.89it/s]
 10%|▉         | 192/1939 [00:28<01:29, 19.48it/s]
 10%|█         | 196/1939 [00:29<03:07,  9.31it/s]
 10%|█         | 200/1939 [00:29<02:27, 11.76it/s]
 10%|█         | 203/1939 [00:30<05:53,  4.91it/s]
 11%|█         | 206/1939 [00:32<07:50,  3.68it/s]
 11%|█         | 208/1939 [00:32<06:43,  4.29it/s]
 11%|█         | 211/1939 [00:33<06:15,  4.60it/s]
 11%|█         | 214/1939 [00:33<04:43,  6.09it/s]
 11%|█         | 216/1939 [00:34<06:31,  4.40it/s]
 11%|█         | 218/1939 [00:34<08:04,  3.55it/s]
 11%|█▏        | 220/1939 [00:35<06:35,  4.34it/s]
 11%|█▏        | 222/1939 [00:35<05:16,  5.43it/s]
 12%|█▏        | 228/1939 [00:35<03:26,  8.30it/s]
 12%|█▏        | 230/1939 [00:35<03:02,  9.37it/s]
 12%|█▏        | 233/1939 [00:36<02:55,  9.71it/s]
 12%|█▏        | 235/1939 [00:36<02:40, 10.61it/s]
 12%|█▏        | 237/1939 [00:36<03:11,  8.88it/s]
 12%|█▏        | 239/1939 [00:37<04:29,  6.30it/s]
 12%|█▏        | 240/1939 [00:37<05:32,  5.11it/s]
 12%|█▏        | 242/1939 [00:38<07:21,  3.84it/s]
 13%|█▎        | 243/1939 [00:38<08:34,  3.30it/s]
 13%|█▎        | 245/1939 [00:39<08:20,  3.39it/s]
 13%|█▎        | 247/1939 [00:39<06:21,  4.44it/s]
 13%|█▎        | 248/1939 [00:39<06:51,  4.11it/s]
 13%|█▎        | 250/1939 [00:39<04:59,  5.65it/s]
 13%|█▎        | 252/1939 [00:40<03:51,  7.28it/s]
 13%|█▎        | 257/1939 [00:40<04:36,  6.08it/s]
 13%|█▎        | 260/1939 [00:41<05:56,  4.72it/s]
 14%|█▎        | 263/1939 [00:42<06:40,  4.19it/s]
 14%|█▎        | 264/1939 [00:42<06:10,  4.52it/s]
 14%|█▎        | 266/1939 [00:43<04:56,  5.65it/s]
 14%|█▍        | 273/1939 [00:43<02:20, 11.85it/s]
 14%|█▍        | 278/1939 [00:43<01:41, 16.29it/s]
 15%|█▍        | 284/1939 [00:44<02:45, 10.01it/s]
 15%|█▍        | 287/1939 [00:45<04:01,  6.83it/s]
 15%|█▌        | 291/1939 [00:45<03:02,  9.01it/s]
 15%|█▌        | 298/1939 [00:45<01:55, 14.15it/s]
 16%|█▌        | 302/1939 [00:45<01:36, 16.96it/s]
 16%|█▌        | 306/1939 [00:45<01:30, 17.97it/s]
 16%|█▌        | 312/1939 [00:45<01:09, 23.57it/s]
 16%|█▋        | 318/1939 [00:45<00:54, 29.50it/s]
 17%|█▋        | 323/1939 [00:46<01:47, 15.06it/s]
 17%|█▋        | 327/1939 [00:47<02:47,  9.64it/s]
 17%|█▋        | 333/1939 [00:47<02:01, 13.25it/s]
 17%|█▋        | 337/1939 [00:48<03:01,  8.83it/s]
 18%|█▊        | 340/1939 [00:48<02:39, 10.03it/s]
 18%|█▊        | 343/1939 [00:49<03:44,  7.11it/s]
 18%|█▊        | 345/1939 [00:50<05:05,  5.22it/s]
 18%|█▊        | 348/1939 [00:50<03:58,  6.68it/s]
 18%|█▊        | 351/1939 [00:51<04:57,  5.34it/s]
 18%|█▊        | 353/1939 [00:52<06:26,  4.10it/s]
 18%|█▊        | 354/1939 [00:53<08:31,  3.10it/s]
 18%|█▊        | 356/1939 [00:53<06:36,  4.00it/s]
 19%|█▊        | 361/1939 [00:53<03:35,  7.33it/s]
 19%|█▉        | 364/1939 [00:54<04:46,  5.49it/s]
 19%|█▉        | 367/1939 [00:54<03:38,  7.18it/s]
 19%|█▉        | 372/1939 [00:54<02:22, 11.03it/s]
 19%|█▉        | 376/1939 [00:55<03:24,  7.63it/s]
 20%|█▉        | 379/1939 [00:55<02:46,  9.37it/s]
 20%|█▉        | 382/1939 [00:56<03:33,  7.29it/s]
 20%|█▉        | 384/1939 [00:56<04:15,  6.10it/s]
 20%|█▉        | 387/1939 [00:56<04:04,  6.36it/s]
 20%|██        | 389/1939 [00:57<04:31,  5.70it/s]
 20%|██        | 390/1939 [00:58<06:18,  4.10it/s]
 20%|██        | 392/1939 [00:58<04:59,  5.17it/s]
 20%|██        | 393/1939 [00:58<05:50,  4.41it/s]
 20%|██        | 394/1939 [00:58<05:59,  4.30it/s]
 20%|██        | 396/1939 [00:59<06:12,  4.15it/s]
 21%|██        | 398/1939 [00:59<05:57,  4.31it/s]
 21%|██        | 400/1939 [00:59<04:33,  5.64it/s]
 21%|██        | 402/1939 [01:00<03:33,  7.20it/s]
 21%|██        | 404/1939 [01:00<06:04,  4.21it/s]
 21%|██        | 405/1939 [01:01<08:52,  2.88it/s]
 21%|██        | 407/1939 [01:02<09:28,  2.69it/s]
 21%|██        | 409/1939 [01:02<06:50,  3.72it/s]
 21%|██        | 411/1939 [01:03<08:06,  3.14it/s]
 21%|██▏       | 413/1939 [01:03<06:04,  4.19it/s]
 21%|██▏       | 415/1939 [01:04<07:26,  3.41it/s]
 22%|██▏       | 418/1939 [01:04<04:53,  5.18it/s]
 22%|██▏       | 420/1939 [01:05<06:34,  3.85it/s]
 22%|██▏       | 422/1939 [01:06<07:53,  3.21it/s]
 22%|██▏       | 424/1939 [01:06<06:05,  4.15it/s]
 22%|██▏       | 426/1939 [01:07<07:30,  3.36it/s]
 22%|██▏       | 428/1939 [01:08<08:51,  2.84it/s]
 22%|██▏       | 431/1939 [01:08<05:45,  4.37it/s]
 23%|██▎       | 437/1939 [01:08<02:57,  8.45it/s]
 23%|██▎       | 443/1939 [01:08<01:53, 13.23it/s]
 23%|██▎       | 450/1939 [01:08<01:16, 19.58it/s]
 24%|██▎       | 456/1939 [01:09<01:02, 23.83it/s]
 24%|██▍       | 461/1939 [01:09<01:01, 24.05it/s]
 24%|██▍       | 465/1939 [01:09<01:04, 22.90it/s]
 24%|██▍       | 472/1939 [01:09<00:48, 30.05it/s]
 25%|██▍       | 477/1939 [01:09<00:50, 29.22it/s]
 25%|██▍       | 481/1939 [01:09<00:56, 25.98it/s]
 25%|██▌       | 488/1939 [01:10<00:44, 32.64it/s]
 25%|██▌       | 492/1939 [01:11<02:59,  8.04it/s]
 26%|██▌       | 495/1939 [01:11<02:37,  9.18it/s]
 26%|██▌       | 498/1939 [01:12<02:16, 10.56it/s]
 26%|██▌       | 503/1939 [01:12<01:38, 14.52it/s]
 26%|██▋       | 510/1939 [01:12<01:06, 21.42it/s]
 27%|██▋       | 515/1939 [01:12<01:01, 23.00it/s]
 27%|██▋       | 519/1939 [01:13<01:50, 12.89it/s]
 27%|██▋       | 522/1939 [01:14<04:18,  5.49it/s]
 27%|██▋       | 525/1939 [01:15<04:55,  4.78it/s]
 27%|██▋       | 527/1939 [01:17<06:49,  3.45it/s]
 27%|██▋       | 529/1939 [01:17<06:10,  3.81it/s]
 27%|██▋       | 531/1939 [01:17<05:46,  4.06it/s]
 27%|██▋       | 533/1939 [01:18<05:44,  4.08it/s]
 28%|██▊       | 535/1939 [01:18<04:33,  5.13it/s]
 28%|██▊       | 537/1939 [01:18<05:18,  4.40it/s]
 28%|██▊       | 539/1939 [01:19<04:19,  5.39it/s]
 28%|██▊       | 541/1939 [01:19<03:29,  6.67it/s]
 28%|██▊       | 546/1939 [01:19<03:11,  7.29it/s]
 28%|██▊       | 548/1939 [01:19<02:45,  8.42it/s]
 28%|██▊       | 551/1939 [01:20<03:19,  6.96it/s]
 29%|██▊       | 554/1939 [01:20<02:32,  9.09it/s]
 29%|██▉       | 560/1939 [01:20<01:31, 15.15it/s]
 29%|██▉       | 567/1939 [01:20<01:00, 22.84it/s]
 29%|██▉       | 571/1939 [01:21<00:57, 23.62it/s]
 30%|██▉       | 575/1939 [01:23<03:46,  6.01it/s]
 30%|██▉       | 578/1939 [01:23<03:09,  7.19it/s]
 30%|██▉       | 581/1939 [01:24<04:06,  5.50it/s]
 30%|███       | 584/1939 [01:24<04:40,  4.84it/s]
 30%|███       | 586/1939 [01:25<05:15,  4.29it/s]
 30%|███       | 588/1939 [01:25<04:21,  5.17it/s]
 31%|███       | 593/1939 [01:25<02:38,  8.50it/s]
 31%|███       | 598/1939 [01:25<01:47, 12.50it/s]
 31%|███       | 602/1939 [01:27<03:11,  7.00it/s]
 31%|███       | 605/1939 [01:27<02:36,  8.50it/s]
 31%|███▏      | 608/1939 [01:27<03:06,  7.13it/s]
 31%|███▏      | 610/1939 [01:28<04:20,  5.11it/s]
 32%|███▏      | 612/1939 [01:30<07:26,  2.97it/s]
 32%|███▏      | 614/1939 [01:31<07:57,  2.77it/s]
 32%|███▏      | 615/1939 [01:32<09:29,  2.32it/s]
 32%|███▏      | 617/1939 [01:32<07:03,  3.12it/s]
 32%|███▏      | 618/1939 [01:32<08:58,  2.45it/s]
 32%|███▏      | 620/1939 [01:33<09:07,  2.41it/s]
 32%|███▏      | 622/1939 [01:34<09:06,  2.41it/s]
 32%|███▏      | 625/1939 [01:34<05:45,  3.80it/s]
 32%|███▏      | 629/1939 [01:35<05:14,  4.16it/s]
 32%|███▏      | 630/1939 [01:36<07:06,  3.07it/s]
 33%|███▎      | 632/1939 [01:37<07:52,  2.77it/s]
 33%|███▎      | 635/1939 [01:37<05:13,  4.16it/s]
 33%|███▎      | 637/1939 [01:39<08:23,  2.59it/s]
 33%|███▎      | 639/1939 [01:39<06:25,  3.38it/s]
 33%|███▎      | 641/1939 [01:40<09:38,  2.24it/s]
 33%|███▎      | 643/1939 [01:41<09:29,  2.28it/s]
 33%|███▎      | 646/1939 [01:41<06:09,  3.50it/s]
 33%|███▎      | 649/1939 [01:42<06:12,  3.46it/s]
 34%|███▎      | 651/1939 [01:43<07:06,  3.02it/s]
 34%|███▎      | 654/1939 [01:44<06:55,  3.09it/s]
 34%|███▍      | 656/1939 [01:45<07:32,  2.84it/s]
 34%|███▍      | 658/1939 [01:46<07:55,  2.69it/s]
 34%|███▍      | 659/1939 [01:46<08:18,  2.57it/s]
 34%|███▍      | 662/1939 [01:46<05:16,  4.04it/s]
 34%|███▍      | 665/1939 [01:47<04:14,  5.01it/s]
 34%|███▍      | 666/1939 [01:47<04:31,  4.68it/s]
 34%|███▍      | 668/1939 [01:48<05:06,  4.15it/s]
 35%|███▍      | 670/1939 [01:48<03:55,  5.39it/s]
 35%|███▍      | 672/1939 [01:48<04:53,  4.31it/s]
 35%|███▍      | 674/1939 [01:49<03:49,  5.51it/s]
 35%|███▍      | 676/1939 [01:49<03:55,  5.37it/s]
 35%|███▌      | 679/1939 [01:49<02:44,  7.66it/s]
 35%|███▌      | 681/1939 [01:50<03:36,  5.80it/s]
 35%|███▌      | 683/1939 [01:50<03:28,  6.03it/s]
 35%|███▌      | 685/1939 [01:50<02:55,  7.13it/s]
 35%|███▌      | 687/1939 [01:51<04:18,  4.85it/s]
 35%|███▌      | 688/1939 [01:51<03:56,  5.28it/s]
 36%|███▌      | 689/1939 [01:52<06:39,  3.13it/s]
 36%|███▌      | 692/1939 [01:53<06:16,  3.31it/s]
 36%|███▌      | 695/1939 [01:53<04:06,  5.05it/s]
 36%|███▌      | 699/1939 [01:54<04:14,  4.88it/s]
 36%|███▌      | 701/1939 [01:54<03:29,  5.90it/s]
 36%|███▋      | 706/1939 [01:54<02:05,  9.83it/s]
 37%|███▋      | 710/1939 [01:54<01:36, 12.68it/s]
 37%|███▋      | 713/1939 [01:54<01:21, 14.98it/s]
 37%|███▋      | 719/1939 [01:54<00:55, 21.86it/s]
 37%|███▋      | 723/1939 [01:55<01:58, 10.30it/s]
 37%|███▋      | 726/1939 [01:55<01:42, 11.85it/s]
 38%|███▊      | 730/1939 [01:56<02:33,  7.88it/s]
 38%|███▊      | 732/1939 [01:57<03:52,  5.19it/s]
 38%|███▊      | 734/1939 [01:58<04:54,  4.09it/s]
 38%|███▊      | 737/1939 [01:58<03:36,  5.55it/s]
 38%|███▊      | 739/1939 [01:58<03:36,  5.55it/s]
 38%|███▊      | 741/1939 [01:59<03:02,  6.57it/s]
 38%|███▊      | 743/1939 [01:59<03:54,  5.09it/s]
 38%|███▊      | 745/1939 [01:59<03:09,  6.29it/s]
 39%|███▊      | 750/1939 [01:59<01:51, 10.66it/s]
 39%|███▉      | 753/1939 [02:00<01:31, 12.91it/s]
 39%|███▉      | 756/1939 [02:00<02:26,  8.07it/s]
 39%|███▉      | 758/1939 [02:00<02:08,  9.19it/s]
 39%|███▉      | 760/1939 [02:01<02:26,  8.05it/s]
 39%|███▉      | 763/1939 [02:01<02:29,  7.85it/s]
 39%|███▉      | 765/1939 [02:01<02:13,  8.81it/s]
 40%|███▉      | 767/1939 [02:03<05:23,  3.63it/s]
 40%|███▉      | 769/1939 [02:04<06:17,  3.10it/s]
 40%|███▉      | 771/1939 [02:04<04:52,  3.99it/s]
 40%|███▉      | 772/1939 [02:05<06:39,  2.92it/s]
 40%|███▉      | 774/1939 [02:05<04:53,  3.97it/s]
 40%|████      | 776/1939 [02:05<05:49,  3.33it/s]
 40%|████      | 777/1939 [02:06<07:49,  2.48it/s]
 40%|████      | 779/1939 [02:07<06:36,  2.93it/s]
 40%|████      | 782/1939 [02:07<04:07,  4.68it/s]
 40%|████      | 784/1939 [02:08<05:21,  3.60it/s]
 41%|████      | 787/1939 [02:09<05:35,  3.43it/s]
 41%|████      | 789/1939 [02:10<06:20,  3.02it/s]
 41%|████      | 791/1939 [02:10<04:52,  3.92it/s]
 41%|████      | 797/1939 [02:10<02:25,  7.85it/s]
 41%|████▏     | 800/1939 [02:11<03:24,  5.56it/s]
 41%|████▏     | 804/1939 [02:12<03:37,  5.22it/s]
 42%|████▏     | 806/1939 [02:13<06:06,  3.09it/s]
 42%|████▏     | 808/1939 [02:14<05:05,  3.70it/s]
 42%|████▏     | 810/1939 [02:14<05:04,  3.71it/s]
 42%|████▏     | 812/1939 [02:14<04:49,  3.90it/s]
 42%|████▏     | 813/1939 [02:15<05:18,  3.54it/s]
 42%|████▏     | 815/1939 [02:15<03:57,  4.73it/s]
 42%|████▏     | 816/1939 [02:15<04:04,  4.59it/s]
 42%|████▏     | 817/1939 [02:15<03:58,  4.70it/s]
 42%|████▏     | 818/1939 [02:16<05:29,  3.40it/s]
 42%|████▏     | 819/1939 [02:16<04:50,  3.85it/s]
 42%|████▏     | 820/1939 [02:17<05:22,  3.47it/s]
 42%|████▏     | 821/1939 [02:17<06:10,  3.02it/s]
 42%|████▏     | 823/1939 [02:17<05:22,  3.46it/s]
 43%|████▎     | 825/1939 [02:18<03:40,  5.05it/s]
 43%|████▎     | 829/1939 [02:18<03:51,  4.80it/s]
 43%|████▎     | 831/1939 [02:19<03:04,  5.99it/s]
 43%|████▎     | 837/1939 [02:19<01:34, 11.60it/s]
 43%|████▎     | 842/1939 [02:19<01:07, 16.19it/s]
 44%|████▎     | 847/1939 [02:19<00:52, 20.99it/s]
 44%|████▍     | 853/1939 [02:19<00:41, 25.86it/s]
 44%|████▍     | 857/1939 [02:20<01:33, 11.57it/s]
 44%|████▍     | 860/1939 [02:20<01:22, 13.13it/s]
 45%|████▍     | 865/1939 [02:20<01:01, 17.33it/s]
 45%|████▍     | 869/1939 [02:20<00:53, 20.12it/s]
 45%|████▌     | 875/1939 [02:20<00:39, 26.81it/s]
 45%|████▌     | 882/1939 [02:20<00:30, 34.40it/s]
 46%|████▌     | 889/1939 [02:21<00:27, 37.79it/s]
 46%|████▌     | 894/1939 [02:21<00:56, 18.56it/s]
 46%|████▋     | 898/1939 [02:22<01:24, 12.36it/s]
 46%|████▋     | 901/1939 [02:23<02:12,  7.84it/s]
 47%|████▋     | 903/1939 [02:24<03:05,  5.59it/s]
 47%|████▋     | 906/1939 [02:24<02:26,  7.05it/s]
 47%|████▋     | 910/1939 [02:25<02:50,  6.05it/s]
 47%|████▋     | 913/1939 [02:25<02:15,  7.56it/s]
 47%|████▋     | 918/1939 [02:25<02:06,  8.08it/s]
 47%|████▋     | 920/1939 [02:25<01:52,  9.04it/s]
 48%|████▊     | 926/1939 [02:26<01:11, 14.17it/s]
 48%|████▊     | 929/1939 [02:27<02:07,  7.95it/s]
 48%|████▊     | 932/1939 [02:28<03:47,  4.42it/s]
 48%|████▊     | 935/1939 [02:28<03:01,  5.53it/s]
 48%|████▊     | 938/1939 [02:29<03:31,  4.72it/s]
 48%|████▊     | 940/1939 [02:29<02:58,  5.60it/s]
 49%|████▊     | 944/1939 [02:29<02:01,  8.16it/s]
 49%|████▉     | 948/1939 [02:29<01:28, 11.20it/s]
 49%|████▉     | 951/1939 [02:30<01:15, 13.14it/s]
 49%|████▉     | 954/1939 [02:30<01:05, 15.09it/s]
 49%|████▉     | 957/1939 [02:30<01:03, 15.57it/s]
 50%|████▉     | 960/1939 [02:30<00:58, 16.66it/s]
 50%|████▉     | 967/1939 [02:30<00:40, 24.22it/s]
 50%|█████     | 970/1939 [02:32<02:44,  5.88it/s]
 50%|█████     | 973/1939 [02:34<04:26,  3.63it/s]
 50%|█████     | 976/1939 [02:34<03:25,  4.69it/s]
 50%|█████     | 978/1939 [02:35<04:14,  3.78it/s]
 51%|█████     | 981/1939 [02:35<03:09,  5.07it/s]
 51%|█████     | 983/1939 [02:35<03:02,  5.25it/s]
 51%|█████     | 985/1939 [02:36<02:53,  5.48it/s]
 51%|█████     | 988/1939 [02:36<02:05,  7.56it/s]
 51%|█████▏    | 995/1939 [02:36<01:06, 14.16it/s]
 52%|█████▏    | 999/1939 [02:37<01:57,  7.99it/s]
 52%|█████▏    | 1002/1939 [02:37<02:19,  6.71it/s]
 52%|█████▏    | 1004/1939 [02:38<02:02,  7.65it/s]
 52%|█████▏    | 1006/1939 [02:38<02:20,  6.66it/s]
 52%|█████▏    | 1008/1939 [02:38<02:27,  6.32it/s]
 52%|█████▏    | 1010/1939 [02:39<03:45,  4.12it/s]
 52%|█████▏    | 1011/1939 [02:40<04:08,  3.73it/s]
 52%|█████▏    | 1012/1939 [02:40<04:51,  3.17it/s]
 52%|█████▏    | 1013/1939 [02:41<05:45,  2.68it/s]
 52%|█████▏    | 1014/1939 [02:42<06:32,  2.35it/s]
 52%|█████▏    | 1015/1939 [02:42<06:44,  2.28it/s]
 52%|█████▏    | 1016/1939 [02:42<06:25,  2.40it/s]
 53%|█████▎    | 1018/1939 [02:42<04:05,  3.76it/s]
 53%|█████▎    | 1019/1939 [02:43<04:20,  3.53it/s]
 53%|█████▎    | 1021/1939 [02:43<03:03,  5.01it/s]
 53%|█████▎    | 1022/1939 [02:44<05:01,  3.04it/s]
 53%|█████▎    | 1024/1939 [02:44<03:24,  4.47it/s]
 53%|█████▎    | 1027/1939 [02:45<03:46,  4.03it/s]
 53%|█████▎    | 1029/1939 [02:45<02:52,  5.28it/s]
 53%|█████▎    | 1035/1939 [02:45<01:23, 10.79it/s]
 54%|█████▎    | 1041/1939 [02:45<00:55, 16.29it/s]
 54%|█████▍    | 1045/1939 [02:46<01:33,  9.54it/s]
 54%|█████▍    | 1048/1939 [02:46<01:52,  7.93it/s]
 54%|█████▍    | 1050/1939 [02:47<01:44,  8.50it/s]
 54%|█████▍    | 1052/1939 [02:48<02:48,  5.28it/s]
 54%|█████▍    | 1054/1939 [02:48<03:26,  4.29it/s]
 54%|█████▍    | 1055/1939 [02:48<03:10,  4.65it/s]
 54%|█████▍    | 1056/1939 [02:49<04:37,  3.18it/s]
 55%|█████▍    | 1058/1939 [02:49<03:25,  4.29it/s]
 55%|█████▍    | 1059/1939 [02:50<05:00,  2.93it/s]
 55%|█████▍    | 1060/1939 [02:50<04:57,  2.95it/s]
 55%|█████▍    | 1062/1939 [02:51<03:25,  4.27it/s]
 55%|█████▍    | 1064/1939 [02:51<02:28,  5.88it/s]
 55%|█████▌    | 1068/1939 [02:52<02:50,  5.12it/s]
 55%|█████▌    | 1071/1939 [02:52<02:01,  7.13it/s]
 55%|█████▌    | 1073/1939 [02:53<03:05,  4.66it/s]
 55%|█████▌    | 1076/1939 [02:53<02:12,  6.53it/s]
 56%|█████▌    | 1080/1939 [02:54<02:35,  5.53it/s]
 56%|█████▌    | 1082/1939 [02:54<02:10,  6.56it/s]
 56%|█████▌    | 1085/1939 [02:55<02:48,  5.07it/s]
 56%|█████▌    | 1087/1939 [02:55<02:20,  6.05it/s]
 56%|█████▌    | 1089/1939 [02:55<03:13,  4.40it/s]
 56%|█████▋    | 1091/1939 [02:56<04:06,  3.44it/s]
 56%|█████▋    | 1092/1939 [02:57<05:10,  2.73it/s]
 56%|█████▋    | 1094/1939 [02:58<05:22,  2.62it/s]
 57%|█████▋    | 1096/1939 [02:58<03:58,  3.54it/s]
 57%|█████▋    | 1102/1939 [02:59<02:54,  4.79it/s]
 57%|█████▋    | 1104/1939 [03:00<03:37,  3.85it/s]
 57%|█████▋    | 1105/1939 [03:00<03:19,  4.18it/s]
 57%|█████▋    | 1108/1939 [03:00<02:17,  6.02it/s]
 57%|█████▋    | 1113/1939 [03:00<01:22, 10.05it/s]
 58%|█████▊    | 1116/1939 [03:01<01:50,  7.48it/s]
 58%|█████▊    | 1118/1939 [03:01<01:37,  8.45it/s]
 58%|█████▊    | 1121/1939 [03:01<01:42,  7.98it/s]
 58%|█████▊    | 1123/1939 [03:02<01:33,  8.75it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 341.50it/s]
 67%|██████▋   | 201/300 [15:53<1:30:54, 55.10s/it]

[[np.int64(0), False, 2], [np.int64(1), False, 9], [np.int64(2), False, 11], [np.int64(3), False, 8], [np.int64(4), False, 8], [np.int64(5), False, 8], [np.int64(6), False, 10], [np.int64(7), False, 12], [np.int64(11), False, 1], [np.int64(12), False, 8], [np.int64(13), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.0186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5013, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.0188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6446, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [15:53<55:18, 34.22s/it]

tensor(13.0228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8795, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1754, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0433, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4091, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [15:54<33:07, 20.92s/it]

tensor(13.0515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4746, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [15:54<20:53, 13.48s/it]

tensor(13.0556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4359, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0393, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3517, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0518, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0392, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3155, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [15:54<13:34,  8.95s/it]

tensor(13.0466, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3725, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0417, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0379, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4710, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [15:54<08:59,  6.07s/it]

tensor(13.0383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5421, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [15:54<06:02,  4.17s/it]

tensor(13.0339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5537, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5547, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [15:55<04:06,  2.90s/it]

tensor(13.0153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5581, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5763, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [15:55<02:48,  2.03s/it]

tensor(13.0199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5999, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [15:55<01:56,  1.44s/it]

tensor(13.0209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6272, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0174, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6466, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [15:55<01:21,  1.03s/it]

tensor(13.0112, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6682, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6496, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0002, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6438, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [15:56<00:41,  1.81it/s]

tensor(12.9975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6461, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6452, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6528, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [15:56<00:30,  2.42it/s]

tensor(12.9884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6517, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6495, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6526, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [15:56<00:17,  4.00it/s]

tensor(12.9761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6666, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0325, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [15:56<00:13,  4.93it/s]

tensor(12.9724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1312, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2981, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4598, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [15:57<00:09,  6.80it/s]

tensor(12.9814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3270, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0430, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5023, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0486, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4938, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [15:57<00:07,  7.64it/s]

tensor(12.9830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0536, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5234, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0575, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5595, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9894, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0599, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5822, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [15:57<00:06,  8.95it/s]

tensor(12.9949, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0616, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6074, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9953, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0621, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6308, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0617, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6392, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [15:57<00:05,  9.41it/s]

tensor(12.9834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0605, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6287, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0587, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6411, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0566, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6516, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [15:58<00:05, 10.06it/s]

tensor(12.9790, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0542, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6587, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0516, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6748, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0487, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6826, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([104, 205, 176, 198,  95,  46,  55,  71,  83, 177, 171, 116, 358,  84])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 4/1939 [00:00<00:50, 38.27it/s]
  1%|          | 10/1939 [00:00<00:40, 47.64it/s]
  1%|          | 16/1939 [00:00<00:36, 52.35it/s]
  1%|          | 23/1939 [00:00<00:33, 57.76it/s]
  2%|▏         | 30/1939 [00:00<00:32, 58.74it/s]
  2%|▏         | 37/1939 [00:00<00:31, 61.17it/s]
  2%|▏         | 44/1939 [00:01<01:28, 21.30it/s]
  3%|▎         | 49/1939 [00:01<02:01, 15.59it/s]
  3%|▎         | 53/1939 [00:02<02:25, 12.93it/s]
  3%|▎         | 56/1939 [00:02<02:18, 13.61it/s]
  3%|▎         | 59/1939 [00:03<03:39,  8.57it/s]
  3%|▎         | 64/1939 [00:03<02:37, 11.90it/s]
  3%|▎         | 67/1939 [00:03<02:51, 10.92it/s]
  4%|▎         | 70/1939 [00:04<02:32, 12.24it/s]
  4%|▍         | 73/1939 [00:04<02:42, 11.48it/s]
  4%|▍         | 75/1939 [00:04<02:33, 12.15it/s]
  4%|▍         | 78/1939 [00:04<03:12,  9.66it/s]
  4%|▍         | 80/1939 [00:05<04:28,  6.92it/s]
  4%|▍         | 82/1939 [00:06<05:20,  5.80it/s]
  4%|▍         | 84/1939 [00:06<04:30,  6.86it/s]
  4%|▍         | 86/1939 [00:06<04:19,  7.13it/s]
  4%|▍         | 87/1939 [00:06<05:01,  6.15it/s]
  5%|▍         | 89/1939 [00:06<04:05,  7.52it/s]
  5%|▍         | 92/1939 [00:06<03:01, 10.16it/s]
  5%|▍         | 94/1939 [00:07<04:29,  6.84it/s]
  5%|▍         | 96/1939 [00:07<03:49,  8.04it/s]
  5%|▌         | 98/1939 [00:07<03:11,  9.61it/s]
  5%|▌         | 100/1939 [00:08<05:23,  5.68it/s]
  5%|▌         | 102/1939 [00:08<04:17,  7.12it/s]
  5%|▌         | 105/1939 [00:09<04:53,  6.26it/s]
  6%|▌         | 107/1939 [00:09<06:01,  5.07it/s]
  6%|▌         | 110/1939 [00:09<04:14,  7.18it/s]
  6%|▌         | 115/1939 [00:10<04:00,  7.57it/s]
  6%|▌         | 118/1939 [00:11<04:37,  6.55it/s]
  6%|▌         | 120/1939 [00:11<05:30,  5.51it/s]
  6%|▋         | 122/1939 [00:11<04:38,  6.52it/s]
  7%|▋         | 128/1939 [00:11<02:33, 11.77it/s]
  7%|▋         | 132/1939 [00:12<03:06,  9.70it/s]
  7%|▋         | 135/1939 [00:12<02:38, 11.36it/s]
  7%|▋         | 138/1939 [00:13<03:41,  8.13it/s]
 83%|████████▎ | 249/300 [16:14<00:05, 10.06it/s]]
  7%|▋         | 145/1939 [00:13<03:29,  8.56it/s]
  8%|▊         | 147/1939 [00:14<04:27,  6.70it/s]
  8%|▊         | 150/1939 [00:14<03:25,  8.72it/s]
  8%|▊         | 152/1939 [00:15<04:32,  6.56it/s]
  8%|▊         | 154/1939 [00:15<05:33,  5.35it/s]
  8%|▊         | 158/1939 [00:16<05:10,  5.74it/s]
  8%|▊         | 160/1939 [00:17<06:10,  4.80it/s]
  8%|▊         | 161/1939 [00:17<07:30,  3.95it/s]
  8%|▊         | 163/1939 [00:17<05:52,  5.04it/s]
  8%|▊         | 164/1939 [00:18<07:32,  3.93it/s]
  9%|▊         | 168/1939 [00:18<04:13,  6.98it/s]
  9%|▉         | 175/1939 [00:18<02:08, 13.69it/s]
  9%|▉         | 182/1939 [00:18<01:22, 21.19it/s]
 10%|▉         | 187/1939 [00:18<01:15, 23.24it/s]
 10%|▉         | 192/1939 [00:18<01:03, 27.52it/s]
 10%|█         | 197/1939 [00:18<00:55, 31.67it/s]
 10%|█         | 202/1939 [00:19<01:15, 22.90it/s]
 11%|█         | 206/1939 [00:20<02:40, 10.76it/s]
 11%|█         | 209/1939 [00:20<02:22, 12.13it/s]
 11%|█         | 213/1939 [00:20<01:56, 14.77it/s]
 11%|█         | 216/1939 [00:20<02:22, 12.07it/s]
 11%|█▏        | 219/1939 [00:20<02:01, 14.16it/s]
 12%|█▏        | 223/1939 [00:21<01:36, 17.87it/s]
 12%|█▏        | 226/1939 [00:21<01:26, 19.89it/s]
 12%|█▏        | 229/1939 [00:21<02:08, 13.28it/s]
 12%|█▏        | 232/1939 [00:22<03:17,  8.64it/s]
 12%|█▏        | 234/1939 [00:22<04:16,  6.65it/s]
 12%|█▏        | 236/1939 [00:23<05:17,  5.37it/s]
 12%|█▏        | 237/1939 [00:23<04:57,  5.72it/s]
 12%|█▏        | 239/1939 [00:24<05:38,  5.03it/s]
 12%|█▏        | 240/1939 [00:24<07:24,  3.82it/s]
 12%|█▏        | 242/1939 [00:25<07:35,  3.72it/s]
 13%|█▎        | 243/1939 [00:25<09:07,  3.10it/s]
 13%|█▎        | 245/1939 [00:26<08:56,  3.16it/s]
 13%|█▎        | 246/1939 [00:26<08:38,  3.26it/s]
 13%|█▎        | 248/1939 [00:26<06:47,  4.15it/s]
 13%|█▎        | 250/1939 [00:27<05:05,  5.52it/s]
 13%|█▎        | 252/1939 [00:27<03:59,  7.04it/s]
 13%|█▎        | 258/1939 [00:27<01:56, 14.38it/s]
 13%|█▎        | 261/1939 [00:27<03:12,  8.70it/s]
 14%|█▎        | 263/1939 [00:28<04:06,  6.80it/s]
 14%|█▎        | 266/1939 [00:28<03:05,  9.02it/s]
 14%|█▍        | 273/1939 [00:28<01:43, 16.17it/s]
 14%|█▍        | 278/1939 [00:28<01:20, 20.71it/s]
 15%|█▍        | 282/1939 [00:29<02:05, 13.24it/s]
 15%|█▍        | 285/1939 [00:30<03:58,  6.95it/s]
 15%|█▍        | 288/1939 [00:30<03:15,  8.43it/s]
 15%|█▌        | 292/1939 [00:30<02:27, 11.20it/s]
 15%|█▌        | 295/1939 [00:31<03:20,  8.19it/s]
 15%|█▌        | 297/1939 [00:31<04:07,  6.63it/s]
 15%|█▌        | 300/1939 [00:31<03:11,  8.55it/s]
 16%|█▌        | 304/1939 [00:32<02:18, 11.85it/s]
 16%|█▌        | 310/1939 [00:32<01:30, 18.07it/s]
 16%|█▌        | 315/1939 [00:32<02:06, 12.80it/s]
 16%|█▋        | 318/1939 [00:32<01:56, 13.95it/s]
 17%|█▋        | 321/1939 [00:33<02:39, 10.13it/s]
 17%|█▋        | 323/1939 [00:34<03:40,  7.32it/s]
 17%|█▋        | 326/1939 [00:34<02:54,  9.22it/s]
 17%|█▋        | 331/1939 [00:34<01:58, 13.63it/s]
 17%|█▋        | 337/1939 [00:34<01:21, 19.59it/s]
 18%|█▊        | 341/1939 [00:34<01:15, 21.14it/s]
 18%|█▊        | 347/1939 [00:34<00:58, 27.37it/s]
 18%|█▊        | 351/1939 [00:35<01:24, 18.74it/s]
 18%|█▊        | 354/1939 [00:35<02:21, 11.22it/s]
 18%|█▊        | 357/1939 [00:35<02:10, 12.13it/s]
 19%|█▊        | 360/1939 [00:36<02:55,  9.01it/s]
 19%|█▊        | 363/1939 [00:37<03:28,  7.56it/s]
 19%|█▉        | 366/1939 [00:37<02:48,  9.35it/s]
 19%|█▉        | 371/1939 [00:37<01:54, 13.66it/s]
 19%|█▉        | 376/1939 [00:37<02:17, 11.35it/s]
 20%|█▉        | 379/1939 [00:38<01:58, 13.21it/s]
 20%|█▉        | 382/1939 [00:38<02:13, 11.65it/s]
 20%|█▉        | 384/1939 [00:38<03:05,  8.38it/s]
 20%|█▉        | 387/1939 [00:39<03:34,  7.22it/s]
 20%|██        | 389/1939 [00:39<04:00,  6.46it/s]
 20%|██        | 390/1939 [00:40<04:12,  6.14it/s]
 20%|██        | 391/1939 [00:40<05:33,  4.64it/s]
 20%|██        | 393/1939 [00:40<05:26,  4.73it/s]
 20%|██        | 394/1939 [00:41<05:48,  4.44it/s]
 20%|██        | 396/1939 [00:41<05:59,  4.30it/s]
 21%|██        | 398/1939 [00:42<06:08,  4.18it/s]
 21%|██        | 400/1939 [00:42<04:42,  5.46it/s]
 21%|██        | 405/1939 [00:42<03:46,  6.78it/s]
 21%|██        | 407/1939 [00:43<04:30,  5.66it/s]
 21%|██        | 410/1939 [00:43<03:21,  7.60it/s]
 21%|██        | 412/1939 [00:44<04:17,  5.94it/s]
 21%|██▏       | 415/1939 [00:44<04:32,  5.60it/s]
 22%|██▏       | 417/1939 [00:45<05:22,  4.72it/s]
 22%|██▏       | 419/1939 [00:45<05:47,  4.38it/s]
 22%|██▏       | 422/1939 [00:46<05:37,  4.50it/s]
 22%|██▏       | 424/1939 [00:46<04:40,  5.40it/s]
 22%|██▏       | 426/1939 [00:47<05:13,  4.83it/s]
 22%|██▏       | 428/1939 [00:47<05:47,  4.35it/s]
 22%|██▏       | 430/1939 [00:47<04:34,  5.49it/s]
 22%|██▏       | 436/1939 [00:48<02:20, 10.72it/s]
 23%|██▎       | 441/1939 [00:48<01:37, 15.33it/s]
 23%|██▎       | 445/1939 [00:48<01:19, 18.72it/s]
 23%|██▎       | 449/1939 [00:48<01:10, 20.99it/s]
 24%|██▎       | 456/1939 [00:48<00:50, 29.43it/s]
 24%|██▍       | 462/1939 [00:48<00:41, 35.65it/s]
 24%|██▍       | 468/1939 [00:48<00:36, 39.80it/s]
 24%|██▍       | 473/1939 [00:48<00:39, 37.58it/s]
 25%|██▍       | 479/1939 [00:49<00:35, 41.03it/s]
 25%|██▍       | 484/1939 [00:49<00:33, 43.00it/s]
 25%|██▌       | 489/1939 [00:49<01:10, 20.57it/s]
 25%|██▌       | 493/1939 [00:50<02:00, 12.04it/s]
 26%|██▌       | 496/1939 [00:50<01:50, 13.04it/s]
 26%|██▌       | 501/1939 [00:50<01:23, 17.15it/s]
 26%|██▌       | 507/1939 [00:50<01:02, 22.75it/s]
 26%|██▋       | 511/1939 [00:51<01:37, 14.58it/s]
 27%|██▋       | 514/1939 [00:51<01:34, 15.02it/s]
 27%|██▋       | 518/1939 [00:51<01:18, 18.01it/s]
 27%|██▋       | 523/1939 [00:51<01:02, 22.66it/s]
 27%|██▋       | 529/1939 [00:51<00:47, 29.39it/s]
 28%|██▊       | 535/1939 [00:52<00:41, 34.16it/s]
 28%|██▊       | 540/1939 [00:52<01:23, 16.74it/s]
 28%|██▊       | 546/1939 [00:53<01:44, 13.33it/s]
 28%|██▊       | 549/1939 [00:53<01:37, 14.26it/s]
 28%|██▊       | 552/1939 [00:54<02:13, 10.35it/s]
 29%|██▊       | 554/1939 [00:54<02:04, 11.15it/s]
 29%|██▉       | 558/1939 [00:54<01:34, 14.57it/s]
 29%|██▉       | 563/1939 [00:54<01:12, 18.86it/s]
 29%|██▉       | 566/1939 [00:54<01:13, 18.66it/s]
 29%|██▉       | 571/1939 [00:54<00:58, 23.28it/s]
 30%|██▉       | 575/1939 [00:55<02:22,  9.54it/s]
 30%|██▉       | 578/1939 [00:55<02:00, 11.25it/s]
 30%|██▉       | 581/1939 [00:56<02:37,  8.61it/s]
 30%|███       | 583/1939 [00:56<03:09,  7.15it/s]
 30%|███       | 585/1939 [00:57<03:44,  6.03it/s]
 30%|███       | 587/1939 [00:57<04:07,  5.47it/s]
 30%|███       | 591/1939 [00:58<02:43,  8.25it/s]
 31%|███       | 596/1939 [00:58<02:43,  8.22it/s]
 31%|███       | 599/1939 [00:59<03:16,  6.80it/s]
 31%|███       | 601/1939 [01:00<04:54,  4.54it/s]
 31%|███       | 604/1939 [01:00<03:47,  5.86it/s]
 31%|███▏      | 607/1939 [01:01<03:57,  5.61it/s]
 31%|███▏      | 609/1939 [01:01<04:21,  5.08it/s]
 32%|███▏      | 611/1939 [01:02<04:26,  4.98it/s]
 32%|███▏      | 612/1939 [01:02<05:29,  4.03it/s]
 32%|███▏      | 614/1939 [01:03<05:49,  3.80it/s]
 32%|███▏      | 615/1939 [01:03<06:49,  3.23it/s]
 32%|███▏      | 616/1939 [01:03<06:33,  3.36it/s]
 32%|███▏      | 617/1939 [01:04<05:41,  3.88it/s]
 32%|███▏      | 618/1939 [01:04<07:17,  3.02it/s]
 32%|███▏      | 620/1939 [01:05<06:48,  3.23it/s]
 32%|███▏      | 622/1939 [01:05<04:56,  4.44it/s]
 32%|███▏      | 625/1939 [01:05<03:06,  7.06it/s]
 32%|███▏      | 629/1939 [01:06<03:10,  6.89it/s]
 33%|███▎      | 631/1939 [01:06<03:42,  5.88it/s]
 33%|███▎      | 632/1939 [01:06<04:12,  5.17it/s]
 33%|███▎      | 634/1939 [01:06<03:18,  6.56it/s]
 33%|███▎      | 636/1939 [01:07<03:29,  6.22it/s]
 33%|███▎      | 637/1939 [01:07<03:47,  5.72it/s]
 33%|███▎      | 639/1939 [01:07<02:54,  7.44it/s]
 33%|███▎      | 641/1939 [01:08<04:21,  4.96it/s]
 33%|███▎      | 643/1939 [01:08<04:37,  4.66it/s]
 33%|███▎      | 646/1939 [01:08<03:07,  6.91it/s]
 33%|███▎      | 649/1939 [01:09<03:24,  6.31it/s]
 34%|███▎      | 652/1939 [01:09<02:33,  8.39it/s]
 34%|███▎      | 654/1939 [01:10<03:20,  6.41it/s]
 34%|███▍      | 656/1939 [01:10<03:58,  5.38it/s]
 34%|███▍      | 658/1939 [01:11<04:34,  4.67it/s]
 34%|███▍      | 660/1939 [01:11<03:36,  5.90it/s]
 34%|███▍      | 663/1939 [01:11<02:38,  8.08it/s]
 34%|███▍      | 665/1939 [01:12<03:20,  6.36it/s]
 34%|███▍      | 667/1939 [01:12<03:59,  5.32it/s]
 35%|███▍      | 669/1939 [01:12<03:11,  6.65it/s]
 35%|███▍      | 672/1939 [01:13<03:26,  6.15it/s]
 35%|███▍      | 675/1939 [01:13<02:31,  8.36it/s]
 35%|███▍      | 677/1939 [01:13<02:58,  7.09it/s]
 35%|███▌      | 679/1939 [01:13<02:30,  8.35it/s]
 35%|███▌      | 681/1939 [01:14<03:28,  6.04it/s]
 35%|███▌      | 683/1939 [01:14<03:41,  5.67it/s]
 35%|███▌      | 685/1939 [01:15<03:06,  6.71it/s]
 35%|███▌      | 687/1939 [01:15<03:28,  6.01it/s]
 36%|███▌      | 689/1939 [01:15<03:47,  5.50it/s]
 36%|███▌      | 691/1939 [01:15<02:59,  6.94it/s]
 36%|███▌      | 693/1939 [01:16<02:43,  7.60it/s]
 36%|███▌      | 696/1939 [01:16<01:56, 10.67it/s]
 36%|███▌      | 701/1939 [01:16<01:13, 16.89it/s]
 37%|███▋      | 708/1939 [01:16<00:46, 26.36it/s]
 37%|███▋      | 715/1939 [01:16<00:34, 35.22it/s]
 37%|███▋      | 720/1939 [01:16<00:31, 38.52it/s]
 37%|███▋      | 727/1939 [01:16<00:26, 45.22it/s]
 38%|███▊      | 733/1939 [01:18<01:52, 10.67it/s]
 38%|███▊      | 737/1939 [01:18<01:36, 12.45it/s]
 38%|███▊      | 741/1939 [01:18<01:48, 11.05it/s]
 38%|███▊      | 744/1939 [01:19<02:18,  8.61it/s]
 39%|███▊      | 749/1939 [01:19<01:59,  9.97it/s]
 39%|███▉      | 752/1939 [01:20<01:45, 11.23it/s]
 39%|███▉      | 754/1939 [01:20<01:39, 11.86it/s]
 39%|███▉      | 756/1939 [01:20<02:34,  7.67it/s]
 39%|███▉      | 758/1939 [01:21<03:27,  5.70it/s]
 39%|███▉      | 760/1939 [01:22<04:02,  4.85it/s]
 39%|███▉      | 762/1939 [01:22<03:16,  5.99it/s]
 39%|███▉      | 764/1939 [01:22<03:53,  5.04it/s]
 40%|███▉      | 766/1939 [01:23<04:22,  4.47it/s]
 40%|███▉      | 767/1939 [01:23<05:22,  3.63it/s]
 40%|███▉      | 769/1939 [01:24<05:27,  3.58it/s]
 40%|███▉      | 770/1939 [01:24<06:15,  3.11it/s]
 40%|███▉      | 772/1939 [01:25<06:03,  3.21it/s]
 40%|███▉      | 773/1939 [01:26<06:54,  2.81it/s]
 40%|███▉      | 775/1939 [01:26<04:50,  4.01it/s]
 40%|████      | 776/1939 [01:26<05:56,  3.27it/s]
 40%|████      | 777/1939 [01:27<06:55,  2.80it/s]
 40%|████      | 779/1939 [01:27<06:24,  3.02it/s]
 40%|████      | 780/1939 [01:28<07:14,  2.67it/s]
 40%|████      | 784/1939 [01:29<04:51,  3.97it/s]
 41%|████      | 786/1939 [01:29<03:47,  5.07it/s]
 41%|████      | 787/1939 [01:29<04:48,  3.99it/s]
 41%|████      | 789/1939 [01:30<05:06,  3.75it/s]
 41%|████      | 791/1939 [01:30<05:26,  3.51it/s]
 41%|████      | 792/1939 [01:31<04:51,  3.94it/s]
 41%|████      | 794/1939 [01:31<03:33,  5.35it/s]
 41%|████      | 798/1939 [01:31<03:06,  6.12it/s]
 41%|████▏     | 800/1939 [01:31<02:34,  7.35it/s]
 41%|████▏     | 804/1939 [01:32<02:35,  7.32it/s]
 42%|████▏     | 806/1939 [01:32<03:16,  5.78it/s]
 42%|████▏     | 808/1939 [01:33<02:44,  6.89it/s]
 42%|████▏     | 810/1939 [01:33<03:24,  5.53it/s]
 42%|████▏     | 812/1939 [01:34<03:47,  4.96it/s]
 42%|████▏     | 813/1939 [01:34<04:44,  3.96it/s]
 42%|████▏     | 815/1939 [01:34<03:34,  5.23it/s]
 42%|████▏     | 816/1939 [01:35<03:50,  4.87it/s]
 42%|████▏     | 817/1939 [01:35<05:01,  3.72it/s]
 42%|████▏     | 818/1939 [01:35<05:18,  3.52it/s]
 42%|████▏     | 819/1939 [01:36<05:38,  3.31it/s]
 42%|████▏     | 820/1939 [01:36<05:17,  3.52it/s]
 42%|████▏     | 821/1939 [01:36<05:35,  3.34it/s]
 42%|████▏     | 822/1939 [01:37<05:17,  3.52it/s]
 42%|████▏     | 823/1939 [01:37<05:11,  3.58it/s]
 43%|████▎     | 825/1939 [01:37<04:11,  4.44it/s]
 43%|████▎     | 827/1939 [01:37<02:59,  6.19it/s]
 43%|████▎     | 829/1939 [01:38<03:44,  4.95it/s]
 43%|████▎     | 832/1939 [01:38<02:27,  7.49it/s]
 43%|████▎     | 839/1939 [01:38<01:09, 15.73it/s]
 44%|████▎     | 846/1939 [01:38<00:45, 24.26it/s]
 44%|████▍     | 852/1939 [01:38<00:37, 28.66it/s]
 44%|████▍     | 857/1939 [01:39<01:08, 15.70it/s]
 44%|████▍     | 861/1939 [01:39<01:07, 16.09it/s]
 45%|████▍     | 864/1939 [01:40<01:18, 13.74it/s]
 45%|████▍     | 867/1939 [01:40<01:14, 14.40it/s]
 45%|████▍     | 871/1939 [01:40<01:00, 17.73it/s]
 45%|████▌     | 877/1939 [01:40<00:44, 23.89it/s]
 46%|████▌     | 885/1939 [01:40<00:31, 33.24it/s]
 46%|████▌     | 892/1939 [01:40<00:25, 40.35it/s]
 46%|████▋     | 898/1939 [01:40<00:23, 43.87it/s]
 47%|████▋     | 904/1939 [01:41<00:50, 20.63it/s]
 47%|████▋     | 908/1939 [01:41<00:46, 22.28it/s]
 47%|████▋     | 912/1939 [01:42<01:17, 13.25it/s]
 47%|████▋     | 918/1939 [01:42<01:24, 12.05it/s]
 47%|████▋     | 921/1939 [01:42<01:17, 13.20it/s]
 48%|████▊     | 926/1939 [01:43<00:59, 16.96it/s]
 48%|████▊     | 929/1939 [01:43<01:16, 13.18it/s]
 48%|████▊     | 932/1939 [01:43<01:07, 14.88it/s]
 48%|████▊     | 938/1939 [01:43<00:47, 21.29it/s]
 49%|████▊     | 942/1939 [01:43<00:41, 24.03it/s]
 49%|████▉     | 949/1939 [01:43<00:30, 32.41it/s]
 49%|████▉     | 955/1939 [01:44<00:26, 37.67it/s]
 50%|████▉     | 962/1939 [01:44<00:21, 44.80it/s]
 50%|████▉     | 968/1939 [01:44<00:44, 21.59it/s]
 50%|█████     | 973/1939 [01:46<02:00,  8.04it/s]
 50%|█████     | 976/1939 [01:46<01:45,  9.15it/s]
 50%|█████     | 979/1939 [01:47<02:02,  7.83it/s]
 51%|█████     | 982/1939 [01:47<02:15,  7.06it/s]
 51%|█████     | 984/1939 [01:48<02:33,  6.22it/s]
 51%|█████     | 987/1939 [01:48<01:59,  7.98it/s]
 51%|█████     | 991/1939 [01:48<02:04,  7.59it/s]
 51%|█████     | 993/1939 [01:49<01:50,  8.55it/s]
 51%|█████▏    | 997/1939 [01:49<02:00,  7.82it/s]
 52%|█████▏    | 999/1939 [01:50<02:30,  6.25it/s]
 52%|█████▏    | 1002/1939 [01:50<02:37,  5.95it/s]
 52%|█████▏    | 1005/1939 [01:51<02:39,  5.84it/s]
 52%|█████▏    | 1007/1939 [01:51<02:15,  6.90it/s]
 52%|█████▏    | 1009/1939 [01:51<02:35,  5.99it/s]
 52%|█████▏    | 1010/1939 [01:51<02:30,  6.16it/s]
 52%|█████▏    | 1011/1939 [01:52<02:57,  5.22it/s]
 52%|█████▏    | 1012/1939 [01:52<03:19,  4.66it/s]
 52%|█████▏    | 1014/1939 [01:53<03:23,  4.54it/s]
 52%|█████▏    | 1015/1939 [01:53<03:54,  3.95it/s]
 52%|█████▏    | 1016/1939 [01:53<03:58,  3.88it/s]
 53%|█████▎    | 1018/1939 [01:53<02:51,  5.36it/s]
 53%|█████▎    | 1019/1939 [01:54<04:16,  3.58it/s]
 53%|█████▎    | 1022/1939 [01:55<03:37,  4.21it/s]
 53%|█████▎    | 1025/1939 [01:55<02:24,  6.33it/s]
 53%|█████▎    | 1027/1939 [01:55<02:47,  5.44it/s]
 53%|█████▎    | 1030/1939 [01:55<01:59,  7.62it/s]
 53%|█████▎    | 1036/1939 [01:55<01:05, 13.75it/s]
 54%|█████▎    | 1042/1939 [01:56<00:44, 20.32it/s]
 54%|█████▍    | 1046/1939 [01:56<01:09, 12.87it/s]
 54%|█████▍    | 1049/1939 [01:57<01:35,  9.35it/s]
 54%|█████▍    | 1052/1939 [01:58<02:32,  5.82it/s]
 54%|█████▍    | 1054/1939 [01:58<02:49,  5.22it/s]
 54%|█████▍    | 1056/1939 [01:59<02:41,  5.47it/s]
 55%|█████▍    | 1058/1939 [01:59<02:57,  4.97it/s]
 55%|█████▍    | 1059/1939 [02:00<03:39,  4.01it/s]
 55%|█████▍    | 1060/1939 [02:00<04:07,  3.56it/s]
 55%|█████▍    | 1063/1939 [02:00<02:34,  5.66it/s]
 55%|█████▌    | 1068/1939 [02:01<02:07,  6.84it/s]
 55%|█████▌    | 1070/1939 [02:01<01:48,  8.01it/s]
 55%|█████▌    | 1075/1939 [02:01<01:08, 12.61it/s]
 56%|█████▌    | 1080/1939 [02:02<01:21, 10.50it/s]
 56%|█████▌    | 1082/1939 [02:02<01:16, 11.24it/s]
 56%|█████▌    | 1088/1939 [02:02<01:23, 10.19it/s]
 56%|█████▌    | 1090/1939 [02:03<01:17, 10.99it/s]
 56%|█████▋    | 1092/1939 [02:03<01:47,  7.88it/s]
 56%|█████▋    | 1094/1939 [02:04<02:06,  6.67it/s]
 56%|█████▋    | 1095/1939 [02:04<02:34,  5.48it/s]
 57%|█████▋    | 1097/1939 [02:04<02:52,  4.87it/s]
 57%|█████▋    | 1099/1939 [02:05<02:18,  6.06it/s]
 57%|█████▋    | 1102/1939 [02:05<02:01,  6.89it/s]
 57%|█████▋    | 1104/1939 [02:05<01:40,  8.32it/s]
 57%|█████▋    | 1106/1939 [02:05<01:52,  7.39it/s]
 57%|█████▋    | 1108/1939 [02:06<01:38,  8.44it/s]
 57%|█████▋    | 1112/1939 [02:06<01:04, 12.72it/s]
 58%|█████▊    | 1116/1939 [02:06<01:24,  9.77it/s]
 58%|█████▊    | 1118/1939 [02:06<01:14, 10.99it/s]
 58%|█████▊    | 1121/1939 [02:07<01:38,  8.30it/s]
 58%|█████▊    | 1123/1939 [02:07<01:25,  9.57it/s]
 58%|█████▊    | 1126/1939 [02:08<01:46,  7.65it/s]
 58%|█████▊    | 1128/1939 [02:08<01:32,  8.77it/s]
 58%|█████▊    | 1130/1939 [02:09<02:54,  4.62it/s]
 58%|█████▊    | 1133/1939 [02:09<02:04,  6.45it/s]
 59%|█████▊    | 1137/1939 [02:09<02:00,  6.64it/s]
 59%|█████▊    | 1139/1939 [02:10<01:58,  6.75it/s]
 59%|█████▉    | 1142/1939 [02:10<02:00,  6.62it/s]
 59%|█████▉    | 1144/1939 [02:10<01:42,  7.75it/s]
 59%|█████▉    | 1148/1939 [02:11<01:48,  7.31it/s]
 59%|█████▉    | 1150/1939 [02:11<02:18,  5.72it/s]
 59%|█████▉    | 1151/1939 [02:12<02:38,  4.96it/s]
 59%|█████▉    | 1153/1939 [02:12<02:24,  5.45it/s]
 60%|█████▉    | 1155/1939 [02:12<01:54,  6.83it/s]
 60%|█████▉    | 1157/1939 [02:12<01:36,  8.13it/s]
 60%|█████▉    | 1159/1939 [02:12<01:21,  9.58it/s]
 60%|█████▉    | 1161/1939 [02:13<02:03,  6.32it/s]
 60%|█████▉    | 1163/1939 [02:14<02:29,  5.18it/s]
 60%|██████    | 1165/1939 [02:14<02:56,  4.38it/s]
 60%|██████    | 1167/1939 [02:14<02:16,  5.67it/s]
 60%|██████    | 1172/1939 [02:15<01:39,  7.69it/s]
 61%|██████    | 1174/1939 [02:15<01:25,  8.91it/s]
 61%|██████    | 1178/1939 [02:15<01:19,  9.59it/s]
 61%|██████    | 1180/1939 [02:16<01:46,  7.16it/s]
 61%|██████    | 1182/1939 [02:16<01:30,  8.40it/s]
 61%|██████    | 1184/1939 [02:16<01:59,  6.30it/s]
 61%|██████    | 1186/1939 [02:17<02:03,  6.12it/s]
 61%|██████▏   | 1188/1939 [02:17<01:39,  7.52it/s]
 61%|██████▏   | 1190/1939 [02:17<02:07,  5.87it/s]
 61%|██████▏   | 1191/1939 [02:18<02:39,  4.70it/s]
 61%|██████▏   | 1192/1939 [02:18<02:42,  4.60it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 311.21it/s]
 84%|████████▎ | 251/300 [19:33<26:22, 32.29s/it]

[[np.int64(0), False, 3], [np.int64(1), False, 12], [np.int64(2), False, 7], [np.int64(3), False, 12], [np.int64(4), False, 11], [np.int64(5), False, 6], [np.int64(8), False, 9], [np.int64(9), False, 1], [np.int64(10), False, 13], [np.int64(11), False, 8]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0453, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9736, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.9662, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0417, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1702, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 253/300 [19:33<16:40, 21.28s/it]

tensor(12.9670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2421, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2662, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0418, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3170, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [19:33<10:09, 13.54s/it]

tensor(12.9756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3487, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [19:33<06:24,  8.93s/it]

tensor(12.9771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0424, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2137, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0419, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2855, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9790, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0411, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2380, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [19:33<04:07,  6.03s/it]

tensor(12.9771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0406, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3375, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0411, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3350, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [19:34<02:41,  4.13s/it]

tensor(12.9814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3311, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [19:34<01:46,  2.87s/it]

tensor(12.9814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4279, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0408, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5160, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0397, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5281, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [19:34<01:10,  2.01s/it]

tensor(12.9905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0389, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5424, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [19:34<00:47,  1.43s/it]

tensor(12.9989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0375, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5682, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0361, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2871, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [19:34<00:31,  1.02s/it]

tensor(13.0000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0395, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4201, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [19:35<00:21,  1.35it/s]

tensor(12.9964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0432, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4051, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0464, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4968, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0602, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0488, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4509, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [19:35<00:14,  1.83it/s]

tensor(13.4226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0505, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4520, device='cuda:0', grad_fn=<MulBackward0>)
tensor(15.2174, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5187, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [19:35<00:10,  2.44it/s]

tensor(20.0315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0531, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4736, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [19:35<00:07,  3.17it/s]

tensor(14.6297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0545, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(15.1956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0548, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5813, device='cuda:0', grad_fn=<MulBackward0>)
tensor(14.1941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0477, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [19:35<00:05,  4.02it/s]

tensor(13.9200, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0542, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4746, device='cuda:0', grad_fn=<MulBackward0>)
tensor(14.0090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0545, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6392, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [19:36<00:03,  4.95it/s]

tensor(14.1755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0550, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2477, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [19:36<00:02,  5.89it/s]

tensor(14.3237, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0552, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(14.3742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0552, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4106, device='cuda:0', grad_fn=<MulBackward0>)
tensor(14.3321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6024, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [19:36<00:02,  6.78it/s]

tensor(14.2850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0535, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7036, device='cuda:0', grad_fn=<MulBackward0>)
tensor(14.2229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0524, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1037, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [19:36<00:01,  7.59it/s]

tensor(14.1339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0508, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1782, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [19:36<00:01,  8.27it/s]

tensor(14.0322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0493, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0410, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.9834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0483, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9277, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.9997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0486, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9077, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [19:36<00:01,  8.84it/s]

tensor(14.0035, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0497, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2201, device='cuda:0', grad_fn=<MulBackward0>)
tensor(14.0227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0511, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0041, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [19:37<00:00,  9.28it/s]

tensor(14.0284, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0519, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9032, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [19:37<00:00,  9.65it/s]

tensor(14.0071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0517, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0239, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.9876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0501, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9437, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.9561, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0470, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9191, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [19:37<00:00,  9.93it/s]

tensor(13.9001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.8622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0427, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9798, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [19:37<00:00, 10.08it/s]

tensor(13.8277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0414, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9060, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [19:37<00:00,  3.93s/it]

Model training finished!

Infer time:  0.0024874210357666016
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 7
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.343137377481
NMI         : 0.522054840567
Runtime     : 1200.99 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed7

==============================================================================================================
PRAGA RUN | S2-E15 | seed=8
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 1.082e-16
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29,  9.99it/s]

tensor(18.1084, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3753, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(18.0544, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2336, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:26, 11.25it/s]

tensor(17.8396, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3019, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6709, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5593, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5628, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9878, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:24, 12.07it/s]

tensor(17.4988, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5711, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4629, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2929, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4442, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1409, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.66it/s]

tensor(17.4240, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1023, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3998, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1651, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3618, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3210, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:00<00:22, 12.84it/s]

tensor(17.3071, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5592, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2444, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8731, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1800, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2548, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.08it/s]

tensor(17.1191, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6974, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0673, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1951, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0161, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7431, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:21, 13.12it/s]

tensor(16.9559, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3351, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8830, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9679, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8033, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6381, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:21, 13.14it/s]

tensor(16.7248, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3404, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6527, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0731, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5865, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8325, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:01<00:21, 13.14it/s]

tensor(16.5217, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6161, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4516, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3738, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2464, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.16it/s]

tensor(16.2864, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0901, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.1920, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9495, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0931, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8232, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:20, 13.18it/s]

tensor(15.9934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7105, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6097, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5199, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:20, 13.23it/s]

tensor(15.6675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4399, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3688, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3058, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:02<00:19, 13.24it/s]

tensor(15.3476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2501, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2017, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1625, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1604, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.23it/s]

tensor(15.0811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0960, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0730, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:03<00:19, 13.13it/s]

tensor(14.8639, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0561, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7190, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:19, 13.17it/s]

tensor(14.6533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:03<00:19, 13.07it/s]

tensor(14.4951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:04<00:18, 13.16it/s]

tensor(14.3747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0346, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3342, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:04<00:18, 13.16it/s]

tensor(14.2552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:18, 13.14it/s]

tensor(14.1393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:04<00:18, 13.19it/s]

tensor(14.0449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.16it/s]

tensor(13.9601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:05<00:17, 13.14it/s]

tensor(13.8811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.18it/s]

tensor(13.8100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:05<00:17, 13.18it/s]

tensor(13.7461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:16, 13.19it/s]

tensor(13.6869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:05<00:16, 13.20it/s]

tensor(13.6313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5961, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.19it/s]

tensor(13.5787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:06<00:16, 13.21it/s]

tensor(13.5295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:16, 13.20it/s]

tensor(13.4833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:06<00:15, 13.17it/s]

tensor(13.4397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4114, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.20it/s]

tensor(13.3978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3705, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:07<00:15, 13.20it/s]

tensor(13.3572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:15, 13.13it/s]

tensor(13.3187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([162, 254,  70, 122, 187,  33,  81, 111, 558, 174,  77,  18,  34,  58])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:48, 17.79it/s]
  0%|          | 6/1939 [00:00<01:09, 27.74it/s]
  0%|          | 9/1939 [00:00<01:10, 27.22it/s]
  1%|          | 14/1939 [00:00<00:54, 35.21it/s]
  1%|          | 18/1939 [00:00<01:01, 31.29it/s]
  1%|          | 22/1939 [00:00<00:57, 33.26it/s]
  1%|▏         | 29/1939 [00:00<00:43, 43.75it/s]
  2%|▏         | 36/1939 [00:00<00:43, 44.16it/s]
  2%|▏         | 41/1939 [00:01<02:09, 14.65it/s]
  2%|▏         | 45/1939 [00:02<03:23,  9.30it/s]
  3%|▎         | 49/1939 [00:03<03:52,  8.12it/s]
  3%|▎         | 51/1939 [00:03<03:34,  8.78it/s]
  3%|▎         | 53/1939 [00:04<04:21,  7.21it/s]
  3%|▎         | 55/1939 [00:04<03:53,  8.09it/s]
  3%|▎         | 57/1939 [00:04<03:24,  9.20it/s]
  3%|▎         | 59/1939 [00:04<05:04,  6.17it/s]
  3%|▎         | 62/1939 [00:05<03:56,  7.95it/s]
  3%|▎         | 66/1939 [00:06<06:17,  4.96it/s]
  4%|▎         | 69/1939 [00:06<04:45,  6.56it/s]
  4%|▎         | 71/1939 [00:08<08:51,  3.51it/s]
  4%|▍         | 73/1939 [00:09<11:44,  2.65it/s]
  4%|▍         | 76/1939 [00:09<08:08,  3.81it/s]
  4%|▍         | 78/1939 [00:10<10:49,  2.86it/s]
 33%|███▎      | 100/300 [00:22<00:15, 13.13it/s]
  4%|▍         | 80/1939 [00:12<16:19,  1.90it/s]
  4%|▍         | 81/1939 [00:13<16:21,  1.89it/s]
  4%|▍         | 82/1939 [00:13<15:39,  1.98it/s]
  4%|▍         | 84/1939 [00:14<12:58,  2.38it/s]
  4%|▍         | 86/1939 [00:14<11:49,  2.61it/s]
  4%|▍         | 87/1939 [00:15<12:09,  2.54it/s]
  5%|▍         | 89/1939 [00:15<08:26,  3.66it/s]
  5%|▍         | 91/1939 [00:15<06:34,  4.68it/s]
  5%|▍         | 94/1939 [00:16<08:16,  3.72it/s]
  5%|▍         | 96/1939 [00:16<06:20,  4.84it/s]
  5%|▌         | 98/1939 [00:16<05:26,  5.64it/s]
  5%|▌         | 100/1939 [00:17<05:53,  5.20it/s]
  5%|▌         | 101/1939 [00:17<07:47,  3.93it/s]
  5%|▌         | 103/1939 [00:18<05:45,  5.32it/s]
  5%|▌         | 105/1939 [00:19<10:39,  2.87it/s]
  5%|▌         | 106/1939 [00:19<09:17,  3.29it/s]
  6%|▌         | 107/1939 [00:20<15:18,  2.00it/s]
  6%|▌         | 109/1939 [00:20<10:07,  3.01it/s]
  6%|▌         | 110/1939 [00:22<16:04,  1.90it/s]
  6%|▌         | 113/1939 [00:22<09:01,  3.37it/s]
  6%|▌         | 115/1939 [00:22<08:53,  3.42it/s]
  6%|▌         | 116/1939 [00:23<08:14,  3.69it/s]
  6%|▌         | 118/1939 [00:23<10:00,  3.03it/s]
  6%|▌         | 120/1939 [00:25<12:25,  2.44it/s]
  6%|▌         | 121/1939 [00:25<13:11,  2.30it/s]
  6%|▋         | 122/1939 [00:25<11:48,  2.56it/s]
  6%|▋         | 124/1939 [00:25<08:05,  3.74it/s]
  7%|▋         | 127/1939 [00:26<04:55,  6.14it/s]
  7%|▋         | 129/1939 [00:26<06:06,  4.94it/s]
  7%|▋         | 132/1939 [00:27<06:56,  4.34it/s]
  7%|▋         | 135/1939 [00:28<09:15,  3.25it/s]
  7%|▋         | 137/1939 [00:30<11:51,  2.53it/s]
  7%|▋         | 139/1939 [00:31<13:49,  2.17it/s]
  7%|▋         | 141/1939 [00:31<10:25,  2.87it/s]
  7%|▋         | 142/1939 [00:32<11:19,  2.64it/s]
  7%|▋         | 144/1939 [00:32<09:20,  3.20it/s]
  7%|▋         | 145/1939 [00:33<12:05,  2.47it/s]
  8%|▊         | 146/1939 [00:33<12:42,  2.35it/s]
  8%|▊         | 148/1939 [00:33<08:34,  3.48it/s]
  8%|▊         | 150/1939 [00:33<06:09,  4.84it/s]
  8%|▊         | 152/1939 [00:35<10:43,  2.78it/s]
  8%|▊         | 153/1939 [00:36<15:32,  1.91it/s]
  8%|▊         | 154/1939 [00:36<12:51,  2.31it/s]
  8%|▊         | 157/1939 [00:37<09:49,  3.02it/s]
  8%|▊         | 158/1939 [00:37<10:06,  2.94it/s]
  8%|▊         | 159/1939 [00:38<13:00,  2.28it/s]
  8%|▊         | 160/1939 [00:39<15:15,  1.94it/s]
  8%|▊         | 161/1939 [00:39<15:24,  1.92it/s]
  8%|▊         | 162/1939 [00:40<18:02,  1.64it/s]
  8%|▊         | 163/1939 [00:41<19:48,  1.49it/s]
  8%|▊         | 164/1939 [00:42<22:36,  1.31it/s]
  9%|▊         | 165/1939 [00:42<20:53,  1.42it/s]
  9%|▊         | 167/1939 [00:43<12:20,  2.39it/s]
  9%|▊         | 169/1939 [00:43<08:17,  3.56it/s]
  9%|▉         | 170/1939 [00:44<14:37,  2.01it/s]
  9%|▉         | 172/1939 [00:44<09:53,  2.98it/s]
  9%|▉         | 173/1939 [00:45<10:55,  2.69it/s]
  9%|▉         | 175/1939 [00:45<07:25,  3.96it/s]
  9%|▉         | 181/1939 [00:45<03:09,  9.26it/s]
  9%|▉         | 184/1939 [00:45<02:32, 11.51it/s]
 10%|▉         | 189/1939 [00:45<01:44, 16.69it/s]
 10%|█         | 195/1939 [00:45<01:14, 23.44it/s]
 10%|█         | 200/1939 [00:45<01:02, 27.71it/s]
 11%|█         | 204/1939 [00:47<03:14,  8.90it/s]
 11%|█         | 207/1939 [00:49<08:19,  3.47it/s]
 11%|█         | 209/1939 [00:49<07:08,  4.03it/s]
 11%|█         | 211/1939 [00:51<09:25,  3.05it/s]
 11%|█         | 213/1939 [00:51<07:39,  3.76it/s]
 11%|█         | 215/1939 [00:51<08:19,  3.45it/s]
 11%|█         | 218/1939 [00:52<08:12,  3.49it/s]
 11%|█▏        | 219/1939 [00:52<07:31,  3.81it/s]
 11%|█▏        | 220/1939 [00:53<10:17,  2.79it/s]
 11%|█▏        | 222/1939 [00:54<09:41,  2.96it/s]
 12%|█▏        | 224/1939 [00:54<08:54,  3.21it/s]
 12%|█▏        | 225/1939 [00:55<08:10,  3.50it/s]
 12%|█▏        | 227/1939 [00:55<06:17,  4.53it/s]
 12%|█▏        | 228/1939 [00:55<08:44,  3.26it/s]
 12%|█▏        | 229/1939 [00:56<07:41,  3.71it/s]
 12%|█▏        | 230/1939 [00:56<10:11,  2.80it/s]
 12%|█▏        | 232/1939 [00:56<07:16,  3.91it/s]
 12%|█▏        | 233/1939 [00:57<10:30,  2.70it/s]
 12%|█▏        | 234/1939 [00:57<08:54,  3.19it/s]
 12%|█▏        | 236/1939 [00:58<09:59,  2.84it/s]
 12%|█▏        | 237/1939 [00:58<08:23,  3.38it/s]
 12%|█▏        | 239/1939 [00:59<08:54,  3.18it/s]
 12%|█▏        | 240/1939 [01:00<12:12,  2.32it/s]
 12%|█▏        | 241/1939 [01:00<13:34,  2.08it/s]
 12%|█▏        | 242/1939 [01:01<14:18,  1.98it/s]
 13%|█▎        | 243/1939 [01:02<17:22,  1.63it/s]
 13%|█▎        | 244/1939 [01:03<18:38,  1.52it/s]
 13%|█▎        | 245/1939 [01:04<22:41,  1.24it/s]
 13%|█▎        | 246/1939 [01:05<25:16,  1.12it/s]
 13%|█▎        | 247/1939 [01:05<19:39,  1.43it/s]
 13%|█▎        | 248/1939 [01:06<21:37,  1.30it/s]
 13%|█▎        | 250/1939 [01:06<12:32,  2.24it/s]
 13%|█▎        | 253/1939 [01:06<06:48,  4.13it/s]
 13%|█▎        | 257/1939 [01:08<07:56,  3.53it/s]
 13%|█▎        | 259/1939 [01:08<06:30,  4.30it/s]
 13%|█▎        | 261/1939 [01:08<07:16,  3.84it/s]
 14%|█▎        | 263/1939 [01:09<07:25,  3.76it/s]
 14%|█▎        | 264/1939 [01:10<09:03,  3.08it/s]
 14%|█▎        | 266/1939 [01:10<06:39,  4.19it/s]
 14%|█▍        | 270/1939 [01:11<07:56,  3.51it/s]
 14%|█▍        | 271/1939 [01:11<07:10,  3.87it/s]
 14%|█▍        | 274/1939 [01:11<04:47,  5.79it/s]
 14%|█▍        | 276/1939 [01:12<04:11,  6.60it/s]
 14%|█▍        | 279/1939 [01:12<03:07,  8.84it/s]
 14%|█▍        | 281/1939 [01:12<03:30,  7.89it/s]
 15%|█▍        | 283/1939 [01:12<03:21,  8.21it/s]
 15%|█▍        | 285/1939 [01:14<07:21,  3.74it/s]
 15%|█▍        | 287/1939 [01:14<05:44,  4.80it/s]
 15%|█▍        | 289/1939 [01:14<06:14,  4.40it/s]
 15%|█▌        | 291/1939 [01:14<04:52,  5.63it/s]
 15%|█▌        | 293/1939 [01:16<08:28,  3.23it/s]
 15%|█▌        | 295/1939 [01:16<06:24,  4.27it/s]
 15%|█▌        | 297/1939 [01:16<06:52,  3.99it/s]
 15%|█▌        | 298/1939 [01:17<08:22,  3.26it/s]
 15%|█▌        | 300/1939 [01:18<10:49,  2.52it/s]
 16%|█▌        | 302/1939 [01:18<07:52,  3.46it/s]
 16%|█▌        | 303/1939 [01:19<11:41,  2.33it/s]
 16%|█▌        | 306/1939 [01:19<07:19,  3.72it/s]
 16%|█▌        | 307/1939 [01:20<09:10,  2.96it/s]
 16%|█▌        | 309/1939 [01:20<06:34,  4.14it/s]
 16%|█▌        | 311/1939 [01:20<05:22,  5.05it/s]
 16%|█▌        | 313/1939 [01:22<08:53,  3.05it/s]
 16%|█▌        | 315/1939 [01:23<11:31,  2.35it/s]
 16%|█▋        | 316/1939 [01:24<15:39,  1.73it/s]
 16%|█▋        | 319/1939 [01:24<09:24,  2.87it/s]
 17%|█▋        | 320/1939 [01:25<10:37,  2.54it/s]
 17%|█▋        | 321/1939 [01:25<10:37,  2.54it/s]
 17%|█▋        | 322/1939 [01:26<12:33,  2.15it/s]
 17%|█▋        | 323/1939 [01:26<10:29,  2.57it/s]
 17%|█▋        | 325/1939 [01:26<06:47,  3.96it/s]
 17%|█▋        | 327/1939 [01:26<04:50,  5.54it/s]
 17%|█▋        | 334/1939 [01:26<01:57, 13.68it/s]
 17%|█▋        | 339/1939 [01:27<03:13,  8.27it/s]
 18%|█▊        | 342/1939 [01:28<02:43,  9.78it/s]
 18%|█▊        | 347/1939 [01:28<01:54, 13.92it/s]
 18%|█▊        | 351/1939 [01:29<03:49,  6.92it/s]
 18%|█▊        | 354/1939 [01:31<08:14,  3.21it/s]
 18%|█▊        | 356/1939 [01:33<09:59,  2.64it/s]
 19%|█▊        | 359/1939 [01:33<08:02,  3.28it/s]
 19%|█▊        | 361/1939 [01:34<08:06,  3.24it/s]
 19%|█▊        | 363/1939 [01:34<07:50,  3.35it/s]
 19%|█▉        | 365/1939 [01:34<06:15,  4.19it/s]
 19%|█▉        | 366/1939 [01:35<07:00,  3.74it/s]
 19%|█▉        | 367/1939 [01:35<06:23,  4.10it/s]
 19%|█▉        | 368/1939 [01:35<07:45,  3.37it/s]
 19%|█▉        | 370/1939 [01:36<09:15,  2.82it/s]
 19%|█▉        | 372/1939 [01:37<09:24,  2.78it/s]
 19%|█▉        | 373/1939 [01:37<08:30,  3.07it/s]
 19%|█▉        | 375/1939 [01:38<06:40,  3.90it/s]
 19%|█▉        | 376/1939 [01:39<10:53,  2.39it/s]
 19%|█▉        | 377/1939 [01:39<09:19,  2.79it/s]
 20%|█▉        | 380/1939 [01:39<05:16,  4.92it/s]
 20%|█▉        | 382/1939 [01:40<07:28,  3.47it/s]
 20%|█▉        | 384/1939 [01:40<07:56,  3.26it/s]
 20%|█▉        | 385/1939 [01:41<09:51,  2.63it/s]
 20%|█▉        | 387/1939 [01:42<08:55,  2.90it/s]
 20%|██        | 388/1939 [01:42<09:25,  2.74it/s]
 20%|██        | 390/1939 [01:43<09:15,  2.79it/s]
 20%|██        | 391/1939 [01:44<11:38,  2.22it/s]
 20%|██        | 393/1939 [01:45<11:22,  2.27it/s]
 20%|██        | 394/1939 [01:45<12:16,  2.10it/s]
 20%|██        | 395/1939 [01:45<10:32,  2.44it/s]
 20%|██        | 396/1939 [01:46<10:42,  2.40it/s]
 20%|██        | 397/1939 [01:46<08:37,  2.98it/s]
 21%|██        | 398/1939 [01:46<10:22,  2.48it/s]
 21%|██        | 399/1939 [01:47<08:44,  2.93it/s]
 21%|██        | 400/1939 [01:47<07:19,  3.50it/s]
 21%|██        | 402/1939 [01:47<04:36,  5.55it/s]
 21%|██        | 404/1939 [01:48<06:23,  4.01it/s]
 21%|██        | 405/1939 [01:48<06:47,  3.77it/s]
 21%|██        | 407/1939 [01:49<07:44,  3.30it/s]
 21%|██        | 410/1939 [01:49<04:44,  5.38it/s]
 21%|██        | 412/1939 [01:50<08:31,  2.99it/s]
 21%|██▏       | 415/1939 [01:51<07:08,  3.55it/s]
 22%|██▏       | 417/1939 [01:52<08:48,  2.88it/s]
 22%|██▏       | 419/1939 [01:53<10:28,  2.42it/s]
 22%|██▏       | 422/1939 [01:54<08:38,  2.92it/s]
 22%|██▏       | 423/1939 [01:54<07:52,  3.21it/s]
 22%|██▏       | 425/1939 [01:54<05:55,  4.26it/s]
 22%|██▏       | 426/1939 [01:54<07:05,  3.56it/s]
 22%|██▏       | 428/1939 [01:55<07:17,  3.46it/s]
 22%|██▏       | 429/1939 [01:55<06:52,  3.66it/s]
 22%|██▏       | 431/1939 [01:55<05:04,  4.96it/s]
 22%|██▏       | 433/1939 [01:55<03:47,  6.62it/s]
 23%|██▎       | 437/1939 [01:56<02:15, 11.12it/s]
 23%|██▎       | 442/1939 [01:56<01:26, 17.38it/s]
 23%|██▎       | 445/1939 [01:56<01:20, 18.56it/s]
 23%|██▎       | 452/1939 [01:56<00:57, 26.00it/s]
 24%|██▎       | 456/1939 [01:56<01:04, 22.99it/s]
 24%|██▎       | 460/1939 [01:56<01:00, 24.58it/s]
 24%|██▍       | 466/1939 [01:56<00:51, 28.62it/s]
 24%|██▍       | 470/1939 [01:57<00:48, 30.40it/s]
 25%|██▍       | 476/1939 [01:58<02:24, 10.12it/s]
 25%|██▍       | 479/1939 [01:59<03:51,  6.30it/s]
 25%|██▍       | 482/1939 [01:59<03:39,  6.64it/s]
 25%|██▍       | 484/1939 [02:00<03:13,  7.51it/s]
 25%|██▌       | 489/1939 [02:01<04:23,  5.51it/s]
 25%|██▌       | 491/1939 [02:01<03:51,  6.25it/s]
 25%|██▌       | 493/1939 [02:02<06:11,  3.89it/s]
 26%|██▌       | 496/1939 [02:03<07:20,  3.28it/s]
 26%|██▌       | 498/1939 [02:04<06:02,  3.98it/s]
 26%|██▌       | 504/1939 [02:04<03:15,  7.33it/s]
 26%|██▋       | 511/1939 [02:05<03:47,  6.28it/s]
 26%|██▋       | 513/1939 [02:05<03:29,  6.81it/s]
 27%|██▋       | 516/1939 [02:05<02:52,  8.25it/s]
 27%|██▋       | 522/1939 [02:05<01:50, 12.87it/s]
 27%|██▋       | 528/1939 [02:06<01:20, 17.52it/s]
 27%|██▋       | 533/1939 [02:06<01:07, 20.95it/s]
 28%|██▊       | 537/1939 [02:07<02:45,  8.49it/s]
 28%|██▊       | 540/1939 [02:07<02:20,  9.96it/s]
 28%|██▊       | 543/1939 [02:07<02:15, 10.28it/s]
 28%|██▊       | 546/1939 [02:09<04:12,  5.53it/s]
 28%|██▊       | 548/1939 [02:10<06:09,  3.76it/s]
 28%|██▊       | 550/1939 [02:10<05:07,  4.52it/s]
 28%|██▊       | 552/1939 [02:11<07:23,  3.13it/s]
 29%|██▊       | 554/1939 [02:11<06:06,  3.78it/s]
 29%|██▊       | 556/1939 [02:13<08:27,  2.73it/s]
 29%|██▉       | 558/1939 [02:14<09:49,  2.34it/s]
 29%|██▉       | 560/1939 [02:14<07:28,  3.07it/s]
 29%|██▉       | 564/1939 [02:14<04:23,  5.21it/s]
 29%|██▉       | 567/1939 [02:14<03:19,  6.89it/s]
 29%|██▉       | 571/1939 [02:15<04:40,  4.87it/s]
 30%|██▉       | 573/1939 [02:16<05:24,  4.21it/s]
 30%|██▉       | 575/1939 [02:18<08:04,  2.81it/s]
 30%|██▉       | 576/1939 [02:18<07:22,  3.08it/s]
 30%|██▉       | 579/1939 [02:19<06:55,  3.27it/s]
 30%|██▉       | 580/1939 [02:19<06:18,  3.59it/s]
 30%|███       | 582/1939 [02:20<08:34,  2.64it/s]
 30%|███       | 584/1939 [02:21<09:49,  2.30it/s]
 30%|███       | 586/1939 [02:22<10:56,  2.06it/s]
 30%|███       | 588/1939 [02:22<08:11,  2.75it/s]
 30%|███       | 589/1939 [02:23<09:30,  2.37it/s]
 30%|███       | 590/1939 [02:23<08:06,  2.77it/s]
 30%|███       | 591/1939 [02:24<12:12,  1.84it/s]
 31%|███       | 592/1939 [02:26<15:16,  1.47it/s]
 31%|███       | 593/1939 [02:27<17:55,  1.25it/s]
 31%|███       | 595/1939 [02:28<14:21,  1.56it/s]
 31%|███       | 596/1939 [02:28<13:41,  1.63it/s]
 31%|███       | 598/1939 [02:28<09:13,  2.42it/s]
 31%|███       | 599/1939 [02:30<13:23,  1.67it/s]
 31%|███       | 600/1939 [02:31<16:54,  1.32it/s]
 31%|███       | 601/1939 [02:32<17:50,  1.25it/s]
 31%|███       | 603/1939 [02:33<16:23,  1.36it/s]
 31%|███       | 605/1939 [02:33<10:55,  2.03it/s]
 31%|███▏      | 607/1939 [02:34<10:04,  2.20it/s]
 31%|███▏      | 608/1939 [02:35<10:35,  2.09it/s]
 31%|███▏      | 609/1939 [02:35<09:30,  2.33it/s]
 32%|███▏      | 611/1939 [02:36<09:26,  2.34it/s]
 32%|███▏      | 612/1939 [02:36<10:20,  2.14it/s]
 32%|███▏      | 613/1939 [02:37<12:13,  1.81it/s]
 32%|███▏      | 614/1939 [02:38<12:03,  1.83it/s]
 32%|███▏      | 615/1939 [02:38<12:03,  1.83it/s]
 32%|███▏      | 616/1939 [02:39<14:27,  1.52it/s]
 32%|███▏      | 617/1939 [02:40<14:32,  1.52it/s]
 32%|███▏      | 618/1939 [02:40<14:17,  1.54it/s]
 32%|███▏      | 619/1939 [02:41<11:02,  1.99it/s]
 32%|███▏      | 620/1939 [02:41<12:44,  1.73it/s]
 32%|███▏      | 621/1939 [02:42<13:16,  1.65it/s]
 32%|███▏      | 622/1939 [02:43<13:36,  1.61it/s]
 32%|███▏      | 623/1939 [02:43<10:48,  2.03it/s]
 32%|███▏      | 625/1939 [02:43<06:20,  3.45it/s]
 32%|███▏      | 627/1939 [02:43<04:24,  4.96it/s]
 32%|███▏      | 629/1939 [02:44<08:00,  2.73it/s]
 32%|███▏      | 630/1939 [02:46<12:07,  1.80it/s]
 33%|███▎      | 632/1939 [02:47<13:04,  1.67it/s]
 33%|███▎      | 635/1939 [02:47<07:41,  2.82it/s]
 33%|███▎      | 636/1939 [02:48<08:40,  2.50it/s]
 33%|███▎      | 637/1939 [02:48<08:54,  2.43it/s]
 33%|███▎      | 639/1939 [02:48<06:07,  3.54it/s]
 33%|███▎      | 640/1939 [02:49<06:23,  3.39it/s]
 33%|███▎      | 641/1939 [02:49<08:55,  2.42it/s]
 33%|███▎      | 643/1939 [02:50<08:24,  2.57it/s]
 33%|███▎      | 644/1939 [02:50<07:13,  2.98it/s]
 33%|███▎      | 646/1939 [02:52<09:27,  2.28it/s]
 33%|███▎      | 649/1939 [02:53<09:24,  2.29it/s]
 34%|███▎      | 651/1939 [02:54<10:47,  1.99it/s]
 34%|███▎      | 653/1939 [02:54<07:54,  2.71it/s]
 34%|███▎      | 654/1939 [02:55<11:05,  1.93it/s]
 34%|███▍      | 656/1939 [02:57<11:59,  1.78it/s]
 34%|███▍      | 657/1939 [02:58<14:47,  1.44it/s]
 34%|███▍      | 658/1939 [02:59<17:11,  1.24it/s]
 34%|███▍      | 659/1939 [02:59<14:22,  1.48it/s]
 34%|███▍      | 662/1939 [03:00<07:32,  2.82it/s]
 34%|███▍      | 665/1939 [03:01<08:09,  2.60it/s]
 34%|███▍      | 666/1939 [03:02<10:52,  1.95it/s]
 34%|███▍      | 667/1939 [03:02<09:30,  2.23it/s]
 34%|███▍      | 668/1939 [03:03<13:01,  1.63it/s]
 35%|███▍      | 671/1939 [03:04<07:09,  2.95it/s]
 35%|███▍      | 673/1939 [03:06<11:35,  1.82it/s]
 35%|███▍      | 675/1939 [03:06<08:19,  2.53it/s]
 35%|███▍      | 677/1939 [03:07<08:39,  2.43it/s]
 35%|███▍      | 678/1939 [03:07<09:56,  2.11it/s]
 35%|███▌      | 680/1939 [03:08<09:01,  2.33it/s]
 35%|███▌      | 682/1939 [03:08<06:24,  3.27it/s]
 35%|███▌      | 683/1939 [03:09<08:12,  2.55it/s]
 35%|███▌      | 685/1939 [03:09<05:42,  3.66it/s]
 35%|███▌      | 687/1939 [03:10<08:05,  2.58it/s]
 36%|███▌      | 689/1939 [03:11<07:27,  2.79it/s]
 36%|███▌      | 690/1939 [03:11<06:43,  3.09it/s]
 36%|███▌      | 692/1939 [03:11<05:04,  4.10it/s]
 36%|███▌      | 696/1939 [03:11<02:55,  7.08it/s]
 36%|███▌      | 700/1939 [03:11<02:02, 10.11it/s]
 36%|███▋      | 704/1939 [03:12<01:30, 13.61it/s]
 37%|███▋      | 708/1939 [03:12<01:11, 17.33it/s]
 37%|███▋      | 711/1939 [03:12<01:03, 19.20it/s]
 37%|███▋      | 714/1939 [03:12<00:57, 21.30it/s]
 37%|███▋      | 720/1939 [03:12<00:45, 26.88it/s]
 37%|███▋      | 725/1939 [03:13<02:21,  8.55it/s]
 38%|███▊      | 728/1939 [03:14<02:00, 10.02it/s]
 38%|███▊      | 731/1939 [03:16<05:38,  3.57it/s]
 38%|███▊      | 733/1939 [03:17<07:01,  2.86it/s]
 38%|███▊      | 735/1939 [03:18<06:50,  2.93it/s]
 38%|███▊      | 737/1939 [03:18<05:31,  3.62it/s]
 38%|███▊      | 739/1939 [03:19<06:14,  3.21it/s]
 38%|███▊      | 741/1939 [03:19<04:53,  4.08it/s]
 38%|███▊      | 743/1939 [03:20<07:04,  2.82it/s]
 38%|███▊      | 745/1939 [03:21<06:47,  2.93it/s]
 38%|███▊      | 746/1939 [03:21<06:41,  2.97it/s]
 39%|███▊      | 747/1939 [03:22<06:45,  2.94it/s]
 39%|███▊      | 749/1939 [03:22<07:16,  2.73it/s]
 39%|███▊      | 751/1939 [03:23<06:39,  2.97it/s]
 39%|███▉      | 752/1939 [03:23<05:54,  3.35it/s]
 39%|███▉      | 754/1939 [03:23<04:19,  4.56it/s]
 39%|███▉      | 755/1939 [03:24<05:23,  3.66it/s]
 39%|███▉      | 756/1939 [03:24<04:56,  3.99it/s]
 39%|███▉      | 757/1939 [03:25<08:47,  2.24it/s]
 39%|███▉      | 759/1939 [03:25<05:36,  3.50it/s]
 39%|███▉      | 760/1939 [03:26<09:36,  2.05it/s]
 39%|███▉      | 761/1939 [03:26<07:57,  2.47it/s]
 39%|███▉      | 763/1939 [03:28<09:45,  2.01it/s]
 39%|███▉      | 764/1939 [03:28<08:36,  2.27it/s]
 40%|███▉      | 766/1939 [03:29<09:59,  1.96it/s]
 40%|███▉      | 767/1939 [03:30<09:47,  2.00it/s]
 40%|███▉      | 768/1939 [03:30<11:14,  1.74it/s]
 40%|███▉      | 769/1939 [03:31<12:11,  1.60it/s]
 40%|███▉      | 770/1939 [03:32<14:02,  1.39it/s]
 40%|███▉      | 771/1939 [03:33<14:23,  1.35it/s]
 40%|███▉      | 772/1939 [03:33<11:56,  1.63it/s]
 40%|███▉      | 773/1939 [03:34<11:39,  1.67it/s]
 40%|███▉      | 774/1939 [03:34<08:49,  2.20it/s]
 40%|████      | 776/1939 [03:35<07:28,  2.59it/s]
 40%|████      | 777/1939 [03:35<07:11,  2.69it/s]
 40%|████      | 779/1939 [03:36<06:52,  2.81it/s]
 40%|████      | 780/1939 [03:36<07:49,  2.47it/s]
 40%|████      | 781/1939 [03:36<06:27,  2.99it/s]
 40%|████      | 784/1939 [03:37<05:52,  3.28it/s]
 40%|████      | 785/1939 [03:37<05:12,  3.70it/s]
 41%|████      | 787/1939 [03:38<06:19,  3.04it/s]
 41%|████      | 789/1939 [03:38<05:25,  3.53it/s]
 41%|████      | 791/1939 [03:39<05:51,  3.26it/s]
 41%|████      | 794/1939 [03:40<06:42,  2.84it/s]
 41%|████      | 795/1939 [03:41<06:09,  3.09it/s]
 41%|████      | 796/1939 [03:42<08:53,  2.14it/s]
 41%|████      | 797/1939 [03:43<11:39,  1.63it/s]
 41%|████      | 798/1939 [03:44<11:51,  1.60it/s]
 41%|████▏     | 800/1939 [03:44<08:54,  2.13it/s]
 41%|████▏     | 801/1939 [03:44<09:02,  2.10it/s]
 41%|████▏     | 803/1939 [03:45<06:10,  3.07it/s]
 41%|████▏     | 804/1939 [03:46<08:51,  2.14it/s]
 42%|████▏     | 805/1939 [03:46<09:20,  2.02it/s]
 42%|████▏     | 806/1939 [03:47<09:31,  1.98it/s]
 42%|████▏     | 808/1939 [03:47<06:16,  3.00it/s]
 42%|████▏     | 809/1939 [03:47<06:44,  2.79it/s]
 42%|████▏     | 810/1939 [03:48<05:38,  3.33it/s]
 42%|████▏     | 812/1939 [03:48<05:42,  3.30it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 274.32it/s]
 34%|███▎      | 101/300 [09:41<5:36:02, 101.32s/it]

[[np.int64(0), False, 9], [np.int64(1), False, 8], [np.int64(2), False, 13], [np.int64(3), False, 10], [np.int64(4), False, 0], [np.int64(5), False, 6], [np.int64(6), False, 0], [np.int64(7), False, 1], [np.int64(11), False, 6], [np.int64(12), False, 1], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.2943, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6848, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(13.2931, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0733, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [09:41<4:27:07, 80.95s/it]

tensor(13.3251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4251, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [09:41<2:47:58, 51.42s/it]

tensor(13.3906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6629, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4722, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8018, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.5423, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8458, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [09:41<1:49:22, 33.83s/it]

tensor(13.5729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8410, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.5565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8948, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [09:42<1:12:45, 22.74s/it]

tensor(13.5072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9883, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [09:42<49:05, 15.50s/it]

tensor(13.4515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.4081, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0889, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [09:42<33:27, 10.68s/it]

tensor(13.3817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0974, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0818, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.3303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0909, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [09:42<22:57,  7.40s/it]

tensor(13.2985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1291, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [09:42<15:50,  5.17s/it]

tensor(13.2743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1770, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2189, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2596, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2433, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [09:43<10:59,  3.62s/it]

tensor(13.2557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2868, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3156, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [09:43<07:39,  2.55s/it]

tensor(13.2267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3453, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [09:43<05:22,  1.81s/it]

tensor(13.2069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3696, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3878, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4064, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [09:43<03:47,  1.29s/it]

tensor(13.1714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4351, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4486, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [09:43<02:42,  1.07it/s]

tensor(13.1473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4681, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [09:44<01:57,  1.47it/s]

tensor(13.1325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4927, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5181, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5462, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [09:44<01:26,  1.98it/s]

tensor(13.0940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0821, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5879, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [09:44<01:04,  2.61it/s]

tensor(13.0699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5943, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [09:44<00:49,  3.37it/s]

tensor(13.0580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6082, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6035, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6181, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [09:44<00:38,  4.23it/s]

tensor(13.0293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6270, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6304, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [09:45<00:31,  5.15it/s]

tensor(13.0143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6359, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [09:45<00:26,  6.07it/s]

tensor(13.0058, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6453, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6532, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6621, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [09:45<00:22,  6.94it/s]

tensor(12.9818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6629, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6748, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [09:45<00:20,  7.69it/s]

tensor(12.9682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6784, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [09:45<00:18,  8.33it/s]

tensor(12.9613, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6822, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6908, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6948, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [09:46<00:17,  8.83it/s]

tensor(12.9408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6970, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6991, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [09:46<00:16,  9.22it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([130, 464, 153,  83,  72, 119, 325, 137,  55,  29, 124,  24,  55, 169])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:40, 19.35it/s]
  0%|          | 5/1939 [00:00<01:23, 23.15it/s]
  1%|          | 10/1939 [00:00<00:56, 34.00it/s]
  1%|          | 17/1939 [00:00<00:40, 47.14it/s]
  1%|          | 24/1939 [00:00<00:36, 53.11it/s]
  2%|▏         | 30/1939 [00:00<00:41, 45.87it/s]
  2%|▏         | 35/1939 [00:00<00:41, 46.30it/s]
  2%|▏         | 41/1939 [00:01<00:58, 32.42it/s]
  2%|▏         | 45/1939 [00:01<01:22, 23.08it/s]
  3%|▎         | 49/1939 [00:01<01:29, 21.19it/s]
  3%|▎         | 52/1939 [00:01<01:29, 21.15it/s]
  3%|▎         | 55/1939 [00:02<02:27, 12.80it/s]
  3%|▎         | 57/1939 [00:02<02:44, 11.45it/s]
  3%|▎         | 59/1939 [00:03<04:22,  7.15it/s]
  3%|▎         | 62/1939 [00:03<03:26,  9.08it/s]
  3%|▎         | 66/1939 [00:03<03:18,  9.43it/s]
  4%|▎         | 68/1939 [00:03<02:58, 10.47it/s]
  4%|▎         | 70/1939 [00:04<03:40,  8.49it/s]
  4%|▎         | 72/1939 [00:04<04:21,  7.15it/s]
  4%|▍         | 73/1939 [00:05<05:21,  5.80it/s]
  4%|▍         | 77/1939 [00:05<03:20,  9.31it/s]
  4%|▍         | 79/1939 [00:05<04:27,  6.96it/s]
  4%|▍         | 81/1939 [00:06<05:25,  5.71it/s]
  4%|▍         | 82/1939 [00:06<05:26,  5.69it/s]
  4%|▍         | 83/1939 [00:06<05:30,  5.61it/s]
  4%|▍         | 84/1939 [00:06<06:52,  4.50it/s]
  4%|▍         | 86/1939 [00:07<06:45,  4.57it/s]
  4%|▍         | 87/1939 [00:07<06:33,  4.70it/s]
  5%|▍         | 89/1939 [00:07<04:41,  6.57it/s]
  5%|▍         | 94/1939 [00:08<03:30,  8.76it/s]
  5%|▍         | 96/1939 [00:08<03:30,  8.74it/s]
  5%|▌         | 99/1939 [00:08<02:45, 11.13it/s]
  5%|▌         | 101/1939 [00:09<04:06,  7.47it/s]
  5%|▌         | 103/1939 [00:09<03:26,  8.90it/s]
  5%|▌         | 105/1939 [00:09<03:32,  8.62it/s]
  6%|▌         | 107/1939 [00:09<03:45,  8.14it/s]
  6%|▌         | 109/1939 [00:09<03:10,  9.60it/s]
  6%|▌         | 111/1939 [00:10<04:14,  7.19it/s]
  6%|▌         | 114/1939 [00:10<03:48,  7.99it/s]
  6%|▌         | 115/1939 [00:10<04:01,  7.55it/s]
  6%|▌         | 117/1939 [00:10<03:24,  8.91it/s]
  6%|▌         | 119/1939 [00:11<03:56,  7.69it/s]
  6%|▌         | 120/1939 [00:11<05:02,  6.02it/s]
  6%|▌         | 121/1939 [00:11<04:56,  6.13it/s]
  6%|▋         | 124/1939 [00:11<03:19,  9.12it/s]
  6%|▋         | 126/1939 [00:12<03:07,  9.69it/s]
  7%|▋         | 128/1939 [00:12<03:31,  8.55it/s]
  7%|▋         | 130/1939 [00:12<03:12,  9.38it/s]
  7%|▋         | 132/1939 [00:12<03:38,  8.29it/s]
 50%|█████     | 150/300 [10:03<00:16,  9.22it/s]]
  7%|▋         | 136/1939 [00:13<03:24,  8.81it/s]
  7%|▋         | 137/1939 [00:13<03:46,  7.97it/s]
  7%|▋         | 138/1939 [00:13<03:59,  7.53it/s]
  7%|▋         | 139/1939 [00:13<04:23,  6.84it/s]
  7%|▋         | 141/1939 [00:13<03:50,  7.80it/s]
  7%|▋         | 142/1939 [00:14<04:23,  6.83it/s]
  7%|▋         | 144/1939 [00:14<04:55,  6.07it/s]
  7%|▋         | 145/1939 [00:14<05:12,  5.74it/s]
  8%|▊         | 146/1939 [00:15<06:40,  4.48it/s]
  8%|▊         | 148/1939 [00:15<04:54,  6.08it/s]
  8%|▊         | 149/1939 [00:15<05:01,  5.94it/s]
  8%|▊         | 151/1939 [00:15<05:06,  5.83it/s]
  8%|▊         | 153/1939 [00:16<04:29,  6.62it/s]
  8%|▊         | 155/1939 [00:16<03:36,  8.24it/s]
  8%|▊         | 157/1939 [00:16<03:29,  8.50it/s]
  8%|▊         | 158/1939 [00:16<04:12,  7.05it/s]
  8%|▊         | 159/1939 [00:16<04:12,  7.04it/s]
  8%|▊         | 160/1939 [00:16<04:39,  6.36it/s]
  8%|▊         | 161/1939 [00:17<04:35,  6.45it/s]
  8%|▊         | 162/1939 [00:17<04:41,  6.30it/s]
  8%|▊         | 163/1939 [00:17<04:37,  6.40it/s]
  8%|▊         | 164/1939 [00:17<05:04,  5.84it/s]
  9%|▊         | 165/1939 [00:17<05:35,  5.28it/s]
  9%|▊         | 168/1939 [00:17<03:07,  9.44it/s]
  9%|▉         | 176/1939 [00:18<01:17, 22.89it/s]
  9%|▉         | 182/1939 [00:18<01:39, 17.57it/s]
 10%|▉         | 185/1939 [00:18<01:31, 19.10it/s]
 10%|▉         | 192/1939 [00:18<01:03, 27.43it/s]
 10%|█         | 199/1939 [00:19<01:05, 26.73it/s]
 10%|█         | 203/1939 [00:19<02:11, 13.23it/s]
 11%|█         | 206/1939 [00:20<03:12,  9.00it/s]
 11%|█         | 208/1939 [00:21<03:43,  7.75it/s]
 11%|█         | 210/1939 [00:21<03:59,  7.21it/s]
 11%|█         | 212/1939 [00:21<04:00,  7.20it/s]
 11%|█         | 214/1939 [00:21<03:58,  7.23it/s]
 11%|█         | 215/1939 [00:22<05:06,  5.62it/s]
 11%|█         | 217/1939 [00:22<04:08,  6.93it/s]
 11%|█▏        | 219/1939 [00:23<05:08,  5.58it/s]
 11%|█▏        | 220/1939 [00:23<05:50,  4.91it/s]
 11%|█▏        | 222/1939 [00:23<05:16,  5.43it/s]
 12%|█▏        | 224/1939 [00:23<05:03,  5.65it/s]
 12%|█▏        | 225/1939 [00:24<05:47,  4.93it/s]
 12%|█▏        | 227/1939 [00:24<05:43,  4.99it/s]
 12%|█▏        | 228/1939 [00:24<05:29,  5.20it/s]
 12%|█▏        | 229/1939 [00:24<05:13,  5.46it/s]
 12%|█▏        | 231/1939 [00:25<03:50,  7.42it/s]
 12%|█▏        | 232/1939 [00:25<04:40,  6.09it/s]
 12%|█▏        | 233/1939 [00:25<06:05,  4.67it/s]
 12%|█▏        | 234/1939 [00:26<06:53,  4.12it/s]
 12%|█▏        | 236/1939 [00:26<05:35,  5.08it/s]
 12%|█▏        | 237/1939 [00:26<05:24,  5.25it/s]
 12%|█▏        | 239/1939 [00:26<04:53,  5.79it/s]
 12%|█▏        | 240/1939 [00:26<04:35,  6.17it/s]
 12%|█▏        | 241/1939 [00:27<04:12,  6.71it/s]
 12%|█▏        | 242/1939 [00:27<05:22,  5.26it/s]
 13%|█▎        | 243/1939 [00:27<04:53,  5.78it/s]
 13%|█▎        | 244/1939 [00:27<04:37,  6.10it/s]
 13%|█▎        | 245/1939 [00:27<05:17,  5.33it/s]
 13%|█▎        | 246/1939 [00:28<05:45,  4.90it/s]
 13%|█▎        | 247/1939 [00:28<05:37,  5.02it/s]
 13%|█▎        | 250/1939 [00:28<03:21,  8.38it/s]
 13%|█▎        | 252/1939 [00:28<03:01,  9.28it/s]
 13%|█▎        | 254/1939 [00:28<02:35, 10.83it/s]
 13%|█▎        | 257/1939 [00:29<03:04,  9.14it/s]
 13%|█▎        | 259/1939 [00:29<02:56,  9.52it/s]
 13%|█▎        | 261/1939 [00:29<03:09,  8.88it/s]
 14%|█▎        | 263/1939 [00:29<03:07,  8.95it/s]
 14%|█▎        | 264/1939 [00:30<03:33,  7.86it/s]
 14%|█▎        | 266/1939 [00:30<02:58,  9.39it/s]
 14%|█▍        | 268/1939 [00:30<02:43, 10.23it/s]
 14%|█▍        | 270/1939 [00:30<02:48,  9.93it/s]
 14%|█▍        | 272/1939 [00:30<02:21, 11.76it/s]
 14%|█▍        | 274/1939 [00:31<03:38,  7.63it/s]
 14%|█▍        | 276/1939 [00:31<03:03,  9.04it/s]
 14%|█▍        | 281/1939 [00:31<02:38, 10.45it/s]
 15%|█▍        | 283/1939 [00:31<02:24, 11.47it/s]
 15%|█▍        | 285/1939 [00:32<03:03,  8.99it/s]
 15%|█▍        | 287/1939 [00:32<03:01,  9.13it/s]
 15%|█▍        | 289/1939 [00:32<03:05,  8.88it/s]
 15%|█▌        | 292/1939 [00:32<02:22, 11.52it/s]
 15%|█▌        | 294/1939 [00:32<02:35, 10.57it/s]
 15%|█▌        | 296/1939 [00:33<03:22,  8.11it/s]
 15%|█▌        | 298/1939 [00:33<03:12,  8.51it/s]
 15%|█▌        | 300/1939 [00:33<03:33,  7.66it/s]
 16%|█▌        | 303/1939 [00:34<02:58,  9.18it/s]
 16%|█▌        | 305/1939 [00:34<02:54,  9.36it/s]
 16%|█▌        | 307/1939 [00:34<03:41,  7.37it/s]
 16%|█▌        | 308/1939 [00:34<03:54,  6.96it/s]
 16%|█▌        | 310/1939 [00:34<03:06,  8.73it/s]
 16%|█▌        | 312/1939 [00:35<03:08,  8.61it/s]
 16%|█▌        | 314/1939 [00:35<03:19,  8.14it/s]
 16%|█▌        | 315/1939 [00:35<03:55,  6.89it/s]
 16%|█▋        | 316/1939 [00:35<04:19,  6.26it/s]
 16%|█▋        | 317/1939 [00:36<04:19,  6.24it/s]
 16%|█▋        | 318/1939 [00:36<04:29,  6.02it/s]
 16%|█▋        | 319/1939 [00:36<04:38,  5.81it/s]
 17%|█▋        | 320/1939 [00:36<04:38,  5.81it/s]
 17%|█▋        | 321/1939 [00:36<05:31,  4.89it/s]
 17%|█▋        | 322/1939 [00:37<05:03,  5.33it/s]
 17%|█▋        | 324/1939 [00:37<03:25,  7.85it/s]
 17%|█▋        | 327/1939 [00:37<03:01,  8.90it/s]
 17%|█▋        | 331/1939 [00:37<01:59, 13.47it/s]
 17%|█▋        | 333/1939 [00:37<02:13, 12.04it/s]
 17%|█▋        | 336/1939 [00:37<01:46, 15.12it/s]
 18%|█▊        | 344/1939 [00:38<00:57, 27.86it/s]
 18%|█▊        | 351/1939 [00:38<01:09, 22.95it/s]
 18%|█▊        | 355/1939 [00:38<01:33, 16.90it/s]
 18%|█▊        | 358/1939 [00:39<01:42, 15.44it/s]
 19%|█▊        | 361/1939 [00:39<02:13, 11.86it/s]
 19%|█▊        | 363/1939 [00:39<02:20, 11.22it/s]
 19%|█▉        | 366/1939 [00:40<02:15, 11.57it/s]
 19%|█▉        | 368/1939 [00:40<03:54,  6.70it/s]
 19%|█▉        | 370/1939 [00:41<03:53,  6.72it/s]
 19%|█▉        | 372/1939 [00:41<03:52,  6.75it/s]
 19%|█▉        | 373/1939 [00:41<04:44,  5.50it/s]
 19%|█▉        | 375/1939 [00:42<05:08,  5.07it/s]
 19%|█▉        | 376/1939 [00:42<05:52,  4.43it/s]
 19%|█▉        | 377/1939 [00:42<06:29,  4.01it/s]
 19%|█▉        | 378/1939 [00:43<06:15,  4.16it/s]
 20%|█▉        | 380/1939 [00:43<05:03,  5.14it/s]
 20%|█▉        | 381/1939 [00:43<06:09,  4.21it/s]
 20%|█▉        | 382/1939 [00:43<06:00,  4.32it/s]
 20%|█▉        | 384/1939 [00:44<05:46,  4.48it/s]
 20%|█▉        | 385/1939 [00:44<06:38,  3.90it/s]
 20%|█▉        | 387/1939 [00:45<05:18,  4.87it/s]
 20%|██        | 388/1939 [00:45<06:24,  4.04it/s]
 20%|██        | 389/1939 [00:45<06:03,  4.26it/s]
 20%|██        | 390/1939 [00:45<06:59,  3.69it/s]
 20%|██        | 391/1939 [00:46<06:35,  3.91it/s]
 20%|██        | 392/1939 [00:46<05:58,  4.31it/s]
 20%|██        | 393/1939 [00:46<05:24,  4.76it/s]
 20%|██        | 394/1939 [00:46<05:22,  4.78it/s]
 20%|██        | 395/1939 [00:47<06:31,  3.94it/s]
 20%|██        | 396/1939 [00:47<07:25,  3.46it/s]
 21%|██        | 398/1939 [00:47<05:30,  4.66it/s]
 21%|██        | 400/1939 [00:47<03:52,  6.63it/s]
 21%|██        | 404/1939 [00:48<03:11,  8.00it/s]
 21%|██        | 405/1939 [00:48<04:08,  6.16it/s]
 21%|██        | 407/1939 [00:48<03:55,  6.50it/s]
 21%|██        | 409/1939 [00:48<03:09,  8.06it/s]
 21%|██        | 411/1939 [00:49<03:34,  7.12it/s]
 21%|██        | 412/1939 [00:49<03:44,  6.79it/s]
 21%|██▏       | 415/1939 [00:49<03:25,  7.42it/s]
 21%|██▏       | 416/1939 [00:50<03:47,  6.71it/s]
 22%|██▏       | 417/1939 [00:50<03:38,  6.97it/s]
 22%|██▏       | 419/1939 [00:50<03:01,  8.38it/s]
 22%|██▏       | 422/1939 [00:50<02:20, 10.81it/s]
 22%|██▏       | 425/1939 [00:50<01:52, 13.45it/s]
 22%|██▏       | 427/1939 [00:50<02:00, 12.51it/s]
 22%|██▏       | 429/1939 [00:51<02:05, 12.03it/s]
 22%|██▏       | 431/1939 [00:51<01:56, 12.94it/s]
 23%|██▎       | 437/1939 [00:51<01:07, 22.20it/s]
 23%|██▎       | 441/1939 [00:51<01:31, 16.39it/s]
 23%|██▎       | 444/1939 [00:51<01:24, 17.76it/s]
 23%|██▎       | 450/1939 [00:51<01:00, 24.71it/s]
 23%|██▎       | 454/1939 [00:52<01:34, 15.79it/s]
 24%|██▎       | 457/1939 [00:52<01:28, 16.80it/s]
 24%|██▍       | 463/1939 [00:52<01:03, 23.36it/s]
 24%|██▍       | 467/1939 [00:52<01:10, 20.89it/s]
 24%|██▍       | 470/1939 [00:53<01:10, 20.85it/s]
 25%|██▍       | 476/1939 [00:53<00:53, 27.40it/s]
 25%|██▍       | 483/1939 [00:53<00:40, 35.54it/s]
 25%|██▌       | 488/1939 [00:53<00:38, 37.52it/s]
 25%|██▌       | 493/1939 [00:54<02:00, 12.02it/s]
 26%|██▌       | 497/1939 [00:54<02:19, 10.34it/s]
 26%|██▌       | 500/1939 [00:55<02:15, 10.62it/s]
 26%|██▌       | 503/1939 [00:55<01:57, 12.18it/s]
 26%|██▌       | 506/1939 [00:55<01:50, 13.01it/s]
 26%|██▋       | 509/1939 [00:55<01:33, 15.25it/s]
 26%|██▋       | 513/1939 [00:55<01:16, 18.63it/s]
 27%|██▋       | 517/1939 [00:55<01:04, 21.95it/s]
 27%|██▋       | 521/1939 [00:56<00:57, 24.50it/s]
 27%|██▋       | 524/1939 [00:56<00:58, 24.08it/s]
 27%|██▋       | 528/1939 [00:56<00:51, 27.59it/s]
 27%|██▋       | 533/1939 [00:56<00:42, 32.81it/s]
 28%|██▊       | 537/1939 [00:56<01:14, 18.93it/s]
 28%|██▊       | 540/1939 [00:57<02:04, 11.20it/s]
 28%|██▊       | 543/1939 [00:57<01:49, 12.81it/s]
 28%|██▊       | 546/1939 [00:57<01:46, 13.10it/s]
 28%|██▊       | 548/1939 [00:57<01:56, 11.98it/s]
 28%|██▊       | 550/1939 [00:58<01:46, 13.07it/s]
 28%|██▊       | 552/1939 [00:58<02:52,  8.06it/s]
 29%|██▊       | 554/1939 [00:58<02:26,  9.48it/s]
 29%|██▊       | 556/1939 [00:59<02:41,  8.56it/s]
 29%|██▉       | 558/1939 [00:59<02:29,  9.26it/s]
 29%|██▉       | 561/1939 [00:59<02:00, 11.41it/s]
 29%|██▉       | 563/1939 [00:59<02:15, 10.17it/s]
 29%|██▉       | 566/1939 [00:59<01:46, 12.93it/s]
 29%|██▉       | 568/1939 [00:59<02:05, 10.93it/s]
 29%|██▉       | 570/1939 [01:00<01:50, 12.40it/s]
 29%|██▉       | 572/1939 [01:00<02:08, 10.64it/s]
 30%|██▉       | 574/1939 [01:00<02:02, 11.17it/s]
 30%|██▉       | 576/1939 [01:00<02:44,  8.29it/s]
 30%|██▉       | 578/1939 [01:01<02:18,  9.82it/s]
 30%|██▉       | 580/1939 [01:01<02:16,  9.95it/s]
 30%|███       | 582/1939 [01:01<02:19,  9.74it/s]
 30%|███       | 584/1939 [01:01<02:15,  9.99it/s]
 30%|███       | 586/1939 [01:01<02:24,  9.39it/s]
 30%|███       | 588/1939 [01:01<02:07, 10.62it/s]
 30%|███       | 590/1939 [01:02<02:03, 10.88it/s]
 31%|███       | 592/1939 [01:02<04:02,  5.55it/s]
 31%|███       | 593/1939 [01:03<04:10,  5.37it/s]
 31%|███       | 595/1939 [01:03<03:16,  6.84it/s]
 31%|███       | 596/1939 [01:03<03:25,  6.53it/s]
 31%|███       | 598/1939 [01:03<02:57,  7.53it/s]
 31%|███       | 599/1939 [01:03<03:19,  6.73it/s]
 31%|███       | 600/1939 [01:04<03:37,  6.16it/s]
 31%|███       | 601/1939 [01:04<03:52,  5.76it/s]
 31%|███       | 603/1939 [01:04<03:05,  7.21it/s]
 31%|███       | 605/1939 [01:04<03:02,  7.33it/s]
 31%|███▏      | 607/1939 [01:05<03:27,  6.43it/s]
 31%|███▏      | 609/1939 [01:05<03:17,  6.73it/s]
 32%|███▏      | 611/1939 [01:05<03:24,  6.50it/s]
 32%|███▏      | 612/1939 [01:05<03:38,  6.08it/s]
 32%|███▏      | 613/1939 [01:06<03:39,  6.04it/s]
 32%|███▏      | 614/1939 [01:06<03:26,  6.42it/s]
 32%|███▏      | 615/1939 [01:06<03:49,  5.78it/s]
 32%|███▏      | 616/1939 [01:06<03:48,  5.78it/s]
 32%|███▏      | 617/1939 [01:06<03:54,  5.64it/s]
 32%|███▏      | 618/1939 [01:07<05:15,  4.19it/s]
 32%|███▏      | 619/1939 [01:07<06:07,  3.59it/s]
 32%|███▏      | 620/1939 [01:07<05:15,  4.18it/s]
 32%|███▏      | 622/1939 [01:07<03:26,  6.38it/s]
 32%|███▏      | 627/1939 [01:07<01:36, 13.58it/s]
 32%|███▏      | 630/1939 [01:08<02:00, 10.83it/s]
 33%|███▎      | 632/1939 [01:08<02:11,  9.96it/s]
 33%|███▎      | 634/1939 [01:08<01:54, 11.42it/s]
 33%|███▎      | 636/1939 [01:09<02:30,  8.68it/s]
 33%|███▎      | 638/1939 [01:09<03:10,  6.82it/s]
 33%|███▎      | 640/1939 [01:09<03:04,  7.03it/s]
 33%|███▎      | 641/1939 [01:10<03:26,  6.28it/s]
 33%|███▎      | 643/1939 [01:10<03:55,  5.50it/s]
 33%|███▎      | 645/1939 [01:10<03:01,  7.15it/s]
 33%|███▎      | 647/1939 [01:10<02:39,  8.09it/s]
 33%|███▎      | 649/1939 [01:10<02:25,  8.88it/s]
 34%|███▎      | 651/1939 [01:11<02:21,  9.08it/s]
 34%|███▎      | 653/1939 [01:11<02:34,  8.32it/s]
 34%|███▎      | 654/1939 [01:11<02:39,  8.03it/s]
 34%|███▍      | 656/1939 [01:11<02:16,  9.43it/s]
 34%|███▍      | 658/1939 [01:11<02:16,  9.38it/s]
 34%|███▍      | 660/1939 [01:12<01:54, 11.16it/s]
 34%|███▍      | 663/1939 [01:12<01:32, 13.78it/s]
 34%|███▍      | 665/1939 [01:12<02:40,  7.96it/s]
 34%|███▍      | 667/1939 [01:13<03:13,  6.56it/s]
 34%|███▍      | 668/1939 [01:13<04:06,  5.16it/s]
 35%|███▍      | 671/1939 [01:13<02:45,  7.67it/s]
 35%|███▍      | 673/1939 [01:14<04:15,  4.96it/s]
 35%|███▍      | 676/1939 [01:14<03:07,  6.73it/s]
 35%|███▍      | 678/1939 [01:14<02:50,  7.41it/s]
 35%|███▌      | 680/1939 [01:14<02:35,  8.08it/s]
 35%|███▌      | 683/1939 [01:15<02:03, 10.19it/s]
 35%|███▌      | 686/1939 [01:15<01:42, 12.21it/s]
 35%|███▌      | 688/1939 [01:15<02:10,  9.61it/s]
 36%|███▌      | 690/1939 [01:15<02:21,  8.83it/s]
 36%|███▌      | 692/1939 [01:16<03:09,  6.60it/s]
 36%|███▌      | 695/1939 [01:16<02:17,  9.04it/s]
 36%|███▌      | 700/1939 [01:16<01:24, 14.63it/s]
 36%|███▋      | 707/1939 [01:16<00:55, 22.15it/s]
 37%|███▋      | 711/1939 [01:17<01:08, 18.05it/s]
 37%|███▋      | 714/1939 [01:17<01:10, 17.49it/s]
 37%|███▋      | 721/1939 [01:17<00:47, 25.79it/s]
 37%|███▋      | 725/1939 [01:17<00:53, 22.61it/s]
 38%|███▊      | 729/1939 [01:17<00:50, 24.02it/s]
 38%|███▊      | 732/1939 [01:18<01:46, 11.33it/s]
 38%|███▊      | 735/1939 [01:19<02:52,  6.98it/s]
 38%|███▊      | 738/1939 [01:19<02:50,  7.05it/s]
 38%|███▊      | 740/1939 [01:20<02:48,  7.12it/s]
 38%|███▊      | 742/1939 [01:20<03:05,  6.44it/s]
 38%|███▊      | 745/1939 [01:20<02:38,  7.54it/s]
 39%|███▊      | 747/1939 [01:21<03:46,  5.26it/s]
 39%|███▊      | 749/1939 [01:21<03:25,  5.79it/s]
 39%|███▊      | 751/1939 [01:22<03:05,  6.39it/s]
 39%|███▉      | 752/1939 [01:22<03:45,  5.27it/s]
 39%|███▉      | 754/1939 [01:22<03:53,  5.07it/s]
 39%|███▉      | 755/1939 [01:23<04:34,  4.31it/s]
 39%|███▉      | 756/1939 [01:23<05:12,  3.79it/s]
 39%|███▉      | 757/1939 [01:23<04:57,  3.98it/s]
 39%|███▉      | 759/1939 [01:24<04:04,  4.83it/s]
 39%|███▉      | 760/1939 [01:24<04:45,  4.13it/s]
 39%|███▉      | 761/1939 [01:24<04:20,  4.52it/s]
 39%|███▉      | 763/1939 [01:24<03:27,  5.67it/s]
 39%|███▉      | 764/1939 [01:25<03:53,  5.03it/s]
 40%|███▉      | 766/1939 [01:25<03:44,  5.22it/s]
 40%|███▉      | 767/1939 [01:25<04:18,  4.53it/s]
 40%|███▉      | 769/1939 [01:26<03:37,  5.38it/s]
 40%|███▉      | 770/1939 [01:26<03:28,  5.61it/s]
 40%|███▉      | 771/1939 [01:26<03:41,  5.28it/s]
 40%|███▉      | 772/1939 [01:26<03:46,  5.16it/s]
 40%|███▉      | 774/1939 [01:27<03:53,  4.99it/s]
 40%|████      | 776/1939 [01:27<03:38,  5.32it/s]
 40%|████      | 777/1939 [01:27<03:42,  5.22it/s]
 40%|████      | 779/1939 [01:27<03:30,  5.50it/s]
 40%|████      | 780/1939 [01:28<03:38,  5.32it/s]
 40%|████      | 781/1939 [01:28<03:36,  5.34it/s]
 40%|████      | 783/1939 [01:28<02:36,  7.38it/s]
 40%|████      | 784/1939 [01:28<03:09,  6.11it/s]
 40%|████      | 785/1939 [01:29<03:51,  4.97it/s]
 41%|████      | 787/1939 [01:29<03:38,  5.27it/s]
 41%|████      | 789/1939 [01:29<03:06,  6.17it/s]
 41%|████      | 791/1939 [01:29<02:44,  7.00it/s]
 41%|████      | 793/1939 [01:29<02:09,  8.87it/s]
 41%|████      | 795/1939 [01:30<02:43,  6.98it/s]
 41%|████      | 796/1939 [01:30<03:04,  6.18it/s]
 41%|████      | 797/1939 [01:30<02:55,  6.50it/s]
 41%|████      | 798/1939 [01:30<03:02,  6.24it/s]
 41%|████▏     | 800/1939 [01:31<02:31,  7.50it/s]
 41%|████▏     | 802/1939 [01:31<02:04,  9.13it/s]
 41%|████▏     | 804/1939 [01:31<03:07,  6.06it/s]
 42%|████▏     | 805/1939 [01:31<03:18,  5.70it/s]
 42%|████▏     | 806/1939 [01:32<03:05,  6.11it/s]
 42%|████▏     | 808/1939 [01:32<02:44,  6.90it/s]
 42%|████▏     | 809/1939 [01:32<02:55,  6.44it/s]
 42%|████▏     | 810/1939 [01:32<03:52,  4.85it/s]
 42%|████▏     | 812/1939 [01:33<03:57,  4.75it/s]
 42%|████▏     | 813/1939 [01:33<04:46,  3.93it/s]
 42%|████▏     | 814/1939 [01:34<05:22,  3.49it/s]
 42%|████▏     | 816/1939 [01:34<04:56,  3.79it/s]
 42%|████▏     | 817/1939 [01:34<05:30,  3.40it/s]
 42%|████▏     | 818/1939 [01:35<05:04,  3.68it/s]
 42%|████▏     | 819/1939 [01:35<05:34,  3.35it/s]
 42%|████▏     | 820/1939 [01:35<05:57,  3.13it/s]
 42%|████▏     | 821/1939 [01:36<05:22,  3.47it/s]
 42%|████▏     | 822/1939 [01:36<04:59,  3.73it/s]
 42%|████▏     | 823/1939 [01:36<05:54,  3.15it/s]
 42%|████▏     | 824/1939 [01:37<06:14,  2.98it/s]
 43%|████▎     | 825/1939 [01:37<05:57,  3.11it/s]
 43%|████▎     | 826/1939 [01:37<05:05,  3.64it/s]
 43%|████▎     | 828/1939 [01:37<03:50,  4.82it/s]
 43%|████▎     | 829/1939 [01:38<03:57,  4.66it/s]
 43%|████▎     | 830/1939 [01:38<03:44,  4.95it/s]
 43%|████▎     | 832/1939 [01:38<02:33,  7.23it/s]
 43%|████▎     | 833/1939 [01:38<02:28,  7.45it/s]
 43%|████▎     | 835/1939 [01:38<01:57,  9.42it/s]
 43%|████▎     | 837/1939 [01:38<01:59,  9.22it/s]
 43%|████▎     | 839/1939 [01:39<01:56,  9.45it/s]
 43%|████▎     | 841/1939 [01:39<02:53,  6.33it/s]
 44%|████▎     | 844/1939 [01:39<02:11,  8.33it/s]
 44%|████▎     | 846/1939 [01:39<01:57,  9.29it/s]
 44%|████▎     | 848/1939 [01:40<01:43, 10.50it/s]
 44%|████▍     | 850/1939 [01:40<02:04,  8.74it/s]
 44%|████▍     | 852/1939 [01:40<01:44, 10.39it/s]
 44%|████▍     | 854/1939 [01:40<01:45, 10.24it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 319.25it/s]
 50%|█████     | 151/300 [13:37<1:41:41, 40.95s/it]

[[np.int64(0), False, 13], [np.int64(1), False, 6], [np.int64(2), False, 7], [np.int64(3), False, 2], [np.int64(4), False, 7], [np.int64(5), False, 1], [np.int64(8), False, 10], [np.int64(9), False, 10], [np.int64(11), False, 2], [np.int64(12), False, 2], [np.int64(13), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9278, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2871, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.9452, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8912, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 152/300 [13:37<1:20:44, 32.73s/it]

tensor(13.0054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3184, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [13:38<1:02:20, 25.44s/it]

tensor(13.0448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1489, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [13:38<37:37, 15.57s/it]

tensor(13.0514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2044, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3804, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4278, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [13:38<23:55, 10.04s/it]

tensor(13.0491, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0373, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4158, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0373, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3991, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [13:38<15:41,  6.68s/it]

tensor(13.0109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4006, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [13:38<10:29,  4.53s/it]

tensor(12.9951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4182, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4652, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4563, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [13:38<07:07,  3.12s/it]

tensor(12.9742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4811, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [13:39<04:54,  2.18s/it]

tensor(12.9732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5046, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [13:39<03:24,  1.54s/it]

tensor(12.9614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5334, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5908, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6004, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [13:39<02:23,  1.10s/it]

tensor(12.8980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6026, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6034, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [13:39<01:42,  1.26it/s]

tensor(12.8757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6048, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [13:39<01:13,  1.72it/s]

tensor(12.8699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6088, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5747, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8535, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5826, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [13:40<00:54,  2.29it/s]

tensor(12.8480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5946, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [13:40<00:41,  3.00it/s]

tensor(12.8392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6007, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [13:40<00:31,  3.80it/s]

tensor(12.8313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6104, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8221, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6250, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6319, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [13:40<00:25,  4.69it/s]

tensor(12.8098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6404, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6416, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [13:40<00:20,  5.60it/s]

tensor(12.7987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6459, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [13:41<00:17,  6.50it/s]

tensor(12.7905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7835, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6469, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [13:41<00:15,  7.29it/s]

tensor(12.7729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6501, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [13:41<00:13,  7.97it/s]

tensor(12.7620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6501, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [13:41<00:12,  8.54it/s]

tensor(12.7575, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7529, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6498, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6516, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [13:41<00:11,  8.97it/s]

tensor(12.7431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6539, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6561, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [13:42<00:11,  9.30it/s]

tensor(12.7344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6571, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [13:42<00:10,  9.55it/s]

tensor(12.7297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6571, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6583, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [13:42<00:10,  9.46it/s]

tensor(12.7205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6637, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6640, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([197, 183,  99, 398, 126, 105, 315, 118, 179,  33,  86,  24,  29,  47])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:40, 19.22it/s]
  0%|          | 6/1939 [00:00<01:22, 23.37it/s]
  1%|          | 14/1939 [00:00<00:50, 38.47it/s]
  1%|          | 18/1939 [00:00<00:51, 37.62it/s]
  1%|          | 22/1939 [00:00<00:59, 32.01it/s]
  1%|▏         | 26/1939 [00:00<00:57, 33.48it/s]
  2%|▏         | 32/1939 [00:00<00:48, 39.43it/s]
  2%|▏         | 39/1939 [00:01<00:45, 42.15it/s]
  2%|▏         | 44/1939 [00:01<02:08, 14.71it/s]
  3%|▎         | 49/1939 [00:02<02:04, 15.18it/s]
  3%|▎         | 52/1939 [00:02<01:54, 16.47it/s]
  3%|▎         | 55/1939 [00:02<02:42, 11.57it/s]
  3%|▎         | 57/1939 [00:03<03:36,  8.70it/s]
  3%|▎         | 59/1939 [00:04<07:22,  4.25it/s]
  3%|▎         | 63/1939 [00:04<04:58,  6.28it/s]
  3%|▎         | 66/1939 [00:05<05:39,  5.51it/s]
  4%|▎         | 69/1939 [00:05<04:25,  7.03it/s]
  4%|▎         | 71/1939 [00:07<07:44,  4.02it/s]
  4%|▍         | 73/1939 [00:07<08:37,  3.61it/s]
  4%|▍         | 75/1939 [00:07<07:03,  4.40it/s]
  4%|▍         | 78/1939 [00:08<06:19,  4.91it/s]
  4%|▍         | 79/1939 [00:08<06:13,  4.98it/s]
  4%|▍         | 80/1939 [00:08<06:38,  4.66it/s]
  4%|▍         | 81/1939 [00:09<06:22,  4.86it/s]
  4%|▍         | 82/1939 [00:09<07:11,  4.30it/s]
  4%|▍         | 84/1939 [00:09<07:41,  4.02it/s]
  4%|▍         | 86/1939 [00:10<08:00,  3.86it/s]
  5%|▍         | 88/1939 [00:10<05:52,  5.26it/s]
  5%|▍         | 94/1939 [00:11<03:43,  8.26it/s]
  5%|▍         | 96/1939 [00:11<03:48,  8.07it/s]
  5%|▌         | 99/1939 [00:11<03:04, 10.00it/s]
  5%|▌         | 101/1939 [00:12<05:08,  5.95it/s]
  5%|▌         | 103/1939 [00:12<04:19,  7.07it/s]
  5%|▌         | 105/1939 [00:12<05:09,  5.92it/s]
  6%|▌         | 107/1939 [00:13<05:35,  5.46it/s]
  6%|▌         | 109/1939 [00:13<04:30,  6.77it/s]
  6%|▌         | 111/1939 [00:14<06:18,  4.83it/s]
  6%|▌         | 114/1939 [00:14<04:19,  7.03it/s]
  6%|▌         | 116/1939 [00:14<06:01,  5.04it/s]
  6%|▌         | 118/1939 [00:15<08:25,  3.60it/s]
  6%|▌         | 120/1939 [00:16<07:47,  3.89it/s]
  6%|▌         | 121/1939 [00:16<07:31,  4.03it/s]
  6%|▋         | 123/1939 [00:16<05:41,  5.31it/s]
  6%|▋         | 125/1939 [00:16<04:22,  6.91it/s]
  7%|▋         | 127/1939 [00:17<06:44,  4.48it/s]
  7%|▋         | 128/1939 [00:17<07:37,  3.96it/s]
  7%|▋         | 130/1939 [00:18<05:31,  5.45it/s]
  7%|▋         | 132/1939 [00:18<07:45,  3.88it/s]
  7%|▋         | 134/1939 [00:18<05:55,  5.08it/s]
  7%|▋         | 136/1939 [00:19<05:49,  5.15it/s]
  7%|▋         | 137/1939 [00:19<06:28,  4.63it/s]
  7%|▋         | 138/1939 [00:19<06:13,  4.82it/s]
  7%|▋         | 139/1939 [00:20<06:12,  4.83it/s]
  7%|▋         | 141/1939 [00:20<05:30,  5.45it/s]
  7%|▋         | 142/1939 [00:20<06:41,  4.48it/s]
  7%|▋         | 144/1939 [00:20<04:43,  6.34it/s]
  7%|▋         | 145/1939 [00:21<05:59,  4.99it/s]
  8%|▊         | 146/1939 [00:21<08:36,  3.47it/s]
  8%|▊         | 148/1939 [00:21<06:04,  4.91it/s]
  8%|▊         | 149/1939 [00:22<06:07,  4.87it/s]
  8%|▊         | 151/1939 [00:22<06:03,  4.91it/s]
  8%|▊         | 153/1939 [00:22<06:07,  4.87it/s]
  8%|▊         | 155/1939 [00:23<04:40,  6.36it/s]
  8%|▊         | 157/1939 [00:23<04:36,  6.43it/s]
  8%|▊         | 158/1939 [00:23<05:21,  5.54it/s]
  8%|▊         | 159/1939 [00:23<05:22,  5.51it/s]
  8%|▊         | 160/1939 [00:24<06:24,  4.63it/s]
  8%|▊         | 161/1939 [00:24<06:46,  4.37it/s]
  8%|▊         | 162/1939 [00:24<07:37,  3.88it/s]
  8%|▊         | 163/1939 [00:25<07:50,  3.78it/s]
  8%|▊         | 164/1939 [00:25<09:12,  3.21it/s]
  9%|▊         | 165/1939 [00:26<12:02,  2.45it/s]
  9%|▊         | 167/1939 [00:26<07:23,  3.99it/s]
  9%|▉         | 174/1939 [00:26<02:35, 11.34it/s]
  9%|▉         | 181/1939 [00:26<01:30, 19.41it/s]
 10%|▉         | 185/1939 [00:26<01:18, 22.45it/s]
 10%|▉         | 189/1939 [00:26<01:12, 24.19it/s]
 10%|█         | 195/1939 [00:26<00:56, 31.12it/s]
 10%|█         | 201/1939 [00:26<00:46, 37.05it/s]
 11%|█         | 206/1939 [00:28<04:04,  7.08it/s]
 11%|█         | 210/1939 [00:29<04:16,  6.74it/s]
 11%|█         | 213/1939 [00:30<04:59,  5.76it/s]
 11%|█         | 215/1939 [00:31<05:50,  4.91it/s]
 11%|█         | 217/1939 [00:31<05:03,  5.67it/s]
 11%|█▏        | 219/1939 [00:32<06:29,  4.41it/s]
 11%|█▏        | 221/1939 [00:32<06:44,  4.25it/s]
 11%|█▏        | 222/1939 [00:32<07:04,  4.04it/s]
 12%|█▏        | 224/1939 [00:33<05:53,  4.85it/s]
 12%|█▏        | 225/1939 [00:33<07:20,  3.89it/s]
 12%|█▏        | 227/1939 [00:33<05:23,  5.30it/s]
 12%|█▏        | 229/1939 [00:34<06:06,  4.67it/s]
 12%|█▏        | 231/1939 [00:34<04:40,  6.09it/s]
 12%|█▏        | 233/1939 [00:34<05:20,  5.32it/s]
 12%|█▏        | 234/1939 [00:35<05:35,  5.08it/s]
 12%|█▏        | 236/1939 [00:35<05:08,  5.53it/s]
 12%|█▏        | 237/1939 [00:35<06:31,  4.35it/s]
 12%|█▏        | 239/1939 [00:36<06:19,  4.48it/s]
 12%|█▏        | 240/1939 [00:36<06:29,  4.36it/s]
 12%|█▏        | 241/1939 [00:36<05:48,  4.87it/s]
 12%|█▏        | 242/1939 [00:37<06:49,  4.15it/s]
 13%|█▎        | 243/1939 [00:37<08:12,  3.44it/s]
 13%|█▎        | 244/1939 [00:37<08:14,  3.43it/s]
 13%|█▎        | 245/1939 [00:38<08:27,  3.34it/s]
 13%|█▎        | 246/1939 [00:38<09:00,  3.13it/s]
 13%|█▎        | 248/1939 [00:38<05:44,  4.91it/s]
 13%|█▎        | 251/1939 [00:38<03:30,  8.03it/s]
 13%|█▎        | 253/1939 [00:39<04:27,  6.31it/s]
 13%|█▎        | 255/1939 [00:39<03:38,  7.70it/s]
 13%|█▎        | 257/1939 [00:39<04:12,  6.65it/s]
 13%|█▎        | 258/1939 [00:39<04:48,  5.83it/s]
 13%|█▎        | 260/1939 [00:40<05:26,  5.14it/s]
 14%|█▎        | 262/1939 [00:40<04:10,  6.69it/s]
 14%|█▎        | 264/1939 [00:40<04:22,  6.38it/s]
 14%|█▎        | 266/1939 [00:40<03:32,  7.89it/s]
 14%|█▍        | 268/1939 [00:41<04:18,  6.46it/s]
 14%|█▍        | 270/1939 [00:41<05:00,  5.55it/s]
 14%|█▍        | 272/1939 [00:42<03:55,  7.07it/s]
 14%|█▍        | 274/1939 [00:42<06:29,  4.27it/s]
 14%|█▍        | 277/1939 [00:43<04:25,  6.27it/s]
 14%|█▍        | 281/1939 [00:43<03:13,  8.58it/s]
 15%|█▍        | 284/1939 [00:43<03:17,  8.39it/s]
 15%|█▍        | 286/1939 [00:43<03:24,  8.07it/s]
 15%|█▍        | 288/1939 [00:44<03:46,  7.27it/s]
 15%|█▍        | 290/1939 [00:44<03:13,  8.50it/s]
 15%|█▌        | 293/1939 [00:44<03:10,  8.65it/s]
 15%|█▌        | 296/1939 [00:44<02:42, 10.10it/s]
 15%|█▌        | 298/1939 [00:45<03:06,  8.80it/s]
 15%|█▌        | 300/1939 [00:45<04:05,  6.67it/s]
 16%|█▌        | 303/1939 [00:46<03:39,  7.44it/s]
 16%|█▌        | 304/1939 [00:46<04:54,  5.55it/s]
 16%|█▌        | 307/1939 [00:47<04:38,  5.87it/s]
 16%|█▌        | 308/1939 [00:47<04:30,  6.03it/s]
 16%|█▌        | 310/1939 [00:47<03:39,  7.43it/s]
 16%|█▌        | 312/1939 [00:47<03:55,  6.90it/s]
 16%|█▌        | 313/1939 [00:47<04:32,  5.97it/s]
 16%|█▌        | 315/1939 [00:48<04:15,  6.36it/s]
 16%|█▋        | 316/1939 [00:48<03:59,  6.77it/s]
 16%|█▋        | 317/1939 [00:48<04:42,  5.75it/s]
 16%|█▋        | 318/1939 [00:48<04:35,  5.88it/s]
 16%|█▋        | 319/1939 [00:48<04:58,  5.42it/s]
 17%|█▋        | 320/1939 [00:49<06:28,  4.17it/s]
 17%|█▋        | 321/1939 [00:50<10:23,  2.60it/s]
 17%|█▋        | 322/1939 [00:50<10:03,  2.68it/s]
 17%|█▋        | 324/1939 [00:50<06:10,  4.36it/s]
 17%|█▋        | 327/1939 [00:51<05:31,  4.87it/s]
 17%|█▋        | 329/1939 [00:51<04:16,  6.29it/s]
 17%|█▋        | 336/1939 [00:51<01:57, 13.65it/s]
 18%|█▊        | 343/1939 [00:51<01:13, 21.63it/s]
 18%|█▊        | 349/1939 [00:51<00:57, 27.69it/s]
 18%|█▊        | 354/1939 [00:52<01:48, 14.60it/s]
 18%|█▊        | 358/1939 [00:52<02:02, 12.88it/s]
 19%|█▊        | 361/1939 [00:53<02:20, 11.24it/s]
 19%|█▊        | 363/1939 [00:53<02:28, 10.61it/s]
 19%|█▉        | 365/1939 [00:53<02:21, 11.11it/s]
 19%|█▉        | 367/1939 [00:53<03:25,  7.64it/s]
 19%|█▉        | 369/1939 [00:54<03:45,  6.97it/s]
 19%|█▉        | 370/1939 [00:54<04:07,  6.34it/s]
 19%|█▉        | 372/1939 [00:54<04:18,  6.07it/s]
 19%|█▉        | 373/1939 [00:55<04:39,  5.61it/s]
 19%|█▉        | 375/1939 [00:55<03:43,  7.00it/s]
 19%|█▉        | 376/1939 [00:55<05:38,  4.61it/s]
 19%|█▉        | 377/1939 [00:56<06:05,  4.27it/s]
 20%|█▉        | 379/1939 [00:56<04:23,  5.92it/s]
 20%|█▉        | 380/1939 [00:56<05:29,  4.73it/s]
 20%|█▉        | 381/1939 [00:57<06:18,  4.12it/s]
 20%|█▉        | 382/1939 [00:57<06:26,  4.03it/s]
 20%|█▉        | 384/1939 [00:57<05:47,  4.48it/s]
 20%|█▉        | 385/1939 [00:58<06:33,  3.95it/s]
 20%|█▉        | 387/1939 [00:58<05:45,  4.49it/s]
 20%|██        | 388/1939 [00:58<07:36,  3.40it/s]
 20%|██        | 389/1939 [00:59<07:23,  3.50it/s]
 20%|██        | 390/1939 [00:59<07:51,  3.29it/s]
 20%|██        | 391/1939 [00:59<07:10,  3.60it/s]
 20%|██        | 393/1939 [00:59<05:05,  5.05it/s]
 20%|██        | 394/1939 [01:00<05:14,  4.92it/s]
 20%|██        | 396/1939 [01:00<04:25,  5.81it/s]
 21%|██        | 398/1939 [01:00<03:57,  6.48it/s]
 21%|██        | 400/1939 [01:00<03:04,  8.34it/s]
 21%|██        | 402/1939 [01:00<02:37,  9.77it/s]
 21%|██        | 404/1939 [01:01<02:55,  8.77it/s]
 21%|██        | 406/1939 [01:01<03:44,  6.84it/s]
 21%|██        | 407/1939 [01:02<06:14,  4.09it/s]
 21%|██        | 409/1939 [01:02<04:37,  5.50it/s]
 21%|██        | 411/1939 [01:03<05:58,  4.26it/s]
 21%|██        | 412/1939 [01:03<06:57,  3.66it/s]
 21%|██▏       | 415/1939 [01:04<06:55,  3.67it/s]
 21%|██▏       | 416/1939 [01:04<07:39,  3.31it/s]
 22%|██▏       | 418/1939 [01:04<05:36,  4.52it/s]
 22%|██▏       | 419/1939 [01:05<05:34,  4.54it/s]
 22%|██▏       | 421/1939 [01:05<04:08,  6.12it/s]
 22%|██▏       | 422/1939 [01:05<05:22,  4.70it/s]
 22%|██▏       | 423/1939 [01:05<04:44,  5.33it/s]
 22%|██▏       | 425/1939 [01:05<03:35,  7.02it/s]
 22%|██▏       | 426/1939 [01:06<04:39,  5.41it/s]
 22%|██▏       | 427/1939 [01:06<05:51,  4.30it/s]
 22%|██▏       | 428/1939 [01:06<06:27,  3.90it/s]
 22%|██▏       | 430/1939 [01:07<06:13,  4.04it/s]
 22%|██▏       | 432/1939 [01:07<04:23,  5.71it/s]
 22%|██▏       | 436/1939 [01:07<02:26, 10.25it/s]
 23%|██▎       | 438/1939 [01:07<02:09, 11.62it/s]
 23%|██▎       | 441/1939 [01:08<02:30,  9.94it/s]
 23%|██▎       | 444/1939 [01:08<02:01, 12.29it/s]
 23%|██▎       | 450/1939 [01:08<01:14, 20.04it/s]
 23%|██▎       | 453/1939 [01:08<02:18, 10.70it/s]
 24%|██▎       | 457/1939 [01:09<01:48, 13.65it/s]
 24%|██▍       | 463/1939 [01:09<01:14, 19.77it/s]
 24%|██▍       | 470/1939 [01:09<00:53, 27.36it/s]
 25%|██▍       | 476/1939 [01:09<01:14, 19.69it/s]
 25%|██▍       | 480/1939 [01:09<01:08, 21.45it/s]
 25%|██▌       | 486/1939 [01:10<00:53, 27.41it/s]
 25%|██▌       | 491/1939 [01:11<02:10, 11.09it/s]
 25%|██▌       | 494/1939 [01:11<02:28,  9.70it/s]
 26%|██▌       | 497/1939 [01:12<03:32,  6.80it/s]
 26%|██▌       | 500/1939 [01:13<03:33,  6.74it/s]
 26%|██▌       | 502/1939 [01:13<03:10,  7.53it/s]
 26%|██▌       | 505/1939 [01:13<03:14,  7.39it/s]
 26%|██▌       | 508/1939 [01:13<02:32,  9.37it/s]
 27%|██▋       | 515/1939 [01:13<01:28, 16.08it/s]
 27%|██▋       | 519/1939 [01:13<01:19, 17.77it/s]
 27%|██▋       | 525/1939 [01:14<00:59, 23.72it/s]
 27%|██▋       | 530/1939 [01:14<00:49, 28.27it/s]
 28%|██▊       | 535/1939 [01:14<00:43, 32.51it/s]
 28%|██▊       | 540/1939 [01:15<02:00, 11.57it/s]
 28%|██▊       | 544/1939 [01:15<01:43, 13.48it/s]
 28%|██▊       | 547/1939 [01:16<02:27,  9.42it/s]
 28%|██▊       | 550/1939 [01:16<02:48,  8.26it/s]
 28%|██▊       | 552/1939 [01:17<04:38,  4.98it/s]
 29%|██▊       | 555/1939 [01:17<03:34,  6.46it/s]
 29%|██▊       | 557/1939 [01:18<03:49,  6.02it/s]
 29%|██▉       | 559/1939 [01:18<04:10,  5.52it/s]
 29%|██▉       | 561/1939 [01:19<04:24,  5.20it/s]
 29%|██▉       | 562/1939 [01:19<05:15,  4.36it/s]
 29%|██▉       | 564/1939 [01:19<04:02,  5.66it/s]
 29%|██▉       | 568/1939 [01:20<03:17,  6.96it/s]
 29%|██▉       | 571/1939 [01:20<03:24,  6.71it/s]
 29%|██▉       | 572/1939 [01:21<05:07,  4.44it/s]
 30%|██▉       | 574/1939 [01:22<06:06,  3.73it/s]
 30%|██▉       | 575/1939 [01:22<07:37,  2.98it/s]
 30%|██▉       | 576/1939 [01:23<09:22,  2.42it/s]
 30%|██▉       | 579/1939 [01:24<07:44,  2.93it/s]
 30%|██▉       | 580/1939 [01:25<09:22,  2.42it/s]
 30%|███       | 582/1939 [01:25<08:01,  2.82it/s]
 30%|███       | 584/1939 [01:26<08:03,  2.80it/s]
 30%|███       | 586/1939 [01:26<08:04,  2.79it/s]
 30%|███       | 588/1939 [01:27<05:55,  3.80it/s]
 30%|███       | 589/1939 [01:27<06:28,  3.48it/s]
 30%|███       | 590/1939 [01:28<08:24,  2.68it/s]
 30%|███       | 591/1939 [01:28<10:05,  2.23it/s]
 31%|███       | 592/1939 [01:29<11:15,  1.99it/s]
 31%|███       | 593/1939 [01:30<11:01,  2.04it/s]
 31%|███       | 595/1939 [01:30<08:48,  2.55it/s]
 31%|███       | 596/1939 [01:31<10:34,  2.12it/s]
 31%|███       | 599/1939 [01:32<08:13,  2.72it/s]
 31%|███       | 600/1939 [01:32<09:31,  2.34it/s]
 31%|███       | 601/1939 [01:33<09:36,  2.32it/s]
 31%|███       | 603/1939 [01:34<09:27,  2.36it/s]
 31%|███       | 605/1939 [01:34<09:20,  2.38it/s]
 31%|███▏      | 607/1939 [01:35<08:58,  2.47it/s]
 31%|███▏      | 608/1939 [01:36<09:11,  2.41it/s]
 31%|███▏      | 609/1939 [01:36<09:41,  2.29it/s]
 32%|███▏      | 611/1939 [01:36<07:20,  3.01it/s]
 32%|███▏      | 612/1939 [01:37<07:55,  2.79it/s]
 32%|███▏      | 613/1939 [01:37<07:24,  2.98it/s]
 32%|███▏      | 614/1939 [01:38<07:56,  2.78it/s]
 32%|███▏      | 615/1939 [01:38<08:24,  2.63it/s]
 32%|███▏      | 616/1939 [01:38<08:10,  2.69it/s]
 32%|███▏      | 617/1939 [01:39<07:33,  2.92it/s]
 32%|███▏      | 618/1939 [01:39<06:57,  3.17it/s]
 32%|███▏      | 619/1939 [01:39<06:53,  3.19it/s]
 32%|███▏      | 620/1939 [01:40<08:03,  2.73it/s]
 32%|███▏      | 622/1939 [01:40<04:53,  4.48it/s]
 32%|███▏      | 624/1939 [01:40<03:30,  6.26it/s]
 32%|███▏      | 627/1939 [01:40<03:24,  6.41it/s]
 32%|███▏      | 629/1939 [01:40<02:47,  7.82it/s]
 33%|███▎      | 631/1939 [01:41<04:13,  5.16it/s]
 33%|███▎      | 632/1939 [01:42<05:01,  4.33it/s]
 33%|███▎      | 635/1939 [01:42<03:11,  6.81it/s]
 33%|███▎      | 637/1939 [01:42<03:49,  5.67it/s]
 33%|███▎      | 639/1939 [01:42<03:05,  7.03it/s]
 33%|███▎      | 641/1939 [01:43<04:29,  4.81it/s]
 33%|███▎      | 643/1939 [01:44<05:33,  3.89it/s]
 33%|███▎      | 646/1939 [01:44<04:49,  4.46it/s]
 33%|███▎      | 649/1939 [01:45<04:28,  4.81it/s]
 34%|███▎      | 650/1939 [01:45<04:49,  4.45it/s]
 34%|███▎      | 652/1939 [01:45<04:19,  4.96it/s]
 34%|███▎      | 653/1939 [01:46<04:31,  4.74it/s]
 34%|███▎      | 654/1939 [01:46<05:57,  3.59it/s]
 34%|███▍      | 655/1939 [01:46<05:11,  4.12it/s]
 34%|███▍      | 656/1939 [01:47<06:31,  3.28it/s]
 34%|███▍      | 658/1939 [01:47<05:21,  3.98it/s]
 34%|███▍      | 660/1939 [01:47<03:48,  5.60it/s]
 34%|███▍      | 663/1939 [01:47<02:30,  8.45it/s]
 34%|███▍      | 665/1939 [01:48<02:14,  9.46it/s]
 34%|███▍      | 667/1939 [01:48<03:00,  7.05it/s]
 35%|███▍      | 669/1939 [01:49<04:22,  4.83it/s]
 35%|███▍      | 672/1939 [01:50<04:51,  4.35it/s]
 35%|███▍      | 673/1939 [01:50<05:30,  3.83it/s]
 35%|███▍      | 676/1939 [01:50<04:42,  4.47it/s]
 35%|███▍      | 677/1939 [01:51<04:58,  4.23it/s]
 35%|███▍      | 678/1939 [01:51<05:46,  3.64it/s]
 35%|███▌      | 680/1939 [01:52<06:29,  3.24it/s]
 35%|███▌      | 682/1939 [01:52<04:41,  4.46it/s]
 35%|███▌      | 683/1939 [01:53<06:34,  3.18it/s]
 35%|███▌      | 686/1939 [01:53<03:57,  5.27it/s]
 35%|███▌      | 688/1939 [01:54<06:04,  3.43it/s]
 36%|███▌      | 689/1939 [01:55<07:30,  2.77it/s]
 36%|███▌      | 691/1939 [01:55<06:38,  3.14it/s]
 36%|███▌      | 692/1939 [01:56<07:13,  2.87it/s]
 36%|███▌      | 694/1939 [01:56<05:09,  4.02it/s]
 36%|███▌      | 696/1939 [01:56<03:49,  5.41it/s]
 36%|███▌      | 699/1939 [01:56<02:33,  8.09it/s]
 36%|███▋      | 706/1939 [01:56<01:14, 16.65it/s]
 37%|███▋      | 713/1939 [01:56<00:48, 25.26it/s]
 37%|███▋      | 718/1939 [01:56<00:41, 29.67it/s]
 37%|███▋      | 724/1939 [01:56<00:35, 34.36it/s]
 38%|███▊      | 729/1939 [01:57<00:51, 23.48it/s]
 38%|███▊      | 733/1939 [01:59<02:58,  6.74it/s]
 38%|███▊      | 736/1939 [02:00<03:59,  5.02it/s]
 38%|███▊      | 739/1939 [02:00<03:50,  5.21it/s]
 38%|███▊      | 742/1939 [02:01<04:13,  4.72it/s]
 38%|███▊      | 744/1939 [02:01<03:36,  5.51it/s]
 38%|███▊      | 746/1939 [02:02<03:49,  5.19it/s]
 39%|███▊      | 748/1939 [02:02<04:50,  4.11it/s]
 39%|███▊      | 749/1939 [02:03<05:21,  3.70it/s]
 39%|███▊      | 751/1939 [02:03<05:20,  3.70it/s]
 39%|███▉      | 752/1939 [02:04<06:56,  2.85it/s]
 39%|███▉      | 755/1939 [02:05<06:16,  3.15it/s]
 39%|███▉      | 757/1939 [02:05<05:52,  3.35it/s]
 39%|███▉      | 760/1939 [02:06<05:32,  3.54it/s]
 39%|███▉      | 762/1939 [02:06<04:24,  4.45it/s]
 39%|███▉      | 763/1939 [02:07<05:50,  3.35it/s]
 39%|███▉      | 764/1939 [02:07<05:58,  3.28it/s]
 40%|███▉      | 766/1939 [02:08<05:08,  3.80it/s]
 40%|███▉      | 767/1939 [02:08<05:53,  3.31it/s]
 40%|███▉      | 768/1939 [02:09<06:12,  3.15it/s]
 40%|███▉      | 769/1939 [02:09<05:35,  3.49it/s]
 40%|███▉      | 770/1939 [02:09<05:39,  3.44it/s]
 40%|███▉      | 771/1939 [02:09<06:13,  3.13it/s]
 40%|███▉      | 772/1939 [02:10<06:47,  2.86it/s]
 40%|███▉      | 773/1939 [02:10<06:27,  3.01it/s]
 40%|███▉      | 775/1939 [02:10<04:46,  4.06it/s]
 40%|████      | 776/1939 [02:11<06:27,  3.00it/s]
 40%|████      | 777/1939 [02:12<08:07,  2.38it/s]
 40%|████      | 779/1939 [02:12<07:38,  2.53it/s]
 40%|████      | 780/1939 [02:13<07:47,  2.48it/s]
 40%|████      | 782/1939 [02:13<05:06,  3.78it/s]
 40%|████      | 784/1939 [02:14<05:29,  3.50it/s]
 41%|████      | 786/1939 [02:14<04:01,  4.78it/s]
 41%|████      | 787/1939 [02:14<04:52,  3.94it/s]
 41%|████      | 789/1939 [02:15<04:22,  4.38it/s]
 41%|████      | 791/1939 [02:15<04:21,  4.39it/s]
 41%|████      | 794/1939 [02:15<03:08,  6.07it/s]
 41%|████      | 795/1939 [02:16<03:33,  5.37it/s]
 41%|████      | 796/1939 [02:16<04:07,  4.61it/s]
 41%|████      | 797/1939 [02:16<04:31,  4.21it/s]
 41%|████      | 798/1939 [02:16<04:27,  4.27it/s]
 41%|████▏     | 800/1939 [02:17<03:44,  5.08it/s]
 41%|████▏     | 801/1939 [02:17<05:06,  3.71it/s]
 41%|████▏     | 804/1939 [02:18<04:52,  3.88it/s]
 42%|████▏     | 805/1939 [02:19<06:13,  3.03it/s]
 42%|████▏     | 806/1939 [02:19<07:29,  2.52it/s]
 42%|████▏     | 808/1939 [02:20<07:12,  2.61it/s]
 42%|████▏     | 809/1939 [02:20<07:27,  2.53it/s]
 42%|████▏     | 811/1939 [02:21<05:12,  3.61it/s]
 42%|████▏     | 812/1939 [02:21<05:53,  3.19it/s]
 42%|████▏     | 813/1939 [02:21<06:14,  3.00it/s]
 42%|████▏     | 814/1939 [02:22<06:44,  2.78it/s]
 42%|████▏     | 816/1939 [02:22<05:45,  3.25it/s]
 42%|████▏     | 817/1939 [02:23<05:53,  3.17it/s]
 42%|████▏     | 818/1939 [02:23<06:09,  3.04it/s]
 42%|████▏     | 819/1939 [02:23<06:30,  2.87it/s]
 42%|████▏     | 820/1939 [02:24<06:15,  2.98it/s]
 42%|████▏     | 821/1939 [02:24<05:27,  3.41it/s]
 42%|████▏     | 822/1939 [02:24<05:37,  3.31it/s]
 42%|████▏     | 823/1939 [02:25<06:15,  2.97it/s]
 43%|████▎     | 825/1939 [02:25<03:53,  4.78it/s]
 43%|████▎     | 826/1939 [02:25<04:09,  4.46it/s]
 43%|████▎     | 828/1939 [02:25<03:55,  4.73it/s]
 43%|████▎     | 829/1939 [02:26<04:16,  4.33it/s]
 43%|████▎     | 832/1939 [02:26<02:32,  7.25it/s]
 43%|████▎     | 834/1939 [02:26<02:46,  6.64it/s]
 43%|████▎     | 837/1939 [02:26<01:57,  9.39it/s]
 43%|████▎     | 839/1939 [02:27<01:53,  9.66it/s]
 43%|████▎     | 841/1939 [02:27<01:47, 10.25it/s]
 44%|████▎     | 844/1939 [02:27<01:51,  9.79it/s]
 44%|████▎     | 847/1939 [02:27<01:28, 12.36it/s]
 44%|████▍     | 849/1939 [02:28<01:53,  9.60it/s]
 44%|████▍     | 851/1939 [02:28<02:14,  8.11it/s]
 44%|████▍     | 853/1939 [02:28<01:57,  9.21it/s]
 44%|████▍     | 855/1939 [02:28<02:30,  7.23it/s]
 44%|████▍     | 857/1939 [02:29<03:10,  5.69it/s]
 44%|████▍     | 859/1939 [02:29<03:15,  5.52it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 326.84it/s]
 67%|██████▋   | 201/300 [19:34<1:27:11, 52.84s/it]

[[np.int64(0), False, 1], [np.int64(1), False, 13], [np.int64(2), False, 8], [np.int64(3), False, 8], [np.int64(4), False, 7], [np.int64(5), False, 0], [np.int64(6), False, 3], [np.int64(9), False, 4], [np.int64(10), False, 13], [np.int64(11), False, 0], [np.int64(12), False, 13]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.7116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5563, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.7087, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6255, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [19:34<56:15, 34.80s/it]

tensor(12.7088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6722, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6952, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [19:34<35:01, 22.12s/it]

tensor(12.7129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7133, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7247, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7198, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [19:34<22:35, 14.57s/it]

tensor(12.6979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7214, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7293, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [19:35<14:52,  9.81s/it]

tensor(12.6859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7367, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [19:35<09:56,  6.71s/it]

tensor(12.6826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7438, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7495, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7470, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [19:35<06:43,  4.63s/it]

tensor(12.6750, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7452, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7427, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [19:35<04:34,  3.23s/it]

tensor(12.6688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7412, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [19:35<03:08,  2.27s/it]

tensor(12.6649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7452, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7456, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7460, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [19:36<02:10,  1.61s/it]

tensor(12.6526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0201, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7429, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7430, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [19:36<01:30,  1.15s/it]

tensor(12.6458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2256, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [19:36<01:04,  1.20it/s]

tensor(12.6437, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3811, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5717, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6358, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [19:36<00:45,  1.64it/s]

tensor(12.6520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0390, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6406, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0408, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6474, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [19:36<00:33,  2.20it/s]

tensor(12.6460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0420, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6523, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [19:37<00:24,  2.89it/s]

tensor(12.6434, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0421, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6589, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6700, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6402, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6813, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [19:37<00:18,  3.69it/s]

tensor(12.6377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6825, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6789, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [19:37<00:14,  4.58it/s]

tensor(12.6315, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6759, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [19:37<00:11,  5.51it/s]

tensor(12.6287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6718, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6740, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6788, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [19:37<00:09,  6.41it/s]

tensor(12.6149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6828, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6104, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6883, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [19:37<00:08,  7.26it/s]

tensor(12.6068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6892, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [19:38<00:07,  7.98it/s]

tensor(12.6043, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6929, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5992, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6973, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [19:38<00:06,  8.57it/s]

tensor(12.5966, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6947, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7060, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [19:38<00:06,  9.05it/s]

tensor(12.5918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6963, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [19:38<00:05,  9.40it/s]

tensor(12.5901, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6978, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6979, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7002, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [19:38<00:05,  9.71it/s]

tensor(12.5851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7079, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([183, 195, 108, 334, 120,  95,  86,  25, 262, 104, 200, 152,  45,  30])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:13, 26.36it/s]
  1%|          | 10/1939 [00:00<00:41, 46.65it/s]
  1%|          | 16/1939 [00:00<00:39, 48.97it/s]
  1%|          | 22/1939 [00:00<00:39, 47.96it/s]
  1%|▏         | 28/1939 [00:00<00:38, 50.19it/s]
  2%|▏         | 34/1939 [00:00<00:38, 49.70it/s]
  2%|▏         | 40/1939 [00:00<00:36, 52.44it/s]
  2%|▏         | 46/1939 [00:01<01:38, 19.18it/s]
  3%|▎         | 50/1939 [00:01<01:54, 16.48it/s]
  3%|▎         | 54/1939 [00:02<02:12, 14.22it/s]
  3%|▎         | 57/1939 [00:02<02:40, 11.71it/s]
  3%|▎         | 59/1939 [00:03<04:38,  6.74it/s]
  3%|▎         | 62/1939 [00:03<03:42,  8.45it/s]
  3%|▎         | 66/1939 [00:04<03:22,  9.24it/s]
  4%|▎         | 68/1939 [00:04<03:03, 10.22it/s]
  4%|▎         | 70/1939 [00:04<02:48, 11.08it/s]
  4%|▍         | 73/1939 [00:04<03:23,  9.18it/s]
  4%|▍         | 75/1939 [00:04<03:08,  9.89it/s]
  4%|▍         | 78/1939 [00:05<03:04, 10.09it/s]
  4%|▍         | 80/1939 [00:06<05:28,  5.66it/s]
  4%|▍         | 81/1939 [00:06<05:56,  5.21it/s]
  4%|▍         | 82/1939 [00:06<05:41,  5.44it/s]
  4%|▍         | 83/1939 [00:06<06:19,  4.89it/s]
  4%|▍         | 84/1939 [00:07<07:46,  3.97it/s]
  4%|▍         | 86/1939 [00:07<07:58,  3.87it/s]
  5%|▍         | 88/1939 [00:07<05:44,  5.37it/s]
  5%|▍         | 91/1939 [00:07<03:49,  8.04it/s]
  5%|▍         | 94/1939 [00:08<04:37,  6.66it/s]
  5%|▍         | 96/1939 [00:09<05:59,  5.12it/s]
 83%|████████▎ | 249/300 [19:53<00:05,  9.71it/s]
  5%|▌         | 101/1939 [00:10<08:03,  3.80it/s]
  5%|▌         | 104/1939 [00:10<05:35,  5.47it/s]
  5%|▌         | 106/1939 [00:11<06:00,  5.09it/s]
  6%|▌         | 108/1939 [00:11<06:38,  4.59it/s]
  6%|▌         | 110/1939 [00:12<06:40,  4.57it/s]
  6%|▌         | 112/1939 [00:12<05:13,  5.82it/s]
  6%|▌         | 114/1939 [00:12<04:12,  7.24it/s]
  6%|▌         | 116/1939 [00:12<04:41,  6.47it/s]
  6%|▌         | 118/1939 [00:13<07:19,  4.15it/s]
  6%|▌         | 120/1939 [00:14<08:15,  3.67it/s]
  6%|▌         | 121/1939 [00:14<08:56,  3.39it/s]
  6%|▋         | 123/1939 [00:14<06:37,  4.57it/s]
  6%|▋         | 126/1939 [00:15<04:31,  6.68it/s]
  7%|▋         | 128/1939 [00:15<04:26,  6.80it/s]
  7%|▋         | 131/1939 [00:15<03:14,  9.31it/s]
  7%|▋         | 133/1939 [00:15<04:31,  6.65it/s]
  7%|▋         | 135/1939 [00:16<05:26,  5.53it/s]
  7%|▋         | 137/1939 [00:17<06:33,  4.58it/s]
  7%|▋         | 138/1939 [00:17<08:07,  3.69it/s]
  7%|▋         | 139/1939 [00:18<09:51,  3.04it/s]
  7%|▋         | 141/1939 [00:18<09:26,  3.18it/s]
  7%|▋         | 142/1939 [00:19<11:13,  2.67it/s]
  7%|▋         | 145/1939 [00:20<09:06,  3.28it/s]
  8%|▊         | 146/1939 [00:20<10:36,  2.82it/s]
  8%|▊         | 148/1939 [00:20<07:35,  3.93it/s]
  8%|▊         | 149/1939 [00:21<09:18,  3.20it/s]
  8%|▊         | 150/1939 [00:21<07:56,  3.75it/s]
  8%|▊         | 151/1939 [00:22<10:47,  2.76it/s]
  8%|▊         | 153/1939 [00:22<10:26,  2.85it/s]
  8%|▊         | 155/1939 [00:22<07:15,  4.10it/s]
  8%|▊         | 157/1939 [00:23<07:24,  4.01it/s]
  8%|▊         | 158/1939 [00:24<09:28,  3.13it/s]
  8%|▊         | 159/1939 [00:24<10:49,  2.74it/s]
  8%|▊         | 160/1939 [00:25<12:42,  2.33it/s]
  8%|▊         | 161/1939 [00:25<13:16,  2.23it/s]
  8%|▊         | 162/1939 [00:26<14:48,  2.00it/s]
  8%|▊         | 163/1939 [00:26<15:22,  1.93it/s]
  8%|▊         | 164/1939 [00:27<15:59,  1.85it/s]
  9%|▊         | 167/1939 [00:27<08:09,  3.62it/s]
  9%|▊         | 169/1939 [00:27<06:02,  4.88it/s]
  9%|▉         | 176/1939 [00:27<02:29, 11.79it/s]
  9%|▉         | 183/1939 [00:28<01:30, 19.45it/s]
 10%|▉         | 189/1939 [00:28<01:10, 24.83it/s]
 10%|█         | 195/1939 [00:28<00:58, 29.77it/s]
 10%|█         | 200/1939 [00:28<01:00, 28.63it/s]
 11%|█         | 204/1939 [00:29<02:25, 11.94it/s]
 11%|█         | 207/1939 [00:30<04:27,  6.47it/s]
 11%|█         | 211/1939 [00:31<04:08,  6.95it/s]
 11%|█         | 213/1939 [00:31<04:13,  6.80it/s]
 11%|█         | 215/1939 [00:31<04:44,  6.07it/s]
 11%|█         | 218/1939 [00:32<04:57,  5.78it/s]
 11%|█▏        | 220/1939 [00:32<04:12,  6.80it/s]
 11%|█▏        | 222/1939 [00:33<05:11,  5.50it/s]
 12%|█▏        | 224/1939 [00:33<06:08,  4.66it/s]
 12%|█▏        | 226/1939 [00:33<04:53,  5.83it/s]
 12%|█▏        | 228/1939 [00:34<05:17,  5.39it/s]
 12%|█▏        | 230/1939 [00:34<04:13,  6.74it/s]
 12%|█▏        | 233/1939 [00:34<04:03,  7.00it/s]
 12%|█▏        | 235/1939 [00:34<03:24,  8.33it/s]
 12%|█▏        | 237/1939 [00:35<04:41,  6.05it/s]
 12%|█▏        | 239/1939 [00:36<05:27,  5.19it/s]
 12%|█▏        | 240/1939 [00:36<07:16,  3.89it/s]
 12%|█▏        | 241/1939 [00:37<09:10,  3.08it/s]
 12%|█▏        | 242/1939 [00:37<09:56,  2.84it/s]
 13%|█▎        | 243/1939 [00:37<09:21,  3.02it/s]
 13%|█▎        | 244/1939 [00:38<09:06,  3.10it/s]
 13%|█▎        | 245/1939 [00:38<09:55,  2.84it/s]
 13%|█▎        | 246/1939 [00:39<11:08,  2.53it/s]
 13%|█▎        | 248/1939 [00:39<10:00,  2.82it/s]
 13%|█▎        | 251/1939 [00:39<05:36,  5.02it/s]
 13%|█▎        | 253/1939 [00:40<06:23,  4.40it/s]
 13%|█▎        | 255/1939 [00:40<04:51,  5.79it/s]
 13%|█▎        | 257/1939 [00:41<06:04,  4.62it/s]
 13%|█▎        | 259/1939 [00:41<04:40,  5.98it/s]
 13%|█▎        | 261/1939 [00:41<05:41,  4.91it/s]
 14%|█▎        | 263/1939 [00:42<06:29,  4.30it/s]
 14%|█▎        | 264/1939 [00:43<08:02,  3.47it/s]
 14%|█▎        | 266/1939 [00:43<05:54,  4.72it/s]
 14%|█▍        | 268/1939 [00:43<06:44,  4.13it/s]
 14%|█▍        | 270/1939 [00:44<06:59,  3.98it/s]
 14%|█▍        | 272/1939 [00:44<05:21,  5.18it/s]
 14%|█▍        | 273/1939 [00:44<07:01,  3.96it/s]
 14%|█▍        | 274/1939 [00:45<08:38,  3.21it/s]
 14%|█▍        | 277/1939 [00:45<05:10,  5.35it/s]
 14%|█▍        | 281/1939 [00:46<05:03,  5.46it/s]
 15%|█▍        | 284/1939 [00:47<05:23,  5.12it/s]
 15%|█▍        | 285/1939 [00:47<06:39,  4.14it/s]
 15%|█▍        | 287/1939 [00:48<06:57,  3.96it/s]
 15%|█▍        | 288/1939 [00:48<08:20,  3.30it/s]
 15%|█▌        | 291/1939 [00:48<05:19,  5.16it/s]
 15%|█▌        | 293/1939 [00:49<06:01,  4.55it/s]
 15%|█▌        | 295/1939 [00:49<04:44,  5.78it/s]
 15%|█▌        | 297/1939 [00:50<05:55,  4.62it/s]
 15%|█▌        | 298/1939 [00:50<07:30,  3.65it/s]
 15%|█▌        | 300/1939 [00:51<07:37,  3.58it/s]
 16%|█▌        | 303/1939 [00:51<06:48,  4.00it/s]
 16%|█▌        | 304/1939 [00:52<08:02,  3.39it/s]
 16%|█▌        | 306/1939 [00:52<05:55,  4.60it/s]
 16%|█▌        | 307/1939 [00:53<07:46,  3.50it/s]
 16%|█▌        | 308/1939 [00:53<09:13,  2.95it/s]
 16%|█▌        | 311/1939 [00:53<05:23,  5.03it/s]
 16%|█▌        | 313/1939 [00:54<08:10,  3.31it/s]
 16%|█▌        | 315/1939 [00:55<07:59,  3.38it/s]
 16%|█▋        | 316/1939 [00:55<09:07,  2.96it/s]
 16%|█▋        | 317/1939 [00:56<09:49,  2.75it/s]
 16%|█▋        | 318/1939 [00:56<11:01,  2.45it/s]
 16%|█▋        | 319/1939 [00:57<11:46,  2.29it/s]
 17%|█▋        | 320/1939 [00:57<12:23,  2.18it/s]
 17%|█▋        | 321/1939 [00:58<13:35,  1.98it/s]
 17%|█▋        | 322/1939 [00:59<14:06,  1.91it/s]
 17%|█▋        | 325/1939 [00:59<06:56,  3.88it/s]
 17%|█▋        | 327/1939 [00:59<07:20,  3.66it/s]
 17%|█▋        | 330/1939 [01:00<04:41,  5.71it/s]
 17%|█▋        | 332/1939 [01:00<05:21,  4.99it/s]
 17%|█▋        | 334/1939 [01:00<04:11,  6.38it/s]
 17%|█▋        | 339/1939 [01:01<03:50,  6.93it/s]
 18%|█▊        | 342/1939 [01:01<02:59,  8.89it/s]
 18%|█▊        | 349/1939 [01:01<01:41, 15.66it/s]
 18%|█▊        | 352/1939 [01:02<03:42,  7.14it/s]
 18%|█▊        | 355/1939 [01:03<05:25,  4.87it/s]
 18%|█▊        | 358/1939 [01:04<04:15,  6.18it/s]
 19%|█▊        | 360/1939 [01:04<04:48,  5.47it/s]
 19%|█▊        | 363/1939 [01:05<05:07,  5.12it/s]
 19%|█▉        | 366/1939 [01:05<05:15,  4.98it/s]
 19%|█▉        | 369/1939 [01:05<03:58,  6.58it/s]
 19%|█▉        | 371/1939 [01:06<04:46,  5.48it/s]
 19%|█▉        | 373/1939 [01:07<05:34,  4.68it/s]
 19%|█▉        | 376/1939 [01:07<05:40,  4.59it/s]
 19%|█▉        | 378/1939 [01:07<04:41,  5.54it/s]
 20%|█▉        | 380/1939 [01:08<05:09,  5.03it/s]
 20%|█▉        | 381/1939 [01:09<06:44,  3.85it/s]
 20%|█▉        | 382/1939 [01:09<07:59,  3.25it/s]
 20%|█▉        | 384/1939 [01:10<07:58,  3.25it/s]
 20%|█▉        | 386/1939 [01:10<05:53,  4.39it/s]
 20%|█▉        | 387/1939 [01:10<07:12,  3.59it/s]
 20%|██        | 388/1939 [01:11<08:33,  3.02it/s]
 20%|██        | 389/1939 [01:11<09:26,  2.74it/s]
 20%|██        | 390/1939 [01:12<10:45,  2.40it/s]
 20%|██        | 391/1939 [01:12<11:04,  2.33it/s]
 20%|██        | 393/1939 [01:13<10:29,  2.46it/s]
 20%|██        | 394/1939 [01:14<10:42,  2.40it/s]
 20%|██        | 396/1939 [01:14<10:10,  2.53it/s]
 20%|██        | 397/1939 [01:15<09:47,  2.63it/s]
 21%|██        | 398/1939 [01:15<11:22,  2.26it/s]
 21%|██        | 399/1939 [01:15<09:14,  2.78it/s]
 21%|██        | 404/1939 [01:16<05:24,  4.72it/s]
 21%|██        | 405/1939 [01:17<06:52,  3.72it/s]
 21%|██        | 407/1939 [01:17<07:08,  3.57it/s]
 21%|██        | 409/1939 [01:17<05:23,  4.73it/s]
 21%|██        | 411/1939 [01:18<05:50,  4.36it/s]
 21%|██        | 412/1939 [01:18<06:19,  4.02it/s]
 21%|██▏       | 414/1939 [01:18<04:42,  5.41it/s]
 21%|██▏       | 415/1939 [01:19<04:51,  5.22it/s]
 21%|██▏       | 416/1939 [01:19<04:54,  5.17it/s]
 22%|██▏       | 417/1939 [01:19<05:02,  5.04it/s]
 22%|██▏       | 419/1939 [01:20<07:14,  3.50it/s]
 22%|██▏       | 422/1939 [01:21<06:34,  3.84it/s]
 22%|██▏       | 425/1939 [01:21<04:17,  5.88it/s]
 22%|██▏       | 427/1939 [01:21<05:03,  4.98it/s]
 22%|██▏       | 428/1939 [01:22<06:16,  4.01it/s]
 22%|██▏       | 430/1939 [01:22<04:50,  5.20it/s]
 22%|██▏       | 431/1939 [01:22<05:45,  4.37it/s]
 22%|██▏       | 432/1939 [01:22<05:05,  4.94it/s]
 23%|██▎       | 437/1939 [01:22<02:27, 10.20it/s]
 23%|██▎       | 441/1939 [01:23<02:06, 11.84it/s]
 23%|██▎       | 444/1939 [01:23<01:47, 13.94it/s]
 23%|██▎       | 450/1939 [01:23<01:11, 20.87it/s]
 23%|██▎       | 453/1939 [01:23<01:12, 20.40it/s]
 24%|██▎       | 456/1939 [01:23<01:09, 21.26it/s]
 24%|██▎       | 459/1939 [01:23<01:07, 22.03it/s]
 24%|██▍       | 465/1939 [01:23<00:49, 29.83it/s]
 24%|██▍       | 472/1939 [01:24<00:41, 35.44it/s]
 25%|██▍       | 476/1939 [01:24<00:45, 31.88it/s]
 25%|██▍       | 482/1939 [01:24<00:39, 36.66it/s]
 25%|██▌       | 489/1939 [01:25<01:16, 19.07it/s]
 25%|██▌       | 493/1939 [01:26<02:36,  9.23it/s]
 26%|██▌       | 496/1939 [01:26<02:58,  8.10it/s]
 26%|██▌       | 498/1939 [01:26<02:41,  8.92it/s]
 26%|██▌       | 500/1939 [01:27<03:24,  7.02it/s]
 26%|██▌       | 503/1939 [01:27<02:43,  8.79it/s]
 26%|██▌       | 505/1939 [01:28<03:30,  6.82it/s]
 26%|██▌       | 508/1939 [01:28<02:44,  8.72it/s]
 27%|██▋       | 514/1939 [01:28<01:38, 14.50it/s]
 27%|██▋       | 521/1939 [01:28<01:05, 21.49it/s]
 27%|██▋       | 529/1939 [01:28<00:45, 30.87it/s]
 28%|██▊       | 536/1939 [01:28<00:37, 37.70it/s]
 28%|██▊       | 542/1939 [01:29<01:54, 12.16it/s]
 28%|██▊       | 546/1939 [01:30<02:16, 10.21it/s]
 28%|██▊       | 549/1939 [01:31<02:41,  8.60it/s]
 28%|██▊       | 552/1939 [01:32<03:46,  6.13it/s]
 29%|██▊       | 554/1939 [01:32<03:19,  6.94it/s]
 29%|██▊       | 556/1939 [01:32<03:57,  5.81it/s]
 29%|██▉       | 558/1939 [01:33<04:14,  5.42it/s]
 29%|██▉       | 561/1939 [01:33<03:11,  7.21it/s]
 29%|██▉       | 563/1939 [01:33<03:10,  7.22it/s]
 29%|██▉       | 566/1939 [01:33<02:24,  9.50it/s]
 29%|██▉       | 568/1939 [01:34<03:29,  6.55it/s]
 29%|██▉       | 571/1939 [01:35<03:50,  5.93it/s]
 30%|██▉       | 573/1939 [01:35<04:45,  4.78it/s]
 30%|██▉       | 574/1939 [01:36<06:01,  3.78it/s]
 30%|██▉       | 575/1939 [01:36<06:08,  3.71it/s]
 30%|██▉       | 578/1939 [01:36<03:51,  5.88it/s]
 30%|██▉       | 580/1939 [01:37<04:53,  4.63it/s]
 30%|███       | 582/1939 [01:37<05:30,  4.11it/s]
 30%|███       | 584/1939 [01:38<06:10,  3.66it/s]
 30%|███       | 586/1939 [01:39<06:18,  3.57it/s]
 30%|███       | 588/1939 [01:39<04:48,  4.68it/s]
 30%|███       | 589/1939 [01:39<06:17,  3.58it/s]
 30%|███       | 591/1939 [01:40<04:34,  4.91it/s]
 31%|███       | 593/1939 [01:40<05:06,  4.39it/s]
 31%|███       | 595/1939 [01:41<05:30,  4.07it/s]
 31%|███       | 598/1939 [01:41<03:37,  6.17it/s]
 31%|███       | 600/1939 [01:42<06:18,  3.54it/s]
 31%|███       | 601/1939 [01:43<07:24,  3.01it/s]
 31%|███       | 604/1939 [01:43<04:42,  4.73it/s]
 31%|███▏      | 607/1939 [01:43<04:35,  4.84it/s]
 31%|███▏      | 609/1939 [01:44<05:03,  4.39it/s]
 32%|███▏      | 611/1939 [01:44<05:28,  4.04it/s]
 32%|███▏      | 612/1939 [01:45<06:40,  3.31it/s]
 32%|███▏      | 613/1939 [01:46<07:37,  2.90it/s]
 32%|███▏      | 614/1939 [01:46<08:36,  2.57it/s]
 32%|███▏      | 615/1939 [01:47<09:36,  2.30it/s]
 32%|███▏      | 616/1939 [01:47<10:19,  2.14it/s]
 32%|███▏      | 617/1939 [01:48<10:25,  2.11it/s]
 32%|███▏      | 618/1939 [01:48<10:45,  2.05it/s]
 32%|███▏      | 620/1939 [01:49<09:28,  2.32it/s]
 32%|███▏      | 622/1939 [01:49<06:16,  3.50it/s]
 32%|███▏      | 624/1939 [01:49<04:27,  4.91it/s]
 32%|███▏      | 627/1939 [01:49<02:51,  7.65it/s]
 32%|███▏      | 630/1939 [01:50<02:37,  8.31it/s]
 33%|███▎      | 632/1939 [01:50<02:50,  7.65it/s]
 33%|███▎      | 634/1939 [01:50<02:23,  9.13it/s]
 33%|███▎      | 636/1939 [01:50<02:24,  9.03it/s]
 33%|███▎      | 638/1939 [01:50<02:16,  9.53it/s]
 33%|███▎      | 640/1939 [01:51<02:34,  8.43it/s]
 33%|███▎      | 642/1939 [01:51<02:51,  7.57it/s]
 33%|███▎      | 643/1939 [01:52<03:58,  5.43it/s]
 33%|███▎      | 645/1939 [01:52<03:10,  6.81it/s]
 33%|███▎      | 646/1939 [01:52<03:23,  6.35it/s]
 33%|███▎      | 648/1939 [01:52<02:46,  7.75it/s]
 33%|███▎      | 649/1939 [01:52<04:02,  5.32it/s]
 34%|███▎      | 651/1939 [01:53<02:58,  7.22it/s]
 34%|███▎      | 653/1939 [01:53<03:29,  6.15it/s]
 34%|███▎      | 654/1939 [01:53<04:00,  5.35it/s]
 34%|███▍      | 656/1939 [01:54<03:42,  5.76it/s]
 34%|███▍      | 658/1939 [01:54<04:12,  5.08it/s]
 34%|███▍      | 661/1939 [01:54<02:50,  7.48it/s]
 34%|███▍      | 665/1939 [01:54<02:14,  9.48it/s]
 34%|███▍      | 667/1939 [01:55<02:23,  8.85it/s]
 35%|███▍      | 669/1939 [01:55<03:00,  7.04it/s]
 35%|███▍      | 671/1939 [01:55<02:34,  8.19it/s]
 35%|███▍      | 673/1939 [01:56<03:28,  6.08it/s]
 35%|███▍      | 674/1939 [01:56<03:15,  6.46it/s]
 35%|███▍      | 676/1939 [01:56<03:04,  6.85it/s]
 35%|███▍      | 677/1939 [01:57<03:56,  5.34it/s]
 35%|███▍      | 678/1939 [01:57<03:50,  5.47it/s]
 35%|███▌      | 680/1939 [01:57<03:53,  5.39it/s]
 35%|███▌      | 683/1939 [01:58<03:38,  5.74it/s]
 35%|███▌      | 686/1939 [01:58<02:31,  8.29it/s]
 35%|███▌      | 688/1939 [01:59<04:27,  4.68it/s]
 36%|███▌      | 689/1939 [01:59<04:43,  4.41it/s]
 36%|███▌      | 690/1939 [01:59<04:14,  4.91it/s]
 36%|███▌      | 692/1939 [02:00<04:43,  4.40it/s]
 36%|███▌      | 694/1939 [02:00<03:35,  5.79it/s]
 36%|███▌      | 697/1939 [02:00<02:28,  8.37it/s]
 36%|███▋      | 704/1939 [02:00<01:12, 17.11it/s]
 37%|███▋      | 711/1939 [02:00<00:49, 24.67it/s]
 37%|███▋      | 717/1939 [02:00<00:39, 30.71it/s]
 37%|███▋      | 724/1939 [02:00<00:31, 38.68it/s]
 38%|███▊      | 730/1939 [02:01<01:23, 14.39it/s]
 38%|███▊      | 734/1939 [02:03<02:56,  6.83it/s]
 38%|███▊      | 737/1939 [02:03<02:30,  8.00it/s]
 38%|███▊      | 740/1939 [02:04<02:37,  7.61it/s]
 38%|███▊      | 743/1939 [02:04<02:47,  7.15it/s]
 38%|███▊      | 745/1939 [02:05<03:24,  5.84it/s]
 39%|███▊      | 747/1939 [02:05<04:11,  4.75it/s]
 39%|███▊      | 749/1939 [02:06<04:41,  4.22it/s]
 39%|███▊      | 751/1939 [02:07<04:58,  3.99it/s]
 39%|███▉      | 753/1939 [02:07<03:56,  5.02it/s]
 39%|███▉      | 755/1939 [02:07<04:19,  4.56it/s]
 39%|███▉      | 757/1939 [02:08<04:44,  4.15it/s]
 39%|███▉      | 759/1939 [02:08<04:57,  3.96it/s]
 39%|███▉      | 760/1939 [02:09<05:14,  3.75it/s]
 39%|███▉      | 761/1939 [02:09<04:36,  4.26it/s]
 39%|███▉      | 763/1939 [02:09<05:08,  3.81it/s]
 39%|███▉      | 765/1939 [02:10<03:48,  5.15it/s]
 40%|███▉      | 766/1939 [02:10<04:50,  4.04it/s]
 40%|███▉      | 767/1939 [02:10<04:56,  3.96it/s]
 40%|███▉      | 768/1939 [02:11<04:56,  3.94it/s]
 40%|███▉      | 769/1939 [02:11<05:39,  3.44it/s]
 40%|███▉      | 770/1939 [02:11<05:32,  3.52it/s]
 40%|███▉      | 771/1939 [02:12<05:27,  3.57it/s]
 40%|███▉      | 772/1939 [02:12<05:12,  3.73it/s]
 40%|███▉      | 773/1939 [02:12<06:08,  3.16it/s]
 40%|███▉      | 775/1939 [02:12<04:33,  4.26it/s]
 40%|████      | 776/1939 [02:13<04:42,  4.11it/s]
 40%|████      | 777/1939 [02:13<04:31,  4.28it/s]
 40%|████      | 779/1939 [02:14<05:05,  3.80it/s]
 40%|████      | 780/1939 [02:14<06:06,  3.16it/s]
 40%|████      | 783/1939 [02:14<03:30,  5.50it/s]
 40%|████      | 784/1939 [02:15<04:25,  4.35it/s]
 41%|████      | 786/1939 [02:15<03:13,  5.96it/s]
 41%|████      | 788/1939 [02:15<04:06,  4.66it/s]
 41%|████      | 789/1939 [02:16<05:30,  3.48it/s]
 41%|████      | 791/1939 [02:16<03:58,  4.81it/s]
 41%|████      | 794/1939 [02:17<03:46,  5.06it/s]
 41%|████      | 796/1939 [02:17<02:57,  6.42it/s]
 41%|████      | 798/1939 [02:17<03:37,  5.23it/s]
 41%|████▏     | 800/1939 [02:18<04:20,  4.37it/s]
 41%|████▏     | 802/1939 [02:18<03:24,  5.56it/s]
 41%|████▏     | 804/1939 [02:19<04:01,  4.70it/s]
 42%|████▏     | 806/1939 [02:19<04:37,  4.08it/s]
 42%|████▏     | 808/1939 [02:19<03:37,  5.19it/s]
 42%|████▏     | 809/1939 [02:20<04:59,  3.77it/s]
 42%|████▏     | 812/1939 [02:21<04:38,  4.04it/s]
 42%|████▏     | 813/1939 [02:21<05:46,  3.25it/s]
 42%|████▏     | 815/1939 [02:21<04:12,  4.46it/s]
 42%|████▏     | 816/1939 [02:22<05:30,  3.39it/s]
 42%|████▏     | 817/1939 [02:23<06:49,  2.74it/s]
 42%|████▏     | 818/1939 [02:23<07:50,  2.38it/s]
 42%|████▏     | 819/1939 [02:24<08:40,  2.15it/s]
 42%|████▏     | 820/1939 [02:24<09:21,  1.99it/s]
 42%|████▏     | 821/1939 [02:25<09:49,  1.90it/s]
 42%|████▏     | 822/1939 [02:26<10:14,  1.82it/s]
 42%|████▏     | 823/1939 [02:26<10:30,  1.77it/s]
 43%|████▎     | 825/1939 [02:27<07:31,  2.47it/s]
 43%|████▎     | 826/1939 [02:27<07:09,  2.59it/s]
 43%|████▎     | 828/1939 [02:27<05:33,  3.33it/s]
 43%|████▎     | 829/1939 [02:28<05:11,  3.57it/s]
 43%|████▎     | 831/1939 [02:28<03:31,  5.24it/s]
 43%|████▎     | 834/1939 [02:28<02:36,  7.07it/s]
 43%|████▎     | 836/1939 [02:28<02:05,  8.78it/s]
 43%|████▎     | 839/1939 [02:28<02:15,  8.12it/s]
 43%|████▎     | 843/1939 [02:29<01:31, 11.94it/s]
 44%|████▎     | 845/1939 [02:29<02:00,  9.07it/s]
 44%|████▎     | 848/1939 [02:29<01:32, 11.80it/s]
 44%|████▍     | 851/1939 [02:29<01:48, 10.01it/s]
 44%|████▍     | 853/1939 [02:30<01:43, 10.51it/s]
 44%|████▍     | 855/1939 [02:30<02:17,  7.88it/s]
 44%|████▍     | 857/1939 [02:30<02:24,  7.48it/s]
 44%|████▍     | 859/1939 [02:31<02:29,  7.23it/s]
 44%|████▍     | 861/1939 [02:31<02:45,  6.53it/s]
 44%|████▍     | 862/1939 [02:32<03:55,  4.58it/s]
 45%|████▍     | 863/1939 [02:32<03:57,  4.52it/s]
 45%|████▍     | 864/1939 [02:32<05:06,  3.51it/s]
 45%|████▍     | 866/1939 [02:32<03:36,  4.95it/s]
 45%|████▍     | 872/1939 [02:33<01:33, 11.36it/s]
 45%|████▌     | 879/1939 [02:33<00:53, 19.79it/s]
 46%|████▌     | 886/1939 [02:33<00:37, 28.03it/s]
 46%|████▌     | 892/1939 [02:33<00:30, 33.95it/s]
 46%|████▋     | 899/1939 [02:33<00:25, 40.73it/s]
 47%|████▋     | 905/1939 [02:34<01:23, 12.36it/s]
 47%|████▋     | 910/1939 [02:35<01:38, 10.46it/s]
 47%|████▋     | 913/1939 [02:36<02:04,  8.22it/s]
 47%|████▋     | 916/1939 [02:36<02:06,  8.11it/s]
 47%|████▋     | 918/1939 [02:36<02:17,  7.41it/s]
 47%|████▋     | 920/1939 [02:37<02:17,  7.44it/s]
 48%|████▊     | 922/1939 [02:37<02:05,  8.13it/s]
 48%|████▊     | 924/1939 [02:37<02:06,  8.03it/s]
 48%|████▊     | 927/1939 [02:38<02:31,  6.68it/s]
 48%|████▊     | 929/1939 [02:38<02:10,  7.74it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 304.60it/s]
 84%|████████▎ | 251/300 [25:08<40:28, 49.56s/it]

[[np.int64(0), False, 1], [np.int64(2), False, 9], [np.int64(3), False, 8], [np.int64(4), False, 3], [np.int64(5), False, 8], [np.int64(6), False, 1], [np.int64(7), False, 0], [np.int64(10), False, 3], [np.int64(11), False, 4], [np.int64(12), False, 1], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3359, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.5822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3604, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [25:08<32:40, 40.84s/it]

tensor(12.5834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4043, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 253/300 [25:09<25:34, 32.64s/it]

tensor(12.5863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4364, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4540, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [25:09<15:33, 20.75s/it]

tensor(12.5908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4590, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [25:09<09:47, 13.67s/it]

tensor(12.5906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4443, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4625, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4766, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [25:09<06:17,  9.21s/it]

tensor(12.5827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4986, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5091, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [25:09<04:05,  6.30s/it]

tensor(12.5788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5164, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [25:10<02:41,  4.35s/it]

tensor(12.5788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5194, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5216, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5228, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [25:10<01:46,  3.04s/it]

tensor(12.5795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5226, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5226, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [25:10<01:10,  2.14s/it]

tensor(12.5764, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5227, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [25:10<00:46,  1.51s/it]

tensor(12.5728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5301, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5291, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5355, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [25:10<00:31,  1.08s/it]

tensor(12.5571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5363, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5523, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5363, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [25:10<00:21,  1.27it/s]

tensor(12.5481, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5367, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [25:11<00:14,  1.73it/s]

tensor(12.5449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5384, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5426, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5407, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5456, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [25:11<00:09,  2.32it/s]

tensor(12.5394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5514, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [25:11<00:06,  3.03it/s]

tensor(12.5361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5531, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [25:11<00:04,  3.86it/s]

tensor(12.5345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5530, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5558, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5582, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [25:11<00:03,  4.76it/s]

tensor(12.5292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5629, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5277, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5650, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [25:12<00:02,  5.70it/s]

tensor(12.5260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0186, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5681, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [25:12<00:01,  6.59it/s]

tensor(12.5246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5711, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5722, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5219, device='cuda:0', grad_fn=<AddBackward0>)

 96%|█████████▋| 289/300 [25:12<00:01,  7.34it/s]

tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5807, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5842, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5872, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [25:12<00:00,  8.75it/s]

tensor(12.5177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5892, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0186, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5917, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5946, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [25:13<00:00,  9.22it/s]

tensor(12.5138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5954, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5973, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [25:13<00:00,  9.86it/s]

tensor(12.5100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0186, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [25:13<00:00,  5.05s/it]

Model training finished!

Infer time:  0.0021936893463134766
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 8
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.448260743315
NMI         : 0.584198956560
Runtime     : 1537.87 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed8

==============================================================================================================
PRAGA RUN | S2-E15 | seed=9
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E15: ATAC 100329 -> 100329 peaks (removed 0 zero-total peaks)
S2-E15: scaled LSI shape = (1939, 50)
S2-E15: max |column mean| = 5.640e-17
S2-E15: sample std range = [1.000000, 1.000000]
S2-E15: RNA feat = (1939, 50)
S2-E15: ATAC feat = (1939, 50)
S2-E15: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:29, 10.22it/s]

tensor(17.7579, device='cuda:0', grad_fn=<AddBackward0>) tensor(21.3797, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.7711, device='cuda:0', grad_fn=<AddBackward0>) tensor(19.2371, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.7460, device='cuda:0', grad_fn=<AddBackward0>) tensor(17.3051, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:25, 11.67it/s]

tensor(17.7136, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.5627, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6762, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.9911, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.6378, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.5735, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:22, 12.71it/s]

tensor(17.6008, device='cuda:0', grad_fn=<AddBackward0>) tensor(11.2952, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5639, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.1430, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.5290, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.1038, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:00<00:22, 12.91it/s]

tensor(17.4939, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.1664, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4598, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.3218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.4262, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.5606, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:22, 12.97it/s]

tensor(17.3934, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.8740, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3603, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.2558, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.3271, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.6978, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:21, 13.09it/s]

tensor(17.2938, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.1957, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2599, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.7430, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.2253, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.3352, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:01<00:21, 13.17it/s]

tensor(17.1884, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9681, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1498, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.6377, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.1083, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.3404, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:01<00:21, 13.22it/s]

tensor(17.0647, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0727, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(17.0180, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8322, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9688, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.6154, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:20, 13.23it/s]

tensor(16.9176, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8649, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2460, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.8109, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0901, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:20, 13.20it/s]

tensor(16.7558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9490, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6996, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.6422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7101, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:02<00:20, 13.28it/s]

tensor(16.5823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6096, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.5203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5197, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.4551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4395, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:02<00:20, 13.27it/s]

tensor(16.3873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3684, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.3170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3056, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2450, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2500, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:02<00:19, 13.22it/s]

tensor(16.1709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2019, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1602, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0174, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1247, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:19, 13.24it/s]

tensor(15.9366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0963, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8525, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0737, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0564, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:03<00:19, 13.25it/s]

tensor(15.6706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5725, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0360, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:03<00:19, 13.24it/s]

tensor(15.3639, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:03<00:18, 13.25it/s]

tensor(15.0228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0332, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:03<00:18, 13.20it/s]

tensor(14.6657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5583, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:04<00:18, 13.10it/s]

tensor(14.3747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:04<00:18, 13.13it/s]

tensor(14.1640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0957, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:04<00:18, 13.20it/s]

tensor(13.9614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8492, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:04<00:17, 13.17it/s]

tensor(13.8037, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:05<00:17, 13.17it/s]

tensor(13.7019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:05<00:17, 13.18it/s]

tensor(13.6053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:05<00:17, 13.18it/s]

tensor(13.4948, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:05<00:17, 13.15it/s]

tensor(13.3975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:06<00:16, 13.06it/s]

tensor(13.3201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:06<00:16, 13.14it/s]

tensor(13.2455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:06<00:16, 13.15it/s]

tensor(13.1743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:06<00:16, 13.13it/s]

tensor(13.1136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0953, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:07<00:15, 13.12it/s]

tensor(13.0600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0427, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:07<00:15, 13.13it/s]

tensor(13.0084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:07<00:15, 13.08it/s]

tensor(12.9587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:07<00:15, 13.08it/s]

tensor(12.9122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([189, 141,  75, 112, 102, 332,  31,  86, 360, 120, 205,  55,  35,  96])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:07, 28.70it/s]
  1%|          | 10/1939 [00:00<00:44, 43.47it/s]
  1%|          | 16/1939 [00:00<00:42, 44.73it/s]
  1%|          | 21/1939 [00:00<01:11, 26.80it/s]
  1%|▏         | 25/1939 [00:00<01:14, 25.84it/s]
  2%|▏         | 30/1939 [00:00<01:01, 31.00it/s]
  2%|▏         | 34/1939 [00:01<01:22, 23.07it/s]
  2%|▏         | 37/1939 [00:01<01:39, 19.14it/s]
  2%|▏         | 41/1939 [00:01<01:46, 17.77it/s]
  2%|▏         | 44/1939 [00:01<01:53, 16.64it/s]
  2%|▏         | 46/1939 [00:02<01:51, 16.98it/s]
  3%|▎         | 49/1939 [00:02<01:43, 18.32it/s]
  3%|▎         | 51/1939 [00:02<01:46, 17.69it/s]
  3%|▎         | 53/1939 [00:02<01:58, 15.94it/s]
  3%|▎         | 55/1939 [00:02<01:56, 16.17it/s]
  3%|▎         | 57/1939 [00:02<02:57, 10.62it/s]
  3%|▎         | 59/1939 [00:03<03:13,  9.73it/s]
  3%|▎         | 62/1939 [00:03<02:36, 12.03it/s]
  3%|▎         | 64/1939 [00:03<02:21, 13.28it/s]
  3%|▎         | 66/1939 [00:03<02:46, 11.27it/s]
  4%|▎         | 68/1939 [00:03<02:34, 12.12it/s]
  4%|▎         | 72/1939 [00:03<01:47, 17.29it/s]
  4%|▍         | 75/1939 [00:04<02:30, 12.36it/s]
  4%|▍         | 78/1939 [00:04<02:14, 13.87it/s]
  4%|▍         | 80/1939 [00:04<02:35, 11.99it/s]
  4%|▍         | 82/1939 [00:05<03:37,  8.54it/s]
  4%|▍         | 84/1939 [00:05<03:19,  9.30it/s]
  4%|▍         | 86/1939 [00:05<03:18,  9.31it/s]
  5%|▍         | 88/1939 [00:05<02:56, 10.46it/s]
  5%|▍         | 91/1939 [00:05<02:14, 13.69it/s]
  5%|▍         | 94/1939 [00:05<02:03, 14.92it/s]
  5%|▍         | 96/1939 [00:06<02:25, 12.69it/s]
  5%|▌         | 98/1939 [00:06<02:13, 13.80it/s]
  5%|▌         | 100/1939 [00:06<03:07,  9.79it/s]
  5%|▌         | 102/1939 [00:07<04:00,  7.63it/s]
  5%|▌         | 105/1939 [00:07<03:46,  8.10it/s]
  6%|▌         | 107/1939 [00:07<04:04,  7.48it/s]
  6%|▌         | 110/1939 [00:07<03:07,  9.74it/s]
  6%|▌         | 114/1939 [00:08<02:50, 10.69it/s]
  6%|▌         | 116/1939 [00:08<03:02,  9.99it/s]
  6%|▌         | 118/1939 [00:08<04:01,  7.55it/s]
  6%|▌         | 120/1939 [00:09<03:58,  7.62it/s]
  6%|▌         | 121/1939 [00:09<04:47,  6.33it/s]
  6%|▋         | 123/1939 [00:09<03:47,  7.99it/s]
  7%|▋         | 128/1939 [00:09<03:01,  9.97it/s]
  7%|▋         | 131/1939 [00:10<02:28, 12.14it/s]
  7%|▋         | 133/1939 [00:10<02:44, 10.97it/s]
  7%|▋         | 135/1939 [00:10<03:27,  8.71it/s]
  7%|▋         | 137/1939 [00:11<03:48,  7.88it/s]
  7%|▋         | 138/1939 [00:11<04:46,  6.28it/s]
  7%|▋         | 139/1939 [00:11<05:34,  5.39it/s]
  7%|▋         | 141/1939 [00:12<05:24,  5.54it/s]
  7%|▋         | 142/1939 [00:12<06:09,  4.87it/s]
  7%|▋         | 144/1939 [00:12<04:38,  6.44it/s]
  7%|▋         | 145/1939 [00:12<05:01,  5.96it/s]
  8%|▊         | 147/1939 [00:12<03:51,  7.74it/s]
  8%|▊         | 149/1939 [00:13<04:06,  7.26it/s]
  8%|▊         | 151/1939 [00:13<03:28,  8.57it/s]
  8%|▊         | 153/1939 [00:13<03:21,  8.88it/s]
  8%|▊         | 156/1939 [00:13<02:31, 11.74it/s]
  8%|▊         | 158/1939 [00:14<03:45,  7.88it/s]
  8%|▊         | 160/1939 [00:14<03:51,  7.69it/s]
  8%|▊         | 161/1939 [00:14<04:33,  6.50it/s]
  8%|▊         | 162/1939 [00:14<04:41,  6.30it/s]
  8%|▊         | 163/1939 [00:14<04:42,  6.28it/s]
  8%|▊         | 164/1939 [00:15<04:31,  6.54it/s]
  9%|▊         | 166/1939 [00:15<03:18,  8.92it/s]
  9%|▉         | 172/1939 [00:15<01:35, 18.54it/s]
  9%|▉         | 175/1939 [00:15<01:26, 20.37it/s]
  9%|▉         | 178/1939 [00:15<01:18, 22.55it/s]
  9%|▉         | 181/1939 [00:15<01:54, 15.41it/s]
  9%|▉         | 184/1939 [00:15<01:37, 18.01it/s]
 10%|▉         | 187/1939 [00:16<02:02, 14.31it/s]
 10%|▉         | 189/1939 [00:16<01:59, 14.68it/s]
 10%|▉         | 191/1939 [00:16<01:53, 15.40it/s]
 10%|█         | 194/1939 [00:16<01:40, 17.35it/s]
 10%|█         | 199/1939 [00:16<01:19, 21.83it/s]
 10%|█         | 202/1939 [00:17<01:52, 15.39it/s]
 33%|███▎      | 100/300 [00:26<00:15, 13.08it/s]]
 11%|█         | 206/1939 [00:17<02:44, 10.55it/s]
 11%|█         | 209/1939 [00:17<02:18, 12.46it/s]
 11%|█         | 211/1939 [00:18<02:35, 11.13it/s]
 11%|█         | 213/1939 [00:18<03:18,  8.70it/s]
 11%|█         | 216/1939 [00:18<02:31, 11.41it/s]
 11%|█         | 218/1939 [00:18<02:54,  9.86it/s]
 11%|█▏        | 220/1939 [00:19<02:38, 10.82it/s]
 11%|█▏        | 222/1939 [00:19<03:04,  9.32it/s]
 12%|█▏        | 224/1939 [00:19<03:17,  8.70it/s]
 12%|█▏        | 226/1939 [00:19<02:50, 10.06it/s]
 12%|█▏        | 228/1939 [00:20<03:28,  8.20it/s]
 12%|█▏        | 230/1939 [00:20<03:36,  7.89it/s]
 12%|█▏        | 232/1939 [00:20<03:04,  9.26it/s]
 12%|█▏        | 234/1939 [00:20<02:47, 10.16it/s]
 12%|█▏        | 236/1939 [00:20<02:50,  9.97it/s]
 12%|█▏        | 239/1939 [00:21<02:58,  9.53it/s]
 12%|█▏        | 241/1939 [00:21<03:56,  7.19it/s]
 12%|█▏        | 242/1939 [00:21<04:08,  6.84it/s]
 13%|█▎        | 243/1939 [00:22<05:02,  5.60it/s]
 13%|█▎        | 244/1939 [00:22<06:07,  4.62it/s]
 13%|█▎        | 245/1939 [00:22<06:43,  4.20it/s]
 13%|█▎        | 246/1939 [00:23<07:02,  4.01it/s]
 13%|█▎        | 248/1939 [00:23<06:04,  4.64it/s]
 13%|█▎        | 250/1939 [00:23<05:44,  4.90it/s]
 13%|█▎        | 251/1939 [00:24<06:40,  4.22it/s]
 13%|█▎        | 254/1939 [00:24<04:04,  6.90it/s]
 13%|█▎        | 256/1939 [00:24<03:17,  8.54it/s]
 13%|█▎        | 258/1939 [00:24<03:45,  7.45it/s]
 13%|█▎        | 260/1939 [00:24<03:25,  8.19it/s]
 14%|█▎        | 263/1939 [00:25<02:57,  9.43it/s]
 14%|█▎        | 265/1939 [00:25<02:53,  9.65it/s]
 14%|█▍        | 268/1939 [00:25<02:51,  9.74it/s]
 14%|█▍        | 270/1939 [00:25<03:11,  8.70it/s]
 14%|█▍        | 272/1939 [00:26<02:45, 10.07it/s]
 14%|█▍        | 274/1939 [00:26<02:54,  9.57it/s]
 14%|█▍        | 276/1939 [00:26<02:31, 10.97it/s]
 14%|█▍        | 281/1939 [00:26<01:54, 14.49it/s]
 15%|█▍        | 284/1939 [00:26<02:04, 13.33it/s]
 15%|█▍        | 286/1939 [00:27<02:44, 10.06it/s]
 15%|█▍        | 288/1939 [00:27<04:16,  6.44it/s]
 15%|█▍        | 290/1939 [00:28<03:31,  7.78it/s]
 15%|█▌        | 293/1939 [00:28<03:29,  7.87it/s]
 15%|█▌        | 295/1939 [00:28<02:57,  9.26it/s]
 15%|█▌        | 297/1939 [00:28<03:24,  8.02it/s]
 15%|█▌        | 299/1939 [00:29<04:17,  6.38it/s]
 15%|█▌        | 300/1939 [00:29<04:52,  5.61it/s]
 16%|█▌        | 302/1939 [00:29<03:45,  7.25it/s]
 16%|█▌        | 304/1939 [00:30<03:42,  7.36it/s]
 16%|█▌        | 306/1939 [00:30<03:04,  8.84it/s]
 16%|█▌        | 308/1939 [00:30<03:09,  8.61it/s]
 16%|█▌        | 310/1939 [00:30<02:51,  9.52it/s]
 16%|█▌        | 312/1939 [00:30<02:28, 10.97it/s]
 16%|█▌        | 315/1939 [00:30<02:26, 11.08it/s]
 16%|█▋        | 317/1939 [00:31<03:28,  7.77it/s]
 16%|█▋        | 319/1939 [00:31<04:05,  6.61it/s]
 17%|█▋        | 320/1939 [00:31<04:11,  6.44it/s]
 17%|█▋        | 321/1939 [00:32<05:03,  5.33it/s]
 17%|█▋        | 322/1939 [00:32<04:43,  5.70it/s]
 17%|█▋        | 324/1939 [00:32<03:27,  7.78it/s]
 17%|█▋        | 326/1939 [00:32<04:20,  6.19it/s]
 17%|█▋        | 328/1939 [00:33<04:08,  6.49it/s]
 17%|█▋        | 329/1939 [00:33<04:40,  5.75it/s]
 17%|█▋        | 330/1939 [00:33<04:55,  5.45it/s]
 17%|█▋        | 333/1939 [00:33<03:00,  8.88it/s]
 17%|█▋        | 335/1939 [00:34<03:07,  8.57it/s]
 17%|█▋        | 337/1939 [00:34<03:51,  6.93it/s]
 17%|█▋        | 338/1939 [00:34<04:11,  6.36it/s]
 17%|█▋        | 339/1939 [00:34<04:29,  5.94it/s]
 18%|█▊        | 340/1939 [00:35<04:44,  5.62it/s]
 18%|█▊        | 342/1939 [00:35<04:35,  5.80it/s]
 18%|█▊        | 343/1939 [00:35<04:35,  5.78it/s]
 18%|█▊        | 345/1939 [00:35<03:44,  7.09it/s]
 18%|█▊        | 347/1939 [00:36<03:51,  6.87it/s]
 18%|█▊        | 349/1939 [00:36<03:11,  8.29it/s]
 18%|█▊        | 350/1939 [00:36<03:21,  7.88it/s]
 18%|█▊        | 351/1939 [00:36<03:30,  7.53it/s]
 18%|█▊        | 352/1939 [00:36<03:41,  7.17it/s]
 18%|█▊        | 354/1939 [00:36<02:50,  9.29it/s]
 18%|█▊        | 356/1939 [00:37<03:02,  8.69it/s]
 19%|█▊        | 359/1939 [00:37<02:08, 12.33it/s]
 19%|█▊        | 361/1939 [00:37<02:58,  8.87it/s]
 19%|█▊        | 363/1939 [00:37<02:35, 10.15it/s]
 19%|█▉        | 365/1939 [00:37<02:14, 11.75it/s]
 19%|█▉        | 367/1939 [00:38<02:21, 11.10it/s]
 19%|█▉        | 370/1939 [00:38<02:16, 11.49it/s]
 19%|█▉        | 372/1939 [00:38<02:48,  9.28it/s]
 19%|█▉        | 374/1939 [00:38<02:32, 10.28it/s]
 19%|█▉        | 376/1939 [00:38<02:18, 11.25it/s]
 19%|█▉        | 378/1939 [00:39<02:26, 10.65it/s]
 20%|█▉        | 381/1939 [00:39<02:19, 11.19it/s]
 20%|█▉        | 383/1939 [00:39<02:13, 11.66it/s]
 20%|█▉        | 385/1939 [00:39<02:20, 11.05it/s]
 20%|█▉        | 387/1939 [00:39<02:22, 10.89it/s]
 20%|██        | 389/1939 [00:40<03:07,  8.27it/s]
 20%|██        | 390/1939 [00:40<03:08,  8.23it/s]
 20%|██        | 391/1939 [00:40<03:18,  7.80it/s]
 20%|██        | 392/1939 [00:40<03:27,  7.47it/s]
 20%|██        | 393/1939 [00:41<04:21,  5.92it/s]
 20%|██        | 394/1939 [00:41<04:15,  6.04it/s]
 20%|██        | 396/1939 [00:41<03:38,  7.05it/s]
 20%|██        | 397/1939 [00:41<03:47,  6.77it/s]
 21%|██        | 398/1939 [00:41<04:49,  5.33it/s]
 21%|██        | 399/1939 [00:42<04:35,  5.60it/s]
 21%|██        | 401/1939 [00:42<03:15,  7.86it/s]
 21%|██        | 404/1939 [00:42<03:03,  8.37it/s]
 21%|██        | 405/1939 [00:42<03:22,  7.59it/s]
 21%|██        | 407/1939 [00:43<03:53,  6.56it/s]
 21%|██        | 410/1939 [00:43<02:39,  9.59it/s]
 21%|██        | 412/1939 [00:43<03:40,  6.93it/s]
 21%|██▏       | 415/1939 [00:44<03:34,  7.11it/s]
 21%|██▏       | 416/1939 [00:44<04:17,  5.91it/s]
 22%|██▏       | 417/1939 [00:44<04:32,  5.59it/s]
 22%|██▏       | 419/1939 [00:44<04:05,  6.19it/s]
 22%|██▏       | 422/1939 [00:45<03:26,  7.34it/s]
 22%|██▏       | 425/1939 [00:45<02:29, 10.11it/s]
 22%|██▏       | 427/1939 [00:45<03:01,  8.34it/s]
 22%|██▏       | 429/1939 [00:45<02:53,  8.70it/s]
 22%|██▏       | 431/1939 [00:45<02:26, 10.32it/s]
 22%|██▏       | 433/1939 [00:46<02:44,  9.18it/s]
 23%|██▎       | 437/1939 [00:46<01:48, 13.85it/s]
 23%|██▎       | 443/1939 [00:46<01:07, 22.22it/s]
 23%|██▎       | 450/1939 [00:46<00:47, 31.25it/s]
 24%|██▎       | 456/1939 [00:46<00:57, 25.87it/s]
 24%|██▎       | 460/1939 [00:46<00:56, 26.16it/s]
 24%|██▍       | 468/1939 [00:47<00:40, 35.92it/s]
 24%|██▍       | 473/1939 [00:47<01:10, 20.79it/s]
 25%|██▍       | 477/1939 [00:47<01:14, 19.74it/s]
 25%|██▍       | 480/1939 [00:48<01:15, 19.39it/s]
 25%|██▍       | 483/1939 [00:48<01:10, 20.65it/s]
 25%|██▌       | 489/1939 [00:48<01:09, 21.01it/s]
 25%|██▌       | 492/1939 [00:49<02:06, 11.42it/s]
 25%|██▌       | 494/1939 [00:49<01:59, 12.04it/s]
 26%|██▌       | 496/1939 [00:49<03:09,  7.63it/s]
 26%|██▌       | 499/1939 [00:49<02:27,  9.75it/s]
 26%|██▌       | 501/1939 [00:50<02:32,  9.45it/s]
 26%|██▌       | 504/1939 [00:50<02:02, 11.75it/s]
 26%|██▌       | 506/1939 [00:50<01:58, 12.05it/s]
 26%|██▋       | 509/1939 [00:50<01:35, 15.02it/s]
 26%|██▋       | 512/1939 [00:50<01:49, 13.03it/s]
 27%|██▋       | 514/1939 [00:50<01:45, 13.49it/s]
 27%|██▋       | 516/1939 [00:51<01:47, 13.18it/s]
 27%|██▋       | 518/1939 [00:51<01:57, 12.08it/s]
 27%|██▋       | 520/1939 [00:51<02:34,  9.21it/s]
 27%|██▋       | 522/1939 [00:52<02:56,  8.02it/s]
 27%|██▋       | 523/1939 [00:52<03:13,  7.33it/s]
 27%|██▋       | 525/1939 [00:52<03:16,  7.18it/s]
 27%|██▋       | 526/1939 [00:52<03:33,  6.61it/s]
 27%|██▋       | 527/1939 [00:53<04:13,  5.57it/s]
 27%|██▋       | 529/1939 [00:53<03:43,  6.31it/s]
 27%|██▋       | 531/1939 [00:53<03:35,  6.53it/s]
 27%|██▋       | 533/1939 [00:53<03:27,  6.78it/s]
 28%|██▊       | 534/1939 [00:54<03:58,  5.88it/s]
 28%|██▊       | 536/1939 [00:54<03:29,  6.68it/s]
 28%|██▊       | 537/1939 [00:54<03:49,  6.10it/s]
 28%|██▊       | 538/1939 [00:54<04:38,  5.04it/s]
 28%|██▊       | 539/1939 [00:55<05:18,  4.39it/s]
 28%|██▊       | 541/1939 [00:55<03:45,  6.19it/s]
 28%|██▊       | 543/1939 [00:55<02:48,  8.28it/s]
 28%|██▊       | 546/1939 [00:55<02:29,  9.33it/s]
 28%|██▊       | 548/1939 [00:56<03:19,  6.96it/s]
 28%|██▊       | 551/1939 [00:56<02:48,  8.24it/s]
 28%|██▊       | 552/1939 [00:56<03:27,  6.67it/s]
 29%|██▊       | 554/1939 [00:56<02:46,  8.31it/s]
 29%|██▊       | 556/1939 [00:57<03:24,  6.77it/s]
 29%|██▉       | 558/1939 [00:57<02:56,  7.82it/s]
 29%|██▉       | 561/1939 [00:57<02:57,  7.76it/s]
 29%|██▉       | 562/1939 [00:58<03:41,  6.21it/s]
 29%|██▉       | 564/1939 [00:58<02:54,  7.88it/s]
 29%|██▉       | 567/1939 [00:58<02:49,  8.10it/s]
 29%|██▉       | 569/1939 [00:58<02:47,  8.19it/s]
 29%|██▉       | 571/1939 [00:59<03:15,  6.99it/s]
 29%|██▉       | 572/1939 [00:59<03:26,  6.62it/s]
 30%|██▉       | 574/1939 [00:59<03:23,  6.70it/s]
 30%|██▉       | 575/1939 [00:59<04:02,  5.63it/s]
 30%|██▉       | 578/1939 [01:00<02:39,  8.56it/s]
 30%|██▉       | 580/1939 [01:00<03:00,  7.51it/s]
 30%|███       | 582/1939 [01:00<03:22,  6.70it/s]
 30%|███       | 584/1939 [01:01<03:10,  7.12it/s]
 30%|███       | 586/1939 [01:01<03:07,  7.21it/s]
 30%|███       | 589/1939 [01:01<03:06,  7.26it/s]
 31%|███       | 592/1939 [01:02<02:59,  7.51it/s]
 31%|███       | 593/1939 [01:02<03:31,  6.35it/s]
 31%|███       | 595/1939 [01:02<03:37,  6.17it/s]
 31%|███       | 597/1939 [01:02<02:57,  7.58it/s]
 31%|███       | 599/1939 [01:03<02:51,  7.80it/s]
 31%|███       | 601/1939 [01:03<03:14,  6.88it/s]
 31%|███       | 603/1939 [01:03<02:43,  8.16it/s]
 31%|███       | 604/1939 [01:03<03:26,  6.46it/s]
 31%|███▏      | 606/1939 [01:04<02:44,  8.12it/s]
 31%|███▏      | 608/1939 [01:04<03:37,  6.13it/s]
 32%|███▏      | 611/1939 [01:04<03:12,  6.90it/s]
 32%|███▏      | 612/1939 [01:05<03:35,  6.16it/s]
 32%|███▏      | 613/1939 [01:05<04:09,  5.32it/s]
 32%|███▏      | 614/1939 [01:05<04:02,  5.46it/s]
 32%|███▏      | 615/1939 [01:05<04:30,  4.90it/s]
 32%|███▏      | 616/1939 [01:06<04:25,  4.98it/s]
 32%|███▏      | 617/1939 [01:06<03:53,  5.66it/s]
 32%|███▏      | 618/1939 [01:06<03:51,  5.71it/s]
 32%|███▏      | 620/1939 [01:06<02:59,  7.37it/s]
 32%|███▏      | 621/1939 [01:06<03:08,  6.99it/s]
 32%|███▏      | 622/1939 [01:06<03:01,  7.24it/s]
 32%|███▏      | 625/1939 [01:06<02:00, 10.90it/s]
 32%|███▏      | 629/1939 [01:07<01:42, 12.76it/s]
 33%|███▎      | 631/1939 [01:07<01:57, 11.15it/s]
 33%|███▎      | 633/1939 [01:07<02:25,  9.01it/s]
 33%|███▎      | 636/1939 [01:08<02:16,  9.54it/s]
 33%|███▎      | 637/1939 [01:08<02:56,  7.37it/s]
 33%|███▎      | 639/1939 [01:08<02:26,  8.87it/s]
 33%|███▎      | 641/1939 [01:08<02:34,  8.41it/s]
 33%|███▎      | 643/1939 [01:09<02:37,  8.22it/s]
 33%|███▎      | 646/1939 [01:09<01:58, 10.93it/s]
 33%|███▎      | 649/1939 [01:09<01:51, 11.59it/s]
 34%|███▎      | 651/1939 [01:09<02:08, 10.00it/s]
 34%|███▎      | 653/1939 [01:10<02:40,  8.01it/s]
 34%|███▎      | 654/1939 [01:10<02:57,  7.24it/s]
 34%|███▍      | 656/1939 [01:10<02:55,  7.29it/s]
 34%|███▍      | 657/1939 [01:10<03:12,  6.67it/s]
 34%|███▍      | 658/1939 [01:11<03:54,  5.45it/s]
 34%|███▍      | 659/1939 [01:11<04:01,  5.29it/s]
 34%|███▍      | 661/1939 [01:11<02:55,  7.26it/s]
 34%|███▍      | 665/1939 [01:11<02:15,  9.40it/s]
 34%|███▍      | 667/1939 [01:11<02:20,  9.06it/s]
 34%|███▍      | 668/1939 [01:12<03:04,  6.89it/s]
 35%|███▍      | 670/1939 [01:12<02:30,  8.46it/s]
 35%|███▍      | 672/1939 [01:12<02:20,  9.01it/s]
 35%|███▍      | 674/1939 [01:12<02:47,  7.56it/s]
 35%|███▍      | 676/1939 [01:13<03:15,  6.45it/s]
 35%|███▍      | 678/1939 [01:13<03:30,  5.98it/s]
 35%|███▌      | 680/1939 [01:14<03:15,  6.45it/s]
 35%|███▌      | 683/1939 [01:14<02:44,  7.63it/s]
 35%|███▌      | 687/1939 [01:14<02:24,  8.64it/s]
 35%|███▌      | 688/1939 [01:14<02:54,  7.16it/s]
 36%|███▌      | 689/1939 [01:15<03:26,  6.04it/s]
 36%|███▌      | 691/1939 [01:15<02:43,  7.65it/s]
 36%|███▌      | 692/1939 [01:15<03:00,  6.92it/s]
 36%|███▌      | 693/1939 [01:15<03:16,  6.35it/s]
 36%|███▌      | 696/1939 [01:15<02:06,  9.80it/s]
 36%|███▌      | 699/1939 [01:16<01:50, 11.18it/s]
 36%|███▌      | 701/1939 [01:16<01:40, 12.30it/s]
 36%|███▋      | 707/1939 [01:16<00:57, 21.53it/s]
 37%|███▋      | 710/1939 [01:16<01:13, 16.63it/s]
 37%|███▋      | 714/1939 [01:16<00:59, 20.44it/s]
 37%|███▋      | 720/1939 [01:16<00:43, 27.83it/s]
 37%|███▋      | 724/1939 [01:17<00:57, 21.30it/s]
 37%|███▋      | 727/1939 [01:17<01:00, 19.91it/s]
 38%|███▊      | 730/1939 [01:17<01:14, 16.24it/s]
 38%|███▊      | 733/1939 [01:18<01:45, 11.48it/s]
 38%|███▊      | 735/1939 [01:18<02:12,  9.07it/s]
 38%|███▊      | 739/1939 [01:18<01:43, 11.63it/s]
 38%|███▊      | 742/1939 [01:18<01:46, 11.27it/s]
 38%|███▊      | 744/1939 [01:19<01:37, 12.31it/s]
 38%|███▊      | 746/1939 [01:19<02:00,  9.88it/s]
 39%|███▊      | 749/1939 [01:19<01:52, 10.54it/s]
 39%|███▊      | 751/1939 [01:19<02:05,  9.47it/s]
 39%|███▉      | 753/1939 [01:20<01:52, 10.50it/s]
 39%|███▉      | 755/1939 [01:20<01:55, 10.29it/s]
 39%|███▉      | 757/1939 [01:20<02:00,  9.77it/s]
 39%|███▉      | 759/1939 [01:20<01:44, 11.28it/s]
 39%|███▉      | 761/1939 [01:20<01:57, 10.04it/s]
 39%|███▉      | 763/1939 [01:21<02:03,  9.51it/s]
 39%|███▉      | 765/1939 [01:21<01:47, 10.89it/s]
 40%|███▉      | 767/1939 [01:21<02:45,  7.08it/s]
 40%|███▉      | 768/1939 [01:22<03:27,  5.63it/s]
 40%|███▉      | 769/1939 [01:22<03:31,  5.53it/s]
 40%|███▉      | 770/1939 [01:22<03:42,  5.25it/s]
 40%|███▉      | 771/1939 [01:22<03:53,  5.00it/s]
 40%|███▉      | 772/1939 [01:22<04:06,  4.73it/s]
 40%|███▉      | 773/1939 [01:23<03:38,  5.34it/s]
 40%|███▉      | 775/1939 [01:23<03:12,  6.04it/s]
 40%|████      | 776/1939 [01:23<02:56,  6.59it/s]
 40%|████      | 777/1939 [01:23<02:59,  6.46it/s]
 40%|████      | 779/1939 [01:24<03:12,  6.02it/s]
 40%|████      | 780/1939 [01:24<03:51,  5.00it/s]
 40%|████      | 782/1939 [01:24<02:49,  6.83it/s]
 40%|████      | 784/1939 [01:24<02:41,  7.13it/s]
 41%|████      | 787/1939 [01:24<02:05,  9.21it/s]
 41%|████      | 789/1939 [01:25<02:00,  9.57it/s]
 41%|████      | 791/1939 [01:25<01:42, 11.15it/s]
 41%|████      | 794/1939 [01:25<01:46, 10.75it/s]
 41%|████      | 796/1939 [01:25<01:34, 12.09it/s]
 41%|████      | 798/1939 [01:25<01:46, 10.69it/s]
 41%|████▏     | 800/1939 [01:26<01:56,  9.74it/s]
 41%|████▏     | 802/1939 [01:26<01:43, 11.02it/s]
 41%|████▏     | 804/1939 [01:26<01:56,  9.72it/s]
 42%|████▏     | 806/1939 [01:26<02:03,  9.17it/s]
 42%|████▏     | 808/1939 [01:26<01:47, 10.55it/s]
 42%|████▏     | 810/1939 [01:27<02:04,  9.10it/s]
 42%|████▏     | 812/1939 [01:27<02:15,  8.30it/s]
 42%|████▏     | 813/1939 [01:27<02:30,  7.49it/s]
 42%|████▏     | 815/1939 [01:27<02:00,  9.31it/s]
 42%|████▏     | 817/1939 [01:28<02:58,  6.29it/s]
 42%|████▏     | 818/1939 [01:28<03:12,  5.82it/s]
 42%|████▏     | 819/1939 [01:28<03:14,  5.76it/s]
 42%|████▏     | 820/1939 [01:28<03:08,  5.94it/s]
 42%|████▏     | 821/1939 [01:28<02:59,  6.23it/s]
 42%|████▏     | 822/1939 [01:29<03:15,  5.70it/s]
 42%|████▏     | 823/1939 [01:29<03:19,  5.60it/s]
 43%|████▎     | 825/1939 [01:29<02:55,  6.35it/s]
 43%|████▎     | 826/1939 [01:29<03:36,  5.15it/s]
 43%|████▎     | 828/1939 [01:30<03:37,  5.11it/s]
 43%|████▎     | 829/1939 [01:30<04:16,  4.33it/s]
 43%|████▎     | 831/1939 [01:30<02:59,  6.16it/s]
 43%|████▎     | 834/1939 [01:31<02:34,  7.17it/s]
 43%|████▎     | 837/1939 [01:31<01:51,  9.86it/s]
 43%|████▎     | 839/1939 [01:31<02:05,  8.78it/s]
 43%|████▎     | 841/1939 [01:31<01:48, 10.13it/s]
 44%|████▎     | 844/1939 [01:32<01:55,  9.45it/s]
 44%|████▎     | 846/1939 [01:32<01:41, 10.81it/s]
 44%|████▍     | 851/1939 [01:32<01:30, 12.06it/s]
 44%|████▍     | 853/1939 [01:32<01:22, 13.19it/s]
 44%|████▍     | 855/1939 [01:32<01:47, 10.05it/s]
 44%|████▍     | 857/1939 [01:33<02:05,  8.63it/s]
 44%|████▍     | 859/1939 [01:33<02:27,  7.31it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 333.88it/s]
 34%|███▎      | 101/300 [03:38<2:03:42, 37.30s/it]

[[np.int64(0), False, 10], [np.int64(1), False, 10], [np.int64(2), False, 11], [np.int64(3), False, 1], [np.int64(4), False, 7], [np.int64(5), False, 10], [np.int64(6), False, 7], [np.int64(8), False, 5], [np.int64(9), False, 4], [np.int64(11), False, 7], [np.int64(12), False, 5], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8524, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.8835, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9120, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▍      | 102/300 [03:38<1:38:24, 29.82s/it]

tensor(12.8798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0685, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:39<1:01:57, 18.97s/it]

tensor(12.8936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2379, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3967, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5052, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [03:39<40:24, 12.50s/it]

tensor(12.9954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5900, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [03:39<26:56,  8.42s/it]

tensor(13.0126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6482, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0121, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7113, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7839, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [03:39<18:14,  5.76s/it]

tensor(12.9736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8474, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9453, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8997, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [03:39<12:29,  3.98s/it]

tensor(12.9158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9426, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [03:39<08:37,  2.78s/it]

tensor(12.8854, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9808, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8540, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0166, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0459, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:40<06:00,  1.96s/it]

tensor(12.7907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0762, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1009, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [03:40<04:13,  1.39s/it]

tensor(12.7440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1280, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [03:40<02:59,  1.00it/s]

tensor(12.7297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1587, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1875, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2147, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [03:40<02:09,  1.37it/s]

tensor(12.6951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2352, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2563, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [03:40<01:34,  1.86it/s]

tensor(12.6653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2757, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [03:41<01:10,  2.47it/s]

tensor(12.6505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2941, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6367, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3176, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3352, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [03:41<00:53,  3.20it/s]

tensor(12.6106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3511, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3693, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [03:41<00:41,  4.05it/s]

tensor(12.5818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3815, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [03:41<00:33,  4.97it/s]

tensor(12.5674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3965, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4111, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5396, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4191, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [03:41<00:28,  5.90it/s]

tensor(12.5264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4288, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4380, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [03:42<00:24,  6.80it/s]

tensor(12.5016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4494, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [03:42<00:21,  7.57it/s]

tensor(12.4896, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4577, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4647, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4756, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [03:42<00:19,  8.26it/s]

tensor(12.4558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4826, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4934, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:42<00:17,  8.84it/s]

tensor(12.4365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5009, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:42<00:16,  9.30it/s]

tensor(12.4271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5079, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5113, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5181, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [03:43<00:16,  9.57it/s]

tensor(12.4004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5214, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5288, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [03:43<00:15,  9.80it/s]

tensor(12.3843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5333, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:43<00:15,  9.92it/s]

tensor(12.3766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5387, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 34,  67, 129, 117, 307,  31, 212, 143, 128, 187, 312,  27,  82, 163])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 2/1939 [00:00<01:46, 18.26it/s]
  0%|          | 6/1939 [00:00<01:54, 16.92it/s]
  0%|          | 9/1939 [00:00<01:37, 19.82it/s]
  1%|          | 15/1939 [00:00<01:03, 30.53it/s]
  1%|          | 19/1939 [00:00<01:30, 21.28it/s]
  1%|          | 24/1939 [00:00<01:12, 26.59it/s]
  1%|▏         | 28/1939 [00:01<01:38, 19.41it/s]
  2%|▏         | 31/1939 [00:01<01:54, 16.61it/s]
  2%|▏         | 34/1939 [00:01<02:20, 13.57it/s]
  2%|▏         | 36/1939 [00:02<02:33, 12.41it/s]
  2%|▏         | 38/1939 [00:02<02:21, 13.43it/s]
  2%|▏         | 41/1939 [00:02<02:25, 13.04it/s]
  2%|▏         | 43/1939 [00:02<02:50, 11.10it/s]
  2%|▏         | 46/1939 [00:02<02:15, 14.00it/s]
  3%|▎         | 49/1939 [00:03<02:20, 13.45it/s]
  3%|▎         | 52/1939 [00:03<01:59, 15.75it/s]
  3%|▎         | 54/1939 [00:03<02:24, 13.07it/s]
  3%|▎         | 58/1939 [00:03<01:47, 17.56it/s]
  3%|▎         | 65/1939 [00:03<01:12, 25.72it/s]
  4%|▎         | 68/1939 [00:04<01:38, 19.00it/s]
  4%|▎         | 71/1939 [00:04<01:40, 18.53it/s]
  4%|▍         | 74/1939 [00:04<01:56, 16.01it/s]
  4%|▍         | 78/1939 [00:04<02:06, 14.70it/s]
  4%|▍         | 80/1939 [00:05<02:31, 12.25it/s]
  4%|▍         | 82/1939 [00:05<02:28, 12.47it/s]
  4%|▍         | 84/1939 [00:05<02:36, 11.85it/s]
  4%|▍         | 86/1939 [00:05<02:31, 12.24it/s]
  5%|▍         | 88/1939 [00:05<02:39, 11.64it/s]
  5%|▍         | 90/1939 [00:05<02:22, 13.00it/s]
  5%|▍         | 94/1939 [00:06<02:15, 13.58it/s]
  5%|▍         | 96/1939 [00:06<02:39, 11.53it/s]
  5%|▌         | 99/1939 [00:06<02:07, 14.48it/s]
  5%|▌         | 101/1939 [00:06<03:10,  9.67it/s]
  5%|▌         | 103/1939 [00:07<02:53, 10.58it/s]
  5%|▌         | 105/1939 [00:07<03:09,  9.70it/s]
  6%|▌         | 107/1939 [00:07<03:36,  8.47it/s]
  6%|▌         | 109/1939 [00:07<03:01, 10.08it/s]
  6%|▌         | 112/1939 [00:07<02:21, 12.89it/s]
  6%|▌         | 115/1939 [00:07<01:59, 15.31it/s]
  6%|▌         | 117/1939 [00:08<02:36, 11.63it/s]
  6%|▌         | 119/1939 [00:08<02:49, 10.72it/s]
  6%|▌         | 121/1939 [00:08<03:36,  8.40it/s]
  6%|▋         | 123/1939 [00:08<03:06,  9.74it/s]
 50%|█████     | 150/300 [03:56<00:15,  9.92it/s]]
  7%|▋         | 128/1939 [00:09<02:40, 11.27it/s]
  7%|▋         | 130/1939 [00:09<02:27, 12.30it/s]
  7%|▋         | 132/1939 [00:09<03:01,  9.95it/s]
  7%|▋         | 134/1939 [00:09<02:40, 11.28it/s]
  7%|▋         | 136/1939 [00:10<02:52, 10.47it/s]
  7%|▋         | 138/1939 [00:10<03:05,  9.73it/s]
  7%|▋         | 140/1939 [00:10<03:19,  9.01it/s]
  7%|▋         | 141/1939 [00:10<03:22,  8.87it/s]
  7%|▋         | 143/1939 [00:10<02:48, 10.63it/s]
  7%|▋         | 145/1939 [00:11<03:25,  8.72it/s]
  8%|▊         | 147/1939 [00:11<03:02,  9.80it/s]
  8%|▊         | 150/1939 [00:11<02:14, 13.32it/s]
  8%|▊         | 153/1939 [00:11<02:51, 10.42it/s]
  8%|▊         | 156/1939 [00:11<02:14, 13.29it/s]
  8%|▊         | 158/1939 [00:12<03:10,  9.33it/s]
  8%|▊         | 160/1939 [00:12<04:14,  7.00it/s]
  8%|▊         | 162/1939 [00:13<04:48,  6.16it/s]
  8%|▊         | 163/1939 [00:13<05:00,  5.91it/s]
  8%|▊         | 164/1939 [00:13<05:37,  5.26it/s]
  9%|▊         | 166/1939 [00:13<04:17,  6.89it/s]
  9%|▉         | 170/1939 [00:14<03:02,  9.71it/s]
  9%|▉         | 173/1939 [00:14<02:22, 12.42it/s]
  9%|▉         | 179/1939 [00:14<01:53, 15.49it/s]
  9%|▉         | 181/1939 [00:14<01:51, 15.83it/s]
 10%|▉         | 185/1939 [00:14<01:51, 15.69it/s]
 10%|▉         | 187/1939 [00:14<01:48, 16.09it/s]
 10%|█         | 194/1939 [00:15<01:07, 25.76it/s]
 10%|█         | 198/1939 [00:15<01:32, 18.80it/s]
 10%|█         | 201/1939 [00:15<01:51, 15.64it/s]
 11%|█         | 204/1939 [00:16<02:31, 11.43it/s]
 11%|█         | 206/1939 [00:16<03:07,  9.22it/s]
 11%|█         | 209/1939 [00:16<02:32, 11.34it/s]
 11%|█         | 211/1939 [00:16<02:42, 10.66it/s]
 11%|█         | 213/1939 [00:17<02:25, 11.87it/s]
 11%|█         | 218/1939 [00:17<02:01, 14.18it/s]
 11%|█▏        | 220/1939 [00:17<01:58, 14.53it/s]
 11%|█▏        | 222/1939 [00:17<02:09, 13.25it/s]
 12%|█▏        | 224/1939 [00:17<02:32, 11.25it/s]
 12%|█▏        | 227/1939 [00:18<02:02, 13.92it/s]
 12%|█▏        | 229/1939 [00:18<02:27, 11.59it/s]
 12%|█▏        | 231/1939 [00:18<02:45, 10.34it/s]
 12%|█▏        | 233/1939 [00:18<02:58,  9.56it/s]
 12%|█▏        | 235/1939 [00:18<02:41, 10.56it/s]
 12%|█▏        | 237/1939 [00:19<02:56,  9.62it/s]
 12%|█▏        | 239/1939 [00:19<02:48, 10.06it/s]
 12%|█▏        | 241/1939 [00:19<04:01,  7.04it/s]
 12%|█▏        | 242/1939 [00:20<04:19,  6.54it/s]
 13%|█▎        | 243/1939 [00:20<04:28,  6.32it/s]
 13%|█▎        | 244/1939 [00:20<04:46,  5.91it/s]
 13%|█▎        | 245/1939 [00:20<05:08,  5.48it/s]
 13%|█▎        | 246/1939 [00:20<05:28,  5.16it/s]
 13%|█▎        | 248/1939 [00:21<04:01,  7.00it/s]
 13%|█▎        | 250/1939 [00:21<03:14,  8.70it/s]
 13%|█▎        | 252/1939 [00:21<02:35, 10.82it/s]
 13%|█▎        | 255/1939 [00:21<01:54, 14.70it/s]
 13%|█▎        | 257/1939 [00:21<02:36, 10.76it/s]
 13%|█▎        | 260/1939 [00:22<02:46, 10.08it/s]
 14%|█▎        | 263/1939 [00:22<02:38, 10.55it/s]
 14%|█▎        | 265/1939 [00:22<02:46, 10.06it/s]
 14%|█▍        | 268/1939 [00:22<02:08, 12.96it/s]
 14%|█▍        | 273/1939 [00:22<01:51, 14.92it/s]
 14%|█▍        | 276/1939 [00:23<02:09, 12.87it/s]
 14%|█▍        | 279/1939 [00:23<01:48, 15.33it/s]
 14%|█▍        | 281/1939 [00:23<01:50, 15.02it/s]
 15%|█▍        | 283/1939 [00:23<01:46, 15.55it/s]
 15%|█▍        | 285/1939 [00:24<02:50,  9.69it/s]
 15%|█▍        | 287/1939 [00:24<03:12,  8.58it/s]
 15%|█▍        | 289/1939 [00:24<03:05,  8.89it/s]
 15%|█▌        | 292/1939 [00:24<02:20, 11.68it/s]
 15%|█▌        | 294/1939 [00:24<02:44, 10.01it/s]
 15%|█▌        | 296/1939 [00:25<02:45,  9.90it/s]
 15%|█▌        | 298/1939 [00:25<03:08,  8.72it/s]
 16%|█▌        | 301/1939 [00:25<02:24, 11.33it/s]
 16%|█▌        | 303/1939 [00:25<02:41, 10.11it/s]
 16%|█▌        | 305/1939 [00:25<02:26, 11.14it/s]
 16%|█▌        | 307/1939 [00:26<02:45,  9.87it/s]
 16%|█▌        | 311/1939 [00:26<01:51, 14.55it/s]
 16%|█▌        | 313/1939 [00:26<02:13, 12.17it/s]
 16%|█▌        | 315/1939 [00:26<02:32, 10.62it/s]
 16%|█▋        | 317/1939 [00:27<03:20,  8.10it/s]
 16%|█▋        | 319/1939 [00:27<04:00,  6.73it/s]
 17%|█▋        | 320/1939 [00:27<04:18,  6.27it/s]
 17%|█▋        | 321/1939 [00:28<04:39,  5.80it/s]
 17%|█▋        | 322/1939 [00:28<04:59,  5.40it/s]
 17%|█▋        | 325/1939 [00:28<03:42,  7.26it/s]
 17%|█▋        | 327/1939 [00:28<03:11,  8.43it/s]
 17%|█▋        | 328/1939 [00:28<03:08,  8.54it/s]
 17%|█▋        | 329/1939 [00:29<03:25,  7.85it/s]
 17%|█▋        | 330/1939 [00:29<04:04,  6.59it/s]
 17%|█▋        | 333/1939 [00:29<02:31, 10.57it/s]
 17%|█▋        | 335/1939 [00:29<02:45,  9.67it/s]
 17%|█▋        | 337/1939 [00:30<03:49,  6.98it/s]
 17%|█▋        | 338/1939 [00:30<04:17,  6.21it/s]
 17%|█▋        | 339/1939 [00:30<04:35,  5.81it/s]
 18%|█▊        | 340/1939 [00:30<04:45,  5.60it/s]
 18%|█▊        | 342/1939 [00:30<04:11,  6.35it/s]
 18%|█▊        | 343/1939 [00:31<04:33,  5.83it/s]
 18%|█▊        | 345/1939 [00:31<04:04,  6.52it/s]
 18%|█▊        | 347/1939 [00:31<03:48,  6.98it/s]
 18%|█▊        | 350/1939 [00:31<03:13,  8.21it/s]
 18%|█▊        | 351/1939 [00:32<03:41,  7.17it/s]
 18%|█▊        | 352/1939 [00:32<04:08,  6.38it/s]
 18%|█▊        | 354/1939 [00:32<03:52,  6.83it/s]
 18%|█▊        | 355/1939 [00:32<04:12,  6.27it/s]
 18%|█▊        | 357/1939 [00:33<03:14,  8.13it/s]
 19%|█▊        | 360/1939 [00:33<02:39,  9.89it/s]
 19%|█▊        | 362/1939 [00:33<02:18, 11.42it/s]
 19%|█▉        | 364/1939 [00:33<02:34, 10.22it/s]
 19%|█▉        | 366/1939 [00:33<02:43,  9.63it/s]
 19%|█▉        | 369/1939 [00:33<02:00, 13.06it/s]
 19%|█▉        | 371/1939 [00:34<02:19, 11.27it/s]
 19%|█▉        | 373/1939 [00:34<02:34, 10.14it/s]
 19%|█▉        | 376/1939 [00:34<02:27, 10.63it/s]
 19%|█▉        | 378/1939 [00:34<02:47,  9.31it/s]
 20%|█▉        | 381/1939 [00:35<02:40,  9.73it/s]
 20%|█▉        | 383/1939 [00:35<02:21, 10.99it/s]
 20%|█▉        | 385/1939 [00:35<02:37,  9.85it/s]
 20%|█▉        | 387/1939 [00:35<02:48,  9.22it/s]
 20%|██        | 389/1939 [00:36<03:27,  7.48it/s]
 20%|██        | 390/1939 [00:36<03:49,  6.76it/s]
 20%|██        | 391/1939 [00:36<04:06,  6.27it/s]
 20%|██        | 393/1939 [00:36<03:44,  6.90it/s]
 20%|██        | 394/1939 [00:37<04:06,  6.27it/s]
 20%|██        | 396/1939 [00:37<04:03,  6.34it/s]
 20%|██        | 397/1939 [00:37<04:15,  6.03it/s]
 21%|██        | 398/1939 [00:37<04:22,  5.86it/s]
 21%|██        | 400/1939 [00:37<03:17,  7.80it/s]
 21%|██        | 404/1939 [00:38<02:19, 11.03it/s]
 21%|██        | 406/1939 [00:38<02:31, 10.14it/s]
 21%|██        | 408/1939 [00:38<02:39,  9.61it/s]
 21%|██        | 411/1939 [00:38<02:09, 11.76it/s]
 21%|██▏       | 413/1939 [00:39<02:17, 11.13it/s]
 21%|██▏       | 415/1939 [00:39<02:01, 12.52it/s]
 22%|██▏       | 417/1939 [00:39<02:20, 10.81it/s]
 22%|██▏       | 419/1939 [00:39<02:32,  9.94it/s]
 22%|██▏       | 421/1939 [00:39<02:12, 11.44it/s]
 22%|██▏       | 423/1939 [00:40<02:44,  9.21it/s]
 22%|██▏       | 425/1939 [00:40<02:22, 10.62it/s]
 22%|██▏       | 427/1939 [00:40<02:25, 10.41it/s]
 22%|██▏       | 429/1939 [00:40<02:27, 10.27it/s]
 22%|██▏       | 431/1939 [00:40<02:14, 11.23it/s]
 22%|██▏       | 434/1939 [00:40<01:43, 14.59it/s]
 23%|██▎       | 437/1939 [00:41<01:51, 13.42it/s]
 23%|██▎       | 440/1939 [00:41<01:35, 15.66it/s]
 23%|██▎       | 443/1939 [00:41<01:26, 17.27it/s]
 23%|██▎       | 445/1939 [00:41<01:26, 17.31it/s]
 23%|██▎       | 451/1939 [00:41<00:56, 26.31it/s]
 23%|██▎       | 454/1939 [00:41<01:02, 23.92it/s]
 24%|██▎       | 457/1939 [00:42<01:22, 18.03it/s]
 24%|██▎       | 460/1939 [00:42<01:20, 18.33it/s]
 24%|██▍       | 466/1939 [00:42<00:55, 26.37it/s]
 24%|██▍       | 470/1939 [00:42<00:57, 25.73it/s]
 24%|██▍       | 475/1939 [00:42<00:47, 30.77it/s]
 25%|██▍       | 479/1939 [00:43<01:28, 16.49it/s]
 25%|██▍       | 482/1939 [00:43<01:20, 18.11it/s]
 25%|██▌       | 489/1939 [00:43<01:07, 21.62it/s]
 25%|██▌       | 492/1939 [00:43<01:17, 18.58it/s]
 26%|██▌       | 495/1939 [00:43<01:14, 19.34it/s]
 26%|██▌       | 498/1939 [00:44<01:31, 15.69it/s]
 26%|██▌       | 503/1939 [00:44<01:09, 20.73it/s]
 26%|██▋       | 509/1939 [00:44<00:51, 27.51it/s]
 26%|██▋       | 513/1939 [00:44<01:09, 20.48it/s]
 27%|██▋       | 516/1939 [00:44<01:21, 17.39it/s]
 27%|██▋       | 519/1939 [00:45<01:38, 14.36it/s]
 27%|██▋       | 521/1939 [00:45<02:00, 11.72it/s]
 27%|██▋       | 523/1939 [00:45<02:00, 11.71it/s]
 27%|██▋       | 525/1939 [00:46<02:20, 10.07it/s]
 27%|██▋       | 527/1939 [00:46<02:59,  7.86it/s]
 27%|██▋       | 529/1939 [00:46<03:04,  7.63it/s]
 27%|██▋       | 531/1939 [00:47<03:10,  7.38it/s]
 27%|██▋       | 533/1939 [00:47<03:17,  7.10it/s]
 28%|██▊       | 534/1939 [00:47<03:51,  6.06it/s]
 28%|██▊       | 536/1939 [00:47<03:35,  6.52it/s]
 28%|██▊       | 537/1939 [00:48<03:39,  6.37it/s]
 28%|██▊       | 539/1939 [00:48<03:02,  7.69it/s]
 28%|██▊       | 541/1939 [00:48<02:25,  9.59it/s]
 28%|██▊       | 546/1939 [00:48<01:36, 14.37it/s]
 28%|██▊       | 548/1939 [00:48<01:51, 12.47it/s]
 28%|██▊       | 550/1939 [00:48<01:41, 13.69it/s]
 28%|██▊       | 552/1939 [00:49<02:07, 10.89it/s]
 29%|██▊       | 557/1939 [00:49<01:19, 17.42it/s]
 29%|██▉       | 560/1939 [00:49<01:36, 14.28it/s]
 29%|██▉       | 566/1939 [00:49<01:03, 21.51it/s]
 29%|██▉       | 571/1939 [00:49<01:07, 20.31it/s]
 30%|██▉       | 574/1939 [00:50<01:47, 12.64it/s]
 30%|██▉       | 577/1939 [00:50<01:50, 12.32it/s]
 30%|██▉       | 579/1939 [00:50<02:03, 11.05it/s]
 30%|███       | 582/1939 [00:51<02:11, 10.36it/s]
 30%|███       | 584/1939 [00:51<02:14, 10.04it/s]
 30%|███       | 586/1939 [00:51<02:24,  9.33it/s]
 30%|███       | 589/1939 [00:52<02:20,  9.60it/s]
 31%|███       | 592/1939 [00:52<01:51, 12.10it/s]
 31%|███       | 594/1939 [00:52<02:11, 10.26it/s]
 31%|███       | 596/1939 [00:52<02:17,  9.74it/s]
 31%|███       | 599/1939 [00:53<02:15,  9.85it/s]
 31%|███       | 601/1939 [00:53<02:25,  9.22it/s]
 31%|███       | 603/1939 [00:53<02:04, 10.70it/s]
 31%|███▏      | 607/1939 [00:53<01:49, 12.22it/s]
 31%|███▏      | 609/1939 [00:53<02:04, 10.69it/s]
 32%|███▏      | 611/1939 [00:54<02:12, 10.05it/s]
 32%|███▏      | 613/1939 [00:54<02:50,  7.76it/s]
 32%|███▏      | 614/1939 [00:54<03:05,  7.15it/s]
 32%|███▏      | 615/1939 [00:55<03:26,  6.43it/s]
 32%|███▏      | 616/1939 [00:55<03:44,  5.89it/s]
 32%|███▏      | 617/1939 [00:55<04:04,  5.41it/s]
 32%|███▏      | 618/1939 [00:55<03:47,  5.82it/s]
 32%|███▏      | 620/1939 [00:55<02:45,  7.99it/s]
 32%|███▏      | 621/1939 [00:55<02:46,  7.94it/s]
 32%|███▏      | 622/1939 [00:56<03:09,  6.96it/s]
 32%|███▏      | 624/1939 [00:56<02:23,  9.16it/s]
 32%|███▏      | 627/1939 [00:56<01:44, 12.58it/s]
 32%|███▏      | 629/1939 [00:56<01:54, 11.39it/s]
 33%|███▎      | 631/1939 [00:56<01:56, 11.19it/s]
 33%|███▎      | 633/1939 [00:56<01:47, 12.16it/s]
 33%|███▎      | 636/1939 [00:57<01:44, 12.48it/s]
 33%|███▎      | 638/1939 [00:57<01:36, 13.45it/s]
 33%|███▎      | 640/1939 [00:57<01:36, 13.42it/s]
 33%|███▎      | 642/1939 [00:57<01:29, 14.55it/s]
 33%|███▎      | 644/1939 [00:57<01:45, 12.32it/s]
 33%|███▎      | 646/1939 [00:57<01:37, 13.20it/s]
 33%|███▎      | 648/1939 [00:57<01:28, 14.52it/s]
 34%|███▎      | 650/1939 [00:58<01:26, 14.86it/s]
 34%|███▎      | 652/1939 [00:58<01:45, 12.25it/s]
 34%|███▎      | 654/1939 [00:58<01:40, 12.75it/s]
 34%|███▍      | 656/1939 [00:58<02:02, 10.46it/s]
 34%|███▍      | 658/1939 [00:58<02:13,  9.58it/s]
 34%|███▍      | 660/1939 [00:59<02:23,  8.89it/s]
 34%|███▍      | 663/1939 [00:59<01:45, 12.10it/s]
 34%|███▍      | 665/1939 [00:59<01:55, 11.05it/s]
 34%|███▍      | 667/1939 [00:59<02:12,  9.57it/s]
 35%|███▍      | 670/1939 [00:59<01:47, 11.83it/s]
 35%|███▍      | 672/1939 [01:00<01:41, 12.43it/s]
 35%|███▍      | 674/1939 [01:00<01:34, 13.44it/s]
 35%|███▍      | 676/1939 [01:00<01:40, 12.55it/s]
 35%|███▍      | 678/1939 [01:00<01:29, 14.01it/s]
 35%|███▌      | 680/1939 [01:00<01:52, 11.15it/s]
 35%|███▌      | 682/1939 [01:00<01:43, 12.11it/s]
 35%|███▌      | 684/1939 [01:01<01:56, 10.79it/s]
 35%|███▌      | 687/1939 [01:01<01:55, 10.88it/s]
 36%|███▌      | 689/1939 [01:01<01:54, 10.93it/s]
 36%|███▌      | 691/1939 [01:01<01:42, 12.16it/s]
 36%|███▌      | 693/1939 [01:02<02:09,  9.63it/s]
 36%|███▌      | 696/1939 [01:02<01:40, 12.32it/s]
 36%|███▌      | 699/1939 [01:02<01:26, 14.28it/s]
 36%|███▌      | 701/1939 [01:02<01:23, 14.90it/s]
 36%|███▋      | 707/1939 [01:02<00:51, 23.78it/s]
 37%|███▋      | 710/1939 [01:02<01:12, 17.01it/s]
 37%|███▋      | 714/1939 [01:02<00:59, 20.71it/s]
 37%|███▋      | 717/1939 [01:03<00:55, 22.05it/s]
 37%|███▋      | 721/1939 [01:03<00:48, 25.14it/s]
 37%|███▋      | 724/1939 [01:03<01:06, 18.23it/s]
 37%|███▋      | 727/1939 [01:03<01:21, 14.85it/s]
 38%|███▊      | 730/1939 [01:04<01:25, 14.11it/s]
 38%|███▊      | 732/1939 [01:04<01:39, 12.10it/s]
 38%|███▊      | 734/1939 [01:04<02:15,  8.90it/s]
 38%|███▊      | 737/1939 [01:04<01:52, 10.66it/s]
 38%|███▊      | 739/1939 [01:05<01:53, 10.60it/s]
 38%|███▊      | 742/1939 [01:05<01:58, 10.09it/s]
 38%|███▊      | 744/1939 [01:05<01:44, 11.43it/s]
 38%|███▊      | 746/1939 [01:05<01:52, 10.56it/s]
 39%|███▊      | 748/1939 [01:05<01:46, 11.19it/s]
 39%|███▊      | 751/1939 [01:06<01:55, 10.26it/s]
 39%|███▉      | 753/1939 [01:06<01:41, 11.64it/s]
 39%|███▉      | 755/1939 [01:06<01:47, 11.03it/s]
 39%|███▉      | 757/1939 [01:06<01:58,  9.94it/s]
 39%|███▉      | 759/1939 [01:06<01:48, 10.83it/s]
 39%|███▉      | 761/1939 [01:07<01:43, 11.38it/s]
 39%|███▉      | 763/1939 [01:07<02:00,  9.75it/s]
 40%|███▉      | 766/1939 [01:07<01:43, 11.38it/s]
 40%|███▉      | 768/1939 [01:07<01:59,  9.78it/s]
 40%|███▉      | 770/1939 [01:08<02:06,  9.25it/s]
 40%|███▉      | 772/1939 [01:08<01:53, 10.29it/s]
 40%|███▉      | 774/1939 [01:08<01:59,  9.76it/s]
 40%|████      | 776/1939 [01:08<01:49, 10.59it/s]
 40%|████      | 778/1939 [01:08<01:39, 11.67it/s]
 40%|████      | 780/1939 [01:09<02:06,  9.14it/s]
 40%|████      | 782/1939 [01:09<01:54, 10.11it/s]
 40%|████      | 784/1939 [01:09<01:59,  9.70it/s]
 41%|████      | 786/1939 [01:09<01:48, 10.65it/s]
 41%|████      | 788/1939 [01:09<01:59,  9.61it/s]
 41%|████      | 790/1939 [01:09<01:43, 11.11it/s]
 41%|████      | 792/1939 [01:10<01:34, 12.18it/s]
 41%|████      | 794/1939 [01:10<01:52, 10.17it/s]
 41%|████      | 796/1939 [01:10<01:39, 11.43it/s]
 41%|████      | 798/1939 [01:10<01:42, 11.08it/s]
 41%|████▏     | 800/1939 [01:10<01:35, 11.91it/s]
 41%|████▏     | 802/1939 [01:10<01:24, 13.49it/s]
 41%|████▏     | 804/1939 [01:11<01:41, 11.23it/s]
 42%|████▏     | 806/1939 [01:11<02:03,  9.17it/s]
 42%|████▏     | 809/1939 [01:11<01:48, 10.38it/s]
 42%|████▏     | 811/1939 [01:11<01:40, 11.17it/s]
 42%|████▏     | 813/1939 [01:12<02:35,  7.24it/s]
 42%|████▏     | 816/1939 [01:12<02:12,  8.49it/s]
 42%|████▏     | 818/1939 [01:12<02:20,  8.00it/s]
 42%|████▏     | 819/1939 [01:13<02:27,  7.61it/s]
 42%|████▏     | 820/1939 [01:13<02:43,  6.85it/s]
 42%|████▏     | 821/1939 [01:13<02:39,  7.02it/s]
 42%|████▏     | 822/1939 [01:13<02:44,  6.80it/s]
 42%|████▏     | 824/1939 [01:13<02:08,  8.68it/s]
 43%|████▎     | 825/1939 [01:13<02:24,  7.73it/s]
 43%|████▎     | 828/1939 [01:13<01:34, 11.77it/s]
 43%|████▎     | 830/1939 [01:14<01:54,  9.69it/s]
 43%|████▎     | 834/1939 [01:14<01:29, 12.32it/s]
 43%|████▎     | 837/1939 [01:14<01:15, 14.62it/s]
 43%|████▎     | 839/1939 [01:14<01:22, 13.33it/s]
 43%|████▎     | 841/1939 [01:14<01:18, 13.90it/s]
 44%|████▎     | 844/1939 [01:15<01:20, 13.67it/s]
 44%|████▎     | 846/1939 [01:15<01:13, 14.82it/s]
 44%|████▍     | 851/1939 [01:15<01:08, 15.96it/s]
 44%|████▍     | 853/1939 [01:15<01:06, 16.41it/s]
 44%|████▍     | 856/1939 [01:15<00:57, 18.71it/s]
 44%|████▍     | 859/1939 [01:16<01:35, 11.34it/s]
 44%|████▍     | 861/1939 [01:16<01:45, 10.21it/s]
 45%|████▍     | 863/1939 [01:16<02:12,  8.15it/s]
 45%|████▍     | 865/1939 [01:17<02:10,  8.25it/s]
 45%|████▍     | 867/1939 [01:17<01:49,  9.80it/s]
 45%|████▌     | 874/1939 [01:17<00:55, 19.28it/s]
 45%|████▌     | 877/1939 [01:17<01:04, 16.38it/s]
 45%|████▌     | 882/1939 [01:17<00:48, 21.74it/s]
 46%|████▌     | 886/1939 [01:17<00:52, 20.04it/s]
 46%|████▌     | 890/1939 [01:18<00:45, 22.99it/s]
 46%|████▌     | 893/1939 [01:18<00:55, 18.85it/s]
 46%|████▌     | 896/1939 [01:18<01:04, 16.17it/s]
 46%|████▋     | 899/1939 [01:18<01:20, 12.97it/s]
 46%|████▋     | 901/1939 [01:19<01:22, 12.57it/s]
 47%|████▋     | 903/1939 [01:19<01:34, 10.92it/s]
 47%|████▋     | 906/1939 [01:19<01:15, 13.68it/s]
 47%|████▋     | 910/1939 [01:19<01:11, 14.38it/s]
 47%|████▋     | 912/1939 [01:19<01:12, 14.23it/s]
 47%|████▋     | 915/1939 [01:19<01:00, 16.89it/s]
 47%|████▋     | 918/1939 [01:20<01:06, 15.34it/s]
 47%|████▋     | 920/1939 [01:20<01:05, 15.46it/s]
 48%|████▊     | 927/1939 [01:20<00:51, 19.51it/s]
 48%|████▊     | 930/1939 [01:20<01:04, 15.67it/s]
 48%|████▊     | 932/1939 [01:21<01:20, 12.48it/s]
 48%|████▊     | 934/1939 [01:21<01:27, 11.53it/s]
 48%|████▊     | 936/1939 [01:21<01:35, 10.47it/s]
 48%|████▊     | 938/1939 [01:21<01:43,  9.66it/s]
 48%|████▊     | 940/1939 [01:22<01:29, 11.18it/s]
 49%|████▉     | 946/1939 [01:22<00:51, 19.29it/s]
 49%|████▉     | 950/1939 [01:22<00:42, 23.20it/s]
 49%|████▉     | 954/1939 [01:22<00:38, 25.45it/s]
 50%|████▉     | 960/1939 [01:22<00:32, 29.94it/s]
 50%|████▉     | 964/1939 [01:22<00:30, 31.59it/s]
 50%|████▉     | 968/1939 [01:22<00:31, 31.27it/s]
 50%|█████     | 972/1939 [01:23<01:15, 12.88it/s]
 50%|█████     | 975/1939 [01:23<01:18, 12.24it/s]
 50%|█████     | 978/1939 [01:24<01:27, 11.01it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 335.00it/s]
 50%|█████     | 151/300 [06:37<1:16:29, 30.80s/it]

[[np.int64(0), False, 10], [np.int64(1), False, 7], [np.int64(2), False, 3], [np.int64(4), False, 10], [np.int64(5), False, 1], [np.int64(6), False, 10], [np.int64(8), False, 13], [np.int64(9), False, 8], [np.int64(11), False, 1], [np.int64(12), False, 1], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3514, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.3636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4327, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████     | 153/300 [06:37<46:54, 19.15s/it]

tensor(12.3634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4996, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [06:37<35:23, 14.54s/it]

tensor(12.3650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5306, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5442, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [06:38<20:43,  8.64s/it]

tensor(12.3646, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3617, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5440, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5482, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [06:38<12:59,  5.49s/it]

tensor(12.3449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5434, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5494, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [06:38<08:28,  3.63s/it]

tensor(12.3246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5600, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [06:38<05:39,  2.46s/it]

tensor(12.3176, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5678, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5728, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5783, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [06:38<03:51,  1.70s/it]

tensor(12.3061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5849, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5886, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [06:38<02:40,  1.20s/it]

tensor(12.2956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5905, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [06:39<01:53,  1.17it/s]

tensor(12.2880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5863, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5860, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5836, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [06:39<01:21,  1.60it/s]

tensor(12.2668, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5850, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5862, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [06:39<00:59,  2.16it/s]

tensor(12.2558, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5883, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [06:39<00:44,  2.84it/s]

tensor(12.2515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5873, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2466, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5896, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5921, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [06:39<00:34,  3.64it/s]

tensor(12.2366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5947, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2313, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5997, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [06:40<00:26,  4.53it/s]

tensor(12.2266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6037, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [06:40<00:21,  5.48it/s]

tensor(12.2220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6078, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6105, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6113, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [06:40<00:18,  6.38it/s]

tensor(12.2098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6133, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6153, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████▏   | 184/300 [06:40<00:16,  7.20it/s]

tensor(12.2019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6150, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [06:40<00:14,  7.90it/s]

tensor(12.1983, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1943, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6171, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6181, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [06:41<00:13,  8.50it/s]

tensor(12.1874, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6191, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1839, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6200, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [06:41<00:12,  9.00it/s]

tensor(12.1806, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6189, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 192/300 [06:41<00:11,  9.37it/s]

tensor(12.1776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6189, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6203, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6229, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [06:41<00:11,  9.62it/s]

tensor(12.1679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6245, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6256, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 196/300 [06:41<00:10,  9.87it/s]

tensor(12.1618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6292, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [06:42<00:10, 10.02it/s]

tensor(12.1586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6295, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0202, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6319, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0199, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6339, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [06:42<00:09, 10.15it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([162, 199,  80, 219,  67, 281,  23, 270,  88, 202, 132, 127,  33,  56])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:08, 28.42it/s]
  0%|          | 9/1939 [00:00<00:44, 43.85it/s]
  1%|          | 16/1939 [00:00<00:35, 53.62it/s]
  1%|          | 22/1939 [00:00<00:35, 53.45it/s]
  1%|▏         | 28/1939 [00:00<00:34, 54.66it/s]
  2%|▏         | 34/1939 [00:00<00:37, 51.26it/s]
  2%|▏         | 40/1939 [00:00<00:37, 51.03it/s]
  2%|▏         | 46/1939 [00:01<01:13, 25.83it/s]
  3%|▎         | 50/1939 [00:01<01:17, 24.44it/s]
  3%|▎         | 54/1939 [00:01<01:32, 20.47it/s]
  3%|▎         | 57/1939 [00:02<02:07, 14.76it/s]
  3%|▎         | 60/1939 [00:02<02:01, 15.42it/s]
  3%|▎         | 64/1939 [00:02<01:39, 18.76it/s]
  3%|▎         | 67/1939 [00:02<02:16, 13.69it/s]
  4%|▎         | 69/1939 [00:02<02:10, 14.36it/s]
  4%|▎         | 72/1939 [00:03<01:50, 16.85it/s]
  4%|▍         | 75/1939 [00:03<02:11, 14.23it/s]
  4%|▍         | 77/1939 [00:03<02:09, 14.35it/s]
  4%|▍         | 79/1939 [00:03<02:42, 11.43it/s]
  4%|▍         | 81/1939 [00:04<03:15,  9.50it/s]
  4%|▍         | 83/1939 [00:04<03:45,  8.23it/s]
  4%|▍         | 85/1939 [00:04<03:18,  9.36it/s]
  4%|▍         | 87/1939 [00:04<03:17,  9.38it/s]
  5%|▍         | 90/1939 [00:04<02:29, 12.34it/s]
  5%|▍         | 96/1939 [00:05<01:57, 15.65it/s]
  5%|▌         | 98/1939 [00:05<01:54, 16.15it/s]
  5%|▌         | 100/1939 [00:05<02:15, 13.53it/s]
  5%|▌         | 102/1939 [00:05<02:36, 11.71it/s]
  5%|▌         | 105/1939 [00:06<02:38, 11.60it/s]
  6%|▌         | 107/1939 [00:06<02:51, 10.67it/s]
  6%|▌         | 110/1939 [00:06<02:19, 13.15it/s]
  6%|▌         | 114/1939 [00:06<02:03, 14.75it/s]
  6%|▌         | 116/1939 [00:06<02:35, 11.73it/s]
  6%|▌         | 118/1939 [00:07<03:23,  8.95it/s]
  6%|▌         | 120/1939 [00:07<03:25,  8.87it/s]
  6%|▋         | 122/1939 [00:07<03:41,  8.20it/s]
  7%|▋         | 127/1939 [00:07<02:11, 13.83it/s]
  7%|▋         | 130/1939 [00:08<02:25, 12.47it/s]
  7%|▋         | 132/1939 [00:08<02:31, 11.91it/s]
  7%|▋         | 135/1939 [00:08<02:34, 11.69it/s]
  7%|▋         | 137/1939 [00:08<02:50, 10.59it/s]
  7%|▋         | 139/1939 [00:09<03:39,  8.22it/s]
  7%|▋         | 141/1939 [00:09<03:33,  8.44it/s]
  7%|▋         | 144/1939 [00:09<02:44, 10.90it/s]
  8%|▊         | 146/1939 [00:09<02:56, 10.16it/s]
  8%|▊         | 149/1939 [00:10<02:51, 10.44it/s]
  8%|▊         | 151/1939 [00:10<03:09,  9.42it/s]
  8%|▊         | 153/1939 [00:10<03:21,  8.88it/s]
  8%|▊         | 155/1939 [00:10<02:52, 10.35it/s]
  8%|▊         | 157/1939 [00:11<02:52, 10.32it/s]
  8%|▊         | 159/1939 [00:11<04:19,  6.87it/s]
  8%|▊         | 160/1939 [00:11<04:30,  6.57it/s]
  8%|▊         | 161/1939 [00:11<04:17,  6.91it/s]
 67%|██████▋   | 200/300 [06:56<00:09, 10.15it/s]]
  8%|▊         | 164/1939 [00:12<03:40,  8.04it/s]
  9%|▊         | 166/1939 [00:12<02:57,  9.96it/s]
  9%|▊         | 168/1939 [00:12<02:30, 11.75it/s]
  9%|▉         | 174/1939 [00:12<01:19, 22.12it/s]
  9%|▉         | 180/1939 [00:12<00:57, 30.45it/s]
 10%|▉         | 186/1939 [00:12<00:48, 36.36it/s]
 10%|▉         | 192/1939 [00:12<00:41, 42.03it/s]
 10%|█         | 198/1939 [00:12<00:38, 45.80it/s]
 10%|█         | 203/1939 [00:13<01:24, 20.60it/s]
 11%|█         | 207/1939 [00:14<01:59, 14.54it/s]
 11%|█         | 210/1939 [00:14<01:47, 16.11it/s]
 11%|█         | 213/1939 [00:14<02:16, 12.68it/s]
 11%|█         | 216/1939 [00:14<02:06, 13.65it/s]
 11%|█▏        | 219/1939 [00:14<02:13, 12.87it/s]
 11%|█▏        | 221/1939 [00:15<02:05, 13.73it/s]
 12%|█▏        | 223/1939 [00:15<02:11, 13.04it/s]
 12%|█▏        | 225/1939 [00:15<02:43, 10.47it/s]
 12%|█▏        | 228/1939 [00:15<02:19, 12.30it/s]
 12%|█▏        | 230/1939 [00:15<02:15, 12.65it/s]
 12%|█▏        | 232/1939 [00:16<02:19, 12.21it/s]
 12%|█▏        | 234/1939 [00:16<03:03,  9.27it/s]
 12%|█▏        | 236/1939 [00:16<03:12,  8.83it/s]
 12%|█▏        | 239/1939 [00:16<02:54,  9.77it/s]
 12%|█▏        | 241/1939 [00:17<03:48,  7.45it/s]
 12%|█▏        | 242/1939 [00:17<04:27,  6.33it/s]
 13%|█▎        | 243/1939 [00:17<04:43,  5.99it/s]
 13%|█▎        | 244/1939 [00:18<04:56,  5.71it/s]
 13%|█▎        | 245/1939 [00:18<05:06,  5.52it/s]
 13%|█▎        | 246/1939 [00:18<04:36,  6.12it/s]
 13%|█▎        | 248/1939 [00:18<03:31,  7.99it/s]
 13%|█▎        | 250/1939 [00:18<02:58,  9.48it/s]
 13%|█▎        | 252/1939 [00:18<02:44, 10.24it/s]
 13%|█▎        | 256/1939 [00:18<01:44, 16.10it/s]
 13%|█▎        | 258/1939 [00:19<02:46, 10.09it/s]
 13%|█▎        | 260/1939 [00:19<02:58,  9.40it/s]
 14%|█▎        | 262/1939 [00:19<02:38, 10.58it/s]
 14%|█▎        | 264/1939 [00:20<03:22,  8.28it/s]
 14%|█▎        | 266/1939 [00:20<03:00,  9.28it/s]
 14%|█▍        | 268/1939 [00:20<03:15,  8.55it/s]
 14%|█▍        | 272/1939 [00:20<02:08, 12.97it/s]
 14%|█▍        | 274/1939 [00:21<02:54,  9.56it/s]
 14%|█▍        | 276/1939 [00:21<02:31, 10.96it/s]
 14%|█▍        | 279/1939 [00:21<02:17, 12.04it/s]
 14%|█▍        | 281/1939 [00:21<02:31, 10.95it/s]
 15%|█▍        | 284/1939 [00:21<02:32, 10.85it/s]
 15%|█▍        | 286/1939 [00:22<02:55,  9.43it/s]
 15%|█▍        | 288/1939 [00:22<03:41,  7.47it/s]
 15%|█▌        | 291/1939 [00:22<02:44, 10.00it/s]
 15%|█▌        | 293/1939 [00:22<02:46,  9.91it/s]
 15%|█▌        | 296/1939 [00:23<02:38, 10.36it/s]
 15%|█▌        | 298/1939 [00:23<02:54,  9.38it/s]
 15%|█▌        | 300/1939 [00:23<03:08,  8.71it/s]
 16%|█▌        | 303/1939 [00:23<02:54,  9.40it/s]
 16%|█▌        | 305/1939 [00:24<02:34, 10.55it/s]
 16%|█▌        | 307/1939 [00:24<02:35, 10.50it/s]
 16%|█▌        | 309/1939 [00:24<02:21, 11.50it/s]
 16%|█▌        | 312/1939 [00:24<02:14, 12.07it/s]
 16%|█▌        | 315/1939 [00:24<02:20, 11.57it/s]
 16%|█▋        | 317/1939 [00:25<03:02,  8.89it/s]
 16%|█▋        | 319/1939 [00:25<03:44,  7.22it/s]
 17%|█▋        | 320/1939 [00:25<04:00,  6.74it/s]
 17%|█▋        | 321/1939 [00:26<04:15,  6.32it/s]
 17%|█▋        | 322/1939 [00:26<04:34,  5.88it/s]
 17%|█▋        | 324/1939 [00:26<03:28,  7.74it/s]
 17%|█▋        | 327/1939 [00:26<02:48,  9.57it/s]
 17%|█▋        | 330/1939 [00:26<02:08, 12.48it/s]
 17%|█▋        | 332/1939 [00:27<02:20, 11.47it/s]
 17%|█▋        | 334/1939 [00:27<02:09, 12.35it/s]
 18%|█▊        | 340/1939 [00:27<01:15, 21.17it/s]
 18%|█▊        | 343/1939 [00:27<01:10, 22.56it/s]
 18%|█▊        | 348/1939 [00:27<00:55, 28.60it/s]
 18%|█▊        | 352/1939 [00:27<01:38, 16.18it/s]
 18%|█▊        | 355/1939 [00:28<02:18, 11.46it/s]
 18%|█▊        | 357/1939 [00:28<02:11, 11.99it/s]
 19%|█▊        | 360/1939 [00:28<02:03, 12.77it/s]
 19%|█▊        | 363/1939 [00:29<02:11, 11.97it/s]
 19%|█▉        | 366/1939 [00:29<02:13, 11.78it/s]
 19%|█▉        | 368/1939 [00:29<02:01, 12.93it/s]
 19%|█▉        | 370/1939 [00:29<02:16, 11.52it/s]
 19%|█▉        | 372/1939 [00:29<02:34, 10.14it/s]
 19%|█▉        | 374/1939 [00:30<02:16, 11.48it/s]
 19%|█▉        | 376/1939 [00:30<02:25, 10.76it/s]
 19%|█▉        | 378/1939 [00:30<02:41,  9.64it/s]
 20%|█▉        | 380/1939 [00:30<02:18, 11.22it/s]
 20%|█▉        | 382/1939 [00:31<03:03,  8.49it/s]
 20%|█▉        | 384/1939 [00:31<03:12,  8.08it/s]
 20%|█▉        | 385/1939 [00:31<03:45,  6.89it/s]
 20%|█▉        | 387/1939 [00:31<03:36,  7.15it/s]
 20%|██        | 388/1939 [00:32<03:53,  6.65it/s]
 20%|██        | 389/1939 [00:32<04:16,  6.04it/s]
 20%|██        | 390/1939 [00:32<04:40,  5.53it/s]
 20%|██        | 391/1939 [00:32<04:51,  5.30it/s]
 20%|██        | 392/1939 [00:32<05:06,  5.05it/s]
 20%|██        | 393/1939 [00:33<05:21,  4.80it/s]
 20%|██        | 394/1939 [00:33<05:29,  4.69it/s]
 20%|██        | 397/1939 [00:33<03:03,  8.39it/s]
 21%|██        | 399/1939 [00:33<03:04,  8.35it/s]
 21%|██        | 402/1939 [00:33<02:09, 11.90it/s]
 21%|██        | 404/1939 [00:34<02:20, 10.93it/s]
 21%|██        | 406/1939 [00:34<02:01, 12.57it/s]
 21%|██        | 411/1939 [00:34<01:37, 15.73it/s]
 21%|██▏       | 413/1939 [00:34<01:56, 13.10it/s]
 21%|██▏       | 415/1939 [00:34<02:12, 11.47it/s]
 22%|██▏       | 417/1939 [00:35<02:36,  9.71it/s]
 22%|██▏       | 419/1939 [00:35<02:44,  9.26it/s]
 22%|██▏       | 422/1939 [00:35<02:38,  9.57it/s]
 22%|██▏       | 424/1939 [00:35<02:19, 10.84it/s]
 22%|██▏       | 426/1939 [00:36<02:32,  9.89it/s]
 22%|██▏       | 428/1939 [00:36<02:44,  9.16it/s]
 22%|██▏       | 430/1939 [00:36<02:21, 10.65it/s]
 22%|██▏       | 436/1939 [00:36<01:17, 19.27it/s]
 23%|██▎       | 441/1939 [00:36<01:16, 19.54it/s]
 23%|██▎       | 444/1939 [00:36<01:14, 20.16it/s]
 23%|██▎       | 451/1939 [00:37<00:54, 27.47it/s]
 23%|██▎       | 455/1939 [00:37<00:52, 28.48it/s]
 24%|██▎       | 459/1939 [00:37<00:48, 30.48it/s]
 24%|██▍       | 466/1939 [00:37<00:38, 38.46it/s]
 24%|██▍       | 471/1939 [00:37<00:35, 41.02it/s]
 25%|██▍       | 478/1939 [00:37<00:30, 48.33it/s]
 25%|██▍       | 484/1939 [00:37<00:28, 50.68it/s]
 25%|██▌       | 490/1939 [00:38<00:52, 27.68it/s]
 26%|██▌       | 495/1939 [00:38<01:25, 16.82it/s]
 26%|██▌       | 499/1939 [00:39<01:32, 15.55it/s]
 26%|██▌       | 502/1939 [00:39<01:43, 13.93it/s]
 26%|██▌       | 505/1939 [00:39<01:53, 12.59it/s]
 26%|██▌       | 507/1939 [00:39<01:48, 13.25it/s]
 27%|██▋       | 514/1939 [00:39<01:08, 20.95it/s]
 27%|██▋       | 519/1939 [00:40<00:55, 25.44it/s]
 27%|██▋       | 525/1939 [00:40<00:44, 31.92it/s]
 27%|██▋       | 531/1939 [00:40<00:38, 36.86it/s]
 28%|██▊       | 536/1939 [00:40<00:35, 39.60it/s]
 28%|██▊       | 541/1939 [00:40<01:07, 20.81it/s]
 28%|██▊       | 545/1939 [00:41<00:59, 23.55it/s]
 28%|██▊       | 549/1939 [00:41<01:00, 22.81it/s]
 29%|██▊       | 553/1939 [00:41<01:33, 14.85it/s]
 29%|██▊       | 556/1939 [00:41<01:37, 14.13it/s]
 29%|██▉       | 559/1939 [00:42<01:37, 14.15it/s]
 29%|██▉       | 561/1939 [00:42<01:45, 13.06it/s]
 29%|██▉       | 563/1939 [00:42<01:53, 12.08it/s]
 29%|██▉       | 566/1939 [00:42<01:35, 14.40it/s]
 29%|██▉       | 568/1939 [00:42<01:37, 14.02it/s]
 29%|██▉       | 570/1939 [00:42<01:32, 14.76it/s]
 29%|██▉       | 572/1939 [00:43<01:58, 11.53it/s]
 30%|██▉       | 574/1939 [00:43<02:00, 11.31it/s]
 30%|██▉       | 576/1939 [00:43<01:59, 11.43it/s]
 30%|██▉       | 579/1939 [00:43<02:01, 11.20it/s]
 30%|███       | 582/1939 [00:44<01:59, 11.37it/s]
 30%|███       | 584/1939 [00:44<02:12, 10.20it/s]
 30%|███       | 586/1939 [00:44<02:23,  9.40it/s]
 30%|███       | 589/1939 [00:44<02:13, 10.14it/s]
 30%|███       | 591/1939 [00:45<01:58, 11.35it/s]
 31%|███       | 593/1939 [00:45<02:38,  8.50it/s]
 31%|███       | 595/1939 [00:45<02:39,  8.41it/s]
 31%|███       | 597/1939 [00:45<02:16,  9.85it/s]
 31%|███       | 599/1939 [00:46<02:17,  9.76it/s]
 31%|███       | 601/1939 [00:46<02:27,  9.06it/s]
 31%|███       | 604/1939 [00:46<01:51, 12.01it/s]
 31%|███▏      | 607/1939 [00:46<01:48, 12.32it/s]
 31%|███▏      | 609/1939 [00:46<02:02, 10.85it/s]
 32%|███▏      | 611/1939 [00:47<02:16,  9.70it/s]
 32%|███▏      | 613/1939 [00:47<02:29,  8.87it/s]
 32%|███▏      | 614/1939 [00:47<02:53,  7.63it/s]
 32%|███▏      | 615/1939 [00:47<03:12,  6.89it/s]
 32%|███▏      | 617/1939 [00:48<02:45,  8.00it/s]
 32%|███▏      | 618/1939 [00:48<02:47,  7.90it/s]
 32%|███▏      | 620/1939 [00:48<02:54,  7.56it/s]
 32%|███▏      | 622/1939 [00:48<02:20,  9.35it/s]
 32%|███▏      | 624/1939 [00:48<02:02, 10.73it/s]
 32%|███▏      | 629/1939 [00:48<01:41, 12.93it/s]
 33%|███▎      | 631/1939 [00:49<01:57, 11.17it/s]
 33%|███▎      | 633/1939 [00:49<02:06, 10.35it/s]
 33%|███▎      | 636/1939 [00:49<02:05, 10.41it/s]
 33%|███▎      | 639/1939 [00:49<01:39, 13.05it/s]
 33%|███▎      | 641/1939 [00:50<01:56, 11.16it/s]
 33%|███▎      | 645/1939 [00:50<01:22, 15.60it/s]
 33%|███▎      | 648/1939 [00:50<01:31, 14.14it/s]
 34%|███▎      | 650/1939 [00:50<01:52, 11.43it/s]
 34%|███▎      | 652/1939 [00:50<01:43, 12.44it/s]
 34%|███▍      | 656/1939 [00:51<01:39, 12.91it/s]
 34%|███▍      | 658/1939 [00:51<01:56, 11.00it/s]
 34%|███▍      | 660/1939 [00:51<01:47, 11.85it/s]
 34%|███▍      | 662/1939 [00:51<01:39, 12.87it/s]
 34%|███▍      | 665/1939 [00:51<01:38, 12.90it/s]
 34%|███▍      | 667/1939 [00:52<01:50, 11.54it/s]
 35%|███▍      | 670/1939 [00:52<01:32, 13.67it/s]
 35%|███▍      | 675/1939 [00:52<01:03, 19.84it/s]
 35%|███▍      | 678/1939 [00:52<01:19, 15.85it/s]
 35%|███▌      | 680/1939 [00:52<01:26, 14.63it/s]
 35%|███▌      | 682/1939 [00:53<01:24, 14.95it/s]
 35%|███▌      | 685/1939 [00:53<01:19, 15.85it/s]
 35%|███▌      | 687/1939 [00:53<01:41, 12.35it/s]
 36%|███▌      | 689/1939 [00:53<02:01, 10.31it/s]
 36%|███▌      | 691/1939 [00:53<01:54, 10.86it/s]
 36%|███▌      | 695/1939 [00:54<01:19, 15.75it/s]
 36%|███▌      | 702/1939 [00:54<00:47, 26.05it/s]
 37%|███▋      | 709/1939 [00:54<00:36, 34.00it/s]
 37%|███▋      | 715/1939 [00:54<00:31, 39.47it/s]
 37%|███▋      | 721/1939 [00:54<00:30, 39.64it/s]
 37%|███▋      | 727/1939 [00:54<00:27, 44.40it/s]
 38%|███▊      | 732/1939 [00:55<00:48, 24.82it/s]
 38%|███▊      | 736/1939 [00:55<00:53, 22.28it/s]
 38%|███▊      | 740/1939 [00:55<01:03, 18.87it/s]
 38%|███▊      | 743/1939 [00:55<01:13, 16.22it/s]
 38%|███▊      | 746/1939 [00:56<01:33, 12.76it/s]
 39%|███▊      | 749/1939 [00:56<01:35, 12.40it/s]
 39%|███▊      | 751/1939 [00:56<01:45, 11.27it/s]
 39%|███▉      | 753/1939 [00:56<01:36, 12.26it/s]
 39%|███▉      | 755/1939 [00:57<01:40, 11.74it/s]
 39%|███▉      | 758/1939 [00:57<01:22, 14.35it/s]
 39%|███▉      | 760/1939 [00:57<01:34, 12.42it/s]
 39%|███▉      | 763/1939 [00:57<01:40, 11.73it/s]
 40%|███▉      | 766/1939 [00:58<01:44, 11.18it/s]
 40%|███▉      | 768/1939 [00:58<02:15,  8.61it/s]
 40%|███▉      | 770/1939 [00:58<02:47,  6.98it/s]
 40%|███▉      | 771/1939 [00:59<02:54,  6.68it/s]
 40%|███▉      | 772/1939 [00:59<03:08,  6.20it/s]
 40%|███▉      | 773/1939 [00:59<03:16,  5.94it/s]
 40%|███▉      | 775/1939 [00:59<02:28,  7.84it/s]
 40%|████      | 776/1939 [00:59<03:10,  6.09it/s]
 40%|████      | 777/1939 [01:00<03:21,  5.77it/s]
 40%|████      | 779/1939 [01:00<02:53,  6.68it/s]
 40%|████      | 780/1939 [01:00<03:18,  5.83it/s]
 40%|████      | 781/1939 [01:00<03:00,  6.41it/s]
 40%|████      | 784/1939 [01:00<02:19,  8.26it/s]
 41%|████      | 787/1939 [01:01<02:08,  8.97it/s]
 41%|████      | 789/1939 [01:01<02:16,  8.44it/s]
 41%|████      | 791/1939 [01:01<01:54,  9.99it/s]
 41%|████      | 793/1939 [01:01<01:39, 11.55it/s]
 41%|████      | 795/1939 [01:01<01:37, 11.69it/s]
 41%|████      | 797/1939 [01:02<01:35, 11.92it/s]
 41%|████      | 799/1939 [01:02<01:52, 10.14it/s]
 41%|████▏     | 801/1939 [01:02<02:00,  9.47it/s]
 41%|████▏     | 803/1939 [01:02<01:48, 10.47it/s]
 42%|████▏     | 805/1939 [01:02<02:05,  9.02it/s]
 42%|████▏     | 807/1939 [01:03<01:50, 10.28it/s]
 42%|████▏     | 809/1939 [01:03<01:40, 11.21it/s]
 42%|████▏     | 811/1939 [01:03<01:28, 12.71it/s]
 42%|████▏     | 813/1939 [01:03<01:25, 13.13it/s]
 42%|████▏     | 815/1939 [01:03<01:18, 14.28it/s]
 42%|████▏     | 817/1939 [01:03<01:26, 12.99it/s]
 42%|████▏     | 819/1939 [01:04<01:41, 10.99it/s]
 42%|████▏     | 821/1939 [01:04<01:59,  9.34it/s]
 42%|████▏     | 823/1939 [01:04<02:17,  8.09it/s]
 43%|████▎     | 826/1939 [01:04<01:53,  9.81it/s]
 43%|████▎     | 828/1939 [01:04<01:40, 11.10it/s]
 43%|████▎     | 830/1939 [01:05<01:41, 10.95it/s]
 43%|████▎     | 832/1939 [01:05<01:30, 12.28it/s]
 43%|████▎     | 834/1939 [01:05<01:42, 10.77it/s]
 43%|████▎     | 837/1939 [01:05<01:18, 14.04it/s]
 43%|████▎     | 839/1939 [01:05<01:24, 13.04it/s]
 43%|████▎     | 841/1939 [01:05<01:17, 14.09it/s]
 44%|████▎     | 844/1939 [01:06<01:06, 16.48it/s]
 44%|████▎     | 846/1939 [01:06<01:11, 15.37it/s]
 44%|████▎     | 848/1939 [01:06<01:12, 14.97it/s]
 44%|████▍     | 851/1939 [01:06<01:19, 13.76it/s]
 44%|████▍     | 853/1939 [01:06<01:18, 13.91it/s]
 44%|████▍     | 855/1939 [01:07<01:38, 11.01it/s]
 44%|████▍     | 857/1939 [01:07<01:55,  9.41it/s]
 44%|████▍     | 859/1939 [01:07<02:06,  8.53it/s]
 44%|████▍     | 860/1939 [01:07<02:26,  7.35it/s]
 44%|████▍     | 861/1939 [01:08<02:38,  6.81it/s]
 44%|████▍     | 862/1939 [01:08<02:51,  6.27it/s]
 45%|████▍     | 863/1939 [01:08<02:54,  6.16it/s]
 45%|████▍     | 864/1939 [01:08<02:57,  6.07it/s]
 45%|████▍     | 866/1939 [01:08<02:12,  8.11it/s]
 45%|████▍     | 869/1939 [01:08<01:28, 12.12it/s]
 45%|████▌     | 876/1939 [01:08<00:44, 24.08it/s]
 45%|████▌     | 882/1939 [01:09<00:32, 32.31it/s]
 46%|████▌     | 889/1939 [01:09<00:25, 40.84it/s]
 46%|████▌     | 894/1939 [01:09<00:26, 40.15it/s]
 46%|████▋     | 899/1939 [01:09<00:26, 39.68it/s]
 47%|████▋     | 904/1939 [01:09<00:47, 21.66it/s]
 47%|████▋     | 908/1939 [01:09<00:43, 23.94it/s]
 47%|████▋     | 912/1939 [01:10<01:01, 16.60it/s]
 47%|████▋     | 915/1939 [01:10<01:10, 14.57it/s]
 47%|████▋     | 918/1939 [01:11<01:16, 13.30it/s]
 47%|████▋     | 920/1939 [01:11<01:29, 11.37it/s]
 48%|████▊     | 923/1939 [01:11<01:14, 13.66it/s]
 48%|████▊     | 927/1939 [01:11<01:08, 14.74it/s]
 48%|████▊     | 930/1939 [01:11<01:00, 16.80it/s]
 48%|████▊     | 933/1939 [01:12<01:24, 11.86it/s]
 48%|████▊     | 935/1939 [01:12<01:22, 12.20it/s]
 48%|████▊     | 938/1939 [01:12<01:08, 14.66it/s]
 49%|████▉     | 946/1939 [01:12<00:38, 25.76it/s]
 49%|████▉     | 953/1939 [01:12<00:29, 33.75it/s]
 50%|████▉     | 960/1939 [01:12<00:23, 40.84it/s]
 50%|████▉     | 966/1939 [01:12<00:21, 44.48it/s]
 50%|█████     | 972/1939 [01:13<00:50, 19.19it/s]
 50%|█████     | 976/1939 [01:13<00:53, 17.84it/s]
 51%|█████     | 980/1939 [01:14<00:58, 16.51it/s]
 51%|█████     | 983/1939 [01:14<01:06, 14.38it/s]
 51%|█████     | 986/1939 [01:14<01:02, 15.36it/s]
 51%|█████     | 989/1939 [01:15<01:15, 12.64it/s]
 51%|█████     | 993/1939 [01:15<01:09, 13.68it/s]
 51%|█████▏    | 995/1939 [01:15<01:10, 13.40it/s]
 51%|█████▏    | 997/1939 [01:15<01:18, 12.05it/s]
 52%|█████▏    | 999/1939 [01:15<01:22, 11.36it/s]
 52%|█████▏    | 1002/1939 [01:16<01:25, 10.92it/s]
 52%|█████▏    | 1004/1939 [01:16<01:20, 11.64it/s]
 52%|█████▏    | 1006/1939 [01:16<01:29, 10.47it/s]
 52%|█████▏    | 1008/1939 [01:16<01:17, 11.96it/s]
 52%|█████▏    | 1010/1939 [01:16<01:37,  9.54it/s]
 52%|█████▏    | 1012/1939 [01:17<02:06,  7.31it/s]
 52%|█████▏    | 1013/1939 [01:17<02:06,  7.33it/s]
 52%|█████▏    | 1014/1939 [01:17<02:02,  7.57it/s]
 52%|█████▏    | 1016/1939 [01:17<01:42,  9.03it/s]
 53%|█████▎    | 1018/1939 [01:17<01:25, 10.82it/s]
 53%|█████▎    | 1020/1939 [01:18<01:17, 11.84it/s]
 53%|█████▎    | 1022/1939 [01:18<01:30, 10.09it/s]
 53%|█████▎    | 1026/1939 [01:18<01:00, 15.15it/s]
 53%|█████▎    | 1028/1939 [01:18<01:07, 13.56it/s]
 53%|█████▎    | 1030/1939 [01:18<01:27, 10.39it/s]
 53%|█████▎    | 1033/1939 [01:19<01:26, 10.51it/s]
 53%|█████▎    | 1036/1939 [01:19<01:09, 13.01it/s]
 54%|█████▎    | 1038/1939 [01:19<01:13, 12.29it/s]
 54%|█████▎    | 1040/1939 [01:19<01:25, 10.50it/s]
 54%|█████▎    | 1042/1939 [01:20<01:35,  9.37it/s]
 54%|█████▍    | 1045/1939 [01:20<01:32,  9.68it/s]
 54%|█████▍    | 1047/1939 [01:20<01:25, 10.46it/s]
 54%|█████▍    | 1049/1939 [01:20<01:43,  8.60it/s]
 54%|█████▍    | 1050/1939 [01:21<01:52,  7.92it/s]
 54%|█████▍    | 1051/1939 [01:21<02:08,  6.91it/s]
 54%|█████▍    | 1052/1939 [01:21<02:30,  5.90it/s]
 54%|█████▍    | 1053/1939 [01:21<02:39,  5.54it/s]
 54%|█████▍    | 1054/1939 [01:21<02:33,  5.75it/s]
 54%|█████▍    | 1056/1939 [01:22<02:22,  6.21it/s]
 55%|█████▍    | 1057/1939 [01:22<02:24,  6.09it/s]
 55%|█████▍    | 1059/1939 [01:22<02:01,  7.23it/s]
 55%|█████▍    | 1060/1939 [01:22<02:11,  6.67it/s]
 55%|█████▍    | 1062/1939 [01:22<01:38,  8.88it/s]
 55%|█████▌    | 1068/1939 [01:23<01:02, 13.96it/s]
 55%|█████▌    | 1070/1939 [01:23<01:13, 11.79it/s]
 55%|█████▌    | 1073/1939 [01:23<01:01, 14.14it/s]
 55%|█████▌    | 1075/1939 [01:23<01:12, 11.98it/s]
 56%|█████▌    | 1077/1939 [01:24<01:22, 10.48it/s]
 56%|█████▌    | 1080/1939 [01:24<01:20, 10.70it/s]
 56%|█████▌    | 1082/1939 [01:24<01:12, 11.87it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 284.85it/s]
 67%|██████▋   | 201/300 [09:18<45:42, 27.70s/it]

[[np.int64(0), False, 11], [np.int64(1), False, 5], [np.int64(2), False, 3], [np.int64(3), False, 11], [np.int64(4), False, 9], [np.int64(6), False, 11], [np.int64(7), False, 5], [np.int64(8), False, 0], [np.int64(9), False, 5], [np.int64(10), False, 11], [np.int64(12), False, 9], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1611, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.1494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2856, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 203/300 [09:19<27:51, 17.23s/it]

tensor(12.1570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4100, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4931, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [09:19<16:42, 10.55s/it]

tensor(12.1743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5107, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1662, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5396, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [09:19<10:33,  6.81s/it]

tensor(12.1592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5722, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5539, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [09:19<06:53,  4.54s/it]

tensor(12.1581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5674, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [09:19<04:35,  3.09s/it]

tensor(12.1598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5627, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5490, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5504, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [09:19<03:06,  2.14s/it]

tensor(12.1472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5547, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5676, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [09:20<02:07,  1.50s/it]

tensor(12.1346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5826, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [09:20<01:28,  1.07s/it]

tensor(12.1338, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5965, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6091, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6151, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [09:20<01:02,  1.30it/s]

tensor(12.1247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6157, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6127, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [09:20<00:44,  1.77it/s]

tensor(12.1141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6151, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [09:20<00:32,  2.36it/s]

tensor(12.1115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6145, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6076, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [09:21<00:24,  3.09it/s]

tensor(12.1036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6056, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0205, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5997, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [09:21<00:18,  3.92it/s]

tensor(12.0942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0203, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5983, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [09:21<00:14,  4.83it/s]

tensor(12.0909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6015, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6032, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6027, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [09:21<00:11,  5.78it/s]

tensor(12.0834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0200, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6053, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6083, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [09:21<00:10,  6.68it/s]

tensor(12.0776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0197, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6092, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [09:22<00:08,  7.48it/s]

tensor(12.0749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6089, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0198, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6147, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6124, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [09:22<00:07,  8.22it/s]

tensor(12.0687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0196, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0195, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6161, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [09:22<00:06,  8.82it/s]

tensor(12.0646, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6175, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [09:22<00:06,  9.28it/s]

tensor(12.0622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6170, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0580, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6161, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [09:22<00:05,  9.65it/s]

tensor(12.0562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6189, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0193, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6210, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [09:22<00:05,  9.91it/s]

tensor(12.0526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6214, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [09:23<00:05, 10.08it/s]

tensor(12.0508, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6241, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6248, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6251, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [09:23<00:05, 10.17it/s]

tensor(12.0456, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6252, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([152, 211, 121,  30, 138,  82, 244,  98, 212, 320,  23, 127, 104,  77])

  0%|          | 0/1939 [00:00<?, ?it/s]
  0%|          | 3/1939 [00:00<01:12, 26.72it/s]
  1%|          | 10/1939 [00:00<00:41, 46.70it/s]
  1%|          | 15/1939 [00:00<00:51, 37.09it/s]
  1%|          | 19/1939 [00:00<01:06, 28.69it/s]
  1%|          | 24/1939 [00:00<00:56, 33.64it/s]
  2%|▏         | 30/1939 [00:00<00:49, 38.75it/s]
  2%|▏         | 35/1939 [00:00<00:50, 37.82it/s]
  2%|▏         | 40/1939 [00:01<00:46, 40.87it/s]
  2%|▏         | 45/1939 [00:01<01:29, 21.19it/s]
  3%|▎         | 49/1939 [00:01<01:37, 19.32it/s]
  3%|▎         | 52/1939 [00:01<01:35, 19.84it/s]
  3%|▎         | 55/1939 [00:02<02:02, 15.36it/s]
  3%|▎         | 61/1939 [00:02<01:26, 21.71it/s]
  3%|▎         | 66/1939 [00:02<01:30, 20.59it/s]
  4%|▎         | 69/1939 [00:02<01:27, 21.33it/s]
  4%|▍         | 73/1939 [00:03<01:37, 19.04it/s]
  4%|▍         | 76/1939 [00:03<01:35, 19.49it/s]
  4%|▍         | 79/1939 [00:03<01:52, 16.58it/s]
  4%|▍         | 81/1939 [00:03<02:56, 10.53it/s]
  4%|▍         | 83/1939 [00:04<03:07,  9.92it/s]
  4%|▍         | 86/1939 [00:04<03:05, 10.00it/s]
  5%|▍         | 88/1939 [00:04<02:46, 11.09it/s]
  5%|▍         | 90/1939 [00:04<02:31, 12.17it/s]
  5%|▍         | 95/1939 [00:04<01:38, 18.72it/s]
  5%|▌         | 100/1939 [00:05<01:30, 20.25it/s]
  5%|▌         | 103/1939 [00:05<01:36, 19.01it/s]
  6%|▌         | 107/1939 [00:05<01:19, 22.95it/s]
  6%|▌         | 114/1939 [00:05<00:57, 31.65it/s]
  6%|▌         | 118/1939 [00:05<01:21, 22.39it/s]
  6%|▌         | 121/1939 [00:06<01:45, 17.19it/s]
  6%|▋         | 126/1939 [00:06<01:22, 21.86it/s]
  7%|▋         | 129/1939 [00:06<01:38, 18.39it/s]
  7%|▋         | 132/1939 [00:06<01:53, 15.91it/s]
  7%|▋         | 135/1939 [00:07<02:12, 13.57it/s]
  7%|▋         | 137/1939 [00:07<02:33, 11.76it/s]
  7%|▋         | 139/1939 [00:07<02:20, 12.81it/s]
  7%|▋         | 145/1939 [00:07<01:55, 15.55it/s]
  8%|▊         | 147/1939 [00:07<01:53, 15.75it/s]
  8%|▊         | 153/1939 [00:08<01:41, 17.57it/s]
  8%|▊         | 156/1939 [00:08<01:33, 19.12it/s]
  8%|▊         | 159/1939 [00:08<02:47, 10.63it/s]
  8%|▊         | 161/1939 [00:09<03:32,  8.35it/s]
  8%|▊         | 163/1939 [00:09<04:00,  7.38it/s]
  9%|▊         | 165/1939 [00:09<04:01,  7.36it/s]
  9%|▊         | 168/1939 [00:10<02:59,  9.85it/s]
  9%|▉         | 174/1939 [00:10<01:48, 16.27it/s]
  9%|▉         | 180/1939 [00:10<01:17, 22.83it/s]
 10%|▉         | 186/1939 [00:10<01:00, 28.89it/s]
 10%|▉         | 190/1939 [00:10<00:56, 30.87it/s]
 10%|█         | 197/1939 [00:10<00:44, 39.04it/s]
 10%|█         | 202/1939 [00:10<00:54, 31.81it/s]
 11%|█         | 206/1939 [00:11<01:52, 15.38it/s]
 11%|█         | 209/1939 [00:11<01:44, 16.61it/s]
 83%|████████▎ | 249/300 [09:36<00:05, 10.17it/s]]
 11%|█         | 215/1939 [00:11<01:36, 17.93it/s]
 11%|█▏        | 222/1939 [00:12<01:05, 26.22it/s]
 12%|█▏        | 228/1939 [00:12<01:03, 26.80it/s]
 12%|█▏        | 232/1939 [00:12<01:03, 26.68it/s]
 12%|█▏        | 236/1939 [00:12<01:44, 16.31it/s]
 12%|█▏        | 239/1939 [00:13<02:00, 14.14it/s]
 12%|█▏        | 241/1939 [00:13<02:42, 10.44it/s]
 13%|█▎        | 243/1939 [00:14<03:35,  7.87it/s]
 13%|█▎        | 245/1939 [00:14<03:44,  7.55it/s]
 13%|█▎        | 247/1939 [00:14<03:37,  7.78it/s]
 13%|█▎        | 249/1939 [00:14<03:07,  9.01it/s]
 13%|█▎        | 252/1939 [00:14<02:21, 11.95it/s]
 13%|█▎        | 256/1939 [00:15<01:41, 16.52it/s]
 14%|█▎        | 262/1939 [00:15<01:11, 23.49it/s]
 14%|█▎        | 266/1939 [00:15<01:33, 17.94it/s]
 14%|█▍        | 269/1939 [00:15<01:29, 18.62it/s]
 14%|█▍        | 275/1939 [00:15<01:04, 25.61it/s]
 14%|█▍        | 281/1939 [00:16<01:12, 23.00it/s]
 15%|█▍        | 284/1939 [00:16<01:11, 23.28it/s]
 15%|█▍        | 288/1939 [00:16<01:23, 19.82it/s]
 15%|█▌        | 291/1939 [00:16<01:19, 20.86it/s]
 15%|█▌        | 294/1939 [00:16<01:35, 17.21it/s]
 15%|█▌        | 298/1939 [00:16<01:18, 20.90it/s]
 16%|█▌        | 304/1939 [00:17<00:57, 28.19it/s]
 16%|█▌        | 308/1939 [00:17<01:12, 22.50it/s]
 16%|█▌        | 311/1939 [00:17<01:15, 21.59it/s]
 16%|█▌        | 315/1939 [00:17<01:22, 19.73it/s]
 16%|█▋        | 318/1939 [00:17<01:22, 19.60it/s]
 17%|█▋        | 322/1939 [00:18<01:31, 17.58it/s]
 17%|█▋        | 324/1939 [00:18<01:34, 17.18it/s]
 17%|█▋        | 329/1939 [00:18<01:13, 21.78it/s]
 17%|█▋        | 335/1939 [00:18<00:55, 29.14it/s]
 18%|█▊        | 342/1939 [00:18<00:42, 37.58it/s]
 18%|█▊        | 347/1939 [00:18<00:44, 35.48it/s]
 18%|█▊        | 351/1939 [00:18<00:48, 33.01it/s]
 18%|█▊        | 355/1939 [00:19<01:07, 23.35it/s]
 18%|█▊        | 358/1939 [00:19<01:15, 20.93it/s]
 19%|█▊        | 362/1939 [00:19<01:04, 24.27it/s]
 19%|█▉        | 365/1939 [00:19<01:17, 20.23it/s]
 19%|█▉        | 370/1939 [00:19<01:01, 25.45it/s]
 19%|█▉        | 375/1939 [00:20<00:51, 30.26it/s]
 20%|█▉        | 379/1939 [00:20<01:14, 20.92it/s]
 20%|█▉        | 384/1939 [00:20<01:17, 19.99it/s]
 20%|█▉        | 387/1939 [00:20<01:34, 16.38it/s]
 20%|██        | 390/1939 [00:21<02:01, 12.74it/s]
 20%|██        | 392/1939 [00:21<01:55, 13.37it/s]
 20%|██        | 394/1939 [00:21<02:35,  9.92it/s]
 20%|██        | 396/1939 [00:22<02:40,  9.59it/s]
 21%|██        | 398/1939 [00:22<02:52,  8.93it/s]
 21%|██        | 400/1939 [00:22<02:28, 10.38it/s]
 21%|██        | 404/1939 [00:22<02:11, 11.68it/s]
 21%|██        | 406/1939 [00:22<02:26, 10.49it/s]
 21%|██        | 408/1939 [00:23<02:08, 11.89it/s]
 21%|██        | 411/1939 [00:23<02:02, 12.48it/s]
 21%|██▏       | 414/1939 [00:23<01:40, 15.13it/s]
 21%|██▏       | 416/1939 [00:23<02:04, 12.25it/s]
 22%|██▏       | 419/1939 [00:23<02:14, 11.32it/s]
 22%|██▏       | 421/1939 [00:24<02:01, 12.50it/s]
 22%|██▏       | 423/1939 [00:24<02:22, 10.66it/s]
 22%|██▏       | 425/1939 [00:24<02:10, 11.62it/s]
 22%|██▏       | 427/1939 [00:24<02:24, 10.49it/s]
 22%|██▏       | 429/1939 [00:24<02:36,  9.63it/s]
 22%|██▏       | 433/1939 [00:25<01:44, 14.43it/s]
 23%|██▎       | 440/1939 [00:25<01:00, 24.58it/s]
 23%|██▎       | 446/1939 [00:25<00:46, 31.78it/s]
 23%|██▎       | 452/1939 [00:25<00:38, 38.20it/s]
 24%|██▎       | 458/1939 [00:25<00:37, 39.58it/s]
 24%|██▍       | 463/1939 [00:25<00:38, 38.14it/s]
 24%|██▍       | 469/1939 [00:25<00:34, 43.14it/s]
 24%|██▍       | 475/1939 [00:25<00:32, 45.59it/s]
 25%|██▍       | 483/1939 [00:26<00:27, 53.39it/s]
 25%|██▌       | 489/1939 [00:26<00:26, 55.11it/s]
 26%|██▌       | 495/1939 [00:26<00:26, 54.34it/s]
 26%|██▌       | 501/1939 [00:26<00:25, 55.67it/s]
 26%|██▌       | 507/1939 [00:26<00:25, 55.89it/s]
 27%|██▋       | 514/1939 [00:26<00:24, 57.90it/s]
 27%|██▋       | 521/1939 [00:26<00:23, 59.46it/s]
 27%|██▋       | 528/1939 [00:26<00:22, 61.94it/s]
 28%|██▊       | 535/1939 [00:26<00:24, 58.16it/s]
 28%|██▊       | 541/1939 [00:27<00:24, 56.14it/s]
 28%|██▊       | 547/1939 [00:27<00:25, 54.52it/s]
 29%|██▊       | 553/1939 [00:27<00:45, 30.55it/s]
 29%|██▉       | 558/1939 [00:27<00:42, 32.12it/s]
 29%|██▉       | 563/1939 [00:27<00:39, 34.98it/s]
 29%|██▉       | 568/1939 [00:27<00:36, 37.91it/s]
 30%|██▉       | 573/1939 [00:28<01:05, 20.74it/s]
 30%|██▉       | 577/1939 [00:28<01:33, 14.57it/s]
 30%|██▉       | 580/1939 [00:29<01:29, 15.26it/s]
 30%|███       | 583/1939 [00:29<01:26, 15.69it/s]
 30%|███       | 586/1939 [00:29<01:48, 12.51it/s]
 30%|███       | 588/1939 [00:29<01:44, 12.97it/s]
 31%|███       | 592/1939 [00:29<01:21, 16.59it/s]
 31%|███       | 595/1939 [00:30<01:23, 16.17it/s]
 31%|███       | 599/1939 [00:30<01:26, 15.47it/s]
 31%|███       | 601/1939 [00:30<01:41, 13.18it/s]
 31%|███       | 605/1939 [00:30<01:19, 16.81it/s]
 31%|███▏      | 608/1939 [00:31<01:48, 12.27it/s]
 32%|███▏      | 611/1939 [00:31<01:37, 13.68it/s]
 32%|███▏      | 613/1939 [00:31<02:23,  9.25it/s]
 32%|███▏      | 615/1939 [00:32<02:50,  7.76it/s]
 32%|███▏      | 617/1939 [00:32<03:01,  7.29it/s]
 32%|███▏      | 618/1939 [00:32<03:22,  6.52it/s]
 32%|███▏      | 620/1939 [00:32<03:08,  6.99it/s]
 32%|███▏      | 622/1939 [00:33<02:37,  8.36it/s]
 32%|███▏      | 624/1939 [00:33<02:17,  9.58it/s]
 32%|███▏      | 629/1939 [00:33<01:19, 16.42it/s]
 33%|███▎      | 632/1939 [00:33<01:32, 14.16it/s]
 33%|███▎      | 636/1939 [00:33<01:30, 14.46it/s]
 33%|███▎      | 639/1939 [00:34<01:22, 15.77it/s]
 33%|███▎      | 642/1939 [00:34<01:11, 18.06it/s]
 33%|███▎      | 649/1939 [00:34<00:46, 27.90it/s]
 34%|███▍      | 656/1939 [00:34<00:47, 26.78it/s]
 34%|███▍      | 660/1939 [00:34<01:07, 19.05it/s]
 34%|███▍      | 664/1939 [00:35<00:58, 21.95it/s]
 34%|███▍      | 667/1939 [00:35<01:30, 14.08it/s]
 35%|███▍      | 671/1939 [00:35<01:12, 17.39it/s]
 35%|███▍      | 674/1939 [00:35<01:24, 14.91it/s]
 35%|███▍      | 677/1939 [00:36<01:37, 13.00it/s]
 35%|███▌      | 682/1939 [00:36<01:10, 17.74it/s]
 35%|███▌      | 687/1939 [00:36<01:12, 17.22it/s]
 36%|███▌      | 690/1939 [00:36<01:19, 15.72it/s]
 36%|███▌      | 693/1939 [00:37<01:14, 16.79it/s]
 36%|███▌      | 698/1939 [00:37<00:56, 21.85it/s]
 36%|███▋      | 704/1939 [00:37<00:42, 28.78it/s]
 37%|███▋      | 712/1939 [00:37<00:32, 38.18it/s]
 37%|███▋      | 717/1939 [00:37<00:31, 39.09it/s]
 37%|███▋      | 722/1939 [00:37<00:34, 35.69it/s]
 38%|███▊      | 728/1939 [00:37<00:30, 39.69it/s]
 38%|███▊      | 733/1939 [00:38<01:06, 18.11it/s]
 38%|███▊      | 737/1939 [00:38<01:10, 17.13it/s]
 38%|███▊      | 742/1939 [00:39<01:11, 16.76it/s]
 38%|███▊      | 745/1939 [00:39<01:11, 16.65it/s]
 39%|███▊      | 749/1939 [00:39<01:00, 19.56it/s]
 39%|███▉      | 755/1939 [00:39<01:01, 19.24it/s]
 39%|███▉      | 758/1939 [00:39<01:00, 19.38it/s]
 39%|███▉      | 761/1939 [00:40<01:13, 15.93it/s]
 39%|███▉      | 763/1939 [00:40<01:27, 13.50it/s]
 39%|███▉      | 765/1939 [00:40<01:24, 13.93it/s]
 40%|███▉      | 767/1939 [00:40<01:55, 10.13it/s]
 40%|███▉      | 769/1939 [00:41<02:13,  8.76it/s]
 40%|███▉      | 771/1939 [00:41<02:10,  8.96it/s]
 40%|███▉      | 773/1939 [00:41<02:35,  7.50it/s]
 40%|███▉      | 775/1939 [00:41<02:09,  8.98it/s]
 40%|████      | 777/1939 [00:42<02:40,  7.26it/s]
 40%|████      | 779/1939 [00:42<02:34,  7.49it/s]
 40%|████      | 780/1939 [00:42<02:37,  7.34it/s]
 40%|████      | 782/1939 [00:42<02:17,  8.44it/s]
 40%|████      | 784/1939 [00:43<02:14,  8.57it/s]
 41%|████      | 787/1939 [00:43<01:59,  9.62it/s]
 41%|████      | 789/1939 [00:43<02:08,  8.92it/s]
 41%|████      | 792/1939 [00:43<01:38, 11.64it/s]
 41%|████      | 798/1939 [00:44<01:16, 14.94it/s]
 41%|████▏     | 801/1939 [00:44<01:08, 16.61it/s]
 41%|████▏     | 803/1939 [00:44<01:08, 16.62it/s]
 42%|████▏     | 805/1939 [00:44<01:08, 16.63it/s]
 42%|████▏     | 807/1939 [00:44<01:06, 16.92it/s]
 42%|████▏     | 809/1939 [00:44<01:11, 15.79it/s]
 42%|████▏     | 811/1939 [00:44<01:11, 15.69it/s]
 42%|████▏     | 813/1939 [00:45<01:34, 11.94it/s]
 42%|████▏     | 815/1939 [00:45<01:29, 12.57it/s]
 42%|████▏     | 817/1939 [00:45<02:10,  8.57it/s]
 42%|████▏     | 819/1939 [00:46<02:49,  6.61it/s]
 42%|████▏     | 821/1939 [00:46<02:36,  7.15it/s]
 42%|████▏     | 822/1939 [00:46<02:46,  6.72it/s]
 42%|████▏     | 823/1939 [00:46<02:53,  6.45it/s]
 43%|████▎     | 825/1939 [00:46<02:13,  8.32it/s]
 43%|████▎     | 827/1939 [00:46<01:47, 10.36it/s]
 43%|████▎     | 829/1939 [00:47<01:44, 10.64it/s]
 43%|████▎     | 831/1939 [00:47<01:31, 12.16it/s]
 43%|████▎     | 836/1939 [00:47<00:57, 19.12it/s]
 43%|████▎     | 841/1939 [00:47<00:43, 25.25it/s]
 44%|████▎     | 845/1939 [00:47<00:38, 28.34it/s]
 44%|████▍     | 851/1939 [00:47<00:30, 35.40it/s]
 44%|████▍     | 857/1939 [00:47<00:26, 40.92it/s]
 45%|████▍     | 863/1939 [00:47<00:24, 44.23it/s]
 45%|████▍     | 870/1939 [00:47<00:21, 49.57it/s]
 45%|████▌     | 876/1939 [00:48<00:20, 51.39it/s]
 45%|████▌     | 882/1939 [00:48<00:19, 53.45it/s]
 46%|████▌     | 888/1939 [00:48<00:19, 54.17it/s]
 46%|████▌     | 895/1939 [00:48<00:19, 54.50it/s]
 46%|████▋     | 901/1939 [00:48<00:22, 46.98it/s]
 47%|████▋     | 906/1939 [00:49<00:43, 23.95it/s]
 47%|████▋     | 910/1939 [00:49<00:50, 20.54it/s]
 47%|████▋     | 914/1939 [00:49<00:46, 22.05it/s]
 47%|████▋     | 918/1939 [00:49<00:52, 19.62it/s]
 48%|████▊     | 922/1939 [00:49<00:46, 21.97it/s]
 48%|████▊     | 927/1939 [00:50<00:47, 21.23it/s]
 48%|████▊     | 930/1939 [00:50<00:47, 21.03it/s]
 48%|████▊     | 933/1939 [00:50<01:06, 15.11it/s]
 48%|████▊     | 938/1939 [00:50<00:50, 19.93it/s]
 49%|████▊     | 941/1939 [00:50<00:49, 20.07it/s]
 49%|████▊     | 944/1939 [00:51<00:46, 21.55it/s]
 49%|████▉     | 948/1939 [00:51<00:39, 24.84it/s]
 49%|████▉     | 953/1939 [00:51<00:33, 29.74it/s]
 49%|████▉     | 959/1939 [00:51<00:27, 35.73it/s]
 50%|████▉     | 965/1939 [00:51<00:23, 41.34it/s]
 50%|█████     | 970/1939 [00:52<00:48, 20.09it/s]
 50%|█████     | 974/1939 [00:52<01:11, 13.49it/s]
 50%|█████     | 977/1939 [00:52<01:15, 12.75it/s]
 51%|█████     | 980/1939 [00:53<01:20, 11.87it/s]
 51%|█████     | 982/1939 [00:53<01:28, 10.77it/s]
 51%|█████     | 984/1939 [00:53<01:23, 11.45it/s]
 51%|█████     | 986/1939 [00:53<01:18, 12.14it/s]
 51%|█████     | 990/1939 [00:53<00:59, 16.06it/s]
 51%|█████     | 993/1939 [00:53<00:51, 18.39it/s]
 51%|█████▏    | 997/1939 [00:54<00:53, 17.54it/s]
 52%|█████▏    | 1000/1939 [00:54<01:07, 14.00it/s]
 52%|█████▏    | 1002/1939 [00:54<01:16, 12.24it/s]
 52%|█████▏    | 1005/1939 [00:55<01:22, 11.27it/s]
 52%|█████▏    | 1008/1939 [00:55<01:12, 12.77it/s]
 52%|█████▏    | 1010/1939 [00:55<01:41,  9.17it/s]
 52%|█████▏    | 1012/1939 [00:55<01:51,  8.34it/s]
 52%|█████▏    | 1014/1939 [00:56<01:48,  8.50it/s]
 52%|█████▏    | 1015/1939 [00:56<02:04,  7.41it/s]
 52%|█████▏    | 1016/1939 [00:56<02:06,  7.28it/s]
 53%|█████▎    | 1018/1939 [00:56<01:44,  8.82it/s]
 53%|█████▎    | 1019/1939 [00:56<01:48,  8.48it/s]
 53%|█████▎    | 1021/1939 [00:56<01:31, 10.06it/s]
 53%|█████▎    | 1023/1939 [00:57<01:33,  9.76it/s]
 53%|█████▎    | 1025/1939 [00:57<01:18, 11.69it/s]
 53%|█████▎    | 1027/1939 [00:57<01:27, 10.38it/s]
 53%|█████▎    | 1029/1939 [00:57<01:16, 11.87it/s]
 53%|█████▎    | 1035/1939 [00:57<00:45, 19.72it/s]
 54%|█████▎    | 1042/1939 [00:57<00:29, 30.31it/s]
 54%|█████▍    | 1046/1939 [00:58<00:38, 23.21it/s]
 54%|█████▍    | 1050/1939 [00:58<00:33, 26.27it/s]
 54%|█████▍    | 1054/1939 [00:58<01:04, 13.63it/s]
 55%|█████▍    | 1057/1939 [00:59<01:10, 12.56it/s]
 55%|█████▍    | 1060/1939 [00:59<01:30,  9.76it/s]
 55%|█████▍    | 1063/1939 [00:59<01:14, 11.81it/s]
 55%|█████▌    | 1069/1939 [00:59<00:48, 17.84it/s]
 55%|█████▌    | 1075/1939 [01:00<00:35, 24.19it/s]
 56%|█████▌    | 1080/1939 [01:00<00:39, 21.77it/s]
 56%|█████▌    | 1084/1939 [01:00<00:37, 23.06it/s]
 56%|█████▌    | 1088/1939 [01:00<00:41, 20.43it/s]
 56%|█████▋    | 1091/1939 [01:00<00:41, 20.40it/s]
 56%|█████▋    | 1094/1939 [01:01<01:04, 13.02it/s]
 57%|█████▋    | 1097/1939 [01:01<01:07, 12.41it/s]
 57%|█████▋    | 1100/1939 [01:01<00:58, 14.29it/s]
 57%|█████▋    | 1102/1939 [01:02<01:08, 12.31it/s]
 57%|█████▋    | 1104/1939 [01:02<01:14, 11.24it/s]
 57%|█████▋    | 1106/1939 [01:02<01:08, 12.23it/s]
 57%|█████▋    | 1108/1939 [01:02<01:04, 12.88it/s]
 57%|█████▋    | 1110/1939 [01:02<01:16, 10.78it/s]
 57%|█████▋    | 1112/1939 [01:03<01:24,  9.78it/s]
 57%|█████▋    | 1114/1939 [01:03<01:14, 11.03it/s]
 58%|█████▊    | 1116/1939 [01:03<01:21, 10.10it/s]
 58%|█████▊    | 1118/1939 [01:03<01:14, 11.06it/s]
 58%|█████▊    | 1121/1939 [01:03<01:11, 11.38it/s]
 58%|█████▊    | 1124/1939 [01:03<00:58, 14.05it/s]
 58%|█████▊    | 1129/1939 [01:04<00:49, 16.22it/s]
 58%|█████▊    | 1131/1939 [01:04<00:47, 16.87it/s]
 59%|█████▊    | 1137/1939 [01:04<00:46, 17.36it/s]
 59%|█████▉    | 1140/1939 [01:04<00:41, 19.29it/s]
 59%|█████▉    | 1143/1939 [01:05<01:00, 13.18it/s]
 59%|█████▉    | 1145/1939 [01:05<01:08, 11.53it/s]
 59%|█████▉    | 1148/1939 [01:05<01:11, 11.11it/s]
 59%|█████▉    | 1150/1939 [01:05<01:17, 10.14it/s]
 59%|█████▉    | 1152/1939 [01:06<01:23,  9.44it/s]
 60%|█████▉    | 1154/1939 [01:06<01:27,  8.96it/s]
 60%|█████▉    | 1159/1939 [01:06<00:54, 14.42it/s]
 60%|█████▉    | 1161/1939 [01:06<00:59, 12.98it/s]
 60%|█████▉    | 1163/1939 [01:07<01:15, 10.33it/s]
 60%|██████    | 1166/1939 [01:07<01:01, 12.60it/s]
 60%|██████    | 1173/1939 [01:07<00:35, 21.43it/s]
 61%|██████    | 1176/1939 [01:07<00:33, 22.63it/s]
 61%|██████    | 1179/1939 [01:07<00:33, 22.35it/s]
 61%|██████    | 1182/1939 [01:07<00:47, 15.94it/s]
 61%|██████    | 1185/1939 [01:08<00:56, 13.31it/s]
 61%|██████    | 1187/1939 [01:08<01:04, 11.72it/s]
 61%|██████▏   | 1190/1939 [01:08<01:05, 11.40it/s]
 61%|██████▏   | 1192/1939 [01:09<01:28,  8.45it/s]
 62%|██████▏   | 1194/1939 [01:09<01:26,  8.64it/s]
 62%|██████▏   | 1196/1939 [01:09<01:25,  8.66it/s]
 62%|██████▏   | 1198/1939 [01:09<01:15,  9.84it/s]
 62%|██████▏   | 1201/1939 [01:09<00:59, 12.31it/s]
 62%|██████▏   | 1207/1939 [01:10<00:36, 20.05it/s]
 63%|██████▎   | 1214/1939 [01:10<00:25, 28.75it/s]
 63%|██████▎   | 1218/1939 [01:10<00:32, 22.48it/s]
 63%|██████▎   | 1223/1939 [01:10<00:26, 26.97it/s]
 63%|██████▎   | 1227/1939 [01:10<00:32, 21.96it/s]
 63%|██████▎   | 1230/1939 [01:10<00:30, 23.21it/s]
 64%|██████▎   | 1234/1939 [01:11<00:27, 26.08it/s]
 64%|██████▍   | 1240/1939 [01:11<00:21, 33.11it/s]
 64%|██████▍   | 1246/1939 [01:11<00:22, 30.14it/s]
 64%|██████▍   | 1250/1939 [01:11<00:22, 29.99it/s]
 65%|██████▍   | 1254/1939 [01:11<00:27, 24.71it/s]
 65%|██████▍   | 1257/1939 [01:11<00:27, 24.71it/s]
 65%|██████▍   | 1260/1939 [01:12<00:35, 19.08it/s]
 65%|██████▌   | 1265/1939 [01:12<00:27, 24.16it/s]
 65%|██████▌   | 1268/1939 [01:12<00:33, 19.82it/s]
 66%|██████▌   | 1271/1939 [01:12<00:34, 19.28it/s]
 66%|██████▌   | 1274/1939 [01:12<00:35, 18.51it/s]
 66%|██████▌   | 1280/1939 [01:12<00:25, 25.80it/s]
 66%|██████▋   | 1285/1939 [01:13<00:22, 29.46it/s]
 66%|██████▋   | 1289/1939 [01:13<00:29, 22.06it/s]
 67%|██████▋   | 1292/1939 [01:13<00:36, 17.82it/s]
 67%|██████▋   | 1295/1939 [01:13<00:32, 19.78it/s]
 67%|██████▋   | 1301/1939 [01:13<00:23, 27.08it/s]
 67%|██████▋   | 1306/1939 [01:13<00:19, 31.79it/s]
 68%|██████▊   | 1310/1939 [01:14<00:24, 25.52it/s]
 68%|██████▊   | 1314/1939 [01:14<00:36, 17.16it/s]
 68%|██████▊   | 1317/1939 [01:14<00:35, 17.36it/s]
 68%|██████▊   | 1323/1939 [01:15<00:34, 17.71it/s]
 68%|██████▊   | 1326/1939 [01:15<00:31, 19.24it/s]
 69%|██████▊   | 1331/1939 [01:15<00:26, 22.95it/s]
 69%|██████▉   | 1334/1939 [01:15<00:33, 18.25it/s]
 69%|██████▉   | 1337/1939 [01:15<00:31, 19.13it/s]
 69%|██████▉   | 1340/1939 [01:15<00:31, 18.93it/s]
 69%|██████▉   | 1343/1939 [01:16<00:41, 14.44it/s]
 69%|██████▉   | 1345/1939 [01:16<00:47, 12.52it/s]
 69%|██████▉   | 1347/1939 [01:16<00:44, 13.27it/s]
 70%|██████▉   | 1349/1939 [01:16<00:51, 11.37it/s]
 70%|██████▉   | 1351/1939 [01:17<00:49, 11.93it/s]
 70%|██████▉   | 1353/1939 [01:17<00:49, 11.86it/s]
 70%|██████▉   | 1355/1939 [01:17<00:47, 12.37it/s]
 70%|███████   | 1358/1939 [01:17<00:39, 14.84it/s]
 70%|███████   | 1360/1939 [01:17<00:37, 15.55it/s]
 70%|███████   | 1362/1939 [01:17<00:45, 12.57it/s]
 70%|███████   | 1364/1939 [01:17<00:43, 13.21it/s]
 71%|███████   | 1369/1939 [01:18<00:27, 20.74it/s]
 71%|███████   | 1376/1939 [01:18<00:17, 31.63it/s]
 71%|███████   | 1380/1939 [01:18<00:24, 22.44it/s]
 71%|███████▏  | 1383/1939 [01:19<00:43, 12.68it/s]
 71%|███████▏  | 1386/1939 [01:19<00:45, 12.22it/s]
 72%|███████▏  | 1389/1939 [01:19<00:45, 12.21it/s]
 72%|███████▏  | 1391/1939 [01:19<00:49, 11.10it/s]
 72%|███████▏  | 1393/1939 [01:20<00:53, 10.23it/s]
 72%|███████▏  | 1396/1939 [01:20<00:41, 12.94it/s]
 72%|███████▏  | 1399/1939 [01:20<00:40, 13.40it/s]
 72%|███████▏  | 1401/1939 [01:20<00:38, 13.93it/s]
 72%|███████▏  | 1403/1939 [01:20<00:45, 11.83it/s]
 72%|███████▏  | 1405/1939 [01:20<00:43, 12.19it/s]
 73%|███████▎  | 1407/1939 [01:21<00:51, 10.30it/s]
 73%|███████▎  | 1409/1939 [01:21<00:55,  9.59it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 307.74it/s]
 84%|████████▎ | 251/300 [11:15<13:46, 16.87s/it]

[[np.int64(0), False, 7], [np.int64(1), False, 9], [np.int64(2), False, 0], [np.int64(3), False, 6], [np.int64(4), False, 8], [np.int64(5), False, 4], [np.int64(6), False, 2], [np.int64(8), False, 9], [np.int64(10), False, 2], [np.int64(11), False, 2], [np.int64(12), False, 4], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0443, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5950, device='cuda:0', grad_fn=<MulBackward0>)

/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(12.0429, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5972, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 252/300 [11:15<11:08, 13.92s/it]

tensor(12.0414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6021, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▍ | 253/300 [11:15<08:43, 11.14s/it]

tensor(12.0398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6024, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [11:15<05:19,  7.11s/it]

tensor(12.0386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6054, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6082, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6087, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 258/300 [11:16<02:39,  3.80s/it]

tensor(12.0344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6108, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6100, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0318, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6088, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [11:16<01:38,  2.47s/it]

tensor(12.0304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6048, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [11:16<01:03,  1.66s/it]

tensor(12.0288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6024, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6011, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6000, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [11:16<00:41,  1.15s/it]

tensor(12.0244, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5997, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [11:16<00:27,  1.23it/s]

tensor(12.0215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5984, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [11:17<00:18,  1.70it/s]

tensor(12.0204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5979, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5982, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [11:17<00:13,  2.29it/s]

tensor(12.0163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5981, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5960, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [11:17<00:09,  3.00it/s]

tensor(12.0140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5993, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [11:17<00:06,  3.83it/s]

tensor(12.0127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5982, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0114, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0192, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [11:17<00:05,  4.74it/s]

tensor(12.0089, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5975, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5986, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [11:18<00:03,  5.67it/s]

tensor(12.0067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5985, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [11:18<00:03,  6.57it/s]

tensor(12.0056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5983, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0029, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5983, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [11:18<00:02,  7.39it/s]

tensor(12.0017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5975, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5976, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [11:18<00:01,  8.11it/s]

tensor(11.9995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5974, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [11:18<00:01,  8.70it/s]

tensor(11.9982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0194, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5972, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9970, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0191, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5967, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [11:19<00:01,  9.20it/s]

tensor(11.9946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5960, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5960, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [11:19<00:01,  9.55it/s]

tensor(11.9924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5961, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [11:19<00:00,  9.81it/s]

tensor(11.9915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5960, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0188, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5974, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0187, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5975, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [11:19<00:00,  9.97it/s]

tensor(11.9882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5969, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0185, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5968, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [11:19<00:00, 10.06it/s]

tensor(11.9861, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [11:19<00:00, 10.17it/s]

tensor(11.9849, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9841, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0189, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5978, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [11:20<00:00,  2.27s/it]

Model training finished!

Infer time:  0.0022513866424560547
PCA20 shape : (1939, 20)
PCA20 finite: True
mclust K    : 15

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E15
Seed        : 9
Spots       : 1939
Target K    : 15
Predicted K : 15
Embedding   : (1939, 64)
ARI         : 0.459694726518
NMI         : 0.590238653733
Runtime     : 701.29 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E15_seed9

==============================================================================================================
PRAGA RUN | S2-E18 | seed=0
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 9.956e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(16.0495, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0707, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8073, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:32,  9.03it/s]

tensor(16.0279, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7193, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9799, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8367, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:31,  9.42it/s]

tensor(15.9254, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1400, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8785, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6101, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 7/300 [00:00<00:31,  9.44it/s]

tensor(15.8342, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2302, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7968, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9877, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:30,  9.70it/s]

tensor(15.7652, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8678, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7350, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8566, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7065, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9464, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:29,  9.80it/s]

tensor(15.6767, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1270, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6463, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3869, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6128, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7210, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:29,  9.74it/s]

tensor(15.5761, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5377, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5800, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:28,  9.80it/s]

tensor(15.4975, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0932, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4567, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6543, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:29,  9.65it/s]

tensor(15.4167, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2600, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3763, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9042, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:29,  9.50it/s]

tensor(15.3386, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5840, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3011, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2954, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:28,  9.67it/s]

tensor(15.2617, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0369, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2222, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8031, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1794, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5939, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:27,  9.77it/s]

tensor(15.1340, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4053, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0850, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2367, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0343, device='cuda:0', grad_fn=<AddBackward0>)

 10%|▉         | 29/300 [00:03<00:27,  9.76it/s]

tensor(1.0840, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9481, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:27,  9.66it/s]

tensor(14.9309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8253, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7164, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:27,  9.74it/s]

tensor(14.8288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6184, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5307, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:27,  9.65it/s]

tensor(14.7255, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4529, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3829, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:28,  9.41it/s]

tensor(14.6184, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5625, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2670, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:27,  9.56it/s]

tensor(14.5056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2190, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1774, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▎        | 41/300 [00:04<00:26,  9.77it/s]

tensor(14.3892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1416, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1105, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:26,  9.85it/s]

tensor(14.2702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0858, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0662, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1459, device='cuda:0', grad_fn=<AddBackward0>)

 15%|█▌        | 45/300 [00:04<00:26,  9.77it/s]

tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:26,  9.75it/s]

tensor(14.0195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0352, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:05<00:25,  9.86it/s]

tensor(13.9009, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.88it/s]

tensor(13.7546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:25,  9.75it/s]

tensor(13.6465, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6123, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:25,  9.38it/s]

tensor(13.5772, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5406, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:06<00:24,  9.64it/s]

tensor(13.5045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4359, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.64it/s]

tensor(13.4048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:24,  9.55it/s]

tensor(13.3478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:24,  9.48it/s]

tensor(13.2937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:07<00:23,  9.74it/s]

tensor(13.2401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:23,  9.75it/s]

tensor(13.1586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:23,  9.64it/s]

tensor(13.1046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:23,  9.55it/s]

tensor(13.0521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:07<00:23,  9.57it/s]

tensor(13.0024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:08<00:22,  9.77it/s]

tensor(12.9560, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9123, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:22,  9.73it/s]

tensor(12.8913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:21,  9.84it/s]

tensor(12.8514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8146, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:21,  9.77it/s]

tensor(12.7969, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7801, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:09<00:21,  9.72it/s]

tensor(12.7640, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:09<00:21,  9.65it/s]

tensor(12.7332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:21,  9.66it/s]

tensor(12.7039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6897, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:21,  9.70it/s]

tensor(12.6760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:10<00:20,  9.79it/s]

tensor(12.6500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:10<00:20,  9.74it/s]

tensor(12.6258, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:20,  9.67it/s]

tensor(12.6032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([183, 163,  98, 130, 155, 117, 238, 390,  63,  90, 228,  87,  90, 216])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<01:54, 19.69it/s]
  0%|          | 7/2248 [00:00<01:06, 33.93it/s]
  0%|          | 11/2248 [00:00<01:08, 32.45it/s]
  1%|          | 18/2248 [00:00<00:50, 43.93it/s]
  1%|          | 25/2248 [00:00<00:44, 49.92it/s]
  1%|▏         | 32/2248 [00:00<00:40, 54.25it/s]
  2%|▏         | 38/2248 [00:00<00:40, 53.92it/s]
  2%|▏         | 44/2248 [00:00<00:50, 43.25it/s]
  2%|▏         | 50/2248 [00:01<00:47, 46.37it/s]
  2%|▏         | 56/2248 [00:01<00:45, 48.28it/s]
  3%|▎         | 62/2248 [00:01<00:43, 50.19it/s]
  3%|▎         | 68/2248 [00:01<00:41, 52.53it/s]
  3%|▎         | 75/2248 [00:02<01:42, 21.29it/s]
  4%|▎         | 80/2248 [00:02<01:35, 22.71it/s]
  4%|▍         | 85/2248 [00:02<01:23, 26.03it/s]
  4%|▍         | 89/2248 [00:03<02:22, 15.13it/s]
  4%|▍         | 95/2248 [00:03<01:47, 20.09it/s]
  4%|▍         | 99/2248 [00:03<02:38, 13.52it/s]
  5%|▍         | 104/2248 [00:03<02:04, 17.21it/s]
  5%|▍         | 109/2248 [00:03<01:40, 21.35it/s]
  5%|▌         | 115/2248 [00:04<01:19, 26.98it/s]
  5%|▌         | 120/2248 [00:05<03:11, 11.08it/s]
  6%|▌         | 124/2248 [00:05<03:53,  9.08it/s]
  6%|▌         | 127/2248 [00:06<05:39,  6.25it/s]
  6%|▌         | 129/2248 [00:07<05:45,  6.13it/s]
  6%|▌         | 131/2248 [00:07<05:00,  7.05it/s]
  6%|▌         | 133/2248 [00:07<05:10,  6.80it/s]
  6%|▌         | 135/2248 [00:08<05:39,  6.23it/s]
  6%|▌         | 137/2248 [00:08<05:38,  6.23it/s]
  6%|▌         | 138/2248 [00:08<06:05,  5.78it/s]
  6%|▌         | 140/2248 [00:08<04:51,  7.23it/s]
  6%|▋         | 145/2248 [00:09<03:38,  9.63it/s]
  7%|▋         | 147/2248 [00:09<03:15, 10.73it/s]
  7%|▋         | 151/2248 [00:09<03:20, 10.47it/s]
  7%|▋         | 154/2248 [00:09<02:46, 12.56it/s]
  7%|▋         | 156/2248 [00:10<03:08, 11.07it/s]
  7%|▋         | 158/2248 [00:11<06:36,  5.28it/s]
  7%|▋         | 159/2248 [00:11<07:10,  4.86it/s]
  7%|▋         | 160/2248 [00:11<08:05,  4.30it/s]
  7%|▋         | 162/2248 [00:11<06:38,  5.24it/s]
  7%|▋         | 164/2248 [00:12<05:04,  6.83it/s]
  7%|▋         | 166/2248 [00:12<05:43,  6.07it/s]
  8%|▊         | 170/2248 [00:12<03:29,  9.93it/s]
  8%|▊         | 173/2248 [00:13<04:31,  7.65it/s]
  8%|▊         | 175/2248 [00:13<03:53,  8.87it/s]
  8%|▊         | 177/2248 [00:13<05:24,  6.39it/s]
  8%|▊         | 179/2248 [00:14<06:35,  5.23it/s]
  8%|▊         | 183/2248 [00:14<04:07,  8.34it/s]
  8%|▊         | 187/2248 [00:15<04:22,  7.85it/s]
  8%|▊         | 190/2248 [00:15<03:31,  9.72it/s]
  9%|▊         | 195/2248 [00:15<03:40,  9.31it/s]
  9%|▉         | 197/2248 [00:15<03:20, 10.25it/s]
  9%|▉         | 202/2248 [00:16<03:35,  9.51it/s]
  9%|▉         | 204/2248 [00:16<03:19, 10.25it/s]
  9%|▉         | 206/2248 [00:17<04:34,  7.43it/s]
  9%|▉         | 208/2248 [00:17<05:40,  6.00it/s]
  9%|▉         | 209/2248 [00:18<07:15,  4.69it/s]
  9%|▉         | 210/2248 [00:18<09:04,  3.75it/s]
  9%|▉         | 211/2248 [00:19<10:36,  3.20it/s]
  9%|▉         | 212/2248 [00:19<11:16,  3.01it/s]
 10%|▉         | 214/2248 [00:19<07:43,  4.39it/s]
 10%|▉         | 220/2248 [00:19<03:17, 10.29it/s]
 10%|█         | 227/2248 [00:19<01:52, 18.01it/s]
 10%|█         | 233/2248 [00:20<01:24, 23.74it/s]
 11%|█         | 237/2248 [00:20<01:16, 26.18it/s]
 11%|█         | 245/2248 [00:20<00:55, 36.41it/s]
 11%|█         | 251/2248 [00:20<00:48, 40.97it/s]
 11%|█▏        | 258/2248 [00:20<00:42, 46.82it/s]
 12%|█▏        | 264/2248 [00:20<00:41, 47.99it/s]
 12%|█▏        | 270/2248 [00:21<01:29, 22.19it/s]
 12%|█▏        | 275/2248 [00:21<02:14, 14.62it/s]
 12%|█▏        | 279/2248 [00:22<02:00, 16.38it/s]
 13%|█▎        | 285/2248 [00:22<01:32, 21.29it/s]
 13%|█▎        | 290/2248 [00:22<02:07, 15.38it/s]
 13%|█▎        | 293/2248 [00:23<02:53, 11.27it/s]
 13%|█▎        | 296/2248 [00:23<03:40,  8.86it/s]
 13%|█▎        | 299/2248 [00:24<04:17,  7.58it/s]
 13%|█▎        | 302/2248 [00:24<03:30,  9.25it/s]
 14%|█▎        | 304/2248 [00:25<05:38,  5.75it/s]
 14%|█▎        | 306/2248 [00:25<04:56,  6.55it/s]
 14%|█▎        | 308/2248 [00:26<06:47,  4.76it/s]
 14%|█▎        | 309/2248 [00:26<07:42,  4.20it/s]
 14%|█▍        | 311/2248 [00:26<05:56,  5.43it/s]
 14%|█▍        | 313/2248 [00:27<06:35,  4.89it/s]
 14%|█▍        | 314/2248 [00:27<08:20,  3.87it/s]
 14%|█▍        | 315/2248 [00:28<10:08,  3.18it/s]
 14%|█▍        | 318/2248 [00:29<08:12,  3.92it/s]
 14%|█▍        | 320/2248 [00:29<08:22,  3.84it/s]
 14%|█▍        | 322/2248 [00:30<08:43,  3.68it/s]
 14%|█▍        | 323/2248 [00:30<09:30,  3.37it/s]
 14%|█▍        | 325/2248 [00:30<07:13,  4.44it/s]
 15%|█▍        | 327/2248 [00:31<06:17,  5.09it/s]
 15%|█▍        | 329/2248 [00:31<05:05,  6.28it/s]
 15%|█▍        | 335/2248 [00:31<02:30, 12.68it/s]
 15%|█▌        | 339/2248 [00:31<02:59, 10.61it/s]
 15%|█▌        | 341/2248 [00:31<02:45, 11.54it/s]
 15%|█▌        | 343/2248 [00:32<03:50,  8.26it/s]
 15%|█▌        | 345/2248 [00:32<03:25,  9.28it/s]
 15%|█▌        | 347/2248 [00:32<04:10,  7.59it/s]
 16%|█▌        | 349/2248 [00:33<05:21,  5.91it/s]
 16%|█▌        | 350/2248 [00:33<05:58,  5.29it/s]
 16%|█▌        | 352/2248 [00:33<04:42,  6.72it/s]
 16%|█▌        | 353/2248 [00:34<04:37,  6.84it/s]
 16%|█▌        | 355/2248 [00:34<03:35,  8.77it/s]
 16%|█▌        | 357/2248 [00:34<05:13,  6.03it/s]
 16%|█▌        | 360/2248 [00:34<03:30,  8.95it/s]
 16%|█▌        | 362/2248 [00:35<04:49,  6.51it/s]
 16%|█▌        | 364/2248 [00:35<05:58,  5.26it/s]
 16%|█▋        | 367/2248 [00:35<04:12,  7.46it/s]
 17%|█▋        | 371/2248 [00:36<04:07,  7.59it/s]
 17%|█▋        | 374/2248 [00:36<03:13,  9.66it/s]
 17%|█▋        | 379/2248 [00:36<02:53, 10.77it/s]
 17%|█▋        | 381/2248 [00:37<02:41, 11.54it/s]
 17%|█▋        | 385/2248 [00:37<03:10,  9.79it/s]
 17%|█▋        | 388/2248 [00:38<03:56,  7.87it/s]
 17%|█▋        | 391/2248 [00:38<03:12,  9.67it/s]
 17%|█▋        | 393/2248 [00:39<05:48,  5.32it/s]
 18%|█▊        | 395/2248 [00:40<08:03,  3.83it/s]
 18%|█▊        | 398/2248 [00:40<05:43,  5.39it/s]
 18%|█▊        | 404/2248 [00:40<03:11,  9.65it/s]
 18%|█▊        | 410/2248 [00:40<02:07, 14.36it/s]
 19%|█▊        | 416/2248 [00:40<01:33, 19.66it/s]
 19%|█▊        | 420/2248 [00:40<01:25, 21.40it/s]
 19%|█▉        | 424/2248 [00:41<01:17, 23.55it/s]
 19%|█▉        | 430/2248 [00:41<01:00, 29.87it/s]
 19%|█▉        | 436/2248 [00:41<01:40, 18.02it/s]
 20%|█▉        | 440/2248 [00:42<02:24, 12.52it/s]
 20%|█▉        | 444/2248 [00:42<02:47, 10.74it/s]
 20%|█▉        | 446/2248 [00:43<03:33,  8.44it/s]
 20%|█▉        | 449/2248 [00:43<02:59, 10.05it/s]
 20%|██        | 451/2248 [00:44<03:53,  7.69it/s]
 20%|██        | 454/2248 [00:44<03:04,  9.73it/s]
 20%|██        | 456/2248 [00:44<03:05,  9.67it/s]
 20%|██        | 458/2248 [00:44<03:38,  8.20it/s]
 20%|██        | 460/2248 [00:45<03:50,  7.77it/s]
 21%|██        | 463/2248 [00:45<02:51, 10.39it/s]
 21%|██        | 470/2248 [00:45<01:32, 19.14it/s]
 21%|██        | 474/2248 [00:45<01:55, 15.32it/s]
 21%|██        | 477/2248 [00:45<02:12, 13.34it/s]
 21%|██▏       | 480/2248 [00:46<02:16, 12.96it/s]
 21%|██▏       | 482/2248 [00:46<03:00,  9.80it/s]
 22%|██▏       | 484/2248 [00:46<02:46, 10.57it/s]
 22%|██▏       | 486/2248 [00:47<03:58,  7.39it/s]
 22%|██▏       | 488/2248 [00:48<06:31,  4.50it/s]
 22%|██▏       | 491/2248 [00:48<04:40,  6.26it/s]
 22%|██▏       | 493/2248 [00:48<05:30,  5.31it/s]
 22%|██▏       | 495/2248 [00:49<05:39,  5.17it/s]
 22%|██▏       | 497/2248 [00:49<04:38,  6.29it/s]
 22%|██▏       | 499/2248 [00:49<03:48,  7.64it/s]
 22%|██▏       | 501/2248 [00:49<04:03,  7.17it/s]
 22%|██▏       | 503/2248 [00:49<03:21,  8.68it/s]
 23%|██▎       | 508/2248 [00:50<01:56, 14.95it/s]
 23%|██▎       | 511/2248 [00:50<02:54,  9.93it/s]
 23%|██▎       | 514/2248 [00:51<03:39,  7.91it/s]
 23%|██▎       | 516/2248 [00:51<04:59,  5.79it/s]
 23%|██▎       | 518/2248 [00:52<06:25,  4.49it/s]
 23%|██▎       | 519/2248 [00:53<07:32,  3.82it/s]
 23%|██▎       | 522/2248 [00:53<05:02,  5.71it/s]
 24%|██▎       | 529/2248 [00:53<02:26, 11.74it/s]
 24%|██▍       | 535/2248 [00:53<01:39, 17.17it/s]
 24%|██▍       | 539/2248 [00:53<01:23, 20.35it/s]
 24%|██▍       | 545/2248 [00:53<01:04, 26.59it/s]
 24%|██▍       | 550/2248 [00:53<01:02, 27.07it/s]
 25%|██▍       | 556/2248 [00:53<00:54, 31.00it/s]
 25%|██▍       | 560/2248 [00:54<00:52, 32.29it/s]
 25%|██▌       | 564/2248 [00:54<00:55, 30.10it/s]
 25%|██▌       | 568/2248 [00:54<00:53, 31.36it/s]
 25%|██▌       | 572/2248 [00:55<02:44, 10.17it/s]
 26%|██▌       | 575/2248 [00:56<03:35,  7.75it/s]
 26%|██▌       | 577/2248 [00:56<03:36,  7.73it/s]
 26%|██▌       | 579/2248 [00:56<04:13,  6.59it/s]
 26%|██▌       | 581/2248 [00:57<04:15,  6.53it/s]
 26%|██▌       | 583/2248 [00:57<03:54,  7.10it/s]
 26%|██▌       | 586/2248 [00:57<03:20,  8.27it/s]
 26%|██▌       | 588/2248 [00:58<03:50,  7.20it/s]
 26%|██▌       | 590/2248 [00:58<03:17,  8.41it/s]
 26%|██▋       | 592/2248 [00:58<02:54,  9.50it/s]
 26%|██▋       | 594/2248 [00:58<02:33, 10.74it/s]
 27%|██▋       | 599/2248 [00:58<02:52,  9.55it/s]
 27%|██▋       | 601/2248 [00:59<02:37, 10.47it/s]
 27%|██▋       | 603/2248 [00:59<03:06,  8.81it/s]
 27%|██▋       | 605/2248 [01:00<04:19,  6.34it/s]
 27%|██▋       | 607/2248 [01:00<04:00,  6.82it/s]
 27%|██▋       | 608/2248 [01:00<04:52,  5.61it/s]
 27%|██▋       | 609/2248 [01:00<05:22,  5.07it/s]
 27%|██▋       | 610/2248 [01:01<05:19,  5.12it/s]
 27%|██▋       | 612/2248 [01:01<03:51,  7.07it/s]
 27%|██▋       | 617/2248 [01:01<01:58, 13.77it/s]
 28%|██▊       | 623/2248 [01:01<01:15, 21.57it/s]
 28%|██▊       | 630/2248 [01:01<00:52, 30.97it/s]
 28%|██▊       | 637/2248 [01:01<00:43, 37.42it/s]
 29%|██▊       | 643/2248 [01:01<00:38, 41.91it/s]
 29%|██▉       | 650/2248 [01:01<00:33, 47.15it/s]
 29%|██▉       | 656/2248 [01:03<02:01, 13.16it/s]
 29%|██▉       | 660/2248 [01:03<02:44,  9.67it/s]
 29%|██▉       | 663/2248 [01:04<03:33,  7.41it/s]
 30%|██▉       | 666/2248 [01:05<03:41,  7.13it/s]
 30%|██▉       | 668/2248 [01:05<03:18,  7.94it/s]
 30%|██▉       | 670/2248 [01:05<03:20,  7.88it/s]
 30%|██▉       | 672/2248 [01:05<02:56,  8.95it/s]
 30%|███       | 677/2248 [01:05<02:16, 11.50it/s]
 30%|███       | 680/2248 [01:06<01:55, 13.58it/s]
 30%|███       | 682/2248 [01:06<02:16, 11.51it/s]
 30%|███       | 685/2248 [01:06<01:52, 13.89it/s]
 31%|███       | 688/2248 [01:06<02:08, 12.18it/s]
 31%|███       | 691/2248 [01:06<01:46, 14.57it/s]
 31%|███       | 693/2248 [01:07<02:42,  9.58it/s]
 31%|███       | 698/2248 [01:07<02:22, 10.85it/s]
 31%|███       | 700/2248 [01:08<03:02,  8.47it/s]
 31%|███       | 702/2248 [01:08<03:53,  6.63it/s]
 31%|███▏      | 704/2248 [01:09<04:26,  5.79it/s]
 31%|███▏      | 706/2248 [01:09<03:42,  6.93it/s]
 32%|███▏      | 712/2248 [01:09<03:02,  8.43it/s]
 32%|███▏      | 714/2248 [01:09<02:40,  9.53it/s]
 32%|███▏      | 719/2248 [01:10<01:48, 14.14it/s]
 32%|███▏      | 724/2248 [01:10<01:19, 19.29it/s]
 32%|███▏      | 728/2248 [01:10<01:11, 21.35it/s]
 33%|███▎      | 731/2248 [01:10<01:06, 22.92it/s]
 33%|███▎      | 735/2248 [01:10<01:45, 14.30it/s]
 33%|███▎      | 738/2248 [01:11<02:51,  8.80it/s]
 33%|███▎      | 740/2248 [01:11<02:36,  9.65it/s]
 33%|███▎      | 742/2248 [01:12<03:13,  7.79it/s]
 33%|███▎      | 744/2248 [01:12<04:06,  6.11it/s]
 33%|███▎      | 746/2248 [01:12<03:31,  7.11it/s]
 33%|███▎      | 749/2248 [01:13<03:24,  7.34it/s]
 33%|███▎      | 752/2248 [01:13<03:43,  6.71it/s]
 34%|███▎      | 755/2248 [01:13<02:58,  8.36it/s]
 34%|███▎      | 758/2248 [01:14<02:19, 10.71it/s]
 34%|███▍      | 760/2248 [01:14<02:05, 11.88it/s]
 34%|███▍      | 763/2248 [01:14<02:26, 10.12it/s]
 34%|███▍      | 765/2248 [01:14<02:10, 11.39it/s]
 34%|███▍      | 767/2248 [01:14<02:22, 10.37it/s]
 34%|███▍      | 770/2248 [01:15<01:53, 13.04it/s]
 34%|███▍      | 772/2248 [01:15<02:33,  9.60it/s]
 34%|███▍      | 774/2248 [01:15<03:47,  6.49it/s]
 35%|███▍      | 776/2248 [01:16<04:27,  5.50it/s]
 35%|███▍      | 778/2248 [01:16<04:34,  5.36it/s]
 35%|███▍      | 780/2248 [01:17<03:39,  6.68it/s]
 35%|███▍      | 782/2248 [01:17<03:53,  6.27it/s]
 35%|███▍      | 783/2248 [01:17<04:21,  5.59it/s]
 35%|███▍      | 784/2248 [01:17<04:53,  4.99it/s]
 35%|███▍      | 786/2248 [01:18<03:45,  6.48it/s]
 35%|███▌      | 788/2248 [01:18<02:55,  8.32it/s]
 35%|███▌      | 790/2248 [01:18<03:23,  7.18it/s]
 35%|███▌      | 792/2248 [01:19<04:24,  5.51it/s]
 35%|███▌      | 794/2248 [01:19<03:30,  6.92it/s]
 35%|███▌      | 797/2248 [01:19<04:08,  5.84it/s]
 36%|███▌      | 800/2248 [01:19<02:57,  8.17it/s]
 36%|███▌      | 805/2248 [01:20<01:48, 13.36it/s]
 36%|███▌      | 808/2248 [01:20<02:37,  9.16it/s]
 36%|███▌      | 811/2248 [01:21<03:06,  7.73it/s]
 36%|███▌      | 813/2248 [01:22<04:36,  5.18it/s]
 36%|███▋      | 815/2248 [01:22<04:55,  4.84it/s]
 36%|███▋      | 816/2248 [01:23<06:02,  3.95it/s]
 36%|███▋      | 819/2248 [01:23<04:02,  5.90it/s]
 37%|███▋      | 825/2248 [01:23<02:07, 11.13it/s]
 37%|███▋      | 830/2248 [01:23<01:30, 15.72it/s]
 37%|███▋      | 834/2248 [01:23<01:15, 18.69it/s]
 37%|███▋      | 838/2248 [01:23<01:05, 21.67it/s]
 37%|███▋      | 842/2248 [01:23<01:12, 19.26it/s]
 38%|███▊      | 846/2248 [01:23<01:02, 22.37it/s]
 38%|███▊      | 850/2248 [01:24<00:56, 24.55it/s]
 38%|███▊      | 855/2248 [01:24<00:46, 29.74it/s]
 38%|███▊      | 859/2248 [01:24<00:47, 29.55it/s]
 38%|███▊      | 863/2248 [01:24<00:50, 27.53it/s]
 39%|███▊      | 867/2248 [01:25<01:35, 14.42it/s]
 39%|███▊      | 870/2248 [01:25<01:28, 15.64it/s]
 39%|███▉      | 874/2248 [01:25<01:57, 11.67it/s]
 39%|███▉      | 876/2248 [01:25<01:49, 12.53it/s]
 39%|███▉      | 878/2248 [01:26<02:46,  8.25it/s]
 39%|███▉      | 881/2248 [01:27<03:14,  7.04it/s]
 39%|███▉      | 884/2248 [01:27<02:32,  8.93it/s]
 40%|███▉      | 889/2248 [01:27<01:40, 13.56it/s]
 40%|███▉      | 892/2248 [01:27<02:29,  9.08it/s]
 40%|███▉      | 894/2248 [01:28<03:13,  6.98it/s]
 40%|███▉      | 896/2248 [01:29<03:55,  5.74it/s]
 40%|████      | 902/2248 [01:29<03:06,  7.22it/s]
 40%|████      | 904/2248 [01:30<03:47,  5.90it/s]
 40%|████      | 906/2248 [01:30<04:20,  5.16it/s]
 40%|████      | 907/2248 [01:31<05:14,  4.27it/s]
 40%|████      | 908/2248 [01:31<06:09,  3.63it/s]
 40%|████      | 910/2248 [01:32<06:24,  3.48it/s]
 41%|████      | 911/2248 [01:32<07:20,  3.04it/s]
 41%|████      | 912/2248 [01:33<07:59,  2.79it/s]
 41%|████      | 913/2248 [01:33<07:15,  3.07it/s]
 41%|████      | 915/2248 [01:33<04:57,  4.48it/s]
 41%|████      | 917/2248 [01:34<04:50,  4.58it/s]
 41%|████      | 919/2248 [01:34<03:36,  6.12it/s]
 41%|████      | 920/2248 [01:34<03:44,  5.92it/s]
 41%|████      | 922/2248 [01:34<02:59,  7.39it/s]
 41%|████      | 924/2248 [01:34<03:17,  6.70it/s]
 41%|████      | 926/2248 [01:35<02:47,  7.90it/s]
 41%|████      | 927/2248 [01:35<03:48,  5.79it/s]
 41%|████▏     | 929/2248 [01:35<03:32,  6.22it/s]
 41%|████▏     | 932/2248 [01:35<02:23,  9.15it/s]
 42%|████▏     | 934/2248 [01:36<02:52,  7.61it/s]
 42%|████▏     | 937/2248 [01:36<02:05, 10.47it/s]
 42%|████▏     | 942/2248 [01:36<01:21, 16.10it/s]
 42%|████▏     | 948/2248 [01:36<00:54, 23.74it/s]
 42%|████▏     | 952/2248 [01:37<01:35, 13.63it/s]
 42%|████▏     | 955/2248 [01:37<01:34, 13.69it/s]
 43%|████▎     | 958/2248 [01:38<02:59,  7.20it/s]
 43%|████▎     | 960/2248 [01:38<03:22,  6.35it/s]
 43%|████▎     | 962/2248 [01:39<03:39,  5.85it/s]
 43%|████▎     | 964/2248 [01:39<03:16,  6.53it/s]
 43%|████▎     | 966/2248 [01:39<03:06,  6.86it/s]
 43%|████▎     | 968/2248 [01:39<02:38,  8.07it/s]
 43%|████▎     | 970/2248 [01:40<02:54,  7.33it/s]
 43%|████▎     | 972/2248 [01:40<02:30,  8.50it/s]
 43%|████▎     | 974/2248 [01:40<03:18,  6.41it/s]
 43%|████▎     | 975/2248 [01:40<03:07,  6.80it/s]
 43%|████▎     | 976/2248 [01:41<03:31,  6.01it/s]
 44%|████▎     | 978/2248 [01:41<03:30,  6.03it/s]
 44%|████▎     | 981/2248 [01:41<02:53,  7.31it/s]
 44%|████▎     | 983/2248 [01:41<02:26,  8.64it/s]
 44%|████▍     | 985/2248 [01:42<02:49,  7.44it/s]
 44%|████▍     | 987/2248 [01:42<03:45,  5.59it/s]
 44%|████▍     | 990/2248 [01:43<02:41,  7.79it/s]
 44%|████▍     | 995/2248 [01:43<01:36, 13.01it/s]
 44%|████▍     | 999/2248 [01:43<02:03, 10.07it/s]
 45%|████▍     | 1002/2248 [01:44<02:36,  7.98it/s]
 45%|████▍     | 1004/2248 [01:45<04:12,  4.93it/s]
 45%|████▍     | 1006/2248 [01:45<04:41,  4.40it/s]
 45%|████▍     | 1007/2248 [01:46<05:32,  3.73it/s]
 45%|████▍     | 1008/2248 [01:46<06:26,  3.21it/s]
 45%|████▍     | 1009/2248 [01:47<07:11,  2.87it/s]
 45%|████▌     | 1012/2248 [01:47<04:20,  4.75it/s]
 45%|████▌     | 1017/2248 [01:47<02:19,  8.79it/s]
 46%|████▌     | 1023/2248 [01:47<01:24, 14.55it/s]
 46%|████▌     | 1027/2248 [01:48<01:15, 16.20it/s]
 46%|████▌     | 1033/2248 [01:48<00:53, 22.69it/s]
 46%|████▌     | 1039/2248 [01:48<00:41, 29.09it/s]
 46%|████▋     | 1044/2248 [01:48<00:40, 29.75it/s]
 47%|████▋     | 1051/2248 [01:48<00:32, 37.37it/s]
 47%|████▋     | 1056/2248 [01:48<00:49, 24.27it/s]
 47%|████▋     | 1060/2248 [01:49<01:49, 10.86it/s]
 47%|████▋     | 1063/2248 [01:50<02:12,  8.94it/s]
 47%|████▋     | 1066/2248 [01:50<02:31,  7.82it/s]
 48%|████▊     | 1069/2248 [01:51<02:03,  9.55it/s]
 48%|████▊     | 1072/2248 [01:51<02:30,  7.83it/s]
 48%|████▊     | 1076/2248 [01:51<02:03,  9.46it/s]
 48%|████▊     | 1079/2248 [01:52<01:47, 10.91it/s]
 48%|████▊     | 1081/2248 [01:52<01:37, 11.97it/s]
 48%|████▊     | 1083/2248 [01:52<02:01,  9.57it/s]
 48%|████▊     | 1085/2248 [01:52<01:47, 10.81it/s]
 48%|████▊     | 1087/2248 [01:52<02:01,  9.55it/s]
 48%|████▊     | 1089/2248 [01:53<02:19,  8.33it/s]
 49%|████▊     | 1091/2248 [01:53<02:16,  8.45it/s]
 49%|████▊     | 1093/2248 [01:54<03:10,  6.07it/s]
 49%|████▊     | 1094/2248 [01:54<03:42,  5.19it/s]
 49%|████▉     | 1096/2248 [01:54<02:53,  6.63it/s]
 49%|████▉     | 1099/2248 [01:54<01:59,  9.61it/s]
 49%|████▉     | 1104/2248 [01:54<01:13, 15.66it/s]
 49%|████▉     | 1108/2248 [01:54<00:58, 19.58it/s]
 50%|████▉     | 1115/2248 [01:54<00:38, 29.25it/s]
 50%|████▉     | 1123/2248 [01:55<00:28, 40.00it/s]
 50%|█████     | 1130/2248 [01:55<00:24, 46.20it/s]
 51%|█████     | 1136/2248 [01:55<00:22, 49.08it/s]
 51%|█████     | 1143/2248 [01:55<00:47, 23.21it/s]
 51%|█████     | 1148/2248 [01:56<01:01, 17.79it/s]
 51%|█████     | 1152/2248 [01:56<01:24, 12.98it/s]
 51%|█████▏    | 1155/2248 [01:57<01:55,  9.48it/s]
 51%|█████▏    | 1157/2248 [01:58<02:33,  7.09it/s]
 52%|█████▏    | 1159/2248 [01:58<02:18,  7.85it/s]
 52%|█████▏    | 1161/2248 [01:58<02:53,  6.27it/s]
 52%|█████▏    | 1164/2248 [01:59<03:04,  5.88it/s]
 52%|█████▏    | 1166/2248 [01:59<02:37,  6.89it/s]
 52%|█████▏    | 1170/2248 [02:00<02:30,  7.18it/s]
 52%|█████▏    | 1172/2248 [02:00<03:02,  5.91it/s]
 52%|█████▏    | 1174/2248 [02:00<02:33,  7.01it/s]
 52%|█████▏    | 1176/2248 [02:01<03:02,  5.88it/s]
 52%|█████▏    | 1179/2248 [02:01<03:10,  5.60it/s]
 53%|█████▎    | 1182/2248 [02:02<03:14,  5.48it/s]
 53%|█████▎    | 1183/2248 [02:03<03:58,  4.46it/s]
 53%|█████▎    | 1185/2248 [02:03<03:11,  5.55it/s]
 53%|█████▎    | 1187/2248 [02:03<03:36,  4.89it/s]
 53%|█████▎    | 1188/2248 [02:04<04:32,  3.90it/s]
 53%|█████▎    | 1189/2248 [02:04<05:26,  3.25it/s]
 53%|█████▎    | 1192/2248 [02:04<03:17,  5.35it/s]
 53%|█████▎    | 1195/2248 [02:05<03:13,  5.43it/s]
 53%|█████▎    | 1197/2248 [02:05<02:42,  6.46it/s]
 53%|█████▎    | 1200/2248 [02:05<01:59,  8.78it/s]
 53%|█████▎    | 1202/2248 [02:06<02:20,  7.43it/s]
 54%|█████▎    | 1204/2248 [02:06<01:58,  8.84it/s]
 54%|█████▎    | 1206/2248 [02:06<02:18,  7.50it/s]
 54%|█████▎    | 1208/2248 [02:06<01:57,  8.83it/s]
 54%|█████▍    | 1213/2248 [02:06<01:09, 14.99it/s]
 54%|█████▍    | 1220/2248 [02:06<00:42, 24.21it/s]
 55%|█████▍    | 1226/2248 [02:07<00:47, 21.51it/s]
 55%|█████▍    | 1229/2248 [02:07<00:50, 20.38it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 310.17it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 7], [np.int64(2), False, 1], [np.int64(3), False, 10], [np.int64(4), False, 11], [np.int64(5), False, 13], [np.int64(6), False, 7], [np.int64(8), False, 0], [np.int64(9), False, 0], [np.int64(10), False, 13], [np.int64(12), False, 7]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7474, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [03:45<3:33:36, 64.41s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [03:45<2:29:08, 45.19s/it]

tensor(12.5813, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7644, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8266, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [03:46<1:12:40, 22.25s/it]

tensor(12.5679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8908, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9676, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [03:46<24:49,  7.72s/it]

tensor(12.5742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0265, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0861, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [03:46<12:14,  3.85s/it]

tensor(12.5883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1484, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2155, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [03:46<08:38,  2.73s/it]

tensor(12.6016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2837, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6082, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3614, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [03:47<04:23,  1.40s/it]

tensor(12.6141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4164, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4713, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [03:47<01:43,  1.79it/s]

tensor(12.6179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5561, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [03:47<01:19,  2.33it/s]

tensor(12.6074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5922, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6179, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [03:47<00:49,  3.69it/s]

tensor(12.5845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6389, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6503, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [03:48<00:30,  5.80it/s]

tensor(12.5512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6924, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [03:48<00:28,  6.31it/s]

tensor(12.5173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7216, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7436, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [03:48<00:23,  7.42it/s]

tensor(12.4869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7732, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [03:48<00:22,  7.58it/s]

tensor(12.4601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7896, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4487, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8090, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [03:49<00:21,  7.92it/s]

tensor(12.4389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8382, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8613, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 130/300 [03:49<00:21,  8.03it/s]

tensor(12.4217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8868, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9041, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [03:49<00:20,  8.08it/s]

tensor(12.4074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9260, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9476, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [03:49<00:20,  8.09it/s]

tensor(12.3935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9718, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9906, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [03:50<00:19,  8.20it/s]

tensor(12.3791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0125, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3719, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0208, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [03:50<00:19,  8.16it/s]

tensor(12.3648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0404, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0530, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [03:50<00:19,  8.09it/s]

tensor(12.3514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0716, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0883, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [03:50<00:19,  8.10it/s]

tensor(12.3401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1063, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1218, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [03:51<00:19,  7.82it/s]

tensor(12.3296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1356, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3237, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1428, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [03:51<00:19,  7.90it/s]

tensor(12.3173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1588, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1785, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [03:51<00:18,  8.08it/s]

tensor(12.3048, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1996, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2169, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [03:51<00:18,  8.12it/s]

tensor(12.2934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2345, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([239, 360, 136, 239, 191, 136,  65,  85,  76, 121,  76, 253, 111, 160])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:56, 12.71it/s]
  0%|          | 6/2248 [00:00<01:36, 23.24it/s]
  0%|          | 11/2248 [00:00<01:07, 33.06it/s]
  1%|          | 16/2248 [00:00<00:57, 38.73it/s]
  1%|          | 21/2248 [00:00<00:56, 39.70it/s]
  1%|          | 26/2248 [00:00<00:52, 42.58it/s]
  1%|▏         | 32/2248 [00:00<00:47, 46.21it/s]
  2%|▏         | 37/2248 [00:01<01:00, 36.53it/s]
  2%|▏         | 42/2248 [00:01<00:57, 38.53it/s]
  2%|▏         | 47/2248 [00:01<00:53, 41.35it/s]
  2%|▏         | 52/2248 [00:01<00:51, 42.39it/s]
  3%|▎         | 58/2248 [00:01<00:47, 45.88it/s]
  3%|▎         | 65/2248 [00:01<00:48, 45.10it/s]
  3%|▎         | 70/2248 [00:01<00:55, 38.97it/s]
  3%|▎         | 75/2248 [00:02<02:00, 18.08it/s]
  4%|▎         | 79/2248 [00:02<02:07, 17.02it/s]
  4%|▎         | 82/2248 [00:02<02:06, 17.11it/s]
  4%|▍         | 86/2248 [00:03<01:47, 20.17it/s]
  4%|▍         | 89/2248 [00:03<01:39, 21.76it/s]
  4%|▍         | 93/2248 [00:03<01:25, 25.19it/s]
  4%|▍         | 97/2248 [00:03<01:44, 20.51it/s]
  4%|▍         | 100/2248 [00:03<01:46, 20.24it/s]
  5%|▍         | 103/2248 [00:03<01:37, 22.03it/s]
  5%|▍         | 107/2248 [00:03<01:22, 25.86it/s]
  5%|▍         | 111/2248 [00:03<01:15, 28.15it/s]
  5%|▌         | 115/2248 [00:04<02:03, 17.33it/s]
  5%|▌         | 118/2248 [00:04<02:23, 14.81it/s]
  5%|▌         | 121/2248 [00:04<02:43, 13.04it/s]
  6%|▌         | 125/2248 [00:05<02:35, 13.66it/s]
  6%|▌         | 127/2248 [00:05<03:32, 10.00it/s]
  6%|▌         | 129/2248 [00:05<03:47,  9.31it/s]
  6%|▌         | 132/2248 [00:06<02:59, 11.76it/s]
  6%|▌         | 134/2248 [00:06<03:27, 10.17it/s]
  6%|▌         | 136/2248 [00:06<03:41,  9.55it/s]
  6%|▌         | 138/2248 [00:06<04:08,  8.50it/s]
  6%|▌         | 140/2248 [00:07<03:38,  9.66it/s]
  6%|▋         | 145/2248 [00:07<02:45, 12.72it/s]
  7%|▋         | 147/2248 [00:07<02:33, 13.69it/s]
  7%|▋         | 149/2248 [00:07<02:53, 12.13it/s]
  7%|▋         | 151/2248 [00:07<03:19, 10.51it/s]
  7%|▋         | 153/2248 [00:08<03:10, 10.99it/s]
  7%|▋         | 156/2248 [00:08<03:11, 10.94it/s]
  7%|▋         | 158/2248 [00:08<04:16,  8.15it/s]
  7%|▋         | 159/2248 [00:08<04:55,  7.08it/s]
  7%|▋         | 160/2248 [00:09<05:32,  6.27it/s]
  7%|▋         | 162/2248 [00:09<05:21,  6.48it/s]
  7%|▋         | 163/2248 [00:09<05:01,  6.92it/s]
  7%|▋         | 165/2248 [00:09<04:35,  7.57it/s]
  7%|▋         | 167/2248 [00:09<03:42,  9.36it/s]
  8%|▊         | 169/2248 [00:10<03:37,  9.56it/s]
  8%|▊         | 172/2248 [00:10<02:47, 12.37it/s]
  8%|▊         | 174/2248 [00:10<03:34,  9.65it/s]
  8%|▊         | 176/2248 [00:10<04:11,  8.25it/s]
  8%|▊         | 178/2248 [00:11<04:02,  8.55it/s]
  8%|▊         | 180/2248 [00:11<03:29,  9.85it/s]
  8%|▊         | 183/2248 [00:11<03:09, 10.88it/s]
  8%|▊         | 185/2248 [00:11<02:47, 12.32it/s]
  8%|▊         | 187/2248 [00:11<02:42, 12.70it/s]
  8%|▊         | 189/2248 [00:11<02:48, 12.22it/s]
  8%|▊         | 191/2248 [00:12<02:51, 12.00it/s]
  9%|▊         | 195/2248 [00:12<02:37, 12.99it/s]
  9%|▉         | 197/2248 [00:12<02:30, 13.63it/s]
  9%|▉         | 202/2248 [00:12<02:12, 15.45it/s]
  9%|▉         | 204/2248 [00:12<02:12, 15.44it/s]
  9%|▉         | 206/2248 [00:13<02:42, 12.55it/s]
  9%|▉         | 208/2248 [00:13<02:38, 12.86it/s]
  9%|▉         | 210/2248 [00:13<03:04, 11.03it/s]
  9%|▉         | 212/2248 [00:13<03:26,  9.88it/s]
 10%|▉         | 214/2248 [00:14<03:12, 10.55it/s]
 10%|▉         | 217/2248 [00:14<02:29, 13.60it/s]
 10%|▉         | 222/2248 [00:14<01:41, 19.88it/s]
 10%|█         | 228/2248 [00:14<01:13, 27.55it/s]
 10%|█         | 232/2248 [00:14<01:06, 30.15it/s]
 11%|█         | 238/2248 [00:14<00:56, 35.37it/s]
 11%|█         | 242/2248 [00:14<00:55, 36.03it/s]
 11%|█         | 249/2248 [00:14<01:04, 31.09it/s]
 11%|█▏        | 253/2248 [00:15<01:04, 30.72it/s]
 12%|█▏        | 260/2248 [00:15<00:51, 38.81it/s]
 12%|█▏        | 265/2248 [00:15<01:19, 24.85it/s]
 12%|█▏        | 269/2248 [00:15<01:34, 20.99it/s]
 12%|█▏        | 272/2248 [00:16<01:52, 17.56it/s]
 12%|█▏        | 275/2248 [00:16<02:18, 14.24it/s]
 12%|█▏        | 277/2248 [00:16<02:42, 12.12it/s]
 12%|█▏        | 280/2248 [00:17<02:46, 11.79it/s]
 13%|█▎        | 282/2248 [00:17<03:00, 10.88it/s]
 13%|█▎        | 284/2248 [00:17<03:09, 10.39it/s]
 13%|█▎        | 286/2248 [00:17<03:04, 10.64it/s]
 13%|█▎        | 288/2248 [00:18<03:47,  8.63it/s]
 13%|█▎        | 289/2248 [00:18<03:44,  8.71it/s]
 13%|█▎        | 290/2248 [00:18<04:40,  6.99it/s]
 13%|█▎        | 291/2248 [00:18<05:07,  6.36it/s]
 13%|█▎        | 292/2248 [00:18<05:27,  5.98it/s]
 13%|█▎        | 294/2248 [00:18<04:18,  7.55it/s]
 13%|█▎        | 295/2248 [00:19<04:19,  7.51it/s]
 13%|█▎        | 296/2248 [00:19<04:18,  7.56it/s]
 13%|█▎        | 298/2248 [00:19<03:25,  9.51it/s]
 13%|█▎        | 300/2248 [00:19<03:09, 10.27it/s]
 13%|█▎        | 302/2248 [00:19<02:56, 11.00it/s]
 14%|█▎        | 304/2248 [00:20<04:28,  7.24it/s]
 14%|█▎        | 305/2248 [00:20<04:25,  7.33it/s]
 14%|█▎        | 306/2248 [00:20<04:25,  7.31it/s]
 14%|█▎        | 307/2248 [00:20<04:59,  6.48it/s]
 14%|█▎        | 308/2248 [00:20<04:36,  7.01it/s]
 14%|█▎        | 309/2248 [00:20<04:16,  7.55it/s]
 14%|█▍        | 310/2248 [00:20<04:04,  7.92it/s]
 14%|█▍        | 312/2248 [00:21<03:05, 10.45it/s]
 14%|█▍        | 314/2248 [00:21<03:57,  8.16it/s]
 14%|█▍        | 315/2248 [00:21<04:27,  7.21it/s]
 14%|█▍        | 317/2248 [00:21<03:41,  8.70it/s]
 14%|█▍        | 318/2248 [00:21<04:18,  7.46it/s]
 14%|█▍        | 319/2248 [00:22<04:03,  7.93it/s]
 14%|█▍        | 320/2248 [00:22<04:21,  7.37it/s]
 14%|█▍        | 322/2248 [00:22<04:15,  7.53it/s]
 14%|█▍        | 323/2248 [00:22<04:34,  7.01it/s]
 14%|█▍        | 325/2248 [00:22<04:18,  7.45it/s]
 15%|█▍        | 327/2248 [00:23<03:19,  9.61it/s]
 15%|█▍        | 329/2248 [00:23<03:08, 10.20it/s]
 15%|█▍        | 331/2248 [00:23<02:59, 10.66it/s]
 15%|█▍        | 333/2248 [00:23<03:26,  9.25it/s]
 15%|█▍        | 335/2248 [00:23<02:56, 10.86it/s]
 15%|█▍        | 337/2248 [00:23<02:36, 12.24it/s]
 15%|█▌        | 339/2248 [00:24<02:54, 10.94it/s]
 15%|█▌        | 341/2248 [00:24<03:20,  9.50it/s]
 15%|█▌        | 343/2248 [00:24<03:39,  8.67it/s]
 15%|█▌        | 344/2248 [00:24<03:38,  8.71it/s]
 15%|█▌        | 346/2248 [00:24<03:03, 10.35it/s]
 15%|█▌        | 348/2248 [00:25<03:41,  8.58it/s]
 16%|█▌        | 349/2248 [00:25<03:55,  8.06it/s]
 16%|█▌        | 350/2248 [00:25<04:30,  7.02it/s]
 16%|█▌        | 352/2248 [00:25<03:36,  8.75it/s]
 16%|█▌        | 354/2248 [00:25<03:36,  8.73it/s]
 16%|█▌        | 355/2248 [00:26<04:14,  7.42it/s]
 16%|█▌        | 356/2248 [00:26<04:55,  6.41it/s]
 16%|█▌        | 358/2248 [00:26<03:46,  8.33it/s]
 16%|█▌        | 362/2248 [00:26<02:49, 11.11it/s]
 16%|█▌        | 364/2248 [00:26<03:04, 10.22it/s]
 16%|█▋        | 367/2248 [00:27<02:29, 12.61it/s]
 16%|█▋        | 370/2248 [00:27<02:08, 14.65it/s]
 17%|█▋        | 372/2248 [00:27<02:42, 11.53it/s]
 17%|█▋        | 374/2248 [00:27<02:45, 11.31it/s]
 17%|█▋        | 377/2248 [00:28<02:48, 11.08it/s]
 17%|█▋        | 379/2248 [00:28<02:37, 11.87it/s]
 17%|█▋        | 384/2248 [00:28<01:44, 17.92it/s]
 17%|█▋        | 387/2248 [00:28<01:36, 19.37it/s]
 17%|█▋        | 390/2248 [00:29<03:04, 10.04it/s]
 17%|█▋        | 392/2248 [00:29<03:16,  9.43it/s]
 18%|█▊        | 394/2248 [00:29<03:49,  8.09it/s]
 18%|█▊        | 396/2248 [00:29<03:27,  8.94it/s]
 18%|█▊        | 399/2248 [00:29<02:35, 11.85it/s]
 18%|█▊        | 405/2248 [00:30<01:34, 19.45it/s]
 18%|█▊        | 410/2248 [00:30<01:13, 25.13it/s]
 19%|█▊        | 416/2248 [00:30<00:57, 32.04it/s]
 19%|█▉        | 422/2248 [00:30<00:47, 38.27it/s]
 19%|█▉        | 427/2248 [00:30<00:47, 38.48it/s]
 19%|█▉        | 433/2248 [00:30<00:43, 41.37it/s]
 19%|█▉        | 438/2248 [00:30<00:56, 32.29it/s]
 20%|█▉        | 442/2248 [00:31<01:25, 21.19it/s]
 20%|█▉        | 445/2248 [00:31<01:42, 17.51it/s]
 20%|█▉        | 448/2248 [00:31<01:46, 16.89it/s]
 20%|██        | 451/2248 [00:31<01:39, 18.00it/s]
 20%|██        | 454/2248 [00:31<01:31, 19.62it/s]
 20%|██        | 457/2248 [00:32<02:20, 12.77it/s]
 20%|██        | 459/2248 [00:32<02:16, 13.15it/s]
 21%|██        | 461/2248 [00:32<02:40, 11.12it/s]
 21%|██        | 463/2248 [00:33<02:49, 10.54it/s]
 21%|██        | 465/2248 [00:33<02:30, 11.85it/s]
 21%|██        | 468/2248 [00:33<01:58, 15.07it/s]
 21%|██        | 471/2248 [00:33<01:48, 16.30it/s]
 21%|██        | 473/2248 [00:33<02:04, 14.24it/s]
 21%|██        | 475/2248 [00:33<02:05, 14.17it/s]
 21%|██        | 477/2248 [00:34<02:50, 10.37it/s]
 21%|██▏       | 479/2248 [00:34<02:39, 11.09it/s]
 21%|██▏       | 481/2248 [00:34<02:51, 10.30it/s]
 21%|██▏       | 483/2248 [00:34<03:28,  8.46it/s]
 22%|██▏       | 485/2248 [00:34<02:53, 10.15it/s]
 22%|██▏       | 487/2248 [00:35<04:04,  7.22it/s]
 22%|██▏       | 489/2248 [00:35<03:48,  7.69it/s]
 22%|██▏       | 491/2248 [00:35<03:12,  9.14it/s]
 22%|██▏       | 494/2248 [00:35<02:20, 12.51it/s]
 22%|██▏       | 496/2248 [00:36<02:59,  9.75it/s]
 22%|██▏       | 499/2248 [00:36<02:58,  9.81it/s]
 22%|██▏       | 501/2248 [00:36<03:16,  8.88it/s]
 22%|██▏       | 505/2248 [00:36<02:13, 13.09it/s]
 23%|██▎       | 507/2248 [00:36<02:05, 13.84it/s]
 23%|██▎       | 509/2248 [00:37<02:28, 11.73it/s]
 23%|██▎       | 511/2248 [00:37<02:16, 12.72it/s]
 23%|██▎       | 513/2248 [00:37<02:42, 10.67it/s]
 23%|██▎       | 515/2248 [00:37<03:33,  8.11it/s]
 23%|██▎       | 517/2248 [00:38<03:02,  9.50it/s]
 23%|██▎       | 519/2248 [00:38<03:08,  9.18it/s]
 23%|██▎       | 521/2248 [00:38<02:51, 10.06it/s]
 23%|██▎       | 527/2248 [00:38<01:34, 18.27it/s]
 24%|██▎       | 530/2248 [00:38<01:28, 19.52it/s]
 24%|██▍       | 535/2248 [00:38<01:08, 25.03it/s]
 24%|██▍       | 539/2248 [00:38<01:01, 27.92it/s]
 24%|██▍       | 546/2248 [00:39<00:46, 36.39it/s]
 25%|██▍       | 551/2248 [00:39<00:44, 37.84it/s]
 25%|██▍       | 556/2248 [00:39<00:44, 38.16it/s]
 25%|██▍       | 561/2248 [00:39<00:42, 39.24it/s]
 25%|██▌       | 566/2248 [00:39<00:40, 41.14it/s]
 25%|██▌       | 571/2248 [00:39<00:39, 42.44it/s]
 26%|██▌       | 576/2248 [00:40<01:42, 16.28it/s]
 26%|██▌       | 580/2248 [00:40<02:14, 12.39it/s]
 26%|██▌       | 583/2248 [00:41<02:22, 11.65it/s]
 26%|██▌       | 586/2248 [00:41<02:24, 11.54it/s]
 26%|██▌       | 588/2248 [00:41<02:27, 11.26it/s]
 26%|██▌       | 590/2248 [00:41<02:23, 11.53it/s]
 26%|██▋       | 592/2248 [00:42<02:39, 10.37it/s]
 26%|██▋       | 594/2248 [00:42<02:27, 11.18it/s]
 27%|██▋       | 596/2248 [00:42<02:11, 12.57it/s]
 27%|██▋       | 599/2248 [00:42<02:08, 12.84it/s]
 27%|██▋       | 601/2248 [00:42<02:19, 11.80it/s]
 27%|██▋       | 603/2248 [00:42<02:22, 11.54it/s]
 27%|██▋       | 605/2248 [00:43<03:30,  7.79it/s]
 27%|██▋       | 607/2248 [00:43<03:12,  8.54it/s]
 27%|██▋       | 609/2248 [00:43<03:06,  8.78it/s]
 27%|██▋       | 611/2248 [00:44<03:54,  6.97it/s]
 27%|██▋       | 613/2248 [00:44<03:10,  8.58it/s]
 27%|██▋       | 618/2248 [00:44<01:49, 14.86it/s]
 28%|██▊       | 622/2248 [00:44<01:28, 18.48it/s]
 28%|██▊       | 626/2248 [00:44<01:11, 22.54it/s]
 28%|██▊       | 632/2248 [00:44<00:54, 29.86it/s]
 28%|██▊       | 637/2248 [00:44<00:46, 34.38it/s]
 29%|██▊       | 642/2248 [00:45<00:59, 27.05it/s]
 29%|██▉       | 647/2248 [00:45<00:52, 30.75it/s]
 29%|██▉       | 651/2248 [00:45<01:30, 17.72it/s]
 29%|██▉       | 654/2248 [00:46<02:10, 12.23it/s]
 29%|██▉       | 658/2248 [00:46<02:05, 12.64it/s]
 29%|██▉       | 660/2248 [00:46<02:20, 11.28it/s]
 29%|██▉       | 662/2248 [00:47<02:35, 10.18it/s]
 30%|██▉       | 664/2248 [00:47<02:45,  9.58it/s]
 30%|██▉       | 666/2248 [00:47<02:59,  8.82it/s]
 30%|██▉       | 670/2248 [00:47<02:32, 10.33it/s]
 30%|██▉       | 672/2248 [00:48<02:17, 11.48it/s]
 30%|███       | 677/2248 [00:48<01:53, 13.89it/s]
 30%|███       | 679/2248 [00:48<02:07, 12.32it/s]
 30%|███       | 682/2248 [00:48<02:10, 11.99it/s]
 30%|███       | 684/2248 [00:49<02:10, 12.03it/s]
 31%|███       | 686/2248 [00:49<02:05, 12.48it/s]
 31%|███       | 688/2248 [00:49<02:25, 10.69it/s]
 31%|███       | 690/2248 [00:49<02:12, 11.79it/s]
 31%|███       | 692/2248 [00:49<02:53,  8.99it/s]
 31%|███       | 694/2248 [00:50<02:33, 10.14it/s]
 31%|███       | 696/2248 [00:50<02:39,  9.71it/s]
 31%|███       | 699/2248 [00:50<02:46,  9.29it/s]
 31%|███       | 701/2248 [00:50<02:36,  9.89it/s]
 31%|███▏      | 703/2248 [00:51<02:52,  8.93it/s]
 31%|███▏      | 704/2248 [00:51<03:31,  7.29it/s]
 31%|███▏      | 706/2248 [00:51<02:56,  8.73it/s]
 32%|███▏      | 709/2248 [00:51<02:26, 10.52it/s]
 32%|███▏      | 712/2248 [00:51<01:59, 12.86it/s]
 32%|███▏      | 714/2248 [00:51<01:55, 13.29it/s]
 32%|███▏      | 717/2248 [00:52<01:42, 14.97it/s]
 32%|███▏      | 722/2248 [00:52<01:10, 21.70it/s]
 32%|███▏      | 727/2248 [00:52<01:20, 18.83it/s]
 32%|███▏      | 730/2248 [00:52<01:45, 14.34it/s]
 33%|███▎      | 732/2248 [00:53<02:02, 12.37it/s]
 33%|███▎      | 734/2248 [00:53<02:14, 11.25it/s]
 33%|███▎      | 736/2248 [00:53<02:56,  8.56it/s]
 33%|███▎      | 738/2248 [00:54<02:59,  8.40it/s]
 33%|███▎      | 740/2248 [00:54<02:43,  9.25it/s]
 33%|███▎      | 742/2248 [00:54<02:39,  9.42it/s]
 33%|███▎      | 744/2248 [00:54<03:26,  7.29it/s]
 33%|███▎      | 746/2248 [00:54<03:03,  8.21it/s]
 33%|███▎      | 748/2248 [00:55<02:39,  9.38it/s]
 33%|███▎      | 750/2248 [00:55<02:17, 10.91it/s]
 33%|███▎      | 752/2248 [00:55<02:02, 12.19it/s]
 34%|███▎      | 754/2248 [00:55<02:27, 10.15it/s]
 34%|███▎      | 756/2248 [00:55<02:07, 11.70it/s]
 34%|███▍      | 759/2248 [00:55<01:39, 14.95it/s]
 34%|███▍      | 762/2248 [00:56<01:29, 16.69it/s]
 34%|███▍      | 764/2248 [00:56<01:40, 14.81it/s]
 34%|███▍      | 766/2248 [00:56<01:33, 15.86it/s]
 34%|███▍      | 768/2248 [00:56<01:36, 15.35it/s]
 34%|███▍      | 771/2248 [00:56<01:26, 17.10it/s]
 34%|███▍      | 773/2248 [00:57<02:31,  9.72it/s]
 34%|███▍      | 775/2248 [00:57<03:09,  7.76it/s]
 35%|███▍      | 777/2248 [00:57<03:12,  7.63it/s]
 35%|███▍      | 779/2248 [00:58<03:21,  7.29it/s]
 35%|███▍      | 782/2248 [00:58<02:47,  8.77it/s]
 35%|███▍      | 784/2248 [00:58<02:40,  9.12it/s]
 35%|███▍      | 786/2248 [00:58<02:22, 10.23it/s]
 35%|███▌      | 788/2248 [00:58<02:14, 10.88it/s]
 35%|███▌      | 790/2248 [00:59<02:57,  8.20it/s]
 35%|███▌      | 792/2248 [00:59<03:14,  7.50it/s]
 35%|███▌      | 794/2248 [00:59<02:49,  8.55it/s]
 35%|███▌      | 797/2248 [00:59<02:27,  9.85it/s]
 36%|███▌      | 800/2248 [00:59<01:55, 12.58it/s]
 36%|███▌      | 805/2248 [01:00<01:21, 17.78it/s]
 36%|███▌      | 808/2248 [01:00<01:52, 12.80it/s]
 36%|███▌      | 811/2248 [01:00<01:47, 13.42it/s]
 36%|███▌      | 813/2248 [01:00<01:52, 12.80it/s]
 36%|███▋      | 815/2248 [01:01<02:36,  9.14it/s]
 36%|███▋      | 817/2248 [01:01<02:32,  9.37it/s]
 36%|███▋      | 819/2248 [01:01<02:24,  9.88it/s]
 37%|███▋      | 821/2248 [01:01<02:14, 10.60it/s]
 37%|███▋      | 827/2248 [01:01<01:15, 18.89it/s]
 37%|███▋      | 831/2248 [01:02<01:10, 20.13it/s]
 37%|███▋      | 834/2248 [01:02<01:05, 21.51it/s]
 37%|███▋      | 841/2248 [01:02<00:45, 30.63it/s]
 38%|███▊      | 849/2248 [01:02<00:34, 41.10it/s]
 38%|███▊      | 854/2248 [01:02<00:35, 39.78it/s]
 38%|███▊      | 861/2248 [01:02<00:29, 46.85it/s]
 39%|███▊      | 867/2248 [01:02<00:37, 36.82it/s]
 39%|███▉      | 872/2248 [01:03<01:02, 21.88it/s]
 39%|███▉      | 876/2248 [01:03<00:58, 23.32it/s]
 39%|███▉      | 880/2248 [01:03<01:13, 18.52it/s]
 39%|███▉      | 883/2248 [01:04<01:26, 15.82it/s]
 39%|███▉      | 886/2248 [01:04<01:31, 14.93it/s]
 40%|███▉      | 888/2248 [01:04<01:27, 15.61it/s]
 40%|███▉      | 890/2248 [01:04<01:29, 15.22it/s]
 40%|███▉      | 892/2248 [01:04<02:01, 11.12it/s]
 40%|███▉      | 894/2248 [01:05<02:02, 11.02it/s]
 40%|███▉      | 896/2248 [01:05<02:12, 10.17it/s]
 40%|███▉      | 898/2248 [01:05<02:02, 11.01it/s]
 40%|████      | 901/2248 [01:05<01:40, 13.41it/s]
 40%|████      | 903/2248 [01:05<01:58, 11.38it/s]
 40%|████      | 905/2248 [01:06<01:47, 12.54it/s]
 40%|████      | 907/2248 [01:06<02:17,  9.78it/s]
 40%|████      | 909/2248 [01:06<02:40,  8.36it/s]
 41%|████      | 911/2248 [01:06<02:41,  8.29it/s]
 41%|████      | 912/2248 [01:07<03:01,  7.35it/s]
 41%|████      | 913/2248 [01:07<03:21,  6.62it/s]
 41%|████      | 914/2248 [01:07<03:06,  7.13it/s]
 41%|████      | 917/2248 [01:07<02:35,  8.58it/s]
 41%|████      | 919/2248 [01:07<02:18,  9.56it/s]
 41%|████      | 920/2248 [01:08<02:43,  8.10it/s]
 41%|████      | 921/2248 [01:08<02:43,  8.11it/s]
 41%|████      | 924/2248 [01:08<02:20,  9.42it/s]
 41%|████      | 926/2248 [01:08<02:03, 10.74it/s]
 41%|████▏     | 928/2248 [01:08<02:04, 10.62it/s]
 41%|████▏     | 930/2248 [01:09<02:18,  9.52it/s]
 42%|████▏     | 933/2248 [01:09<01:43, 12.76it/s]
 42%|████▏     | 935/2248 [01:09<02:05, 10.45it/s]
 42%|████▏     | 939/2248 [01:09<01:26, 15.07it/s]
 42%|████▏     | 941/2248 [01:09<01:24, 15.44it/s]
 42%|████▏     | 944/2248 [01:09<01:16, 17.00it/s]
 42%|████▏     | 947/2248 [01:09<01:08, 18.87it/s]
 42%|████▏     | 950/2248 [01:10<01:07, 19.19it/s]
 42%|████▏     | 953/2248 [01:10<01:46, 12.11it/s]
 42%|████▏     | 955/2248 [01:10<01:42, 12.61it/s]
 43%|████▎     | 957/2248 [01:11<02:30,  8.58it/s]
 43%|████▎     | 959/2248 [01:11<02:19,  9.27it/s]
 43%|████▎     | 961/2248 [01:11<02:10,  9.84it/s]
 43%|████▎     | 963/2248 [01:11<02:15,  9.48it/s]
 43%|████▎     | 965/2248 [01:11<02:04, 10.28it/s]
 43%|████▎     | 967/2248 [01:12<02:26,  8.72it/s]
 43%|████▎     | 969/2248 [01:12<02:10,  9.79it/s]
 43%|████▎     | 971/2248 [01:12<02:14,  9.47it/s]
 43%|████▎     | 973/2248 [01:12<01:56, 10.94it/s]
 43%|████▎     | 975/2248 [01:12<02:01, 10.52it/s]
 43%|████▎     | 977/2248 [01:13<01:56, 10.91it/s]
 44%|████▎     | 979/2248 [01:13<01:44, 12.13it/s]
 44%|████▎     | 981/2248 [01:13<01:40, 12.62it/s]
 44%|████▎     | 983/2248 [01:13<01:40, 12.56it/s]
 44%|████▍     | 985/2248 [01:13<01:54, 11.02it/s]
 44%|████▍     | 987/2248 [01:13<01:39, 12.67it/s]
 44%|████▍     | 989/2248 [01:13<01:29, 14.13it/s]
 44%|████▍     | 991/2248 [01:14<01:22, 15.26it/s]
 44%|████▍     | 993/2248 [01:14<01:20, 15.51it/s]
 44%|████▍     | 998/2248 [01:14<01:02, 20.03it/s]
 44%|████▍     | 1000/2248 [01:14<01:39, 12.60it/s]
 45%|████▍     | 1002/2248 [01:14<01:58, 10.54it/s]
 45%|████▍     | 1004/2248 [01:15<02:36,  7.97it/s]
 45%|████▍     | 1006/2248 [01:15<03:00,  6.86it/s]
 45%|████▍     | 1007/2248 [01:16<03:15,  6.35it/s]
 45%|████▍     | 1008/2248 [01:16<03:28,  5.95it/s]
 45%|████▍     | 1009/2248 [01:16<03:36,  5.73it/s]
 45%|████▍     | 1011/2248 [01:16<02:44,  7.50it/s]
 45%|████▌     | 1016/2248 [01:16<01:27, 14.05it/s]
 45%|████▌     | 1022/2248 [01:16<00:56, 21.80it/s]
 46%|████▌     | 1025/2248 [01:16<00:55, 21.87it/s]
 46%|████▌     | 1029/2248 [01:17<00:47, 25.48it/s]
 46%|████▌     | 1034/2248 [01:17<00:39, 30.91it/s]
 46%|████▌     | 1039/2248 [01:17<00:35, 33.85it/s]
 46%|████▋     | 1043/2248 [01:17<00:35, 34.04it/s]
 47%|████▋     | 1049/2248 [01:17<00:30, 39.91it/s]
 47%|████▋     | 1054/2248 [01:17<00:43, 27.63it/s]
 47%|████▋     | 1058/2248 [01:18<01:13, 16.11it/s]
 47%|████▋     | 1061/2248 [01:18<01:30, 13.05it/s]
 47%|████▋     | 1064/2248 [01:19<01:48, 10.95it/s]
 47%|████▋     | 1066/2248 [01:19<01:48, 10.94it/s]
 48%|████▊     | 1068/2248 [01:19<01:40, 11.71it/s]
 48%|████▊     | 1072/2248 [01:19<01:15, 15.58it/s]
 48%|████▊     | 1075/2248 [01:19<01:11, 16.33it/s]
 48%|████▊     | 1078/2248 [01:19<01:11, 16.33it/s]
 48%|████▊     | 1083/2248 [01:20<00:58, 19.86it/s]
 48%|████▊     | 1086/2248 [01:20<01:04, 18.07it/s]
 48%|████▊     | 1088/2248 [01:20<01:33, 12.35it/s]
 48%|████▊     | 1090/2248 [01:20<01:51, 10.40it/s]
 49%|████▊     | 1092/2248 [01:21<02:26,  7.89it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 302.47it/s]

[[np.int64(0), False, 4], [np.int64(1), False, 11], [np.int64(2), False, 10], [np.int64(3), False, 0], [np.int64(5), False, 0], [np.int64(6), False, 2], [np.int64(7), False, 2], [np.int64(8), False, 0], [np.int64(9), False, 1], [np.int64(12), False, 4], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2130, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [06:31<1:59:17, 48.04s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [06:31<1:23:03, 33.67s/it]

tensor(12.2867, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5362, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7922, device='cuda:0', grad_fn=<MulBackward0>)

 51%|█████▏    | 154/300 [06:32<40:17, 16.56s/it]

tensor(12.3183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8886, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3311, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8906, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [06:32<13:43,  5.76s/it]

tensor(12.3386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0345, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9653, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0117, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 158/300 [06:32<09:37,  4.07s/it]

tensor(12.3443, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0371, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0850, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1711, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 160/300 [06:32<04:47,  2.06s/it]

tensor(12.3388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0386, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0385, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2751, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [06:33<02:27,  1.07s/it]

tensor(12.3095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0382, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2933, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3165, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▍    | 164/300 [06:33<01:20,  1.70it/s]

tensor(12.2773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3414, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3544, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 166/300 [06:33<00:47,  2.83it/s]

tensor(12.2666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3648, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3822, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [06:33<00:26,  4.98it/s]

tensor(12.2718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4030, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4161, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 170/300 [06:34<00:22,  5.68it/s]

tensor(12.2737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4152, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2701, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4220, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 172/300 [06:34<00:19,  6.69it/s]

tensor(12.2635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4295, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4340, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [06:34<00:17,  7.28it/s]

tensor(12.2462, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4439, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4518, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▊    | 176/300 [06:34<00:16,  7.60it/s]

tensor(12.2327, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4656, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 178/300 [06:35<00:15,  7.87it/s]

tensor(12.2243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4781, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 180/300 [06:35<00:15,  7.87it/s]

tensor(12.2171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4903, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4998, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [06:35<00:15,  7.86it/s]

tensor(12.2096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5059, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5140, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [06:35<00:14,  8.08it/s]

tensor(12.2030, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2002, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5274, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [06:36<00:13,  8.12it/s]

tensor(12.1973, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5257, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5277, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [06:36<00:14,  7.97it/s]

tensor(12.1922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5276, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1899, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5273, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 190/300 [06:36<00:13,  7.93it/s]

tensor(12.1876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5298, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1854, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5302, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [06:36<00:13,  8.12it/s]

tensor(12.1833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5288, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5290, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [06:37<00:12,  8.17it/s]

tensor(12.1788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5322, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1764, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5322, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [06:37<00:12,  8.18it/s]

tensor(12.1743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5336, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5349, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [06:37<00:12,  8.23it/s]

tensor(12.1702, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5351, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5359, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [06:37<00:12,  8.22it/s]

tensor(12.1665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5353, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([199, 349, 169, 126, 138, 205,  33, 125, 222, 127, 197,  77, 189,  92])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:08, 17.49it/s]
  0%|          | 5/2248 [00:00<01:33, 23.93it/s]
  0%|          | 8/2248 [00:00<01:31, 24.49it/s]
  1%|          | 12/2248 [00:00<01:17, 28.73it/s]
  1%|          | 15/2248 [00:00<01:20, 27.86it/s]
  1%|          | 22/2248 [00:00<00:55, 39.91it/s]
  1%|          | 27/2248 [00:00<00:57, 38.43it/s]
  1%|▏         | 32/2248 [00:00<00:57, 38.24it/s]
  2%|▏         | 36/2248 [00:01<00:57, 38.60it/s]
  2%|▏         | 40/2248 [00:01<00:58, 37.70it/s]
  2%|▏         | 46/2248 [00:01<00:52, 41.83it/s]
  2%|▏         | 52/2248 [00:01<00:48, 45.51it/s]
  3%|▎         | 57/2248 [00:01<00:53, 41.23it/s]
  3%|▎         | 62/2248 [00:01<00:57, 38.02it/s]
  3%|▎         | 68/2248 [00:01<00:56, 38.57it/s]
  3%|▎         | 72/2248 [00:01<01:00, 35.76it/s]
  3%|▎         | 76/2248 [00:02<01:41, 21.33it/s]
  4%|▎         | 79/2248 [00:02<01:36, 22.46it/s]
  4%|▍         | 86/2248 [00:03<02:15, 15.94it/s]
  4%|▍         | 89/2248 [00:03<02:09, 16.68it/s]
  4%|▍         | 96/2248 [00:03<01:34, 22.76it/s]
  4%|▍         | 100/2248 [00:03<02:08, 16.74it/s]
  5%|▍         | 106/2248 [00:03<01:37, 22.01it/s]
  5%|▍         | 112/2248 [00:04<01:17, 27.67it/s]
  5%|▌         | 117/2248 [00:04<01:54, 18.68it/s]
  5%|▌         | 121/2248 [00:04<02:21, 15.00it/s]
  6%|▌         | 124/2248 [00:05<02:13, 15.90it/s]
  6%|▌         | 127/2248 [00:06<04:34,  7.74it/s]
  6%|▌         | 129/2248 [00:06<04:53,  7.23it/s]
  6%|▌         | 132/2248 [00:06<03:57,  8.90it/s]
  6%|▌         | 134/2248 [00:07<04:25,  7.97it/s]
  6%|▌         | 136/2248 [00:07<05:20,  6.59it/s]
  6%|▌         | 138/2248 [00:07<04:32,  7.73it/s]
  6%|▋         | 143/2248 [00:07<02:45, 12.76it/s]
  6%|▋         | 146/2248 [00:07<02:51, 12.25it/s]
  7%|▋         | 148/2248 [00:08<02:46, 12.59it/s]
  7%|▋         | 151/2248 [00:08<02:50, 12.33it/s]
  7%|▋         | 153/2248 [00:08<02:43, 12.79it/s]
  7%|▋         | 156/2248 [00:08<03:27, 10.08it/s]
  7%|▋         | 158/2248 [00:09<06:00,  5.79it/s]
  7%|▋         | 159/2248 [00:10<07:18,  4.76it/s]
  7%|▋         | 160/2248 [00:10<06:56,  5.02it/s]
  7%|▋         | 162/2248 [00:10<07:42,  4.51it/s]
  7%|▋         | 165/2248 [00:11<06:14,  5.57it/s]
  7%|▋         | 167/2248 [00:11<05:12,  6.66it/s]
  8%|▊         | 169/2248 [00:11<05:13,  6.64it/s]
  8%|▊         | 173/2248 [00:12<04:35,  7.54it/s]
  8%|▊         | 175/2248 [00:12<03:59,  8.66it/s]
  8%|▊         | 177/2248 [00:12<05:45,  5.99it/s]
  8%|▊         | 178/2248 [00:13<07:57,  4.33it/s]
  8%|▊         | 180/2248 [00:13<06:12,  5.56it/s]
  8%|▊         | 186/2248 [00:13<03:01, 11.34it/s]
  8%|▊         | 189/2248 [00:14<04:17,  8.01it/s]
  9%|▊         | 194/2248 [00:14<02:50, 12.08it/s]
  9%|▉         | 197/2248 [00:15<04:09,  8.22it/s]
  9%|▉         | 202/2248 [00:15<04:16,  7.96it/s]
  9%|▉         | 204/2248 [00:15<03:49,  8.89it/s]
  9%|▉         | 206/2248 [00:16<05:08,  6.62it/s]
  9%|▉         | 208/2248 [00:17<06:27,  5.27it/s]
  9%|▉         | 209/2248 [00:17<08:06,  4.19it/s]
  9%|▉         | 210/2248 [00:18<09:40,  3.51it/s]
  9%|▉         | 211/2248 [00:18<11:20,  2.99it/s]
  9%|▉         | 212/2248 [00:19<13:00,  2.61it/s]
 10%|▉         | 215/2248 [00:19<07:26,  4.56it/s]
 10%|▉         | 220/2248 [00:19<03:51,  8.78it/s]
 10%|▉         | 224/2248 [00:19<02:42, 12.42it/s]
 10%|█         | 227/2248 [00:19<02:16, 14.78it/s]
 10%|█         | 232/2248 [00:19<01:39, 20.36it/s]
 11%|█         | 237/2248 [00:19<01:17, 25.95it/s]
 11%|█         | 245/2248 [00:20<00:55, 36.14it/s]
 11%|█         | 251/2248 [00:20<00:48, 41.22it/s]
 11%|█▏        | 256/2248 [00:20<00:49, 40.10it/s]
 12%|█▏        | 262/2248 [00:20<00:50, 39.16it/s]
 12%|█▏        | 268/2248 [00:20<00:45, 43.61it/s]
 12%|█▏        | 273/2248 [00:21<01:50, 17.81it/s]
 12%|█▏        | 277/2248 [00:22<02:51, 11.49it/s]
 12%|█▎        | 281/2248 [00:22<02:21, 13.89it/s]
 13%|█▎        | 284/2248 [00:22<03:09, 10.34it/s]
 13%|█▎        | 287/2248 [00:22<02:45, 11.83it/s]
 13%|█▎        | 292/2248 [00:23<03:18,  9.85it/s]
 13%|█▎        | 294/2248 [00:23<03:05, 10.54it/s]
 13%|█▎        | 301/2248 [00:23<01:53, 17.20it/s]
 14%|█▎        | 305/2248 [00:24<03:02, 10.63it/s]
 14%|█▎        | 308/2248 [00:25<03:43,  8.66it/s]
 14%|█▍        | 310/2248 [00:25<04:54,  6.57it/s]
 14%|█▍        | 313/2248 [00:26<05:25,  5.94it/s]
 14%|█▍        | 315/2248 [00:27<08:46,  3.67it/s]
 14%|█▍        | 318/2248 [00:28<07:14,  4.44it/s]
 14%|█▍        | 320/2248 [00:28<06:48,  4.72it/s]
 14%|█▍        | 322/2248 [00:28<06:21,  5.04it/s]
 14%|█▍        | 323/2248 [00:29<07:16,  4.41it/s]
 14%|█▍        | 325/2248 [00:29<07:27,  4.30it/s]
 15%|█▍        | 327/2248 [00:29<05:51,  5.47it/s]
 15%|█▍        | 332/2248 [00:30<04:46,  6.68it/s]
 15%|█▍        | 335/2248 [00:30<03:39,  8.70it/s]
 15%|█▌        | 339/2248 [00:30<03:44,  8.50it/s]
 15%|█▌        | 341/2248 [00:31<03:24,  9.34it/s]
 15%|█▌        | 343/2248 [00:31<04:07,  7.69it/s]
 15%|█▌        | 345/2248 [00:32<06:01,  5.26it/s]
 15%|█▌        | 347/2248 [00:32<06:38,  4.77it/s]
 15%|█▌        | 348/2248 [00:32<06:44,  4.69it/s]
 16%|█▌        | 349/2248 [00:33<07:42,  4.10it/s]
 16%|█▌        | 350/2248 [00:33<08:11,  3.86it/s]
 16%|█▌        | 353/2248 [00:34<06:37,  4.76it/s]
 16%|█▌        | 355/2248 [00:34<05:08,  6.14it/s]
 16%|█▌        | 356/2248 [00:34<07:24,  4.26it/s]
 16%|█▌        | 358/2248 [00:34<05:35,  5.64it/s]
 16%|█▌        | 362/2248 [00:35<05:20,  5.88it/s]
 16%|█▌        | 364/2248 [00:36<06:38,  4.72it/s]
 16%|█▋        | 366/2248 [00:36<05:18,  5.90it/s]
 17%|█▋        | 371/2248 [00:37<04:39,  6.70it/s]
 17%|█▋        | 373/2248 [00:37<04:01,  7.76it/s]
 17%|█▋        | 379/2248 [00:37<02:19, 13.39it/s]
 17%|█▋        | 382/2248 [00:37<02:01, 15.34it/s]
 17%|█▋        | 385/2248 [00:38<03:26,  9.04it/s]
 17%|█▋        | 388/2248 [00:38<04:20,  7.15it/s]
 17%|█▋        | 390/2248 [00:39<05:35,  5.53it/s]
 17%|█▋        | 392/2248 [00:39<05:23,  5.73it/s]
 17%|█▋        | 393/2248 [00:40<06:28,  4.78it/s]
 18%|█▊        | 394/2248 [00:40<07:10,  4.31it/s]
 18%|█▊        | 395/2248 [00:40<07:30,  4.11it/s]
 18%|█▊        | 397/2248 [00:40<05:33,  5.55it/s]
 18%|█▊        | 402/2248 [00:40<02:48, 10.98it/s]
 18%|█▊        | 408/2248 [00:41<01:44, 17.69it/s]
 18%|█▊        | 415/2248 [00:41<01:14, 24.59it/s]
 19%|█▊        | 421/2248 [00:41<00:59, 30.92it/s]
 19%|█▉        | 427/2248 [00:41<00:50, 36.00it/s]
 19%|█▉        | 432/2248 [00:41<00:55, 32.45it/s]
 19%|█▉        | 436/2248 [00:42<01:27, 20.65it/s]
 20%|█▉        | 440/2248 [00:42<02:30, 12.03it/s]
 20%|█▉        | 443/2248 [00:42<02:21, 12.74it/s]
 20%|█▉        | 446/2248 [00:44<04:16,  7.02it/s]
 20%|█▉        | 448/2248 [00:44<03:49,  7.85it/s]
 20%|██        | 451/2248 [00:44<03:01,  9.92it/s]
 20%|██        | 457/2248 [00:44<02:38, 11.27it/s]
 20%|██        | 459/2248 [00:44<02:30, 11.92it/s]
 21%|██        | 463/2248 [00:44<01:55, 15.49it/s]
 21%|██        | 468/2248 [00:45<01:25, 20.71it/s]
 21%|██        | 472/2248 [00:45<02:05, 14.10it/s]
 21%|██        | 475/2248 [00:46<03:27,  8.55it/s]
 21%|██        | 477/2248 [00:46<04:29,  6.58it/s]
 21%|██▏       | 479/2248 [00:47<04:52,  6.05it/s]
 21%|██▏       | 481/2248 [00:47<05:58,  4.93it/s]
 21%|██▏       | 483/2248 [00:48<04:56,  5.95it/s]
 22%|██▏       | 485/2248 [00:48<04:02,  7.26it/s]
 22%|██▏       | 487/2248 [00:48<05:07,  5.73it/s]
 22%|██▏       | 490/2248 [00:48<03:44,  7.82it/s]
 22%|██▏       | 492/2248 [00:48<03:10,  9.23it/s]
 22%|██▏       | 495/2248 [00:49<03:05,  9.46it/s]
 22%|██▏       | 497/2248 [00:49<02:40, 10.92it/s]
 22%|██▏       | 499/2248 [00:49<02:27, 11.82it/s]
 22%|██▏       | 501/2248 [00:49<03:00,  9.71it/s]
 22%|██▏       | 504/2248 [00:49<02:18, 12.63it/s]
 23%|██▎       | 509/2248 [00:50<01:41, 17.12it/s]
 23%|██▎       | 512/2248 [00:50<01:36, 18.06it/s]
 23%|██▎       | 515/2248 [00:50<02:38, 10.95it/s]
 23%|██▎       | 518/2248 [00:50<02:13, 12.92it/s]
 23%|██▎       | 523/2248 [00:51<01:33, 18.51it/s]
 24%|██▎       | 529/2248 [00:51<01:07, 25.29it/s]
 24%|██▍       | 534/2248 [00:51<00:59, 28.63it/s]
 24%|██▍       | 539/2248 [00:51<00:53, 32.08it/s]
 24%|██▍       | 543/2248 [00:51<00:52, 32.63it/s]
 24%|██▍       | 549/2248 [00:51<00:43, 39.10it/s]
 25%|██▍       | 555/2248 [00:51<00:38, 43.67it/s]
 25%|██▍       | 561/2248 [00:51<00:36, 46.83it/s]
 25%|██▌       | 566/2248 [00:51<00:36, 45.88it/s]
 25%|██▌       | 571/2248 [00:52<00:56, 29.87it/s]
 26%|██▌       | 575/2248 [00:52<01:48, 15.39it/s]
 26%|██▌       | 578/2248 [00:53<01:39, 16.76it/s]
 26%|██▌       | 581/2248 [00:53<02:45, 10.06it/s]
 26%|██▌       | 584/2248 [00:54<04:12,  6.58it/s]
 26%|██▌       | 586/2248 [00:55<04:43,  5.86it/s]
 26%|██▌       | 588/2248 [00:55<05:32,  5.00it/s]
 26%|██▌       | 589/2248 [00:55<05:14,  5.28it/s]
 26%|██▋       | 592/2248 [00:56<04:24,  6.27it/s]
 26%|██▋       | 595/2248 [00:56<03:19,  8.30it/s]
 27%|██▋       | 601/2248 [00:56<01:55, 14.23it/s]
 27%|██▋       | 604/2248 [00:57<03:17,  8.30it/s]
 27%|██▋       | 606/2248 [00:58<05:34,  4.92it/s]
 27%|██▋       | 608/2248 [00:59<07:23,  3.70it/s]
 27%|██▋       | 610/2248 [00:59<06:53,  3.96it/s]
 27%|██▋       | 612/2248 [00:59<05:39,  4.83it/s]
 27%|██▋       | 617/2248 [00:59<03:13,  8.45it/s]
 28%|██▊       | 620/2248 [01:00<02:39, 10.22it/s]
 28%|██▊       | 623/2248 [01:00<02:23, 11.30it/s]
 28%|██▊       | 625/2248 [01:00<02:12, 12.22it/s]
 28%|██▊       | 630/2248 [01:00<01:32, 17.50it/s]
 28%|██▊       | 633/2248 [01:00<01:23, 19.39it/s]
 28%|██▊       | 637/2248 [01:00<01:10, 22.73it/s]
 29%|██▊       | 641/2248 [01:00<01:02, 25.55it/s]
 29%|██▊       | 646/2248 [01:01<00:51, 30.98it/s]
 29%|██▉       | 651/2248 [01:01<00:55, 28.77it/s]
 29%|██▉       | 655/2248 [01:01<01:40, 15.91it/s]
 29%|██▉       | 658/2248 [01:02<02:26, 10.82it/s]
 29%|██▉       | 661/2248 [01:02<03:10,  8.34it/s]
 29%|██▉       | 663/2248 [01:03<02:49,  9.36it/s]
 30%|██▉       | 665/2248 [01:03<02:32, 10.41it/s]
 30%|██▉       | 670/2248 [01:03<02:30, 10.48it/s]
 30%|██▉       | 673/2248 [01:03<02:12, 11.86it/s]
 30%|███       | 675/2248 [01:03<02:02, 12.85it/s]
 30%|███       | 677/2248 [01:04<03:32,  7.41it/s]
 30%|███       | 679/2248 [01:04<03:01,  8.64it/s]
 30%|███       | 682/2248 [01:05<03:32,  7.38it/s]
 30%|███       | 684/2248 [01:05<03:38,  7.17it/s]
 31%|███       | 686/2248 [01:05<03:54,  6.66it/s]
 31%|███       | 688/2248 [01:06<04:34,  5.68it/s]
 31%|███       | 690/2248 [01:06<03:44,  6.94it/s]
 31%|███       | 692/2248 [01:06<03:44,  6.94it/s]
 31%|███       | 694/2248 [01:06<03:06,  8.34it/s]
 31%|███       | 696/2248 [01:06<02:35, 10.01it/s]
 31%|███       | 698/2248 [01:07<02:37,  9.84it/s]
 31%|███       | 700/2248 [01:07<03:05,  8.33it/s]
 31%|███       | 702/2248 [01:07<03:21,  7.66it/s]
 31%|███▏      | 704/2248 [01:08<04:02,  6.35it/s]
 31%|███▏      | 706/2248 [01:08<03:15,  7.88it/s]
 31%|███▏      | 708/2248 [01:08<02:42,  9.46it/s]
 32%|███▏      | 712/2248 [01:09<03:19,  7.72it/s]
 32%|███▏      | 715/2248 [01:09<02:36,  9.78it/s]
 32%|███▏      | 722/2248 [01:09<01:26, 17.68it/s]
 32%|███▏      | 728/2248 [01:10<01:57, 12.94it/s]
 33%|███▎      | 731/2248 [01:10<01:46, 14.26it/s]
 33%|███▎      | 735/2248 [01:10<02:32,  9.95it/s]
 33%|███▎      | 737/2248 [01:11<03:38,  6.91it/s]
 33%|███▎      | 739/2248 [01:12<04:31,  5.56it/s]
 33%|███▎      | 742/2248 [01:12<04:54,  5.11it/s]
 33%|███▎      | 743/2248 [01:13<05:50,  4.30it/s]
 33%|███▎      | 744/2248 [01:13<07:00,  3.58it/s]
 33%|███▎      | 746/2248 [01:14<05:26,  4.60it/s]
 33%|███▎      | 749/2248 [01:14<04:32,  5.50it/s]
 33%|███▎      | 751/2248 [01:14<03:44,  6.66it/s]
 33%|███▎      | 752/2248 [01:14<04:07,  6.04it/s]
 34%|███▎      | 754/2248 [01:14<03:15,  7.64it/s]
 34%|███▍      | 759/2248 [01:15<01:49, 13.55it/s]
 34%|███▍      | 765/2248 [01:15<01:10, 21.04it/s]
 34%|███▍      | 771/2248 [01:15<00:51, 28.43it/s]
 34%|███▍      | 775/2248 [01:16<03:14,  7.58it/s]
 35%|███▍      | 778/2248 [01:18<05:09,  4.76it/s]
 35%|███▍      | 781/2248 [01:18<04:06,  5.95it/s]
 35%|███▍      | 784/2248 [01:20<06:34,  3.71it/s]
 35%|███▌      | 787/2248 [01:20<05:02,  4.83it/s]
 35%|███▌      | 792/2248 [01:20<04:09,  5.84it/s]
 35%|███▌      | 795/2248 [01:20<03:22,  7.19it/s]
 35%|███▌      | 797/2248 [01:21<03:35,  6.73it/s]
 36%|███▌      | 799/2248 [01:21<03:04,  7.85it/s]
 36%|███▌      | 801/2248 [01:21<02:38,  9.10it/s]
 36%|███▌      | 806/2248 [01:22<02:52,  8.38it/s]
 36%|███▌      | 809/2248 [01:22<02:18, 10.36it/s]
 36%|███▌      | 812/2248 [01:22<02:58,  8.06it/s]
 36%|███▋      | 815/2248 [01:22<02:24,  9.91it/s]
 36%|███▋      | 817/2248 [01:23<03:29,  6.84it/s]
 37%|███▋      | 821/2248 [01:23<02:24,  9.89it/s]
 37%|███▋      | 825/2248 [01:23<01:46, 13.31it/s]
 37%|███▋      | 831/2248 [01:23<01:11, 19.80it/s]
 37%|███▋      | 837/2248 [01:23<00:54, 26.12it/s]
 37%|███▋      | 842/2248 [01:24<00:50, 28.09it/s]
 38%|███▊      | 846/2248 [01:24<00:48, 28.82it/s]
 38%|███▊      | 854/2248 [01:24<00:35, 39.00it/s]
 38%|███▊      | 859/2248 [01:24<00:33, 40.99it/s]
 39%|███▊      | 866/2248 [01:24<00:29, 46.28it/s]
 39%|███▉      | 872/2248 [01:25<01:23, 16.53it/s]
 39%|███▉      | 876/2248 [01:25<01:13, 18.77it/s]
 39%|███▉      | 880/2248 [01:26<01:58, 11.57it/s]
 39%|███▉      | 883/2248 [01:27<02:44,  8.29it/s]
 39%|███▉      | 886/2248 [01:27<02:23,  9.49it/s]
 40%|███▉      | 891/2248 [01:27<01:43, 13.17it/s]
 40%|███▉      | 894/2248 [01:28<02:28,  9.09it/s]
 40%|███▉      | 897/2248 [01:28<02:02, 10.99it/s]
 40%|████      | 902/2248 [01:28<02:21,  9.53it/s]
 40%|████      | 904/2248 [01:29<03:13,  6.94it/s]
 40%|████      | 906/2248 [01:30<03:54,  5.71it/s]
 40%|████      | 908/2248 [01:31<05:59,  3.73it/s]
 40%|████      | 910/2248 [01:31<06:26,  3.46it/s]
 41%|████      | 911/2248 [01:32<07:28,  2.98it/s]
 41%|████      | 912/2248 [01:33<08:24,  2.65it/s]
 41%|████      | 913/2248 [01:33<08:12,  2.71it/s]
 41%|████      | 916/2248 [01:33<04:46,  4.65it/s]
 41%|████      | 918/2248 [01:34<05:24,  4.09it/s]
 41%|████      | 920/2248 [01:34<05:49,  3.80it/s]
 41%|████      | 922/2248 [01:34<04:28,  4.94it/s]
 41%|████      | 924/2248 [01:35<05:17,  4.18it/s]
 41%|████      | 927/2248 [01:36<05:14,  4.20it/s]
 41%|████▏     | 930/2248 [01:36<03:40,  5.98it/s]
 42%|████▏     | 935/2248 [01:36<02:13,  9.87it/s]
 42%|████▏     | 938/2248 [01:36<01:54, 11.42it/s]
 42%|████▏     | 944/2248 [01:36<01:14, 17.57it/s]
 42%|████▏     | 948/2248 [01:36<01:05, 19.93it/s]
 42%|████▏     | 952/2248 [01:37<01:49, 11.85it/s]
 42%|████▏     | 955/2248 [01:37<01:35, 13.61it/s]
 43%|████▎     | 958/2248 [01:38<03:26,  6.24it/s]
 43%|████▎     | 960/2248 [01:39<04:01,  5.33it/s]
 43%|████▎     | 962/2248 [01:40<05:22,  3.98it/s]
 43%|████▎     | 963/2248 [01:41<06:23,  3.35it/s]
 43%|████▎     | 966/2248 [01:41<05:46,  3.70it/s]
 43%|████▎     | 968/2248 [01:41<04:34,  4.66it/s]
 43%|████▎     | 969/2248 [01:42<05:49,  3.66it/s]
 43%|████▎     | 970/2248 [01:43<07:04,  3.01it/s]
 43%|████▎     | 973/2248 [01:43<04:18,  4.93it/s]
 43%|████▎     | 975/2248 [01:43<04:56,  4.30it/s]
 43%|████▎     | 976/2248 [01:44<06:20,  3.34it/s]
 43%|████▎     | 977/2248 [01:44<05:30,  3.85it/s]
 44%|████▎     | 979/2248 [01:44<03:56,  5.38it/s]
 44%|████▎     | 981/2248 [01:44<03:28,  6.06it/s]
 44%|████▎     | 983/2248 [01:44<02:45,  7.63it/s]
 44%|████▍     | 985/2248 [01:45<02:45,  7.65it/s]
 44%|████▍     | 987/2248 [01:45<02:54,  7.22it/s]
 44%|████▍     | 989/2248 [01:45<02:29,  8.44it/s]
 44%|████▍     | 992/2248 [01:45<01:46, 11.80it/s]
 44%|████▍     | 999/2248 [01:46<01:55, 10.84it/s]
 45%|████▍     | 1002/2248 [01:46<01:39, 12.46it/s]
 45%|████▍     | 1004/2248 [01:47<03:39,  5.66it/s]
 45%|████▍     | 1006/2248 [01:48<05:25,  3.81it/s]
 45%|████▍     | 1007/2248 [01:49<06:22,  3.25it/s]
 45%|████▍     | 1008/2248 [01:50<07:19,  2.82it/s]
 45%|████▍     | 1009/2248 [01:50<08:15,  2.50it/s]
 45%|████▍     | 1011/2248 [01:50<05:49,  3.54it/s]
 45%|████▌     | 1016/2248 [01:50<02:50,  7.23it/s]
 45%|████▌     | 1022/2248 [01:51<01:38, 12.49it/s]
 46%|████▌     | 1027/2248 [01:51<01:11, 17.13it/s]
 46%|████▌     | 1033/2248 [01:51<00:51, 23.41it/s]
 46%|████▌     | 1039/2248 [01:51<00:42, 28.29it/s]
 46%|████▋     | 1044/2248 [01:51<00:37, 31.73it/s]
 47%|████▋     | 1050/2248 [01:51<00:33, 35.89it/s]
 47%|████▋     | 1055/2248 [01:52<01:06, 18.01it/s]
 47%|████▋     | 1059/2248 [01:52<01:41, 11.76it/s]
 47%|████▋     | 1062/2248 [01:53<02:18,  8.57it/s]
 47%|████▋     | 1064/2248 [01:53<02:05,  9.46it/s]
 47%|████▋     | 1066/2248 [01:54<02:47,  7.05it/s]
 48%|████▊     | 1069/2248 [01:54<02:13,  8.82it/s]
 48%|████▊     | 1071/2248 [01:55<03:03,  6.40it/s]
 48%|████▊     | 1073/2248 [01:55<02:39,  7.36it/s]
 48%|████▊     | 1076/2248 [01:55<03:13,  6.06it/s]
 48%|████▊     | 1078/2248 [01:55<02:40,  7.29it/s]
 48%|████▊     | 1082/2248 [01:56<01:46, 10.93it/s]
 48%|████▊     | 1086/2248 [01:56<01:19, 14.70it/s]
 48%|████▊     | 1089/2248 [01:57<02:58,  6.50it/s]
 49%|████▊     | 1091/2248 [01:58<04:43,  4.08it/s]
 49%|████▊     | 1093/2248 [01:59<06:20,  3.04it/s]
 49%|████▊     | 1095/2248 [02:00<06:15,  3.07it/s]
 49%|████▉     | 1098/2248 [02:00<04:21,  4.40it/s]
 49%|████▉     | 1105/2248 [02:00<02:09,  8.82it/s]
 49%|████▉     | 1111/2248 [02:00<01:26, 13.18it/s]
 50%|████▉     | 1117/2248 [02:00<01:04, 17.56it/s]
 50%|████▉     | 1121/2248 [02:00<00:56, 19.77it/s]
 50%|█████     | 1127/2248 [02:01<00:46, 23.96it/s]
 50%|█████     | 1131/2248 [02:01<00:42, 26.36it/s]
 51%|█████     | 1137/2248 [02:01<00:34, 32.53it/s]
 51%|█████     | 1142/2248 [02:01<01:01, 17.89it/s]
 51%|█████     | 1146/2248 [02:03<02:05,  8.81it/s]
 51%|█████     | 1149/2248 [02:03<01:54,  9.58it/s]
 51%|█████     | 1152/2248 [02:03<02:09,  8.44it/s]
 51%|█████▏    | 1154/2248 [02:04<02:44,  6.64it/s]
 51%|█████▏    | 1156/2248 [02:04<02:36,  6.98it/s]
 52%|█████▏    | 1158/2248 [02:04<02:13,  8.18it/s]
 52%|█████▏    | 1160/2248 [02:05<02:39,  6.82it/s]
 52%|█████▏    | 1162/2248 [02:05<02:17,  7.90it/s]
 52%|█████▏    | 1164/2248 [02:06<03:35,  5.02it/s]
 52%|█████▏    | 1166/2248 [02:06<02:51,  6.30it/s]
 52%|█████▏    | 1170/2248 [02:06<02:51,  6.29it/s]
 52%|█████▏    | 1172/2248 [02:07<03:30,  5.12it/s]
 52%|█████▏    | 1175/2248 [02:07<02:32,  7.06it/s]
 52%|█████▏    | 1178/2248 [02:08<02:52,  6.22it/s]
 52%|█████▏    | 1180/2248 [02:08<03:33,  5.01it/s]
 53%|█████▎    | 1182/2248 [02:09<03:36,  4.93it/s]
 53%|█████▎    | 1184/2248 [02:09<02:57,  6.00it/s]
 53%|█████▎    | 1186/2248 [02:09<02:25,  7.29it/s]
 53%|█████▎    | 1188/2248 [02:10<04:29,  3.94it/s]
 53%|█████▎    | 1189/2248 [02:11<05:32,  3.18it/s]
 53%|█████▎    | 1191/2248 [02:11<04:05,  4.31it/s]
 53%|█████▎    | 1195/2248 [02:11<03:24,  5.16it/s]
 53%|█████▎    | 1198/2248 [02:12<02:29,  7.02it/s]
 53%|█████▎    | 1201/2248 [02:12<02:50,  6.14it/s]
 54%|█████▎    | 1204/2248 [02:12<02:09,  8.04it/s]
 54%|█████▎    | 1206/2248 [02:13<02:55,  5.95it/s]
 54%|█████▍    | 1210/2248 [02:13<01:56,  8.93it/s]
 54%|█████▍    | 1215/2248 [02:14<02:16,  7.59it/s]
 54%|█████▍    | 1217/2248 [02:14<02:01,  8.48it/s]
 54%|█████▍    | 1224/2248 [02:14<01:10, 14.60it/s]
 55%|█████▍    | 1227/2248 [02:15<01:52,  9.08it/s]
 55%|█████▍    | 1230/2248 [02:15<01:54,  8.93it/s]
 55%|█████▍    | 1232/2248 [02:16<02:43,  6.22it/s]
 55%|█████▍    | 1234/2248 [02:16<02:21,  7.17it/s]
 55%|█████▌    | 1240/2248 [02:16<01:46,  9.50it/s]
 55%|█████▌    | 1243/2248 [02:16<01:28, 11.37it/s]
 55%|█████▌    | 1245/2248 [02:17<01:53,  8.84it/s]
 55%|█████▌    | 1247/2248 [02:17<02:02,  8.17it/s]
 56%|█████▌    | 1251/2248 [02:17<01:25, 11.73it/s]
 56%|█████▌    | 1256/2248 [02:17<00:58, 17.02it/s]
 56%|█████▌    | 1262/2248 [02:18<00:41, 23.99it/s]
 56%|█████▋    | 1267/2248 [02:18<00:34, 28.83it/s]
 57%|█████▋    | 1272/2248 [02:18<01:03, 15.31it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 296.82it/s]

[[np.int64(0), False, 8], [np.int64(1), False, 12], [np.int64(2), False, 12], [np.int64(3), False, 8], [np.int64(4), False, 9], [np.int64(5), False, 0], [np.int64(6), False, 9], [np.int64(7), False, 0], [np.int64(9), False, 12], [np.int64(10), False, 1], [np.int64(11), False, 9], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6540, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [10:27<1:53:52, 69.01s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [10:27<1:18:58, 48.35s/it]

tensor(12.1669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7922, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1752, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0084, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 204/300 [10:27<38:00, 23.76s/it]

tensor(12.1861, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1029, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1150, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [10:28<18:19, 11.70s/it]

tensor(12.1956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1824, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1297, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 208/300 [10:28<08:53,  5.80s/it]

tensor(12.1889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1442, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1600, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 210/300 [10:28<04:21,  2.90s/it]

tensor(12.1825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1835, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2075, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 212/300 [10:28<02:11,  1.49s/it]

tensor(12.1789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0369, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2208, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2587, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [10:29<00:50,  1.69it/s]

tensor(12.1766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0375, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9517, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 216/300 [10:29<00:37,  2.22it/s]

tensor(12.1761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0367, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1859, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2374, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 218/300 [10:29<00:23,  3.51it/s]

tensor(12.1930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2254, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0385, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2486, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [10:29<00:16,  4.93it/s]

tensor(12.1805, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0395, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2872, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3042, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [10:30<00:11,  6.66it/s]

tensor(12.1982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3713, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [10:30<00:10,  7.09it/s]

tensor(12.2003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0407, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3953, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0405, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4076, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [10:30<00:09,  7.54it/s]

tensor(12.1672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0401, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4193, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4040, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [10:30<00:09,  7.65it/s]

tensor(12.1716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0387, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4014, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1807, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3978, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [10:31<00:08,  8.00it/s]

tensor(12.1816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0373, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3927, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [10:31<00:08,  7.90it/s]

tensor(12.1603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1488, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 234/300 [10:31<00:08,  7.85it/s]

tensor(12.1422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3960, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3958, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▊  | 236/300 [10:31<00:08,  7.92it/s]

tensor(12.1424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4021, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4033, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [10:32<00:07,  8.03it/s]

tensor(12.1428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4095, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4131, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [10:32<00:07,  8.08it/s]

tensor(12.1363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0284, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4136, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4185, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 242/300 [10:32<00:07,  8.11it/s]

tensor(12.1294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4166, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4201, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████▏ | 244/300 [10:32<00:07,  7.75it/s]

tensor(12.1245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4201, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1221, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4189, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [10:33<00:07,  7.66it/s]

tensor(12.1195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4238, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4284, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [10:33<00:06,  7.87it/s]

tensor(12.1142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4303, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4332, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [10:33<00:06,  7.98it/s]

tensor(12.1108, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4369, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([219, 214, 247,  54, 116, 133, 112, 189, 173, 170, 115, 322,  95,  89])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 4/2248 [00:00<00:58, 38.12it/s]
  0%|          | 8/2248 [00:00<01:17, 29.01it/s]
  1%|          | 12/2248 [00:00<01:15, 29.72it/s]
  1%|          | 16/2248 [00:00<01:11, 31.06it/s]
  1%|          | 23/2248 [00:00<00:53, 41.48it/s]
  1%|          | 28/2248 [00:00<00:50, 43.86it/s]
  2%|▏         | 35/2248 [00:00<00:44, 49.93it/s]
  2%|▏         | 41/2248 [00:01<01:13, 30.23it/s]
  2%|▏         | 46/2248 [00:01<01:44, 20.98it/s]
  2%|▏         | 50/2248 [00:01<01:34, 23.21it/s]
  2%|▏         | 54/2248 [00:01<01:31, 23.89it/s]
  3%|▎         | 58/2248 [00:02<01:27, 24.92it/s]
  3%|▎         | 62/2248 [00:02<01:56, 18.83it/s]
  3%|▎         | 65/2248 [00:02<01:49, 20.02it/s]
  3%|▎         | 73/2248 [00:02<01:11, 30.31it/s]
  3%|▎         | 77/2248 [00:02<01:37, 22.34it/s]
  4%|▎         | 81/2248 [00:03<02:10, 16.55it/s]
  4%|▎         | 84/2248 [00:03<02:25, 14.90it/s]
  4%|▍         | 87/2248 [00:03<02:37, 13.68it/s]
  4%|▍         | 89/2248 [00:04<03:00, 11.96it/s]
  4%|▍         | 92/2248 [00:04<02:31, 14.21it/s]
  4%|▍         | 94/2248 [00:04<03:07, 11.50it/s]
  4%|▍         | 96/2248 [00:04<02:58, 12.06it/s]
  4%|▍         | 98/2248 [00:04<03:02, 11.81it/s]
  4%|▍         | 100/2248 [00:05<02:51, 12.50it/s]
  5%|▍         | 102/2248 [00:05<03:00, 11.86it/s]
  5%|▍         | 104/2248 [00:05<02:45, 12.94it/s]
  5%|▍         | 107/2248 [00:05<02:29, 14.34it/s]
  5%|▍         | 109/2248 [00:05<02:57, 12.08it/s]
  5%|▍         | 111/2248 [00:05<03:22, 10.56it/s]
  5%|▌         | 113/2248 [00:06<03:19, 10.71it/s]
  5%|▌         | 115/2248 [00:06<03:14, 10.99it/s]
  5%|▌         | 117/2248 [00:06<04:21,  8.14it/s]
  5%|▌         | 119/2248 [00:06<03:48,  9.32it/s]
  5%|▌         | 121/2248 [00:07<03:43,  9.53it/s]
  5%|▌         | 123/2248 [00:07<04:33,  7.76it/s]
  6%|▌         | 126/2248 [00:07<04:28,  7.90it/s]
  6%|▌         | 127/2248 [00:08<05:31,  6.39it/s]
  6%|▌         | 128/2248 [00:08<06:37,  5.34it/s]
  6%|▌         | 130/2248 [00:08<05:05,  6.94it/s]
  6%|▌         | 133/2248 [00:08<04:47,  7.34it/s]
  6%|▌         | 135/2248 [00:09<03:55,  8.95it/s]
  6%|▌         | 137/2248 [00:09<04:45,  7.40it/s]
  6%|▋         | 141/2248 [00:09<03:02, 11.57it/s]
  6%|▋         | 145/2248 [00:09<03:01, 11.60it/s]
  7%|▋         | 147/2248 [00:10<02:52, 12.18it/s]
  7%|▋         | 151/2248 [00:10<02:56, 11.90it/s]
  7%|▋         | 153/2248 [00:10<02:41, 12.97it/s]
  7%|▋         | 156/2248 [00:10<03:08, 11.11it/s]
  7%|▋         | 158/2248 [00:11<03:58,  8.78it/s]
  7%|▋         | 160/2248 [00:11<04:39,  7.48it/s]
  7%|▋         | 162/2248 [00:12<05:11,  6.71it/s]
  7%|▋         | 164/2248 [00:12<04:16,  8.14it/s]
  7%|▋         | 166/2248 [00:12<04:55,  7.05it/s]
  8%|▊         | 169/2248 [00:12<04:48,  7.20it/s]
  8%|▊         | 170/2248 [00:13<05:34,  6.21it/s]
  8%|▊         | 172/2248 [00:13<05:09,  6.71it/s]
  8%|▊         | 174/2248 [00:13<04:21,  7.93it/s]
  8%|▊         | 176/2248 [00:13<04:26,  7.77it/s]
  8%|▊         | 177/2248 [00:14<04:39,  7.42it/s]
  8%|▊         | 178/2248 [00:14<05:24,  6.39it/s]
  8%|▊         | 179/2248 [00:14<05:15,  6.56it/s]
  8%|▊         | 183/2248 [00:14<03:43,  9.23it/s]
  8%|▊         | 184/2248 [00:14<03:54,  8.82it/s]
  8%|▊         | 186/2248 [00:14<03:33,  9.64it/s]
  8%|▊         | 187/2248 [00:15<04:58,  6.90it/s]
  8%|▊         | 188/2248 [00:15<04:45,  7.22it/s]
  8%|▊         | 189/2248 [00:15<06:10,  5.56it/s]
  8%|▊         | 191/2248 [00:15<04:45,  7.20it/s]
  9%|▊         | 193/2248 [00:15<03:40,  9.30it/s]
  9%|▉         | 197/2248 [00:16<02:28, 13.78it/s]
  9%|▉         | 199/2248 [00:16<03:00, 11.35it/s]
  9%|▉         | 201/2248 [00:16<02:55, 11.64it/s]
  9%|▉         | 203/2248 [00:16<04:02,  8.43it/s]
  9%|▉         | 206/2248 [00:17<02:56, 11.55it/s]
  9%|▉         | 208/2248 [00:17<03:40,  9.27it/s]
  9%|▉         | 210/2248 [00:17<04:47,  7.09it/s]
  9%|▉         | 212/2248 [00:18<05:14,  6.47it/s]
  9%|▉         | 213/2248 [00:18<05:05,  6.67it/s]
 10%|▉         | 215/2248 [00:18<04:11,  8.07it/s]
 10%|▉         | 217/2248 [00:18<03:32,  9.56it/s]
 10%|▉         | 220/2248 [00:18<02:41, 12.53it/s]
 10%|▉         | 222/2248 [00:18<02:47, 12.13it/s]
 10%|▉         | 224/2248 [00:19<02:37, 12.82it/s]
 10%|█         | 229/2248 [00:19<01:41, 19.93it/s]
 10%|█         | 232/2248 [00:19<01:32, 21.85it/s]
 11%|█         | 240/2248 [00:19<00:57, 34.92it/s]
 11%|█         | 246/2248 [00:19<00:50, 40.03it/s]
 11%|█         | 251/2248 [00:19<00:47, 41.66it/s]
 11%|█▏        | 258/2248 [00:19<00:40, 49.07it/s]
 12%|█▏        | 264/2248 [00:19<00:38, 51.53it/s]
 12%|█▏        | 270/2248 [00:19<00:39, 49.78it/s]
 12%|█▏        | 276/2248 [00:20<00:47, 41.15it/s]
 12%|█▎        | 281/2248 [00:20<01:22, 23.94it/s]
 13%|█▎        | 285/2248 [00:21<01:55, 16.95it/s]
 13%|█▎        | 289/2248 [00:21<01:39, 19.77it/s]
 13%|█▎        | 293/2248 [00:21<02:05, 15.61it/s]
 13%|█▎        | 296/2248 [00:21<02:03, 15.80it/s]
 13%|█▎        | 299/2248 [00:22<02:30, 12.93it/s]
 13%|█▎        | 301/2248 [00:22<02:35, 12.50it/s]
 13%|█▎        | 303/2248 [00:22<04:11,  7.73it/s]
 14%|█▎        | 305/2248 [00:23<04:36,  7.02it/s]
 14%|█▎        | 307/2248 [00:23<04:58,  6.49it/s]
 14%|█▎        | 308/2248 [00:23<05:36,  5.77it/s]
 14%|█▎        | 309/2248 [00:24<06:18,  5.12it/s]
 14%|█▍        | 310/2248 [00:24<06:10,  5.23it/s]
 14%|█▍        | 312/2248 [00:24<04:31,  7.12it/s]
 14%|█▍        | 313/2248 [00:24<05:25,  5.94it/s]
 14%|█▍        | 314/2248 [00:25<06:28,  4.98it/s]
 14%|█▍        | 315/2248 [00:25<07:01,  4.59it/s]
 14%|█▍        | 318/2248 [00:25<04:03,  7.92it/s]
 14%|█▍        | 320/2248 [00:25<03:42,  8.68it/s]
 14%|█▍        | 322/2248 [00:25<03:12, 10.00it/s]
 14%|█▍        | 324/2248 [00:26<03:57,  8.09it/s]
 15%|█▍        | 326/2248 [00:26<04:16,  7.50it/s]
 15%|█▍        | 327/2248 [00:26<04:42,  6.79it/s]
 15%|█▍        | 329/2248 [00:26<04:30,  7.10it/s]
 15%|█▍        | 331/2248 [00:27<03:39,  8.73it/s]
 15%|█▍        | 333/2248 [00:27<04:46,  6.68it/s]
 15%|█▍        | 337/2248 [00:27<03:02, 10.50it/s]
 15%|█▌        | 339/2248 [00:27<02:46, 11.45it/s]
 15%|█▌        | 343/2248 [00:28<02:50, 11.15it/s]
 15%|█▌        | 345/2248 [00:28<04:35,  6.91it/s]
 15%|█▌        | 347/2248 [00:29<05:03,  6.26it/s]
 15%|█▌        | 348/2248 [00:29<05:46,  5.49it/s]
 16%|█▌        | 349/2248 [00:29<06:31,  4.85it/s]
 16%|█▌        | 350/2248 [00:30<07:15,  4.36it/s]
 16%|█▌        | 351/2248 [00:30<06:22,  4.97it/s]
 16%|█▌        | 353/2248 [00:30<06:01,  5.25it/s]
 16%|█▌        | 356/2248 [00:31<05:09,  6.11it/s]
 16%|█▌        | 358/2248 [00:31<04:05,  7.70it/s]
 16%|█▌        | 362/2248 [00:31<03:34,  8.79it/s]
 16%|█▌        | 364/2248 [00:31<04:02,  7.76it/s]
 16%|█▋        | 366/2248 [00:31<03:24,  9.21it/s]
 16%|█▋        | 368/2248 [00:32<03:53,  8.06it/s]
 16%|█▋        | 370/2248 [00:32<03:20,  9.39it/s]
 17%|█▋        | 372/2248 [00:32<03:53,  8.04it/s]
 17%|█▋        | 375/2248 [00:32<02:49, 11.05it/s]
 17%|█▋        | 381/2248 [00:32<01:38, 18.93it/s]
 17%|█▋        | 385/2248 [00:33<01:47, 17.38it/s]
 17%|█▋        | 388/2248 [00:33<02:45, 11.21it/s]
 17%|█▋        | 390/2248 [00:34<03:26,  9.01it/s]
 17%|█▋        | 392/2248 [00:34<03:56,  7.83it/s]
 18%|█▊        | 394/2248 [00:35<05:16,  5.85it/s]
 18%|█▊        | 395/2248 [00:35<05:57,  5.19it/s]
 18%|█▊        | 396/2248 [00:35<05:28,  5.64it/s]
 18%|█▊        | 398/2248 [00:35<04:14,  7.28it/s]
 18%|█▊        | 401/2248 [00:35<03:00, 10.23it/s]
 18%|█▊        | 404/2248 [00:35<02:18, 13.28it/s]
 18%|█▊        | 407/2248 [00:36<02:15, 13.63it/s]
 18%|█▊        | 409/2248 [00:36<02:14, 13.69it/s]
 18%|█▊        | 411/2248 [00:36<02:05, 14.59it/s]
 19%|█▊        | 417/2248 [00:36<01:18, 23.41it/s]
 19%|█▉        | 422/2248 [00:36<01:05, 27.91it/s]
 19%|█▉        | 426/2248 [00:36<01:23, 21.72it/s]
 19%|█▉        | 430/2248 [00:37<01:12, 25.08it/s]
 19%|█▉        | 433/2248 [00:37<01:18, 23.09it/s]
 19%|█▉        | 436/2248 [00:37<01:44, 17.38it/s]
 20%|█▉        | 439/2248 [00:37<02:14, 13.46it/s]
 20%|█▉        | 441/2248 [00:38<03:14,  9.29it/s]
 20%|█▉        | 443/2248 [00:38<03:00, 10.02it/s]
 20%|█▉        | 446/2248 [00:38<02:37, 11.44it/s]
 20%|█▉        | 449/2248 [00:38<02:09, 13.85it/s]
 20%|██        | 455/2248 [00:38<01:26, 20.61it/s]
 20%|██        | 458/2248 [00:39<02:09, 13.82it/s]
 21%|██        | 462/2248 [00:39<02:06, 14.07it/s]
 21%|██        | 465/2248 [00:39<01:53, 15.78it/s]
 21%|██        | 468/2248 [00:39<01:55, 15.43it/s]
 21%|██        | 470/2248 [00:40<01:58, 15.01it/s]
 21%|██        | 472/2248 [00:40<02:22, 12.50it/s]
 21%|██        | 474/2248 [00:40<02:11, 13.47it/s]
 21%|██        | 476/2248 [00:40<02:11, 13.43it/s]
 21%|██▏       | 479/2248 [00:40<02:08, 13.77it/s]
 21%|██▏       | 481/2248 [00:41<02:27, 12.01it/s]
 21%|██▏       | 483/2248 [00:41<02:23, 12.32it/s]
 22%|██▏       | 485/2248 [00:41<02:12, 13.35it/s]
 22%|██▏       | 487/2248 [00:41<02:05, 14.03it/s]
 22%|██▏       | 490/2248 [00:41<01:41, 17.31it/s]
 22%|██▏       | 495/2248 [00:41<01:16, 22.95it/s]
 22%|██▏       | 498/2248 [00:41<01:14, 23.50it/s]
 22%|██▏       | 501/2248 [00:42<01:36, 18.17it/s]
 22%|██▏       | 504/2248 [00:42<01:42, 17.07it/s]
 23%|██▎       | 506/2248 [00:42<02:00, 14.48it/s]
 23%|██▎       | 508/2248 [00:42<02:07, 13.68it/s]
 23%|██▎       | 510/2248 [00:42<02:08, 13.55it/s]
 23%|██▎       | 514/2248 [00:43<02:12, 13.05it/s]
 23%|██▎       | 516/2248 [00:43<02:06, 13.67it/s]
 23%|██▎       | 519/2248 [00:43<01:53, 15.22it/s]
 23%|██▎       | 525/2248 [00:43<01:15, 22.73it/s]
 24%|██▎       | 529/2248 [00:43<01:06, 25.86it/s]
 24%|██▎       | 532/2248 [00:43<01:05, 26.32it/s]
 24%|██▍       | 535/2248 [00:44<01:35, 17.93it/s]
 24%|██▍       | 539/2248 [00:44<01:21, 21.08it/s]
 24%|██▍       | 544/2248 [00:44<01:06, 25.66it/s]
 24%|██▍       | 548/2248 [00:44<01:02, 27.25it/s]
 25%|██▍       | 552/2248 [00:44<01:14, 22.84it/s]
 25%|██▍       | 555/2248 [00:44<01:20, 21.16it/s]
 25%|██▍       | 558/2248 [00:44<01:15, 22.31it/s]
 25%|██▌       | 563/2248 [00:45<01:02, 26.91it/s]
 25%|██▌       | 566/2248 [00:45<01:22, 20.50it/s]
 25%|██▌       | 569/2248 [00:45<01:19, 21.24it/s]
 25%|██▌       | 572/2248 [00:45<01:40, 16.62it/s]
 26%|██▌       | 574/2248 [00:46<02:12, 12.62it/s]
 26%|██▌       | 576/2248 [00:46<02:18, 12.07it/s]
 26%|██▌       | 581/2248 [00:46<02:22, 11.71it/s]
 26%|██▌       | 583/2248 [00:47<03:06,  8.94it/s]
 26%|██▌       | 585/2248 [00:47<03:29,  7.93it/s]
 26%|██▌       | 586/2248 [00:47<04:30,  6.15it/s]
 26%|██▌       | 588/2248 [00:48<04:35,  6.02it/s]
 26%|██▌       | 590/2248 [00:48<03:47,  7.29it/s]
 26%|██▋       | 592/2248 [00:48<04:21,  6.33it/s]
 26%|██▋       | 593/2248 [00:48<04:08,  6.65it/s]
 27%|██▋       | 598/2248 [00:48<02:12, 12.50it/s]
 27%|██▋       | 603/2248 [00:49<02:05, 13.09it/s]
 27%|██▋       | 605/2248 [00:49<03:26,  7.96it/s]
 27%|██▋       | 607/2248 [00:50<04:33,  6.01it/s]
 27%|██▋       | 609/2248 [00:50<04:38,  5.90it/s]
 27%|██▋       | 610/2248 [00:51<05:11,  5.27it/s]
 27%|██▋       | 612/2248 [00:51<04:11,  6.50it/s]
 27%|██▋       | 618/2248 [00:51<02:08, 12.73it/s]
 28%|██▊       | 622/2248 [00:51<01:47, 15.12it/s]
 28%|██▊       | 628/2248 [00:51<01:16, 21.25it/s]
 28%|██▊       | 631/2248 [00:52<01:38, 16.44it/s]
 28%|██▊       | 636/2248 [00:52<01:15, 21.25it/s]
 28%|██▊       | 640/2248 [00:52<01:06, 24.35it/s]
 29%|██▊       | 645/2248 [00:52<00:56, 28.50it/s]
 29%|██▉       | 651/2248 [00:52<01:00, 26.59it/s]
 29%|██▉       | 655/2248 [00:53<01:57, 13.50it/s]
 29%|██▉       | 658/2248 [00:53<02:16, 11.65it/s]
 29%|██▉       | 661/2248 [00:54<02:28, 10.66it/s]
 29%|██▉       | 663/2248 [00:54<02:20, 11.27it/s]
 30%|██▉       | 669/2248 [00:54<01:36, 16.39it/s]
 30%|██▉       | 672/2248 [00:54<02:07, 12.32it/s]
 30%|██▉       | 674/2248 [00:55<02:16, 11.53it/s]
 30%|███       | 676/2248 [00:55<02:10, 12.06it/s]
 30%|███       | 682/2248 [00:55<01:58, 13.16it/s]
 30%|███       | 684/2248 [00:56<02:35, 10.05it/s]
 31%|███       | 686/2248 [00:56<03:09,  8.25it/s]
 31%|███       | 688/2248 [00:56<03:44,  6.94it/s]
 31%|███       | 690/2248 [00:57<03:12,  8.08it/s]
 31%|███       | 692/2248 [00:57<03:40,  7.07it/s]
 31%|███       | 694/2248 [00:57<03:07,  8.28it/s]
 31%|███       | 696/2248 [00:57<03:13,  8.03it/s]
 31%|███       | 698/2248 [00:58<03:13,  8.02it/s]
 31%|███       | 700/2248 [00:58<02:56,  8.75it/s]
 31%|███       | 702/2248 [00:58<03:33,  7.24it/s]
 31%|███▏      | 704/2248 [00:58<03:42,  6.95it/s]
 31%|███▏      | 707/2248 [00:59<02:36,  9.87it/s]
 32%|███▏      | 710/2248 [00:59<02:16, 11.30it/s]
 32%|███▏      | 712/2248 [00:59<02:40,  9.55it/s]
 32%|███▏      | 714/2248 [00:59<02:36,  9.78it/s]
 32%|███▏      | 716/2248 [00:59<02:25, 10.51it/s]
 32%|███▏      | 718/2248 [01:00<02:11, 11.63it/s]
 32%|███▏      | 723/2248 [01:00<01:22, 18.44it/s]
 32%|███▏      | 726/2248 [01:00<01:32, 16.39it/s]
 32%|███▏      | 728/2248 [01:00<01:43, 14.65it/s]
 32%|███▏      | 730/2248 [01:00<02:16, 11.13it/s]
 33%|███▎      | 734/2248 [01:00<01:37, 15.49it/s]
 33%|███▎      | 737/2248 [01:01<02:46,  9.09it/s]
 33%|███▎      | 739/2248 [01:02<03:52,  6.50it/s]
 33%|███▎      | 742/2248 [01:02<03:31,  7.12it/s]
 33%|███▎      | 744/2248 [01:02<03:47,  6.63it/s]
 33%|███▎      | 748/2248 [01:03<02:32,  9.87it/s]
 33%|███▎      | 752/2248 [01:03<02:27, 10.16it/s]
 34%|███▎      | 754/2248 [01:03<02:16, 10.94it/s]
 34%|███▍      | 760/2248 [01:03<01:26, 17.22it/s]
 34%|███▍      | 763/2248 [01:03<01:22, 18.07it/s]
 34%|███▍      | 770/2248 [01:03<00:58, 25.05it/s]
 34%|███▍      | 774/2248 [01:04<01:34, 15.58it/s]
 35%|███▍      | 777/2248 [01:04<02:02, 11.97it/s]
 35%|███▍      | 779/2248 [01:05<03:05,  7.92it/s]
 35%|███▍      | 782/2248 [01:05<02:29,  9.83it/s]
 35%|███▌      | 788/2248 [01:05<01:35, 15.29it/s]
 35%|███▌      | 791/2248 [01:05<01:28, 16.47it/s]
 35%|███▌      | 794/2248 [01:06<01:44, 13.94it/s]
 35%|███▌      | 797/2248 [01:06<01:51, 12.96it/s]
 36%|███▌      | 799/2248 [01:06<01:54, 12.67it/s]
 36%|███▌      | 801/2248 [01:06<01:45, 13.72it/s]
 36%|███▌      | 803/2248 [01:07<02:02, 11.84it/s]
 36%|███▌      | 805/2248 [01:07<01:53, 12.71it/s]
 36%|███▌      | 807/2248 [01:07<01:47, 13.40it/s]
 36%|███▌      | 811/2248 [01:07<01:18, 18.37it/s]
 36%|███▋      | 817/2248 [01:07<00:57, 24.79it/s]
 36%|███▋      | 820/2248 [01:07<01:00, 23.77it/s]
 37%|███▋      | 824/2248 [01:08<01:20, 17.80it/s]
 37%|███▋      | 828/2248 [01:08<01:07, 21.02it/s]
 37%|███▋      | 834/2248 [01:08<00:50, 28.00it/s]
 37%|███▋      | 840/2248 [01:08<00:40, 34.63it/s]
 38%|███▊      | 848/2248 [01:08<00:34, 41.04it/s]
 38%|███▊      | 854/2248 [01:08<00:31, 44.63it/s]
 38%|███▊      | 861/2248 [01:08<00:27, 50.14it/s]
 39%|███▊      | 867/2248 [01:09<01:00, 22.95it/s]
 39%|███▉      | 872/2248 [01:10<01:37, 14.07it/s]
 39%|███▉      | 876/2248 [01:10<01:26, 15.86it/s]
 39%|███▉      | 879/2248 [01:10<01:44, 13.08it/s]
 39%|███▉      | 884/2248 [01:10<01:21, 16.84it/s]
 39%|███▉      | 887/2248 [01:11<01:36, 14.09it/s]
 40%|███▉      | 890/2248 [01:11<01:26, 15.64it/s]
 40%|███▉      | 893/2248 [01:11<01:27, 15.55it/s]
 40%|███▉      | 896/2248 [01:11<01:51, 12.17it/s]
 40%|███▉      | 898/2248 [01:12<02:02, 11.00it/s]
 40%|████      | 900/2248 [01:12<02:02, 11.00it/s]
 40%|████      | 902/2248 [01:12<02:27,  9.15it/s]
 40%|████      | 904/2248 [01:12<02:29,  9.02it/s]
 40%|████      | 906/2248 [01:13<02:59,  7.48it/s]
 40%|████      | 907/2248 [01:13<03:34,  6.25it/s]
 40%|████      | 908/2248 [01:13<04:21,  5.13it/s]
 40%|████      | 909/2248 [01:14<04:47,  4.66it/s]
 40%|████      | 910/2248 [01:14<05:14,  4.25it/s]
 41%|████      | 911/2248 [01:14<05:42,  3.90it/s]
 41%|████      | 912/2248 [01:15<05:57,  3.74it/s]
 41%|████      | 913/2248 [01:15<06:17,  3.53it/s]
 41%|████      | 914/2248 [01:15<06:05,  3.65it/s]
 41%|████      | 916/2248 [01:15<05:01,  4.42it/s]
 41%|████      | 918/2248 [01:16<03:30,  6.31it/s]
 41%|████      | 919/2248 [01:16<04:06,  5.39it/s]
 41%|████      | 920/2248 [01:16<05:03,  4.37it/s]
 41%|████      | 921/2248 [01:16<04:27,  4.96it/s]
 41%|████      | 924/2248 [01:16<02:33,  8.63it/s]
 41%|████      | 926/2248 [01:17<02:07, 10.40it/s]
 41%|████▏     | 928/2248 [01:17<02:55,  7.51it/s]
 41%|████▏     | 932/2248 [01:17<01:47, 12.26it/s]
 42%|████▏     | 934/2248 [01:17<02:22,  9.22it/s]
 42%|████▏     | 936/2248 [01:18<02:28,  8.82it/s]
 42%|████▏     | 938/2248 [01:18<03:01,  7.21it/s]
 42%|████▏     | 940/2248 [01:18<02:32,  8.57it/s]
 42%|████▏     | 942/2248 [01:18<02:13,  9.81it/s]
 42%|████▏     | 944/2248 [01:19<02:29,  8.71it/s]
 42%|████▏     | 948/2248 [01:19<01:38, 13.19it/s]
 42%|████▏     | 951/2248 [01:19<01:28, 14.73it/s]
 42%|████▏     | 953/2248 [01:19<02:07, 10.17it/s]
 42%|████▏     | 955/2248 [01:20<02:13,  9.71it/s]
 43%|████▎     | 957/2248 [01:20<02:44,  7.85it/s]
 43%|████▎     | 959/2248 [01:20<02:49,  7.62it/s]
 43%|████▎     | 960/2248 [01:20<03:12,  6.69it/s]
 43%|████▎     | 961/2248 [01:21<03:13,  6.66it/s]
 43%|████▎     | 962/2248 [01:21<03:28,  6.16it/s]
 43%|████▎     | 964/2248 [01:21<02:52,  7.43it/s]
 43%|████▎     | 966/2248 [01:21<02:52,  7.43it/s]
 43%|████▎     | 968/2248 [01:21<02:17,  9.28it/s]
 43%|████▎     | 970/2248 [01:22<03:42,  5.74it/s]
 43%|████▎     | 973/2248 [01:22<02:32,  8.38it/s]
 43%|████▎     | 976/2248 [01:22<02:29,  8.53it/s]
 44%|████▎     | 978/2248 [01:23<02:07,  9.94it/s]
 44%|████▎     | 981/2248 [01:23<02:13,  9.46it/s]
 44%|████▎     | 983/2248 [01:23<02:37,  8.06it/s]
 44%|████▍     | 985/2248 [01:24<02:49,  7.44it/s]
 44%|████▍     | 987/2248 [01:24<03:02,  6.93it/s]
 44%|████▍     | 989/2248 [01:24<02:35,  8.09it/s]
 44%|████▍     | 991/2248 [01:24<02:10,  9.64it/s]
 44%|████▍     | 997/2248 [01:24<01:10, 17.69it/s]
 44%|████▍     | 1000/2248 [01:25<01:32, 13.46it/s]
 45%|████▍     | 1003/2248 [01:25<01:54, 10.83it/s]
 45%|████▍     | 1005/2248 [01:26<02:52,  7.22it/s]
 45%|████▍     | 1007/2248 [01:26<03:46,  5.49it/s]
 45%|████▍     | 1008/2248 [01:27<04:05,  5.04it/s]
 45%|████▍     | 1009/2248 [01:27<04:25,  4.66it/s]
 45%|████▌     | 1012/2248 [01:27<02:57,  6.98it/s]
 45%|████▌     | 1018/2248 [01:27<01:34, 13.02it/s]
 45%|████▌     | 1021/2248 [01:27<01:38, 12.40it/s]
 46%|████▌     | 1025/2248 [01:28<01:18, 15.54it/s]
 46%|████▌     | 1030/2248 [01:28<01:09, 17.58it/s]
 46%|████▌     | 1033/2248 [01:28<01:07, 18.07it/s]
 46%|████▌     | 1036/2248 [01:28<01:01, 19.77it/s]
 46%|████▌     | 1039/2248 [01:28<00:57, 20.89it/s]
 46%|████▋     | 1042/2248 [01:28<01:06, 18.17it/s]
 46%|████▋     | 1045/2248 [01:29<01:05, 18.28it/s]
 47%|████▋     | 1050/2248 [01:29<00:49, 24.16it/s]
 47%|████▋     | 1054/2248 [01:29<01:07, 17.62it/s]
 47%|████▋     | 1057/2248 [01:29<01:28, 13.41it/s]
 47%|████▋     | 1059/2248 [01:30<01:24, 14.02it/s]
 47%|████▋     | 1066/2248 [01:30<01:17, 15.35it/s]
 48%|████▊     | 1068/2248 [01:30<01:15, 15.55it/s]
 48%|████▊     | 1070/2248 [01:30<01:35, 12.33it/s]
 48%|████▊     | 1073/2248 [01:31<01:23, 14.09it/s]
 48%|████▊     | 1079/2248 [01:31<01:06, 17.70it/s]
 48%|████▊     | 1082/2248 [01:31<01:03, 18.51it/s]
 48%|████▊     | 1087/2248 [01:31<01:07, 17.11it/s]
 48%|████▊     | 1090/2248 [01:32<01:27, 13.17it/s]
 49%|████▊     | 1092/2248 [01:32<01:24, 13.71it/s]
 49%|████▊     | 1094/2248 [01:32<01:46, 10.81it/s]
 49%|████▉     | 1097/2248 [01:32<01:27, 13.10it/s]
 49%|████▉     | 1104/2248 [01:32<00:52, 21.60it/s]
 49%|████▉     | 1110/2248 [01:32<00:40, 28.24it/s]
 50%|████▉     | 1116/2248 [01:33<00:34, 32.49it/s]
 50%|████▉     | 1123/2248 [01:33<00:27, 40.21it/s]
 50%|█████     | 1129/2248 [01:33<00:26, 41.62it/s]
 50%|█████     | 1134/2248 [01:33<00:25, 43.52it/s]
 51%|█████     | 1140/2248 [01:33<00:23, 47.13it/s]
 51%|█████     | 1146/2248 [01:34<01:12, 15.24it/s]
 51%|█████     | 1150/2248 [01:34<01:11, 15.44it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 326.87it/s]

[[np.int64(0), False, 7], [np.int64(1), False, 11], [np.int64(2), False, 9], [np.int64(3), False, 4], [np.int64(4), False, 8], [np.int64(5), False, 0], [np.int64(6), False, 0], [np.int64(8), False, 1], [np.int64(9), False, 11], [np.int64(10), False, 13], [np.int64(12), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2215, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [13:36<44:50, 54.91s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [13:36<30:47, 38.49s/it]

tensor(12.1083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2550, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2861, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▍ | 254/300 [13:36<14:30, 18.93s/it]

tensor(12.1073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2954, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3098, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 256/300 [13:37<06:50,  9.34s/it]

tensor(12.1057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3251, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3305, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [13:37<02:14,  3.28s/it]

tensor(12.1028, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3344, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3379, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [13:37<01:05,  1.67s/it]

tensor(12.0984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3470, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3562, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [13:37<00:45,  1.20s/it]

tensor(12.0952, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0939, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3658, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [13:38<00:23,  1.53it/s]

tensor(12.0928, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3541, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3586, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [13:38<00:10,  3.30it/s]

tensor(12.0906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3634, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3734, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [13:38<00:07,  4.03it/s]

tensor(12.0889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3792, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3826, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [13:38<00:05,  5.46it/s]

tensor(12.0869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3853, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3929, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [13:39<00:03,  7.01it/s]

tensor(12.0846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4023, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4110, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████▏| 274/300 [13:39<00:03,  7.24it/s]

tensor(12.0822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4156, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0811, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4234, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [13:39<00:02,  7.92it/s]

tensor(12.0797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4349, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4379, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [13:39<00:02,  8.05it/s]

tensor(12.0775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4408, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4436, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [13:40<00:02,  8.03it/s]

tensor(12.0753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4459, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4323, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [13:40<00:02,  7.96it/s]

tensor(12.0730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4348, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4394, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [13:40<00:01,  8.09it/s]

tensor(12.0709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4446, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [13:40<00:01,  8.01it/s]

tensor(12.0688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4499, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4495, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [13:41<00:01,  8.18it/s]

tensor(12.0669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4513, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4524, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [13:41<00:01,  8.02it/s]

tensor(12.0650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4535, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [13:41<00:00,  8.09it/s]

tensor(12.0636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4539, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4570, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [13:41<00:00,  8.19it/s]

tensor(12.0621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4579, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4593, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [13:42<00:00,  8.04it/s]

tensor(12.0606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4595, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4619, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [13:42<00:00,  7.99it/s]

tensor(12.0589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4656, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [13:42<00:00,  2.74s/it]

tensor(12.0574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4648, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0019423961639404297
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 0
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.352017873965
NMI         : 0.475134628466
Runtime     : 843.49 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed0

==============================================================================================================
PRAGA RUN | S2-E18 | seed=1
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 1.495e-16
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:30,  9.87it/s]

tensor(15.9449, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9274, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8049, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:30,  9.61it/s]

tensor(15.9200, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7170, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9105, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8350, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:30,  9.72it/s]

tensor(15.8990, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1381, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8876, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6086, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:29,  9.75it/s]

tensor(15.8760, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2291, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8641, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9860, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:29,  9.79it/s]

tensor(15.8532, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8661, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8425, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8561, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:29,  9.78it/s]

tensor(15.8328, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9455, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8233, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1256, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:29,  9.82it/s]

tensor(15.8144, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3861, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8051, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7202, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:29,  9.79it/s]

tensor(15.7959, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7863, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5794, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:28,  9.85it/s]

tensor(15.7761, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0922, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7649, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6539, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:02<00:28,  9.85it/s]

tensor(15.7525, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2590, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7388, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9033, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:02<00:28,  9.84it/s]

tensor(15.7231, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5829, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7057, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2949, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:27,  9.86it/s]

tensor(15.6865, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0358, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6647, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8025, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:27,  9.83it/s]

tensor(15.6401, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5928, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6133, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4047, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:27,  9.83it/s]

tensor(15.5838, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2353, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5519, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0836, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:03<00:27,  9.86it/s]

tensor(15.5175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9470, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8252, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:27,  9.86it/s]

tensor(15.4427, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7157, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6180, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:27,  9.82it/s]

tensor(15.3625, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5303, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4522, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:26,  9.86it/s]

tensor(15.2793, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3828, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3211, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:26,  9.83it/s]

tensor(15.1929, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2671, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2189, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:04<00:26,  9.83it/s]

tensor(15.1018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1774, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1410, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:26,  9.86it/s]

tensor(15.0053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1107, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9552, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0855, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:26,  9.81it/s]

tensor(14.9044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0659, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0512, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:25,  9.83it/s]

tensor(14.8011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0353, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.83it/s]

tensor(14.6941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:05<00:25,  9.82it/s]

tensor(14.5804, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5210, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.84it/s]

tensor(14.4599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:25,  9.84it/s]

tensor(14.3365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2751, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:24,  9.85it/s]

tensor(14.2140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:24,  9.83it/s]

tensor(14.0963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0421, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:06<00:24,  9.78it/s]

tensor(13.9931, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:24,  9.86it/s]

tensor(13.9101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:23,  9.84it/s]

tensor(13.8379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8028, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:23,  9.85it/s]

tensor(13.7670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:23,  9.83it/s]

tensor(13.6937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:07<00:23,  9.80it/s]

tensor(13.6260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5957, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:07<00:23,  9.80it/s]

tensor(13.5672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5396, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:22,  9.83it/s]

tensor(13.5126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:07<00:22,  9.82it/s]

tensor(13.4592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:07<00:22,  9.81it/s]

tensor(13.4053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:08<00:22,  9.80it/s]

tensor(13.3510, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:22,  9.82it/s]

tensor(13.2988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2738, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:21,  9.84it/s]

tensor(13.2498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:21,  9.83it/s]

tensor(13.2044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:08<00:21,  9.85it/s]

tensor(13.1619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:09<00:21,  9.84it/s]

tensor(13.1215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1021, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:21,  9.82it/s]

tensor(13.0831, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:21,  9.57it/s]

tensor(13.0469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:21,  9.48it/s]

tensor(13.0129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:10<00:21,  9.58it/s]

tensor(12.9810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:10<00:20,  9.70it/s]

tensor(12.9505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([222, 100, 118, 358,  49,  59, 252,  98,  86, 161,  75, 204, 119, 347])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:32, 14.71it/s]
  0%|          | 4/2248 [00:00<02:28, 15.10it/s]
  0%|          | 6/2248 [00:00<02:40, 13.95it/s]
  0%|          | 8/2248 [00:00<02:23, 15.65it/s]
  0%|          | 10/2248 [00:00<03:14, 11.50it/s]
  1%|          | 12/2248 [00:00<02:47, 13.34it/s]
  1%|          | 18/2248 [00:00<01:31, 24.28it/s]
  1%|          | 24/2248 [00:01<01:09, 32.21it/s]
  1%|▏         | 30/2248 [00:01<00:58, 38.17it/s]
  2%|▏         | 35/2248 [00:01<01:08, 32.39it/s]
  2%|▏         | 39/2248 [00:01<01:22, 26.76it/s]
  2%|▏         | 43/2248 [00:01<01:21, 27.20it/s]
  2%|▏         | 46/2248 [00:01<01:23, 26.25it/s]
  2%|▏         | 49/2248 [00:02<01:32, 23.68it/s]
  2%|▏         | 52/2248 [00:02<01:37, 22.55it/s]
  2%|▏         | 56/2248 [00:02<01:29, 24.43it/s]
  3%|▎         | 59/2248 [00:02<01:28, 24.86it/s]
  3%|▎         | 62/2248 [00:02<01:29, 24.48it/s]
  3%|▎         | 65/2248 [00:02<01:44, 20.81it/s]
  3%|▎         | 69/2248 [00:02<01:27, 24.93it/s]
  3%|▎         | 72/2248 [00:03<01:30, 23.95it/s]
  3%|▎         | 75/2248 [00:03<02:07, 17.01it/s]
  3%|▎         | 78/2248 [00:03<02:25, 14.96it/s]
  4%|▎         | 80/2248 [00:03<02:18, 15.68it/s]
  4%|▎         | 83/2248 [00:03<02:32, 14.23it/s]
  4%|▍         | 85/2248 [00:04<02:36, 13.81it/s]
  4%|▍         | 87/2248 [00:04<02:58, 12.10it/s]
  4%|▍         | 90/2248 [00:04<02:40, 13.49it/s]
  4%|▍         | 93/2248 [00:04<02:18, 15.56it/s]
  4%|▍         | 95/2248 [00:04<02:37, 13.69it/s]
  4%|▍         | 97/2248 [00:05<02:50, 12.63it/s]
  4%|▍         | 99/2248 [00:05<02:42, 13.22it/s]
  4%|▍         | 101/2248 [00:05<02:32, 14.12it/s]
  5%|▍         | 103/2248 [00:05<02:33, 13.95it/s]
  5%|▍         | 105/2248 [00:05<02:53, 12.33it/s]
  5%|▍         | 107/2248 [00:05<02:39, 13.42it/s]
  5%|▍         | 111/2248 [00:06<02:27, 14.52it/s]
  5%|▌         | 113/2248 [00:06<03:03, 11.67it/s]
  5%|▌         | 115/2248 [00:06<03:01, 11.73it/s]
  5%|▌         | 117/2248 [00:06<03:29, 10.17it/s]
  5%|▌         | 119/2248 [00:06<03:25, 10.34it/s]
  5%|▌         | 121/2248 [00:07<03:40,  9.66it/s]
  5%|▌         | 123/2248 [00:07<03:52,  9.15it/s]
  6%|▌         | 125/2248 [00:07<03:36,  9.81it/s]
  6%|▌         | 127/2248 [00:07<04:08,  8.54it/s]
  6%|▌         | 129/2248 [00:08<03:36,  9.79it/s]
  6%|▌         | 131/2248 [00:08<03:13, 10.93it/s]
  6%|▌         | 133/2248 [00:08<03:54,  9.03it/s]
  6%|▌         | 135/2248 [00:08<04:08,  8.49it/s]
  6%|▌         | 136/2248 [00:08<04:06,  8.56it/s]
  6%|▌         | 138/2248 [00:09<04:11,  8.40it/s]
  6%|▌         | 139/2248 [00:09<04:09,  8.44it/s]
  6%|▌         | 140/2248 [00:09<04:48,  7.30it/s]
  6%|▋         | 141/2248 [00:09<05:30,  6.38it/s]
  6%|▋         | 143/2248 [00:09<04:14,  8.28it/s]
  6%|▋         | 145/2248 [00:09<03:47,  9.26it/s]
  7%|▋         | 148/2248 [00:10<02:47, 12.52it/s]
  7%|▋         | 151/2248 [00:10<02:26, 14.27it/s]
  7%|▋         | 153/2248 [00:10<02:30, 13.88it/s]
  7%|▋         | 156/2248 [00:10<02:58, 11.70it/s]
  7%|▋         | 158/2248 [00:11<03:54,  8.90it/s]
  7%|▋         | 160/2248 [00:11<04:25,  7.87it/s]
  7%|▋         | 162/2248 [00:11<04:24,  7.87it/s]
  7%|▋         | 164/2248 [00:11<03:41,  9.39it/s]
  7%|▋         | 166/2248 [00:12<04:23,  7.90it/s]
  7%|▋         | 168/2248 [00:12<04:15,  8.15it/s]
  8%|▊         | 169/2248 [00:12<05:26,  6.37it/s]
  8%|▊         | 171/2248 [00:12<04:14,  8.15it/s]
  8%|▊         | 173/2248 [00:12<03:31,  9.83it/s]
  8%|▊         | 176/2248 [00:13<04:21,  7.91it/s]
  8%|▊         | 178/2248 [00:13<05:07,  6.73it/s]
  8%|▊         | 179/2248 [00:14<05:26,  6.33it/s]
  8%|▊         | 180/2248 [00:14<05:41,  6.05it/s]
  8%|▊         | 183/2248 [00:14<05:25,  6.34it/s]
  8%|▊         | 185/2248 [00:14<05:04,  6.77it/s]
  8%|▊         | 187/2248 [00:15<05:46,  5.96it/s]
  8%|▊         | 188/2248 [00:15<05:22,  6.40it/s]
  8%|▊         | 189/2248 [00:15<06:55,  4.95it/s]
  8%|▊         | 190/2248 [00:16<06:52,  4.99it/s]
  9%|▊         | 193/2248 [00:16<05:10,  6.61it/s]
  9%|▊         | 195/2248 [00:16<05:05,  6.72it/s]
  9%|▉         | 198/2248 [00:16<03:45,  9.10it/s]
  9%|▉         | 200/2248 [00:17<03:53,  8.77it/s]
  9%|▉         | 201/2248 [00:17<04:28,  7.63it/s]
  9%|▉         | 202/2248 [00:17<05:34,  6.11it/s]
  9%|▉         | 204/2248 [00:17<04:15,  7.99it/s]
  9%|▉         | 206/2248 [00:17<03:57,  8.60it/s]
  9%|▉         | 208/2248 [00:18<04:28,  7.61it/s]
  9%|▉         | 209/2248 [00:18<04:59,  6.81it/s]
  9%|▉         | 210/2248 [00:18<05:50,  5.81it/s]
  9%|▉         | 211/2248 [00:18<06:05,  5.57it/s]
  9%|▉         | 212/2248 [00:19<06:08,  5.53it/s]
 10%|▉         | 214/2248 [00:19<04:40,  7.26it/s]
 10%|▉         | 216/2248 [00:19<03:42,  9.12it/s]
 10%|▉         | 218/2248 [00:19<03:13, 10.50it/s]
 10%|▉         | 222/2248 [00:19<03:13, 10.45it/s]
 10%|▉         | 224/2248 [00:19<02:51, 11.78it/s]
 10%|█         | 227/2248 [00:20<02:14, 15.05it/s]
 10%|█         | 229/2248 [00:20<02:20, 14.35it/s]
 10%|█         | 232/2248 [00:20<01:55, 17.44it/s]
 11%|█         | 237/2248 [00:20<01:24, 23.87it/s]
 11%|█         | 240/2248 [00:20<01:22, 24.39it/s]
 11%|█         | 247/2248 [00:20<00:57, 35.06it/s]
 11%|█         | 251/2248 [00:21<01:48, 18.33it/s]
 11%|█▏        | 255/2248 [00:21<01:35, 20.89it/s]
 12%|█▏        | 262/2248 [00:21<01:47, 18.51it/s]
 12%|█▏        | 265/2248 [00:22<02:51, 11.55it/s]
 12%|█▏        | 267/2248 [00:22<03:25,  9.63it/s]
 12%|█▏        | 270/2248 [00:23<03:21,  9.80it/s]
 12%|█▏        | 272/2248 [00:23<03:01, 10.87it/s]
 12%|█▏        | 274/2248 [00:23<03:40,  8.96it/s]
 12%|█▏        | 276/2248 [00:23<03:36,  9.09it/s]
 12%|█▏        | 278/2248 [00:23<03:43,  8.80it/s]
 12%|█▏        | 280/2248 [00:24<04:26,  7.38it/s]
 13%|█▎        | 282/2248 [00:24<04:18,  7.61it/s]
 13%|█▎        | 284/2248 [00:24<04:43,  6.93it/s]
 13%|█▎        | 286/2248 [00:25<05:26,  6.00it/s]
 13%|█▎        | 287/2248 [00:25<05:29,  5.94it/s]
 13%|█▎        | 289/2248 [00:25<04:29,  7.28it/s]
 13%|█▎        | 290/2248 [00:25<04:18,  7.58it/s]
 13%|█▎        | 291/2248 [00:25<04:42,  6.93it/s]
 13%|█▎        | 292/2248 [00:26<04:25,  7.38it/s]
 13%|█▎        | 294/2248 [00:26<03:53,  8.35it/s]
 13%|█▎        | 298/2248 [00:26<03:41,  8.82it/s]
 13%|█▎        | 299/2248 [00:26<04:25,  7.35it/s]
 13%|█▎        | 301/2248 [00:27<03:56,  8.24it/s]
 13%|█▎        | 302/2248 [00:27<04:20,  7.46it/s]
 14%|█▎        | 304/2248 [00:27<04:15,  7.61it/s]
 14%|█▎        | 305/2248 [00:27<04:53,  6.63it/s]
 14%|█▎        | 306/2248 [00:28<05:40,  5.70it/s]
 14%|█▎        | 307/2248 [00:28<07:10,  4.51it/s]
 14%|█▎        | 308/2248 [00:28<06:32,  4.95it/s]
 14%|█▍        | 310/2248 [00:28<04:44,  6.82it/s]
 14%|█▍        | 312/2248 [00:28<04:18,  7.48it/s]
 14%|█▍        | 314/2248 [00:29<04:43,  6.82it/s]
 14%|█▍        | 315/2248 [00:29<04:52,  6.60it/s]
 14%|█▍        | 317/2248 [00:29<03:44,  8.60it/s]
 14%|█▍        | 319/2248 [00:29<03:08, 10.24it/s]
 14%|█▍        | 321/2248 [00:29<03:16,  9.82it/s]
 14%|█▍        | 323/2248 [00:30<03:34,  8.97it/s]
 14%|█▍        | 325/2248 [00:30<03:19,  9.64it/s]
 15%|█▍        | 327/2248 [00:30<03:21,  9.52it/s]
 15%|█▍        | 329/2248 [00:30<04:02,  7.92it/s]
 15%|█▍        | 332/2248 [00:31<04:07,  7.75it/s]
 15%|█▍        | 334/2248 [00:31<03:30,  9.11it/s]
 15%|█▍        | 336/2248 [00:31<03:33,  8.96it/s]
 15%|█▌        | 339/2248 [00:31<03:17,  9.67it/s]
 15%|█▌        | 341/2248 [00:32<03:46,  8.42it/s]
 15%|█▌        | 343/2248 [00:32<04:39,  6.83it/s]
 15%|█▌        | 344/2248 [00:32<05:03,  6.27it/s]
 15%|█▌        | 345/2248 [00:33<05:29,  5.78it/s]
 15%|█▌        | 346/2248 [00:33<06:23,  4.96it/s]
 15%|█▌        | 347/2248 [00:33<06:30,  4.86it/s]
 15%|█▌        | 348/2248 [00:33<06:25,  4.93it/s]
 16%|█▌        | 349/2248 [00:34<05:46,  5.48it/s]
 16%|█▌        | 350/2248 [00:34<05:49,  5.42it/s]
 16%|█▌        | 352/2248 [00:34<03:58,  7.94it/s]
 16%|█▌        | 353/2248 [00:34<04:31,  6.97it/s]
 16%|█▌        | 354/2248 [00:34<06:04,  5.19it/s]
 16%|█▌        | 355/2248 [00:35<05:42,  5.53it/s]
 16%|█▌        | 356/2248 [00:35<06:18,  5.00it/s]
 16%|█▌        | 358/2248 [00:35<04:24,  7.15it/s]
 16%|█▌        | 360/2248 [00:35<03:25,  9.20it/s]
 16%|█▌        | 362/2248 [00:35<02:50, 11.09it/s]
 16%|█▌        | 364/2248 [00:35<03:16,  9.56it/s]
 16%|█▋        | 366/2248 [00:36<03:27,  9.09it/s]
 16%|█▋        | 368/2248 [00:36<04:20,  7.23it/s]
 17%|█▋        | 371/2248 [00:36<04:19,  7.22it/s]
 17%|█▋        | 373/2248 [00:37<04:48,  6.49it/s]
 17%|█▋        | 374/2248 [00:37<04:50,  6.46it/s]
 17%|█▋        | 377/2248 [00:37<03:49,  8.15it/s]
 17%|█▋        | 378/2248 [00:37<04:11,  7.44it/s]
 17%|█▋        | 380/2248 [00:38<03:24,  9.13it/s]
 17%|█▋        | 382/2248 [00:38<02:50, 10.94it/s]
 17%|█▋        | 384/2248 [00:38<03:15,  9.56it/s]
 17%|█▋        | 386/2248 [00:38<02:51, 10.85it/s]
 17%|█▋        | 388/2248 [00:38<03:11,  9.73it/s]
 17%|█▋        | 390/2248 [00:39<03:42,  8.36it/s]
 17%|█▋        | 391/2248 [00:39<04:36,  6.71it/s]
 17%|█▋        | 393/2248 [00:39<04:35,  6.73it/s]
 18%|█▊        | 394/2248 [00:39<04:32,  6.80it/s]
 18%|█▊        | 396/2248 [00:39<03:40,  8.39it/s]
 18%|█▊        | 399/2248 [00:40<02:34, 11.99it/s]
 18%|█▊        | 402/2248 [00:40<02:05, 14.74it/s]
 18%|█▊        | 404/2248 [00:40<01:56, 15.80it/s]
 18%|█▊        | 407/2248 [00:40<01:41, 18.16it/s]
 18%|█▊        | 411/2248 [00:40<01:20, 22.91it/s]
 18%|█▊        | 414/2248 [00:40<01:29, 20.42it/s]
 19%|█▊        | 418/2248 [00:40<01:16, 24.02it/s]
 19%|█▉        | 422/2248 [00:40<01:05, 27.83it/s]
 19%|█▉        | 426/2248 [00:41<01:10, 25.99it/s]
 19%|█▉        | 429/2248 [00:41<01:09, 26.36it/s]
 19%|█▉        | 432/2248 [00:41<01:10, 25.80it/s]
 19%|█▉        | 436/2248 [00:41<01:57, 15.42it/s]
 20%|█▉        | 439/2248 [00:42<03:00, 10.04it/s]
 20%|█▉        | 441/2248 [00:42<03:42,  8.14it/s]
 20%|█▉        | 444/2248 [00:43<03:14,  9.28it/s]
 20%|█▉        | 446/2248 [00:43<03:19,  9.02it/s]
 20%|█▉        | 448/2248 [00:43<03:03,  9.82it/s]
 20%|██        | 450/2248 [00:43<03:13,  9.30it/s]
 20%|██        | 453/2248 [00:43<03:16,  9.15it/s]
 20%|██        | 455/2248 [00:44<03:32,  8.44it/s]
 20%|██        | 456/2248 [00:44<03:46,  7.93it/s]
 20%|██        | 457/2248 [00:44<03:47,  7.86it/s]
 20%|██        | 459/2248 [00:44<03:28,  8.57it/s]
 21%|██        | 461/2248 [00:44<02:59,  9.95it/s]
 21%|██        | 463/2248 [00:45<03:14,  9.15it/s]
 21%|██        | 465/2248 [00:45<02:46, 10.73it/s]
 21%|██        | 467/2248 [00:45<02:38, 11.25it/s]
 21%|██        | 469/2248 [00:45<02:27, 12.08it/s]
 21%|██        | 471/2248 [00:45<02:36, 11.32it/s]
 21%|██        | 473/2248 [00:46<03:08,  9.41it/s]
 21%|██        | 475/2248 [00:46<03:26,  8.60it/s]
 21%|██        | 476/2248 [00:46<03:33,  8.29it/s]
 21%|██        | 477/2248 [00:46<03:46,  7.81it/s]
 21%|██▏       | 478/2248 [00:46<04:19,  6.81it/s]
 21%|██▏       | 479/2248 [00:47<04:39,  6.34it/s]
 21%|██▏       | 480/2248 [00:47<04:54,  6.01it/s]
 21%|██▏       | 481/2248 [00:47<06:02,  4.88it/s]
 21%|██▏       | 483/2248 [00:47<04:11,  7.02it/s]
 22%|██▏       | 485/2248 [00:48<04:38,  6.32it/s]
 22%|██▏       | 486/2248 [00:48<04:59,  5.89it/s]
 22%|██▏       | 487/2248 [00:48<05:31,  5.31it/s]
 22%|██▏       | 488/2248 [00:48<05:20,  5.49it/s]
 22%|██▏       | 491/2248 [00:48<03:14,  9.04it/s]
 22%|██▏       | 493/2248 [00:48<02:39, 11.02it/s]
 22%|██▏       | 495/2248 [00:49<02:58,  9.82it/s]
 22%|██▏       | 497/2248 [00:49<02:31, 11.55it/s]
 22%|██▏       | 499/2248 [00:49<02:34, 11.34it/s]
 22%|██▏       | 501/2248 [00:49<02:35, 11.26it/s]
 22%|██▏       | 503/2248 [00:49<02:59,  9.75it/s]
 23%|██▎       | 506/2248 [00:49<02:11, 13.22it/s]
 23%|██▎       | 509/2248 [00:50<02:15, 12.82it/s]
 23%|██▎       | 511/2248 [00:50<02:03, 14.09it/s]
 23%|██▎       | 513/2248 [00:50<03:09,  9.17it/s]
 23%|██▎       | 515/2248 [00:51<03:48,  7.59it/s]
 23%|██▎       | 517/2248 [00:51<04:20,  6.66it/s]
 23%|██▎       | 518/2248 [00:51<04:36,  6.26it/s]
 23%|██▎       | 519/2248 [00:51<04:52,  5.92it/s]
 23%|██▎       | 521/2248 [00:52<03:45,  7.64it/s]
 23%|██▎       | 527/2248 [00:52<02:04, 13.79it/s]
 24%|██▎       | 529/2248 [00:52<01:56, 14.73it/s]
 24%|██▎       | 533/2248 [00:52<01:47, 15.95it/s]
 24%|██▍       | 535/2248 [00:52<01:55, 14.83it/s]
 24%|██▍       | 539/2248 [00:52<01:30, 18.86it/s]
 24%|██▍       | 545/2248 [00:53<01:02, 27.28it/s]
 24%|██▍       | 549/2248 [00:53<00:56, 30.08it/s]
 25%|██▍       | 554/2248 [00:53<00:49, 34.45it/s]
 25%|██▍       | 558/2248 [00:53<01:08, 24.73it/s]
 25%|██▌       | 562/2248 [00:53<01:14, 22.56it/s]
 25%|██▌       | 565/2248 [00:53<01:11, 23.67it/s]
 25%|██▌       | 571/2248 [00:54<01:29, 18.76it/s]
 26%|██▌       | 574/2248 [00:54<02:27, 11.34it/s]
 26%|██▌       | 576/2248 [00:54<02:18, 12.08it/s]
 26%|██▌       | 578/2248 [00:55<02:27, 11.35it/s]
 26%|██▌       | 580/2248 [00:55<02:46, 10.02it/s]
 26%|██▌       | 582/2248 [00:55<03:24,  8.16it/s]
 26%|██▌       | 584/2248 [00:56<03:28,  7.97it/s]
 26%|██▌       | 586/2248 [00:56<03:54,  7.10it/s]
 26%|██▌       | 588/2248 [00:56<04:30,  6.13it/s]
 26%|██▋       | 591/2248 [00:57<03:17,  8.38it/s]
 26%|██▋       | 593/2248 [00:57<03:14,  8.50it/s]
 26%|██▋       | 595/2248 [00:57<03:09,  8.70it/s]
 27%|██▋       | 597/2248 [00:57<02:40, 10.29it/s]
 27%|██▋       | 599/2248 [00:57<02:55,  9.38it/s]
 27%|██▋       | 601/2248 [00:58<03:25,  8.00it/s]
 27%|██▋       | 603/2248 [00:58<03:52,  7.08it/s]
 27%|██▋       | 604/2248 [00:58<04:36,  5.95it/s]
 27%|██▋       | 605/2248 [00:59<04:48,  5.70it/s]
 27%|██▋       | 606/2248 [00:59<05:40,  4.82it/s]
 27%|██▋       | 607/2248 [00:59<05:32,  4.93it/s]
 27%|██▋       | 608/2248 [00:59<05:15,  5.19it/s]
 27%|██▋       | 609/2248 [01:00<06:15,  4.37it/s]
 27%|██▋       | 610/2248 [01:00<05:45,  4.75it/s]
 27%|██▋       | 613/2248 [01:00<03:44,  7.27it/s]
 27%|██▋       | 616/2248 [01:00<02:41, 10.09it/s]
 27%|██▋       | 618/2248 [01:00<02:19, 11.66it/s]
 28%|██▊       | 620/2248 [01:00<02:15, 11.99it/s]
 28%|██▊       | 622/2248 [01:01<02:11, 12.37it/s]
 28%|██▊       | 625/2248 [01:01<01:50, 14.67it/s]
 28%|██▊       | 627/2248 [01:01<01:47, 15.08it/s]
 28%|██▊       | 629/2248 [01:01<02:23, 11.26it/s]
 28%|██▊       | 631/2248 [01:01<02:41,  9.99it/s]
 28%|██▊       | 633/2248 [01:01<02:22, 11.36it/s]
 28%|██▊       | 636/2248 [01:02<02:14, 11.96it/s]
 28%|██▊       | 638/2248 [01:02<02:23, 11.20it/s]
 29%|██▊       | 641/2248 [01:02<02:04, 12.91it/s]
 29%|██▊       | 643/2248 [01:02<01:53, 14.09it/s]
 29%|██▊       | 645/2248 [01:02<02:10, 12.29it/s]
 29%|██▉       | 647/2248 [01:03<02:03, 12.96it/s]
 29%|██▉       | 650/2248 [01:03<02:00, 13.22it/s]
 29%|██▉       | 652/2248 [01:03<03:19,  8.00it/s]
 29%|██▉       | 654/2248 [01:04<03:22,  7.86it/s]
 29%|██▉       | 656/2248 [01:04<02:52,  9.24it/s]
 29%|██▉       | 658/2248 [01:04<03:06,  8.51it/s]
 29%|██▉       | 660/2248 [01:04<03:13,  8.19it/s]
 29%|██▉       | 661/2248 [01:04<03:33,  7.43it/s]
 29%|██▉       | 663/2248 [01:05<03:46,  6.99it/s]
 30%|██▉       | 664/2248 [01:05<04:05,  6.46it/s]
 30%|██▉       | 665/2248 [01:05<04:24,  5.99it/s]
 30%|██▉       | 666/2248 [01:05<04:46,  5.52it/s]
 30%|██▉       | 669/2248 [01:06<02:58,  8.87it/s]
 30%|██▉       | 671/2248 [01:06<03:37,  7.25it/s]
 30%|███       | 676/2248 [01:06<01:58, 13.28it/s]
 30%|███       | 679/2248 [01:07<02:46,  9.40it/s]
 30%|███       | 681/2248 [01:07<02:53,  9.01it/s]
 30%|███       | 683/2248 [01:08<04:35,  5.68it/s]
 30%|███       | 685/2248 [01:08<06:03,  4.30it/s]
 31%|███       | 686/2248 [01:09<06:39,  3.91it/s]
 31%|███       | 687/2248 [01:09<06:33,  3.97it/s]
 31%|███       | 688/2248 [01:09<06:00,  4.33it/s]
 31%|███       | 690/2248 [01:09<04:17,  6.04it/s]
 31%|███       | 691/2248 [01:09<05:04,  5.12it/s]
 31%|███       | 692/2248 [01:10<04:55,  5.26it/s]
 31%|███       | 694/2248 [01:10<04:23,  5.90it/s]
 31%|███       | 695/2248 [01:10<04:41,  5.52it/s]
 31%|███       | 697/2248 [01:10<03:26,  7.50it/s]
 31%|███       | 698/2248 [01:10<03:51,  6.68it/s]
 31%|███       | 699/2248 [01:11<03:55,  6.57it/s]
 31%|███       | 701/2248 [01:11<02:54,  8.88it/s]
 31%|███▏      | 703/2248 [01:11<03:50,  6.71it/s]
 31%|███▏      | 704/2248 [01:11<03:50,  6.70it/s]
 31%|███▏      | 706/2248 [01:12<03:26,  7.47it/s]
 31%|███▏      | 708/2248 [01:12<02:42,  9.47it/s]
 32%|███▏      | 710/2248 [01:12<03:05,  8.28it/s]
 32%|███▏      | 712/2248 [01:13<04:36,  5.56it/s]
 32%|███▏      | 713/2248 [01:13<05:28,  4.67it/s]
 32%|███▏      | 714/2248 [01:13<05:06,  5.00it/s]
 32%|███▏      | 715/2248 [01:13<06:10,  4.14it/s]
 32%|███▏      | 716/2248 [01:14<07:01,  3.64it/s]
 32%|███▏      | 717/2248 [01:14<06:19,  4.04it/s]
 32%|███▏      | 719/2248 [01:14<04:27,  5.71it/s]
 32%|███▏      | 721/2248 [01:14<03:37,  7.02it/s]
 32%|███▏      | 723/2248 [01:14<02:55,  8.70it/s]
 32%|███▏      | 726/2248 [01:15<02:38,  9.60it/s]
 32%|███▏      | 728/2248 [01:15<04:04,  6.22it/s]
 32%|███▏      | 730/2248 [01:15<03:17,  7.70it/s]
 33%|███▎      | 732/2248 [01:16<04:27,  5.66it/s]
 33%|███▎      | 733/2248 [01:16<04:20,  5.83it/s]
 33%|███▎      | 734/2248 [01:16<04:23,  5.74it/s]
 33%|███▎      | 735/2248 [01:17<05:08,  4.90it/s]
 33%|███▎      | 736/2248 [01:17<05:54,  4.27it/s]
 33%|███▎      | 737/2248 [01:17<06:05,  4.13it/s]
 33%|███▎      | 738/2248 [01:17<05:33,  4.53it/s]
 33%|███▎      | 741/2248 [01:18<03:12,  7.84it/s]
 33%|███▎      | 743/2248 [01:18<04:30,  5.56it/s]
 33%|███▎      | 744/2248 [01:18<04:42,  5.33it/s]
 33%|███▎      | 746/2248 [01:18<03:30,  7.14it/s]
 33%|███▎      | 748/2248 [01:19<02:55,  8.56it/s]
 33%|███▎      | 750/2248 [01:19<02:36,  9.57it/s]
 33%|███▎      | 752/2248 [01:19<02:34,  9.67it/s]
 34%|███▎      | 754/2248 [01:19<02:41,  9.23it/s]
 34%|███▎      | 756/2248 [01:19<02:48,  8.88it/s]
 34%|███▎      | 757/2248 [01:20<02:59,  8.33it/s]
 34%|███▍      | 760/2248 [01:20<02:10, 11.40it/s]
 34%|███▍      | 762/2248 [01:20<02:21, 10.48it/s]
 34%|███▍      | 764/2248 [01:20<02:39,  9.32it/s]
 34%|███▍      | 767/2248 [01:20<02:26, 10.09it/s]
 34%|███▍      | 770/2248 [01:21<01:55, 12.75it/s]
 34%|███▍      | 772/2248 [01:21<02:07, 11.61it/s]
 34%|███▍      | 774/2248 [01:21<02:24, 10.19it/s]
 35%|███▍      | 776/2248 [01:21<02:48,  8.74it/s]
 35%|███▍      | 778/2248 [01:22<02:51,  8.58it/s]
 35%|███▍      | 780/2248 [01:22<02:27,  9.94it/s]
 35%|███▍      | 782/2248 [01:22<02:33,  9.55it/s]
 35%|███▍      | 784/2248 [01:22<03:28,  7.02it/s]
 35%|███▍      | 786/2248 [01:23<02:59,  8.13it/s]
 35%|███▌      | 788/2248 [01:23<02:37,  9.25it/s]
 35%|███▌      | 790/2248 [01:23<02:52,  8.43it/s]
 35%|███▌      | 791/2248 [01:23<03:02,  7.98it/s]
 35%|███▌      | 792/2248 [01:23<03:40,  6.62it/s]
 35%|███▌      | 794/2248 [01:24<03:04,  7.88it/s]
 35%|███▌      | 795/2248 [01:24<03:19,  7.28it/s]
 35%|███▌      | 797/2248 [01:24<02:54,  8.29it/s]
 36%|███▌      | 799/2248 [01:24<02:34,  9.40it/s]
 36%|███▌      | 800/2248 [01:24<03:02,  7.94it/s]
 36%|███▌      | 802/2248 [01:24<02:25,  9.93it/s]
 36%|███▌      | 804/2248 [01:25<02:05, 11.51it/s]
 36%|███▌      | 806/2248 [01:25<01:50, 13.06it/s]
 36%|███▌      | 808/2248 [01:25<01:47, 13.34it/s]
 36%|███▌      | 811/2248 [01:25<01:50, 12.99it/s]
 36%|███▌      | 813/2248 [01:25<02:24,  9.91it/s]
 36%|███▋      | 815/2248 [01:26<03:08,  7.59it/s]
 36%|███▋      | 816/2248 [01:26<03:27,  6.91it/s]
 36%|███▋      | 818/2248 [01:26<03:01,  7.90it/s]
 36%|███▋      | 820/2248 [01:26<02:26,  9.73it/s]
 37%|███▋      | 824/2248 [01:26<01:42, 13.85it/s]
 37%|███▋      | 826/2248 [01:27<02:13, 10.67it/s]
 37%|███▋      | 828/2248 [01:27<01:59, 11.87it/s]
 37%|███▋      | 830/2248 [01:27<01:51, 12.67it/s]
 37%|███▋      | 832/2248 [01:27<02:01, 11.62it/s]
 37%|███▋      | 835/2248 [01:27<01:35, 14.73it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 338.98it/s]

[[np.int64(0), False, 11], [np.int64(1), False, 13], [np.int64(2), False, 10], [np.int64(3), False, 13], [np.int64(4), False, 8], [np.int64(5), False, 0], [np.int64(6), False, 11], [np.int64(7), False, 12], [np.int64(9), False, 2]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9218, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6197, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:18<4:06:48, 74.41s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:18<2:52:03, 52.14s/it]

tensor(12.9075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8953, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7616, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [04:18<1:23:39, 25.61s/it]

tensor(12.8869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8003, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8795, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [04:18<40:46, 12.61s/it]

tensor(12.8792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9247, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9842, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [04:18<19:58,  6.24s/it]

tensor(12.8726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0188, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8677, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0610, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [04:19<09:53,  3.12s/it]

tensor(12.8620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0890, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1224, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:19<03:35,  1.15s/it]

tensor(12.8499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1614, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1844, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 114/300 [04:19<02:36,  1.19it/s]

tensor(12.8402, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2221, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2432, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [04:20<01:07,  2.71it/s]

tensor(12.8302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2668, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2865, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 118/300 [04:20<00:53,  3.40it/s]

tensor(12.8160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3185, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3535, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:20<00:37,  4.85it/s]

tensor(12.7974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3816, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7877, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4171, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:20<00:29,  6.11it/s]

tensor(12.7784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4460, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4519, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [04:20<00:25,  6.93it/s]

tensor(12.7586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4707, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4836, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [04:21<00:23,  7.38it/s]

tensor(12.7355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4787, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7233, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4850, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:21<00:21,  7.92it/s]

tensor(12.7115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4972, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5211, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:21<00:20,  8.08it/s]

tensor(12.6905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5479, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5673, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:21<00:20,  8.12it/s]

tensor(12.6736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5958, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6107, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [04:22<00:20,  8.02it/s]

tensor(12.6609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6466, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6843, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:22<00:20,  7.95it/s]

tensor(12.6500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7247, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6444, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7644, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [04:22<00:20,  8.01it/s]

tensor(12.6385, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8009, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8497, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [04:22<00:20,  7.87it/s]

tensor(12.6265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8861, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6202, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9264, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 142/300 [04:23<00:19,  7.99it/s]

tensor(12.6141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9398, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5865, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [04:23<00:19,  7.88it/s]

tensor(12.6013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6215, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7422, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [04:23<00:19,  7.95it/s]

tensor(12.5956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8361, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9000, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 148/300 [04:23<00:19,  7.95it/s]

tensor(12.5919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0366, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9263, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0370, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9085, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:24<00:18,  7.92it/s]

tensor(12.5761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0367, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9136, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([151, 360,  78, 202, 144, 121,  68, 211,  53,  63, 100, 117, 207, 373])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:06, 17.73it/s]
  0%|          | 8/2248 [00:00<00:59, 37.66it/s]
  1%|          | 14/2248 [00:00<00:47, 46.84it/s]
  1%|          | 21/2248 [00:00<00:40, 54.41it/s]
  1%|          | 27/2248 [00:00<00:39, 56.27it/s]
  1%|▏         | 33/2248 [00:00<00:48, 45.59it/s]
  2%|▏         | 40/2248 [00:00<00:42, 51.51it/s]
  2%|▏         | 46/2248 [00:00<00:42, 52.06it/s]
  2%|▏         | 52/2248 [00:01<00:43, 50.12it/s]
  3%|▎         | 58/2248 [00:01<00:43, 50.17it/s]
  3%|▎         | 64/2248 [00:01<00:45, 48.20it/s]
  3%|▎         | 69/2248 [00:01<00:46, 47.02it/s]
  3%|▎         | 74/2248 [00:01<00:46, 47.07it/s]
  4%|▎         | 79/2248 [00:02<01:50, 19.66it/s]
  4%|▎         | 83/2248 [00:02<01:40, 21.46it/s]
  4%|▍         | 87/2248 [00:02<01:38, 21.96it/s]
  4%|▍         | 91/2248 [00:02<01:58, 18.16it/s]
  4%|▍         | 95/2248 [00:03<02:15, 15.93it/s]
  4%|▍         | 98/2248 [00:03<03:09, 11.32it/s]
  4%|▍         | 100/2248 [00:04<04:06,  8.71it/s]
  5%|▍         | 102/2248 [00:04<03:42,  9.66it/s]
  5%|▍         | 104/2248 [00:04<05:18,  6.72it/s]
  5%|▍         | 107/2248 [00:05<04:12,  8.47it/s]
  5%|▍         | 111/2248 [00:05<03:30, 10.14it/s]
  5%|▌         | 113/2248 [00:05<04:04,  8.73it/s]
  5%|▌         | 115/2248 [00:05<03:37,  9.83it/s]
  5%|▌         | 117/2248 [00:05<03:39,  9.70it/s]
  5%|▌         | 119/2248 [00:06<03:37,  9.77it/s]
  5%|▌         | 121/2248 [00:06<03:51,  9.18it/s]
  5%|▌         | 123/2248 [00:06<03:58,  8.92it/s]
  6%|▌         | 125/2248 [00:06<04:01,  8.79it/s]
  6%|▌         | 127/2248 [00:07<04:39,  7.60it/s]
  6%|▌         | 128/2248 [00:07<04:42,  7.50it/s]
  6%|▌         | 130/2248 [00:07<04:00,  8.82it/s]
  6%|▌         | 133/2248 [00:07<03:17, 10.69it/s]
  6%|▌         | 135/2248 [00:07<03:25, 10.26it/s]
  6%|▌         | 137/2248 [00:08<03:34,  9.83it/s]
  6%|▌         | 139/2248 [00:08<03:39,  9.61it/s]
  6%|▋         | 141/2248 [00:08<03:06, 11.31it/s]
  6%|▋         | 145/2248 [00:08<02:41, 13.04it/s]
  7%|▋         | 147/2248 [00:08<02:27, 14.26it/s]
  7%|▋         | 149/2248 [00:09<03:34,  9.81it/s]
  7%|▋         | 151/2248 [00:09<03:50,  9.08it/s]
  7%|▋         | 153/2248 [00:09<04:07,  8.46it/s]
  7%|▋         | 156/2248 [00:10<03:44,  9.30it/s]
  7%|▋         | 158/2248 [00:10<06:26,  5.41it/s]
  7%|▋         | 159/2248 [00:11<06:26,  5.40it/s]
  7%|▋         | 160/2248 [00:11<06:40,  5.21it/s]
  7%|▋         | 162/2248 [00:11<05:42,  6.09it/s]
  7%|▋         | 164/2248 [00:11<04:24,  7.89it/s]
  7%|▋         | 166/2248 [00:12<06:04,  5.71it/s]
  8%|▊         | 169/2248 [00:12<05:47,  5.98it/s]
  8%|▊         | 171/2248 [00:12<04:44,  7.30it/s]
  8%|▊         | 173/2248 [00:12<04:40,  7.40it/s]
  8%|▊         | 175/2248 [00:13<03:54,  8.83it/s]
  8%|▊         | 177/2248 [00:13<04:28,  7.71it/s]
  8%|▊         | 179/2248 [00:13<04:45,  7.26it/s]
  8%|▊         | 180/2248 [00:13<04:53,  7.05it/s]
  8%|▊         | 182/2248 [00:14<03:54,  8.80it/s]
  8%|▊         | 184/2248 [00:14<05:01,  6.85it/s]
  8%|▊         | 185/2248 [00:14<05:44,  5.99it/s]
  8%|▊         | 187/2248 [00:14<05:18,  6.47it/s]
  8%|▊         | 189/2248 [00:15<06:10,  5.56it/s]
  8%|▊         | 190/2248 [00:15<05:53,  5.83it/s]
  9%|▊         | 192/2248 [00:15<04:41,  7.30it/s]
  9%|▊         | 193/2248 [00:15<05:12,  6.57it/s]
  9%|▊         | 194/2248 [00:16<05:09,  6.63it/s]
  9%|▊         | 195/2248 [00:16<07:09,  4.78it/s]
  9%|▉         | 198/2248 [00:16<04:14,  8.06it/s]
  9%|▉         | 201/2248 [00:16<03:06, 10.96it/s]
  9%|▉         | 203/2248 [00:17<03:38,  9.34it/s]
  9%|▉         | 205/2248 [00:17<03:45,  9.06it/s]
  9%|▉         | 207/2248 [00:17<04:54,  6.93it/s]
  9%|▉         | 208/2248 [00:17<05:24,  6.28it/s]
  9%|▉         | 209/2248 [00:18<05:52,  5.79it/s]
  9%|▉         | 210/2248 [00:18<06:43,  5.05it/s]
  9%|▉         | 211/2248 [00:18<07:02,  4.82it/s]
  9%|▉         | 212/2248 [00:18<06:10,  5.49it/s]
 10%|▉         | 214/2248 [00:18<04:20,  7.82it/s]
 10%|▉         | 216/2248 [00:19<03:22, 10.04it/s]
 10%|▉         | 221/2248 [00:19<01:50, 18.35it/s]
 10%|█         | 227/2248 [00:19<01:12, 27.71it/s]
 10%|█         | 231/2248 [00:19<01:07, 29.97it/s]
 11%|█         | 237/2248 [00:19<00:54, 37.22it/s]
 11%|█         | 244/2248 [00:19<00:47, 41.88it/s]
 11%|█         | 249/2248 [00:19<00:47, 41.91it/s]
 11%|█▏        | 257/2248 [00:19<00:39, 50.73it/s]
 12%|█▏        | 263/2248 [00:20<00:55, 35.62it/s]
 12%|█▏        | 268/2248 [00:20<01:26, 22.84it/s]
 12%|█▏        | 272/2248 [00:20<01:30, 21.90it/s]
 12%|█▏        | 275/2248 [00:21<02:41, 12.23it/s]
 12%|█▏        | 278/2248 [00:21<03:18,  9.92it/s]
 12%|█▏        | 280/2248 [00:22<04:02,  8.13it/s]
 13%|█▎        | 282/2248 [00:23<05:18,  6.17it/s]
 13%|█▎        | 285/2248 [00:23<04:06,  7.98it/s]
 13%|█▎        | 287/2248 [00:23<05:23,  6.05it/s]
 13%|█▎        | 289/2248 [00:23<04:32,  7.18it/s]
 13%|█▎        | 291/2248 [00:24<05:05,  6.41it/s]
 13%|█▎        | 293/2248 [00:24<04:50,  6.73it/s]
 13%|█▎        | 295/2248 [00:24<04:35,  7.08it/s]
 13%|█▎        | 298/2248 [00:25<04:53,  6.65it/s]
 13%|█▎        | 299/2248 [00:25<05:38,  5.76it/s]
 13%|█▎        | 301/2248 [00:25<04:42,  6.89it/s]
 13%|█▎        | 302/2248 [00:25<05:06,  6.36it/s]
 13%|█▎        | 303/2248 [00:26<05:36,  5.79it/s]
 14%|█▎        | 304/2248 [00:26<05:53,  5.50it/s]
 14%|█▎        | 305/2248 [00:26<07:21,  4.40it/s]
 14%|█▎        | 306/2248 [00:27<08:05,  4.00it/s]
 14%|█▎        | 307/2248 [00:27<07:45,  4.17it/s]
 14%|█▎        | 308/2248 [00:27<07:13,  4.48it/s]
 14%|█▎        | 309/2248 [00:27<06:48,  4.74it/s]
 14%|█▍        | 311/2248 [00:27<04:35,  7.04it/s]
 14%|█▍        | 312/2248 [00:28<05:32,  5.82it/s]
 14%|█▍        | 313/2248 [00:28<05:17,  6.10it/s]
 14%|█▍        | 314/2248 [00:28<05:59,  5.39it/s]
 14%|█▍        | 315/2248 [00:28<05:48,  5.54it/s]
 14%|█▍        | 317/2248 [00:28<04:21,  7.40it/s]
 14%|█▍        | 318/2248 [00:28<04:31,  7.11it/s]
 14%|█▍        | 320/2248 [00:29<03:40,  8.74it/s]
 14%|█▍        | 322/2248 [00:29<03:48,  8.43it/s]
 14%|█▍        | 323/2248 [00:29<04:27,  7.19it/s]
 14%|█▍        | 325/2248 [00:29<04:57,  6.46it/s]
 15%|█▍        | 327/2248 [00:30<05:44,  5.57it/s]
 15%|█▍        | 328/2248 [00:30<07:29,  4.27it/s]
 15%|█▍        | 329/2248 [00:31<07:22,  4.34it/s]
 15%|█▍        | 331/2248 [00:31<05:11,  6.16it/s]
 15%|█▍        | 332/2248 [00:31<05:52,  5.44it/s]
 15%|█▍        | 333/2248 [00:31<05:14,  6.09it/s]
 15%|█▌        | 338/2248 [00:31<02:22, 13.43it/s]
 15%|█▌        | 340/2248 [00:31<03:16,  9.73it/s]
 15%|█▌        | 343/2248 [00:32<03:37,  8.75it/s]
 15%|█▌        | 345/2248 [00:32<05:14,  6.05it/s]
 15%|█▌        | 347/2248 [00:33<06:04,  5.22it/s]
 15%|█▌        | 348/2248 [00:33<07:02,  4.49it/s]
 16%|█▌        | 349/2248 [00:34<07:59,  3.96it/s]
 16%|█▌        | 350/2248 [00:34<07:31,  4.20it/s]
 16%|█▌        | 353/2248 [00:34<06:19,  4.99it/s]
 16%|█▌        | 354/2248 [00:35<07:31,  4.19it/s]
 16%|█▌        | 355/2248 [00:35<08:06,  3.89it/s]
 16%|█▌        | 356/2248 [00:36<08:46,  3.60it/s]
 16%|█▌        | 358/2248 [00:36<06:01,  5.22it/s]
 16%|█▌        | 362/2248 [00:36<03:58,  7.89it/s]
 16%|█▌        | 364/2248 [00:36<04:35,  6.84it/s]
 16%|█▋        | 366/2248 [00:36<03:56,  7.96it/s]
 16%|█▋        | 367/2248 [00:37<05:25,  5.77it/s]
 16%|█▋        | 369/2248 [00:37<04:13,  7.40it/s]
 17%|█▋        | 371/2248 [00:37<04:33,  6.87it/s]
 17%|█▋        | 373/2248 [00:38<05:01,  6.22it/s]
 17%|█▋        | 375/2248 [00:38<03:59,  7.82it/s]
 17%|█▋        | 377/2248 [00:38<03:27,  9.02it/s]
 17%|█▋        | 379/2248 [00:38<03:00, 10.34it/s]
 17%|█▋        | 381/2248 [00:38<02:58, 10.45it/s]
 17%|█▋        | 384/2248 [00:39<03:45,  8.28it/s]
 17%|█▋        | 386/2248 [00:39<04:20,  7.16it/s]
 17%|█▋        | 388/2248 [00:39<04:27,  6.95it/s]
 17%|█▋        | 389/2248 [00:40<04:29,  6.89it/s]
 17%|█▋        | 390/2248 [00:40<05:46,  5.36it/s]
 17%|█▋        | 391/2248 [00:40<06:03,  5.11it/s]
 17%|█▋        | 392/2248 [00:41<07:26,  4.15it/s]
 17%|█▋        | 393/2248 [00:41<07:12,  4.29it/s]
 18%|█▊        | 394/2248 [00:41<07:47,  3.97it/s]
 18%|█▊        | 395/2248 [00:41<06:55,  4.46it/s]
 18%|█▊        | 397/2248 [00:41<04:54,  6.29it/s]
 18%|█▊        | 399/2248 [00:41<03:38,  8.46it/s]
 18%|█▊        | 401/2248 [00:42<03:01, 10.18it/s]
 18%|█▊        | 407/2248 [00:42<01:30, 20.37it/s]
 18%|█▊        | 414/2248 [00:42<01:00, 30.45it/s]
 19%|█▊        | 420/2248 [00:42<00:50, 36.37it/s]
 19%|█▉        | 427/2248 [00:42<00:41, 43.39it/s]
 19%|█▉        | 432/2248 [00:42<00:46, 38.75it/s]
 19%|█▉        | 437/2248 [00:43<01:41, 17.92it/s]
 20%|█▉        | 441/2248 [00:44<03:17,  9.16it/s]
 20%|█▉        | 444/2248 [00:44<03:40,  8.17it/s]
 20%|█▉        | 446/2248 [00:45<04:09,  7.23it/s]
 20%|█▉        | 448/2248 [00:45<04:04,  7.35it/s]
 20%|██        | 450/2248 [00:45<03:59,  7.52it/s]
 20%|██        | 453/2248 [00:46<04:19,  6.92it/s]
 20%|██        | 455/2248 [00:46<04:14,  7.05it/s]
 20%|██        | 457/2248 [00:47<04:54,  6.08it/s]
 20%|██        | 459/2248 [00:47<05:19,  5.60it/s]
 20%|██        | 460/2248 [00:47<05:23,  5.53it/s]
 21%|██        | 463/2248 [00:48<04:20,  6.85it/s]
 21%|██        | 464/2248 [00:48<04:36,  6.45it/s]
 21%|██        | 465/2248 [00:48<04:50,  6.14it/s]
 21%|██        | 468/2248 [00:48<03:54,  7.58it/s]
 21%|██        | 470/2248 [00:48<03:17,  9.00it/s]
 21%|██        | 472/2248 [00:49<04:05,  7.24it/s]
 21%|██        | 475/2248 [00:49<04:18,  6.86it/s]
 21%|██        | 476/2248 [00:49<04:19,  6.83it/s]
 21%|██        | 477/2248 [00:50<04:41,  6.29it/s]
 21%|██▏       | 478/2248 [00:50<04:26,  6.63it/s]
 21%|██▏       | 479/2248 [00:50<04:46,  6.17it/s]
 21%|██▏       | 480/2248 [00:50<05:13,  5.64it/s]
 21%|██▏       | 481/2248 [00:50<05:24,  5.44it/s]
 21%|██▏       | 482/2248 [00:50<04:45,  6.18it/s]
 22%|██▏       | 485/2248 [00:51<02:49, 10.42it/s]
 22%|██▏       | 487/2248 [00:51<03:37,  8.09it/s]
 22%|██▏       | 489/2248 [00:51<03:13,  9.11it/s]
 22%|██▏       | 491/2248 [00:51<02:45, 10.64it/s]
 22%|██▏       | 493/2248 [00:52<03:21,  8.72it/s]
 22%|██▏       | 495/2248 [00:52<03:30,  8.33it/s]
 22%|██▏       | 498/2248 [00:52<02:35, 11.28it/s]
 22%|██▏       | 500/2248 [00:52<02:41, 10.83it/s]
 22%|██▏       | 502/2248 [00:52<02:27, 11.80it/s]
 23%|██▎       | 508/2248 [00:52<01:24, 20.58it/s]
 23%|██▎       | 511/2248 [00:53<01:52, 15.48it/s]
 23%|██▎       | 514/2248 [00:53<02:31, 11.41it/s]
 23%|██▎       | 516/2248 [00:54<03:15,  8.88it/s]
 23%|██▎       | 518/2248 [00:54<03:50,  7.51it/s]
 23%|██▎       | 520/2248 [00:54<03:49,  7.52it/s]
 23%|██▎       | 523/2248 [00:54<02:50, 10.11it/s]
 24%|██▎       | 531/2248 [00:54<01:27, 19.62it/s]
 24%|██▍       | 535/2248 [00:55<01:17, 22.08it/s]
 24%|██▍       | 542/2248 [00:55<00:55, 30.62it/s]
 24%|██▍       | 547/2248 [00:55<00:56, 30.17it/s]
 25%|██▍       | 554/2248 [00:55<00:44, 38.29it/s]
 25%|██▍       | 560/2248 [00:55<00:39, 43.09it/s]
 25%|██▌       | 566/2248 [00:55<00:35, 46.95it/s]
 25%|██▌       | 572/2248 [00:56<01:24, 19.74it/s]
 26%|██▌       | 576/2248 [00:57<02:11, 12.67it/s]
 26%|██▌       | 579/2248 [00:57<02:38, 10.51it/s]
 26%|██▌       | 582/2248 [00:57<02:56,  9.44it/s]
 26%|██▌       | 584/2248 [00:58<02:57,  9.36it/s]
 26%|██▌       | 586/2248 [00:58<03:35,  7.70it/s]
 26%|██▌       | 588/2248 [00:59<04:12,  6.57it/s]
 26%|██▋       | 591/2248 [00:59<03:14,  8.51it/s]
 26%|██▋       | 593/2248 [00:59<03:17,  8.38it/s]
 27%|██▋       | 596/2248 [00:59<02:30, 10.94it/s]
 27%|██▋       | 599/2248 [00:59<02:26, 11.22it/s]
 27%|██▋       | 601/2248 [01:00<03:19,  8.25it/s]
 27%|██▋       | 603/2248 [01:00<04:07,  6.65it/s]
 27%|██▋       | 604/2248 [01:00<04:21,  6.29it/s]
 27%|██▋       | 605/2248 [01:01<05:58,  4.58it/s]
 27%|██▋       | 606/2248 [01:01<07:07,  3.84it/s]
 27%|██▋       | 607/2248 [01:02<06:45,  4.05it/s]
 27%|██▋       | 608/2248 [01:02<07:53,  3.47it/s]
 27%|██▋       | 609/2248 [01:02<08:54,  3.07it/s]
 27%|██▋       | 610/2248 [01:03<08:10,  3.34it/s]
 27%|██▋       | 612/2248 [01:03<05:14,  5.20it/s]
 27%|██▋       | 618/2248 [01:03<02:08, 12.68it/s]
 28%|██▊       | 624/2248 [01:03<01:19, 20.39it/s]
 28%|██▊       | 631/2248 [01:03<00:54, 29.40it/s]
 28%|██▊       | 637/2248 [01:03<00:45, 35.35it/s]
 29%|██▊       | 645/2248 [01:03<00:35, 44.86it/s]
 29%|██▉       | 651/2248 [01:04<01:05, 24.55it/s]
 29%|██▉       | 656/2248 [01:05<01:51, 14.34it/s]
 29%|██▉       | 660/2248 [01:05<02:07, 12.50it/s]
 29%|██▉       | 663/2248 [01:05<02:26, 10.83it/s]
 30%|██▉       | 665/2248 [01:06<02:31, 10.42it/s]
 30%|██▉       | 667/2248 [01:06<02:36, 10.11it/s]
 30%|██▉       | 669/2248 [01:06<02:27, 10.67it/s]
 30%|██▉       | 671/2248 [01:06<02:52,  9.13it/s]
 30%|███       | 677/2248 [01:07<01:55, 13.59it/s]
 30%|███       | 679/2248 [01:07<02:10, 12.02it/s]
 30%|███       | 681/2248 [01:07<02:02, 12.84it/s]
 30%|███       | 683/2248 [01:08<03:29,  7.48it/s]
 30%|███       | 685/2248 [01:08<05:30,  4.73it/s]
 31%|███       | 686/2248 [01:09<05:47,  4.49it/s]
 31%|███       | 688/2248 [01:09<05:15,  4.95it/s]
 31%|███       | 689/2248 [01:09<04:50,  5.36it/s]
 31%|███       | 691/2248 [01:10<05:00,  5.17it/s]
 31%|███       | 692/2248 [01:10<05:10,  5.02it/s]
 31%|███       | 694/2248 [01:10<04:38,  5.59it/s]
 31%|███       | 695/2248 [01:10<05:19,  4.87it/s]
 31%|███       | 696/2248 [01:11<05:13,  4.95it/s]
 31%|███       | 698/2248 [01:11<03:44,  6.90it/s]
 31%|███       | 699/2248 [01:11<03:49,  6.74it/s]
 31%|███       | 701/2248 [01:11<02:52,  8.96it/s]
 31%|███▏      | 703/2248 [01:11<02:40,  9.64it/s]
 31%|███▏      | 705/2248 [01:11<02:27, 10.48it/s]
 32%|███▏      | 709/2248 [01:12<02:47,  9.20it/s]
 32%|███▏      | 711/2248 [01:12<02:47,  9.19it/s]
 32%|███▏      | 713/2248 [01:12<03:44,  6.84it/s]
 32%|███▏      | 715/2248 [01:13<04:26,  5.75it/s]
 32%|███▏      | 716/2248 [01:13<05:26,  4.70it/s]
 32%|███▏      | 718/2248 [01:14<04:11,  6.07it/s]
 32%|███▏      | 719/2248 [01:14<04:19,  5.88it/s]
 32%|███▏      | 720/2248 [01:14<04:37,  5.51it/s]
 32%|███▏      | 721/2248 [01:14<04:43,  5.38it/s]
 32%|███▏      | 724/2248 [01:14<03:36,  7.04it/s]
 32%|███▏      | 725/2248 [01:15<04:58,  5.10it/s]
 32%|███▏      | 727/2248 [01:15<04:35,  5.52it/s]
 32%|███▏      | 728/2248 [01:16<05:50,  4.33it/s]
 32%|███▏      | 730/2248 [01:16<04:10,  6.05it/s]
 33%|███▎      | 731/2248 [01:16<05:22,  4.70it/s]
 33%|███▎      | 732/2248 [01:16<05:18,  4.76it/s]
 33%|███▎      | 733/2248 [01:17<06:34,  3.84it/s]
 33%|███▎      | 734/2248 [01:17<06:47,  3.71it/s]
 33%|███▎      | 735/2248 [01:17<06:47,  3.71it/s]
 33%|███▎      | 736/2248 [01:18<06:34,  3.84it/s]
 33%|███▎      | 737/2248 [01:18<06:40,  3.77it/s]
 33%|███▎      | 738/2248 [01:18<05:42,  4.41it/s]
 33%|███▎      | 740/2248 [01:18<03:42,  6.78it/s]
 33%|███▎      | 742/2248 [01:18<03:53,  6.45it/s]
 33%|███▎      | 743/2248 [01:19<04:27,  5.62it/s]
 33%|███▎      | 744/2248 [01:19<04:02,  6.20it/s]
 33%|███▎      | 747/2248 [01:19<02:37,  9.52it/s]
 33%|███▎      | 749/2248 [01:19<02:38,  9.46it/s]
 33%|███▎      | 751/2248 [01:19<03:04,  8.10it/s]
 33%|███▎      | 752/2248 [01:20<03:37,  6.87it/s]
 34%|███▎      | 754/2248 [01:20<03:23,  7.33it/s]
 34%|███▎      | 756/2248 [01:20<02:47,  8.91it/s]
 34%|███▎      | 758/2248 [01:20<02:26, 10.19it/s]
 34%|███▍      | 761/2248 [01:20<02:33,  9.70it/s]
 34%|███▍      | 763/2248 [01:21<02:52,  8.59it/s]
 34%|███▍      | 765/2248 [01:21<02:28, 10.00it/s]
 34%|███▍      | 767/2248 [01:21<02:28,  9.95it/s]
 34%|███▍      | 770/2248 [01:21<01:51, 13.29it/s]
 34%|███▍      | 772/2248 [01:21<01:56, 12.66it/s]
 34%|███▍      | 774/2248 [01:22<02:56,  8.34it/s]
 35%|███▍      | 776/2248 [01:22<03:31,  6.96it/s]
 35%|███▍      | 778/2248 [01:22<03:22,  7.27it/s]
 35%|███▍      | 780/2248 [01:23<02:45,  8.89it/s]
 35%|███▍      | 782/2248 [01:23<02:48,  8.69it/s]
 35%|███▍      | 784/2248 [01:23<03:32,  6.89it/s]
 35%|███▌      | 788/2248 [01:23<02:14, 10.88it/s]
 35%|███▌      | 790/2248 [01:24<02:26,  9.96it/s]
 35%|███▌      | 792/2248 [01:24<03:04,  7.90it/s]
 35%|███▌      | 795/2248 [01:24<02:17, 10.55it/s]
 35%|███▌      | 797/2248 [01:25<02:56,  8.21it/s]
 36%|███▌      | 800/2248 [01:25<02:44,  8.81it/s]
 36%|███▌      | 803/2248 [01:25<02:08, 11.20it/s]
 36%|███▌      | 806/2248 [01:25<02:03, 11.71it/s]
 36%|███▌      | 808/2248 [01:25<01:51, 12.95it/s]
 36%|███▌      | 810/2248 [01:26<02:10, 11.05it/s]
 36%|███▌      | 812/2248 [01:26<02:38,  9.07it/s]
 36%|███▌      | 814/2248 [01:26<02:53,  8.26it/s]
 36%|███▋      | 815/2248 [01:26<03:10,  7.52it/s]
 36%|███▋      | 816/2248 [01:27<03:22,  7.08it/s]
 36%|███▋      | 818/2248 [01:27<02:45,  8.65it/s]
 37%|███▋      | 823/2248 [01:27<01:31, 15.58it/s]
 37%|███▋      | 829/2248 [01:27<00:58, 24.15it/s]
 37%|███▋      | 835/2248 [01:27<00:44, 31.91it/s]
 37%|███▋      | 842/2248 [01:27<00:34, 40.60it/s]
 38%|███▊      | 849/2248 [01:27<00:29, 47.70it/s]
 38%|███▊      | 855/2248 [01:27<00:27, 49.87it/s]
 38%|███▊      | 861/2248 [01:27<00:27, 50.00it/s]
 39%|███▊      | 867/2248 [01:28<01:03, 21.85it/s]
 39%|███▉      | 872/2248 [01:29<01:55, 11.92it/s]
 39%|███▉      | 875/2248 [01:29<01:53, 12.11it/s]
 39%|███▉      | 878/2248 [01:30<02:16, 10.01it/s]
 39%|███▉      | 880/2248 [01:30<02:26,  9.32it/s]
 39%|███▉      | 882/2248 [01:30<02:35,  8.79it/s]
 39%|███▉      | 884/2248 [01:31<02:57,  7.69it/s]
 39%|███▉      | 886/2248 [01:31<02:59,  7.57it/s]
 40%|███▉      | 888/2248 [01:31<03:37,  6.24it/s]
 40%|███▉      | 890/2248 [01:32<04:08,  5.47it/s]
 40%|███▉      | 891/2248 [01:32<04:02,  5.60it/s]
 40%|███▉      | 893/2248 [01:32<03:15,  6.92it/s]
 40%|███▉      | 894/2248 [01:33<03:41,  6.12it/s]
 40%|███▉      | 895/2248 [01:33<03:56,  5.71it/s]
 40%|███▉      | 896/2248 [01:33<04:10,  5.41it/s]
 40%|███▉      | 898/2248 [01:33<02:58,  7.58it/s]
 40%|████      | 900/2248 [01:33<03:02,  7.40it/s]
 40%|████      | 902/2248 [01:34<03:38,  6.17it/s]
 40%|████      | 903/2248 [01:34<04:37,  4.84it/s]
 40%|████      | 905/2248 [01:34<03:30,  6.38it/s]
 40%|████      | 906/2248 [01:35<04:05,  5.47it/s]
 40%|████      | 907/2248 [01:35<05:00,  4.46it/s]
 40%|████      | 908/2248 [01:35<05:48,  3.85it/s]
 40%|████      | 909/2248 [01:36<05:48,  3.84it/s]
 40%|████      | 910/2248 [01:36<06:04,  3.67it/s]
 41%|████      | 911/2248 [01:36<07:11,  3.10it/s]
 41%|████      | 912/2248 [01:37<06:24,  3.48it/s]
 41%|████      | 913/2248 [01:37<05:39,  3.94it/s]
 41%|████      | 915/2248 [01:37<03:41,  6.02it/s]
 41%|████      | 916/2248 [01:37<04:19,  5.12it/s]
 41%|████      | 917/2248 [01:37<04:13,  5.26it/s]
 41%|████      | 919/2248 [01:38<03:45,  5.90it/s]
 41%|████      | 920/2248 [01:38<03:27,  6.41it/s]
 41%|████      | 922/2248 [01:38<02:39,  8.33it/s]
 41%|████      | 924/2248 [01:38<02:47,  7.91it/s]
 41%|████      | 927/2248 [01:39<03:23,  6.48it/s]
 41%|████▏     | 929/2248 [01:39<03:23,  6.47it/s]
 41%|████▏     | 930/2248 [01:39<03:12,  6.84it/s]
 41%|████▏     | 931/2248 [01:39<03:04,  7.13it/s]
 42%|████▏     | 934/2248 [01:39<02:33,  8.58it/s]
 42%|████▏     | 936/2248 [01:40<02:11,  9.96it/s]
 42%|████▏     | 938/2248 [01:40<02:51,  7.63it/s]
 42%|████▏     | 940/2248 [01:40<02:55,  7.46it/s]
 42%|████▏     | 941/2248 [01:40<03:03,  7.13it/s]
 42%|████▏     | 943/2248 [01:41<02:33,  8.52it/s]
 42%|████▏     | 944/2248 [01:41<02:58,  7.30it/s]
 42%|████▏     | 946/2248 [01:41<02:55,  7.40it/s]
 42%|████▏     | 948/2248 [01:41<02:21,  9.16it/s]
 42%|████▏     | 950/2248 [01:41<02:29,  8.70it/s]
 42%|████▏     | 952/2248 [01:42<03:18,  6.54it/s]
 42%|████▏     | 953/2248 [01:42<04:18,  5.00it/s]
 42%|████▏     | 954/2248 [01:43<04:19,  4.99it/s]
 43%|████▎     | 956/2248 [01:43<04:38,  4.64it/s]
 43%|████▎     | 957/2248 [01:43<05:34,  3.86it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 324.86it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 13], [np.int64(2), False, 11], [np.int64(4), False, 2], [np.int64(5), False, 0], [np.int64(6), False, 10], [np.int64(7), False, 0], [np.int64(8), False, 6], [np.int64(9), False, 10], [np.int64(10), False, 12], [np.int64(12), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0361, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0517, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [08:37<3:08:57, 76.09s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [08:37<2:11:30, 53.32s/it]

tensor(12.5565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2385, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5628, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5521, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [08:37<44:22, 18.36s/it]

tensor(12.5805, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7266, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8227, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [08:38<21:35,  9.06s/it]

tensor(12.6139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8146, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8297, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [08:38<10:34,  4.50s/it]

tensor(12.6205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9044, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9596, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [08:38<05:14,  2.26s/it]

tensor(12.5961, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0486, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0886, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [08:38<02:40,  1.17s/it]

tensor(12.5476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1195, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1157, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [08:39<01:25,  1.58it/s]

tensor(12.5295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1103, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1637, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [08:39<00:49,  2.70it/s]

tensor(12.5382, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2055, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5368, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2406, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [08:39<00:31,  4.15it/s]

tensor(12.5291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2340, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5169, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2399, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [08:39<00:23,  5.57it/s]

tensor(12.5018, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2442, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2513, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [08:40<00:19,  6.68it/s]

tensor(12.4773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2676, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2821, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [08:40<00:16,  7.50it/s]

tensor(12.4745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2862, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4728, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2998, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [08:40<00:15,  8.12it/s]

tensor(12.4686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3087, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3200, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [08:40<00:14,  8.31it/s]

tensor(12.4545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3278, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3385, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [08:41<00:14,  8.37it/s]

tensor(12.4383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3433, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3475, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [08:41<00:13,  8.45it/s]

tensor(12.4298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3563, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3585, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [08:41<00:13,  8.48it/s]

tensor(12.4208, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4162, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3583, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [08:41<00:13,  8.52it/s]

tensor(12.4115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3597, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3639, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [08:41<00:12,  8.54it/s]

tensor(12.4024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3669, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3750, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [08:42<00:12,  8.54it/s]

tensor(12.3950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3780, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3864, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [08:42<00:12,  8.54it/s]

tensor(12.3863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3916, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3966, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [08:42<00:12,  8.42it/s]

tensor(12.3782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3925, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3950, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [08:42<00:12,  8.35it/s]

tensor(12.3712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3998, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4034, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [08:43<00:12,  8.40it/s]

tensor(12.3650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4063, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4118, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:43<00:11,  8.46it/s]

tensor(12.3589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4113, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([173, 316, 135, 187, 167, 160, 130,  51, 423, 126, 191,  69,  75,  45])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 4/2248 [00:00<01:27, 25.63it/s]
  0%|          | 9/2248 [00:00<01:04, 34.62it/s]
  1%|          | 14/2248 [00:00<00:56, 39.53it/s]
  1%|          | 21/2248 [00:00<00:45, 48.54it/s]
  1%|          | 27/2248 [00:00<00:42, 51.88it/s]
  2%|▏         | 34/2248 [00:00<00:39, 56.71it/s]
  2%|▏         | 40/2248 [00:00<00:45, 48.63it/s]
  2%|▏         | 46/2248 [00:01<00:50, 43.75it/s]
  2%|▏         | 51/2248 [00:01<00:54, 40.35it/s]
  3%|▎         | 58/2248 [00:01<00:47, 46.45it/s]
  3%|▎         | 63/2248 [00:01<00:49, 43.76it/s]
  3%|▎         | 70/2248 [00:01<00:47, 45.44it/s]
  3%|▎         | 75/2248 [00:01<01:09, 31.11it/s]
  4%|▎         | 79/2248 [00:02<02:00, 18.05it/s]
  4%|▎         | 83/2248 [00:02<01:44, 20.80it/s]
  4%|▍         | 90/2248 [00:02<01:38, 21.86it/s]
  4%|▍         | 93/2248 [00:02<01:42, 21.10it/s]
  4%|▍         | 96/2248 [00:03<02:07, 16.83it/s]
  4%|▍         | 99/2248 [00:03<02:35, 13.80it/s]
  4%|▍         | 101/2248 [00:03<02:52, 12.48it/s]
  5%|▍         | 103/2248 [00:04<03:00, 11.89it/s]
  5%|▍         | 105/2248 [00:04<03:07, 11.44it/s]
  5%|▍         | 108/2248 [00:04<02:30, 14.26it/s]
  5%|▍         | 111/2248 [00:04<02:41, 13.26it/s]
  5%|▌         | 113/2248 [00:04<03:11, 11.17it/s]
  5%|▌         | 115/2248 [00:05<02:58, 11.92it/s]
  5%|▌         | 117/2248 [00:05<04:11,  8.46it/s]
  5%|▌         | 119/2248 [00:05<04:15,  8.33it/s]
  5%|▌         | 121/2248 [00:05<04:32,  7.82it/s]
  5%|▌         | 122/2248 [00:06<05:05,  6.96it/s]
  6%|▌         | 125/2248 [00:06<04:16,  8.27it/s]
  6%|▌         | 126/2248 [00:06<04:41,  7.53it/s]
  6%|▌         | 127/2248 [00:06<05:22,  6.57it/s]
  6%|▌         | 128/2248 [00:07<06:22,  5.55it/s]
  6%|▌         | 130/2248 [00:07<04:48,  7.35it/s]
  6%|▌         | 133/2248 [00:07<04:12,  8.37it/s]
  6%|▌         | 135/2248 [00:07<04:16,  8.23it/s]
  6%|▌         | 136/2248 [00:08<04:43,  7.45it/s]
  6%|▌         | 138/2248 [00:08<04:58,  7.07it/s]
  6%|▌         | 140/2248 [00:08<04:59,  7.04it/s]
  6%|▋         | 142/2248 [00:08<04:04,  8.60it/s]
  6%|▋         | 145/2248 [00:09<03:38,  9.62it/s]
  7%|▋         | 148/2248 [00:09<02:47, 12.57it/s]
  7%|▋         | 151/2248 [00:09<02:45, 12.66it/s]
  7%|▋         | 153/2248 [00:09<03:01, 11.55it/s]
  7%|▋         | 156/2248 [00:09<03:16, 10.65it/s]
  7%|▋         | 158/2248 [00:10<04:34,  7.62it/s]
  7%|▋         | 159/2248 [00:10<05:01,  6.92it/s]
  7%|▋         | 160/2248 [00:10<05:33,  6.26it/s]
  7%|▋         | 162/2248 [00:11<05:05,  6.82it/s]
  7%|▋         | 165/2248 [00:11<04:07,  8.42it/s]
  7%|▋         | 166/2248 [00:11<04:39,  7.46it/s]
  7%|▋         | 168/2248 [00:11<04:22,  7.92it/s]
  8%|▊         | 169/2248 [00:11<04:39,  7.43it/s]
  8%|▊         | 172/2248 [00:12<03:14, 10.66it/s]
  8%|▊         | 174/2248 [00:12<03:36,  9.57it/s]
  8%|▊         | 176/2248 [00:12<03:33,  9.71it/s]
  8%|▊         | 178/2248 [00:12<03:41,  9.36it/s]
  8%|▊         | 180/2248 [00:12<03:10, 10.86it/s]
  8%|▊         | 182/2248 [00:12<02:49, 12.22it/s]
  8%|▊         | 184/2248 [00:13<03:27,  9.97it/s]
  8%|▊         | 186/2248 [00:13<03:43,  9.21it/s]
  8%|▊         | 188/2248 [00:13<04:12,  8.16it/s]
  8%|▊         | 189/2248 [00:14<04:59,  6.87it/s]
  8%|▊         | 190/2248 [00:14<05:21,  6.40it/s]
  9%|▊         | 192/2248 [00:14<04:13,  8.12it/s]
  9%|▊         | 193/2248 [00:14<04:42,  7.28it/s]
  9%|▊         | 194/2248 [00:14<05:21,  6.38it/s]
  9%|▊         | 195/2248 [00:15<05:39,  6.04it/s]
  9%|▉         | 199/2248 [00:15<02:57, 11.55it/s]
  9%|▉         | 201/2248 [00:15<03:06, 10.95it/s]
  9%|▉         | 203/2248 [00:15<03:37,  9.42it/s]
  9%|▉         | 205/2248 [00:15<04:01,  8.47it/s]
  9%|▉         | 206/2248 [00:16<04:30,  7.56it/s]
  9%|▉         | 207/2248 [00:16<05:12,  6.52it/s]
  9%|▉         | 208/2248 [00:16<05:37,  6.04it/s]
  9%|▉         | 209/2248 [00:16<06:18,  5.39it/s]
  9%|▉         | 210/2248 [00:17<06:51,  4.95it/s]
  9%|▉         | 211/2248 [00:17<07:16,  4.66it/s]
  9%|▉         | 212/2248 [00:17<07:07,  4.77it/s]
 10%|▉         | 214/2248 [00:17<04:52,  6.95it/s]
 10%|▉         | 221/2248 [00:17<01:54, 17.75it/s]
 10%|█         | 226/2248 [00:17<01:26, 23.48it/s]
 10%|█         | 231/2248 [00:17<01:09, 29.03it/s]
 11%|█         | 237/2248 [00:18<00:56, 35.70it/s]
 11%|█         | 244/2248 [00:18<00:45, 44.06it/s]
 11%|█         | 250/2248 [00:18<00:42, 47.11it/s]
 11%|█▏        | 256/2248 [00:18<00:44, 44.51it/s]
 12%|█▏        | 261/2248 [00:18<00:52, 38.17it/s]
 12%|█▏        | 266/2248 [00:19<02:17, 14.41it/s]
 12%|█▏        | 270/2248 [00:20<02:45, 11.95it/s]
 12%|█▏        | 273/2248 [00:20<02:54, 11.34it/s]
 12%|█▏        | 275/2248 [00:20<03:11, 10.29it/s]
 12%|█▏        | 277/2248 [00:20<03:26,  9.57it/s]
 12%|█▏        | 279/2248 [00:21<03:08, 10.42it/s]
 12%|█▎        | 281/2248 [00:21<03:36,  9.09it/s]
 13%|█▎        | 283/2248 [00:21<03:51,  8.49it/s]
 13%|█▎        | 285/2248 [00:21<03:19,  9.84it/s]
 13%|█▎        | 287/2248 [00:22<04:25,  7.38it/s]
 13%|█▎        | 289/2248 [00:22<03:51,  8.45it/s]
 13%|█▎        | 291/2248 [00:22<04:27,  7.31it/s]
 13%|█▎        | 292/2248 [00:22<04:38,  7.02it/s]
 13%|█▎        | 294/2248 [00:22<03:39,  8.90it/s]
 13%|█▎        | 296/2248 [00:23<03:14, 10.05it/s]
 13%|█▎        | 298/2248 [00:23<02:55, 11.13it/s]
 13%|█▎        | 300/2248 [00:23<02:59, 10.88it/s]
 13%|█▎        | 302/2248 [00:23<02:42, 11.99it/s]
 14%|█▎        | 304/2248 [00:23<03:45,  8.61it/s]
 14%|█▎        | 306/2248 [00:24<04:15,  7.60it/s]
 14%|█▎        | 307/2248 [00:24<04:04,  7.93it/s]
 14%|█▎        | 308/2248 [00:24<03:57,  8.18it/s]
 14%|█▎        | 309/2248 [00:24<04:12,  7.69it/s]
 14%|█▍        | 312/2248 [00:24<03:34,  9.01it/s]
 14%|█▍        | 313/2248 [00:25<04:02,  7.99it/s]
 14%|█▍        | 314/2248 [00:25<04:30,  7.15it/s]
 14%|█▍        | 315/2248 [00:25<04:55,  6.55it/s]
 14%|█▍        | 317/2248 [00:25<03:39,  8.79it/s]
 14%|█▍        | 319/2248 [00:25<03:07, 10.28it/s]
 14%|█▍        | 321/2248 [00:26<03:25,  9.40it/s]
 14%|█▍        | 323/2248 [00:26<04:30,  7.12it/s]
 14%|█▍        | 325/2248 [00:26<04:11,  7.65it/s]
 15%|█▍        | 327/2248 [00:26<04:09,  7.69it/s]
 15%|█▍        | 328/2248 [00:27<04:32,  7.04it/s]
 15%|█▍        | 331/2248 [00:27<03:15,  9.80it/s]
 15%|█▍        | 333/2248 [00:27<03:48,  8.40it/s]
 15%|█▍        | 336/2248 [00:27<02:51, 11.18it/s]
 15%|█▌        | 339/2248 [00:27<02:41, 11.81it/s]
 15%|█▌        | 341/2248 [00:28<02:38, 12.03it/s]
 15%|█▌        | 343/2248 [00:28<02:39, 11.95it/s]
 15%|█▌        | 345/2248 [00:28<04:04,  7.79it/s]
 15%|█▌        | 347/2248 [00:29<04:30,  7.03it/s]
 16%|█▌        | 349/2248 [00:29<03:54,  8.10it/s]
 16%|█▌        | 351/2248 [00:29<03:35,  8.80it/s]
 16%|█▌        | 353/2248 [00:29<04:09,  7.58it/s]
 16%|█▌        | 354/2248 [00:29<04:18,  7.32it/s]
 16%|█▌        | 355/2248 [00:30<04:16,  7.38it/s]
 16%|█▌        | 357/2248 [00:30<03:35,  8.78it/s]
 16%|█▌        | 359/2248 [00:30<03:00, 10.49it/s]
 16%|█▌        | 362/2248 [00:30<02:42, 11.63it/s]
 16%|█▌        | 364/2248 [00:30<03:04, 10.19it/s]
 16%|█▋        | 366/2248 [00:31<03:20,  9.41it/s]
 16%|█▋        | 368/2248 [00:31<03:08,  9.96it/s]
 16%|█▋        | 370/2248 [00:31<02:50, 10.98it/s]
 17%|█▋        | 372/2248 [00:31<03:24,  9.19it/s]
 17%|█▋        | 374/2248 [00:31<03:47,  8.24it/s]
 17%|█▋        | 377/2248 [00:32<03:15,  9.58it/s]
 17%|█▋        | 379/2248 [00:32<03:10,  9.81it/s]
 17%|█▋        | 381/2248 [00:32<03:24,  9.12it/s]
 17%|█▋        | 383/2248 [00:32<03:05, 10.05it/s]
 17%|█▋        | 385/2248 [00:33<04:07,  7.52it/s]
 17%|█▋        | 388/2248 [00:33<03:49,  8.11it/s]
 17%|█▋        | 389/2248 [00:33<04:16,  7.24it/s]
 17%|█▋        | 391/2248 [00:34<04:23,  7.06it/s]
 17%|█▋        | 392/2248 [00:34<04:39,  6.65it/s]
 17%|█▋        | 393/2248 [00:34<04:39,  6.63it/s]
 18%|█▊        | 394/2248 [00:34<05:05,  6.06it/s]
 18%|█▊        | 395/2248 [00:34<04:44,  6.51it/s]
 18%|█▊        | 397/2248 [00:34<03:49,  8.08it/s]
 18%|█▊        | 399/2248 [00:35<03:09,  9.77it/s]
 18%|█▊        | 403/2248 [00:35<01:57, 15.71it/s]
 18%|█▊        | 411/2248 [00:35<01:01, 29.94it/s]
 19%|█▊        | 416/2248 [00:35<00:54, 33.44it/s]
 19%|█▉        | 422/2248 [00:35<00:45, 39.95it/s]
 19%|█▉        | 428/2248 [00:35<00:41, 43.57it/s]
 19%|█▉        | 433/2248 [00:35<00:43, 41.44it/s]
 19%|█▉        | 438/2248 [00:36<01:21, 22.09it/s]
 20%|█▉        | 442/2248 [00:36<01:40, 17.93it/s]
 20%|█▉        | 445/2248 [00:36<01:55, 15.66it/s]
 20%|█▉        | 448/2248 [00:37<02:17, 13.05it/s]
 20%|██        | 450/2248 [00:37<02:22, 12.60it/s]
 20%|██        | 452/2248 [00:37<02:12, 13.56it/s]
 20%|██        | 454/2248 [00:37<02:12, 13.50it/s]
 20%|██        | 456/2248 [00:37<02:20, 12.80it/s]
 20%|██        | 458/2248 [00:37<02:12, 13.47it/s]
 20%|██        | 460/2248 [00:38<02:14, 13.25it/s]
 21%|██        | 462/2248 [00:38<02:07, 14.01it/s]
 21%|██        | 464/2248 [00:38<02:45, 10.75it/s]
 21%|██        | 466/2248 [00:38<03:11,  9.29it/s]
 21%|██        | 468/2248 [00:39<03:22,  8.80it/s]
 21%|██        | 471/2248 [00:39<03:21,  8.84it/s]
 21%|██        | 472/2248 [00:39<03:34,  8.28it/s]
 21%|██        | 473/2248 [00:39<03:53,  7.59it/s]
 21%|██        | 475/2248 [00:39<03:37,  8.15it/s]
 21%|██        | 477/2248 [00:40<03:18,  8.92it/s]
 21%|██▏       | 478/2248 [00:40<04:06,  7.17it/s]
 21%|██▏       | 479/2248 [00:40<04:11,  7.03it/s]
 21%|██▏       | 481/2248 [00:40<03:24,  8.64it/s]
 21%|██▏       | 482/2248 [00:40<03:36,  8.14it/s]
 22%|██▏       | 484/2248 [00:40<02:50, 10.32it/s]
 22%|██▏       | 486/2248 [00:41<03:38,  8.05it/s]
 22%|██▏       | 487/2248 [00:41<04:00,  7.32it/s]
 22%|██▏       | 488/2248 [00:41<04:53,  6.00it/s]
 22%|██▏       | 490/2248 [00:41<03:43,  7.86it/s]
 22%|██▏       | 492/2248 [00:42<04:02,  7.23it/s]
 22%|██▏       | 494/2248 [00:42<04:03,  7.22it/s]
 22%|██▏       | 495/2248 [00:42<04:24,  6.62it/s]
 22%|██▏       | 497/2248 [00:42<03:26,  8.46it/s]
 22%|██▏       | 499/2248 [00:43<03:19,  8.76it/s]
 22%|██▏       | 500/2248 [00:43<03:55,  7.42it/s]
 22%|██▏       | 502/2248 [00:43<03:04,  9.49it/s]
 22%|██▏       | 504/2248 [00:43<03:08,  9.24it/s]
 23%|██▎       | 506/2248 [00:43<02:36, 11.17it/s]
 23%|██▎       | 509/2248 [00:43<02:28, 11.72it/s]
 23%|██▎       | 511/2248 [00:44<02:11, 13.16it/s]
 23%|██▎       | 513/2248 [00:44<03:16,  8.84it/s]
 23%|██▎       | 515/2248 [00:44<04:07,  6.99it/s]
 23%|██▎       | 516/2248 [00:45<04:22,  6.59it/s]
 23%|██▎       | 517/2248 [00:45<04:36,  6.25it/s]
 23%|██▎       | 519/2248 [00:45<04:20,  6.64it/s]
 23%|██▎       | 522/2248 [00:45<02:57,  9.71it/s]
 23%|██▎       | 526/2248 [00:45<01:57, 14.72it/s]
 24%|██▎       | 530/2248 [00:45<01:31, 18.80it/s]
 24%|██▍       | 534/2248 [00:45<01:13, 23.19it/s]
 24%|██▍       | 540/2248 [00:46<00:54, 31.19it/s]
 24%|██▍       | 544/2248 [00:46<00:52, 32.28it/s]
 24%|██▍       | 550/2248 [00:46<00:43, 39.07it/s]
 25%|██▍       | 558/2248 [00:46<00:35, 48.12it/s]
 25%|██▌       | 565/2248 [00:46<00:32, 52.12it/s]
 25%|██▌       | 571/2248 [00:46<00:48, 34.82it/s]
 26%|██▌       | 576/2248 [00:47<01:28, 18.89it/s]
 26%|██▌       | 580/2248 [00:47<01:55, 14.47it/s]
 26%|██▌       | 583/2248 [00:48<02:08, 13.01it/s]
 26%|██▌       | 586/2248 [00:48<02:18, 12.01it/s]
 26%|██▌       | 588/2248 [00:48<02:21, 11.73it/s]
 26%|██▌       | 590/2248 [00:48<02:13, 12.45it/s]
 26%|██▋       | 592/2248 [00:49<02:37, 10.51it/s]
 26%|██▋       | 594/2248 [00:49<02:24, 11.46it/s]
 27%|██▋       | 596/2248 [00:49<02:10, 12.69it/s]
 27%|██▋       | 599/2248 [00:49<02:04, 13.23it/s]
 27%|██▋       | 601/2248 [00:49<02:11, 12.48it/s]
 27%|██▋       | 603/2248 [00:50<02:54,  9.42it/s]
 27%|██▋       | 605/2248 [00:50<03:22,  8.12it/s]
 27%|██▋       | 606/2248 [00:50<03:17,  8.33it/s]
 27%|██▋       | 607/2248 [00:50<03:43,  7.35it/s]
 27%|██▋       | 608/2248 [00:51<04:18,  6.34it/s]
 27%|██▋       | 609/2248 [00:51<04:22,  6.26it/s]
 27%|██▋       | 610/2248 [00:51<04:07,  6.63it/s]
 27%|██▋       | 612/2248 [00:51<03:00,  9.04it/s]
 28%|██▊       | 619/2248 [00:51<01:15, 21.44it/s]
 28%|██▊       | 625/2248 [00:51<00:54, 29.60it/s]
 28%|██▊       | 630/2248 [00:51<00:46, 34.48it/s]
 28%|██▊       | 636/2248 [00:51<00:40, 40.20it/s]
 29%|██▊       | 641/2248 [00:51<00:39, 40.73it/s]
 29%|██▉       | 648/2248 [00:52<00:33, 48.33it/s]
 29%|██▉       | 654/2248 [00:53<01:41, 15.66it/s]
 29%|██▉       | 658/2248 [00:53<01:50, 14.39it/s]
 29%|██▉       | 661/2248 [00:53<02:18, 11.45it/s]
 30%|██▉       | 664/2248 [00:54<02:27, 10.73it/s]
 30%|██▉       | 666/2248 [00:54<02:36, 10.10it/s]
 30%|██▉       | 668/2248 [00:54<02:48,  9.39it/s]
 30%|██▉       | 670/2248 [00:55<03:04,  8.57it/s]
 30%|██▉       | 673/2248 [00:55<02:25, 10.86it/s]
 30%|███       | 676/2248 [00:55<01:58, 13.31it/s]
 30%|███       | 678/2248 [00:55<02:38,  9.89it/s]
 30%|███       | 680/2248 [00:55<02:23, 10.96it/s]
 30%|███       | 682/2248 [00:55<02:19, 11.20it/s]
 30%|███       | 684/2248 [00:56<02:34, 10.13it/s]
 31%|███       | 686/2248 [00:56<02:30, 10.38it/s]
 31%|███       | 688/2248 [00:56<02:20, 11.09it/s]
 31%|███       | 690/2248 [00:56<03:00,  8.62it/s]
 31%|███       | 692/2248 [00:57<03:33,  7.30it/s]
 31%|███       | 694/2248 [00:57<03:23,  7.63it/s]
 31%|███       | 695/2248 [00:57<03:38,  7.11it/s]
 31%|███       | 697/2248 [00:57<02:57,  8.72it/s]
 31%|███       | 699/2248 [00:58<03:10,  8.12it/s]
 31%|███       | 701/2248 [00:58<02:39,  9.71it/s]
 31%|███▏      | 703/2248 [00:58<03:04,  8.37it/s]
 31%|███▏      | 705/2248 [00:58<03:27,  7.43it/s]
 31%|███▏      | 706/2248 [00:59<03:55,  6.55it/s]
 32%|███▏      | 709/2248 [00:59<03:10,  8.07it/s]
 32%|███▏      | 711/2248 [00:59<03:16,  7.82it/s]
 32%|███▏      | 713/2248 [00:59<03:25,  7.46it/s]
 32%|███▏      | 715/2248 [01:00<03:07,  8.17it/s]
 32%|███▏      | 717/2248 [01:00<02:46,  9.22it/s]
 32%|███▏      | 719/2248 [01:00<02:21, 10.79it/s]
 32%|███▏      | 721/2248 [01:00<02:14, 11.33it/s]
 32%|███▏      | 723/2248 [01:00<02:04, 12.24it/s]
 32%|███▏      | 725/2248 [01:00<02:07, 11.99it/s]
 32%|███▏      | 727/2248 [01:01<02:14, 11.35it/s]
 32%|███▏      | 729/2248 [01:01<02:12, 11.48it/s]
 33%|███▎      | 731/2248 [01:01<02:08, 11.81it/s]
 33%|███▎      | 733/2248 [01:01<02:55,  8.63it/s]
 33%|███▎      | 735/2248 [01:02<03:40,  6.87it/s]
 33%|███▎      | 736/2248 [01:02<04:25,  5.70it/s]
 33%|███▎      | 737/2248 [01:02<04:11,  6.02it/s]
 33%|███▎      | 738/2248 [01:02<04:29,  5.60it/s]
 33%|███▎      | 741/2248 [01:02<02:51,  8.80it/s]
 33%|███▎      | 743/2248 [01:03<03:08,  7.99it/s]
 33%|███▎      | 744/2248 [01:03<03:52,  6.46it/s]
 33%|███▎      | 746/2248 [01:03<02:59,  8.39it/s]
 33%|███▎      | 749/2248 [01:03<02:33,  9.80it/s]
 33%|███▎      | 751/2248 [01:04<02:43,  9.14it/s]
 33%|███▎      | 753/2248 [01:04<02:29, 10.01it/s]
 34%|███▎      | 755/2248 [01:04<02:35,  9.58it/s]
 34%|███▎      | 758/2248 [01:04<02:03, 12.07it/s]
 34%|███▍      | 761/2248 [01:04<02:08, 11.56it/s]
 34%|███▍      | 763/2248 [01:05<02:22, 10.40it/s]
 34%|███▍      | 765/2248 [01:05<02:09, 11.43it/s]
 34%|███▍      | 767/2248 [01:05<02:30,  9.82it/s]
 34%|███▍      | 769/2248 [01:05<02:12, 11.16it/s]
 34%|███▍      | 772/2248 [01:05<02:12, 11.17it/s]
 34%|███▍      | 774/2248 [01:06<02:46,  8.87it/s]
 35%|███▍      | 776/2248 [01:06<03:19,  7.37it/s]
 35%|███▍      | 778/2248 [01:07<03:22,  7.26it/s]
 35%|███▍      | 780/2248 [01:07<02:47,  8.79it/s]
 35%|███▍      | 782/2248 [01:07<02:51,  8.56it/s]
 35%|███▍      | 784/2248 [01:07<03:30,  6.96it/s]
 35%|███▍      | 786/2248 [01:07<02:54,  8.36it/s]
 35%|███▌      | 789/2248 [01:08<02:46,  8.79it/s]
 35%|███▌      | 791/2248 [01:08<02:51,  8.48it/s]
 35%|███▌      | 792/2248 [01:08<03:02,  7.96it/s]
 35%|███▌      | 794/2248 [01:08<03:07,  7.76it/s]
 35%|███▌      | 796/2248 [01:09<02:35,  9.32it/s]
 35%|███▌      | 798/2248 [01:09<02:33,  9.44it/s]
 36%|███▌      | 800/2248 [01:09<02:34,  9.36it/s]
 36%|███▌      | 803/2248 [01:09<02:04, 11.60it/s]
 36%|███▌      | 806/2248 [01:09<02:09, 11.13it/s]
 36%|███▌      | 808/2248 [01:10<01:55, 12.47it/s]
 36%|███▌      | 810/2248 [01:10<02:42,  8.84it/s]
 36%|███▌      | 812/2248 [01:10<03:12,  7.48it/s]
 36%|███▌      | 813/2248 [01:11<03:26,  6.94it/s]
 36%|███▌      | 814/2248 [01:11<03:52,  6.18it/s]
 36%|███▋      | 815/2248 [01:11<04:03,  5.87it/s]
 36%|███▋      | 816/2248 [01:11<04:12,  5.67it/s]
 36%|███▋      | 818/2248 [01:11<03:04,  7.75it/s]
 37%|███▋      | 824/2248 [01:11<01:24, 16.92it/s]
 37%|███▋      | 830/2248 [01:11<00:55, 25.47it/s]
 37%|███▋      | 835/2248 [01:12<00:47, 29.93it/s]
 37%|███▋      | 839/2248 [01:12<00:51, 27.30it/s]
 38%|███▊      | 843/2248 [01:12<00:54, 25.99it/s]
 38%|███▊      | 849/2248 [01:12<00:42, 32.82it/s]
 38%|███▊      | 854/2248 [01:12<00:40, 34.05it/s]
 38%|███▊      | 861/2248 [01:12<00:33, 41.51it/s]
 39%|███▊      | 866/2248 [01:13<00:55, 24.81it/s]
 39%|███▊      | 870/2248 [01:13<01:16, 17.96it/s]
 39%|███▉      | 873/2248 [01:13<01:23, 16.45it/s]
 39%|███▉      | 876/2248 [01:14<01:40, 13.65it/s]
 39%|███▉      | 878/2248 [01:14<01:54, 11.96it/s]
 39%|███▉      | 880/2248 [01:14<02:01, 11.30it/s]
 39%|███▉      | 882/2248 [01:14<02:19,  9.80it/s]
 39%|███▉      | 884/2248 [01:15<02:33,  8.88it/s]
 39%|███▉      | 886/2248 [01:15<02:39,  8.54it/s]
 40%|███▉      | 888/2248 [01:15<02:51,  7.92it/s]
 40%|███▉      | 890/2248 [01:16<02:57,  7.65it/s]
 40%|███▉      | 891/2248 [01:16<03:13,  7.02it/s]
 40%|███▉      | 893/2248 [01:16<02:32,  8.86it/s]
 40%|███▉      | 895/2248 [01:16<03:20,  6.76it/s]
 40%|███▉      | 896/2248 [01:17<03:43,  6.06it/s]
 40%|███▉      | 899/2248 [01:17<03:03,  7.36it/s]
 40%|████      | 901/2248 [01:17<02:34,  8.70it/s]
 40%|████      | 903/2248 [01:17<03:20,  6.70it/s]
 40%|████      | 905/2248 [01:18<02:41,  8.33it/s]
 40%|████      | 907/2248 [01:18<03:37,  6.16it/s]
 40%|████      | 908/2248 [01:18<03:58,  5.63it/s]
 40%|████      | 909/2248 [01:19<04:19,  5.16it/s]
 40%|████      | 910/2248 [01:19<04:33,  4.90it/s]
 41%|████      | 911/2248 [01:19<04:47,  4.64it/s]
 41%|████      | 912/2248 [01:19<04:29,  4.96it/s]
 41%|████      | 913/2248 [01:19<04:16,  5.20it/s]
 41%|████      | 915/2248 [01:20<03:29,  6.35it/s]
 41%|████      | 916/2248 [01:20<03:36,  6.15it/s]
 41%|████      | 917/2248 [01:20<03:23,  6.55it/s]
 41%|████      | 919/2248 [01:20<03:04,  7.20it/s]
 41%|████      | 920/2248 [01:20<03:39,  6.06it/s]
 41%|████      | 922/2248 [01:21<02:42,  8.15it/s]
 41%|████      | 924/2248 [01:21<02:41,  8.19it/s]
 41%|████      | 927/2248 [01:21<02:34,  8.55it/s]
 41%|████▏     | 929/2248 [01:21<02:43,  8.07it/s]
 41%|████▏     | 931/2248 [01:22<02:56,  7.46it/s]
 42%|████▏     | 934/2248 [01:22<02:43,  8.05it/s]
 42%|████▏     | 936/2248 [01:22<02:39,  8.22it/s]
 42%|████▏     | 938/2248 [01:23<02:51,  7.62it/s]
 42%|████▏     | 940/2248 [01:23<02:56,  7.41it/s]
 42%|████▏     | 941/2248 [01:23<03:14,  6.71it/s]
 42%|████▏     | 944/2248 [01:23<02:57,  7.35it/s]
 42%|████▏     | 946/2248 [01:24<02:48,  7.71it/s]
 42%|████▏     | 948/2248 [01:24<02:18,  9.36it/s]
 42%|████▏     | 950/2248 [01:24<02:17,  9.46it/s]
 42%|████▏     | 952/2248 [01:24<02:02, 10.57it/s]
 42%|████▏     | 954/2248 [01:24<01:58, 10.91it/s]
 43%|████▎     | 956/2248 [01:24<01:48, 11.89it/s]
 43%|████▎     | 958/2248 [01:25<02:02, 10.49it/s]
 43%|████▎     | 960/2248 [01:25<02:51,  7.53it/s]
 43%|████▎     | 962/2248 [01:25<02:35,  8.29it/s]
 43%|████▎     | 964/2248 [01:25<02:15,  9.47it/s]
 43%|████▎     | 966/2248 [01:26<02:48,  7.59it/s]
 43%|████▎     | 967/2248 [01:26<03:12,  6.65it/s]
 43%|████▎     | 969/2248 [01:26<03:10,  6.71it/s]
 43%|████▎     | 970/2248 [01:27<03:08,  6.79it/s]
 43%|████▎     | 972/2248 [01:27<02:29,  8.53it/s]
 43%|████▎     | 974/2248 [01:27<02:21,  8.99it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 314.11it/s]

[[np.int64(0), False, 5], [np.int64(1), False, 8], [np.int64(2), False, 11], [np.int64(3), False, 8], [np.int64(4), False, 12], [np.int64(6), False, 3], [np.int64(7), False, 13], [np.int64(9), False, 10], [np.int64(10), False, 3], [np.int64(11), False, 5], [np.int64(12), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5692, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [12:04<1:39:29, 60.29s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [12:04<1:09:00, 42.25s/it]

tensor(12.3548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6716, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2860, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [12:04<23:03, 14.57s/it]

tensor(12.3848, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4884, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6203, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [12:04<11:09,  7.20s/it]

tensor(12.4631, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6411, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1725, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [12:04<05:26,  3.59s/it]

tensor(12.4615, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3900, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4790, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [12:05<02:41,  1.82s/it]

tensor(12.4611, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0397, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5816, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4399, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [12:05<01:22,  1.05it/s]

tensor(12.4565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0468, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3845, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4512, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [12:05<00:44,  1.91it/s]

tensor(12.4621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0492, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6841, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0497, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8735, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [12:05<00:26,  3.16it/s]

tensor(12.5013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0497, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0191, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0497, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0547, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [12:06<00:17,  4.65it/s]

tensor(12.5393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0490, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9885, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5452, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0481, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9382, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [12:06<00:12,  6.08it/s]

tensor(12.5489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0471, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9803, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0462, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0716, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [12:06<00:10,  7.09it/s]

tensor(12.5588, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0456, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1714, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5501, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0455, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1764, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [12:06<00:09,  7.72it/s]

tensor(12.5324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0453, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2219, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2183, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [12:07<00:08,  8.18it/s]

tensor(12.4863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0422, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2568, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [12:07<00:08,  8.30it/s]

tensor(12.4495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2801, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0376, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3053, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [12:07<00:08,  8.50it/s]

tensor(12.4238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0378, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3267, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0383, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3371, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [12:07<00:07,  8.52it/s]

tensor(12.4047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3373, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0369, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3398, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [12:07<00:07,  8.61it/s]

tensor(12.3863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3353, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [12:08<00:07,  8.56it/s]

tensor(12.3761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3348, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3337, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [12:08<00:07,  8.62it/s]

tensor(12.3734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3370, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3353, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [12:08<00:06,  8.59it/s]

tensor(12.3674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3463, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3481, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [12:08<00:06,  8.58it/s]

tensor(12.3535, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3543, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3462, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3501, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [12:09<00:06,  8.58it/s]

tensor(12.3389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3610, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3728, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [12:09<00:06,  8.58it/s]

tensor(12.3272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3723, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3760, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [12:09<00:05,  8.57it/s]

tensor(12.3188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3800, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3155, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3866, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [12:09<00:05,  8.61it/s]

tensor(12.3122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3909, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([181, 164, 117, 125,  95, 348, 294, 190, 204,  37, 140, 103, 172,  78])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:48, 20.66it/s]
  0%|          | 7/2248 [00:00<01:19, 28.27it/s]
  0%|          | 11/2248 [00:00<01:10, 31.57it/s]
  1%|          | 16/2248 [00:00<01:00, 36.97it/s]
  1%|          | 20/2248 [00:00<01:01, 36.40it/s]
  1%|          | 27/2248 [00:00<00:48, 46.19it/s]
  1%|▏         | 33/2248 [00:00<00:45, 48.54it/s]
  2%|▏         | 38/2248 [00:00<00:48, 45.85it/s]
  2%|▏         | 45/2248 [00:01<00:43, 50.51it/s]
  2%|▏         | 52/2248 [00:01<00:39, 55.76it/s]
  3%|▎         | 58/2248 [00:01<00:45, 48.29it/s]
  3%|▎         | 64/2248 [00:01<00:53, 40.65it/s]
  3%|▎         | 70/2248 [00:01<00:48, 44.91it/s]
  3%|▎         | 75/2248 [00:01<01:09, 31.46it/s]
  4%|▎         | 79/2248 [00:02<01:38, 22.12it/s]
  4%|▎         | 83/2248 [00:02<01:34, 22.80it/s]
  4%|▍         | 86/2248 [00:02<01:46, 20.21it/s]
  4%|▍         | 89/2248 [00:02<01:57, 18.33it/s]
  4%|▍         | 95/2248 [00:02<01:27, 24.71it/s]
  4%|▍         | 99/2248 [00:03<01:56, 18.37it/s]
  5%|▍         | 103/2248 [00:03<01:39, 21.64it/s]
  5%|▍         | 106/2248 [00:03<01:56, 18.41it/s]
  5%|▍         | 111/2248 [00:03<02:02, 17.50it/s]
  5%|▌         | 114/2248 [00:04<02:50, 12.53it/s]
  5%|▌         | 116/2248 [00:04<03:09, 11.24it/s]
  5%|▌         | 118/2248 [00:04<03:33,  9.98it/s]
  5%|▌         | 121/2248 [00:05<02:50, 12.48it/s]
  5%|▌         | 123/2248 [00:05<03:10, 11.18it/s]
  6%|▌         | 126/2248 [00:05<03:11, 11.07it/s]
  6%|▌         | 128/2248 [00:06<05:08,  6.88it/s]
  6%|▌         | 131/2248 [00:06<03:52,  9.09it/s]
  6%|▌         | 133/2248 [00:06<04:16,  8.24it/s]
  6%|▌         | 135/2248 [00:06<04:22,  8.04it/s]
  6%|▌         | 137/2248 [00:07<04:31,  7.77it/s]
  6%|▌         | 138/2248 [00:07<05:06,  6.88it/s]
  6%|▋         | 141/2248 [00:07<03:33,  9.88it/s]
  6%|▋         | 145/2248 [00:07<02:56, 11.93it/s]
  7%|▋         | 148/2248 [00:07<02:26, 14.35it/s]
  7%|▋         | 150/2248 [00:08<02:54, 12.00it/s]
  7%|▋         | 152/2248 [00:08<04:00,  8.72it/s]
  7%|▋         | 154/2248 [00:08<03:36,  9.69it/s]
  7%|▋         | 156/2248 [00:08<03:30,  9.94it/s]
  7%|▋         | 158/2248 [00:09<05:16,  6.60it/s]
  7%|▋         | 159/2248 [00:09<05:26,  6.40it/s]
  7%|▋         | 160/2248 [00:09<05:36,  6.21it/s]
  7%|▋         | 162/2248 [00:10<05:37,  6.19it/s]
  7%|▋         | 164/2248 [00:10<04:19,  8.02it/s]
  7%|▋         | 166/2248 [00:10<05:48,  5.97it/s]
  7%|▋         | 168/2248 [00:10<04:33,  7.61it/s]
  8%|▊         | 170/2248 [00:11<05:07,  6.75it/s]
  8%|▊         | 173/2248 [00:11<04:55,  7.03it/s]
  8%|▊         | 175/2248 [00:11<04:06,  8.42it/s]
  8%|▊         | 177/2248 [00:12<04:39,  7.40it/s]
  8%|▊         | 178/2248 [00:12<05:43,  6.03it/s]
  8%|▊         | 180/2248 [00:12<04:31,  7.61it/s]
  8%|▊         | 183/2248 [00:12<04:19,  7.95it/s]
  8%|▊         | 185/2248 [00:13<03:38,  9.46it/s]
  8%|▊         | 187/2248 [00:13<04:13,  8.13it/s]
  8%|▊         | 189/2248 [00:13<04:38,  7.40it/s]
  8%|▊         | 191/2248 [00:13<03:56,  8.70it/s]
  9%|▊         | 195/2248 [00:14<03:48,  8.98it/s]
  9%|▉         | 197/2248 [00:14<03:17, 10.36it/s]
  9%|▉         | 199/2248 [00:14<03:33,  9.60it/s]
  9%|▉         | 201/2248 [00:14<03:47,  8.99it/s]
  9%|▉         | 203/2248 [00:15<04:24,  7.74it/s]
  9%|▉         | 205/2248 [00:15<04:36,  7.40it/s]
  9%|▉         | 207/2248 [00:15<04:07,  8.24it/s]
  9%|▉         | 209/2248 [00:16<05:13,  6.51it/s]
  9%|▉         | 210/2248 [00:16<06:00,  5.65it/s]
  9%|▉         | 211/2248 [00:16<05:38,  6.02it/s]
  9%|▉         | 213/2248 [00:16<04:26,  7.62it/s]
 10%|▉         | 216/2248 [00:16<03:03, 11.10it/s]
 10%|▉         | 222/2248 [00:16<01:45, 19.15it/s]
 10%|█         | 225/2248 [00:17<01:42, 19.65it/s]
 10%|█         | 231/2248 [00:17<01:17, 25.88it/s]
 11%|█         | 238/2248 [00:17<00:59, 34.03it/s]
 11%|█         | 245/2248 [00:17<00:49, 40.67it/s]
 11%|█         | 250/2248 [00:17<00:47, 42.10it/s]
 11%|█▏        | 257/2248 [00:17<00:42, 47.21it/s]
 12%|█▏        | 262/2248 [00:18<01:15, 26.28it/s]
 12%|█▏        | 266/2248 [00:18<02:12, 15.00it/s]
 12%|█▏        | 269/2248 [00:18<02:01, 16.28it/s]
 12%|█▏        | 272/2248 [00:19<02:26, 13.53it/s]
 12%|█▏        | 275/2248 [00:19<02:43, 12.09it/s]
 12%|█▏        | 277/2248 [00:19<02:36, 12.57it/s]
 12%|█▏        | 279/2248 [00:19<02:27, 13.31it/s]
 12%|█▎        | 281/2248 [00:20<02:51, 11.46it/s]
 13%|█▎        | 284/2248 [00:20<02:47, 11.73it/s]
 13%|█▎        | 286/2248 [00:20<03:30,  9.33it/s]
 13%|█▎        | 288/2248 [00:20<03:02, 10.74it/s]
 13%|█▎        | 290/2248 [00:20<02:59, 10.89it/s]
 13%|█▎        | 292/2248 [00:21<02:52, 11.31it/s]
 13%|█▎        | 295/2248 [00:21<02:54, 11.21it/s]
 13%|█▎        | 297/2248 [00:21<02:51, 11.35it/s]
 13%|█▎        | 299/2248 [00:21<03:48,  8.55it/s]
 13%|█▎        | 301/2248 [00:22<03:14,  9.99it/s]
 13%|█▎        | 303/2248 [00:22<04:49,  6.73it/s]
 14%|█▎        | 304/2248 [00:22<05:29,  5.89it/s]
 14%|█▎        | 306/2248 [00:23<05:09,  6.27it/s]
 14%|█▎        | 307/2248 [00:23<05:18,  6.09it/s]
 14%|█▎        | 308/2248 [00:23<06:27,  5.00it/s]
 14%|█▎        | 309/2248 [00:23<06:18,  5.12it/s]
 14%|█▍        | 311/2248 [00:23<04:31,  7.14it/s]
 14%|█▍        | 312/2248 [00:24<05:06,  6.32it/s]
 14%|█▍        | 313/2248 [00:24<05:22,  5.99it/s]
 14%|█▍        | 314/2248 [00:24<06:22,  5.06it/s]
 14%|█▍        | 315/2248 [00:24<05:55,  5.43it/s]
 14%|█▍        | 317/2248 [00:24<04:06,  7.85it/s]
 14%|█▍        | 320/2248 [00:25<03:12, 10.00it/s]
 14%|█▍        | 322/2248 [00:25<03:16,  9.81it/s]
 14%|█▍        | 324/2248 [00:25<03:52,  8.26it/s]
 14%|█▍        | 325/2248 [00:25<04:09,  7.70it/s]
 15%|█▍        | 327/2248 [00:26<03:35,  8.90it/s]
 15%|█▍        | 328/2248 [00:26<04:04,  7.86it/s]
 15%|█▍        | 330/2248 [00:26<03:28,  9.20it/s]
 15%|█▍        | 332/2248 [00:26<03:41,  8.63it/s]
 15%|█▍        | 335/2248 [00:26<02:42, 11.75it/s]
 15%|█▌        | 339/2248 [00:26<01:53, 16.81it/s]
 15%|█▌        | 342/2248 [00:27<01:51, 17.08it/s]
 15%|█▌        | 344/2248 [00:27<02:05, 15.16it/s]
 15%|█▌        | 346/2248 [00:27<02:51, 11.12it/s]
 15%|█▌        | 348/2248 [00:27<03:22,  9.40it/s]
 16%|█▌        | 350/2248 [00:28<04:33,  6.94it/s]
 16%|█▌        | 352/2248 [00:28<04:53,  6.47it/s]
 16%|█▌        | 353/2248 [00:28<05:00,  6.32it/s]
 16%|█▌        | 355/2248 [00:29<05:20,  5.91it/s]
 16%|█▌        | 356/2248 [00:29<05:30,  5.73it/s]
 16%|█▌        | 358/2248 [00:29<04:23,  7.18it/s]
 16%|█▌        | 362/2248 [00:29<03:27,  9.10it/s]
 16%|█▌        | 364/2248 [00:30<03:43,  8.44it/s]
 16%|█▋        | 366/2248 [00:30<03:44,  8.40it/s]
 16%|█▋        | 367/2248 [00:30<04:50,  6.47it/s]
 16%|█▋        | 370/2248 [00:30<03:22,  9.27it/s]
 17%|█▋        | 372/2248 [00:31<03:57,  7.90it/s]
 17%|█▋        | 374/2248 [00:31<04:16,  7.30it/s]
 17%|█▋        | 376/2248 [00:31<03:31,  8.86it/s]
 17%|█▋        | 378/2248 [00:31<03:16,  9.51it/s]
 17%|█▋        | 380/2248 [00:32<03:21,  9.26it/s]
 17%|█▋        | 382/2248 [00:32<03:34,  8.72it/s]
 17%|█▋        | 384/2248 [00:32<04:04,  7.62it/s]
 17%|█▋        | 385/2248 [00:32<04:12,  7.37it/s]
 17%|█▋        | 387/2248 [00:32<03:22,  9.20it/s]
 17%|█▋        | 389/2248 [00:33<04:23,  7.04it/s]
 17%|█▋        | 390/2248 [00:33<04:30,  6.86it/s]
 17%|█▋        | 391/2248 [00:33<04:23,  7.04it/s]
 17%|█▋        | 392/2248 [00:33<04:53,  6.32it/s]
 17%|█▋        | 393/2248 [00:34<05:53,  5.25it/s]
 18%|█▊        | 394/2248 [00:34<07:09,  4.31it/s]
 18%|█▊        | 395/2248 [00:34<06:53,  4.48it/s]
 18%|█▊        | 398/2248 [00:34<03:52,  7.96it/s]
 18%|█▊        | 404/2248 [00:34<01:49, 16.77it/s]
 18%|█▊        | 407/2248 [00:35<01:46, 17.28it/s]
 18%|█▊        | 413/2248 [00:35<01:11, 25.70it/s]
 19%|█▊        | 420/2248 [00:35<00:51, 35.33it/s]
 19%|█▉        | 427/2248 [00:35<00:44, 41.04it/s]
 19%|█▉        | 432/2248 [00:35<00:44, 40.68it/s]
 19%|█▉        | 437/2248 [00:36<01:31, 19.86it/s]
 20%|█▉        | 441/2248 [00:36<02:25, 12.46it/s]
 20%|█▉        | 444/2248 [00:37<02:40, 11.25it/s]
 20%|█▉        | 447/2248 [00:37<02:50, 10.57it/s]
 20%|█▉        | 449/2248 [00:37<02:52, 10.43it/s]
 20%|██        | 451/2248 [00:37<03:03,  9.80it/s]
 20%|██        | 453/2248 [00:38<03:21,  8.91it/s]
 20%|██        | 455/2248 [00:38<03:04,  9.70it/s]
 20%|██        | 457/2248 [00:38<03:12,  9.33it/s]
 20%|██        | 459/2248 [00:38<03:22,  8.85it/s]
 21%|██        | 461/2248 [00:39<02:51, 10.44it/s]
 21%|██        | 463/2248 [00:39<02:52, 10.34it/s]
 21%|██        | 465/2248 [00:39<02:45, 10.80it/s]
 21%|██        | 467/2248 [00:39<02:40, 11.12it/s]
 21%|██        | 469/2248 [00:39<03:15,  9.09it/s]
 21%|██        | 471/2248 [00:40<03:36,  8.20it/s]
 21%|██        | 472/2248 [00:40<04:24,  6.71it/s]
 21%|██        | 473/2248 [00:40<04:22,  6.76it/s]
 21%|██        | 475/2248 [00:40<04:15,  6.94it/s]
 21%|██        | 476/2248 [00:41<04:15,  6.92it/s]
 21%|██        | 477/2248 [00:41<04:35,  6.43it/s]
 21%|██▏       | 478/2248 [00:41<05:14,  5.62it/s]
 21%|██▏       | 479/2248 [00:41<06:17,  4.68it/s]
 21%|██▏       | 480/2248 [00:41<05:48,  5.08it/s]
 21%|██▏       | 481/2248 [00:42<06:08,  4.80it/s]
 21%|██▏       | 483/2248 [00:42<04:11,  7.01it/s]
 22%|██▏       | 486/2248 [00:42<03:25,  8.59it/s]
 22%|██▏       | 487/2248 [00:42<03:47,  7.74it/s]
 22%|██▏       | 488/2248 [00:42<04:12,  6.97it/s]
 22%|██▏       | 491/2248 [00:43<02:41, 10.85it/s]
 22%|██▏       | 493/2248 [00:43<02:57,  9.90it/s]
 22%|██▏       | 495/2248 [00:43<03:56,  7.40it/s]
 22%|██▏       | 497/2248 [00:43<03:20,  8.74it/s]
 22%|██▏       | 499/2248 [00:44<03:28,  8.37it/s]
 22%|██▏       | 501/2248 [00:44<03:33,  8.19it/s]
 22%|██▏       | 503/2248 [00:44<03:32,  8.20it/s]
 23%|██▎       | 506/2248 [00:44<02:37, 11.03it/s]
 23%|██▎       | 509/2248 [00:44<02:26, 11.84it/s]
 23%|██▎       | 511/2248 [00:45<02:14, 12.93it/s]
 23%|██▎       | 513/2248 [00:45<03:16,  8.82it/s]
 23%|██▎       | 515/2248 [00:45<04:10,  6.93it/s]
 23%|██▎       | 516/2248 [00:46<04:25,  6.51it/s]
 23%|██▎       | 517/2248 [00:46<04:51,  5.93it/s]
 23%|██▎       | 518/2248 [00:46<05:11,  5.56it/s]
 23%|██▎       | 519/2248 [00:46<05:21,  5.39it/s]
 23%|██▎       | 522/2248 [00:46<03:10,  9.08it/s]
 23%|██▎       | 524/2248 [00:47<02:41, 10.69it/s]
 24%|██▎       | 529/2248 [00:47<01:33, 18.41it/s]
 24%|██▍       | 535/2248 [00:47<01:09, 24.65it/s]
 24%|██▍       | 539/2248 [00:47<01:02, 27.25it/s]
 24%|██▍       | 543/2248 [00:47<00:59, 28.62it/s]
 24%|██▍       | 549/2248 [00:47<00:47, 35.51it/s]
 25%|██▍       | 553/2248 [00:47<00:46, 36.23it/s]
 25%|██▍       | 557/2248 [00:47<01:07, 24.92it/s]
 25%|██▍       | 561/2248 [00:48<01:02, 27.00it/s]
 25%|██▌       | 566/2248 [00:48<00:52, 31.97it/s]
 25%|██▌       | 571/2248 [00:48<01:13, 22.91it/s]
 26%|██▌       | 575/2248 [00:49<02:10, 12.79it/s]
 26%|██▌       | 579/2248 [00:49<02:08, 12.98it/s]
 26%|██▌       | 582/2248 [00:49<02:31, 11.00it/s]
 26%|██▌       | 585/2248 [00:50<02:11, 12.63it/s]
 26%|██▌       | 587/2248 [00:50<02:43, 10.14it/s]
 26%|██▌       | 589/2248 [00:50<03:14,  8.54it/s]
 26%|██▋       | 592/2248 [00:51<03:18,  8.33it/s]
 26%|██▋       | 594/2248 [00:51<02:53,  9.56it/s]
 27%|██▋       | 596/2248 [00:51<02:36, 10.55it/s]
 27%|██▋       | 599/2248 [00:51<02:32, 10.78it/s]
 27%|██▋       | 601/2248 [00:52<03:10,  8.66it/s]
 27%|██▋       | 603/2248 [00:52<02:52,  9.53it/s]
 27%|██▋       | 605/2248 [00:52<03:27,  7.93it/s]
 27%|██▋       | 606/2248 [00:52<04:12,  6.51it/s]
 27%|██▋       | 607/2248 [00:53<04:22,  6.25it/s]
 27%|██▋       | 609/2248 [00:53<04:31,  6.05it/s]
 27%|██▋       | 610/2248 [00:53<04:41,  5.82it/s]
 27%|██▋       | 612/2248 [00:53<03:29,  7.80it/s]
 27%|██▋       | 614/2248 [00:53<02:51,  9.55it/s]
 28%|██▊       | 619/2248 [00:53<01:37, 16.70it/s]
 28%|██▊       | 624/2248 [00:54<01:18, 20.80it/s]
 28%|██▊       | 630/2248 [00:54<00:56, 28.45it/s]
 28%|██▊       | 637/2248 [00:54<00:43, 37.28it/s]
 29%|██▊       | 644/2248 [00:54<00:36, 43.54it/s]
 29%|██▉       | 650/2248 [00:54<00:46, 34.53it/s]
 29%|██▉       | 655/2248 [00:55<01:25, 18.66it/s]
 29%|██▉       | 659/2248 [00:55<01:34, 16.81it/s]
 29%|██▉       | 662/2248 [00:56<02:03, 12.80it/s]
 30%|██▉       | 664/2248 [00:56<02:09, 12.22it/s]
 30%|██▉       | 666/2248 [00:56<02:22, 11.09it/s]
 30%|██▉       | 668/2248 [00:56<02:11, 12.02it/s]
 30%|██▉       | 670/2248 [00:56<02:39,  9.89it/s]
 30%|██▉       | 672/2248 [00:57<02:28, 10.62it/s]
 30%|███       | 677/2248 [00:57<01:56, 13.51it/s]
 30%|███       | 679/2248 [00:57<02:16, 11.49it/s]
 30%|███       | 681/2248 [00:57<02:31, 10.33it/s]
 30%|███       | 683/2248 [00:58<03:33,  7.33it/s]
 30%|███       | 684/2248 [00:58<04:16,  6.09it/s]
 30%|███       | 685/2248 [00:59<04:57,  5.26it/s]
 31%|███       | 686/2248 [00:59<05:50,  4.46it/s]
 31%|███       | 688/2248 [00:59<05:08,  5.06it/s]
 31%|███       | 690/2248 [00:59<03:55,  6.61it/s]
 31%|███       | 691/2248 [01:00<05:03,  5.13it/s]
 31%|███       | 692/2248 [01:00<05:02,  5.14it/s]
 31%|███       | 694/2248 [01:00<03:52,  6.69it/s]
 31%|███       | 695/2248 [01:00<04:45,  5.44it/s]
 31%|███       | 697/2248 [01:00<03:39,  7.07it/s]
 31%|███       | 698/2248 [01:01<04:14,  6.08it/s]
 31%|███       | 699/2248 [01:01<04:13,  6.11it/s]
 31%|███       | 701/2248 [01:01<03:02,  8.46it/s]
 31%|███▏      | 703/2248 [01:01<02:31, 10.19it/s]
 31%|███▏      | 705/2248 [01:01<02:40,  9.64it/s]
 32%|███▏      | 709/2248 [01:02<02:13, 11.57it/s]
 32%|███▏      | 711/2248 [01:02<02:09, 11.83it/s]
 32%|███▏      | 713/2248 [01:02<03:08,  8.14it/s]
 32%|███▏      | 715/2248 [01:02<02:46,  9.18it/s]
 32%|███▏      | 717/2248 [01:03<02:26, 10.47it/s]
 32%|███▏      | 719/2248 [01:03<02:11, 11.64it/s]
 32%|███▏      | 721/2248 [01:03<01:57, 13.03it/s]
 32%|███▏      | 724/2248 [01:03<01:52, 13.51it/s]
 32%|███▏      | 727/2248 [01:03<02:02, 12.39it/s]
 32%|███▏      | 729/2248 [01:04<02:53,  8.77it/s]
 33%|███▎      | 731/2248 [01:04<03:15,  7.76it/s]
 33%|███▎      | 733/2248 [01:04<03:33,  7.11it/s]
 33%|███▎      | 735/2248 [01:05<03:52,  6.51it/s]
 33%|███▎      | 736/2248 [01:05<04:30,  5.59it/s]
 33%|███▎      | 737/2248 [01:05<05:02,  4.99it/s]
 33%|███▎      | 738/2248 [01:06<05:26,  4.63it/s]
 33%|███▎      | 740/2248 [01:06<03:52,  6.48it/s]
 33%|███▎      | 742/2248 [01:06<03:43,  6.75it/s]
 33%|███▎      | 743/2248 [01:06<03:56,  6.37it/s]
 33%|███▎      | 744/2248 [01:06<04:34,  5.49it/s]
 33%|███▎      | 746/2248 [01:07<03:20,  7.50it/s]
 33%|███▎      | 748/2248 [01:07<02:40,  9.37it/s]
 33%|███▎      | 750/2248 [01:07<02:52,  8.69it/s]
 33%|███▎      | 752/2248 [01:07<03:53,  6.41it/s]
 33%|███▎      | 753/2248 [01:08<03:44,  6.65it/s]
 34%|███▎      | 754/2248 [01:08<04:12,  5.91it/s]
 34%|███▎      | 756/2248 [01:08<03:18,  7.53it/s]
 34%|███▍      | 761/2248 [01:08<02:11, 11.27it/s]
 34%|███▍      | 763/2248 [01:08<02:02, 12.16it/s]
 34%|███▍      | 766/2248 [01:08<01:45, 13.98it/s]
 34%|███▍      | 768/2248 [01:09<02:05, 11.76it/s]
 34%|███▍      | 770/2248 [01:09<01:54, 12.96it/s]
 34%|███▍      | 772/2248 [01:09<02:10, 11.30it/s]
 34%|███▍      | 774/2248 [01:09<02:28,  9.96it/s]
 35%|███▍      | 776/2248 [01:10<02:26, 10.02it/s]
 35%|███▍      | 778/2248 [01:10<02:42,  9.02it/s]
 35%|███▍      | 780/2248 [01:10<02:21, 10.41it/s]
 35%|███▍      | 782/2248 [01:10<02:20, 10.46it/s]
 35%|███▍      | 784/2248 [01:11<03:06,  7.86it/s]
 35%|███▍      | 786/2248 [01:11<02:34,  9.45it/s]
 35%|███▌      | 789/2248 [01:11<02:02, 11.89it/s]
 35%|███▌      | 791/2248 [01:11<02:03, 11.84it/s]
 35%|███▌      | 793/2248 [01:11<02:23, 10.13it/s]
 35%|███▌      | 795/2248 [01:11<02:11, 11.07it/s]
 35%|███▌      | 797/2248 [01:12<02:30,  9.62it/s]
 36%|███▌      | 800/2248 [01:12<02:00, 12.00it/s]
 36%|███▌      | 803/2248 [01:12<01:41, 14.22it/s]
 36%|███▌      | 806/2248 [01:12<01:44, 13.77it/s]
 36%|███▌      | 809/2248 [01:12<01:28, 16.19it/s]
 36%|███▌      | 811/2248 [01:13<02:21, 10.13it/s]
 36%|███▌      | 813/2248 [01:13<03:07,  7.66it/s]
 36%|███▋      | 815/2248 [01:14<03:40,  6.50it/s]
 36%|███▋      | 816/2248 [01:14<04:01,  5.92it/s]
 36%|███▋      | 817/2248 [01:14<03:47,  6.29it/s]
 37%|███▋      | 822/2248 [01:14<01:57, 12.18it/s]
 37%|███▋      | 824/2248 [01:14<01:49, 12.96it/s]
 37%|███▋      | 829/2248 [01:14<01:12, 19.66it/s]
 37%|███▋      | 835/2248 [01:14<00:52, 27.12it/s]
 37%|███▋      | 840/2248 [01:15<00:44, 31.83it/s]
 38%|███▊      | 847/2248 [01:15<00:34, 40.22it/s]
 38%|███▊      | 854/2248 [01:15<00:29, 46.55it/s]
 38%|███▊      | 861/2248 [01:15<00:26, 52.32it/s]
 39%|███▊      | 867/2248 [01:15<00:57, 23.90it/s]
 39%|███▉      | 872/2248 [01:16<01:29, 15.34it/s]
 39%|███▉      | 876/2248 [01:16<01:35, 14.33it/s]
 39%|███▉      | 879/2248 [01:17<01:53, 12.04it/s]
 39%|███▉      | 882/2248 [01:17<01:48, 12.54it/s]
 39%|███▉      | 884/2248 [01:17<02:08, 10.64it/s]
 39%|███▉      | 886/2248 [01:17<01:56, 11.69it/s]
 40%|███▉      | 888/2248 [01:18<02:15, 10.07it/s]
 40%|███▉      | 890/2248 [01:18<02:15, 10.06it/s]
 40%|███▉      | 893/2248 [01:18<01:54, 11.80it/s]
 40%|███▉      | 895/2248 [01:18<02:09, 10.42it/s]
 40%|███▉      | 897/2248 [01:19<02:12, 10.22it/s]
 40%|███▉      | 899/2248 [01:19<02:22,  9.44it/s]
 40%|████      | 901/2248 [01:19<02:06, 10.63it/s]
 40%|████      | 903/2248 [01:19<02:29,  9.03it/s]
 40%|████      | 906/2248 [01:20<02:28,  9.03it/s]
 40%|████      | 907/2248 [01:20<02:30,  8.90it/s]
 40%|████      | 908/2248 [01:20<02:51,  7.83it/s]
 40%|████      | 910/2248 [01:20<03:26,  6.49it/s]
 41%|████      | 911/2248 [01:21<04:15,  5.24it/s]
 41%|████      | 912/2248 [01:21<04:00,  5.56it/s]
 41%|████      | 914/2248 [01:21<03:02,  7.31it/s]
 41%|████      | 916/2248 [01:21<03:17,  6.75it/s]
 41%|████      | 917/2248 [01:21<03:17,  6.75it/s]
 41%|████      | 919/2248 [01:22<03:10,  6.96it/s]
 41%|████      | 920/2248 [01:22<03:24,  6.50it/s]
 41%|████      | 922/2248 [01:22<02:45,  8.01it/s]
 41%|████      | 924/2248 [01:22<02:38,  8.37it/s]
 41%|████      | 926/2248 [01:22<02:20,  9.42it/s]
 41%|████      | 927/2248 [01:23<02:46,  7.94it/s]
 41%|████▏     | 929/2248 [01:23<03:09,  6.96it/s]
 41%|████▏     | 931/2248 [01:23<03:00,  7.31it/s]
 42%|████▏     | 933/2248 [01:23<02:24,  9.07it/s]
 42%|████▏     | 935/2248 [01:24<02:58,  7.37it/s]
 42%|████▏     | 938/2248 [01:24<02:56,  7.44it/s]
 42%|████▏     | 940/2248 [01:25<03:26,  6.33it/s]
 42%|████▏     | 943/2248 [01:25<02:29,  8.73it/s]
 42%|████▏     | 945/2248 [01:25<02:35,  8.35it/s]
 42%|████▏     | 947/2248 [01:25<02:34,  8.43it/s]
 42%|████▏     | 949/2248 [01:25<02:40,  8.10it/s]
 42%|████▏     | 952/2248 [01:26<02:26,  8.83it/s]
 42%|████▏     | 953/2248 [01:26<03:02,  7.11it/s]
 43%|████▎     | 956/2248 [01:26<02:53,  7.43it/s]
 43%|████▎     | 958/2248 [01:27<03:06,  6.90it/s]
 43%|████▎     | 959/2248 [01:27<03:44,  5.73it/s]
 43%|████▎     | 960/2248 [01:27<04:16,  5.03it/s]
 43%|████▎     | 961/2248 [01:28<04:48,  4.46it/s]
 43%|████▎     | 962/2248 [01:28<05:03,  4.23it/s]
 43%|████▎     | 963/2248 [01:28<04:32,  4.72it/s]
 43%|████▎     | 965/2248 [01:28<03:49,  5.59it/s]
 43%|████▎     | 966/2248 [01:29<04:28,  4.78it/s]
 43%|████▎     | 967/2248 [01:29<04:32,  4.71it/s]
 43%|████▎     | 969/2248 [01:29<04:14,  5.02it/s]
 43%|████▎     | 970/2248 [01:29<04:07,  5.16it/s]
 43%|████▎     | 973/2248 [01:30<02:30,  8.46it/s]
 43%|████▎     | 975/2248 [01:30<02:54,  7.28it/s]
 43%|████▎     | 976/2248 [01:30<03:28,  6.11it/s]
 44%|████▎     | 978/2248 [01:30<03:05,  6.84it/s]
 44%|████▎     | 981/2248 [01:31<02:46,  7.62it/s]
 44%|████▎     | 983/2248 [01:31<02:19,  9.05it/s]
 44%|████▍     | 985/2248 [01:31<02:40,  7.87it/s]
 44%|████▍     | 987/2248 [01:32<03:03,  6.86it/s]
 44%|████▍     | 990/2248 [01:32<02:13,  9.42it/s]
 44%|████▍     | 992/2248 [01:32<02:19,  9.01it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 303.82it/s]

[[np.int64(0), False, 2], [np.int64(1), False, 6], [np.int64(3), False, 4], [np.int64(4), False, 0], [np.int64(5), False, 6], [np.int64(7), False, 8], [np.int64(9), False, 0], [np.int64(10), False, 6], [np.int64(11), False, 13], [np.int64(12), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7165, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [15:39<51:21, 62.89s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [15:39<35:15, 44.07s/it]

tensor(12.3072, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0057, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1754, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [15:39<11:23, 15.19s/it]

tensor(12.3073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2228, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3350, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [15:39<05:22,  7.51s/it]

tensor(12.3074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3893, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4584, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [15:40<02:33,  3.74s/it]

tensor(12.3091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5002, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3087, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5131, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [15:40<01:13,  1.89s/it]

tensor(12.3059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5304, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5635, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [15:40<00:36,  1.01it/s]

tensor(12.2947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2899, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5660, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [15:40<00:18,  1.84it/s]

tensor(12.2870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5713, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5776, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [15:41<00:10,  3.07it/s]

tensor(12.2857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5724, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2864, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5594, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [15:41<00:06,  4.56it/s]

tensor(12.2868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5610, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [15:41<00:04,  6.01it/s]

tensor(12.2847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5539, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5571, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [15:41<00:03,  7.09it/s]

tensor(12.2785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5529, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2749, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5499, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [15:41<00:03,  7.76it/s]

tensor(12.2720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5422, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5340, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [15:42<00:02,  8.18it/s]

tensor(12.2681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5300, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5300, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [15:42<00:02,  8.37it/s]

tensor(12.2662, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5288, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5265, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [15:42<00:02,  8.49it/s]

tensor(12.2645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5252, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5249, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [15:42<00:01,  8.55it/s]

tensor(12.2619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5259, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5270, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [15:43<00:01,  8.60it/s]

tensor(12.2584, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5271, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5281, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [15:43<00:01,  8.51it/s]

tensor(12.2548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5283, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5279, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [15:43<00:01,  8.53it/s]

tensor(12.2518, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5289, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5343, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [15:43<00:01,  8.52it/s]

tensor(12.2494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5388, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2483, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5465, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [15:44<00:00,  8.45it/s]

tensor(12.2471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5546, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5589, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [15:44<00:00,  8.51it/s]

tensor(12.2445, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5628, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [15:44<00:00,  8.48it/s]

tensor(12.2418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5639, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2404, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5636, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [15:44<00:00,  8.56it/s]

tensor(12.2390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0204, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5640, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5640, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [15:44<00:00,  3.15s/it]

tensor(12.2365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0206, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5684, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.002095937728881836
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 1
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.377654512556
NMI         : 0.471133561227
Runtime     : 970.49 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed1

==============================================================================================================
PRAGA RUN | S2-E18 | seed=2
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 1.588e-16
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(15.9357, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9314, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8071, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:33,  8.81it/s]

tensor(15.9247, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7191, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9160, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8368, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9076, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1397, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 7/300 [00:00<00:29,  9.87it/s]

tensor(15.8972, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6097, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8869, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8768, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9880, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:28, 10.09it/s]

tensor(15.8673, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8675, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8593, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8574, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8516, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9469, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:28, 10.21it/s]

tensor(15.8448, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1266, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8390, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3873, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8341, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7215, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:27, 10.24it/s]

tensor(15.8296, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1209, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8254, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5805, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8214, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0931, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:27, 10.27it/s]

tensor(15.8174, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6547, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8133, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2598, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8090, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9040, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:27, 10.28it/s]

tensor(15.8042, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5840, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7987, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2958, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7926, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0364, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:26, 10.28it/s]

tensor(15.7859, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8028, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7782, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5939, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7695, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4050, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:26, 10.35it/s]

tensor(15.7595, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2358, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7484, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0836, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9477, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 31/300 [00:03<00:25, 10.35it/s]

tensor(15.7220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7161, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6893, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6180, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:25, 10.33it/s]

tensor(15.6703, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5306, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4524, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3830, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 37/300 [00:03<00:25, 10.33it/s]

tensor(15.6016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2672, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2187, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:25, 10.38it/s]

tensor(15.5143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1773, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1411, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1111, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:24, 10.33it/s]

tensor(15.4078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0853, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0658, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0512, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:24, 10.31it/s]

tensor(15.2826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0415, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:04<00:24, 10.32it/s]

tensor(15.1448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0503, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:04<00:24, 10.34it/s]

tensor(15.0023, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9024, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:23, 10.33it/s]

tensor(14.8494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:23, 10.35it/s]

tensor(14.6779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5588, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:05<00:23, 10.33it/s]

tensor(14.4988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4385, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:23, 10.29it/s]

tensor(14.3226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:22, 10.31it/s]

tensor(14.1890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1202, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:06<00:22, 10.32it/s]

tensor(14.0856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0145, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:22, 10.26it/s]

tensor(13.9765, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9007, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:21, 10.32it/s]

tensor(13.8669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:07<00:21, 10.33it/s]

tensor(13.7799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:07<00:21, 10.28it/s]

tensor(13.6997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6446, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:20, 10.29it/s]

tensor(13.6163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:20, 10.24it/s]

tensor(13.5336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:08<00:20, 10.25it/s]

tensor(13.4554, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4060, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:20, 10.29it/s]

tensor(13.3819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3584, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3352, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:19, 10.24it/s]

tensor(13.3124, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:09<00:19, 10.30it/s]

tensor(13.2476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([166, 162,  82, 105,  98, 178, 182, 108, 237, 262,  54, 199, 358,  57])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 4/2248 [00:00<01:00, 36.87it/s]
  0%|          | 9/2248 [00:00<00:51, 43.36it/s]
  1%|          | 14/2248 [00:00<00:48, 46.29it/s]
  1%|          | 19/2248 [00:00<00:51, 43.38it/s]
  1%|          | 25/2248 [00:00<00:46, 48.15it/s]
  1%|▏         | 30/2248 [00:00<00:46, 48.05it/s]
  2%|▏         | 35/2248 [00:01<01:21, 27.08it/s]
  2%|▏         | 39/2248 [00:01<02:00, 18.27it/s]
  2%|▏         | 43/2248 [00:01<02:16, 16.14it/s]
  2%|▏         | 46/2248 [00:01<02:22, 15.42it/s]
  2%|▏         | 49/2248 [00:02<02:15, 16.17it/s]
  2%|▏         | 54/2248 [00:02<01:46, 20.51it/s]
  3%|▎         | 57/2248 [00:02<02:17, 15.93it/s]
  3%|▎         | 60/2248 [00:02<02:09, 16.89it/s]
  3%|▎         | 63/2248 [00:03<02:50, 12.80it/s]
  3%|▎         | 65/2248 [00:03<03:45,  9.67it/s]
  3%|▎         | 69/2248 [00:03<02:44, 13.24it/s]
  3%|▎         | 72/2248 [00:03<03:06, 11.66it/s]
  3%|▎         | 75/2248 [00:04<02:36, 13.90it/s]
  3%|▎         | 77/2248 [00:04<02:28, 14.62it/s]
  4%|▎         | 79/2248 [00:04<02:30, 14.40it/s]
  4%|▎         | 81/2248 [00:04<03:01, 11.93it/s]
  4%|▎         | 83/2248 [00:04<02:58, 12.14it/s]
  4%|▍         | 85/2248 [00:04<03:22, 10.68it/s]
  4%|▍         | 87/2248 [00:05<04:32,  7.92it/s]
  4%|▍         | 89/2248 [00:05<05:20,  6.73it/s]
  4%|▍         | 92/2248 [00:05<03:47,  9.46it/s]
  4%|▍         | 94/2248 [00:06<04:13,  8.49it/s]
  4%|▍         | 96/2248 [00:06<03:51,  9.32it/s]
  4%|▍         | 98/2248 [00:06<04:31,  7.93it/s]
  4%|▍         | 101/2248 [00:06<03:16, 10.91it/s]
  5%|▍         | 103/2248 [00:07<03:22, 10.62it/s]
  5%|▍         | 105/2248 [00:07<03:06, 11.50it/s]
  5%|▍         | 108/2248 [00:07<02:26, 14.61it/s]
  5%|▍         | 110/2248 [00:07<04:08,  8.61it/s]
  5%|▍         | 112/2248 [00:07<03:34,  9.94it/s]
  5%|▌         | 117/2248 [00:08<03:35,  9.89it/s]
  5%|▌         | 120/2248 [00:08<04:29,  7.89it/s]
  5%|▌         | 122/2248 [00:09<03:53,  9.09it/s]
  6%|▌         | 124/2248 [00:09<04:08,  8.55it/s]
 33%|███▎      | 99/300 [00:22<00:19, 10.30it/s]s]
  6%|▌         | 127/2248 [00:10<06:12,  5.69it/s]
  6%|▌         | 128/2248 [00:10<06:01,  5.86it/s]
  6%|▌         | 130/2248 [00:10<04:51,  7.27it/s]
  6%|▌         | 133/2248 [00:11<05:16,  6.68it/s]
  6%|▌         | 136/2248 [00:11<05:35,  6.29it/s]
  6%|▌         | 138/2248 [00:11<06:08,  5.72it/s]
  6%|▌         | 140/2248 [00:12<05:32,  6.35it/s]
  6%|▋         | 143/2248 [00:12<03:56,  8.89it/s]
  6%|▋         | 145/2248 [00:12<04:36,  7.62it/s]
  7%|▋         | 148/2248 [00:12<03:48,  9.19it/s]
  7%|▋         | 150/2248 [00:13<04:38,  7.53it/s]
  7%|▋         | 151/2248 [00:13<06:02,  5.78it/s]
  7%|▋         | 152/2248 [00:13<05:54,  5.91it/s]
  7%|▋         | 154/2248 [00:13<04:44,  7.36it/s]
  7%|▋         | 156/2248 [00:14<06:08,  5.67it/s]
  7%|▋         | 158/2248 [00:14<06:52,  5.06it/s]
  7%|▋         | 159/2248 [00:15<08:51,  3.93it/s]
  7%|▋         | 160/2248 [00:15<10:20,  3.37it/s]
  7%|▋         | 162/2248 [00:16<09:49,  3.54it/s]
  7%|▋         | 165/2248 [00:16<08:14,  4.21it/s]
  7%|▋         | 168/2248 [00:17<05:37,  6.17it/s]
  8%|▊         | 170/2248 [00:17<06:30,  5.32it/s]
  8%|▊         | 171/2248 [00:17<07:00,  4.94it/s]
  8%|▊         | 172/2248 [00:18<07:27,  4.64it/s]
  8%|▊         | 173/2248 [00:18<08:35,  4.03it/s]
  8%|▊         | 174/2248 [00:18<08:26,  4.09it/s]
  8%|▊         | 176/2248 [00:19<07:15,  4.75it/s]
  8%|▊         | 177/2248 [00:19<06:58,  4.95it/s]
  8%|▊         | 178/2248 [00:19<08:24,  4.10it/s]
  8%|▊         | 179/2248 [00:19<08:02,  4.29it/s]
  8%|▊         | 181/2248 [00:19<05:30,  6.25it/s]
  8%|▊         | 186/2248 [00:20<02:37, 13.12it/s]
  8%|▊         | 189/2248 [00:20<04:51,  7.08it/s]
  8%|▊         | 191/2248 [00:21<04:57,  6.92it/s]
  9%|▊         | 193/2248 [00:21<04:11,  8.16it/s]
  9%|▉         | 200/2248 [00:21<02:46, 12.27it/s]
  9%|▉         | 202/2248 [00:22<03:55,  8.67it/s]
  9%|▉         | 204/2248 [00:22<04:05,  8.31it/s]
  9%|▉         | 206/2248 [00:22<05:07,  6.64it/s]
  9%|▉         | 207/2248 [00:23<06:42,  5.08it/s]
  9%|▉         | 209/2248 [00:23<07:13,  4.71it/s]
  9%|▉         | 210/2248 [00:24<08:57,  3.79it/s]
  9%|▉         | 211/2248 [00:24<09:27,  3.59it/s]
  9%|▉         | 213/2248 [00:24<07:02,  4.81it/s]
 10%|▉         | 214/2248 [00:25<06:54,  4.91it/s]
 10%|▉         | 216/2248 [00:25<04:59,  6.78it/s]
 10%|▉         | 219/2248 [00:25<03:20, 10.11it/s]
 10%|▉         | 221/2248 [00:25<04:09,  8.12it/s]
 10%|▉         | 224/2248 [00:25<03:12, 10.53it/s]
 10%|█         | 226/2248 [00:26<03:47,  8.89it/s]
 10%|█         | 228/2248 [00:26<03:18, 10.17it/s]
 10%|█         | 232/2248 [00:26<02:14, 14.97it/s]
 10%|█         | 235/2248 [00:26<01:53, 17.80it/s]
 11%|█         | 241/2248 [00:26<01:15, 26.64it/s]
 11%|█         | 248/2248 [00:26<00:54, 36.41it/s]
 11%|█▏        | 253/2248 [00:27<01:26, 23.02it/s]
 12%|█▏        | 260/2248 [00:27<01:04, 30.62it/s]
 12%|█▏        | 266/2248 [00:27<00:55, 35.79it/s]
 12%|█▏        | 271/2248 [00:27<01:33, 21.09it/s]
 12%|█▏        | 275/2248 [00:27<01:25, 23.11it/s]
 12%|█▎        | 281/2248 [00:28<01:09, 28.47it/s]
 13%|█▎        | 287/2248 [00:28<00:58, 33.37it/s]
 13%|█▎        | 292/2248 [00:29<02:44, 11.90it/s]
 13%|█▎        | 296/2248 [00:29<02:45, 11.82it/s]
 13%|█▎        | 299/2248 [00:29<02:28, 13.12it/s]
 13%|█▎        | 302/2248 [00:30<03:40,  8.82it/s]
 14%|█▎        | 304/2248 [00:31<05:49,  5.57it/s]
 14%|█▎        | 306/2248 [00:32<06:29,  4.98it/s]
 14%|█▎        | 308/2248 [00:32<06:05,  5.31it/s]
 14%|█▎        | 309/2248 [00:32<06:08,  5.27it/s]
 14%|█▍        | 311/2248 [00:32<05:03,  6.38it/s]
 14%|█▍        | 312/2248 [00:33<06:06,  5.29it/s]
 14%|█▍        | 313/2248 [00:33<08:04,  4.00it/s]
 14%|█▍        | 314/2248 [00:33<08:39,  3.73it/s]
 14%|█▍        | 315/2248 [00:34<09:20,  3.45it/s]
 14%|█▍        | 317/2248 [00:34<06:24,  5.02it/s]
 14%|█▍        | 318/2248 [00:34<08:00,  4.02it/s]
 14%|█▍        | 319/2248 [00:34<07:42,  4.17it/s]
 14%|█▍        | 320/2248 [00:35<08:54,  3.60it/s]
 14%|█▍        | 322/2248 [00:35<07:21,  4.36it/s]
 14%|█▍        | 323/2248 [00:35<07:52,  4.07it/s]
 14%|█▍        | 324/2248 [00:36<07:34,  4.24it/s]
 15%|█▍        | 326/2248 [00:36<05:14,  6.12it/s]
 15%|█▍        | 332/2248 [00:36<02:47, 11.45it/s]
 15%|█▍        | 334/2248 [00:36<02:36, 12.26it/s]
 15%|█▍        | 336/2248 [00:36<02:56, 10.85it/s]
 15%|█▌        | 338/2248 [00:37<03:15,  9.78it/s]
 15%|█▌        | 340/2248 [00:37<03:36,  8.82it/s]
 15%|█▌        | 343/2248 [00:37<03:46,  8.40it/s]
 15%|█▌        | 344/2248 [00:38<04:37,  6.86it/s]
 15%|█▌        | 346/2248 [00:38<03:45,  8.44it/s]
 15%|█▌        | 348/2248 [00:39<06:15,  5.07it/s]
 16%|█▌        | 349/2248 [00:39<06:37,  4.77it/s]
 16%|█▌        | 350/2248 [00:39<06:45,  4.68it/s]
 16%|█▌        | 352/2248 [00:39<04:57,  6.36it/s]
 16%|█▌        | 353/2248 [00:40<07:02,  4.49it/s]
 16%|█▌        | 355/2248 [00:40<05:04,  6.21it/s]
 16%|█▌        | 357/2248 [00:40<06:00,  5.25it/s]
 16%|█▌        | 360/2248 [00:40<03:56,  7.99it/s]
 16%|█▌        | 362/2248 [00:41<05:01,  6.25it/s]
 16%|█▌        | 364/2248 [00:41<05:59,  5.24it/s]
 16%|█▋        | 366/2248 [00:42<04:46,  6.57it/s]
 16%|█▋        | 368/2248 [00:42<05:40,  5.52it/s]
 16%|█▋        | 369/2248 [00:42<06:08,  5.09it/s]
 17%|█▋        | 371/2248 [00:43<06:34,  4.75it/s]
 17%|█▋        | 374/2248 [00:43<04:24,  7.10it/s]
 17%|█▋        | 380/2248 [00:43<02:19, 13.37it/s]
 17%|█▋        | 386/2248 [00:43<01:32, 20.05it/s]
 17%|█▋        | 390/2248 [00:44<03:17,  9.43it/s]
 17%|█▋        | 393/2248 [00:45<03:45,  8.21it/s]
 18%|█▊        | 395/2248 [00:45<04:48,  6.43it/s]
 18%|█▊        | 398/2248 [00:45<03:44,  8.22it/s]
 18%|█▊        | 400/2248 [00:46<03:46,  8.15it/s]
 18%|█▊        | 402/2248 [00:46<04:14,  7.25it/s]
 18%|█▊        | 405/2248 [00:46<03:15,  9.43it/s]
 18%|█▊        | 412/2248 [00:46<01:46, 17.20it/s]
 19%|█▊        | 417/2248 [00:47<01:54, 15.99it/s]
 19%|█▊        | 420/2248 [00:47<01:44, 17.54it/s]
 19%|█▉        | 426/2248 [00:47<01:14, 24.32it/s]
 19%|█▉        | 430/2248 [00:47<01:40, 18.02it/s]
 19%|█▉        | 436/2248 [00:48<02:03, 14.71it/s]
 20%|█▉        | 439/2248 [00:48<01:54, 15.87it/s]
 20%|█▉        | 442/2248 [00:48<02:42, 11.11it/s]
 20%|█▉        | 444/2248 [00:49<03:33,  8.44it/s]
 20%|█▉        | 446/2248 [00:49<04:19,  6.95it/s]
 20%|█▉        | 449/2248 [00:49<03:22,  8.89it/s]
 20%|██        | 452/2248 [00:50<02:44, 10.89it/s]
 20%|██        | 455/2248 [00:50<02:15, 13.28it/s]
 20%|██        | 458/2248 [00:50<02:38, 11.29it/s]
 21%|██        | 463/2248 [00:51<02:51, 10.38it/s]
 21%|██        | 465/2248 [00:51<02:41, 11.07it/s]
 21%|██        | 467/2248 [00:51<02:57, 10.06it/s]
 21%|██        | 469/2248 [00:51<02:38, 11.26it/s]
 21%|██        | 472/2248 [00:52<03:34,  8.29it/s]
 21%|██        | 475/2248 [00:52<04:26,  6.66it/s]
 21%|██▏       | 478/2248 [00:52<03:24,  8.66it/s]
 21%|██▏       | 480/2248 [00:53<05:47,  5.09it/s]
 21%|██▏       | 482/2248 [00:54<06:16,  4.69it/s]
 22%|██▏       | 486/2248 [00:54<05:18,  5.53it/s]
 22%|██▏       | 487/2248 [00:55<06:22,  4.60it/s]
 22%|██▏       | 488/2248 [00:55<07:29,  3.92it/s]
 22%|██▏       | 490/2248 [00:55<05:39,  5.17it/s]
 22%|██▏       | 495/2248 [00:56<04:12,  6.95it/s]
 22%|██▏       | 497/2248 [00:56<03:37,  8.07it/s]
 22%|██▏       | 499/2248 [00:57<05:35,  5.21it/s]
 22%|██▏       | 500/2248 [00:57<06:27,  4.51it/s]
 22%|██▏       | 502/2248 [00:57<05:04,  5.73it/s]
 22%|██▏       | 505/2248 [00:57<03:35,  8.10it/s]
 23%|██▎       | 507/2248 [00:58<03:45,  7.73it/s]
 23%|██▎       | 509/2248 [00:58<05:38,  5.13it/s]
 23%|██▎       | 512/2248 [00:59<05:20,  5.42it/s]
 23%|██▎       | 514/2248 [00:59<05:00,  5.77it/s]
 23%|██▎       | 515/2248 [01:00<05:31,  5.23it/s]
 23%|██▎       | 517/2248 [01:00<04:43,  6.11it/s]
 23%|██▎       | 518/2248 [01:00<05:30,  5.24it/s]
 23%|██▎       | 519/2248 [01:00<05:52,  4.91it/s]
 23%|██▎       | 521/2248 [01:00<04:17,  6.70it/s]
 23%|██▎       | 524/2248 [01:01<02:57,  9.72it/s]
 23%|██▎       | 527/2248 [01:01<02:45, 10.41it/s]
 24%|██▎       | 529/2248 [01:01<02:26, 11.73it/s]
 24%|██▎       | 533/2248 [01:01<01:49, 15.63it/s]
 24%|██▍       | 536/2248 [01:01<01:36, 17.77it/s]
 24%|██▍       | 543/2248 [01:01<01:00, 28.19it/s]
 24%|██▍       | 547/2248 [01:02<01:11, 23.88it/s]
 25%|██▍       | 552/2248 [01:02<01:00, 27.91it/s]
 25%|██▍       | 556/2248 [01:02<01:00, 27.81it/s]
 25%|██▍       | 560/2248 [01:02<01:26, 19.44it/s]
 25%|██▌       | 567/2248 [01:02<01:02, 26.97it/s]
 25%|██▌       | 571/2248 [01:03<01:37, 17.12it/s]
 26%|██▌       | 574/2248 [01:04<04:09,  6.72it/s]
 26%|██▌       | 576/2248 [01:04<03:44,  7.45it/s]
 26%|██▌       | 578/2248 [01:05<04:22,  6.37it/s]
 26%|██▌       | 580/2248 [01:05<05:14,  5.31it/s]
 26%|██▌       | 582/2248 [01:06<07:07,  3.90it/s]
 26%|██▌       | 583/2248 [01:07<07:20,  3.78it/s]
 26%|██▌       | 586/2248 [01:07<06:23,  4.33it/s]
 26%|██▌       | 588/2248 [01:07<05:09,  5.37it/s]
 26%|██▌       | 589/2248 [01:08<05:16,  5.24it/s]
 26%|██▋       | 591/2248 [01:08<04:06,  6.72it/s]
 26%|██▋       | 593/2248 [01:08<05:06,  5.41it/s]
 26%|██▋       | 595/2248 [01:09<04:51,  5.68it/s]
 27%|██▋       | 597/2248 [01:09<04:01,  6.83it/s]
 27%|██▋       | 599/2248 [01:09<04:02,  6.79it/s]
 27%|██▋       | 600/2248 [01:09<04:41,  5.85it/s]
 27%|██▋       | 602/2248 [01:09<03:37,  7.58it/s]
 27%|██▋       | 604/2248 [01:10<05:57,  4.60it/s]
 27%|██▋       | 605/2248 [01:10<06:20,  4.32it/s]
 27%|██▋       | 607/2248 [01:11<06:45,  4.05it/s]
 27%|██▋       | 608/2248 [01:11<06:46,  4.03it/s]
 27%|██▋       | 609/2248 [01:12<06:43,  4.06it/s]
 27%|██▋       | 610/2248 [01:12<07:09,  3.81it/s]
 27%|██▋       | 612/2248 [01:12<04:49,  5.65it/s]
 27%|██▋       | 614/2248 [01:12<03:44,  7.28it/s]
 27%|██▋       | 616/2248 [01:12<03:14,  8.38it/s]
 27%|██▋       | 618/2248 [01:12<02:38, 10.30it/s]
 28%|██▊       | 620/2248 [01:13<03:32,  7.66it/s]
 28%|██▊       | 622/2248 [01:13<04:00,  6.77it/s]
 28%|██▊       | 624/2248 [01:13<03:15,  8.30it/s]
 28%|██▊       | 626/2248 [01:13<02:47,  9.68it/s]
 28%|██▊       | 631/2248 [01:13<01:36, 16.73it/s]
 28%|██▊       | 638/2248 [01:14<01:00, 26.82it/s]
 29%|██▊       | 645/2248 [01:14<01:08, 23.37it/s]
 29%|██▉       | 649/2248 [01:14<01:05, 24.42it/s]
 29%|██▉       | 653/2248 [01:16<03:20,  7.95it/s]
 29%|██▉       | 656/2248 [01:16<02:53,  9.16it/s]
 29%|██▉       | 659/2248 [01:16<03:05,  8.58it/s]
 29%|██▉       | 661/2248 [01:16<03:07,  8.44it/s]
 29%|██▉       | 663/2248 [01:17<03:19,  7.94it/s]
 30%|██▉       | 665/2248 [01:17<03:26,  7.66it/s]
 30%|██▉       | 667/2248 [01:17<03:38,  7.24it/s]
 30%|██▉       | 670/2248 [01:18<03:07,  8.40it/s]
 30%|██▉       | 672/2248 [01:18<02:52,  9.15it/s]
 30%|██▉       | 674/2248 [01:18<02:54,  9.03it/s]
 30%|███       | 677/2248 [01:18<03:14,  8.06it/s]
 30%|███       | 678/2248 [01:19<03:54,  6.69it/s]
 30%|███       | 679/2248 [01:19<03:41,  7.08it/s]
 30%|███       | 681/2248 [01:19<04:43,  5.53it/s]
 30%|███       | 682/2248 [01:20<06:25,  4.06it/s]
 30%|███       | 685/2248 [01:20<05:54,  4.41it/s]
 31%|███       | 687/2248 [01:21<06:17,  4.13it/s]
 31%|███       | 688/2248 [01:21<07:25,  3.50it/s]
 31%|███       | 691/2248 [01:22<04:43,  5.49it/s]
 31%|███       | 695/2248 [01:22<04:10,  6.19it/s]
 31%|███       | 697/2248 [01:22<03:29,  7.40it/s]
 31%|███       | 699/2248 [01:23<04:26,  5.82it/s]
 31%|███       | 700/2248 [01:23<04:58,  5.18it/s]
 31%|███       | 702/2248 [01:24<05:45,  4.48it/s]
 31%|███▏      | 704/2248 [01:24<06:17,  4.09it/s]
 31%|███▏      | 708/2248 [01:24<03:41,  6.96it/s]
 32%|███▏      | 710/2248 [01:25<03:40,  6.98it/s]
 32%|███▏      | 712/2248 [01:25<03:11,  8.01it/s]
 32%|███▏      | 714/2248 [01:25<04:42,  5.44it/s]
 32%|███▏      | 717/2248 [01:26<03:56,  6.47it/s]
 32%|███▏      | 718/2248 [01:26<04:16,  5.97it/s]
 32%|███▏      | 720/2248 [01:26<03:29,  7.30it/s]
 32%|███▏      | 725/2248 [01:26<01:58, 12.80it/s]
 32%|███▏      | 728/2248 [01:27<03:19,  7.62it/s]
 32%|███▏      | 730/2248 [01:27<03:34,  7.06it/s]
 33%|███▎      | 732/2248 [01:28<04:23,  5.76it/s]
 33%|███▎      | 733/2248 [01:28<05:28,  4.61it/s]
 33%|███▎      | 735/2248 [01:29<05:46,  4.36it/s]
 33%|███▎      | 736/2248 [01:29<06:59,  3.61it/s]
 33%|███▎      | 737/2248 [01:30<08:08,  3.09it/s]
 33%|███▎      | 738/2248 [01:30<09:17,  2.71it/s]
 33%|███▎      | 739/2248 [01:31<08:37,  2.92it/s]
 33%|███▎      | 741/2248 [01:31<05:42,  4.40it/s]
 33%|███▎      | 742/2248 [01:31<07:01,  3.57it/s]
 33%|███▎      | 743/2248 [01:32<08:03,  3.12it/s]
 33%|███▎      | 744/2248 [01:32<09:04,  2.76it/s]
 33%|███▎      | 746/2248 [01:32<05:45,  4.35it/s]
 33%|███▎      | 748/2248 [01:33<04:44,  5.28it/s]
 33%|███▎      | 749/2248 [01:33<06:19,  3.95it/s]
 33%|███▎      | 751/2248 [01:34<06:13,  4.01it/s]
 33%|███▎      | 752/2248 [01:34<07:22,  3.38it/s]
 34%|███▎      | 754/2248 [01:34<05:07,  4.87it/s]
 34%|███▍      | 759/2248 [01:34<02:27, 10.08it/s]
 34%|███▍      | 763/2248 [01:35<02:43,  9.06it/s]
 34%|███▍      | 765/2248 [01:35<02:55,  8.43it/s]
 34%|███▍      | 767/2248 [01:36<03:44,  6.58it/s]
 34%|███▍      | 769/2248 [01:36<03:06,  7.93it/s]
 34%|███▍      | 772/2248 [01:36<03:28,  7.07it/s]
 34%|███▍      | 774/2248 [01:37<05:38,  4.35it/s]
 34%|███▍      | 775/2248 [01:37<05:20,  4.60it/s]
 35%|███▍      | 776/2248 [01:37<05:00,  4.89it/s]
 35%|███▍      | 778/2248 [01:38<05:14,  4.67it/s]
 35%|███▍      | 781/2248 [01:38<03:27,  7.08it/s]
 35%|███▍      | 783/2248 [01:39<05:43,  4.27it/s]
 35%|███▍      | 784/2248 [01:39<06:49,  3.57it/s]
 35%|███▍      | 786/2248 [01:40<05:09,  4.72it/s]
 35%|███▌      | 788/2248 [01:40<03:57,  6.16it/s]
 35%|███▌      | 790/2248 [01:40<04:49,  5.04it/s]
 35%|███▌      | 792/2248 [01:41<05:23,  4.50it/s]
 35%|███▌      | 794/2248 [01:41<04:09,  5.83it/s]
 35%|███▌      | 797/2248 [01:41<04:14,  5.69it/s]
 36%|███▌      | 800/2248 [01:42<03:02,  7.95it/s]
 36%|███▌      | 803/2248 [01:42<02:46,  8.68it/s]
 36%|███▌      | 805/2248 [01:42<02:58,  8.07it/s]
 36%|███▌      | 807/2248 [01:43<03:53,  6.18it/s]
 36%|███▌      | 809/2248 [01:43<03:11,  7.50it/s]
 36%|███▌      | 811/2248 [01:43<04:05,  5.84it/s]
 36%|███▌      | 812/2248 [01:44<04:26,  5.38it/s]
 36%|███▌      | 814/2248 [01:44<04:55,  4.86it/s]
 36%|███▋      | 815/2248 [01:44<05:05,  4.69it/s]
 36%|███▋      | 816/2248 [01:45<05:10,  4.61it/s]
 36%|███▋      | 818/2248 [01:45<04:38,  5.13it/s]
 36%|███▋      | 820/2248 [01:45<03:36,  6.60it/s]
 37%|███▋      | 824/2248 [01:45<02:35,  9.16it/s]
 37%|███▋      | 826/2248 [01:46<03:07,  7.59it/s]
 37%|███▋      | 828/2248 [01:46<02:36,  9.10it/s]
 37%|███▋      | 830/2248 [01:46<02:37,  9.03it/s]
 37%|███▋      | 832/2248 [01:46<02:31,  9.38it/s]
 37%|███▋      | 834/2248 [01:46<02:12, 10.64it/s]
 37%|███▋      | 840/2248 [01:47<01:34, 14.83it/s]
 37%|███▋      | 842/2248 [01:47<01:31, 15.28it/s]
 38%|███▊      | 850/2248 [01:47<00:51, 27.10it/s]
 38%|███▊      | 854/2248 [01:47<01:06, 20.97it/s]
 38%|███▊      | 857/2248 [01:47<01:02, 22.12it/s]
 38%|███▊      | 863/2248 [01:47<00:46, 29.50it/s]
 39%|███▊      | 867/2248 [01:48<01:19, 17.40it/s]
 39%|███▊      | 870/2248 [01:48<01:59, 11.52it/s]
 39%|███▉      | 873/2248 [01:49<01:45, 13.03it/s]
 39%|███▉      | 877/2248 [01:49<02:06, 10.86it/s]
 39%|███▉      | 881/2248 [01:50<02:27,  9.29it/s]
 39%|███▉      | 885/2248 [01:50<01:54, 11.92it/s]
 40%|███▉      | 890/2248 [01:50<01:23, 16.33it/s]
 40%|███▉      | 894/2248 [01:50<01:29, 15.21it/s]
 40%|███▉      | 897/2248 [01:50<01:21, 16.51it/s]
 40%|████      | 900/2248 [01:51<02:01, 11.07it/s]
 40%|████      | 902/2248 [01:51<01:55, 11.66it/s]
 40%|████      | 905/2248 [01:51<02:10, 10.33it/s]
 40%|████      | 907/2248 [01:52<04:01,  5.56it/s]
 40%|████      | 909/2248 [01:53<04:35,  4.86it/s]
 40%|████      | 910/2248 [01:53<05:28,  4.07it/s]
 41%|████      | 911/2248 [01:54<06:38,  3.35it/s]
 41%|████      | 912/2248 [01:54<07:21,  3.03it/s]
 41%|████      | 915/2248 [01:54<04:24,  5.05it/s]
 41%|████      | 917/2248 [01:55<04:41,  4.73it/s]
 41%|████      | 920/2248 [01:56<04:30,  4.90it/s]
 41%|████      | 923/2248 [01:56<03:54,  5.66it/s]
 41%|████      | 924/2248 [01:56<04:46,  4.63it/s]
 41%|████      | 925/2248 [01:57<04:53,  4.51it/s]
 41%|████      | 927/2248 [01:57<04:58,  4.42it/s]
 41%|████▏     | 929/2248 [01:58<05:13,  4.21it/s]
 41%|████▏     | 930/2248 [01:58<04:40,  4.69it/s]
 42%|████▏     | 935/2248 [01:58<02:50,  7.69it/s]
 42%|████▏     | 937/2248 [01:58<02:58,  7.33it/s]
 42%|████▏     | 938/2248 [01:59<03:50,  5.68it/s]
 42%|████▏     | 940/2248 [01:59<03:09,  6.89it/s]
 42%|████▏     | 942/2248 [01:59<02:53,  7.54it/s]
 42%|████▏     | 944/2248 [01:59<02:28,  8.77it/s]
 42%|████▏     | 948/2248 [01:59<01:55, 11.27it/s]
 42%|████▏     | 950/2248 [02:00<01:47, 12.12it/s]
 42%|████▏     | 952/2248 [02:00<01:47, 12.03it/s]
 42%|████▏     | 954/2248 [02:00<01:39, 12.99it/s]
 43%|████▎     | 956/2248 [02:00<02:17,  9.39it/s]
 43%|████▎     | 958/2248 [02:01<02:41,  7.97it/s]
 43%|████▎     | 959/2248 [02:01<02:37,  8.17it/s]
 43%|████▎     | 960/2248 [02:01<03:00,  7.13it/s]
 43%|████▎     | 961/2248 [02:01<03:13,  6.64it/s]
 43%|████▎     | 962/2248 [02:01<03:58,  5.39it/s]
 43%|████▎     | 963/2248 [02:02<04:43,  4.53it/s]
 43%|████▎     | 964/2248 [02:02<04:32,  4.71it/s]
 43%|████▎     | 966/2248 [02:02<04:08,  5.16it/s]
 43%|████▎     | 968/2248 [02:02<03:08,  6.80it/s]
 43%|████▎     | 970/2248 [02:03<03:37,  5.86it/s]
 43%|████▎     | 972/2248 [02:03<02:53,  7.37it/s]
 43%|████▎     | 974/2248 [02:03<03:29,  6.08it/s]
 43%|████▎     | 976/2248 [02:04<03:36,  5.88it/s]
 44%|████▎     | 978/2248 [02:04<02:48,  7.53it/s]
 44%|████▎     | 981/2248 [02:04<02:17,  9.23it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 323.69it/s]

[[np.int64(0), False, 9], [np.int64(1), False, 12], [np.int64(2), False, 13], [np.int64(3), False, 11], [np.int64(4), False, 5], [np.int64(5), False, 9], [np.int64(6), False, 1], [np.int64(7), False, 12], [np.int64(8), False, 12], [np.int64(10), False, 0], [np.int64(11), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.2066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.0205, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:37<2:13:28, 40.24s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:37<1:49:27, 33.17s/it]

tensor(13.1841, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1300, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3489, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:38<50:53, 15.66s/it]

tensor(13.1524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5300, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1482, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7091, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [04:38<27:33,  8.57s/it]

tensor(13.1501, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8058, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1536, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8910, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [04:38<14:17,  4.49s/it]

tensor(13.1524, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9745, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0570, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [04:38<07:18,  2.32s/it]

tensor(13.1343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1573, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2450, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:38<03:46,  1.21s/it]

tensor(13.1316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2790, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1299, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3423, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:39<02:01,  1.52it/s]

tensor(13.1164, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3806, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4177, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▊      | 116/300 [04:39<01:31,  2.01it/s]

tensor(13.0556, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4343, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4441, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [04:39<00:45,  4.02it/s]

tensor(12.9852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4589, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4769, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [04:39<00:32,  5.52it/s]

tensor(12.9256, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4980, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9019, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5209, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [04:40<00:26,  6.74it/s]

tensor(12.8815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5272, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5583, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [04:40<00:23,  7.58it/s]

tensor(12.8492, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5876, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6118, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [04:40<00:21,  8.04it/s]

tensor(12.8225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6350, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8093, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6579, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:40<00:20,  8.32it/s]

tensor(12.7975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6675, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7874, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6969, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:41<00:19,  8.50it/s]

tensor(12.7799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7309, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7642, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [04:41<00:19,  8.47it/s]

tensor(12.7649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7887, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8199, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [04:41<00:19,  8.43it/s]

tensor(12.7439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8597, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [04:41<00:19,  8.46it/s]

tensor(12.7191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8714, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7040, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9010, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [04:41<00:19,  8.40it/s]

tensor(12.6882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9240, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9484, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:42<00:18,  8.43it/s]

tensor(12.6650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9459, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9660, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:42<00:18,  8.40it/s]

tensor(12.6499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9382, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6413, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9301, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [04:42<00:18,  8.54it/s]

tensor(12.6325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9536, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6250, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9828, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [04:42<00:18,  8.48it/s]

tensor(12.6186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0120, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0395, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:43<00:17,  8.53it/s]

tensor(12.6059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0611, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0602, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:43<00:17,  8.55it/s]

tensor(12.5960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0709, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([154, 242, 149,  61, 264, 344, 115, 105, 145, 144,  84, 100, 135, 206])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:19, 28.12it/s]
  0%|          | 9/2248 [00:00<00:48, 46.33it/s]
  1%|          | 16/2248 [00:00<00:40, 55.16it/s]
  1%|          | 23/2248 [00:00<00:38, 58.28it/s]
  1%|▏         | 31/2248 [00:00<00:34, 63.88it/s]
  2%|▏         | 38/2248 [00:01<01:36, 22.93it/s]
  2%|▏         | 43/2248 [00:01<02:12, 16.68it/s]
  2%|▏         | 47/2248 [00:02<02:26, 15.00it/s]
  2%|▏         | 50/2248 [00:02<02:38, 13.85it/s]
  2%|▏         | 56/2248 [00:02<01:55, 18.96it/s]
  3%|▎         | 62/2248 [00:02<01:48, 20.16it/s]
  3%|▎         | 65/2248 [00:02<01:44, 20.87it/s]
  3%|▎         | 71/2248 [00:03<01:38, 22.19it/s]
  3%|▎         | 74/2248 [00:03<01:37, 22.19it/s]
  3%|▎         | 77/2248 [00:03<02:29, 14.57it/s]
  4%|▎         | 81/2248 [00:03<02:26, 14.76it/s]
  4%|▎         | 83/2248 [00:04<02:54, 12.39it/s]
  4%|▍         | 85/2248 [00:04<03:08, 11.50it/s]
  4%|▍         | 87/2248 [00:04<04:09,  8.65it/s]
  4%|▍         | 89/2248 [00:05<04:51,  7.42it/s]
  4%|▍         | 91/2248 [00:05<04:09,  8.65it/s]
  4%|▍         | 94/2248 [00:05<03:57,  9.08it/s]
  4%|▍         | 96/2248 [00:05<04:09,  8.63it/s]
  4%|▍         | 97/2248 [00:06<04:06,  8.73it/s]
  4%|▍         | 98/2248 [00:06<04:06,  8.73it/s]
  4%|▍         | 100/2248 [00:06<04:35,  7.78it/s]
  4%|▍         | 101/2248 [00:06<04:51,  7.36it/s]
  5%|▍         | 102/2248 [00:06<05:04,  7.04it/s]
  5%|▍         | 104/2248 [00:06<04:08,  8.62it/s]
  5%|▍         | 107/2248 [00:07<03:32, 10.09it/s]
  5%|▍         | 109/2248 [00:07<03:59,  8.92it/s]
  5%|▍         | 110/2248 [00:07<04:42,  7.58it/s]
  5%|▍         | 112/2248 [00:07<03:45,  9.47it/s]
  5%|▌         | 114/2248 [00:08<03:55,  9.07it/s]
  5%|▌         | 117/2248 [00:08<04:19,  8.22it/s]
  5%|▌         | 119/2248 [00:08<03:46,  9.42it/s]
  5%|▌         | 121/2248 [00:09<04:34,  7.75it/s]
  5%|▌         | 123/2248 [00:09<04:37,  7.67it/s]
  6%|▌         | 125/2248 [00:09<05:29,  6.43it/s]
  6%|▌         | 126/2248 [00:10<06:41,  5.29it/s]
  6%|▌         | 128/2248 [00:10<07:21,  4.80it/s]
  6%|▌         | 130/2248 [00:10<05:36,  6.30it/s]
  6%|▌         | 132/2248 [00:10<05:14,  6.73it/s]
  6%|▌         | 133/2248 [00:11<06:43,  5.25it/s]
  6%|▌         | 134/2248 [00:11<06:10,  5.71it/s]
  6%|▌         | 135/2248 [00:11<07:42,  4.57it/s]
  6%|▌         | 136/2248 [00:12<08:34,  4.10it/s]
  6%|▌         | 138/2248 [00:12<07:54,  4.44it/s]
  6%|▌         | 140/2248 [00:12<05:43,  6.14it/s]
  6%|▋         | 145/2248 [00:12<04:01,  8.72it/s]
  7%|▋         | 147/2248 [00:13<03:28, 10.10it/s]
  7%|▋         | 149/2248 [00:13<03:36,  9.69it/s]
  7%|▋         | 151/2248 [00:13<03:38,  9.59it/s]
  7%|▋         | 154/2248 [00:13<02:50, 12.27it/s]
  7%|▋         | 156/2248 [00:14<03:50,  9.08it/s]
  7%|▋         | 158/2248 [00:14<04:14,  8.20it/s]
  7%|▋         | 160/2248 [00:14<05:44,  6.06it/s]
  7%|▋         | 162/2248 [00:15<04:55,  7.05it/s]
  7%|▋         | 164/2248 [00:15<04:09,  8.35it/s]
  7%|▋         | 166/2248 [00:15<04:40,  7.43it/s]
  7%|▋         | 168/2248 [00:15<03:56,  8.81it/s]
  8%|▊         | 170/2248 [00:15<03:18, 10.45it/s]
  8%|▊         | 172/2248 [00:16<03:35,  9.64it/s]
  8%|▊         | 174/2248 [00:16<05:03,  6.83it/s]
  8%|▊         | 176/2248 [00:16<04:19,  7.99it/s]
  8%|▊         | 178/2248 [00:17<05:41,  6.07it/s]
  8%|▊         | 179/2248 [00:17<05:38,  6.12it/s]
  8%|▊         | 181/2248 [00:17<04:32,  7.58it/s]
  8%|▊         | 184/2248 [00:17<03:52,  8.89it/s]
  8%|▊         | 187/2248 [00:18<04:18,  7.98it/s]
  8%|▊         | 188/2248 [00:18<04:38,  7.41it/s]
  8%|▊         | 191/2248 [00:18<04:01,  8.50it/s]
  9%|▊         | 192/2248 [00:18<04:30,  7.61it/s]
  9%|▊         | 194/2248 [00:18<03:41,  9.29it/s]
  9%|▉         | 197/2248 [00:19<03:14, 10.52it/s]
  9%|▉         | 199/2248 [00:19<03:43,  9.17it/s]
  9%|▉         | 202/2248 [00:19<04:14,  8.03it/s]
  9%|▉         | 204/2248 [00:20<04:19,  7.86it/s]
  9%|▉         | 205/2248 [00:20<05:36,  6.07it/s]
  9%|▉         | 207/2248 [00:21<06:15,  5.43it/s]
  9%|▉         | 210/2248 [00:21<05:59,  5.67it/s]
  9%|▉         | 211/2248 [00:21<07:05,  4.79it/s]
  9%|▉         | 212/2248 [00:22<08:19,  4.07it/s]
 10%|▉         | 214/2248 [00:22<06:03,  5.59it/s]
 10%|▉         | 216/2248 [00:22<05:16,  6.41it/s]
 10%|▉         | 219/2248 [00:22<03:38,  9.29it/s]
 10%|▉         | 221/2248 [00:22<03:46,  8.97it/s]
 10%|▉         | 224/2248 [00:23<02:51, 11.79it/s]
 10%|█         | 228/2248 [00:23<02:31, 13.33it/s]
 10%|█         | 231/2248 [00:23<02:09, 15.53it/s]
 11%|█         | 238/2248 [00:23<01:19, 25.26it/s]
 11%|█         | 245/2248 [00:23<00:58, 34.51it/s]
 11%|█         | 250/2248 [00:23<01:09, 28.71it/s]
 11%|█▏        | 254/2248 [00:24<01:07, 29.34it/s]
 12%|█▏        | 262/2248 [00:24<00:50, 39.36it/s]
 12%|█▏        | 267/2248 [00:24<00:48, 40.71it/s]
 12%|█▏        | 272/2248 [00:24<01:39, 19.93it/s]
 12%|█▏        | 276/2248 [00:24<01:29, 21.96it/s]
 12%|█▏        | 280/2248 [00:25<02:06, 15.58it/s]
 13%|█▎        | 285/2248 [00:25<01:39, 19.66it/s]
 13%|█▎        | 289/2248 [00:26<02:21, 13.84it/s]
 13%|█▎        | 292/2248 [00:26<03:49,  8.51it/s]
 13%|█▎        | 295/2248 [00:27<03:12, 10.15it/s]
 13%|█▎        | 298/2248 [00:27<03:39,  8.88it/s]
 13%|█▎        | 300/2248 [00:27<03:28,  9.35it/s]
 13%|█▎        | 303/2248 [00:28<03:40,  8.81it/s]
 14%|█▎        | 305/2248 [00:28<03:22,  9.60it/s]
 14%|█▎        | 307/2248 [00:28<03:03, 10.55it/s]
 14%|█▎        | 309/2248 [00:28<03:42,  8.70it/s]
 14%|█▍        | 311/2248 [00:28<03:49,  8.43it/s]
 14%|█▍        | 313/2248 [00:29<04:05,  7.87it/s]
 14%|█▍        | 314/2248 [00:29<04:04,  7.91it/s]
 14%|█▍        | 315/2248 [00:29<04:34,  7.04it/s]
 14%|█▍        | 317/2248 [00:29<03:33,  9.03it/s]
 14%|█▍        | 319/2248 [00:29<03:58,  8.09it/s]
 14%|█▍        | 320/2248 [00:30<03:54,  8.22it/s]
 14%|█▍        | 322/2248 [00:30<04:05,  7.84it/s]
 14%|█▍        | 323/2248 [00:30<05:16,  6.09it/s]
 14%|█▍        | 324/2248 [00:30<05:30,  5.82it/s]
 14%|█▍        | 325/2248 [00:31<06:46,  4.74it/s]
 15%|█▍        | 327/2248 [00:31<05:05,  6.28it/s]
 15%|█▍        | 329/2248 [00:31<03:58,  8.03it/s]
 15%|█▍        | 331/2248 [00:31<03:19,  9.61it/s]
 15%|█▍        | 333/2248 [00:32<04:35,  6.94it/s]
 15%|█▍        | 335/2248 [00:32<04:16,  7.45it/s]
 15%|█▍        | 337/2248 [00:32<04:20,  7.33it/s]
 15%|█▌        | 339/2248 [00:33<05:16,  6.04it/s]
 15%|█▌        | 342/2248 [00:33<03:43,  8.54it/s]
 15%|█▌        | 344/2248 [00:33<05:51,  5.42it/s]
 15%|█▌        | 346/2248 [00:34<04:43,  6.71it/s]
 15%|█▌        | 348/2248 [00:34<06:43,  4.71it/s]
 16%|█▌        | 349/2248 [00:35<07:43,  4.10it/s]
 16%|█▌        | 350/2248 [00:35<08:16,  3.82it/s]
 16%|█▌        | 353/2248 [00:35<06:30,  4.85it/s]
 16%|█▌        | 355/2248 [00:36<05:07,  6.15it/s]
 16%|█▌        | 356/2248 [00:36<06:15,  5.04it/s]
 16%|█▌        | 358/2248 [00:36<04:43,  6.66it/s]
 16%|█▌        | 360/2248 [00:36<03:53,  8.09it/s]
 16%|█▌        | 362/2248 [00:37<04:55,  6.39it/s]
 16%|█▌        | 364/2248 [00:37<05:34,  5.63it/s]
 16%|█▋        | 366/2248 [00:37<05:51,  5.36it/s]
 16%|█▋        | 368/2248 [00:38<04:34,  6.85it/s]
 17%|█▋        | 371/2248 [00:38<04:36,  6.79it/s]
 17%|█▋        | 373/2248 [00:38<03:50,  8.12it/s]
 17%|█▋        | 377/2248 [00:39<03:29,  8.94it/s]
 17%|█▋        | 381/2248 [00:39<02:29, 12.49it/s]
 17%|█▋        | 387/2248 [00:39<01:36, 19.29it/s]
 17%|█▋        | 390/2248 [00:39<03:04, 10.08it/s]
 17%|█▋        | 393/2248 [00:40<02:34, 12.03it/s]
 18%|█▊        | 396/2248 [00:40<03:02, 10.17it/s]
 18%|█▊        | 398/2248 [00:40<02:44, 11.25it/s]
 18%|█▊        | 400/2248 [00:40<02:53, 10.62it/s]
 18%|█▊        | 402/2248 [00:41<03:09,  9.72it/s]
 18%|█▊        | 405/2248 [00:41<02:32, 12.12it/s]
 18%|█▊        | 413/2248 [00:41<01:19, 23.21it/s]
 19%|█▊        | 418/2248 [00:41<01:06, 27.35it/s]
 19%|█▉        | 422/2248 [00:41<01:03, 28.79it/s]
 19%|█▉        | 428/2248 [00:41<00:54, 33.19it/s]
 19%|█▉        | 432/2248 [00:41<00:56, 32.08it/s]
 19%|█▉        | 436/2248 [00:41<00:58, 31.19it/s]
 20%|█▉        | 440/2248 [00:42<01:43, 17.45it/s]
 20%|█▉        | 443/2248 [00:42<02:30, 12.03it/s]
 20%|█▉        | 446/2248 [00:43<03:16,  9.17it/s]
 20%|█▉        | 448/2248 [00:43<03:00,  9.99it/s]
 20%|██        | 450/2248 [00:43<02:40, 11.18it/s]
 20%|██        | 456/2248 [00:43<01:39, 18.05it/s]
 21%|██        | 461/2248 [00:43<01:16, 23.34it/s]
 21%|██        | 465/2248 [00:44<01:35, 18.66it/s]
 21%|██        | 468/2248 [00:44<01:35, 18.73it/s]
 21%|██        | 471/2248 [00:44<01:35, 18.62it/s]
 21%|██        | 474/2248 [00:44<01:56, 15.22it/s]
 21%|██        | 476/2248 [00:45<02:13, 13.25it/s]
 21%|██▏       | 478/2248 [00:45<02:04, 14.22it/s]
 21%|██▏       | 480/2248 [00:45<02:45, 10.66it/s]
 21%|██▏       | 482/2248 [00:45<03:15,  9.03it/s]
 22%|██▏       | 484/2248 [00:46<03:25,  8.58it/s]
 22%|██▏       | 486/2248 [00:46<04:12,  6.98it/s]
 22%|██▏       | 487/2248 [00:46<04:43,  6.22it/s]
 22%|██▏       | 489/2248 [00:46<03:56,  7.44it/s]
 22%|██▏       | 491/2248 [00:47<03:45,  7.81it/s]
 22%|██▏       | 494/2248 [00:47<02:41, 10.89it/s]
 22%|██▏       | 496/2248 [00:47<02:52, 10.14it/s]
 22%|██▏       | 499/2248 [00:47<03:03,  9.51it/s]
 22%|██▏       | 501/2248 [00:48<03:34,  8.14it/s]
 22%|██▏       | 502/2248 [00:48<03:43,  7.80it/s]
 22%|██▏       | 504/2248 [00:48<03:03,  9.50it/s]
 23%|██▎       | 506/2248 [00:48<02:42, 10.73it/s]
 23%|██▎       | 508/2248 [00:48<02:45, 10.51it/s]
 23%|██▎       | 510/2248 [00:49<03:26,  8.44it/s]
 23%|██▎       | 512/2248 [00:49<03:59,  7.24it/s]
 23%|██▎       | 514/2248 [00:49<03:52,  7.45it/s]
 23%|██▎       | 516/2248 [00:49<03:24,  8.49it/s]
 23%|██▎       | 518/2248 [00:50<03:52,  7.44it/s]
 23%|██▎       | 520/2248 [00:50<03:37,  7.94it/s]
 23%|██▎       | 522/2248 [00:50<03:13,  8.91it/s]
 23%|██▎       | 523/2248 [00:50<03:20,  8.59it/s]
 23%|██▎       | 525/2248 [00:50<02:50, 10.08it/s]
 23%|██▎       | 527/2248 [00:51<02:24, 11.91it/s]
 24%|██▎       | 529/2248 [00:51<02:06, 13.57it/s]
 24%|██▎       | 533/2248 [00:51<01:35, 17.87it/s]
 24%|██▍       | 535/2248 [00:51<01:57, 14.59it/s]
 24%|██▍       | 537/2248 [00:51<01:50, 15.51it/s]
 24%|██▍       | 542/2248 [00:51<01:20, 21.14it/s]
 24%|██▍       | 545/2248 [00:52<01:45, 16.10it/s]
 24%|██▍       | 547/2248 [00:52<01:41, 16.76it/s]
 25%|██▍       | 552/2248 [00:52<01:13, 23.03it/s]
 25%|██▍       | 559/2248 [00:52<00:50, 33.14it/s]
 25%|██▌       | 563/2248 [00:52<00:56, 29.60it/s]
 25%|██▌       | 570/2248 [00:52<00:44, 37.91it/s]
 26%|██▌       | 575/2248 [00:53<02:27, 11.36it/s]
 26%|██▌       | 579/2248 [00:54<02:44, 10.17it/s]
 26%|██▌       | 582/2248 [00:54<03:06,  8.93it/s]
 26%|██▌       | 584/2248 [00:55<03:47,  7.31it/s]
 26%|██▌       | 586/2248 [00:55<03:28,  7.99it/s]
 26%|██▌       | 588/2248 [00:55<03:49,  7.25it/s]
 26%|██▌       | 590/2248 [00:56<03:19,  8.29it/s]
 26%|██▋       | 592/2248 [00:56<03:29,  7.89it/s]
 26%|██▋       | 594/2248 [00:56<02:57,  9.32it/s]
 27%|██▋       | 596/2248 [00:56<02:34, 10.68it/s]
 27%|██▋       | 598/2248 [00:56<02:21, 11.66it/s]
 27%|██▋       | 600/2248 [00:56<02:06, 13.05it/s]
 27%|██▋       | 603/2248 [00:57<02:55,  9.36it/s]
 27%|██▋       | 605/2248 [00:57<03:31,  7.77it/s]
 27%|██▋       | 607/2248 [00:58<04:13,  6.48it/s]
 27%|██▋       | 608/2248 [00:58<04:34,  5.98it/s]
 27%|██▋       | 609/2248 [00:58<04:13,  6.46it/s]
 27%|██▋       | 610/2248 [00:58<04:40,  5.84it/s]
 27%|██▋       | 613/2248 [00:58<03:52,  7.03it/s]
 27%|██▋       | 615/2248 [00:59<03:08,  8.66it/s]
 27%|██▋       | 617/2248 [00:59<03:16,  8.32it/s]
 28%|██▊       | 619/2248 [00:59<03:21,  8.10it/s]
 28%|██▊       | 620/2248 [00:59<03:45,  7.24it/s]
 28%|██▊       | 622/2248 [01:00<03:36,  7.50it/s]
 28%|██▊       | 624/2248 [01:00<02:59,  9.04it/s]
 28%|██▊       | 626/2248 [01:00<03:06,  8.70it/s]
 28%|██▊       | 630/2248 [01:00<01:58, 13.62it/s]
 28%|██▊       | 637/2248 [01:00<01:08, 23.35it/s]
 29%|██▊       | 644/2248 [01:00<00:48, 32.89it/s]
 29%|██▉       | 649/2248 [01:01<01:05, 24.58it/s]
 29%|██▉       | 653/2248 [01:01<02:16, 11.69it/s]
 29%|██▉       | 656/2248 [01:02<02:05, 12.72it/s]
 29%|██▉       | 659/2248 [01:02<02:21, 11.26it/s]
 29%|██▉       | 661/2248 [01:02<03:00,  8.77it/s]
 29%|██▉       | 663/2248 [01:03<03:02,  8.70it/s]
 30%|██▉       | 665/2248 [01:03<03:34,  7.39it/s]
 30%|██▉       | 669/2248 [01:03<02:26, 10.81it/s]
 30%|██▉       | 671/2248 [01:04<02:50,  9.22it/s]
 30%|██▉       | 673/2248 [01:04<02:59,  8.77it/s]
 30%|███       | 675/2248 [01:04<02:39,  9.87it/s]
 30%|███       | 677/2248 [01:04<03:26,  7.61it/s]
 30%|███       | 679/2248 [01:05<04:07,  6.33it/s]
 30%|███       | 682/2248 [01:05<03:16,  7.95it/s]
 30%|███       | 684/2248 [01:05<02:55,  8.90it/s]
 31%|███       | 686/2248 [01:05<02:57,  8.82it/s]
 31%|███       | 688/2248 [01:06<02:51,  9.09it/s]
 31%|███       | 690/2248 [01:06<02:37,  9.87it/s]
 31%|███       | 692/2248 [01:06<03:01,  8.59it/s]
 31%|███       | 694/2248 [01:06<02:34, 10.05it/s]
 31%|███       | 696/2248 [01:06<03:03,  8.48it/s]
 31%|███       | 698/2248 [01:07<02:42,  9.55it/s]
 31%|███       | 700/2248 [01:07<03:24,  7.55it/s]
 31%|███       | 702/2248 [01:07<03:37,  7.10it/s]
 31%|███▏      | 703/2248 [01:08<03:54,  6.60it/s]
 31%|███▏      | 704/2248 [01:08<03:39,  7.03it/s]
 31%|███▏      | 706/2248 [01:08<02:48,  9.14it/s]
 32%|███▏      | 709/2248 [01:08<01:59, 12.86it/s]
 32%|███▏      | 711/2248 [01:08<02:10, 11.74it/s]
 32%|███▏      | 713/2248 [01:08<01:55, 13.24it/s]
 32%|███▏      | 715/2248 [01:08<02:10, 11.71it/s]
 32%|███▏      | 717/2248 [01:09<04:12,  6.07it/s]
 32%|███▏      | 719/2248 [01:10<05:17,  4.82it/s]
 32%|███▏      | 721/2248 [01:10<04:12,  6.06it/s]
 32%|███▏      | 725/2248 [01:10<03:03,  8.28it/s]
 32%|███▏      | 727/2248 [01:10<03:05,  8.21it/s]
 32%|███▏      | 730/2248 [01:11<02:45,  9.15it/s]
 33%|███▎      | 733/2248 [01:11<02:58,  8.49it/s]
 33%|███▎      | 735/2248 [01:11<02:38,  9.52it/s]
 33%|███▎      | 737/2248 [01:12<03:10,  7.94it/s]
 33%|███▎      | 738/2248 [01:12<03:18,  7.61it/s]
 33%|███▎      | 740/2248 [01:12<02:47,  9.00it/s]
 33%|███▎      | 742/2248 [01:12<02:56,  8.54it/s]
 33%|███▎      | 743/2248 [01:12<03:45,  6.67it/s]
 33%|███▎      | 744/2248 [01:13<04:15,  5.89it/s]
 33%|███▎      | 746/2248 [01:13<03:14,  7.72it/s]
 33%|███▎      | 748/2248 [01:13<03:22,  7.39it/s]
 33%|███▎      | 749/2248 [01:13<04:26,  5.62it/s]
 33%|███▎      | 751/2248 [01:14<04:11,  5.95it/s]
 33%|███▎      | 752/2248 [01:14<05:10,  4.82it/s]
 34%|███▎      | 754/2248 [01:14<04:22,  5.68it/s]
 34%|███▎      | 756/2248 [01:14<03:30,  7.07it/s]
 34%|███▍      | 761/2248 [01:15<02:25, 10.19it/s]
 34%|███▍      | 764/2248 [01:15<02:05, 11.84it/s]
 34%|███▍      | 766/2248 [01:15<01:56, 12.72it/s]
 34%|███▍      | 768/2248 [01:15<02:33,  9.67it/s]
 34%|███▍      | 770/2248 [01:16<02:16, 10.84it/s]
 34%|███▍      | 772/2248 [01:16<02:50,  8.64it/s]
 34%|███▍      | 774/2248 [01:16<03:03,  8.04it/s]
 34%|███▍      | 775/2248 [01:17<03:49,  6.41it/s]
 35%|███▍      | 776/2248 [01:17<03:55,  6.25it/s]
 35%|███▍      | 778/2248 [01:17<03:23,  7.22it/s]
 35%|███▍      | 780/2248 [01:17<02:44,  8.91it/s]
 35%|███▍      | 782/2248 [01:17<02:37,  9.30it/s]
 35%|███▍      | 784/2248 [01:17<02:55,  8.33it/s]
 35%|███▍      | 786/2248 [01:18<02:29,  9.77it/s]
 35%|███▌      | 788/2248 [01:18<03:03,  7.96it/s]
 35%|███▌      | 792/2248 [01:18<02:26,  9.92it/s]
 35%|███▌      | 794/2248 [01:19<02:47,  8.66it/s]
 35%|███▌      | 796/2248 [01:19<02:22, 10.16it/s]
 35%|███▌      | 798/2248 [01:19<02:59,  8.07it/s]
 36%|███▌      | 800/2248 [01:19<03:02,  7.92it/s]
 36%|███▌      | 803/2248 [01:20<02:47,  8.60it/s]
 36%|███▌      | 805/2248 [01:20<02:42,  8.89it/s]
 36%|███▌      | 806/2248 [01:20<03:32,  6.80it/s]
 36%|███▌      | 808/2248 [01:20<02:49,  8.51it/s]
 36%|███▌      | 811/2248 [01:21<02:57,  8.08it/s]
 36%|███▌      | 813/2248 [01:21<03:20,  7.14it/s]
 36%|███▋      | 815/2248 [01:21<03:24,  6.99it/s]
 36%|███▋      | 816/2248 [01:21<03:26,  6.92it/s]
 36%|███▋      | 817/2248 [01:22<03:21,  7.11it/s]
 36%|███▋      | 819/2248 [01:22<02:44,  8.68it/s]
 36%|███▋      | 820/2248 [01:22<02:56,  8.09it/s]
 37%|███▋      | 822/2248 [01:22<02:18, 10.30it/s]
 37%|███▋      | 824/2248 [01:22<02:15, 10.48it/s]
 37%|███▋      | 826/2248 [01:22<02:02, 11.61it/s]
 37%|███▋      | 830/2248 [01:23<01:54, 12.35it/s]
 37%|███▋      | 832/2248 [01:23<02:11, 10.76it/s]
 37%|███▋      | 834/2248 [01:23<01:58, 11.95it/s]
 37%|███▋      | 836/2248 [01:23<01:46, 13.22it/s]
 37%|███▋      | 839/2248 [01:23<01:24, 16.60it/s]
 37%|███▋      | 841/2248 [01:23<01:42, 13.70it/s]
 38%|███▊      | 845/2248 [01:24<01:14, 18.71it/s]
 38%|███▊      | 852/2248 [01:24<00:47, 29.62it/s]
 38%|███▊      | 859/2248 [01:24<00:35, 38.65it/s]
 39%|███▊      | 866/2248 [01:24<00:30, 45.40it/s]
 39%|███▉      | 872/2248 [01:25<01:08, 19.98it/s]
 39%|███▉      | 876/2248 [01:25<01:20, 17.14it/s]
 39%|███▉      | 879/2248 [01:25<01:46, 12.91it/s]
 39%|███▉      | 882/2248 [01:26<02:05, 10.89it/s]
 39%|███▉      | 885/2248 [01:26<01:46, 12.85it/s]
 40%|███▉      | 888/2248 [01:26<02:12, 10.28it/s]
 40%|███▉      | 892/2248 [01:26<01:40, 13.54it/s]
 40%|███▉      | 895/2248 [01:27<02:21,  9.59it/s]
 40%|███▉      | 898/2248 [01:27<02:01, 11.13it/s]
 40%|████      | 900/2248 [01:27<02:12, 10.14it/s]
 40%|████      | 902/2248 [01:28<02:33,  8.76it/s]
 40%|████      | 904/2248 [01:28<02:19,  9.64it/s]
 40%|████      | 906/2248 [01:28<02:21,  9.51it/s]
 40%|████      | 908/2248 [01:29<03:31,  6.34it/s]
 40%|████      | 910/2248 [01:29<02:57,  7.55it/s]
 41%|████      | 912/2248 [01:29<03:30,  6.33it/s]
 41%|████      | 913/2248 [01:30<04:04,  5.46it/s]
 41%|████      | 914/2248 [01:30<04:02,  5.50it/s]
 41%|████      | 917/2248 [01:30<02:52,  7.69it/s]
 41%|████      | 919/2248 [01:30<02:26,  9.07it/s]
 41%|████      | 921/2248 [01:30<02:54,  7.59it/s]
 41%|████      | 923/2248 [01:31<02:26,  9.02it/s]
 41%|████      | 925/2248 [01:31<03:06,  7.09it/s]
 41%|████      | 927/2248 [01:31<03:12,  6.85it/s]
 41%|████▏     | 929/2248 [01:32<03:37,  6.07it/s]
 41%|████▏     | 931/2248 [01:32<03:01,  7.25it/s]
 42%|████▏     | 935/2248 [01:32<02:20,  9.32it/s]
 42%|████▏     | 937/2248 [01:32<02:26,  8.96it/s]
 42%|████▏     | 940/2248 [01:33<01:54, 11.43it/s]
 42%|████▏     | 942/2248 [01:33<02:00, 10.88it/s]
 42%|████▏     | 944/2248 [01:33<02:59,  7.28it/s]
 42%|████▏     | 946/2248 [01:33<02:29,  8.73it/s]
 42%|████▏     | 948/2248 [01:34<02:27,  8.81it/s]
 42%|████▏     | 951/2248 [01:34<02:26,  8.86it/s]
 42%|████▏     | 953/2248 [01:34<02:53,  7.49it/s]
 43%|████▎     | 957/2248 [01:35<02:36,  8.26it/s]
 43%|████▎     | 959/2248 [01:35<02:19,  9.26it/s]
 43%|████▎     | 961/2248 [01:35<02:45,  7.77it/s]
 43%|████▎     | 962/2248 [01:36<03:34,  5.99it/s]
 43%|████▎     | 963/2248 [01:36<04:36,  4.65it/s]
 43%|████▎     | 964/2248 [01:36<04:34,  4.67it/s]
 43%|████▎     | 966/2248 [01:37<04:28,  4.77it/s]
 43%|████▎     | 967/2248 [01:37<05:15,  4.07it/s]
 43%|████▎     | 969/2248 [01:37<04:49,  4.42it/s]
 43%|████▎     | 970/2248 [01:38<05:33,  3.83it/s]
 43%|████▎     | 971/2248 [01:38<05:12,  4.08it/s]
 43%|████▎     | 973/2248 [01:38<03:39,  5.80it/s]
 43%|████▎     | 976/2248 [01:39<03:14,  6.54it/s]
 44%|████▎     | 979/2248 [01:39<02:16,  9.32it/s]
 44%|████▎     | 981/2248 [01:39<02:42,  7.81it/s]
 44%|████▍     | 984/2248 [01:39<02:00, 10.47it/s]
 44%|████▍     | 986/2248 [01:40<02:30,  8.39it/s]
 44%|████▍     | 989/2248 [01:40<01:51, 11.25it/s]
 44%|████▍     | 991/2248 [01:40<02:22,  8.81it/s]
 44%|████▍     | 993/2248 [01:40<02:02, 10.28it/s]
 44%|████▍     | 998/2248 [01:41<01:56, 10.73it/s]
 44%|████▍     | 1000/2248 [01:41<02:26,  8.55it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 296.22it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 5], [np.int64(2), False, 11], [np.int64(3), False, 9], [np.int64(4), False, 8], [np.int64(6), False, 13], [np.int64(7), False, 9], [np.int64(9), False, 12], [np.int64(10), False, 9], [np.int64(11), False, 4], [np.int64(12), False, 5], [np.int64(13), False, 4]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-2.2924, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [08:23<2:44:02, 66.06s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [08:23<1:54:09, 46.28s/it]

tensor(12.6023, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8254, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6380, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [08:23<38:32, 15.95s/it]

tensor(12.6941, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6778, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2452, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [08:23<18:46,  7.88s/it]

tensor(12.7799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0463, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2422, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0471, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4799, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [08:24<09:12,  3.92s/it]

tensor(12.8361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0480, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6288, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0486, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6734, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [08:24<04:34,  1.98s/it]

tensor(12.8029, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0492, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7178, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7684, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0490, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7267, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [08:24<02:20,  1.03s/it]

tensor(12.7370, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0485, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7442, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0471, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8470, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [08:24<01:16,  1.78it/s]

tensor(12.7070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0458, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9131, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0135, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [08:25<00:44,  2.98it/s]

tensor(12.7074, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0435, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0955, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0421, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1181, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [08:25<00:29,  4.47it/s]

tensor(12.6774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0404, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6584, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0387, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0966, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [08:25<00:21,  5.89it/s]

tensor(12.6415, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1136, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1529, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [08:25<00:18,  7.04it/s]

tensor(12.6245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1464, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1595, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [08:26<00:16,  7.68it/s]

tensor(12.6197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1730, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2052, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [08:26<00:15,  8.16it/s]

tensor(12.5975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2332, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2673, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [08:26<00:14,  8.31it/s]

tensor(12.5664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2821, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5510, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2886, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [08:26<00:14,  8.47it/s]

tensor(12.5391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3055, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [08:26<00:13,  8.52it/s]

tensor(12.5230, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3244, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3431, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [08:27<00:13,  8.57it/s]

tensor(12.5031, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3463, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3424, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 186/300 [08:27<00:13,  8.55it/s]

tensor(12.4909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3416, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4862, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3498, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [08:27<00:13,  8.43it/s]

tensor(12.4814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3572, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3653, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [08:27<00:12,  8.52it/s]

tensor(12.4693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3773, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3810, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [08:28<00:12,  8.53it/s]

tensor(12.4585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3861, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4529, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3976, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [08:28<00:12,  8.60it/s]

tensor(12.4468, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4059, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4426, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4147, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [08:28<00:12,  8.55it/s]

tensor(12.4392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4244, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4342, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4273, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [08:28<00:11,  8.59it/s]

tensor(12.4294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4360, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4250, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4432, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:28<00:11,  8.57it/s]

tensor(12.4204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4477, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([127, 356, 170, 253,  97,  78, 257,  82, 172, 162, 121, 137, 117, 119])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 5/2248 [00:00<00:49, 45.20it/s]
  1%|          | 12/2248 [00:00<00:39, 56.70it/s]
  1%|          | 18/2248 [00:00<00:42, 52.19it/s]
  1%|          | 24/2248 [00:00<00:48, 45.86it/s]
  1%|▏         | 31/2248 [00:00<00:42, 52.33it/s]
  2%|▏         | 38/2248 [00:00<00:39, 55.32it/s]
  2%|▏         | 45/2248 [00:00<00:37, 58.15it/s]
  2%|▏         | 53/2248 [00:00<00:35, 61.32it/s]
  3%|▎         | 60/2248 [00:01<00:35, 61.51it/s]
  3%|▎         | 67/2248 [00:01<00:35, 61.65it/s]
  3%|▎         | 74/2248 [00:01<00:43, 50.30it/s]
  4%|▎         | 80/2248 [00:01<01:09, 31.03it/s]
  4%|▍         | 85/2248 [00:02<01:29, 24.17it/s]
  4%|▍         | 89/2248 [00:02<02:08, 16.79it/s]
  4%|▍         | 92/2248 [00:02<02:08, 16.79it/s]
  4%|▍         | 95/2248 [00:02<02:07, 16.85it/s]
  4%|▍         | 98/2248 [00:03<03:01, 11.84it/s]
  4%|▍         | 100/2248 [00:03<03:55,  9.13it/s]
  5%|▍         | 102/2248 [00:04<03:50,  9.32it/s]
  5%|▍         | 104/2248 [00:04<03:44,  9.56it/s]
  5%|▍         | 106/2248 [00:04<03:16, 10.91it/s]
  5%|▍         | 108/2248 [00:04<03:06, 11.48it/s]
  5%|▍         | 110/2248 [00:04<03:14, 11.02it/s]
  5%|▌         | 113/2248 [00:04<03:02, 11.70it/s]
  5%|▌         | 116/2248 [00:05<02:34, 13.83it/s]
  5%|▌         | 118/2248 [00:05<03:35,  9.89it/s]
  5%|▌         | 120/2248 [00:05<03:48,  9.33it/s]
  5%|▌         | 123/2248 [00:05<03:09, 11.24it/s]
  6%|▌         | 126/2248 [00:06<03:45,  9.43it/s]
  6%|▌         | 128/2248 [00:06<04:46,  7.41it/s]
  6%|▌         | 131/2248 [00:06<03:31,  9.99it/s]
  6%|▌         | 133/2248 [00:07<04:14,  8.31it/s]
  6%|▌         | 135/2248 [00:07<05:21,  6.56it/s]
  6%|▌         | 136/2248 [00:08<06:19,  5.56it/s]
  6%|▌         | 138/2248 [00:08<06:02,  5.83it/s]
  6%|▌         | 140/2248 [00:08<05:29,  6.40it/s]
  6%|▋         | 141/2248 [00:08<05:45,  6.09it/s]
  6%|▋         | 142/2248 [00:08<05:37,  6.25it/s]
  6%|▋         | 144/2248 [00:09<04:12,  8.32it/s]
  6%|▋         | 146/2248 [00:09<04:41,  7.46it/s]
  7%|▋         | 149/2248 [00:09<03:12, 10.92it/s]
  7%|▋         | 151/2248 [00:09<02:47, 12.54it/s]
  7%|▋         | 154/2248 [00:09<02:14, 15.58it/s]
  7%|▋         | 156/2248 [00:10<04:29,  7.77it/s]
  7%|▋         | 158/2248 [00:10<06:24,  5.44it/s]
  7%|▋         | 160/2248 [00:12<09:38,  3.61it/s]
  7%|▋         | 161/2248 [00:12<09:07,  3.82it/s]
  7%|▋         | 163/2248 [00:12<06:43,  5.17it/s]
  7%|▋         | 165/2248 [00:12<06:00,  5.77it/s]
  7%|▋         | 167/2248 [00:12<05:33,  6.25it/s]
  8%|▊         | 169/2248 [00:13<04:57,  6.98it/s]
  8%|▊         | 171/2248 [00:13<04:34,  7.56it/s]
  8%|▊         | 173/2248 [00:13<05:28,  6.32it/s]
  8%|▊         | 176/2248 [00:13<04:33,  7.58it/s]
  8%|▊         | 178/2248 [00:14<04:26,  7.77it/s]
  8%|▊         | 179/2248 [00:14<04:44,  7.27it/s]
  8%|▊         | 181/2248 [00:14<04:00,  8.58it/s]
  8%|▊         | 183/2248 [00:14<03:52,  8.87it/s]
  8%|▊         | 184/2248 [00:14<03:49,  8.99it/s]
  8%|▊         | 186/2248 [00:14<03:31,  9.74it/s]
  8%|▊         | 188/2248 [00:15<04:39,  7.38it/s]
  8%|▊         | 189/2248 [00:15<05:32,  6.19it/s]
  8%|▊         | 190/2248 [00:15<06:25,  5.34it/s]
  8%|▊         | 191/2248 [00:16<07:13,  4.75it/s]
  9%|▊         | 192/2248 [00:16<06:34,  5.22it/s]
  9%|▊         | 194/2248 [00:16<05:05,  6.73it/s]
  9%|▊         | 196/2248 [00:16<03:56,  8.69it/s]
  9%|▉         | 198/2248 [00:16<03:22, 10.10it/s]
  9%|▉         | 200/2248 [00:16<03:05, 11.02it/s]
  9%|▉         | 202/2248 [00:17<02:54, 11.70it/s]
  9%|▉         | 204/2248 [00:17<03:16, 10.39it/s]
  9%|▉         | 206/2248 [00:17<03:27,  9.83it/s]
  9%|▉         | 208/2248 [00:17<03:43,  9.15it/s]
  9%|▉         | 209/2248 [00:18<04:31,  7.52it/s]
  9%|▉         | 210/2248 [00:18<06:23,  5.31it/s]
  9%|▉         | 212/2248 [00:18<04:50,  7.00it/s]
 10%|▉         | 214/2248 [00:18<04:08,  8.20it/s]
 10%|▉         | 216/2248 [00:18<03:30,  9.67it/s]
 10%|▉         | 220/2248 [00:19<03:02, 11.13it/s]
 10%|▉         | 222/2248 [00:19<02:52, 11.75it/s]
 10%|█         | 225/2248 [00:19<02:17, 14.69it/s]
 10%|█         | 227/2248 [00:19<02:30, 13.39it/s]
 10%|█         | 229/2248 [00:19<02:27, 13.65it/s]
 10%|█         | 231/2248 [00:19<02:21, 14.23it/s]
 10%|█         | 235/2248 [00:20<01:42, 19.63it/s]
 11%|█         | 238/2248 [00:20<01:47, 18.65it/s]
 11%|█         | 241/2248 [00:20<01:37, 20.64it/s]
 11%|█         | 245/2248 [00:20<01:20, 25.00it/s]
 11%|█         | 249/2248 [00:20<01:19, 25.27it/s]
 11%|█         | 252/2248 [00:20<01:24, 23.53it/s]
 11%|█▏        | 255/2248 [00:20<01:23, 23.97it/s]
 12%|█▏        | 261/2248 [00:20<01:02, 31.92it/s]
 12%|█▏        | 265/2248 [00:21<02:15, 14.61it/s]
 12%|█▏        | 268/2248 [00:21<02:23, 13.79it/s]
 12%|█▏        | 271/2248 [00:22<04:04,  8.09it/s]
 12%|█▏        | 273/2248 [00:23<04:53,  6.73it/s]
 12%|█▏        | 275/2248 [00:23<05:44,  5.73it/s]
 12%|█▏        | 277/2248 [00:24<06:24,  5.12it/s]
 12%|█▏        | 279/2248 [00:24<05:18,  6.18it/s]
 12%|█▎        | 281/2248 [00:24<05:57,  5.51it/s]
 13%|█▎        | 282/2248 [00:25<06:59,  4.68it/s]
 13%|█▎        | 284/2248 [00:25<06:05,  5.37it/s]
 13%|█▎        | 286/2248 [00:25<05:37,  5.82it/s]
 13%|█▎        | 287/2248 [00:26<07:13,  4.52it/s]
 13%|█▎        | 289/2248 [00:26<05:48,  5.62it/s]
 13%|█▎        | 290/2248 [00:26<07:26,  4.39it/s]
 13%|█▎        | 291/2248 [00:27<08:42,  3.74it/s]
 13%|█▎        | 292/2248 [00:27<08:12,  3.97it/s]
 13%|█▎        | 294/2248 [00:27<05:48,  5.61it/s]
 13%|█▎        | 296/2248 [00:27<04:29,  7.24it/s]
 13%|█▎        | 298/2248 [00:28<05:39,  5.74it/s]
 13%|█▎        | 299/2248 [00:28<06:00,  5.40it/s]
 13%|█▎        | 300/2248 [00:28<05:27,  5.95it/s]
 13%|█▎        | 302/2248 [00:28<04:49,  6.73it/s]
 13%|█▎        | 303/2248 [00:29<07:00,  4.62it/s]
 14%|█▎        | 304/2248 [00:29<07:34,  4.28it/s]
 14%|█▎        | 305/2248 [00:29<07:19,  4.42it/s]
 14%|█▎        | 306/2248 [00:30<08:30,  3.80it/s]
 14%|█▎        | 307/2248 [00:30<10:10,  3.18it/s]
 14%|█▎        | 308/2248 [00:30<09:22,  3.45it/s]
 14%|█▎        | 309/2248 [00:31<11:22,  2.84it/s]
 14%|█▍        | 310/2248 [00:31<09:42,  3.33it/s]
 14%|█▍        | 312/2248 [00:31<06:58,  4.62it/s]
 14%|█▍        | 313/2248 [00:32<08:49,  3.65it/s]
 14%|█▍        | 314/2248 [00:32<10:41,  3.01it/s]
 14%|█▍        | 315/2248 [00:32<11:11,  2.88it/s]
 14%|█▍        | 316/2248 [00:33<09:01,  3.57it/s]
 14%|█▍        | 318/2248 [00:33<05:45,  5.59it/s]
 14%|█▍        | 320/2248 [00:33<04:40,  6.86it/s]
 14%|█▍        | 322/2248 [00:33<04:51,  6.61it/s]
 14%|█▍        | 323/2248 [00:33<05:48,  5.52it/s]
 14%|█▍        | 325/2248 [00:34<06:46,  4.73it/s]
 15%|█▍        | 327/2248 [00:34<05:43,  5.59it/s]
 15%|█▍        | 328/2248 [00:35<06:13,  5.14it/s]
 15%|█▍        | 329/2248 [00:35<05:43,  5.59it/s]
 15%|█▍        | 332/2248 [00:35<06:03,  5.26it/s]
 15%|█▍        | 334/2248 [00:35<04:41,  6.81it/s]
 15%|█▌        | 339/2248 [00:36<03:49,  8.33it/s]
 15%|█▌        | 341/2248 [00:36<03:45,  8.47it/s]
 15%|█▌        | 343/2248 [00:36<03:43,  8.51it/s]
 15%|█▌        | 344/2248 [00:37<05:38,  5.63it/s]
 15%|█▌        | 345/2248 [00:37<07:26,  4.26it/s]
 15%|█▌        | 346/2248 [00:38<09:16,  3.42it/s]
 15%|█▌        | 347/2248 [00:38<09:35,  3.31it/s]
 15%|█▌        | 348/2248 [00:38<09:30,  3.33it/s]
 16%|█▌        | 349/2248 [00:39<08:34,  3.69it/s]
 16%|█▌        | 350/2248 [00:39<09:30,  3.33it/s]
 16%|█▌        | 353/2248 [00:39<05:17,  5.97it/s]
 16%|█▌        | 354/2248 [00:39<05:36,  5.63it/s]
 16%|█▌        | 355/2248 [00:40<05:54,  5.34it/s]
 16%|█▌        | 356/2248 [00:40<07:54,  3.99it/s]
 16%|█▌        | 358/2248 [00:40<05:25,  5.80it/s]
 16%|█▌        | 361/2248 [00:40<03:26,  9.13it/s]
 16%|█▌        | 363/2248 [00:41<05:03,  6.21it/s]
 16%|█▋        | 366/2248 [00:41<05:22,  5.83it/s]
 16%|█▋        | 367/2248 [00:42<05:44,  5.46it/s]
 16%|█▋        | 369/2248 [00:42<05:12,  6.01it/s]
 17%|█▋        | 371/2248 [00:42<04:16,  7.32it/s]
 17%|█▋        | 373/2248 [00:42<03:44,  8.37it/s]
 17%|█▋        | 376/2248 [00:42<02:56, 10.60it/s]
 17%|█▋        | 378/2248 [00:43<04:04,  7.65it/s]
 17%|█▋        | 381/2248 [00:43<02:57, 10.49it/s]
 17%|█▋        | 384/2248 [00:43<03:21,  9.24it/s]
 17%|█▋        | 386/2248 [00:44<03:11,  9.74it/s]
 17%|█▋        | 388/2248 [00:44<03:33,  8.73it/s]
 17%|█▋        | 390/2248 [00:44<05:04,  6.10it/s]
 17%|█▋        | 391/2248 [00:45<04:59,  6.21it/s]
 17%|█▋        | 393/2248 [00:45<04:35,  6.74it/s]
 18%|█▊        | 394/2248 [00:45<05:07,  6.04it/s]
 18%|█▊        | 395/2248 [00:45<07:01,  4.39it/s]
 18%|█▊        | 397/2248 [00:46<05:05,  6.05it/s]
 18%|█▊        | 401/2248 [00:46<02:52, 10.73it/s]
 18%|█▊        | 405/2248 [00:46<02:00, 15.25it/s]
 18%|█▊        | 412/2248 [00:46<01:14, 24.70it/s]
 19%|█▊        | 416/2248 [00:46<01:09, 26.18it/s]
 19%|█▉        | 423/2248 [00:46<00:51, 35.63it/s]
 19%|█▉        | 430/2248 [00:46<00:42, 43.21it/s]
 19%|█▉        | 436/2248 [00:46<00:49, 36.78it/s]
 20%|█▉        | 441/2248 [00:47<02:12, 13.64it/s]
 20%|█▉        | 445/2248 [00:48<02:40, 11.22it/s]
 20%|█▉        | 448/2248 [00:49<03:27,  8.69it/s]
 20%|██        | 450/2248 [00:49<03:08,  9.54it/s]
 20%|██        | 453/2248 [00:49<02:50, 10.54it/s]
 20%|██        | 456/2248 [00:49<02:25, 12.31it/s]
 20%|██        | 458/2248 [00:49<02:41, 11.11it/s]
 20%|██        | 460/2248 [00:50<03:52,  7.69it/s]
 21%|██        | 462/2248 [00:50<03:45,  7.91it/s]
 21%|██        | 464/2248 [00:51<06:36,  4.50it/s]
 21%|██        | 467/2248 [00:51<04:49,  6.15it/s]
 21%|██        | 470/2248 [00:51<03:32,  8.35it/s]
 21%|██        | 472/2248 [00:52<05:07,  5.77it/s]
 21%|██        | 474/2248 [00:52<04:17,  6.89it/s]
 21%|██        | 476/2248 [00:53<05:38,  5.24it/s]
 21%|██▏       | 478/2248 [00:53<05:39,  5.22it/s]
 21%|██▏       | 479/2248 [00:54<07:00,  4.21it/s]
 21%|██▏       | 480/2248 [00:54<06:46,  4.35it/s]
 21%|██▏       | 481/2248 [00:54<06:59,  4.21it/s]
 21%|██▏       | 483/2248 [00:54<05:10,  5.68it/s]
 22%|██▏       | 485/2248 [00:54<03:52,  7.59it/s]
 22%|██▏       | 487/2248 [00:55<04:56,  5.93it/s]
 22%|██▏       | 489/2248 [00:55<03:50,  7.62it/s]
 22%|██▏       | 492/2248 [00:55<02:43, 10.77it/s]
 22%|██▏       | 495/2248 [00:55<02:16, 12.86it/s]
 22%|██▏       | 497/2248 [00:55<02:08, 13.60it/s]
 22%|██▏       | 499/2248 [00:56<02:37, 11.07it/s]
 22%|██▏       | 501/2248 [00:56<02:46, 10.52it/s]
 22%|██▏       | 504/2248 [00:56<02:06, 13.81it/s]
 23%|██▎       | 509/2248 [00:56<02:30, 11.55it/s]
 23%|██▎       | 511/2248 [00:57<02:22, 12.23it/s]
 23%|██▎       | 513/2248 [00:57<02:35, 11.19it/s]
 23%|██▎       | 515/2248 [00:58<05:18,  5.45it/s]
 23%|██▎       | 517/2248 [00:58<04:21,  6.61it/s]
 23%|██▎       | 519/2248 [00:58<04:00,  7.20it/s]
 23%|██▎       | 521/2248 [00:58<04:05,  7.05it/s]
 23%|██▎       | 523/2248 [00:59<03:27,  8.30it/s]
 23%|██▎       | 527/2248 [00:59<02:26, 11.75it/s]
 24%|██▎       | 531/2248 [00:59<01:51, 15.34it/s]
 24%|██▎       | 533/2248 [00:59<02:13, 12.88it/s]
 24%|██▍       | 535/2248 [00:59<02:15, 12.61it/s]
 24%|██▍       | 537/2248 [00:59<02:06, 13.52it/s]
 24%|██▍       | 542/2248 [00:59<01:25, 20.05it/s]
 24%|██▍       | 545/2248 [01:00<01:17, 21.87it/s]
 24%|██▍       | 548/2248 [01:00<01:20, 21.24it/s]
 25%|██▍       | 551/2248 [01:00<01:22, 20.59it/s]
 25%|██▍       | 554/2248 [01:00<02:01, 13.97it/s]
 25%|██▍       | 556/2248 [01:00<02:06, 13.36it/s]
 25%|██▍       | 558/2248 [01:01<02:14, 12.53it/s]
 25%|██▍       | 560/2248 [01:01<02:11, 12.79it/s]
 25%|██▌       | 563/2248 [01:01<01:47, 15.71it/s]
 25%|██▌       | 566/2248 [01:01<01:30, 18.58it/s]
 25%|██▌       | 571/2248 [01:01<01:32, 18.14it/s]
 26%|██▌       | 574/2248 [01:02<03:31,  7.91it/s]
 26%|██▌       | 576/2248 [01:02<03:07,  8.93it/s]
 26%|██▌       | 579/2248 [01:03<02:57,  9.38it/s]
 26%|██▌       | 581/2248 [01:03<03:13,  8.60it/s]
 26%|██▌       | 583/2248 [01:03<03:58,  6.99it/s]
 26%|██▌       | 584/2248 [01:04<04:28,  6.19it/s]
 26%|██▌       | 586/2248 [01:04<04:28,  6.20it/s]
 26%|██▌       | 588/2248 [01:04<03:38,  7.58it/s]
 26%|██▋       | 591/2248 [01:04<02:47,  9.89it/s]
 26%|██▋       | 593/2248 [01:05<03:04,  8.99it/s]
 26%|██▋       | 595/2248 [01:05<02:37, 10.48it/s]
 27%|██▋       | 598/2248 [01:05<02:03, 13.38it/s]
 27%|██▋       | 600/2248 [01:05<03:02,  9.04it/s]
 27%|██▋       | 602/2248 [01:05<02:44,  9.98it/s]
 27%|██▋       | 604/2248 [01:06<04:16,  6.40it/s]
 27%|██▋       | 606/2248 [01:07<07:14,  3.78it/s]
 27%|██▋       | 607/2248 [01:07<07:36,  3.59it/s]
 27%|██▋       | 608/2248 [01:08<08:31,  3.21it/s]
 27%|██▋       | 609/2248 [01:08<07:42,  3.55it/s]
 27%|██▋       | 610/2248 [01:08<08:30,  3.21it/s]
 27%|██▋       | 612/2248 [01:09<05:51,  4.66it/s]
 27%|██▋       | 613/2248 [01:09<05:15,  5.18it/s]
 27%|██▋       | 615/2248 [01:09<03:58,  6.84it/s]
 27%|██▋       | 617/2248 [01:09<03:06,  8.73it/s]
 28%|██▊       | 619/2248 [01:09<02:36, 10.38it/s]
 28%|██▊       | 621/2248 [01:09<02:24, 11.27it/s]
 28%|██▊       | 623/2248 [01:09<02:24, 11.24it/s]
 28%|██▊       | 626/2248 [01:09<01:49, 14.86it/s]
 28%|██▊       | 633/2248 [01:10<01:01, 26.27it/s]
 28%|██▊       | 640/2248 [01:10<00:45, 35.69it/s]
 29%|██▊       | 645/2248 [01:10<00:42, 37.94it/s]
 29%|██▉       | 650/2248 [01:10<01:00, 26.60it/s]
 29%|██▉       | 654/2248 [01:11<02:54,  9.15it/s]
 29%|██▉       | 657/2248 [01:11<02:30, 10.55it/s]
 29%|██▉       | 660/2248 [01:12<03:01,  8.75it/s]
 29%|██▉       | 662/2248 [01:12<03:20,  7.90it/s]
 30%|██▉       | 664/2248 [01:13<04:01,  6.56it/s]
 30%|██▉       | 666/2248 [01:13<04:21,  6.05it/s]
 30%|██▉       | 667/2248 [01:13<04:15,  6.18it/s]
 30%|██▉       | 669/2248 [01:14<03:27,  7.60it/s]
 30%|██▉       | 671/2248 [01:14<03:37,  7.25it/s]
 30%|███       | 675/2248 [01:14<02:18, 11.40it/s]
 30%|███       | 677/2248 [01:14<02:40,  9.78it/s]
 30%|███       | 680/2248 [01:14<02:07, 12.28it/s]
 30%|███       | 682/2248 [01:15<02:25, 10.73it/s]
 30%|███       | 684/2248 [01:15<04:10,  6.24it/s]
 31%|███       | 686/2248 [01:16<04:57,  5.24it/s]
 31%|███       | 687/2248 [01:16<05:02,  5.16it/s]
 31%|███       | 688/2248 [01:16<04:57,  5.25it/s]
 31%|███       | 690/2248 [01:16<03:43,  6.98it/s]
 31%|███       | 692/2248 [01:17<04:13,  6.13it/s]
 31%|███       | 694/2248 [01:17<04:45,  5.45it/s]
 31%|███       | 696/2248 [01:18<04:23,  5.90it/s]
 31%|███       | 698/2248 [01:18<03:54,  6.61it/s]
 31%|███       | 699/2248 [01:18<04:10,  6.17it/s]
 31%|███       | 700/2248 [01:18<04:22,  5.89it/s]
 31%|███       | 702/2248 [01:19<05:42,  4.52it/s]
 31%|███▏      | 704/2248 [01:19<05:57,  4.32it/s]
 31%|███▏      | 707/2248 [01:19<03:52,  6.62it/s]
 32%|███▏      | 709/2248 [01:20<03:28,  7.39it/s]
 32%|███▏      | 711/2248 [01:20<02:56,  8.70it/s]
 32%|███▏      | 713/2248 [01:20<03:54,  6.53it/s]
 32%|███▏      | 714/2248 [01:20<03:43,  6.87it/s]
 32%|███▏      | 715/2248 [01:21<04:00,  6.38it/s]
 32%|███▏      | 716/2248 [01:21<04:24,  5.80it/s]
 32%|███▏      | 717/2248 [01:21<04:15,  6.00it/s]
 32%|███▏      | 718/2248 [01:21<04:04,  6.25it/s]
 32%|███▏      | 719/2248 [01:21<05:16,  4.83it/s]
 32%|███▏      | 720/2248 [01:22<04:45,  5.35it/s]
 32%|███▏      | 721/2248 [01:22<04:38,  5.47it/s]
 32%|███▏      | 723/2248 [01:22<03:41,  6.89it/s]
 32%|███▏      | 725/2248 [01:22<03:09,  8.05it/s]
 32%|███▏      | 726/2248 [01:22<03:19,  7.63it/s]
 32%|███▏      | 727/2248 [01:22<03:50,  6.61it/s]
 32%|███▏      | 728/2248 [01:23<03:48,  6.64it/s]
 32%|███▏      | 729/2248 [01:23<03:38,  6.97it/s]
 33%|███▎      | 731/2248 [01:23<03:18,  7.63it/s]
 33%|███▎      | 732/2248 [01:23<04:01,  6.27it/s]
 33%|███▎      | 733/2248 [01:24<05:28,  4.62it/s]
 33%|███▎      | 734/2248 [01:24<05:18,  4.75it/s]
 33%|███▎      | 735/2248 [01:24<05:10,  4.88it/s]
 33%|███▎      | 736/2248 [01:24<05:58,  4.22it/s]
 33%|███▎      | 737/2248 [01:25<06:04,  4.14it/s]
 33%|███▎      | 739/2248 [01:25<04:31,  5.56it/s]
 33%|███▎      | 741/2248 [01:25<03:18,  7.58it/s]
 33%|███▎      | 742/2248 [01:25<03:30,  7.17it/s]
 33%|███▎      | 743/2248 [01:25<04:09,  6.02it/s]
 33%|███▎      | 744/2248 [01:26<05:10,  4.85it/s]
 33%|███▎      | 746/2248 [01:26<03:44,  6.69it/s]
 33%|███▎      | 749/2248 [01:26<03:26,  7.26it/s]
 33%|███▎      | 751/2248 [01:27<04:08,  6.01it/s]
 33%|███▎      | 752/2248 [01:27<04:45,  5.25it/s]
 34%|███▎      | 754/2248 [01:27<04:14,  5.87it/s]
 34%|███▎      | 757/2248 [01:27<02:53,  8.59it/s]
 34%|███▍      | 759/2248 [01:27<02:34,  9.61it/s]
 34%|███▍      | 761/2248 [01:28<03:02,  8.13it/s]
 34%|███▍      | 765/2248 [01:28<01:58, 12.46it/s]
 34%|███▍      | 767/2248 [01:28<02:52,  8.58it/s]
 34%|███▍      | 770/2248 [01:28<02:14, 11.02it/s]
 34%|███▍      | 772/2248 [01:29<03:07,  7.87it/s]
 34%|███▍      | 774/2248 [01:30<04:19,  5.68it/s]
 35%|███▍      | 776/2248 [01:30<06:00,  4.08it/s]
 35%|███▍      | 777/2248 [01:31<05:51,  4.18it/s]
 35%|███▍      | 779/2248 [01:31<04:31,  5.41it/s]
 35%|███▍      | 782/2248 [01:31<04:02,  6.05it/s]
 35%|███▍      | 783/2248 [01:31<04:23,  5.56it/s]
 35%|███▍      | 784/2248 [01:32<05:03,  4.82it/s]
 35%|███▍      | 786/2248 [01:32<03:51,  6.32it/s]
 35%|███▌      | 789/2248 [01:32<03:10,  7.65it/s]
 35%|███▌      | 791/2248 [01:32<02:42,  8.99it/s]
 35%|███▌      | 793/2248 [01:33<02:45,  8.80it/s]
 35%|███▌      | 796/2248 [01:33<02:06, 11.49it/s]
 35%|███▌      | 798/2248 [01:33<02:09, 11.21it/s]
 36%|███▌      | 800/2248 [01:33<02:01, 11.90it/s]
 36%|███▌      | 807/2248 [01:33<01:03, 22.63it/s]
 36%|███▌      | 810/2248 [01:33<01:10, 20.29it/s]
 36%|███▌      | 813/2248 [01:34<02:40,  8.91it/s]
 36%|███▋      | 815/2248 [01:35<03:54,  6.10it/s]
 36%|███▋      | 817/2248 [01:35<04:31,  5.28it/s]
 36%|███▋      | 819/2248 [01:36<04:11,  5.69it/s]
 37%|███▋      | 821/2248 [01:36<03:25,  6.94it/s]
 37%|███▋      | 823/2248 [01:36<02:52,  8.26it/s]
 37%|███▋      | 825/2248 [01:36<02:25,  9.78it/s]
 37%|███▋      | 830/2248 [01:36<01:27, 16.18it/s]
 37%|███▋      | 834/2248 [01:36<01:13, 19.15it/s]
 37%|███▋      | 838/2248 [01:36<01:01, 23.09it/s]
 37%|███▋      | 841/2248 [01:37<01:33, 15.08it/s]
 38%|███▊      | 844/2248 [01:37<01:27, 16.11it/s]
 38%|███▊      | 850/2248 [01:37<00:59, 23.54it/s]
 38%|███▊      | 854/2248 [01:37<01:09, 19.92it/s]
 38%|███▊      | 857/2248 [01:37<01:09, 19.89it/s]
 38%|███▊      | 861/2248 [01:38<00:59, 23.49it/s]
 39%|███▊      | 866/2248 [01:38<01:02, 22.18it/s]
 39%|███▊      | 869/2248 [01:38<01:59, 11.51it/s]
 39%|███▊      | 871/2248 [01:39<02:23,  9.58it/s]
 39%|███▉      | 873/2248 [01:39<02:11, 10.47it/s]
 39%|███▉      | 875/2248 [01:39<02:28,  9.27it/s]
 39%|███▉      | 877/2248 [01:40<03:16,  6.99it/s]
 39%|███▉      | 879/2248 [01:40<02:55,  7.81it/s]
 39%|███▉      | 881/2248 [01:40<03:26,  6.61it/s]
 39%|███▉      | 883/2248 [01:40<02:48,  8.11it/s]
 39%|███▉      | 885/2248 [01:41<02:35,  8.75it/s]
 39%|███▉      | 887/2248 [01:41<02:34,  8.82it/s]
 40%|███▉      | 889/2248 [01:41<02:26,  9.28it/s]
 40%|███▉      | 891/2248 [01:42<04:01,  5.61it/s]
 40%|███▉      | 893/2248 [01:42<03:55,  5.74it/s]
 40%|███▉      | 894/2248 [01:42<04:58,  4.53it/s]
 40%|███▉      | 895/2248 [01:43<06:16,  3.59it/s]
 40%|███▉      | 898/2248 [01:43<04:07,  5.46it/s]
 40%|████      | 900/2248 [01:43<03:22,  6.66it/s]
 40%|████      | 902/2248 [01:44<03:52,  5.78it/s]
 40%|████      | 903/2248 [01:44<04:05,  5.48it/s]
 40%|████      | 905/2248 [01:44<03:05,  7.25it/s]
 40%|████      | 907/2248 [01:45<04:36,  4.86it/s]
 40%|████      | 908/2248 [01:45<05:51,  3.81it/s]
 40%|████      | 909/2248 [01:46<05:37,  3.97it/s]
 40%|████      | 910/2248 [01:46<06:59,  3.19it/s]
 41%|████      | 911/2248 [01:47<08:00,  2.78it/s]
 41%|████      | 912/2248 [01:47<07:08,  3.11it/s]
 41%|████      | 913/2248 [01:47<08:11,  2.72it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 293.11it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 6], [np.int64(2), False, 4], [np.int64(3), False, 8], [np.int64(5), False, 12], [np.int64(7), False, 1], [np.int64(8), False, 9], [np.int64(10), False, 9], [np.int64(11), False, 1], [np.int64(12), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4165, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6626, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [12:59<2:13:55, 81.17s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [12:59<1:32:53, 56.87s/it]

tensor(12.4175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5413, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8172, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [12:59<31:00, 19.58s/it]

tensor(12.4381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9516, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4466, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0498, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0493, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [12:59<14:57,  9.65s/it]

tensor(12.4448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0533, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0259, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4350, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0560, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9245, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [13:00<07:15,  4.79s/it]

tensor(12.4281, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0572, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0582, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0169, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [13:00<03:34,  2.41s/it]

tensor(12.4489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0586, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9826, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0591, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9667, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [13:00<01:47,  1.24s/it]

tensor(12.4308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0591, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0473, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0593, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1523, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [13:00<00:56,  1.50it/s]

tensor(12.4321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0597, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2708, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0614, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3480, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [13:01<00:32,  2.59it/s]

tensor(12.4396, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0634, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3652, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0639, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3372, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [13:01<00:20,  4.01it/s]

tensor(12.3989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0609, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3561, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0556, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4278, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [13:01<00:14,  5.51it/s]

tensor(12.3903, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0517, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4519, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0498, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4530, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 222/300 [13:01<00:12,  6.16it/s]

tensor(12.4000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4502, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3943, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0468, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4430, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [13:02<00:10,  7.46it/s]

tensor(12.3833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0444, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4603, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0410, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4745, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [13:02<00:09,  8.01it/s]

tensor(12.3661, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0379, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4866, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4846, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [13:02<00:08,  8.30it/s]

tensor(12.3664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4808, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4800, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [13:02<00:08,  8.44it/s]

tensor(12.3632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4816, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3571, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4801, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [13:03<00:07,  8.54it/s]

tensor(12.3501, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4860, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4936, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [13:03<00:07,  8.54it/s]

tensor(12.3421, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5002, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5032, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [13:03<00:07,  8.63it/s]

tensor(12.3394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5001, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5003, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [13:03<00:07,  8.59it/s]

tensor(12.3342, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4981, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4983, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [13:03<00:06,  8.64it/s]

tensor(12.3272, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5011, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5028, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [13:04<00:06,  8.66it/s]

tensor(12.3219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5054, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5037, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [13:04<00:06,  8.60it/s]

tensor(12.3179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4999, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3161, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4997, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [13:04<00:06,  8.65it/s]

tensor(12.3139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5009, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [13:04<00:05,  8.53it/s]

tensor(12.3097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5007, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5040, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [13:05<00:05,  8.49it/s]

tensor(12.3059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5028, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([177, 181,  89, 257, 107, 198, 134, 181,  39, 311,  94, 155,  78, 247])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:24, 15.56it/s]
  0%|          | 5/2248 [00:00<01:51, 20.08it/s]
  0%|          | 11/2248 [00:00<01:04, 34.62it/s]
  1%|          | 17/2248 [00:00<00:52, 42.55it/s]
  1%|          | 22/2248 [00:00<01:03, 34.79it/s]
  1%|▏         | 29/2248 [00:00<00:51, 43.12it/s]
  2%|▏         | 34/2248 [00:00<01:05, 33.71it/s]
  2%|▏         | 38/2248 [00:01<01:10, 31.23it/s]
  2%|▏         | 42/2248 [00:01<01:17, 28.46it/s]
  2%|▏         | 46/2248 [00:01<02:13, 16.51it/s]
  2%|▏         | 49/2248 [00:02<02:12, 16.55it/s]
  2%|▏         | 52/2248 [00:02<02:16, 16.04it/s]
  2%|▏         | 54/2248 [00:02<02:17, 15.95it/s]
  2%|▏         | 56/2248 [00:02<02:25, 15.04it/s]
  3%|▎         | 58/2248 [00:02<02:27, 14.88it/s]
  3%|▎         | 60/2248 [00:02<02:19, 15.64it/s]
  3%|▎         | 62/2248 [00:02<02:43, 13.34it/s]
  3%|▎         | 65/2248 [00:03<02:37, 13.82it/s]
  3%|▎         | 67/2248 [00:03<02:27, 14.75it/s]
  3%|▎         | 72/2248 [00:03<01:37, 22.23it/s]
  3%|▎         | 75/2248 [00:03<01:58, 18.26it/s]
  3%|▎         | 78/2248 [00:03<02:36, 13.90it/s]
  4%|▎         | 80/2248 [00:04<02:28, 14.57it/s]
  4%|▎         | 83/2248 [00:04<02:08, 16.80it/s]
  4%|▍         | 86/2248 [00:04<02:42, 13.29it/s]
  4%|▍         | 88/2248 [00:04<03:09, 11.42it/s]
  4%|▍         | 90/2248 [00:04<03:17, 10.93it/s]
  4%|▍         | 93/2248 [00:05<02:35, 13.84it/s]
  4%|▍         | 95/2248 [00:05<03:06, 11.57it/s]
  4%|▍         | 97/2248 [00:05<03:53,  9.20it/s]
  4%|▍         | 99/2248 [00:05<04:00,  8.93it/s]
  4%|▍         | 101/2248 [00:06<04:16,  8.36it/s]
  5%|▍         | 102/2248 [00:06<04:21,  8.21it/s]
  5%|▍         | 105/2248 [00:06<03:04, 11.59it/s]
  5%|▍         | 108/2248 [00:06<02:27, 14.55it/s]
  5%|▍         | 110/2248 [00:06<03:01, 11.79it/s]
  5%|▍         | 112/2248 [00:07<03:36,  9.89it/s]
  5%|▌         | 114/2248 [00:07<03:28, 10.23it/s]
  5%|▌         | 117/2248 [00:07<03:25, 10.36it/s]
  5%|▌         | 119/2248 [00:07<03:43,  9.53it/s]
  5%|▌         | 121/2248 [00:08<03:57,  8.97it/s]
  5%|▌         | 123/2248 [00:08<03:39,  9.67it/s]
  6%|▌         | 126/2248 [00:08<03:28, 10.19it/s]
  6%|▌         | 128/2248 [00:08<04:30,  7.82it/s]
  6%|▌         | 131/2248 [00:09<03:24, 10.33it/s]
  6%|▌         | 133/2248 [00:09<03:30, 10.05it/s]
  6%|▌         | 135/2248 [00:09<03:51,  9.11it/s]
  6%|▌         | 137/2248 [00:09<03:58,  8.87it/s]
  6%|▌         | 138/2248 [00:10<04:37,  7.60it/s]
  6%|▌         | 140/2248 [00:10<04:30,  7.79it/s]
  6%|▋         | 142/2248 [00:10<03:52,  9.08it/s]
  6%|▋         | 145/2248 [00:10<03:07, 11.20it/s]
  7%|▋         | 148/2248 [00:10<03:00, 11.64it/s]
  7%|▋         | 150/2248 [00:10<02:43, 12.83it/s]
  7%|▋         | 152/2248 [00:11<03:23, 10.30it/s]
  7%|▋         | 154/2248 [00:11<03:00, 11.60it/s]
  7%|▋         | 156/2248 [00:11<03:17, 10.59it/s]
  7%|▋         | 158/2248 [00:11<04:22,  7.97it/s]
  7%|▋         | 159/2248 [00:12<04:54,  7.08it/s]
  7%|▋         | 160/2248 [00:12<05:04,  6.85it/s]
  7%|▋         | 162/2248 [00:12<05:16,  6.59it/s]
  7%|▋         | 164/2248 [00:12<04:33,  7.63it/s]
  7%|▋         | 165/2248 [00:13<05:06,  6.79it/s]
  7%|▋         | 166/2248 [00:13<04:57,  7.00it/s]
  8%|▊         | 169/2248 [00:13<03:40,  9.43it/s]
  8%|▊         | 171/2248 [00:13<03:23, 10.21it/s]
  8%|▊         | 173/2248 [00:13<02:53, 11.96it/s]
  8%|▊         | 175/2248 [00:13<03:22, 10.25it/s]
  8%|▊         | 177/2248 [00:14<03:32,  9.75it/s]
  8%|▊         | 179/2248 [00:14<04:37,  7.46it/s]
  8%|▊         | 181/2248 [00:14<03:46,  9.11it/s]
  8%|▊         | 183/2248 [00:14<04:02,  8.52it/s]
  8%|▊         | 185/2248 [00:15<03:49,  8.98it/s]
  8%|▊         | 187/2248 [00:15<03:43,  9.21it/s]
  8%|▊         | 189/2248 [00:15<04:40,  7.34it/s]
  8%|▊         | 191/2248 [00:15<04:02,  8.49it/s]
  9%|▊         | 193/2248 [00:16<03:46,  9.08it/s]
  9%|▊         | 195/2248 [00:16<03:48,  8.98it/s]
  9%|▉         | 197/2248 [00:16<03:12, 10.68it/s]
  9%|▉         | 199/2248 [00:16<03:23, 10.06it/s]
  9%|▉         | 201/2248 [00:17<04:42,  7.24it/s]
  9%|▉         | 202/2248 [00:17<04:49,  7.07it/s]
  9%|▉         | 204/2248 [00:17<04:23,  7.77it/s]
  9%|▉         | 205/2248 [00:17<05:08,  6.62it/s]
  9%|▉         | 207/2248 [00:17<04:51,  7.00it/s]
  9%|▉         | 209/2248 [00:18<04:36,  7.37it/s]
  9%|▉         | 210/2248 [00:18<05:15,  6.46it/s]
  9%|▉         | 211/2248 [00:18<05:40,  5.98it/s]
  9%|▉         | 212/2248 [00:18<06:01,  5.63it/s]
  9%|▉         | 213/2248 [00:19<07:04,  4.80it/s]
 10%|▉         | 216/2248 [00:19<04:21,  7.77it/s]
 10%|▉         | 219/2248 [00:19<03:04, 10.97it/s]
 10%|▉         | 221/2248 [00:19<02:53, 11.66it/s]
 10%|█         | 225/2248 [00:19<02:02, 16.58it/s]
 10%|█         | 232/2248 [00:19<01:14, 27.22it/s]
 11%|█         | 238/2248 [00:19<00:58, 34.29it/s]
 11%|█         | 244/2248 [00:20<00:50, 39.50it/s]
 11%|█         | 249/2248 [00:20<00:48, 41.51it/s]
 11%|█▏        | 256/2248 [00:20<00:41, 47.47it/s]
 12%|█▏        | 262/2248 [00:20<00:39, 49.91it/s]
 12%|█▏        | 268/2248 [00:20<01:23, 23.66it/s]
 12%|█▏        | 272/2248 [00:21<02:03, 16.06it/s]
 12%|█▏        | 276/2248 [00:21<02:37, 12.53it/s]
 12%|█▏        | 279/2248 [00:22<02:51, 11.45it/s]
 13%|█▎        | 282/2248 [00:22<02:48, 11.68it/s]
 13%|█▎        | 284/2248 [00:22<02:37, 12.50it/s]
 13%|█▎        | 289/2248 [00:22<02:08, 15.20it/s]
 13%|█▎        | 291/2248 [00:23<02:31, 12.96it/s]
 13%|█▎        | 293/2248 [00:23<02:44, 11.88it/s]
 13%|█▎        | 295/2248 [00:23<03:10, 10.27it/s]
 13%|█▎        | 297/2248 [00:23<03:02, 10.67it/s]
 13%|█▎        | 299/2248 [00:24<03:52,  8.37it/s]
 13%|█▎        | 301/2248 [00:24<03:39,  8.87it/s]
 13%|█▎        | 303/2248 [00:24<04:52,  6.65it/s]
 14%|█▎        | 305/2248 [00:25<04:09,  7.78it/s]
 14%|█▎        | 306/2248 [00:25<04:35,  7.05it/s]
 14%|█▎        | 307/2248 [00:25<04:59,  6.47it/s]
 14%|█▎        | 308/2248 [00:25<04:49,  6.70it/s]
 14%|█▍        | 310/2248 [00:25<04:14,  7.62it/s]
 14%|█▍        | 312/2248 [00:25<03:18,  9.73it/s]
 14%|█▍        | 314/2248 [00:26<03:43,  8.64it/s]
 14%|█▍        | 316/2248 [00:26<03:41,  8.70it/s]
 14%|█▍        | 319/2248 [00:26<03:49,  8.40it/s]
 14%|█▍        | 320/2248 [00:26<03:50,  8.38it/s]
 14%|█▍        | 322/2248 [00:27<03:31,  9.12it/s]
 14%|█▍        | 323/2248 [00:27<03:59,  8.03it/s]
 14%|█▍        | 324/2248 [00:27<04:07,  7.78it/s]
 14%|█▍        | 325/2248 [00:27<03:54,  8.18it/s]
 15%|█▍        | 327/2248 [00:27<03:36,  8.87it/s]
 15%|█▍        | 329/2248 [00:27<02:56, 10.85it/s]
 15%|█▍        | 332/2248 [00:27<02:10, 14.65it/s]
 15%|█▍        | 335/2248 [00:28<01:53, 16.90it/s]
 15%|█▌        | 339/2248 [00:28<02:02, 15.55it/s]
 15%|█▌        | 341/2248 [00:28<02:46, 11.49it/s]
 15%|█▌        | 343/2248 [00:28<02:42, 11.69it/s]
 15%|█▌        | 345/2248 [00:29<03:37,  8.75it/s]
 15%|█▌        | 347/2248 [00:29<03:50,  8.24it/s]
 15%|█▌        | 348/2248 [00:29<04:14,  7.46it/s]
 16%|█▌        | 349/2248 [00:29<04:20,  7.29it/s]
 16%|█▌        | 350/2248 [00:29<04:14,  7.45it/s]
 16%|█▌        | 351/2248 [00:30<04:11,  7.56it/s]
 16%|█▌        | 353/2248 [00:30<03:49,  8.27it/s]
 16%|█▌        | 355/2248 [00:30<03:09,  9.99it/s]
 16%|█▌        | 357/2248 [00:30<03:08, 10.05it/s]
 16%|█▌        | 362/2248 [00:30<02:12, 14.24it/s]
 16%|█▌        | 364/2248 [00:31<02:24, 13.03it/s]
 16%|█▋        | 366/2248 [00:31<02:36, 12.03it/s]
 16%|█▋        | 368/2248 [00:31<02:53, 10.83it/s]
 17%|█▋        | 371/2248 [00:31<02:55, 10.72it/s]
 17%|█▋        | 373/2248 [00:32<03:26,  9.08it/s]
 17%|█▋        | 375/2248 [00:32<02:57, 10.53it/s]
 17%|█▋        | 377/2248 [00:32<03:03, 10.18it/s]
 17%|█▋        | 379/2248 [00:32<03:14,  9.61it/s]
 17%|█▋        | 382/2248 [00:32<02:28, 12.54it/s]
 17%|█▋        | 384/2248 [00:32<02:41, 11.57it/s]
 17%|█▋        | 386/2248 [00:33<03:07,  9.96it/s]
 17%|█▋        | 388/2248 [00:33<03:30,  8.82it/s]
 17%|█▋        | 390/2248 [00:33<03:38,  8.52it/s]
 17%|█▋        | 392/2248 [00:34<03:39,  8.45it/s]
 17%|█▋        | 393/2248 [00:34<04:14,  7.29it/s]
 18%|█▊        | 394/2248 [00:34<04:25,  6.98it/s]
 18%|█▊        | 396/2248 [00:34<03:33,  8.68it/s]
 18%|█▊        | 398/2248 [00:34<02:57, 10.42it/s]
 18%|█▊        | 400/2248 [00:34<02:30, 12.29it/s]
 18%|█▊        | 402/2248 [00:34<02:19, 13.23it/s]
 18%|█▊        | 404/2248 [00:35<02:18, 13.32it/s]
 18%|█▊        | 407/2248 [00:35<02:01, 15.10it/s]
 18%|█▊        | 412/2248 [00:35<01:22, 22.31it/s]
 18%|█▊        | 415/2248 [00:35<01:18, 23.36it/s]
 19%|█▊        | 418/2248 [00:35<01:36, 18.93it/s]
 19%|█▊        | 421/2248 [00:35<01:27, 20.92it/s]
 19%|█▉        | 427/2248 [00:35<01:05, 27.96it/s]
 19%|█▉        | 431/2248 [00:36<01:03, 28.78it/s]
 19%|█▉        | 436/2248 [00:36<01:13, 24.56it/s]
 20%|█▉        | 439/2248 [00:36<02:04, 14.50it/s]
 20%|█▉        | 442/2248 [00:37<02:20, 12.85it/s]
 20%|█▉        | 444/2248 [00:37<02:40, 11.23it/s]
 20%|█▉        | 446/2248 [00:37<02:58, 10.07it/s]
 20%|█▉        | 448/2248 [00:38<03:27,  8.67it/s]
 20%|██        | 451/2248 [00:38<02:38, 11.36it/s]
 20%|██        | 453/2248 [00:38<02:49, 10.58it/s]
 20%|██        | 455/2248 [00:38<03:39,  8.17it/s]
 20%|██        | 457/2248 [00:39<04:35,  6.50it/s]
 20%|██        | 459/2248 [00:39<04:20,  6.86it/s]
 20%|██        | 460/2248 [00:39<04:36,  6.46it/s]
 21%|██        | 462/2248 [00:39<03:56,  7.55it/s]
 21%|██        | 464/2248 [00:40<03:44,  7.94it/s]
 21%|██        | 465/2248 [00:40<04:00,  7.41it/s]
 21%|██        | 467/2248 [00:40<03:13,  9.21it/s]
 21%|██        | 469/2248 [00:40<02:56, 10.09it/s]
 21%|██        | 471/2248 [00:40<03:06,  9.54it/s]
 21%|██        | 473/2248 [00:40<02:45, 10.73it/s]
 21%|██        | 475/2248 [00:41<02:29, 11.87it/s]
 21%|██        | 477/2248 [00:41<02:40, 11.02it/s]
 21%|██▏       | 479/2248 [00:41<02:30, 11.76it/s]
 21%|██▏       | 481/2248 [00:41<03:08,  9.35it/s]
 21%|██▏       | 483/2248 [00:42<03:36,  8.15it/s]
 22%|██▏       | 486/2248 [00:42<03:18,  8.87it/s]
 22%|██▏       | 487/2248 [00:42<03:23,  8.66it/s]
 22%|██▏       | 488/2248 [00:42<03:40,  7.97it/s]
 22%|██▏       | 490/2248 [00:42<03:15,  8.99it/s]
 22%|██▏       | 492/2248 [00:42<03:11,  9.19it/s]
 22%|██▏       | 494/2248 [00:43<02:47, 10.50it/s]
 22%|██▏       | 496/2248 [00:43<03:30,  8.31it/s]
 22%|██▏       | 498/2248 [00:43<03:44,  7.80it/s]
 22%|██▏       | 499/2248 [00:43<03:43,  7.81it/s]
 22%|██▏       | 500/2248 [00:44<04:11,  6.96it/s]
 22%|██▏       | 502/2248 [00:44<03:36,  8.08it/s]
 23%|██▎       | 506/2248 [00:44<02:18, 12.56it/s]
 23%|██▎       | 509/2248 [00:44<02:07, 13.59it/s]
 23%|██▎       | 512/2248 [00:44<02:13, 13.05it/s]
 23%|██▎       | 514/2248 [00:45<02:56,  9.83it/s]
 23%|██▎       | 516/2248 [00:45<03:39,  7.91it/s]
 23%|██▎       | 517/2248 [00:45<03:34,  8.07it/s]
 23%|██▎       | 519/2248 [00:45<03:14,  8.91it/s]
 23%|██▎       | 521/2248 [00:45<02:42, 10.61it/s]
 23%|██▎       | 526/2248 [00:46<01:39, 17.32it/s]
 24%|██▎       | 529/2248 [00:46<01:26, 19.81it/s]
 24%|██▎       | 533/2248 [00:46<01:19, 21.55it/s]
 24%|██▍       | 536/2248 [00:46<01:26, 19.82it/s]
 24%|██▍       | 539/2248 [00:46<01:21, 21.02it/s]
 24%|██▍       | 544/2248 [00:46<01:13, 23.08it/s]
 24%|██▍       | 548/2248 [00:46<01:06, 25.43it/s]
 25%|██▍       | 554/2248 [00:47<00:52, 32.38it/s]
 25%|██▍       | 560/2248 [00:47<00:43, 38.67it/s]
 25%|██▌       | 566/2248 [00:47<00:39, 42.71it/s]
 25%|██▌       | 572/2248 [00:47<00:50, 32.95it/s]
 26%|██▌       | 576/2248 [00:48<01:31, 18.35it/s]
 26%|██▌       | 579/2248 [00:48<01:45, 15.76it/s]
 26%|██▌       | 582/2248 [00:48<02:14, 12.35it/s]
 26%|██▌       | 584/2248 [00:49<02:37, 10.57it/s]
 26%|██▌       | 586/2248 [00:49<02:58,  9.29it/s]
 26%|██▌       | 588/2248 [00:49<03:06,  8.89it/s]
 26%|██▋       | 591/2248 [00:49<02:28, 11.15it/s]
 26%|██▋       | 593/2248 [00:50<02:46,  9.91it/s]
 26%|██▋       | 595/2248 [00:50<02:48,  9.82it/s]
 27%|██▋       | 598/2248 [00:50<02:14, 12.23it/s]
 27%|██▋       | 600/2248 [00:50<02:11, 12.54it/s]
 27%|██▋       | 603/2248 [00:50<02:08, 12.76it/s]
 27%|██▋       | 605/2248 [00:51<03:11,  8.60it/s]
 27%|██▋       | 607/2248 [00:51<03:32,  7.74it/s]
 27%|██▋       | 609/2248 [00:51<03:31,  7.73it/s]
 27%|██▋       | 610/2248 [00:52<04:02,  6.74it/s]
 27%|██▋       | 613/2248 [00:52<03:26,  7.90it/s]
 27%|██▋       | 615/2248 [00:52<02:52,  9.46it/s]
 28%|██▊       | 620/2248 [00:52<01:42, 15.89it/s]
 28%|██▊       | 623/2248 [00:52<01:57, 13.77it/s]
 28%|██▊       | 625/2248 [00:53<01:51, 14.60it/s]
 28%|██▊       | 630/2248 [00:53<01:17, 20.95it/s]
 28%|██▊       | 636/2248 [00:53<01:06, 24.11it/s]
 28%|██▊       | 640/2248 [00:53<01:01, 26.14it/s]
 29%|██▊       | 643/2248 [00:53<01:04, 24.95it/s]
 29%|██▊       | 646/2248 [00:53<01:12, 22.02it/s]
 29%|██▉       | 649/2248 [00:53<01:19, 20.04it/s]
 29%|██▉       | 652/2248 [00:54<02:02, 13.06it/s]
 29%|██▉       | 654/2248 [00:54<02:25, 10.98it/s]
 29%|██▉       | 657/2248 [00:54<01:57, 13.55it/s]
 29%|██▉       | 659/2248 [00:55<02:10, 12.21it/s]
 29%|██▉       | 661/2248 [00:55<03:04,  8.61it/s]
 29%|██▉       | 663/2248 [00:55<03:37,  7.30it/s]
 30%|██▉       | 665/2248 [00:56<03:22,  7.82it/s]
 30%|██▉       | 667/2248 [00:56<03:09,  8.36it/s]
 30%|██▉       | 669/2248 [00:56<02:43,  9.65it/s]
 30%|██▉       | 671/2248 [00:56<02:21, 11.12it/s]
 30%|██▉       | 673/2248 [00:56<02:14, 11.75it/s]
 30%|███       | 677/2248 [00:56<02:07, 12.31it/s]
 30%|███       | 680/2248 [00:57<01:46, 14.76it/s]
 30%|███       | 682/2248 [00:57<02:41,  9.69it/s]
 30%|███       | 684/2248 [00:57<03:15,  8.02it/s]
 31%|███       | 686/2248 [00:58<03:51,  6.74it/s]
 31%|███       | 687/2248 [00:58<04:08,  6.27it/s]
 31%|███       | 688/2248 [00:58<04:11,  6.20it/s]
 31%|███       | 689/2248 [00:58<04:38,  5.59it/s]
 31%|███       | 691/2248 [00:59<04:04,  6.36it/s]
 31%|███       | 692/2248 [00:59<04:24,  5.88it/s]
 31%|███       | 694/2248 [00:59<03:47,  6.84it/s]
 31%|███       | 695/2248 [00:59<03:51,  6.70it/s]
 31%|███       | 696/2248 [01:00<04:26,  5.83it/s]
 31%|███       | 699/2248 [01:00<03:15,  7.92it/s]
 31%|███       | 701/2248 [01:00<02:49,  9.15it/s]
 31%|███       | 702/2248 [01:00<03:28,  7.43it/s]
 31%|███▏      | 703/2248 [01:00<03:16,  7.85it/s]
 31%|███▏      | 704/2248 [01:00<03:15,  7.92it/s]
 31%|███▏      | 706/2248 [01:00<02:33, 10.04it/s]
 32%|███▏      | 709/2248 [01:01<01:47, 14.27it/s]
 32%|███▏      | 711/2248 [01:01<02:39,  9.64it/s]
 32%|███▏      | 713/2248 [01:01<02:18, 11.10it/s]
 32%|███▏      | 715/2248 [01:01<02:12, 11.56it/s]
 32%|███▏      | 717/2248 [01:01<02:31, 10.11it/s]
 32%|███▏      | 719/2248 [01:02<02:40,  9.52it/s]
 32%|███▏      | 721/2248 [01:02<03:01,  8.40it/s]
 32%|███▏      | 724/2248 [01:02<02:11, 11.61it/s]
 32%|███▏      | 726/2248 [01:02<02:16, 11.13it/s]
 32%|███▏      | 728/2248 [01:03<03:16,  7.74it/s]
 32%|███▏      | 730/2248 [01:03<02:42,  9.32it/s]
 33%|███▎      | 732/2248 [01:03<03:06,  8.15it/s]
 33%|███▎      | 734/2248 [01:04<03:19,  7.60it/s]
 33%|███▎      | 735/2248 [01:04<03:35,  7.01it/s]
 33%|███▎      | 736/2248 [01:04<03:51,  6.54it/s]
 33%|███▎      | 737/2248 [01:04<04:04,  6.17it/s]
 33%|███▎      | 738/2248 [01:04<04:13,  5.96it/s]
 33%|███▎      | 740/2248 [01:04<03:10,  7.93it/s]
 33%|███▎      | 742/2248 [01:05<03:00,  8.32it/s]
 33%|███▎      | 743/2248 [01:05<03:31,  7.10it/s]
 33%|███▎      | 744/2248 [01:05<03:51,  6.50it/s]
 33%|███▎      | 746/2248 [01:05<02:57,  8.46it/s]
 33%|███▎      | 748/2248 [01:05<02:32,  9.85it/s]
 33%|███▎      | 750/2248 [01:06<02:38,  9.45it/s]
 33%|███▎      | 752/2248 [01:06<03:27,  7.20it/s]
 34%|███▎      | 754/2248 [01:06<03:20,  7.46it/s]
 34%|███▎      | 757/2248 [01:06<02:25, 10.25it/s]
 34%|███▍      | 761/2248 [01:07<02:01, 12.24it/s]
 34%|███▍      | 764/2248 [01:07<01:46, 13.89it/s]
 34%|███▍      | 767/2248 [01:07<01:46, 13.89it/s]
 34%|███▍      | 769/2248 [01:07<01:42, 14.43it/s]
 34%|███▍      | 772/2248 [01:07<01:47, 13.72it/s]
 34%|███▍      | 774/2248 [01:08<02:32,  9.68it/s]
 35%|███▍      | 776/2248 [01:08<03:12,  7.65it/s]
 35%|███▍      | 778/2248 [01:08<03:23,  7.22it/s]
 35%|███▍      | 779/2248 [01:09<04:00,  6.12it/s]
 35%|███▍      | 782/2248 [01:09<03:16,  7.47it/s]
 35%|███▍      | 783/2248 [01:09<03:31,  6.92it/s]
 35%|███▍      | 784/2248 [01:09<03:49,  6.38it/s]
 35%|███▌      | 787/2248 [01:10<02:28,  9.81it/s]
 35%|███▌      | 789/2248 [01:10<02:38,  9.19it/s]
 35%|███▌      | 792/2248 [01:10<02:33,  9.48it/s]
 35%|███▌      | 794/2248 [01:10<02:17, 10.59it/s]
 35%|███▌      | 797/2248 [01:10<02:06, 11.48it/s]
 36%|███▌      | 799/2248 [01:11<01:57, 12.38it/s]
 36%|███▌      | 801/2248 [01:11<02:11, 11.02it/s]
 36%|███▌      | 803/2248 [01:11<02:00, 11.99it/s]
 36%|███▌      | 805/2248 [01:11<02:00, 11.96it/s]
 36%|███▌      | 807/2248 [01:11<02:22, 10.09it/s]
 36%|███▌      | 810/2248 [01:12<02:18, 10.38it/s]
 36%|███▌      | 812/2248 [01:12<03:00,  7.95it/s]
 36%|███▌      | 813/2248 [01:12<03:17,  7.27it/s]
 36%|███▌      | 814/2248 [01:12<03:35,  6.64it/s]
 36%|███▋      | 815/2248 [01:13<03:57,  6.02it/s]
 36%|███▋      | 816/2248 [01:13<04:08,  5.76it/s]
 36%|███▋      | 818/2248 [01:13<03:05,  7.72it/s]
 36%|███▋      | 820/2248 [01:13<02:35,  9.21it/s]
 37%|███▋      | 822/2248 [01:13<02:10, 10.94it/s]
 37%|███▋      | 824/2248 [01:13<02:02, 11.63it/s]
 37%|███▋      | 828/2248 [01:14<01:25, 16.65it/s]
 37%|███▋      | 832/2248 [01:14<01:07, 20.88it/s]
 37%|███▋      | 835/2248 [01:14<01:04, 22.04it/s]
 37%|███▋      | 839/2248 [01:14<00:56, 24.98it/s]
 38%|███▊      | 846/2248 [01:14<00:40, 34.41it/s]
 38%|███▊      | 851/2248 [01:14<00:37, 36.85it/s]
 38%|███▊      | 857/2248 [01:14<00:36, 37.75it/s]
 38%|███▊      | 861/2248 [01:14<00:38, 36.49it/s]
 39%|███▊      | 866/2248 [01:15<00:47, 29.02it/s]
 39%|███▊      | 870/2248 [01:15<01:35, 14.41it/s]
 39%|███▉      | 873/2248 [01:16<01:39, 13.82it/s]
 39%|███▉      | 876/2248 [01:16<02:02, 11.17it/s]
 39%|███▉      | 878/2248 [01:16<02:29,  9.16it/s]
 39%|███▉      | 880/2248 [01:17<02:40,  8.54it/s]
 39%|███▉      | 882/2248 [01:17<02:40,  8.53it/s]
 39%|███▉      | 884/2248 [01:17<02:40,  8.50it/s]
 39%|███▉      | 886/2248 [01:17<02:23,  9.50it/s]
 40%|███▉      | 888/2248 [01:18<02:43,  8.30it/s]
 40%|███▉      | 890/2248 [01:18<02:33,  8.85it/s]
 40%|███▉      | 891/2248 [01:18<03:04,  7.34it/s]
 40%|███▉      | 893/2248 [01:18<02:51,  7.88it/s]
 40%|███▉      | 894/2248 [01:18<02:47,  8.09it/s]
 40%|███▉      | 895/2248 [01:19<03:16,  6.88it/s]
 40%|███▉      | 896/2248 [01:19<03:04,  7.33it/s]
 40%|███▉      | 898/2248 [01:19<02:29,  9.00it/s]
 40%|███▉      | 899/2248 [01:19<03:06,  7.25it/s]
 40%|████      | 901/2248 [01:19<02:24,  9.33it/s]
 40%|████      | 903/2248 [01:20<03:21,  6.68it/s]
 40%|████      | 905/2248 [01:20<02:54,  7.69it/s]
 40%|████      | 907/2248 [01:20<02:26,  9.17it/s]
 40%|████      | 909/2248 [01:20<03:06,  7.20it/s]
 41%|████      | 911/2248 [01:21<02:43,  8.20it/s]
 41%|████      | 913/2248 [01:21<03:04,  7.24it/s]
 41%|████      | 914/2248 [01:21<02:58,  7.46it/s]
 41%|████      | 916/2248 [01:21<02:31,  8.79it/s]
 41%|████      | 918/2248 [01:22<02:46,  8.00it/s]
 41%|████      | 920/2248 [01:22<02:45,  8.02it/s]
 41%|████      | 921/2248 [01:22<02:56,  7.54it/s]
 41%|████      | 923/2248 [01:22<02:23,  9.24it/s]
 41%|████      | 925/2248 [01:22<02:15,  9.74it/s]
 41%|████      | 927/2248 [01:22<02:18,  9.52it/s]
 41%|████▏     | 929/2248 [01:23<02:33,  8.58it/s]
 41%|████▏     | 931/2248 [01:23<02:40,  8.22it/s]
 42%|████▏     | 934/2248 [01:23<02:17,  9.57it/s]
 42%|████▏     | 936/2248 [01:23<02:01, 10.77it/s]
 42%|████▏     | 938/2248 [01:24<02:18,  9.44it/s]
 42%|████▏     | 940/2248 [01:24<02:25,  9.01it/s]
 42%|████▏     | 941/2248 [01:24<03:01,  7.20it/s]
 42%|████▏     | 943/2248 [01:24<02:34,  8.44it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 297.77it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 9], [np.int64(2), False, 3], [np.int64(3), False, 9], [np.int64(4), False, 5], [np.int64(5), False, 13], [np.int64(6), False, 13], [np.int64(7), False, 4], [np.int64(8), False, 4], [np.int64(10), False, 4], [np.int64(11), False, 6], [np.int64(12), False, 5]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3040, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6722, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [16:24<48:50, 59.81s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [16:24<33:31, 41.91s/it]

tensor(12.3090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1080, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0364, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6341, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [16:24<10:50, 14.45s/it]

tensor(12.3635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0487, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9517, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0582, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9910, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [16:24<05:07,  7.14s/it]

tensor(12.3914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0674, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0762, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0772, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1467, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [16:25<02:25,  3.56s/it]

tensor(12.3683, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0841, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1949, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0876, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2230, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [16:25<01:10,  1.80s/it]

tensor(12.3723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0867, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2601, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0835, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2809, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [16:25<00:34,  1.06it/s]

tensor(12.3803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0788, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2891, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0741, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2882, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [16:25<00:18,  1.92it/s]

tensor(12.3732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0697, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0659, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3041, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [16:25<00:10,  3.18it/s]

tensor(12.3567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0623, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3481, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0592, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3206, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [16:26<00:06,  4.68it/s]

tensor(12.3396, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0561, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3056, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0528, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2894, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [16:26<00:04,  6.10it/s]

tensor(12.3288, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2859, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0435, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3087, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [16:26<00:03,  7.14it/s]

tensor(12.3243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0391, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3174, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3253, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [16:26<00:03,  7.85it/s]

tensor(12.3175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3276, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3356, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [16:27<00:02,  8.18it/s]

tensor(12.3079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3479, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3573, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [16:27<00:02,  8.42it/s]

tensor(12.3011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3787, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [16:27<00:02,  8.53it/s]

tensor(12.2937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3789, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2896, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3772, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [16:27<00:01,  8.56it/s]

tensor(12.2870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3853, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3924, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [16:28<00:01,  8.62it/s]

tensor(12.2855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4011, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4087, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [16:28<00:01,  8.53it/s]

tensor(12.2829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4127, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4146, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [16:28<00:01,  8.57it/s]

tensor(12.2773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4172, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4189, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [16:28<00:01,  8.58it/s]

tensor(12.2727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4228, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4252, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [16:29<00:00,  8.66it/s]

tensor(12.2696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4264, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4270, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [16:29<00:00,  8.58it/s]

tensor(12.2656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4271, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2633, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4261, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [16:29<00:00,  8.61it/s]

tensor(12.2611, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4294, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2593, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4296, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [16:29<00:00,  8.64it/s]

tensor(12.2575, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4304, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2560, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4328, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [16:29<00:00,  3.30s/it]

tensor(12.2546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4332, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.002307415008544922
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 2
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.339376706877
NMI         : 0.465146814148
Runtime     : 1010.04 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed2

==============================================================================================================
PRAGA RUN | S2-E18 | seed=3
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 7.749e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:33,  8.95it/s]

tensor(17.5979, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1188, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.9949, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8033, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:34,  8.67it/s]

tensor(16.3404, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7156, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0283, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8336, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 5/300 [00:00<00:30,  9.58it/s]

tensor(15.8591, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1370, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7233, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6069, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6073, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2277, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:28, 10.13it/s]

tensor(15.5205, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9851, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4615, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8652, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4230, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8549, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:28, 10.19it/s]

tensor(15.3966, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9446, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3741, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3498, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3860, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:27, 10.29it/s]

tensor(15.3186, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7198, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2773, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1197, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2262, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5794, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:27, 10.35it/s]

tensor(15.1676, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0923, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1047, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6535, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0416, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2588, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:27, 10.33it/s]

tensor(14.9817, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9032, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9251, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5830, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8699, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2952, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:26, 10.33it/s]

tensor(14.8118, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0360, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7497, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8032, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6837, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5932, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:26, 10.46it/s]

tensor(14.6161, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4054, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5490, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2357, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4835, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0841, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|▉         | 29/300 [00:02<00:26, 10.41it/s]

tensor(14.4198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9472, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7157, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:25, 10.38it/s]

tensor(14.2298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6181, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5311, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1044, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4524, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:25, 10.41it/s]

tensor(14.0471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3831, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3218, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2667, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:25, 10.37it/s]

tensor(13.9063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2191, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1774, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8290, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1413, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▎        | 41/300 [00:03<00:25, 10.35it/s]

tensor(13.7946, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1107, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7604, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0857, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0659, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:24, 10.37it/s]

tensor(13.6860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0517, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6488, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 47/300 [00:04<00:24, 10.35it/s]

tensor(13.5794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5164, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:04<00:24, 10.32it/s]

tensor(13.4873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4594, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 53/300 [00:05<00:23, 10.36it/s]

tensor(13.4039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3759, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:23, 10.38it/s]

tensor(13.3203, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:05<00:23, 10.34it/s]

tensor(13.2403, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:22, 10.31it/s]

tensor(13.1635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:22, 10.36it/s]

tensor(13.0951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:06<00:22, 10.40it/s]

tensor(13.0312, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0110, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:06<00:22, 10.34it/s]

tensor(12.9727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9546, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9371, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:21, 10.32it/s]

tensor(12.9202, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9037, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 77/300 [00:07<00:21, 10.36it/s]

tensor(12.8723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8423, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:07<00:21, 10.35it/s]

tensor(12.8279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8140, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 83/300 [00:08<00:21, 10.31it/s]

tensor(12.7874, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7745, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7623, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:20, 10.40it/s]

tensor(12.7504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7389, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|██▉       | 89/300 [00:08<00:20, 10.45it/s]

tensor(12.7170, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:19, 10.38it/s]

tensor(12.6866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 95/300 [00:09<00:19, 10.34it/s]

tensor(12.6585, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6496, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:09<00:19, 10.28it/s]

tensor(12.6325, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([124, 348, 237,  82,  39, 406, 123,  56, 247, 149,  74, 137, 122, 104])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:23, 27.01it/s]
  0%|          | 9/2248 [00:00<01:27, 25.66it/s]
  1%|          | 12/2248 [00:00<01:37, 23.02it/s]
  1%|          | 16/2248 [00:00<01:22, 27.17it/s]
  1%|          | 22/2248 [00:00<01:03, 35.16it/s]
  1%|          | 27/2248 [00:00<00:57, 38.66it/s]
  1%|▏         | 33/2248 [00:00<00:50, 43.48it/s]
  2%|▏         | 38/2248 [00:01<01:19, 27.96it/s]
  2%|▏         | 42/2248 [00:01<01:41, 21.76it/s]
  2%|▏         | 48/2248 [00:01<01:19, 27.58it/s]
  2%|▏         | 52/2248 [00:01<01:20, 27.35it/s]
  2%|▏         | 56/2248 [00:02<01:40, 21.74it/s]
  3%|▎         | 59/2248 [00:02<01:41, 21.62it/s]
  3%|▎         | 62/2248 [00:02<01:40, 21.76it/s]
  3%|▎         | 67/2248 [00:02<01:26, 25.10it/s]
  3%|▎         | 71/2248 [00:02<01:23, 26.08it/s]
  3%|▎         | 75/2248 [00:02<01:36, 22.55it/s]
  3%|▎         | 78/2248 [00:03<01:50, 19.59it/s]
  4%|▎         | 81/2248 [00:03<02:30, 14.44it/s]
  4%|▎         | 83/2248 [00:03<03:13, 11.21it/s]
  4%|▍         | 85/2248 [00:04<03:24, 10.59it/s]
  4%|▍         | 87/2248 [00:04<04:26,  8.12it/s]
  4%|▍         | 89/2248 [00:04<04:16,  8.43it/s]
  4%|▍         | 90/2248 [00:04<04:44,  7.58it/s]
  4%|▍         | 92/2248 [00:05<03:52,  9.27it/s]
  4%|▍         | 94/2248 [00:05<04:49,  7.45it/s]
  4%|▍         | 96/2248 [00:05<04:14,  8.46it/s]
  4%|▍         | 98/2248 [00:05<04:40,  7.67it/s]
  4%|▍         | 99/2248 [00:06<04:54,  7.30it/s]
  4%|▍         | 100/2248 [00:06<04:49,  7.42it/s]
  4%|▍         | 101/2248 [00:06<04:44,  7.55it/s]
  5%|▍         | 102/2248 [00:06<04:47,  7.47it/s]
  5%|▍         | 103/2248 [00:06<04:55,  7.25it/s]
  5%|▍         | 104/2248 [00:06<05:01,  7.10it/s]
  5%|▍         | 106/2248 [00:06<03:44,  9.54it/s]
  5%|▍         | 108/2248 [00:06<03:13, 11.04it/s]
  5%|▍         | 111/2248 [00:07<03:06, 11.45it/s]
  5%|▌         | 113/2248 [00:07<03:45,  9.49it/s]
  5%|▌         | 115/2248 [00:07<03:22, 10.55it/s]
  5%|▌         | 117/2248 [00:08<04:50,  7.34it/s]
  5%|▌         | 118/2248 [00:08<04:38,  7.65it/s]
  5%|▌         | 119/2248 [00:08<04:42,  7.54it/s]
  5%|▌         | 120/2248 [00:08<05:05,  6.97it/s]
  5%|▌         | 122/2248 [00:08<05:58,  5.93it/s]
 33%|███▎      | 99/300 [00:23<00:19, 10.28it/s]s]
  6%|▌         | 126/2248 [00:09<04:30,  7.84it/s]
  6%|▌         | 127/2248 [00:09<05:04,  6.96it/s]
  6%|▌         | 128/2248 [00:09<05:24,  6.53it/s]
  6%|▌         | 130/2248 [00:09<04:19,  8.18it/s]
  6%|▌         | 133/2248 [00:10<04:26,  7.94it/s]
  6%|▌         | 135/2248 [00:10<05:13,  6.73it/s]
  6%|▌         | 136/2248 [00:11<06:33,  5.36it/s]
  6%|▌         | 138/2248 [00:11<05:31,  6.37it/s]
  6%|▌         | 140/2248 [00:11<04:36,  7.63it/s]
  6%|▋         | 142/2248 [00:11<04:15,  8.25it/s]
  6%|▋         | 144/2248 [00:11<03:35,  9.75it/s]
  6%|▋         | 146/2248 [00:12<04:47,  7.32it/s]
  7%|▋         | 149/2248 [00:12<03:23, 10.33it/s]
  7%|▋         | 151/2248 [00:12<03:29, 10.01it/s]
  7%|▋         | 153/2248 [00:12<03:00, 11.62it/s]
  7%|▋         | 155/2248 [00:12<02:38, 13.19it/s]
  7%|▋         | 157/2248 [00:13<04:22,  7.96it/s]
  7%|▋         | 159/2248 [00:13<05:54,  5.89it/s]
  7%|▋         | 161/2248 [00:14<05:25,  6.41it/s]
  7%|▋         | 162/2248 [00:14<05:11,  6.70it/s]
  7%|▋         | 164/2248 [00:14<04:07,  8.41it/s]
  7%|▋         | 166/2248 [00:14<03:51,  9.00it/s]
  7%|▋         | 168/2248 [00:14<03:40,  9.45it/s]
  8%|▊         | 170/2248 [00:14<03:21, 10.30it/s]
  8%|▊         | 172/2248 [00:14<03:30,  9.84it/s]
  8%|▊         | 174/2248 [00:15<03:44,  9.23it/s]
  8%|▊         | 176/2248 [00:15<03:34,  9.66it/s]
  8%|▊         | 178/2248 [00:15<03:23, 10.17it/s]
  8%|▊         | 180/2248 [00:15<03:22, 10.20it/s]
  8%|▊         | 182/2248 [00:15<03:00, 11.42it/s]
  8%|▊         | 184/2248 [00:16<03:11, 10.76it/s]
  8%|▊         | 186/2248 [00:16<03:45,  9.16it/s]
  8%|▊         | 187/2248 [00:16<04:28,  7.67it/s]
  8%|▊         | 188/2248 [00:16<04:19,  7.94it/s]
  8%|▊         | 189/2248 [00:16<04:15,  8.06it/s]
  8%|▊         | 190/2248 [00:17<04:33,  7.52it/s]
  8%|▊         | 191/2248 [00:17<04:35,  7.46it/s]
  9%|▊         | 193/2248 [00:17<04:52,  7.03it/s]
  9%|▊         | 194/2248 [00:17<05:35,  6.12it/s]
  9%|▊         | 195/2248 [00:18<07:00,  4.89it/s]
  9%|▉         | 197/2248 [00:18<05:29,  6.23it/s]
  9%|▉         | 199/2248 [00:18<04:31,  7.54it/s]
  9%|▉         | 200/2248 [00:18<04:18,  7.93it/s]
  9%|▉         | 201/2248 [00:18<04:55,  6.94it/s]
  9%|▉         | 202/2248 [00:19<06:36,  5.16it/s]
  9%|▉         | 204/2248 [00:19<05:08,  6.62it/s]
  9%|▉         | 205/2248 [00:19<05:16,  6.45it/s]
  9%|▉         | 206/2248 [00:19<05:23,  6.30it/s]
  9%|▉         | 207/2248 [00:19<06:04,  5.60it/s]
  9%|▉         | 208/2248 [00:20<06:06,  5.56it/s]
  9%|▉         | 209/2248 [00:20<07:07,  4.77it/s]
  9%|▉         | 210/2248 [00:20<07:13,  4.70it/s]
  9%|▉         | 211/2248 [00:20<07:03,  4.80it/s]
  9%|▉         | 212/2248 [00:20<07:08,  4.75it/s]
  9%|▉         | 213/2248 [00:21<06:04,  5.58it/s]
 10%|▉         | 215/2248 [00:21<04:16,  7.94it/s]
 10%|▉         | 217/2248 [00:21<03:21, 10.09it/s]
 10%|▉         | 222/2248 [00:21<01:47, 18.92it/s]
 10%|█         | 228/2248 [00:21<01:11, 28.26it/s]
 10%|█         | 234/2248 [00:21<00:55, 36.09it/s]
 11%|█         | 239/2248 [00:21<01:20, 24.97it/s]
 11%|█         | 244/2248 [00:22<01:11, 28.07it/s]
 11%|█         | 251/2248 [00:22<00:55, 35.83it/s]
 11%|█▏        | 258/2248 [00:22<00:45, 43.41it/s]
 12%|█▏        | 264/2248 [00:22<01:15, 26.21it/s]
 12%|█▏        | 268/2248 [00:23<01:44, 18.91it/s]
 12%|█▏        | 272/2248 [00:23<02:00, 16.43it/s]
 12%|█▏        | 275/2248 [00:23<02:12, 14.85it/s]
 12%|█▏        | 278/2248 [00:23<02:15, 14.56it/s]
 12%|█▏        | 280/2248 [00:24<02:33, 12.82it/s]
 13%|█▎        | 282/2248 [00:24<03:15, 10.04it/s]
 13%|█▎        | 284/2248 [00:24<03:43,  8.78it/s]
 13%|█▎        | 286/2248 [00:25<03:51,  8.46it/s]
 13%|█▎        | 287/2248 [00:25<04:21,  7.49it/s]
 13%|█▎        | 289/2248 [00:25<04:15,  7.66it/s]
 13%|█▎        | 290/2248 [00:25<04:59,  6.54it/s]
 13%|█▎        | 291/2248 [00:26<05:23,  6.05it/s]
 13%|█▎        | 292/2248 [00:26<06:49,  4.77it/s]
 13%|█▎        | 295/2248 [00:26<05:40,  5.73it/s]
 13%|█▎        | 296/2248 [00:27<05:49,  5.58it/s]
 13%|█▎        | 298/2248 [00:27<06:03,  5.37it/s]
 13%|█▎        | 299/2248 [00:27<06:00,  5.40it/s]
 13%|█▎        | 302/2248 [00:27<04:42,  6.90it/s]
 13%|█▎        | 303/2248 [00:28<05:00,  6.47it/s]
 14%|█▎        | 305/2248 [00:28<04:58,  6.52it/s]
 14%|█▎        | 306/2248 [00:28<06:02,  5.35it/s]
 14%|█▎        | 307/2248 [00:29<07:18,  4.43it/s]
 14%|█▎        | 308/2248 [00:29<07:11,  4.50it/s]
 14%|█▎        | 309/2248 [00:29<08:11,  3.95it/s]
 14%|█▍        | 310/2248 [00:29<07:00,  4.61it/s]
 14%|█▍        | 312/2248 [00:30<05:49,  5.53it/s]
 14%|█▍        | 313/2248 [00:30<07:16,  4.43it/s]
 14%|█▍        | 314/2248 [00:30<08:37,  3.74it/s]
 14%|█▍        | 315/2248 [00:31<09:31,  3.38it/s]
 14%|█▍        | 317/2248 [00:31<06:18,  5.10it/s]
 14%|█▍        | 320/2248 [00:31<05:23,  5.96it/s]
 14%|█▍        | 322/2248 [00:32<05:57,  5.38it/s]
 14%|█▍        | 323/2248 [00:32<07:11,  4.46it/s]
 14%|█▍        | 324/2248 [00:32<07:13,  4.44it/s]
 14%|█▍        | 325/2248 [00:33<07:08,  4.49it/s]
 15%|█▍        | 327/2248 [00:33<06:48,  4.70it/s]
 15%|█▍        | 328/2248 [00:33<06:44,  4.74it/s]
 15%|█▍        | 329/2248 [00:33<05:59,  5.34it/s]
 15%|█▍        | 331/2248 [00:33<04:14,  7.54it/s]
 15%|█▍        | 332/2248 [00:34<05:38,  5.66it/s]
 15%|█▍        | 335/2248 [00:34<03:33,  8.94it/s]
 15%|█▌        | 339/2248 [00:34<02:52, 11.08it/s]
 15%|█▌        | 341/2248 [00:34<02:40, 11.87it/s]
 15%|█▌        | 343/2248 [00:35<03:20,  9.48it/s]
 15%|█▌        | 345/2248 [00:35<04:16,  7.43it/s]
 15%|█▌        | 346/2248 [00:35<04:29,  7.06it/s]
 15%|█▌        | 347/2248 [00:35<04:42,  6.72it/s]
 15%|█▌        | 348/2248 [00:36<05:19,  5.95it/s]
 16%|█▌        | 349/2248 [00:36<05:20,  5.92it/s]
 16%|█▌        | 350/2248 [00:36<05:53,  5.37it/s]
 16%|█▌        | 352/2248 [00:36<04:18,  7.32it/s]
 16%|█▌        | 353/2248 [00:36<05:03,  6.25it/s]
 16%|█▌        | 355/2248 [00:36<03:51,  8.19it/s]
 16%|█▌        | 356/2248 [00:37<03:55,  8.03it/s]
 16%|█▌        | 359/2248 [00:37<02:45, 11.40it/s]
 16%|█▌        | 362/2248 [00:37<02:32, 12.33it/s]
 16%|█▌        | 364/2248 [00:37<02:53, 10.84it/s]
 16%|█▋        | 366/2248 [00:38<03:37,  8.67it/s]
 16%|█▋        | 367/2248 [00:38<04:52,  6.43it/s]
 16%|█▋        | 369/2248 [00:38<04:27,  7.02it/s]
 17%|█▋        | 371/2248 [00:39<05:05,  6.15it/s]
 17%|█▋        | 373/2248 [00:39<04:50,  6.45it/s]
 17%|█▋        | 375/2248 [00:39<03:55,  7.95it/s]
 17%|█▋        | 377/2248 [00:39<04:07,  7.55it/s]
 17%|█▋        | 379/2248 [00:40<04:47,  6.51it/s]
 17%|█▋        | 381/2248 [00:40<05:12,  5.98it/s]
 17%|█▋        | 383/2248 [00:40<04:08,  7.52it/s]
 17%|█▋        | 385/2248 [00:41<04:57,  6.26it/s]
 17%|█▋        | 387/2248 [00:41<04:03,  7.65it/s]
 17%|█▋        | 389/2248 [00:41<05:24,  5.73it/s]
 17%|█▋        | 390/2248 [00:41<05:36,  5.53it/s]
 17%|█▋        | 391/2248 [00:42<06:05,  5.09it/s]
 17%|█▋        | 392/2248 [00:42<07:22,  4.19it/s]
 17%|█▋        | 393/2248 [00:43<08:32,  3.62it/s]
 18%|█▊        | 394/2248 [00:43<10:03,  3.07it/s]
 18%|█▊        | 395/2248 [00:43<09:28,  3.26it/s]
 18%|█▊        | 397/2248 [00:43<06:05,  5.06it/s]
 18%|█▊        | 400/2248 [00:43<03:47,  8.13it/s]
 18%|█▊        | 402/2248 [00:44<03:05,  9.97it/s]
 18%|█▊        | 404/2248 [00:44<03:20,  9.18it/s]
 18%|█▊        | 406/2248 [00:44<02:56, 10.44it/s]
 18%|█▊        | 408/2248 [00:44<02:51, 10.73it/s]
 18%|█▊        | 410/2248 [00:44<02:34, 11.88it/s]
 18%|█▊        | 412/2248 [00:44<02:24, 12.73it/s]
 18%|█▊        | 414/2248 [00:45<02:32, 12.00it/s]
 19%|█▊        | 416/2248 [00:45<02:33, 11.97it/s]
 19%|█▊        | 418/2248 [00:45<02:33, 11.92it/s]
 19%|█▊        | 420/2248 [00:45<02:23, 12.77it/s]
 19%|█▉        | 422/2248 [00:45<02:16, 13.35it/s]
 19%|█▉        | 424/2248 [00:45<02:16, 13.32it/s]
 19%|█▉        | 427/2248 [00:46<02:04, 14.62it/s]
 19%|█▉        | 429/2248 [00:46<02:39, 11.38it/s]
 19%|█▉        | 431/2248 [00:46<02:27, 12.33it/s]
 19%|█▉        | 434/2248 [00:46<01:59, 15.14it/s]
 19%|█▉        | 436/2248 [00:46<02:31, 11.96it/s]
 19%|█▉        | 438/2248 [00:47<02:43, 11.06it/s]
 20%|█▉        | 440/2248 [00:47<03:45,  8.03it/s]
 20%|█▉        | 442/2248 [00:47<03:14,  9.30it/s]
 20%|█▉        | 444/2248 [00:47<03:36,  8.34it/s]
 20%|█▉        | 446/2248 [00:48<03:42,  8.10it/s]
 20%|█▉        | 448/2248 [00:48<03:19,  9.02it/s]
 20%|██        | 450/2248 [00:48<03:40,  8.17it/s]
 20%|██        | 452/2248 [00:48<03:10,  9.42it/s]
 20%|██        | 454/2248 [00:49<03:32,  8.43it/s]
 20%|██        | 455/2248 [00:49<04:00,  7.45it/s]
 20%|██        | 457/2248 [00:49<04:10,  7.14it/s]
 20%|██        | 459/2248 [00:49<04:05,  7.27it/s]
 20%|██        | 460/2248 [00:50<04:30,  6.61it/s]
 21%|██        | 462/2248 [00:50<03:37,  8.21it/s]
 21%|██        | 463/2248 [00:50<03:40,  8.09it/s]
 21%|██        | 464/2248 [00:50<04:10,  7.11it/s]
 21%|██        | 465/2248 [00:50<04:19,  6.86it/s]
 21%|██        | 467/2248 [00:50<03:23,  8.76it/s]
 21%|██        | 469/2248 [00:50<02:50, 10.41it/s]
 21%|██        | 471/2248 [00:51<03:03,  9.70it/s]
 21%|██        | 473/2248 [00:51<02:54, 10.15it/s]
 21%|██        | 475/2248 [00:51<02:54, 10.15it/s]
 21%|██        | 477/2248 [00:51<03:24,  8.66it/s]
 21%|██▏       | 479/2248 [00:52<03:41,  8.00it/s]
 21%|██▏       | 480/2248 [00:52<04:35,  6.43it/s]
 21%|██▏       | 481/2248 [00:52<05:04,  5.81it/s]
 21%|██▏       | 482/2248 [00:52<06:12,  4.74it/s]
 22%|██▏       | 484/2248 [00:53<04:26,  6.61it/s]
 22%|██▏       | 485/2248 [00:53<04:49,  6.08it/s]
 22%|██▏       | 486/2248 [00:53<05:27,  5.38it/s]
 22%|██▏       | 487/2248 [00:53<06:29,  4.53it/s]
 22%|██▏       | 488/2248 [00:54<07:38,  3.84it/s]
 22%|██▏       | 490/2248 [00:54<05:06,  5.73it/s]
 22%|██▏       | 492/2248 [00:54<04:18,  6.79it/s]
 22%|██▏       | 494/2248 [00:54<03:18,  8.82it/s]
 22%|██▏       | 496/2248 [00:55<03:44,  7.80it/s]
 22%|██▏       | 498/2248 [00:55<03:08,  9.30it/s]
 22%|██▏       | 500/2248 [00:55<03:58,  7.34it/s]
 22%|██▏       | 502/2248 [00:55<03:26,  8.47it/s]
 22%|██▏       | 504/2248 [00:55<02:58,  9.78it/s]
 23%|██▎       | 506/2248 [00:56<03:09,  9.21it/s]
 23%|██▎       | 508/2248 [00:56<03:00,  9.64it/s]
 23%|██▎       | 510/2248 [00:56<03:47,  7.65it/s]
 23%|██▎       | 512/2248 [00:56<03:29,  8.28it/s]
 23%|██▎       | 513/2248 [00:57<03:52,  7.45it/s]
 23%|██▎       | 514/2248 [00:57<04:17,  6.73it/s]
 23%|██▎       | 515/2248 [00:57<04:28,  6.47it/s]
 23%|██▎       | 516/2248 [00:57<04:44,  6.10it/s]
 23%|██▎       | 517/2248 [00:58<06:33,  4.40it/s]
 23%|██▎       | 518/2248 [00:58<07:20,  3.92it/s]
 23%|██▎       | 519/2248 [00:58<08:26,  3.42it/s]
 23%|██▎       | 520/2248 [00:59<08:21,  3.45it/s]
 23%|██▎       | 523/2248 [00:59<04:19,  6.65it/s]
 24%|██▎       | 530/2248 [00:59<01:48, 15.81it/s]
 24%|██▍       | 537/2248 [00:59<01:09, 24.66it/s]
 24%|██▍       | 542/2248 [00:59<00:57, 29.53it/s]
 24%|██▍       | 547/2248 [00:59<01:19, 21.50it/s]
 25%|██▍       | 552/2248 [00:59<01:04, 26.11it/s]
 25%|██▍       | 556/2248 [01:00<01:05, 25.78it/s]
 25%|██▌       | 562/2248 [01:00<00:52, 31.83it/s]
 25%|██▌       | 567/2248 [01:00<01:08, 24.39it/s]
 25%|██▌       | 571/2248 [01:00<01:14, 22.56it/s]
 26%|██▌       | 574/2248 [01:01<02:27, 11.34it/s]
 26%|██▌       | 577/2248 [01:01<02:16, 12.20it/s]
 26%|██▌       | 579/2248 [01:01<02:41, 10.34it/s]
 26%|██▌       | 581/2248 [01:02<02:32, 10.94it/s]
 26%|██▌       | 583/2248 [01:02<02:50,  9.76it/s]
 26%|██▌       | 585/2248 [01:02<02:49,  9.79it/s]
 26%|██▌       | 587/2248 [01:02<03:06,  8.91it/s]
 26%|██▌       | 589/2248 [01:03<03:15,  8.47it/s]
 26%|██▋       | 592/2248 [01:03<02:51,  9.68it/s]
 26%|██▋       | 594/2248 [01:03<02:32, 10.88it/s]
 27%|██▋       | 598/2248 [01:03<01:49, 15.05it/s]
 27%|██▋       | 600/2248 [01:04<03:01,  9.06it/s]
 27%|██▋       | 603/2248 [01:04<03:29,  7.84it/s]
 27%|██▋       | 605/2248 [01:05<05:12,  5.26it/s]
 27%|██▋       | 606/2248 [01:05<05:45,  4.75it/s]
 27%|██▋       | 607/2248 [01:06<06:00,  4.56it/s]
 27%|██▋       | 608/2248 [01:06<05:56,  4.60it/s]
 27%|██▋       | 609/2248 [01:06<06:34,  4.16it/s]
 27%|██▋       | 610/2248 [01:06<06:46,  4.03it/s]
 27%|██▋       | 612/2248 [01:06<04:38,  5.88it/s]
 27%|██▋       | 614/2248 [01:07<03:29,  7.79it/s]
 27%|██▋       | 617/2248 [01:07<02:46,  9.80it/s]
 28%|██▊       | 619/2248 [01:07<02:29, 10.91it/s]
 28%|██▊       | 625/2248 [01:07<01:23, 19.40it/s]
 28%|██▊       | 628/2248 [01:07<01:17, 20.97it/s]
 28%|██▊       | 631/2248 [01:07<01:14, 21.60it/s]
 28%|██▊       | 634/2248 [01:07<01:12, 22.38it/s]
 28%|██▊       | 637/2248 [01:08<01:22, 19.42it/s]
 28%|██▊       | 640/2248 [01:08<01:29, 17.90it/s]
 29%|██▊       | 642/2248 [01:08<01:36, 16.70it/s]
 29%|██▊       | 645/2248 [01:08<01:23, 19.22it/s]
 29%|██▉       | 650/2248 [01:08<01:43, 15.40it/s]
 29%|██▉       | 652/2248 [01:09<02:53,  9.18it/s]
 29%|██▉       | 654/2248 [01:09<03:29,  7.59it/s]
 29%|██▉       | 658/2248 [01:10<03:18,  7.99it/s]
 29%|██▉       | 660/2248 [01:10<04:03,  6.52it/s]
 29%|██▉       | 661/2248 [01:11<04:51,  5.44it/s]
 29%|██▉       | 663/2248 [01:11<05:00,  5.27it/s]
 30%|██▉       | 665/2248 [01:12<05:11,  5.08it/s]
 30%|██▉       | 667/2248 [01:12<04:42,  5.60it/s]
 30%|██▉       | 669/2248 [01:12<03:45,  7.00it/s]
 30%|██▉       | 670/2248 [01:12<04:38,  5.67it/s]
 30%|██▉       | 673/2248 [01:13<03:38,  7.21it/s]
 30%|███       | 675/2248 [01:13<03:01,  8.69it/s]
 30%|███       | 677/2248 [01:13<03:02,  8.60it/s]
 30%|███       | 679/2248 [01:13<02:40,  9.80it/s]
 30%|███       | 681/2248 [01:13<03:17,  7.94it/s]
 30%|███       | 682/2248 [01:14<03:56,  6.63it/s]
 30%|███       | 684/2248 [01:14<03:26,  7.58it/s]
 30%|███       | 685/2248 [01:14<03:43,  7.00it/s]
 31%|███       | 686/2248 [01:14<04:03,  6.42it/s]
 31%|███       | 688/2248 [01:15<03:50,  6.78it/s]
 31%|███       | 691/2248 [01:15<02:57,  8.79it/s]
 31%|███       | 692/2248 [01:15<03:56,  6.59it/s]
 31%|███       | 694/2248 [01:15<03:18,  7.83it/s]
 31%|███       | 695/2248 [01:15<03:27,  7.47it/s]
 31%|███       | 696/2248 [01:16<03:40,  7.03it/s]
 31%|███       | 698/2248 [01:16<03:18,  7.80it/s]
 31%|███       | 699/2248 [01:16<03:34,  7.22it/s]
 31%|███       | 701/2248 [01:16<03:01,  8.53it/s]
 31%|███       | 702/2248 [01:17<04:20,  5.94it/s]
 31%|███▏      | 704/2248 [01:17<04:19,  5.95it/s]
 31%|███▏      | 706/2248 [01:17<03:18,  7.77it/s]
 32%|███▏      | 709/2248 [01:17<02:52,  8.92it/s]
 32%|███▏      | 711/2248 [01:18<03:26,  7.46it/s]
 32%|███▏      | 712/2248 [01:18<03:42,  6.91it/s]
 32%|███▏      | 713/2248 [01:18<03:57,  6.46it/s]
 32%|███▏      | 715/2248 [01:18<03:53,  6.58it/s]
 32%|███▏      | 716/2248 [01:18<04:11,  6.09it/s]
 32%|███▏      | 717/2248 [01:19<03:50,  6.63it/s]
 32%|███▏      | 719/2248 [01:19<03:36,  7.07it/s]
 32%|███▏      | 720/2248 [01:19<03:55,  6.50it/s]
 32%|███▏      | 721/2248 [01:19<05:11,  4.91it/s]
 32%|███▏      | 723/2248 [01:20<04:17,  5.91it/s]
 32%|███▏      | 725/2248 [01:20<03:15,  7.80it/s]
 32%|███▏      | 727/2248 [01:20<03:16,  7.76it/s]
 32%|███▏      | 728/2248 [01:20<03:38,  6.96it/s]
 32%|███▏      | 729/2248 [01:20<03:59,  6.35it/s]
 33%|███▎      | 731/2248 [01:21<04:06,  6.16it/s]
 33%|███▎      | 732/2248 [01:21<04:25,  5.72it/s]
 33%|███▎      | 733/2248 [01:21<04:38,  5.44it/s]
 33%|███▎      | 734/2248 [01:21<04:43,  5.34it/s]
 33%|███▎      | 735/2248 [01:22<04:54,  5.14it/s]
 33%|███▎      | 736/2248 [01:22<05:16,  4.78it/s]
 33%|███▎      | 737/2248 [01:22<06:37,  3.80it/s]
 33%|███▎      | 738/2248 [01:23<07:37,  3.30it/s]
 33%|███▎      | 740/2248 [01:23<04:47,  5.24it/s]
 33%|███▎      | 742/2248 [01:23<04:52,  5.15it/s]
 33%|███▎      | 743/2248 [01:23<04:56,  5.07it/s]
 33%|███▎      | 744/2248 [01:24<05:09,  4.86it/s]
 33%|███▎      | 745/2248 [01:24<04:34,  5.48it/s]
 33%|███▎      | 749/2248 [01:24<03:09,  7.90it/s]
 33%|███▎      | 751/2248 [01:24<03:04,  8.13it/s]
 33%|███▎      | 752/2248 [01:25<03:28,  7.19it/s]
 34%|███▎      | 754/2248 [01:25<03:19,  7.48it/s]
 34%|███▎      | 757/2248 [01:25<02:23, 10.37it/s]
 34%|███▍      | 761/2248 [01:25<02:08, 11.58it/s]
 34%|███▍      | 764/2248 [01:25<01:46, 13.97it/s]
 34%|███▍      | 767/2248 [01:26<02:04, 11.88it/s]
 34%|███▍      | 769/2248 [01:26<02:02, 12.07it/s]
 34%|███▍      | 772/2248 [01:26<01:50, 13.36it/s]
 34%|███▍      | 774/2248 [01:27<03:04,  7.97it/s]
 35%|███▍      | 776/2248 [01:27<03:49,  6.42it/s]
 35%|███▍      | 778/2248 [01:27<04:00,  6.11it/s]
 35%|███▍      | 779/2248 [01:28<03:47,  6.45it/s]
 35%|███▍      | 781/2248 [01:28<03:03,  8.00it/s]
 35%|███▍      | 783/2248 [01:28<03:50,  6.36it/s]
 35%|███▍      | 784/2248 [01:28<03:51,  6.31it/s]
 35%|███▍      | 786/2248 [01:28<03:13,  7.57it/s]
 35%|███▌      | 789/2248 [01:29<02:44,  8.88it/s]
 35%|███▌      | 791/2248 [01:29<02:50,  8.56it/s]
 35%|███▌      | 792/2248 [01:29<03:18,  7.34it/s]
 35%|███▌      | 794/2248 [01:30<03:37,  6.69it/s]
 35%|███▌      | 796/2248 [01:30<02:57,  8.16it/s]
 35%|███▌      | 797/2248 [01:30<03:41,  6.56it/s]
 36%|███▌      | 799/2248 [01:30<03:25,  7.05it/s]
 36%|███▌      | 800/2248 [01:31<04:35,  5.26it/s]
 36%|███▌      | 803/2248 [01:31<02:56,  8.19it/s]
 36%|███▌      | 806/2248 [01:31<03:09,  7.59it/s]
 36%|███▌      | 809/2248 [01:31<02:23, 10.02it/s]
 36%|███▌      | 811/2248 [01:32<04:04,  5.87it/s]
 36%|███▌      | 813/2248 [01:33<05:16,  4.54it/s]
 36%|███▌      | 814/2248 [01:33<05:26,  4.40it/s]
 36%|███▋      | 816/2248 [01:33<05:02,  4.74it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 323.09it/s]

[[np.int64(0), False, 8], [np.int64(1), False, 5], [np.int64(2), False, 8], [np.int64(3), False, 9], [np.int64(4), False, 10], [np.int64(6), False, 0], [np.int64(7), False, 11], [np.int64(11), False, 0], [np.int64(12), False, 2], [np.int64(13), False, 5]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.6078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1010, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:23<2:06:34, 38.16s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:23<1:43:49, 31.46s/it]

tensor(12.5980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1670, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1557, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:24<48:16, 14.86s/it]

tensor(12.5831, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2009, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2563, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [04:24<26:08,  8.13s/it]

tensor(12.5827, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3263, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3853, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [04:24<13:34,  4.27s/it]

tensor(12.5937, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4380, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4818, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [04:24<06:57,  2.21s/it]

tensor(12.6066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5323, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5887, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:25<03:36,  1.16s/it]

tensor(12.6122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6261, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6653, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:25<01:56,  1.59it/s]

tensor(12.6090, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6995, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6040, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7400, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [04:25<01:07,  2.71it/s]

tensor(12.5973, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7726, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5897, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8044, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [04:25<00:43,  4.16it/s]

tensor(12.5810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8331, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8604, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [04:25<00:31,  5.66it/s]

tensor(12.5625, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8853, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9035, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [04:26<00:25,  6.85it/s]

tensor(12.5438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9211, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9367, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [04:26<00:22,  7.67it/s]

tensor(12.5247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9656, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [04:26<00:21,  8.10it/s]

tensor(12.5053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9843, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:26<00:20,  8.39it/s]

tensor(12.4863, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0010, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4777, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0150, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:27<00:20,  8.37it/s]

tensor(12.4696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0278, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0428, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [04:27<00:19,  8.38it/s]

tensor(12.4547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0599, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4470, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0668, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [04:27<00:19,  8.47it/s]

tensor(12.4395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0821, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0970, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [04:27<00:19,  8.42it/s]

tensor(12.4253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1078, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1214, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [04:28<00:19,  8.41it/s]

tensor(12.4127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1375, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1483, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:28<00:18,  8.56it/s]

tensor(12.4011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1649, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1792, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:28<00:18,  8.59it/s]

tensor(12.3902, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1883, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1991, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [04:28<00:18,  8.61it/s]

tensor(12.3803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2130, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2247, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [04:29<00:17,  8.68it/s]

tensor(12.3708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3661, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2578, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:29<00:17,  8.55it/s]

tensor(12.3613, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2739, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3568, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2892, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:29<00:17,  8.50it/s]

tensor(12.3523, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3094, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([119, 337, 135,  59, 240, 121, 140, 413,  71, 249, 128,  89,  81,  66])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<03:14, 11.56it/s]
  0%|          | 4/2248 [00:00<02:32, 14.75it/s]
  0%|          | 6/2248 [00:00<02:29, 15.04it/s]
  0%|          | 8/2248 [00:00<02:15, 16.49it/s]
  0%|          | 10/2248 [00:00<02:32, 14.63it/s]
  1%|          | 13/2248 [00:00<02:02, 18.21it/s]
  1%|          | 19/2248 [00:00<01:15, 29.39it/s]
  1%|          | 25/2248 [00:01<01:00, 36.50it/s]
  1%|▏         | 29/2248 [00:01<01:17, 28.61it/s]
  2%|▏         | 34/2248 [00:01<01:30, 24.44it/s]
  2%|▏         | 37/2248 [00:01<01:34, 23.44it/s]
  2%|▏         | 43/2248 [00:01<01:12, 30.23it/s]
  2%|▏         | 47/2248 [00:02<01:51, 19.70it/s]
  2%|▏         | 50/2248 [00:02<02:02, 17.95it/s]
  2%|▏         | 53/2248 [00:02<02:16, 16.13it/s]
  3%|▎         | 57/2248 [00:02<01:55, 18.89it/s]
  3%|▎         | 64/2248 [00:02<01:19, 27.49it/s]
  3%|▎         | 71/2248 [00:02<01:06, 32.85it/s]
  3%|▎         | 75/2248 [00:03<01:21, 26.70it/s]
  4%|▎         | 79/2248 [00:04<03:25, 10.55it/s]
  4%|▎         | 82/2248 [00:04<03:06, 11.59it/s]
  4%|▍         | 86/2248 [00:05<04:18,  8.36it/s]
  4%|▍         | 88/2248 [00:05<03:57,  9.11it/s]
  4%|▍         | 90/2248 [00:05<04:14,  8.47it/s]
  4%|▍         | 93/2248 [00:05<03:23, 10.59it/s]
  4%|▍         | 95/2248 [00:05<03:17, 10.92it/s]
  4%|▍         | 97/2248 [00:06<03:53,  9.20it/s]
  4%|▍         | 99/2248 [00:06<04:06,  8.73it/s]
  4%|▍         | 101/2248 [00:06<03:42,  9.64it/s]
  5%|▍         | 103/2248 [00:06<03:34, 10.02it/s]
  5%|▍         | 105/2248 [00:07<03:50,  9.32it/s]
  5%|▍         | 109/2248 [00:07<02:33, 13.93it/s]
  5%|▍         | 111/2248 [00:07<02:54, 12.25it/s]
  5%|▌         | 113/2248 [00:07<04:17,  8.29it/s]
  5%|▌         | 115/2248 [00:08<03:36,  9.83it/s]
  5%|▌         | 117/2248 [00:08<06:42,  5.29it/s]
  5%|▌         | 119/2248 [00:09<09:22,  3.79it/s]
  5%|▌         | 120/2248 [00:10<11:53,  2.98it/s]
  5%|▌         | 122/2248 [00:11<12:12,  2.90it/s]
  6%|▌         | 125/2248 [00:11<11:00,  3.22it/s]
  6%|▌         | 126/2248 [00:12<13:26,  2.63it/s]
  6%|▌         | 127/2248 [00:13<15:46,  2.24it/s]
  6%|▌         | 128/2248 [00:14<17:28,  2.02it/s]
  6%|▌         | 130/2248 [00:14<13:09,  2.68it/s]
  6%|▌         | 133/2248 [00:15<11:09,  3.16it/s]
  6%|▌         | 135/2248 [00:15<10:41,  3.29it/s]
  6%|▌         | 136/2248 [00:15<09:54,  3.55it/s]
  6%|▌         | 138/2248 [00:16<09:41,  3.63it/s]
  6%|▌         | 139/2248 [00:16<08:47,  4.00it/s]
  6%|▋         | 142/2248 [00:17<08:14,  4.26it/s]
  6%|▋         | 143/2248 [00:17<07:49,  4.48it/s]
  6%|▋         | 145/2248 [00:17<07:12,  4.87it/s]
  7%|▋         | 148/2248 [00:17<04:48,  7.29it/s]
  7%|▋         | 151/2248 [00:18<04:30,  7.76it/s]
  7%|▋         | 154/2248 [00:18<03:41,  9.46it/s]
  7%|▋         | 156/2248 [00:18<05:08,  6.78it/s]
  7%|▋         | 157/2248 [00:19<06:56,  5.02it/s]
  7%|▋         | 158/2248 [00:20<09:21,  3.72it/s]
  7%|▋         | 159/2248 [00:20<09:37,  3.62it/s]
  7%|▋         | 160/2248 [00:20<11:48,  2.95it/s]
  7%|▋         | 162/2248 [00:21<10:10,  3.41it/s]
  7%|▋         | 164/2248 [00:21<07:16,  4.78it/s]
  7%|▋         | 165/2248 [00:21<07:09,  4.85it/s]
  7%|▋         | 166/2248 [00:21<07:21,  4.72it/s]
  7%|▋         | 168/2248 [00:21<05:14,  6.61it/s]
  8%|▊         | 170/2248 [00:22<04:18,  8.05it/s]
  8%|▊         | 172/2248 [00:22<04:03,  8.54it/s]
  8%|▊         | 174/2248 [00:22<04:58,  6.96it/s]
  8%|▊         | 176/2248 [00:23<07:17,  4.73it/s]
  8%|▊         | 177/2248 [00:23<06:59,  4.93it/s]
  8%|▊         | 178/2248 [00:24<10:06,  3.42it/s]
  8%|▊         | 179/2248 [00:24<08:58,  3.84it/s]
  8%|▊         | 180/2248 [00:24<08:31,  4.04it/s]
  8%|▊         | 182/2248 [00:24<05:50,  5.90it/s]
  8%|▊         | 183/2248 [00:24<06:34,  5.24it/s]
  8%|▊         | 185/2248 [00:25<05:38,  6.09it/s]
  8%|▊         | 187/2248 [00:25<06:08,  5.59it/s]
  8%|▊         | 188/2248 [00:25<06:30,  5.28it/s]
  8%|▊         | 189/2248 [00:26<06:26,  5.32it/s]
  8%|▊         | 190/2248 [00:26<06:31,  5.26it/s]
  9%|▊         | 193/2248 [00:26<04:54,  6.97it/s]
  9%|▊         | 194/2248 [00:26<05:10,  6.61it/s]
  9%|▊         | 195/2248 [00:27<09:13,  3.71it/s]
  9%|▉         | 198/2248 [00:27<05:21,  6.38it/s]
  9%|▉         | 200/2248 [00:27<05:47,  5.90it/s]
  9%|▉         | 201/2248 [00:28<05:59,  5.69it/s]
  9%|▉         | 202/2248 [00:28<05:27,  6.25it/s]
  9%|▉         | 204/2248 [00:28<04:03,  8.40it/s]
  9%|▉         | 206/2248 [00:29<06:39,  5.11it/s]
  9%|▉         | 207/2248 [00:29<06:32,  5.20it/s]
  9%|▉         | 208/2248 [00:29<06:52,  4.94it/s]
  9%|▉         | 209/2248 [00:29<06:34,  5.17it/s]
  9%|▉         | 210/2248 [00:29<07:43,  4.40it/s]
  9%|▉         | 211/2248 [00:30<09:07,  3.72it/s]
  9%|▉         | 212/2248 [00:30<07:58,  4.25it/s]
 10%|▉         | 214/2248 [00:30<06:06,  5.55it/s]
 10%|▉         | 216/2248 [00:30<04:44,  7.14it/s]
 10%|▉         | 218/2248 [00:30<03:41,  9.16it/s]
 10%|▉         | 220/2248 [00:31<03:27,  9.79it/s]
 10%|▉         | 222/2248 [00:31<03:10, 10.65it/s]
 10%|▉         | 224/2248 [00:31<02:42, 12.45it/s]
 10%|█         | 226/2248 [00:31<03:45,  8.95it/s]
 10%|█         | 228/2248 [00:32<05:05,  6.62it/s]
 10%|█         | 231/2248 [00:32<03:36,  9.32it/s]
 10%|█         | 233/2248 [00:32<03:06, 10.80it/s]
 10%|█         | 236/2248 [00:32<03:00, 11.16it/s]
 11%|█         | 239/2248 [00:32<02:22, 14.07it/s]
 11%|█         | 245/2248 [00:32<01:28, 22.64it/s]
 11%|█         | 249/2248 [00:33<01:36, 20.63it/s]
 11%|█         | 252/2248 [00:33<01:47, 18.54it/s]
 11%|█▏        | 258/2248 [00:33<01:19, 24.88it/s]
 12%|█▏        | 262/2248 [00:33<01:30, 22.02it/s]
 12%|█▏        | 265/2248 [00:34<02:24, 13.77it/s]
 12%|█▏        | 268/2248 [00:34<02:52, 11.51it/s]
 12%|█▏        | 270/2248 [00:35<04:51,  6.79it/s]
 12%|█▏        | 272/2248 [00:35<04:12,  7.82it/s]
 12%|█▏        | 274/2248 [00:35<04:23,  7.49it/s]
 12%|█▏        | 276/2248 [00:36<06:14,  5.26it/s]
 12%|█▏        | 277/2248 [00:36<06:28,  5.08it/s]
 12%|█▏        | 279/2248 [00:36<05:14,  6.26it/s]
 12%|█▏        | 280/2248 [00:37<05:39,  5.80it/s]
 13%|█▎        | 282/2248 [00:37<05:46,  5.67it/s]
 13%|█▎        | 283/2248 [00:37<06:45,  4.84it/s]
 13%|█▎        | 284/2248 [00:38<06:55,  4.72it/s]
 13%|█▎        | 285/2248 [00:38<06:49,  4.80it/s]
 13%|█▎        | 286/2248 [00:38<06:42,  4.87it/s]
 13%|█▎        | 287/2248 [00:38<06:50,  4.78it/s]
 13%|█▎        | 288/2248 [00:38<07:11,  4.54it/s]
 13%|█▎        | 290/2248 [00:39<05:35,  5.83it/s]
 13%|█▎        | 291/2248 [00:39<05:57,  5.48it/s]
 13%|█▎        | 292/2248 [00:39<08:23,  3.88it/s]
 13%|█▎        | 294/2248 [00:40<06:54,  4.72it/s]
 13%|█▎        | 295/2248 [00:40<07:14,  4.49it/s]
 13%|█▎        | 297/2248 [00:40<06:03,  5.37it/s]
 13%|█▎        | 298/2248 [00:40<06:39,  4.88it/s]
 13%|█▎        | 299/2248 [00:41<06:05,  5.34it/s]
 13%|█▎        | 301/2248 [00:41<05:15,  6.17it/s]
 13%|█▎        | 302/2248 [00:41<05:26,  5.96it/s]
 13%|█▎        | 303/2248 [00:42<08:18,  3.91it/s]
 14%|█▎        | 304/2248 [00:42<07:51,  4.12it/s]
 14%|█▎        | 305/2248 [00:42<07:35,  4.26it/s]
 14%|█▎        | 306/2248 [00:43<11:50,  2.73it/s]
 14%|█▎        | 307/2248 [00:43<15:02,  2.15it/s]
 14%|█▎        | 308/2248 [00:44<12:41,  2.55it/s]
 14%|█▎        | 309/2248 [00:44<15:55,  2.03it/s]
 14%|█▍        | 312/2248 [00:45<08:49,  3.66it/s]
 14%|█▍        | 313/2248 [00:45<10:41,  3.01it/s]
 14%|█▍        | 314/2248 [00:46<10:45,  3.00it/s]
 14%|█▍        | 315/2248 [00:46<10:02,  3.21it/s]
 14%|█▍        | 317/2248 [00:46<06:44,  4.78it/s]
 14%|█▍        | 320/2248 [00:47<07:22,  4.36it/s]
 14%|█▍        | 322/2248 [00:47<08:58,  3.57it/s]
 14%|█▍        | 323/2248 [00:48<11:29,  2.79it/s]
 14%|█▍        | 325/2248 [00:48<09:11,  3.49it/s]
 15%|█▍        | 326/2248 [00:49<09:59,  3.21it/s]
 15%|█▍        | 327/2248 [00:49<08:58,  3.56it/s]
 15%|█▍        | 328/2248 [00:49<08:29,  3.77it/s]
 15%|█▍        | 329/2248 [00:49<07:46,  4.11it/s]
 15%|█▍        | 330/2248 [00:50<06:48,  4.69it/s]
 15%|█▍        | 332/2248 [00:50<06:42,  4.76it/s]
 15%|█▍        | 335/2248 [00:50<04:16,  7.46it/s]
 15%|█▌        | 339/2248 [00:51<04:30,  7.07it/s]
 15%|█▌        | 340/2248 [00:51<07:07,  4.47it/s]
 15%|█▌        | 342/2248 [00:52<06:33,  4.84it/s]
 15%|█▌        | 343/2248 [00:52<08:51,  3.59it/s]
 15%|█▌        | 344/2248 [00:53<11:06,  2.86it/s]
 15%|█▌        | 345/2248 [00:53<11:57,  2.65it/s]
 15%|█▌        | 346/2248 [00:54<13:34,  2.33it/s]
 15%|█▌        | 347/2248 [00:54<11:07,  2.85it/s]
 15%|█▌        | 348/2248 [00:54<09:47,  3.23it/s]
 16%|█▌        | 349/2248 [00:55<11:08,  2.84it/s]
 16%|█▌        | 350/2248 [00:55<11:21,  2.78it/s]
 16%|█▌        | 352/2248 [00:55<07:03,  4.48it/s]
 16%|█▌        | 353/2248 [00:56<08:06,  3.90it/s]
 16%|█▌        | 354/2248 [00:56<07:27,  4.24it/s]
 16%|█▌        | 355/2248 [00:56<06:38,  4.75it/s]
 16%|█▌        | 356/2248 [00:56<07:31,  4.19it/s]
 16%|█▌        | 358/2248 [00:56<05:07,  6.14it/s]
 16%|█▌        | 360/2248 [00:57<06:20,  4.96it/s]
 16%|█▌        | 362/2248 [00:58<08:24,  3.74it/s]
 16%|█▌        | 364/2248 [00:59<09:42,  3.24it/s]
 16%|█▋        | 366/2248 [00:59<07:40,  4.09it/s]
 16%|█▋        | 367/2248 [00:59<07:38,  4.10it/s]
 16%|█▋        | 369/2248 [00:59<06:53,  4.55it/s]
 17%|█▋        | 371/2248 [01:00<08:28,  3.69it/s]
 17%|█▋        | 373/2248 [01:00<06:58,  4.49it/s]
 17%|█▋        | 374/2248 [01:00<06:33,  4.77it/s]
 17%|█▋        | 377/2248 [01:01<04:55,  6.33it/s]
 17%|█▋        | 378/2248 [01:01<04:52,  6.40it/s]
 17%|█▋        | 379/2248 [01:02<07:49,  3.98it/s]
 17%|█▋        | 381/2248 [01:02<06:16,  4.96it/s]
 17%|█▋        | 383/2248 [01:02<04:43,  6.58it/s]
 17%|█▋        | 384/2248 [01:02<06:16,  4.95it/s]
 17%|█▋        | 385/2248 [01:02<05:35,  5.55it/s]
 17%|█▋        | 387/2248 [01:03<04:06,  7.54it/s]
 17%|█▋        | 389/2248 [01:03<05:13,  5.93it/s]
 17%|█▋        | 390/2248 [01:03<05:04,  6.11it/s]
 17%|█▋        | 391/2248 [01:03<05:43,  5.40it/s]
 17%|█▋        | 392/2248 [01:04<09:50,  3.14it/s]
 17%|█▋        | 393/2248 [01:04<10:07,  3.05it/s]
 18%|█▊        | 394/2248 [01:05<09:48,  3.15it/s]
 18%|█▊        | 395/2248 [01:05<09:12,  3.35it/s]
 18%|█▊        | 397/2248 [01:05<05:49,  5.29it/s]
 18%|█▊        | 398/2248 [01:05<05:22,  5.73it/s]
 18%|█▊        | 400/2248 [01:06<04:48,  6.42it/s]
 18%|█▊        | 402/2248 [01:06<04:18,  7.15it/s]
 18%|█▊        | 405/2248 [01:06<02:58, 10.35it/s]
 18%|█▊        | 408/2248 [01:06<02:20, 13.05it/s]
 18%|█▊        | 411/2248 [01:06<02:13, 13.75it/s]
 18%|█▊        | 414/2248 [01:06<01:51, 16.50it/s]
 19%|█▊        | 416/2248 [01:06<01:46, 17.23it/s]
 19%|█▉        | 422/2248 [01:07<01:10, 26.02it/s]
 19%|█▉        | 425/2248 [01:07<01:12, 25.26it/s]
 19%|█▉        | 429/2248 [01:07<01:16, 23.85it/s]
 19%|█▉        | 432/2248 [01:07<01:28, 20.59it/s]
 19%|█▉        | 436/2248 [01:07<01:31, 19.88it/s]
 20%|█▉        | 439/2248 [01:08<03:35,  8.38it/s]
 20%|█▉        | 441/2248 [01:09<03:53,  7.72it/s]
 20%|█▉        | 443/2248 [01:09<04:15,  7.08it/s]
 20%|█▉        | 445/2248 [01:10<05:37,  5.34it/s]
 20%|█▉        | 446/2248 [01:10<06:46,  4.44it/s]
 20%|█▉        | 448/2248 [01:10<06:58,  4.30it/s]
 20%|██        | 450/2248 [01:11<06:47,  4.42it/s]
 20%|██        | 453/2248 [01:11<05:11,  5.76it/s]
 20%|██        | 455/2248 [01:12<05:28,  5.45it/s]
 20%|██        | 457/2248 [01:12<04:39,  6.40it/s]
 20%|██        | 459/2248 [01:12<04:03,  7.36it/s]
 20%|██        | 460/2248 [01:12<04:00,  7.43it/s]
 21%|██        | 461/2248 [01:12<04:38,  6.41it/s]
 21%|██        | 463/2248 [01:13<05:15,  5.66it/s]
 21%|██        | 464/2248 [01:13<05:30,  5.40it/s]
 21%|██        | 465/2248 [01:13<07:23,  4.02it/s]
 21%|██        | 467/2248 [01:14<05:04,  5.84it/s]
 21%|██        | 470/2248 [01:14<03:15,  9.09it/s]
 21%|██        | 472/2248 [01:14<03:33,  8.34it/s]
 21%|██        | 474/2248 [01:14<03:28,  8.51it/s]
 21%|██        | 476/2248 [01:15<06:00,  4.91it/s]
 21%|██        | 477/2248 [01:15<05:52,  5.02it/s]
 21%|██▏       | 478/2248 [01:15<05:42,  5.17it/s]
 21%|██▏       | 479/2248 [01:16<07:36,  3.87it/s]
 21%|██▏       | 480/2248 [01:16<07:16,  4.05it/s]
 21%|██▏       | 481/2248 [01:17<11:08,  2.64it/s]
 21%|██▏       | 482/2248 [01:17<13:04,  2.25it/s]
 22%|██▏       | 484/2248 [01:18<08:10,  3.60it/s]
 22%|██▏       | 486/2248 [01:18<06:34,  4.46it/s]
 22%|██▏       | 487/2248 [01:18<06:05,  4.82it/s]
 22%|██▏       | 488/2248 [01:18<06:05,  4.82it/s]
 22%|██▏       | 490/2248 [01:18<04:16,  6.86it/s]
 22%|██▏       | 492/2248 [01:19<04:28,  6.53it/s]
 22%|██▏       | 494/2248 [01:19<03:27,  8.44it/s]
 22%|██▏       | 496/2248 [01:19<06:04,  4.81it/s]
 22%|██▏       | 498/2248 [01:20<04:58,  5.86it/s]
 22%|██▏       | 499/2248 [01:20<06:24,  4.55it/s]
 22%|██▏       | 500/2248 [01:20<06:34,  4.43it/s]
 22%|██▏       | 502/2248 [01:20<04:49,  6.02it/s]
 22%|██▏       | 505/2248 [01:21<03:10,  9.16it/s]
 23%|██▎       | 509/2248 [01:21<04:16,  6.78it/s]
 23%|██▎       | 512/2248 [01:22<05:18,  5.44it/s]
 23%|██▎       | 513/2248 [01:23<06:14,  4.63it/s]
 23%|██▎       | 514/2248 [01:23<07:13,  4.00it/s]
 23%|██▎       | 515/2248 [01:24<08:45,  3.30it/s]
 23%|██▎       | 516/2248 [01:24<08:35,  3.36it/s]
 23%|██▎       | 517/2248 [01:24<08:08,  3.54it/s]
 23%|██▎       | 518/2248 [01:24<08:29,  3.40it/s]
 23%|██▎       | 520/2248 [01:24<05:40,  5.08it/s]
 23%|██▎       | 521/2248 [01:25<05:18,  5.42it/s]
 23%|██▎       | 523/2248 [01:25<04:37,  6.21it/s]
 23%|██▎       | 524/2248 [01:25<07:36,  3.78it/s]
 23%|██▎       | 527/2248 [01:26<05:07,  5.60it/s]
 24%|██▎       | 529/2248 [01:26<04:00,  7.14it/s]
 24%|██▍       | 535/2248 [01:26<02:13, 12.86it/s]
 24%|██▍       | 537/2248 [01:26<02:13, 12.80it/s]
 24%|██▍       | 539/2248 [01:26<02:02, 13.98it/s]
 24%|██▍       | 541/2248 [01:26<02:01, 14.08it/s]
 24%|██▍       | 543/2248 [01:27<01:53, 15.01it/s]
 24%|██▍       | 546/2248 [01:27<01:41, 16.81it/s]
 24%|██▍       | 550/2248 [01:27<01:17, 21.79it/s]
 25%|██▍       | 557/2248 [01:27<00:51, 32.79it/s]
 25%|██▍       | 561/2248 [01:27<01:22, 20.45it/s]
 25%|██▌       | 564/2248 [01:28<02:20, 11.96it/s]
 25%|██▌       | 567/2248 [01:28<01:59, 14.01it/s]
 25%|██▌       | 571/2248 [01:28<01:46, 15.73it/s]
 26%|██▌       | 574/2248 [01:29<04:22,  6.37it/s]
 26%|██▌       | 576/2248 [01:30<03:47,  7.36it/s]
 26%|██▌       | 578/2248 [01:30<03:16,  8.50it/s]
 26%|██▌       | 580/2248 [01:30<04:46,  5.83it/s]
 26%|██▌       | 582/2248 [01:32<08:19,  3.33it/s]
 26%|██▌       | 583/2248 [01:32<07:28,  3.71it/s]
 26%|██▌       | 584/2248 [01:32<07:19,  3.78it/s]
 26%|██▌       | 585/2248 [01:32<08:08,  3.41it/s]
 26%|██▌       | 586/2248 [01:33<07:37,  3.63it/s]
 26%|██▌       | 588/2248 [01:33<08:30,  3.25it/s]
 26%|██▌       | 589/2248 [01:34<08:12,  3.37it/s]
 26%|██▋       | 592/2248 [01:34<05:30,  5.02it/s]
 26%|██▋       | 595/2248 [01:34<03:49,  7.20it/s]
 27%|██▋       | 600/2248 [01:35<04:01,  6.82it/s]
 27%|██▋       | 602/2248 [01:35<03:26,  7.97it/s]
 27%|██▋       | 604/2248 [01:36<05:07,  5.34it/s]
 27%|██▋       | 605/2248 [01:36<07:14,  3.78it/s]
 27%|██▋       | 606/2248 [01:37<08:13,  3.33it/s]
 27%|██▋       | 607/2248 [01:37<08:43,  3.13it/s]
 27%|██▋       | 608/2248 [01:38<08:26,  3.24it/s]
 27%|██▋       | 609/2248 [01:38<09:11,  2.97it/s]
 27%|██▋       | 610/2248 [01:38<09:10,  2.97it/s]
 27%|██▋       | 612/2248 [01:38<06:00,  4.54it/s]
 27%|██▋       | 613/2248 [01:39<05:22,  5.07it/s]
 27%|██▋       | 615/2248 [01:39<03:53,  7.00it/s]
 27%|██▋       | 617/2248 [01:39<03:36,  7.53it/s]
 28%|██▊       | 619/2248 [01:39<02:54,  9.31it/s]
 28%|██▊       | 621/2248 [01:39<03:09,  8.58it/s]
 28%|██▊       | 623/2248 [01:40<03:22,  8.04it/s]
 28%|██▊       | 624/2248 [01:40<03:38,  7.43it/s]
 28%|██▊       | 625/2248 [01:40<03:56,  6.87it/s]
 28%|██▊       | 627/2248 [01:40<03:02,  8.90it/s]
 28%|██▊       | 629/2248 [01:40<02:27, 10.97it/s]
 28%|██▊       | 633/2248 [01:40<01:37, 16.58it/s]
 28%|██▊       | 637/2248 [01:40<01:16, 20.95it/s]
 28%|██▊       | 640/2248 [01:41<01:13, 21.91it/s]
 29%|██▊       | 643/2248 [01:41<01:07, 23.62it/s]
 29%|██▊       | 646/2248 [01:41<01:21, 19.67it/s]
 29%|██▉       | 649/2248 [01:41<01:21, 19.68it/s]
 29%|██▉       | 652/2248 [01:42<03:27,  7.71it/s]
 29%|██▉       | 654/2248 [01:42<03:48,  6.99it/s]
 29%|██▉       | 656/2248 [01:43<03:37,  7.32it/s]
 29%|██▉       | 658/2248 [01:43<04:33,  5.82it/s]
 29%|██▉       | 660/2248 [01:43<04:31,  5.86it/s]
 29%|██▉       | 661/2248 [01:44<05:52,  4.50it/s]
 29%|██▉       | 663/2248 [01:44<05:36,  4.71it/s]
 30%|██▉       | 664/2248 [01:44<05:13,  5.05it/s]
 30%|██▉       | 665/2248 [01:45<06:11,  4.27it/s]
 30%|██▉       | 667/2248 [01:45<05:41,  4.63it/s]
 30%|██▉       | 668/2248 [01:45<05:29,  4.79it/s]
 30%|██▉       | 670/2248 [01:46<06:45,  3.90it/s]
 30%|██▉       | 672/2248 [01:46<04:56,  5.31it/s]
 30%|███       | 675/2248 [01:46<03:14,  8.11it/s]
 30%|███       | 677/2248 [01:47<04:21,  6.00it/s]
 30%|███       | 679/2248 [01:47<03:34,  7.32it/s]
 30%|███       | 681/2248 [01:48<04:54,  5.31it/s]
 30%|███       | 682/2248 [01:48<05:08,  5.07it/s]
 30%|███       | 683/2248 [01:48<05:37,  4.63it/s]
 30%|███       | 684/2248 [01:49<07:52,  3.31it/s]
 30%|███       | 685/2248 [01:49<10:23,  2.51it/s]
 31%|███       | 686/2248 [01:50<11:01,  2.36it/s]
 31%|███       | 687/2248 [01:50<09:58,  2.61it/s]
 31%|███       | 688/2248 [01:51<11:19,  2.30it/s]
 31%|███       | 690/2248 [01:51<06:56,  3.74it/s]
 31%|███       | 691/2248 [01:51<06:19,  4.10it/s]
 31%|███       | 692/2248 [01:51<07:16,  3.57it/s]
 31%|███       | 693/2248 [01:52<06:28,  4.01it/s]
 31%|███       | 694/2248 [01:52<06:28,  4.00it/s]
 31%|███       | 695/2248 [01:52<06:14,  4.14it/s]
 31%|███       | 697/2248 [01:52<05:28,  4.72it/s]
 31%|███       | 698/2248 [01:53<05:24,  4.77it/s]
 31%|███       | 699/2248 [01:53<08:51,  2.91it/s]
 31%|███       | 701/2248 [01:53<05:43,  4.50it/s]
 31%|███       | 702/2248 [01:54<08:40,  2.97it/s]
 31%|███▏      | 703/2248 [01:54<07:20,  3.51it/s]
 31%|███▏      | 704/2248 [01:55<09:48,  2.62it/s]
 31%|███▏      | 705/2248 [01:55<08:21,  3.08it/s]
 31%|███▏      | 706/2248 [01:55<07:18,  3.52it/s]
 31%|███▏      | 708/2248 [01:55<04:40,  5.48it/s]
 32%|███▏      | 709/2248 [01:56<04:51,  5.28it/s]
 32%|███▏      | 711/2248 [01:56<04:10,  6.13it/s]
 32%|███▏      | 712/2248 [01:56<04:33,  5.62it/s]
 32%|███▏      | 713/2248 [01:56<04:40,  5.48it/s]
 32%|███▏      | 714/2248 [01:56<04:29,  5.70it/s]
 32%|███▏      | 715/2248 [01:57<04:35,  5.56it/s]
 32%|███▏      | 716/2248 [01:57<04:59,  5.11it/s]
 32%|███▏      | 717/2248 [01:57<04:22,  5.82it/s]
 32%|███▏      | 719/2248 [01:57<04:04,  6.25it/s]
 32%|███▏      | 720/2248 [01:57<04:19,  5.89it/s]
 32%|███▏      | 721/2248 [01:58<07:56,  3.21it/s]
 32%|███▏      | 723/2248 [01:58<05:58,  4.25it/s]
 32%|███▏      | 724/2248 [01:59<08:45,  2.90it/s]
 32%|███▏      | 726/2248 [01:59<06:14,  4.07it/s]
 32%|███▏      | 727/2248 [02:00<06:04,  4.18it/s]
 32%|███▏      | 728/2248 [02:00<06:12,  4.08it/s]
 33%|███▎      | 731/2248 [02:00<04:15,  5.93it/s]
 33%|███▎      | 732/2248 [02:00<04:27,  5.67it/s]
 33%|███▎      | 733/2248 [02:01<04:38,  5.45it/s]
 33%|███▎      | 734/2248 [02:01<04:45,  5.30it/s]
 33%|███▎      | 735/2248 [02:01<04:46,  5.28it/s]
 33%|███▎      | 736/2248 [02:01<06:01,  4.18it/s]
 33%|███▎      | 737/2248 [02:02<06:33,  3.84it/s]
 33%|███▎      | 738/2248 [02:02<07:41,  3.27it/s]
 33%|███▎      | 740/2248 [02:02<04:59,  5.04it/s]
 33%|███▎      | 742/2248 [02:02<04:23,  5.72it/s]
 33%|███▎      | 743/2248 [02:03<05:18,  4.72it/s]
 33%|███▎      | 744/2248 [02:03<06:44,  3.72it/s]
 33%|███▎      | 746/2248 [02:04<05:48,  4.31it/s]
 33%|███▎      | 749/2248 [02:04<04:52,  5.13it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 327.46it/s]

[[np.int64(0), False, 2], [np.int64(1), False, 7], [np.int64(2), False, 5], [np.int64(3), False, 6], [np.int64(4), False, 9], [np.int64(8), False, 11], [np.int64(10), False, 0], [np.int64(11), False, 7], [np.int64(12), False, 0], [np.int64(13), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.3477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4298, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [10:39<4:35:40, 111.01s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [10:39<3:11:48, 77.76s/it]

tensor(12.3471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8058, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9511, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [10:39<1:04:38, 26.75s/it]

tensor(12.3566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0069, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1668, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [10:39<31:22, 13.17s/it]

tensor(12.3548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0409, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3163, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3535, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0439, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3739, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [10:40<15:17,  6.51s/it]

tensor(12.3533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0461, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3907, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3532, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0478, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3912, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [10:40<07:31,  3.25s/it]

tensor(12.3508, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0481, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3808, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0482, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4071, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [10:40<03:46,  1.65s/it]

tensor(12.3402, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0468, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4260, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3364, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0454, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4601, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [10:40<01:57,  1.15it/s]

tensor(12.3338, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0443, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4773, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4808, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [10:41<01:04,  2.06it/s]

tensor(12.3262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0405, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4629, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4639, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [10:41<00:38,  3.38it/s]

tensor(12.3187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4819, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4996, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [10:41<00:26,  4.88it/s]

tensor(12.3115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5118, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5277, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [10:41<00:20,  6.28it/s]

tensor(12.3055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5480, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5564, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [10:41<00:17,  7.25it/s]

tensor(12.2971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5674, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5742, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [10:42<00:15,  7.87it/s]

tensor(12.2884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5838, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5860, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [10:42<00:14,  8.13it/s]

tensor(12.2814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5953, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [10:42<00:14,  8.40it/s]

tensor(12.2754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5999, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2723, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6062, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [10:42<00:13,  8.48it/s]

tensor(12.2694, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6072, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6129, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [10:43<00:13,  8.59it/s]

tensor(12.2634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6236, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2606, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6255, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [10:43<00:13,  8.54it/s]

tensor(12.2575, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6355, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6451, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [10:43<00:12,  8.61it/s]

tensor(12.2515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6490, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6582, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [10:43<00:12,  8.62it/s]

tensor(12.2456, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6630, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6672, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [10:44<00:12,  8.62it/s]

tensor(12.2401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6719, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6760, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [10:44<00:12,  8.58it/s]

tensor(12.2349, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6756, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6775, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [10:44<00:11,  8.60it/s]

tensor(12.2299, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6759, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6793, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [10:44<00:11,  8.66it/s]

tensor(12.2251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6805, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6843, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [10:44<00:11,  8.61it/s]

tensor(12.2204, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6843, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([140, 142, 124,  82, 170, 133, 239, 273,  54, 206,  58, 112, 416,  99])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:21, 15.85it/s]
  0%|          | 7/2248 [00:00<01:09, 32.14it/s]
  1%|          | 13/2248 [00:00<00:52, 42.64it/s]
  1%|          | 19/2248 [00:00<00:47, 46.90it/s]
  1%|          | 25/2248 [00:00<00:45, 49.25it/s]
  1%|▏         | 31/2248 [00:00<00:42, 51.78it/s]
  2%|▏         | 37/2248 [00:00<00:44, 49.93it/s]
  2%|▏         | 44/2248 [00:00<00:42, 52.47it/s]
  2%|▏         | 50/2248 [00:01<00:42, 52.23it/s]
  2%|▏         | 56/2248 [00:01<00:40, 53.50it/s]
  3%|▎         | 63/2248 [00:01<00:38, 56.71it/s]
  3%|▎         | 70/2248 [00:01<00:38, 57.23it/s]
  3%|▎         | 76/2248 [00:02<01:49, 19.86it/s]
  4%|▎         | 81/2248 [00:02<02:18, 15.69it/s]
  4%|▍         | 86/2248 [00:03<03:11, 11.26it/s]
  4%|▍         | 89/2248 [00:03<02:55, 12.28it/s]
  4%|▍         | 92/2248 [00:04<03:19, 10.82it/s]
  4%|▍         | 95/2248 [00:04<03:30, 10.20it/s]
  4%|▍         | 97/2248 [00:04<03:17, 10.90it/s]
  4%|▍         | 100/2248 [00:04<03:30, 10.21it/s]
  5%|▍         | 102/2248 [00:04<03:13, 11.11it/s]
  5%|▍         | 104/2248 [00:05<05:14,  6.83it/s]
  5%|▍         | 106/2248 [00:05<04:32,  7.86it/s]
  5%|▍         | 108/2248 [00:05<03:55,  9.08it/s]
  5%|▍         | 111/2248 [00:06<03:14, 10.96it/s]
  5%|▌         | 113/2248 [00:06<03:02, 11.67it/s]
  5%|▌         | 116/2248 [00:06<02:56, 12.11it/s]
  5%|▌         | 118/2248 [00:06<04:17,  8.26it/s]
  5%|▌         | 120/2248 [00:07<04:22,  8.10it/s]
  5%|▌         | 122/2248 [00:07<03:48,  9.30it/s]
  6%|▌         | 124/2248 [00:07<03:18, 10.70it/s]
  6%|▌         | 126/2248 [00:08<05:47,  6.11it/s]
  6%|▌         | 128/2248 [00:09<10:50,  3.26it/s]
  6%|▌         | 130/2248 [00:09<08:16,  4.27it/s]
  6%|▌         | 132/2248 [00:09<06:22,  5.54it/s]
  6%|▌         | 134/2248 [00:10<07:17,  4.83it/s]
  6%|▌         | 136/2248 [00:10<08:26,  4.17it/s]
  6%|▌         | 138/2248 [00:11<07:13,  4.87it/s]
  6%|▌         | 140/2248 [00:11<05:55,  5.93it/s]
  6%|▋         | 144/2248 [00:11<03:36,  9.70it/s]
  6%|▋         | 146/2248 [00:11<04:15,  8.22it/s]
  7%|▋         | 148/2248 [00:11<03:46,  9.25it/s]
  7%|▋         | 151/2248 [00:12<03:47,  9.21it/s]
  7%|▋         | 153/2248 [00:12<03:20, 10.47it/s]
  7%|▋         | 156/2248 [00:12<04:22,  7.98it/s]
  7%|▋         | 158/2248 [00:14<08:58,  3.88it/s]
  7%|▋         | 159/2248 [00:14<11:22,  3.06it/s]
  7%|▋         | 160/2248 [00:15<12:41,  2.74it/s]
  7%|▋         | 162/2248 [00:15<10:39,  3.26it/s]
  7%|▋         | 164/2248 [00:15<07:48,  4.45it/s]
  7%|▋         | 165/2248 [00:16<08:29,  4.09it/s]
  7%|▋         | 166/2248 [00:16<08:45,  3.96it/s]
  7%|▋         | 168/2248 [00:16<06:18,  5.49it/s]
  8%|▊         | 169/2248 [00:16<06:23,  5.42it/s]
  8%|▊         | 171/2248 [00:16<04:50,  7.15it/s]
  8%|▊         | 173/2248 [00:17<07:39,  4.52it/s]
  8%|▊         | 176/2248 [00:18<07:57,  4.33it/s]
  8%|▊         | 178/2248 [00:19<09:13,  3.74it/s]
  8%|▊         | 180/2248 [00:19<08:26,  4.09it/s]
  8%|▊         | 183/2248 [00:19<06:48,  5.06it/s]
  8%|▊         | 185/2248 [00:20<06:37,  5.19it/s]
  8%|▊         | 187/2248 [00:20<08:20,  4.12it/s]
  8%|▊         | 189/2248 [00:21<07:47,  4.40it/s]
  8%|▊         | 190/2248 [00:21<08:08,  4.21it/s]
  9%|▊         | 192/2248 [00:21<06:14,  5.50it/s]
  9%|▊         | 193/2248 [00:22<06:51,  4.99it/s]
  9%|▊         | 194/2248 [00:22<07:20,  4.66it/s]
  9%|▊         | 195/2248 [00:22<07:35,  4.51it/s]
  9%|▉         | 197/2248 [00:22<05:18,  6.44it/s]
  9%|▉         | 199/2248 [00:22<04:07,  8.29it/s]
  9%|▉         | 201/2248 [00:23<05:09,  6.62it/s]
  9%|▉         | 202/2248 [00:23<06:35,  5.17it/s]
  9%|▉         | 204/2248 [00:23<04:59,  6.82it/s]
  9%|▉         | 205/2248 [00:23<06:02,  5.63it/s]
  9%|▉         | 206/2248 [00:24<06:37,  5.14it/s]
  9%|▉         | 207/2248 [00:24<06:35,  5.16it/s]
  9%|▉         | 208/2248 [00:24<06:06,  5.56it/s]
  9%|▉         | 209/2248 [00:25<10:34,  3.21it/s]
  9%|▉         | 210/2248 [00:26<14:46,  2.30it/s]
  9%|▉         | 211/2248 [00:26<17:37,  1.93it/s]
  9%|▉         | 212/2248 [00:27<19:38,  1.73it/s]
 10%|▉         | 214/2248 [00:27<11:36,  2.92it/s]
 10%|▉         | 219/2248 [00:27<04:52,  6.93it/s]
 10%|█         | 225/2248 [00:27<02:41, 12.53it/s]
 10%|█         | 230/2248 [00:27<01:58, 17.07it/s]
 10%|█         | 234/2248 [00:28<01:38, 20.39it/s]
 11%|█         | 238/2248 [00:28<01:29, 22.38it/s]
 11%|█         | 242/2248 [00:28<01:24, 23.64it/s]
 11%|█         | 246/2248 [00:28<01:15, 26.36it/s]
 11%|█         | 251/2248 [00:28<01:06, 30.20it/s]
 11%|█▏        | 256/2248 [00:28<01:02, 31.95it/s]
 12%|█▏        | 260/2248 [00:28<00:59, 33.52it/s]
 12%|█▏        | 264/2248 [00:29<02:35, 12.78it/s]
 12%|█▏        | 267/2248 [00:30<03:45,  8.78it/s]
 12%|█▏        | 270/2248 [00:30<04:21,  7.55it/s]
 12%|█▏        | 272/2248 [00:30<03:53,  8.47it/s]
 12%|█▏        | 274/2248 [00:31<04:20,  7.58it/s]
 12%|█▏        | 276/2248 [00:31<05:46,  5.68it/s]
 12%|█▏        | 278/2248 [00:32<05:22,  6.10it/s]
 12%|█▏        | 280/2248 [00:32<05:15,  6.23it/s]
 13%|█▎        | 282/2248 [00:32<04:30,  7.26it/s]
 13%|█▎        | 284/2248 [00:32<04:32,  7.22it/s]
 13%|█▎        | 286/2248 [00:33<05:27,  6.00it/s]
 13%|█▎        | 287/2248 [00:33<05:24,  6.05it/s]
 13%|█▎        | 289/2248 [00:33<04:20,  7.53it/s]
 13%|█▎        | 290/2248 [00:33<04:43,  6.91it/s]
 13%|█▎        | 292/2248 [00:34<03:59,  8.16it/s]
 13%|█▎        | 294/2248 [00:34<03:23,  9.58it/s]
 13%|█▎        | 296/2248 [00:34<02:54, 11.19it/s]
 13%|█▎        | 298/2248 [00:34<03:23,  9.56it/s]
 13%|█▎        | 300/2248 [00:35<04:30,  7.21it/s]
 13%|█▎        | 302/2248 [00:35<05:00,  6.48it/s]
 13%|█▎        | 303/2248 [00:36<07:53,  4.11it/s]
 14%|█▎        | 304/2248 [00:36<10:17,  3.15it/s]
 14%|█▎        | 305/2248 [00:36<09:08,  3.54it/s]
 14%|█▎        | 306/2248 [00:37<09:33,  3.39it/s]
 14%|█▎        | 307/2248 [00:37<10:25,  3.10it/s]
 14%|█▎        | 308/2248 [00:37<10:24,  3.11it/s]
 14%|█▎        | 309/2248 [00:38<10:22,  3.11it/s]
 14%|█▍        | 312/2248 [00:38<06:22,  5.06it/s]
 14%|█▍        | 313/2248 [00:38<07:03,  4.57it/s]
 14%|█▍        | 314/2248 [00:39<08:02,  4.01it/s]
 14%|█▍        | 315/2248 [00:39<08:45,  3.68it/s]
 14%|█▍        | 317/2248 [00:39<05:49,  5.52it/s]
 14%|█▍        | 320/2248 [00:40<05:38,  5.70it/s]
 14%|█▍        | 322/2248 [00:40<05:26,  5.89it/s]
 14%|█▍        | 323/2248 [00:40<06:19,  5.08it/s]
 14%|█▍        | 325/2248 [00:40<05:25,  5.91it/s]
 15%|█▍        | 326/2248 [00:41<05:03,  6.33it/s]
 15%|█▍        | 327/2248 [00:41<05:16,  6.07it/s]
 15%|█▍        | 328/2248 [00:41<04:50,  6.60it/s]
 15%|█▍        | 331/2248 [00:41<03:15,  9.82it/s]
 15%|█▍        | 333/2248 [00:42<05:23,  5.93it/s]
 15%|█▍        | 335/2248 [00:42<04:14,  7.53it/s]
 15%|█▍        | 337/2248 [00:42<03:35,  8.89it/s]
 15%|█▌        | 339/2248 [00:43<05:54,  5.38it/s]
 15%|█▌        | 340/2248 [00:43<06:40,  4.77it/s]
 15%|█▌        | 343/2248 [00:44<07:22,  4.31it/s]
 15%|█▌        | 344/2248 [00:44<10:02,  3.16it/s]
 15%|█▌        | 345/2248 [00:45<12:28,  2.54it/s]
 15%|█▌        | 346/2248 [00:45<11:20,  2.79it/s]
 15%|█▌        | 347/2248 [00:46<12:15,  2.59it/s]
 15%|█▌        | 348/2248 [00:47<15:12,  2.08it/s]
 16%|█▌        | 349/2248 [00:47<13:53,  2.28it/s]
 16%|█▌        | 350/2248 [00:47<14:00,  2.26it/s]
 16%|█▌        | 352/2248 [00:47<08:34,  3.69it/s]
 16%|█▌        | 353/2248 [00:48<07:53,  4.00it/s]
 16%|█▌        | 354/2248 [00:48<07:05,  4.45it/s]
 16%|█▌        | 355/2248 [00:48<07:00,  4.50it/s]
 16%|█▌        | 356/2248 [00:48<08:37,  3.66it/s]
 16%|█▌        | 358/2248 [00:49<05:39,  5.57it/s]
 16%|█▌        | 362/2248 [00:49<03:26,  9.12it/s]
 16%|█▌        | 364/2248 [00:49<05:10,  6.07it/s]
 16%|█▋        | 366/2248 [00:50<04:46,  6.58it/s]
 16%|█▋        | 367/2248 [00:50<04:38,  6.76it/s]
 16%|█▋        | 370/2248 [00:50<03:16,  9.55it/s]
 17%|█▋        | 372/2248 [00:51<05:36,  5.57it/s]
 17%|█▋        | 373/2248 [00:51<06:19,  4.95it/s]
 17%|█▋        | 374/2248 [00:51<05:49,  5.36it/s]
 17%|█▋        | 377/2248 [00:52<06:48,  4.59it/s]
 17%|█▋        | 379/2248 [00:53<08:33,  3.64it/s]
 17%|█▋        | 381/2248 [00:53<06:29,  4.79it/s]
 17%|█▋        | 384/2248 [00:53<06:45,  4.59it/s]
 17%|█▋        | 385/2248 [00:54<07:06,  4.37it/s]
 17%|█▋        | 387/2248 [00:54<05:23,  5.76it/s]
 17%|█▋        | 389/2248 [00:55<08:32,  3.63it/s]
 17%|█▋        | 390/2248 [00:55<08:33,  3.62it/s]
 17%|█▋        | 391/2248 [00:55<08:55,  3.47it/s]
 17%|█▋        | 392/2248 [00:56<11:47,  2.62it/s]
 17%|█▋        | 393/2248 [00:57<13:58,  2.21it/s]
 18%|█▊        | 394/2248 [00:58<16:03,  1.92it/s]
 18%|█▊        | 396/2248 [00:58<09:56,  3.10it/s]
 18%|█▊        | 402/2248 [00:58<03:55,  7.85it/s]
 18%|█▊        | 407/2248 [00:58<02:28, 12.36it/s]
 18%|█▊        | 410/2248 [00:58<02:05, 14.60it/s]
 18%|█▊        | 413/2248 [00:58<01:51, 16.46it/s]
 19%|█▊        | 418/2248 [00:58<01:24, 21.63it/s]
 19%|█▉        | 423/2248 [00:58<01:08, 26.56it/s]
 19%|█▉        | 429/2248 [00:58<00:55, 32.78it/s]
 19%|█▉        | 434/2248 [00:59<00:49, 36.52it/s]
 20%|█▉        | 439/2248 [01:00<04:06,  7.35it/s]
 20%|█▉        | 443/2248 [01:01<04:23,  6.86it/s]
 20%|█▉        | 446/2248 [01:02<04:31,  6.65it/s]
 20%|█▉        | 448/2248 [01:02<05:23,  5.57it/s]
 20%|██        | 450/2248 [01:03<06:32,  4.58it/s]
 20%|██        | 452/2248 [01:03<05:31,  5.42it/s]
 20%|██        | 454/2248 [01:04<05:35,  5.34it/s]
 20%|██        | 455/2248 [01:04<07:21,  4.07it/s]
 20%|██        | 457/2248 [01:04<06:42,  4.45it/s]
 20%|██        | 459/2248 [01:05<05:26,  5.47it/s]
 20%|██        | 460/2248 [01:05<05:34,  5.34it/s]
 21%|██        | 461/2248 [01:05<05:06,  5.83it/s]
 21%|██        | 463/2248 [01:05<04:17,  6.92it/s]
 21%|██        | 465/2248 [01:05<03:20,  8.91it/s]
 21%|██        | 467/2248 [01:05<02:51, 10.41it/s]
 21%|██        | 470/2248 [01:06<02:14, 13.25it/s]
 21%|██        | 472/2248 [01:06<04:35,  6.44it/s]
 21%|██        | 474/2248 [01:06<04:03,  7.27it/s]
 21%|██        | 476/2248 [01:07<05:51,  5.05it/s]
 21%|██        | 477/2248 [01:07<06:28,  4.56it/s]
 21%|██▏       | 478/2248 [01:08<06:24,  4.60it/s]
 21%|██▏       | 479/2248 [01:08<08:16,  3.56it/s]
 21%|██▏       | 480/2248 [01:09<08:56,  3.30it/s]
 21%|██▏       | 481/2248 [01:09<09:37,  3.06it/s]
 21%|██▏       | 483/2248 [01:09<06:16,  4.69it/s]
 22%|██▏       | 486/2248 [01:09<03:45,  7.82it/s]
 22%|██▏       | 488/2248 [01:09<04:05,  7.17it/s]
 22%|██▏       | 490/2248 [01:10<03:24,  8.59it/s]
 22%|██▏       | 495/2248 [01:10<04:01,  7.26it/s]
 22%|██▏       | 498/2248 [01:10<03:07,  9.31it/s]
 22%|██▏       | 500/2248 [01:11<03:29,  8.36it/s]
 22%|██▏       | 503/2248 [01:11<03:26,  8.47it/s]
 22%|██▏       | 505/2248 [01:11<02:58,  9.78it/s]
 23%|██▎       | 507/2248 [01:11<02:39, 10.91it/s]
 23%|██▎       | 509/2248 [01:12<04:41,  6.17it/s]
 23%|██▎       | 511/2248 [01:12<03:51,  7.51it/s]
 23%|██▎       | 513/2248 [01:14<08:25,  3.43it/s]
 23%|██▎       | 514/2248 [01:14<09:31,  3.03it/s]
 23%|██▎       | 515/2248 [01:15<10:18,  2.80it/s]
 23%|██▎       | 517/2248 [01:15<07:17,  3.96it/s]
 23%|██▎       | 518/2248 [01:15<07:46,  3.71it/s]
 23%|██▎       | 520/2248 [01:15<05:46,  4.98it/s]
 23%|██▎       | 524/2248 [01:15<03:14,  8.87it/s]
 24%|██▎       | 529/2248 [01:15<01:59, 14.33it/s]
 24%|██▎       | 532/2248 [01:16<01:44, 16.44it/s]
 24%|██▍       | 535/2248 [01:16<01:33, 18.25it/s]
 24%|██▍       | 539/2248 [01:16<01:16, 22.23it/s]
 24%|██▍       | 545/2248 [01:16<01:00, 27.96it/s]
 24%|██▍       | 549/2248 [01:16<00:57, 29.79it/s]
 25%|██▍       | 553/2248 [01:16<00:55, 30.42it/s]
 25%|██▍       | 558/2248 [01:16<00:50, 33.60it/s]
 25%|██▌       | 564/2248 [01:16<00:42, 39.70it/s]
 25%|██▌       | 571/2248 [01:17<00:54, 30.93it/s]
 26%|██▌       | 575/2248 [01:18<02:51,  9.77it/s]
 26%|██▌       | 578/2248 [01:18<02:36, 10.64it/s]
 26%|██▌       | 581/2248 [01:19<03:13,  8.62it/s]
 26%|██▌       | 583/2248 [01:19<03:17,  8.43it/s]
 26%|██▌       | 585/2248 [01:19<03:10,  8.75it/s]
 26%|██▌       | 587/2248 [01:19<03:16,  8.44it/s]
 26%|██▌       | 589/2248 [01:20<04:07,  6.72it/s]
 26%|██▋       | 592/2248 [01:20<04:02,  6.83it/s]
 26%|██▋       | 594/2248 [01:21<03:33,  7.75it/s]
 27%|██▋       | 600/2248 [01:21<02:18, 11.91it/s]
 27%|██▋       | 603/2248 [01:21<02:48,  9.77it/s]
 27%|██▋       | 605/2248 [01:22<03:31,  7.76it/s]
 27%|██▋       | 606/2248 [01:22<04:54,  5.57it/s]
 27%|██▋       | 607/2248 [01:23<07:01,  3.90it/s]
 27%|██▋       | 608/2248 [01:24<09:17,  2.94it/s]
 27%|██▋       | 609/2248 [01:24<11:12,  2.44it/s]
 27%|██▋       | 611/2248 [01:24<07:36,  3.59it/s]
 27%|██▋       | 613/2248 [01:25<05:34,  4.89it/s]
 27%|██▋       | 616/2248 [01:25<03:36,  7.53it/s]
 28%|██▊       | 622/2248 [01:25<01:55, 14.14it/s]
 28%|██▊       | 628/2248 [01:25<01:18, 20.72it/s]
 28%|██▊       | 634/2248 [01:25<00:58, 27.46it/s]
 28%|██▊       | 640/2248 [01:25<00:48, 33.04it/s]
 29%|██▊       | 645/2248 [01:25<00:44, 35.87it/s]
 29%|██▉       | 650/2248 [01:26<01:04, 24.76it/s]
 29%|██▉       | 654/2248 [01:27<03:44,  7.10it/s]
 29%|██▉       | 657/2248 [01:27<03:07,  8.48it/s]
 29%|██▉       | 660/2248 [01:29<05:24,  4.90it/s]
 29%|██▉       | 662/2248 [01:30<06:07,  4.32it/s]
 30%|██▉       | 664/2248 [01:30<07:03,  3.74it/s]
 30%|██▉       | 666/2248 [01:31<07:32,  3.50it/s]
 30%|██▉       | 669/2248 [01:31<05:20,  4.92it/s]
 30%|██▉       | 671/2248 [01:32<06:22,  4.12it/s]
 30%|███       | 675/2248 [01:32<04:03,  6.46it/s]
 30%|███       | 677/2248 [01:33<05:15,  4.98it/s]
 30%|███       | 680/2248 [01:33<03:50,  6.81it/s]
 30%|███       | 682/2248 [01:34<05:04,  5.14it/s]
 30%|███       | 684/2248 [01:35<07:06,  3.67it/s]
 31%|███       | 686/2248 [01:36<09:44,  2.67it/s]
 31%|███       | 688/2248 [01:36<08:28,  3.07it/s]
 31%|███       | 690/2248 [01:36<06:27,  4.02it/s]
 31%|███       | 692/2248 [01:37<06:03,  4.28it/s]
 31%|███       | 694/2248 [01:37<05:15,  4.93it/s]
 31%|███       | 695/2248 [01:37<05:47,  4.46it/s]
 31%|███       | 697/2248 [01:37<04:19,  5.98it/s]
 31%|███       | 699/2248 [01:38<04:09,  6.20it/s]
 31%|███       | 701/2248 [01:38<03:16,  7.89it/s]
 31%|███▏      | 703/2248 [01:38<03:30,  7.34it/s]
 31%|███▏      | 705/2248 [01:39<03:41,  6.98it/s]
 31%|███▏      | 707/2248 [01:39<03:00,  8.53it/s]
 32%|███▏      | 709/2248 [01:39<02:32, 10.08it/s]
 32%|███▏      | 711/2248 [01:39<02:57,  8.68it/s]
 32%|███▏      | 713/2248 [01:40<03:47,  6.75it/s]
 32%|███▏      | 715/2248 [01:40<04:23,  5.83it/s]
 32%|███▏      | 716/2248 [01:40<04:04,  6.27it/s]
 32%|███▏      | 718/2248 [01:40<03:26,  7.42it/s]
 32%|███▏      | 719/2248 [01:40<03:43,  6.86it/s]
 32%|███▏      | 720/2248 [01:41<03:38,  6.98it/s]
 32%|███▏      | 721/2248 [01:41<03:41,  6.89it/s]
 32%|███▏      | 723/2248 [01:41<03:32,  7.19it/s]
 32%|███▏      | 725/2248 [01:41<03:56,  6.44it/s]
 32%|███▏      | 726/2248 [01:41<03:43,  6.80it/s]
 32%|███▏      | 727/2248 [01:42<04:07,  6.16it/s]
 32%|███▏      | 728/2248 [01:42<04:14,  5.97it/s]
 32%|███▏      | 730/2248 [01:42<03:19,  7.63it/s]
 33%|███▎      | 731/2248 [01:42<03:14,  7.80it/s]
 33%|███▎      | 732/2248 [01:42<03:32,  7.15it/s]
 33%|███▎      | 733/2248 [01:43<05:00,  5.05it/s]
 33%|███▎      | 734/2248 [01:43<05:24,  4.66it/s]
 33%|███▎      | 735/2248 [01:43<06:17,  4.01it/s]
 33%|███▎      | 736/2248 [01:44<06:14,  4.04it/s]
 33%|███▎      | 737/2248 [01:44<06:03,  4.15it/s]
 33%|███▎      | 738/2248 [01:44<06:49,  3.69it/s]
 33%|███▎      | 742/2248 [01:45<04:29,  5.59it/s]
 33%|███▎      | 743/2248 [01:45<05:09,  4.87it/s]
 33%|███▎      | 744/2248 [01:45<05:06,  4.90it/s]
 33%|███▎      | 746/2248 [01:45<03:54,  6.40it/s]
 33%|███▎      | 749/2248 [01:46<03:39,  6.82it/s]
 33%|███▎      | 751/2248 [01:46<04:02,  6.18it/s]
 33%|███▎      | 752/2248 [01:46<04:28,  5.58it/s]
 34%|███▎      | 754/2248 [01:47<04:27,  5.59it/s]
 34%|███▎      | 755/2248 [01:47<04:05,  6.08it/s]
 34%|███▎      | 757/2248 [01:47<03:08,  7.91it/s]
 34%|███▍      | 761/2248 [01:47<02:20, 10.62it/s]
 34%|███▍      | 763/2248 [01:47<02:10, 11.35it/s]
 34%|███▍      | 767/2248 [01:48<03:06,  7.96it/s]
 34%|███▍      | 770/2248 [01:48<02:27, 10.03it/s]
 34%|███▍      | 772/2248 [01:49<03:48,  6.45it/s]
 34%|███▍      | 774/2248 [01:50<07:03,  3.48it/s]
 34%|███▍      | 775/2248 [01:51<08:02,  3.05it/s]
 35%|███▍      | 776/2248 [01:51<09:31,  2.58it/s]
 35%|███▍      | 778/2248 [01:52<09:09,  2.68it/s]
 35%|███▍      | 780/2248 [01:52<06:38,  3.68it/s]
 35%|███▍      | 782/2248 [01:53<07:29,  3.26it/s]
 35%|███▍      | 783/2248 [01:54<09:23,  2.60it/s]
 35%|███▍      | 784/2248 [01:54<10:56,  2.23it/s]
 35%|███▌      | 787/2248 [01:55<06:17,  3.87it/s]
 35%|███▌      | 791/2248 [01:55<05:24,  4.49it/s]
 35%|███▌      | 792/2248 [01:56<07:07,  3.41it/s]
 35%|███▌      | 794/2248 [01:56<05:27,  4.44it/s]
 35%|███▌      | 797/2248 [01:57<05:42,  4.24it/s]
 36%|███▌      | 799/2248 [01:57<04:35,  5.25it/s]
 36%|███▌      | 800/2248 [01:57<04:32,  5.32it/s]
 36%|███▌      | 803/2248 [01:57<03:13,  7.48it/s]
 36%|███▌      | 806/2248 [01:58<03:06,  7.73it/s]
 36%|███▌      | 808/2248 [01:58<02:39,  9.03it/s]
 36%|███▌      | 810/2248 [01:58<02:51,  8.38it/s]
 36%|███▌      | 812/2248 [01:59<03:55,  6.11it/s]
 36%|███▌      | 814/2248 [01:59<03:16,  7.31it/s]
 36%|███▋      | 816/2248 [01:59<03:33,  6.71it/s]
 36%|███▋      | 820/2248 [01:59<02:15, 10.53it/s]
 37%|███▋      | 825/2248 [01:59<01:27, 16.18it/s]
 37%|███▋      | 830/2248 [01:59<01:04, 21.97it/s]
 37%|███▋      | 835/2248 [02:00<00:53, 26.20it/s]
 37%|███▋      | 839/2248 [02:00<00:52, 26.99it/s]
 38%|███▊      | 844/2248 [02:00<00:44, 31.76it/s]
 38%|███▊      | 850/2248 [02:00<00:36, 38.42it/s]
 38%|███▊      | 855/2248 [02:00<00:34, 39.91it/s]
 38%|███▊      | 862/2248 [02:00<00:29, 47.14it/s]
 39%|███▊      | 868/2248 [02:02<02:07, 10.81it/s]
 39%|███▉      | 872/2248 [02:03<03:08,  7.29it/s]
 39%|███▉      | 875/2248 [02:03<03:32,  6.45it/s]
 39%|███▉      | 878/2248 [02:04<03:44,  6.11it/s]
 39%|███▉      | 881/2248 [02:05<04:16,  5.32it/s]
 39%|███▉      | 883/2248 [02:05<03:43,  6.10it/s]
 39%|███▉      | 885/2248 [02:05<03:46,  6.02it/s]
 39%|███▉      | 887/2248 [02:06<05:09,  4.39it/s]
 40%|███▉      | 888/2248 [02:06<05:28,  4.14it/s]
 40%|███▉      | 890/2248 [02:07<05:08,  4.40it/s]
 40%|███▉      | 891/2248 [02:07<06:41,  3.38it/s]
 40%|███▉      | 893/2248 [02:08<04:56,  4.57it/s]
 40%|███▉      | 894/2248 [02:08<07:02,  3.21it/s]
 40%|███▉      | 896/2248 [02:08<05:05,  4.43it/s]
 40%|████      | 902/2248 [02:09<03:45,  5.97it/s]
 40%|████      | 903/2248 [02:10<04:11,  5.35it/s]
 40%|████      | 906/2248 [02:10<04:43,  4.73it/s]
 40%|████      | 907/2248 [02:11<06:21,  3.51it/s]
 40%|████      | 908/2248 [02:12<07:53,  2.83it/s]
 40%|████      | 909/2248 [02:12<07:43,  2.89it/s]
 40%|████      | 910/2248 [02:13<09:15,  2.41it/s]
 41%|████      | 911/2248 [02:13<10:34,  2.11it/s]
 41%|████      | 912/2248 [02:14<11:32,  1.93it/s]
 41%|████      | 913/2248 [02:15<12:43,  1.75it/s]
 41%|████      | 915/2248 [02:15<07:48,  2.85it/s]
 41%|████      | 916/2248 [02:15<07:40,  2.89it/s]
 41%|████      | 917/2248 [02:16<09:44,  2.28it/s]
 41%|████      | 919/2248 [02:16<07:29,  2.95it/s]
 41%|████      | 920/2248 [02:17<09:10,  2.41it/s]
 41%|████      | 922/2248 [02:17<05:58,  3.69it/s]
 41%|████      | 923/2248 [02:17<06:11,  3.57it/s]
 41%|████      | 924/2248 [02:18<07:18,  3.02it/s]
 41%|████      | 926/2248 [02:18<05:00,  4.40it/s]
 41%|████      | 927/2248 [02:18<05:18,  4.14it/s]
 41%|████▏     | 929/2248 [02:19<05:31,  3.98it/s]
 41%|████▏     | 931/2248 [02:19<04:37,  4.74it/s]
 42%|████▏     | 933/2248 [02:19<03:29,  6.27it/s]
 42%|████▏     | 934/2248 [02:20<05:19,  4.12it/s]
 42%|████▏     | 936/2248 [02:20<03:49,  5.71it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 309.35it/s]

[[np.int64(0), False, 9], [np.int64(1), False, 12], [np.int64(2), False, 6], [np.int64(3), False, 1], [np.int64(4), False, 12], [np.int64(5), False, 10], [np.int64(6), False, 9], [np.int64(7), False, 12], [np.int64(8), False, 10], [np.int64(11), False, 2], [np.int64(13), False, 12]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1421, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [16:25<2:48:47, 102.30s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [16:25<1:57:01, 71.65s/it]

tensor(12.2172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1958, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2608, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [16:26<39:02, 24.65s/it]

tensor(12.2230, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3105, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0353, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3308, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [16:26<18:48, 12.14s/it]

tensor(12.2269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0376, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3454, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2232, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3571, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [16:26<09:06,  6.01s/it]

tensor(12.2167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0376, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3669, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3743, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [16:26<04:27,  3.00s/it]

tensor(12.2057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0365, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3837, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0366, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3867, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [16:27<02:13,  1.53s/it]

tensor(12.2075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3986, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0361, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4058, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [16:27<01:08,  1.24it/s]

tensor(12.2103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3976, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1210, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [16:27<00:37,  2.19it/s]

tensor(12.2027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0332, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2190, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1993, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3470, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [16:27<00:22,  3.53it/s]

tensor(12.1991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3854, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3976, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [16:27<00:15,  5.05it/s]

tensor(12.2031, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3967, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3978, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [16:28<00:12,  6.37it/s]

tensor(12.2029, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4013, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1999, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4064, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [16:28<00:10,  7.34it/s]

tensor(12.1959, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4113, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4084, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [16:28<00:09,  7.96it/s]

tensor(12.1895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4189, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1875, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4234, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [16:28<00:08,  8.27it/s]

tensor(12.1866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4280, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4334, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [16:29<00:08,  8.48it/s]

tensor(12.1851, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4462, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [16:29<00:07,  8.48it/s]

tensor(12.1825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4453, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1805, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4469, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [16:29<00:07,  8.59it/s]

tensor(12.1780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4567, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4556, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [16:29<00:07,  8.61it/s]

tensor(12.1731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4586, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1707, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4634, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [16:30<00:07,  8.60it/s]

tensor(12.1687, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4645, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1669, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3547, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [16:30<00:06,  8.63it/s]

tensor(12.1657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2786, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2945, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [16:30<00:06,  8.57it/s]

tensor(12.1656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2786, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3152, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [16:30<00:06,  8.56it/s]

tensor(12.1685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3500, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3534, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [16:30<00:06,  8.57it/s]

tensor(12.1715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0331, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3730, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0347, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4037, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [16:31<00:05,  8.52it/s]

tensor(12.1732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0360, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4282, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0371, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4379, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [16:31<00:05,  8.58it/s]

tensor(12.1719, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0378, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4517, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 82, 395, 158, 118, 159,  75, 167, 199, 211,  84, 120, 305, 104,  71])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 4/2248 [00:00<01:10, 31.72it/s]
  0%|          | 9/2248 [00:00<01:00, 37.30it/s]
  1%|          | 16/2248 [00:00<00:46, 48.48it/s]
  1%|          | 23/2248 [00:00<00:41, 53.85it/s]
  1%|▏         | 29/2248 [00:00<00:51, 43.28it/s]
  2%|▏         | 35/2248 [00:00<00:47, 46.82it/s]
  2%|▏         | 40/2248 [00:00<00:49, 44.61it/s]
  2%|▏         | 45/2248 [00:00<00:48, 45.19it/s]
  2%|▏         | 50/2248 [00:01<00:50, 43.76it/s]
  2%|▏         | 55/2248 [00:01<00:48, 45.28it/s]
  3%|▎         | 60/2248 [00:01<00:52, 41.59it/s]
  3%|▎         | 66/2248 [00:01<00:49, 44.33it/s]
  3%|▎         | 73/2248 [00:01<00:43, 49.82it/s]
  4%|▎         | 79/2248 [00:02<01:59, 18.17it/s]
  4%|▎         | 83/2248 [00:02<01:47, 20.07it/s]
  4%|▍         | 88/2248 [00:02<01:31, 23.57it/s]
  4%|▍         | 92/2248 [00:03<01:58, 18.17it/s]
  4%|▍         | 95/2248 [00:03<02:14, 16.04it/s]
  4%|▍         | 98/2248 [00:03<02:58, 12.02it/s]
  4%|▍         | 100/2248 [00:04<03:27, 10.37it/s]
  5%|▍         | 103/2248 [00:04<02:58, 12.00it/s]
  5%|▍         | 105/2248 [00:04<02:58, 12.02it/s]
  5%|▍         | 107/2248 [00:04<02:49, 12.66it/s]
  5%|▍         | 111/2248 [00:04<02:33, 13.90it/s]
  5%|▌         | 113/2248 [00:05<03:58,  8.96it/s]
  5%|▌         | 116/2248 [00:05<04:08,  8.60it/s]
  5%|▌         | 118/2248 [00:06<06:40,  5.32it/s]
  5%|▌         | 120/2248 [00:06<06:31,  5.44it/s]
  5%|▌         | 122/2248 [00:06<05:23,  6.57it/s]
  6%|▌         | 126/2248 [00:07<04:51,  7.29it/s]
  6%|▌         | 127/2248 [00:07<05:54,  5.99it/s]
  6%|▌         | 128/2248 [00:08<06:27,  5.48it/s]
  6%|▌         | 131/2248 [00:08<04:18,  8.19it/s]
  6%|▌         | 133/2248 [00:08<06:22,  5.53it/s]
  6%|▌         | 135/2248 [00:09<06:07,  5.75it/s]
  6%|▌         | 136/2248 [00:09<08:23,  4.20it/s]
  6%|▌         | 138/2248 [00:10<08:37,  4.08it/s]
  6%|▌         | 140/2248 [00:10<06:34,  5.35it/s]
  6%|▋         | 142/2248 [00:10<06:40,  5.25it/s]
  6%|▋         | 145/2248 [00:11<06:24,  5.46it/s]
  7%|▋         | 148/2248 [00:11<04:46,  7.33it/s]
  7%|▋         | 150/2248 [00:11<04:02,  8.67it/s]
  7%|▋         | 152/2248 [00:12<07:14,  4.82it/s]
  7%|▋         | 154/2248 [00:12<05:47,  6.02it/s]
  7%|▋         | 156/2248 [00:13<07:09,  4.87it/s]
  7%|▋         | 157/2248 [00:13<09:53,  3.52it/s]
  7%|▋         | 158/2248 [00:14<12:22,  2.81it/s]
  7%|▋         | 159/2248 [00:15<14:45,  2.36it/s]
  7%|▋         | 160/2248 [00:15<13:55,  2.50it/s]
  7%|▋         | 162/2248 [00:16<13:32,  2.57it/s]
  7%|▋         | 164/2248 [00:16<09:28,  3.67it/s]
  7%|▋         | 165/2248 [00:16<09:38,  3.60it/s]
  7%|▋         | 166/2248 [00:16<08:42,  3.98it/s]
  7%|▋         | 168/2248 [00:17<07:31,  4.61it/s]
  8%|▊         | 169/2248 [00:17<07:33,  4.58it/s]
  8%|▊         | 171/2248 [00:17<05:34,  6.21it/s]
  8%|▊         | 173/2248 [00:17<05:20,  6.47it/s]
  8%|▊         | 175/2248 [00:17<04:22,  7.88it/s]
  8%|▊         | 176/2248 [00:18<05:48,  5.94it/s]
  8%|▊         | 178/2248 [00:18<06:14,  5.53it/s]
  8%|▊         | 180/2248 [00:18<05:06,  6.75it/s]
  8%|▊         | 183/2248 [00:19<03:56,  8.71it/s]
  8%|▊         | 185/2248 [00:19<03:46,  9.12it/s]
  8%|▊         | 187/2248 [00:19<04:17,  8.00it/s]
  8%|▊         | 189/2248 [00:19<04:07,  8.33it/s]
  8%|▊         | 190/2248 [00:19<04:21,  7.87it/s]
  9%|▊         | 192/2248 [00:20<03:39,  9.37it/s]
  9%|▊         | 194/2248 [00:20<03:29,  9.79it/s]
  9%|▊         | 196/2248 [00:20<03:28,  9.86it/s]
  9%|▉         | 199/2248 [00:20<02:34, 13.25it/s]
  9%|▉         | 201/2248 [00:20<02:33, 13.31it/s]
  9%|▉         | 203/2248 [00:21<03:21, 10.14it/s]
  9%|▉         | 205/2248 [00:21<03:56,  8.64it/s]
  9%|▉         | 207/2248 [00:21<04:25,  7.69it/s]
  9%|▉         | 208/2248 [00:21<04:24,  7.70it/s]
  9%|▉         | 209/2248 [00:22<05:07,  6.64it/s]
  9%|▉         | 210/2248 [00:22<06:06,  5.56it/s]
  9%|▉         | 211/2248 [00:22<08:53,  3.82it/s]
  9%|▉         | 212/2248 [00:23<09:01,  3.76it/s]
 10%|▉         | 214/2248 [00:23<06:10,  5.49it/s]
 10%|▉         | 220/2248 [00:23<02:37, 12.90it/s]
 10%|█         | 226/2248 [00:23<01:38, 20.55it/s]
 10%|█         | 230/2248 [00:23<01:24, 23.86it/s]
 10%|█         | 236/2248 [00:23<01:05, 30.95it/s]
 11%|█         | 242/2248 [00:23<00:53, 37.17it/s]
 11%|█         | 249/2248 [00:23<00:46, 43.26it/s]
 11%|█▏        | 256/2248 [00:24<00:40, 49.60it/s]
 12%|█▏        | 262/2248 [00:24<01:02, 31.66it/s]
 12%|█▏        | 267/2248 [00:25<01:53, 17.44it/s]
 12%|█▏        | 271/2248 [00:25<02:59, 11.03it/s]
 12%|█▏        | 274/2248 [00:26<03:11, 10.32it/s]
 12%|█▏        | 276/2248 [00:26<04:22,  7.50it/s]
 12%|█▏        | 278/2248 [00:27<04:21,  7.55it/s]
 12%|█▏        | 280/2248 [00:27<04:32,  7.22it/s]
 13%|█▎        | 282/2248 [00:28<05:54,  5.54it/s]
 13%|█▎        | 284/2248 [00:28<05:39,  5.78it/s]
 13%|█▎        | 287/2248 [00:28<05:23,  6.07it/s]
 13%|█▎        | 290/2248 [00:29<05:01,  6.50it/s]
 13%|█▎        | 291/2248 [00:29<05:42,  5.72it/s]
 13%|█▎        | 292/2248 [00:30<08:04,  4.04it/s]
 13%|█▎        | 294/2248 [00:30<06:08,  5.31it/s]
 13%|█▎        | 298/2248 [00:30<04:12,  7.71it/s]
 13%|█▎        | 300/2248 [00:30<04:09,  7.80it/s]
 13%|█▎        | 302/2248 [00:31<04:16,  7.60it/s]
 13%|█▎        | 303/2248 [00:31<05:35,  5.79it/s]
 14%|█▎        | 304/2248 [00:31<05:36,  5.78it/s]
 14%|█▎        | 305/2248 [00:31<05:53,  5.49it/s]
 14%|█▎        | 306/2248 [00:32<05:52,  5.51it/s]
 14%|█▎        | 307/2248 [00:32<07:01,  4.61it/s]
 14%|█▎        | 308/2248 [00:32<06:43,  4.81it/s]
 14%|█▎        | 309/2248 [00:32<06:49,  4.74it/s]
 14%|█▍        | 311/2248 [00:32<04:37,  6.98it/s]
 14%|█▍        | 312/2248 [00:33<05:32,  5.82it/s]
 14%|█▍        | 313/2248 [00:33<08:10,  3.94it/s]
 14%|█▍        | 314/2248 [00:34<10:18,  3.13it/s]
 14%|█▍        | 315/2248 [00:34<10:44,  3.00it/s]
 14%|█▍        | 317/2248 [00:34<06:44,  4.77it/s]
 14%|█▍        | 318/2248 [00:34<06:38,  4.84it/s]
 14%|█▍        | 320/2248 [00:35<06:05,  5.28it/s]
 14%|█▍        | 322/2248 [00:35<05:51,  5.49it/s]
 14%|█▍        | 323/2248 [00:35<05:29,  5.85it/s]
 14%|█▍        | 325/2248 [00:35<04:25,  7.25it/s]
 15%|█▍        | 326/2248 [00:35<04:10,  7.68it/s]
 15%|█▍        | 327/2248 [00:36<05:08,  6.23it/s]
 15%|█▍        | 328/2248 [00:36<06:00,  5.33it/s]
 15%|█▍        | 329/2248 [00:36<06:24,  5.00it/s]
 15%|█▍        | 330/2248 [00:36<05:55,  5.40it/s]
 15%|█▍        | 332/2248 [00:37<07:49,  4.08it/s]
 15%|█▍        | 335/2248 [00:37<04:56,  6.45it/s]
 15%|█▌        | 339/2248 [00:38<04:09,  7.65it/s]
 15%|█▌        | 340/2248 [00:38<04:39,  6.84it/s]
 15%|█▌        | 343/2248 [00:38<03:58,  8.00it/s]
 15%|█▌        | 344/2248 [00:38<04:53,  6.48it/s]
 15%|█▌        | 345/2248 [00:38<04:45,  6.67it/s]
 15%|█▌        | 346/2248 [00:39<04:43,  6.71it/s]
 15%|█▌        | 347/2248 [00:39<08:07,  3.90it/s]
 15%|█▌        | 348/2248 [00:40<10:33,  3.00it/s]
 16%|█▌        | 349/2248 [00:40<12:26,  2.54it/s]
 16%|█▌        | 350/2248 [00:41<13:45,  2.30it/s]
 16%|█▌        | 352/2248 [00:41<08:28,  3.73it/s]
 16%|█▌        | 353/2248 [00:41<08:08,  3.88it/s]
 16%|█▌        | 354/2248 [00:41<07:04,  4.47it/s]
 16%|█▌        | 355/2248 [00:42<06:33,  4.81it/s]
 16%|█▌        | 356/2248 [00:42<08:05,  3.90it/s]
 16%|█▌        | 358/2248 [00:42<05:29,  5.73it/s]
 16%|█▌        | 361/2248 [00:42<03:23,  9.25it/s]
 16%|█▌        | 363/2248 [00:43<05:07,  6.13it/s]
 16%|█▌        | 365/2248 [00:43<06:53,  4.55it/s]
 16%|█▋        | 366/2248 [00:44<07:14,  4.34it/s]
 16%|█▋        | 367/2248 [00:44<06:56,  4.51it/s]
 16%|█▋        | 370/2248 [00:44<04:17,  7.28it/s]
 17%|█▋        | 372/2248 [00:45<06:17,  4.96it/s]
 17%|█▋        | 373/2248 [00:45<06:30,  4.81it/s]
 17%|█▋        | 375/2248 [00:45<04:53,  6.38it/s]
 17%|█▋        | 377/2248 [00:45<04:47,  6.51it/s]
 17%|█▋        | 379/2248 [00:46<06:32,  4.76it/s]
 17%|█▋        | 382/2248 [00:46<04:27,  6.97it/s]
 17%|█▋        | 384/2248 [00:46<04:22,  7.09it/s]
 17%|█▋        | 386/2248 [00:47<04:38,  6.69it/s]
 17%|█▋        | 388/2248 [00:47<06:14,  4.97it/s]
 17%|█▋        | 389/2248 [00:48<06:03,  5.12it/s]
 17%|█▋        | 390/2248 [00:48<06:08,  5.05it/s]
 17%|█▋        | 391/2248 [00:48<06:24,  4.83it/s]
 17%|█▋        | 392/2248 [00:48<07:13,  4.29it/s]
 17%|█▋        | 393/2248 [00:48<06:12,  4.98it/s]
 18%|█▊        | 394/2248 [00:49<06:18,  4.90it/s]
 18%|█▊        | 396/2248 [00:49<04:24,  7.01it/s]
 18%|█▊        | 401/2248 [00:49<02:07, 14.53it/s]
 18%|█▊        | 407/2248 [00:49<01:18, 23.56it/s]
 18%|█▊        | 414/2248 [00:49<00:56, 32.49it/s]
 19%|█▊        | 418/2248 [00:49<00:54, 33.50it/s]
 19%|█▉        | 425/2248 [00:49<00:44, 41.42it/s]
 19%|█▉        | 430/2248 [00:49<00:42, 43.20it/s]
 19%|█▉        | 436/2248 [00:50<01:05, 27.68it/s]
 20%|█▉        | 440/2248 [00:50<01:52, 16.06it/s]
 20%|█▉        | 443/2248 [00:51<01:55, 15.64it/s]
 20%|█▉        | 446/2248 [00:51<03:28,  8.64it/s]
 20%|█▉        | 448/2248 [00:52<04:16,  7.02it/s]
 20%|██        | 450/2248 [00:52<03:53,  7.69it/s]
 20%|██        | 452/2248 [00:52<03:25,  8.75it/s]
 20%|██        | 454/2248 [00:52<03:18,  9.05it/s]
 20%|██        | 456/2248 [00:53<03:16,  9.14it/s]
 20%|██        | 458/2248 [00:53<04:06,  7.28it/s]
 20%|██        | 459/2248 [00:53<03:56,  7.55it/s]
 20%|██        | 460/2248 [00:54<04:53,  6.10it/s]
 21%|██        | 463/2248 [00:54<04:02,  7.37it/s]
 21%|██        | 464/2248 [00:54<05:54,  5.04it/s]
 21%|██        | 465/2248 [00:55<07:07,  4.17it/s]
 21%|██        | 467/2248 [00:55<05:06,  5.81it/s]
 21%|██        | 469/2248 [00:55<03:56,  7.52it/s]
 21%|██        | 472/2248 [00:56<05:14,  5.64it/s]
 21%|██        | 473/2248 [00:56<07:31,  3.93it/s]
 21%|██        | 475/2248 [00:57<08:16,  3.57it/s]
 21%|██        | 476/2248 [00:58<10:08,  2.91it/s]
 21%|██        | 477/2248 [00:58<09:01,  3.27it/s]
 21%|██▏       | 478/2248 [00:58<08:02,  3.67it/s]
 21%|██▏       | 479/2248 [00:58<07:33,  3.90it/s]
 21%|██▏       | 480/2248 [00:58<07:34,  3.89it/s]
 21%|██▏       | 481/2248 [00:59<07:31,  3.91it/s]
 21%|██▏       | 482/2248 [00:59<08:53,  3.31it/s]
 22%|██▏       | 484/2248 [00:59<05:41,  5.16it/s]
 22%|██▏       | 485/2248 [00:59<05:19,  5.52it/s]
 22%|██▏       | 486/2248 [01:00<05:38,  5.20it/s]
 22%|██▏       | 487/2248 [01:00<06:47,  4.32it/s]
 22%|██▏       | 490/2248 [01:00<03:58,  7.36it/s]
 22%|██▏       | 493/2248 [01:00<02:44, 10.64it/s]
 22%|██▏       | 495/2248 [01:01<04:55,  5.94it/s]
 22%|██▏       | 498/2248 [01:01<03:33,  8.20it/s]
 22%|██▏       | 500/2248 [01:02<06:20,  4.59it/s]
 22%|██▏       | 503/2248 [01:02<05:23,  5.40it/s]
 23%|██▎       | 506/2248 [01:02<03:53,  7.46it/s]
 23%|██▎       | 509/2248 [01:03<03:30,  8.27it/s]
 23%|██▎       | 511/2248 [01:03<03:07,  9.28it/s]
 23%|██▎       | 513/2248 [01:04<05:43,  5.05it/s]
 23%|██▎       | 515/2248 [01:04<06:32,  4.42it/s]
 23%|██▎       | 516/2248 [01:05<06:33,  4.40it/s]
 23%|██▎       | 517/2248 [01:05<06:43,  4.28it/s]
 23%|██▎       | 518/2248 [01:05<07:32,  3.82it/s]
 23%|██▎       | 521/2248 [01:05<04:40,  6.15it/s]
 23%|██▎       | 523/2248 [01:06<03:50,  7.47it/s]
 23%|██▎       | 525/2248 [01:06<05:08,  5.59it/s]
 23%|██▎       | 528/2248 [01:06<03:28,  8.24it/s]
 24%|██▍       | 534/2248 [01:06<01:54, 14.97it/s]
 24%|██▍       | 541/2248 [01:06<01:12, 23.52it/s]
 24%|██▍       | 546/2248 [01:07<01:00, 28.05it/s]
 25%|██▍       | 551/2248 [01:07<02:02, 13.82it/s]
 25%|██▍       | 555/2248 [01:07<01:46, 15.91it/s]
 25%|██▍       | 561/2248 [01:08<01:19, 21.34it/s]
 25%|██▌       | 565/2248 [01:09<03:21,  8.36it/s]
 25%|██▌       | 569/2248 [01:09<02:39, 10.51it/s]
 25%|██▌       | 572/2248 [01:10<03:54,  7.13it/s]
 26%|██▌       | 575/2248 [01:11<05:54,  4.72it/s]
 26%|██▌       | 577/2248 [01:12<06:27,  4.31it/s]
 26%|██▌       | 579/2248 [01:12<06:14,  4.45it/s]
 26%|██▌       | 581/2248 [01:13<05:40,  4.90it/s]
 26%|██▌       | 582/2248 [01:13<05:57,  4.66it/s]
 26%|██▌       | 584/2248 [01:13<04:54,  5.65it/s]
 26%|██▌       | 586/2248 [01:13<04:14,  6.52it/s]
 26%|██▌       | 588/2248 [01:13<03:51,  7.18it/s]
 26%|██▌       | 590/2248 [01:13<03:09,  8.75it/s]
 26%|██▋       | 592/2248 [01:14<03:39,  7.56it/s]
 26%|██▋       | 594/2248 [01:14<03:01,  9.10it/s]
 27%|██▋       | 599/2248 [01:14<02:25, 11.34it/s]
 27%|██▋       | 601/2248 [01:14<02:35, 10.62it/s]
 27%|██▋       | 603/2248 [01:15<03:08,  8.73it/s]
 27%|██▋       | 604/2248 [01:15<03:58,  6.89it/s]
 27%|██▋       | 605/2248 [01:16<04:59,  5.48it/s]
 27%|██▋       | 606/2248 [01:16<05:48,  4.71it/s]
 27%|██▋       | 607/2248 [01:17<08:29,  3.22it/s]
 27%|██▋       | 608/2248 [01:17<09:22,  2.92it/s]
 27%|██▋       | 609/2248 [01:17<10:41,  2.56it/s]
 27%|██▋       | 610/2248 [01:18<09:57,  2.74it/s]
 27%|██▋       | 612/2248 [01:18<06:14,  4.36it/s]
 27%|██▋       | 614/2248 [01:18<04:35,  5.93it/s]
 27%|██▋       | 617/2248 [01:18<02:58,  9.16it/s]
 28%|██▊       | 620/2248 [01:18<02:18, 11.79it/s]
 28%|██▊       | 625/2248 [01:18<01:28, 18.40it/s]
 28%|██▊       | 630/2248 [01:18<01:06, 24.46it/s]
 28%|██▊       | 636/2248 [01:19<00:50, 31.82it/s]
 29%|██▊       | 641/2248 [01:19<00:44, 36.14it/s]
 29%|██▉       | 647/2248 [01:19<00:38, 41.19it/s]
 29%|██▉       | 652/2248 [01:20<02:17, 11.60it/s]
 29%|██▉       | 656/2248 [01:21<03:03,  8.69it/s]
 29%|██▉       | 659/2248 [01:21<03:41,  7.17it/s]
 29%|██▉       | 661/2248 [01:22<04:26,  5.96it/s]
 29%|██▉       | 663/2248 [01:23<05:10,  5.10it/s]
 30%|██▉       | 665/2248 [01:23<05:13,  5.05it/s]
 30%|██▉       | 667/2248 [01:23<04:29,  5.86it/s]
 30%|██▉       | 670/2248 [01:24<04:13,  6.23it/s]
 30%|██▉       | 672/2248 [01:24<03:33,  7.37it/s]
 30%|███       | 675/2248 [01:24<02:40,  9.80it/s]
 30%|███       | 677/2248 [01:25<04:09,  6.29it/s]
 30%|███       | 679/2248 [01:25<04:41,  5.58it/s]
 30%|███       | 681/2248 [01:26<05:19,  4.91it/s]
 30%|███       | 682/2248 [01:26<07:12,  3.62it/s]
 30%|███       | 683/2248 [01:27<08:36,  3.03it/s]
 30%|███       | 684/2248 [01:27<08:05,  3.22it/s]
 30%|███       | 685/2248 [01:27<07:29,  3.47it/s]
 31%|███       | 686/2248 [01:27<06:50,  3.80it/s]
 31%|███       | 688/2248 [01:28<06:38,  3.91it/s]
 31%|███       | 690/2248 [01:28<04:45,  5.45it/s]
 31%|███       | 691/2248 [01:28<04:35,  5.65it/s]
 31%|███       | 692/2248 [01:29<06:14,  4.16it/s]
 31%|███       | 694/2248 [01:29<05:20,  4.84it/s]
 31%|███       | 695/2248 [01:29<05:28,  4.72it/s]
 31%|███       | 698/2248 [01:30<04:14,  6.09it/s]
 31%|███       | 699/2248 [01:30<04:25,  5.83it/s]
 31%|███       | 701/2248 [01:30<03:22,  7.64it/s]
 31%|███       | 702/2248 [01:30<04:08,  6.21it/s]
 31%|███▏      | 704/2248 [01:31<05:29,  4.69it/s]
 31%|███▏      | 706/2248 [01:31<04:07,  6.22it/s]
 32%|███▏      | 709/2248 [01:31<03:32,  7.23it/s]
 32%|███▏      | 711/2248 [01:32<03:45,  6.82it/s]
 32%|███▏      | 712/2248 [01:32<04:18,  5.94it/s]
 32%|███▏      | 713/2248 [01:32<04:48,  5.31it/s]
 32%|███▏      | 715/2248 [01:32<04:27,  5.74it/s]
 32%|███▏      | 716/2248 [01:33<04:43,  5.41it/s]
 32%|███▏      | 718/2248 [01:33<03:29,  7.29it/s]
 32%|███▏      | 719/2248 [01:33<03:59,  6.40it/s]
 32%|███▏      | 721/2248 [01:34<05:36,  4.54it/s]
 32%|███▏      | 723/2248 [01:34<04:13,  6.01it/s]
 32%|███▏      | 727/2248 [01:34<03:06,  8.15it/s]
 32%|███▏      | 729/2248 [01:34<03:14,  7.80it/s]
 33%|███▎      | 731/2248 [01:35<03:20,  7.58it/s]
 33%|███▎      | 732/2248 [01:35<03:51,  6.55it/s]
 33%|███▎      | 733/2248 [01:35<04:12,  6.00it/s]
 33%|███▎      | 734/2248 [01:35<04:28,  5.64it/s]
 33%|███▎      | 735/2248 [01:36<04:52,  5.16it/s]
 33%|███▎      | 736/2248 [01:36<05:10,  4.87it/s]
 33%|███▎      | 737/2248 [01:36<07:37,  3.31it/s]
 33%|███▎      | 738/2248 [01:37<09:40,  2.60it/s]
 33%|███▎      | 740/2248 [01:37<06:12,  4.05it/s]
 33%|███▎      | 742/2248 [01:38<05:59,  4.19it/s]
 33%|███▎      | 743/2248 [01:38<05:24,  4.64it/s]
 33%|███▎      | 744/2248 [01:38<07:00,  3.57it/s]
 33%|███▎      | 747/2248 [01:38<03:55,  6.38it/s]
 33%|███▎      | 749/2248 [01:38<03:27,  7.21it/s]
 33%|███▎      | 751/2248 [01:39<03:34,  6.97it/s]
 33%|███▎      | 752/2248 [01:39<04:24,  5.66it/s]
 34%|███▎      | 754/2248 [01:39<03:40,  6.78it/s]
 34%|███▎      | 756/2248 [01:39<02:53,  8.60it/s]
 34%|███▍      | 761/2248 [01:40<02:54,  8.51it/s]
 34%|███▍      | 764/2248 [01:40<02:20, 10.60it/s]
 34%|███▍      | 767/2248 [01:41<03:15,  7.59it/s]
 34%|███▍      | 771/2248 [01:41<02:20, 10.54it/s]
 34%|███▍      | 773/2248 [01:42<05:11,  4.73it/s]
 34%|███▍      | 775/2248 [01:44<07:43,  3.18it/s]
 35%|███▍      | 776/2248 [01:44<07:57,  3.09it/s]
 35%|███▍      | 778/2248 [01:44<07:29,  3.27it/s]
 35%|███▍      | 780/2248 [01:45<05:45,  4.24it/s]
 35%|███▍      | 782/2248 [01:45<04:55,  4.95it/s]
 35%|███▍      | 783/2248 [01:45<05:52,  4.16it/s]
 35%|███▍      | 784/2248 [01:45<05:55,  4.12it/s]
 35%|███▍      | 786/2248 [01:46<04:14,  5.75it/s]
 35%|███▌      | 789/2248 [01:46<03:53,  6.25it/s]
 35%|███▌      | 791/2248 [01:46<04:00,  6.06it/s]
 35%|███▌      | 792/2248 [01:47<04:12,  5.78it/s]
 35%|███▌      | 794/2248 [01:47<03:55,  6.17it/s]
 35%|███▌      | 796/2248 [01:47<03:05,  7.82it/s]
 35%|███▌      | 798/2248 [01:47<03:16,  7.36it/s]
 36%|███▌      | 800/2248 [01:48<04:47,  5.04it/s]
 36%|███▌      | 803/2248 [01:48<03:16,  7.35it/s]
 36%|███▌      | 806/2248 [01:49<04:01,  5.98it/s]
 36%|███▌      | 808/2248 [01:49<03:22,  7.12it/s]
 36%|███▌      | 810/2248 [01:50<04:36,  5.21it/s]
 36%|███▌      | 811/2248 [01:50<06:08,  3.90it/s]
 36%|███▌      | 812/2248 [01:51<07:39,  3.12it/s]
 36%|███▌      | 813/2248 [01:51<09:07,  2.62it/s]
 36%|███▌      | 814/2248 [01:52<10:18,  2.32it/s]
 36%|███▋      | 815/2248 [01:53<11:25,  2.09it/s]
 36%|███▋      | 817/2248 [01:53<07:15,  3.29it/s]
 37%|███▋      | 823/2248 [01:53<02:51,  8.30it/s]
 37%|███▋      | 827/2248 [01:53<02:01, 11.71it/s]
 37%|███▋      | 830/2248 [01:53<01:47, 13.25it/s]
 37%|███▋      | 835/2248 [01:53<01:15, 18.82it/s]
 37%|███▋      | 841/2248 [01:53<00:53, 26.22it/s]
 38%|███▊      | 847/2248 [01:53<00:43, 32.15it/s]
 38%|███▊      | 852/2248 [01:53<00:41, 33.32it/s]
 38%|███▊      | 858/2248 [01:54<00:35, 39.31it/s]
 39%|███▊      | 866/2248 [01:54<01:07, 20.37it/s]
 39%|███▊      | 870/2248 [01:55<01:25, 16.09it/s]
 39%|███▉      | 873/2248 [01:55<01:25, 16.06it/s]
 39%|███▉      | 876/2248 [01:55<02:02, 11.22it/s]
 39%|███▉      | 878/2248 [01:56<02:43,  8.37it/s]
 39%|███▉      | 880/2248 [01:57<03:31,  6.46it/s]
 39%|███▉      | 882/2248 [01:57<03:51,  5.90it/s]
 39%|███▉      | 884/2248 [01:57<03:18,  6.88it/s]
 39%|███▉      | 886/2248 [01:58<04:21,  5.20it/s]
 40%|███▉      | 888/2248 [01:58<03:57,  5.73it/s]
 40%|███▉      | 890/2248 [01:58<03:39,  6.18it/s]
 40%|███▉      | 891/2248 [01:59<05:14,  4.32it/s]
 40%|███▉      | 893/2248 [01:59<04:05,  5.51it/s]
 40%|███▉      | 894/2248 [01:59<04:35,  4.91it/s]
 40%|███▉      | 895/2248 [02:00<05:05,  4.43it/s]
 40%|███▉      | 896/2248 [02:00<05:55,  3.80it/s]
 40%|███▉      | 898/2248 [02:00<04:15,  5.29it/s]
 40%|████      | 900/2248 [02:00<03:07,  7.21it/s]
 40%|████      | 902/2248 [02:01<02:45,  8.14it/s]
 40%|████      | 904/2248 [02:01<02:35,  8.62it/s]
 40%|████      | 906/2248 [02:01<02:44,  8.14it/s]
 40%|████      | 907/2248 [02:01<03:41,  6.06it/s]
 40%|████      | 908/2248 [02:02<05:22,  4.16it/s]
 40%|████      | 909/2248 [02:02<06:37,  3.37it/s]
 40%|████      | 910/2248 [02:03<06:13,  3.59it/s]
 41%|████      | 911/2248 [02:03<08:26,  2.64it/s]
 41%|████      | 912/2248 [02:04<09:32,  2.33it/s]
 41%|████      | 913/2248 [02:04<10:44,  2.07it/s]
 41%|████      | 915/2248 [02:05<06:28,  3.43it/s]
 41%|████      | 916/2248 [02:05<06:05,  3.65it/s]
 41%|████      | 917/2248 [02:05<08:05,  2.74it/s]
 41%|████      | 919/2248 [02:06<06:13,  3.56it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 334.46it/s]

[[np.int64(0), False, 9], [np.int64(1), False, 11], [np.int64(2), False, 10], [np.int64(3), False, 1], [np.int64(4), False, 7], [np.int64(5), False, 1], [np.int64(6), False, 4], [np.int64(7), False, 11], [np.int64(8), False, 7], [np.int64(10), False, 0], [np.int64(12), False, 4], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0385, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6932, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [21:38<1:15:13, 92.11s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [21:38<51:36, 64.52s/it]

tensor(12.1762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0390, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6755, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0415, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9635, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [21:38<16:39, 22.21s/it]

tensor(12.2345, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0429, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2358, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0440, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4026, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [21:38<07:50, 10.94s/it]

tensor(12.3303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0468, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5056, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0508, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7179, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [21:39<03:42,  5.42s/it]

tensor(12.3158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8200, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9883, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [21:39<01:45,  2.71s/it]

tensor(12.2614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0596, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1677, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0610, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2538, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [21:39<00:51,  1.39s/it]

tensor(12.3191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0623, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2664, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0632, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2853, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [21:39<00:25,  1.35it/s]

tensor(12.3298, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0632, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3090, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3022, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0621, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2884, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [21:39<00:13,  2.37it/s]

tensor(12.2809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0603, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2509, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0576, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2439, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [21:40<00:08,  3.76it/s]

tensor(12.2690, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0545, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2752, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0516, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2997, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [21:40<00:05,  5.28it/s]

tensor(12.2500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0490, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3151, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2365, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0467, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3353, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [21:40<00:04,  6.56it/s]

tensor(12.2268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3654, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0417, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3917, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [21:40<00:03,  7.52it/s]

tensor(12.2216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0392, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4201, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2230, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0374, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4216, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [21:41<00:02,  7.94it/s]

tensor(12.2208, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0359, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4137, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4146, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [21:41<00:02,  8.30it/s]

tensor(12.2103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4192, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4269, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [21:41<00:02,  8.39it/s]

tensor(12.1966, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4351, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4336, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [21:41<00:01,  8.55it/s]

tensor(12.1866, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4328, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4361, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [21:42<00:01,  8.45it/s]

tensor(12.1809, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4358, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4395, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [21:42<00:01,  8.54it/s]

tensor(12.1761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1729, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4427, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [21:42<00:01,  8.52it/s]

tensor(12.1698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4464, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4509, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [21:42<00:01,  8.55it/s]

tensor(12.1622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4504, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4540, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [21:43<00:00,  8.56it/s]

tensor(12.1560, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4554, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4596, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [21:43<00:00,  8.56it/s]

tensor(12.1513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4636, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1491, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4644, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [21:43<00:00,  8.57it/s]

tensor(12.1469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4637, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1446, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4616, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [21:43<00:00,  8.55it/s]

tensor(12.1424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4613, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4605, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [21:43<00:00,  4.35s/it]

tensor(12.1392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4596, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0021767616271972656
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 3
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.374961584790
NMI         : 0.483305433521
Runtime     : 1323.32 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed3

==============================================================================================================
PRAGA RUN | S2-E18 | seed=4
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 1.889e-16
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:31,  9.49it/s]

tensor(16.0098, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1249, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0296, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8088, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:34,  8.73it/s]

tensor(16.0007, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9628, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8381, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 5/300 [00:00<00:30,  9.60it/s]

tensor(15.9185, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1412, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8748, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6107, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8328, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2315, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:28, 10.10it/s]

tensor(15.7905, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9883, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7517, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8679, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7146, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8574, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:28, 10.19it/s]

tensor(15.6791, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9469, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6449, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1276, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6100, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3875, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:27, 10.31it/s]

tensor(15.5763, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5424, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1213, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5077, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5811, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:27, 10.38it/s]

tensor(15.4722, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0941, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4365, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6549, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3993, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2600, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:27, 10.24it/s]

tensor(15.3610, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9046, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3214, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5849, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2804, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2959, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:26, 10.30it/s]

tensor(15.2377, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0373, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1933, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8039, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1478, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5945, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:26, 10.27it/s]

tensor(15.1002, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4061, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0514, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2368, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9999, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0852, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|▉         | 29/300 [00:02<00:26, 10.30it/s]

tensor(14.9478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9486, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8262, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7169, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:25, 10.36it/s]

tensor(14.7830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6192, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4536, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:25, 10.35it/s]

tensor(14.6107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3840, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2682, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:25, 10.37it/s]

tensor(14.4372, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2201, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1781, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1422, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▎        | 41/300 [00:04<00:25, 10.36it/s]

tensor(14.2651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1117, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0865, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1497, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0672, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:24, 10.37it/s]

tensor(14.0921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0527, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0349, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 47/300 [00:04<00:24, 10.35it/s]

tensor(13.9235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8697, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:04<00:24, 10.37it/s]

tensor(13.7654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7142, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6642, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 53/300 [00:05<00:23, 10.37it/s]

tensor(13.6158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5251, device='cuda:0', grad_fn=<AddBackward0>)

 18%|█▊        | 55/300 [00:05<00:23, 10.24it/s]

tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4447, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:05<00:23, 10.34it/s]

tensor(13.4084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3414, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:05<00:23, 10.30it/s]

tensor(13.3096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2783, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:22, 10.31it/s]

tensor(13.2167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:22, 10.37it/s]

tensor(13.1361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0897, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:06<00:22, 10.36it/s]

tensor(13.0671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0441, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:21, 10.32it/s]

tensor(12.9982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9529, device='cuda:0', grad_fn=<AddBackward0>)

 25%|██▌       | 75/300 [00:07<00:21, 10.24it/s]

tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:07<00:21, 10.27it/s]

tensor(12.8872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8658, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:07<00:21, 10.31it/s]

tensor(12.8253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7867, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:20, 10.31it/s]

tensor(12.7682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7502, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:20, 10.39it/s]

tensor(12.7156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6826, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:08<00:20, 10.31it/s]

tensor(12.6670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6363, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:20, 10.34it/s]

tensor(12.6211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5929, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:19, 10.27it/s]

tensor(12.5791, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5527, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:09<00:19, 10.32it/s]

tensor(12.5397, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([163,  72, 123, 245, 199, 121, 119,  63, 286,  89,  56, 411,  64, 237])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<01:54, 19.62it/s]
  0%|          | 6/2248 [00:00<01:11, 31.29it/s]
  0%|          | 10/2248 [00:00<01:11, 31.42it/s]
  1%|          | 14/2248 [00:00<01:40, 22.26it/s]
  1%|          | 17/2248 [00:00<01:37, 22.89it/s]
  1%|          | 20/2248 [00:00<01:41, 22.05it/s]
  1%|          | 26/2248 [00:00<01:11, 31.29it/s]
  1%|▏         | 32/2248 [00:01<01:03, 35.15it/s]
  2%|▏         | 36/2248 [00:01<01:05, 33.96it/s]
  2%|▏         | 40/2248 [00:01<01:03, 34.86it/s]
  2%|▏         | 44/2248 [00:01<01:07, 32.62it/s]
  2%|▏         | 48/2248 [00:01<01:17, 28.25it/s]
  2%|▏         | 52/2248 [00:01<01:12, 30.29it/s]
  2%|▏         | 56/2248 [00:01<01:14, 29.51it/s]
  3%|▎         | 60/2248 [00:02<01:13, 29.86it/s]
  3%|▎         | 65/2248 [00:02<01:03, 34.37it/s]
  3%|▎         | 71/2248 [00:02<01:02, 34.84it/s]
  3%|▎         | 75/2248 [00:02<01:36, 22.49it/s]
  3%|▎         | 78/2248 [00:03<02:30, 14.38it/s]
  4%|▎         | 81/2248 [00:03<02:52, 12.57it/s]
  4%|▎         | 83/2248 [00:03<03:13, 11.19it/s]
  4%|▍         | 86/2248 [00:04<03:11, 11.29it/s]
  4%|▍         | 88/2248 [00:04<03:33, 10.11it/s]
  4%|▍         | 91/2248 [00:04<02:54, 12.39it/s]
  4%|▍         | 96/2248 [00:04<01:59, 18.08it/s]
  4%|▍         | 99/2248 [00:04<02:57, 12.10it/s]
  4%|▍         | 101/2248 [00:05<03:21, 10.63it/s]
  5%|▍         | 104/2248 [00:05<03:16, 10.93it/s]
  5%|▍         | 107/2248 [00:05<02:45, 12.96it/s]
  5%|▍         | 112/2248 [00:05<02:18, 15.41it/s]
  5%|▌         | 114/2248 [00:06<03:08, 11.33it/s]
  5%|▌         | 116/2248 [00:06<05:02,  7.04it/s]
  5%|▌         | 118/2248 [00:07<06:20,  5.60it/s]
  5%|▌         | 120/2248 [00:08<07:32,  4.70it/s]
  5%|▌         | 121/2248 [00:08<09:28,  3.74it/s]
  5%|▌         | 122/2248 [00:09<11:07,  3.19it/s]
  6%|▌         | 124/2248 [00:09<08:06,  4.36it/s]
  6%|▌         | 126/2248 [00:10<09:03,  3.90it/s]
  6%|▌         | 127/2248 [00:10<11:10,  3.16it/s]
  6%|▌         | 128/2248 [00:11<13:05,  2.70it/s]
  6%|▌         | 130/2248 [00:11<09:34,  3.69it/s]
  6%|▌         | 133/2248 [00:12<08:55,  3.95it/s]
  6%|▌         | 135/2248 [00:12<09:51,  3.57it/s]
  6%|▌         | 136/2248 [00:13<11:55,  2.95it/s]
  6%|▌         | 138/2248 [00:13<11:35,  3.03it/s]
  6%|▌         | 139/2248 [00:14<10:33,  3.33it/s]
  6%|▋         | 142/2248 [00:14<06:26,  5.45it/s]
  6%|▋         | 143/2248 [00:14<06:01,  5.82it/s]
  6%|▋         | 145/2248 [00:15<07:39,  4.58it/s]
  7%|▋         | 148/2248 [00:15<05:03,  6.92it/s]
 33%|███▎      | 99/300 [00:28<00:19, 10.32it/s]s]
  7%|▋         | 153/2248 [00:16<07:16,  4.79it/s]
  7%|▋         | 155/2248 [00:16<05:51,  5.96it/s]
  7%|▋         | 157/2248 [00:17<07:39,  4.55it/s]
  7%|▋         | 158/2248 [00:17<08:20,  4.18it/s]
  7%|▋         | 159/2248 [00:17<08:37,  4.04it/s]
  7%|▋         | 160/2248 [00:18<08:43,  3.99it/s]
  7%|▋         | 162/2248 [00:18<08:11,  4.25it/s]
  7%|▋         | 165/2248 [00:19<07:32,  4.60it/s]
  8%|▊         | 169/2248 [00:19<04:56,  7.01it/s]
  8%|▊         | 170/2248 [00:19<04:46,  7.26it/s]
  8%|▊         | 172/2248 [00:19<03:58,  8.70it/s]
  8%|▊         | 174/2248 [00:19<04:51,  7.12it/s]
  8%|▊         | 176/2248 [00:20<04:40,  7.38it/s]
  8%|▊         | 178/2248 [00:20<05:11,  6.65it/s]
  8%|▊         | 180/2248 [00:20<04:17,  8.03it/s]
  8%|▊         | 182/2248 [00:20<03:35,  9.60it/s]
  8%|▊         | 184/2248 [00:21<04:10,  8.25it/s]
  8%|▊         | 186/2248 [00:21<03:30,  9.81it/s]
  8%|▊         | 188/2248 [00:21<03:17, 10.41it/s]
  8%|▊         | 190/2248 [00:21<03:36,  9.53it/s]
  9%|▊         | 192/2248 [00:21<03:20, 10.23it/s]
  9%|▊         | 194/2248 [00:22<03:15, 10.49it/s]
  9%|▊         | 196/2248 [00:22<03:06, 11.01it/s]
  9%|▉         | 198/2248 [00:22<03:07, 10.93it/s]
  9%|▉         | 200/2248 [00:22<03:11, 10.72it/s]
  9%|▉         | 202/2248 [00:23<04:57,  6.88it/s]
  9%|▉         | 203/2248 [00:23<06:01,  5.66it/s]
  9%|▉         | 205/2248 [00:23<05:55,  5.75it/s]
  9%|▉         | 207/2248 [00:24<06:31,  5.21it/s]
  9%|▉         | 209/2248 [00:24<07:52,  4.32it/s]
  9%|▉         | 210/2248 [00:25<07:40,  4.42it/s]
  9%|▉         | 211/2248 [00:25<07:54,  4.29it/s]
  9%|▉         | 212/2248 [00:25<08:43,  3.89it/s]
 10%|▉         | 214/2248 [00:25<06:24,  5.29it/s]
 10%|▉         | 216/2248 [00:26<05:10,  6.54it/s]
 10%|▉         | 218/2248 [00:26<04:14,  7.97it/s]
 10%|▉         | 222/2248 [00:26<02:35, 13.04it/s]
 10%|█         | 226/2248 [00:26<02:02, 16.46it/s]
 10%|█         | 229/2248 [00:26<02:19, 14.50it/s]
 10%|█         | 231/2248 [00:26<02:24, 13.99it/s]
 10%|█         | 233/2248 [00:26<02:22, 14.19it/s]
 10%|█         | 235/2248 [00:27<02:12, 15.14it/s]
 11%|█         | 241/2248 [00:27<01:22, 24.39it/s]
 11%|█         | 247/2248 [00:27<01:02, 31.76it/s]
 11%|█         | 251/2248 [00:27<01:38, 20.36it/s]
 11%|█▏        | 254/2248 [00:27<01:33, 21.29it/s]
 12%|█▏        | 261/2248 [00:27<01:05, 30.52it/s]
 12%|█▏        | 265/2248 [00:28<02:44, 12.02it/s]
 12%|█▏        | 268/2248 [00:29<02:47, 11.81it/s]
 12%|█▏        | 271/2248 [00:29<04:21,  7.56it/s]
 12%|█▏        | 273/2248 [00:30<04:47,  6.87it/s]
 12%|█▏        | 275/2248 [00:31<06:45,  4.86it/s]
 12%|█▏        | 277/2248 [00:31<06:12,  5.30it/s]
 12%|█▏        | 279/2248 [00:31<05:04,  6.47it/s]
 12%|█▎        | 281/2248 [00:31<05:33,  5.89it/s]
 13%|█▎        | 283/2248 [00:32<05:59,  5.47it/s]
 13%|█▎        | 284/2248 [00:32<06:12,  5.27it/s]
 13%|█▎        | 285/2248 [00:32<06:20,  5.17it/s]
 13%|█▎        | 286/2248 [00:33<06:23,  5.12it/s]
 13%|█▎        | 287/2248 [00:33<06:36,  4.95it/s]
 13%|█▎        | 288/2248 [00:33<06:31,  5.01it/s]
 13%|█▎        | 290/2248 [00:33<07:27,  4.37it/s]
 13%|█▎        | 291/2248 [00:34<06:56,  4.70it/s]
 13%|█▎        | 292/2248 [00:34<08:10,  3.99it/s]
 13%|█▎        | 294/2248 [00:34<05:56,  5.49it/s]
 13%|█▎        | 296/2248 [00:34<04:33,  7.13it/s]
 13%|█▎        | 298/2248 [00:35<04:02,  8.03it/s]
 13%|█▎        | 300/2248 [00:35<03:34,  9.09it/s]
 13%|█▎        | 302/2248 [00:35<03:30,  9.25it/s]
 14%|█▎        | 304/2248 [00:35<05:10,  6.26it/s]
 14%|█▎        | 305/2248 [00:36<05:35,  5.80it/s]
 14%|█▎        | 306/2248 [00:36<05:52,  5.52it/s]
 14%|█▎        | 307/2248 [00:36<06:54,  4.68it/s]
 14%|█▎        | 308/2248 [00:36<06:33,  4.93it/s]
 14%|█▎        | 309/2248 [00:37<07:22,  4.38it/s]
 14%|█▍        | 311/2248 [00:37<05:09,  6.25it/s]
 14%|█▍        | 312/2248 [00:37<05:08,  6.27it/s]
 14%|█▍        | 313/2248 [00:37<05:28,  5.89it/s]
 14%|█▍        | 314/2248 [00:37<06:21,  5.07it/s]
 14%|█▍        | 315/2248 [00:38<07:32,  4.27it/s]
 14%|█▍        | 317/2248 [00:38<05:24,  5.95it/s]
 14%|█▍        | 319/2248 [00:38<03:57,  8.12it/s]
 14%|█▍        | 321/2248 [00:38<04:15,  7.55it/s]
 14%|█▍        | 322/2248 [00:39<07:14,  4.44it/s]
 14%|█▍        | 323/2248 [00:39<09:40,  3.31it/s]
 14%|█▍        | 325/2248 [00:40<09:58,  3.21it/s]
 15%|█▍        | 326/2248 [00:40<09:23,  3.41it/s]
 15%|█▍        | 327/2248 [00:41<08:33,  3.74it/s]
 15%|█▍        | 328/2248 [00:41<07:56,  4.03it/s]
 15%|█▍        | 329/2248 [00:41<07:43,  4.14it/s]
 15%|█▍        | 332/2248 [00:42<07:28,  4.28it/s]
 15%|█▍        | 334/2248 [00:42<05:29,  5.81it/s]
 15%|█▍        | 336/2248 [00:42<04:17,  7.43it/s]
 15%|█▌        | 339/2248 [00:42<05:13,  6.10it/s]
 15%|█▌        | 340/2248 [00:43<05:10,  6.14it/s]
 15%|█▌        | 342/2248 [00:43<04:16,  7.44it/s]
 15%|█▌        | 344/2248 [00:43<05:58,  5.31it/s]
 15%|█▌        | 345/2248 [00:44<06:08,  5.17it/s]
 15%|█▌        | 346/2248 [00:44<06:16,  5.05it/s]
 15%|█▌        | 347/2248 [00:44<07:08,  4.44it/s]
 15%|█▌        | 348/2248 [00:44<08:00,  3.95it/s]
 16%|█▌        | 349/2248 [00:45<08:23,  3.77it/s]
 16%|█▌        | 350/2248 [00:45<07:55,  3.99it/s]
 16%|█▌        | 353/2248 [00:45<05:47,  5.45it/s]
 16%|█▌        | 354/2248 [00:45<05:21,  5.90it/s]
 16%|█▌        | 356/2248 [00:46<04:45,  6.63it/s]
 16%|█▌        | 359/2248 [00:46<03:12,  9.80it/s]
 16%|█▌        | 361/2248 [00:46<03:14,  9.69it/s]
 16%|█▌        | 363/2248 [00:46<03:50,  8.18it/s]
 16%|█▌        | 364/2248 [00:47<04:12,  7.46it/s]
 16%|█▋        | 366/2248 [00:47<04:37,  6.79it/s]
 16%|█▋        | 367/2248 [00:47<05:15,  5.97it/s]
 16%|█▋        | 369/2248 [00:47<04:04,  7.70it/s]
 17%|█▋        | 371/2248 [00:48<06:10,  5.07it/s]
 17%|█▋        | 373/2248 [00:49<07:33,  4.13it/s]
 17%|█▋        | 374/2248 [00:49<07:10,  4.36it/s]
 17%|█▋        | 377/2248 [00:49<06:39,  4.68it/s]
 17%|█▋        | 380/2248 [00:50<04:37,  6.73it/s]
 17%|█▋        | 384/2248 [00:50<03:42,  8.39it/s]
 17%|█▋        | 386/2248 [00:50<03:26,  9.01it/s]
 17%|█▋        | 388/2248 [00:50<03:31,  8.81it/s]
 17%|█▋        | 390/2248 [00:51<05:41,  5.44it/s]
 17%|█▋        | 391/2248 [00:51<05:18,  5.82it/s]
 17%|█▋        | 392/2248 [00:52<06:37,  4.66it/s]
 17%|█▋        | 393/2248 [00:52<06:53,  4.49it/s]
 18%|█▊        | 394/2248 [00:52<07:50,  3.94it/s]
 18%|█▊        | 395/2248 [00:52<07:43,  4.00it/s]
 18%|█▊        | 396/2248 [00:52<06:32,  4.71it/s]
 18%|█▊        | 398/2248 [00:53<04:32,  6.79it/s]
 18%|█▊        | 400/2248 [00:53<03:34,  8.61it/s]
 18%|█▊        | 402/2248 [00:53<03:10,  9.69it/s]
 18%|█▊        | 406/2248 [00:53<02:11, 13.97it/s]
 18%|█▊        | 408/2248 [00:53<02:04, 14.73it/s]
 18%|█▊        | 411/2248 [00:53<01:43, 17.70it/s]
 18%|█▊        | 415/2248 [00:53<01:29, 20.52it/s]
 19%|█▊        | 420/2248 [00:54<01:07, 26.97it/s]
 19%|█▉        | 426/2248 [00:54<00:56, 32.38it/s]
 19%|█▉        | 430/2248 [00:54<01:09, 26.28it/s]
 19%|█▉        | 433/2248 [00:54<01:25, 21.24it/s]
 19%|█▉        | 436/2248 [00:55<02:03, 14.72it/s]
 19%|█▉        | 438/2248 [00:55<02:43, 11.05it/s]
 20%|█▉        | 440/2248 [00:55<03:55,  7.68it/s]
 20%|█▉        | 442/2248 [00:56<03:51,  7.78it/s]
 20%|█▉        | 444/2248 [00:56<05:00,  6.00it/s]
 20%|█▉        | 446/2248 [00:57<04:46,  6.28it/s]
 20%|█▉        | 449/2248 [00:57<03:28,  8.63it/s]
 20%|██        | 451/2248 [00:57<03:17,  9.11it/s]
 20%|██        | 453/2248 [00:57<03:40,  8.15it/s]
 20%|██        | 455/2248 [00:57<03:55,  7.63it/s]
 20%|██        | 457/2248 [00:58<03:57,  7.55it/s]
 20%|██        | 459/2248 [00:58<03:27,  8.61it/s]
 21%|██        | 461/2248 [00:58<03:30,  8.48it/s]
 21%|██        | 463/2248 [00:58<03:38,  8.18it/s]
 21%|██        | 464/2248 [00:59<03:46,  7.88it/s]
 21%|██        | 467/2248 [00:59<02:43, 10.88it/s]
 21%|██        | 471/2248 [00:59<02:06, 14.00it/s]
 21%|██        | 473/2248 [00:59<03:31,  8.40it/s]
 21%|██        | 475/2248 [01:00<04:33,  6.48it/s]
 21%|██        | 476/2248 [01:00<04:46,  6.18it/s]
 21%|██        | 477/2248 [01:00<05:26,  5.43it/s]
 21%|██▏       | 478/2248 [01:01<05:46,  5.10it/s]
 21%|██▏       | 479/2248 [01:01<07:53,  3.73it/s]
 21%|██▏       | 480/2248 [01:01<07:39,  3.84it/s]
 21%|██▏       | 481/2248 [01:02<10:00,  2.94it/s]
 21%|██▏       | 482/2248 [01:02<11:33,  2.55it/s]
 22%|██▏       | 484/2248 [01:03<07:11,  4.09it/s]
 22%|██▏       | 485/2248 [01:03<06:46,  4.34it/s]
 22%|██▏       | 486/2248 [01:03<09:06,  3.22it/s]
 22%|██▏       | 487/2248 [01:04<10:38,  2.76it/s]
 22%|██▏       | 488/2248 [01:04<11:49,  2.48it/s]
 22%|██▏       | 491/2248 [01:04<06:05,  4.80it/s]
 22%|██▏       | 495/2248 [01:05<04:19,  6.75it/s]
 22%|██▏       | 497/2248 [01:05<03:40,  7.93it/s]
 22%|██▏       | 499/2248 [01:05<03:09,  9.25it/s]
 22%|██▏       | 501/2248 [01:06<04:40,  6.22it/s]
 22%|██▏       | 503/2248 [01:06<05:53,  4.93it/s]
 22%|██▏       | 505/2248 [01:06<04:37,  6.29it/s]
 23%|██▎       | 507/2248 [01:07<04:15,  6.83it/s]
 23%|██▎       | 509/2248 [01:07<05:14,  5.53it/s]
 23%|██▎       | 512/2248 [01:08<05:37,  5.14it/s]
 23%|██▎       | 513/2248 [01:08<07:17,  3.97it/s]
 23%|██▎       | 514/2248 [01:09<08:29,  3.40it/s]
 23%|██▎       | 515/2248 [01:09<09:00,  3.21it/s]
 23%|██▎       | 517/2248 [01:10<07:44,  3.72it/s]
 23%|██▎       | 518/2248 [01:10<08:05,  3.56it/s]
 23%|██▎       | 519/2248 [01:10<09:00,  3.20it/s]
 23%|██▎       | 520/2248 [01:10<07:37,  3.78it/s]
 23%|██▎       | 521/2248 [01:11<06:31,  4.41it/s]
 23%|██▎       | 523/2248 [01:11<04:22,  6.56it/s]
 23%|██▎       | 525/2248 [01:11<03:32,  8.09it/s]
 23%|██▎       | 527/2248 [01:11<02:53,  9.94it/s]
 24%|██▎       | 529/2248 [01:11<02:27, 11.65it/s]
 24%|██▎       | 531/2248 [01:11<02:11, 13.06it/s]
 24%|██▎       | 533/2248 [01:11<02:03, 13.87it/s]
 24%|██▍       | 535/2248 [01:11<02:07, 13.48it/s]
 24%|██▍       | 540/2248 [01:12<01:25, 20.09it/s]
 24%|██▍       | 544/2248 [01:12<01:08, 24.71it/s]
 24%|██▍       | 550/2248 [01:12<00:51, 33.09it/s]
 25%|██▍       | 554/2248 [01:12<01:14, 22.84it/s]
 25%|██▍       | 557/2248 [01:12<01:18, 21.63it/s]
 25%|██▍       | 560/2248 [01:12<01:18, 21.50it/s]
 25%|██▌       | 563/2248 [01:13<01:17, 21.86it/s]
 25%|██▌       | 567/2248 [01:13<01:05, 25.66it/s]
 25%|██▌       | 571/2248 [01:13<01:09, 24.12it/s]
 26%|██▌       | 574/2248 [01:14<03:26,  8.11it/s]
 26%|██▌       | 576/2248 [01:14<03:10,  8.79it/s]
 26%|██▌       | 578/2248 [01:14<02:53,  9.65it/s]
 26%|██▌       | 580/2248 [01:15<03:20,  8.31it/s]
 26%|██▌       | 582/2248 [01:16<06:56,  4.00it/s]
 26%|██▌       | 583/2248 [01:16<06:20,  4.38it/s]
 26%|██▌       | 584/2248 [01:16<07:49,  3.54it/s]
 26%|██▌       | 586/2248 [01:17<08:09,  3.40it/s]
 26%|██▌       | 588/2248 [01:18<08:34,  3.22it/s]
 26%|██▌       | 590/2248 [01:18<06:21,  4.35it/s]
 26%|██▋       | 592/2248 [01:18<06:40,  4.13it/s]
 26%|██▋       | 595/2248 [01:19<04:40,  5.90it/s]
 27%|██▋       | 597/2248 [01:19<03:50,  7.16it/s]
 27%|██▋       | 599/2248 [01:19<05:12,  5.28it/s]
 27%|██▋       | 600/2248 [01:20<05:14,  5.24it/s]
 27%|██▋       | 603/2248 [01:20<05:12,  5.26it/s]
 27%|██▋       | 604/2248 [01:20<05:33,  4.92it/s]
 27%|██▋       | 605/2248 [01:21<06:26,  4.25it/s]
 27%|██▋       | 606/2248 [01:21<06:58,  3.92it/s]
 27%|██▋       | 607/2248 [01:21<07:01,  3.90it/s]
 27%|██▋       | 608/2248 [01:22<08:54,  3.07it/s]
 27%|██▋       | 609/2248 [01:22<10:33,  2.59it/s]
 27%|██▋       | 610/2248 [01:23<11:43,  2.33it/s]
 27%|██▋       | 613/2248 [01:23<06:08,  4.43it/s]
 27%|██▋       | 616/2248 [01:23<03:57,  6.88it/s]
 28%|██▊       | 619/2248 [01:23<03:06,  8.74it/s]
 28%|██▊       | 621/2248 [01:24<02:42, 10.01it/s]
 28%|██▊       | 623/2248 [01:24<02:28, 10.93it/s]
 28%|██▊       | 625/2248 [01:24<02:27, 11.02it/s]
 28%|██▊       | 629/2248 [01:24<01:44, 15.56it/s]
 28%|██▊       | 635/2248 [01:24<01:07, 23.98it/s]
 28%|██▊       | 638/2248 [01:24<01:04, 25.09it/s]
 29%|██▊       | 642/2248 [01:24<00:58, 27.56it/s]
 29%|██▊       | 646/2248 [01:24<00:57, 27.72it/s]
 29%|██▉       | 650/2248 [01:25<01:25, 18.77it/s]
 29%|██▉       | 653/2248 [01:26<03:16,  8.12it/s]
 29%|██▉       | 655/2248 [01:26<03:04,  8.64it/s]
 29%|██▉       | 657/2248 [01:26<02:42,  9.78it/s]
 29%|██▉       | 659/2248 [01:27<04:06,  6.45it/s]
 29%|██▉       | 661/2248 [01:28<06:15,  4.23it/s]
 29%|██▉       | 663/2248 [01:28<06:07,  4.31it/s]
 30%|██▉       | 664/2248 [01:28<05:53,  4.48it/s]
 30%|██▉       | 665/2248 [01:29<06:09,  4.28it/s]
 30%|██▉       | 667/2248 [01:29<05:11,  5.07it/s]
 30%|██▉       | 669/2248 [01:29<04:08,  6.34it/s]
 30%|██▉       | 670/2248 [01:29<04:08,  6.36it/s]
 30%|██▉       | 672/2248 [01:29<03:13,  8.16it/s]
 30%|███       | 675/2248 [01:29<02:18, 11.39it/s]
 30%|███       | 677/2248 [01:30<03:50,  6.82it/s]
 30%|███       | 679/2248 [01:31<04:53,  5.35it/s]
 30%|███       | 680/2248 [01:31<04:48,  5.44it/s]
 30%|███       | 682/2248 [01:31<05:33,  4.69it/s]
 30%|███       | 683/2248 [01:32<05:32,  4.71it/s]
 30%|███       | 684/2248 [01:32<07:40,  3.39it/s]
 30%|███       | 685/2248 [01:32<07:12,  3.62it/s]
 31%|███       | 686/2248 [01:33<08:51,  2.94it/s]
 31%|███       | 688/2248 [01:33<08:09,  3.19it/s]
 31%|███       | 690/2248 [01:34<05:35,  4.64it/s]
 31%|███       | 691/2248 [01:34<05:39,  4.59it/s]
 31%|███       | 692/2248 [01:34<07:51,  3.30it/s]
 31%|███       | 694/2248 [01:35<05:59,  4.32it/s]
 31%|███       | 695/2248 [01:35<05:57,  4.34it/s]
 31%|███       | 696/2248 [01:35<05:52,  4.40it/s]
 31%|███       | 697/2248 [01:35<05:37,  4.59it/s]
 31%|███       | 698/2248 [01:35<06:01,  4.29it/s]
 31%|███       | 699/2248 [01:36<07:53,  3.27it/s]
 31%|███       | 702/2248 [01:37<06:19,  4.07it/s]
 31%|███▏      | 704/2248 [01:37<06:46,  3.80it/s]
 31%|███▏      | 705/2248 [01:37<05:59,  4.30it/s]
 31%|███▏      | 706/2248 [01:38<07:26,  3.45it/s]
 31%|███▏      | 708/2248 [01:38<05:04,  5.05it/s]
 32%|███▏      | 709/2248 [01:38<06:54,  3.71it/s]
 32%|███▏      | 711/2248 [01:39<07:00,  3.65it/s]
 32%|███▏      | 712/2248 [01:39<06:39,  3.84it/s]
 32%|███▏      | 713/2248 [01:39<06:25,  3.98it/s]
 32%|███▏      | 714/2248 [01:39<05:37,  4.54it/s]
 32%|███▏      | 715/2248 [01:40<05:28,  4.67it/s]
 32%|███▏      | 716/2248 [01:40<04:53,  5.22it/s]
 32%|███▏      | 718/2248 [01:40<03:42,  6.88it/s]
 32%|███▏      | 720/2248 [01:40<03:05,  8.24it/s]
 32%|███▏      | 722/2248 [01:40<02:26, 10.40it/s]
 32%|███▏      | 724/2248 [01:40<02:18, 11.03it/s]
 32%|███▏      | 726/2248 [01:41<02:24, 10.56it/s]
 32%|███▏      | 728/2248 [01:41<03:41,  6.85it/s]
 32%|███▏      | 729/2248 [01:41<04:10,  6.05it/s]
 33%|███▎      | 731/2248 [01:42<03:51,  6.56it/s]
 33%|███▎      | 733/2248 [01:42<03:27,  7.29it/s]
 33%|███▎      | 734/2248 [01:42<03:19,  7.58it/s]
 33%|███▎      | 735/2248 [01:42<03:33,  7.09it/s]
 33%|███▎      | 736/2248 [01:42<03:48,  6.61it/s]
 33%|███▎      | 737/2248 [01:43<04:43,  5.33it/s]
 33%|███▎      | 738/2248 [01:43<04:59,  5.05it/s]
 33%|███▎      | 740/2248 [01:43<03:22,  7.43it/s]
 33%|███▎      | 742/2248 [01:43<03:51,  6.51it/s]
 33%|███▎      | 743/2248 [01:44<04:51,  5.17it/s]
 33%|███▎      | 744/2248 [01:44<05:25,  4.62it/s]
 33%|███▎      | 746/2248 [01:44<04:01,  6.21it/s]
 33%|███▎      | 749/2248 [01:45<03:44,  6.67it/s]
 33%|███▎      | 751/2248 [01:45<03:58,  6.27it/s]
 33%|███▎      | 752/2248 [01:45<04:44,  5.26it/s]
 34%|███▎      | 754/2248 [01:46<05:02,  4.93it/s]
 34%|███▎      | 755/2248 [01:46<04:36,  5.39it/s]
 34%|███▎      | 758/2248 [01:46<02:54,  8.54it/s]
 34%|███▍      | 760/2248 [01:46<02:24, 10.30it/s]
 34%|███▍      | 762/2248 [01:46<02:56,  8.43it/s]
 34%|███▍      | 765/2248 [01:46<02:07, 11.64it/s]
 34%|███▍      | 767/2248 [01:47<02:28,  9.97it/s]
 34%|███▍      | 770/2248 [01:47<01:57, 12.55it/s]
 34%|███▍      | 772/2248 [01:47<03:21,  7.34it/s]
 34%|███▍      | 774/2248 [01:48<05:13,  4.70it/s]
 34%|███▍      | 775/2248 [01:49<05:31,  4.45it/s]
 35%|███▍      | 776/2248 [01:49<06:13,  3.94it/s]
 35%|███▍      | 778/2248 [01:49<05:16,  4.64it/s]
 35%|███▍      | 780/2248 [01:49<04:00,  6.10it/s]
 35%|███▍      | 782/2248 [01:50<03:26,  7.12it/s]
 35%|███▍      | 783/2248 [01:50<03:54,  6.24it/s]
 35%|███▍      | 784/2248 [01:50<04:59,  4.88it/s]
 35%|███▍      | 786/2248 [01:50<04:08,  5.87it/s]
 35%|███▌      | 789/2248 [01:51<04:19,  5.62it/s]
 35%|███▌      | 790/2248 [01:51<04:37,  5.25it/s]
 35%|███▌      | 791/2248 [01:51<04:48,  5.05it/s]
 35%|███▌      | 792/2248 [01:52<04:58,  4.87it/s]
 35%|███▌      | 794/2248 [01:52<03:46,  6.43it/s]
 35%|███▌      | 795/2248 [01:52<04:09,  5.82it/s]
 35%|███▌      | 797/2248 [01:52<04:03,  5.96it/s]
 36%|███▌      | 799/2248 [01:53<03:17,  7.34it/s]
 36%|███▌      | 800/2248 [01:53<04:57,  4.86it/s]
 36%|███▌      | 802/2248 [01:53<03:39,  6.58it/s]
 36%|███▌      | 804/2248 [01:53<02:55,  8.24it/s]
 36%|███▌      | 806/2248 [01:54<03:16,  7.35it/s]
 36%|███▌      | 808/2248 [01:54<02:42,  8.89it/s]
 36%|███▌      | 810/2248 [01:54<03:34,  6.70it/s]
 36%|███▌      | 811/2248 [01:54<04:04,  5.88it/s]
 36%|███▌      | 812/2248 [01:55<04:20,  5.51it/s]
 36%|███▌      | 813/2248 [01:55<05:13,  4.57it/s]
 36%|███▌      | 814/2248 [01:55<05:32,  4.32it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 286.35it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 11], [np.int64(2), False, 13], [np.int64(3), False, 13], [np.int64(4), False, 11], [np.int64(5), False, 3], [np.int64(6), False, 0], [np.int64(7), False, 0], [np.int64(8), False, 11], [np.int64(9), False, 3], [np.int64(10), False, 11], [np.int64(12), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8638, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [05:10<2:29:51, 45.18s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [05:10<2:02:53, 37.24s/it]

tensor(12.5013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9157, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0004, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [05:10<57:06, 17.57s/it]

tensor(12.4806, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0962, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4785, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1643, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [05:11<30:54,  9.61s/it]

tensor(12.4814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2320, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2700, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [05:11<16:00,  5.03s/it]

tensor(12.4930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3372, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4017, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [05:11<08:10,  2.59s/it]

tensor(12.5036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4442, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5101, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [05:11<04:11,  1.35s/it]

tensor(12.5076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5646, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6167, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [05:12<02:13,  1.38it/s]

tensor(12.4957, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6551, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4841, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6444, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [05:12<01:16,  2.40it/s]

tensor(12.4694, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6555, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4523, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6678, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [05:12<00:47,  3.78it/s]

tensor(12.4337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6493, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6692, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [05:12<00:34,  5.25it/s]

tensor(12.3985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6915, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3840, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7117, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [05:13<00:27,  6.55it/s]

tensor(12.3718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7310, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7521, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [05:13<00:23,  7.47it/s]

tensor(12.3518, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7866, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8081, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [05:13<00:21,  7.95it/s]

tensor(12.3324, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8357, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8602, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [05:13<00:20,  8.17it/s]

tensor(12.3150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8829, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3071, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9047, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [05:13<00:20,  8.43it/s]

tensor(12.2993, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9230, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9403, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [05:14<00:19,  8.49it/s]

tensor(12.2843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9540, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9486, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [05:14<00:19,  8.57it/s]

tensor(12.2703, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9648, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9690, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [05:14<00:19,  8.46it/s]

tensor(12.2566, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9543, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2497, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9374, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [05:14<00:18,  8.54it/s]

tensor(12.2436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9632, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2385, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8884, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [05:15<00:18,  8.53it/s]

tensor(12.2360, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8135, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8263, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [05:15<00:18,  8.44it/s]

tensor(12.2429, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8833, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [05:15<00:18,  8.49it/s]

tensor(12.2474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9330, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [05:15<00:18,  8.50it/s]

tensor(12.2334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9525, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9678, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [05:16<00:17,  8.54it/s]

tensor(12.2149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9812, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9970, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [05:16<00:17,  8.59it/s]

tensor(12.2028, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0114, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([130, 142, 401, 125,  92,  80, 118, 307, 257,  62, 153, 282,  39,  60])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:38, 14.14it/s]
  0%|          | 4/2248 [00:00<02:13, 16.76it/s]
  0%|          | 6/2248 [00:00<03:07, 11.96it/s]
  0%|          | 8/2248 [00:00<02:40, 13.99it/s]
  0%|          | 10/2248 [00:00<04:22,  8.52it/s]
  1%|          | 12/2248 [00:01<03:31, 10.55it/s]
  1%|          | 15/2248 [00:01<02:45, 13.47it/s]
  1%|          | 18/2248 [00:01<02:13, 16.70it/s]
  1%|          | 24/2248 [00:01<01:24, 26.45it/s]
  1%|▏         | 32/2248 [00:01<00:57, 38.46it/s]
  2%|▏         | 37/2248 [00:02<01:51, 19.87it/s]
  2%|▏         | 41/2248 [00:02<03:32, 10.38it/s]
  2%|▏         | 44/2248 [00:03<05:00,  7.34it/s]
  2%|▏         | 46/2248 [00:04<05:02,  7.29it/s]
  2%|▏         | 48/2248 [00:04<05:40,  6.46it/s]
  2%|▏         | 50/2248 [00:04<04:50,  7.57it/s]
  2%|▏         | 52/2248 [00:05<05:56,  6.16it/s]
  2%|▏         | 54/2248 [00:05<05:28,  6.67it/s]
  2%|▏         | 56/2248 [00:05<06:29,  5.63it/s]
  3%|▎         | 59/2248 [00:06<04:36,  7.91it/s]
  3%|▎         | 62/2248 [00:06<05:25,  6.71it/s]
  3%|▎         | 65/2248 [00:07<06:03,  6.00it/s]
  3%|▎         | 67/2248 [00:07<05:06,  7.11it/s]
  3%|▎         | 71/2248 [00:07<03:53,  9.31it/s]
  3%|▎         | 73/2248 [00:07<03:32, 10.23it/s]
  3%|▎         | 75/2248 [00:07<03:48,  9.52it/s]
  3%|▎         | 77/2248 [00:08<03:42,  9.77it/s]
  4%|▎         | 79/2248 [00:08<03:12, 11.29it/s]
  4%|▎         | 81/2248 [00:08<05:14,  6.88it/s]
  4%|▎         | 83/2248 [00:09<05:42,  6.32it/s]
  4%|▎         | 84/2248 [00:09<06:35,  5.47it/s]
  4%|▍         | 86/2248 [00:09<06:21,  5.67it/s]
  4%|▍         | 87/2248 [00:10<06:36,  5.45it/s]
  4%|▍         | 88/2248 [00:10<06:27,  5.57it/s]
  4%|▍         | 89/2248 [00:10<09:18,  3.87it/s]
  4%|▍         | 92/2248 [00:10<05:29,  6.55it/s]
  4%|▍         | 94/2248 [00:11<06:48,  5.27it/s]
  4%|▍         | 96/2248 [00:11<07:55,  4.53it/s]
  4%|▍         | 97/2248 [00:12<08:02,  4.46it/s]
  4%|▍         | 98/2248 [00:12<08:42,  4.12it/s]
  4%|▍         | 99/2248 [00:12<07:37,  4.70it/s]
  4%|▍         | 100/2248 [00:12<06:44,  5.32it/s]
  4%|▍         | 101/2248 [00:13<10:08,  3.53it/s]
  5%|▍         | 102/2248 [00:13<12:35,  2.84it/s]
  5%|▍         | 104/2248 [00:14<09:02,  3.95it/s]
  5%|▍         | 106/2248 [00:14<06:18,  5.66it/s]
  5%|▍         | 107/2248 [00:14<09:12,  3.87it/s]
  5%|▍         | 109/2248 [00:15<10:14,  3.48it/s]
  5%|▍         | 110/2248 [00:16<12:31,  2.84it/s]
  5%|▍         | 112/2248 [00:16<09:35,  3.71it/s]
  5%|▌         | 113/2248 [00:16<09:12,  3.87it/s]
  5%|▌         | 114/2248 [00:17<11:38,  3.05it/s]
  5%|▌         | 117/2248 [00:17<09:52,  3.60it/s]
  5%|▌         | 120/2248 [00:18<08:51,  4.00it/s]
  5%|▌         | 122/2248 [00:18<09:30,  3.73it/s]
  5%|▌         | 123/2248 [00:19<11:00,  3.22it/s]
  6%|▌         | 125/2248 [00:19<08:07,  4.36it/s]
  6%|▌         | 126/2248 [00:20<10:18,  3.43it/s]
  6%|▌         | 127/2248 [00:20<12:12,  2.89it/s]
  6%|▌         | 128/2248 [00:20<11:06,  3.18it/s]
  6%|▌         | 130/2248 [00:21<08:03,  4.38it/s]
  6%|▌         | 132/2248 [00:21<05:51,  6.01it/s]
  6%|▌         | 133/2248 [00:21<07:45,  4.54it/s]
  6%|▌         | 135/2248 [00:21<06:41,  5.27it/s]
  6%|▌         | 136/2248 [00:22<07:17,  4.83it/s]
  6%|▌         | 138/2248 [00:22<06:51,  5.13it/s]
  6%|▌         | 139/2248 [00:22<06:38,  5.29it/s]
  6%|▋         | 141/2248 [00:22<05:00,  7.01it/s]
  6%|▋         | 143/2248 [00:23<05:22,  6.53it/s]
  6%|▋         | 145/2248 [00:23<07:18,  4.80it/s]
  7%|▋         | 147/2248 [00:23<05:33,  6.31it/s]
  7%|▋         | 149/2248 [00:24<06:34,  5.32it/s]
  7%|▋         | 151/2248 [00:24<05:45,  6.07it/s]
  7%|▋         | 152/2248 [00:24<05:54,  5.91it/s]
  7%|▋         | 154/2248 [00:25<05:16,  6.62it/s]
  7%|▋         | 156/2248 [00:25<05:44,  6.07it/s]
  7%|▋         | 157/2248 [00:25<06:10,  5.64it/s]
  7%|▋         | 158/2248 [00:26<07:25,  4.69it/s]
  7%|▋         | 159/2248 [00:26<07:24,  4.70it/s]
  7%|▋         | 160/2248 [00:26<09:44,  3.57it/s]
  7%|▋         | 162/2248 [00:27<07:43,  4.50it/s]
  7%|▋         | 164/2248 [00:27<05:39,  6.14it/s]
  7%|▋         | 165/2248 [00:27<06:08,  5.66it/s]
  7%|▋         | 167/2248 [00:27<05:32,  6.25it/s]
  8%|▊         | 169/2248 [00:28<05:41,  6.08it/s]
  8%|▊         | 170/2248 [00:28<06:00,  5.76it/s]
  8%|▊         | 171/2248 [00:28<06:19,  5.48it/s]
  8%|▊         | 172/2248 [00:28<07:33,  4.58it/s]
  8%|▊         | 173/2248 [00:29<09:05,  3.80it/s]
  8%|▊         | 174/2248 [00:29<09:19,  3.70it/s]
  8%|▊         | 176/2248 [00:29<08:08,  4.24it/s]
  8%|▊         | 177/2248 [00:30<07:53,  4.37it/s]
  8%|▊         | 178/2248 [00:30<08:00,  4.30it/s]
  8%|▊         | 179/2248 [00:30<07:23,  4.67it/s]
  8%|▊         | 181/2248 [00:30<05:10,  6.65it/s]
  8%|▊         | 183/2248 [00:30<03:56,  8.73it/s]
  8%|▊         | 185/2248 [00:31<04:24,  7.81it/s]
  8%|▊         | 186/2248 [00:31<05:47,  5.94it/s]
  8%|▊         | 187/2248 [00:31<05:33,  6.19it/s]
  8%|▊         | 188/2248 [00:31<06:29,  5.29it/s]
  8%|▊         | 189/2248 [00:31<06:33,  5.23it/s]
  8%|▊         | 191/2248 [00:32<06:53,  4.98it/s]
  9%|▊         | 192/2248 [00:32<07:48,  4.38it/s]
  9%|▊         | 194/2248 [00:32<06:22,  5.37it/s]
  9%|▊         | 195/2248 [00:33<06:27,  5.30it/s]
  9%|▉         | 197/2248 [00:33<07:27,  4.58it/s]
  9%|▉         | 199/2248 [00:34<06:47,  5.03it/s]
  9%|▉         | 200/2248 [00:34<09:16,  3.68it/s]
  9%|▉         | 202/2248 [00:34<07:32,  4.52it/s]
  9%|▉         | 203/2248 [00:35<08:18,  4.10it/s]
  9%|▉         | 204/2248 [00:35<08:51,  3.85it/s]
  9%|▉         | 205/2248 [00:35<10:10,  3.35it/s]
  9%|▉         | 207/2248 [00:36<07:47,  4.37it/s]
  9%|▉         | 209/2248 [00:36<06:46,  5.02it/s]
  9%|▉         | 210/2248 [00:36<06:26,  5.27it/s]
  9%|▉         | 211/2248 [00:36<07:54,  4.29it/s]
  9%|▉         | 212/2248 [00:37<08:26,  4.02it/s]
  9%|▉         | 213/2248 [00:37<10:28,  3.24it/s]
 10%|▉         | 214/2248 [00:37<09:46,  3.47it/s]
 10%|▉         | 216/2248 [00:38<07:26,  4.56it/s]
 10%|▉         | 219/2248 [00:38<04:30,  7.51it/s]
 10%|▉         | 221/2248 [00:38<04:40,  7.23it/s]
 10%|▉         | 222/2248 [00:38<05:06,  6.61it/s]
 10%|█         | 225/2248 [00:39<03:25,  9.84it/s]
 10%|█         | 227/2248 [00:39<04:30,  7.47it/s]
 10%|█         | 229/2248 [00:40<06:06,  5.51it/s]
 10%|█         | 230/2248 [00:40<06:16,  5.36it/s]
 10%|█         | 232/2248 [00:40<04:47,  7.00it/s]
 10%|█         | 235/2248 [00:40<03:25,  9.79it/s]
 11%|█         | 237/2248 [00:40<03:40,  9.12it/s]
 11%|█         | 240/2248 [00:40<02:46, 12.04it/s]
 11%|█         | 244/2248 [00:40<02:08, 15.63it/s]
 11%|█         | 246/2248 [00:41<02:12, 15.09it/s]
 11%|█         | 249/2248 [00:41<02:04, 16.11it/s]
 11%|█         | 252/2248 [00:41<01:52, 17.70it/s]
 11%|█▏        | 257/2248 [00:41<01:22, 24.10it/s]
 12%|█▏        | 262/2248 [00:41<01:34, 21.11it/s]
 12%|█▏        | 265/2248 [00:42<02:30, 13.19it/s]
 12%|█▏        | 267/2248 [00:42<02:29, 13.21it/s]
 12%|█▏        | 269/2248 [00:42<03:24,  9.67it/s]
 12%|█▏        | 271/2248 [00:43<05:04,  6.49it/s]
 12%|█▏        | 273/2248 [00:43<04:42,  7.00it/s]
 12%|█▏        | 275/2248 [00:44<05:02,  6.53it/s]
 12%|█▏        | 277/2248 [00:44<05:04,  6.48it/s]
 12%|█▏        | 280/2248 [00:44<04:01,  8.16it/s]
 12%|█▎        | 281/2248 [00:45<06:03,  5.41it/s]
 13%|█▎        | 282/2248 [00:45<06:08,  5.34it/s]
 13%|█▎        | 283/2248 [00:45<08:34,  3.82it/s]
 13%|█▎        | 284/2248 [00:46<08:18,  3.94it/s]
 13%|█▎        | 285/2248 [00:46<07:16,  4.50it/s]
 13%|█▎        | 286/2248 [00:46<06:52,  4.75it/s]
 13%|█▎        | 287/2248 [00:46<07:38,  4.28it/s]
 13%|█▎        | 288/2248 [00:46<06:44,  4.85it/s]
 13%|█▎        | 289/2248 [00:47<08:13,  3.97it/s]
 13%|█▎        | 290/2248 [00:47<10:23,  3.14it/s]
 13%|█▎        | 291/2248 [00:47<09:00,  3.62it/s]
 13%|█▎        | 292/2248 [00:48<11:06,  2.93it/s]
 13%|█▎        | 294/2248 [00:48<09:33,  3.40it/s]
 13%|█▎        | 295/2248 [00:49<09:58,  3.27it/s]
 13%|█▎        | 296/2248 [00:49<10:16,  3.17it/s]
 13%|█▎        | 297/2248 [00:49<08:39,  3.76it/s]
 13%|█▎        | 298/2248 [00:49<08:05,  4.02it/s]
 13%|█▎        | 299/2248 [00:50<07:47,  4.17it/s]
 13%|█▎        | 300/2248 [00:50<08:17,  3.91it/s]
 13%|█▎        | 301/2248 [00:50<07:51,  4.13it/s]
 13%|█▎        | 302/2248 [00:50<07:20,  4.42it/s]
 13%|█▎        | 303/2248 [00:51<08:56,  3.63it/s]
 14%|█▎        | 304/2248 [00:51<08:04,  4.01it/s]
 14%|█▎        | 305/2248 [00:51<07:55,  4.09it/s]
 14%|█▎        | 306/2248 [00:51<07:23,  4.38it/s]
 14%|█▎        | 307/2248 [00:52<10:38,  3.04it/s]
 14%|█▎        | 308/2248 [00:52<09:21,  3.45it/s]
 14%|█▎        | 309/2248 [00:53<11:45,  2.75it/s]
 14%|█▍        | 310/2248 [00:53<13:06,  2.46it/s]
 14%|█▍        | 312/2248 [00:53<08:50,  3.65it/s]
 14%|█▍        | 313/2248 [00:54<10:56,  2.95it/s]
 14%|█▍        | 314/2248 [00:54<12:30,  2.58it/s]
 14%|█▍        | 315/2248 [00:55<13:36,  2.37it/s]
 14%|█▍        | 317/2248 [00:55<08:22,  3.84it/s]
 14%|█▍        | 320/2248 [00:56<07:23,  4.35it/s]
 14%|█▍        | 322/2248 [00:56<08:10,  3.93it/s]
 14%|█▍        | 323/2248 [00:57<09:55,  3.23it/s]
 14%|█▍        | 324/2248 [00:57<09:03,  3.54it/s]
 14%|█▍        | 325/2248 [00:58<11:05,  2.89it/s]
 15%|█▍        | 326/2248 [00:58<10:01,  3.19it/s]
 15%|█▍        | 327/2248 [00:58<09:20,  3.43it/s]
 15%|█▍        | 328/2248 [00:58<08:27,  3.78it/s]
 15%|█▍        | 329/2248 [00:58<07:44,  4.13it/s]
 15%|█▍        | 330/2248 [00:59<07:13,  4.43it/s]
 15%|█▍        | 332/2248 [00:59<07:25,  4.30it/s]
 15%|█▍        | 334/2248 [00:59<05:12,  6.12it/s]
 15%|█▍        | 335/2248 [00:59<05:20,  5.97it/s]
 15%|█▌        | 338/2248 [01:00<03:55,  8.10it/s]
 15%|█▌        | 339/2248 [01:00<05:00,  6.35it/s]
 15%|█▌        | 340/2248 [01:00<04:55,  6.45it/s]
 15%|█▌        | 342/2248 [01:00<04:35,  6.91it/s]
 15%|█▌        | 343/2248 [01:01<05:23,  5.89it/s]
 15%|█▌        | 344/2248 [01:01<07:51,  4.03it/s]
 15%|█▌        | 345/2248 [01:01<07:30,  4.23it/s]
 15%|█▌        | 346/2248 [01:01<07:03,  4.49it/s]
 15%|█▌        | 347/2248 [01:02<07:57,  3.98it/s]
 15%|█▌        | 348/2248 [01:02<08:18,  3.81it/s]
 16%|█▌        | 349/2248 [01:02<07:40,  4.13it/s]
 16%|█▌        | 350/2248 [01:03<09:17,  3.41it/s]
 16%|█▌        | 353/2248 [01:03<07:43,  4.09it/s]
 16%|█▌        | 354/2248 [01:03<06:57,  4.54it/s]
 16%|█▌        | 355/2248 [01:04<06:39,  4.73it/s]
 16%|█▌        | 356/2248 [01:04<09:13,  3.42it/s]
 16%|█▌        | 359/2248 [01:04<05:10,  6.08it/s]
 16%|█▌        | 361/2248 [01:04<04:30,  6.98it/s]
 16%|█▌        | 362/2248 [01:05<05:36,  5.61it/s]
 16%|█▌        | 364/2248 [01:05<05:32,  5.67it/s]
 16%|█▋        | 366/2248 [01:06<06:43,  4.67it/s]
 16%|█▋        | 367/2248 [01:06<06:27,  4.85it/s]
 16%|█▋        | 368/2248 [01:06<06:23,  4.90it/s]
 16%|█▋        | 369/2248 [01:06<06:09,  5.08it/s]
 16%|█▋        | 370/2248 [01:06<05:26,  5.75it/s]
 17%|█▋        | 371/2248 [01:07<08:33,  3.65it/s]
 17%|█▋        | 373/2248 [01:08<09:17,  3.36it/s]
 17%|█▋        | 374/2248 [01:08<08:04,  3.87it/s]
 17%|█▋        | 376/2248 [01:08<05:27,  5.71it/s]
 17%|█▋        | 377/2248 [01:08<06:05,  5.11it/s]
 17%|█▋        | 379/2248 [01:09<07:19,  4.25it/s]
 17%|█▋        | 381/2248 [01:09<05:21,  5.81it/s]
 17%|█▋        | 383/2248 [01:09<04:09,  7.49it/s]
 17%|█▋        | 385/2248 [01:09<04:42,  6.59it/s]
 17%|█▋        | 387/2248 [01:09<03:50,  8.08it/s]
 17%|█▋        | 389/2248 [01:11<08:05,  3.83it/s]
 17%|█▋        | 390/2248 [01:11<07:54,  3.91it/s]
 17%|█▋        | 391/2248 [01:11<07:38,  4.05it/s]
 17%|█▋        | 392/2248 [01:12<09:53,  3.13it/s]
 17%|█▋        | 393/2248 [01:12<09:01,  3.43it/s]
 18%|█▊        | 394/2248 [01:12<11:26,  2.70it/s]
 18%|█▊        | 395/2248 [01:13<10:38,  2.90it/s]
 18%|█▊        | 396/2248 [01:13<09:53,  3.12it/s]
 18%|█▊        | 398/2248 [01:13<07:12,  4.27it/s]
 18%|█▊        | 400/2248 [01:13<06:11,  4.97it/s]
 18%|█▊        | 402/2248 [01:14<05:17,  5.82it/s]
 18%|█▊        | 403/2248 [01:14<07:46,  3.95it/s]
 18%|█▊        | 404/2248 [01:15<09:31,  3.22it/s]
 18%|█▊        | 405/2248 [01:15<08:47,  3.49it/s]
 18%|█▊        | 407/2248 [01:16<09:00,  3.40it/s]
 18%|█▊        | 408/2248 [01:16<08:30,  3.60it/s]
 18%|█▊        | 410/2248 [01:16<06:35,  4.65it/s]
 18%|█▊        | 411/2248 [01:16<06:31,  4.69it/s]
 18%|█▊        | 412/2248 [01:17<08:13,  3.72it/s]
 18%|█▊        | 414/2248 [01:17<08:30,  3.60it/s]
 19%|█▊        | 416/2248 [01:17<06:03,  5.04it/s]
 19%|█▊        | 417/2248 [01:18<08:00,  3.81it/s]
 19%|█▊        | 419/2248 [01:18<05:45,  5.29it/s]
 19%|█▊        | 421/2248 [01:18<04:55,  6.18it/s]
 19%|█▉        | 422/2248 [01:19<07:09,  4.25it/s]
 19%|█▉        | 424/2248 [01:19<08:20,  3.64it/s]
 19%|█▉        | 427/2248 [01:20<07:22,  4.11it/s]
 19%|█▉        | 430/2248 [01:20<04:59,  6.07it/s]
 19%|█▉        | 432/2248 [01:20<04:41,  6.44it/s]
 19%|█▉        | 436/2248 [01:21<03:31,  8.58it/s]
 19%|█▉        | 438/2248 [01:21<04:56,  6.10it/s]
 20%|█▉        | 439/2248 [01:22<05:04,  5.95it/s]
 20%|█▉        | 440/2248 [01:22<06:58,  4.32it/s]
 20%|█▉        | 441/2248 [01:23<08:44,  3.45it/s]
 20%|█▉        | 443/2248 [01:23<08:56,  3.36it/s]
 20%|█▉        | 444/2248 [01:24<10:29,  2.87it/s]
 20%|█▉        | 446/2248 [01:24<10:20,  2.90it/s]
 20%|█▉        | 448/2248 [01:25<10:01,  2.99it/s]
 20%|██        | 450/2248 [01:25<08:54,  3.37it/s]
 20%|██        | 452/2248 [01:26<06:34,  4.55it/s]
 20%|██        | 454/2248 [01:26<06:00,  4.97it/s]
 20%|██        | 455/2248 [01:26<07:09,  4.17it/s]
 20%|██        | 456/2248 [01:27<08:45,  3.41it/s]
 20%|██        | 457/2248 [01:27<08:14,  3.62it/s]
 20%|██        | 458/2248 [01:27<08:18,  3.59it/s]
 20%|██        | 459/2248 [01:28<07:50,  3.81it/s]
 20%|██        | 460/2248 [01:28<10:20,  2.88it/s]
 21%|██        | 461/2248 [01:28<09:35,  3.10it/s]
 21%|██        | 462/2248 [01:29<09:08,  3.26it/s]
 21%|██        | 463/2248 [01:29<09:04,  3.28it/s]
 21%|██        | 464/2248 [01:29<09:04,  3.28it/s]
 21%|██        | 466/2248 [01:29<05:39,  5.25it/s]
 21%|██        | 467/2248 [01:30<06:46,  4.39it/s]
 21%|██        | 469/2248 [01:30<06:26,  4.61it/s]
 21%|██        | 470/2248 [01:30<06:17,  4.71it/s]
 21%|██        | 471/2248 [01:30<05:35,  5.29it/s]
 21%|██        | 473/2248 [01:31<04:24,  6.71it/s]
 21%|██        | 474/2248 [01:31<06:56,  4.25it/s]
 21%|██        | 475/2248 [01:32<09:03,  3.26it/s]
 21%|██        | 476/2248 [01:32<08:50,  3.34it/s]
 21%|██        | 477/2248 [01:32<08:34,  3.44it/s]
 21%|██▏       | 478/2248 [01:32<07:16,  4.06it/s]
 21%|██▏       | 479/2248 [01:33<07:00,  4.20it/s]
 21%|██▏       | 480/2248 [01:33<06:38,  4.44it/s]
 21%|██▏       | 481/2248 [01:33<09:07,  3.23it/s]
 21%|██▏       | 482/2248 [01:34<11:02,  2.67it/s]
 22%|██▏       | 485/2248 [01:34<05:33,  5.29it/s]
 22%|██▏       | 486/2248 [01:34<07:17,  4.03it/s]
 22%|██▏       | 487/2248 [01:35<07:06,  4.13it/s]
 22%|██▏       | 488/2248 [01:35<06:15,  4.69it/s]
 22%|██▏       | 490/2248 [01:35<04:26,  6.60it/s]
 22%|██▏       | 492/2248 [01:35<05:46,  5.07it/s]
 22%|██▏       | 494/2248 [01:36<04:24,  6.63it/s]
 22%|██▏       | 496/2248 [01:36<03:52,  7.53it/s]
 22%|██▏       | 498/2248 [01:36<03:34,  8.16it/s]
 22%|██▏       | 500/2248 [01:36<03:35,  8.12it/s]
 22%|██▏       | 503/2248 [01:37<03:41,  7.86it/s]
 22%|██▏       | 505/2248 [01:37<03:05,  9.38it/s]
 23%|██▎       | 507/2248 [01:37<03:18,  8.78it/s]
 23%|██▎       | 509/2248 [01:38<05:03,  5.73it/s]
 23%|██▎       | 511/2248 [01:38<04:03,  7.12it/s]
 23%|██▎       | 513/2248 [01:38<04:36,  6.26it/s]
 23%|██▎       | 514/2248 [01:38<05:03,  5.72it/s]
 23%|██▎       | 515/2248 [01:39<05:31,  5.23it/s]
 23%|██▎       | 516/2248 [01:39<05:32,  5.22it/s]
 23%|██▎       | 517/2248 [01:39<05:33,  5.20it/s]
 23%|██▎       | 518/2248 [01:39<05:31,  5.21it/s]
 23%|██▎       | 519/2248 [01:40<06:19,  4.56it/s]
 23%|██▎       | 520/2248 [01:40<06:07,  4.70it/s]
 23%|██▎       | 521/2248 [01:40<06:03,  4.75it/s]
 23%|██▎       | 523/2248 [01:40<06:00,  4.79it/s]
 23%|██▎       | 525/2248 [01:40<04:23,  6.54it/s]
 23%|██▎       | 527/2248 [01:41<03:41,  7.76it/s]
 24%|██▎       | 529/2248 [01:41<03:04,  9.30it/s]
 24%|██▎       | 531/2248 [01:41<02:41, 10.65it/s]
 24%|██▎       | 533/2248 [01:41<03:24,  8.38it/s]
 24%|██▍       | 535/2248 [01:41<03:07,  9.16it/s]
 24%|██▍       | 537/2248 [01:42<03:13,  8.83it/s]
 24%|██▍       | 539/2248 [01:42<02:52,  9.93it/s]
 24%|██▍       | 542/2248 [01:42<02:08, 13.31it/s]
 24%|██▍       | 544/2248 [01:42<03:42,  7.67it/s]
 24%|██▍       | 547/2248 [01:43<02:41, 10.55it/s]
 25%|██▍       | 551/2248 [01:43<02:14, 12.64it/s]
 25%|██▍       | 554/2248 [01:43<02:20, 12.06it/s]
 25%|██▍       | 556/2248 [01:43<02:16, 12.40it/s]
 25%|██▍       | 558/2248 [01:43<02:10, 12.99it/s]
 25%|██▍       | 560/2248 [01:43<02:04, 13.59it/s]
 25%|██▌       | 566/2248 [01:44<01:14, 22.67it/s]
 25%|██▌       | 571/2248 [01:44<01:17, 21.57it/s]
 26%|██▌       | 574/2248 [01:46<05:08,  5.42it/s]
 26%|██▌       | 576/2248 [01:46<04:34,  6.09it/s]
 26%|██▌       | 579/2248 [01:46<04:25,  6.29it/s]
 26%|██▌       | 581/2248 [01:47<04:16,  6.50it/s]
 26%|██▌       | 583/2248 [01:48<06:44,  4.12it/s]
 26%|██▌       | 584/2248 [01:48<08:00,  3.46it/s]
 26%|██▌       | 585/2248 [01:48<07:35,  3.65it/s]
 26%|██▌       | 586/2248 [01:49<07:17,  3.80it/s]
 26%|██▌       | 587/2248 [01:49<07:05,  3.90it/s]
 26%|██▌       | 588/2248 [01:49<08:09,  3.39it/s]
 26%|██▌       | 589/2248 [01:49<07:12,  3.83it/s]
 26%|██▌       | 590/2248 [01:50<06:51,  4.03it/s]
 26%|██▋       | 592/2248 [01:50<07:31,  3.66it/s]
 26%|██▋       | 594/2248 [01:50<05:13,  5.28it/s]
 26%|██▋       | 595/2248 [01:50<05:16,  5.23it/s]
 27%|██▋       | 597/2248 [01:51<03:53,  7.07it/s]
 27%|██▋       | 599/2248 [01:51<04:22,  6.28it/s]
 27%|██▋       | 600/2248 [01:51<05:00,  5.49it/s]
 27%|██▋       | 602/2248 [01:51<03:44,  7.34it/s]
 27%|██▋       | 604/2248 [01:52<05:44,  4.77it/s]
 27%|██▋       | 605/2248 [01:53<07:27,  3.67it/s]
 27%|██▋       | 606/2248 [01:53<08:57,  3.05it/s]
 27%|██▋       | 607/2248 [01:54<10:18,  2.65it/s]
 27%|██▋       | 608/2248 [01:54<10:15,  2.66it/s]
 27%|██▋       | 609/2248 [01:54<09:39,  2.83it/s]
 27%|██▋       | 610/2248 [01:55<09:43,  2.81it/s]
 27%|██▋       | 612/2248 [01:55<06:04,  4.48it/s]
 27%|██▋       | 613/2248 [01:55<06:07,  4.45it/s]
 27%|██▋       | 616/2248 [01:56<05:44,  4.74it/s]
 27%|██▋       | 617/2248 [01:56<07:18,  3.72it/s]
 27%|██▋       | 618/2248 [01:57<08:07,  3.35it/s]
 28%|██▊       | 619/2248 [01:57<07:01,  3.86it/s]
 28%|██▊       | 620/2248 [01:57<06:18,  4.30it/s]
 28%|██▊       | 621/2248 [01:57<06:12,  4.36it/s]
 28%|██▊       | 622/2248 [01:57<05:37,  4.81it/s]
 28%|██▊       | 624/2248 [01:57<04:48,  5.63it/s]
 28%|██▊       | 625/2248 [01:58<04:42,  5.75it/s]
 28%|██▊       | 626/2248 [01:58<06:04,  4.45it/s]
 28%|██▊       | 628/2248 [01:58<05:13,  5.17it/s]
 28%|██▊       | 630/2248 [01:58<03:51,  7.00it/s]
 28%|██▊       | 631/2248 [01:59<04:39,  5.79it/s]
 28%|██▊       | 633/2248 [01:59<03:28,  7.76it/s]
 28%|██▊       | 635/2248 [01:59<03:08,  8.53it/s]
 28%|██▊       | 637/2248 [01:59<04:01,  6.67it/s]
 28%|██▊       | 638/2248 [02:00<05:28,  4.90it/s]
 29%|██▊       | 641/2248 [02:00<04:33,  5.87it/s]
 29%|██▊       | 643/2248 [02:00<03:45,  7.12it/s]
 29%|██▊       | 645/2248 [02:01<03:44,  7.15it/s]
 29%|██▉       | 647/2248 [02:01<03:00,  8.86it/s]
 29%|██▉       | 650/2248 [02:01<02:31, 10.56it/s]
 29%|██▉       | 652/2248 [02:02<04:38,  5.73it/s]
 29%|██▉       | 653/2248 [02:02<06:20,  4.20it/s]
 29%|██▉       | 655/2248 [02:03<05:35,  4.74it/s]
 29%|██▉       | 657/2248 [02:03<04:53,  5.42it/s]
 29%|██▉       | 658/2248 [02:03<06:44,  3.93it/s]
 29%|██▉       | 660/2248 [02:04<07:33,  3.50it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 319.51it/s]

[[np.int64(0), False, 4], [np.int64(1), False, 4], [np.int64(2), False, 8], [np.int64(3), False, 0], [np.int64(4), False, 10], [np.int64(5), False, 1], [np.int64(6), False, 11], [np.int64(7), False, 11], [np.int64(9), False, 2], [np.int64(12), False, 4], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1959, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [12:17<5:14:22, 126.59s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [12:18<3:38:41, 88.66s/it]

tensor(12.1950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2435, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2861, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [12:18<1:13:40, 30.49s/it]

tensor(12.2011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3348, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [12:18<35:44, 15.00s/it]

tensor(12.2047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3485, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3607, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [12:18<17:24,  7.41s/it]

tensor(12.1983, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3627, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1916, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3717, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [12:19<08:32,  3.69s/it]

tensor(12.1836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3758, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3835, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [12:19<04:15,  1.87s/it]

tensor(12.1675, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3863, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1598, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3933, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [12:19<02:11,  1.03it/s]

tensor(12.1516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4013, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1441, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4051, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [12:19<01:11,  1.86it/s]

tensor(12.1373, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4111, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4142, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [12:20<00:42,  3.10it/s]

tensor(12.1259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4196, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4299, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [12:20<00:27,  4.62it/s]

tensor(12.1173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4356, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4444, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [12:20<00:21,  5.98it/s]

tensor(12.1095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4551, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1051, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4604, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [12:20<00:17,  7.04it/s]

tensor(12.1004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4605, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4668, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [12:20<00:15,  7.79it/s]

tensor(12.0915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4738, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4806, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [12:21<00:14,  8.22it/s]

tensor(12.0848, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4846, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0822, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4895, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [12:21<00:14,  8.32it/s]

tensor(12.0794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4937, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [12:21<00:13,  8.47it/s]

tensor(12.0736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4985, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5035, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [12:21<00:13,  8.50it/s]

tensor(12.0670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5102, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5149, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [12:22<00:13,  8.54it/s]

tensor(12.0607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5178, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5208, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [12:22<00:12,  8.60it/s]

tensor(12.0550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5239, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5266, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [12:22<00:12,  8.67it/s]

tensor(12.0500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5291, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5295, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [12:22<00:12,  8.61it/s]

tensor(12.0449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5315, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5319, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [12:23<00:12,  8.63it/s]

tensor(12.0399, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5328, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0376, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5351, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [12:23<00:11,  8.62it/s]

tensor(12.0351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5375, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5370, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [12:23<00:11,  8.60it/s]

tensor(12.0307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5376, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4890, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [12:23<00:11,  8.58it/s]

tensor(12.0265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4935, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([165, 207,  54, 129, 105, 288, 290,  70, 133,  55, 142, 207, 313,  90])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<04:39,  8.03it/s]
  0%|          | 4/2248 [00:00<03:03, 12.22it/s]
  0%|          | 6/2248 [00:00<04:16,  8.75it/s]
  0%|          | 8/2248 [00:00<03:27, 10.80it/s]
  0%|          | 10/2248 [00:01<05:36,  6.64it/s]
  1%|          | 12/2248 [00:01<04:32,  8.21it/s]
  1%|          | 17/2248 [00:01<02:28, 15.01it/s]
  1%|          | 24/2248 [00:01<01:29, 24.93it/s]
  1%|▏         | 31/2248 [00:01<01:05, 33.59it/s]
  2%|▏         | 36/2248 [00:02<02:17, 16.15it/s]
  2%|▏         | 40/2248 [00:02<02:40, 13.75it/s]
  2%|▏         | 43/2248 [00:03<03:52,  9.46it/s]
  2%|▏         | 45/2248 [00:03<04:15,  8.63it/s]
  2%|▏         | 47/2248 [00:04<04:55,  7.46it/s]
  2%|▏         | 49/2248 [00:04<05:08,  7.13it/s]
  2%|▏         | 52/2248 [00:05<05:10,  7.07it/s]
  2%|▏         | 53/2248 [00:05<05:38,  6.48it/s]
  2%|▏         | 55/2248 [00:05<05:25,  6.73it/s]
  3%|▎         | 57/2248 [00:05<04:41,  7.80it/s]
  3%|▎         | 59/2248 [00:05<04:50,  7.54it/s]
  3%|▎         | 61/2248 [00:06<03:58,  9.18it/s]
  3%|▎         | 63/2248 [00:06<04:19,  8.41it/s]
  3%|▎         | 65/2248 [00:06<05:02,  7.21it/s]
  3%|▎         | 68/2248 [00:06<03:39,  9.94it/s]
  3%|▎         | 71/2248 [00:07<03:19, 10.89it/s]
  3%|▎         | 73/2248 [00:07<02:58, 12.20it/s]
  3%|▎         | 77/2248 [00:07<02:36, 13.88it/s]
  4%|▎         | 80/2248 [00:07<02:15, 16.02it/s]
  4%|▎         | 82/2248 [00:07<03:37,  9.97it/s]
  4%|▎         | 84/2248 [00:08<03:50,  9.37it/s]
  4%|▍         | 86/2248 [00:08<03:37,  9.95it/s]
  4%|▍         | 88/2248 [00:08<04:30,  7.98it/s]
  4%|▍         | 90/2248 [00:09<04:55,  7.30it/s]
  4%|▍         | 93/2248 [00:09<04:22,  8.22it/s]
  4%|▍         | 94/2248 [00:09<05:27,  6.58it/s]
  4%|▍         | 96/2248 [00:10<05:55,  6.06it/s]
  4%|▍         | 98/2248 [00:10<06:32,  5.48it/s]
  4%|▍         | 100/2248 [00:10<05:17,  6.78it/s]
  4%|▍         | 101/2248 [00:10<05:57,  6.00it/s]
  5%|▍         | 102/2248 [00:11<07:13,  4.95it/s]
  5%|▍         | 104/2248 [00:11<05:24,  6.61it/s]
  5%|▍         | 105/2248 [00:11<05:52,  6.08it/s]
  5%|▍         | 107/2248 [00:11<05:29,  6.50it/s]
  5%|▍         | 109/2248 [00:12<05:00,  7.11it/s]
  5%|▍         | 110/2248 [00:12<05:09,  6.92it/s]
  5%|▍         | 112/2248 [00:12<04:07,  8.65it/s]
  5%|▌         | 114/2248 [00:12<05:12,  6.82it/s]
  5%|▌         | 116/2248 [00:12<04:06,  8.65it/s]
  5%|▌         | 118/2248 [00:13<04:13,  8.39it/s]
  5%|▌         | 120/2248 [00:13<05:20,  6.65it/s]
  5%|▌         | 122/2248 [00:13<04:23,  8.08it/s]
  6%|▌         | 124/2248 [00:14<04:58,  7.11it/s]
  6%|▌         | 126/2248 [00:14<04:02,  8.74it/s]
  6%|▌         | 128/2248 [00:14<03:52,  9.11it/s]
  6%|▌         | 130/2248 [00:14<03:43,  9.48it/s]
  6%|▌         | 133/2248 [00:14<02:59, 11.79it/s]
  6%|▌         | 136/2248 [00:15<03:01, 11.63it/s]
  6%|▌         | 139/2248 [00:15<03:14, 10.84it/s]
  6%|▋         | 142/2248 [00:15<02:47, 12.58it/s]
  6%|▋         | 144/2248 [00:15<03:05, 11.32it/s]
  6%|▋         | 146/2248 [00:15<02:47, 12.54it/s]
  7%|▋         | 148/2248 [00:16<03:09, 11.11it/s]
  7%|▋         | 150/2248 [00:16<02:51, 12.23it/s]
  7%|▋         | 152/2248 [00:16<03:00, 11.60it/s]
  7%|▋         | 154/2248 [00:16<03:39,  9.55it/s]
  7%|▋         | 157/2248 [00:16<03:00, 11.57it/s]
  7%|▋         | 159/2248 [00:17<03:16, 10.61it/s]
  7%|▋         | 162/2248 [00:17<02:33, 13.58it/s]
  7%|▋         | 167/2248 [00:17<02:30, 13.82it/s]
  8%|▊         | 169/2248 [00:17<02:23, 14.44it/s]
  8%|▊         | 171/2248 [00:18<04:17,  8.05it/s]
  8%|▊         | 173/2248 [00:18<05:34,  6.21it/s]
  8%|▊         | 174/2248 [00:19<06:10,  5.59it/s]
  8%|▊         | 176/2248 [00:19<05:07,  6.74it/s]
  8%|▊         | 177/2248 [00:19<05:04,  6.80it/s]
  8%|▊         | 178/2248 [00:19<05:19,  6.48it/s]
  8%|▊         | 179/2248 [00:19<06:14,  5.52it/s]
  8%|▊         | 182/2248 [00:20<03:47,  9.08it/s]
  8%|▊         | 184/2248 [00:20<04:43,  7.28it/s]
  8%|▊         | 186/2248 [00:20<05:49,  5.89it/s]
  8%|▊         | 188/2248 [00:21<06:28,  5.30it/s]
  8%|▊         | 190/2248 [00:21<05:06,  6.71it/s]
  9%|▊         | 192/2248 [00:22<07:09,  4.78it/s]
  9%|▊         | 195/2248 [00:22<05:31,  6.19it/s]
  9%|▉         | 197/2248 [00:22<05:55,  5.77it/s]
  9%|▉         | 198/2248 [00:23<05:58,  5.72it/s]
  9%|▉         | 199/2248 [00:23<07:23,  4.62it/s]
  9%|▉         | 200/2248 [00:23<07:36,  4.49it/s]
  9%|▉         | 203/2248 [00:24<06:23,  5.33it/s]
  9%|▉         | 204/2248 [00:24<07:33,  4.51it/s]
  9%|▉         | 205/2248 [00:24<07:18,  4.65it/s]
  9%|▉         | 207/2248 [00:24<06:11,  5.50it/s]
  9%|▉         | 209/2248 [00:25<05:22,  6.32it/s]
  9%|▉         | 210/2248 [00:25<05:35,  6.07it/s]
  9%|▉         | 211/2248 [00:25<05:55,  5.72it/s]
  9%|▉         | 213/2248 [00:25<06:14,  5.44it/s]
 10%|▉         | 214/2248 [00:26<06:48,  4.98it/s]
 10%|▉         | 216/2248 [00:26<06:18,  5.38it/s]
 10%|▉         | 218/2248 [00:26<04:42,  7.20it/s]
 10%|▉         | 220/2248 [00:26<04:32,  7.43it/s]
 10%|▉         | 222/2248 [00:27<04:37,  7.31it/s]
 10%|▉         | 224/2248 [00:27<03:49,  8.81it/s]
 10%|█         | 226/2248 [00:27<03:51,  8.72it/s]
 10%|█         | 228/2248 [00:28<05:31,  6.09it/s]
 10%|█         | 230/2248 [00:28<05:27,  6.16it/s]
 10%|█         | 233/2248 [00:28<03:48,  8.83it/s]
 11%|█         | 240/2248 [00:28<01:55, 17.35it/s]
 11%|█         | 244/2248 [00:28<02:07, 15.74it/s]
 11%|█         | 247/2248 [00:29<01:58, 16.88it/s]
 11%|█         | 250/2248 [00:29<02:16, 14.60it/s]
 11%|█▏        | 254/2248 [00:29<01:50, 18.05it/s]
 12%|█▏        | 262/2248 [00:29<01:10, 28.19it/s]
 12%|█▏        | 266/2248 [00:29<01:31, 21.70it/s]
 12%|█▏        | 269/2248 [00:30<02:07, 15.48it/s]
 12%|█▏        | 272/2248 [00:30<03:17,  9.98it/s]
 12%|█▏        | 274/2248 [00:31<04:18,  7.62it/s]
 12%|█▏        | 276/2248 [00:31<04:09,  7.91it/s]
 12%|█▏        | 278/2248 [00:31<03:53,  8.45it/s]
 12%|█▏        | 280/2248 [00:31<03:24,  9.61it/s]
 13%|█▎        | 282/2248 [00:32<03:15, 10.04it/s]
 13%|█▎        | 284/2248 [00:32<03:52,  8.44it/s]
 13%|█▎        | 286/2248 [00:32<03:58,  8.24it/s]
 13%|█▎        | 287/2248 [00:32<04:14,  7.71it/s]
 13%|█▎        | 288/2248 [00:33<04:30,  7.24it/s]
 13%|█▎        | 289/2248 [00:33<05:46,  5.65it/s]
 13%|█▎        | 290/2248 [00:33<06:04,  5.37it/s]
 13%|█▎        | 291/2248 [00:33<06:10,  5.28it/s]
 13%|█▎        | 293/2248 [00:33<04:18,  7.56it/s]
 13%|█▎        | 294/2248 [00:34<06:09,  5.29it/s]
 13%|█▎        | 296/2248 [00:34<06:28,  5.03it/s]
 13%|█▎        | 297/2248 [00:34<06:45,  4.81it/s]
 13%|█▎        | 298/2248 [00:35<06:56,  4.69it/s]
 13%|█▎        | 301/2248 [00:35<05:09,  6.29it/s]
 13%|█▎        | 303/2248 [00:35<04:52,  6.64it/s]
 14%|█▎        | 304/2248 [00:36<05:12,  6.22it/s]
 14%|█▎        | 306/2248 [00:36<03:57,  8.18it/s]
 14%|█▎        | 308/2248 [00:36<04:12,  7.68it/s]
 14%|█▎        | 309/2248 [00:36<04:41,  6.88it/s]
 14%|█▍        | 310/2248 [00:36<05:34,  5.80it/s]
 14%|█▍        | 312/2248 [00:37<04:14,  7.61it/s]
 14%|█▍        | 314/2248 [00:37<04:26,  7.26it/s]
 14%|█▍        | 315/2248 [00:37<05:21,  6.02it/s]
 14%|█▍        | 317/2248 [00:37<05:29,  5.86it/s]
 14%|█▍        | 318/2248 [00:38<05:31,  5.82it/s]
 14%|█▍        | 319/2248 [00:38<05:25,  5.93it/s]
 14%|█▍        | 321/2248 [00:38<03:55,  8.17it/s]
 14%|█▍        | 323/2248 [00:38<03:25,  9.36it/s]
 14%|█▍        | 325/2248 [00:39<05:43,  5.61it/s]
 15%|█▍        | 326/2248 [00:39<06:08,  5.21it/s]
 15%|█▍        | 327/2248 [00:39<05:33,  5.75it/s]
 15%|█▍        | 329/2248 [00:39<04:14,  7.53it/s]
 15%|█▍        | 330/2248 [00:39<04:55,  6.50it/s]
 15%|█▍        | 332/2248 [00:40<04:28,  7.14it/s]
 15%|█▍        | 335/2248 [00:40<03:54,  8.15it/s]
 15%|█▍        | 337/2248 [00:40<03:24,  9.33it/s]
 15%|█▌        | 339/2248 [00:40<03:53,  8.19it/s]
 15%|█▌        | 340/2248 [00:41<04:21,  7.29it/s]
 15%|█▌        | 342/2248 [00:41<04:36,  6.90it/s]
 15%|█▌        | 343/2248 [00:41<04:58,  6.38it/s]
 15%|█▌        | 344/2248 [00:41<05:16,  6.02it/s]
 15%|█▌        | 345/2248 [00:42<05:31,  5.74it/s]
 15%|█▌        | 347/2248 [00:42<04:50,  6.53it/s]
 15%|█▌        | 348/2248 [00:42<05:14,  6.04it/s]
 16%|█▌        | 349/2248 [00:42<05:34,  5.68it/s]
 16%|█▌        | 352/2248 [00:42<03:27,  9.14it/s]
 16%|█▌        | 354/2248 [00:43<03:45,  8.40it/s]
 16%|█▌        | 356/2248 [00:43<03:50,  8.21it/s]
 16%|█▌        | 358/2248 [00:43<03:10,  9.93it/s]
 16%|█▌        | 360/2248 [00:43<03:05, 10.16it/s]
 16%|█▌        | 362/2248 [00:43<03:30,  8.97it/s]
 16%|█▌        | 364/2248 [00:44<03:30,  8.94it/s]
 16%|█▋        | 366/2248 [00:44<03:40,  8.55it/s]
 16%|█▋        | 367/2248 [00:44<04:16,  7.32it/s]
 16%|█▋        | 368/2248 [00:44<05:09,  6.07it/s]
 16%|█▋        | 370/2248 [00:45<04:00,  7.81it/s]
 17%|█▋        | 371/2248 [00:45<04:24,  7.11it/s]
 17%|█▋        | 373/2248 [00:45<03:21,  9.32it/s]
 17%|█▋        | 375/2248 [00:45<03:47,  8.23it/s]
 17%|█▋        | 377/2248 [00:45<03:48,  8.20it/s]
 17%|█▋        | 379/2248 [00:45<03:05, 10.05it/s]
 17%|█▋        | 384/2248 [00:46<02:26, 12.74it/s]
 17%|█▋        | 387/2248 [00:46<02:02, 15.16it/s]
 17%|█▋        | 389/2248 [00:46<02:58, 10.43it/s]
 17%|█▋        | 392/2248 [00:47<02:56, 10.52it/s]
 18%|█▊        | 394/2248 [00:47<03:04, 10.04it/s]
 18%|█▊        | 396/2248 [00:47<02:42, 11.38it/s]
 18%|█▊        | 398/2248 [00:47<03:05,  9.98it/s]
 18%|█▊        | 401/2248 [00:47<02:24, 12.74it/s]
 18%|█▊        | 403/2248 [00:48<03:05,  9.97it/s]
 18%|█▊        | 405/2248 [00:48<03:28,  8.85it/s]
 18%|█▊        | 407/2248 [00:48<04:37,  6.64it/s]
 18%|█▊        | 408/2248 [00:49<05:08,  5.96it/s]
 18%|█▊        | 410/2248 [00:49<05:00,  6.11it/s]
 18%|█▊        | 411/2248 [00:49<05:35,  5.47it/s]
 18%|█▊        | 414/2248 [00:49<03:38,  8.37it/s]
 19%|█▊        | 416/2248 [00:50<04:20,  7.04it/s]
 19%|█▊        | 417/2248 [00:50<05:47,  5.27it/s]
 19%|█▊        | 419/2248 [00:50<04:22,  6.98it/s]
 19%|█▊        | 421/2248 [00:51<04:22,  6.97it/s]
 19%|█▉        | 423/2248 [00:51<03:35,  8.47it/s]
 19%|█▉        | 425/2248 [00:51<04:26,  6.84it/s]
 19%|█▉        | 427/2248 [00:52<04:59,  6.07it/s]
 19%|█▉        | 429/2248 [00:52<04:02,  7.51it/s]
 19%|█▉        | 431/2248 [00:52<03:53,  7.79it/s]
 19%|█▉        | 433/2248 [00:52<03:22,  8.95it/s]
 19%|█▉        | 438/2248 [00:52<01:58, 15.30it/s]
 20%|█▉        | 441/2248 [00:53<02:41, 11.18it/s]
 20%|█▉        | 443/2248 [00:53<03:23,  8.87it/s]
 20%|█▉        | 445/2248 [00:53<03:16,  9.19it/s]
 20%|█▉        | 448/2248 [00:53<02:31, 11.92it/s]
 20%|██        | 454/2248 [00:54<02:07, 14.03it/s]
 20%|██        | 456/2248 [00:54<02:31, 11.87it/s]
 20%|██        | 458/2248 [00:54<02:24, 12.35it/s]
 20%|██        | 460/2248 [00:54<02:51, 10.43it/s]
 21%|██        | 462/2248 [00:55<03:39,  8.12it/s]
 21%|██        | 463/2248 [00:55<03:53,  7.66it/s]
 21%|██        | 464/2248 [00:55<04:31,  6.58it/s]
 21%|██        | 466/2248 [00:55<03:31,  8.43it/s]
 21%|██        | 468/2248 [00:56<04:06,  7.21it/s]
 21%|██        | 469/2248 [00:56<05:15,  5.64it/s]
 21%|██        | 470/2248 [00:56<04:55,  6.02it/s]
 21%|██        | 471/2248 [00:56<04:58,  5.96it/s]
 21%|██        | 473/2248 [00:56<04:25,  6.68it/s]
 21%|██        | 474/2248 [00:57<05:00,  5.91it/s]
 21%|██        | 475/2248 [00:57<04:51,  6.08it/s]
 21%|██        | 476/2248 [00:57<04:50,  6.11it/s]
 21%|██        | 477/2248 [00:57<05:09,  5.73it/s]
 21%|██▏       | 479/2248 [00:57<04:31,  6.52it/s]
 21%|██▏       | 480/2248 [00:58<04:37,  6.37it/s]
 21%|██▏       | 481/2248 [00:58<04:41,  6.28it/s]
 21%|██▏       | 483/2248 [00:58<03:26,  8.53it/s]
 22%|██▏       | 486/2248 [00:58<02:21, 12.43it/s]
 22%|██▏       | 490/2248 [00:58<01:38, 17.82it/s]
 22%|██▏       | 496/2248 [00:58<01:03, 27.52it/s]
 22%|██▏       | 500/2248 [00:59<01:44, 16.70it/s]
 22%|██▏       | 503/2248 [00:59<02:10, 13.42it/s]
 23%|██▎       | 506/2248 [01:00<02:50, 10.20it/s]
 23%|██▎       | 508/2248 [01:00<02:49, 10.26it/s]
 23%|██▎       | 510/2248 [01:00<02:47, 10.35it/s]
 23%|██▎       | 512/2248 [01:00<02:32, 11.38it/s]
 23%|██▎       | 514/2248 [01:00<02:48, 10.27it/s]
 23%|██▎       | 517/2248 [01:00<02:09, 13.36it/s]
 23%|██▎       | 519/2248 [01:01<02:18, 12.48it/s]
 23%|██▎       | 521/2248 [01:01<03:55,  7.34it/s]
 23%|██▎       | 523/2248 [01:01<03:37,  7.94it/s]
 23%|██▎       | 525/2248 [01:01<03:03,  9.41it/s]
 23%|██▎       | 527/2248 [01:02<04:10,  6.87it/s]
 24%|██▎       | 529/2248 [01:02<03:29,  8.22it/s]
 24%|██▎       | 533/2248 [01:02<03:08,  9.11it/s]
 24%|██▍       | 535/2248 [01:03<03:36,  7.92it/s]
 24%|██▍       | 537/2248 [01:03<03:36,  7.89it/s]
 24%|██▍       | 539/2248 [01:03<03:05,  9.22it/s]
 24%|██▍       | 542/2248 [01:03<02:18, 12.35it/s]
 24%|██▍       | 544/2248 [01:04<02:49, 10.07it/s]
 24%|██▍       | 547/2248 [01:04<02:20, 12.13it/s]
 25%|██▍       | 551/2248 [01:04<02:12, 12.79it/s]
 25%|██▍       | 553/2248 [01:04<02:05, 13.53it/s]
 25%|██▍       | 555/2248 [01:04<02:07, 13.31it/s]
 25%|██▍       | 558/2248 [01:05<02:17, 12.26it/s]
 25%|██▍       | 561/2248 [01:05<01:52, 15.02it/s]
 25%|██▌       | 569/2248 [01:05<01:03, 26.39it/s]
 25%|██▌       | 573/2248 [01:05<01:14, 22.46it/s]
 26%|██▌       | 576/2248 [01:05<01:19, 21.15it/s]
 26%|██▌       | 579/2248 [01:05<01:28, 18.88it/s]
 26%|██▌       | 582/2248 [01:06<01:36, 17.33it/s]
 26%|██▌       | 584/2248 [01:06<02:44, 10.14it/s]
 26%|██▌       | 586/2248 [01:07<03:23,  8.16it/s]
 26%|██▌       | 588/2248 [01:07<04:05,  6.75it/s]
 26%|██▌       | 589/2248 [01:07<04:31,  6.12it/s]
 26%|██▌       | 590/2248 [01:08<05:03,  5.47it/s]
 26%|██▋       | 592/2248 [01:08<03:57,  6.98it/s]
 26%|██▋       | 595/2248 [01:08<03:51,  7.14it/s]
 27%|██▋       | 597/2248 [01:08<03:13,  8.54it/s]
 27%|██▋       | 603/2248 [01:09<02:09, 12.68it/s]
 27%|██▋       | 605/2248 [01:09<02:48,  9.74it/s]
 27%|██▋       | 607/2248 [01:09<02:50,  9.64it/s]
 27%|██▋       | 609/2248 [01:09<02:45,  9.88it/s]
 27%|██▋       | 612/2248 [01:09<02:19, 11.77it/s]
 27%|██▋       | 614/2248 [01:10<02:41, 10.12it/s]
 27%|██▋       | 616/2248 [01:10<02:24, 11.28it/s]
 27%|██▋       | 618/2248 [01:10<03:55,  6.93it/s]
 28%|██▊       | 620/2248 [01:11<03:31,  7.69it/s]
 28%|██▊       | 622/2248 [01:11<03:18,  8.18it/s]
 28%|██▊       | 624/2248 [01:11<03:24,  7.94it/s]
 28%|██▊       | 625/2248 [01:11<03:34,  7.57it/s]
 28%|██▊       | 626/2248 [01:11<03:47,  7.12it/s]
 28%|██▊       | 628/2248 [01:12<04:23,  6.16it/s]
 28%|██▊       | 629/2248 [01:12<04:24,  6.12it/s]
 28%|██▊       | 631/2248 [01:12<03:45,  7.17it/s]
 28%|██▊       | 633/2248 [01:12<02:56,  9.16it/s]
 28%|██▊       | 635/2248 [01:13<03:06,  8.63it/s]
 28%|██▊       | 637/2248 [01:13<05:26,  4.93it/s]
 28%|██▊       | 638/2248 [01:14<06:25,  4.18it/s]
 28%|██▊       | 640/2248 [01:14<04:50,  5.54it/s]
 29%|██▊       | 641/2248 [01:14<05:45,  4.66it/s]
 29%|██▊       | 643/2248 [01:14<04:11,  6.39it/s]
 29%|██▊       | 645/2248 [01:15<04:20,  6.16it/s]
 29%|██▉       | 647/2248 [01:15<03:28,  7.66it/s]
 29%|██▉       | 649/2248 [01:15<02:50,  9.39it/s]
 29%|██▉       | 651/2248 [01:15<03:04,  8.64it/s]
 29%|██▉       | 653/2248 [01:15<03:07,  8.53it/s]
 29%|██▉       | 655/2248 [01:16<03:12,  8.28it/s]
 29%|██▉       | 657/2248 [01:16<03:29,  7.61it/s]
 29%|██▉       | 659/2248 [01:16<02:52,  9.22it/s]
 29%|██▉       | 661/2248 [01:16<02:49,  9.38it/s]
 30%|██▉       | 664/2248 [01:17<02:57,  8.94it/s]
 30%|██▉       | 666/2248 [01:17<03:04,  8.55it/s]
 30%|██▉       | 667/2248 [01:17<03:18,  7.95it/s]
 30%|██▉       | 668/2248 [01:18<04:38,  5.67it/s]
 30%|██▉       | 670/2248 [01:18<04:08,  6.36it/s]
 30%|██▉       | 672/2248 [01:18<03:18,  7.94it/s]
 30%|██▉       | 673/2248 [01:18<04:20,  6.04it/s]
 30%|███       | 676/2248 [01:19<03:52,  6.77it/s]
 30%|███       | 678/2248 [01:19<03:51,  6.80it/s]
 30%|███       | 680/2248 [01:19<03:51,  6.77it/s]
 30%|███       | 682/2248 [01:19<03:43,  7.00it/s]
 30%|███       | 683/2248 [01:20<04:11,  6.23it/s]
 30%|███       | 684/2248 [01:20<04:24,  5.92it/s]
 30%|███       | 685/2248 [01:20<04:40,  5.57it/s]
 31%|███       | 688/2248 [01:20<02:55,  8.90it/s]
 31%|███       | 693/2248 [01:20<01:38, 15.82it/s]
 31%|███       | 696/2248 [01:21<02:19, 11.14it/s]
 31%|███       | 698/2248 [01:21<02:54,  8.90it/s]
 31%|███       | 700/2248 [01:22<04:09,  6.22it/s]
 31%|███       | 702/2248 [01:22<03:54,  6.60it/s]
 31%|███▏      | 703/2248 [01:22<04:28,  5.76it/s]
 31%|███▏      | 704/2248 [01:23<04:31,  5.69it/s]
 31%|███▏      | 705/2248 [01:23<04:53,  5.26it/s]
 31%|███▏      | 708/2248 [01:23<03:08,  8.16it/s]
 32%|███▏      | 710/2248 [01:23<02:48,  9.13it/s]
 32%|███▏      | 712/2248 [01:23<02:30, 10.24it/s]
 32%|███▏      | 714/2248 [01:24<03:10,  8.04it/s]
 32%|███▏      | 716/2248 [01:24<02:38,  9.68it/s]
 32%|███▏      | 718/2248 [01:24<03:55,  6.51it/s]
 32%|███▏      | 719/2248 [01:24<04:07,  6.18it/s]
 32%|███▏      | 721/2248 [01:25<03:25,  7.42it/s]
 32%|███▏      | 723/2248 [01:25<04:04,  6.24it/s]
 32%|███▏      | 725/2248 [01:25<04:06,  6.18it/s]
 32%|███▏      | 726/2248 [01:26<04:27,  5.70it/s]
 32%|███▏      | 727/2248 [01:26<04:13,  6.01it/s]
 32%|███▏      | 729/2248 [01:26<03:34,  7.10it/s]
 32%|███▏      | 730/2248 [01:26<04:24,  5.74it/s]
 33%|███▎      | 732/2248 [01:26<03:49,  6.60it/s]
 33%|███▎      | 733/2248 [01:27<03:55,  6.43it/s]
 33%|███▎      | 735/2248 [01:27<02:57,  8.52it/s]
 33%|███▎      | 737/2248 [01:27<02:39,  9.47it/s]
 33%|███▎      | 739/2248 [01:27<03:19,  7.56it/s]
 33%|███▎      | 741/2248 [01:27<02:40,  9.39it/s]
 33%|███▎      | 744/2248 [01:27<01:55, 13.05it/s]
 33%|███▎      | 746/2248 [01:28<01:54, 13.11it/s]
 33%|███▎      | 748/2248 [01:28<02:34,  9.69it/s]
 33%|███▎      | 750/2248 [01:28<02:20, 10.70it/s]
 33%|███▎      | 752/2248 [01:28<02:23, 10.41it/s]
 34%|███▎      | 754/2248 [01:29<03:25,  7.28it/s]
 34%|███▎      | 755/2248 [01:29<03:20,  7.45it/s]
 34%|███▎      | 757/2248 [01:29<02:40,  9.29it/s]
 34%|███▍      | 759/2248 [01:29<03:20,  7.43it/s]
 34%|███▍      | 761/2248 [01:30<02:44,  9.06it/s]
 34%|███▍      | 763/2248 [01:30<02:51,  8.64it/s]
 34%|███▍      | 765/2248 [01:30<04:04,  6.07it/s]
 34%|███▍      | 767/2248 [01:30<03:18,  7.44it/s]
 34%|███▍      | 769/2248 [01:31<02:43,  9.04it/s]
 34%|███▍      | 771/2248 [01:31<03:18,  7.44it/s]
 34%|███▍      | 774/2248 [01:31<03:05,  7.97it/s]
 35%|███▍      | 776/2248 [01:31<02:36,  9.42it/s]
 35%|███▍      | 779/2248 [01:32<02:33,  9.54it/s]
 35%|███▍      | 781/2248 [01:32<02:19, 10.52it/s]
 35%|███▍      | 783/2248 [01:32<02:01, 12.06it/s]
 35%|███▍      | 786/2248 [01:32<02:20, 10.38it/s]
 35%|███▌      | 788/2248 [01:33<03:29,  6.97it/s]
 35%|███▌      | 790/2248 [01:33<03:23,  7.16it/s]
 35%|███▌      | 792/2248 [01:33<02:53,  8.41it/s]
 35%|███▌      | 794/2248 [01:34<03:21,  7.21it/s]
 35%|███▌      | 795/2248 [01:34<04:21,  5.56it/s]
 35%|███▌      | 797/2248 [01:34<03:20,  7.24it/s]
 36%|███▌      | 799/2248 [01:35<03:50,  6.29it/s]
 36%|███▌      | 802/2248 [01:35<02:39,  9.07it/s]
 36%|███▌      | 804/2248 [01:35<03:09,  7.61it/s]
 36%|███▌      | 806/2248 [01:35<03:49,  6.28it/s]
 36%|███▌      | 810/2248 [01:36<02:24,  9.95it/s]
 36%|███▋      | 816/2248 [01:36<01:26, 16.47it/s]
 36%|███▋      | 819/2248 [01:36<02:21, 10.07it/s]
 37%|███▋      | 822/2248 [01:37<02:25,  9.77it/s]
 37%|███▋      | 824/2248 [01:37<02:43,  8.73it/s]
 37%|███▋      | 826/2248 [01:37<03:02,  7.81it/s]
 37%|███▋      | 828/2248 [01:38<03:11,  7.43it/s]
 37%|███▋      | 830/2248 [01:38<03:27,  6.82it/s]
 37%|███▋      | 831/2248 [01:38<03:54,  6.04it/s]
 37%|███▋      | 832/2248 [01:39<04:23,  5.38it/s]
 37%|███▋      | 834/2248 [01:39<04:14,  5.57it/s]
 37%|███▋      | 835/2248 [01:39<04:36,  5.11it/s]
 37%|███▋      | 837/2248 [01:39<03:29,  6.72it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 314.94it/s]

[[np.int64(0), False, 6], [np.int64(1), False, 12], [np.int64(2), False, 13], [np.int64(3), False, 6], [np.int64(4), False, 1], [np.int64(5), False, 6], [np.int64(7), False, 13], [np.int64(8), False, 0], [np.int64(9), False, 1], [np.int64(10), False, 4], [np.int64(11), False, 12]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2099, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [17:01<2:17:33, 83.37s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [17:01<1:35:23, 58.40s/it]

tensor(12.0243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2673, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3127, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [17:01<31:50, 20.11s/it]

tensor(12.0273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3377, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0289, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3551, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [17:01<15:21,  9.91s/it]

tensor(12.0296, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3572, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [17:02<07:27,  4.92s/it]

tensor(12.0275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3688, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3739, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [17:02<03:39,  2.47s/it]

tensor(12.0209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3822, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3936, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [17:02<01:50,  1.27s/it]

tensor(12.0154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4000, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4042, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [17:02<00:57,  1.47it/s]

tensor(12.0102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4079, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4087, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [17:03<00:32,  2.54it/s]

tensor(12.0056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4094, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0029, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4116, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [17:03<00:20,  3.97it/s]

tensor(12.0004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4150, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4149, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [17:03<00:14,  5.48it/s]

tensor(11.9949, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4215, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9924, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4256, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [17:03<00:11,  6.71it/s]

tensor(11.9899, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4312, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9875, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4364, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [17:04<00:09,  7.57it/s]

tensor(11.9852, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4405, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [17:04<00:09,  8.10it/s]

tensor(11.9808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4450, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4466, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [17:04<00:08,  8.26it/s]

tensor(11.9776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4508, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4548, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [17:04<00:08,  8.40it/s]

tensor(11.9748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4600, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4619, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [17:05<00:07,  8.48it/s]

tensor(11.9717, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4636, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9700, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4666, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [17:05<00:07,  8.46it/s]

tensor(11.9686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4625, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4629, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [17:05<00:07,  8.58it/s]

tensor(11.9659, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4628, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4675, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [17:05<00:07,  8.59it/s]

tensor(11.9631, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4692, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9617, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4714, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [17:05<00:06,  8.61it/s]

tensor(11.9602, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4745, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4765, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [17:06<00:06,  8.61it/s]

tensor(11.9574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4774, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4789, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [17:06<00:06,  8.60it/s]

tensor(11.9547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4827, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9533, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4839, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [17:06<00:06,  8.61it/s]

tensor(11.9520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4865, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9505, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4881, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [17:06<00:06,  8.49it/s]

tensor(11.9495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4912, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9481, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4925, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [17:06<00:05,  8.49it/s]

tensor(11.9468, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4951, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([162, 266,  88, 103, 130, 248, 326, 108,  67, 139, 128, 229, 178,  76])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:01, 18.52it/s]
  0%|          | 9/2248 [00:00<00:50, 44.64it/s]
  1%|          | 16/2248 [00:00<00:41, 53.77it/s]
  1%|          | 22/2248 [00:00<00:50, 44.23it/s]
  1%|▏         | 29/2248 [00:00<00:43, 50.91it/s]
  2%|▏         | 35/2248 [00:00<00:41, 53.25it/s]
  2%|▏         | 41/2248 [00:00<00:41, 53.52it/s]
  2%|▏         | 47/2248 [00:00<00:48, 45.50it/s]
  2%|▏         | 53/2248 [00:01<00:47, 45.73it/s]
  3%|▎         | 58/2248 [00:01<01:13, 29.61it/s]
  3%|▎         | 62/2248 [00:01<01:37, 22.39it/s]
  3%|▎         | 65/2248 [00:01<01:43, 21.01it/s]
  3%|▎         | 68/2248 [00:02<01:40, 21.66it/s]
  3%|▎         | 74/2248 [00:02<01:16, 28.25it/s]
  3%|▎         | 78/2248 [00:02<02:05, 17.34it/s]
  4%|▎         | 81/2248 [00:02<02:11, 16.45it/s]
  4%|▎         | 84/2248 [00:03<02:15, 15.94it/s]
  4%|▍         | 87/2248 [00:03<02:25, 14.90it/s]
  4%|▍         | 89/2248 [00:03<02:22, 15.19it/s]
  4%|▍         | 93/2248 [00:03<01:53, 18.97it/s]
  4%|▍         | 96/2248 [00:03<02:26, 14.67it/s]
  4%|▍         | 98/2248 [00:04<02:54, 12.30it/s]
  4%|▍         | 100/2248 [00:04<03:11, 11.24it/s]
  5%|▍         | 102/2248 [00:04<03:09, 11.32it/s]
  5%|▍         | 104/2248 [00:04<02:52, 12.45it/s]
  5%|▍         | 108/2248 [00:04<02:07, 16.81it/s]
  5%|▍         | 110/2248 [00:05<03:10, 11.23it/s]
  5%|▍         | 112/2248 [00:05<03:02, 11.71it/s]
  5%|▌         | 114/2248 [00:05<02:46, 12.85it/s]
  5%|▌         | 116/2248 [00:05<02:34, 13.84it/s]
  5%|▌         | 118/2248 [00:05<03:14, 10.95it/s]
  5%|▌         | 120/2248 [00:06<03:34,  9.93it/s]
  5%|▌         | 122/2248 [00:06<03:14, 10.96it/s]
  6%|▌         | 124/2248 [00:06<03:05, 11.46it/s]
  6%|▌         | 126/2248 [00:06<04:04,  8.68it/s]
  6%|▌         | 128/2248 [00:07<04:40,  7.57it/s]
  6%|▌         | 130/2248 [00:07<03:58,  8.89it/s]
  6%|▌         | 133/2248 [00:07<03:14, 10.88it/s]
  6%|▌         | 135/2248 [00:07<03:05, 11.39it/s]
  6%|▌         | 137/2248 [00:07<03:21, 10.47it/s]
  6%|▌         | 139/2248 [00:08<03:37,  9.68it/s]
  6%|▋         | 141/2248 [00:08<03:33,  9.85it/s]
  6%|▋         | 143/2248 [00:08<03:19, 10.57it/s]
  6%|▋         | 145/2248 [00:08<03:12, 10.94it/s]
  7%|▋         | 147/2248 [00:08<02:53, 12.13it/s]
  7%|▋         | 149/2248 [00:08<02:56, 11.91it/s]
  7%|▋         | 151/2248 [00:08<02:57, 11.82it/s]
  7%|▋         | 153/2248 [00:09<03:35,  9.72it/s]
  7%|▋         | 156/2248 [00:09<03:20, 10.42it/s]
  7%|▋         | 158/2248 [00:09<03:52,  8.98it/s]
  7%|▋         | 160/2248 [00:10<03:54,  8.89it/s]
  7%|▋         | 162/2248 [00:10<03:21, 10.34it/s]
  7%|▋         | 165/2248 [00:10<02:40, 13.01it/s]
  7%|▋         | 167/2248 [00:10<03:19, 10.44it/s]
  8%|▊         | 169/2248 [00:10<03:43,  9.29it/s]
  8%|▊         | 171/2248 [00:11<03:44,  9.26it/s]
  8%|▊         | 173/2248 [00:11<04:21,  7.93it/s]
  8%|▊         | 174/2248 [00:11<04:17,  8.05it/s]
  8%|▊         | 176/2248 [00:11<04:19,  7.97it/s]
  8%|▊         | 178/2248 [00:12<04:42,  7.34it/s]
  8%|▊         | 180/2248 [00:12<03:52,  8.91it/s]
  8%|▊         | 183/2248 [00:12<03:24, 10.10it/s]
  8%|▊         | 185/2248 [00:12<04:24,  7.79it/s]
  8%|▊         | 187/2248 [00:13<04:26,  7.73it/s]
  8%|▊         | 189/2248 [00:13<04:22,  7.83it/s]
  8%|▊         | 190/2248 [00:13<04:41,  7.31it/s]
  8%|▊         | 191/2248 [00:13<04:48,  7.14it/s]
  9%|▊         | 193/2248 [00:13<03:48,  8.98it/s]
  9%|▊         | 195/2248 [00:14<03:57,  8.64it/s]
  9%|▉         | 197/2248 [00:14<04:14,  8.06it/s]
  9%|▉         | 199/2248 [00:14<04:15,  8.01it/s]
  9%|▉         | 200/2248 [00:14<04:44,  7.21it/s]
  9%|▉         | 202/2248 [00:15<04:52,  7.01it/s]
  9%|▉         | 203/2248 [00:15<05:07,  6.65it/s]
  9%|▉         | 205/2248 [00:15<05:08,  6.63it/s]
  9%|▉         | 207/2248 [00:15<04:54,  6.94it/s]
  9%|▉         | 209/2248 [00:16<04:39,  7.31it/s]
  9%|▉         | 210/2248 [00:16<05:22,  6.32it/s]
  9%|▉         | 211/2248 [00:16<05:44,  5.91it/s]
  9%|▉         | 213/2248 [00:16<05:10,  6.55it/s]
 10%|▉         | 217/2248 [00:16<03:01, 11.20it/s]
 10%|▉         | 223/2248 [00:17<01:51, 18.10it/s]
 10%|█         | 226/2248 [00:17<01:44, 19.34it/s]
 10%|█         | 231/2248 [00:17<01:20, 25.09it/s]
 11%|█         | 238/2248 [00:17<00:59, 33.83it/s]
 11%|█         | 244/2248 [00:17<00:50, 39.36it/s]
 11%|█         | 251/2248 [00:17<00:43, 45.54it/s]
 11%|█▏        | 258/2248 [00:17<00:40, 49.12it/s]
 12%|█▏        | 264/2248 [00:18<01:13, 27.01it/s]
 12%|█▏        | 269/2248 [00:18<01:44, 18.99it/s]
 12%|█▏        | 273/2248 [00:19<02:17, 14.35it/s]
 12%|█▏        | 276/2248 [00:19<02:33, 12.86it/s]
 12%|█▏        | 278/2248 [00:19<02:49, 11.63it/s]
 12%|█▏        | 280/2248 [00:20<02:57, 11.07it/s]
 13%|█▎        | 282/2248 [00:20<03:17,  9.97it/s]
 13%|█▎        | 284/2248 [00:20<03:48,  8.60it/s]
 13%|█▎        | 286/2248 [00:20<03:58,  8.21it/s]
 13%|█▎        | 288/2248 [00:21<03:36,  9.07it/s]
 13%|█▎        | 290/2248 [00:21<03:46,  8.65it/s]
 13%|█▎        | 292/2248 [00:21<03:47,  8.58it/s]
 13%|█▎        | 294/2248 [00:21<03:29,  9.31it/s]
 13%|█▎        | 296/2248 [00:22<03:40,  8.84it/s]
 13%|█▎        | 297/2248 [00:22<03:36,  9.01it/s]
 13%|█▎        | 298/2248 [00:22<04:27,  7.30it/s]
 13%|█▎        | 299/2248 [00:22<05:05,  6.38it/s]
 13%|█▎        | 301/2248 [00:22<04:07,  7.88it/s]
 13%|█▎        | 303/2248 [00:22<03:36,  8.97it/s]
 14%|█▎        | 304/2248 [00:23<03:56,  8.21it/s]
 14%|█▎        | 306/2248 [00:23<03:45,  8.61it/s]
 14%|█▎        | 308/2248 [00:23<04:01,  8.02it/s]
 14%|█▎        | 309/2248 [00:23<04:21,  7.42it/s]
 14%|█▍        | 310/2248 [00:23<04:10,  7.75it/s]
 14%|█▍        | 312/2248 [00:24<03:57,  8.14it/s]
 14%|█▍        | 313/2248 [00:24<03:56,  8.17it/s]
 14%|█▍        | 314/2248 [00:24<04:00,  8.06it/s]
 14%|█▍        | 315/2248 [00:24<03:55,  8.22it/s]
 14%|█▍        | 317/2248 [00:24<03:04, 10.47it/s]
 14%|█▍        | 319/2248 [00:24<02:42, 11.86it/s]
 14%|█▍        | 321/2248 [00:24<02:21, 13.67it/s]
 14%|█▍        | 323/2248 [00:25<03:31,  9.12it/s]
 14%|█▍        | 325/2248 [00:25<03:16,  9.79it/s]
 15%|█▍        | 327/2248 [00:25<04:01,  7.95it/s]
 15%|█▍        | 328/2248 [00:25<04:15,  7.53it/s]
 15%|█▍        | 330/2248 [00:26<03:39,  8.76it/s]
 15%|█▍        | 332/2248 [00:26<03:35,  8.90it/s]
 15%|█▍        | 335/2248 [00:26<03:02, 10.49it/s]
 15%|█▍        | 337/2248 [00:26<02:41, 11.81it/s]
 15%|█▌        | 339/2248 [00:26<03:04, 10.37it/s]
 15%|█▌        | 341/2248 [00:26<02:50, 11.19it/s]
 15%|█▌        | 343/2248 [00:27<03:01, 10.50it/s]
 15%|█▌        | 345/2248 [00:27<04:12,  7.55it/s]
 15%|█▌        | 346/2248 [00:27<04:15,  7.44it/s]
 15%|█▌        | 347/2248 [00:27<04:13,  7.50it/s]
 16%|█▌        | 349/2248 [00:28<03:42,  8.54it/s]
 16%|█▌        | 351/2248 [00:28<03:06, 10.15it/s]
 16%|█▌        | 353/2248 [00:28<02:46, 11.39it/s]
 16%|█▌        | 355/2248 [00:28<03:12,  9.84it/s]
 16%|█▌        | 357/2248 [00:28<03:20,  9.44it/s]
 16%|█▌        | 360/2248 [00:28<02:31, 12.44it/s]
 16%|█▌        | 362/2248 [00:29<02:30, 12.49it/s]
 16%|█▌        | 364/2248 [00:29<02:49, 11.14it/s]
 16%|█▋        | 366/2248 [00:29<03:05, 10.17it/s]
 16%|█▋        | 368/2248 [00:29<03:17,  9.52it/s]
 16%|█▋        | 370/2248 [00:30<03:04, 10.21it/s]
 17%|█▋        | 372/2248 [00:30<03:06, 10.07it/s]
 17%|█▋        | 374/2248 [00:30<03:23,  9.22it/s]
 17%|█▋        | 377/2248 [00:30<03:16,  9.54it/s]
 17%|█▋        | 379/2248 [00:31<03:19,  9.36it/s]
 17%|█▋        | 382/2248 [00:31<02:36, 11.93it/s]
 17%|█▋        | 384/2248 [00:31<02:40, 11.61it/s]
 17%|█▋        | 386/2248 [00:31<03:01, 10.24it/s]
 17%|█▋        | 388/2248 [00:31<03:14,  9.56it/s]
 17%|█▋        | 390/2248 [00:32<04:11,  7.38it/s]
 17%|█▋        | 391/2248 [00:32<04:36,  6.71it/s]
 17%|█▋        | 392/2248 [00:32<05:00,  6.18it/s]
 17%|█▋        | 393/2248 [00:32<05:10,  5.98it/s]
 18%|█▊        | 394/2248 [00:33<05:22,  5.75it/s]
 18%|█▊        | 397/2248 [00:33<03:20,  9.22it/s]
 18%|█▊        | 403/2248 [00:33<01:41, 18.10it/s]
 18%|█▊        | 407/2248 [00:33<01:40, 18.28it/s]
 18%|█▊        | 410/2248 [00:33<01:41, 18.18it/s]
 18%|█▊        | 415/2248 [00:33<01:36, 18.90it/s]
 19%|█▊        | 418/2248 [00:34<01:51, 16.35it/s]
 19%|█▊        | 421/2248 [00:34<01:38, 18.50it/s]
 19%|█▉        | 424/2248 [00:34<01:39, 18.25it/s]
 19%|█▉        | 427/2248 [00:34<01:35, 19.03it/s]
 19%|█▉        | 430/2248 [00:34<01:28, 20.52it/s]
 19%|█▉        | 436/2248 [00:34<01:13, 24.70it/s]
 20%|█▉        | 439/2248 [00:35<02:16, 13.26it/s]
 20%|█▉        | 441/2248 [00:35<02:37, 11.48it/s]
 20%|█▉        | 443/2248 [00:36<02:54, 10.33it/s]
 20%|█▉        | 445/2248 [00:36<03:04,  9.77it/s]
 20%|█▉        | 447/2248 [00:36<03:14,  9.27it/s]
 20%|█▉        | 449/2248 [00:36<03:18,  9.07it/s]
 20%|██        | 452/2248 [00:36<02:30, 11.94it/s]
 20%|██        | 454/2248 [00:37<03:17,  9.09it/s]
 20%|██        | 456/2248 [00:37<04:00,  7.45it/s]
 20%|██        | 458/2248 [00:37<03:59,  7.48it/s]
 20%|██        | 459/2248 [00:38<04:36,  6.48it/s]
 20%|██        | 460/2248 [00:38<04:36,  6.47it/s]
 21%|██        | 462/2248 [00:38<03:43,  8.00it/s]
 21%|██        | 463/2248 [00:38<04:04,  7.30it/s]
 21%|██        | 464/2248 [00:38<04:29,  6.61it/s]
 21%|██        | 465/2248 [00:38<04:29,  6.61it/s]
 21%|██        | 467/2248 [00:39<03:20,  8.87it/s]
 21%|██        | 469/2248 [00:39<03:24,  8.69it/s]
 21%|██        | 471/2248 [00:39<03:08,  9.44it/s]
 21%|██        | 473/2248 [00:39<03:15,  9.09it/s]
 21%|██        | 475/2248 [00:39<03:00,  9.81it/s]
 21%|██        | 477/2248 [00:40<03:10,  9.29it/s]
 21%|██▏       | 478/2248 [00:40<03:48,  7.75it/s]
 21%|██▏       | 479/2248 [00:40<04:19,  6.82it/s]
 21%|██▏       | 480/2248 [00:40<04:56,  5.97it/s]
 21%|██▏       | 481/2248 [00:41<05:17,  5.56it/s]
 22%|██▏       | 484/2248 [00:41<03:12,  9.15it/s]
 22%|██▏       | 487/2248 [00:41<02:55, 10.04it/s]
 22%|██▏       | 490/2248 [00:41<02:14, 13.10it/s]
 22%|██▏       | 495/2248 [00:41<01:48, 16.09it/s]
 22%|██▏       | 497/2248 [00:41<01:48, 16.08it/s]
 22%|██▏       | 499/2248 [00:42<02:30, 11.65it/s]
 22%|██▏       | 501/2248 [00:42<02:44, 10.65it/s]
 22%|██▏       | 503/2248 [00:42<02:36, 11.13it/s]
 23%|██▎       | 506/2248 [00:42<02:17, 12.71it/s]
 23%|██▎       | 508/2248 [00:42<02:25, 11.94it/s]
 23%|██▎       | 510/2248 [00:43<02:48, 10.30it/s]
 23%|██▎       | 512/2248 [00:43<02:58,  9.72it/s]
 23%|██▎       | 514/2248 [00:43<03:04,  9.40it/s]
 23%|██▎       | 516/2248 [00:43<02:44, 10.55it/s]
 23%|██▎       | 518/2248 [00:44<03:25,  8.42it/s]
 23%|██▎       | 520/2248 [00:44<02:59,  9.62it/s]
 23%|██▎       | 522/2248 [00:44<02:34, 11.16it/s]
 23%|██▎       | 527/2248 [00:44<01:46, 16.13it/s]
 24%|██▎       | 531/2248 [00:44<01:27, 19.58it/s]
 24%|██▍       | 534/2248 [00:44<01:36, 17.69it/s]
 24%|██▍       | 537/2248 [00:45<01:27, 19.48it/s]
 24%|██▍       | 543/2248 [00:45<01:01, 27.90it/s]
 24%|██▍       | 547/2248 [00:45<01:01, 27.45it/s]
 25%|██▍       | 552/2248 [00:45<00:53, 31.77it/s]
 25%|██▍       | 559/2248 [00:45<00:41, 40.46it/s]
 25%|██▌       | 565/2248 [00:45<00:38, 44.00it/s]
 25%|██▌       | 571/2248 [00:45<00:53, 31.27it/s]
 26%|██▌       | 575/2248 [00:46<01:33, 17.86it/s]
 26%|██▌       | 578/2248 [00:46<01:51, 14.99it/s]
 26%|██▌       | 581/2248 [00:47<02:05, 13.25it/s]
 26%|██▌       | 583/2248 [00:47<02:26, 11.38it/s]
 26%|██▌       | 585/2248 [00:47<02:51,  9.67it/s]
 26%|██▌       | 587/2248 [00:48<03:07,  8.85it/s]
 26%|██▌       | 589/2248 [00:48<03:12,  8.63it/s]
 26%|██▋       | 592/2248 [00:48<03:01,  9.11it/s]
 26%|██▋       | 594/2248 [00:48<02:39, 10.40it/s]
 27%|██▋       | 600/2248 [00:48<01:54, 14.43it/s]
 27%|██▋       | 603/2248 [00:49<02:02, 13.38it/s]
 27%|██▋       | 605/2248 [00:49<02:51,  9.56it/s]
 27%|██▋       | 607/2248 [00:50<03:26,  7.93it/s]
 27%|██▋       | 608/2248 [00:50<03:42,  7.36it/s]
 27%|██▋       | 609/2248 [00:50<03:58,  6.87it/s]
 27%|██▋       | 611/2248 [00:50<03:10,  8.62it/s]
 27%|██▋       | 616/2248 [00:50<01:47, 15.18it/s]
 28%|██▊       | 619/2248 [00:51<02:08, 12.70it/s]
 28%|██▊       | 621/2248 [00:51<02:27, 11.00it/s]
 28%|██▊       | 624/2248 [00:51<01:59, 13.64it/s]
 28%|██▊       | 628/2248 [00:51<01:46, 15.27it/s]
 28%|██▊       | 630/2248 [00:51<02:00, 13.42it/s]
 28%|██▊       | 632/2248 [00:52<02:04, 12.99it/s]
 28%|██▊       | 634/2248 [00:52<01:55, 13.95it/s]
 28%|██▊       | 638/2248 [00:52<01:43, 15.61it/s]
 28%|██▊       | 640/2248 [00:52<01:38, 16.41it/s]
 29%|██▊       | 642/2248 [00:52<01:45, 15.22it/s]
 29%|██▊       | 645/2248 [00:52<01:29, 17.98it/s]
 29%|██▉       | 650/2248 [00:52<01:26, 18.46it/s]
 29%|██▉       | 652/2248 [00:53<01:46, 15.02it/s]
 29%|██▉       | 654/2248 [00:53<02:13, 11.96it/s]
 29%|██▉       | 657/2248 [00:53<02:26, 10.85it/s]
 29%|██▉       | 659/2248 [00:53<02:24, 11.00it/s]
 29%|██▉       | 661/2248 [00:54<03:10,  8.32it/s]
 29%|██▉       | 663/2248 [00:54<02:59,  8.81it/s]
 30%|██▉       | 665/2248 [00:54<03:19,  7.95it/s]
 30%|██▉       | 667/2248 [00:55<02:52,  9.17it/s]
 30%|██▉       | 670/2248 [00:55<02:35, 10.15it/s]
 30%|██▉       | 673/2248 [00:55<02:29, 10.56it/s]
 30%|███       | 677/2248 [00:55<01:45, 14.88it/s]
 30%|███       | 679/2248 [00:55<01:57, 13.32it/s]
 30%|███       | 681/2248 [00:56<02:09, 12.10it/s]
 30%|███       | 683/2248 [00:56<02:35, 10.08it/s]
 30%|███       | 685/2248 [00:56<03:16,  7.96it/s]
 31%|███       | 686/2248 [00:56<03:30,  7.43it/s]
 31%|███       | 687/2248 [00:57<04:00,  6.50it/s]
 31%|███       | 689/2248 [00:57<03:05,  8.40it/s]
 31%|███       | 691/2248 [00:57<02:45,  9.39it/s]
 31%|███       | 693/2248 [00:57<02:26, 10.59it/s]
 31%|███       | 695/2248 [00:57<02:57,  8.75it/s]
 31%|███       | 697/2248 [00:58<02:57,  8.72it/s]
 31%|███       | 699/2248 [00:58<03:00,  8.60it/s]
 31%|███       | 701/2248 [00:58<02:34, 10.00it/s]
 31%|███▏      | 703/2248 [00:58<02:42,  9.49it/s]
 31%|███▏      | 705/2248 [00:59<03:10,  8.11it/s]
 32%|███▏      | 709/2248 [00:59<02:31, 10.19it/s]
 32%|███▏      | 711/2248 [00:59<02:39,  9.61it/s]
 32%|███▏      | 713/2248 [00:59<02:46,  9.23it/s]
 32%|███▏      | 715/2248 [01:00<02:57,  8.64it/s]
 32%|███▏      | 717/2248 [01:00<02:34,  9.90it/s]
 32%|███▏      | 719/2248 [01:00<02:37,  9.68it/s]
 32%|███▏      | 721/2248 [01:00<02:57,  8.62it/s]
 32%|███▏      | 723/2248 [01:00<02:31, 10.06it/s]
 32%|███▏      | 725/2248 [01:01<02:46,  9.16it/s]
 32%|███▏      | 727/2248 [01:01<03:00,  8.45it/s]
 32%|███▏      | 728/2248 [01:01<03:21,  7.54it/s]
 32%|███▏      | 730/2248 [01:01<02:40,  9.45it/s]
 33%|███▎      | 732/2248 [01:02<03:31,  7.16it/s]
 33%|███▎      | 733/2248 [01:02<04:01,  6.28it/s]
 33%|███▎      | 735/2248 [01:02<03:57,  6.36it/s]
 33%|███▎      | 736/2248 [01:02<04:16,  5.90it/s]
 33%|███▎      | 737/2248 [01:03<04:33,  5.52it/s]
 33%|███▎      | 739/2248 [01:03<03:35,  7.01it/s]
 33%|███▎      | 743/2248 [01:03<02:30,  9.99it/s]
 33%|███▎      | 745/2248 [01:03<02:37,  9.56it/s]
 33%|███▎      | 747/2248 [01:03<02:15, 11.09it/s]
 33%|███▎      | 751/2248 [01:03<01:34, 15.82it/s]
 33%|███▎      | 753/2248 [01:04<01:57, 12.75it/s]
 34%|███▎      | 755/2248 [01:04<02:33,  9.73it/s]
 34%|███▍      | 760/2248 [01:04<01:34, 15.68it/s]
 34%|███▍      | 763/2248 [01:05<01:56, 12.71it/s]
 34%|███▍      | 767/2248 [01:05<01:51, 13.26it/s]
 34%|███▍      | 769/2248 [01:05<01:50, 13.42it/s]
 34%|███▍      | 772/2248 [01:05<01:57, 12.57it/s]
 34%|███▍      | 774/2248 [01:06<02:39,  9.26it/s]
 35%|███▍      | 776/2248 [01:06<02:51,  8.60it/s]
 35%|███▍      | 779/2248 [01:06<02:19, 10.55it/s]
 35%|███▍      | 782/2248 [01:06<02:19, 10.54it/s]
 35%|███▍      | 784/2248 [01:07<02:39,  9.20it/s]
 35%|███▍      | 786/2248 [01:07<02:42,  8.98it/s]
 35%|███▌      | 790/2248 [01:07<01:53, 12.89it/s]
 35%|███▌      | 792/2248 [01:07<02:02, 11.90it/s]
 35%|███▌      | 794/2248 [01:07<02:01, 11.93it/s]
 35%|███▌      | 796/2248 [01:08<02:05, 11.53it/s]
 35%|███▌      | 798/2248 [01:08<02:21, 10.23it/s]
 36%|███▌      | 800/2248 [01:08<02:13, 10.84it/s]
 36%|███▌      | 803/2248 [01:08<02:05, 11.50it/s]
 36%|███▌      | 805/2248 [01:08<02:04, 11.56it/s]
 36%|███▌      | 807/2248 [01:09<01:55, 12.53it/s]
 36%|███▌      | 809/2248 [01:09<01:44, 13.79it/s]
 36%|███▋      | 815/2248 [01:09<01:16, 18.65it/s]
 36%|███▋      | 817/2248 [01:09<01:33, 15.37it/s]
 36%|███▋      | 819/2248 [01:09<01:32, 15.53it/s]
 37%|███▋      | 822/2248 [01:09<01:17, 18.32it/s]
 37%|███▋      | 827/2248 [01:09<00:56, 25.08it/s]
 37%|███▋      | 832/2248 [01:10<00:49, 28.83it/s]
 37%|███▋      | 839/2248 [01:10<00:37, 37.23it/s]
 38%|███▊      | 845/2248 [01:10<00:33, 41.68it/s]
 38%|███▊      | 853/2248 [01:10<00:27, 49.88it/s]
 38%|███▊      | 859/2248 [01:10<00:26, 51.45it/s]
 39%|███▊      | 866/2248 [01:10<00:30, 45.21it/s]
 39%|███▊      | 871/2248 [01:11<01:15, 18.34it/s]
 39%|███▉      | 875/2248 [01:11<01:28, 15.51it/s]
 39%|███▉      | 878/2248 [01:12<01:38, 13.84it/s]
 39%|███▉      | 881/2248 [01:12<01:39, 13.68it/s]
 39%|███▉      | 884/2248 [01:12<01:38, 13.91it/s]
 39%|███▉      | 886/2248 [01:12<01:48, 12.50it/s]
 40%|███▉      | 888/2248 [01:13<02:10, 10.45it/s]
 40%|███▉      | 890/2248 [01:13<02:30,  9.04it/s]
 40%|███▉      | 892/2248 [01:13<02:40,  8.46it/s]
 40%|███▉      | 894/2248 [01:14<02:53,  7.82it/s]
 40%|███▉      | 895/2248 [01:14<03:15,  6.91it/s]
 40%|███▉      | 896/2248 [01:14<03:26,  6.55it/s]
 40%|███▉      | 898/2248 [01:14<02:49,  7.96it/s]
 40%|███▉      | 899/2248 [01:14<03:06,  7.22it/s]
 40%|████      | 900/2248 [01:14<03:03,  7.33it/s]
 40%|████      | 902/2248 [01:15<03:20,  6.70it/s]
 40%|████      | 903/2248 [01:15<03:52,  5.79it/s]
 40%|████      | 905/2248 [01:15<03:09,  7.09it/s]
 40%|████      | 906/2248 [01:15<03:11,  6.99it/s]
 40%|████      | 908/2248 [01:16<02:57,  7.53it/s]
 40%|████      | 910/2248 [01:16<02:38,  8.43it/s]
 41%|████      | 912/2248 [01:16<02:23,  9.29it/s]
 41%|████      | 913/2248 [01:16<02:27,  9.06it/s]
 41%|████      | 914/2248 [01:16<02:48,  7.91it/s]
 41%|████      | 916/2248 [01:17<02:45,  8.03it/s]
 41%|████      | 918/2248 [01:17<02:26,  9.06it/s]
 41%|████      | 920/2248 [01:17<02:37,  8.42it/s]
 41%|████      | 921/2248 [01:17<02:45,  8.01it/s]
 41%|████      | 923/2248 [01:17<02:23,  9.21it/s]
 41%|████      | 924/2248 [01:18<03:09,  6.99it/s]
 41%|████      | 925/2248 [01:18<03:28,  6.34it/s]
 41%|████      | 927/2248 [01:18<03:13,  6.81it/s]
 41%|████▏     | 929/2248 [01:18<03:12,  6.85it/s]
 41%|████▏     | 931/2248 [01:19<03:15,  6.74it/s]
 42%|████▏     | 933/2248 [01:19<02:35,  8.47it/s]
 42%|████▏     | 935/2248 [01:19<03:11,  6.86it/s]
 42%|████▏     | 938/2248 [01:19<02:41,  8.12it/s]
 42%|████▏     | 940/2248 [01:20<02:43,  8.00it/s]
 42%|████▏     | 942/2248 [01:20<02:18,  9.46it/s]
 42%|████▏     | 944/2248 [01:20<02:28,  8.77it/s]
 42%|████▏     | 946/2248 [01:20<02:34,  8.45it/s]
 42%|████▏     | 948/2248 [01:20<02:29,  8.69it/s]
 42%|████▏     | 949/2248 [01:21<02:52,  7.55it/s]
 42%|████▏     | 951/2248 [01:21<02:23,  9.03it/s]
 42%|████▏     | 953/2248 [01:21<03:14,  6.67it/s]
 42%|████▏     | 955/2248 [01:21<02:38,  8.14it/s]
 43%|████▎     | 957/2248 [01:22<03:09,  6.81it/s]
 43%|████▎     | 958/2248 [01:22<03:24,  6.31it/s]
 43%|████▎     | 959/2248 [01:22<03:37,  5.93it/s]
 43%|████▎     | 960/2248 [01:22<03:53,  5.53it/s]
 43%|████▎     | 961/2248 [01:23<03:53,  5.51it/s]
 43%|████▎     | 962/2248 [01:23<03:58,  5.38it/s]
 43%|████▎     | 964/2248 [01:23<03:17,  6.50it/s]
 43%|████▎     | 966/2248 [01:23<02:56,  7.26it/s]
 43%|████▎     | 967/2248 [01:24<03:14,  6.57it/s]
 43%|████▎     | 969/2248 [01:24<02:58,  7.15it/s]
 43%|████▎     | 970/2248 [01:24<03:10,  6.72it/s]
 43%|████▎     | 972/2248 [01:24<02:35,  8.23it/s]
 43%|████▎     | 974/2248 [01:24<02:34,  8.25it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 314.41it/s]

[[np.int64(0), False, 11], [np.int64(1), False, 6], [np.int64(2), False, 9], [np.int64(3), False, 13], [np.int64(4), False, 6], [np.int64(5), False, 11], [np.int64(7), False, 12], [np.int64(8), False, 13], [np.int64(10), False, 5], [np.int64(12), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(11.9454, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9336, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [20:26<48:49, 59.79s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [20:26<33:30, 41.90s/it]

tensor(11.9464, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0230, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1227, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [20:26<10:50, 14.45s/it]

tensor(11.9644, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1346, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0060, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [20:26<05:06,  7.14s/it]

tensor(11.9699, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0178, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0276, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [20:26<02:25,  3.56s/it]

tensor(11.9527, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0856, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9483, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1327, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [20:27<01:10,  1.80s/it]

tensor(11.9512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1701, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1960, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [20:27<00:49,  1.30s/it]

tensor(11.9634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1929, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2036, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [20:27<00:18,  1.91it/s]

tensor(11.9549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0298, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9475, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2252, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [20:27<00:10,  3.18it/s]

tensor(11.9428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0288, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2370, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9413, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0282, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2476, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [20:28<00:06,  4.67it/s]

tensor(11.9428, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2535, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [20:28<00:04,  6.11it/s]

tensor(11.9440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2607, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9425, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2711, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [20:28<00:03,  7.15it/s]

tensor(11.9390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3002, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [20:28<00:03,  7.84it/s]

tensor(11.9322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3127, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3220, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [20:29<00:02,  8.06it/s]

tensor(11.9303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3318, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3380, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [20:29<00:02,  8.21it/s]

tensor(11.9301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9290, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3498, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [20:29<00:02,  8.40it/s]

tensor(11.9269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3527, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3542, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [20:29<00:02,  8.46it/s]

tensor(11.9232, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3578, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3645, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [20:30<00:01,  8.47it/s]

tensor(11.9211, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3664, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3675, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [20:30<00:01,  8.50it/s]

tensor(11.9195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3698, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9183, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3725, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [20:30<00:01,  8.39it/s]

tensor(11.9166, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3764, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [20:30<00:01,  8.42it/s]

tensor(11.9135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3795, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3826, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [20:30<00:00,  8.57it/s]

tensor(11.9109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3849, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3864, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [20:31<00:00,  8.52it/s]

tensor(11.9091, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3879, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3897, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [20:31<00:00,  8.30it/s]

tensor(11.9073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3909, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3889, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [20:31<00:00,  8.41it/s]

tensor(11.9056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3929, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [20:31<00:00,  4.11s/it]

tensor(11.9042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3943, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0020596981048583984
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 4
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.513844168847
NMI         : 0.493775594552
Runtime     : 1252.44 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed4

==============================================================================================================
PRAGA RUN | S2-E18 | seed=5
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 6.951e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():

tensor(16.0483, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0662, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8057, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:31,  9.48it/s]

tensor(16.0412, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7177, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.0048, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8356, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9650, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1385, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:29,  9.87it/s]

tensor(15.9216, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6087, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8794, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2295, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8403, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9867, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 10/300 [00:01<00:28, 10.22it/s]

tensor(15.8011, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8658, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7657, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8562, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7312, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9455, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:28, 10.19it/s]

tensor(15.6970, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6645, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3863, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6317, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7204, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 16/300 [00:01<00:27, 10.32it/s]

tensor(15.5993, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1204, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5672, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5794, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5345, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0932, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:27, 10.36it/s]

tensor(15.5010, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6541, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4662, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2590, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4297, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9035, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 22/300 [00:02<00:26, 10.37it/s]

tensor(15.3913, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5834, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3503, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2951, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3073, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0364, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:26, 10.34it/s]

tensor(15.2619, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8027, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2142, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5935, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1647, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4051, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 28/300 [00:02<00:26, 10.35it/s]

tensor(15.1136, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2355, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0612, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0836, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9474, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:26, 10.36it/s]

tensor(14.9550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8253, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7160, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6181, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█▏        | 34/300 [00:03<00:25, 10.38it/s]

tensor(14.7936, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7384, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4527, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3829, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:25, 10.41it/s]

tensor(14.6241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2668, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2191, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 40/300 [00:03<00:25, 10.34it/s]

tensor(14.4442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1769, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1412, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3240, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1106, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:24, 10.38it/s]

tensor(14.2647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0852, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0658, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0513, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 46/300 [00:04<00:24, 10.40it/s]

tensor(14.0883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0353, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:24, 10.38it/s]

tensor(13.9205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8689, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:23, 10.38it/s]

tensor(13.7732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6882, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:23, 10.38it/s]

tensor(13.6485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5713, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:23, 10.36it/s]

tensor(13.5331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4596, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:05<00:23, 10.31it/s]

tensor(13.4254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3933, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:22, 10.28it/s]

tensor(13.3331, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2779, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:22, 10.34it/s]

tensor(13.2516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:06<00:22, 10.36it/s]

tensor(13.1732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1466, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1207, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:06<00:22, 10.31it/s]

tensor(13.0952, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:07<00:21, 10.31it/s]

tensor(13.0222, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9757, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:07<00:21, 10.39it/s]

tensor(12.9536, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9316, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9102, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:07<00:21, 10.37it/s]

tensor(12.8893, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8494, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:20, 10.40it/s]

tensor(12.8300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8113, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:08<00:20, 10.39it/s]

tensor(12.7753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:08<00:20, 10.32it/s]

tensor(12.7243, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.7082, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:19, 10.33it/s]

tensor(12.6769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6474, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:19, 10.30it/s]

tensor(12.6337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6202, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.6073, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:09<00:19, 10.27it/s]

tensor(12.5948, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.5828, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([180, 105, 119, 246, 142,  68, 120, 133,  73, 257,  59, 453,  64, 229])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:24, 26.50it/s]
  0%|          | 9/2248 [00:00<01:47, 20.82it/s]
  1%|          | 12/2248 [00:00<01:42, 21.91it/s]
  1%|          | 18/2248 [00:00<01:10, 31.69it/s]
  1%|          | 24/2248 [00:00<00:56, 39.30it/s]
  1%|▏         | 29/2248 [00:01<01:35, 23.33it/s]
  2%|▏         | 36/2248 [00:01<01:38, 22.35it/s]
  2%|▏         | 39/2248 [00:02<02:43, 13.55it/s]
  2%|▏         | 42/2248 [00:02<02:29, 14.78it/s]
  2%|▏         | 45/2248 [00:02<02:58, 12.34it/s]
  2%|▏         | 51/2248 [00:02<02:02, 17.99it/s]
  2%|▏         | 54/2248 [00:03<02:33, 14.34it/s]
  3%|▎         | 57/2248 [00:03<02:58, 12.26it/s]
  3%|▎         | 62/2248 [00:03<02:43, 13.40it/s]
  3%|▎         | 64/2248 [00:03<02:38, 13.78it/s]
  3%|▎         | 66/2248 [00:04<03:28, 10.49it/s]
  3%|▎         | 72/2248 [00:04<02:10, 16.71it/s]
  3%|▎         | 77/2248 [00:04<01:39, 21.81it/s]
  4%|▎         | 81/2248 [00:04<02:29, 14.53it/s]
  4%|▎         | 84/2248 [00:05<03:37,  9.96it/s]
  4%|▍         | 86/2248 [00:05<03:24, 10.57it/s]
  4%|▍         | 88/2248 [00:05<03:49,  9.40it/s]
  4%|▍         | 90/2248 [00:06<03:54,  9.20it/s]
  4%|▍         | 92/2248 [00:06<03:29, 10.30it/s]
  4%|▍         | 94/2248 [00:06<03:57,  9.07it/s]
  4%|▍         | 96/2248 [00:06<04:15,  8.43it/s]
  4%|▍         | 98/2248 [00:07<05:09,  6.95it/s]
  4%|▍         | 99/2248 [00:07<05:08,  6.96it/s]
  4%|▍         | 101/2248 [00:07<04:53,  7.33it/s]
  5%|▍         | 102/2248 [00:07<05:45,  6.21it/s]
  5%|▍         | 104/2248 [00:08<04:27,  8.03it/s]
  5%|▍         | 106/2248 [00:08<03:34, 10.00it/s]
  5%|▍         | 108/2248 [00:08<03:32, 10.06it/s]
  5%|▍         | 110/2248 [00:08<05:09,  6.91it/s]
  5%|▍         | 112/2248 [00:09<04:47,  7.43it/s]
  5%|▌         | 114/2248 [00:09<05:11,  6.85it/s]
  5%|▌         | 116/2248 [00:09<04:12,  8.45it/s]
  5%|▌         | 118/2248 [00:10<07:09,  4.96it/s]
  5%|▌         | 119/2248 [00:10<07:05,  5.01it/s]
  5%|▌         | 120/2248 [00:11<10:37,  3.34it/s]
  5%|▌         | 122/2248 [00:11<11:30,  3.08it/s]
  5%|▌         | 123/2248 [00:12<10:56,  3.24it/s]
  6%|▌         | 125/2248 [00:12<07:31,  4.70it/s]
  6%|▌         | 126/2248 [00:13<11:12,  3.16it/s]
  6%|▌         | 127/2248 [00:13<14:09,  2.50it/s]
  6%|▌         | 128/2248 [00:14<17:11,  2.05it/s]
  6%|▌         | 130/2248 [00:14<10:52,  3.25it/s]
  6%|▌         | 132/2248 [00:14<08:40,  4.07it/s]
 33%|███▎      | 100/300 [00:27<00:19, 10.27it/s]]
  6%|▌         | 135/2248 [00:15<07:59,  4.41it/s]
  6%|▌         | 136/2248 [00:16<10:56,  3.22it/s]
  6%|▌         | 138/2248 [00:16<10:04,  3.49it/s]
  6%|▌         | 140/2248 [00:16<07:12,  4.87it/s]
  6%|▋         | 142/2248 [00:16<05:41,  6.16it/s]
  6%|▋         | 145/2248 [00:17<07:30,  4.67it/s]
  7%|▋         | 148/2248 [00:18<06:05,  5.74it/s]
  7%|▋         | 151/2248 [00:18<07:23,  4.72it/s]
  7%|▋         | 153/2248 [00:19<06:05,  5.73it/s]
  7%|▋         | 156/2248 [00:19<07:07,  4.90it/s]
  7%|▋         | 157/2248 [00:20<09:50,  3.54it/s]
  7%|▋         | 158/2248 [00:21<11:09,  3.12it/s]
  7%|▋         | 159/2248 [00:21<11:00,  3.16it/s]
  7%|▋         | 160/2248 [00:21<11:31,  3.02it/s]
  7%|▋         | 162/2248 [00:22<10:58,  3.17it/s]
  7%|▋         | 164/2248 [00:22<07:44,  4.49it/s]
  7%|▋         | 165/2248 [00:22<09:03,  3.83it/s]
  7%|▋         | 167/2248 [00:22<06:24,  5.41it/s]
  8%|▊         | 169/2248 [00:23<08:48,  3.93it/s]
  8%|▊         | 170/2248 [00:23<08:49,  3.92it/s]
  8%|▊         | 171/2248 [00:24<07:58,  4.34it/s]
  8%|▊         | 172/2248 [00:24<07:10,  4.82it/s]
  8%|▊         | 173/2248 [00:24<11:07,  3.11it/s]
  8%|▊         | 174/2248 [00:25<10:28,  3.30it/s]
  8%|▊         | 176/2248 [00:25<11:53,  2.91it/s]
  8%|▊         | 177/2248 [00:26<11:17,  3.06it/s]
  8%|▊         | 178/2248 [00:26<14:55,  2.31it/s]
  8%|▊         | 179/2248 [00:27<13:15,  2.60it/s]
  8%|▊         | 181/2248 [00:27<08:25,  4.09it/s]
  8%|▊         | 183/2248 [00:27<06:24,  5.37it/s]
  8%|▊         | 184/2248 [00:27<07:33,  4.55it/s]
  8%|▊         | 186/2248 [00:28<06:54,  4.97it/s]
  8%|▊         | 187/2248 [00:28<08:09,  4.21it/s]
  8%|▊         | 188/2248 [00:28<07:52,  4.36it/s]
  8%|▊         | 190/2248 [00:29<06:18,  5.44it/s]
  8%|▊         | 191/2248 [00:29<05:50,  5.87it/s]
  9%|▊         | 192/2248 [00:29<05:54,  5.80it/s]
  9%|▊         | 194/2248 [00:29<04:34,  7.49it/s]
  9%|▊         | 195/2248 [00:29<06:12,  5.51it/s]
  9%|▉         | 197/2248 [00:30<05:43,  5.97it/s]
  9%|▉         | 198/2248 [00:30<05:25,  6.29it/s]
  9%|▉         | 200/2248 [00:30<04:26,  7.68it/s]
  9%|▉         | 202/2248 [00:30<05:45,  5.92it/s]
  9%|▉         | 203/2248 [00:31<05:26,  6.27it/s]
  9%|▉         | 204/2248 [00:31<06:03,  5.63it/s]
  9%|▉         | 205/2248 [00:32<10:39,  3.20it/s]
  9%|▉         | 207/2248 [00:32<11:25,  2.98it/s]
  9%|▉         | 209/2248 [00:33<12:02,  2.82it/s]
  9%|▉         | 210/2248 [00:33<11:15,  3.02it/s]
  9%|▉         | 211/2248 [00:34<12:09,  2.79it/s]
  9%|▉         | 212/2248 [00:34<11:23,  2.98it/s]
  9%|▉         | 213/2248 [00:34<10:05,  3.36it/s]
 10%|▉         | 215/2248 [00:34<06:40,  5.07it/s]
 10%|▉         | 218/2248 [00:34<04:01,  8.39it/s]
 10%|▉         | 220/2248 [00:35<03:37,  9.34it/s]
 10%|▉         | 222/2248 [00:35<03:17, 10.25it/s]
 10%|▉         | 224/2248 [00:35<02:52, 11.73it/s]
 10%|█         | 227/2248 [00:35<02:25, 13.90it/s]
 10%|█         | 234/2248 [00:35<01:20, 25.17it/s]
 11%|█         | 238/2248 [00:35<01:24, 23.71it/s]
 11%|█         | 243/2248 [00:35<01:08, 29.19it/s]
 11%|█         | 248/2248 [00:35<00:59, 33.87it/s]
 11%|█         | 252/2248 [00:36<01:23, 23.99it/s]
 11%|█▏        | 258/2248 [00:36<01:05, 30.38it/s]
 12%|█▏        | 263/2248 [00:36<01:09, 28.48it/s]
 12%|█▏        | 267/2248 [00:36<01:19, 24.83it/s]
 12%|█▏        | 270/2248 [00:37<02:18, 14.27it/s]
 12%|█▏        | 273/2248 [00:38<03:35,  9.18it/s]
 12%|█▏        | 275/2248 [00:38<03:54,  8.41it/s]
 12%|█▏        | 277/2248 [00:38<03:50,  8.55it/s]
 12%|█▏        | 279/2248 [00:38<03:30,  9.37it/s]
 12%|█▎        | 281/2248 [00:38<03:09, 10.39it/s]
 13%|█▎        | 283/2248 [00:39<05:55,  5.52it/s]
 13%|█▎        | 285/2248 [00:39<05:30,  5.95it/s]
 13%|█▎        | 286/2248 [00:40<05:34,  5.87it/s]
 13%|█▎        | 287/2248 [00:40<08:34,  3.81it/s]
 13%|█▎        | 289/2248 [00:41<07:30,  4.35it/s]
 13%|█▎        | 290/2248 [00:41<10:30,  3.10it/s]
 13%|█▎        | 291/2248 [00:42<13:19,  2.45it/s]
 13%|█▎        | 292/2248 [00:42<12:46,  2.55it/s]
 13%|█▎        | 294/2248 [00:43<08:32,  3.82it/s]
 13%|█▎        | 295/2248 [00:43<08:23,  3.88it/s]
 13%|█▎        | 296/2248 [00:43<08:10,  3.98it/s]
 13%|█▎        | 298/2248 [00:43<06:20,  5.12it/s]
 13%|█▎        | 300/2248 [00:43<04:51,  6.68it/s]
 13%|█▎        | 302/2248 [00:44<04:01,  8.07it/s]
 14%|█▎        | 304/2248 [00:44<05:09,  6.28it/s]
 14%|█▎        | 306/2248 [00:45<07:55,  4.08it/s]
 14%|█▎        | 307/2248 [00:45<09:22,  3.45it/s]
 14%|█▎        | 308/2248 [00:46<10:23,  3.11it/s]
 14%|█▎        | 309/2248 [00:46<10:50,  2.98it/s]
 14%|█▍        | 310/2248 [00:46<10:33,  3.06it/s]
 14%|█▍        | 312/2248 [00:47<07:44,  4.17it/s]
 14%|█▍        | 313/2248 [00:47<08:47,  3.67it/s]
 14%|█▍        | 314/2248 [00:47<09:43,  3.31it/s]
 14%|█▍        | 315/2248 [00:48<10:06,  3.19it/s]
 14%|█▍        | 317/2248 [00:48<06:33,  4.91it/s]
 14%|█▍        | 319/2248 [00:48<04:54,  6.55it/s]
 14%|█▍        | 320/2248 [00:48<06:37,  4.85it/s]
 14%|█▍        | 322/2248 [00:49<05:56,  5.41it/s]
 14%|█▍        | 323/2248 [00:49<09:34,  3.35it/s]
 14%|█▍        | 325/2248 [00:50<09:15,  3.46it/s]
 15%|█▍        | 327/2248 [00:50<06:59,  4.58it/s]
 15%|█▍        | 329/2248 [00:50<05:22,  5.96it/s]
 15%|█▍        | 332/2248 [00:51<05:40,  5.63it/s]
 15%|█▍        | 335/2248 [00:51<03:59,  8.00it/s]
 15%|█▌        | 339/2248 [00:52<05:01,  6.32it/s]
 15%|█▌        | 341/2248 [00:52<04:48,  6.62it/s]
 15%|█▌        | 343/2248 [00:53<06:40,  4.76it/s]
 15%|█▌        | 344/2248 [00:54<09:08,  3.47it/s]
 15%|█▌        | 345/2248 [00:54<09:50,  3.22it/s]
 15%|█▌        | 346/2248 [00:54<08:31,  3.72it/s]
 15%|█▌        | 347/2248 [00:55<09:23,  3.37it/s]
 15%|█▌        | 348/2248 [00:55<09:05,  3.48it/s]
 16%|█▌        | 349/2248 [00:55<09:09,  3.45it/s]
 16%|█▌        | 350/2248 [00:55<09:17,  3.40it/s]
 16%|█▌        | 352/2248 [00:55<06:05,  5.19it/s]
 16%|█▌        | 353/2248 [00:56<07:13,  4.37it/s]
 16%|█▌        | 354/2248 [00:56<06:27,  4.89it/s]
 16%|█▌        | 356/2248 [00:56<05:06,  6.17it/s]
 16%|█▌        | 358/2248 [00:56<03:47,  8.29it/s]
 16%|█▌        | 360/2248 [00:56<03:33,  8.86it/s]
 16%|█▌        | 362/2248 [00:57<05:27,  5.75it/s]
 16%|█▌        | 364/2248 [00:58<06:00,  5.23it/s]
 16%|█▋        | 366/2248 [00:58<04:40,  6.72it/s]
 16%|█▋        | 368/2248 [00:58<05:39,  5.54it/s]
 16%|█▋        | 370/2248 [00:58<04:29,  6.97it/s]
 17%|█▋        | 372/2248 [00:59<07:13,  4.33it/s]
 17%|█▋        | 373/2248 [01:00<10:26,  2.99it/s]
 17%|█▋        | 374/2248 [01:00<08:57,  3.49it/s]
 17%|█▋        | 379/2248 [01:01<06:41,  4.66it/s]
 17%|█▋        | 381/2248 [01:01<05:28,  5.68it/s]
 17%|█▋        | 384/2248 [01:01<04:14,  7.33it/s]
 17%|█▋        | 386/2248 [01:01<03:46,  8.22it/s]
 17%|█▋        | 388/2248 [01:02<04:07,  7.51it/s]
 17%|█▋        | 390/2248 [01:02<05:47,  5.34it/s]
 17%|█▋        | 392/2248 [01:03<05:53,  5.25it/s]
 17%|█▋        | 393/2248 [01:03<07:37,  4.06it/s]
 18%|█▊        | 394/2248 [01:04<10:41,  2.89it/s]
 18%|█▊        | 395/2248 [01:04<10:37,  2.91it/s]
 18%|█▊        | 397/2248 [01:04<07:12,  4.28it/s]
 18%|█▊        | 399/2248 [01:05<05:17,  5.83it/s]
 18%|█▊        | 401/2248 [01:05<05:01,  6.13it/s]
 18%|█▊        | 404/2248 [01:05<03:27,  8.88it/s]
 18%|█▊        | 406/2248 [01:05<02:58, 10.34it/s]
 18%|█▊        | 408/2248 [01:05<03:17,  9.30it/s]
 18%|█▊        | 411/2248 [01:05<02:26, 12.54it/s]
 18%|█▊        | 415/2248 [01:06<02:04, 14.67it/s]
 19%|█▊        | 417/2248 [01:06<02:49, 10.79it/s]
 19%|█▊        | 419/2248 [01:06<02:31, 12.08it/s]
 19%|█▉        | 424/2248 [01:06<02:12, 13.80it/s]
 19%|█▉        | 426/2248 [01:07<02:08, 14.21it/s]
 19%|█▉        | 428/2248 [01:07<02:56, 10.31it/s]
 19%|█▉        | 430/2248 [01:07<03:20,  9.09it/s]
 19%|█▉        | 434/2248 [01:07<02:16, 13.25it/s]
 19%|█▉        | 436/2248 [01:08<04:27,  6.77it/s]
 19%|█▉        | 438/2248 [01:08<04:19,  6.98it/s]
 20%|█▉        | 440/2248 [01:09<06:41,  4.51it/s]
 20%|█▉        | 443/2248 [01:09<04:44,  6.35it/s]
 20%|█▉        | 445/2248 [01:10<06:39,  4.51it/s]
 20%|█▉        | 447/2248 [01:11<08:31,  3.52it/s]
 20%|█▉        | 448/2248 [01:12<11:03,  2.71it/s]
 20%|██        | 450/2248 [01:13<11:21,  2.64it/s]
 20%|██        | 453/2248 [01:13<07:58,  3.75it/s]
 20%|██        | 454/2248 [01:13<07:56,  3.76it/s]
 20%|██        | 455/2248 [01:14<08:04,  3.70it/s]
 20%|██        | 457/2248 [01:14<09:13,  3.24it/s]
 20%|██        | 459/2248 [01:15<07:29,  3.98it/s]
 20%|██        | 460/2248 [01:15<07:36,  3.91it/s]
 21%|██        | 462/2248 [01:15<06:01,  4.94it/s]
 21%|██        | 463/2248 [01:15<06:04,  4.89it/s]
 21%|██        | 464/2248 [01:15<05:39,  5.25it/s]
 21%|██        | 466/2248 [01:16<04:13,  7.04it/s]
 21%|██        | 467/2248 [01:16<04:58,  5.97it/s]
 21%|██        | 469/2248 [01:16<04:12,  7.05it/s]
 21%|██        | 471/2248 [01:16<03:30,  8.44it/s]
 21%|██        | 472/2248 [01:17<06:48,  4.35it/s]
 21%|██        | 475/2248 [01:18<07:25,  3.98it/s]
 21%|██        | 476/2248 [01:18<10:04,  2.93it/s]
 21%|██        | 477/2248 [01:19<12:28,  2.36it/s]
 21%|██▏       | 478/2248 [01:19<10:48,  2.73it/s]
 21%|██▏       | 479/2248 [01:20<13:38,  2.16it/s]
 21%|██▏       | 480/2248 [01:21<13:39,  2.16it/s]
 21%|██▏       | 481/2248 [01:21<12:42,  2.32it/s]
 21%|██▏       | 482/2248 [01:21<13:23,  2.20it/s]
 22%|██▏       | 485/2248 [01:22<07:37,  3.85it/s]
 22%|██▏       | 486/2248 [01:23<10:50,  2.71it/s]
 22%|██▏       | 487/2248 [01:23<13:46,  2.13it/s]
 22%|██▏       | 488/2248 [01:24<15:56,  1.84it/s]
 22%|██▏       | 490/2248 [01:24<10:04,  2.91it/s]
 22%|██▏       | 491/2248 [01:25<09:42,  3.02it/s]
 22%|██▏       | 492/2248 [01:25<11:08,  2.63it/s]
 22%|██▏       | 494/2248 [01:25<07:12,  4.06it/s]
 22%|██▏       | 495/2248 [01:26<08:50,  3.31it/s]
 22%|██▏       | 497/2248 [01:26<06:01,  4.84it/s]
 22%|██▏       | 498/2248 [01:26<05:52,  4.96it/s]
 22%|██▏       | 499/2248 [01:27<09:06,  3.20it/s]
 22%|██▏       | 500/2248 [01:27<11:55,  2.44it/s]
 22%|██▏       | 502/2248 [01:28<08:33,  3.40it/s]
 22%|██▏       | 504/2248 [01:28<05:53,  4.94it/s]
 23%|██▎       | 506/2248 [01:28<05:23,  5.38it/s]
 23%|██▎       | 508/2248 [01:28<05:11,  5.59it/s]
 23%|██▎       | 509/2248 [01:29<08:21,  3.47it/s]
 23%|██▎       | 510/2248 [01:29<07:52,  3.68it/s]
 23%|██▎       | 513/2248 [01:30<07:33,  3.83it/s]
 23%|██▎       | 514/2248 [01:30<07:57,  3.64it/s]
 23%|██▎       | 515/2248 [01:31<09:04,  3.18it/s]
 23%|██▎       | 516/2248 [01:31<08:58,  3.22it/s]
 23%|██▎       | 517/2248 [01:32<10:07,  2.85it/s]
 23%|██▎       | 518/2248 [01:32<13:19,  2.16it/s]
 23%|██▎       | 519/2248 [01:33<15:31,  1.86it/s]
 23%|██▎       | 520/2248 [01:33<13:08,  2.19it/s]
 23%|██▎       | 522/2248 [01:34<08:08,  3.53it/s]
 23%|██▎       | 525/2248 [01:34<04:43,  6.08it/s]
 23%|██▎       | 527/2248 [01:34<04:30,  6.36it/s]
 24%|██▎       | 529/2248 [01:34<03:36,  7.95it/s]
 24%|██▎       | 532/2248 [01:34<02:33, 11.20it/s]
 24%|██▍       | 534/2248 [01:35<03:27,  8.28it/s]
 24%|██▍       | 536/2248 [01:35<02:58,  9.57it/s]
 24%|██▍       | 538/2248 [01:35<02:32, 11.19it/s]
 24%|██▍       | 544/2248 [01:35<01:53, 14.95it/s]
 24%|██▍       | 546/2248 [01:35<01:55, 14.68it/s]
 24%|██▍       | 550/2248 [01:35<01:29, 18.90it/s]
 25%|██▍       | 553/2248 [01:36<01:37, 17.33it/s]
 25%|██▍       | 555/2248 [01:36<01:52, 15.07it/s]
 25%|██▍       | 557/2248 [01:36<01:48, 15.65it/s]
 25%|██▌       | 563/2248 [01:36<01:08, 24.51it/s]
 25%|██▌       | 569/2248 [01:36<00:52, 32.05it/s]
 25%|██▌       | 573/2248 [01:37<02:50,  9.82it/s]
 26%|██▌       | 576/2248 [01:37<02:48,  9.93it/s]
 26%|██▌       | 579/2248 [01:38<03:40,  7.57it/s]
 26%|██▌       | 581/2248 [01:38<03:23,  8.20it/s]
 26%|██▌       | 583/2248 [01:39<04:04,  6.80it/s]
 26%|██▌       | 585/2248 [01:39<03:32,  7.83it/s]
 26%|██▌       | 587/2248 [01:39<03:04,  9.01it/s]
 26%|██▌       | 589/2248 [01:39<02:49,  9.76it/s]
 26%|██▋       | 591/2248 [01:39<02:27, 11.27it/s]
 26%|██▋       | 593/2248 [01:40<02:42, 10.21it/s]
 27%|██▋       | 596/2248 [01:40<02:10, 12.68it/s]
 27%|██▋       | 599/2248 [01:40<03:04,  8.92it/s]
 27%|██▋       | 601/2248 [01:40<02:44, 10.03it/s]
 27%|██▋       | 603/2248 [01:41<03:27,  7.91it/s]
 27%|██▋       | 605/2248 [01:41<05:15,  5.20it/s]
 27%|██▋       | 606/2248 [01:42<05:44,  4.77it/s]
 27%|██▋       | 607/2248 [01:42<06:41,  4.08it/s]
 27%|██▋       | 608/2248 [01:43<09:06,  3.00it/s]
 27%|██▋       | 609/2248 [01:44<11:25,  2.39it/s]
 27%|██▋       | 610/2248 [01:44<10:50,  2.52it/s]
 27%|██▋       | 612/2248 [01:44<07:03,  3.87it/s]
 27%|██▋       | 616/2248 [01:44<04:12,  6.46it/s]
 27%|██▋       | 617/2248 [01:44<04:20,  6.25it/s]
 27%|██▋       | 618/2248 [01:45<04:18,  6.31it/s]
 28%|██▊       | 621/2248 [01:45<03:10,  8.53it/s]
 28%|██▊       | 623/2248 [01:45<02:51,  9.45it/s]
 28%|██▊       | 625/2248 [01:45<02:24, 11.21it/s]
 28%|██▊       | 628/2248 [01:45<02:14, 12.05it/s]
 28%|██▊       | 630/2248 [01:45<02:28, 10.87it/s]
 28%|██▊       | 632/2248 [01:46<02:41, 10.03it/s]
 28%|██▊       | 634/2248 [01:46<02:20, 11.52it/s]
 28%|██▊       | 636/2248 [01:46<02:29, 10.76it/s]
 28%|██▊       | 638/2248 [01:46<02:43,  9.82it/s]
 28%|██▊       | 640/2248 [01:46<02:32, 10.58it/s]
 29%|██▊       | 642/2248 [01:47<02:49,  9.49it/s]
 29%|██▊       | 645/2248 [01:47<02:51,  9.33it/s]
 29%|██▉       | 647/2248 [01:47<02:32, 10.53it/s]
 29%|██▉       | 650/2248 [01:47<02:08, 12.45it/s]
 29%|██▉       | 652/2248 [01:48<03:25,  7.77it/s]
 29%|██▉       | 654/2248 [01:48<03:48,  6.96it/s]
 29%|██▉       | 656/2248 [01:48<03:13,  8.24it/s]
 29%|██▉       | 658/2248 [01:49<03:55,  6.76it/s]
 29%|██▉       | 660/2248 [01:49<04:18,  6.14it/s]
 29%|██▉       | 661/2248 [01:50<05:14,  5.05it/s]
 29%|██▉       | 662/2248 [01:50<04:43,  5.59it/s]
 29%|██▉       | 663/2248 [01:50<08:16,  3.19it/s]
 30%|██▉       | 665/2248 [01:51<09:17,  2.84it/s]
 30%|██▉       | 667/2248 [01:51<06:33,  4.02it/s]
 30%|██▉       | 669/2248 [01:52<04:51,  5.41it/s]
 30%|██▉       | 671/2248 [01:52<05:56,  4.42it/s]
 30%|██▉       | 673/2248 [01:52<04:46,  5.50it/s]
 30%|███       | 676/2248 [01:52<03:27,  7.59it/s]
 30%|███       | 678/2248 [01:53<05:22,  4.86it/s]
 30%|███       | 680/2248 [01:53<04:15,  6.13it/s]
 30%|███       | 682/2248 [01:54<06:09,  4.24it/s]
 30%|███       | 683/2248 [01:55<08:35,  3.04it/s]
 30%|███       | 684/2248 [01:55<07:58,  3.27it/s]
 30%|███       | 685/2248 [01:56<08:59,  2.89it/s]
 31%|███       | 686/2248 [01:56<09:44,  2.67it/s]
 31%|███       | 688/2248 [01:57<09:28,  2.74it/s]
 31%|███       | 690/2248 [01:57<06:36,  3.93it/s]
 31%|███       | 691/2248 [01:57<06:10,  4.21it/s]
 31%|███       | 692/2248 [01:58<08:03,  3.22it/s]
 31%|███       | 694/2248 [01:58<05:36,  4.62it/s]
 31%|███       | 695/2248 [01:58<05:40,  4.55it/s]
 31%|███       | 696/2248 [01:58<05:24,  4.79it/s]
 31%|███       | 698/2248 [01:58<03:59,  6.47it/s]
 31%|███       | 699/2248 [01:59<04:50,  5.32it/s]
 31%|███       | 700/2248 [01:59<04:47,  5.39it/s]
 31%|███       | 702/2248 [01:59<04:16,  6.04it/s]
 31%|███▏      | 704/2248 [02:00<05:00,  5.13it/s]
 31%|███▏      | 706/2248 [02:00<03:43,  6.90it/s]
 31%|███▏      | 708/2248 [02:00<02:58,  8.64it/s]
 32%|███▏      | 710/2248 [02:00<03:14,  7.92it/s]
 32%|███▏      | 712/2248 [02:00<02:45,  9.30it/s]
 32%|███▏      | 714/2248 [02:01<02:38,  9.67it/s]
 32%|███▏      | 716/2248 [02:01<02:25, 10.51it/s]
 32%|███▏      | 718/2248 [02:01<02:20, 10.86it/s]
 32%|███▏      | 721/2248 [02:01<02:45,  9.22it/s]
 32%|███▏      | 723/2248 [02:01<02:30, 10.11it/s]
 32%|███▏      | 726/2248 [02:01<01:55, 13.19it/s]
 32%|███▏      | 728/2248 [02:02<02:25, 10.43it/s]
 32%|███▏      | 730/2248 [02:02<02:29, 10.18it/s]
 33%|███▎      | 732/2248 [02:02<02:35,  9.74it/s]
 33%|███▎      | 734/2248 [02:03<04:14,  5.94it/s]
 33%|███▎      | 735/2248 [02:03<05:29,  4.60it/s]
 33%|███▎      | 736/2248 [02:04<05:45,  4.38it/s]
 33%|███▎      | 737/2248 [02:04<06:45,  3.72it/s]
 33%|███▎      | 738/2248 [02:04<06:28,  3.89it/s]
 33%|███▎      | 739/2248 [02:04<05:36,  4.48it/s]
 33%|███▎      | 741/2248 [02:05<03:59,  6.29it/s]
 33%|███▎      | 742/2248 [02:05<04:37,  5.44it/s]
 33%|███▎      | 743/2248 [02:05<05:45,  4.36it/s]
 33%|███▎      | 744/2248 [02:05<05:28,  4.58it/s]
 33%|███▎      | 746/2248 [02:05<03:49,  6.54it/s]
 33%|███▎      | 748/2248 [02:06<03:52,  6.45it/s]
 33%|███▎      | 749/2248 [02:06<05:29,  4.55it/s]
 33%|███▎      | 751/2248 [02:07<05:10,  4.81it/s]
 33%|███▎      | 752/2248 [02:07<07:08,  3.50it/s]
 34%|███▎      | 754/2248 [02:08<07:54,  3.15it/s]
 34%|███▎      | 757/2248 [02:08<04:44,  5.24it/s]
 34%|███▍      | 759/2248 [02:08<03:41,  6.72it/s]
 34%|███▍      | 761/2248 [02:09<04:41,  5.29it/s]
 34%|███▍      | 763/2248 [02:09<05:17,  4.67it/s]
 34%|███▍      | 765/2248 [02:09<04:13,  5.86it/s]
 34%|███▍      | 767/2248 [02:10<04:22,  5.64it/s]
 34%|███▍      | 772/2248 [02:10<03:07,  7.86it/s]
 34%|███▍      | 773/2248 [02:11<03:52,  6.35it/s]
 34%|███▍      | 774/2248 [02:11<05:14,  4.69it/s]
 34%|███▍      | 775/2248 [02:11<06:06,  4.02it/s]
 35%|███▍      | 776/2248 [02:12<07:37,  3.22it/s]
 35%|███▍      | 778/2248 [02:12<06:00,  4.07it/s]
 35%|███▍      | 779/2248 [02:12<05:21,  4.57it/s]
 35%|███▍      | 782/2248 [02:13<04:27,  5.47it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 266.67it/s]

[[np.int64(0), False, 9], [np.int64(1), False, 11], [np.int64(2), False, 8], [np.int64(3), False, 11], [np.int64(4), False, 8], [np.int64(5), False, 0], [np.int64(6), False, 11], [np.int64(7), False, 13], [np.int64(9), False, 13], [np.int64(10), False, 12]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5713, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9138, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [06:30<3:43:12, 67.30s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [06:30<2:57:28, 53.78s/it]

tensor(12.5581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9446, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9940, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▍      | 104/300 [06:31<1:43:36, 31.71s/it]

tensor(12.5377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0706, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5352, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1586, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [06:31<55:55, 17.30s/it]

tensor(12.5378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2383, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3107, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 108/300 [06:31<28:50,  9.02s/it]

tensor(12.5519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3929, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4712, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 110/300 [06:31<14:34,  4.60s/it]

tensor(12.5668, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5402, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6017, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [06:32<05:15,  1.69s/it]

tensor(12.5722, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6561, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5697, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7020, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [06:32<02:44,  1.12it/s]

tensor(12.5647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7466, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7752, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [06:32<01:31,  2.01it/s]

tensor(12.5490, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8007, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8221, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [06:32<00:55,  3.28it/s]

tensor(12.5199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8469, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8670, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [06:32<00:45,  4.00it/s]

tensor(12.4829, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8924, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9155, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [06:33<00:29,  6.03it/s]

tensor(12.4481, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9355, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9487, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████▏     | 124/300 [06:33<00:26,  6.55it/s]

tensor(12.4157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9597, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4003, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9744, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [06:33<00:22,  7.56it/s]

tensor(12.3858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9900, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3725, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0090, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [06:33<00:22,  7.75it/s]

tensor(12.3603, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0281, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0408, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [06:34<00:20,  8.11it/s]

tensor(12.3392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0584, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0757, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [06:34<00:20,  8.12it/s]

tensor(12.3216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0957, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1166, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▍     | 134/300 [06:34<00:20,  8.14it/s]

tensor(12.3062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1355, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1464, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [06:34<00:20,  8.20it/s]

tensor(12.2908, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1643, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2834, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1864, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 138/300 [06:35<00:19,  8.20it/s]

tensor(12.2766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2060, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2705, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2296, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 140/300 [06:35<00:19,  8.19it/s]

tensor(12.2650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2479, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2596, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2656, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [06:35<00:19,  8.24it/s]

tensor(12.2539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2677, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2485, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2816, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [06:35<00:19,  8.18it/s]

tensor(12.2430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3023, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3205, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [06:36<00:18,  8.22it/s]

tensor(12.2323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3388, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3576, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [06:36<00:18,  8.29it/s]

tensor(12.2216, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3726, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2164, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3766, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [06:36<00:18,  8.28it/s]

tensor(12.2116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3917, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([224, 414, 232,  89, 137,  43, 119,  87,  77,  61, 188, 357, 130,  90])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:17, 29.13it/s]
  0%|          | 9/2248 [00:00<00:52, 42.29it/s]
  1%|          | 17/2248 [00:00<00:41, 54.37it/s]
  1%|          | 23/2248 [00:00<00:53, 41.87it/s]
  1%|          | 28/2248 [00:00<00:50, 43.91it/s]
  1%|▏         | 33/2248 [00:00<00:54, 40.98it/s]
  2%|▏         | 38/2248 [00:00<00:55, 39.48it/s]
  2%|▏         | 43/2248 [00:01<01:00, 36.21it/s]
  2%|▏         | 49/2248 [00:01<00:55, 39.50it/s]
  2%|▏         | 54/2248 [00:01<00:52, 41.70it/s]
  3%|▎         | 59/2248 [00:01<01:05, 33.25it/s]
  3%|▎         | 65/2248 [00:01<00:56, 38.86it/s]
  3%|▎         | 71/2248 [00:01<00:54, 39.88it/s]
  3%|▎         | 76/2248 [00:02<01:40, 21.58it/s]
  4%|▎         | 80/2248 [00:02<01:54, 18.93it/s]
  4%|▎         | 83/2248 [00:02<02:06, 17.08it/s]
  4%|▍         | 86/2248 [00:03<03:42,  9.71it/s]
  4%|▍         | 89/2248 [00:03<03:11, 11.30it/s]
  4%|▍         | 91/2248 [00:04<03:37,  9.92it/s]
  4%|▍         | 93/2248 [00:04<03:42,  9.68it/s]
  4%|▍         | 95/2248 [00:04<03:29, 10.29it/s]
  4%|▍         | 97/2248 [00:04<04:04,  8.80it/s]
  4%|▍         | 99/2248 [00:04<03:41,  9.69it/s]
  4%|▍         | 101/2248 [00:05<03:42,  9.66it/s]
  5%|▍         | 103/2248 [00:05<03:53,  9.20it/s]
  5%|▍         | 105/2248 [00:05<04:02,  8.85it/s]
  5%|▍         | 107/2248 [00:05<03:32, 10.07it/s]
  5%|▍         | 111/2248 [00:05<02:47, 12.73it/s]
  5%|▌         | 113/2248 [00:06<03:17, 10.80it/s]
  5%|▌         | 115/2248 [00:06<03:33,  9.99it/s]
  5%|▌         | 117/2248 [00:07<08:04,  4.40it/s]
  5%|▌         | 118/2248 [00:07<07:57,  4.46it/s]
  5%|▌         | 120/2248 [00:08<10:12,  3.48it/s]
  5%|▌         | 121/2248 [00:08<09:46,  3.63it/s]
  5%|▌         | 122/2248 [00:09<09:10,  3.86it/s]
  6%|▌         | 124/2248 [00:09<06:31,  5.43it/s]
  6%|▌         | 125/2248 [00:09<06:55,  5.11it/s]
  6%|▌         | 126/2248 [00:09<07:05,  4.98it/s]
  6%|▌         | 127/2248 [00:10<12:36,  2.80it/s]
  6%|▌         | 128/2248 [00:11<16:38,  2.12it/s]
  6%|▌         | 130/2248 [00:11<10:23,  3.40it/s]
  6%|▌         | 133/2248 [00:11<06:48,  5.18it/s]
  6%|▌         | 135/2248 [00:11<06:05,  5.78it/s]
  6%|▌         | 136/2248 [00:12<06:16,  5.60it/s]
  6%|▌         | 138/2248 [00:12<05:39,  6.21it/s]
  6%|▋         | 141/2248 [00:12<03:56,  8.93it/s]
  6%|▋         | 145/2248 [00:12<03:18, 10.59it/s]
  7%|▋         | 148/2248 [00:12<02:38, 13.21it/s]
  7%|▋         | 150/2248 [00:13<03:11, 10.95it/s]
  7%|▋         | 152/2248 [00:13<04:10,  8.36it/s]
  7%|▋         | 154/2248 [00:13<03:35,  9.74it/s]
  7%|▋         | 156/2248 [00:13<03:37,  9.61it/s]
  7%|▋         | 158/2248 [00:14<07:33,  4.61it/s]
  7%|▋         | 159/2248 [00:15<10:53,  3.20it/s]
  7%|▋         | 160/2248 [00:15<10:19,  3.37it/s]
  7%|▋         | 162/2248 [00:16<08:20,  4.17it/s]
  7%|▋         | 164/2248 [00:16<06:12,  5.60it/s]
  7%|▋         | 165/2248 [00:17<10:30,  3.30it/s]
  7%|▋         | 166/2248 [00:17<09:50,  3.52it/s]
  8%|▊         | 169/2248 [00:18<09:44,  3.56it/s]
  8%|▊         | 170/2248 [00:18<08:42,  3.98it/s]
  8%|▊         | 172/2248 [00:18<06:21,  5.44it/s]
  8%|▊         | 173/2248 [00:18<06:43,  5.14it/s]
  8%|▊         | 175/2248 [00:18<04:56,  6.99it/s]
  8%|▊         | 177/2248 [00:19<07:40,  4.50it/s]
  8%|▊         | 178/2248 [00:19<07:31,  4.58it/s]
  8%|▊         | 180/2248 [00:20<06:57,  4.95it/s]
  8%|▊         | 182/2248 [00:20<05:15,  6.54it/s]
  8%|▊         | 184/2248 [00:20<06:10,  5.57it/s]
  8%|▊         | 185/2248 [00:20<06:24,  5.36it/s]
  8%|▊         | 187/2248 [00:21<08:53,  3.86it/s]
  8%|▊         | 189/2248 [00:22<10:25,  3.29it/s]
  8%|▊         | 190/2248 [00:22<09:57,  3.44it/s]
  9%|▊         | 192/2248 [00:22<07:09,  4.78it/s]
  9%|▊         | 193/2248 [00:22<07:11,  4.77it/s]
  9%|▊         | 194/2248 [00:23<07:20,  4.67it/s]
  9%|▊         | 195/2248 [00:23<07:17,  4.69it/s]
  9%|▉         | 197/2248 [00:23<05:05,  6.71it/s]
  9%|▉         | 199/2248 [00:23<04:03,  8.43it/s]
  9%|▉         | 201/2248 [00:23<03:46,  9.03it/s]
  9%|▉         | 203/2248 [00:24<06:50,  4.98it/s]
  9%|▉         | 205/2248 [00:24<05:56,  5.73it/s]
  9%|▉         | 206/2248 [00:25<06:08,  5.53it/s]
  9%|▉         | 207/2248 [00:25<09:24,  3.62it/s]
  9%|▉         | 208/2248 [00:25<08:17,  4.10it/s]
  9%|▉         | 209/2248 [00:26<09:13,  3.69it/s]
  9%|▉         | 210/2248 [00:26<11:08,  3.05it/s]
  9%|▉         | 211/2248 [00:27<13:11,  2.57it/s]
  9%|▉         | 213/2248 [00:27<08:22,  4.05it/s]
 10%|▉         | 214/2248 [00:27<10:09,  3.34it/s]
 10%|▉         | 216/2248 [00:27<06:56,  4.88it/s]
 10%|▉         | 220/2248 [00:28<03:41,  9.14it/s]
 10%|▉         | 222/2248 [00:28<03:55,  8.59it/s]
 10%|█         | 225/2248 [00:28<02:55, 11.51it/s]
 10%|█         | 227/2248 [00:29<05:29,  6.13it/s]
 10%|█         | 229/2248 [00:29<04:34,  7.35it/s]
 10%|█         | 236/2248 [00:29<02:14, 14.91it/s]
 11%|█         | 242/2248 [00:29<01:33, 21.53it/s]
 11%|█         | 249/2248 [00:30<02:31, 13.16it/s]
 11%|█         | 252/2248 [00:30<02:19, 14.28it/s]
 12%|█▏        | 259/2248 [00:30<01:35, 20.93it/s]
 12%|█▏        | 263/2248 [00:32<04:13,  7.83it/s]
 12%|█▏        | 266/2248 [00:33<06:57,  4.74it/s]
 12%|█▏        | 269/2248 [00:33<05:37,  5.86it/s]
 12%|█▏        | 272/2248 [00:34<04:56,  6.65it/s]
 12%|█▏        | 274/2248 [00:34<06:29,  5.07it/s]
 12%|█▏        | 276/2248 [00:35<05:57,  5.51it/s]
 12%|█▏        | 278/2248 [00:35<07:30,  4.37it/s]
 12%|█▏        | 280/2248 [00:36<08:56,  3.67it/s]
 12%|█▎        | 281/2248 [00:37<11:11,  2.93it/s]
 13%|█▎        | 282/2248 [00:37<10:15,  3.19it/s]
 13%|█▎        | 284/2248 [00:38<11:07,  2.94it/s]
 13%|█▎        | 286/2248 [00:39<11:25,  2.86it/s]
 13%|█▎        | 287/2248 [00:39<10:17,  3.18it/s]
 13%|█▎        | 289/2248 [00:39<07:17,  4.48it/s]
 13%|█▎        | 290/2248 [00:40<11:10,  2.92it/s]
 13%|█▎        | 291/2248 [00:40<10:07,  3.22it/s]
 13%|█▎        | 292/2248 [00:40<08:30,  3.83it/s]
 13%|█▎        | 294/2248 [00:40<05:48,  5.61it/s]
 13%|█▎        | 296/2248 [00:40<05:47,  5.61it/s]
 13%|█▎        | 298/2248 [00:41<05:16,  6.17it/s]
 13%|█▎        | 299/2248 [00:41<05:39,  5.74it/s]
 13%|█▎        | 301/2248 [00:41<04:37,  7.01it/s]
 13%|█▎        | 302/2248 [00:41<05:49,  5.57it/s]
 13%|█▎        | 303/2248 [00:42<05:50,  5.55it/s]
 14%|█▎        | 304/2248 [00:42<06:02,  5.37it/s]
 14%|█▎        | 305/2248 [00:42<08:00,  4.04it/s]
 14%|█▎        | 306/2248 [00:43<09:14,  3.50it/s]
 14%|█▎        | 307/2248 [00:43<09:40,  3.34it/s]
 14%|█▎        | 308/2248 [00:43<10:50,  2.98it/s]
 14%|█▎        | 309/2248 [00:44<09:28,  3.41it/s]
 14%|█▍        | 311/2248 [00:44<06:04,  5.31it/s]
 14%|█▍        | 312/2248 [00:44<08:10,  3.95it/s]
 14%|█▍        | 314/2248 [00:45<08:58,  3.59it/s]
 14%|█▍        | 315/2248 [00:45<09:17,  3.47it/s]
 14%|█▍        | 317/2248 [00:45<06:24,  5.02it/s]
 14%|█▍        | 319/2248 [00:45<04:55,  6.54it/s]
 14%|█▍        | 320/2248 [00:46<05:01,  6.39it/s]
 14%|█▍        | 322/2248 [00:46<03:57,  8.13it/s]
 14%|█▍        | 324/2248 [00:46<04:56,  6.50it/s]
 14%|█▍        | 325/2248 [00:46<05:06,  6.27it/s]
 15%|█▍        | 327/2248 [00:47<06:28,  4.95it/s]
 15%|█▍        | 328/2248 [00:47<07:32,  4.25it/s]
 15%|█▍        | 330/2248 [00:47<05:30,  5.81it/s]
 15%|█▍        | 332/2248 [00:48<05:20,  5.97it/s]
 15%|█▍        | 334/2248 [00:48<04:21,  7.33it/s]
 15%|█▍        | 336/2248 [00:48<03:28,  9.19it/s]
 15%|█▌        | 339/2248 [00:48<03:15,  9.78it/s]
 15%|█▌        | 341/2248 [00:49<04:53,  6.49it/s]
 15%|█▌        | 343/2248 [00:49<05:03,  6.27it/s]
 15%|█▌        | 344/2248 [00:49<05:20,  5.93it/s]
 15%|█▌        | 345/2248 [00:50<07:22,  4.30it/s]
 15%|█▌        | 346/2248 [00:51<11:02,  2.87it/s]
 15%|█▌        | 347/2248 [00:51<12:36,  2.51it/s]
 15%|█▌        | 348/2248 [00:52<12:12,  2.59it/s]
 16%|█▌        | 349/2248 [00:52<10:12,  3.10it/s]
 16%|█▌        | 350/2248 [00:52<08:18,  3.81it/s]
 16%|█▌        | 352/2248 [00:52<05:33,  5.68it/s]
 16%|█▌        | 353/2248 [00:52<05:38,  5.60it/s]
 16%|█▌        | 354/2248 [00:52<07:24,  4.26it/s]
 16%|█▌        | 355/2248 [00:53<09:50,  3.20it/s]
 16%|█▌        | 356/2248 [00:53<10:39,  2.96it/s]
 16%|█▌        | 358/2248 [00:54<06:47,  4.64it/s]
 16%|█▌        | 362/2248 [00:54<06:23,  4.92it/s]
 16%|█▌        | 364/2248 [00:55<05:41,  5.52it/s]
 16%|█▋        | 366/2248 [00:55<05:08,  6.09it/s]
 16%|█▋        | 367/2248 [00:56<08:01,  3.91it/s]
 16%|█▋        | 369/2248 [00:56<05:58,  5.24it/s]
 17%|█▋        | 371/2248 [00:56<07:39,  4.08it/s]
 17%|█▋        | 373/2248 [00:57<09:14,  3.38it/s]
 17%|█▋        | 376/2248 [00:57<06:01,  5.18it/s]
 17%|█▋        | 378/2248 [00:58<05:26,  5.73it/s]
 17%|█▋        | 380/2248 [00:58<05:05,  6.12it/s]
 17%|█▋        | 381/2248 [00:58<05:36,  5.55it/s]
 17%|█▋        | 384/2248 [00:59<06:45,  4.60it/s]
 17%|█▋        | 385/2248 [01:00<09:51,  3.15it/s]
 17%|█▋        | 388/2248 [01:01<09:22,  3.31it/s]
 17%|█▋        | 389/2248 [01:01<12:00,  2.58it/s]
 17%|█▋        | 390/2248 [01:02<14:13,  2.18it/s]
 17%|█▋        | 391/2248 [01:03<16:14,  1.91it/s]
 17%|█▋        | 392/2248 [01:04<17:43,  1.75it/s]
 17%|█▋        | 393/2248 [01:04<19:10,  1.61it/s]
 18%|█▊        | 394/2248 [01:05<20:28,  1.51it/s]
 18%|█▊        | 395/2248 [01:06<17:50,  1.73it/s]
 18%|█▊        | 396/2248 [01:06<13:52,  2.22it/s]
 18%|█▊        | 398/2248 [01:06<08:30,  3.62it/s]
 18%|█▊        | 403/2248 [01:06<03:43,  8.27it/s]
 18%|█▊        | 408/2248 [01:06<02:19, 13.21it/s]
 18%|█▊        | 413/2248 [01:06<01:38, 18.57it/s]
 19%|█▊        | 420/2248 [01:06<01:07, 26.92it/s]
 19%|█▉        | 425/2248 [01:06<01:00, 29.93it/s]
 19%|█▉        | 431/2248 [01:06<00:51, 35.59it/s]
 19%|█▉        | 436/2248 [01:07<02:00, 15.08it/s]
 20%|█▉        | 440/2248 [01:08<03:38,  8.27it/s]
 20%|█▉        | 443/2248 [01:09<03:11,  9.42it/s]
 20%|█▉        | 446/2248 [01:09<04:02,  7.42it/s]
 20%|█▉        | 448/2248 [01:09<03:49,  7.85it/s]
 20%|██        | 450/2248 [01:10<03:45,  7.99it/s]
 20%|██        | 452/2248 [01:10<03:19,  9.01it/s]
 20%|██        | 454/2248 [01:10<03:50,  7.77it/s]
 20%|██        | 456/2248 [01:10<04:08,  7.22it/s]
 20%|██        | 457/2248 [01:11<07:10,  4.16it/s]
 20%|██        | 459/2248 [01:12<08:45,  3.41it/s]
 20%|██        | 460/2248 [01:12<08:27,  3.52it/s]
 21%|██        | 462/2248 [01:12<06:09,  4.84it/s]
 21%|██        | 463/2248 [01:13<06:04,  4.89it/s]
 21%|██        | 464/2248 [01:13<05:48,  5.12it/s]
 21%|██        | 466/2248 [01:13<04:15,  6.98it/s]
 21%|██        | 468/2248 [01:13<03:21,  8.85it/s]
 21%|██        | 471/2248 [01:14<05:23,  5.49it/s]
 21%|██        | 472/2248 [01:14<06:16,  4.71it/s]
 21%|██        | 473/2248 [01:14<05:45,  5.14it/s]
 21%|██        | 475/2248 [01:15<06:26,  4.59it/s]
 21%|██        | 476/2248 [01:15<06:20,  4.66it/s]
 21%|██        | 477/2248 [01:15<07:24,  3.99it/s]
 21%|██▏       | 478/2248 [01:16<07:41,  3.83it/s]
 21%|██▏       | 479/2248 [01:16<09:34,  3.08it/s]
 21%|██▏       | 480/2248 [01:17<13:01,  2.26it/s]
 21%|██▏       | 481/2248 [01:17<12:41,  2.32it/s]
 21%|██▏       | 482/2248 [01:17<10:03,  2.93it/s]
 22%|██▏       | 484/2248 [01:18<06:17,  4.67it/s]
 22%|██▏       | 485/2248 [01:18<05:43,  5.13it/s]
 22%|██▏       | 486/2248 [01:18<05:29,  5.34it/s]
 22%|██▏       | 487/2248 [01:18<05:28,  5.37it/s]
 22%|██▏       | 488/2248 [01:18<06:31,  4.50it/s]
 22%|██▏       | 490/2248 [01:19<04:23,  6.68it/s]
 22%|██▏       | 492/2248 [01:19<04:02,  7.24it/s]
 22%|██▏       | 494/2248 [01:19<03:08,  9.31it/s]
 22%|██▏       | 496/2248 [01:19<03:16,  8.93it/s]
 22%|██▏       | 499/2248 [01:19<02:59,  9.76it/s]
 22%|██▏       | 501/2248 [01:20<03:01,  9.60it/s]
 22%|██▏       | 503/2248 [01:20<03:12,  9.08it/s]
 23%|██▎       | 506/2248 [01:20<02:28, 11.70it/s]
 23%|██▎       | 509/2248 [01:20<02:27, 11.78it/s]
 23%|██▎       | 511/2248 [01:21<02:54,  9.94it/s]
 23%|██▎       | 513/2248 [01:21<03:42,  7.79it/s]
 23%|██▎       | 514/2248 [01:22<06:38,  4.35it/s]
 23%|██▎       | 515/2248 [01:22<06:29,  4.45it/s]
 23%|██▎       | 516/2248 [01:22<06:19,  4.56it/s]
 23%|██▎       | 517/2248 [01:22<06:12,  4.65it/s]
 23%|██▎       | 518/2248 [01:23<06:37,  4.35it/s]
 23%|██▎       | 519/2248 [01:23<06:10,  4.67it/s]
 23%|██▎       | 522/2248 [01:23<03:29,  8.24it/s]
 24%|██▎       | 529/2248 [01:23<02:05, 13.71it/s]
 24%|██▎       | 531/2248 [01:23<02:00, 14.22it/s]
 24%|██▍       | 534/2248 [01:24<02:04, 13.75it/s]
 24%|██▍       | 536/2248 [01:24<02:01, 14.04it/s]
 24%|██▍       | 543/2248 [01:24<01:17, 22.09it/s]
 24%|██▍       | 546/2248 [01:24<01:14, 22.92it/s]
 24%|██▍       | 549/2248 [01:24<01:12, 23.51it/s]
 25%|██▍       | 552/2248 [01:25<02:16, 12.47it/s]
 25%|██▍       | 554/2248 [01:25<03:01,  9.32it/s]
 25%|██▍       | 556/2248 [01:25<02:52,  9.81it/s]
 25%|██▍       | 559/2248 [01:25<02:18, 12.16it/s]
 25%|██▌       | 562/2248 [01:25<02:01, 13.84it/s]
 25%|██▌       | 564/2248 [01:26<02:18, 12.17it/s]
 25%|██▌       | 567/2248 [01:26<01:57, 14.36it/s]
 25%|██▌       | 571/2248 [01:27<02:58,  9.38it/s]
 25%|██▌       | 573/2248 [01:27<04:23,  6.37it/s]
 26%|██▌       | 575/2248 [01:27<03:51,  7.22it/s]
 26%|██▌       | 577/2248 [01:27<03:22,  8.24it/s]
 26%|██▌       | 579/2248 [01:28<03:02,  9.16it/s]
 26%|██▌       | 581/2248 [01:28<02:47,  9.96it/s]
 26%|██▌       | 583/2248 [01:28<04:19,  6.42it/s]
 26%|██▌       | 584/2248 [01:29<06:15,  4.44it/s]
 26%|██▌       | 586/2248 [01:30<07:28,  3.71it/s]
 26%|██▌       | 588/2248 [01:30<08:23,  3.30it/s]
 26%|██▌       | 590/2248 [01:31<06:18,  4.38it/s]
 26%|██▋       | 592/2248 [01:31<05:23,  5.11it/s]
 26%|██▋       | 595/2248 [01:31<03:39,  7.54it/s]
 27%|██▋       | 599/2248 [01:31<02:55,  9.38it/s]
 27%|██▋       | 601/2248 [01:32<04:54,  5.59it/s]
 27%|██▋       | 603/2248 [01:32<05:12,  5.26it/s]
 27%|██▋       | 604/2248 [01:33<05:04,  5.40it/s]
 27%|██▋       | 605/2248 [01:33<06:17,  4.35it/s]
 27%|██▋       | 606/2248 [01:34<07:40,  3.56it/s]
 27%|██▋       | 607/2248 [01:34<07:00,  3.91it/s]
 27%|██▋       | 608/2248 [01:34<07:09,  3.82it/s]
 27%|██▋       | 609/2248 [01:35<08:59,  3.04it/s]
 27%|██▋       | 611/2248 [01:35<05:58,  4.57it/s]
 27%|██▋       | 613/2248 [01:35<04:28,  6.08it/s]
 27%|██▋       | 615/2248 [01:35<03:24,  7.99it/s]
 28%|██▊       | 621/2248 [01:35<01:39, 16.30it/s]
 28%|██▊       | 625/2248 [01:35<01:19, 20.43it/s]
 28%|██▊       | 628/2248 [01:35<01:21, 19.89it/s]
 28%|██▊       | 634/2248 [01:35<00:57, 27.96it/s]
 28%|██▊       | 638/2248 [01:35<00:52, 30.50it/s]
 29%|██▊       | 645/2248 [01:36<00:42, 38.09it/s]
 29%|██▉       | 650/2248 [01:36<00:51, 31.04it/s]
 29%|██▉       | 654/2248 [01:37<02:30, 10.56it/s]
 29%|██▉       | 657/2248 [01:37<02:13, 11.93it/s]
 29%|██▉       | 660/2248 [01:37<02:18, 11.50it/s]
 29%|██▉       | 663/2248 [01:38<02:09, 12.20it/s]
 30%|██▉       | 665/2248 [01:38<02:09, 12.26it/s]
 30%|██▉       | 667/2248 [01:38<02:01, 13.00it/s]
 30%|██▉       | 669/2248 [01:38<01:56, 13.53it/s]
 30%|██▉       | 671/2248 [01:38<02:07, 12.34it/s]
 30%|███       | 675/2248 [01:38<01:32, 16.93it/s]
 30%|███       | 678/2248 [01:39<02:08, 12.19it/s]
 30%|███       | 680/2248 [01:39<01:57, 13.35it/s]
 30%|███       | 682/2248 [01:39<03:29,  7.49it/s]
 30%|███       | 684/2248 [01:40<04:57,  5.25it/s]
 31%|███       | 686/2248 [01:41<06:12,  4.19it/s]
 31%|███       | 687/2248 [01:41<06:08,  4.24it/s]
 31%|███       | 688/2248 [01:41<05:50,  4.45it/s]
 31%|███       | 690/2248 [01:41<04:22,  5.94it/s]
 31%|███       | 691/2248 [01:42<04:26,  5.84it/s]
 31%|███       | 692/2248 [01:42<04:14,  6.12it/s]
 31%|███       | 694/2248 [01:42<03:21,  7.71it/s]
 31%|███       | 695/2248 [01:42<04:48,  5.38it/s]
 31%|███       | 697/2248 [01:42<03:47,  6.81it/s]
 31%|███       | 698/2248 [01:43<05:51,  4.41it/s]
 31%|███       | 699/2248 [01:43<05:15,  4.91it/s]
 31%|███       | 701/2248 [01:43<03:41,  6.98it/s]
 31%|███▏      | 703/2248 [01:44<04:32,  5.68it/s]
 31%|███▏      | 705/2248 [01:44<03:37,  7.09it/s]
 31%|███▏      | 708/2248 [01:44<02:28, 10.37it/s]
 32%|███▏      | 710/2248 [01:44<03:36,  7.12it/s]
 32%|███▏      | 712/2248 [01:45<04:43,  5.42it/s]
 32%|███▏      | 713/2248 [01:45<05:32,  4.61it/s]
 32%|███▏      | 715/2248 [01:46<06:23,  4.00it/s]
 32%|███▏      | 717/2248 [01:46<04:51,  5.25it/s]
 32%|███▏      | 719/2248 [01:46<04:08,  6.15it/s]
 32%|███▏      | 721/2248 [01:47<03:56,  6.46it/s]
 32%|███▏      | 723/2248 [01:47<03:13,  7.90it/s]
 32%|███▏      | 725/2248 [01:47<05:07,  4.95it/s]
 32%|███▏      | 727/2248 [01:48<04:35,  5.52it/s]
 32%|███▏      | 728/2248 [01:48<05:33,  4.55it/s]
 33%|███▎      | 731/2248 [01:49<04:43,  5.35it/s]
 33%|███▎      | 732/2248 [01:49<06:31,  3.87it/s]
 33%|███▎      | 733/2248 [01:50<07:34,  3.33it/s]
 33%|███▎      | 734/2248 [01:50<06:59,  3.60it/s]
 33%|███▎      | 735/2248 [01:50<08:35,  2.93it/s]
 33%|███▎      | 736/2248 [01:51<08:22,  3.01it/s]
 33%|███▎      | 737/2248 [01:51<07:32,  3.34it/s]
 33%|███▎      | 738/2248 [01:51<06:24,  3.92it/s]
 33%|███▎      | 740/2248 [01:51<04:09,  6.03it/s]
 33%|███▎      | 742/2248 [01:51<04:07,  6.09it/s]
 33%|███▎      | 743/2248 [01:52<07:14,  3.46it/s]
 33%|███▎      | 744/2248 [01:53<08:05,  3.10it/s]
 33%|███▎      | 746/2248 [01:53<05:22,  4.66it/s]
 33%|███▎      | 749/2248 [01:53<03:53,  6.41it/s]
 33%|███▎      | 751/2248 [01:53<04:03,  6.15it/s]
 33%|███▎      | 752/2248 [01:54<04:24,  5.65it/s]
 34%|███▎      | 754/2248 [01:54<04:19,  5.75it/s]
 34%|███▎      | 757/2248 [01:54<02:56,  8.43it/s]
 34%|███▍      | 761/2248 [01:54<02:24, 10.31it/s]
 34%|███▍      | 763/2248 [01:54<02:14, 11.03it/s]
 34%|███▍      | 765/2248 [01:55<02:24, 10.28it/s]
 34%|███▍      | 767/2248 [01:55<02:41,  9.19it/s]
 34%|███▍      | 770/2248 [01:55<02:04, 11.87it/s]
 34%|███▍      | 772/2248 [01:55<02:13, 11.03it/s]
 34%|███▍      | 774/2248 [01:56<04:39,  5.26it/s]
 34%|███▍      | 775/2248 [01:57<06:50,  3.59it/s]
 35%|███▍      | 776/2248 [01:57<06:32,  3.75it/s]
 35%|███▍      | 778/2248 [01:58<05:24,  4.53it/s]
 35%|███▍      | 781/2248 [01:58<03:33,  6.88it/s]
 35%|███▍      | 783/2248 [01:58<03:57,  6.17it/s]
 35%|███▍      | 784/2248 [01:58<04:08,  5.88it/s]
 35%|███▌      | 787/2248 [01:58<02:48,  8.65it/s]
 35%|███▌      | 789/2248 [01:59<02:45,  8.83it/s]
 35%|███▌      | 791/2248 [01:59<03:32,  6.85it/s]
 35%|███▌      | 792/2248 [01:59<03:51,  6.28it/s]
 35%|███▌      | 793/2248 [01:59<03:38,  6.67it/s]
 35%|███▌      | 794/2248 [02:00<04:12,  5.77it/s]
 35%|███▌      | 796/2248 [02:00<03:03,  7.91it/s]
 35%|███▌      | 798/2248 [02:01<05:17,  4.57it/s]
 36%|███▌      | 800/2248 [02:01<04:25,  5.45it/s]
 36%|███▌      | 803/2248 [02:01<02:59,  8.04it/s]
 36%|███▌      | 806/2248 [02:01<02:34,  9.31it/s]
 36%|███▌      | 809/2248 [02:01<02:02, 11.74it/s]
 36%|███▌      | 811/2248 [02:02<02:45,  8.69it/s]
 36%|███▌      | 813/2248 [02:02<03:08,  7.61it/s]
 36%|███▋      | 815/2248 [02:02<03:10,  7.51it/s]
 36%|███▋      | 816/2248 [02:02<03:02,  7.83it/s]
 36%|███▋      | 818/2248 [02:03<03:57,  6.02it/s]
 36%|███▋      | 820/2248 [02:03<03:11,  7.47it/s]
 37%|███▋      | 826/2248 [02:04<02:50,  8.33it/s]
 37%|███▋      | 828/2248 [02:04<02:33,  9.23it/s]
 37%|███▋      | 831/2248 [02:05<03:44,  6.30it/s]
 37%|███▋      | 834/2248 [02:05<02:52,  8.21it/s]
 37%|███▋      | 841/2248 [02:05<01:36, 14.65it/s]
 38%|███▊      | 848/2248 [02:05<01:03, 21.94it/s]
 38%|███▊      | 853/2248 [02:05<01:26, 16.07it/s]
 38%|███▊      | 857/2248 [02:06<01:22, 16.83it/s]
 38%|███▊      | 864/2248 [02:06<00:58, 23.77it/s]
 39%|███▊      | 868/2248 [02:07<01:51, 12.35it/s]
 39%|███▊      | 871/2248 [02:08<03:07,  7.34it/s]
 39%|███▉      | 874/2248 [02:08<02:52,  7.99it/s]
 39%|███▉      | 877/2248 [02:09<03:48,  6.00it/s]
 39%|███▉      | 879/2248 [02:09<03:47,  6.02it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 306.53it/s]

[[np.int64(0), False, 10], [np.int64(1), False, 11], [np.int64(2), False, 10], [np.int64(3), False, 8], [np.int64(4), False, 0], [np.int64(5), False, 13], [np.int64(6), False, 0], [np.int64(7), False, 5], [np.int64(8), False, 13], [np.int64(9), False, 0], [np.int64(12), False, 10], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1023, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [12:33<4:25:49, 107.05s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [12:33<3:04:56, 74.98s/it]

tensor(12.2154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9377, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9062, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [12:33<1:02:20, 25.79s/it]

tensor(12.2652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7927, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9754, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [12:33<30:15, 12.70s/it]

tensor(12.2780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3286, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2781, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3762, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [12:34<14:45,  6.28s/it]

tensor(12.2671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3384, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4102, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [12:34<07:16,  3.14s/it]

tensor(12.2431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0318, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4828, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2383, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4831, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [12:34<03:38,  1.60s/it]

tensor(12.2327, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0357, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4767, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4678, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [12:34<01:53,  1.19it/s]

tensor(12.2226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4474, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4760, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [12:35<01:02,  2.12it/s]

tensor(12.2167, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2118, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5394, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [12:35<00:38,  3.44it/s]

tensor(12.2065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5472, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5509, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [12:35<00:26,  4.93it/s]

tensor(12.1975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5742, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [12:35<00:20,  6.31it/s]

tensor(12.1806, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6032, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 174/300 [12:35<00:18,  6.85it/s]

tensor(12.1656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6160, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1602, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6257, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [12:36<00:15,  7.71it/s]

tensor(12.1567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6324, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6359, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [12:36<00:14,  8.15it/s]

tensor(12.1493, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6362, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6405, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [12:36<00:14,  8.34it/s]

tensor(12.1415, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6417, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6408, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [12:36<00:13,  8.48it/s]

tensor(12.1337, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6429, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6457, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [12:37<00:13,  8.46it/s]

tensor(12.1276, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6483, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [12:37<00:13,  8.50it/s]

tensor(12.1232, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6476, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6469, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [12:37<00:13,  8.53it/s]

tensor(12.1185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6429, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1158, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6458, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [12:37<00:12,  8.53it/s]

tensor(12.1128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6488, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6533, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [12:38<00:12,  8.57it/s]

tensor(12.1077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6562, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6598, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [12:38<00:12,  8.57it/s]

tensor(12.1031, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6606, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1011, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6619, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [12:38<00:12,  8.55it/s]

tensor(12.0990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6587, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6624, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [12:38<00:11,  8.56it/s]

tensor(12.0950, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6638, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6663, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [12:38<00:11,  8.60it/s]

tensor(12.0910, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6700, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([174, 329, 113,  72, 137, 101, 189,  89, 145, 143,  81,  95, 397, 183])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 4/2248 [00:00<01:01, 36.49it/s]
  0%|          | 10/2248 [00:00<00:47, 46.82it/s]
  1%|          | 17/2248 [00:00<00:47, 47.39it/s]
  1%|          | 24/2248 [00:00<00:43, 51.57it/s]
  1%|▏         | 30/2248 [00:00<00:42, 52.28it/s]
  2%|▏         | 36/2248 [00:00<00:41, 53.38it/s]
  2%|▏         | 43/2248 [00:00<00:39, 56.05it/s]
  2%|▏         | 50/2248 [00:00<00:37, 59.31it/s]
  2%|▏         | 56/2248 [00:01<00:39, 54.94it/s]
  3%|▎         | 64/2248 [00:01<00:35, 60.69it/s]
  3%|▎         | 71/2248 [00:01<00:43, 49.68it/s]
  3%|▎         | 77/2248 [00:02<02:36, 13.85it/s]
  4%|▎         | 81/2248 [00:03<02:52, 12.56it/s]
  4%|▍         | 86/2248 [00:03<03:12, 11.22it/s]
  4%|▍         | 89/2248 [00:03<03:04, 11.70it/s]
  4%|▍         | 92/2248 [00:04<03:42,  9.69it/s]
  4%|▍         | 94/2248 [00:04<03:25, 10.47it/s]
  4%|▍         | 96/2248 [00:04<03:50,  9.35it/s]
  4%|▍         | 98/2248 [00:05<04:32,  7.90it/s]
  4%|▍         | 100/2248 [00:05<04:54,  7.29it/s]
  5%|▍         | 102/2248 [00:05<04:19,  8.27it/s]
  5%|▍         | 104/2248 [00:05<04:13,  8.46it/s]
  5%|▍         | 106/2248 [00:05<03:40,  9.73it/s]
  5%|▍         | 111/2248 [00:06<02:44, 13.01it/s]
  5%|▌         | 113/2248 [00:06<04:09,  8.55it/s]
  5%|▌         | 115/2248 [00:07<04:19,  8.21it/s]
  5%|▌         | 117/2248 [00:07<05:41,  6.25it/s]
  5%|▌         | 118/2248 [00:07<05:44,  6.18it/s]
  5%|▌         | 120/2248 [00:08<05:30,  6.43it/s]
  5%|▌         | 122/2248 [00:08<05:01,  7.05it/s]
  6%|▌         | 125/2248 [00:08<04:30,  7.85it/s]
  6%|▌         | 126/2248 [00:08<05:29,  6.43it/s]
  6%|▌         | 127/2248 [00:09<06:58,  5.07it/s]
  6%|▌         | 128/2248 [00:09<08:50,  3.99it/s]
  6%|▌         | 131/2248 [00:09<05:17,  6.66it/s]
  6%|▌         | 133/2248 [00:10<05:26,  6.48it/s]
  6%|▌         | 135/2248 [00:10<05:22,  6.55it/s]
  6%|▌         | 136/2248 [00:10<06:00,  5.86it/s]
  6%|▌         | 138/2248 [00:11<05:59,  5.87it/s]
  6%|▌         | 140/2248 [00:11<06:31,  5.39it/s]
  6%|▋         | 142/2248 [00:11<05:16,  6.64it/s]
  6%|▋         | 144/2248 [00:11<04:10,  8.39it/s]
  6%|▋         | 146/2248 [00:12<04:39,  7.52it/s]
  7%|▋         | 149/2248 [00:12<03:16, 10.67it/s]
  7%|▋         | 151/2248 [00:12<04:11,  8.35it/s]
  7%|▋         | 153/2248 [00:12<04:00,  8.73it/s]
  7%|▋         | 155/2248 [00:12<03:23, 10.26it/s]
  7%|▋         | 157/2248 [00:13<05:33,  6.27it/s]
  7%|▋         | 159/2248 [00:14<07:15,  4.79it/s]
  7%|▋         | 160/2248 [00:14<07:03,  4.93it/s]
  7%|▋         | 162/2248 [00:14<06:27,  5.38it/s]
  7%|▋         | 165/2248 [00:15<06:18,  5.51it/s]
  7%|▋         | 166/2248 [00:15<06:34,  5.27it/s]
  7%|▋         | 168/2248 [00:15<07:09,  4.85it/s]
  8%|▊         | 169/2248 [00:16<08:26,  4.10it/s]
  8%|▊         | 173/2248 [00:16<05:33,  6.22it/s]
  8%|▊         | 175/2248 [00:16<04:43,  7.32it/s]
  8%|▊         | 176/2248 [00:16<05:04,  6.81it/s]
  8%|▊         | 178/2248 [00:17<06:41,  5.16it/s]
  8%|▊         | 180/2248 [00:17<07:05,  4.86it/s]
  8%|▊         | 182/2248 [00:18<05:27,  6.31it/s]
  8%|▊         | 183/2248 [00:18<09:09,  3.76it/s]
  8%|▊         | 185/2248 [00:19<09:01,  3.81it/s]
  8%|▊         | 187/2248 [00:20<10:41,  3.21it/s]
  8%|▊         | 189/2248 [00:20<11:40,  2.94it/s]
  8%|▊         | 190/2248 [00:21<11:23,  3.01it/s]
  9%|▊         | 192/2248 [00:21<08:15,  4.15it/s]
  9%|▊         | 193/2248 [00:21<09:08,  3.75it/s]
  9%|▊         | 195/2248 [00:22<08:29,  4.03it/s]
  9%|▉         | 197/2248 [00:22<06:16,  5.45it/s]
  9%|▉         | 198/2248 [00:22<07:52,  4.34it/s]
  9%|▉         | 201/2248 [00:23<07:04,  4.82it/s]
  9%|▉         | 202/2248 [00:23<07:12,  4.73it/s]
  9%|▉         | 204/2248 [00:23<05:30,  6.18it/s]
  9%|▉         | 205/2248 [00:24<06:53,  4.94it/s]
  9%|▉         | 206/2248 [00:24<07:16,  4.68it/s]
  9%|▉         | 207/2248 [00:24<07:38,  4.45it/s]
  9%|▉         | 208/2248 [00:24<07:35,  4.48it/s]
  9%|▉         | 209/2248 [00:25<09:31,  3.57it/s]
  9%|▉         | 210/2248 [00:25<08:40,  3.91it/s]
  9%|▉         | 211/2248 [00:25<09:30,  3.57it/s]
  9%|▉         | 212/2248 [00:26<10:07,  3.35it/s]
 10%|▉         | 214/2248 [00:26<06:26,  5.26it/s]
 10%|▉         | 219/2248 [00:26<02:54, 11.66it/s]
 10%|█         | 227/2248 [00:26<01:28, 22.87it/s]
 10%|█         | 231/2248 [00:26<01:24, 23.88it/s]
 10%|█         | 236/2248 [00:26<01:09, 29.05it/s]
 11%|█         | 243/2248 [00:26<00:52, 38.02it/s]
 11%|█         | 248/2248 [00:26<00:50, 39.26it/s]
 11%|█▏        | 253/2248 [00:26<00:49, 40.14it/s]
 11%|█▏        | 258/2248 [00:27<00:46, 42.35it/s]
 12%|█▏        | 263/2248 [00:28<03:42,  8.92it/s]
 12%|█▏        | 267/2248 [00:30<06:11,  5.33it/s]
 12%|█▏        | 270/2248 [00:30<05:54,  5.58it/s]
 12%|█▏        | 272/2248 [00:30<05:12,  6.32it/s]
 12%|█▏        | 274/2248 [00:31<06:50,  4.81it/s]
 12%|█▏        | 276/2248 [00:32<07:10,  4.58it/s]
 12%|█▏        | 278/2248 [00:33<09:01,  3.64it/s]
 12%|█▏        | 280/2248 [00:33<10:09,  3.23it/s]
 13%|█▎        | 282/2248 [00:34<11:12,  2.92it/s]
 13%|█▎        | 284/2248 [00:35<10:33,  3.10it/s]
 13%|█▎        | 286/2248 [00:35<09:39,  3.39it/s]
 13%|█▎        | 287/2248 [00:36<10:07,  3.23it/s]
 13%|█▎        | 289/2248 [00:36<07:35,  4.30it/s]
 13%|█▎        | 290/2248 [00:36<08:17,  3.93it/s]
 13%|█▎        | 292/2248 [00:36<06:52,  4.74it/s]
 13%|█▎        | 294/2248 [00:37<05:22,  6.06it/s]
 13%|█▎        | 295/2248 [00:37<05:47,  5.62it/s]
 13%|█▎        | 297/2248 [00:37<04:32,  7.16it/s]
 13%|█▎        | 298/2248 [00:38<08:31,  3.81it/s]
 13%|█▎        | 299/2248 [00:38<08:39,  3.75it/s]
 13%|█▎        | 301/2248 [00:38<06:02,  5.36it/s]
 13%|█▎        | 302/2248 [00:39<10:05,  3.22it/s]
 13%|█▎        | 303/2248 [00:39<11:03,  2.93it/s]
 14%|█▎        | 304/2248 [00:40<14:15,  2.27it/s]
 14%|█▎        | 305/2248 [00:41<17:12,  1.88it/s]
 14%|█▎        | 306/2248 [00:42<19:07,  1.69it/s]
 14%|█▎        | 307/2248 [00:42<21:29,  1.51it/s]
 14%|█▎        | 308/2248 [00:43<20:40,  1.56it/s]
 14%|█▎        | 309/2248 [00:43<18:33,  1.74it/s]
 14%|█▍        | 312/2248 [00:44<10:55,  2.95it/s]
 14%|█▍        | 313/2248 [00:44<10:09,  3.17it/s]
 14%|█▍        | 314/2248 [00:44<10:00,  3.22it/s]
 14%|█▍        | 315/2248 [00:45<09:33,  3.37it/s]
 14%|█▍        | 317/2248 [00:45<06:26,  5.00it/s]
 14%|█▍        | 318/2248 [00:45<06:48,  4.73it/s]
 14%|█▍        | 320/2248 [00:45<05:19,  6.04it/s]
 14%|█▍        | 322/2248 [00:46<06:02,  5.32it/s]
 14%|█▍        | 323/2248 [00:46<06:19,  5.07it/s]
 14%|█▍        | 325/2248 [00:46<05:55,  5.40it/s]
 15%|█▍        | 327/2248 [00:47<06:26,  4.97it/s]
 15%|█▍        | 328/2248 [00:47<07:35,  4.22it/s]
 15%|█▍        | 331/2248 [00:47<04:46,  6.68it/s]
 15%|█▍        | 332/2248 [00:48<06:25,  4.97it/s]
 15%|█▍        | 334/2248 [00:48<04:49,  6.61it/s]
 15%|█▌        | 339/2248 [00:48<03:53,  8.18it/s]
 15%|█▌        | 341/2248 [00:49<06:15,  5.08it/s]
 15%|█▌        | 343/2248 [00:50<06:26,  4.93it/s]
 15%|█▌        | 344/2248 [00:50<06:43,  4.72it/s]
 15%|█▌        | 345/2248 [00:50<08:00,  3.96it/s]
 15%|█▌        | 346/2248 [00:51<08:42,  3.64it/s]
 15%|█▌        | 347/2248 [00:51<09:26,  3.36it/s]
 15%|█▌        | 348/2248 [00:51<09:48,  3.23it/s]
 16%|█▌        | 349/2248 [00:52<12:07,  2.61it/s]
 16%|█▌        | 350/2248 [00:52<10:45,  2.94it/s]
 16%|█▌        | 353/2248 [00:53<08:47,  3.59it/s]
 16%|█▌        | 354/2248 [00:53<09:24,  3.36it/s]
 16%|█▌        | 355/2248 [00:54<09:15,  3.41it/s]
 16%|█▌        | 356/2248 [00:54<12:20,  2.55it/s]
 16%|█▌        | 359/2248 [00:54<06:36,  4.76it/s]
 16%|█▌        | 362/2248 [00:55<07:14,  4.34it/s]
 16%|█▌        | 364/2248 [00:56<07:15,  4.32it/s]
 16%|█▋        | 366/2248 [00:56<07:27,  4.20it/s]
 16%|█▋        | 367/2248 [00:57<10:17,  3.05it/s]
 16%|█▋        | 369/2248 [00:57<07:30,  4.17it/s]
 17%|█▋        | 371/2248 [00:58<08:47,  3.56it/s]
 17%|█▋        | 373/2248 [00:58<10:00,  3.12it/s]
 17%|█▋        | 375/2248 [00:59<07:26,  4.20it/s]
 17%|█▋        | 377/2248 [00:59<07:07,  4.38it/s]
 17%|█▋        | 379/2248 [01:00<07:20,  4.25it/s]
 17%|█▋        | 382/2248 [01:00<04:55,  6.31it/s]
 17%|█▋        | 384/2248 [01:00<06:55,  4.49it/s]
 17%|█▋        | 385/2248 [01:01<09:45,  3.18it/s]
 17%|█▋        | 388/2248 [01:02<09:15,  3.35it/s]
 17%|█▋        | 389/2248 [01:02<09:51,  3.14it/s]
 17%|█▋        | 390/2248 [01:03<10:55,  2.83it/s]
 17%|█▋        | 391/2248 [01:03<10:44,  2.88it/s]
 17%|█▋        | 392/2248 [01:04<11:10,  2.77it/s]
 17%|█▋        | 393/2248 [01:04<11:39,  2.65it/s]
 18%|█▊        | 394/2248 [01:05<12:06,  2.55it/s]
 18%|█▊        | 395/2248 [01:05<13:29,  2.29it/s]
 18%|█▊        | 397/2248 [01:05<08:25,  3.67it/s]
 18%|█▊        | 399/2248 [01:05<05:51,  5.26it/s]
 18%|█▊        | 402/2248 [01:05<03:43,  8.27it/s]
 18%|█▊        | 408/2248 [01:06<01:55, 15.96it/s]
 18%|█▊        | 414/2248 [01:06<01:18, 23.28it/s]
 19%|█▊        | 418/2248 [01:06<01:11, 25.54it/s]
 19%|█▉        | 422/2248 [01:06<01:04, 28.23it/s]
 19%|█▉        | 428/2248 [01:06<00:52, 34.97it/s]
 19%|█▉        | 433/2248 [01:06<00:54, 33.41it/s]
 19%|█▉        | 437/2248 [01:07<02:07, 14.21it/s]
 20%|█▉        | 440/2248 [01:08<03:54,  7.72it/s]
 20%|█▉        | 443/2248 [01:08<03:22,  8.93it/s]
 20%|█▉        | 445/2248 [01:08<03:49,  7.86it/s]
 20%|█▉        | 447/2248 [01:09<04:38,  6.46it/s]
 20%|█▉        | 449/2248 [01:09<04:32,  6.59it/s]
 20%|██        | 451/2248 [01:10<04:55,  6.07it/s]
 20%|██        | 453/2248 [01:10<05:44,  5.21it/s]
 20%|██        | 455/2248 [01:11<05:47,  5.16it/s]
 20%|██        | 457/2248 [01:11<05:47,  5.16it/s]
 20%|██        | 459/2248 [01:11<05:37,  5.30it/s]
 20%|██        | 460/2248 [01:12<07:30,  3.97it/s]
 21%|██        | 462/2248 [01:12<05:38,  5.28it/s]
 21%|██        | 463/2248 [01:12<05:47,  5.14it/s]
 21%|██        | 464/2248 [01:13<07:35,  3.91it/s]
 21%|██        | 465/2248 [01:13<07:53,  3.77it/s]
 21%|██        | 467/2248 [01:13<05:25,  5.47it/s]
 21%|██        | 469/2248 [01:13<04:01,  7.36it/s]
 21%|██        | 471/2248 [01:14<05:56,  4.98it/s]
 21%|██        | 472/2248 [01:15<09:04,  3.26it/s]
 21%|██        | 474/2248 [01:15<06:22,  4.64it/s]
 21%|██        | 476/2248 [01:16<09:47,  3.02it/s]
 21%|██        | 477/2248 [01:17<11:41,  2.52it/s]
 21%|██▏       | 478/2248 [01:17<13:47,  2.14it/s]
 21%|██▏       | 479/2248 [01:18<13:54,  2.12it/s]
 21%|██▏       | 480/2248 [01:18<12:08,  2.43it/s]
 21%|██▏       | 481/2248 [01:18<12:54,  2.28it/s]
 21%|██▏       | 482/2248 [01:19<12:17,  2.40it/s]
 22%|██▏       | 484/2248 [01:19<07:37,  3.85it/s]
 22%|██▏       | 485/2248 [01:19<07:13,  4.07it/s]
 22%|██▏       | 486/2248 [01:19<06:38,  4.42it/s]
 22%|██▏       | 487/2248 [01:20<08:10,  3.59it/s]
 22%|██▏       | 488/2248 [01:20<07:36,  3.86it/s]
 22%|██▏       | 490/2248 [01:20<04:58,  5.88it/s]
 22%|██▏       | 492/2248 [01:20<03:57,  7.39it/s]
 22%|██▏       | 494/2248 [01:21<04:33,  6.41it/s]
 22%|██▏       | 495/2248 [01:21<04:37,  6.32it/s]
 22%|██▏       | 497/2248 [01:21<03:27,  8.43it/s]
 22%|██▏       | 499/2248 [01:21<04:14,  6.88it/s]
 22%|██▏       | 500/2248 [01:22<05:06,  5.70it/s]
 22%|██▏       | 502/2248 [01:22<03:57,  7.35it/s]
 22%|██▏       | 503/2248 [01:22<04:03,  7.18it/s]
 22%|██▏       | 505/2248 [01:22<03:09,  9.19it/s]
 23%|██▎       | 507/2248 [01:22<02:41, 10.77it/s]
 23%|██▎       | 509/2248 [01:22<03:34,  8.10it/s]
 23%|██▎       | 511/2248 [01:23<03:46,  7.68it/s]
 23%|██▎       | 512/2248 [01:23<05:20,  5.42it/s]
 23%|██▎       | 513/2248 [01:23<05:45,  5.02it/s]
 23%|██▎       | 514/2248 [01:24<06:27,  4.48it/s]
 23%|██▎       | 515/2248 [01:24<06:52,  4.20it/s]
 23%|██▎       | 516/2248 [01:24<07:51,  3.67it/s]
 23%|██▎       | 517/2248 [01:25<07:27,  3.87it/s]
 23%|██▎       | 518/2248 [01:25<07:09,  4.02it/s]
 23%|██▎       | 519/2248 [01:25<06:44,  4.27it/s]
 23%|██▎       | 521/2248 [01:25<04:44,  6.08it/s]
 23%|██▎       | 525/2248 [01:25<02:32, 11.33it/s]
 24%|██▎       | 533/2248 [01:25<01:18, 21.93it/s]
 24%|██▍       | 537/2248 [01:26<01:08, 25.03it/s]
 24%|██▍       | 545/2248 [01:26<00:51, 33.16it/s]
 24%|██▍       | 549/2248 [01:26<00:51, 33.22it/s]
 25%|██▍       | 555/2248 [01:26<00:45, 36.98it/s]
 25%|██▌       | 562/2248 [01:27<01:19, 21.25it/s]
 25%|██▌       | 566/2248 [01:27<01:58, 14.20it/s]
 25%|██▌       | 570/2248 [01:27<01:39, 16.87it/s]
 25%|██▌       | 573/2248 [01:28<03:34,  7.82it/s]
 26%|██▌       | 576/2248 [01:29<03:29,  7.99it/s]
 26%|██▌       | 578/2248 [01:29<03:25,  8.11it/s]
 26%|██▌       | 580/2248 [01:29<03:40,  7.57it/s]
 26%|██▌       | 582/2248 [01:31<07:36,  3.65it/s]
 26%|██▌       | 584/2248 [01:32<08:24,  3.30it/s]
 26%|██▌       | 586/2248 [01:32<08:52,  3.12it/s]
 26%|██▌       | 588/2248 [01:33<08:44,  3.16it/s]
 26%|██▌       | 590/2248 [01:33<06:44,  4.10it/s]
 26%|██▋       | 592/2248 [01:34<06:33,  4.21it/s]
 26%|██▋       | 595/2248 [01:34<04:30,  6.11it/s]
 27%|██▋       | 599/2248 [01:34<03:56,  6.98it/s]
 27%|██▋       | 601/2248 [01:35<05:31,  4.97it/s]
 27%|██▋       | 603/2248 [01:36<06:51,  4.00it/s]
 27%|██▋       | 604/2248 [01:36<07:32,  3.63it/s]
 27%|██▋       | 605/2248 [01:37<08:06,  3.38it/s]
 27%|██▋       | 606/2248 [01:37<10:40,  2.56it/s]
 27%|██▋       | 607/2248 [01:38<10:53,  2.51it/s]
 27%|██▋       | 608/2248 [01:38<11:12,  2.44it/s]
 27%|██▋       | 609/2248 [01:39<11:08,  2.45it/s]
 27%|██▋       | 610/2248 [01:39<10:26,  2.61it/s]
 27%|██▋       | 612/2248 [01:39<06:34,  4.15it/s]
 27%|██▋       | 617/2248 [01:39<02:55,  9.31it/s]
 28%|██▊       | 623/2248 [01:39<01:46, 15.29it/s]
 28%|██▊       | 628/2248 [01:39<01:19, 20.44it/s]
 28%|██▊       | 634/2248 [01:39<00:59, 26.95it/s]
 28%|██▊       | 640/2248 [01:40<00:48, 33.48it/s]
 29%|██▉       | 647/2248 [01:40<00:38, 41.44it/s]
 29%|██▉       | 653/2248 [01:41<02:26, 10.89it/s]
 29%|██▉       | 657/2248 [01:41<02:15, 11.76it/s]
 29%|██▉       | 661/2248 [01:43<03:58,  6.65it/s]
 30%|██▉       | 664/2248 [01:43<04:02,  6.54it/s]
 30%|██▉       | 666/2248 [01:44<04:18,  6.11it/s]
 30%|██▉       | 669/2248 [01:44<03:26,  7.64it/s]
 30%|██▉       | 671/2248 [01:44<03:23,  7.73it/s]
 30%|██▉       | 673/2248 [01:44<02:55,  8.95it/s]
 30%|███       | 677/2248 [01:44<02:43,  9.61it/s]
 30%|███       | 679/2248 [01:45<03:29,  7.50it/s]
 30%|███       | 681/2248 [01:45<04:00,  6.52it/s]
 30%|███       | 682/2248 [01:46<06:15,  4.17it/s]
 30%|███       | 683/2248 [01:47<08:16,  3.15it/s]
 30%|███       | 684/2248 [01:48<10:25,  2.50it/s]
 30%|███       | 685/2248 [01:48<12:35,  2.07it/s]
 31%|███       | 686/2248 [01:49<12:45,  2.04it/s]
 31%|███       | 687/2248 [01:49<12:27,  2.09it/s]
 31%|███       | 688/2248 [01:50<10:38,  2.44it/s]
 31%|███       | 691/2248 [01:50<07:48,  3.33it/s]
 31%|███       | 692/2248 [01:50<07:08,  3.63it/s]
 31%|███       | 694/2248 [01:51<05:21,  4.84it/s]
 31%|███       | 695/2248 [01:51<05:10,  5.01it/s]
 31%|███       | 697/2248 [01:51<03:49,  6.77it/s]
 31%|███       | 699/2248 [01:51<04:01,  6.42it/s]
 31%|███       | 702/2248 [01:52<04:03,  6.34it/s]
 31%|███▏      | 704/2248 [01:52<04:49,  5.33it/s]
 31%|███▏      | 706/2248 [01:53<05:17,  4.85it/s]
 32%|███▏      | 709/2248 [01:54<06:13,  4.12it/s]
 32%|███▏      | 711/2248 [01:54<06:11,  4.13it/s]
 32%|███▏      | 713/2248 [01:55<07:19,  3.50it/s]
 32%|███▏      | 715/2248 [01:56<07:52,  3.25it/s]
 32%|███▏      | 716/2248 [01:56<08:19,  3.07it/s]
 32%|███▏      | 718/2248 [01:56<06:05,  4.18it/s]
 32%|███▏      | 719/2248 [01:56<06:22,  4.00it/s]
 32%|███▏      | 721/2248 [01:57<05:14,  4.85it/s]
 32%|███▏      | 723/2248 [01:57<04:00,  6.35it/s]
 32%|███▏      | 725/2248 [01:57<03:11,  7.95it/s]
 32%|███▏      | 727/2248 [01:57<02:35,  9.75it/s]
 32%|███▏      | 729/2248 [01:57<03:19,  7.63it/s]
 33%|███▎      | 731/2248 [01:58<04:21,  5.80it/s]
 33%|███▎      | 732/2248 [01:58<04:49,  5.23it/s]
 33%|███▎      | 733/2248 [01:59<06:01,  4.19it/s]
 33%|███▎      | 734/2248 [01:59<05:36,  4.50it/s]
 33%|███▎      | 735/2248 [01:59<06:47,  3.71it/s]
 33%|███▎      | 736/2248 [01:59<06:34,  3.83it/s]
 33%|███▎      | 737/2248 [02:00<08:26,  2.98it/s]
 33%|███▎      | 738/2248 [02:00<07:32,  3.34it/s]
 33%|███▎      | 740/2248 [02:00<04:46,  5.26it/s]
 33%|███▎      | 742/2248 [02:01<05:07,  4.89it/s]
 33%|███▎      | 743/2248 [02:01<06:24,  3.92it/s]
 33%|███▎      | 744/2248 [02:02<09:20,  2.68it/s]
 33%|███▎      | 746/2248 [02:02<06:10,  4.05it/s]
 33%|███▎      | 749/2248 [02:02<05:01,  4.97it/s]
 33%|███▎      | 751/2248 [02:03<05:07,  4.87it/s]
 33%|███▎      | 752/2248 [02:04<07:43,  3.23it/s]
 34%|███▎      | 754/2248 [02:04<06:54,  3.61it/s]
 34%|███▎      | 757/2248 [02:04<04:20,  5.73it/s]
 34%|███▍      | 761/2248 [02:05<03:37,  6.83it/s]
 34%|███▍      | 764/2248 [02:05<02:47,  8.84it/s]
 34%|███▍      | 767/2248 [02:05<02:58,  8.30it/s]
 34%|███▍      | 770/2248 [02:05<02:23, 10.27it/s]
 34%|███▍      | 772/2248 [02:06<03:03,  8.05it/s]
 34%|███▍      | 774/2248 [02:07<04:38,  5.30it/s]
 34%|███▍      | 775/2248 [02:07<04:45,  5.15it/s]
 35%|███▍      | 776/2248 [02:07<04:37,  5.31it/s]
 35%|███▍      | 778/2248 [02:07<04:18,  5.70it/s]
 35%|███▍      | 780/2248 [02:07<03:22,  7.25it/s]
 35%|███▍      | 782/2248 [02:08<03:47,  6.44it/s]
 35%|███▍      | 783/2248 [02:08<03:52,  6.31it/s]
 35%|███▍      | 784/2248 [02:08<03:41,  6.60it/s]
 35%|███▍      | 786/2248 [02:08<02:47,  8.75it/s]
 35%|███▌      | 789/2248 [02:09<03:04,  7.89it/s]
 35%|███▌      | 791/2248 [02:09<03:42,  6.54it/s]
 35%|███▌      | 792/2248 [02:09<04:34,  5.30it/s]
 35%|███▌      | 794/2248 [02:10<04:18,  5.63it/s]
 35%|███▌      | 796/2248 [02:10<03:20,  7.23it/s]
 35%|███▌      | 798/2248 [02:10<03:37,  6.68it/s]
 36%|███▌      | 800/2248 [02:10<03:23,  7.12it/s]
 36%|███▌      | 802/2248 [02:10<02:43,  8.82it/s]
 36%|███▌      | 805/2248 [02:11<01:58, 12.20it/s]
 36%|███▌      | 807/2248 [02:11<02:22, 10.10it/s]
 36%|███▌      | 810/2248 [02:11<02:34,  9.33it/s]
 36%|███▌      | 812/2248 [02:12<03:27,  6.93it/s]
 36%|███▌      | 813/2248 [02:12<03:40,  6.51it/s]
 36%|███▌      | 814/2248 [02:12<05:10,  4.62it/s]
 36%|███▋      | 815/2248 [02:13<06:04,  3.93it/s]
 36%|███▋      | 816/2248 [02:13<07:21,  3.25it/s]
 36%|███▋      | 817/2248 [02:13<06:08,  3.89it/s]
 37%|███▋      | 821/2248 [02:14<02:55,  8.13it/s]
 37%|███▋      | 826/2248 [02:14<02:26,  9.70it/s]
 37%|███▋      | 829/2248 [02:14<02:01, 11.71it/s]
 37%|███▋      | 831/2248 [02:14<01:56, 12.18it/s]
 37%|███▋      | 837/2248 [02:14<01:12, 19.50it/s]
 37%|███▋      | 842/2248 [02:14<00:57, 24.66it/s]
 38%|███▊      | 850/2248 [02:15<00:41, 34.04it/s]
 38%|███▊      | 856/2248 [02:15<00:35, 38.92it/s]
 38%|███▊      | 861/2248 [02:15<00:38, 36.20it/s]
 39%|███▊      | 866/2248 [02:15<01:08, 20.14it/s]
 39%|███▊      | 870/2248 [02:16<02:17, 10.06it/s]
 39%|███▉      | 873/2248 [02:17<02:06, 10.90it/s]
 39%|███▉      | 876/2248 [02:17<02:31,  9.04it/s]
 39%|███▉      | 878/2248 [02:18<03:40,  6.22it/s]
 39%|███▉      | 880/2248 [02:18<03:58,  5.74it/s]
 39%|███▉      | 881/2248 [02:19<04:39,  4.88it/s]
 39%|███▉      | 883/2248 [02:19<03:43,  6.10it/s]
 39%|███▉      | 885/2248 [02:20<05:21,  4.25it/s]
 39%|███▉      | 886/2248 [02:20<07:10,  3.17it/s]
 40%|███▉      | 888/2248 [02:21<07:45,  2.92it/s]
 40%|███▉      | 890/2248 [02:22<08:13,  2.75it/s]
 40%|███▉      | 891/2248 [02:22<08:34,  2.64it/s]
 40%|███▉      | 893/2248 [02:23<06:06,  3.70it/s]
 40%|███▉      | 894/2248 [02:23<06:13,  3.63it/s]
 40%|███▉      | 896/2248 [02:23<05:24,  4.17it/s]
 40%|███▉      | 899/2248 [02:24<04:31,  4.98it/s]
 40%|████      | 902/2248 [02:24<05:02,  4.45it/s]
 40%|████      | 903/2248 [02:25<06:52,  3.26it/s]
 40%|████      | 905/2248 [02:25<05:12,  4.30it/s]
 40%|████      | 906/2248 [02:26<07:19,  3.05it/s]
 40%|████      | 907/2248 [02:27<07:32,  2.97it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 313.04it/s]

[[np.int64(0), False, 6], [np.int64(1), False, 12], [np.int64(2), False, 6], [np.int64(3), False, 11], [np.int64(4), False, 0], [np.int64(5), False, 11], [np.int64(6), False, 13], [np.int64(7), False, 9], [np.int64(8), False, 3], [np.int64(9), False, 6], [np.int64(10), False, 3], [np.int64(11), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2051, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [19:13<3:15:32, 118.51s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [19:13<2:15:34, 83.00s/it]

tensor(12.0943, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4759, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1229, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5503, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [19:14<45:12, 28.55s/it]

tensor(12.1792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5520, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [19:14<31:21, 20.02s/it]

tensor(12.2062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2857, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [19:14<10:31,  6.94s/it]

tensor(12.1593, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4888, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1483, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0341, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7212, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [19:14<05:08,  3.46s/it]

tensor(12.1511, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9195, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1649, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0400, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0397, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [19:15<02:32,  1.76s/it]

tensor(12.1842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0427, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8954, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2046, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0451, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9841, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [19:15<01:18,  1.09it/s]

tensor(12.2126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0469, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9848, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0485, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9622, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [19:15<00:42,  1.96it/s]

tensor(12.1938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0495, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0188, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0504, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9700, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [19:15<00:24,  3.24it/s]

tensor(12.2052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0512, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8759, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2417, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0512, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2829, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 220/300 [19:15<00:20,  3.96it/s]

tensor(12.2802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0514, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3419, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0510, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3341, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [19:16<00:12,  6.04it/s]

tensor(12.2596, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0505, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3530, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0494, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3631, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [19:16<00:10,  7.15it/s]

tensor(12.1918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0485, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1883, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0472, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3704, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [19:16<00:09,  7.76it/s]

tensor(12.1987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0455, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3762, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2056, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0442, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3863, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [19:16<00:08,  8.22it/s]

tensor(12.1983, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0427, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3930, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4027, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [19:17<00:08,  8.33it/s]

tensor(12.1489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0400, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3974, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0382, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3978, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [19:17<00:07,  8.52it/s]

tensor(12.1104, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0365, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4005, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1068, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0351, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4080, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [19:17<00:07,  8.46it/s]

tensor(12.1082, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0333, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4135, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4185, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [19:17<00:07,  8.52it/s]

tensor(12.1047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4126, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0984, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4220, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [19:18<00:07,  8.52it/s]

tensor(12.0914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4322, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0857, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4423, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [19:18<00:06,  8.54it/s]

tensor(12.0818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4431, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4392, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [19:18<00:06,  8.55it/s]

tensor(12.0767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4412, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4399, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [19:18<00:06,  8.56it/s]

tensor(12.0704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4379, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4371, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [19:19<00:06,  8.56it/s]

tensor(12.0645, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4374, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0627, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4441, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [19:19<00:05,  8.55it/s]

tensor(12.0607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4509, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4546, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [19:19<00:05,  8.59it/s]

tensor(12.0551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4551, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([154,  88, 157, 126, 156,  85, 340, 265,  75,  89, 181,  62, 355, 115])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<03:56,  9.49it/s]
  0%|          | 4/2248 [00:00<02:59, 12.50it/s]
  0%|          | 6/2248 [00:00<02:36, 14.29it/s]
  1%|          | 13/2248 [00:00<01:11, 31.22it/s]
  1%|          | 17/2248 [00:00<01:13, 30.28it/s]
  1%|          | 21/2248 [00:00<01:23, 26.66it/s]
  1%|          | 26/2248 [00:00<01:08, 32.37it/s]
  1%|▏         | 33/2248 [00:01<00:52, 41.88it/s]
  2%|▏         | 38/2248 [00:01<01:55, 19.09it/s]
  2%|▏         | 44/2248 [00:01<01:49, 20.11it/s]
  2%|▏         | 48/2248 [00:02<01:52, 19.55it/s]
  2%|▏         | 55/2248 [00:02<01:22, 26.69it/s]
  3%|▎         | 61/2248 [00:02<01:08, 31.78it/s]
  3%|▎         | 67/2248 [00:02<00:58, 37.20it/s]
  3%|▎         | 72/2248 [00:02<00:59, 36.48it/s]
  3%|▎         | 77/2248 [00:03<01:43, 21.05it/s]
  4%|▎         | 81/2248 [00:04<04:01,  8.96it/s]
  4%|▎         | 84/2248 [00:04<03:40,  9.81it/s]
  4%|▍         | 87/2248 [00:04<03:35, 10.03it/s]
  4%|▍         | 89/2248 [00:05<03:51,  9.33it/s]
  4%|▍         | 91/2248 [00:05<04:30,  7.99it/s]
  4%|▍         | 93/2248 [00:05<04:32,  7.91it/s]
  4%|▍         | 95/2248 [00:06<05:33,  6.46it/s]
  4%|▍         | 97/2248 [00:06<05:07,  6.99it/s]
  4%|▍         | 99/2248 [00:06<05:04,  7.06it/s]
  4%|▍         | 100/2248 [00:07<06:41,  5.35it/s]
  5%|▍         | 102/2248 [00:07<05:18,  6.73it/s]
  5%|▍         | 103/2248 [00:07<06:35,  5.42it/s]
  5%|▍         | 104/2248 [00:07<06:48,  5.25it/s]
  5%|▍         | 106/2248 [00:07<04:59,  7.16it/s]
  5%|▍         | 110/2248 [00:08<03:01, 11.78it/s]
  5%|▍         | 112/2248 [00:08<04:22,  8.15it/s]
  5%|▌         | 114/2248 [00:08<04:04,  8.72it/s]
  5%|▌         | 116/2248 [00:09<04:44,  7.49it/s]
  5%|▌         | 118/2248 [00:09<07:44,  4.59it/s]
  5%|▌         | 119/2248 [00:10<08:00,  4.43it/s]
  5%|▌         | 120/2248 [00:10<07:18,  4.86it/s]
  5%|▌         | 121/2248 [00:10<07:08,  4.96it/s]
  5%|▌         | 122/2248 [00:10<08:04,  4.39it/s]
  6%|▌         | 124/2248 [00:10<05:35,  6.33it/s]
  6%|▌         | 126/2248 [00:11<07:35,  4.66it/s]
  6%|▌         | 127/2248 [00:11<08:28,  4.17it/s]
  6%|▌         | 128/2248 [00:12<09:20,  3.78it/s]
  6%|▌         | 130/2248 [00:12<06:24,  5.51it/s]
  6%|▌         | 133/2248 [00:13<06:51,  5.13it/s]
  6%|▌         | 135/2248 [00:13<09:00,  3.91it/s]
  6%|▌         | 136/2248 [00:14<09:13,  3.82it/s]
  6%|▌         | 138/2248 [00:14<10:07,  3.48it/s]
  6%|▋         | 142/2248 [00:15<06:29,  5.41it/s]
  6%|▋         | 144/2248 [00:15<05:16,  6.66it/s]
  6%|▋         | 146/2248 [00:15<06:59,  5.02it/s]
  7%|▋         | 149/2248 [00:15<04:51,  7.19it/s]
  7%|▋         | 151/2248 [00:16<06:24,  5.46it/s]
  7%|▋         | 153/2248 [00:16<05:13,  6.68it/s]
  7%|▋         | 156/2248 [00:17<05:54,  5.91it/s]
  7%|▋         | 158/2248 [00:18<09:38,  3.61it/s]
  7%|▋         | 159/2248 [00:19<11:34,  3.01it/s]
  7%|▋         | 160/2248 [00:19<11:33,  3.01it/s]
  7%|▋         | 162/2248 [00:20<11:31,  3.02it/s]
  7%|▋         | 165/2248 [00:20<08:21,  4.15it/s]
  7%|▋         | 166/2248 [00:21<10:35,  3.27it/s]
  7%|▋         | 168/2248 [00:21<07:46,  4.46it/s]
  8%|▊         | 169/2248 [00:21<07:45,  4.46it/s]
  8%|▊         | 170/2248 [00:21<08:22,  4.13it/s]
  8%|▊         | 171/2248 [00:21<07:30,  4.61it/s]
  8%|▊         | 172/2248 [00:21<06:48,  5.08it/s]
  8%|▊         | 173/2248 [00:22<09:20,  3.70it/s]
  8%|▊         | 175/2248 [00:22<06:26,  5.37it/s]
  8%|▊         | 176/2248 [00:22<07:57,  4.34it/s]
  8%|▊         | 177/2248 [00:23<07:25,  4.65it/s]
  8%|▊         | 178/2248 [00:23<09:21,  3.69it/s]
  8%|▊         | 179/2248 [00:23<08:48,  3.92it/s]
  8%|▊         | 180/2248 [00:24<11:25,  3.02it/s]
  8%|▊         | 182/2248 [00:24<07:07,  4.84it/s]
  8%|▊         | 183/2248 [00:24<08:08,  4.23it/s]
  8%|▊         | 184/2248 [00:25<08:21,  4.11it/s]
  8%|▊         | 185/2248 [00:25<11:57,  2.88it/s]
  8%|▊         | 186/2248 [00:25<10:40,  3.22it/s]
  8%|▊         | 187/2248 [00:26<10:50,  3.17it/s]
  8%|▊         | 188/2248 [00:26<09:59,  3.44it/s]
  8%|▊         | 189/2248 [00:26<09:40,  3.55it/s]
  8%|▊         | 190/2248 [00:26<09:58,  3.44it/s]
  8%|▊         | 191/2248 [00:27<08:47,  3.90it/s]
  9%|▊         | 193/2248 [00:27<07:22,  4.65it/s]
  9%|▊         | 195/2248 [00:27<05:17,  6.47it/s]
  9%|▉         | 197/2248 [00:27<04:17,  7.96it/s]
  9%|▉         | 199/2248 [00:27<03:30,  9.75it/s]
  9%|▉         | 201/2248 [00:28<06:06,  5.58it/s]
  9%|▉         | 202/2248 [00:28<07:09,  4.76it/s]
  9%|▉         | 203/2248 [00:29<07:11,  4.73it/s]
  9%|▉         | 204/2248 [00:29<07:15,  4.69it/s]
  9%|▉         | 205/2248 [00:29<08:01,  4.25it/s]
  9%|▉         | 206/2248 [00:30<11:44,  2.90it/s]
  9%|▉         | 207/2248 [00:30<14:30,  2.34it/s]
  9%|▉         | 208/2248 [00:31<15:58,  2.13it/s]
  9%|▉         | 209/2248 [00:31<14:22,  2.36it/s]
  9%|▉         | 210/2248 [00:32<13:34,  2.50it/s]
  9%|▉         | 211/2248 [00:32<12:50,  2.64it/s]
  9%|▉         | 212/2248 [00:33<15:46,  2.15it/s]
 10%|▉         | 214/2248 [00:33<11:34,  2.93it/s]
 10%|▉         | 216/2248 [00:33<08:50,  3.83it/s]
 10%|▉         | 218/2248 [00:33<06:18,  5.36it/s]
 10%|▉         | 220/2248 [00:34<05:18,  6.37it/s]
 10%|▉         | 223/2248 [00:34<03:41,  9.14it/s]
 10%|█         | 228/2248 [00:34<02:34, 13.06it/s]
 10%|█         | 231/2248 [00:34<02:12, 15.19it/s]
 10%|█         | 236/2248 [00:34<01:43, 19.45it/s]
 11%|█         | 239/2248 [00:34<01:49, 18.33it/s]
 11%|█         | 242/2248 [00:35<01:42, 19.65it/s]
 11%|█         | 249/2248 [00:35<01:48, 18.48it/s]
 11%|█         | 252/2248 [00:35<01:42, 19.51it/s]
 12%|█▏        | 260/2248 [00:35<01:07, 29.53it/s]
 12%|█▏        | 264/2248 [00:36<02:56, 11.25it/s]
 12%|█▏        | 267/2248 [00:37<03:49,  8.65it/s]
 12%|█▏        | 270/2248 [00:38<04:44,  6.96it/s]
 12%|█▏        | 272/2248 [00:38<04:40,  7.05it/s]
 12%|█▏        | 274/2248 [00:38<04:52,  6.74it/s]
 12%|█▏        | 276/2248 [00:39<06:16,  5.23it/s]
 12%|█▏        | 277/2248 [00:39<08:08,  4.03it/s]
 12%|█▏        | 279/2248 [00:40<06:20,  5.18it/s]
 12%|█▏        | 280/2248 [00:40<06:15,  5.24it/s]
 12%|█▎        | 281/2248 [00:40<06:13,  5.27it/s]
 13%|█▎        | 282/2248 [00:40<07:41,  4.26it/s]
 13%|█▎        | 284/2248 [00:41<06:24,  5.11it/s]
 13%|█▎        | 286/2248 [00:41<05:40,  5.77it/s]
 13%|█▎        | 287/2248 [00:41<06:27,  5.06it/s]
 13%|█▎        | 289/2248 [00:41<05:38,  5.78it/s]
 13%|█▎        | 290/2248 [00:42<06:17,  5.18it/s]
 13%|█▎        | 291/2248 [00:42<06:30,  5.01it/s]
 13%|█▎        | 292/2248 [00:42<09:11,  3.55it/s]
 13%|█▎        | 294/2248 [00:43<06:07,  5.31it/s]
 13%|█▎        | 295/2248 [00:43<08:48,  3.70it/s]
 13%|█▎        | 298/2248 [00:44<07:00,  4.64it/s]
 13%|█▎        | 299/2248 [00:44<07:26,  4.36it/s]
 13%|█▎        | 300/2248 [00:44<07:00,  4.64it/s]
 13%|█▎        | 302/2248 [00:44<05:27,  5.94it/s]
 13%|█▎        | 303/2248 [00:45<06:25,  5.04it/s]
 14%|█▎        | 304/2248 [00:45<06:44,  4.80it/s]
 14%|█▎        | 305/2248 [00:45<07:27,  4.34it/s]
 14%|█▎        | 306/2248 [00:45<06:32,  4.95it/s]
 14%|█▎        | 307/2248 [00:45<06:22,  5.08it/s]
 14%|█▎        | 308/2248 [00:46<07:32,  4.29it/s]
 14%|█▎        | 309/2248 [00:46<07:40,  4.21it/s]
 14%|█▍        | 311/2248 [00:46<05:02,  6.41it/s]
 14%|█▍        | 312/2248 [00:46<04:35,  7.02it/s]
 14%|█▍        | 313/2248 [00:47<06:47,  4.74it/s]
 14%|█▍        | 314/2248 [00:47<06:45,  4.77it/s]
 14%|█▍        | 315/2248 [00:47<06:11,  5.21it/s]
 14%|█▍        | 316/2248 [00:47<06:10,  5.22it/s]
 14%|█▍        | 318/2248 [00:47<04:18,  7.47it/s]
 14%|█▍        | 320/2248 [00:48<06:55,  4.64it/s]
 14%|█▍        | 322/2248 [00:48<06:45,  4.75it/s]
 14%|█▍        | 323/2248 [00:49<06:47,  4.72it/s]
 14%|█▍        | 325/2248 [00:49<07:46,  4.12it/s]
 15%|█▍        | 327/2248 [00:49<06:27,  4.96it/s]
 15%|█▍        | 328/2248 [00:50<06:44,  4.75it/s]
 15%|█▍        | 329/2248 [00:50<06:47,  4.71it/s]
 15%|█▍        | 331/2248 [00:50<04:54,  6.52it/s]
 15%|█▍        | 332/2248 [00:50<06:32,  4.88it/s]
 15%|█▍        | 333/2248 [00:51<06:38,  4.80it/s]
 15%|█▍        | 335/2248 [00:51<04:42,  6.76it/s]
 15%|█▌        | 339/2248 [00:51<03:16,  9.73it/s]
 15%|█▌        | 341/2248 [00:51<03:13,  9.83it/s]
 15%|█▌        | 343/2248 [00:51<03:40,  8.66it/s]
 15%|█▌        | 344/2248 [00:52<06:06,  5.20it/s]
 15%|█▌        | 345/2248 [00:52<07:07,  4.45it/s]
 15%|█▌        | 346/2248 [00:53<07:44,  4.10it/s]
 15%|█▌        | 347/2248 [00:53<11:03,  2.86it/s]
 15%|█▌        | 348/2248 [00:54<09:54,  3.19it/s]
 16%|█▌        | 349/2248 [00:54<09:57,  3.18it/s]
 16%|█▌        | 350/2248 [00:54<10:24,  3.04it/s]
 16%|█▌        | 353/2248 [00:55<06:47,  4.65it/s]
 16%|█▌        | 354/2248 [00:55<06:10,  5.11it/s]
 16%|█▌        | 356/2248 [00:55<05:11,  6.08it/s]
 16%|█▌        | 358/2248 [00:55<03:57,  7.94it/s]
 16%|█▌        | 362/2248 [00:55<03:23,  9.28it/s]
 16%|█▌        | 364/2248 [00:56<04:55,  6.37it/s]
 16%|█▋        | 366/2248 [00:57<06:13,  5.04it/s]
 16%|█▋        | 367/2248 [00:57<06:39,  4.71it/s]
 16%|█▋        | 369/2248 [00:57<06:00,  5.22it/s]
 17%|█▋        | 371/2248 [00:58<05:57,  5.25it/s]
 17%|█▋        | 373/2248 [00:58<05:52,  5.32it/s]
 17%|█▋        | 375/2248 [00:58<04:42,  6.63it/s]
 17%|█▋        | 377/2248 [00:59<06:24,  4.86it/s]
 17%|█▋        | 379/2248 [00:59<07:34,  4.11it/s]
 17%|█▋        | 381/2248 [01:00<05:46,  5.39it/s]
 17%|█▋        | 384/2248 [01:00<05:41,  5.46it/s]
 17%|█▋        | 385/2248 [01:00<06:05,  5.10it/s]
 17%|█▋        | 387/2248 [01:00<04:41,  6.61it/s]
 17%|█▋        | 389/2248 [01:01<05:49,  5.32it/s]
 17%|█▋        | 390/2248 [01:01<06:12,  4.99it/s]
 17%|█▋        | 391/2248 [01:01<06:14,  4.96it/s]
 17%|█▋        | 392/2248 [01:02<06:10,  5.00it/s]
 17%|█▋        | 393/2248 [01:02<06:40,  4.63it/s]
 18%|█▊        | 394/2248 [01:02<06:17,  4.91it/s]
 18%|█▊        | 395/2248 [01:02<06:47,  4.54it/s]
 18%|█▊        | 397/2248 [01:03<04:56,  6.24it/s]
 18%|█▊        | 400/2248 [01:03<03:23,  9.10it/s]
 18%|█▊        | 402/2248 [01:03<02:58, 10.33it/s]
 18%|█▊        | 406/2248 [01:03<01:57, 15.66it/s]
 18%|█▊        | 409/2248 [01:03<01:43, 17.80it/s]
 18%|█▊        | 412/2248 [01:03<01:41, 18.10it/s]
 18%|█▊        | 415/2248 [01:03<01:37, 18.75it/s]
 19%|█▊        | 421/2248 [01:03<01:10, 25.76it/s]
 19%|█▉        | 424/2248 [01:04<01:13, 24.77it/s]
 19%|█▉        | 429/2248 [01:04<01:04, 28.06it/s]
 19%|█▉        | 432/2248 [01:04<01:35, 18.97it/s]
 19%|█▉        | 435/2248 [01:04<01:29, 20.31it/s]
 19%|█▉        | 438/2248 [01:05<03:52,  7.78it/s]
 20%|█▉        | 440/2248 [01:06<05:08,  5.86it/s]
 20%|█▉        | 442/2248 [01:06<04:50,  6.21it/s]
 20%|█▉        | 444/2248 [01:07<06:25,  4.68it/s]
 20%|█▉        | 446/2248 [01:08<07:19,  4.10it/s]
 20%|█▉        | 448/2248 [01:08<08:12,  3.66it/s]
 20%|██        | 450/2248 [01:09<08:57,  3.35it/s]
 20%|██        | 453/2248 [01:09<07:04,  4.23it/s]
 20%|██        | 454/2248 [01:10<07:02,  4.24it/s]
 20%|██        | 455/2248 [01:10<09:22,  3.19it/s]
 20%|██        | 457/2248 [01:11<08:02,  3.71it/s]
 20%|██        | 459/2248 [01:11<07:13,  4.12it/s]
 20%|██        | 460/2248 [01:12<09:34,  3.11it/s]
 21%|██        | 462/2248 [01:12<06:49,  4.36it/s]
 21%|██        | 463/2248 [01:12<08:14,  3.61it/s]
 21%|██        | 464/2248 [01:12<07:43,  3.85it/s]
 21%|██        | 465/2248 [01:13<08:34,  3.46it/s]
 21%|██        | 467/2248 [01:13<05:46,  5.14it/s]
 21%|██        | 471/2248 [01:14<05:15,  5.64it/s]
 21%|██        | 472/2248 [01:14<05:49,  5.09it/s]
 21%|██        | 473/2248 [01:14<05:50,  5.07it/s]
 21%|██        | 475/2248 [01:14<05:37,  5.26it/s]
 21%|██        | 476/2248 [01:15<08:12,  3.60it/s]
 21%|██        | 477/2248 [01:15<08:32,  3.45it/s]
 21%|██▏       | 478/2248 [01:16<08:45,  3.37it/s]
 21%|██▏       | 479/2248 [01:16<11:29,  2.57it/s]
 21%|██▏       | 480/2248 [01:17<10:46,  2.74it/s]
 21%|██▏       | 481/2248 [01:17<13:01,  2.26it/s]
 22%|██▏       | 484/2248 [01:17<06:35,  4.46it/s]
 22%|██▏       | 485/2248 [01:18<07:23,  3.98it/s]
 22%|██▏       | 486/2248 [01:19<10:09,  2.89it/s]
 22%|██▏       | 487/2248 [01:19<12:31,  2.34it/s]
 22%|██▏       | 488/2248 [01:20<12:41,  2.31it/s]
 22%|██▏       | 490/2248 [01:20<08:09,  3.59it/s]
 22%|██▏       | 492/2248 [01:20<07:54,  3.70it/s]
 22%|██▏       | 495/2248 [01:21<05:42,  5.12it/s]
 22%|██▏       | 497/2248 [01:21<04:36,  6.33it/s]
 22%|██▏       | 499/2248 [01:21<03:58,  7.33it/s]
 22%|██▏       | 500/2248 [01:21<04:42,  6.19it/s]
 22%|██▏       | 503/2248 [01:21<03:13,  9.03it/s]
 23%|██▎       | 506/2248 [01:21<02:34, 11.29it/s]
 23%|██▎       | 509/2248 [01:22<02:45, 10.50it/s]
 23%|██▎       | 512/2248 [01:22<03:07,  9.26it/s]
 23%|██▎       | 514/2248 [01:23<06:43,  4.30it/s]
 23%|██▎       | 515/2248 [01:24<08:34,  3.37it/s]
 23%|██▎       | 516/2248 [01:25<10:12,  2.83it/s]
 23%|██▎       | 517/2248 [01:25<11:40,  2.47it/s]
 23%|██▎       | 518/2248 [01:26<11:02,  2.61it/s]
 23%|██▎       | 521/2248 [01:26<06:26,  4.47it/s]
 23%|██▎       | 523/2248 [01:26<04:54,  5.86it/s]
 23%|██▎       | 527/2248 [01:26<03:31,  8.15it/s]
 24%|██▎       | 529/2248 [01:26<03:03,  9.39it/s]
 24%|██▎       | 532/2248 [01:26<02:21, 12.16it/s]
 24%|██▍       | 535/2248 [01:27<02:18, 12.33it/s]
 24%|██▍       | 537/2248 [01:27<02:15, 12.64it/s]
 24%|██▍       | 539/2248 [01:27<02:06, 13.52it/s]
 24%|██▍       | 542/2248 [01:27<01:49, 15.59it/s]
 24%|██▍       | 545/2248 [01:27<01:34, 17.96it/s]
 24%|██▍       | 547/2248 [01:27<01:51, 15.31it/s]
 25%|██▍       | 551/2248 [01:28<02:05, 13.54it/s]
 25%|██▍       | 555/2248 [01:28<01:37, 17.31it/s]
 25%|██▍       | 558/2248 [01:28<02:05, 13.49it/s]
 25%|██▍       | 560/2248 [01:28<01:56, 14.43it/s]
 25%|██▌       | 562/2248 [01:29<03:34,  7.87it/s]
 25%|██▌       | 564/2248 [01:30<05:09,  5.43it/s]
 25%|██▌       | 567/2248 [01:30<03:47,  7.40it/s]
 25%|██▌       | 571/2248 [01:30<03:14,  8.61it/s]
 25%|██▌       | 573/2248 [01:31<06:19,  4.41it/s]
 26%|██▌       | 574/2248 [01:32<07:48,  3.57it/s]
 26%|██▌       | 576/2248 [01:32<06:02,  4.61it/s]
 26%|██▌       | 579/2248 [01:33<05:57,  4.67it/s]
 26%|██▌       | 581/2248 [01:33<06:50,  4.06it/s]
 26%|██▌       | 582/2248 [01:34<07:17,  3.81it/s]
 26%|██▌       | 583/2248 [01:34<07:05,  3.92it/s]
 26%|██▌       | 584/2248 [01:34<06:54,  4.01it/s]
 26%|██▌       | 586/2248 [01:35<06:07,  4.52it/s]
 26%|██▌       | 588/2248 [01:35<05:13,  5.29it/s]
 26%|██▌       | 589/2248 [01:35<05:27,  5.07it/s]
 26%|██▋       | 591/2248 [01:35<04:12,  6.56it/s]
 26%|██▋       | 592/2248 [01:36<05:18,  5.19it/s]
 26%|██▋       | 593/2248 [01:36<04:46,  5.77it/s]
 27%|██▋       | 599/2248 [01:36<02:32, 10.80it/s]
 27%|██▋       | 601/2248 [01:36<02:40, 10.29it/s]
 27%|██▋       | 603/2248 [01:37<03:15,  8.42it/s]
 27%|██▋       | 604/2248 [01:37<04:43,  5.81it/s]
 27%|██▋       | 605/2248 [01:37<04:54,  5.57it/s]
 27%|██▋       | 606/2248 [01:37<05:07,  5.33it/s]
 27%|██▋       | 607/2248 [01:38<07:02,  3.88it/s]
 27%|██▋       | 608/2248 [01:38<07:27,  3.66it/s]
 27%|██▋       | 609/2248 [01:39<10:29,  2.60it/s]
 27%|██▋       | 610/2248 [01:40<12:30,  2.18it/s]
 27%|██▋       | 612/2248 [01:40<07:55,  3.44it/s]
 27%|██▋       | 614/2248 [01:40<05:33,  4.89it/s]
 28%|██▊       | 619/2248 [01:40<02:44,  9.87it/s]
 28%|██▊       | 625/2248 [01:40<02:06, 12.87it/s]
 28%|██▊       | 627/2248 [01:40<02:00, 13.44it/s]
 28%|██▊       | 633/2248 [01:41<01:18, 20.65it/s]
 28%|██▊       | 640/2248 [01:41<00:55, 29.18it/s]
 29%|██▊       | 645/2248 [01:41<01:04, 24.87it/s]
 29%|██▉       | 649/2248 [01:41<01:11, 22.52it/s]
 29%|██▉       | 652/2248 [01:42<01:58, 13.42it/s]
 29%|██▉       | 655/2248 [01:42<02:20, 11.31it/s]
 29%|██▉       | 658/2248 [01:43<02:59,  8.84it/s]
 29%|██▉       | 660/2248 [01:43<04:00,  6.60it/s]
 29%|██▉       | 662/2248 [01:44<04:02,  6.55it/s]
 29%|██▉       | 663/2248 [01:44<05:35,  4.73it/s]
 30%|██▉       | 665/2248 [01:45<05:17,  4.99it/s]
 30%|██▉       | 667/2248 [01:45<05:07,  5.14it/s]
 30%|██▉       | 669/2248 [01:45<04:06,  6.40it/s]
 30%|██▉       | 670/2248 [01:45<05:12,  5.05it/s]
 30%|██▉       | 672/2248 [01:46<03:57,  6.63it/s]
 30%|███       | 677/2248 [01:46<03:50,  6.81it/s]
 30%|███       | 681/2248 [01:47<03:27,  7.56it/s]
 30%|███       | 682/2248 [01:47<05:02,  5.18it/s]
 30%|███       | 683/2248 [01:48<05:31,  4.72it/s]
 30%|███       | 684/2248 [01:48<05:57,  4.38it/s]
 30%|███       | 685/2248 [01:49<07:57,  3.27it/s]
 31%|███       | 686/2248 [01:49<08:05,  3.22it/s]
 31%|███       | 687/2248 [01:49<08:00,  3.25it/s]
 31%|███       | 688/2248 [01:50<09:53,  2.63it/s]
 31%|███       | 691/2248 [01:50<06:22,  4.07it/s]
 31%|███       | 692/2248 [01:51<08:28,  3.06it/s]
 31%|███       | 694/2248 [01:51<08:03,  3.21it/s]
 31%|███       | 695/2248 [01:52<07:44,  3.34it/s]
 31%|███       | 698/2248 [01:52<04:50,  5.34it/s]
 31%|███       | 699/2248 [01:52<05:50,  4.41it/s]
 31%|███       | 700/2248 [01:52<05:19,  4.85it/s]
 31%|███       | 702/2248 [01:53<04:39,  5.53it/s]
 31%|███▏      | 704/2248 [01:53<04:40,  5.50it/s]
 31%|███▏      | 706/2248 [01:53<03:35,  7.15it/s]
 32%|███▏      | 709/2248 [01:54<03:33,  7.21it/s]
 32%|███▏      | 710/2248 [01:54<03:23,  7.55it/s]
 32%|███▏      | 711/2248 [01:54<04:38,  5.53it/s]
 32%|███▏      | 712/2248 [01:54<04:24,  5.80it/s]
 32%|███▏      | 713/2248 [01:54<04:17,  5.96it/s]
 32%|███▏      | 714/2248 [01:54<04:27,  5.74it/s]
 32%|███▏      | 715/2248 [01:55<04:07,  6.20it/s]
 32%|███▏      | 716/2248 [01:55<04:29,  5.68it/s]
 32%|███▏      | 717/2248 [01:55<04:11,  6.08it/s]
 32%|███▏      | 719/2248 [01:56<05:39,  4.50it/s]
 32%|███▏      | 720/2248 [01:56<05:26,  4.68it/s]
 32%|███▏      | 721/2248 [01:56<08:47,  2.90it/s]
 32%|███▏      | 723/2248 [01:57<06:41,  3.80it/s]
 32%|███▏      | 725/2248 [01:57<05:31,  4.59it/s]
 32%|███▏      | 726/2248 [01:57<05:32,  4.58it/s]
 32%|███▏      | 727/2248 [01:58<07:54,  3.21it/s]
 32%|███▏      | 728/2248 [01:58<08:04,  3.14it/s]
 32%|███▏      | 729/2248 [01:58<07:09,  3.54it/s]
 32%|███▏      | 730/2248 [01:59<05:53,  4.29it/s]
 33%|███▎      | 731/2248 [01:59<05:38,  4.48it/s]
 33%|███▎      | 732/2248 [01:59<06:33,  3.86it/s]
 33%|███▎      | 733/2248 [01:59<05:37,  4.48it/s]
 33%|███▎      | 734/2248 [02:00<06:58,  3.62it/s]
 33%|███▎      | 735/2248 [02:00<06:08,  4.10it/s]
 33%|███▎      | 736/2248 [02:00<05:40,  4.44it/s]
 33%|███▎      | 737/2248 [02:00<05:30,  4.57it/s]
 33%|███▎      | 738/2248 [02:01<08:23,  3.00it/s]
 33%|███▎      | 739/2248 [02:01<07:25,  3.39it/s]
 33%|███▎      | 742/2248 [02:02<06:33,  3.82it/s]
 33%|███▎      | 743/2248 [02:02<08:18,  3.02it/s]
 33%|███▎      | 744/2248 [02:03<10:02,  2.49it/s]
 33%|███▎      | 746/2248 [02:03<06:32,  3.82it/s]
 33%|███▎      | 749/2248 [02:04<06:16,  3.98it/s]
 33%|███▎      | 751/2248 [02:04<06:48,  3.66it/s]
 33%|███▎      | 752/2248 [02:05<08:09,  3.06it/s]
 34%|███▎      | 754/2248 [02:06<08:13,  3.02it/s]
 34%|███▎      | 757/2248 [02:06<05:13,  4.75it/s]
 34%|███▎      | 758/2248 [02:06<05:13,  4.75it/s]
 34%|███▍      | 761/2248 [02:07<05:19,  4.65it/s]
 34%|███▍      | 763/2248 [02:07<04:59,  4.95it/s]
 34%|███▍      | 765/2248 [02:07<04:01,  6.13it/s]
 34%|███▍      | 767/2248 [02:08<05:26,  4.53it/s]
 34%|███▍      | 770/2248 [02:08<03:44,  6.58it/s]
 34%|███▍      | 772/2248 [02:09<04:55,  5.00it/s]
 34%|███▍      | 773/2248 [02:09<06:34,  3.74it/s]
 34%|███▍      | 774/2248 [02:10<08:15,  2.97it/s]
 34%|███▍      | 775/2248 [02:10<09:41,  2.53it/s]
 35%|███▍      | 776/2248 [02:11<11:09,  2.20it/s]
 35%|███▍      | 778/2248 [02:12<09:48,  2.50it/s]
 35%|███▍      | 781/2248 [02:12<05:45,  4.24it/s]
 35%|███▍      | 782/2248 [02:13<07:32,  3.24it/s]
 35%|███▍      | 783/2248 [02:13<09:02,  2.70it/s]
 35%|███▍      | 784/2248 [02:14<10:36,  2.30it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 322.59it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 12], [np.int64(2), False, 7], [np.int64(3), False, 0], [np.int64(4), False, 9], [np.int64(5), False, 13], [np.int64(6), False, 12], [np.int64(8), False, 9], [np.int64(10), False, 7], [np.int64(11), False, 12]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0515, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1953, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [25:18<1:28:07, 107.90s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [25:18<1:00:27, 75.58s/it]

tensor(12.0502, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4764, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [25:19<19:29, 26.00s/it]

tensor(12.0626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4608, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0670, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5191, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [25:19<09:10, 12.80s/it]

tensor(12.0676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5382, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5310, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [25:19<04:19,  6.33s/it]

tensor(12.0560, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5148, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5039, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [25:20<02:03,  3.16s/it]

tensor(12.0464, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5050, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0430, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5240, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [25:20<00:59,  1.61s/it]

tensor(12.0425, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5395, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5450, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [25:20<00:29,  1.18it/s]

tensor(12.0440, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5472, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0432, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5473, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [25:20<00:15,  2.11it/s]

tensor(12.0420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5401, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5401, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [25:20<00:09,  3.42it/s]

tensor(12.0354, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5385, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5388, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [25:21<00:05,  4.95it/s]

tensor(12.0304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5370, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5419, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [25:21<00:04,  6.30it/s]

tensor(12.0270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5409, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5454, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [25:21<00:03,  7.31it/s]

tensor(12.0263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5416, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5450, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [25:21<00:02,  7.94it/s]

tensor(12.0248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5455, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5444, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [25:22<00:02,  8.26it/s]

tensor(12.0227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5418, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5408, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [25:22<00:02,  8.47it/s]

tensor(12.0199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5386, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5325, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [25:22<00:01,  8.50it/s]

tensor(12.0173, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5341, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5334, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [25:22<00:01,  8.62it/s]

tensor(12.0153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5287, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0141, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5235, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [25:23<00:01,  8.56it/s]

tensor(12.0131, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5233, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5195, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [25:23<00:01,  8.60it/s]

tensor(12.0115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5130, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [25:23<00:01,  8.53it/s]

tensor(12.0101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5116, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [25:23<00:00,  8.58it/s]

tensor(12.0088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5145, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0081, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5145, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [25:23<00:00,  8.50it/s]

tensor(12.0075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5145, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5170, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [25:24<00:00,  8.62it/s]

tensor(12.0063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5187, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [25:24<00:00,  8.61it/s]

tensor(12.0050, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5183, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5186, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [25:24<00:00,  5.08s/it]

tensor(12.0036, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0207, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5189, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.002195596694946289
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 5
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.313077154310
NMI         : 0.477885704940
Runtime     : 1545.24 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed5

==============================================================================================================
PRAGA RUN | S2-E18 | seed=6
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 1.092e-16
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:33,  9.01it/s]

tensor(15.9556, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9572, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8045, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:30,  9.71it/s]

tensor(15.9428, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7167, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9242, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9075, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1376, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:29,  9.82it/s]

tensor(15.8900, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6078, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8794, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2290, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8697, device='cuda:0', grad_fn=<AddBackward0>)

  3%|▎         | 9/300 [00:00<00:29,  9.90it/s]

tensor(10.9863, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8632, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8660, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8580, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8558, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:28,  9.97it/s]

tensor(15.8536, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9458, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8498, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8448, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3866, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:28, 10.00it/s]

tensor(15.8392, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7203, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8325, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8261, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5800, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:28, 10.05it/s]

tensor(15.8185, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0928, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8092, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6541, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:28,  9.84it/s]

tensor(15.8002, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2594, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7913, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9032, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:28,  9.89it/s]

tensor(15.7813, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5834, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7704, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2954, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7583, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0367, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:27, 10.15it/s]

tensor(15.7447, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8029, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7288, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5937, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7111, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4051, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:26, 10.19it/s]

tensor(15.6909, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2361, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6682, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0836, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6431, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9476, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 31/300 [00:03<00:26, 10.26it/s]

tensor(15.6151, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5848, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7162, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6181, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:26, 10.25it/s]

tensor(15.5171, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4522, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4413, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3831, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 37/300 [00:03<00:26, 10.10it/s]

tensor(15.4013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3600, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2669, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2190, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:25, 10.17it/s]

tensor(15.2752, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1772, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2320, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1408, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1103, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:25, 10.26it/s]

tensor(15.1458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0853, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0656, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0511, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:25, 10.19it/s]

tensor(15.0148, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0410, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9692, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:04<00:24, 10.28it/s]

tensor(14.8724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:05<00:24, 10.22it/s]

tensor(14.7120, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:23, 10.28it/s]

tensor(14.5391, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4802, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:23, 10.16it/s]

tensor(14.3634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|█▉        | 59/300 [00:05<00:24, 10.04it/s]

tensor(14.2557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2089, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1676, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:23, 10.11it/s]

tensor(14.1307, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 65/300 [00:06<00:23, 10.10it/s]

tensor(14.0651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0004, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:22, 10.16it/s]

tensor(13.9648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▎       | 71/300 [00:07<00:22, 10.11it/s]

tensor(13.8592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8287, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:22, 10.06it/s]

tensor(13.7998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7721, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7456, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:22, 10.06it/s]

tensor(13.7199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6685, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:07<00:22,  9.98it/s]

tensor(13.6420, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6150, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5879, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:21, 10.05it/s]

tensor(13.5608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5342, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:21, 10.04it/s]

tensor(13.4823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4344, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:08<00:20, 10.20it/s]

tensor(13.4114, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3674, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:08<00:20, 10.03it/s]

tensor(13.3460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3251, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:20, 10.02it/s]

tensor(13.3045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2843, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2647, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:20, 10.15it/s]

tensor(13.2455, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2269, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2087, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:09<00:19, 10.16it/s]

tensor(13.1907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1562, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:09<00:19, 10.22it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([263,  96,  91, 147, 121, 236, 139, 211,  76, 139, 118, 102,  60, 449])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:42, 13.85it/s]
  0%|          | 4/2248 [00:00<02:22, 15.72it/s]
  0%|          | 7/2248 [00:00<02:07, 17.61it/s]
  0%|          | 10/2248 [00:00<01:51, 20.15it/s]
  1%|          | 16/2248 [00:00<01:11, 31.41it/s]
  1%|          | 22/2248 [00:00<00:57, 38.82it/s]
  1%|▏         | 30/2248 [00:00<00:43, 50.50it/s]
  2%|▏         | 36/2248 [00:01<01:10, 31.58it/s]
  2%|▏         | 41/2248 [00:01<01:22, 26.90it/s]
  2%|▏         | 45/2248 [00:01<01:40, 21.98it/s]
  2%|▏         | 48/2248 [00:01<01:38, 22.32it/s]
  2%|▏         | 51/2248 [00:01<01:35, 23.08it/s]
  2%|▏         | 54/2248 [00:02<02:22, 15.41it/s]
  3%|▎         | 57/2248 [00:02<02:45, 13.26it/s]
  3%|▎         | 62/2248 [00:02<02:33, 14.26it/s]
  3%|▎         | 64/2248 [00:03<02:29, 14.63it/s]
  3%|▎         | 66/2248 [00:03<02:57, 12.29it/s]
  3%|▎         | 69/2248 [00:03<02:29, 14.61it/s]
  3%|▎         | 73/2248 [00:03<01:54, 19.00it/s]
  3%|▎         | 76/2248 [00:04<03:22, 10.75it/s]
  3%|▎         | 78/2248 [00:04<03:13, 11.24it/s]
  4%|▎         | 80/2248 [00:04<03:01, 11.92it/s]
  4%|▎         | 82/2248 [00:04<03:52,  9.30it/s]
  4%|▎         | 84/2248 [00:04<03:37,  9.97it/s]
  4%|▍         | 86/2248 [00:05<04:11,  8.61it/s]
  4%|▍         | 88/2248 [00:05<03:53,  9.27it/s]
  4%|▍         | 90/2248 [00:06<07:21,  4.89it/s]
  4%|▍         | 92/2248 [00:06<05:49,  6.16it/s]
  4%|▍         | 94/2248 [00:06<05:51,  6.13it/s]
  4%|▍         | 96/2248 [00:07<05:12,  6.89it/s]
  4%|▍         | 97/2248 [00:07<06:01,  5.95it/s]
  4%|▍         | 98/2248 [00:07<06:03,  5.91it/s]
 33%|███▎      | 100/300 [00:20<00:19, 10.22it/s]]
  4%|▍         | 101/2248 [00:07<05:45,  6.21it/s]
  5%|▍         | 102/2248 [00:08<06:11,  5.77it/s]
  5%|▍         | 103/2248 [00:08<07:15,  4.93it/s]
  5%|▍         | 104/2248 [00:08<07:53,  4.53it/s]
  5%|▍         | 106/2248 [00:08<05:23,  6.61it/s]
  5%|▍         | 108/2248 [00:08<04:18,  8.28it/s]
  5%|▍         | 110/2248 [00:09<04:02,  8.80it/s]
  5%|▍         | 112/2248 [00:09<05:30,  6.46it/s]
  5%|▌         | 113/2248 [00:09<05:39,  6.29it/s]
  5%|▌         | 115/2248 [00:09<04:19,  8.21it/s]
  5%|▌         | 117/2248 [00:10<03:58,  8.92it/s]
  5%|▌         | 119/2248 [00:10<05:00,  7.08it/s]
  5%|▌         | 120/2248 [00:10<06:15,  5.67it/s]
  5%|▌         | 121/2248 [00:10<06:29,  5.46it/s]
  5%|▌         | 122/2248 [00:11<07:51,  4.51it/s]
  5%|▌         | 123/2248 [00:11<07:38,  4.63it/s]
  6%|▌         | 125/2248 [00:11<07:25,  4.77it/s]
  6%|▌         | 126/2248 [00:12<08:32,  4.14it/s]
  6%|▌         | 127/2248 [00:12<09:03,  3.91it/s]
  6%|▌         | 128/2248 [00:13<10:32,  3.35it/s]
  6%|▌         | 130/2248 [00:13<07:09,  4.93it/s]
  6%|▌         | 132/2248 [00:13<05:17,  6.66it/s]
  6%|▌         | 133/2248 [00:13<06:30,  5.42it/s]
  6%|▌         | 135/2248 [00:14<07:58,  4.42it/s]
  6%|▌         | 136/2248 [00:14<08:55,  3.95it/s]
  6%|▌         | 138/2248 [00:14<07:38,  4.61it/s]
  6%|▌         | 140/2248 [00:15<08:44,  4.02it/s]
  6%|▋         | 142/2248 [00:15<06:30,  5.39it/s]
  6%|▋         | 144/2248 [00:15<05:09,  6.81it/s]
  6%|▋         | 146/2248 [00:16<06:51,  5.11it/s]
  7%|▋         | 148/2248 [00:16<05:24,  6.48it/s]
  7%|▋         | 150/2248 [00:16<04:16,  8.16it/s]
  7%|▋         | 152/2248 [00:17<07:17,  4.79it/s]
  7%|▋         | 154/2248 [00:17<05:46,  6.05it/s]
  7%|▋         | 156/2248 [00:17<05:49,  5.99it/s]
  7%|▋         | 158/2248 [00:18<05:37,  6.19it/s]
  7%|▋         | 159/2248 [00:18<05:47,  6.02it/s]
  7%|▋         | 160/2248 [00:18<06:03,  5.75it/s]
  7%|▋         | 162/2248 [00:18<06:16,  5.55it/s]
  7%|▋         | 164/2248 [00:19<04:54,  7.08it/s]
  7%|▋         | 165/2248 [00:19<06:26,  5.39it/s]
  7%|▋         | 166/2248 [00:19<07:54,  4.39it/s]
  7%|▋         | 168/2248 [00:19<05:39,  6.13it/s]
  8%|▊         | 169/2248 [00:20<05:29,  6.31it/s]
  8%|▊         | 170/2248 [00:20<05:27,  6.35it/s]
  8%|▊         | 172/2248 [00:20<04:35,  7.54it/s]
  8%|▊         | 174/2248 [00:20<04:02,  8.55it/s]
  8%|▊         | 176/2248 [00:20<04:17,  8.05it/s]
  8%|▊         | 178/2248 [00:21<05:31,  6.25it/s]
  8%|▊         | 180/2248 [00:21<07:15,  4.75it/s]
  8%|▊         | 182/2248 [00:22<05:47,  5.95it/s]
  8%|▊         | 184/2248 [00:22<04:52,  7.05it/s]
  8%|▊         | 185/2248 [00:22<06:57,  4.94it/s]
  8%|▊         | 186/2248 [00:22<06:22,  5.39it/s]
  8%|▊         | 187/2248 [00:23<06:13,  5.52it/s]
  8%|▊         | 188/2248 [00:23<05:33,  6.18it/s]
  8%|▊         | 190/2248 [00:23<04:22,  7.83it/s]
  8%|▊         | 191/2248 [00:23<04:59,  6.87it/s]
  9%|▊         | 192/2248 [00:23<05:30,  6.22it/s]
  9%|▊         | 193/2248 [00:23<06:16,  5.45it/s]
  9%|▊         | 196/2248 [00:24<03:47,  9.04it/s]
  9%|▉         | 198/2248 [00:24<03:10, 10.73it/s]
  9%|▉         | 200/2248 [00:24<03:14, 10.53it/s]
  9%|▉         | 202/2248 [00:25<06:05,  5.60it/s]
  9%|▉         | 203/2248 [00:25<06:09,  5.54it/s]
  9%|▉         | 204/2248 [00:25<06:07,  5.55it/s]
  9%|▉         | 205/2248 [00:26<09:22,  3.63it/s]
  9%|▉         | 206/2248 [00:26<10:11,  3.34it/s]
  9%|▉         | 207/2248 [00:26<09:59,  3.41it/s]
  9%|▉         | 208/2248 [00:26<08:32,  3.98it/s]
  9%|▉         | 209/2248 [00:27<08:33,  3.97it/s]
  9%|▉         | 210/2248 [00:27<08:07,  4.18it/s]
  9%|▉         | 211/2248 [00:27<08:49,  3.85it/s]
  9%|▉         | 212/2248 [00:27<07:58,  4.26it/s]
 10%|▉         | 214/2248 [00:27<05:12,  6.50it/s]
 10%|▉         | 216/2248 [00:28<04:02,  8.40it/s]
 10%|▉         | 219/2248 [00:28<02:56, 11.51it/s]
 10%|█         | 225/2248 [00:28<01:39, 20.35it/s]
 10%|█         | 231/2248 [00:28<01:11, 28.37it/s]
 11%|█         | 238/2248 [00:28<00:53, 37.81it/s]
 11%|█         | 243/2248 [00:28<00:53, 37.66it/s]
 11%|█         | 250/2248 [00:28<00:46, 42.73it/s]
 11%|█▏        | 258/2248 [00:28<00:38, 51.03it/s]
 12%|█▏        | 264/2248 [00:29<01:32, 21.46it/s]
 12%|█▏        | 269/2248 [00:29<01:20, 24.60it/s]
 12%|█▏        | 274/2248 [00:30<02:29, 13.24it/s]
 12%|█▏        | 278/2248 [00:31<03:06, 10.56it/s]
 12%|█▎        | 281/2248 [00:31<02:42, 12.08it/s]
 13%|█▎        | 284/2248 [00:31<03:33,  9.20it/s]
 13%|█▎        | 287/2248 [00:32<04:15,  7.69it/s]
 13%|█▎        | 289/2248 [00:32<04:25,  7.39it/s]
 13%|█▎        | 291/2248 [00:33<07:11,  4.54it/s]
 13%|█▎        | 294/2248 [00:34<05:27,  5.97it/s]
 13%|█▎        | 296/2248 [00:34<04:38,  7.01it/s]
 13%|█▎        | 300/2248 [00:34<03:13, 10.07it/s]
 13%|█▎        | 303/2248 [00:34<04:15,  7.62it/s]
 14%|█▎        | 306/2248 [00:35<04:59,  6.49it/s]
 14%|█▎        | 308/2248 [00:36<07:50,  4.12it/s]
 14%|█▎        | 309/2248 [00:37<09:04,  3.56it/s]
 14%|█▍        | 310/2248 [00:37<08:38,  3.74it/s]
 14%|█▍        | 312/2248 [00:37<06:41,  4.83it/s]
 14%|█▍        | 313/2248 [00:37<07:27,  4.32it/s]
 14%|█▍        | 314/2248 [00:38<07:08,  4.52it/s]
 14%|█▍        | 315/2248 [00:38<07:57,  4.05it/s]
 14%|█▍        | 317/2248 [00:38<05:39,  5.68it/s]
 14%|█▍        | 318/2248 [00:38<06:13,  5.17it/s]
 14%|█▍        | 320/2248 [00:39<06:05,  5.27it/s]
 14%|█▍        | 322/2248 [00:39<05:46,  5.56it/s]
 14%|█▍        | 323/2248 [00:40<08:23,  3.82it/s]
 14%|█▍        | 325/2248 [00:40<07:21,  4.36it/s]
 15%|█▍        | 327/2248 [00:40<06:38,  4.82it/s]
 15%|█▍        | 329/2248 [00:40<05:02,  6.34it/s]
 15%|█▍        | 331/2248 [00:40<04:03,  7.87it/s]
 15%|█▍        | 333/2248 [00:41<03:53,  8.20it/s]
 15%|█▍        | 336/2248 [00:41<02:47, 11.40it/s]
 15%|█▌        | 338/2248 [00:41<02:32, 12.54it/s]
 15%|█▌        | 340/2248 [00:41<03:47,  8.40it/s]
 15%|█▌        | 342/2248 [00:41<03:12,  9.92it/s]
 15%|█▌        | 344/2248 [00:42<07:03,  4.50it/s]
 15%|█▌        | 346/2248 [00:43<05:35,  5.67it/s]
 15%|█▌        | 348/2248 [00:43<06:43,  4.71it/s]
 16%|█▌        | 349/2248 [00:44<08:26,  3.75it/s]
 16%|█▌        | 350/2248 [00:44<09:34,  3.30it/s]
 16%|█▌        | 353/2248 [00:45<08:13,  3.84it/s]
 16%|█▌        | 355/2248 [00:45<06:12,  5.08it/s]
 16%|█▌        | 356/2248 [00:45<08:13,  3.84it/s]
 16%|█▌        | 358/2248 [00:46<06:02,  5.22it/s]
 16%|█▌        | 362/2248 [00:46<05:41,  5.52it/s]
 16%|█▌        | 364/2248 [00:47<06:41,  4.69it/s]
 16%|█▋        | 366/2248 [00:47<07:26,  4.21it/s]
 16%|█▋        | 368/2248 [00:48<05:55,  5.29it/s]
 17%|█▋        | 371/2248 [00:48<04:55,  6.34it/s]
 17%|█▋        | 373/2248 [00:48<04:05,  7.63it/s]
 17%|█▋        | 376/2248 [00:48<03:05, 10.08it/s]
 17%|█▋        | 378/2248 [00:48<03:14,  9.64it/s]
 17%|█▋        | 381/2248 [00:48<02:27, 12.65it/s]
 17%|█▋        | 384/2248 [00:49<02:50, 10.93it/s]
 17%|█▋        | 386/2248 [00:49<03:50,  8.06it/s]
 17%|█▋        | 388/2248 [00:50<04:32,  6.81it/s]
 17%|█▋        | 389/2248 [00:50<05:01,  6.16it/s]
 17%|█▋        | 391/2248 [00:50<04:01,  7.69it/s]
 17%|█▋        | 393/2248 [00:50<03:44,  8.25it/s]
 18%|█▊        | 395/2248 [00:51<06:12,  4.98it/s]
 18%|█▊        | 397/2248 [00:51<04:49,  6.38it/s]
 18%|█▊        | 399/2248 [00:51<04:01,  7.66it/s]
 18%|█▊        | 401/2248 [00:52<04:07,  7.47it/s]
 18%|█▊        | 403/2248 [00:52<04:02,  7.62it/s]
 18%|█▊        | 404/2248 [00:52<04:33,  6.73it/s]
 18%|█▊        | 407/2248 [00:52<03:44,  8.22it/s]
 18%|█▊        | 409/2248 [00:52<03:07,  9.82it/s]
 18%|█▊        | 412/2248 [00:53<02:51, 10.71it/s]
 18%|█▊        | 414/2248 [00:53<03:06,  9.85it/s]
 19%|█▊        | 416/2248 [00:53<03:25,  8.93it/s]
 19%|█▊        | 420/2248 [00:53<02:15, 13.45it/s]
 19%|█▉        | 422/2248 [00:54<02:28, 12.26it/s]
 19%|█▉        | 424/2248 [00:54<02:47, 10.92it/s]
 19%|█▉        | 427/2248 [00:54<02:54, 10.44it/s]
 19%|█▉        | 431/2248 [00:54<02:06, 14.41it/s]
 19%|█▉        | 434/2248 [00:54<02:08, 14.17it/s]
 19%|█▉        | 436/2248 [00:55<03:38,  8.28it/s]
 19%|█▉        | 438/2248 [00:56<04:54,  6.15it/s]
 20%|█▉        | 440/2248 [00:56<05:52,  5.12it/s]
 20%|█▉        | 441/2248 [00:56<06:02,  4.99it/s]
 20%|█▉        | 443/2248 [00:56<04:39,  6.46it/s]
 20%|█▉        | 446/2248 [00:57<05:08,  5.83it/s]
 20%|█▉        | 449/2248 [00:57<03:44,  8.00it/s]
 20%|██        | 451/2248 [00:58<05:01,  5.97it/s]
 20%|██        | 454/2248 [00:58<04:12,  7.11it/s]
 20%|██        | 456/2248 [00:59<05:21,  5.58it/s]
 20%|██        | 460/2248 [00:59<04:58,  5.99it/s]
 21%|██        | 462/2248 [01:00<04:45,  6.26it/s]
 21%|██        | 463/2248 [01:00<06:33,  4.53it/s]
 21%|██        | 464/2248 [01:01<08:29,  3.50it/s]
 21%|██        | 466/2248 [01:01<06:13,  4.77it/s]
 21%|██        | 467/2248 [01:01<06:22,  4.65it/s]
 21%|██        | 469/2248 [01:01<05:44,  5.17it/s]
 21%|██        | 472/2248 [01:02<06:03,  4.89it/s]
 21%|██        | 473/2248 [01:02<06:06,  4.85it/s]
 21%|██        | 475/2248 [01:03<07:24,  3.99it/s]
 21%|██        | 476/2248 [01:04<09:27,  3.12it/s]
 21%|██▏       | 479/2248 [01:04<08:14,  3.57it/s]
 21%|██▏       | 480/2248 [01:05<09:59,  2.95it/s]
 21%|██▏       | 481/2248 [01:05<09:53,  2.98it/s]
 21%|██▏       | 482/2248 [01:05<09:04,  3.24it/s]
 22%|██▏       | 484/2248 [01:06<06:22,  4.61it/s]
 22%|██▏       | 485/2248 [01:06<06:28,  4.54it/s]
 22%|██▏       | 486/2248 [01:06<08:36,  3.41it/s]
 22%|██▏       | 488/2248 [01:06<05:44,  5.10it/s]
 22%|██▏       | 491/2248 [01:07<04:06,  7.12it/s]
 22%|██▏       | 495/2248 [01:07<04:22,  6.69it/s]
 22%|██▏       | 496/2248 [01:07<04:40,  6.25it/s]
 22%|██▏       | 498/2248 [01:08<04:27,  6.54it/s]
 22%|██▏       | 499/2248 [01:08<06:34,  4.43it/s]
 22%|██▏       | 500/2248 [01:09<08:25,  3.46it/s]
 22%|██▏       | 502/2248 [01:09<06:35,  4.41it/s]
 22%|██▏       | 503/2248 [01:10<08:43,  3.33it/s]
 23%|██▎       | 506/2248 [01:10<05:51,  4.95it/s]
 23%|██▎       | 508/2248 [01:10<05:12,  5.57it/s]
 23%|██▎       | 509/2248 [01:11<07:17,  3.97it/s]
 23%|██▎       | 510/2248 [01:11<09:11,  3.15it/s]
 23%|██▎       | 513/2248 [01:12<07:35,  3.81it/s]
 23%|██▎       | 515/2248 [01:13<08:17,  3.48it/s]
 23%|██▎       | 517/2248 [01:13<06:20,  4.55it/s]
 23%|██▎       | 518/2248 [01:13<06:50,  4.22it/s]
 23%|██▎       | 520/2248 [01:13<05:49,  4.95it/s]
 23%|██▎       | 523/2248 [01:14<03:55,  7.32it/s]
 24%|██▎       | 529/2248 [01:14<02:05, 13.66it/s]
 24%|██▎       | 532/2248 [01:14<01:53, 15.14it/s]
 24%|██▍       | 535/2248 [01:14<01:57, 14.57it/s]
 24%|██▍       | 540/2248 [01:14<01:23, 20.39it/s]
 24%|██▍       | 544/2248 [01:14<01:29, 19.03it/s]
 24%|██▍       | 547/2248 [01:15<01:39, 17.12it/s]
 24%|██▍       | 550/2248 [01:15<01:32, 18.37it/s]
 25%|██▍       | 555/2248 [01:15<01:10, 23.86it/s]
 25%|██▍       | 558/2248 [01:15<01:48, 15.56it/s]
 25%|██▍       | 561/2248 [01:15<01:38, 17.14it/s]
 25%|██▌       | 569/2248 [01:15<00:59, 28.06it/s]
 25%|██▌       | 573/2248 [01:17<03:36,  7.74it/s]
 26%|██▌       | 576/2248 [01:18<04:09,  6.70it/s]
 26%|██▌       | 579/2248 [01:19<06:01,  4.61it/s]
 26%|██▌       | 581/2248 [01:20<06:39,  4.18it/s]
 26%|██▌       | 583/2248 [01:20<06:38,  4.18it/s]
 26%|██▌       | 585/2248 [01:20<05:29,  5.05it/s]
 26%|██▌       | 587/2248 [01:21<06:15,  4.42it/s]
 26%|██▋       | 591/2248 [01:21<03:57,  6.98it/s]
 26%|██▋       | 593/2248 [01:22<04:58,  5.55it/s]
 27%|██▋       | 596/2248 [01:22<03:41,  7.45it/s]
 27%|██▋       | 599/2248 [01:22<04:08,  6.65it/s]
 27%|██▋       | 601/2248 [01:22<03:31,  7.79it/s]
 27%|██▋       | 603/2248 [01:23<04:36,  5.94it/s]
 27%|██▋       | 605/2248 [01:24<07:23,  3.71it/s]
 27%|██▋       | 606/2248 [01:25<08:39,  3.16it/s]
 27%|██▋       | 607/2248 [01:25<09:52,  2.77it/s]
 27%|██▋       | 608/2248 [01:26<09:46,  2.80it/s]
 27%|██▋       | 609/2248 [01:26<09:54,  2.76it/s]
 27%|██▋       | 610/2248 [01:26<09:46,  2.79it/s]
 27%|██▋       | 612/2248 [01:26<06:17,  4.33it/s]
 27%|██▋       | 617/2248 [01:27<03:25,  7.94it/s]
 28%|██▊       | 619/2248 [01:27<03:28,  7.80it/s]
 28%|██▊       | 621/2248 [01:27<03:20,  8.11it/s]
 28%|██▊       | 624/2248 [01:27<02:30, 10.81it/s]
 28%|██▊       | 626/2248 [01:27<02:35, 10.40it/s]
 28%|██▊       | 628/2248 [01:28<02:43,  9.92it/s]
 28%|██▊       | 630/2248 [01:28<02:53,  9.30it/s]
 28%|██▊       | 632/2248 [01:28<03:02,  8.85it/s]
 28%|██▊       | 635/2248 [01:28<02:16, 11.85it/s]
 28%|██▊       | 637/2248 [01:29<02:34, 10.42it/s]
 29%|██▊       | 641/2248 [01:29<02:12, 12.16it/s]
 29%|██▊       | 644/2248 [01:29<01:49, 14.62it/s]
 29%|██▉       | 650/2248 [01:30<02:17, 11.63it/s]
 29%|██▉       | 652/2248 [01:30<03:22,  7.87it/s]
 29%|██▉       | 654/2248 [01:31<04:19,  6.15it/s]
 29%|██▉       | 656/2248 [01:31<03:39,  7.26it/s]
 29%|██▉       | 658/2248 [01:31<04:06,  6.46it/s]
 29%|██▉       | 660/2248 [01:32<04:26,  5.95it/s]
 29%|██▉       | 661/2248 [01:32<04:49,  5.48it/s]
 29%|██▉       | 662/2248 [01:32<04:43,  5.60it/s]
 29%|██▉       | 663/2248 [01:32<05:42,  4.63it/s]
 30%|██▉       | 665/2248 [01:33<05:28,  4.82it/s]
 30%|██▉       | 666/2248 [01:33<05:58,  4.41it/s]
 30%|██▉       | 668/2248 [01:33<04:37,  5.70it/s]
 30%|██▉       | 670/2248 [01:34<04:20,  6.06it/s]
 30%|██▉       | 672/2248 [01:34<03:20,  7.87it/s]
 30%|██▉       | 674/2248 [01:34<03:01,  8.66it/s]
 30%|███       | 676/2248 [01:34<02:39,  9.87it/s]
 30%|███       | 678/2248 [01:35<04:28,  5.84it/s]
 30%|███       | 680/2248 [01:35<03:38,  7.19it/s]
 30%|███       | 682/2248 [01:36<05:26,  4.79it/s]
 30%|███       | 684/2248 [01:36<04:15,  6.11it/s]
 31%|███       | 686/2248 [01:36<05:10,  5.02it/s]
 31%|███       | 687/2248 [01:37<06:58,  3.73it/s]
 31%|███       | 688/2248 [01:37<08:34,  3.03it/s]
 31%|███       | 689/2248 [01:38<07:57,  3.27it/s]
 31%|███       | 692/2248 [01:38<06:39,  3.89it/s]
 31%|███       | 694/2248 [01:38<04:57,  5.21it/s]
 31%|███       | 696/2248 [01:39<04:20,  5.96it/s]
 31%|███       | 699/2248 [01:39<04:52,  5.29it/s]
 31%|███       | 700/2248 [01:39<04:55,  5.23it/s]
 31%|███       | 702/2248 [01:40<05:42,  4.52it/s]
 31%|███▏      | 704/2248 [01:41<06:29,  3.96it/s]
 31%|███▏      | 706/2248 [01:41<04:54,  5.23it/s]
 32%|███▏      | 710/2248 [01:41<03:20,  7.67it/s]
 32%|███▏      | 712/2248 [01:42<04:30,  5.68it/s]
 32%|███▏      | 715/2248 [01:42<03:15,  7.86it/s]
 32%|███▏      | 717/2248 [01:42<03:09,  8.09it/s]
 32%|███▏      | 719/2248 [01:43<04:47,  5.32it/s]
 32%|███▏      | 722/2248 [01:43<03:25,  7.41it/s]
 32%|███▏      | 727/2248 [01:43<02:05, 12.12it/s]
 32%|███▏      | 730/2248 [01:44<03:49,  6.61it/s]
 33%|███▎      | 733/2248 [01:45<04:21,  5.78it/s]
 33%|███▎      | 735/2248 [01:45<05:04,  4.97it/s]
 33%|███▎      | 737/2248 [01:46<06:38,  3.79it/s]
 33%|███▎      | 738/2248 [01:47<07:42,  3.27it/s]
 33%|███▎      | 739/2248 [01:47<06:58,  3.60it/s]
 33%|███▎      | 741/2248 [01:47<05:08,  4.89it/s]
 33%|███▎      | 743/2248 [01:48<06:16,  4.00it/s]
 33%|███▎      | 744/2248 [01:48<06:19,  3.96it/s]
 33%|███▎      | 746/2248 [01:48<04:44,  5.27it/s]
 33%|███▎      | 751/2248 [01:48<03:02,  8.22it/s]
 33%|███▎      | 753/2248 [01:49<03:13,  7.71it/s]
 34%|███▎      | 754/2248 [01:49<03:24,  7.31it/s]
 34%|███▎      | 756/2248 [01:49<02:56,  8.45it/s]
 34%|███▎      | 758/2248 [01:49<03:15,  7.63it/s]
 34%|███▍      | 760/2248 [01:49<02:43,  9.07it/s]
 34%|███▍      | 763/2248 [01:50<02:15, 10.92it/s]
 34%|███▍      | 765/2248 [01:50<02:08, 11.54it/s]
 34%|███▍      | 767/2248 [01:50<02:50,  8.68it/s]
 34%|███▍      | 769/2248 [01:50<02:23, 10.31it/s]
 34%|███▍      | 771/2248 [01:50<02:08, 11.49it/s]
 34%|███▍      | 773/2248 [01:51<03:42,  6.64it/s]
 34%|███▍      | 775/2248 [01:52<05:08,  4.78it/s]
 35%|███▍      | 776/2248 [01:52<06:39,  3.68it/s]
 35%|███▍      | 778/2248 [01:53<07:00,  3.50it/s]
 35%|███▍      | 779/2248 [01:53<06:49,  3.59it/s]
 35%|███▍      | 781/2248 [01:53<04:55,  4.97it/s]
 35%|███▍      | 782/2248 [01:54<06:41,  3.65it/s]
 35%|███▍      | 783/2248 [01:54<08:28,  2.88it/s]
 35%|███▍      | 784/2248 [01:55<09:48,  2.49it/s]
 35%|███▍      | 786/2248 [01:55<06:37,  3.68it/s]
 35%|███▌      | 788/2248 [01:55<05:24,  4.49it/s]
 35%|███▌      | 790/2248 [01:56<04:10,  5.82it/s]
 35%|███▌      | 791/2248 [01:56<05:16,  4.60it/s]
 35%|███▌      | 792/2248 [01:56<05:02,  4.82it/s]
 35%|███▌      | 793/2248 [01:56<04:29,  5.39it/s]
 35%|███▌      | 794/2248 [01:57<06:02,  4.01it/s]
 35%|███▌      | 795/2248 [01:57<05:08,  4.71it/s]
 35%|███▌      | 797/2248 [01:57<06:12,  3.89it/s]
 36%|███▌      | 799/2248 [01:58<05:06,  4.73it/s]
 36%|███▌      | 800/2248 [01:58<05:07,  4.70it/s]
 36%|███▌      | 802/2248 [01:58<03:48,  6.32it/s]
 36%|███▌      | 804/2248 [01:58<02:54,  8.28it/s]
 36%|███▌      | 806/2248 [01:59<03:52,  6.21it/s]
 36%|███▌      | 808/2248 [01:59<03:10,  7.57it/s]
 36%|███▌      | 810/2248 [01:59<02:59,  8.02it/s]
 36%|███▌      | 812/2248 [02:00<06:41,  3.58it/s]
 36%|███▋      | 815/2248 [02:01<05:59,  3.99it/s]
 36%|███▋      | 816/2248 [02:01<07:05,  3.36it/s]
 36%|███▋      | 817/2248 [02:02<06:45,  3.53it/s]
 36%|███▋      | 819/2248 [02:02<04:49,  4.93it/s]
 37%|███▋      | 825/2248 [02:02<02:11, 10.82it/s]
 37%|███▋      | 831/2248 [02:02<01:22, 17.08it/s]
 37%|███▋      | 837/2248 [02:02<00:59, 23.65it/s]
 38%|███▊      | 843/2248 [02:02<00:46, 30.11it/s]
 38%|███▊      | 848/2248 [02:02<00:45, 30.88it/s]
 38%|███▊      | 855/2248 [02:02<00:35, 38.90it/s]
 38%|███▊      | 862/2248 [02:03<00:31, 44.65it/s]
 39%|███▊      | 868/2248 [02:03<01:04, 21.49it/s]
 39%|███▉      | 873/2248 [02:04<01:41, 13.51it/s]
 39%|███▉      | 877/2248 [02:05<02:20,  9.78it/s]
 39%|███▉      | 880/2248 [02:05<02:05, 10.88it/s]
 39%|███▉      | 883/2248 [02:06<02:49,  8.05it/s]
 39%|███▉      | 886/2248 [02:06<03:10,  7.16it/s]
 40%|███▉      | 888/2248 [02:06<02:55,  7.73it/s]
 40%|███▉      | 891/2248 [02:07<03:15,  6.95it/s]
 40%|███▉      | 893/2248 [02:07<03:15,  6.92it/s]
 40%|███▉      | 894/2248 [02:08<03:57,  5.70it/s]
 40%|███▉      | 895/2248 [02:08<04:42,  4.78it/s]
 40%|███▉      | 897/2248 [02:08<03:37,  6.20it/s]
 40%|███▉      | 898/2248 [02:08<03:49,  5.89it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 298.50it/s]

[[np.int64(0), False, 7], [np.int64(1), False, 13], [np.int64(2), False, 9], [np.int64(3), False, 7], [np.int64(4), False, 0], [np.int64(5), False, 13], [np.int64(6), False, 7], [np.int64(8), False, 1], [np.int64(10), False, 6], [np.int64(11), False, 2], [np.int64(12), False, 6]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.1395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4481, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [05:11<2:57:17, 53.46s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [05:11<2:20:53, 42.69s/it]

tensor(13.1226, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5234, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1099, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6242, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [05:11<1:00:49, 18.72s/it]

tensor(13.1047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8016, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1053, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9282, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [05:12<31:59,  9.95s/it]

tensor(13.1081, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0428, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1896, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [05:12<16:19,  5.13s/it]

tensor(13.1135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3346, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1196, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4076, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [05:12<08:15,  2.62s/it]

tensor(13.1265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4255, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1305, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4487, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [05:12<04:13,  1.36s/it]

tensor(13.1300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4738, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4969, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [05:12<02:14,  1.38it/s]

tensor(13.1111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5240, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5253, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [05:13<01:16,  2.40it/s]

tensor(13.0553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5360, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5278, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [05:13<00:47,  3.80it/s]

tensor(12.9853, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5338, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5435, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [05:13<00:33,  5.32it/s]

tensor(12.9378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5555, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5570, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [05:13<00:26,  6.63it/s]

tensor(12.9122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5818, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9031, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6097, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [05:14<00:23,  7.49it/s]

tensor(12.8945, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6365, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6672, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [05:14<00:21,  8.04it/s]

tensor(12.8755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6952, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8652, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7188, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [05:14<00:20,  8.28it/s]

tensor(12.8553, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7434, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7540, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [05:14<00:19,  8.48it/s]

tensor(12.8378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7278, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6871, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [05:15<00:19,  8.57it/s]

tensor(12.8221, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7223, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6517, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [05:15<00:19,  8.57it/s]

tensor(12.8130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6252, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6259, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [05:15<00:18,  8.61it/s]

tensor(12.8156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6329, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8106, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6833, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [05:15<00:18,  8.59it/s]

tensor(12.8005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7360, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0278, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7704, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [05:15<00:18,  8.63it/s]

tensor(12.7815, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8018, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8224, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [05:16<00:18,  8.60it/s]

tensor(12.7734, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8451, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8646, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [05:16<00:18,  8.61it/s]

tensor(12.7620, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8879, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7539, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9100, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [05:16<00:17,  8.51it/s]

tensor(12.7439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9268, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9387, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [05:16<00:17,  8.47it/s]

tensor(12.7239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9578, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7159, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9718, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [05:17<00:17,  8.48it/s]

tensor(12.7100, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0299, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9985, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([189, 254, 130, 176,  51, 172, 340, 225, 109, 150,  57, 115, 214,  66])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<01:54, 19.57it/s]
  0%|          | 7/2248 [00:00<01:01, 36.48it/s]
  0%|          | 11/2248 [00:00<01:02, 35.68it/s]
  1%|          | 15/2248 [00:00<01:17, 28.85it/s]
  1%|          | 20/2248 [00:00<01:03, 35.02it/s]
  1%|          | 26/2248 [00:00<00:55, 40.29it/s]
  1%|▏         | 32/2248 [00:00<00:48, 45.80it/s]
  2%|▏         | 38/2248 [00:00<00:45, 48.62it/s]
  2%|▏         | 44/2248 [00:01<00:42, 51.74it/s]
  2%|▏         | 50/2248 [00:01<00:40, 53.89it/s]
  2%|▏         | 56/2248 [00:01<00:41, 53.17it/s]
  3%|▎         | 63/2248 [00:01<00:38, 57.12it/s]
  3%|▎         | 69/2248 [00:01<00:37, 57.78it/s]
  3%|▎         | 75/2248 [00:01<01:06, 32.62it/s]
  4%|▎         | 80/2248 [00:02<01:19, 27.20it/s]
  4%|▍         | 86/2248 [00:02<01:41, 21.21it/s]
  4%|▍         | 90/2248 [00:02<01:45, 20.42it/s]
  4%|▍         | 93/2248 [00:02<01:43, 20.76it/s]
  4%|▍         | 96/2248 [00:03<02:23, 15.00it/s]
  4%|▍         | 99/2248 [00:03<03:09, 11.37it/s]
  4%|▍         | 101/2248 [00:04<03:48,  9.40it/s]
  5%|▍         | 103/2248 [00:04<03:35,  9.95it/s]
  5%|▍         | 105/2248 [00:04<04:27,  8.01it/s]
  5%|▍         | 108/2248 [00:04<03:26, 10.37it/s]
  5%|▍         | 112/2248 [00:05<03:26, 10.35it/s]
  5%|▌         | 114/2248 [00:05<03:09, 11.29it/s]
  5%|▌         | 116/2248 [00:05<02:52, 12.35it/s]
  5%|▌         | 118/2248 [00:05<03:37,  9.82it/s]
  5%|▌         | 120/2248 [00:06<03:59,  8.89it/s]
  5%|▌         | 122/2248 [00:06<03:53,  9.11it/s]
  6%|▌         | 124/2248 [00:06<03:18, 10.69it/s]
  6%|▌         | 126/2248 [00:06<03:29, 10.11it/s]
  6%|▌         | 128/2248 [00:06<04:06,  8.59it/s]
  6%|▌         | 130/2248 [00:06<03:27, 10.19it/s]
  6%|▌         | 133/2248 [00:07<03:04, 11.43it/s]
  6%|▌         | 135/2248 [00:07<02:59, 11.80it/s]
  6%|▌         | 137/2248 [00:07<04:01,  8.73it/s]
  6%|▌         | 139/2248 [00:07<03:54,  9.01it/s]
  6%|▋         | 141/2248 [00:08<04:16,  8.22it/s]
  6%|▋         | 145/2248 [00:08<03:08, 11.18it/s]
  7%|▋         | 149/2248 [00:08<02:21, 14.87it/s]
  7%|▋         | 152/2248 [00:08<02:14, 15.54it/s]
  7%|▋         | 155/2248 [00:08<02:00, 17.43it/s]
  7%|▋         | 157/2248 [00:09<02:18, 15.07it/s]
  7%|▋         | 159/2248 [00:09<03:24, 10.21it/s]
  7%|▋         | 161/2248 [00:09<03:22, 10.32it/s]
  7%|▋         | 164/2248 [00:09<02:36, 13.28it/s]
  7%|▋         | 168/2248 [00:09<02:01, 17.06it/s]
  8%|▊         | 171/2248 [00:10<02:51, 12.10it/s]
  8%|▊         | 173/2248 [00:10<03:31,  9.80it/s]
  8%|▊         | 175/2248 [00:10<03:08, 10.97it/s]
  8%|▊         | 177/2248 [00:11<03:46,  9.16it/s]
  8%|▊         | 179/2248 [00:11<04:13,  8.15it/s]
  8%|▊         | 182/2248 [00:11<03:08, 10.95it/s]
  8%|▊         | 186/2248 [00:11<02:18, 14.85it/s]
  8%|▊         | 190/2248 [00:11<02:29, 13.78it/s]
  9%|▊         | 192/2248 [00:12<02:29, 13.72it/s]
  9%|▊         | 195/2248 [00:12<02:15, 15.20it/s]
  9%|▉         | 197/2248 [00:12<02:18, 14.76it/s]
  9%|▉         | 200/2248 [00:12<01:58, 17.33it/s]
  9%|▉         | 202/2248 [00:12<02:53, 11.79it/s]
  9%|▉         | 205/2248 [00:13<02:53, 11.76it/s]
  9%|▉         | 207/2248 [00:13<03:40,  9.26it/s]
  9%|▉         | 209/2248 [00:13<04:04,  8.34it/s]
  9%|▉         | 211/2248 [00:14<05:41,  5.96it/s]
  9%|▉         | 212/2248 [00:14<05:35,  6.07it/s]
 10%|▉         | 215/2248 [00:14<03:50,  8.81it/s]
 10%|▉         | 220/2248 [00:14<02:27, 13.73it/s]
 10%|▉         | 222/2248 [00:14<02:20, 14.47it/s]
 10%|▉         | 224/2248 [00:15<02:14, 15.02it/s]
 10%|█         | 227/2248 [00:15<02:01, 16.68it/s]
 10%|█         | 231/2248 [00:15<01:35, 21.21it/s]
 11%|█         | 237/2248 [00:15<01:13, 27.52it/s]
 11%|█         | 241/2248 [00:15<01:09, 29.06it/s]
 11%|█         | 247/2248 [00:15<00:56, 35.49it/s]
 11%|█▏        | 254/2248 [00:15<00:47, 42.00it/s]
 12%|█▏        | 261/2248 [00:15<00:45, 44.11it/s]
 12%|█▏        | 266/2248 [00:16<01:45, 18.73it/s]
 12%|█▏        | 270/2248 [00:17<02:10, 15.21it/s]
 12%|█▏        | 273/2248 [00:17<02:39, 12.35it/s]
 12%|█▏        | 276/2248 [00:17<02:46, 11.82it/s]
 12%|█▏        | 278/2248 [00:18<03:19,  9.88it/s]
 12%|█▎        | 281/2248 [00:18<02:47, 11.75it/s]
 13%|█▎        | 283/2248 [00:18<03:23,  9.64it/s]
 13%|█▎        | 285/2248 [00:18<03:05, 10.57it/s]
 13%|█▎        | 287/2248 [00:18<03:14, 10.07it/s]
 13%|█▎        | 289/2248 [00:19<03:07, 10.48it/s]
 13%|█▎        | 291/2248 [00:19<03:54,  8.35it/s]
 13%|█▎        | 293/2248 [00:19<03:22,  9.65it/s]
 13%|█▎        | 295/2248 [00:19<02:53, 11.25it/s]
 13%|█▎        | 297/2248 [00:19<02:35, 12.59it/s]
 13%|█▎        | 299/2248 [00:20<02:46, 11.70it/s]
 13%|█▎        | 301/2248 [00:20<02:35, 12.54it/s]
 13%|█▎        | 303/2248 [00:20<03:44,  8.66it/s]
 14%|█▎        | 305/2248 [00:20<04:29,  7.21it/s]
 14%|█▎        | 306/2248 [00:21<05:11,  6.22it/s]
 14%|█▎        | 307/2248 [00:21<06:23,  5.07it/s]
 14%|█▎        | 308/2248 [00:21<06:24,  5.05it/s]
 14%|█▎        | 309/2248 [00:21<05:55,  5.45it/s]
 14%|█▍        | 311/2248 [00:22<04:15,  7.59it/s]
 14%|█▍        | 313/2248 [00:22<03:38,  8.85it/s]
 14%|█▍        | 315/2248 [00:22<04:41,  6.87it/s]
 14%|█▍        | 318/2248 [00:22<03:38,  8.83it/s]
 14%|█▍        | 320/2248 [00:22<03:11, 10.06it/s]
 14%|█▍        | 322/2248 [00:23<02:57, 10.85it/s]
 14%|█▍        | 324/2248 [00:23<03:04, 10.46it/s]
 15%|█▍        | 326/2248 [00:23<03:06, 10.32it/s]
 15%|█▍        | 328/2248 [00:23<02:46, 11.50it/s]
 15%|█▍        | 332/2248 [00:23<02:52, 11.14it/s]
 15%|█▍        | 334/2248 [00:24<02:45, 11.57it/s]
 15%|█▍        | 336/2248 [00:24<02:29, 12.82it/s]
 15%|█▌        | 340/2248 [00:24<01:49, 17.48it/s]
 15%|█▌        | 343/2248 [00:24<02:50, 11.17it/s]
 15%|█▌        | 345/2248 [00:25<03:30,  9.04it/s]
 15%|█▌        | 347/2248 [00:25<04:28,  7.09it/s]
 16%|█▌        | 349/2248 [00:26<04:49,  6.55it/s]
 16%|█▌        | 350/2248 [00:26<04:38,  6.82it/s]
 16%|█▌        | 352/2248 [00:26<03:46,  8.37it/s]
 16%|█▌        | 354/2248 [00:26<04:26,  7.12it/s]
 16%|█▌        | 356/2248 [00:26<04:20,  7.26it/s]
 16%|█▌        | 358/2248 [00:27<03:43,  8.47it/s]
 16%|█▌        | 362/2248 [00:27<02:23, 13.17it/s]
 16%|█▌        | 364/2248 [00:27<02:51, 10.97it/s]
 16%|█▋        | 366/2248 [00:27<02:54, 10.78it/s]
 16%|█▋        | 368/2248 [00:27<02:35, 12.10it/s]
 17%|█▋        | 371/2248 [00:28<02:47, 11.21it/s]
 17%|█▋        | 373/2248 [00:28<02:28, 12.60it/s]
 17%|█▋        | 377/2248 [00:28<02:24, 12.99it/s]
 17%|█▋        | 379/2248 [00:28<02:37, 11.86it/s]
 17%|█▋        | 382/2248 [00:28<02:08, 14.50it/s]
 17%|█▋        | 384/2248 [00:28<02:00, 15.43it/s]
 17%|█▋        | 386/2248 [00:29<02:26, 12.67it/s]
 17%|█▋        | 388/2248 [00:29<02:47, 11.12it/s]
 17%|█▋        | 390/2248 [00:29<03:54,  7.92it/s]
 17%|█▋        | 392/2248 [00:30<04:13,  7.32it/s]
 17%|█▋        | 393/2248 [00:30<04:55,  6.28it/s]
 18%|█▊        | 394/2248 [00:30<06:12,  4.97it/s]
 18%|█▊        | 395/2248 [00:30<05:42,  5.42it/s]
 18%|█▊        | 397/2248 [00:31<04:29,  6.87it/s]
 18%|█▊        | 399/2248 [00:31<03:32,  8.68it/s]
 18%|█▊        | 404/2248 [00:31<01:55, 15.99it/s]
 18%|█▊        | 408/2248 [00:31<01:30, 20.22it/s]
 18%|█▊        | 414/2248 [00:31<01:05, 27.91it/s]
 19%|█▊        | 418/2248 [00:31<01:03, 28.85it/s]
 19%|█▉        | 423/2248 [00:31<00:54, 33.58it/s]
 19%|█▉        | 429/2248 [00:31<00:46, 39.47it/s]
 19%|█▉        | 435/2248 [00:31<00:40, 44.43it/s]
 20%|█▉        | 440/2248 [00:32<02:13, 13.52it/s]
 20%|█▉        | 444/2248 [00:33<02:30, 11.99it/s]
 20%|█▉        | 447/2248 [00:33<02:17, 13.11it/s]
 20%|██        | 450/2248 [00:33<02:20, 12.79it/s]
 20%|██        | 453/2248 [00:33<02:10, 13.74it/s]
 20%|██        | 455/2248 [00:34<02:05, 14.29it/s]
 20%|██        | 457/2248 [00:34<02:07, 14.01it/s]
 20%|██        | 460/2248 [00:34<01:53, 15.70it/s]
 21%|██        | 463/2248 [00:34<01:53, 15.71it/s]
 21%|██        | 465/2248 [00:34<01:58, 15.07it/s]
 21%|██        | 470/2248 [00:34<01:23, 21.20it/s]
 21%|██        | 473/2248 [00:35<02:25, 12.24it/s]
 21%|██        | 475/2248 [00:35<02:27, 12.06it/s]
 21%|██        | 477/2248 [00:35<03:16,  9.03it/s]
 21%|██▏       | 479/2248 [00:36<03:38,  8.10it/s]
 21%|██▏       | 481/2248 [00:36<04:55,  5.98it/s]
 21%|██▏       | 482/2248 [00:37<05:00,  5.88it/s]
 22%|██▏       | 484/2248 [00:37<03:57,  7.43it/s]
 22%|██▏       | 486/2248 [00:37<03:20,  8.78it/s]
 22%|██▏       | 489/2248 [00:37<02:24, 12.14it/s]
 22%|██▏       | 492/2248 [00:37<02:06, 13.83it/s]
 22%|██▏       | 495/2248 [00:37<02:16, 12.88it/s]
 22%|██▏       | 497/2248 [00:37<02:06, 13.81it/s]
 22%|██▏       | 499/2248 [00:38<02:53, 10.10it/s]
 22%|██▏       | 501/2248 [00:38<03:02,  9.57it/s]
 22%|██▏       | 503/2248 [00:38<02:52, 10.13it/s]
 23%|██▎       | 506/2248 [00:38<02:20, 12.36it/s]
 23%|██▎       | 509/2248 [00:38<01:55, 15.08it/s]
 23%|██▎       | 512/2248 [00:39<02:10, 13.28it/s]
 23%|██▎       | 514/2248 [00:39<02:12, 13.10it/s]
 23%|██▎       | 516/2248 [00:39<02:41, 10.72it/s]
 23%|██▎       | 518/2248 [00:40<03:41,  7.81it/s]
 23%|██▎       | 520/2248 [00:40<03:20,  8.60it/s]
 23%|██▎       | 524/2248 [00:40<02:14, 12.87it/s]
 23%|██▎       | 527/2248 [00:40<01:56, 14.78it/s]
 24%|██▎       | 533/2248 [00:40<01:15, 22.82it/s]
 24%|██▍       | 540/2248 [00:40<00:52, 32.29it/s]
 24%|██▍       | 545/2248 [00:40<00:56, 30.10it/s]
 25%|██▍       | 552/2248 [00:41<00:45, 37.63it/s]
 25%|██▍       | 557/2248 [00:41<00:48, 34.63it/s]
 25%|██▌       | 562/2248 [00:41<00:48, 34.80it/s]
 25%|██▌       | 566/2248 [00:41<00:58, 28.90it/s]
 25%|██▌       | 572/2248 [00:41<00:50, 33.26it/s]
 26%|██▌       | 576/2248 [00:42<01:20, 20.83it/s]
 26%|██▌       | 579/2248 [00:42<01:45, 15.75it/s]
 26%|██▌       | 582/2248 [00:42<02:19, 11.94it/s]
 26%|██▌       | 584/2248 [00:43<02:49,  9.82it/s]
 26%|██▌       | 586/2248 [00:43<02:32, 10.87it/s]
 26%|██▌       | 588/2248 [00:43<02:58,  9.28it/s]
 26%|██▌       | 590/2248 [00:43<02:37, 10.50it/s]
 26%|██▋       | 592/2248 [00:44<02:58,  9.26it/s]
 26%|██▋       | 594/2248 [00:44<02:35, 10.60it/s]
 27%|██▋       | 597/2248 [00:44<02:05, 13.11it/s]
 27%|██▋       | 599/2248 [00:44<02:05, 13.16it/s]
 27%|██▋       | 603/2248 [00:44<02:00, 13.65it/s]
 27%|██▋       | 605/2248 [00:45<02:39, 10.29it/s]
 27%|██▋       | 607/2248 [00:45<03:25,  7.99it/s]
 27%|██▋       | 608/2248 [00:45<03:48,  7.16it/s]
 27%|██▋       | 609/2248 [00:46<04:22,  6.24it/s]
 27%|██▋       | 611/2248 [00:46<03:41,  7.38it/s]
 27%|██▋       | 614/2248 [00:46<02:38, 10.34it/s]
 28%|██▊       | 619/2248 [00:46<01:35, 16.98it/s]
 28%|██▊       | 622/2248 [00:46<01:32, 17.54it/s]
 28%|██▊       | 627/2248 [00:46<01:08, 23.52it/s]
 28%|██▊       | 630/2248 [00:46<01:07, 24.09it/s]
 28%|██▊       | 635/2248 [00:46<00:55, 29.21it/s]
 28%|██▊       | 640/2248 [00:47<00:51, 31.52it/s]
 29%|██▊       | 645/2248 [00:47<00:45, 35.57it/s]
 29%|██▉       | 650/2248 [00:47<00:56, 28.06it/s]
 29%|██▉       | 654/2248 [00:48<02:10, 12.22it/s]
 29%|██▉       | 657/2248 [00:48<01:56, 13.71it/s]
 29%|██▉       | 660/2248 [00:48<01:58, 13.41it/s]
 29%|██▉       | 663/2248 [00:49<02:27, 10.77it/s]
 30%|██▉       | 665/2248 [00:49<02:31, 10.42it/s]
 30%|██▉       | 667/2248 [00:49<02:30, 10.48it/s]
 30%|██▉       | 669/2248 [00:49<02:19, 11.35it/s]
 30%|██▉       | 671/2248 [00:49<02:19, 11.30it/s]
 30%|███       | 675/2248 [00:49<01:38, 15.92it/s]
 30%|███       | 678/2248 [00:50<01:35, 16.36it/s]
 30%|███       | 681/2248 [00:50<01:36, 16.16it/s]
 30%|███       | 683/2248 [00:50<02:06, 12.36it/s]
 30%|███       | 685/2248 [00:51<03:21,  7.74it/s]
 31%|███       | 687/2248 [00:51<04:20,  5.99it/s]
 31%|███       | 688/2248 [00:51<04:12,  6.17it/s]
 31%|███       | 691/2248 [00:51<02:56,  8.81it/s]
 31%|███       | 693/2248 [00:52<02:34, 10.09it/s]
 31%|███       | 695/2248 [00:52<03:04,  8.43it/s]
 31%|███       | 697/2248 [00:52<02:34, 10.03it/s]
 31%|███       | 699/2248 [00:52<02:49,  9.14it/s]
 31%|███       | 702/2248 [00:53<02:46,  9.31it/s]
 31%|███▏      | 704/2248 [00:53<03:13,  7.98it/s]
 31%|███▏      | 706/2248 [00:53<02:44,  9.39it/s]
 32%|███▏      | 711/2248 [00:53<01:39, 15.49it/s]
 32%|███▏      | 716/2248 [00:54<01:47, 14.26it/s]
 32%|███▏      | 719/2248 [00:54<02:14, 11.36it/s]
 32%|███▏      | 721/2248 [00:54<02:58,  8.57it/s]
 32%|███▏      | 724/2248 [00:55<02:25, 10.47it/s]
 32%|███▏      | 727/2248 [00:55<02:03, 12.29it/s]
 32%|███▏      | 729/2248 [00:55<01:53, 13.44it/s]
 33%|███▎      | 731/2248 [00:55<02:14, 11.31it/s]
 33%|███▎      | 733/2248 [00:56<03:27,  7.29it/s]
 33%|███▎      | 735/2248 [00:56<03:44,  6.75it/s]
 33%|███▎      | 736/2248 [00:56<04:10,  6.03it/s]
 33%|███▎      | 737/2248 [00:56<04:25,  5.68it/s]
 33%|███▎      | 738/2248 [00:57<04:37,  5.45it/s]
 33%|███▎      | 741/2248 [00:57<02:53,  8.70it/s]
 33%|███▎      | 743/2248 [00:57<03:29,  7.19it/s]
 33%|███▎      | 744/2248 [00:57<03:41,  6.80it/s]
 33%|███▎      | 747/2248 [00:57<02:34,  9.72it/s]
 33%|███▎      | 749/2248 [00:58<02:29, 10.01it/s]
 33%|███▎      | 751/2248 [00:58<02:25, 10.29it/s]
 33%|███▎      | 753/2248 [00:58<02:39,  9.39it/s]
 34%|███▎      | 755/2248 [00:58<02:17, 10.85it/s]
 34%|███▎      | 757/2248 [00:58<02:04, 11.96it/s]
 34%|███▍      | 759/2248 [00:58<01:51, 13.31it/s]
 34%|███▍      | 761/2248 [00:59<02:18, 10.72it/s]
 34%|███▍      | 763/2248 [00:59<02:04, 11.89it/s]
 34%|███▍      | 766/2248 [00:59<01:38, 15.08it/s]
 34%|███▍      | 768/2248 [00:59<01:42, 14.42it/s]
 34%|███▍      | 770/2248 [00:59<01:45, 13.96it/s]
 34%|███▍      | 772/2248 [01:00<02:20, 10.52it/s]
 34%|███▍      | 774/2248 [01:00<02:50,  8.66it/s]
 35%|███▍      | 776/2248 [01:00<02:59,  8.20it/s]
 35%|███▍      | 779/2248 [01:00<02:13, 10.97it/s]
 35%|███▍      | 782/2248 [01:01<02:02, 11.93it/s]
 35%|███▍      | 784/2248 [01:01<02:22, 10.30it/s]
 35%|███▌      | 787/2248 [01:01<01:54, 12.75it/s]
 35%|███▌      | 789/2248 [01:01<02:01, 11.99it/s]
 35%|███▌      | 791/2248 [01:01<01:57, 12.41it/s]
 35%|███▌      | 793/2248 [01:02<02:22, 10.21it/s]
 35%|███▌      | 795/2248 [01:02<02:03, 11.78it/s]
 36%|███▌      | 800/2248 [01:02<01:27, 16.55it/s]
 36%|███▌      | 802/2248 [01:02<01:26, 16.66it/s]
 36%|███▌      | 807/2248 [01:02<01:06, 21.80it/s]
 36%|███▌      | 810/2248 [01:02<01:19, 18.20it/s]
 36%|███▌      | 813/2248 [01:03<01:33, 15.27it/s]
 36%|███▋      | 815/2248 [01:03<01:58, 12.09it/s]
 36%|███▋      | 817/2248 [01:03<02:02, 11.68it/s]
 36%|███▋      | 819/2248 [01:03<01:50, 12.96it/s]
 37%|███▋      | 825/2248 [01:03<01:06, 21.27it/s]
 37%|███▋      | 831/2248 [01:03<00:48, 29.24it/s]
 37%|███▋      | 835/2248 [01:04<00:46, 30.26it/s]
 37%|███▋      | 839/2248 [01:04<00:43, 32.41it/s]
 38%|███▊      | 845/2248 [01:04<00:35, 39.37it/s]
 38%|███▊      | 850/2248 [01:04<00:36, 38.79it/s]
 38%|███▊      | 856/2248 [01:04<00:32, 43.25it/s]
 38%|███▊      | 862/2248 [01:04<00:29, 46.49it/s]
 39%|███▊      | 867/2248 [01:04<00:33, 40.90it/s]
 39%|███▉      | 872/2248 [01:05<00:56, 24.43it/s]
 39%|███▉      | 876/2248 [01:05<01:06, 20.72it/s]
 39%|███▉      | 879/2248 [01:05<01:17, 17.75it/s]
 39%|███▉      | 882/2248 [01:05<01:19, 17.20it/s]
 39%|███▉      | 885/2248 [01:06<01:16, 17.75it/s]
 40%|███▉      | 888/2248 [01:06<01:46, 12.76it/s]
 40%|███▉      | 893/2248 [01:06<01:16, 17.79it/s]
 40%|███▉      | 896/2248 [01:06<01:31, 14.71it/s]
 40%|███▉      | 899/2248 [01:07<01:33, 14.42it/s]
 40%|████      | 902/2248 [01:07<01:46, 12.68it/s]
 40%|████      | 904/2248 [01:07<01:39, 13.55it/s]
 40%|████      | 906/2248 [01:07<01:44, 12.90it/s]
 40%|████      | 908/2248 [01:08<02:22,  9.38it/s]
 40%|████      | 910/2248 [01:08<03:30,  6.35it/s]
 41%|████      | 911/2248 [01:09<04:00,  5.57it/s]
 41%|████      | 912/2248 [01:09<04:31,  4.92it/s]
 41%|████      | 913/2248 [01:09<04:20,  5.12it/s]
 41%|████      | 916/2248 [01:09<02:45,  8.04it/s]
 41%|████      | 919/2248 [01:09<02:30,  8.80it/s]
 41%|████      | 921/2248 [01:10<03:01,  7.32it/s]
 41%|████      | 924/2248 [01:10<02:42,  8.16it/s]
 41%|████      | 926/2248 [01:10<02:24,  9.18it/s]
 41%|████▏     | 928/2248 [01:10<02:26,  9.02it/s]
 41%|████▏     | 930/2248 [01:11<02:31,  8.69it/s]
 41%|████▏     | 932/2248 [01:11<02:09, 10.16it/s]
 42%|████▏     | 935/2248 [01:11<01:38, 13.34it/s]
 42%|████▏     | 941/2248 [01:11<00:59, 21.94it/s]
 42%|████▏     | 944/2248 [01:11<01:24, 15.48it/s]
 42%|████▏     | 947/2248 [01:12<02:18,  9.36it/s]
 42%|████▏     | 949/2248 [01:12<02:11,  9.86it/s]
 42%|████▏     | 952/2248 [01:13<02:19,  9.28it/s]
 42%|████▏     | 954/2248 [01:13<02:42,  7.97it/s]
 43%|████▎     | 956/2248 [01:13<02:55,  7.36it/s]
 43%|████▎     | 957/2248 [01:14<03:28,  6.19it/s]
 43%|████▎     | 958/2248 [01:14<03:58,  5.40it/s]
 43%|████▎     | 960/2248 [01:14<04:07,  5.21it/s]
 43%|████▎     | 961/2248 [01:14<04:02,  5.31it/s]
 43%|████▎     | 962/2248 [01:15<04:34,  4.68it/s]
 43%|████▎     | 963/2248 [01:15<04:28,  4.79it/s]
 43%|████▎     | 966/2248 [01:15<03:34,  5.96it/s]
 43%|████▎     | 967/2248 [01:16<04:07,  5.17it/s]
 43%|████▎     | 969/2248 [01:16<04:17,  4.97it/s]
 43%|████▎     | 970/2248 [01:16<04:50,  4.40it/s]
 43%|████▎     | 972/2248 [01:17<03:30,  6.07it/s]
 43%|████▎     | 976/2248 [01:17<01:59, 10.68it/s]
 44%|████▎     | 978/2248 [01:17<01:48, 11.72it/s]
 44%|████▎     | 981/2248 [01:17<02:09,  9.80it/s]
 44%|████▍     | 984/2248 [01:17<01:43, 12.23it/s]
 44%|████▍     | 986/2248 [01:18<02:09,  9.71it/s]
 44%|████▍     | 988/2248 [01:18<02:40,  7.83it/s]
 44%|████▍     | 991/2248 [01:18<02:35,  8.08it/s]
 44%|████▍     | 993/2248 [01:19<02:25,  8.60it/s]
 44%|████▍     | 995/2248 [01:19<02:10,  9.59it/s]
 44%|████▍     | 998/2248 [01:19<02:25,  8.59it/s]
 44%|████▍     | 1000/2248 [01:20<02:55,  7.13it/s]
 45%|████▍     | 1002/2248 [01:20<02:55,  7.10it/s]
 45%|████▍     | 1004/2248 [01:20<02:41,  7.71it/s]
 45%|████▍     | 1005/2248 [01:20<02:46,  7.45it/s]
 45%|████▍     | 1006/2248 [01:20<03:03,  6.78it/s]
 45%|████▍     | 1007/2248 [01:21<03:25,  6.04it/s]
 45%|████▍     | 1008/2248 [01:21<03:33,  5.80it/s]
 45%|████▍     | 1010/2248 [01:21<02:48,  7.35it/s]
 45%|████▌     | 1012/2248 [01:21<02:20,  8.82it/s]
 45%|████▌     | 1018/2248 [01:21<01:12, 17.06it/s]
 46%|████▌     | 1024/2248 [01:21<00:51, 23.70it/s]
 46%|████▌     | 1028/2248 [01:22<00:45, 26.99it/s]
 46%|████▌     | 1033/2248 [01:22<00:39, 30.62it/s]
 46%|████▌     | 1037/2248 [01:22<00:37, 32.52it/s]
 46%|████▋     | 1041/2248 [01:22<00:36, 32.68it/s]
 46%|████▋     | 1045/2248 [01:22<00:38, 31.47it/s]
 47%|████▋     | 1049/2248 [01:22<00:37, 31.88it/s]
 47%|████▋     | 1054/2248 [01:22<00:33, 35.47it/s]
 47%|████▋     | 1058/2248 [01:23<01:01, 19.47it/s]
 47%|████▋     | 1061/2248 [01:23<01:01, 19.41it/s]
 47%|████▋     | 1064/2248 [01:23<00:58, 20.39it/s]
 47%|████▋     | 1067/2248 [01:23<01:27, 13.45it/s]
 48%|████▊     | 1069/2248 [01:24<01:53, 10.41it/s]
 48%|████▊     | 1072/2248 [01:24<01:32, 12.68it/s]
 48%|████▊     | 1075/2248 [01:24<01:16, 15.33it/s]
 48%|████▊     | 1078/2248 [01:24<01:25, 13.62it/s]
 48%|████▊     | 1082/2248 [01:24<01:05, 17.84it/s]
 48%|████▊     | 1085/2248 [01:25<01:11, 16.34it/s]
 48%|████▊     | 1088/2248 [01:25<01:28, 13.08it/s]
 48%|████▊     | 1090/2248 [01:25<01:44, 11.07it/s]
 49%|████▊     | 1092/2248 [01:25<01:45, 10.97it/s]
 49%|████▊     | 1094/2248 [01:26<01:51, 10.33it/s]
 49%|████▉     | 1096/2248 [01:26<01:44, 11.06it/s]
 49%|████▉     | 1099/2248 [01:26<01:23, 13.82it/s]
 49%|████▉     | 1105/2248 [01:26<00:50, 22.59it/s]
 49%|████▉     | 1112/2248 [01:26<00:35, 31.91it/s]
 50%|████▉     | 1118/2248 [01:26<00:29, 38.28it/s]
 50%|█████     | 1126/2248 [01:26<00:25, 43.23it/s]
 50%|█████     | 1133/2248 [01:26<00:22, 49.44it/s]
 51%|█████     | 1139/2248 [01:27<00:24, 44.96it/s]
 51%|█████     | 1144/2248 [01:27<00:29, 37.75it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 313.28it/s]

[[np.int64(0), False, 9], [np.int64(1), False, 6], [np.int64(2), False, 13], [np.int64(3), False, 6], [np.int64(4), False, 8], [np.int64(5), False, 1], [np.int64(7), False, 12], [np.int64(8), False, 0], [np.int64(9), False, 7], [np.int64(10), False, 11], [np.int64(11), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.7052, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.1105, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [08:11<2:10:04, 52.38s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [08:11<1:30:32, 36.71s/it]

tensor(12.7088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0405, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0333, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5367, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [08:11<30:36, 12.67s/it]

tensor(12.7589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0361, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7911, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7755, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6706, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [08:12<14:56,  6.27s/it]

tensor(12.7844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0384, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7205, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7876, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0381, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7379, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [08:12<07:21,  3.13s/it]

tensor(12.7891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0389, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7620, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0402, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9397, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [08:12<03:41,  1.59s/it]

tensor(12.7955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0410, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9988, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0316, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [08:12<01:54,  1.19it/s]

tensor(12.7714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0406, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0411, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7565, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0404, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0561, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [08:13<01:03,  2.13it/s]

tensor(12.7514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0399, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0789, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7496, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0394, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1163, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [08:13<00:38,  3.45it/s]

tensor(12.7471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0388, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1624, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0378, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1979, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [08:13<00:26,  4.98it/s]

tensor(12.7526, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0369, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2328, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0358, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2560, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [08:13<00:20,  6.33it/s]

tensor(12.7297, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2709, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2810, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [08:13<00:17,  7.36it/s]

tensor(12.6782, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2895, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2942, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [08:14<00:15,  7.90it/s]

tensor(12.6551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3079, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6504, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3156, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [08:14<00:14,  8.29it/s]

tensor(12.6481, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3230, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3347, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [08:14<00:14,  8.36it/s]

tensor(12.6340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3461, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6220, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3541, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [08:14<00:13,  8.52it/s]

tensor(12.6115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3624, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3731, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [08:15<00:13,  8.53it/s]

tensor(12.5938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3828, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5890, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3905, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [08:15<00:13,  8.53it/s]

tensor(12.5842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4018, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [08:15<00:13,  8.45it/s]

tensor(12.5731, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4111, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4190, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [08:15<00:13,  8.43it/s]

tensor(12.5607, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4208, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5561, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4261, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [08:16<00:12,  8.50it/s]

tensor(12.5519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4303, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4382, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [08:16<00:12,  8.53it/s]

tensor(12.5448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4414, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4439, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [08:16<00:12,  8.54it/s]

tensor(12.5358, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4479, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4520, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [08:16<00:12,  8.54it/s]

tensor(12.5270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4539, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4565, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [08:16<00:11,  8.54it/s]

tensor(12.5198, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4565, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4582, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:17<00:11,  8.61it/s]

tensor(12.5126, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4596, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([192, 402,  67, 248, 119, 115, 244, 123,  79, 143, 157,  97, 129, 133])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 5/2248 [00:00<00:48, 45.95it/s]
  0%|          | 10/2248 [00:00<00:57, 38.95it/s]
  1%|          | 15/2248 [00:00<00:58, 38.24it/s]
  1%|          | 21/2248 [00:00<00:50, 44.25it/s]
  1%|          | 28/2248 [00:00<00:44, 50.30it/s]
  2%|▏         | 34/2248 [00:00<00:48, 46.06it/s]
  2%|▏         | 39/2248 [00:01<01:25, 25.91it/s]
  2%|▏         | 43/2248 [00:01<01:18, 27.94it/s]
  2%|▏         | 47/2248 [00:01<01:17, 28.28it/s]
  2%|▏         | 54/2248 [00:01<01:00, 36.02it/s]
  3%|▎         | 59/2248 [00:01<01:07, 32.41it/s]
  3%|▎         | 63/2248 [00:01<01:14, 29.48it/s]
  3%|▎         | 68/2248 [00:02<01:08, 32.02it/s]
  3%|▎         | 74/2248 [00:02<00:59, 36.81it/s]
  4%|▎         | 79/2248 [00:02<02:10, 16.62it/s]
  4%|▎         | 83/2248 [00:03<02:14, 16.15it/s]
  4%|▍         | 86/2248 [00:03<02:36, 13.80it/s]
  4%|▍         | 89/2248 [00:03<02:43, 13.19it/s]
  4%|▍         | 91/2248 [00:04<03:41,  9.73it/s]
  4%|▍         | 93/2248 [00:04<03:22, 10.67it/s]
  4%|▍         | 95/2248 [00:04<04:33,  7.88it/s]
  4%|▍         | 97/2248 [00:05<05:31,  6.48it/s]
  4%|▍         | 98/2248 [00:05<05:32,  6.47it/s]
  4%|▍         | 101/2248 [00:05<04:15,  8.40it/s]
  5%|▍         | 104/2248 [00:05<03:19, 10.75it/s]
  5%|▍         | 106/2248 [00:05<02:58, 12.01it/s]
  5%|▍         | 108/2248 [00:05<02:44, 13.04it/s]
  5%|▍         | 111/2248 [00:06<03:24, 10.45it/s]
  5%|▌         | 113/2248 [00:06<05:07,  6.95it/s]
  5%|▌         | 115/2248 [00:07<05:20,  6.65it/s]
  5%|▌         | 117/2248 [00:07<06:58,  5.09it/s]
  5%|▌         | 119/2248 [00:07<05:39,  6.27it/s]
  5%|▌         | 120/2248 [00:08<08:01,  4.42it/s]
  5%|▌         | 123/2248 [00:08<05:32,  6.38it/s]
  6%|▌         | 125/2248 [00:09<06:54,  5.12it/s]
  6%|▌         | 126/2248 [00:09<08:36,  4.11it/s]
  6%|▌         | 127/2248 [00:10<11:00,  3.21it/s]
  6%|▌         | 128/2248 [00:10<12:41,  2.78it/s]
  6%|▌         | 130/2248 [00:11<08:32,  4.13it/s]
  6%|▌         | 132/2248 [00:11<06:59,  5.05it/s]
  6%|▌         | 133/2248 [00:11<09:42,  3.63it/s]
  6%|▌         | 135/2248 [00:12<09:35,  3.67it/s]
  6%|▌         | 136/2248 [00:12<10:12,  3.45it/s]
  6%|▌         | 138/2248 [00:13<09:24,  3.74it/s]
  6%|▌         | 139/2248 [00:13<08:46,  4.00it/s]
  6%|▋         | 141/2248 [00:13<06:12,  5.66it/s]
  6%|▋         | 145/2248 [00:13<05:11,  6.75it/s]
  7%|▋         | 147/2248 [00:14<04:19,  8.10it/s]
  7%|▋         | 149/2248 [00:14<03:43,  9.38it/s]
  7%|▋         | 151/2248 [00:14<04:31,  7.71it/s]
  7%|▋         | 153/2248 [00:14<04:13,  8.25it/s]
  7%|▋         | 155/2248 [00:14<03:30,  9.96it/s]
  7%|▋         | 157/2248 [00:15<03:33,  9.81it/s]
  7%|▋         | 159/2248 [00:15<04:54,  7.10it/s]
  7%|▋         | 160/2248 [00:15<06:12,  5.61it/s]
  7%|▋         | 162/2248 [00:16<06:03,  5.74it/s]
  7%|▋         | 164/2248 [00:16<04:45,  7.31it/s]
  7%|▋         | 166/2248 [00:17<06:47,  5.11it/s]
  7%|▋         | 168/2248 [00:17<05:24,  6.40it/s]
  8%|▊         | 170/2248 [00:17<05:57,  5.80it/s]
  8%|▊         | 172/2248 [00:17<05:11,  6.67it/s]
  8%|▊         | 173/2248 [00:17<05:14,  6.61it/s]
  8%|▊         | 174/2248 [00:18<04:57,  6.97it/s]
  8%|▊         | 176/2248 [00:18<05:05,  6.77it/s]
  8%|▊         | 178/2248 [00:18<05:03,  6.82it/s]
  8%|▊         | 180/2248 [00:18<03:59,  8.63it/s]
  8%|▊         | 182/2248 [00:18<03:28,  9.93it/s]
  8%|▊         | 184/2248 [00:19<03:39,  9.39it/s]
  8%|▊         | 186/2248 [00:19<05:36,  6.13it/s]
  8%|▊         | 187/2248 [00:20<07:53,  4.35it/s]
  8%|▊         | 189/2248 [00:20<05:58,  5.74it/s]
  8%|▊         | 190/2248 [00:20<08:25,  4.07it/s]
  8%|▊         | 191/2248 [00:21<07:33,  4.53it/s]
  9%|▊         | 192/2248 [00:21<07:05,  4.83it/s]
  9%|▊         | 194/2248 [00:21<05:01,  6.80it/s]
  9%|▉         | 197/2248 [00:21<04:00,  8.51it/s]
  9%|▉         | 199/2248 [00:21<03:48,  8.96it/s]
  9%|▉         | 201/2248 [00:22<05:38,  6.05it/s]
  9%|▉         | 202/2248 [00:22<08:04,  4.22it/s]
  9%|▉         | 203/2248 [00:23<08:02,  4.24it/s]
  9%|▉         | 205/2248 [00:23<09:09,  3.72it/s]
  9%|▉         | 207/2248 [00:24<09:38,  3.53it/s]
  9%|▉         | 208/2248 [00:24<11:34,  2.94it/s]
  9%|▉         | 209/2248 [00:25<13:30,  2.52it/s]
  9%|▉         | 210/2248 [00:25<12:02,  2.82it/s]
  9%|▉         | 211/2248 [00:26<12:23,  2.74it/s]
  9%|▉         | 212/2248 [00:26<11:07,  3.05it/s]
  9%|▉         | 213/2248 [00:26<09:38,  3.52it/s]
 10%|▉         | 215/2248 [00:26<06:28,  5.23it/s]
 10%|▉         | 220/2248 [00:26<02:58, 11.34it/s]
 10%|█         | 226/2248 [00:26<01:50, 18.27it/s]
 10%|█         | 230/2248 [00:27<01:32, 21.74it/s]
 10%|█         | 236/2248 [00:27<01:10, 28.69it/s]
 11%|█         | 243/2248 [00:27<00:53, 37.53it/s]
 11%|█         | 249/2248 [00:27<00:48, 41.59it/s]
 11%|█▏        | 254/2248 [00:27<00:46, 43.29it/s]
 12%|█▏        | 259/2248 [00:27<00:45, 43.60it/s]
 12%|█▏        | 265/2248 [00:27<00:43, 46.02it/s]
 12%|█▏        | 271/2248 [00:27<00:43, 45.96it/s]
 12%|█▏        | 276/2248 [00:28<00:45, 42.95it/s]
 13%|█▎        | 282/2248 [00:28<00:42, 46.48it/s]
 13%|█▎        | 287/2248 [00:28<01:39, 19.69it/s]
 13%|█▎        | 291/2248 [00:30<03:46,  8.63it/s]
 13%|█▎        | 294/2248 [00:30<03:22,  9.65it/s]
 13%|█▎        | 297/2248 [00:30<03:02, 10.67it/s]
 13%|█▎        | 300/2248 [00:30<02:51, 11.33it/s]
 13%|█▎        | 302/2248 [00:30<02:38, 12.28it/s]
 14%|█▎        | 304/2248 [00:31<04:11,  7.74it/s]
 14%|█▎        | 307/2248 [00:31<05:03,  6.40it/s]
 14%|█▎        | 309/2248 [00:32<06:11,  5.22it/s]
 14%|█▍        | 310/2248 [00:32<06:37,  4.87it/s]
 14%|█▍        | 312/2248 [00:33<05:19,  6.05it/s]
 14%|█▍        | 313/2248 [00:33<07:50,  4.12it/s]
 14%|█▍        | 314/2248 [00:33<08:19,  3.87it/s]
 14%|█▍        | 315/2248 [00:34<08:16,  3.89it/s]
 14%|█▍        | 317/2248 [00:34<05:43,  5.62it/s]
 14%|█▍        | 320/2248 [00:34<04:58,  6.46it/s]
 14%|█▍        | 322/2248 [00:35<05:11,  6.18it/s]
 14%|█▍        | 324/2248 [00:35<04:35,  6.98it/s]
 15%|█▍        | 326/2248 [00:35<03:55,  8.18it/s]
 15%|█▍        | 330/2248 [00:35<02:29, 12.85it/s]
 15%|█▍        | 332/2248 [00:35<03:22,  9.45it/s]
 15%|█▍        | 334/2248 [00:35<02:55, 10.91it/s]
 15%|█▍        | 336/2248 [00:36<02:37, 12.11it/s]
 15%|█▌        | 339/2248 [00:36<03:47,  8.40it/s]
 15%|█▌        | 341/2248 [00:36<03:30,  9.05it/s]
 15%|█▌        | 343/2248 [00:37<04:31,  7.02it/s]
 15%|█▌        | 345/2248 [00:38<06:43,  4.72it/s]
 15%|█▌        | 346/2248 [00:38<06:58,  4.55it/s]
 15%|█▌        | 347/2248 [00:38<07:44,  4.09it/s]
 15%|█▌        | 348/2248 [00:38<07:49,  4.05it/s]
 16%|█▌        | 349/2248 [00:39<09:41,  3.26it/s]
 16%|█▌        | 350/2248 [00:39<09:08,  3.46it/s]
 16%|█▌        | 352/2248 [00:39<06:12,  5.08it/s]
 16%|█▌        | 353/2248 [00:40<08:09,  3.87it/s]
 16%|█▌        | 355/2248 [00:40<05:52,  5.37it/s]
 16%|█▌        | 356/2248 [00:40<06:52,  4.59it/s]
 16%|█▌        | 358/2248 [00:40<04:50,  6.51it/s]
 16%|█▌        | 360/2248 [00:40<03:53,  8.10it/s]
 16%|█▌        | 362/2248 [00:41<04:34,  6.88it/s]
 16%|█▌        | 363/2248 [00:41<04:19,  7.27it/s]
 16%|█▌        | 364/2248 [00:41<04:21,  7.19it/s]
 16%|█▋        | 366/2248 [00:42<06:25,  4.89it/s]
 16%|█▋        | 368/2248 [00:42<04:50,  6.48it/s]
 17%|█▋        | 373/2248 [00:42<02:29, 12.54it/s]
 17%|█▋        | 377/2248 [00:43<03:21,  9.27it/s]
 17%|█▋        | 379/2248 [00:43<03:04, 10.15it/s]
 17%|█▋        | 384/2248 [00:43<02:33, 12.13it/s]
 17%|█▋        | 386/2248 [00:43<03:01, 10.26it/s]
 17%|█▋        | 388/2248 [00:43<02:50, 10.90it/s]
 17%|█▋        | 390/2248 [00:44<03:23,  9.13it/s]
 17%|█▋        | 392/2248 [00:44<04:00,  7.72it/s]
 17%|█▋        | 393/2248 [00:45<04:58,  6.22it/s]
 18%|█▊        | 394/2248 [00:45<05:00,  6.16it/s]
 18%|█▊        | 398/2248 [00:45<02:58, 10.37it/s]
 18%|█▊        | 403/2248 [00:45<02:09, 14.21it/s]
 18%|█▊        | 405/2248 [00:45<02:03, 14.93it/s]
 18%|█▊        | 408/2248 [00:45<01:44, 17.53it/s]
 18%|█▊        | 412/2248 [00:45<01:42, 17.89it/s]
 18%|█▊        | 415/2248 [00:46<01:36, 18.98it/s]
 19%|█▊        | 418/2248 [00:46<02:24, 12.67it/s]
 19%|█▉        | 423/2248 [00:46<01:41, 17.96it/s]
 19%|█▉        | 426/2248 [00:46<01:53, 16.01it/s]
 19%|█▉        | 429/2248 [00:46<01:39, 18.22it/s]
 19%|█▉        | 434/2248 [00:47<01:16, 23.59it/s]
 19%|█▉        | 437/2248 [00:48<03:38,  8.30it/s]
 20%|█▉        | 440/2248 [00:48<04:26,  6.78it/s]
 20%|█▉        | 442/2248 [00:48<03:51,  7.80it/s]
 20%|█▉        | 444/2248 [00:49<04:54,  6.13it/s]
 20%|█▉        | 446/2248 [00:50<05:56,  5.05it/s]
 20%|█▉        | 449/2248 [00:50<04:20,  6.92it/s]
 20%|██        | 456/2248 [00:50<02:16, 13.16it/s]
 20%|██        | 460/2248 [00:50<02:58,  9.99it/s]
 21%|██        | 463/2248 [00:51<03:55,  7.58it/s]
 21%|██        | 465/2248 [00:52<04:19,  6.86it/s]
 21%|██        | 467/2248 [00:52<04:07,  7.19it/s]
 21%|██        | 469/2248 [00:52<03:49,  7.75it/s]
 21%|██        | 472/2248 [00:53<04:30,  6.57it/s]
 21%|██        | 475/2248 [00:53<05:01,  5.89it/s]
 21%|██        | 476/2248 [00:54<06:33,  4.50it/s]
 21%|██▏       | 478/2248 [00:54<05:12,  5.66it/s]
 21%|██▏       | 480/2248 [00:54<06:16,  4.70it/s]
 21%|██▏       | 481/2248 [00:55<08:07,  3.63it/s]
 21%|██▏       | 482/2248 [00:55<08:17,  3.55it/s]
 22%|██▏       | 485/2248 [00:55<05:00,  5.88it/s]
 22%|██▏       | 487/2248 [00:57<08:33,  3.43it/s]
 22%|██▏       | 490/2248 [00:57<05:36,  5.23it/s]
 22%|██▏       | 495/2248 [00:57<04:45,  6.14it/s]
 22%|██▏       | 497/2248 [00:58<04:09,  7.01it/s]
 22%|██▏       | 499/2248 [00:58<05:26,  5.35it/s]
 22%|██▏       | 501/2248 [00:59<06:04,  4.79it/s]
 22%|██▏       | 502/2248 [00:59<06:04,  4.80it/s]
 22%|██▏       | 505/2248 [00:59<04:04,  7.13it/s]
 23%|██▎       | 507/2248 [00:59<04:01,  7.20it/s]
 23%|██▎       | 509/2248 [01:00<05:14,  5.53it/s]
 23%|██▎       | 512/2248 [01:00<04:38,  6.24it/s]
 23%|██▎       | 514/2248 [01:01<04:33,  6.35it/s]
 23%|██▎       | 515/2248 [01:01<06:06,  4.73it/s]
 23%|██▎       | 517/2248 [01:01<04:40,  6.17it/s]
 23%|██▎       | 518/2248 [01:02<06:50,  4.21it/s]
 23%|██▎       | 520/2248 [01:02<05:11,  5.55it/s]
 23%|██▎       | 523/2248 [01:02<03:33,  8.08it/s]
 23%|██▎       | 527/2248 [01:02<02:28, 11.62it/s]
 24%|██▎       | 529/2248 [01:02<02:16, 12.62it/s]
 24%|██▍       | 534/2248 [01:02<01:32, 18.55it/s]
 24%|██▍       | 538/2248 [01:03<01:15, 22.57it/s]
 24%|██▍       | 542/2248 [01:03<01:05, 26.11it/s]
 24%|██▍       | 546/2248 [01:03<01:07, 25.31it/s]
 25%|██▍       | 552/2248 [01:03<00:55, 30.39it/s]
 25%|██▍       | 556/2248 [01:03<01:17, 21.71it/s]
 25%|██▍       | 559/2248 [01:03<01:13, 23.04it/s]
 25%|██▌       | 562/2248 [01:04<01:16, 22.05it/s]
 25%|██▌       | 568/2248 [01:04<00:56, 29.70it/s]
 25%|██▌       | 572/2248 [01:05<03:01,  9.24it/s]
 26%|██▌       | 575/2248 [01:06<04:57,  5.63it/s]
 26%|██▌       | 578/2248 [01:06<04:40,  5.94it/s]
 26%|██▌       | 580/2248 [01:07<05:20,  5.21it/s]
 26%|██▌       | 582/2248 [01:08<07:22,  3.76it/s]
 26%|██▌       | 584/2248 [01:08<05:58,  4.64it/s]
 26%|██▌       | 586/2248 [01:09<06:25,  4.31it/s]
 26%|██▌       | 588/2248 [01:09<05:05,  5.44it/s]
 26%|██▋       | 591/2248 [01:09<03:35,  7.69it/s]
 26%|██▋       | 593/2248 [01:09<03:43,  7.39it/s]
 26%|██▋       | 595/2248 [01:09<03:09,  8.74it/s]
 27%|██▋       | 598/2248 [01:10<02:30, 10.95it/s]
 27%|██▋       | 601/2248 [01:10<02:08, 12.85it/s]
 27%|██▋       | 603/2248 [01:10<03:36,  7.59it/s]
 27%|██▋       | 605/2248 [01:11<03:53,  7.05it/s]
 27%|██▋       | 607/2248 [01:11<04:21,  6.27it/s]
 27%|██▋       | 608/2248 [01:11<04:39,  5.86it/s]
 27%|██▋       | 609/2248 [01:12<05:27,  5.01it/s]
 27%|██▋       | 610/2248 [01:12<07:36,  3.59it/s]
 27%|██▋       | 612/2248 [01:12<05:21,  5.09it/s]
 27%|██▋       | 616/2248 [01:12<03:01,  9.01it/s]
 27%|██▋       | 618/2248 [01:13<03:15,  8.35it/s]
 28%|██▊       | 620/2248 [01:13<02:48,  9.66it/s]
 28%|██▊       | 622/2248 [01:13<03:04,  8.81it/s]
 28%|██▊       | 624/2248 [01:13<02:36, 10.35it/s]
 28%|██▊       | 626/2248 [01:13<02:23, 11.28it/s]
 28%|██▊       | 628/2248 [01:14<02:23, 11.32it/s]
 28%|██▊       | 630/2248 [01:14<02:11, 12.35it/s]
 28%|██▊       | 632/2248 [01:14<02:12, 12.19it/s]
 28%|██▊       | 636/2248 [01:14<01:39, 16.18it/s]
 28%|██▊       | 638/2248 [01:14<01:40, 16.01it/s]
 29%|██▊       | 641/2248 [01:14<01:34, 16.93it/s]
 29%|██▊       | 644/2248 [01:14<01:28, 18.19it/s]
 29%|██▉       | 647/2248 [01:15<01:18, 20.41it/s]
 29%|██▉       | 650/2248 [01:15<02:35, 10.30it/s]
 29%|██▉       | 652/2248 [01:16<03:45,  7.08it/s]
 29%|██▉       | 654/2248 [01:16<04:43,  5.62it/s]
 29%|██▉       | 658/2248 [01:17<04:12,  6.29it/s]
 29%|██▉       | 660/2248 [01:17<04:04,  6.49it/s]
 29%|██▉       | 661/2248 [01:18<05:41,  4.65it/s]
 29%|██▉       | 663/2248 [01:18<06:31,  4.05it/s]
 30%|██▉       | 665/2248 [01:19<07:01,  3.76it/s]
 30%|██▉       | 668/2248 [01:19<04:45,  5.53it/s]
 30%|██▉       | 670/2248 [01:20<05:29,  4.79it/s]
 30%|██▉       | 673/2248 [01:20<04:25,  5.94it/s]
 30%|███       | 675/2248 [01:20<03:38,  7.21it/s]
 30%|███       | 677/2248 [01:21<04:48,  5.45it/s]
 30%|███       | 678/2248 [01:21<05:36,  4.66it/s]
 30%|███       | 681/2248 [01:21<04:26,  5.88it/s]
 30%|███       | 682/2248 [01:22<06:07,  4.26it/s]
 30%|███       | 684/2248 [01:22<06:29,  4.01it/s]
 30%|███       | 685/2248 [01:23<07:49,  3.33it/s]
 31%|███       | 687/2248 [01:23<05:42,  4.56it/s]
 31%|███       | 688/2248 [01:24<07:36,  3.42it/s]
 31%|███       | 689/2248 [01:24<07:58,  3.26it/s]
 31%|███       | 691/2248 [01:24<05:30,  4.71it/s]
 31%|███       | 692/2248 [01:25<07:37,  3.40it/s]
 31%|███       | 695/2248 [01:25<04:28,  5.79it/s]
 31%|███       | 697/2248 [01:25<03:56,  6.57it/s]
 31%|███       | 700/2248 [01:25<03:18,  7.82it/s]
 31%|███       | 702/2248 [01:26<04:20,  5.94it/s]
 31%|███▏      | 704/2248 [01:26<04:36,  5.59it/s]
 31%|███▏      | 706/2248 [01:26<03:39,  7.02it/s]
 32%|███▏      | 709/2248 [01:27<02:38,  9.71it/s]
 32%|███▏      | 711/2248 [01:27<03:33,  7.19it/s]
 32%|███▏      | 713/2248 [01:27<03:02,  8.41it/s]
 32%|███▏      | 715/2248 [01:27<02:42,  9.44it/s]
 32%|███▏      | 718/2248 [01:27<02:05, 12.20it/s]
 32%|███▏      | 720/2248 [01:28<02:13, 11.41it/s]
 32%|███▏      | 722/2248 [01:28<02:01, 12.53it/s]
 32%|███▏      | 726/2248 [01:28<01:27, 17.49it/s]
 32%|███▏      | 729/2248 [01:28<02:17, 11.08it/s]
 33%|███▎      | 731/2248 [01:29<02:20, 10.79it/s]
 33%|███▎      | 734/2248 [01:29<01:50, 13.66it/s]
 33%|███▎      | 736/2248 [01:29<03:23,  7.44it/s]
 33%|███▎      | 738/2248 [01:30<03:54,  6.44it/s]
 33%|███▎      | 740/2248 [01:30<03:22,  7.44it/s]
 33%|███▎      | 742/2248 [01:30<03:22,  7.42it/s]
 33%|███▎      | 744/2248 [01:31<05:37,  4.45it/s]
 33%|███▎      | 746/2248 [01:31<04:33,  5.49it/s]
 33%|███▎      | 748/2248 [01:31<03:48,  6.55it/s]
 33%|███▎      | 750/2248 [01:32<03:41,  6.76it/s]
 33%|███▎      | 751/2248 [01:32<04:16,  5.84it/s]
 33%|███▎      | 752/2248 [01:32<04:33,  5.47it/s]
 34%|███▎      | 754/2248 [01:32<03:32,  7.02it/s]
 34%|███▎      | 757/2248 [01:33<02:26, 10.19it/s]
 34%|███▍      | 761/2248 [01:33<02:55,  8.45it/s]
 34%|███▍      | 763/2248 [01:33<02:34,  9.60it/s]
 34%|███▍      | 765/2248 [01:33<02:33,  9.65it/s]
 34%|███▍      | 767/2248 [01:34<04:01,  6.14it/s]
 34%|███▍      | 770/2248 [01:34<02:53,  8.54it/s]
 34%|███▍      | 772/2248 [01:35<03:57,  6.20it/s]
 34%|███▍      | 774/2248 [01:35<04:47,  5.12it/s]
 34%|███▍      | 775/2248 [01:36<06:04,  4.04it/s]
 35%|███▍      | 776/2248 [01:36<07:38,  3.21it/s]
 35%|███▍      | 778/2248 [01:37<07:34,  3.23it/s]
 35%|███▍      | 779/2248 [01:37<06:55,  3.54it/s]
 35%|███▍      | 782/2248 [01:38<06:01,  4.06it/s]
 35%|███▍      | 783/2248 [01:38<07:31,  3.24it/s]
 35%|███▍      | 784/2248 [01:39<08:40,  2.81it/s]
 35%|███▍      | 786/2248 [01:39<05:56,  4.10it/s]
 35%|███▌      | 788/2248 [01:39<04:56,  4.92it/s]
 35%|███▌      | 791/2248 [01:40<04:45,  5.11it/s]
 35%|███▌      | 792/2248 [01:40<05:57,  4.07it/s]
 35%|███▌      | 793/2248 [01:41<05:47,  4.19it/s]
 35%|███▌      | 795/2248 [01:41<04:21,  5.56it/s]
 35%|███▌      | 797/2248 [01:41<04:43,  5.13it/s]
 36%|███▌      | 799/2248 [01:41<03:58,  6.06it/s]
 36%|███▌      | 800/2248 [01:42<05:48,  4.16it/s]
 36%|███▌      | 803/2248 [01:42<03:43,  6.45it/s]
 36%|███▌      | 805/2248 [01:42<03:09,  7.60it/s]
 36%|███▌      | 807/2248 [01:43<04:37,  5.20it/s]
 36%|███▌      | 810/2248 [01:44<04:48,  4.98it/s]
 36%|███▌      | 811/2248 [01:44<06:19,  3.79it/s]
 36%|███▌      | 812/2248 [01:45<07:48,  3.06it/s]
 36%|███▌      | 814/2248 [01:45<05:32,  4.31it/s]
 36%|███▋      | 815/2248 [01:45<06:58,  3.43it/s]
 36%|███▋      | 817/2248 [01:46<05:46,  4.13it/s]
 36%|███▋      | 819/2248 [01:46<04:18,  5.52it/s]
 37%|███▋      | 825/2248 [01:46<01:59, 11.93it/s]
 37%|███▋      | 831/2248 [01:46<01:21, 17.48it/s]
 37%|███▋      | 836/2248 [01:46<01:06, 21.26it/s]
 38%|███▊      | 843/2248 [01:46<00:47, 29.57it/s]
 38%|███▊      | 849/2248 [01:46<00:39, 35.03it/s]
 38%|███▊      | 855/2248 [01:47<00:34, 40.11it/s]
 38%|███▊      | 860/2248 [01:47<00:34, 39.89it/s]
 39%|███▊      | 867/2248 [01:47<01:05, 21.05it/s]
 39%|███▊      | 871/2248 [01:48<01:43, 13.31it/s]
 39%|███▉      | 874/2248 [01:48<01:47, 12.77it/s]
 39%|███▉      | 877/2248 [01:49<02:22,  9.62it/s]
 39%|███▉      | 880/2248 [01:49<02:01, 11.30it/s]
 39%|███▉      | 882/2248 [01:50<02:56,  7.75it/s]
 39%|███▉      | 884/2248 [01:50<02:36,  8.74it/s]
 39%|███▉      | 886/2248 [01:50<02:57,  7.68it/s]
 40%|███▉      | 888/2248 [01:50<02:34,  8.79it/s]
 40%|███▉      | 891/2248 [01:51<03:13,  7.03it/s]
 40%|███▉      | 893/2248 [01:51<02:52,  7.87it/s]
 40%|███▉      | 895/2248 [01:52<05:17,  4.26it/s]
 40%|███▉      | 897/2248 [01:52<04:09,  5.42it/s]
 40%|███▉      | 899/2248 [01:52<03:18,  6.79it/s]
 40%|████      | 901/2248 [01:52<02:50,  7.92it/s]
 40%|████      | 903/2248 [01:53<03:56,  5.69it/s]
 40%|████      | 905/2248 [01:53<03:15,  6.88it/s]
 40%|████      | 907/2248 [01:54<06:03,  3.69it/s]
 40%|████      | 908/2248 [01:55<07:09,  3.12it/s]
 40%|████      | 909/2248 [01:55<08:14,  2.71it/s]
 40%|████      | 910/2248 [01:56<09:09,  2.44it/s]
 41%|████      | 911/2248 [01:56<09:54,  2.25it/s]
 41%|████      | 912/2248 [01:57<10:23,  2.14it/s]
 41%|████      | 913/2248 [01:57<10:22,  2.14it/s]
 41%|████      | 914/2248 [01:58<08:13,  2.70it/s]
 41%|████      | 916/2248 [01:58<05:15,  4.22it/s]
 41%|████      | 919/2248 [01:58<03:03,  7.24it/s]
 41%|████      | 921/2248 [01:58<03:46,  5.85it/s]
 41%|████      | 923/2248 [01:58<03:15,  6.78it/s]
 41%|████      | 925/2248 [01:59<04:40,  4.71it/s]
 41%|████      | 927/2248 [02:00<05:11,  4.24it/s]
 41%|████▏     | 929/2248 [02:00<03:58,  5.54it/s]
 41%|████▏     | 931/2248 [02:00<04:15,  5.16it/s]
 42%|████▏     | 933/2248 [02:00<03:19,  6.60it/s]
 42%|████▏     | 935/2248 [02:01<03:15,  6.71it/s]
 42%|████▏     | 937/2248 [02:01<02:52,  7.60it/s]
 42%|████▏     | 939/2248 [02:01<02:31,  8.63it/s]
 42%|████▏     | 943/2248 [02:01<01:45, 12.42it/s]
 42%|████▏     | 946/2248 [02:01<01:25, 15.29it/s]
 42%|████▏     | 951/2248 [02:02<01:09, 18.73it/s]
 42%|████▏     | 954/2248 [02:02<01:49, 11.80it/s]
 43%|████▎     | 956/2248 [02:02<01:43, 12.47it/s]
 43%|████▎     | 958/2248 [02:03<04:02,  5.33it/s]
 43%|████▎     | 960/2248 [02:04<04:36,  4.66it/s]
 43%|████▎     | 961/2248 [02:04<05:46,  3.71it/s]
 43%|████▎     | 963/2248 [02:05<06:13,  3.44it/s]
 43%|████▎     | 964/2248 [02:05<05:42,  3.75it/s]
 43%|████▎     | 966/2248 [02:06<05:59,  3.57it/s]
 43%|████▎     | 967/2248 [02:06<07:22,  2.90it/s]
 43%|████▎     | 969/2248 [02:07<05:10,  4.11it/s]
 43%|████▎     | 970/2248 [02:07<06:29,  3.28it/s]
 43%|████▎     | 973/2248 [02:07<03:54,  5.43it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 315.87it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 6], [np.int64(2), False, 7], [np.int64(4), False, 11], [np.int64(5), False, 9], [np.int64(8), False, 11], [np.int64(9), False, 0], [np.int64(10), False, 3], [np.int64(12), False, 1], [np.int64(13), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2686, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [12:55<2:17:42, 83.46s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [12:55<1:35:30, 58.47s/it]

tensor(12.5067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6275, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5124, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0466, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [12:55<31:52, 20.13s/it]

tensor(12.5248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0955, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0376, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2191, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [12:55<15:22,  9.92s/it]

tensor(12.5544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0416, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2638, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8884, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [12:56<07:27,  4.92s/it]

tensor(12.5657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0470, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9386, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0479, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0059, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [12:56<03:39,  2.47s/it]

tensor(12.5619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0488, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9121, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0497, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1329, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [12:56<01:50,  1.27s/it]

tensor(12.5656, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0516, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2618, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0532, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3145, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [12:56<00:58,  1.47it/s]

tensor(12.5820, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0551, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3760, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4259, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [12:56<00:32,  2.55it/s]

tensor(12.5557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0590, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4732, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0604, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4997, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [12:57<00:20,  3.97it/s]

tensor(12.5295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0605, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5152, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0594, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5420, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [12:57<00:14,  5.49it/s]

tensor(12.5258, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0576, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5564, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0553, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5565, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [12:57<00:11,  6.71it/s]

tensor(12.5078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0526, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5495, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4978, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0500, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5531, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▍  | 224/300 [12:57<00:10,  7.21it/s]

tensor(12.4923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0479, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5327, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4904, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0461, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5356, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [12:58<00:09,  7.92it/s]

tensor(12.4888, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0441, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5383, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0421, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5357, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [12:58<00:08,  8.24it/s]

tensor(12.4788, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0396, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5438, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [12:58<00:08,  8.43it/s]

tensor(12.4696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5478, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5490, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 232/300 [12:58<00:08,  8.42it/s]

tensor(12.4666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5505, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4648, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5518, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [12:59<00:07,  8.33it/s]

tensor(12.4619, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5556, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5574, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [12:59<00:07,  8.49it/s]

tensor(12.4559, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5529, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4536, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5512, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [12:59<00:07,  8.52it/s]

tensor(12.4516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5483, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5413, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [12:59<00:07,  8.39it/s]

tensor(12.4472, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5394, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [13:00<00:06,  8.56it/s]

tensor(12.4424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5376, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5380, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [13:00<00:06,  8.53it/s]

tensor(12.4381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5400, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5390, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [13:00<00:06,  8.60it/s]

tensor(12.4341, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5314, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5299, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [13:00<00:06,  8.48it/s]

tensor(12.4301, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5249, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4283, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5267, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [13:00<00:06,  8.28it/s]

tensor(12.4262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5258, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([111, 336, 115, 172, 172, 125, 331, 132, 151,  96,  80, 108, 180, 139])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:23, 26.86it/s]
  0%|          | 6/2248 [00:00<01:35, 23.46it/s]
  1%|          | 12/2248 [00:00<00:59, 37.39it/s]
  1%|          | 17/2248 [00:00<01:03, 34.98it/s]
  1%|          | 23/2248 [00:00<00:53, 41.53it/s]
  1%|          | 28/2248 [00:00<00:54, 40.87it/s]
  2%|▏         | 36/2248 [00:00<00:44, 49.93it/s]
  2%|▏         | 43/2248 [00:00<00:40, 55.01it/s]
  2%|▏         | 49/2248 [00:01<00:41, 52.47it/s]
  2%|▏         | 55/2248 [00:01<00:42, 51.37it/s]
  3%|▎         | 62/2248 [00:01<00:39, 55.10it/s]
  3%|▎         | 68/2248 [00:01<00:39, 55.04it/s]
  3%|▎         | 74/2248 [00:01<01:18, 27.66it/s]
  4%|▎         | 79/2248 [00:02<02:38, 13.66it/s]
  4%|▎         | 83/2248 [00:03<02:31, 14.33it/s]
  4%|▍         | 86/2248 [00:03<02:47, 12.89it/s]
  4%|▍         | 89/2248 [00:03<02:37, 13.67it/s]
  4%|▍         | 92/2248 [00:03<02:50, 12.63it/s]
  4%|▍         | 95/2248 [00:04<03:22, 10.62it/s]
  4%|▍         | 97/2248 [00:04<03:19, 10.79it/s]
  4%|▍         | 99/2248 [00:04<03:00, 11.94it/s]
  5%|▍         | 103/2248 [00:04<02:54, 12.28it/s]
  5%|▍         | 105/2248 [00:04<02:44, 13.02it/s]
  5%|▍         | 108/2248 [00:05<02:15, 15.79it/s]
  5%|▍         | 111/2248 [00:05<03:14, 11.01it/s]
  5%|▌         | 113/2248 [00:05<02:54, 12.24it/s]
  5%|▌         | 115/2248 [00:05<02:45, 12.91it/s]
  5%|▌         | 117/2248 [00:06<04:33,  7.78it/s]
  5%|▌         | 119/2248 [00:06<04:35,  7.73it/s]
  5%|▌         | 121/2248 [00:06<04:53,  7.25it/s]
  5%|▌         | 122/2248 [00:07<06:16,  5.64it/s]
  5%|▌         | 123/2248 [00:07<05:49,  6.08it/s]
  6%|▌         | 126/2248 [00:07<04:29,  7.88it/s]
  6%|▌         | 127/2248 [00:07<04:50,  7.30it/s]
  6%|▌         | 128/2248 [00:08<06:21,  5.56it/s]
  6%|▌         | 131/2248 [00:08<03:59,  8.83it/s]
  6%|▌         | 133/2248 [00:08<03:55,  8.97it/s]
  6%|▌         | 135/2248 [00:08<04:38,  7.60it/s]
  6%|▌         | 136/2248 [00:09<05:24,  6.50it/s]
  6%|▌         | 138/2248 [00:09<06:43,  5.23it/s]
  6%|▌         | 140/2248 [00:09<05:07,  6.86it/s]
  6%|▋         | 145/2248 [00:10<04:10,  8.38it/s]
  7%|▋         | 148/2248 [00:10<03:19, 10.54it/s]
  7%|▋         | 151/2248 [00:10<03:47,  9.22it/s]
  7%|▋         | 153/2248 [00:10<03:58,  8.78it/s]
  7%|▋         | 156/2248 [00:11<04:03,  8.60it/s]
  7%|▋         | 158/2248 [00:12<06:50,  5.09it/s]
  7%|▋         | 159/2248 [00:12<08:12,  4.25it/s]
  7%|▋         | 160/2248 [00:13<08:35,  4.05it/s]
  7%|▋         | 162/2248 [00:13<08:13,  4.23it/s]
  7%|▋         | 164/2248 [00:13<06:13,  5.58it/s]
  7%|▋         | 165/2248 [00:13<05:59,  5.80it/s]
  7%|▋         | 166/2248 [00:13<06:40,  5.19it/s]
  7%|▋         | 168/2248 [00:14<06:32,  5.31it/s]
  8%|▊         | 169/2248 [00:14<06:59,  4.95it/s]
  8%|▊         | 171/2248 [00:14<05:10,  6.68it/s]
  8%|▊         | 173/2248 [00:15<06:13,  5.55it/s]
  8%|▊         | 176/2248 [00:15<06:22,  5.41it/s]
  8%|▊         | 178/2248 [00:16<07:21,  4.68it/s]
  8%|▊         | 180/2248 [00:16<08:02,  4.29it/s]
  8%|▊         | 183/2248 [00:17<06:41,  5.14it/s]
  8%|▊         | 185/2248 [00:17<07:29,  4.59it/s]
  8%|▊         | 187/2248 [00:18<07:14,  4.74it/s]
  8%|▊         | 189/2248 [00:18<07:14,  4.74it/s]
  8%|▊         | 191/2248 [00:18<05:43,  5.98it/s]
  9%|▊         | 193/2248 [00:19<06:32,  5.24it/s]
  9%|▊         | 195/2248 [00:19<07:38,  4.48it/s]
  9%|▉         | 197/2248 [00:20<05:57,  5.74it/s]
  9%|▉         | 201/2248 [00:20<05:07,  6.66it/s]
  9%|▉         | 202/2248 [00:20<06:04,  5.61it/s]
  9%|▉         | 204/2248 [00:20<04:55,  6.91it/s]
  9%|▉         | 205/2248 [00:21<06:06,  5.57it/s]
  9%|▉         | 206/2248 [00:21<08:10,  4.17it/s]
  9%|▉         | 207/2248 [00:22<09:52,  3.44it/s]
  9%|▉         | 208/2248 [00:22<11:40,  2.91it/s]
  9%|▉         | 209/2248 [00:23<11:18,  3.00it/s]
  9%|▉         | 210/2248 [00:23<12:55,  2.63it/s]
  9%|▉         | 211/2248 [00:23<12:07,  2.80it/s]
  9%|▉         | 212/2248 [00:24<13:10,  2.58it/s]
 10%|▉         | 214/2248 [00:24<08:14,  4.11it/s]
 10%|▉         | 221/2248 [00:24<02:53, 11.69it/s]
 10%|█         | 229/2248 [00:24<01:35, 21.16it/s]
 10%|█         | 235/2248 [00:24<01:13, 27.28it/s]
 11%|█         | 240/2248 [00:25<01:53, 17.67it/s]
 11%|█         | 244/2248 [00:25<01:38, 20.36it/s]
 11%|█         | 248/2248 [00:25<01:28, 22.65it/s]
 11%|█▏        | 255/2248 [00:25<01:05, 30.35it/s]
 12%|█▏        | 261/2248 [00:25<00:54, 36.13it/s]
 12%|█▏        | 266/2248 [00:26<01:54, 17.25it/s]
 12%|█▏        | 270/2248 [00:26<02:17, 14.36it/s]
 12%|█▏        | 273/2248 [00:27<02:23, 13.77it/s]
 12%|█▏        | 276/2248 [00:27<03:05, 10.64it/s]
 12%|█▏        | 278/2248 [00:27<03:17,  9.99it/s]
 12%|█▏        | 280/2248 [00:28<03:41,  8.88it/s]
 13%|█▎        | 282/2248 [00:28<04:54,  6.67it/s]
 13%|█▎        | 284/2248 [00:29<05:09,  6.35it/s]
 13%|█▎        | 286/2248 [00:29<05:24,  6.05it/s]
 13%|█▎        | 288/2248 [00:29<04:31,  7.23it/s]
 13%|█▎        | 290/2248 [00:30<05:25,  6.02it/s]
 13%|█▎        | 292/2248 [00:30<06:26,  5.05it/s]
 13%|█▎        | 294/2248 [00:30<05:11,  6.27it/s]
 13%|█▎        | 295/2248 [00:31<06:32,  4.98it/s]
 13%|█▎        | 298/2248 [00:31<05:29,  5.92it/s]
 13%|█▎        | 299/2248 [00:31<06:14,  5.20it/s]
 13%|█▎        | 301/2248 [00:32<04:56,  6.57it/s]
 13%|█▎        | 302/2248 [00:32<05:26,  5.97it/s]
 13%|█▎        | 303/2248 [00:32<05:47,  5.60it/s]
 14%|█▎        | 306/2248 [00:32<04:08,  7.81it/s]
 14%|█▎        | 307/2248 [00:32<04:08,  7.82it/s]
 14%|█▎        | 308/2248 [00:32<04:13,  7.65it/s]
 14%|█▎        | 309/2248 [00:33<05:03,  6.39it/s]
 14%|█▍        | 311/2248 [00:33<03:43,  8.68it/s]
 14%|█▍        | 313/2248 [00:34<06:47,  4.75it/s]
 14%|█▍        | 314/2248 [00:34<07:33,  4.26it/s]
 14%|█▍        | 315/2248 [00:34<07:06,  4.53it/s]
 14%|█▍        | 317/2248 [00:34<05:04,  6.33it/s]
 14%|█▍        | 320/2248 [00:35<04:44,  6.78it/s]
 14%|█▍        | 322/2248 [00:35<05:47,  5.54it/s]
 14%|█▍        | 323/2248 [00:35<06:35,  4.87it/s]
 14%|█▍        | 325/2248 [00:36<06:37,  4.84it/s]
 15%|█▍        | 327/2248 [00:36<06:26,  4.97it/s]
 15%|█▍        | 328/2248 [00:37<07:05,  4.51it/s]
 15%|█▍        | 330/2248 [00:37<05:11,  6.16it/s]
 15%|█▍        | 332/2248 [00:37<04:29,  7.10it/s]
 15%|█▍        | 335/2248 [00:37<03:14,  9.86it/s]
 15%|█▌        | 339/2248 [00:37<03:37,  8.78it/s]
 15%|█▌        | 342/2248 [00:38<02:52, 11.05it/s]
 15%|█▌        | 344/2248 [00:38<04:27,  7.11it/s]
 15%|█▌        | 346/2248 [00:39<06:18,  5.03it/s]
 15%|█▌        | 347/2248 [00:39<06:45,  4.69it/s]
 15%|█▌        | 348/2248 [00:40<08:07,  3.90it/s]
 16%|█▌        | 349/2248 [00:40<09:24,  3.36it/s]
 16%|█▌        | 350/2248 [00:41<10:39,  2.97it/s]
 16%|█▌        | 353/2248 [00:41<07:23,  4.27it/s]
 16%|█▌        | 354/2248 [00:41<08:13,  3.84it/s]
 16%|█▌        | 355/2248 [00:42<08:39,  3.65it/s]
 16%|█▌        | 356/2248 [00:42<10:06,  3.12it/s]
 16%|█▌        | 358/2248 [00:42<06:46,  4.64it/s]
 16%|█▌        | 362/2248 [00:43<05:20,  5.88it/s]
 16%|█▌        | 364/2248 [00:43<04:21,  7.20it/s]
 16%|█▋        | 366/2248 [00:43<05:15,  5.96it/s]
 16%|█▋        | 367/2248 [00:44<06:01,  5.21it/s]
 16%|█▋        | 369/2248 [00:44<04:38,  6.75it/s]
 17%|█▋        | 371/2248 [00:44<04:45,  6.59it/s]
 17%|█▋        | 373/2248 [00:45<04:59,  6.26it/s]
 17%|█▋        | 376/2248 [00:45<03:31,  8.85it/s]
 17%|█▋        | 378/2248 [00:45<04:38,  6.72it/s]
 17%|█▋        | 380/2248 [00:46<05:42,  5.45it/s]
 17%|█▋        | 381/2248 [00:46<07:06,  4.38it/s]
 17%|█▋        | 383/2248 [00:46<05:18,  5.86it/s]
 17%|█▋        | 385/2248 [00:47<06:49,  4.55it/s]
 17%|█▋        | 388/2248 [00:47<05:03,  6.13it/s]
 17%|█▋        | 389/2248 [00:48<06:10,  5.02it/s]
 17%|█▋        | 390/2248 [00:48<06:13,  4.97it/s]
 17%|█▋        | 391/2248 [00:48<06:37,  4.67it/s]
 17%|█▋        | 392/2248 [00:48<06:14,  4.95it/s]
 17%|█▋        | 393/2248 [00:48<06:44,  4.58it/s]
 18%|█▊        | 394/2248 [00:49<07:09,  4.32it/s]
 18%|█▊        | 395/2248 [00:49<07:00,  4.41it/s]
 18%|█▊        | 397/2248 [00:49<04:39,  6.61it/s]
 18%|█▊        | 399/2248 [00:49<03:28,  8.85it/s]
 18%|█▊        | 406/2248 [00:49<01:30, 20.25it/s]
 18%|█▊        | 414/2248 [00:49<01:01, 30.06it/s]
 19%|█▊        | 419/2248 [00:49<00:54, 33.56it/s]
 19%|█▉        | 423/2248 [00:50<00:52, 34.69it/s]
 19%|█▉        | 427/2248 [00:50<00:53, 33.75it/s]
 19%|█▉        | 434/2248 [00:50<00:42, 42.57it/s]
 20%|█▉        | 439/2248 [00:51<02:38, 11.44it/s]
 20%|█▉        | 443/2248 [00:51<02:49, 10.68it/s]
 20%|█▉        | 446/2248 [00:52<03:54,  7.69it/s]
 20%|█▉        | 448/2248 [00:53<04:32,  6.62it/s]
 20%|██        | 450/2248 [00:53<05:27,  5.49it/s]
 20%|██        | 452/2248 [00:54<04:48,  6.23it/s]
 20%|██        | 454/2248 [00:54<04:22,  6.83it/s]
 20%|██        | 456/2248 [00:54<04:22,  6.84it/s]
 20%|██        | 457/2248 [00:54<04:21,  6.84it/s]
 20%|██        | 459/2248 [00:54<04:08,  7.20it/s]
 21%|██        | 461/2248 [00:55<03:31,  8.46it/s]
 21%|██        | 463/2248 [00:55<04:03,  7.34it/s]
 21%|██        | 465/2248 [00:55<03:59,  7.46it/s]
 21%|██        | 467/2248 [00:55<03:25,  8.68it/s]
 21%|██        | 469/2248 [00:56<04:56,  6.00it/s]
 21%|██        | 471/2248 [00:56<05:06,  5.80it/s]
 21%|██        | 472/2248 [00:57<05:52,  5.04it/s]
 21%|██        | 474/2248 [00:57<04:25,  6.69it/s]
 21%|██        | 476/2248 [00:57<06:35,  4.48it/s]
 21%|██        | 477/2248 [00:58<06:56,  4.25it/s]
 21%|██▏       | 478/2248 [00:58<07:21,  4.01it/s]
 21%|██▏       | 479/2248 [00:58<07:44,  3.81it/s]
 21%|██▏       | 480/2248 [00:58<06:49,  4.32it/s]
 21%|██▏       | 481/2248 [00:59<06:00,  4.91it/s]
 21%|██▏       | 482/2248 [00:59<06:48,  4.32it/s]
 22%|██▏       | 484/2248 [00:59<04:28,  6.58it/s]
 22%|██▏       | 486/2248 [00:59<05:12,  5.65it/s]
 22%|██▏       | 487/2248 [01:00<05:31,  5.32it/s]
 22%|██▏       | 488/2248 [01:00<06:07,  4.78it/s]
 22%|██▏       | 491/2248 [01:00<03:42,  7.91it/s]
 22%|██▏       | 493/2248 [01:01<04:48,  6.07it/s]
 22%|██▏       | 495/2248 [01:01<04:59,  5.86it/s]
 22%|██▏       | 499/2248 [01:01<04:25,  6.58it/s]
 22%|██▏       | 500/2248 [01:02<05:17,  5.51it/s]
 22%|██▏       | 503/2248 [01:02<05:20,  5.44it/s]
 23%|██▎       | 506/2248 [01:03<03:51,  7.53it/s]
 23%|██▎       | 509/2248 [01:03<04:18,  6.73it/s]
 23%|██▎       | 511/2248 [01:03<03:37,  7.97it/s]
 23%|██▎       | 513/2248 [01:04<05:50,  4.95it/s]
 23%|██▎       | 514/2248 [01:04<06:47,  4.26it/s]
 23%|██▎       | 515/2248 [01:05<07:48,  3.70it/s]
 23%|██▎       | 516/2248 [01:05<07:54,  3.65it/s]
 23%|██▎       | 517/2248 [01:05<07:30,  3.85it/s]
 23%|██▎       | 518/2248 [01:06<08:11,  3.52it/s]
 23%|██▎       | 519/2248 [01:06<09:37,  2.99it/s]
 23%|██▎       | 521/2248 [01:06<06:15,  4.60it/s]
 23%|██▎       | 528/2248 [01:06<02:17, 12.49it/s]
 24%|██▍       | 534/2248 [01:07<01:29, 19.12it/s]
 24%|██▍       | 539/2248 [01:07<01:10, 24.12it/s]
 24%|██▍       | 545/2248 [01:07<00:55, 30.51it/s]
 25%|██▍       | 551/2248 [01:07<00:46, 36.24it/s]
 25%|██▍       | 557/2248 [01:07<00:41, 40.97it/s]
 25%|██▌       | 563/2248 [01:07<00:39, 42.61it/s]
 25%|██▌       | 568/2248 [01:07<00:38, 43.90it/s]
 25%|██▌       | 573/2248 [01:08<02:13, 12.59it/s]
 26%|██▌       | 577/2248 [01:09<02:42, 10.26it/s]
 26%|██▌       | 580/2248 [01:09<03:11,  8.71it/s]
 26%|██▌       | 583/2248 [01:10<04:04,  6.80it/s]
 26%|██▌       | 585/2248 [01:10<03:39,  7.57it/s]
 26%|██▌       | 587/2248 [01:11<03:38,  7.61it/s]
 26%|██▌       | 589/2248 [01:11<03:43,  7.43it/s]
 26%|██▋       | 591/2248 [01:11<03:11,  8.65it/s]
 26%|██▋       | 593/2248 [01:11<03:59,  6.90it/s]
 26%|██▋       | 595/2248 [01:12<03:25,  8.06it/s]
 27%|██▋       | 599/2248 [01:12<02:25, 11.32it/s]
 27%|██▋       | 601/2248 [01:12<02:11, 12.49it/s]
 27%|██▋       | 603/2248 [01:12<02:57,  9.26it/s]
 27%|██▋       | 605/2248 [01:13<04:39,  5.88it/s]
 27%|██▋       | 607/2248 [01:14<06:10,  4.43it/s]
 27%|██▋       | 608/2248 [01:14<06:43,  4.07it/s]
 27%|██▋       | 609/2248 [01:14<06:59,  3.91it/s]
 27%|██▋       | 610/2248 [01:15<06:38,  4.11it/s]
 27%|██▋       | 612/2248 [01:15<04:42,  5.79it/s]
 27%|██▋       | 614/2248 [01:15<03:34,  7.62it/s]
 28%|██▊       | 620/2248 [01:15<01:43, 15.75it/s]
 28%|██▊       | 626/2248 [01:15<01:13, 21.93it/s]
 28%|██▊       | 631/2248 [01:15<01:04, 25.19it/s]
 28%|██▊       | 636/2248 [01:15<00:53, 29.89it/s]
 29%|██▊       | 643/2248 [01:15<00:41, 38.53it/s]
 29%|██▉       | 648/2248 [01:15<00:40, 39.91it/s]
 29%|██▉       | 653/2248 [01:17<02:13, 11.95it/s]
 29%|██▉       | 657/2248 [01:17<01:52, 14.10it/s]
 29%|██▉       | 661/2248 [01:18<03:55,  6.74it/s]
 30%|██▉       | 664/2248 [01:19<04:15,  6.19it/s]
 30%|██▉       | 666/2248 [01:20<05:20,  4.94it/s]
 30%|██▉       | 668/2248 [01:20<04:32,  5.80it/s]
 30%|██▉       | 670/2248 [01:20<04:17,  6.13it/s]
 30%|██▉       | 673/2248 [01:20<03:18,  7.94it/s]
 30%|███       | 677/2248 [01:20<02:40,  9.77it/s]
 30%|███       | 679/2248 [01:21<02:25, 10.82it/s]
 30%|███       | 681/2248 [01:21<02:54,  8.98it/s]
 30%|███       | 683/2248 [01:21<03:41,  7.07it/s]
 30%|███       | 685/2248 [01:22<04:10,  6.23it/s]
 31%|███       | 686/2248 [01:22<04:24,  5.90it/s]
 31%|███       | 687/2248 [01:22<05:32,  4.70it/s]
 31%|███       | 688/2248 [01:23<06:13,  4.17it/s]
 31%|███       | 690/2248 [01:23<04:23,  5.90it/s]
 31%|███       | 691/2248 [01:23<04:58,  5.21it/s]
 31%|███       | 692/2248 [01:23<05:43,  4.53it/s]
 31%|███       | 694/2248 [01:24<05:07,  5.05it/s]
 31%|███       | 695/2248 [01:24<05:07,  5.05it/s]
 31%|███       | 698/2248 [01:24<04:12,  6.15it/s]
 31%|███       | 699/2248 [01:25<05:21,  4.82it/s]
 31%|███       | 701/2248 [01:25<03:59,  6.46it/s]
 31%|███       | 702/2248 [01:25<04:52,  5.28it/s]
 31%|███▏      | 704/2248 [01:26<05:37,  4.57it/s]
 31%|███▏      | 706/2248 [01:26<05:58,  4.31it/s]
 32%|███▏      | 709/2248 [01:26<03:55,  6.54it/s]
 32%|███▏      | 712/2248 [01:27<03:32,  7.24it/s]
 32%|███▏      | 714/2248 [01:27<03:50,  6.64it/s]
 32%|███▏      | 715/2248 [01:27<04:25,  5.78it/s]
 32%|███▏      | 719/2248 [01:28<04:01,  6.34it/s]
 32%|███▏      | 721/2248 [01:28<04:45,  5.35it/s]
 32%|███▏      | 723/2248 [01:29<03:50,  6.61it/s]
 32%|███▏      | 724/2248 [01:29<05:04,  5.01it/s]
 32%|███▏      | 725/2248 [01:29<04:36,  5.51it/s]
 32%|███▏      | 727/2248 [01:30<04:54,  5.17it/s]
 32%|███▏      | 728/2248 [01:30<05:31,  4.58it/s]
 32%|███▏      | 730/2248 [01:30<04:05,  6.17it/s]
 33%|███▎      | 731/2248 [01:30<04:07,  6.13it/s]
 33%|███▎      | 732/2248 [01:30<04:47,  5.26it/s]
 33%|███▎      | 733/2248 [01:31<04:33,  5.55it/s]
 33%|███▎      | 734/2248 [01:31<04:58,  5.07it/s]
 33%|███▎      | 735/2248 [01:31<05:29,  4.59it/s]
 33%|███▎      | 736/2248 [01:31<05:46,  4.36it/s]
 33%|███▎      | 737/2248 [01:32<05:47,  4.34it/s]
 33%|███▎      | 738/2248 [01:32<05:52,  4.29it/s]
 33%|███▎      | 740/2248 [01:32<03:50,  6.53it/s]
 33%|███▎      | 742/2248 [01:32<04:07,  6.08it/s]
 33%|███▎      | 743/2248 [01:33<06:03,  4.14it/s]
 33%|███▎      | 744/2248 [01:33<07:13,  3.47it/s]
 33%|███▎      | 746/2248 [01:33<04:50,  5.17it/s]
 33%|███▎      | 749/2248 [01:34<04:29,  5.55it/s]
 33%|███▎      | 751/2248 [01:34<04:46,  5.23it/s]
 33%|███▎      | 752/2248 [01:35<05:07,  4.86it/s]
 34%|███▎      | 754/2248 [01:35<03:53,  6.40it/s]
 34%|███▎      | 758/2248 [01:35<02:18, 10.72it/s]
 34%|███▍      | 761/2248 [01:35<02:31,  9.82it/s]
 34%|███▍      | 763/2248 [01:35<02:18, 10.75it/s]
 34%|███▍      | 767/2248 [01:36<02:50,  8.69it/s]
 34%|███▍      | 769/2248 [01:36<02:33,  9.62it/s]
 34%|███▍      | 772/2248 [01:36<02:45,  8.89it/s]
 34%|███▍      | 774/2248 [01:37<04:28,  5.48it/s]
 34%|███▍      | 775/2248 [01:37<04:49,  5.09it/s]
 35%|███▍      | 776/2248 [01:38<05:33,  4.41it/s]
 35%|███▍      | 778/2248 [01:38<04:51,  5.05it/s]
 35%|███▍      | 780/2248 [01:38<03:44,  6.53it/s]
 35%|███▍      | 782/2248 [01:39<03:50,  6.35it/s]
 35%|███▍      | 783/2248 [01:39<03:54,  6.24it/s]
 35%|███▍      | 784/2248 [01:39<04:56,  4.94it/s]
 35%|███▍      | 786/2248 [01:39<03:44,  6.50it/s]
 35%|███▌      | 788/2248 [01:39<03:01,  8.06it/s]
 35%|███▌      | 790/2248 [01:40<03:09,  7.71it/s]
 35%|███▌      | 791/2248 [01:40<04:09,  5.83it/s]
 35%|███▌      | 792/2248 [01:40<04:33,  5.32it/s]
 35%|███▌      | 795/2248 [01:40<02:58,  8.16it/s]
 35%|███▌      | 797/2248 [01:41<03:11,  7.56it/s]
 36%|███▌      | 799/2248 [01:41<02:36,  9.28it/s]
 36%|███▌      | 801/2248 [01:41<03:12,  7.51it/s]
 36%|███▌      | 805/2248 [01:41<01:59, 12.07it/s]
 36%|███▌      | 807/2248 [01:42<02:18, 10.41it/s]
 36%|███▌      | 810/2248 [01:42<02:57,  8.09it/s]
 36%|███▌      | 812/2248 [01:43<03:44,  6.41it/s]
 36%|███▌      | 813/2248 [01:43<04:29,  5.33it/s]
 36%|███▌      | 814/2248 [01:43<05:03,  4.72it/s]
 36%|███▋      | 815/2248 [01:44<06:26,  3.70it/s]
 36%|███▋      | 816/2248 [01:44<06:58,  3.42it/s]
 36%|███▋      | 818/2248 [01:44<04:43,  5.04it/s]
 37%|███▋      | 824/2248 [01:44<02:02, 11.66it/s]
 37%|███▋      | 831/2248 [01:45<01:11, 19.69it/s]
 37%|███▋      | 839/2248 [01:45<00:48, 29.08it/s]
 38%|███▊      | 844/2248 [01:45<00:44, 31.45it/s]
 38%|███▊      | 852/2248 [01:45<00:33, 41.32it/s]
 38%|███▊      | 858/2248 [01:45<00:30, 45.34it/s]
 38%|███▊      | 865/2248 [01:45<00:27, 50.08it/s]
 39%|███▊      | 871/2248 [01:47<02:03, 11.15it/s]
 39%|███▉      | 876/2248 [01:47<02:16, 10.04it/s]
 39%|███▉      | 880/2248 [01:48<02:48,  8.13it/s]
 39%|███▉      | 883/2248 [01:49<03:01,  7.53it/s]
 39%|███▉      | 885/2248 [01:49<03:11,  7.10it/s]
 40%|███▉      | 888/2248 [01:49<03:03,  7.42it/s]
 40%|███▉      | 890/2248 [01:50<03:16,  6.92it/s]
 40%|███▉      | 893/2248 [01:50<02:34,  8.76it/s]
 40%|███▉      | 895/2248 [01:50<03:11,  7.06it/s]
 40%|███▉      | 897/2248 [01:51<03:49,  5.88it/s]
 40%|███▉      | 899/2248 [01:51<04:19,  5.21it/s]
 40%|████      | 902/2248 [01:52<03:52,  5.78it/s]
 40%|████      | 903/2248 [01:52<04:16,  5.24it/s]
 40%|████      | 905/2248 [01:52<03:24,  6.57it/s]
 40%|████      | 906/2248 [01:52<04:00,  5.57it/s]
 40%|████      | 907/2248 [01:53<05:14,  4.27it/s]
 40%|████      | 908/2248 [01:53<05:26,  4.10it/s]
 40%|████      | 909/2248 [01:53<05:00,  4.46it/s]
 40%|████      | 910/2248 [01:54<05:26,  4.09it/s]
 41%|████      | 911/2248 [01:54<05:49,  3.82it/s]
 41%|████      | 912/2248 [01:54<05:55,  3.75it/s]
 41%|████      | 913/2248 [01:55<07:01,  3.17it/s]
 41%|████      | 915/2248 [01:55<04:31,  4.91it/s]
 41%|████      | 916/2248 [01:55<04:48,  4.62it/s]
 41%|████      | 917/2248 [01:56<06:06,  3.63it/s]
 41%|████      | 919/2248 [01:56<05:22,  4.12it/s]
 41%|████      | 920/2248 [01:56<05:36,  3.95it/s]
 41%|████      | 922/2248 [01:56<03:56,  5.61it/s]
 41%|████      | 924/2248 [01:57<04:27,  4.95it/s]
 41%|████      | 926/2248 [01:57<03:20,  6.58it/s]
 41%|████▏     | 928/2248 [01:57<03:25,  6.42it/s]
 41%|████▏     | 929/2248 [01:58<05:04,  4.34it/s]
 41%|████▏     | 931/2248 [01:58<05:12,  4.22it/s]
 42%|████▏     | 933/2248 [01:58<03:52,  5.66it/s]
 42%|████▏     | 934/2248 [01:59<04:30,  4.87it/s]
 42%|████▏     | 936/2248 [01:59<03:17,  6.65it/s]
 42%|████▏     | 938/2248 [01:59<03:27,  6.32it/s]
 42%|████▏     | 940/2248 [02:00<03:41,  5.92it/s]
 42%|████▏     | 942/2248 [02:00<02:56,  7.38it/s]
 42%|████▏     | 944/2248 [02:00<03:11,  6.80it/s]
 42%|████▏     | 946/2248 [02:01<04:08,  5.24it/s]
 42%|████▏     | 948/2248 [02:01<03:14,  6.69it/s]
 42%|████▏     | 950/2248 [02:01<03:56,  5.48it/s]
 42%|████▏     | 952/2248 [02:02<04:19,  5.00it/s]
 42%|████▏     | 953/2248 [02:02<04:33,  4.73it/s]
 42%|████▏     | 955/2248 [02:02<03:26,  6.28it/s]
 43%|████▎     | 956/2248 [02:02<03:21,  6.40it/s]
 43%|████▎     | 957/2248 [02:03<04:42,  4.57it/s]
 43%|████▎     | 958/2248 [02:03<04:40,  4.60it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 320.11it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 6], [np.int64(2), False, 9], [np.int64(4), False, 12], [np.int64(5), False, 4], [np.int64(7), False, 5], [np.int64(8), False, 4], [np.int64(9), False, 13], [np.int64(10), False, 5], [np.int64(11), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4246, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8097, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [17:37<1:07:55, 83.17s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [17:37<46:36, 58.26s/it]

tensor(12.4252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4395, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4318, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0398, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0697, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [17:38<15:02, 20.06s/it]

tensor(12.4392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0528, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9429, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4390, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0611, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6996, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [17:38<07:05,  9.89s/it]

tensor(12.4328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0661, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0679, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6928, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [17:38<03:21,  4.91s/it]

tensor(12.4392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0687, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9259, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4499, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0690, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0783, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [17:39<01:36,  2.46s/it]

tensor(12.4592, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0691, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1389, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0688, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6691, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [17:39<00:46,  1.27s/it]

tensor(12.4577, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0689, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4088, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4542, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0702, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6932, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [17:39<00:23,  1.47it/s]

tensor(12.4590, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0731, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8385, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4662, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0755, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8333, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [17:39<00:13,  2.53it/s]

tensor(12.4720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0759, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8468, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4756, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0751, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4209, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [17:39<00:07,  3.93it/s]

tensor(12.4775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0745, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6947, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4849, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0779, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1483, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [17:40<00:05,  5.45it/s]

tensor(12.4980, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0828, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3589, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5085, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0852, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7091, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [17:40<00:04,  6.69it/s]

tensor(12.5078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0869, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0572, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4922, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0910, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1352, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [17:40<00:03,  7.48it/s]

tensor(12.4726, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0945, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4655, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0960, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8106, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [17:40<00:03,  7.63it/s]

tensor(12.4712, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0957, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0933, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9384, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [17:41<00:02,  8.12it/s]

tensor(12.4977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0882, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8425, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0854, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2789, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [17:41<00:02,  8.28it/s]

tensor(12.4905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0921, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9557, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1044, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5517, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [17:41<00:02,  8.35it/s]

tensor(12.5458, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1130, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6268, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1174, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8675, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [17:41<00:01,  8.48it/s]

tensor(12.5489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1190, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2062, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1180, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3013, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [17:42<00:01,  8.56it/s]

tensor(12.5347, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1154, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1849, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5488, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1122, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1665, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [17:42<00:01,  8.59it/s]

tensor(12.5894, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1079, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2498, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6326, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1038, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2940, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [17:42<00:01,  8.52it/s]

tensor(12.6280, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0996, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3264, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0950, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4047, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [17:42<00:00,  8.53it/s]

tensor(12.5353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0905, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4557, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5184, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0862, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5327, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [17:43<00:00,  8.44it/s]

tensor(12.5205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0819, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6161, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5227, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0779, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6463, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [17:43<00:00,  8.26it/s]

tensor(12.5177, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0737, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7021, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0695, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7324, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [17:43<00:00,  8.29it/s]

tensor(12.4964, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0652, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7460, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4884, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0612, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7189, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [17:43<00:00,  3.55s/it]

tensor(12.4819, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0574, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.7278, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0022134780883789062
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 6
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.435181904209
NMI         : 0.485153954200
Runtime     : 1085.86 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed6

==============================================================================================================
PRAGA RUN | S2-E18 | seed=7
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 5.936e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:32,  9.27it/s]

tensor(15.9598, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1220, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9777, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8062, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:34,  8.70it/s]

tensor(15.9525, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7177, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9201, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8357, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:30,  9.61it/s]

tensor(15.8892, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1389, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8603, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6088, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8338, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2299, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:29,  9.95it/s]

tensor(15.8131, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9871, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7938, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8668, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7768, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8566, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 12/300 [00:01<00:28, 10.24it/s]

tensor(15.7595, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9461, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7401, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1262, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7170, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3868, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▍         | 14/300 [00:01<00:27, 10.24it/s]

tensor(15.6906, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6597, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1206, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6255, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5800, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 18/300 [00:01<00:27, 10.30it/s]

tensor(15.5885, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0934, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5500, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6544, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5109, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2597, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 20/300 [00:01<00:26, 10.38it/s]

tensor(15.4721, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9043, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4334, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5839, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3942, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2956, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 24/300 [00:02<00:26, 10.42it/s]

tensor(15.3535, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0368, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3107, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8031, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2660, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5938, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▊         | 26/300 [00:02<00:26, 10.44it/s]

tensor(15.2200, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4056, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1737, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2362, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1268, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0839, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 30/300 [00:02<00:25, 10.40it/s]

tensor(15.0796, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9480, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0309, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7159, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 32/300 [00:03<00:25, 10.33it/s]

tensor(14.9285, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6184, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8744, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5308, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4525, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 36/300 [00:03<00:25, 10.36it/s]

tensor(14.7609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3833, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7014, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2673, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 38/300 [00:03<00:25, 10.31it/s]

tensor(14.5795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2194, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5194, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1770, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1416, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 42/300 [00:04<00:24, 10.33it/s]

tensor(14.4061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1110, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3541, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0860, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0662, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:24, 10.38it/s]

tensor(14.2660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0517, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2310, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0418, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1992, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:24, 10.38it/s]

tensor(14.1682, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1373, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 50/300 [00:04<00:24, 10.35it/s]

tensor(14.0735, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0084, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 54/300 [00:05<00:23, 10.34it/s]

tensor(13.9800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0333, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9317, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0330, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:23, 10.37it/s]

tensor(13.9097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8657, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 60/300 [00:05<00:23, 10.36it/s]

tensor(13.8432, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8202, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7968, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:23, 10.31it/s]

tensor(13.7730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7489, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 66/300 [00:06<00:22, 10.40it/s]

tensor(13.7015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6792, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:22, 10.44it/s]

tensor(13.6366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6166, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 72/300 [00:06<00:21, 10.39it/s]

tensor(13.5786, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:21, 10.33it/s]

tensor(13.5238, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4900, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▌       | 78/300 [00:07<00:21, 10.32it/s]

tensor(13.4737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4424, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:07<00:21, 10.31it/s]

tensor(13.4271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3972, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:20, 10.32it/s]

tensor(13.3825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3681, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3537, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▊       | 86/300 [00:08<00:20, 10.33it/s]

tensor(13.3400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:08<00:20, 10.34it/s]

tensor(13.3008, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2885, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:08<00:20, 10.28it/s]

tensor(13.2653, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2543, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2435, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:19, 10.32it/s]

tensor(13.2332, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2233, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2137, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 98/300 [00:09<00:19, 10.30it/s]

tensor(13.2045, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1956, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1869, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:09<00:19, 10.33it/s]

updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([173, 372, 100,  79, 200, 129,  55, 133, 263, 152,  73, 103, 226, 190])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 5/2248 [00:00<00:52, 42.58it/s]
  0%|          | 11/2248 [00:00<00:45, 49.06it/s]
  1%|          | 18/2248 [00:00<00:38, 57.56it/s]
  1%|          | 24/2248 [00:00<00:39, 56.48it/s]
  1%|▏         | 31/2248 [00:00<00:36, 60.17it/s]
  2%|▏         | 38/2248 [00:00<00:59, 37.07it/s]
  2%|▏         | 43/2248 [00:01<01:22, 26.78it/s]
  2%|▏         | 47/2248 [00:01<01:23, 26.30it/s]
  2%|▏         | 52/2248 [00:01<01:33, 23.38it/s]
  2%|▏         | 55/2248 [00:01<02:00, 18.15it/s]
  3%|▎         | 58/2248 [00:02<01:53, 19.27it/s]
  3%|▎         | 62/2248 [00:02<02:02, 17.88it/s]
  3%|▎         | 65/2248 [00:02<02:21, 15.39it/s]
  3%|▎         | 68/2248 [00:02<02:09, 16.88it/s]
  3%|▎         | 75/2248 [00:03<02:32, 14.24it/s]
  3%|▎         | 78/2248 [00:03<02:25, 14.94it/s]
  4%|▎         | 80/2248 [00:03<02:31, 14.29it/s]
  4%|▎         | 82/2248 [00:03<02:50, 12.70it/s]
  4%|▎         | 84/2248 [00:04<02:50, 12.70it/s]
  4%|▍         | 86/2248 [00:04<04:32,  7.94it/s]
  4%|▍         | 88/2248 [00:04<04:52,  7.38it/s]
  4%|▍         | 89/2248 [00:05<05:22,  6.70it/s]
  4%|▍         | 92/2248 [00:05<03:46,  9.51it/s]
  4%|▍         | 94/2248 [00:05<03:44,  9.59it/s]
  4%|▍         | 96/2248 [00:05<04:04,  8.79it/s]
  4%|▍         | 98/2248 [00:06<05:37,  6.36it/s]
  4%|▍         | 100/2248 [00:06<06:53,  5.20it/s]
  4%|▍         | 101/2248 [00:07<06:53,  5.19it/s]
  5%|▍         | 102/2248 [00:07<07:06,  5.03it/s]
  5%|▍         | 103/2248 [00:07<06:21,  5.63it/s]
  5%|▍         | 104/2248 [00:07<06:58,  5.12it/s]
  5%|▍         | 106/2248 [00:07<04:59,  7.14it/s]
  5%|▍         | 107/2248 [00:07<05:33,  6.42it/s]
  5%|▍         | 108/2248 [00:08<05:10,  6.88it/s]
  5%|▍         | 109/2248 [00:08<05:53,  6.04it/s]
  5%|▍         | 110/2248 [00:08<06:13,  5.73it/s]
  5%|▍         | 111/2248 [00:08<09:12,  3.87it/s]
  5%|▍         | 112/2248 [00:09<08:45,  4.06it/s]
  5%|▌         | 113/2248 [00:09<08:16,  4.30it/s]
  5%|▌         | 114/2248 [00:09<07:33,  4.70it/s]
  5%|▌         | 116/2248 [00:09<05:25,  6.56it/s]
  5%|▌         | 117/2248 [00:09<06:51,  5.18it/s]
  5%|▌         | 119/2248 [00:10<07:00,  5.06it/s]
  5%|▌         | 120/2248 [00:10<07:46,  4.56it/s]
 33%|███▎      | 100/300 [00:25<00:19, 10.33it/s]]
  5%|▌         | 123/2248 [00:11<07:15,  4.88it/s]
  6%|▌         | 125/2248 [00:11<06:03,  5.85it/s]
  6%|▌         | 126/2248 [00:11<07:07,  4.97it/s]
  6%|▌         | 127/2248 [00:12<07:24,  4.77it/s]
  6%|▌         | 130/2248 [00:12<04:28,  7.87it/s]
  6%|▌         | 135/2248 [00:12<02:30, 14.01it/s]
  6%|▌         | 137/2248 [00:12<02:20, 15.00it/s]
  6%|▌         | 139/2248 [00:12<02:12, 15.97it/s]
  6%|▋         | 141/2248 [00:12<03:20, 10.52it/s]
  6%|▋         | 143/2248 [00:13<04:04,  8.62it/s]
  6%|▋         | 145/2248 [00:13<03:49,  9.17it/s]
  7%|▋         | 148/2248 [00:13<03:26, 10.15it/s]
  7%|▋         | 150/2248 [00:14<05:05,  6.87it/s]
  7%|▋         | 152/2248 [00:14<06:01,  5.79it/s]
  7%|▋         | 154/2248 [00:14<04:57,  7.03it/s]
  7%|▋         | 157/2248 [00:15<05:11,  6.71it/s]
  7%|▋         | 158/2248 [00:15<06:52,  5.06it/s]
  7%|▋         | 160/2248 [00:16<07:32,  4.61it/s]
  7%|▋         | 163/2248 [00:16<05:08,  6.76it/s]
  7%|▋         | 166/2248 [00:16<05:22,  6.46it/s]
  8%|▊         | 169/2248 [00:17<05:38,  6.15it/s]
  8%|▊         | 170/2248 [00:17<05:51,  5.92it/s]
  8%|▊         | 173/2248 [00:17<04:10,  8.29it/s]
  8%|▊         | 175/2248 [00:18<04:05,  8.44it/s]
  8%|▊         | 178/2248 [00:18<03:05, 11.14it/s]
  8%|▊         | 183/2248 [00:18<02:00, 17.15it/s]
  8%|▊         | 186/2248 [00:19<04:07,  8.32it/s]
  8%|▊         | 188/2248 [00:19<04:48,  7.14it/s]
  8%|▊         | 190/2248 [00:19<04:09,  8.24it/s]
  9%|▊         | 192/2248 [00:19<03:44,  9.17it/s]
  9%|▊         | 194/2248 [00:19<03:20, 10.26it/s]
  9%|▉         | 197/2248 [00:20<03:21, 10.20it/s]
  9%|▉         | 199/2248 [00:20<03:48,  8.97it/s]
  9%|▉         | 201/2248 [00:20<03:59,  8.55it/s]
  9%|▉         | 203/2248 [00:21<06:19,  5.39it/s]
  9%|▉         | 204/2248 [00:21<05:53,  5.78it/s]
  9%|▉         | 205/2248 [00:22<07:55,  4.29it/s]
  9%|▉         | 207/2248 [00:22<07:40,  4.44it/s]
  9%|▉         | 208/2248 [00:22<07:00,  4.85it/s]
  9%|▉         | 209/2248 [00:23<08:53,  3.82it/s]
  9%|▉         | 210/2248 [00:23<10:52,  3.12it/s]
  9%|▉         | 211/2248 [00:23<09:49,  3.45it/s]
  9%|▉         | 212/2248 [00:24<09:35,  3.54it/s]
  9%|▉         | 213/2248 [00:24<08:51,  3.83it/s]
 10%|▉         | 215/2248 [00:24<05:45,  5.88it/s]
 10%|▉         | 221/2248 [00:24<02:21, 14.36it/s]
 10%|█         | 228/2248 [00:24<01:23, 24.25it/s]
 10%|█         | 235/2248 [00:24<01:07, 29.96it/s]
 11%|█         | 239/2248 [00:24<01:08, 29.18it/s]
 11%|█         | 245/2248 [00:25<00:59, 33.40it/s]
 11%|█         | 249/2248 [00:25<01:12, 27.55it/s]
 11%|█▏        | 253/2248 [00:25<01:17, 25.90it/s]
 11%|█▏        | 257/2248 [00:25<01:12, 27.28it/s]
 12%|█▏        | 263/2248 [00:26<01:51, 17.79it/s]
 12%|█▏        | 266/2248 [00:26<02:38, 12.51it/s]
 12%|█▏        | 269/2248 [00:26<02:27, 13.43it/s]
 12%|█▏        | 271/2248 [00:27<02:44, 12.01it/s]
 12%|█▏        | 273/2248 [00:27<02:31, 13.02it/s]
 12%|█▏        | 277/2248 [00:27<02:43, 12.06it/s]
 12%|█▏        | 279/2248 [00:27<02:33, 12.81it/s]
 12%|█▎        | 281/2248 [00:27<03:12, 10.22it/s]
 13%|█▎        | 283/2248 [00:28<03:39,  8.93it/s]
 13%|█▎        | 287/2248 [00:28<03:04, 10.62it/s]
 13%|█▎        | 289/2248 [00:28<02:50, 11.49it/s]
 13%|█▎        | 291/2248 [00:29<05:05,  6.40it/s]
 13%|█▎        | 293/2248 [00:29<04:17,  7.60it/s]
 13%|█▎        | 295/2248 [00:29<03:39,  8.90it/s]
 13%|█▎        | 297/2248 [00:29<03:31,  9.22it/s]
 13%|█▎        | 299/2248 [00:30<03:51,  8.43it/s]
 13%|█▎        | 301/2248 [00:30<03:31,  9.22it/s]
 13%|█▎        | 303/2248 [00:30<05:49,  5.57it/s]
 14%|█▎        | 305/2248 [00:31<04:41,  6.91it/s]
 14%|█▎        | 307/2248 [00:31<06:28,  4.99it/s]
 14%|█▎        | 308/2248 [00:32<07:11,  4.50it/s]
 14%|█▎        | 309/2248 [00:32<07:18,  4.42it/s]
 14%|█▍        | 310/2248 [00:32<06:31,  4.95it/s]
 14%|█▍        | 312/2248 [00:32<04:38,  6.96it/s]
 14%|█▍        | 314/2248 [00:33<05:30,  5.86it/s]
 14%|█▍        | 315/2248 [00:33<06:17,  5.13it/s]
 14%|█▍        | 317/2248 [00:33<04:51,  6.61it/s]
 14%|█▍        | 318/2248 [00:33<07:10,  4.48it/s]
 14%|█▍        | 319/2248 [00:34<06:16,  5.12it/s]
 14%|█▍        | 322/2248 [00:34<05:42,  5.63it/s]
 14%|█▍        | 323/2248 [00:35<07:37,  4.21it/s]
 14%|█▍        | 325/2248 [00:35<07:46,  4.13it/s]
 15%|█▍        | 327/2248 [00:35<05:48,  5.51it/s]
 15%|█▍        | 329/2248 [00:35<04:59,  6.41it/s]
 15%|█▍        | 331/2248 [00:36<04:41,  6.81it/s]
 15%|█▍        | 332/2248 [00:36<06:36,  4.83it/s]
 15%|█▍        | 335/2248 [00:36<04:16,  7.45it/s]
 15%|█▍        | 337/2248 [00:36<03:53,  8.17it/s]
 15%|█▌        | 339/2248 [00:37<05:11,  6.13it/s]
 15%|█▌        | 342/2248 [00:37<03:43,  8.54it/s]
 15%|█▌        | 344/2248 [00:38<06:43,  4.72it/s]
 15%|█▌        | 345/2248 [00:38<08:08,  3.89it/s]
 15%|█▌        | 347/2248 [00:39<08:05,  3.92it/s]
 15%|█▌        | 348/2248 [00:39<09:14,  3.43it/s]
 16%|█▌        | 349/2248 [00:40<10:44,  2.95it/s]
 16%|█▌        | 352/2248 [00:40<06:16,  5.03it/s]
 16%|█▌        | 354/2248 [00:41<06:52,  4.59it/s]
 16%|█▌        | 356/2248 [00:41<07:23,  4.27it/s]
 16%|█▌        | 358/2248 [00:41<05:43,  5.51it/s]
 16%|█▌        | 364/2248 [00:42<04:08,  7.57it/s]
 16%|█▋        | 366/2248 [00:42<04:56,  6.35it/s]
 16%|█▋        | 367/2248 [00:43<05:36,  5.58it/s]
 16%|█▋        | 370/2248 [00:43<03:58,  7.86it/s]
 17%|█▋        | 372/2248 [00:43<05:04,  6.16it/s]
 17%|█▋        | 375/2248 [00:43<03:41,  8.44it/s]
 17%|█▋        | 377/2248 [00:44<04:39,  6.70it/s]
 17%|█▋        | 379/2248 [00:44<03:55,  7.95it/s]
 17%|█▋        | 384/2248 [00:45<03:36,  8.60it/s]
 17%|█▋        | 386/2248 [00:45<04:41,  6.60it/s]
 17%|█▋        | 388/2248 [00:46<05:32,  5.59it/s]
 17%|█▋        | 389/2248 [00:46<06:45,  4.59it/s]
 17%|█▋        | 391/2248 [00:46<05:15,  5.88it/s]
 17%|█▋        | 392/2248 [00:47<06:48,  4.54it/s]
 18%|█▊        | 395/2248 [00:47<06:22,  4.85it/s]
 18%|█▊        | 397/2248 [00:47<05:01,  6.13it/s]
 18%|█▊        | 400/2248 [00:48<04:02,  7.62it/s]
 18%|█▊        | 403/2248 [00:48<03:51,  7.96it/s]
 18%|█▊        | 405/2248 [00:48<04:00,  7.67it/s]
 18%|█▊        | 407/2248 [00:48<04:12,  7.30it/s]
 18%|█▊        | 408/2248 [00:49<04:10,  7.33it/s]
 18%|█▊        | 410/2248 [00:49<03:33,  8.62it/s]
 18%|█▊        | 412/2248 [00:49<03:56,  7.76it/s]
 18%|█▊        | 414/2248 [00:49<03:48,  8.02it/s]
 18%|█▊        | 415/2248 [00:49<03:57,  7.70it/s]
 19%|█▊        | 417/2248 [00:50<03:44,  8.15it/s]
 19%|█▊        | 419/2248 [00:50<03:11,  9.57it/s]
 19%|█▊        | 421/2248 [00:50<02:41, 11.28it/s]
 19%|█▉        | 423/2248 [00:50<03:03,  9.94it/s]
 19%|█▉        | 425/2248 [00:50<03:07,  9.72it/s]
 19%|█▉        | 427/2248 [00:51<02:39, 11.39it/s]
 19%|█▉        | 429/2248 [00:51<02:22, 12.76it/s]
 19%|█▉        | 435/2248 [00:51<01:20, 22.57it/s]
 19%|█▉        | 438/2248 [00:51<02:35, 11.61it/s]
 20%|█▉        | 441/2248 [00:52<03:26,  8.77it/s]
 20%|█▉        | 443/2248 [00:52<03:11,  9.42it/s]
 20%|█▉        | 445/2248 [00:52<03:11,  9.43it/s]
 20%|█▉        | 447/2248 [00:52<02:58, 10.07it/s]
 20%|█▉        | 449/2248 [00:53<02:42, 11.05it/s]
 20%|██        | 453/2248 [00:53<02:33, 11.69it/s]
 20%|██        | 455/2248 [00:53<03:57,  7.53it/s]
 20%|██        | 457/2248 [00:54<04:32,  6.58it/s]
 20%|██        | 459/2248 [00:54<03:44,  7.98it/s]
 21%|██        | 461/2248 [00:54<04:36,  6.47it/s]
 21%|██        | 462/2248 [00:55<04:44,  6.28it/s]
 21%|██        | 464/2248 [00:55<05:49,  5.10it/s]
 21%|██        | 467/2248 [00:55<04:00,  7.40it/s]
 21%|██        | 469/2248 [00:55<03:46,  7.85it/s]
 21%|██        | 472/2248 [00:56<04:26,  6.66it/s]
 21%|██        | 473/2248 [00:56<04:43,  6.25it/s]
 21%|██        | 475/2248 [00:57<05:49,  5.07it/s]
 21%|██        | 476/2248 [00:57<07:14,  4.08it/s]
 21%|██▏       | 478/2248 [00:57<05:18,  5.55it/s]
 21%|██▏       | 479/2248 [00:58<07:01,  4.20it/s]
 21%|██▏       | 480/2248 [00:58<08:26,  3.49it/s]
 21%|██▏       | 481/2248 [00:59<09:10,  3.21it/s]
 21%|██▏       | 482/2248 [00:59<07:38,  3.85it/s]
 21%|██▏       | 483/2248 [00:59<06:28,  4.54it/s]
 22%|██▏       | 485/2248 [00:59<04:22,  6.72it/s]
 22%|██▏       | 487/2248 [01:00<06:14,  4.70it/s]
 22%|██▏       | 490/2248 [01:00<03:54,  7.49it/s]
 22%|██▏       | 492/2248 [01:00<03:27,  8.46it/s]
 22%|██▏       | 496/2248 [01:00<02:31, 11.55it/s]
 22%|██▏       | 498/2248 [01:00<02:50, 10.26it/s]
 22%|██▏       | 500/2248 [01:01<05:05,  5.72it/s]
 22%|██▏       | 502/2248 [01:01<04:17,  6.79it/s]
 22%|██▏       | 505/2248 [01:01<03:11,  9.10it/s]
 23%|██▎       | 507/2248 [01:02<02:46, 10.43it/s]
 23%|██▎       | 509/2248 [01:02<03:52,  7.47it/s]
 23%|██▎       | 511/2248 [01:03<04:34,  6.32it/s]
 23%|██▎       | 514/2248 [01:03<03:18,  8.74it/s]
 23%|██▎       | 516/2248 [01:03<04:27,  6.48it/s]
 23%|██▎       | 518/2248 [01:04<05:09,  5.59it/s]
 23%|██▎       | 520/2248 [01:04<04:43,  6.11it/s]
 23%|██▎       | 522/2248 [01:04<03:47,  7.60it/s]
 23%|██▎       | 528/2248 [01:04<01:57, 14.61it/s]
 24%|██▎       | 533/2248 [01:04<01:26, 19.88it/s]
 24%|██▍       | 537/2248 [01:04<01:17, 22.16it/s]
 24%|██▍       | 544/2248 [01:05<01:11, 23.74it/s]
 24%|██▍       | 547/2248 [01:05<01:18, 21.74it/s]
 25%|██▍       | 551/2248 [01:05<01:07, 24.98it/s]
 25%|██▍       | 554/2248 [01:05<01:07, 24.98it/s]
 25%|██▍       | 558/2248 [01:05<01:01, 27.47it/s]
 25%|██▌       | 564/2248 [01:05<01:04, 26.01it/s]
 25%|██▌       | 567/2248 [01:06<01:07, 24.79it/s]
 25%|██▌       | 571/2248 [01:06<01:22, 20.31it/s]
 26%|██▌       | 574/2248 [01:07<02:48,  9.92it/s]
 26%|██▌       | 576/2248 [01:07<02:38, 10.54it/s]
 26%|██▌       | 578/2248 [01:07<03:03,  9.09it/s]
 26%|██▌       | 580/2248 [01:07<02:42, 10.29it/s]
 26%|██▌       | 582/2248 [01:08<04:39,  5.95it/s]
 26%|██▌       | 584/2248 [01:08<05:00,  5.53it/s]
 26%|██▌       | 586/2248 [01:09<05:33,  4.98it/s]
 26%|██▌       | 588/2248 [01:09<05:26,  5.08it/s]
 26%|██▋       | 591/2248 [01:09<03:49,  7.22it/s]
 26%|██▋       | 593/2248 [01:10<04:44,  5.81it/s]
 27%|██▋       | 597/2248 [01:10<03:02,  9.04it/s]
 27%|██▋       | 600/2248 [01:11<03:34,  7.68it/s]
 27%|██▋       | 602/2248 [01:11<03:06,  8.84it/s]
 27%|██▋       | 604/2248 [01:12<05:33,  4.93it/s]
 27%|██▋       | 606/2248 [01:13<07:31,  3.64it/s]
 27%|██▋       | 608/2248 [01:13<07:31,  3.63it/s]
 27%|██▋       | 609/2248 [01:14<08:28,  3.22it/s]
 27%|██▋       | 611/2248 [01:14<06:17,  4.34it/s]
 27%|██▋       | 612/2248 [01:14<06:15,  4.36it/s]
 27%|██▋       | 614/2248 [01:14<04:37,  5.90it/s]
 27%|██▋       | 617/2248 [01:14<03:35,  7.55it/s]
 28%|██▊       | 619/2248 [01:15<03:40,  7.39it/s]
 28%|██▊       | 621/2248 [01:15<03:35,  7.56it/s]
 28%|██▊       | 623/2248 [01:15<02:57,  9.16it/s]
 28%|██▊       | 626/2248 [01:15<02:33, 10.59it/s]
 28%|██▊       | 628/2248 [01:15<02:49,  9.55it/s]
 28%|██▊       | 631/2248 [01:16<02:40, 10.08it/s]
 28%|██▊       | 634/2248 [01:16<02:05, 12.91it/s]
 28%|██▊       | 636/2248 [01:16<02:15, 11.91it/s]
 28%|██▊       | 638/2248 [01:16<03:09,  8.49it/s]
 29%|██▊       | 641/2248 [01:17<02:54,  9.22it/s]
 29%|██▊       | 643/2248 [01:17<02:31, 10.59it/s]
 29%|██▊       | 645/2248 [01:17<02:17, 11.62it/s]
 29%|██▉       | 649/2248 [01:17<01:39, 16.08it/s]
 29%|██▉       | 651/2248 [01:18<03:09,  8.44it/s]
 29%|██▉       | 655/2248 [01:18<02:09, 12.26it/s]
 29%|██▉       | 659/2248 [01:18<01:37, 16.29it/s]
 29%|██▉       | 662/2248 [01:18<02:27, 10.73it/s]
 30%|██▉       | 665/2248 [01:19<03:05,  8.52it/s]
 30%|██▉       | 667/2248 [01:20<04:34,  5.76it/s]
 30%|██▉       | 669/2248 [01:20<04:13,  6.22it/s]
 30%|██▉       | 671/2248 [01:20<04:19,  6.08it/s]
 30%|██▉       | 673/2248 [01:20<03:40,  7.14it/s]
 30%|███       | 675/2248 [01:21<03:05,  8.50it/s]
 30%|███       | 677/2248 [01:21<02:41,  9.70it/s]
 30%|███       | 679/2248 [01:21<03:31,  7.42it/s]
 30%|███       | 681/2248 [01:22<04:33,  5.74it/s]
 30%|███       | 682/2248 [01:22<06:03,  4.31it/s]
 30%|███       | 683/2248 [01:22<06:18,  4.14it/s]
 30%|███       | 684/2248 [01:23<07:02,  3.70it/s]
 30%|███       | 685/2248 [01:23<07:52,  3.30it/s]
 31%|███       | 686/2248 [01:23<06:49,  3.81it/s]
 31%|███       | 687/2248 [01:24<07:05,  3.67it/s]
 31%|███       | 690/2248 [01:24<03:51,  6.72it/s]
 31%|███       | 692/2248 [01:24<03:26,  7.53it/s]
 31%|███       | 695/2248 [01:25<03:50,  6.73it/s]
 31%|███       | 696/2248 [01:25<04:07,  6.28it/s]
 31%|███       | 698/2248 [01:25<03:47,  6.82it/s]
 31%|███       | 700/2248 [01:25<03:21,  7.67it/s]
 31%|███▏      | 703/2248 [01:25<02:25, 10.59it/s]
 31%|███▏      | 705/2248 [01:26<02:47,  9.21it/s]
 31%|███▏      | 708/2248 [01:26<02:14, 11.45it/s]
 32%|███▏      | 710/2248 [01:26<02:35,  9.87it/s]
 32%|███▏      | 712/2248 [01:27<03:49,  6.70it/s]
 32%|███▏      | 715/2248 [01:27<02:45,  9.26it/s]
 32%|███▏      | 717/2248 [01:27<03:39,  6.99it/s]
 32%|███▏      | 719/2248 [01:28<04:44,  5.37it/s]
 32%|███▏      | 721/2248 [01:28<03:48,  6.67it/s]
 32%|███▏      | 723/2248 [01:28<03:06,  8.19it/s]
 32%|███▏      | 725/2248 [01:28<03:02,  8.35it/s]
 32%|███▏      | 727/2248 [01:29<03:32,  7.16it/s]
 32%|███▏      | 729/2248 [01:29<03:50,  6.58it/s]
 33%|███▎      | 731/2248 [01:29<04:41,  5.39it/s]
 33%|███▎      | 732/2248 [01:30<05:53,  4.29it/s]
 33%|███▎      | 733/2248 [01:30<07:17,  3.46it/s]
 33%|███▎      | 735/2248 [01:31<06:54,  3.65it/s]
 33%|███▎      | 736/2248 [01:31<07:56,  3.17it/s]
 33%|███▎      | 737/2248 [01:32<08:57,  2.81it/s]
 33%|███▎      | 739/2248 [01:32<06:51,  3.67it/s]
 33%|███▎      | 742/2248 [01:32<04:12,  5.98it/s]
 33%|███▎      | 749/2248 [01:32<01:54, 13.13it/s]
 33%|███▎      | 752/2248 [01:33<03:35,  6.95it/s]
 34%|███▎      | 754/2248 [01:34<04:36,  5.40it/s]
 34%|███▎      | 756/2248 [01:34<03:51,  6.44it/s]
 34%|███▍      | 759/2248 [01:34<02:56,  8.43it/s]
 34%|███▍      | 761/2248 [01:35<04:11,  5.92it/s]
 34%|███▍      | 763/2248 [01:35<04:24,  5.61it/s]
 34%|███▍      | 766/2248 [01:36<03:19,  7.43it/s]
 34%|███▍      | 768/2248 [01:36<02:49,  8.74it/s]
 34%|███▍      | 772/2248 [01:36<02:26, 10.10it/s]
 34%|███▍      | 774/2248 [01:36<03:05,  7.94it/s]
 35%|███▍      | 776/2248 [01:37<02:38,  9.28it/s]
 35%|███▍      | 778/2248 [01:37<02:16, 10.74it/s]
 35%|███▍      | 780/2248 [01:37<02:21, 10.37it/s]
 35%|███▍      | 782/2248 [01:37<03:20,  7.30it/s]
 35%|███▍      | 784/2248 [01:38<04:07,  5.91it/s]
 35%|███▍      | 786/2248 [01:38<03:17,  7.42it/s]
 35%|███▌      | 788/2248 [01:38<02:50,  8.58it/s]
 35%|███▌      | 791/2248 [01:38<02:10, 11.16it/s]
 35%|███▌      | 793/2248 [01:39<03:47,  6.39it/s]
 35%|███▌      | 795/2248 [01:39<04:45,  5.08it/s]
 35%|███▌      | 797/2248 [01:40<05:08,  4.70it/s]
 36%|███▌      | 799/2248 [01:40<04:31,  5.33it/s]
 36%|███▌      | 801/2248 [01:40<03:39,  6.58it/s]
 36%|███▌      | 803/2248 [01:41<03:24,  7.07it/s]
 36%|███▌      | 805/2248 [01:41<03:13,  7.45it/s]
 36%|███▌      | 808/2248 [01:41<02:22, 10.11it/s]
 36%|███▌      | 812/2248 [01:41<02:36,  9.15it/s]
 36%|███▋      | 815/2248 [01:42<02:06, 11.30it/s]
 36%|███▋      | 817/2248 [01:42<02:12, 10.84it/s]
 37%|███▋      | 821/2248 [01:42<01:36, 14.85it/s]
 37%|███▋      | 828/2248 [01:42<00:58, 24.25it/s]
 37%|███▋      | 835/2248 [01:42<00:43, 32.78it/s]
 37%|███▋      | 841/2248 [01:42<00:37, 37.16it/s]
 38%|███▊      | 849/2248 [01:42<00:29, 46.89it/s]
 38%|███▊      | 855/2248 [01:42<00:28, 48.93it/s]
 38%|███▊      | 862/2248 [01:43<00:26, 53.10it/s]
 39%|███▊      | 868/2248 [01:43<00:56, 24.59it/s]
 39%|███▉      | 873/2248 [01:44<01:34, 14.49it/s]
 39%|███▉      | 878/2248 [01:44<01:17, 17.62it/s]
 39%|███▉      | 884/2248 [01:44<01:17, 17.59it/s]
 40%|███▉      | 888/2248 [01:45<01:32, 14.66it/s]
 40%|███▉      | 891/2248 [01:45<01:41, 13.30it/s]
 40%|███▉      | 893/2248 [01:45<01:53, 11.91it/s]
 40%|███▉      | 895/2248 [01:46<02:08, 10.50it/s]
 40%|███▉      | 897/2248 [01:46<01:57, 11.46it/s]
 40%|███▉      | 899/2248 [01:46<01:46, 12.67it/s]
 40%|████      | 901/2248 [01:46<01:53, 11.86it/s]
 40%|████      | 903/2248 [01:46<02:17,  9.77it/s]
 40%|████      | 905/2248 [01:47<02:06, 10.59it/s]
 40%|████      | 907/2248 [01:47<03:53,  5.75it/s]
 40%|████      | 908/2248 [01:48<04:49,  4.63it/s]
 40%|████      | 909/2248 [01:48<05:42,  3.91it/s]
 40%|████      | 910/2248 [01:49<06:58,  3.19it/s]
 41%|████      | 911/2248 [01:49<07:46,  2.87it/s]
 41%|████      | 912/2248 [01:50<08:03,  2.76it/s]
 41%|████      | 913/2248 [01:50<08:44,  2.55it/s]
 41%|████      | 916/2248 [01:50<04:34,  4.85it/s]
 41%|████      | 917/2248 [01:51<05:53,  3.77it/s]
 41%|████      | 920/2248 [01:51<05:06,  4.33it/s]
 41%|████      | 921/2248 [01:51<05:01,  4.41it/s]
 41%|████      | 923/2248 [01:52<04:18,  5.13it/s]
 41%|████      | 925/2248 [01:52<03:33,  6.20it/s]
 41%|████      | 927/2248 [01:52<03:16,  6.72it/s]
 41%|████▏     | 929/2248 [01:52<02:37,  8.36it/s]
 41%|████▏     | 931/2248 [01:53<03:37,  6.06it/s]
 42%|████▏     | 933/2248 [01:53<02:51,  7.67it/s]
 42%|████▏     | 935/2248 [01:54<04:19,  5.07it/s]
 42%|████▏     | 937/2248 [01:54<03:49,  5.70it/s]
 42%|████▏     | 939/2248 [01:54<03:05,  7.07it/s]
 42%|████▏     | 942/2248 [01:54<02:35,  8.41it/s]
 42%|████▏     | 944/2248 [01:55<03:49,  5.68it/s]
 42%|████▏     | 946/2248 [01:55<03:05,  7.01it/s]
 42%|████▏     | 948/2248 [01:55<03:07,  6.93it/s]
 42%|████▏     | 950/2248 [01:55<02:54,  7.42it/s]
 42%|████▏     | 952/2248 [01:56<03:44,  5.78it/s]
 42%|████▏     | 954/2248 [01:56<03:22,  6.38it/s]
 42%|████▏     | 955/2248 [01:56<03:36,  5.96it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 327.85it/s]

[[np.int64(0), False, 4], [np.int64(1), False, 12], [np.int64(2), False, 9], [np.int64(3), False, 12], [np.int64(5), False, 8], [np.int64(6), False, 11], [np.int64(7), False, 4], [np.int64(8), False, 13], [np.int64(10), False, 2], [np.int64(11), False, 0], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.1787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6562, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:28<2:31:53, 45.80s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:28<2:00:48, 36.61s/it]

tensor(13.1706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.6841, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7203, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:29<52:16, 16.08s/it]

tensor(13.1641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1693, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9092, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [04:29<27:31,  8.56s/it]

tensor(13.1796, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1099, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [04:29<14:04,  4.42s/it]

tensor(13.2038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1826, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2122, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2382, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [04:30<07:08,  2.27s/it]

tensor(13.2172, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2805, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2189, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3109, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [04:30<03:40,  1.18s/it]

tensor(13.2186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3417, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2156, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4022, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:30<01:58,  1.56it/s]

tensor(13.2098, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4522, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.2017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4653, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [04:30<01:08,  2.68it/s]

tensor(13.1898, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4807, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1747, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4819, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [04:30<00:44,  4.11it/s]

tensor(13.1578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1410, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5187, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [04:31<00:31,  5.61it/s]

tensor(13.1266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5527, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5704, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [04:31<00:26,  6.78it/s]

tensor(13.1069, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5908, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.1005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6023, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [04:31<00:22,  7.65it/s]

tensor(13.0954, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6129, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0905, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6279, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [04:31<00:21,  8.10it/s]

tensor(13.0855, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6362, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0800, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6557, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [04:32<00:20,  8.36it/s]

tensor(13.0742, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6810, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0680, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7003, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:32<00:19,  8.50it/s]

tensor(13.0616, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7215, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0547, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7528, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [04:32<00:19,  8.56it/s]

tensor(13.0478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7713, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0419, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7936, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [04:32<00:19,  8.46it/s]

tensor(13.0374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8191, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8334, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [04:33<00:19,  8.58it/s]

tensor(13.0290, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8609, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8752, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [04:33<00:19,  8.47it/s]

tensor(13.0175, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8899, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0119, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8705, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:33<00:18,  8.55it/s]

tensor(13.0064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8803, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8471, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:33<00:18,  8.57it/s]

tensor(12.9995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8962, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9358, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [04:33<00:17,  8.62it/s]

tensor(13.0054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9623, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9785, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [04:34<00:17,  8.59it/s]

tensor(13.0065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0095, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0016, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0582, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:34<00:17,  8.64it/s]

tensor(12.9961, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0971, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1129, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:34<00:17,  8.62it/s]

tensor(12.9915, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1297, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([188, 327, 154, 157, 280,  62, 137,  65, 173,  86,  72, 193, 200, 154])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:23, 26.93it/s]
  0%|          | 8/2248 [00:00<01:07, 33.24it/s]
  1%|          | 14/2248 [00:00<00:51, 43.14it/s]
  1%|          | 19/2248 [00:00<01:19, 28.00it/s]
  1%|          | 25/2248 [00:00<01:06, 33.28it/s]
  1%|▏         | 30/2248 [00:00<01:02, 35.74it/s]
  2%|▏         | 36/2248 [00:01<00:58, 37.58it/s]
  2%|▏         | 41/2248 [00:01<01:00, 36.56it/s]
  2%|▏         | 48/2248 [00:01<00:52, 41.91it/s]
  2%|▏         | 54/2248 [00:01<00:50, 43.77it/s]
  3%|▎         | 61/2248 [00:01<00:44, 49.45it/s]
  3%|▎         | 67/2248 [00:01<00:44, 48.65it/s]
  3%|▎         | 73/2248 [00:01<00:42, 50.66it/s]
  4%|▎         | 79/2248 [00:03<02:53, 12.53it/s]
  4%|▎         | 83/2248 [00:03<02:28, 14.58it/s]
  4%|▍         | 87/2248 [00:03<02:34, 13.95it/s]
  4%|▍         | 90/2248 [00:03<03:02, 11.84it/s]
  4%|▍         | 93/2248 [00:04<02:49, 12.73it/s]
  4%|▍         | 96/2248 [00:04<03:36,  9.93it/s]
  4%|▍         | 98/2248 [00:04<03:26, 10.43it/s]
  4%|▍         | 100/2248 [00:05<04:15,  8.41it/s]
  5%|▍         | 102/2248 [00:05<03:45,  9.53it/s]
  5%|▍         | 104/2248 [00:05<04:21,  8.19it/s]
  5%|▍         | 106/2248 [00:05<03:43,  9.57it/s]
  5%|▍         | 108/2248 [00:05<03:13, 11.08it/s]
  5%|▍         | 111/2248 [00:06<03:14, 10.99it/s]
  5%|▌         | 113/2248 [00:06<02:55, 12.18it/s]
  5%|▌         | 115/2248 [00:06<02:36, 13.62it/s]
  5%|▌         | 117/2248 [00:06<04:49,  7.37it/s]
  5%|▌         | 119/2248 [00:07<05:55,  5.98it/s]
  5%|▌         | 120/2248 [00:07<07:31,  4.71it/s]
  5%|▌         | 122/2248 [00:08<06:18,  5.62it/s]
  6%|▌         | 124/2248 [00:08<04:53,  7.25it/s]
  6%|▌         | 126/2248 [00:08<05:36,  6.32it/s]
  6%|▌         | 127/2248 [00:08<06:35,  5.37it/s]
  6%|▌         | 128/2248 [00:09<06:39,  5.31it/s]
  6%|▌         | 130/2248 [00:09<04:56,  7.13it/s]
  6%|▌         | 133/2248 [00:09<04:47,  7.35it/s]
  6%|▌         | 135/2248 [00:09<05:03,  6.95it/s]
  6%|▌         | 136/2248 [00:10<06:08,  5.74it/s]
  6%|▌         | 138/2248 [00:10<06:11,  5.69it/s]
  6%|▌         | 140/2248 [00:10<06:08,  5.72it/s]
  6%|▋         | 142/2248 [00:11<05:21,  6.55it/s]
  6%|▋         | 145/2248 [00:11<04:38,  7.56it/s]
  7%|▋         | 148/2248 [00:11<03:24, 10.28it/s]
  7%|▋         | 150/2248 [00:11<03:01, 11.56it/s]
  7%|▋         | 152/2248 [00:12<05:39,  6.17it/s]
  7%|▋         | 154/2248 [00:12<04:38,  7.51it/s]
  7%|▋         | 156/2248 [00:13<05:46,  6.03it/s]
  7%|▋         | 158/2248 [00:13<07:32,  4.62it/s]
  7%|▋         | 159/2248 [00:14<09:12,  3.78it/s]
  7%|▋         | 160/2248 [00:14<10:48,  3.22it/s]
  7%|▋         | 162/2248 [00:15<10:12,  3.41it/s]
  7%|▋         | 164/2248 [00:15<07:25,  4.68it/s]
  7%|▋         | 165/2248 [00:15<07:22,  4.71it/s]
  7%|▋         | 166/2248 [00:16<09:47,  3.55it/s]
  7%|▋         | 168/2248 [00:16<09:57,  3.48it/s]
  8%|▊         | 169/2248 [00:16<09:25,  3.67it/s]
  8%|▊         | 171/2248 [00:17<06:31,  5.31it/s]
  8%|▊         | 173/2248 [00:17<05:50,  5.92it/s]
  8%|▊         | 175/2248 [00:17<04:30,  7.66it/s]
  8%|▊         | 177/2248 [00:17<04:27,  7.74it/s]
  8%|▊         | 179/2248 [00:17<04:51,  7.10it/s]
  8%|▊         | 180/2248 [00:18<07:16,  4.74it/s]
  8%|▊         | 182/2248 [00:18<05:26,  6.34it/s]
  8%|▊         | 184/2248 [00:18<05:07,  6.70it/s]
  8%|▊         | 185/2248 [00:19<07:16,  4.73it/s]
  8%|▊         | 187/2248 [00:19<06:10,  5.57it/s]
  8%|▊         | 189/2248 [00:19<05:49,  5.88it/s]
  9%|▊         | 192/2248 [00:20<04:01,  8.52it/s]
  9%|▊         | 194/2248 [00:20<04:29,  7.63it/s]
  9%|▉         | 199/2248 [00:20<02:34, 13.23it/s]
  9%|▉         | 202/2248 [00:20<03:02, 11.21it/s]
  9%|▉         | 204/2248 [00:20<02:52, 11.86it/s]
  9%|▉         | 206/2248 [00:21<04:32,  7.50it/s]
  9%|▉         | 208/2248 [00:22<06:06,  5.57it/s]
  9%|▉         | 209/2248 [00:22<06:08,  5.54it/s]
  9%|▉         | 210/2248 [00:22<06:06,  5.56it/s]
  9%|▉         | 211/2248 [00:22<06:05,  5.58it/s]
  9%|▉         | 212/2248 [00:23<07:26,  4.56it/s]
 10%|▉         | 214/2248 [00:23<05:25,  6.24it/s]
 10%|▉         | 220/2248 [00:23<02:25, 13.98it/s]
 10%|▉         | 223/2248 [00:23<02:11, 15.43it/s]
 10%|█         | 226/2248 [00:23<01:56, 17.42it/s]
 10%|█         | 229/2248 [00:23<01:57, 17.17it/s]
 10%|█         | 232/2248 [00:23<01:45, 19.05it/s]
 11%|█         | 237/2248 [00:23<01:23, 24.02it/s]
 11%|█         | 240/2248 [00:24<01:23, 23.93it/s]
 11%|█         | 247/2248 [00:24<00:59, 33.82it/s]
 11%|█▏        | 253/2248 [00:24<00:50, 39.72it/s]
 11%|█▏        | 258/2248 [00:24<00:48, 40.90it/s]
 12%|█▏        | 263/2248 [00:25<01:49, 18.07it/s]
 12%|█▏        | 267/2248 [00:25<02:08, 15.46it/s]
 12%|█▏        | 270/2248 [00:25<01:57, 16.86it/s]
 12%|█▏        | 273/2248 [00:25<02:16, 14.43it/s]
 12%|█▏        | 276/2248 [00:26<02:05, 15.71it/s]
 12%|█▏        | 279/2248 [00:26<02:06, 15.55it/s]
 12%|█▎        | 281/2248 [00:26<02:25, 13.53it/s]
 13%|█▎        | 283/2248 [00:26<02:48, 11.69it/s]
 13%|█▎        | 285/2248 [00:26<03:18,  9.90it/s]
 13%|█▎        | 287/2248 [00:27<04:35,  7.13it/s]
 13%|█▎        | 289/2248 [00:27<03:53,  8.39it/s]
 13%|█▎        | 291/2248 [00:28<07:20,  4.44it/s]
 13%|█▎        | 293/2248 [00:28<05:44,  5.68it/s]
 13%|█▎        | 297/2248 [00:28<03:32,  9.19it/s]
 13%|█▎        | 299/2248 [00:29<05:21,  6.06it/s]
 13%|█▎        | 302/2248 [00:29<04:38,  6.99it/s]
 14%|█▎        | 304/2248 [00:30<05:24,  5.99it/s]
 14%|█▎        | 306/2248 [00:30<05:02,  6.42it/s]
 14%|█▎        | 307/2248 [00:30<05:15,  6.16it/s]
 14%|█▎        | 308/2248 [00:30<05:37,  5.74it/s]
 14%|█▎        | 309/2248 [00:31<08:04,  4.00it/s]
 14%|█▍        | 311/2248 [00:31<05:44,  5.63it/s]
 14%|█▍        | 312/2248 [00:31<05:39,  5.70it/s]
 14%|█▍        | 313/2248 [00:31<05:35,  5.77it/s]
 14%|█▍        | 314/2248 [00:32<05:43,  5.63it/s]
 14%|█▍        | 315/2248 [00:32<07:17,  4.42it/s]
 14%|█▍        | 318/2248 [00:32<05:37,  5.72it/s]
 14%|█▍        | 320/2248 [00:33<06:06,  5.25it/s]
 14%|█▍        | 322/2248 [00:33<06:27,  4.97it/s]
 14%|█▍        | 323/2248 [00:33<06:29,  4.94it/s]
 14%|█▍        | 325/2248 [00:34<05:36,  5.72it/s]
 15%|█▍        | 327/2248 [00:34<04:16,  7.48it/s]
 15%|█▍        | 329/2248 [00:34<04:13,  7.56it/s]
 15%|█▍        | 332/2248 [00:35<04:51,  6.58it/s]
 15%|█▍        | 334/2248 [00:35<03:57,  8.07it/s]
 15%|█▌        | 339/2248 [00:35<03:50,  8.29it/s]
 15%|█▌        | 342/2248 [00:35<03:00, 10.56it/s]
 15%|█▌        | 344/2248 [00:36<04:37,  6.86it/s]
 15%|█▌        | 346/2248 [00:37<05:08,  6.16it/s]
 15%|█▌        | 347/2248 [00:37<06:42,  4.72it/s]
 15%|█▌        | 348/2248 [00:37<06:36,  4.80it/s]
 16%|█▌        | 349/2248 [00:37<06:36,  4.79it/s]
 16%|█▌        | 350/2248 [00:38<08:31,  3.71it/s]
 16%|█▌        | 353/2248 [00:38<05:58,  5.28it/s]
 16%|█▌        | 355/2248 [00:38<05:21,  5.90it/s]
 16%|█▌        | 356/2248 [00:39<05:36,  5.63it/s]
 16%|█▌        | 358/2248 [00:39<04:19,  7.29it/s]
 16%|█▌        | 360/2248 [00:39<05:25,  5.79it/s]
 16%|█▌        | 362/2248 [00:40<06:28,  4.86it/s]
 16%|█▌        | 363/2248 [00:40<05:57,  5.27it/s]
 16%|█▌        | 364/2248 [00:40<05:59,  5.24it/s]
 16%|█▋        | 366/2248 [00:41<06:54,  4.54it/s]
 16%|█▋        | 367/2248 [00:41<06:27,  4.85it/s]
 16%|█▋        | 369/2248 [00:41<04:39,  6.72it/s]
 17%|█▋        | 371/2248 [00:41<04:15,  7.36it/s]
 17%|█▋        | 373/2248 [00:41<03:30,  8.92it/s]
 17%|█▋        | 376/2248 [00:41<02:37, 11.92it/s]
 17%|█▋        | 378/2248 [00:42<02:44, 11.40it/s]
 17%|█▋        | 383/2248 [00:42<01:40, 18.62it/s]
 17%|█▋        | 386/2248 [00:42<02:44, 11.33it/s]
 17%|█▋        | 388/2248 [00:42<02:35, 11.93it/s]
 17%|█▋        | 390/2248 [00:43<03:37,  8.56it/s]
 17%|█▋        | 392/2248 [00:43<04:28,  6.90it/s]
 18%|█▊        | 394/2248 [00:44<04:54,  6.30it/s]
 18%|█▊        | 395/2248 [00:44<05:33,  5.56it/s]
 18%|█▊        | 397/2248 [00:44<04:26,  6.95it/s]
 18%|█▊        | 403/2248 [00:44<02:11, 14.02it/s]
 18%|█▊        | 410/2248 [00:44<01:20, 22.80it/s]
 19%|█▊        | 416/2248 [00:44<01:02, 29.40it/s]
 19%|█▉        | 423/2248 [00:45<00:49, 37.17it/s]
 19%|█▉        | 430/2248 [00:45<00:41, 43.75it/s]
 19%|█▉        | 436/2248 [00:45<00:59, 30.51it/s]
 20%|█▉        | 441/2248 [00:46<02:17, 13.18it/s]
 20%|█▉        | 445/2248 [00:46<02:16, 13.19it/s]
 20%|█▉        | 448/2248 [00:47<02:58, 10.10it/s]
 20%|██        | 450/2248 [00:47<03:42,  8.09it/s]
 20%|██        | 452/2248 [00:47<03:20,  8.94it/s]
 20%|██        | 454/2248 [00:48<03:21,  8.88it/s]
 20%|██        | 456/2248 [00:48<03:42,  8.05it/s]
 20%|██        | 458/2248 [00:48<03:46,  7.89it/s]
 20%|██        | 460/2248 [00:49<04:26,  6.72it/s]
 21%|██        | 463/2248 [00:49<04:45,  6.26it/s]
 21%|██        | 464/2248 [00:50<06:07,  4.86it/s]
 21%|██        | 467/2248 [00:50<04:08,  7.17it/s]
 21%|██        | 471/2248 [00:50<04:02,  7.32it/s]
 21%|██        | 473/2248 [00:51<03:57,  7.46it/s]
 21%|██        | 475/2248 [00:51<03:52,  7.62it/s]
 21%|██        | 477/2248 [00:51<03:47,  7.77it/s]
 21%|██▏       | 478/2248 [00:51<04:18,  6.83it/s]
 21%|██▏       | 479/2248 [00:52<04:36,  6.39it/s]
 21%|██▏       | 480/2248 [00:52<04:48,  6.13it/s]
 21%|██▏       | 481/2248 [00:52<05:06,  5.76it/s]
 21%|██▏       | 482/2248 [00:52<07:04,  4.16it/s]
 22%|██▏       | 484/2248 [00:52<04:45,  6.17it/s]
 22%|██▏       | 486/2248 [00:53<05:37,  5.23it/s]
 22%|██▏       | 487/2248 [00:53<06:23,  4.59it/s]
 22%|██▏       | 488/2248 [00:54<08:01,  3.66it/s]
 22%|██▏       | 490/2248 [00:54<05:32,  5.28it/s]
 22%|██▏       | 492/2248 [00:54<04:05,  7.14it/s]
 22%|██▏       | 495/2248 [00:54<02:56,  9.95it/s]
 22%|██▏       | 498/2248 [00:54<02:16, 12.81it/s]
 22%|██▏       | 500/2248 [00:55<02:53, 10.09it/s]
 22%|██▏       | 502/2248 [00:55<02:36, 11.12it/s]
 22%|██▏       | 504/2248 [00:55<03:40,  7.92it/s]
 23%|██▎       | 506/2248 [00:55<03:12,  9.07it/s]
 23%|██▎       | 509/2248 [00:56<03:34,  8.11it/s]
 23%|██▎       | 512/2248 [00:56<03:22,  8.57it/s]
 23%|██▎       | 514/2248 [00:57<04:55,  5.87it/s]
 23%|██▎       | 515/2248 [00:57<05:16,  5.48it/s]
 23%|██▎       | 518/2248 [00:57<04:45,  6.06it/s]
 23%|██▎       | 519/2248 [00:58<05:05,  5.65it/s]
 23%|██▎       | 522/2248 [00:58<03:29,  8.23it/s]
 24%|██▎       | 529/2248 [00:58<01:44, 16.44it/s]
 24%|██▍       | 535/2248 [00:58<01:15, 22.81it/s]
 24%|██▍       | 541/2248 [00:58<00:59, 28.47it/s]
 24%|██▍       | 547/2248 [00:58<00:49, 34.56it/s]
 25%|██▍       | 552/2248 [00:58<00:48, 35.30it/s]
 25%|██▍       | 558/2248 [00:58<00:42, 39.55it/s]
 25%|██▌       | 564/2248 [00:58<00:38, 43.73it/s]
 25%|██▌       | 571/2248 [00:59<00:39, 42.70it/s]
 26%|██▌       | 576/2248 [00:59<01:34, 17.61it/s]
 26%|██▌       | 580/2248 [01:00<02:03, 13.48it/s]
 26%|██▌       | 583/2248 [01:00<02:32, 10.90it/s]
 26%|██▌       | 586/2248 [01:01<02:51,  9.71it/s]
 26%|██▌       | 588/2248 [01:01<02:59,  9.26it/s]
 26%|██▌       | 590/2248 [01:01<02:49,  9.76it/s]
 26%|██▋       | 592/2248 [01:02<03:13,  8.54it/s]
 26%|██▋       | 594/2248 [01:02<02:49,  9.74it/s]
 27%|██▋       | 599/2248 [01:02<02:46,  9.93it/s]
 27%|██▋       | 603/2248 [01:03<02:33, 10.69it/s]
 27%|██▋       | 605/2248 [01:03<03:11,  8.56it/s]
 27%|██▋       | 607/2248 [01:03<03:57,  6.92it/s]
 27%|██▋       | 608/2248 [01:04<04:53,  5.58it/s]
 27%|██▋       | 609/2248 [01:04<06:03,  4.50it/s]
 27%|██▋       | 610/2248 [01:05<07:07,  3.83it/s]
 27%|██▋       | 612/2248 [01:05<05:10,  5.26it/s]
 27%|██▋       | 614/2248 [01:05<03:54,  6.97it/s]
 27%|██▋       | 616/2248 [01:05<03:10,  8.55it/s]
 28%|██▊       | 620/2248 [01:05<02:02, 13.32it/s]
 28%|██▊       | 622/2248 [01:05<01:59, 13.61it/s]
 28%|██▊       | 624/2248 [01:05<01:52, 14.48it/s]
 28%|██▊       | 626/2248 [01:06<01:49, 14.86it/s]
 28%|██▊       | 632/2248 [01:06<01:07, 24.07it/s]
 28%|██▊       | 638/2248 [01:06<00:51, 31.18it/s]
 29%|██▊       | 645/2248 [01:06<00:40, 39.48it/s]
 29%|██▉       | 650/2248 [01:06<01:14, 21.38it/s]
 29%|██▉       | 654/2248 [01:07<02:46,  9.60it/s]
 29%|██▉       | 658/2248 [01:08<02:55,  9.05it/s]
 29%|██▉       | 660/2248 [01:09<03:33,  7.44it/s]
 29%|██▉       | 662/2248 [01:09<03:48,  6.95it/s]
 30%|██▉       | 664/2248 [01:09<04:11,  6.30it/s]
 30%|██▉       | 665/2248 [01:10<04:37,  5.70it/s]
 30%|██▉       | 667/2248 [01:10<03:54,  6.76it/s]
 30%|██▉       | 670/2248 [01:10<04:00,  6.57it/s]
 30%|██▉       | 673/2248 [01:10<03:07,  8.41it/s]
 30%|███       | 677/2248 [01:11<03:16,  7.98it/s]
 30%|███       | 679/2248 [01:11<03:59,  6.56it/s]
 30%|███       | 681/2248 [01:12<04:37,  5.65it/s]
 30%|███       | 682/2248 [01:12<05:45,  4.54it/s]
 30%|███       | 683/2248 [01:13<05:35,  4.66it/s]
 30%|███       | 685/2248 [01:13<05:57,  4.38it/s]
 31%|███       | 687/2248 [01:13<04:33,  5.70it/s]
 31%|███       | 688/2248 [01:14<05:58,  4.35it/s]
 31%|███       | 690/2248 [01:14<04:24,  5.89it/s]
 31%|███       | 691/2248 [01:14<04:31,  5.74it/s]
 31%|███       | 692/2248 [01:14<06:13,  4.17it/s]
 31%|███       | 695/2248 [01:15<04:10,  6.20it/s]
 31%|███       | 697/2248 [01:15<03:17,  7.87it/s]
 31%|███▏      | 704/2248 [01:15<01:53, 13.66it/s]
 31%|███▏      | 706/2248 [01:16<02:46,  9.28it/s]
 32%|███▏      | 709/2248 [01:16<02:40,  9.60it/s]
 32%|███▏      | 711/2248 [01:16<02:49,  9.06it/s]
 32%|███▏      | 713/2248 [01:16<02:55,  8.73it/s]
 32%|███▏      | 715/2248 [01:17<03:00,  8.50it/s]
 32%|███▏      | 717/2248 [01:17<02:35,  9.84it/s]
 32%|███▏      | 719/2248 [01:17<03:31,  7.24it/s]
 32%|███▏      | 722/2248 [01:17<02:31, 10.07it/s]
 32%|███▏      | 727/2248 [01:18<02:32,  9.98it/s]
 32%|███▏      | 729/2248 [01:18<02:44,  9.22it/s]
 33%|███▎      | 731/2248 [01:18<02:47,  9.07it/s]
 33%|███▎      | 733/2248 [01:19<04:23,  5.76it/s]
 33%|███▎      | 735/2248 [01:19<04:03,  6.21it/s]
 33%|███▎      | 736/2248 [01:20<04:18,  5.86it/s]
 33%|███▎      | 737/2248 [01:20<04:22,  5.77it/s]
 33%|███▎      | 738/2248 [01:20<05:52,  4.29it/s]
 33%|███▎      | 741/2248 [01:20<03:35,  7.01it/s]
 33%|███▎      | 743/2248 [01:21<05:04,  4.95it/s]
 33%|███▎      | 747/2248 [01:21<03:02,  8.22it/s]
 33%|███▎      | 749/2248 [01:22<03:38,  6.87it/s]
 33%|███▎      | 751/2248 [01:22<04:26,  5.61it/s]
 33%|███▎      | 752/2248 [01:22<04:31,  5.51it/s]
 34%|███▎      | 754/2248 [01:23<05:08,  4.85it/s]
 34%|███▎      | 757/2248 [01:23<03:27,  7.19it/s]
 34%|███▍      | 761/2248 [01:23<03:20,  7.41it/s]
 34%|███▍      | 763/2248 [01:24<04:05,  6.05it/s]
 34%|███▍      | 765/2248 [01:24<03:25,  7.21it/s]
 34%|███▍      | 767/2248 [01:24<03:42,  6.66it/s]
 34%|███▍      | 769/2248 [01:25<03:07,  7.89it/s]
 34%|███▍      | 772/2248 [01:25<04:08,  5.94it/s]
 34%|███▍      | 773/2248 [01:26<04:31,  5.43it/s]
 34%|███▍      | 774/2248 [01:26<04:28,  5.48it/s]
 34%|███▍      | 775/2248 [01:26<04:51,  5.05it/s]
 35%|███▍      | 776/2248 [01:26<04:45,  5.15it/s]
 35%|███▍      | 778/2248 [01:26<03:51,  6.35it/s]
 35%|███▍      | 781/2248 [01:27<02:35,  9.41it/s]
 35%|███▍      | 783/2248 [01:27<03:26,  7.08it/s]
 35%|███▍      | 784/2248 [01:27<03:18,  7.37it/s]
 35%|███▌      | 787/2248 [01:27<02:15, 10.81it/s]
 35%|███▌      | 791/2248 [01:28<02:25, 10.03it/s]
 35%|███▌      | 793/2248 [01:28<03:27,  7.03it/s]
 35%|███▌      | 795/2248 [01:29<03:37,  6.67it/s]
 35%|███▌      | 797/2248 [01:29<03:16,  7.40it/s]
 36%|███▌      | 800/2248 [01:29<03:38,  6.63it/s]
 36%|███▌      | 802/2248 [01:29<03:06,  7.76it/s]
 36%|███▌      | 805/2248 [01:29<02:18, 10.40it/s]
 36%|███▌      | 807/2248 [01:30<03:11,  7.53it/s]
 36%|███▌      | 809/2248 [01:31<04:05,  5.85it/s]
 36%|███▌      | 810/2248 [01:31<04:29,  5.33it/s]
 36%|███▌      | 811/2248 [01:31<05:57,  4.02it/s]
 36%|███▌      | 812/2248 [01:32<06:47,  3.52it/s]
 36%|███▌      | 813/2248 [01:32<07:15,  3.30it/s]
 36%|███▋      | 815/2248 [01:33<06:40,  3.58it/s]
 36%|███▋      | 816/2248 [01:33<06:58,  3.43it/s]
 36%|███▋      | 818/2248 [01:33<04:51,  4.91it/s]
 36%|███▋      | 820/2248 [01:33<03:34,  6.64it/s]
 37%|███▋      | 824/2248 [01:33<02:06, 11.24it/s]
 37%|███▋      | 829/2248 [01:33<01:22, 17.18it/s]
 37%|███▋      | 834/2248 [01:33<01:00, 23.20it/s]
 37%|███▋      | 841/2248 [01:34<00:43, 32.26it/s]
 38%|███▊      | 847/2248 [01:34<00:37, 37.63it/s]
 38%|███▊      | 853/2248 [01:34<00:33, 41.89it/s]
 38%|███▊      | 860/2248 [01:34<00:29, 47.63it/s]
 39%|███▊      | 866/2248 [01:34<00:38, 35.58it/s]
 39%|███▊      | 871/2248 [01:35<01:44, 13.13it/s]
 39%|███▉      | 875/2248 [01:35<01:32, 14.88it/s]
 39%|███▉      | 879/2248 [01:36<01:53, 12.04it/s]
 39%|███▉      | 882/2248 [01:36<02:26,  9.31it/s]
 39%|███▉      | 884/2248 [01:37<02:31,  9.02it/s]
 39%|███▉      | 886/2248 [01:37<02:33,  8.85it/s]
 40%|███▉      | 888/2248 [01:37<02:34,  8.81it/s]
 40%|███▉      | 890/2248 [01:38<02:47,  8.10it/s]
 40%|███▉      | 892/2248 [01:38<03:01,  7.47it/s]
 40%|███▉      | 894/2248 [01:38<03:40,  6.14it/s]
 40%|███▉      | 895/2248 [01:39<04:46,  4.72it/s]
 40%|███▉      | 898/2248 [01:39<03:12,  7.03it/s]
 40%|████      | 902/2248 [01:39<02:25,  9.25it/s]
 40%|████      | 904/2248 [01:40<02:41,  8.30it/s]
 40%|████      | 906/2248 [01:40<02:41,  8.29it/s]
 40%|████      | 908/2248 [01:40<04:05,  5.45it/s]
 40%|████      | 909/2248 [01:41<05:10,  4.31it/s]
 40%|████      | 910/2248 [01:41<04:59,  4.47it/s]
 41%|████      | 911/2248 [01:41<04:55,  4.52it/s]
 41%|████      | 912/2248 [01:42<05:00,  4.45it/s]
 41%|████      | 913/2248 [01:42<06:20,  3.51it/s]
 41%|████      | 916/2248 [01:42<04:11,  5.30it/s]
 41%|████      | 917/2248 [01:43<05:29,  4.03it/s]
 41%|████      | 919/2248 [01:43<04:26,  4.98it/s]
 41%|████      | 920/2248 [01:43<04:25,  5.00it/s]
 41%|████      | 922/2248 [01:43<03:13,  6.86it/s]
 41%|████      | 927/2248 [01:44<02:03, 10.70it/s]
 41%|████▏     | 929/2248 [01:44<02:58,  7.38it/s]
 41%|████▏     | 931/2248 [01:45<03:38,  6.02it/s]
 42%|████▏     | 934/2248 [01:45<03:02,  7.19it/s]
 42%|████▏     | 936/2248 [01:46<04:01,  5.44it/s]
 42%|████▏     | 938/2248 [01:46<03:34,  6.10it/s]
 42%|████▏     | 940/2248 [01:46<03:05,  7.05it/s]
 42%|████▏     | 942/2248 [01:46<02:39,  8.17it/s]
 42%|████▏     | 944/2248 [01:46<02:17,  9.48it/s]
 42%|████▏     | 951/2248 [01:46<01:08, 19.04it/s]
 42%|████▏     | 954/2248 [01:47<01:42, 12.59it/s]
 43%|████▎     | 957/2248 [01:47<02:18,  9.30it/s]
 43%|████▎     | 959/2248 [01:48<02:30,  8.54it/s]
 43%|████▎     | 961/2248 [01:48<03:00,  7.14it/s]
 43%|████▎     | 963/2248 [01:49<03:56,  5.43it/s]
 43%|████▎     | 966/2248 [01:49<03:21,  6.37it/s]
 43%|████▎     | 967/2248 [01:50<04:15,  5.01it/s]
 43%|████▎     | 969/2248 [01:50<03:49,  5.57it/s]
 43%|████▎     | 970/2248 [01:50<03:52,  5.50it/s]
 43%|████▎     | 973/2248 [01:50<02:32,  8.38it/s]
 43%|████▎     | 976/2248 [01:50<02:12,  9.62it/s]
 44%|████▎     | 979/2248 [01:50<01:42, 12.35it/s]
 44%|████▎     | 981/2248 [01:51<01:51, 11.32it/s]
 44%|████▎     | 983/2248 [01:51<01:41, 12.44it/s]
 44%|████▍     | 985/2248 [01:51<01:48, 11.64it/s]
 44%|████▍     | 987/2248 [01:51<02:01, 10.38it/s]
 44%|████▍     | 989/2248 [01:51<01:47, 11.72it/s]
 44%|████▍     | 991/2248 [01:52<02:49,  7.39it/s]
 44%|████▍     | 993/2248 [01:52<02:18,  9.03it/s]
 44%|████▍     | 998/2248 [01:52<02:14,  9.28it/s]
 44%|████▍     | 1000/2248 [01:53<02:20,  8.87it/s]
 45%|████▍     | 1002/2248 [01:53<02:22,  8.73it/s]
 45%|████▍     | 1004/2248 [01:54<03:43,  5.56it/s]
 45%|████▍     | 1005/2248 [01:54<03:49,  5.43it/s]
 45%|████▍     | 1006/2248 [01:54<03:50,  5.38it/s]
 45%|████▍     | 1008/2248 [01:54<03:04,  6.73it/s]
 45%|████▍     | 1009/2248 [01:55<04:01,  5.14it/s]
 45%|████▌     | 1012/2248 [01:55<02:42,  7.60it/s]
 45%|████▌     | 1014/2248 [01:55<02:13,  9.28it/s]
 45%|████▌     | 1021/2248 [01:55<01:08, 17.91it/s]
 46%|████▌     | 1025/2248 [01:55<00:56, 21.52it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 329.94it/s]

[[np.int64(0), False, 11], [np.int64(1), False, 3], [np.int64(2), False, 0], [np.int64(3), False, 12], [np.int64(4), False, 3], [np.int64(5), False, 10], [np.int64(6), False, 12], [np.int64(7), False, 5], [np.int64(8), False, 4], [np.int64(9), False, 4], [np.int64(13), False, 11]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.9897, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1801, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [08:27<2:53:52, 70.02s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [08:27<2:01:00, 49.06s/it]

tensor(12.9870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3855, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9887, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5992, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [08:28<40:50, 16.90s/it]

tensor(12.9965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7661, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0067, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0289, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8037, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [08:28<19:52,  8.34s/it]

tensor(13.0178, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0293, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8254, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7892, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [08:28<09:44,  4.15s/it]

tensor(13.0254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8232, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0306, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8534, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [08:28<04:50,  2.09s/it]

tensor(13.0193, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9354, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0184, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9825, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [08:29<02:28,  1.08s/it]

tensor(13.0107, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0329, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0070, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0306, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [08:29<01:19,  1.69it/s]

tensor(12.9938, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0340, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0697, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9878, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1132, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [08:29<00:46,  2.86it/s]

tensor(12.9818, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1839, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2139, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [08:29<00:30,  4.32it/s]

tensor(12.9748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0338, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2349, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2534, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [08:30<00:22,  5.80it/s]

tensor(12.9695, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0333, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2683, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0323, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2846, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [08:30<00:18,  6.95it/s]

tensor(12.9601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3124, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3364, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [08:30<00:16,  7.73it/s]

tensor(12.9564, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3436, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3458, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [08:30<00:15,  8.12it/s]

tensor(12.9460, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3376, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9395, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0276, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3508, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [08:30<00:14,  8.36it/s]

tensor(12.9333, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3604, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3750, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [08:31<00:14,  8.49it/s]

tensor(12.9286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3839, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3936, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [08:31<00:13,  8.56it/s]

tensor(12.9254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3994, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9223, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4025, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [08:31<00:13,  8.60it/s]

tensor(12.9180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4126, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9136, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4159, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [08:31<00:13,  8.59it/s]

tensor(12.9101, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4167, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4169, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [08:32<00:12,  8.60it/s]

tensor(12.9049, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4132, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9026, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4163, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [08:32<00:12,  8.56it/s]

tensor(12.9001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4128, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8974, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4222, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [08:32<00:12,  8.58it/s]

tensor(12.8944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4241, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8917, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4342, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [08:32<00:12,  8.64it/s]

tensor(12.8892, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4378, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4404, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [08:33<00:12,  8.55it/s]

tensor(12.8850, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4402, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8831, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4425, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [08:33<00:11,  8.52it/s]

tensor(12.8810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4368, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8789, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4366, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [08:33<00:11,  8.59it/s]

tensor(12.8769, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4386, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([189, 248,  82, 153, 177, 129, 101, 308, 153, 144,  91,  57,  92, 324])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<01:53, 19.79it/s]
  0%|          | 8/2248 [00:00<00:52, 42.87it/s]
  1%|          | 13/2248 [00:00<01:30, 24.62it/s]
  1%|          | 19/2248 [00:00<01:07, 33.14it/s]
  1%|          | 24/2248 [00:00<00:59, 37.30it/s]
  1%|▏         | 32/2248 [00:00<00:46, 48.11it/s]
  2%|▏         | 38/2248 [00:01<01:21, 27.08it/s]
  2%|▏         | 43/2248 [00:01<01:14, 29.49it/s]
  2%|▏         | 48/2248 [00:01<01:17, 28.30it/s]
  2%|▏         | 52/2248 [00:01<01:18, 28.11it/s]
  2%|▏         | 56/2248 [00:01<01:16, 28.55it/s]
  3%|▎         | 63/2248 [00:01<01:00, 36.29it/s]
  3%|▎         | 71/2248 [00:02<00:48, 44.77it/s]
  3%|▎         | 77/2248 [00:02<01:37, 22.33it/s]
  4%|▎         | 81/2248 [00:03<02:31, 14.30it/s]
  4%|▎         | 84/2248 [00:03<02:52, 12.52it/s]
  4%|▍         | 87/2248 [00:04<03:39,  9.86it/s]
  4%|▍         | 90/2248 [00:04<03:38,  9.88it/s]
  4%|▍         | 92/2248 [00:04<03:29, 10.31it/s]
  4%|▍         | 95/2248 [00:05<04:02,  8.89it/s]
  4%|▍         | 97/2248 [00:05<05:12,  6.89it/s]
  4%|▍         | 99/2248 [00:05<04:33,  7.86it/s]
  4%|▍         | 101/2248 [00:05<04:17,  8.33it/s]
  5%|▍         | 103/2248 [00:06<04:05,  8.73it/s]
  5%|▍         | 105/2248 [00:06<04:10,  8.57it/s]
  5%|▍         | 107/2248 [00:06<03:34,  9.97it/s]
  5%|▍         | 111/2248 [00:06<03:44,  9.51it/s]
  5%|▌         | 113/2248 [00:07<04:33,  7.81it/s]
  5%|▌         | 116/2248 [00:07<04:53,  7.27it/s]
  5%|▌         | 117/2248 [00:08<06:25,  5.53it/s]
  5%|▌         | 118/2248 [00:08<07:36,  4.67it/s]
  5%|▌         | 120/2248 [00:09<07:43,  4.59it/s]
  5%|▌         | 122/2248 [00:09<07:47,  4.54it/s]
  6%|▌         | 124/2248 [00:09<05:55,  5.97it/s]
  6%|▌         | 125/2248 [00:10<07:37,  4.64it/s]
  6%|▌         | 126/2248 [00:10<09:22,  3.77it/s]
  6%|▌         | 127/2248 [00:11<11:25,  3.10it/s]
  6%|▌         | 128/2248 [00:11<12:15,  2.88it/s]
  6%|▌         | 132/2248 [00:11<05:42,  6.18it/s]
  6%|▌         | 134/2248 [00:12<06:09,  5.73it/s]
  6%|▌         | 136/2248 [00:12<07:44,  4.55it/s]
  6%|▌         | 138/2248 [00:13<07:01,  5.01it/s]
  6%|▌         | 140/2248 [00:13<07:13,  4.87it/s]
  6%|▋         | 142/2248 [00:13<05:48,  6.04it/s]
  6%|▋         | 145/2248 [00:14<05:33,  6.31it/s]
  7%|▋         | 148/2248 [00:14<03:59,  8.77it/s]
  7%|▋         | 151/2248 [00:14<04:32,  7.69it/s]
  7%|▋         | 154/2248 [00:14<03:31,  9.91it/s]
  7%|▋         | 156/2248 [00:15<04:37,  7.54it/s]
  7%|▋         | 158/2248 [00:16<07:36,  4.58it/s]
  7%|▋         | 159/2248 [00:16<08:57,  3.89it/s]
  7%|▋         | 160/2248 [00:17<10:17,  3.38it/s]
  7%|▋         | 162/2248 [00:17<09:38,  3.61it/s]
  7%|▋         | 165/2248 [00:18<08:36,  4.03it/s]
  7%|▋         | 166/2248 [00:18<09:24,  3.69it/s]
  7%|▋         | 168/2248 [00:19<09:04,  3.82it/s]
  8%|▊         | 169/2248 [00:19<10:18,  3.36it/s]
  8%|▊         | 171/2248 [00:19<07:50,  4.41it/s]
  8%|▊         | 173/2248 [00:19<05:50,  5.93it/s]
  8%|▊         | 176/2248 [00:20<06:00,  5.75it/s]
  8%|▊         | 178/2248 [00:20<07:11,  4.80it/s]
  8%|▊         | 180/2248 [00:21<07:22,  4.68it/s]
  8%|▊         | 183/2248 [00:21<07:06,  4.84it/s]
  8%|▊         | 185/2248 [00:22<06:32,  5.25it/s]
  8%|▊         | 186/2248 [00:22<06:26,  5.33it/s]
  8%|▊         | 187/2248 [00:22<08:21,  4.11it/s]
  8%|▊         | 189/2248 [00:23<08:51,  3.87it/s]
  8%|▊         | 190/2248 [00:23<08:01,  4.28it/s]
  8%|▊         | 191/2248 [00:23<07:18,  4.69it/s]
  9%|▊         | 193/2248 [00:24<07:10,  4.77it/s]
  9%|▊         | 194/2248 [00:24<06:59,  4.90it/s]
  9%|▊         | 195/2248 [00:24<09:03,  3.78it/s]
  9%|▉         | 197/2248 [00:25<07:08,  4.78it/s]
  9%|▉         | 198/2248 [00:25<07:14,  4.71it/s]
  9%|▉         | 199/2248 [00:25<07:02,  4.85it/s]
  9%|▉         | 200/2248 [00:25<06:37,  5.16it/s]
  9%|▉         | 201/2248 [00:26<08:41,  3.93it/s]
  9%|▉         | 202/2248 [00:26<10:35,  3.22it/s]
  9%|▉         | 203/2248 [00:26<08:40,  3.93it/s]
  9%|▉         | 204/2248 [00:26<07:24,  4.60it/s]
  9%|▉         | 205/2248 [00:27<08:48,  3.87it/s]
  9%|▉         | 206/2248 [00:27<09:31,  3.57it/s]
  9%|▉         | 207/2248 [00:27<10:08,  3.36it/s]
  9%|▉         | 208/2248 [00:27<08:48,  3.86it/s]
  9%|▉         | 209/2248 [00:28<08:02,  4.23it/s]
  9%|▉         | 210/2248 [00:28<09:35,  3.54it/s]
  9%|▉         | 211/2248 [00:28<10:07,  3.35it/s]
  9%|▉         | 212/2248 [00:29<09:03,  3.75it/s]
 10%|▉         | 214/2248 [00:29<06:24,  5.29it/s]
 10%|▉         | 216/2248 [00:29<04:46,  7.08it/s]
 10%|▉         | 219/2248 [00:29<03:10, 10.65it/s]
 10%|▉         | 221/2248 [00:29<03:06, 10.88it/s]
 10%|▉         | 223/2248 [00:29<03:08, 10.73it/s]
 10%|█         | 226/2248 [00:30<02:22, 14.23it/s]
 10%|█         | 228/2248 [00:30<02:41, 12.52it/s]
 10%|█         | 230/2248 [00:30<02:25, 13.87it/s]
 10%|█         | 236/2248 [00:30<02:10, 15.42it/s]
 11%|█         | 238/2248 [00:30<02:09, 15.57it/s]
 11%|█         | 244/2248 [00:30<01:25, 23.55it/s]
 11%|█         | 249/2248 [00:31<01:31, 21.93it/s]
 11%|█         | 252/2248 [00:31<01:29, 22.31it/s]
 11%|█▏        | 258/2248 [00:31<01:08, 29.13it/s]
 12%|█▏        | 262/2248 [00:31<02:08, 15.43it/s]
 12%|█▏        | 265/2248 [00:33<04:16,  7.72it/s]
 12%|█▏        | 267/2248 [00:33<05:20,  6.19it/s]
 12%|█▏        | 269/2248 [00:33<04:47,  6.88it/s]
 12%|█▏        | 271/2248 [00:33<04:16,  7.71it/s]
 12%|█▏        | 273/2248 [00:34<05:45,  5.72it/s]
 12%|█▏        | 276/2248 [00:34<04:12,  7.80it/s]
 12%|█▏        | 278/2248 [00:35<05:23,  6.09it/s]
 12%|█▏        | 280/2248 [00:35<06:17,  5.22it/s]
 12%|█▎        | 281/2248 [00:36<06:37,  4.94it/s]
 13%|█▎        | 282/2248 [00:36<07:19,  4.47it/s]
 13%|█▎        | 284/2248 [00:36<07:07,  4.59it/s]
 13%|█▎        | 286/2248 [00:37<07:41,  4.25it/s]
 13%|█▎        | 287/2248 [00:37<09:15,  3.53it/s]
 13%|█▎        | 289/2248 [00:37<07:01,  4.64it/s]
 13%|█▎        | 290/2248 [00:38<08:45,  3.72it/s]
 13%|█▎        | 291/2248 [00:38<10:23,  3.14it/s]
 13%|█▎        | 293/2248 [00:39<07:04,  4.61it/s]
 13%|█▎        | 295/2248 [00:39<05:13,  6.22it/s]
 13%|█▎        | 298/2248 [00:39<05:12,  6.25it/s]
 13%|█▎        | 299/2248 [00:40<06:50,  4.75it/s]
 13%|█▎        | 300/2248 [00:40<07:42,  4.22it/s]
 13%|█▎        | 301/2248 [00:40<06:51,  4.73it/s]
 13%|█▎        | 302/2248 [00:40<07:24,  4.38it/s]
 13%|█▎        | 303/2248 [00:41<07:20,  4.41it/s]
 14%|█▎        | 304/2248 [00:41<07:07,  4.55it/s]
 14%|█▎        | 305/2248 [00:41<07:48,  4.15it/s]
 14%|█▎        | 306/2248 [00:41<08:30,  3.80it/s]
 14%|█▎        | 307/2248 [00:42<08:56,  3.62it/s]
 14%|█▎        | 308/2248 [00:42<08:17,  3.90it/s]
 14%|█▎        | 309/2248 [00:42<06:48,  4.75it/s]
 14%|█▍        | 310/2248 [00:42<06:08,  5.26it/s]
 14%|█▍        | 312/2248 [00:43<07:21,  4.38it/s]
 14%|█▍        | 313/2248 [00:43<08:12,  3.93it/s]
 14%|█▍        | 314/2248 [00:44<10:57,  2.94it/s]
 14%|█▍        | 315/2248 [00:44<11:13,  2.87it/s]
 14%|█▍        | 317/2248 [00:44<07:14,  4.44it/s]
 14%|█▍        | 320/2248 [00:45<05:46,  5.56it/s]
 14%|█▍        | 322/2248 [00:45<05:46,  5.56it/s]
 14%|█▍        | 323/2248 [00:45<06:33,  4.89it/s]
 14%|█▍        | 325/2248 [00:46<07:06,  4.51it/s]
 15%|█▍        | 327/2248 [00:46<08:00,  4.00it/s]
 15%|█▍        | 328/2248 [00:47<09:26,  3.39it/s]
 15%|█▍        | 329/2248 [00:47<10:00,  3.20it/s]
 15%|█▍        | 332/2248 [00:48<07:43,  4.14it/s]
 15%|█▍        | 333/2248 [00:48<07:39,  4.17it/s]
 15%|█▍        | 336/2248 [00:48<04:49,  6.61it/s]
 15%|█▌        | 339/2248 [00:49<05:01,  6.32it/s]
 15%|█▌        | 340/2248 [00:49<04:47,  6.64it/s]
 15%|█▌        | 342/2248 [00:49<03:48,  8.34it/s]
 15%|█▌        | 344/2248 [00:50<06:26,  4.92it/s]
 15%|█▌        | 345/2248 [00:50<07:16,  4.36it/s]
 15%|█▌        | 346/2248 [00:50<07:28,  4.24it/s]
 15%|█▌        | 347/2248 [00:51<08:19,  3.81it/s]
 15%|█▌        | 348/2248 [00:51<08:56,  3.54it/s]
 16%|█▌        | 349/2248 [00:51<09:05,  3.48it/s]
 16%|█▌        | 350/2248 [00:51<08:05,  3.91it/s]
 16%|█▌        | 352/2248 [00:51<05:25,  5.83it/s]
 16%|█▌        | 353/2248 [00:52<08:21,  3.78it/s]
 16%|█▌        | 354/2248 [00:52<09:45,  3.23it/s]
 16%|█▌        | 355/2248 [00:53<11:47,  2.68it/s]
 16%|█▌        | 356/2248 [00:54<13:16,  2.38it/s]
 16%|█▌        | 359/2248 [00:54<06:56,  4.54it/s]
 16%|█▌        | 362/2248 [00:54<05:47,  5.42it/s]
 16%|█▌        | 364/2248 [00:55<06:27,  4.86it/s]
 16%|█▋        | 366/2248 [00:55<06:31,  4.81it/s]
 16%|█▋        | 367/2248 [00:56<08:03,  3.89it/s]
 16%|█▋        | 369/2248 [00:56<06:07,  5.11it/s]
 17%|█▋        | 371/2248 [00:56<06:59,  4.48it/s]
 17%|█▋        | 373/2248 [00:57<07:18,  4.28it/s]
 17%|█▋        | 376/2248 [00:57<04:49,  6.47it/s]
 17%|█▋        | 378/2248 [00:57<05:30,  5.67it/s]
 17%|█▋        | 382/2248 [00:57<03:26,  9.04it/s]
 17%|█▋        | 384/2248 [00:58<04:19,  7.19it/s]
 17%|█▋        | 386/2248 [00:58<05:20,  5.81it/s]
 17%|█▋        | 388/2248 [00:59<06:20,  4.88it/s]
 17%|█▋        | 389/2248 [00:59<07:08,  4.34it/s]
 17%|█▋        | 390/2248 [01:00<08:20,  3.71it/s]
 17%|█▋        | 391/2248 [01:01<11:05,  2.79it/s]
 17%|█▋        | 392/2248 [01:01<10:22,  2.98it/s]
 17%|█▋        | 393/2248 [01:01<09:52,  3.13it/s]
 18%|█▊        | 394/2248 [01:02<10:49,  2.86it/s]
 18%|█▊        | 395/2248 [01:02<10:35,  2.92it/s]
 18%|█▊        | 397/2248 [01:02<06:50,  4.51it/s]
 18%|█▊        | 400/2248 [01:02<04:17,  7.17it/s]
 18%|█▊        | 405/2248 [01:02<02:30, 12.26it/s]
 18%|█▊        | 410/2248 [01:02<01:41, 18.07it/s]
 19%|█▊        | 416/2248 [01:03<01:17, 23.79it/s]
 19%|█▊        | 420/2248 [01:03<01:15, 24.31it/s]
 19%|█▉        | 426/2248 [01:03<01:02, 28.95it/s]
 19%|█▉        | 431/2248 [01:03<01:28, 20.53it/s]
 19%|█▉        | 434/2248 [01:03<01:24, 21.59it/s]
 19%|█▉        | 437/2248 [01:04<03:16,  9.23it/s]
 20%|█▉        | 439/2248 [01:05<04:15,  7.08it/s]
 20%|█▉        | 441/2248 [01:05<04:46,  6.32it/s]
 20%|█▉        | 444/2248 [01:06<05:08,  5.84it/s]
 20%|█▉        | 446/2248 [01:06<05:35,  5.37it/s]
 20%|█▉        | 449/2248 [01:06<04:08,  7.24it/s]
 20%|██        | 451/2248 [01:07<04:44,  6.31it/s]
 20%|██        | 453/2248 [01:08<05:47,  5.16it/s]
 20%|██        | 455/2248 [01:08<06:33,  4.56it/s]
 20%|██        | 457/2248 [01:09<06:58,  4.27it/s]
 20%|██        | 459/2248 [01:09<07:48,  3.81it/s]
 20%|██        | 460/2248 [01:10<09:12,  3.24it/s]
 21%|██        | 462/2248 [01:10<06:42,  4.44it/s]
 21%|██        | 463/2248 [01:10<07:52,  3.78it/s]
 21%|██        | 464/2248 [01:11<09:40,  3.07it/s]
 21%|██        | 467/2248 [01:11<05:34,  5.32it/s]
 21%|██        | 471/2248 [01:12<04:26,  6.66it/s]
 21%|██        | 473/2248 [01:12<06:07,  4.82it/s]
 21%|██        | 475/2248 [01:13<06:47,  4.35it/s]
 21%|██        | 476/2248 [01:13<07:58,  3.71it/s]
 21%|██        | 477/2248 [01:14<08:14,  3.58it/s]
 21%|██▏       | 478/2248 [01:14<09:00,  3.27it/s]
 21%|██▏       | 479/2248 [01:14<09:50,  3.00it/s]
 21%|██▏       | 480/2248 [01:15<09:26,  3.12it/s]
 21%|██▏       | 481/2248 [01:15<09:01,  3.26it/s]
 21%|██▏       | 482/2248 [01:15<08:44,  3.37it/s]
 22%|██▏       | 484/2248 [01:15<05:35,  5.25it/s]
 22%|██▏       | 485/2248 [01:16<05:22,  5.46it/s]
 22%|██▏       | 486/2248 [01:16<04:53,  6.01it/s]
 22%|██▏       | 487/2248 [01:16<05:13,  5.61it/s]
 22%|██▏       | 489/2248 [01:16<03:44,  7.82it/s]
 22%|██▏       | 490/2248 [01:16<05:17,  5.53it/s]
 22%|██▏       | 493/2248 [01:16<03:12,  9.11it/s]
 22%|██▏       | 495/2248 [01:17<03:57,  7.39it/s]
 22%|██▏       | 497/2248 [01:17<03:10,  9.18it/s]
 22%|██▏       | 499/2248 [01:17<04:16,  6.81it/s]
 22%|██▏       | 501/2248 [01:18<04:49,  6.04it/s]
 22%|██▏       | 504/2248 [01:18<03:20,  8.70it/s]
 23%|██▎       | 509/2248 [01:18<02:56,  9.83it/s]
 23%|██▎       | 511/2248 [01:19<02:39, 10.87it/s]
 23%|██▎       | 513/2248 [01:19<04:31,  6.40it/s]
 23%|██▎       | 515/2248 [01:20<05:15,  5.50it/s]
 23%|██▎       | 518/2248 [01:20<05:02,  5.71it/s]
 23%|██▎       | 519/2248 [01:21<05:45,  5.01it/s]
 23%|██▎       | 521/2248 [01:21<04:37,  6.23it/s]
 23%|██▎       | 526/2248 [01:21<02:35, 11.10it/s]
 23%|██▎       | 528/2248 [01:21<02:28, 11.58it/s]
 24%|██▎       | 530/2248 [01:21<02:35, 11.01it/s]
 24%|██▍       | 534/2248 [01:21<02:18, 12.36it/s]
 24%|██▍       | 536/2248 [01:22<02:13, 12.85it/s]
 24%|██▍       | 539/2248 [01:22<01:49, 15.58it/s]
 24%|██▍       | 545/2248 [01:22<01:12, 23.55it/s]
 25%|██▍       | 551/2248 [01:22<01:03, 26.65it/s]
 25%|██▍       | 555/2248 [01:22<01:23, 20.21it/s]
 25%|██▍       | 560/2248 [01:22<01:06, 25.22it/s]
 25%|██▌       | 567/2248 [01:23<00:50, 33.57it/s]
 25%|██▌       | 572/2248 [01:23<02:10, 12.87it/s]
 26%|██▌       | 576/2248 [01:25<03:35,  7.75it/s]
 26%|██▌       | 579/2248 [01:25<03:45,  7.40it/s]
 26%|██▌       | 581/2248 [01:26<04:11,  6.62it/s]
 26%|██▌       | 583/2248 [01:26<04:42,  5.90it/s]
 26%|██▌       | 585/2248 [01:27<05:41,  4.87it/s]
 26%|██▌       | 586/2248 [01:27<06:50,  4.05it/s]
 26%|██▌       | 588/2248 [01:28<07:01,  3.94it/s]
 26%|██▌       | 589/2248 [01:28<06:41,  4.13it/s]
 26%|██▋       | 592/2248 [01:28<05:53,  4.68it/s]
 26%|██▋       | 595/2248 [01:29<04:07,  6.67it/s]
 27%|██▋       | 599/2248 [01:29<03:37,  7.58it/s]
 27%|██▋       | 601/2248 [01:30<04:38,  5.91it/s]
 27%|██▋       | 603/2248 [01:30<05:20,  5.14it/s]
 27%|██▋       | 604/2248 [01:31<06:10,  4.43it/s]
 27%|██▋       | 605/2248 [01:31<07:10,  3.81it/s]
 27%|██▋       | 606/2248 [01:31<07:18,  3.74it/s]
 27%|██▋       | 607/2248 [01:31<06:23,  4.28it/s]
 27%|██▋       | 608/2248 [01:32<07:09,  3.82it/s]
 27%|██▋       | 609/2248 [01:32<06:04,  4.49it/s]
 27%|██▋       | 610/2248 [01:32<06:14,  4.38it/s]
 27%|██▋       | 612/2248 [01:32<04:25,  6.16it/s]
 27%|██▋       | 613/2248 [01:32<04:03,  6.71it/s]
 27%|██▋       | 615/2248 [01:32<02:58,  9.17it/s]
 28%|██▊       | 619/2248 [01:33<01:47, 15.17it/s]
 28%|██▊       | 622/2248 [01:33<01:45, 15.44it/s]
 28%|██▊       | 624/2248 [01:33<01:45, 15.34it/s]
 28%|██▊       | 626/2248 [01:33<02:07, 12.77it/s]
 28%|██▊       | 628/2248 [01:33<01:55, 14.02it/s]
 28%|██▊       | 633/2248 [01:33<01:15, 21.31it/s]
 28%|██▊       | 640/2248 [01:33<00:50, 31.79it/s]
 29%|██▊       | 644/2248 [01:34<00:52, 30.75it/s]
 29%|██▉       | 648/2248 [01:34<01:01, 26.18it/s]
 29%|██▉       | 651/2248 [01:35<02:16, 11.69it/s]
 29%|██▉       | 654/2248 [01:36<04:09,  6.40it/s]
 29%|██▉       | 658/2248 [01:36<03:41,  7.17it/s]
 29%|██▉       | 660/2248 [01:36<04:06,  6.45it/s]
 29%|██▉       | 662/2248 [01:37<04:29,  5.88it/s]
 29%|██▉       | 663/2248 [01:37<05:27,  4.84it/s]
 30%|██▉       | 665/2248 [01:38<05:45,  4.58it/s]
 30%|██▉       | 667/2248 [01:38<06:23,  4.13it/s]
 30%|██▉       | 670/2248 [01:39<05:46,  4.55it/s]
 30%|██▉       | 673/2248 [01:39<04:08,  6.34it/s]
 30%|███       | 677/2248 [01:40<03:38,  7.20it/s]
 30%|███       | 680/2248 [01:40<02:53,  9.05it/s]
 30%|███       | 682/2248 [01:41<04:30,  5.78it/s]
 30%|███       | 684/2248 [01:42<06:32,  3.98it/s]
 30%|███       | 685/2248 [01:42<07:11,  3.62it/s]
 31%|███       | 686/2248 [01:42<07:18,  3.57it/s]
 31%|███       | 687/2248 [01:42<07:07,  3.65it/s]
 31%|███       | 688/2248 [01:43<07:11,  3.62it/s]
 31%|███       | 689/2248 [01:43<06:16,  4.15it/s]
 31%|███       | 691/2248 [01:43<06:18,  4.11it/s]
 31%|███       | 692/2248 [01:44<07:01,  3.69it/s]
 31%|███       | 694/2248 [01:44<06:30,  3.98it/s]
 31%|███       | 695/2248 [01:45<08:08,  3.18it/s]
 31%|███       | 697/2248 [01:45<05:35,  4.63it/s]
 31%|███       | 698/2248 [01:45<05:53,  4.38it/s]
 31%|███       | 699/2248 [01:45<05:57,  4.34it/s]
 31%|███       | 700/2248 [01:46<06:22,  4.05it/s]
 31%|███       | 702/2248 [01:46<06:03,  4.25it/s]
 31%|███▏      | 704/2248 [01:47<07:09,  3.59it/s]
 31%|███▏      | 706/2248 [01:47<06:44,  3.82it/s]
 32%|███▏      | 709/2248 [01:48<06:04,  4.22it/s]
 32%|███▏      | 711/2248 [01:48<06:13,  4.12it/s]
 32%|███▏      | 712/2248 [01:49<07:27,  3.43it/s]
 32%|███▏      | 713/2248 [01:49<08:41,  2.95it/s]
 32%|███▏      | 714/2248 [01:50<08:22,  3.05it/s]
 32%|███▏      | 715/2248 [01:50<09:42,  2.63it/s]
 32%|███▏      | 716/2248 [01:51<10:41,  2.39it/s]
 32%|███▏      | 717/2248 [01:51<10:13,  2.49it/s]
 32%|███▏      | 718/2248 [01:51<09:41,  2.63it/s]
 32%|███▏      | 719/2248 [01:52<10:02,  2.54it/s]
 32%|███▏      | 720/2248 [01:52<09:17,  2.74it/s]
 32%|███▏      | 723/2248 [01:53<05:49,  4.36it/s]
 32%|███▏      | 725/2248 [01:53<05:27,  4.65it/s]
 32%|███▏      | 726/2248 [01:53<06:01,  4.21it/s]
 32%|███▏      | 727/2248 [01:54<05:57,  4.26it/s]
 32%|███▏      | 728/2248 [01:54<06:42,  3.78it/s]
 32%|███▏      | 729/2248 [01:54<06:37,  3.83it/s]
 32%|███▏      | 730/2248 [01:54<05:53,  4.30it/s]
 33%|███▎      | 731/2248 [01:55<07:40,  3.30it/s]
 33%|███▎      | 732/2248 [01:55<08:50,  2.86it/s]
 33%|███▎      | 733/2248 [01:56<09:45,  2.59it/s]
 33%|███▎      | 734/2248 [01:56<08:03,  3.13it/s]
 33%|███▎      | 735/2248 [01:56<09:54,  2.55it/s]
 33%|███▎      | 736/2248 [01:57<10:26,  2.41it/s]
 33%|███▎      | 737/2248 [01:57<10:19,  2.44it/s]
 33%|███▎      | 738/2248 [01:57<08:19,  3.02it/s]
 33%|███▎      | 739/2248 [01:58<06:47,  3.70it/s]
 33%|███▎      | 742/2248 [01:58<04:12,  5.97it/s]
 33%|███▎      | 743/2248 [01:58<06:00,  4.17it/s]
 33%|███▎      | 744/2248 [01:59<07:00,  3.58it/s]
 33%|███▎      | 748/2248 [01:59<03:24,  7.33it/s]
 33%|███▎      | 750/2248 [01:59<03:54,  6.38it/s]
 33%|███▎      | 752/2248 [02:00<05:56,  4.20it/s]
 34%|███▎      | 754/2248 [02:01<06:08,  4.06it/s]
 34%|███▎      | 757/2248 [02:01<04:06,  6.05it/s]
 34%|███▍      | 759/2248 [02:01<03:34,  6.95it/s]
 34%|███▍      | 761/2248 [02:01<04:22,  5.68it/s]
 34%|███▍      | 763/2248 [02:02<04:47,  5.16it/s]
 34%|███▍      | 766/2248 [02:02<03:36,  6.83it/s]
 34%|███▍      | 768/2248 [02:03<04:16,  5.78it/s]
 34%|███▍      | 772/2248 [02:03<03:36,  6.81it/s]
 34%|███▍      | 773/2248 [02:04<04:31,  5.43it/s]
 34%|███▍      | 774/2248 [02:04<05:07,  4.79it/s]
 34%|███▍      | 775/2248 [02:04<05:29,  4.48it/s]
 35%|███▍      | 776/2248 [02:04<05:51,  4.18it/s]
 35%|███▍      | 778/2248 [02:05<05:32,  4.43it/s]
 35%|███▍      | 781/2248 [02:05<03:39,  6.68it/s]
 35%|███▍      | 782/2248 [02:05<04:33,  5.35it/s]
 35%|███▍      | 783/2248 [02:06<05:18,  4.60it/s]
 35%|███▍      | 784/2248 [02:06<05:56,  4.11it/s]
 35%|███▍      | 786/2248 [02:06<05:17,  4.61it/s]
 35%|███▌      | 788/2248 [02:07<03:59,  6.10it/s]
 35%|███▌      | 791/2248 [02:07<03:57,  6.14it/s]
 35%|███▌      | 792/2248 [02:07<04:55,  4.93it/s]
 35%|███▌      | 794/2248 [02:08<05:07,  4.73it/s]
 35%|███▌      | 797/2248 [02:08<04:38,  5.21it/s]
 36%|███▌      | 800/2248 [02:09<04:24,  5.47it/s]
 36%|███▌      | 803/2248 [02:09<03:13,  7.46it/s]
 36%|███▌      | 806/2248 [02:09<03:12,  7.50it/s]
 36%|███▌      | 809/2248 [02:10<02:30,  9.56it/s]
 36%|███▌      | 811/2248 [02:10<04:15,  5.63it/s]
 36%|███▌      | 813/2248 [02:11<04:29,  5.33it/s]
 36%|███▋      | 815/2248 [02:11<04:28,  5.34it/s]
 36%|███▋      | 816/2248 [02:11<04:44,  5.04it/s]
 36%|███▋      | 818/2248 [02:12<04:00,  5.94it/s]
 37%|███▋      | 821/2248 [02:12<02:51,  8.30it/s]
 37%|███▋      | 824/2248 [02:12<02:11, 10.81it/s]
 37%|███▋      | 827/2248 [02:12<01:45, 13.51it/s]
 37%|███▋      | 830/2248 [02:12<01:32, 15.38it/s]
 37%|███▋      | 832/2248 [02:12<01:45, 13.44it/s]
 37%|███▋      | 835/2248 [02:12<01:27, 16.14it/s]
 37%|███▋      | 840/2248 [02:13<01:23, 16.78it/s]
 37%|███▋      | 842/2248 [02:13<01:27, 16.10it/s]
 38%|███▊      | 846/2248 [02:13<01:09, 20.13it/s]
 38%|███▊      | 851/2248 [02:13<00:59, 23.39it/s]
 38%|███▊      | 854/2248 [02:13<01:11, 19.60it/s]
 38%|███▊      | 857/2248 [02:14<01:11, 19.49it/s]
 38%|███▊      | 860/2248 [02:14<01:08, 20.14it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 308.96it/s]

[[np.int64(0), False, 1], [np.int64(2), False, 7], [np.int64(3), False, 0], [np.int64(4), False, 0], [np.int64(5), False, 10], [np.int64(6), False, 5], [np.int64(7), False, 13], [np.int64(8), False, 3], [np.int64(9), False, 12], [np.int64(11), False, 10]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8346, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [14:17<2:50:33, 103.37s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [14:17<1:58:15, 72.40s/it]

tensor(12.8904, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7946, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9393, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9352, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [14:18<39:26, 24.91s/it]

tensor(12.9868, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0300, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2305, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0143, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0339, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5907, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [14:18<19:00, 12.27s/it]

tensor(13.0032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0377, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6179, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9837, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0419, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9580, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [14:18<09:12,  6.07s/it]

tensor(12.9679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0459, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2363, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9698, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0495, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3962, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [14:18<04:29,  3.03s/it]

tensor(12.9930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0518, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4388, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0228, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0532, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4672, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [14:19<02:14,  1.55s/it]

tensor(13.0268, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0538, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0047, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0538, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4539, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [14:19<01:09,  1.22it/s]

tensor(12.9766, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0531, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4722, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0523, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5014, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [14:19<00:38,  2.18it/s]

tensor(12.9632, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0511, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5070, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9673, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0498, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5167, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [14:19<00:22,  3.52it/s]

tensor(12.9597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0482, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5254, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9434, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0461, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5378, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [14:20<00:15,  5.02it/s]

tensor(12.9312, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0439, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5500, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9260, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0415, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5539, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [14:20<00:12,  6.40it/s]

tensor(12.9254, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0390, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5641, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9247, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0362, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5741, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [14:20<00:10,  7.37it/s]

tensor(12.9195, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5755, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9105, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5877, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [14:20<00:09,  7.93it/s]

tensor(12.9010, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0305, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6081, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8934, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0295, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6236, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [14:20<00:08,  8.22it/s]

tensor(12.8879, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8846, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0283, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6465, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [14:21<00:08,  8.37it/s]

tensor(12.8838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6512, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6509, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [14:21<00:07,  8.38it/s]

tensor(12.8812, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6570, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8776, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6632, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [14:21<00:07,  8.55it/s]

tensor(12.8718, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6653, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8665, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6490, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [14:21<00:07,  8.49it/s]

tensor(12.8636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6478, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8624, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6451, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [14:22<00:07,  8.58it/s]

tensor(12.8621, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6543, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6580, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [14:22<00:06,  8.57it/s]

tensor(12.8582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6612, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6628, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [14:22<00:06,  8.60it/s]

tensor(12.8516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6631, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8495, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6647, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [14:22<00:06,  8.59it/s]

tensor(12.8479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6599, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8462, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6536, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [14:23<00:06,  8.51it/s]

tensor(12.8438, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6485, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8410, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6427, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [14:23<00:06,  8.37it/s]

tensor(12.8385, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6394, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6367, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [14:23<00:05,  8.42it/s]

tensor(12.8355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6368, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([182, 282,  70, 230, 137, 188, 213, 169, 254, 194, 137, 108,  61,  23])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:25, 26.36it/s]
  0%|          | 9/2248 [00:00<00:50, 44.70it/s]
  1%|          | 15/2248 [00:00<00:44, 49.77it/s]
  1%|          | 21/2248 [00:00<00:41, 53.47it/s]
  1%|          | 27/2248 [00:00<00:41, 53.86it/s]
  2%|▏         | 34/2248 [00:00<00:39, 56.65it/s]
  2%|▏         | 41/2248 [00:00<00:37, 59.07it/s]
  2%|▏         | 47/2248 [00:00<00:39, 55.79it/s]
  2%|▏         | 54/2248 [00:00<00:38, 57.26it/s]
  3%|▎         | 60/2248 [00:01<00:39, 55.56it/s]
  3%|▎         | 66/2248 [00:01<00:49, 44.20it/s]
  3%|▎         | 71/2248 [00:01<00:48, 45.16it/s]
  3%|▎         | 78/2248 [00:01<00:44, 48.35it/s]
  4%|▎         | 84/2248 [00:01<00:43, 49.44it/s]
  4%|▍         | 90/2248 [00:01<00:43, 49.21it/s]
  4%|▍         | 96/2248 [00:01<00:42, 51.23it/s]
  5%|▍         | 102/2248 [00:02<00:43, 49.45it/s]
  5%|▍         | 108/2248 [00:02<01:08, 31.34it/s]
  5%|▌         | 114/2248 [00:02<00:59, 36.05it/s]
  5%|▌         | 119/2248 [00:02<01:25, 24.97it/s]
  5%|▌         | 123/2248 [00:03<01:29, 23.75it/s]
  6%|▌         | 127/2248 [00:03<02:08, 16.51it/s]
  6%|▌         | 130/2248 [00:03<02:19, 15.15it/s]
  6%|▌         | 134/2248 [00:03<01:56, 18.19it/s]
  6%|▌         | 137/2248 [00:04<02:02, 17.18it/s]
  6%|▌         | 140/2248 [00:04<02:11, 15.99it/s]
  6%|▋         | 143/2248 [00:04<01:57, 17.86it/s]
  6%|▋         | 146/2248 [00:04<01:58, 17.75it/s]
  7%|▋         | 151/2248 [00:04<01:38, 21.37it/s]
  7%|▋         | 154/2248 [00:05<02:05, 16.72it/s]
  7%|▋         | 157/2248 [00:05<02:09, 16.19it/s]
  7%|▋         | 159/2248 [00:05<02:29, 13.99it/s]
  7%|▋         | 162/2248 [00:05<02:31, 13.81it/s]
  7%|▋         | 165/2248 [00:05<02:32, 13.66it/s]
  7%|▋         | 167/2248 [00:06<02:25, 14.27it/s]
  8%|▊         | 169/2248 [00:06<02:57, 11.73it/s]
  8%|▊         | 171/2248 [00:06<02:45, 12.55it/s]
  8%|▊         | 173/2248 [00:06<02:44, 12.58it/s]
  8%|▊         | 175/2248 [00:06<02:41, 12.85it/s]
  8%|▊         | 177/2248 [00:06<02:29, 13.87it/s]
  8%|▊         | 180/2248 [00:06<02:06, 16.33it/s]
  8%|▊         | 183/2248 [00:07<02:26, 14.06it/s]
  8%|▊         | 185/2248 [00:07<02:23, 14.33it/s]
  8%|▊         | 187/2248 [00:07<02:49, 12.18it/s]
  8%|▊         | 189/2248 [00:07<03:35,  9.54it/s]
  8%|▊         | 191/2248 [00:08<03:04, 11.17it/s]
  9%|▊         | 193/2248 [00:08<02:53, 11.88it/s]
  9%|▉         | 197/2248 [00:08<02:07, 16.09it/s]
  9%|▉         | 200/2248 [00:08<01:48, 18.91it/s]
  9%|▉         | 203/2248 [00:08<02:17, 14.84it/s]
  9%|▉         | 205/2248 [00:08<02:40, 12.71it/s]
  9%|▉         | 207/2248 [00:09<03:14, 10.52it/s]
  9%|▉         | 209/2248 [00:09<03:34,  9.50it/s]
  9%|▉         | 211/2248 [00:09<04:00,  8.46it/s]
  9%|▉         | 212/2248 [00:09<04:09,  8.16it/s]
 10%|▉         | 215/2248 [00:10<02:57, 11.45it/s]
 10%|▉         | 221/2248 [00:10<01:40, 20.13it/s]
 10%|█         | 226/2248 [00:10<01:18, 25.69it/s]
 10%|█         | 232/2248 [00:10<01:02, 32.32it/s]
 11%|█         | 239/2248 [00:10<00:50, 40.00it/s]
 11%|█         | 245/2248 [00:10<00:45, 44.30it/s]
 11%|█         | 251/2248 [00:10<00:41, 48.32it/s]
 11%|█▏        | 258/2248 [00:10<00:37, 52.79it/s]
 12%|█▏        | 264/2248 [00:11<00:57, 34.68it/s]
 12%|█▏        | 269/2248 [00:11<01:22, 23.93it/s]
 12%|█▏        | 273/2248 [00:11<01:23, 23.66it/s]
 12%|█▏        | 277/2248 [00:11<01:23, 23.50it/s]
 12%|█▎        | 281/2248 [00:12<01:15, 26.11it/s]
 13%|█▎        | 285/2248 [00:12<01:29, 21.86it/s]
 13%|█▎        | 288/2248 [00:12<01:57, 16.73it/s]
 13%|█▎        | 291/2248 [00:12<02:00, 16.29it/s]
 13%|█▎        | 293/2248 [00:12<01:59, 16.38it/s]
 13%|█▎        | 296/2248 [00:13<01:44, 18.61it/s]
 13%|█▎        | 299/2248 [00:13<02:11, 14.84it/s]
 13%|█▎        | 301/2248 [00:13<02:06, 15.45it/s]
 13%|█▎        | 303/2248 [00:13<02:53, 11.23it/s]
 14%|█▎        | 305/2248 [00:14<03:13, 10.05it/s]
 14%|█▎        | 307/2248 [00:14<03:37,  8.94it/s]
 14%|█▎        | 309/2248 [00:14<03:44,  8.65it/s]
 14%|█▍        | 312/2248 [00:14<03:29,  9.23it/s]
 14%|█▍        | 314/2248 [00:15<03:53,  8.27it/s]
 14%|█▍        | 316/2248 [00:15<03:20,  9.63it/s]
 14%|█▍        | 318/2248 [00:15<03:29,  9.20it/s]
 14%|█▍        | 320/2248 [00:15<03:04, 10.46it/s]
 14%|█▍        | 322/2248 [00:15<02:39, 12.10it/s]
 14%|█▍        | 324/2248 [00:15<02:25, 13.18it/s]
 15%|█▍        | 326/2248 [00:16<02:41, 11.90it/s]
 15%|█▍        | 328/2248 [00:16<03:32,  9.04it/s]
 15%|█▍        | 330/2248 [00:16<03:13,  9.92it/s]
 15%|█▍        | 332/2248 [00:16<02:52, 11.12it/s]
 15%|█▍        | 336/2248 [00:16<01:59, 16.01it/s]
 15%|█▌        | 339/2248 [00:16<01:46, 17.97it/s]
 15%|█▌        | 342/2248 [00:17<01:51, 17.10it/s]
 15%|█▌        | 344/2248 [00:17<03:01, 10.47it/s]
 15%|█▌        | 346/2248 [00:18<04:05,  7.74it/s]
 15%|█▌        | 348/2248 [00:18<04:44,  6.68it/s]
 16%|█▌        | 349/2248 [00:18<05:15,  6.01it/s]
 16%|█▌        | 350/2248 [00:18<05:09,  6.13it/s]
 16%|█▌        | 352/2248 [00:18<04:02,  7.80it/s]
 16%|█▌        | 354/2248 [00:19<03:56,  8.01it/s]
 16%|█▌        | 355/2248 [00:19<03:59,  7.89it/s]
 16%|█▌        | 356/2248 [00:19<04:35,  6.87it/s]
 16%|█▌        | 358/2248 [00:19<03:37,  8.71it/s]
 16%|█▌        | 362/2248 [00:19<02:42, 11.59it/s]
 16%|█▌        | 364/2248 [00:20<02:24, 13.06it/s]
 16%|█▋        | 367/2248 [00:20<02:22, 13.18it/s]
 16%|█▋        | 369/2248 [00:20<02:25, 12.87it/s]
 17%|█▋        | 371/2248 [00:20<02:30, 12.44it/s]
 17%|█▋        | 373/2248 [00:20<02:37, 11.90it/s]
 17%|█▋        | 375/2248 [00:20<02:30, 12.41it/s]
 17%|█▋        | 378/2248 [00:21<02:01, 15.43it/s]
 17%|█▋        | 382/2248 [00:21<01:41, 18.38it/s]
 17%|█▋        | 385/2248 [00:21<02:13, 13.93it/s]
 17%|█▋        | 387/2248 [00:21<02:20, 13.24it/s]
 17%|█▋        | 389/2248 [00:21<02:35, 11.99it/s]
 17%|█▋        | 391/2248 [00:22<02:52, 10.75it/s]
 17%|█▋        | 393/2248 [00:22<02:53, 10.72it/s]
 18%|█▊        | 395/2248 [00:22<03:25,  9.03it/s]
 18%|█▊        | 397/2248 [00:22<02:56, 10.50it/s]
 18%|█▊        | 404/2248 [00:22<01:28, 20.75it/s]
 18%|█▊        | 410/2248 [00:23<01:06, 27.53it/s]
 19%|█▊        | 416/2248 [00:23<00:59, 30.71it/s]
 19%|█▊        | 420/2248 [00:23<00:56, 32.30it/s]
 19%|█▉        | 424/2248 [00:23<00:55, 32.78it/s]
 19%|█▉        | 428/2248 [00:23<00:54, 33.56it/s]
 19%|█▉        | 432/2248 [00:23<01:00, 29.92it/s]
 19%|█▉        | 436/2248 [00:23<01:09, 25.95it/s]
 20%|█▉        | 439/2248 [00:24<01:38, 18.31it/s]
 20%|█▉        | 442/2248 [00:24<01:45, 17.08it/s]
 20%|█▉        | 445/2248 [00:24<01:41, 17.68it/s]
 20%|█▉        | 447/2248 [00:24<01:45, 17.11it/s]
 20%|█▉        | 449/2248 [00:24<01:49, 16.45it/s]
 20%|██        | 451/2248 [00:24<01:50, 16.27it/s]
 20%|██        | 453/2248 [00:25<01:58, 15.11it/s]
 20%|██        | 457/2248 [00:25<01:58, 15.13it/s]
 20%|██        | 459/2248 [00:25<02:24, 12.40it/s]
 21%|██        | 461/2248 [00:25<02:10, 13.66it/s]
 21%|██        | 463/2248 [00:25<02:25, 12.26it/s]
 21%|██        | 465/2248 [00:26<02:34, 11.55it/s]
 21%|██        | 467/2248 [00:26<02:21, 12.59it/s]
 21%|██        | 469/2248 [00:26<02:23, 12.37it/s]
 21%|██        | 471/2248 [00:26<02:18, 12.80it/s]
 21%|██        | 473/2248 [00:26<02:20, 12.59it/s]
 21%|██        | 475/2248 [00:27<03:01,  9.77it/s]
 21%|██        | 477/2248 [00:27<03:02,  9.68it/s]
 21%|██▏       | 479/2248 [00:27<03:29,  8.45it/s]
 21%|██▏       | 480/2248 [00:27<03:25,  8.59it/s]
 21%|██▏       | 481/2248 [00:27<04:06,  7.17it/s]
 22%|██▏       | 484/2248 [00:28<02:40, 10.99it/s]
 22%|██▏       | 486/2248 [00:28<02:24, 12.20it/s]
 22%|██▏       | 488/2248 [00:28<02:13, 13.18it/s]
 22%|██▏       | 490/2248 [00:28<02:08, 13.64it/s]
 22%|██▏       | 492/2248 [00:28<02:13, 13.18it/s]
 22%|██▏       | 495/2248 [00:28<01:45, 16.59it/s]
 22%|██▏       | 498/2248 [00:28<01:31, 19.04it/s]
 22%|██▏       | 501/2248 [00:28<01:23, 20.81it/s]
 22%|██▏       | 504/2248 [00:29<01:16, 22.89it/s]
 23%|██▎       | 509/2248 [00:29<01:09, 24.92it/s]
 23%|██▎       | 512/2248 [00:29<01:11, 24.17it/s]
 23%|██▎       | 515/2248 [00:29<01:26, 20.02it/s]
 23%|██▎       | 518/2248 [00:29<01:22, 20.97it/s]
 23%|██▎       | 521/2248 [00:29<01:35, 18.17it/s]
 23%|██▎       | 526/2248 [00:30<01:12, 23.90it/s]
 24%|██▎       | 532/2248 [00:30<00:54, 31.59it/s]
 24%|██▍       | 538/2248 [00:30<00:45, 37.71it/s]
 24%|██▍       | 544/2248 [00:30<00:43, 38.93it/s]
 24%|██▍       | 549/2248 [00:30<00:41, 40.82it/s]
 25%|██▍       | 554/2248 [00:30<00:42, 39.63it/s]
 25%|██▍       | 561/2248 [00:30<00:35, 46.87it/s]
 25%|██▌       | 566/2248 [00:30<00:42, 39.18it/s]
 25%|██▌       | 571/2248 [00:31<01:01, 27.21it/s]
 26%|██▌       | 575/2248 [00:31<01:43, 16.10it/s]
 26%|██▌       | 578/2248 [00:32<01:55, 14.47it/s]
 26%|██▌       | 581/2248 [00:32<02:07, 13.05it/s]
 26%|██▌       | 583/2248 [00:32<02:02, 13.63it/s]
 26%|██▌       | 585/2248 [00:32<01:58, 14.02it/s]
 26%|██▌       | 587/2248 [00:32<02:12, 12.50it/s]
 26%|██▌       | 589/2248 [00:32<02:06, 13.16it/s]
 26%|██▋       | 592/2248 [00:33<01:44, 15.87it/s]
 26%|██▋       | 595/2248 [00:33<01:38, 16.80it/s]
 27%|██▋       | 599/2248 [00:33<01:31, 18.10it/s]
 27%|██▋       | 601/2248 [00:33<02:00, 13.65it/s]
 27%|██▋       | 603/2248 [00:33<02:22, 11.58it/s]
 27%|██▋       | 605/2248 [00:34<02:21, 11.61it/s]
 27%|██▋       | 607/2248 [00:34<02:42, 10.07it/s]
 27%|██▋       | 609/2248 [00:34<03:02,  8.99it/s]
 27%|██▋       | 611/2248 [00:34<02:36, 10.45it/s]
 27%|██▋       | 614/2248 [00:34<01:58, 13.74it/s]
 28%|██▊       | 619/2248 [00:35<01:18, 20.86it/s]
 28%|██▊       | 625/2248 [00:35<00:55, 29.01it/s]
 28%|██▊       | 630/2248 [00:35<00:48, 33.66it/s]
 28%|██▊       | 635/2248 [00:35<00:42, 37.74it/s]
 29%|██▊       | 641/2248 [00:35<00:39, 40.50it/s]
 29%|██▉       | 647/2248 [00:35<00:36, 44.18it/s]
 29%|██▉       | 652/2248 [00:36<01:10, 22.76it/s]
 29%|██▉       | 656/2248 [00:36<01:20, 19.79it/s]
 29%|██▉       | 659/2248 [00:36<01:17, 20.53it/s]
 29%|██▉       | 662/2248 [00:36<01:47, 14.80it/s]
 30%|██▉       | 665/2248 [00:37<02:13, 11.82it/s]
 30%|██▉       | 667/2248 [00:37<02:16, 11.57it/s]
 30%|██▉       | 669/2248 [00:37<02:08, 12.25it/s]
 30%|██▉       | 673/2248 [00:37<01:44, 15.14it/s]
 30%|███       | 678/2248 [00:37<01:28, 17.64it/s]
 30%|███       | 681/2248 [00:38<01:21, 19.15it/s]
 30%|███       | 684/2248 [00:38<01:38, 15.85it/s]
 31%|███       | 687/2248 [00:38<01:28, 17.55it/s]
 31%|███       | 690/2248 [00:38<01:22, 18.86it/s]
 31%|███       | 693/2248 [00:38<01:42, 15.16it/s]
 31%|███       | 695/2248 [00:39<01:54, 13.51it/s]
 31%|███       | 697/2248 [00:39<01:51, 13.93it/s]
 31%|███       | 699/2248 [00:39<01:53, 13.62it/s]
 31%|███       | 702/2248 [00:39<01:43, 14.96it/s]
 31%|███▏      | 704/2248 [00:39<01:45, 14.66it/s]
 31%|███▏      | 707/2248 [00:39<01:30, 16.95it/s]
 32%|███▏      | 709/2248 [00:39<01:41, 15.13it/s]
 32%|███▏      | 711/2248 [00:40<01:36, 15.94it/s]
 32%|███▏      | 713/2248 [00:40<02:16, 11.27it/s]
 32%|███▏      | 715/2248 [00:40<02:43,  9.39it/s]
 32%|███▏      | 717/2248 [00:40<02:49,  9.02it/s]
 32%|███▏      | 721/2248 [00:41<02:20, 10.84it/s]
 32%|███▏      | 723/2248 [00:41<02:09, 11.73it/s]
 32%|███▏      | 726/2248 [00:41<01:48, 14.08it/s]
 32%|███▏      | 728/2248 [00:41<02:05, 12.11it/s]
 33%|███▎      | 731/2248 [00:41<01:52, 13.44it/s]
 33%|███▎      | 733/2248 [00:42<02:35,  9.72it/s]
 33%|███▎      | 735/2248 [00:42<02:33,  9.88it/s]
 33%|███▎      | 737/2248 [00:42<02:45,  9.14it/s]
 33%|███▎      | 739/2248 [00:42<02:21, 10.68it/s]
 33%|███▎      | 742/2248 [00:42<01:47, 13.98it/s]
 33%|███▎      | 744/2248 [00:43<01:48, 13.82it/s]
 33%|███▎      | 747/2248 [00:43<01:30, 16.67it/s]
 33%|███▎      | 750/2248 [00:43<01:16, 19.55it/s]
 33%|███▎      | 753/2248 [00:43<01:38, 15.15it/s]
 34%|███▎      | 757/2248 [00:43<01:17, 19.34it/s]
 34%|███▍      | 764/2248 [00:43<00:50, 29.28it/s]
 34%|███▍      | 769/2248 [00:43<00:44, 33.52it/s]
 34%|███▍      | 773/2248 [00:44<00:53, 27.63it/s]
 35%|███▍      | 777/2248 [00:44<01:20, 18.36it/s]
 35%|███▍      | 780/2248 [00:44<01:25, 17.21it/s]
 35%|███▍      | 783/2248 [00:45<01:58, 12.38it/s]
 35%|███▍      | 786/2248 [00:45<01:41, 14.37it/s]
 35%|███▌      | 789/2248 [00:45<01:40, 14.49it/s]
 35%|███▌      | 791/2248 [00:45<01:51, 13.11it/s]
 35%|███▌      | 793/2248 [00:46<02:10, 11.14it/s]
 35%|███▌      | 796/2248 [00:46<01:46, 13.62it/s]
 35%|███▌      | 798/2248 [00:46<02:16, 10.63it/s]
 36%|███▌      | 801/2248 [00:46<01:49, 13.21it/s]
 36%|███▌      | 805/2248 [00:46<01:23, 17.37it/s]
 36%|███▌      | 809/2248 [00:46<01:07, 21.24it/s]
 36%|███▌      | 812/2248 [00:47<01:23, 17.19it/s]
 36%|███▋      | 815/2248 [00:47<01:15, 18.93it/s]
 36%|███▋      | 818/2248 [00:47<01:07, 21.11it/s]
 37%|███▋      | 823/2248 [00:47<00:54, 26.09it/s]
 37%|███▋      | 827/2248 [00:47<00:50, 27.89it/s]
 37%|███▋      | 834/2248 [00:47<00:37, 37.38it/s]
 37%|███▋      | 839/2248 [00:47<00:38, 36.25it/s]
 38%|███▊      | 844/2248 [00:47<00:35, 39.36it/s]
 38%|███▊      | 851/2248 [00:48<00:32, 43.62it/s]
 38%|███▊      | 856/2248 [00:48<00:33, 41.05it/s]
 38%|███▊      | 861/2248 [00:48<00:37, 37.38it/s]
 39%|███▊      | 866/2248 [00:48<00:42, 32.48it/s]
 39%|███▊      | 870/2248 [00:48<00:48, 28.46it/s]
 39%|███▉      | 874/2248 [00:48<00:57, 23.80it/s]
 39%|███▉      | 877/2248 [00:49<01:11, 19.30it/s]
 39%|███▉      | 880/2248 [00:49<01:07, 20.19it/s]
 39%|███▉      | 883/2248 [00:49<01:03, 21.59it/s]
 39%|███▉      | 886/2248 [00:49<01:24, 16.08it/s]
 40%|███▉      | 888/2248 [00:50<01:39, 13.71it/s]
 40%|███▉      | 890/2248 [00:50<01:56, 11.68it/s]
 40%|███▉      | 893/2248 [00:50<01:34, 14.39it/s]
 40%|███▉      | 896/2248 [00:50<01:19, 17.09it/s]
 40%|███▉      | 899/2248 [00:50<01:13, 18.37it/s]
 40%|████      | 903/2248 [00:50<01:22, 16.24it/s]
 40%|████      | 906/2248 [00:51<01:31, 14.68it/s]
 40%|████      | 908/2248 [00:51<02:06, 10.63it/s]
 40%|████      | 910/2248 [00:51<02:12, 10.07it/s]
 41%|████      | 912/2248 [00:52<02:47,  7.98it/s]
 41%|████      | 914/2248 [00:52<02:25,  9.16it/s]
 41%|████      | 916/2248 [00:52<02:22,  9.32it/s]
 41%|████      | 919/2248 [00:52<02:19,  9.53it/s]
 41%|████      | 921/2248 [00:52<02:07, 10.40it/s]
 41%|████      | 924/2248 [00:53<01:52, 11.74it/s]
 41%|████      | 927/2248 [00:53<01:36, 13.69it/s]
 41%|████▏     | 931/2248 [00:53<01:13, 17.81it/s]
 42%|████▏     | 934/2248 [00:53<01:25, 15.43it/s]
 42%|████▏     | 937/2248 [00:53<01:16, 17.07it/s]
 42%|████▏     | 939/2248 [00:54<01:40, 12.97it/s]
 42%|████▏     | 941/2248 [00:54<02:02, 10.63it/s]
 42%|████▏     | 946/2248 [00:54<01:21, 15.99it/s]
 42%|████▏     | 949/2248 [00:54<01:22, 15.75it/s]
 42%|████▏     | 953/2248 [00:54<01:24, 15.41it/s]
 43%|████▎     | 956/2248 [00:55<01:36, 13.39it/s]
 43%|████▎     | 958/2248 [00:55<01:33, 13.81it/s]
 43%|████▎     | 960/2248 [00:55<02:19,  9.26it/s]
 43%|████▎     | 962/2248 [00:56<02:36,  8.23it/s]
 43%|████▎     | 964/2248 [00:56<02:19,  9.18it/s]
 43%|████▎     | 966/2248 [00:56<02:23,  8.93it/s]
 43%|████▎     | 969/2248 [00:56<02:15,  9.44it/s]
 43%|████▎     | 971/2248 [00:57<02:22,  8.94it/s]
 43%|████▎     | 973/2248 [00:57<02:04, 10.27it/s]
 43%|████▎     | 975/2248 [00:57<02:10,  9.78it/s]
 43%|████▎     | 977/2248 [00:57<02:12,  9.60it/s]
 44%|████▎     | 979/2248 [00:57<02:02, 10.35it/s]
 44%|████▎     | 981/2248 [00:58<02:07,  9.92it/s]
 44%|████▎     | 983/2248 [00:58<01:52, 11.25it/s]
 44%|████▍     | 985/2248 [00:58<01:54, 11.01it/s]
 44%|████▍     | 987/2248 [00:58<02:09,  9.72it/s]
 44%|████▍     | 990/2248 [00:58<01:39, 12.67it/s]
 44%|████▍     | 994/2248 [00:58<01:12, 17.28it/s]
 44%|████▍     | 998/2248 [00:59<01:18, 15.92it/s]
 44%|████▍     | 1000/2248 [00:59<01:32, 13.45it/s]
 45%|████▍     | 1002/2248 [00:59<01:30, 13.72it/s]
 45%|████▍     | 1004/2248 [00:59<01:34, 13.18it/s]
 45%|████▍     | 1006/2248 [00:59<01:50, 11.26it/s]
 45%|████▍     | 1008/2248 [01:00<02:23,  8.67it/s]
 45%|████▍     | 1010/2248 [01:00<02:20,  8.79it/s]
 45%|████▌     | 1015/2248 [01:00<01:24, 14.60it/s]
 45%|████▌     | 1021/2248 [01:00<00:55, 22.02it/s]
 46%|████▌     | 1028/2248 [01:00<00:39, 31.23it/s]
 46%|████▌     | 1034/2248 [01:01<00:34, 34.93it/s]
 46%|████▌     | 1039/2248 [01:01<00:36, 33.35it/s]
 46%|████▋     | 1043/2248 [01:01<00:34, 34.45it/s]
 47%|████▋     | 1047/2248 [01:01<00:37, 32.27it/s]
 47%|████▋     | 1053/2248 [01:01<00:31, 38.06it/s]
 47%|████▋     | 1058/2248 [01:02<01:16, 15.50it/s]
 47%|████▋     | 1062/2248 [01:02<01:22, 14.41it/s]
 47%|████▋     | 1065/2248 [01:02<01:13, 16.02it/s]
 48%|████▊     | 1069/2248 [01:02<01:00, 19.38it/s]
 48%|████▊     | 1072/2248 [01:03<01:16, 15.34it/s]
 48%|████▊     | 1076/2248 [01:03<01:05, 18.00it/s]
 48%|████▊     | 1079/2248 [01:03<01:01, 18.93it/s]
 48%|████▊     | 1083/2248 [01:03<00:58, 19.96it/s]
 48%|████▊     | 1086/2248 [01:03<01:15, 15.31it/s]
 48%|████▊     | 1088/2248 [01:04<01:32, 12.48it/s]
 48%|████▊     | 1090/2248 [01:04<02:14,  8.62it/s]
 49%|████▊     | 1092/2248 [01:05<02:21,  8.17it/s]
 49%|████▊     | 1094/2248 [01:05<02:04,  9.27it/s]
 49%|████▉     | 1096/2248 [01:05<01:48, 10.65it/s]
 49%|████▉     | 1098/2248 [01:05<01:35, 11.98it/s]
 49%|████▉     | 1101/2248 [01:05<01:14, 15.32it/s]
 49%|████▉     | 1108/2248 [01:05<00:44, 25.91it/s]
 49%|████▉     | 1112/2248 [01:05<00:39, 28.96it/s]
 50%|████▉     | 1119/2248 [01:05<00:29, 37.95it/s]
 50%|█████     | 1126/2248 [01:05<00:25, 44.54it/s]
 50%|█████     | 1131/2248 [01:06<00:25, 43.87it/s]
 51%|█████     | 1137/2248 [01:06<00:23, 46.68it/s]
 51%|█████     | 1142/2248 [01:06<00:33, 32.90it/s]
 51%|█████     | 1146/2248 [01:06<00:57, 19.10it/s]
 51%|█████     | 1150/2248 [01:07<01:04, 17.00it/s]
 51%|█████▏    | 1153/2248 [01:07<01:09, 15.67it/s]
 51%|█████▏    | 1156/2248 [01:07<01:11, 15.24it/s]
 52%|█████▏    | 1158/2248 [01:07<01:13, 14.73it/s]
 52%|█████▏    | 1160/2248 [01:08<01:22, 13.17it/s]
 52%|█████▏    | 1162/2248 [01:08<01:16, 14.27it/s]
 52%|█████▏    | 1164/2248 [01:08<01:17, 13.98it/s]
 52%|█████▏    | 1166/2248 [01:08<01:29, 12.14it/s]
 52%|█████▏    | 1169/2248 [01:08<01:18, 13.69it/s]
 52%|█████▏    | 1172/2248 [01:08<01:21, 13.14it/s]
 52%|█████▏    | 1175/2248 [01:09<01:21, 13.21it/s]
 52%|█████▏    | 1177/2248 [01:09<01:18, 13.71it/s]
 52%|█████▏    | 1179/2248 [01:09<01:37, 10.92it/s]
 53%|█████▎    | 1181/2248 [01:09<01:26, 12.39it/s]
 53%|█████▎    | 1183/2248 [01:09<01:23, 12.80it/s]
 53%|█████▎    | 1185/2248 [01:09<01:17, 13.76it/s]
 53%|█████▎    | 1187/2248 [01:10<01:37, 10.88it/s]
 53%|█████▎    | 1189/2248 [01:10<01:33, 11.31it/s]
 53%|█████▎    | 1191/2248 [01:10<01:25, 12.39it/s]
 53%|█████▎    | 1193/2248 [01:10<01:43, 10.17it/s]
 53%|█████▎    | 1195/2248 [01:10<01:38, 10.71it/s]
 53%|█████▎    | 1197/2248 [01:11<01:27, 12.03it/s]
 53%|█████▎    | 1202/2248 [01:11<00:55, 18.88it/s]
 54%|█████▎    | 1205/2248 [01:11<01:09, 15.00it/s]
 54%|█████▎    | 1208/2248 [01:11<01:05, 15.98it/s]
 54%|█████▍    | 1210/2248 [01:11<01:18, 13.21it/s]
 54%|█████▍    | 1212/2248 [01:12<01:29, 11.62it/s]
 54%|█████▍    | 1214/2248 [01:12<01:20, 12.90it/s]
 54%|█████▍    | 1216/2248 [01:12<01:22, 12.47it/s]
 54%|█████▍    | 1218/2248 [01:12<01:17, 13.36it/s]
 54%|█████▍    | 1221/2248 [01:12<01:01, 16.59it/s]
 54%|█████▍    | 1223/2248 [01:12<01:18, 13.04it/s]
 55%|█████▍    | 1226/2248 [01:13<01:24, 12.09it/s]
 55%|█████▍    | 1228/2248 [01:13<01:15, 13.43it/s]
 55%|█████▍    | 1230/2248 [01:13<01:27, 11.69it/s]
 55%|█████▍    | 1232/2248 [01:13<02:06,  8.03it/s]
 55%|█████▍    | 1234/2248 [01:14<01:49,  9.28it/s]
 55%|█████▍    | 1236/2248 [01:14<01:49,  9.26it/s]
 55%|█████▌    | 1239/2248 [01:14<01:22, 12.21it/s]
 55%|█████▌    | 1241/2248 [01:14<01:32, 10.85it/s]
 55%|█████▌    | 1244/2248 [01:14<01:30, 11.15it/s]
 55%|█████▌    | 1246/2248 [01:15<01:41,  9.87it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 311.32it/s]

[[np.int64(0), False, 6], [np.int64(1), False, 3], [np.int64(2), False, 8], [np.int64(3), False, 8], [np.int64(4), False, 0], [np.int64(5), False, 3], [np.int64(7), False, 6], [np.int64(9), False, 0], [np.int64(10), False, 6], [np.int64(11), False, 0], [np.int64(12), False, 0], [np.int64(13), False, 12]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7054, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [16:41<33:47, 41.38s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [16:41<23:12, 29.01s/it]

tensor(12.8520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4085, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8833, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0320, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6962, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [16:41<07:31, 10.03s/it]

tensor(12.9054, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0397, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5105, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0444, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9448, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [16:41<03:33,  4.97s/it]

tensor(12.9038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0473, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9726, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9065, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0494, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0937, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [16:42<01:42,  2.50s/it]

tensor(12.9095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0519, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1232, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9086, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0553, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1086, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [16:42<00:50,  1.28s/it]

tensor(12.9137, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0591, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6112, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0630, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8818, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [16:42<00:25,  1.46it/s]

tensor(12.9271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0685, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1409, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0748, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2203, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [16:42<00:13,  2.52it/s]

tensor(12.9351, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0794, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2120, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9416, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0800, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2319, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [16:43<00:08,  3.95it/s]

tensor(12.9402, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0777, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2809, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9348, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0733, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3477, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [16:43<00:05,  5.41it/s]

tensor(12.9266, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0688, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2753, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0653, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3018, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [16:43<00:04,  6.70it/s]

tensor(12.9062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0628, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3598, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0610, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3943, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [16:43<00:03,  7.56it/s]

tensor(12.9127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0591, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4210, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4296, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [16:43<00:03,  8.11it/s]

tensor(12.9077, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0552, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8981, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0538, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5043, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [16:44<00:02,  8.40it/s]

tensor(12.8888, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0525, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5243, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8831, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0513, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5340, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 279/300 [16:44<00:02,  8.45it/s]

tensor(12.8799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0499, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5424, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8774, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0482, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5514, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [16:44<00:02,  8.50it/s]

tensor(12.8732, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0460, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5478, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8686, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0434, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5565, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [16:44<00:01,  8.59it/s]

tensor(12.8635, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0407, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5641, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8587, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0379, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5709, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [16:45<00:01,  8.65it/s]

tensor(12.8550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5764, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8530, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5922, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [16:45<00:01,  8.60it/s]

tensor(12.8519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0321, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5950, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6006, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [16:45<00:01,  8.63it/s]

tensor(12.8471, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5956, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5929, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [16:45<00:01,  8.59it/s]

tensor(12.8402, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6001, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8367, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6013, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [16:46<00:00,  8.62it/s]

tensor(12.8343, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6038, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6061, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [16:46<00:00,  8.63it/s]

tensor(12.8318, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6036, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6030, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [16:46<00:00,  8.63it/s]

tensor(12.8284, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6156, device='cuda:0', grad_fn=<MulBackward0>)

100%|█████████▉| 299/300 [16:46<00:00,  8.63it/s]

tensor(12.8241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6147, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8224, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6112, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [16:46<00:00,  3.36s/it]

tensor(12.8213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0218, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.6121, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0020911693572998047
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 7
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.402319058108
NMI         : 0.433206058756
Runtime     : 1030.63 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed7

==============================================================================================================
PRAGA RUN | S2-E18 | seed=8
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 6.762e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:31,  9.38it/s]

tensor(16.1814, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1228, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(16.2020, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8066, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|▏         | 4/300 [00:00<00:30,  9.69it/s]

tensor(16.0955, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7185, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9839, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8361, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 6/300 [00:00<00:29,  9.92it/s]

tensor(15.8923, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1396, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8264, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6094, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7817, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2297, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 8/300 [00:00<00:29,  9.78it/s]

tensor(15.7554, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9870, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7364, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8666, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7241, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8566, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▎         | 11/300 [00:01<00:28, 10.03it/s]

tensor(15.7108, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9464, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6955, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6720, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3866, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:28, 10.04it/s]

tensor(15.6420, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6046, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1201, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▌         | 17/300 [00:01<00:27, 10.13it/s]

tensor(15.5619, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5796, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5174, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0929, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4751, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6541, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:27, 10.11it/s]

tensor(15.4374, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2595, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4027, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9032, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3699, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5837, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 23/300 [00:02<00:27, 10.12it/s]

tensor(15.3351, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2947, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2949, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0363, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2514, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8026, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:27, 10.18it/s]

tensor(15.2068, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5929, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1627, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4043, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1206, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2354, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|▉         | 29/300 [00:02<00:26, 10.10it/s]

tensor(15.0804, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0834, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0400, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9469, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 31/300 [00:03<00:26, 10.00it/s]

tensor(14.9985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9545, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7154, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:26,  9.95it/s]

tensor(14.9080, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6176, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8597, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5298, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4520, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 35/300 [00:03<00:26, 10.09it/s]

tensor(14.7581, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3824, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3207, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2665, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:25, 10.04it/s]

tensor(14.5970, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2185, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5405, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1766, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4830, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1406, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▎        | 41/300 [00:04<00:25, 10.02it/s]

tensor(14.4273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1106, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3739, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0853, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▍        | 44/300 [00:04<00:25,  9.97it/s]

tensor(14.3239, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0658, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2767, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0512, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2319, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0412, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 47/300 [00:04<00:25,  9.85it/s]

tensor(14.1909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0349, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▌        | 48/300 [00:04<00:25,  9.80it/s]

tensor(14.1235, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:05<00:25,  9.89it/s]

tensor(14.0601, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0241, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 52/300 [00:05<00:25,  9.90it/s]

tensor(13.9870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0327, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▊        | 56/300 [00:05<00:24,  9.89it/s]

tensor(13.8889, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8614, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0291, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 58/300 [00:05<00:24, 10.07it/s]

tensor(13.8109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0272, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7870, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 62/300 [00:06<00:23, 10.05it/s]

tensor(13.7381, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7125, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6865, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██▏       | 64/300 [00:06<00:23, 10.10it/s]

tensor(13.6602, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6083, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 68/300 [00:06<00:22, 10.16it/s]

tensor(13.5832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5590, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5357, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 70/300 [00:06<00:22, 10.15it/s]

tensor(13.5130, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▍       | 74/300 [00:07<00:22, 10.23it/s]

tensor(13.4477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4061, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 76/300 [00:07<00:21, 10.29it/s]

tensor(13.3860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3663, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3476, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 80/300 [00:07<00:21, 10.06it/s]

tensor(13.3292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3116, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 82/300 [00:08<00:21, 10.04it/s]

tensor(13.2942, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2609, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 84/300 [00:08<00:21, 10.07it/s]

tensor(13.2449, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2139, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 88/300 [00:08<00:21, 10.09it/s]

tensor(13.1990, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 90/300 [00:08<00:20, 10.06it/s]

tensor(13.1706, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1573, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1445, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 92/300 [00:09<00:20, 10.10it/s]

tensor(13.1321, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1201, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███▏      | 94/300 [00:09<00:20, 10.09it/s]

tensor(13.1088, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 96/300 [00:09<00:20,  9.98it/s]

tensor(13.0872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0771, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 100/300 [00:09<00:19, 10.06it/s]

tensor(13.0576, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([176, 465, 102, 141, 118, 107, 276, 151, 178,  92,  32, 231,  61, 118])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:25, 26.29it/s]
  0%|          | 7/2248 [00:00<01:16, 29.29it/s]
  0%|          | 10/2248 [00:00<01:42, 21.78it/s]
  1%|          | 13/2248 [00:00<01:39, 22.57it/s]
  1%|          | 19/2248 [00:00<01:08, 32.74it/s]
  1%|          | 24/2248 [00:00<00:59, 37.16it/s]
  1%|          | 28/2248 [00:00<01:00, 36.89it/s]
  2%|▏         | 34/2248 [00:00<00:52, 42.53it/s]
  2%|▏         | 39/2248 [00:01<01:32, 23.79it/s]
  2%|▏         | 45/2248 [00:01<01:14, 29.61it/s]
  2%|▏         | 51/2248 [00:01<01:02, 35.30it/s]
  3%|▎         | 58/2248 [00:01<00:51, 42.30it/s]
  3%|▎         | 64/2248 [00:01<00:59, 36.41it/s]
  3%|▎         | 70/2248 [00:02<00:53, 40.52it/s]
  3%|▎         | 75/2248 [00:02<01:21, 26.74it/s]
  4%|▎         | 79/2248 [00:02<01:57, 18.46it/s]
  4%|▎         | 82/2248 [00:03<02:00, 17.91it/s]
  4%|▍         | 85/2248 [00:03<02:39, 13.60it/s]
  4%|▍         | 87/2248 [00:03<03:15, 11.06it/s]
  4%|▍         | 89/2248 [00:04<03:50,  9.38it/s]
  4%|▍         | 91/2248 [00:04<04:52,  7.36it/s]
  4%|▍         | 93/2248 [00:05<05:27,  6.58it/s]
  4%|▍         | 95/2248 [00:05<06:24,  5.59it/s]
  4%|▍         | 97/2248 [00:05<06:20,  5.66it/s]
  4%|▍         | 99/2248 [00:06<06:09,  5.82it/s]
  4%|▍         | 100/2248 [00:06<07:09,  5.00it/s]
  5%|▍         | 102/2248 [00:06<05:39,  6.32it/s]
  5%|▍         | 103/2248 [00:06<06:45,  5.29it/s]
  5%|▍         | 104/2248 [00:07<06:39,  5.37it/s]
  5%|▍         | 107/2248 [00:07<04:09,  8.59it/s]
  5%|▍         | 111/2248 [00:07<03:33, 10.03it/s]
  5%|▌         | 113/2248 [00:07<03:44,  9.51it/s]
  5%|▌         | 115/2248 [00:07<03:22, 10.52it/s]
  5%|▌         | 117/2248 [00:08<06:20,  5.60it/s]
  5%|▌         | 118/2248 [00:08<06:10,  5.75it/s]
  5%|▌         | 119/2248 [00:09<06:05,  5.82it/s]
  5%|▌         | 120/2248 [00:09<06:09,  5.75it/s]
  5%|▌         | 122/2248 [00:09<05:35,  6.34it/s]
  6%|▌         | 124/2248 [00:09<04:19,  8.18it/s]
  6%|▌         | 126/2248 [00:10<07:28,  4.73it/s]
  6%|▌         | 127/2248 [00:10<08:02,  4.39it/s]
  6%|▌         | 128/2248 [00:11<09:36,  3.68it/s]
  6%|▌         | 132/2248 [00:11<04:51,  7.27it/s]
 33%|███▎      | 100/300 [00:24<00:19, 10.06it/s]]
  6%|▌         | 136/2248 [00:12<08:22,  4.20it/s]
  6%|▌         | 138/2248 [00:13<08:15,  4.26it/s]
  6%|▌         | 140/2248 [00:13<07:48,  4.50it/s]
  6%|▋         | 142/2248 [00:13<07:27,  4.71it/s]
  6%|▋         | 144/2248 [00:13<05:54,  5.94it/s]
  6%|▋         | 145/2248 [00:14<06:47,  5.16it/s]
  7%|▋         | 147/2248 [00:14<05:16,  6.64it/s]
  7%|▋         | 150/2248 [00:14<03:35,  9.73it/s]
  7%|▋         | 152/2248 [00:14<03:42,  9.43it/s]
  7%|▋         | 154/2248 [00:14<03:22, 10.37it/s]
  7%|▋         | 156/2248 [00:15<03:25, 10.18it/s]
  7%|▋         | 158/2248 [00:15<05:16,  6.61it/s]
  7%|▋         | 159/2248 [00:15<05:07,  6.80it/s]
  7%|▋         | 160/2248 [00:15<05:52,  5.92it/s]
  7%|▋         | 162/2248 [00:16<06:27,  5.38it/s]
  7%|▋         | 164/2248 [00:16<04:53,  7.11it/s]
  7%|▋         | 166/2248 [00:16<05:57,  5.82it/s]
  7%|▋         | 168/2248 [00:17<04:39,  7.45it/s]
  8%|▊         | 170/2248 [00:17<05:59,  5.77it/s]
  8%|▊         | 172/2248 [00:17<04:42,  7.34it/s]
  8%|▊         | 174/2248 [00:17<04:42,  7.34it/s]
  8%|▊         | 176/2248 [00:18<04:16,  8.09it/s]
  8%|▊         | 178/2248 [00:18<05:08,  6.72it/s]
  8%|▊         | 180/2248 [00:19<05:52,  5.87it/s]
  8%|▊         | 182/2248 [00:19<04:41,  7.33it/s]
  8%|▊         | 184/2248 [00:19<04:42,  7.32it/s]
  8%|▊         | 185/2248 [00:19<05:37,  6.11it/s]
  8%|▊         | 187/2248 [00:20<05:47,  5.93it/s]
  8%|▊         | 189/2248 [00:20<05:40,  6.05it/s]
  8%|▊         | 190/2248 [00:20<06:28,  5.29it/s]
  9%|▊         | 193/2248 [00:21<06:14,  5.48it/s]
  9%|▊         | 195/2248 [00:21<07:23,  4.63it/s]
  9%|▉         | 197/2248 [00:21<05:43,  5.96it/s]
  9%|▉         | 201/2248 [00:22<04:53,  6.98it/s]
  9%|▉         | 202/2248 [00:22<05:30,  6.18it/s]
  9%|▉         | 204/2248 [00:22<04:35,  7.42it/s]
  9%|▉         | 205/2248 [00:22<04:51,  7.00it/s]
  9%|▉         | 206/2248 [00:23<05:17,  6.42it/s]
  9%|▉         | 207/2248 [00:23<05:20,  6.36it/s]
  9%|▉         | 208/2248 [00:23<05:06,  6.67it/s]
  9%|▉         | 209/2248 [00:23<04:56,  6.87it/s]
  9%|▉         | 210/2248 [00:23<04:48,  7.07it/s]
  9%|▉         | 211/2248 [00:23<06:04,  5.58it/s]
  9%|▉         | 212/2248 [00:24<05:57,  5.69it/s]
 10%|▉         | 214/2248 [00:24<04:31,  7.50it/s]
 10%|▉         | 216/2248 [00:24<03:30,  9.67it/s]
 10%|▉         | 218/2248 [00:24<02:56, 11.52it/s]
 10%|▉         | 222/2248 [00:24<03:02, 11.11it/s]
 10%|▉         | 224/2248 [00:25<02:52, 11.76it/s]
 10%|█         | 226/2248 [00:25<02:37, 12.83it/s]
 10%|█         | 228/2248 [00:25<03:51,  8.74it/s]
 10%|█         | 231/2248 [00:25<02:52, 11.71it/s]
 10%|█         | 236/2248 [00:26<02:33, 13.10it/s]
 11%|█         | 238/2248 [00:26<02:32, 13.20it/s]
 11%|█         | 245/2248 [00:26<01:30, 22.20it/s]
 11%|█         | 249/2248 [00:26<01:57, 17.05it/s]
 11%|█         | 252/2248 [00:26<01:49, 18.18it/s]
 12%|█▏        | 260/2248 [00:26<01:09, 28.45it/s]
 12%|█▏        | 264/2248 [00:27<01:45, 18.78it/s]
 12%|█▏        | 267/2248 [00:27<02:39, 12.38it/s]
 12%|█▏        | 270/2248 [00:28<03:28,  9.48it/s]
 12%|█▏        | 272/2248 [00:28<03:10, 10.38it/s]
 12%|█▏        | 274/2248 [00:28<03:14, 10.16it/s]
 12%|█▏        | 276/2248 [00:28<03:04, 10.67it/s]
 12%|█▏        | 278/2248 [00:29<03:56,  8.33it/s]
 12%|█▏        | 280/2248 [00:29<04:11,  7.83it/s]
 13%|█▎        | 282/2248 [00:30<05:20,  6.13it/s]
 13%|█▎        | 283/2248 [00:30<05:02,  6.50it/s]
 13%|█▎        | 284/2248 [00:30<05:08,  6.37it/s]
 13%|█▎        | 286/2248 [00:30<05:30,  5.94it/s]
 13%|█▎        | 287/2248 [00:31<05:55,  5.52it/s]
 13%|█▎        | 289/2248 [00:31<04:22,  7.45it/s]
 13%|█▎        | 291/2248 [00:31<04:37,  7.06it/s]
 13%|█▎        | 292/2248 [00:31<05:18,  6.13it/s]
 13%|█▎        | 294/2248 [00:31<04:10,  7.80it/s]
 13%|█▎        | 295/2248 [00:32<04:53,  6.66it/s]
 13%|█▎        | 298/2248 [00:32<04:16,  7.60it/s]
 13%|█▎        | 299/2248 [00:32<04:35,  7.08it/s]
 13%|█▎        | 301/2248 [00:32<03:47,  8.56it/s]
 13%|█▎        | 302/2248 [00:32<04:43,  6.85it/s]
 13%|█▎        | 303/2248 [00:33<06:23,  5.08it/s]
 14%|█▎        | 304/2248 [00:33<06:03,  5.35it/s]
 14%|█▎        | 305/2248 [00:33<06:30,  4.97it/s]
 14%|█▎        | 306/2248 [00:33<06:19,  5.11it/s]
 14%|█▎        | 307/2248 [00:34<06:59,  4.62it/s]
 14%|█▎        | 308/2248 [00:34<06:55,  4.67it/s]
 14%|█▎        | 309/2248 [00:34<08:21,  3.86it/s]
 14%|█▍        | 311/2248 [00:34<05:38,  5.72it/s]
 14%|█▍        | 312/2248 [00:35<05:25,  5.94it/s]
 14%|█▍        | 313/2248 [00:35<06:52,  4.70it/s]
 14%|█▍        | 314/2248 [00:35<07:00,  4.60it/s]
 14%|█▍        | 315/2248 [00:36<08:38,  3.73it/s]
 14%|█▍        | 317/2248 [00:36<05:32,  5.80it/s]
 14%|█▍        | 320/2248 [00:36<05:34,  5.77it/s]
 14%|█▍        | 322/2248 [00:37<06:17,  5.11it/s]
 14%|█▍        | 323/2248 [00:37<07:54,  4.06it/s]
 14%|█▍        | 325/2248 [00:37<06:43,  4.76it/s]
 15%|█▍        | 327/2248 [00:38<05:51,  5.47it/s]
 15%|█▍        | 328/2248 [00:38<06:36,  4.85it/s]
 15%|█▍        | 329/2248 [00:38<06:04,  5.27it/s]
 15%|█▍        | 331/2248 [00:38<04:28,  7.13it/s]
 15%|█▍        | 332/2248 [00:38<04:38,  6.89it/s]
 15%|█▍        | 334/2248 [00:39<03:34,  8.91it/s]
 15%|█▍        | 336/2248 [00:39<02:56, 10.82it/s]
 15%|█▌        | 339/2248 [00:39<02:30, 12.69it/s]
 15%|█▌        | 341/2248 [00:39<02:48, 11.35it/s]
 15%|█▌        | 343/2248 [00:39<03:53,  8.15it/s]
 15%|█▌        | 345/2248 [00:40<05:36,  5.66it/s]
 15%|█▌        | 346/2248 [00:40<05:45,  5.50it/s]
 15%|█▌        | 347/2248 [00:41<06:12,  5.11it/s]
 15%|█▌        | 348/2248 [00:41<07:48,  4.06it/s]
 16%|█▌        | 349/2248 [00:41<08:58,  3.52it/s]
 16%|█▌        | 350/2248 [00:42<09:55,  3.19it/s]
 16%|█▌        | 352/2248 [00:42<06:44,  4.68it/s]
 16%|█▌        | 353/2248 [00:42<07:41,  4.11it/s]
 16%|█▌        | 354/2248 [00:42<07:00,  4.51it/s]
 16%|█▌        | 355/2248 [00:43<06:49,  4.63it/s]
 16%|█▌        | 356/2248 [00:43<06:30,  4.84it/s]
 16%|█▌        | 358/2248 [00:43<04:38,  6.78it/s]
 16%|█▌        | 362/2248 [00:43<03:08, 10.03it/s]
 16%|█▌        | 364/2248 [00:44<04:55,  6.37it/s]
 16%|█▋        | 366/2248 [00:44<05:44,  5.46it/s]
 16%|█▋        | 367/2248 [00:45<06:22,  4.92it/s]
 16%|█▋        | 369/2248 [00:45<06:11,  5.06it/s]
 17%|█▋        | 371/2248 [00:45<06:37,  4.72it/s]
 17%|█▋        | 373/2248 [00:46<06:18,  4.96it/s]
 17%|█▋        | 375/2248 [00:46<04:56,  6.32it/s]
 17%|█▋        | 377/2248 [00:46<05:43,  5.44it/s]
 17%|█▋        | 380/2248 [00:46<03:57,  7.86it/s]
 17%|█▋        | 384/2248 [00:47<03:20,  9.30it/s]
 17%|█▋        | 386/2248 [00:47<04:12,  7.37it/s]
 17%|█▋        | 388/2248 [00:48<05:13,  5.94it/s]
 17%|█▋        | 389/2248 [00:48<06:28,  4.78it/s]
 17%|█▋        | 390/2248 [00:49<07:07,  4.35it/s]
 17%|█▋        | 391/2248 [00:49<07:29,  4.14it/s]
 17%|█▋        | 392/2248 [00:49<08:50,  3.50it/s]
 17%|█▋        | 393/2248 [00:50<10:05,  3.06it/s]
 18%|█▊        | 394/2248 [00:50<11:00,  2.81it/s]
 18%|█▊        | 395/2248 [00:51<11:32,  2.68it/s]
 18%|█▊        | 398/2248 [00:51<06:03,  5.08it/s]
 18%|█▊        | 403/2248 [00:51<03:00, 10.20it/s]
 18%|█▊        | 409/2248 [00:51<01:49, 16.87it/s]
 18%|█▊        | 414/2248 [00:51<01:27, 20.96it/s]
 19%|█▊        | 418/2248 [00:51<01:16, 23.90it/s]
 19%|█▉        | 422/2248 [00:51<01:11, 25.59it/s]
 19%|█▉        | 426/2248 [00:51<01:06, 27.39it/s]
 19%|█▉        | 430/2248 [00:52<01:13, 24.66it/s]
 19%|█▉        | 433/2248 [00:52<01:11, 25.36it/s]
 19%|█▉        | 436/2248 [00:52<01:35, 18.90it/s]
 20%|█▉        | 439/2248 [00:52<02:07, 14.18it/s]
 20%|█▉        | 441/2248 [00:53<02:22, 12.71it/s]
 20%|█▉        | 444/2248 [00:53<02:11, 13.68it/s]
 20%|█▉        | 446/2248 [00:53<02:31, 11.89it/s]
 20%|█▉        | 448/2248 [00:53<02:19, 12.94it/s]
 20%|██        | 450/2248 [00:53<02:41, 11.12it/s]
 20%|██        | 452/2248 [00:54<02:22, 12.57it/s]
 20%|██        | 454/2248 [00:54<02:23, 12.49it/s]
 20%|██        | 456/2248 [00:54<03:04,  9.71it/s]
 20%|██        | 458/2248 [00:54<03:46,  7.89it/s]
 20%|██        | 459/2248 [00:55<04:02,  7.37it/s]
 20%|██        | 460/2248 [00:55<04:39,  6.40it/s]
 21%|██        | 463/2248 [00:55<03:59,  7.45it/s]
 21%|██        | 464/2248 [00:55<04:51,  6.11it/s]
 21%|██        | 465/2248 [00:56<04:32,  6.53it/s]
 21%|██        | 468/2248 [00:56<03:01,  9.82it/s]
 21%|██        | 471/2248 [00:56<03:10,  9.33it/s]
 21%|██        | 473/2248 [00:56<03:58,  7.45it/s]
 21%|██        | 475/2248 [00:57<04:14,  6.96it/s]
 21%|██        | 476/2248 [00:57<04:55,  5.99it/s]
 21%|██        | 477/2248 [00:57<05:23,  5.48it/s]
 21%|██▏       | 479/2248 [00:58<05:10,  5.70it/s]
 21%|██▏       | 480/2248 [00:58<05:27,  5.40it/s]
 21%|██▏       | 481/2248 [00:58<06:21,  4.63it/s]
 21%|██▏       | 482/2248 [00:58<07:04,  4.16it/s]
 22%|██▏       | 484/2248 [00:59<04:47,  6.14it/s]
 22%|██▏       | 485/2248 [00:59<05:27,  5.38it/s]
 22%|██▏       | 486/2248 [00:59<05:53,  4.98it/s]
 22%|██▏       | 487/2248 [00:59<05:54,  4.96it/s]
 22%|██▏       | 488/2248 [00:59<05:49,  5.04it/s]
 22%|██▏       | 490/2248 [01:00<04:02,  7.25it/s]
 22%|██▏       | 492/2248 [01:00<05:42,  5.13it/s]
 22%|██▏       | 495/2248 [01:01<05:30,  5.30it/s]
 22%|██▏       | 499/2248 [01:01<04:39,  6.25it/s]
 22%|██▏       | 500/2248 [01:02<05:41,  5.12it/s]
 22%|██▏       | 503/2248 [01:02<03:59,  7.29it/s]
 23%|██▎       | 509/2248 [01:02<02:31, 11.45it/s]
 23%|██▎       | 512/2248 [01:02<02:43, 10.60it/s]
 23%|██▎       | 514/2248 [01:03<03:07,  9.26it/s]
 23%|██▎       | 516/2248 [01:03<03:47,  7.62it/s]
 23%|██▎       | 517/2248 [01:03<04:05,  7.06it/s]
 23%|██▎       | 518/2248 [01:04<05:45,  5.00it/s]
 23%|██▎       | 519/2248 [01:04<06:07,  4.70it/s]
 23%|██▎       | 521/2248 [01:04<04:30,  6.38it/s]
 23%|██▎       | 525/2248 [01:04<02:36, 10.99it/s]
 24%|██▎       | 531/2248 [01:04<01:30, 19.05it/s]
 24%|██▍       | 538/2248 [01:04<01:00, 28.27it/s]
 24%|██▍       | 543/2248 [01:05<00:57, 29.78it/s]
 24%|██▍       | 548/2248 [01:05<00:50, 33.86it/s]
 25%|██▍       | 553/2248 [01:05<00:45, 37.48it/s]
 25%|██▍       | 558/2248 [01:05<01:21, 20.65it/s]
 25%|██▌       | 564/2248 [01:06<01:29, 18.82it/s]
 25%|██▌       | 567/2248 [01:06<01:26, 19.39it/s]
 25%|██▌       | 571/2248 [01:06<01:39, 16.80it/s]
 26%|██▌       | 574/2248 [01:07<03:53,  7.18it/s]
 26%|██▌       | 577/2248 [01:07<03:10,  8.75it/s]
 26%|██▌       | 579/2248 [01:08<03:44,  7.43it/s]
 26%|██▌       | 581/2248 [01:08<04:22,  6.35it/s]
 26%|██▌       | 583/2248 [01:09<04:58,  5.59it/s]
 26%|██▌       | 584/2248 [01:09<06:04,  4.57it/s]
 26%|██▌       | 586/2248 [01:10<06:20,  4.37it/s]
 26%|██▌       | 588/2248 [01:10<06:01,  4.59it/s]
 26%|██▌       | 590/2248 [01:10<04:43,  5.84it/s]
 26%|██▋       | 592/2248 [01:11<04:45,  5.80it/s]
 26%|██▋       | 595/2248 [01:11<03:17,  8.37it/s]
 27%|██▋       | 599/2248 [01:11<02:28, 11.11it/s]
 27%|██▋       | 601/2248 [01:11<02:45,  9.95it/s]
 27%|██▋       | 603/2248 [01:12<02:59,  9.18it/s]
 27%|██▋       | 605/2248 [01:12<03:59,  6.87it/s]
 27%|██▋       | 606/2248 [01:12<04:39,  5.87it/s]
 27%|██▋       | 607/2248 [01:13<05:05,  5.38it/s]
 27%|██▋       | 608/2248 [01:13<05:35,  4.89it/s]
 27%|██▋       | 609/2248 [01:13<06:15,  4.37it/s]
 27%|██▋       | 610/2248 [01:13<06:00,  4.55it/s]
 27%|██▋       | 612/2248 [01:14<04:08,  6.58it/s]
 27%|██▋       | 618/2248 [01:14<01:48, 15.09it/s]
 28%|██▊       | 621/2248 [01:14<02:03, 13.17it/s]
 28%|██▊       | 624/2248 [01:14<01:42, 15.89it/s]
 28%|██▊       | 631/2248 [01:14<01:03, 25.66it/s]
 28%|██▊       | 638/2248 [01:14<00:46, 34.27it/s]
 29%|██▊       | 643/2248 [01:14<00:47, 34.08it/s]
 29%|██▉       | 648/2248 [01:14<00:42, 37.64it/s]
 29%|██▉       | 653/2248 [01:15<01:49, 14.59it/s]
 29%|██▉       | 657/2248 [01:16<01:41, 15.62it/s]
 29%|██▉       | 660/2248 [01:16<02:43,  9.69it/s]
 29%|██▉       | 663/2248 [01:17<02:53,  9.12it/s]
 30%|██▉       | 665/2248 [01:17<02:56,  8.95it/s]
 30%|██▉       | 667/2248 [01:17<03:02,  8.64it/s]
 30%|██▉       | 669/2248 [01:17<02:41,  9.76it/s]
 30%|██▉       | 671/2248 [01:18<03:02,  8.66it/s]
 30%|██▉       | 673/2248 [01:18<02:37, 10.03it/s]
 30%|███       | 677/2248 [01:18<02:58,  8.78it/s]
 30%|███       | 679/2248 [01:19<03:15,  8.01it/s]
 30%|███       | 681/2248 [01:19<03:24,  7.67it/s]
 30%|███       | 682/2248 [01:19<04:27,  5.84it/s]
 30%|███       | 683/2248 [01:20<05:12,  5.01it/s]
 30%|███       | 684/2248 [01:20<05:30,  4.73it/s]
 30%|███       | 685/2248 [01:20<06:40,  3.91it/s]
 31%|███       | 686/2248 [01:21<08:05,  3.22it/s]
 31%|███       | 687/2248 [01:21<08:51,  2.94it/s]
 31%|███       | 688/2248 [01:22<09:15,  2.81it/s]
 31%|███       | 691/2248 [01:22<06:08,  4.22it/s]
 31%|███       | 692/2248 [01:22<07:11,  3.60it/s]
 31%|███       | 694/2248 [01:23<06:14,  4.15it/s]
 31%|███       | 695/2248 [01:23<06:16,  4.13it/s]
 31%|███       | 697/2248 [01:23<04:30,  5.72it/s]
 31%|███       | 698/2248 [01:23<05:04,  5.09it/s]
 31%|███       | 699/2248 [01:24<06:13,  4.15it/s]
 31%|███       | 702/2248 [01:24<05:21,  4.80it/s]
 31%|███▏      | 704/2248 [01:25<05:28,  4.70it/s]
 31%|███▏      | 707/2248 [01:25<03:42,  6.94it/s]
 32%|███▏      | 709/2248 [01:25<03:52,  6.62it/s]
 32%|███▏      | 711/2248 [01:26<04:37,  5.53it/s]
 32%|███▏      | 712/2248 [01:26<05:08,  4.98it/s]
 32%|███▏      | 713/2248 [01:26<05:21,  4.77it/s]
 32%|███▏      | 715/2248 [01:27<05:13,  4.89it/s]
 32%|███▏      | 716/2248 [01:27<05:10,  4.93it/s]
 32%|███▏      | 718/2248 [01:27<04:01,  6.33it/s]
 32%|███▏      | 719/2248 [01:27<04:52,  5.23it/s]
 32%|███▏      | 720/2248 [01:27<04:35,  5.54it/s]
 32%|███▏      | 721/2248 [01:28<05:19,  4.78it/s]
 32%|███▏      | 723/2248 [01:28<03:46,  6.73it/s]
 32%|███▏      | 725/2248 [01:28<02:54,  8.74it/s]
 32%|███▏      | 727/2248 [01:28<02:39,  9.56it/s]
 32%|███▏      | 729/2248 [01:29<04:06,  6.17it/s]
 33%|███▎      | 731/2248 [01:29<04:11,  6.02it/s]
 33%|███▎      | 733/2248 [01:29<03:46,  6.69it/s]
 33%|███▎      | 734/2248 [01:30<04:28,  5.65it/s]
 33%|███▎      | 735/2248 [01:30<05:30,  4.58it/s]
 33%|███▎      | 736/2248 [01:30<05:02,  5.00it/s]
 33%|███▎      | 737/2248 [01:30<04:27,  5.65it/s]
 33%|███▎      | 738/2248 [01:30<04:23,  5.72it/s]
 33%|███▎      | 740/2248 [01:31<03:06,  8.09it/s]
 33%|███▎      | 742/2248 [01:31<04:18,  5.82it/s]
 33%|███▎      | 743/2248 [01:31<05:47,  4.33it/s]
 33%|███▎      | 744/2248 [01:32<07:08,  3.51it/s]
 33%|███▎      | 746/2248 [01:32<04:55,  5.08it/s]
 33%|███▎      | 749/2248 [01:33<04:22,  5.70it/s]
 33%|███▎      | 751/2248 [01:33<04:56,  5.05it/s]
 33%|███▎      | 752/2248 [01:33<05:22,  4.64it/s]
 34%|███▎      | 754/2248 [01:34<05:28,  4.55it/s]
 34%|███▎      | 757/2248 [01:34<03:37,  6.84it/s]
 34%|███▍      | 763/2248 [01:34<01:52, 13.20it/s]
 34%|███▍      | 767/2248 [01:35<02:18, 10.72it/s]
 34%|███▍      | 770/2248 [01:35<01:58, 12.49it/s]
 34%|███▍      | 773/2248 [01:36<03:22,  7.27it/s]
 34%|███▍      | 775/2248 [01:36<04:36,  5.32it/s]
 35%|███▍      | 777/2248 [01:37<04:38,  5.28it/s]
 35%|███▍      | 778/2248 [01:37<04:48,  5.09it/s]
 35%|███▍      | 780/2248 [01:37<03:49,  6.41it/s]
 35%|███▍      | 782/2248 [01:38<04:32,  5.39it/s]
 35%|███▍      | 783/2248 [01:38<04:30,  5.42it/s]
 35%|███▍      | 784/2248 [01:38<05:25,  4.50it/s]
 35%|███▍      | 786/2248 [01:38<04:08,  5.89it/s]
 35%|███▌      | 788/2248 [01:38<03:14,  7.49it/s]
 35%|███▌      | 790/2248 [01:39<03:15,  7.45it/s]
 35%|███▌      | 792/2248 [01:39<04:13,  5.73it/s]
 35%|███▌      | 794/2248 [01:39<03:18,  7.34it/s]
 35%|███▌      | 797/2248 [01:40<03:14,  7.46it/s]
 36%|███▌      | 799/2248 [01:40<02:41,  8.99it/s]
 36%|███▌      | 803/2248 [01:40<01:46, 13.55it/s]
 36%|███▌      | 806/2248 [01:40<02:14, 10.71it/s]
 36%|███▌      | 808/2248 [01:40<02:00, 11.99it/s]
 36%|███▌      | 810/2248 [01:40<01:51, 12.84it/s]
 36%|███▌      | 812/2248 [01:41<03:45,  6.36it/s]
 36%|███▌      | 814/2248 [01:42<05:33,  4.30it/s]
 36%|███▋      | 815/2248 [01:42<06:12,  3.85it/s]
 36%|███▋      | 816/2248 [01:43<06:52,  3.47it/s]
 36%|███▋      | 818/2248 [01:43<05:54,  4.04it/s]
 36%|███▋      | 820/2248 [01:43<04:19,  5.50it/s]
 37%|███▋      | 826/2248 [01:44<02:37,  9.01it/s]
 37%|███▋      | 829/2248 [01:44<02:07, 11.13it/s]
 37%|███▋      | 831/2248 [01:44<02:26,  9.70it/s]
 37%|███▋      | 833/2248 [01:44<02:10, 10.88it/s]
 37%|███▋      | 840/2248 [01:45<01:37, 14.51it/s]
 37%|███▋      | 842/2248 [01:45<01:32, 15.25it/s]
 38%|███▊      | 849/2248 [01:45<00:58, 23.80it/s]
 38%|███▊      | 853/2248 [01:45<01:18, 17.69it/s]
 38%|███▊      | 856/2248 [01:45<01:13, 18.95it/s]
 38%|███▊      | 863/2248 [01:45<00:51, 26.78it/s]
 39%|███▊      | 867/2248 [01:46<01:46, 12.95it/s]
 39%|███▊      | 870/2248 [01:47<02:12, 10.43it/s]
 39%|███▉      | 872/2248 [01:47<02:01, 11.29it/s]
 39%|███▉      | 874/2248 [01:47<02:42,  8.45it/s]
 39%|███▉      | 876/2248 [01:47<02:21,  9.68it/s]
 39%|███▉      | 878/2248 [01:48<02:29,  9.19it/s]
 39%|███▉      | 880/2248 [01:48<02:13, 10.24it/s]
 39%|███▉      | 882/2248 [01:48<02:21,  9.64it/s]
 39%|███▉      | 884/2248 [01:48<02:14, 10.13it/s]
 39%|███▉      | 886/2248 [01:48<02:36,  8.71it/s]
 40%|███▉      | 888/2248 [01:49<02:45,  8.24it/s]
 40%|███▉      | 890/2248 [01:49<02:52,  7.86it/s]
 40%|███▉      | 891/2248 [01:49<04:11,  5.39it/s]
 40%|███▉      | 893/2248 [01:50<03:16,  6.90it/s]
 40%|███▉      | 894/2248 [01:50<04:42,  4.78it/s]
 40%|███▉      | 895/2248 [01:51<05:45,  3.91it/s]
 40%|███▉      | 897/2248 [01:51<04:02,  5.57it/s]
 40%|████      | 902/2248 [01:51<03:07,  7.18it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 324.83it/s]

[[np.int64(0), False, 3], [np.int64(1), False, 6], [np.int64(2), False, 1], [np.int64(3), False, 11], [np.int64(4), False, 8], [np.int64(5), False, 1], [np.int64(7), False, 2], [np.int64(8), False, 11], [np.int64(9), False, 2], [np.int64(10), False, 9], [np.int64(12), False, 0], [np.int64(13), False, 3]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(13.0394, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9707, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [04:52<2:45:51, 50.01s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [04:53<2:11:54, 39.97s/it]

tensor(13.0295, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0004, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0199, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0692, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [04:53<57:03, 17.56s/it]

tensor(13.0128, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1213, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0096, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1264, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 106/300 [04:53<41:38, 12.88s/it]

tensor(13.0103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1955, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0138, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2575, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [04:53<15:20,  4.82s/it]

tensor(13.0188, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3034, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3666, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [04:54<07:46,  2.47s/it]

tensor(13.0261, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4146, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4617, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 112/300 [04:54<05:33,  1.77s/it]

tensor(13.0265, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5156, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5568, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [04:54<02:08,  1.44it/s]

tensor(13.0196, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0279, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(13.0135, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6556, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [04:54<01:13,  2.50it/s]

tensor(13.0059, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7076, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0290, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7198, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [04:55<00:46,  3.93it/s]

tensor(12.9873, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0287, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7491, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7774, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 120/300 [04:55<00:38,  4.68it/s]

tensor(12.9672, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0281, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8029, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9572, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8258, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 122/300 [04:55<00:29,  6.01it/s]

tensor(12.9473, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8605, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8798, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [04:55<00:24,  7.26it/s]

tensor(12.9291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8918, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9208, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9107, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 126/300 [04:55<00:23,  7.53it/s]

tensor(12.9134, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9392, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9622, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 128/300 [04:56<00:21,  7.83it/s]

tensor(12.8991, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9869, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8921, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0140, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [04:56<00:20,  8.10it/s]

tensor(12.8858, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0412, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8797, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0733, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 132/300 [04:56<00:20,  8.15it/s]

tensor(12.8737, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1039, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1295, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [04:56<00:20,  8.18it/s]

tensor(12.8615, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1483, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8549, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1724, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 136/300 [04:57<00:20,  8.11it/s]

tensor(12.8480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1966, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8412, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2163, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [04:57<00:19,  8.38it/s]

tensor(12.8346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2432, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8279, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2576, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [04:57<00:18,  8.50it/s]

tensor(12.8209, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2805, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8133, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0260, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2941, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [04:57<00:18,  8.33it/s]

tensor(12.8055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3109, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7979, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3288, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 144/300 [04:58<00:18,  8.27it/s]

tensor(12.7906, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3412, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7837, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3522, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▊     | 146/300 [04:58<00:18,  8.20it/s]

tensor(12.7773, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3684, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7714, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3770, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [04:58<00:17,  8.42it/s]

tensor(12.7660, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3889, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3941, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [04:58<00:17,  8.52it/s]

tensor(12.7561, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4055, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([206, 232, 137,  83, 207, 234,  42,  90, 124, 134, 369, 127, 132, 131])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:09, 17.29it/s]
  0%|          | 9/2248 [00:00<00:48, 46.19it/s]
  1%|          | 16/2248 [00:00<00:39, 56.12it/s]
  1%|          | 23/2248 [00:00<00:37, 59.44it/s]
  1%|▏         | 30/2248 [00:00<00:42, 52.01it/s]
  2%|▏         | 37/2248 [00:00<00:39, 56.18it/s]
  2%|▏         | 43/2248 [00:00<00:40, 55.06it/s]
  2%|▏         | 49/2248 [00:00<00:47, 46.61it/s]
  2%|▏         | 54/2248 [00:01<00:46, 46.76it/s]
  3%|▎         | 61/2248 [00:01<00:41, 52.25it/s]
  3%|▎         | 67/2248 [00:01<00:40, 53.28it/s]
  3%|▎         | 73/2248 [00:01<00:39, 54.55it/s]
  4%|▎         | 79/2248 [00:02<02:03, 17.58it/s]
  4%|▎         | 84/2248 [00:02<01:45, 20.59it/s]
  4%|▍         | 90/2248 [00:02<01:23, 25.79it/s]
  4%|▍         | 95/2248 [00:03<02:32, 14.11it/s]
  4%|▍         | 99/2248 [00:03<02:26, 14.64it/s]
  5%|▍         | 102/2248 [00:03<02:14, 16.01it/s]
  5%|▍         | 105/2248 [00:03<02:02, 17.52it/s]
  5%|▍         | 110/2248 [00:03<01:37, 21.87it/s]
  5%|▌         | 114/2248 [00:04<03:22, 10.56it/s]
  5%|▌         | 117/2248 [00:05<05:07,  6.93it/s]
  5%|▌         | 119/2248 [00:06<06:26,  5.51it/s]
  5%|▌         | 121/2248 [00:07<07:28,  4.75it/s]
  5%|▌         | 123/2248 [00:07<06:19,  5.59it/s]
  6%|▌         | 127/2248 [00:07<05:53,  6.00it/s]
  6%|▌         | 129/2248 [00:07<05:04,  6.96it/s]
  6%|▌         | 131/2248 [00:08<04:18,  8.20it/s]
  6%|▌         | 137/2248 [00:08<02:25, 14.55it/s]
  6%|▌         | 140/2248 [00:08<04:03,  8.67it/s]
  6%|▋         | 145/2248 [00:09<04:04,  8.59it/s]
  7%|▋         | 147/2248 [00:09<03:41,  9.48it/s]
  7%|▋         | 149/2248 [00:10<05:59,  5.83it/s]
  7%|▋         | 152/2248 [00:10<04:31,  7.73it/s]
  7%|▋         | 155/2248 [00:10<03:34,  9.75it/s]
  7%|▋         | 157/2248 [00:11<05:48,  6.00it/s]
  7%|▋         | 159/2248 [00:12<08:15,  4.22it/s]
  7%|▋         | 165/2248 [00:12<04:22,  7.94it/s]
  7%|▋         | 168/2248 [00:13<05:36,  6.17it/s]
  8%|▊         | 173/2248 [00:14<05:38,  6.14it/s]
  8%|▊         | 175/2248 [00:14<04:55,  7.01it/s]
  8%|▊         | 177/2248 [00:14<06:46,  5.09it/s]
  8%|▊         | 179/2248 [00:15<08:24,  4.10it/s]
  8%|▊         | 182/2248 [00:15<06:01,  5.72it/s]
  8%|▊         | 185/2248 [00:16<06:56,  4.95it/s]
  8%|▊         | 187/2248 [00:17<08:26,  4.07it/s]
  8%|▊         | 189/2248 [00:17<06:51,  5.00it/s]
  9%|▊         | 195/2248 [00:18<05:44,  5.95it/s]
  9%|▉         | 198/2248 [00:19<06:40,  5.12it/s]
  9%|▉         | 201/2248 [00:19<07:22,  4.63it/s]
  9%|▉         | 203/2248 [00:20<06:15,  5.44it/s]
  9%|▉         | 205/2248 [00:20<07:39,  4.44it/s]
  9%|▉         | 207/2248 [00:21<09:12,  3.70it/s]
  9%|▉         | 209/2248 [00:22<10:26,  3.25it/s]
  9%|▉         | 210/2248 [00:23<12:43,  2.67it/s]
  9%|▉         | 211/2248 [00:23<14:46,  2.30it/s]
 10%|▉         | 214/2248 [00:24<08:54,  3.81it/s]
 10%|▉         | 222/2248 [00:24<03:35,  9.38it/s]
 10%|█         | 227/2248 [00:24<02:33, 13.19it/s]
 10%|█         | 231/2248 [00:24<02:04, 16.18it/s]
 11%|█         | 239/2248 [00:24<01:19, 25.13it/s]
 11%|█         | 244/2248 [00:24<01:18, 25.67it/s]
 11%|█         | 251/2248 [00:24<01:00, 32.85it/s]
 11%|█▏        | 257/2248 [00:24<00:53, 37.23it/s]
 12%|█▏        | 262/2248 [00:25<00:52, 37.62it/s]
 12%|█▏        | 267/2248 [00:25<01:21, 24.25it/s]
 12%|█▏        | 271/2248 [00:25<02:07, 15.46it/s]
 12%|█▏        | 274/2248 [00:26<02:08, 15.38it/s]
 12%|█▏        | 277/2248 [00:27<05:27,  6.01it/s]
 12%|█▏        | 279/2248 [00:27<04:47,  6.85it/s]
 13%|█▎        | 282/2248 [00:28<06:00,  5.46it/s]
 13%|█▎        | 285/2248 [00:28<04:41,  6.97it/s]
 13%|█▎        | 287/2248 [00:29<06:14,  5.24it/s]
 13%|█▎        | 289/2248 [00:29<05:20,  6.11it/s]
 13%|█▎        | 291/2248 [00:29<05:08,  6.35it/s]
 13%|█▎        | 293/2248 [00:30<06:23,  5.09it/s]
 13%|█▎        | 295/2248 [00:31<08:19,  3.91it/s]
 13%|█▎        | 298/2248 [00:31<07:45,  4.19it/s]
 13%|█▎        | 300/2248 [00:32<06:16,  5.17it/s]
 13%|█▎        | 302/2248 [00:32<05:01,  6.46it/s]
 14%|█▎        | 304/2248 [00:32<05:21,  6.04it/s]
 14%|█▎        | 306/2248 [00:32<05:31,  5.86it/s]
 14%|█▎        | 307/2248 [00:33<07:29,  4.32it/s]
 14%|█▎        | 308/2248 [00:33<08:13,  3.93it/s]
 14%|█▎        | 309/2248 [00:34<09:56,  3.25it/s]
 14%|█▍        | 312/2248 [00:34<05:50,  5.53it/s]
 14%|█▍        | 314/2248 [00:34<05:31,  5.83it/s]
 14%|█▍        | 317/2248 [00:34<03:47,  8.51it/s]
 14%|█▍        | 322/2248 [00:35<04:32,  7.07it/s]
 14%|█▍        | 324/2248 [00:36<06:26,  4.98it/s]
 14%|█▍        | 325/2248 [00:37<07:49,  4.10it/s]
 15%|█▍        | 328/2248 [00:37<08:14,  3.88it/s]
 15%|█▍        | 330/2248 [00:38<06:36,  4.84it/s]
 15%|█▍        | 332/2248 [00:38<07:50,  4.08it/s]
 15%|█▍        | 334/2248 [00:38<06:08,  5.19it/s]
 15%|█▌        | 340/2248 [00:39<04:13,  7.52it/s]
 15%|█▌        | 342/2248 [00:39<03:41,  8.62it/s]
 15%|█▌        | 344/2248 [00:40<05:25,  5.86it/s]
 15%|█▌        | 346/2248 [00:40<06:59,  4.54it/s]
 15%|█▌        | 348/2248 [00:41<07:40,  4.12it/s]
 16%|█▌        | 349/2248 [00:41<07:43,  4.10it/s]
 16%|█▌        | 351/2248 [00:41<05:56,  5.32it/s]
 16%|█▌        | 353/2248 [00:42<05:28,  5.76it/s]
 16%|█▌        | 355/2248 [00:42<04:23,  7.18it/s]
 16%|█▌        | 357/2248 [00:42<04:44,  6.65it/s]
 16%|█▌        | 359/2248 [00:42<03:53,  8.08it/s]
 16%|█▌        | 361/2248 [00:42<03:13,  9.74it/s]
 16%|█▌        | 364/2248 [00:43<03:34,  8.80it/s]
 16%|█▋        | 366/2248 [00:43<04:02,  7.77it/s]
 16%|█▋        | 368/2248 [00:43<03:25,  9.13it/s]
 17%|█▋        | 371/2248 [00:44<04:44,  6.59it/s]
 17%|█▋        | 373/2248 [00:44<04:05,  7.65it/s]
 17%|█▋        | 375/2248 [00:44<03:26,  9.08it/s]
 17%|█▋        | 377/2248 [00:45<05:17,  5.89it/s]
 17%|█▋        | 379/2248 [00:45<04:31,  6.88it/s]
 17%|█▋        | 383/2248 [00:45<02:50, 10.94it/s]
 17%|█▋        | 385/2248 [00:46<05:04,  6.12it/s]
 17%|█▋        | 387/2248 [00:46<04:11,  7.40it/s]
 17%|█▋        | 389/2248 [00:47<07:20,  4.22it/s]
 17%|█▋        | 391/2248 [00:47<05:55,  5.22it/s]
 17%|█▋        | 393/2248 [00:48<09:48,  3.15it/s]
 18%|█▊        | 394/2248 [00:49<12:05,  2.56it/s]
 18%|█▊        | 397/2248 [00:49<07:33,  4.08it/s]
 18%|█▊        | 399/2248 [00:49<05:53,  5.23it/s]
 18%|█▊        | 402/2248 [00:50<04:05,  7.51it/s]
 18%|█▊        | 408/2248 [00:50<02:14, 13.64it/s]
 18%|█▊        | 415/2248 [00:50<01:24, 21.73it/s]
 19%|█▊        | 420/2248 [00:50<01:14, 24.66it/s]
 19%|█▉        | 428/2248 [00:50<00:54, 33.53it/s]
 19%|█▉        | 434/2248 [00:50<00:46, 38.75it/s]
 20%|█▉        | 440/2248 [00:52<03:43,  8.09it/s]
 20%|█▉        | 444/2248 [00:53<03:40,  8.18it/s]
 20%|█▉        | 447/2248 [00:53<03:11,  9.39it/s]
 20%|██        | 450/2248 [00:53<03:44,  8.00it/s]
 20%|██        | 453/2248 [00:54<04:28,  6.68it/s]
 20%|██        | 455/2248 [00:55<05:46,  5.17it/s]
 20%|██        | 457/2248 [00:56<07:01,  4.24it/s]
 20%|██        | 460/2248 [00:56<07:24,  4.03it/s]
 21%|██        | 463/2248 [00:57<05:30,  5.40it/s]
 21%|██        | 465/2248 [00:57<06:42,  4.43it/s]
 21%|██        | 468/2248 [00:57<04:51,  6.12it/s]
 21%|██        | 471/2248 [00:58<05:34,  5.31it/s]
 21%|██        | 473/2248 [00:59<07:01,  4.21it/s]
 21%|██        | 475/2248 [01:00<08:10,  3.61it/s]
 21%|██        | 476/2248 [01:00<10:09,  2.91it/s]
 21%|██▏       | 478/2248 [01:01<07:36,  3.88it/s]
 21%|██▏       | 479/2248 [01:01<10:05,  2.92it/s]
 21%|██▏       | 480/2248 [01:02<12:27,  2.37it/s]
 21%|██▏       | 481/2248 [01:03<14:25,  2.04it/s]
 22%|██▏       | 484/2248 [01:03<07:55,  3.71it/s]
 22%|██▏       | 486/2248 [01:04<08:56,  3.28it/s]
 22%|██▏       | 488/2248 [01:04<06:43,  4.37it/s]
 22%|██▏       | 493/2248 [01:04<03:31,  8.29it/s]
 22%|██▏       | 496/2248 [01:04<02:43, 10.68it/s]
 22%|██▏       | 501/2248 [01:04<01:50, 15.80it/s]
 22%|██▏       | 504/2248 [01:04<01:43, 16.93it/s]
 23%|██▎       | 510/2248 [01:05<02:14, 12.93it/s]
 23%|██▎       | 513/2248 [01:05<01:56, 14.85it/s]
 23%|██▎       | 516/2248 [01:05<02:49, 10.25it/s]
 23%|██▎       | 518/2248 [01:06<03:22,  8.53it/s]
 23%|██▎       | 520/2248 [01:06<02:58,  9.70it/s]
 23%|██▎       | 522/2248 [01:06<02:42, 10.59it/s]
 23%|██▎       | 524/2248 [01:06<02:28, 11.62it/s]
 24%|██▎       | 529/2248 [01:06<01:36, 17.79it/s]
 24%|██▍       | 536/2248 [01:06<01:07, 25.53it/s]
 24%|██▍       | 540/2248 [01:07<01:04, 26.31it/s]
 24%|██▍       | 546/2248 [01:07<00:52, 32.22it/s]
 25%|██▍       | 551/2248 [01:07<00:48, 34.84it/s]
 25%|██▍       | 555/2248 [01:07<00:49, 34.34it/s]
 25%|██▌       | 562/2248 [01:07<00:40, 42.07it/s]
 25%|██▌       | 567/2248 [01:07<00:46, 35.96it/s]
 25%|██▌       | 571/2248 [01:08<01:23, 20.12it/s]
 26%|██▌       | 575/2248 [01:08<01:15, 22.06it/s]
 26%|██▌       | 580/2248 [01:08<01:02, 26.78it/s]
 26%|██▌       | 584/2248 [01:09<03:22,  8.22it/s]
 26%|██▌       | 587/2248 [01:10<04:16,  6.49it/s]
 26%|██▌       | 589/2248 [01:11<05:21,  5.16it/s]
 26%|██▋       | 592/2248 [01:12<05:55,  4.66it/s]
 26%|██▋       | 595/2248 [01:12<04:33,  6.03it/s]
 27%|██▋       | 602/2248 [01:12<02:33, 10.73it/s]
 27%|██▋       | 606/2248 [01:15<07:27,  3.67it/s]
 27%|██▋       | 609/2248 [01:16<07:35,  3.60it/s]
 27%|██▋       | 612/2248 [01:16<05:58,  4.56it/s]
 27%|██▋       | 617/2248 [01:16<03:57,  6.88it/s]
 28%|██▊       | 623/2248 [01:16<02:35, 10.42it/s]
 28%|██▊       | 630/2248 [01:16<01:44, 15.46it/s]
 28%|██▊       | 636/2248 [01:16<01:19, 20.29it/s]
 29%|██▊       | 643/2248 [01:16<01:02, 25.80it/s]
 29%|██▉       | 649/2248 [01:17<00:51, 31.12it/s]
 29%|██▉       | 655/2248 [01:17<01:47, 14.79it/s]
 29%|██▉       | 660/2248 [01:18<02:20, 11.27it/s]
 29%|██▉       | 663/2248 [01:19<03:14,  8.13it/s]
 30%|██▉       | 666/2248 [01:19<02:49,  9.35it/s]
 30%|██▉       | 670/2248 [01:20<03:30,  7.50it/s]
 30%|██▉       | 673/2248 [01:20<02:56,  8.94it/s]
 30%|███       | 680/2248 [01:20<01:51, 14.05it/s]
 30%|███       | 683/2248 [01:21<03:17,  7.91it/s]
 31%|███       | 686/2248 [01:22<04:47,  5.42it/s]
 31%|███       | 688/2248 [01:23<04:12,  6.17it/s]
 31%|███       | 690/2248 [01:23<03:37,  7.17it/s]
 31%|███       | 697/2248 [01:23<01:59, 13.03it/s]
 31%|███       | 702/2248 [01:24<02:46,  9.30it/s]
 31%|███▏      | 705/2248 [01:24<02:27, 10.45it/s]
 32%|███▏      | 710/2248 [01:24<01:47, 14.28it/s]
 32%|███▏      | 713/2248 [01:24<02:31, 10.13it/s]
 32%|███▏      | 716/2248 [01:25<03:03,  8.33it/s]
 32%|███▏      | 718/2248 [01:25<02:52,  8.88it/s]
 32%|███▏      | 720/2248 [01:26<03:34,  7.13it/s]
 32%|███▏      | 722/2248 [01:26<03:05,  8.22it/s]
 32%|███▏      | 724/2248 [01:26<02:39,  9.57it/s]
 32%|███▏      | 727/2248 [01:26<02:46,  9.13it/s]
 32%|███▏      | 729/2248 [01:26<02:33,  9.93it/s]
 33%|███▎      | 731/2248 [01:27<04:26,  5.70it/s]
 33%|███▎      | 732/2248 [01:28<05:35,  4.52it/s]
 33%|███▎      | 734/2248 [01:28<04:16,  5.91it/s]
 33%|███▎      | 736/2248 [01:29<07:14,  3.48it/s]
 33%|███▎      | 737/2248 [01:29<08:54,  2.82it/s]
 33%|███▎      | 739/2248 [01:30<06:21,  3.96it/s]
 33%|███▎      | 743/2248 [01:30<05:46,  4.34it/s]
 33%|███▎      | 745/2248 [01:30<04:35,  5.45it/s]
 33%|███▎      | 751/2248 [01:31<02:23, 10.44it/s]
 34%|███▎      | 754/2248 [01:32<05:20,  4.66it/s]
 34%|███▎      | 757/2248 [01:32<04:04,  6.10it/s]
 34%|███▍      | 763/2248 [01:33<03:43,  6.63it/s]
 34%|███▍      | 766/2248 [01:33<03:05,  7.99it/s]
 34%|███▍      | 772/2248 [01:34<03:08,  7.82it/s]
 34%|███▍      | 774/2248 [01:35<04:14,  5.80it/s]
 35%|███▍      | 776/2248 [01:35<03:43,  6.59it/s]
 35%|███▍      | 782/2248 [01:35<02:14, 10.90it/s]
 35%|███▍      | 785/2248 [01:35<01:59, 12.24it/s]
 35%|███▌      | 788/2248 [01:35<01:43, 14.12it/s]
 35%|███▌      | 791/2248 [01:35<01:34, 15.43it/s]
 35%|███▌      | 794/2248 [01:36<02:15, 10.71it/s]
 35%|███▌      | 796/2248 [01:36<02:09, 11.24it/s]
 35%|███▌      | 798/2248 [01:37<03:41,  6.56it/s]
 36%|███▌      | 801/2248 [01:37<02:46,  8.70it/s]
 36%|███▌      | 807/2248 [01:37<01:37, 14.83it/s]
 36%|███▌      | 810/2248 [01:37<01:25, 16.82it/s]
 36%|███▋      | 815/2248 [01:37<01:05, 21.95it/s]
 36%|███▋      | 820/2248 [01:37<00:53, 26.55it/s]
 37%|███▋      | 825/2248 [01:38<00:45, 31.45it/s]
 37%|███▋      | 830/2248 [01:38<00:40, 34.98it/s]
 37%|███▋      | 836/2248 [01:38<00:34, 40.73it/s]
 37%|███▋      | 841/2248 [01:38<00:35, 39.46it/s]
 38%|███▊      | 847/2248 [01:38<00:31, 44.26it/s]
 38%|███▊      | 852/2248 [01:38<00:30, 45.76it/s]
 38%|███▊      | 857/2248 [01:38<00:31, 44.29it/s]
 38%|███▊      | 863/2248 [01:38<00:28, 48.06it/s]
 39%|███▊      | 868/2248 [01:39<01:29, 15.46it/s]
 39%|███▉      | 872/2248 [01:40<02:18,  9.97it/s]
 39%|███▉      | 875/2248 [01:41<03:12,  7.14it/s]
 39%|███▉      | 877/2248 [01:41<03:41,  6.18it/s]
 39%|███▉      | 879/2248 [01:42<04:29,  5.08it/s]
 39%|███▉      | 882/2248 [01:42<03:24,  6.67it/s]
 39%|███▉      | 886/2248 [01:43<02:47,  8.13it/s]
 40%|███▉      | 889/2248 [01:43<02:17,  9.88it/s]
 40%|███▉      | 895/2248 [01:43<02:39,  8.49it/s]
 40%|███▉      | 897/2248 [01:44<02:28,  9.11it/s]
 40%|███▉      | 899/2248 [01:44<02:15,  9.98it/s]
 40%|████      | 902/2248 [01:45<03:16,  6.85it/s]
 40%|████      | 904/2248 [01:45<04:32,  4.94it/s]
 40%|████      | 906/2248 [01:46<05:35,  4.00it/s]
 40%|████      | 908/2248 [01:47<06:23,  3.49it/s]
 40%|████      | 909/2248 [01:48<08:01,  2.78it/s]
 40%|████      | 910/2248 [01:48<08:28,  2.63it/s]
 41%|████      | 911/2248 [01:49<09:51,  2.26it/s]
 41%|████      | 912/2248 [01:49<09:52,  2.26it/s]
 41%|████      | 914/2248 [01:49<06:30,  3.42it/s]
 41%|████      | 917/2248 [01:49<03:53,  5.70it/s]
 41%|████      | 923/2248 [01:50<01:54, 11.58it/s]
 41%|████      | 926/2248 [01:50<02:52,  7.65it/s]
 41%|████▏     | 928/2248 [01:51<04:04,  5.40it/s]
 41%|████▏     | 930/2248 [01:51<03:32,  6.22it/s]
 41%|████▏     | 932/2248 [01:52<04:21,  5.04it/s]
 42%|████▏     | 934/2248 [01:52<03:32,  6.19it/s]
 42%|████▏     | 936/2248 [01:52<02:56,  7.43it/s]
 42%|████▏     | 938/2248 [01:52<02:28,  8.80it/s]
 42%|████▏     | 944/2248 [01:53<02:02, 10.67it/s]
 42%|████▏     | 947/2248 [01:53<01:43, 12.54it/s]
 42%|████▏     | 952/2248 [01:53<01:51, 11.64it/s]
 42%|████▏     | 954/2248 [01:53<01:43, 12.51it/s]
 43%|████▎     | 956/2248 [01:54<03:29,  6.18it/s]
 43%|████▎     | 958/2248 [01:56<06:20,  3.39it/s]
 43%|████▎     | 960/2248 [01:57<06:40,  3.21it/s]
 43%|████▎     | 961/2248 [01:57<08:15,  2.60it/s]
 43%|████▎     | 962/2248 [01:58<09:29,  2.26it/s]
 43%|████▎     | 964/2248 [01:58<06:42,  3.19it/s]
 43%|████▎     | 966/2248 [01:59<05:46,  3.70it/s]
 43%|████▎     | 967/2248 [01:59<05:57,  3.58it/s]
 43%|████▎     | 969/2248 [02:00<06:24,  3.33it/s]
 43%|████▎     | 970/2248 [02:00<06:43,  3.17it/s]
 43%|████▎     | 972/2248 [02:00<04:40,  4.55it/s]
 43%|████▎     | 974/2248 [02:01<05:26,  3.90it/s]
 43%|████▎     | 977/2248 [02:01<03:27,  6.12it/s]
 44%|████▎     | 979/2248 [02:02<04:43,  4.48it/s]
 44%|████▎     | 981/2248 [02:02<06:02,  3.50it/s]
 44%|████▎     | 983/2248 [02:03<04:38,  4.54it/s]
 44%|████▍     | 985/2248 [02:03<05:28,  3.85it/s]
 44%|████▍     | 987/2248 [02:04<05:54,  3.56it/s]
 44%|████▍     | 990/2248 [02:04<03:58,  5.27it/s]
 44%|████▍     | 992/2248 [02:05<05:04,  4.12it/s]
 44%|████▍     | 995/2248 [02:05<03:32,  5.91it/s]
 44%|████▍     | 998/2248 [02:06<04:14,  4.91it/s]
 44%|████▍     | 1000/2248 [02:07<05:23,  3.86it/s]
 45%|████▍     | 1002/2248 [02:07<06:08,  3.39it/s]
 45%|████▍     | 1003/2248 [02:08<07:16,  2.85it/s]
 45%|████▍     | 1004/2248 [02:09<08:40,  2.39it/s]
 45%|████▍     | 1005/2248 [02:10<10:08,  2.04it/s]
 45%|████▍     | 1006/2248 [02:10<11:15,  1.84it/s]
 45%|████▍     | 1007/2248 [02:11<12:10,  1.70it/s]
 45%|████▍     | 1008/2248 [02:12<12:39,  1.63it/s]
 45%|████▍     | 1010/2248 [02:12<07:45,  2.66it/s]
 45%|████▌     | 1017/2248 [02:12<02:40,  7.66it/s]
 46%|████▌     | 1023/2248 [02:12<01:37, 12.51it/s]
 46%|████▌     | 1030/2248 [02:12<01:03, 19.20it/s]
 46%|████▌     | 1035/2248 [02:12<00:55, 21.96it/s]
 46%|████▌     | 1039/2248 [02:12<00:52, 22.87it/s]
 46%|████▋     | 1045/2248 [02:13<00:41, 29.02it/s]
 47%|████▋     | 1050/2248 [02:13<00:37, 31.72it/s]
 47%|████▋     | 1056/2248 [02:13<01:05, 18.29it/s]
 47%|████▋     | 1060/2248 [02:13<00:59, 19.84it/s]
 47%|████▋     | 1066/2248 [02:13<00:46, 25.18it/s]
 48%|████▊     | 1070/2248 [02:14<01:30, 13.00it/s]
 48%|████▊     | 1073/2248 [02:15<02:23,  8.19it/s]
 48%|████▊     | 1076/2248 [02:16<03:00,  6.51it/s]
 48%|████▊     | 1079/2248 [02:16<02:26,  7.97it/s]
 48%|████▊     | 1084/2248 [02:17<02:44,  7.09it/s]
 48%|████▊     | 1087/2248 [02:18<03:20,  5.78it/s]
 48%|████▊     | 1089/2248 [02:19<05:10,  3.74it/s]
 48%|████▊     | 1090/2248 [02:20<06:07,  3.15it/s]
 49%|████▊     | 1092/2248 [02:21<06:32,  2.95it/s]
 49%|████▊     | 1093/2248 [02:21<07:58,  2.41it/s]
 49%|████▊     | 1095/2248 [02:21<05:51,  3.28it/s]
 49%|████▉     | 1102/2248 [02:22<02:29,  7.67it/s]
 49%|████▉     | 1109/2248 [02:22<01:28, 12.83it/s]
 50%|████▉     | 1116/2248 [02:22<01:00, 18.84it/s]
 50%|████▉     | 1121/2248 [02:22<00:49, 22.62it/s]
 50%|█████     | 1126/2248 [02:22<00:45, 24.67it/s]
 50%|█████     | 1131/2248 [02:22<00:39, 28.56it/s]
 51%|█████     | 1136/2248 [02:22<00:36, 30.48it/s]
 51%|█████     | 1141/2248 [02:22<00:32, 34.33it/s]
 51%|█████     | 1146/2248 [02:23<01:07, 16.35it/s]
 51%|█████     | 1150/2248 [02:24<01:15, 14.48it/s]
 51%|█████▏    | 1153/2248 [02:24<01:41, 10.83it/s]
 51%|█████▏    | 1155/2248 [02:24<02:02,  8.92it/s]
 51%|█████▏    | 1157/2248 [02:25<02:25,  7.49it/s]
 52%|█████▏    | 1160/2248 [02:25<01:55,  9.40it/s]
 52%|█████▏    | 1162/2248 [02:26<02:54,  6.24it/s]
 52%|█████▏    | 1164/2248 [02:26<02:26,  7.39it/s]
 52%|█████▏    | 1169/2248 [02:26<01:29, 12.12it/s]
 52%|█████▏    | 1172/2248 [02:27<03:35,  4.99it/s]
 52%|█████▏    | 1175/2248 [02:28<02:51,  6.27it/s]
 52%|█████▏    | 1178/2248 [02:28<02:47,  6.38it/s]
 52%|█████▏    | 1180/2248 [02:29<03:09,  5.64it/s]
 53%|█████▎    | 1182/2248 [02:29<03:14,  5.48it/s]
 53%|█████▎    | 1183/2248 [02:29<03:59,  4.45it/s]
 53%|█████▎    | 1184/2248 [02:30<04:10,  4.25it/s]
 53%|█████▎    | 1186/2248 [02:30<03:13,  5.49it/s]
 53%|█████▎    | 1187/2248 [02:30<03:44,  4.73it/s]
 53%|█████▎    | 1188/2248 [02:31<04:14,  4.17it/s]
 53%|█████▎    | 1190/2248 [02:31<03:00,  5.87it/s]
 53%|█████▎    | 1193/2248 [02:31<02:55,  6.00it/s]
 53%|█████▎    | 1195/2248 [02:32<03:02,  5.77it/s]
 53%|█████▎    | 1198/2248 [02:32<02:07,  8.26it/s]
 54%|█████▎    | 1204/2248 [02:32<01:09, 15.07it/s]
 54%|█████▎    | 1207/2248 [02:33<02:22,  7.29it/s]
 54%|█████▍    | 1209/2248 [02:33<02:08,  8.06it/s]
 54%|█████▍    | 1213/2248 [02:33<01:31, 11.34it/s]
 54%|█████▍    | 1216/2248 [02:34<02:03,  8.35it/s]
 54%|█████▍    | 1222/2248 [02:34<01:39, 10.31it/s]
 54%|█████▍    | 1224/2248 [02:34<01:35, 10.68it/s]
 55%|█████▍    | 1226/2248 [02:35<02:06,  8.09it/s]
 55%|█████▍    | 1228/2248 [02:35<01:50,  9.24it/s]
 55%|█████▍    | 1230/2248 [02:35<02:49,  5.99it/s]
 55%|█████▍    | 1232/2248 [02:36<03:57,  4.28it/s]
 55%|█████▍    | 1234/2248 [02:36<03:10,  5.32it/s]
 55%|█████▌    | 1240/2248 [02:37<02:03,  8.18it/s]
 55%|█████▌    | 1242/2248 [02:37<01:50,  9.13it/s]
 55%|█████▌    | 1244/2248 [02:37<02:19,  7.19it/s]
 55%|█████▌    | 1246/2248 [02:38<02:38,  6.34it/s]
 56%|█████▌    | 1248/2248 [02:38<02:11,  7.59it/s]
 56%|█████▌    | 1252/2248 [02:38<01:27, 11.34it/s]
 56%|█████▌    | 1255/2248 [02:38<01:15, 13.07it/s]
 56%|█████▌    | 1261/2248 [02:38<00:49, 20.00it/s]
 56%|█████▋    | 1267/2248 [02:38<00:35, 27.29it/s]
 57%|█████▋    | 1271/2248 [02:39<01:18, 12.47it/s]
 57%|█████▋    | 1274/2248 [02:40<01:57,  8.29it/s]
 57%|█████▋    | 1277/2248 [02:40<01:39,  9.79it/s]
 57%|█████▋    | 1280/2248 [02:41<02:14,  7.22it/s]
 57%|█████▋    | 1282/2248 [02:41<01:57,  8.23it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 314.61it/s]

[[np.int64(0), False, 12], [np.int64(1), False, 10], [np.int64(2), False, 12], [np.int64(3), False, 13], [np.int64(4), False, 10], [np.int64(5), False, 9], [np.int64(6), False, 3], [np.int64(7), False, 0], [np.int64(8), False, 12], [np.int64(9), False, 0], [np.int64(11), False, 7]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.7512, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5268, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [09:42<3:31:54, 85.33s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [09:43<2:27:26, 59.78s/it]

tensor(12.7608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4177, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7874, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0368, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7141, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [09:43<49:44, 20.58s/it]

tensor(12.8089, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0410, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0738, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0448, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2426, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 156/300 [09:43<34:40, 14.45s/it]

tensor(12.8304, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0475, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5839, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8492, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0500, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7989, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [09:43<11:49,  5.04s/it]

tensor(12.8814, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0520, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8819, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.9005, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0540, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6216, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [09:44<05:51,  2.53s/it]

tensor(12.8881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7407, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8578, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0562, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9593, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 162/300 [09:44<04:09,  1.80s/it]

tensor(12.8274, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9712, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8025, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0560, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0203, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [09:44<01:34,  1.43it/s]

tensor(12.7844, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0544, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0885, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7784, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0544, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1277, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [09:44<00:53,  2.48it/s]

tensor(12.7794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0548, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1303, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7794, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0826, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 168/300 [09:45<00:42,  3.13it/s]

tensor(12.7753, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0533, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1603, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7708, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0511, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2091, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [09:45<00:23,  5.39it/s]

tensor(12.7626, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0484, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2373, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7548, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0461, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2640, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [09:45<00:19,  6.65it/s]

tensor(12.7520, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0447, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2829, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7469, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0438, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2941, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [09:45<00:16,  7.49it/s]

tensor(12.7379, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3178, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7306, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0413, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3345, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [09:46<00:15,  7.96it/s]

tensor(12.7245, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0403, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3372, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0391, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2910, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [09:46<00:14,  8.28it/s]

tensor(12.7038, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0379, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3029, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0372, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3137, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [09:46<00:14,  8.29it/s]

tensor(12.6871, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0363, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3785, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6823, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0361, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3991, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 182/300 [09:46<00:14,  8.35it/s]

tensor(12.6787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4190, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6768, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0354, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4318, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [09:47<00:13,  8.26it/s]

tensor(12.6730, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4396, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6679, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0343, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4429, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [09:47<00:13,  8.33it/s]

tensor(12.6618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0335, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4466, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0325, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4514, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 188/300 [09:47<00:13,  8.28it/s]

tensor(12.6506, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4586, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4702, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [09:47<00:13,  8.29it/s]

tensor(12.6436, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4767, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4843, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [09:48<00:12,  8.27it/s]

tensor(12.6338, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4885, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6293, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0275, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4911, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▍   | 194/300 [09:48<00:12,  8.25it/s]

tensor(12.6253, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4980, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5052, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [09:48<00:12,  8.26it/s]

tensor(12.6182, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0257, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5097, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6144, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5055, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 198/300 [09:48<00:12,  8.32it/s]

tensor(12.6103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5089, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5122, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [09:48<00:12,  8.26it/s]

tensor(12.6027, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5169, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([200, 327, 104,  95, 223, 126, 196, 232, 141,  82,  81, 171, 223,  47])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<01:55, 19.37it/s]
  0%|          | 8/2248 [00:00<00:54, 41.48it/s]
  1%|          | 14/2248 [00:00<00:48, 46.07it/s]
  1%|          | 22/2248 [00:00<00:39, 56.91it/s]
  1%|▏         | 29/2248 [00:00<00:37, 59.91it/s]
  2%|▏         | 36/2248 [00:00<00:36, 60.72it/s]
  2%|▏         | 43/2248 [00:00<00:36, 60.52it/s]
  2%|▏         | 51/2248 [00:00<00:33, 64.63it/s]
  3%|▎         | 58/2248 [00:01<00:35, 61.86it/s]
  3%|▎         | 65/2248 [00:01<00:35, 60.96it/s]
  3%|▎         | 72/2248 [00:01<00:35, 61.65it/s]
  4%|▎         | 79/2248 [00:01<01:02, 34.64it/s]
  4%|▎         | 84/2248 [00:01<01:01, 35.18it/s]
  4%|▍         | 89/2248 [00:02<01:25, 25.21it/s]
  4%|▍         | 95/2248 [00:02<01:11, 30.10it/s]
  4%|▍         | 100/2248 [00:02<01:05, 32.81it/s]
  5%|▍         | 106/2248 [00:02<00:56, 38.03it/s]
  5%|▍         | 111/2248 [00:02<01:11, 29.76it/s]
  5%|▌         | 115/2248 [00:02<01:15, 28.41it/s]
  5%|▌         | 119/2248 [00:03<01:38, 21.52it/s]
  5%|▌         | 122/2248 [00:03<02:08, 16.54it/s]
  6%|▌         | 127/2248 [00:03<02:08, 16.51it/s]
  6%|▌         | 130/2248 [00:03<02:00, 17.52it/s]
  6%|▌         | 138/2248 [00:04<01:42, 20.57it/s]
  6%|▋         | 141/2248 [00:04<01:38, 21.29it/s]
  6%|▋         | 145/2248 [00:04<01:47, 19.65it/s]
  7%|▋         | 148/2248 [00:04<01:41, 20.61it/s]
  7%|▋         | 151/2248 [00:05<02:11, 15.94it/s]
  7%|▋         | 153/2248 [00:05<02:39, 13.10it/s]
  7%|▋         | 157/2248 [00:05<02:30, 13.87it/s]
  7%|▋         | 159/2248 [00:05<02:36, 13.33it/s]
  7%|▋         | 161/2248 [00:05<02:45, 12.64it/s]
  7%|▋         | 163/2248 [00:06<02:31, 13.73it/s]
  7%|▋         | 167/2248 [00:06<02:00, 17.28it/s]
  8%|▊         | 169/2248 [00:06<01:57, 17.74it/s]
  8%|▊         | 173/2248 [00:06<01:41, 20.41it/s]
  8%|▊         | 176/2248 [00:06<02:13, 15.49it/s]
  8%|▊         | 178/2248 [00:06<02:15, 15.23it/s]
  8%|▊         | 181/2248 [00:07<01:55, 17.89it/s]
  8%|▊         | 185/2248 [00:07<01:35, 21.59it/s]
  8%|▊         | 188/2248 [00:07<02:01, 16.96it/s]
  8%|▊         | 191/2248 [00:07<01:49, 18.87it/s]
  9%|▊         | 195/2248 [00:07<01:31, 22.51it/s]
  9%|▉         | 198/2248 [00:07<01:54, 17.84it/s]
  9%|▉         | 201/2248 [00:08<01:50, 18.45it/s]
  9%|▉         | 204/2248 [00:08<01:50, 18.46it/s]
  9%|▉         | 207/2248 [00:08<02:14, 15.19it/s]
  9%|▉         | 209/2248 [00:08<02:31, 13.42it/s]
  9%|▉         | 211/2248 [00:09<03:39,  9.29it/s]
  9%|▉         | 213/2248 [00:09<03:50,  8.84it/s]
 10%|▉         | 215/2248 [00:09<03:19, 10.21it/s]
 10%|▉         | 221/2248 [00:09<01:52, 17.96it/s]
 10%|█         | 227/2248 [00:09<01:21, 24.76it/s]
 10%|█         | 234/2248 [00:09<00:59, 33.80it/s]
 11%|█         | 239/2248 [00:09<00:56, 35.43it/s]
 11%|█         | 244/2248 [00:10<00:52, 38.15it/s]
 11%|█         | 252/2248 [00:10<00:46, 42.85it/s]
 11%|█▏        | 257/2248 [00:10<00:46, 42.75it/s]
 12%|█▏        | 263/2248 [00:10<00:57, 34.55it/s]
 12%|█▏        | 267/2248 [00:10<01:23, 23.61it/s]
 12%|█▏        | 271/2248 [00:11<01:44, 18.85it/s]
 12%|█▏        | 275/2248 [00:11<01:55, 17.09it/s]
 12%|█▏        | 278/2248 [00:11<01:51, 17.72it/s]
 13%|█▎        | 284/2248 [00:11<01:23, 23.64it/s]
 13%|█▎        | 290/2248 [00:12<01:26, 22.61it/s]
 13%|█▎        | 293/2248 [00:12<01:52, 17.33it/s]
 13%|█▎        | 296/2248 [00:12<02:15, 14.45it/s]
 13%|█▎        | 298/2248 [00:13<02:34, 12.66it/s]
 13%|█▎        | 300/2248 [00:13<02:29, 13.06it/s]
 13%|█▎        | 303/2248 [00:13<02:33, 12.70it/s]
 14%|█▎        | 305/2248 [00:13<02:31, 12.83it/s]
 14%|█▎        | 307/2248 [00:13<02:46, 11.67it/s]
 14%|█▎        | 309/2248 [00:14<03:27,  9.35it/s]
 14%|█▍        | 311/2248 [00:14<03:06, 10.39it/s]
 14%|█▍        | 313/2248 [00:14<02:48, 11.49it/s]
 14%|█▍        | 315/2248 [00:14<03:32,  9.09it/s]
 14%|█▍        | 317/2248 [00:14<03:10, 10.11it/s]
 14%|█▍        | 319/2248 [00:15<02:50, 11.35it/s]
 14%|█▍        | 322/2248 [00:15<02:23, 13.41it/s]
 14%|█▍        | 324/2248 [00:15<02:34, 12.49it/s]
 15%|█▍        | 326/2248 [00:15<03:00, 10.66it/s]
 15%|█▍        | 328/2248 [00:15<02:47, 11.49it/s]
 15%|█▍        | 332/2248 [00:16<02:36, 12.25it/s]
 15%|█▍        | 334/2248 [00:16<02:22, 13.47it/s]
 15%|█▌        | 339/2248 [00:16<02:12, 14.39it/s]
 15%|█▌        | 341/2248 [00:16<02:15, 14.07it/s]
 15%|█▌        | 343/2248 [00:16<02:51, 11.13it/s]
 15%|█▌        | 345/2248 [00:17<03:42,  8.56it/s]
 15%|█▌        | 346/2248 [00:17<04:12,  7.53it/s]
 15%|█▌        | 348/2248 [00:17<04:27,  7.11it/s]
 16%|█▌        | 349/2248 [00:18<04:31,  7.00it/s]
 16%|█▌        | 351/2248 [00:18<03:40,  8.59it/s]
 16%|█▌        | 353/2248 [00:18<03:42,  8.51it/s]
 16%|█▌        | 355/2248 [00:18<03:12,  9.86it/s]
 16%|█▌        | 357/2248 [00:18<03:22,  9.32it/s]
 16%|█▌        | 360/2248 [00:18<02:28, 12.69it/s]
 16%|█▌        | 362/2248 [00:19<02:42, 11.57it/s]
 16%|█▌        | 364/2248 [00:19<02:26, 12.90it/s]
 16%|█▋        | 370/2248 [00:19<01:24, 22.29it/s]
 17%|█▋        | 373/2248 [00:19<02:12, 14.11it/s]
 17%|█▋        | 379/2248 [00:20<01:51, 16.75it/s]
 17%|█▋        | 382/2248 [00:20<02:13, 13.96it/s]
 17%|█▋        | 384/2248 [00:20<02:21, 13.21it/s]
 17%|█▋        | 386/2248 [00:20<02:29, 12.49it/s]
 17%|█▋        | 388/2248 [00:20<02:42, 11.45it/s]
 17%|█▋        | 390/2248 [00:21<02:41, 11.50it/s]
 17%|█▋        | 393/2248 [00:21<02:15, 13.66it/s]
 18%|█▊        | 395/2248 [00:21<02:37, 11.73it/s]
 18%|█▊        | 399/2248 [00:21<01:52, 16.38it/s]
 18%|█▊        | 405/2248 [00:21<01:15, 24.43it/s]
 18%|█▊        | 411/2248 [00:21<00:57, 32.00it/s]
 19%|█▊        | 417/2248 [00:21<00:47, 38.42it/s]
 19%|█▉        | 424/2248 [00:22<00:39, 45.94it/s]
 19%|█▉        | 431/2248 [00:22<00:37, 47.86it/s]
 19%|█▉        | 437/2248 [00:22<00:59, 30.37it/s]
 20%|█▉        | 442/2248 [00:22<01:17, 23.22it/s]
 20%|█▉        | 446/2248 [00:23<01:39, 18.06it/s]
 20%|█▉        | 449/2248 [00:23<01:52, 15.97it/s]
 20%|██        | 452/2248 [00:23<01:42, 17.48it/s]
 20%|██        | 455/2248 [00:23<02:02, 14.60it/s]
 20%|██        | 457/2248 [00:24<02:14, 13.29it/s]
 20%|██        | 459/2248 [00:24<02:11, 13.63it/s]
 21%|██        | 463/2248 [00:24<02:04, 14.39it/s]
 21%|██        | 465/2248 [00:24<02:39, 11.19it/s]
 21%|██        | 467/2248 [00:24<02:23, 12.41it/s]
 21%|██        | 469/2248 [00:25<02:41, 11.00it/s]
 21%|██        | 472/2248 [00:25<02:06, 14.06it/s]
 21%|██        | 475/2248 [00:25<02:09, 13.73it/s]
 21%|██        | 477/2248 [00:25<02:07, 13.92it/s]
 21%|██▏       | 479/2248 [00:25<02:25, 12.19it/s]
 21%|██▏       | 481/2248 [00:26<03:28,  8.46it/s]
 21%|██▏       | 483/2248 [00:26<03:01,  9.71it/s]
 22%|██▏       | 485/2248 [00:26<03:03,  9.59it/s]
 22%|██▏       | 488/2248 [00:26<02:21, 12.40it/s]
 22%|██▏       | 495/2248 [00:26<01:17, 22.65it/s]
 22%|██▏       | 500/2248 [00:27<01:24, 20.75it/s]
 22%|██▏       | 503/2248 [00:27<01:24, 20.61it/s]
 23%|██▎       | 506/2248 [00:27<01:19, 21.88it/s]
 23%|██▎       | 509/2248 [00:27<01:23, 20.80it/s]
 23%|██▎       | 512/2248 [00:27<01:35, 18.18it/s]
 23%|██▎       | 515/2248 [00:28<02:08, 13.48it/s]
 23%|██▎       | 518/2248 [00:28<02:09, 13.31it/s]
 23%|██▎       | 520/2248 [00:28<02:08, 13.40it/s]
 23%|██▎       | 522/2248 [00:28<02:04, 13.86it/s]
 23%|██▎       | 525/2248 [00:28<01:42, 16.81it/s]
 24%|██▎       | 532/2248 [00:28<01:02, 27.36it/s]
 24%|██▍       | 537/2248 [00:29<00:53, 32.00it/s]
 24%|██▍       | 543/2248 [00:29<00:44, 38.61it/s]
 24%|██▍       | 549/2248 [00:29<00:38, 43.91it/s]
 25%|██▍       | 556/2248 [00:29<00:38, 44.11it/s]
 25%|██▍       | 561/2248 [00:29<00:37, 45.00it/s]
 25%|██▌       | 566/2248 [00:29<00:37, 44.85it/s]
 25%|██▌       | 571/2248 [00:29<00:39, 42.53it/s]
 26%|██▌       | 576/2248 [00:30<01:17, 21.70it/s]
 26%|██▌       | 581/2248 [00:30<01:20, 20.83it/s]
 26%|██▌       | 584/2248 [00:30<01:42, 16.28it/s]
 26%|██▌       | 588/2248 [00:31<01:42, 16.22it/s]
 26%|██▋       | 591/2248 [00:31<01:34, 17.47it/s]
 26%|██▋       | 594/2248 [00:31<01:53, 14.60it/s]
 27%|██▋       | 597/2248 [00:31<01:39, 16.68it/s]
 27%|██▋       | 602/2248 [00:31<01:15, 21.94it/s]
 27%|██▋       | 605/2248 [00:32<02:10, 12.61it/s]
 27%|██▋       | 608/2248 [00:32<03:02,  9.01it/s]
 27%|██▋       | 610/2248 [00:33<03:02,  9.00it/s]
 27%|██▋       | 612/2248 [00:33<02:41, 10.12it/s]
 27%|██▋       | 617/2248 [00:33<01:46, 15.26it/s]
 28%|██▊       | 623/2248 [00:33<01:13, 22.07it/s]
 28%|██▊       | 627/2248 [00:33<01:19, 20.36it/s]
 28%|██▊       | 634/2248 [00:33<00:56, 28.72it/s]
 29%|██▊       | 641/2248 [00:33<00:45, 35.64it/s]
 29%|██▉       | 648/2248 [00:34<00:37, 42.75it/s]
 29%|██▉       | 654/2248 [00:34<00:58, 27.26it/s]
 29%|██▉       | 660/2248 [00:34<01:06, 23.93it/s]
 30%|██▉       | 664/2248 [00:35<01:18, 20.19it/s]
 30%|██▉       | 667/2248 [00:35<01:19, 19.95it/s]
 30%|██▉       | 670/2248 [00:35<01:31, 17.25it/s]
 30%|██▉       | 673/2248 [00:35<01:26, 18.29it/s]
 30%|███       | 678/2248 [00:35<01:26, 18.08it/s]
 30%|███       | 681/2248 [00:36<01:20, 19.46it/s]
 30%|███       | 684/2248 [00:36<01:53, 13.76it/s]
 31%|███       | 686/2248 [00:36<02:32, 10.21it/s]
 31%|███       | 689/2248 [00:36<02:04, 12.50it/s]
 31%|███       | 694/2248 [00:37<01:28, 17.55it/s]
 31%|███       | 698/2248 [00:37<01:12, 21.34it/s]
 31%|███       | 701/2248 [00:37<01:36, 16.01it/s]
 31%|███▏      | 704/2248 [00:37<02:07, 12.09it/s]
 31%|███▏      | 707/2248 [00:38<01:54, 13.51it/s]
 32%|███▏      | 709/2248 [00:38<01:50, 13.98it/s]
 32%|███▏      | 714/2248 [00:38<01:19, 19.21it/s]
 32%|███▏      | 719/2248 [00:38<01:25, 17.82it/s]
 32%|███▏      | 722/2248 [00:38<01:28, 17.26it/s]
 32%|███▏      | 724/2248 [00:38<01:32, 16.49it/s]
 32%|███▏      | 726/2248 [00:39<01:30, 16.74it/s]
 32%|███▏      | 728/2248 [00:39<02:07, 11.88it/s]
 32%|███▏      | 730/2248 [00:39<01:58, 12.79it/s]
 33%|███▎      | 732/2248 [00:39<02:36,  9.67it/s]
 33%|███▎      | 734/2248 [00:40<02:32,  9.94it/s]
 33%|███▎      | 736/2248 [00:40<03:32,  7.12it/s]
 33%|███▎      | 738/2248 [00:40<02:56,  8.58it/s]
 33%|███▎      | 743/2248 [00:40<02:01, 12.40it/s]
 33%|███▎      | 745/2248 [00:41<01:59, 12.54it/s]
 33%|███▎      | 747/2248 [00:41<01:50, 13.59it/s]
 33%|███▎      | 752/2248 [00:41<01:31, 16.43it/s]
 34%|███▎      | 754/2248 [00:41<01:33, 16.05it/s]
 34%|███▍      | 760/2248 [00:41<01:01, 24.39it/s]
 34%|███▍      | 763/2248 [00:41<01:16, 19.37it/s]
 34%|███▍      | 766/2248 [00:42<01:17, 19.05it/s]
 34%|███▍      | 773/2248 [00:42<00:52, 28.33it/s]
 35%|███▍      | 777/2248 [00:42<01:28, 16.60it/s]
 35%|███▍      | 780/2248 [00:42<01:21, 18.11it/s]
 35%|███▌      | 787/2248 [00:42<00:55, 26.47it/s]
 35%|███▌      | 792/2248 [00:43<01:02, 23.45it/s]
 35%|███▌      | 796/2248 [00:43<01:08, 21.24it/s]
 36%|███▌      | 799/2248 [00:43<01:28, 16.38it/s]
 36%|███▌      | 804/2248 [00:43<01:08, 21.15it/s]
 36%|███▌      | 810/2248 [00:43<00:52, 27.44it/s]
 36%|███▌      | 814/2248 [00:44<01:10, 20.45it/s]
 36%|███▋      | 820/2248 [00:44<00:55, 25.67it/s]
 37%|███▋      | 826/2248 [00:44<00:45, 31.28it/s]
 37%|███▋      | 831/2248 [00:44<00:47, 29.80it/s]
 37%|███▋      | 837/2248 [00:44<00:40, 34.82it/s]
 38%|███▊      | 844/2248 [00:44<00:33, 42.20it/s]
 38%|███▊      | 850/2248 [00:45<00:30, 45.53it/s]
 38%|███▊      | 856/2248 [00:45<00:28, 49.09it/s]
 38%|███▊      | 864/2248 [00:45<00:25, 53.96it/s]
 39%|███▊      | 870/2248 [00:45<00:38, 35.43it/s]
 39%|███▉      | 875/2248 [00:45<00:58, 23.46it/s]
 39%|███▉      | 879/2248 [00:46<01:14, 18.27it/s]
 39%|███▉      | 882/2248 [00:46<01:12, 18.72it/s]
 39%|███▉      | 885/2248 [00:46<01:08, 19.81it/s]
 40%|███▉      | 890/2248 [00:46<00:56, 24.10it/s]
 40%|███▉      | 894/2248 [00:47<01:03, 21.31it/s]
 40%|███▉      | 897/2248 [00:47<01:07, 20.09it/s]
 40%|████      | 900/2248 [00:47<01:14, 18.08it/s]
 40%|████      | 903/2248 [00:47<01:35, 14.05it/s]
 40%|████      | 906/2248 [00:48<01:45, 12.76it/s]
 40%|████      | 908/2248 [00:48<02:07, 10.48it/s]
 40%|████      | 910/2248 [00:48<02:25,  9.16it/s]
 41%|████      | 912/2248 [00:48<02:26,  9.13it/s]
 41%|████      | 914/2248 [00:49<02:11, 10.17it/s]
 41%|████      | 916/2248 [00:49<01:58, 11.22it/s]
 41%|████      | 918/2248 [00:49<01:45, 12.65it/s]
 41%|████      | 920/2248 [00:49<01:50, 12.05it/s]
 41%|████      | 922/2248 [00:49<01:38, 13.45it/s]
 41%|████      | 924/2248 [00:49<01:56, 11.40it/s]
 41%|████      | 927/2248 [00:49<01:41, 13.05it/s]
 41%|████▏     | 929/2248 [00:50<02:03, 10.69it/s]
 41%|████▏     | 931/2248 [00:50<02:38,  8.33it/s]
 42%|████▏     | 933/2248 [00:50<02:18,  9.52it/s]
 42%|████▏     | 935/2248 [00:50<01:58, 11.08it/s]
 42%|████▏     | 938/2248 [00:50<01:30, 14.41it/s]
 42%|████▏     | 940/2248 [00:51<01:24, 15.44it/s]
 42%|████▏     | 944/2248 [00:51<01:24, 15.44it/s]
 42%|████▏     | 946/2248 [00:51<01:45, 12.35it/s]
 42%|████▏     | 949/2248 [00:51<01:49, 11.91it/s]
 42%|████▏     | 952/2248 [00:52<01:50, 11.72it/s]
 42%|████▏     | 954/2248 [00:52<01:42, 12.63it/s]
 43%|████▎     | 956/2248 [00:52<01:49, 11.81it/s]
 43%|████▎     | 958/2248 [00:52<02:38,  8.16it/s]
 43%|████▎     | 960/2248 [00:53<02:40,  8.01it/s]
 43%|████▎     | 961/2248 [00:53<02:54,  7.37it/s]
 43%|████▎     | 964/2248 [00:53<02:00, 10.64it/s]
 43%|████▎     | 966/2248 [00:53<02:05, 10.19it/s]
 43%|████▎     | 968/2248 [00:53<02:21,  9.06it/s]
 43%|████▎     | 970/2248 [00:54<02:58,  7.16it/s]
 43%|████▎     | 973/2248 [00:54<02:07, 10.01it/s]
 43%|████▎     | 975/2248 [00:54<02:15,  9.38it/s]
 43%|████▎     | 977/2248 [00:55<02:28,  8.56it/s]
 44%|████▎     | 979/2248 [00:55<02:38,  8.02it/s]
 44%|████▎     | 981/2248 [00:55<02:41,  7.87it/s]
 44%|████▍     | 984/2248 [00:55<01:58, 10.66it/s]
 44%|████▍     | 986/2248 [00:55<02:09,  9.76it/s]
 44%|████▍     | 988/2248 [00:56<02:18,  9.10it/s]
 44%|████▍     | 992/2248 [00:56<01:33, 13.47it/s]
 44%|████▍     | 994/2248 [00:56<01:49, 11.46it/s]
 44%|████▍     | 998/2248 [00:56<01:37, 12.77it/s]
 44%|████▍     | 1000/2248 [00:57<01:51, 11.23it/s]
 45%|████▍     | 1002/2248 [00:57<02:06,  9.87it/s]
 45%|████▍     | 1004/2248 [00:57<02:12,  9.42it/s]
 45%|████▍     | 1006/2248 [00:58<02:44,  7.56it/s]
 45%|████▍     | 1007/2248 [00:58<02:59,  6.91it/s]
 45%|████▍     | 1008/2248 [00:58<03:12,  6.44it/s]
 45%|████▍     | 1011/2248 [00:58<02:10,  9.46it/s]
 45%|████▌     | 1018/2248 [00:58<01:05, 18.87it/s]
 46%|████▌     | 1024/2248 [00:58<00:46, 26.56it/s]
 46%|████▌     | 1031/2248 [00:58<00:35, 34.31it/s]
 46%|████▌     | 1037/2248 [00:59<00:31, 38.22it/s]
 46%|████▋     | 1042/2248 [00:59<00:29, 40.25it/s]
 47%|████▋     | 1048/2248 [00:59<00:26, 44.83it/s]
 47%|████▋     | 1053/2248 [00:59<00:29, 40.64it/s]
 47%|████▋     | 1058/2248 [00:59<00:41, 28.78it/s]
 47%|████▋     | 1062/2248 [00:59<00:38, 30.68it/s]
 47%|████▋     | 1066/2248 [00:59<00:40, 29.12it/s]
 48%|████▊     | 1070/2248 [01:00<00:40, 28.97it/s]
 48%|████▊     | 1075/2248 [01:00<00:37, 31.54it/s]
 48%|████▊     | 1079/2248 [01:00<00:45, 25.50it/s]
 48%|████▊     | 1086/2248 [01:00<00:34, 33.72it/s]
 48%|████▊     | 1090/2248 [01:01<01:13, 15.81it/s]
 49%|████▊     | 1093/2248 [01:01<01:32, 12.51it/s]
 49%|████▉     | 1096/2248 [01:01<01:21, 14.09it/s]
 49%|████▉     | 1104/2248 [01:01<00:50, 22.60it/s]
 49%|████▉     | 1110/2248 [01:02<00:40, 28.38it/s]
 50%|████▉     | 1117/2248 [01:02<00:32, 35.33it/s]
 50%|█████     | 1124/2248 [01:02<00:27, 41.07it/s]
 50%|█████     | 1130/2248 [01:02<00:27, 40.77it/s]
 51%|█████     | 1138/2248 [01:02<00:22, 49.19it/s]
 51%|█████     | 1144/2248 [01:02<00:32, 34.26it/s]
 51%|█████     | 1149/2248 [01:03<00:45, 23.95it/s]
 51%|█████▏    | 1153/2248 [01:03<01:05, 16.72it/s]
 51%|█████▏    | 1156/2248 [01:04<01:15, 14.46it/s]
 52%|█████▏    | 1159/2248 [01:04<01:28, 12.34it/s]
 52%|█████▏    | 1162/2248 [01:04<01:19, 13.73it/s]
 52%|█████▏    | 1164/2248 [01:04<01:17, 13.98it/s]
 52%|█████▏    | 1167/2248 [01:04<01:06, 16.32it/s]
 52%|█████▏    | 1170/2248 [01:05<01:15, 14.35it/s]
 52%|█████▏    | 1172/2248 [01:05<01:35, 11.28it/s]
 52%|█████▏    | 1174/2248 [01:05<01:28, 12.14it/s]
 52%|█████▏    | 1176/2248 [01:05<01:37, 10.98it/s]
 52%|█████▏    | 1178/2248 [01:05<01:50,  9.68it/s]
 52%|█████▏    | 1180/2248 [01:06<01:50,  9.71it/s]
 53%|█████▎    | 1182/2248 [01:06<01:57,  9.06it/s]
 53%|█████▎    | 1183/2248 [01:06<02:09,  8.19it/s]
 53%|█████▎    | 1184/2248 [01:06<02:23,  7.39it/s]
 53%|█████▎    | 1186/2248 [01:06<01:57,  9.00it/s]
 53%|█████▎    | 1187/2248 [01:07<02:13,  7.97it/s]
 53%|█████▎    | 1188/2248 [01:07<02:33,  6.92it/s]
 53%|█████▎    | 1192/2248 [01:07<01:27, 12.14it/s]
 53%|█████▎    | 1194/2248 [01:07<01:43, 10.14it/s]
 53%|█████▎    | 1200/2248 [01:07<00:56, 18.67it/s]
 54%|█████▎    | 1203/2248 [01:08<01:09, 15.00it/s]
 54%|█████▎    | 1206/2248 [01:08<01:19, 13.13it/s]
 54%|█████▎    | 1208/2248 [01:08<01:22, 12.57it/s]
 54%|█████▍    | 1210/2248 [01:08<01:20, 12.90it/s]
 54%|█████▍    | 1214/2248 [01:08<01:00, 17.05it/s]
 54%|█████▍    | 1217/2248 [01:09<01:06, 15.40it/s]
 54%|█████▍    | 1222/2248 [01:09<00:54, 18.87it/s]
 54%|█████▍    | 1225/2248 [01:09<00:56, 18.22it/s]
 55%|█████▍    | 1227/2248 [01:09<01:07, 15.23it/s]
 55%|█████▍    | 1229/2248 [01:09<01:11, 14.18it/s]
 55%|█████▍    | 1231/2248 [01:10<01:36, 10.52it/s]
 55%|█████▍    | 1233/2248 [01:10<01:30, 11.26it/s]
 55%|█████▍    | 1236/2248 [01:10<01:11, 14.11it/s]
 55%|█████▌    | 1240/2248 [01:10<01:04, 15.57it/s]
 55%|█████▌    | 1242/2248 [01:10<01:03, 15.83it/s]
 55%|█████▌    | 1244/2248 [01:11<01:13, 13.73it/s]
 55%|█████▌    | 1246/2248 [01:11<01:27, 11.46it/s]
 56%|█████▌    | 1248/2248 [01:11<01:37, 10.24it/s]
 56%|█████▌    | 1250/2248 [01:11<01:25, 11.65it/s]
 56%|█████▌    | 1255/2248 [01:11<00:53, 18.70it/s]
 56%|█████▌    | 1260/2248 [01:11<00:42, 23.41it/s]
 56%|█████▌    | 1264/2248 [01:12<00:52, 18.74it/s]
 56%|█████▋    | 1267/2248 [01:12<00:57, 16.92it/s]
 56%|█████▋    | 1270/2248 [01:12<00:52, 18.55it/s]
 57%|█████▋    | 1273/2248 [01:12<00:53, 18.24it/s]
 57%|█████▋    | 1276/2248 [01:13<01:03, 15.21it/s]
 57%|█████▋    | 1278/2248 [01:13<01:03, 15.20it/s]
 57%|█████▋    | 1280/2248 [01:13<01:17, 12.55it/s]
 57%|█████▋    | 1282/2248 [01:13<01:17, 12.42it/s]
 57%|█████▋    | 1286/2248 [01:13<00:56, 17.10it/s]
 57%|█████▋    | 1291/2248 [01:13<00:41, 22.80it/s]
 58%|█████▊    | 1295/2248 [01:14<00:48, 19.66it/s]
 58%|█████▊    | 1298/2248 [01:14<00:59, 15.98it/s]
 58%|█████▊    | 1300/2248 [01:14<01:10, 13.47it/s]
 58%|█████▊    | 1302/2248 [01:14<01:05, 14.41it/s]
 58%|█████▊    | 1304/2248 [01:14<01:08, 13.86it/s]
 58%|█████▊    | 1306/2248 [01:15<01:12, 13.02it/s]
 58%|█████▊    | 1308/2248 [01:15<01:06, 14.03it/s]
 58%|█████▊    | 1313/2248 [01:15<00:44, 21.18it/s]
 59%|█████▊    | 1316/2248 [01:15<00:59, 15.58it/s]
 59%|█████▊    | 1318/2248 [01:15<01:13, 12.58it/s]
 59%|█████▉    | 1321/2248 [01:15<01:00, 15.37it/s]
 59%|█████▉    | 1325/2248 [01:16<00:57, 16.16it/s]
 59%|█████▉    | 1327/2248 [01:16<01:00, 15.31it/s]
 59%|█████▉    | 1329/2248 [01:16<01:12, 12.68it/s]
 59%|█████▉    | 1331/2248 [01:16<01:09, 13.16it/s]
 59%|█████▉    | 1335/2248 [01:16<01:01, 14.82it/s]
 59%|█████▉    | 1337/2248 [01:17<01:01, 14.83it/s]
 60%|█████▉    | 1342/2248 [01:17<00:55, 16.34it/s]
 60%|█████▉    | 1345/2248 [01:17<01:04, 13.98it/s]
 60%|█████▉    | 1347/2248 [01:17<01:13, 12.24it/s]
 60%|██████    | 1349/2248 [01:18<01:23, 10.78it/s]
 60%|██████    | 1352/2248 [01:18<01:09, 12.94it/s]
 60%|██████    | 1357/2248 [01:18<00:47, 18.78it/s]
 61%|██████    | 1363/2248 [01:18<00:33, 26.32it/s]
 61%|██████    | 1367/2248 [01:18<00:53, 16.51it/s]
 61%|██████    | 1370/2248 [01:19<00:59, 14.86it/s]
 61%|██████    | 1373/2248 [01:19<01:06, 13.12it/s]
 61%|██████    | 1376/2248 [01:19<01:07, 12.83it/s]
 61%|██████▏   | 1378/2248 [01:20<01:22, 10.58it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 303.37it/s]

[[np.int64(0), False, 12], [np.int64(1), False, 7], [np.int64(2), False, 0], [np.int64(3), False, 8], [np.int64(4), False, 12], [np.int64(5), False, 4], [np.int64(6), False, 1], [np.int64(9), False, 6], [np.int64(10), False, 11], [np.int64(11), False, 12], [np.int64(13), False, 9]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.5995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8004, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [11:55<1:03:02, 38.21s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [11:56<43:45, 26.79s/it]

tensor(12.5992, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2938, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6114, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0350, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0233, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [11:56<14:40,  9.27s/it]

tensor(12.6366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0471, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2338, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6500, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0536, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1359, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▊   | 206/300 [11:56<10:13,  6.52s/it]

tensor(12.6448, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0545, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2186, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0572, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2245, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [11:56<03:30,  2.32s/it]

tensor(12.6114, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0600, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2790, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6145, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0595, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2490, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [11:57<01:46,  1.20s/it]

tensor(12.6386, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0573, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2684, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0569, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3388, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [11:57<00:56,  1.55it/s]

tensor(12.6599, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0558, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3572, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6453, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0546, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3224, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 215/300 [11:57<00:32,  2.65it/s]

tensor(12.6291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0536, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3635, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6197, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0526, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3674, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [11:57<00:20,  4.09it/s]

tensor(12.6154, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0509, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3760, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6153, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0477, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4166, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [11:58<00:14,  5.55it/s]

tensor(12.6148, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0449, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4279, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0424, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4255, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [11:58<00:11,  6.78it/s]

tensor(12.6076, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0402, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5999, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0380, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4539, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [11:58<00:10,  7.58it/s]

tensor(12.5927, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0365, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4531, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5880, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0355, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4465, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [11:58<00:09,  8.07it/s]

tensor(12.5836, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0348, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4464, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5790, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0342, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4176, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 226/300 [11:58<00:09,  8.17it/s]

tensor(12.5750, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0334, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4179, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5704, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4312, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 228/300 [11:59<00:08,  8.17it/s]

tensor(12.5654, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0319, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4414, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5610, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4412, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 230/300 [11:59<00:08,  8.16it/s]

tensor(12.5574, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0303, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4519, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5542, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0294, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4495, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [11:59<00:08,  8.22it/s]

tensor(12.5516, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4530, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5486, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4521, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [12:00<00:07,  8.31it/s]

tensor(12.5451, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4519, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5421, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4518, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [12:00<00:07,  8.34it/s]

tensor(12.5388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4510, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5356, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4514, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [12:00<00:07,  8.45it/s]

tensor(12.5328, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4519, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5299, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4541, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 240/300 [12:00<00:07,  8.37it/s]

tensor(12.5270, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4518, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5242, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4554, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [12:00<00:06,  8.44it/s]

tensor(12.5215, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4557, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5186, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4565, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [12:01<00:06,  8.56it/s]

tensor(12.5160, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4542, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5132, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0234, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4560, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 246/300 [12:01<00:06,  8.39it/s]

tensor(12.5105, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4573, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4630, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 248/300 [12:01<00:06,  8.37it/s]

tensor(12.5055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4649, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5031, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4623, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [12:01<00:06,  8.25it/s]

tensor(12.5009, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4617, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([207, 353, 150, 118, 253, 162, 148,  70, 133, 116, 122,  78, 158, 180])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:02, 18.26it/s]
  0%|          | 8/2248 [00:00<00:53, 41.84it/s]
  1%|          | 13/2248 [00:00<00:54, 40.83it/s]
  1%|          | 21/2248 [00:00<00:41, 53.05it/s]
  1%|          | 27/2248 [00:00<00:51, 43.11it/s]
  1%|▏         | 32/2248 [00:00<00:52, 41.92it/s]
  2%|▏         | 37/2248 [00:00<01:04, 34.11it/s]
  2%|▏         | 42/2248 [00:01<01:00, 36.21it/s]
  2%|▏         | 47/2248 [00:01<00:56, 38.86it/s]
  2%|▏         | 55/2248 [00:01<00:46, 47.50it/s]
  3%|▎         | 61/2248 [00:01<00:43, 50.40it/s]
  3%|▎         | 68/2248 [00:01<00:39, 54.52it/s]
  3%|▎         | 75/2248 [00:01<00:43, 50.37it/s]
  4%|▎         | 81/2248 [00:02<01:19, 27.24it/s]
  4%|▍         | 86/2248 [00:02<01:21, 26.38it/s]
  4%|▍         | 90/2248 [00:02<01:32, 23.24it/s]
  4%|▍         | 93/2248 [00:02<01:32, 23.28it/s]
  4%|▍         | 96/2248 [00:02<01:32, 23.24it/s]
  4%|▍         | 99/2248 [00:03<02:09, 16.65it/s]
  5%|▍         | 102/2248 [00:03<02:21, 15.17it/s]
  5%|▍         | 104/2248 [00:03<02:46, 12.91it/s]
  5%|▍         | 108/2248 [00:03<02:09, 16.59it/s]
  5%|▍         | 111/2248 [00:04<02:19, 15.34it/s]
  5%|▌         | 113/2248 [00:04<02:46, 12.85it/s]
  5%|▌         | 116/2248 [00:04<02:50, 12.53it/s]
  5%|▌         | 118/2248 [00:04<03:55,  9.03it/s]
  5%|▌         | 120/2248 [00:05<03:40,  9.64it/s]
  5%|▌         | 122/2248 [00:05<03:19, 10.67it/s]
  6%|▌         | 126/2248 [00:05<02:18, 15.31it/s]
  6%|▌         | 129/2248 [00:05<03:29, 10.13it/s]
  6%|▌         | 132/2248 [00:06<02:53, 12.19it/s]
  6%|▌         | 136/2248 [00:06<02:26, 14.42it/s]
  6%|▌         | 138/2248 [00:06<02:56, 11.96it/s]
  6%|▌         | 140/2248 [00:06<02:41, 13.03it/s]
  6%|▋         | 145/2248 [00:06<02:16, 15.43it/s]
  7%|▋         | 147/2248 [00:06<02:12, 15.87it/s]
  7%|▋         | 151/2248 [00:07<02:13, 15.74it/s]
  7%|▋         | 153/2248 [00:07<02:14, 15.55it/s]
  7%|▋         | 156/2248 [00:07<02:29, 13.97it/s]
  7%|▋         | 158/2248 [00:08<03:37,  9.62it/s]
  7%|▋         | 160/2248 [00:08<03:55,  8.88it/s]
  7%|▋         | 162/2248 [00:08<03:28, 10.01it/s]
  7%|▋         | 165/2248 [00:08<03:28,  9.97it/s]
  7%|▋         | 167/2248 [00:08<03:21, 10.33it/s]
  8%|▊         | 169/2248 [00:09<02:59, 11.61it/s]
  8%|▊         | 171/2248 [00:09<02:46, 12.47it/s]
  8%|▊         | 173/2248 [00:09<03:10, 10.92it/s]
  8%|▊         | 176/2248 [00:09<03:06, 11.10it/s]
  8%|▊         | 178/2248 [00:09<03:23, 10.17it/s]
  8%|▊         | 180/2248 [00:10<03:42,  9.28it/s]
  8%|▊         | 182/2248 [00:10<03:25, 10.03it/s]
  8%|▊         | 184/2248 [00:10<03:16, 10.51it/s]
  8%|▊         | 186/2248 [00:10<03:34,  9.62it/s]
  8%|▊         | 188/2248 [00:10<03:25, 10.01it/s]
  8%|▊         | 190/2248 [00:11<04:14,  8.10it/s]
  8%|▊         | 191/2248 [00:11<04:07,  8.32it/s]
  9%|▊         | 193/2248 [00:11<04:19,  7.91it/s]
  9%|▊         | 194/2248 [00:11<04:13,  8.11it/s]
  9%|▊         | 195/2248 [00:12<04:50,  7.07it/s]
  9%|▉         | 197/2248 [00:12<03:45,  9.11it/s]
  9%|▉         | 199/2248 [00:12<03:14, 10.54it/s]
  9%|▉         | 201/2248 [00:12<03:44,  9.14it/s]
  9%|▉         | 203/2248 [00:12<03:46,  9.03it/s]
  9%|▉         | 205/2248 [00:13<04:00,  8.48it/s]
  9%|▉         | 206/2248 [00:13<04:39,  7.30it/s]
  9%|▉         | 207/2248 [00:13<05:15,  6.48it/s]
  9%|▉         | 208/2248 [00:13<05:32,  6.14it/s]
  9%|▉         | 210/2248 [00:13<05:11,  6.54it/s]
  9%|▉         | 212/2248 [00:14<04:43,  7.18it/s]
 10%|▉         | 214/2248 [00:14<03:43,  9.10it/s]
 10%|▉         | 220/2248 [00:14<01:53, 17.80it/s]
 10%|█         | 227/2248 [00:14<01:18, 25.91it/s]
 10%|█         | 231/2248 [00:14<01:16, 26.44it/s]
 11%|█         | 238/2248 [00:14<00:56, 35.33it/s]
 11%|█         | 243/2248 [00:14<01:02, 32.13it/s]
 11%|█         | 248/2248 [00:15<00:56, 35.53it/s]
 11%|█         | 252/2248 [00:15<01:07, 29.65it/s]
 11%|█▏        | 256/2248 [00:15<01:07, 29.47it/s]
 12%|█▏        | 263/2248 [00:15<00:55, 36.07it/s]
 12%|█▏        | 267/2248 [00:15<01:05, 30.07it/s]
 12%|█▏        | 271/2248 [00:16<01:29, 22.17it/s]
 12%|█▏        | 274/2248 [00:16<01:27, 22.63it/s]
 12%|█▏        | 277/2248 [00:16<02:21, 13.90it/s]
 12%|█▏        | 280/2248 [00:16<02:13, 14.70it/s]
 13%|█▎        | 282/2248 [00:17<02:29, 13.18it/s]
 13%|█▎        | 284/2248 [00:17<02:19, 14.05it/s]
 13%|█▎        | 287/2248 [00:17<02:26, 13.39it/s]
 13%|█▎        | 289/2248 [00:17<02:23, 13.69it/s]
 13%|█▎        | 291/2248 [00:17<03:05, 10.58it/s]
 13%|█▎        | 293/2248 [00:18<03:22,  9.65it/s]
 13%|█▎        | 295/2248 [00:18<03:35,  9.05it/s]
 13%|█▎        | 298/2248 [00:18<03:05, 10.49it/s]
 13%|█▎        | 300/2248 [00:18<02:54, 11.17it/s]
 13%|█▎        | 303/2248 [00:19<02:56, 11.03it/s]
 14%|█▎        | 305/2248 [00:19<03:04, 10.53it/s]
 14%|█▎        | 307/2248 [00:19<03:59,  8.11it/s]
 14%|█▎        | 308/2248 [00:19<04:00,  8.07it/s]
 14%|█▎        | 309/2248 [00:19<04:26,  7.28it/s]
 14%|█▍        | 311/2248 [00:20<03:34,  9.05it/s]
 14%|█▍        | 313/2248 [00:20<03:28,  9.27it/s]
 14%|█▍        | 315/2248 [00:20<04:19,  7.46it/s]
 14%|█▍        | 317/2248 [00:20<03:31,  9.12it/s]
 14%|█▍        | 320/2248 [00:20<02:41, 11.94it/s]
 14%|█▍        | 322/2248 [00:21<02:37, 12.24it/s]
 14%|█▍        | 324/2248 [00:21<02:28, 12.96it/s]
 15%|█▍        | 326/2248 [00:21<02:39, 12.06it/s]
 15%|█▍        | 328/2248 [00:21<02:38, 12.09it/s]
 15%|█▍        | 332/2248 [00:21<02:08, 14.87it/s]
 15%|█▍        | 334/2248 [00:21<02:03, 15.55it/s]
 15%|█▌        | 339/2248 [00:22<01:50, 17.21it/s]
 15%|█▌        | 341/2248 [00:22<01:54, 16.70it/s]
 15%|█▌        | 343/2248 [00:22<02:13, 14.27it/s]
 15%|█▌        | 345/2248 [00:22<03:19,  9.53it/s]
 15%|█▌        | 347/2248 [00:23<04:18,  7.36it/s]
 15%|█▌        | 348/2248 [00:23<04:41,  6.74it/s]
 16%|█▌        | 349/2248 [00:23<05:03,  6.25it/s]
 16%|█▌        | 352/2248 [00:23<03:23,  9.33it/s]
 16%|█▌        | 354/2248 [00:24<03:18,  9.55it/s]
 16%|█▌        | 356/2248 [00:24<03:59,  7.91it/s]
 16%|█▌        | 358/2248 [00:24<03:17,  9.56it/s]
 16%|█▌        | 362/2248 [00:24<02:42, 11.64it/s]
 16%|█▌        | 364/2248 [00:24<02:39, 11.79it/s]
 16%|█▋        | 366/2248 [00:25<02:35, 12.11it/s]
 16%|█▋        | 368/2248 [00:25<02:35, 12.07it/s]
 17%|█▋        | 371/2248 [00:25<02:31, 12.37it/s]
 17%|█▋        | 373/2248 [00:25<02:20, 13.38it/s]
 17%|█▋        | 375/2248 [00:25<02:22, 13.15it/s]
 17%|█▋        | 377/2248 [00:26<03:00, 10.36it/s]
 17%|█▋        | 379/2248 [00:26<03:32,  8.79it/s]
 17%|█▋        | 381/2248 [00:26<03:44,  8.32it/s]
 17%|█▋        | 384/2248 [00:26<03:25,  9.07it/s]
 17%|█▋        | 387/2248 [00:27<02:39, 11.64it/s]
 17%|█▋        | 389/2248 [00:27<03:40,  8.42it/s]
 17%|█▋        | 391/2248 [00:27<03:20,  9.27it/s]
 17%|█▋        | 393/2248 [00:27<03:33,  8.68it/s]
 18%|█▊        | 395/2248 [00:28<03:39,  8.43it/s]
 18%|█▊        | 400/2248 [00:28<02:10, 14.16it/s]
 18%|█▊        | 407/2248 [00:28<01:18, 23.41it/s]
 18%|█▊        | 411/2248 [00:28<01:09, 26.32it/s]
 19%|█▊        | 416/2248 [00:28<00:59, 30.80it/s]
 19%|█▉        | 422/2248 [00:28<00:49, 36.90it/s]
 19%|█▉        | 427/2248 [00:28<00:51, 35.47it/s]
 19%|█▉        | 433/2248 [00:28<00:44, 40.94it/s]
 19%|█▉        | 438/2248 [00:29<01:00, 29.85it/s]
 20%|█▉        | 442/2248 [00:29<01:20, 22.57it/s]
 20%|█▉        | 446/2248 [00:29<01:42, 17.63it/s]
 20%|█▉        | 449/2248 [00:30<01:54, 15.76it/s]
 20%|██        | 452/2248 [00:30<01:43, 17.39it/s]
 20%|██        | 455/2248 [00:30<02:18, 12.96it/s]
 20%|██        | 457/2248 [00:30<02:15, 13.21it/s]
 20%|██        | 459/2248 [00:30<02:08, 13.88it/s]
 21%|██        | 461/2248 [00:31<02:24, 12.33it/s]
 21%|██        | 463/2248 [00:31<02:39, 11.20it/s]
 21%|██        | 465/2248 [00:31<03:08,  9.44it/s]
 21%|██        | 467/2248 [00:31<02:43, 10.88it/s]
 21%|██        | 469/2248 [00:32<02:39, 11.15it/s]
 21%|██        | 471/2248 [00:32<02:26, 12.16it/s]
 21%|██        | 473/2248 [00:32<02:18, 12.79it/s]
 21%|██        | 475/2248 [00:32<02:41, 10.96it/s]
 21%|██        | 477/2248 [00:32<02:33, 11.50it/s]
 21%|██▏       | 479/2248 [00:33<03:32,  8.34it/s]
 21%|██▏       | 481/2248 [00:33<03:49,  7.71it/s]
 21%|██▏       | 483/2248 [00:33<03:10,  9.24it/s]
 22%|██▏       | 490/2248 [00:33<01:32, 18.99it/s]
 22%|██▏       | 497/2248 [00:33<01:01, 28.50it/s]
 22%|██▏       | 501/2248 [00:33<01:15, 23.13it/s]
 22%|██▏       | 505/2248 [00:34<01:12, 24.13it/s]
 23%|██▎       | 509/2248 [00:34<01:13, 23.54it/s]
 23%|██▎       | 512/2248 [00:34<01:19, 21.83it/s]
 23%|██▎       | 515/2248 [00:34<01:53, 15.23it/s]
 23%|██▎       | 517/2248 [00:34<01:48, 15.91it/s]
 23%|██▎       | 519/2248 [00:35<02:05, 13.81it/s]
 23%|██▎       | 521/2248 [00:35<02:05, 13.80it/s]
 23%|██▎       | 525/2248 [00:35<01:33, 18.37it/s]
 24%|██▎       | 530/2248 [00:35<01:09, 24.61it/s]
 24%|██▍       | 537/2248 [00:35<00:49, 34.63it/s]
 24%|██▍       | 543/2248 [00:35<00:42, 40.30it/s]
 24%|██▍       | 549/2248 [00:35<00:37, 44.74it/s]
 25%|██▍       | 554/2248 [00:36<00:52, 32.23it/s]
 25%|██▍       | 559/2248 [00:36<01:11, 23.58it/s]
 25%|██▌       | 563/2248 [00:36<01:09, 24.33it/s]
 25%|██▌       | 570/2248 [00:36<00:54, 30.87it/s]
 26%|██▌       | 574/2248 [00:37<01:27, 19.11it/s]
 26%|██▌       | 577/2248 [00:37<01:26, 19.31it/s]
 26%|██▌       | 580/2248 [00:37<01:23, 20.01it/s]
 26%|██▌       | 583/2248 [00:37<01:58, 14.08it/s]
 26%|██▌       | 585/2248 [00:38<02:08, 12.89it/s]
 26%|██▌       | 587/2248 [00:38<02:10, 12.71it/s]
 26%|██▌       | 589/2248 [00:38<02:31, 10.97it/s]
 26%|██▋       | 592/2248 [00:38<02:25, 11.37it/s]
 26%|██▋       | 594/2248 [00:38<02:15, 12.18it/s]
 27%|██▋       | 600/2248 [00:39<01:36, 17.09it/s]
 27%|██▋       | 602/2248 [00:39<01:37, 16.88it/s]
 27%|██▋       | 604/2248 [00:39<02:28, 11.04it/s]
 27%|██▋       | 606/2248 [00:40<03:11,  8.58it/s]
 27%|██▋       | 608/2248 [00:40<03:50,  7.13it/s]
 27%|██▋       | 609/2248 [00:40<03:57,  6.91it/s]
 27%|██▋       | 611/2248 [00:40<03:17,  8.30it/s]
 27%|██▋       | 614/2248 [00:40<02:21, 11.54it/s]
 28%|██▊       | 619/2248 [00:40<01:30, 18.08it/s]
 28%|██▊       | 623/2248 [00:41<01:14, 21.85it/s]
 28%|██▊       | 628/2248 [00:41<00:58, 27.73it/s]
 28%|██▊       | 634/2248 [00:41<00:48, 33.51it/s]
 28%|██▊       | 639/2248 [00:41<00:43, 37.05it/s]
 29%|██▊       | 644/2248 [00:41<00:40, 39.32it/s]
 29%|██▉       | 650/2248 [00:41<00:49, 32.01it/s]
 29%|██▉       | 654/2248 [00:42<01:26, 18.47it/s]
 29%|██▉       | 658/2248 [00:42<01:14, 21.32it/s]
 29%|██▉       | 662/2248 [00:42<01:44, 15.19it/s]
 30%|██▉       | 665/2248 [00:43<01:55, 13.65it/s]
 30%|██▉       | 668/2248 [00:43<01:42, 15.43it/s]
 30%|██▉       | 671/2248 [00:43<01:55, 13.69it/s]
 30%|██▉       | 674/2248 [00:43<01:39, 15.79it/s]
 30%|███       | 678/2248 [00:43<01:19, 19.68it/s]
 30%|███       | 682/2248 [00:43<01:11, 21.82it/s]
 30%|███       | 685/2248 [00:44<02:11, 11.92it/s]
 31%|███       | 688/2248 [00:44<02:16, 11.40it/s]
 31%|███       | 691/2248 [00:44<02:08, 12.15it/s]
 31%|███       | 694/2248 [00:45<01:57, 13.26it/s]
 31%|███       | 696/2248 [00:45<02:05, 12.35it/s]
 31%|███       | 698/2248 [00:45<02:04, 12.40it/s]
 31%|███       | 700/2248 [00:45<02:24, 10.71it/s]
 31%|███       | 702/2248 [00:45<02:25, 10.62it/s]
 31%|███▏      | 704/2248 [00:46<02:43,  9.44it/s]
 31%|███▏      | 706/2248 [00:46<02:29, 10.29it/s]
 32%|███▏      | 710/2248 [00:46<01:43, 14.89it/s]
 32%|███▏      | 712/2248 [00:46<02:08, 11.94it/s]
 32%|███▏      | 714/2248 [00:46<02:08, 11.95it/s]
 32%|███▏      | 716/2248 [00:47<01:59, 12.84it/s]
 32%|███▏      | 719/2248 [00:47<01:56, 13.14it/s]
 32%|███▏      | 721/2248 [00:47<02:21, 10.78it/s]
 32%|███▏      | 723/2248 [00:47<02:12, 11.48it/s]
 32%|███▏      | 725/2248 [00:47<02:27, 10.32it/s]
 32%|███▏      | 727/2248 [00:48<02:55,  8.65it/s]
 32%|███▏      | 728/2248 [00:48<02:56,  8.61it/s]
 32%|███▏      | 730/2248 [00:48<02:27, 10.28it/s]
 33%|███▎      | 733/2248 [00:48<01:56, 13.06it/s]
 33%|███▎      | 735/2248 [00:48<01:45, 14.32it/s]
 33%|███▎      | 737/2248 [00:49<02:29, 10.10it/s]
 33%|███▎      | 741/2248 [00:49<01:39, 15.19it/s]
 33%|███▎      | 744/2248 [00:49<02:14, 11.15it/s]
 33%|███▎      | 746/2248 [00:49<02:01, 12.33it/s]
 33%|███▎      | 748/2248 [00:49<01:51, 13.50it/s]
 33%|███▎      | 752/2248 [00:50<01:39, 15.06it/s]
 34%|███▎      | 754/2248 [00:50<02:12, 11.24it/s]
 34%|███▎      | 757/2248 [00:50<01:46, 13.94it/s]
 34%|███▍      | 762/2248 [00:50<01:19, 18.79it/s]
 34%|███▍      | 767/2248 [00:50<01:20, 18.31it/s]
 34%|███▍      | 770/2248 [00:51<01:15, 19.56it/s]
 34%|███▍      | 773/2248 [00:51<01:26, 17.05it/s]
 34%|███▍      | 775/2248 [00:51<02:16, 10.79it/s]
 35%|███▍      | 777/2248 [00:51<02:25, 10.08it/s]
 35%|███▍      | 780/2248 [00:52<01:57, 12.55it/s]
 35%|███▍      | 784/2248 [00:52<01:46, 13.80it/s]
 35%|███▌      | 787/2248 [00:52<01:33, 15.62it/s]
 35%|███▌      | 792/2248 [00:52<01:23, 17.42it/s]
 35%|███▌      | 794/2248 [00:52<01:23, 17.50it/s]
 35%|███▌      | 797/2248 [00:52<01:21, 17.82it/s]
 36%|███▌      | 799/2248 [00:53<01:19, 18.15it/s]
 36%|███▌      | 805/2248 [00:53<00:54, 26.41it/s]
 36%|███▌      | 809/2248 [00:53<00:50, 28.46it/s]
 36%|███▌      | 813/2248 [00:53<01:08, 21.06it/s]
 36%|███▋      | 817/2248 [00:53<00:58, 24.37it/s]
 36%|███▋      | 820/2248 [00:53<01:10, 20.29it/s]
 37%|███▋      | 823/2248 [00:54<01:06, 21.35it/s]
 37%|███▋      | 826/2248 [00:54<01:03, 22.51it/s]
 37%|███▋      | 829/2248 [00:54<01:11, 19.76it/s]
 37%|███▋      | 832/2248 [00:54<01:16, 18.56it/s]
 37%|███▋      | 840/2248 [00:54<00:45, 30.62it/s]
 38%|███▊      | 846/2248 [00:54<00:38, 36.47it/s]
 38%|███▊      | 851/2248 [00:54<00:41, 33.80it/s]
 38%|███▊      | 859/2248 [00:55<00:32, 43.17it/s]
 38%|███▊      | 865/2248 [00:55<00:29, 46.22it/s]
 39%|███▊      | 871/2248 [00:55<01:11, 19.22it/s]
 39%|███▉      | 875/2248 [00:56<01:17, 17.68it/s]
 39%|███▉      | 879/2248 [00:56<01:24, 16.23it/s]
 39%|███▉      | 882/2248 [00:56<01:29, 15.30it/s]
 39%|███▉      | 885/2248 [00:57<01:35, 14.28it/s]
 39%|███▉      | 887/2248 [00:57<01:48, 12.50it/s]
 40%|███▉      | 889/2248 [00:57<02:00, 11.24it/s]
 40%|███▉      | 891/2248 [00:58<02:50,  7.95it/s]
 40%|███▉      | 894/2248 [00:58<02:35,  8.69it/s]
 40%|███▉      | 896/2248 [00:58<03:04,  7.32it/s]
 40%|███▉      | 898/2248 [00:58<02:41,  8.38it/s]
 40%|████      | 900/2248 [00:59<02:49,  7.97it/s]
 40%|████      | 902/2248 [00:59<02:37,  8.56it/s]
 40%|████      | 904/2248 [00:59<02:24,  9.27it/s]
 40%|████      | 906/2248 [00:59<02:44,  8.15it/s]
 40%|████      | 908/2248 [00:59<02:33,  8.75it/s]
 40%|████      | 909/2248 [01:00<02:40,  8.32it/s]
 40%|████      | 910/2248 [01:00<02:51,  7.79it/s]
 41%|████      | 911/2248 [01:00<03:02,  7.31it/s]
 41%|████      | 912/2248 [01:00<03:11,  6.99it/s]
 41%|████      | 913/2248 [01:00<03:33,  6.26it/s]
 41%|████      | 915/2248 [01:00<02:42,  8.22it/s]
 41%|████      | 917/2248 [01:01<02:54,  7.63it/s]
 41%|████      | 919/2248 [01:01<02:33,  8.65it/s]
 41%|████      | 920/2248 [01:01<02:55,  7.58it/s]
 41%|████      | 922/2248 [01:01<02:25,  9.11it/s]
 41%|████      | 924/2248 [01:01<02:00, 11.01it/s]
 41%|████      | 926/2248 [01:02<01:43, 12.80it/s]
 41%|████▏     | 928/2248 [01:02<01:59, 11.09it/s]
 41%|████▏     | 930/2248 [01:02<02:41,  8.18it/s]
 41%|████▏     | 932/2248 [01:02<02:36,  8.42it/s]
 42%|████▏     | 934/2248 [01:03<02:31,  8.69it/s]
 42%|████▏     | 938/2248 [01:03<01:56, 11.25it/s]
 42%|████▏     | 940/2248 [01:03<01:47, 12.22it/s]
 42%|████▏     | 942/2248 [01:03<01:37, 13.37it/s]
 42%|████▏     | 944/2248 [01:03<01:57, 11.08it/s]
 42%|████▏     | 946/2248 [01:04<02:09, 10.02it/s]
 42%|████▏     | 948/2248 [01:04<02:00, 10.75it/s]
 42%|████▏     | 950/2248 [01:04<02:01, 10.65it/s]
 42%|████▏     | 952/2248 [01:04<02:13,  9.72it/s]
 42%|████▏     | 954/2248 [01:04<02:01, 10.67it/s]
 43%|████▎     | 956/2248 [01:05<02:12,  9.74it/s]
 43%|████▎     | 958/2248 [01:05<02:42,  7.93it/s]
 43%|████▎     | 960/2248 [01:05<02:34,  8.34it/s]
 43%|████▎     | 961/2248 [01:05<02:50,  7.53it/s]
 43%|████▎     | 963/2248 [01:05<02:20,  9.13it/s]
 43%|████▎     | 965/2248 [01:06<02:01, 10.60it/s]
 43%|████▎     | 967/2248 [01:06<02:18,  9.22it/s]
 43%|████▎     | 969/2248 [01:06<02:11,  9.71it/s]
 43%|████▎     | 971/2248 [01:06<02:16,  9.36it/s]
 43%|████▎     | 973/2248 [01:06<01:57, 10.82it/s]
 43%|████▎     | 975/2248 [01:07<02:06, 10.03it/s]
 43%|████▎     | 977/2248 [01:07<02:13,  9.49it/s]
 44%|████▎     | 979/2248 [01:07<02:15,  9.34it/s]
 44%|████▎     | 981/2248 [01:07<02:06, 10.02it/s]
 44%|████▎     | 983/2248 [01:07<01:51, 11.39it/s]
 44%|████▍     | 987/2248 [01:07<01:22, 15.38it/s]
 44%|████▍     | 989/2248 [01:08<01:19, 15.84it/s]
 44%|████▍     | 993/2248 [01:08<01:17, 16.22it/s]
 44%|████▍     | 995/2248 [01:08<01:44, 12.03it/s]
 44%|████▍     | 998/2248 [01:08<01:39, 12.56it/s]
 44%|████▍     | 1000/2248 [01:09<01:53, 11.03it/s]
 45%|████▍     | 1002/2248 [01:09<02:03, 10.12it/s]
 45%|████▍     | 1004/2248 [01:09<01:48, 11.47it/s]
 45%|████▍     | 1006/2248 [01:09<01:53, 10.93it/s]
 45%|████▍     | 1008/2248 [01:10<02:32,  8.13it/s]
 45%|████▍     | 1011/2248 [01:10<01:52, 11.01it/s]
 45%|████▌     | 1018/2248 [01:10<01:00, 20.30it/s]
 45%|████▌     | 1022/2248 [01:10<00:53, 22.93it/s]
 46%|████▌     | 1027/2248 [01:10<00:43, 28.14it/s]
 46%|████▌     | 1033/2248 [01:10<00:35, 34.41it/s]
 46%|████▌     | 1039/2248 [01:10<00:30, 39.70it/s]
 47%|████▋     | 1046/2248 [01:10<00:26, 46.09it/s]
 47%|████▋     | 1053/2248 [01:10<00:23, 50.99it/s]
 47%|████▋     | 1059/2248 [01:11<00:37, 31.91it/s]
 47%|████▋     | 1064/2248 [01:11<00:48, 24.23it/s]
 48%|████▊     | 1068/2248 [01:11<00:59, 19.85it/s]
 48%|████▊     | 1073/2248 [01:12<00:51, 22.95it/s]
 48%|████▊     | 1077/2248 [01:12<01:01, 18.99it/s]
 48%|████▊     | 1081/2248 [01:12<00:53, 21.66it/s]
 48%|████▊     | 1084/2248 [01:12<00:52, 22.19it/s]
 48%|████▊     | 1087/2248 [01:12<01:03, 18.28it/s]
 48%|████▊     | 1090/2248 [01:13<01:10, 16.48it/s]
 49%|████▊     | 1092/2248 [01:13<01:15, 15.37it/s]
 49%|████▊     | 1094/2248 [01:13<01:13, 15.68it/s]
 49%|████▉     | 1097/2248 [01:13<01:03, 18.09it/s]
 49%|████▉     | 1103/2248 [01:13<00:44, 25.88it/s]
 49%|████▉     | 1108/2248 [01:13<00:36, 31.29it/s]
 50%|████▉     | 1114/2248 [01:13<00:29, 38.29it/s]
 50%|████▉     | 1121/2248 [01:14<00:25, 44.94it/s]
 50%|█████     | 1127/2248 [01:14<00:23, 47.47it/s]
 50%|█████     | 1132/2248 [01:14<00:29, 38.15it/s]
 51%|█████     | 1139/2248 [01:14<00:24, 45.30it/s]
 51%|█████     | 1145/2248 [01:14<00:43, 25.63it/s]
 51%|█████     | 1149/2248 [01:15<00:58, 18.71it/s]
 51%|█████▏    | 1153/2248 [01:15<01:18, 13.89it/s]
 51%|█████▏    | 1156/2248 [01:16<01:25, 12.77it/s]
 52%|█████▏    | 1158/2248 [01:16<01:40, 10.83it/s]
 52%|█████▏    | 1160/2248 [01:16<01:45, 10.28it/s]
 52%|█████▏    | 1162/2248 [01:16<01:56,  9.34it/s]
 52%|█████▏    | 1164/2248 [01:17<01:59,  9.09it/s]
 52%|█████▏    | 1166/2248 [01:17<01:59,  9.02it/s]
 52%|█████▏    | 1170/2248 [01:17<01:38, 10.95it/s]
 52%|█████▏    | 1172/2248 [01:17<01:48,  9.93it/s]
 52%|█████▏    | 1174/2248 [01:18<01:38, 10.92it/s]
 52%|█████▏    | 1176/2248 [01:18<01:46, 10.03it/s]
 52%|█████▏    | 1178/2248 [01:18<01:55,  9.25it/s]
 52%|█████▏    | 1179/2248 [01:18<01:57,  9.09it/s]
 53%|█████▎    | 1182/2248 [01:18<01:25, 12.48it/s]
 53%|█████▎    | 1184/2248 [01:19<02:02,  8.67it/s]
 53%|█████▎    | 1186/2248 [01:19<01:46,  9.99it/s]
 53%|█████▎    | 1188/2248 [01:19<02:15,  7.81it/s]
 53%|█████▎    | 1190/2248 [01:19<01:53,  9.35it/s]
 53%|█████▎    | 1194/2248 [01:20<01:25, 12.34it/s]
 53%|█████▎    | 1196/2248 [01:20<01:35, 11.06it/s]
 53%|█████▎    | 1200/2248 [01:20<01:08, 15.36it/s]
 53%|█████▎    | 1202/2248 [01:20<01:21, 12.83it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 322.70it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 4], [np.int64(2), False, 3], [np.int64(3), False, 8], [np.int64(5), False, 13], [np.int64(6), False, 0], [np.int64(7), False, 11], [np.int64(8), False, 0], [np.int64(9), False, 0], [np.int64(10), False, 5], [np.int64(12), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.4987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0045, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [14:33<37:13, 45.58s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [14:33<25:34, 31.96s/it]

tensor(12.4981, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1797, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5015, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3314, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [14:34<08:16, 11.04s/it]

tensor(12.5064, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0277, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3977, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4168, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [14:34<03:55,  5.47s/it]

tensor(12.5111, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3903, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5057, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3807, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [14:34<01:52,  2.74s/it]

tensor(12.4988, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0322, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4086, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0316, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4307, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 260/300 [14:34<01:18,  1.96s/it]

tensor(12.4919, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0315, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4472, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4930, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4510, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 263/300 [14:34<00:27,  1.33it/s]

tensor(12.4963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0317, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4568, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4998, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4494, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 265/300 [14:35<00:14,  2.35it/s]

tensor(12.5017, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0296, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4495, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5000, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0280, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4461, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 267/300 [14:35<00:08,  3.71it/s]

tensor(12.4947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0269, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4427, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4872, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4403, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▉ | 268/300 [14:35<00:07,  4.44it/s]

tensor(12.4798, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0262, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4394, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4743, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4433, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 271/300 [14:35<00:04,  6.36it/s]

tensor(12.4716, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0265, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4475, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0261, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4545, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 273/300 [14:36<00:03,  7.20it/s]

tensor(12.4724, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4594, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4640, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [14:36<00:03,  7.72it/s]

tensor(12.4727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4699, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4709, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4684, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 277/300 [14:36<00:02,  7.95it/s]

tensor(12.4678, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4677, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4641, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4672, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [14:36<00:02,  7.95it/s]

tensor(12.4608, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4688, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4582, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4691, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▎| 281/300 [14:37<00:02,  8.10it/s]

tensor(12.4567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4681, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4557, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4669, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 283/300 [14:37<00:02,  8.22it/s]

tensor(12.4551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4637, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4544, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4657, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 285/300 [14:37<00:01,  8.31it/s]

tensor(12.4534, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4671, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4519, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4664, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 287/300 [14:37<00:01,  8.30it/s]

tensor(12.4501, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4687, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4484, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4685, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▋| 289/300 [14:38<00:01,  8.41it/s]

tensor(12.4467, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4677, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4452, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4696, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 291/300 [14:38<00:01,  8.32it/s]

tensor(12.4439, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4697, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4429, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4707, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 293/300 [14:38<00:00,  8.34it/s]

tensor(12.4418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4711, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4408, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4713, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 295/300 [14:38<00:00,  8.26it/s]

tensor(12.4398, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4708, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4388, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4672, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 297/300 [14:39<00:00,  8.27it/s]

tensor(12.4377, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0210, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4653, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4366, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4658, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [14:39<00:00,  8.23it/s]

tensor(12.4355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4658, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4346, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0208, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4641, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [14:39<00:00,  2.93s/it]

tensor(12.4334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4639, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.0021779537200927734
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 8
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.411450380957
NMI         : 0.463248632606
Runtime     : 899.49 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed8

==============================================================================================================
PRAGA RUN | S2-E18 | seed=9
==============================================================================================================

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/usr/lib/python3.12/functools.py:912: UserWarning: zero-centering a sparse array/matrix densifies it.
  return dispatch(args[0].__class__)(*args, **kw)

S2-E18: ATAC 94941 -> 94941 peaks (removed 0 zero-total peaks)
S2-E18: scaled LSI shape = (2248, 50)
S2-E18: max |column mean| = 9.408e-17
S2-E18: sample std range = [1.000000, 1.000000]
S2-E18: RNA feat = (2248, 50)
S2-E18: ATAC feat = (2248, 50)
S2-E18: KNN_k=20, weights=[1, 10], init_k=14

  0%|          | 0/300 [00:00<?, ?it/s]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
  1%|          | 2/300 [00:00<00:31,  9.35it/s]

tensor(15.9612, device='cuda:0', grad_fn=<AddBackward0>) tensor(23.1175, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9752, device='cuda:0', grad_fn=<AddBackward0>) tensor(20.8017, device='cuda:0', grad_fn=<DivBackward0>) 0

  1%|          | 3/300 [00:00<00:30,  9.61it/s]

tensor(15.9574, device='cuda:0', grad_fn=<AddBackward0>) tensor(18.7143, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9347, device='cuda:0', grad_fn=<AddBackward0>) tensor(16.8325, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.9053, device='cuda:0', grad_fn=<AddBackward0>) tensor(15.1359, device='cuda:0', grad_fn=<DivBackward0>) 0

  2%|▏         | 7/300 [00:00<00:28, 10.15it/s]

tensor(15.8743, device='cuda:0', grad_fn=<AddBackward0>) tensor(13.6060, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8418, device='cuda:0', grad_fn=<AddBackward0>) tensor(12.2273, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.8093, device='cuda:0', grad_fn=<AddBackward0>) tensor(10.9848, device='cuda:0', grad_fn=<DivBackward0>) 0

  3%|▎         | 9/300 [00:00<00:28, 10.22it/s]

tensor(15.7775, device='cuda:0', grad_fn=<AddBackward0>) tensor(9.8648, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7470, device='cuda:0', grad_fn=<AddBackward0>) tensor(8.8551, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.7174, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.9451, device='cuda:0', grad_fn=<DivBackward0>) 0

  4%|▍         | 13/300 [00:01<00:27, 10.31it/s]

tensor(15.6897, device='cuda:0', grad_fn=<AddBackward0>) tensor(7.1250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6627, device='cuda:0', grad_fn=<AddBackward0>) tensor(6.3857, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.6369, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.7199, device='cuda:0', grad_fn=<DivBackward0>) 0

  5%|▌         | 15/300 [00:01<00:27, 10.37it/s]

tensor(15.6114, device='cuda:0', grad_fn=<AddBackward0>) tensor(5.1201, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5861, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.5798, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5610, device='cuda:0', grad_fn=<AddBackward0>) tensor(4.0927, device='cuda:0', grad_fn=<DivBackward0>) 0

  6%|▋         | 19/300 [00:01<00:27, 10.40it/s]

tensor(15.5354, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.6541, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.5094, device='cuda:0', grad_fn=<AddBackward0>) tensor(3.2592, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4823, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.9040, device='cuda:0', grad_fn=<DivBackward0>) 0

  7%|▋         | 21/300 [00:02<00:26, 10.42it/s]

tensor(15.4546, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.5840, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.4259, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.2958, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3955, device='cuda:0', grad_fn=<AddBackward0>) tensor(2.0365, device='cuda:0', grad_fn=<DivBackward0>) 0

  8%|▊         | 25/300 [00:02<00:26, 10.48it/s]

tensor(15.3645, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.8037, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.3324, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.5940, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2992, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.4058, device='cuda:0', grad_fn=<DivBackward0>) 0

  9%|▉         | 27/300 [00:02<00:26, 10.40it/s]

tensor(15.2648, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.2366, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.2301, device='cuda:0', grad_fn=<AddBackward0>) tensor(1.0852, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1947, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.9485, device='cuda:0', grad_fn=<DivBackward0>) 0

 10%|█         | 31/300 [00:03<00:25, 10.37it/s]

tensor(15.1586, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.8265, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.1219, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.7171, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.6194, device='cuda:0', grad_fn=<DivBackward0>) 0

 11%|█         | 33/300 [00:03<00:25, 10.37it/s]

tensor(15.0486, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.5320, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(15.0115, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.4540, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3840, device='cuda:0', grad_fn=<DivBackward0>) 0

 12%|█▏        | 37/300 [00:03<00:25, 10.37it/s]

tensor(14.9378, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.3227, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.9006, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2683, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.8636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.2202, device='cuda:0', grad_fn=<DivBackward0>) 0

 13%|█▎        | 39/300 [00:03<00:25, 10.33it/s]

tensor(14.8264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1784, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7893, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1423, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.7522, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.1120, device='cuda:0', grad_fn=<DivBackward0>) 0

 14%|█▍        | 43/300 [00:04<00:24, 10.33it/s]

tensor(14.7149, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0867, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6780, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0671, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.6410, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0523, device='cuda:0', grad_fn=<DivBackward0>) 0

 15%|█▌        | 45/300 [00:04<00:24, 10.36it/s]

tensor(14.6039, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0423, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5671, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0356, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.5302, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0326, device='cuda:0', grad_fn=<DivBackward0>) 0

 16%|█▋        | 49/300 [00:04<00:24, 10.35it/s]

tensor(14.4935, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0314, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4569, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0307, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.4206, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0302, device='cuda:0', grad_fn=<DivBackward0>) 0

 17%|█▋        | 51/300 [00:04<00:24, 10.31it/s]

tensor(14.3842, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0313, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3480, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0324, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.3117, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0337, device='cuda:0', grad_fn=<DivBackward0>) 0

 18%|█▊        | 55/300 [00:05<00:23, 10.33it/s]

tensor(14.2758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0336, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2402, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0328, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.2043, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0310, device='cuda:0', grad_fn=<DivBackward0>) 0

 19%|█▉        | 57/300 [00:05<00:23, 10.36it/s]

tensor(14.1688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0292, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.1334, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0270, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0982, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) 0

 20%|██        | 61/300 [00:05<00:23, 10.35it/s]

tensor(14.0634, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(14.0291, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9945, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) 0

 21%|██        | 63/300 [00:06<00:22, 10.35it/s]

tensor(13.9605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.9264, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8929, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) 0

 22%|██▏       | 67/300 [00:06<00:22, 10.33it/s]

tensor(13.8591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.8259, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0

 23%|██▎       | 69/300 [00:06<00:22, 10.32it/s]

tensor(13.7595, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.7267, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6932, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) 0

 24%|██▍       | 73/300 [00:07<00:22, 10.25it/s]

tensor(13.6605, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.6273, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0259, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) 0

 25%|██▌       | 75/300 [00:07<00:21, 10.32it/s]

tensor(13.5613, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.5282, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4948, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0

 26%|██▋       | 79/300 [00:07<00:21, 10.33it/s]

tensor(13.4615, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.4284, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3949, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 27%|██▋       | 81/300 [00:07<00:21, 10.31it/s]

tensor(13.3618, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.3290, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) 0

 28%|██▊       | 85/300 [00:08<00:20, 10.30it/s]

tensor(13.2650, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.2042, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) 0

 29%|██▉       | 87/300 [00:08<00:20, 10.35it/s]

tensor(13.1754, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.1218, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0

 30%|███       | 91/300 [00:08<00:20, 10.27it/s]

tensor(13.0971, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0736, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0513, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0

 31%|███       | 93/300 [00:09<00:20, 10.30it/s]

tensor(13.0300, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(13.0092, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9886, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) 0

 32%|███▏      | 97/300 [00:09<00:19, 10.32it/s]

tensor(12.9684, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0239, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9486, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.9292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) 0

 33%|███▎      | 99/300 [00:09<00:19, 10.26it/s]

tensor(12.9097, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) 0
tensor(12.8907, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) 0
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 89, 531, 107,  63,  98, 209,  89,  93, 349,  89,  56,  59,  36, 380])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 1/2248 [00:00<06:01,  6.21it/s]
  0%|          | 2/2248 [00:00<09:02,  4.14it/s]
  0%|          | 4/2248 [00:00<04:47,  7.80it/s]
  0%|          | 7/2248 [00:00<02:53, 12.93it/s]
  0%|          | 9/2248 [00:01<04:39,  8.02it/s]
  0%|          | 11/2248 [00:01<03:45,  9.93it/s]
  1%|          | 13/2248 [00:01<05:41,  6.55it/s]
  1%|          | 16/2248 [00:01<03:54,  9.50it/s]
  1%|          | 23/2248 [00:02<03:19, 11.17it/s]
  1%|          | 26/2248 [00:02<02:50, 13.00it/s]
  1%|▏         | 33/2248 [00:02<01:46, 20.84it/s]
  2%|▏         | 37/2248 [00:03<02:51, 12.87it/s]
  2%|▏         | 40/2248 [00:03<03:30, 10.48it/s]
  2%|▏         | 43/2248 [00:04<03:42,  9.92it/s]
  2%|▏         | 45/2248 [00:04<04:10,  8.81it/s]
  2%|▏         | 47/2248 [00:04<04:14,  8.65it/s]
  2%|▏         | 49/2248 [00:04<03:44,  9.78it/s]
  2%|▏         | 52/2248 [00:05<03:45,  9.72it/s]
  2%|▏         | 54/2248 [00:05<04:52,  7.50it/s]
  2%|▏         | 55/2248 [00:05<05:35,  6.55it/s]
  3%|▎         | 57/2248 [00:05<04:31,  8.06it/s]
  3%|▎         | 60/2248 [00:06<03:22, 10.82it/s]
  3%|▎         | 62/2248 [00:06<04:16,  8.53it/s]
  3%|▎         | 64/2248 [00:06<03:40,  9.92it/s]
  3%|▎         | 66/2248 [00:07<06:12,  5.86it/s]
  3%|▎         | 68/2248 [00:07<04:59,  7.27it/s]
  3%|▎         | 71/2248 [00:07<05:12,  6.97it/s]
  3%|▎         | 73/2248 [00:07<04:19,  8.39it/s]
  3%|▎         | 75/2248 [00:08<05:49,  6.22it/s]
  3%|▎         | 77/2248 [00:09<08:40,  4.17it/s]
  4%|▎         | 79/2248 [00:09<08:47,  4.11it/s]
 33%|███▎      | 99/300 [00:25<00:19, 10.26it/s]]
  4%|▎         | 81/2248 [00:10<11:37,  3.11it/s]
  4%|▎         | 82/2248 [00:11<12:50,  2.81it/s]
  4%|▎         | 83/2248 [00:11<13:50,  2.61it/s]
  4%|▎         | 84/2248 [00:12<14:22,  2.51it/s]
  4%|▍         | 86/2248 [00:12<12:29,  2.89it/s]
  4%|▍         | 87/2248 [00:13<13:29,  2.67it/s]
  4%|▍         | 88/2248 [00:13<14:23,  2.50it/s]
  4%|▍         | 89/2248 [00:14<14:46,  2.43it/s]
  4%|▍         | 91/2248 [00:14<09:16,  3.87it/s]
  4%|▍         | 93/2248 [00:14<09:08,  3.93it/s]
  4%|▍         | 94/2248 [00:15<11:16,  3.18it/s]
  4%|▍         | 96/2248 [00:15<10:28,  3.43it/s]
  4%|▍         | 97/2248 [00:16<10:42,  3.35it/s]
  4%|▍         | 98/2248 [00:16<11:44,  3.05it/s]
  4%|▍         | 99/2248 [00:16<12:20,  2.90it/s]
  4%|▍         | 100/2248 [00:17<11:21,  3.15it/s]
  4%|▍         | 101/2248 [00:17<11:21,  3.15it/s]
  5%|▍         | 102/2248 [00:17<12:17,  2.91it/s]
  5%|▍         | 104/2248 [00:18<10:06,  3.54it/s]
  5%|▍         | 105/2248 [00:18<10:12,  3.50it/s]
  5%|▍         | 107/2248 [00:19<09:52,  3.61it/s]
  5%|▍         | 109/2248 [00:19<09:44,  3.66it/s]
  5%|▍         | 110/2248 [00:20<11:21,  3.14it/s]
  5%|▍         | 112/2248 [00:20<10:43,  3.32it/s]
  5%|▌         | 113/2248 [00:21<12:08,  2.93it/s]
  5%|▌         | 114/2248 [00:21<13:24,  2.65it/s]
  5%|▌         | 115/2248 [00:22<14:21,  2.48it/s]
  5%|▌         | 117/2248 [00:22<12:32,  2.83it/s]
  5%|▌         | 119/2248 [00:23<11:21,  3.13it/s]
  5%|▌         | 120/2248 [00:24<16:05,  2.20it/s]
  5%|▌         | 121/2248 [00:24<16:18,  2.17it/s]
  5%|▌         | 122/2248 [00:25<22:50,  1.55it/s]
  5%|▌         | 123/2248 [00:26<21:16,  1.66it/s]
  6%|▌         | 125/2248 [00:26<13:14,  2.67it/s]
  6%|▌         | 126/2248 [00:27<16:43,  2.12it/s]
  6%|▌         | 127/2248 [00:27<16:14,  2.18it/s]
  6%|▌         | 128/2248 [00:28<19:57,  1.77it/s]
  6%|▌         | 129/2248 [00:29<18:29,  1.91it/s]
  6%|▌         | 130/2248 [00:29<17:15,  2.05it/s]
  6%|▌         | 132/2248 [00:29<13:47,  2.56it/s]
  6%|▌         | 133/2248 [00:31<20:39,  1.71it/s]
  6%|▌         | 135/2248 [00:32<21:15,  1.66it/s]
  6%|▌         | 137/2248 [00:32<16:55,  2.08it/s]
  6%|▌         | 138/2248 [00:33<21:02,  1.67it/s]
  6%|▌         | 139/2248 [00:34<18:47,  1.87it/s]
  6%|▋         | 141/2248 [00:34<12:08,  2.89it/s]
  6%|▋         | 142/2248 [00:34<11:07,  3.15it/s]
  6%|▋         | 144/2248 [00:34<07:43,  4.54it/s]
  6%|▋         | 145/2248 [00:35<10:31,  3.33it/s]
  6%|▋         | 146/2248 [00:35<10:22,  3.37it/s]
  7%|▋         | 148/2248 [00:35<06:56,  5.04it/s]
  7%|▋         | 149/2248 [00:35<07:21,  4.75it/s]
  7%|▋         | 151/2248 [00:36<08:18,  4.21it/s]
  7%|▋         | 153/2248 [00:36<07:22,  4.73it/s]
  7%|▋         | 155/2248 [00:36<05:29,  6.36it/s]
  7%|▋         | 157/2248 [00:37<08:31,  4.08it/s]
  7%|▋         | 158/2248 [00:38<13:20,  2.61it/s]
  7%|▋         | 159/2248 [00:39<15:36,  2.23it/s]
  7%|▋         | 160/2248 [00:40<18:23,  1.89it/s]
  7%|▋         | 162/2248 [00:40<15:18,  2.27it/s]
  7%|▋         | 164/2248 [00:41<10:22,  3.35it/s]
  7%|▋         | 165/2248 [00:41<12:59,  2.67it/s]
  7%|▋         | 167/2248 [00:41<08:59,  3.86it/s]
  8%|▊         | 169/2248 [00:42<09:41,  3.57it/s]
  8%|▊         | 170/2248 [00:42<10:34,  3.28it/s]
  8%|▊         | 171/2248 [00:43<11:35,  2.98it/s]
  8%|▊         | 172/2248 [00:43<12:26,  2.78it/s]
  8%|▊         | 173/2248 [00:44<19:02,  1.82it/s]
  8%|▊         | 174/2248 [00:45<17:41,  1.95it/s]
  8%|▊         | 176/2248 [00:46<19:04,  1.81it/s]
  8%|▊         | 177/2248 [00:46<18:39,  1.85it/s]
  8%|▊         | 178/2248 [00:48<24:02,  1.44it/s]
  8%|▊         | 179/2248 [00:48<21:17,  1.62it/s]
  8%|▊         | 182/2248 [00:48<10:41,  3.22it/s]
  8%|▊         | 183/2248 [00:49<11:43,  2.93it/s]
  8%|▊         | 184/2248 [00:49<11:14,  3.06it/s]
  8%|▊         | 186/2248 [00:49<08:41,  3.95it/s]
  8%|▊         | 187/2248 [00:50<11:58,  2.87it/s]
  8%|▊         | 188/2248 [00:50<12:24,  2.77it/s]
  8%|▊         | 189/2248 [00:51<18:28,  1.86it/s]
  8%|▊         | 190/2248 [00:52<15:44,  2.18it/s]
  8%|▊         | 191/2248 [00:52<14:27,  2.37it/s]
  9%|▊         | 192/2248 [00:52<12:16,  2.79it/s]
  9%|▊         | 194/2248 [00:52<08:30,  4.03it/s]
  9%|▊         | 195/2248 [00:53<09:31,  3.60it/s]
  9%|▉         | 197/2248 [00:53<08:44,  3.91it/s]
  9%|▉         | 198/2248 [00:54<10:33,  3.23it/s]
  9%|▉         | 199/2248 [00:54<10:05,  3.39it/s]
  9%|▉         | 200/2248 [00:54<10:30,  3.25it/s]
  9%|▉         | 202/2248 [00:55<11:18,  3.02it/s]
  9%|▉         | 203/2248 [00:55<11:48,  2.88it/s]
  9%|▉         | 204/2248 [00:56<12:20,  2.76it/s]
  9%|▉         | 205/2248 [00:56<14:19,  2.38it/s]
  9%|▉         | 207/2248 [00:57<10:48,  3.15it/s]
  9%|▉         | 209/2248 [00:57<09:27,  3.60it/s]
  9%|▉         | 210/2248 [00:58<11:30,  2.95it/s]
  9%|▉         | 211/2248 [00:59<17:30,  1.94it/s]
  9%|▉         | 212/2248 [01:00<20:32,  1.65it/s]
  9%|▉         | 213/2248 [01:00<18:26,  1.84it/s]
 10%|▉         | 214/2248 [01:00<17:38,  1.92it/s]
 10%|▉         | 216/2248 [01:01<12:34,  2.69it/s]
 10%|▉         | 218/2248 [01:01<08:37,  3.92it/s]
 10%|▉         | 220/2248 [01:01<08:45,  3.86it/s]
 10%|▉         | 223/2248 [01:02<05:34,  6.05it/s]
 10%|█         | 226/2248 [01:02<05:39,  5.95it/s]
 10%|█         | 227/2248 [01:02<06:22,  5.29it/s]
 10%|█         | 228/2248 [01:03<06:47,  4.95it/s]
 10%|█         | 230/2248 [01:03<06:50,  4.91it/s]
 10%|█         | 233/2248 [01:03<04:41,  7.16it/s]
 10%|█         | 236/2248 [01:04<04:51,  6.89it/s]
 11%|█         | 238/2248 [01:04<04:10,  8.02it/s]
 11%|█         | 241/2248 [01:04<03:06, 10.74it/s]
 11%|█         | 248/2248 [01:04<01:42, 19.44it/s]
 11%|█▏        | 255/2248 [01:04<01:14, 26.81it/s]
 12%|█▏        | 260/2248 [01:04<01:06, 29.86it/s]
 12%|█▏        | 264/2248 [01:06<04:24,  7.51it/s]
 12%|█▏        | 267/2248 [01:08<08:20,  3.96it/s]
 12%|█▏        | 269/2248 [01:09<08:36,  3.83it/s]
 12%|█▏        | 271/2248 [01:09<08:59,  3.67it/s]
 12%|█▏        | 273/2248 [01:10<08:15,  3.99it/s]
 12%|█▏        | 274/2248 [01:10<08:01,  4.10it/s]
 12%|█▏        | 275/2248 [01:10<08:57,  3.67it/s]
 12%|█▏        | 277/2248 [01:11<08:05,  4.06it/s]
 12%|█▏        | 279/2248 [01:11<06:08,  5.35it/s]
 12%|█▏        | 280/2248 [01:11<07:30,  4.37it/s]
 12%|█▎        | 281/2248 [01:11<08:02,  4.08it/s]
 13%|█▎        | 282/2248 [01:12<12:02,  2.72it/s]
 13%|█▎        | 283/2248 [01:13<11:48,  2.77it/s]
 13%|█▎        | 284/2248 [01:13<11:36,  2.82it/s]
 13%|█▎        | 286/2248 [01:13<09:52,  3.31it/s]
 13%|█▎        | 287/2248 [01:14<11:11,  2.92it/s]
 13%|█▎        | 288/2248 [01:14<10:10,  3.21it/s]
 13%|█▎        | 289/2248 [01:15<11:08,  2.93it/s]
 13%|█▎        | 290/2248 [01:15<12:26,  2.62it/s]
 13%|█▎        | 291/2248 [01:15<11:23,  2.86it/s]
 13%|█▎        | 292/2248 [01:16<11:27,  2.84it/s]
 13%|█▎        | 294/2248 [01:16<07:59,  4.08it/s]
 13%|█▎        | 295/2248 [01:17<11:00,  2.96it/s]
 13%|█▎        | 296/2248 [01:17<11:27,  2.84it/s]
 13%|█▎        | 298/2248 [01:17<09:21,  3.47it/s]
 13%|█▎        | 299/2248 [01:18<10:33,  3.08it/s]
 13%|█▎        | 300/2248 [01:18<11:06,  2.92it/s]
 13%|█▎        | 301/2248 [01:19<11:51,  2.74it/s]
 13%|█▎        | 302/2248 [01:19<12:33,  2.58it/s]
 13%|█▎        | 303/2248 [01:19<12:32,  2.59it/s]
 14%|█▎        | 304/2248 [01:20<12:01,  2.70it/s]
 14%|█▎        | 305/2248 [01:20<11:18,  2.87it/s]
 14%|█▎        | 306/2248 [01:20<10:20,  3.13it/s]
 14%|█▎        | 307/2248 [01:21<12:27,  2.60it/s]
 14%|█▎        | 308/2248 [01:21<11:53,  2.72it/s]
 14%|█▎        | 309/2248 [01:22<13:59,  2.31it/s]
 14%|█▍        | 310/2248 [01:22<11:43,  2.75it/s]
 14%|█▍        | 312/2248 [01:23<10:55,  2.95it/s]
 14%|█▍        | 313/2248 [01:23<11:02,  2.92it/s]
 14%|█▍        | 314/2248 [01:23<11:29,  2.81it/s]
 14%|█▍        | 315/2248 [01:24<11:48,  2.73it/s]
 14%|█▍        | 316/2248 [01:24<11:26,  2.81it/s]
 14%|█▍        | 318/2248 [01:24<08:55,  3.60it/s]
 14%|█▍        | 320/2248 [01:25<10:59,  2.92it/s]
 14%|█▍        | 321/2248 [01:25<10:11,  3.15it/s]
 14%|█▍        | 322/2248 [01:26<11:27,  2.80it/s]
 14%|█▍        | 323/2248 [01:27<13:34,  2.36it/s]
 14%|█▍        | 325/2248 [01:27<12:44,  2.52it/s]
 15%|█▍        | 327/2248 [01:28<12:12,  2.62it/s]
 15%|█▍        | 328/2248 [01:29<17:39,  1.81it/s]
 15%|█▍        | 329/2248 [01:30<17:11,  1.86it/s]
 15%|█▍        | 331/2248 [01:30<11:10,  2.86it/s]
 15%|█▍        | 332/2248 [01:31<16:32,  1.93it/s]
 15%|█▍        | 333/2248 [01:31<16:04,  1.99it/s]
 15%|█▍        | 335/2248 [01:32<13:04,  2.44it/s]
 15%|█▍        | 337/2248 [01:32<08:57,  3.56it/s]
 15%|█▌        | 339/2248 [01:33<09:33,  3.33it/s]
 15%|█▌        | 340/2248 [01:33<09:17,  3.42it/s]
 15%|█▌        | 341/2248 [01:33<09:25,  3.37it/s]
 15%|█▌        | 343/2248 [01:34<09:34,  3.32it/s]
 15%|█▌        | 344/2248 [01:34<11:21,  2.79it/s]
 15%|█▌        | 345/2248 [01:36<17:06,  1.85it/s]
 15%|█▌        | 346/2248 [01:37<21:00,  1.51it/s]
 15%|█▌        | 347/2248 [01:38<23:13,  1.36it/s]
 15%|█▌        | 348/2248 [01:38<23:14,  1.36it/s]
 16%|█▌        | 349/2248 [01:39<21:26,  1.48it/s]
 16%|█▌        | 350/2248 [01:40<21:10,  1.49it/s]
 16%|█▌        | 353/2248 [01:40<13:56,  2.26it/s]
 16%|█▌        | 354/2248 [01:41<15:20,  2.06it/s]
 16%|█▌        | 355/2248 [01:41<15:01,  2.10it/s]
 16%|█▌        | 356/2248 [01:42<16:02,  1.97it/s]
 16%|█▌        | 357/2248 [01:43<16:09,  1.95it/s]
 16%|█▌        | 359/2248 [01:43<09:57,  3.16it/s]
 16%|█▌        | 360/2248 [01:43<11:11,  2.81it/s]
 16%|█▌        | 362/2248 [01:44<14:30,  2.17it/s]
 16%|█▌        | 364/2248 [01:45<12:27,  2.52it/s]
 16%|█▋        | 366/2248 [01:46<11:38,  2.70it/s]
 16%|█▋        | 367/2248 [01:46<14:02,  2.23it/s]
 16%|█▋        | 368/2248 [01:47<12:28,  2.51it/s]
 16%|█▋        | 369/2248 [01:47<10:54,  2.87it/s]
 17%|█▋        | 371/2248 [01:48<11:26,  2.73it/s]
 17%|█▋        | 373/2248 [01:49<14:18,  2.18it/s]
 17%|█▋        | 374/2248 [01:49<14:33,  2.15it/s]
 17%|█▋        | 377/2248 [01:50<13:51,  2.25it/s]
 17%|█▋        | 378/2248 [01:51<14:09,  2.20it/s]
 17%|█▋        | 380/2248 [01:51<09:55,  3.14it/s]
 17%|█▋        | 383/2248 [01:51<06:12,  5.01it/s]
 17%|█▋        | 385/2248 [01:52<09:52,  3.14it/s]
 17%|█▋        | 386/2248 [01:53<09:54,  3.13it/s]
 17%|█▋        | 388/2248 [01:53<09:33,  3.25it/s]
 17%|█▋        | 389/2248 [01:54<11:20,  2.73it/s]
 17%|█▋        | 390/2248 [01:54<12:26,  2.49it/s]
 17%|█▋        | 391/2248 [01:55<11:26,  2.71it/s]
 17%|█▋        | 392/2248 [01:55<12:55,  2.39it/s]
 17%|█▋        | 393/2248 [01:56<14:00,  2.21it/s]
 18%|█▊        | 394/2248 [01:56<15:10,  2.04it/s]
 18%|█▊        | 395/2248 [01:57<16:19,  1.89it/s]
 18%|█▊        | 397/2248 [01:57<10:03,  3.07it/s]
 18%|█▊        | 398/2248 [01:58<11:17,  2.73it/s]
 18%|█▊        | 400/2248 [01:58<10:01,  3.07it/s]
 18%|█▊        | 402/2248 [01:59<09:00,  3.42it/s]
 18%|█▊        | 405/2248 [01:59<07:12,  4.26it/s]
 18%|█▊        | 407/2248 [02:00<06:26,  4.76it/s]
 18%|█▊        | 409/2248 [02:00<05:04,  6.04it/s]
 18%|█▊        | 410/2248 [02:00<05:39,  5.42it/s]
 18%|█▊        | 412/2248 [02:00<04:23,  6.96it/s]
 19%|█▊        | 417/2248 [02:01<03:40,  8.31it/s]
 19%|█▊        | 420/2248 [02:01<04:17,  7.11it/s]
 19%|█▉        | 422/2248 [02:01<03:48,  7.99it/s]
 19%|█▉        | 428/2248 [02:01<02:15, 13.47it/s]
 19%|█▉        | 431/2248 [02:02<03:12,  9.43it/s]
 19%|█▉        | 433/2248 [02:02<04:06,  7.36it/s]
 19%|█▉        | 435/2248 [02:03<03:34,  8.45it/s]
 19%|█▉        | 437/2248 [02:05<11:01,  2.74it/s]
 20%|█▉        | 439/2248 [02:06<12:53,  2.34it/s]
 20%|█▉        | 440/2248 [02:07<16:04,  1.88it/s]
 20%|█▉        | 441/2248 [02:08<15:22,  1.96it/s]
 20%|█▉        | 443/2248 [02:08<12:04,  2.49it/s]
 20%|█▉        | 444/2248 [02:09<14:45,  2.04it/s]
 20%|█▉        | 445/2248 [02:09<13:10,  2.28it/s]
 20%|█▉        | 446/2248 [02:10<15:16,  1.97it/s]
 20%|█▉        | 448/2248 [02:10<11:11,  2.68it/s]
 20%|██        | 450/2248 [02:11<10:42,  2.80it/s]
 20%|██        | 452/2248 [02:11<07:50,  3.82it/s]
 20%|██        | 453/2248 [02:12<13:03,  2.29it/s]
 20%|██        | 454/2248 [02:13<12:47,  2.34it/s]
 20%|██        | 455/2248 [02:13<14:15,  2.10it/s]
 20%|██        | 456/2248 [02:14<13:10,  2.27it/s]
 20%|██        | 457/2248 [02:14<14:23,  2.07it/s]
 20%|██        | 459/2248 [02:15<11:16,  2.64it/s]
 20%|██        | 460/2248 [02:15<13:37,  2.19it/s]
 21%|██        | 461/2248 [02:16<12:05,  2.46it/s]
 21%|██        | 462/2248 [02:16<12:08,  2.45it/s]
 21%|██        | 463/2248 [02:16<13:06,  2.27it/s]
 21%|██        | 464/2248 [02:17<10:59,  2.70it/s]
 21%|██        | 466/2248 [02:17<09:21,  3.17it/s]
 21%|██        | 467/2248 [02:17<09:11,  3.23it/s]
 21%|██        | 469/2248 [02:18<07:51,  3.77it/s]
 21%|██        | 471/2248 [02:19<08:30,  3.48it/s]
 21%|██        | 472/2248 [02:19<12:17,  2.41it/s]
 21%|██        | 473/2248 [02:20<12:49,  2.31it/s]
 21%|██        | 474/2248 [02:20<13:03,  2.27it/s]
 21%|██        | 475/2248 [02:21<12:39,  2.33it/s]
 21%|██        | 476/2248 [02:22<18:48,  1.57it/s]
 21%|██        | 477/2248 [02:23<19:38,  1.50it/s]
 21%|██▏       | 478/2248 [02:24<22:38,  1.30it/s]
 21%|██▏       | 479/2248 [02:25<24:54,  1.18it/s]
 21%|██▏       | 480/2248 [02:26<26:52,  1.10it/s]
 21%|██▏       | 481/2248 [02:27<28:20,  1.04it/s]
 21%|██▏       | 482/2248 [02:28<29:05,  1.01it/s]
 21%|██▏       | 483/2248 [02:28<24:51,  1.18it/s]
 22%|██▏       | 485/2248 [02:29<16:41,  1.76it/s]
 22%|██▏       | 486/2248 [02:30<20:01,  1.47it/s]
 22%|██▏       | 487/2248 [02:31<22:37,  1.30it/s]
 22%|██▏       | 488/2248 [02:32<25:00,  1.17it/s]
 22%|██▏       | 490/2248 [02:32<16:08,  1.82it/s]
 22%|██▏       | 493/2248 [02:33<09:00,  3.25it/s]
 22%|██▏       | 494/2248 [02:33<08:47,  3.32it/s]
 22%|██▏       | 495/2248 [02:33<08:37,  3.39it/s]
 22%|██▏       | 498/2248 [02:33<06:13,  4.69it/s]
 22%|██▏       | 499/2248 [02:34<06:34,  4.43it/s]
 22%|██▏       | 500/2248 [02:34<08:32,  3.41it/s]
 22%|██▏       | 502/2248 [02:35<07:32,  3.86it/s]
 22%|██▏       | 503/2248 [02:35<08:40,  3.36it/s]
 22%|██▏       | 505/2248 [02:35<06:09,  4.72it/s]
 23%|██▎       | 506/2248 [02:36<08:08,  3.56it/s]
 23%|██▎       | 508/2248 [02:36<08:01,  3.62it/s]
 23%|██▎       | 509/2248 [02:38<13:26,  2.16it/s]
 23%|██▎       | 510/2248 [02:38<13:01,  2.22it/s]
 23%|██▎       | 512/2248 [02:38<10:46,  2.69it/s]
 23%|██▎       | 513/2248 [02:40<15:32,  1.86it/s]
 23%|██▎       | 514/2248 [02:41<19:12,  1.51it/s]
 23%|██▎       | 515/2248 [02:42<22:24,  1.29it/s]
 23%|██▎       | 516/2248 [02:43<24:39,  1.17it/s]
 23%|██▎       | 517/2248 [02:44<26:37,  1.08it/s]
 23%|██▎       | 518/2248 [02:45<26:26,  1.09it/s]
 23%|██▎       | 519/2248 [02:45<23:10,  1.24it/s]
 23%|██▎       | 521/2248 [02:45<13:27,  2.14it/s]
 23%|██▎       | 523/2248 [02:46<10:22,  2.77it/s]
 23%|██▎       | 524/2248 [02:46<09:43,  2.95it/s]
 23%|██▎       | 527/2248 [02:46<06:14,  4.59it/s]
 24%|██▎       | 529/2248 [02:47<06:22,  4.49it/s]
 24%|██▎       | 531/2248 [02:47<05:07,  5.58it/s]
 24%|██▎       | 533/2248 [02:47<05:09,  5.54it/s]
 24%|██▍       | 535/2248 [02:48<05:36,  5.09it/s]
 24%|██▍       | 537/2248 [02:48<04:21,  6.53it/s]
 24%|██▍       | 541/2248 [02:48<03:30,  8.09it/s]
 24%|██▍       | 544/2248 [02:49<03:17,  8.61it/s]
 24%|██▍       | 547/2248 [02:49<02:33, 11.08it/s]
 25%|██▍       | 554/2248 [02:49<02:05, 13.45it/s]
 25%|██▍       | 556/2248 [02:49<02:00, 14.06it/s]
 25%|██▍       | 558/2248 [02:50<03:42,  7.61it/s]
 25%|██▍       | 560/2248 [02:50<03:15,  8.63it/s]
 25%|██▌       | 562/2248 [02:50<03:04,  9.14it/s]
 25%|██▌       | 564/2248 [02:51<03:24,  8.23it/s]
 25%|██▌       | 566/2248 [02:51<02:55,  9.57it/s]
 25%|██▌       | 569/2248 [02:51<02:11, 12.73it/s]
 25%|██▌       | 571/2248 [02:51<03:24,  8.20it/s]
 25%|██▌       | 573/2248 [02:53<08:17,  3.36it/s]
 26%|██▌       | 575/2248 [02:54<11:30,  2.42it/s]
 26%|██▌       | 577/2248 [02:55<10:32,  2.64it/s]
 26%|██▌       | 579/2248 [02:56<10:16,  2.71it/s]
 26%|██▌       | 580/2248 [02:56<09:53,  2.81it/s]
 26%|██▌       | 581/2248 [02:56<10:51,  2.56it/s]
 26%|██▌       | 582/2248 [02:57<12:07,  2.29it/s]
 26%|██▌       | 584/2248 [02:57<09:35,  2.89it/s]
 26%|██▌       | 586/2248 [02:59<12:34,  2.20it/s]
 26%|██▌       | 587/2248 [02:59<10:35,  2.61it/s]
 26%|██▌       | 588/2248 [02:59<12:14,  2.26it/s]
 26%|██▌       | 589/2248 [03:00<11:24,  2.42it/s]
 26%|██▋       | 591/2248 [03:00<07:20,  3.76it/s]
 26%|██▋       | 592/2248 [03:00<09:32,  2.89it/s]
 26%|██▋       | 593/2248 [03:01<08:48,  3.13it/s]
 26%|██▋       | 594/2248 [03:01<08:38,  3.19it/s]
 26%|██▋       | 595/2248 [03:01<08:24,  3.28it/s]
 27%|██▋       | 597/2248 [03:01<05:32,  4.96it/s]
 27%|██▋       | 599/2248 [03:02<06:53,  3.99it/s]
 27%|██▋       | 600/2248 [03:02<07:50,  3.50it/s]
 27%|██▋       | 601/2248 [03:03<07:16,  3.77it/s]
 27%|██▋       | 603/2248 [03:04<09:04,  3.02it/s]
 27%|██▋       | 604/2248 [03:04<09:44,  2.81it/s]
 27%|██▋       | 605/2248 [03:05<12:15,  2.23it/s]
 27%|██▋       | 606/2248 [03:06<15:04,  1.81it/s]
 27%|██▋       | 607/2248 [03:06<15:01,  1.82it/s]
 27%|██▋       | 608/2248 [03:07<16:03,  1.70it/s]
 27%|██▋       | 609/2248 [03:07<16:28,  1.66it/s]
 27%|██▋       | 610/2248 [03:08<16:04,  1.70it/s]
 27%|██▋       | 612/2248 [03:08<11:33,  2.36it/s]
 27%|██▋       | 613/2248 [03:09<11:32,  2.36it/s]
 27%|██▋       | 616/2248 [03:09<08:02,  3.38it/s]
 28%|██▊       | 619/2248 [03:10<06:45,  4.01it/s]
 28%|██▊       | 620/2248 [03:10<07:59,  3.40it/s]
 28%|██▊       | 621/2248 [03:11<09:09,  2.96it/s]
 28%|██▊       | 622/2248 [03:11<08:26,  3.21it/s]
 28%|██▊       | 624/2248 [03:12<06:53,  3.92it/s]
 28%|██▊       | 625/2248 [03:12<07:13,  3.75it/s]
 28%|██▊       | 627/2248 [03:12<05:05,  5.30it/s]
 28%|██▊       | 630/2248 [03:12<03:18,  8.14it/s]
 28%|██▊       | 632/2248 [03:13<04:15,  6.31it/s]
 28%|██▊       | 635/2248 [03:13<04:29,  6.00it/s]
 28%|██▊       | 636/2248 [03:14<05:52,  4.57it/s]
 28%|██▊       | 639/2248 [03:14<03:55,  6.82it/s]
 29%|██▊       | 641/2248 [03:14<04:44,  5.65it/s]
 29%|██▊       | 644/2248 [03:14<03:19,  8.05it/s]
 29%|██▊       | 646/2248 [03:15<04:18,  6.21it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 304.80it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 8], [np.int64(2), False, 8], [np.int64(3), False, 6], [np.int64(4), False, 13], [np.int64(5), False, 13], [np.int64(6), False, 8], [np.int64(7), False, 9], [np.int64(10), False, 1], [np.int64(11), False, 8], [np.int64(12), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.8720, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3368, device='cuda:0', grad_fn=<MulBackward0>)

 34%|███▎      | 101/300 [11:58<5:52:58, 106.42s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 34%|███▍      | 102/300 [11:58<4:49:17, 87.67s/it]

tensor(12.8497, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.3901, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8271, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.4749, device='cuda:0', grad_fn=<MulBackward0>)

 35%|███▌      | 105/300 [11:59<2:14:10, 41.28s/it]

tensor(12.8079, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.5877, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7952, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.7078, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▌      | 107/300 [11:59<1:12:22, 22.50s/it]

tensor(12.7914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.8201, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-3.9262, device='cuda:0', grad_fn=<MulBackward0>)

 36%|███▋      | 109/300 [11:59<37:15, 11.71s/it]

tensor(12.8075, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0093, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8217, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.0870, device='cuda:0', grad_fn=<MulBackward0>)

 37%|███▋      | 111/300 [11:59<18:45,  5.96s/it]

tensor(12.8336, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.1539, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8385, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2077, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 113/300 [12:00<09:24,  3.02s/it]

tensor(12.8330, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.8169, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.2908, device='cuda:0', grad_fn=<MulBackward0>)

 38%|███▊      | 115/300 [12:00<04:46,  1.55s/it]

tensor(12.7923, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3322, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.7617, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.3645, device='cuda:0', grad_fn=<MulBackward0>)

 39%|███▉      | 117/300 [12:00<02:30,  1.22it/s]

tensor(12.7286, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4013, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6957, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4328, device='cuda:0', grad_fn=<MulBackward0>)

 40%|███▉      | 119/300 [12:00<01:23,  2.16it/s]

tensor(12.6651, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4596, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.6375, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4807, device='cuda:0', grad_fn=<MulBackward0>)

 40%|████      | 121/300 [12:00<00:51,  3.50it/s]

tensor(12.6129, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.4974, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5911, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5239, device='cuda:0', grad_fn=<MulBackward0>)

 41%|████      | 123/300 [12:01<00:35,  5.02it/s]

tensor(12.5715, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5399, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5536, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5537, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 125/300 [12:01<00:27,  6.39it/s]

tensor(12.5370, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5703, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.5213, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.5929, device='cuda:0', grad_fn=<MulBackward0>)

 42%|████▏     | 127/300 [12:01<00:23,  7.33it/s]

tensor(12.5063, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6133, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4918, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6353, device='cuda:0', grad_fn=<MulBackward0>)

 43%|████▎     | 129/300 [12:01<00:21,  7.95it/s]

tensor(12.4778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6444, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4646, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6657, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▎     | 131/300 [12:02<00:20,  8.32it/s]

tensor(12.4521, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.6924, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4404, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7134, device='cuda:0', grad_fn=<MulBackward0>)

 44%|████▍     | 133/300 [12:02<00:19,  8.46it/s]

tensor(12.4294, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7331, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4192, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7512, device='cuda:0', grad_fn=<MulBackward0>)

 45%|████▌     | 135/300 [12:02<00:19,  8.48it/s]

tensor(12.4095, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7683, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.4001, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.7865, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▌     | 137/300 [12:02<00:19,  8.54it/s]

tensor(12.3909, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8048, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3817, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8236, device='cuda:0', grad_fn=<MulBackward0>)

 46%|████▋     | 139/300 [12:03<00:18,  8.48it/s]

tensor(12.3727, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8471, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8626, device='cuda:0', grad_fn=<MulBackward0>)

 47%|████▋     | 141/300 [12:03<00:18,  8.57it/s]

tensor(12.3551, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8813, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3466, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0250, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8986, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 143/300 [12:03<00:18,  8.46it/s]

tensor(12.3384, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9141, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3303, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9331, device='cuda:0', grad_fn=<MulBackward0>)

 48%|████▊     | 145/300 [12:03<00:18,  8.58it/s]

tensor(12.3225, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9523, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.3147, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9687, device='cuda:0', grad_fn=<MulBackward0>)

 49%|████▉     | 147/300 [12:04<00:17,  8.54it/s]

tensor(12.3070, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9830, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2995, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0005, device='cuda:0', grad_fn=<MulBackward0>)

 50%|████▉     | 149/300 [12:04<00:17,  8.62it/s]

tensor(12.2925, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9930, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0119, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 150/300 [12:04<00:17,  8.58it/s]

tensor(12.2799, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0281, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([111, 200,  76, 217, 113,  90,  75, 213, 523,  91,  58,  55,  69, 357])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<02:08, 17.44it/s]
  0%|          | 9/2248 [00:00<02:08, 17.38it/s]
  0%|          | 11/2248 [00:00<02:05, 17.79it/s]
  1%|          | 17/2248 [00:00<01:20, 27.73it/s]
  1%|          | 25/2248 [00:00<00:55, 40.29it/s]
  1%|▏         | 31/2248 [00:00<00:49, 44.77it/s]
  2%|▏         | 37/2248 [00:01<01:45, 20.87it/s]
  2%|▏         | 41/2248 [00:01<02:01, 18.16it/s]
  2%|▏         | 44/2248 [00:02<02:32, 14.44it/s]
  2%|▏         | 47/2248 [00:02<03:09, 11.61it/s]
  2%|▏         | 49/2248 [00:02<02:58, 12.31it/s]
  2%|▏         | 52/2248 [00:03<03:23, 10.80it/s]
  2%|▏         | 54/2248 [00:03<03:10, 11.53it/s]
  2%|▏         | 56/2248 [00:03<04:02,  9.03it/s]
  3%|▎         | 61/2248 [00:03<02:35, 14.04it/s]
  3%|▎         | 64/2248 [00:03<02:28, 14.73it/s]
  3%|▎         | 67/2248 [00:04<04:01,  9.02it/s]
  3%|▎         | 69/2248 [00:04<03:36, 10.04it/s]
  3%|▎         | 72/2248 [00:04<02:56, 12.32it/s]
  3%|▎         | 75/2248 [00:05<04:12,  8.62it/s]
  3%|▎         | 77/2248 [00:05<03:54,  9.27it/s]
  4%|▎         | 79/2248 [00:05<03:26, 10.50it/s]
  4%|▎         | 81/2248 [00:06<04:53,  7.37it/s]
  4%|▎         | 83/2248 [00:06<05:36,  6.43it/s]
  4%|▎         | 84/2248 [00:06<05:35,  6.45it/s]
  4%|▍         | 86/2248 [00:06<04:26,  8.10it/s]
  4%|▍         | 88/2248 [00:07<06:19,  5.69it/s]
  4%|▍         | 89/2248 [00:07<07:23,  4.86it/s]
  4%|▍         | 91/2248 [00:07<05:33,  6.46it/s]
  4%|▍         | 94/2248 [00:08<05:28,  6.56it/s]
  4%|▍         | 96/2248 [00:08<06:00,  5.97it/s]
  4%|▍         | 97/2248 [00:09<10:49,  3.31it/s]
  4%|▍         | 98/2248 [00:10<11:26,  3.13it/s]
  4%|▍         | 100/2248 [00:10<09:44,  3.68it/s]
  4%|▍         | 101/2248 [00:10<09:12,  3.88it/s]
  5%|▍         | 102/2248 [00:10<08:29,  4.21it/s]
  5%|▍         | 104/2248 [00:11<07:08,  5.00it/s]
  5%|▍         | 106/2248 [00:11<05:22,  6.64it/s]
  5%|▍         | 107/2248 [00:11<06:59,  5.10it/s]
  5%|▍         | 109/2248 [00:12<07:10,  4.97it/s]
  5%|▍         | 110/2248 [00:12<08:25,  4.23it/s]
  5%|▍         | 112/2248 [00:12<08:06,  4.39it/s]
  5%|▌         | 113/2248 [00:13<09:14,  3.85it/s]
  5%|▌         | 114/2248 [00:13<09:50,  3.61it/s]
  5%|▌         | 117/2248 [00:14<10:29,  3.39it/s]
  5%|▌         | 119/2248 [00:14<07:48,  4.55it/s]
  5%|▌         | 120/2248 [00:15<12:04,  2.94it/s]
  5%|▌         | 121/2248 [00:15<10:24,  3.41it/s]
  5%|▌         | 123/2248 [00:15<08:45,  4.04it/s]
  6%|▌         | 125/2248 [00:16<06:23,  5.54it/s]
  6%|▌         | 126/2248 [00:16<07:56,  4.45it/s]
  6%|▌         | 127/2248 [00:16<08:08,  4.34it/s]
  6%|▌         | 128/2248 [00:17<10:29,  3.37it/s]
  6%|▌         | 129/2248 [00:17<08:44,  4.04it/s]
  6%|▌         | 133/2248 [00:17<06:09,  5.73it/s]
  6%|▌         | 135/2248 [00:18<06:55,  5.08it/s]
  6%|▌         | 136/2248 [00:19<10:29,  3.36it/s]
  6%|▌         | 138/2248 [00:19<10:04,  3.49it/s]
  6%|▌         | 139/2248 [00:19<09:38,  3.65it/s]
  6%|▋         | 141/2248 [00:19<06:51,  5.13it/s]
  6%|▋         | 142/2248 [00:20<10:07,  3.46it/s]
  6%|▋         | 145/2248 [00:21<08:11,  4.28it/s]
  7%|▋         | 148/2248 [00:21<05:25,  6.46it/s]
  7%|▋         | 151/2248 [00:21<06:11,  5.65it/s]
  7%|▋         | 154/2248 [00:22<04:41,  7.43it/s]
  7%|▋         | 156/2248 [00:23<07:38,  4.56it/s]
  7%|▋         | 157/2248 [00:23<10:55,  3.19it/s]
  7%|▋         | 158/2248 [00:24<13:11,  2.64it/s]
  7%|▋         | 159/2248 [00:25<14:14,  2.44it/s]
  7%|▋         | 160/2248 [00:25<13:41,  2.54it/s]
  7%|▋         | 162/2248 [00:25<11:41,  2.97it/s]
  7%|▋         | 165/2248 [00:26<08:30,  4.08it/s]
  7%|▋         | 167/2248 [00:26<06:33,  5.28it/s]
  8%|▊         | 169/2248 [00:27<09:27,  3.66it/s]
  8%|▊         | 170/2248 [00:27<09:36,  3.60it/s]
  8%|▊         | 171/2248 [00:28<10:13,  3.39it/s]
  8%|▊         | 172/2248 [00:28<09:13,  3.75it/s]
  8%|▊         | 174/2248 [00:28<07:58,  4.34it/s]
  8%|▊         | 176/2248 [00:28<07:33,  4.56it/s]
  8%|▊         | 177/2248 [00:29<06:53,  5.00it/s]
  8%|▊         | 179/2248 [00:29<06:56,  4.96it/s]
  8%|▊         | 181/2248 [00:29<05:10,  6.65it/s]
  8%|▊         | 183/2248 [00:29<05:43,  6.02it/s]
  8%|▊         | 184/2248 [00:30<05:47,  5.94it/s]
  8%|▊         | 186/2248 [00:30<04:59,  6.88it/s]
  8%|▊         | 187/2248 [00:31<11:18,  3.04it/s]
  8%|▊         | 188/2248 [00:31<10:36,  3.24it/s]
  8%|▊         | 189/2248 [00:32<11:08,  3.08it/s]
  8%|▊         | 190/2248 [00:32<09:59,  3.43it/s]
  8%|▊         | 191/2248 [00:32<10:06,  3.39it/s]
  9%|▊         | 192/2248 [00:32<10:35,  3.23it/s]
  9%|▊         | 194/2248 [00:33<09:29,  3.60it/s]
  9%|▊         | 195/2248 [00:33<12:11,  2.81it/s]
  9%|▉         | 197/2248 [00:34<09:21,  3.65it/s]
  9%|▉         | 199/2248 [00:34<07:33,  4.52it/s]
  9%|▉         | 200/2248 [00:34<08:50,  3.86it/s]
  9%|▉         | 202/2248 [00:35<08:34,  3.98it/s]
  9%|▉         | 203/2248 [00:35<09:09,  3.72it/s]
  9%|▉         | 204/2248 [00:35<08:03,  4.23it/s]
  9%|▉         | 206/2248 [00:35<05:41,  5.98it/s]
  9%|▉         | 207/2248 [00:36<07:12,  4.72it/s]
  9%|▉         | 209/2248 [00:36<06:57,  4.88it/s]
  9%|▉         | 210/2248 [00:37<10:51,  3.13it/s]
  9%|▉         | 211/2248 [00:37<11:37,  2.92it/s]
  9%|▉         | 213/2248 [00:38<09:24,  3.60it/s]
 10%|▉         | 215/2248 [00:38<06:54,  4.90it/s]
 10%|▉         | 216/2248 [00:38<07:27,  4.54it/s]
 10%|▉         | 220/2248 [00:38<03:55,  8.62it/s]
 10%|▉         | 224/2248 [00:38<02:37, 12.82it/s]
 10%|█         | 229/2248 [00:39<01:46, 18.93it/s]
 10%|█         | 233/2248 [00:39<01:32, 21.84it/s]
 11%|█         | 240/2248 [00:39<01:04, 31.18it/s]
 11%|█         | 247/2248 [00:39<00:51, 38.97it/s]
 11%|█▏        | 254/2248 [00:39<00:43, 45.55it/s]
 12%|█▏        | 261/2248 [00:39<00:38, 51.56it/s]
 12%|█▏        | 267/2248 [00:43<06:03,  5.45it/s]
 12%|█▏        | 272/2248 [00:44<06:58,  4.72it/s]
 12%|█▏        | 275/2248 [00:45<07:43,  4.25it/s]
 12%|█▏        | 278/2248 [00:46<07:16,  4.51it/s]
 12%|█▏        | 280/2248 [00:46<07:48,  4.20it/s]
 13%|█▎        | 282/2248 [00:47<08:50,  3.71it/s]
 13%|█▎        | 284/2248 [00:48<08:46,  3.73it/s]
 13%|█▎        | 286/2248 [00:48<09:34,  3.42it/s]
 13%|█▎        | 287/2248 [00:49<11:02,  2.96it/s]
 13%|█▎        | 289/2248 [00:49<08:53,  3.67it/s]
 13%|█▎        | 290/2248 [00:49<08:56,  3.65it/s]
 13%|█▎        | 292/2248 [00:50<06:40,  4.89it/s]
 13%|█▎        | 295/2248 [00:50<04:26,  7.34it/s]
 13%|█▎        | 297/2248 [00:50<04:55,  6.59it/s]
 13%|█▎        | 299/2248 [00:52<11:38,  2.79it/s]
 13%|█▎        | 301/2248 [00:52<08:49,  3.68it/s]
 13%|█▎        | 303/2248 [00:53<12:20,  2.63it/s]
 14%|█▎        | 304/2248 [00:54<12:33,  2.58it/s]
 14%|█▎        | 305/2248 [00:54<12:17,  2.63it/s]
 14%|█▎        | 306/2248 [00:54<11:43,  2.76it/s]
 14%|█▎        | 307/2248 [00:55<12:21,  2.62it/s]
 14%|█▎        | 308/2248 [00:55<14:02,  2.30it/s]
 14%|█▍        | 310/2248 [00:56<10:39,  3.03it/s]
 14%|█▍        | 312/2248 [00:56<09:24,  3.43it/s]
 14%|█▍        | 313/2248 [00:57<10:56,  2.95it/s]
 14%|█▍        | 314/2248 [00:57<12:28,  2.58it/s]
 14%|█▍        | 315/2248 [00:58<14:32,  2.22it/s]
 14%|█▍        | 317/2248 [00:58<09:13,  3.49it/s]
 14%|█▍        | 318/2248 [00:58<10:13,  3.15it/s]
 14%|█▍        | 320/2248 [00:59<08:50,  3.63it/s]
 14%|█▍        | 322/2248 [00:59<07:54,  4.06it/s]
 14%|█▍        | 323/2248 [01:00<10:03,  3.19it/s]
 14%|█▍        | 324/2248 [01:00<10:08,  3.16it/s]
 14%|█▍        | 325/2248 [01:00<10:14,  3.13it/s]
 15%|█▍        | 327/2248 [01:01<08:49,  3.63it/s]
 15%|█▍        | 328/2248 [01:01<10:42,  2.99it/s]
 15%|█▍        | 329/2248 [01:02<11:44,  2.72it/s]
 15%|█▍        | 331/2248 [01:02<07:58,  4.01it/s]
 15%|█▍        | 332/2248 [01:02<08:32,  3.74it/s]
 15%|█▍        | 334/2248 [01:02<05:53,  5.42it/s]
 15%|█▌        | 339/2248 [01:03<05:55,  5.37it/s]
 15%|█▌        | 340/2248 [01:04<08:32,  3.73it/s]
 15%|█▌        | 343/2248 [01:05<08:08,  3.90it/s]
 15%|█▌        | 344/2248 [01:06<11:09,  2.84it/s]
 15%|█▌        | 345/2248 [01:07<14:33,  2.18it/s]
 15%|█▌        | 346/2248 [01:08<17:45,  1.78it/s]
 15%|█▌        | 347/2248 [01:09<20:16,  1.56it/s]
 15%|█▌        | 348/2248 [01:09<22:28,  1.41it/s]
 16%|█▌        | 349/2248 [01:10<24:29,  1.29it/s]
 16%|█▌        | 350/2248 [01:10<18:46,  1.68it/s]
 16%|█▌        | 353/2248 [01:11<13:51,  2.28it/s]
 16%|█▌        | 354/2248 [01:12<16:24,  1.92it/s]
 16%|█▌        | 355/2248 [01:13<18:31,  1.70it/s]
 16%|█▌        | 357/2248 [01:13<12:15,  2.57it/s]
 16%|█▌        | 360/2248 [01:13<07:08,  4.41it/s]
 16%|█▌        | 364/2248 [01:13<04:11,  7.50it/s]
 16%|█▋        | 367/2248 [01:14<04:44,  6.62it/s]
 16%|█▋        | 369/2248 [01:14<04:46,  6.56it/s]
 17%|█▋        | 371/2248 [01:15<05:45,  5.44it/s]
 17%|█▋        | 373/2248 [01:16<08:18,  3.76it/s]
 17%|█▋        | 374/2248 [01:16<08:31,  3.66it/s]
 17%|█▋        | 376/2248 [01:16<06:30,  4.79it/s]
 17%|█▋        | 382/2248 [01:16<03:06,  9.99it/s]
 17%|█▋        | 385/2248 [01:18<05:50,  5.31it/s]
 17%|█▋        | 387/2248 [01:18<06:01,  5.16it/s]
 17%|█▋        | 389/2248 [01:19<07:43,  4.01it/s]
 17%|█▋        | 390/2248 [01:19<09:12,  3.37it/s]
 17%|█▋        | 391/2248 [01:20<09:07,  3.39it/s]
 17%|█▋        | 393/2248 [01:20<08:15,  3.74it/s]
 18%|█▊        | 394/2248 [01:21<10:20,  2.99it/s]
 18%|█▊        | 396/2248 [01:21<07:19,  4.22it/s]
 18%|█▊        | 402/2248 [01:21<03:39,  8.41it/s]
 18%|█▊        | 405/2248 [01:21<02:53, 10.63it/s]
 18%|█▊        | 410/2248 [01:21<01:58, 15.57it/s]
 18%|█▊        | 413/2248 [01:22<02:34, 11.88it/s]
 19%|█▊        | 417/2248 [01:22<02:50, 10.71it/s]
 19%|█▊        | 420/2248 [01:23<03:10,  9.62it/s]
 19%|█▉        | 422/2248 [01:23<02:57, 10.31it/s]
 19%|█▉        | 424/2248 [01:23<03:33,  8.56it/s]
 19%|█▉        | 427/2248 [01:24<03:47,  8.01it/s]
 19%|█▉        | 430/2248 [01:24<03:04,  9.87it/s]
 19%|█▉        | 435/2248 [01:24<02:02, 14.84it/s]
 19%|█▉        | 438/2248 [01:26<06:23,  4.71it/s]
 20%|█▉        | 440/2248 [01:27<10:32,  2.86it/s]
 20%|█▉        | 442/2248 [01:28<08:35,  3.51it/s]
 20%|█▉        | 446/2248 [01:29<08:06,  3.70it/s]
 20%|█▉        | 448/2248 [01:29<06:48,  4.40it/s]
 20%|██        | 450/2248 [01:30<08:39,  3.46it/s]
 20%|██        | 452/2248 [01:30<06:50,  4.38it/s]
 20%|██        | 454/2248 [01:31<09:40,  3.09it/s]
 20%|██        | 456/2248 [01:31<08:14,  3.62it/s]
 20%|██        | 457/2248 [01:32<11:31,  2.59it/s]
 20%|██        | 459/2248 [01:33<11:03,  2.70it/s]
 20%|██        | 460/2248 [01:34<12:48,  2.33it/s]
 21%|██        | 462/2248 [01:34<09:50,  3.03it/s]
 21%|██        | 463/2248 [01:34<10:08,  2.93it/s]
 21%|██        | 464/2248 [01:35<12:19,  2.41it/s]
 21%|██        | 465/2248 [01:35<10:08,  2.93it/s]
 21%|██        | 467/2248 [01:35<08:37,  3.44it/s]
 21%|██        | 469/2248 [01:36<07:41,  3.86it/s]
 21%|██        | 471/2248 [01:37<09:50,  3.01it/s]
 21%|██        | 472/2248 [01:38<13:02,  2.27it/s]
 21%|██        | 473/2248 [01:39<16:08,  1.83it/s]
 21%|██        | 475/2248 [01:40<15:32,  1.90it/s]
 21%|██        | 476/2248 [01:40<17:59,  1.64it/s]
 21%|██        | 477/2248 [01:41<19:41,  1.50it/s]
 21%|██▏       | 478/2248 [01:42<17:05,  1.73it/s]
 21%|██▏       | 479/2248 [01:43<19:07,  1.54it/s]
 21%|██▏       | 480/2248 [01:43<20:36,  1.43it/s]
 21%|██▏       | 481/2248 [01:44<22:25,  1.31it/s]
 21%|██▏       | 482/2248 [01:45<23:17,  1.26it/s]
 21%|██▏       | 483/2248 [01:46<19:53,  1.48it/s]
 22%|██▏       | 485/2248 [01:47<17:54,  1.64it/s]
 22%|██▏       | 486/2248 [01:48<20:18,  1.45it/s]
 22%|██▏       | 487/2248 [01:48<22:13,  1.32it/s]
 22%|██▏       | 490/2248 [01:49<11:10,  2.62it/s]
 22%|██▏       | 495/2248 [01:50<08:01,  3.64it/s]
 22%|██▏       | 498/2248 [01:50<06:49,  4.27it/s]
 22%|██▏       | 499/2248 [01:50<07:40,  3.79it/s]
 22%|██▏       | 501/2248 [01:51<06:08,  4.74it/s]
 22%|██▏       | 503/2248 [01:51<04:52,  5.97it/s]
 23%|██▎       | 509/2248 [01:52<04:39,  6.22it/s]
 23%|██▎       | 510/2248 [01:53<07:06,  4.08it/s]
 23%|██▎       | 513/2248 [01:53<05:07,  5.64it/s]
 23%|██▎       | 515/2248 [01:54<09:05,  3.18it/s]
 23%|██▎       | 517/2248 [01:54<07:12,  4.00it/s]
 23%|██▎       | 519/2248 [01:54<05:41,  5.06it/s]
 23%|██▎       | 523/2248 [01:54<03:34,  8.06it/s]
 23%|██▎       | 527/2248 [01:55<03:24,  8.43it/s]
 24%|██▎       | 529/2248 [01:55<03:14,  8.85it/s]
 24%|██▎       | 532/2248 [01:55<02:32, 11.25it/s]
 24%|██▍       | 534/2248 [01:56<03:14,  8.81it/s]
 24%|██▍       | 538/2248 [01:56<02:14, 12.68it/s]
 24%|██▍       | 544/2248 [01:56<02:11, 12.91it/s]
 24%|██▍       | 546/2248 [01:56<02:06, 13.47it/s]
 24%|██▍       | 550/2248 [01:56<01:38, 17.21it/s]
 25%|██▍       | 553/2248 [01:57<01:28, 19.09it/s]
 25%|██▍       | 561/2248 [01:57<00:55, 30.43it/s]
 25%|██▌       | 565/2248 [01:57<01:23, 20.27it/s]
 25%|██▌       | 569/2248 [01:57<01:12, 23.09it/s]
 25%|██▌       | 573/2248 [01:59<05:25,  5.15it/s]
 26%|██▌       | 576/2248 [02:00<04:58,  5.59it/s]
 26%|██▌       | 578/2248 [02:00<05:39,  4.92it/s]
 26%|██▌       | 580/2248 [02:01<06:20,  4.39it/s]
 26%|██▌       | 582/2248 [02:02<06:45,  4.11it/s]
 26%|██▌       | 584/2248 [02:03<07:53,  3.51it/s]
 26%|██▌       | 586/2248 [02:03<09:13,  3.00it/s]
 26%|██▌       | 588/2248 [02:04<10:01,  2.76it/s]
 26%|██▌       | 589/2248 [02:05<10:17,  2.68it/s]
 26%|██▋       | 591/2248 [02:05<07:31,  3.67it/s]
 26%|██▋       | 592/2248 [02:06<10:19,  2.67it/s]
 26%|██▋       | 595/2248 [02:06<06:16,  4.40it/s]
 27%|██▋       | 599/2248 [02:07<06:07,  4.48it/s]
 27%|██▋       | 600/2248 [02:08<08:32,  3.21it/s]
 27%|██▋       | 603/2248 [02:08<05:46,  4.75it/s]
 27%|██▋       | 605/2248 [02:09<10:27,  2.62it/s]
 27%|██▋       | 606/2248 [02:10<12:34,  2.18it/s]
 27%|██▋       | 607/2248 [02:11<14:50,  1.84it/s]
 27%|██▋       | 608/2248 [02:12<16:50,  1.62it/s]
 27%|██▋       | 609/2248 [02:13<18:48,  1.45it/s]
 27%|██▋       | 610/2248 [02:14<20:19,  1.34it/s]
 27%|██▋       | 612/2248 [02:14<12:36,  2.16it/s]
 27%|██▋       | 613/2248 [02:14<11:13,  2.43it/s]
 27%|██▋       | 616/2248 [02:15<07:36,  3.58it/s]
 27%|██▋       | 617/2248 [02:15<07:42,  3.53it/s]
 28%|██▊       | 619/2248 [02:15<05:35,  4.86it/s]
 28%|██▊       | 621/2248 [02:16<05:39,  4.79it/s]
 28%|██▊       | 622/2248 [02:16<06:31,  4.15it/s]
 28%|██▊       | 625/2248 [02:16<04:04,  6.63it/s]
 28%|██▊       | 628/2248 [02:16<03:49,  7.05it/s]
 28%|██▊       | 631/2248 [02:17<03:53,  6.91it/s]
 28%|██▊       | 635/2248 [02:17<02:40, 10.04it/s]
 28%|██▊       | 637/2248 [02:18<04:20,  6.18it/s]
 28%|██▊       | 639/2248 [02:18<03:36,  7.42it/s]
 29%|██▊       | 641/2248 [02:18<03:59,  6.70it/s]
 29%|██▊       | 643/2248 [02:18<03:17,  8.13it/s]
 29%|██▉       | 650/2248 [02:18<01:38, 16.17it/s]
 29%|██▉       | 653/2248 [02:20<05:14,  5.07it/s]
 29%|██▉       | 656/2248 [02:20<04:08,  6.41it/s]
 29%|██▉       | 659/2248 [02:21<05:17,  5.00it/s]
 29%|██▉       | 661/2248 [02:23<09:01,  2.93it/s]
 29%|██▉       | 663/2248 [02:24<09:53,  2.67it/s]
 30%|██▉       | 666/2248 [02:24<06:57,  3.79it/s]
 30%|██▉       | 668/2248 [02:25<08:23,  3.14it/s]
 30%|██▉       | 670/2248 [02:26<09:21,  2.81it/s]
 30%|██▉       | 671/2248 [02:26<08:51,  2.97it/s]
 30%|██▉       | 673/2248 [02:26<06:39,  3.94it/s]
 30%|███       | 678/2248 [02:27<05:50,  4.48it/s]
 30%|███       | 679/2248 [02:28<06:22,  4.10it/s]
 30%|███       | 682/2248 [02:29<07:11,  3.63it/s]
 30%|███       | 683/2248 [02:30<09:28,  2.75it/s]
 30%|███       | 684/2248 [02:30<09:15,  2.82it/s]
 30%|███       | 685/2248 [02:30<09:05,  2.86it/s]
 31%|███       | 686/2248 [02:31<11:44,  2.22it/s]
 31%|███       | 688/2248 [02:32<10:30,  2.47it/s]
 31%|███       | 690/2248 [02:32<07:13,  3.59it/s]
 31%|███       | 691/2248 [02:32<07:22,  3.52it/s]
 31%|███       | 692/2248 [02:33<10:25,  2.49it/s]
 31%|███       | 694/2248 [02:33<07:50,  3.30it/s]
 31%|███       | 695/2248 [02:34<09:21,  2.77it/s]
 31%|███       | 696/2248 [02:34<08:34,  3.02it/s]
 31%|███       | 698/2248 [02:34<06:54,  3.74it/s]
 31%|███       | 700/2248 [02:35<05:24,  4.76it/s]
 31%|███       | 702/2248 [02:36<07:29,  3.44it/s]
 31%|███▏      | 704/2248 [02:36<05:31,  4.65it/s]
 32%|███▏      | 709/2248 [02:37<05:04,  5.05it/s]
 32%|███▏      | 710/2248 [02:37<05:44,  4.46it/s]
 32%|███▏      | 711/2248 [02:38<08:31,  3.00it/s]
 32%|███▏      | 713/2248 [02:39<09:36,  2.66it/s]
 32%|███▏      | 714/2248 [02:39<09:21,  2.73it/s]
 32%|███▏      | 715/2248 [02:39<08:35,  2.97it/s]
 32%|███▏      | 716/2248 [02:40<08:00,  3.19it/s]
 32%|███▏      | 717/2248 [02:40<08:46,  2.91it/s]
 32%|███▏      | 718/2248 [02:40<08:46,  2.91it/s]
 32%|███▏      | 720/2248 [02:41<10:00,  2.55it/s]
 32%|███▏      | 722/2248 [02:41<06:42,  3.79it/s]
 32%|███▏      | 723/2248 [02:42<07:21,  3.45it/s]
 32%|███▏      | 725/2248 [02:42<06:29,  3.91it/s]
 32%|███▏      | 726/2248 [02:43<07:06,  3.57it/s]
 32%|███▏      | 728/2248 [02:44<08:51,  2.86it/s]
 32%|███▏      | 729/2248 [02:44<09:01,  2.81it/s]
 32%|███▏      | 730/2248 [02:44<08:47,  2.88it/s]
 33%|███▎      | 731/2248 [02:45<10:31,  2.40it/s]
 33%|███▎      | 732/2248 [02:45<11:54,  2.12it/s]
 33%|███▎      | 733/2248 [02:46<14:43,  1.71it/s]
 33%|███▎      | 734/2248 [02:47<13:11,  1.91it/s]
 33%|███▎      | 735/2248 [02:48<16:30,  1.53it/s]
 33%|███▎      | 736/2248 [02:48<15:43,  1.60it/s]
 33%|███▎      | 737/2248 [02:49<13:07,  1.92it/s]
 33%|███▎      | 738/2248 [02:49<11:24,  2.21it/s]
 33%|███▎      | 739/2248 [02:49<09:36,  2.62it/s]
 33%|███▎      | 742/2248 [02:50<07:22,  3.41it/s]
 33%|███▎      | 743/2248 [02:50<08:17,  3.02it/s]
 33%|███▎      | 744/2248 [02:51<08:52,  2.83it/s]
 33%|███▎      | 746/2248 [02:51<06:01,  4.16it/s]
 33%|███▎      | 749/2248 [02:52<06:15,  3.99it/s]
 33%|███▎      | 751/2248 [02:52<07:18,  3.41it/s]
 33%|███▎      | 752/2248 [02:53<08:22,  2.98it/s]
 34%|███▎      | 754/2248 [02:54<08:56,  2.78it/s]
 34%|███▎      | 757/2248 [02:54<05:38,  4.41it/s]
 34%|███▎      | 758/2248 [02:54<05:58,  4.16it/s]
 34%|███▍      | 761/2248 [02:55<06:26,  3.85it/s]
 34%|███▍      | 763/2248 [02:55<04:57,  4.99it/s]
 34%|███▍      | 765/2248 [02:55<05:08,  4.81it/s]
 34%|███▍      | 770/2248 [02:56<02:49,  8.72it/s]
 34%|███▍      | 772/2248 [02:57<04:41,  5.24it/s]
 34%|███▍      | 774/2248 [02:57<06:11,  3.97it/s]
 35%|███▍      | 776/2248 [02:59<10:02,  2.44it/s]
 35%|███▍      | 778/2248 [03:00<10:42,  2.29it/s]
 35%|███▍      | 780/2248 [03:00<08:06,  3.01it/s]
 35%|███▍      | 782/2248 [03:01<07:55,  3.08it/s]
 35%|███▍      | 783/2248 [03:01<07:56,  3.08it/s]
 35%|███▍      | 784/2248 [03:01<07:45,  3.14it/s]
 35%|███▍      | 786/2248 [03:02<05:54,  4.12it/s]
 35%|███▌      | 789/2248 [03:02<03:48,  6.38it/s]
 35%|███▌      | 792/2248 [03:02<03:37,  6.68it/s]
 35%|███▌      | 794/2248 [03:02<02:59,  8.10it/s]
 35%|███▌      | 797/2248 [03:03<04:43,  5.11it/s]
 36%|███▌      | 799/2248 [03:04<04:53,  4.94it/s]
 36%|███▌      | 802/2248 [03:04<03:29,  6.91it/s]
 36%|███▌      | 808/2248 [03:04<01:56, 12.40it/s]
 36%|███▌      | 811/2248 [03:04<02:18, 10.36it/s]
 36%|███▌      | 814/2248 [03:05<03:36,  6.63it/s]
 36%|███▋      | 816/2248 [03:06<05:30,  4.33it/s]
 36%|███▋      | 820/2248 [03:07<04:21,  5.46it/s]
 37%|███▋      | 822/2248 [03:07<03:41,  6.43it/s]
 37%|███▋      | 824/2248 [03:07<03:58,  5.98it/s]
 37%|███▋      | 826/2248 [03:08<04:08,  5.71it/s]
 37%|███▋      | 828/2248 [03:08<03:25,  6.90it/s]
 37%|███▋      | 830/2248 [03:08<03:41,  6.40it/s]
 37%|███▋      | 832/2248 [03:09<04:10,  5.64it/s]
 37%|███▋      | 834/2248 [03:09<03:23,  6.94it/s]
 37%|███▋      | 840/2248 [03:09<01:44, 13.52it/s]
 38%|███▊      | 848/2248 [03:09<01:02, 22.57it/s]
 38%|███▊      | 855/2248 [03:09<00:46, 29.87it/s]
 38%|███▊      | 862/2248 [03:09<00:37, 37.30it/s]
 39%|███▊      | 868/2248 [03:11<02:34,  8.93it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 292.40it/s]

[[np.int64(0), False, 13], [np.int64(1), False, 8], [np.int64(2), False, 1], [np.int64(3), False, 13], [np.int64(4), False, 0], [np.int64(5), False, 1], [np.int64(6), False, 0], [np.int64(7), False, 8], [np.int64(9), False, 5], [np.int64(10), False, 1], [np.int64(11), False, 8], [np.int64(12), False, 5]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.2746, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9187, device='cuda:0', grad_fn=<MulBackward0>)

 50%|█████     | 151/300 [20:28<6:15:25, 151.18s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 51%|█████     | 152/300 [20:28<4:21:09, 105.88s/it]

tensor(12.2691, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9742, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2667, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0752, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 155/300 [20:28<1:27:56, 36.39s/it]

tensor(12.2696, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1562, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2760, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2421, device='cuda:0', grad_fn=<MulBackward0>)

 52%|█████▏    | 157/300 [20:28<42:38, 17.89s/it]

tensor(12.2832, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0264, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2984, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2895, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0266, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3284, device='cuda:0', grad_fn=<MulBackward0>)

 53%|█████▎    | 159/300 [20:29<20:44,  8.83s/it]

tensor(12.2944, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0267, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3331, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3370, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▎    | 161/300 [20:29<10:09,  4.38s/it]

tensor(12.2985, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0273, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3430, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2965, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0271, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3493, device='cuda:0', grad_fn=<MulBackward0>)

 54%|█████▍    | 163/300 [20:29<05:02,  2.21s/it]

tensor(12.2917, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3509, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2847, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0258, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3676, device='cuda:0', grad_fn=<MulBackward0>)

 55%|█████▌    | 165/300 [20:29<02:34,  1.14s/it]

tensor(12.2761, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0253, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3708, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2666, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3829, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▌    | 167/300 [20:29<01:22,  1.62it/s]

tensor(12.2570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3914, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2477, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3986, device='cuda:0', grad_fn=<MulBackward0>)

 56%|█████▋    | 169/300 [20:30<00:47,  2.76it/s]

tensor(12.2392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4071, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2314, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4141, device='cuda:0', grad_fn=<MulBackward0>)

 57%|█████▋    | 171/300 [20:30<00:30,  4.24it/s]

tensor(12.2248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4228, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2184, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4310, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 173/300 [20:30<00:22,  5.70it/s]

tensor(12.2124, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4401, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.2066, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4490, device='cuda:0', grad_fn=<MulBackward0>)

 58%|█████▊    | 175/300 [20:30<00:18,  6.91it/s]

tensor(12.2013, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4533, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1963, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4563, device='cuda:0', grad_fn=<MulBackward0>)

 59%|█████▉    | 177/300 [20:31<00:16,  7.64it/s]

tensor(12.1914, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4659, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1860, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4712, device='cuda:0', grad_fn=<MulBackward0>)

 60%|█████▉    | 179/300 [20:31<00:14,  8.12it/s]

tensor(12.1810, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4743, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1758, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4791, device='cuda:0', grad_fn=<MulBackward0>)

 60%|██████    | 181/300 [20:31<00:14,  8.35it/s]

tensor(12.1710, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4808, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4871, device='cuda:0', grad_fn=<MulBackward0>)

 61%|██████    | 183/300 [20:31<00:13,  8.49it/s]

tensor(12.1622, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4961, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1579, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5038, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 185/300 [20:32<00:13,  8.53it/s]

tensor(12.1538, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5078, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5155, device='cuda:0', grad_fn=<MulBackward0>)

 62%|██████▏   | 187/300 [20:32<00:13,  8.50it/s]

tensor(12.1457, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0231, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5237, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1422, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5303, device='cuda:0', grad_fn=<MulBackward0>)

 63%|██████▎   | 189/300 [20:32<00:13,  8.41it/s]

tensor(12.1387, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5330, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1353, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5385, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▎   | 191/300 [20:32<00:12,  8.40it/s]

tensor(12.1323, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1292, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5496, device='cuda:0', grad_fn=<MulBackward0>)

 64%|██████▍   | 193/300 [20:32<00:12,  8.35it/s]

tensor(12.1263, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5527, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1231, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0227, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5598, device='cuda:0', grad_fn=<MulBackward0>)

 65%|██████▌   | 195/300 [20:33<00:12,  8.46it/s]

tensor(12.1205, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5633, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1180, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5687, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▌   | 197/300 [20:33<00:12,  8.51it/s]

tensor(12.1152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5719, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1127, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5736, device='cuda:0', grad_fn=<MulBackward0>)

 66%|██████▋   | 199/300 [20:33<00:11,  8.57it/s]

tensor(12.1103, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5774, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.1078, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5796, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 200/300 [20:33<00:11,  8.54it/s]

tensor(12.1055, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5823, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 83,  44, 431, 113,  55,  76, 107, 317, 145, 139,  64, 119, 265, 290])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 2/2248 [00:00<05:49,  6.43it/s]
  0%|          | 5/2248 [00:00<04:30,  8.29it/s]
  0%|          | 8/2248 [00:00<03:03, 12.24it/s]
  0%|          | 10/2248 [00:01<07:30,  4.97it/s]
  1%|          | 12/2248 [00:02<08:03,  4.62it/s]
  1%|          | 16/2248 [00:02<04:49,  7.70it/s]
  1%|          | 24/2248 [00:02<02:21, 15.74it/s]
  1%|▏         | 31/2248 [00:02<01:35, 23.10it/s]
  2%|▏         | 36/2248 [00:02<02:03, 17.87it/s]
  2%|▏         | 40/2248 [00:03<02:30, 14.72it/s]
  2%|▏         | 43/2248 [00:04<03:45,  9.77it/s]
  2%|▏         | 45/2248 [00:04<04:19,  8.49it/s]
  2%|▏         | 47/2248 [00:04<04:20,  8.46it/s]
  2%|▏         | 49/2248 [00:04<03:53,  9.43it/s]
  2%|▏         | 52/2248 [00:04<03:26, 10.64it/s]
  2%|▏         | 54/2248 [00:05<04:25,  8.26it/s]
  2%|▏         | 56/2248 [00:05<04:34,  7.98it/s]
  3%|▎         | 58/2248 [00:06<05:18,  6.88it/s]
  3%|▎         | 59/2248 [00:06<06:24,  5.70it/s]
  3%|▎         | 61/2248 [00:06<04:59,  7.30it/s]
  3%|▎         | 63/2248 [00:06<05:42,  6.38it/s]
  3%|▎         | 65/2248 [00:07<04:37,  7.86it/s]
  3%|▎         | 67/2248 [00:07<06:01,  6.03it/s]
  3%|▎         | 69/2248 [00:07<04:58,  7.29it/s]
  3%|▎         | 71/2248 [00:08<06:34,  5.52it/s]
  3%|▎         | 73/2248 [00:08<05:08,  7.05it/s]
  3%|▎         | 75/2248 [00:09<07:41,  4.71it/s]
  3%|▎         | 76/2248 [00:09<07:32,  4.80it/s]
  3%|▎         | 77/2248 [00:09<09:21,  3.87it/s]
  3%|▎         | 78/2248 [00:09<08:47,  4.11it/s]
  4%|▎         | 80/2248 [00:10<07:11,  5.02it/s]
  4%|▎         | 81/2248 [00:10<07:15,  4.98it/s]
  4%|▎         | 82/2248 [00:10<07:24,  4.87it/s]
  4%|▎         | 83/2248 [00:10<07:33,  4.77it/s]
  4%|▎         | 84/2248 [00:11<07:25,  4.86it/s]
  4%|▍         | 86/2248 [00:11<06:11,  5.82it/s]
  4%|▍         | 87/2248 [00:11<06:15,  5.75it/s]
  4%|▍         | 89/2248 [00:11<05:15,  6.84it/s]
  4%|▍         | 90/2248 [00:11<05:10,  6.96it/s]
  4%|▍         | 92/2248 [00:11<03:53,  9.25it/s]
  4%|▍         | 94/2248 [00:12<03:52,  9.27it/s]
  4%|▍         | 96/2248 [00:12<05:12,  6.89it/s]
  4%|▍         | 97/2248 [00:13<09:32,  3.76it/s]
  4%|▍         | 98/2248 [00:13<08:59,  3.98it/s]
  4%|▍         | 100/2248 [00:13<07:10,  4.99it/s]
  4%|▍         | 101/2248 [00:14<07:08,  5.01it/s]
  5%|▍         | 102/2248 [00:14<06:41,  5.34it/s]
  5%|▍         | 103/2248 [00:14<06:26,  5.55it/s]
  5%|▍         | 104/2248 [00:14<06:25,  5.56it/s]
  5%|▍         | 105/2248 [00:14<06:39,  5.36it/s]
  5%|▍         | 107/2248 [00:14<04:53,  7.31it/s]
  5%|▍         | 109/2248 [00:14<04:04,  8.74it/s]
  5%|▍         | 110/2248 [00:15<04:36,  7.73it/s]
  5%|▍         | 112/2248 [00:15<05:00,  7.10it/s]
  5%|▌         | 113/2248 [00:15<04:47,  7.43it/s]
  5%|▌         | 114/2248 [00:15<04:37,  7.70it/s]
  5%|▌         | 116/2248 [00:15<03:57,  8.96it/s]
  5%|▌         | 117/2248 [00:16<04:09,  8.55it/s]
  5%|▌         | 118/2248 [00:16<04:18,  8.23it/s]
  5%|▌         | 119/2248 [00:16<05:07,  6.93it/s]
  5%|▌         | 120/2248 [00:16<07:14,  4.89it/s]
  5%|▌         | 121/2248 [00:16<06:25,  5.51it/s]
  5%|▌         | 123/2248 [00:17<05:40,  6.24it/s]
  6%|▌         | 125/2248 [00:17<04:11,  8.45it/s]
  6%|▌         | 127/2248 [00:17<06:48,  5.19it/s]
  6%|▌         | 128/2248 [00:18<08:29,  4.16it/s]
  6%|▌         | 130/2248 [00:18<06:53,  5.12it/s]
  6%|▌         | 132/2248 [00:18<05:29,  6.42it/s]
  6%|▌         | 133/2248 [00:19<08:27,  4.17it/s]
  6%|▌         | 135/2248 [00:19<08:06,  4.35it/s]
  6%|▌         | 136/2248 [00:20<08:39,  4.06it/s]
  6%|▌         | 138/2248 [00:20<07:24,  4.75it/s]
  6%|▌         | 139/2248 [00:20<06:58,  5.04it/s]
  6%|▋         | 142/2248 [00:21<06:58,  5.03it/s]
  6%|▋         | 144/2248 [00:21<05:29,  6.38it/s]
  6%|▋         | 145/2248 [00:21<07:02,  4.97it/s]
  7%|▋         | 147/2248 [00:21<05:15,  6.66it/s]
  7%|▋         | 151/2248 [00:22<05:51,  5.97it/s]
  7%|▋         | 154/2248 [00:23<06:14,  5.60it/s]
  7%|▋         | 156/2248 [00:23<08:10,  4.27it/s]
  7%|▋         | 157/2248 [00:24<08:57,  3.89it/s]
  7%|▋         | 158/2248 [00:24<11:48,  2.95it/s]
  7%|▋         | 159/2248 [00:25<15:03,  2.31it/s]
  7%|▋         | 160/2248 [00:26<17:25,  2.00it/s]
  7%|▋         | 162/2248 [00:27<16:24,  2.12it/s]
  7%|▋         | 164/2248 [00:27<11:14,  3.09it/s]
  7%|▋         | 165/2248 [00:28<14:25,  2.41it/s]
  7%|▋         | 166/2248 [00:28<12:41,  2.74it/s]
  7%|▋         | 167/2248 [00:28<13:44,  2.52it/s]
  7%|▋         | 168/2248 [00:29<11:55,  2.91it/s]
  8%|▊         | 169/2248 [00:29<10:50,  3.20it/s]
  8%|▊         | 170/2248 [00:29<09:51,  3.51it/s]
  8%|▊         | 171/2248 [00:29<09:09,  3.78it/s]
  8%|▊         | 172/2248 [00:29<08:37,  4.01it/s]
  8%|▊         | 173/2248 [00:30<08:48,  3.93it/s]
  8%|▊         | 174/2248 [00:30<08:20,  4.15it/s]
  8%|▊         | 176/2248 [00:30<07:29,  4.61it/s]
  8%|▊         | 177/2248 [00:31<07:22,  4.68it/s]
  8%|▊         | 178/2248 [00:31<06:24,  5.38it/s]
  8%|▊         | 179/2248 [00:31<06:17,  5.49it/s]
  8%|▊         | 180/2248 [00:31<06:28,  5.32it/s]
  8%|▊         | 182/2248 [00:31<04:41,  7.33it/s]
  8%|▊         | 183/2248 [00:32<06:39,  5.17it/s]
  8%|▊         | 184/2248 [00:32<06:27,  5.33it/s]
  8%|▊         | 185/2248 [00:32<06:23,  5.37it/s]
  8%|▊         | 186/2248 [00:32<05:50,  5.88it/s]
  8%|▊         | 187/2248 [00:32<07:25,  4.63it/s]
  8%|▊         | 188/2248 [00:32<06:32,  5.25it/s]
  8%|▊         | 189/2248 [00:33<11:00,  3.12it/s]
  8%|▊         | 190/2248 [00:33<08:48,  3.89it/s]
  9%|▊         | 192/2248 [00:33<06:13,  5.51it/s]
  9%|▊         | 193/2248 [00:34<06:22,  5.37it/s]
  9%|▊         | 194/2248 [00:34<05:39,  6.05it/s]
  9%|▊         | 195/2248 [00:34<06:35,  5.19it/s]
  9%|▉         | 197/2248 [00:34<04:57,  6.89it/s]
  9%|▉         | 198/2248 [00:34<04:54,  6.95it/s]
  9%|▉         | 199/2248 [00:35<05:34,  6.13it/s]
  9%|▉         | 200/2248 [00:35<06:23,  5.33it/s]
  9%|▉         | 201/2248 [00:35<05:58,  5.71it/s]
  9%|▉         | 202/2248 [00:35<08:14,  4.14it/s]
  9%|▉         | 203/2248 [00:36<07:58,  4.27it/s]
  9%|▉         | 204/2248 [00:36<07:10,  4.75it/s]
  9%|▉         | 205/2248 [00:36<08:45,  3.89it/s]
  9%|▉         | 206/2248 [00:36<08:10,  4.16it/s]
  9%|▉         | 207/2248 [00:36<07:12,  4.72it/s]
  9%|▉         | 208/2248 [00:37<06:27,  5.26it/s]
  9%|▉         | 209/2248 [00:37<06:12,  5.47it/s]
  9%|▉         | 210/2248 [00:37<09:09,  3.71it/s]
  9%|▉         | 211/2248 [00:38<10:16,  3.30it/s]
  9%|▉         | 212/2248 [00:38<08:27,  4.01it/s]
 10%|▉         | 214/2248 [00:38<06:49,  4.96it/s]
 10%|▉         | 216/2248 [00:38<06:38,  5.11it/s]
 10%|▉         | 218/2248 [00:38<04:50,  6.99it/s]
 10%|▉         | 220/2248 [00:39<03:56,  8.56it/s]
 10%|▉         | 222/2248 [00:39<05:30,  6.13it/s]
 10%|▉         | 224/2248 [00:39<04:21,  7.75it/s]
 10%|█         | 226/2248 [00:39<04:17,  7.84it/s]
 10%|█         | 228/2248 [00:40<05:12,  6.46it/s]
 10%|█         | 230/2248 [00:40<05:15,  6.39it/s]
 10%|█         | 233/2248 [00:40<03:45,  8.93it/s]
 11%|█         | 241/2248 [00:40<01:45, 19.03it/s]
 11%|█         | 245/2248 [00:41<02:20, 14.22it/s]
 11%|█         | 248/2248 [00:41<02:05, 15.99it/s]
 11%|█         | 251/2248 [00:42<03:01, 11.00it/s]
 11%|█▏        | 255/2248 [00:42<02:18, 14.38it/s]
 12%|█▏        | 261/2248 [00:42<01:35, 20.90it/s]
 12%|█▏        | 265/2248 [00:43<05:10,  6.39it/s]
 12%|█▏        | 268/2248 [00:45<06:47,  4.86it/s]
 12%|█▏        | 270/2248 [00:45<07:05,  4.65it/s]
 12%|█▏        | 272/2248 [00:45<06:27,  5.10it/s]
 12%|█▏        | 274/2248 [00:46<07:36,  4.32it/s]
 12%|█▏        | 275/2248 [00:46<07:15,  4.53it/s]
 12%|█▏        | 277/2248 [00:47<07:33,  4.35it/s]
 12%|█▏        | 280/2248 [00:47<07:53,  4.16it/s]
 12%|█▎        | 281/2248 [00:48<07:40,  4.27it/s]
 13%|█▎        | 282/2248 [00:48<07:23,  4.43it/s]
 13%|█▎        | 283/2248 [00:48<08:56,  3.66it/s]
 13%|█▎        | 284/2248 [00:49<12:30,  2.62it/s]
 13%|█▎        | 285/2248 [00:50<13:10,  2.48it/s]
 13%|█▎        | 286/2248 [00:50<16:01,  2.04it/s]
 13%|█▎        | 287/2248 [00:50<13:26,  2.43it/s]
 13%|█▎        | 288/2248 [00:51<14:01,  2.33it/s]
 13%|█▎        | 289/2248 [00:51<12:04,  2.70it/s]
 13%|█▎        | 290/2248 [00:52<15:37,  2.09it/s]
 13%|█▎        | 291/2248 [00:52<13:03,  2.50it/s]
 13%|█▎        | 292/2248 [00:52<11:14,  2.90it/s]
 13%|█▎        | 294/2248 [00:53<09:40,  3.37it/s]
 13%|█▎        | 295/2248 [00:53<08:52,  3.66it/s]
 13%|█▎        | 296/2248 [00:53<09:56,  3.27it/s]
 13%|█▎        | 297/2248 [00:54<10:01,  3.24it/s]
 13%|█▎        | 298/2248 [00:54<12:29,  2.60it/s]
 13%|█▎        | 299/2248 [00:55<12:47,  2.54it/s]
 13%|█▎        | 300/2248 [00:55<10:18,  3.15it/s]
 13%|█▎        | 301/2248 [00:55<11:49,  2.74it/s]
 13%|█▎        | 302/2248 [00:56<14:21,  2.26it/s]
 13%|█▎        | 303/2248 [00:56<14:34,  2.23it/s]
 14%|█▎        | 304/2248 [00:57<11:42,  2.77it/s]
 14%|█▎        | 305/2248 [00:57<12:32,  2.58it/s]
 14%|█▎        | 306/2248 [00:57<12:20,  2.62it/s]
 14%|█▎        | 307/2248 [00:58<11:31,  2.81it/s]
 14%|█▎        | 308/2248 [00:58<11:27,  2.82it/s]
 14%|█▍        | 310/2248 [00:58<07:55,  4.08it/s]
 14%|█▍        | 312/2248 [00:59<07:09,  4.51it/s]
 14%|█▍        | 313/2248 [00:59<06:32,  4.93it/s]
 14%|█▍        | 314/2248 [00:59<08:32,  3.77it/s]
 14%|█▍        | 315/2248 [01:00<09:24,  3.42it/s]
 14%|█▍        | 317/2248 [01:00<06:18,  5.10it/s]
 14%|█▍        | 318/2248 [01:00<05:54,  5.45it/s]
 14%|█▍        | 319/2248 [01:00<07:06,  4.52it/s]
 14%|█▍        | 320/2248 [01:01<08:44,  3.67it/s]
 14%|█▍        | 322/2248 [01:01<06:35,  4.86it/s]
 14%|█▍        | 323/2248 [01:01<07:25,  4.32it/s]
 14%|█▍        | 324/2248 [01:01<06:50,  4.68it/s]
 14%|█▍        | 325/2248 [01:02<06:27,  4.97it/s]
 15%|█▍        | 326/2248 [01:02<08:28,  3.78it/s]
 15%|█▍        | 327/2248 [01:03<12:53,  2.48it/s]
 15%|█▍        | 328/2248 [01:03<16:18,  1.96it/s]
 15%|█▍        | 329/2248 [01:04<13:25,  2.38it/s]
 15%|█▍        | 330/2248 [01:04<13:51,  2.31it/s]
 15%|█▍        | 332/2248 [01:05<13:27,  2.37it/s]
 15%|█▍        | 333/2248 [01:05<13:55,  2.29it/s]
 15%|█▍        | 335/2248 [01:06<10:54,  2.92it/s]
 15%|█▌        | 338/2248 [01:06<06:24,  4.97it/s]
 15%|█▌        | 339/2248 [01:06<06:26,  4.94it/s]
 15%|█▌        | 340/2248 [01:06<06:26,  4.93it/s]
 15%|█▌        | 342/2248 [01:07<06:40,  4.76it/s]
 15%|█▌        | 343/2248 [01:07<07:13,  4.40it/s]
 15%|█▌        | 344/2248 [01:07<06:50,  4.64it/s]
 15%|█▌        | 345/2248 [01:08<11:11,  2.84it/s]
 15%|█▌        | 346/2248 [01:08<10:27,  3.03it/s]
 15%|█▌        | 347/2248 [01:09<09:28,  3.34it/s]
 15%|█▌        | 348/2248 [01:09<10:20,  3.06it/s]
 16%|█▌        | 349/2248 [01:09<09:55,  3.19it/s]
 16%|█▌        | 350/2248 [01:10<10:34,  2.99it/s]
 16%|█▌        | 353/2248 [01:10<07:21,  4.29it/s]
 16%|█▌        | 354/2248 [01:11<08:34,  3.68it/s]
 16%|█▌        | 355/2248 [01:11<09:16,  3.40it/s]
 16%|█▌        | 356/2248 [01:11<09:31,  3.31it/s]
 16%|█▌        | 357/2248 [01:12<09:43,  3.24it/s]
 16%|█▌        | 359/2248 [01:12<06:25,  4.90it/s]
 16%|█▌        | 360/2248 [01:12<06:59,  4.50it/s]
 16%|█▌        | 361/2248 [01:12<08:44,  3.60it/s]
 16%|█▌        | 362/2248 [01:13<07:56,  3.96it/s]
 16%|█▌        | 364/2248 [01:13<06:44,  4.66it/s]
 16%|█▋        | 366/2248 [01:13<05:23,  5.81it/s]
 16%|█▋        | 367/2248 [01:13<05:27,  5.74it/s]
 16%|█▋        | 368/2248 [01:14<07:21,  4.26it/s]
 16%|█▋        | 369/2248 [01:14<06:56,  4.51it/s]
 17%|█▋        | 371/2248 [01:14<06:35,  4.75it/s]
 17%|█▋        | 373/2248 [01:15<08:47,  3.55it/s]
 17%|█▋        | 374/2248 [01:16<10:43,  2.91it/s]
 17%|█▋        | 377/2248 [01:16<07:04,  4.41it/s]
 17%|█▋        | 378/2248 [01:16<08:38,  3.61it/s]
 17%|█▋        | 380/2248 [01:17<06:13,  5.00it/s]
 17%|█▋        | 383/2248 [01:17<04:01,  7.72it/s]
 17%|█▋        | 385/2248 [01:18<07:14,  4.29it/s]
 17%|█▋        | 387/2248 [01:18<07:22,  4.20it/s]
 17%|█▋        | 388/2248 [01:18<07:14,  4.28it/s]
 17%|█▋        | 389/2248 [01:19<07:08,  4.34it/s]
 17%|█▋        | 390/2248 [01:19<10:41,  2.90it/s]
 17%|█▋        | 391/2248 [01:20<13:51,  2.23it/s]
 17%|█▋        | 392/2248 [01:20<12:04,  2.56it/s]
 17%|█▋        | 393/2248 [01:21<14:18,  2.16it/s]
 18%|█▊        | 394/2248 [01:22<17:05,  1.81it/s]
 18%|█▊        | 395/2248 [01:22<13:58,  2.21it/s]
 18%|█▊        | 398/2248 [01:22<08:23,  3.67it/s]
 18%|█▊        | 402/2248 [01:23<06:11,  4.97it/s]
 18%|█▊        | 403/2248 [01:23<06:11,  4.96it/s]
 18%|█▊        | 405/2248 [01:23<05:59,  5.12it/s]
 18%|█▊        | 408/2248 [01:24<05:27,  5.61it/s]
 18%|█▊        | 410/2248 [01:24<06:01,  5.08it/s]
 18%|█▊        | 412/2248 [01:25<06:19,  4.84it/s]
 18%|█▊        | 414/2248 [01:25<05:00,  6.11it/s]
 19%|█▊        | 417/2248 [01:25<04:58,  6.13it/s]
 19%|█▊        | 419/2248 [01:26<04:12,  7.24it/s]
 19%|█▊        | 420/2248 [01:26<04:26,  6.85it/s]
 19%|█▊        | 421/2248 [01:26<05:06,  5.96it/s]
 19%|█▉        | 423/2248 [01:26<03:57,  7.67it/s]
 19%|█▉        | 425/2248 [01:27<04:21,  6.98it/s]
 19%|█▉        | 427/2248 [01:27<04:05,  7.40it/s]
 19%|█▉        | 429/2248 [01:27<03:23,  8.93it/s]
 19%|█▉        | 431/2248 [01:27<02:51, 10.59it/s]
 19%|█▉        | 436/2248 [01:28<04:07,  7.33it/s]
 19%|█▉        | 438/2248 [01:29<06:01,  5.01it/s]
 20%|█▉        | 439/2248 [01:29<08:28,  3.56it/s]
 20%|█▉        | 440/2248 [01:30<10:52,  2.77it/s]
 20%|█▉        | 441/2248 [01:30<10:00,  3.01it/s]
 20%|█▉        | 443/2248 [01:31<09:15,  3.25it/s]
 20%|█▉        | 444/2248 [01:31<08:53,  3.38it/s]
 20%|█▉        | 445/2248 [01:31<08:05,  3.71it/s]
 20%|█▉        | 446/2248 [01:32<10:17,  2.92it/s]
 20%|█▉        | 449/2248 [01:32<05:41,  5.27it/s]
 20%|██        | 450/2248 [01:32<06:28,  4.62it/s]
 20%|██        | 452/2248 [01:33<04:46,  6.28it/s]
 20%|██        | 454/2248 [01:33<06:18,  4.74it/s]
 20%|██        | 456/2248 [01:33<05:27,  5.47it/s]
 20%|██        | 457/2248 [01:34<06:04,  4.91it/s]
 20%|██        | 459/2248 [01:34<05:12,  5.73it/s]
 20%|██        | 460/2248 [01:34<06:43,  4.43it/s]
 21%|██        | 461/2248 [01:35<07:50,  3.80it/s]
 21%|██        | 462/2248 [01:35<07:16,  4.10it/s]
 21%|██        | 463/2248 [01:35<08:13,  3.62it/s]
 21%|██        | 464/2248 [01:36<11:56,  2.49it/s]
 21%|██        | 467/2248 [01:36<06:59,  4.25it/s]
 21%|██        | 469/2248 [01:37<05:51,  5.06it/s]
 21%|██        | 471/2248 [01:37<07:45,  3.81it/s]
 21%|██        | 472/2248 [01:38<10:28,  2.83it/s]
 21%|██        | 473/2248 [01:39<12:57,  2.28it/s]
 21%|██        | 474/2248 [01:39<13:08,  2.25it/s]
 21%|██        | 475/2248 [01:40<13:12,  2.24it/s]
 21%|██        | 477/2248 [01:40<10:56,  2.70it/s]
 21%|██▏       | 478/2248 [01:41<10:22,  2.84it/s]
 21%|██▏       | 479/2248 [01:41<11:34,  2.55it/s]
 21%|██▏       | 480/2248 [01:41<11:32,  2.55it/s]
 21%|██▏       | 481/2248 [01:42<11:01,  2.67it/s]
 21%|██▏       | 482/2248 [01:42<11:44,  2.51it/s]
 21%|██▏       | 483/2248 [01:42<09:14,  3.18it/s]
 22%|██▏       | 485/2248 [01:43<06:32,  4.49it/s]
 22%|██▏       | 486/2248 [01:43<05:56,  4.94it/s]
 22%|██▏       | 487/2248 [01:43<06:20,  4.63it/s]
 22%|██▏       | 490/2248 [01:43<03:49,  7.65it/s]
 22%|██▏       | 492/2248 [01:43<03:22,  8.69it/s]
 22%|██▏       | 494/2248 [01:43<03:00,  9.69it/s]
 22%|██▏       | 496/2248 [01:44<03:14,  9.02it/s]
 22%|██▏       | 498/2248 [01:44<03:51,  7.55it/s]
 22%|██▏       | 499/2248 [01:44<04:00,  7.26it/s]
 22%|██▏       | 500/2248 [01:44<03:49,  7.61it/s]
 22%|██▏       | 502/2248 [01:45<05:18,  5.48it/s]
 22%|██▏       | 503/2248 [01:45<05:23,  5.39it/s]
 23%|██▎       | 506/2248 [01:46<04:49,  6.01it/s]
 23%|██▎       | 508/2248 [01:46<04:36,  6.29it/s]
 23%|██▎       | 509/2248 [01:46<07:17,  3.98it/s]
 23%|██▎       | 510/2248 [01:47<07:03,  4.10it/s]
 23%|██▎       | 512/2248 [01:47<05:40,  5.10it/s]
 23%|██▎       | 513/2248 [01:47<05:36,  5.16it/s]
 23%|██▎       | 514/2248 [01:48<09:03,  3.19it/s]
 23%|██▎       | 515/2248 [01:49<12:01,  2.40it/s]
 23%|██▎       | 516/2248 [01:49<10:25,  2.77it/s]
 23%|██▎       | 517/2248 [01:49<09:05,  3.17it/s]
 23%|██▎       | 518/2248 [01:49<08:19,  3.47it/s]
 23%|██▎       | 519/2248 [01:49<07:46,  3.70it/s]
 23%|██▎       | 520/2248 [01:50<08:16,  3.48it/s]
 23%|██▎       | 521/2248 [01:50<06:53,  4.18it/s]
 23%|██▎       | 523/2248 [01:50<07:51,  3.66it/s]
 23%|██▎       | 526/2248 [01:51<04:32,  6.32it/s]
 23%|██▎       | 528/2248 [01:51<04:11,  6.84it/s]
 24%|██▎       | 532/2248 [01:51<02:33, 11.18it/s]
 24%|██▍       | 534/2248 [01:51<02:51, 10.02it/s]
 24%|██▍       | 536/2248 [01:52<03:57,  7.19it/s]
 24%|██▍       | 538/2248 [01:52<04:54,  5.80it/s]
 24%|██▍       | 541/2248 [01:52<03:58,  7.16it/s]
 24%|██▍       | 544/2248 [01:53<03:37,  7.84it/s]
 24%|██▍       | 547/2248 [01:53<02:46, 10.25it/s]
 25%|██▍       | 554/2248 [01:53<02:30, 11.29it/s]
 25%|██▍       | 556/2248 [01:54<02:19, 12.17it/s]
 25%|██▌       | 562/2248 [01:54<01:48, 15.52it/s]
 25%|██▌       | 564/2248 [01:54<02:02, 13.74it/s]
 25%|██▌       | 567/2248 [01:54<01:48, 15.52it/s]
 25%|██▌       | 571/2248 [01:55<03:04,  9.08it/s]
 25%|██▌       | 573/2248 [01:55<03:35,  7.78it/s]
 26%|██▌       | 575/2248 [01:56<05:23,  5.17it/s]
 26%|██▌       | 576/2248 [01:57<06:33,  4.25it/s]
 26%|██▌       | 579/2248 [01:58<07:02,  3.95it/s]
 26%|██▌       | 581/2248 [01:58<08:07,  3.42it/s]
 26%|██▌       | 582/2248 [01:59<10:18,  2.69it/s]
 26%|██▌       | 583/2248 [01:59<09:25,  2.94it/s]
 26%|██▌       | 584/2248 [02:00<11:38,  2.38it/s]
 26%|██▌       | 585/2248 [02:00<10:27,  2.65it/s]
 26%|██▌       | 586/2248 [02:01<11:10,  2.48it/s]
 26%|██▌       | 588/2248 [02:01<10:16,  2.69it/s]
 26%|██▌       | 589/2248 [02:02<08:55,  3.10it/s]
 26%|██▋       | 591/2248 [02:02<05:58,  4.63it/s]
 26%|██▋       | 592/2248 [02:02<07:43,  3.57it/s]
 26%|██▋       | 594/2248 [02:02<05:20,  5.15it/s]
 26%|██▋       | 595/2248 [02:03<05:57,  4.62it/s]
 27%|██▋       | 598/2248 [02:03<03:41,  7.46it/s]
 27%|██▋       | 600/2248 [02:03<04:15,  6.46it/s]
 27%|██▋       | 602/2248 [02:03<03:21,  8.16it/s]
 27%|██▋       | 604/2248 [02:04<04:29,  6.10it/s]
 27%|██▋       | 606/2248 [02:05<06:36,  4.14it/s]
 27%|██▋       | 607/2248 [02:05<07:28,  3.66it/s]
 27%|██▋       | 608/2248 [02:06<08:27,  3.23it/s]
 27%|██▋       | 609/2248 [02:06<09:50,  2.77it/s]
 27%|██▋       | 610/2248 [02:07<10:19,  2.64it/s]
 27%|██▋       | 612/2248 [02:07<06:40,  4.08it/s]
 27%|██▋       | 613/2248 [02:07<06:49,  3.99it/s]
 27%|██▋       | 616/2248 [02:07<05:00,  5.43it/s]
 27%|██▋       | 617/2248 [02:07<04:37,  5.87it/s]
 28%|██▊       | 619/2248 [02:07<03:34,  7.59it/s]
 28%|██▊       | 621/2248 [02:08<03:24,  7.96it/s]
 28%|██▊       | 622/2248 [02:08<03:42,  7.29it/s]
 28%|██▊       | 624/2248 [02:08<05:01,  5.39it/s]
 28%|██▊       | 625/2248 [02:09<05:46,  4.69it/s]
 28%|██▊       | 627/2248 [02:09<04:11,  6.44it/s]
 28%|██▊       | 628/2248 [02:09<04:17,  6.28it/s]
 28%|██▊       | 630/2248 [02:09<03:29,  7.71it/s]
 28%|██▊       | 631/2248 [02:09<04:22,  6.15it/s]
 28%|██▊       | 634/2248 [02:10<02:45,  9.75it/s]
 28%|██▊       | 636/2248 [02:10<04:31,  5.95it/s]
 28%|██▊       | 638/2248 [02:10<03:45,  7.14it/s]
 29%|██▊       | 641/2248 [02:11<03:28,  7.71it/s]
 29%|██▊       | 643/2248 [02:11<02:54,  9.18it/s]
 29%|██▊       | 645/2248 [02:11<03:38,  7.32it/s]
 29%|██▉       | 647/2248 [02:11<03:01,  8.80it/s]
 29%|██▉       | 651/2248 [02:12<03:17,  8.10it/s]
 29%|██▉       | 653/2248 [02:12<03:54,  6.79it/s]
 29%|██▉       | 655/2248 [02:13<03:57,  6.70it/s]
 29%|██▉       | 658/2248 [02:13<03:53,  6.80it/s]
 29%|██▉       | 660/2248 [02:13<04:09,  6.38it/s]
 29%|██▉       | 661/2248 [02:14<04:15,  6.21it/s]
 29%|██▉       | 663/2248 [02:14<04:21,  6.07it/s]
 30%|██▉       | 664/2248 [02:14<05:29,  4.81it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 300.88it/s]

[[np.int64(0), False, 7], [np.int64(1), False, 13], [np.int64(2), False, 13], [np.int64(3), False, 9], [np.int64(4), False, 8], [np.int64(5), False, 0], [np.int64(6), False, 8], [np.int64(7), False, 12], [np.int64(8), False, 7], [np.int64(10), False, 13], [np.int64(11), False, 0]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.1032, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0753, device='cuda:0', grad_fn=<MulBackward0>)

 67%|██████▋   | 201/300 [28:31<3:56:35, 143.39s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 67%|██████▋   | 202/300 [28:31<2:44:00, 100.42s/it]

tensor(12.1002, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0220, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1310, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0976, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1790, device='cuda:0', grad_fn=<MulBackward0>)

 68%|██████▊   | 205/300 [28:31<54:39, 34.52s/it]

tensor(12.0958, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2456, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0951, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3014, device='cuda:0', grad_fn=<MulBackward0>)

 69%|██████▉   | 207/300 [28:32<26:18, 16.97s/it]

tensor(12.0955, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0241, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3297, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0967, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3412, device='cuda:0', grad_fn=<MulBackward0>)

 70%|██████▉   | 209/300 [28:32<12:42,  8.38s/it]

tensor(12.0977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3402, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0987, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3458, device='cuda:0', grad_fn=<MulBackward0>)

 70%|███████   | 211/300 [28:32<06:10,  4.16s/it]

tensor(12.0989, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0246, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3669, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0986, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3921, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████   | 213/300 [28:32<03:02,  2.10s/it]

tensor(12.0975, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4180, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0960, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4326, device='cuda:0', grad_fn=<MulBackward0>)

 71%|███████▏  | 214/300 [28:33<02:09,  1.51s/it]

tensor(12.0940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4445, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0913, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0240, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4518, device='cuda:0', grad_fn=<MulBackward0>)

 72%|███████▏  | 217/300 [28:33<00:49,  1.68it/s]

tensor(12.0881, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0237, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4647, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0845, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0236, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4725, device='cuda:0', grad_fn=<MulBackward0>)

 73%|███████▎  | 219/300 [28:33<00:28,  2.86it/s]

tensor(12.0816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4771, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0795, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0230, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4786, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▎  | 221/300 [28:33<00:18,  4.32it/s]

tensor(12.0778, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0229, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4880, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0763, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4868, device='cuda:0', grad_fn=<MulBackward0>)

 74%|███████▍  | 223/300 [28:34<00:13,  5.79it/s]

tensor(12.0748, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0223, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4924, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0733, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4959, device='cuda:0', grad_fn=<MulBackward0>)

 75%|███████▌  | 225/300 [28:34<00:10,  6.94it/s]

tensor(12.0711, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0221, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4994, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0688, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5046, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▌  | 227/300 [28:34<00:09,  7.72it/s]

tensor(12.0664, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5139, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0636, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5210, device='cuda:0', grad_fn=<MulBackward0>)

 76%|███████▋  | 229/300 [28:34<00:08,  8.15it/s]

tensor(12.0612, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5250, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0589, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5292, device='cuda:0', grad_fn=<MulBackward0>)

 77%|███████▋  | 231/300 [28:35<00:08,  8.35it/s]

tensor(12.0567, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5315, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0550, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5321, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 233/300 [28:35<00:07,  8.50it/s]

tensor(12.0531, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5353, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0514, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5355, device='cuda:0', grad_fn=<MulBackward0>)

 78%|███████▊  | 235/300 [28:35<00:07,  8.54it/s]

tensor(12.0498, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5390, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0479, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5402, device='cuda:0', grad_fn=<MulBackward0>)

 79%|███████▉  | 237/300 [28:35<00:07,  8.65it/s]

tensor(12.0461, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5413, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0442, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5428, device='cuda:0', grad_fn=<MulBackward0>)

 80%|███████▉  | 239/300 [28:35<00:07,  8.59it/s]

tensor(12.0427, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0216, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5428, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0409, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5440, device='cuda:0', grad_fn=<MulBackward0>)

 80%|████████  | 241/300 [28:36<00:06,  8.65it/s]

tensor(12.0392, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0214, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5443, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0374, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5464, device='cuda:0', grad_fn=<MulBackward0>)

 81%|████████  | 243/300 [28:36<00:06,  8.62it/s]

tensor(12.0355, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5483, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0339, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5479, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 245/300 [28:36<00:06,  8.62it/s]

tensor(12.0322, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5467, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0308, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5492, device='cuda:0', grad_fn=<MulBackward0>)

 82%|████████▏ | 247/300 [28:36<00:06,  8.59it/s]

tensor(12.0290, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5529, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0212, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5549, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 249/300 [28:37<00:05,  8.59it/s]

tensor(12.0262, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5564, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0248, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5576, device='cuda:0', grad_fn=<MulBackward0>)

 83%|████████▎ | 250/300 [28:37<00:05,  8.53it/s]

tensor(12.0234, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.5579, device='cuda:0', grad_fn=<MulBackward0>)
updating clustring...
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor([ 84, 207, 219, 555, 141, 110,  51, 212,  70, 209, 109, 125, 119,  37])

  0%|          | 0/2248 [00:00<?, ?it/s]
  0%|          | 3/2248 [00:00<01:21, 27.69it/s]
  0%|          | 9/2248 [00:00<00:50, 44.71it/s]
  1%|          | 14/2248 [00:00<00:49, 44.74it/s]
  1%|          | 21/2248 [00:00<00:41, 53.04it/s]
  1%|▏         | 30/2248 [00:00<00:34, 63.60it/s]
  2%|▏         | 37/2248 [00:00<00:35, 62.60it/s]
  2%|▏         | 44/2248 [00:00<00:43, 50.13it/s]
  2%|▏         | 50/2248 [00:01<00:51, 43.01it/s]
  2%|▏         | 55/2248 [00:01<00:50, 43.77it/s]
  3%|▎         | 62/2248 [00:01<00:46, 46.83it/s]
  3%|▎         | 67/2248 [00:01<00:53, 40.74it/s]
  3%|▎         | 72/2248 [00:01<00:57, 37.66it/s]
  3%|▎         | 76/2248 [00:02<03:08, 11.51it/s]
  4%|▎         | 79/2248 [00:02<02:47, 12.96it/s]
  4%|▎         | 84/2248 [00:02<02:09, 16.72it/s]
  4%|▍         | 88/2248 [00:04<04:13,  8.52it/s]
  4%|▍         | 94/2248 [00:04<02:53, 12.38it/s]
  4%|▍         | 98/2248 [00:05<04:08,  8.66it/s]
  4%|▍         | 101/2248 [00:05<04:13,  8.46it/s]
  5%|▍         | 103/2248 [00:05<03:53,  9.19it/s]
  5%|▍         | 105/2248 [00:06<05:09,  6.92it/s]
  5%|▍         | 107/2248 [00:06<04:28,  7.97it/s]
  5%|▍         | 111/2248 [00:06<03:07, 11.39it/s]
  5%|▌         | 117/2248 [00:06<02:00, 17.69it/s]
  5%|▌         | 121/2248 [00:07<04:10,  8.49it/s]
  6%|▌         | 124/2248 [00:07<03:27, 10.23it/s]
  6%|▌         | 127/2248 [00:08<06:32,  5.41it/s]
  6%|▌         | 129/2248 [00:09<07:18,  4.83it/s]
  6%|▌         | 131/2248 [00:09<06:10,  5.71it/s]
  6%|▌         | 133/2248 [00:10<06:19,  5.57it/s]
  6%|▌         | 135/2248 [00:10<06:57,  5.07it/s]
  6%|▌         | 136/2248 [00:11<10:30,  3.35it/s]
  6%|▌         | 138/2248 [00:12<13:15,  2.65it/s]
  6%|▌         | 140/2248 [00:12<09:59,  3.52it/s]
  6%|▋         | 142/2248 [00:13<12:10,  2.88it/s]
  6%|▋         | 144/2248 [00:13<09:04,  3.86it/s]
  6%|▋         | 145/2248 [00:14<13:34,  2.58it/s]
  7%|▋         | 147/2248 [00:14<09:42,  3.60it/s]
  7%|▋         | 151/2248 [00:15<07:29,  4.66it/s]
  7%|▋         | 155/2248 [00:15<04:47,  7.28it/s]
  7%|▋         | 157/2248 [00:16<08:20,  4.18it/s]
  7%|▋         | 159/2248 [00:17<10:56,  3.18it/s]
  7%|▋         | 160/2248 [00:18<12:37,  2.76it/s]
  7%|▋         | 162/2248 [00:18<11:12,  3.10it/s]
  7%|▋         | 165/2248 [00:19<09:43,  3.57it/s]
  7%|▋         | 168/2248 [00:19<06:47,  5.11it/s]
  8%|▊         | 170/2248 [00:20<08:11,  4.23it/s]
  8%|▊         | 173/2248 [00:20<07:41,  4.49it/s]
  8%|▊         | 175/2248 [00:21<06:25,  5.37it/s]
  8%|▊         | 176/2248 [00:22<10:35,  3.26it/s]
  8%|▊         | 178/2248 [00:23<12:44,  2.71it/s]
  8%|▊         | 179/2248 [00:23<11:08,  3.09it/s]
  8%|▊         | 181/2248 [00:23<07:58,  4.32it/s]
  8%|▊         | 183/2248 [00:24<11:09,  3.08it/s]
  8%|▊         | 185/2248 [00:24<08:22,  4.10it/s]
  8%|▊         | 187/2248 [00:24<08:14,  4.17it/s]
  8%|▊         | 189/2248 [00:25<06:22,  5.38it/s]
  8%|▊         | 191/2248 [00:25<06:41,  5.12it/s]
  9%|▊         | 193/2248 [00:25<05:17,  6.48it/s]
  9%|▊         | 195/2248 [00:26<06:47,  5.04it/s]
  9%|▉         | 197/2248 [00:26<05:25,  6.31it/s]
  9%|▉         | 201/2248 [00:26<03:20, 10.23it/s]
  9%|▉         | 203/2248 [00:27<06:47,  5.02it/s]
  9%|▉         | 205/2248 [00:28<09:21,  3.64it/s]
  9%|▉         | 207/2248 [00:29<11:19,  3.00it/s]
  9%|▉         | 209/2248 [00:30<12:49,  2.65it/s]
  9%|▉         | 210/2248 [00:31<16:12,  2.10it/s]
  9%|▉         | 211/2248 [00:32<19:16,  1.76it/s]
  9%|▉         | 212/2248 [00:33<22:23,  1.52it/s]
 10%|▉         | 214/2248 [00:33<14:38,  2.31it/s]
 10%|▉         | 216/2248 [00:33<10:11,  3.33it/s]
 10%|▉         | 221/2248 [00:33<04:56,  6.84it/s]
 10%|█         | 227/2248 [00:33<02:47, 12.04it/s]
 10%|█         | 234/2248 [00:33<01:45, 19.09it/s]
 11%|█         | 241/2248 [00:34<01:16, 26.35it/s]
 11%|█         | 249/2248 [00:34<00:56, 35.26it/s]
 11%|█▏        | 255/2248 [00:34<00:49, 40.04it/s]
 12%|█▏        | 262/2248 [00:35<02:12, 15.01it/s]
 12%|█▏        | 267/2248 [00:38<06:36,  5.00it/s]
 12%|█▏        | 271/2248 [00:38<05:19,  6.20it/s]
 12%|█▏        | 275/2248 [00:39<06:00,  5.48it/s]
 12%|█▏        | 278/2248 [00:40<06:38,  4.95it/s]
 12%|█▏        | 280/2248 [00:41<07:59,  4.10it/s]
 13%|█▎        | 282/2248 [00:41<08:21,  3.92it/s]
 13%|█▎        | 284/2248 [00:41<06:55,  4.73it/s]
 13%|█▎        | 286/2248 [00:41<05:42,  5.73it/s]
 13%|█▎        | 288/2248 [00:42<06:11,  5.28it/s]
 13%|█▎        | 290/2248 [00:43<07:14,  4.51it/s]
 13%|█▎        | 291/2248 [00:43<07:59,  4.08it/s]
 13%|█▎        | 294/2248 [00:43<05:14,  6.22it/s]
 13%|█▎        | 298/2248 [00:43<04:12,  7.71it/s]
 13%|█▎        | 300/2248 [00:44<06:08,  5.28it/s]
 13%|█▎        | 302/2248 [00:45<07:24,  4.38it/s]
 13%|█▎        | 303/2248 [00:45<07:51,  4.12it/s]
 14%|█▎        | 304/2248 [00:46<08:44,  3.71it/s]
 14%|█▎        | 306/2248 [00:46<07:00,  4.62it/s]
 14%|█▎        | 307/2248 [00:46<09:07,  3.55it/s]
 14%|█▎        | 308/2248 [00:47<10:50,  2.98it/s]
 14%|█▎        | 309/2248 [00:48<14:30,  2.23it/s]
 14%|█▍        | 311/2248 [00:48<09:18,  3.47it/s]
 14%|█▍        | 312/2248 [00:48<11:49,  2.73it/s]
 14%|█▍        | 313/2248 [00:49<12:35,  2.56it/s]
 14%|█▍        | 314/2248 [00:49<12:53,  2.50it/s]
 14%|█▍        | 315/2248 [00:50<12:05,  2.66it/s]
 14%|█▍        | 318/2248 [00:50<06:33,  4.90it/s]
 14%|█▍        | 320/2248 [00:50<05:58,  5.38it/s]
 14%|█▍        | 322/2248 [00:51<06:20,  5.06it/s]
 14%|█▍        | 323/2248 [00:51<08:41,  3.69it/s]
 14%|█▍        | 325/2248 [00:51<06:45,  4.74it/s]
 15%|█▍        | 327/2248 [00:52<06:51,  4.67it/s]
 15%|█▍        | 328/2248 [00:53<10:14,  3.13it/s]
 15%|█▍        | 330/2248 [00:53<07:15,  4.40it/s]
 15%|█▍        | 332/2248 [00:53<06:55,  4.61it/s]
 15%|█▍        | 334/2248 [00:53<05:33,  5.74it/s]
 15%|█▌        | 339/2248 [00:54<06:00,  5.30it/s]
 15%|█▌        | 341/2248 [00:54<05:02,  6.31it/s]
 15%|█▌        | 343/2248 [00:55<07:35,  4.18it/s]
 15%|█▌        | 344/2248 [00:56<11:05,  2.86it/s]
 15%|█▌        | 345/2248 [00:57<14:28,  2.19it/s]
 15%|█▌        | 346/2248 [00:58<17:26,  1.82it/s]
 15%|█▌        | 347/2248 [00:59<20:46,  1.53it/s]
 15%|█▌        | 348/2248 [01:00<23:14,  1.36it/s]
 16%|█▌        | 349/2248 [01:01<21:25,  1.48it/s]
 16%|█▌        | 350/2248 [01:02<24:18,  1.30it/s]
 16%|█▌        | 352/2248 [01:02<14:35,  2.17it/s]
 16%|█▌        | 353/2248 [01:03<17:40,  1.79it/s]
 16%|█▌        | 354/2248 [01:04<20:16,  1.56it/s]
 16%|█▌        | 356/2248 [01:04<17:57,  1.76it/s]
 16%|█▌        | 358/2248 [01:05<12:07,  2.60it/s]
 16%|█▌        | 362/2248 [01:06<09:57,  3.16it/s]
 16%|█▌        | 365/2248 [01:06<06:51,  4.57it/s]
 16%|█▋        | 367/2248 [01:08<12:04,  2.60it/s]
 17%|█▋        | 371/2248 [01:08<10:05,  3.10it/s]
 17%|█▋        | 373/2248 [01:09<10:12,  3.06it/s]
 17%|█▋        | 375/2248 [01:09<08:03,  3.87it/s]
 17%|█▋        | 377/2248 [01:10<08:43,  3.57it/s]
 17%|█▋        | 380/2248 [01:10<05:59,  5.20it/s]
 17%|█▋        | 383/2248 [01:10<04:20,  7.17it/s]
 17%|█▋        | 385/2248 [01:11<07:31,  4.12it/s]
 17%|█▋        | 388/2248 [01:12<06:27,  4.80it/s]
 17%|█▋        | 390/2248 [01:12<06:39,  4.65it/s]
 17%|█▋        | 392/2248 [01:13<07:50,  3.95it/s]
 17%|█▋        | 393/2248 [01:14<10:44,  2.88it/s]
 18%|█▊        | 394/2248 [01:15<13:28,  2.29it/s]
 18%|█▊        | 395/2248 [01:16<16:53,  1.83it/s]
 18%|█▊        | 397/2248 [01:16<11:10,  2.76it/s]
 18%|█▊        | 402/2248 [01:16<05:08,  5.98it/s]
 18%|█▊        | 409/2248 [01:16<02:38, 11.58it/s]
 19%|█▊        | 416/2248 [01:16<01:41, 18.04it/s]
 19%|█▉        | 424/2248 [01:16<01:09, 26.09it/s]
 19%|█▉        | 430/2248 [01:16<00:58, 30.93it/s]
 19%|█▉        | 436/2248 [01:17<02:19, 12.94it/s]
 20%|█▉        | 440/2248 [01:20<06:52,  4.39it/s]
 20%|█▉        | 443/2248 [01:21<07:36,  3.95it/s]
 20%|█▉        | 446/2248 [01:22<08:06,  3.71it/s]
 20%|█▉        | 449/2248 [01:22<06:30,  4.61it/s]
 20%|██        | 451/2248 [01:23<07:36,  3.93it/s]
 20%|██        | 453/2248 [01:24<08:49,  3.39it/s]
 20%|██        | 455/2248 [01:25<08:45,  3.41it/s]
 20%|██        | 457/2248 [01:25<08:15,  3.61it/s]
 20%|██        | 459/2248 [01:26<07:42,  3.87it/s]
 20%|██        | 460/2248 [01:26<08:11,  3.64it/s]
 21%|██        | 462/2248 [01:26<06:15,  4.76it/s]
 21%|██        | 463/2248 [01:26<06:52,  4.32it/s]
 21%|██        | 464/2248 [01:27<08:14,  3.61it/s]
 21%|██        | 466/2248 [01:27<05:46,  5.14it/s]
 21%|██        | 471/2248 [01:28<06:01,  4.92it/s]
 21%|██        | 472/2248 [01:29<09:06,  3.25it/s]
 21%|██        | 473/2248 [01:30<12:22,  2.39it/s]
 21%|██        | 475/2248 [01:31<13:01,  2.27it/s]
 21%|██        | 476/2248 [01:32<15:34,  1.90it/s]
 21%|██        | 477/2248 [01:33<18:22,  1.61it/s]
 21%|██▏       | 478/2248 [01:34<20:07,  1.47it/s]
 21%|██▏       | 479/2248 [01:35<21:05,  1.40it/s]
 21%|██▏       | 480/2248 [01:35<22:32,  1.31it/s]
 21%|██▏       | 481/2248 [01:36<23:31,  1.25it/s]
 21%|██▏       | 482/2248 [01:37<24:40,  1.19it/s]
 22%|██▏       | 485/2248 [01:37<11:46,  2.50it/s]
 22%|██▏       | 486/2248 [01:38<14:29,  2.03it/s]
 22%|██▏       | 487/2248 [01:39<13:56,  2.11it/s]
 22%|██▏       | 488/2248 [01:39<14:09,  2.07it/s]
 22%|██▏       | 492/2248 [01:39<06:26,  4.54it/s]
 22%|██▏       | 495/2248 [01:40<04:54,  5.94it/s]
 22%|██▏       | 498/2248 [01:40<03:36,  8.08it/s]
 22%|██▏       | 500/2248 [01:40<04:21,  6.69it/s]
 22%|██▏       | 502/2248 [01:40<03:36,  8.08it/s]
 22%|██▏       | 504/2248 [01:40<03:33,  8.17it/s]
 23%|██▎       | 506/2248 [01:41<03:04,  9.42it/s]
 23%|██▎       | 509/2248 [01:41<03:40,  7.87it/s]
 23%|██▎       | 512/2248 [01:41<02:48, 10.30it/s]
 23%|██▎       | 514/2248 [01:42<05:54,  4.89it/s]
 23%|██▎       | 516/2248 [01:43<06:47,  4.25it/s]
 23%|██▎       | 517/2248 [01:43<07:27,  3.86it/s]
 23%|██▎       | 519/2248 [01:44<07:28,  3.85it/s]
 23%|██▎       | 521/2248 [01:44<05:40,  5.08it/s]
 23%|██▎       | 523/2248 [01:44<04:26,  6.47it/s]
 24%|██▎       | 531/2248 [01:44<01:51, 15.34it/s]
 24%|██▍       | 538/2248 [01:44<01:14, 23.09it/s]
 24%|██▍       | 546/2248 [01:44<00:54, 30.95it/s]
 25%|██▍       | 551/2248 [01:45<00:52, 32.22it/s]
 25%|██▍       | 558/2248 [01:45<00:43, 38.87it/s]
 25%|██▌       | 563/2248 [01:45<00:42, 40.09it/s]
 25%|██▌       | 570/2248 [01:45<00:37, 45.01it/s]
 26%|██▌       | 576/2248 [01:49<06:00,  4.63it/s]
 26%|██▌       | 580/2248 [01:49<05:33,  5.00it/s]
 26%|██▌       | 583/2248 [01:51<06:28,  4.28it/s]
 26%|██▌       | 585/2248 [01:51<06:43,  4.12it/s]
 26%|██▌       | 587/2248 [01:52<07:31,  3.68it/s]
 26%|██▌       | 589/2248 [01:53<07:37,  3.63it/s]
 26%|██▋       | 591/2248 [01:53<06:13,  4.43it/s]
 26%|██▋       | 593/2248 [01:53<05:49,  4.73it/s]
 26%|██▋       | 595/2248 [01:53<04:43,  5.82it/s]
 27%|██▋       | 599/2248 [01:54<04:56,  5.56it/s]
 27%|██▋       | 601/2248 [01:54<04:56,  5.56it/s]
 27%|██▋       | 603/2248 [01:55<05:58,  4.58it/s]
 27%|██▋       | 604/2248 [01:55<06:16,  4.37it/s]
 27%|██▋       | 605/2248 [01:56<08:01,  3.41it/s]
 27%|██▋       | 606/2248 [01:56<08:48,  3.10it/s]
 27%|██▋       | 607/2248 [01:57<09:29,  2.88it/s]
 27%|██▋       | 608/2248 [01:57<10:22,  2.63it/s]
 27%|██▋       | 609/2248 [01:57<09:15,  2.95it/s]
 27%|██▋       | 610/2248 [01:58<08:49,  3.09it/s]
 27%|██▋       | 612/2248 [01:58<05:36,  4.86it/s]
 27%|██▋       | 615/2248 [01:58<03:23,  8.03it/s]
 28%|██▊       | 622/2248 [01:58<01:32, 17.53it/s]
 28%|██▊       | 629/2248 [01:58<01:00, 26.94it/s]
 28%|██▊       | 635/2248 [01:58<00:48, 33.44it/s]
 29%|██▊       | 641/2248 [01:58<00:40, 39.40it/s]
 29%|██▉       | 648/2248 [01:58<00:34, 46.26it/s]
 29%|██▉       | 654/2248 [02:00<02:30, 10.61it/s]
 29%|██▉       | 658/2248 [02:01<03:34,  7.42it/s]
 29%|██▉       | 661/2248 [02:03<05:28,  4.84it/s]
 30%|██▉       | 664/2248 [02:03<05:41,  4.64it/s]
 30%|██▉       | 667/2248 [02:04<05:29,  4.80it/s]
 30%|██▉       | 670/2248 [02:04<05:28,  4.80it/s]
 30%|██▉       | 672/2248 [02:05<04:45,  5.53it/s]
 30%|██▉       | 674/2248 [02:05<04:01,  6.51it/s]
 30%|███       | 677/2248 [02:05<04:44,  5.53it/s]
 30%|███       | 679/2248 [02:06<03:58,  6.58it/s]
 30%|███       | 682/2248 [02:07<05:36,  4.66it/s]
 30%|███       | 683/2248 [02:07<06:42,  3.89it/s]
 30%|███       | 684/2248 [02:08<08:35,  3.04it/s]
 30%|███       | 685/2248 [02:09<11:25,  2.28it/s]
 31%|███       | 686/2248 [02:09<12:15,  2.12it/s]
 31%|███       | 687/2248 [02:09<10:00,  2.60it/s]
 31%|███       | 688/2248 [02:10<13:23,  1.94it/s]
 31%|███       | 691/2248 [02:11<11:01,  2.35it/s]
 31%|███       | 692/2248 [02:12<13:39,  1.90it/s]
 31%|███       | 695/2248 [02:13<11:27,  2.26it/s]
 31%|███       | 697/2248 [02:13<08:26,  3.06it/s]
 31%|███       | 698/2248 [02:14<11:19,  2.28it/s]
 31%|███       | 699/2248 [02:15<13:58,  1.85it/s]
 31%|███       | 702/2248 [02:16<11:25,  2.25it/s]
 31%|███▏      | 704/2248 [02:17<11:59,  2.15it/s]
 31%|███▏      | 706/2248 [02:17<08:45,  2.93it/s]
 32%|███▏      | 709/2248 [02:18<08:36,  2.98it/s]
 32%|███▏      | 711/2248 [02:19<09:47,  2.61it/s]
 32%|███▏      | 712/2248 [02:20<12:23,  2.07it/s]
 32%|███▏      | 713/2248 [02:21<14:38,  1.75it/s]
 32%|███▏      | 715/2248 [02:22<10:04,  2.54it/s]
 32%|███▏      | 716/2248 [02:23<13:16,  1.92it/s]
 32%|███▏      | 717/2248 [02:23<10:55,  2.34it/s]
 32%|███▏      | 719/2248 [02:23<09:43,  2.62it/s]
 32%|███▏      | 721/2248 [02:23<06:42,  3.79it/s]
 32%|███▏      | 724/2248 [02:23<04:10,  6.09it/s]
 32%|███▏      | 727/2248 [02:24<05:18,  4.77it/s]
 32%|███▏      | 729/2248 [02:25<05:02,  5.02it/s]
 33%|███▎      | 731/2248 [02:25<06:02,  4.19it/s]
 33%|███▎      | 732/2248 [02:26<08:45,  2.88it/s]
 33%|███▎      | 733/2248 [02:27<11:20,  2.23it/s]
 33%|███▎      | 734/2248 [02:28<13:43,  1.84it/s]
 33%|███▎      | 735/2248 [02:29<15:56,  1.58it/s]
 33%|███▎      | 736/2248 [02:30<17:51,  1.41it/s]
 33%|███▎      | 737/2248 [02:31<17:16,  1.46it/s]
 33%|███▎      | 738/2248 [02:31<16:01,  1.57it/s]
 33%|███▎      | 740/2248 [02:31<09:32,  2.64it/s]
 33%|███▎      | 742/2248 [02:32<10:37,  2.36it/s]
 33%|███▎      | 743/2248 [02:33<12:44,  1.97it/s]
 33%|███▎      | 744/2248 [02:33<12:32,  2.00it/s]
 33%|███▎      | 746/2248 [02:33<08:02,  3.11it/s]
 33%|███▎      | 749/2248 [02:34<08:09,  3.06it/s]
 33%|███▎      | 751/2248 [02:36<09:52,  2.53it/s]
 33%|███▎      | 752/2248 [02:37<12:28,  2.00it/s]
 34%|███▎      | 754/2248 [02:38<12:27,  2.00it/s]
 34%|███▎      | 756/2248 [02:38<08:50,  2.81it/s]
 34%|███▍      | 761/2248 [02:39<06:46,  3.66it/s]
 34%|███▍      | 763/2248 [02:39<05:29,  4.50it/s]
 34%|███▍      | 767/2248 [02:40<05:44,  4.30it/s]
 34%|███▍      | 770/2248 [02:40<04:18,  5.72it/s]
 34%|███▍      | 772/2248 [02:41<06:03,  4.06it/s]
 34%|███▍      | 773/2248 [02:42<07:13,  3.40it/s]
 34%|███▍      | 774/2248 [02:42<09:19,  2.64it/s]
 34%|███▍      | 775/2248 [02:43<10:32,  2.33it/s]
 35%|███▍      | 776/2248 [02:44<13:00,  1.89it/s]
 35%|███▍      | 778/2248 [02:45<12:27,  1.97it/s]
 35%|███▍      | 780/2248 [02:45<08:37,  2.83it/s]
 35%|███▍      | 782/2248 [02:46<09:28,  2.58it/s]
 35%|███▍      | 783/2248 [02:47<11:55,  2.05it/s]
 35%|███▍      | 784/2248 [02:48<13:57,  1.75it/s]
 35%|███▍      | 786/2248 [02:48<09:08,  2.67it/s]
 35%|███▌      | 788/2248 [02:48<06:22,  3.82it/s]
 35%|███▌      | 791/2248 [02:49<07:09,  3.40it/s]
 35%|███▌      | 792/2248 [02:50<09:52,  2.46it/s]
 35%|███▌      | 795/2248 [02:50<06:08,  3.94it/s]
 35%|███▌      | 797/2248 [02:51<07:43,  3.13it/s]
 36%|███▌      | 800/2248 [02:52<07:45,  3.11it/s]
 36%|███▌      | 804/2248 [02:52<04:48,  5.00it/s]
 36%|███▌      | 806/2248 [02:53<06:22,  3.77it/s]
 36%|███▌      | 809/2248 [02:53<04:34,  5.24it/s]
 36%|███▌      | 811/2248 [02:55<09:05,  2.64it/s]
 36%|███▌      | 813/2248 [02:57<12:50,  1.86it/s]
 36%|███▌      | 814/2248 [02:58<14:32,  1.64it/s]
 36%|███▋      | 816/2248 [02:59<13:41,  1.74it/s]
 36%|███▋      | 819/2248 [02:59<08:35,  2.77it/s]
 37%|███▋      | 826/2248 [02:59<03:54,  6.06it/s]
 37%|███▋      | 832/2248 [02:59<02:28,  9.56it/s]
 37%|███▋      | 839/2248 [02:59<01:35, 14.72it/s]
 38%|███▊      | 845/2248 [03:00<01:11, 19.52it/s]
 38%|███▊      | 853/2248 [03:00<00:51, 27.16it/s]
 38%|███▊      | 860/2248 [03:00<00:41, 33.13it/s]
 39%|███▊      | 866/2248 [03:01<01:34, 14.62it/s]
 39%|███▊      | 871/2248 [03:04<04:19,  5.30it/s]
 39%|███▉      | 874/2248 [03:04<03:46,  6.08it/s]
 39%|███▉      | 877/2248 [03:05<04:32,  5.03it/s]
 39%|███▉      | 879/2248 [03:05<04:02,  5.65it/s]
 39%|███▉      | 881/2248 [03:05<04:26,  5.12it/s]
 39%|███▉      | 884/2248 [03:06<03:57,  5.75it/s]
 39%|███▉      | 886/2248 [03:06<04:56,  4.59it/s]
 40%|███▉      | 888/2248 [03:07<04:43,  4.80it/s]
 40%|███▉      | 890/2248 [03:07<04:40,  4.84it/s]
 40%|███▉      | 891/2248 [03:08<05:53,  3.84it/s]
 40%|███▉      | 893/2248 [03:08<04:37,  4.89it/s]
 40%|███▉      | 894/2248 [03:08<05:15,  4.30it/s]
 40%|███▉      | 895/2248 [03:09<07:27,  3.02it/s]
 40%|███▉      | 898/2248 [03:09<04:33,  4.94it/s]
 40%|████      | 901/2248 [03:09<03:02,  7.40it/s]
 40%|████      | 903/2248 [03:11<08:03,  2.78it/s]
 40%|████      | 905/2248 [03:12<08:23,  2.67it/s]
 40%|████      | 906/2248 [03:13<09:58,  2.24it/s]
 40%|████      | 907/2248 [03:13<10:34,  2.11it/s]
 40%|████      | 908/2248 [03:14<09:31,  2.35it/s]
 40%|████      | 909/2248 [03:14<11:07,  2.01it/s]
 40%|████      | 910/2248 [03:15<10:39,  2.09it/s]
 41%|████      | 911/2248 [03:15<10:26,  2.13it/s]
 41%|████      | 912/2248 [03:16<10:41,  2.08it/s]
 41%|████      | 913/2248 [03:16<09:15,  2.40it/s]
 41%|████      | 915/2248 [03:16<05:37,  3.95it/s]
 41%|████      | 916/2248 [03:16<06:02,  3.67it/s]
 41%|████      | 917/2248 [03:17<07:56,  2.79it/s]
 41%|████      | 919/2248 [03:18<07:00,  3.16it/s]
 41%|████      | 920/2248 [03:18<07:35,  2.91it/s]
 41%|████      | 922/2248 [03:18<05:02,  4.38it/s]
 41%|████      | 924/2248 [03:19<07:01,  3.14it/s]
 41%|████      | 927/2248 [03:20<07:12,  3.05it/s]
 41%|████▏     | 929/2248 [03:21<08:21,  2.63it/s]
 41%|████▏     | 931/2248 [03:22<09:12,  2.38it/s]
 42%|████▏     | 933/2248 [03:22<06:47,  3.22it/s]
 42%|████▏     | 934/2248 [03:23<09:22,  2.34it/s]
 42%|████▏     | 936/2248 [03:23<06:38,  3.29it/s]
 42%|████▏     | 938/2248 [03:24<07:39,  2.85it/s]
 42%|████▏     | 940/2248 [03:25<08:13,  2.65it/s]
 42%|████▏     | 943/2248 [03:25<05:17,  4.11it/s]
 42%|████▏     | 945/2248 [03:26<06:43,  3.23it/s]
 42%|████▏     | 948/2248 [03:26<04:33,  4.75it/s]
 42%|████▏     | 950/2248 [03:26<03:39,  5.91it/s]
 42%|████▏     | 952/2248 [03:27<04:17,  5.03it/s]
 42%|████▏     | 954/2248 [03:27<04:35,  4.70it/s]
 43%|████▎     | 956/2248 [03:28<04:38,  4.63it/s]
 43%|████▎     | 957/2248 [03:28<04:51,  4.43it/s]
 43%|████▎     | 958/2248 [03:29<05:35,  3.85it/s]
 43%|████▎     | 959/2248 [03:29<06:19,  3.40it/s]
 43%|████▎     | 960/2248 [03:30<07:24,  2.90it/s]
 43%|████▎     | 961/2248 [03:30<07:54,  2.71it/s]
 43%|████▎     | 962/2248 [03:31<09:41,  2.21it/s]
 43%|████▎     | 963/2248 [03:31<10:15,  2.09it/s]
 43%|████▎     | 965/2248 [03:31<06:13,  3.44it/s]
 43%|████▎     | 966/2248 [03:32<07:08,  2.99it/s]
 43%|████▎     | 967/2248 [03:32<07:59,  2.67it/s]
 43%|████▎     | 969/2248 [03:32<05:06,  4.18it/s]
 43%|████▎     | 970/2248 [03:33<08:10,  2.61it/s]
 43%|████▎     | 972/2248 [03:33<05:24,  3.93it/s]
 43%|████▎     | 974/2248 [03:33<03:51,  5.49it/s]
 43%|████▎     | 976/2248 [03:34<06:04,  3.49it/s]
 44%|████▎     | 979/2248 [03:35<03:49,  5.53it/s]
 44%|████▎     | 981/2248 [03:36<05:37,  3.75it/s]
 44%|████▎     | 983/2248 [03:36<04:22,  4.83it/s]
 44%|████▍     | 985/2248 [03:36<04:38,  4.53it/s]
 44%|████▍     | 987/2248 [03:37<05:51,  3.58it/s]
 44%|████▍     | 989/2248 [03:37<04:32,  4.62it/s]
 44%|████▍     | 991/2248 [03:37<04:19,  4.85it/s]
 44%|████▍     | 993/2248 [03:38<03:21,  6.24it/s]

[[0, False], [1, False], [2, False], [3, False], [4, False], [5, False], [6, False], [7, False], [8, False], [9, False], [10, False], [11, False], [12, False], [13, False]]

14it [00:00, 320.22it/s]

[[np.int64(0), False, 2], [np.int64(1), False, 3], [np.int64(2), False, 9], [np.int64(4), False, 12], [np.int64(5), False, 1], [np.int64(6), False, 11], [np.int64(7), False, 2], [np.int64(8), False, 0], [np.int64(10), False, 9], [np.int64(11), False, 2], [np.int64(12), False, 0], [np.int64(13), False, 1]]
not_updated_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
after merge torch.Size([14, 64])
after delete torch.Size([14, 64])
tensor(12.0218, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0209, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0326, device='cuda:0', grad_fn=<MulBackward0>)

 84%|████████▎ | 251/300 [36:05<1:49:47, 134.44s/it]/kaggle/working/PRAGA/PRAGA/Train_model.py:107: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = torch.cuda.amp.GradScaler()
/kaggle/working/PRAGA/PRAGA/Train_model.py:108: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
 84%|████████▍ | 252/300 [36:05<1:15:19, 94.15s/it]

tensor(12.0208, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0213, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0787, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0212, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.8896, device='cuda:0', grad_fn=<MulBackward0>)

 85%|████████▌ | 255/300 [36:05<24:16, 32.37s/it]

tensor(12.0252, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0245, device='cuda:0', grad_fn=<DivBackward0>) tensor(-4.9836, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0340, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0268, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.0879, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▌ | 257/300 [36:05<11:24, 15.92s/it]

tensor(12.0478, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0285, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1614, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0629, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0301, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1794, device='cuda:0', grad_fn=<MulBackward0>)

 86%|████████▋ | 259/300 [36:06<05:22,  7.86s/it]

tensor(12.0741, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0309, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1512, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0770, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1442, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 261/300 [36:06<02:32,  3.91s/it]

tensor(12.0713, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0312, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1522, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0591, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0311, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.1982, device='cuda:0', grad_fn=<MulBackward0>)

 87%|████████▋ | 262/300 [36:06<01:45,  2.78s/it]

tensor(12.0459, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0308, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2255, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0361, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0304, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2526, device='cuda:0', grad_fn=<MulBackward0>)

 88%|████████▊ | 264/300 [36:06<00:51,  1.42s/it]

tensor(12.0335, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0297, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2733, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0401, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0286, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.2933, device='cuda:0', grad_fn=<MulBackward0>)

 89%|████████▊ | 266/300 [36:06<00:25,  1.32it/s]

tensor(12.0528, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0274, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3103, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0638, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0263, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3170, device='cuda:0', grad_fn=<MulBackward0>)

 90%|████████▉ | 269/300 [36:07<00:10,  2.94it/s]

tensor(12.0659, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0256, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3209, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0570, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3233, device='cuda:0', grad_fn=<MulBackward0>)

 90%|█████████ | 270/300 [36:07<00:08,  3.64it/s]

tensor(12.0418, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3229, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0275, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0252, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3216, device='cuda:0', grad_fn=<MulBackward0>)

 91%|█████████ | 272/300 [36:07<00:05,  5.08it/s]

tensor(12.0187, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3225, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0157, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0255, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3277, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 275/300 [36:08<00:03,  6.80it/s]

tensor(12.0163, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0254, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3291, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0179, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0251, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3339, device='cuda:0', grad_fn=<MulBackward0>)

 92%|█████████▏| 276/300 [36:08<00:03,  7.05it/s]

tensor(12.0191, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0249, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3398, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0185, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0248, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3478, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 278/300 [36:08<00:02,  7.65it/s]

tensor(12.0152, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3556, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0109, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0247, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3647, device='cuda:0', grad_fn=<MulBackward0>)

 93%|█████████▎| 280/300 [36:08<00:02,  7.95it/s]

tensor(12.0062, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0243, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3698, device='cuda:0', grad_fn=<MulBackward0>)
tensor(12.0023, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0244, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3740, device='cuda:0', grad_fn=<MulBackward0>)

 94%|█████████▍| 282/300 [36:08<00:02,  8.07it/s]

tensor(11.9997, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0242, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3821, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9977, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0238, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.3906, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▍| 284/300 [36:09<00:01,  8.13it/s]

tensor(11.9962, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0235, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4014, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9952, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0233, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4066, device='cuda:0', grad_fn=<MulBackward0>)

 95%|█████████▌| 286/300 [36:09<00:01,  8.18it/s]

tensor(11.9940, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0232, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4097, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9926, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0228, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4139, device='cuda:0', grad_fn=<MulBackward0>)

 96%|█████████▌| 288/300 [36:09<00:01,  8.20it/s]

tensor(11.9910, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0226, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4193, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9891, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0224, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4233, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 290/300 [36:09<00:01,  8.19it/s]

tensor(11.9875, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0225, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4244, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9856, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0222, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4294, device='cuda:0', grad_fn=<MulBackward0>)

 97%|█████████▋| 292/300 [36:10<00:00,  8.19it/s]

tensor(11.9838, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4332, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9825, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0219, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4376, device='cuda:0', grad_fn=<MulBackward0>)

 98%|█████████▊| 294/300 [36:10<00:00,  8.22it/s]

tensor(11.9816, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4397, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9808, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4411, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▊| 296/300 [36:10<00:00,  8.21it/s]

tensor(11.9803, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4459, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9796, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0217, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4524, device='cuda:0', grad_fn=<MulBackward0>)

 99%|█████████▉| 298/300 [36:10<00:00,  8.20it/s]

tensor(11.9787, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0215, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4589, device='cuda:0', grad_fn=<MulBackward0>)
tensor(11.9775, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4629, device='cuda:0', grad_fn=<MulBackward0>)

100%|██████████| 300/300 [36:11<00:00,  7.24s/it]

tensor(11.9762, device='cuda:0', grad_fn=<AddBackward0>) tensor(0.0211, device='cuda:0', grad_fn=<DivBackward0>) tensor(-5.4652, device='cuda:0', grad_fn=<MulBackward0>)
Model training finished!

Infer time:  0.00235748291015625
PCA20 shape : (2248, 20)
PCA20 finite: True
mclust K    : 16

--------------------------------------------------------------------------------------------------------------
PRAGA RUN RESULT
--------------------------------------------------------------------------------------------------------------
Dataset     : S2-E18
Seed        : 9
Spots       : 2248
Target K    : 16
Predicted K : 16
Embedding   : (2248, 64)
ARI         : 0.326071958160
NMI         : 0.492151398633
Runtime     : 2191.54 sec
Evidence    : /kaggle/working/PRAGA_baseline/formal/S2E18_seed9

Saved: /kaggle/working/PRAGA_baseline/PRAGA_5datasets_10seeds_RAW.csv
Completed runs: 50

   dataset  seed       ARI       NMI  runtime_sec
0    E18.5     0  0.619755  0.620758   674.398380
1    E18.5     1  0.527284  0.589601  1002.814961
2    E18.5     2  0.527942  0.577047   740.726273
3    E18.5     3  0.519993  0.590708   784.296499
4    E18.5     4  0.597059  0.609564  1279.134429
5    E18.5     5  0.580906  0.601505   946.881583
6    E18.5     6  0.460449  0.569380   497.073450
7    E18.5     7  0.507632  0.579141   667.820817
8    E18.5     8  0.603200  0.608395   585.161538
9    E18.5     9  0.547171  0.582059  1837.788869
10  HLN-A1     0  0.268852  0.355541    24.842445
11  HLN-A1     1  0.266686  0.347509    24.774924
12  HLN-A1     2  0.260934  0.337296    27.905554
13  HLN-A1     3  0.222459  0.303298    26.171656
14  HLN-A1     4  0.270035  0.349797    24.258194
15  HLN-A1     5  0.253820  0.345299    24.757144
16  HLN-A1     6  0.266414  0.349928    27.069347
17  HLN-A1     7  0.265953  0.348738    27.081309
18  HLN-A1     8  0.235730  0.324173    25.190107
19  HLN-A1     9  0.262257  0.339515    28.533803
20  HLN-D1     0  0.193806  0.298272    24.553856
21  HLN-D1     1  0.211567  0.304277    23.823096
22  HLN-D1     2  0.198650  0.307996    26.021425
23  HLN-D1     3  0.165636  0.297202    27.186032
24  HLN-D1     4  0.173935  0.298787    24.710263
25  HLN-D1     5  0.186998  0.296371    26.807960
26  HLN-D1     6  0.191968  0.295184    24.521119
27  HLN-D1     7  0.195815  0.308086    24.744599
28  HLN-D1     8  0.175746  0.295864    27.024605
29  HLN-D1     9  0.201763  0.310366    24.571973
30  S2-E15     0  0.440489  0.601843   782.093683
31  S2-E15     1  0.452735  0.583210   899.700398
32  S2-E15     2  0.439196  0.569900  1106.122727
33  S2-E15     3  0.480295  0.603017   679.159512
34  S2-E15     4  0.472255  0.590751   660.144947
35  S2-E15     5  0.460203  0.596454   768.525908
36  S2-E15     6  0.475248  0.597648   847.474544
37  S2-E15     7  0.343137  0.522055  1200.994735
38  S2-E15     8  0.448261  0.584199  1537.874817
39  S2-E15     9  0.459695  0.590239   701.285220
40  S2-E18     0  0.352018  0.475135   843.487607
41  S2-E18     1  0.377655  0.471134   970.489782
42  S2-E18     2  0.339377  0.465147  1010.044722
43  S2-E18     3  0.374962  0.483305  1323.315272
44  S2-E18     4  0.513844  0.493776  1252.438000
45  S2-E18     5  0.313077  0.477886  1545.240261
46  S2-E18     6  0.435182  0.485154  1085.863837
47  S2-E18     7  0.402319  0.433206  1030.634093
48  S2-E18     8  0.411450  0.463249   899.490727
49  S2-E18     9  0.326072  0.492151  2191.544638

### Cell 12 — Summarize and validate all 50 formal PRAGA runs

In [63]:
# ============================================================
# Reload every completed run from disk
# ============================================================

rows = []


for dataset_name in DATASET_ORDER:

    tag = dataset_tag(
        dataset_name
    )

    for seed in FORMAL_SEEDS:

        run_dir = (
            FORMAL_ROOT
            / f"{tag}_seed{seed}"
        )

        metrics_path = (
            run_dir
            / "metrics.json"
        )

        assert metrics_path.exists(), (
            f"Missing: {metrics_path}"
        )

        with open(
            metrics_path,
            "r",
            encoding="utf-8",
        ) as f:

            row = json.load(
                f
            )

        rows.append(
            row
        )


raw = pd.DataFrame(
    rows
)


raw = (
    raw
    .sort_values(
        [
            "dataset",
            "seed",
        ]
    )
    .reset_index(
        drop=True
    )
)


# ============================================================
# 50-run validation
# ============================================================

assert (
    len(raw)
    ==
    50
)


for dataset_name in DATASET_ORDER:

    sub = raw[
        raw[
            "dataset"
        ]
        ==
        dataset_name
    ]

    assert (
        len(sub)
        ==
        10
    )

    assert (
        sorted(
            sub[
                "seed"
            ].tolist()
        )
        ==
        list(
            range(10)
        )
    )

    spec = (
        DATASET_SPECS[
            dataset_name
        ]
    )

    assert (
        sub[
            "n_spots"
        ]
        ==
        spec[
            "n_spots"
        ]
    ).all()

    assert (
        sub[
            "target_K"
        ]
        ==
        spec[
            "K"
        ]
    ).all()

    assert (
        sub[
            "predicted_K"
        ]
        ==
        spec[
            "K"
        ]
    ).all()

    assert (
        sub[
            "training_init_K"
        ]
        ==
        spec[
            "init_k"
        ]
    ).all()

    assert (
        sub[
            "epochs"
        ]
        ==
        spec[
            "epochs"
        ]
    ).all()


assert np.isfinite(
    raw[
        [
            "ARI",
            "NMI",
            "runtime_sec",
        ]
    ].to_numpy()
).all()


# ============================================================
# Summary
# ============================================================

summary_rows = []


for dataset_name in DATASET_ORDER:

    sub = raw[
        raw[
            "dataset"
        ]
        ==
        dataset_name
    ]


    summary_rows.append(
        {
            "dataset":
                dataset_name,

            "n_runs":
                len(sub),

            "ARI_mean":
                sub[
                    "ARI"
                ].mean(),

            "ARI_std":
                sub[
                    "ARI"
                ].std(
                    ddof=0
                ),

            "NMI_mean":
                sub[
                    "NMI"
                ].mean(),

            "NMI_std":
                sub[
                    "NMI"
                ].std(
                    ddof=0
                ),

            "runtime_mean_sec":
                sub[
                    "runtime_sec"
                ].mean(),

            "runtime_std_sec":
                sub[
                    "runtime_sec"
                ].std(
                    ddof=0
                ),
        }
    )


summary = pd.DataFrame(
    summary_rows
)


macro_ari = float(
    summary[
        "ARI_mean"
    ].mean()
)

macro_nmi = float(
    summary[
        "NMI_mean"
    ].mean()
)


RAW_CSV = (
    PRAGA_OUTPUT_ROOT
    / "PRAGA_5datasets_10seeds_RAW.csv"
)

SUMMARY_CSV = (
    PRAGA_OUTPUT_ROOT
    / "PRAGA_5datasets_10seeds_SUMMARY.csv"
)


raw.to_csv(
    RAW_CSV,
    index=False,
)

summary.to_csv(
    SUMMARY_CSV,
    index=False,
)


protocol = {
    "method":
        "PRAGA",

    "datasets":
        DATASET_ORDER,

    "seeds":
        FORMAL_SEEDS,

    "n_formal_runs":
        50,

    "RNA_ADT": {
        "KNN_k": 20,
        "RNA_weight": 5,
        "ADT_weight": 5,
        "epochs": 30,
    },

    "RNA_ATAC": {
        "KNN_k": 20,
        "RNA_weight": 1,
        "ATAC_weight": 10,
        "epochs": 300,
        "compatibility_preprocessing":
            "remove zero-total peaks; "
            "PRAGA LSI; "
            "column-wise zero-mean / "
            "unit sample-std scaling",
        "spot_filtering":
            False,
    },

    "init_k": {
        name:
            int(
                DATASET_SPECS[
                    name
                ][
                    "init_k"
                ]
            )
        for name
        in DATASET_ORDER
    },

    "clustering":
        "PRAGA embedding -> "
        "PCA20 -> mclust EEE",

    "mclust_seed":
        2020,

    "NMI_average_method":
        "max",

    "summary_std_ddof":
        0,

    "macro_ARI":
        macro_ari,

    "macro_NMI":
        macro_nmi,
}


PROTOCOL_JSON = (
    PRAGA_OUTPUT_ROOT
    / "PRAGA_PROTOCOL.json"
)


with open(
    PROTOCOL_JSON,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        protocol,
        f,
        indent=2,
    )


print(
    "=" * 110
)

print(
    "PRAGA 50-RUN VALIDATION PASS"
)

print(
    "=" * 110
)


display(
    summary
)


print(
    f"\nMacro ARI = "
    f"{macro_ari:.6f}"
)

print(
    f"Macro NMI = "
    f"{macro_nmi:.6f}"
)

print(
    "\nRAW     :",
    RAW_CSV
)

print(
    "SUMMARY :",
    SUMMARY_CSV
)

print(
    "PROTOCOL:",
    PROTOCOL_JSON
)

==============================================================================================================
PRAGA 50-RUN VALIDATION PASS
==============================================================================================================

,dataset,n_runs,ARI_mean,ARI_std,NMI_mean,NMI_std,runtime_mean_sec,runtime_std_sec
0,HLN-A1,10,0.257314,0.015069,0.340109,0.014839,26.058449,1.429496
1,HLN-D1,10,0.189588,0.013389,0.301240,0.005527,25.396493,1.173183
2,E18.5,10,0.549139,0.047522,0.592816,0.015795,901.609680,379.600515
3,S2-E15,10,0.447151,0.037155,0.583931,0.022677,918.337649,267.645452
4,S2-E18,10,0.384596,0.056645,0.474014,0.016776,1215.254894,382.865201

Macro ARI = 0.365558
Macro NMI = 0.458422

RAW     : /kaggle/working/PRAGA_baseline/PRAGA_5datasets_10seeds_RAW.csv
SUMMARY : /kaggle/working/PRAGA_baseline/PRAGA_5datasets_10seeds_SUMMARY.csv
PROTOCOL: /kaggle/working/PRAGA_baseline/PRAGA_PROTOCOL.json

### Cell 13 — Freeze all completed PRAGA formal results### Cell 13 — Freeze all completed PRAGA formal results

In [64]:
from pathlib import Path
from datetime import datetime
import json
import shutil
import platform
import sys
import numpy as np
import pandas as pd
import torch
import sklearn
import scanpy as sc
import anndata


ARCHIVE_ROOT = (
    Path("/kaggle/working")
    / "PRAGA_FINAL_ARCHIVE"
)


if ARCHIVE_ROOT.exists():

    shutil.rmtree(
        ARCHIVE_ROOT
    )


ARCHIVE_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)


# ============================================================
# Copy top-level result files
# ============================================================

top_level_files = [
    PRAGA_OUTPUT_ROOT
    / "PRAGA_5datasets_10seeds_RAW.csv",

    PRAGA_OUTPUT_ROOT
    / "PRAGA_5datasets_10seeds_SUMMARY.csv",

    PRAGA_OUTPUT_ROOT
    / "PRAGA_PROTOCOL.json",
]


for src in top_level_files:

    if src.exists():

        shutil.copy2(
            src,
            ARCHIVE_ROOT
            / src.name,
        )


# ============================================================
# Copy all 50 formal run folders
# ============================================================

formal_archive = (
    ARCHIVE_ROOT
    / "formal_runs"
)

formal_archive.mkdir(
    parents=True,
    exist_ok=True,
)


completed_runs = []
missing_runs = []


required_files = [
    "embedding.npy",
    "pred_labels.npy",
    "gt_labels.npy",
    "coords.npy",
    "spot_ids.npy",
    "metrics.json",
    "preprocessing_audit.json",
]


for dataset_name in DATASET_ORDER:

    tag = dataset_tag(
        dataset_name
    )

    for seed in range(10):

        run_name = (
            f"{tag}_seed{seed}"
        )

        src_dir = (
            FORMAL_ROOT
            / run_name
        )

        dst_dir = (
            formal_archive
            / run_name
        )


        missing = [
            name
            for name in required_files
            if not (
                src_dir
                / name
            ).exists()
        ]


        if src_dir.exists():

            shutil.copytree(
                src_dir,
                dst_dir,
                dirs_exist_ok=True,
            )


        if len(missing) == 0:

            completed_runs.append(
                {
                    "dataset":
                        dataset_name,

                    "seed":
                        int(seed),

                    "run_name":
                        run_name,
                }
            )

        else:

            missing_runs.append(
                {
                    "dataset":
                        dataset_name,

                    "seed":
                        int(seed),

                    "run_name":
                        run_name,

                    "missing_files":
                        missing,
                }
            )


# ============================================================
# Save environment / protocol snapshot
# ============================================================

manifest = {
    "method":
        "PRAGA",

    "archive_time":
        datetime.now()
        .astimezone()
        .isoformat(),

    "datasets":
        list(
            DATASET_ORDER
        ),

    "formal_seeds":
        list(
            range(10)
        ),

    "expected_runs":
        50,

    "completed_runs":
        len(
            completed_runs
        ),

    "missing_runs":
        len(
            missing_runs
        ),

    "PRAGA_git_commit":
        str(
            PRAGA_COMMIT
        ),

    "result_policy":
        (
            "All completed formal runs are archived "
            "regardless of ARI/NMI performance."
        ),

    "RNA_ADT": {
        "epochs": 30,
        "KNN_k": 20,
        "RNA_weight": 5,
        "ADT_weight": 5,
    },

    "RNA_ATAC": {
        "epochs": 300,
        "KNN_k": 20,
        "RNA_weight": 1,
        "ATAC_weight": 10,
        "compatibility_preprocessing":
            (
                "remove zero-total peaks; "
                "PRAGA LSI; "
                "component-wise standardization"
            ),
        "spot_filtering":
            False,
    },

    "final_clustering":
        "PRAGA embedding -> PCA20 -> mclust EEE",

    "mclust_seed":
        2020,

    "NMI_average_method":
        "max",

    "summary_std_ddof":
        0,

    "environment": {
        "python":
            sys.version.split()[0],

        "torch":
            torch.__version__,

        "numpy":
            np.__version__,

        "sklearn":
            sklearn.__version__,

        "scanpy":
            sc.__version__,

        "anndata":
            anndata.__version__,

        "gpu":
            (
                torch.cuda.get_device_name(0)
                if torch.cuda.is_available()
                else None
            ),
    },
}


with open(
    ARCHIVE_ROOT
    / "ARCHIVE_MANIFEST.json",
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        manifest,
        f,
        indent=2,
    )


with open(
    ARCHIVE_ROOT
    / "MISSING_RUNS.json",
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        missing_runs,
        f,
        indent=2,
    )


print("=" * 100)
print("PRAGA FINAL ARCHIVE CHECK")
print("=" * 100)

print(
    "Expected runs :",
    50
)

print(
    "Completed     :",
    len(
        completed_runs
    )
)

print(
    "Missing       :",
    len(
        missing_runs
    )
)

print(
    "Archive root  :",
    ARCHIVE_ROOT
)


if len(missing_runs) == 0:

    print(
        "\nPASS: 50/50 formal runs archived."
    )

else:

    print(
        "\nWARNING: some formal runs are incomplete."
    )

    display(
        pd.DataFrame(
            missing_runs
        )
    )

====================================================================================================
PRAGA FINAL ARCHIVE CHECK
====================================================================================================
Expected runs : 50
Completed     : 50
Missing       : 0
Archive root  : /kaggle/working/PRAGA_FINAL_ARCHIVE

PASS: 50/50 formal runs archived.

### Cell 14 — Create the final PRAGA result ZIP### Cell 14 — Create the final PRAGA result ZIP

In [65]:
import shutil
from pathlib import Path


ZIP_BASE = (
    Path("/kaggle/working")
    / "PRAGA_FINAL_5datasets_10seeds"
)


zip_path = shutil.make_archive(
    base_name=str(
        ZIP_BASE
    ),
    format="zip",
    root_dir=ARCHIVE_ROOT.parent,
    base_dir=ARCHIVE_ROOT.name,
)


zip_path = Path(
    zip_path
)


print("=" * 100)
print("FINAL PRAGA RESULT PACKAGE")
print("=" * 100)

print(
    "ZIP file:",
    zip_path
)

print(
    "Size MB :",
    f"{zip_path.stat().st_size / 1024 / 1024:.2f}"
)


summary_path = (
    ARCHIVE_ROOT
    / "PRAGA_5datasets_10seeds_SUMMARY.csv"
)


if summary_path.exists():

    summary = pd.read_csv(
        summary_path
    )

    print(
        "\nFrozen summary:"
    )

    display(
        summary
    )


print(
    "\nPASS: final PRAGA results packaged."
)

====================================================================================================
FINAL PRAGA RESULT PACKAGE
====================================================================================================
ZIP file: /kaggle/working/PRAGA_FINAL_5datasets_10seeds.zip
Size MB : 35.93

Frozen summary:

,dataset,n_runs,ARI_mean,ARI_std,NMI_mean,NMI_std,runtime_mean_sec,runtime_std_sec
0,HLN-A1,10,0.257314,0.015069,0.340109,0.014839,26.058449,1.429496
1,HLN-D1,10,0.189588,0.013389,0.301240,0.005527,25.396493,1.173183
2,E18.5,10,0.549139,0.047522,0.592816,0.015795,901.609680,379.600515
3,S2-E15,10,0.447151,0.037155,0.583931,0.022677,918.337649,267.645452
4,S2-E18,10,0.384596,0.056645,0.474014,0.016776,1215.254894,382.865201

PASS: final PRAGA results packaged.