Cell 1：检查 GPU

In [1]:
import torch
print("GPU 是否可用:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU 型号:", torch.cuda.get_device_name(0))

GPU 是否可用: True
GPU 型号: Tesla T4

Cell 2：挂载 Google Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Cell 3：验证数据路径

In [4]:
import os
data_path = "/content/drive/MyDrive/SMGC-data/"
print(os.listdir(data_path))

['simulation', 'Mouse_Embryos_S2', 'Human_Lymph_Nodes', 'E18.5_mouse_brain']

Cell 4：克隆 GitHub 代码

In [3]:
!git clone https://huqian122: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@github.com/huqian122/SpaMGCL.git /content/SpaMGCL

Cloning into '/content/SpaMGCL'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (328/328), done.
remote: Compressing objects: 100% (313/313), done.
remote: Total 328 (delta 126), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (328/328), 2.35 MiB | 11.61 MiB/s, done.
Resolving deltas: 100% (126/126), done.

Cell 5：运行 Phase 4 冒烟测试

In [5]:
!cd /content/SpaMGCL/SpaMGCL && python scripts/phase4_smoke.py

/content/SpaMGCL/SpaMGCL/src/models/gcn.py:32: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  tensor = torch.sparse_coo_tensor(indices, values, size=adj.shape).coalesce()
L_rec=0.250091
L_MGCL=3.087323
L_cluster=2.233750
L_spatial=0.000285
WD=[0.33151009678840637, 0.17174333333969116, 0.15729603171348572, 0.13252972066402435]
SC=[0.00014662364264950156, 2.6803680157172494e-05, 4.2885065340669826e-05, 6.826334720244631e-05]
w_WD=[0.2181641012430191, 0.25595822930336, 0.2596829831600189, 0.2661946713924408]
w_SC=[0.21815554797649384, 0.255963534116745, 0.25968626141548157, 0.2661946713924408]
✅ Phase 4 验证通过

Cell 6：安装依赖

In [4]:
%cd /content/SpaMGCL/SpaMGCL
!pip install anndata scanpy

/content/SpaMGCL/SpaMGCL
Collecting anndata
  Downloading anndata-0.13.3.post0-py3-none-any.whl.metadata (7.2 kB)
Collecting scanpy
  Downloading scanpy-1.12.4-py3-none-any.whl.metadata (8.5 kB)
Collecting array-api-compat>=1.7.1 (from anndata)
  Downloading array_api_compat-1.15.0-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: h5py>=3.11 in /usr/local/lib/python3.13/dist-packages (from anndata) (3.16.0)
Collecting legacy-api-wrap (from anndata)
  Downloading legacy_api_wrap-1.5-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: natsort in /usr/local/lib/python3.13/dist-packages (from anndata) (8.4.0)
Requirement already satisfied: numpy>=2.1 in /usr/local/lib/python3.13/dist-packages (from anndata) (2.1.3)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.13/dist-packages (from anndata) (26.3)
Collecting pandas>=2.3 (from anndata)
  Downloading pandas-3.0.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 4.9 MB/s eta 0:00:00
Requirement already satisfied: scipy!=1.17.0,>=1.14 in /usr/local/lib/python3.13/dist-packages (from anndata) (1.16.3)
Collecting scverse-misc>=0.1.0 (from scverse-misc[settings]>=0.1.0->anndata)
  Downloading scverse_misc-0.1.6-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.16 in /usr/local/lib/python3.13/dist-packages (from anndata) (4.16.0)
Collecting zarr>=3.1 (from anndata)
  Downloading zarr-3.3.0-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from scanpy) (2026.7.22)
Collecting fast-array-utils>=1.4 (from fast-array-utils[accel,sparse]>=1.4->scanpy)
  Downloading fast_array_utils-1.5-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from scanpy) (1.6.0)
Requirement already satisfied: matplotlib>=3.10 in /usr/local/lib/python3.13/dist-packages (from scanpy) (3.10.0)
Requirement already satisfied: networkx>=2.8.8 in /usr/local/lib/python3.13/dist-packages (from scanpy) (3.6.1)
Requirement already satisfied: numba>=0.60 in /usr/local/lib/python3.13/dist-packages (from scanpy) (0.61.2)
Requirement already satisfied: patsy in /usr/local/lib/python3.13/dist-packages (from scanpy) (1.0.3)
Requirement already satisfied: pynndescent>=0.5.13 in /usr/local/lib/python3.13/dist-packages (from scanpy) (0.6.0)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.13/dist-packages (from scanpy) (1.6.1)
Requirement already satisfied: seaborn>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from scanpy) (0.13.2)
Collecting session-info2 (from scanpy)
  Downloading session_info2-0.4.2-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: statsmodels>=0.14.5 in /usr/local/lib/python3.13/dist-packages (from scanpy) (0.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from scanpy) (4.67.3)
Requirement already satisfied: umap-learn>=0.5.12 in /usr/local/lib/python3.13/dist-packages (from scanpy) (0.5.12)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.10->scanpy) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.60->scanpy) (0.44.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->scanpy) (3.1.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6->scanpy) (3.6.0)
Collecting pydantic-settings (from scverse-misc[settings]>=0.1.0->anndata)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.13/dist-packages (from scverse-misc[settings]>=0.1.0->anndata) (1.2.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.14.5->scanpy) (1.2.2)
Collecting donfig>=0.8 (from zarr>=3.1->anndata)
  Downloading donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.13/dist-packages (from zarr>=3.1->anndata) (1.8.0)
Collecting numcodecs>=0.14 (from zarr>=3.1->anndata)
  Downloading numcodecs-0.16.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from donfig>=0.8->zarr>=3.1->anndata) (6.0.3)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->scanpy) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->scanpy) (2.25.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.14.5->scanpy) (2.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.10->scanpy) (1.17.0)
Requirement already satisfied: pydantic>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings->scverse-misc[settings]>=0.1.0->anndata) (2.13.5)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings->scverse-misc[settings]>=0.1.0->anndata) (0.4.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.7.0->pydantic-settings->scverse-misc[settings]>=0.1.0->anndata) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.7.0->pydantic-settings->scverse-misc[settings]>=0.1.0->anndata) (2.46.5)
Downloading anndata-0.13.3.post0-py3-none-any.whl (188 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.8/188.8 kB 14.0 MB/s eta 0:00:00
Downloading scanpy-1.12.4-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 75.2 MB/s eta 0:00:00
Downloading array_api_compat-1.15.0-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 8.9 MB/s eta 0:00:00
Downloading fast_array_utils-1.5-py3-none-any.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.0/40.0 kB 4.5 MB/s eta 0:00:00
Downloading legacy_api_wrap-1.5-py3-none-any.whl (10 kB)
Downloading pandas-3.0.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 125.6 MB/s eta 0:00:00
Downloading scverse_misc-0.1.6-py3-none-any.whl (28 kB)
Downloading zarr-3.3.0-py3-none-any.whl (363 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 36.8 MB/s eta 0:00:00
Downloading session_info2-0.4.2-py3-none-any.whl (17 kB)
Downloading donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Downloading numcodecs-0.16.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 130.3 MB/s eta 0:00:00
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 8.3 MB/s eta 0:00:00
Installing collected packages: session-info2, numcodecs, legacy-api-wrap, donfig, array-api-compat, zarr, scverse-misc, pandas, fast-array-utils, pydantic-settings, anndata, scanpy
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed anndata-0.13.3.post0 array-api-compat-1.15.0 donfig-0.8.1.post1 fast-array-utils-1.5 legacy-api-wrap-1.5 numcodecs-0.16.5 pandas-3.0.5 pydantic-settings-2.15.0 scanpy-1.12.4 scverse-misc-0.1.6 session-info2-0.4.2 zarr-3.3.0

Cell 7：运行 P0（Simulation，基线）

In [7]:
%cd /content/SpaMGCL/SpaMGCL

import os, yaml

# 先拉最新代码
!git pull

# 已存在就跳过
if os.path.exists("results/p0_smoke/metrics.json"):
    print("⏭️ P0 结果已存在，跳过重跑")
else:
    config_path = "configs/p0_smoke.yaml"
    with open(config_path) as f:
        cfg = yaml.safe_load(f)
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results/"}
    cfg.pop("dir", None)
    cfg["experiment"]["name"] = "p0_smoke"
    with open(config_path, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    !python experiments/run_exp.py --config configs/p0_smoke.yaml
    !cat results/p0_smoke/metrics.json

/content/SpaMGCL/SpaMGCL
Already up to date.
⏭️ P0 结果已存在，跳过重跑

Cell 8：跑 HLN-A1

In [8]:
%cd /content/SpaMGCL/SpaMGCL

import os, yaml

if os.path.exists("results/p1_hlna1/metrics.json"):
    print("⏭️ HLN-A1 结果已存在，跳过重跑")
else:
    config_path = "configs/p1_hlna1_base.yaml"
    with open("configs/p0_smoke.yaml") as f:
        cfg = yaml.safe_load(f)

    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["data"]["label_key"] = "Spatial_Label"
    cfg["data"]["n_pca_components"] = 100
    cfg["experiment"]["dataset"] = "HLN-A1"
    cfg["experiment"]["name"] = "p1_hlna1"
    cfg["training"]["epochs"] = 50
    cfg["output"] = {"root": "results/"}
    cfg.pop("dir", None)

    with open(config_path, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)

    !python experiments/run_exp.py --config configs/p1_hlna1_base.yaml
    !cat results/p1_hlna1/metrics.json

/content/SpaMGCL/SpaMGCL
⏭️ HLN-A1 结果已存在，跳过重跑

Cell 9：跑 E18.5

In [9]:
%cd /content/SpaMGCL/SpaMGCL

import os, yaml

if os.path.exists("results/p1_e185/metrics.json"):
    print("⏭️ E18.5 结果已存在，跳过重跑")
else:
    config_path = "configs/p1_e185_base.yaml"
    with open("configs/p0_smoke.yaml") as f:
        cfg = yaml.safe_load(f)

    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["data"]["label_key"] = "Combined_Clusters"
    cfg["data"]["n_pca_components"] = 100
    cfg["experiment"]["dataset"] = "E18.5"
    cfg["experiment"]["name"] = "p1_e185"
    cfg["training"]["epochs"] = 50
    cfg["output"] = {"root": "results/"}
    cfg.pop("dir", None)

    with open(config_path, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)

    !python experiments/run_exp.py --config configs/p1_e185_base.yaml
    !cat results/p1_e185/metrics.json

/content/SpaMGCL/SpaMGCL
⏭️ E18.5 结果已存在，跳过重跑

Cell 10（三组消融）

In [10]:
%%bash
cd /content/SpaMGCL/SpaMGCL

python - <<'PY'
import yaml

with open("configs/diagnostic_hlna1_fine32.yaml") as f:
    base = yaml.safe_load(f)

variants = [
    ("ablation_hlna1_core",   False, False, False),
    ("ablation_hlna1_sc",     True,  True,  False),
    ("ablation_hlna1_sc_snf", True,  True,  True),
]

for name, enabled, sc, snf in variants:
    cfg = yaml.safe_load(yaml.safe_dump(base))

    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results/"}
    cfg.pop("dir", None)
    cfg["experiment"]["name"] = name
    cfg["loss"]["lambda_cluster"] = 0.1
    cfg["loss"]["lambda_spatial"] = 0.0
    cfg["spatial"] = {
        "enabled": enabled,
        "consistency_weighting": sc,
        "negative_filter": snf,
    }
    cfg["training"]["spatial_start_epoch"] = 11 if enabled else 999

    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"✅ {name}: SC={sc} SNF={snf}")
PY

for name in ablation_hlna1_core ablation_hlna1_sc ablation_hlna1_sc_snf; do
    echo ""
    echo "=========================================="
    echo "🚀 $name"
    echo "=========================================="
    python experiments/run_exp.py --config configs/${name}.yaml || echo "⚠️ $name 失败或已存在"
done

echo ""
echo "🏁 三组消融完成"

✅ ablation_hlna1_core: SC=False SNF=False
✅ ablation_hlna1_sc: SC=True SNF=False
✅ ablation_hlna1_sc_snf: SC=True SNF=True

==========================================
🚀 ablation_hlna1_core
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.949508 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.948801 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361096 | rec=0.205753 | mgcl=8.155343 | cluster=2.947582 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947062 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154637 | cluster=2.946602 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181858 | mgcl=8.154244 | cluster=2.946202 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328270 | rec=0.174488 | mgcl=8.153782 | cluster=2.945862 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.615178 | rec=0.167404 | mgcl=8.153217 | cluster=2.945576 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=1.395e-03
epoch 012/050 | total=8.607622 | rec=0.160600 | mgcl=8.152499 | cluster=2.945223 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=1.146e-03
epoch 013/050 | total=8.600133 | rec=0.154075 | mgcl=8.151571 | cluster=2.944873 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=8.227e-04
epoch 014/050 | total=8.592641 | rec=0.147824 | mgcl=8.150353 | cluster=2.944627 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.808e-04
epoch 015/050 | total=8.585044 | rec=0.141847 | mgcl=8.148746 | cluster=2.944520 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.415e-04
epoch 016/050 | total=8.577204 | rec=0.136141 | mgcl=8.146609 | cluster=2.944533 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.458e-04
epoch 017/050 | total=8.568939 | rec=0.130708 | mgcl=8.143771 | cluster=2.944606 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.381e-04
epoch 018/050 | total=8.560001 | rec=0.125554 | mgcl=8.139980 | cluster=2.944673 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.582e-04
epoch 019/050 | total=8.550066 | rec=0.120684 | mgcl=8.134913 | cluster=2.944694 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.884e-04
epoch 020/050 | total=8.538750 | rec=0.116108 | mgcl=8.128175 | cluster=2.944668 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.431e-04
epoch 021/050 | total=8.525523 | rec=0.111836 | mgcl=8.119226 | cluster=2.944616 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.485e-04
epoch 022/050 | total=8.509752 | rec=0.107877 | mgcl=8.107418 | cluster=2.944563 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.337e-04
epoch 023/050 | total=8.490826 | rec=0.104238 | mgcl=8.092135 | cluster=2.944521 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.303e-04
epoch 024/050 | total=8.468355 | rec=0.100921 | mgcl=8.072986 | cluster=2.944493 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.703e-04
epoch 025/050 | total=8.442245 | rec=0.097920 | mgcl=8.049878 | cluster=2.944474 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.652e-04
epoch 026/050 | total=8.412889 | rec=0.095222 | mgcl=8.023221 | cluster=2.944457 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.880e-04
epoch 027/050 | total=8.381453 | rec=0.092811 | mgcl=7.994198 | cluster=2.944432 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.077e-04
epoch 028/050 | total=8.347629 | rec=0.090662 | mgcl=7.962527 | cluster=2.944395 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.104e-04
epoch 029/050 | total=8.310227 | rec=0.088756 | mgcl=7.927038 | cluster=2.944341 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.994e-04
epoch 030/050 | total=8.269084 | rec=0.087077 | mgcl=7.887579 | cluster=2.944270 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.832e-04
epoch 031/050 | total=8.225828 | rec=0.085604 | mgcl=7.845807 | cluster=2.944177 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.701e-04
epoch 032/050 | total=8.184093 | rec=0.084324 | mgcl=7.805363 | cluster=2.944055 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.689e-04
epoch 033/050 | total=8.145285 | rec=0.083212 | mgcl=7.767683 | cluster=2.943896 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.837e-04
epoch 034/050 | total=8.111240 | rec=0.082243 | mgcl=7.734628 | cluster=2.943688 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.168e-04
epoch 035/050 | total=8.077624 | rec=0.081386 | mgcl=7.701896 | cluster=2.943416 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.631e-04
epoch 036/050 | total=8.034717 | rec=0.080638 | mgcl=7.659772 | cluster=2.943067 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.196e-04
epoch 037/050 | total=8.006115 | rec=0.079961 | mgcl=7.631893 | cluster=2.942616 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.867e-04
epoch 038/050 | total=7.961985 | rec=0.079381 | mgcl=7.588400 | cluster=2.942039 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.595e-04
epoch 039/050 | total=7.929675 | rec=0.078872 | mgcl=7.556673 | cluster=2.941309 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.393e-04
epoch 040/050 | total=7.887064 | rec=0.078416 | mgcl=7.514607 | cluster=2.940418 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.284e-04
epoch 041/050 | total=7.852359 | rec=0.078021 | mgcl=7.480404 | cluster=2.939337 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=8.274e-04
epoch 042/050 | total=7.814095 | rec=0.077695 | mgcl=7.442598 | cluster=2.938018 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=9.357e-04
epoch 043/050 | total=7.781472 | rec=0.077425 | mgcl=7.410404 | cluster=2.936435 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.053e-03
epoch 044/050 | total=7.746835 | rec=0.077193 | mgcl=7.376182 | cluster=2.934598 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.177e-03
epoch 045/050 | total=7.716823 | rec=0.076993 | mgcl=7.346581 | cluster=2.932491 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.305e-03
epoch 046/050 | total=7.688784 | rec=0.076825 | mgcl=7.318953 | cluster=2.930064 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.438e-03
epoch 047/050 | total=7.660791 | rec=0.076682 | mgcl=7.291379 | cluster=2.927298 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.575e-03
epoch 048/050 | total=7.637600 | rec=0.076545 | mgcl=7.268631 | cluster=2.924230 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.714e-03
epoch 049/050 | total=7.613406 | rec=0.076411 | mgcl=7.244909 | cluster=2.920860 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.854e-03
epoch 050/050 | total=7.594195 | rec=0.076279 | mgcl=7.226204 | cluster=2.917119 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.996e-03
ARI=0.289443 | NMI=0.353859
Output directory: /content/SpaMGCL/SpaMGCL/results/ablation_hlna1_core
Saved metrics: /content/SpaMGCL/SpaMGCL/results/ablation_hlna1_core/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/ablation_hlna1_core/config.yaml

==========================================
🚀 ablation_hlna1_sc
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411675 | rec=0.252383 | mgcl=8.159292 | cluster=2.951158 | spatial=0.000000 | SC=on | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=on | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389495 | rec=0.232628 | mgcl=8.156867 | cluster=2.949508 | spatial=0.000000 | SC=on | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379530 | rec=0.223314 | mgcl=8.156216 | cluster=2.948801 | spatial=0.000000 | SC=on | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370091 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=on | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361095 | rec=0.205753 | mgcl=8.155343 | cluster=2.947582 | spatial=0.000000 | SC=on | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197477 | mgcl=8.154991 | cluster=2.947062 | spatial=0.000000 | SC=on | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344153 | rec=0.189517 | mgcl=8.154636 | cluster=2.946602 | spatial=0.000000 | SC=on | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181857 | mgcl=8.154244 | cluster=2.946203 | spatial=0.000000 | SC=on | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328271 | rec=0.174488 | mgcl=8.153783 | cluster=2.945862 | spatial=0.000000 | SC=on | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.615179 | rec=0.167403 | mgcl=8.153218 | cluster=2.945576 | spatial=0.024308 | SC=on | SNF=off | effC=9.991 | gradC=1.395e-03
epoch 012/050 | total=8.607621 | rec=0.160600 | mgcl=8.152499 | cluster=2.945223 | spatial=0.026732 | SC=on | SNF=off | effC=9.994 | gradC=1.146e-03
epoch 013/050 | total=8.600133 | rec=0.154074 | mgcl=8.151572 | cluster=2.944873 | spatial=0.030071 | SC=on | SNF=off | effC=9.997 | gradC=8.227e-04
epoch 014/050 | total=8.592643 | rec=0.147823 | mgcl=8.150356 | cluster=2.944627 | spatial=0.034579 | SC=on | SNF=off | effC=9.999 | gradC=4.807e-04
epoch 015/050 | total=8.585047 | rec=0.141846 | mgcl=8.148749 | cluster=2.944520 | spatial=0.040605 | SC=on | SNF=off | effC=10.000 | gradC=2.415e-04
epoch 016/050 | total=8.577210 | rec=0.136140 | mgcl=8.146617 | cluster=2.944533 | spatial=0.048598 | SC=on | SNF=off | effC=10.000 | gradC=3.458e-04
epoch 017/050 | total=8.568951 | rec=0.130707 | mgcl=8.143784 | cluster=2.944606 | spatial=0.059086 | SC=on | SNF=off | effC=9.999 | gradC=5.382e-04
epoch 018/050 | total=8.560019 | rec=0.125552 | mgcl=8.140000 | cluster=2.944673 | spatial=0.072810 | SC=on | SNF=off | effC=9.998 | gradC=6.582e-04
epoch 019/050 | total=8.550095 | rec=0.120682 | mgcl=8.134944 | cluster=2.944693 | spatial=0.090888 | SC=on | SNF=off | effC=9.998 | gradC=6.884e-04
epoch 020/050 | total=8.538795 | rec=0.116106 | mgcl=8.128222 | cluster=2.944668 | spatial=0.114850 | SC=on | SNF=off | effC=9.998 | gradC=6.432e-04
epoch 021/050 | total=8.525596 | rec=0.111833 | mgcl=8.119301 | cluster=2.944616 | spatial=0.146580 | SC=on | SNF=off | effC=9.999 | gradC=5.485e-04
epoch 022/050 | total=8.509867 | rec=0.107874 | mgcl=8.107536 | cluster=2.944563 | spatial=0.188678 | SC=on | SNF=off | effC=9.999 | gradC=4.337e-04
epoch 023/050 | total=8.491003 | rec=0.104234 | mgcl=8.092317 | cluster=2.944521 | spatial=0.244473 | SC=on | SNF=off | effC=10.000 | gradC=3.303e-04
epoch 024/050 | total=8.468616 | rec=0.100915 | mgcl=8.073252 | cluster=2.944493 | spatial=0.318297 | SC=on | SNF=off | effC=10.000 | gradC=2.703e-04
epoch 025/050 | total=8.442596 | rec=0.097913 | mgcl=8.050237 | cluster=2.944474 | spatial=0.414856 | SC=on | SNF=off | effC=10.000 | gradC=2.651e-04
epoch 026/050 | total=8.413293 | rec=0.095214 | mgcl=8.023633 | cluster=2.944457 | spatial=0.536538 | SC=on | SNF=off | effC=10.000 | gradC=2.880e-04
epoch 027/050 | total=8.381778 | rec=0.092801 | mgcl=7.994533 | cluster=2.944432 | spatial=0.678627 | SC=on | SNF=off | effC=10.000 | gradC=3.076e-04
epoch 028/050 | total=8.347730 | rec=0.090651 | mgcl=7.962639 | cluster=2.944395 | spatial=0.822096 | SC=on | SNF=off | effC=10.000 | gradC=3.103e-04
epoch 029/050 | total=8.310050 | rec=0.088743 | mgcl=7.926872 | cluster=2.944341 | spatial=0.946957 | SC=on | SNF=off | effC=10.000 | gradC=2.991e-04
epoch 030/050 | total=8.268601 | rec=0.087063 | mgcl=7.887111 | cluster=2.944270 | spatial=1.027573 | SC=on | SNF=off | effC=10.000 | gradC=2.830e-04
epoch 031/050 | total=8.225157 | rec=0.085587 | mgcl=7.845152 | cluster=2.944176 | spatial=1.081260 | SC=on | SNF=off | effC=10.000 | gradC=2.700e-04
epoch 032/050 | total=8.183490 | rec=0.084304 | mgcl=7.804781 | cluster=2.944055 | spatial=1.143319 | SC=on | SNF=off | effC=10.000 | gradC=2.690e-04
epoch 033/050 | total=8.144593 | rec=0.083191 | mgcl=7.767014 | cluster=2.943896 | spatial=1.223871 | SC=on | SNF=off | effC=10.000 | gradC=2.838e-04
epoch 034/050 | total=8.109466 | rec=0.082217 | mgcl=7.732880 | cluster=2.943688 | spatial=1.343861 | SC=on | SNF=off | effC=10.000 | gradC=3.173e-04
epoch 035/050 | total=8.075731 | rec=0.081368 | mgcl=7.700022 | cluster=2.943414 | spatial=1.435315 | SC=on | SNF=off | effC=10.000 | gradC=3.633e-04
epoch 036/050 | total=8.032287 | rec=0.080610 | mgcl=7.657370 | cluster=2.943064 | spatial=1.506378 | SC=on | SNF=off | effC=10.000 | gradC=4.210e-04
epoch 037/050 | total=8.002275 | rec=0.079941 | mgcl=7.628073 | cluster=2.942614 | spatial=1.584295 | SC=on | SNF=off | effC=10.000 | gradC=4.879e-04
epoch 038/050 | total=7.959035 | rec=0.079357 | mgcl=7.585475 | cluster=2.942031 | spatial=1.641879 | SC=on | SNF=off | effC=10.000 | gradC=5.601e-04
epoch 039/050 | total=7.928644 | rec=0.078850 | mgcl=7.555664 | cluster=2.941301 | spatial=1.663437 | SC=on | SNF=off | effC=10.000 | gradC=6.394e-04
epoch 040/050 | total=7.882317 | rec=0.078390 | mgcl=7.509886 | cluster=2.940413 | spatial=1.684698 | SC=on | SNF=off | effC=10.000 | gradC=7.292e-04
epoch 041/050 | total=7.850960 | rec=0.077999 | mgcl=7.479029 | cluster=2.939323 | spatial=1.714126 | SC=on | SNF=off | effC=10.000 | gradC=8.287e-04
epoch 042/050 | total=7.808726 | rec=0.077681 | mgcl=7.437246 | cluster=2.937993 | spatial=1.754313 | SC=on | SNF=off | effC=10.000 | gradC=9.374e-04
epoch 043/050 | total=7.778788 | rec=0.077411 | mgcl=7.407736 | cluster=2.936409 | spatial=1.801804 | SC=on | SNF=off | effC=10.000 | gradC=1.056e-03
epoch 044/050 | total=7.741001 | rec=0.077174 | mgcl=7.370369 | cluster=2.934574 | spatial=1.820937 | SC=on | SNF=off | effC=10.000 | gradC=1.180e-03
epoch 045/050 | total=7.714134 | rec=0.076974 | mgcl=7.343915 | cluster=2.932455 | spatial=1.807815 | SC=on | SNF=off | effC=10.000 | gradC=1.309e-03
epoch 046/050 | total=7.682283 | rec=0.076809 | mgcl=7.312474 | cluster=2.930002 | spatial=1.792425 | SC=on | SNF=off | effC=10.000 | gradC=1.443e-03
epoch 047/050 | total=7.656895 | rec=0.076661 | mgcl=7.287512 | cluster=2.927219 | spatial=1.789277 | SC=on | SNF=off | effC=10.000 | gradC=1.582e-03
epoch 048/050 | total=7.630391 | rec=0.076522 | mgcl=7.261454 | cluster=2.924145 | spatial=1.776190 | SC=on | SNF=off | effC=9.999 | gradC=1.722e-03
epoch 049/050 | total=7.607790 | rec=0.076387 | mgcl=7.239327 | cluster=2.920751 | spatial=1.742686 | SC=on | SNF=off | effC=9.999 | gradC=1.862e-03
epoch 050/050 | total=7.587786 | rec=0.076257 | mgcl=7.219833 | cluster=2.916956 | spatial=1.727486 | SC=on | SNF=off | effC=9.999 | gradC=2.005e-03
ARI=0.288287 | NMI=0.353487
Output directory: /content/SpaMGCL/SpaMGCL/results/ablation_hlna1_sc
Saved metrics: /content/SpaMGCL/SpaMGCL/results/ablation_hlna1_sc/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/ablation_hlna1_sc/config.yaml

==========================================
🚀 ablation_hlna1_sc_snf
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.410587 | rec=0.252383 | mgcl=8.158204 | cluster=2.951158 | spatial=0.000000 | SC=on | SNF=on | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.399041 | rec=0.242313 | mgcl=8.156728 | cluster=2.950293 | spatial=0.000000 | SC=on | SNF=on | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.388408 | rec=0.232628 | mgcl=8.155780 | cluster=2.949508 | spatial=0.000000 | SC=on | SNF=on | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.378442 | rec=0.223314 | mgcl=8.155128 | cluster=2.948801 | spatial=0.000000 | SC=on | SNF=on | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.369002 | rec=0.214360 | mgcl=8.154642 | cluster=2.948162 | spatial=0.000000 | SC=on | SNF=on | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.360005 | rec=0.205753 | mgcl=8.154252 | cluster=2.947582 | spatial=0.000000 | SC=on | SNF=on | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.351377 | rec=0.197478 | mgcl=8.153900 | cluster=2.947062 | spatial=0.000000 | SC=on | SNF=on | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.343061 | rec=0.189517 | mgcl=8.153544 | cluster=2.946602 | spatial=0.000000 | SC=on | SNF=on | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.335011 | rec=0.181858 | mgcl=8.153152 | cluster=2.946202 | spatial=0.000000 | SC=on | SNF=on | effC=9.986 | gradC=0.000e+00
epoch 010/050 | total=8.327178 | rec=0.174488 | mgcl=8.152690 | cluster=2.945862 | spatial=0.000000 | SC=on | SNF=on | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.614084 | rec=0.167404 | mgcl=8.152122 | cluster=2.945576 | spatial=0.024325 | SC=on | SNF=on | effC=9.991 | gradC=1.395e-03
epoch 012/050 | total=8.606525 | rec=0.160601 | mgcl=8.151402 | cluster=2.945223 | spatial=0.026757 | SC=on | SNF=on | effC=9.994 | gradC=1.146e-03
epoch 013/050 | total=8.599034 | rec=0.154075 | mgcl=8.150473 | cluster=2.944873 | spatial=0.030103 | SC=on | SNF=on | effC=9.997 | gradC=8.227e-04
epoch 014/050 | total=8.591539 | rec=0.147824 | mgcl=8.149252 | cluster=2.944627 | spatial=0.034619 | SC=on | SNF=on | effC=9.999 | gradC=4.808e-04
epoch 015/050 | total=8.583940 | rec=0.141847 | mgcl=8.147641 | cluster=2.944520 | spatial=0.040655 | SC=on | SNF=on | effC=10.000 | gradC=2.415e-04
epoch 016/050 | total=8.576095 | rec=0.136141 | mgcl=8.145499 | cluster=2.944533 | spatial=0.048661 | SC=on | SNF=on | effC=10.000 | gradC=3.457e-04
epoch 017/050 | total=8.567826 | rec=0.130709 | mgcl=8.142657 | cluster=2.944606 | spatial=0.059176 | SC=on | SNF=on | effC=9.999 | gradC=5.381e-04
epoch 018/050 | total=8.558884 | rec=0.125555 | mgcl=8.138862 | cluster=2.944673 | spatial=0.072931 | SC=on | SNF=on | effC=9.998 | gradC=6.582e-04
epoch 019/050 | total=8.548941 | rec=0.120685 | mgcl=8.133786 | cluster=2.944694 | spatial=0.091043 | SC=on | SNF=on | effC=9.998 | gradC=6.884e-04
epoch 020/050 | total=8.537618 | rec=0.116110 | mgcl=8.127041 | cluster=2.944668 | spatial=0.115048 | SC=on | SNF=on | effC=9.998 | gradC=6.432e-04
epoch 021/050 | total=8.524386 | rec=0.111838 | mgcl=8.118087 | cluster=2.944616 | spatial=0.146825 | SC=on | SNF=on | effC=9.999 | gradC=5.485e-04
epoch 022/050 | total=8.508617 | rec=0.107880 | mgcl=8.106280 | cluster=2.944563 | spatial=0.188987 | SC=on | SNF=on | effC=9.999 | gradC=4.338e-04
epoch 023/050 | total=8.489699 | rec=0.104242 | mgcl=8.091006 | cluster=2.944521 | spatial=0.244878 | SC=on | SNF=on | effC=10.000 | gradC=3.303e-04

/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(

Cell 11（结果汇总）

In [11]:
import json
import pandas as pd

rows = []
for name in ["ablation_hlna1_core", "ablation_hlna1_sc", "ablation_hlna1_sc_snf"]:
    path = f"/content/SpaMGCL/SpaMGCL/results/{name}/metrics.json"
    try:
        with open(path) as f:
            d = json.load(f)
        rows.append({
            "config": name,
            "SC": d.get("spatial_weighting_enabled"),
            "SNF": d.get("spatial_negative_filter_enabled"),
            "ARI": round(d["ARI"], 4),
            "NMI": round(d["NMI"], 4),
        })
    except FileNotFoundError:
        rows.append({"config": name, "status": "❌ 未完成"})

print(pd.DataFrame(rows).to_string(index=False))

               config    SC   SNF    ARI    NMI
  ablation_hlna1_core False False 0.2894 0.3539
    ablation_hlna1_sc  True False 0.2883 0.3535
ablation_hlna1_sc_snf  True  True 0.2880 0.3529

SC 消融：SC 开启后 ARI 从 0.2894 降到 0.2883（-0.0011），NMI 从 0.3539 降到 0.3535。
SNF 消融：SC+SNF 后 ARI 进一步降到 0.2880，NMI 降到 0.3529。
结论：在当前 fine32 + lambda_cluster=0.1 + lambda_spatial=0 设置下，
      SC 和 SNF 均无正向收益，SNF 甚至进一步轻微下降。
      空间机制的收益问题需要单独设计实验验证，见下一节。

cell12:跑E18.5 数据

In [10]:
%cd /content/SpaMGCL/SpaMGCL

import yaml

with open("configs/e185_ablation_core.yaml") as f:
    base = yaml.safe_load(f)

variants = [
    ("e185_cl03",   32,  0.3),
    ("e185_cl10",   32,  1.0),
    ("e185_cl30",   32,  3.0),
    ("e185_dim64",  64,  1.0),
    ("e185_dim128", 128, 1.0),
]

for name, dim, lam in variants:
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["model"]["fine_dim"] = dim
    cfg["loss"]["lambda_cluster"] = lam
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"✅ {name}: fine_dim={dim}, lambda_cluster={lam}")

/content/SpaMGCL/SpaMGCL
✅ e185_cl03: fine_dim=32, lambda_cluster=0.3
✅ e185_cl10: fine_dim=32, lambda_cluster=1.0
✅ e185_cl30: fine_dim=32, lambda_cluster=3.0
✅ e185_dim64: fine_dim=64, lambda_cluster=1.0
✅ e185_dim128: fine_dim=128, lambda_cluster=1.0

In [11]:
%cd /content/SpaMGCL/SpaMGCL

!python experiments/run_exp.py --config configs/e185_cl03.yaml
!python experiments/run_exp.py --config configs/e185_cl10.yaml
!python experiments/run_exp.py --config configs/e185_cl30.yaml
!python experiments/run_exp.py --config configs/e185_dim64.yaml
!python experiments/run_exp.py --config configs/e185_dim128.yaml

/content/SpaMGCL/SpaMGCL
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.864917 | rec=0.198570 | mgcl=7.666347 | cluster=3.303800 | spatial=0.000000 | SC=off | SNF=off | effC=13.909 | gradC=0.000e+00
epoch 002/050 | total=7.853665 | rec=0.188822 | mgcl=7.664843 | cluster=3.302656 | spatial=0.000000 | SC=off | SNF=off | effC=13.922 | gradC=0.000e+00
epoch 003/050 | total=7.843503 | rec=0.179530 | mgcl=7.663973 | cluster=3.301626 | spatial=0.000000 | SC=off | SNF=off | effC=13.934 | gradC=0.000e+00
epoch 004/050 | total=7.834100 | rec=0.170688 | mgcl=7.663412 | cluster=3.300723 | spatial=0.000000 | SC=off | SNF=off | effC=13.944 | gradC=0.000e+00
epoch 005/050 | total=7.825247 | rec=0.162272 | mgcl=7.662975 | cluster=3.299937 | spatial=0.000000 | SC=off | SNF=off | effC=13.953 | gradC=0.000e+00
epoch 006/050 | total=7.816809 | rec=0.154253 | mgcl=7.662556 | cluster=3.299252 | spatial=0.000000 | SC=off | SNF=off | effC=13.961 | gradC=0.000e+00
epoch 007/050 | total=7.808719 | rec=0.146611 | mgcl=7.662108 | cluster=3.298657 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=0.000e+00
epoch 008/050 | total=7.800929 | rec=0.139332 | mgcl=7.661596 | cluster=3.298143 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=0.000e+00
epoch 009/050 | total=7.793368 | rec=0.132402 | mgcl=7.660966 | cluster=3.297704 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=0.000e+00
epoch 010/050 | total=7.785978 | rec=0.125803 | mgcl=7.660175 | cluster=3.297333 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=0.000e+00
epoch 011/050 | total=8.767776 | rec=0.119521 | mgcl=7.659146 | cluster=3.297028 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=3.686e-03
epoch 012/050 | total=8.760330 | rec=0.113543 | mgcl=7.657787 | cluster=3.296668 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=3.104e-03
epoch 013/050 | total=8.752737 | rec=0.107857 | mgcl=7.655985 | cluster=3.296315 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.401e-03
epoch 014/050 | total=8.744872 | rec=0.102457 | mgcl=7.653593 | cluster=3.296075 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.754e-03
epoch 015/050 | total=8.736523 | rec=0.097338 | mgcl=7.650398 | cluster=3.295956 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.273e-03
epoch 016/050 | total=8.727326 | rec=0.092498 | mgcl=7.646049 | cluster=3.295930 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.041e-03
epoch 017/050 | total=8.716834 | rec=0.087940 | mgcl=7.640107 | cluster=3.295958 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.100e-03
epoch 018/050 | total=8.704453 | rec=0.083673 | mgcl=7.631979 | cluster=3.296004 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.323e-03
epoch 019/050 | total=8.689379 | rec=0.079709 | mgcl=7.620859 | cluster=3.296040 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.544e-03
epoch 020/050 | total=8.670780 | rec=0.076070 | mgcl=7.605896 | cluster=3.296048 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.676e-03
epoch 021/050 | total=8.647725 | rec=0.072769 | mgcl=7.586149 | cluster=3.296025 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.695e-03
epoch 022/050 | total=8.619845 | rec=0.069811 | mgcl=7.561241 | cluster=3.295978 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.616e-03
epoch 023/050 | total=8.587719 | rec=0.067188 | mgcl=7.531756 | cluster=3.295917 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.467e-03
epoch 024/050 | total=8.553042 | rec=0.064883 | mgcl=7.499406 | cluster=3.295845 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.282e-03
epoch 025/050 | total=8.518414 | rec=0.062862 | mgcl=7.466823 | cluster=3.295761 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.098e-03
epoch 026/050 | total=8.485389 | rec=0.061086 | mgcl=7.435606 | cluster=3.295655 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.547e-04
epoch 027/050 | total=8.453099 | rec=0.059521 | mgcl=7.404924 | cluster=3.295513 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=8.921e-04
epoch 028/050 | total=8.420782 | rec=0.058141 | mgcl=7.374047 | cluster=3.295315 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=9.278e-04
epoch 029/050 | total=8.389747 | rec=0.056918 | mgcl=7.344315 | cluster=3.295045 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.046e-03
epoch 030/050 | total=8.360291 | rec=0.055837 | mgcl=7.316050 | cluster=3.294680 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.216e-03
epoch 031/050 | total=8.331424 | rec=0.054881 | mgcl=7.288282 | cluster=3.294203 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.427e-03
epoch 032/050 | total=8.305558 | rec=0.054037 | mgcl=7.263447 | cluster=3.293581 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.677e-03
epoch 033/050 | total=8.282589 | rec=0.053314 | mgcl=7.241441 | cluster=3.292778 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.975e-03
epoch 034/050 | total=8.260364 | rec=0.052686 | mgcl=7.220154 | cluster=3.291746 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.330e-03
epoch 035/050 | total=8.239453 | rec=0.052156 | mgcl=7.200167 | cluster=3.290436 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.733e-03
epoch 036/050 | total=8.220098 | rec=0.051716 | mgcl=7.181748 | cluster=3.288783 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.192e-03
epoch 037/050 | total=8.202271 | rec=0.051341 | mgcl=7.164911 | cluster=3.286731 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.704e-03
epoch 038/050 | total=8.185185 | rec=0.051013 | mgcl=7.148890 | cluster=3.284274 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.243e-03
epoch 039/050 | total=8.169123 | rec=0.050724 | mgcl=7.133989 | cluster=3.281363 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.810e-03
epoch 040/050 | total=8.153051 | rec=0.050454 | mgcl=7.119207 | cluster=3.277971 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.391e-03
epoch 041/050 | total=8.137575 | rec=0.050202 | mgcl=7.105140 | cluster=3.274109 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.973e-03
epoch 042/050 | total=8.123114 | rec=0.049951 | mgcl=7.092227 | cluster=3.269786 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.529e-03
epoch 043/050 | total=8.108473 | rec=0.049710 | mgcl=7.079295 | cluster=3.264891 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.090e-03
epoch 044/050 | total=8.093903 | rec=0.049464 | mgcl=7.066597 | cluster=3.259476 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.610e-03
epoch 045/050 | total=8.079655 | rec=0.049228 | mgcl=7.054387 | cluster=3.253467 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=8.111e-03
epoch 046/050 | total=8.065612 | rec=0.048999 | mgcl=7.042590 | cluster=3.246743 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=8.591e-03
epoch 047/050 | total=8.051311 | rec=0.048778 | mgcl=7.030738 | cluster=3.239312 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.023e-03
epoch 048/050 | total=8.035992 | rec=0.048574 | mgcl=7.018051 | cluster=3.231219 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.414e-03
epoch 049/050 | total=8.020616 | rec=0.048375 | mgcl=7.005509 | cluster=3.222439 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.733e-03
epoch 050/050 | total=8.005498 | rec=0.048182 | mgcl=6.993401 | cluster=3.213050 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.972e-03
ARI=0.218132 | NMI=0.200427
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_cl03
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_cl03/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_cl03/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.864917 | rec=0.198570 | mgcl=7.666347 | cluster=3.303800 | spatial=0.000000 | SC=off | SNF=off | effC=13.909 | gradC=0.000e+00
epoch 002/050 | total=7.853665 | rec=0.188822 | mgcl=7.664843 | cluster=3.302656 | spatial=0.000000 | SC=off | SNF=off | effC=13.922 | gradC=0.000e+00
epoch 003/050 | total=7.843503 | rec=0.179530 | mgcl=7.663973 | cluster=3.301626 | spatial=0.000000 | SC=off | SNF=off | effC=13.934 | gradC=0.000e+00
epoch 004/050 | total=7.834100 | rec=0.170688 | mgcl=7.663412 | cluster=3.300723 | spatial=0.000000 | SC=off | SNF=off | effC=13.944 | gradC=0.000e+00
epoch 005/050 | total=7.825246 | rec=0.162272 | mgcl=7.662974 | cluster=3.299937 | spatial=0.000000 | SC=off | SNF=off | effC=13.953 | gradC=0.000e+00
epoch 006/050 | total=7.816809 | rec=0.154253 | mgcl=7.662556 | cluster=3.299252 | spatial=0.000000 | SC=off | SNF=off | effC=13.961 | gradC=0.000e+00
epoch 007/050 | total=7.808719 | rec=0.146611 | mgcl=7.662108 | cluster=3.298657 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=0.000e+00
epoch 008/050 | total=7.800929 | rec=0.139332 | mgcl=7.661596 | cluster=3.298143 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=0.000e+00
epoch 009/050 | total=7.793368 | rec=0.132402 | mgcl=7.660966 | cluster=3.297704 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=0.000e+00
epoch 010/050 | total=7.785977 | rec=0.125803 | mgcl=7.660174 | cluster=3.297333 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=0.000e+00
epoch 011/050 | total=11.075695 | rec=0.119521 | mgcl=7.659146 | cluster=3.297028 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=1.229e-02
epoch 012/050 | total=11.067999 | rec=0.113543 | mgcl=7.657787 | cluster=3.296668 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=1.035e-02
epoch 013/050 | total=11.060160 | rec=0.107858 | mgcl=7.655985 | cluster=3.296316 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=7.991e-03
epoch 014/050 | total=11.052124 | rec=0.102459 | mgcl=7.653592 | cluster=3.296074 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=5.817e-03
epoch 015/050 | total=11.043694 | rec=0.097340 | mgcl=7.650398 | cluster=3.295955 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.210e-03
epoch 016/050 | total=11.034481 | rec=0.092500 | mgcl=7.646051 | cluster=3.295929 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.457e-03
epoch 017/050 | total=11.024010 | rec=0.087942 | mgcl=7.640111 | cluster=3.295956 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.680e-03
epoch 018/050 | total=11.011665 | rec=0.083676 | mgcl=7.631987 | cluster=3.296002 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.432e-03
epoch 019/050 | total=10.996614 | rec=0.079713 | mgcl=7.620863 | cluster=3.296038 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=5.166e-03
epoch 020/050 | total=10.978016 | rec=0.076075 | mgcl=7.605896 | cluster=3.296045 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=5.597e-03
epoch 021/050 | total=10.954941 | rec=0.072775 | mgcl=7.586145 | cluster=3.296021 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=5.653e-03
epoch 022/050 | total=10.927027 | rec=0.069818 | mgcl=7.561238 | cluster=3.295972 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=5.384e-03
epoch 023/050 | total=10.894857 | rec=0.067196 | mgcl=7.531754 | cluster=3.295907 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.889e-03
epoch 024/050 | total=10.860121 | rec=0.064892 | mgcl=7.499399 | cluster=3.295830 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.285e-03
epoch 025/050 | total=10.825431 | rec=0.062872 | mgcl=7.466819 | cluster=3.295739 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.689e-03
epoch 026/050 | total=10.792313 | rec=0.061096 | mgcl=7.435593 | cluster=3.295624 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.234e-03
epoch 027/050 | total=10.759892 | rec=0.059532 | mgcl=7.404891 | cluster=3.295469 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.044e-03
epoch 028/050 | total=10.727395 | rec=0.058153 | mgcl=7.373989 | cluster=3.295254 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.178e-03
epoch 029/050 | total=10.696131 | rec=0.056932 | mgcl=7.344238 | cluster=3.294960 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.590e-03
epoch 030/050 | total=10.666379 | rec=0.055853 | mgcl=7.315959 | cluster=3.294566 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.184e-03
epoch 031/050 | total=10.637178 | rec=0.054900 | mgcl=7.288226 | cluster=3.294053 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.919e-03
epoch 032/050 | total=10.610864 | rec=0.054060 | mgcl=7.263418 | cluster=3.293386 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=5.790e-03
epoch 033/050 | total=10.587294 | rec=0.053343 | mgcl=7.241426 | cluster=3.292524 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=6.828e-03
epoch 034/050 | total=10.564293 | rec=0.052721 | mgcl=7.220157 | cluster=3.291415 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=8.065e-03
epoch 035/050 | total=10.542408 | rec=0.052199 | mgcl=7.200208 | cluster=3.290001 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.484e-03
epoch 036/050 | total=10.521744 | rec=0.051769 | mgcl=7.181774 | cluster=3.288201 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.112e-02
epoch 037/050 | total=10.502352 | rec=0.051408 | mgcl=7.165007 | cluster=3.285938 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.298e-02
epoch 038/050 | total=10.483313 | rec=0.051097 | mgcl=7.149047 | cluster=3.283168 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.500e-02
epoch 039/050 | total=10.464811 | rec=0.050829 | mgcl=7.134191 | cluster=3.279791 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.720e-02
epoch 040/050 | total=10.445824 | rec=0.050586 | mgcl=7.119526 | cluster=3.275712 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.956e-02
epoch 041/050 | total=10.426777 | rec=0.050366 | mgcl=7.105554 | cluster=3.270857 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.204e-02
epoch 042/050 | total=10.407911 | rec=0.050158 | mgcl=7.092635 | cluster=3.265119 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.457e-02
epoch 043/050 | total=10.388136 | rec=0.049965 | mgcl=7.079883 | cluster=3.258288 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.722e-02
epoch 044/050 | total=10.367863 | rec=0.049778 | mgcl=7.067791 | cluster=3.250294 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.980e-02
epoch 045/050 | total=10.346519 | rec=0.049613 | mgcl=7.055920 | cluster=3.240986 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.232e-02
epoch 046/050 | total=10.324148 | rec=0.049463 | mgcl=7.044469 | cluster=3.230216 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.468e-02
epoch 047/050 | total=10.300472 | rec=0.049334 | mgcl=7.033149 | cluster=3.217988 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=3.673e-02
epoch 048/050 | total=10.275244 | rec=0.049233 | mgcl=7.021572 | cluster=3.204439 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=3.840e-02
epoch 049/050 | total=10.249112 | rec=0.049145 | mgcl=7.010157 | cluster=3.189811 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=3.953e-02
epoch 050/050 | total=10.222245 | rec=0.049070 | mgcl=6.998785 | cluster=3.174389 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=4.015e-02
ARI=0.232525 | NMI=0.226878
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_cl10
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_cl10/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_cl10/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.864917 | rec=0.198570 | mgcl=7.666347 | cluster=3.303800 | spatial=0.000000 | SC=off | SNF=off | effC=13.909 | gradC=0.000e+00
epoch 002/050 | total=7.853665 | rec=0.188822 | mgcl=7.664843 | cluster=3.302656 | spatial=0.000000 | SC=off | SNF=off | effC=13.922 | gradC=0.000e+00
epoch 003/050 | total=7.843503 | rec=0.179530 | mgcl=7.663973 | cluster=3.301626 | spatial=0.000000 | SC=off | SNF=off | effC=13.934 | gradC=0.000e+00
epoch 004/050 | total=7.834100 | rec=0.170688 | mgcl=7.663412 | cluster=3.300723 | spatial=0.000000 | SC=off | SNF=off | effC=13.944 | gradC=0.000e+00
epoch 005/050 | total=7.825245 | rec=0.162272 | mgcl=7.662973 | cluster=3.299937 | spatial=0.000000 | SC=off | SNF=off | effC=13.953 | gradC=0.000e+00
epoch 006/050 | total=7.816809 | rec=0.154253 | mgcl=7.662556 | cluster=3.299252 | spatial=0.000000 | SC=off | SNF=off | effC=13.961 | gradC=0.000e+00
epoch 007/050 | total=7.808719 | rec=0.146611 | mgcl=7.662108 | cluster=3.298657 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=0.000e+00
epoch 008/050 | total=7.800929 | rec=0.139332 | mgcl=7.661596 | cluster=3.298143 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=0.000e+00
epoch 009/050 | total=7.793369 | rec=0.132402 | mgcl=7.660967 | cluster=3.297704 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=0.000e+00
epoch 010/050 | total=7.785977 | rec=0.125803 | mgcl=7.660174 | cluster=3.297333 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=0.000e+00
epoch 011/050 | total=17.669752 | rec=0.119521 | mgcl=7.659147 | cluster=3.297028 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=3.686e-02
epoch 012/050 | total=17.661337 | rec=0.113546 | mgcl=7.657787 | cluster=3.296668 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=3.102e-02
epoch 013/050 | total=17.652794 | rec=0.107863 | mgcl=7.655986 | cluster=3.296315 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.392e-02
epoch 014/050 | total=17.644276 | rec=0.102467 | mgcl=7.653594 | cluster=3.296072 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.737e-02
epoch 015/050 | total=17.635611 | rec=0.097350 | mgcl=7.650402 | cluster=3.295953 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.254e-02

In [12]:
# 汇总
import json, pandas as pd

rows = []
for name in ["e185_cl03", "e185_cl10", "e185_cl30", "e185_dim64", "e185_dim128"]:
    p = f"results/{name}/metrics.json"
    try:
        with open(p) as f:
            d = json.load(f)
        rows.append({
            "config": name,
            "fine_dim": d["fine_dim"],
            "lambda_cluster": d["loss_history"][-1]["lambda_cluster"],
            "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
            "ARI": round(d["ARI"], 4),
            "NMI": round(d["NMI"], 4),
        })
    except FileNotFoundError:
        rows.append({"config": name, "status": "未完成"})

print("\n===== E18.5 参数扫描结果 =====")
print(pd.DataFrame(rows).to_string(index=False))

===== E18.5 参数扫描结果 =====
     config  fine_dim  lambda_cluster   effC    ARI    NMI
  e185_cl03        32             0.3 13.998 0.2181 0.2004
  e185_cl10        32             1.0 13.993 0.2325 0.2269
  e185_cl30        32             3.0 13.971 0.2120 0.2799
 e185_dim64        64             1.0 13.999 0.2705 0.3727
e185_dim128       128             1.0 13.989 0.2840 0.4334

In [13]:
import json
with open("/content/SpaMGCL/SpaMGCL/results/e185_dim128/metrics.json") as f:
    d = json.load(f)

for k in ["cluster_argmax"]:
    print(k, round(d["candidate_metrics"][k]["ARI"], 4), round(d["candidate_metrics"][k]["NMI"], 4))
for k in ["weighted_views", "mean_views", "global", "concat_views"]:
    print(k, round(d["candidate_metrics"][k]["ARI"], 4), round(d["candidate_metrics"][k]["NMI"], 4))
for k in ["mean_z", "concat_z"]:
    print(k, round(d["representation_metrics"][k]["ARI"], 4), round(d["representation_metrics"][k]["NMI"], 4))
for k in ["rna_spatial", "rna_feature", "atac_spatial", "atac_feature"]:
    print(k, round(d["representation_metrics"]["z_views"][k]["ARI"], 4), round(d["representation_metrics"]["z_views"][k]["NMI"], 4))

cluster_argmax 0.284 0.4334
weighted_views 0.3553 0.5047
mean_views 0.335 0.4898
global 0.3298 0.448
concat_views 0.3298 0.4921
mean_z 0.3096 0.4594
concat_z 0.3375 0.4986
rna_spatial 0.2773 0.4479
rna_feature 0.2252 0.3922
atac_spatial 0.3765 0.4135
atac_feature 0.2828 0.4477

In [18]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_dim128.yaml") as f:
    base = yaml.safe_load(f)

variants = {
    "e185_dim256":  {"model": {"fine_dim": 256}},
    "e185_spk5":    {"graphs": {"spatial": {"k": 5}}},
    "e185_ep100":   {"training": {"epochs": 100}, "experiment": {"epochs": 100}},
    "e185_hid64":   {"model": {"gcn_hidden_dim": 64}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/e185_dim256 results/e185_spk5 results/e185_ep100 results/e185_hid64

!python experiments/run_exp.py --config configs/e185_dim256.yaml
!python experiments/run_exp.py --config configs/e185_spk5.yaml
!python experiments/run_exp.py --config configs/e185_ep100.yaml
!python experiments/run_exp.py --config configs/e185_hid64.yaml

rows = [{
    "config": "e185_dim128 (基准)",
    "fine_dim": 128, "spatial_k": 3, "epochs": 50, "hid": 32,
    "ARI": 0.2840, "NMI": 0.4334,
}]
for name in ["e185_dim256", "e185_spk5", "e185_ep100", "e185_hid64"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "fine_dim": d["fine_dim"],
        "spatial_k": d["data"].get("spatial_k", "-"),
        "epochs": d["epochs"],
        "hid": "-",
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 e185_dim256
生成 e185_spk5
生成 e185_ep100
生成 e185_hid64
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.832512 | rec=0.154364 | mgcl=7.678148 | cluster=3.296766 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 002/050 | total=7.793888 | rec=0.135850 | mgcl=7.658038 | cluster=3.296433 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=0.000e+00
epoch 003/050 | total=7.750212 | rec=0.120059 | mgcl=7.630152 | cluster=3.296210 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 004/050 | total=7.688490 | rec=0.107056 | mgcl=7.581434 | cluster=3.296063 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 005/050 | total=7.599078 | rec=0.097341 | mgcl=7.501737 | cluster=3.295962 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 006/050 | total=7.546188 | rec=0.091093 | mgcl=7.455095 | cluster=3.295907 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 007/050 | total=7.578012 | rec=0.087883 | mgcl=7.490129 | cluster=3.295883 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=0.000e+00
epoch 008/050 | total=7.453537 | rec=0.086010 | mgcl=7.367527 | cluster=3.295881 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=0.000e+00
epoch 009/050 | total=7.434268 | rec=0.083931 | mgcl=7.350338 | cluster=3.295892 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=0.000e+00
epoch 010/050 | total=7.363864 | rec=0.081576 | mgcl=7.282288 | cluster=3.295908 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=0.000e+00
epoch 011/050 | total=10.574900 | rec=0.079270 | mgcl=7.199705 | cluster=3.295924 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.189e-03
epoch 012/050 | total=10.521774 | rec=0.077202 | mgcl=7.148679 | cluster=3.295893 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.469e-03
epoch 013/050 | total=10.436885 | rec=0.075120 | mgcl=7.066068 | cluster=3.295697 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.958e-03
epoch 014/050 | total=10.364316 | rec=0.073516 | mgcl=6.995680 | cluster=3.295120 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.021e-03
epoch 015/050 | total=10.319751 | rec=0.072255 | mgcl=6.953514 | cluster=3.293981 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.444e-03
epoch 016/050 | total=10.243833 | rec=0.070937 | mgcl=6.880938 | cluster=3.291957 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.016e-02
epoch 017/050 | total=10.177193 | rec=0.069560 | mgcl=6.818834 | cluster=3.288799 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.307e-02
epoch 018/050 | total=10.114902 | rec=0.068152 | mgcl=6.762489 | cluster=3.284262 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.618e-02
epoch 019/050 | total=10.054420 | rec=0.066787 | mgcl=6.709506 | cluster=3.278128 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=1.939e-02
epoch 020/050 | total=9.995490 | rec=0.065467 | mgcl=6.659805 | cluster=3.270218 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=2.245e-02
epoch 021/050 | total=9.934224 | rec=0.064165 | mgcl=6.609739 | cluster=3.260320 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.519e-02
epoch 022/050 | total=9.872136 | rec=0.062916 | mgcl=6.561094 | cluster=3.248126 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=2.764e-02
epoch 023/050 | total=9.817233 | rec=0.061679 | mgcl=6.522285 | cluster=3.233269 | spatial=0.000000 | SC=off | SNF=off | effC=13.988 | gradC=3.001e-02
epoch 024/050 | total=9.759125 | rec=0.060399 | mgcl=6.483086 | cluster=3.215639 | spatial=0.000000 | SC=off | SNF=off | effC=13.983 | gradC=3.243e-02
epoch 025/050 | total=9.701479 | rec=0.059080 | mgcl=6.446878 | cluster=3.195522 | spatial=0.000000 | SC=off | SNF=off | effC=13.975 | gradC=3.453e-02
epoch 026/050 | total=9.643194 | rec=0.057767 | mgcl=6.412001 | cluster=3.173427 | spatial=0.000000 | SC=off | SNF=off | effC=13.969 | gradC=3.562e-02
epoch 027/050 | total=9.585288 | rec=0.056466 | mgcl=6.378618 | cluster=3.150204 | spatial=0.000000 | SC=off | SNF=off | effC=13.965 | gradC=3.544e-02
epoch 028/050 | total=9.530333 | rec=0.055153 | mgcl=6.348341 | cluster=3.126838 | spatial=0.000000 | SC=off | SNF=off | effC=13.965 | gradC=3.394e-02
epoch 029/050 | total=9.478460 | rec=0.053861 | mgcl=6.320354 | cluster=3.104245 | spatial=0.000000 | SC=off | SNF=off | effC=13.971 | gradC=3.117e-02
epoch 030/050 | total=9.426003 | rec=0.052586 | mgcl=6.290323 | cluster=3.083094 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=2.746e-02
epoch 031/050 | total=9.381388 | rec=0.051306 | mgcl=6.266105 | cluster=3.063977 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.365e-02
epoch 032/050 | total=9.337946 | rec=0.050047 | mgcl=6.240784 | cluster=3.047115 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.064e-02
epoch 033/050 | total=9.295447 | rec=0.048797 | mgcl=6.214252 | cluster=3.032398 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.919e-02
epoch 034/050 | total=9.259591 | rec=0.047549 | mgcl=6.192599 | cluster=3.019444 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=1.921e-02
epoch 035/050 | total=9.228082 | rec=0.046323 | mgcl=6.174190 | cluster=3.007569 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=1.987e-02
epoch 036/050 | total=9.193678 | rec=0.045100 | mgcl=6.152457 | cluster=2.996121 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=2.070e-02
epoch 037/050 | total=9.160725 | rec=0.043894 | mgcl=6.132198 | cluster=2.984632 | spatial=0.000000 | SC=off | SNF=off | effC=13.975 | gradC=2.127e-02
epoch 038/050 | total=9.125803 | rec=0.042689 | mgcl=6.110200 | cluster=2.972913 | spatial=0.000000 | SC=off | SNF=off | effC=13.972 | gradC=2.177e-02
epoch 039/050 | total=9.093626 | rec=0.041503 | mgcl=6.091250 | cluster=2.960873 | spatial=0.000000 | SC=off | SNF=off | effC=13.970 | gradC=2.234e-02
epoch 040/050 | total=9.065272 | rec=0.040332 | mgcl=6.076425 | cluster=2.948515 | spatial=0.000000 | SC=off | SNF=off | effC=13.970 | gradC=2.315e-02
epoch 041/050 | total=9.034931 | rec=0.039175 | mgcl=6.059901 | cluster=2.935854 | spatial=0.000000 | SC=off | SNF=off | effC=13.969 | gradC=2.414e-02
epoch 042/050 | total=9.001940 | rec=0.038066 | mgcl=6.040821 | cluster=2.923054 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=2.499e-02
epoch 043/050 | total=8.972317 | rec=0.037001 | mgcl=6.025205 | cluster=2.910110 | spatial=0.000000 | SC=off | SNF=off | effC=13.966 | gradC=2.560e-02
epoch 044/050 | total=8.943077 | rec=0.035955 | mgcl=6.010064 | cluster=2.897059 | spatial=0.000000 | SC=off | SNF=off | effC=13.963 | gradC=2.592e-02
epoch 045/050 | total=8.914513 | rec=0.034936 | mgcl=5.995684 | cluster=2.883893 | spatial=0.000000 | SC=off | SNF=off | effC=13.960 | gradC=2.591e-02
epoch 046/050 | total=8.885505 | rec=0.033958 | mgcl=5.980977 | cluster=2.870570 | spatial=0.000000 | SC=off | SNF=off | effC=13.958 | gradC=2.582e-02
epoch 047/050 | total=8.857853 | rec=0.033017 | mgcl=5.967679 | cluster=2.857158 | spatial=0.000000 | SC=off | SNF=off | effC=13.958 | gradC=2.550e-02
epoch 048/050 | total=8.830259 | rec=0.032068 | mgcl=5.954554 | cluster=2.843637 | spatial=0.000000 | SC=off | SNF=off | effC=13.957 | gradC=2.476e-02
epoch 049/050 | total=8.801547 | rec=0.031155 | mgcl=5.940153 | cluster=2.830239 | spatial=0.000000 | SC=off | SNF=off | effC=13.956 | gradC=2.390e-02
epoch 050/050 | total=8.772551 | rec=0.030275 | mgcl=5.925207 | cluster=2.817069 | spatial=0.000000 | SC=off | SNF=off | effC=13.953 | gradC=2.325e-02
ARI=0.298228 | NMI=0.468623
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_dim256
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_dim256/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_dim256/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=12406
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.807449 | rec=0.139239 | mgcl=7.668211 | cluster=3.298089 | spatial=0.000000 | SC=off | SNF=off | effC=13.977 | gradC=0.000e+00
epoch 002/050 | total=7.786852 | rec=0.126689 | mgcl=7.660162 | cluster=3.297597 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=7.767997 | rec=0.115666 | mgcl=7.652330 | cluster=3.297182 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=7.745534 | rec=0.106021 | mgcl=7.639513 | cluster=3.296844 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=7.714508 | rec=0.097654 | mgcl=7.616854 | cluster=3.296564 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=7.670294 | rec=0.090527 | mgcl=7.579767 | cluster=3.296335 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=7.614194 | rec=0.084599 | mgcl=7.529596 | cluster=3.296160 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=7.562561 | rec=0.079796 | mgcl=7.482765 | cluster=3.296037 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=7.511941 | rec=0.076032 | mgcl=7.435910 | cluster=3.295961 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=7.456131 | rec=0.073194 | mgcl=7.382937 | cluster=3.295921 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=10.716268 | rec=0.071166 | mgcl=7.349195 | cluster=3.295907 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.740e-03
epoch 012/050 | total=10.699868 | rec=0.069755 | mgcl=7.334234 | cluster=3.295880 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.136e-03
epoch 013/050 | total=10.641309 | rec=0.068753 | mgcl=7.276676 | cluster=3.295879 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.005e-03
epoch 014/050 | total=10.606012 | rec=0.068004 | mgcl=7.242228 | cluster=3.295781 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.441e-03
epoch 015/050 | total=10.545812 | rec=0.067279 | mgcl=7.182913 | cluster=3.295619 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.586e-03
epoch 016/050 | total=10.505491 | rec=0.066556 | mgcl=7.143612 | cluster=3.295323 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.432e-03
epoch 017/050 | total=10.446287 | rec=0.065932 | mgcl=7.085558 | cluster=3.294797 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.536e-03
epoch 018/050 | total=10.385478 | rec=0.065332 | mgcl=7.026161 | cluster=3.293986 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=5.770e-03
epoch 019/050 | total=10.314123 | rec=0.064730 | mgcl=6.956549 | cluster=3.292844 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=7.135e-03
epoch 020/050 | total=10.258444 | rec=0.064202 | mgcl=6.902922 | cluster=3.291319 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=8.588e-03
epoch 021/050 | total=10.189728 | rec=0.063742 | mgcl=6.836654 | cluster=3.289332 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.006e-02
epoch 022/050 | total=10.149770 | rec=0.063325 | mgcl=6.799599 | cluster=3.286846 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.152e-02
epoch 023/050 | total=10.103135 | rec=0.062979 | mgcl=6.756403 | cluster=3.283752 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.305e-02
epoch 024/050 | total=10.046359 | rec=0.062674 | mgcl=6.703705 | cluster=3.279979 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.464e-02
epoch 025/050 | total=10.000843 | rec=0.062365 | mgcl=6.663292 | cluster=3.275186 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.630e-02
epoch 026/050 | total=9.949336 | rec=0.062052 | mgcl=6.618191 | cluster=3.269094 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.803e-02
epoch 027/050 | total=9.897658 | rec=0.061742 | mgcl=6.574373 | cluster=3.261543 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.993e-02
epoch 028/050 | total=9.857927 | rec=0.061445 | mgcl=6.544111 | cluster=3.252371 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.201e-02
epoch 029/050 | total=9.806614 | rec=0.061145 | mgcl=6.504035 | cluster=3.241435 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.414e-02
epoch 030/050 | total=9.762783 | rec=0.060815 | mgcl=6.473266 | cluster=3.228702 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.629e-02
epoch 031/050 | total=9.712543 | rec=0.060463 | mgcl=6.437851 | cluster=3.214229 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=2.840e-02
epoch 032/050 | total=9.670638 | rec=0.060091 | mgcl=6.412440 | cluster=3.198107 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=3.042e-02
epoch 033/050 | total=9.626814 | rec=0.059699 | mgcl=6.386438 | cluster=3.180676 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=3.228e-02
epoch 034/050 | total=9.585279 | rec=0.059303 | mgcl=6.363539 | cluster=3.162437 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=3.376e-02
epoch 035/050 | total=9.543160 | rec=0.058898 | mgcl=6.340353 | cluster=3.143909 | spatial=0.000000 | SC=off | SNF=off | effC=13.983 | gradC=3.455e-02
epoch 036/050 | total=9.503241 | rec=0.058469 | mgcl=6.319308 | cluster=3.125464 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=3.425e-02
epoch 037/050 | total=9.465336 | rec=0.058025 | mgcl=6.299834 | cluster=3.107476 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=3.280e-02
epoch 038/050 | total=9.426363 | rec=0.057581 | mgcl=6.278353 | cluster=3.090429 | spatial=0.000000 | SC=off | SNF=off | effC=13.985 | gradC=3.044e-02
epoch 039/050 | total=9.393109 | rec=0.057128 | mgcl=6.261371 | cluster=3.074610 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=2.739e-02
epoch 040/050 | total=9.361075 | rec=0.056660 | mgcl=6.244277 | cluster=3.060137 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=2.373e-02
epoch 041/050 | total=9.329872 | rec=0.056177 | mgcl=6.226520 | cluster=3.047175 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.997e-02
epoch 042/050 | total=9.301546 | rec=0.055681 | mgcl=6.210030 | cluster=3.035836 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.676e-02
epoch 043/050 | total=9.275442 | rec=0.055173 | mgcl=6.194251 | cluster=3.026019 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=1.435e-02
epoch 044/050 | total=9.252557 | rec=0.054651 | mgcl=6.180396 | cluster=3.017510 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=1.270e-02
epoch 045/050 | total=9.229239 | rec=0.054111 | mgcl=6.165019 | cluster=3.010110 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=1.172e-02
epoch 046/050 | total=9.209169 | rec=0.053537 | mgcl=6.152060 | cluster=3.003572 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=1.126e-02
epoch 047/050 | total=9.187397 | rec=0.052923 | mgcl=6.136787 | cluster=2.997687 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=1.128e-02
epoch 048/050 | total=9.168453 | rec=0.052272 | mgcl=6.123917 | cluster=2.992265 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=1.179e-02
epoch 049/050 | total=9.149045 | rec=0.051587 | mgcl=6.110329 | cluster=2.987130 | spatial=0.000000 | SC=off | SNF=off | effC=13.983 | gradC=1.277e-02
epoch 050/050 | total=9.130394 | rec=0.050876 | mgcl=6.097382 | cluster=2.982136 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=1.413e-02
ARI=0.282006 | NMI=0.452726
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_spk5
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_spk5/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_spk5/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/100 | total=7.829533 | rec=0.160812 | mgcl=7.668721 | cluster=3.298100 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/100 | total=7.806659 | rec=0.147007 | mgcl=7.659652 | cluster=3.297613 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/100 | total=7.785351 | rec=0.134802 | mgcl=7.650549 | cluster=3.297199 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/100 | total=7.759805 | rec=0.124008 | mgcl=7.635797 | cluster=3.296858 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/100 | total=7.725086 | rec=0.114519 | mgcl=7.610567 | cluster=3.296576 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/100 | total=7.677305 | rec=0.106296 | mgcl=7.571008 | cluster=3.296344 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/100 | total=7.621832 | rec=0.099297 | mgcl=7.522535 | cluster=3.296165 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/100 | total=7.572734 | rec=0.093481 | mgcl=7.479253 | cluster=3.296041 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/100 | total=7.524709 | rec=0.088807 | mgcl=7.435902 | cluster=3.295964 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/100 | total=7.484998 | rec=0.085213 | mgcl=7.399785 | cluster=3.295923 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/100 | total=10.735395 | rec=0.082541 | mgcl=7.356945 | cluster=3.295910 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.784e-03
epoch 012/100 | total=10.700605 | rec=0.080597 | mgcl=7.324131 | cluster=3.295878 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.185e-03
epoch 013/100 | total=10.671581 | rec=0.079170 | mgcl=7.296543 | cluster=3.295868 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.158e-03
epoch 014/100 | total=10.617969 | rec=0.078000 | mgcl=7.244226 | cluster=3.295743 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.786e-03
epoch 015/100 | total=10.583211 | rec=0.077040 | mgcl=7.210661 | cluster=3.295510 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.104e-03

In [19]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_dim128.yaml") as f:
    base = yaml.safe_load(f)

variants = {
    "e185_dim128_mgcl05":  {"loss": {"lambda_mgcl": 0.5}},
    "e185_dim128_mgcl2":   {"loss": {"lambda_mgcl": 2.0}},
    "e185_dim128_t05":     {"model": {"cluster_temperature": 0.5}},
    "e185_dim128_t2":      {"model": {"cluster_temperature": 2.0}},
    "e185_dim128_featk10": {"graphs": {"feature": {"k": 10}}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/e185_dim128_mgcl05 results/e185_dim128_mgcl2 \
       results/e185_dim128_t05 results/e185_dim128_t2 results/e185_dim128_featk10

!python experiments/run_exp.py --config configs/e185_dim128_mgcl05.yaml
!python experiments/run_exp.py --config configs/e185_dim128_mgcl2.yaml
!python experiments/run_exp.py --config configs/e185_dim128_t05.yaml
!python experiments/run_exp.py --config configs/e185_dim128_t2.yaml
!python experiments/run_exp.py --config configs/e185_dim128_featk10.yaml

rows = [{"config": "e185_dim128 (基准)", "ARI": 0.2840, "NMI": 0.4334}]
for name in ["e185_dim128_mgcl05", "e185_dim128_mgcl2",
             "e185_dim128_t05", "e185_dim128_t2", "e185_dim128_featk10"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
        "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 e185_dim128_mgcl05
生成 e185_dim128_mgcl2
生成 e185_dim128_t05
生成 e185_dim128_t2
生成 e185_dim128_featk10
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=3.995173 | rec=0.160812 | mgcl=7.668722 | cluster=3.298100 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=3.976383 | rec=0.146324 | mgcl=7.660118 | cluster=3.297601 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=3.959701 | rec=0.133662 | mgcl=7.652078 | cluster=3.297187 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=3.942121 | rec=0.122449 | mgcl=7.639344 | cluster=3.296853 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=3.921176 | rec=0.112455 | mgcl=7.617441 | cluster=3.296577 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=3.894971 | rec=0.103620 | mgcl=7.582703 | cluster=3.296350 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=3.865183 | rec=0.095984 | mgcl=7.538396 | cluster=3.296172 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=3.838515 | rec=0.089607 | mgcl=7.497816 | cluster=3.296046 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=3.811831 | rec=0.084555 | mgcl=7.454551 | cluster=3.295968 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=3.791934 | rec=0.080740 | mgcl=7.422386 | cluster=3.295928 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=7.072299 | rec=0.077949 | mgcl=7.396868 | cluster=3.295916 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.885e-03
epoch 012/050 | total=7.045320 | rec=0.075823 | mgcl=7.347208 | cluster=3.295892 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.417e-03
epoch 013/050 | total=7.036914 | rec=0.074043 | mgcl=7.333981 | cluster=3.295880 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.262e-03
epoch 014/050 | total=7.008954 | rec=0.072386 | mgcl=7.281578 | cluster=3.295779 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.674e-03
epoch 015/050 | total=6.992319 | rec=0.070912 | mgcl=7.251590 | cluster=3.295612 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.854e-03
epoch 016/050 | total=6.966110 | rec=0.069382 | mgcl=7.202843 | cluster=3.295307 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.525e-03
epoch 017/050 | total=6.950023 | rec=0.067885 | mgcl=7.174713 | cluster=3.294782 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.588e-03
epoch 018/050 | total=6.918416 | rec=0.066553 | mgcl=7.115824 | cluster=3.293951 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=5.826e-03
epoch 019/050 | total=6.892653 | rec=0.065394 | mgcl=7.069004 | cluster=3.292757 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=7.170e-03
epoch 020/050 | total=6.860049 | rec=0.064396 | mgcl=7.009024 | cluster=3.291141 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=8.625e-03
epoch 021/050 | total=6.828078 | rec=0.063520 | mgcl=6.951036 | cluster=3.289040 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.010e-02
epoch 022/050 | total=6.796414 | rec=0.062717 | mgcl=6.894627 | cluster=3.286384 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.157e-02
epoch 023/050 | total=6.766568 | rec=0.061971 | mgcl=6.843019 | cluster=3.283087 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.306e-02
epoch 024/050 | total=6.743821 | rec=0.061284 | mgcl=6.806952 | cluster=3.279061 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.451e-02
epoch 025/050 | total=6.715307 | rec=0.060657 | mgcl=6.761261 | cluster=3.274019 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.609e-02
epoch 026/050 | total=6.682017 | rec=0.060055 | mgcl=6.708548 | cluster=3.267689 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.779e-02
epoch 027/050 | total=6.651319 | rec=0.059502 | mgcl=6.664274 | cluster=3.259679 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.968e-02
epoch 028/050 | total=6.622013 | rec=0.059015 | mgcl=6.626596 | cluster=3.249700 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.181e-02
epoch 029/050 | total=6.585743 | rec=0.058569 | mgcl=6.579208 | cluster=3.237569 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=2.417e-02
epoch 030/050 | total=6.557759 | rec=0.058141 | mgcl=6.552892 | cluster=3.223172 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=2.668e-02
epoch 031/050 | total=6.518656 | rec=0.057709 | mgcl=6.508505 | cluster=3.206694 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=2.907e-02
epoch 032/050 | total=6.485472 | rec=0.057277 | mgcl=6.479750 | cluster=3.188319 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=3.124e-02
epoch 033/050 | total=6.450053 | rec=0.056845 | mgcl=6.449272 | cluster=3.168572 | spatial=0.000000 | SC=off | SNF=off | effC=13.980 | gradC=3.297e-02
epoch 034/050 | total=6.415481 | rec=0.056421 | mgcl=6.421932 | cluster=3.148093 | spatial=0.000000 | SC=off | SNF=off | effC=13.975 | gradC=3.397e-02
epoch 035/050 | total=6.381592 | rec=0.056006 | mgcl=6.396385 | cluster=3.127393 | spatial=0.000000 | SC=off | SNF=off | effC=13.972 | gradC=3.399e-02
epoch 036/050 | total=6.348901 | rec=0.055589 | mgcl=6.372671 | cluster=3.106977 | spatial=0.000000 | SC=off | SNF=off | effC=13.973 | gradC=3.296e-02
epoch 037/050 | total=6.317007 | rec=0.055168 | mgcl=6.349108 | cluster=3.087286 | spatial=0.000000 | SC=off | SNF=off | effC=13.978 | gradC=3.090e-02
epoch 038/050 | total=6.287902 | rec=0.054749 | mgcl=6.328775 | cluster=3.068766 | spatial=0.000000 | SC=off | SNF=off | effC=13.985 | gradC=2.819e-02
epoch 039/050 | total=6.259981 | rec=0.054326 | mgcl=6.307656 | cluster=3.051826 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.540e-02
epoch 040/050 | total=6.235119 | rec=0.053885 | mgcl=6.289041 | cluster=3.036714 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=2.303e-02
epoch 041/050 | total=6.211187 | rec=0.053425 | mgcl=6.268569 | cluster=3.023479 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.124e-02
epoch 042/050 | total=6.190534 | rec=0.052952 | mgcl=6.251228 | cluster=3.011967 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.990e-02
epoch 043/050 | total=6.171453 | rec=0.052459 | mgcl=6.234148 | cluster=3.001920 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=1.877e-02
epoch 044/050 | total=6.153076 | rec=0.051932 | mgcl=6.216089 | cluster=2.993099 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=1.769e-02
epoch 045/050 | total=6.136176 | rec=0.051363 | mgcl=6.199074 | cluster=2.985276 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=1.664e-02
epoch 046/050 | total=6.121570 | rec=0.050743 | mgcl=6.185216 | cluster=2.978219 | spatial=0.000000 | SC=off | SNF=off | effC=13.983 | gradC=1.566e-02
epoch 047/050 | total=6.106181 | rec=0.050072 | mgcl=6.168661 | cluster=2.971778 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=1.499e-02
epoch 048/050 | total=6.091857 | rec=0.049356 | mgcl=6.153336 | cluster=2.965833 | spatial=0.000000 | SC=off | SNF=off | effC=13.978 | gradC=1.473e-02
epoch 049/050 | total=6.078316 | rec=0.048597 | mgcl=6.138921 | cluster=2.960258 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=1.496e-02
epoch 050/050 | total=6.064713 | rec=0.047811 | mgcl=6.123904 | cluster=2.954950 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=1.566e-02
ARI=0.241630 | NMI=0.406790
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_dim128_mgcl05
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_dim128_mgcl05/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_dim128_mgcl05/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=15.498254 | rec=0.160812 | mgcl=7.668721 | cluster=3.298100 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=15.466587 | rec=0.147807 | mgcl=7.659390 | cluster=3.297628 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=15.435402 | rec=0.136209 | mgcl=7.649597 | cluster=3.297212 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=15.392783 | rec=0.126034 | mgcl=7.633375 | cluster=3.296865 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=15.328312 | rec=0.117320 | mgcl=7.605496 | cluster=3.296576 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=15.234179 | rec=0.109966 | mgcl=7.562107 | cluster=3.296342 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=15.124910 | rec=0.103796 | mgcl=7.510557 | cluster=3.296164 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=15.030099 | rec=0.098648 | mgcl=7.465725 | cluster=3.296040 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=14.935410 | rec=0.094429 | mgcl=7.420490 | cluster=3.295963 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=14.848242 | rec=0.091128 | mgcl=7.378557 | cluster=3.295922 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=18.059036 | rec=0.088633 | mgcl=7.337247 | cluster=3.295907 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.753e-03
epoch 012/050 | total=17.986702 | rec=0.086859 | mgcl=7.301986 | cluster=3.295869 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.061e-03
epoch 013/050 | total=17.927704 | rec=0.085611 | mgcl=7.273116 | cluster=3.295861 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.106e-03
epoch 014/050 | total=17.818382 | rec=0.084694 | mgcl=7.218990 | cluster=3.295708 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.950e-03
epoch 015/050 | total=17.740694 | rec=0.084025 | mgcl=7.180632 | cluster=3.295405 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.521e-03
epoch 016/050 | total=17.660305 | rec=0.083461 | mgcl=7.141004 | cluster=3.294836 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.972e-03
epoch 017/050 | total=17.541069 | rec=0.082895 | mgcl=7.082151 | cluster=3.293872 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=6.695e-03
epoch 018/050 | total=17.424387 | rec=0.082358 | mgcl=7.024804 | cluster=3.292421 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=8.500e-03
epoch 019/050 | total=17.298630 | rec=0.081839 | mgcl=6.963177 | cluster=3.290438 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.029e-02
epoch 020/050 | total=17.164808 | rec=0.081312 | mgcl=6.897800 | cluster=3.287895 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.201e-02
epoch 021/050 | total=17.063625 | rec=0.080801 | mgcl=6.849015 | cluster=3.284795 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.360e-02
epoch 022/050 | total=16.959324 | rec=0.080324 | mgcl=6.798946 | cluster=3.281108 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.507e-02
epoch 023/050 | total=16.859325 | rec=0.079857 | mgcl=6.751311 | cluster=3.276847 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.637e-02
epoch 024/050 | total=16.749870 | rec=0.079462 | mgcl=6.699274 | cluster=3.271859 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.759e-02
epoch 025/050 | total=16.666689 | rec=0.079065 | mgcl=6.660811 | cluster=3.266002 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.875e-02
epoch 026/050 | total=16.570333 | rec=0.078642 | mgcl=6.616305 | cluster=3.259081 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.984e-02
epoch 027/050 | total=16.477005 | rec=0.078222 | mgcl=6.573900 | cluster=3.250982 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.092e-02
epoch 028/050 | total=16.395624 | rec=0.077801 | mgcl=6.538033 | cluster=3.241756 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.203e-02
epoch 029/050 | total=16.318933 | rec=0.077400 | mgcl=6.505012 | cluster=3.231511 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.303e-02
epoch 030/050 | total=16.223867 | rec=0.077014 | mgcl=6.463322 | cluster=3.220210 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.395e-02
epoch 031/050 | total=16.157242 | rec=0.076614 | mgcl=6.436367 | cluster=3.207892 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.485e-02
epoch 032/050 | total=16.078581 | rec=0.076180 | mgcl=6.403837 | cluster=3.194728 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=2.563e-02
epoch 033/050 | total=16.014683 | rec=0.075704 | mgcl=6.379060 | cluster=3.180858 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.631e-02
epoch 034/050 | total=15.944468 | rec=0.075196 | mgcl=6.351362 | cluster=3.166548 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=2.675e-02
epoch 035/050 | total=15.884701 | rec=0.074662 | mgcl=6.328986 | cluster=3.152068 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=2.681e-02
epoch 036/050 | total=15.828653 | rec=0.074103 | mgcl=6.308447 | cluster=3.137656 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.652e-02
epoch 037/050 | total=15.768803 | rec=0.073538 | mgcl=6.285862 | cluster=3.123539 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.573e-02
epoch 038/050 | total=15.715967 | rec=0.072962 | mgcl=6.266551 | cluster=3.109902 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=2.441e-02
epoch 039/050 | total=15.662455 | rec=0.072370 | mgcl=6.246617 | cluster=3.096851 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.279e-02
epoch 040/050 | total=15.613205 | rec=0.071764 | mgcl=6.228466 | cluster=3.084510 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=2.097e-02
epoch 041/050 | total=15.565235 | rec=0.071134 | mgcl=6.210548 | cluster=3.073005 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.910e-02
epoch 042/050 | total=15.518885 | rec=0.070476 | mgcl=6.193013 | cluster=3.062382 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.729e-02
epoch 043/050 | total=15.476308 | rec=0.069799 | mgcl=6.176946 | cluster=3.052616 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=1.554e-02
epoch 044/050 | total=15.433979 | rec=0.069106 | mgcl=6.160579 | cluster=3.043715 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.413e-02
epoch 045/050 | total=15.393112 | rec=0.068396 | mgcl=6.144560 | cluster=3.035596 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=1.319e-02
epoch 046/050 | total=15.356850 | rec=0.067664 | mgcl=6.130511 | cluster=3.028165 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=1.276e-02
epoch 047/050 | total=15.320214 | rec=0.066904 | mgcl=6.116005 | cluster=3.021301 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=1.277e-02
epoch 048/050 | total=15.285408 | rec=0.066117 | mgcl=6.102212 | cluster=3.014866 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=1.313e-02
epoch 049/050 | total=15.249856 | rec=0.065297 | mgcl=6.087920 | cluster=3.008719 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=1.378e-02
epoch 050/050 | total=15.218189 | rec=0.064455 | mgcl=6.075491 | cluster=3.002752 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=1.464e-02
ARI=0.359463 | NMI=0.417345
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_dim128_mgcl2
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_dim128_mgcl2/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_dim128_mgcl2/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.829534 | rec=0.160812 | mgcl=7.668722 | cluster=3.298072 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=7.806659 | rec=0.147007 | mgcl=7.659652 | cluster=3.297589 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=7.785350 | rec=0.134802 | mgcl=7.650548 | cluster=3.297181 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=7.759805 | rec=0.124008 | mgcl=7.635797 | cluster=3.296844 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=7.725085 | rec=0.114519 | mgcl=7.610567 | cluster=3.296565 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=7.677305 | rec=0.106296 | mgcl=7.571009 | cluster=3.296336 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=7.621832 | rec=0.099297 | mgcl=7.522535 | cluster=3.296161 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=7.572734 | rec=0.093481 | mgcl=7.479253 | cluster=3.296040 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=7.524693 | rec=0.088807 | mgcl=7.435886 | cluster=3.295965 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=7.484995 | rec=0.085214 | mgcl=7.399782 | cluster=3.295927 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=10.735399 | rec=0.082541 | mgcl=7.356945 | cluster=3.295914 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.876e-03
epoch 012/050 | total=10.700593 | rec=0.080597 | mgcl=7.324143 | cluster=3.295852 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.198e-03
epoch 013/050 | total=10.671477 | rec=0.079170 | mgcl=7.296550 | cluster=3.295756 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.853e-03
epoch 014/050 | total=10.617581 | rec=0.078001 | mgcl=7.244224 | cluster=3.295357 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.257e-03

In [20]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_dim128_t05.yaml") as f:
    base = yaml.safe_load(f)

variants = {
    "e185_t05_mgcl2":       {"loss": {"lambda_mgcl": 2.0}},
    "e185_t05_featk10":     {"graphs": {"feature": {"k": 10}}},
    "e185_t05_mgcl2_featk10": {"loss": {"lambda_mgcl": 2.0}, "graphs": {"feature": {"k": 10}}},
    "e185_t03":             {"model": {"cluster_temperature": 0.3}},
    "e185_t01":             {"model": {"cluster_temperature": 0.1}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/e185_t05_mgcl2 results/e185_t05_featk10 \
       results/e185_t05_mgcl2_featk10 results/e185_t03 results/e185_t01

!python experiments/run_exp.py --config configs/e185_t05_mgcl2.yaml
!python experiments/run_exp.py --config configs/e185_t05_featk10.yaml
!python experiments/run_exp.py --config configs/e185_t05_mgcl2_featk10.yaml
!python experiments/run_exp.py --config configs/e185_t03.yaml
!python experiments/run_exp.py --config configs/e185_t01.yaml

rows = [{"config": "e185_dim128_t05 (当前最佳)", "ARI": 0.4071, "NMI": 0.4401}]
for name in ["e185_t05_mgcl2", "e185_t05_featk10", "e185_t05_mgcl2_featk10",
             "e185_t03", "e185_t01"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
        "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 e185_t05_mgcl2
生成 e185_t05_featk10
生成 e185_t05_mgcl2_featk10
生成 e185_t03
生成 e185_t01
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=15.498254 | rec=0.160812 | mgcl=7.668721 | cluster=3.298072 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=15.466586 | rec=0.147807 | mgcl=7.659389 | cluster=3.297604 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=15.435402 | rec=0.136209 | mgcl=7.649597 | cluster=3.297194 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=15.392784 | rec=0.126034 | mgcl=7.633375 | cluster=3.296852 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=15.328312 | rec=0.117320 | mgcl=7.605496 | cluster=3.296566 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=15.234179 | rec=0.109966 | mgcl=7.562107 | cluster=3.296336 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=15.124910 | rec=0.103796 | mgcl=7.510557 | cluster=3.296160 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=15.030099 | rec=0.098648 | mgcl=7.465725 | cluster=3.296039 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=14.935405 | rec=0.094429 | mgcl=7.420488 | cluster=3.295965 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=14.848221 | rec=0.091128 | mgcl=7.378546 | cluster=3.295926 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=18.059046 | rec=0.088633 | mgcl=7.337250 | cluster=3.295912 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.851e-03
epoch 012/050 | total=17.986677 | rec=0.086859 | mgcl=7.301988 | cluster=3.295841 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.108e-03
epoch 013/050 | total=17.927570 | rec=0.085611 | mgcl=7.273123 | cluster=3.295714 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.046e-03
epoch 014/050 | total=17.817860 | rec=0.084694 | mgcl=7.218988 | cluster=3.295187 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.030e-03
epoch 015/050 | total=17.739342 | rec=0.084025 | mgcl=7.180643 | cluster=3.294031 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.035e-03
epoch 016/050 | total=17.657576 | rec=0.083462 | mgcl=7.141041 | cluster=3.292032 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.269e-02
epoch 017/050 | total=17.536343 | rec=0.082898 | mgcl=7.082214 | cluster=3.289016 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.656e-02
epoch 018/050 | total=17.417074 | rec=0.082364 | mgcl=7.024922 | cluster=3.284867 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.036e-02
epoch 019/050 | total=17.288145 | rec=0.081848 | mgcl=6.963377 | cluster=3.279543 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.390e-02
epoch 020/050 | total=17.150417 | rec=0.081325 | mgcl=6.898063 | cluster=3.272967 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.718e-02
epoch 021/050 | total=17.044579 | rec=0.080815 | mgcl=6.849343 | cluster=3.265079 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.016e-02
epoch 022/050 | total=16.934258 | rec=0.080339 | mgcl=6.799101 | cluster=3.255717 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.289e-02
epoch 023/050 | total=16.828018 | rec=0.079870 | mgcl=6.751673 | cluster=3.244802 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.534e-02
epoch 024/050 | total=16.710226 | rec=0.079470 | mgcl=6.699480 | cluster=3.231796 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.763e-02
epoch 025/050 | total=16.616945 | rec=0.079072 | mgcl=6.660788 | cluster=3.216298 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.975e-02
epoch 026/050 | total=16.510454 | rec=0.078654 | mgcl=6.616899 | cluster=3.198003 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.168e-02
epoch 027/050 | total=16.403618 | rec=0.078247 | mgcl=6.574235 | cluster=3.176899 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.342e-02
epoch 028/050 | total=16.308653 | rec=0.077850 | mgcl=6.538747 | cluster=3.153307 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.498e-02
epoch 029/050 | total=16.216444 | rec=0.077479 | mgcl=6.505544 | cluster=3.127876 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=4.618e-02
epoch 030/050 | total=16.109205 | rec=0.077123 | mgcl=6.465455 | cluster=3.101174 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=4.698e-02
epoch 031/050 | total=16.027977 | rec=0.076748 | mgcl=6.438716 | cluster=3.073796 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=4.739e-02
epoch 032/050 | total=15.934486 | rec=0.076333 | mgcl=6.405807 | cluster=3.046540 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=4.728e-02
epoch 033/050 | total=15.860627 | rec=0.075877 | mgcl=6.382334 | cluster=3.020082 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=4.660e-02
epoch 034/050 | total=15.778201 | rec=0.075397 | mgcl=6.353918 | cluster=2.994969 | spatial=0.000000 | SC=off | SNF=off | effC=13.980 | gradC=4.525e-02
epoch 035/050 | total=15.710722 | rec=0.074900 | mgcl=6.332175 | cluster=2.971471 | spatial=0.000000 | SC=off | SNF=off | effC=13.980 | gradC=4.317e-02
epoch 036/050 | total=15.645070 | rec=0.074388 | mgcl=6.310449 | cluster=2.949784 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=4.058e-02
epoch 037/050 | total=15.582007 | rec=0.073872 | mgcl=6.289114 | cluster=2.929909 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=3.759e-02
epoch 038/050 | total=15.522840 | rec=0.073344 | mgcl=6.268856 | cluster=2.911784 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=3.445e-02
epoch 039/050 | total=15.467878 | rec=0.072795 | mgcl=6.249897 | cluster=2.895289 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=3.177e-02
epoch 040/050 | total=15.415424 | rec=0.072218 | mgcl=6.231484 | cluster=2.880239 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=3.000e-02
epoch 041/050 | total=15.366020 | rec=0.071607 | mgcl=6.213975 | cluster=2.866462 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.939e-02
epoch 042/050 | total=15.315972 | rec=0.070957 | mgcl=6.195640 | cluster=2.853735 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=2.994e-02
epoch 043/050 | total=15.272100 | rec=0.070277 | mgcl=6.180053 | cluster=2.841717 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=3.136e-02
epoch 044/050 | total=15.225725 | rec=0.069570 | mgcl=6.163040 | cluster=2.830075 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=3.342e-02
epoch 045/050 | total=15.182802 | rec=0.068835 | mgcl=6.147688 | cluster=2.818592 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=3.591e-02
epoch 046/050 | total=15.141641 | rec=0.068065 | mgcl=6.133268 | cluster=2.807040 | spatial=0.000000 | SC=off | SNF=off | effC=13.972 | gradC=3.864e-02
epoch 047/050 | total=15.099669 | rec=0.067257 | mgcl=6.118630 | cluster=2.795152 | spatial=0.000000 | SC=off | SNF=off | effC=13.966 | gradC=4.148e-02
epoch 048/050 | total=15.059214 | rec=0.066416 | mgcl=6.105064 | cluster=2.782669 | spatial=0.000000 | SC=off | SNF=off | effC=13.960 | gradC=4.428e-02
epoch 049/050 | total=15.017154 | rec=0.065547 | mgcl=6.091106 | cluster=2.769394 | spatial=0.000000 | SC=off | SNF=off | effC=13.956 | gradC=4.691e-02
epoch 050/050 | total=14.976473 | rec=0.064662 | mgcl=6.078312 | cluster=2.755187 | spatial=0.000000 | SC=off | SNF=off | effC=13.952 | gradC=4.925e-02
ARI=0.455915 | NMI=0.441034
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl2
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl2/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl2/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=7.856833 | rec=0.187170 | mgcl=7.669663 | cluster=3.298096 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=7.830379 | rec=0.171911 | mgcl=7.658468 | cluster=3.297613 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=0.000e+00
epoch 003/050 | total=7.805126 | rec=0.158268 | mgcl=7.646858 | cluster=3.297202 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=7.774220 | rec=0.146100 | mgcl=7.628120 | cluster=3.296858 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=7.733190 | rec=0.135323 | mgcl=7.597866 | cluster=3.296572 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=0.000e+00
epoch 006/050 | total=7.680403 | rec=0.125878 | mgcl=7.554525 | cluster=3.296340 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=7.626087 | rec=0.117698 | mgcl=7.508389 | cluster=3.296163 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=7.580087 | rec=0.110751 | mgcl=7.469336 | cluster=3.296042 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=7.526442 | rec=0.105043 | mgcl=7.421400 | cluster=3.295968 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=7.476040 | rec=0.100553 | mgcl=7.375488 | cluster=3.295931 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=10.738239 | rec=0.097177 | mgcl=7.345143 | cluster=3.295918 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.944e-03
epoch 012/050 | total=10.703938 | rec=0.094699 | mgcl=7.313391 | cluster=3.295848 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.303e-03
epoch 013/050 | total=10.664160 | rec=0.092802 | mgcl=7.275648 | cluster=3.295709 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.346e-03
epoch 014/050 | total=10.622549 | rec=0.091224 | mgcl=7.236161 | cluster=3.295163 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.576e-03
epoch 015/050 | total=10.585859 | rec=0.089858 | mgcl=7.202028 | cluster=3.293973 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.782e-03
epoch 016/050 | total=10.545017 | rec=0.088576 | mgcl=7.164506 | cluster=3.291934 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.360e-02
epoch 017/050 | total=10.481819 | rec=0.087238 | mgcl=7.105762 | cluster=3.288819 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.775e-02
epoch 018/050 | total=10.429966 | rec=0.085975 | mgcl=7.059602 | cluster=3.284389 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.206e-02
epoch 019/050 | total=10.357073 | rec=0.084846 | mgcl=6.993799 | cluster=3.278427 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.638e-02
epoch 020/050 | total=10.291136 | rec=0.083793 | mgcl=6.936644 | cluster=3.270699 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.062e-02
epoch 021/050 | total=10.217930 | rec=0.082802 | mgcl=6.874164 | cluster=3.260964 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.469e-02
epoch 022/050 | total=10.156521 | rec=0.081947 | mgcl=6.825693 | cluster=3.248881 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=3.854e-02
epoch 023/050 | total=10.111816 | rec=0.081143 | mgcl=6.796593 | cluster=3.234081 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.222e-02
epoch 024/050 | total=10.030525 | rec=0.080432 | mgcl=6.734370 | cluster=3.215724 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=4.572e-02
epoch 025/050 | total=9.966000 | rec=0.079764 | mgcl=6.693062 | cluster=3.193174 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=4.905e-02
epoch 026/050 | total=9.895205 | rec=0.079124 | mgcl=6.649603 | cluster=3.166477 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=5.210e-02
epoch 027/050 | total=9.818733 | rec=0.078540 | mgcl=6.603827 | cluster=3.136366 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=5.470e-02
epoch 028/050 | total=9.752609 | rec=0.078044 | mgcl=6.570446 | cluster=3.104119 | spatial=0.000000 | SC=off | SNF=off | effC=13.972 | gradC=5.680e-02
epoch 029/050 | total=9.678779 | rec=0.077619 | mgcl=6.529934 | cluster=3.071225 | spatial=0.000000 | SC=off | SNF=off | effC=13.959 | gradC=5.802e-02
epoch 030/050 | total=9.619586 | rec=0.077215 | mgcl=6.503391 | cluster=3.038980 | spatial=0.000000 | SC=off | SNF=off | effC=13.947 | gradC=5.804e-02
epoch 031/050 | total=9.549986 | rec=0.076805 | mgcl=6.464909 | cluster=3.008272 | spatial=0.000000 | SC=off | SNF=off | effC=13.941 | gradC=5.642e-02
epoch 032/050 | total=9.496349 | rec=0.076376 | mgcl=6.440244 | cluster=2.979730 | spatial=0.000000 | SC=off | SNF=off | effC=13.943 | gradC=5.328e-02
epoch 033/050 | total=9.438133 | rec=0.075906 | mgcl=6.408473 | cluster=2.953755 | spatial=0.000000 | SC=off | SNF=off | effC=13.951 | gradC=4.895e-02
epoch 034/050 | total=9.390432 | rec=0.075404 | mgcl=6.384574 | cluster=2.930454 | spatial=0.000000 | SC=off | SNF=off | effC=13.964 | gradC=4.383e-02
epoch 035/050 | total=9.341616 | rec=0.074900 | mgcl=6.356813 | cluster=2.909903 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=3.858e-02
epoch 036/050 | total=9.302024 | rec=0.074409 | mgcl=6.335699 | cluster=2.891916 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=3.402e-02
epoch 037/050 | total=9.261168 | rec=0.073906 | mgcl=6.311108 | cluster=2.876155 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.096e-02
epoch 038/050 | total=9.229422 | rec=0.073366 | mgcl=6.293752 | cluster=2.862304 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=3.005e-02
epoch 039/050 | total=9.194479 | rec=0.072779 | mgcl=6.271782 | cluster=2.849918 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=3.123e-02
epoch 040/050 | total=9.166286 | rec=0.072123 | mgcl=6.255732 | cluster=2.838432 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=3.388e-02
epoch 041/050 | total=9.135628 | rec=0.071396 | mgcl=6.236866 | cluster=2.827366 | spatial=0.000000 | SC=off | SNF=off | effC=13.966 | gradC=3.727e-02
epoch 042/050 | total=9.107704 | rec=0.070624 | mgcl=6.220560 | cluster=2.816520 | spatial=0.000000 | SC=off | SNF=off | effC=13.952 | gradC=4.089e-02
epoch 043/050 | total=9.077728 | rec=0.069820 | mgcl=6.202177 | cluster=2.805732 | spatial=0.000000 | SC=off | SNF=off | effC=13.937 | gradC=4.446e-02
epoch 044/050 | total=9.050875 | rec=0.068994 | mgcl=6.187041 | cluster=2.794840 | spatial=0.000000 | SC=off | SNF=off | effC=13.923 | gradC=4.782e-02
epoch 045/050 | total=9.023067 | rec=0.068130 | mgcl=6.170994 | cluster=2.783942 | spatial=0.000000 | SC=off | SNF=off | effC=13.910 | gradC=5.079e-02
epoch 046/050 | total=8.997773 | rec=0.067215 | mgcl=6.157504 | cluster=2.773055 | spatial=0.000000 | SC=off | SNF=off | effC=13.898 | gradC=5.328e-02
epoch 047/050 | total=8.970191 | rec=0.066256 | mgcl=6.141872 | cluster=2.762063 | spatial=0.000000 | SC=off | SNF=off | effC=13.887 | gradC=5.523e-02
epoch 048/050 | total=8.944717 | rec=0.065281 | mgcl=6.128607 | cluster=2.750829 | spatial=0.000000 | SC=off | SNF=off | effC=13.881 | gradC=5.664e-02
epoch 049/050 | total=8.917392 | rec=0.064296 | mgcl=6.113966 | cluster=2.739130 | spatial=0.000000 | SC=off | SNF=off | effC=13.880 | gradC=5.750e-02
epoch 050/050 | total=8.890372 | rec=0.063308 | mgcl=6.100419 | cluster=2.726645 | spatial=0.000000 | SC=off | SNF=off | effC=13.883 | gradC=5.777e-02
ARI=0.451784 | NMI=0.440941
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t05_featk10
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t05_featk10/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t05_featk10/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=15.526496 | rec=0.187170 | mgcl=7.669663 | cluster=3.298096 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=15.489040 | rec=0.172771 | mgcl=7.658135 | cluster=3.297622 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=0.000e+00
epoch 003/050 | total=15.451313 | rec=0.159823 | mgcl=7.645745 | cluster=3.297210 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=15.399115 | rec=0.148374 | mgcl=7.625371 | cluster=3.296863 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=0.000e+00
epoch 005/050 | total=15.323063 | rec=0.138484 | mgcl=7.592289 | cluster=3.296571 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=0.000e+00
epoch 006/050 | total=15.220914 | rec=0.130021 | mgcl=7.545446 | cluster=3.296338 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=15.117821 | rec=0.122764 | mgcl=7.497528 | cluster=3.296162 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=15.031244 | rec=0.116563 | mgcl=7.457341 | cluster=3.296042 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=14.927942 | rec=0.111378 | mgcl=7.408282 | cluster=3.295968 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=14.827831 | rec=0.107215 | mgcl=7.360308 | cluster=3.295930 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=18.059092 | rec=0.104036 | mgcl=7.329569 | cluster=3.295917 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.913e-03
epoch 012/050 | total=17.999174 | rec=0.101750 | mgcl=7.300797 | cluster=3.295831 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.204e-03
epoch 013/050 | total=17.920113 | rec=0.100095 | mgcl=7.262186 | cluster=3.295646 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.662e-03
epoch 014/050 | total=17.830114 | rec=0.098911 | mgcl=7.218133 | cluster=3.294937 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.576e-03

In [21]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_t05_mgcl2.yaml") as f:
    base = yaml.safe_load(f)

variants = {
    "e185_t04_mgcl2":   {"model": {"cluster_temperature": 0.4}},
    "e185_t03_mgcl2":   {"model": {"cluster_temperature": 0.3}},
    "e185_t05_mgcl3":   {"loss": {"lambda_mgcl": 3.0}},
    "e185_t05_mgcl2_fk15": {"graphs": {"feature": {"k": 15}}},
    "e185_t03_featk10": {"model": {"cluster_temperature": 0.3},
                         "graphs": {"feature": {"k": 10}}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/e185_t04_mgcl2 results/e185_t03_mgcl2 results/e185_t05_mgcl3 \
       results/e185_t05_mgcl2_fk15 results/e185_t03_featk10

!python experiments/run_exp.py --config configs/e185_t04_mgcl2.yaml
!python experiments/run_exp.py --config configs/e185_t03_mgcl2.yaml
!python experiments/run_exp.py --config configs/e185_t05_mgcl3.yaml
!python experiments/run_exp.py --config configs/e185_t05_mgcl2_fk15.yaml
!python experiments/run_exp.py --config configs/e185_t03_featk10.yaml

rows = [{"config": "e185_t05_mgcl2 (当前最佳)", "ARI": 0.4559, "NMI": 0.4410}]
for name in ["e185_t04_mgcl2", "e185_t03_mgcl2", "e185_t05_mgcl3",
             "e185_t05_mgcl2_fk15", "e185_t03_featk10"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
        "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 e185_t04_mgcl2
生成 e185_t03_mgcl2
生成 e185_t05_mgcl3
生成 e185_t05_mgcl2_fk15
生成 e185_t03_featk10
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=15.498254 | rec=0.160812 | mgcl=7.668721 | cluster=3.298058 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=15.466587 | rec=0.147807 | mgcl=7.659390 | cluster=3.297592 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=15.435402 | rec=0.136209 | mgcl=7.649597 | cluster=3.297186 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=15.392783 | rec=0.126034 | mgcl=7.633375 | cluster=3.296845 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=15.328314 | rec=0.117320 | mgcl=7.605497 | cluster=3.296562 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=15.234180 | rec=0.109966 | mgcl=7.562107 | cluster=3.296332 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=15.124909 | rec=0.103796 | mgcl=7.510557 | cluster=3.296158 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=15.030101 | rec=0.098648 | mgcl=7.465726 | cluster=3.296039 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=14.935410 | rec=0.094429 | mgcl=7.420490 | cluster=3.295966 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=14.848236 | rec=0.091128 | mgcl=7.378554 | cluster=3.295928 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=18.059034 | rec=0.088633 | mgcl=7.337244 | cluster=3.295914 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.913e-03
epoch 012/050 | total=17.986645 | rec=0.086859 | mgcl=7.301980 | cluster=3.295825 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.275e-03
epoch 013/050 | total=17.927446 | rec=0.085611 | mgcl=7.273108 | cluster=3.295619 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.765e-03
epoch 014/050 | total=17.817539 | rec=0.084694 | mgcl=7.218992 | cluster=3.294860 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.781e-03
epoch 015/050 | total=17.738527 | rec=0.084026 | mgcl=7.180634 | cluster=3.293234 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.190e-02
epoch 016/050 | total=17.656063 | rec=0.083463 | mgcl=7.141054 | cluster=3.290493 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.663e-02
epoch 017/050 | total=17.533773 | rec=0.082900 | mgcl=7.082220 | cluster=3.286434 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.157e-02
epoch 018/050 | total=17.413208 | rec=0.082368 | mgcl=7.024972 | cluster=3.280896 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.645e-02
epoch 019/050 | total=17.282518 | rec=0.081854 | mgcl=6.963433 | cluster=3.273799 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.105e-02
epoch 020/050 | total=17.142651 | rec=0.081332 | mgcl=6.898171 | cluster=3.264977 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.539e-02
epoch 021/050 | total=17.033779 | rec=0.080824 | mgcl=6.849345 | cluster=3.254265 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.942e-02
epoch 022/050 | total=16.920187 | rec=0.080350 | mgcl=6.799230 | cluster=3.241377 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.314e-02
epoch 023/050 | total=16.809811 | rec=0.079881 | mgcl=6.751908 | cluster=3.226115 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.650e-02
epoch 024/050 | total=16.686274 | rec=0.079480 | mgcl=6.699535 | cluster=3.207723 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.959e-02
epoch 025/050 | total=16.587111 | rec=0.079083 | mgcl=6.661148 | cluster=3.185732 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=5.235e-02
epoch 026/050 | total=16.472843 | rec=0.078670 | mgcl=6.617102 | cluster=3.159969 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.465e-02
epoch 027/050 | total=16.358889 | rec=0.078273 | mgcl=6.574934 | cluster=3.130746 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=5.642e-02
epoch 028/050 | total=16.256121 | rec=0.077889 | mgcl=6.539700 | cluster=3.098833 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=5.758e-02
epoch 029/050 | total=16.155064 | rec=0.077532 | mgcl=6.506015 | cluster=3.065501 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=5.792e-02
epoch 030/050 | total=16.043327 | rec=0.077188 | mgcl=6.467110 | cluster=3.031920 | spatial=0.000000 | SC=off | SNF=off | effC=13.983 | gradC=5.740e-02
epoch 031/050 | total=15.956400 | rec=0.076820 | mgcl=6.440224 | cluster=2.999132 | spatial=0.000000 | SC=off | SNF=off | effC=13.975 | gradC=5.612e-02
epoch 032/050 | total=15.859101 | rec=0.076410 | mgcl=6.407254 | cluster=2.968184 | spatial=0.000000 | SC=off | SNF=off | effC=13.969 | gradC=5.398e-02
epoch 033/050 | total=15.784296 | rec=0.075959 | mgcl=6.384279 | cluster=2.939779 | spatial=0.000000 | SC=off | SNF=off | effC=13.963 | gradC=5.111e-02
epoch 034/050 | total=15.700766 | rec=0.075486 | mgcl=6.355509 | cluster=2.914261 | spatial=0.000000 | SC=off | SNF=off | effC=13.961 | gradC=4.751e-02
epoch 035/050 | total=15.634847 | rec=0.075000 | mgcl=6.334138 | cluster=2.891570 | spatial=0.000000 | SC=off | SNF=off | effC=13.962 | gradC=4.326e-02
epoch 036/050 | total=15.569586 | rec=0.074497 | mgcl=6.311745 | cluster=2.871600 | spatial=0.000000 | SC=off | SNF=off | effC=13.966 | gradC=3.872e-02
epoch 037/050 | total=15.510246 | rec=0.073987 | mgcl=6.291061 | cluster=2.854137 | spatial=0.000000 | SC=off | SNF=off | effC=13.973 | gradC=3.414e-02
epoch 038/050 | total=15.452935 | rec=0.073461 | mgcl=6.270288 | cluster=2.838899 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=2.985e-02
epoch 039/050 | total=15.401398 | rec=0.072906 | mgcl=6.251456 | cluster=2.825579 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=2.659e-02
epoch 040/050 | total=15.352197 | rec=0.072315 | mgcl=6.233013 | cluster=2.813856 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.496e-02
epoch 041/050 | total=15.305812 | rec=0.071684 | mgcl=6.215372 | cluster=2.803385 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.525e-02
epoch 042/050 | total=15.259022 | rec=0.071012 | mgcl=6.197126 | cluster=2.793757 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.731e-02
epoch 043/050 | total=15.217965 | rec=0.070309 | mgcl=6.181590 | cluster=2.784476 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.059e-02
epoch 044/050 | total=15.173929 | rec=0.069576 | mgcl=6.164652 | cluster=2.775048 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=3.464e-02
epoch 045/050 | total=15.132821 | rec=0.068813 | mgcl=6.149453 | cluster=2.765101 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=3.901e-02
epoch 046/050 | total=15.092096 | rec=0.068014 | mgcl=6.134874 | cluster=2.754334 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=4.338e-02
epoch 047/050 | total=15.049514 | rec=0.067179 | mgcl=6.119942 | cluster=2.742451 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=4.756e-02
epoch 048/050 | total=15.008292 | rec=0.066316 | mgcl=6.106352 | cluster=2.729272 | spatial=0.000000 | SC=off | SNF=off | effC=13.967 | gradC=5.148e-02
epoch 049/050 | total=14.964599 | rec=0.065431 | mgcl=6.092250 | cluster=2.714668 | spatial=0.000000 | SC=off | SNF=off | effC=13.961 | gradC=5.511e-02
epoch 050/050 | total=14.921323 | rec=0.064540 | mgcl=6.079125 | cluster=2.698531 | spatial=0.000000 | SC=off | SNF=off | effC=13.954 | gradC=5.847e-02
ARI=0.461761 | NMI=0.463166
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t04_mgcl2
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t04_mgcl2/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t04_mgcl2/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=15.498254 | rec=0.160812 | mgcl=7.668721 | cluster=3.298035 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=15.466587 | rec=0.147807 | mgcl=7.659390 | cluster=3.297573 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=15.435400 | rec=0.136209 | mgcl=7.649596 | cluster=3.297172 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=15.392783 | rec=0.126034 | mgcl=7.633375 | cluster=3.296835 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=15.328312 | rec=0.117320 | mgcl=7.605496 | cluster=3.296554 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=15.234179 | rec=0.109966 | mgcl=7.562107 | cluster=3.296327 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=15.124911 | rec=0.103796 | mgcl=7.510558 | cluster=3.296155 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=15.030097 | rec=0.098648 | mgcl=7.465724 | cluster=3.296038 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=14.935406 | rec=0.094429 | mgcl=7.420488 | cluster=3.295968 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=14.848242 | rec=0.091128 | mgcl=7.378557 | cluster=3.295932 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=18.059044 | rec=0.088633 | mgcl=7.337246 | cluster=3.295918 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.034e-03
epoch 012/050 | total=17.986614 | rec=0.086859 | mgcl=7.301979 | cluster=3.295797 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.674e-03
epoch 013/050 | total=17.927265 | rec=0.085612 | mgcl=7.273098 | cluster=3.295457 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.102e-03
epoch 014/050 | total=17.816952 | rec=0.084695 | mgcl=7.218966 | cluster=3.294325 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.063e-02
epoch 015/050 | total=17.737246 | rec=0.084027 | mgcl=7.180637 | cluster=3.291945 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.640e-02
epoch 016/050 | total=17.653566 | rec=0.083465 | mgcl=7.141059 | cluster=3.287982 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.274e-02
epoch 017/050 | total=17.529713 | rec=0.082905 | mgcl=7.082308 | cluster=3.282192 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.914e-02
epoch 018/050 | total=17.406849 | rec=0.082375 | mgcl=7.025041 | cluster=3.274391 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.530e-02
epoch 019/050 | total=17.273556 | rec=0.081864 | mgcl=6.963606 | cluster=3.264481 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.098e-02
epoch 020/050 | total=17.130297 | rec=0.081345 | mgcl=6.898376 | cluster=3.252199 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.627e-02
epoch 021/050 | total=17.017536 | rec=0.080840 | mgcl=6.849718 | cluster=3.237261 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.110e-02
epoch 022/050 | total=16.898317 | rec=0.080368 | mgcl=6.799342 | cluster=3.219265 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.542e-02
epoch 023/050 | total=16.782787 | rec=0.079901 | mgcl=6.752466 | cluster=3.197955 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.913e-02
epoch 024/050 | total=16.652361 | rec=0.079500 | mgcl=6.700204 | cluster=3.172452 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.223e-02
epoch 025/050 | total=16.544085 | rec=0.079105 | mgcl=6.661262 | cluster=3.142456 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.456e-02
epoch 026/050 | total=16.423658 | rec=0.078700 | mgcl=6.618347 | cluster=3.108266 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=6.591e-02
epoch 027/050 | total=16.300169 | rec=0.078315 | mgcl=6.575476 | cluster=3.070901 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=6.617e-02
epoch 028/050 | total=16.191486 | rec=0.077948 | mgcl=6.540850 | cluster=3.031839 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=6.536e-02
epoch 029/050 | total=16.084259 | rec=0.077606 | mgcl=6.506832 | cluster=2.992989 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=6.345e-02
epoch 030/050 | total=15.971156 | rec=0.077275 | mgcl=6.469030 | cluster=2.955821 | spatial=0.000000 | SC=off | SNF=off | effC=13.978 | gradC=6.066e-02
epoch 031/050 | total=15.881988 | rec=0.076915 | mgcl=6.441872 | cluster=2.921329 | spatial=0.000000 | SC=off | SNF=off | effC=13.972 | gradC=5.731e-02
epoch 032/050 | total=15.783965 | rec=0.076509 | mgcl=6.408588 | cluster=2.890281 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=5.353e-02
epoch 033/050 | total=15.710917 | rec=0.076066 | mgcl=6.385980 | cluster=2.862891 | spatial=0.000000 | SC=off | SNF=off | effC=13.966 | gradC=4.963e-02
epoch 034/050 | total=15.628243 | rec=0.075603 | mgcl=6.356815 | cluster=2.839011 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=4.602e-02
epoch 035/050 | total=15.564423 | rec=0.075126 | mgcl=6.335597 | cluster=2.818102 | spatial=0.000000 | SC=off | SNF=off | effC=13.971 | gradC=4.327e-02
epoch 036/050 | total=15.499454 | rec=0.074634 | mgcl=6.312593 | cluster=2.799634 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=4.229e-02
epoch 037/050 | total=15.441854 | rec=0.074129 | mgcl=6.292405 | cluster=2.782917 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=4.379e-02
epoch 038/050 | total=15.383106 | rec=0.073600 | mgcl=6.271164 | cluster=2.767177 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=4.773e-02
epoch 039/050 | total=15.329888 | rec=0.073037 | mgcl=6.252625 | cluster=2.751600 | spatial=0.000000 | SC=off | SNF=off | effC=13.983 | gradC=5.337e-02
epoch 040/050 | total=15.275801 | rec=0.072433 | mgcl=6.233936 | cluster=2.735495 | spatial=0.000000 | SC=off | SNF=off | effC=13.977 | gradC=5.953e-02
epoch 041/050 | total=15.222576 | rec=0.071789 | mgcl=6.216135 | cluster=2.718518 | spatial=0.000000 | SC=off | SNF=off | effC=13.968 | gradC=6.510e-02
epoch 042/050 | total=15.167085 | rec=0.071108 | mgcl=6.197651 | cluster=2.700674 | spatial=0.000000 | SC=off | SNF=off | effC=13.954 | gradC=6.955e-02
epoch 043/050 | total=15.116290 | rec=0.070396 | mgcl=6.181903 | cluster=2.682087 | spatial=0.000000 | SC=off | SNF=off | effC=13.937 | gradC=7.298e-02
epoch 044/050 | total=15.062847 | rec=0.069655 | mgcl=6.165144 | cluster=2.662904 | spatial=0.000000 | SC=off | SNF=off | effC=13.920 | gradC=7.589e-02
epoch 045/050 | total=15.012982 | rec=0.068882 | mgcl=6.150289 | cluster=2.643523 | spatial=0.000000 | SC=off | SNF=off | effC=13.905 | gradC=7.890e-02
epoch 046/050 | total=14.962911 | rec=0.068073 | mgcl=6.135404 | cluster=2.624029 | spatial=0.000000 | SC=off | SNF=off | effC=13.892 | gradC=8.229e-02
epoch 047/050 | total=14.912430 | rec=0.067231 | mgcl=6.120650 | cluster=2.603899 | spatial=0.000000 | SC=off | SNF=off | effC=13.883 | gradC=8.588e-02
epoch 048/050 | total=14.863569 | rec=0.066363 | mgcl=6.107389 | cluster=2.582428 | spatial=0.000000 | SC=off | SNF=off | effC=13.880 | gradC=8.930e-02
epoch 049/050 | total=14.811453 | rec=0.065479 | mgcl=6.093541 | cluster=2.558893 | spatial=0.000000 | SC=off | SNF=off | effC=13.883 | gradC=9.223e-02
epoch 050/050 | total=14.757779 | rec=0.064593 | mgcl=6.080267 | cluster=2.532652 | spatial=0.000000 | SC=off | SNF=off | effC=13.888 | gradC=9.435e-02
ARI=0.462508 | NMI=0.467886
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t03_mgcl2
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t03_mgcl2/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t03_mgcl2/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=23.166975 | rec=0.160812 | mgcl=7.668721 | cluster=3.298072 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=23.126156 | rec=0.148331 | mgcl=7.659275 | cluster=3.297603 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=23.084658 | rec=0.137186 | mgcl=7.649157 | cluster=3.297196 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=23.024109 | rec=0.127556 | mgcl=7.632185 | cluster=3.296851 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=22.928083 | rec=0.119453 | mgcl=7.602877 | cluster=3.296564 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=22.785597 | rec=0.112694 | mgcl=7.557634 | cluster=3.296333 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=22.622032 | rec=0.107028 | mgcl=7.505002 | cluster=3.296158 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=22.481276 | rec=0.102244 | mgcl=7.459677 | cluster=3.296039 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=22.337914 | rec=0.098258 | mgcl=7.413218 | cluster=3.295965 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=22.201511 | rec=0.095103 | mgcl=7.368803 | cluster=3.295926 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=25.376467 | rec=0.092690 | mgcl=7.329288 | cluster=3.295912 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.852e-03
epoch 012/050 | total=25.262480 | rec=0.090988 | mgcl=7.291886 | cluster=3.295833 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.034e-03
epoch 013/050 | total=25.168089 | rec=0.089801 | mgcl=7.260869 | cluster=3.295682 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.200e-03
epoch 014/050 | total=25.003016 | rec=0.088953 | mgcl=7.206329 | cluster=3.295077 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.491e-03

In [22]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_t05_mgcl3.yaml") as f:
    base = yaml.safe_load(f)

variants = {
    "e185_t05_mgcl5":    {"loss": {"lambda_mgcl": 5.0}},
    "e185_t05_mgcl4":    {"loss": {"lambda_mgcl": 4.0}},
    "e185_t03_mgcl3":    {"model": {"cluster_temperature": 0.3}, "loss": {"lambda_mgcl": 3.0}},
    "e185_t04_mgcl3":    {"model": {"cluster_temperature": 0.4}, "loss": {"lambda_mgcl": 3.0}},
    "e185_t035_mgcl3":   {"model": {"cluster_temperature": 0.35}, "loss": {"lambda_mgcl": 3.0}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/e185_t05_mgcl5 results/e185_t05_mgcl4 results/e185_t03_mgcl3 \
       results/e185_t04_mgcl3 results/e185_t035_mgcl3

!python experiments/run_exp.py --config configs/e185_t05_mgcl5.yaml
!python experiments/run_exp.py --config configs/e185_t05_mgcl4.yaml
!python experiments/run_exp.py --config configs/e185_t03_mgcl3.yaml
!python experiments/run_exp.py --config configs/e185_t04_mgcl3.yaml
!python experiments/run_exp.py --config configs/e185_t035_mgcl3.yaml

rows = [
    {"config": "e185_t05_mgcl3", "ARI": 0.4768, "NMI": 0.4454},
    {"config": "e185_t03_mgcl2", "ARI": 0.4625, "NMI": 0.4679},
]
for name in ["e185_t05_mgcl5", "e185_t05_mgcl4", "e185_t03_mgcl3",
             "e185_t04_mgcl3", "e185_t035_mgcl3"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
        "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 e185_t05_mgcl5
生成 e185_t05_mgcl4
生成 e185_t03_mgcl3
生成 e185_t04_mgcl3
生成 e185_t035_mgcl3
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=38.504417 | rec=0.160812 | mgcl=7.668721 | cluster=3.298072 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=38.444881 | rec=0.149041 | mgcl=7.659168 | cluster=3.297612 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=0.000e+00
epoch 003/050 | total=38.382034 | rec=0.138670 | mgcl=7.648672 | cluster=3.297204 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=38.283916 | rec=0.129931 | mgcl=7.630797 | cluster=3.296857 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=0.000e+00
epoch 005/050 | total=38.122292 | rec=0.122700 | mgcl=7.599918 | cluster=3.296568 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=0.000e+00
epoch 006/050 | total=37.880859 | rec=0.116707 | mgcl=7.552830 | cluster=3.296335 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=37.609879 | rec=0.111639 | mgcl=7.499649 | cluster=3.296160 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=37.378868 | rec=0.107248 | mgcl=7.454325 | cluster=3.296041 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=37.132832 | rec=0.103469 | mgcl=7.405872 | cluster=3.295967 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=36.894890 | rec=0.100426 | mgcl=7.358892 | cluster=3.295926 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=40.006889 | rec=0.098070 | mgcl=7.322582 | cluster=3.295910 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.858e-03
epoch 012/050 | total=39.798542 | rec=0.096411 | mgcl=7.281261 | cluster=3.295825 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.028e-03
epoch 013/050 | total=39.623951 | rec=0.095262 | mgcl=7.246609 | cluster=3.295642 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.435e-03
epoch 014/050 | total=39.359688 | rec=0.094468 | mgcl=7.194054 | cluster=3.294947 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.038e-03
epoch 015/050 | total=39.123531 | rec=0.093953 | mgcl=7.147218 | cluster=3.293487 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.052e-02
epoch 016/050 | total=38.880470 | rec=0.093558 | mgcl=7.099169 | cluster=3.291066 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.447e-02
epoch 017/050 | total=38.592495 | rec=0.093180 | mgcl=7.042355 | cluster=3.287542 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.847e-02
epoch 018/050 | total=38.235847 | rec=0.092800 | mgcl=6.972034 | cluster=3.282881 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.220e-02
epoch 019/050 | total=37.908215 | rec=0.092393 | mgcl=6.907734 | cluster=3.277148 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.550e-02
epoch 020/050 | total=37.606323 | rec=0.091942 | mgcl=6.848795 | cluster=3.270407 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.834e-02
epoch 021/050 | total=37.395081 | rec=0.091504 | mgcl=6.808197 | cluster=3.262588 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.081e-02
epoch 022/050 | total=37.182938 | rec=0.091036 | mgcl=6.767626 | cluster=3.253774 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.291e-02
epoch 023/050 | total=36.833340 | rec=0.090625 | mgcl=6.699796 | cluster=3.243733 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.475e-02
epoch 024/050 | total=36.684597 | rec=0.090257 | mgcl=6.672417 | cluster=3.232255 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.636e-02
epoch 025/050 | total=36.396927 | rec=0.089853 | mgcl=6.617627 | cluster=3.218939 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.782e-02
epoch 026/050 | total=36.223373 | rec=0.089418 | mgcl=6.586029 | cluster=3.203815 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.910e-02
epoch 027/050 | total=35.971748 | rec=0.088965 | mgcl=6.539112 | cluster=3.187220 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.010e-02
epoch 028/050 | total=35.812374 | rec=0.088500 | mgcl=6.510940 | cluster=3.169174 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.086e-02
epoch 029/050 | total=35.585167 | rec=0.088038 | mgcl=6.469471 | cluster=3.149773 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.138e-02
epoch 030/050 | total=35.424847 | rec=0.087575 | mgcl=6.441597 | cluster=3.129292 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.165e-02
epoch 031/050 | total=35.236229 | rec=0.087091 | mgcl=6.408234 | cluster=3.107966 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.171e-02
epoch 032/050 | total=35.098095 | rec=0.086580 | mgcl=6.385084 | cluster=3.086098 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.165e-02
epoch 033/050 | total=34.938503 | rec=0.086038 | mgcl=6.357645 | cluster=3.064242 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.137e-02
epoch 034/050 | total=34.805046 | rec=0.085450 | mgcl=6.335341 | cluster=3.042894 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=4.068e-02
epoch 035/050 | total=34.675629 | rec=0.084810 | mgcl=6.313704 | cluster=3.022300 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.954e-02
epoch 036/050 | total=34.550797 | rec=0.084148 | mgcl=6.292807 | cluster=3.002614 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.798e-02
epoch 037/050 | total=34.429596 | rec=0.083486 | mgcl=6.272408 | cluster=2.984069 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=3.602e-02
epoch 038/050 | total=34.315170 | rec=0.082816 | mgcl=6.253134 | cluster=2.966686 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.388e-02
epoch 039/050 | total=34.209740 | rec=0.082131 | mgcl=6.235442 | cluster=2.950401 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.182e-02
epoch 040/050 | total=34.098854 | rec=0.081432 | mgcl=6.216447 | cluster=2.935184 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.999e-02
epoch 041/050 | total=34.003448 | rec=0.080717 | mgcl=6.200359 | cluster=2.920933 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.857e-02
epoch 042/050 | total=33.896908 | rec=0.079985 | mgcl=6.181871 | cluster=2.907567 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.774e-02
epoch 043/050 | total=33.810604 | rec=0.079225 | mgcl=6.167275 | cluster=2.895003 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=2.764e-02
epoch 044/050 | total=33.718315 | rec=0.078439 | mgcl=6.151361 | cluster=2.883071 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.828e-02
epoch 045/050 | total=33.632961 | rec=0.077636 | mgcl=6.136755 | cluster=2.871553 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.967e-02
epoch 046/050 | total=33.546223 | rec=0.076817 | mgcl=6.121845 | cluster=2.860178 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=3.159e-02
epoch 047/050 | total=33.461971 | rec=0.075981 | mgcl=6.107453 | cluster=2.848727 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=3.386e-02
epoch 048/050 | total=33.381939 | rec=0.075125 | mgcl=6.093963 | cluster=2.836998 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=3.633e-02
epoch 049/050 | total=33.302143 | rec=0.074243 | mgcl=6.080618 | cluster=2.824810 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=3.882e-02
epoch 050/050 | total=33.221748 | rec=0.073344 | mgcl=6.067281 | cluster=2.811999 | spatial=0.000000 | SC=off | SNF=off | effC=13.977 | gradC=4.125e-02
ARI=0.451637 | NMI=0.455736
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl5
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl5/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl5/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=30.835695 | rec=0.160812 | mgcl=7.668721 | cluster=3.298072 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=30.785578 | rec=0.148728 | mgcl=7.659213 | cluster=3.297607 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=30.733517 | rec=0.137994 | mgcl=7.648880 | cluster=3.297200 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=30.654394 | rec=0.128837 | mgcl=7.631389 | cluster=3.296854 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=30.525852 | rec=0.121214 | mgcl=7.601160 | cluster=3.296566 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=0.000e+00
epoch 006/050 | total=30.334248 | rec=0.114888 | mgcl=7.554840 | cluster=3.296334 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=30.116980 | rec=0.109569 | mgcl=7.501853 | cluster=3.296159 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=29.931290 | rec=0.105018 | mgcl=7.456568 | cluster=3.296040 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=29.738995 | rec=0.101154 | mgcl=7.409460 | cluster=3.295966 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=29.554529 | rec=0.098070 | mgcl=7.364115 | cluster=3.295927 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=32.692097 | rec=0.095694 | mgcl=7.325123 | cluster=3.295911 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.855e-03
epoch 012/050 | total=32.537533 | rec=0.094015 | mgcl=7.286922 | cluster=3.295828 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.016e-03
epoch 013/050 | total=32.404388 | rec=0.092854 | mgcl=7.253969 | cluster=3.295661 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.327e-03
epoch 014/050 | total=32.185745 | rec=0.092042 | mgcl=7.199675 | cluster=3.295005 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.799e-03
epoch 015/050 | total=32.006306 | rec=0.091498 | mgcl=7.155300 | cluster=3.293608 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.020e-02
epoch 016/050 | total=31.830023 | rec=0.091077 | mgcl=7.111922 | cluster=3.291260 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.412e-02
epoch 017/050 | total=31.596561 | rec=0.090669 | mgcl=7.054520 | cluster=3.287813 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.812e-02
epoch 018/050 | total=31.311295 | rec=0.090265 | mgcl=6.984452 | cluster=3.283222 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.189e-02
epoch 019/050 | total=31.064253 | rec=0.089848 | mgcl=6.924220 | cluster=3.277527 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.526e-02
epoch 020/050 | total=30.801121 | rec=0.089395 | mgcl=6.860245 | cluster=3.270746 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.821e-02
epoch 021/050 | total=30.626562 | rec=0.088943 | mgcl=6.818681 | cluster=3.262893 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.076e-02
epoch 022/050 | total=30.488075 | rec=0.088508 | mgcl=6.786438 | cluster=3.253814 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.305e-02
epoch 023/050 | total=30.167065 | rec=0.088083 | mgcl=6.708862 | cluster=3.243535 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.499e-02
epoch 024/050 | total=30.074432 | rec=0.087688 | mgcl=6.688762 | cluster=3.231695 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.671e-02
epoch 025/050 | total=29.825726 | rec=0.087314 | mgcl=6.630110 | cluster=3.217969 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.828e-02
epoch 026/050 | total=29.695202 | rec=0.086924 | mgcl=6.601521 | cluster=3.202191 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.966e-02
epoch 027/050 | total=29.464766 | rec=0.086496 | mgcl=6.548447 | cluster=3.184483 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.084e-02
epoch 028/050 | total=29.353811 | rec=0.086045 | mgcl=6.525643 | cluster=3.165196 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.177e-02
epoch 029/050 | total=29.154009 | rec=0.085620 | mgcl=6.480917 | cluster=3.144722 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=4.230e-02
epoch 030/050 | total=29.027191 | rec=0.085198 | mgcl=6.454773 | cluster=3.122899 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.264e-02
epoch 031/050 | total=28.853121 | rec=0.084742 | mgcl=6.417077 | cluster=3.100074 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=4.291e-02
epoch 032/050 | total=28.745804 | rec=0.084254 | mgcl=6.396125 | cluster=3.077049 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=4.291e-02
epoch 033/050 | total=28.603853 | rec=0.083737 | mgcl=6.366451 | cluster=3.054311 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=4.246e-02
epoch 034/050 | total=28.493538 | rec=0.083187 | mgcl=6.344561 | cluster=3.032108 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=4.160e-02
epoch 035/050 | total=28.374750 | rec=0.082595 | mgcl=6.320338 | cluster=3.010804 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=4.035e-02
epoch 036/050 | total=28.272297 | rec=0.081965 | mgcl=6.299891 | cluster=2.990767 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=3.876e-02
epoch 037/050 | total=28.176851 | rec=0.081328 | mgcl=6.280848 | cluster=2.972131 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=3.664e-02
epoch 038/050 | total=28.070810 | rec=0.080686 | mgcl=6.258844 | cluster=2.954747 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=3.395e-02
epoch 039/050 | total=27.986771 | rec=0.080026 | mgcl=6.242048 | cluster=2.938552 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=3.130e-02
epoch 040/050 | total=27.899136 | rec=0.079350 | mgcl=6.224039 | cluster=2.923629 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.910e-02
epoch 041/050 | total=27.812838 | rec=0.078664 | mgcl=6.206069 | cluster=2.909896 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.737e-02
epoch 042/050 | total=27.732519 | rec=0.077952 | mgcl=6.189348 | cluster=2.897174 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.638e-02
epoch 043/050 | total=27.654177 | rec=0.077212 | mgcl=6.172925 | cluster=2.885268 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=2.637e-02
epoch 044/050 | total=27.578468 | rec=0.076453 | mgcl=6.157014 | cluster=2.873958 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=2.723e-02
epoch 045/050 | total=27.511003 | rec=0.075674 | mgcl=6.143072 | cluster=2.863041 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=2.891e-02
epoch 046/050 | total=27.439035 | rec=0.074867 | mgcl=6.127977 | cluster=2.852258 | spatial=0.000000 | SC=off | SNF=off | effC=13.988 | gradC=3.125e-02
epoch 047/050 | total=27.370541 | rec=0.074031 | mgcl=6.113798 | cluster=2.841318 | spatial=0.000000 | SC=off | SNF=off | effC=13.985 | gradC=3.395e-02
epoch 048/050 | total=27.304899 | rec=0.073175 | mgcl=6.100433 | cluster=2.829990 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=3.681e-02
epoch 049/050 | total=27.233564 | rec=0.072300 | mgcl=6.085800 | cluster=2.818064 | spatial=0.000000 | SC=off | SNF=off | effC=13.977 | gradC=3.968e-02
epoch 050/050 | total=27.171511 | rec=0.071407 | mgcl=6.073681 | cluster=2.805379 | spatial=0.000000 | SC=off | SNF=off | effC=13.973 | gradC=4.243e-02
ARI=0.471667 | NMI=0.449187
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl4
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl4/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t05_mgcl4/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=23.166975 | rec=0.160812 | mgcl=7.668721 | cluster=3.298035 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=23.126156 | rec=0.148331 | mgcl=7.659275 | cluster=3.297572 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=23.084658 | rec=0.137186 | mgcl=7.649157 | cluster=3.297174 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=23.024111 | rec=0.127556 | mgcl=7.632185 | cluster=3.296836 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=22.928083 | rec=0.119453 | mgcl=7.602877 | cluster=3.296552 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=22.785597 | rec=0.112694 | mgcl=7.557634 | cluster=3.296325 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=22.622032 | rec=0.107028 | mgcl=7.505002 | cluster=3.296154 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=22.481274 | rec=0.102244 | mgcl=7.459676 | cluster=3.296038 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=22.337906 | rec=0.098258 | mgcl=7.413216 | cluster=3.295969 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=22.201523 | rec=0.095103 | mgcl=7.368807 | cluster=3.295932 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=25.376484 | rec=0.092690 | mgcl=7.329292 | cluster=3.295918 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.047e-03
epoch 012/050 | total=25.262428 | rec=0.090987 | mgcl=7.291885 | cluster=3.295785 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.768e-03
epoch 013/050 | total=25.167809 | rec=0.089801 | mgcl=7.260873 | cluster=3.295390 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.526e-03
epoch 014/050 | total=25.002060 | rec=0.088953 | mgcl=7.206329 | cluster=3.294120 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.148e-02

In [23]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_t03_mgcl3.yaml") as f:
    base = yaml.safe_load(f)

variants = {
    "e185_t03_mgcl4":   {"loss": {"lambda_mgcl": 4.0}},
    "e185_t025_mgcl3":  {"model": {"cluster_temperature": 0.25}},
    "e185_t02_mgcl3":   {"model": {"cluster_temperature": 0.2}},
    "e185_t025_mgcl4":  {"model": {"cluster_temperature": 0.25},
                         "loss": {"lambda_mgcl": 4.0}},
    "e185_dim256_t03_mgcl3": {"model": {"fine_dim": 256}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    cfg["output"] = {"root": "results"}
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/e185_t03_mgcl4 results/e185_t025_mgcl3 results/e185_t02_mgcl3 \
       results/e185_t025_mgcl4 results/e185_dim256_t03_mgcl3

!python experiments/run_exp.py --config configs/e185_t03_mgcl4.yaml
!python experiments/run_exp.py --config configs/e185_t025_mgcl3.yaml
!python experiments/run_exp.py --config configs/e185_t02_mgcl3.yaml
!python experiments/run_exp.py --config configs/e185_t025_mgcl4.yaml
!python experiments/run_exp.py --config configs/e185_dim256_t03_mgcl3.yaml

rows = [{"config": "e185_t03_mgcl3 (当前最佳)", "ARI": 0.4963, "NMI": 0.4712}]
for name in ["e185_t03_mgcl4", "e185_t025_mgcl3", "e185_t02_mgcl3",
             "e185_t025_mgcl4", "e185_dim256_t03_mgcl3"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
        "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 e185_t03_mgcl4
生成 e185_t025_mgcl3
生成 e185_t02_mgcl3
生成 e185_t025_mgcl4
生成 e185_dim256_t03_mgcl3
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=30.835695 | rec=0.160812 | mgcl=7.668721 | cluster=3.298035 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=30.785578 | rec=0.148728 | mgcl=7.659213 | cluster=3.297577 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=30.733517 | rec=0.137994 | mgcl=7.648880 | cluster=3.297179 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=30.654394 | rec=0.128837 | mgcl=7.631389 | cluster=3.296839 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=30.525852 | rec=0.121214 | mgcl=7.601160 | cluster=3.296555 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=0.000e+00
epoch 006/050 | total=30.334248 | rec=0.114888 | mgcl=7.554840 | cluster=3.296327 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=30.116983 | rec=0.109569 | mgcl=7.501853 | cluster=3.296155 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=29.931292 | rec=0.105018 | mgcl=7.456568 | cluster=3.296039 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=29.738993 | rec=0.101154 | mgcl=7.409460 | cluster=3.295969 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=29.554531 | rec=0.098070 | mgcl=7.364115 | cluster=3.295932 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=32.692108 | rec=0.095694 | mgcl=7.325124 | cluster=3.295918 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.059e-03
epoch 012/050 | total=32.537483 | rec=0.094015 | mgcl=7.286922 | cluster=3.295779 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=2.835e-03
epoch 013/050 | total=32.404072 | rec=0.092854 | mgcl=7.253968 | cluster=3.295347 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.804e-03
epoch 014/050 | total=32.184727 | rec=0.092042 | mgcl=7.199676 | cluster=3.293981 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.203e-02
epoch 015/050 | total=32.003937 | rec=0.091498 | mgcl=7.155308 | cluster=3.291209 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.832e-02
epoch 016/050 | total=31.825592 | rec=0.091078 | mgcl=7.111946 | cluster=3.286730 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.494e-02
epoch 017/050 | total=31.589327 | rec=0.090672 | mgcl=7.054573 | cluster=3.280365 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.141e-02
epoch 018/050 | total=31.300526 | rec=0.090270 | mgcl=6.984542 | cluster=3.272086 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.733e-02
epoch 019/050 | total=31.049288 | rec=0.089856 | mgcl=6.924370 | cluster=3.261954 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.252e-02
epoch 020/050 | total=30.780947 | rec=0.089405 | mgcl=6.860401 | cluster=3.249937 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.705e-02
epoch 021/050 | total=30.600136 | rec=0.088955 | mgcl=6.818801 | cluster=3.235975 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.090e-02
epoch 022/050 | total=30.453703 | rec=0.088520 | mgcl=6.786353 | cluster=3.219772 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.426e-02
epoch 023/050 | total=30.125027 | rec=0.088092 | mgcl=6.708903 | cluster=3.201324 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=5.695e-02
epoch 024/050 | total=30.022141 | rec=0.087695 | mgcl=6.688613 | cluster=3.179995 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=5.912e-02
epoch 025/050 | total=29.763165 | rec=0.087320 | mgcl=6.630102 | cluster=3.155437 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=6.077e-02
epoch 026/050 | total=29.621149 | rec=0.086932 | mgcl=6.601623 | cluster=3.127726 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=6.175e-02
epoch 027/050 | total=29.378735 | rec=0.086509 | mgcl=6.548692 | cluster=3.097459 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.203e-02
epoch 028/050 | total=29.255674 | rec=0.086068 | mgcl=6.526012 | cluster=3.065557 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=6.156e-02
epoch 029/050 | total=29.043867 | rec=0.085653 | mgcl=6.481284 | cluster=3.033079 | spatial=0.000000 | SC=off | SNF=off | effC=13.996 | gradC=6.020e-02
epoch 030/050 | total=28.908253 | rec=0.085242 | mgcl=6.455666 | cluster=3.000347 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=5.825e-02
epoch 031/050 | total=28.724785 | rec=0.084794 | mgcl=6.417901 | cluster=2.968389 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=5.602e-02
epoch 032/050 | total=28.609985 | rec=0.084310 | mgcl=6.396822 | cluster=2.938385 | spatial=0.000000 | SC=off | SNF=off | effC=13.988 | gradC=5.342e-02
epoch 033/050 | total=28.465662 | rec=0.083795 | mgcl=6.367767 | cluster=2.910799 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=5.038e-02
epoch 034/050 | total=28.350418 | rec=0.083250 | mgcl=6.345356 | cluster=2.885743 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=4.715e-02
epoch 035/050 | total=28.231728 | rec=0.082669 | mgcl=6.321445 | cluster=2.863281 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=4.396e-02
epoch 036/050 | total=28.129663 | rec=0.082055 | mgcl=6.301066 | cluster=2.843346 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=4.116e-02
epoch 037/050 | total=28.034752 | rec=0.081433 | mgcl=6.281930 | cluster=2.825600 | spatial=0.000000 | SC=off | SNF=off | effC=13.989 | gradC=3.892e-02
epoch 038/050 | total=27.930387 | rec=0.080800 | mgcl=6.260043 | cluster=2.809414 | spatial=0.000000 | SC=off | SNF=off | effC=13.992 | gradC=3.767e-02
epoch 039/050 | total=27.847748 | rec=0.080144 | mgcl=6.243325 | cluster=2.794304 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=3.828e-02
epoch 040/050 | total=27.760050 | rec=0.079467 | mgcl=6.225168 | cluster=2.779911 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=4.103e-02
epoch 041/050 | total=27.674252 | rec=0.078772 | mgcl=6.207459 | cluster=2.765644 | spatial=0.000000 | SC=off | SNF=off | effC=13.994 | gradC=4.547e-02
epoch 042/050 | total=27.589952 | rec=0.078044 | mgcl=6.190261 | cluster=2.750864 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=5.102e-02
epoch 043/050 | total=27.507105 | rec=0.077284 | mgcl=6.173685 | cluster=2.735083 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=5.702e-02
epoch 044/050 | total=27.426359 | rec=0.076502 | mgcl=6.157970 | cluster=2.717976 | spatial=0.000000 | SC=off | SNF=off | effC=13.981 | gradC=6.292e-02
epoch 045/050 | total=27.350174 | rec=0.075698 | mgcl=6.143787 | cluster=2.699328 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=6.841e-02
epoch 046/050 | total=27.269863 | rec=0.074865 | mgcl=6.128994 | cluster=2.679021 | spatial=0.000000 | SC=off | SNF=off | effC=13.966 | gradC=7.332e-02
epoch 047/050 | total=27.189941 | rec=0.074003 | mgcl=6.114727 | cluster=2.657030 | spatial=0.000000 | SC=off | SNF=off | effC=13.958 | gradC=7.761e-02
epoch 048/050 | total=27.112099 | rec=0.073119 | mgcl=6.101385 | cluster=2.633440 | spatial=0.000000 | SC=off | SNF=off | effC=13.951 | gradC=8.141e-02
epoch 049/050 | total=27.028227 | rec=0.072221 | mgcl=6.086944 | cluster=2.608230 | spatial=0.000000 | SC=off | SNF=off | effC=13.944 | gradC=8.477e-02
epoch 050/050 | total=26.951281 | rec=0.071311 | mgcl=6.074669 | cluster=2.581291 | spatial=0.000000 | SC=off | SNF=off | effC=13.939 | gradC=8.752e-02
ARI=0.486370 | NMI=0.474710
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t03_mgcl4
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t03_mgcl4/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t03_mgcl4/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=23.166977 | rec=0.160812 | mgcl=7.668722 | cluster=3.298017 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=23.126156 | rec=0.148331 | mgcl=7.659275 | cluster=3.297557 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=23.084658 | rec=0.137186 | mgcl=7.649157 | cluster=3.297164 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=23.024109 | rec=0.127556 | mgcl=7.632185 | cluster=3.296828 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=22.928083 | rec=0.119453 | mgcl=7.602877 | cluster=3.296547 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=22.785595 | rec=0.112694 | mgcl=7.557634 | cluster=3.296321 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=22.622032 | rec=0.107028 | mgcl=7.505002 | cluster=3.296152 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=22.481274 | rec=0.102244 | mgcl=7.459676 | cluster=3.296038 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=22.337914 | rec=0.098258 | mgcl=7.413218 | cluster=3.295970 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=22.201513 | rec=0.095103 | mgcl=7.368804 | cluster=3.295935 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=25.376476 | rec=0.092690 | mgcl=7.329288 | cluster=3.295921 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.165e-03
epoch 012/050 | total=25.262413 | rec=0.090987 | mgcl=7.291887 | cluster=3.295763 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.228e-03
epoch 013/050 | total=25.167633 | rec=0.089801 | mgcl=7.260866 | cluster=3.295237 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.825e-03
epoch 014/050 | total=25.001566 | rec=0.088953 | mgcl=7.206327 | cluster=3.293631 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.399e-02
epoch 015/050 | total=24.869066 | rec=0.088372 | mgcl=7.163441 | cluster=3.290371 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.141e-02
epoch 016/050 | total=24.737741 | rec=0.087908 | mgcl=7.121578 | cluster=3.285099 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=2.921e-02
epoch 017/050 | total=24.555758 | rec=0.087453 | mgcl=7.063574 | cluster=3.277581 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.684e-02
epoch 018/050 | total=24.347515 | rec=0.087014 | mgcl=6.997599 | cluster=3.267705 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=4.390e-02
epoch 019/050 | total=24.154522 | rec=0.086573 | mgcl=6.937500 | cluster=3.255448 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.018e-02
epoch 020/050 | total=23.941422 | rec=0.086099 | mgcl=6.871557 | cluster=3.240649 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=5.579e-02
epoch 021/050 | total=23.794584 | rec=0.085631 | mgcl=6.828627 | cluster=3.223073 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.062e-02
epoch 022/050 | total=23.675179 | rec=0.085181 | mgcl=6.795878 | cluster=3.202365 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.477e-02
epoch 023/050 | total=23.420771 | rec=0.084730 | mgcl=6.719202 | cluster=3.178436 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=6.800e-02
epoch 024/050 | total=23.317894 | rec=0.084322 | mgcl=6.694396 | cluster=3.150383 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.042e-02
epoch 025/050 | total=23.122587 | rec=0.083943 | mgcl=6.640182 | cluster=3.118097 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=7.185e-02
epoch 026/050 | total=22.985094 | rec=0.083551 | mgcl=6.606466 | cluster=3.082143 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=7.204e-02
epoch 027/050 | total=22.799297 | rec=0.083141 | mgcl=6.557436 | cluster=3.043850 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=7.096e-02
epoch 028/050 | total=22.681416 | rec=0.082734 | mgcl=6.531317 | cluster=3.004733 | spatial=0.000000 | SC=off | SNF=off | effC=13.991 | gradC=6.873e-02
epoch 029/050 | total=22.513845 | rec=0.082355 | mgcl=6.488316 | cluster=2.966542 | spatial=0.000000 | SC=off | SNF=off | effC=13.987 | gradC=6.529e-02
epoch 030/050 | total=22.397539 | rec=0.081980 | mgcl=6.461778 | cluster=2.930226 | spatial=0.000000 | SC=off | SNF=off | effC=13.984 | gradC=6.118e-02
epoch 031/050 | total=22.253736 | rec=0.081566 | mgcl=6.425055 | cluster=2.897007 | spatial=0.000000 | SC=off | SNF=off | effC=13.978 | gradC=5.706e-02
epoch 032/050 | total=22.154243 | rec=0.081120 | mgcl=6.401884 | cluster=2.867472 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=5.293e-02
epoch 033/050 | total=22.040337 | rec=0.080645 | mgcl=6.372712 | cluster=2.841557 | spatial=0.000000 | SC=off | SNF=off | effC=13.973 | gradC=4.899e-02
epoch 034/050 | total=21.949471 | rec=0.080143 | mgcl=6.350124 | cluster=2.818954 | spatial=0.000000 | SC=off | SNF=off | effC=13.973 | gradC=4.607e-02
epoch 035/050 | total=21.854618 | rec=0.079614 | mgcl=6.325291 | cluster=2.799129 | spatial=0.000000 | SC=off | SNF=off | effC=13.974 | gradC=4.466e-02
epoch 036/050 | total=21.776661 | rec=0.079059 | mgcl=6.305402 | cluster=2.781394 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=4.526e-02
epoch 037/050 | total=21.699415 | rec=0.078485 | mgcl=6.285333 | cluster=2.764930 | spatial=0.000000 | SC=off | SNF=off | effC=13.979 | gradC=4.846e-02
epoch 038/050 | total=21.617310 | rec=0.077890 | mgcl=6.263562 | cluster=2.748733 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=5.399e-02
epoch 039/050 | total=21.551439 | rec=0.077268 | mgcl=6.247391 | cluster=2.731998 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=6.083e-02
epoch 040/050 | total=21.474672 | rec=0.076617 | mgcl=6.227950 | cluster=2.714207 | spatial=0.000000 | SC=off | SNF=off | effC=13.978 | gradC=6.783e-02
epoch 041/050 | total=21.403883 | rec=0.075934 | mgcl=6.210991 | cluster=2.694977 | spatial=0.000000 | SC=off | SNF=off | effC=13.970 | gradC=7.399e-02
epoch 042/050 | total=21.328312 | rec=0.075215 | mgcl=6.192964 | cluster=2.674206 | spatial=0.000000 | SC=off | SNF=off | effC=13.960 | gradC=7.880e-02
epoch 043/050 | total=21.255831 | rec=0.074474 | mgcl=6.176388 | cluster=2.652194 | spatial=0.000000 | SC=off | SNF=off | effC=13.947 | gradC=8.232e-02
epoch 044/050 | total=21.187277 | rec=0.073715 | mgcl=6.161393 | cluster=2.629384 | spatial=0.000000 | SC=off | SNF=off | effC=13.934 | gradC=8.520e-02
epoch 045/050 | total=21.120031 | rec=0.072926 | mgcl=6.147043 | cluster=2.605976 | spatial=0.000000 | SC=off | SNF=off | effC=13.922 | gradC=8.824e-02
epoch 046/050 | total=21.050117 | rec=0.072098 | mgcl=6.132010 | cluster=2.581990 | spatial=0.000000 | SC=off | SNF=off | effC=13.911 | gradC=9.193e-02
epoch 047/050 | total=20.981840 | rec=0.071242 | mgcl=6.117803 | cluster=2.557189 | spatial=0.000000 | SC=off | SNF=off | effC=13.904 | gradC=9.652e-02
epoch 048/050 | total=20.913660 | rec=0.070367 | mgcl=6.104162 | cluster=2.530807 | spatial=0.000000 | SC=off | SNF=off | effC=13.901 | gradC=1.015e-01
epoch 049/050 | total=20.845085 | rec=0.069477 | mgcl=6.091235 | cluster=2.501904 | spatial=0.000000 | SC=off | SNF=off | effC=13.901 | gradC=1.062e-01
epoch 050/050 | total=20.772095 | rec=0.068587 | mgcl=6.077937 | cluster=2.469697 | spatial=0.000000 | SC=off | SNF=off | effC=13.904 | gradC=1.099e-01
ARI=0.483940 | NMI=0.474030
Output directory: /content/SpaMGCL/SpaMGCL/results/e185_t025_mgcl3
Saved metrics: /content/SpaMGCL/SpaMGCL/results/e185_t025_mgcl3/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/e185_t025_mgcl3/config.yaml
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: E18.5 | spots=2129 | device=cuda
Modalities: RNA, ATAC | label=Combined_Clusters
Spatial graph: shape=(2129, 2129), nnz=7784
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=23.166977 | rec=0.160812 | mgcl=7.668722 | cluster=3.297991 | spatial=0.000000 | SC=off | SNF=off | effC=13.976 | gradC=0.000e+00
epoch 002/050 | total=23.126156 | rec=0.148331 | mgcl=7.659275 | cluster=3.297535 | spatial=0.000000 | SC=off | SNF=off | effC=13.982 | gradC=0.000e+00
epoch 003/050 | total=23.084658 | rec=0.137186 | mgcl=7.649157 | cluster=3.297148 | spatial=0.000000 | SC=off | SNF=off | effC=13.986 | gradC=0.000e+00
epoch 004/050 | total=23.024109 | rec=0.127556 | mgcl=7.632185 | cluster=3.296817 | spatial=0.000000 | SC=off | SNF=off | effC=13.990 | gradC=0.000e+00
epoch 005/050 | total=22.928083 | rec=0.119453 | mgcl=7.602877 | cluster=3.296538 | spatial=0.000000 | SC=off | SNF=off | effC=13.993 | gradC=0.000e+00
epoch 006/050 | total=22.785595 | rec=0.112694 | mgcl=7.557634 | cluster=3.296315 | spatial=0.000000 | SC=off | SNF=off | effC=13.995 | gradC=0.000e+00
epoch 007/050 | total=22.622030 | rec=0.107028 | mgcl=7.505001 | cluster=3.296149 | spatial=0.000000 | SC=off | SNF=off | effC=13.997 | gradC=0.000e+00
epoch 008/050 | total=22.481274 | rec=0.102244 | mgcl=7.459676 | cluster=3.296038 | spatial=0.000000 | SC=off | SNF=off | effC=13.998 | gradC=0.000e+00
epoch 009/050 | total=22.337906 | rec=0.098258 | mgcl=7.413216 | cluster=3.295972 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 010/050 | total=22.201519 | rec=0.095103 | mgcl=7.368805 | cluster=3.295939 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=0.000e+00
epoch 011/050 | total=25.376490 | rec=0.092690 | mgcl=7.329291 | cluster=3.295926 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=3.364e-03
epoch 012/050 | total=25.262367 | rec=0.090987 | mgcl=7.291883 | cluster=3.295728 | spatial=0.000000 | SC=off | SNF=off | effC=14.000 | gradC=3.993e-03
epoch 013/050 | total=25.167427 | rec=0.089801 | mgcl=7.260870 | cluster=3.295018 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=9.794e-03
epoch 014/050 | total=25.000858 | rec=0.088953 | mgcl=7.206324 | cluster=3.292932 | spatial=0.000000 | SC=off | SNF=off | effC=13.999 | gradC=1.768e-02

论文里建议主报 t03_mgcl3（ARI 高、NMI 也不差），附 t025_mgcl4 作为平衡点

In [24]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

with open("configs/e185_t03_mgcl3.yaml") as f:
    e185_best = yaml.safe_load(f)

# 派生 HLN-A1 版本
cfg = yaml.safe_load(yaml.safe_dump(e185_best))
cfg["experiment"]["name"] = "hlna1_t03_mgcl3"
cfg["experiment"]["dataset"] = "HLN-A1"
cfg["data"]["label_key"] = "Spatial_Label"
cfg["model"]["num_clusters"] = 10
cfg["clustering"]["n_clusters"] = 10
cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
cfg["output"] = {"root": "results"}
with open("configs/hlna1_t03_mgcl3.yaml", "w") as f:
    yaml.dump(cfg, f, default_flow_style=False)
print("生成 hlna1_t03_mgcl3")

!rm -rf results/hlna1_t03_mgcl3
!python experiments/run_exp.py --config configs/hlna1_t03_mgcl3.yaml

with open("results/hlna1_t03_mgcl3/metrics.json") as f:
    d = json.load(f)
print(f"HLN-A1 t03_mgcl3: ARI={d['ARI']:.4f}  NMI={d['NMI']:.4f}")
print(f"HLN-A1 基准:      ARI=0.2894  NMI=0.3539")

/content/SpaMGCL/SpaMGCL
生成 hlna1_t03_mgcl3
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=24.706766 | rec=0.213358 | mgcl=8.164470 | cluster=2.946114 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 002/050 | total=24.657948 | rec=0.199251 | mgcl=8.152899 | cluster=2.945764 | spatial=0.000000 | SC=off | SNF=off | effC=9.990 | gradC=0.000e+00
epoch 003/050 | total=24.624865 | rec=0.186240 | mgcl=8.146209 | cluster=2.945432 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=0.000e+00
epoch 004/050 | total=24.581125 | rec=0.174341 | mgcl=8.135594 | cluster=2.945150 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=0.000e+00
epoch 005/050 | total=24.511986 | rec=0.163605 | mgcl=8.116127 | cluster=2.944919 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=0.000e+00
epoch 006/050 | total=24.401438 | rec=0.154161 | mgcl=8.082425 | cluster=2.944743 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=0.000e+00
epoch 007/050 | total=24.228165 | rec=0.146083 | mgcl=8.027360 | cluster=2.944622 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=0.000e+00
epoch 008/050 | total=23.980064 | rec=0.139281 | mgcl=7.946928 | cluster=2.944551 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 009/050 | total=23.707592 | rec=0.133600 | mgcl=7.857997 | cluster=2.944516 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 010/050 | total=23.477943 | rec=0.129053 | mgcl=7.782963 | cluster=2.944505 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 011/050 | total=26.232300 | rec=0.125593 | mgcl=7.720735 | cluster=2.944503 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.864e-03
epoch 012/050 | total=26.069614 | rec=0.123205 | mgcl=7.667355 | cluster=2.944346 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.221e-03
epoch 013/050 | total=25.934050 | rec=0.121590 | mgcl=7.622840 | cluster=2.943939 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=6.784e-03
epoch 014/050 | total=25.754963 | rec=0.120474 | mgcl=7.563865 | cluster=2.942894 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.033e-02
epoch 015/050 | total=25.606609 | rec=0.119583 | mgcl=7.515347 | cluster=2.940987 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.432e-02
epoch 016/050 | total=25.415121 | rec=0.118759 | mgcl=7.452780 | cluster=2.938022 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.880e-02
epoch 017/050 | total=25.283642 | rec=0.117894 | mgcl=7.410638 | cluster=2.933833 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=2.357e-02
epoch 018/050 | total=25.117022 | rec=0.116939 | mgcl=7.357272 | cluster=2.928267 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=2.843e-02
epoch 019/050 | total=24.988323 | rec=0.115905 | mgcl=7.317060 | cluster=2.921236 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=3.322e-02
epoch 020/050 | total=24.845140 | rec=0.114829 | mgcl=7.272561 | cluster=2.912631 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=3.792e-02
epoch 021/050 | total=24.708351 | rec=0.113762 | mgcl=7.230808 | cluster=2.902164 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=4.274e-02
epoch 022/050 | total=24.552708 | rec=0.112700 | mgcl=7.183445 | cluster=2.889671 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=4.765e-02
epoch 023/050 | total=24.425629 | rec=0.111623 | mgcl=7.146293 | cluster=2.875127 | spatial=0.000000 | SC=off | SNF=off | effC=9.993 | gradC=5.252e-02
epoch 024/050 | total=24.295319 | rec=0.110525 | mgcl=7.108790 | cluster=2.858423 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=5.719e-02
epoch 025/050 | total=24.172199 | rec=0.109412 | mgcl=7.074513 | cluster=2.839250 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=6.166e-02
epoch 026/050 | total=24.041210 | rec=0.108279 | mgcl=7.038565 | cluster=2.817238 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=6.613e-02
epoch 027/050 | total=23.918289 | rec=0.107112 | mgcl=7.006320 | cluster=2.792216 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=7.062e-02
epoch 028/050 | total=23.795128 | rec=0.105894 | mgcl=6.975014 | cluster=2.764193 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=7.508e-02
epoch 029/050 | total=23.681192 | rec=0.104632 | mgcl=6.947826 | cluster=2.733083 | spatial=0.000000 | SC=off | SNF=off | effC=9.990 | gradC=7.952e-02
epoch 030/050 | total=23.568741 | rec=0.103332 | mgcl=6.922132 | cluster=2.699013 | spatial=0.000000 | SC=off | SNF=off | effC=9.990 | gradC=8.374e-02
epoch 031/050 | total=23.457699 | rec=0.101995 | mgcl=6.897808 | cluster=2.662279 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=8.758e-02
epoch 032/050 | total=23.350365 | rec=0.100640 | mgcl=6.875589 | cluster=2.622958 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=9.125e-02
epoch 033/050 | total=23.243013 | rec=0.099264 | mgcl=6.854123 | cluster=2.581378 | spatial=0.000000 | SC=off | SNF=off | effC=9.993 | gradC=9.502e-02
epoch 034/050 | total=23.141031 | rec=0.097880 | mgcl=6.835094 | cluster=2.537870 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=9.900e-02
epoch 035/050 | total=23.039051 | rec=0.096502 | mgcl=6.816692 | cluster=2.492471 | spatial=0.000000 | SC=off | SNF=off | effC=9.995 | gradC=1.031e-01
epoch 036/050 | total=22.934978 | rec=0.095115 | mgcl=6.798233 | cluster=2.445163 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=1.071e-01
epoch 037/050 | total=22.830002 | rec=0.093710 | mgcl=6.780094 | cluster=2.396010 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=1.110e-01
epoch 038/050 | total=22.728731 | rec=0.092298 | mgcl=6.763823 | cluster=2.344965 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=1.146e-01
epoch 039/050 | total=22.626026 | rec=0.090880 | mgcl=6.747685 | cluster=2.292090 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=1.176e-01
epoch 040/050 | total=22.525520 | rec=0.089453 | mgcl=6.732758 | cluster=2.237794 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=1.197e-01
epoch 041/050 | total=22.423203 | rec=0.088022 | mgcl=6.717493 | cluster=2.182702 | spatial=0.000000 | SC=off | SNF=off | effC=9.968 | gradC=1.205e-01
epoch 042/050 | total=22.322132 | rec=0.086592 | mgcl=6.702734 | cluster=2.127337 | spatial=0.000000 | SC=off | SNF=off | effC=9.953 | gradC=1.203e-01
epoch 043/050 | total=22.223139 | rec=0.085175 | mgcl=6.688591 | cluster=2.072191 | spatial=0.000000 | SC=off | SNF=off | effC=9.935 | gradC=1.195e-01
epoch 044/050 | total=22.125494 | rec=0.083788 | mgcl=6.674659 | cluster=2.017729 | spatial=0.000000 | SC=off | SNF=off | effC=9.915 | gradC=1.185e-01
epoch 045/050 | total=22.031075 | rec=0.082439 | mgcl=6.661479 | cluster=1.964198 | spatial=0.000000 | SC=off | SNF=off | effC=9.891 | gradC=1.177e-01
epoch 046/050 | total=21.938280 | rec=0.081128 | mgcl=6.648533 | cluster=1.911552 | spatial=0.000000 | SC=off | SNF=off | effC=9.865 | gradC=1.168e-01
epoch 047/050 | total=21.847233 | rec=0.079856 | mgcl=6.635866 | cluster=1.859779 | spatial=0.000000 | SC=off | SNF=off | effC=9.836 | gradC=1.151e-01
epoch 048/050 | total=21.759188 | rec=0.078621 | mgcl=6.623854 | cluster=1.809006 | spatial=0.000000 | SC=off | SNF=off | effC=9.806 | gradC=1.128e-01
epoch 049/050 | total=21.672987 | rec=0.077414 | mgcl=6.611982 | cluster=1.759628 | spatial=0.000000 | SC=off | SNF=off | effC=9.776 | gradC=1.106e-01
epoch 050/050 | total=21.589270 | rec=0.076234 | mgcl=6.600280 | cluster=1.712197 | spatial=0.000000 | SC=off | SNF=off | effC=9.745 | gradC=1.089e-01
ARI=0.205013 | NMI=0.291781
Output directory: /content/SpaMGCL/SpaMGCL/results/hlna1_t03_mgcl3
Saved metrics: /content/SpaMGCL/SpaMGCL/results/hlna1_t03_mgcl3/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/hlna1_t03_mgcl3/config.yaml
HLN-A1 t03_mgcl3: ARI=0.2050  NMI=0.2918
HLN-A1 基准:      ARI=0.2894  NMI=0.3539

| 数据集 | fine_dim | cluster_temp | lambda_mgcl | ARI | NMI |
|---|---|---|---|---|---|
| HLN-A1 | 32 | 1.0 | 1.0 | 0.2894 | 0.3539 |
| E18.5 | 128 | 0.3 | 3.0 | 0.4963 | 0.4712 |

In [6]:
!ls /content/SpaMGCL/SpaMGCL/configs/ | grep -i hlna1
!ls /content/SpaMGCL/SpaMGCL/configs/ | grep -i e185

diagnostic_hlna1_fine128.yaml
diagnostic_hlna1_fine16.yaml
diagnostic_hlna1_fine32.yaml
diagnostic_hlna1_fine64.yaml
p1_hlna1.yaml
e185_ablation_core.yaml
e185_ablation_sc_snf.yaml
e185_ablation_sc.yaml
p1_e185.yaml

In [7]:
%cd /content/SpaMGCL/SpaMGCL

import yaml, json
import pandas as pd

# 用 fine32 作为 base
with open("configs/diagnostic_hlna1_fine32.yaml") as f:
    base = yaml.safe_load(f)

# 先把 base 对齐到 HLN-A1 最佳 baseline
base["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
base["data"]["label_key"] = "Spatial_Label"
base["loss"]["lambda_cluster"] = 0.1
base["loss"]["lambda_spatial"] = 0.0
base["spatial"] = {"enabled": False, "consistency_weighting": False, "negative_filter": False}
base["training"]["cluster_head_lr_multiplier"] = 8.0
base["training"]["spatial_start_epoch"] = 999
base["output"] = {"root": "results"}

variants = {
    "hlna1_t2":        {"model": {"cluster_temperature": 2.0}},
    "hlna1_t05":       {"model": {"cluster_temperature": 0.5}},
    "hlna1_mgcl2":     {"loss": {"lambda_mgcl": 2.0}},
    "hlna1_mgcl3":     {"loss": {"lambda_mgcl": 3.0}},
    "hlna1_t2_mgcl2":  {"model": {"cluster_temperature": 2.0}, "loss": {"lambda_mgcl": 2.0}},
}

for name, patch in variants.items():
    cfg = yaml.safe_load(yaml.safe_dump(base))
    cfg["experiment"]["name"] = name
    for sec, kv in patch.items():
        for k, v in kv.items():
            cfg[sec][k] = v
    with open(f"configs/{name}.yaml", "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"生成 {name}")

!rm -rf results/hlna1_t2 results/hlna1_t05 results/hlna1_mgcl2 results/hlna1_mgcl3 results/hlna1_t2_mgcl2

!python experiments/run_exp.py --config configs/hlna1_t2.yaml
!python experiments/run_exp.py --config configs/hlna1_t05.yaml
!python experiments/run_exp.py --config configs/hlna1_mgcl2.yaml
!python experiments/run_exp.py --config configs/hlna1_mgcl3.yaml
!python experiments/run_exp.py --config configs/hlna1_t2_mgcl2.yaml

rows = [{"config": "hlna1 基准 (fine32, λc=0.1, t=1, mgcl=1)", "ARI": 0.2894, "NMI": 0.3539}]
for name in ["hlna1_t2", "hlna1_t05", "hlna1_mgcl2", "hlna1_mgcl3", "hlna1_t2_mgcl2"]:
    with open(f"results/{name}/metrics.json") as f:
        d = json.load(f)
    rows.append({
        "config": name,
        "ARI": round(d["ARI"], 4),
        "NMI": round(d["NMI"], 4),
        "effC": round(d["final_cluster_diagnostics"]["effective_clusters"], 3),
    })

print(pd.DataFrame(rows).to_string(index=False))

/content/SpaMGCL/SpaMGCL
生成 hlna1_t2
生成 hlna1_t05
生成 hlna1_mgcl2
生成 hlna1_mgcl3
生成 hlna1_t2_mgcl2
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951205 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950331 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.949540 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.948827 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948182 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361096 | rec=0.205753 | mgcl=8.155343 | cluster=2.947599 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947075 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154637 | cluster=2.946613 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336101 | rec=0.181858 | mgcl=8.154243 | cluster=2.946211 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328271 | rec=0.174488 | mgcl=8.153783 | cluster=2.945869 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.615179 | rec=0.167404 | mgcl=8.153217 | cluster=2.945581 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=1.395e-03
epoch 012/050 | total=8.607621 | rec=0.160600 | mgcl=8.152497 | cluster=2.945228 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=1.146e-03
epoch 013/050 | total=8.600134 | rec=0.154075 | mgcl=8.151571 | cluster=2.944879 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=8.227e-04
epoch 014/050 | total=8.592641 | rec=0.147824 | mgcl=8.150353 | cluster=2.944634 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.803e-04
epoch 015/050 | total=8.585046 | rec=0.141847 | mgcl=8.148746 | cluster=2.944529 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.408e-04
epoch 016/050 | total=8.577205 | rec=0.136141 | mgcl=8.146609 | cluster=2.944544 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.451e-04
epoch 017/050 | total=8.568941 | rec=0.130708 | mgcl=8.143771 | cluster=2.944620 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.364e-04
epoch 018/050 | total=8.560003 | rec=0.125554 | mgcl=8.139980 | cluster=2.944689 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.546e-04
epoch 019/050 | total=8.550068 | rec=0.120684 | mgcl=8.134913 | cluster=2.944710 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.825e-04
epoch 020/050 | total=8.538752 | rec=0.116108 | mgcl=8.128175 | cluster=2.944686 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.351e-04
epoch 021/050 | total=8.525526 | rec=0.111836 | mgcl=8.119226 | cluster=2.944636 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.385e-04
epoch 022/050 | total=8.509754 | rec=0.107877 | mgcl=8.107419 | cluster=2.944586 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.226e-04
epoch 023/050 | total=8.490830 | rec=0.104238 | mgcl=8.092137 | cluster=2.944549 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.201e-04
epoch 024/050 | total=8.468362 | rec=0.100920 | mgcl=8.072989 | cluster=2.944530 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.646e-04
epoch 025/050 | total=8.442253 | rec=0.097919 | mgcl=8.049882 | cluster=2.944522 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.648e-04
epoch 026/050 | total=8.412899 | rec=0.095222 | mgcl=8.023225 | cluster=2.944519 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.893e-04
epoch 027/050 | total=8.381469 | rec=0.092811 | mgcl=7.994207 | cluster=2.944513 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.064e-04
epoch 028/050 | total=8.347655 | rec=0.090662 | mgcl=7.962543 | cluster=2.944502 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.037e-04
epoch 029/050 | total=8.310266 | rec=0.088755 | mgcl=7.927063 | cluster=2.944487 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.857e-04
epoch 030/050 | total=8.269135 | rec=0.087077 | mgcl=7.887611 | cluster=2.944467 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.602e-04
epoch 031/050 | total=8.225882 | rec=0.085603 | mgcl=7.845834 | cluster=2.944445 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.332e-04
epoch 032/050 | total=8.184158 | rec=0.084323 | mgcl=7.805393 | cluster=2.944420 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.099e-04
epoch 033/050 | total=8.145399 | rec=0.083211 | mgcl=7.767750 | cluster=2.944392 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.915e-04
epoch 034/050 | total=8.111545 | rec=0.082242 | mgcl=7.734868 | cluster=2.944359 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.830e-04
epoch 035/050 | total=8.077377 | rec=0.081384 | mgcl=7.701561 | cluster=2.944320 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.836e-04
epoch 036/050 | total=8.034760 | rec=0.080636 | mgcl=7.659697 | cluster=2.944274 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.951e-04
epoch 037/050 | total=8.006001 | rec=0.079959 | mgcl=7.631620 | cluster=2.944214 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.119e-04
epoch 038/050 | total=7.962288 | rec=0.079378 | mgcl=7.588497 | cluster=2.944134 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.233e-04
epoch 039/050 | total=7.929565 | rec=0.078869 | mgcl=7.556294 | cluster=2.944028 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.306e-04
epoch 040/050 | total=7.887371 | rec=0.078411 | mgcl=7.514571 | cluster=2.943892 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.399e-04
epoch 041/050 | total=7.852539 | rec=0.078016 | mgcl=7.480151 | cluster=2.943719 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.563e-04
epoch 042/050 | total=7.814455 | rec=0.077688 | mgcl=7.442417 | cluster=2.943498 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.813e-04
epoch 043/050 | total=7.781981 | rec=0.077417 | mgcl=7.410242 | cluster=2.943218 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.157e-04
epoch 044/050 | total=7.747438 | rec=0.077183 | mgcl=7.375968 | cluster=2.942872 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.575e-04
epoch 045/050 | total=7.717828 | rec=0.076981 | mgcl=7.346603 | cluster=2.942446 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.064e-04
epoch 046/050 | total=7.689757 | rec=0.076810 | mgcl=7.318754 | cluster=2.941927 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.634e-04
epoch 047/050 | total=7.662148 | rec=0.076663 | mgcl=7.291355 | cluster=2.941301 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.274e-04
epoch 048/050 | total=7.639052 | rec=0.076523 | mgcl=7.268473 | cluster=2.940562 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.966e-04
epoch 049/050 | total=7.615050 | rec=0.076384 | mgcl=7.244695 | cluster=2.939702 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.699e-04
epoch 050/050 | total=7.596228 | rec=0.076247 | mgcl=7.226111 | cluster=2.938700 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.471e-04
ARI=0.284819 | NMI=0.329478
Output directory: /content/SpaMGCL/SpaMGCL/results/hlna1_t2
Saved metrics: /content/SpaMGCL/SpaMGCL/results/hlna1_t2/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/hlna1_t2/config.yaml
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951065 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950217 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389495 | rec=0.232628 | mgcl=8.156867 | cluster=2.949446 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.948750 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948120 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361094 | rec=0.205753 | mgcl=8.155341 | cluster=2.947548 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947035 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154637 | cluster=2.946580 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336101 | rec=0.181858 | mgcl=8.154243 | cluster=2.946185 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328271 | rec=0.174488 | mgcl=8.153783 | cluster=2.945848 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.615176 | rec=0.167404 | mgcl=8.153216 | cluster=2.945565 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=1.395e-03
epoch 012/050 | total=8.607621 | rec=0.160600 | mgcl=8.152499 | cluster=2.945212 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=1.147e-03
epoch 013/050 | total=8.600131 | rec=0.154075 | mgcl=8.151570 | cluster=2.944861 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=8.242e-04
epoch 014/050 | total=8.592639 | rec=0.147824 | mgcl=8.150353 | cluster=2.944611 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.835e-04
epoch 015/050 | total=8.585043 | rec=0.141847 | mgcl=8.148746 | cluster=2.944499 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.440e-04
epoch 016/050 | total=8.577201 | rec=0.136141 | mgcl=8.146609 | cluster=2.944504 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.469e-04
epoch 017/050 | total=8.568935 | rec=0.130708 | mgcl=8.143771 | cluster=2.944570 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.419e-04
epoch 018/050 | total=8.559998 | rec=0.125554 | mgcl=8.139980 | cluster=2.944628 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.665e-04
epoch 019/050 | total=8.550061 | rec=0.120684 | mgcl=8.134912 | cluster=2.944641 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=7.023e-04
epoch 020/050 | total=8.538741 | rec=0.116108 | mgcl=8.128173 | cluster=2.944605 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.629e-04
epoch 021/050 | total=8.525512 | rec=0.111836 | mgcl=8.119222 | cluster=2.944540 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.734e-04
epoch 022/050 | total=8.509737 | rec=0.107877 | mgcl=8.107413 | cluster=2.944464 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.621e-04
epoch 023/050 | total=8.490806 | rec=0.104239 | mgcl=8.092128 | cluster=2.944390 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.589e-04
epoch 024/050 | total=8.468325 | rec=0.100921 | mgcl=8.072972 | cluster=2.944317 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.949e-04
epoch 025/050 | total=8.442201 | rec=0.097920 | mgcl=8.049857 | cluster=2.944237 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.876e-04
epoch 026/050 | total=8.412825 | rec=0.095223 | mgcl=8.023189 | cluster=2.944133 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.185e-04
epoch 027/050 | total=8.381366 | rec=0.092812 | mgcl=7.994156 | cluster=2.943986 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.583e-04
epoch 028/050 | total=8.347522 | rec=0.090664 | mgcl=7.962481 | cluster=2.943777 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.945e-04
epoch 029/050 | total=8.310091 | rec=0.088757 | mgcl=7.926985 | cluster=2.943487 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.319e-04
epoch 030/050 | total=8.268915 | rec=0.087080 | mgcl=7.887526 | cluster=2.943094 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.820e-04
epoch 031/050 | total=8.225624 | rec=0.085607 | mgcl=7.845761 | cluster=2.942571 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.541e-04
epoch 032/050 | total=8.183851 | rec=0.084328 | mgcl=7.805335 | cluster=2.941884 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.527e-04
epoch 033/050 | total=8.144892 | rec=0.083217 | mgcl=7.767577 | cluster=2.940982 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.779e-04
epoch 034/050 | total=8.110368 | rec=0.082249 | mgcl=7.734137 | cluster=2.939822 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=9.264e-04
epoch 035/050 | total=8.077581 | rec=0.081394 | mgcl=7.702353 | cluster=2.938349 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.094e-03
epoch 036/050 | total=8.033945 | rec=0.080646 | mgcl=7.659644 | cluster=2.936552 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.272e-03
epoch 037/050 | total=8.005562 | rec=0.079971 | mgcl=7.632155 | cluster=2.934357 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.467e-03
epoch 038/050 | total=7.960937 | rec=0.079394 | mgcl=7.588372 | cluster=2.931710 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.675e-03
epoch 039/050 | total=7.928682 | rec=0.078888 | mgcl=7.556940 | cluster=2.928551 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.893e-03
epoch 040/050 | total=7.885476 | rec=0.078435 | mgcl=7.514551 | cluster=2.924905 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.116e-03
epoch 041/050 | total=7.850951 | rec=0.078044 | mgcl=7.480835 | cluster=2.920719 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.344e-03
epoch 042/050 | total=7.811892 | rec=0.077723 | mgcl=7.442583 | cluster=2.915859 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.581e-03
epoch 043/050 | total=7.779135 | rec=0.077459 | mgcl=7.410646 | cluster=2.910301 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.822e-03
epoch 044/050 | total=7.744112 | rec=0.077233 | mgcl=7.376462 | cluster=2.904162 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.058e-03
epoch 045/050 | total=7.713419 | rec=0.077039 | mgcl=7.346637 | cluster=2.897423 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.290e-03
epoch 046/050 | total=7.685195 | rec=0.076880 | mgcl=7.319323 | cluster=2.889926 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.526e-03
epoch 047/050 | total=7.656382 | rec=0.076746 | mgcl=7.291471 | cluster=2.881650 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.769e-03
epoch 048/050 | total=7.632835 | rec=0.076620 | mgcl=7.268941 | cluster=2.872738 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.011e-03
epoch 049/050 | total=7.608023 | rec=0.076498 | mgcl=7.245205 | cluster=2.863201 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.249e-03
epoch 050/050 | total=7.587883 | rec=0.076379 | mgcl=7.226217 | cluster=2.852865 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.488e-03
ARI=0.287450 | NMI=0.356697
Output directory: /content/SpaMGCL/SpaMGCL/results/hlna1_t05
Saved metrics: /content/SpaMGCL/SpaMGCL/results/hlna1_t05/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/hlna1_t05/config.yaml
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:149: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=16.570969 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=16.557932 | rec=0.242478 | mgcl=8.157727 | cluster=2.950299 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=16.546398 | rec=0.232931 | mgcl=8.156734 | cluster=2.949521 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=16.535841 | rec=0.223731 | mgcl=8.156054 | cluster=2.948817 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=16.525955 | rec=0.214877 | mgcl=8.155540 | cluster=2.948178 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=16.516571 | rec=0.206359 | mgcl=8.155107 | cluster=2.947599 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00

| 数据集 | fine_dim | cluster_temp | lambda_mgcl | ARI | NMI |
|---|---|---|---|---|---|
| HLN-A1 | 32 | 1.0 | 1.0 | 0.2894 | 0.3539 |
| E18.5 | 128 | 0.3 | 3.0 | 0.4963 | 0.4712 |

cella:修正诊断配置的 data.root

In [11]:
import os
import yaml

os.chdir("/content/SpaMGCL/SpaMGCL")

# 修正所有诊断配置文件的 data.root
for d in [16, 32, 64, 128]:
    path = f"configs/diagnostic_hlna1_fine{d}.yaml"
    with open(path, "r") as f:
        cfg = yaml.safe_load(f)
    cfg["data"]["root"] = "/content/drive/MyDrive/SMGC-data/"
    with open(path, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"✅ 已修正 {path} 的 data.root")

# 验证一下
for d in [16, 32, 64, 128]:
    with open(f"configs/diagnostic_hlna1_fine{d}.yaml", "r") as f:
        cfg = yaml.safe_load(f)
    print(f"fine{d}: data.root = {cfg['data']['root']}")

✅ 已修正 configs/diagnostic_hlna1_fine16.yaml 的 data.root
✅ 已修正 configs/diagnostic_hlna1_fine32.yaml 的 data.root
✅ 已修正 configs/diagnostic_hlna1_fine64.yaml 的 data.root
✅ 已修正 configs/diagnostic_hlna1_fine128.yaml 的 data.root
fine16: data.root = /content/drive/MyDrive/SMGC-data/
fine32: data.root = /content/drive/MyDrive/SMGC-data/
fine64: data.root = /content/drive/MyDrive/SMGC-data/
fine128: data.root = /content/drive/MyDrive/SMGC-data/

cellb:批量运行 fine_dim=16/32/64/128

In [12]:
%%bash
cd /content/SpaMGCL/SpaMGCL

for d in 16 32 64 128; do
    echo "=========================================="
    echo "🚀 开始 fine_dim=${d}"
    echo "=========================================="
    python experiments/run_exp.py --config configs/diagnostic_hlna1_fine${d}.yaml
    echo "✅ fine_dim=${d} 完成"
    echo ""
done

==========================================
🚀 开始 fine_dim=16
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.405149 | rec=0.248008 | mgcl=8.157142 | cluster=2.959329 | spatial=0.000000 | SC=off | SNF=off | effC=9.858 | gradC=0.000e+00
epoch 002/050 | total=8.394496 | rec=0.237817 | mgcl=8.156678 | cluster=2.958024 | spatial=0.000000 | SC=off | SNF=off | effC=9.871 | gradC=0.000e+00
epoch 003/050 | total=8.384409 | rec=0.228064 | mgcl=8.156344 | cluster=2.956799 | spatial=0.000000 | SC=off | SNF=off | effC=9.882 | gradC=0.000e+00
epoch 004/050 | total=8.374840 | rec=0.218736 | mgcl=8.156104 | cluster=2.955626 | spatial=0.000000 | SC=off | SNF=off | effC=9.894 | gradC=0.000e+00
epoch 005/050 | total=8.365738 | rec=0.209811 | mgcl=8.155927 | cluster=2.954504 | spatial=0.000000 | SC=off | SNF=off | effC=9.904 | gradC=0.000e+00
epoch 006/050 | total=8.357061 | rec=0.201272 | mgcl=8.155789 | cluster=2.953441 | spatial=0.000000 | SC=off | SNF=off | effC=9.915 | gradC=0.000e+00
epoch 007/050 | total=8.348775 | rec=0.193100 | mgcl=8.155675 | cluster=2.952448 | spatial=0.000000 | SC=off | SNF=off | effC=9.924 | gradC=0.000e+00
epoch 008/050 | total=8.340852 | rec=0.185279 | mgcl=8.155573 | cluster=2.951529 | spatial=0.000000 | SC=off | SNF=off | effC=9.933 | gradC=0.000e+00
epoch 009/050 | total=8.333262 | rec=0.177793 | mgcl=8.155469 | cluster=2.950683 | spatial=0.000000 | SC=off | SNF=off | effC=9.941 | gradC=0.000e+00
epoch 010/050 | total=8.325993 | rec=0.170632 | mgcl=8.155361 | cluster=2.949912 | spatial=0.000000 | SC=off | SNF=off | effC=9.949 | gradC=0.000e+00
epoch 011/050 | total=23.065084 | rec=0.163781 | mgcl=8.155246 | cluster=2.949212 | spatial=0.000000 | SC=off | SNF=off | effC=9.955 | gradC=1.575e-01
epoch 012/050 | total=23.055433 | rec=0.157271 | mgcl=8.155115 | cluster=2.948609 | spatial=0.000000 | SC=off | SNF=off | effC=9.961 | gradC=1.463e-01
epoch 013/050 | total=23.045408 | rec=0.151073 | mgcl=8.154969 | cluster=2.947873 | spatial=0.000000 | SC=off | SNF=off | effC=9.969 | gradC=1.315e-01
epoch 014/050 | total=23.035637 | rec=0.145162 | mgcl=8.154795 | cluster=2.947136 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=1.148e-01
epoch 015/050 | total=23.026480 | rec=0.139522 | mgcl=8.154590 | cluster=2.946474 | spatial=0.000000 | SC=off | SNF=off | effC=9.982 | gradC=9.743e-02
epoch 016/050 | total=23.018097 | rec=0.134136 | mgcl=8.154342 | cluster=2.945924 | spatial=0.000000 | SC=off | SNF=off | effC=9.988 | gradC=8.037e-02
epoch 017/050 | total=23.010515 | rec=0.128991 | mgcl=8.154041 | cluster=2.945497 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=6.430e-02
epoch 018/050 | total=23.003677 | rec=0.124073 | mgcl=8.153670 | cluster=2.945187 | spatial=0.000000 | SC=off | SNF=off | effC=9.995 | gradC=4.979e-02
epoch 019/050 | total=22.997482 | rec=0.119375 | mgcl=8.153203 | cluster=2.944981 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=3.762e-02
epoch 020/050 | total=22.991791 | rec=0.114888 | mgcl=8.152606 | cluster=2.944859 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.908e-02
epoch 021/050 | total=22.986473 | rec=0.110605 | mgcl=8.151844 | cluster=2.944805 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.582e-02
epoch 022/050 | total=22.981390 | rec=0.106522 | mgcl=8.150891 | cluster=2.944795 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.764e-02
epoch 023/050 | total=22.976383 | rec=0.102636 | mgcl=8.149706 | cluster=2.944808 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.189e-02
epoch 024/050 | total=22.971268 | rec=0.098941 | mgcl=8.148202 | cluster=2.944825 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.615e-02
epoch 025/050 | total=22.965862 | rec=0.095434 | mgcl=8.146277 | cluster=2.944830 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=3.918e-02
epoch 026/050 | total=22.959997 | rec=0.092112 | mgcl=8.143801 | cluster=2.944817 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=4.047e-02
epoch 027/050 | total=22.953476 | rec=0.088974 | mgcl=8.140585 | cluster=2.944783 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=3.995e-02
epoch 028/050 | total=22.946060 | rec=0.086019 | mgcl=8.136367 | cluster=2.944735 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=3.783e-02
epoch 029/050 | total=22.937447 | rec=0.083249 | mgcl=8.130799 | cluster=2.944680 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.454e-02
epoch 030/050 | total=22.927254 | rec=0.080671 | mgcl=8.123455 | cluster=2.944626 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.062e-02
epoch 031/050 | total=22.915001 | rec=0.078290 | mgcl=8.113835 | cluster=2.944575 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.663e-02
epoch 032/050 | total=22.900101 | rec=0.076114 | mgcl=8.101339 | cluster=2.944529 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.305e-02
epoch 033/050 | total=22.881836 | rec=0.074148 | mgcl=8.085265 | cluster=2.944484 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.017e-02
epoch 034/050 | total=22.859528 | rec=0.072395 | mgcl=8.064960 | cluster=2.944435 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.802e-02
epoch 035/050 | total=22.832924 | rec=0.070856 | mgcl=8.040184 | cluster=2.944377 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.646e-02
epoch 036/050 | total=22.802006 | rec=0.069522 | mgcl=8.010943 | cluster=2.944308 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.531e-02
epoch 037/050 | total=22.767094 | rec=0.068382 | mgcl=7.977587 | cluster=2.944225 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.453e-02
epoch 038/050 | total=22.729435 | rec=0.067419 | mgcl=7.941399 | cluster=2.944124 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.426e-02
epoch 039/050 | total=22.689703 | rec=0.066611 | mgcl=7.903091 | cluster=2.944000 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.469e-02
epoch 040/050 | total=22.648607 | rec=0.065930 | mgcl=7.863436 | cluster=2.943848 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.591e-02
epoch 041/050 | total=22.607147 | rec=0.065359 | mgcl=7.823495 | cluster=2.943658 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.799e-02
epoch 042/050 | total=22.566971 | rec=0.064894 | mgcl=7.784969 | cluster=2.943421 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.079e-02
epoch 043/050 | total=22.528532 | rec=0.064523 | mgcl=7.748379 | cluster=2.943126 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.429e-02
epoch 044/050 | total=22.492104 | rec=0.064234 | mgcl=7.714120 | cluster=2.942750 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.847e-02
epoch 045/050 | total=22.456690 | rec=0.064022 | mgcl=7.681301 | cluster=2.942273 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.340e-02
epoch 046/050 | total=22.424730 | rec=0.063876 | mgcl=7.652503 | cluster=2.941670 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.908e-02
epoch 047/050 | total=22.393345 | rec=0.063753 | mgcl=7.625162 | cluster=2.940886 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.592e-02
epoch 048/050 | total=22.360397 | rec=0.063687 | mgcl=7.597220 | cluster=2.939898 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.380e-02
epoch 049/050 | total=22.329247 | rec=0.063652 | mgcl=7.572416 | cluster=2.938636 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=6.302e-02
epoch 050/050 | total=22.294800 | rec=0.063628 | mgcl=7.546106 | cluster=2.937013 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=7.390e-02
ARI=0.136410 | NMI=0.193117
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine16/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine16/config.yaml
✅ fine_dim=16 完成

==========================================
🚀 开始 fine_dim=32
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.949508 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.948801 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361094 | rec=0.205753 | mgcl=8.155341 | cluster=2.947582 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947062 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344152 | rec=0.189517 | mgcl=8.154635 | cluster=2.946602 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181858 | mgcl=8.154244 | cluster=2.946202 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328271 | rec=0.174488 | mgcl=8.153783 | cluster=2.945862 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=23.048500 | rec=0.167404 | mgcl=8.153216 | cluster=2.945576 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=6.975e-02
epoch 012/050 | total=23.039198 | rec=0.160610 | mgcl=8.152500 | cluster=2.945218 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=5.686e-02
epoch 013/050 | total=23.029991 | rec=0.154098 | mgcl=8.151578 | cluster=2.944863 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=4.020e-02
epoch 014/050 | total=23.021313 | rec=0.147862 | mgcl=8.150367 | cluster=2.944617 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.273e-02
epoch 015/050 | total=23.013247 | rec=0.141897 | mgcl=8.148771 | cluster=2.944516 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.156e-02
epoch 016/050 | total=23.005531 | rec=0.136204 | mgcl=8.146649 | cluster=2.944536 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.843e-02
epoch 017/050 | total=22.997669 | rec=0.130784 | mgcl=8.143826 | cluster=2.944612 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.811e-02
epoch 018/050 | total=22.989079 | rec=0.125642 | mgcl=8.140059 | cluster=2.944675 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.367e-02
epoch 019/050 | total=22.979248 | rec=0.120783 | mgcl=8.135025 | cluster=2.944688 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.450e-02
epoch 020/050 | total=22.967825 | rec=0.116215 | mgcl=8.128339 | cluster=2.944654 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.155e-02
epoch 021/050 | total=22.954399 | rec=0.111947 | mgcl=8.119462 | cluster=2.944598 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.628e-02
epoch 022/050 | total=22.938463 | rec=0.107987 | mgcl=8.107759 | cluster=2.944544 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.031e-02
epoch 023/050 | total=22.919453 | rec=0.104343 | mgcl=8.092601 | cluster=2.944502 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.536e-02
epoch 024/050 | total=22.896921 | rec=0.101018 | mgcl=8.073537 | cluster=2.944473 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.302e-02
epoch 025/050 | total=22.870739 | rec=0.098008 | mgcl=8.050485 | cluster=2.944450 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.332e-02
epoch 026/050 | total=22.841278 | rec=0.095301 | mgcl=8.023873 | cluster=2.944421 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.454e-02
epoch 027/050 | total=22.809608 | rec=0.092881 | mgcl=7.994827 | cluster=2.944380 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.530e-02
epoch 028/050 | total=22.775610 | rec=0.090725 | mgcl=7.963280 | cluster=2.944321 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.519e-02
epoch 029/050 | total=22.737843 | rec=0.088812 | mgcl=7.927826 | cluster=2.944241 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.456e-02
epoch 030/050 | total=22.696060 | rec=0.087130 | mgcl=7.888252 | cluster=2.944136 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.398e-02
epoch 031/050 | total=22.651936 | rec=0.085657 | mgcl=7.846285 | cluster=2.943999 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.392e-02
epoch 032/050 | total=22.609261 | rec=0.084380 | mgcl=7.805780 | cluster=2.943820 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.470e-02
epoch 033/050 | total=22.569647 | rec=0.083277 | mgcl=7.768452 | cluster=2.943584 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.640e-02
epoch 034/050 | total=22.534552 | rec=0.082320 | mgcl=7.735864 | cluster=2.943274 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.900e-02
epoch 035/050 | total=22.493271 | rec=0.081487 | mgcl=7.697472 | cluster=2.942862 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.222e-02
epoch 036/050 | total=22.449856 | rec=0.080759 | mgcl=7.657464 | cluster=2.942327 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.603e-02
epoch 037/050 | total=22.414610 | rec=0.080123 | mgcl=7.626328 | cluster=2.941632 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.053e-02
epoch 038/050 | total=22.369204 | rec=0.079570 | mgcl=7.586030 | cluster=2.940721 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.568e-02
epoch 039/050 | total=22.331940 | rec=0.079109 | mgcl=7.555096 | cluster=2.939547 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.155e-02
epoch 040/050 | total=22.277668 | rec=0.078702 | mgcl=7.508642 | cluster=2.938065 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.846e-02
epoch 041/050 | total=22.236732 | rec=0.078376 | mgcl=7.477534 | cluster=2.936165 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.662e-02
epoch 042/050 | total=22.183556 | rec=0.078144 | mgcl=7.436840 | cluster=2.933714 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.623e-02
epoch 043/050 | total=22.137506 | rec=0.077988 | mgcl=7.406656 | cluster=2.930573 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.754e-02
epoch 044/050 | total=22.081659 | rec=0.077896 | mgcl=7.370722 | cluster=2.926608 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=9.050e-02
epoch 045/050 | total=22.029509 | rec=0.077876 | mgcl=7.343657 | cluster=2.921595 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.053e-01
epoch 046/050 | total=21.970276 | rec=0.077935 | mgcl=7.315931 | cluster=2.915282 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.221e-01
epoch 047/050 | total=21.906010 | rec=0.078066 | mgcl=7.290686 | cluster=2.907451 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.407e-01
epoch 048/050 | total=21.836544 | rec=0.078260 | mgcl=7.268871 | cluster=2.897882 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.609e-01
epoch 049/050 | total=21.757776 | rec=0.078514 | mgcl=7.247293 | cluster=2.886394 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.820e-01
epoch 050/050 | total=21.673599 | rec=0.078829 | mgcl=7.230361 | cluster=2.872882 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.034e-01
ARI=0.262954 | NMI=0.341379
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml
✅ fine_dim=32 完成

==========================================
🚀 开始 fine_dim=64
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.373463 | rec=0.215289 | mgcl=8.158174 | cluster=2.950635 | spatial=0.000000 | SC=off | SNF=off | effC=9.947 | gradC=0.000e+00
epoch 002/050 | total=8.361030 | rec=0.205297 | mgcl=8.155733 | cluster=2.949618 | spatial=0.000000 | SC=off | SNF=off | effC=9.955 | gradC=0.000e+00
epoch 003/050 | total=8.349435 | rec=0.195784 | mgcl=8.153651 | cluster=2.948720 | spatial=0.000000 | SC=off | SNF=off | effC=9.963 | gradC=0.000e+00
epoch 004/050 | total=8.337866 | rec=0.186686 | mgcl=8.151180 | cluster=2.947946 | spatial=0.000000 | SC=off | SNF=off | effC=9.970 | gradC=0.000e+00
epoch 005/050 | total=8.325715 | rec=0.177960 | mgcl=8.147756 | cluster=2.947276 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 006/050 | total=8.312439 | rec=0.169594 | mgcl=8.142845 | cluster=2.946694 | spatial=0.000000 | SC=off | SNF=off | effC=9.981 | gradC=0.000e+00
epoch 007/050 | total=8.297442 | rec=0.161598 | mgcl=8.135844 | cluster=2.946190 | spatial=0.000000 | SC=off | SNF=off | effC=9.985 | gradC=0.000e+00
epoch 008/050 | total=8.279897 | rec=0.154005 | mgcl=8.125892 | cluster=2.945763 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 009/050 | total=8.258702 | rec=0.146858 | mgcl=8.111844 | cluster=2.945407 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=0.000e+00
epoch 010/050 | total=8.232811 | rec=0.140195 | mgcl=8.092616 | cluster=2.945122 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=0.000e+00
epoch 011/050 | total=22.926374 | rec=0.134049 | mgcl=8.067818 | cluster=2.944901 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=4.748e-02
epoch 012/050 | total=22.888460 | rec=0.128454 | mgcl=8.036887 | cluster=2.944624 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.087e-02
epoch 013/050 | total=22.846651 | rec=0.123428 | mgcl=8.000858 | cluster=2.944473 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.457e-02
epoch 014/050 | total=22.806698 | rec=0.118958 | mgcl=7.965359 | cluster=2.944476 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.693e-02
epoch 015/050 | total=22.768894 | rec=0.115032 | mgcl=7.931229 | cluster=2.944527 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.761e-02
epoch 016/050 | total=22.730843 | rec=0.111635 | mgcl=7.896652 | cluster=2.944511 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.321e-02
epoch 017/050 | total=22.690676 | rec=0.108713 | mgcl=7.860030 | cluster=2.944386 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.311e-02
epoch 018/050 | total=22.651869 | rec=0.106186 | mgcl=7.824914 | cluster=2.944154 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.952e-02
epoch 019/050 | total=22.614063 | rec=0.103986 | mgcl=7.791021 | cluster=2.943811 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.583e-02
epoch 020/050 | total=22.575882 | rec=0.102059 | mgcl=7.757156 | cluster=2.943333 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.621e-02
epoch 021/050 | total=22.535618 | rec=0.100355 | mgcl=7.721991 | cluster=2.942655 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.131e-02
epoch 022/050 | total=22.495823 | rec=0.098844 | mgcl=7.688496 | cluster=2.941696 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.931e-02
epoch 023/050 | total=22.459003 | rec=0.097519 | mgcl=7.659653 | cluster=2.940367 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.851e-02

/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(

cellc:汇总 fine_dim 主指标

In [13]:
import json
import pandas as pd

rows = []
for d in [16, 32, 64, 128]:
    path = f"/content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine{d}/metrics.json"
    try:
        with open(path, "r") as f:
            data = json.load(f)
        rows.append({
            "fine_dim": d,
            "Z_mean_ARI": data.get("z_mean_ari", None),
            "Z_concat_ARI": data.get("z_concat_ari", None),
            "Q_argmax_ARI": data.get("ARI", None),
            "NMI": data.get("NMI", None)
        })
    except FileNotFoundError:
        rows.append({"fine_dim": d, "status": "❌ 未找到"})

df = pd.DataFrame(rows)
print(df.to_string(index=False))

 fine_dim Z_mean_ARI Z_concat_ARI  Q_argmax_ARI      NMI
       16       None         None      0.136410 0.193117
       32       None         None      0.262954 0.341379
       64       None         None      0.225507 0.303100
      128       None         None      0.203812 0.306323

| fine_dim |        ARI |        NMI | 排名     |
| -------: | ---------: | ---------: | ------ |
|       16 |     0.1365 |     0.1932 | 最差     |
|   **32** | **0.2629** | **0.3408** | **最好** |
|       64 |     0.2254 |     0.3030 | 次优     |
|      128 |     0.2045 |     0.3066 | 再下降    |

celld:查看 fine_dim 的表示层指标

读取四个 fine_dim 的 representation_metrics

In [14]:
import json

path = "results/diagnostic_hlna1_fine32/metrics.json"

with open(path, "r") as f:
    m = json.load(f)

print("顶层 keys:")
print(m.keys())

print("\n完整 metrics:")
print(json.dumps(m, indent=2, ensure_ascii=False))

顶层 keys:
dict_keys(['dataset', 'seed', 'device', 'epochs', 'warm_up_epochs', 'spatial_start_epoch', 'spatial_mechanism_enabled', 'spatial_weighting_enabled', 'spatial_negative_filter_enabled', 'cluster_enabled_epochs', 'spatial_enabled_epochs', 'clustering_method_requested', 'clustering_method_used', 'clustering_embedding', 'candidate_metrics', 'representation_metrics', 'fine_dim', 'num_clusters', 'ARI', 'NMI', 'metrics', 'final_weights', 'final_cluster_diagnostics', 'data', 'graph_stats', 'loss_history'])

完整 metrics:
{
  "dataset": "HLN-A1",
  "seed": 0,
  "device": "cuda",
  "epochs": 50,
  "warm_up_epochs": 10,
  "spatial_start_epoch": 51,
  "spatial_mechanism_enabled": false,
  "spatial_weighting_enabled": false,
  "spatial_negative_filter_enabled": false,
  "cluster_enabled_epochs": [
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50
  ],
  "spatial_enabled_epochs": [],
  "clustering_method_requested": "argmax",
  "clustering_method_used": "argmax",
  "clustering_embedding": "cluster_probabilities",
  "candidate_metrics": {
    "global": {
      "method": "kmeans",
      "ARI": 0.2317296154441496,
      "NMI": 0.31615483614522866
    },
    "weighted_views": {
      "method": "kmeans",
      "ARI": 0.2482580567249055,
      "NMI": 0.3344084487437432
    },
    "mean_views": {
      "method": "kmeans",
      "ARI": 0.25121777220078917,
      "NMI": 0.3297492495894551
    },
    "cluster_probabilities": {
      "method": "kmeans",
      "ARI": 0.21441535848028573,
      "NMI": 0.3241573837284317
    },
    "concat_views": {
      "method": "kmeans",
      "ARI": 0.2332603600165846,
      "NMI": 0.3190680342911825
    },
    "cluster_argmax": {
      "method": "argmax",
      "ARI": 0.26295407824772854,
      "NMI": 0.34137890350148625
    }
  },
  "representation_metrics": {
    "z_views": {
      "rna_spatial": {
        "method": "kmeans",
        "dim": 32,
        "ARI": 0.25729600083085813,
        "NMI": 0.35100969547081434
      },
      "rna_feature": {
        "method": "kmeans",
        "dim": 32,
        "ARI": 0.23032684692311386,
        "NMI": 0.30609097530981005
      },
      "adt_spatial": {
        "method": "kmeans",
        "dim": 32,
        "ARI": 0.19666771870372993,
        "NMI": 0.29546589542574675
      },
      "adt_feature": {
        "method": "kmeans",
        "dim": 32,
        "ARI": 0.16092287368705535,
        "NMI": 0.24498105877695855
      }
    },
    "mean_z": {
      "method": "kmeans",
      "dim": 32,
      "ARI": 0.23834160603908153,
      "NMI": 0.34649724407105575
    },
    "concat_z": {
      "method": "kmeans",
      "dim": 128,
      "ARI": 0.25519903719248,
      "NMI": 0.35640339309149816
    }
  },
  "fine_dim": 32,
  "num_clusters": 10,
  "ARI": 0.26295407824772854,
  "NMI": 0.34137890350148625,
  "metrics": {
    "ARI": 0.26295407824772854,
    "NMI": 0.34137890350148625
  },
  "final_weights": [
    0.24859631061553955,
    0.2439475655555725,
    0.25360405445098877,
    0.25385209918022156
  ],
  "final_cluster_diagnostics": {
    "assignment_entropy": 2.286647081375122,
    "max_probability": 0.12252700328826904,
    "effective_clusters": 9.998035430908203,
    "min_cluster_mass": 0.0969569981098175,
    "max_cluster_mass": 0.10431431233882904
  },
  "data": {
    "dataset": "HLN-A1",
    "n_spots": 3484,
    "modalities": {
      "RNA": {
        "shape": [
          3484,
          100
        ],
        "dtype": "float32"
      },
      "ADT": {
        "shape": [
          3484,
          31
        ],
        "dtype": "float32"
      }
    },
    "spatial_source": "obsm['spatial']",
    "label_key": "Spatial_Label",
    "modality_paths": {
      "RNA": "/content/drive/MyDrive/SMGC-data/Human_Lymph_Nodes/A1/adata_RNA.h5ad",
      "ADT": "/content/drive/MyDrive/SMGC-data/Human_Lymph_Nodes/A1/adata_ADT.h5ad"
    }
  },
  "graph_stats": {
    "spatial": {
      "shape": [
        3484,
        3484
      ],
      "nnz": 13206
    },
    "feature": {
      "RNA": {
        "shape": [
          3484,
          3484
        ],
        "nnz": 93108
      },
      "ADT": {
        "shape": [
          3484,
          3484
        ],
        "nnz": 90228
      }
    }
  },
  "loss_history": [
    {
      "epoch": 1,
      "total": 8.411676406860352,
      "reconstruction": 0.25238287448883057,
      "sample_contrastive": 8.159293174743652,
      "cluster_contrastive": 2.951158285140991,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.2975404262542725,
      "cluster_max_probability": 0.11471141874790192,
      "cluster_effective_clusters": 9.950251579284668,
      "cluster_min_mass": 0.08757234364748001,
      "cluster_max_mass": 0.11413218080997467,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 2,
      "total": 8.400130271911621,
      "reconstruction": 0.24231328070163727,
      "sample_contrastive": 8.157816886901855,
      "cluster_contrastive": 2.9502930641174316,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.2981698513031006,
      "cluster_max_probability": 0.11375385522842407,
      "cluster_effective_clusters": 9.956424713134766,
      "cluster_min_mass": 0.08815016597509384,
      "cluster_max_mass": 0.11322499811649323,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 3,
      "total": 8.389495849609375,
      "reconstruction": 0.2326279878616333,
      "sample_contrastive": 8.156867980957031,
      "cluster_contrastive": 2.9495081901550293,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.2987422943115234,
      "cluster_max_probability": 0.11278247088193893,
      "cluster_effective_clusters": 9.962044715881348,
      "cluster_min_mass": 0.08871772140264511,
      "cluster_max_mass": 0.11227449029684067,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 4,
      "total": 8.379530906677246,
      "reconstruction": 0.2233143001794815,
      "sample_contrastive": 8.156216621398926,
      "cluster_contrastive": 2.948801040649414,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.2992594242095947,
      "cluster_max_probability": 0.11180902272462845,
      "cluster_effective_clusters": 9.96712875366211,
      "cluster_min_mass": 0.08927077054977417,
      "cluster_max_mass": 0.11127530038356781,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 5,
      "total": 8.370092391967773,
      "reconstruction": 0.21435999870300293,
      "sample_contrastive": 8.155732154846191,
      "cluster_contrastive": 2.9481616020202637,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.299730062484741,
      "cluster_max_probability": 0.11085983365774155,
      "cluster_effective_clusters": 9.971768379211426,
      "cluster_min_mass": 0.08981534838676453,
      "cluster_max_mass": 0.1102471798658371,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 6,
      "total": 8.36109447479248,
      "reconstruction": 0.2057529091835022,
      "sample_contrastive": 8.155341148376465,
      "cluster_contrastive": 2.9475817680358887,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3001623153686523,
      "cluster_max_probability": 0.109953373670578,
      "cluster_effective_clusters": 9.976034164428711,
      "cluster_min_mass": 0.09035741537809372,
      "cluster_max_mass": 0.10948594659566879,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 7,
      "total": 8.35246753692627,
      "reconstruction": 0.19747766852378845,
      "sample_contrastive": 8.154990196228027,
      "cluster_contrastive": 2.947061777114868,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3005564212799072,
      "cluster_max_probability": 0.10909926891326904,
      "cluster_effective_clusters": 9.979926109313965,
      "cluster_min_mass": 0.09090124815702438,
      "cluster_max_mass": 0.10880604386329651,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 8,
      "total": 8.344152450561523,
      "reconstruction": 0.18951749801635742,
      "sample_contrastive": 8.154635429382324,
      "cluster_contrastive": 2.9466018676757812,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.300910234451294,
      "cluster_max_probability": 0.10829222202301025,
      "cluster_effective_clusters": 9.98342514038086,
      "cluster_min_mass": 0.09144989401102066,
      "cluster_max_mass": 0.10810578614473343,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 9,
      "total": 8.336101531982422,
      "reconstruction": 0.18185755610466003,
      "sample_contrastive": 8.154244422912598,
      "cluster_contrastive": 2.946202278137207,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3012208938598633,
      "cluster_max_probability": 0.10751492530107498,
      "cluster_effective_clusters": 9.98650074005127,
      "cluster_min_mass": 0.09200448542833328,
      "cluster_max_mass": 0.10738978534936905,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 10,
      "total": 8.32827091217041,
      "reconstruction": 0.17448844015598297,
      "sample_contrastive": 8.153782844543457,
      "cluster_contrastive": 2.945862293243408,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 0.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": false,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3014886379241943,
      "cluster_max_probability": 0.10675635188817978,
      "cluster_effective_clusters": 9.989148139953613,
      "cluster_min_mass": 0.09256410598754883,
      "cluster_max_mass": 0.10666622221469879,
      "cluster_head_gradient_norm": 0.0
    },
    {
      "epoch": 11,
      "total": 23.048500061035156,
      "reconstruction": 0.16740365326404572,
      "sample_contrastive": 8.153216361999512,
      "cluster_contrastive": 2.9455761909484863,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3017148971557617,
      "cluster_max_probability": 0.10601365566253662,
      "cluster_effective_clusters": 9.991392135620117,
      "cluster_min_mass": 0.09312590956687927,
      "cluster_max_mass": 0.10594485700130463,
      "cluster_head_gradient_norm": 0.06975071629604855
    },
    {
      "epoch": 12,
      "total": 23.03919792175293,
      "reconstruction": 0.1606103926897049,
      "sample_contrastive": 8.15250015258789,
      "cluster_contrastive": 2.9452176094055176,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.302009105682373,
      "cluster_max_probability": 0.10502838343381882,
      "cluster_effective_clusters": 9.994329452514648,
      "cluster_min_mass": 0.09420344978570938,
      "cluster_max_mass": 0.10494714230298996,
      "cluster_head_gradient_norm": 0.056862948187621574
    },
    {
      "epoch": 13,
      "total": 23.029991149902344,
      "reconstruction": 0.154098242521286,
      "sample_contrastive": 8.151577949523926,
      "cluster_contrastive": 2.9448628425598145,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3022964000701904,
      "cluster_max_probability": 0.10367058217525482,
      "cluster_effective_clusters": 9.997201919555664,
      "cluster_min_mass": 0.09560561180114746,
      "cluster_max_mass": 0.1035720705986023,
      "cluster_head_gradient_norm": 0.04020302697681059
    },
    {
      "epoch": 14,
      "total": 23.021312713623047,
      "reconstruction": 0.14786159992218018,
      "sample_contrastive": 8.15036678314209,
      "cluster_contrastive": 2.9446170330047607,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.302490472793579,
      "cluster_max_probability": 0.10209508240222931,
      "cluster_effective_clusters": 9.999144554138184,
      "cluster_min_mass": 0.09713391214609146,
      "cluster_max_mass": 0.10197573155164719,
      "cluster_head_gradient_norm": 0.0227255235673764
    },
    {
      "epoch": 15,
      "total": 23.013246536254883,
      "reconstruction": 0.14189749956130981,
      "sample_contrastive": 8.148771286010742,
      "cluster_contrastive": 2.9445157051086426,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3025574684143066,
      "cluster_max_probability": 0.10115423053503036,
      "cluster_effective_clusters": 9.999823570251465,
      "cluster_min_mass": 0.09869475662708282,
      "cluster_max_mass": 0.10096000880002975,
      "cluster_head_gradient_norm": 0.011561737938061634
    },
    {
      "epoch": 16,
      "total": 23.005531311035156,
      "reconstruction": 0.13620418310165405,
      "sample_contrastive": 8.146649360656738,
      "cluster_contrastive": 2.944535732269287,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.302520275115967,
      "cluster_max_probability": 0.10200807452201843,
      "cluster_effective_clusters": 9.999465942382812,
      "cluster_min_mass": 0.09850218892097473,
      "cluster_max_mass": 0.10189265757799149,
      "cluster_head_gradient_norm": 0.018425784083943495
    },
    {
      "epoch": 17,
      "total": 22.997669219970703,
      "reconstruction": 0.13078394532203674,
      "sample_contrastive": 8.143826484680176,
      "cluster_contrastive": 2.9446117877960205,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3024396896362305,
      "cluster_max_probability": 0.10256122052669525,
      "cluster_effective_clusters": 9.998674392700195,
      "cluster_min_mass": 0.09767495840787888,
      "cluster_max_mass": 0.10234781354665756,
      "cluster_head_gradient_norm": 0.02810626568096835
    },
    {
      "epoch": 18,
      "total": 22.989078521728516,
      "reconstruction": 0.12564203143119812,
      "sample_contrastive": 8.140059471130371,
      "cluster_contrastive": 2.9446754455566406,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3023784160614014,
      "cluster_max_probability": 0.10284355282783508,
      "cluster_effective_clusters": 9.99807357788086,
      "cluster_min_mass": 0.09714347869157791,
      "cluster_max_mass": 0.10256153345108032,
      "cluster_head_gradient_norm": 0.03366915254667148
    },
    {
      "epoch": 19,
      "total": 22.979248046875,
      "reconstruction": 0.12078316509723663,
      "sample_contrastive": 8.135025024414062,
      "cluster_contrastive": 2.944688081741333,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,
      "spatial_enabled": false,
      "spatial_weighting_enabled": false,
      "spatial_negative_filter_enabled": false,
      "cluster_assignment_entropy": 2.3023681640625,
      "cluster_max_probability": 0.1031891256570816,
      "cluster_effective_clusters": 9.997979164123535,
      "cluster_min_mass": 0.09704435616731644,
      "cluster_max_mass": 0.10314752161502838,
      "cluster_head_gradient_norm": 0.03450246041230271
    },
    {
      "epoch": 20,
      "total": 22.967824935913086,
      "reconstruction": 0.11621533334255219,
      "sample_contrastive": 8.128338813781738,
      "cluster_contrastive": 2.9446539878845215,
      "spatial": 0.0,
      "lambda_rec": 1.0,
      "lambda_mgcl": 1.0,
      "lambda_cluster": 5.0,
      "lambda_spatial": 0.0,
      "cluster_enabled": true,

celle：对比 mean_z、concat_z 与 Q_argmax

生成并运行两个微调实验：• diag_fine32_lr2x：cluster_head_lr_multiplier=2.0•

diag_fine32_cl1：lambda_cluster=1.0

In [15]:
%%bash
cd /content/SpaMGCL/SpaMGCL

# 复制 fine32 配置，创建两个变体
python - <<'PY'
import yaml

with open("configs/diagnostic_hlna1_fine32.yaml") as f:
    base = yaml.safe_load(f)

# 实验 A：降低 cluster_head_lr_multiplier 到 2x
cfg_a = yaml.safe_load(yaml.safe_dump(base))
cfg_a["experiment"]["name"] = "diag_fine32_lr2x"
cfg_a["training"]["cluster_head_lr_multiplier"] = 2.0
cfg_a["output"]["dir"] = "results/diag_fine32_lr2x/"
with open("configs/diag_fine32_lr2x.yaml", "w") as f:
    yaml.dump(cfg_a, f, default_flow_style=False)

# 实验 B：降低 lambda_cluster 到 1.0
cfg_b = yaml.safe_load(yaml.safe_dump(base))
cfg_b["experiment"]["name"] = "diag_fine32_cl1"
cfg_b["loss"]["lambda_cluster"] = 1.0
cfg_b["output"]["dir"] = "results/diag_fine32_cl1/"
with open("configs/diag_fine32_cl1.yaml", "w") as f:
    yaml.dump(cfg_b, f, default_flow_style=False)

print("✅ 生成 diag_fine32_lr2x.yaml 和 diag_fine32_cl1.yaml")
PY

echo "=========================================="
echo "🚀 实验 A: fine_dim=32, cluster_head_lr_multiplier=2.0"
echo "=========================================="
python experiments/run_exp.py --config configs/diag_fine32_lr2x.yaml

echo ""
echo "=========================================="
echo "🚀 实验 B: fine_dim=32, lambda_cluster=1.0"
echo "=========================================="
python experiments/run_exp.py --config configs/diag_fine32_cl1.yaml

echo ""
echo "🏁 两个微调实验完成"

✅ 生成 diag_fine32_lr2x.yaml 和 diag_fine32_cl1.yaml
==========================================
🚀 实验 A: fine_dim=32, cluster_head_lr_multiplier=2.0
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.002 (2x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950877 | spatial=0.000000 | SC=off | SNF=off | effC=9.952 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.950612 | spatial=0.000000 | SC=off | SNF=off | effC=9.954 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.950364 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 005/050 | total=8.370091 | rec=0.214360 | mgcl=8.155731 | cluster=2.950131 | spatial=0.000000 | SC=off | SNF=off | effC=9.957 | gradC=0.000e+00
epoch 006/050 | total=8.361096 | rec=0.205753 | mgcl=8.155343 | cluster=2.949914 | spatial=0.000000 | SC=off | SNF=off | effC=9.959 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154991 | cluster=2.949707 | spatial=0.000000 | SC=off | SNF=off | effC=9.961 | gradC=0.000e+00
epoch 008/050 | total=8.344152 | rec=0.189517 | mgcl=8.154635 | cluster=2.949514 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181858 | mgcl=8.154244 | cluster=2.949332 | spatial=0.000000 | SC=off | SNF=off | effC=9.963 | gradC=0.000e+00
epoch 010/050 | total=8.328269 | rec=0.174488 | mgcl=8.153781 | cluster=2.949160 | spatial=0.000000 | SC=off | SNF=off | effC=9.965 | gradC=0.000e+00
epoch 011/050 | total=23.065611 | rec=0.167404 | mgcl=8.153218 | cluster=2.948998 | spatial=0.000000 | SC=off | SNF=off | effC=9.966 | gradC=1.399e-01
epoch 012/050 | total=23.056866 | rec=0.160674 | mgcl=8.152515 | cluster=2.948735 | spatial=0.000000 | SC=off | SNF=off | effC=9.968 | gradC=1.354e-01
epoch 013/050 | total=23.047791 | rec=0.154258 | mgcl=8.151624 | cluster=2.948382 | spatial=0.000000 | SC=off | SNF=off | effC=9.971 | gradC=1.291e-01
epoch 014/050 | total=23.038527 | rec=0.148135 | mgcl=8.150472 | cluster=2.947984 | spatial=0.000000 | SC=off | SNF=off | effC=9.975 | gradC=1.217e-01
epoch 015/050 | total=23.029114 | rec=0.142292 | mgcl=8.148971 | cluster=2.947570 | spatial=0.000000 | SC=off | SNF=off | effC=9.978 | gradC=1.134e-01
epoch 016/050 | total=23.019508 | rec=0.136717 | mgcl=8.146996 | cluster=2.947159 | spatial=0.000000 | SC=off | SNF=off | effC=9.981 | gradC=1.047e-01
epoch 017/050 | total=23.009621 | rec=0.131402 | mgcl=8.144389 | cluster=2.946766 | spatial=0.000000 | SC=off | SNF=off | effC=9.984 | gradC=9.556e-02
epoch 018/050 | total=22.999268 | rec=0.126345 | mgcl=8.140925 | cluster=2.946399 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=8.629e-02
epoch 019/050 | total=22.988182 | rec=0.121547 | mgcl=8.136312 | cluster=2.946065 | spatial=0.000000 | SC=off | SNF=off | effC=9.990 | gradC=7.699e-02
epoch 020/050 | total=22.976027 | rec=0.117014 | mgcl=8.130179 | cluster=2.945767 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=6.777e-02
epoch 021/050 | total=22.962332 | rec=0.112752 | mgcl=8.122050 | cluster=2.945506 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=5.874e-02
epoch 022/050 | total=22.946518 | rec=0.108773 | mgcl=8.111331 | cluster=2.945283 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=5.003e-02
epoch 023/050 | total=22.928017 | rec=0.105087 | mgcl=8.097453 | cluster=2.945095 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=4.177e-02
epoch 024/050 | total=22.906336 | rec=0.101700 | mgcl=8.079931 | cluster=2.944941 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.417e-02
epoch 025/050 | total=22.881084 | rec=0.098613 | mgcl=8.058388 | cluster=2.944817 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.752e-02
epoch 026/050 | total=22.852369 | rec=0.095821 | mgcl=8.032959 | cluster=2.944718 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.212e-02
epoch 027/050 | total=22.821060 | rec=0.093312 | mgcl=8.004551 | cluster=2.944640 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.838e-02
epoch 028/050 | total=22.787670 | rec=0.091064 | mgcl=7.973714 | cluster=2.944579 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.659e-02
epoch 029/050 | total=22.751472 | rec=0.089060 | mgcl=7.939761 | cluster=2.944530 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.664e-02
epoch 030/050 | total=22.711967 | rec=0.087285 | mgcl=7.902232 | cluster=2.944490 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.794e-02
epoch 031/050 | total=22.669477 | rec=0.085722 | mgcl=7.861477 | cluster=2.944456 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.983e-02
epoch 032/050 | total=22.627607 | rec=0.084354 | mgcl=7.821128 | cluster=2.944425 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.189e-02
epoch 033/050 | total=22.589533 | rec=0.083168 | mgcl=7.784389 | cluster=2.944395 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.389e-02
epoch 034/050 | total=22.556179 | rec=0.082131 | mgcl=7.752223 | cluster=2.944365 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.581e-02
epoch 035/050 | total=22.519085 | rec=0.081240 | mgcl=7.716212 | cluster=2.944327 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.703e-02
epoch 036/050 | total=22.478724 | rec=0.080454 | mgcl=7.676847 | cluster=2.944284 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.802e-02
epoch 037/050 | total=22.447216 | rec=0.079764 | mgcl=7.646282 | cluster=2.944234 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.870e-02
epoch 038/050 | total=22.407352 | rec=0.079160 | mgcl=7.607329 | cluster=2.944173 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.879e-02
epoch 039/050 | total=22.374355 | rec=0.078640 | mgcl=7.575204 | cluster=2.944102 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.854e-02
epoch 040/050 | total=22.331825 | rec=0.078170 | mgcl=7.533544 | cluster=2.944022 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.807e-02
epoch 041/050 | total=22.298168 | rec=0.077765 | mgcl=7.500748 | cluster=2.943931 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.747e-02
epoch 042/050 | total=22.256710 | rec=0.077433 | mgcl=7.460133 | cluster=2.943829 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.692e-02
epoch 043/050 | total=22.223848 | rec=0.077149 | mgcl=7.428127 | cluster=2.943715 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.664e-02
epoch 044/050 | total=22.185997 | rec=0.076904 | mgcl=7.391162 | cluster=2.943586 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.669e-02
epoch 045/050 | total=22.155455 | rec=0.076702 | mgcl=7.361542 | cluster=2.943442 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.705e-02
epoch 046/050 | total=22.123497 | rec=0.076532 | mgcl=7.330569 | cluster=2.943279 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.773e-02
epoch 047/050 | total=22.095869 | rec=0.076380 | mgcl=7.304008 | cluster=2.943096 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.874e-02
epoch 048/050 | total=22.068441 | rec=0.076243 | mgcl=7.277740 | cluster=2.942892 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.008e-02
epoch 049/050 | total=22.044243 | rec=0.076122 | mgcl=7.254818 | cluster=2.942661 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.180e-02
epoch 050/050 | total=22.021488 | rec=0.076013 | mgcl=7.233492 | cluster=2.942397 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=3.398e-02
ARI=0.104918 | NMI=0.198193
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml

==========================================
🚀 实验 B: fine_dim=32, lambda_cluster=1.0
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389495 | rec=0.232628 | mgcl=8.156867 | cluster=2.949508 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.948801 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361095 | rec=0.205753 | mgcl=8.155342 | cluster=2.947582 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947062 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154636 | cluster=2.946602 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336101 | rec=0.181858 | mgcl=8.154243 | cluster=2.946202 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328270 | rec=0.174488 | mgcl=8.153782 | cluster=2.945862 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=11.266195 | rec=0.167404 | mgcl=8.153216 | cluster=2.945576 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=1.395e-02
epoch 012/050 | total=11.258321 | rec=0.160601 | mgcl=8.152497 | cluster=2.945222 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=1.141e-02
epoch 013/050 | total=11.250517 | rec=0.154077 | mgcl=8.151570 | cluster=2.944870 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=8.124e-03
epoch 014/050 | total=11.242805 | rec=0.147828 | mgcl=8.150352 | cluster=2.944625 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.679e-03
epoch 015/050 | total=11.235119 | rec=0.141852 | mgcl=8.148746 | cluster=2.944521 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.396e-03
epoch 016/050 | total=11.227293 | rec=0.136148 | mgcl=8.146609 | cluster=2.944536 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.590e-03
epoch 017/050 | total=11.219095 | rec=0.130717 | mgcl=8.143769 | cluster=2.944610 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.501e-03
epoch 018/050 | total=11.210216 | rec=0.125564 | mgcl=8.139977 | cluster=2.944674 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.658e-03
epoch 019/050 | total=11.200295 | rec=0.120696 | mgcl=8.134908 | cluster=2.944692 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.908e-03
epoch 020/050 | total=11.188952 | rec=0.116122 | mgcl=8.128168 | cluster=2.944662 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.412e-03
epoch 021/050 | total=11.175678 | rec=0.111851 | mgcl=8.119220 | cluster=2.944608 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.439e-03
epoch 022/050 | total=11.159859 | rec=0.107892 | mgcl=8.107414 | cluster=2.944552 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.285e-03
epoch 023/050 | total=11.140894 | rec=0.104253 | mgcl=8.092133 | cluster=2.944509 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.267e-03
epoch 024/050 | total=11.118393 | rec=0.100935 | mgcl=8.072979 | cluster=2.944479 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.703e-03
epoch 025/050 | total=11.092246 | rec=0.097933 | mgcl=8.049857 | cluster=2.944455 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.677e-03
epoch 026/050 | total=11.062864 | rec=0.095235 | mgcl=8.023200 | cluster=2.944430 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.908e-03
epoch 027/050 | total=11.031386 | rec=0.092823 | mgcl=7.994170 | cluster=2.944393 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.094e-03
epoch 028/050 | total=10.997509 | rec=0.090675 | mgcl=7.962494 | cluster=2.944340 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.119e-03
epoch 029/050 | total=10.959964 | rec=0.088768 | mgcl=7.926931 | cluster=2.944264 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.030e-03
epoch 030/050 | total=10.918655 | rec=0.087091 | mgcl=7.887400 | cluster=2.944164 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.920e-03
epoch 031/050 | total=10.875299 | rec=0.085618 | mgcl=7.845646 | cluster=2.944034 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.876e-03
epoch 032/050 | total=10.833537 | rec=0.084342 | mgcl=7.805331 | cluster=2.943865 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.970e-03
epoch 033/050 | total=10.795157 | rec=0.083231 | mgcl=7.768282 | cluster=2.943645 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.239e-03
epoch 034/050 | total=10.762667 | rec=0.082268 | mgcl=7.737037 | cluster=2.943361 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.679e-03
epoch 035/050 | total=10.722764 | rec=0.081413 | mgcl=7.698357 | cluster=2.942994 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.251e-03
epoch 036/050 | total=10.684074 | rec=0.080674 | mgcl=7.660873 | cluster=2.942527 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.920e-03
epoch 037/050 | total=10.650084 | rec=0.080008 | mgcl=7.628139 | cluster=2.941936 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.693e-03
epoch 038/050 | total=10.607716 | rec=0.079432 | mgcl=7.587095 | cluster=2.941188 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.538e-03
epoch 039/050 | total=10.572957 | rec=0.078930 | mgcl=7.553774 | cluster=2.940253 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.459e-03
epoch 040/050 | total=10.530055 | rec=0.078484 | mgcl=7.512453 | cluster=2.939118 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=8.475e-03
epoch 041/050 | total=10.492735 | rec=0.078102 | mgcl=7.476886 | cluster=2.937747 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=9.601e-03
epoch 042/050 | total=10.453512 | rec=0.077788 | mgcl=7.439652 | cluster=2.936071 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.085e-02
epoch 043/050 | total=10.419001 | rec=0.077532 | mgcl=7.407420 | cluster=2.934048 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.222e-02
epoch 044/050 | total=10.381216 | rec=0.077323 | mgcl=7.372225 | cluster=2.931669 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.369e-02
epoch 045/050 | total=10.349729 | rec=0.077150 | mgcl=7.343699 | cluster=2.928880 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.525e-02
epoch 046/050 | total=10.317085 | rec=0.077014 | mgcl=7.314480 | cluster=2.925590 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.694e-02
epoch 047/050 | total=10.287254 | rec=0.076910 | mgcl=7.288595 | cluster=2.921751 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.875e-02
epoch 048/050 | total=10.258441 | rec=0.076819 | mgcl=7.264288 | cluster=2.917333 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.068e-02
epoch 049/050 | total=10.231159 | rec=0.076744 | mgcl=7.242186 | cluster=2.912230 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.272e-02
epoch 050/050 | total=10.205656 | rec=0.076684 | mgcl=7.222677 | cluster=2.906296 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.491e-02
ARI=0.280820 | NMI=0.351580
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml

🏁 两个微调实验完成

/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(

cellf：读取 fine_dim 表示层指标表。

目的：读取四个 fine_dim 的 metrics.json，从 representation_metrics 和 candidate_metrics 里提取：

In [16]:
import os
import json
import pandas as pd

fine_dims = [16, 32, 64, 128]
rows = []

for d in fine_dims:
    path = f"results/diagnostic_hlna1_fine{d}/metrics.json"

    with open(path, "r") as f:
        m = json.load(f)

    rep = m["representation_metrics"]
    cand = m["candidate_metrics"]

    rows.append({
        "fine_dim": d,

        "RNA_spatial_Z_ARI": rep["z_views"]["rna_spatial"]["ARI"],
        "RNA_feature_Z_ARI": rep["z_views"]["rna_feature"]["ARI"],
        "ADT_spatial_Z_ARI": rep["z_views"]["adt_spatial"]["ARI"],
        "ADT_feature_Z_ARI": rep["z_views"]["adt_feature"]["ARI"],

        "Z_mean_ARI": rep["mean_z"]["ARI"],
        "Z_concat_ARI": rep["concat_z"]["ARI"],

        "Q_argmax_ARI": cand["cluster_argmax"]["ARI"],
        "Q_argmax_NMI": cand["cluster_argmax"]["NMI"],
    })

df = pd.DataFrame(rows)
display(df)

,fine_dim,RNA_spatial_Z_ARI,RNA_feature_Z_ARI,ADT_spatial_Z_ARI,ADT_feature_Z_ARI,Z_mean_ARI,Z_concat_ARI,Q_argmax_ARI,Q_argmax_NMI
0,16,0.142404,0.122812,0.147725,0.121369,0.173640,0.154628,0.136410,0.193117
1,32,0.262079,0.233164,0.189612,0.159578,0.238379,0.271365,0.280820,0.351580
2,64,0.207654,0.178527,0.212820,0.182648,0.212208,0.238012,0.225507,0.303100
3,128,0.263503,0.203931,0.247616,0.205633,0.276440,0.279341,0.203812,0.306323

cellg：meanZ / concatZ / Q 对比表

In [17]:
rows = []

for d in [16, 32, 64, 128]:
    with open(f"results/diagnostic_hlna1_fine{d}/metrics.json") as f:
        m = json.load(f)

    rep = m["representation_metrics"]
    q = m["candidate_metrics"]["cluster_argmax"]

    rows.append({
        "fine_dim": d,
        "meanZ_ARI": rep["mean_z"]["ARI"],
        "meanZ_NMI": rep["mean_z"]["NMI"],
        "concatZ_ARI": rep["concat_z"]["ARI"],
        "concatZ_NMI": rep["concat_z"]["NMI"],
        "Q_ARI": q["ARI"],
        "Q_NMI": q["NMI"],
    })

pd.DataFrame(rows)

,fine_dim,meanZ_ARI,meanZ_NMI,concatZ_ARI,concatZ_NMI,Q_ARI,Q_NMI
0,16,0.173640,0.242702,0.154628,0.225108,0.136410,0.193117
1,32,0.238379,0.334134,0.271365,0.360825,0.280820,0.351580
2,64,0.212208,0.300818,0.238012,0.334844,0.225507,0.303100
3,128,0.276440,0.362924,0.279341,0.372164,0.203812,0.306323

cellh：lambda_cluster 变体批量实验（cl05 / cl01 / cl2 / fine64_cl1）

作用：生成并运行四个变体：• diag_fine32_cl05：fine32，λ=0.5

• diag_fine32_cl01：fine32，λ=0.1

• diag_fine32_cl20：fine32，λ=2.0（配置文件名是 cl20）

• diag_fine64_cl1：fine64，λ=1.0

In [18]:
%%bash
cd /content/SpaMGCL/SpaMGCL

python - <<'PY'
import yaml

# 读 fine32 基准配置
with open("configs/diagnostic_hlna1_fine32.yaml") as f:
    base32 = yaml.safe_load(f)

# 读 fine64 基准配置
with open("configs/diagnostic_hlna1_fine64.yaml") as f:
    base64 = yaml.safe_load(f)

# 三个 lambda 变体（fine32）
for lam in [0.5, 0.1, 2.0]:
    cfg = yaml.safe_load(yaml.safe_dump(base32))
    cfg["experiment"]["name"] = f"diag_fine32_cl{str(lam).replace('.','')}"
    cfg["loss"]["lambda_cluster"] = lam
    cfg["output"]["dir"] = f"results/diag_fine32_cl{str(lam).replace('.','')}/"
    fname = f"configs/diag_fine32_cl{str(lam).replace('.','')}.yaml"
    with open(fname, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)
    print(f"✅ 生成 {fname}")

# fine64 + lambda_cluster=1
cfg = yaml.safe_load(yaml.safe_dump(base64))
cfg["experiment"]["name"] = "diag_fine64_cl1"
cfg["loss"]["lambda_cluster"] = 1.0
cfg["output"]["dir"] = "results/diag_fine64_cl1/"
with open("configs/diag_fine64_cl1.yaml", "w") as f:
    yaml.dump(cfg, f, default_flow_style=False)
print("✅ 生成 configs/diag_fine64_cl1.yaml")
PY

echo ""
echo "=========================================="
echo "🚀 实验 C: fine32, λ_cluster=0.5"
echo "=========================================="
python experiments/run_exp.py --config configs/diag_fine32_cl05.yaml

echo ""
echo "=========================================="
echo "🚀 实验 D: fine32, λ_cluster=0.1"
echo "=========================================="
python experiments/run_exp.py --config configs/diag_fine32_cl01.yaml

echo ""
echo "=========================================="
echo "🚀 实验 E: fine32, λ_cluster=2.0"
echo "=========================================="
python experiments/run_exp.py --config configs/diag_fine32_cl2.yaml

echo ""
echo "=========================================="
echo "🚀 实验 F: fine64, λ_cluster=1.0"
echo "=========================================="
python experiments/run_exp.py --config configs/diag_fine64_cl1.yaml

echo ""
echo "🏁 全部 4 个实验完成"
import json
import pandas as pd

rows = []
for name in ["diag_fine32_cl05", "diag_fine32_cl01", "diag_fine32_cl2", "diag_fine64_cl1"]:
    path = f"/content/SpaMGCL/SpaMGCL/results/{name}/metrics.json"
    try:
        with open(path) as f:
            data = json.load(f)
        rows.append({
            "实验": name,
            "λ_cluster": data["loss_history"][-1]["lambda_cluster"],
            "ARI": round(data["ARI"], 4),
            "NMI": round(data["NMI"], 4),
        })
    except FileNotFoundError:
        rows.append({"实验": name, "状态": "❌ 未找到"})

df = pd.DataFrame(rows)
print(df.to_string(index=False))

✅ 生成 configs/diag_fine32_cl05.yaml
✅ 生成 configs/diag_fine32_cl01.yaml
✅ 生成 configs/diag_fine32_cl20.yaml
✅ 生成 configs/diag_fine64_cl1.yaml

==========================================
🚀 实验 C: fine32, λ_cluster=0.5
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.949508 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379530 | rec=0.223314 | mgcl=8.156216 | cluster=2.948801 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361095 | rec=0.205753 | mgcl=8.155342 | cluster=2.947582 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154991 | cluster=2.947062 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154636 | cluster=2.946602 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181858 | mgcl=8.154244 | cluster=2.946202 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328270 | rec=0.174488 | mgcl=8.153782 | cluster=2.945862 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=9.793407 | rec=0.167404 | mgcl=8.153216 | cluster=2.945576 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=6.975e-03
epoch 012/050 | total=9.785710 | rec=0.160601 | mgcl=8.152498 | cluster=2.945222 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=5.708e-03
epoch 013/050 | total=9.778083 | rec=0.154075 | mgcl=8.151571 | cluster=2.944872 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=4.072e-03
epoch 014/050 | total=9.770492 | rec=0.147825 | mgcl=8.150353 | cluster=2.944626 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.355e-03
epoch 015/050 | total=9.762856 | rec=0.141849 | mgcl=8.148746 | cluster=2.944522 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.205e-03
epoch 016/050 | total=9.755020 | rec=0.136143 | mgcl=8.146608 | cluster=2.944536 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.782e-03
epoch 017/050 | total=9.746785 | rec=0.130711 | mgcl=8.143769 | cluster=2.944609 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.736e-03
epoch 018/050 | total=9.737872 | rec=0.125558 | mgcl=8.139977 | cluster=2.944674 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.320e-03
epoch 019/050 | total=9.727944 | rec=0.120689 | mgcl=8.134909 | cluster=2.944692 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.452e-03
epoch 020/050 | total=9.716615 | rec=0.116114 | mgcl=8.128169 | cluster=2.944663 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=3.212e-03
epoch 021/050 | total=9.703365 | rec=0.111842 | mgcl=8.119219 | cluster=2.944610 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.733e-03
epoch 022/050 | total=9.687572 | rec=0.107884 | mgcl=8.107411 | cluster=2.944555 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=2.159e-03
epoch 023/050 | total=9.668629 | rec=0.104245 | mgcl=8.092129 | cluster=2.944511 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.648e-03
epoch 024/050 | total=9.646143 | rec=0.100927 | mgcl=8.072976 | cluster=2.944481 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.359e-03
epoch 025/050 | total=9.620015 | rec=0.097925 | mgcl=8.049861 | cluster=2.944458 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.339e-03
epoch 026/050 | total=9.590644 | rec=0.095228 | mgcl=8.023199 | cluster=2.944433 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.452e-03
epoch 027/050 | total=9.559189 | rec=0.092816 | mgcl=7.994174 | cluster=2.944398 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.547e-03
epoch 028/050 | total=9.525340 | rec=0.090668 | mgcl=7.962498 | cluster=2.944347 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.562e-03
epoch 029/050 | total=9.487886 | rec=0.088761 | mgcl=7.926987 | cluster=2.944275 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.519e-03
epoch 030/050 | total=9.446675 | rec=0.087084 | mgcl=7.887503 | cluster=2.944178 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.463e-03
epoch 031/050 | total=9.403359 | rec=0.085611 | mgcl=7.845722 | cluster=2.944052 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.435e-03
epoch 032/050 | total=9.361560 | rec=0.084333 | mgcl=7.805283 | cluster=2.943889 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.474e-03
epoch 033/050 | total=9.322763 | rec=0.083221 | mgcl=7.767704 | cluster=2.943677 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.600e-03
epoch 034/050 | total=9.289141 | rec=0.082255 | mgcl=7.735184 | cluster=2.943404 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.813e-03
epoch 035/050 | total=9.253730 | rec=0.081400 | mgcl=7.700806 | cluster=2.943049 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.091e-03
epoch 036/050 | total=9.211617 | rec=0.080655 | mgcl=7.659662 | cluster=2.942601 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.414e-03
epoch 037/050 | total=9.181747 | rec=0.079982 | mgcl=7.630749 | cluster=2.942034 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.791e-03
epoch 038/050 | total=9.138100 | rec=0.079404 | mgcl=7.588037 | cluster=2.941317 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.198e-03
epoch 039/050 | total=9.104619 | rec=0.078898 | mgcl=7.555510 | cluster=2.940423 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.639e-03
epoch 040/050 | total=9.062122 | rec=0.078447 | mgcl=7.514004 | cluster=2.939343 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.125e-03
epoch 041/050 | total=9.026352 | rec=0.078059 | mgcl=7.479271 | cluster=2.938045 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.661e-03
epoch 042/050 | total=8.987672 | rec=0.077738 | mgcl=7.441699 | cluster=2.936471 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.247e-03
epoch 043/050 | total=8.954283 | rec=0.077476 | mgcl=7.409512 | cluster=2.934592 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.882e-03
epoch 044/050 | total=8.918489 | rec=0.077254 | mgcl=7.375028 | cluster=2.932415 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.549e-03
epoch 045/050 | total=8.887859 | rec=0.077065 | mgcl=7.345839 | cluster=2.929911 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.245e-03
epoch 046/050 | total=8.858032 | rec=0.076911 | mgcl=7.317617 | cluster=2.927008 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.977e-03
epoch 047/050 | total=8.829338 | rec=0.076784 | mgcl=7.290717 | cluster=2.923674 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=8.750e-03
epoch 048/050 | total=8.804057 | rec=0.076667 | mgcl=7.267425 | cluster=2.919930 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=9.549e-03
epoch 049/050 | total=8.778487 | rec=0.076557 | mgcl=7.244063 | cluster=2.915735 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.037e-02
epoch 050/050 | total=8.757124 | rec=0.076454 | mgcl=7.225180 | cluster=2.910980 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.122e-02
ARI=0.283967 | NMI=0.352305
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml

==========================================
🚀 实验 D: fine32, λ_cluster=0.1
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.949508 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379529 | rec=0.223314 | mgcl=8.156215 | cluster=2.948801 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361095 | rec=0.205753 | mgcl=8.155342 | cluster=2.947582 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947062 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154637 | cluster=2.946602 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181858 | mgcl=8.154244 | cluster=2.946202 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328270 | rec=0.174488 | mgcl=8.153782 | cluster=2.945862 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.615178 | rec=0.167404 | mgcl=8.153217 | cluster=2.945576 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=1.395e-03
epoch 012/050 | total=8.607621 | rec=0.160600 | mgcl=8.152498 | cluster=2.945223 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=1.146e-03
epoch 013/050 | total=8.600132 | rec=0.154075 | mgcl=8.151570 | cluster=2.944873 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=8.227e-04
epoch 014/050 | total=8.592641 | rec=0.147824 | mgcl=8.150353 | cluster=2.944627 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.808e-04
epoch 015/050 | total=8.585045 | rec=0.141847 | mgcl=8.148746 | cluster=2.944520 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.415e-04
epoch 016/050 | total=8.577203 | rec=0.136141 | mgcl=8.146608 | cluster=2.944533 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.458e-04
epoch 017/050 | total=8.568939 | rec=0.130708 | mgcl=8.143771 | cluster=2.944606 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.381e-04
epoch 018/050 | total=8.560002 | rec=0.125554 | mgcl=8.139981 | cluster=2.944673 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.582e-04
epoch 019/050 | total=8.550066 | rec=0.120684 | mgcl=8.134913 | cluster=2.944693 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.884e-04
epoch 020/050 | total=8.538750 | rec=0.116108 | mgcl=8.128175 | cluster=2.944668 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.431e-04
epoch 021/050 | total=8.525523 | rec=0.111836 | mgcl=8.119226 | cluster=2.944616 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.485e-04
epoch 022/050 | total=8.509753 | rec=0.107877 | mgcl=8.107419 | cluster=2.944563 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=4.337e-04
epoch 023/050 | total=8.490825 | rec=0.104239 | mgcl=8.092134 | cluster=2.944521 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.303e-04
epoch 024/050 | total=8.468353 | rec=0.100921 | mgcl=8.072984 | cluster=2.944493 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.703e-04
epoch 025/050 | total=8.442244 | rec=0.097920 | mgcl=8.049876 | cluster=2.944474 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.652e-04
epoch 026/050 | total=8.412888 | rec=0.095223 | mgcl=8.023219 | cluster=2.944457 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.880e-04
epoch 027/050 | total=8.381457 | rec=0.092811 | mgcl=7.994203 | cluster=2.944432 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.077e-04
epoch 028/050 | total=8.347642 | rec=0.090663 | mgcl=7.962540 | cluster=2.944395 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.104e-04
epoch 029/050 | total=8.310245 | rec=0.088756 | mgcl=7.927055 | cluster=2.944341 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.994e-04
epoch 030/050 | total=8.269105 | rec=0.087077 | mgcl=7.887600 | cluster=2.944270 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.832e-04
epoch 031/050 | total=8.225850 | rec=0.085603 | mgcl=7.845829 | cluster=2.944177 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.701e-04
epoch 032/050 | total=8.184127 | rec=0.084324 | mgcl=7.805398 | cluster=2.944055 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.688e-04
epoch 033/050 | total=8.145341 | rec=0.083211 | mgcl=7.767741 | cluster=2.943896 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.837e-04
epoch 034/050 | total=8.111391 | rec=0.082242 | mgcl=7.734780 | cluster=2.943689 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.167e-04
epoch 035/050 | total=8.077345 | rec=0.081385 | mgcl=7.701618 | cluster=2.943416 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.630e-04
epoch 036/050 | total=8.034576 | rec=0.080637 | mgcl=7.659633 | cluster=2.943067 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.195e-04
epoch 037/050 | total=8.005980 | rec=0.079960 | mgcl=7.631758 | cluster=2.942616 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=4.867e-04
epoch 038/050 | total=7.962078 | rec=0.079380 | mgcl=7.588494 | cluster=2.942040 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.594e-04
epoch 039/050 | total=7.929442 | rec=0.078871 | mgcl=7.556440 | cluster=2.941311 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.392e-04
epoch 040/050 | total=7.887088 | rec=0.078415 | mgcl=7.514632 | cluster=2.940420 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.282e-04
epoch 041/050 | total=7.852200 | rec=0.078020 | mgcl=7.480246 | cluster=2.939339 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=8.270e-04
epoch 042/050 | total=7.813977 | rec=0.077694 | mgcl=7.442481 | cluster=2.938022 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=9.352e-04
epoch 043/050 | total=7.781378 | rec=0.077424 | mgcl=7.410311 | cluster=2.936441 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.052e-03
epoch 044/050 | total=7.746749 | rec=0.077192 | mgcl=7.376096 | cluster=2.934607 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.176e-03
epoch 045/050 | total=7.716900 | rec=0.076991 | mgcl=7.346658 | cluster=2.932502 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.304e-03
epoch 046/050 | total=7.688764 | rec=0.076823 | mgcl=7.318933 | cluster=2.930075 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.437e-03
epoch 047/050 | total=7.660846 | rec=0.076679 | mgcl=7.291435 | cluster=2.927311 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=1.574e-03
epoch 048/050 | total=7.637567 | rec=0.076543 | mgcl=7.268599 | cluster=2.924246 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.713e-03
epoch 049/050 | total=7.613255 | rec=0.076409 | mgcl=7.244759 | cluster=2.920876 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.853e-03
epoch 050/050 | total=7.594110 | rec=0.076276 | mgcl=7.226120 | cluster=2.917136 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=1.995e-03
ARI=0.289443 | NMI=0.353859
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml

==========================================
🚀 实验 E: fine32, λ_cluster=2.0
==========================================

==========================================
🚀 实验 F: fine64, λ_cluster=1.0
==========================================
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.373463 | rec=0.215289 | mgcl=8.158174 | cluster=2.950635 | spatial=0.000000 | SC=off | SNF=off | effC=9.947 | gradC=0.000e+00
epoch 002/050 | total=8.361030 | rec=0.205297 | mgcl=8.155733 | cluster=2.949619 | spatial=0.000000 | SC=off | SNF=off | effC=9.955 | gradC=0.000e+00
epoch 003/050 | total=8.349434 | rec=0.195784 | mgcl=8.153650 | cluster=2.948720 | spatial=0.000000 | SC=off | SNF=off | effC=9.963 | gradC=0.000e+00
epoch 004/050 | total=8.337865 | rec=0.186686 | mgcl=8.151179 | cluster=2.947946 | spatial=0.000000 | SC=off | SNF=off | effC=9.970 | gradC=0.000e+00
epoch 005/050 | total=8.325717 | rec=0.177960 | mgcl=8.147758 | cluster=2.947276 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 006/050 | total=8.312439 | rec=0.169594 | mgcl=8.142845 | cluster=2.946693 | spatial=0.000000 | SC=off | SNF=off | effC=9.981 | gradC=0.000e+00
epoch 007/050 | total=8.297442 | rec=0.161598 | mgcl=8.135844 | cluster=2.946190 | spatial=0.000000 | SC=off | SNF=off | effC=9.985 | gradC=0.000e+00
epoch 008/050 | total=8.279897 | rec=0.154005 | mgcl=8.125892 | cluster=2.945763 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 009/050 | total=8.258702 | rec=0.146858 | mgcl=8.111844 | cluster=2.945407 | spatial=0.000000 | SC=off | SNF=off | effC=9.992 | gradC=0.000e+00
epoch 010/050 | total=8.232811 | rec=0.140195 | mgcl=8.092616 | cluster=2.945122 | spatial=0.000000 | SC=off | SNF=off | effC=9.994 | gradC=0.000e+00
epoch 011/050 | total=11.146769 | rec=0.134049 | mgcl=8.067818 | cluster=2.944901 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=9.496e-03
epoch 012/050 | total=11.109966 | rec=0.128454 | mgcl=8.036888 | cluster=2.944624 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.190e-03
epoch 013/050 | total=11.068757 | rec=0.123428 | mgcl=8.000855 | cluster=2.944473 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=2.931e-03
epoch 014/050 | total=11.028794 | rec=0.118958 | mgcl=7.965359 | cluster=2.944477 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=3.377e-03
epoch 015/050 | total=10.990789 | rec=0.115032 | mgcl=7.931231 | cluster=2.944527 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.517e-03
epoch 016/050 | total=10.952806 | rec=0.111633 | mgcl=7.896660 | cluster=2.944513 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.646e-03
epoch 017/050 | total=10.913119 | rec=0.108710 | mgcl=7.860020 | cluster=2.944389 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=6.636e-03
epoch 018/050 | total=10.875248 | rec=0.106183 | mgcl=7.824908 | cluster=2.944157 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.918e-03
epoch 019/050 | total=10.838829 | rec=0.103983 | mgcl=7.791028 | cluster=2.943817 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=5.157e-03
epoch 020/050 | total=10.802542 | rec=0.102056 | mgcl=7.757139 | cluster=2.943347 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=5.193e-03
epoch 021/050 | total=10.764957 | rec=0.100349 | mgcl=7.721916 | cluster=2.942692 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=6.164e-03
epoch 022/050 | total=10.728968 | rec=0.098832 | mgcl=7.688341 | cluster=2.941794 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=7.674e-03

/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
Traceback (most recent call last):
  File "/content/SpaMGCL/SpaMGCL/experiments/run_exp.py", line 696, in <module>
    raise SystemExit(main())
                     ~~~~^^
  File "/content/SpaMGCL/SpaMGCL/experiments/run_exp.py", line 690, in main
    config_path = _resolve_config_path(args.config)
  File "/content/SpaMGCL/SpaMGCL/experiments/run_exp.py", line 54, in _resolve_config_path
    raise FileNotFoundError(f"Config file not found; searched: {searched}")
FileNotFoundError: Config file not found; searched: /content/SpaMGCL/SpaMGCL/configs/diag_fine32_cl2.yaml, /content/SpaMGCL/SpaMGCL/configs/diag_fine32_cl2.yaml
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(
bash: line 61: import: command not found
bash: line 62: import: command not found
bash: line 64: rows: command not found
bash: line 66: syntax error near unexpected token `path'
bash: line 66: `    path = f"/content/SpaMGCL/SpaMGCL/results/{name}/metrics.json"'

CalledProcessError: Command 'b'cd /content/SpaMGCL/SpaMGCL\n\npython - <<\'PY\'\nimport yaml\n\n# \xe8\xaf\xbb fine32 \xe5\x9f\xba\xe5\x87\x86\xe9\x85\x8d\xe7\xbd\xae\nwith open("configs/diagnostic_hlna1_fine32.yaml") as f:\n    base32 = yaml.safe_load(f)\n\n# \xe8\xaf\xbb fine64 \xe5\x9f\xba\xe5\x87\x86\xe9\x85\x8d\xe7\xbd\xae\nwith open("configs/diagnostic_hlna1_fine64.yaml") as f:\n    base64 = yaml.safe_load(f)\n\n# \xe4\xb8\x89\xe4\xb8\xaa lambda \xe5\x8f\x98\xe4\xbd\x93\xef\xbc\x88fine32\xef\xbc\x89\nfor lam in [0.5, 0.1, 2.0]:\n    cfg = yaml.safe_load(yaml.safe_dump(base32))\n    cfg["experiment"]["name"] = f"diag_fine32_cl{str(lam).replace(\'.\',\'\')}"\n    cfg["loss"]["lambda_cluster"] = lam\n    cfg["output"]["dir"] = f"results/diag_fine32_cl{str(lam).replace(\'.\',\'\')}/"\n    fname = f"configs/diag_fine32_cl{str(lam).replace(\'.\',\'\')}.yaml"\n    with open(fname, "w") as f:\n        yaml.dump(cfg, f, default_flow_style=False)\n    print(f"\xe2\x9c\x85 \xe7\x94\x9f\xe6\x88\x90 {fname}")\n\n# fine64 + lambda_cluster=1\ncfg = yaml.safe_load(yaml.safe_dump(base64))\ncfg["experiment"]["name"] = "diag_fine64_cl1"\ncfg["loss"]["lambda_cluster"] = 1.0\ncfg["output"]["dir"] = "results/diag_fine64_cl1/"\nwith open("configs/diag_fine64_cl1.yaml", "w") as f:\n    yaml.dump(cfg, f, default_flow_style=False)\nprint("\xe2\x9c\x85 \xe7\x94\x9f\xe6\x88\x90 configs/diag_fine64_cl1.yaml")\nPY\n\necho ""\necho "=========================================="\necho "\xf0\x9f\x9a\x80 \xe5\xae\x9e\xe9\xaa\x8c C: fine32, \xce\xbb_cluster=0.5"\necho "=========================================="\npython experiments/run_exp.py --config configs/diag_fine32_cl05.yaml\n\necho ""\necho "=========================================="\necho "\xf0\x9f\x9a\x80 \xe5\xae\x9e\xe9\xaa\x8c D: fine32, \xce\xbb_cluster=0.1"\necho "=========================================="\npython experiments/run_exp.py --config configs/diag_fine32_cl01.yaml\n\necho ""\necho "=========================================="\necho "\xf0\x9f\x9a\x80 \xe5\xae\x9e\xe9\xaa\x8c E: fine32, \xce\xbb_cluster=2.0"\necho "=========================================="\npython experiments/run_exp.py --config configs/diag_fine32_cl2.yaml\n\necho ""\necho "=========================================="\necho "\xf0\x9f\x9a\x80 \xe5\xae\x9e\xe9\xaa\x8c F: fine64, \xce\xbb_cluster=1.0"\necho "=========================================="\npython experiments/run_exp.py --config configs/diag_fine64_cl1.yaml\n\necho ""\necho "\xf0\x9f\x8f\x81 \xe5\x85\xa8\xe9\x83\xa8 4 \xe4\xb8\xaa\xe5\xae\x9e\xe9\xaa\x8c\xe5\xae\x8c\xe6\x88\x90"\nimport json\nimport pandas as pd\n\nrows = []\nfor name in ["diag_fine32_cl05", "diag_fine32_cl01", "diag_fine32_cl2", "diag_fine64_cl1"]:\n    path = f"/content/SpaMGCL/SpaMGCL/results/{name}/metrics.json"\n    try:\n        with open(path) as f:\n            data = json.load(f)\n        rows.append({\n            "\xe5\xae\x9e\xe9\xaa\x8c": name,\n            "\xce\xbb_cluster": data["loss_history"][-1]["lambda_cluster"],\n            "ARI": round(data["ARI"], 4),\n            "NMI": round(data["NMI"], 4),\n        })\n    except FileNotFoundError:\n        rows.append({"\xe5\xae\x9e\xe9\xaa\x8c": name, "\xe7\x8a\xb6\xe6\x80\x81": "\xe2\x9d\x8c \xe6\x9c\xaa\xe6\x89\xbe\xe5\x88\xb0"})\n\ndf = pd.DataFrame(rows)\nprint(df.to_string(index=False))\n'' returned non-zero exit status 2.

| 设置                        |        ARI |        NMI |
| ------------------------- | ---------: | ---------: |
| fine32, λ_cluster=5（之前）   |     0.2808 |     0.3516 |
| fine32, λ_cluster=0.5     |     0.2840 |     0.3523 |
| **fine32, λ_cluster=0.1** | **0.2894** | **0.3539** |
| fine64, λ_cluster=1       |     0.2123 |     0.3064 |

cell I：lambda_cluster 结果表格

In [19]:
%%bash
cd /content/SpaMGCL/SpaMGCL
python - <<'PY'
import yaml
with open("configs/diagnostic_hlna1_fine32.yaml") as f:
    base = yaml.safe_load(f)
cfg = yaml.safe_load(yaml.safe_dump(base))
cfg["experiment"]["name"] = "diag_fine32_cl0"
cfg["loss"]["lambda_cluster"] = 0.0
cfg["output"]["dir"] = "results/diag_fine32_cl0/"
with open("configs/diag_fine32_cl0.yaml", "w") as f:
    yaml.dump(cfg, f, default_flow_style=False)
print("✅ 生成 diag_fine32_cl0.yaml")
PY

python experiments/run_exp.py --config configs/diag_fine32_cl0.yaml

✅ 生成 diag_fine32_cl0.yaml
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411676 | rec=0.252383 | mgcl=8.159293 | cluster=2.951158 | spatial=0.000000 | SC=off | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=off | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389496 | rec=0.232628 | mgcl=8.156868 | cluster=2.949508 | spatial=0.000000 | SC=off | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379531 | rec=0.223314 | mgcl=8.156217 | cluster=2.948801 | spatial=0.000000 | SC=off | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370092 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=off | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361096 | rec=0.205753 | mgcl=8.155343 | cluster=2.947582 | spatial=0.000000 | SC=off | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197478 | mgcl=8.154990 | cluster=2.947062 | spatial=0.000000 | SC=off | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344154 | rec=0.189517 | mgcl=8.154636 | cluster=2.946602 | spatial=0.000000 | SC=off | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181858 | mgcl=8.154244 | cluster=2.946202 | spatial=0.000000 | SC=off | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328270 | rec=0.174488 | mgcl=8.153782 | cluster=2.945862 | spatial=0.000000 | SC=off | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=8.320620 | rec=0.167404 | mgcl=8.153216 | cluster=2.945576 | spatial=0.000000 | SC=off | SNF=off | effC=9.991 | gradC=0.000e+00
epoch 012/050 | total=8.313100 | rec=0.160600 | mgcl=8.152499 | cluster=2.945339 | spatial=0.000000 | SC=off | SNF=off | effC=9.993 | gradC=0.000e+00
epoch 013/050 | total=8.305646 | rec=0.154074 | mgcl=8.151571 | cluster=2.945144 | spatial=0.000000 | SC=off | SNF=off | effC=9.995 | gradC=0.000e+00
epoch 014/050 | total=8.298176 | rec=0.147824 | mgcl=8.150352 | cluster=2.944986 | spatial=0.000000 | SC=off | SNF=off | effC=9.996 | gradC=0.000e+00
epoch 015/050 | total=8.290592 | rec=0.141846 | mgcl=8.148746 | cluster=2.944858 | spatial=0.000000 | SC=off | SNF=off | effC=9.997 | gradC=0.000e+00
epoch 016/050 | total=8.282749 | rec=0.136140 | mgcl=8.146609 | cluster=2.944756 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=0.000e+00
epoch 017/050 | total=8.274480 | rec=0.130707 | mgcl=8.143772 | cluster=2.944675 | spatial=0.000000 | SC=off | SNF=off | effC=9.998 | gradC=0.000e+00
epoch 018/050 | total=8.265536 | rec=0.125553 | mgcl=8.139983 | cluster=2.944615 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 019/050 | total=8.255598 | rec=0.120683 | mgcl=8.134915 | cluster=2.944571 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 020/050 | total=8.244284 | rec=0.116107 | mgcl=8.128177 | cluster=2.944540 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 021/050 | total=8.231063 | rec=0.111835 | mgcl=8.119228 | cluster=2.944522 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 022/050 | total=8.215297 | rec=0.107876 | mgcl=8.107421 | cluster=2.944512 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 023/050 | total=8.196373 | rec=0.104237 | mgcl=8.092136 | cluster=2.944510 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 024/050 | total=8.173901 | rec=0.100919 | mgcl=8.072982 | cluster=2.944512 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 025/050 | total=8.147788 | rec=0.097918 | mgcl=8.049870 | cluster=2.944518 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 026/050 | total=8.118428 | rec=0.095221 | mgcl=8.023208 | cluster=2.944526 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 027/050 | total=8.086985 | rec=0.092810 | mgcl=7.994175 | cluster=2.944536 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 028/050 | total=8.053157 | rec=0.090661 | mgcl=7.962496 | cluster=2.944545 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 029/050 | total=8.015764 | rec=0.088754 | mgcl=7.927010 | cluster=2.944554 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 030/050 | total=7.974633 | rec=0.087076 | mgcl=7.887557 | cluster=2.944561 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 031/050 | total=7.931388 | rec=0.085602 | mgcl=7.845786 | cluster=2.944566 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 032/050 | total=7.889660 | rec=0.084323 | mgcl=7.805337 | cluster=2.944566 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 033/050 | total=7.850812 | rec=0.083211 | mgcl=7.767601 | cluster=2.944566 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 034/050 | total=7.816310 | rec=0.082241 | mgcl=7.734069 | cluster=2.944562 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 035/050 | total=7.783545 | rec=0.081385 | mgcl=7.702159 | cluster=2.944556 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 036/050 | total=7.739905 | rec=0.080634 | mgcl=7.659271 | cluster=2.944549 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 037/050 | total=7.711863 | rec=0.079956 | mgcl=7.631907 | cluster=2.944541 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 038/050 | total=7.667762 | rec=0.079377 | mgcl=7.588384 | cluster=2.944531 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 039/050 | total=7.635605 | rec=0.078867 | mgcl=7.556738 | cluster=2.944521 | spatial=0.000000 | SC=off | SNF=off | effC=9.999 | gradC=0.000e+00
epoch 040/050 | total=7.592358 | rec=0.078409 | mgcl=7.513948 | cluster=2.944512 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 041/050 | total=7.559087 | rec=0.078014 | mgcl=7.481073 | cluster=2.944503 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 042/050 | total=7.519346 | rec=0.077688 | mgcl=7.441658 | cluster=2.944495 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 043/050 | total=7.488370 | rec=0.077418 | mgcl=7.410952 | cluster=2.944487 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 044/050 | total=7.452911 | rec=0.077184 | mgcl=7.375727 | cluster=2.944479 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 045/050 | total=7.423848 | rec=0.076981 | mgcl=7.346867 | cluster=2.944473 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 046/050 | total=7.395728 | rec=0.076811 | mgcl=7.318916 | cluster=2.944467 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 047/050 | total=7.368005 | rec=0.076664 | mgcl=7.291340 | cluster=2.944462 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 048/050 | total=7.345252 | rec=0.076524 | mgcl=7.268728 | cluster=2.944458 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 049/050 | total=7.321245 | rec=0.076385 | mgcl=7.244860 | cluster=2.944454 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
epoch 050/050 | total=7.302284 | rec=0.076248 | mgcl=7.226037 | cluster=2.944452 | spatial=0.000000 | SC=off | SNF=off | effC=10.000 | gradC=0.000e+00
ARI=0.049604 | NMI=0.096936
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml

/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(

| λ_cluster |        ARI |        NMI |
| --------: | ---------: | ---------: |
|         0 |     0.0496 |     0.0969 |
|   **0.1** | **0.2894** | **0.3539** |
|       0.5 |     0.2840 |     0.3523 |
|         5 |     0.2808 |     0.3516 |

cell j：Spatial 空间机制消融实验：diag_fine32_spatial，λ_cluster=0

In [20]:
%%bash
cd /content/SpaMGCL/SpaMGCL
python - <<'PY'
import yaml
with open("configs/diagnostic_hlna1_fine32.yaml") as f:
    base = yaml.safe_load(f)
cfg = yaml.safe_load(yaml.safe_dump(base))
cfg["experiment"]["name"] = "diag_fine32_spatial"
cfg["loss"]["lambda_cluster"] = 1.0
cfg["loss"]["lambda_spatial"] = 0.1
cfg["spatial"] = {
    "enabled": True,
    "consistency_weighting": True,
    "negative_filter": False   # 先只加 SC，SNF 保持关闭
}
cfg["training"]["spatial_start_epoch"] = 11
cfg["output"]["dir"] = "results/diag_fine32_spatial/"
with open("configs/diag_fine32_spatial.yaml", "w") as f:
    yaml.dump(cfg, f, default_flow_style=False)
print("✅ 生成 diag_fine32_spatial.yaml")
PY

python experiments/run_exp.py --config configs/diag_fine32_spatial.yaml

✅ 生成 diag_fine32_spatial.yaml
Dataset: HLN-A1 | spots=3484 | device=cuda
Modalities: RNA, ADT | label=Spatial_Label
Spatial graph: shape=(3484, 3484), nnz=13206
Learning rates: backbone=0.001 | cluster_head=0.008 (8x)
epoch 001/050 | total=8.411675 | rec=0.252383 | mgcl=8.159292 | cluster=2.951158 | spatial=0.000000 | SC=on | SNF=off | effC=9.950 | gradC=0.000e+00
epoch 002/050 | total=8.400130 | rec=0.242313 | mgcl=8.157817 | cluster=2.950293 | spatial=0.000000 | SC=on | SNF=off | effC=9.956 | gradC=0.000e+00
epoch 003/050 | total=8.389495 | rec=0.232628 | mgcl=8.156867 | cluster=2.949508 | spatial=0.000000 | SC=on | SNF=off | effC=9.962 | gradC=0.000e+00
epoch 004/050 | total=8.379530 | rec=0.223314 | mgcl=8.156216 | cluster=2.948801 | spatial=0.000000 | SC=on | SNF=off | effC=9.967 | gradC=0.000e+00
epoch 005/050 | total=8.370091 | rec=0.214360 | mgcl=8.155732 | cluster=2.948162 | spatial=0.000000 | SC=on | SNF=off | effC=9.972 | gradC=0.000e+00
epoch 006/050 | total=8.361095 | rec=0.205753 | mgcl=8.155343 | cluster=2.947582 | spatial=0.000000 | SC=on | SNF=off | effC=9.976 | gradC=0.000e+00
epoch 007/050 | total=8.352468 | rec=0.197477 | mgcl=8.154991 | cluster=2.947062 | spatial=0.000000 | SC=on | SNF=off | effC=9.980 | gradC=0.000e+00
epoch 008/050 | total=8.344153 | rec=0.189517 | mgcl=8.154636 | cluster=2.946602 | spatial=0.000000 | SC=on | SNF=off | effC=9.983 | gradC=0.000e+00
epoch 009/050 | total=8.336102 | rec=0.181857 | mgcl=8.154244 | cluster=2.946202 | spatial=0.000000 | SC=on | SNF=off | effC=9.987 | gradC=0.000e+00
epoch 010/050 | total=8.328271 | rec=0.174488 | mgcl=8.153783 | cluster=2.945862 | spatial=0.000000 | SC=on | SNF=off | effC=9.989 | gradC=0.000e+00
epoch 011/050 | total=11.268628 | rec=0.167403 | mgcl=8.153218 | cluster=2.945576 | spatial=0.024308 | SC=on | SNF=off | effC=9.991 | gradC=1.395e-02
epoch 012/050 | total=11.260962 | rec=0.160597 | mgcl=8.152576 | cluster=2.945222 | spatial=0.025651 | SC=on | SNF=off | effC=9.994 | gradC=1.141e-02
epoch 013/050 | total=11.253464 | rec=0.154065 | mgcl=8.151834 | cluster=2.944871 | spatial=0.026932 | SC=on | SNF=off | effC=9.997 | gradC=8.132e-03
epoch 014/050 | total=11.246218 | rec=0.147802 | mgcl=8.150948 | cluster=2.944626 | spatial=0.028423 | SC=on | SNF=off | effC=9.999 | gradC=4.694e-03
epoch 015/050 | total=11.239224 | rec=0.141805 | mgcl=8.149857 | cluster=2.944522 | spatial=0.030413 | SC=on | SNF=off | effC=10.000 | gradC=2.406e-03
epoch 016/050 | total=11.232390 | rec=0.136068 | mgcl=8.148470 | cluster=2.944537 | spatial=0.033152 | SC=on | SNF=off | effC=10.000 | gradC=3.575e-03
epoch 017/050 | total=11.225561 | rec=0.130593 | mgcl=8.146665 | cluster=2.944611 | spatial=0.036933 | SC=on | SNF=off | effC=9.999 | gradC=5.481e-03
epoch 018/050 | total=11.218531 | rec=0.125381 | mgcl=8.144264 | cluster=2.944676 | spatial=0.042098 | SC=on | SNF=off | effC=9.998 | gradC=6.642e-03
epoch 019/050 | total=11.211101 | rec=0.120435 | mgcl=8.141059 | cluster=2.944694 | spatial=0.049123 | SC=on | SNF=off | effC=9.998 | gradC=6.899e-03
epoch 020/050 | total=11.203058 | rec=0.115764 | mgcl=8.136765 | cluster=2.944665 | spatial=0.058638 | SC=on | SNF=off | effC=9.998 | gradC=6.410e-03
epoch 021/050 | total=11.194120 | rec=0.111372 | mgcl=8.130997 | cluster=2.944611 | spatial=0.071415 | SC=on | SNF=off | effC=9.999 | gradC=5.438e-03
epoch 022/050 | total=11.183957 | rec=0.107267 | mgcl=8.123290 | cluster=2.944555 | spatial=0.088451 | SC=on | SNF=off | effC=9.999 | gradC=4.278e-03
epoch 023/050 | total=11.172174 | rec=0.103456 | mgcl=8.113110 | cluster=2.944512 | spatial=0.110971 | SC=on | SNF=off | effC=10.000 | gradC=3.250e-03
epoch 024/050 | total=11.158285 | rec=0.099942 | mgcl=8.099805 | cluster=2.944484 | spatial=0.140537 | SC=on | SNF=off | effC=10.000 | gradC=2.683e-03
epoch 025/050 | total=11.141842 | rec=0.096726 | mgcl=8.082736 | cluster=2.944465 | spatial=0.179142 | SC=on | SNF=off | effC=10.000 | gradC=2.657e-03
epoch 026/050 | total=11.122510 | rec=0.093806 | mgcl=8.061362 | cluster=2.944445 | spatial=0.228971 | SC=on | SNF=off | effC=10.000 | gradC=2.876e-03
epoch 027/050 | total=11.100168 | rec=0.091177 | mgcl=8.035511 | cluster=2.944417 | spatial=0.290635 | SC=on | SNF=off | effC=10.000 | gradC=3.049e-03
epoch 028/050 | total=11.074830 | rec=0.088828 | mgcl=8.005429 | cluster=2.944375 | spatial=0.361977 | SC=on | SNF=off | effC=10.000 | gradC=3.076e-03
epoch 029/050 | total=11.046700 | rec=0.086738 | mgcl=7.971935 | cluster=2.944316 | spatial=0.437120 | SC=on | SNF=off | effC=10.000 | gradC=2.987e-03
epoch 030/050 | total=11.015086 | rec=0.084882 | mgcl=7.934949 | cluster=2.944237 | spatial=0.510176 | SC=on | SNF=off | effC=10.000 | gradC=2.863e-03
epoch 031/050 | total=10.979733 | rec=0.083242 | mgcl=7.895335 | cluster=2.944133 | spatial=0.570233 | SC=on | SNF=off | effC=10.000 | gradC=2.774e-03
epoch 032/050 | total=10.941600 | rec=0.081795 | mgcl=7.853903 | cluster=2.943998 | spatial=0.619040 | SC=on | SNF=off | effC=10.000 | gradC=2.779e-03
epoch 033/050 | total=10.903594 | rec=0.080522 | mgcl=7.812616 | cluster=2.943820 | spatial=0.666361 | SC=on | SNF=off | effC=10.000 | gradC=2.929e-03
epoch 034/050 | total=10.867968 | rec=0.079411 | mgcl=7.772991 | cluster=2.943586 | spatial=0.719794 | SC=on | SNF=off | effC=10.000 | gradC=3.273e-03
epoch 035/050 | total=10.837080 | rec=0.078425 | mgcl=7.736535 | cluster=2.943276 | spatial=0.788445 | SC=on | SNF=off | effC=10.000 | gradC=3.815e-03
epoch 036/050 | total=10.809662 | rec=0.077567 | mgcl=7.705714 | cluster=2.942871 | spatial=0.835108 | SC=on | SNF=off | effC=10.000 | gradC=4.519e-03
epoch 037/050 | total=10.773962 | rec=0.076785 | mgcl=7.667477 | cluster=2.942349 | spatial=0.873496 | SC=on | SNF=off | effC=10.000 | gradC=5.312e-03
epoch 038/050 | total=10.745465 | rec=0.076087 | mgcl=7.636614 | cluster=2.941670 | spatial=0.910934 | SC=on | SNF=off | effC=10.000 | gradC=6.231e-03
epoch 039/050 | total=10.714671 | rec=0.075484 | mgcl=7.604107 | cluster=2.940800 | spatial=0.942793 | SC=on | SNF=off | effC=10.000 | gradC=7.276e-03
epoch 040/050 | total=10.682653 | rec=0.074948 | mgcl=7.570623 | cluster=2.939708 | spatial=0.973736 | SC=on | SNF=off | effC=10.000 | gradC=8.425e-03
epoch 041/050 | total=10.651847 | rec=0.074465 | mgcl=7.537672 | cluster=2.938364 | spatial=1.013457 | SC=on | SNF=off | effC=10.000 | gradC=9.704e-03
epoch 042/050 | total=10.619655 | rec=0.074044 | mgcl=7.504076 | cluster=2.936711 | spatial=1.048240 | SC=on | SNF=off | effC=10.000 | gradC=1.113e-02
epoch 043/050 | total=10.586946 | rec=0.073690 | mgcl=7.471788 | cluster=2.934694 | spatial=1.067734 | SC=on | SNF=off | effC=10.000 | gradC=1.267e-02
epoch 044/050 | total=10.553241 | rec=0.073391 | mgcl=7.438935 | cluster=2.932304 | spatial=1.086099 | SC=on | SNF=off | effC=10.000 | gradC=1.428e-02
epoch 045/050 | total=10.521585 | rec=0.073143 | mgcl=7.408020 | cluster=2.929502 | spatial=1.109211 | SC=on | SNF=off | effC=10.000 | gradC=1.595e-02
epoch 046/050 | total=10.488417 | rec=0.072952 | mgcl=7.375593 | cluster=2.926173 | spatial=1.136994 | SC=on | SNF=off | effC=10.000 | gradC=1.774e-02
epoch 047/050 | total=10.458325 | rec=0.072810 | mgcl=7.346677 | cluster=2.922263 | spatial=1.165751 | SC=on | SNF=off | effC=10.000 | gradC=1.966e-02
epoch 048/050 | total=10.427717 | rec=0.072696 | mgcl=7.318817 | cluster=2.917757 | spatial=1.184485 | SC=on | SNF=off | effC=10.000 | gradC=2.167e-02
epoch 049/050 | total=10.398988 | rec=0.072607 | mgcl=7.294948 | cluster=2.912572 | spatial=1.188611 | SC=on | SNF=off | effC=10.000 | gradC=2.379e-02
epoch 050/050 | total=10.370482 | rec=0.072543 | mgcl=7.273094 | cluster=2.906605 | spatial=1.182391 | SC=on | SNF=off | effC=10.000 | gradC=2.611e-02
ARI=0.281912 | NMI=0.344025
Saved metrics: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/metrics.json
Saved config copy: /content/SpaMGCL/SpaMGCL/results/diagnostic_hlna1_fine32/config.yaml

/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/src/data/dataset.py:191: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  adatas = {modality: anndata.read_h5ad(path) for modality, path in paths.items()}
/content/SpaMGCL/SpaMGCL/experiments/run_exp.py:101: UserWarning: Sparse invariant checks are implicitly disabled. Memory errors (e.g. SEGFAULT) will occur when operating on a sparse tensor which violates the invariants, but checks incur performance overhead. To silence this warning, explicitly opt in or out. See `torch.sparse.check_sparse_tensor_invariants.__doc__` for guidance.  (Triggered internally at /pytorch/aten/src/ATen/Context.cpp:760.)
  return torch.sparse_coo_tensor(